### DISCUSSION TITLE
[Support]: Video playback not working in Firefox, no errors in console

### DISCUSSION THREAD

**Discussion by maples3** [blakeblackshear/frigate#16652] [General Support] [answered]
### Describe the problem you are having

Video playback in the Review section is not working on my local Frigate install.  The low-resolution preview shows, and I can scrub through it via the timeline on the right, but any timestamp I go to, I get a spinner icon that never loads.  The real-time playback also works just fine.

This behavior only happens in Firefox, I installed Google Chrome to test and Chrome seemed to work without issue.

I opened the [Frigate demo](https://demo.frigate.video/review), and Firefox is able to play back recordings there without issue.  So there's something problematic about my specific setup.

There are no errors visible in the Firefox javascript console, not even a `.log()` or `.warn()`.  It looks like it's simply not making the HTTP requests for the video.

I saw [this issue](https://github.com/blakeblackshear/frigate/discussions/12704) but wasn't able to get any further debugging, other than noting that I do see the m3u8 playlist being requested in the Firefox network tab.

I am using the out-of-the-box self-signed certificate, which Firefox complains about and requires clicking the "Accept risk and continue" button, but I can't imagine that's blocking just the HLS playback when the real-time feeds work without issue.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox 135.0 (64-bit) on Ubuntu (non-Snap version)

### Frigate config file

```yaml
version: 0.15-1

# https://github.com/blakeblackshear/frigate/issues/3213#issuecomment-1126629669

mqtt:
  enabled: false

cameras:
  sitting_room:
    ffmpeg:
      hwaccel_args: -hwaccel cuvid
      inputs:
        - path: /dev/video_builtin
          input_args: -f v4l2 -video_size 1280x720 -format mjpeg
          roles:
            - detect
            - record

      output_args:
        record: -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format
          mp4 -reset_timestamps 1 -strftime 1 -an

    detect:
      enabled: true
      width: 1280
      height: 720

    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true
  ext_1:
    ffmpeg:
      hwaccel_args: -hwaccel cuvid
      inputs:
        - path: /dev/video_2E
          input_args: -f v4l2 -video_size 1280x960 -format mjpeg
          roles:
            - detect
            - record

      output_args:
        record: -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format
          mp4 -reset_timestamps 1 -strftime 1 -an

    detect:
      enabled: true

  ext_2:
    ffmpeg:
      hwaccel_args: -hwaccel cuvid
      inputs:
        - path: /dev/video_9E
          input_args: -f v4l2
          roles:
            - detect
            - record

      output_args:
        record: -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format
          mp4 -reset_timestamps 1 -strftime 1 -an

    detect:
      height: 720

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  ext_3:
    ffmpeg:
      hwaccel_args: -hwaccel cuvid
      inputs:
        - path: /dev/video_6C
          input_args: -f v4l2
          roles:
            - detect
            - record

      output_args:
        record: -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format
          mp4 -reset_timestamps 1 -strftime 1 -an

    detect:
      enabled: true

    motion:
      threshold: 35
      contour_area: 20
      improve_contrast: true
      mask: 0.774,0.13,0.77,0.014,0.891,0.017,0.896,0.14

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320



        #detectors:
        #ov:
        #type: openvino
        #device: AUTO

      #model:
      #width: 300
      #height: 300
      #input_tensor: nhwc
      #input_pixel_format: bgr
      #path: /openvino-model/ssdlite_mobilenet_v2.xml
      #labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant Frigate log output

```shell
No visible errors.  Here's the full output of `docker logs frigate`, starting from when I click on a thumbnail on the review page:


2025-02-17 23:12:10.775694509  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /api/logs/nginx?start=10303 HTTP/1.1" 200 281 "https://192.168.0.67:8971/logs" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.792631188  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /api/config HTTP/1.1" 200 21226 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.793748556  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /api/profile HTTP/1.1" 200 20 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.796112362  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /api/preview/all/start/1739746800/end/1739836800 HTTP/1.1" 200 12551 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.798932343  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /api/review/summary?timezone=America%2FNew_York HTTP/1.1" 200 321 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.882503238  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "POST /api/reviews/viewed HTTP/1.1" 200 52 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.908974863  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /clips/previews/ext_3/1739829600.00742-1739833200.196022.mp4 HTTP/1.1" 206 3173443 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.961645698  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /vod/ext_3/start/1739829600/end/1739833200/master.m3u8 HTTP/1.1" 200 154 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.968339771  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /api/ext_3/recordings?before=1739833200&after=1739829600 HTTP/1.1" 200 55325 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:10.970834212  192.168.0.106 - - [17/Feb/2025:23:12:10 +0000] "GET /clips/previews/ext_3/1739829600.00742-1739833200.196022.mp4 HTTP/1.1" 206 961973 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:11.242986157  192.168.0.106 - - [17/Feb/2025:23:12:11 +0000] "GET /api/review/activity/motion?before=1739833924&after=1739747524&scale=15&cameras=ext_3 HTTP/1.1" 200 270671 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:11.299629759  192.168.0.106 - - [17/Feb/2025:23:12:11 +0000] "GET /clips/previews/ext_1/1739829600.04918-1739833200.008684.mp4 HTTP/1.1" 206 2068826 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:11.375289613  192.168.0.106 - - [17/Feb/2025:23:12:11 +0000] "GET /clips/previews/sitting_room/1739829600.128677-1739833200.050209.mp4 HTTP/1.1" 206 3636717 "https://192.168.0.67:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
2025-02-17 23:12:16.817756767  192.168.0.106 - - [17/Feb/2025:23:12:16 +0000] "GET /api/logs/nginx?start=10304 HTTP/1.1" 200 3570 "https://192.168.0.67:8971/logs" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0" "-"
```

### Relevant go2rtc log output

```shell
Not using go2rtc
```

### FFprobe output from your camera

```shell
ffmpeg executed from host, not from within Docker.  ffprobe doesn't seem to work with v4l, so here's ffmpeg with list_formats:

anthony@sentry:~$ ffmpeg -f v4l2 -list_formats all -i /dev/v4l/by-id/usb-046d_0825_2EE0F7C0-video-index0 
ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[video4linux2,v4l2 @ 0x55ee3ebc3880] Raw       :     yuyv422 :           YUYV 4:2:2 : 640x480 160x120 176x144 320x176 320x240 352x288 432x240 544x288 640x360 752x416 800x448 800x600 864x480 960x544 960x720 1024x576 1184x656 1280x720 1280x960
[video4linux2,v4l2 @ 0x55ee3ebc3880] Compressed:       mjpeg :          Motion-JPEG : 640x480 160x120 176x144 320x176 320x240 352x288 432x240 544x288 640x360 752x416 800x448 800x600 864x480 960x544 960x720 1024x576 1184x656 1280x720 1280x960
/dev/v4l/by-id/usb-046d_0825_2EE0F7C0-video-index0: Immediate exit requested
```

### Frigate stats

```json
{
  "cameras": {
    "sitting_room": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 0.1,
      "detection_enabled": true,
      "pid": 475,
      "capture_pid": 489,
      "ffmpeg_pid": 498,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "ext_1": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 0,
      "detection_enabled": true,
      "pid": 478,
      "capture_pid": 513,
      "ffmpeg_pid": 517,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "ext_2": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 2.8,
      "detection_enabled": true,
      "pid": 481,
      "capture_pid": 516,
      "ffmpeg_pid": 520,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "ext_3": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 0,
      "detection_enabled": true,
      "pid": 483,
      "capture_pid": 525,
      "ffmpeg_pid": 540,
      "audio_rms": 0,
      "audio_dBFS": 0
    }
  },
  "detectors": {
    "tensorrt": {
      "inference_speed": 26.85,
      "detection_start": 1739833994.213976,
      "pid": 444
    }
  },
  "detection_fps": 2.9,
  "gpu_usages": {
    "NVIDIA GeForce GTX 1050": {
      "gpu": "19.0%",
      "mem": "14.81%",
      "enc": "6.0%",
      "dec": "0.0%"
    }
  },
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
    },
    "15": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6-linux-init-shutdownd"
    },
    "16": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
    },
    "24": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync"
    },
    "25": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-healthcheck"
    },
    "26": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-fdholder"
    },
    "27": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate-log"
    },
    "28": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate"
    },
    "29": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc"
    },
    "30": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx-log"
    },
    "31": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx"
    },
    "32": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-oneshot-runner"
    },
    "33": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-log"
    },
    "34": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync-log"
    },
    "45": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
    },
    "46": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
    },
    "94": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
    },
    "97": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
    },
    "98": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
    },
    "99": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
    },
    "107": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
    },
    "115": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user go2rtc-healthcheck"
    },
    "116": {
      "cpu": "4.3",
      "cpu_average": "4",
      "mem": "3.2",
      "cmdline": "python3 -u -m frigate"
    },
    "132": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: master process nginx"
    },
    "173": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "nginx: worker process"
    },
    "174": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "nginx: worker process"
    },
    "175": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "nginx: worker process"
    },
    "176": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "nginx: worker process"
    },
    "177": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: cache manager process"
    },
    "310": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user certsync"
    },
    "428": {
      "cpu": "1.3",
      "cpu_average": "1",
      "mem": "1.7",
      "cmdline": "frigate.recording_manager"
    },
    "434": {
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "1.5",
      "cmdline": "frigate.review_segment_manager"
    },
    "444": {
      "cpu": "6.1",
      "cpu_average": "5",
      "mem": "3.2",
      "cmdline": "frigate.detector.tensorrt"
    },
    "459": {
      "cpu": "2.3",
      "cpu_average": "3",
      "mem": "1.6",
      "cmdline": "frigate.output       "
    },
    "475": {
      "cpu": "2.8",
      "cpu_average": "3",
      "mem": "1.7",
      "cmdline": "frigate.process:sitting_room"
    },
    "478": {
      "cpu": "1.8",
      "cpu_average": "2",
      "mem": "1.5",
      "cmdline": "frigate.process:ext_1"
    },
    "481": {
      "cpu": "10.3",
      "cpu_average": "6",
      "mem": "1.5",
      "cmdline": "frigate.process:ext_2"
    },
    "483": {
      "cpu": "2.3",
      "cpu_average": "3",
      "mem": "1.5",
      "cmdline": "frigate.process:ext_3"
    },
    "489": {
      "cpu": "2.3",
      "cpu_average": "2",
      "mem": "1.5",
      "cmdline": "frigate.capture:sitting_room"
    },
    "498": {
      "cpu": "22.4",
      "cpu_average": "22",
      "mem": "1.7",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuvid -f v4l2 -video_size 1280x720 -format mjpeg -i /dev/video_builtin -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an /tmp/cache/sitting_room@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "513": {
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "1.4",
      "cmdline": "frigate.capture:ext_1"
    },
    "516": {
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "1.4",
      "cmdline": "frigate.capture:ext_2"
    },
    "517": {
      "cpu": "18.6",
      "cpu_average": "21",
      "mem": "1.8",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuvid -f v4l2 -video_size 1280x960 -format mjpeg -i /dev/video_2E -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an /tmp/cache/ext_1@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "520": {
      "cpu": "23.7",
      "cpu_average": "19",
      "mem": "1.3",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuvid -f v4l2 -i /dev/video_9E -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an /tmp/cache/ext_2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "524": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "525": {
      "cpu": "1.1",
      "cpu_average": "1",
      "mem": "1.4",
      "cmdline": "frigate.capture:ext_3"
    },
    "539": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "540": {
      "cpu": "23.8",
      "cpu_average": "20",
      "mem": "1.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuvid -f v4l2 -i /dev/video_6C -c:v h264_nvenc -preset p2 -tune hq -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an /tmp/cache/ext_3@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "548": {
      "cpu": "0.0",
      "cpu_average": "1",
      "mem": "0.3",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "555": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "562": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "239090": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 60"
    },
    "239123": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 30s"
    },
    "frigate.full_system": {
      "cpu": "17.1",
      "mem": "19.4"
    }
  },
  "service": {
    "uptime": 62297,
    "version": "0.15.0-cea210d",
    "latest_version": "0.15.0",
    "storage": {
      "/media/frigate/recordings": {
        "total": 960330.4,
        "used": 65617.6,
        "free": 845858.7,
        "mount_type": "ext4"
      },
      "/media/frigate/clips": {
        "total": 960330.4,
        "used": 65617.6,
        "free": 845858.7,
        "mount_type": "ext4"
      },
      "/tmp/cache": {
        "total": 953.7,
        "used": 18.1,
        "free": 935.6,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 1024,
        "used": 137.2,
        "free": 886.8,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {},
    "last_updated": 1739833994
  },
  "processes": {
    "recording": {
      "pid": 428
    },
    "review_segment": {
      "pid": 434
    },
    "go2rtc": {
      "pid": 107
    }
  }
}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "1024mb" # 128mb is enough for two 720p streams according to docs
    devices:
      - /dev/v4l/by-id/usb-Chicony_Electronics_Co._Ltd._USB2.0_HD_UVC_WebCam_0x0001-video-index0:/dev/video_builtin
      - /dev/v4l/by-id/usb-046d_0825_2EE0F7C0-video-index0:/dev/video_2E
      - /dev/v4l/by-id/usb-046d_0825_9EAA03E0-video-index0:/dev/video_9E
      - /dev/v4l/by-id/usb-046d_C270_HD_WEBCAM_6C843F90-video-index0:/dev/video_6C

    volumes:
      - /mnt/1tb/frigate/config:/config
      - /mnt/1tb/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      YOLO_MODELS: yolov7-320,yolov7x-640
      USE_FP16: false

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```

### Object Detector

TensorRT

### Network connection

Wireless

### Camera make and model

Logitech C720 (USB via ffmpeg and v4l2)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/bdd6af36-9933-450c-9887-bcf08dfaf06d)

### Any other information that may be helpful

I found [this issue](https://github.com/blakeblackshear/frigate/discussions/13514) which discussed mjpeg cameras (which is the format supplied by the USB cameras, from what I can tell), but in the `cameras` section of the config, I'm using `output_args` to encode to h264 via nvenc.  I kept getting errors if I tried the same thing with the detect stream, and detection seems to work just fine with the current config, so I have not supplied `output_args` for the detect stream.
