### DISCUSSION TITLE
Guide: Deploying Frigate (Docker) with Coral TPU USB on Ubuntu 24.04 or Above (VMware ESXi)

### DISCUSSION THREAD

**Discussion by IncognitoCoding** [blakeblackshear/frigate#16650] [Show and tell]
# Guide: Deploying Frigate (Docker) with Coral TPU USB on Ubuntu 24.04 or Above (VMware ESXi)

## Overview
Frigate strongly recommends the Google Coral TPU for accelerating object detection, and while it can be a game changer, setting it up is anything but straightforward depending on how you are piecing everything together. The process is often derailed by outdated instructions, conflicting guidance for different environments (e.g., Docker vs. non-Docker, VMware vs. Hyper-V, or Raspberry Pi), and compatibility issues like outdated Python dependencies.

This guide provides a clear, tested approach to getting the Coral TPU working inside Docker on the latest supported Ubuntu OS running on VMware ESXi, while avoiding unnecessary software installations and common pitfalls. It focuses on the essential steps to get the Coral TPU functioning with Frigate NVR, and does not cover advanced configurations beyond the high-level basic setup.

While tailored for this setup, many insights and solutions provided here may also help users on other hypervisors or operating systems resolve similar challenges.

## 🛑 Important Considerations Before You Begin
- **No Coral TPU drivers or software are required on the Ubuntu host.** Frigate's Docker container includes everything necessary to utilize the Coral TPU. Installing Coral drivers or TPU libraries on the host can cause conflicts and unnecessary troubleshooting.  
- **Google’s Coral TPU development appears stagnant.** The official Coral website has had no updates since 2022, raising concerns about long-term support.  
  - A notable issue is the TPU's dependency on outdated Python versions, which complicates compatibility with modern operating systems.  
- **Frigate currently uses a Docker container (Debian 11)** *(as of 2/17/2025)* that still supports the Coral TPU's required python version, but **Debian 11 reaches EOL in 2026**.  
- **Many users have abandoned Coral TPU due to these issues**, but if configured correctly, it remains **a powerful, viable option**.  
- **Direct USB Connection is Critical.** Avoid using USB hubs with the Coral TPU. Connect it directly to the motherboard for stable performance. I experienced crashes using a USB hub.  
- **This guide focuses on VMware ESXi**, but some of these solutions **may apply to other hypervisors (Proxmox, Hyper-V, etc.)**.  
- **VMware vSphere ESXi** requires additional steps for proper USB passthrough and device recognition.  
---

## System Configuration Used in This Guide
| Component  | Details  |
|------------|------------------------------------------------------|
| **VM OS** | Ubuntu (20.04 [EoL Soon], 22.04, or 24.04)  |
| **Hypervisor** | VMware ESXi 7.x or 8.x  |
| **VM USB Setup** | USB device-specific passthrough, not USB controller passthrough  |
| **Frigate Deployment** | Docker Container  |
| **Docker Base OS** | Debian 11 (EOL: Aug 2026) |
| **Coral TPU Version** | USB (Not PCIe)  |

---

## 🚀 Step 1: Set Up the Ubuntu VM and Attach the Coral TPU
1. **Create your VM using a supported Ubuntu release (not EoL).**
2. **Plug your Coral TPU USB into the physical server.**
3. **Pass the Coral TPU USB device to the Ubuntu VM in ESXi.**
   - Add a **USB Controller** to the VM.
   - Add a **USB device** and select **"Host Device - Global Unichip product 0x089a"**.
4. **Add a VMware Advanced Configuration Parameter to prevent boot issues:**
   ```shell
   usb.quirks.device0 = "0x18d1:0x9302 skip-reset,skip-setconfig"
   ```
5. **Save settings**
6. **Power on** the VM.
---

### 1️⃣ Install Docker & Docker Compose on Ubuntu
```shell
sudo apt update && sudo apt install -y docker.io docker-compose
```

### 2️⃣ Create Directories for Frigate (~ is your home directory path)
```shell
mkdir -p ~/nvr/frigate/config
mkdir -p ~/nvr/frigate/recordings
mkdir -p ~/nvr/frigate/clips
mkdir -p ~/nvr/docker
```

### 3️⃣ Create `docker-compose.yml` File
```shell
cd ~/nvr/docker
nano docker-compose.yml
```

```yaml
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true
    shm_size: "768mb"
    environment:
      - TZ=US/Central
      - FRIGATE_MYCAMERA_USER=frigate
      - FRIGATE_MYCAMERA_PASSWORD=mypassword
      - FRIGATE_RTSP_USER=frigate_viewer
      - FRIGATE_RTSP_PASSWORD=mypassword
      - FRIGATE_MQTT_USER=frigate
      - FRIGATE_MQTT_PASSWORD=mypassword
    devices:
      - /dev/bus/usb:/dev/bus/usb  
    volumes:
      - ../frigate/config:/config
      - ../frigate/recordings:/media/frigate/recordings
      - ../frigate/clips:/media/frigate/clips
    ports:
      - "5000:5000"
      - "8554:8554"
    restart: always
```

### 4️⃣ Create Frigate `config.yaml` File
```shell
cd ~/nvr/frigate/config
nano config.yaml
```

```yaml
mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: []  # Check hardware for compatibility

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: True
  retain:
    default: 30

cameras:
  name_of_your_camera:
    detect:
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://<x.x.x.x>:554/rtsp
          roles:
            - detect
    motion:
      mask:
        - 0.000,0.427,0.002,0.000,0.999,0.000,0.999,0.781,0.885,0.456,0.700,0.424,0.701,0.311,0.507,0.294,0.453,0.347,0.451,0.400
```

### 5️⃣ Start Frigate
```shell
docker compose up -d
```

### 6️⃣ Check Logs
```shell
docker logs -f frigate
```
🚨 **At this stage, TPU detection will show FAILED in the logs**. This is expected.

---

### 1️⃣ Check the Coral TPU device name in Ubuntu
```shell
lsusb
```
- If it shows **`1a6e:089a Global Unichip Corp.`**, the Coral TPU **will not work**.
- The correct device name should be **`18d1:9302 Google Inc.`**.

### 2️⃣ Reload the USB Module on your ESXi host through SSH
Note: Reloading this module will temporarly disconnect all connected USB devices.
```shell
/etc/init.d/usbarbitrator stop
vmkload_mod -u vmkusb; vmkload_mod vmkusb
kill -SIGHUP $(ps -C | grep vmkdevmgr | awk '{print $1}')
/etc/init.d/usbarbitrator start
```

### 3️⃣ Re-check the Coral TPU device name in Ubuntu
```shell
lsusb
```
- The correct device name should now show **`18d1:9302 Google Inc.`**.

### 4️⃣ Restart Frigate inside Docker
```shell
cd ~/nvr/docker
docker compose restart
```

### 5️⃣ Check Frigate Logs Again
```shell
docker logs -f frigate
```
✅ If successful, you will see:
```plaintext
frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

---

## 🛑 Final Notes & Troubleshooting
-  **Noticed a 40% CPU usage decrease by adding the Coral TPU vs only using my Xeon Platinum 8260.**
- **Frigate remains a powerful solution despite Coral TPU's uncertain future.**  
- **If you unplug the Coral TPU, you may need to reload the USB module in ESXi again.**  
- **Connect Coral TPU directly into the motherboard and not through any USB hub.** (I had crash issues using a USB hub)  
- **No software installation is needed on the Ubuntu host – everything runs inside Frigate’s Docker container.**  
- **Keep your Frigate Docker container updated** to maintain compatibility with newer integrations or bug fixes.  
- **Document your quirks and configuration changes**, as VMware ESXi updates may revert settings.
- **This guide does not go into best practice configuration such as extra security or user account creation.**
---
