### DISCUSSION TITLE
[Bug]: default go2rtc ffmpeg config can lead to very old version on arm64 docker image

### DISCUSSION THREAD

**Discussion by breuxi** [blakeblackshear/frigate#16688] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

While trying to setup 2-way-audio with a new Reolink Lumus Pro and Frigate running in a podman container on a raspberry pi 4 4gb running nixos, I came across the fact that transcoding audio for use with WebRTC using the bundled go2rtc will simply not work and also apparently not throw any errors. When you also transcode the video stream, suddenly the line `WRN [rtsp] error="streams: ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1" stream=reolink_lumus` appears in the logs. If you add the ffmpeg 7.0 path manually to config.yaml.
```
go2rtc: 
  ffmpeg:
    bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg
```
Everthing works again. I think this is caused by the way how frigate handles the default ffmpeg config for itself and g2rtc always checking if there is a version installed by the operating system. Which will as debian is the base image, always be quite old.
https://github.com/blakeblackshear/frigate/blob/0083d09a8b78c20e23bc80e9adf9e74506e863f3/docker/main/rootfs/usr/local/ffmpeg/get_ffmpeg_path.py#L36-L45
https://github.com/blakeblackshear/frigate/blob/0083d09a8b78c20e23bc80e9adf9e74506e863f3/docker/main/rootfs/usr/local/go2rtc/create_config.py#L115-L125

I would recommend to default to the bundled versions to achieve some consistency (as they are also already there, I don't know if thats always the case, but you will know I suppose). Or at least mention that in the docs as it took me two full days to debug this case, and I would love for people not to have to go that road! :)

### Steps to reproduce

1. Install frigate using docker (or in my case podman) on a arm64 machine
2. Setup webrtc and transcoding for a reolink lumus pro camera (or any camera with this specs)
```
Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2560x1440, 25 fps, 50 tbr, 90k tbn
Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```
```
go2rtc:
  streams:
    reolink_lumus:
      - "rtsp://<user>:<password>@<ip>/h264Preview_01_main"
      - "ffmpeg:reolink_lumus#audio=opus"
    reolink_lumus_sub:
      - "rtsp://<user>:<password>@<ip>/h264Preview_01_sub"
      - "ffmpeg:reolink_lumus_sub#audio=opus"
    webrtc:
       candidates:
          - <host ip>:8555
          - stun:8555
```
3. It wont work and you wont get an error
4. Change to this and you will find  `WRN [rtsp] error="streams: ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1" stream=reolink_lumus` in the logs
```
go2rtc:
  streams:
    reolink_lumus:
      - "ffmpeg:rtsp://<user>:<password>@<ip>/h264Preview_01_main"
      - "ffmpeg:reolink_lumus#audio=opus"
    reolink_lumus_sub:
      - "ffmpeg:rtsp://<user>:<password>@<ip>/h264Preview_01_sub"
      - "ffmpeg:reolink_lumus_sub#audio=opus"
    webrtc:
       candidates:
          - <host_ip>:8555
          - stun:8555
```
6. Change to this and it will work
```
go2rtc:
  ffmpeg:
    bin: /usr/lib/ffmpeg/7.0/bin/ffmpeg
  streams:
    reolink_lumus:
      - "rtsp://<user>:<password>@<ip>/h264Preview_01_main"
      - "ffmpeg:reolink_lumus#audio=opus"
    reolink_lumus_sub:
      - "rtsp://<user>:<password>@<ip>/h264Preview_01_sub"
      - "ffmpeg:reolink_lumus_sub#audio=opus"
    webrtc:
       candidates:
          - <host ip>:8555
          - stun:8555 
```
...

### Version

0.15.0-cea210d

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

go2rtc:
  streams:
    reolink_lumus:
      - "rtsp://<user>:<password>@<ip>/h264Preview_01_main"
      - "ffmpeg:reolink_lumus#audio=opus"
    reolink_lumus_sub:
      - "rtsp://<user>:<password>@<ip>/h264Preview_01_sub"
      - "ffmpeg:reolink_lumus_sub#audio=opus"
    webrtc:
       candidates:
          - <host ip>:8555
          - stun:8555
```

### docker-compose file or Docker CLI command

```yaml
Off topic.
```

### Relevant Frigate log output

```shell
There is none.
```

### Relevant go2rtc log output

```shell
WRN [rtsp] error="streams: ffmpeg: unsupported version: 4.3.8-0+deb11u1+rpt1"
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Reolink Lumus Pro

### Screenshots of the Frigate UI's System metrics pages

![firefox_uGXbrtPnp1](https://github.com/user-attachments/assets/59372aaf-a551-48c3-8cb6-4af47dcdce0c)
![firefox_EDLYYObqsJ](https://github.com/user-attachments/assets/f80a3d58-7cbc-4ada-a90d-91d3660fbc78)
![firefox_9ZsPZcGRPv](https://github.com/user-attachments/assets/34056fca-0ad3-4c43-a2b4-57e513b063a6)
