### DISCUSSION TITLE
[Detector Support]: model training without frigate+

### DISCUSSION THREAD

**Discussion by crazych1** [blakeblackshear/frigate#16681] [Detector Support]
### Describe the problem you are having

I live in a cold climate, but my cat goes outside all the time, I have a system that opens and closes the door for the cat, but I have a problem recognizing the cat at the door to trigger the trigger, I know that there is a training system based on firigate+, but unfortunately I do not have the financial ability to pay for a subscription, but physically because it is not possible to pay with a card to other countries. My question is, is there an alternative way to train frigate to recognize my cat at the door? I'm currently using the YOLOv7 model in conjunction with the nvidia adapter,
but as it turns out, it doesn't detect the cat well, the camera detects movement perfectly, circles the cat with a red square, but does not recognize it as a cat.

### Version

0.15beta2

### Frigate config file

```yaml
home_enter:
    detect:
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://@172.16.1.221:554/Streaming/Channels/101 # <--- the name here must match the name of the camera in restream
          #input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: home_enter
    motion:
      threshold: 19
      contour_area: 7
      improve_contrast: true
      mask: 0.034,0,0.037,0.035,0.337,0.033,0.338,0
    zones:
      detect:
        coordinates: 
          0,1,0,0.037,0.344,0.04,0.343,0,0.825,0,0.715,0.463,0.734,0.574,0.795,0.58,0.998,0.288,0.998,0.926,0.817,0.859,0.702,0.915,0.528,0.931,0.2,0.886,0.084,0.891
        loitering_time: 0
        inertia: 3
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
          max_area: 200000
        dog:
          min_score: 0.3
          threshold: 0.5
          max_area: 200000
    review:
      alerts: {}
      detections:
        required_zones: detect
```

### docker-compose file or Docker CLI command

```yaml
none
```

### Relevant Frigate log output

```shell
none
```

### Install method

Docker CLI

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

none

**Comment by daoudeddy** [comment]
I heard that the current dev branch supports the yolov9 model, if you have the time to check it out

**Comment by crazych1** [comment]
if you can tell me detailed instructions on where to download, how to install, and how to make it work on my installation, I'll be happy to do it. Because it doesn't work out of the box, as I understand it.

**Reply by daoudeddy** [reply]
I have never worked with nvidia tbh 
```
detectors:
  onnx:
    type: onnx

model:
  model_type: yolov9
  width: 640 # <--- should match the imgsize set during model export
  height: 640 # <--- should match the imgsize set during model export
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-t.onnx
  labelmap_path: /labelmap/coco-80.txt
  ```
maybe test some of the models [here](https://huggingface.co/illuni/YOLOv9.onnx_v11/tree/main)
