### DISCUSSION TITLE
Support Rockchip hardware acceleration and Hailo object detection in a single Frigate instance

### DISCUSSION THREAD

**Discussion by huijizyf** [blakeblackshear/frigate#16696] [Ask A Question] [answered]
I am trying to configure Frigate to use both Rockchip hardware acceleration for FFmpeg and Hailo hardware acceleration for object detection in a single instance.

Currently:

The frigate:stable-rk image supports Rockchip hardware acceleration but does not support Hailo object detection.
The frigate:stable-h8l image supports Hailo object detection but does not support Rockchip hardware acceleration.
I would like to configure Frigate with the following settings in a single instance:

```
ffmpeg:
  hwaccel_args: preset-rk-h264

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
```

Is there a way to achieve this, or could support for this combination be added in future releases?

Thank you!
