### DISCUSSION TITLE
Does this config mean that only these sepecified objects will be detected?

### DISCUSSION THREAD

**Discussion by nabheet** [blakeblackshear/frigate#16699] [Ask A Question]
Referring to the following configuration for a zone for a camera, is this saying that only the specified objects should be detected in this zone? Other objects should be ignored? I am seeing recordings of cars , trucks and buses when they drive through this zone. Do you have any suggestions on what it might be? I can post the entire config too but didnt becuase I need to remove secrets from it.
```
front_street:
  coordinates: 0.033,0.46,0.71,0.281,0.655,0.23,0.273,0.314,0.029,0.39
  objects:
    - person
    - bird
    - dog
    - cat
  inertia: 10
  loitering_time: 3
```

**Comment by daoudeddy** [comment]
In this zone yes but in any other zones on non-specified zone all camera specific objects will be detected, means if the object is detected before entering this zone it will show as a detected object anyways, you can either create an object mask or specify these object in the camera config. another solution to add this zone to the alerts in the camera review classification settings.

**Reply by nabheet** [reply]
`specify these object in the camera config` - The difference between alert and detection is not obvious to me here. Somewhere in the doc I read that one might be loitering or something but I am not getting it. 

I think all I want is a recording when a certain object enters a zone. And ignore everything else. I am not sure how to make that happen with alerts and detections.

**Reply by nabheet** [reply]
Here is my entire config so far. There has been quite a bit of thrashing in the config as I get a better understanding.

```
# yaml-language-server: $schema=http://potter.lan:5000/api/config/schema.json

mqtt:
  host: m
  user: 
  password: 

detectors:
  # deepstack:
  #   type: deepstack
  #   api_url: http://cpai:32168/v1/vision/detection
  #   api_timeout: 15
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    front_door:
      # hevc 3840x2160
      - rtsp://
    carport:
      # hevc 1920x1080
      - rtsp://
    garage:
      # hevc 3840x2160
      - rtsp://
    patio:
      # hevc 3712x1056
      - rtsp://

cameras:
  front_door:
    birdseye:
      order: 1
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 320
      required_zones:
        - front_path
        - front_street
        - front_side_lawn
    zones:
      front_path:
        coordinates: 0.182,0.554,0.339,1,0.141,1,0.054,0.618
        objects:
          - person
          - bird
          - cat
          - dog
        inertia: 10
        loitering_time: 3
      front_street:
        coordinates: 0.033,0.46,0.71,0.281,0.655,0.23,0.273,0.314,0.029,0.39
        objects:
          - person
          - bird
          - dog
          - cat
        inertia: 10
        loitering_time: 3
      front_side_lawn:
        coordinates: 0.318,0.863,0.787,0.568,0.739,0.415,0.19,0.55
        inertia: 10
        loitering_time: 3
    review:
      alerts:
        required_zones:
          - front_path
          - front_side_lawn
      detections: {}
    motion:
      threshold: 60
      contour_area: 20
      improve_contrast: true
  carport:
    birdseye:
      order: 0
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 320
      required_zones:
        - carport_driveway
        - carport_street
    zones:
      carport_driveway:
        coordinates:
          0.36,0.372,0.765,0.512,0.673,1,0.262,1,0.264,0.804,0.343,0.598,0.233,0.494,0,0.467,0.251,0.405
        inertia: 10
        loitering_time: 3
      carport_street:
        coordinates: 1,0.484,0.993,0.347,0.298,0.249,0.298,0.301
        objects:
          - person
          - bird
          - cat
          - dog
        inertia: 10
        loitering_time: 3
    review:
      alerts:
        required_zones: carport_driveway
      detections: {}
    motion:
      threshold: 60
      contour_area: 20
      improve_contrast: true
    objects:
      filters:
        car:
          mask:
            - 0.004,0.144,0.188,0.136,0.295,0.4,0,0.5
            - 0.524,0.012,0.878,0.036,0.923,0.32,0.484,0.265
  garage:
    birdseye:
      order: 2
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 320
      required_zones:
        - garage_driveway
        - front_lawn
        - garage_street
    zones:
      garage_street:
        coordinates: 1,0.481,0,0.733,0,0.522,1,0.33
        objects:
          - bicycle
          - motorcycle
          - car
          - bus
          - truck
        inertia: 10
        loitering_time: 3
      garage_driveway:
        coordinates: 0.002,0.816,0.996,0.521,1,0.996,0.002,0.998
        inertia: 10
        loitering_time: 3
        objects:
          - dog
          - person
          - cat
          - bird
    review:
      detections: {}
      alerts:
        required_zones: garage_street
    motion:
      threshold: 60
      contour_area: 20
      improve_contrast: true
  patio:
    birdseye:
      order: 3
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          roles:
            - record
            - detect
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 320
      required_zones:
        - back_side_lawn
        - playground
        - side_patio
    zones:
      back_side_lawn:
        coordinates: 0.643,1,0.648,0.485,0.258,0.438,0.224,1
        objects:
          - person
          - bird
          - cat
          - dog
        inertia: 10
        loitering_time: 3
      playground:
        coordinates: 0.882,0.232,0.907,0.552,0.789,0.509,0.73,0.277,0.725,0
        objects:
          - person
          - bird
          - cat
          - dog
        inertia: 10
        loitering_time: 3
      side_patio:
        coordinates: 0.808,1,1,1,1,0.596,0.877,0.545
        objects:
          - person
          - bird
          - cat
          - dog
        inertia: 10
        loitering_time: 3
    motion:
      threshold: 60
      contour_area: 50
      improve_contrast: true
    review:
      alerts:
        required_zones:
          - back_side_lawn
          - playground
          - side_patio
      detections: {}
ffmpeg:
  input_args: preset-rtsp-restream
  # input_args: >-
  #   -hide_banner -loglevel warning
  #   -avoid_negative_ts make_zero -fflags
  #   +genpts+discardcorrupt -rtsp_transport tcp
  #   -timeout 5000000 -use_wallclock_as_timestamps 1
  hwaccel_args: preset-nvidia-h265

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: true
  height: 320

record:
  enabled: true

birdseye:
  enabled: true
  restream: true
  width: 640
  height: 480
  quality: 1
  mode: objects

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - bicycle
    - motorcycle
    - car
    - bus
    - truck
    - bird
    - cat
    - dog
  filters:
    person:
      min_area: 20000
    car:
      min_area: 20000
version: 0.15-1

review:
  alerts:
    labels:
      - dog
      - cat
      - bird
      - person
  detections:
    labels:
      - person
      - dog
      - car
      - bicycle
      - cat
      - motorcycle
      - bird
```

**Reply by nabheet** [reply]
I think this last config may have done the trick - I need to wait until daytime to confirm the videos.

**Reply by nabheet** [reply]
nope - it is still recording all objects from all cameras. I will close this for now and read the docs again when I have more time.

**Reply by daoudeddy** [reply]
When motion detected in the stream these motion boxes are sent to the detector, and snapshots/videos will be created if a any of the objects you selected for the camera is detected in that motion box, while zones are just zones that can help you create automation when an object is detected in that zone for example, but if you want to detect objects only in one zone you should create object mask or motion mask for the other area outside that zone, or select for example cat in zone 1 and select person in zone 2, that way you get only cat in zone 1 and only person in zone 2

Example config:

```
  office_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office_door
          roles:
            - detect
            - record
    live:
      streams:
        office_door: office_door_live
    zones:
      Front_Door:
        coordinates: 1,0.517,0.506,0.244,0,0.466,0,1,1,1
        loitering_time: 0
        objects:
          - person
          - face
          - cat
          - dog
        inertia: 3
      Side_Road:
        coordinates: 0,0.465,0,0,1,0,1,0.512,0.503,0.237
        loitering_time: 0
        inertia: 3
        objects:
          - car
          - license_plate
          - person
    motion:
      threshold: 50
      contour_area: 30
      improve_contrast: true
    review:
      detections: {}
      alerts:
        required_zones: Front_Door
    objects:
      track:
        - person
        - car
        - license_plate
        - face
        - cat
        - dog
```
