### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by Struggle2020** [blakeblackshear/frigate#16719] [Config Support] [answered]
### Describe the problem you are having

Firstly, massive thank you to the developers. This container is absolutely amazing 99% of the time.

Note: Alerts are only NUC1 and NUC2 by design NUC3 I'm still training so it's not turned on for alerts yet

The two issues are:

1. If the alerts are created often the alert won't stop and will carry on until i restart it (often hours) meaning that new alerts can't be made for some reason (see more info at bottom for timeline snapshot). Even though in the new explore tab I can see that a person has been detected in the correct zone with a 90%+ confidence score.
2. Sometimes when I click on an alert it will send me to a previous alert from a few hours ago, meaning they can be all mismatched. I think due to the above issue.

Things I've tried / noticed:

1. I think my config will be pretty crap but I've played around with setting up alerts in the UI and started fresh to see if that would help.
2. I've checked and tested read/write perms in frigate folders on ubuntu
3. I've completely removed the frigate folders (db and all) and started fresh.
4. If I restart frigate the first alert appears (though sometimes goes on for hours)
5. I've used the date command in the container exec to make sure timezone was correct.

I did set up a new router recently with a wireguard VPN but I set it up to allow the server which frigate is on to bypass it. I did have adguard home on my router too but tested it with it off and still didn't work.

I have a suspicion it's something to do with my new router or docker setup but I have no idea how to debug it in relation to frigate. This may not just be a frigate 0.15 issue as I believe I had issues before upgrading last night as I noticed my Home Assistant automation stopped working unless I reset the server but hadn't had a chance to look into it until now.

Please help me solve this, I use this as a way to alert me at night from intruders. If you need anything else at all to help debug this issue please let me know.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.68.51
  port: 1883

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://<path>

go2rtc:
  streams:
    NUC_1:
      - rtsp://admin:<pass>@192.168.68.69/Preview_01_main
      - ffmpeg:NUC_1#audio=opus
    NUC_1_Sub:
      - rtsp://admin:<pass>@192.168.68.69/Preview_01_sub
      - ffmpeg:NUC_1_Sub#audio=opus
    NUC_2:
      - rtsp://admin:<pass>@192.168.68.70/Preview_01_main
      - ffmpeg:NUC_2#audio=opus
    NUC_2_Sub:
      - rtsp://admin:<pass>@192.168.68.70/Preview_01_sub
      - ffmpeg:NUC_2_Sub#audio=opus
    NUC_3:
      - rtsp://admin:<pass>@192.168.68.82/Preview_01_main
      - ffmpeg:NUC_2#audio=opus
    NUC_3_Sub:
      - rtsp://admin:<pass>@192.168.68.82/Preview_01_sub
      - ffmpeg:NUC_2_Sub#audio=opus
    webrtc:
      candidates:
        - 192.168.68.51:8555
        - stun:8555

birdseye:
  enabled: true
  restream: true
  quality: 30
  mode: continuous
  layout:
    max_cameras: 3

snapshots:
  bounding_box: true
  enabled: true
  retain:
    default: 5
  required_zones:
    - inside_gate
    - entrance_gate
    - street
    - front_garden
    - back_garden

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects
cameras:
  NUC_1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/NUC_1 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NUC_1_Sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0.604,0.27,0.483,0.376,0.225,0.412,0.118,0.576,0.104,0.609,0.343,1,0.451,1,0,0,0
        - 0,0.913,0.436,0.913,0.436,0.978,0,0.979
      threshold: 70
      contour_area: 40
      improve_contrast: 'true'
    objects:
      track:
        - person
        - dog
        - face
        - car
    detect:
      width: 896
      height: 512
    zones:
      entrance_gate:
        coordinates: 0.436,0.619,0.705,0.432,0.662,0.43,0.435,0.588
        inertia: 3
        loitering_time: 1
      inside_gate:
        coordinates: 1,1,1,0.449,0.602,0.351,0,0.625,0,1
        inertia: 3
        loitering_time: 1
      street:
        coordinates: 0.375,0.23,0.41,0.117,0.58,0.105,0.615,0.339,0.267,0.497
        inertia: 3
        loitering_time: 1
    review:
      alerts:
        labels:
          - person
        required_zones:
          - entrance_gate
          - inside_gate
          - street
      detections:
        labels:
          - car
          - dog

  NUC_2:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/NUC_2 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NUC_2_Sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        person:
          max_area: 61200
          min_area: 5000
      track:
        - person
        - dog
        - face
    zones:
      front_garden:
        coordinates: 
          1,1,1,0.193,0.406,0.24,0.35,0.242,0.355,0.328,0.292,0.33,0.287,0.23,0.188,0.234,0.177,0.398,0.256,0.484,0.247,0.625,0.158,0.789,0.047,0.93,0,1
        objects:
          - person
          - dog
          - face
        inertia: 3
        loitering_time: 1
    motion:
      mask: 0,0.91,0.431,0.905,0.429,0.99,0.004,0.989
      threshold: 75
      contour_area: 40
      improve_contrast: 'true'
    review:
      alerts:
        required_zones:
          - front_garden
        labels:
          - person
      detections:
        labels:
          - car
          - dog
  NUC_3:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/NUC_3 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NUC_3_Sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0.006,0.925,0.421,0.921,0.421,0.978,0.006,0.979
        - 0.093,0.563,0.146,0.521,0.191,0.549,0.205,0.638,0.152,0.688,0.097,0.623
      threshold: 75
      contour_area: 40
      improve_contrast: 'true'
    zones:
      back_garden:
        coordinates: 
          1,1,0.998,0.533,0.954,0.508,0.951,0.358,0.848,0.389,0.759,0.274,0.632,0.208,0.624,0.259,0.559,0.298,0.504,0.309,0.442,0.317,0.474,0.397,0.442,0.475,0.385,0.525,0.175,0.389,0,0.486,0,1
    review:
      alerts:
        required_zones: back_garden
        labels: []
      detections:
        labels:
          - person
          - car
          - dog
    objects:
      filters:
        person: {}
camera_groups:
  NUC:
    order: 1
    icon: LuSwitchCamera
    cameras: birdseye
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-02-21 09:36:55.279091356  [INFO] Preparing Frigate...
2025-02-21 09:36:55.354965109  [INFO] Starting Frigate...
2025-02-21 09:36:56.945509183  [2025-02-21 19:06:56] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-02-21 09:36:56.974522042  [2025-02-21 19:06:56] frigate.util.config            INFO    : frigate config does not need migration...
2025-02-21 09:37:00.912998912  [2025-02-21 19:07:00] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
2025-02-21 09:37:00.933779045  [2025-02-21 19:07:00] peewee_migrate.logs            INFO    : Starting migrations
2025-02-21 09:37:00.933998366  [2025-02-21 19:07:00] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-02-21 09:37:00.953338294  [2025-02-21 19:07:00] frigate.app                    INFO    : Recording process started: 432
2025-02-21 09:37:00.953651275  [2025-02-21 19:07:00] frigate.app                    INFO    : Review process started: 433
2025-02-21 09:37:00.954898355  [2025-02-21 19:07:00] frigate.app                    INFO    : go2rtc process pid: 96
2025-02-21 09:37:00.962205074  [2025-02-21 19:07:00] detector.coral                 INFO    : Starting detection process: 448
2025-02-21 09:37:03.571480766  [2025-02-21 19:07:00] frigate.app                    INFO    : Output process started: 467
2025-02-21 09:37:03.575235312  [2025-02-21 19:07:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-02-21 09:37:03.575390843  [2025-02-21 19:07:00] frigate.app                    INFO    : Camera processor started for NUC_1: 481
2025-02-21 09:37:03.575430891  [2025-02-21 19:07:03] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-02-21 09:37:03.575493204  [2025-02-21 19:07:00] frigate.app                    INFO    : Camera processor started for NUC_2: 482
2025-02-21 09:37:03.575531568  [2025-02-21 19:07:00] frigate.app                    INFO    : Camera processor started for NUC_3: 486
2025-02-21 09:37:03.575559316  [2025-02-21 19:07:00] frigate.app                    INFO    : Capture process started for NUC_1: 489
2025-02-21 09:37:03.575590816  [2025-02-21 19:07:01] frigate.app                    INFO    : Capture process started for NUC_2: 505
2025-02-21 09:37:03.575622557  [2025-02-21 19:07:01] frigate.app                    INFO    : Capture process started for NUC_3: 521
2025-02-21 09:37:03.575684558  [2025-02-21 19:07:01] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-02-21 09:37:03.575719570  [2025-02-21 19:07:01] frigate.api.fastapi_app        INFO    : FastAPI started
```

### Relevant go2rtc log output

```shell
2025-02-21 09:36:55.277982622  [INFO] Preparing new go2rtc config...
2025-02-21 09:36:55.630386995  [INFO] Starting go2rtc...
2025-02-21 09:36:55.714691143  19:06:55.714 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-02-21 09:36:55.714694172  19:06:55.714 INF config path=/dev/shm/go2rtc.yaml
2025-02-21 09:36:55.715032969  19:06:55.714 INF [rtsp] listen addr=:8554
2025-02-21 09:36:55.715138036  19:06:55.715 INF [webrtc] listen addr=:8555/tcp
2025-02-21 09:36:55.715139873  19:06:55.714 INF [api] listen addr=:1984
2025-02-21 09:37:05.279255104  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
cameras	
NUC_1	
camera_fps	5
process_fps	5
skipped_fps	0
detection_fps	4.5
detection_enabled	true
pid	481
capture_pid	489
ffmpeg_pid	498
audio_rms	0
audio_dBFS	0
NUC_2	
camera_fps	5
process_fps	5
skipped_fps	0
detection_fps	1.2
detection_enabled	true
pid	482
capture_pid	505
ffmpeg_pid	523
audio_rms	0
audio_dBFS	0
NUC_3	
camera_fps	5
process_fps	5
skipped_fps	0
detection_fps	2.8
detection_enabled	true
pid	486
capture_pid	521
ffmpeg_pid	534
audio_rms	0
audio_dBFS	0
detectors	
coral	
inference_speed	5.84
detection_start	0
pid	448
detection_fps	8.5
gpu_usages	
intel-qsv	
gpu	"1.06%"
mem	"-%"
clients	
498	"1.77%"
523	"1.41%"
534	"1.75%"
cpu_usages	
1	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
15	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise s6-linux-init-shutdownd"
17	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
24	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise frigate"
25	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise s6rc-oneshot-runner"
26	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise certsync"
27	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise frigate-log"
28	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise go2rtc-log"
29	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise go2rtc"
30	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise go2rtc-healthcheck"
31	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise s6rc-fdholder"
32	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise certsync-log"
33	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise nginx-log"
34	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise nginx"
45	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
46	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
85	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
87	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
89	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
90	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
96	
cpu	"15.1"
cpu_average	"14"
mem	"0.1"
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
106	
cpu	"1.6"
cpu_average	"1"
mem	"1.0"
cmdline	"python3 -u -m frigate"
107	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"bash ./run.user go2rtc-healthcheck"
124	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: master process nginx"
205	
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
cmdline	"nginx: worker process"
206	
cpu	"0.3"
cpu_average	"0"
mem	"0.1"
cmdline	"nginx: worker process"
207	
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
cmdline	"nginx: worker process"
208	
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
cmdline	"nginx: worker process"
209	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: cache manager process"
343	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"bash ./run.user certsync"
432	
cpu	"0.1"
cpu_average	"0"
mem	"0.7"
cmdline	"frigate.recording_manager"
433	
cpu	"0.3"
cpu_average	"0"
mem	"0.6"
cmdline	"frigate.review_segment_manager"
448	
cpu	"1.9"
cpu_average	"2"
mem	"0.6"
cmdline	"frigate.detector.coral"
467	
cpu	"4.5"
cpu_average	"4"
mem	"0.6"
cmdline	"frigate.output       "
481	
cpu	"5.3"
cpu_average	"4"
mem	"0.6"
cmdline	"frigate.process:NUC_1"
482	
cpu	"1.9"
cpu_average	"1"
mem	"0.6"
cmdline	"frigate.process:NUC_2"
486	
cpu	"2.3"
cpu_average	"3"
mem	"0.6"
cmdline	"frigate.process:NUC_3"
489	
cpu	"0.3"
cpu_average	"0"
mem	"0.6"
cmdline	"frigate.capture:NUC_1"
498	
cpu	"1.3"
cpu_average	"1"
mem	"0.2"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/NUC_1_Sub -r 5 -vf vpp_qsv=framerate=5:w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
499	
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
505	
cpu	"0.4"
cpu_average	"0"
mem	"0.6"
cmdline	"frigate.capture:NUC_2"
521	
cpu	"0.3"
cpu_average	"0"
mem	"0.6"
cmdline	"frigate.capture:NUC_3"
523	
cpu	"1.3"
cpu_average	"1"
mem	"0.3"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/NUC_2_Sub -r 5 -vf vpp_qsv=framerate=5:w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
525	
cpu	"0.8"
cpu_average	"0"
mem	"0.1"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/NUC_1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/NUC_1@%Y%m%d%H%M%S%z.mp4"
531	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
534	
cpu	"1.2"
cpu_average	"1"
mem	"0.3"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/NUC_3_Sub -r 5 -vf vpp_qsv=framerate=5:w=896:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
543	
cpu	"0.8"
cpu_average	"0"
mem	"0.1"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/NUC_2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/NUC_2@%Y%m%d%H%M%S%z.mp4"
544	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
569	
cpu	"0.7"
cpu_average	"0"
mem	"0.1"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/NUC_3 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/NUC_3@%Y%m%d%H%M%S%z.mp4"
616	
cpu	"1.5"
cpu_average	"1"
mem	"0.1"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 30 -bf 0 pipe:"
47434	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"sleep 60"
47486	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"sleep 30s"
frigate.full_system	
cpu	"3.2"
mem	"20.5"
service	
uptime	8190
version	"0.15.0-cea210d"
latest_version	"0.15.0"
storage	
/media/frigate/recordings	
total	936737.1
used	753559.9
free	135521.6
mount_type	"ext4"
/media/frigate/clips	
total	936737.1
used	753559.9
free	135521.6
mount_type	"ext4"
/tmp/cache	
total	953.7
used	130.7
free	822.9
mount_type	"tmpfs"
/dev/shm	
total	512
used	102.6
free	409.4
mount_type	"tmpfs"
temperatures	{}
last_updated	1740138811
processes	
recording	
pid	432
review_segment	
pid	433
go2rtc	
pid	96
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    privileged: true
    container_name: "frigate"
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /home/nuc/containers/frigate/config:/config
      - /home/nuc/containers/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
    environment:
      TZ: "Australia/Darwin"
      FRIGATE_RTSP_PASSWORD: "<pass>"
      PLUS_API_KEY: "<key>"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![metrics1](https://github.com/user-attachments/assets/403cf63a-24c4-4176-ad71-6cee849ec2f3)
![metrics2](https://github.com/user-attachments/assets/3a4b701a-9a6a-4384-a3a1-4b53be5e5503)
![metrics3](https://github.com/user-attachments/assets/cac2aa86-e29c-475a-8905-292f2e12a2b4)

### Any other information that may be helpful

This is an example from 5 minutes ago where even though it detected me with high confidence and in the correct zone it did not create an alert. 

![object lifecycle1](https://github.com/user-attachments/assets/8df15737-cba4-4d01-b4c1-a04cdd0aabc7)
![object lifecycle2](https://github.com/user-attachments/assets/93cae250-86c5-4099-a47a-5029b7f96e7b)
![object lifecycle3](https://github.com/user-attachments/assets/5bd0d49e-e127-48ab-bf6d-dcea6c3dd27d)
![object lifecycle4](https://github.com/user-attachments/assets/545989a7-bbdd-4cf5-9a2d-744405d29300)
![timeline](https://github.com/user-attachments/assets/853e109f-fb22-4e13-a135-add86c5c3e84)
