### DISCUSSION TITLE
[Support]: Detection stream started failing (was working)

### DISCUSSION THREAD

**Discussion by blacknell** [blakeblackshear/frigate#16717] [General Support]
### Describe the problem you are having

On of my streams started failing - saying to check the logs.

When I click on the defective stream in the frgate home page it does bring up the stream for that camera

Any ideas?

### Version

0.14.1

### Frigate config file

```yaml
go2rtc:
  log:
    level: info
    api: info
    exec: info
    ngrok: info
    rtsp: info
    streams: info
    webrtc: info
  streams:
    front_garden:
      - rtsp://stream:REDACTED@192.168.61.52/cam/realmonitor?channel=1&subtype=0
    front_garden_720:
      - rtsp://stream:REDACTED@192.168.61.52/cam/realmonitor?channel=1&subtype=2


  front_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden_720
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_garden
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
```

### Relevant Frigate log output

```shell
frigate.record.maintainer
Unable to keep up with recording segments in cache for front_garden. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Relevant go2rtc log output

```shell
startup
github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://stream:streaming123@192.168.61.52/cam/realmonitor?channel=1&subtype=0
```

### FFprobe output from your camera

```shell
could not find
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    hostname: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: "ghcr.io/blakeblackshear/frigate:{{frigate_docker_tag}}"
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/frigate/config/:/config/
      - /home/pi/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"
      - "8971:8971"
    environment:
      - PLUS_API_KEY={{ lookup('ansible.builtin.env', 'FRIGATE_PLUS_API_KEY', default=undef()) }}
      - TZ=Europe/London
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua
