### DISCUSSION TITLE
[Support]: 0.15 clip files are incompatible with AppleWebKit (Safari) browsers

### DISCUSSION THREAD

**Discussion by zestysoft** [blakeblackshear/frigate#16738] [General Support] [answered]
### Describe the problem you are having

Hey all, after upgrading from 0.14 to 0.15, none of the mp4 clip files play back correctly in any Safari based browsers.

### Version

0.15

### What browser(s) are you using?

All browsers in IOS, and Safari on MacOS.  Chrome works on MacOS.

### Frigate config file

```yaml
go2rtc:
  streams:
    front-camera:
      - rtsp://frigate:...@192.168.100.109:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front-camera-sub:
      - rtsp://frigate:...@192.168.100.109:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    right-camera:
      - rtsp://frigate:...@192.168.100.37:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    right-camera-sub:
      - rtsp://frigate:...@192.168.100.37:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    backyard-camera:
      - rtmp://192.168.100.21/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user=admin&password=...
    backyard-camera-sub:
      - rtmp://192.168.100.21/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=0&user=admin&password=...
    front-yard-camera:
      - rtsp://frigate:...@192.168.100.105:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    front-yard-camera-sub:
      - rtsp://frigate:...@192.168.100.105:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
    chimney-camera:
      - rtsp://frigate:...@192.168.100.127:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    chimney-camera-sub:
      - rtsp://frigate:...@192.168.100.127:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_1
  webrtc:
    candidates:
      - frigate:8555
mqtt:
  host: ha-mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: ...
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
logger:
  default: info
ffmpeg:
  path: '5.0'
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel_output_format
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    record: preset-record-generic-audio-copy
objects:
  track:
    - person
    - dog
    - cat
    - bird
    - bicycle
  filters:
    person:
      min_area: 5000
      max_area: 100000
birdseye:
  enabled: true
  width: 1024
  height: 768
  quality: 1
  mode: continuous
snapshots:
  enabled: true
cameras:
  right-camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/right-camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/right-camera-sub
          roles:
            - detect
            - audio
    detect:
      width: 1920
      height: 540
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
      required_zones: []
    zones:
      side-gate-path-zone:
        coordinates: 0,536,1920,536,1920,389,1818,251,1373,116,807,91,321,143,224,0,0,221
        objects:
          - person
          - dog
          - cat
          - bird
    birdseye:
      order: 5
  backyard-camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard-camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard-camera-sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
      required_zones: []
    zones:
      backyard-flat-zone:
        coordinates: 0,0.829,0.168,0.744,0.261,0.757,0.694,0.963,0.693,1,0.955,1,0.883,0.599,0,0.287
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
        loitering_time: 0
      backyard-hill-zone:
        coordinates: 0,136,558,282,547,38,213,0
        objects:
          - person
          - dog
          - cat
          - bird
    birdseye:
      order: 3
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: true
      mask: 0,1,0,0.834,0.17,0.749,0.256,0.76,0.688,0.968,0.687,1
  front-yard-camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-yard-camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front-yard-camera-sub
          roles:
            - detect
            - audio
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
      required_zones: []
    motion:
      mask:
        - 364,63,640,146,640,0,404,0,140,0,138,33
        - 640,320,593,183,568,179,588,394
        - 35,480,256,480,58,262,0,302,0,390
    zones:
      front-yard-path-zone:
        coordinates: 175,327,273,288,399,166,285,123,169,181,115,292
        objects:
          - person
          - dog
          - cat
          - bird
      front-yard-driveway-zone:
        coordinates: 346,107,129,56,147,213
        objects:
          - person
          - dog
          - cat
          - bird
          - bicycle
      front-yard-sidewalk-zone:
        coordinates: 558,227,556,141,132,45,139,95
        objects:
          - person
          - cat
          - dog
          - bird
    birdseye:
      order: 1
  front-camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front-camera-sub
          roles:
            - detect
            - audio
    detect:
      width: 1920
      height: 540
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
      required_zones: []
    birdseye:
      order: 4
    zones:
      Front-Camera-Driveway-Zone:
        coordinates: 0.098,0.9,0.27,0.275,0.647,0.304,0.801,0.993,0.128,0.989
        inertia: 3
        loitering_time: 0
      Front-Camera-Walkway-Zone:
        coordinates: 0.723,0.382,0.761,0.386,0.892,0.818,0.861,0.904
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0.89,0.132,0.958,0.075,0.993,0.196,0.959,0.364
  chimney-camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/chimney-camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/chimney-camera-sub
          roles:
            - detect
    motion:
      threshold: 10
      mask: 0.634,0,1,0,1,0.696,0.773,0.491,0.664,0.467,0.634,0.437
    detect:
      width: 1280
      height: 720
      fps: 6
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      quality: 100
      required_zones: []
    birdseye:
      order: 5
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version 7.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1_4 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, rtsp, from 'rtsp://frigate:...@192.168.100.37:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.023200, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 5120x1440 [SAR 1:1 DAR 32:9], 20 fps, 10 tbr, 90k tbn
  Stream #0:1: Audio: mp3 (mp2), 16000 Hz, mono, s16p, 16 kb/s
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
I use kubernetes to deploy.
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

All cameras

### Any other information that may be helpful

Giving the output of ffprobe for clip files created by the same camera with 0.14 and 0.15 to chatgpt, this is what it detects are being different:

```
Here are the key differences between the old (0.14) and new (0.15) MP4 files based on the ffprobe output you provided:

Compatible Brands
Old (0.14): TAG:compatible_brands=isomiso2avc1mp41
New (0.15): TAG:compatible_brands=isomiso6iso2avc1mp41
The new file adds iso6 to the list of compatible brands. In some cases, older players (or certain browsers) can be sensitive to the “brand” and either refuse to play or exhibit issues.
Frame Rate and Frame Count Reporting
Old (0.14):
r_frame_rate=50/1
avg_frame_rate=2048000/100997 ~ 20.27 fps
nb_frames=200
New (0.15):
r_frame_rate=40/1
avg_frame_rate=7168/361 ~ 19.86 fps
nb_frames=N/A (ffprobe cannot detect the total frame count)
While the reported “real” playback frame rate is roughly the same (in the 20 fps range), the container metadata is different, and nb_frames is missing in the new file.
Duration and Bitrate
Old (0.14): Duration ~ 9.862 s, Bitrate ~ 9.67 Mbps
New (0.15): Duration ~ 7.05 s, Bitrate ~ 7.11 Mbps
The new files are slightly shorter and have a lower bitrate. The difference itself in duration/bitrate is unlikely to break Safari playback, but any changes in how the container is written could affect compatibility.
Missing “title=go2rtc/1.9.2” Tag
The old file has a metadata tag TAG:title=go2rtc/1.9.2 that the new file lacks. Usually, title tags are not critical for playback, but it shows the new file uses a slightly different writing library or parameters.
```

The difference in bitrate could be because the older one was recorded during the day while the new was recorded at night.

Also, I've confirmed with one other that they also see this behavior with their recently upgraded deployment.

Finally, using the Frigate UI on these same browsers works perfectly.
