### DISCUSSION TITLE
How to finetune bounding box limits

### DISCUSSION THREAD

**Discussion by bartbutenaers** [blakeblackshear/frigate#16731] [Ask A Question] [answered]
Hi all,

I started with Frigate few weeks ago, and amazed about what it allows me to setup in such a short time.  I just need to _**reduce the false positives**_, by filtering the _**object shape**_: min/max area and min/max ratio.

But to be honest I have no idea how I could finetune those values decently.  I could of course go through a process of lots of trial and error, but I hope there exists somehow a bit more scientifical approach.  I am wondering if there aren't rule of thumbs we can use.  Or a list of steps we can follow, to determine somehow the most optimal minimum and maximum values.

I 'assume' the _**object lifecycle window**_ is the best tool to accomplish this, because it shows a lot of useful information:

![image](https://github.com/user-attachments/assets/d5c87eb4-77e4-4a67-9bf1-f66b5fa97bdb)

Although this window is really nice, I have no idea how much _**tolerance**_ I should apply to those measured values to get good limits.
I assume I should walk towards the camera from the farest distance to the nearest distance?  
But then I only have decent bounding box shapes determined for my own body.
It would be a bit weired having to invite a large group of people with all different sizes and weights, only to be able to determine good limits ;-)

Thanks for illuminating me!!
Bart

**Comment by hawkeye217** [comment]
There is certainly a bit of trial and error here, but the values you're seeing in the Object Lifecycle pane should give you a good place to start. Because you can configure both a min and max value for each, start with a lot of tolerance and then narrow it down if you're still getting false positives.

**Comment by bartbutenaers** [comment]
@hawkeye217 
Thanks for your fast response!

It would be nice if I had at least some guidelines, because unfortunately as a video surveillance noob I don't have any feeling at all with these ratio's at the moment.

I read somewhere that - based on observations and anthropometric studies - human bodies have a (height/width) ratio between:
+ Lower bound `5:1` for average adults.
+ Upper bound `8:1` for slim body types.

Suppose I would calculate my _**ratio limits**_ like this:
1. Measure my true body dimensions
       + `realHeight` = length from the feet to top of the head
       + `realWidth` = width from shoulder to shoulder (when that is the widest part of my body)
2. `realAspectRatio` = realHeight / realWidth
3. Walk directly towards the camera, and look at the `imageAspectRatio` in the ***object lifecycle window***.
4. `imageDistortionFactor` = imageAspectRatio / realAspectRatio
   I think that when this ratio > 1, then the camera is distorting the width more than the height, which makes the body appear wider in the image than it would in reality.
5. The ratio limits (in the image) for human bodies are then:
   + minimumAspectRatio=5 * imageDistortionFactor
   + maximumAspectRatio=8 * imageDistortionFactor

I haven't tried this yet, so hopefully I am not talking complete nononses...

**Reply by ElectronicBattle** [reply]
I've been a Frigate user since last summer and I am very much a novice. All I did was to embrace the recommended values because i decided that trying to set my own would probably be a lengthy process. 

My false alarm rate was quite low but not really good enough, but when I got my first trained model via Frigate+ it made a huge difference.  I now detect people with close to 100% accuracy. I get dogs and cats and foxes differentiated with similarly high accuracy too - maybe 1 or 2 errors in every hundred - and I have found the paid-for model approach to be the easiest way to get brilliant results.

**Reply by hawkeye217** [reply]
> @hawkeye217 Thanks for your fast response!
> 
> It would be nice if I had at least some guidelines, because unfortunately as a video surveillance noob I don't have any feeling at all with these ratio's at the moment.
> 
> I read somewhere that - based on observations and anthropometric studies - human bodies have a (height/width) ratio between:
> 
>     * Lower bound `5:1` for average adults.
> 
>     * Upper bound `8:1` for slim body types.
> 
> 
> Suppose I would calculate my _**ratio limits**_ like this:
> 
>     1. Measure my true body dimensions
>        + `realHeight` = length from the feet to top of the head
>        + `realWidth` = width from shoulder to shoulder (when that is the widest part of my body)
> 
>     2. `realAspectRatio` = realHeight / realWidth
> 
>     3. Walk directly towards the camera, and look at the `imageAspectRatio` in the _**object lifecycle window**_.
> 
>     4. `imageDistortionFactor` = imageAspectRatio / realAspectRatio
>        I think that when this ratio > 1, then the camera is distorting the width more than the height, which makes the body appear wider in the image than it would in reality.
> 
>     5. The ratio limits (in the image) for human bodies are then:
>        
>        * minimumAspectRatio=5 * imageDistortionFactor
>        * maximumAspectRatio=8 * imageDistortionFactor
> 
> 
> I haven't tried this yet, so hopefully I am not talking complete nononses...

You might not need to go as in-depth with these measurements as you're thinking. With the scene you've posted, many users have found that the stock free model that ships with Frigate performs well enough without specifying any kind of min or max ratio. 

Additionally, you may still need a wide range of ratios depending on a person's orientation or distance from your camera. 

Are you actually experiencing any false positives that you think should be tuned out?

For other users of this thread, the `min_ratio` and `max_ratio` values are compared against a detected object's width/height ratio (in pixels). If the ratio is outside this range, the object will be ignored as a false positive  [(1)](https://docs.frigate.video/configuration/object_filters/#object-shape) .

To understand the ratios:
- A ratio of 1 is a square shape
- A ratio of 0.5 is a "tall skinny" box 
- A ratio of 2 is a "wide flat" box 

For example:
- If `min_ratio` is 1.0, any object that is taller than it is wide will be ignored
- If `max_ratio` is 1.0, any object that is wider than it is tall will be ignored

**Reply by bartbutenaers** [reply]
> Are you actually experiencing any false positives that you think should be tuned out?

@hawkeye217 
I have to admit that Frigate works amazingly well with out-of-the box settings.  I have it now running for a couple of days and it sees completely all persons.  But every morning I have a series of false positives.  Will digg further into this, because probably it will be me having done something wrong.  Will get here back afterwards with feedback, to make sure you don't loose too much of your precious time with this.

**Comment by bartbutenaers** [comment]
@ElectronicBattle,

With *"recommended values"*, do you mean the ones in the [reference config](https://docs.frigate.video/configuration/reference/)?
```
min_ratio: 0.5
max_ratio: 2.0
```
I would have thought this would depend on the camera type, so that there would be no one value that fits all use cases? Or perhaps I can/should adjust my camera settings to make this happen.   Don't know ;-(

**Reply by ElectronicBattle** [reply]
I didn't do anything even as clever as that. I simply took (from the reference config)

```
person:
      min_score: .65
      threshold: .85
```

and found that the results were quite good. Then, after I had amassed many hundreds of images, I submitted to frigate+ for a model.

I think that the cameras available, assuming you're talking about ordinary commercial ones, will all use similar CCD sensors whose aspect ratios, coordinated with lenses, are likely to give a similar range of values which are going to be 16:9 or 4:3 or thereabouts.  I think you are over-complicating things (it is something I always do!).

**Comment by bartbutenaers** [comment]
Hi guys,

I again got a series of false positives tonight.  For example:

![image](https://github.com/user-attachments/assets/8d059c30-921d-4dd3-8019-bab4fc98b4e6)

The score is `71%`.  So I can increase the threshold to `.85` like @ElectronicBattle suggests.  Currently I use the default value (i.e. I have not specified explicit a threshold value in my config), because I assumed - perhaps incorrectly - that the default values are choosen to be appropriate for most use cases...  See my config at the bottom of this post.

But apart from that, the default settings allow any area.  Which means that in this case nearly my ***entire image*** is being accepted as a person.  Therefore I started this discussion, because I assumed that most users have a maximum area configured.  But I might be completely mistaken again, and perhaps a higher threshold is enough to get rid of all this...

BTW the ratio's are above `1` as you can see for example here:

![image](https://github.com/user-attachments/assets/8c497a59-0f16-4632-9732-9c1cf7d899d9)

P.S. Unfortunately most of these snapshot images are not shown in this window:
![image](https://github.com/user-attachments/assets/388b2ad8-0c81-4b6f-b63e-4d573f300f98)
Need to investigate that further afterwards.  No idea the moment what could cause this...

Here is my (perhaps too primitive) config:
   ```
   tls:
      # No https (with self-signed) certificate, because Tailscale already provides https (with LetsEncrypt certificate)
      enabled: false
   mqtt:
      enabled: true #Use MQTT
      host: xxxxxxxxxxxx
      port: 1883
      user: xxxx
      password: xxxxx
   ffmpeg:
      # Decode H.264 streams via GPU (i.e. hardware acceleration)
      hwaccel_args: preset-rpi-64-h264
   detectors:
      #cpu1:
      #  type: cpu
      #  num_threads: 3
      coral:
        type: edgetpu
        device: usb
    record:
      enabled: true
      retain:
        # Don't store the continious video stream (i.e. no 24/7 live recording)
        days: 0
        mode: all
      alerts:
        retain:
          days: 30
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 30
        pre_capture: 10
        post_capture: 10
    snapshots:
      enabled: true
      quality: 100
      timestamp: false
      bounding_box: true
      crop: false
      # Store snapshot jpg images (for 30 days) in /media/frigate/clips for each object that is detected
      retain:
        default: 30
    detect:
      enabled: true
      fps: 3
    objects:
      track:
        - person
        - dog
    go2rtc:
      streams:
        # ====== Video deurbel =======
        rtsp_video_deurbel_sub:
          - rtsp://xxxxx/h264Preview_01_sub
          - ffmpeg:rtsp_video_deurbel_sub#video=copy
        rtsp_video_deurbel_main:
          - rtsp://xxxxx/h264Preview_01_main
          - ffmpeg:rtsp_video_deurbel_main#video=copy
        # ====== Camera achter garage ======
        rtsp_cam_achter_garage_sub: # WERKT NIET
          - rtsp://xxxxx/cam/realmonitor?channel=1&subtype=1
          - ffmpeg://rtsp_cam_achter_garage_sub#video=copy
        rtsp_cam_achter_garage_main:
          - rtsp://xxxxx/cam/realmonitor?channel=1&subtype=0
          - ffmpeg:rtsp_cam_achter_garage_main#video=copy
        # ====== Camera koer portaal ======
        rtsp_cam_koer_portaal_sub: # WERKT NIET
          - rtsp://xxxxx/cam/realmonitor?channel=1&subtype=1
          - ffmpeg:rtsp_cam_koer_portaal_sub#video=copy
        rtsp_cam_koer_portaal_main:
          - rtsp://xxxx/cam/realmonitor?channel=1&subtype=0
          - ffmpeg:rtsp_cam_koer_portaal_main#video=copy
        # ====== Camera kelder experiment ======
        rtsp_cam_kelder_experiment_sub:
          - rtsp://xxxx/h264Preview_01_sub
          - ffmpeg:rtsp_cam_kelder_experiment_sub#video=copy
      webrtc:
        # For local access of the webrtc stream
        candidates:
          - xxxxx.ts.net:8555
          - stun:8555
    birdseye:
      enabled: true
      # Include all cameras by default in Birdseye view
      mode: continuous
    cameras:
      deurbel_voordeur:
        enabled: true
        live:
          stream_name: rtsp_video_deurbel_main
        ffmpeg:
          #TODO input_args: -skip_frame nokey
          inputs:
            - path: rtsp://127.0.0.1:8554/rtsp_video_deurbel_sub
              input_args: preset-rtsp-restream
              # Use the cam's low-resolution sub stream for motion/object detection
              roles:
                - detect
            - path: rtsp://127.0.0.1:8554/rtsp_video_deurbel_main
              input_args: preset-rtsp-restream
              # Use the cam's high-resolution main stream for recording
              roles:
                - record
        objects:
          mask: 
            0.284,0.289,0.291,0.554,0.484,0.594,0.486,0.495,0.545,0.5,0.546,0.485,0.985,0.479,0.909,0.054,0.286,0.17
        motion:
          mask:
            - 0.008,0.926,0.308,0.93,0.308,0.986,0.007,0.992
            - 0,0,-0.001,0.151,0.195,0.219,0.193,0.543,0.552,0.603,0.55,0.49,1,0.484,1,0
      cam_achter_garage:
        enabled: true
        live:
          stream_name: rtsp_cam_achter_garage_main
        ffmpeg:
          #TODO input_args: -skip_frame nokey
          inputs:
            - path: rtsp://127.0.0.1:8554/rtsp_cam_achter_garage_sub
              input_args: preset-rtsp-restream
              # Use the cam's low-resolution sub stream for motion/object detection
              roles:
                - detect
            - path: rtsp://127.0.0.1:8554/rtsp_cam_achter_garage_main
              input_args: preset-rtsp-restream
              # Use the cam's high-resolution main stream for recording
              roles:
                - record
        objects:
          mask:
            - 0.663,0.113,0.674,0.459,0.823,0.488,0.837,0.146,0.732,0.105
            - 0.163,0.168,0.082,0.337,0.157,0.545,0.278,0.47,0.305,0.254,0.209,0.152
      cam_koer_portaal:
        enabled: true
        live:
          stream_name: rtsp_cam_koer_portaal_main
        ffmpeg:
          #TODO input_args: -skip_frame nokey
          inputs:
            - path: rtsp://127.0.0.1:8554/rtsp_cam_koer_portaal_sub
              input_args: preset-rtsp-restream
              # Use the cam's low-resolution sub stream for motion/object detection
              roles:
                - detect
            - path: rtsp://127.0.0.1:8554/rtsp_cam_koer_portaal_main
              input_args: preset-rtsp-restream
              # Use the cam's high-resolution main stream for recording
              roles:
                - record
        objects:
          mask:
            - 0.294,0.287,0.333,0.288,0.37,0.058,0.334,0.012,0.295,0.018,0.266,0.11
            - 0.794,0.11,0.697,0.177,0.653,0.462,0.704,0.675,0.757,0.701,0.861,0.535,0.891,0.248
      cam_kelder_experiment:
        enabled: true
        live:
          stream_name: rtsp_cam_kelder_experiment_sub
        ffmpeg:
          #TODO input_args: -skip_frame nokey
          inputs:
            - path: rtsp://127.0.0.1:8554/rtsp_cam_kelder_experiment_sub
              input_args: preset-rtsp-restream
              # Use the cam's low-resolution sub stream for motion/object detection
              roles:
                - detect
    version: 0.15-1
    camera_groups:
      Buiten:
        order: 1
        icon: LuTreePine
        cameras:
          - deurbel_voordeur
          - cam_achter_garage
          - cam_koer_portaal

   ```

**Comment by bartbutenaers** [comment]
I have updated my settings to:
```
objects:
  track:
    - person
    - dog
  filters:
    person:
      min_score: .65
      threshold: .85
    dog:
      min_score: .65
      threshold: .85
```
But then I am ***not detected anymore*** when I am walking by.
I had a quickly look at the history, and when my boys arrived at home they got a score of about `73%` to `76%`.
When I look at the false positives, those are between `69%` and `76%`:

![image](https://github.com/user-attachments/assets/98b1abf4-df84-46cd-b461-83d02fab77cc)

So there is an ***overlap*** between the high scores of the false positives and the low scores of real humans.  As a result I don't think I can ever be able to get rid of the false positives, only by filtering based on the threshold.  I had hoped that there would be a ***gap*** in between both, but that doesn't seem the case for some reason.  I assume it is me doing something wrong, because others don't seem to have this issue.

All noob level tips are welcome!

**Reply by ElectronicBattle** [reply]
I'm sorry - my limited knowledge can't contribute anything directly useful. All I know is that I also saw overlapping true and false scores and yet I was able to get it all working. 

I do still get weird false positives from time to time, for example with deer or a tree which, to Frigate, apparently looks like a deer!  But not many at all.  Once a month ?

I could post my config in case you are able to usefully copy parts of it but I think someone (anyone!) with better knowledge than me will be able to provide better value.

**Reply by NickM-27** [reply, marked as answer]
For the default model a threshold of .85 will never work because the max possible score of the default coral model is 84%

In this case a max area filter would likely work well

**Reply by ElectronicBattle** [reply]
Ahh ... I remember now (Nick's right of course). This is what happened with me :

the default model (in other words, *not* a model due to using Frigate+)  gave me results with me using some score or other, presumably as per the standard reference config. The spread of the results was quite wide (say 0.6 to 0.8 or something).  I can't remember the details now, because this was all happening during August 2024.

Once I had collected more than 100 images (I think 150 or so), I submitted them to Frigate+ which gave me a custom trained model, at which point I was able to increase the threshold from the original nominal value to the ones I mentioned above (0.85) because now the spread was from 0.8 to 0.95 or similar.  This meant that my false positives reduced massively.

The trained model means the confidences increase hugely (let's say to the range 0.8 to 0.9) and hence they separate themselves away, numerically, from the untrained values (let's say 0.6 - 0.8).

**Comment by bartbutenaers** [comment]
Hi guys,
I had a look at all my recordings from the last weeks, especially at the ***area*** numbers in the nice Object LifeCycle window.  From those area numbers, it became pretty quickly clear that:
+ All the real humans had an area of maximum 45K
+ All the false positives had an area of above 80K

So I have overridden the ***max_area*** setting for that particular camera (which had the false positives), with a bit of tolerance:
```
cam_koer_portaal:
   filters:
      person:
          max_area: 55000
```
Perhaps I can try to increase it even more, to avoid real humans not getting detected when doing some movements.  But at moment all real humans are still detected, and last night I had no false positives anymore.

Hopefully others can learn from our discussion.

Thanks all for assisting me to get this solved.  Really appreciated!!!!

Bart
