### DISCUSSION TITLE
[Camera Support]: what form of nvenc/nvdec is needed by Frigate for this `ffprobe` result?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#16734] [Camera Support] [answered]
### Describe the problem you are having

Hello all

I want to have another try with a different graphics card (Nvidia P620 this time, replacing my existing GT1030) at getting  go2rtc working properly so that I can view the various video formats properly within Frigate (HLS vs MSE etc.) using linux and the chromium (or firefox or anything!) browser.  It already all works perfectly in Android.

The [Nvidia P620](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) tells me for nvenc
![image](https://github.com/user-attachments/assets/cc0b8cee-5ca6-4a65-ac22-1163f7d7acbd)

and for nvdec
![image](https://github.com/user-attachments/assets/92b51cc0-2405-4ede-aca9-584edb51bbc8)

When I run `ffprobe` in verbose mode on my linux desktop connected to my cameras,  I get a lot of additional information which shows my cameras are generating h265 (hvec) traffic (I cannot switch it to h264).

Given the above capabilities and contrasted with the plethora of information below, is the P620 likely to work on account of it being capable of  **h.265(hevc) 4:2:0** but not capable of **h.265(hevc) 4:4:4** ?

$ ffprobe -v error -show_format -show_streams 'rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0'

```
[STREAM]
index=0
codec_name=hevc
codec_long_name=H.265 / HEVC (High Efficiency Video Coding)
profile=Main
codec_type=video
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=1920
height=1080
coded_width=1920
coded_height=1080
closed_captions=0
film_grain=0
has_b_frames=0
sample_aspect_ratio=N/A
display_aspect_ratio=N/A
pix_fmt=yuvj420p
level=123
color_range=pc
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=unknown
refs=1
id=N/A
r_frame_rate=31/4
avg_frame_rate=16/1
time_base=1/90000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=96
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
[/STREAM]
```
```
[STREAM]
index=1
codec_name=pcm_mulaw
codec_long_name=PCM mu-law / G.711 mu-law
profile=unknown
codec_type=audio
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=s16
sample_rate=8000
channels=1
channel_layout=unknown
bits_per_sample=8
initial_padding=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/8000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=64000
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
[/STREAM]
```
```
[FORMAT]
filename=rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0
nb_streams=2
nb_programs=0
format_name=rtsp
format_long_name=RTSP input
start_time=0.000000
duration=N/A
size=N/A
bit_rate=N/A
probe_score=100
TAG:title=Jabsco NVR Stream
[/FORMAT]
```

### Version

0.15

### What browser(s) are you using?

chromium

### Frigate config file

```yaml
#BASELINE8_160225_0.15.0 TRUENAS low CPU burden (upper patio restream drive restream OK but a bit glitchy on video - disable for now)
version: 0.15-1

ui:
  time_format: 24hour
mqtt:
  enabled: false


model:
  path: plus://750ee08e1dda3669bc2c3273e6984a53  #mobiledet edgeTPU 2025.0 25/1/25

genai:
  enabled: True
  provider: gemini
  api_key: "###########################"
  model: gemini-2.0-flash-lite-preview-02-05 #gemini-2.0-flash

semantic_search:
  enabled: true
  reindex: false #true 
  model_size: small



objects:
  filters:
    dog:
      min_score: .8
      threshold: .9
    cat:
      min_score: .75
      threshold: .8
    fox:
      min_score: .65
      threshold: .8
    squirrel:
      min_score: .65
      threshold: .8
    bird:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    license_plate:
      min_score: .6
    bicycle:
      min_score: .65
      threshold: .85


  track:
    - person
    - face
    - car
    - license_plate
    - cat
    - dog
    - fox
    - bird
    - deer
    - squirrel
    - package
    - bicycle


review:
  alerts:
    labels:
      - person
      - face
      
      - car
      - license_plate
      
      - cat
      - dog
      - fox
      - deer
      - bicycle

  detections:
    #enabled: true
    labels:
      - deer
      - bird
      - squirrel
      

snapshots:
  enabled: true # Optional: Enable writing jpg snapshot to /media/frigate/clips
  clean_copy: true #false  #true # Optional: save a clean PNG copy of the snapshot image
  timestamp: false # Optional: print a timestamp on the snapshots
  bounding_box: true # Optional: draw bounding box on the snapshots
  crop: false # Optional: crop the snapshot
  height: 768 # Optional: height to resize the snapshot to (default: original size)  #height: 800
  #required_zones: []# Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  retain: # Optional: Camera override for retention settings (default: global values)
    default: 5 # Required: Default retention days 
    objects: # Optional: Per object retention days
      person: 7
      face: 7
      cat: 7
      dog: 7
      bird: 3
      squirrel: 3
      fox: 7
      badger: 7
      deer: 7
      car: 7
      licence_plate: 7
      bicycle: 7

  
  quality: 100 # Optional: quality of the encoded jpeg, 0-100 

# go2rtc:
# streams:
    #reference format from NickM-27 @ https://github.com/blakeblackshear/frigate/discussions/12376 
    #              "ffmpeg:rtsp://...                                               #video=h264#audio=copy#hardware" note the quotes and hashes
#    greenhouse:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
#      - ffmpeg:greenhouse#audio=opus
#   upper_patio:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0#video=h264#audio=copy
#      - ffmpeg:upper_patio#audio=opus
#    ponds:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0#video=h264#audio=copy
#      - ffmpeg:ponds#audio=opus
#    blue_gate:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0#video=h264#audio=copy
#      - ffmpeg:blue_gate#audio=opus
#    lower_steps:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0#video=h264#audio=copy
#      - ffmpeg:lower_steps#audio=opus
#    lower_patio:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0#video=h264#audio=copy
#      - ffmpeg:lower_patio#audio=opus
#    shed:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0#video=h264#audio=copy
#      - ffmpeg:shed#audio=opus
#   drive:
#      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0#video=h264#audio=copy
#      - ffmpeg:drive#audio=opus
#    doorbell:
#      - "ffmpeg:rtsp://admin:QXQODG@192.168.1.192:554/Streaming/Channels/101#raw -vf lenscorrection=k1=-0.450:k2=0.1"
#      - "ffmpeg:doorbell#audio=opus"

####rtsp is 30060 and webRTC is 30061 (TN Frigate app internals)
#webrtc:
#    candidates:
#      - 192.168.1.194:30061
#      - stun:30061


ffmpeg:
  #####you can only have one line here#####
  hwaccel_args: preset-nvidia-h264
  #hwaccel_args: preset-nvidia-hevc #gives black screens on cameras
  #hwaccel_args: preset-nvidia-cuvid #gives black screens on cameras
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb
    detect:
      enabled: true

birdseye:
  enabled: true
  mode: continuous #continuous | objects | motion

# record: # <----- Enable recording # was working
#  enabled: true # was working

# added from https://fixtse.com/blog/coral-ia-frigate start#

# added from https://fixtse.com/blog/coral-ia-frigate #


record:
  enabled: true
  retain:
    days: 3
    mode: motion

motion:
  improve_contrast: true

detect:
  width: 640
  height: 360

#record:
#  width: 1920
#  height: 1080

########################################################################################################################################################################################################################################

cameras: #########GREENHOUSE##################GREENHOUSE##################GREENHOUSE##################GREENHOUSE##################GREENHOUSE#########GREENHOUSE#########
  greenhouse:
    genai:
      enabled: False # <- enable GenAI for this camera
      

    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
          roles:
            - detect



        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 1





#########UPPER_PATIO###############################################UPPER_PATIO###########################UPPER_PATIO###########################UPPER_PATIO###########################
  upper_patio:
    genai:
      enabled: True # <- enable GenAI for this camera
      use_snapshot: True
      objects:
        - fox
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=1/track0 #SD 640x360 level1 ### 130125 trying HD for det (here) and rec below as usual
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=1&level=0/track0
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder

    zones:
      upperpatio:
        coordinates: 
          0.003,0.997,0.005,0.795,0.042,0.789,0.045,0.732,0.049,0.619,0.077,0.546,0.103,0.479,0.145,0.425,0.168,0.401,0.204,0.371,0.216,0.369,0.268,0.378,0.279,0.339,0.32,0.302,0.347,0.293,0.361,0.298,0.382,0.345,0.395,0.375,0.563,0.418,0.582,0.474,0.626,0.476,0.674,0.51,0.712,0.515,0.795,0.664,0.862,0.704,0.933,0.822,0.999,0.896,0.995,0.996
        loitering_time: 0
    motion:
      mask: 
        0.003,0.374,0.207,0.313,0.239,0.272,0.292,0.258,0.32,0.245,0.36,0.222,0.682,0.219,0.716,0.204,0.726,0.001,0.002,0.001

    review:
      alerts:
        required_zones: upperpatio
      detections: 
        required_zones: upperpatio

    
      
    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 2

#########UPPER_PATIO###############################################UPPER_PATIO###########################UPPER_PATIO###########################UPPER_PATIO###########################

  ponds: #################PONDS#######################################PONDS#########################PONDS#########################PONDS#########################PONDS#########################
    genai:
      enabled: False # <- enable GenAI for this camera
    
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=2&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
          roles:
            - detect


        - path: rtsp://192.168.1.123:554/media=0/channel=2&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
          roles:
            - record
    
    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - squirrel
        - fox
        - badger #placeholder

    birdseye:
      mode: continuous  #continuous | objects | motion
     # masks are black: they block out areas where you aren't interested in detecting things
      order: 3
#################PONDS#######################################PONDS#########################PONDS#########################PONDS#########################PONDS#########################

  blue_gate: #########BLUE_GATE###################################################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################
    genai:
      enabled: False # <- enable GenAI for this camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=3&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=3&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
      #  input_args: preset-rtsp-restream

          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=3&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - badger # placeholder
        - car
        - license_plate
        - bicycle

    birdseye:
      mode: continuous   #continuous | objects | motion
      # masks are black: they block out areas where you aren't interested in detecting things
      order: 4

    motion:
      mask:
        - 0,153,85,148,140,139,239,140,300,142,354,145,398,141,429,141,486,145,518,213,450,226,605,360,640,360,640,0,0,0
        - 479,360,423,337,411,310,390,288,369,268,352,248,340,228,297,223,267,247,231,253,212,204,188,200,152,218,107,227,88,222,73,234,63,250,54,266,45,282,27,292,0,287,0,360

    zones:
      gravel:
        coordinates: 
          411,273,471,360,523,360,585,360,474,227,473,151,388,141,283,146,228,142,0,151,0,301,296,233
#########BLUE_GATE###################################################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################BLUE_GATE#############################

  lower_steps: #########LOWER_STEPS#########LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######
    genai:
      enabled: False # <- enable GenAI for this camera
      
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=4&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=4&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 5
#########LOWER_STEPS#########LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######LOWER_STEPS#######

  lower_patio: #########LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO
    genai:
      enabled: False # <- enable GenAI for this camera
    
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=5&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 6

      # masks are black: they block out areas where you aren't interested in detecting things
    motion:
      mask:
        - 0,148,92,104,184,55,253,0,269,154,272,305,318,125,354,107,345,56,406,60,417,131,504,240,570,360,640,360,640,0,0,0
        #- 0,219,72,169,140,139,146,79,218,73,291,72,362,133,430,143,450,121,488,120,523,98,640,95,640,0,0,0

    zones:
      lower patio:
        coordinates: 
          284,360,303,183,333,157,344,139,357,118,352,99,359,74,382,73,384,110,403,128,499,246,580,360
#########LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO######LOWER_PATIO



  shed: #########SHED##########################SHED#########################SHED#########################SHED#########################SHED#########################SHED#########################
    genai:
      enabled: False # <- enable GenAI for this camera
    
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=6&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
        #- path: http://truenas.local:8082/media=0/channel=5&level=1/track0 # didn't work: two streams avalble from .123 not from motioneye
        #- path: http://truenas.local:8082 # didn't work: two streams avalble from .123 not from motioneye
       #input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://192.168.1.123:554/media=0/channel=6&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

    objects:
      track:
        - face
        - person
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder

    birdseye:
      mode: continuous   #continuous | objects | motion
      order: 7

#########SHED##########################SHED#########################SHED#########################SHED#########################SHED#########################SHED#########################



#########DRIVE##########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################
  drive: 
    genai:
      enabled: False # <- enable GenAI for this camera
      
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=7&level=1/track0 #level1 = SD; track0 media=0 are the only working options tested in ffplay
          roles:
            - detect
        - path: rtsp://192.168.1.123:554/media=0/channel=7&level=0/track0 #level0 = HD ;  track0 media=0 are the only working options tested in ffplay
          roles:
            - record
    
    objects:
      track:
        - face
        - person
        - car
        - bicycle
        - cat
        - dog
        - bird
        - deer
        - fox
        - squirrel
        - badger #placeholder


    zones:
      drive_gravel:
        coordinates: 
          0.256,0.37,0.355,0.375,0.344,0.548,0.693,0.536,0.991,0.866,0.999,0.991,0.207,0.995,0.2,0.595,0.082,0.522
        loitering_time: 0
    motion:
      mask: 
        0.002,0.36,0.179,0.304,0.27,0.269,0.276,0.12,0.361,0.137,0.358,0.349,0.487,0.351,0.658,0.356,0.71,0.358,0.998,0.539,0.993,0.003,0.008,0

    review:
      alerts:
        required_zones: drive_gravel
      detections:
        required_zones: drive_gravel

    birdseye:
      mode: continuous #continuous | objects | motion
    # masks are black: they block out areas where you aren't interested in detecting things
      order: 8
        
#########DRIVE##########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################DRIVE#########################  

logger:
  logs:
      #frigate.record.maintainer: debug
    frigate.object_detection: debug
      #watchdog.blue_gate: debug

camera_groups:
  Woodlands:
    order: 1
    icon: LuActivitySquare
    cameras:
      - blue_gate
      - drive
      - greenhouse
      - lower_patio
      - lower_steps
      - ponds
      - shed
      - upper_patio
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
go2rtc is not used
```

### FFprobe output from your camera

```shell
[STREAM]
index=0
codec_name=hevc
codec_long_name=H.265 / HEVC (High Efficiency Video Coding)
profile=Main
codec_type=video
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=1920
height=1080
coded_width=1920
coded_height=1080
closed_captions=0
film_grain=0
has_b_frames=0
sample_aspect_ratio=N/A
display_aspect_ratio=N/A
pix_fmt=yuvj420p
level=123
color_range=pc
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=unknown
refs=1
id=N/A
r_frame_rate=31/4
avg_frame_rate=16/1
time_base=1/90000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=96
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
[/STREAM]
```
```
[STREAM]
index=1
codec_name=pcm_mulaw
codec_long_name=PCM mu-law / G.711 mu-law
profile=unknown
codec_type=audio
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=s16
sample_rate=8000
channels=1
channel_layout=unknown
bits_per_sample=8
initial_padding=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/8000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=64000
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
[/STREAM]
```
```
[FORMAT]
filename=rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0
nb_streams=2
nb_programs=0
format_name=rtsp
format_long_name=RTSP input
start_time=0.000000
duration=N/A
size=N/A
bit_rate=N/A
probe_score=100
TAG:title=Jabsco NVR Stream
[/FORMAT]
```
```


### Frigate stats

_No response_

### Operating system

Other Linux

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

various hik clones

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/45884109-d061-4b2c-82e2-eed2e368bf90)


### Any other information that may be helpful

_No response_
