### DISCUSSION TITLE
[Bug]: Documentation for PCIe Coral is no longer accurate as of Kernel 6.5.x+

### DISCUSSION THREAD

**Discussion by clockwinder** [blakeblackshear/frigate#16748] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

In the Frigate install documentation for docker: https://docs.frigate.video/frigate/installation#docker

There's a line that reads:
```yaml
    devices:
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
```
As well as a line in: https://docs.frigate.video/frigate/hardware/#google-coral-tpu
`The PCIe and M.2 versions require installation of a driver on the host. Follow the instructions for your version from https://coral.ai/`

From my experience and the info [here](https://github.com/google-coral/edgetpu/issues/822) it looks like that guide is no longer functional in some use cases.  

I think the [install guide](https://docs.frigate.video/frigate/installation#docker) and/or the [recomended hardware](https://docs.frigate.video/frigate/hardware/#google-coral-tpu) should be removed or have a note to help people avoid buying/using hardware with these potential issues.

### Steps to reproduce

- Be on a 6.5.x+ Kernel
- Follow the driver instructions here: https://coral.ai/docs/m2/get-started/#2a-on-linux
- Driver install fails

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Firefox

### Frigate config file

```yaml
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.50:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pass@192.168.1.50:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp #Depreciated in v14
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10
    objects:
      filters:
        person:
          mask:
            - 379,74,379,41,414,42,413,82
    motion:
      mask: 0.728,0.039,0.973,0.035,0.973,0.08,0.729,0.079
    zones:
      Front_Yard:
        coordinates: 
          0.004,0.005,0.104,0.33,0.191,0.197,0.256,0.24,0.274,0.313,0.458,0.309,0.732,0.313,0.72,0.423,0.792,0.427,0.818,0.336,0.9,0.311,1,0.562,1,1,0,1
        loitering_time: 0
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.51:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pass@192.168.1.51:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp #Depreciated in v14
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10


# Optional: Database configuration
    motion:
      mask: 0.675,0.04,0.966,0.041,0.964,0.083,0.676,0.083
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: pci:0
#  coral2:
#    type: edgetpu
#    device: pci:1
#  cpu1:
#    type: cpu
#    num_threads: 6

objects:
  track:
    - person
    - dog
    - cat
    - bird

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30
mqtt:
  enabled: false
  host: 192.168.1.10

ffmpeg:
  #hwaccel_args:
  #  - -hwaccel
  #  - vaapi
  #  - -hwaccel_device
  #  - /dev/dri/renderD128
  #  - -hwaccel_output_format
  #  - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac

record:
  enabled: true
  events:
    pre_capture: 12
    post_capture: 12
    retain:
      default: 30
      mode: active_objects
    objects:
      - person
      - bird
      - cat
      - dog

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
version: 0.14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    #devices:
      #- /dev/bus/usb:/dev/bus/usb
      #- /dev/apex_0:/dev/apex_0
      #- /dev/apex_1:/dev/apex_1
      #- /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/:/config/
      - /frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      #- "1935:1935" # RTMP feeds (deprecated)
      - "8554:8554" # RTSP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: ""
    security_opt:
      - no-new-privileges:true
```

### Relevant Frigate log output

```shell
Not relevant, can't boot frigate without tpu support.
```

### Relevant go2rtc log output

```shell
Not relevant.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Not relevant.

### Screenshots of the Frigate UI's System metrics pages

Can't boot into metric without TPU installed.

### Any other information that may be helpful

Please let me know what other info I can provide, and if any of the info I skipped would be helpful.
