### DISCUSSION TITLE
[Detector Support]:  can’t detect pickup trucks?

### DISCUSSION THREAD

**Discussion by nckrwlmn** [blakeblackshear/frigate#16750] [Detector Support] [answered]
### Describe the problem you are having

Frigate has no clue what a pickup truck is.

![IMG_1946](https://github.com/user-attachments/assets/7c2a93f7-7077-40ae-b77f-c2e294d8d689)

### Version

0.15

### Frigate config file

```yaml
cameras:
  3D_Printers:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:cosine-sighted-retinal@192.168.50.204:554/cam/realmonitor?channel=1&subtype=1     # <----- The stream you want to use for detection
          roles:
            - detect
        - path: 
            rtsp://admin:cosine-sighted-retinal@192.168.50.204:554/cam/realmonitor?channel=1&subtype=0     # <----- The stream you want to use for Record
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 7
    audio:
      enabled: false
    zones:
      3D_Printer_Shelf:
        coordinates: 0.194,0.479,0.37,0.345,0.404,0.712,0.255,0.906
        inertia: 3
        loitering_time: 3
        objects: person

    review:
      alerts:
        required_zones: 3D_Printer_Shelf
    motion:
      threshold: 28
      contour_area: 52
      improve_contrast: true
      mask: 0.695,0.009,0.98,0.007,0.979,0.099,0.693,0.108
    objects:
      mask: 0.788,0.802,1,0.792,1,1,0.806,0.976,0.822,0.825
  Office:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:p8NdtZGa9N3_Hje6@192.168.50.26:554/Streaming/channels/102/ # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://frigate:p8NdtZGa9N3_Hje6@192.168.50.26:554/Streaming/channels/101/ # <----- The stream you want to use for Record
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 7
      annotation_offset: 0
    audio:
      enabled: false
    motion:
      threshold: 46
      contour_area: 30
      improve_contrast: 'true'
    zones:
      In_the_Office:
        coordinates: 
          0.406,0,0.578,0.007,0.588,0.571,0.721,0.67,0.637,0.996,0.259,0.996,0.4,0.83,0.428,0.617
        loitering_time: 4
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: In_the_Office
  
  SWxE_Yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:KHTNaMFesu66h@oa@192.168.50.39:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://frigate:KHTNaMFesu66h@oa@192.168.50.39:554/Streaming/channels/102
          roles:
            - detect
    audio:
      enabled: false
    webui_url: https://192.168.50.39
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    motion:
      threshold: 42
      contour_area: 24
      improve_contrast: 'true'
    zones:
      In_the_yard:
        coordinates: 
          0.969,0.94,0.58,0.219,0.474,0.215,0.337,0.216,0.278,0.233,0.259,0.232,0.258,0.185,0.001,0.249,0.001,0.996,0.989,0.994
        inertia: 5
        loitering_time: 0
    review:
      alerts:
        required_zones: In_the_yard
review:
  alerts:
    labels:
      - car
      - car
      - truck
      - person
      - motorcycle
      - bicycle
  detections:
    labels:
      - person
      - bicycle
      - car
      - truck
      - car
      - motorcycle
      - airplane
      - bus
      - train

audio:
  # Optional: Enable audio events (default: shown below)
  enabled: true
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

record:
  enabled: true
  expire_interval: 30
  retain:
    days: 5
    mode: motion
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: high

  alerts:
    retain:
      days: 15
  detections:
    retain:
      days: 15
snapshots:
  enabled: true
  retain: # retain snapshots for x days
    default: 10
  quality: 75 # 1-100 quality of snapshots

detectors:
  coral:
    type: edgetpu
    device: pci

mqtt:
  enabled: false

tls:
  enabled: false

logger:
  logs:
    frigate.record.maintainer: info

version: 0.15-1

camera_groups:
  Yard:
    order: 1
    icon: LuActivity
    cameras: SWxE_Yard
notifications:
  enabled: 'true'
  email: 
```

### docker-compose file or Docker CLI command

```yaml
Stock portainer compose file from frigate. Can share if needed.
```

### Relevant Frigate log output

```shell
No error
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![IMG_1947](https://github.com/user-attachments/assets/afe2069d-f929-42c1-baf2-325edefdb5c7)

### Any other information that may be helpful

All of my other cameras are working except this one. It’s never detected any pickup, which is most of what it sees out in the countryside. Camera in question is swxe_Yard.

That there is a F150 from Ford, the nation‘s most popular pick up truck. How can this AI model not detect that?

Do you guys think it’s too far away from the camera? Even the person is a 55% lock, which seems a bit low.
