### DISCUSSION TITLE
[Support]: How can we increase the amount of snapshots or alerts that show up in the live camera view?

### DISCUSSION THREAD

**Discussion by bozoboo** [blakeblackshear/frigate#16751] [General Support]
### Describe the problem you are having

I'm trying to increase the amount of snapshots or reviews are posted in the live camera section.

Is there a way we can increase the time frame? 

Whenever I log into my pc, I like to see what has occurred in the last 1-2 hours while also looking at the live view of all the cameras. 

Its the section above the live cameras.

Thanks

### Version

0.15-1

### Frigate config file

```yaml
go2rtc:
  streams:
    HighDrivewayCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.252/cam/realmonitor?channel=1&subtype=0
    HighDrivewaySub:
      - rtsp://admin:Dldl8989!!@192.168.1.252/cam/realmonitor?channel=1&subtype=1
    LowerDrivewayCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.251/cam/realmonitor?channel=1&subtype=0
    LowerDrivewaySub:
      - rtsp://admin:Dldl8989!!@192.168.1.251/cam/realmonitor?channel=1&subtype=1
    SidegateCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.31:554/Streaming/Channels/101
    SidegateSub:
      - rtsp://admin:Dldl8989!!@192.168.1.31:554/Streaming/Channels/102
    FrontdoorCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.26:554/Streaming/Channels/101
    FrontdoorSub:
      - rtsp://admin:Dldl8989!!@192.168.1.26:554/Streaming/Channels/102
    FrontyardCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.40:554/Streaming/Channels/101
    FrontyardSub:
      - rtsp://admin:Dldl8989!!@192.168.1.40:554/Streaming/Channels/102
    GarageCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.38:554/Streaming/Channels/101
    GarageSub:
      - rtsp://admin:Dldl8989!!@192.168.1.38:554/Streaming/Channels/102
    KitchenCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.39:554/Streaming/Channels/101
    KitchenSub:
      - rtsp://admin:Dldl8989!!@192.168.1.39:554/Streaming/Channels/102
    OliviaCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.34:554/Streaming/Channels/101
    OliviaSub:
      - rtsp://admin:Dldl8989!!@192.168.1.34:554/Streaming/Channels/102
    PlayroomCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.44:554/Streaming/Channels/101
    PlayroomSub:
      - rtsp://admin:Dldl8989!!@192.168.1.44:554/Streaming/Channels/102
    StairsCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.30:554/Streaming/Channels/101
    StairsSub:
      - rtsp://admin:Dldl8989!!@192.168.1.30:554/Streaming/Channels/102
    AbyssCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.33:554/Streaming/Channels/101
    AbyssSub:
      - rtsp://admin:Dldl8989!!@192.168.1.33:554/Streaming/Channels/102
    BackyardCamera:
      - rtsp://admin:Dldl8989!!@192.168.1.41:554/Streaming/Channels/101
    BackyardSub:
      - rtsp://admin:Dldl8989!!@192.168.1.41:554/Streaming/Channels/102
  webrtc:
    candidates:
      - 192.168.1.14:8555
      - stun:8555
detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  enabled: true
   # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 640
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 480
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 10
  # Optional: enables detection for the camera (default: True)
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 5
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 300
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
objects:
  filters:
    car:
      min_score: 0.45
    person:
      min_score: 0.45
  track:
    - person
    - bicycle
    - car
    - boat
    - motorcycle
    - bird
    - cat
    - dog
review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person
      - speech
birdseye:
  enabled: true
  mode: objects
mqtt:
  enabled: true
  host: 192.168.1.13
  topic_prefix: frigate
  client_id: frigate
  user: concac
  password: Dldl8989!!
cameras:
  Abyss:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/AbyssCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/AbyssSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: AbyssCamera
    detect:
      enabled: true
    motion:
      mask: 0.024,0,0.026,0.069,0.531,0.071,0.529,0,0.16,0.006
      threshold: 19
      contour_area: 8
      improve_contrast: 'true'
    zones:
      side_abyss:
        coordinates: 0,0.081,0.502,0.115,0.475,0.948,0,0.853
        inertia: 1
        loitering_time: 0
        objects: person
    review:
      alerts: {}
      detections:
        required_zones: side_abyss
    ui:
      order: 12
  Backyard:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/BackyardCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/BackyardSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: BackyardCamera
    detect:
      enabled: true
    motion:
      mask: 0.038,0.005,0.042,0.07,0.532,0.071,0.524,0.005
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      back_yard:
        coordinates: 0.869,0.989,0.138,0.489,0.686,0.136,0.915,0.261
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      detections:
        required_zones: back_yard
      alerts: {}
    ui:
      order: 10
  FrontdoorCamera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/FrontdoorCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/FrontdoorSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: FrontdoorCamera
    detect:
      enabled: true
    motion:
      mask: 0.058,0.037,0.058,0.089,0.543,0.1,0.54,0.037
      threshold: 30
      contour_area: 15
      improve_contrast: true
    zones:
      front_door:
        coordinates: 0.038,0.998,1,1,1,0.686,0.923,0.461,0.095,0.638
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      detections:
        required_zones: front_door
      alerts: {}
    ui:
      order: 3
  Frontyard:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/FrontyardCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/FrontyardSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: FrontyardCamera
    detect:
      enabled: true
    motion:
      mask: 0.561,0.94,0.56,0.989,0.971,0.998,0.974,0.922
      threshold: 20
      contour_area: 7
      improve_contrast: 'true'
    zones:
      front_yard:
        coordinates: 0.006,0.754,0.503,0.896,0.646,0.3,0.714,0.021,0.283,0
        inertia: 2
        loitering_time: 0
        objects: person
    review:
      detections:
        required_zones: front_yard
      alerts: {}
    ui:
      order: 4
  Garage:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/GarageCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/GarageSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: GarageCamera
    detect:
      enabled: true
    motion:
      mask: 0.47,0.935,0.47,0.984,0.961,0.99,0.953,0.921
    ui:
      order: 6
    zones:
      garage:
        coordinates: 0.169,0,0.177,0.246,0.586,0.237,0.591,0.007
        loitering_time: 0
    review:
      detections:
        required_zones: garage
  Kitchen:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/KitchenCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/KitchenSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: KitchenCamera
    detect:
      enabled: true
    motion:
      mask: 0.034,0.006,0.035,0.066,0.532,0.07,0.53,0.002
    ui:
      order: 7
  Olivia:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/OliviaCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/OliviaSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: OliviaCamera
    detect:
      enabled: true
    motion:
      mask: 0.462,0.932,0.459,1,0.961,0.985,0.96,0.922
    ui:
      order: 9
    zones:
      olivia:
        coordinates: 0.012,0.014,0.975,0.022,0.983,0.893,0.009,0.85
        loitering_time: 0
        inertia: 3
        objects: person
    review:
      detections:
        required_zones: olivia
  Playroom:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/PlayroomCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/PlayroomSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: PlayroomCamera
    detect:
      enabled: true
    motion:
      mask: 0.575,0.898,0.572,0.96,0.987,0.966,0.992,0.883
    ui:
      order: 8
    zones:
      play:
        coordinates: 0.009,0.168,0.011,0.953,0.976,0.982,0.925,0.257
        loitering_time: 0
    review:
      detections:
        required_zones: play
  Sidegate:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/SidegateCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/SidegateSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: SidegateCamera
    detect:
      enabled: true
    motion:
      mask: 0.039,0.032,0.036,0.099,0.529,0.108,0.526,0.036
      threshold: 15
      contour_area: 6
      improve_contrast: 'true'
    zones:
      side_gate:
        coordinates: 0.002,0.138,0.613,0.107,0.997,0.644,0.997,0.99,0.008,0.99
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      detections:
        required_zones: side_gate
      alerts: {}
    ui:
      order: 5
  Stairs:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/StairsCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/StairsSub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: StairsCamera
    detect:
      enabled: true
    motion:
      mask: 0.496,0.008,0.496,0.071,0.985,0.07,0.985,0
      threshold: 40
      contour_area: 17
      improve_contrast: true
    zones:
      stair:
        coordinates: 0.673,0.357,0.709,0.434,0.608,0.638,0.587,0.555
        inertia: 3
        loitering_time: 2
        objects: person
    review:
      alerts: {}
      detections:
        required_zones: stair
    ui:
      order: 8
  HighDrivewayCamera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/HighDrivewayCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/HighDrivewaySub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: HighDrivewayCamera
    detect:
      enabled: true
    motion:
      mask: 0.554,0.037,0.554,0.11,0.975,0.118,0.965,0.023
      threshold: 30
      contour_area: 13
      improve_contrast: 'true'
    zones:
      high_driveway:
        coordinates: 0.003,0.997,0.719,0.995,0.84,0.44,0.823,0.264,0.778,0.233,0.558,0.157,0,0.322
        inertia: 3
        loitering_time: 0
    review:
      detections:
        required_zones: high_driveway
      alerts: {}
    ui:
      order: 1
  LowerDrivewayCamera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://192.168.1.14:8554/LowerDrivewayCamera # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.14:8554/LowerDrivewaySub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: LowerDrivewayCamera
    detect:
      enabled: true
    motion:
      mask: 0.009,0,0.198,0.115,1,0.34,1,0
      threshold: 34
      contour_area: 10
      improve_contrast: 'true'
    zones:
      low_driveway:
        coordinates: 0.161,0.127,0.56,0.232,1,0.372,0.997,0.991,0.005,0.993,0,0.196
        inertia: 2
        loitering_time: 0
        objects:
          - person
          - car
    review:
      detections:
        required_zones: low_driveway
      alerts: {}
    ui:
      order: 2
record:
  enabled: true
  sync_recordings: false
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7
snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  timestamp: false
  retain:
    default: 10
    objects:
      person: 10
version: 0.15-1
camera_groups:
  test:
    order: 1
    icon: LuAlertCircle
    cameras: birdseye
#ui:
#  timezone: America/Los_Angeles
```

### Relevant Frigate log output

```shell
na
```

### Relevant go2rtc log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
na
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hadua
