### DISCUSSION TITLE
MQTT Payload ID question

### DISCUSSION THREAD

**Discussion by Struggle2020** [blakeblackshear/frigate#16754] [Ask A Question] [answered]
Hello,

I'm writing a HA automation and trying to set up a condition on review alerts where it only succeeds if:

1. It's type == new and object is person
2. It's type == update and person wasn't on the before object list but is on the after object list.

Everything is working however i'm struggling to work out which of the detection ids refer to the person and not the dog/car or whatever else may be there in after objects list.

For example:

```
payload_json:
    type: update
    before:
      id: 1740305812.111463-hmvhd3
      camera: NUC_1
      start_time: 1740305812.111463
      end_time: null
      severity: detection
      thumb_path: /media/frigate/clips/review/thumb-NUC_1-1740305812.111463-hmvhd3.webp
      data:
        detections:
          - 1740305811.507561-4j0ksj
        objects:
          - dog
        sub_labels: []
        zones:
          - inside_gate
        audio: []
    after:
      id: 1740305812.111463-hmvhd3
      camera: NUC_1
      start_time: 1740305812.111463
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-NUC_1-1740305812.111463-hmvhd3.webp
      data:
        detections:
          - 1740305813.320503-qkuzdg
          - 1740305811.507561-4j0ksj
        objects:
          - person
          - dog
        sub_labels: []
        zones:
          - inside_gate
        audio: []
```

Is there any way to always get the person detection id and not the other ones? In this case it was 1740305813.320503-qkuzdg so i'm assuming it's always the first index [0] but if it was dog -> person -> dog it might be the middle one?

I'm not sure how to tackle this problem except from stopping all detections/alerts on everything but people.

Thanks
