### DISCUSSION TITLE
[Camera Support]: Reolink RLC-842A and Reolink E1 Zoom - no audio in livestream on Frigate WEBUI or HomeAssistant

### DISCUSSION THREAD

**Discussion by roelbeun** [blakeblackshear/frigate#16760] [Camera Support] [answered]
### Describe the problem you are having

I'm unable to get audio in a Live view on the Frigate WebUI or in Home Assistant (Advanced Camera card). In earlier versions (before the WebUI revamp) this worked. I don't see any audio toggle in the Live View screen either.

Recordings for both camera's do contain audio. Output is AAC by default for these camera's

### Version

0.15.0-cea210d

### What browser(s) are you using?

Arc (Version 1.83.0 (59042)) and Chrome (Version 133.0.6943.127 (Official Build) (arm64))

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.161
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 14
    mode: all
  alerts:
    retain:
      days: 50
  detections:
    retain:
      days: 50
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 50
    objects:
      person: 50

genai:
  enabled: true
  provider: openai
  api_key: '{FRIGATE_OPENAI_API_KEY}'
  model: gpt-4o

go2rtc:
  streams:
    camera1_main:
      - http://192.168.0.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera1_sub:
      - rtsp://<user>:<password>@192.168.0.71:554/h264Preview_01_sub
    camera2_main:
      - http://192.168.0.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera2_sub:
      - rtsp://<user>:<password>@192.168.0.72:554/h264Preview_01_sub
    camera3_main:
      - http://192.168.0.73/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera3_sub:
      - rtsp://<user>:<password>@192.168.0.73:554/h264Preview_01_sub
    camera4_main:
      - http://192.168.0.74/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera4_sub:
      - rtsp://<user>:<password>@192.168.0.74:554/h264Preview_01_sub
    camera5_main:
      - http://192.168.0.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera5_sub:
      - rtsp://<user>:<password>@192.168.0.75:554/h264Preview_01_sub
    camera6_main:
      - http://192.168.0.76/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera6_sub:
      - rtsp://<user>:<password>@192.168.0.76:554/h264Preview_01_sub
    camera7_main:
      - http://192.168.0.91/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<password>
    camera7_sub:
      - rtsp://<user>:<password>@192.168.0.91:554/h264Preview_01_sub

birdseye:
  enabled: false
  mode: continuous
  restream: true

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac

cameras:
  # Camera 1
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera1_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      threshold: 100
      mask:
        # date and time
        - 444,356,634,350,637,333,445,335
  # Camera 2
  Camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera2_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        # date and time
        - 444,356,634,350,637,333,445,335
  # Camera 3
  Camera3:
    genai:
      enabled: true
      use_snapshot: true
      objects:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera3_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    snapshots:
      required_zones:
        - cam_3_zone_oprit
    zones:
      cam_3_zone_oprit:
        coordinates: 288,360,640,360,547,122,411,93,148,271
    motion:
      threshold: 100
      mask:
        - 303,360,143,241,37,242,48,360
        - 640,0,619,28,619,122,590,99,606,0,561,0,552,128,554,360,640,360
        - 236,205,325,135,349,158,264,230
        # date and time
        - 444,356,634,350,637,333,445,335
  # Camera 4
    review:
      alerts:
        required_zones:
          - cam_3_zone_oprit
  Camera4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera4_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 640,360,385,360,93,49,94,0,640,0
  # Camera 5
  Camera5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera5_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    zones:
      cam5_zone_oprit:
        coordinates: 0,246,81,123,301,126,456,127,590,136,640,137,640,208,640,360,0,360
      cam5_zone_straat:
        coordinates: 0,0,0,131,459,131,640,137,640,0
    motion:
      threshold: 100
      mask:
        - 1,0,0.706,0,0.834,0.233,1,0.375
        - 0.37,0,0,0,0,0.208
        - 0.203,0.342,0.013,0.353,0.072,0.164,0.184,0.156
        - 0.694,0.989,0.991,0.972,0.995,0.925,0.695,0.931
  Camera6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera6_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera6_main
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      threshold: 100
      mask:
        - 640,0,640,307,512,205,424,91,378,0
        - 302,0,33,0,53,132,169,204,355,227,371,200,385,85
        - 232,232,180,261,280,360,374,360,389,260
        # date and time
        - 444,356,634,350,637,333,445,335
  # Camera 7 - e1 zoom
  Camera7:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/camera7_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera7_main
          roles:
            - record
    onvif:
      host: 192.168.0.91
      port: 8000
      user: <user>
      password: <password>
    objects:
      track:
        - person
    motion:
      threshold: 100
      mask:
        # date and time
        - 0.688,0.988,1,0.985,1,0.945,0.688,0.946

version: 0.15-1
camera_groups:
  Monitor:
    order: 1
    icon: LuMonitor
    cameras:
      - Camera3
      - Camera4
      - Camera5
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{
"cameras": {
"Camera1": {
"camera_fps": 5.1,
"process_fps": 5.1,
"skipped_fps": 0,
"detection_fps": 0,
"detection_enabled": true,
"pid": 472,
"capture_pid": 528,
"ffmpeg_pid": 532,
"audio_rms": 0,
"audio_dBFS": 0
},
"Camera2": {
"camera_fps": 5,
"process_fps": 5,
"skipped_fps": 0,
"detection_fps": 1.7,
"detection_enabled": true,
"pid": 480,
"capture_pid": 531,
"ffmpeg_pid": 536,
"audio_rms": 0,
"audio_dBFS": 0
},
"Camera3": {
"camera_fps": 5.1,
"process_fps": 5.1,
"skipped_fps": 0,
"detection_fps": 0.2,
"detection_enabled": true,
"pid": 488,
"capture_pid": 535,
"ffmpeg_pid": 541,
"audio_rms": 0,
"audio_dBFS": 0
},
"Camera4": {
"camera_fps": 5.1,
"process_fps": 5.1,
"skipped_fps": 0,
"detection_fps": 0,
"detection_enabled": true,
"pid": 496,
"capture_pid": 547,
"ffmpeg_pid": 575,
"audio_rms": 0,
"audio_dBFS": 0
},
"Camera5": {
"camera_fps": 5,
"process_fps": 5.1,
"skipped_fps": 0,
"detection_fps": 0,
"detection_enabled": true,
"pid": 504,
"capture_pid": 576,
"ffmpeg_pid": 595,
"audio_rms": 0,
"audio_dBFS": 0
},
"Camera6": {
"camera_fps": 5.1,
"process_fps": 5.1,
"skipped_fps": 0,
"detection_fps": 0,
"detection_enabled": true,
"pid": 512,
"capture_pid": 592,
"ffmpeg_pid": 601,
"audio_rms": 0,
"audio_dBFS": 0
},
"Camera7": {
"camera_fps": 5,
"process_fps": 5,
"skipped_fps": 0,
"detection_fps": 0,
"detection_enabled": true,
"pid": 520,
"capture_pid": 599,
"ffmpeg_pid": 623,
"audio_rms": 0,
"audio_dBFS": 0
}
},
"detectors": {
"coral": {
"inference_speed": 8.2,
"detection_start": 0,
"pid": 388
}
},
"detection_fps": 1.9,
"gpu_usages": {
"intel-qsv": {
"gpu": "1.23%",
"mem": "-%",
"clients": {
"532": "3.88%",
"536": "3.03%",
"541": "3.85%",
"575": "2.45%",
"595": "2.56%",
"601": "3.48%",
"623": "5.03%"
}
}
},
"cpu_usages": {
"1": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
},
"15": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6-linux-init-shutdownd"
},
"16": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
},
"24": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-oneshot-runner"
},
"25": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-fdholder"
},
"26": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync"
},
"27": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync-log"
},
"28": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate"
},
"29": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate-log"
},
"30": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc"
},
"31": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-healthcheck"
},
"32": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-log"
},
"33": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx"
},
"34": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx-log"
},
"45": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
},
"46": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
},
"87": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
},
"88": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
},
"89": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
},
"90": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
},
"98": {
"cpu": "16.3",
"cpu_average": "15",
"mem": "0.1",
"cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
},
"106": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user go2rtc-healthcheck"
},
"115": {
"cpu": "2.8",
"cpu_average": "6",
"mem": "1.9",
"cmdline": "python3 -u -m frigate"
},
"130": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: master process nginx"
},
"164": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"165": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"172": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"189": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: worker process"
},
"214": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: cache manager process"
},
"237": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user certsync"
},
"372": {
"cpu": "0.3",
"cpu_average": "1",
"mem": "0.7",
"cmdline": "frigate.recording_manager"
},
"381": {
"cpu": "0.7",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.review_segment_manager"
},
"388": {
"cpu": "1.7",
"cpu_average": "2",
"mem": "0.6",
"cmdline": "frigate.detector.coral"
},
"407": {
"cpu": "2.0",
"cpu_average": "1",
"mem": "0.6",
"cmdline": "frigate.output       "
},
"412": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"419": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"426": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"433": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"441": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"448": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"455": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"472": {
"cpu": "0.8",
"cpu_average": "0",
"mem": "0.7",
"cmdline": "frigate.process:Camera1"
},
"480": {
"cpu": "5.3",
"cpu_average": "4",
"mem": "0.7",
"cmdline": "frigate.process:Camera2"
},
"488": {
"cpu": "1.1",
"cpu_average": "1",
"mem": "0.7",
"cmdline": "frigate.process:Camera3"
},
"496": {
"cpu": "1.0",
"cpu_average": "2",
"mem": "0.7",
"cmdline": "frigate.process:Camera4"
},
"504": {
"cpu": "0.9",
"cpu_average": "0",
"mem": "0.7",
"cmdline": "frigate.process:Camera5"
},
"512": {
"cpu": "0.8",
"cpu_average": "0",
"mem": "0.7",
"cmdline": "frigate.process:Camera6"
},
"520": {
"cpu": "0.8",
"cpu_average": "1",
"mem": "0.7",
"cmdline": "frigate.process:Camera7"
},
"528": {
"cpu": "0.5",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera1"
},
"531": {
"cpu": "0.6",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera2"
},
"532": {
"cpu": "1.0",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera1_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"535": {
"cpu": "0.5",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera3"
},
"536": {
"cpu": "1.1",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera2_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"541": {
"cpu": "1.1",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera3_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"547": {
"cpu": "0.5",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera4"
},
"575": {
"cpu": "1.1",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera4_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"576": {
"cpu": "0.6",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera5"
},
"592": {
"cpu": "0.5",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera6"
},
"595": {
"cpu": "1.1",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera5_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"599": {
"cpu": "0.6",
"cpu_average": "0",
"mem": "0.6",
"cmdline": "frigate.capture:Camera7"
},
"601": {
"cpu": "1.0",
"cpu_average": "0",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera6_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=360:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"623": {
"cpu": "1.3",
"cpu_average": "1",
"mem": "0.2",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera7_sub -r 5 -vf vpp_qsv=framerate=5:w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"3652": {
"cpu": "2.7",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera3_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera3@%Y%m%d%H%M%S%z.mp4"
},
"3653": {
"cpu": "3.0",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera1_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera1@%Y%m%d%H%M%S%z.mp4"
},
"3654": {
"cpu": "2.9",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera2_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera2@%Y%m%d%H%M%S%z.mp4"
},
"3655": {
"cpu": "2.3",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera5_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera5@%Y%m%d%H%M%S%z.mp4"
},
"3656": {
"cpu": "2.8",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera6_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera6@%Y%m%d%H%M%S%z.mp4"
},
"3657": {
"cpu": "3.0",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera4_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera4@%Y%m%d%H%M%S%z.mp4"
},
"3658": {
"cpu": "3.0",
"cpu_average": "2",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/camera7_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Camera7@%Y%m%d%H%M%S%z.mp4"
},
"4254": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 60"
},
"4278": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 30s"
},
"frigate.full_system": {
"cpu": "11.2",
"mem": "24.4"
}
},
"service": {
"uptime": 823,
"version": "0.15.0-cea210d",
"latest_version": "0.15.0",
"storage": {
"/media/frigate/recordings": {
"total": 3651993.6,
"used": 3631880.2,
"free": 20113.4,
"mount_type": "nfs"
},
"/media/frigate/clips": {
"total": 953403,
"used": 812616.6,
"free": 140786.4,
"mount_type": "fuse.shfs"
},
"/tmp/cache": {
"total": 953.7,
"used": 510.1,
"free": 443.5,
"mount_type": "tmpfs"
},
"/dev/shm": {
"total": 256,
"used": 115.8,
"free": 140.2,
"mount_type": "tmpfs"
}
},
"temperatures": {},
"last_updated": 1740317671
},
"processes": {
"recording": {
"pid": 372
},
"review_segment": {
"pid": 381
},
"go2rtc": {
"pid": 98
}
}
}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-842A and Reolink E1 Zoom

### Screenshots of the Frigate UI's System metrics pages

N/A

### Any other information that may be helpful

Camera 1 to 6 are the Reolink RLC-842A (outside camera's)
Camera 7 is the Reolink E1 Zoom (inside camera)

Camera 7 has a HTTP sub stream as well, but that one returns failures on ffmpeg hence returning to rtsp

No errors in the log currently, just no audio in Live View.

No audio in the go2rtc dashboards streams either.

The streams give audio when i connect to them via VLC.

ps. Not sure if the detect of substream resolution needs to be present. Saw in another thread frigate should be able to detect this itself?

**Comment by NickM-27** [comment]
See https://docs.frigate.video/configuration/live#setting-stream-for-live-ui

**Reply by roelbeun** [reply]
Yes I've tested the opus tag as stated in that doc but it did not work out. Let me test again and paste the log here!

**Reply by hawkeye217** [reply, marked as answer]
You need to either have your camera names match your stream names in go2rtc (eg `camera1_main` needs to be `Camera1`, etc) or use the `stream_name` directive.

```
cameras:
  Camera1:
    ...
    live:
      stream_name: camera1_main
```

**Reply by roelbeun** [reply]
Thanks for that tip! that does give me audio and the audio button in live view. It also gives me the better (main) quality of the stream. Spend 3 hours on this yesterday (learnt a ton though), glad it has been resolved!

Some follow-up questions.

1. Does it give me the go2rtc stream (e.g. camera1_main) or the direct stream for the camera? I would expect I need to ask for something like _rtsp://127.0.0.1:8554/camera1_main_
2. Possibly a question for the HomeAssistant Camera card integration, but I don't get the audio on the HomeAssistant card, also it still the sub stream (bad quality). Ive checked the _automatic_ option and the _go2rtc_ option. 
3. Can i skip the following camera settings so frigate will detect the resolution automatically? (sorry not related to this discussion)
```
  detect:
      width: 640
      height: 360
```

**Reply by hawkeye217** [reply]
> * Does it give me the go2rtc stream (e.g. camera1_main) or the direct stream for the camera? I would expect I need to ask for something like _rtsp://127.0.0.1:8554/camera1_main_
>

The `stream_name` parameter only accepts go2rtc stream names, not urls. By specifying the go2rtc stream name, you're instructing Frigate to pull the go2rtc stream for the live view. 
 
> * Possibly a question for the HomeAssistant Camera card integration, but I don't get the audio on the HomeAssistant card, also it still the sub stream (bad quality). Ive checked the _automatic_ option and the _go2rtc_ option.
> 

Not 100% sure, but you may need to specify the stream name somewhere there as well.

> * Can i skip the following camera settings so frigate will detect the resolution automatically? (sorry not related to this discussion)

You could try, but there's no harm in leaving it in and explicitly defining it.

**Reply by roelbeun** [reply]
Yes found it for HomeAssistant. You can specify the stream name. This will give audio, the higher quality and PTZ (if applicable). More info [here](https://card.camera/#/configuration/cameras/live-provider)

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.camera7
    live_provider: go2rtc
    go2rtc:
      stream: camera7_main
```

Thanks for the tips and quick replies @hawkeye217 and @NickM-27 ! Really appreciated :)
