### DISCUSSION TITLE
[Config Support]: Frigate integration Failed to connect

### DISCUSSION THREAD

**Discussion by rwagner3** [blakeblackshear/frigate#16769] [Config Support] [answered]
### Describe the problem you are having

When I go to Settings -> Devices and Services -> +Add Integration, and attempt to install Frigate, it suggests using `http://ccab4aaf-frigate:5000`. This returns Failed to connect.

I have Frigate (Full Access) add-on installed and everything seems to be working, in that I have a working camera that detects and records.

![image](https://github.com/user-attachments/assets/03c4a4cb-81bc-4c4b-81b2-7169a08edec6)

I've not had luck getting to Frigate from outside of HA OS Add-on, but within HA OS it seems to work OK other than I cannot get the Integration to connect. I saw that the user and pass was optional, so I attempted with it empty, and setting a user in HA OS and using that and both ways "Failed to connect".

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: 10.2.1.188
  user: mqtt-svc
  password: xx

cameras:
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@10.4.1.107:554/live/ch0 #Change as per your camera documentation for high quality feed
          roles:
            - record
        - path: rtsp://xx:xx@10.4.1.107:554/live/ch1 #Change as per your camera documentation for low quality feed
          roles:
            - detect
    detect:
      width: 640  # resolution of detection channel 1
      height: 360 # resolution of detection channel 1
      fps: 10
    record:
      enabled: true
      retain:
        days: 0 #The number of days a recording will be kept for after a motion is detected.
        mode: motion
      alerts:
        retain:
          days: 1
      detections:
        retain:
          days: 1
    objects:
      track:
        - person
        - cat

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
database:
  path: /config/frigate.db

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
I see nothing obvious to me in the logging when I made the attempt and get the failed to connect.

2025-02-24 02:14:26.157224061  172.30.32.2 - - [23/Feb/2025:21:14:26 -0500] "GET /ws HTTP/1.1" 101 633 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36" "127.0.0.1, 172.30.32.1"
2025-02-24 02:14:35.989656825  127.0.0.1 - - [23/Feb/2025:21:14:35 -0500] "" 400 0 "-" "-" "-"
2025-02-24 02:15:18.813718406  172.30.32.2 - - [23/Feb/2025:21:15:18 -0500] "GET / HTTP/1.1" 200 2651 "-" "HomeAssistantSupervisor/2025.02.1 aiohttp/3.11.12 Python/3.13" "-"
2025-02-24 02:15:36.026556967  127.0.0.1 - - [23/Feb/2025:21:15:36 -0500] "" 400 0 "-" "-" "-"
```

### Relevant go2rtc log output

```shell
Not sure how to get this.
```

### Frigate stats

```json
Not sure how to get this.
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
NA all HA OS based, no docker.
```

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/29487b16-b3fb-4597-acf0-6883d3daa5a7)
