### DISCUSSION TITLE
[Support]: Exporting results in an audio only MP4 file

### DISCUSSION THREAD

**Discussion by crowbarsolutions** [blakeblackshear/frigate#16771] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When exporting video from my timeline, frigate only exports an MP4 file that contains an AAC audio stream. No video at all. Playback from the history timeline in my browser works without issues, as well as when I manually view the segments in the recording folder. It is only when I export it that I only get an audio only file.

I have successfully exported video in the past with this setup, however it was with a previous version. No errors appear in the logs during the export.

### Steps to reproduce

1. Go into my "backyard" camera, select Feb 22, and see several events in my timeline, I would like to export about an hours worth of recordings
2. Click the export button
3. Select an export method - custom, or select from timeline
4. Select a range in the timeline, click the "preview export" button at the top and confirm that it is what I want, and see that video+audio is playing correctly.
5. Hit the"save export" button
6. Observe message "Successfully started export. View the file in the /exports folder."
7. View the MP4 file in the export folder. It is very small, when inspecting with VLC it appears as the correct length, but only contains an AAC audio stream
8. When I try to preview the export in the browser, it will appear with no video - just a white screen, with audio.

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

Firefox 135.0.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.12
  user: frigate
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi
  path: "5.0"

go2rtc:
  streams:
    backyard:
      - rtsp://xxx:xxx@192.168.1.50/stream1
      - ffmpeg:backyard#audio=aac
    backyard_sub:
      - ffmpeg:rtsp://xxx:xxx@192.168.1.50/stream2#audio=opus#video=copy
      - tapo://xxx@192.168.1.50
      #- "ffmpeg:backyard_sub#audio=aac"
  webrtc:
    candidates:
      - 192.168.1.14:8555
      - stun:8555

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  backyard:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://localhost:8554/backyard?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        #- path: rtsp://localhost:8554/backyard_sub
        #  input_args: preset-rtsp-restream
        #  roles:
        #    - detect
    live:
      stream_name: backyard_sub
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 405,30,405,0,0,0,0,30
    objects:
      track: # support multiple of: person, car, dog, cat, bicycle, bus
        - person
      filters:
        person:
          threshold: 0.85
          #min_area: 9000
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    snapshots:
      enabled: true
      retain:
        default: 30
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
No errors appear in the logs during the export
```

### Relevant go2rtc log output

```shell
No errors appear in the logs during the export
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tapo C320WS

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/80d6286c-a23d-4358-aa17-54a15ca0198e)

### Any other information that may be helpful

Frigate is running in docker, inside a proxmox privileged LXC container, with an intel i5-6500 doing all the heavy lifting.
