### DISCUSSION TITLE
[Camera Support]: Reolink trackmix poe autop-tracking

### DISCUSSION THREAD

**Discussion by mmaaligema** [blakeblackshear/frigate#16775] [Camera Support]
### Describe the problem you are having

Hi !
I currently have 2 reolink trackmix poe auto.tracking that I can't get to work properly in frigate. What is the correct frigate.yaml file on such a camera

Hi!
I currently have 2 reolink trackmix poe auto.tracking that I can't get to work properly in frigate. What is the correct fregate.yaml file on such a camera?
I have other cameras that work fine like amcreast camera.
Then I have such a setup.

  altanen:
    ffmpeg:
      inputs:
      - path: rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://admin:password@192.168.1.5:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
        roles:
        - record
      output_args:
                record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1080
      height: 720
      fps: 5

### Version

15.1

### Frigate config file

```yaml
innegarden_overgripande:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.8:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
```

### Relevant Frigate log output

```shell
vet ej
```

### Relevant go2rtc log output

```shell
vet ej
```

### FFprobe output from your camera

```shell
vet ej
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink trackmix poe 

### Screenshots of the Frigate UI's System metrics pages

a
