### DISCUSSION TITLE
[Camera Support]: A few questions about setting up old MJPEG cameras (config, resolution resizing, timestamps)

### DISCUSSION THREAD

**Discussion by lukasig** [blakeblackshear/frigate#16782] [Camera Support] [answered]
### Describe the problem you are having

I am trying to set up some older models (640x480) mjpeg streaming cameras, but I can't seem to understand a few things:

**1. CONFIG:**
i have tried setting them up without go2rtc
```
cameras:
  MJPEG_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.10:554/videostream.cgi
          input_args: preset-http-mjpeg-generic
```
this for some reason did not save recordings even if i added output_args **_preset-record-mjpeg_** at the camera level.

then the go2rtc route:
```
go2rtc:
  streams:
    CAM1:
      - rtsp://admin:password@192.168.1.10:554/videostream.cgi
      - "ffmpeg:CAM2#video=h264#hardware"
cameras:
  MJPEG_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM1
```
this saves recordings, but I am confused ast to if I should use **_preset-http-mjpeg-generic_** or _**preset-rtsp-restream**_ for input_args at the camera level, because the stream is ureliable but that could be the fault of cheap camera even though wired.

**2. RESOLUTION & FPS**
The camera has a 4/3 aspect ratio but for some reason the stream is coming stretched to a 16/9 ratio (ffprobe: 640x360). I have set up the FPS for the original camera stream to 5fps using the web interface. Since I am re-encoding the feed anyway, how should I approach resizing the output at 640x480 and 5fps?

**3. TIMESTAMPS**
The camera UI does not offer options for adding a timestamp to the output stream.
Again, since the stream is re-encoded, I would guess there should not be a problem of adding a timestamp on the output feed. How would this be done in frigate?

thank you

### Version
0.15-1

### Hardware
intel N95 - 8GB RAM - SATA SSD

### Operating system
Debian

### Install method
Docker Compose

### Object Detector
OpenVino

### Network connection
Wired

### Camera make and model
TriVision, Wanscam

**Comment by hawkeye217** [comment, marked as answer]
go2rtc is the recommended method for mjpeg cameras if you plan to use recording. You should use `preset-rtsp-restream` for any cameras you are using with go2rtc.

As far as the aspect ratio, you could try explicitly setting the `detect` width and height in your config.

```
cameras:
  MJPEG_cam:
    ffmpeg:
      ....
    detect:
      width: 640
      height: 360
```

For adding a timestamp, other users have asked the question before and you can likely find answers in past discussions. Here's one that quickly came up: https://github.com/blakeblackshear/frigate/discussions/10951

**Reply by lukasig** [reply]
Thank you

any idea on setting the new stream to 5fps?

**Reply by hawkeye217** [reply]
Just add `fps: 5` to your detect params:

```
detect:
  width: 640
  height: 360
  fps: 5
```
