### DISCUSSION TITLE
[Support]:

### DISCUSSION THREAD

**Discussion by Mareckil** [blakeblackshear/frigate#16784] [General Support]
### Describe the problem you are having

I have two cameras connected via wired connection. From time to time, one or both of them fail to receive frames from the detect stream. The live view works correctly, and for example, in the Home Assistant interface, the image displayed by the Frigate card looks fine, with no signs of an issue. However, when I open the Frigate panel, a black camera window appears with an error message about frame reception problems. After a short while, it tries again, and the live stream image appears.

At first, I thought it was an issue with the cameras, but the RTSP streams in their native application work fine on all streams. Restarting Frigate is the only thing that helps.

### Version

0.15.0

### What browser(s) are you using?

Firefox 135.0.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.11.94
  port: 1883
  user: mqtt
  password: passwd
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

logger:
  default: debug

detectors:
  coral:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    wejscie:
      - rtsp://user:passwd@192.168.11.21:554/live/ch0
      - ffmpeg:wejscie#video=copy
    wejscie_detect:
      - rtsp://user:passwd@192.168.11.21:554/live/ch1
      - ffmpeg:wejscie_detect#video=copy
    ogrod:
      - rtsp://user:passwd@192.168.11.22:554/live/ch0
      - ffmpeg:ogrod#video=copy
    ogrod_detect:
      - rtsp://user:passwd@192.168.11.22:554/live/ch1
      - ffmpeg:ogrod_detect#video=copy

  webrtc:
    candidates:
      - 192.168.11.3:8555
      - stun:8555
  log:
    level: debug
    exec: trace


cameras:

# -----------------------------------------------------------------------------------------------------------------

  wejscie_cam:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: preset-vaapi
      #hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://localhost:8554/wejscie_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://localhost:8554/wejscie
          input_args: preset-rtsp-restream
          roles:
            - record

    objects:
      track:
        - person
        - car
      mask: 0.001,0.079,0.466,0.077,0.456,0.488,0.001,0.5

      filters:
        person:
          mask:
            - 0.001,0.079,0.466,0.077,0.456,0.488,0.001,0.5
            - 0.894,0.081,0.882,0.437,1,0.481,1,0.098
    live:
      stream_name: wejscie

    review:
      alerts:
        required_zones: podjazd
      detections:
        required_zones: podjazd
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 7
      alerts:
        retain:
          days: 60
          mode: active_objects
        pre_capture: 60
        post_capture: 60
      detections:
        retain:
          days: 60
          mode: active_objects
        pre_capture: 60
        post_capture: 60

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
      required_zones:
        - podjazd
      retain:
        default: 365

    motion:
      enabled: true
      mask:

        - 0,0,0,0.783,0.122,0.774,0.121,0
        - 0.349,0,0.424,0.265,0.46,0.267,0.466,0.08,0.852,0.088,0.845,0.446,1,0.499,1,0
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 10
      stationary:
        interval: 50
        threshold: 50

    zones:
      podjazd:
        coordinates: 0.459,0.494,0.469,0.086,0.849,0.092,0.843,0.45,1,0.503,1,1,0,1,0,0.506
        inertia: 3
        loitering_time: 2
        objects:
          - person
          - car
    mqtt:
      quality: 70
      required_zones:
        - podjazd

# -----------------------------------------------------------------------------------------------------------------

  ogrod_cam:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://localhost:8554/ogrod_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://localhost:8554/ogrod
          input_args: preset-rtsp-restream
          roles:
            - record

    objects:
      track:
        - person
        - car

      filters:
        person:
          mask:
            - 0.71,0.476,0.808,0.484,0.799,0.812,0.698,0.805
            - 0,0.898,0.242,0.679,0.362,0.947,0.351,1,0,1
        car:
          mask:
            - 0,0,0,0.106,0.111,0.086,0.122,0.235,0.27,0.179,0.275,0.109,0.306,0.101,0.304,0.065,0.54,0.055,0.544,0.003
            - 0.697,0.003,0.696,0.225,0.684,0.283,0.88,0.301,0.881,0.003

    live:
      stream_name: ogrod

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 7
        mode: all

      alerts:
        retain:
          days: 7
        pre_capture: 60
        post_capture: 60

      detections:
        retain:
          days: 7
        pre_capture: 60
        post_capture: 60

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 720
      required_zones: []
      retain:
        default: 365

    motion:
      threshold: 40
      lightning_threshold: 0.8
      contour_area: 10
      frame_alpha: 0.01
      frame_height: 50
      improve_contrast: true
      mqtt_off_delay: 30
      mask:
        - 0.885,0.724,0.899,0.108,1,0.101,0.999,0,0.627,0,0.436,0,0.441,0.385,0.817,0.418,0.815,0.72
        - 0,0.299,0.072,0.296,0.163,0.451,0.173,0.617,0,0.772
        - 0.588,0.509,0.671,0.518,0.67,0.704,0.584,0.695
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 10
      stationary:
        interval: 50
        threshold: 50

    zones:
      Ogrod:
        coordinates: 
          0.246,0.191,0.117,0.241,0,0.334,0,1,0.869,1,0.878,0.077,0.689,0.07,0.31,0.06,0.309,0.191
        loitering_time: 0
        objects:
          - person
          - car

    review:
      alerts:
        required_zones: Ogrod
      detections:
        required_zones: Ogrod

version: 0.15-1

semantic_search:
  enabled: true
  reindex: false
  model_size: small

camera_groups:
  dom:
    order: 1
    icon: LuCakeSlice
    cameras:
      - wejscie_cam
      - ogrod_cam
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Frigate stats

```json
none
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    privileged: true
    hostname: "frigate"
    restart: "unless-stopped"
    shm_size: "256mb"
    devices:
      - "/dev/apex_0:/dev/apex_0"
      - "/dev/dri/renderD128" # for intel hwaccel
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume1/docker/frigate_015/config/:/config/:rw"
      - "/volume1/docker/frigate/:/media/frigate:rw"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - LIBVA_DRIVER_NAME=i965
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri/
    ports:
      - "7001:5000" # web interface
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

noname
