### DISCUSSION TITLE
Stuck at go2rtc version 1.8.4

### DISCUSSION THREAD

**Discussion by ChildishGambin0** [blakeblackshear/frigate#16797] [Ask A Question] [answered]
### Followed Instruction
https://docs.frigate.video/configuration/advanced/#custom-go2rtc-version

### Referenced
https://github.com/blakeblackshear/frigate/discussions/6646

### Go2rtc Versions Tried
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.8
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.7

### Installation Method
1. Confirmed my machine's kernel by using "uname -r"
2. Downloaded [go2rtc_linux_amd64](https://github.com/AlexxIT/go2rtc/releases/download/v1.9.8/go2rtc_linux_amd64)
3. Placed it under /config/go2rtc/
4. Renamed it to "go2rtc"
5. Ran "chmod +X go2rtc"
6. Stopped Frigate container then removed it
7. Modified "docker-compose.yml"
8. Ran "docker-compose up -d" then started Frigate container
9. checked the Logs in Frigate Proxy as well as in "homeassistant:1984"

### homeassistant:1984
![image](https://github.com/user-attachments/assets/8c096914-a9c5-4e64-9bb2-bcc3311a6279)

### Attempt 1 (not setting go2rtc config manually)

**docker-compose.yml**:
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    image: [ghcr.io/blakeblackshear/frigate:stable](http://ghcr.io/blakeblackshear/frigate:stable)
    privileged: true
    shm_size: "1100m"
    restart: unless-stopped
    stop_grace_period: 30s
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    ports:
      - "1935:1935"
      - "1984:1984"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_PASSWORD=****
    volumes:
      - /media/homeassistant/ext_hdd:/media/frigate
      - /usr/share/hassio/homeassistant/config.yml:/config/config.yml
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

**Frigate Proxy > Logs > Go2rtc tab**:
```
2025-02-25 01:33:07.464705126  [INFO] Preparing new go2rtc config...
2025-02-25 01:33:07.922712386  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-02-25 01:33:07.954661195  [INFO] Starting go2rtc...
2025-02-25 01:33:08.013799858  01:33:08.013 INF go2rtc version 1.8.4 linux/amd64
2025-02-25 01:33:08.014150830  01:33:08.014 INF [api] listen addr=:1984
2025-02-25 01:33:08.014391897  01:33:08.014 INF [rtsp] listen addr=:8554
2025-02-25 01:33:08.014875094  01:33:08.014 INF [webrtc] listen addr=:8555
2025-02-25 01:33:17.411538363  [INFO] Starting go2rtc healthcheck service...
```

### Attempt 2 (setting go2rtc config manually)

docker-compose.yml:
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    image: [ghcr.io/blakeblackshear/frigate:stable](http://ghcr.io/blakeblackshear/frigate:stable)
    privileged: true
    shm_size: "1100m"
    restart: unless-stopped
    stop_grace_period: 30s
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    ports:
      - "1935:1935"
      - "1984:1984"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_PASSWORD=****
    volumes:
      - /media/homeassistant/ext_hdd:/media/frigate
      - /usr/share/hassio/homeassistant/config.yml:/config/config.yml
      - /media/user/frigate/config/go2rtc/go2rtc:/config/go2rtc       ## added line
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

```
Frigate Proxy > Logs > Go2rtc tab
```
2025-02-25 01:18:10.267123646  [INFO] Preparing new go2rtc config...
2025-02-25 01:18:10.547466146  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-02-25 01:18:10.575227686  [INFO] Starting go2rtc...
2025-02-25 01:18:10.632840102  01:18:10.632 INF go2rtc version 1.8.4 linux/amd64
2025-02-25 01:18:10.633220579  01:18:10.633 INF [api] listen addr=:1984
2025-02-25 01:18:10.633428102  01:18:10.633 INF [rtsp] listen addr=:8554
2025-02-25 01:18:10.633869338  01:18:10.633 INF [webrtc] listen addr=:8555
2025-02-25 01:18:20.264567340  [INFO] Starting go2rtc healthcheck service...
```

### Attempt 3 (intentionally setting go2rtc location elsewhere to see frigate is even attempting to mount)

docker-compose.yml:
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    image: [ghcr.io/blakeblackshear/frigate:stable](http://ghcr.io/blakeblackshear/frigate:stable)
    privileged: true
    shm_size: "1100m"
    restart: unless-stopped
    stop_grace_period: 30s
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    ports:
      - "1935:1935"
      - "1984:1984"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_PASSWORD=****
    volumes:
      - /media/homeassistant/ext_hdd:/media/frigate
      - /usr/share/hassio/homeassistant/config.yml:/config/config.yml
      - /media/user/frigate/config/go2rtc:/config/go2rtc       ## added line
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

```
Frigate Proxy > Logs > Go2rtc tab
```
2025-02-25 01:07:18.540667634  [INFO] Preparing new go2rtc config...
2025-02-25 01:07:18.786621377  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-02-25 01:07:18.831363001  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2025-02-25 01:07:18.831366236  [INFO] Starting go2rtc...
2025-02-25 01:07:18.831369716  ./run.user: line 79: /config/go2rtc: Is a directory
2025-02-25 01:07:18.831371482  ./run.user: line 79: exec: /config/go2rtc: cannot execute: Is a directory
2025-02-25 01:07:18.833925628  [INFO] The go2rtc service exited with code 126 (by signal 0)
2025-02-25 01:07:19.842322192  [INFO] Removing stale config from last run...
```

Honestly, I don't have any issues with this version of go2rtc, but it bothers me that the current Frigate release is running on go2rtc version 1.9.2 while mine isn't, and I can't seem to update it manually.

**Comment by hawkeye217** [comment]
Your docker compose file only maps `config.yml`. You should be mapping the entire `/config` directory. 

See the reference file in the docs: https://docs.frigate.video/frigate/installation#docker

**Reply by ChildishGambin0** [reply]
I've tried:
```
...
    volumes:
      - /media/homeassistant/ext_hdd:/media/frigate
      - /usr/share/hassio/homeassistant/config.yml:/config/config.yml
      - /usr/share/hassio/homeassistant/go2rtc:/config/go2rtc
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

ls -l /usr/share/hassio/homeassistant/go2rtc returns:
`-rw-r--r-- 1 homeassistant homeassistant 5714828 Feb 26 21:26 /usr/share/hassio/homeassistant/go2rtc
`

but docker exec -it frigate go2rtc --version returns:
`Current version:  1.8.4`


any idea?

**Reply by hawkeye217** [reply, marked as answer]
As I said above, you need to map your entire `/config` directory. Make a directory called `/usr/share/hassio/homeassistant/config` and put your `config.yml` in there. Then use:

```
    volumes:
      - /media/homeassistant/ext_hdd:/media/frigate
      - /usr/share/hassio/homeassistant/config:/config
      - /usr/share/hassio/homeassistant/go2rtc:/config/go2rtc
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

You could even just put your go2rtc binary in `/usr/share/hassio/homeassistant/config` at that point and not do a bind-mount for it, which is the recommended way in the documentation.

**Reply by ChildishGambin0** [reply]
Moved config.yml and go2rtc binary into a dedicated config folder:
```
mkdir -p /usr/share/hassio/homeassistant/config
mv /usr/share/hassio/homeassistant/config.yml /usr/share/hassio/homeassistant/config/config.yml
mv /usr/share/hassio/homeassistant/go2rtc /usr/share/hassio/homeassistant/config/go2rtc
chmod +x /usr/share/hassio/homeassistant/config/go2rtc
```

Updated docker-compose.yml to map /config:
```
volumes:
  - /media/homeassistant/ext_hdd:/media/frigate
  - /usr/share/hassio/homeassistant/config:/config
  - /etc/localtime:/etc/localtime:ro
  - type: tmpfs
    target: /tmp/cache
    tmpfs:
      size: 1000000000
```

Recreated the Frigate container:
```
docker-compose down
docker-compose up -d
```

docker exec -it frigate go2rtc --version returns:
`Current version:  1.8.4`

But localhost:1984 shows the version 1.9.8 and go2rtc log shows:
`2025-02-26 22:07:00.125488180  22:07:00.125 INF go2rtc platform=linux/amd64 revision=199fdd6 version=1.9.8`

So I assume the problem is solved. Thank you.
