### DISCUSSION TITLE
[HW Accel Support]: ffmpeg crashes with intel 2nd gen

### DISCUSSION THREAD

**Discussion by aenima-x** [blakeblackshear/frigate#16807] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

Intel 2nd Gen crashes ffmpeg.

I think I have the configuration ok, I have set the device, the preset and the driver (i965).
But ffmpeg crashes.

Could be my GPU not compatible?

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  #host: mqtt
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  living:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@IP:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: false
    birdseye:
      order: 4
    onvif:
      host: 192.168.1.22
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
  patio:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@IP:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: false
  puerta:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@IP:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: false
  pasillo:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@IP:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: false

record:
  enabled: true
  retain:
    days: 2
    mode: all

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  layout:
    max_cameras: 4

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1gb" # update for your cameras based on calculation above
    devices:
     - /dev/dri/renderD128:/dev/dri/renderD128 
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      LIBVA_DRIVER_NAME: "i965"
```

### Relevant Frigate log output

```shell
frigate  | 2025-02-25 17:49:15.483743754  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [segment @ 0x5c7c81cce300] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | 2025-02-25 17:49:15.483750165  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vost#0:0/copy @ 0x5c7c81cded00] Non-monotonic DTS; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frigate  | 2025-02-25 17:49:15.483755718  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [hevc @ 0x5c7c81ce6080] No support for codec hevc profile 1.
frigate  | 2025-02-25 17:49:15.483759832  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [hevc @ 0x5c7c81ce6080] Failed setup for format vaapi: hwaccel initialisation returned error.
frigate  | 2025-02-25 17:49:15.483922695  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
frigate  | 2025-02-25 17:49:15.483976370  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vf#1:0 @ 0x5c7c81d21700] Error reinitializing filters!
frigate  | 2025-02-25 17:49:15.484005442  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vf#1:0 @ 0x5c7c81d21700] Task finished with error code: -38 (Function not implemented)
frigate  | 2025-02-25 17:49:15.484411494  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vf#1:0 @ 0x5c7c81d21700] Terminating thread with return code -38 (Function not implemented)
frigate  | 2025-02-25 17:49:15.484418064  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vost#1:0/rawvideo @ 0x5c7c81cd9e80] Could not open encoder before EOF
frigate  | 2025-02-25 17:49:15.484422637  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vost#1:0/rawvideo @ 0x5c7c81cd9e80] Task finished with error code: -22 (Invalid argument)
frigate  | 2025-02-25 17:49:15.484427448  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [vost#1:0/rawvideo @ 0x5c7c81cd9e80] Terminating thread with return code -22 (Invalid argument)
frigate  | 2025-02-25 17:49:15.484742196  [2025-02-25 17:49:15] ffmpeg.living.detect           ERROR   : [out#1/rawvideo @ 0x5c7c81d11700] Nothing was written into output file, because at least one of its streams received no packets.
```

### Relevant go2rtc log output

```shell
NO
```

### FFprobe output from your camera

```shell
ffprobe version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, rtsp, from 'rtsp://XXXXX/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.167000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 1920x1080, 6 tbr, 90k tbn
```

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision DS-2CV2Q21FD-IW

### Screenshots of the Frigate UI's System metrics pages

NO
