### DISCUSSION TITLE
[Support]: extension frigate-hailo

### DISCUSSION THREAD

**Discussion by familyegu973** [blakeblackshear/frigate#16808] [General Support]
### Describe the problem you are having

Hello,
After added a hailo 8L to my PI5 with HASS, I noticed that I have to change the URL in frigate extension.
I followed the docs : https://docs.frigate.video/integrations/home-assistant/
I installed Frigate NVR HailoRT Beta, as URL for frigate NVR HailoRT is not mentionned (any update ?).
Then I replaced the http://ccab4aaf-frigate:5000 of my initial installation with Frigate NVR HassOS Addon, with http://ccab4aaf-frigate-hailo-beta:5000 for frigate NVR HailoRT Beta HassOS Addon
But Connection failed.

In logs
Enregistreur: custom_components.frigate.api
Source: custom_components/frigate/api.py:369

Unauthorized (401) error for URL http://ccab4aaf-frigate-hailo:5000/api/login: Unauthorized
Unauthorized (401) error for URL http://ccab4aaf-frigate-hailo-beta:5000/api/login: Unauthorized
Unauthorized (401) error for URL http://ccab4aaf-frigate:5000/api/login: Unauthorized

Except frigate integration, all is working with frigate NVR HailoRT Beta HassOS Addon and my Hailo 8L.
Is there something I missed ?
In my frigate NVR HailoRT Beta HassOS Addon, the given url is hotname ccab4aaf-frigate-hailo-beta
same url as doc's

May you help me ? Please

### Version

0.15.0-h8l

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx.xx.xx.xxx
  user: xxxxxxx
  password: xxxxxxx
  port: 1883

cameras:
  cam01:
    ffmpeg:
      inputs:
        - path: 
            rtsp://xxxx:xxxxx@x.x.x.x:xx/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://xxxx:xxxx@xx.xxx.x.x:xx/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280 
      height: 720 
    motion:
      mask:
        - 0.977,0,0.98,0.083,0.878,0.078,0.878,0
        - 0.324,0.251,0.483,0.232,0.495,0.39,0.286,0.425,0.317,0.286
        - 0.027,0.425,0.105,0.427,0.124,0.976,0.005,0.981,0.005,0.651
        - 0.123,0.051,0.109,0.205,0.378,0.136,0.264,0.096
        - 0.683,0.655,0.8,0.641,0.846,0.808,0.85,0.827,0.885,0.851,0.863,0.971,0.699,0.965
        - 0.481,0.927,0.537,0.788,0.678,0.888,0.675,0.991,0.48,0.998
    objects:
      filters:
        person:
          mask: 0.067,0.22,0.075,0.131,0.287,0.092,0.377,0.141
      mask: 0.655,0.575,0.884,0.547,0.889,0.835,0.891,0.948,0.663,0.967
  cam02:
    ffmpeg:
      inputs:
        - path: 
            rtsp://xxx:xxxx@x.x.x.x:x/cam/realmonitor?channel=2&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://xxx:xxxx@x.x.x.x:x/cam/realmonitor?channel=2&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280 # largeur de l'image du flux secondaire (en pixels)
      height: 720 # hauteur de l'image du flux secondaire (en pixels)
    motion:
      mask:
        - 0,0.698,0.07,0.605,0.158,0.489,0.278,0.336,0.419,0.217,0.423,0.097,0.505,0.06,0.52,0.024,0.608,0,0,0
        - 0.777,1,1,1,1,0,0.777,0
        - 0.983,0.029,0.98,0.089,0.741,0.083,0.741,0.035
        - 0.264,0.339,0.272,0.45,0.312,0.561,0.311,0.646,0.322,0.661,0.346,0.654,0.361,0.633,0.368,0.614,0.348,0.549,0.381,0.455,0.367,0.326,0.36,0.291
    zones: {}
    objects:
      filters:
        person:
          mask: 
            0.263,0.333,0.365,0.295,0.381,0.453,0.349,0.545,0.37,0.617,0.348,0.658,0.319,0.661,0.308,0.651,0.31,0.563,0.272,0.453
  cam03:
    ffmpeg:
      inputs:
        - path: 
            rtsp://xxx:xxxx@x.x.x.x:x/cam/realmonitor?channel=3&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://xxx:xxxx@x.x.x.x:x/cam/realmonitor?channel=3&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280 
      height: 720 
    motion:
      mask:
        - 0,0.342,0.053,0.528,0.12,0.486,0.075,0.246,0.045,0.189,0,0.113
        - 0,0.216,0.144,0.088,0.374,0.046,0.575,0.044,0.771,0.075,1,0.157,1,0,0,0
        - 0.176,0.15,0.234,0.127,0.252,0.242,0.187,0.266
        - 0.434,0.297,0.42,0.406,0.8,0.761,0.862,0.6
        - 0.111,0.328,0.136,0.515,0.199,0.498,0.307,0.431,0.33,0.418,0.306,0.314,0.259,0.303,0.241,0.266,0.219,0.27,0.201,0.307,0.197,0.332,0.174,0.344,0.161,0.325,0.138,0.31
    objects:
      filters:
        person:
          mask:
            - 0,0.342,0.052,0.524,0.117,0.486,0.066,0.235,0.015,0.135,0,0.113
            - 0.174,0.148,0.187,0.268,0.254,0.243,0.238,0.125
            - 0.041,0.178,0.05,0.198,0.152,0.136,0.148,0.088
    zones: {}
  cam04:
    ffmpeg:
      inputs:
        - path: 
            rtsp://xxx:xxxx@x.x.x.x:x/cam/realmonitor?channel=4&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: 
            rtsp://xxx:xxxx@x.x.x.x:x/cam/realmonitor?channel=4&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280 # largeur de l'image du flux secondaire (en pixels)
      height: 720 # hauteur de l'image du flux secondaire (en pixels)
    zones: {}
    objects:
      filters:
        person:
          mask:
            - 0.798,0.212,1,0.311,1,0.199,0.802,0.168
            - 0.633,0.34,0.629,0.441,0.699,0.439,0.693,0.351
            - 0.772,0.164,0.773,0.422,0.81,0.437,0.818,0.169
            - 0.448,0.291,0.452,0.524,0.588,0.491,0.585,0.272
            - 0.51,0.268,0.519,0.347,0.55,0.349,0.546,0.259
            - 0.365,0.885,0.369,0.993,0.505,0.996,0.501,0.884
    motion:
      mask:
        - 1280,0,1280,67,1110,65,1113,0
        - 0,264,582,108,552,0,0,0
  cam05:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxxx@x.x.x.x:x/img/media.sav
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx:xxxx@x.x.x.x:x/img/media.sav
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 1280 
      height: 720 
    motion:
      mask:
        - 0.555,0.591,0.667,0.591,0.669,0.452,0.559,0.446
        - 0,0.033,0,0,0.13,0,0.124,0.031
record:
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
snapshots:
  enabled: true

objects:
  track:
    - person
  filters:
    person:
      threshold: 0.72
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: ssd
  path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef
```

### Relevant Frigate log output

```shell
Enregistreur: custom_components.frigate.api
Source: custom_components/frigate/api.py:369

Unauthorized (401) error for URL http://ccab4aaf-frigate-hailo:5000/api/login: Unauthorized
Unauthorized (401) error for URL http://ccab4aaf-frigate-hailo-beta:5000/api/login: Unauthorized
Unauthorized (401) error for URL http://ccab4aaf-frigate:5000/api/login: Unauthorized
```

### Relevant go2rtc log output

```shell
13:52:16.697 INF go2rtc platform=linux/arm64 revision=199fdd6 version=1.9.8
13:52:16.703 INF config path=/config/go2rtc.yaml
13:52:16.719 INF [rtsp] listen addr=:8554
13:52:16.722 INF [api] listen addr=:1984
13:52:16.732 INF [webrtc] listen addr=:8555/tcp
```

### FFprobe output from your camera

```shell
no log
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
no file
```

### Object Detector

Other

### Network connection

Wired

### Camera make and model

alhua
