### DISCUSSION TITLE
[Config Support]: Unexpected Alerts in Night vision

### DISCUSSION THREAD

**Discussion by jfh250** [blakeblackshear/frigate#16815] [Config Support]
### Describe the problem you are having

For the life of me I can’t understand why I’m getting ‘Alerts’ when my zone rules are otherwise working correctly during daylight. When my camera flips to night vision, things get weird. Furthermore, what’s happening isn’t supported by what’s reported in object lifecycle - this is the most confusing bit, I don't see how alert conditions are met without this.

Essentially, I have two zones, Driveway & Road. People and Cars on my Driveway should be classified as an Alert. People and Cars in the Road should be classified as a Detection.
**This works as expected during hours of daylight**. But when the camera flips to night vision, Passing cars become prone to classification as an Alert rather than a Detection. This would suggest they must have interacted with my Driveway zone. However, and the bit I find most puzzling is that reviewing the object Lifecycle for these instances confirms all activity took place in the Road.
I don’t really know how to troubleshoot, due to the conflicting information in Object Lifecycle. Watching the scene in debug also doesn’t really help.

I would entirely expect object lifecycle to suggest some interaction with the Driveway, but it doesn't. Hence I don't know how alert conditions are being achieved, but they are.

I don't think it's related, but but in my screenshots below, it does appear to have tracked a stationary car, parked in the road, caused by the motion of an actual passing car. But again, it all happened in the Road zone, so this shouldn't amount to an alert.

### Version

0.15-1

### Frigate config file

```yaml
# ==========================
# SYSTEM CONFIGURATION
# ==========================
mqtt:
  enabled: false  # Disable MQTT if not using it

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

# ==========================
# CAMERA CONFIGURATION
# ==========================
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@192.168.1.5:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://frigate:password@192.168.1.5:554/Streaming/Channels/101
          roles:
            - record

    detect:
      width: 640
      height: 480
      fps: 8
      stationary:
        threshold: 240 # How long before Frigate considers an object "stationary" (FPS) (reflecting headlight problem)
        interval: 100 # How often Frigate checks if a stationary object moved (FPS) (reflecting headlight problem)


    objects:
      track:
        - person
        - car

    # ==========================
    # RECORDING CONFIGURATION
    # ==========================
      filters:
        person:
          mask: 0.535,0.123,0.557,0.121,0.557,0.164,0.535,0.167
    record:
      enabled: true
      retain:
        days: 0 # Keep recordings for 35 days
        mode: active_objects
      alerts:
        retain:
          days: 35
          mode: active_objects
      detections:
        retain:
          days: 35
          mode: active_objects


    # ==========================
    # SNAPSHOT CONFIGURATION
    # ==========================
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 35  # Keep snapshots for 35 days
      required_zones:
        - Road
        - Driveway


    # ==========================
    # MOTION DETECTION SETTINGS
    # ==========================
    motion:
      mask:
        - 0.268,0.047,0.268,0.082,0.334,0.082,0.334,0.039
        - 0.429,1,0.137,0.618,0.004,0.727,0.001,0.993
        - -0.001,0.354,0.08,0.251,0.136,0.237,0.144,0.038,0.132,0,-0.001,0.001
        - 1,0.182,0.665,0.074,0.394,0.066,0.157,0.086,0.147,0.005,0.996,0.001
        - 0.819,0.993,1,0.357,0.999,0.994
        - 0.217,0.136,0.183,0.23,0.354,0.266,0.428,0.215,0.424,0.153,0.315,0.141
        - 0.895,0.383,0.86,0.558,0.752,0.523,0.594,0.438,0.636,0.322,0.765,0.329
      threshold: 45
      contour_area: 25
      improve_contrast: true

    # ==========================
    # ZONE CONFIGURATION
    # ==========================
    zones:
      Driveway:
        coordinates: 
          0.313,0.988,0.916,1,0.956,0.428,0.896,0.372,0.716,0.323,0.662,0.312,0.445,0.24,0.424,0.205,0.404,0.195,0.226,0.166,0.112,0.149,0.002,0.28,0.003,0.761
        filters:
          person:
            min_area: 5000  # Adjust as needed to filter out false positives
          car:
            min_area: 8000  # Adjust as needed

        inertia: 3
        loitering_time: 0
        objects:
          - car
          - person
      Road:
        coordinates: 
          0.963,0.403,1,0.107,0.657,0.009,0.521,0,0.15,0,0.152,0.144,0.406,0.186,0.448,0.233,0.675,0.307,0.766,0.333
        filters:
          person:
            min_area: 300 # Adjust as needed
          car:
            min_area: 2000 # Adjust as needed
        loitering_time: 0  # Record cars only if they linger for 7 seconds or more (temp disabled)
        inertia: 2

        objects:
          - car
          - person
    review:
      alerts:
        required_zones: Driveway
      detections:
        required_zones: Road
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![1JPG](https://github.com/user-attachments/assets/c307efae-f8fa-4864-9f31-55b3a97c4118)
![2JPG](https://github.com/user-attachments/assets/3fee0567-fc7f-4030-af62-4f5a7a5dac4d)
![3](https://github.com/user-attachments/assets/eccf46d4-29a4-44cf-b479-4dd497b2a412)
![4JPG](https://github.com/user-attachments/assets/bf8c05ab-7a9e-48ff-b7a8-6ae22d852ec7)
![5JPG](https://github.com/user-attachments/assets/93aac216-b69d-4067-b550-9847132aab49)
