### DISCUSSION TITLE
[Development]: Generating tensorrt trt stopped working since 877b7b291061fc92d1bfb18622ee6b0259ff5ed7

### DISCUSSION THREAD

**Discussion by SigHunter** [blakeblackshear/frigate#16822] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

in commit 877b7b291061fc92d1bfb18622ee6b0259ff5ed7 the base image and with it the tensorrt TRT version (TRT_VER=8.6.1) was upgraded to 8.6.1. I did all my testing with yesterday's latest commit 7eb3c87fa0d8a5737d866867bdbaea7b690b4642

Starting the docker container leads to
```
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 57, in <module>
frigate  |     import tensorrt as trt
frigate  |   File "/usr/local/lib/python3.11/dist-packages/tensorrt/__init__.py", line 18, in <module>
frigate  |     from tensorrt_bindings import *
frigate  |   File "/usr/local/lib/python3.11/dist-packages/tensorrt_bindings/__init__.py", line 67, in <module>
frigate  |     from .tensorrt import *
frigate  | ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
frigate  | Available tensorrt models:
frigate  | ls: cannot access '*.trt': No such file or directory
frigate  | s6-rc: warning: unable to start service trt-model-prepare: command exited 2
```

Usually (on my machine) the trt files reside in /var/lib/docker-services/frigate/config/model_cache/tensorrt/8.5.3/
I see there is a new folder 8.6.1 created but it is empty

[frigate_7eb3c87_compose.txt](https://github.com/user-attachments/files/18980001/frigate_7eb3c87_compose.txt)
[frigate_7eb3c87_logs.txt](https://github.com/user-attachments/files/18980002/frigate_7eb3c87_logs.txt)
[frigate_config.txt](https://github.com/user-attachments/files/18980003/frigate_config.txt)
[frigate_working_compose.txt](https://github.com/user-attachments/files/18980004/frigate_working_compose.txt)
[frigate_working_logs.txt](https://github.com/user-attachments/files/18980005/frigate_working_logs.txt)

### Steps to reproduce

1. Switch docker compose image from 15.0 to ghcr.io/blakeblackshear/frigate:7eb3c87-tensorrt
2. start the docker container
3. check the logs and folder

### Version

ghcr.io/blakeblackshear/frigate:7eb3c87-tensorrt

### In which browser(s) are you experiencing the issue with?

Firefox 135.0.1

### Frigate config file

```yaml
ui:
  timezone: Europe/Berlin
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%Y/%m/%d %H:%M'

mqtt:
  enabled: false

tls:
  enabled: false

record:
  enabled: true
  retain:
    days: 10
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    hofkamera:
      - rtsp://user:pw@redacted_ip/stream1
      - ffmpeg:hofkamera#audio=aac
    hofkamera_detect:
      - rtsp://user:pw@redacted_ip/stream2
      - ffmpeg:hofkamera_detect#audio=aac
    tuerkamera:
      - rtsp://user:pw@redacted_ip/h264Preview_01_main
    tuerkamera_detect:
      - rtsp://user:pw@redacted_ip/h264Preview_01_sub

cameras:
  hofkamera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hofkamera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hofkamera_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
    zones:
      Waschkueche:
        coordinates: 0.578,0.168,0.524,0.164,0.517,0.37,0.57,0.347
        loitering_time: 0
      Garage:
        coordinates: 0.71,0.176,0.813,0.196,0.797,0.385,0.705,0.364
        loitering_time: 0
    motion:
      mask: 0.904,0.174,1,0.255,1,0.503,0.892,0.335
  tuerkamera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tuerkamera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuerkamera_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - bicycle
    motion:
      mask:
        - 0.01,0.069,0.303,0.069,0.302,0.025,0.012,0.025
        - 0.914,0.422,1,0.519,1,0,0.972,0,0.963,0.15,0.911,0.215,0.903,0.31

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:7eb3c87-tensorrt
    privileged: true
    container_name: frigate
    ports:
      - "8971:8971" # host:container
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "1984:1984"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker-services/frigate/config:/config
      - /var/lib/docker-services/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    restart: unless-stopped
    shm_size: "512mb"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: -1
    environment:
      YOLO_MODELS: "yolov7-320"
```

### Relevant Frigate log output

```shell
frigate  |
frigate  | Creating yolov7-320.cfg and yolov7-320.weights
frigate  |
frigate  | Done.
frigate  | 2025-02-26 08:56:40.506177150  [INFO] Starting go2rtc healthcheck service...
frigate  |
frigate  | Generating yolov7-320.trt. This may take a few minutes.
frigate  |
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 57, in <module>
frigate  |     import tensorrt as trt
frigate  |   File "/usr/local/lib/python3.11/dist-packages/tensorrt/__init__.py", line 18, in <module>
frigate  |     from tensorrt_bindings import *
frigate  |   File "/usr/local/lib/python3.11/dist-packages/tensorrt_bindings/__init__.py", line 67, in <module>
frigate  |     from .tensorrt import *
frigate  | ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
frigate  | Available tensorrt models:
frigate  | ls: cannot access '*.trt': No such file or directory
frigate  | s6-rc: warning: unable to start service trt-model-prepare: command exited 2
```

### Relevant go2rtc log output

```shell
go2rtc not relevant here
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink, TP-Link, not relevant here

### Screenshots of the Frigate UI's System metrics pages

Backend problem, UI not relevant
