### DISCUSSION TITLE
[Config Support]: Can't save audio in recordings for just one camera

### DISCUSSION THREAD

**Discussion by dagord** [blakeblackshear/frigate#16829] [Config Support]
### Describe the problem you are having

Hello everyone, in my setup I have several cameras; for all of them, I'm able to save audio in the recordings, with the exception of one, for which I can only hear audio in the live view, while the recordings are completely mute.

Specifically, it's a Uefy indoor wireless camera. For the sake of brevity, I've included an excerpt from my config file, showing the configuration of the camera in question (**indoor-camera**) and that of another properly functioning camera (**front-camera**)

I already tried replicating the configuration of the latter as follows
```
go2rtc:
  streams:
    indoor-camera: ffmpeg:rtsp://A4dC0oPOc8Lx:w6xMU4oCJLOj@192.168.0.211/live0#video=h264#audio=copy#hardware

cameras:
  indoor-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor-camera?video&audio
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-generic
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
```

but the situation worsens: not only does the recording remain mute, but after a few moments, the loading stays forever as if it can't play the video (perhaps due to a codec error or to a file corruption?).
Can you help me troubleshooting the issue?

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false
tls:
  enabled: false
ui:
  time_format: 24hour

go2rtc:
  streams:
    front-camera: 
      ffmpeg:rtsp://user:password$@192.168.0.212:554/Preview_01_main#video=h264#width=1706#height=1280#audio=copy#hardware
    indoor-camera: rtsp://A4dC0oPOc8Lx:w6xMU4oCJLOj@192.168.0.211/live0

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  front-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-camera?video&audio
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
  indoor-camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor-camera
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-generic
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
version: 0.14
camera_groups:
  test:
    order: 1
    icon: LuAirplay
    cameras:
      - birdseye
      - name_of_your_camera
      - front-camera

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### Relevant Frigate log output

```shell
nothing relevant
```

### Relevant go2rtc log output

```shell
nothing relevant
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "640mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/projects/frigate/config:/config
      - /home/user/usb/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

OpenVino
