### DISCUSSION TITLE
And way to schedule 'disable' a camera ?  I'm using Home Assistant with it

### DISCUSSION THREAD

**Discussion by vw-kombi** [blakeblackshear/frigate#16821] [Config Support]
### Describe the problem you are having

The dog (we think) sleeps on our bed when we are not home.  I recently got a new Dahua cam to replace a Foscam G4P at the front door which had its IR lights fail, so now I have a sort of ok foscam, so I moved it to our bedroom.  
So I don't want that cam working when we are home (for obvious reasons), so I added a HA automation to run every 5 mins that if we are not home, then it turns off the switches for motion, detect, recordings and snapshots.  I also added to turn off the HA camera too......  But, the image is still showing on the camera card in HA, and obviously in the frigate birdseye main screen.

The camera is Loki-Cam in the config if that matters.

Is there a process I can do to stop it completely ?

### Version

0.15

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.30.249:5005/api/config/schema.json

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720

database:
  path: /config/frigate.db

mqtt:
  host: core-mosquitto
  topic_prefix: frigate
  user: MQTT
  password: XXXXXXXXXX

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

semantic_search:
  enabled: true
  model_size: large
  reindex: false

genai:
  enabled: true
  provider: gemini
  api_key: XXXXXXXXXX
  model: gemini-1.5-pro

cameras:
  Front-Cam:
    enabled: true
    genai: # <- Custom AI Prompts for objects can go here
      enabled: true
      use_snapshot: false
      prompt: Summarize what's happening in the camera feed (one sentence max). Don't
        describe the scene! If there is a person, describe what they're doing and
        what they look like. If they look like a courier mention that! If nothing
        is happening, say so.
#     objects:
#       - person
      required_zones:
        - frontpath
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://hikvision:XXXXXXXXXX@10.10.40.18:554/Streaming/Channels/102 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://hikvision:XXXXXXXXXX@10.10.40.18:554/Streaming/Channels/101 # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
        - person
        - motorcycle
      filters:
        motorcycle:
          min_score: 40
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    snapshots:
      enabled: true
      required_zones:
        - frontleft
        - frontright
        - frontpath
        - driveway
      bounding_box: true
      timestamp: true
      retain:
        default: 14
    motion:
      mask:
        - 0.943,0.917,1,0.805,1,0,0,0,0,0.181,0,0.386,0.128,0.206,0.11,0.2,0.101,0.084,0.195,0,0.385,0,0.386,0.117,0.433,0.217,0.516,0.249,0.808,0.35,0.818,0.255,0.56,0.155,0.574,0,0.617,0,0.888,0.077,0.89,0.226,0.881,0.284,0.868,0.41
        - 0.4,1,0.399,0.902,0.17,0.877,0.138,0.946,0,0.943,0.002,0.997
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    zones:
      driveway:
        coordinates: 0.184,0.156,0,0.391,0,1,0.421,1,0.737,1,0.748,0.338,0.413,0.218
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - motorcycle
      frontpath:
        coordinates: 0.744,1,0.752,0.34,0.804,0.36,0.862,0.388,0.889,0.607,0.937,0.932,0.901,1
        inertia: 3
        loitering_time: 0
        objects: person
      frontleft:
        coordinates: 0.206,0.13,0.379,0.13,0.385,0.08,0.381,0,0.202,0,0.195,0.053
        inertia: 3
        loitering_time: 3
        objects: person
      frontright:
        coordinates: 
          0.885,0.083,0.887,0.139,0.886,0.207,0.869,0.381,0.807,0.353,0.819,0.255,0.563,0.157,0.572,0.058,0.591,0
        inertia: 3
        loitering_time: 3
        objects:
          - person
          - motorcycle
    review:
      alerts:
        required_zones:
          - driveway
          - frontpath
          - frontleft
          - frontright
  Front-Door:
    enabled: true
    genai: # <- Custom AI Prompts for objects can go here
      enabled: true
      prompt: Summarize what's happening in the camera feed (one sentence max). Don't
        describe the scene! If there is a person, describe what they're doing and
        what they look like. If they look like a courier mention that! If nothing
        is happening, say so. Ignore the tortoise.
#      object_prompts:
#         person: "Observe the person in these images, describe what they're doing and what they look like (one sentence max). Don't describe the scene! If they look like a courier mention that! If nothing is happening, say so."
#         cat: "Observe the cat in these images. Focus on its movement and intent (e.g., wandering, hunting, interacting with objects). If the cat is near the flower pots or engaging in any specific actions, mention it."
#      objects:
#        - person
#        - cat
#      required_zones:
#        - doorway
#        - pathway
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://dahua:XXXXXXXXXX@10.10.40.15/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://dahua:XXXXXXXXXX@10.10.40.15/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots:
      enabled: true
      required_zones:
        - doorway
        - pathway
      bounding_box: true
      timestamp: true
      retain:
        default: 7
    motion:
      mask: 
        0.929,0.409,0.924,0.248,0.912,0.224,0.915,0.163,0.869,0.158,0.879,0.086,0.775,0.082,0.768,0.476,0.679,0.725,0.692,0.061,0.364,0.056,0,0.06,0,0,1,0,1,1,0.888,1,0.896,0.92,0.677,0.81,0.682,0.725,0.75,0.536,0.923,0.616,0.892,0.505
      threshold: 30
      contour_area: 10
      lightning_threshold: 0.8
      improve_contrast: 'true'
    zones:
      doorway:
        coordinates: 
          0.69,1,0.763,1,0.88,1,0.89,0.928,0.671,0.818,0.691,0.29,0.681,0.061,0.375,0.06,0,0.059,0,1,0.605,1
        inertia: 3
        loitering_time: 0
      pathway:
        coordinates: 
          0.864,0.266,0.798,0.548,0.917,0.603,0.921,0.516,0.924,0.403,0.925,0.312,0.92,0.25,0.907,0.224,0.911,0.174,0.871,0.17
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - doorway
  Loki-Cam:
    enabled: true
    genai: # <- Custom AI Prompts for objects can go here
      enabled: false
      prompt: Summarize what's happening in the camera feed (one sentence max). Don't
        describe the scene! If there is a person, describe what they're doing and
        what they look like. If they look like a courier mention that! If nothing
        is happening, say so. Ignore the tortoise.
    ffmpeg:
      inputs:
        - path: rtsp://foscam:XXXXXXXXXX@10.10.40.16:88/videoSub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://foscam:XXXXXXXXXX@10.10.40.16:88/videoMain # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - dog
      filters:
        dog:
          threshold: 0.8
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 3
      detections:
        retain:
          days: 3
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 3
    motion:
      threshold: 30
      contour_area: 10
      lightning_threshold: 0.8
      improve_contrast: 'true'
      mask: 0.002,0.001,0.36,0.001,0.36,0.047,-0.001,0.048
    zones:
      Loki-Zone:
        coordinates: 0.002,0.047,0.995,0.052,0.995,0.986,0.001,0.984
        loitering_time: 3
        objects: dog
    review: {}
  Back-Cam:
    enabled: true
    genai: # <- disable GenAI for your indoor camera
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://foscam:XXXXXXXXXX@10.10.40.14:554/videoSub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://foscam:XXXXXXXXXX@10.10.40.14:554/videoMain # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 7
    motion:
      mask: 
        1,0,1,0.392,0.665,0.332,0.66,0.476,0.627,0.47,0.627,0.595,0.572,0.605,0.451,0.569,0.385,0.542,0.36,0.543,0.343,0.269,0.288,0.266,0.313,0.589,0.192,0.631,0.164,0.317,0.142,0.206,0.036,0.21,0.042,0.431,0,0.447,0,0
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

OpenVino
