### DISCUSSION TITLE
[Bug]: System Metrics Storage not showing correct usage per camera

### DISCUSSION THREAD

**Discussion by toperichvania** [blakeblackshear/frigate#16825] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

In System Metrics storage view I see few cameras that show as if they are using 0 of storage which by looking at the actual recordings on disk is incorrect.

### Steps to reproduce

1.
2.
3.
...

### Version

0.15.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 172.19.160.10
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

go2rtc:
  webrtc:
    ice_servers:
    - urls: [stun:172.19.160.10:3478]
    # - urls: [turn:172.19.160.10:3478]
    candidates:
      - 172.19.160.30:8555
      - stun:8555
  streams:
    CAM20:
      - ffmpeg:rtsp://admin:password@172.19.162.89:554/axis-media/media.amp
    CAM21:
      - ffmpeg:rtsp://admin:password@172.19.162.90:554/axis-media/media.amp

cameras:
  CAM20:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM20
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 172.19.162.89
      port: 80
      user: admin
      password: password
    detect:
      enabled: false
    live:
      stream_name: CAM20
  CAM21:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM21
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 172.19.162.90
      port: 80
      user: admin
      password: password
    detect:
      enabled: false
    live:
      stream_name: CAM21

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 10
      mode: motion
  detections:
    retain:
      days: 10
      mode: motion

snapshots:
  enabled: false
  clean_copy: true
  timestamp: false
  bounding_box: false
  crop: true
  # height: 720
  quality: 100

detect:
  fps: 5
  enabled: false

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: false
  provider: ollama
  base_url: http://172.19.160.30:11434
  model: llava:7b
  
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    privileged: true
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-tensorrt
    shm_size: "8gb"
    devices:
      - /dev/dri/renderD128
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /shared/recordings:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "1984:1984"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      FRIGATE_MQTT_USER: "mqtt_user"
      FRIGATE_MQTT_PASSWORD: "password"
      YOLO_MODELS: "yolov7-320,yolov7x-640"
```

### Relevant Frigate log output

```shell
noting related
```

### Relevant go2rtc log output

```shell
nothing related
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

AXIS M3215

### Screenshots of the Frigate UI's System metrics pages

<img width="1396" alt="Screenshot 2025-02-26 at 12 22 44" src="https://github.com/user-attachments/assets/e55c44c7-5311-4c7a-b192-7e9be0b70396" />

### Any other information that may be helpful

Output of du of s single hour in a day: 
/shared/recordings/recordings/2025-02-25/00$ du -h | sort -r -k2
3.9G	./CAM9
21M	./CAM8
34M	./CAM7
24M	./CAM6
796M	./CAM53
841M	./CAM52
432M	./CAM51
820M	./CAM50
20M	./CAM5
804M	./CAM49
515M	./CAM46
470M	./CAM45
622M	./CAM44
404M	./CAM43
217M	./CAM42
474M	./CAM41
722M	./CAM39
367M	./CAM36
369M	./CAM35
6.8M	./CAM33
577M	./CAM32
493M	./CAM31
60M	./CAM30
85M	./CAM29
51M	./CAM28
6.8M	./CAM27
6.8M	./CAM26
88M	./CAM25
5.7M	./CAM24
6.8M	./CAM21
6.8M	./CAM20
203M	./CAM19
389M	./CAM18
467M	./CAM17
232M	./CAM16
181M	./CAM15
421M	./CAM14
399M	./CAM13
333M	./CAM12
358M	./CAM11
163M	./CAM10
16G	.
