### DISCUSSION TITLE
Newbie Questions: storage, SSLs, multiple Cores

### DISCUSSION THREAD

**Discussion by PrestonMcAfee** [blakeblackshear/frigate#16839] [Ask A Question] [answered]
Long time Blue Iris customer looking at Frigate as a way of eliminating Windows from my life.  I have 13 cameras.  I'm a noob^3 -- new to Frigate, newish to Linux, and this is only my second docker, so likely that I've made transparent blunders.

I installed Frigate using docker compose on a machine running Ubuntu 24.04.  This is primarily a test and I expect to eventually dedicate a PC to Frigate and one of the things I wanted to know is what kind of machine is good for my 13 cameras.  The present machine is a NUC with an 11th gen i7, 64GB of RAM, a GE Force RTX 2060 and Iris XE graphics.  To this I've added a USB coral and ordered a second one for detection.

I have a 2TB NVMe drive that I am dedicating to Frigate and built the container on that drive.

My first question is: I can't tell where Frigate is storing clips, but it isn't the 2 TB drive.  I put this docker compose file on the 2TB drive, along with a folder named config with config.yml in it, and a folder named storage:

````
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    stop_grace_period: 30s 
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "20000mb" 
    volumes:
      - ./config:/config
      - ./storage:/storage
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "554:554"
      - "8554:8554" 
      - "8555:8555/tcp" 
      - "8555:8555/udp" 
    environment:
      FRIGATE_RTSP_PASSWORD: "HIDDEN"
    devices:
      - /dev/bus/usb:/dev/bus/usb 
````

and nothing has appeared in the storage folder.  I tried both ./storage and  /path/to/your/storage to identify the volume.  So how do I tell Frigate to keep recordings in that folder?  Here is a sample from one camera's settings in case that is the problem:

````
  Garage:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: 
            rtsp://XXX:YYY@192.168.5.8:554/MediaProfile_Channel1_MainStream/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
        - path: 
            rtsp://XXX:YYY@192.168.5.8:554/MediaProfile_Channel1_SubStream1/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    motion:
      mask: 0.558,0.035,0.552,0.104,0.899,0.102,0.899,0.027
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
````

Second question: Can Frigate make use of multiple cores?  I put
````
detectors:
  coral:
    type: edgetpu
    device: usb
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2
  cpu3:
    type: cpu
    num_threads: 2
  cpu4:
    type: cpu
    num_threads: 2
````

and the system metrics show Frigate using four cores.  But it also shows Frigate using those cores more than 90% and only about 15% on the Coral, so that seems like a waste.  But when I try with a single CPU, Frigate shows utilization over 300%, which is what sent me in this direction in the first place.

Finally, when I go to https://ip:8971 I run into the 400 Bad Request The plain HTTP request was sent to HTTPS port problem.  I can work around this by re-entering https://ip:8971 and then taking an exception, but I don't encounter this problem on blue iris, a docker container on a Synology drive that supports Fresh RSS, or Home Assistant.  Is there some way to avoid the 400 Bad Request error?

I'm impressed with Frigate's detection -- it seems better than Blue Iris and the web interface is comparable.  I suspect that I am going to like it a lot better than Blue Iris, especially as I'm already seeing fewer false positives and I have barely started.
