### DISCUSSION TITLE
Why frigate resizing 640x480 streams to 960x720 and 1280x720?

### DISCUSSION THREAD

**Discussion by harryqt** [blakeblackshear/frigate#16844] [Ask A Question] [answered]
My Hikvision camera has been configured to the following:

- **Main stream**: 1920x1080, fps+iframe = 25, h265 (_Record_)
- **Sub stream**: 640x480, fps+iframe = 6, h264 (_Detect_)

<details>
<summary>docker-compose.yaml</summary>

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/extdrive/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
```
</details>

<details>
<summary>config.yaml</summary>

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -c:v h264_v4l2m2m

record:
  enabled: true
  retain:
    days: 0
  alerts:
    retain:
      days: 30
      mode: motion

cameras:
  Camera1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.5.63:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://user:pass@192.168.5.63:554/Streaming/Channels/2
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 6
    motion:
      mask: 0.961,1,0.797,0.66,0.51,0.126,0,0.116,0,0,1,0,1,1
    zones:
      Road:
        coordinates: 0.309,0.998,0.406,0.131,0.468,0.132,0.761,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Road
      detections:
        required_zones: Road
version: 0.15-1
```
</details>

While browsing `htop`, marked processes caught my attention:

<img width="1470" alt="Screenshot 2025-02-27 at 11 13 35 AM" src="https://github.com/user-attachments/assets/34e485a2-420a-42cd-a074-642814560e83" />

I'm not a ffmpeg guru but looks like, one process of ffmpeg resizing 640x480 streams to 960x720 and another process doing something with 1280x720. This looks odd, can someone explain to me what's going on there?

**Comment by leccelecce** [comment]
The 1280x720 is for Birdseye. You can disable it if you don't use it.

https://docs.frigate.video/configuration/birdseye#birdseye-dimensions

The 640x480 one I think is for the JSMpeg player, seeing as you've not configured "proper" live streaming using MSE or WebRTC. You'll probably want to set that up.

https://docs.frigate.video/configuration/live#live-view-technologies

**Comment by harryqt** [comment]
Thank you for the help. After disabling Birdseye one process goes away but I'm still stuck with second one. I've configured "Live View" as you suggested but 960x720 process still not going away. ☹️

<details>
<summary>Updated config.yaml</summary>

```yaml
mqtt:
  enabled: false

birdseye:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -c:v h264_v4l2m2m

record:
  enabled: true
  retain:
    days: 0
  alerts:
    retain:
      days: 30
      mode: motion

go2rtc:
  streams:
    camera1:
      - rtsp://user:pass@192.168.5.63:554/Streaming/Channels/1
    camera1_sub:
      - rtsp://user:pass@192.168.5.63:554/Streaming/Channels/2

cameras:
  camera1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: camera1_sub
    detect:
      fps: 6
    motion:
      mask: 0.961,1,0.797,0.66,0.51,0.126,0,0.116,0,0,1,0,1,1
    zones:
      Road:
        coordinates: 0.309,0.998,0.406,0.131,0.468,0.132,0.761,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Road
      detections:
        required_zones: Road
version: 0.15-1

```
</details>

<img width="1535" alt="Screenshot 2025-02-27 at 4 16 38 PM" src="https://github.com/user-attachments/assets/2683f62b-116a-40d2-a2f9-19a0adb6062c" />
