### DISCUSSION TITLE
[Development]: tensorrt JP6 cannot load library libavdevice.so.60

### DISCUSSION THREAD

**Discussion by hieulq** [blakeblackshear/frigate#16845] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Maybe after PR #16712 , ffmpeg build with JP6 seem broken with below error

```
frigate  | 2025-02-27 14:25:09.609390660  [INFO] Preparing Frigate...
frigate  | 2025-02-27 14:25:09.627081156  [INFO] Starting NGINX...
frigate  | 2025-02-27 14:25:09.651402452  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | 2025-02-27 14:25:09.752452667  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | 2025-02-27 14:25:09.763180671  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | 2025-02-27 14:25:10.911444736  [INFO] The go2rtc service exited with code 1 (by signal 0)

```

### Steps to reproduce

1. Pull tensorrt JP6 dev build (like `frigate:d0e9bcb-tensorrt-jp6`) or manually build 
2. Start frigate container with tensorrt detector
3. Check log

### Version

dev

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0

face_recognition:
  enabled: true

model:
  path: /config/model_cache/tensorrt/8.6.2/yolov7x-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    runtime: nvidia
    image: ghcr.io/blakeblackshear/frigate:d0e9bcb-tensorrt-jp6
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    environment:
      YOLO_MODELS: yolov7x-320
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
```

### Relevant Frigate log output

```shell
frigate  | 2025-02-27 14:25:09.609390660  [INFO] Preparing Frigate...
frigate  | 2025-02-27 14:25:09.627081156  [INFO] Starting NGINX...
frigate  | 2025-02-27 14:25:09.651402452  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | 2025-02-27 14:25:09.752452667  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | 2025-02-27 14:25:09.763180671  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | 2025-02-27 14:25:10.911444736  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | /usr/lib/ffmpeg/jetson/bin/ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory
frigate  | 2025-02-27 14:25:12.072297702  [INFO] The go2rtc service exited with code 1 (by signal 0)
```

### Relevant go2rtc log output

```shell
frigate  | 2025-02-27 14:25:10.911444736  [INFO] The go2rtc service exited with code 1 (by signal 0)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tapo, IMOU

### Screenshots of the Frigate UI's System metrics pages

no screenshot
