### DISCUSSION TITLE
[Support]: Where to find all detection snapshot pics for HA?

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#16853] [General Support]
### Describe the problem you are having

Apologies, if this is a dumb question or if this is more of an HA question.

I want to use a swipe card in HA to display the 10-20 latest detection snapshots across all my cameras. HA/MQTT has an image entity for each camera showing the latest snapshot below, but this is only the latest:

![image](https://github.com/user-attachments/assets/3eb0cb3f-6845-4642-80f3-59c6e96dc3e1)

I want to display the 10-20 latest snapshots. Is that possible? Is there a way to get those images into HA via Frigate or connect HA to where Frigate stores those on my Frigate server?

If relevant, I run HA and Frigate on seperate servers.

### Version

 0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  host: 192.168.107.2
  port: 1883
  user: user1
  password: password1
  topic_prefix: frigate

go2rtc:
  streams:
    FrontPorch:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=0
    FrontPorch_sub:
      - rtsp://admin:admin@192.168.107.47:554/cam/realmonitor?channel=1&subtype=1
    Driveway:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:admin@192.168.107.42:554/cam/realmonitor?channel=1&subtype=1

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
  Driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 30
          mode: motion
    objects:
      track:
        - person
        - dog
        - cat
        - bear
      mask: 0.189,0.697,0.812,0.743,1,0.982,0.001,0.996,0.004,0.703
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/frigate:/config
      - /media/user/T7:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua
