### DISCUSSION TITLE
[Support]: Frigate+ buttons / integration missing since update to 0.15.0

### DISCUSSION THREAD

**Discussion by jake1164** [blakeblackshear/frigate#16863] [General Support] [answered]
### Describe the problem you are having

Prior to the update frigate+ was working, I had a review button and could submit images to frigate+ and my frigate+ model worked.  Since updating to frigate 0.15.0 via docker everything seems to work, however, I no longer have review buttons on the left side (bottom bird button under export).  The model does seem to work, I just cant submit updated images.

I went into frigate+ and regenerated a new api key and applied that and then recreated the container and its the same result.  When I print the ENV values in the container it shows a PLUS_API_KEY so I am unsure what else to do to get the submit button to show up. 

```
docker exec frigate printenv
PATH=/usr/local/go2rtc/bin:/usr/local/tempio/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=frigate
FRIGATE_MQTT_USERNAME=REDACTED
FRIGATE_MQTT_PASSWORD=REDACTED
LIBVA_DRIVER_NAME=radeonsi
PLUS_API_KEY=REDACTED
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
TOKENIZERS_PARALLELISM=true
TRANSFORMERS_NO_ADVISORY_WARNINGS=1
OPENCV_FFMPEG_LOGLEVEL=8
S6_LOGGING_SCRIPT=T 1 n0 s10000000 T
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
HOME=/root
```

### Version

0.15.0-cea210d

### What browser(s) are you using?

Edge

### Frigate config file

```yaml
# yaml-language-server: $schema=http://toontown-app-srv1:5000/api/config/schema.json
mqtt:
  enabled: true
  host: 127.0.0.1
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USERNAME}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

logger:
  default: info
  logs:
    frigate.mqtt: info

# NOTE: pci coral requires the driver to be installed and currently it has to be from : https://github.com/google/gasket-driver
detectors:
  coralusb:
    type: edgetpu
    device: usb
  coralpci:
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
#    - car
    - amazon
    - fedex
    - ups
    - package

#ffmpeg:
#  hwaccel_args: preset-vaapi

model:
  path: plus://9b623d8b7f1775090d6d1e0e6aa4b802

record:
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7
snapshots:
  enabled: true
  retain:
    default: 7

tls:
  enabled: true

cameras:
############  Back Yard Camera  ############
  back_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_BACKYARD_USERNAME}:{FRIGATE_CAMERA_BACKYARD_PASSWORD}@192.168.1.73:554/ISAPI/Streaming/channels/102
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_BACKYARD_USERNAME}:{FRIGATE_CAMERA_BACKYARD_PASSWORD}@192.168.1.73:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
    zones:
      Patio-zone:
        coordinates: 0,0.764,0.662,0.687,0.658,0.994,0.002,0.993
        loitering_time: 0
      Backyard-zone:
        coordinates: 0.007,0.417,0.729,0.371,0.997,0.499,0.995,0.645,0.703,0.656,0.001,0.756
        loitering_time: 0
      pergola-zone:
        coordinates: 0.664,0.68,0.995,0.677,0.998,0.987,0.662,1
        loitering_time: 0
############  Driveway Camera  ############
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_DRIVEWAY_USERNAME}:{FRIGATE_CAMERA_DRIVEWAY_PASSWORD}@192.168.1.71:554/ISAPI/Streaming/channels/102
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_DRIVEWAY_USERNAME}:{FRIGATE_CAMERA_DRIVEWAY_PASSWORD}@192.168.1.71:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
    zones:
      Driveway-zone:
        coordinates: 0.017,0.173,0.294,0.155,0.967,1,0.116,0.997
        loitering_time: 0
      road-zone:
        coordinates: 0.093,0,0.811,0.045,0.932,0.19,0.916,0.269,0.528,0.169,0.094,0.162
        loitering_time: 0
    review:
      alerts:
        required_zones: Driveway-zone
############  Front Door Camera  ############
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_FRONTDOOR_USERNAME}:{FRIGATE_CAMERA_FRONTDOOR_PASSWORD}@192.168.1.70:554/ISAPI/Streaming/channels/102
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_FRONTDOOR_USERNAME}:{FRIGATE_CAMERA_FRONTDOOR_PASSWORD}@192.168.1.70:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
    zones:
      Frontdoor-zone:
        coordinates: 0.003,0.374,0.902,0.574,0.903,0.983,0.004,0.997
        loitering_time: 0
      Driveway-zone:
        coordinates: 0.002,0,0.922,0.001,0.905,0.57,0.004,0.362
        loitering_time: 0
############  Front Yard Camera  ############
  front_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_FRONTYARD_USERNAME}:{FRIGATE_CAMERA_FRONTYARD_PASSWORD}@192.168.1.75:554/ISAPI/Streaming/channels/102
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_FRONTYARD_USERNAME}:{FRIGATE_CAMERA_FRONTYARD_PASSWORD}@192.168.1.75:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
    zones:
      Frontyard-zone:
        coordinates: 
          0,0.609,0.616,0.333,0.9,0.379,0.821,0.554,0.986,0.645,0.995,0.994,0.531,0.986,0.32,0.726,0.062,0.805,0,0.787,0,0.659
        loitering_time: 0
      Driveway-zone:
        coordinates: 0.741,0.289,0.998,0.333,0.998,0.401,0.64,0.333
        loitering_time: 0
      Frontdoor-zone:
        coordinates: 0.897,0.382,0.999,0.415,0.997,0.633,0.83,0.55
        loitering_time: 0
      road-zone:
        coordinates: 
          0.001,0.606,0.615,0.334,0.989,0.213,0.979,0.123,0.814,0.08,0.544,0.151,0.188,0.233,0.001,0.327
        loitering_time: 0
      neighbor-zone:
        coordinates: 1,0.216,0.998,0.323,0.777,0.295
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Driveway-zone
          - Frontdoor-zone
          - Frontyard-zone
    motion:
      threshold: 30
      contour_area: 35
      improve_contrast: 'true'
      mask: 0,0,0.868,0,1,0.109,0.946,0.138,0.785,0.133,0.635,0.15,0.439,0.181,0,0.25
############  Garage BackYard Camera  ############
  garage_backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_TRAMP_USERNAME}:{FRIGATE_CAMERA_TRAMP_PASSWORD}@192.168.1.77:554/Preview_01_main
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_TRAMP_USERNAME}:{FRIGATE_CAMERA_TRAMP_PASSWORD}@192.168.1.77:554/Preview_01_sub
          roles:
            - detect
    onvif:
      host: 192.168.1.77
      port: 8000
      user: '{FRIGATE_CAMERA_TRAMP_USERNAME}'
      password: '{FRIGATE_CAMERA_TRAMP_PASSWORD}'
      autotracking:
        enabled: false
        calibrate_on_startup: false
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - driveway_zone
        return_preset: home
        timeout: 10
        #movement_weights: []
    record:
      enabled: true
    zones:
      Backyard-zone:
        coordinates: 
          0.763,0.347,0.998,0.461,0.996,0.659,0.902,0.994,0.008,0.99,0.013,0.482,0.581,0.334
        loitering_time: 0
      neighbor-zone:
        coordinates: 0.747,0.329,0.999,0.443,0.997,0.286,0.862,0.209
        loitering_time: 0
    review:
      alerts:
        required_zones: Backyard-zone
############  Garage Driveway Camera  ############
  garage_driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_GARAGE_USERNAME}:{FRIGATE_CAMERA_GARAGE_PASSWORD}@192.168.1.76:554/Preview_01_main
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_GARAGE_USERNAME}:{FRIGATE_CAMERA_GARAGE_PASSWORD}@192.168.1.76:554/Preview_01_sub
          roles:
            - detect
    onvif:
      host: 192.168.1.76
      port: 8000
      user: '{FRIGATE_CAMERA_GARAGE_USERNAME}'
      password: '{FRIGATE_CAMERA_GARAGE_PASSWORD}'
      autotracking: # Not Supported on this camera
        enabled: false
        calibrate_on_startup: false
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - driveway_zone
        return_preset: home
        timeout: 10
        #movement_weights: []
    record:
      enabled: true
    zones:
      Driveway-zone:
        coordinates: 0.485,0.158,0.612,0.154,0.703,0.233,0.998,0.805,1,0.989,0.19,0.994
        loitering_time: 0
      road-zone:
        coordinates: 0.842,0.162,0.441,0.151,0.41,0.011,0.89,0
        loitering_time: 0
      neighbor-zone:
        coordinates: 0.618,0.157,0.849,0.168,0.998,0.337,0.995,0.797,0.702,0.22
        loitering_time: 0
      Frontdoor-zone:
        coordinates: 0.439,0.157,0.478,0.157,0.446,0.261
        loitering_time: 0
      Patio-zone:
        coordinates: 0.052,0.621,0.183,0.993,0.002,0.997,0.001,0.7
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Driveway-zone
          - Frontdoor-zone
          - Patio-zone
############  Patio Driveway Camera  ############
  patio_driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_PATIO_USERNAME}:{FRIGATE_CAMERA_PATIO_PASSWORD}@192.168.1.72:554/ISAPI/Streaming/channels/102
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_PATIO_USERNAME}:{FRIGATE_CAMERA_PATIO_PASSWORD}@192.168.1.72:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
    zones:
      Driveway-zone:
        coordinates: 0.104,0.25,0.267,0.219,0.3,0.47,0.126,0.495
        loitering_time: 0
      neighbor-zone:
        coordinates: 0.1,0.041,0.273,0.047,0.272,0.199,0.103,0.244
        loitering_time: 0
      Patio-zone:
        coordinates: 
          0.055,0.496,0,1,0.998,0.992,0.991,0.523,0.793,0.385,0.776,0.219,0.293,0.279,0.31,0.487
        loitering_time: 0
        inertia: 3
      Backyard-zone:
        coordinates: 0.784,0.109,0.998,0.23,0.992,0.512,0.794,0.382
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Patio-zone
          - Driveway-zone
          - Backyard-zone
############  Side Yard Camera  ############
  side_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_SIDEYARD_USERNAME}:{FRIGATE_CAMERA_SIDEYARD_PASSWORD}@192.168.1.74:554/ISAPI/Streaming/channels/102
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_SIDEYARD_USERNAME}:{FRIGATE_CAMERA_SIDEYARD_PASSWORD}@192.168.1.74:554/ISAPI/Streaming/channels/101
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
    zones:
      Sideyard-zone:
        coordinates: 0.756,0.08,0.286,0.989,0.929,0.992,0.989,0.109
        loitering_time: 0
      road-zone:
        coordinates: 0.271,0.004,0.998,0.001,0.994,0.113,0.735,0.075,0.472,0.089,0.286,0.172
        loitering_time: 0
      neighbor-zone:
        coordinates: 0.284,0.176,0.48,0.092,0.748,0.087,0.274,0.986,0.005,0.989,0.002,0.261
        loitering_time: 0
    review:
      alerts:
        required_zones: Sideyard-zone

############  Kitchen Camera  ############
  kitchen:
    enabled: false
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_KITCHEN_USERNAME}:{FRIGATE_CAMERA_KITCHEN_PASSWORD}@192.168.1.69/Preview_01_main
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_KITCHEN_USERNAME}:{FRIGATE_CAMERA_GARAGE_PASSWORD}@192.168.1.69/Preview_01_sub
          roles:
            - detect
    onvif:
      host: 192.168.1.69
      port: 8000
      user: '{FRIGATE_CAMERA_KITCHEN_USERNAME}'
      password: '{FRIGATE_CAMERA_KITCHEN_PASSWORD}'
      autotracking:
        enabled: false
        calibrate_on_startup: false
        zooming: disabled
        zoom_factor: 0.3
        track:
          - cat
        return_preset: home
        timeout: 10
        #movement_weights: []
    record:
      enabled: true
    review:
      alerts:
        labels:
          - cat
############  Office Camera  ############
  office:
    enabled: false
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_CAMERA_OFFICE_USERNAME}:{FRIGATE_CAMERA_OFFICE_PASSWORD}@192.168.1.68:554/Preview_01_main
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_CAMERA_OFFICE_USERNAME}:{FRIGATE_CAMERA_OFFICE_PASSWORD}@192.168.1.68:554/Preview_01_sub
          roles:
            - detect
    onvif:
      host: 192.168.1.68
      port: 8000
      user: '{FRIGATE_CAMERA_OFFICE_USERNAME}'
      password: '{FRIGATE_CAMERA_OFFICE_PASSWORD}'
      autotracking: # Relative zoom not supported & FOV relative movement not supported
        enabled: false
        calibrate_on_startup: true
        zooming: disabled
        zoom_factor: 0.3
        required_zones:
          - litter-zone
          - office-zone
          - window-zone
        track:
          - cat
        return_preset: home
        timeout: 10
        #movement_weights: []
    record:
      enabled: true
    review:
      alerts:
        labels:
          - cat
    zones:
      litter-zone:
        coordinates: 0.831,0.405,0.921,0.403,0.949,0.55,0.911,0.69,0.777,0.714,0.734,0.571
        loitering_time: 0
        objects: cat
      office-zone:
        coordinates: 0.302,0.396,0.826,0.402,0.732,0.564,0.774,0.713,0.913,0.699,1,1,0.007,0.993
        loitering_time: 0
        objects: cat
      window-zone:
        coordinates: 0.406,0.032,0.91,0.085,0.898,0.405,0.398,0.382
        inertia: 3
        loitering_time: 0
        objects: cat

version: 0.15-1
camera_groups:
  front:
    order: 1
    icon: LuDoorOpen
    cameras:
      - driveway
      - front_door
      - front_yard
      - garage_driveway
      - side_yard
  back:
    order: 2
    icon: LuAlertCircle
    cameras:
      - back_yard
      - garage_backyard
      - patio_driveway
  birdseye:
    order: 3
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
info | 2025-02-28 10:17:20 | startup                               | Preparing Frigate...
info | 2025-02-28 10:17:20 | startup                               | Starting Frigate...
info | 2025-02-28 10:17:22 | frigate.util.config                   | Checking if frigate config needs migration...
info | 2025-02-28 10:17:22 | frigate.util.config                   | frigate config does not need migration...
info | 2025-02-28 10:17:22 | frigate.util.services                 | Automatically detected vaapi hwaccel for video decoding
info | 2025-02-28 10:17:54 | frigate.app                           | Starting Frigate (0.15.0-cea210d)
info | 2025-02-28 10:17:54 | peewee_migrate.logs                   | Starting migrations
info | 2025-02-28 10:17:54 | peewee_migrate.logs                   | There is nothing to migrate
info | 2025-02-28 10:17:54 | frigate.app                           | Recording process started: 741
info | 2025-02-28 10:17:54 | frigate.app                           | Review process started: 750
info | 2025-02-28 10:17:54 | frigate.app                           | go2rtc process pid: 98
info | 2025-02-28 10:17:54 | detector.coralusb                     | Starting detection process: 757
info | 2025-02-28 10:17:54 | detector.coralpci                     | Starting detection process: 762
info | 2025-02-28 10:17:54 | frigate.app                           | Output process started: 783
info | 2025-02-28 10:17:54 | frigate.detectors.plugins.edgetpu_tfl | Attempting to load TPU as pci:0
info | 2025-02-28 10:17:54 | frigate.detectors.plugins.edgetpu_tfl | TPU found
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for back_yard: 836
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for driveway: 847
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for front_door: 858
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for front_yard: 867
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for garage_backyard: 886
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for garage_driveway: 897
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for patio_driveway: 910
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor started for side_yard: 916
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor not started for disabled camera kitchen
info | 2025-02-28 10:17:54 | frigate.app                           | Camera processor not started for disabled camera office
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for back_yard: 934
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for driveway: 937
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for front_door: 941
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for front_yard: 949
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for garage_backyard: 955
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for garage_driveway: 961
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for patio_driveway: 976
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process started for side_yard: 979
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process not started for disabled camera kitchen
info | 2025-02-28 10:17:54 | frigate.app                           | Capture process not started for disabled camera office
info | 2025-02-28 10:17:54 | frigate.api.fastapi_app               | Starting FastAPI app
info | 2025-02-28 10:17:55 | frigate.api.fastapi_app               | FastAPI started
info | 2025-02-28 10:17:54 | frigate.detectors.plugins.edgetpu_tfl | Attempting to load TPU as usb
info | 2025-02-28 10:17:57 | frigate.detectors.plugins.edgetpu_tfl | TPU found
```

### Relevant go2rtc log output

```shell
info | 2025-02-28 10:17:20 | startup | Preparing new go2rtc config...
info | 2025-02-28 10:17:20 | startup | Starting go2rtc...
info | 2025-02-28 10:17:20 | startup | go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info | 2025-02-28 10:17:20 | startup | config path=/dev/shm/go2rtc.yaml
info | 2025-02-28 10:17:20 | rtsp    | listen addr=:8554
info | 2025-02-28 10:17:20 | api     | listen addr=:1984
info | 2025-02-28 10:17:20 | webrtc  | listen addr=:8555/tcp
info | 2025-02-28 10:17:30 | startup | Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
# NOTE: Environment variables are stored in the .env file.
services:
  frigate:
    hostname: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    shm_size: "500mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128  # Path for AMD GPU
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker-apps/frigate:/config
      - /images/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
####  Wish this worked without host mode.  Have to look into this more.
    network_mode: host
#    ports:
#      - 5000:5000
#      - 8554:8554
#      - 8555:8555/tcp
#      - 8555:8555/udp
    environment:
      LIBVA_DRIVER_NAME: radeonsi
      PLUS_API_KEY: ${PLUS_API_KEY}
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
      FRIGATE_MQTT_USERNAME: ${FRIGATE_MQTT_USERNAME}
      FRIGATE_CAMERA_BACKYARD_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_BACKYARD_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_DRIVEWAY_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_DRIVEWAY_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_FRONTDOOR_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_FRONTDOOR_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_FRONTYARD_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_FRONTYARD_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_TRAMP_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_TRAMP_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_GARAGE_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_GARAGE_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_PATIO_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_PATIO_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_SIDEYARD_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_SIDEYARD_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_KITCHEN_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_KITCHEN_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_LIVINGROOM_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_LIVINGROOM_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
      FRIGATE_CAMERA_OFFICE_USERNAME: ${FRIGATE_CAMERA_USERNAME}
      FRIGATE_CAMERA_OFFICE_PASSWORD: ${FRIGATE_CAMERA_PASSWORD}
    cap_add:
      - CAP_PERFMON
    depends_on:
      - mqtt
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision, reolink

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/4e4fcdc0-8d1f-4826-b155-2961a8fa9f3a)

**Comment by hawkeye217** [comment, marked as answer]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/16391), Usage question 1.

**Comment by jake1164** [comment]
Ok.. 
1) - I  disabled hardware acceleration and have the same issue.
2) - Which setting should be used for `16x AMD Ryzen 9 7940HS w/ Radeon 780M Graphics`

```
objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
#    - car
    - amazon
    - fedex
    - ups
    - package

#ffmpeg:
#  hwaccel_args: preset-vaapi

model:
  path: plus://
```

![image](https://github.com/user-attachments/assets/bd77b30f-037f-40d0-920c-2cbae7a33a9b)
