### DISCUSSION TITLE
[Support]: Sync recordings option not working

### DISCUSSION THREAD

**Discussion by rstanislav** [blakeblackshear/frigate#16868] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When option sync_recordings is enabled after start abort message in log appears, and no recordings deleted. (all of them should be deleted)
025-02-28 22:37:54.485843364  [2025-02-28 22:37:54] frigate.record.util            INFO    : Deleting 261000 recording DB entries with missing files

2025-02-28 22:37:54.667605538  [2025-02-28 22:37:54] frigate.record.util            WARNING : Deleting 0.996605% of recordings DB entries, could be due to configuration error. Aborting...

### Steps to reproduce

1. enable sync_recordings in config
2. restart

### Version

 0.15.0-cea210d

### Frigate config file

```yaml
record:
  sync_recordings: True
  enabled: true
  retain:
    days: 15
    mode: motion
  alerts:
    retain:
      days: 60
      mode: motion
    pre_capture: 5
    post_capture: 10
  detections:
    retain:
      days: 90
      mode: motion
    pre_capture: 5
    post_capture: 10
snapshots:
  enabled: true
  bounding_box: true
```

### docker-compose file or Docker CLI command

```yaml
..
```

### Relevant Frigate log output

```shell
025-02-28 22:37:54.485843364  [2025-02-28 22:37:54] frigate.record.util            INFO    : Deleting 261000 recording DB entries with missing files

2025-02-28 22:37:54.667605538  [2025-02-28 22:37:54] frigate.record.util            WARNING : Deleting 0.996605% of recordings DB entries, could be due to configuration error. Aborting...
```

### Relevant go2rtc log output

```shell
Empty
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Any

### Screenshots of the Frigate UI's System metrics pages

..
