### DISCUSSION TITLE
Filter detection based on zones

### DISCUSSION THREAD

**Discussion by jchretien** [blakeblackshear/frigate#16862] [Ask A Question] [answered]
I live on a boulevard where there's about 5000 cars a day passing.

I want to detect cars entering my driveway.

I can filter out cars from the boulevard in "Alers" or "Detections".

However each single car driving on the boulevard will appear in the "Explore" tab. And they will be sent my genai provider which is fun and cool but will become expensive.

Is there a way to send to genai only the detections that are within the zones of interest?

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/genai#custom-prompts

**Comment by jchretien** [comment]
Yes I have read the documentation.

That doesn't answer the question.

What if I want to track something from the street but not the cars?

**Reply by NickM-27** [reply]
Then you'll create a second zone that covers those objects and make both required

**Reply by jchretien** [reply]
I don't understand

**Reply by hawkeye217** [reply]
You can create a zone for the street area and specify which objects you want to track in that zone [(1)](https://docs.frigate.video/configuration/zones/) . For example, you could configure the zone to only track people, packages, or other objects while excluding cars.

Here's how you can configure this:

```yaml
cameras:
  name_of_your_camera:
    zones:
      street:
        coordinates: ... (your street area coordinates)
        objects:
          - person
          - package
```


This configuration will create a zone that only tracks the specified objects (person and package in this example) while ignoring cars in that area. You can adjust the list of objects based on what you want to track.

Additionally, you can use the zones feature to restrict alerts and detections to specific areas and object types. This gives you fine-grained control over what gets detected and recorded in different areas of your camera view.

**Reply by hawkeye217** [reply]
You can configure GenAI to only generate descriptions for objects in specific zones. Here's how to set it up:

```yaml
cameras:
  front_camera:
    genai:
      enabled: True
      required_zones:
        - driveway_entrance
      objects:
        - car
```
 [(1)](https://docs.frigate.video/configuration/genai/#custom-prompts) 

This configuration will:
1. Only generate AI descriptions for objects in the specified zone (driveway_entrance) 
2. Only process cars as specified in the objects list 

You can combine this with zone-specific object tracking. For example:

```yaml
cameras:
  name_of_your_camera:
    zones:
      driveway_entrance:
        coordinates: ... (just your driveway entrance)
        objects:
          - car
```
 [(2)](https://docs.frigate.video/configuration/zones/) 

This setup ensures that:
- Only cars entering your specified driveway zone will be tracked 
- Only those tracked cars will be sent to your AI provider for description generation  [(1)](https://docs.frigate.video/configuration/genai/#custom-prompts) 
- Cars on the boulevard outside your zones of interest won't consume your AI API usage  [(3)](https://docs.frigate.video/configuration/genai/#usage-and-best-practices)

**Reply by jchretien** [reply]
What if I want to detect dogs on the street and send those to genai ?

**Reply by hawkeye217** [reply]
You can configure your camera to detect dogs in a specific street zone while still filtering out cars. Here's how to set it up:

```yaml
cameras:
  street_camera:
    zones:
      street_zone:
        coordinates: ... (your street area coordinates)
        objects:
          - dog
    genai:
      enabled: True
      required_zones:
        - street_zone
      objects:
        - dog
```
 [(1)](https://docs.frigate.video/configuration/genai/#usage-and-best-practices) 

This configuration will:
1. Create a zone for the street area that only tracks dogs  [(2)](https://docs.frigate.video/configuration/zones/) 
2. Enable GenAI processing only for dogs detected in that specific zone  [(1)](https://docs.frigate.video/configuration/genai/#usage-and-best-practices) 
3. Send only those specific detections to your AI provider for description generation 

You can also customize the AI prompt specifically for dogs in this zone:

```yaml
genai:
  object_prompts:
    dog: "Observe the dog in these images. Focus on its movement and intent (e.g., wandering, running, interacting with objects)."
```


This setup ensures you're only processing and generating AI descriptions for dogs in your specified street zone, helping to manage API usage while still capturing the specific activity you're interested in monitoring.

**Reply by jchretien** [reply]
So if I have 2 cameras with 5 zones each, I'm gonna need to list all objects for each zone.... That's a lot of configuration...?!

**Reply by hawkeye217** [reply]
Luckily you can do some of it through the UI in the Camera Settings, at least for alerts and detections. Point and click!

**Reply by jchretien** [reply]
It was done already for alerts and detection

But for genai it's another story... We need to repeat the configuration for genai it's like a completely independent application that has its own configuration section.

**Reply by jchretien** [reply]
If you want to detect every objects in every zones you don't need to specify anything.

But if you have 10 zones on 10 cameras and want to detect every objects from every zones except one object in one zone you'll have to list 10 objects in each zone of each camera. Except in one of the 100 zones you'll not include the one object you don't want to detect in that zone, is that correct?

**Reply by hawkeye217** [reply]
Configuration is needed only if the defaults are not appropriate. You may not want to run GenAI for all of your zones or all of your objects - in fact, many users have reduced the amount of GenAI calls because they quickly exceeded Gemini's quota, for example. There shouldn't be too much configuration for you to do if that's the case.

**Reply by jchretien** [reply]
what do you mean by "not too much configuration" ?

**Reply by jchretien** [reply]
May I propose some improvement?

Send to GenAI only the objects that caused alerts or detections?

**Reply by hawkeye217** [reply]
> what do you mean by "not too much configuration" ?

Most users have found that GenAI is only useful for a small percentage of their tracked objects. For example, some users have been using it for audio announcements for their front door. Others have used it to try to identify cars that have pulled into their driveway.

This makes configuration easy because you're only working with a zone or two.

Unless you pay for API access or are running with the Ollama provider and have a hefty GPU, generating descriptive text for tracked objects can be expensive and in most cases we've seen, is impractical - especially with how well the Semantic Search feature works in 0.15. See this post: https://github.com/blakeblackshear/frigate/discussions/14654

Frigate allows you to configure it to your liking, though - so you're certainly not limited by anything there.

**Reply by jchretien** [reply]
Hi Josh,
I appreciate your patience in trying to help but still I dont understand how your examples will allow me to enable genai for every zones but with different objects list for each zone...

**Reply by hawkeye217** [reply]
You can enable GenAI for specific zones and objects by configuring both at the camera level [(1)](https://docs.frigate.video/configuration/genai/#configuration) . Here's how to set it up:

```yaml
cameras:
  front_door:
    genai:
      use_snapshot: True
      prompt: "Analyze the {label} in these images from the {camera} security camera at the front door. Focus on the actions and potential intent of the {label}."
      object_prompts:
        person: "Examine the person in these images. What are they doing, and how might their actions suggest their purpose (e.g., delivering something, approaching, leaving)? If they are carrying or interacting with a package, include details about its source or destination."
        cat: "Observe the cat in these images. Focus on its movement and intent (e.g., wandering, hunting, interacting with objects). If the cat is near the flower pots or engaging in any specific actions, mention it."
      objects:
        - person
        - cat
      required_zones:
        - steps
```

For each zone, you can specify different objects to track [(3)](https://docs.frigate.video/configuration/zones/) :

```yaml
cameras:
  name_of_your_camera:
    zones:
      entire_yard:
        coordinates: ... 
        objects:
          - person
      front_yard_street:
        coordinates: ...
        objects:
          - car
```

If you want some help putting together your config for everything you'd like to use GenAI for, you could use our AI at https://docs.frigate.video - just show it your config and ask it questions. It's been very helpful for lots of users.

**Reply by jchretien** [reply]
My goal is simple:
1. Send cars detected in "driveway" zone from "name_of_my_camera" to genai with the  default prompt.
2. **Do not** send detected cars in "street" zone from "name_of_my_camera" to genai

With all the examples you sent me I can't figure how to accomplish my goal.

**Reply by hawkeye217** [reply]
Here's how to configure this in your Frigate setup:

```yaml
cameras:
  name_of_my_camera:
    genai:
      enabled: True
      required_zones:
        - driveway
      objects:
        - car
    zones:
      driveway:
        coordinates: ... # Add your driveway coordinates here
        objects:
          - car
      street:
        coordinates: ... # Add your street coordinates here
        objects:
          - car
```
 [(1)](https://docs.frigate.video/configuration/genai/#configuration) ,  [(2)](https://docs.frigate.video/configuration/zones/) 

This configuration will:
1. Enable GenAI for your camera  [(1)](https://docs.frigate.video/configuration/genai/#configuration) 
2. Only process cars detected in the "driveway" zone for GenAI analysis 
3. Still track cars in both zones, but only send driveway detections to GenAI  [(2)](https://docs.frigate.video/configuration/zones/) 

The default prompt will be used since we haven't specified a custom one  [(3)](https://docs.frigate.video/configuration/genai/#usage-and-best-practices) . The system will analyze the car's behavior and potential intent rather than just describing its appearance .
