### DISCUSSION TITLE
Pulling my hair out - payload_json array item comparison

### DISCUSSION THREAD

**Discussion by danlo315** [blakeblackshear/frigate#16871] [Ask A Question]
Help! I’m literally at my wits end trying to figure out something that I thought would be relatively simple. I am using Frigate’s frigate/reviews MQTT topic as an automation trigger to send out a notification. I am trying to build logic to only pull certain objects detected in a review topic.

```
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: mqtt
  topic: frigate/reviews
  payload: >-
    {"type": "end", "before": {"id": "1740765619.832969-b4tgkm", "camera":
    "doorbell", "start_time": 1740765619.832969, "end_time": null, "severity":
    "detection", "thumb_path":
    "/media/frigate/clips/review/thumb-doorbell-1740765619.832969-b4tgkm.webp",
    "data": {"detections": ["1740765616.092773-ja4l4g"], "objects": ["car"],
    "sub_labels": [], "zones": [], "audio": []}}, "after": {"id":
    "1740765619.832969-b4tgkm", "camera": "doorbell", "start_time":
    1740765619.832969, "end_time": 1740765622.916183, "severity": "detection",
    "thumb_path":
    "/media/frigate/clips/review/thumb-doorbell-1740765619.832969-b4tgkm.webp",
    "data": {"detections": ["1740765616.092773-ja4l4g"], "objects": ["car"],
    "sub_labels": [], "zones": [], "audio": []}}}
  qos: 0
  description: mqtt topic frigate/reviews
  payload_json:
    type: end
    before:
      id: 1740765619.832969-b4tgkm
      camera: doorbell
      start_time: 1740765619.832969
      end_time: null
      severity: detection
      thumb_path: /media/frigate/clips/review/thumb-doorbell-1740765619.832969-b4tgkm.webp
      data:
        detections:
          - 1740765616.092773-ja4l4g
        objects:
          - car
        sub_labels: []
        zones: []
        audio: []
    after:
      id: 1740765619.832969-b4tgkm
      camera: doorbell
      start_time: 1740765619.832969
      end_time: 1740765622.916183
      severity: detection
      thumb_path: /media/frigate/clips/review/thumb-doorbell-1740765619.832969-b4tgkm.webp
      data:
        detections:
          - 1740765616.092773-ja4l4g
        objects:
          - car
        sub_labels: []
        zones: []
        audio: []
```

I have a template evaluation condition, but this fails evaluates to false with the message above.

```
{% set ns = namespace(count=0') %}
{% set objects = trigger.payload_json["after"]["data"]["objects"] %}
{% set detect_list = ['car','truck','bus','person'] %}
{% for items in objects %}
  {% if items in detect_list %}
    {% set ns.count = ns.count + 1 %}
    {{ ns.count }}
  {% endif %}
{% endfor %}
{{ ns.count > 0 }}
```

Can anyone shine some light on what am I overlooking? the [‘car’] object should be in detect_list.

Thanks.
