### DISCUSSION TITLE
[Support]:  CPU usage with detect enabled and Coral TPU USB

### DISCUSSION THREAD

**Discussion by comdinet** [blakeblackshear/frigate#16876] [General Support]
### Describe the problem you are having

I was under impression that VM CPU would not be used for detection if I use coral tpu?
CPU for frigate is upwards of 80% at all times with detection enabled. TPU is recognized and in hw monitor it says "Coral: 81%" but also VM cpu is skyhigh.
This is running on ubuntu vm in proxmox on beelink 12s.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
tls:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  Bart:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:WAOKTM@192.168.1.123:554/h264_stream
          roles:
            - record
            - detect
    motion:
      threshold: 5
      contour_area: 5
      improve_contrast: true
      mask: 0.07,0.26,0.1,0.481,0.312,0.473,0.286,0.218
    zones: {}
version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: small
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 3
      mode: motion
  detections:
    retain:
      days: 3
      mode: motion
```

### Relevant Frigate log output

```shell
2025-03-01 08:45:42.250772194  [2025-03-01 08:45:42] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-03-01 08:45:42.395974466  [2025-03-01 08:45:42] frigate.api.fastapi_app        INFO    : FastAPI started
2025-03-01 08:45:44.649467785  [2025-03-01 08:45:41] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-03-01 08:45:44.655599838  [2025-03-01 08:45:44] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-03-01 08:45:45.414980876  [INFO] Starting go2rtc healthcheck service...
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    shm_size: "256MB"
    volumes:
      - ./config:/config
      - /mnt/Data/Share/Frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

ezviz ze5

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b6c603b5-7505-43dd-bab7-5946d3ed12b3)
![image](https://github.com/user-attachments/assets/b64e224a-dc2e-484f-bd34-4aa1fd76b8ff)
