### DISCUSSION TITLE
[Support]: Stationary object detection in HA is unstable

### DISCUSSION THREAD

**Discussion by basvdl** [blakeblackshear/frigate#16890] [General Support]
### Describe the problem you are having

I'm trying to keep track if a specific parking spot is occupied or not. Detecting cars within the `Parking_1` zone is working, but it seems to struggle stationary cars.

The car is already their for hours, and every time motion is detected, Frigate publishes a MQTT message to `frigate/Parking_1/car` with a value `0` and at the same moment a message with value `1`.

This will trigger my simple automation that is watching the occupancy sensor (`binary_sensor.parking_1_car_occupancy`) in HA. As you see in the screenshot, it is non stop changing. I noticed that the moment it is changing, is basically when something is moving.

<img width="556" alt="image" src="https://github.com/user-attachments/assets/c5d85150-5bfd-44b5-a1d7-ded2bd99525e" />

This is the setup of my area's:

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/687a3bf6-5981-4a4b-b908-c3e19ef7819c" />

How can I tune Frigate to make sure that it is not sending 0 cars followed by 1 car when motion is detected.

Thanks!

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 192.168.50.156
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Frigate provides many types, see https://docs.frigate.video/configuration/object_detectors for more details (default: shown below)
    # Additional detector types can also be plugged in.
    # Detectors may require additional configuration.
    # Refer to the Detectors configuration page for more information.
    type: edgetpu
    device: usb

# Optional: TLS configuration
tls:
  # Optional: Enable TLS for port 8971 (default: shown below)
  enabled: False

# Optional: Authentication configuration
auth:
  # Optional: Enable authentication
  enabled: True

# Optional: Audio Events Configuration
# NOTE: Can be overridden at the camera level
audio:
  # Optional: Enable audio events (default: shown below)
  enabled: False

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

# Optional: set environment variables
environment_vars:
  LIBVA_DRIVER_NAME: i965 # iHD

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False

# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: auto detect)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi # preset-vaapi, preset-intel-qsv-h264, preset-intel-qsv-h265
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 640
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 360
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat

# Optional: Review configuration
# NOTE: Can be overridden at the camera level
review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - car
      - person
      - cat
  # Optional: detections configuration
  detections:
    # Optional: labels that qualify as a detection (default: all labels that are tracked / listened to)
    labels:
      - car
      - person
      - cat

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: enables detection for the camera (default: True)
  # NOTE: Motion detection is required for object detection,
  #       setting this to False and leaving detect enabled
  #       will result in an error on startup.
  enabled: True
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.01
  # Optional: Height of the resized motion frame  (default: 100)
  # Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 100
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: True
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30

# Optional: Notification Configuration
notifications:
  # Optional: Enable notification service (default: shown below)
  enabled: False

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: False
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of tracked objects (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in alerts and detections section below
    #       if you only want to retain recordings of alerts and detections.
    days: 1
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Recording Preview Settings
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: medium
  # Optional: alert recording settings
  alerts:
    # Optional: Number of seconds before the alert to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the alert to include (default: shown below)
    post_capture: 5
    # Optional: Retention settings for recordings of alerts
    retain:
      # Required: Retention days (default: shown below)
      days: 5
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for alerts regardless of activity
      #   motion - save all recordings segments for alerts with any detected motion
      #   active_objects - save all recording segments for alerts with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
  # Optional: detection recording settings
  detections:
    # Optional: Number of seconds before the detection to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the detection to include (default: shown below)
    post_capture: 5
    # Optional: Retention settings for recordings of detections
    retain:
      # Required: Retention days (default: shown below)
      days: 5
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for detections regardless of activity
      #   motion - save all recordings segments for detections with any detected motion
      #   active_objects - save all recording segments for detections with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion

# Optional: Configuration for the jpg snapshots written to the clips directory for each tracked object
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70

# Optional: Configuration for semantic search capability
semantic_search:
  # Optional: Enable semantic search (default: shown below)
  enabled: False

# Optional: Configuration for AI generated tracked object descriptions
# NOTE: Semantic Search must be enabled for this to do anything.
# WARNING: Depending on the provider, this will send thumbnails over the internet
# to Google or OpenAI's LLMs to generate descriptions. It can be overridden at
# the camera level (enabled: False) to enhance privacy for indoor cameras.
genai:
  # Optional: Enable AI description generation (default: shown below)
  enabled: False

# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.9.2)
# NOTE: The default go2rtc API port (1984) must be used,
#       changing this port for the integrated go2rtc instance is not supported. 
go2rtc:
  streams:
    # demo:
    #   - ffmpeg:rtsp://192.168.50.39:1945/h264.sdp#video=h264#hardware
    demo:
      - ffmpeg:rtsp://192.168.50.27:8554/live#video=h264#hardware=vaapi
    demo_low:
      # - ffmpeg:demo#video=h264#hardware#encoder=h264_vaapi#width=640#height=360
      - ffmpeg:demo#video=h264#hardware=vaapi#width=640#height=360

# Optional: Live stream configuration for WebUI.
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the name of the stream configured in go2rtc
  # that should be used for live view in frigate WebUI. (default: name of camera)
  # NOTE: In most cases this should be set at the camera level only.
  stream_name: demo_low

# Required
cameras:
  # Required: name of the camera
  demo:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: True
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        - path: rtsp://127.0.0.1:8554/demo
          # Required: list of roles for this stream. valid values are: audio,detect,record
          # NOTICE: In addition to assigning the audio, detect, and record roles
          # they must also be enabled in the camera config.
          roles:
            - record
          # Optional: stream specific global args (default: inherit)
          # global_args:
          # Optional: stream specific hwaccel args (default: inherit)
          # hwaccel_args:
          # Optional: stream specific input args (default: inherit)
          # input_args:
        - path: rtsp://127.0.0.1:8554/demo_low
          roles:
            - detect
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      # hwaccel_args:
      # Optional: camera specific input args (default: inherit)
      # input_args:
      # Optional: camera specific output args (default: inherit)
      # output_args:
    live:
      stream_name: demo_low
    objects:
      filters:
        car: {}
    motion:
      mask: 0,0.200,0.320,0.200,0.320,0,0,0
    # Optional: zones for this camera
    zones:
      # Required: name of the zone
      # NOTE: This must be different than any camera names, but can match with another zone on another
      #       camera.
      Parking_1:
        coordinates: 0.160,0.296,0.925,0.320,0.925,0.725,0.160,0.70
        loitering_time: 0
        objects: car
        inertia: 3
    review:
      alerts:
        required_zones: Parking_1
      detections: {}

version: 0.15-1
```

### Relevant Frigate log output

```shell
skipped
```

### Relevant go2rtc log output

```shell
skipped
```

### FFprobe output from your camera

```shell
skipped
```

### Frigate stats

```json
{
  "cameras": {
    "demo": {
      "camera_fps": 5.1,
      "process_fps": 5.1,
      "skipped_fps": 0,
      "detection_fps": 0.2,
      "detection_enabled": true,
      "pid": 402,
      "capture_pid": 409,
      "ffmpeg_pid": 419,
      "audio_rms": 0,
      "audio_dBFS": 0
    }
  },
  "detectors": {
    "coral": {
      "inference_speed": 11.86,
      "detection_start": 0,
      "pid": 369
    }
  },
  "detection_fps": 0.2,
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "31.29%",
      "mem": "-%",
      "clients": {
        "423": "106.41%",
        "424": "316.95%",
        "419": "3.66%"
      }
    }
  },
  "cpu_usages": {
    "frigate.full_system": {
      "cpu": "29.7",
      "mem": "19.9"
    },
    "1": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
    },
    "15": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6-linux-init-shutdownd"
    },
    "16": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
    },
    "24": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-oneshot-runner"
    },
    "25": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-fdholder"
    },
    "26": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync"
    },
    "27": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync-log"
    },
    "28": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate"
    },
    "29": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate-log"
    },
    "30": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc"
    },
    "31": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-healthcheck"
    },
    "32": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-log"
    },
    "33": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx"
    },
    "34": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx-log"
    },
    "45": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
    },
    "46": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
    },
    "86": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
    },
    "87": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
    },
    "88": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
    },
    "90": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
    },
    "98": {
      "cpu": "4.0",
      "cpu_average": "3",
      "mem": "0.2",
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
    },
    "105": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user go2rtc-healthcheck"
    },
    "110": {
      "cpu": "2.2",
      "cpu_average": "2",
      "mem": "2.0",
      "cmdline": "python3 -u -m frigate"
    },
    "127": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: master process nginx"
    },
    "162": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "nginx: worker process"
    },
    "163": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "nginx: worker process"
    },
    "166": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "nginx: worker process"
    },
    "167": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "nginx: worker process"
    },
    "169": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: cache manager process"
    },
    "313": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user certsync"
    },
    "331": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 9999"
    },
    "338": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash"
    },
    "353": {
      "cpu": "2.5",
      "cpu_average": "3",
      "mem": "1.2",
      "cmdline": "frigate.recording_manager"
    },
    "362": {
      "cpu": "0.3",
      "cpu_average": "0",
      "mem": "1.1",
      "cmdline": "frigate.review_segment_manager"
    },
    "369": {
      "cpu": "0.5",
      "cpu_average": "5",
      "mem": "1.2",
      "cmdline": "frigate.detector.coral"
    },
    "388": {
      "cpu": "0.5",
      "cpu_average": "1",
      "mem": "1.1",
      "cmdline": "frigate.output       "
    },
    "402": {
      "cpu": "2.8",
      "cpu_average": "7",
      "mem": "1.2",
      "cmdline": "frigate.process:demo "
    },
    "409": {
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "1.0",
      "cmdline": "frigate.capture:demo "
    },
    "419": {
      "cpu": "2.2",
      "cpu_average": "2",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/demo_low -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "422": {
      "cpu": "4.7",
      "cpu_average": "4",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/demo -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/demo@%Y%m%d%H%M%S%z.mp4"
    },
    "423": {
      "cpu": "10.3",
      "cpu_average": "9",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/demo?video -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf format=vaapi|nv12,hwupload,scale_vaapi=640:360:out_color_matrix=bt709:out_range=tv:format=nv12 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/6cd7d2b2a6abe8e0f77a44edda6acefe"
    },
    "424": {
      "cpu": "23.3",
      "cpu_average": "23",
      "mem": "0.4",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://192.168.50.27:8554/live -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf format=vaapi|nv12,hwupload,scale_vaapi=out_color_matrix=bt709:out_range=tv:format=nv12 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/710a3baec01020c571ed64860f394c3b"
    },
    "437": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "445": {
      "cpu": "1.3",
      "cpu_average": "1",
      "mem": "0.0",
      "cmdline": "intel_gpu_top"
    },
    "10967": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 30s"
    }
  },
  "service": {
    "uptime": 7023,
    "version": "0.15.0-cea210d",
    "latest_version": "0.15.0",
    "storage": {
      "/media/frigate/recordings": {
        "total": 2815430.6,
        "used": 80914.9,
        "free": 2591426.7,
        "mount_type": "ext4"
      },
      "/media/frigate/clips": {
        "total": 2815430.6,
        "used": 80914.9,
        "free": 2591426.7,
        "mount_type": "ext4"
      },
      "/tmp/cache": {
        "total": 953.7,
        "used": 20.9,
        "free": 932.8,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 128,
        "used": 17.6,
        "free": 110.4,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {

    },
    "last_updated": 1740933483
  },
  "processes": {
    "recording": {
      "pid": 353
    },
    "review_segment": {
      "pid": 362
    },
    "go2rtc": {
      "pid": 98
    }
  }
}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "128MB"
    devices:
      - /dev/dri
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - /var/cold/frigate/config:/config
      - /var/cold/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp

    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      # LIBVA_DRIVER_NAME: "iHD"
      LIBVA_DRIVER_NAME: "i965"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Iphone

### Screenshots of the Frigate UI's System metrics pages

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/37f9d574-a4fe-4c56-9e50-d15e46bae3f1" />

<img width="1457" alt="image" src="https://github.com/user-attachments/assets/c40e5964-59d1-410f-85e9-31e4409b35dd" />

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/7694462d-aaee-48c6-bbd7-b29b107f1d89" />

### Any other information that may be helpful

MQTT message received

```
Message 682 received on frigate/Parking_1/all at 4:44 PM:
1
QoS: 0 - Retain: false
```
```
Message 681 received on frigate/Parking_1/car at 4:44 PM:
1
QoS: 0 - Retain: false
```
```
Message 680 received on frigate/events at 4:44 PM:
{"before": {"id": "1740926466.496432-0h7q5h", "camera": "demo", "frame_time": 1740930286.848996, "snapshot": {"frame_time": 1740929791.644283, "box": [233, 134, 507, 252], "area": 32332, "region": [142, 0, 546, 404], "score": 0.8125, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1740926466.496432, "end_time": null, "score": 0.71484375, "box": [239, 142, 504, 262], "area": 31800, "ratio": 2.2083333333333335, "region": [0, 0, 648, 648], "active": false, "stationary": true, "motionless_count": 3425, "position_changes": 1, "current_zones": [], "entered_zones": ["Parking_1"], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": [], "pending_loitering": false, "max_severity": "alert"}, "after": {"id": "1740926466.496432-0h7q5h", "camera": "demo", "frame_time": 1740930287.045585, "snapshot": {"frame_time": 1740929791.644283, "box": [233, 134, 507, 252], "area": 32332, "region": [142, 0, 546, 404], "score": 0.8125, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1740926466.496432, "end_time": null, "score": 0.76953125, "box": [234, 141, 513, 248], "area": 29853, "ratio": 2.607476635514019, "region": [0, 0, 680, 680], "active": false, "stationary": true, "motionless_count": 3426, "position_changes": 1, "current_zones": ["Parking_1"], "entered_zones": ["Parking_1"], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": [], "pending_loitering": false, "max_severity": "alert"}, "type": "update"}
QoS: 0 - Retain: false
```
```
Message 679 received on frigate/Parking_1/all at 4:44 PM:
0
QoS: 0 - Retain: false
```
```
Message 678 received on frigate/Parking_1/car at 4:44 PM:
0
QoS: 0 - Retain: false
```
```
Message 677 received on frigate/events at 4:44 PM:
{"before": {"id": "1740926466.496432-0h7q5h", "camera": "demo", "frame_time": 1740930241.646509, "snapshot": {"frame_time": 1740929791.644283, "box": [233, 134, 507, 252], "area": 32332, "region": [142, 0, 546, 404], "score": 0.8125, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1740926466.496432, "end_time": null, "score": 0.82421875, "box": [230, 143, 503, 251], "area": 29484, "ratio": 2.5277777777777777, "region": [180, 0, 548, 368], "active": false, "stationary": true, "motionless_count": 3199, "position_changes": 1, "current_zones": ["Parking_1"], "entered_zones": ["Parking_1"], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": [], "pending_loitering": false, "max_severity": "alert"}, "after": {"id": "1740926466.496432-0h7q5h", "camera": "demo", "frame_time": 1740930286.848996, "snapshot": {"frame_time": 1740929791.644283, "box": [233, 134, 507, 252], "area": 32332, "region": [142, 0, 546, 404], "score": 0.8125, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1740926466.496432, "end_time": null, "score": 0.71484375, "box": [239, 142, 504, 262], "area": 31800, "ratio": 2.2083333333333335, "region": [0, 0, 648, 648], "active": false, "stationary": true, "motionless_count": 3425, "position_changes": 1, "current_zones": [], "entered_zones": ["Parking_1"], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": [], "pending_loitering": false, "max_severity": "alert"}, "type": "update"}
QoS: 0 - Retain: false
```

**Comment by hawkeye217** [comment]
First, it's important to remember that Frigate [uses the bottom center point of an object's bounding box](https://docs.frigate.video/configuration/zones/) to determine presence in a zone.

Based on the screenshot, you'll probably want to move your zone downwards.

Second, the occupancy sensors in HA have less filters on them, and this is intentional. See [the documentation](https://docs.frigate.video/integrations/home-assistant#i-have-set-up-automations-based-on-the-occupancy-sensors-sometimes-the-automation-runs-because-the-sensors-are-turned-on-but-then-i-look-at-frigate-i-cant-find-the-object-that-triggered-the-sensor-is-this-a-bug). 

I'd suggest tweaking based on those two things. Let us know if you continue to have issues after that.

**Reply by basvdl** [reply]
Hi @hawkeye217 , Thanks for taking the time.

The car is fully inside the box, is it just a matter of giving it just a bit more room?

I'll have a look at the `frigate/events` to see how that behaves vs. the occupancy sensors.

Would you also recommend playing around with the `loitering_time` for instance?

```
      Parking_1:
        coordinates: 0.160,0.296,0.925,0.320,0.925,0.725,0.160,0.70
        loitering_time: 0
        objects: car
        inertia: 3
```

**Reply by hawkeye217** [reply]
> The car is fully inside the box, is it just a matter of giving it just a bit more room?

The car does not have to be fully inside of the box, only the bottom center of the bounding box does. 

So if a car doesn't quite fit inside of your parking spot or the bounding box jumps around slightly from motion or another object passing it, it would explain the behavior you are seeing.

**Comment by basvdl** [comment]
1 more observation is that in debug Frigate has the car still as object detected.
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/8a68323d-40c8-4efe-b55b-5550707c918f" />

However in HA, the occupancy sensors is set to clear.
<img width="663" alt="image" src="https://github.com/user-attachments/assets/43c49d58-cfa4-4a5a-ab27-211a4a8cd213" />

**Comment by basvdl** [comment]
The HA sensor become much more accurate after playing around with the following settings:

```
    objects:
      filters:
        car:
          min_area: 500  # Ignore small objects (adjust as needed)
          max_area: 35000  # Ignore very large objects
          threshold: 0.55  # Confidence threshold
    zones:
      Parking_1:
        loitering_time: 3
        objects: car
```
