### DISCUSSION TITLE
[Support]: ffmpeg missing from Docker container

### DISCUSSION THREAD

**Discussion by mechovation** [blakeblackshear/frigate#16892] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

ffmpeg errors when bringing up docker container with "docker-compose up"

### Steps to reproduce

1. Fresh install using image: ghcr.io/blakeblackshear/frigate:stable
2. Start container
3. Enter container shell
4. ffmpeg -version
5. try install ffmpeg with apt
6. 
root@9e30010c31a2:/etc/apt# ffmpeg -version 
bash: ffmpeg: command not found
root@9e30010c31a2:/etc/apt# apt install ffmpeg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ffmpeg : Depends: libavcodec58 (= 7:4.3.8-0+deb11u3)
          Depends: libavfilter7 (= 7:4.3.8-0+deb11u3)
 libavdevice58 : Depends: libavcodec58 (= 7:4.3.8-0+deb11u3)
                 Depends: libavfilter7 (= 7:4.3.8-0+deb11u3)
 libavformat58 : Depends: libavcodec58 (= 7:4.3.8-0+deb11u3)
 libchromaprint1 : Depends: libavcodec58 (>= 7:4.0)
E: Unable to correct problems, you have held broken packages.
root@9e30010c31a2:/etc/apt# 
...

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

Firefox, but not browser related

### Frigate config file

```yaml
n/a
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
#    image: ghcr.io/blakeblackshear/frigate:0.14.1
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/eric/Docker/Frigate/video:/media/frigate
      - /home/eric/Docker/Frigate/config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_MQTT_PASSWORD: ${pass}
```

### Relevant Frigate log output

```shell
frigate    | 2025-03-02 18:32:19.766193568  [2025-03-02 18:32:19] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
frigate    | 2025-03-02 18:32:19.766531155  [2025-03-02 18:32:19] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
frigate    | 2025-03-02 18:32:23.258024119  [INFO] Starting go2rtc healthcheck service...
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Doorbell , not the problem.

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

Was working fine in 0.14 before I tried to upgrade.   Docker image is non-functional without ffmpeg.
