### DISCUSSION TITLE
Using Go2RTC to transcode to h.264 but recordings are still in h.265

### DISCUSSION THREAD

**Discussion by Foritus** [blakeblackshear/frigate#16891] [Ask A Question] [answered]
Hello friends!
My camera only provides H.265 feeds and they don't play in Firefox. So I followed the instructions to use Go2RTC to transcode the feeds into H.264 and the live view now works perfectly. However the recordings are somehow still being written in the original H.265 :thinking:

Is there a way for me to save the transcoded feed instead? Otherwise viewing history doesn't work in non-hevc-capable browsers :(

Config:
```
# Reference config: https://docs.frigate.video/configuration/reference/
version: 0.15-1

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detect:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  # The path to store the SQLite DB (default: /config/frigate.db)
  path: /db/frigate.db

record:
  enabled: true
  # Sync recordings with disk on startup and once a day (default: false)
  sync_recordings: true

  retain:
    days: 3
    mode: all

  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5

go2rtc:
  streams:
    rear-garden-high-res:
      - rtsp://creds:creds@hostname/h265Preview_01_main
      - "ffmpeg:rear-garden-high-res#video=h264#audio=copy#hardware"
    rear-garden-low-res:
      - rtsp://creds:creds@hostname/h265Preview_01_sub
      - "ffmpeg:rear-garden-low-res#video=h264#audio=copy#hardware"

cameras:
  reargarden:
    enabled: true
    ffmpeg:
      # Use QSV for H.264 here as we're consuming the post-Go2RTC feed here, I think?
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rear-garden-high-res
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rear-garden-low-res
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
      # for daytime.
      improve_contrast: false
      # The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 30
      # Minimum size in pixels in the resized motion image that counts as motion (default: 10)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 10 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      contour_area: 30
    live:
      stream_name: rear-garden-low-res
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: 0)
      # By default the cameras are sorted alphabetically.
      order: 1
    birdseye:
      # Optional: Adjust sort order of cameras in the Birdseye view. Larger numbers come later (default: 0)
      # By default the cameras are sorted alphabetically.
      order: 1
```

**Comment by hawkeye217** [comment, marked as answer]
You should provide a single stream only from go2rtc, eg:

```
go2rtc:
  streams:
    rear-garden-high-res:
      - ffmpeg:rtsp://creds:creds@hostname/h265Preview_01_main#video=h264#audio=copy#hardware
```

This creates a single transcoded stream from go2rtc (rather than the original and transcoded one) that gets fed into Frigate.

**Reply by Foritus** [reply]
oh I may have misunderstood and thought the ffmpeg thing below was some kind of args to the base stream, my bad! I'll give that a try, brb

**Reply by Foritus** [reply]
Nope, still recording in H.265 :<

```
go2rtc:
  streams:
    rear-garden-high-res:
      - rtsp://creds:creds@hostname/h265Preview_01_main#video=h264#audio=copy#hardware"
    rear-garden-low-res:
      - rtsp://creds:creds@hostname/h265Preview_01_sub#video=h264#audio=copy#hardware"
```

![image](https://github.com/user-attachments/assets/8cddf79b-0a24-46bf-bff3-d539feff60b7)
