### DISCUSSION TITLE
[Detector Support]: /etc/s6-overlay/s6-rc.d/trt-model-prepare/run: line 23: [: missing `]'

### DISCUSSION THREAD

**Discussion by venssy** [blakeblackshear/frigate#16905] [Detector Support]
### Describe the problem you are having

frigate throws exception 

> /etc/s6-overlay/s6-rc.d/trt-model-prepare/run: line 23: [: missing `]'

### Version

unknown(ghcr.io/blakeblackshear/frigate:stable-tensorrt)

### Frigate config file

```yaml
mqtt:
  enabled: False

record:
  enabled: True
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 10
    pre_capture: 1
    post_capture: 3
  detections:
    retain:
      days: 10
    pre_capture: 1
    post_capture: 3

snapshots:
  enabled: True
  retain:
    default: 30

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

objects:
  track:
    - person


cameras:
  lounge_camera:
    onvif:
      host: 192.168.0.90
      port: 2020
      user: xxxx
      password: xxxxx

    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxxx@192.168.0.90:554/stream1&channel=1
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
      hwaccel_args: preset-nvidia-h265
    detect:
      width: 1920
      height: 1080
      fps: 3
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"

services:
  frigate:
    environment: 
      - YOLO_MODELS=yolov7-320
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    shm_size: "512mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/frigate/config:/config
      - /config/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "18971:8971"
      - "15555:5000"
      - "18554:8554"
      - "18555:8555/tcp"
      - "18555:8555/udp"
```

### Relevant Frigate log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
/etc/s6-overlay/s6-rc.d/trt-model-prepare/run: line 23: [: missing `]'
Generating the following TRT Models: yolov7-320
Downloading yolo weights
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2025-03-03 14:59:32.439498790  [INFO] Preparing new go2rtc config...
2025-03-03 14:59:33.179818720  [INFO] Starting go2rtc...
2025-03-03 14:59:33.300448089  14:59:33.300 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-03-03 14:59:33.300452908  14:59:33.300 INF config path=/dev/shm/go2rtc.yaml
2025-03-03 14:59:33.301006767  14:59:33.300 INF [rtsp] listen addr=:8554
2025-03-03 14:59:33.301042187  14:59:33.300 INF [api] listen addr=:1984
2025-03-03 14:59:33.301198961  14:59:33.301 INF [webrtc] listen addr=:8555/tcp
2025-03-03 14:59:42.440879544  [INFO] Starting go2rtc healthcheck service...
s6-rc: warning: unable to start service trt-model-prepare: command exited 6
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

N/A
