### DISCUSSION TITLE
[Support]: dockerd file descriptors utilization leaving frigate in non-functional state

### DISCUSSION THREAD

**Discussion by InstantCassette** [blakeblackshear/frigate#16923] [General Support]
### Describe the problem you are having

(Running in a docker container on Unraid 7)

Almost daily I get a warning from my Netdata container stating that `Raised to Warning, App group dockerd file descriptors utilization = 95.04 %`. Usually about an hour later I get anoter notification stating: `Recovered, App group dockerd file descriptors utilization = 0.29 %`. (Details: Open files percentage against the processes limits, among all PIDs in application group)

During that time my Frigate container will cease to receive any footage from my cameras and I'm forced to restart it to restore frigate functionality, otherwise it will remain in a state where no camera is being received.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Google Chrome 133.0.6943.142

### Frigate config file

```yaml
version: 0.15-1
#https://docs.frigate.video/configuration/

# UI SETTINGS
camera_groups:
  Home:
    order: 2
    icon: LuHome
    cameras:
      - Frigate0
      - Frigate1
      - Frigate2
      - Frigate3
      - Frigate4
      - Frigate5

  Front:
    order: 2
    icon: LuShieldCheck
    cameras: Frigate0
birdseye:
  enabled: false

# SERVICES
mqtt:
  host: nexus.jupiter
  port: 1883
  user: XXX
  password: XXX
  topic_prefix: frigate
  client_id: frigate

# GLOBAL DETECTION SETTINGS
detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog
    - bicycle
    - motorcycle
    - car
    - bus

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

review:
  alerts:
    labels:
      - person
      - cat
      - dog

# GLOBAL RECORDING SETTINGS
ffmpeg:
  hwaccel_args: preset-vaapi
  # RESTREAMING
  input_args: preset-rtsp-restream #preset-rtsp-restream #preset-rtsp-restream-low-latency #preset-rtsp-generic
  # RECORDING
  output_args:
    record: preset-record-generic-audio-copy #preset-record-generic-audio-aac #preset-record-generic-audio-copy #preset-record-generic
    #record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    #rtmp: preset-rtmp-generic #Deprecated in favour of go2rtc.

record:
  enabled: true
  retain:
    days: 2
    mode: all
  expire_interval: 240
  sync_recordings: true

snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  clean_copy: true
  retain:
    default: 7

# WEBRTC Settings
# Setup reusable restreams so only a single connection is active to the cameras.
# This will also resolve any codec issues when the cameras use formats unsupported by browsers.
# RTSP == UDP, complex, H265 compatibility, multiple connections, mediocre realiability.
# RTMP == TCP, simple, H264 compatibility, single connection, best realiability.
go2rtc:
  webrtc:
    candidates:
      - nexus.jupiter:8555

  #log:
  #  exec: trace

  streams:

    #Reolink Video Doorbell WiFi (95270006Q2UG1B4X) 10.0.100.10
    Camera0_SD:
      #H254 640x480 15FPS 512Kbps
      #RTSP
      #- "rtsp://XXX:XXX@10.0.100.10:554/h264Preview_01_sub"
      #- "ffmpeg:Camera0_SD#video=copy#audio=opus#async"
      #RTMP/HTTP
      - ffmpeg:https://10.0.100.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX#video=copy#audio=opus#async
    Camera0_HD:
      #H265 2560x1920 20FPS 6144Kbps
      #RTSP
      #- "rtsp://XXX:XXX@10.0.100.10:554/h265Preview_01_main"
      #- "ffmpeg:Camera0_HD#video=h264#audio=opus#async"
      #RTMP/HTTP
      - ffmpeg:https://10.0.100.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=opus#async

    #Reolink E1 Zoom (95270005Z9JDLW1Z) 10.0.100.20
    Camera1_SD:
      #H264 640x480 15FPS 512Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.20:554/h264Preview_01_sub
      - ffmpeg:Camera1_SD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"
    Camera1_HD:
      #H264 2560x1920 20FPS 4096Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.20:554/h264Preview_01_main
      - ffmpeg:Camera1_HD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"

    #Reolink E1 Zoom (95270005ZSA514D9) 10.0.100.21
    Camera2_SD:
      #640x480 15FPS 512Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.21:554/h264Preview_01_sub
      - ffmpeg:Camera2_SD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"
    Camera2_HD:
      #H264 2560x1920 20FPS 4096Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.21:554/h264Preview_01_main
      - ffmpeg:Camera2_HD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"

    #Reolink E1 Zoom (95270005ZS2CDYXQ) 10.0.100.22
    Camera3_SD:
      #H264 640x480 15FPS 512Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.22:554/h264Preview_01_sub
      - ffmpeg:Camera3_SD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"
    Camera3_HD:
      #H264 2560x1920 20FPS 4096Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.22:554/h264Preview_01_main
      - ffmpeg:Camera3_HD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"

    #Reolink E1 Zoom (95270005ZRZU1JGA) 10.0.100.23
    Camera4_SD:
      #H264 640x480 15FPS 512Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.23:554/h264Preview_01_sub
      - ffmpeg:Camera4_SD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.23/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"
    Camera4_HD:
      #H264 2560x1920 20FPS 4096Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.23:554/h264Preview_01_main
      - ffmpeg:Camera4_HD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.23/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"

      #Reolink E1 Outdoor CX (952700080HGM1WX7) 10.0.100.24
    Camera5_SD:
      #H264 640x360 15FPS 512Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.24:554/h264Preview_01_sub
      - ffmpeg:Camera5_SD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"
    Camera5_HD:
      #H264 2560x1440 25FPS 4096Kbps
      #RTSP
      - rtsp://XXX:XXX@10.0.100.24:554/h264Preview_01_main
      - ffmpeg:Camera5_HD#video=copy#audio=opus#async
      #RTMP/HTTP
      #- "ffmpeg:https://10.0.100.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXX&password=XXX#video=copy#audio=opus#async"
      #Reolink E1 Outdoor CX (952700080HGM1WX7) 10.0.100.24

    Camera20:
      #H264 1920x1080
      #RTSP
      - rtsp://XXX:XXX@10.0.0.210/ch0_0.h264
      - ffmpeg:Camera20#video=copy#async
    Camera21:
      #H264 1920x1080
      #RTSP
      - rtsp://XXX:XXX@10.0.0.211/ch0_0.h264
      - ffmpeg:Camera21#video=copy#async
    Camera22:
      #H264 1920x1080
      #RTSP
      - rtsp://XXX:XXX@10.0.0.212/ch0_0.h264
      - ffmpeg:Camera22#video=copy#async
    Camera23:
      #H264 1920x1080
      #RTSP
      - rtsp://XXX:XXX@10.0.0.213/ch0_0.h264
      - ffmpeg:Camera23#video=copy#async

# FRIGATE Settings
# The frigate plugin for Home Assistant will only expose the detect stream at very low framerate.
# You're better off linking the webrtc streams via the control panel for viewing the live stream. (http://nexus.jupiter:5000/live/webrtc/)
cameras:
  #FRIGATE0
  Frigate0:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera0_SD?video&audio
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera0_HD?video&audio
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: Camera0_HD
    motion:
      mask: 0.259,0,0.734,0,0.732,0.065,0.259,0.065
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Street:
        coordinates: 0,0.38,1,0.383,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: Street
      detections:
        required_zones: Street
    objects:
      mask:
        - 0,0.456,0.145,0.494,0.134,0.555,0,0.513
        - 0.925,0.502,1,0.513,1,0.559,0.926,0.536

  #FRIGATE1
  Frigate1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera1_SD?video&audio
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera1_HD?video&audio
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: Camera1_HD
    motion:
      mask: 0.32,0,0.664,0,0.663,0.091,0.321,0.093
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Inside:
        coordinates: 0,0.228,1,0.22,1,1,0,1
        loitering_time: 0

  #FRIGATE2
    review:
      alerts:
        required_zones: Inside
      detections:
        required_zones: Inside
  Frigate2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera2_SD?video&audio
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera2_HD?video&audio
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: Camera2_HD
    motion:
      mask: 0.32,0,0.661,0,0.661,0.085,0.321,0.088
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Inside:
        coordinates: 0,0.136,1,0.126,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: Inside
      detections:
        required_zones: Inside

  #FRIGATE3
  Frigate3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera3_SD?video&audio
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera3_HD?video&audio
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: Camera3_HD
    motion:
      mask: 0.316,0,0.662,0,0.663,0.084,0.317,0.086
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Inside:
        coordinates: 0,0.114,1,0.112,1,1,0,1
        loitering_time: 0

  #FRIGATE4
    review:
      alerts:
        required_zones: Inside
      detections:
        required_zones: Inside
  Frigate4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera4_SD?video&audio
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera4_HD?video&audio
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: Camera4_HD
    motion:
      mask: 0.316,0,0.664,0,0.664,0.086,0.316,0.085
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Inside:
        coordinates: 0,0.098,1,0.094,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: Inside
      detections:
        required_zones: Inside

  #FRIGATE5
  Frigate5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera5_SD?video&audio
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera5_HD?video&audio
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    live:
      stream_name: Camera5_HD
    motion:
      mask: 0.326,0,0.325,0.095,0.664,0.097,0.663,0
      threshold: 50
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Garden:
        coordinates: 0.443,0.325,0.87,0.326,0.873,0.963,0.45,0.963
        loitering_time: 0
    review:
      alerts:
        required_zones: Garden
      detections:
        required_zones: Garden

  #FRIGATE20
  Frigate20:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera20?video
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera20?video
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    record:
      enabled: false
    snapshots:
      enabled: true
    live:
      stream_name: Camera20

  #FRIGATE21
  Frigate21:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera21?video
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera21?video
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    record:
      enabled: false
    snapshots:
      enabled: true
    live:
      stream_name: Camera21

  #FRIGATE22
  Frigate22:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera22?video
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera22?video
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    record:
      enabled: false
    snapshots:
      enabled: true
    live:
      stream_name: Camera22

  #FRIGATE23
  Frigate23:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://nexus.jupiter:8554/Camera23?video
          roles:
            - detect
            - audio
        - path: rtsp://nexus.jupiter:8554/Camera23?video
          roles:
            - record
    #ROLE SETTINGS
    detect:
      enabled: false
      width: 640
      height: 360
      fps: 5
    record:
      enabled: false
    snapshots:
      enabled: true
    live:
      stream_name: Camera23
```

### Relevant Frigate log output

```shell
/
```

### Relevant go2rtc log output

```shell
/
```

### FFprobe output from your camera

```shell
/
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='Frigate'
  --net='bridge'
  --cpuset-cpus='0,1,2,6,7,8'
  --pids-limit 2048
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="NEXUS"
  -e HOST_CONTAINERNAME="Frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='XXX'
  -e 'LIBVA_DRIVER_NAME'='radeonsi'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8971]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '8554:8554/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -p '1984:1984/tcp'
  -p '8971:8971/tcp'
  -p '5000:5000/tcp'
  -v '/mnt/user/System/Appdata/frigate':'/config':'rw'
  -v '/mnt/user/Recordings':'/media/frigate':'rw'
  -v '/mnt/user/System/Appdata/frigate/logs':'/dev/shm/logs':'rw'
  -v '/mnt/user/System/Appdata/frigate/docker':'/var/log/':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/dri/renderD128'
  --device='/dev/bus/usb'
  --memory=8g
  --kernel-memory=8g
  --shm-size=2g
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=200000000
  --log-opt max-size=10m
  --log-opt max-file=100
  --memory-swap=-1
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable'
e2b9262fc0379460f8e7304b63b615272890f7e6d429f0f47c7797df3d9e7d8d
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink, Yi Camera
