### DISCUSSION TITLE
[Support]: How do I use the Network Storage in HA which is mapped to a TrueNAS NFS share to store my Frigate clips and recordings

### DISCUSSION THREAD

**Discussion by rdperkins** [blakeblackshear/frigate#16930] [General Support]
### Describe the problem you are having

Frigate is working well but is filling up my local storage. I'm running HAOS on a Proxmox VM. The Frigate add-on in HA is storing clips and recordings to /media/frigate/clips, etc. That sits on the Proxmox server. How do i change to force storage on the NFS share instead.

### Version

HAOS 13.1; Frigate add-on 0.15.0; TrueNAS Scale Dragonfish-24.04.2.5

### What browser(s) are you using?

MS Edge Version 133.0.3065.92 (Official build) (64-bit)

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.XXX #Insert the IP address of your Home Assistant
  port: 1883 #Leave as default 1883 or change to match the port set in your MQTT Broker configuration
  topic_prefix: frigate
  client_id: frigate
  user: XXXXXX #Change to match the username set in your MQTT Broker
  password: XXSXX
  stats_interval: 60

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  retry_interval: 10

logger:
  default: error
  logs:
    frigate: error
    frigate.ffmpeg: error

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 7
      mode: motion
  detections:
    retain:
      days: 7
      mode: motion

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 10

detectors: # Moved to top level
  coral: # Moved to top level
    type: edgetpu

database:
  path: /config/frigate.db

cameras:
  back_porch: # Change this to a name of the camera that makes sense to you
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac # Insert this if your camera supports audio output
      inputs:
        - path: rtsp://admin:XXXXX@192.168.1.XXX:554/h265Preview_01_main
          roles:
            - record
        - path: rtsp://admin:XXXXX@192.168.1.XXX:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      height: 512
      width: 896
      fps: 7
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - rabbit
        - deer
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-1224A
