### DISCUSSION TITLE
[Bug]: Debug logging doesn't work in some modules

### DISCUSSION THREAD

**Discussion by leccelecce** [blakeblackshear/frigate#16933] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Despite the below config, I never see any log messages below WARN from frigate.embeddings.maintainer.

```
logger:
  default: info
  logs:
    frigate.embeddings.maintainer: debug
```

I'm guessing this is because the logger is going to https://docs.python.org/3.11/library/logging.html#logging.lastResort

logging seems to work in the init() method, as all three of these statements print:

```
EmbeddingMaintainer.__init__()
...
logger.debug("init: test debug logging")
logger.info("init: test info logging")
logger.warning("init: test warn logging")
```

However logging in any method outside `__init__`  doesn't work e.g. `run()`.

Adding the below to the top of `EmbeddingMaintainer.run()` fixes it:

```
logger.addHandler(QueueHandler(frigate.log.log_listener.queue))

logger.debug("run: test debug logging")
logger.info("run: test info logging")
logger.warning("run: test warn logging")
```

...confirming the problem is that the log handler is somehow not being used.

I know maintainers cannot reproduce this but it's 100% consistent for me. I will have a dig through Python logging docs when I have more time and I know there were a number of previous discussions on this, but wanted to capture what I'd found so far (albeit it might have already been known).

### Steps to reproduce

See above

### Version

0.16 dev 

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.embeddings.maintainer: debug
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

n/a

**Comment by leccelecce** [comment]
Code has been moved around before: https://github.com/blakeblackshear/frigate/pull/14079
Further discussion: https://github.com/blakeblackshear/frigate/pull/13785

**Comment by leccelecce** [comment]
OK, I'm pretty much totally insane now. I can't get this to reproduce 100% reliably as stated above. When I try stepping through the various bits of app startup / config / logging code, sometimes it gets through the validation of the LogConfig, but post-validation the "logger" entry is None.

It feels like there must be a race condition somewhere.

**Reply by leccelecce** [reply]
@gtsiam as the contributor of the log code - would welcome any thoughts if you have the time!

**Reply by gtsiam** [reply]
I do recall logging being rather fragile. Give me a moment to look at any changes since I touched that code.

**Reply by hawkeye217** [reply]
In trying to fix this issue, I reverted logging to a process from before the changes and still had the problem. So I don't think it's specific to the changes from @gtsiam

**Comment by hawkeye217** [comment]
Are you using Ollama for your GenAI provider?

**Reply by leccelecce** [reply]
Yes. Though removing all the genai config and just setting `enabled: false` doesn't seem to change anything.

**Reply by leccelecce** [reply]
I'm also mainly trying to debug in frigate.embeddings.maintainer so to be more accurate, not actually in the GenAI modules

**Reply by hawkeye217** [reply]
I've noticed that any debug logs printing from other modules that the embedding maintainer runs in init (model downloads, for example) as well as any genai provider logs will do something odd with python's logging QueueHandler and prevent any logs from printing in the run method. If I disable genai and ensure the "model is already downloaded" debug logs are not printed, everything works fine. 

Seems python related to me.

**Reply by gtsiam** [reply]
There's a lot of weirdness with the fork start method which is why I was trying to ditch it. I took a break from frigate cause life, but I should probably finish that work sooner rather than later.

Gonna need to experiment some more here.

**Reply by hawkeye217** [reply]
Another interesting note is that other processes like the recordings maintainer don't seem to exhibit the logging issue like the embeddings maintainer.

**Reply by leccelecce** [reply]
https://github.com/python/cpython/issues/84559
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

Frigate is on Python 3.11. Sounds like some major changes coming between 3.12 and 3.14 to how fork works...

**Reply by gtsiam** [reply]
Yes, that's why I was trying to move away from it (probably forkserver).

~~PS: Building the devcontainers takes an ungodly amount of time~~

**Reply by leccelecce** [reply]
I can reproduce this not working 9 times out of 10.

I've tried watching the QueueHandler / QueueListener buffer but can't figure out what's going on; I'm not knowledgeable on the Python debugger to understand what are side-effects of me pausing the multi-threaded setup. Sometimes I can see my log messages building up in the log buffer, so they're making it that far, but then I never seem to see them getting popped - they just vanish.

If anyone would like to guide me on debug steps happy to dump what state I can.

**Reply by gtsiam** [reply]
Can't really guide you through this, there's just too many things that could have gone wrong. I'm building the devcontainer right now, hopefully I can reproduce it.

I would like to know the exact reproduction steps though. Say I'm starting with nothing. What are you doing to reproduce this? Give me steps like I'm 5

**Reply by leccelecce** [reply]
I'm running Frigate's latest 0.16 dev build (though this has been present for me as far back as November in 0.14)
Running latest Docker in a Debian Bookworm VM
Latest VS Code, connecting to the Devcontainer in the VM via SSH
VSCode: `Rebuild Container`
VSCode: F5 to debug

At the bottom of frigate.embeddings.maintainer __init__, I've added:

```
        logger.debug("init: test debug logging")
        logger.info("init: test info logging")
        logger.warning("init: test warn logging")
```

Immediately below in run() I've added:

```
        logger.debug("run: test debug logging")
        logger.info("run: test info logging")
        logger.warning("run: test warn logging")
```

The log prints in run() only seem to work 10% of the time I debug.

Just discovered that if I run `python3 -m frigate` from the VS Code terminal, they seem to reliably always print. But that's not helpful as it doesn't work in my production environment.

Minimal Frigate config:

```
version: 0.16-0

logger:
  default: info
  logs:
    frigate.genai: debug
    frigate.embeddings: debug
    frigate.embeddings.maintainer: debug

mqtt:
  host: mqtt

semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: false

snapshots:
  enabled: true

record:
  enabled: true
  retain:
    days: 1
    mode: active_objects

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.4
      threshold: 0.50

cameras:
  hikcam9:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxx
          roles:
            - detect
            - record
    detect:
      height: 1080
      width: 1920
      fps: 5


```
