### DISCUSSION TITLE
[Support]:  Stationary objects redundant notifications

### DISCUSSION THREAD

**Discussion by leonbrag** [blakeblackshear/frigate#16942] [General Support] [answered]
### Describe the problem you are having

**Before I start, v.15 has this issue MUCH better and MUCH better debugging tools for it! Thank you.**

I have garage with glass doors and window. So lighting condition change (when passing car shine light). This triggers redundant notifications as attached. I don't think I can tune motion any better.  Car is not moving of course.

Below is just a single representative sample. 

![2025-03-04_07h20_24](https://github.com/user-attachments/assets/1a254653-034b-4ffe-9faa-ab82d9e1313b)
![2025-03-04_07h20_30](https://github.com/user-attachments/assets/19f2aa60-f1f7-42d6-a568-1e7d698b6b66)
![2025-03-04_07h20_40](https://github.com/user-attachments/assets/80016da5-18c2-48e0-8148-0a73a8a3e897)
![2025-03-04_07h20_51](https://github.com/user-attachments/assets/28a36b93-a9cc-4f6d-82f1-0b7fc59c8924)

Is there a way to control it?

Above is only one representative sample. There are a few more instances like this

### Version

.15

### Frigate config file

```yaml
Garage: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.10.17/Streaming/Channels/101
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://x:x@192.168.10.17/Streaming/Channels/101
          roles:
            - record
    motion:
      mask: 0.043,0.053,0.367,0.056,0.37,0.093,0.043,0.096
      threshold: 40
      contour_area: 19
      improve_contrast: true
    review:
      alerts:
        required_zones: zoneGarage
      detections: {}
    zones:
      zoneGarage:
        coordinates: 
          0.004,0.138,0.253,0.145,0.297,0.168,0.365,0.138,0.492,0.203,0.561,0.232,0.622,0.228,0.986,0.646,0.991,0.982,0.003,1
        inertia: 3
        loitering_time: 0
```

### Relevant Frigate log output

```shell
na
```

### Relevant go2rtc log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
na
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Hik
