### DISCUSSION TITLE
[Support]: Sync recordings after deletion not working

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#16948] [General Support]
### Describe the problem you are having

So I needed to completely wipe my SSD where all my Frigate stuff is stored (long story) and it was successful. The terminal is showing the SSD as 100% empty. I added the "sync_recording" lines to my config and rebooted.

In the UI, all my clips and recordings are unavailable (they won't load) so it seems like it worked. But there's still the yellow lines in the history for each camera and my metrics page still shows the storage at it's typical level (see below).

![Capture2](https://github.com/user-attachments/assets/f870c31a-a100-4742-8322-152b743172d1)

![Capture1](https://github.com/user-attachments/assets/57d15736-f323-40a6-99d9-d5e826f5b6fc)

I did this all about 45 mins ago so not sure if there's just a lag time for the history/metrics to update or if I did something wrong? Any thoughts? 

### Version

0.15.0-e76f4e9

### Frigate config file

```yaml
mqtt:
  host: 192.168.107.2
  port: 1883
  user: [username]
  password: [password]
  topic_prefix: frigate

go2rtc:
  streams:
    Driveway:
      - rtsp://admin:guns1721@192.168.207.2:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:guns1721@192.168.207.2:554/cam/realmonitor?channel=1&subtype=1
    FrontPorch:
      - rtsp://admin:guns1721@192.168.207.3:554/cam/realmonitor?channel=1&subtype=0
    FrontPorch_sub:
      - rtsp://admin:guns1721@192.168.207.3:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.107.3:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3
        mode: active_objects
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 7
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    objects:
      track:
        - person
        - dog
        - cat
        - bear
      filters:
        person:
          min_score: 0.7
        dog:
          min_score: 0.7
        cat:
          min_score: 0.7
        bear:
          min_score: 0.7
  Driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3
        mode: active_objects    
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 7
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.7
      mask:
        - 0.192,0.595,0.795,0.662,1,1,0.001,0.996,0.004,0.703
        - 0.982,0.732,0.904,0.703,0.636,0.361,0.786,0.312,0.858,0.316,0.935,0.336,0.99,0.44,0.999,0.512
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

n/a
