### DISCUSSION TITLE
[Support]: MQTT connection to HA seems to have just "stopped"

### DISCUSSION THREAD

**Discussion by calum-mcfarlane** [blakeblackshear/frigate#16941] [General Support]
### Describe the problem you are having

I no longer get HA notifications about events on my phone, which has been working reliably for months. I haven't made any configuration changes that might have caused this. 

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox 135.0.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: home-assistant.<REDACTED DOMAIN>
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

# Uncomment the two  rows below to reset the password
#auth:
#  reset_admin_password: true

ffmpeg:
  hwaccel_args: preset-vaapi


record:
  enabled: true
  retain:
    days: 20
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

snapshots:
  enabled: true
  bounding_box: true
  crop: true
  retain:
    default: 360

go2rtc:
  streams:
    ################################################### IPC-Color4M-T #####################################################
#    front_door:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.13:554/cam/realmonitor?channel=1&subtype=0#timeout=10      # Main stream
#    front_door_sub:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.13:554/cam/realmonitor?channel=1&subtype=2#timeout=10      # Sub stream

    ################################################### IPC-Color4M-T #####################################################
#    side_gate:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.14:554/cam/realmonitor?channel=1&subtype=0#timeout=10      # Main stream
#    side_gate_sub:
#      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.14:554/cam/realmonitor?channel=1&subtype=2#timeout=10      # Sub stream  

    ################################################### IPC-T54IR-AS-S3 ###################################################
    garage_front:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.11:554/cam/realmonitor?channel=1&subtype=0#timeout=10      # Main stream
    garage_front_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.11:554/cam/realmonitor?channel=1&subtype=3#timeout=10      # Sub stream

    ################################################### IPC-T2X5M-IL #1 ################################################### 
    garage_side:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.10:554/cam/realmonitor?channel=1&subtype=0#timeout=10      # Main stream
    #  - "ffmpeg:garage-side#audio=aac" # Only needed if using IPC-T2X5M-IL with go2rtc - set audio to "PCM" on the camera's web interface
    garage_side_sub:
      - ffmpeg:garage_side#video=h264#width=1280#height=720#raw=-fpsmax 8#hardware=vaapi#timeout=10    # Define substream as a resized version of main stream
    ################################################### PTZ3E405-AI ######################################################## 
    back_garden:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.12:554/cam/realmonitor?channel=1&subtype=0#timeout=10     # Main stream
    back_garden_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.12:554/cam/realmonitor?channel=1&subtype=2#timeout=10     # Sub stream

cameras:
#  front_door:
#    ffmpeg:
#      output_args:
#        record: preset-record-generic-audio-copy
#      inputs:
#        - path: rtsp://127.0.0.1:8554/front_door # <--- the name here must match the name of the camera in restream
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#        - path: rtsp://127.0.0.1:8554/front_door_sub # <--- the name here must match the name of the camera_sub in restream
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#    detect:
#      enabled: true
#      fps: 8
#      width: 1280
#      height: 720

#  side_gate:
#    ffmpeg:
#      output_args:
#        record: preset-record-generic-audio-copy
#      inputs:
#        - path: rtsp://127.0.0.1:8554/side_gate # <--- the name here must match the name of the camera in restream
#          input_args: preset-rtsp-restream
#          roles:
#            - record
#        - path: rtsp://127.0.0.1:8554/side_gate_sub # <--- the name here must match the name of the camera_sub in restream
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
#    detect:
#      enabled: false
#      fps: 8
#      width: 1280
#      height: 720    

  garage_side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_side # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_side_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 8
      width: 1280
      height: 720


    zones:
      Inside_fence:
        coordinates: 
          0.077,0.692,0.001,0.667,0,1,1,1,1,0,0.802,0.002,0.666,0.086,0.514,0.215,0.368,0.347,0.244,0.494
        inertia: 1
        loitering_time: 0
      Brook_Lane:
        coordinates: 0,0,0,0.66,0.073,0.689,0.285,0.44,0.371,0.341,0.552,0.183,0.799,0
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.681,0.04,0.958,0.034,0.96,0.086,0.681,0.087
      threshold: 56
      contour_area: 31
      improve_contrast: 'true'
    review:
      alerts:
        required_zones: Inside_fence
      detections:
        required_zones: Brook_Lane

  garage_front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_front # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_front_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 8






    motion:
      threshold: 50
      contour_area: 28
      improve_contrast: 'true'
      mask: 
        0.998,0.295,0.798,0.191,0.608,0.127,0.608,0.079,0.612,0.044,0.547,0.045,0.514,0.05,0.479,0.051,0.193,0.038,0.193,0,1,0
    zones:
      Driveway:
        coordinates: 
          0.194,0.081,0.191,0,0.127,0,0.078,0.074,0,0.179,0,0.654,0.074,0.874,0.094,0.91,0.136,0.999,0.68,1,0.748,0.666,0.78,0.389,0.781,0.352,0.724,0.274,0.684,0.241,0.643,0.217,0.613,0.207,0.606,0.124,0.601,0.084,0.444,0.072,0.375,0.077,0.291,0.089
        loitering_time: 0
        inertia: 3
      Brook_Lane:
        coordinates: 
          0.783,0.342,0.729,0.275,0.666,0.227,0.615,0.204,0.61,0.134,0.797,0.188,0.998,0.297,1,1,0.684,0.998,0.722,0.816,0.759,0.589,0.785,0.397
        loitering_time: 0
    review:
      alerts:
        required_zones: Driveway
  back_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy

      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_garden_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.3.12
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'

    detect:
      enabled: true
      fps: 8
      width: 1280
      height: 720

    motion:
      mask: 0.685,0.033,0.962,0.034,0.962,0.086,0.684,0.088
      threshold: 42
      contour_area: 18
      improve_contrast: 'true'
    objects:
      filters:
        person:
          mask: 
            0.255,0.208,0.497,0.299,0.462,0.549,0.341,0.85,0.226,0.932,0.185,0.701,0.007,0.63,0,0.342
    zones:
      Patio:
        coordinates: 
          0.284,0.993,0.834,0.993,0.913,0.708,0.92,0.661,0.902,0.637,0.824,0.575,0.821,0.543,0.836,0.506,0.869,0.252,0.741,0.166,0.602,0.236
        loitering_time: 0
      Lawn:
        coordinates: 
          0.726,0.16,0.558,0.112,0.514,0.123,0.474,0.124,0.426,0.126,0.376,0.152,0.18,0.276,0.048,0.382,0.032,0.399,0.042,0.424,0.045,0.474,0.038,0.535,0.001,0.997,0.279,0.998,0.598,0.238
        loitering_time: 0
    review:
      alerts:
        required_zones: Patio
detectors:
  coral:
    type: edgetpu
    device: pci


camera_groups:
  Front:
    order: 2
    icon: LuDoorClosed
    cameras:
      - garage_front
      - garage_side
      - front_door
  Garden:
    order: 3
    icon: LuTrees
    cameras: back_garden


version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: large
notifications:
  enabled: 'true'
  email: <redacted>
```

### Relevant Frigate log output

```shell
This is the weird part - while troubleshooting I have changed my frigate.env file so that {FRIGATE_MQTT_PASSWORD} is an incorrect value, however the log doesn't show any error that Frigate was unable to connect. I have enabled the in-browser notifications and they work as expected. 

2025-03-04 14:20:11.585896445  [INFO] Preparing Frigate...
2025-03-04 14:20:11.683065004  [INFO] Starting Frigate...
2025-03-04 14:20:13.664005221  [2025-03-04 14:20:13] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-03-04 14:20:13.693376757  [2025-03-04 14:20:13] frigate.util.config            INFO    : frigate config does not need migration...
2025-03-04 14:20:17.366552168  [2025-03-04 14:20:17] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
2025-03-04 14:20:17.376844627  [2025-03-04 14:20:17] peewee_migrate.logs            INFO    : Starting migrations
2025-03-04 14:20:17.377112314  [2025-03-04 14:20:17] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-03-04 14:20:17.668016282  [2025-03-04 14:20:17] frigate.app                    INFO    : Recording process started: 359
2025-03-04 14:20:17.668019834  [2025-03-04 14:20:17] frigate.app                    INFO    : Review process started: 361
2025-03-04 14:20:17.670208749  [2025-03-04 14:20:17] frigate.app                    INFO    : go2rtc process pid: 97
2025-03-04 14:20:17.681005733  [2025-03-04 14:20:17] detector.coral                 INFO    : Starting detection process: 375
2025-03-04 14:20:17.688670433  [2025-03-04 14:20:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2025-03-04 14:20:17.688695338  [2025-03-04 14:20:17] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-03-04 14:20:17.700528660  [2025-03-04 14:20:17] frigate.app                    INFO    : Output process started: 404
2025-03-04 14:20:17.751686281  [2025-03-04 14:20:17] frigate.app                    INFO    : Camera processor started for garage_side: 419
2025-03-04 14:20:17.751967680  [2025-03-04 14:20:17] frigate.app                    INFO    : Camera processor started for garage_front: 427
2025-03-04 14:20:17.752026934  [2025-03-04 14:20:17] frigate.app                    INFO    : Camera processor started for back_garden: 429
2025-03-04 14:20:17.752028938  [2025-03-04 14:20:17] frigate.app                    INFO    : Capture process started for garage_side: 454
2025-03-04 14:20:17.774241930  [2025-03-04 14:20:17] frigate.app                    INFO    : Capture process started for garage_front: 470
2025-03-04 14:20:17.791992429  [2025-03-04 14:20:17] frigate.app                    INFO    : Capture process started for back_garden: 475
2025-03-04 14:20:17.862404535  [2025-03-04 14:20:17] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-03-04 14:20:17.981405361  [2025-03-04 14:20:17] frigate.api.fastapi_app        INFO    : FastAPI started
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
cameras	
garage_side	
camera_fps	8.1
process_fps	8.1
skipped_fps	0
detection_fps	0
detection_enabled	true
pid	419
capture_pid	454
ffmpeg_pid	459
audio_rms	0
audio_dBFS	0
garage_front	
camera_fps	8.1
process_fps	8.1
skipped_fps	0
detection_fps	0
detection_enabled	true
pid	427
capture_pid	470
ffmpeg_pid	476
audio_rms	0
audio_dBFS	0
back_garden	
camera_fps	8.1
process_fps	8.1
skipped_fps	0
detection_fps	0
detection_enabled	true
pid	429
capture_pid	475
ffmpeg_pid	489
audio_rms	0
audio_dBFS	0
detectors	
coral	
inference_speed	6.49
detection_start	0
pid	375
detection_fps	0
gpu_usages	
intel-vaapi	
gpu	"4.32%"
mem	"-%"
clients	
459	"2.07%"
469	"26.8%"
476	"1.52%"
489	"2.04%"
cpu_usages	
1	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
15	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise s6-linux-init-shutdownd"
17	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
24	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise certsync-log"
25	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise nginx"
26	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise go2rtc-healthcheck"
27	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise certsync"
28	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise go2rtc-log"
29	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise frigate"
30	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise s6rc-fdholder"
31	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise nginx-log"
32	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise frigate-log"
33	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise s6rc-oneshot-runner"
34	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-supervise go2rtc"
45	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
46	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
84	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
88	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
89	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
90	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
97	
cpu	"3.0"
cpu_average	"2"
mem	"0.0"
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
112	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"bash ./run.user go2rtc-healthcheck"
121	
cpu	"1.5"
cpu_average	"1"
mem	"0.5"
cmdline	"python3 -u -m frigate"
129	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: master process nginx"
161	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: worker process"
162	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: worker process"
163	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: worker process"
164	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: worker process"
165	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"nginx: cache manager process"
314	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"bash ./run.user certsync"
359	
cpu	"1.3"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.recording_manager"
361	
cpu	"0.4"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.review_segment_manager"
375	
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.detector.coral"
404	
cpu	"0.8"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.output       "
418	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
419	
cpu	"1.1"
cpu_average	"1"
mem	"0.2"
cmdline	"frigate.process:garage_side"
427	
cpu	"1.0"
cpu_average	"1"
mem	"0.2"
cmdline	"frigate.process:garage_front"
428	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
429	
cpu	"1.1"
cpu_average	"1"
mem	"0.2"
cmdline	"frigate.process:back_garden"
454	
cpu	"1.0"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.capture:garage_side"
459	
cpu	"2.1"
cpu_average	"2"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_side_sub -r 8 -vf fps=8,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
460	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
469	
cpu	"1.2"
cpu_average	"1"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/garage_side?video -fpsmax 8 -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf format=vaapi|nv12,hwupload,scale_vaapi=1280:720:out_color_matrix=bt709:out_range=tv:format=nv12 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/c3b82e10077139cf648a942cdf337859"
470	
cpu	"1.0"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.capture:garage_front"
471	
cpu	"0.4"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage_side@%Y%m%d%H%M%S%z.mp4"
472	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
475	
cpu	"1.0"
cpu_average	"0"
mem	"0.2"
cmdline	"frigate.capture:back_garden"
476	
cpu	"1.8"
cpu_average	"1"
mem	"0.1"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_front_sub -r 8 -vf fps=8,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
489	
cpu	"1.9"
cpu_average	"1"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_garden_sub -r 8 -vf fps=8,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
495	
cpu	"0.4"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage_front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garage_front@%Y%m%d%H%M%S%z.mp4"
496	
cpu	"0.4"
cpu_average	"0"
mem	"0.0"
cmdline	"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/back_garden@%Y%m%d%H%M%S%z.mp4"
6071	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"sleep 60"
6097	
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
cmdline	"sleep 30s"
frigate.full_system	
cpu	"6.6"
mem	"59.1"
service	
uptime	1706
version	"0.15.0-cea210d"
latest_version	"0.15.0"
storage	
/media/frigate/recordings	
total	3611297.4
used	1077148
free	2350632.6
mount_type	"ext4"
/media/frigate/clips	
total	3611297.4
used	1077148
free	2350632.6
mount_type	"ext4"
/tmp/cache	
total	2048
used	9.5
free	2038.5
mount_type	"tmpfs"
/dev/shm	
total	200
used	124.6
free	75.4
mount_type	"tmpfs"
temperatures	
apex_0	43.55
last_updated	1741099723
processes	
recording	
pid	359
review_segment	
pid	361
go2rtc	
pid	97
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
NB I'm running Docker in a Debian container, so that it can make use of the iGPU for transcoding but other containers can also use it.

services:
  frigate:
    env_file: "frigate.env"
    privileged: false
#    user: 0:104
    cap_add:
        - CAP_PERFMON
    container_name: frigate
    restart: unless-stopped
    network_mode: "host"
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 200mb
    volumes:
      - /var/local/frigate/config:/config
      - /mnt/micron/media:/media/frigate
      - type: tmpfs # Optional: 2GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2147483648
    # Hide the ports section if using host networking
#    ports:
#      - "5000:5000" # For HA
#      - "1984:1984" # Access to go2rtc
#      - "8971:8971"
#      - "8554:8554" # RTSP feeds
    devices:
      - /dev/dri/renderD128 # for intel hwaccel
      - /dev/apex_0:/dev/apex_0  # Only put this in if you have a PCIe Coral Edge TPU
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

EmpireTech Dahua rebadge (IPC-T54IR-AS-S3, IPC-Color4M-T)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/37187d00-60ae-4a95-a899-31870dd00192)

### Any other information that may be helpful

I have used MQTT explorer to check what messages, are arriving with the MQTT broker (which is Mosquitto running as an HA addon). It shows no activity for Frigate at all (but I know MQTT working because I can see all the updates from my Tasmota devices coming in). 

I also see no connection attempts from Frigate in the Mosquitto logs. I can ping my HA VM from my Frigate container, and I can also watch clips from Frigate through the Media library feature in HA, so I know the connectivity between them is working.

**Comment by hawkeye217** [comment]
Since Frigate didn't change, perhaps this is due to something in HA or with an update to the mosquitto addon?

You could try enabling mqtt debug logs:

```
logger:
  default: info
  logs:
    frigate.comms.mqtt: debug
```
