### DISCUSSION TITLE
[Config Support]: go2rtc image rotation in system with AMD and Intel GPUs

### DISCUSSION THREAD

**Discussion by Omagerrrhd** [blakeblackshear/frigate#16946] [Config Support] [answered]
### Describe the problem you are having

Recently migrated Frigate from a Raspberry PI 5 to a Micro FF PC due to the lack of a GPU in the PI to offload acceleration to. Using go2rtc for all streams from 7 cameras now, and have everything working except one issue:

One of the cameras is a Wyze Doorbell with Thingino firmware. That camera does not support camera rotation natively, so I am trying to rotate the stream 90 degree clockwise using go2rtc/ffmpeg. I am having issues getting the rotation to work with go2rtc and GPU acceleration. It's working at the moment, but is using the CPUs and not the GPU.

System Info:
Debian Bookworm
Intel Core i7 8th Gen CPU
Intel Coffee Lake Integrated GPU
AMD RX 560 GPU in PCI slot
Frigate 15.0 Stable (no GPU specific variant)
Mesa Gallium Driver for GPU (VA-API)

I had this working as expected on another system with NVIDIA GPUs and CUDA, so I know this works. The issue I am seeing now is that when I attempt to use the 'rotate=90' option in the go2rtc section of config.yml, it throws an error in the go2rtc logs

3/4/2025, 10:46:12 AM | warn | [rtsp] error=streams: exec: [Parsed_transpose_vaapi_3 @ 0x7ff628004a00] VAAPI driver doesn't support transpose[Parsed_transpose_vaapi_3 @ 0x7ff628004a00] Failed to configure output pad on Parsed_transpose_vaapi_3

Initial thought is that rotation with VAAPI and the AMD GPU isn't supported. The next thought I'm having is to try and enable the Intel Embedded GPU and use that for the rotation, but any config attempts ignore the hardware directives and use the CPU. 

Looking for any advice to see if I can get this working on the GPUs.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi #Enable Hardware Acceleration

go2rtc:
  streams:
    Wyze-Doorbell-ro: #Uncomment to enable
      - ffmpeg:rtsp://REDACT:REDACT@IP_ADDRESS:554/ch0#video=h264#hardware=intel-qsv-h264#height=2048#width=1536#timeout=30000000#rotate=90 #Uncomment to run locally
#      - ffmpeg:rtsp://REDACT:REDACT@IP_ADDRESS:554/ch0#video=h264#hardware=vaapi#height=2048#width=1536#timeout=30000000#rotate=90 #Uncomment to run locally

    Wyze-Doorbell-lores-ro: #Uncomment to enable
      - ffmpeg:rtsp://REDACT:REDACT@IP_ADDRESS:554/ch1#video=h264#hardware=intel-qsv-h264#height=640#width=364#timeout=30000000#rotate=90 #Uncomment to run localy
#      - ffmpeg:rtsp://REDACT:REDACT@IP_ADDRESS:554/ch1#video=h264#hardware#height=640#width=364#timeout=30000000#rotate=90 #Uncomment to run localy
```

### Relevant Frigate log output

```shell
None - errors are visible only in go2rtc log
```

### Relevant go2rtc log output

```shell
3/4/2025, 10:46:12 AM | warn | [rtsp] error=streams: exec: [Parsed_transpose_vaapi_3 @ 0x7ff628004a00] VAAPI driver doesn't support transpose[Parsed_transpose_vaapi_3 @ 0x7ff628004a00] Failed to configure output pad on Parsed_transpose_vaapi_3
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
#    image: ghcr.io/blakeblackshear/frigate:0.14.1-standard-arm64 (OLD RP5 IMAGE)
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/dri/renderD128 #Map the hardware acceleration (Intel GPU)
      - /dev/dri/renderD129 #Map the hardware acceleration (AMD GPU)
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - ./config.yml:/config/config.yml
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
#      - "1984:1984"
      - "1984:1984/tcp"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      LIBVA_DRIVER_NAME: radeonsi
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1581" alt="Screenshot 2025-03-04 at 11 16 02 AM" src="https://github.com/user-attachments/assets/53d0127c-d3fb-4d87-9415-7466619d3857" />
