### DISCUSSION TITLE
[Camera Support]: New ONVIF issue - failed to establish new connection

### DISCUSSION THREAD

**Discussion by nsprawling** [blakeblackshear/frigate#16959] [Camera Support] [answered]
### Describe the problem you are having

Previously had ONVIF working without issue on a HikVision DS-2DE4425IW-DE. I haven't made any config changes but have lost the controls within frigate since I last carried out a docker pull. The logs show an unknown error and "failed to establish a new connection"; included below. I'm not using autotracking; I use automations in HA to make calls for presets to the camera over ONVIF when detections are made on other cameras. This is still working.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
YardPTZ: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/YardPTZ # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1440 # <---- update for your camera's resolution
      height: 810 # <---- update for your camera's resolution
    birdseye:
      mode: objects
    zones:
      PTZ:
        coordinates: 0.999,0.061,0.82,0.049,0.635,0.058,0.395,0.088,0,0.146,0,1,1,1
        loitering_time: 0
    motion:
      mask:
        - 0.022,0.018,0.021,0.07,0.316,0.068,0.314,0.02
        - 0,0.144,0.211,0.113,0.43,0.082,0.635,0.055,0.823,0.048,1,0.063,1,0,0,0
        - 0.713,0.816,0.836,0.821,0.838,0.887,0.715,0.89
        - 0.328,0.879,0.578,0.876,0.581,0.961,0.328,0.961
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
    review: {}
    objects:
      filters:
        car: {}
        bicycle: {}
        person: {}
    ui:
      order: 3
    onvif:
      host: 192.168.60.104
      port: 80
      ignore_time_mismatch: true
      user: frigate
      password: *********
      autotracking:
        enabled: false
        zooming: relative
        zoom_factor: 0.5
        #calibrate_on_startup: true
        required_zones:
          - Main_Yard_(PTZ)
          - Front_Field_(PTZ)
          - Courtyard
        track:
          - person
          - car
        return_preset: Home
        timeout: 10
```

### Relevant Frigate log output

```shell
Onvif connection to YardPTZ failed: Unknown error: HTTPConnectionPool(host='192.168.60.104', port=80): Max retries exceeded with url: /onvif/device_service (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecf5b0bca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### Relevant go2rtc log output

```shell
Don't believe the below is relevant, however:

error="streams: wrong response on DESCRIBE" stream=YardPTZ
```

### FFprobe output from your camera

```shell
Don't believe this is relevant but request if useful
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

DS-2DE4425IW-DE

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/1c7edddd-d0e8-49be-ad4d-e4df3a996b99)
![image](https://github.com/user-attachments/assets/b0050eab-075e-482a-a4f0-21cddb921787)
