### DISCUSSION TITLE
[Support]:  Generative AI description only working for dog?

### DISCUSSION THREAD

**Discussion by dakotasoukup** [blakeblackshear/frigate#16952] [General Support]
### Describe the problem you are having

The generative AI is falling at anything other then a dog.    I am not over my quota.

![IMG_9011](https://github.com/user-attachments/assets/9b950f66-a9ff-4d2d-add5-77505a2e155b)
![IMG_9012](https://github.com/user-attachments/assets/8e0625b4-04ab-4d8d-8608-676cb5648965)

### Version

0.15.0-cea210d

### What browser(s) are you using?

chrom. 

### Frigate config file

```yaml
semantic_ search: enabled: true reindex: false model_size: small
genai:
enabled: true provider: gemini api_key: AIzaSyDdqP5geIVqC4Z1EcAGqvI
model: gemini-2. 0-flash
القة
```

### Relevant Frigate log output

```shell
Gemini returned an error: 429 Resource has been exhausted (e.g. check quota).
=
192.168.0.170
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

none
