### DISCUSSION TITLE
[Config Support]: Page in settings for zones and masks fails to load

### DISCUSSION THREAD

**Discussion by overlordhub** [blakeblackshear/frigate#16956] [Config Support]
### Describe the problem you are having

I’m having trouble loading the Mask/Zone settings page in Frigate. All other settings pages, including UI settings, Explore settings, Camera settings, Motion Tuner, and Debug, load normally. However, the Mask/Zone settings page appears blank page.

I’ve tried deleting and reinstalling Frigate multiple times, but the issue persists. I’m also running the latest version of Frigate and Frigate cards as of 3/5/25.

Not sure if this is just my issue or if others are experiencing it too.

### Version

Current version: 0.15.0

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.167
  port: 1883
  client_id: frigate
  user: mqtt-user
  password: *****
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    cam7: ffmpeg:http://10.0.0.157:8080/?action=stream#video=h264#hardware

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:*****@10.0.0.161:554/11
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - dog
        - cat
        - squirrel
    record:
      enabled: true
      retain:
        days: 2
      alerts:
        retain:
          days: 5
      detections:
        retain:
          days: 2
    zones:
      Cam1zone1:
        coordinates:
          - 0.067,0.723,0.15,0.76,0.192,0.84,0.188,0.935,0.184,0.973,0.936,0.996,0.974,0.854,0.675,0.572,0.581,0.487,0.53,0.439,0.512,0.45,0.507,0.349,0.191,0.281,0.048,0.262
        loitering_time: 0
    review:
      alerts:
        required_zones: Cam1zone1

  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:*****@10.0.0.165:554/11
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - dog
        - cat
        - squirrel
    record:
      enabled: true
      retain:
        days: 2
      alerts:
        retain:
          days: 5
      detections:
        retain:
          days: 5

  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://*****@10.0.0.138/live
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - dog
        - cat
        - squirrel
    record:
      enabled: true
      retain:
        days: 2
      alerts:
        retain:
          days: 5
      detections:
        retain:
          days: 5

  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://*****h@10.0.0.112/live
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - dog
        - cat
        - squirrel
      mask:
        - 0.506,0.374,0.522,0.305,0.54,0.366
    record:
      enabled: true
      retain:
        days: 2
      alerts:
        retain:
          days: 5
      detections:
        retain:
          days: 2
    zones:
      cam4zone1:
        coordinates:
          - 0,0.615,0.222,0.5,1,0.494,1,0.622,0.998,0.998,0.005,0.998
        loitering_time: 0
        inertia: 3
    motion:
      mask:
        - 0.524,0.314,0.514,0.37,0.529,0.369,0.535,0.365
    review:
      alerts:
        required_zones: cam4zone1

  cam5:
    ffmpeg:
      inputs:
        - path: rtsp://*****@10.0.0.133/live
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - dog
        - cat
        - squirrel
      mask:
        - 0.687,0.576,0.674,0.179,0.677,0.055,0.815,0.221,0.812,0.751,0.756,0.859,0.697,0.896,0.669,0.783,0.682,0.692
        - 0,0.758,0.008,0.317,0.21,0.183,0.276,0.387
    record:
      enabled: true
      retain:
        days: 2
      alerts:
        retain:
          days: 5
      detections:
        retain:
          days: 5

  cam7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam7
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    objects:
      track:
        - person
        - dog
        - cat
        - squirrel
    record:
      enabled: true
      retain:
        days: 2
      alerts:
        retain:
          days: 5
      detections:
        retain:
          days: 2
    zones:
      Cam7zone1:
        coordinates:
          - 0.067,0.723,0.15,0.76,0.192,0.84,0.188,0.935,0.184,0.973,0.936,0.996,0.974,0.854,0.675,0.572,0.581,0.487,0.53,0.439,0.512,0.45,0.507,0.349,0.191,0.281,0.048,0.262
        loitering_time: 0
    review:
      alerts:
        required_zones: Cam7zone1

version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
N/a
```

### Relevant go2rtc log output

```shell
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
Home assistant VM on Proxmox
```

### Object Detector

Coral
