### DISCUSSION TITLE
The solution for all Firefox (Windows) related playback HEVC/H265 issues! At least for me! (Full HEVC/H265 Support for Windows Firefox)

### DISCUSSION THREAD

**Discussion by Gubelat** [blakeblackshear/frigate#16965] [Show and tell]
Since the Start of Firefox iam using this Browser and i love him. I really dont like to switch over to Edge or Chrome.
In the last three weeeks Iam tinkering with Frigate and the Videostream of my cheap Ali Express PTZ Camera.
This Camera only supports HEVC (H265) rtsp Streams. And as we all now Firefox has bad issues in showing and Playback with such VBR encoded HEVC streams. With open H265 in Firefox i got a lot of trouble to display my live view and my recordings.

**Tada, the soulution is:**   
Go to Microsoft Store and buy the HEVC-Extensions from Microsoft for 1 € or 1$. And install!
now open Firefox an enter about:config an accept the risks! 
Search for "media.hevc.enabled" and set media.hevc.enabled to false or 0!
go to manage extensions/plugins.
Set OpenH264-Videocodec inactive.
Restart Firefox and boom! You have flawless HEVC/H265 decoding in your freakin Firefox Browser!

Maybe some of you can confirm, that this setup works, and then we should put this in to the docs!
So that People can find this information more quickly

Now i can enjoy my Pee Alarm System. :-)

Edit: I still run into some Issues.

now i transcode the HVEC stream to H264 in go2rtc.

using: 
`ptzcam:
      - ffmpeg:rtsp://uname:passwd@192.168.124.4:8554/profile1#video=h264#audio=aac#hardware`
      
 and this general ffmpeg setup.
 
 ```
ffmpeg:

  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: -avoid_negative_ts make_zero -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
      record: -map 0:v -map 0:a -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy -b:v 4M -r 5
```
