### DISCUSSION TITLE
[Detector Support]: RKNN false positives with the latest images

### DISCUSSION THREAD

**Discussion by a2nt** [blakeblackshear/frigate#16967] [Detector Support]
### Describe the problem you are having

Looks like something went wrong with the latest frigate versions RKNN detectors detects weird something at the empty space see. You can see it at the screenshoot, I'm using the same config as manual says

![image](https://github.com/user-attachments/assets/2d273760-7fa0-49c5-b4ac-c5f074e384e4)

### Version

0.16-0

### Frigate config file

```yaml
auth:
#  mode: native
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.17.0.0/16
    - 172.18.0.0/16
    - 172.19.0.0/16

lpr:
  enabled: false

face_recognition:
  enabled: false

detectors:
  rknn:
    type: rknn
    num_cores: 3

model:
  # name of model (will be automatically downloaded) or path to your own .rknn model file
  # possible values are:
  # - deci-fp16-yolonas_s
  # - deci-fp16-yolonas_m
  # - deci-fp16-yolonas_l
  # - /config/model_cache/your_custom_model.rknn
  path: deci-fp16-yolonas_s
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nhwc
  labelmap_path: /labelmap/coco-80.txt

ffmpeg:
  hwaccel_args: preset-rk-h264 # or preset-rk-h265
  output_args:
    record: preset-record-generic-audio-aac # preset-record-generic-audio-copy
     #detect: -f rawvideo
     #rtmp: -c copy -f flv -flvflags no_duration_filesize

ui:
  timezone: Etc/GMT-2
  time_format: 24hour
  date_style: full
  time_style: medium
  strftime_fmt: '%a, %H:%M (%d.%m.%Y)'

# Re-stream
#- ffmpeg:camera_0
##video=h264/rk
##audio=aac 
# rtsp:// :554
# dvrip:// :34567
go2rtc:
  streams:
    camera_0:
      #- dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      #- "ffmpeg:camera_0#video=copy"
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.10:34567
      - ffmpeg:camera_0#audio=aac
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.11:34567/audioback?backchannel=1
    camera_1:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.11:34567
      - ffmpeg:camera_1#audio=aac
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.11:34567/audioback?backchannel=1
    camera_2:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.12:34567
      - ffmpeg:camera_2#audio=aac
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.12:34567/audioback?backchannel=1
    camera_3:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.13:34567
      - ffmpeg:camera_3#audio=aac
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.13:34567/audioback?backchannel=1
    camera_4:
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.14:34567
      - ffmpeg:camera_4#audio=aac
      - dvrip://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.14:34567/audioback?backchannel=1
    webrtc:
      candidates:
        - 192.168.88.2:8555
        - stun:8555
mqtt:
  host: 192.168.88.2 # Docker Host
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

birdseye:
  enabled: true
  mode: continuous
  quality: 1
  width: 2880
  height: 1616

audio:
  enabled: true
  listen:
    - scream
    - speech
    - yell

database:
  path: /db/frigate.db

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle

motion:
  threshold: 30
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mqtt_off_delay: 30

record:
  enabled: true
  retain:
    days: 0
    mode: motion

  #alerts:
  #  retain:
  #    days: 7
  #  pre_capture: 10
  #  post_capture: 60
  #detections:
  #  retain:
  #    days: 7
  #  pre_capture: 10
  #  post_capture: 60
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 1080
  retain:
    default: 15
    objects:
      person: 15
      car: 3
#rtmp:
#  enabled: false

live:
  height: 1080
  quality: 1

timestamp_style:
  position: br
  format: '%d.%m.%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid

detect:
  enabled: true
  fps: 5
  max_disappeared: 250
  stationary:
    interval: 5000
    threshold: 500
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    #max_frames:
    #  default: 3000 # 3000 frames / 5 fps = 10 mins

logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.record.maintainer: debug
    detector.audio: debug
cameras:
  camera_0:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_0
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/camera_0
          roles:
            - audio
    detect:
      width: 2880
      height: 1616
    zones:
      inner_entrance-0:
        coordinates: 0,1616,2880,1616,2880,1301,2369,755,0,1044
      outside_entrance_road-0:
        coordinates: 
          0.905,0.51,1,0.603,1,0.4,0.96,0.356,0.936,0.357,0.829,0.39,0.808,0.412,0.829,0.433,0.851,0.467
        inertia: 3
      outside_entrance_house1-0:
        coordinates: 
          695,685,1611,501,1620,568,2028,517,2114,561,2132,556,2213,598,2245,612,2273,609,2328,623,2479,695,1559,824,713,925
      outside_entrance_house2-0:
        coordinates: 2658,653,2522,589,2319,494,2333,429,2880,408,2880,646
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

    review:
      detections:
        required_zones: outside_entrance_road-0
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/camera_1
          roles:
            - audio
    detect:
      width: 2880
      height: 1616
    zones:
      inner_garden-1:
        coordinates: 2880,813,1807,275,1696,242,0,260,0,1616,2880,1616

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

  camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/camera_2
          roles:
            - audio
    detect:
      width: 2880
      height: 1616
    zones:
      gate_inner-2:
        coordinates: 413,693,460,0,0,0,0,1616,455,1616
      gate_outer_near-2:
        coordinates: 
          0.446,1,0.636,1,0.578,0.82,0.525,0.639,0.386,0.252,0.342,0.119,0.141,0,0.14,0.313,0.149,1
        inertia: 3
      gate_outer_road-2:
        coordinates: 2880,1616,2880,743,2146,0,517,0,515,86,907,256,1821,1616
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

    review:
      alerts:
        required_zones: gate_outer_near-2
      detections:
        required_zones: gate_outer_near-2
  camera_3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/camera_3
          roles:
            - audio
    detect:
      width: 2880
      height: 1616
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100
    zones:
      spokoinaya_road-3:
        coordinates: 
          0,0.111,0.41,0.09,0.812,0.23,0.762,0.142,0.767,0.119,0.822,0.197,0.884,0.269,0.953,0.4,0.943,0.436,0.151,0.721,0,0.721
        inertia: 3
      inner-3:
        coordinates: 2880,895,2880,1616,2245,1616,2687,1157
      outside_garden-3:
        coordinates: 0,1,0.781,1,0.924,0.745,1,0.548,0.927,0.448,0.635,0.573,0,0.743
        inertia: 3
    motion: {}
    review:
      detections:
        required_zones:
          - spokoinaya_road-3
          - outside_garden-3
      alerts:
        required_zones: outside_garden-3
  camera_4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_4
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/camera_4
          roles:
            - audio
    detect:
      width: 2880
      height: 1616
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      quality: 100

camera_groups:
  Outside:
    order: 0
    icon: LuCar
    cameras:
      - camera_2
      - camera_3
  Inner:
    order: 1
    icon: LuPalmtree
    cameras:
      - camera_0
      - camera_1

semantic_search:
  enabled: true
  reindex: false
  model_size: small
version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    hostname: 127.0.0.1
    network_mode: host
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:73c2c34-rk #ac3dfbc-rk
    group_add:
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "512mb" # update for your cameras based on calculation above
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0:/dev/dri/card0
      - /dev/video-dec0:/dev/video-dec0
      - /dev/video-enc0:/dev/video-enc0
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
      - /dev/mali0:/dev/mali0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./db:/db
      - /mnt/data/frigate:/media/frigate
      - ./default-yolov8m-rk3588.rknn:/default-yolov8m-rk3588.rknn
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2G
    ports:
      - "127.0.0.1:5000:5000" # HTTP
      - "127.0.0.1:8554:8554" # RTSP
#      - "192.168.88.2:8443:8443" # SRTP
#      - "192.168.88.2:1984:1984" # API
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FFMPEG_RKMPP_PIXFMT: "YUV420P"
      FRIGATE_MQTT_USER: "home"
      FRIGATE_MQTT_PASSWORD: "xdc534"
      FRIGATE_RTSP_USER: "admin"
      FRIGATE_RTSP_PASSWORD: "xdc534xdc534"
      I_PROMISE_I_WONT_MAKE_AN_ISSUE_ON_GITHUB: "true"
    deploy:
      resources:
        limits:
          cpus: '5.0'
    extra_hosts:
      - "192.168.88.2:192.168.88.2"
```

### Relevant Frigate log output

```shell
frigate  | 2025-03-06 02:08:50.644687953  [2025-03-06 02:08:50] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2025-03-06 02:08:50.693646327  [2025-03-06 02:08:50] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2025-03-06 02:08:50.770346127  [2025-03-06 02:08:50] frigate.app                    INFO    : Starting Frigate (0.16.0-73c2c34)
frigate  | 2025-03-06 02:08:50.788775953  [2025-03-06 02:08:50] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2025-03-06 02:08:50.789377068  [2025-03-06 02:08:50] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2025-03-06 02:08:50.842066090  [2025-03-06 02:08:50] frigate.app                    INFO    : Recording process started: 390
frigate  | 2025-03-06 02:08:50.843914935  [2025-03-06 02:08:50] frigate.app                    INFO    : Review process started: 401
frigate  | 2025-03-06 02:08:50.847009760  [2025-03-06 02:08:50] frigate.app                    INFO    : go2rtc process pid: 101
frigate  | 2025-03-06 02:08:50.875142888  [2025-03-06 02:08:50] detector.rknn                  INFO    : Starting detection process: 410
frigate  | 2025-03-06 02:08:50.875786294  [2025-03-06 02:08:50] frigate.app                    INFO    : Embedding process started: 412
frigate  | 2025-03-06 02:08:50.881673199  [2025-03-06 02:08:50] frigate.detectors.plugins.rknn INFO    : You are using yolo-nas with weights from DeciAI. These weights are subject to their license and can't be used commercially. For more information, see: https://docs.deci.ai/super-gradients/latest/LICENSE.YOLONAS.html
frigate  | 2025-03-06 02:08:50.902261616  [2025-03-06 02:08:50] frigate.app                    INFO    : Output process started: 433
frigate  | 2025-03-06 02:08:50.984541491  W rknn-toolkit-lite2 version: 2.3.0
frigate  | 2025-03-06 02:08:51.028383240  [2025-03-06 02:08:51] frigate.app                    INFO    : Camera processor started for camera_0: 521
frigate  | 2025-03-06 02:08:51.037754338  I RKNN: [02:08:51.037] RKNN Runtime Information, librknnrt version: 2.3.0 (c949ad889d@2024-11-07T11:35:33)
frigate  | 2025-03-06 02:08:51.037774463  I RKNN: [02:08:51.037] RKNN Driver Information, version: 0.9.8
frigate  | 2025-03-06 02:08:51.038201456  I RKNN: [02:08:51.038] RKNN Model Information, version: 6, toolkit version: 2.3.0(compiler version: 2.3.0 (@2024-11-07T08:11:34)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
frigate  | 2025-03-06 02:08:51.059493361  [2025-03-06 02:08:51] frigate.app                    INFO    : Camera processor started for camera_1: 527
frigate  | 2025-03-06 02:08:51.060256932  [2025-03-06 02:08:51] frigate.app                    INFO    : Camera processor started for camera_2: 528
frigate  | 2025-03-06 02:08:51.065885424  W RKNN: [02:08:51.065] query RKNN_QUERY_INPUT_DYNAMIC_RANGE error, rknn model is static shape type, please export rknn with dynamic_shapes
frigate  | 2025-03-06 02:08:51.066028630  W Query dynamic range failed. Ret code: RKNN_ERR_MODEL_INVALID. (If it is a static shape RKNN model, please ignore the above warning message.)
frigate  | 2025-03-06 02:08:51.076926579  [2025-03-06 02:08:51] frigate.app                    INFO    : Camera processor started for camera_3: 538
frigate  | 2025-03-06 02:08:51.092358121  [2025-03-06 02:08:51] frigate.app                    INFO    : Camera processor started for camera_4: 557
frigate  | 2025-03-06 02:08:51.092525826  [2025-03-06 02:08:51] frigate.app                    WARNING : The current SHM size of 512.0MB is too small, recommend increasing it to at least 740MB.
frigate  | 2025-03-06 02:08:51.132421680  [2025-03-06 02:08:51] frigate.app                    INFO    : Capture process started for camera_0: 576
frigate  | 2025-03-06 02:08:51.146433703  [2025-03-06 02:08:51] frigate.app                    INFO    : Capture process started for camera_1: 581
frigate  | 2025-03-06 02:08:51.160575224  [2025-03-06 02:08:51] frigate.app                    INFO    : Capture process started for camera_2: 589
frigate  | 2025-03-06 02:08:51.175566648  [2025-03-06 02:08:51] frigate.app                    INFO    : Capture process started for camera_3: 600
frigate  | 2025-03-06 02:08:51.190651404  [2025-03-06 02:08:51] frigate.app                    INFO    : Capture process started for camera_4: 608
frigate  | 2025-03-06 02:08:51.219005320  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
frigate  | 2025-03-06 02:08:51.337913561  [2025-03-06 02:08:51] frigate.audio_manager          INFO    : Audio processor started (pid: 617)
frigate  | 2025-03-06 02:08:51.418733669  [2025-03-06 02:08:51] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate  | 2025-03-06 02:08:51.577316101  [2025-03-06 02:08:51] frigate.api.fastapi_app        INFO    : FastAPI started
frigate  | 2025-03-06 02:08:54.764199120  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-03-06 02:08:56.301122524  [2025-03-06 02:08:56] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-06 02:08:56.301510726  [2025-03-06 02:08:56] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-06 02:08:56.349732653  [2025-03-06 02:08:56] frigate.video                  ERROR   : camera_4: Unable to read frames from ffmpeg process.
frigate  | 2025-03-06 02:08:56.350937800  [2025-03-06 02:08:56] frigate.video                  ERROR   : camera_4: ffmpeg process is not running. exiting capture thread...
```

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/fff83f51-5b59-4743-b114-459db91b7cb1)

P.S. the detector runs ok with with image ghcr.io/blakeblackshear/frigate:2207a91-rk
But broken with the latest images like [73c2c34-rk](https://github.com/users/blakeblackshear/packages/container/frigate/368036655?tag=73c2c34-rk)

![image](https://github.com/user-attachments/assets/ff9c983b-7dbc-4213-88ac-602ed76c8cea)
