### DISCUSSION TITLE
[Detector Support]: Issues with Coral detection getting stuck

### DISCUSSION THREAD

**Discussion by bigmike613** [blakeblackshear/frigate#16977] [Detector Support]
### Describe the problem you are having

I am using the USB Coral TPU and since last week I have been getting "Detection appears to be stuck. Restarting detection process..." error messages sporadically. I have tried the same coral on **2 different PCs** and have also **bought a new USB cable and new Coral device to rule out hardware issues**. I have the same results. the detection is always force killed and then restarts fine and runs for some time. I am using a Frigate+ model, but I have also tried to go back to a standard model for troubleshooting and get the same result. 

### Version

0.15.0-cea210d

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate:5000/api/config/schema.json
model:
#TPU
  path: plus://<redacted>

mqtt:
  enabled: true
  host: 10.10.10.250
  user: mqtt101
  password: <redacted>
ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  coral:
    type: edgetpu
    device: usb


go2rtc:
  streams:
    Backyard:
      - rtsp://<redacted>@10.10.20.24:554/axis-media/media.amp
    Front:
      - rtsp://<redacted>@10.10.20.22:554/axis-media/media.amp
    Side:
      - rtsp://<redacted>@10.10.20.21:554/axis-media/media.amp
    Garage:
      - rtsp://<redacted>@10.10.20.23:554/axis-media/media.amp

record:
  #sync_recordings: true
  enabled: true
  retain:
    days: 90

objects:
  track:
    - person
    - car
    - dog
    - cat
    - deer
    - license_plate
    - face
    - package
    - amazon
    - ups
    - fedex
    - amazon
  filters:
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6
    amazon:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    person:
      min_score: .7
      threshold: .85
    car:
      min_area: 500
      max_area: 100000
      min_ratio: 0.5
      min_score: 0.7
      threshold: 0.85
timestamp_style:
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
#---------------------------------------------------------------------------------------------------------------------------------------
birdseye:
  enabled: true
  mode: continuous
cameras:
  Backyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true  # <---- disable detection until you have a working camera feed
      width: 1920  # <---- update for your camera's resolution
      height: 1080  # <---- update for your camera's resolution
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      required_zones:
        - entire_yard
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 15
        post_capture: 15
      detections:
        retain:
          days: 90
    motion:
      mask: 
        0.296,0.191,0.421,0.213,0.489,0.239,0.676,0.305,0.863,0.351,0.956,0.29,0.94,0.155,0.906,0,0,0,0,0.277,0.176,0.208
    zones:
      entire_yard:
        coordinates: 
          1,1,1,0,0.908,0,0.957,0.285,0.866,0.345,0.676,0.308,0.561,0.266,0.441,0.229,0.296,0.19,0,0.278,0,1
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        car:
          mask:
            - 585,226,1297,329,1297,167,0,101,0,343
    review:
      alerts:
        required_zones:
          - entire_yard
  Front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    zones:
      goodFront:
        coordinates: 
          0,1,0.752,1,0.865,0.709,0.927,0.444,0.953,0.255,0.841,0.185,0.828,0.155,0.701,0.133,0.62,0.133,0.357,0.191,0,0.436
        inertia: 3
        loitering_time: 0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      required_zones:
        - goodFront
    motion:
      mask:
        - 0.833,0.177,0.956,0.261,0.986,0,0.968,0,0.83,0
        - 0.354,0.202,0.563,0.146,0.683,0.132,0.83,0.155,0.831,0,0,0,0,0.462,0.177,0.314
    objects:
      filters:
        car:
          mask:
            - 0.831,0.197,0.954,0.283,0.986,0,0.968,0,0.83,0
            - 0.353,0.23,0.563,0.146,0.688,0.137,0.886,0.16,0.871,0,0,0,0,0.462
        person:
          mask: 
            0.353,0.202,0.563,0.146,0.64,0.135,0.691,0.132,0.869,0.163,0.975,0.219,0.896,0,0,0,0,0.462,0.047,0.405,0.186,0.301,0.319,0.219
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 15
        post_capture: 15
      detections:
        retain:
          days: 90
    review:
      alerts:
        required_zones: goodFront
      detections:
        required_zones: goodFront
  Side: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      required_zones:
        - goodside
    motion:
      mask: 0.515,0.301,0.657,0.31,0.956,0.351,1,0,0,0,0,0.452,0.207,0.331
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 15
        post_capture: 15
      detections:
        retain:
          days: 90
    zones:
      goodside:
        coordinates: 
          0.916,1,0.95,0.423,0.954,0.355,0.897,0.348,0.845,0.335,0.658,0.309,0.508,0.296,0.259,0.328,0.202,0.332,0,0.453,0,1
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        car:
          mask: 0.513,0.301,0.657,0.308,0.956,0.351,1,0,0,0,0,0.483
    review:
      alerts:
        required_zones:
          - goodside
  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    zones:
      garageGrasshouse:
        coordinates: 1920,1080,1920,597,1586,468,512,441,0,592,0,1080
      garageGrass:
        coordinates: 0.553,0.136,0.858,0.262,0.774,0,0.36,0,0.358,0.162
        inertia: 3
        loitering_time: 0
      driveway:
        coordinates: 1920,682,1920,452,1861,415,1733,322,1639,273,1484,244,1691,591
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 500
      #required_zones:
      #  - driveway
      #  - garageGrass
      #  - garageGrasshouse
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      alerts:
        retain:
          days: 90
        pre_capture: 15
        post_capture: 15
      detections:
        retain:
          days: 90
    objects:
      filters:
        car:
          mask: 0.884,0.552,1,0.402,1,0.081,0.342,0.06,0.227,0.485
    review:
      alerts:
        required_zones:
          - driveway
          - garageGrass
          - garageGrasshouse
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.183,0.084,0.281,0.037,0.31,0.078,0.309,0.164,0.306,0.238,0.295,0.273,0.267,0.307,0.243,0.339,0.211,0.343,0.186,0.31,0.166,0.296,0.155,0.24,0.158,0.157
        - 0.862,0,0.853,0.232,1,0.393,1,0
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:    
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
    shm_size: "308mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /FRIGATE/config/config.yml:/config/config.yml
      - /mnt/video6:/media/frigate
      - /FRIGATE/config:/config
      - /FRIGATE/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "<redacted>"
      PLUS_API_KEY: "<redacted>"
      YOLO_MODELS: "yolov7-320"
```

### Relevant Frigate log output

```shell
2025-03-06 05:12:17.571321046  [2025-03-06 05:12:14] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-03-06 05:12:17.576207783  [2025-03-06 05:12:17] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-03-06 05:12:20.392673954  [INFO] Starting go2rtc healthcheck service...
2025-03-06 06:35:44.989850461  [2025-03-06 06:35:44] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2025-03-06 06:35:44.989855559  [2025-03-06 06:35:44] root                           INFO    : Waiting for detection process to exit gracefully...
2025-03-06 06:36:15.017444433  [2025-03-06 06:36:15] root                           INFO    : Detection process didn't exit. Force killing...
2025-03-06 06:36:15.034271283  [2025-03-06 06:36:15] root                           INFO    : Detection process has exited...
2025-03-06 06:36:15.085942775  [2025-03-06 06:36:15] detector.coral                 INFO    : Starting detection process: 28183
2025-03-06 06:36:18.062770153  [2025-03-06 06:36:15] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-03-06 06:36:18.068603388  [2025-03-06 06:36:18] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-03-06 06:54:15.071370304  [2025-03-06 06:54:15] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2025-03-06 06:54:15.072040241  [2025-03-06 06:54:15] root                           INFO    : Waiting for detection process to exit gracefully...
2025-03-06 06:54:45.094820342  [2025-03-06 06:54:45] root                           INFO    : Detection process didn't exit. Force killing...
2025-03-06 06:54:45.119301954  [2025-03-06 06:54:45] root                           INFO    : Detection process has exited...
2025-03-06 06:54:45.147532271  [2025-03-06 06:54:45] detector.coral                 INFO    : Starting detection process: 34258
2025-03-06 06:54:47.909448361  [2025-03-06 06:54:45] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-03-06 06:54:47.914825274  [2025-03-06 06:54:47] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-03-06 070633](https://github.com/user-attachments/assets/c33cf283-fa0e-48cd-9064-170c71af492b)
