### DISCUSSION TITLE
[Support]: ffmpeg processing issues - No space left on device

### DISCUSSION THREAD

**Discussion by rgregg** [blakeblackshear/frigate#16986] [General Support]
### Describe the problem you are having

I've been running into issues lately where I'm unable to play back or export video that should have been recorded. When I look in the log files, I see numerous issues around the same timestamp of the video I'm trying to watch about "No space left on device".

For example:
```
ffmpeg.carport.record          ERROR   : [vost#0:0/copy @ 0x5ed895023780] Error submitting a packet to the muxer: No space left on device
ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Task finished with error code: -28 (No space left on device)
ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Terminating thread with return code -28 (No space left on device)
ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Error writing trailer: No space left on device
```

However, there's plenty of space when I do a df:

```
Filesystem                         Size  Used Avail Use% Mounted on
overlay                            1.8T   77G  1.7T   5% /
tmpfs                               64M     0   64M   0% /dev
shm                                1.0G  477M  548M  47% /dev/shm
/dev/mapper/ubuntu--vg-ubuntu--lv  1.8T   77G  1.7T   5% /config
tmpfs                              954M  114M  841M  12% /tmp/cache
/dev/mapper/large_disk_array-cctv   22T   17T  4.3T  80% /media/frigate
tmpfs                               32G   12K   32G   1% /proc/driver/nvidia
tmpfs                              6.3G  6.6M  6.3G   1% /run/nvidia-persistenced/socket
udev                                32G     0   32G   0% /dev/nvidia0
```

Any way to debug or better understand what's going on here? It seems like every time I want to go look at a video of an event that happened - I'm running into this error and it's a huge pain.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Google Chrome 88.0.4324.150

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt.lan

ffmpeg:
  # hwaccel_args: preset-vaapi
  hwaccel_args: preset-nvidia
  output_args:
    record: preset-record-generic-audio-aac

auth:
  enabled: true
  cookie_secure: true
  session_length: 864000
  refresh_time: 259200
  trusted_proxies:
    - 10.0.2.164
    - 10.0.1.3

go2rtc:
  streams:
    yard:
      - rtsp://192.168.42.73:554/Preview_01_main
    yard_sub:
      - rtsp://192.168.42.73:554/Preview_01_sub
    side_yard:
      - rtsp://192.168.42.148:554/Preview_01_main
    side_yard_sub:
      - rtsp://192.168.42.148:554/Preview_01_sub
    side_yard_back:
      - rtsp://192.168.42.129:554/Preview_01_main
    side_yard_back_sub:
      - rtsp://192.168.42.129:554/Preview_01_sub
    lake_view:
      - rtsp://192.168.42.161:554/Preview_01_main
    lake_view_sub:
      - rtsp://192.168.42.161:554/Preview_01_sub
    backyard:
      - rtsp://192.168.42.106:554/Preview_01_main
    backyard_sub:
      - rtsp://192.168.42.106:554/Preview_01_sub
    carport:
      - rtsp://192.168.42.123:554/Preview_01_main
    carport_sub:
      - rtsp://192.168.42.123:554/Preview_01_sub
    front_steps:
      - rtsp://192.168.42.100:554/Preview_01_main
    front_steps_sub:
      - rtsp://192.168.42.100:554/Preview_01_sub
    front_door:
      - rtsp://192.168.42.101:554/Preview_01_main
    front_door_sub:
      - rtsp://192.168.42.101:554/Preview_01_sub
    driveway:
      - rtsp://192.168.42.196:554/Preview_01_main
    driveway_sub:
      - rtsp://192.168.42.196:554/Preview_01_sub
    dining_room:
      - rtsp://192.168.42.182:554/Preview_01_main
    dining_room_sub:
      - rtsp://192.168.42.182:554/Preview_01_sub
    porch:
      - rtsp://192.168.42.76:554/Preview_01_main
    porch_sub:
      - rtsp://192.168.42.76:554/Preview_01_sub

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://5c61bf8e253fcbb2afec46f0f221d889

semantic_search:
  enabled: true
  reindex: false
  model_size: large

objects:
  track:
    - person
    - car
    - package
    - fedex
    - ups
    - amazon

  filters:
    car:
      min_area: 5000
      min_score: 0.85
    person:
      min_score: 0.85
    package:
      min_score: 0.85
    cat:
      min_score: 0.9
    dog:
      min_score: 0.9
    deer:
      min_score: 0.9
    face:
      min_score: 0.9
    fedex:
      min_score: 0.9
    ups:
      min_score: 0.9
    amazon:
      min_score: 0.9

motion:
  threshold: 50
  contour_area: 30

audio:
  enabled: false

snapshots:
  enabled: true
  bounding_box: false
  crop: true
  retain:
    default: 30
    objects:
      person: 60

record:
  enabled: true
#  sync_recordings: true
  retain:
    days: 30
    mode: all
  alerts:
    retain:
      days: 60
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 60
    pre_capture: 5
    post_capture: 5
cameras:
  yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/yard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1536
      height: 432
      fps: 7
      enabled: true
    motion:
      mask:
        - 571,46,943,48,943,0,570,0
    zones:
      yard_patio:
        coordinates: 872,432,878,311,817,294,540,260,457,162,255,212,158,228,0,398,0,432
      yard_grass:
        coordinates: 1182,295,1166,158,673,129,471,159,467,235,631,270,862,291
    objects:
      filters:
        person:
          mask:
            - 158,198,74,305,139,432,0,432,0,353,0,178
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  side_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/side_yard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 7
      enabled: true
    motion:
      mask:
        - 641,0,638,39,260,36,262,0
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  side_yard_back:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_yard_back_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/side_yard_back
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 7
      enabled: true
    motion:
      mask:
        - 641,0,638,39,260,36,262,0
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      width: 1440
      height: 1080
      fps: 5
      enabled: true
    motion:
      mask: 0.643,0,0.641,0.036,0.35,0.033,0.35,0
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  lake_view:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lake_view
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    onvif:
      host: 192.168.42.161
      port: 8000
      user: admin
      password: mbFRhK1Wrf9tKjGd9Sjb
    detect:
      width: 640
      height: 360
      fps: 7
      enabled: false
    motion:
      mask: 0.598,0.038,0.397,0.039,0.399,0,0.593,0
  carport:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 7
      enabled: true
    objects:
      filters:
        car:
          mask:
            - 702,106,753,0,484,125,728,113
    motion:
      mask:
        - 641,0,638,39,260,36,262,0
    zones:
      parked_cars:
        coordinates: 896,512,896,246,0,207,0,512
      driveway:
        coordinates: 803,285,233,230,238,112,804,110
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1536
      height: 432
      fps: 7
      enabled: true
    motion:
      mask: 0.374,0.074,0.624,0.075,0.624,0,0.371,0
    objects:
      filters:
        person:
          mask:
            - 158,198,74,305,139,432,0,432,0,353,0,178
        vehicle:
          min_area: 15000
          mask:
            - 244,432,753,432,717,238,394,219,193,177,31,311
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

  front_steps:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_steps_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/front_steps_sub
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1536
      height: 432
      fps: 7
      enabled: true
    motion:
      mask:
        - 572,33,954,39,955,0,570,0
    objects:
      filters:
        car: {}
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    zones:
      steps:
        coordinates: 476,323,419,432,590,432,765,373,1019,257,984,69,802,39
      deck:
        coordinates: 689,0,622,205,378,432,0,432,0,193,280,45
  carport_side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1536
      height: 576
      fps: 7
      enabled: true
    motion:
      mask: 0.752,0.068,0.999,0.071,1,0.003,0.749,0.011
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    objects:
      mask:
        - 0.241,0.011,0.405,0,0.397,0.069,0.291,0.167
        - 0,0,0.178,0.395,0.295,0.302,0.288,1,0.001,0.995,0,0.445
    zones:
      garden_path:
        coordinates: 0.411,0,0.425,0.181,0.293,0.298,0.291,1,0.995,0.989,1,0
        loitering_time: 0
        objects: person
        inertia: 3
      street:
        coordinates: 0.177,0.394,0.423,0.177,0.413,0.045,0.141,0.319
        loitering_time: 0
        objects:
          - car
          - person
        inertia: 3
  dining_room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dining_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/dining_room
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
      host: 192.168.42.182
      port: 8000
      user: admin
      password: mbFRhK1Wrf9tKjGd9Sjb
    detect:
      width: 640
      height: 480
      fps: 7
      enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 480
    motion:
      mask: 0.012,0.016,0.012,0.047,0.343,0.048,0.343,0.014
  porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/porch
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 7
      enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    motion:
      mask: 0.327,0.021,0.327,0.07,0.658,0.068,0.658,0.019
version: 0.15-1
camera_groups: {}
```

### Relevant Frigate log output

```shell
frigate  | 2025-03-06 07:28:47.558310095  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [segment @ 0x5ed895024a00] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | 2025-03-06 07:28:47.558325782  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 1.7 is not allocated
frigate  | 2025-03-06 07:28:47.558340144  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558357336  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] TYPE_FIL: Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558364891  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558375302  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 0.12 is not allocated
frigate  | 2025-03-06 07:28:47.558387472  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558398087  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 0.0 is not allocated
frigate  | 2025-03-06 07:28:47.558423225  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558435021  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558449315  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558456572  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558467290  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558478886  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] skip_data_stream_element: Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558488753  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558501234  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 3.6 is not allocated
frigate  | 2025-03-06 07:28:47.558510985  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558520628  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558530214  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558539975  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558550389  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558563575  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 3.0 is not allocated
frigate  | 2025-03-06 07:28:47.558569776  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558580045  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 3.0 is not allocated
frigate  | 2025-03-06 07:28:47.558590082  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558600282  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558609980  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558619155  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed8950278c0] Queue input is backward in time
frigate  | 2025-03-06 07:28:47.558629709  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 48999855, current: 48995819; changing to 48999856. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558639554  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 48999856, current: 48996843; changing to 48999857. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558649996  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 48999857, current: 48997867; changing to 48999858. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558659904  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 48999858, current: 48998891; changing to 48999859. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558669935  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed8950278c0] Queue input is backward in time
frigate  | 2025-03-06 07:28:47.558680966  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 87840531, current: 87835737; changing to 87840532. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558690766  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 87840532, current: 87836761; changing to 87840533. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558700753  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 87840533, current: 87837785; changing to 87840534. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558710428  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 87840534, current: 87838809; changing to 87840535. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558720066  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aost#0:1/aac @ 0x5ed8950240c0] Non-monotonic DTS; previous: 87840535, current: 87839833; changing to 87840536. This may result in incorrect timestamps in the output file.
frigate  | 2025-03-06 07:28:47.558729785  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 1.8 is not allocated
frigate  | 2025-03-06 07:28:47.558739666  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558749934  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] skip_data_stream_element: Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558759523  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558769319  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] Input buffer exhausted before END element found
frigate  | 2025-03-06 07:28:47.558779396  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Decoding error: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558789255  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 3.8 is not allocated
frigate  | 2025-03-06 07:28:47.558799222  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558808695  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aac @ 0x5ed895055a00] channel element 0.0 is not allocated
frigate  | 2025-03-06 07:28:47.558818583  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [aist#0:1/aac @ 0x5ed895042040] [dec:aac @ 0x5ed8950a5ec0] Error submitting packet to decoder: Invalid data found when processing input
frigate  | 2025-03-06 07:28:47.558828324  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [vost#0:0/copy @ 0x5ed895023780] Error submitting a packet to the muxer: No space left on device
frigate  | 2025-03-06 07:28:47.558839236  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   :     Last message repeated 1 times
frigate  | 2025-03-06 07:28:47.558849203  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Error muxing a packet
frigate  | 2025-03-06 07:28:47.558859704  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Task finished with error code: -28 (No space left on device)
frigate  | 2025-03-06 07:28:47.558870088  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Terminating thread with return code -28 (No space left on device)
frigate  | 2025-03-06 07:28:47.558880416  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [segment @ 0x5ed895024a00] Failure occurred when ending segment '/tmp/cache/carport@20250306072827-0800.mp4'
frigate  | 2025-03-06 07:28:47.558890305  [2025-03-06 07:28:47] ffmpeg.carport.record          ERROR   : [out#0/segment @ 0x5ed895025280] Error writing trailer: No space left on device
frigate  | 2025-03-06 07:28:47.558900620  [2025-03-06 07:28:47] watchdog.carport               INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-03-06 07:28:47.558910761  [2025-03-06 07:28:47] watchdog.carport               INFO    : Waiting for ffmpeg to exit gracefully...
```

### Relevant go2rtc log output

```shell
See above
```

### FFprobe output from your camera

```shell
ffprobe doesn't seem to be in the container
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /media/cctv_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "1935:1935" # RTMP feeds
    environment:
      - FRIGATE_RTSP_PASSWORD=foo
      - PLUS_API_KEY=bar
    logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "30"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [ 'gpu' ]
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink

**Comment by NickM-27** [comment]
is the device out of RAM / Frigate have some sort of memory limit on it?

**Reply by rgregg** [reply]
I don't think so - the machine has 64GB and it seems like most of it is available, just being used as cache?

```
               total        used        free      shared  buff/cache   available
Mem:           64075       11500         470         984       53809       52574
Swap:           8191           0        8191
```

**Reply by MitchWuk** [reply]
I can see that you're running a fair amount of cameras compared to your SHM size, have you tried increasing this to see if your issue persists?

**Comment by MitchWuk** [comment]
`/dev/mapper/large_disk_array-cctv   22T   17T  4.3T  80% /media/frigate`

Am I seeing this right? You're using 17TB of 22TB? What's your retention and Camera feeds? (Sorry, curiosity)

**EDIT**
Looking through your config, I presume they're reolink cameras running at 4-5MP?

**Reply by rgregg** [reply]
Yes - somewhere around an average of 2-4GB/hr of video depending on the camera, although I'm wondering if I should downsample the video since I don't really need super high resolution all the time. It's nice to have though.

**Comment by ReallyNotARussianSpy** [comment]
I am having the same issue. I have to restart Frigate every 24-48 hours. 4 cameras with SHM size at 256m. I can try doubling that but it seems like it should be enough and I don't have any bus errors.

**Comment by rgregg** [comment]
I've bumped my SHM up to 4GB just to see what happens - and I'm still getting out of space errors. I've never seen the space for SHM or /tmp/cache exceed about 500MB though. I think the issue might be upstream and getting caught by something that assumes the problem is out of disk space in ffmpeg. I generally have what looks like ffmpeg decoder errors show up in the logs first, before the out of disk space error occurs. Strangely I don't see any errors in the go2rtc log though, only in the frigate logs.

**Comment by MitchWuk** [comment]
So I had a similar issue, streams were crashing, very inconsistent UI, other little bits like that.

I increased the TempFS and SHM size on my docker container, even though the system was saying I needed 840MB, I actually ended up using 1.7GB (I upped it to 4GB on both).

EDIT

I also had the same thing of lots of Frigate errors, no Go2RTC errors

**Comment by distante** [comment]
Those logs sound like the ones I got here https://github.com/blakeblackshear/frigate/discussions/16974

@NickM-27 I know it said in the other discussion that it was due my cameras but I never had this problem until I updated to 0.15-1

**Comment by 0xjams** [comment]
I'm having the same problem.

I even tried to increase the size of tmpfs, but it only made the problem take longer to appear:

```
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 8000000000
```

With that size, it takes 24-36 hours to run out of tmp space.
