### DISCUSSION TITLE
[Config Support]: Issue with FFMPEG CPU on 2 cameras.

### DISCUSSION THREAD

**Discussion by MitchWuk** [blakeblackshear/frigate#16984] [Config Support] [answered]
### Describe the problem you are having

Recently I have setup Go2RTC after having many issues with the setting it up in the first place (I believe it was user error, after going through the cameras slowly and individually I don't seem to have a system crashing issue anymore).

I have noticed that 2 of the 5 cameras that are currently connected, seem to have a lot higher FFMPEG resources than the others:
Driveway: 130% (?)
Yard2: 64% (?)

_All at the time of writing this, screenshot may differ_

Please note, all cameras (except CarPark) are the same cameras, and all running the same firmware and same Encoding settings, Shutter settings, quality settings, IR settings, everything (branded cameras).

They are all running:
H.265
NTSC
4MP
25fps
SmartExIR

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    DrivewayCam_Main:
      - rtsp://##:554/user=##_password=##_channel=0_stream=0
      - ffmpeg:DrivewayCam_Main#video=264#audio=aac#hardware
    DrivewayCam_Detect:
      - rtsp://##:554/user=##_password=##_channel=0_stream=0
      - ffmpeg:DrivewayCam_Main#video=264#audio=aac#hardware
    CarParkCam_Main:
      - rtsp://##:##!@##:554/h264Preview_01_main
      - ffmpeg:CarParkCam_Main#video=264#audio=aac#hardware
    CarParkCam_Sub:
      - rtsp://##:##@10.0.0.201:554/h264Preview_01_sub
      - ffmpeg:CarParkCam_Sub#video=264#audio=aac#hardware
    StablesIndoors1_Main:
      - rtsp://##:554/user=##_password=##_channel=0_stream=0
      - ffmpeg:StablesIndoors1_Main#video=264#audio=aac#hardware
    StablesIndoors1_Sub:
      - rtsp://##:554/user=##_password=##_channel=0_stream=1
      - ffmpeg:StablesIndoors1_Sub#video=264#audio=aac#hardware
    StablesIndoors2_Main:
      - rtsp://##:554/user=##_password=##_channel=0_stream=0
      - ffmpeg:StablesIndoors2_Main#video=264#audio=aac#hardware
    StablesIndoors2_Sub:
      - rtsp://##:554/user=##_password=##_channel=0_stream=1
      - ffmpeg:StablesIndoors2_Sub#video=264#audio=aac#hardware
    Yard2_Main:
      - rtsp://##:554/user=##_password=##_channel=0_stream=0
      - ffmpeg:Yard2_Main#video=264#audio=aac#hardware

cameras:
  DrivewayCam: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/DrivewayCam_Main ##Main stream for the camera (Recording)
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://##:554/user=##_password=##_channel=0_stream=0
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: DrivewayCam_Main
    record: ##Recording Settings
      enabled: true
      retain:
        days: 7
    ##detect: ##Detection settings for quality and Framerate
    ##  width: 640
     ## height: 480
    ##  fps: 10
    motion:  ##Masking and Threshold to determine events
      threshold: 19
      contour_area: 7
      improve_contrast: false
      mask: 1,1,1,0.664,0.425,0.599,0.26,0.802,0.168,0.94,0.149,0.987
    objects: ##Object Setup
      track:
        - person
        - car
        - horse
        - dog
        - cat
        - truck
      filters:
        car:
          mask: 
            0.592,0.451,0.909,0.464,0.994,0.43,0.996,0.214,0.844,0.171,0.669,0.201,0.568,0.326,0.653,0.352
        truck:
          mask: 
            0.594,0.443,0.878,0.456,1,0.404,0.999,0.21,0.824,0.193,0.662,0.189,0.592,0.288,0.621,0.374
    zones:
      Driveway:
        coordinates: 
          0,1,0.064,1,0.285,0.677,0.372,0.578,0.456,0.513,0.517,0.504,0.59,0.556,0.604,0.422,0.631,0.353,0.551,0.332,0.614,0.25,0.657,0.19,0.631,0.129,0.512,0.172,0.398,0.164,0.311,0.194,0.149,0.323,0.059,0.427,0,0.409
        inertia: 3
        loitering_time: 1
        objects:
          - car
          - person
          - truck
  CarParkCam: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CarParkCam_Main ##Main stream for the camera (Recording)
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CarParkCam_Sub ##Sub stream for the camera (Live and Detection)
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: CarParkCam_Main
    record: ##Recording Settings
      enabled: true
      retain:
        days: 7
   ## detect: ##Detection settings for quality and Framerate
   ##   width: 640
   ##   height: 480
    ##  fps: 10
    motion: ##Masking and Threshold to determine events
      threshold: 20
      contour_area: 10
      improve_contrast: true
      mask: 
        0.204,0.295,0.171,0.37,0.113,0.395,0.087,0.374,0.075,0.307,0.072,0.238,0.107,0.207,0.147,0.207,0.178,0.211,0.19,0.211,0.207,0.268
    objects: ##Object Setup
      track:
        - person
        - horse
        - dog
        - cat
    zones:
      CarPark:
        coordinates: 
          0.365,0.31,0.417,0.364,0.458,0.434,0.463,0.474,0.479,0.509,0.525,0.55,0.568,0.572,0.601,0.596,0.632,0.646,0.661,0.721,0.715,0.867,0.773,0.957,0.769,0.999,0.002,0.996,0.086,0.398,0.155,0.385,0.182,0.376,0.195,0.349,0.203,0.325,0.206,0.306
        loitering_time: 0
        inertia: 3
        objects:
          - dog
          - cat
          - horse
      CarParkDrive:
        coordinates: 
          0.771,0.998,0.958,0.977,0.999,0.987,0.999,0.701,0.675,0.331,0.554,0.252,0.441,0.226,0.397,0.199,0.368,0.201,0.363,0.23,0.367,0.264,0.373,0.308,0.612,0.611
        loitering_time: 0

  StablesIndoors1: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/StablesIndoors1_Main ##Main stream for the camera (Recording)
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/StablesIndoors1_Sub ##Sub stream for the camera (Detection)
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: StablesIndoors1_Main
    record: ##Recording Settings
      enabled: true
      retain:
        days: 7
   ## detect: ##Detection settings for quality and Framerate
    ##  width: 640
   ##   height: 480
    ##  fps: 10
    objects:
      track:
        - plane
        - dog

  StablesIndoors2: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/StablesIndoors2_Main ##Main stream for the camera (Recording)
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: StablesIndoors2_Main
    record: ##Recording Settings
      enabled: true
      retain:
        days: 7
   ## detect: ##Detection settings for quality and Framerate
   ##   width: 640
    ##  height: 480
    ##  fps: 10
    objects:
      track:
        - plane
        - dog

  Yard2: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Yard2_Main ##Main stream for the camera (Recording)
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: Yard2_Main
    record: ##Recording Settings
      enabled: true
      retain:
        days: 7
   ## detect: ##Detection settings for quality and Framerate
    ##  width: 640
    ##  height: 480
    ##  fps: 10
    objects:
      track:
        - plane
        - dog
    motion: {}
    zones:
      Test:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 10
        loitering_time: 120


version: 0.15-1

##Notification Settings
notifications:
  enabled: true
  email: ##

semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
2025-03-06 15:02:28.570273955  [INFO] Preparing Frigate...
2025-03-06 15:02:28.768734086  [INFO] Starting Frigate...
2025-03-06 15:02:33.632360306  [2025-03-06 15:02:33] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-03-06 15:02:33.710198045  [2025-03-06 15:02:33] frigate.util.config            INFO    : frigate config does not need migration...
2025-03-06 15:02:33.883180454  [2025-03-06 15:02:33] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2025-03-06 15:02:49.985174636  [2025-03-06 15:02:49] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
2025-03-06 15:02:50.012748919  [2025-03-06 15:02:50] peewee_migrate.logs            INFO    : Starting migrations
2025-03-06 15:02:50.013122406  [2025-03-06 15:02:50] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-03-06 15:02:50.173374488  [2025-03-06 15:02:50] frigate.app                    INFO    : Recording process started: 503
2025-03-06 15:02:50.183023428  [2025-03-06 15:02:50] frigate.app                    INFO    : Review process started: 512
2025-03-06 15:02:50.186678176  [2025-03-06 15:02:50] frigate.app                    INFO    : go2rtc process pid: 114
2025-03-06 15:02:50.210828915  [2025-03-06 15:02:50] detector.cpu                   INFO    : Starting detection process: 519
2025-03-06 15:02:50.212465226  [2025-03-06 15:02:50] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2025-03-06 15:02:50.212490886  [2025-03-06 15:02:50] frigate.app                    INFO    : Embedding process started: 521
2025-03-06 15:02:50.253418108  [2025-03-06 15:02:50] frigate.app                    INFO    : Output process started: 542
2025-03-06 15:02:50.290452577  [2025-03-06 15:02:50] frigate.app                    INFO    : Camera processor started for DrivewayCam: 556
2025-03-06 15:02:50.315122736  [2025-03-06 15:02:50] frigate.app                    INFO    : Camera processor started for CarParkCam: 558
2025-03-06 15:02:50.340235493  [2025-03-06 15:02:50] frigate.app                    INFO    : Camera processor started for StablesIndoors1: 568
2025-03-06 15:02:50.341248802  [2025-03-06 15:02:50] frigate.app                    INFO    : Camera processor started for StablesIndoors2: 581
2025-03-06 15:02:50.356462895  [2025-03-06 15:02:50] frigate.app                    INFO    : Camera processor started for Yard2: 588
2025-03-06 15:02:50.358451012  [2025-03-06 15:02:50] frigate.app                    WARNING : The current SHM size of 512.0MB is too small, recommend increasing it to at least 542MB.
2025-03-06 15:02:50.377518167  [2025-03-06 15:02:50] frigate.app                    INFO    : Capture process started for DrivewayCam: 596
2025-03-06 15:02:50.395765947  [2025-03-06 15:02:50] frigate.app                    INFO    : Capture process started for CarParkCam: 615
2025-03-06 15:02:50.456621869  [2025-03-06 15:02:50] frigate.app                    INFO    : Capture process started for StablesIndoors1: 636
2025-03-06 15:02:50.478553047  [2025-03-06 15:02:50] frigate.app                    INFO    : Capture process started for StablesIndoors2: 648
2025-03-06 15:02:50.501327011  [2025-03-06 15:02:50] frigate.app                    INFO    : Capture process started for Yard2: 654
2025-03-06 15:02:50.773061928  [2025-03-06 15:02:50] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-03-06 15:02:51.072560781  [2025-03-06 15:02:51] frigate.api.fastapi_app        INFO    : FastAPI started
```

### Relevant go2rtc log output

```shell
2025-03-06 15:02:28.544374604  [INFO] Preparing new go2rtc config...
2025-03-06 15:02:29.461339175  [INFO] Starting go2rtc...
2025-03-06 15:02:29.665458833  15:02:29.665 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-03-06 15:02:29.665467733  15:02:29.665 INF config path=/dev/shm/go2rtc.yaml
2025-03-06 15:02:29.666596234  15:02:29.666 INF [rtsp] listen addr=:8554
2025-03-06 15:02:29.666694586  15:02:29.666 INF [api] listen addr=:1984
2025-03-06 15:02:29.666951451  15:02:29.666 INF [webrtc] listen addr=:8555/tcp
2025-03-06 15:02:38.571013164  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{
  "cameras": {
    "DrivewayCam": {
      "camera_fps": 5,
      "process_fps": 0.2,
      "skipped_fps": 4.9,
      "detection_fps": 1.8,
      "detection_enabled": true,
      "pid": 556,
      "capture_pid": 596,
      "ffmpeg_pid": 614,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "CarParkCam": {
      "camera_fps": 5,
      "process_fps": 0.3,
      "skipped_fps": 4.7,
      "detection_fps": 1.8,
      "detection_enabled": true,
      "pid": 558,
      "capture_pid": 615,
      "ffmpeg_pid": 635,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "StablesIndoors1": {
      "camera_fps": 5.1,
      "process_fps": 0.4,
      "skipped_fps": 4.8,
      "detection_fps": 1.9,
      "detection_enabled": true,
      "pid": 568,
      "capture_pid": 636,
      "ffmpeg_pid": 653,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "StablesIndoors2": {
      "camera_fps": 5.1,
      "process_fps": 0.3,
      "skipped_fps": 4.8,
      "detection_fps": 1.8,
      "detection_enabled": true,
      "pid": 581,
      "capture_pid": 648,
      "ffmpeg_pid": 655,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "Yard2": {
      "camera_fps": 5,
      "process_fps": 0.1,
      "skipped_fps": 4.9,
      "detection_fps": 1.8,
      "detection_enabled": true,
      "pid": 588,
      "capture_pid": 654,
      "ffmpeg_pid": 664,
      "audio_rms": 0,
      "audio_dBFS": 0
    }
  },
  "detectors": {
    "cpu": {
      "inference_speed": 126.28,
      "detection_start": 1741273455.84379,
      "pid": 519
    }
  },
  "detection_fps": 9.1,
  "cpu_usages": {
    "frigate.full_system": {
      "cpu": "37.7",
      "mem": "19.4"
    },
    "1": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
    },
    "15": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6-linux-init-shutdownd"
    },
    "16": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
    },
    "24": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-fdholder"
    },
    "25": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate"
    },
    "26": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync"
    },
    "27": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-healthcheck"
    },
    "28": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync-log"
    },
    "29": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc"
    },
    "30": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-log"
    },
    "31": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate-log"
    },
    "32": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx-log"
    },
    "33": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx"
    },
    "34": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-oneshot-runner"
    },
    "45": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
    },
    "46": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
    },
    "87": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
    },
    "88": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
    },
    "89": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
    },
    "90": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
    },
    "114": {
      "cpu": "24.8",
      "cpu_average": "20",
      "mem": "0.2",
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
    },
    "123": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user go2rtc-healthcheck"
    },
    "124": {
      "cpu": "1.3",
      "cpu_average": "14",
      "mem": "3.5",
      "cmdline": "python3 -u -m frigate"
    },
    "130": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: master process nginx"
    },
    "172": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "173": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: worker process"
    },
    "174": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: worker process"
    },
    "175": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: worker process"
    },
    "176": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: cache manager process"
    },
    "309": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user certsync"
    },
    "503": {
      "cpu": "4.9",
      "cpu_average": "2",
      "mem": "1.4",
      "cmdline": "frigate.recording_manager"
    },
    "512": {
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "1.3",
      "cmdline": "frigate.review_segment_manager"
    },
    "519": {
      "cpu": "246.5",
      "cpu_average": "233",
      "mem": "1.4",
      "cmdline": "frigate.detector.cpu "
    },
    "521": {
      "cpu": "0.3",
      "cpu_average": "3",
      "mem": "4.3",
      "cmdline": "frigate.embeddings_manager"
    },
    "542": {
      "cpu": "3.1",
      "cpu_average": "2",
      "mem": "1.3",
      "cmdline": "frigate.output       "
    },
    "556": {
      "cpu": "15.8",
      "cpu_average": "16",
      "mem": "1.6",
      "cmdline": "frigate.process:DrivewayCam"
    },
    "557": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "558": {
      "cpu": "3.4",
      "cpu_average": "2",
      "mem": "1.3",
      "cmdline": "frigate.process:CarParkCam"
    },
    "568": {
      "cpu": "4.9",
      "cpu_average": "3",
      "mem": "1.4",
      "cmdline": "frigate.process:StablesIndoors1"
    },
    "581": {
      "cpu": "6.8",
      "cpu_average": "9",
      "mem": "1.6",
      "cmdline": "frigate.process:StablesIndoors2"
    },
    "588": {
      "cpu": "5.1",
      "cpu_average": "3",
      "mem": "1.5",
      "cmdline": "frigate.process:Yard2"
    },
    "595": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "596": {
      "cpu": "11.2",
      "cpu_average": "9",
      "mem": "2.8",
      "cmdline": "frigate.capture:DrivewayCam"
    },
    "614": {
      "cpu": "114.6",
      "cpu_average": "119",
      "mem": "1.0",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://##:554/user=##_password=##_channel=0_stream=0 -r 5 -vf fps=5,scale=3840:2160 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "615": {
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "1.3",
      "cmdline": "frigate.capture:CarParkCam"
    },
    "616": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 800x448 -i pipe: -threads 1 -f mpegts -s 1285x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "627": {
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/DrivewayCam_Main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/DrivewayCam@%Y%m%d%H%M%S%z.mp4"
    },
    "628": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "635": {
      "cpu": "2.5",
      "cpu_average": "1",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/CarParkCam_Sub -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "636": {
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "1.3",
      "cmdline": "frigate.capture:StablesIndoors1"
    },
    "637": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "648": {
      "cpu": "5.7",
      "cpu_average": "3",
      "mem": "1.9",
      "cmdline": "frigate.capture:StablesIndoors2"
    },
    "649": {
      "cpu": "1.7",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/CarParkCam_Main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/CarParkCam@%Y%m%d%H%M%S%z.mp4"
    },
    "650": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "653": {
      "cpu": "5.2",
      "cpu_average": "4",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/StablesIndoors1_Sub -r 5 -vf fps=5,scale=800:448 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "654": {
      "cpu": "5.0",
      "cpu_average": "3",
      "mem": "1.9",
      "cmdline": "frigate.capture:Yard2"
    },
    "655": {
      "cpu": "59.2",
      "cpu_average": "58",
      "mem": "0.6",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/StablesIndoors2_Main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/StablesIndoors2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "664": {
      "cpu": "62.6",
      "cpu_average": "61",
      "mem": "0.5",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/Yard2_Main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Yard2@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=2560:1440 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "683": {
      "cpu": "1.4",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/StablesIndoors1_Main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/StablesIndoors1@%Y%m%d%H%M%S%z.mp4"
    },
    "1175": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 60"
    },
    "1602": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 30s"
    }
  },
  "service": {
    "uptime": 85,
    "version": "0.15.0-cea210d",
    "latest_version": "0.15.0",
    "storage": {
      "/media/frigate/recordings": {
        "total": 1004268.6,
        "used": 754002.5,
        "free": 208371.7,
        "mount_type": "ext4"
      },
      "/media/frigate/clips": {
        "total": 1004268.6,
        "used": 754002.5,
        "free": 208371.7,
        "mount_type": "ext4"
      },
      "/tmp/cache": {
        "total": 953.7,
        "used": 62.8,
        "free": 890.9,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 512,
        "used": 423.6,
        "free": 88.4,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {

    },
    "last_updated": 1741273455
  },
  "processes": {
    "recording": {
      "pid": 503
    },
    "review_segment": {
      "pid": 512
    },
    "go2rtc": {
      "pid": 114
    },
    "embeddings": {
      "pid": 521
    }
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
(Please let me know if this is required.)
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/5271e5fb-fd01-4d38-b0de-53770e7dd73c)

### Any other information that may be helpful

Please note, I have changed the StablesIndoors2 Camera to be the same stream, and noticed that this is idling around FFMPEG 60%.

My concern is that I would like a higher quality detection stream, as when using the sub stream, it is either missing detections, or thinks a horse is a dog....

I have noticed that there is FFMPEG 7.1 out now, would it be worth setting this up and then adding this into my docker compose file? 

Can you please also let me know, if I can just use _sudo docker-compose restart frigate_, will this then update my docker container? I have been using docker-compose down and docker-compose up for this, but I don't want to have to rebuild users etc... as people are using this (referencing the error in the SHM size in the log)
