### DISCUSSION TITLE
[Support]: amggpu crash when using rocm in docker

### DISCUSSION THREAD

**Discussion by foxdvd** [blakeblackshear/frigate#16982] [Hardware Acceleration Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

GPU and other components are good, stress test pass ok. 
I tried it in latest Debian, Arch, Ubuntu - no luck.

```
GPU: AMD Radeon MI50 16GB
CPU: E5-2690 v2 x 2
RAM: 256GB DDR3
SSD: 1T SATA x 6
MB: Supermicro
```

### Steps to reproduce

1. Start docker container
2. Look dmesg & docker logs

### Version

latest

### Frigate config file

```yaml
mqtt:
enabled: false

record:
enabled: true
retain:
days: 7
mode: motion
alerts:
retain:
days: 14
pre_capture: 12
post_capture: 24
detections:
retain:
days: 14
pre_capture: 12
post_capture: 24
ffmpeg:
hwaccel_args: preset-vaapi

detectors:
rocm:
type: rocm

model:
model_type: yolonas
path: /config/model_cache/yolo_nas_l.onnx
input_pixel_format: rgb
width: 320
height: 320
  input_tensor: nchw

objects:
track:
  - person
    - cat
    - dog


detect:
fps: 5
enabled: true
min_initialized: 3
max_disappeared: 25
annotation_offset: 0
stationary:
interval: 50
threshold: 50
max_frames:
default: 3000
objects:
person: 2000
cat: 700
dog: 700

camera_kitchen:
enabled: true
ffmpeg:
inputs:
- path: rtsp://user:password@192.168.5.5:554/
roles:
- detect
- record
detect:
enabled: true
width: 1920
height: 1080
```

### docker-compose file or Docker CLI command

```yaml
services:
frigate:
ipc: host
security_opt:
- seccomp:unconfined
container_name: frigate
privileged:
restart: no
    image: ghcr.io/blakeblackshear/frigate:stable-rocm
shm_size: "8096mb"
devices:
- /dev/dri
- /dev/kfd
volumes:
- /etc/localtime:/etc/localtime:ro
- /opt/frigate/config:/config
- /opt/frigate/storage:/media/frigate
- type: tmpfs
target: /tmp/cache
tmpfs:
size: 1000000000
ports:
- "8971:8971"
#        - "8554:8554" # RTSP feeds
#        - "8555:8555/tcp" # WebRTC over tcp
#        - "8555:8555/udp" # WebRTC over udp
environment:
FRIGATE_RTSP_PASSWORD: "password"
LIBVA_DRIVER_NAME: "radeonsi"
```

### Relevant Frigate log output

```shell
...
2025-03-06 14:47:09.717086519  [2025-03-06 14:47:09] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-03-06 14:47:09.892904737  [2025-03-06 14:47:09] frigate.api.fastapi_app        INFO    : FastAPI started
2025-03-06 14:47:15.004280768  [INFO] Starting go2rtc healthcheck service...
2025-03-06 14:47:21.645925672  [2025-03-06 14:47:09] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: loading parsed model from /config/model_cache/yolo_nas_l.mxr
2025-03-06 14:47:21.646542326  [2025-03-06 14:47:21] frigate.detectors.plugins.rocm INFO    : AMD/ROCm: model loaded
2025-03-06 14:47:28.189527407  Memory access fault by GPU node-2 (Agent handle: 0x11558c60) on address 0x460e40c000. Reason: Page not present or supervisor privilege.
...
```

### Relevant go2rtc log output

```shell
---
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

HiWatch (FHD)

### Screenshots of the Frigate UI's System metrics pages

---

### Any other information that may be helpful

```[ +23.281036] amdgpu 0000:0c:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:8 pasid:32794)
[  +0.000016] amdgpu 0000:0c:00.0: amdgpu:  for process frigate.detecto pid 15045 thread frigate.detecto pid 15045)
[  +0.000004] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x000000460e40c000 from IH client 0x1b (UTCL2)
[  +0.000008] amdgpu 0000:0c:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00801031
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:       Faulty UTCL2 client ID: TCP (0x8)
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:       MORE_FAULTS: 0x1
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:       WALKER_ERROR: 0x0
[  +0.000001] amdgpu 0000:0c:00.0: amdgpu:       PERMISSION_FAULTS: 0x3
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:       MAPPING_ERROR: 0x0
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:       RW: 0x0
[  +0.000010] amdgpu 0000:0c:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:8 pasid:32794)
[  +0.000004] amdgpu 0000:0c:00.0: amdgpu:  for process frigate.detecto pid 15045 thread frigate.detecto pid 15045)
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x000000460e40c000 from IH client 0x1b (UTCL2)
[  +0.000005] amdgpu 0000:0c:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:8 pasid:32794)
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:  for process frigate.detecto pid 15045 thread frigate.detecto pid 15045)
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x000000460e40c000 from IH client 0x1b (UTCL2)
[  +0.000005] amdgpu 0000:0c:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:8 pasid:32794)
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:  for process frigate.detecto pid 15045 thread frigate.detecto pid 15045)
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x000000460e40c000 from IH client 0x1b (UTCL2)
[  +0.000004] amdgpu 0000:0c:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:8 pasid:32794)
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:  for process frigate.detecto pid 15045 thread frigate.detecto pid 15045)
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x000000460e40c000 from IH client 0x1b (UTCL2)
[  +0.000004] amdgpu 0000:0c:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:24 vmid:8 pasid:32794)
[  +0.000003] amdgpu 0000:0c:00.0: amdgpu:  for process frigate.detecto pid 15045 thread frigate.detecto pid 15045)
[  +0.000002] amdgpu 0000:0c:00.0: amdgpu:   in page starting at address 0x000000460e40c000 from IH client 0x1b (UTCL2)
```
