### DISCUSSION TITLE
[Detector Support]: Frigate v0.15.1 not support Hailo8L firmware 4.20.0

### DISCUSSION THREAD

**Discussion by monpelaud** [blakeblackshear/frigate#16991] [Detector Support] [answered]
### Describe the problem you are having

Hello,
I am newbees to Frigate and I am experiencing a firmware version issue with the Hailo8L detector.
Message in the logs:
[HailoRT] [warning] Unsupported firmware operation. Host: 4.19.0, Device: 4.20.0
Best Regards

### Version

0.15.1

### Frigate config file

```yaml
mqtt:
  enabled: false

database:
  path: /data/db/frigate.db

cameras:
  cam03:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:888/rtsp
          roles:
            - record
            - detect
    onvif:
      host: 192.168.1.42
      port: 88
      user: xxxxx
      password: xxxxxxx
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720

objects:
  track:
    - person

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model_path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: bgr

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate-hailo
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:0.15.0-h8l
    shm_size: 1024mb
    devices:
      - /dev/hailo0:/dev/hailo0
    volumes:
      - ./config:/config
      - ./data/db/:/data/db
      - ./data/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
```

### Relevant Frigate log output

```shell
[HailoRT] [warning] Unsupported firmware operation. Host: 4.19.0, Device: 4.20.0
[HailoRT] [error] Operation 51 is not allowed when FW version in not supported. Host supported FW version is 4.19.0
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

none
