### DISCUSSION TITLE
Mac Safari incompatible with Frigate audio?

### DISCUSSION THREAD

**Discussion by FS1961** [blakeblackshear/frigate#17005] [Config Support]
Hello - 

I've been chasing my tail (again) thinking my cameras/Frigate config was not correct as I couldn't hear the audio live or recorded.  Tried a different browser, MS Edge, and it works!

Is Mac Safari incompatible or are there settings somewhere?

Also having the same problem on my iPhone 13 in the HA app.  I have Frigate loaded as an add-on but I get no sound there either.

Help! :) Thanks!

<img width="756" alt="Screenshot 2025-03-07 at 2 19 01 PM" src="https://github.com/user-attachments/assets/4d897111-ded9-4bda-996e-7bb1a1a18532" />

**Comment by constantm** [comment]
If anybody comes across this, I was able to get sound working on iOS/Safari by transcoding the go2rtc stream audio to AAC.

```
go2rtc:
  streams:
    kantoor:
      - rtsp://user:dockerhost@192.168.1.193:554/stream1
      - ffmpeg:kantoor#audio=aac
```
