### DISCUSSION TITLE
[Support]:  4k footage playback buffers for 20-30 seconds. Is there a problem with my config, or just the way it is?

### DISCUSSION THREAD

**Discussion by partytimeexcellent** [blakeblackshear/frigate#17018] [General Support]
### Describe the problem you are having

I have a 4k camera (Empire Tech Color 4k). Loading the livestream is just a few seconds, but playing back saved clips takes 20-30 seconds of buffering before playback begins. The footage is all stored on a fast NVME drive. It seems like something must not be working correctly because when I was using Scrypted, the same footage would play back almost instantly. There are no errors on the logs. Just wondering why this happens.

Seems like it would be a good feature to allow recording at multiple resolutions, one for max quality archive, and a sub recording for instant playback on remote devices.

### Version

0.15.0

### What browser(s) are you using?

Safari 18.0.1, and others

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.0.0.101
  user: frigate
  password: x

#audio:
#  enabled: true

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264  
  output_args:
    record: preset-record-generic-audio-copy
#  hwaccel_args: preset-intel-qsv-h264
#  global_args: -hide_banner -loglevel warning -threads 2 -bsf:v dump_extra
#  hwaccel_args: preset-vaapi
#  output_args:
#    record: preset-record-generic-audio-aac
#  hwaccel_args:
#    - -bsf:v
#    - dump_extra
#    - -hwaccel_output_format
#    - qsv
#    - -c:v
#    - h264_qsv

detectors:
  coral:
    type: edgetpu
    device: pci
#  ov:
#    type: openvino
#    device: GPU

#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


go2rtc:
  ffmpeg:
  streams:
    Driveway:
      - rtsp://u&p@10.0.20.10/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Driveway#audio=opus
    Driveway_sub:
      - rtsp://u&p@10.0.20.10/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:Driveway_sub#audio=opus
    South-Side:
      - rtsp://u&p@10.0.20.13:554/stream1#video=copy#audio=copy#audio=aac
#      - ffmpeg:South-Side#audio=aac
    South-Side_sub:
      - rtsp://u&p@10.0.20.13:554/stream2#video=copy#audio=copy#audio=aac
#      - ffmpeg:South-Side_sub#audio=aac
    Doorbell:
      - ffmpeg:https://10.0.20.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&u&p#video=copy#audio=copy#audio=opus
      - rtsp://u&p@10.0.20.12:554/h264Preview_01_sub
    Doorbell_sub:
      - ffmpeg:https://10.0.20.12/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=u&p
#    Doorbell:
#      - rtsp://u&p@10.0.20.12:554/h264Preview_01_main
#      - ffmpeg:Doorbell#audio=opus
#    Doorbell_sub:
#      - rtsp://u&p@10.0.20.12:554/h264Preview_01_sub
#      - ffmpeg:Doorbell_sub#audio=opus
    Living-Room:
      - rtsp://u&p@10.0.20.11/ch0
      - ffmpeg:Living-Room#audio=opus
    Living-Room_sub:
      - rtsp://u&p@10.0.20.11/ch1
      - ffmpeg:Living-Room_sub#audio=opus
cameras:
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
    review:
      alerts:
        required_zones: yard
    detect:
#      enabled: false
      fps: 5
      width: 1280
      height: 720
      annotation_offset: -500
    zones:
      yard:
        coordinates: 0.001,0.28,0.175,0.226,0.364,0.199,0.563,0.198,0.679,0.208,0.999,0.474,1,1,0,1
        loitering_time: 0
    motion:
      mask: 0.725,0.04,0.856,0.154,1,0.205,1,0,0.724,0
    objects:
      mask: 0.659,0.105,0.705,0.109,0.704,0.212,0.658,0.209

  South-Side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/South-Side_sub
#          input_args: preset-rtsp-restream
          input_args: -rtsp_transport tcp -timeout 30000000
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/South-Side
          input_args: preset-rtsp-restream
          roles:
            - record
    review:
      alerts:
        required_zones: yard
    detect:
#      enabled: false
      fps: 5
      width: 1280
      height: 720
      annotation_offset: -1800
    zones:
      yard:
        coordinates: 
          1,0.464,0.786,0.3,0.584,0.208,0.396,0.147,0.314,0.213,0.292,0.289,0.149,0.229,0.118,0.229,0.087,0.244,0,0.296,0,1,1,1
        loitering_time: 0
        inertia: 3
    motion:
      mask:
        - 0.412,0,0.354,0.045,0.163,0.092,0.134,0.122,0.09,0.126,0.053,0.099,0.065,0
        - 1,0,0.78,0,1,0.323,1,0.323

  Doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell_sub #?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Doorbell #?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
    review:
      alerts:
        required_zones: yard
    detect:
#      enabled: false
      fps: 5
      width: 640
      height: 480
      annotation_offset: -1000
    zones:
      yard:
        coordinates: 0,0.605,0.241,0.599,0.43,0.608,0.661,0.606,0.882,0.593,1,0.589,1,1,0,1
        inertia: 3
        loitering_time: 0
    motion:
      mask: 0.635,0.019,0.967,0.018,0.965,0.052,0.636,0.053

  Living-Room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Living-Room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Living-Room
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
#      enabled: false
      fps: 5
      width: 640
      height: 360
    motion:
      mask: 0.224,0.051,0.007,0.051,0.008,0,0.223,0

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 30
      mode: active_objects
  detections:
    retain:
      days: 30
      mode: active_objects
  preview:
    quality: medium ## Options are: very_low, low, medium, high, very_high

#  sync_recordings: True. ### Enale to fix database when recordings are missing
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 30
  quality: 70

version: 0.15-1
notifications:
  enabled: 'true'
  email:
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Frigate stats

```json
none
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

Empire Tech Color 4k
