### DISCUSSION TITLE
[Config Support]: Has “events” been replaced?

### DISCUSSION THREAD

**Discussion by albotroz** [blakeblackshear/frigate#17015] [Config Support] [answered]
### Describe the problem you are having

Has the “events” sub-area been replaced or deleted in the “record” area?

Because I no longer see it in the Frigate full-config: https://docs.frigate.video/configuration/reference

Probably renamed in “alerts”?

### Version

0.14

### Frigate config file

```yaml
detect:
      width: 640
      height: 352
      fps: 5
      enabled: true

    record:
      enabled: true
      expire_interval: 60
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: motion

    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: false
      crop: false
#      required_zones: []
      retain:
        default: 1
#        objects:
#          person: 2
      quality: 100
```

### Relevant Frigate log output

```shell
...
```

### Relevant go2rtc log output

```shell
...
```

### Operating system

Proxmox

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
...
```

### Object Detector

Coral

**Comment by NickM-27** [comment]
What do you mean by events sub area?

**Comment by hawkeye217** [comment]
You noted in your post that you're running Frigate 0.14. The reference config at docs.frigate.video is for the latest stable version of Frigate, 0.15. What you have in your config is correct for 0.14.

**Comment by albotroz** [comment]
Thanks. 

Yes, I have just tested it. It is due to version 0.14, which uses “events” instead of “alerts”.

I also noticed in new frigate Full Reference Config “detections” in the “record” area
Was this added with 0.15?

I have tried to add it in 0.14 and then errors appeared immediately.

```
cameras:
  front:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        # Stream Low Res
        - path: rtsp://127.0.0.1:8554/front_sub
          roles:
            - detect
        # Stream High Res
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record

    detect:
      width: 640
      height: 360
      fps: 4
      enabled: true

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 2
        mode: all
      preview:
        quality: medium
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: motion
      detections:
        pre_capture: 5
        post_capture: 5
        retain:
          days: 2
          mode: motion
```

Error:
```
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 245, in config_save
    FrigateConfig.parse_raw(new_config)
  File &#34;/opt/frigate/frigate/config.py&#34;, line 1665, in parse_raw
    return cls.model_validate(config)
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for FrigateConfig
cameras.front.record.detections
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;pre_capture&#39;: 5, &#39;post_...&#39;: 2, &#39;mode&#39;: &#39;motion&#39;}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
```

I would like to be able to access older versions of the Full Reference Config. I often stick with older versions and then look at Reference config to customize sometimes.
Otherwise I get confusing errors like now, which only occur because the Full Reference Config has been updated for the latest Frigate version.
