### DISCUSSION TITLE
Frigate API Export Video

### DISCUSSION THREAD

**Discussion by jwill2385** [blakeblackshear/frigate#17014] [Ask A Question]
I noticed with the latest Frigate version 0.15 the export video naming convention has changed. Previously videos would export as cameraname_starttime_endtime.mp4. Now videos export as camername_id with a random ID at the end. Is there anyway to change this id at the end to go back to the time naming convention? We relied on this framework to do our data processing and align times.

Currently we tried a workaround by waiting for the file to arrive in local storage after API request and then rename but the files take a while to appear. It would be more streamlined to just have the files renamed initially as the previous version of frigate did.

` def export_video_feed(camera, start_timestamp, end_timestamp):
    url = f'{FRIGATE_API_URL}/api/export/{camera}/start/{start_timestamp}/end/{end_timestamp}'
    headers = {'Content-Type': 'application/json'}
    response = requests.post(url, headers=headers, json={})  # Send empty JSON body
    response.raise_for_status()
    
    export_id = response.json().get("export_id") # This is the new export ID of file with latest 0.15.0 frigate update
    print(f"Export started: {export_id}")

    # Expected filename format from Frigate
    expected_filename = f"{export_id}.mp4"
    expected_filepath = os.path.join(EXPORTS_DIR, expected_filename)

    # Wait for file to appear in exports folder
    # Wait for the exact file to appear (polling every 2 seconds, max 40 seconds)
    timeout = 40
    elapsed = 0
    while not os.path.exists(expected_filepath):
        time.sleep(2)
        elapsed += 2
        if elapsed >= timeout:
            print(f"Error: Export file for {camera} not found after {timeout} seconds!")
            return

    # Rename file with correct timestamp format
    #convert to YY_MONTH_DAY_HOUR_MINUTE
    # Convert timestamps to EST
    start_time_est = datetime.datetime.utcfromtimestamp(start_timestamp).replace(tzinfo=pytz.utc).astimezone(est)
    end_time_est = datetime.datetime.utcfromtimestamp(end_timestamp).replace(tzinfo=pytz.utc).astimezone(est)

    # Format as YYYY_MM_DD_HH_MM
    start_time_str = start_time_est.strftime("%Y_%m_%d_%H_%M")
    end_time_str = end_time_est.strftime("%Y_%m_%d_%H_%M")

    # Create new filename
    new_filename = f"{camera}_{start_time_str}__{end_time_str}.mp4"
    print(new_filename)
    # new_filename = f"{camera}_{start_timestamp}_{end_timestamp}.mp4"
    new_filepath = os.path.join(EXPORTS_DIR, new_filename)

    # Ensure the script has permission to rename
    os.chmod(expected_filepath, 0o777)

    os.rename(expected_filepath, new_filepath)
    print(f"Renamed: {expected_filename} → {new_filename}")
  

    return new_filename`

**Comment by NickM-27** [comment]
This was a 0.14 change, but in any case this has been corrected in 0.16

**Reply by jwill2385** [reply]
Oh interesting how do i launch version 0.16 with tensorrt for GPU usage? Currently I have it running [stable](image: ghcr.io/blakeblackshear/frigate:stable-tensorrt)

Here's full docker-compose file

```
# version: "3.9"
services:
  frigate:
    container_name: frigate
    # runtime: nvidia
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "512mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/video11:/dev/video11 # For Raspberry Pi 4B
    #   - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/vsironhorse/Docker/Frigate/config:/config
      - /home/vsironhorse/Docker/Frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    

```
