### DISCUSSION TITLE
Object detection in homeassistant

### DISCUSSION THREAD

**Discussion by mohaje83** [blakeblackshear/frigate#17032] [Ask A Question] [answered]
Hello all

I have been trying to setup Frigate object detection and get a notification in homeassistant, as soon a person is detected in my driveway. Have been watching YouTube videos and read forums. 

I got to a point where it work, I get notifications. But I only want notification inside a desired zone. Basically I don't want frigate to detect anything outside the zone. However I am getting notifications for entire camera area, not matter what I do. I am certain my zone is correct, have the same problem with other cameras, and I can see in Frigate UI it looks correct. Can anyone point me in the right direction?

Frigate config:

```
mqtt:
  host: mosquitto
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    garage_outside_high: rtsp://frigate:XXXX@192.168.1.23:554/Streaming/Channels/101
    garage_outside_low: rtsp://frigate:XXXX@192.168.1.23:554/Streaming/Channels/102
    
cameras:
  GarageOutside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_outside_high
          roles:
            - detect
    detect:
      width: 2560
      height: 1440
      fps: 5

    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - driveway
    zones:
      driveway_zone:
        coordinates: 
          0.008,0.103,0.371,0.02,0.378,0.087,0.474,0.109,0.476,0.153,0.991,0.539,0.993,0.992,0.004,0.995
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - umbrella
          - car
    objects:
      track:
        - person
        - umbrella
        - car
      filters:
        person:
          min_score: 0.75

    review:
      alerts:
        required_zones: driveway_zone
      detections:
        required_zones: driveway_zone
    motion: {}
  

version: 0.15-1
```
Homeassistant automation:
````
alias: Persons at driveway
description: ""
triggers:
  - type: occupied
    device_id: 2a3e4c74fbfc3569a2a1c6527cdcb0da
    entity_id: f698027c41bf9ad95ca7144d631fabe8
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 2
conditions: []
actions:
  - action: notify.myphone
    metadata: {}
    data:
      message: Person detected at garage
mode: single
````

Thanks in advance
