### DISCUSSION TITLE
Expand current HA API to include Media?

### DISCUSSION THREAD

**Discussion by danlo315** [blakeblackshear/frigate#17038] [Ideas]
Hello,

I am going down the rabbit hole of utilizing Review vs Events in non time sensitive situations.  For example, I have a HA automation that is triggered by a doorbell/front porch camera event (since it's time sensitive); people walking up/down the driveway is not as important but I'd still like to review the relevant video segments.  I am able to ingest the frigate/reviews topic and construct the notification information (I use Telegram for that):

![image](https://github.com/user-attachments/assets/b13386f9-63aa-4e55-a824-227f477ce91c)

The preview gif is great as an at-a-glance notification, but I would love to be able to download the high res/non timelapsed video.  Frigate's HA API is focused on events (https://docs.frigate.video/integrations/home-assistant/) with only one exception to pull the preview gif, and I am making a proposal to add additional endpoints that are available in the general Frigate API.  In my specific use case, I would like to use the Recording Clip API endpoint, so I can construct the URL via the start/end time of the frigate/reviews topic:

https://docs.frigate.video/integrations/api/recording-clip-camera-name-start-start-ts-end-end-ts-clip-mp-4-get

Thoughts?

**Comment by hawkeye217** [comment]
You can use the full Frigate API directly, you just need open the port via your docker compose or the HA addon config if you're using the addon and provide secure external access to your instance. We don't have plans to create duplicate API routes for HA users.

**Reply by danlo315** [reply]
The issue with using full Frigate API is authentication (and rightfully so); I imagine that I would need to figure out a way to pass in the bearer token as part of the href to properly authenticate (my Telegram notification message is just markdown HTML).  My proposal is to expand (and not fully duplicate) the HA API feature set, as I think the detect/alert functionalities (in addition to tracked objects) are very useful.

**Reply by hawkeye217** [reply]
There is no authorization on the API in 0.15, so you'll need to use a proxy, VPN, or tunnel of some kind.

**Reply by NickM-27** [reply]
> There is no authorization on the API in 0.15

There is authorization on the API in 0.15 to be clear, I think you may be thinking of user roles or something ese

**Reply by NickM-27** [reply]
In most cases one of the event IDs that are included as part of the review item will work for the clip video

**Reply by hawkeye217** [reply]
> > There is no authorization on the API in 0.15
> 
> There is authorization on the API in 0.15 to be clear, I think you may be thinking of user roles or something ese

Ah yes, my head has been elsewhere :)

**Reply by danlo315** [reply]
@NickM-27 - thanks for the feedback, and I agree that majority of the time, an event ID clip associated with the review will work.  Here's an example where there are multiple events:

![image](https://github.com/user-attachments/assets/39ea0837-427b-459a-9112-8e5438f4b6d0)

And the MQTT message behind this Telegram message:

```
  type: end
    before:
      id: 1741556057.752591-pyfkm6
      camera: driveway
      start_time: 1741556057.752591
      end_time: null
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-driveway-1741556057.752591-pyfkm6.webp
      data:
        detections:
          - 1741556057.334311-x8ch58
          - 1741556117.287553-t3x0cs
          - 1741556190.507333-g8ga1w
          - 1741556142.874166-nw2o79
          - 1741556066.74641-9fz6qf
          - 1741556154.288345-l3s9o8
        objects:
          - person
          - dog
        sub_labels: []
        zones:
          - f_front_yard
          - f_driveway
        audio: []
    after:
      id: 1741556057.752591-pyfkm6
      camera: driveway
      start_time: 1741556057.752591
      end_time: 1741556196.283872
      severity: alert
      thumb_path: /media/frigate/clips/review/thumb-driveway-1741556057.752591-pyfkm6.webp
      data:
        detections:
          - 1741556057.334311-x8ch58
          - 1741556117.287553-t3x0cs
          - 1741556190.507333-g8ga1w
          - 1741556142.874166-nw2o79
          - 1741556066.74641-9fz6qf
          - 1741556154.288345-l3s9o8
        objects:
          - person
          - dog
        sub_labels: []
        zones:
          - f_front_yard
          - f_driveway
        audio: []
```

This review has 6 events associated.  I'm walking my dog, moving back and forth between different zones.  These clips represent multiple events associated with different zones and labels, and individually they don't paint the entire picture.  My notification message allows me to click in on different events (I construct the href based on event ID and utilize the HA API endpoint), but the one that consolidates them all is the preview GIF of the review.  For now, I'm just using the internal Frigate URL (host:5000/api/<camera>/start/:start/end/:end/clip.mp4) so I can pull the review clip, but obviously that will only work when I'm inside my network or I VPN back home.  I am hesitant to reverse proxy port 5000 to the outside world.
