### DISCUSSION TITLE
Why can't I get my coral usb accelerator to work in my raspberry pi 4 when I run frigate ?[Detector Support]:

### DISCUSSION THREAD

**Discussion by mmaaligema** [blakeblackshear/frigate#17037] [Detector Support]
### Describe the problem you are having

1 843 / 5 000
Hi ! Why can't I get my coral usb accelerator to work in my raspberry pi 4 when I run frigate ?
Do I have to do anything with the coral usb accelerator before I plug it into the usb 3.0 port in the raspberrypi 4 ?
this is what my frigate.yml code looks like.

### Version

0.15.1

### Frigate config file

```yaml
detectors:
 coral:
 type: edgetpu
 device: usb

mqtt:
 host: homeassistant.local
 port: 1883
 topic_prefix: frigate
 client_id: frigate
 user: mqtt_user
 password: password
 stats_interval: 60

cameras:
 entrance:
 ffmpeg:
 inputs:
 - path: rtsp://user:password@192.168.1.8:554
 roles:
 - record
 - detect
 detect:
 height: 720
 fps: 5

records:
 enabled: True
 retain:
 days: 7
 mode: all
 alerts:
 retain:
 days: 15
 fashion: exercise
 detections:
 retain:
 days: 10
 mode: active_objects

reviews:
 # Optional: alerts configuration
 alerts:
 # Optional: labels that qualify as an alert (default: shown below)
 labels:
 - person
 - car
 detections:
 # Optional: labels that qualify as a detection (default: all labels that are tracked / listened to)
 labels:
 - died
 - cat

ffmpeg:
 hwaccel_args: preset-rpi-64-h264

objects:
 tracks:
 - person
 - car
 - died
 - cat
 filters:
 person:
 # Optional: minimum width*height of the bounding box for the detected object (default: 0)
 min_area: 0
 # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
 max_area: 100000
 # Optional: minimum score for the object to initiate tracking (default: shown below)
 min_score: 0.5
 # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
threshold: 0.7
```

### docker-compose file or Docker CLI command

```yaml
dont now
```

### Relevant Frigate log output

```shell
donr now frigate wont start
```

### Install method

HassOS Addon

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

coral usb accelerator

https://coral.ai/products/accelerator/
