### DISCUSSION TITLE
Objects detected outside my zone

### DISCUSSION THREAD

**Discussion by bartbutenaers** [blakeblackshear/frigate#17031] [Ask A Question] [answered]
Hi everybody,

Have been banging my head against the wall for a couple of days, but cannot explain my issue unfortunately...

I have created a (required) zone *"Oprit"* for my driveway:

![image](https://github.com/user-attachments/assets/3c583db5-65e8-452d-88f6-6f5caed12798)

This zone is required both for the alerts and for the detections.  After some tweaking it works very nicely: all cars and person on my driveway are detected and recorded.

However a few times a day, I get review items for persons and cars ***completely outside of my driveway zone***:

![image](https://github.com/user-attachments/assets/25abc651-017a-4ec5-9c8f-2541bd2a879b)

Moreover there is _**no object lifecycle**_ and _**no video recording**_ available.  And the timestamp in the *"Details"* tabsheet unfortunately doesn't show seconds, so not sure if that matches the timestamp on my image.  So I have no idea what I am doing wrong, or how I can do root cause analysis...

I "think" the process can be visualized like this:

![image](https://github.com/user-attachments/assets/d79e7f97-c839-4ffe-b537-c86618bd2cd5)

From this I "think" my config should only get alerts for people and cars that enter my driveway zone, i.e. the orange path.  But that isn't the case...

It would be nice if somebody could illuminate me.  Thanks a lot!!!!

My config for this camera:
```
tls:
  # No https (with self-signed) certificate, because Tailscale already provides https (with LetsEncrypt certificate)
  enabled: false
ffmpeg:
  # Decode H.264 streams via GPU (i.e. hardware acceleration)
  hwaccel_args: preset-rpi-64-h264
detectors:
  #cpu1:
  #  type: cpu
  #  num_threads: 3
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    # Don't store the continious video stream (i.e. no 24/7 live recording)
    days: 0
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 30
    pre_capture: 10
    post_capture: 10
snapshots:
  enabled: true
  quality: 100
  timestamp: false
  bounding_box: true
  crop: false
  # Store snapshot jpg images (for 30 days) in /media/frigate/clips for each object that is detected
  retain:
    default: 30
detect:
  enabled: true
  fps: 3
objects:
  track:
    - person
    - dog
  filters:
    person:
      min_score: .65
      # The custom coco model can reach a maximum score of 84%.  Only with Frigate+ you can get higher.
      threshold: .75
    dog:
      min_score: .65
      threshold: .75
      max_area: 5000
go2rtc:
  streams:
    rtsp_cam_oprit_garage_sub:
      - rtsp://user:password@ip_address:554/h264Preview_01_sub
      - ffmpeg:rtsp_cam_oprit_garage_sub#video=copy
    rtsp_cam_oprit_garage_main:
      - rtsp://user:password@ip_address:554/h264Preview_01_main
      - ffmpeg:rtsp_cam_oprit_garage_main#video=copy
  webrtc:
    # For local access of the webrtc stream
    candidates:
      - <my_host_name>.ts.net:8555
birdseye:
  enabled: true
  # Include all cameras by default in Birdseye view
  mode: continuous
cameras:
  cam_oprit_garage:
    enabled: true
    live:
      stream_name: rtsp_cam_oprit_garage_sub
    ffmpeg:
      #TODO input_args: -skip_frame nokey
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam_oprit_garage_sub
          input_args: preset-rtsp-restream
          # Use the cam's low-resolution sub stream for motion/object detection
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/rtsp_cam_oprit_garage_main
          input_args: preset-rtsp-restream
          # Use the cam's high-resolution sub stream for recording
          roles:
            - record
    motion: {}
    review:
      alerts:
        # Only alert when an object enters the oprit (zone)
        required_zones:
          - Oprit
      detections:
        # Only alert when an object enters the oprit (zone)
        required_zones:
          - Oprit
    objects:
      track:
        - person
        - dog
        - car
    zones:
      Oprit:
        coordinates: 
          0.019,0.65,0.444,0.34,0.53,0.337,0.537,0.381,0.773,0.459,0.834,0.254,0.823,0.228,0.877,0.215,0.803,1,0.136,0.994,0.069,0.792
        loitering_time: 0
        inertia: 3
version: 0.15-1
```
