### DISCUSSION TITLE
Hikvision DS-2CD2387G2-LSU two way audio

### DISCUSSION THREAD

**Discussion by kirsch33** [blakeblackshear/frigate#17048] [General]
i installed a couple of Hikvision DS-2CD2387G2-LSU and they look great. However I cannot get two way audio working even after searching previous discussions here and on the go2rtc repo. I'm finding alot of conflicting info on what the camera codecs need to be set to as well as the recommended URL for the go2rtc portion. 

I can't get the microphone button to display in Frigate or if I load the webrtc stream directly from the go2rtc dashboard.

Heres the relevant part of the config now:
```yaml
go2rtc:
  streams:
    back:
      - rtsp://USER:PASS@MYCAMERAIP:554/streaming/channels/101#backchannel=0
      - isapi://USER:PASS@MYCAMERAIP:80/
      - ffmpeg:back#audio=opus
  webrtc:
    listen: :8555
    candidates:
      - MYFRIGATEIP:8555
      - MYPUBLICIP:8555

ffmpeg:
  hwaccel_args: preset-nvidia-h264

cameras:
  back:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp:/MYFRIGATEIP:8554/back
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
```
