### DISCUSSION TITLE
Enabling Intel VAAPI/QSV Hardware Acceleration in Frigate (iHD Driver)  Intel i7-7600U (Intel HD Graphics 620)

### DISCUSSION THREAD

**Discussion by codecrunchers** [blakeblackshear/frigate#17043] [Show and tell]
# **Enabling Intel VAAPI/QSV Hardware Acceleration in Frigate (iHD Driver)  Intel i7-7600U (Intel HD Graphics 620)**

I had trouble with `preset-intel-qsv-h264` on this machine,  CPU usage for two streams was high.  This setup enabled the GPU and dropped CPU significantly with 4 1080p+ streams.

### **Tested on:**

-   **Intel i7-7600U (Intel HD Graphics 620)**
-  **Arch**
-   **Frigate 0.15-1**
-   **Docker-based deployment with `iHD` driver**

----------

## **1️⃣ Step 1: Verify VAAPI Support on Host**

Before configuring Frigate, confirm that your host supports VAAPI hardware acceleration.

Run:

```bash
vainfo

```

👉 **Expected output (example):**

```
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1
...

```

If `vainfo` fails:

-   Ensure `intel-media-va-driver-non-free` is installed:
    
    ```bash
    sudo apt-get install intel-media-va-driver-non-free
    
    ```
    

----------

## **2️⃣ Step 2: Verify Hardware Decoding with FFmpeg**

Test VAAPI decoding inside a Docker container:

```bash
docker run --rm -it \
  --device /dev/dri/renderD128:/dev/dri/renderD128 \
  ubuntu:22.04 \
  bash -c "apt update && apt install -y ffmpeg vainfo && \
  ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi \
  -i 'rtsp://YOUR_CAMERA_URL' -f null -"

```

👉 **Expected result:**

-   **Frames should process without errors**.

----------

## **3️⃣ Step 3: Configure Frigate to Use VAAPI**

Update your **`frigate.yml`**:

```yaml
detectors:
  ov_0:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  ...

logger:
  default: info
  logs:
    frigate.video: debug  # Enable FFmpeg debug logs
  
ffmpeg:
  input_args:
    - -hwaccel
    - vaapi        
    - -rtsp_transport
    - tcp
```
dopcker-compose
```
    environment:
      - FFREPORT=file=/config/ffmpeg.log:level=32:format=text

```
the logs will dump ffmpeg command line so you can debug your setup

   **Docker Compose includes:**
    
   ```yaml
   devices:
     - /dev/dri/renderD128:/dev/dri/renderD128
   
   ```
    
Restart Frigate:

```bash
docker restart frigate
```

----------

## **4️⃣ Step 4: Confirm Frigate is Using VAAPI**

Run:

```bash
docker logs frigate 2>&1 | grep -i hwaccel
```

👉 **Expected output:**

something about
```
vaapi hwaccel 
```
in logs   

and  in UI
![Screenshot From 2025-03-09 20-42-09](https://github.com/user-attachments/assets/dc21f8de-a2a6-496f-8005-52a3492eb7df)

----------

-   **4 cameras with sub-streams**
-   **VAAPI enabled**
-   **CPU usage reduced from 74% → <40%**
-   **Frigate logs confirm VAAPI acceleration is active**

----------

**Comment by mozillalives** [comment]
Thank you! I was struggling to figure out how to get this configured.

**Reply by codecrunchers** [reply]
@mozillalives  I just updated the ffmeg/hwaccel as I found silent error - vaapi was not kicking in

```
ffmpeg:
  input_args:
    - -hwaccel
    - vaapi        
    - -rtsp_transport
    - tcp
  output_args:
    record: -vf "format=nv12,hwupload" -c:v h264_vaapi -b:v 2M -f segment -segment_time
      60 -segment_format mp4 -strftime 1 -profile:v high -level:v "4.1"
```
These output args to handle a slow network I have

With that I get this in logs:
      

      
```
2025-03-11 22:52:49.139473892  [2025-03-11 22:52:49] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
```

in logs. 

Also, a lifesaver was getting a ffmpeg log created, it landed in config dir.
```
logger:
  default: info
  logs:
    frigate.video: debug  # Enable FFmpeg debug logs
```

Docker-compose
```
    environment:
      - FFREPORT=file=/config/ffmpeg.log:level=32:format=text

```

> ffmpeg started on 2025-03-11 at 23:12:00
Report written to "/config/ffmpeg.log"
Log level: 32
Command line:
/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -y -i /tmp/cache/side_passage@20250311231055+0000.mp4 -c copy -movflags +faststart /media/frigate/recordings/2025-03-11/23/side_passage/10.55.mp4
