### DISCUSSION TITLE
Getting substream on live view while go2rtc and `live` field defined

### DISCUSSION THREAD

**Discussion by weber8thomas** [blakeblackshear/frigate#17055] [Ask A Question] [answered]
Hi, 

First thanks a lot for that wonderful open-source system you're developing! 

I just migrated from 0.13.2 to 0.15.0 and cannot get my main stream to be displayed (also currently without audio) on the live view. This is my config:

```
mqtt:
  enabled: false

go2rtc:
  streams:
    annkec800_sd:
      - ffmpeg:rtsp://admin:pwd@192.168.0.192:554/Streaming/Channels/101
    annkec800_transcode:
      - ffmpeg:rtsp://admin:pwd@192.168.0.192:554/Streaming/Channels/102#video=h264#audio=copy#hardware

ffmpeg:
  hwaccel_args: preset-vaapi

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - keys_jangling
    - door

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog
  filters:
    person:
      threshold: 0.8
    dog:
      threshold: 0.8
cameras:
  annkec800_sd:
    live:
      stream_name: annkec800_sd
    ffmpeg:
      inputs:
        - path: rtsp://admin:pwd@192.168.0.192:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/annkec800_transcode
          roles:
            - detect
            - audio
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a copy
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    zones:
      zone_0:
        coordinates: 365,480,481,480,520,334,448,291

version: 0.15-1
```

Don't pay attentions to the naming with `_sd`, this is legacy. Main stream is playing 4K.

Many thanks in advance for you help!
