### DISCUSSION TITLE
clip with notification and frigate proxy

### DISCUSSION THREAD

**Discussion by Frazou1** [blakeblackshear/frigate#17078] [Ask A Question]
Im trying to get a notification with frigate v15 by home assistant and im using frigate proxy on home assistant.  I try to put a button view clip on my notification to when i clikc on it i will redirect me to the clip. i take the exemple of the frigate documentation and is look like this 👍 
```
alias: NOTIF FRIGATE TEST
description: ""
triggers:
  - topic: frigate/reviews
    payload: alert
    value_template: "{{ value_json['after']['severity'] }}"
    trigger: mqtt
actions:
  - data:
      message: >-
        A {{trigger.payload_json["after"]["data"]["objects"] | sort | join(", ")
        | title}} was detected.
      data:
        image: >-
          https://xxx/api/frigate/notifications/{{trigger.payload_json["after"]["data"]["detections"][0]}}/thumbnail.jpg
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        entity_id: >-
          camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
          lower}}
        actions:
          - action: WATCH_CLIP
            title: 🎥 Voir le clip
            uri: >-
              https://xxx/api/frigate/events/{{trigger.payload_json["after"]["id"]}}/clip.mp4
    action: notify.mobile_app_iphone
mode: single
```
When i click on de watch button they redirect me on home assistant and not on the clip.   Someone know what im doing wrong ?
