### DISCUSSION TITLE
[Config Support]: No Audio Being Recorded

### DISCUSSION THREAD

**Discussion by craftcm** [blakeblackshear/frigate#17085] [Config Support] [answered]
### Describe the problem you are having

Hi all - I've searched around and tried a few suggestions from prior posts, but none have worked for me. Frigate is recording audio without issue for my Reolink doorbell camera, but I cannot seem to get it to record any audio for my two POE 5MP cameras - front_yard and garage. I've included my config and would appreciate someone pointing out where I've gone wrong. Thank you!

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    doorbell_camera_main:
      - ffmpeg:http://10.10.2.100/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=PASSWORD#video=copy#audio=copy#audio=opus
    doorbell_camera_sub:
      - ffmpeg:http://10.10.2.100/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password=PASSWORD#video=copy#audio=copy#audio=opus
    front_yard_camera_main:
      - ffmpeg:rtsp://frigate:PASSWORD@10.10.2.101:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
    front_yard_camera_sub:
      - ffmpeg:rtsp://frigate:PASSWORD@10.10.2.101:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
    garage_camera_main:
      - ffmpeg:rtsp://frigate:PASSWORD@10.10.2.102:554/h264Preview_01_main#video=copy#audio=copy#audio=opus
    garage_camera_sub:
      - ffmpeg:rtsp://frigate:PASSWORD@10.10.2.102:554/h264Preview_01_sub#video=copy#audio=copy#audio=opus
    bin: ffmpeg
    volume: -af "volume=30dB"
    hwaccel_args: preset-vaapi
cameras:
  doorbell_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: doorbell_camera_main
    objects:
      track:
        - person
        - cat
        - dog
        - bird
  front_yard_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    live:
      stream_name: front_yard_camera_main
    objects:
      track:
        - person
        - cat
        - dog
        - bird
  garage_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: garage_camera_main
    objects:
      track:
        - person
        - cat
        - dog
        - bird
record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: motion
detectors:
  cpu0:
    type: cpu
    num_threads: 1
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
  cpu3:
    type: cpu
    num_threads: 1
version: 0.14
```

### Relevant Frigate log output

```shell
N/A.
```

### Relevant go2rtc log output

```shell
N/A.
```

### Operating system

Other Linux

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
sudo docker run -d \
  --name frigate \
  --shm-size="248mb" \
  --restart unless-stopped \
  -v /home/user/frigate/config/config.yaml:/config/config.yaml \
  -v /mnt/Data/NVR:/media/frigate \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/cache \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  --cap-add=CAP_PERFMON \
  --device /dev/dri/renderD128 \
ghcr.io/blakeblackshear/frigate:0.14.1
```

### Object Detector

CPU (no coral)
