### DISCUSSION TITLE
timestamp - possible to set (x,y) coordinates rather than tl/tr/bl/br?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#17082] [Ask A Question] [answered]
Hello

I have tried to set a timestamp to be visible on a camera whose output has been dewarped from a spherical lens. The timestamp isn't visible, because I think it has been warped out of shot by 

`- ffmpeg:rtsp://admin:password@192.168.1.192:554/Streaming/Channels/101#video=h264#audio=copy#raw=-vf
        "lenscorrection=k1=-0.450:k2=0.1"`

This is how I'm attempting the timestamp:

```
timestamp_style:
      format: "%d/%m/%Y %H:%M:%S"
      position: "bl"
      color:
        red: 0 #255
        green: 0 #255
        blue: 0 #255
      thickness: 2
      effect: solid 
```

(1) Is there a way round the problem (whilst still maintaining the dewarping of course!)?

(2) an (x,y) to set the position might be a nice feature for future versions.

(3) the documentation says for `effect` that the options are 

![image](https://github.com/user-attachments/assets/a2c1113d-d6d5-437f-85a6-51fbbe871e54)

but when I try `None` or `none` I get an error:

![image](https://github.com/user-attachments/assets/b7d32a2c-a163-4ef2-8284-54f9acae9347)
![image](https://github.com/user-attachments/assets/cb4f088d-9c4c-420c-8862-02483c06c234)

but `solid` is OK
![image](https://github.com/user-attachments/assets/3d856526-380b-49c6-a17d-1f538465846b)

(Frigate version 0.15.0-cea210d)
