### DISCUSSION TITLE
[Support]: Downloading event clips do not includes some seconds before and after the event

### DISCUSSION THREAD

**Discussion by JanickGers85** [blakeblackshear/frigate#17092] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Downloading event clips do not includes some seconds before and after the event, as it did before.

### Steps to reproduce

1. Download an event's clip the the UI or get it from HTTP API

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

Google Chrome 134.0.6998.37

### Frigate config file

```yaml
ui:
  time_format: 24hour

auth:
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb
model:
  path: plus://***
mqtt:
  host: 192.168.1.217
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: nlh6Q6zW4cYmALBn
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-vaapi
birdseye:
  mode: continuous
timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

go2rtc:
  streams:
    garden:
      - rtsp://admin:***@192.168.1.181:554/live/0/MAIN
      - ffmpeg:garden#audio=aac
    garden-sub:
      - rtsp://admin:***@192.168.1.181:554/live/0/SUB
      - ffmpeg:garden-sub#audio=aac
    garage-esterno:
      - rtsp://admin:***@192.168.1.56:554/live/0/MAIN
      - ffmpeg:garage-esterno#audio=aac
    garage-esterno-sub:
      - rtsp://admin:***@192.168.1.56:554/live/0/SUB
      - ffmpeg:garage-esterno-sub#audio=aac
    garage-interno:
      - rtsp://***:***@192.168.1.111:554/stream1
      - ffmpeg:garage-interno#audio=aac

cameras:
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden-sub
          hwaccel_args: preset-intel-qsv-h265
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/garden
          hwaccel_args: preset-intel-qsv-h265
          roles:
            - record
    live:
      stream_name: garden-sub
    audio:
      enabled: true
      min_volume: 65
      listen:
        - bark
        - fire_alarm
        - alarm
        - car_alarm
        - scream
        - speech
        - yell
    ui:
      order: 1
    birdseye:
      order: 1
    snapshots:
      required_zones:
        - giardino_siepe
        - giardino_patio
        - vialetto
        - viale
        - strada
        - pancini
        - cassetta_posta
        - cancellino
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 36500
        objects:
          car: 21
    detect:
      fps: 5
      width: 1280
      height: 720
      annotation_offset: 0
    best_image_timeout: 5
    mqtt:
      enabled: true
      crop: true
      height: 500
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      alerts:
        retain:
          days: 36500
      detections:
        retain:
          days: 36500
    zones:
      giardino_siepe:
        coordinates: 
          0.614,0.352,0.636,0.21,0.589,0.18,0.488,0.147,0.412,0.136,0.328,0.128,0.251,0.12,0.223,0.124,0.226,0.231
        filters:
          car:
            min_area: 10000
        inertia: 3
        loitering_time: 0
      giardino_patio:
        coordinates: 
          0,1,0.843,1,0.839,0.901,0.831,0.856,0.588,0.787,0.599,0.678,0.611,0.515,0.613,0.351,0.372,0.279,0.224,0.226,0.163,0.296,0.073,0.418,0,0.568
        filters:
          person:
            min_area: 6000
            max_area: 900000
        inertia: 3
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - person
      vialetto:
        coordinates: 
          0.603,0.666,0.588,0.786,0.835,0.862,0.83,0.755,0.788,0.795,0.779,0.693,0.767,0.606,0.755,0.495,0.748,0.423,0.72,0.415,0.706,0.435,0.637,0.401,0.624,0.38,0.613,0.366,0.608,0.536
        filters:
          person:
            min_area: 6000
            max_area: 900000
        inertia: 3
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - person
      viale:
        coordinates: 
          0.221,0.176,0.379,0.199,0.526,0.26,0.632,0.311,0.634,0.376,0.702,0.409,0.712,0.352,0.794,0.39,0.781,0.444,0.818,0.462,0.835,0.412,1,0.541,1,0.511,0.917,0.432,0.832,0.36,0.732,0.29,0.642,0.231,0.498,0.175,0.371,0.149,0.263,0.14,0.221,0.141
        inertia: 3
        loitering_time: 0
      strada:
        coordinates: 
          0,0,1,0,1,0.474,0.911,0.363,0.82,0.289,0.725,0.222,0.646,0.187,0.585,0.158,0.529,0.148,0.438,0.124,0.353,0.11,0.27,0.104,0.181,0.115,0.107,0.132,0.056,0.155,0,0.182
        objects:
          - person
          - face
          - bicycle
          - cat
          - dog
        inertia: 3
        loitering_time: 0
      pancini:
        coordinates: 1,0.894,1,1,0.862,1,0.838,0.754,0.78,0.445,0.822,0.485,0.84,0.437,0.877,0.47
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - bicycle
      cassetta_posta:
        coordinates: 0.648,0.233,0.628,0.344,0.562,0.305,0.583,0.187
        inertia: 3
        loitering_time: 0
      cancellino:
        coordinates: 0.653,0.244,0.726,0.289,0.703,0.414,0.633,0.379,0.631,0.339
        inertia: 3
        loitering_time: 0
      rumeno:
        coordinates: 
          0.152,0.201,0.204,0.223,0.158,0.274,0.115,0.322,0.074,0.38,0.002,0.496,0,0.299,0.076,0.227,0.092,0.264,0.118,0.232
        loitering_time: 0
        inertia: 3
        objects:
          - bicycle
          - cat
          - dog
          - person
      No_mans_land:
        coordinates: 
          0.173,0.113,0.101,0.133,0.104,0.149,0.162,0.14,0.212,0.142,0.403,0.153,0.499,0.171,0.57,0.201,0.634,0.228,0.687,0.262,0.745,0.295,0.816,0.344,0.882,0.399,0.926,0.445,0.999,0.512,1,0.476,0.955,0.416,0.908,0.36,0.829,0.296,0.768,0.254,0.684,0.202,0.591,0.162,0.505,0.142,0.42,0.122,0.341,0.113,0.282,0.11
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - person
        inertia: 3
    objects:
      track:
        - person
        - face
        - bicycle
        - cat
        - dog
        - license_plate
    review:
      alerts:
        required_zones:
          - vialetto
          - giardino_patio
      detections:
        required_zones:
          - vialetto
          - viale
          - pancini
          - giardino_siepe
          - giardino_patio
          - cassetta_posta
          - cancellino
          - rumeno
          - No_mans_land
          - strada
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  garage-esterno:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-esterno-sub
          hwaccel_args: preset-intel-qsv-h265
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/garage-esterno
          hwaccel_args: preset-intel-qsv-h265
          roles:
            - record
    live:
      stream_name: garage-esterno-sub
    audio:
      enabled: true
      min_volume: 25
      listen:
        - bark
        - fire_alarm
        - alarm
        - car_alarm
        - scream
        - speech
        - yell
    ui:
      order: 2
    birdseye:
      order: 2
    snapshots:
      required_zones:
        - garage_ingresso
        - garage_piazzale
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 36500
        mode: active_objects
    detect:
      fps: 5
    best_image_timeout: 5
    mqtt:
      enabled: true
      crop: true
      height: 500
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      alerts:
        retain:
          days: 36500
      detections:
        retain:
          days: 21
    zones:
      garage_ingresso:
        coordinates: 1,1,1,0.131,0.953,0.121,0.804,0.661,0.719,0.596,0.642,0.532,0.347,0.854,0.406,1
        filters:
          person:
            min_area: 800
            max_area: 300000
          car:
            min_area: 1000
            max_area: 200000
        inertia: 3
        loitering_time: 0
      garage_piazzale:
        coordinates: 
          0,1,0.404,1,0.346,0.856,0.641,0.535,0.805,0.664,0.951,0.126,1,0.137,1,0,0.88,0.088,0.875,0.197,0.791,0.147,0.818,0.063,0.752,0.034,0.704,0.056,0.628,0.049,0.5,0.067,0.444,0.072,0.396,0.088,0.394,0,0.22,0,0,0
        filters:
          person:
            min_area: 10
            max_area: 300000
          car:
            min_area: 100
            max_area: 200000
        inertia: 3
        loitering_time: 0
      area_illuminazione:
        coordinates: 
          0.821,0.442,0.944,0.641,1,1,0.208,1,0.226,0.84,0.234,0.691,0.533,0.425,0.68,0.503
        filters:
          person:
            min_area: 800
            max_area: 300000
          car:
            min_area: 1000
            max_area: 200000
        inertia: 3
        loitering_time: 0
      car_no_alert:
        coordinates: 0.793,0.146,0.871,0.194,0.878,0.101,0.816,0.068
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - person
        inertia: 3
      garage_strada:
        coordinates: 
          0.395,0,0.398,0.092,0.534,0.06,0.629,0.049,0.669,0.049,0.704,0.054,0.749,0.035,0.819,0.063,0.875,0.097,0.882,0
        loitering_time: 0
    objects:
      track:
        - person
        - face
        - car
        - bicycle
        - cat
        - dog
        - license_plate
    review:
      alerts:
        required_zones: garage_ingresso
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  garage-interno:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-interno
          hwaccel_args: preset-intel-qsv-h264
          roles:
            - detect
            - record
            - audio
        # - path: rtsp://127.0.0.1:8554/garage-interno-sub
        #   roles:
        #     - detect
    live:
      stream_name: garage-interno
    audio:
      enabled: true
      min_volume: 9
      listen:
        - bark
        - fire_alarm
        - alarm
        - car_alarm
        - scream
        - speech
        - yell
    ui:
      order: 3
    birdseye:
      order: 3
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 36500
        mode: active_objects
    detect:
      fps: 5
    best_image_timeout: 5
    objects:
      track:
        - person
        - face
    mqtt:
      enabled: true
      crop: true
      height: 500
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 36500
      detections:
        retain:
          days: 36500
objects:
  track:
    - person
    - face
    - car
    - bicycle
    - cat
    - dog
    - license_plate
    - amazon
    - fedex
    - ups
    - package
  filters:
    person:
      #min_area: 800
      #max_area: 400000
      min_score: 0.70
      threshold: 0.82
    cat:
      #min_area: 1000
      max_area: 25000
      min_score: 0.65
      threshold: 0.75
    face:
      min_score: 0.7
    car:
      #max_area: 250000
      min_score: 0.65
      threshold: 0.78
    license_plate:
      min_score: 0.65
    dog:
      min_score: 0.65
      threshold: 0.78
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
  Esterni:
    order: 2
    icon: LuExternalLink
    cameras:
      - garage-esterno
      - garden
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    cap_add:
      - CAP_PERFMON
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri:/dev/dri
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1gb"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ./docker/frigate:/config
      - /home/nuc/frigate/:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - 5000:5000
      - 1935:1935
      - 8554:8554
    environment:
      - PLUS_API_KEY=***
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Not relevant

### General
![image](https://github.com/user-attachments/assets/2a4bf15a-aee2-40db-9e32-c91dae12df26)

### Storage
![image](https://github.com/user-attachments/assets/65fa2216-48d2-4880-808f-2489838efc04)

### Cameras
![image](https://github.com/user-attachments/assets/5f14ea6d-bfaa-412d-bc24-7d94344920ca)
