### DISCUSSION TITLE
Birdseye

### DISCUSSION THREAD

**Discussion by kadamik** [blakeblackshear/frigate#17103] [Config Support]
### Describe the problem you are having

I have Birdseye configured for 6 cameras in continuous mode.  It does display the cameras but each camera section will randomly go blank for a ms and then back on.  All 6 of them will do that thur out the day.  I have adjusted setting and streams and I can't seam to fix it.  I am using the secondary stream of my cameras at a low resolution and that seems to help but it still drops a frame or 2 randomly.  Any thoughts on adjustments I can make?

### Version

0.16.0-7d44970

### Frigate config file

```yaml
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: false
  # Required: host name
  host: 192.168.10.5
  topic_prefix: frigate

go2rtc:
  streams:
#4K Cameras
    Camera_Sideyard:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.10:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Frontyard:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.11:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Dog_Gate:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.12:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Backyard:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.13:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Driveway:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.14:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Frontdoor_Garage:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.15:554/cam/realmonitor?channel=1&subtype=0#timeout=30

#2KCameras
    Camera_Den:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.102:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Front_Hall:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.101:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Garage:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.103:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Playroom:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.104:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Front_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.16:554/h264Preview_01_main#timeout=30#backchannel=0
    Camera_Dog_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.17:554/h264Preview_01_main#timeout=30#backchannel=0
    Camera_Back_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.18:554/h264Preview_01_main#timeout=30#backchannel=0
    Camera_Garage_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.19:554/h264Preview_01_main#timeout=30#backchannel=0
#    Camera_Garage_Doorbell:
#      - ffmpeg:Rotated_Camera_Garage_Doorbell#video=h264#raw=-vf transpose=1#audio=copy
#    Camera_Birdseye:
#       - rtsp://192.168.10.5:8554/birdseye#timeout=30#backchannel=0

#Substreams
    Camera_Frontyard_sub:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.11:554/cam/realmonitor?channel=1&subtype=1
    Camera_Dog_Gate_sub:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.12:554/cam/realmonitor?channel=1&subtype=1
    Camera_Garage_sub:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.103:554/cam/realmonitor?channel=1&subtype=1
    Camera_Driveway_sub:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.14:554/cam/realmonitor?channel=1&subtype=1
    Camera_Frontdoor_Garage_sub:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.15:554/cam/realmonitor?channel=1&subtype=1
    Camera_Sideyard_sub:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.10:554/cam/realmonitor?channel=1&subtype=1
#    Calendar: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -i rtsp://192.168.10.5:8554/Camera_Dog_Gate_sub -i rtsp://192.168.10.5:8554/Camera_Driveway_sub -i rtsp://192.168.10.5:8554/Camera_Frontyard_sub -i rtsp://192.168.10.5:8554/Camera_Sideyard_sub -i rtsp://192.168.10.5:8554/Camera_Sideyard_sub -i rtsp://192.168.10.5:8554/Camera_Sideyard_sub -filter_complex "[0:v][1:v][2:v]hstack=inputs=3[top]; [3:v][4:v][5:v]hstack=inputs=3[bottom]; [top][bottom]vstack=inputs=2[v]" -map "[v]" -c:v libx264 -f rtsp {{output}}

ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/Chicago

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: true
  # Optional: Width of the output resolution (default: shown below)
  width: 704
  # Optional: Height of the output resolution (default: shown below)
  height: 480
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 30
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  # Optional: Threshold for camera activity to stop showing camera (default: shown below)
  inactivity_threshold: 60
  # Optional: Configure the birdseye layout
  layout:
    # Optional: Scaling factor for the layout calculator, range 1.0-5.0 (default: shown below)
    scaling_factor: 1.5
    # Optional: Maximum number of cameras to show at one time, showing the most recent (default: show all cameras)
    max_cameras: 6

ffmpeg:
  input_args: preset-rtsp-restream
#  hwaccel_args: preset-intel-qsv-h265
  hwaccel_args: preset-vaapi
#  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
#    tcp -timeout 12000000 -use_wallclock_as_timestamps 1
#  global_args: -hide_banner -loglevel warning -threads 2

database:
  path: /database/frigate.db

detectors:
  ov_0:
    type: openvino
    device: GPU
#  ov_1:
#    type: openvino
#    device: GPU

model:
  path: plus://c01840996a2de74978cc1bba6b7bc6dd

#  model_type: yolonas
#  width: 320 # <--- should match whatever was set in notebook
#  height: 320 # <--- should match whatever was set in notebook
#  input_tensor: nchw
#  input_pixel_format: bgr
#  path: /config/yolo_nas_l.onnx
#  labelmap_path: /labelmap/coco-80.txt





objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - car
    - cat
    - ups
    - amazon
    - fedex
    - face
    - usps
    - package
    - license_plate
    - bicycle
    - motorcycle
  filters:
    dog:
      min_score: .7
      threshold: .8
    cat:
      min_score: .6
      threshold: .7
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .8
    license_plate:
      min_score: .6
    amazon:
      min_score: .6
    ups:
      min_score: .6
    fedex:
      min_score: .6
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85

record:
  enabled: true
  retain:
    days: 20
    mode: all
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 30
snapshots:
  clean_copy: false
  bounding_box: true
  crop: false
  quality: 70
  height: 1660
  timestamp: true
  enabled: true
  retain:
    default: 60
#detect:
#  stationary:
#    interval: 50
#    threshold: 50
#  width: 1920
#  height: 1080
#  fps: 5

semantic_search:
  enabled: true
  reindex: false
  model_size: small

face_recognition:
  enabled: true

#telemetry:
#  stats:
#    amd_gpu_stats: false
#    intel_gpu_stats: true
#    network_bandwidth: true

cameras:
# sub
  Camera_Driveway_sub:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Driveway_sub
#          roles:
#           - detect
    detect:
      enabled: false
    record:
      enabled: false
    live:
      streams:
        Camera_Driveway_sub: Camera_Driveway_sub

  Camera_Sideyard_sub:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Sideyard_sub
#          roles:
#            - detect
    detect:
      enabled: false
    record:
      enabled: false
    live:
      streams:
        Camera_Sideyard_sub: Camera_Sideyard_sub

  Camera_Frontyard_sub:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Frontyard_sub
#          roles:
#            - detect
    detect:
      enabled: false
    record:
      enabled: false
    live:
      streams:
        Camera_Frontyard_sub: Camera_Frontyard_sub

  Camera_Dog_Gate_sub:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Dog_Gate_sub
#          roles:
#            - detect
    detect:
      enabled: false
    record:
      enabled: false
    live:
      streams:
        Camera_Dog_Gate_sub: Camera_Dog_Gate_sub

  Camera_Garage_sub:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Garage_sub
#          roles:
#            - detect
    detect:
      enabled: false
    record:
      enabled: false
    live:
      streams:
        Camera_Garage_sub: Camera_Garage_sub

  Camera_Frontdoor_Garage_sub:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera_Frontdoor_Garage_sub
#          roles:
#            - detect
    detect:
      enabled: false
    record:
      enabled: false
    live:
      streams:
        Camera_Frontdoor_Garage_sub: Camera_Frontdoor_Garage_sub
```

### Relevant Frigate log output

```shell
no errors
```

### Relevant go2rtc log output

```shell
no errors
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate16
    privileged: true # this may not be necessary for all setups
    stop_grace_period: 30s
    restart: always
    image: ghcr.io/blakeblackshear/frigate:7d44970
    shm_size: "4096mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/kadamik/docker/frigate16/database:/database
      - /mnt/cameras/frigate16/config:/config
      - /mnt/cameras/frigate16/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971"
      - "1984:1984/tcp"
      - "1984:1984/udp"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/13c938e2-b4f5-4af4-ab76-f3a1169047cd)
