### DISCUSSION TITLE
[Config Support]: Unable to connect to MQTT server

### DISCUSSION THREAD

**Discussion by SailingNut** [blakeblackshear/frigate#17102] [Config Support] [answered]
### Describe the problem you are having

I am running mosquitto and frigate in docker containers. Frigate is unable to connect to mosquitto and I'm very lost on how to go about troubleshooting this. I did increase logging for frigate.coms and frigate.mqtt to debug but still nothing that pointed me in a direction of what is wrong.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
go2rtc:
  streams:
    driveway_cam:
      - rtsp://wtbadmin:***@192.168.0.160:554/stream1 # stream which supports video & aac audio
      - "ffmpeg:driveway_cam#audio=opus" # copy of the stream which transcodes audio to opus
logger:
  default: info
  logs:
    frigate.mqtt: debug
    frigate.comms: debug
mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate

cameras:
  driveway_cam: # <------ Name the camera
    enabled: true
    ffmpeg:
      #output_args:
       #- preset-record-generic-audio-aac [1, 7]
      inputs:
        - path: rtsp://wtbadmin:***@192.168.0.160:554/stream1 # <----- The stream you want to use for detection
          roles:
            - detect
            - record
            - audio
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-03-11 14:11:22.032405372  [2025-03-11 14:11:22] frigate.comms.ws               DEBUG   : Publishing mqtt message from websockets at onConnect.
2025-03-11 14:11:22.032720837  [2025-03-11 14:11:22] frigate.comms.mqtt             DEBUG   : Unable to publish to camera_activity: client is not connected
2025-03-11 14:11:22.032917988  [2025-03-11 14:11:22] frigate.comms.mqtt             DEBUG   : Unable to publish to model_state: client is not connected
2025-03-11 14:11:22.033241619  [2025-03-11 14:11:22] frigate.comms.mqtt             DEBUG   : Unable to publish to embeddings_reindex_progress: client is not connected
2
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
# version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1833:1833"
    networks:
      - frigate_network

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config:/config
      - /frigate/media:/media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      - frigate_network
    depends_on:
      - mosquitto
networks:
  frigate_network:
```

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
Your port numbers are incorrect.

You have this in your docker compose file:
```
    ports:
      - "1833:1833"
```
But in your Frigate config, you are specifying this:
```
mqtt:
  enabled: true
  host: mosquitto
  port: 1883
```
The standard port for mqtt is 1883, not 1833. But you could update one or the other - just keep it consistent.
