### DISCUSSION TITLE
[Bug]: activating authentication makes WebRTC + Home assistant integration broken

### DISCUSSION THREAD

**Discussion by aqwserf** [blakeblackshear/frigate#17100] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Everything works fine using `auth.enable: false` but once activated, and removing everything under `config/` , I noticed that almost every stream are broken:
1. The `camera.office_camera` which is supposed to gather some pictures does not work anymore
2. It's no longer possible to use `live_provider: go2rtc` within `custom:advanced-camera-card`

I obviously deleted the previous Firgate integration and added with a user/password.
After investigating, I noticed that while the WebUI is working fine, enabling debug log showed this while refreshing the HA frigate camera integration:
```
frigate  | 2025-03-11 16:48:10.457570947  [2025-03-11 16:48:10] asyncio                        DEBUG   : Using selector: EpollSelector
frigate  | 2025-03-11 16:48:10.461210452  [2025-03-11 16:48:10] peewee                         DEBUG   : ('SELECT "t1"."start_time", "t1"."end_time", "t1"."severity", "t1"."data" FROM "reviewsegment" AS "t1" WHERE (("t1"."camera" = ?) AND (("t1"."end_time" IS NULL) OR ("t1"."end_time" >= ?))) ORDER BY "t1"."start_time"', ['office_camera', 1741708073.0])
frigate  | 2025-03-11 16:48:13.144535647  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : Found authorization header
frigate  | 2025-03-11 16:48:13.146255269  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : current time:   Tue Mar 11 16:48:13 2025
frigate  | 2025-03-11 16:48:13.146472672  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : jwt expires at: Wed Mar 12 16:43:17 2025
frigate  | 2025-03-11 16:48:13.146475918  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : jwt refresh at: Wed Mar 12 04:43:17 2025
frigate  | 2025-03-11 16:48:13.213130990  192.168.51.90 - - [11/Mar/2025:16:48:13 +0100] "POST /api/go2rtc/webrtc?src=office_camera HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:13.214753487  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:13.246800331  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:13.247607527  192.168.51.90 - - [11/Mar/2025:16:48:13 +0100] "GET /api/office_camera/latest.jpg HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:14.198219545  [2025-03-11 16:48:14] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:14.199538003  192.168.51.90 - - [11/Mar/2025:16:48:14 +0100] "GET /api/office_camera/latest.jpg HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:15.218961947  [2025-03-11 16:48:15] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:15.220745440  192.168.51.90 - - [11/Mar/2025:16:48:15 +0100] "GET /api/office_camera/latest.jpg HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
```
Everything else work, as it relies on MQTT I guess.

I also noticed that configuring the integration without ticking `Use Frigate-native WebRTC support` and using `live_provider: ha` with `custom:advanced-camera-card` work with authentication enabled.

I'm not using something crazy, but at first, I wanted to use Nginx reverse proxy, which didn't work. So after investing, and removing all the potential problematic layers, I ended up with this. 
Or maybe I'm missing something...

For context: I'm coming from a supervised HA with everything to a Proxmox with separated QEMU (HA) and LXC (z2m, frigate, mqtt). 

### Steps to reproduce

1. Activate authentication on Frigate
2. Add the Frigate integration on HA
3. No pictures under the `camera.name`

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

Firefox 135.0.1 (64-bit)

### Frigate config file

```yaml
################################################################
#### MQTT
################################################################
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: xxxx
  # Optional: port (default: shown below)
  port: 8883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: frigate
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxxx
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  tls_ca_certs: /ssl/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  tls_client_cert: /ssl/hysteresis.lan.crt
  tls_client_key: /ssl/hysteresis.lan.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  tls_insecure: true
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

################################################################
#### DETECTORS
################################################################
# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  detector_name:
    # Required: type of the detector
    # Frigate provided types include 'cpu', 'edgetpu', 'openvino' and 'tensorrt' (default: shown below)
    # Additional detector types can also be plugged in.
    # Detectors may require additional configuration.
    # Refer to the Detectors configuration page for more information.
    type: edgetpu
    device: usb

################################################################
#### TLS
################################################################
# Optional: TLS configuration
tls:
  # Optional: Enable TLS for port 8971 (default: shown below)
  # enabled: True
  enabled: false

################################################################
#### AUTHENTICATION
################################################################
# Optional: Authentication configuration
auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false
  # Optional: Cookie to store the JWT token for native auth (default: shown below)
  cookie_name: frigate_token
  # Optional: Set secure flag on cookie. (default: shown below)
  # NOTE: This should be set to True if you are using TLS
  cookie_secure: false
  # Optional: Session length in seconds (default: shown below)
  session_length: 86400 # 24 hours
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  failed_login_rate_limit: "60/second"
  # Optional: Trusted proxies for determining IP address to rate limit
  # NOTE: This is only used for rate limiting login attempts and does not bypass
  # authentication. See the authentication docs for more details.
  trusted_proxies:
    - 172.18.0.0/16 # <---- this is the subnet for the internal docker compose network
    - 192.168.0.0/16
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000

################################################################
#### LOGGER
################################################################
# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  # logs:
  #   frigate.video: critical
  #   watchdog.livingroom_camera: critical
  #   watchdog.landing_camera: critical
  #   watchdog.office_camera: critical
  #   watchdog.front_yard_camera: critical
  #   watchdog.side_yard_camera: critical
  #   watchdog.kitchen_camera: critical
  #   watchdog.back_yard_camera: critical

################################################################
#### RESTREAM
################################################################
# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.8.3)
go2rtc:
  streams:
    office_camera:
       - rtsp://admin:xxxx@xxxx:554/ch0_0.h264
       - "ffmpeg:office_camera#video=copy#audio=aac#hardware"
       #- ffmpeg:rtsp://xxx:xxx@xxx:554/ch0_0.h264#video=copy#audio=aac
  webrtc:
    candidates:
      - 192.168.123.190:8555
      - 172.18.0.2:8555
      - 127.0.0.1:8555
      - 192.168.51.20:8555
      #- stun:8555
  log:
    level: debug  # default level
    # api: info
    # exec: info
    # ngrok: info
    # rtsp: fatal
    # streams: fatal
    # webrtc: fatal


################################################################
#### CAMERAS
################################################################
# Required
cameras:
  ################################
  #### OFFICE
  ################################
  # Required: name of the camera
  office_camera:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: true
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://admin:PWBH2lnktCV54NvRviD2@192.168.107.30:554/ch0_0.h264
        - path: rtsp://127.0.0.1:8554/office_camera
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - record
            - detect

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      #crop: True
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 720
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      #order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

    objects:
      track:
        - person
      filters:
        person:
          min_area: 150000

    # enable records otherwise it's not possible to enable it afterwards and enable snapshots by default
    record:
      enabled: true
    snapshots:
      enabled: false

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./medias:/media/frigate
      - ./ssl:/ssl
      #- /etc/ssl/private/hysteresis.lan.key:/ssl/hysteresis.lan.key:ro
      #- /etc/ssl/certs/hysteresis.lan.crt:/ssl/hysteresis.lan.crt:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      #- "127.0.0.1:1984:1984"
      - "80:8971"
      #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      #FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: "radeonsi"
```

### Relevant Frigate log output

```shell
frigate  | 2025-03-11 16:48:05.637620477  [2025-03-11 16:48:05] frigate.stats.emitter          DEBUG   : Starting stats collection
frigate  | 2025-03-11 16:48:05.639189863  [2025-03-11 16:48:05] asyncio                        DEBUG   : Using selector: EpollSelector
frigate  | 2025-03-11 16:48:06.767812364  [2025-03-11 16:48:06] frigate.stats.emitter          DEBUG   : Finished stats collection
frigate  | 2025-03-11 16:48:08.146119951  [2025-03-11 16:48:08] frigate.api.auth               DEBUG   : Found authorization header
frigate  | 2025-03-11 16:48:08.146124059  [2025-03-11 16:48:08] frigate.api.auth               DEBUG   : current time:   Tue Mar 11 16:48:08 2025
frigate  | 2025-03-11 16:48:08.148406131  [2025-03-11 16:48:08] frigate.api.auth               DEBUG   : jwt expires at: Wed Mar 12 16:43:17 2025
frigate  | 2025-03-11 16:48:08.148433513  [2025-03-11 16:48:08] frigate.api.auth               DEBUG   : jwt refresh at: Wed Mar 12 04:43:17 2025
frigate  | 2025-03-11 16:48:10.457570947  [2025-03-11 16:48:10] asyncio                        DEBUG   : Using selector: EpollSelector
frigate  | 2025-03-11 16:48:10.461210452  [2025-03-11 16:48:10] peewee                         DEBUG   : ('SELECT "t1"."start_time", "t1"."end_time", "t1"."severity", "t1"."data" FROM "reviewsegment" AS "t1" WHERE (("t1"."camera" = ?) AND (("t1"."end_time" IS NULL) OR ("t1"."end_time" >= ?))) ORDER BY "t1"."start_time"', ['office_camera', 1741708073.0])
frigate  | 2025-03-11 16:48:13.144535647  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : Found authorization header
frigate  | 2025-03-11 16:48:13.146255269  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : current time:   Tue Mar 11 16:48:13 2025
frigate  | 2025-03-11 16:48:13.146472672  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : jwt expires at: Wed Mar 12 16:43:17 2025
frigate  | 2025-03-11 16:48:13.146475918  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : jwt refresh at: Wed Mar 12 04:43:17 2025
frigate  | 2025-03-11 16:48:13.213130990  192.168.51.90 - - [11/Mar/2025:16:48:13 +0100] "POST /api/go2rtc/webrtc?src=office_camera HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:13.214753487  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:13.246800331  [2025-03-11 16:48:13] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:13.247607527  192.168.51.90 - - [11/Mar/2025:16:48:13 +0100] "GET /api/office_camera/latest.jpg HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:14.198219545  [2025-03-11 16:48:14] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:14.199538003  192.168.51.90 - - [11/Mar/2025:16:48:14 +0100] "GET /api/office_camera/latest.jpg HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:15.218961947  [2025-03-11 16:48:15] frigate.api.auth               DEBUG   : No jwt token found
frigate  | 2025-03-11 16:48:15.220745440  192.168.51.90 - - [11/Mar/2025:16:48:15 +0100] "GET /api/office_camera/latest.jpg HTTP/1.1" 401 179 "-" "HomeAssistant/2025.3.1 aiohttp/3.11.13 Python/3.13" "-"
frigate  | 2025-03-11 16:48:15.463446578  [2025-03-11 16:48:15] asyncio                        DEBUG   : Using selector: EpollSelector
frigate  | 2025-03-11 16:48:15.478679981  [2025-03-11 16:48:15] peewee                         DEBUG   : ('SELECT "t1"."start_time", "t1"."end_time", "t1"."severity", "t1"."data" FROM "reviewsegment" AS "t1" WHERE (("t1"."camera" = ?) AND (("t1"."end_time" IS NULL) OR ("t1"."end_time" >= ?))) ORDER BY "t1"."start_time"', ['office_camera', 1741708084.0])
```

### Relevant go2rtc log output

```shell
2025-03-11 17:17:08.065004505  [INFO] Preparing new go2rtc config...
2025-03-11 17:17:08.740764875  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-03-11 17:17:09.009924788  [INFO] Starting go2rtc...
2025-03-11 17:17:09.113845581  17:17:09.113 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-03-11 17:17:09.114125985  17:17:09.114 DBG build vcs.time=2024-05-17T12:57:11Z version=go1.22.2
2025-03-11 17:17:09.114518131  17:17:09.114 INF config path=/dev/shm/go2rtc.yaml
2025-03-11 17:17:09.117444178  17:17:09.117 INF [api] listen addr=:1984
2025-03-11 17:17:09.117703120  17:17:09.117 INF [rtsp] listen addr=:8554
2025-03-11 17:17:09.118299294  17:17:09.118 INF [webrtc] listen addr=:8555
2025-03-11 17:17:09.118876332  17:17:09.118 DBG [hass] can't import config: open /config/.storage/core.config_entries: no such file or directory
2025-03-11 17:17:11.938583431  17:17:11.938 DBG [rtsp] new consumer stream=office_camera
2025-03-11 17:17:11.949013313  17:17:11.948 DBG [exec] run cmd="/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/office_camera?video&audio -c:v copy -c:a aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/01547013448de0ac1fd7b5361b39f679" url="exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/office_camera?video&audio -c:v copy -c:a aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/01547013448de0ac1fd7b5361b39f679"
2025-03-11 17:17:11.958062078  17:17:11.957 DBG [rtsp] new consumer stream=office_camera
2025-03-11 17:17:11.961977196  17:17:11.961 DBG [streams] start producer url=rtsp://admin:PWBH2lnktCV54NvRviD2@192.168.107.30:554/ch0_0.h264
2025-03-11 17:17:13.620182447  17:17:13.620 DBG [exec] run launch=1.671007867s
2025-03-11 17:17:13.620186815  17:17:13.620 DBG [streams] start producer url=ffmpeg:office_camera#video=copy#audio=aac#hardware
2025-03-11 17:17:18.087302896  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Yi-Home 1080p 

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c5e0f34c-d1b8-47eb-9776-720a653f719c)
