### DISCUSSION TITLE
[Support]: MQTT topic frigate/reviews end too fast

### DISCUSSION THREAD

**Discussion by Tux92** [blakeblackshear/frigate#17124] [General Support] [answered]
### Describe the problem you are having

I use mqtt topic `frigate/reviews` to trigger notification with HomeAssistant.
I describe what happen and what I expect.

One of my camera in front of Garage detect 1st car:
```
{
   "type":"new",
   "before":{
      "id":"1741798050.995885-gbz9ds",
      "camera":"Garage",
      "start_time":1741798050.995885,
      "end_time":null,
      "severity":"alert",
      "thumb_path":"/media/frigate/clips/review/thumb-Garage-1741798050.995885-gbz9ds.webp",
      "data":{
         "detections":[
            "1741798050.1257-cng439"
         ],
         "objects":[
            "car"
         ],
         "sub_labels":[
         ],
         "zones":[           
         ],
         "audio":[            
         ]
      }
   },
   "after":{
      "id":"1741798050.995885-gbz9ds",
      "camera":"Garage",
      "start_time":1741798050.995885,
      "end_time":null,
      "severity":"alert",
      "thumb_path":"/media/frigate/clips/review/thumb-Garage-1741798050.995885-gbz9ds.webp",
      "data":{
         "detections":[
            "1741798050.1257-cng439"
         ],
         "objects":[
            "car"
         ],
         "sub_labels":[            
         ],
         "zones":[          
         ],
         "audio":[            
         ]
      }
   }
}
```

The 1st person exit from 1st car and there is no update message, but in mqtt topic `frigate/events` I saw this:
```
{
  "before":{
    "id":"1741798075.345299-dw0x8l",
    "camera":"Garage",
    "frame_time":1741798075.345299,
    "snapshot":null,
    "label":"person",
    "sub_label":null,
    "top_score":0.0,
    "false_positive":true,
    "start_time":1741798075.345299,
    "end_time":null,
    "score":0.90234375,
    "box":[
      2366,
      865,
      2504,
      1207
    ],
    "area":47196,
    "ratio":0.40350877192982454,
    "region":[
      2202,
      796,
      2638,
      1232
    ],
    "active":true,
    "stationary":false,
    "motionless_count":0,
    "position_changes":0,
    "current_zones":[
      
    ],
    "entered_zones":[
      
    ],
    "has_clip":false,
    "has_snapshot":false,
    "attributes":{
      
    },
    "current_attributes":[
      
    ],
    "pending_loitering":false,
    "max_severity":"alert"
  },
  "after":{
    "id":"1741798075.345299-dw0x8l",
    "camera":"Garage",
    "frame_time":1741798075.505576,
    "snapshot":{
      "frame_time":1741798075.505576,
      "box":[
        2374,
        885,
        2524,
        1220
      ],
      "area":50250,
      "region":[
        2200,
        799,
        2652,
        1251
      ],
      "score":0.78515625,
      "attributes":[
        
      ]
    },
    "label":"person",
    "sub_label":null,
    "top_score":0.84375,
    "false_positive":false,
    "start_time":1741798075.345299,
    "end_time":null,
    "score":0.78515625,
    "box":[
      2374,
      885,
      2524,
      1220
    ],
    "area":50250,
    "ratio":0.44776119402985076,
    "region":[
      2200,
      799,
      2652,
      1251
    ],
    "active":true,
    "stationary":false,
    "motionless_count":1,
    "position_changes":0,
    "current_zones":[
      
    ],
    "entered_zones":[
      
    ],
    "has_clip":false,
    "has_snapshot":false,
    "attributes":{
      
    },
    "current_attributes":[
      
    ],
    "pending_loitering":false,
    "max_severity":"alert"
  },
  "type":"new"
}
```

Then 1st person exit from camera and after some time on `frigate/reviews`:
```
{
  "type":"end",
  "before":{
    "id":"1741798050.995885-gbz9ds",
    "camera":"Garage",
    "start_time":1741798050.995885,
    "end_time":null,
    "severity":"alert",
    "thumb_path":"/media/frigate/clips/review/thumb-Garage-1741798050.995885-gbz9ds.webp",
    "data":{
      "detections":[
        "1741798075.345299-dw0x8l",
        "1741798050.1257-cng439"
      ],
      "objects":[
        "person",
        "car"
      ],
      "sub_labels":[
        
      ],
      "zones":[
        "fronte_garage",
        "sotto_basculante"
      ],
      "audio":[
        
      ]
    }
  },
  "after":{
    "id":"1741798050.995885-gbz9ds",
    "camera":"Garage",
    "start_time":1741798050.995885,
    "end_time":1741798080.876119,
    "severity":"alert",
    "thumb_path":"/media/frigate/clips/review/thumb-Garage-1741798050.995885-gbz9ds.webp",
    "data":{
      "detections":[
        "1741798075.345299-dw0x8l",
        "1741798050.1257-cng439"
      ],
      "objects":[
        "person",
        "car"
      ],
      "sub_labels":[
        
      ],
      "zones":[
        "fronte_garage",
        "sotto_basculante"
      ],
      "audio":[
        
      ]
    }
  }
}
```

The strange is that on `reviews `topic I have only `new `and then `end`.

After some time arrive 2nd car but no message on `reviews` only this on  `events`:
```
{
  "before":{
    "id":"1741798869.123161-zmvkya",
    "camera":"Garage",
    "frame_time":1741798869.123161,
    "snapshot":null,
    "label":"car",
    "sub_label":null,
    "top_score":0.0,
    "false_positive":true,
    "start_time":1741798869.123161,
    "end_time":null,
    "score":0.953125,
    "box":[
      1638,
      647,
      1907,
      893
    ],
    "area":66174,
    "ratio":1.0934959349593496,
    "region":[
      1578,
      579,
      1942,
      943
    ],
    "active":true,
    "stationary":false,
    "motionless_count":0,
    "position_changes":0,
    "current_zones":[
      
    ],
    "entered_zones":[
      
    ],
    "has_clip":false,
    "has_snapshot":false,
    "attributes":{
      
    },
    "current_attributes":[
      
    ],
    "pending_loitering":false,
    "max_severity":"alert"
  },
  "after":{
    "id":"1741798869.123161-zmvkya",
    "camera":"Garage",
    "frame_time":1741798869.162658,
    "snapshot":{
      "frame_time":1741798869.162658,
      "box":[
        1621,
        646,
        1915,
        899
      ],
      "area":74382,
      "region":[
        1584,
        583,
        1948,
        947
      ],
      "score":0.94140625,
      "attributes":[
        
      ]
    },
    "label":"car",
    "sub_label":null,
    "top_score":0.947265625,
    "false_positive":false,
    "start_time":1741798869.123161,
    "end_time":null,
    "score":0.94140625,
    "box":[
      1621,
      646,
      1915,
      899
    ],
    "area":74382,
    "ratio":1.1620553359683794,
    "region":[
      1584,
      583,
      1948,
      947
    ],
    "active":true,
    "stationary":false,
    "motionless_count":1,
    "position_changes":0,
    "current_zones":[
      
    ],
    "entered_zones":[
      
    ],
    "has_clip":false,
    "has_snapshot":false,
    "attributes":{
      
    },
    "current_attributes":[
      
    ],
    "pending_loitering":false,
    "max_severity":"alert"
  },
  "type":"new"
}
```

The 2nd person exit from 2nd car and now I have this message on `reviews` with its corresponding end.
```
{
  "type":"new",
  "before":{
    "id":"1741799078.970113-r60rsl",
    "camera":"Garage",
    "start_time":1741799078.970113,
    "end_time":null,
    "severity":"alert",
    "thumb_path":"/media/frigate/clips/review/thumb-Garage-1741799078.970113-r60rsl.webp",
    "data":{
      "detections":[
        "1741799077.714644-rwjniv"
      ],
      "objects":[
        "person"
      ],
      "sub_labels":[
        
      ],
      "zones":[
        
      ],
      "audio":[
        
      ]
    }
  },
  "after":{
    "id":"1741799078.970113-r60rsl",
    "camera":"Garage",
    "start_time":1741799078.970113,
    "end_time":null,
    "severity":"alert",
    "thumb_path":"/media/frigate/clips/review/thumb-Garage-1741799078.970113-r60rsl.webp",
    "data":{
      "detections":[
        "1741799077.714644-rwjniv"
      ],
      "objects":[
        "person"
      ],
      "sub_labels":[
        
      ],
      "zones":[
        
      ],
      "audio":[
        
      ]
    }
  }
}
```

So in conclusion I'm expeting this on reviews topic:
- new for 1st car
- update for 1st person
- update because remain only 1st car
- update for 2nd car
- update for 2nd person
- update becausa remain 1st and 2nd car

A screen of the camera:
![Screenshot 2025-03-12 185159](https://github.com/user-attachments/assets/472e9216-1d72-4574-abfd-9a9b5a3890e4)

In Explore view I see all 2 cars as not ended event.
![image](https://github.com/user-attachments/assets/ed85cf45-42ad-49d5-8dbf-15b09421bd09)

### Version

0.15.0-cea210d

### What browser(s) are you using?

Brave Versione 1.76.73 Chromium: 134.0.6998.45 (Build ufficiale) (a 64 bit)

### Frigate config file

```yaml
Garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/Streaming/Channels/101
          roles:
            - detect
    detect:
      width: 2688
      height: 1520
      annotation_offset: -2000
    motion:
      mask: 
        0,0.68,0.143,0.566,0.292,0.472,0.355,0.442,0.551,0.446,0.746,0.459,0.898,0.48,1,0.553,1,0,0,0
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
    objects:
      track:
        - person
        - car
        - license_plate
        - bicycle
        - dog
        - cat
      filters:
        person:
          min_area: 10000
          max_area: 150000
          max_ratio: 0.6
          min_score: .75
        car:
          min_area: 20000
          max_area: 800000
          min_score: .75
          mask: 0.591,0.438,0.59,0.536,0.722,0.545,0.692,0.442
        bicycle:
          min_score: .75
    zones:
      fronte_garage:
        coordinates: 1,1,1,0.819,0.862,0.672,0.61,0.682,0.607,1
        inertia: 3
        loitering_time: 0
      sotto_basculante:
        coordinates: 0.694,1,0.669,0.896,0.804,0.874,0.888,0.83,0.981,1
        loitering_time: 0
        objects: car
        inertia: 3
    review:
      alerts: {}
      detections: {}
```

### Relevant Frigate log output

```shell
no log
```

### Relevant go2rtc log output

```shell
no log
```

### FFprobe output from your camera

```shell
no output
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
I copy after
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2T45G0P-I (1.68mm)

**Comment by NickM-27** [comment]
This is a combination of a few problems. First off if you have a motion mask that large then that is a major problem, and it is likely keeping cars from being detected correctly. The second review item wasn't created for the car because the car didn't enter the required zones in your config.

**Comment by Tux92** [comment]
The motion mask is large because the camera is 180° and in front of my house there is a street I don't want that camera process car and people on the street. Then the 2 zones I created are not required and I use only as filter in web frigate.
However you think that I have to enlarge fronte_garage zone (the orange one) to cover all the path and select only for car? This helps?

**Reply by Tux92** [reply]
This is my setup could you please help me to obtain:
1. Alert for people on the area not covered by motion mask
2. Alert for car in the driveway and in front of garage
3. Detection for all other object configured only in the area not coverd by motion mask

![image](https://github.com/user-attachments/assets/d240dea3-e490-452b-886a-1f303ffc6a0b)

**Reply by NickM-27** [reply]
I have a similar camera setup and realistically if you want it to work optimally then you shouldn't be using a large motion mask like that. Frigate is resigned to work efficiently detecting objects in the entire frame.

**Reply by Tux92** [reply, marked as answer]
ok I try to reduce motion mask (now on gui warning of large maks disappear) and enlarge zone garage_front, then restrict alert and detection only in garage_front zone. Is this right?

![image](https://github.com/user-attachments/assets/0f8bc60e-b16e-4ea0-b6ab-00333084e2cb)

camera config:
```
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp:/---
          roles:
            - detect
    detect:
      width: 2688
      height: 1520
      annotation_offset: -2000
    motion:
      mask: 0,0.426,0.135,0.345,0.315,0.301,0.689,0.307,1,0.423,1,0,0,0
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
    objects:
      track:
        - person
        - car
        - license_plate
        - bicycle
        - dog
        - cat
      filters:
        person:
          min_area: 10000
          max_area: 150000
          max_ratio: 0.6
          min_score: .75
        car:
          min_area: 20000
          max_area: 800000
          min_score: .75
        bicycle:
          min_score: .75
    zones:
      sotto_basculante:
        coordinates: 0.694,1,0.669,0.896,0.804,0.874,0.888,0.83,0.981,1
        loitering_time: 0
        objects: car
        inertia: 3
      garage_front:
        coordinates: 
          1,1,1,0.552,0.914,0.485,0.746,0.459,0.554,0.448,0.349,0.443,0.181,0.552,0,0.712,0,1
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: garage_front
      detections:
        required_zones: garage_front
```
