### DISCUSSION TITLE
[Config Support]: Wrong timestamp on frigate recordings/alerts timeline, correct time on Timestamp Overlay

### DISCUSSION THREAD

**Discussion by iparout** [blakeblackshear/frigate#17127] [Config Support] [answered]
### Describe the problem you are having

Although the time reported in the Debug -> Timestamp Overlay menu is correct, the time shown in alerts is wrong. Alerts show UTC time, instead of UTC+2, which is the correct for my country.

I have installed frigate on proxmox through [VE-Helper Scripts](https://community-scripts.github.io/ProxmoxVE/scripts?id=frigate)

I know LXC is not officially supported but I doubt that's the reason for my problem. everything else works great.

![Screenshot 2025-03-12 233713](https://github.com/user-attachments/assets/fa87d2fb-b97e-4e93-9fef-e63b5b46c9dd)

### Version

version: 0.15-1

### Frigate config file

```yaml
mqtt:
  enabled: false

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"
  
environment_vars:
  TZ: "Europe/Athens"

cameras:
  Iatreio: #Change this to a name of the camera that makes sense to you
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac #Insert this if your camera supports audio output
      inputs:
        - path: rtsp://XXXXXXXX #Change as per your camera documentation for high quality feed
          roles:
            - record
        - path: rtsp:// XXXXXXXX #Change as per your camera documentation for low quality feed
          roles:
            - detect
    detect:
      height: 360 #Change this to match the resolution of your detection channel (in this case channel 1)
      width: 640 #Change this to match the resolution of your detection channel (in this case channel 1)
      fps: 10 #This is the frame rate for detection, between 5-10 fps is sufficient.
    record:
      enabled: true
      retain:
        days: 60 #The number of days a recording will be kept for after a motion is detected.
        mode: active_objects
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    objects:
      track:
        - person
        - car

detectors:
  ov:
    type: openvino
    device: GPU
    model_path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

version: 0.15-1
```

### Relevant Frigate log output

```shell
Nothing
```

### Relevant go2rtc log output

```shell
Nothing
```

### Operating system

Proxmox

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
Nothing
```

### Object Detector

OpenVino
