### DISCUSSION TITLE
Can't get GenAI to work

### DISCUSSION THREAD

**Discussion by TheStigh** [blakeblackshear/frigate#17122] [Config Support]
### Describe the problem you are having

Trying to get GenAI to work for adding descriptions of snapshots recorded, but only get errors. Tried with both Gemini & OpenAI (both paid subscriptions). Easiest error to show is the Gemini.

Nothing regarding GenAI happens when it detect a car or person, but Frigate creates the snapshot and record the video.

If I go into `Explore` and select an event and choose `Regenerate` I get following error:
```
Type
warning
Timestamp
2025-03-12 17:21:00
Tag
frigate.genai.gemini
Message
Gemini returned an error: 503 DNS resolution failed for generativelanguage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=AAAA name=generativelanguage.googleapis.com is_balancer=0: Could not contact DNS servers
```

I should mention I use Pi-Hole on my LAN, but everything else as it should. And I use both OpenAI and Gemini elsewhere within my HA for different tasks.

### Version

0.15

### Frigate config file

```yaml
semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: True
  provider: gemini
  api_key: "***masked***"
  model: gemini-1.5-flash
  prompt: "Analyze the {label} in these images from the {camera} security camera. Focus on the actions, behavior, and potential intent of the {label}, rather than just describing its appearance."
  object_prompts:
    person: "Examine the main person in these images. What are they doing and what might their actions suggest about their intent (e.g., approaching a door, leaving an area, standing still)? Do not describe the surroundings or static details."
    car: "Observe the primary vehicle in these images. Focus on its movement, direction, or purpose (e.g., parking, approaching, circling). If it's a delivery vehicle, mention the company. Try your best to record the license plate of the vehicle."



cameras:
  my_ptz:
    genai:
      enabled: True # <- enable GenAI for your front camera
      use_snapshot: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ptz
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/ptz_sub
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - bird
```

### Relevant Frigate log output

```shell
Type
warning
Timestamp
2025-03-12 17:21:00
Tag
frigate.genai.gemini
Message
Gemini returned an error: 503 DNS resolution failed for generativelanguage.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=AAAA name=generativelanguage.googleapis.com is_balancer=0: Could not contact DNS servers
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Should not be needed
```

### Object Detector

Coral
