### DISCUSSION TITLE
[HW Accel Support]: How to verify OpenVINO is being used for Intel GPU accelerated Semantic Search?

### DISCUSSION THREAD

**Discussion by ammgws** [blakeblackshear/frigate#17141] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

HW: Intel Arc A310 passed through to docker as /dev/dri/renderD128 (already being used for ffmpeg hwaccel in frigate)

I also want to use the GPU for hw accel for semantic search.

First I enabled semantic search with the "small" model, confirmed it was working, then afterwards changed to the "large" model and restarted Frigate. I want to make sure it is using the GPU as expected, and not falling back to the CPU. The docs say that "OpenVINO will automatically be detected and used for Semantic Search in the default Frigate image." but I cannot find anything in the logs to confirm that.

Is there any way to verify OpenVINO is being used for Intel GPU accelerated Semantic Search?

### Version

0.15.0-cea210d

### Frigate config file

```yaml
semantic_search:
  enabled: True
  model_size: large
  reindex: false

logger:
    default: info
    logs:
      frigate.embeddings: debug
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
```

### Relevant Frigate log output

```shell
info
2025-03-14 15:17:52
frigate.embeddings.embeddings
Indexing tracked object embeddings...

info
2025-03-14 15:18:32
frigate.embeddings.embeddings
Embedded 1158 thumbnails and 0 descriptions in 40.5 seconds

debug
2025-03-14 16:32:42
frigate.embeddings.functions.onnx
models are already downloaded for jinaai/jina-clip-v1
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Install method

Proxmox via Docker

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

-

### Screenshots of the Frigate UI's System metrics pages

-
