### DISCUSSION TITLE
Snapshot event ID not matching MQTT event ID

### DISCUSSION THREAD

**Discussion by abrenneman87** [blakeblackshear/frigate#17156] [Ask A Question] [answered]
I've noticed a problem with mismatching event IDs when trying to retrieve a snapshot based on the MQTT after:id payload.  Here's an example.

My Frigate instance detected a vehicle this afternoon.  It took a snapshot (as expected), and passed the change event to MQTT (as expected).  My code received the MQTT event and tried to retrieve the corresponding snapshot.   When I investigated after its failure, here's what I found:

**Snapshot**
A snapshot named _Front-1741975616.16659-zgolc3.jpg_ was created.  It contains the correct image.  The filename indicates the snapshot event ID was _1741975616.16659-zgolc3_.

**MQTT**
A change event was passed to my MQTT server.  The payload for after:id is _1741975616.350521-fx1dht_.   The epoch timestamp indicates this separate event ID was created 0.18 seconds after the snapshot event ID was created, so it's clearly the same detection.

**Review thumbnail**
A review thumbnail was created in /clips/review/.  It contains the correct image but matches the MQTT event ID:  _thumb-Front-1741975616.350521-fx1dht.webp_

When I attempt to use the API to retrieve _https://frigate_instance/api/events/1741975616.350521-fx1dht/snapshot.jpg_, I receive a failure, with the JSON response indicating that the event is not found.  Since the snapshot created a separate [different] event ID, this is expected but problematic.

Is this the intended behavior?  If not, can someone suggest troubleshooting steps to make snapshot event ID match the MQTT event ID?

Here is my Frigate config:

```
database:
  path: /media/frigate/frigate.db

auth:
  enabled: false

mqtt:
  enabled: true
  host: IP_ADDRESS
  user: USER
  password: PASSWORD

birdseye:
  enabled: false

snapshots:
  enabled: true
  bounding_box: false
  clean_copy: false

record:
  retain:
    days: 14
    mode: motion
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  filters:
    person:
      threshold: 0.65
    car:
      threshold: 0.6

detect:
  fps: 10

go2rtc:
  streams:
    Front:
      - rtsp://CAMERA1_ADDRESS
    Rear:
      - rtsp://CAMERA2_ADDRESS
    Backyard:
      - rtsp://CAMERA3_ADDRESS
    West:
      - rtsp://CAMERA4_ADDRESS
    North:
      - rtsp://CAMERA5_ADDRESS

cameras:
  Front:
    enabled: true
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://CAMERA1_ADDRESS
          roles:
            - record
        - path: rtsp://CAMERA1_SUB_ADDRESS
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 360
      enabled: true
    motion:
      mask:
        - 0,1,0.364,1,0.322,0.81,0.265,0.712,0.101,0.65,0,0.658
        - 0,0.499,0,0,0.554,0,0.622,0,0.744,0,1,0,1,0.199,0.978,0.171,0.657,0.083,0.626,0.183,0.602,0.16,0.478,0.197,0.311,0.266,0.115,0.398
      threshold: 30
      contour_area: 20
      improve_contrast: true
    live:
      stream_name: Front
    objects:
      track:
        - car
      mask:
        - 0,0.494,0.303,0.258,0.595,0.149,0.628,0.184,0.657,0.075,0.979,0.161,1,0.258,1,0,0,0
        - 0.001,0.66,0,1,0.362,1,0.32,0.816,0.263,0.72,0.102,0.656
		
  Rear:
    enabled: true
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://CAMERA2_ADDRESS
          roles:
            - record
        - path: rtsp://CAMERA2_SUB_ADDRESS
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 360
      enabled: false
    motion:
      mask:
        - 0.395,0.925,0.4,1,0,1,0,0.92
        - 0,0,0,0.407,0.239,0.465,0.297,0.336,0.437,0.282,0.445,0.044,0.634,0.064,0.628,0.255,1,0.518,1,0
    live:
      stream_name: Rear
    objects:
      track:
        - person
        - dog
      mask: 
        0,0,0,0.406,0.239,0.466,0.297,0.334,0.437,0.282,0.445,0.044,0.635,0.063,0.629,0.255,1,0.521,1,0

  Backyard:
    enabled: true
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://CAMERA3_ADDRESS
          roles:
            - record
        - path: rtsp://CAMERA3_SUB_ADDRESS
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 360
      enabled: true
    motion:
      mask:
        - 0,0,1,0,1,0.531,0.862,0.414,0.765,0.378,0.765,0.338,0.765,0.32,0.737,0.317,0.728,0.328,0.728,0.365,0.705,0.361,0.703,0.314,0.658,0.309,0.655,0.295,0.611,0.293,0.61,0.351,0.446,0.356,0.352,0.365,0.357,0.391,0.344,0.387,0.337,0.369,0.281,0.39,0.281,0.425,0.261,0.43,0.252,0.4,0.203,0.419,0.196,0.456,0.173,0.456,0.165,0.431,0,0.483
        - 0.059,0.949,0.367,0.95,0.368,0.891,0.061,0.891
    live:
      stream_name: Backyard
    objects:
      track:
        - horse
      mask:
        - 0,0,0,0.486,0.162,0.434,0.174,0.459,0.199,0.457,0.204,0.419,0.25,0.402,0.261,0.428,0.284,0.427,0.283,0.39,0.332,0.371,0.343,0.389,0.358,0.393,0.356,0.365,0.611,0.353,0.768,0.38,0.863,0.414,1,0.535,1,0
        - 0.058,0.889,0.058,0.95,0.368,0.95,0.368,0.89

  West:
    enabled: true
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://CAMERA4_ADDRESS
          roles:
            - record
        - path: rtsp://CAMERA4_SUB_ADDRESS
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 360
      enabled: false
    motion:
      mask:
        - 0,0.412,0.169,0.321,0.278,0.278,0.361,0.278,0.419,0.263,0.44,0.259,0.455,0.254,0.456,0.207,0.464,0.186,0.476,0.188,0.486,0.141,0.61,0.125,0.614,0.184,0.654,0.196,0.664,0.255,0.743,0.289,1,0.781,1,0,0,0
        - 0.776,0.937,0.777,0.989,0.993,0.989,0.992,0.932
    live:
      stream_name: West

  North:
    enabled: true
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://CAMERA5_ADDRESS
          roles:
            - record
        - path: rtsp://CAMERA5_SUB_ADDRESS
          roles:
            - detect
    record:
      enabled: true
    detect:
      width: 640
      height: 360
      enabled: false
    motion:
      mask:
        - 0,0.656,0.319,0.431,0.394,0.352,0.454,0.338,0.524,0.342,0.667,0.35,0.744,0.374,0.755,0.308,0.817,0.298,0.902,0.314,0.966,0.358,1,0.433,1,0,0.398,0,0,0
        - 0.773,0.996,0.777,0.941,0.837,0.939,0.787,0.808,0.799,0.698,0.852,0.662,0.9,0.627,0.916,0.562,0.933,0.496,0.968,0.361,1,0.336,1,1
      threshold: 30
      contour_area: 20
      improve_contrast: true
    live:
      stream_name: North

version: 0.15-1
```
