### DISCUSSION TITLE
[Support]: Live view artifact

### DISCUSSION THREAD

**Discussion by Xplode85** [blakeblackshear/frigate#17162] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Both live view and thumbnail live view has artifacts on some cameras, on thumbnail live view it onløy shows up when there is actual video, not static image.
All affected cameras are Dahua of different types with different resolution.
2 non Dahua cameras does not show the artifact.
The problem has always been there from the system was setup with 0.14.
![Screenshot_11](https://github.com/user-attachments/assets/a6591e0c-6a40-4e08-a20f-8f69b6f50e32)
![Screenshot_12](https://github.com/user-attachments/assets/ddfbe881-397e-4f5c-bc66-d923fb6f9797)

### Steps to reproduce

It's a UI bug that's always there so no steps needed to reproduce on this system. 

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

Google Chrome 134.0.6998.89

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: ************
  password: ************

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

#detectors:
#  openvino:
#    type: openvino
#
detectors:
  coral:
    type: edgetpu
    device: usb
#  coral3:
#    type: edgetpu
#    device: pci:1
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ui:
  timezone: Europe/Oslo
  time_format: 24hour

record:
  enabled: true
  retain:
    days: 7
    mode: all
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  preview:
    quality: high
  sync_recordings: false

  alerts:
    retain:
      days: 3
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 3
    pre_capture: 5
    post_capture: 5
motion:
  enabled: true

review:
  alerts:
    labels:
      - dog
      - horse
      - motorcycle
      - person
      - bicycle
      - car

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
#  height: 600
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
#  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 7
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70

detect:
  enabled: true
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
#  width: 1920
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
#  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 3
  stationary:
    interval: 15
    threshold: 15

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - dog
    - horse
    - motorcycle
    - person
    - bicycle
    - car

  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 100
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 20000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.3
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 3.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
    car:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 500
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 50000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.3
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 3.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.75
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

go2rtc:
  streams:
    1_Huset:
      - rtsp://************:************@192.168.1.57:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:1_Huset#video=h265#hardware
    3_Observatoriet:
      - rtsp://************:************@192.168.1.52:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:3_Observatoriet#video=h265#hardware
    4_Taarnet:
      - rtsp://************:************@192.168.1.54/axis-media/media.amp
      - ffmpeg:4_Taarnet#video=h265#hardware
    6_Garasjeporter:
      - rtsp://************:************@192.168.1.56:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:6_Garasjeporter#video=h265#hardware
    7_Garasjedor:
      - rtsp://************:************@192.168.1.51:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:7_Garasjedor#video=h265#hardware
    8_Huset:
      - rtsp://************:************@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:8_Huset#video=h265#hardware
    9_Huset:
      - rtsp://************:************@192.168.1.59:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:9_Huset#video=h265#hardware
birdseye:
  enabled: true
  mode: objects
  width: 1920
  height: 1080
  layout:
    max_cameras: 4
    scaling_factor: 1.0

live:
  # Optional: Set the name of the stream that should be used for live view
  # in frigate WebUI. (default: name of camera)
  stream_name: camera_name
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
cameras: # EmpireTech IPC-T54IR-AS 3.6mm
  1_Huset:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://************:************@192.168.1.57:554/cam/realmonitor?channel=1&subtype=0
#        - path: rtsp://127.0.0.1:8554/1_Huset
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/1_Huset
          roles:
            - detect
    motion:
      mask: 0.867,0.035,0.969,0.036,0.97,0.058,0.868,0.06
      threshold: 27
      contour_area: 10
      improve_contrast: 'true'
  2_Bak_Uthuset: # Vivotek IB8369A
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.53:554/live.sdp
          roles:
            - record
            - audio
        - path: rtsp://192.168.1.53:554/live2.sdp
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
  3_Observatoriet: # # Amcrest IP5M-T1179EW-AI-V3
    enabled: true
    ffmpeg:
      inputs:
#        - path: rtsp://************:************@192.168.1.52:554/cam/realmonitor?channel=1&subtype=0
        - path: rtsp://127.0.0.1:8554/3_Observatoriet
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/3_Observatoriet
          roles:
            - detect
  4_Taarnet:  # Axis M1065-L
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/4_Taarnet
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/4_Taarnet
          roles:
            - detect
  5_Domen: # Vivotek FD816BA-HT
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.55:554/live.sdp
          roles:
            - record
            - audio
        - path: rtsp://192.168.1.55:554/live2.sdp
          roles:
            - detect
    motion:
      mask: 0.03,0.053,0.023,0.012,0.755,0.01,0.755,0.053
  6_Garasjeporter: # Amcrest IP5M-T1179EW-AI-V3
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/6_Garasjeporter
#        - path: rtsp://************:************@192.168.1.56:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/6_Garasjeporter
#        - path: rtsp://************:************@192.168.1.56:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    motion:
      mask: 0.701,0.001,0.702,0.052,0.984,0.058,0.984,0.005
  7_Garasjedor: # Amcrest IP5M-T1179EW-AI-V3
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/7_Garasjedor
#        - path: rtsp://************:************@192.168.1.51:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/7_Garasjedor
#        - path: rtsp://************:************@192.168.1.51:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    motion:
      mask: 0.712,0.001,0.712,0.056,0.989,0.056,0.988,0.005
      threshold: 30
      contour_area: 15
      improve_contrast: 'true'
  8_Huset:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://************:************@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0
#        - path: rtsp://127.0.0.1:8554/8_Huset
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/8_Huset
          roles:
            - detect
    motion:
      mask: 0.867,0.035,0.969,0.036,0.97,0.058,0.868,0.06
      threshold: 27
      contour_area: 10
      improve_contrast: 'true'
  9_Huset:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://************:************@192.168.1.59:554/cam/realmonitor?channel=1&subtype=0
#        - path: rtsp://127.0.0.1:8554/9_Huset
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/9_Huset
          roles:
            - detect
    motion:
      mask: 0.867,0.035,0.969,0.036,0.97,0.058,0.868,0.06
      threshold: 27
      contour_area: 10
      improve_contrast: 'true'
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
  Garasjen:
    order: 2
    icon: LuCar
    cameras:
      - 6_Garasjeporter
      - 7_Garasjedor
  Observatorie:
    order: 3
    icon: LuStar
    cameras:
      - 5_Domen
      - 4_Taarnet
      - 3_Observatoriet
  Uthuset/huset:
    order: 4
    icon: LuArmchair
    cameras:
      - 1_Huset
      - 2_Bak_Uthuset
```

### docker-compose file or Docker CLI command

```yaml
Using HaasOS
```

### Relevant Frigate log output

```shell
No relevent info in log
```

### Relevant go2rtc log output

```shell
No relevent info in log
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

EmpireTech IPC-T54IR-AS, Amcrest IP5M-T1179EW-AI-V3

### Screenshots of the Frigate UI's System metrics pages

There is no relevant info here.

### Any other information that may be helpful

If needed access to the system can be arranged for problem finding.
