### DISCUSSION TITLE
[Support]: frigate not recording "Could not clear 5124.530000000001 MB, currently 268.9 MB have been cleared. Retained recordings must be deleted."

### DISCUSSION THREAD

**Discussion by hagar17** [blakeblackshear/frigate#17161] [General Support]
### Describe the problem you are having

since updating to ver 15 frigate  keep giving me this error "Could not clear 5124.530000000001 MB, currently 268.9 MB have been cleared. Retained recordings must be deleted." and wont hold/show recorded events.
I tried everything i could find on forums sorry if tghis has been answered anywhere i tried the AI help but no luck 

thanks in advance for any help

### Version

 0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.202
  user: mqtt-user
  password: ********

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
#    frigate.record.maintainer: debug
    frigate.storage: debug


detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

#semantic_search:
#  enabled: true
#  reindex: false

ffmpeg:
  hwaccel_args: preset-vaapi
  
go2rtc:
  streams:
    garden_reolink_camera:
      - ffmpeg:http://192.168.2.222/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=*****#video=copy#audio=copy#audio=opus
    garden_reolink_camera_sub:
      - ffmpeg:http://192.168.2.222/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=******
    door_reolink_camera:
      - ffmpeg:http://192.168.2.223/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=*******#video=copy#audio=copy#audio=opus
    door_reolink_camera_sub:
      - ffmpeg:http://192.168.2.223/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=******
    lounge_reolink_camera:
      - ffmpeg:http://192.168.2.221/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=*******#video=copy#audio=copy#audio=opus
    lounge_reolink_camera_sub:
      - ffmpeg:http://192.168.2.221/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=******
    Dogcam_camera:
      - ffmpeg:http://192.168.2.89:98/videostream.cgi?user=admin&pwd=*******#video=h264#hardware"

cameras:
  garden_reolink:
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_reolink_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_reolink_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    audio:
      enabled: True
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    objects:
      track:
        - person
        - dog
        - car
        - bird

    motion:
      mask: 
        0.576,0.484,0.714,0.565,0.775,0.457,0.835,0.365,0.927,0.403,1,0.472,1,0,0.203,0,0.062,0,0,0,0,0,0,0.148,0.222,0.218,0.254,0.083,0.54,0.153,0.575,0.202,0.556,0.318
      threshold: 30
      contour_area: 20
      improve_contrast: true
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 5
          mode: motion
      detections:
        retain:
          days: 5
          mode: motion
        pre_capture: 3
        post_capture: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1

  door_reolink:
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/door_reolink_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/door_reolink_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    objects:
      track:
        - person
        - dog
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1100
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      alerts:
        retain:
          days: 2
          mode: motion
        pre_capture: 5
        post_capture: 10
      detections:
        retain:
          days: 2
          mode: motion
        pre_capture: 5
        post_capture: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1

  lounge_reolink:
    ffmpeg:
#      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/lounge_reolink_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lounge_reolink_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    objects:
      track:
        - person
        - dog
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      alerts:
        retain:
          days: 2
          mode: motion
        pre_capture: 5
        post_capture: 10
      detections:
        retain:
          days: 2
          mode: motion
        pre_capture: 5
        post_capture: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
#  pi_camera:
#    ffmpeg:
#       inputs:
#         - path: rtsp://192.168.2.39:8554/cam
#           roles:
#             - detect
  Dogcam_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Dogcam_camera
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - dog
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      alerts:
        retain:
          days: 5
          mode : motion
        pre_capture: 3
        post_capture: 10
      detections:
        retain:
          days: 5
          mode: motion
        pre_capture: 3
        post_capture: 10
version: 0.15-1
camera_groups:
  testCam1:
    order: 1
    icon: LuActivitySquare
    cameras:
      - door_reolink
      - garden_reolink
      - lounge_reolink
      - Dogcam_camera
```

### Relevant Frigate log output

```shell
debug | 2025-03-15 15:55:34 | frigate.storage | Storage cleanup check: 5124.530000000001 hourly with remaining storage: 4605.7.
info  | 2025-03-15 15:55:34 | frigate.storage | Less than 1 hour of recording space left, running storage maintenance...
debug | 2025-03-15 15:55:34 | frigate.storage | Starting storage cleanup.
error | 2025-03-15 15:55:34 | frigate.storage | Could not clear 5124.530000000001 MB, currently 266.4 MB have been cleared. Retained recordings must be deleted.
debug | 2025-03-15 15:55:34 | frigate.storage | Expiring 119 recordings
debug | 2025-03-15 16:00:34 | frigate.storage | Storage cleanup check: 5124.530000000001 hourly with remaining storage: 4589.6.
info  | 2025-03-15 16:00:34 | frigate.storage | Less than 1 hour of recording space left, running storage maintenance...
debug | 2025-03-15 16:00:34 | frigate.storage | Starting storage cleanup.
error | 2025-03-15 16:00:34 | frigate.storage | Could not clear 5124.530000000001 MB, currently 268.0 MB have been cleared. Retained recordings must be deleted.
debug | 2025-03-15 16:00:34 | frigate.storage | Expiring 120 recordings
```

### Relevant go2rtc log output

```shell
2025-03-15 15:00:14.660137081  [INFO] Preparing new go2rtc config...
2025-03-15 15:00:15.054681335  [INFO] Starting go2rtc...
2025-03-15 15:00:15.151571462  15:00:15.151 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-03-15 15:00:15.151574677  15:00:15.151 INF config path=/dev/shm/go2rtc.yaml
2025-03-15 15:00:15.152169655  15:00:15.152 INF [api] listen addr=:1984
2025-03-15 15:00:15.152172476  15:00:15.152 INF [rtsp] listen addr=:8554
2025-03-15 15:00:15.152295171  15:00:15.152 INF [webrtc] listen addr=:8555/tcp
2025-03-15 15:00:24.664334505  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
tony@frigatelounge://var/opt/frigate$ ffprobe ffmpeg:http://192.168.2.221/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Albastrea1#video=copy#audio=copy#audio=opus
[1] 2612583
[2] 2612584
[3] 2612585
[4] 2612586
[2]   Done                    app=bcs
tony@frigatelounge://var/opt/frigate$ ffprobe version 5.1.6-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
ffmpeg:http://192.168.2.221/flv?port=1935: Protocol not found
```

### Frigate stats

```json
cant find how to get this sorry
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
#version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024MB" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    group_add:
      - "44"  # Add your video group ID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/opt/frigate/config/:/config/
      - /var/opt/frigate/clips:/media/frigate/clips
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: radeonsi
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

reolink RLC-420-5MP

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-03-15 161203](https://github.com/user-attachments/assets/e1a34adf-d5cf-4c7c-88f8-d173cec4a252)
![Screenshot 2025-03-15 161054](https://github.com/user-attachments/assets/39a1d74c-9f33-4150-9764-cd2b9137c96d)
![Screenshot 2025-03-15 161123](https://github.com/user-attachments/assets/d9a81057-0c51-4784-a63c-db9b4d8ae5ea)

### Any other information that may be helpful

hardware info "{"return_code":0,"stderr":"","stdout":"vainfo: VA-API version: 1.22 (libva 2.10.0)
vainfo: Driver version: Mesa Gallium driver 22.3.6 for AMD Radeon RX 580 Series (polaris10, LLVM 15.0.6, DRM 3.49, 6.1.0-31-amd64)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc"}

build on bare metal "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
