### DISCUSSION TITLE
[Support]: Export results in failure

### DISCUSSION THREAD

**Discussion by hassos246** [blakeblackshear/frigate#17167] [General Support]
All my attempts to export have failed.

Log: https://pastebin.com/WdYrrL7K

**Comment by hassos246** [comment]
Wasn't able to use the form for posting.

```
go2rtc:
  rtsp:
  streams:
    Allrummet:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.91:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Vardagsrummet:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.90:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Baksidan:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.0.92:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  webrtc:
    candidates:
      - 10.0.0.101:8555
      - stun:8555


cameras:
  Allrummet:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Allrummet
          roles:
            - audio
            - detect
            - record
    live:
      stream_name: Allrummet
    detect:
      enabled: true
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - person
        - face
        - cat
        - dog
        - bird
      filters:
        person:
          min_area: 6500
          min_score: 0.6
          threshold: 0.8
        cat:
          min_area: 6500
          min_score: 0.6
          threshold: 0.8
    onvif:
      host: 10.0.0.91
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    motion: {}
    genai:
      enabled: false
    audio:
      enabled: true
      listen:
        - fire_alarm #audio
    review:
      alerts:
        labels:
          - bird
          - dog
          - fire_alarm #audio


  Vardagsrummet:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Vardagsrummet
          roles:
            - audio
            - detect
            - record
    live:
      stream_name: Vardagsrummet
    detect:
      enabled: true
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - person
        - face
        - cat
        - dog
        - bird
      filters:
        cat:
          min_score: 0.6
          threshold: 0.8
        person:
          min_score: 0.6
          threshold: 0.8
    onvif:
      host: 10.0.0.90
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    motion: {}
    genai:
      enabled: false
    audio:
      enabled: true
      listen:
        - fire_alarm #audio
    review:
      alerts:
        labels:
          - bird
          - dog
          - fire_alarm #audio


  Baksidan:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Baksidan
          roles:
            - audio
            - detect
            - record
    live:
      stream_name: Baksidan
    detect:
      enabled: true
      width: 2304
      height: 1296
      fps: 5
    motion:
      mask:
        - 0.67,0.052,0.633,0,0.702,0
        - 0.952,0,0.935,0.539,0.919,1,1,0.69,1,0
      threshold: 30
      contour_area: 10
      improve_contrast: true
    genai:
      enabled: false
    objects:
      track:
        - person
        - face
        - cat
        - dog
        - umbrella
        - bird
        - bbq_grill
        - car
        - license_plate
        - bicycle
        - motorcycle
        - rabbit
        - deer
        - squirrel
        - fox
      mask: 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
      filters:
        person:
          min_score: 0.6
          mask:
            - 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
            - 0.089,0.972,0.096,0.937,0.067,0.84,0.034,0.753,0.016,0.657,0.036,0.637,0.027,0.555,0.024,0.487,0,0.376,0,0.682,-0.001,0.685,0.025,0.809,0.06,0.958
        car:
          mask:
            - 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
            - 0.22,0,0.237,0.345,0.932,0.542,0.949,0
            - 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
        cat:
          min_score: 0.6
          mask:
            - 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
            - 0.094,1,0.096,0.937,0.067,0.84,0.034,0.753,0.016,0.657,0.036,0.637,0.027,0.555,0.024,0.487,0,0.376,0,0.682,-0.001,0.685,0,1,0.082,1
            - 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
            - 0.221,0.148,0.308,0.108,0.393,0.115,0.392,0.278,0.324,0.256,0.319,0.212,0.225,0.25
            - 0.921,0.998,0.999,0.69,1,0,0.951,0,0.933,0.532
    audio:
      enabled: true
      listen:
        - air_horn #audio
        - alarm #audio
        - ambulance #audio
        - bark #audio
        - boom #audio
        - car_alarm #audio
        - civil_defense_siren #audio
        - emergency_vehicle #audio
        - explosion #audio
        - fire_alarm #audio
        - fire_engine #audio
        - gunshot #audio
        - police_car #audio
        - siren #audio
    zones:
      zone_baksidan_yttre1:
        coordinates: 0.045,0.441,0.054,0.407,0.229,0.311,0.23,0.336
        loitering_time: 0
        inertia: 3
        objects:
          - bbq_grill
          - bicycle
          - bird
          - car
          - cat
          - deer
          - dog
          - fox
          - motorcycle
          - person
          - rabbit
          - squirrel
          - umbrella
      zone_baksidan_inre:
        coordinates: 
          0,1,1,1,1,0,0.936,0,0.939,0.2,0.566,0.146,0.568,0.376,0.397,0.335,0.392,0.115,0.312,0.108,0.226,0.148,0.234,0.334,0.042,0.443,0.037,0.377,0.023,0.339,0,0.342
        inertia: 3
        loitering_time: 0
        objects:
          - bicycle
          - bird
          - car
          - deer
          - dog
          - fox
          - motorcycle
          - rabbit
          - squirrel
          - umbrella
      zone_baksidan_yttre2:
        coordinates: 
          0,0.344,0,0,0.935,0,0.938,0.193,0.564,0.143,0.567,0.375,0.398,0.334,0.395,0.111,0.313,0.103,0.224,0.143,0.229,0.313,0.057,0.405,0.038,0.332
        loitering_time: 0
        inertia: 3
        objects:
          - bbq_grill
          - bicycle
          - bird
          - car
          - cat
          - deer
          - dog
          - fox
          - motorcycle
          - person
          - rabbit
          - squirrel
          - umbrella
    review:
      alerts:
        labels:
          - air_horn #audio
          - alarm #audio
          - ambulance #audio
          - bark #audio
          - bbq_grill
          - bicycle
          - bird
          - boom #audio
          - car
          - car_alarm #audio
          - cat
          - civil_defense_siren #audio
          - deer
          - dog
          - emergency_vehicle #audio
          - explosion #audio
          - face
          - fire_alarm #audio
          - fire_engine #audio
          - fox
          - gunshot #audio
          - license_plate
          - motorcycle
          - person
          - police_car #audio
          - rabbit
          - siren #audio
          - squirrel
          - umbrella
        required_zones:
          - zone_baksidan_yttre1
          - zone_baksidan_inre
          - zone_baksidan_yttre2


detect:
  enabled: true
  stationary:
    interval: 50
    threshold: 50


detectors:
  coral:
    type: edgetpu
    device: usb


ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy


genai:
  enabled: false
  provider: ollama
  base_url: http://10.0.0.100:11434
  model: llava-llama3:latest
  prompt: Describe the {label} in the sequence of images with as much detail as possible.
    Do not describe the background.


logger:
  default: info


model:
  path: plus://d49b4cd17f43a0c32bd01c6500b16f68


mqtt:
  enabled: true
  host: 10.0.0.20
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 15


record:
  enabled: true
  sync_recordings: false
  export:
    timelapse_args: -vf setpts=0.003*PTS -r 30
  preview:
    quality: very_high
  retain:
    days: 7
    mode: all
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30
  detections:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 30


semantic_search:
  enabled: true
  reindex: false
  model_size: large


snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  crop: false
  timestamp: true
  quality: 100
  retain:
    default: 60


timestamp_style:
  position: tl
  format: '%Y-%m-%d %H:%M:%S'


tls:
  enabled: false


ui:
  time_format: 24hour


version: 0.15-1
```




Docker compose:
```
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "650mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate_media:/media/frigate:rw
      - /home/daniel/frigate_config:/config:rw
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PLUS_API_KEY: *****
      LIBVA_DRIVER_NAME: i965
      TZ: Europe/Stockholm
      FRIGATE_RTSP_USER: "*****"
      FRIGATE_RTSP_PASSWORD: "*****"
      FRIGATE_MQTT_USER: "*****"
      FRIGATE_MQTT_PASSWORD: "*****"
volumes:

  frigate_media:
    external: true

```
