### DISCUSSION TITLE
[Support]: Not Submitting Snapshot to Frigate+

### DISCUSSION THREAD

**Discussion by nicoema** [blakeblackshear/frigate#17179] [Config Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I try to Submit a snapshot to Frigate+ (ex. This is not a car) it Says 'Submitted' but not get the green popup confirming it have been sent. And i don't show up on 'https://plus.frigate.video/'.
But if I pause a clip and send a frame to Frigate+ it works. It gives me a green popup confirming it have been sent. And I can see it on 'https://plus.frigate.video/'

### Steps to reproduce

1.
2.
3.
...

### Version

0.15.0

### Frigate config file

```yaml
############## FRIGATE ###################
#############  CONFIG  ###################
version: 0.15.0

ui:
  time_format: 24hour

timestamp_style:
  position: br
  format: '%Y/%m/%d %H:%M:%S'

mqtt:
  host: 192.***.*.***
  user: *****
  password: ******

model:
  path: plus://****

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  path: '5.0'


go2rtc:
  streams:
    reo_cam1_wide:
      - rtsp://***
    reo_cam1_wide_sub:
      - rtsp://***
    reo_cam1_zoom:
      - rtsp://***
    reo_cam1_zoom_sub:
      - rtsp://***
    hall_cam:
      - rtsp://***
    hall_cam_sub:
      - rtsp://***
    studio_cam:
      - rtsp://***
    studio_cam_sub:
      - rtsp://***

birdseye:
  enabled: false
  mode: continuous

camera_groups:
  Cameras:
    order: 1
    icon: LuRadiation
    cameras:
      - Door_Cam_Wide
      - Door_Cam_Zoom
      - Hall_Cam
      - Studio_Cam
semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: true
  provider: openai
  api_key: "***"
  model: gpt-4o

##############################################################      
             ######---------  CAMERAS  -----------------######
##############################################################
cameras:
##############################################################
  Door_Cam_Wide:
    ffmpeg:
      inputs:
        - path: rtsp://***/reo_cam1_wide
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://***/reo_cam1_wide_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: reo_cam1_wide_sub
      height: 512
      quality: 2
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - face
        - license_plate
        - car
        - motorcycle
        - umbrella
        - postnord
        - ups
        - dhl
        - fedex
        - amazon
        - package
        - deer
        - fox
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          mask:
            - 0.819,0,1,0,1,0.698,0.91,0.656
            - 0.007,0.009,0.248,0.375,0.628,0.378,0.993,0.005
        face:
          min_score: 0.6
          threshold: 0.7
        car:
          min_score: 0.7
          threshold: 0.8
          mask: 
            0.168,0.425,0.439,0.441,0.705,0.453,0.729,0.388,1,0.449,1,0,0,0,0,0.619,0.065,0.371,0.147,0.371
        motorcycle:
          threshold: 0.8
        license_plate:
          threshold: 0.7
          mask:
            - 0.17,0.384,0.678,0.383,1,0.347,1,0,0,0,0,0.343
            - 0,1,1,1,1,0.543,0.652,0.639,0.272,0.688,0,0.643
        package:
          threshold: 0.8
    record:
      enabled: true
      sync_recordings: true
      retain:
        days: 3
        mode: motion
      alerts:
        pre_capture: 5
        post_capture: 8
        retain:
          days: 7
          mode: active_objects
      detections:
        retain:
          days: 7
          mode: active_objects
    snapshots:
      enabled: true
      clean_copy: false
      crop: true
      height: 500
      bounding_box: true
      retain:
        default: 4
      quality: 100
    motion:
      mask:
        - 1,0,0.629,0.398,0.248,0.402,0,0
        - 0.999,0,1,0.69,0.908,0.66,0.826,0
    zones:
      front_zone:
        inertia: 3
        coordinates: 1,1,1,0.785,0.915,0.72,0.66,0.814,0.578,0.751,0.316,0.734,0.301,1
        objects:
          - person
          - face
          - package
          - umbrella
          - postnord
          - ups
          - dhl
          - fedex
          - amazon
        loitering_time: 0
      Publick_zon:
        coordinates: 0,0,0,1,0.279,1,0.305,0.71,0.577,0.718,0.665,0.79,0.919,0.688,1,0.733,1,0
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: front_zone

    genai:
      enabled: true # <- enable GenAI
      use_snapshot: True
      prompt: "***"
      object_prompts:
        person: "***"
      objects:
        - person
      required_zones:
        - front_zone
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "300mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/:/config/ # Config and database
      - /opt/frigate/surveillance:/media/frigate #Save media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "***"
```

### Relevant Frigate log output

```shell
nop***
```

### Relevant go2rtc log output

```shell
nop***
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

Dlink, Reolink, Tapo

### Screenshots of the Frigate UI's System metrics pages

<img width="536" alt="frigate" src="https://github.com/user-attachments/assets/7296eaf7-4afe-4552-84a6-d6940ddf8128" />

### Any other information that may be helpful

I run Ubuntu 24.04.2 LTS
