### DISCUSSION TITLE
PLUS_API_KEY not being used

### DISCUSSION THREAD

**Discussion by schasj** [blakeblackshear/frigate#17177] [Config Support] [answered]
### Describe the problem you are having

I have obtained a Frigate+ key and added it to my docker command but the buttons do not appear on an image selected from the Explore page.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: server-ha

  # Optional: port (default: shown below)
  port: 1883

  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate

  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate

  # Optional: user
  user: steve

  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: REDACTED

  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt

  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key

  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false

  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral:

    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu

    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb

    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
#    num_threads: 3

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db

# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
#  path: /edgetpu_model.tflite

  # Optional: path to the labelmap (default: shown below)
#  labelmap_path: /labelmap.txt

  # Required: Object detection model input width (default: shown below)
  width: 320

  # Required: Object detection model input height (default: shown below)
  height: 320

  # Optional: Label name modifications. These are merged into the standard labelmap.
#  labelmap:
 #   2: vehicle

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info

  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

# Optional: set environment variables
environment_vars:
  EXAMPLE_VAR: value

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true

  # Optional: Width of the output resolution (default: shown below)
  width: 1280

  # Optional: Height of the output resolution (default: shown below)
  height: 720

  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning

  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []

  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -use_wallclock_as_timestamps 1

  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p

    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c copy -an

    # Optional: output args for rtmp streams (default: shown below)
#    rtmp: -c copy -f flv

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280

  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720

  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5

  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true

  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25

  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 10

    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25

  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30

  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2

  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2

  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50

  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
#  mask: 0,900,1080,900,1080,1920,0,1920

  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: false

  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: true

  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60

  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 10

    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true

  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true

  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true

  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true

  # Optional: crop the snapshot (default: shown below)
  crop: false

  # Optional: height to resize the snapshot to (default: original size)
  height: 175

  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []

  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10

# Optional: RTMP configuration
# NOTE: Can be overridden at the camera level
 #rtmp:
  # Optional: Enable the RTMP stream (default: True)
 #  enabled: True

# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720

  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl

  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%m/%d/%Y %H:%M:%S'

  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255

  # Optional: Line thickness of font (default: shown below)
  thickness: 2

  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
#  effect: 

# Required
cameras:
  # Required: name of the camera
  cam-drw:

    # Required: ffmpeg settings for the camera
    ffmpeg:

      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:

        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
        - path: rtsp://steve:REDACTED@cam-drw:554/h264Preview_01_sub

          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - audio

    detect:
      enabled: true
      fps: 5
      min_initialized: 2
      max_disappeared: 25 # consider 30 (note, detect FPS is 5)
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bicycle
        - motorcycle
        - car

      filters:
        person:
          max_area: 55000

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true

      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true

      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true

      # Optional: crop the snapshot (default: shown below)
      crop: true

      # Optional: height to resize the snapshot to (default: shown below)
      height: 270

      # Optional: jpeg encode quality (default: shown below)
      quality: 70

      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0

      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

    motion:
      mask: 0.999,0.07,1,0.002,0,0,0,0.077
      threshold: 25
      contour_area: 30
      improve_contrast: true
    zones:
      driveway:
        coordinates: 1,0.057,0.997,0.3,0.997,0.996,0.142,0.996,0.519,0.049
        loitering_time: 0
        inertia: 3

    review:
      alerts:
        required_zones: driveway


  cam-gaz:

    # Required: ffmpeg settings for the camera
    ffmpeg:

      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:

        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
        - path: rtsp://steve:REDACTED@cam-gaz:554/h264Preview_01_sub

          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - audio

    detect:
      enabled: true
      fps: 5
      min_initialized: 2
      max_disappeared: 25 # consider 30 (note, detect FPS is 5)
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bicycle


    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true

      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true

      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true

      # Optional: crop the snapshot (default: shown below)
      crop: true

      # Optional: height to resize the snapshot to (default: shown below)
      height: 270

      # Optional: jpeg encode quality (default: shown below)
      quality: 70

      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0

      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

    motion:
      mask:
        - 0.63,0,0.999,0.002,0.999,0.179,0.628,0.113
        - 0.002,0,0.403,0,0.332,0.338,0.285,0.353
      threshold: 25
      contour_area: 30
      improve_contrast: true
    zones:
      back_yard:
        coordinates: 0.629,0.106,0.003,0.349,0.005,0.998,1,0.998,0.999,0.181
        loitering_time: 0
        inertia: 3
      back_deck:
        coordinates: 0.377,0.296,0.386,0.068,0.526,0.074,0.627,0.149,0.661,0.306,0.539,0.357
        loitering_time: 0

        inertia: 3
    review:
      alerts:
        required_zones:
          - back_deck
          - back_yard


  cam-por:

    # Required: ffmpeg settings for the camera
    ffmpeg:

      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:

        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
        - path: rtsp://steve:REDACTED@cam-por:554/h264Preview_01_sub

          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - audio

    detect:
      enabled: true
      fps: 5
      min_initialized: 2
      max_disappeared: 25 # consider 30 (note, detect FPS is 5)
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bicycle

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true

      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true

      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true

      # Optional: crop the snapshot (default: shown below)
      crop: true

      # Optional: height to resize the snapshot to (default: shown below)
      height: 270

      # Optional: jpeg encode quality (default: shown below)
      quality: 70

      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0

      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

    motion:
      mask: 0.485,0.105,0.503,0,0.997,0,1,0.417
      threshold: 25
      contour_area: 30
      improve_contrast: true
    zones:
      front_steps:
        coordinates: 0.348,0.553,0.115,0.596,0.072,0.134,0.275,0.129
        loitering_time: 0
        inertia: 3
      front_porch:
        coordinates: 0.106,0.53,0.363,0.526,0.569,0.996,0.124,0.994
        loitering_time: 0
        inertia: 3
      front_walk_street:
        coordinates: 0.997,0.498,0.999,0.162,0.286,0.191,0.365,0.63
        inertia: 3
        loitering_time: 0
      front_walk_yard:
        coordinates: 0.588,0.998,0.854,0.994,0.609,0.532,0.401,0.585
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - front_walk_yard
          - front_walk_street
          - front_porch
          - front_steps


  pi-cam-01:

    # Required: ffmpeg settings for the camera
    ffmpeg:

      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:

        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
        - path: rtsp://pi-cam-01:8554/cam

          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect

    detect:
      enabled: true
      fps: 5
      min_initialized: 2
      max_disappeared: 25 # consider 30 (note, detect FPS is 5)
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bicycle

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true

      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true

      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true

      # Optional: crop the snapshot (default: shown below)
      crop: true

      # Optional: height to resize the snapshot to (default: shown below)
      height: 270

      # Optional: jpeg encode quality (default: shown below)
      quality: 70

      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    # Optional: Configuration for how camera is handled in the GUI.
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0

      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true

    motion:
      threshold: 25
      contour_area: 30
      improve_contrast: true


version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
I don't see anything relevant here...

s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2025-03-15 13:12:54.969523141  [INFO] Preparing new go2rtc config...
2025-03-15 13:12:54.970756472  [INFO] Preparing Frigate...
2025-03-15 13:12:54.971709221  [INFO] Starting NGINX...
2025-03-15 13:12:54.978326238  [INFO] No TLS certificate found. Generating a self signed certificate...
2025-03-15 13:12:55.181783134  [INFO] Starting Frigate...
2025-03-15 13:12:55.655036219  [INFO] Starting go2rtc...
2025-03-15 13:12:55.762338255  13:12:55.762 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-03-15 13:12:55.762380432  13:12:55.762 INF config path=/dev/shm/go2rtc.yaml
2025-03-15 13:12:55.763027169  13:12:55.762 INF [api] listen addr=:1984
2025-03-15 13:12:55.763572288  13:12:55.763 INF [rtsp] listen addr=:8554
2025-03-15 13:12:55.763752812  13:12:55.763 INF [webrtc] listen addr=:8555/tcp
2025-03-15 13:12:55.879130210  2025/03/15 13:12:55 [error] 189#189: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.3, server: , request: "GET /ws HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "server-v:5000"
2025-03-15 13:12:55.879135235  2025/03/15 13:12:55 [error] 189#189: *1 auth request unexpected status: 502 while sending to client, client: 192.168.1.3, server: , request: "GET /ws HTTP/1.1", host: "server-v:5000"
2025-03-15 13:12:55.879172834  192.168.1.3 - - [15/Mar/2025:13:12:55 -0600] "GET /ws HTTP/1.1" 500 579 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" "-"
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
2025-03-15 13:12:56.767267793  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
2025-03-15 13:12:56.948901473  127.0.0.1 - - [15/Mar/2025:13:12:56 -0600] "" 400 0 "-" "-" "-"
2025-03-15 13:12:58.305796632  [2025-03-15 13:12:58] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-03-15 13:12:58.422678633  [2025-03-15 13:12:58] frigate.util.config            INFO    : frigate config does not need migration...
2025-03-15 13:12:58.542396094  [2025-03-15 13:12:58] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
2025-03-15 13:12:58.560114703  [2025-03-15 13:12:58] peewee_migrate.logs            INFO    : Starting migrations
2025-03-15 13:12:58.560520823  [2025-03-15 13:12:58] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-03-15 13:12:58.804580557  [2025-03-15 13:12:58] frigate.app                    INFO    : Recording process started: 371
2025-03-15 13:12:58.812165445  [2025-03-15 13:12:58] frigate.app                    INFO    : Review process started: 380
2025-03-15 13:12:58.815535189  [2025-03-15 13:12:58] frigate.app                    INFO    : go2rtc process pid: 106
2025-03-15 13:12:58.837909133  [2025-03-15 13:12:58] detector.coral                 INFO    : Starting detection process: 387
2025-03-15 13:12:58.838568892  [2025-03-15 13:12:58] frigate.app                    INFO    : Embedding process started: 389
2025-03-15 13:12:58.855165614  [2025-03-15 13:12:58] frigate.app                    INFO    : Output process started: 412
2025-03-15 13:12:58.886365182  [2025-03-15 13:12:58] frigate.app                    INFO    : Camera processor started for cam-drw: 426
2025-03-15 13:12:58.908206695  [2025-03-15 13:12:58] frigate.app                    INFO    : Camera processor started for cam-gaz: 429
2025-03-15 13:12:58.908846257  [2025-03-15 13:12:58] frigate.app                    INFO    : Camera processor started for cam-por: 438
2025-03-15 13:12:58.909120780  [2025-03-15 13:12:58] frigate.app                    INFO    : Camera processor started for pi-cam-01: 448
2025-03-15 13:12:58.928505035  [2025-03-15 13:12:58] frigate.app                    INFO    : Capture process started for cam-drw: 459
2025-03-15 13:12:58.962235642  [2025-03-15 13:12:58] frigate.app                    INFO    : Capture process started for cam-gaz: 477
2025-03-15 13:12:58.973020147  [2025-03-15 13:12:58] frigate.app                    INFO    : Capture process started for cam-por: 489
2025-03-15 13:12:59.004208940  [2025-03-15 13:12:59] frigate.app                    INFO    : Capture process started for pi-cam-01: 503
2025-03-15 13:12:59.323243046  [2025-03-15 13:12:59] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-03-15 13:12:59.482959920  [2025-03-15 13:12:59] frigate.api.fastapi_app        INFO    : FastAPI started
2025-03-15 13:13:01.980590811  [2025-03-15 13:12:58] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-03-15 13:13:01.985747624  [2025-03-15 13:13:01] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-03-15 13:13:04.971354656  [INFO] Starting go2rtc healthcheck service...
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
docker run -d \
--device /dev/dri/renderD128 \
--device /dev/bus/usb:/dev/bus/usb \
--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
--name frigate \
--restart unless-stopped \
--shm-size=1g \
--network=host \
-e TZ=America/Boise \
-e PLUS_API_KEY=REDACTED \
-v /Videos/frigate:/media/frigate \
-v /data/frigate:/config \
-v /etc/localtime:/etc/localtime:ro \
ghcr.io/blakeblackshear/frigate:stable
```

### Object Detector

Coral

### Any other information that may be helpful

I have verified that the key is available inside the docker container with:

# echo $PLUS_API_KEY
<correct key shown here>
#
