### DISCUSSION TITLE
Admin role not applying as expected (Dev branch)

### DISCUSSION THREAD

**Discussion by lngarrett** [blakeblackshear/frigate#17183] [General Support] [answered]
This issue stemmed from a [closed PR discussion.](https://github.com/blakeblackshear/frigate/pull/16978#issuecomment-2726499659)

I'm running dev branch `a995872`. My traffic flow is Cloudflare -> Traefik -> Frigate. On Cloudflare, I set the following headers:

```
    requestWithID.headers.set('x-forwarded-user', cfaccessemail);
    requestWithID.headers.set('x-forwarded-groups', "admin");
```

I've confirmed via Frigate nginx access log that the headers are present:

```
2025-03-16 11:47:32.375702700  172.31.0.3 - - [16/Mar/2025:11:47:32 -0400] "GET /api/eastcam/latest.webp?height=279&cache=1742140054053 HTTP/1.1" 200 34542 "https://frigate.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:136.0) Gecko/20100101 Firefox/136.0" "172.18.0.12"X-Forwarded-Groups: "admin" X-Forwarded-User: "lngarrett@gmail.com" 
```

My relevant Frigate config is as follows:

```
auth:
  enabled: false
  trusted_proxies:
    - 172.18.0.0/16
proxy:
  header_map:
    user: x-forwarded-user
    role: x-forwarded-groups
```

However, in the UI; I am still receiving the viewer role. This happens no matter what username I pass in via the user header.
