### DISCUSSION TITLE
[Bug]: Memory usage steadily increasing (8 days and going)

### DISCUSSION THREAD

**Discussion by kingp0dd** [blakeblackshear/frigate#17188] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Memory usage has been steadily increasing over time. Previously, I am limiting the docker container RAM usage to 4GB only, but it's causing docker to get OOM which results in Frigate constantly restarting hence missing detection for a few minutes.

So I upgraded my RAM. But now it's been 8 days and the RAM usage of the container is still steadily increasing.

I have searched and read other similar issues here. One of the threads I found talked about weak signal from one of his wireless cameras but all my cameras are wired.

I'm running the latest Frigate version in a Docker container. Docker is installed in a Debian 12 VM.

### Steps to reproduce

Just run the container normally and wait a few days

### Version

0.15.0-cea210d

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
tls:
  enabled: false

proxy:
  auth_secret: 
  header_map:
    user: X-Forwarded-Preferred-Username
  logout_url: /oauth2/sign_out

auth:
  enabled: false

mqtt:
  enabled: true
  host: hass.internal
  port: 1883
  topic_prefix: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  rtsp:
    username: restream
  webrtc:
    candidates:
      - stun:8555
  streams:
    reolink_doorbell:
      - ffmpeg:https://10.10.30.9/flv?port=1935&xxxxxxx
    living:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/102
    doorbell:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/202
    lanai:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/302
    storage:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/402
    backroof:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/502
    garage:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/602
    back:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/702
    kitchen:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/802
    balcony:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/902
    mastertop:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/1002
    dirtykitchen:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/1102
    maindoor:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/1202

    reolink_doorbell_hd:
      - ffmpeg:https://10.10.30.9/flv?port=1935&xxxxxxxxx
    living_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/101
    doorbell_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/201
    lanai_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/301
    storage_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/401
    backroof_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/501
    garage_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/601
    back_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/701
    kitchen_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/801
    balcony_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/901
    mastertop_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/1001
    dirtykitchen_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/1101
    maindoor_hd:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.10.20.2:554/Streaming/channels/1201

review:
  alerts:
    labels:
      - car
      - person

snapshots:
  enabled: true
  retain:
    # Required: Default retention days (default: shown below)
    default: 14
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70

# default for all cameras:
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 6

cameras:

  doorbell:
    ui:
      order: 1
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0.332,0,0.833,1,1,1,1,0,0.495,0
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    review:
      alerts:
        required_zones:
          - doorbell_sidewalk_zone
    live:
      stream_name: doorbell
    zones:
      doorbell_sidewalk_zone:
        coordinates: 0.331,0,0.834,1,0,1,0,0
        loitering_time: 0
        objects: person

    objects:
      filters:
        person:
          mask: 0.205,0.106,0.266,0.57,0.237,0.788,0.09,0.238
  reolink_doorbell:
    ui:
      order: 2
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_hd
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    review:
      alerts:
        labels:
          - person
        required_zones:
          - reolink_doorbell_sidewalk
      detections:
        labels:
          - person
        required_zones:
          - reolink_doorbell_road
    live:
      stream_name: reolink_doorbell
    motion:
      mask: 
        0,0,0,0.565,0.184,0.592,0.457,0.62,0.792,0.599,1,0.554,1,0.514,1,0.425,1,0.25,1,0,0.882,0
      threshold: 40
      contour_area: 19
      improve_contrast: 'true'
    zones:
      reolink_doorbell_sidewalk:
        coordinates: 
          0,0.666,0.076,0.716,0.293,0.799,0.318,0.819,0.512,0.842,0.754,0.81,0.828,0.771,1,1,1,1,0,1,0.004,0.946
        loitering_time: 0
        objects: person
        inertia: 3
      reolink_doorbell_road:
        coordinates: 
          0.082,0.583,0.222,0.607,0.458,0.634,0.893,0.592,0.995,0.557,0.995,0.658,0.857,0.752,0.746,0.818,0.515,0.848,0.333,0.83,0.233,0.77,0.069,0.717,0,0.666,0.002,0.577
        loitering_time: 0
        objects: person


  balcony:
    ui:
      order: 3
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/balcony
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/balcony_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0.248,0.305,0.276,0.23,0.674,0.619,0.722,0.575,0.942,0.756,1,0.463,1,0,0.207,0.003,0.032,0,0.034,0.145,0.147,0.316
      threshold: 30
      contour_area: 18
      improve_contrast: 'true'
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    review:
      alerts:
        required_zones:
          - balcony_balcony_zone
          - balcony_garage_zone
    live:
      stream_name: balcony
    zones:
      balcony_balcony_zone:
        coordinates: 0,0.196,0.437,1,0,1,0,0.218
        inertia: 3
        loitering_time: 0
        objects: person
      balcony_garage_zone:
        coordinates: 0.008,0.22,0.44,1,0.929,1,0.806,1,0.17,0.281
        loitering_time: 0
        objects: person


        inertia: 3
      balcony_pedestrian_gate_zone:
        coordinates: 0.412,0.931,0.452,1,0.572,1,0.809,1,0.577,0.746
        loitering_time: 0
        objects: person
  maindoor:
    ui:
      order: 4
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/maindoor
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/maindoor_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask: 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: maindoor


    zones:
      maindoor_pedestrian_gate_zone:
        coordinates: 1,0.457,0.6,0.047,0.534,0,0.88,0,1,0,1,0.27
        loitering_time: 0
        objects: person
  garage:
    ui:
      order: 5
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage_hd
          roles:
            - record
    detect:
      enabled: false
      # width: 1280
      # height: 720
    motion:
      enabled: false
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0.292,0,0.209,1,1,1,1,0
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: garage


    zones:
      garage_pedestrian_gate_zone:
        coordinates: 0,0.346,0.216,0.314,0.256,0.434,0.205,1,0,1,0,0.387
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: garage_pedestrian_gate_zone
  mastertop:
    ui:
      order: 6
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/mastertop
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/mastertop_hd
          roles:
            - record
    detect:
      enabled: false
      # width: 1280
      # height: 720
    motion:
      enabled: false
      mask: 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: mastertop


  storage:
    ui:
      order: 7
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/storage
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/storage_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0,0.534,0.122,0.536,0.786,0.536,0.857,0.577,1,0.541,1,0,0,0
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: storage

    objects:
      filters:
        person:
          mask:


            - 0.107,0.688,0.135,1,0,1,0,0.639
            - 0.803,0.478,0.891,0.423,0.943,0.635,0.869,0.68
  dirtykitchen:
    ui:
      order: 8
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/dirtykitchen
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/dirtykitchen_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask: 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    review:
      alerts:
        labels: []
      detections:
        labels:
          - person
    live:
      stream_name: dirtykitchen


  back:
    ui:
      order: 9
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0.114,0.353,0.167,0.393,0.319,0.567,0.593,0.809,0.977,0,0.529,0.002,0.098,0,0,0.134,0,0.441
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: back


  backroof:
    ui:
      order: 10
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/backroof
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backroof_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0.527,1,0.398,0.895,0.33,0.823,0.027,1,0.23,0.997
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: backroof

  lanai:
    ui:
      order: 11
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/lanai
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/lanai_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
        - 0.178,1,0.152,0.886,0.48,0,0,0,0,1
        - 0.839,0.671,1,0.275,1,1,0.791,1
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    live:
      stream_name: lanai


  kitchen:
    ui:
      order: 12
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/kitchen_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask: 0.287,0.018,0.003,0.021,0,0.078,0.289,0.071
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    review:
      alerts:
        labels: []
      detections:
        labels:
          - person
    live:
      stream_name: kitchen
    zones:
      kitchen_kitchen_zone:
        coordinates: 
          0.366,0.58,0.479,0.441,0.652,0.327,0.876,0.474,0.929,0.603,0.799,0.702,0.591,1,0.487,0.835
        loitering_time: 0
        objects: person
        inertia: 3
      kitchen_hallway_zone:
        coordinates: 0.589,1,0.327,0.511,0.031,0.63,0,1
        inertia: 1
        loitering_time: 0
        objects: person
      kitchen_dining_zone:
        coordinates: 0.186,0.301,0.263,0.56,0.595,0.349,0.63,0.217,0.513,0.096,0.18,0.261
        loitering_time: 5
        objects: person


  living:
    ui:
      order: 13
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/living
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/living_hd
          roles:
            - record
   #  detect:
      # enabled: true
      # width: 1280
      # height: 720
    motion:
      mask:
        - 0.287,0.018,0,0.014,0,0.078,0.29,0.078
        - 1,0.158,1,0.639,0,0.421,0,0,1,0
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 60
      detections:
        retain:
          days: 60
    review:
      alerts:
        labels: []
      detections:
        labels:
          - person
    live:
      stream_name: living
    zones:
      salas_couch:
        coordinates: 0.293,1,0.34,0.772,0.427,0.694,0.518,0.558,0.908,0.695,0.924,0.836,0.873,1
        loitering_time: 0
        objects: person
        inertia: 3
      salas_dining_table:
        coordinates: 
          0.152,0.489,0.302,0.332,0.401,0.298,0.491,0.519,0.253,0.886,0.142,0.637,0.176,0.585
        inertia: 3
        loitering_time: 0
        objects: person
      living_stairs_zone:
        coordinates: 
          0.91,0.283,0.652,0.296,0.518,0.435,0.42,0.404,0.216,0.666,0.151,0.594,0.056,0.702,0.183,1,0.345,1,0.559,0.669,0.933,0.736
        loitering_time: 0
        inertia: 3
        objects: person


version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 780mb # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config:/config
      - ./frigate/healthcheck.sh:/healthcheck.sh
      - ${DOCKER_MNT_FOLDER}/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      # - "8971:8971" # Web UI
      # Internal unauthenticated access. Expose carefully:
      - 5000:5000 
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
      FRIGATE_MQTT_USER: $FRIGATE_MQTT_USER
      FRIGATE_MQTT_PASSWORD: $FRIGATE_MQTT_PASSWORD
      # LIBVA_DRIVER_NAME: i965
    networks:
      - frigate
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
    #deploy:
      #resources:
        #limits:
          #memory: '4.0g'
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

HIKVision, Reolink Doorbell POE

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/fa9510b7-632d-4988-a7d9-689aa62fb2cf)
![image](https://github.com/user-attachments/assets/e096f2f7-27a0-478c-b4b9-40b7efb69680)
![image](https://github.com/user-attachments/assets/decd7082-dc53-448b-8697-967575e885ff)

### Any other information that may be helpful

This is the memory usage in Grafana for around 8 days since I upgraded my RAM. 

![image](https://github.com/user-attachments/assets/3b41edb3-a8b1-4931-8b7c-4722b45f3a51)

**Comment by NickM-27** [comment]
We need to know what process is using memory

**Reply by kingp0dd** [reply]
Is this output from htop enough. I also pasted the output from Grafana docker containers

![image](https://github.com/user-attachments/assets/b8ce6a84-983b-46d3-a6df-b32a2d6cdae9)

![image](https://github.com/user-attachments/assets/5f9aa1ec-4b48-457d-8931-d95f2134e9df)

There was high usage from mqtt-explorer in the grafana graph, but i have since disabled it. Frigate seems to steadily increase still afterwards

**Reply by NickM-27** [reply]
This seems like it may be the python behavior where there is not a true memory leak but python does not release the memory. https://github.com/blakeblackshear/frigate/discussions/10921

**Reply by kingp0dd** [reply]
What's the recommended configuration in this case? 

I've tried limiting the docker container using resource limits in compose, 

however, when the limit is reached, the python process gets killed through OOM. 

Frigate will detect this and will restart python. Frigate will recover automatically on its own but during the process, motion detection will be unavailable and will miss Alerts or Detections.

**Reply by NickM-27** [reply]
I believe python will stop after 10% of memory so perhaps just increase the memory limit to that point. There are some solutions shared in that post depending on how exactly Frigate is running

**Reply by kingp0dd** [reply]
I tried to dig deeper, please let me know if some of my assumptions are not accurate. I read https://github.com/blakeblackshear/frigate/discussions/10921 and it seems that the consensus is:

- If Frigate is running inside an LXC, python will check the total RAM of the Proxmox host instead of the LXC
- Python will consume 10% of the total RAM (in this case, it gets total RAM of Proxmox host instead of the LXC)
- Resulting to python consuming more than the LXC assigned RAM

In my case:
- Frigate is running inside a VM instead of an LXC
- meminfo inside Frigate's bash shows the correct VM assigned RAM:
```
inside Frigate container:
$ docker exec -it frigate cat /proc/meminfo | grep Total
MemTotal:       21230128 kB
SwapTotal:        999420 kB
VmallocTotal:   34359738367 kB
HugePages_Total:       0

inside VM:
$ cat /proc/meminfo  | grep Total
MemTotal:       21230128 kB
SwapTotal:        999420 kB
VmallocTotal:   34359738367 kB
HugePages_Total:       0
```
- VM RAM is set at 20GB, 10% of which is just 2GB
- Frigate on boot consumes 4GB already, and is steadily rising up to 6.5GB after 8 days

**Reply by kingp0dd** [reply]
Do you think that this is not related to python anymore and should be investigated further? Let me know if I need to open an issue and provide more logs/details.

I restarted Frigate 4 days ago, and it's RAM usage is still steadily rising (from 4.6GB to 6.3GB currently):

![image](https://github.com/user-attachments/assets/7ac34d3d-92de-462e-88b3-2758453ae252)

**Reply by kingp0dd** [reply]
To update, it's still increasing in memory usage. It's been at its highest usage today at 7GB

![Screenshot_20250424_230904_Firefox](https://github.com/user-attachments/assets/54c3d2e9-4168-4723-810f-2b6d03fd2e1f)

**Comment by jbcortes** [comment]
I'm running into a similar issue where memory usage will just keep increasing. Not sure if this has been pointed out, but for me this starts to occur when recording is enabled. For reference in the picture below, the memory usage in the first part of the graph is a new installation where there is one camera and the cpu is doing detection, the second portion is when I enabled openvino using an intel igpu, and the third section is when I enabled recording (in the two prior portions of the graph, recording was not enabled).
![frigate-02](https://github.com/user-attachments/assets/40aeafcf-2d7d-41c3-8be5-3f65c24454b1)

**Comment by ekaszubski** [comment]
I'm seeing a very similar issue, but as far as I can tell it only happens when I actually load the camera stream via the frigate dashboard, and rather than taking a few days it takes a few seconds.

If I never open the dashboard, then everything (detection and recording) seemingly works perfectly. Same is true I go directly to another camera's live view. But as soon as I open the dashboard/live view, `frigate.capture:<camera>` goes from using ~75 MB to > 2 GB in literally 7 seconds and keeps climbing until OOM kills it a few seconds later.

This happens so fast I don't even see the spike in proxmox. I haven't tried watching the camera's stream directly via go2rtc but I suspect I won't see any issue since the only process blowing up is `frigate.capture`. Typical RAM usage for the frigate VM reported by proxmox is 3.2 GB.

My setup is:
- Ryzen 5800X3D
- 128 GB DDR4 3600
- RTX 3080 Ti
- PCIe dual coral
- PVE 8.4.1 (Linux 6.8.12-10-pve)
  - zfs arcmax = 4 GB
  - Other VM's and CTs occupy 102 GB RAM
  - VM for frigate with 8 GB RAM balloon=0, 8x VCPU type=host
    - Ubuntu Server 24.04.2 (Linux 6.8.0-60)
    - GPU via PCIe passthrough
    - dual coral via PCIe passthrough
    - nvidia-driver-570
    - 8 TB HDD for recording mounted via NFS
    - docker-compose (configured via portainer)
      - frigate 0.16.0-beta1-tensorrt
        - shm_size: 4096mb
        - tmpfs size: 1 GB
        - face recognition enabled, large model
        - full hardware transcode (cuda/nvenc) for a few h256 streams to h264
      - 4x neolink 0.6.2, one for each of my Reolink cameras (all PoE)

The camera corresponding to the leak is a Reolink CX810 (firmware `v3.1.0.4666_2503072060`) with the main stream set to H.264 3840x2160 @ 25 FPS / 8192 Kbps. go2rtc grabs the stream (from neolink) via `rtsp://<neolink-CT-name>:8554/<camera-name>/main#video=copy#audio=aac`. The sub stream is disabled in neolink. The config for the camera looks like:
```yaml
<camera-name>:
  enabled: true
  live:
    streams:
      <stream-name>: <stream-name>
  ffmpeg:
    inputs:
      - path: rtsp://127.0.0.1:8554/<stream-name>?video=h264&audio=aac
        roles:
          - record
          - detect
  detect:
    enabled: true
  objects:
    track:
      - person
      - cat
      - dog
      - car
      - bicycle
  motion:
    mask: 0.093,0.966,0.161,0.966,0.161,0.994,0.093,0.994
    threshold: 30
    contour_area: 20
    improve_contrast: false
  review:
    alerts:
      labels:
        - person
        - cat
        - dog
        - bicycle
```

The relevant global config is:
```yaml
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
detect:
  enabled: true
  fps: 5
ffmpeg:
  hwaccel_args: preset-nvidia
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac
record:
  enabled: true
  retain:
    days: 21
    mode: all
  alerts:
    retain:
      days: 42
  detections:
    retain:
      days: 42
  export:
    timelapse_args: -vf setpts=PTS/30 -r 60
snapshots:
  enabled: true
  retain:
    default: 42
  quality: 100
go2rtc:
  ffmpeg:
    h264/cuda: -c:v h264_nvenc -g 50 -preset:v llhp -rc constqp -cq:v 23 -rc-lookahead 8
```
