### DISCUSSION TITLE
[Detector Support]: USB Coral using high CPU

### DISCUSSION THREAD

**Discussion by mabnz** [blakeblackshear/frigate#17189] [Detector Support] [answered]
### Describe the problem you are having

I have two detectors - a Coral PCI-e and Coral USB. The USB Coral seems to be using 20-101% CPU, as opposed to the PCI-e Coral which hovers about 5%. Is this expected?

### Version

0.15

### Frigate config file

```yaml
detectors:
  coral_pci:
    type: edgetpu
    device: pci
  coral_usb:
    type: edgetpu
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    cap_add:
        - PERFMON
        - CAP_PERFMON
        - SYS_ADMIN 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512MB"
    deploy:
      mode: replicated
      replicas: 1

    devices:
      - /dev/dri/:/dev/dri/
      - /dev/apex_0:/dev/apex_0

    volumes:
      - /frigate/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971" # HTTPS admin
      - "1984:1984" # go2rtc admin ux
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-03-17 at 3 21 48 PM](https://github.com/user-attachments/assets/b6b69596-e147-49ad-83b9-111444e79ad2)
