### DISCUSSION TITLE
Ability to insert a video filter before the scaling options for the detect stream?

### DISCUSSION THREAD

**Discussion by maples3** [blakeblackshear/frigate#17206] [General]
I'm using a couple of webcams with Frigate via ffmpeg, and one of them is a little buggy and needs its Display Aspect Ration to be corrected via the `setdar` ffmpeg filter.

Here is the current full config for the camera:
```yaml
  front_down_the_road:
    # NOTE: this camera is a little buggy, it seems to set aspect ratio parameters incorrectly
    ffmpeg:
      hwaccel_args: "" # temporarily disable hardware acceleration, it was causing issues during testing
      inputs:
        - path: /dev/video_6C
          input_args: -f v4l2 -video_size 1280x720 -format mjpeg
          roles:
            - detect
            - record

      output_args:
        detect: -vf "setdar=dar=16/9" -threads 2 -f rawvideo -pix_fmt yuv420p
        record: -vf "setdar=dar=16/9" -c:v h264_nvenc -preset p4 -profile high -cq 30 -tune hq -pix_fmt
          yuv420p -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -an

    # detect, motion, zones, review, objects...
```

For the recording, I have a manually-defined output command for each webcam, because nvenc can't handle the yuv422p pixel format that the webcams natively output.  If I add the `setdar` filter there, my recordings have the proper aspect ratio and all is well there.  The example I posted above works perfectly for recording.

However, I'm not having the same luck with the `detect` stream (which seems to power the live view in addition to detection).  With the example above, I get a distorted, flickering image like this in my live view:
![image](https://github.com/user-attachments/assets/58eadcc7-6f02-4ef2-b2fa-264f3b7114c2)

I believe this is because my `setdar` filter is being applied _after_ Frigate scales down the input to preview resolution.

From what I can tell, Frigate uses a ffmpeg command template something like this:
```
/usr/lib/ffmpeg/7.0/bin/ffmpeg {{ffmpeg.global_options}} {{ffmpeg.hwaccel_args}} {{ffmpeg.input_args}} -i {{ffmpeg.path_escaped}} {{ffmpeg.record_args}} /tmp/cache/{{camera_name}}@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=640:480 {{ffmpeg.detect_args}} pipe:
```

In my case, I think I need to apply the `setdar` filter before the `scale` filter, but there doesn't seem to be a way to do it, based on what I've found in the function `parse_preset_hardware_acceleration_scale` in `ffmpeg_presets.py`.

I realize this is a rather niche edge case I'm trying to work around, but I could see value in other cases by being able to apply a custom filter at the _beginning_ of the ffmpeg output arguments.  For example, something like this template:
```
/usr/lib/ffmpeg/7.0/bin/ffmpeg {{ffmpeg.global_options}} {{ffmpeg.hwaccel_args}} {{ffmpeg.input_args}} -i {{ffmpeg.path_escaped}} {{ffmpeg.NEW_OUPTUT_RECORD_FILTERS_ARG}} {{ffmpeg.record_args}} /tmp/cache/{{camera_name}}@%Y%m%d%H%M%S%z.mp4 {{ffmpeg.NEW_OUPTUT_DETECT_FILTERS_ARG}} -r 5 -vf fps=5,scale=640:480 {{ffmpeg.detect_args}} pipe:
```

This ability to _insert_ an argument (instead of replacing the arguments, which the current output_args do) could result in simpler configs for people who only need to make a slight tweak.  For example, really the only thing I _need_ to have set in my `output_args.record` is the `-pix_fmt=yuv420p`, the rest could probably be left at whatever Frigate has for NVENC defaults.

Alternatively, if the `output_args.detect` overrode _all_ output arguments instead of just some of them like it does now, that could also be helpful in edge cases like mine, in which case I'd insert the scale arguments manually there.  When setting up my `record` arguments, I remember coming across helpful error messages along the lines of "You're missing the segment_time and segment_format arguments in output_args.record, go add those!"; similar warnings could be output if the a simple string-search doesn't fine "scale" or "fps" in `output_args.detect`.  EDIT: `config.py`, function `verify_recording_segments_setup_with_reasonable_time` has the messages I'm remembering.

Anyway, this originally started as a [Camera Support] request but evolved a bit as I read a bit of code and learned more about how Frigate actually works.  Feel free to rename/recategorize this if it makes sense somewhere else besides a general discussion.

**Comment by maples3** [comment]
Update: this seems like exactly the reason that go2rtc exists: to take a messy input, clean it up, and present it cleanly to Frigate

For my buggy USB webcam, this is working nicely for getting the aspect ratio corrected for both previews and recordings.  It comes at the theoretical expense of slightly elevated CPU/GPU usage for decoding the h264 stream for the detection, but in practice I haven't noticed a difference in idle resource usage.
```yaml
go2rtc:
  streams:
    # NOTE: this camera is a little buggy, it seems to set aspect ratio parameters incorrectly
    front_down_the_road: exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -f v4l2 -video_size 1280x960 -framerate 15 -format mjpeg -i /dev/video_6C -vf "setdar=dar=16/9" -c:v h264_nvenc -preset p4 -profile high -cq 30 -tune hq -pix_fmt yuv420p -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {{output}}

cameras:
  front_down_the_road:
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/front_down_the_road
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
```

The `setdar` filter is applied in the go2rtc ffmpeg command, and the rest of the arguments are just for setting up the V4L camera input and NVENC hardware-accelerated encoding.  It's a bit long, but it works!
