### DISCUSSION TITLE
[Support]: MQTT frigate/reviews — way too many detections

### DISCUSSION THREAD

**Discussion by jazonh** [blakeblackshear/frigate#17214] [General Support]
### The Issue
I am trying to key off of frigate/reviews for Home Assistant automations, and I noticed that instead of a review ending in a timely fashion, it just stays open for 10, 20, 30 min at a time, collecting detections like crazy.

Looking for any clue as to how I can tame this.

### An Example Review
`{'type': 'update', 'before': {'id': '1742243523.766152-hknrnl', 'camera': 'Driveway', 'start_time': 1742243523.766152, 'end_time': None, 'severity': 'alert', 'thumb_path': '/media/frigate/clips/review/thumb-Driveway-1742243523.766152-hknrnl.webp', 'data': {'detections': ['1742244718.566104-orjtzx', '1742246533.736887-0dx98p', '1742245894.877874-l82zqk', '1742246791.84729-gmm6pf', '1742249093.057681-lctr9m', '1742245612.183431-sl90nf', '1742247335.522152-7ound0', '1742244332.719986-57e2wb', '1742244099.993678-fr0h7m', '1742247531.388178-h09svv', '1742244049.145354-osup68', '1742247137.391029-bgf2sr', '1742247303.397251-4sy667', '1742247150.164592-vul5id', '1742248630.776299-fo1l8f', '1742245318.161843-alpu3j', '1742247167.381421-u0h4pa', '1742246747.931887-2i3ovg', '1742247508.206384-2oprkr', '1742249934.245781-w79dhq', '1742247526.006883-hwspsn', '1742246931.362697-oiilfw', '1742250033.962352-gmerxy', '1742243342.156786-7s3bfi', '1742247341.784144-zx1l94', '1742246770.171366-q7hxvv', '1742246833.770815-ljj113', '1742249430.07754-1borga', '1742245966.946784-2cxgb6', '1742249932.641446-zc19ft', '1742247126.708407-2zgkum', '1742248968.601826-e3d9nm', '1742247434.693865-ughylq', '1742249732.240886-odyzsp', '1742244415.511412-qx4dc9', '1742245085.253308-3diceb', '1742243577.688482-rd40l7', '1742249930.84378-q1t7ck', '1742247644.988906-4g3v1v', '1742247857.184921-scsxjs', '1742248579.364005-mu4oj3', '1742246284.364449-mge7py', '1742248366.971149-rp5x6c', '1742247487.646231-pcrk71', '1742249580.875427-e4ipls', '1742247036.357189-qb84o6', '1742244083.795686-xbhaof', '1742246805.358076-89yeq0', '1742245095.566079-p88vkc', '1742247371.972633-g0tetu', '1742245529.751969-d4r1tr', '1742248516.560087-rz6go3', '1742248183.174661-jclq4u', '1742246898.38744-78glr4', '1742248901.060628-g7ifh4', '1742248005.364601-5paukk', '1742247383.957171-z4ps6j', '1742245040.727325-mlsmy8', '1742247630.618375-x7bq6i', '1742244090.593863-mgm8mc', '1742243358.828232-lin01q', '1742245800.601502-76hl27', '1742249671.125771-g8u6e5', '1742249823.272286-vw4m1a', '1742249178.436245-a7lu5v', '1742249831.468082-1inayp', '1742247193.801484-i10rrs', '1742243980.762883-7i3gu8', '1742243704.21223-g8hl4w', '1742243340.035752-4pki9v', '1742243613.650915-dge9hi', '1742249965.295105-qqm7yn', '1742244074.192374-b2e0zi', '1742249313.300693-pmnpc6', '1742246672.824925-8vcgbm', '1742243571.773037-9t3knl', '1742247632.941749-incut1', '1742249208.442349-hrd08p', '1742249911.973456-grlna3', '1742247506.521531-dee6ih', '1742243636.266581-tuei9z', '1742244669.543853-hpg8y7', '1742246291.37428-uapdsw', '1742249932.641446-ra6ezx', '1742247158.547319-vj2w00', '1742245522.179061-iaunud', '1742245204.386388-t4crnb', '1742249200.005564-um28du', '1742247171.571034-9kkjoi', '1742243648.731116-0lna1a', '1742244691.977536-dot66k', '1742246678.737042-e9lo4w'], 'objects': ['car', 'person'], 'sub_labels': [], 'zones': ['neighborhood', 'street'], 'audio': []}}, 'after': {'id': '1742243523.766152-hknrnl', 'camera': 'Driveway', 'start_time': 1742243523.766152, 'end_time': None, 'severity': 'alert', 'thumb_path': '/media/frigate/clips/review/thumb-Driveway-1742243523.766152-hknrnl.webp', 'data': {'detections': ['1742244718.566104-orjtzx', '1742246533.736887-0dx98p', '1742245894.877874-l82zqk', '1742246791.84729-gmm6pf', '1742249093.057681-lctr9m', '1742245612.183431-sl90nf', '1742247335.522152-7ound0', '1742244332.719986-57e2wb', '1742244099.993678-fr0h7m', '1742247531.388178-h09svv', '1742244049.145354-osup68', '1742247137.391029-bgf2sr', '1742247303.397251-4sy667', '1742247150.164592-vul5id', '1742248630.776299-fo1l8f', '1742245318.161843-alpu3j', '1742247167.381421-u0h4pa', '1742246747.931887-2i3ovg', '1742247508.206384-2oprkr', '1742249934.245781-w79dhq', '1742247526.006883-hwspsn', '1742246931.362697-oiilfw', '1742250033.962352-gmerxy', '1742243342.156786-7s3bfi', '1742247341.784144-zx1l94', '1742246770.171366-q7hxvv', '1742246833.770815-ljj113', '1742249430.07754-1borga', '1742245966.946784-2cxgb6', '1742249932.641446-zc19ft', '1742247126.708407-2zgkum', '1742248968.601826-e3d9nm', '1742247434.693865-ughylq', '1742249732.240886-odyzsp', '1742244415.511412-qx4dc9', '1742245085.253308-3diceb', '1742243577.688482-rd40l7', '1742249930.84378-q1t7ck', '1742247644.988906-4g3v1v', '1742247857.184921-scsxjs', '1742248579.364005-mu4oj3', '1742246284.364449-mge7py', '1742248366.971149-rp5x6c', '1742247487.646231-pcrk71', '1742249580.875427-e4ipls', '1742247036.357189-qb84o6', '1742244083.795686-xbhaof', '1742246805.358076-89yeq0', '1742245095.566079-p88vkc', '1742247371.972633-g0tetu', '1742245529.751969-d4r1tr', '1742248516.560087-rz6go3', '1742248183.174661-jclq4u', '1742246898.38744-78glr4', '1742248901.060628-g7ifh4', '1742248005.364601-5paukk', '1742247383.957171-z4ps6j', '1742245040.727325-mlsmy8', '1742247630.618375-x7bq6i', '1742244090.593863-mgm8mc', '1742243358.828232-lin01q', '1742245800.601502-76hl27', '1742249671.125771-g8u6e5', '1742249823.272286-vw4m1a', '1742249178.436245-a7lu5v', '1742249831.468082-1inayp', '1742247193.801484-i10rrs', '1742243980.762883-7i3gu8', '1742243704.21223-g8hl4w', '1742243340.035752-4pki9v', '1742243613.650915-dge9hi', '1742249965.295105-qqm7yn', '1742244074.192374-b2e0zi', '1742249313.300693-pmnpc6', '1742246672.824925-8vcgbm', '1742243571.773037-9t3knl', '1742247632.941749-incut1', '1742249208.442349-hrd08p', '1742249911.973456-grlna3', '1742247506.521531-dee6ih', '1742243636.266581-tuei9z', '1742244669.543853-hpg8y7', '1742246291.37428-uapdsw', '1742249932.641446-ra6ezx', '1742247158.547319-vj2w00', '1742245522.179061-iaunud', '1742245204.386388-t4crnb', '1742249200.005564-um28du', '1742247171.571034-9kkjoi', '1742243648.731116-0lna1a', '1742244691.977536-dot66k', '1742246678.737042-e9lo4w'], 'objects': ['car', 'person'], 'sub_labels': [], 'zones': ['neighborhood', 'street'], 'audio': []}}}
`

### My Hardware
- Beelink EQR5 AMD Ryzen™ 7 5825U, 32GB RAM
- USB Coral TPU

### Version

0.15.0-cea210d

### What browser(s) are you using?

Arc Version 1.85.1 (59724) Chromium Engine Version 134.0.6998.45

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: U
  password: P

go2rtc:
  streams:
    Driveway:
      - rtsp://U:P@ip.ip.ip.ip/live
      - ffmpeg:Driveway#audio=aac

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: true
  fps: 5

record:
  enabled: true

review:
  alerts:
    labels:
      - person
      - car
      - dog
      - package

objects:
  track:
    - person
    - car
    - dog
    - cat
    - package

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - record
            - detect
            - audio
    # mqtt:
    #   timestamp: false
    #   bounding_box: false
    #   crop: true
    #   quality: 100
    #   height: 800
    motion:
      mask: 0,0,0,0.284,0.515,0.202,1,0.285,1,0
    zones:
      driveway:
        coordinates: 0.977,1,0,1,0,0.713,0.121,0.616,0.373,0.461,0.708,0.467
        loitering_time: 0
        inertia: 3
      front_yard_tree:
        coordinates: 0.119,0.419,0.363,0.465,0.165,0.58,0,0.706,0,0.476
        loitering_time: 0
        inertia: 3
      front_yard_mb:
        coordinates: 0.708,0.466,0.793,0.469,1,0.694,0.998,1,0.976,1
        loitering_time: 0
        inertia: 3
      street:
        coordinates: 0.243,0.368,0.098,0.413,0.361,0.461,0.846,0.468,0.794,0.392,0.515,0.382
        loitering_time: 5
        inertia: 3
      neighborhood:
        coordinates: 
          0,0.474,0,0.444,0.086,0.406,0.131,0.356,0.162,0,0.813,0,0.869,0.392,1,0.478,1,0.688,0.8,0.47,0.851,0.471,0.792,0.387,0.501,0.376,0.246,0.364,0.094,0.41,0.109,0.42
        loitering_time: 20
        inertia: 3
    review:
      alerts:
        labels:
          - person
          - car
          - package
        required_zones:
          - driveway
          - front_yard_tree
          - front_yard_mb
          - street
    objects:
      filters:
        person:
          mask:
            - 0.739,0.35,0.736,0.469,0.758,0.475,0.764,0.351
            - 0.788,0.354,0.811,0.356,0.809,0.465,0.797,0.462
            - 0.155,0.357,0.169,0.357,0.167,0.316,0.15,0.316
            - 0.208,0.512,0.219,0.545,0.231,0.536,0.226,0.5
snapshots:
  enabled: true
  timestamp: false
  bounding_box: false
  crop: true
  height: 800
  quality: 100
  clean_copy: true
version: 0.15-1
```

### Relevant Frigate log output

```shell
See description
```

### Relevant go2rtc log output

```shell
See description
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":1920,"height":1080,"avg_frame_rate":"20/1"},{"codec_long_name":"AAC (Advanced Audio Coding)","avg_frame_rate":"0/0"}]}}]
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Wyze v3
