### DISCUSSION TITLE
[Config Support]: Using zones, MQTT event for person occupation but alert not registered for review

### DISCUSSION THREAD

**Discussion by 6BL9U** [blakeblackshear/frigate#17215] [Config Support] [answered]
### Describe the problem you are having

I am using home assistant to turn on a porch light in the early morning for an hour but I noticed it turned off after a minute when an automation for person occupancy was triggered. In review and explore I did not find an alert that matched the occurrence but in home assistant's logbook I found the event that occurred.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.5
  user: redacted
  password: redacted

detectors:
  tensorrt_1:
    type: tensorrt
    device: 0
  tensorrt_2:
    type: tensorrt
    device: 0
  tensorrt_3:
    type: tensorrt
    device: 0

tls:
  enabled: false

model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

birdseye:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

detect:
  width: 1280
  height: 960
  fps: 5

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_score: 0.8
      threshold: 0.8
    cat:
      min_score: 0.8
      threshold: 0.8
    dog:
      min_score: 0.8
      threshold: 0.8

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 28
  detections:
    retain:
      days: 14

go2rtc:
  streams:
    street:
      - ffmpeg:http://192.168.0.19/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted
      - ffmpeg:street#video=copy#audio=opus
    front_door:
      - ffmpeg:http://192.168.0.25/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted
      - ffmpeg:front_door#video=copy#audio=opus
    driveway_1:
      - ffmpeg:http://192.168.0.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted
      - ffmpeg:driveway_1#video=copy#audio=opus
    driveway_2:
      - ffmpeg:http://192.168.0.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted
      - ffmpeg:driveway_2#video=copy#audio=opus
    backyard_1:
      - ffmpeg:http://192.168.0.23/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted
      - ffmpeg:backyard_1#video=copy#audio=opus
    backyard_2:
      - ffmpeg:http://192.168.0.18/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=redacted&password=redacted
      - ffmpeg:backyard_2#video=copy#audio=opus
  webrtc:
    candidates:
      - 192.168.0.5:8555
      - redacted:8555

live:
  quality: 1

cameras:
  street:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street
          roles:
            - record
            - detect
    ui:
      order: 3
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record
            - detect
    ui:
      order: 2
    zones:
      porch:
        coordinates: 
          0,0.216,0.204,0.167,0.349,0.146,0.597,0.169,0.239,0.259,0.527,0.444,0.529,0.725,0.739,0.582,1,0.766,1,1,0,1
        loitering_time: 0
        objects: person
        inertia: 3
  driveway_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_1
          roles:
            - record
            - detect
    ui:
      order: 4
  driveway_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_2
          roles:
            - record
            - detect
    ui:
      order: 1
  backyard_1:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_1
          roles:
            - record
            - detect
    ui:
      order: 6
  backyard_2:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_2
          roles:
            - record
            - detect
    ui:
      order: 5
version: 0.15-1
camera_groups: {}
semantic_search:
  enabled: false
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  pv2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    env_file:
      - ./govee2mqtt/.env
    # Host networking is required
    network_mode: host

  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "640mb"
    volumes:
      - ./frigate/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/WDPurple6TB:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      # - "8971:8971"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - YOLO_MODELS=yolov7x-320
```

### Object Detector

TensorRT
