### DISCUSSION TITLE
[HW Accel Support]: No HW Acceleration in ffmpeg/frigate since upgrade to HAOS 15.0

### DISCUSSION THREAD

**Discussion by rober3847** [blakeblackshear/frigate#17229] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I'm running home assistant in a Proxmox VM with GPU passthrough, this has been working well for sometime with Frigate using
ffmpeg:
hwaccel_args: -qsv_device /dev/dri/renderD128

After upgrading to Home Assistant OS 15.0 my camera streams failed to start in Frigate.
Running vainfo inside the frigate container shows (with OS15.0)

`# vainfo
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit`

Previously with OS 14.2 vainfo returned -
`# vainfo 
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats`

I raised this issue in the home assistant os repo and was refered over here - 
It seems the Intel driver (the userspace part) in the Frigate container is not compatible with the i915 driver in Linux 6.12.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant.local
  user: homeassistant
  password: password

ffmpeg:
  hwaccel_args: -qsv_device /dev/dri/renderD128
  # hwaccel_args: -vaapi_device /dev/dri/renderD128


timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'

go2rtc:
  streams:
    West_Door_Sub:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/102
    West_Door:
      - ffmpeg:West_Door_Sub#video=h264
    West_Door_Main:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/101
    West_Door_Main_h264:
      - ffmpeg:West_Door_Main#video=h264
    Front_Door_Sub:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/202
    Front_Door:
      - ffmpeg:Front_Door_Sub#video=h264
    Front_Door_Main:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/201
    Front_Door_Main_h264:
      - ffmpeg:Front_Door_Main#video=h264
    East_Door_Sub:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/302
    East_Door:
      - ffmpeg:East_Door_Sub#video=h264
    East_Door_Main:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/301
    East_Door_Main_h264:
      - ffmpeg:East_Door_Main#video=h264
    Kitchen_Door_Sub:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/402
    Kitchen_Door:
      - ffmpeg:Kitchen_Door_Sub#video=h264
    Kitchen_Door_Main:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/401
    Kitchen_Door_Main_h264:
      - ffmpeg:Kitchen_Door_Main#video=h264
    Back_Door_Sub:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/502
    Back_Door:
      - ffmpeg:Back_Door_Sub#video=h264
    Back_Door_Main:
      - rtsp://username:password@192.168.1.100:554/Streaming/Channels/501
    Back_Door_Main_h264:
      - ffmpeg:Back_Door_Main#video=h264
    webrtc:
      candidates:
        - 172.16.0.72:8555
        - stun:8555


detectors:
  coral:
    type: edgetpu
    device: pci

birdseye:
  enabled: true
  mode: continuous
  layout:
    max_cameras: 6

objects:
  track:
    - person
    - dog
    - cat

detect:
  fps: 10

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 1
    mode: motion
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  alerts:
    retain:
      days: 3
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 3
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: false
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 2
    objects:
      dog: 1
  quality: 90


cameras:
  West_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/West_Door_Sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/West_Door_Main
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    live:
      stream_name: West_Door
    detect:
      enabled: true
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 3
        objects:
          dog: 1
      required_zones:
        - Driveway_West
    record:
      enabled: true
    motion:
      mask:
        - 221,0,217,32,0,37,0,0
        - 0,0,640,0,640,61,0,167
    zones:
      Driveway_West:
        coordinates: 77,480,640,480,530,109,77,187
    mqtt:
      enabled: true
      bounding_box: true
      timestamp: true
      crop: true
    review:
      alerts:
        required_zones: Driveway_West
  Front_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door_Sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front_Door_Main
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    live:
      stream_name: Front_Door
    detect:
      enabled: true
    snapshots:
      enabled: true
    record:
      enabled: true
    motion:
      mask:
        - 223,0,220,41,0,45,0,0


  East_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/East_Door_Sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/East_Door_Main
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    live:
      stream_name: East_Door
    detect:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - Driveway_East
    record:
      enabled: true
    motion:
      mask:
        - 223,0,220,41,0,44,0,0
        - 640,0,0,0,0,66,640,128,640,126
    zones:
      Driveway_East:
        coordinates: 77,480,640,480,584,146,309,114,0,115,0,224
    mqtt:
      enabled: true
      bounding_box: true
      timestamp: true
      crop: true

    review:
      alerts:
        required_zones:
          - Driveway_East
  Kitchen_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Kitchen_Door_Sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Kitchen_Door_Main
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    live:
      stream_name: Kitchen_Door
    detect:
      enabled: true
    snapshots:
      enabled: true
    record:
      enabled: true
    motion:
      mask:
        - 223,0,227,41,0,43,0,0
    zones:
      Outside_Kitchen:
        coordinates: 0,1,1,1,0.77,0.221,0.314,0.196,0,0.442
        objects:
          - dog
          - cat
          - person
        inertia: 5
        loitering_time: 0
    review:
      alerts:
        required_zones: Outside_Kitchen
      detections:
        required_zones: Outside_Kitchen
  Back_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Back_Door_Main
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
    live:
      stream_name: Back_Door
    detect:
      enabled: true
    snapshots:
      enabled: true
    record:
      enabled: true
    motion:
      mask:
        - 223,0,222,41,0,41,0,0
    zones:
      Decking:
        coordinates: 0.467,0.44,0.759,0.698,0.561,1,0.214,1,0.105,0.629
        objects:
          - dog
          - cat
          - person
        filters:
          person:
            threshold: 0.85
        inertia: 5
        loitering_time: 1
    review:
      alerts:
        required_zones: Decking
version: 0.15-1
semantic_search:
  enabled: true
  reindex: true
  model_size: small
tls:
  enabled: false
```

### docker-compose file or Docker CLI command

```yaml
N/A Home Assistant OS using Frigate Add On
```

### Relevant Frigate log output

```shell
Frigate logs the following
[AVHWDeviceContext @ 0x556dd5ddc400] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
2025-03-18 15:47:14.545206612  [2025-03-18 15:47:14] ffmpeg.Back_Door.detect        ERROR   : [AVHWDeviceContext @ 0x556dd5ddc400] Failed to initialise VAAPI connection: 1 (operation failed).
2025-03-18 15:47:14.545324738  [2025-03-18 15:47:14] ffmpeg.Back_Door.detect        ERROR   : Device creation failed: -5.
2025-03-18 15:47:14.547785016  [2025-03-18 15:47:14] ffmpeg.Back_Door.detect        ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Input/output error
2025-03-18 15:47:14.547787973  [2025-03-18 15:47:14] ffmpeg.Back_Door.detect        ERROR   : Error parsing global options: Input/output error
2025-03-18 15:47:14.560528310  [2025-03-18 15:47:14] frigate.video                  ERROR   : Kitchen_Door: Unable to read frames from ffmpeg process.
2025-03-18 15:47:14.561795638  [2025-03-18 15:47:14] frigate.video                  ERROR   : Kitchen_Door: ffmpeg process is not running. exiting capture thread...
2025-03-18 15:47:14.566535609  [2025-03-18 15:47:14] frigate.video                  ERROR   : Back_Door: Unable to read frames from ffmpeg process.
2025-03-18 15:47:14.566672301  [2025-03-18 15:47:14] frigate.video                  ERROR   : Back_Door: ffmpeg process is not running. exiting capture thread...
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision

### Screenshots of the Frigate UI's System metrics pages

<img width="1681" alt="Screenshot 2025-03-18 at 16 40 29" src="https://github.com/user-attachments/assets/113645ba-518a-484c-8b98-590696f0c92f" />
<img width="1681" alt="Screenshot 2025-03-18 at 16 40 13" src="https://github.com/user-attachments/assets/b5cd2456-e3ab-4f15-86c4-920474eb4c45" />
