### DISCUSSION TITLE
Need help setting up coral and quicksync on frigate (Docker Desktop - Windows 11)

### DISCUSSION THREAD

**Discussion by bobyelbob** [blakeblackshear/frigate#1723] [Ask A Question]
I am having issues when trying to use coral pcie on frigate. I installed the pcie driver and edgetpu runtime. I also installed the pycoral library and ran the test model successfully.

I'm thinking it has something to do with the devices in the docker-compose.yml but I can't find any information on how to pass the coral pcie device to frigate.

When passing the intel gpu I get this error. I saw some info for unraid where you need to install an intel community app. Any ideas how to get it to work on Docker Desktop?

> Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - error gathering device information while adding custom device "/dev/dri/renderD128": no such file or directory

-----------------------

Here is the docker-compose.yml:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - X:\Docker\frigate\config\config.yml:/config/config.yml:ro
      - X:\Surveillance:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

```
-----------------

config.yml:
```
mqtt:
  host: <localhost>
  port: 1883
  user: <user>
  password: <password>
  
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: <rtsp path>
          roles:
            - detect
            - clips
            - rtmp
            # - record
    width: 640
    height: 360
    fps: 5
    objects:
      track:
        - person
    clips:
      enabled: true
      
detectors:
  coral:
    type: edgetpu
    device: pci

```
--------------------------------

Error message:

```
frigate.edgetpu                INFO    : Attempting to load TPU as pci

Process detector:coral:

frigate.edgetpu                INFO    : No EdgeTPU detected.

frigate.app                    INFO    : Camera processor started for backyard: 45

frigate.app                    INFO    : Capture process started for backyard: 46

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate

    delegate = Delegate(library, options)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__

    raise ValueError(capture.message)

ValueError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector

    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)

  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__

    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate

    raise ValueError('Failed to load delegate from {}\n{}'.format(

ValueError: Failed to load delegate from libedgetpu.so.1.0
```

**Comment by TurboTronix** [comment]
I never got it to work.

**Comment by haggercody** [comment]
i was also keen to get my intel quicksync working on windows and i dug into WLS 2.0.. i'd read some posts that it should be possible with some of the newer versions of windows.  Ended up giving up and installed unbuntu desktop and everything worked with such ease.  Quicksync is a big difference in cpu for me--we are talking ffmpeg jobs in the 50 percent range (of a single cpu) down to 12-15.

**Reply by bobyelbob** [reply]
Yeah I gave up on this as well. Currently running on unRAID and it didn't throw any errors. Are you using ffmpeg to change from h265 to h264? When I try this it seems even with quicksync the CPU has a really hard time. 70-90% usage

**Reply by haggercody** [reply]
my cams are all h264.  You can run intel_gpu_top to confirm quicksync is running. I had been using the wrong settings in my config at first and didn't realize it till i checked here to confirm.

**Reply by bobyelbob** [reply]
Ok I will look into that. Thank you. If you get a chance could you share the config settings that are working for you? I have an i7-9700k

**Comment by haggercody** [comment]
yea sure here is my config

```
mqtt:
  host: 192.168.10.207
  user: mqtt
  password: "1234"

cameras:

  side:
    ffmpeg:

      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
  
      inputs:
        - path: rtsp://xxxxx:xxxxx@192.168.10.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect #blah
            - rtmp          
        - path: rtsp://xxxxx:xxxx@192.168.10.12:554/cam/realmonitor?channel=1&subtype=0
          roles:      
            - record    

    detect:
      width: 2304
      height: 1296
      fps: 6
      enabled: True

    motion:
      mask:
        - 2304,0,2304,720,0,560,0,0
      delta_alpha: 0.4

    objects:

      track:
        - person
        - dog


      filters:
        person:
          min_score: 0.6
          threshold: 0.7


    record: 
    # Optional: Enable recording (default: shown below)
      retain_days: 0
      enabled: True   
      events:
        objects:
          - person
          - dog
          
        pre_capture: 5
        # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 5

  front:
    ffmpeg:

      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
    
      #input_args: -tag:v hvc1
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.10.203:554/Streaming/Channels/101
          roles:
            - detect #blah               
            - record
            - rtmp
    zones:
      front_door:
        coordinates: 132,1386,379,1520,788,1491,367,1205,160,1266

        #input_args: -tag:v hvc1
    detect:
      width: 2688
      height: 1520
      fps: 5
      enabled: True
      max_disappeared: 70

    motion:    
     mask:
        - 2688,0,2688,942,822,778,0,679,0,0

    objects:

      track:
        - person
        - dog

      filters:
        person:
          min_score: 0.5
          threshold: 0.7

    record: 
    # Optional: Enable recording (default: shown below)
      retain_days: 0
      enabled: True   
      events:
        objects:
          - person
          - dog
          
        pre_capture: 5
        # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 5


  garage:
    ffmpeg:

      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128

      #input_args: -tag:v hvc1
      inputs:
        - path: rtsp://192.168.10.95/ch1.h264
          roles:
            - detect #blah
            - rtmp             
        - path: rtsp://192.168.10.95/ch0.h264
          roles:           
            - record

      #input_args: -tag:v hvc1
    detect:
      width: 640 
      height: 386
      fps: 6
      enabled: True
    
    motion:
     mask:
        - 640,0,640,103,0,122,0,0  
    objects:
      track:
        - person

        - dog

      filters:
        person:
          min_score: 0.6
          threshold: 0.7

    record: 
    # Optional: Enable recording (default: shown below)
      retain_days: 0
      enabled: True   
      events:
        objects:
          - person
          - dog
          
        pre_capture: 5
        # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 5

detectors:
  coral:
    type: edgetpu
    device: usb

```
