### DISCUSSION TITLE
Playback randomly skips time

### DISCUSSION THREAD

**Discussion by jrmymllr** [blakeblackshear/frigate#17232] [General Support]
### Describe the problem you are having

Playback will frequently skip frames at random times. It's usually 1 - 3 seconds at a time. It looks like the frame freezes, but once it starts playing again the camera time watermark will have jumped ahead the amount of time it froze. An export of the video plays smoothly. The same video segment will exhibit the same issue each time it's played back. Same issue on multiple computers, but Firefox plays it ok. What can be done so it plays correctly on all browsers?

### Version

0.15 released

### Frigate config file

```yaml
mqtt:
  enabled: false

logger:
  default: error

go2rtc:
  streams:
    SouthFront:
      - rtsp://192.168.0.8/streaming/channels/101
    NorthFront:
      - rtsp://192.168.0.7/streaming/channels/101
    Door:
      - rtsp://192.168.0.6/streaming/channels/101
    Back:
      - rtsp://192.168.0.9/streaming/channels/101
    Deck:
      - rtsp://192.168.0.10/streaming/channels/101
    Garage:
      - rtsp://192.168.0.5/streaming/channels/101

cameras:
  SouthFront:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.0.8/streaming/channels/101
          roles:
            - detect
    motion:
      mask: 0.378,0.066,0.407,0.067,0.407,0.089,0.379,0.087
    objects:
      track:
        - amazon
        - bear
        - bicycle
        - bird
        - boat
        - car
        - cat
        - deer
        - dhl
        - dog
        - fedex
        - fox
        - horse
        - motorcycle
        - person
        - rabbit
        - raccoon
        - squirrel
        - ups
        - usps
    review:
      alerts:
        labels:
          - amazon
          - bear
          - bird
          - cat
          - deer
          - dhl
          - dog
          - fedex
          - fox
          - horse
          - rabbit
          - raccoon
          - squirrel
          - ups
          - usps
      detections:
        labels:
          - bear
          - bicycle
          - bird
          - boat
          - car
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
    ui:
      order: 2
    birdseye:
      order: 2
  NorthFront:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.0.7/streaming/channels/101
          roles:
            - detect
    motion:
      mask: 0.374,0.064,0.406,0.063,0.405,0.089,0.375,0.089
    objects:
      track:
        - amazon
        - bear
        - bicycle
        - bird
        - boat
        - car
        - cat
        - deer
        - dhl
        - dog
        - fedex
        - fox
        - horse
        - motorcycle
        - person
        - rabbit
        - raccoon
        - squirrel
        - ups
        - usps
    review:
      alerts:
        labels:
          - amazon
          - bear
          - bird
          - cat
          - deer
          - dhl
          - dog
          - fedex
          - fox
          - horse
          - rabbit
          - raccoon
          - squirrel
          - ups
          - usps
      detections:
        labels:
          - bear
          - bicycle
          - bird
          - boat
          - car
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
    ui:
      order: 1
    birdseye:
      order: 1
  Door:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.0.6/streaming/channels/101
          roles:
            - detect
    objects:
      track:
        - bear
        - bicycle
        - bird
        - cat
        - deer
        - dog
        - fox
        - horse
        - motorcycle
        - person
        - rabbit
        - raccoon
        - squirrel
    motion:
      mask:
        - 0.371,0.066,0.406,0.065,0.406,0.086,0.371,0.084
        - 0,0,0,0.121,0.238,0.08,0.232,0
    review:
      alerts:
        labels:
          - bear
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcyle
          - person
          - rabbit
          - raccoon
          - squirrel
      detections:
        labels:
          - bear
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
    ui:
      order: 0
    birdseye:
      order: 0
  Back:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.0.9/streaming/channels/101
          roles:
            - detect
    objects:
      track:
        - bear
        - bicycle
        - bird
        - cat
        - deer
        - dog
        - fox
        - horse
        - motorcycle
        - person
        - rabbit
        - raccoon
        - squirrel
    review:
      alerts:
        labels:
          - bear
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
      detections:
        labels:
          - bear
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
    ui:
      order: 4
    birdseye:
      order: 4
    motion:
      mask: 0.143,0.047,0.145,0.073,0.166,0.071,0.163,0.046
  Deck:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.0.10/streaming/channels/101
          roles:
            - detect
    objects:
      track:
        - bear
        - bicycle
        - bird
        - cat
        - deer
        - dog
        - fox
        - horse
        - motorcycle
        - person
        - rabbit
        - raccoon
        - squirrel
    review:
      alerts:
        labels:
          - bear
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
      detections:
        labels:
          - bear
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - horse
          - motorcycle
          - person
          - rabbit
          - raccoon
          - squirrel
    ui:
      order: 3
    birdseye:
      order: 3
    motion:
      mask: 0.374,0.061,0.403,0.061,0.404,0.083,0.375,0.083
  Garage:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.0.5/streaming/channels/101
          roles:
            - detect
    detect:
      enabled: false

    motion:
      mask:
        - 0.016,0.047,0.015,0.069,0.164,0.072,0.164,0.05
        - 0.439,0.096,0.456,0.096,0.458,0.121,0.438,0.122
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
    ui:
      order: 5
    birdseye:
      order: 5
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  contour_area: 15
  lightning_threshold: 0.5
  improve_contrast: 'true'

objects:
  filters:
    amazon:
      min_score: .50
      threshold: .70
    bear:
      min_score: .50
      threshold: .80
    bicycle:
      min_score: .50
      threshold: .70
    bird:
      min_score: .50
      threshold: .80
    boat:
      min_score: .50
      threshold: .70
    car:
      min_score: .70
      threshold: .80
      min_area: 15000
    cat:
      min_score: .50
      threshold: .80
    deer:
      min_score: .50
      threshold: .80
    dhl:
      min_score: .50
      threshold: .70
    dog:
      min_score: .50
      threshold: .80
    fedex:
      min_score: .50
      threshold: .70
    fox:
      min_score: .50
      threshold: .80
    horse:
      min_score: .50
      threshold: .80
    motorcycle:
      min_score: .50
      threshold: .70
    person:
      min_score: .50
      threshold: .70
    rabbit:
      min_score: .50
      threshold: .80
    raccoon:
      min_score: .50
      threshold: .80
    squirrel:
      min_score: .50
      threshold: .80
    ups:
      min_score: .50
      threshold: .70
    usps:
      min_score: .50
      threshold: .60
detect:
  width: 2048
  height: 1536
  fps: 4
  stationary:
    interval: 40
    threshold: 40
  annotation_offset: -2500
record:
  enabled: true
  retain:
    days: 4
    mode: all
  alerts:
    retain:
      days: 30
    pre_capture: 40
    post_capture: 40
  detections:
    retain:
      days: 30
    pre_capture: 40
    post_capture: 40
birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  layout:
    scaling_factor: 1.5

snapshots:
  enabled: true
  retain:
    default: 4

live:
  height: 720
  quality: 1

database:
  path: /db/frigate.db

detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU

model:
  path: plus://------------

version: 0.15-1
camera_groups:
  All:
    order: 2
    icon: LuActivity
    cameras:
      - Back
      - Deck
      - Door
      - Garage
      - NorthFront
      - SouthFront
  Birdseye:
    order: 2
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
No errors associated with this.
```

### Relevant go2rtc log output

```shell
No errors.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":2048,"height":1536,"avg_frame_rate":"15/1"}]}}]
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: frigate:latest
    logging:
      driver: none
    healthcheck:
      disable: true
    shm_size: "400mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config:/config/:rw
      - /CCTV/storage:/media/frigate/:rw
      - /root/frigate/db-ramdisk:/db/:rw
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Port used by the Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"
    environment:
      FRIGATE_RTSP_PASSWORD: "useyourownpassword!"
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2332 and 2335

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/be38414b-e969-4074-bc30-a2589384329c)

### Any other information that may be helpful

I understand this is likely a browser issue, but is there a way to root-cause this further? It seems to occur on the border between 10 second recording segments.
