### DISCUSSION TITLE
[Support]: Detection for non-specified object prevented detection of other objects

### DISCUSSION THREAD

**Discussion by jonofmac** [blakeblackshear/frigate#17234] [General Support]
### Describe the problem you are having

Weird one I haven't encountered before. It's a weird one to try to reproduce. Basically, I got a delivery of car tires today. On my front porch camera, it detected the tires as "car" according to the event list when i look at the history view. If I go to detections/alerts view, it does NOT show these tires as a car in the list at all, but this is expected because I do not detect car objects on the front door camera at all. It's not part of the config.

The issue is that I received other packages afterwards and had people on the porch but NONE of those events were captured/tagged in alerts, detections, or history. Once I moved the tires out of view of the camera, it began tagging objects it's supposed to correctly again. I can't see the incorrect tag anywhere to be able to see/verify the bounding box.

Posting the configuration so you can see that the front door cam has no objection detection for "car" so I don't know why my event log in the history view only is filled with "car", and it did not tag any other (valid) objects until the tires were moved out of view.

In this example photo, you can see how it did not tag the UPS man, or the package at all because it was tagging "car" on the tires non stop.
<img width="1113" alt="Screenshot 2025-03-18 at 17 33 23" src="https://github.com/user-attachments/assets/22a70b29-8cf9-4012-898f-ad0b8ab3fc67" />

Below you can see the review alert page. The tires on the front porch aren't even shown as an event, but you see the guy with the tires get tagged. Notice it also missed the UPS guy after the tires were delivered. And it doesn't tag me on the front porch until the tires were moved from the camera's view. Notice it successfully tagged the amazon delivery too.
<img width="1487" alt="image" src="https://github.com/user-attachments/assets/fb4e2630-44c0-442b-8ce0-ef555e974e63" />

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox

### Frigate config file

```yaml
database:
  path: /db/frigate.db

model:
  path: plus://<redacted>

mqtt:
  host: <redacted>
  port: 1883
  user: <redacted>
  password: <redacted>


logger:
  default: info

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  stationary:
    interval: 5
    threshold: 50

objects:
  track:
    - person
    - face
    - car
    - amazon
    - ups
    - fedex
    - package
    - cat
    - dog
  filters:
    person:
      min_score: 0.85
    cat:
      min_score: 0.90
    dog:
      min_score: 0.90
    car:
      min_score: 0.8
    package:
      min_score: 0.84

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_height: 50
  improve_contrast: true

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: true
  retain:
    default: 20

record:
  enabled: true
  expire_interval: 1
  retain:
    days: 20
    mode: all
  alerts:
    retain: {}
    pre_capture: 5
    post_capture: 2
  detections:
    retain: {}
    pre_capture: 5
    post_capture: 2
live:
  height: 1080
  quality: 8


# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
   # Optional: Mode of the view. Available options are: objects, motion, and continuous
   #   objects - cameras are included if they have had a tracked object within the last 30 seconds
   #   motion - cameras are included if motion was detected in the last 30 seconds
   #   continuous - all cameras are included always
  mode: continuous

go2rtc:
  webrtc:
    candidates:
      - 10.1.1.10:8555
  streams:
    rtsp_back_porch:
      - rtsp://<redacted>:<redacted>@hikvision3:554/Streaming/Channels/101/

    rtsp_front_yard:
      - rtsp://<redacted>:<redacted>@hikvision6:554/Streaming/Channels/101/

    rtsp_front_yard_sub:
      - rtsp://<redacted>:<redacted>@hikvision6:554/Streaming/Channels/103/

    rtsp_driveway_side:
      - rtsp://<redacted>:<redacted>@hikvision5:554/Streaming/Channels/101/

    rtsp_front_door:
      - rtsp://<redacted>:<redacted>@hikvision1:554/Streaming/Channels/101/

    rtsp_garage:
      - rtsp://<redacted>:<redacted>@hikvision2:554/Streaming/Channels/101/


cameras:
####### Back Porch Camera ######
  back_porch:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: rtsp_back_porch
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      patio:
        coordinates: 0.957,0.608,0.333,0.083,0.234,0,0.115,0,0,0.102,0,1,0.982,1
        objects:
          - person
          - cat
          - dog
        inertia: 3
      parking_zone:
        coordinates: 0.281,0,0.969,0,0.899,0.582,0.374,0.212,0.258,0.149
        objects:
          - person
          - car
          - cat
          - dog
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - patio
        - parking_zone
    objects:
      track:
        - person
        - face
        - car
        - cat
        - dog
      filters:
        cat:
          min_area: 200
        dog:
          min_area: 200
    review:
      alerts:
        required_zones:
          - patio
          - parking_zone
        labels:
          - person
          - cat
          - dog
      detections:
        required_zones: patio
        labels:
          - person
          - cat
          - dog
    motion:
      mask: 0.063,0.932,0.34,0.924,0.342,0.968,0.06,0.97
  front_yard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/rtsp_front_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: rtsp_front_yard
    detect:
      #width: 1920
      #height: 1080
      fps: 4
    motion:
      mask:
        - 0.415,0.061,0.345,0.09,0.335,0,1,0,1,0.162,0.896,0.104,0.699,0.054
        - 0,0,0.273,0,0.28,0.058,0.23,0.1,0.151,0.147,0,0.243
        - 0.018,0.913,0.311,0.916,0.313,0.947,0.016,0.948
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      yard:
        coordinates: 
          0.064,0.306,0,0.383,0,1,1,1,1,0.422,0.887,0.233,0.65,0.191,0.374,0.203,0.263,0.224,0.119,0.268
        objects:
          - person
          - face
          - amazon
          - ups
          - fedex
          - cat
          - dog
        min_area: 3000
        inertia: 3
      driveway:
        coordinates: 1,0.425,1,0.284,0.893,0.246
        objects:
          - person
          - fedex
          - amazon
          - ups
          - car
          - cat
          - dog
        inertia: 3
      street:
        coordinates: 
          0,0.26,0.165,0.162,0.229,0.113,0.308,0.066,0.344,0.065,0.292,0.113,0.457,0.076,0.613,0.064,0.824,0.091,1,0.152,1,0.251,0.649,0.182,0.323,0.201,0.124,0.265,0,0.333
        objects:
          - car
          - person
          - face
          - amazon
          - ups
          - fedex
          - cat
          - dog
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        car:
          min_area: 3000
        person:
          min_area: 3000
    snapshots:
      required_zones:
        - street
        - driveway
        - yard
    review:
      alerts:
        required_zones:
          - driveway
          - yard
      detections:
        required_zones:
          - yard
          - driveway
          - street

# Driveway camera
  driveway_side:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        #- path: /media/frigate/test/driveway-test-cat-night.mp4 
        #  input_args: -re -stream_loop -1 -fflags +genpts
        - path: rtsp://127.0.0.1:8554/rtsp_driveway_side
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      #- path: rtsp://127.0.0.1:8554/rtsp_driveway_side_sub
      #  input_args: preset-rtsp-restream
      #  roles:
      #  - detect
    live:
      stream_name: rtsp_driveway_side
    detect:
      width: 1920
      height: 1080
      fps: 4
    motion:
      mask:
        - 0.585,0.078,0.405,0.122,0.545,0.162,0.76,0.263,0.772,0.002
        - 0.336,0,0.035,0,0.044,0.188,0.193,0.131,0.347,0.064
        - 0.018,0.913,0.26,0.908,0.261,0.948,0.016,0.949
    objects:
      filters:
        car:
          min_area: 15000
        person:
          min_area: 70000
        cat:
          min_score: 0.5
          min_area: 10000
        dog:
          min_score: 0.5
          min_area: 10000
    zones:
      driveway_entrance:
        coordinates: 0.393,0.148,0.51,0.255,0,0.5,0,0.323
        objects:
          - person
          - face
          - car
          - cat
          - dog
        inertia: 3
      driveway:
        coordinates: 
          0.536,0.253,0.761,0.348,0.775,0.035,0.935,0.078,1,0.092,1,1,0,1,0,0.518,0.205,0.48,0.447,0.353
        objects:
          - person
          - car
          - cat
          - dog
        inertia: 3
      street:
        coordinates: 0.234,0.184,0.039,0.249,0.035,0.09,0.21,0.029,0.427,0.019,0.435,0.114
        objects:
          - car
          - person
          - cat
          - dog
        inertia: 3
    snapshots:
      required_zones:
        - driveway_entrance
        - driveway
        - street
    review:
      alerts:
        required_zones:
          - driveway_entrance
          - driveway
      detections:
        required_zones:
          - driveway
          - driveway_entrance

# Front Door
  front_door:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: rtsp_front_door
    detect:
      height: 1920
      width: 1080
      fps: 5
    motion:
      mask: 1,0,0,0,0,0.388,1,0.432
    zones:
      front_porch:
        coordinates: 884,824,1086,939,1086,1920,0,1920,0,767,86,806,348,841
        objects:
          - person
          - face
          - cat
          - dog
          - amazon
          - ups
          - fedex
          - package
    objects:
      filters:
        dog:
          mask:
            - 644,1628,839,1920,1080,1920,1080,1369,999,1353,728,1441
        cat:
          mask:
            - 644,1628,839,1920,1080,1920,1080,1369,999,1353,728,1441
        package:
          mask:
            - 0,1920,222,1920,97,1498,0,1463
            - 1080,1920,1080,1403,528,1424,442,1809,156,1841,116,1920
    snapshots:
      required_zones:
        - front_porch

    review:
      alerts:
        required_zones:
          - front_porch

###### Garage Camera ######
  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: rtsp_garage
    detect:
      width: 1920
      height: 1080
      fps: 5
      annotation_offset: -1000
    zones:
      garage_inside:
        coordinates: 0.003,0.125,0.539,0.003,0.999,0.18,0.995,0.994,0.003,0.997
        objects:
          - person
          - cat
          - dog
        inertia: 3
      garage_bay_1:
        coordinates: 0,1,0,0.505,0.518,0.236,0.745,0.389,0.481,1
        loitering_time: 0
        objects: car
        inertia: 3
      garage_bay_2:
        coordinates: 0.485,1,0.753,0.395,1,0.526,1,1
        loitering_time: 0
        objects: car
        inertia: 3
    objects:
      filters:
        car:
          min_area: 25000
    snapshots:
      required_zones:
        - garage_inside

    review:
      detections:
        required_zones: garage_inside
        labels:
          - person
          - cat
          - dog
      alerts:
        required_zones: garage_inside
        labels:
          - cat
          - dog
    motion:
      mask: 0.351,0.968,0.349,0.924,0.067,0.928,0.068,0.973
version: 0.15-1
camera_groups:
  Perimeter:
    order: 1
    icon: LuHome
    cameras:
      - back_porch
      - driveway_side
      - front_door
      - front_yard
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### FFprobe output from your camera

```shell
Was ffprobe removed from the frigate container? lol

user@server:~$ sudo docker exec -it frigate bash
root@51af15b16008:/opt/frigate# ffprobe rtsp://<redacted>:<redacted>@hikvision3:554/Streaming/Channels/101/
bash: ffprobe: command not found



Anyway, below is output from outside the container:
 ffprobe rtsp://hass:<redacted>@<redacted>:554/Streaming/Channels/101/
ffprobe version N-107435-g61c151a098 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --pkg-config-flags=--static --enable-nonfree --enable-gpl --enable-version3 --enable-libmp3lame --enable-libvpx --enable-libopus --enable-opencl --enable-libxcb --enable-opengl --enable-nvenc --enable-vaapi --enable-vdpau --enable-ffplay --enable-ffprobe --enable-libx264 --enable-libx265 --enable-openssl --enable-cuda-nvcc --enable-cuvid --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
  libavutil      57. 29.100 / 57. 29.100
  libavcodec     59. 39.100 / 59. 39.100
  libavformat    59. 29.100 / 59. 29.100
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 46.100 /  8. 46.100
  libswscale      6.  8.100 /  6.  8.100
  libswresample   4.  8.100 /  4.  8.100
  libpostproc    56.  7.100 / 56.  7.100
[rtsp @ 0x5596f308fe40] max delay reached. need to consume packet
[rtsp @ 0x5596f308fe40] RTP: missed 229 packets
[h264 @ 0x5596f3096940] left block unavailable for requested intra mode
[h264 @ 0x5596f3096940] error while decoding MB 0 34, bytestream 39146
[h264 @ 0x5596f3096940] concealing 10297 DC, 10297 AC, 10297 MV errors in I frame
Input #0, rtsp, from 'rtsp://<redacted>:<redacted>@hikvision3:554/Streaming/Channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.100000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 1:1 DAR 168:95], 10 fps, 10 tbr, 90k tbn
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: '3.3'
services:
    blakeblackshear:
        container_name: frigate
        restart: unless-stopped
        devices:
            - '/dev/bus/usb:/dev/bus/usb'
            - '/dev/dri/renderD128:/dev/dri/renderD128'
            - '/dev/apex_0:/dev/apex_0'
        volumes:
            - '/shares/nvr/frigate:/media/frigate'
            - '/shares/server/frigate/config/:/config/'
            - '/shares/server/frigate/db:/db'
            - '/etc/localtime:/etc/localtime:ro'
            - type: tmpfs
              target: /tmp/cache/
              tmpfs:
                size: 1000000000
        environment:
            - FRIGATE_RTSP_PASSWORD=<redacted>
            - PLUS_API_KEY=<redacted>
        ports:
            - '5000:5000'
            - '8554:8554'
            - '8555:8555'
        shm_size: '3gb'
        build:
          context: .
          shm_size: '3gb'
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        image: 'ghcr.io/blakeblackshear/frigate:0.15.0'
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision Cameras
