### DISCUSSION TITLE
[Camera Support]: Change resolution for YT stream.

### DISCUSSION THREAD

**Discussion by frehall** [blakeblackshear/frigate#17254] [Camera Support]
### Describe the problem you are having

There are no option to change resolution on my china-cam im using for streaming a bird-nest. Youtube wants 1920x1080 but my only options are 640x360 or 2288x1288. Is there a way to change res before sending steam to YT? 
I guess its heavy on resources?

### Version

0.15.0-cea210d

### What browser(s) are you using?

Mozilla Firefox 135.0.1

### Frigate config file

```yaml
go2rtc:
  streams:
holken:
      - rtsp://192.168.107.33:554/user=XXX&password=XXX&channel=2&stream=0.sdp?real_stream
      - ffmpeg:holken#audio=aac
    holken_sub:
      - rtsp://192.168.107.33:554/user=XXX&password=XXX&channel=0&stream=1 
      - ffmpeg:holken_sub#audio=aac
    video_audio_transcode:
      - ffmpeg:rtsp://127.0.0.1:8554/holken_sub#video=h264#hardware#audio=aac
    audio_transcode:
      - ffmpeg:rtsp://127.0.0.1:8554/holken_sub#video=copy#audio=aac
  publish:
    audio_transcode:
      - rtmp://x.rtmp.youtube.com/live2/xxxxx
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Object Detector

Coral

### Network connection

Wireless

### Camera make and model

China

### Screenshots of the Frigate UI's System metrics pages

-

**Comment by NickM-27** [comment]
this can be done using go2rtc

**Reply by frehall** [reply]
Yes, thats what i think too but i have tried several ways of using width and height parameters with no effect. I am not sure where to put them.

**Reply by NickM-27** [reply]
would be like this:

```yaml
go2rtc:
  streams:
    holken:
      - rtsp://192.168.107.33:554/user=XXX&password=XXX&channel=2&stream=0.sdp?real_stream#video=h264#width=1920#height=1080#audio=copy
```
