### DISCUSSION TITLE
Opening Chrome Dev Tools Breaking Live Stream

### DISCUSSION THREAD

**Discussion by piyushpranjal03** [blakeblackshear/frigate#17253] [Ask A Question] [answered]
Whenever I am opening chrome dev tools it is pausing the stream. When I am closing this sometimes all live streams working normally sometimes one of them are completely frozen and one is working.

Switching chrome tabs are completely freezing both streams.

Not even a single error in `gortc` or `frigate` tab. `nginx` tab has all 200 responses

I am using `ghcr.io/blakeblackshear/frigate   stable    dc77295ccc5a` pulled yesterday.
Chrome version: Version 134.0.6998.89 (Official Build) (arm64)
Running on MacOS

```
mqtt:
  enabled: false

#audio:
#  enabled: true

logger:
  default: error

detect:
  enabled: false

auth:
  enabled: false

# Camera stream definitions
go2rtc:
  streams:
    roadside:
      - rtsp://user:pass@192.168.18.102:554/stream1

    stairs:
      - rtsp://user:pass@192.168.18.101:554/stream1

  webrtc:
    candidates:
      - localhost:8555
      - stun:8555

## Camera entity definitions and settings
cameras:
  roadside:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/roadside
          input_args: preset-rtsp-restream
          roles:
            - record

  stairs:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/stairs
          input_args: preset-rtsp-restream
          roles:
            - record

record:
  enabled: true
  retain:
    days: 1
    mode: all

camera_groups:
  Home:
    order: 1
    icon: LuBuilding
    cameras:
      - roadside
      - stairs

version: 0.15-1
```
