### DISCUSSION TITLE
[Support]: Installation Help please with my Portainer docker compose file

### DISCUSSION THREAD

**Discussion by sqlegan** [blakeblackshear/frigate#17270] [General Support] [answered]
### Describe the problem you are having

I'm quite new to docker and compose files but have followed the example in a document'Installing Frigate from scratch'. I've built a new PC, added coral cards and re-used some storage I had.
The storage is a 250gb ssd and 2 Western Digital 2TB spinning drives.
I've installed Ubunutu server on the new pc(to the 250GB ssd), mounted the other 2 drives, installed docker (during server install), installed portainer.
My plan was to use the two spinning 2TB drives for recordings so I have attempted to map them in my docker compose file. I have created frigate.yml file in /frigate01/config on the ubutunu server and was expecting this to map into docker in /config as I have specified this in my docker compose file, but this is clearly not working as frigate is trying to connect to a camera with the wrong IP Address.
I'm not sure if I misunderstand how mapping drives works or if I have done something wrong in my compose file and would appreciate suggestions as to how to correct it.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox 136.02

### Frigate config file

```yaml
mqtt:
#point to your host
  host: 192.168.31.104
  user: 
  password: 

database:
  path: /db/frigate.db
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
rtmp:
  enabled: false

birdseye:
  width: 1920
  height: 1080
  mode: continuous

record:
  enabled: True
  retain:
    days: 14
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: True
  retain:
    default: 30
    # Optional: Per object retention days
    objects:
      person: 15
```

### Relevant Frigate log output

```shell
2025-03-20 11:04:39.922538901  [2025-03-20 11:04:39] frigate.video                  ERROR   : name_of_your_camera: Unable to read frames from ffmpeg process.
2025-03-20 11:04:39.922579461  [2025-03-20 11:04:39] frigate.video                  ERROR   : name_of_your_camera: ffmpeg process is not running. exiting capture thread...
2025-03-20 11:04:44.906747609  [2025-03-20 11:04:44] watchdog.name_of_your_camera   ERROR   : Ffmpeg process crashed unexpectedly for name_of_your_camera.
2025-03-20 11:04:44.906848841  [2025-03-20 11:04:44] watchdog.name_of_your_camera   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-03-20 11:04:44.907022874  [2025-03-20 11:04:44] ffmpeg.name_of_your_camera.detect ERROR   : [tcp @ 0x61e462261280] Connection to tcp://10.0.10.10:554?timeout=5000000 failed: Connection timed out
2025-03-20 11:04:44.907031690  [2025-03-20 11:04:44] ffmpeg.name_of_your_camera.detect ERROR   : [in#0 @ 0x61e46225fd80] Error opening input: Connection timed out
```

### Relevant go2rtc log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Frigate stats

```json
N/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation
    devices: 
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1      
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /frigate01/config
        target: /config
        read_only: false
      - type: bind
        source: /frigate01/exports
        target: /media/frigate/exports
        read_only: false
      - type: bind
        source: /frigate02/recordings
        target: /media/frigate/recordings
        read_only: false
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000    
    ports:
      - "5000:5000" # web interface
      #- "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"  #modify to whatever if using rtsp
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Annke
