### DISCUSSION TITLE
[Support]: Camera/Process FPS drops and FFMPEG crashes

### DISCUSSION THREAD

**Discussion by github-tijlxyz** [blakeblackshear/frigate#17284] [General Support] [answered]
### Describe the problem you are having

On very random moments the camera fps drops because the ffmpeg crashes.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: <redacted> # <---- same mqtt broker that home assistant uses
  user: <redacted>
  password: <redacted>
  enabled: true
  topic_prefix: frigate

auth:
  trusted_proxies:
    - 127.0.0.0/8

ffmpeg:
  hwaccel_args: preset-vaapi # <- hardware accelerated encoding
  output_args:
    record: preset-record-generic-audio-aac # <- add audio to recording

audio:
  enabled: true
  listen:
    - fire_alarm
    - scream
#    - speech
#    - yell

detectors:
  coral:
    type: edgetpu
    device: usb
    model_path: /edgetpu_model.tflite
    #width: 640
    #height: 640

birdseye:
  enabled: true
  mode: motion
  inactivity_threshold: 60

record:
  enabled: true
  retain:
    days: 30
    mode: all

#  events:
#    pre_capture: 30
#    post_capture: 30
#    retain:
#      default: 30
#      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 90
  bounding_box: true

detect:
  fps: 5
  enabled: true

ui:
  timezone: Europe/Berlin

objects:
  track:
    - person
    - cat
#    - car
    - bicycle
    - dog
  filters:
    cat:
      threshold: 0.50

go2rtc:
  streams:
    cam1:
      #- rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0#video=h264#video=copy#audio=copy#audio=aac#hardware
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:#video=h264#audio=aac#hardware"
    cam1_sub:
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:#video=h264#audio=aac#hardware"

# ...

cameras:
  cam1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - detect
    objects:
      filters:
        person:
          mask: 0.283,0.445,0.297,0.531,0.351,0.525,0.336,0.422
    review:
      alerts:
        required_zones: myzone
    motion:
      threshold: 28
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.297,0.442,0.343,0.458,0.345,0.328,0.335,0.216,0.292,0.055,0.23,0.014,0.215,0.038,0.233,0.113,0.26,0.278,0.23,0.293,0.207,0.296,0.183,0.325,0.186,0.241,0.163,0.176,0.146,0.122,0.174,0.067,0.186,0,0,0,0,1,0.234,1,0.333,0.984,0.384,0.946,0.404,0.863,0.411,0.789,0.407,0.706,0.399,0.621,0.364,0.566
        - 0.517,0.88,0.478,0.773,0.473,0.712,0.463,0.643,0.475,0.599,0.462,0.6,0.443,0.573,0.435,0.531,0.42,0.501,0.429,0.408,0.456,0.373,0.419,0.373,0.404,0.303,0.479,0.268,0.435,0.202,0.421,0.109,0.399,0.054,0.412,0,0.458,0,0.48,0.087,0.524,0.082,0.549,0,0.889,0,0.888,0.03,0.856,0.039,0.868,0.065,0.865,0.109,0.825,0.14,0.844,0.178,0.883,0.284,0.906,0.405,0.879,0.459,0.845,0.464,0.849,0.51,0.897,0.56,0.92,0.669,0.912,0.771,0.887,0.816,0.84,0.856,0.806,0.812,0.775,0.776,0.766,0.71,0.738,0.722,0.702,0.672,0.704,0.759,0.693,0.825,0.644,0.892,0.607,0.896
        - 0,0.044,0.215,0.057,0.216,0,0,0
        - 0.893,0.251,0.915,0.3,0.937,0.332,0.971,0.395,0.983,0.5,0.991,0.545,0.999,0.561,1,0.297,1,0.219,0.988,0.204,0.965,0.14,0.946,0.124,0.921,0.136,0.902,0.184
        - 0.936,0,1,0,1,0.131,0.964,0.061
    zones:
      myzone:
        coordinates: 0.273,0.36,0.205,1,0.79,1,0.954,0.899,0.651,0.248
        inertia: 3
        loitering_time: 1
version: 0.15-1
```

### Relevant Frigate log output

```shell
frigate  | 2025-03-21 03:05:51.022291102  [2025-03-21 03:05:51] frigate.video                  ERROR   : cam1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-21 03:05:51.022303452  [2025-03-21 03:05:51] frigate.video                  ERROR   : cam1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-21 03:05:58.805749376  [2025-03-21 03:05:58] watchdog.cam1                  ERROR   : Ffmpeg process crashed unexpectedly for cam1.
frigate  | 2025-03-21 03:05:58.805751949  [2025-03-21 03:05:58] watchdog.cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-03-21 03:05:58.805774544  [2025-03-21 03:05:58] ffmpeg.cam1.detect             ERROR   : [AVHWFramesContext @ 0x703f3004bf40] Failed to sync surface 0x13: 1 (operation failed).
frigate  | 2025-03-21 03:05:58.805794009  [2025-03-21 03:05:58] ffmpeg.cam1.detect             ERROR   : [hwdownload @ 0x703f40003980] Failed to download frame: -5.
frigate  | 2025-03-21 03:05:58.805836635  [2025-03-21 03:05:58] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x59295b6ebd40] Error while filtering: Input/output error
frigate  | 2025-03-21 03:05:58.805855546  [2025-03-21 03:05:58] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x59295b6ebd40] Task finished with error code: -5 (Input/output error)
frigate  | 2025-03-21 03:05:58.805874334  [2025-03-21 03:05:58] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x59295b6ebd40] Terminating thread with return code -5 (Input/output error)
frigate  | 2025-03-21 03:06:29.746236422  [2025-03-21 03:06:29] frigate.video                  ERROR   : cam1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-21 03:06:29.746239050  [2025-03-21 03:06:29] frigate.video                  ERROR   : cam1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-21 03:06:38.815040944  [2025-03-21 03:06:38] watchdog.cam1                  ERROR   : Ffmpeg process crashed unexpectedly for cam1.
frigate  | 2025-03-21 03:06:38.815085264  [2025-03-21 03:06:38] watchdog.cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-03-21 03:06:38.815124529  [2025-03-21 03:06:38] ffmpeg.cam1.detect             ERROR   : [AVHWFramesContext @ 0x7d734c04ec80] Failed to sync surface 0x13: 1 (operation failed).
frigate  | 2025-03-21 03:06:38.815149515  [2025-03-21 03:06:38] ffmpeg.cam1.detect             ERROR   : [hwdownload @ 0x7d735c003980] Failed to download frame: -5.
frigate  | 2025-03-21 03:06:38.815176830  [2025-03-21 03:06:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x5589d03dd0c0] Error while filtering: Input/output error
frigate  | 2025-03-21 03:06:38.815211487  [2025-03-21 03:06:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x5589d03dd0c0] Task finished with error code: -5 (Input/output error)
frigate  | 2025-03-21 03:06:38.815213118  [2025-03-21 03:06:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x5589d03dd0c0] Terminating thread with return code -5 (Input/output error)
frigate  | 2025-03-21 03:06:44.547899473  127.0.0.1 - - [21/Mar/2025:03:06:44 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-03-21 03:07:13.905697274  [2025-03-21 03:07:13] frigate.video                  ERROR   : cam1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-21 03:07:13.905760513  [2025-03-21 03:07:13] frigate.video                  ERROR   : cam1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-21 03:07:18.824262667  [2025-03-21 03:07:18] watchdog.cam1                  ERROR   : Ffmpeg process crashed unexpectedly for cam1.
frigate  | 2025-03-21 03:07:18.824265276  [2025-03-21 03:07:18] watchdog.cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-03-21 03:07:18.824286583  [2025-03-21 03:07:18] ffmpeg.cam1.detect             ERROR   : [AVHWFramesContext @ 0x7cd14404c900] Failed to sync surface 0x12: 1 (operation failed).
frigate  | 2025-03-21 03:07:18.824361225  [2025-03-21 03:07:18] ffmpeg.cam1.detect             ERROR   : [hwdownload @ 0x7cd158003980] Failed to download frame: -5.
frigate  | 2025-03-21 03:07:18.824363101  [2025-03-21 03:07:18] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x5ecc03a4eac0] Error while filtering: Input/output error
frigate  | 2025-03-21 03:07:18.824383480  [2025-03-21 03:07:18] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x5ecc03a4eac0] Task finished with error code: -5 (Input/output error)
frigate  | 2025-03-21 03:07:18.824417617  [2025-03-21 03:07:18] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x5ecc03a4eac0] Terminating thread with return code -5 (Input/output error)
frigate  | 2025-03-21 03:07:44.559213644  127.0.0.1 - - [21/Mar/2025:03:07:44 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-03-21 03:07:50.150131281  [2025-03-21 03:07:50] frigate.video                  ERROR   : cam1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-21 03:07:50.150272890  [2025-03-21 03:07:50] frigate.video                  ERROR   : cam1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-21 03:07:58.829989573  [2025-03-21 03:07:58] watchdog.cam1                  ERROR   : Ffmpeg process crashed unexpectedly for cam1.
frigate  | 2025-03-21 03:07:58.830005814  [2025-03-21 03:07:58] watchdog.cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-03-21 03:07:58.830053615  [2025-03-21 03:07:58] ffmpeg.cam1.detect             ERROR   : [AVHWFramesContext @ 0x7e0b4c04be80] Failed to sync surface 0xc: 1 (operation failed).
frigate  | 2025-03-21 03:07:58.830085097  [2025-03-21 03:07:58] ffmpeg.cam1.detect             ERROR   : [hwdownload @ 0x7e0b5c003980] Failed to download frame: -5.
frigate  | 2025-03-21 03:07:58.830170050  [2025-03-21 03:07:58] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x60bd99a760c0] Error while filtering: Input/output error
frigate  | 2025-03-21 03:07:58.830171985  [2025-03-21 03:07:58] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x60bd99a760c0] Task finished with error code: -5 (Input/output error)
frigate  | 2025-03-21 03:07:58.830181103  [2025-03-21 03:07:58] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x60bd99a760c0] Terminating thread with return code -5 (Input/output error)
frigate  | 2025-03-21 03:08:33.904823551  [2025-03-21 03:08:33] frigate.video                  ERROR   : cam1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-21 03:08:33.904860706  [2025-03-21 03:08:33] frigate.video                  ERROR   : cam1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-21 03:08:38.839677002  [2025-03-21 03:08:38] watchdog.cam1                  ERROR   : Ffmpeg process crashed unexpectedly for cam1.
frigate  | 2025-03-21 03:08:38.839707517  [2025-03-21 03:08:38] watchdog.cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-03-21 03:08:38.839732055  [2025-03-21 03:08:38] ffmpeg.cam1.detect             ERROR   : [AVHWFramesContext @ 0x777ec804b680] Failed to sync surface 0x12: 1 (operation failed).
frigate  | 2025-03-21 03:08:38.839770929  [2025-03-21 03:08:38] ffmpeg.cam1.detect             ERROR   : [hwdownload @ 0x777edc003980] Failed to download frame: -5.
frigate  | 2025-03-21 03:08:38.839798810  [2025-03-21 03:08:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x635ad8ad7d40] Error while filtering: Input/output error
frigate  | 2025-03-21 03:08:38.839830172  [2025-03-21 03:08:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x635ad8ad7d40] Task finished with error code: -5 (Input/output error)
frigate  | 2025-03-21 03:08:38.839837455  [2025-03-21 03:08:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x635ad8ad7d40] Terminating thread with return code -5 (Input/output error)
frigate  | 2025-03-21 03:08:44.570369278  127.0.0.1 - - [21/Mar/2025:03:08:44 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-03-21 03:09:38.349506816  [2025-03-21 03:09:38] frigate.video                  ERROR   : cam1: Unable to read frames from ffmpeg process.
frigate  | 2025-03-21 03:09:38.349574871  [2025-03-21 03:09:38] frigate.video                  ERROR   : cam1: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-03-21 03:09:38.849897625  [2025-03-21 03:09:38] watchdog.cam1                  ERROR   : Ffmpeg process crashed unexpectedly for cam1.
frigate  | 2025-03-21 03:09:38.849909185  [2025-03-21 03:09:38] watchdog.cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-03-21 03:09:38.849929094  [2025-03-21 03:09:38] ffmpeg.cam1.detect             ERROR   : [AVHWFramesContext @ 0x7781c404b6c0] Failed to sync surface 0xc: 1 (operation failed).
frigate  | 2025-03-21 03:09:38.849947081  [2025-03-21 03:09:38] ffmpeg.cam1.detect             ERROR   : [hwdownload @ 0x7781d4003980] Failed to download frame: -5.
frigate  | 2025-03-21 03:09:38.849973508  [2025-03-21 03:09:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x610b8d0a03c0] Error while filtering: Input/output error
frigate  | 2025-03-21 03:09:38.849992990  [2025-03-21 03:09:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x610b8d0a03c0] Task finished with error code: -5 (Input/output error)
frigate  | 2025-03-21 03:09:38.850016801  [2025-03-21 03:09:38] ffmpeg.cam1.detect             ERROR   : [vf#0:0 @ 0x610b8d0a03c0] Terminating thread with return code -5 (Input/output error)
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
{"cameras":{"cam1":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":417,"capture_pid":424,"ffmpeg_pid":251713,"audio_rms":103.9199,"audio_dBFS":-49.975}},"detectors":{"coral":{"inference_speed":7.68,"detection_start":0.0,"pid":251491}},"detection_fps":0.0,"gpu_usages":{"intel-vaapi":{"gpu":"5.98%","mem":"-%","clients":{"251713":"27.57%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"17.0","mem":"93.1"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"17":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"85":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"97":{"cpu":"1.5","cpu_average":"1","mem":"0.0","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"116":{"cpu":"0.8","cpu_average":"0","mem":"0.7","cmdline":"python3 -u -m frigate"},"124":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"131":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"162":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"163":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"164":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"165":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"166":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"315":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"367":{"cpu":"1.4","cpu_average":"0","mem":"0.2","cmdline":"frigate.recording_manager"},"402":{"cpu":"0.2","cpu_average":"0","mem":"0.1","cmdline":"frigate.output       "},"416":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"417":{"cpu":"0.8","cpu_average":"1","mem":"0.2","cmdline":"frigate.process:cam1 "},"424":{"cpu":"1.5","cpu_average":"1","mem":"0.1","cmdline":"frigate.capture:cam1 "},"427":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"python3 -u -m frigate"},"443":{"cpu":"1.2","cpu_average":"1","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/cam1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/cam1@%Y%m%d%H%M%S%z.mp4"},"444":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"453":{"cpu":"0.4","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/cam1 -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:"},"251491":{"cpu":"0.0","cpu_average":"0","mem":"0.7","cmdline":"frigate.detector.coral"},"251713":{"cpu":"5.0","cpu_average":"5","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/cam1 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"275628":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"275699":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":146890,"version":"0.15.0-cea210d","latest_version":"0.15.0","storage":{"/media/frigate/recordings":{"total":920772.0,"used":915957.0,"free":4815.0,"mount_type":"nfs4"},"/media/frigate/clips":{"total":920772.0,"used":915957.0,"free":4815.0,"mount_type":"nfs4"},"/tmp/cache":{"total":1907.4,"used":11.3,"free":1896.1,"mount_type":"tmpfs"},"/dev/shm":{"total":1024.0,"used":265.1,"free":758.9,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1742543373},"processes":{"recording":{"pid":367},"review_segment":{"pid":369},"go2rtc":{"pid":97},"audio_detector":{"pid":427}}}
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri:/dev/dri # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/nvr-hdd/systems/volumes/frigate_data_02:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      #- "8971:8971" # auth
      - "8971:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "<redacted>"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

dahua HDW2441TMP-S-DG 

### Any other information that may be helpful

it is working great, other then these crashes every few hours
