### DISCUSSION TITLE
Frigate HA Integration will not install

### DISCUSSION THREAD

**Discussion by birdman7160** [blakeblackshear/frigate#17280] [General Support] [answered]
### Describe the problem you are having

I installed FRIGATE in a WINDOWS 11 VM environment. I installed OpenCV after installing FRIGATE (don't know if that was a problem or not). I got my cameras installed and working but noticed that my UI was different than what i was seeing in YOUTUBE videos. I had a number of issues getting things to work. So I decided to delete the current FRIGATE instance and start anew. I uninstalled FRIGATE Add-on, deleted the FRIGATE Integration, and renamed the frigate.yaml file. I then stopped and restarted my VM, rebooted HA. I successfully reinstalled FRIGATE Addon and but when i tried to install the HA Frigate Integration I got the following error in the System Log:

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:369
integration: Frigate (documentation, issues)
First occurred: 4:42:58 PM (4 occurrences)
Last logged: 4:46:37 PM

Unauthorized (401) error for URL http://ccab4aaf-frigate:5000/api/login: Unauthorized

### Version

Current version: 0.15.0 (Changelog)

### What browser(s) are you using?

Google Chrome Version 134.0.6998.117 (Official Build) (64-bit)

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60

detectors:
  cpu1:
    type: cpu

go2rtc:
  streams:
    your_reolink_doorbell:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Jmmreolink01#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.0.81:554/Preview_01_main
    your_reolink_doorbell_sub:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Jmmreolink01"
      - rtsp://192.168.0.81:554/Preview_01_sub

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 480 # <- optional, by default Frigate tries to automatically detect resolution
      height: 640 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car


version: 0.15-1
```

### Relevant Frigate log output

```shell
Not relevant to the Frigate Integration (I don't believe)
```

### Relevant go2rtc log output

```shell
Not relevant to the Frigate Integration (I don't believe)
```

### FFprobe output from your camera

```shell
Not relevant to the Frigate Integration (I don't believe)
```

### Frigate stats

```json
Not relevant to the Frigate Integration (I don't believe)
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
Not relevant to the Frigate Integration (I don't believe)
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Not relevant to the Frigate Integration (I don't believe)

### Screenshots of the Frigate UI's System metrics pages

Not relevant to the Frigate Integration (I don't believe)
