### DISCUSSION TITLE
[Camera Support]: Tapo c200c Material version 5 Firmware 1.1.4

### DISCUSSION THREAD

**Discussion by Madeuh** [blakeblackshear/frigate#17292] [Camera Support] [answered]
### Describe the problem you are having

Hi all,

I have a tapo apo c200c Material version 5 Firmware 1.1.4, all it's ok for rtsp but when i want to have onvif i have this in log 
Tag
frigate.ptz.onvif
Message
No appropriate Onvif profiles found for camera: camera_bas.
So i can't have ptz button in frigate, if i test this on other application like anycam all works 
My onvif  config for this camera is 
onvif:
      host: 192.168.100.155
      port: 2020
      user: user
      password: pwd

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.7.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: USER
  password: PWD
tls:
  enabled: false
logger:
  # Optional: default log level (default: shown below)
  default: warning
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  camera_bas:
    enabled: true
    onvif:
      host: 192.168.100.155
      port: 2020
      user: USER
      password: PWD
      ignore_time_mismatch: True
     
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_bas 
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_bas2
          input_args: preset-rtsp-restream
          roles:
            - detect
    
    detect:
      enabled: true
      fps: 5
      width: 640 # largeur de l'image du flux secondaire (en pixels)
      height: 480 # hauteur de l'image du flux secondaire (en pixels)
    objects:
      track:
        - person
        - dog
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
  piscine_ext:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/piscine_ext #rtsp://USER:PWD@192.168.7.240:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/piscine_ext_Flux2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      width: 640 # largeur de l'image du flux secondaire (en pixels)
      height: 480 # hauteur de l'image du flux secondaire (en pixels)
    objects:
      track:
        - person
        - dog
        - car
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

  piscine_int:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/piscine_int #rtsp://USER:PWD@192.168.7.240:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/piscine_int_Flux2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      width: 640 # largeur de l'image du flux secondaire (en pixels)
      height: 480 # hauteur de l'image du flux secondaire (en pixels)
    objects:
      track:
        - person
        - dog
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
  
  sous_sol:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sous_sol #rtsp://USER:PWD@192.168.7.240:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sous_sol_Flux2 #rtsp://USER:PWD@192.168.7.240:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      width: 640 # largeur de l'image du flux secondaire (en pixels)
      height: 480 # hauteur de l'image du flux secondaire (en pixels)
    objects:
      track:
        - person
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_Flux2
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true
      fps: 5
      #width: 1536 # largeur de l'image du flux secondaire (en pixels)
      #height: 576 # hauteur de l'image du flux secondaire (en pixels)
    objects:
      track:
        - person
        - dog
        - car
      filters:
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
    motion:
      mask: 0.016,0.053,0.32,0.051,0.319,0.115,0.016,0.121
record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 2
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  alerts:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 14
    # Optional: Per object retention days
    objects:
      person: 14
      car: 14


go2rtc:
  streams:
    piscine_ext: 
      rtsp://USER:PWD@192.168.100.154:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif                 #DAHUA
    piscine_ext_Flux2: 
      rtsp://USER:PWD@192.168.100.154:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif                 #DAHUA
    piscine_int: 
      rtsp://USER:PWD@192.168.100.153:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    piscine_int_Flux2: 
      rtsp://USER:PWD@192.168.100.153:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    sous_sol: 
      rtsp://USER:PWD@192.168.100.152:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    sous_sol_Flux2: 
      rtsp://USER:PWD@192.168.100.152:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    garage: 
      rtsp://USER:PWD@192.168.100.151:554/Streaming/Channels/101
    garage_Flux2: 
      rtsp://USER:PWD@192.168.100.151:554/Streaming/Channels/102
    camera_bas:
      rtsp://USER:PWD@192.168.100.155:554/stream1
    camera_bas2:
      rtsp://USER:PWD@192.168.100.155:554/stream2
  webrtc:
    listen: :8555     # address of your local server and port (TCP/UDP)
    candidates:
      - 192.168.7.4:8555    # if you have static public IP-address (1.2.3.4 To replace by External Public IP)
      - stun:8555   # if you have dynamic public IP-address
    ice_servers:
      - urls: [turn:a.relay.metered.ca:443]   #TURN Server on https://www.metered.ca/stun-turn
        username: USER
        credential: PWD
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-03-21 17:10:10.649820414  [INFO] Preparing Frigate...
2025-03-21 17:10:11.064644599  [INFO] Starting Frigate...
2025-03-21 17:10:24.108852408  [2025-03-21 17:10:24] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-03-21 17:10:24.320796746  [2025-03-21 17:10:24] frigate.util.config            INFO    : frigate config does not need migration...
2025-03-21 17:10:26.434712520  [2025-03-21 17:10:26] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2025-03-21 17:10:49.571193507  [2025-03-21 17:10:49] ffmpeg.piscine_int.record      ERROR   : [rtsp @ 0x5f19ee214fc0] method DESCRIBE failed: 404 Not Found
2025-03-21 17:10:49.571727772  [2025-03-21 17:10:49] ffmpeg.piscine_int.record      ERROR   : [in#0 @ 0x5f19ee214cc0] Error opening input: Server returned 404 Not Found
2025-03-21 17:10:49.572139339  [2025-03-21 17:10:49] ffmpeg.piscine_int.record      ERROR   : Error opening input file rtsp://127.0.0.1:8554/piscine_int.
2025-03-21 17:10:49.572739274  [2025-03-21 17:10:49] ffmpeg.piscine_int.record      ERROR   : Error opening input files: Server returned 404 Not Found
2025-03-21 17:10:56.423610922  [2025-03-21 17:10:56] frigate.ptz.onvif              ERROR   : No appropriate Onvif profiles found for camera: camera_bas.
```

### Relevant go2rtc log output

```shell
2025-03-21 17:10:10.648248025  [INFO] Preparing new go2rtc config...
2025-03-21 17:10:11.597261144  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-03-21 17:10:11.812940360  [INFO] Starting go2rtc...
2025-03-21 17:10:11.985595524  17:10:11.985 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-03-21 17:10:11.985601419  17:10:11.985 INF config path=/dev/shm/go2rtc.yaml
2025-03-21 17:10:11.986426633  17:10:11.986 INF [api] listen addr=:1984
2025-03-21 17:10:11.986575772  17:10:11.986 INF [rtsp] listen addr=:8554
2025-03-21 17:10:11.987176354  17:10:11.987 INF [webrtc] listen addr=:8555
2025-03-21 17:10:20.651097181  [INFO] Starting go2rtc healthcheck service...
2025-03-21 17:10:29.775104533  17:10:29.774 WRN [rtsp] error="streams: wrong user/pass" stream=piscine_int
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

TAP C200C V5

### Screenshots of the Frigate UI's System metrics pages

![Sans titre](https://github.com/user-attachments/assets/49ba01ac-5004-401a-944c-93f73e960c3d)
