### DISCUSSION TITLE
How do I record only when certain audio detectors trigger?

### DISCUSSION THREAD

**Discussion by javydekoning** [blakeblackshear/frigate#17302] [Ask A Question]
I have a babymonitor that I'd like to record when there is crying detected. 

In 0.14 something like this was supported:

```yaml
    record:
      events:
        retain:
          default: 3
          mode: motion
          objects:
            crying: 7
```

How do I achieve this now? I'm not interested in any motion or object events. I only want to record based on audio triggers.
