### DISCUSSION TITLE
Running Frigate with Let’s Encrypt SSL without Reverse Proxy?

### DISCUSSION THREAD

**Discussion by Tauchsport-Nidwalden** [blakeblackshear/frigate#17303] [Ask A Question]
Hi everyone,

I’m running Frigate in a Docker container on a Raspberry Pi and I’d like to secure the web interface with HTTPS using Let’s Encrypt, but without using a reverse proxy like Nginx or Traefik.

Goal:
Access Frigate directly via https://my-domain.com:PORT with a valid Let’s Encrypt certificate.

Questions:

1. Is it possible to run Frigate with Let’s Encrypt SSL certificates without a reverse proxy?

2. If yes: What does the correct configuration look like?

Which settings or environment variables need to be configured in docker-compose.yml or config.yml?

Where do I mount or reference the certificate files (fullchain.pem, privkey.pem)?

3. Are there any known limitations or downsides to this setup?

My setup:

Raspberry Pi 5, Docker running, Frigate (latest version)

Let’s Encrypt certificates already available (stored at /etc/ssl/tauchsport-zertifikate/)

I’d prefer a minimal setup without additional reverse proxy layers

Looking forward to your input or example configurations.

Thanks in advance

**Comment by hawkeye217** [comment]
This is covered in the official documentation. https://docs.frigate.video/configuration/tls/

Frigate supports using Let's Encrypt certificates directly without a reverse proxy  [(1)](https://docs.frigate.video/configuration/tls/#certificates) . Here's how to set it up:

1. In your docker-compose.yml, add a volume mount for your certificates :

```yaml
frigate:
  ...
  volumes:
    - /etc/ssl/tauchsport-zertifikate:/etc/letsencrypt/live/frigate:ro
  ...
```

2. Within your certificate folder, Frigate expects :
- Private key named `privkey.pem`
- Certificate named `fullchain.pem`

3. If you're using certbot, you'll also need to mount the archive folder since certbot uses symlinks :

```yaml
frigate:
  ...
  volumes:
    - /etc/ssl/tauchsport-zertifikate:/etc/letsencrypt/live/frigate:ro
    - /etc/letsencrypt/archive/frigate:/etc/letsencrypt/archive/frigate:ro
  ...
```

4. To make Frigate accessible without specifying a port number, map port 8971 to 443 :

```yaml
frigate:
  ...
  ports:
    - "443:8971"
  ...
```

Important notes:
- Frigate automatically checks the certificate fingerprint every minute and reloads if changed 
- By default, Frigate will generate a self-signed certificate for port 8971 if no certificate is provided 
- TLS can be disabled completely in the config if needed 

For your config.yml, the TLS section should look like this :

```yaml
tls:
  enabled: True
```

This setup should allow you to access Frigate securely via HTTPS without an additional reverse proxy layer.
