### DISCUSSION TITLE
JSMPEG Fallback

### DISCUSSION THREAD

**Discussion by lngarrett** [blakeblackshear/frigate#17300] [Ask A Question]
I have an issue where in grid mode, my cameras will start in MSE, but over several minutes they fallback to JSMPEG. Nothing obvious is jumping out to me in console or server logs. I'd like to self troubleshoot this a bit. So, my questions currently is if there's any guidance on better observing what might be happening here. 

Looking at the code it appears that the key fallback mechanism occurs when:
  - MsePlayer encounters errors (stalled buffer, decode issues, or startup problems)
  - After 3+ errors, it calls onError?.("startup") to signal LivePlayer
  - LivePlayer then resets and potentially changes player type

Are these areas I should light up with more logging or are there other areas I should be focused?

FWIW, this issue has been present even in .15. I have solid network connectivity and strong hardware on both client and server. I am running 15 cameras, I have a hunch that might have something to do with it. I did switch to substreams in .16, but that hasn't helped.

```
cameras:
  westcam:
    enabled: true
    ffmpeg:
      inputs:
        # Sub-stream
        - path:
            rtsp://foo:bar@foobar:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        # Main-stream
        - path:
            rtsp://foo:bar@foobar:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    live: # .16
      streams:
        Main Stream: westcam
        Sub Stream: westcam_sub
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - car
    motion:
      mask: 0.797,0.927,0.925,0.924,0.929,0.977,0.795,0.981
    zones:
      Near_House:
        coordinates: 0.002,0.992,0,0,0.756,0,0.943,0.525,0.972,0.996
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: Near_House

go2rtc:
  rtsp:
    username: foo
    password: bar
  streams:
    parkingcam:
      - rtsp://foo:bar@foobar:554/cam/realmonitor?channel=1&subtype=0
    parkingcam_sub:
      - ffmpeg:rtsp://foo:bar@foobar:554/cam/realmonitor?channel=1&subtype=1#video=h264#width=iw*1.205#height=ih#audio=copy
```
