### DISCUSSION TITLE
[Config Support]: Pre/Post Capture NW for Alerts/Detections

### DISCUSSION THREAD

**Discussion by Morphy99** [blakeblackshear/frigate#17309] [Config Support]
### Describe the problem you are having

I can't seem to get Pre or Post capture working with my config. I've checked previous issues and everything is set as specified but it still doesn't seem to make a difference. I've set up a test file to troubleshoot in the config below.

The preview GIF appears to show the few seconds before but when clicking on the event in review it starts playing from the exact moment the object was detected, not before as specified in Pre Capture.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: xxxx

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: false
auth:
  enabled: false
objects:
  track:
    - person

  filters:
    person:
      threshold: 0.7
      max_ratio: 0.7

record:
  enabled: true
  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 1
      mode: all
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 1
      mode: all
    pre_capture: 10
    post_capture: 10


snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 1

detect:
  stationary:
    interval: 10

motion:
  improve_contrast: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

cameras:
###############################################################front########################################################################

  front:
    ffmpeg:
      inputs:
        - path: /media/frigate/exports/front_c0vvie.mkv
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      mask:
        - 0,0.596,0,0,0.793,0.001,0.642,0.07,0.404,0.234,0.195,0.394
        - 0.148,0.939,0.227,0.858,0.304,1,0.174,0.997
        - 0.974,0.103,0.966,0.144,0.989,0.174,1,0.115
    zones:
      front_doorway:
        coordinates: 0.774,0.355,0.713,0.436,0.847,0.656,0.897,0.527
        loitering_time: 0
        filters:
          person:
            min_area: 20000
            max_area: 50000
      front_window:
        coordinates: 0.714,0.445,0.301,0.958,0.316,1,0.684,0.999,0.844,0.653
        loitering_time: 0
      front_path_close:
        coordinates: 0.309,0.996,0.296,0.954,0.572,0.618,0.403,0.238,0.196,0.4,0.003,0.602,0,1
        loitering_time: 0
      front_path_far:
        coordinates: 0.405,0.238,0.575,0.618,0.776,0.349,0.994,0,0.808,0,0.637,0.076
        loitering_time: 0
      front_103:
        coordinates: 0.897,0.512,0.782,0.35,0.818,0.281,0.996,0.009,1,0.205
        loitering_time: 0
      front_road:
        coordinates: 0,0.596,0,0,0.793,0.001,0.642,0.07,0.404,0.234,0.195,0.394
        loitering_time: 0
#        filters:
#          person:
#            min_area: 80000
#            max_area: 250000
#            min_score: 0.6
#            threshold: 0.7
    mqtt:
      required_zones:
        - front_doorway
        - front_window
    snapshots:
      required_zones:
        - front_doorway
        - front_window
    review:
      alerts:
        required_zones:
          - front_doorway
          - front_window
      detections:
        required_zones:
          - front_window
          - front_doorway
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

Coral
