### DISCUSSION TITLE
[Support]: Snapshot Image API

### DISCUSSION THREAD

**Discussion by github-tijlxyz** [blakeblackshear/frigate#17304] [General Support]
### Describe the problem you are having

I had the problem that the home assistant notifications using the blueprint were not showing the cropped snapshots that I configured.
So I looked at the API, on home assistant https://[home assistant]/api/frigate/notifications/[event]/snapshot.jpg?crop=1 or directly from frigate http://[frigate]/api/events/[event]/snapshot.jpg?crop=1 it shows exactly the same as without ?crop=1. What am I doing wrong here?

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: <redacted> # <---- same mqtt broker that home assistant uses
  user: <redacted>
  password: <redacted>
  enabled: true
  topic_prefix: frigate

auth:
  trusted_proxies:
    - 127.0.0.0/8

ffmpeg:
  hwaccel_args: preset-vaapi # <- hardware accelerated encoding
  output_args:
    record: preset-record-generic-audio-aac # <- add audio to recording

audio:
  enabled: true
  listen:
    - fire_alarm
    - scream
#    - speech
#    - yell

detectors:
  coral:
    type: edgetpu
    device: usb
    model_path: /edgetpu_model.tflite
    #width: 640
    #height: 640

birdseye:
  enabled: true
  mode: motion
  inactivity_threshold: 60

record:
  enabled: true
  retain:
    days: 30
    mode: all

#  events:
#    pre_capture: 30
#    post_capture: 30
#    retain:
#      default: 30
#      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 90
  bounding_box: true

detect:
  fps: 5
  enabled: true

ui:
  timezone: Europe/Berlin

objects:
  track:
    - person
    - cat
#    - car
    - bicycle
    - dog
  filters:
    cat:
      threshold: 0.50

go2rtc:
  streams:
    cam1:
      #- rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0#video=h264#video=copy#audio=copy#audio=aac#hardware
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:#video=h264#audio=aac#hardware"
    cam1_sub:
      - rtsp://<redacted>/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:#video=h264#audio=aac#hardware"

# ...

cameras:
  cam1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - detect
    objects:
      filters:
        person:
          mask: 0.283,0.445,0.297,0.531,0.351,0.525,0.336,0.422
    review:
      alerts:
        required_zones: myzone
    motion:
      threshold: 28
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.297,0.442,0.343,0.458,0.345,0.328,0.335,0.216,0.292,0.055,0.23,0.014,0.215,0.038,0.233,0.113,0.26,0.278,0.23,0.293,0.207,0.296,0.183,0.325,0.186,0.241,0.163,0.176,0.146,0.122,0.174,0.067,0.186,0,0,0,0,1,0.234,1,0.333,0.984,0.384,0.946,0.404,0.863,0.411,0.789,0.407,0.706,0.399,0.621,0.364,0.566
        - 0.517,0.88,0.478,0.773,0.473,0.712,0.463,0.643,0.475,0.599,0.462,0.6,0.443,0.573,0.435,0.531,0.42,0.501,0.429,0.408,0.456,0.373,0.419,0.373,0.404,0.303,0.479,0.268,0.435,0.202,0.421,0.109,0.399,0.054,0.412,0,0.458,0,0.48,0.087,0.524,0.082,0.549,0,0.889,0,0.888,0.03,0.856,0.039,0.868,0.065,0.865,0.109,0.825,0.14,0.844,0.178,0.883,0.284,0.906,0.405,0.879,0.459,0.845,0.464,0.849,0.51,0.897,0.56,0.92,0.669,0.912,0.771,0.887,0.816,0.84,0.856,0.806,0.812,0.775,0.776,0.766,0.71,0.738,0.722,0.702,0.672,0.704,0.759,0.693,0.825,0.644,0.892,0.607,0.896
        - 0,0.044,0.215,0.057,0.216,0,0,0
        - 0.893,0.251,0.915,0.3,0.937,0.332,0.971,0.395,0.983,0.5,0.991,0.545,0.999,0.561,1,0.297,1,0.219,0.988,0.204,0.965,0.14,0.946,0.124,0.921,0.136,0.902,0.184
        - 0.936,0,1,0,1,0.131,0.964,0.061
    zones:
      myzone:
        coordinates: 0.273,0.36,0.205,1,0.79,1,0.954,0.899,0.651,0.248
        inertia: 3
        loitering_time: 1
version: 0.15-1
```

### Relevant Frigate log output

```shell
frigate  | 2025-03-22 10:41:04.426779593  x.x.x.x - - [22/Mar/2025:10:41:04 +0000] "GET /api/events/1742632234.763904-alzqg7/snapshot.jpg?crop=1 HTTP/1.1" 200 1113489 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0" "x.x.x.x, x.x.x.x"
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri:/dev/dri # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/nvr-hdd/systems/volumes/frigate_data_02:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      #- "8971:8971" # auth
      - "8971:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "<redacted>"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

dahua HDW2441TMP-S-DG
