### DISCUSSION TITLE
Unable to get Image: ghcr.io/blakeblackshear/frigate:stable using Docker Compose:

### DISCUSSION THREAD

**Discussion by birdman7160** [blakeblackshear/frigate#17327] [Config Support]
### Describe the problem you are having

I am getting the following error when executing "docker compose up" command:
 unable to get image 'ghcr.io/blakeblackshear/frigate:stable': permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.48/images/ghcr.io/blakeblackshear/frigate:stable/json": dial unix /var/run/docker.sock: connect: permission denied

### Version

Current version: 0.15.0 

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    your_reolink_doorbell:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Jmmreolink01#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.0.81:554/Preview_01_main
    your_reolink_doorbell_sub:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Jmmreolink01"
      - rtsp://192.168.0.81:554/Preview_01_sub

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 480 # <- optional, by default Frigate tries to automatically detect resolution
      height: 640 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car


version: 0.15-1
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    your_reolink_doorbell:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Jmmreolink01#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.0.81:554/Preview_01_main
    your_reolink_doorbell_sub:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Jmmreolink01"
      - rtsp://192.168.0.81:554/Preview_01_sub

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 480 # <- optional, by default Frigate tries to automatically detect resolution
      height: 640 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car


version: 0.15-1
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    your_reolink_doorbell:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Jmmreolink01#video=copy#audio=copy#audio=opus"
      - rtsp://192.168.0.81:554/Preview_01_main
    your_reolink_doorbell_sub:
      - "ffmpeg:http://192.168.0.81:554/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Jmmreolink01"
      - rtsp://192.168.0.81:554/Preview_01_sub

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 480 # <- optional, by default Frigate tries to automatically detect resolution
      height: 640 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
    objects:
      track:
        - person
        - car


version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /wsl.localhost/Debian/home/millerdebian/config.yml:ro
      - /wsl.localhost/Debian/home/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

N/A

### Any other information that may be helpful

This is my first time using Linux, Docker or Docker Compose. Frigate was not running well, although it was running, in VM VirtualBox so trying to port it over to a cleaner environment.
