### DISCUSSION TITLE
[Config Support]: Where to configure IP to use for mDNS/avahi

### DISCUSSION THREAD

**Discussion by oransterf** [blakeblackshear/frigate#17353] [Config Support]
### Describe the problem you are having

I am running frigate with docker in bridged network mode and I have exposed UDP port 5353 however I believe the reason why Homekit does not show the cameras is because go2rtc is configured to use the local docker bridge IP.

### Version

0.15.0-cea210d

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nvme/frigate/config:/config
      - /mnt/nvme/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 500000000

    ports:
      - "8971:8971"
      # - "127.0.0.1:5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5353:5353/udp"
      - "127.0.0.1:1984:1984"
```
