### DISCUSSION TITLE
[Config Support]: Force Birdseye to do 3 columns and maximize the height of the screen

### DISCUSSION THREAD

**Discussion by ianpogi5** [blakeblackshear/frigate#17354] [Config Support]
### Describe the problem you are having

I have 8 cameras - 4 reolink and 4 anran(china brand). I want to see in birdseye a 3x3 layout with 1 empty slot at the end.

If I leave it auto, it creates 4x4 layout. It only occupies half the screen height which a waste of space.

I tried different resolution, scaling_factor and order but I couldn't make it 3x3.

Any help would be appreciated.

### Version

0.15.0

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: True
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

objects:
  track:
    - person
    - dog
    - cat
  filters:
    person:
      threshold: 0.8
    dog:
      threshold: 0.75
    cat:
      threshold: 0.85

cameras:
  FrontCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    birdseye:
      order: 1
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - delivery
        - yard
      retain:
        default: 20
    live:
      stream_name: FrontCam
    review:
      alerts:
        required_zones:
          - delivery
          - yard
  BackCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/BackCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    birdseye:
      order: 3
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    motion:
      mask:
        - 201,39,201,65,0,64,0,0,227,0,439,0,433,38
    live:
      stream_name: BackCam
  SideCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/SideCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    birdseye:
      order: 2
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    live:
      stream_name: SideCam
  LivingRoomCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.11.8:554/ch0_1.264
          roles:
            - detect
            - record
    birdseye:
      order: 7
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    motion:
      mask:
        - 0,71,0,0,399,0,396,40,236,36,237,72
    live:
      stream_name: LivingRoomCam
  HallwayCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        # high resoltion
        - path: rtsp://admin:xxxxxxx@192.168.11.4:554/h264Preview_01_main
          roles:
            - record
        # low resolution
        - path: rtsp://127.0.0.1:8554/HallwayCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      order: 8
    detect:
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    live:
      stream_name: HallwayCam
  StudyCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        # high resoltion
        - path: rtsp://admin:xxxxxxx@192.168.11.5:554/h264Preview_01_main
          roles:
            - record
        # low resolution
        - path: rtsp://127.0.0.1:8554/StudyCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      order: 4
    detect:
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    live:
      stream_name: StudyCam
  OfficeCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        # high resoltion
        - path: rtsp://admin:xxxxxxxxxx@192.168.69.6:554/h264Preview_01_main
          roles:
            - record
        # low resolution
        - path: rtsp://127.0.0.1:8554/OfficeCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      order: 5
    detect:
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    live:
      stream_name: OfficeCam
  BedroomCam:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        # high resoltion
        - path: rtsp://admin:xxxxxxxx@192.168.11.7:554/h264Preview_01_main
          roles:
            - record
        # low resolution
        - path: rtsp://127.0.0.1:8554/BedroomCam?video=h264&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      order: 6
    detect:
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 50
        threshold: 60
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 20
    live:
      stream_name: BedroomCam

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
  layout:
    scaling_factor: 1

go2rtc:
  streams:
    FrontCam:
      - rtsp://admin:xxxxxxxxxx@192.168.11.1:554/ch0_1.264
      - ffmpeg:FrontCam#video=h264#audio=aac#hardware
    BackCam:
      - rtsp://admin:xxxxxxxxxx@192.168.11.2:554/ch0_1.264
      - ffmpeg:BackCam#video=h264#audio=aac#hardware
    SideCam:
      - rtsp://admin:xxxxxxxxxx@192.168.11.3:554/ch0_1.264
      - ffmpeg:SideCam#video=h264#audio=aac#hardware
    HallwayCam:
      - rtsp://admin:xxxxxxxx@192.168.5.4:554/h264Preview_01_sub
    StudyCam:
      - rtsp://admin:xxxxxxx@192.168.11.5:554/h264Preview_01_sub
    OfficeCam:
      - rtsp://admin:xxxxxxxxxx@192.168.69.6:554/h264Preview_01_sub
    BedroomCam:
      - rtsp://admin:xxxxxxxx@192.168.11.7:554/h264Preview_01_sub
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuActivitySquare
    cameras: birdseye
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate-config:/config
      - frigate-recordings:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    cap_add:
      - CAP_PERFMON
volumes:
  frigate-config:
    external: true
  frigate-recordings:
    external: true
```

### Object Detector

Coral
