### DISCUSSION TITLE
Dual Coral USB devices not working together on Beelink Sei 12 Pro

### DISCUSSION THREAD

**Discussion by berkansezer77** [blakeblackshear/frigate#17350] [Detector Support]
### Describe the problem you are having

I'm running Frigate 0.15.0 as an add-on in Home Assistant OS on a Beelink SEi12 Pro mini PC. I have two USB Coral Edge TPUs connected directly to the USB ports.

While Frigate successfully detects and uses the first TPU (usb:0), it fails to initialize the second TPU (usb:1). Upon startup, Frigate shows the following error:

frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb:1
frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
ValueError: Failed to load delegate from libedgetpu.so.1.0

### Version

0.15

### Frigate config file

```yaml
mqtt:
  host: (myhost)
  user: (myuser)
  password: (mypass)
  port: 1883

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
record:
  enabled: true
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1
objects:
  track:
    - person

snapshots:
  enabled: true
  retain:
    default: 1

cameras:
  ofisag:
    detect:
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: (my rtsp)
          roles:
            - detect
            - rtmp
            - clips
    best_image_timeout: 60
    zones:
      ofissag_zone:
        coordinates: 
          1166,470,1060,408,905,337,629,220,468,267,354,300,273,326,289,388,241,0,0,0,0,720,1033,720
      ofissag_tuvalet:
        coordinates: 199,270,112,303,148,435,277,395
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 1
      alerts:
        retain:
          days: 1
      detections:
        retain:
          days: 1
    snapshots:
      enabled: true
      required_zones:
        - ofissag_zone
      retain:
        default: 1
    review:
      alerts:
        required_zones: ofissag_zone
      detections:
        required_zones: ofissag_zone
```

### docker-compose file or Docker CLI command

```yaml
Frigate is running as a Home Assistant OS add-on, not using Docker CLI or docker-compose directly.
```

### Relevant Frigate log output

```shell
[2025-03-25 01:30:25] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb:1
[2025-03-25 01:30:25] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Install method

Home Assistant Add-on

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/229bb551-11fc-4a2f-b6ca-3dfb8f690acd)
