### DISCUSSION TITLE
How to create image entity for specific combination of camera and zones?

### DISCUSSION THREAD

**Discussion by Mincka** [blakeblackshear/frigate#17361] [Ask A Question] [answered]
I would like to show on my HA dashboard "the latest person seen in zone x by camera y" using `image` entity.

Currently, such combination is not possible and I requested it [here](https://github.com/blakeblackshear/frigate-hass-integration/issues/679).
Using `required_zone` is not enough because I want the flexibility to use different zones for different scenarios.

In the meantime, I filter events on MQTT for the combination I want.
Then, I save the snapshot I get from event or review endpoints somewhere as `camera_zone_object_latest.jpg`.

1) Is it the best approach to do that right now?
2) Does anyone know how update a [MQTT Image](https://www.home-assistant.io/integrations/image.mqtt/) based on Frigate MQTT event and the API to get the image? That could be better approach to handle this as an `image` entity.

**Comment by hawkeye217** [comment, marked as answer]
Untested, but you could probably do something like this:

```
automation:
  - alias: "Update Latest Person in Zone X by Camera Y"
    trigger:
      - platform: mqtt
        topic: "frigate/events"
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json['after']['camera'] == 'camera_y' }}"
      - condition: template
        value_template: "{{ 'zone_x' in trigger.payload_json['after']['entered_zones'] }}"
      - condition: template
        value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
    action:
      - service: mqtt.publish
        data:
          topic: "homeassistant/image/latest_person_zone_x_camera_y"
          payload: "http://<HA_URL>/api/frigate/notifications/{{ trigger.payload_json['after']['id'] }}/snapshot.jpg"
```

Then you can just use the MQTT image integration to get the image from the `homeassistant/image/latest_person_zone_x_camera_y` topic.

Using `snapshot.jpg` requires snapshots to be enabled, of course. And you may also need to check if the snapshot exists on the event before publishing. See the MQTT payload in the docs: https://docs.frigate.video/integrations/mqtt

**Reply by Mincka** [reply]
Thanks a lot for the pointers.

I managed to create the MQTT Image entity with this config, publish on the topic and I can see the image on HA.

```
mqtt:
  - image:
      unique_id: latest_person_zone_x_camera_y
      name: Latest person in zone X camera Y
      url_topic: homeassistant/image/latest_person_zone_x_camera_y
```

```
action: mqtt.publish
data:
  topic: homeassistant/image/latest_person_zone_x_camera_y
  payload: >-
    https://xxxxxxx
```

I will complete the automation and post it here if it can help others.
