### DISCUSSION TITLE
[Support]: "Snapshot Not Available" via API. Event "1 unavailable object was detected and included in this review item"

### DISCUSSION THREAD

**Discussion by jonofmac** [blakeblackshear/frigate#17370] [General Support]
### Describe the problem you are having

I'm using the automation [https://github.com/SgtBatten/HA_blueprints](https://github.com/SgtBatten/HA_blueprints) that utilizes the events mqtt topic.

For the most part, using events cut down on "false notifications". I just got one though, and I don't understand why it fails to load. The issue I don't believe is the automation, but rather how frigate sent the event gets saved/processed with sublabels. So perhaps a bug.

I've got an event where a UPS truck pulled up in front of my house, a driver hopped out and walked up my sidewalk (a different zone). This event gets recognized/tagged with UPS and package (not car though). It sent a MQTT message to events that the automation saw and sent my phone a notification. However, the thumb nail did not work (it works in other events). Looking through the HA trace and looking at the URL it pointed to for the thumbnail and screenshot, when I open them, I get the following response from the frigate API: 
<img width="413" alt="image" src="https://github.com/user-attachments/assets/c87acd8c-a3e5-4a53-b685-8a3350e2684b" />

I get this same error when I click on "view snapshot", but it works if I click on "view clip". So something about the snapshot specifically changed/got deleted.

So when I open up the event in Frigate, I see the following in the event details pane
<img width="560" alt="image" src="https://github.com/user-attachments/assets/b4c8f8ec-9595-4bf5-a542-b8a01fce33e9" />

The error seems to be because I do not detect ups in the car_loitering zone (see camera config below)

Then looking at the HA trace that kicked the automation off:
```
payload_json:
    type: new
    before:
      id: 1742932980.962107-jjem7v
      camera: front_yard
      start_time: 1742932980.962107
      end_time: null
      severity: alert
      thumb_path: >-
        /media/frigate/clips/review/thumb-front_yard-1742932980.962107-jjem7v.webp
      data:
        detections:
          - 1742932960.476375-d5y2nj
        objects:
          - ups
        sub_labels: []
        zones:
          - car_loitering
        audio: []
```

This however would be ignored by the automation if it only ended here because this automation doesn't care what happens in the street. It only looks at objects when they cross into "yard". 

In this JSON payload:
```
id: 1742932980.962107-jjem7v
        camera: front_yard
        start_time: 1742932980.962107
        end_time: 1742933066.200274
        severity: alert
        thumb_path: >-
          /media/frigate/clips/review/thumb-front_yard-1742932980.962107-jjem7v.webp
        data:
          detections:
            - 1742932960.476375-d5y2nj
            - 1742932999.726803-hmjfxl
            - 1742933016.706823-28tlry
            - 1742933034.975934-ckz5mj
          objects:
            - ups
            - car
            - person
          sub_labels: []
          zones:
            - car_loitering
            - yard
          audio: []
```

So I started testing the api for each detection item:

1. 1742932980.962107-jjem7v - "Event not found"
2. 1742932960.476375-d5y2nj - "Snapshot not available"
3. 1742932999.726803-hmjfxl - Snapshot works. ![image](https://github.com/user-attachments/assets/8003c66d-813c-4da2-865f-d8c6dc86d0a6)
4. 1742933016.706823-28tlry - "Event not found"
5. 1742933034.975934-ckz5mj - Snapshot works. 
![image](https://github.com/user-attachments/assets/7a579cf4-535f-49ff-a928-257d34cb7848)

Why do the snapshots for the truck no longer work? I suspect it's because I do not do detections for cars/ups/etc in the "street" zone. But the only "snapshots" that work are the person's snapshots. Yet somehow a snapshot works for the event in the review pane
<img width="501" alt="image" src="https://github.com/user-attachments/assets/a4e9641e-779e-48b5-8fdc-009c10f907dd" />

Not sure if it's the act of an object changing objects, or an initial detection which crosses into a zone to become a valid alert/detection.

Trying to understand why an object is created as "new event" in mqtt is ups in the street is not something I allow as a detection according to the config. Shouldn't the event not be started until a detection/alert happens? Or is it based purely off of any detection?

Are there general rules for how to handle situations like this? Should I not do any object detection in the street zone (since I do not require street for a detection or alert)

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox 136.0.2

### Frigate config file

```yaml
front_yard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/rtsp_front_yard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: rtsp_front_yard
    detect:
      fps: 4
      annotation_offset: -1000
    motion:
      mask:
        - 0.415,0.061,0.345,0.09,0.335,0,1,0,1,0.162,0.896,0.104,0.699,0.054
        - 0,0,0.273,0,0.28,0.058,0.23,0.1,0.151,0.147,0,0.243
        - 0.018,0.913,0.322,0.901,0.322,0.96,0.019,0.956
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      yard:
        coordinates: 
          0.07,0.306,0,0.404,0,1,1,1,1,0.422,0.887,0.233,0.65,0.191,0.374,0.203,0.263,0.224,0.119,0.268
        objects:
          - person
          - motorcycle
          - bicycle
          - face
          - cat
          - dog
          - fox
          - squirrel
          - racoon
        min_area: 3000
        inertia: 3
        loitering_time: 0
      driveway:
        coordinates: 1,0.425,1,0.284,0.893,0.246
        objects:
          - person
          - fedex
          - amazon
          - ups
          - usps
          - car
          - motorcycle
          - bicycle
          - cat
          - dog
          - fox
          - squirrel
          - racoon
        inertia: 3
      street:
        coordinates: 
          0,0.26,0.165,0.162,0.229,0.113,0.308,0.066,0.344,0.065,0.292,0.113,0.457,0.076,0.613,0.064,0.824,0.091,1,0.152,1,0.251,0.649,0.182,0.323,0.201,0.124,0.265,0,0.333
        objects:
          - car
          - motorcycle
          - bicycle
          - person
          - face
          - amazon
          - ups
          - usps
          - fedex
          - cat
          - dog
          - fox
          - squirrel
          - racoon
          - waste bin
        inertia: 3
        loitering_time: 300
      car_loitering:
        coordinates: 
          0.367,0.155,0.274,0.17,0.193,0.21,0.175,0.29,0.412,0.272,0.614,0.3,0.611,0.138,0.526,0.133
        loitering_time: 10
        objects:
          - car
          - motorcycle
          - bicycle
          - person
        inertia: 3
    objects:
      filters:
        car:
          min_area: 3000
        person:
          min_area: 3000
    snapshots:
      required_zones:
        - street
        - driveway
        - yard
    review:
      alerts:
        required_zones:
          - driveway
          - yard
          - car_loitering
      detections:
        required_zones:
          - yard
          - driveway
          - car_loitering
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision Cameras
