### DISCUSSION TITLE
HA Frigate Integration "FAILED TO CONNECT"

### DISCUSSION THREAD

**Discussion by birdman7160** [blakeblackshear/frigate#17372] [Config Support] [answered]
### Describe the problem you are having

I am running Debian-Docker Frigate on Windows 11. I am trying to install the HA Frigate Integration which is running on a Virtual Box VM. Frigate is running fine and the Web UI is up and running. However I cannot get the integration to install.

### Version

System 0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          roles:
            - detect
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:LAGGJW@192.168.0.57:554/Streaming/Channels/101/  #HIGH RESOLUTION
          roles:
            - record
        - path: rtsp://admin:LAGGJW@192.168.0.57:554/Streaming/Channels/102/  #LOW RESOLUTION
          roles:
            - detect
    detect:
      enabled: true


version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/millerdebian/frigate/config.yml:/config/config.yml
      - /home/millerdebian/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c6e2e889-b096-46df-9912-142c0d11656c)

### Any other information that may be helpful

        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2314f8a7ce265b645225a927c64c83333b3c2073d8fc692364e805a880625e31",
            "SandboxKey": "/var/run/docker/netns/2314f8a7ce26",
            "Ports": {
                "5000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5000"
                    }
                ],
                "8554/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8554"
                    }
                ],
                "8555/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8555"
                    }
                ],
                "8555/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8555"
                    }
                ],
                "8971/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8971"
                    }
                ]
            },
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "frigate_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "frigate",
                        "frigate"
                    ],
                    "MacAddress": "c2:d1:08:16:7a:5c",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "523763c9fb3bc24766fa48e6f17ed235ead8b41db9f6820777b1b0a08d1752be",
                    "EndpointID": "dabacbab68ec6731d1a1be49168c8a366aa2afa0db863202fff8f9ad5588f186",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "frigate",
                        "4b8c10815d7d"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:1fa122d39ec454dc0067b516778dd5ccabbd0dba34970d0c7451b89740f70beb",
            "size": 1632,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
