### DISCUSSION TITLE
How to have different zone and object dependencies?

### DISCUSSION THREAD

**Discussion by jonofmac** [blakeblackshear/frigate#17391] [Ask A Question]
Sorry for so many questions, I am struggling to figure out how to do this, or if it's even possible.

I've got a camera on my back porch, and it overlooks my porch and my parking area. I've got 2 zones: porch and parking_zone.

Is there a way to do the following with the config:

1. Any person detected in either zone is an alert
2. Any cat or dog detected in parking_zone is an alert
3. Any cat or dog detected in porch is a detection only

I think having #1 and 2 requirements makes this not possible with the alert/zone filters. Am I correct? My current config is below.

Perhaps a work around is to have a person be an alert always, and specify that cat/dog alerts require parking_zone, but I'm not sure how to do that.

I can remove the 'patio' zone from alerts, but then I won't get people alerts on the patio.

```
  back_porch:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: rtsp_back_porch
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      patio:
        coordinates: 0.957,0.608,0.333,0.083,0.234,0,0.115,0,0,0.102,0,1,0.982,1
        objects:
          - person
          - cat
          - dog
          - squirrel
        inertia: 3
        loitering_time: 0
      parking_zone:
        coordinates: 0.281,0,0.969,0,0.899,0.582,0.374,0.212,0.258,0.149
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - patio
        - parking_zone
    objects:
      track:
        - person
        - face
        - car
        - cat
        - dog
        - squirrel
    review:
      alerts:
        required_zones:
          - patio
          - parking_zone
        labels:
          - person
          - cat
          - dog
      detections:
        required_zones:
          - patio
          - parking_zone
        labels:
          - cat
          - dog
```

**Comment by NickM-27** [comment]
there is no way to do this with 2 zones, you would simply need to make three zones including 2 versions of porch, one with person and one with car / dog

**Reply by jonofmac** [reply]
Makes sense. That's a simple solution. Thanks.

**Comment by jonofmac** [comment]
Based on your suggestion, I've duplicated my patio zone, made it "animal" specific, changed the patio zone to be only for people. Then set up alerts for the people patio and detections for the animal patio zones.

```
  back_porch:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_back_porch
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: rtsp_back_porch
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      patio:
        coordinates: 0.957,0.608,0.333,0.083,0.234,0,0.115,0,0,0.102,0,1,0.982,1
        objects:
          - person
        inertia: 3
        loitering_time: 0
      parking_zone:
        coordinates: 0.281,0,0.969,0,0.899,0.582,0.374,0.212,0.258,0.149
        inertia: 3
        loitering_time: 0
      patio_animal:
        coordinates: 0.957,0.608,0.333,0.083,0.234,0,0.115,0,0,0.102,0,1,0.982,1
        objects:
          - cat
          - dog
          - fox
          - squirrel
          - racoon
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - patio
        - parking_zone
    objects:
      track:
        - person
        - face
        - car
        - cat
        - dog
        - fox
        - squirrel
        - racoon
    review:
      alerts:
        required_zones:
          - patio
          - parking_zone
        labels:
          - person
          - cat
          - dog
      detections:
        required_zones:
          - patio
          - patio_animal
          - parking_zone
        labels:
          - person
          - cat
          - dog
```
