### DISCUSSION TITLE
Config reset

### DISCUSSION THREAD

**Discussion by SavageAUS** [blakeblackshear/frigate#17425] [Config Support]
### Describe the problem you are having

Unable to access cameras as config had reset itself back to default.
Cameras working fine yesterday but today unable to view as config file was reverted back to default.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.XXXX
  port: 1883
  user: XXXXXXXXXXXXX
  password: XXXXXXXXXXXX
  topic_prefix: XXXXXXXX
  client_id: XXXXXXXXX
  stats_interval: 60

##------------------------------------------------------------------------------------------------------------------------------------------------------
detectors:
  coral1:
    type: edgetpu
    device: pci:0
    model_path: /edgetpu_model.tflite
  coral2:
    type: edgetpu
    device: pci:1

##------------------------------------------------------------------------------------------------------------------------------------------------------
database:
  path: /config/frigate.db

##------------------------------------------------------------------------------------------------------------------------------------------------------
auth:
  enabled: true
  reset_admin_password: false
  #cookie_name: frigate_token
  cookie_secure: false
  session_length: 86400 # 24 hours
  refresh_time: 43200 # 12 hours
  failed_login_rate_limit: None
  # trusted_proxies: [https://frigate.XXXXXXXXXX.XXX]
  hash_iterations: 600000

##------------------------------------------------------------------------------------------------------------------------------------------------------
#model:
#  path: /edgetpu_model.tflite
#  labelmap_path: /labelmap.txt
#  width: 320
#  height: 320
#  input_pixel_format: rgb
#  input_tensor: nhwc
#  model_type: ssd
#  labelmap:
#    1: person
#    2: car

##------------------------------------------------------------------------------------------------------------------------------------------------------
birdseye:
  enabled: true
  mode: continuous
  quality: 5
  restream: true
  width: 1920
  height: 1080

##------------------------------------------------------------------------------------------------------------------------------------------------------
ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: auto
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac
  retry_interval: 10

##------------------------------------------------------------------------------------------------------------------------------------------------------
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  min_initialized: 2
  max_disappeared: 50
  stationary:
    interval: 50
    threshold: 50
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000

##------------------------------------------------------------------------------------------------------------------------------------------------------
objects:
  track:
    - person
    #- fox
    #- car
    #- dog
    #- cat
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 2000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 0.8
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.50
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.6
#    car:
#      min_score: 0.50
#      threshold: 0.70
#    fox:
#      threshold: 0.5
#    cat:
#      threshold: 0.5
#    dog:
#      threshold: 0.5

##------------------------------------------------------------------------------------------------------------------------------------------------------
review:
  alerts:
    labels:
#      - car
      - person
#    required_zones:
#      - Turret-Front
#      - PTZ-Front
  detections:
    labels:
#      - car
      - person
#    required_zones:
#      - Turret-Front
#      - PTZ-Front

##------------------------------------------------------------------------------------------------------------------------------------------------------
motion:
  threshold: 20
  lightning_threshold: 0.8
  contour_area: 10
  frame_alpha: 0.01
  frame_height: 100
  improve_contrast: true

##------------------------------------------------------------------------------------------------------------------------------------------------------
record:
  #sync_recordings: True
  enabled: true
  retain:
    days: 14
    mode: all
  preview:
    quality: medium
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  alerts:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  height: 1080
  retain:
    default: 14
    objects:
      person: 14
  quality: 80

##------------------------------------------------------------------------------------------------------------------------------------------------------
go2rtc:
  modes:
    - webrtc
  streams:
    Turret:
      - rtsp://192.168.XXXXXX:554/11?video&audio
    PTZ:
      - rtsp://192.168.XXXXXX:554/12?video&audio
    VIGI:
      - rtsp://XXXXXX:XXXXXXXX@192.168.XXXXXXXX:554/stream2

##------------------------------------------------------------------------------------------------------------------------------------------------------
cameras:
  Turret:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://192.168.XXXXXXX:554/11
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0.752,0.04,1,0.044,1,0,0.752,0
    zones:
      FrontYard:
        coordinates: 0,1,0,0.244,0.139,0.186,0.411,0.139,0.457,0.2,0.775,0.328,1,0.419,1,1
        loitering_time: 0
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
    review: {}
    objects:
      mask: 0.394,0.103,0.395,0.213,0.42,0.214,0.419,0.102

  PTZ:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://192.168.XXXXXXX:554/12
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0.754,0,0.755,0.038,1,0.038,1,0
    zones:
      Front_Yard:
        coordinates: 0,0.266,0,1,0.766,1,1,1,1,0.343,1,0.104,0.6,0.17,0.331,0.183
        loitering_time: 0
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
    review: {}

  VIGI:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX:XXXXXXXX@192.168.XXXXXXXX:554/stream1?video&audio
          roles:
            - record
        - path: rtsp://XXXXXXXXX:XXXXXXXX@192.168.XXXXXXXX:554/stream2?video&audio
          roles:
            - detect
    motion:
      mask: 0,0,0,0.061,0.251,0.057,0.25,0
      threshold: 30
      contour_area: 10
      improve_contrast: true
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
    review: {}
    objects:
      mask:
        - 0,0.138,0,0.226,0.248,0.175,0.429,0.158,0.66,0.158,0.659,0.231,1,0.237,1,0,0.252,0,0.252,0.058,0,0.062
        - 0,0.222,0.024,0.227,0.073,0.513,0.104,1,0,1
        - 0.07,0.334,0.138,0.34,0.165,0.595,0.098,0.626
    zones:
      Front_Door:
        coordinates: 
          0.023,0.231,0.157,0.194,0.295,0.173,0.453,0.163,0.66,0.164,0.665,0.217,0.969,0.232,1,0.244,1,1,0.095,0.991
        loitering_time: 0

##------------------------------------------------------------------------------------------------------------------------------------------------------
live:
  stream_name: Turret, PTZ, VIGI
  height: 1080
  quality: 10

##------------------------------------------------------------------------------------------------------------------------------------------------------
telemetry:
  network_interfaces:
    - eth
    - enp
    - eno
    - ens
    - wl
    - lo
  # Optional: Configure system stats
  stats:
    # Enable AMD GPU stats (default: shown below)
    #amd_gpu_stats: True
    # Enable Intel GPU stats (default: shown below)
    intel_gpu_stats: true
    # Enable network bandwidth stats monitoring for camera ffmpeg processes, go2rtc, and object detectors. (default: shown below)
    # NOTE: The container must either be privileged or have cap_net_admin, cap_net_raw capabilities enabled.
    network_bandwidth: true
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
version: 0.15-1

##------------------------------------------------------------------------------------------------------------------------------------------------------
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: info

##------------------------------------------------------------------------------------------------------------------------------------------------------
camera_groups:
  All_Camera's:
    order: 1
    icon: LuCamera
    cameras:
      - PTZ
      - Turret
      - VIGI
      - birdseye
ui:
  timezone: Australia/Adelaide
```

### Relevant Frigate log output

```shell
No log
```

### Relevant go2rtc log output

```shell
No log
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
Unraid
```

### Object Detector

Coral
