### DISCUSSION TITLE
Add Timestamp to frigate.yaml when saving from Configuration Editor

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#17429] [Ideas]
I usually place a Date/Time stamp at the top of my configuration files, but sometimes I forget. Suggest adding a timestamp automatically when editing and saving using Frigate Configuration Editor.
```
# Date: March 28-2025 
# Time: 08:25
detectors:
  coral:
    type: edgetpu
    device: usb
```

81Xats
