### DISCUSSION TITLE
[Config Support]: onvif config document error

### DISCUSSION THREAD

**Discussion by christaikobo** [blakeblackshear/frigate#17422] [Config Support] [answered]
### Describe the problem you are having

The default onvif config example is this (https://docs.frigate.video/configuration/cameras/#setting-up-camera-ptz-controls):

```
cameras:
  back:
    ffmpeg: ...
    onvif:
      host: 10.0.10.10
      port: 8000
      user: admin
      password: password
```

It gives an impression that username and password does not have to be quoted, but in reality it must be quoted using double quotes otherwise the authentication fails. So I think the document should be amended like this:

```
cameras:
  back:
    ffmpeg: ...
    onvif:
      host: 10.0.10.10
      port: 8000
      user: "admin"
      password: "password"
```

### Version

N/A

### Frigate config file

```yaml
cameras:
  Living_Room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Living_Room
          roles:
            - record
            - detect
            - audio
    onvif:
      host: 192.168.1.1
      port: 2020
      user: "admin"
      password: "redacted"
```

### Relevant Frigate log output

```shell
2025-03-27 21:41:15.458165639  [2025-03-27 14:41:15] frigate.ptz.onvif              INFO    : Attempting ONVIF initialization for Living_Room (retry 1/5)
2025-03-27 21:41:17.481806567  [2025-03-27 14:41:17] frigate.ptz.onvif              ERROR   : Unable to get Onvif media profiles for camera: Living_Room: Authority failure
2025-03-27 21:41:17.482736572  [2025-03-27 14:41:17] frigate.ptz.onvif              WARNING : ONVIF initialization failed for Living_Room
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

OpenVino
