### DISCUSSION TITLE
Two Coral USB with two docker frigate containers

### DISCUSSION THREAD

**Discussion by RaTiMax** [blakeblackshear/frigate#17459] [Ask A Question] [answered]
Hello,
I am using 2 frigates on Docker. (so that the neighbor doesn't see all the cameras)
I bought 2 USB corals.

lsusb:
```
Bus 004 Device 003: ID 18d1:9302 Google Inc. 
...
Bus 002 Device 003: ID 18d1:9302 Google Inc. 
```

Both frigate configs use this config:
```
detectors:                                                                                                                                                                                                                                 
  coral:                                                                                                                                                                                                                                   
    type: edgetpu                                                                                                                                                                                                                          
    device: usb

```

I see that both frigates are using the USB coral. 
How can I check if both frigates are using separate corals?

The USB is shared in both docker containers like this:
 ```
 --device /dev/bus/usb:/dev/bus/usb \
  --privileged -v /dev/bus/usb:/dev/bus/usb
```

If this is not good, how should I do it?
Sorry for my bad english.
