### DISCUSSION TITLE
[Detector Support]: Tensorrt issue

### DISCUSSION THREAD

**Discussion by Matikjacc** [blakeblackshear/frigate#17451] [Detector Support]
### Describe the problem you are having

I set up the tensorrt and it worked for a while then it didn't detect the GPU correctly and started giving me this error. When changing the detector to openvino using CPU it detect the GPU correctly and everything works fine

### Version

0.15-1

### Frigate config file

```yaml
model:
  path: plus://----
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

detectors:
  tensorrt:
    type: tensorrt
    device: 0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    network_mode: host
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "256mb"  # Adjust based on available memory
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/md1/frigate:/media/frigate  # Adjust path for recordings
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
frigate  | 2025-03-30 12:56:16.088113901  2025/03/30 12:56:16 [error] 172#172: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate  | 2025-03-30 12:56:16.088121465  2025/03/30 12:56:16 [error] 172#172: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate  | 2025-03-30 12:56:16.152902071  [2025-03-30 12:56:16] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate  | 2025-03-30 12:56:16.243146588  [2025-03-30 12:56:16] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::32] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
frigate  | 2025-03-30 12:56:16.248911760  [2025-03-30 12:56:16] frigate.api.fastapi_app        INFO    : FastAPI started
frigate  | 2025-03-30 12:56:16.253717795  [2025-03-30 12:56:16] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
frigate  | 2025-03-30 12:56:16.258647695  Process detector:tensorrt:
frigate  | 2025-03-30 12:56:16.258650200  Traceback (most recent call last):
frigate  | 2025-03-30 12:56:16.258651212    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  | 2025-03-30 12:56:16.258651933      self.run()
frigate  | 2025-03-30 12:56:16.258652664    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2025-03-30 12:56:16.258654448      return run(*args, **kwargs)
frigate  | 2025-03-30 12:56:16.258670057    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  | 2025-03-30 12:56:16.258670849      self._target(*self._args, **self._kwargs)
frigate  | 2025-03-30 12:56:16.258672111    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
frigate  | 2025-03-30 12:56:16.258672893      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2025-03-30 12:56:16.258673614    File "/opt/frigate/frigate/object_detection.py", line 68, in __init__
frigate  | 2025-03-30 12:56:16.258674265      self.detect_api = create_detector(detector_config)
frigate  | 2025-03-30 12:56:16.258692600    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2025-03-30 12:56:16.258693331      return api(detector_config)
frigate  | 2025-03-30 12:56:16.258710965    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 244, in __init__
frigate  | 2025-03-30 12:56:16.258711756      self.input_shape = self._get_input_shape()
frigate  | 2025-03-30 12:56:16.258712548    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 118, in _get_input_shape
frigate  | 2025-03-30 12:56:16.258713079      binding = self.engine[0]
frigate  | 2025-03-30 12:56:16.258713690  TypeError: 'NoneType' object is not subscriptable
frigate  | 2025-03-30 12:56:16.258714421  Exception ignored in: <function TensorRtDetector.__del__ at 0x7103b46c7ca0>
frigate  | 2025-03-30 12:56:16.258715093  Traceback (most recent call last):
frigate  | 2025-03-30 12:56:16.258715774    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 262, in __del__
frigate  | 2025-03-30 12:56:16.258729530      if self.outputs is not None:
frigate  | 2025-03-30 12:56:16.258730362  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate  | 2025-03-30 12:56:21.188134700  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-03-30 12:56:30.949690797  [2025-03-30 12:56:30] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for livingroom. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a67be9ba-0a30-4589-891b-8da15278e1ad)
