### DISCUSSION TITLE
How to enable/open port 5000?

### DISCUSSION THREAD

**Discussion by Hubcraft101** [blakeblackshear/frigate#17466] [Ask A Question] [answered]
Not sure how to get port 5000 to listen/work. In ubuntu when I do a netstat -l it doesnt show port 5000 listening like the other ports that work. In my docker file I've got the mapping "5000:5000" just like for the other ports that work. I've rebooted a few times. Not sure what else is needed.

**Comment by hawkeye217** [comment]
What is your full docker compose file?

**Reply by Hubcraft101** [reply]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    stop_grace_period: 30s
    image: [ghcr.io/blakeblackshear/frigate:stable](http://ghcr.io/blakeblackshear/frigate:stable)
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # unauthenticated
      - "8971:8971"
      - "8554:8554" # RTSP feeds
    shm_size: '128mb'
```
