### DISCUSSION TITLE
Recording Error when adding Reolink NVR camera to frigate

### DISCUSSION THREAD

**Discussion by rpuserh** [blakeblackshear/frigate#17475] [General]
I added one camera from Reolink NVR(channel7) to frigate, Now I see camera live and screenshots for events, but when I try to play video it fails. Looks like it's not recording video.

Here is my config 
```
logger:
  logs:
    frigate.record.maintainer: debug
mqtt:
  enabled: false
go2rtc:
  streams:
    reolink_cam7:
      - "ffmpeg:http://192.168.8.200/flv?port=1935&app=bcs&stream=channel7_main.bcs&user=admin&password=MyPassNoSpecialChar#video=copy#audio=copy#audio=opus"
    reolink_cam7_sub:
      - "ffmpeg:http://192.168.8.200/flv?port=1935&app=bcs&stream=channel7_ext.bcs&user=admin&password=MyPassNoSpecialChar"
cameras:
  GarageFrontPano:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_cam7
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_cam7_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 1536 # this is panoramic camera I got this number from substreem resolution
      height: 432
      fps: 5
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - bus
        - bird
        - cat
        - dog
    record:
      enabled: True
      retain:
        days: 0
      alerts:
        retain:
          days: 90
          mode: motion
      detections:
        retain:
          days: 90
          mode: motion
auth:
  enabled: false
version: 0.15-1
```

Here is error I see 
```
frigate    | 2025-03-31 21:22:39.854303118  [2025-03-31 21:22:39] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:22:39.854307629  [2025-03-31 21:22:39] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:22:39.854309760  [2025-03-31 21:22:39] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:22:49.863007742  [2025-03-31 21:22:49] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:22:49.863126425  [2025-03-31 21:22:49] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:22:49.863129353  [2025-03-31 21:22:49] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:22:59.886299158  [2025-03-31 21:22:59] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:22:59.886350465  [2025-03-31 21:22:59] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:22:59.886432450  [2025-03-31 21:22:59] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:23:06.608889579  127.0.0.1 - - [31/Mar/2025:21:23:06 +0000] "" 400 0 "-" "-" "-"
frigate    | 2025-03-31 21:23:07.692436345  21:23:07.692 ERR [exec] timeout url="exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.8.200/flv?port=1935&app=bcs&stream=channel7_main.bcs&user=admin&password=MyPassNoSpecialChar -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9e19a5d7a6858baac95d6520ceeedc77"
frigate    | 2025-03-31 21:23:07.693133930  21:23:07.692 WRN [rtsp] error="streams: timeout" stream=reolink_cam7
frigate    | 2025-03-31 21:23:07.693137389  21:23:07.692 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225 > error="write tcp 127.0.0.1:8554->127.0.0.1:53316: write: broken pipe"
frigate    | 2025-03-31 21:23:09.894722463  [2025-03-31 21:23:09] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:23:09.894835090  [2025-03-31 21:23:09] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:23:09.894838234  [2025-03-31 21:23:09] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:23:19.927793678  [2025-03-31 21:23:19] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:23:19.927799040  [2025-03-31 21:23:19] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:23:19.927801492  [2025-03-31 21:23:19] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:23:29.933636905  [2025-03-31 21:23:29] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:23:29.933640738  [2025-03-31 21:23:29] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:23:29.933642205  [2025-03-31 21:23:29] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:23:39.955666341  [2025-03-31 21:23:39] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:23:39.955670939  [2025-03-31 21:23:39] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:23:39.955673019  [2025-03-31 21:23:39] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:23:49.970833285  [2025-03-31 21:23:49] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:23:49.970882479  [2025-03-31 21:23:49] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:23:49.970963578  [2025-03-31 21:23:49] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:23:59.985284449  [2025-03-31 21:23:59] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:23:59.985628550  [2025-03-31 21:23:59] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:23:59.985631536  [2025-03-31 21:23:59] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:24:06.639756034  127.0.0.1 - - [31/Mar/2025:21:24:06 +0000] "" 400 0 "-" "-" "-"
frigate    | 2025-03-31 21:24:07.695460079  21:24:07.695 ERR [exec] timeout url="exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.8.200/flv?port=1935&app=bcs&stream=channel7_main.bcs&user=admin&password=MyPassNoSpecialChar -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/9e19a5d7a6858baac95d6520ceeedc77"
frigate    | 2025-03-31 21:24:07.695464490  21:24:07.695 WRN [rtsp] error="streams: timeout" stream=reolink_cam7
frigate    | 2025-03-31 21:24:07.696287258  21:24:07.696 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225 > error="write tcp 127.0.0.1:8554->127.0.0.1:55952: write: broken pipe"
frigate    | 2025-03-31 21:24:10.003740712  [2025-03-31 21:24:09] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:24:10.003743939  [2025-03-31 21:24:09] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:24:10.003745360  [2025-03-31 21:24:09] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:24:20.019197930  [2025-03-31 21:24:20] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:24:20.019268654  [2025-03-31 21:24:20] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:24:20.019289325  [2025-03-31 21:24:20] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:24:30.036357953  [2025-03-31 21:24:30] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:24:30.036678874  [2025-03-31 21:24:30] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-03-31 21:24:30.036681750  [2025-03-31 21:24:30] watchdog.GarageFrontPano       INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-03-31 21:24:40.058912329  [2025-03-31 21:24:40] watchdog.GarageFrontPano       ERROR   : No new recording segments were created for GarageFrontPano in the last 120s. restarting the ffmpeg record process...
frigate    | 2025-03-31 21:24:40.058918450  [2025-03-31 21:24:40] watchdog.GarageFrontPano       INFO    : Terminating the existing ffmpeg process...
```

unable to find reason, any thoughts ?
