### DISCUSSION TITLE
[Support]: Frigate Proxy Map doesn't include X-Auth-Request-* headers

### DISCUSSION THREAD

**Discussion by warrenrees** [blakeblackshear/frigate#17480] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I'm in the process of setting up Frigate to leverage my keycloak / oauth2 proxy, however by default frigate doesn't whitelist the proper X-Auth-Request-* headers in the /usr/local/nginx/conf/proxy_trusted_headers.conf for this to work out of the box.

Can you please add the following lines to the proxy_trusted_headers.conf file prior to next release?

proxy_set_header X-Auth-Request-User $http_x_auth_request_user;
proxy_set_header X-Auth-Request-Groups $http_x_auth_request_groups;
proxy_set_header X-Auth-Request-Email $http_x_auth_request_email;
proxy_set_header X-Auth-Request-Preferred-Username $http_x_auth_request_preferred_username;

### Steps to reproduce

1. Install keycloak & oauth2-proxy
2. Setup ingress to leverage keycloak for authorizaztion
3. Check headers by going to https://{oauth_endpoint}/oauth2/auth

Request URL:
https://auth.rees.ca/oauth2/auth
Request Method:
GET
Status Code:
202 Accepted
Remote Address:
10.0.0.240:443
Referrer Policy:
strict-origin-when-cross-origin
content-length:
0
date:
Tue, 01 Apr 2025 06:21:11 GMT
gap-auth:
warren@rees.ca

strict-transport-security:
max-age=31536000; includeSubDomains
x-auth-request-email:
warren@rees.ca
x-auth-request-groups:
k8s-admin,ombi,create-realm,default-roles-master,offline_access,admin,uma_authorization
x-auth-request-preferred-username:
wrees
x-auth-request-user:
d8deb6ee-839e-4caa-9717-2711b8b7b003

...

### Version

0.15.0-cea210d

### Frigate config file

```yaml
auth:
  enabled: false
proxy:
  header_map:
    user: X-Auth-Request-Preferred-Username
```

### docker-compose file or Docker CLI command

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Preferred-Username, X-Auth-Request-Groups"
    nginx.ingress.kubernetes.io/auth-signin: https://auth.rees.ca/oauth2/start?rd=$scheme://$best_http_host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.rees.ca/oauth2/auth
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.org/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600"
    nginx.org/websocket-services: frigate
  labels:
    app.kubernetes.io/name: frigate
  name: frigate
  namespace: default
spec:
  rules:
  - host: frigate.rees.ca
    http:
      paths:
      - backend:
          service:
            name: frigate-tcp
            port:
              number: 8971
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - frigate.rees.ca
    secretName: frigate-tls
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.240
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

n/a
