### DISCUSSION TITLE
[Support]: exec /init: exec format error on trying to deploy 15.0 on my raspi4

### DISCUSSION THREAD

**Discussion by OldGuyDevGithub** [blakeblackshear/frigate#17482] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I run my frigate on a raspi4 4GB in a complete aarch64 architecture.

This has been working fine for the last 2 years including frigate 0.14.1 

I tried serveral times to upgrade to 0.15.0 but all I get is 

`exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error` 

I tried different approaches with directly pulling the arm64 image or deploying the cotainer directly from console.

All I get is "exec /init: exec format error"

Anybody else experiencing this issue ?

thx

### Steps to reproduce

1. have a aarch64 raspi4 with docker 
2. try to deploy a 0.15.0 frigate container

### Version

0.15.0 release

### Frigate config file

```yaml
default config file
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate_test
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #image: ghcr.io/blakeblackshear/frigate:0.15.0-rc1-standard-arm64
    image: ghcr.io/blakeblackshear/frigate:0.15.0-standard-arm64
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /var/lib/docker/volumes/frigate/_data/config/config.yml:/config/config.yml
      #- /var/lib/docker/volumes/frigate/_data/media:/media/frigate
      #- /var/lib/docker/volumes/frigate/_data/db:/db

      - frigate:/config/config.yml
      - frigate:/media/frigate
      - frigate:/db:/db

      #- /mnt/ssd/volumes/frigate/_data/config/config.yml:/config/config.yml
      #- /mnt/ssd/docker/volumes/frigate/_data/media:/media/frigate
      #- /mnt/ssd/docker/volumes/frigate/_data/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXX"
      PLUS_API_KEY: "XXXXXX"
volumes:
  frigate:
```

### Relevant Frigate log output

```shell
Actions

      

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error

exec /init: exec format error
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

multiple

### Screenshots of the Frigate UI's System metrics pages

I wish I would get this far
