### DISCUSSION TITLE
[Camera Support]: Reolink FE-P Quad View

### DISCUSSION THREAD

**Discussion by broyuken** [blakeblackshear/frigate#17506] [Camera Support]
### Describe the problem you are having

I am trying to figure out how to get 4 streams out of the Reolink FE-P 360 camera. I would like to be able to have 4 different streams similar to how the Reolink app is set up. 

### Version

0.15.0-cea210d

### What browser(s) are you using?

Google Chrome 134.0.6998.178

### Frigate config file

```yaml
mqtt:
  host: 10.x.x.x
  user: homeassistant
  password: mqttpassword


detectors:
  coral:
    type: edgetpu
    device: usb


go2rtc:
  streams:
    frigate_garage_360:
      - rtsp://admin:camerapassword@10.x.x.35/Preview_01_main
      - ffmpeg:frigate_spare_camera#audio=aac


objects:
  track:
    - person
    - dog


snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  height: 1080
  quality: 100
  retain:
    default: 30


live:
  height: 1080
  quality: 8


record:
  enabled: true
  retain:
    days: 90
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30


cameras:
  frigate_garage_360: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_garage_360 # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
#        - path: rtsp://admin:camerapassword@10.x.x.35/Preview_01_sub # <----- The stream you want to use for detection
#          input_args: preset-rtsp-restream-low-latency
#          roles:
#            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1024
      height: 1024
      fps: 5
    mqtt:
      timestamp: false
    objects:
      track:
        - person
        - dog
        - car
        - bicycle


version: 0.15-1
camera_groups:
  Birdseye:
    order: 2
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
No errors, camera just doesn't de-fisheye

I have also tried with 
ffmpeg -i rtsp://admin:camerapassword@10.x.x.35/Preview_01_main -vf "v360=fisheye:equirect:id_fov=360"

but that doesn't change anything.
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink FE-P

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-04-02 103138](https://github.com/user-attachments/assets/4155dd18-5fe8-468d-884d-3a4c4347c744)
![Screenshot 2025-04-02 103151](https://github.com/user-attachments/assets/413a6c0d-d846-4521-b122-52883478a989)

### Any other information that may be helpful

View in Reolink App:

View in Frigate:
![image](https://github.com/user-attachments/assets/4391b583-118a-4d64-9aba-3f5714ce8d04)

**Comment by hawkeye217** [comment]
If there are 4 streams available from the camera, you can just use those directly in go2rtc. 

For correcting fisheye, see this discussion: https://github.com/blakeblackshear/frigate/discussions/17013

**Comment by broyuken** [comment]
There’s only a main and a sub stream from the camera. They are both fish eye 360 degree views. I was hoping to split this one view into 4 dewarped streams likely using restreams and some ffmpeg magic. But so far I haven’t had any luck.

**Reply by NickM-27** [reply]
that is going to be very difficult to do without connecting to the camera 4 times, which it likely won't be able to handle. https://www.reddit.com/r/reolinkcam/comments/17i9xtc/comment/k7kra2r/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button looks like it may be related though

**Reply by hawkeye217** [reply]
You'd have to use go2rtc for that, and you'd have to re-encode, which will use a large amount of CPU. I don't recall any user ever having split apart a stream like that before.

**Comment by broyuken** [comment]
I was looking at that thread but when I put the configs from it in my frigate it errors and doesn’t load. But it works when I manually run the ffmpeg commands.

**Reply by hawkeye217** [reply]
We'll need to see your config and logs in order to be able to help.

**Reply by broyuken** [reply]
My config is here.
```
mqtt:
  host: 10.x.x.138
  user: homeassistant
  password: mqttpassword


detectors:
  coral:
    type: edgetpu
    device: usb


go2rtc:
  streams:
    frigate_garage_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:camerapassword@10.x.x.33/main
      - ffmpeg:frigate_garage_camera#audio=aac
    frigate_office_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:camerapassword@10.x.x.12/main
      - ffmpeg:frigate_office_camera#audio=aac
    frigate_basement_back_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:camerapassword@10.x.x.13/main
      - ffmpeg:frigate_basement_back_camera#audio=aac
    frigate_basement_playroom_camera:
      - rtsp://user:camerapassword@10.x.x.10:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:frigate_basement_playroom_camera#audio=aac
    frigate_spare_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:camerapassword@10.x.x.11/main
      - ffmpeg:frigate_spare_camera#audio=aac
    frigate_garage_360:
      - ffmpeg -i rtsp://admin:camerapassword@10.x.x.35/Preview_01_main -vf v360=fisheye:flat:id_fov=180:d_fov=90:roll=0:pitch=30:rorder=rpy
      - ffmpeg:frigate_spare_camera#audio=aac


objects:
  track:
    - person
    - dog


snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  height: 1080
  quality: 100
  retain:
    default: 30


live:
  height: 1080
  quality: 8


record:
  enabled: true
  retain:
    days: 90
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30


cameras:
  frigate_garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_garage_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:camerapassword@10.x.x.33/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.793,0.204,0.789,0.205,0.833,0,0.834
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: false
    objects:
      track:
        - person
        - dog
        - car
        - bicycle


  frigate_office_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_office_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:camerapassword@10.x.x.12/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      filters:
        person:
          mask:
            - 0.786,0.061,0.936,0.11,0.928,0.305,0.784,0.241
            - 0.52,0.502,0.617,0.555,0.631,0.038,0.525,0.037
            - 0.121,0.775,0.327,0.617,0.311,0.039,0.063,0.114,0.078,0.483
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.794,0.204,0.79,0.206,0.831,0,0.832
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: false
    zones:
      Desk:
        coordinates: 0.686,0.877,0.94,1,1,0.308,1,0,0.776,0
        loitering_time: 30
        objects: person
        inertia: 3


  frigate_basement_back_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_basement_back_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:camerapassword@10.x.x.13/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.791,0.205,0.791,0.205,0.833,0,0.833
      lightning_threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: false


  frigate_basement_playroom_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_basement_playroom_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user:camerapassword@10.x.x.10:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.664,0.036,0.973,0.037,0.972,0.075,0.664,0.078
      lightning_threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704
      height: 480
      fps: 5
    mqtt:
      timestamp: false


  frigate_spare_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_spare_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:camerapassword@10.x.x.11/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      lightning_threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
    mqtt:
      timestamp: false


  frigate_garage_360: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_garage_360 # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
#        - path: rtsp://admin:camerapassword@10.x.x.35/Preview_01_sub # <----- The stream you want to use for detection
#          input_args: preset-rtsp-restream-low-latency
#          roles:
#            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1024
      height: 1024
      fps: 5
    mqtt:
      timestamp: false
    objects:
      track:
        - person
        - dog
        - car
        - bicycle

version: 0.15-1
camera_groups:
  Inside_Cameras:
    order: 1
    icon: LuCamera
    cameras:
      - frigate_basement_front_camera
      - frigate_office_camera
      - frigate_basement_playroom_camera
      - frigate_basement_back_camera
  Birdseye:
    order: 2
    icon: LuBird
    cameras: birdseye

```

and my logs are here
[frigate-logs.txt](https://github.com/user-attachments/files/19572959/frigate-logs.txt)

**Reply by hawkeye217** [reply]
You've not formatted the stream correctly in your go2rtc config.

```
   frigate_garage_360:
      - ffmpeg:rtsp://admin:camerapassword@10.x.x.35/Preview_01_main#video=h264#audio=copy#raw=-vf "lenscorrection=k1=-0.450:k2=0.1"
```

I've used `lenscorrection` here at the end as the other thread did, but you can try the other filters if you want. The first part of your string was formatted incorrectly.

**Reply by broyuken** [reply]
That seems to have made it work however my cpu is getting pegged, and the stream keeps crashing out on me. I'm starting to get the hint that this camera might not be the best for what I'm looking for and will probably be going back. I just want a camera with a 180 fov that I can mount in the middle of the back wall of my garage and see left where my workbench is, as well as right where the door into the house is.

**Reply by hawkeye217** [reply]
Yes, the CPU usage will be much higher because you have to re-encode the stream after dewarping. You could try adding `#hardware` after `#video=h264` to use hardware acceleration.

**Reply by broyuken** [reply]
As soon as I did that, it went back to the fisheye view.

**Reply by hawkeye217** [reply]
DId you add it after `#video=264` like this?
```
   frigate_garage_360:
      - ffmpeg:rtsp://admin:camerapassword@10.x.x.35/Preview_01_main#video=h264#hardware#audio=copy#raw=-vf "lenscorrection=k1=-0.450:k2=0.1"
```

If so, what do your go2rtc logs show?

You may need to enable trace logs:

```
go2rtc:
  log:
    exec: trace
  ...
```
