### DISCUSSION TITLE
[Bug]: cache fills up when notifications can't be delivered

### DISCUSSION THREAD

**Discussion by piv3rt** [blakeblackshear/frigate#17503] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When notifications are enabled but Frigate can't access the internet and an event is detected (such as a human passing by), the `/tmp/cache` tmpfs fills up with `.mp4` files which prevents Frigate from operating.
It looks like failure to send notifications prevents Frigate from flushing cache files.
Live views even stop working before the cache is full and display the following message: "No frames have been received, check error logs"
Web UI metrics don't show the cache filing up. Only `df -h` on the OS shows the real space being used.

### Steps to reproduce

1. Inside Frigate's web UI : Settings > Notifications > Enable notifications
2. Restart Frigate
3. Open a shell on the Frigate server
4. `watch ls -l /tmp/cache` and observe cache files being created and flushed
5. Prevent Frigate from accessing the internet (with a firewall for example, or by unplugging your internet gateway)
6. Stand in front of one of the cameras so Frigate detects a human
7. `watch ls -l /tmp/cache` and observe cache files piling up, until the tmpfs is full and Frigate can't operate anymore

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.123.123
  user: frigate
  password: xxxxxxxx

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
go2rtc:
  streams:
    room1:
      - rtsp://viewer:xxxxxxxx@192.168.123.124:554/Streaming/channels/101

detect:
  fps: 6

snapshots:
  enabled: true
  crop: true

cameras:
  room1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/room1
          roles:
            - record
        - path: rtsp://viewer:xxxxxxxx@192.168.123.124:554/Streaming/channels/102
          roles:
            - detect

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config:/config
      - /home/frigate/storage:/media/frigate
      - /home/frigate/certs:/etc/letsencrypt/live/frigate:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "443:8971"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxxx"
```

### Relevant Frigate log output

```shell
frigate  | 2025-04-02 15:24:27.175839196  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [segment @ 0x5560316d2300] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | 2025-04-02 15:24:27.175855347  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [aost#0:1/copy @ 0x556031a4a500] Error submitting a packet to the muxer: No space left on device
frigate  | 2025-04-02 15:24:27.175928810  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   :     Last message repeated 1 times
frigate  | 2025-04-02 15:24:27.177025425  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [out#0/segment @ 0x5560316e3840] Error muxing a packet
frigate  | 2025-04-02 15:24:27.177154378  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [out#0/segment @ 0x5560316e3840] Task finished with error code: -28 (No space left on device)
frigate  | 2025-04-02 15:24:27.177427679  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [out#0/segment @ 0x5560316e3840] Terminating thread with return code -28 (No space left on device)
frigate  | 2025-04-02 15:24:27.177434734  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [segment @ 0x5560316d2300] Failure occurred when ending segment '/tmp/cache/room1@20250402152417+0200.mp4'
frigate  | 2025-04-02 15:24:27.177912104  [2025-04-02 15:24:27] ffmpeg.room1.record           ERROR   : [out#0/segment @ 0x5560316e3840] Error writing trailer: No space left on device
frigate  | 2025-04-02 15:24:27.177917963  [2025-04-02 15:24:27] watchdog.room1                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-04-02 15:24:27.177920821  [2025-04-02 15:24:27] watchdog.room1                INFO    : Waiting for ffmpeg to exit gracefully...
```

### Relevant go2rtc log output

```shell
info | 2025-04-02 15:07:13 | startup | Preparing new go2rtc config...
info | 2025-04-02 15:07:13 | startup | Starting go2rtc...
info | 2025-04-02 15:07:13 | startup | go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info | 2025-04-02 15:07:13 | startup | config path=/dev/shm/go2rtc.yaml
info | 2025-04-02 15:07:13 | api     | listen addr=:1984
info | 2025-04-02 15:07:13 | rtsp    | listen addr=:8554
info | 2025-04-02 15:07:13 | webrtc  | listen addr=:8555/tcp
info | 2025-04-02 15:07:23 | startup | Starting go2rtc healthcheck service...
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

-
