### DISCUSSION TITLE
[Detector Support]: Is 43 ms inference speed expected for yolonas_s on RK3588

### DISCUSSION THREAD

**Discussion by lightingghost** [blakeblackshear/frigate#17508] [Detector Support] [answered]
### Describe the problem you are having

I am running Frigate on RK3588 (3 NPU, 2TOPS each). And my config is attached below.

According to the[ document](https://docs.frigate.video/frigate/hardware/)

> The inference time of a rk3588 with all 3 cores enabled is typically 25-30 ms for yolo-nas s.

However, I am seeing a consistent 40+ ms reported for RKNN, even though the utilization is low:

Is there anything I am doing wrong? Any help will be appreciated

### Version

 0.15.0-cea210d

### Frigate config file

```yaml
detectors:
  rknn:
    type: rknn # required
    # core mask for npu
    core_mask: 0b111

model:
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - backpack

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects

cameras:
  backyard: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/backyard_1280_720
          roles:
            - detect
        - path: rtsp://localhost:8554/backyard_3200_1800
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720

    motion:
      mask:
        - 0.099,0.462,0.124,0.535,0.167,0.535,0.212,0.447,0.201,0.405,0.138,0.379
        - 0.224,0.357,0.21,0.416,0.249,0.43,0.268,0.371
        - 0.37,0.364,0.358,0.416,0.405,0.423,0.505,0.386,0.479,0.333,0.411,0.34
        - 0.6,0.328,0.562,0.399,0.594,0.433,0.642,0.431,0.67,0.43,0.69,0.394,0.686,0.335,0.649,0.315
        - 0.801,0.323,0.766,0.396,0.804,0.43,0.856,0.44,0.894,0.423,0.878,0.342,0.841,0.313
        - 0.025,0.048,0.023,0.101,0.272,0.103,0.271,0.048
        - 0.828,0.889,0.828,0.938,0.933,0.938,0.934,0.889
      threshold: 30
      contour_area: 20
      improve_contrast: true
      lightning_threshold: 0.8
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev/dri/renderD129:/dev/dri/renderD129
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

RKNN

### Screenshots of the Frigate UI's System metrics pages

<img width="1530" alt="image" src="https://github.com/user-attachments/assets/e1f8a539-13fb-4133-868b-ce1be6d973cc" />
