### DISCUSSION TITLE
[Detector Support]: How to log image patches sent to objection detection models for debug purpose?

### DISCUSSION THREAD

**Discussion by lightingghost** [blakeblackshear/frigate#17510] [Detector Support] [answered]
### Describe the problem you are having

I have both motion detection and object detection enabled. I can see in the recording that a cat appeared in the frame, but object detection did not identify it. I would like to understand if it is a problem on motion detection (incorrect patch) or object detection (wrong model prediction).

IMHO, logging image patches sent to objection detection models will be a way to solve the problem, but I could not find ways to do that. I would appreciate other advices as well.

### Version

 0.15.0-cea210d

### Frigate config file

```yaml
detectors:
  rknn:
    type: rknn # required
    # core mask for npu
    core_mask: 0b111

model:
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - backpack
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
N/A
```

### Install method

Docker Compose

### Object Detector

RKNN

### Screenshots of the Frigate UI's System metrics pages

N/A
