### DISCUSSION TITLE
Suitable hardware for frigate with hailo

### DISCUSSION THREAD

**Discussion by tomaae** [blakeblackshear/frigate#17516] [Ask A Question] [answered]
Hello,
I'm currently using rpi5 with hailo8l, but rpi5 is not suitable for frigate because its lacking hardware acceleration for video encoding.
Did anyone found better alternative to rpi5 which supports m.2 pcie3.0 2 lane?

**Comment by SkeLLLa** [comment, marked as answer]
Frigate doesn't require "encoding", it's not mandatory. The camera encodes the stream and frigate can consume it as-is. Hailo is powerful enough to consume even 4k stream.

If encoding is mandatory in your case any "minipc" with low power CPU could make a trick. However, check the specs, since processors like n1XX, n2XX, n3XX have limited PCI lanes (8 in total), so there should be not more than 4 m.2 slots.

**Reply by tomaae** [reply]
I dont think I can disable encoding. I have most of featured disabled, like record, but each camera still uses ~35% cpu for ffmpeg. Detect and motion have to be enabled for object detection.

I was thinking more of an arm device.
I was looking at hardkernel h4 which has 4x slot, but adding everything on top of that will be bit pricy.

**Reply by SkeLLLa** [reply]
I think it's not "encoding" but decoding which has [official support](https://docs.frigate.video/configuration/hardware_acceleration/#raspberry-pi-34) on PIs. Frigate still needs to get I-frames from stream in order to send it for detection. CPU usage maybe also caused due to timecodes overlay.

So if you can share your sample config, it might help all other to figure out what could be optimized.

**Reply by SkeLLLa** [reply]
Also if your cameras encode stream in H265, it takes more CPU even with hardware acceleration to process it. So changing the codec to H264 may help as well.

**Reply by tomaae** [reply]
Sure, here is my frigate config:
```
mqtt:
  host: 10.0.1.7
  topic_prefix: frigate-hamster
  client_id: frigate-hamster
  user: ***
  password: ***

cameras:
  dahua1:
    ffmpeg:
      inputs:
        - path: rtsp://***@10.0.1.60:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect

    zones:
      Sandbox:
        coordinates: 
          0.54,0.131,0.529,0.213,0.525,0.374,0.605,0.376,0.611,0.267,0.642,0.229,0.638,0.112
        inertia: 2
        loitering_time: 0
      Water:
        coordinates: 0.727,0.276,0.73,0.4,0.802,0.426,0.807,0.255
        inertia: 2
        loitering_time: 0
      Wheel:
        coordinates: 0.307,0.037,0.422,0.029,0.424,0.205,0.281,0.22
        inertia: 2
        loitering_time: 0
      Bowl:
        coordinates: 0.803,1,0.796,0.82,0.703,0.854,0.677,1
        loitering_time: 0

        inertia: 3
  dahua2:
    ffmpeg:
      inputs:
        - path: rtsp://***@10.0.1.61:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect

    zones:
      Hideout:
        coordinates: 0,0.052,0.659,0.07,0.654,0.861,0.988,0.866,0.989,0.993,0.004,0.998
        loitering_time: 0

  # dahua3:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://***@10.0.1.62:554/cam/realmonitor?channel=1&subtype=0
  #         roles:
  #           - detect


  # dahua4:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://***@10.0.1.63:554/cam/realmonitor?channel=1&subtype=0
  #         roles:
  #           - detect


detect:
  width: 1280
  height: 780
  fps: 10
  enabled: true

record:
  enabled: false

motion:
  enabled: true
  threshold: 35
  contour_area: 15
  improve_contrast: 'true'

objects:
  track:
    - hamster
  filters:
    hamster:
      min_score: 0.5
      threshold: 0.5

detectors:
  hailo8l:
    type: hailo8l
    device: PCIe

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: bgr
  model_type: yolox
  path: /config/model_cache/yolov8s_hamster.hef
  labelmap:
    0: hamster

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

version: 0.15-1
```

All my cameras use h264, their config:
cam1: 
![image](https://github.com/user-attachments/assets/07f3faf2-291f-4ebe-8cad-06fd3e213ddd)
cam2-4(only cam2 is enabled in frigate due to cpu usage): 
![image](https://github.com/user-attachments/assets/572c5bab-2007-49e9-abd5-8148b70410c1)

ffmpeg processes:
```
root      405716 39.1  2.3 810944 98384 ?        Ssl  04:55 205:03 /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://***@10.0.1.60:554/cam/realmonitor?channel=1&subtype=0 -r 10 -vf fps=10,scale=1280:780 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root     1615248 36.2  1.5 805904 62784 ?        Ssl  13:35   1:23 /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 h264_v4l2m2m -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://***@10.0.1.61:554/cam/realmonitor?channel=1&subtype=0 -r 10 -vf fps=10,scale=1280:780 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
````
