### DISCUSSION TITLE
Help with Package detection / HA Integration

### DISCUSSION THREAD

**Discussion by AdmiralRaccoon** [blakeblackshear/frigate#17515] [Config Support]
### Describe the problem you are having

Good Morning,

1.) I´m struggeling witha package detection, as I want to be informed by Home Assistant if a package arrives and how many of them (if possible). Clearly this is eome config issue of mine:

A test package is successfully detected all the time:

![image](https://github.com/user-attachments/assets/cd736f95-268b-4c90-afbd-5dd2b5985966)

but why are the HA Sensors at 0 ?

![image](https://github.com/user-attachments/assets/c491a274-50f1-468b-b200-61f63561cc4d)

2.) Although Snapshots are enabled, I can´t see them in the review, and though not able to send them to Frigate+ for training:

![image](https://github.com/user-attachments/assets/fd6a898b-0abf-425a-b6a8-9cb7d5d23e3e)

Thanks for some (config) hints and a nice day
Philipp

### Version

0.15.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.99
  user: ******
  password: ******

#birdseye:
#  enabled: True
#  mode: objects

go2rtc:
  streams:
    cam_carport_neu:
      - rtsp://****:****T@192.168.1.86:554/stream1

genai:
  enabled: false
  provider: gemini
  api_key: *****
  model: gemini-1.5-flash

cameras:
  cam_carport_neu:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://****:****@192.168.1.86:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - package
        - face
        - cat
        - dog
      filters:
        package:
          min_area: 0
          min_ratio: 0
          max_ratio: 1000
          min_score: 0
          threshold: 0.2
        dog:
          mask:
            - 0.47,0.287,0.481,0.004,0.997,0.001,0.997,0.816,0.758,0.564,0.467,0.336
            - 0,0.545,0.221,0.459,0.346,0.997,0.003,0.999
        cat:
          mask:
            - 0.47,0.287,0.481,0.004,0.997,0.001,0.997,0.816,0.758,0.564,0.467,0.336
            - 0,0.545,0.221,0.459,0.346,0.997,0.003,0.999          
      mask: 0,0.545,0.221,0.459,0.346,0.997,0.003,0.999
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          package: 30
    genai:
      enabled: false
    review:
      alerts:
        labels:
          - package
          - cat
          - dog
        required_zones: carport_post
      detections:
        required_zones: carport_post
        labels:
          - package
          - cat
          - dog
    motion:
      threshold: 10
      contour_area: 10
      improve_contrast: true
    zones:
      carport_post:
        coordinates: 0.238,0.506,0.31,0.786,0.443,0.973,0.738,0.656,0.471,0.416
        loitering_time: 0
        objects: package
        
detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://****

version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### Relevant Frigate log output

```shell
not neccessary
```

### Relevant go2rtc log output

```shell
not neccessary
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
    frigate:
      container_name: frigate
      image: ghcr.io/blakeblackshear/frigate:stable
      restart: always
      shm_size: "512mb"
      privileged: true
      devices:
        - /dev/bus/usb/002:/dev/bus/usb/002
        - /dev/dri/renderD128 # for intel hwaccel
      volumes:
        - /etc/localtime:/etc/localtime
        - /root/frigate:/config:rw
        - /root/frigate/clips:/media/frigate/clips:rw
        - /root/frigate/recordings:/media/frigate/recordings:rw
      ports:
        - 5000:5000
        - 1935:1935
      environment:
        #FRIGATE_RTSP_PASSWORD: "frigate" 
        - PLUS_API_KEY=*************************************************************
```

### Object Detector

Coral
