### DISCUSSION TITLE
How do I enable continous recordings via HA?

### DISCUSSION THREAD

**Discussion by mkryszto-kr** [blakeblackshear/frigate#17548] [Ask A Question] [answered]
I have a record config defined for a particular camera as follows (btw this is taken from the docs [here](https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean)):
```
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects
```
This works fine, but during some critical hours, I just want continuous recordings and to record everything regardless of whether motion was detected or not. According to the [docs](https://docs.frigate.video/configuration/record/#can-i-have-continuous-recordings-but-only-at-certain-times) this should be possible via HA integration.

> Can I have "continuous" recordings, but only at certain times?
> 
> Using Frigate UI, HomeAssistant, or MQTT, cameras can be automated to only record in certain situations or at certain times.

I checked HA integration, but it seems I can only completely switch off recordings for a particular camera. So either nothing at all gets recorded, or it gets recorded according to what is already defined in the config. I cannot figure out how to turn on/off continuous recordings, as mentioned in the docs. What am I missing?
