### DISCUSSION TITLE
How can I limit notifications

### DISCUSSION THREAD

**Discussion by niclas3332** [blakeblackshear/frigate#17540] [Ask A Question]
How can I limit the notifications, like only one per hour?
The camera (eufy) is at the front door and today I was standing there and I received 6 notifications for just standing there.

Thats my config, maybe I did something wrong:

```yaml
mqtt:
  enabled: true
  user: niclas
  password: pw
  host: 192.168.178.114
  stats_interval: 30
  port: 1883

semantic_search:
  enabled: false
  model_size: large





  reindex: false
ffmpeg:
  hwaccel_args: preset-nvidia-h265
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac


audio: # <- enable audio events for all camera
  enabled: true
go2rtc:
  streams:

    rtsp_cam:
      - rtsp://192.168.178.207/live0 # <- stream which supports video & aac audio.
      - ffmpeg:rtsp_cam#audio=opus#hardware   # <- copy of the stream which transcodes audio to opus
    rlc_main:
      - rtsp://admin:pw@192.168.178.64/Preview_01_main # <- stream which supports video & aac audio.
      - ffmpeg:rlc_main#audio=opus#hardware   # <- copy of the stream which transcodes audio to opus
    rlc_sub:
      - rtsp://admin:pw@192.168.178.64/Preview_01_sub # <- stream which supports video & aac audio.
      - ffmpeg:rlc_sub#audio=opus#hardware   # <- copy of the stream which transcodes audio to opus

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog

  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (d
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.8

cameras:
  garten_main:
    genai:
      enabled: false
    live:
      stream_name: rlc_main
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rlc_main
          roles:
            - detect
            - record
        - path: rtsp://127.0.0.1:8554/rlc_sub
          roles:
            - audio
    onvif:
      host: 192.168.178.64
      port: 8000
      user: admin
      password: pw
    record:
      # Optional: Enable recording (default: shown below)
      # WARNING: If recording is disabled in the config, turning it on via
      #          the UI or MQTT later will have no effect.
      enabled: true
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 14
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 14
        pre_capture: 10
        post_capture: 10
    zones:
      front:
        coordinates: 0.414,0.478,0.461,0.979,0.905,0.99,0.888,0.418

      Back:
        coordinates: 0.401,0.543,0.428,0.933,0.059,0.938,0.043,0.6
        loitering_time: 0
    motion:
      mask:
        - 0,0.515,1,0.402,1,0,0,0
        - 0.979,0.54,0.853,0.563,0.838,0.412,0.987,0.409
  eufy: # <------ Name the camera
    genai:
      enabled: false
    live:
      stream_name: rtsp_cam
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam # <----- The stream you want to use for detection
          roles:
            - audio
            - detect
            - record
    snapshots:
      enabled: true
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    zones:
      gartentor:
        coordinates: 42,408,298,413,333,919,83,915
      haustuer:
        coordinates: 813,436,1117,442,1109,867,798,894
    motion:
      mask:
        - 0.391,0.419,0.543,0.358,0.598,0,0,0,0,0.22,0,0.271,0,0.329,0.118,0.375
        - 1,0,1,0.369,1,0.575,1,1,0.91,1,0.857,0.881,0.738,0.769,0.641,0.729,0.604,0.605,0.568,0.566,0.472,0.432,0.272,0.487,0.368,0
        - 0.046,0.589,0.028,0.716,0,0.583,0,0.431,0.041,0.34,0.069,0.452
        - 0,1,0.186,1,0.147,0.86,0,0.845
        - 0.631,0.843,0.552,0.886,0.526,0.907,0.549,1,0.691,0.997
      threshold: 30
      contour_area: 10
      improve_contrast: true
    birdseye:
      mode: objects


record: # <----- Enable recording
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false

  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 15

detect:
  enabled: true
  max_disappeared: 100

motion:
  contour_area: 30 # 30 default
  improve_contrast: true


detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

version: 0.15-1
camera_groups:
  Test:
    order: 1
    icon: LuActivity
    cameras:
      - birdseye
      - eufy
      - garten
      - garten_main
notifications:
  enabled: 'true'
  
  ```
  ![Screenshot 2025-04-05 at 08 14 34](https://github.com/user-attachments/assets/7da80a4c-535e-4756-b8e2-a10c3e75c429)
