### DISCUSSION TITLE
Telemetry configuration - network_bandwidth

### DISCUSSION THREAD

**Discussion by beginner2047** [blakeblackshear/frigate#17557] [Ask A Question] [answered]
I would like to enable the network bandwidth monitoring via Frigate

I have enabled cap_net_admin and cap_net_raw

```
docker inspect frigate | grep -A 3 "CapAdd"
            "CapAdd": [
                "CAP_NET_ADMIN",
                "CAP_NET_RAW"
            ],
```

version 1 in config.yaml
```
telemetry:
  network_interfaces:
    - ens18
    - lo
  stats:
    network_bandwidth: true
```
version 2 in config.yaml
```
telemetry:
  stats:
    network_bandwidth: true
```
 
There is no new section / information about network bandwidth in system metrics page. May I know how I can enable it?
