### DISCUSSION TITLE
[Config Support]: Config error using FRIGATE_MQTT_PASSWORD

### DISCUSSION THREAD

**Discussion by luukrijnbende** [blakeblackshear/frigate#17551] [Config Support] [answered]
### Describe the problem you are having

I'm trying to use FRIGATE_MQTT_PASSWORD as substitution for connecting to my MQTT server. When I try to save the config I get an error, it works when I don't use the substitution. The variable is defined in my docker environment variables. Other substitutions do work.

```
Config Error:

Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 200, in config_save
    FrigateConfig.parse_yaml(new_config)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 689, in parse_yaml
    return cls.parse(config_yaml, is_json=False, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 685, in parse
    return cls.parse_object(config, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 695, in parse_object
    return cls.model_validate(
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
  File &#34;/opt/frigate/frigate/config/env.py&#34;, line 18, in validate_env_string
    return v.format(**FRIGATE_ENV_VARS)
KeyError: &#39;FRIGATE_MQTT_PASSWORD&#39;
```

### Version

0.15.0-cea210d

### Frigate config file

```yaml
...
mqtt:
  enabled: true
  host: x.x.x.x
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
...
```

### Relevant Frigate log output

```shell
Nothing is logged
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rocm
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
    - /dev/dri # VAAPI
    - /dev/kfd # ROCm
    - /dev/apex_0 # Coral TPU
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/frigate/config:/config
    - /mnt/nvr:/media/frigate
    - type: tmpfs
      target: /tmp/cache
      tmpfs:
        size: 1000000000
    ports:
    # - "1984:1984" # go2rtc
    - "8971:8971" # Webinterface
    # - "5000:5000" # Internal unauthenticated access. Expose carefully.
    - "8554:8554" # RTSP feeds
    - "8555:8555/tcp" # WebRTC over tcp
    - "8555:8555/udp" # WebRTC over udp
    environment:
      #LIBVA_DRIVER_NAME: radeonsi
      HSA_OVERRIDE_GFX_VERSION: 9.0.0
      HSA_USE_SVM: 0
      FRIGATE_RTSP_PASSWORD: "very_secure"
      FRIGATE_GO2RTC_RTSP_PASSWORD: "very_secure"
      FIRGATE_MQTT_PASSWORD: "very_secure"
```

### Object Detector

Coral
