### DISCUSSION TITLE
[Support]: Browser Playback for H265 Codec

### DISCUSSION THREAD

**Discussion by matthew-w-bayley** [blakeblackshear/frigate#17558] [General Support]
### Describe the problem you are having

I'm unable to replay recorded video from Frigate in the browser. The video appears and tries to play but it doesn't play. I think this is because my cameras use H.265 decoding and browsers don't support decoding?

It would be great to have the ability to convert to the h264 codec on playback (instead of transcoding at runtime which might be costly?)

### Version

0.15.0-cea210d

### What browser(s) are you using?

Version 135.0.7049.52 (Official Build) (64-bit)

### Frigate config file

```yaml
cameras:
  BAR-RIGHT:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://$URL
          roles:
            - detect

detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: []

record:
  enabled: true
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from '$URL':
  Metadata:
    title           : HIK Media Server V4.72.107
    comment         : HIK Media Server Session Description : standard
  Duration: N/A, start: 0.120000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuvj420p(pc), 640x360 [SAR 1:1 DAR 16:9], 25 tbr, 90k tbn
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "452mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/{USER}/frigate:/config
      - /home/{USER}/C-DRIVE/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      #- "8554:8554" # RTSP feeds
      #- "8555:8555/tcp" # WebRTC over tcp
      #- "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Hikvision
