### DISCUSSION TITLE
Whats wrong config.yml (0.9.0 rc2)

### DISCUSSION THREAD

**Discussion by McPaHa** [blakeblackshear/frigate#1756] [General]
Hi!

Cannot get clips and snapshots saved... whats wrong with this config.yml?

```
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.1.60
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: xxx

cameras:
  etupiha:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.1.67:554/Streaming/Channels/1
          roles:
            - rtmp
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: True
    objects:
      track:
        - person
        - dog
        - cat
        - car
    record:
      enabled: True
      retain_days: 0
      events:
        enabled: True
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - cat
          - car
        required_zones: []
        retain:
          default: 3
          objects:
            person: 7
      snapshots:
        enabled: True
        bounding_box: True
        retain:
          default: 3
          objects:
            person: 7

```
