### DISCUSSION TITLE
cameras.TestCam.detect.coral: Extra inputs are not permitted:

### DISCUSSION THREAD

**Discussion by rubgar-lab** [blakeblackshear/frigate#17566] [Ask A Question] [answered]
Hi,

I am new to frigate. I am trying to utilize frigate with my coral accelerator USB. I got frigate working with a light setup and a test camera, which didn't contain coral. however as soon as I add the detect section with reference to coral, frigate's log says: Extra inputs are not permitted.

I have been at it for three days now. So I figured I'd ask the question here. maybe someone knows the answer. I did see other discussions regarding extra inputs, however they pertained to other parameters.

My config.yml file looks like this:

```
database:
  path: /db/frigate.db

mqtt:
  host: mqtt
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: <password>

birdseye:
  enabled: true
  mode: continuous

cameras:
  TestCam:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@ip:554/stream1
          roles:
            - detect
    detect:
      enabled: true
      coral:
        device: usb
version: 0.15-1
```

What am I doing wrong? When I remove coral: and the device: usb it works fine. But obviously I want to be able to detect movement and recognize the subject.
