### DISCUSSION TITLE
Audio detector errors

### DISCUSSION THREAD

**Discussion by mydreamdoctor** [blakeblackshear/frigate#17570] [Config Support] [answered]
### Describe the problem you are having

I'm trying to add audio detection to my existing frigate setup. I have a camera with audio. I'm able to hear the audio from that camera when viewing the live feed in Frigate. However when I add audio detection to that feed I get the following errors continuously in the logs.

Any advice would be appreciated.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: x.x.x.24
  user: ********
  password: ********

auth:
  enabled: true

go2rtc:
  streams:
    driveway:
      - rtsp://********:********@x.x.x.104:554/stream1
    driveway_detect:
      - rtsp://********:********@x.x.x.104:554/stream2
    front_door:
      - rtsp://********:********@x.x.x.106:554/stream1
    front_door_detect:
      - rtsp://********:********@x.x.x.106:554/stream2
    backyard:
      - rtsp://********:********@x.x.x.103:554/stream1
    backyard_detect:
      - rtsp://********:********@x.x.x.103:554/stream2
    front_courtyard:
      - rtsp://********:********@x.x.x.105:554/stream1
      - "ffmpeg:back#audio=aac"
    front_courtyard_detect:
      - rtsp://********:********@x.x.x.105:554/stream2
      - "ffmpeg:back#audio=aac"
    front_street:
      - onvif://********:********@x.x.x.107:80?subtype=MainStreamToken
    front_street_detect:
      - onvif://********:********@x.x.x.107:80?subtype=SubStreamToken
    garage:
      - rtsp://********:********@x.x.x.102:554/stream=0

  webrtc:
    candidates:
      - x.x.x.59:8555
      - stun:8555

detectors:
  coral1:
    type: edgetpu
    device: pci:0

cameras:

  driveway:
    enabled: true
    record:
      retain:
        days: 2
        mode: all

    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/driveway
          roles:
            - record
        - path: rtsp://localhost:8554/driveway_detect
          roles:
            - detect
    zones:
      part_driveway:
        coordinates: 852,68,1280,302,1280,720,0,720,0,0
    objects:
      track:
        - car
        - car
        - person

    review:
      alerts:
        required_zones:
          - part_driveway

    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: true
  
  garage:
    enabled: true
    record:
      retain:
        days: 2
        mode: all
    detect:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/garage
          roles:
            - record

  front_door:
    enabled: true
    record:
      retain:
        days: 2
        mode: all
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/front_door
          roles:
            - record
        - path: rtsp://localhost:8554/front_door_detect
          roles:
            - detect
    objects:
      track:
        - dog
        - cat
        - person
        - bird

    motion:
      mask: 
        0.198,0.357,0.322,0.407,0.413,0.402,0.481,0.348,0.537,0.267,0.597,0.16,0.65,0.118,0.709,0.108,0.705,0.001,0.003,0.005,0.015,0.136,0.163,0.22

  front_street:
    enabled: false
    record:
      retain:
        days: 2
        mode: all
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/front_street
          roles:
            - record
        - path: rtsp://localhost:8554/front_street_detect
          roles:
            - detect
    objects:
      track:
        - dog
        - cat
        - person
        - bird

    motion:
      mask: 0.912,0.205,0.784,0,1,0,1,0.455
  backyard:
    enabled: true
    record:
      retain:
        days: 2
        mode: all
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/backyard
          roles:
            - record
        - path: rtsp://localhost:8554/backyard_detect
          roles:
            - detect
    objects:
      track:
        - dog
        - cat
        - person
        - bird

    motion:
      threshold: 70
      contour_area: 10
      improve_contrast: true

  front_courtyard:
    enabled: true
    record:
      retain:
        days: 2
        mode: all
    audio:
      enabled: true
      listen:
        - bark
        - yip
        - howl
        - bow-wow
        - growling
        - whimper_dog
        - motor_vehicle
        - car
        - honk
        - toot
        - car_alarm
        - power_windows
        - skidding
        - tire_squeal
        - car_passing_by
        - race_car
        - truck
        - air_brake
        - air_horn
        - reversing_beeps
        - ice_cream_truck
        - bus
        - emergency_vehicle
        - police_car
        - ambulance
        - fire_engine
        - motorcycle
        - traffic_noise
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://localhost:8554/front_courtyard
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/front_courtyard_detect
          roles:
            - detect
    zones:
      front_courtyard_main_zone:
        coordinates: 341,475,0,623,0,720,232,720,1013,720,1000,109,660,109
      Frnt_Courtyard_Road:
        coordinates: 0.775,0.146,0.771,0,0.511,0,0.514,0.149
        loitering_time: 2
        inertia: 3
    review:
      alerts:
        required_zones: front_courtyard_main_zone
    objects:
      track:
        - dog
        - cat
        - person
        - bird
      filters:
        person:
          mask: 0.783,0.005,0.809,0.992,0.997,0.996,0.999,0
    motion:
      threshold: 57
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.001,0.856,0.001,0,0.508,0.002,0.513,0.15,0.264,0.654
        - 0.001,0.867,0.269,0.66,0.343,0.512,0.618,0.728,0.537,0.996,0.003,0.996


objects:
  filters:
    person:
      min_score: 0.75


record:
  enabled: true
  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 3
  detections:
    retain:
      days: 3
version: 0.15-1
```

### Relevant Frigate log output

```shell
|info  | 2025-04-07 11:25:23 | frigate.audio_manager        | Audio processor started (pid: 937)
info  | 2025-04-07 11:25:23 | frigate.api.fastapi_app      | Starting FastAPI app
info  | 2025-04-07 11:25:23 | frigate.api.fastapi_app      | FastAPI started
error | 2025-04-07 11:25:24 | audio.front_courtyard        | ffmpeg process is not running, restarting...
error | 2025-04-07 11:25:34 | ffmpeg.front_courtyard.audio | [out#0/s16le @ 0x5611600a0400] Output file does not contain any stream
error | 2025-04-07 11:25:34 | ffmpeg.front_courtyard.audio | Error opening output file pipe:.
error | 2025-04-07 11:25:34 | ffmpeg.front_courtyard.audio | Error opening output files: Invalid argument
info  | 2025-04-07 11:25:34 | audio.front_courtyard        | Terminating the existing ffmpeg process...
info  | 2025-04-07 11:25:34 | audio.front_courtyard        | Waiting for ffmpeg to exit gracefully...
error | 2025-04-07 11:25:36 | audio.front_courtyard        | ffmpeg process is not running, restarting...
error | 2025-04-07 11:25:46 | ffmpeg.front_courtyard.audio | [out#0/s16le @ 0x5586dc8ddf00] Output file does not contain any stream
error | 2025-04-07 11:25:46 | ffmpeg.front_courtyard.audio | Error opening output file pipe:.
error | 2025-04-07 11:25:46 | ffmpeg.front_courtyard.audio | Error opening output files: Invalid argument
info  | 2025-04-07 11:25:46 | audio.front_courtyard        | Terminating the existing ffmpeg process...
info  | 2025-04-07 11:25:46 | audio.front_courtyard        | Waiting for ffmpeg to exit gracefully...
error | 2025-04-07 11:25:47 | audio.front_courtyard        | ffmpeg process is not running, restarting...
```

### Relevant go2rtc log output

```shell
No errors in log.
```

### Frigate stats

```json
{"cameras":{"driveway":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":750,"capture_pid":853,"ffmpeg_pid":868,"audio_rms":0.0,"audio_dBFS":0.0},"garage":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":false,"pid":756,"capture_pid":869,"ffmpeg_pid":873,"audio_rms":0.0,"audio_dBFS":0.0},"front_door":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":785,"capture_pid":872,"ffmpeg_pid":895,"audio_rms":0.0,"audio_dBFS":0.0},"front_street":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":null,"capture_pid":null,"ffmpeg_pid":0,"audio_rms":0.0,"audio_dBFS":0.0},"backyard":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":5.1,"detection_enabled":true,"pid":800,"capture_pid":916,"ffmpeg_pid":922,"audio_rms":0.0,"audio_dBFS":0.0},"front_courtyard":{"camera_fps":5.0,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":2.7,"detection_enabled":true,"pid":808,"capture_pid":921,"ffmpeg_pid":943,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral1":{"inference_speed":7.14,"detection_start":0.0,"pid":699}},"detection_fps":7.8,"gpu_usages":{"amd-vaapi":{"gpu":"1.67%","mem":"6.73%"}},"cpu_usages":{"frigate.full_system":{"cpu":"4.2","mem":"10.1"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"97":{"cpu":"8.2","cpu_average":"8","mem":"0.3","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"106":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"3.7","cpu_average":"3","mem":"1.5","cmdline":"python3 -u -m frigate"},"121":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"173":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"174":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"175":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"176":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"177":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"339":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"683":{"cpu":"2.8","cpu_average":"2","mem":"0.7","cmdline":"frigate.recording_manager"},"692":{"cpu":"0.9","cpu_average":"0","mem":"0.6","cmdline":"frigate.review_segment_manager"},"699":{"cpu":"1.7","cpu_average":"1","mem":"0.6","cmdline":"frigate.detector.coral1"},"721":{"cpu":"3.0","cpu_average":"2","mem":"0.7","cmdline":"frigate.output       "},"750":{"cpu":"1.1","cpu_average":"1","mem":"0.7","cmdline":"frigate.process:driveway"},"756":{"cpu":"1.0","cpu_average":"1","mem":"0.7","cmdline":"frigate.process:garage"},"785":{"cpu":"1.7","cpu_average":"1","mem":"0.7","cmdline":"frigate.process:front_door"},"800":{"cpu":"8.2","cpu_average":"3","mem":"0.7","cmdline":"frigate.process:backyard"},"808":{"cpu":"3.8","cpu_average":"5","mem":"0.7","cmdline":"frigate.process:front_courtyard"},"853":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:driveway"},"868":{"cpu":"0.9","cpu_average":"1","mem":"0.4","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/driveway_detect -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"869":{"cpu":"2.4","cpu_average":"2","mem":"0.7","cmdline":"frigate.capture:garage"},"872":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:front_door"},"873":{"cpu":"4.3","cpu_average":"4","mem":"0.5","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1920:h=1080,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"894":{"cpu":"0.4","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4"},"895":{"cpu":"1.1","cpu_average":"1","mem":"0.4","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/front_door_detect -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"899":{"cpu":"0.6","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4"},"916":{"cpu":"0.5","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:backyard"},"921":{"cpu":"0.5","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:front_courtyard"},"922":{"cpu":"1.1","cpu_average":"1","mem":"0.3","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/backyard_detect -r 5 -vf fps=5,scale_vaapi=w=640:h=480,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"935":{"cpu":"0.1","cpu_average":"0","mem":"0.6","cmdline":"python3 -u -m frigate"},"943":{"cpu":"1.1","cpu_average":"0","mem":"0.4","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/front_courtyard_detect -r 5 -vf fps=5,scale_vaapi=w=736:h=416,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"959":{"cpu":"0.6","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4"},"963":{"cpu":"0.5","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://localhost:8554/front_courtyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_courtyard@%Y%m%d%H%M%S%z.mp4"},"968":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"975":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"982":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"989":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"996":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 736x416 -i pipe: -threads 1 -f mpegts -s 1273x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"1003":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"69279":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"69708":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":6208,"version":"0.15.0-cea210d","latest_version":"0.15.0","storage":{"/media/frigate/recordings":{"total":958863.5,"used":242872.6,"free":667211.3,"mount_type":"ext4"},"/media/frigate/clips":{"total":958863.5,"used":242872.6,"free":667211.3,"mount_type":"ext4"},"/tmp/cache":{"total":958863.5,"used":242872.6,"free":667211.3,"mount_type":"overlay"},"/dev/shm":{"total":1024.0,"used":240.1,"free":783.9,"mount_type":"tmpfs"}},"temperatures":{"apex_0":66.05},"last_updated":1743996043},"processes":{"recording":{"pid":683},"review_segment":{"pid":692},"go2rtc":{"pid":97},"audio_detector":{"pid":935}}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      # - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/storage:/media/frigate

    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" # WebRTC web interface
    environment:
      FRIGATE_RTSP_PASSWORD: "********"
      HSA_OVERRIDE_GFX_VERSION: "9.0.0"
      LIBVA_DRIVER_NAME: "radeonsi"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a0de4eef-1506-4740-9e53-e3e8e7c1a848)
