### DISCUSSION TITLE
Question on go2rtc

### DISCUSSION THREAD

**Discussion by kadamik** [blakeblackshear/frigate#17580] [Ask A Question]
I have a question when I am using only 1 stream for detect and stream.  It is my understanding that when go2rtc does scaling that the bitrate is unaffected is that true?  If not is there anything that can be done to keep the bitrate the same?  Scaling as I know it is just resizing the video as long as it is in the same ratio as the original stream.  I am still learning so please correct me if I am wrong.

**Comment by hawkeye217** [comment]
What is your go2rtc config?

**Reply by kadamik** [reply]
```
go2rtc:
  streams:
#4K Cameras
    Camera_Sideyard:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.10:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Frontyard:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.11:554/Streaming/Channels/101#timeout=30
    Camera_Dog_Gate:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.12:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Backyard:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.13:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Driveway:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.14:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Frontdoor_Garage:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.15:554/cam/realmonitor?channel=1&subtype=0#timeout=30
    Camera_Street_lpr:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.20:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Garage:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.103:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0

#2KCameras
    Camera_Den:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.102:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Front_Hall:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.101:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0

    Camera_Playroom:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.104:554/cam/realmonitor?channel=1&subtype=0#timeout=30#backchannel=0
    Camera_Front_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.16:554/h264Preview_01_main#timeout=30#backchannel=0
    Camera_Dog_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.17:554/h264Preview_01_main#timeout=30#backchannel=0
    Camera_Back_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.18:554/h264Preview_01_main#timeout=30#backchannel=0
    Camera_Garage_Doorbell:
      - rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.10.19:554/h264Preview_01_main#timeout=30#backchannel=0
```
