### DISCUSSION TITLE
Green screen on my eleventh camera.

### DISCUSSION THREAD

**Discussion by HarryTutt** [blakeblackshear/frigate#17587] [Ask A Question]
I recently added another camera to my system to see if it explodes. The funny thing is that on Windows 10, with any browser, that damn camera gives me green screens, especially when I maximize the view. The only way to keep it stable is to use Steam 1 2560x1440 as the live view. The funny thing is that the computer I'm accessing from has two operating systems installed: Windows 10 and OS X Hackintosh, and it turns out that when I access it from the Mac with Safari, the problem disappears. Could you explain this to me?

**Comment by hawkeye217** [comment]
We'll need to see your config and logs in order to be able to help.

**Comment by HarryTutt** [comment]
```
mqtt:
  host: 192.168.2.90
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
tls:
  enabled: true
auth:
  enabled: true
  reset_admin_password: false
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.19.0.0/16 # <---- this is the subnet for the internal docker compose network
ffmpeg:
  hwaccel_args: preset-vaapi   #Enable Hardware Acceleration
detectors:
  coral_1:
    type: edgetpu
    device: usb:0
  coral_2:
    type: edgetpu
    device: usb:1
record:
  enabled: true
  retain:
    days: 20
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 30
birdseye:
  enabled: true
  mode: continuous
  layout:
    scaling_factor: 2.0
objects:
  track:
    - person
    - dog
    - cat
    - car
    - bird
    - license_plate
go2rtc:
  modes:
    - webrtc
  streams:
    Perimeter_1:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.46:554/stream1#audio=aac#video=copy
    Perimeter_1_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.46:554/stream2#audio=aac#video=copy
    Perimeter_2:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.47:554/stream1#audio=aac#video=copy
    Perimeter_2_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.47:554/stream2#audio=aac#video=copy
    Perimeter_3:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.48:554/stream1#audio=aac#video=copy
    Perimeter_3_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.48:554/stream2#audio=aac#video=copy
    Perimeter_4:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.49:554/stream1#audio=aac#video=copy
    Perimeter_4_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.49:554/stream2#audio=aac#video=copy
    Salon_1:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.34:554/stream1#audio=aac#video=copy
    Salon_1_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.34:554/stream2#audio=aac#video=copy
    Salon_2:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.42:554/stream1#audio=aac#video=copy
    Salon_2_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.42:554/stream2#audio=aac#video=copy
    Sotano_1:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.35:554/stream1#audio=aac#video=copy
    Sotano_1_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.35:554/stream2#audio=aac#video=copy
    Entrada_1:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.33:554/stream1#audio=aac#video=copy
    Entrada_1_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.33:554/stream2#audio=aac#video=copy
    Dormitorio_1:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.36:554/stream1#audio=aac#video=copy
    Dormitorio_1_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.36:554/stream2#audio=aac#video=copy
    Exterior_1:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.45:554/stream1#audio=aac#video=copy
    Exterior_1_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.45:554/stream2#audio=aac#video=copy
    Exterior_2:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.73:554/stream1#audio=aac#video=copy
    Exterior_2_sub:
      - ffmpeg:rtsp://{FRIGATE_GO2RTC_RTSP_USERNAME}:{FRIGATE_GO2RTC_RTSP_PASSWORD}@192.168.2.73:554/stream2#audio=aac#video=copy
  webrtc:
    candidates:
      - 192.168.2.80:8555
      - stun:8555
cameras:
  Perimeter_1: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      #output_args:
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Perimeter_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Perimeter_1_sub
          roles:
            - detect
    live:
      stream_name: Perimeter_1_sub
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0,0.043,0.361,0.046,0.359,0,0,0
    zones:
      Zona0:
        coordinates: 0.471,0.155,0.403,0.146,0.378,0.142,0.348,0.142,0.196,1,0.533,0.996
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
      Zona1:
        coordinates: 
          0.244,0.723,0.195,1,0,1,0,0.914,0.23,0.235,0.229,0.185,0.211,0.152,0.188,0.117,0.174,0.091,0.157,0.079,0.218,0.086,0.248,0.088,0.254,0.1,0.311,0.126,0.349,0.146,0.335,0.225
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
    objects:
      filters:
        car:
          mask: 0.001,0.047,0.363,0.05,0.361,0,1,0,1,1,0,1
    review:
      alerts:
        required_zones: Zona0
      detections:
        required_zones: Zona1
  Perimeter_2: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      #output_args:
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Perimeter_2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Perimeter_2_sub
          roles:
            - detect
    live:
      stream_name: Perimeter_2_sub
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0,0.051,0.357,0.052,0.358,0,0,0
    zones:
      Zona0:
        coordinates: 0.392,1,0.806,1,0.563,0.171,0.455,0.187
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
      Zona1:
        coordinates: 
          0.808,1,1,1,1,0.799,0.888,0.618,0.827,0.524,0.691,0.327,0.633,0.251,0.599,0.204,0.564,0.171,0.643,0.436
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
    objects:
      filters:
        car:
          mask: 0,1,0,0.054,0.359,0.053,0.36,0,1,0,1,1
    review:
      alerts:
        required_zones: Zona0
      detections:
        required_zones: Zona1
  Perimeter_3: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      #output_args:
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Perimeter_3
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Perimeter_3_sub
          roles:
            - detect
    live:
      stream_name: Perimeter_3_sub
    objects:
      filters:
        car:
          mask: 
            0,1,0.336,1,0.353,0.712,0.296,0.338,0.199,0.164,0.247,0.149,0.25,0.119,0.34,0.103,0.349,0.151,0.5,0.133,0.5,0.004,0.367,0.004,0.368,0.049,0.003,0.053,0,0.129,0.039,0.172,0.043,0.256,0,0.446
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0,0.043,0.362,0.048,0.361,0,0,0
    zones:
      Zona0:
        coordinates: 
          0.198,0.165,0.299,0.33,0.307,0.406,0.358,0.711,0.34,1,0.916,1,0.751,0.592,0.594,0.265,0.596,0.135,0.343,0.158,0.34,0.101,0.251,0.121,0.25,0.152
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
      Zona1:
        coordinates: 
          0.337,1,0.354,0.711,0.303,0.404,0.295,0.335,0.197,0.167,0.25,0.148,0.248,0.114,0.344,0.097,0.347,0.148,0.499,0.133,0.501,0,0.362,0,0.363,0.046,0,0.047,-0.001,0.126,0.027,0.154,0.041,0.173,0.042,0.259,0,0.441,0,1
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
      Zona2:
        coordinates: 
          0.595,0.257,0.598,0.158,0.705,0.256,0.703,0.312,0.836,0.464,0.825,0.539,0.988,0.771,0.98,0.811,1,0.85,1,1,0.918,1,0.748,0.576
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
    review:
      alerts:
        required_zones: Zona0
      detections:
        required_zones:
          - Zona1
          - Zona2
  Perimeter_4: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      #output_args:
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Perimeter_4
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Perimeter_4_sub
          roles:
            - detect
    live:
      stream_name: Perimeter_4_sub
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0.358,0.046,0.358,0,0,0,0,0.047
    zones:
      Zona0:
        coordinates: 
          0,0.487,0,0.043,0.289,0.047,0.517,0.275,0.585,0.336,0.784,0.538,0.653,1,0.546,0.874,0.456,0.953,0.335,0.761,0.149,0.446,0.026,0.56
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
      Zona1:
        coordinates: 0,0.493,0,1,0.652,1,0.543,0.877,0.457,0.961,0.147,0.447,0.027,0.559
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
      Zona2:
        coordinates: 
          0.786,0.536,0.841,0.283,0.609,0.131,0.607,0.097,0.42,0,0.359,0,0.358,0.046,0.288,0.047
        loitering_time: 0
        objects:
          - person
          - cat
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 400
            max_area: 8000
        inertia: 1
    review:
      alerts:
        required_zones: Zona0
      detections:
        required_zones:
          - Zona1
          - Zona2
  Salon_2: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Salon_2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Salon_2_sub
          roles:
            - detect
    live:
      stream_name: Salon_2_sub
    motion:
      mask: 0,0.046,0.36,0.045,0.361,0,0,0
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Zona3:
        coordinates: 0,1,0,0.056,0.363,0.047,0.363,0,1,0,1,1
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 1
    review:
      alerts:
        required_zones: Zona3
    objects:
      filters:
        car:
          mask: 0,1,1,1,1,0,0,0
    onvif:
      host: 192.168.2.42
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
  Salon_1: #Name for your comment
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Salon_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Salon_1_sub
          roles:
            - detect
    live:
      stream_name: Salon_1_sub
    motion:
      mask: 0,0.053,0.361,0.049,0.362,0,0,0
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Zona3:
        coordinates: 0,0.054,0,1,1,1,1,0,0.903,0,0.363,0,0.364,0.051
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 1
    objects:
      filters:
        car:
          mask: 0,1,0,0,1,0,1,1
    onvif:
      host: 192.168.2.34
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    review:
      alerts:
        required_zones: Zona3
  Sotano_1: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Sotano_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Sotano_1_sub
          roles:
            - detect
    live:
      stream_name: Sotano_1_sub
    onvif:
      host: 192.168.2.35
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    zones:
      Zona6:
        coordinates: 1,0,1,1,0,1,0,0.048,0.36,0.046,0.36,0
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 4500
            max_area: 18000
        inertia: 1
    motion:
      mask: 0,0,0.357,0,0.357,0.047,0,0.044
    review:
      alerts:
        required_zones: Zona6
  Entrada_1: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Entrada_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Entrada_1_sub
          roles:
            - detect
    live:
      stream_name: Entrada_1_sub
    onvif:
      host: 192.168.2.33
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    motion:
      mask: 0,0,0.359,0,0.357,0.05,0,0.048
    zones:
      Zona7:
        coordinates: 0,0.05,0.36,0.056,0.362,0,1,0,1,1,0,1
        inertia: 1
        loitering_time: 0
        objects:
          - person
        filters:
          person:
            min_score: .5
            threshold: .7
            min_area: 20000
            max_area: 80000
    review:
      alerts:
        required_zones: Zona7
  Dormitorio_1: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Dormitorio_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Dormitorio_1_sub
          roles:
            - detect
    live:
      stream_name: Dormitorio_1_sub
    onvif:
      host: 192.168.2.36
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    motion:
      mask: 0,0,0.361,0,0.362,0.048,0,0.045
    zones:
      Zona5:
        coordinates: 0,0.047,0,1,1,1,1,0,0.364,0,0.365,0.051
        loitering_time: 0
        objects: person
        inertia: 1
    review:
      alerts:
        required_zones: Zona5
    objects:
      mask: 0.425,0.322,0.709,0.36,0.711,0,0.423,0
  Exterior_1: #Name for your comment
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    ffmpeg:
      #output_args:
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Exterior_1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Exterior_1_sub
          roles:
            - detect
    live:
      stream_name: Exterior_1_sub
    onvif:
      host: 192.168.2.45
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    motion:
      mask: 0,0.049,0.359,0.048,0.361,0,0,0
      threshold: 30
      contour_area: 17
      improve_contrast: true
    zones:
      Zona4:
        coordinates: 0,0.079,0.317,0.18,0.322,0.328,0.331,0.51,0.323,0.809,0,0.805
        inertia: 1
        loitering_time: 0
        objects: bird
    objects:
      filters:
        bird:
          min_score: 0.1
          threshold: 0.2
      mask: 
        0.001,0.809,0.324,0.812,0.33,0.494,0.32,0.177,0,0.07,0,0.053,0.364,0.052,0.367,0.004,1,0,1,1,0,1
    review:
      alerts:
        required_zones: Zona4
      detections: {}
  Exterior_2: #Name for your comment
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      #output_args:
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Exterior_2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Exterior_2_sub
          roles:
            - detect
    live:
      stream_name: Exterior_2
    onvif:
      host: 192.168.2.73
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'
    zones:
      Zona8:
        coordinates: 0,0.844,0.187,0.848,0.364,0.827,0.482,0.894,0.563,0.942,0.721,1,0,1
        loitering_time: 0
        inertia: 3
        objects: bird
    motion: {}
    review:
      alerts:
        required_zones: Zona8
    objects:
      filters:
        car:
          mask: 
            0,0,1,0,1,1,0.879,1,0.72,1,0.567,0.937,0.48,0.889,0.362,0.823,0.27,0.835,0.159,0.844,0.071,0.844,0,0.84
camera_groups:
  Perimetro:
    order: 1
    icon: LuExpand
    cameras:
      - Perimeter_1
      - Perimeter_2
      - Perimeter_3
      - Perimeter_4
  Interior:
    order: 2
    icon: LuView
    cameras:
      - Salon_2
      - Salon_1
  Exterior:
    order: 3
    icon: LuActivitySquare
    cameras:
      - Exterior_1
      - Exterior_2
version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
notifications:
  enabled: 'false'
```
