### DISCUSSION TITLE
[Bug]: 0.16.0-f284046 - UI - Monaco Editor - Numbers shown with weird font

### DISCUSSION THREAD

**Discussion by crossan007** [blakeblackshear/frigate#17602] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When editing the config in the UI (I believe this is VS Code / Monaco), all numbers present in the text render using the "Emoji" variant of each numeric character instead of plain text.

![image](https://github.com/user-attachments/assets/adfd5d23-d74a-4758-b1e9-47a08aeee36b)

Disabling "Allow pages to choose their own fonts, instead of your selections above" in "about:preferences#searchResults" results in "regular" characters being shown (in other words, forcing a specific font in Firefox and preventing Frigate from choosing its own font causes the "expected" numerals to render)

![image](https://github.com/user-attachments/assets/02762a85-61ae-4c91-b64b-0faf8f92565d)
![image](https://github.com/user-attachments/assets/ef71f46a-4338-4bc0-aa2c-5bae9128c649)

Switching to a different / new Firefox profile causes the issue to persist; however, opening Firefox "In Private" renders with regular numerals

### Steps to reproduce

1. Running frigate from `ghcr.io/blakeblackshear/frigate:f284046` (or whatever latest commit is)
2. Open config editor in Firefox
3. Observe all numerals are "emoji"
...

### Version

0.16.0-f284046

### In which browser(s) are you experiencing the issue with?

Firefox 136.0.2

### Frigate config file

```yaml
version: 0.16-0
auth:
  session_length: 2592000 # 30 days
  refresh_time: 1728000 # 20 days
mqtt:
  enabled: false
tls:
  enabled: false
detect:
  enabled: false
audio:
  enabled: false
logger:
  default: info
  # logs:
  #   frigate.output.birdseye: info
  #   peewee: info
  #   urllib3: info
  #   frigate.record.maintainer: info
  #   frigate.api.auth: info
record:
  enabled: true
  retain:
    days: 7
    mode: all
ffmpeg:
  path: '5.0'
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-rtsp-restream
birdseye:
  enabled: true
  restream: true
  mode: motion
  layout:
    max_cameras: 4

camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
  Doors_And_Front:
    order: 1
    icon: LuDoorOpen
    cameras:
      - wyze-v3-side-door
      - wyze-v3-front-porch
      - wyze-v3-back-yard
      - wyze-v3-bay-window

  First_Floor:
    order: 3
    icon: LuCat
    cameras:
      - wyze-v3-side-door
      - wyze-v3-cat-feeder
      - wyze-v3-kitchen
      - wyze-v3-spare-room
      - wyze-v3-bay-window
      - wyze-v3-dining-room-2
      - wyze-v3-dining-room
go2rtc:
  webrtc:
    candidates:
      - nvr.ccrossan.com:8555
  streams:
    wyze-v3-side-door:
      - rtsp://thingino:thingino@172.30.9.154/ch0
    wyze-v3-side-door_sub:
      - rtsp://thingino:thingino@172.30.9.154/ch1
    wyze-v3-9064:
      - rtsp://thingino:thingino@172.30.9.125/ch0
    wyze-v3-9064_sub:
      - rtsp://thingino:thingino@172.30.9.125/ch1
    wyze-v3-cat-feeder:
      - rtsp://thingino:thingino@172.30.9.135/ch0
    wyze-v3-cat-feeder_sub:
      - rtsp://thingino:thingino@172.30.9.135/ch1
    wyze-v3-kitchen:
      - rtsp://thingino:thingino@172.30.9.147/ch0
    wyze-v3-kitchen_sub:
      - rtsp://thingino:thingino@172.30.9.147/ch1
    wyze-v3-spare-1:
      - rtsp://thingino:thingino@172.30.9.112/ch0
    wyze-v3-spare-1_sub:
      - rtsp://thingino:thingino@172.30.9.112/ch1
    wyze-v3-utility-room:
      - rtsp://thingino:thingino@172.30.9.128/ch0
    wyze-v3-utility-room_sub:
      - rtsp://thingino:thingino@172.30.9.128/ch1
    wyze-v3-charles-office:
      - rtsp://thingino:thingino@172.30.9.142/ch0
    wyze-v3-charles-office_sub:
      - rtsp://thingino:thingino@172.30.9.142/ch1
    wyze-v3-back-yard:
      - rtsp://thingino:thingino@172.30.9.115/ch0
    wyze-v3-back-yard_sub:
      - rtsp://thingino:thingino@172.30.9.115/ch1
    wyze-v3-front-porch:
      - rtsp://thingino:thingino@172.30.9.104/ch0
    wyze-v3-front-porch_sub:
      - rtsp://thingino:thingino@172.30.9.104/ch1
    wyze-v3-dining-room:
      - rtsp://thingino:thingino@172.30.9.151/ch0
    wyze-v3-dining-room_sub:
      - rtsp://thingino:thingino@172.30.9.151/ch1
    wyze-v3-dining-room-2:
      - rtsp://thingino:thingino@172.30.9.152/ch0
    wyze-v3-dining-room-2_sub:
      - rtsp://thingino:thingino@172.30.9.152/ch1
    wyze-v3-bay-window:
      - rtsp://thingino:thingino@172.30.9.153/ch0
    wyze-v3-bay-window_sub:
      - rtsp://thingino:thingino@172.30.9.153/ch1
    wyze-v3-spare-room:
      - rtsp://thingino:thingino@172.30.9.137/ch0
    wyze-v3-spare-room_sub:
      - rtsp://thingino:thingino@172.30.9.137/ch1

cameras:
  wyze-v3-side-door:
    enabled: true
    webui_url: http://172.30.9.154
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-side-door
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-side-door_sub
          roles:
            - detect

  wyze-v3-9064:
    enabled: true
    webui_url: http://172.30.9.125
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-9064
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-9064_sub
          roles:
            - detect

  wyze-v3-cat-feeder:
    enabled: true
    webui_url: http://172.30.9.135
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-cat-feeder
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-cat-feeder_sub
          roles:
            - detect

  wyze-v3-kitchen:
    enabled: true
    webui_url: http://172.30.9.147
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-kitchen
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-kitchen_sub
          roles:
            - detect

  wyze-v3-spare-1:
    enabled: true
    webui_url: http://172.30.9.112
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-spare-1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-spare-1_sub
          roles:
            - detect

  wyze-v3-utility-room:
    enabled: true
    webui_url: http://172.30.9.128
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-utility-room
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-utility-room_sub
          roles:
            - detect

  wyze-v3-charles-office:
    enabled: true
    webui_url: http://172.30.9.118
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-charles-office
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-charles-office_sub
          roles:
            - detect

  wyze-v3-back-yard:
    enabled: true
    webui_url: http://172.30.9.115
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-back-yard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-back-yard_sub
          roles:
            - detect

  wyze-v3-front-porch:
    enabled: true
    webui_url: http://172.30.9.104
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-front-porch
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-front-porch_sub
          roles:
            - detect

    motion:
      mask:
        - 0.891,0.202,0.54,0.157,0.584,0.401,0.742,0.511,0.914,0.451
        - 0.178,0.174,0.542,0.157,0.476,0.44,0.425,0.533,0.216,0.492,0.22,0.234
        - 0.713,0.795,0.67,0.864,0.776,0.95,0.795,0.822
        - 0,0.241,0.423,0.163,0.813,0.208,0.999,0.268,1,0,0,0
  wyze-v3-dining-room:
    enabled: true
    webui_url: http://172.30.9.151
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-dining-room
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-dining-room_sub
          roles:
            - detect

  wyze-v3-dining-room-2:
    enabled: true
    webui_url: http://172.30.9.152
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-dining-room-2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-dining-room-2_sub
          roles:
            - detect

  wyze-v3-bay-window:
    enabled: true
    webui_url: http://172.30.9.153
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-bay-window
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-bay-window_sub
          roles:
            - detect

  wyze-v3-spare-room:
    enabled: true
    webui_url: http://172.30.9.137
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/wyze-v3-spare-room
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wyze-v3-spare-room_sub
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
networks:
 app_network:
    external:
      name: app_network
services:
  # go2rtc:
  #   image: alexxit/go2rtc
  #   #network_mode: host       # important for WebRTC, HomeKit, UDP cameras
  #   privileged: true         # only for FFmpeg hardware transcoding
  #   restart: unless-stopped  # autorestart on fail or config change from WebUI
  #   ports:
  #     - "1984:1984"
  #     - "8556:8554" # RTSP feeds
  #   environment:
  #     - TZ=America/New_York  # timezone in logs
  #   volumes:
  #     - "/DiskPool1/Frigate/go2rtc:/config"   # folder for go2rtc.yaml file (edit from WebUI)
  #   networks:
  #     - app_network
  #     - default

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:f284046
    shm_size: "1GB"
    deploy:
      resources:
        limits:
          #cpus: "3.0"
          memory: 14G
        reservations:
          memory: 14G
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DiskPool1/Frigate/config:/config
      - /DiskPool1/Frigate/Storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2G
    ports:
      - "1984:1984"
      #- "1935:1935" # RTMP
      #- "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
     
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app_network"
      - "traefik.http.services.frigate.loadbalancer.server.port=8971"
      - "traefik.http.routers.frigate-secure.rule=Host(`nvr.ccrossan.com`)"
      - "traefik.http.routers.frigate-secure.entrypoints=websecure"
      - "traefik.http.routers.frigate-secure.tls=true"
      - "traefik.http.routers.frigate-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.frigate-secure.service=frigate"
      
      # Additional labels for WebSocket compatibility
      - "traefik.http.middlewares.frigate-websockets.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.frigate-websockets.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept"
      - "traefik.http.routers.frigate-secure.middlewares=frigate-websockets"
    
    networks:
      - app_network
      - default
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://frigate:5000/api/stats"]
      interval: 15s
      timeout: 10s
      retries: 2
      start_period: 60s
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A

### Screenshots of the Frigate UI's System metrics pages

N/A
