### DISCUSSION TITLE
[Config Support]: Only track cars on a single camera

### DISCUSSION THREAD

**Discussion by staridiot** [blakeblackshear/frigate#17605] [Config Support]
### Describe the problem you are having

I have several cameras but I only want one to track cars. I've noticed a camera that is only supposed to detect people is constantly seeing a car (its a fridge). If I remove car from the
```
objects:
  track:
```

block it errors out. How do I add the ability for only camera3 to track cars?

### Version

0.15.0

### Frigate config file

```yaml
# This will error because car is not present in 
# objects:
#  track:

detectors:
  coral:
    type: edgetpu
    device: pci:0

mqtt:
  enabled: false

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

go2rtc:
  streams:
    camera1:
      - ffmpeg:http://192.168.1.254/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=mMd526TBmMES#video=copy#audio=copy#audio=opus
    camera2:
      - ffmpeg:http://192.168.1.253/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=rT06TygJNYL#video=copy#audio=copy#audio=opus
    camera3:
      - "ffmpeg:rtsp://admin:Po1wT6hAGcw.@192.168.1.252:8554/streaming/channels/101"
      - "ffmpeg:camera3#audio=opus#audio=aac"
    camera4:
      - ffmpeg:http://192.168.1.251/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=eX93bBocarLj#video=copy#audio=copy#audio=opus
  webrtc:
    candidates:
      - 192.168.0.60:8554

ffmpeg:
    #hwaccel_args: -c:v h264_cuvid -hwaccel_device 1
    hwaccel_args: preset-nvidia
    output_args:
        record: preset-record-generic-audio-copy

cameras:
  camera1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      enabled: true
    record:
      enabled: true
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          mode: all
          days: 90
    zones:
      Breeze_Way:
        coordinates: 
          0,0,0.329,0,0.328,0.036,0.658,0.036,0.66,0,0.704,0,0.68,0.272,0.771,0.352,1,0.552,1,1,0,1
        objects: person
        filters:
          person:
            min_area: 150000
    review:
      detections:
        required_zones: Breeze_Way
      alerts:
        labels: []
  camera2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      enabled: true
    record:
      enabled: true
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          mode: all
          days: 90
    zones:
      Front_Door:
        coordinates: 
          0.455,0.038,0.571,0.039,0.602,0.356,1,0.378,1,1,0.267,0.997,0.306,0.538,0.355,0.64,0.398,0.637,0.405,0.531
        objects: person
        filters:
          person:
            min_score: 0.75
            threshold: 0.75
            min_area: 150000
    review:
      detections:
        required_zones: Front_Door
      alerts:
        labels: []
  camera3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera3
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      enabled: true
    record:
      enabled: true
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          mode: all
          days: 90
    zones:
      Drive_Way:
        coordinates: 0.249,1,0.683,1,0.603,0.397,0.349,0.38
        loitering_time: 2
        objects: car
      Side_Yard:
        coordinates: 0.076,0.392,0.353,0.377,1,0.428,1,1,0,1,0,0.393
        objects: person
        loitering_time: 4
        filters:
          person:
            min_area: 150000
            max_area: 300000
    review:
      detections:
        required_zones:
          - Drive_Way
          - Side_Yard
      alerts:
        labels: []
  camera4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      enabled: true
    record:
      enabled: true
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          mode: all
          days: 90
    zones:
      Garage:
        coordinates: 0,0,1,0,1,1,0,1
        objects: person
        filters:
          person:
            min_area: 50000
    review:
      detections:
        required_zones: Garage
      alerts:
        labels: []

detect:
  enabled: true
  fps: 10
  stationary:
    interval: 10
    threshold: 50

objects:
  track:
    - person

version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral
