### DISCUSSION TITLE
[Config Support]: 2-way audio on new Reolink Doorbell (D340W) only sending one way

### DISCUSSION THREAD

**Discussion by lucasballr** [blakeblackshear/frigate#17604] [Config Support] [answered]
### Describe the problem you are having

I'm working on getting 2-way audio functioning in frigate using my Reolink doorbell (D340W) and I've almost solved it using various configurations I've found online. The only issue is when I select the mic icon on the video feed, it cuts out the audio from the doorbell. I did a voice test (muting my computer mic) and nothing came through. When I deselect the mic icon, the audio comes through (My understanding is 2-way mode puts a filter to filter out background noise). For now, the audio will come through both ways, but not at the same time. I have to toggle the mic on and off to switch directions.

I saw that [last year](https://github.com/blakeblackshear/frigate/discussions/10595) there was a FW update that broke the 2-way audio, but this was before the D340W version from my understanding, so I don't think the super old FW is compatible with my model.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
go2rtc:
      webrtc:
        listen: ":8555"
        candidates:
          - <FRIGATE_IP>:8555
          - stun:8555
      streams:
        doorbell:
          - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@<REOLINK_IP>:554/
          - ffmpeg:http://<REOLINK_IP>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#audio=opus#audio=volume
        doorbell_sub:
          - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@<REOLINK_IP>:554/h264Preview_01_sub
          - ffmpeg:http://<REOLINK_IP>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}#audio=opus#audio=volume
      ffmpeg:
        bin: ffmpeg
        volume: -af "volume=25dB"
    
cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
    onvif:
      host: <REOLINK_IP>
      port: 80
      user: admin
      password: ${FRIGATE_RTSP_PASSWORD}
```

### Relevant Frigate log output

```shell
There aren't any relevant logs that I can tell.
```

### Relevant go2rtc log output

```shell
I'm not sure how to find this. I was directed to <frigate_IP>:1984 but that port is blocked.
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config:/config
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
```

### Object Detector

Coral
