### DISCUSSION TITLE
Detection snapshots for cars always display my neighbors car

### DISCUSSION THREAD

**Discussion by mbieser** [blakeblackshear/frigate#17617] [General Support]
### Describe the problem you are having

When a car is detected, the snapshot for the event usually shows my neighbor's car across the street. I have masked out the neighbor's cars in the UI, but this mask seems to be ignored when frigate computes the still to use for the snapshot.

### Version

0.15.0-cea210d

### What browser(s) are you using?

Firefox 115.22.0esr 

### Frigate config file

```yaml
n/a
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

amcrest

### Screenshots of the Frigate UI's System metrics pages

![Screenshot_20250409-120057](https://github.com/user-attachments/assets/fb0b4e14-5df7-4b10-9fe8-ef7d5714db63)
<img width="1403" alt="Screen Shot 2025-04-09 at 12 22 13 PM" src="https://github.com/user-attachments/assets/ac9b596a-325c-4ad7-85e6-f3eb8ada4ca1" />

**Comment by NickM-27** [comment]
there is no way to help without seeing your config

**Reply by mbieser** [reply]
posted. thanks

**Comment by hawkeye217** [comment]
One important thing to note is that masks are always based on the bottom center of your object's bounding box. Object masks typically do not need to be large, but they do need to cover the bottom center of any bounding box.

https://docs.frigate.video/configuration/masks/#object-filter-masks

**Comment by mbieser** [comment]
Here's the config yml:
```
auth:
  enabled: True
  reset_admin_password: True

tls:
  enabled: False

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb  # Use 'usb' for a USB Coral TPU or 'pci' for a PCIe version

record:
  enabled: true
  retain:
    days: 7  # Keep recordings for days
  alerts:
    pre_capture: 20
    post_capture: 20
    retain:
      days: 14
  detections:
    pre_capture: 15
    post_capture: 15
    retain:
      days: 14


snapshots:
  enabled: true
  timestamp: true
  retain:
    default: 10  # Keep snapshots for 10 days
  quality: 100


cameras:
  lpr_street:
    ffmpeg:
      inputs:
        - path: rtsp://<MASKED>
          roles:
            - detect
    detect:
      width: 2960  # Adjust to your camera's resolution
      height: 1668
      fps: 20  # Lower FPS helps with CPU usage


    objects:
      track:
        - person
        - car
        - license_plate
      filters:
        person:
          min_score: 0.5  # Lower if necessary
        car:
          min_score: 0.4  # Lower if necessary

      mask:
        - 0.839,0.062,0.839,0.082,0.839,0.084,0.96,0.086,0.96,0.039,0.84,0.039,0.828,0.04
        - 0,0.378,0.218,0.385,0.226,0.18,0.116,0.109,0,0.047
        - 0.55,0.093,0.527,0.143,0.567,0.23,0.696,0.268,0.735,0.138,0.654,0.104
    motion:
      threshold: 43   # More sensitive to changes
      contour_area: 10
      improve_contrast: true
      delta_alpha: 0.5

  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://<MASKED>
          roles:
            - detect
    detect:
      width: 1920  # Adjust to your camera's resolution
      height: 1080
      fps: 10  # Lower FPS helps with CPU usage


    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.5  # Lower if necessary
        car:
          min_score: 0.4  # Lower if necessary

      mask:
        - 0.684,0.043,0.684,0.079,0.705,0.088,0.839,0.086,0.965,0.084,0.966,0.039
        - 0.002,0.713,0.042,0.761,0.065,0.819,0.091,0.921,0.101,0.987,0.05,0.998,0.004,0.996,0.005,0.882,0.005,0.788
        - 1,0.624,1,0.496,0.874,0.393,0.842,0.382,0.826,0.461,0.858,0.483,0.897,0.519
        - 0.158,0.695,0.164,0.474,0.036,0.341,0.018,0.393,0.079,0.519
        - 0.017,0.75,0.059,0.829,0.094,0.932,0.144,0.93,0.18,1,0.029,0.995,0.007,0.842
    motion:
      threshold: 34   # More sensitive to changes
      contour_area: 30
      improve_contrast: true
      delta_alpha: 0.5
    zones:
      stairs:
        coordinates:
          0,0.368,0,0.314,0.075,0.149,0.199,0.259,0.306,0.388,0.545,0.399,0.562,0.589,0.602,0.517,0.588,0.422,0.54,0.384,0.465,0.251,0.475,0.183,0.678,0.343,0.716,0.336,0.718,0.533,0.724,0.716,0.701,1,0.243,0.727,0.031,0.418
        loitering_time: 0
        objects: person
live:
  height: 1080  # Scale live view to reduce CPU usage
  quality: 1

version: 0.15-1
```
