### DISCUSSION TITLE
[HW Accel Support]: 0.15.0 seems to break hwaccel for J3455 Intel CPU

### DISCUSSION THREAD

**Discussion by wingkinl** [blakeblackshear/frigate#17625] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I forgot the original version of my frigate before updating it to 0.15.0 (I updated it using docker-compose pull & docker-compose up -d), but it used to be working fine. After the upgrade, it keeps stopping when I start it. If I remove the detectors and the model section from the config, then it can be started but hwaccel seems to be not working at all (CPU usage takes 74%+).

### Version

0.15.0

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.3.2
  port: 31883
  client_id: frigate
  topic_prefix: frigate

detectors:
  J3455:
    type: openvino
    device: AUTO

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  outdoor:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.3.111:554/stream1
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440
      fps: 5
    snapshots: # <----- Enable snapshots
      enabled: true
    onvif:
      host: 192.168.3.111
      port: 2020
      user: admin
      password: *

    motion:
      mask:
        - 1376,87,1356,151,1035,145,1019,87
record: # <----- Enable recording
  enabled: true
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 60
  detections:
    retain:
      days: 60
objects:
  track:
    - person
    # - bicycle
    # - car
    # - motorcycle
    # - cat
    # - dog


environment_vars:
  LIBVA_DRIVER_NAME: i965
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11  # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /volume2/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "25000:5000"
      - "21935:1935" # RTMP feeds
      - "28554:8554" # RTSP feeds
      - "28555:8555/tcp" # WebRTC over tcp
      - "28555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: "i965" # if hwacl isn't working properly with the default iHD driver
      TZ: "Asia/Shanghai"
```

### Relevant Frigate log output

```shell
Starting frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service certsync-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service certsync-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | [WARN] /sys/fs/cgroup/cpu/cpu.cfs_quota_us or /sys/fs/cgroup/cpu/cpu.cfs_period_us not found. Falling back to /proc/cpuinfo.
frigate    | 2025-04-10 16:16:12.740137734  [INFO] Starting NGINX...
frigate    | 2025-04-10 16:16:12.740135948  [INFO] Preparing new go2rtc config...
frigate    | 2025-04-10 16:16:12.740300531  [INFO] Preparing Frigate...
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service certsync: starting
frigate    | s6-rc: info: service certsync successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2025-04-10 16:16:15.802111397  [INFO] Starting certsync...
frigate    | 2025-04-10 16:16:15.819539999  [INFO] Starting Frigate...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2025-04-10 16:16:16.170030642  127.0.0.1 - - [10/Apr/2025:16:16:16 +0800] "" 400 0 "-" "-" "-"
frigate    | 2025-04-10 16:16:19.431891739  2025/04/10 16:16:19 [error] 163#163: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.3.2, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "192.168.3.2:25000"
frigate    | 2025-04-10 16:16:19.433762697  2025/04/10 16:16:19 [error] 163#163: *2 auth request unexpected status: 502 while sending to client, client: 192.168.3.2, server: , request: "GET /api/stats HTTP/1.1", host: "192.168.3.2:25000"
frigate    | 2025-04-10 16:16:19.531678833  [INFO] Starting go2rtc...
frigate    | 2025-04-10 16:16:19.863487004  16:16:19.863 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate    | 2025-04-10 16:16:19.863943554  16:16:19.863 INF config path=/dev/shm/go2rtc.yaml
frigate    | 2025-04-10 16:16:19.864800215  16:16:19.864 INF [rtsp] listen addr=:8554
frigate    | 2025-04-10 16:16:19.865988331  16:16:19.865 INF [webrtc] listen addr=:8555/tcp
frigate    | 2025-04-10 16:16:19.867331560  16:16:19.867 INF [api] listen addr=:1984
frigate    | 2025-04-10 16:16:22.735746638  [INFO] Starting go2rtc healthcheck service...
frigate    | 2025-04-10 16:16:24.672834986  2025/04/10 16:16:24 [error] 161#161: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate    | 2025-04-10 16:16:24.672881365  2025/04/10 16:16:24 [error] 161#161: *4 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate    | 2025-04-10 16:16:36.822634528  [2025-04-10 16:16:36] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate    | 2025-04-10 16:16:36.886795240  [2025-04-10 16:16:36] frigate.util.config            INFO    : frigate config does not need migration...
frigate    | 2025-04-10 16:16:36.978189535  [2025-04-10 16:16:36] frigate.app                    INFO    : Starting Frigate (0.15.0-cea210d)
frigate    | 2025-04-10 16:16:37.014896488  [2025-04-10 16:16:37] peewee_migrate.logs            INFO    : Starting migrations
frigate    | 2025-04-10 16:16:37.016589495  [2025-04-10 16:16:37] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate    | 2025-04-10 16:16:38.079044238  [2025-04-10 16:16:38] frigate.app                    INFO    : Recording process started: 356
frigate    | 2025-04-10 16:16:38.080362526  [2025-04-10 16:16:38] frigate.app                    INFO    : Review process started: 357
frigate    | 2025-04-10 16:16:38.089495890  [2025-04-10 16:16:38] frigate.app                    INFO    : go2rtc process pid: 110
frigate    | 2025-04-10 16:16:38.116345935  [2025-04-10 16:16:38] detector.J3455                 INFO    : Starting detection process: 372
frigate    | 2025-04-10 16:16:38.140922695  [2025-04-10 16:16:38] frigate.app                    INFO    : Output process started: 388
frigate    | 2025-04-10 16:16:38.184170152  [2025-04-10 16:16:38] frigate.app                    INFO    : Camera processor started for outdoor: 402
frigate    | 2025-04-10 16:16:38.197436105  [2025-04-10 16:16:38] frigate.app                    INFO    : Capture process started for outdoor: 403
frigate    | 2025-04-10 16:16:39.103379032  [2025-04-10 16:16:39] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate    | 2025-04-10 16:16:40.003794047  2025/04/10 16:16:40 [error] 163#163: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigate    | 2025-04-10 16:16:40.003840712  2025/04/10 16:16:40 [error] 163#163: *6 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigate    | 2025-04-10 16:16:40.302433415  [2025-04-10 16:16:40] frigate.api.fastapi_app        INFO    : FastAPI started
frigate    | 2025-04-10 16:16:42.595904337  Fatal Python error: Illegal instruction
frigate    | 2025-04-10 16:16:42.595913211
frigate    | 2025-04-10 16:16:42.595916325  Thread 0x00007fe49e8e86c0 (most recent call first):
frigate    | 2025-04-10 16:16:42.595960831    File "/usr/lib/python3.9/threading.py", line 312 in wait
frigate    | 2025-04-10 16:16:42.595980634    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
frigate    | 2025-04-10 16:16:42.596016023    File "/usr/lib/python3.9/threading.py", line 892 in run
frigate    | 2025-04-10 16:16:42.596066304    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
frigate    | 2025-04-10 16:16:42.596109576    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
frigate    | 2025-04-10 16:16:42.596112160
frigate    | 2025-04-10 16:16:42.596131443  Current thread 0x00007fe4d2807740 (most recent call first):
frigate    | 2025-04-10 16:16:42.597251971    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 543 in compile_model
frigate    | 2025-04-10 16:16:42.597261834    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 40 in __init__
frigate    | 2025-04-10 16:16:42.597272318    File "/opt/frigate/frigate/detectors/__init__.py", line 18 in create_detector
frigate    | 2025-04-10 16:16:42.597277286    File "/opt/frigate/frigate/object_detection.py", line 68 in __init__
frigate    | 2025-04-10 16:16:42.597298890    File "/opt/frigate/frigate/object_detection.py", line 121 in run_detector
frigate    | 2025-04-10 16:16:42.597303193    File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
frigate    | 2025-04-10 16:16:42.597307289    File "/opt/frigate/frigate/util/process.py", line 41 in run_wrapper
frigate    | 2025-04-10 16:16:42.597310756    File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
frigate    | 2025-04-10 16:16:42.597314732    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
frigate    | 2025-04-10 16:16:42.597317842    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
frigate    | 2025-04-10 16:16:42.597345200    File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
frigate    | 2025-04-10 16:16:42.597348951    File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
frigate    | 2025-04-10 16:16:42.597364725    File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
frigate    | 2025-04-10 16:16:42.597368377    File "/opt/frigate/frigate/util/process.py", line 30 in start
frigate    | 2025-04-10 16:16:42.597371763    File "/opt/frigate/frigate/object_detection.py", line 204 in start_or_restart
frigate    | 2025-04-10 16:16:42.597374682    File "/opt/frigate/frigate/object_detection.py", line 172 in __init__
frigate    | 2025-04-10 16:16:42.597377684    File "/opt/frigate/frigate/app.py", line 350 in start_detectors
frigate    | 2025-04-10 16:16:42.597380464    File "/opt/frigate/frigate/app.py", line 598 in start
frigate    | 2025-04-10 16:16:42.597383240    File "/opt/frigate/frigate/__main__.py", line 60 in main
frigate    | 2025-04-10 16:16:42.597399616    File "/opt/frigate/frigate/__main__.py", line 64 in <module>
frigate    | 2025-04-10 16:16:42.597403078    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
frigate    | 2025-04-10 16:16:42.597405978    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
frigate    | 2025-04-10 16:16:59.096386675  [2025-04-10 16:16:59] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | s6-rc: info: service certsync: stopping
frigate    | 2025-04-10 16:16:59.129847769  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2025-04-10 16:16:59.142105039  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate    | s6-rc: info: service certsync successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service certsync-log: stopping
frigate    | s6-rc: info: service certsync-log successfully stopped
frigate    | 2025-04-10 16:16:59.191838571  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | 2025-04-10 16:16:59.382290601  [2025-04-10 16:16:59] frigate.app                    INFO    : Stopping...
frigate    | 2025-04-10 16:16:59.384824626  [2025-04-10 16:16:59] frigate.watchdog               INFO    : Exiting watchdog...
frigate    | 2025-04-10 16:16:59.387912935  [2025-04-10 16:16:59] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate    | 2025-04-10 16:16:59.389352865  [2025-04-10 16:16:59] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate    | 2025-04-10 16:16:59.389824982  [2025-04-10 16:16:59] frigate.stats.emitter          INFO    : Exiting stats emitter...
frigate    | 2025-04-10 16:16:59.389834321  [2025-04-10 16:16:59] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate    | 2025-04-10 16:16:59.390293836  [2025-04-10 16:16:59] frigate.storage                INFO    : Exiting storage maintainer...
frigate    | 2025-04-10 16:16:59.391164811  [2025-04-10 16:16:59] watchdog.outdoor               INFO    : Terminating the existing ffmpeg process...
frigate    | 2025-04-10 16:16:59.391807665  [2025-04-10 16:16:59] watchdog.outdoor               INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | 2025-04-10 16:16:59.391818852  [2025-04-10 16:16:59] frigate.app                    INFO    : Waiting for capture process for outdoor to stop
frigate    | 2025-04-10 16:16:59.761290405  [2025-04-10 16:16:59] frigate.app                    INFO    : Waiting for process for outdoor to stop
frigate    | 2025-04-10 16:17:00.111319830  [2025-04-10 16:17:00] frigate.events.maintainer      INFO    : Exiting event processor...
frigate    | 2025-04-10 16:17:00.206720791  [2025-04-10 16:17:00] frigate.object_processing      INFO    : Exiting object processor...
frigate    | 2025-04-10 16:17:00.910359420  [2025-04-10 16:17:00] frigate.video                  INFO    : outdoor: emptying frame queue
frigate    | 2025-04-10 16:17:00.912147356  [2025-04-10 16:17:00] frigate.video                  INFO    : outdoor: exiting subprocess
frigate    | 2025-04-10 16:17:00.922911222  [2025-04-10 16:17:00] frigate.app                    INFO    : Closing frame queue for outdoor
frigate    | 2025-04-10 16:17:01.925199067  [2025-04-10 16:17:01] frigate.app                    INFO    : Detection queue closed
frigate    | 2025-04-10 16:17:02.426520661  [2025-04-10 16:17:02] frigate.app                    INFO    : Detected frames queue closed
frigate    | 2025-04-10 16:17:02.927487092  [2025-04-10 16:17:02] frigate.app                    INFO    : Timeline queue closed
frigate    | 2025-04-10 16:18:59.312604979  [INFO] Service Frigate exited with code 256 (by signal 9)
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | 2025-04-10 16:18:59.318023541  exit with signal: terminated
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | 2025-04-10 16:18:59.327056526  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

TP-Link TL-IPC48AW-PLUS

### Screenshots of the Frigate UI's System metrics pages

none
