### DISCUSSION TITLE
[HW Accel Support]: Multiple AMD GPUs - how to configure

### DISCUSSION THREAD

**Discussion by phedders** [blakeblackshear/frigate#17626] [Hardware Acceleration Support]
### Describe the problem you are having

I have two (older) Firepro cards in a server and I want Frigate to use both of them. I can see the documentation for how to configure multiple nvidia cards - but not for anything else. Is it possible? 

(Apologies in advance if I have missed the obvious...)

### Version

3d2bfa3-amd64

### Frigate config file

```yaml
auth:
  enabled: true


mqtt:
  host: X
  user: X
  password: X
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

      #ffmpeg:
      #hwaccel_args: preset-vaapi

objects:
  track:
    - person
    - car
    - bicycle
    - cat
    - dog
    - bird

record:
  enabled: true
  retain:
    days: 10
    mode: motion

semantic_search:
  enabled: true
  reindex: false
  model_size: small

birdseye:
  enabled: true
  mode: motion
  quality: 1
  restream: true
  width: 1920
  height: 1080

timestamp_style:
  position: br
  format: '%Y%m%d-%H%M%S'

logger:
  default: info
  logs:
    frigate.mqtt: error

go2rtc:
  rtsp:
    listen: :8554      # RTSP Server TCP port, default - 8554
  streams:
    181drive:
      - rtsp://X:554/s0
    181drive_sub:
      - rtsp://X:554/s2
    181truss1:
      - rtsp://X:554/s0
    181truss1_sub:
      - rtsp://X:554/s2

    181plantroom:
      - rtsp://X:554/s0
    181plantroom_sub:
      - rtsp://X:554/s2

    181caferoad:
      - rtsp://X:554/s0
    181caferoad_sub:
      - rtsp://X:554/s2

    181cafedrive:
      - rtsp://X:554/s0
    181cafedrive_sub:
      - rtsp://X:554/s2

    181carpark1:
      - rtsp://X:554/s0
    181carpark1_sub:
      - rtsp://X:554/s2

    181carpark2:
      - rtsp://X:554/s0
    181carpark2_sub:
      - rtsp://X:554/s2

    181trussWide:
      - rtsp://X:554/avstream/channel=1/stream=0.sdp
    181trussWide_sub:
      - rtsp://X:554/avstream/channel=1/stream=1.sdp

  webrtc:
    webrtc:
      listen: :8555
    candidates:
      - X:8555
      - stun:8555

cameras:

  181carpark1:
    ffmpeg:
      global_args: -hide_banner -loglevel warning -threads 2 -hwaccel_device 0
      inputs:
        - path: rtsp://127.0.0.1:8554/181carpark1
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181carpark1_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false
    motion:
      mask:
        - 301,35,310,0,0,0,0,33

      threshold: 30
      contour_area: 22
      improve_contrast: true
  181carpark2:
    ffmpeg:
      global_args: -hide_banner -loglevel warning -threads 2 -hwaccel_device 2
      inputs:
        - path: rtsp://127.0.0.1:8554/181carpark2
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181carpark2_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false
    motion:
      mask:
        - 301,35,310,0,0,0,0,33
        - 781,0,730,101,250,106,240,89,0,76,0,0

    zones:
      cp2disabledSlots:
        coordinates: 512,758,0,984,0,719,269,620
      cp2gate:
        coordinates: 1343,419,849,276,379,465,806,698
      cp2heathRoad:
        coordinates: 30,230,30,177,623,247,315,326
      cp2roadway:
        coordinates: 1213,1080,0,1080,0,1010,1895,240,1897,575
      cp2staffSlots:
        coordinates: 0,457,0,280,21,275,167,416
      cp2topSlots:
        coordinates: 1746,117,1920,136,1920,224,1436,392,1034,300

  181cafedrive:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/181cafedrive
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181cafedrive_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false

    motion:
      mask: 0,0.033,0.156,0.035,0.155,0.003,0.001,0.002
    lpr:
      enabled: true

  181caferoad:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/181caferoad
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181caferoad_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false
    motion:
      mask: 0.05,0.108,0.117,0.176,0.17,0.124,0.047,0.223,0.033,0.162
    lpr:
      enabled: true

  181drive:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/181drive
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181drive_sub
          roles:
            - detect
      output_args:
       record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false
    motion:
      mask:
        - 301,35,310,0,0,0,0,33

  181plantroom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/181plantroom
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181plantroom_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false
    motion:
      mask:
        - 301,35,310,0,0,0,0,33
    lpr:
      enabled: true

  181truss1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/181truss1
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181truss1_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c copy
    detect:
      width: 1920
      height: 1080
    record:
      enabled: true
    snapshots:
      enabled: true
    mqtt:
      enabled: false
    motion:
      mask:
        - 301,35,310,0,0,0,0,33
    lpr:
      enabled: true


  181trussWide:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/181trussWide
          hwaccel_args: preset-vaapi
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/181trussWide_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 576
      fps: 5
    record:
      enabled: true
        #width: 2304
        #height: 1296
        #fps: 25
    snapshots:
      enabled: true
    motion:
      mask:
        - 301,35,310,0,0,0,0,33
    lpr:
      enabled: true


camera_groups:
  All-Hall:
    order: 1
    icon: LuStarOff
    cameras:
      - birdseye
      - 181cafedrive
      - 181caferoad
      - 181carpark1
      - 181carpark2
      - 181drive
      - 181plantroom
  External:
    order: 2
    icon: LuCar
    cameras:
      - 181drive
      - 181carpark1
      - 181plantroom
      - 181carpark2
  Internal:
    order: 3
    icon: LuBuilding
    cameras:
      - 181truss1
      - 181trussWide
      - 181cafedrive
      - 181caferoad
  Cafe:
    order: 4
    icon: LuCoffee
    cameras:
      - 181cafedrive
      - 181caferoad


  Birdy:
    order: 5
    icon: LuEye
    cameras: birdseye
version: 0.16-0
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:${V}
    deploy:
      resources:
        limits:
          cpus: "14"
          memory: "20g"
    shm_size: "1024mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config/:rw
      - /srv/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "1936:1935" # RTMP feeds
      - "8554:8554" # go2rtc
      - "8555:8555" # webrtc
    environment:
     - LIBVA_DRIVER_NAME=radeonsi
```

### Relevant Frigate log output

```shell
--
```

### Relevant go2rtc log output

```shell
--
```

### FFprobe output from your camera

```shell
--
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Ubiquiti G3* / Reolink *

### Screenshots of the Frigate UI's System metrics pages

--
