### DISCUSSION TITLE
[Support]: Corrupted recordings preventing alerts from being reviewed

### DISCUSSION THREAD

**Discussion by ozhound** [blakeblackshear/frigate#17646] [General Support] [answered]
### Describe the problem you are having

Hi I don't know how to really describe this, but my recordings are corrupted maybe for 20 seconds every time frigate generates an alert.

I see the alert on the homepage, I click on it, which goes to the reviews page. But the timestamp that it navigates to automatically simply shows the low resolution preview screen with a spinning loading circle, which never loads. If I drag the slider back maybe a few minutes then the video will play from that point, but when it hits the timestamp of the alert it freezes again. If I use the slider and go into the future by a few minutes, the video continues to play. This results in missing the most important part of the stream, where something is actually happened. 

If I export a video over this time. It's fine and playback is perfect, however, having to do this to look at the video every time is tiresome.

There are no associated errors in the log that any of these times.

### Version

0.15.0-cea210d

### What browser(s) are you using?

All browser, including Mobile Chrome has this issue

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.25
  user: 
  password: 
go2rtc:
  streams:
    Driveway:
      - tapo://x@192.168.1.193
      - ffmpeg:backyard#audio=aac
    FrontCourtyard:
      - tapo://x@192.168.1.194
      - ffmpeg:backyard#audio=aac
    Laundry:
      - tapo://x@192.168.1.191
    MasterBed:
      - tapo://x@192.168.1.192
      - ffmpeg:backyard#audio=aac
    backyard:
      - tapo://x@192.168.1.190
      - ffmpeg:backyard#audio=aac
audio:
  enabled: false
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  height: 250
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
  quality: 100
record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 2
      mode: motion
  detections:
    pre_capture: 10
    post_capture: 10
    retain:
      days: 10
      mode: active_objects
  preview:
      # Options are: very_low, low, medium, high, very_high
    quality: low
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
cameras:
  Driveway: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      stationary:
        interval: 50
        threshold: 50
      enabled: true
      width: 1280
      height: 720
      fps: 5
      annotation_offset: -1800
    motion:
      mask: 0.001,0.049,0.362,0.046,0.36,0.002,0,0
      threshold: 20
      contour_area: 10
      improve_contrast: true
    objects:
      track:
        - person
        - car
        - bird
        - airplane
        - bicycle
        - motorcycle
        - bus
        - cat
        - dog
        - cell phone
        - package
        - truck
      filters:
        car: {}
        person: {}
    zones:
      Entryway:
        coordinates: 
          0.844,0.252,0.961,0.328,0.906,0.668,0.934,0.691,0.872,1,0.591,1,0.819,0.594,0.654,0.462,0.693,0.429,0.704,0.329
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - package
          - dog
          - cat
      MainDriveway:
        coordinates: 
          0.612,0.434,0.936,0.69,0.873,1,0.004,0.999,0,0.407,0.07,0.374,0.143,0.347,0.252,0.312,0.401,0.274,0.407,0.3,0.458,0.343,0.514,0.374
        loitering_time: 3
        inertia: 3
      Roadway:
        coordinates: 
          0,0.406,0.18,0.334,0.407,0.269,0.431,0.26,0.664,0.222,0.669,0.177,0.571,0.17,0.374,0.179,0.201,0.203,0.083,0.215,0,0.248
        loitering_time: 0
        inertia: 3
      Bus_Stop:
        coordinates: 0.496,0.001,0.492,0.153,0.652,0.158,0.654,0.083,0.6,0.098,0.606,0
        loitering_time: 5
        objects: person
        inertia: 3
      Henley:
        coordinates: 
          0,0,0.232,0,0.49,0.003,0.638,0,0.829,0.166,0.493,0.124,0.491,0.14,0.345,0.143,0.204,0.159,0,0.219
        loitering_time: 10
        inertia: 3
      Grass:
        coordinates: 
          0.685,0.272,0.652,0.293,0.638,0.381,0.637,0.415,0.674,0.44,0.65,0.463,0.611,0.428,0.461,0.34,0.409,0.304,0.401,0.273,0.52,0.239,0.663,0.223
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones:
          - Entryway
          - MainDriveway
      detections:
        required_zones:
          - Entryway
          - MainDriveway
          - Roadway
          - Grass
  FrontCourtyard: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontCourtyard?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
      annotation_offset: 8000
    objects:
      track:
        - person
        - car
        - bird
        - airplane
        - bicycle
        - motorcycle
        - cat
        - dog
        - cell phone
        - package
        - truck
#    motion:
#      mask:
#        - 0.001,0.001,0.357,0,0.356,0.05,0.002,0.042
#       - 0.054,0.117,0.052,0.039,0.106,0.043,0.121,0.212,0.133,0.307,0.107,0.36,0.091,0.424,0.047,0.419,0.044,0.233
#      threshold: 30
#      contour_area: 30
#    objects:
#      filters:
#        person:
#          mask: 
#            0,0.043,0.156,0.048,0.165,0.4,0.104,0.426,0.111,0.511,0.102,0.517,0.09,0.433,0.001,0.44
#    zones:
#      All:
#        coordinates: 0.163,0.184,0.579,0.119,0.995,0.143,0.995,0.99,0.008,0.994,0.01,0.192
#        loitering_time: 0
    zones:
      Walkway:
        coordinates: 
          0.396,0.288,0.308,0.285,0.296,0.044,0.253,0.045,0.245,0.533,0.143,0.994,0.515,1,0.475,0.397,0.469,0.295
        loitering_time: 0
        inertia: 3
        objects:
          - package
          - cell phone
          - dog
          - cat
          - bird
          - bicycle
          - person
      Window:
        coordinates: 
          0.242,0.538,0.25,0.047,0.094,0.101,0.093,0.295,0.102,0.517,0.146,0.88,0.163,0.905
        loitering_time: 0
        inertia: 3
        objects: person
      Foilage:
        coordinates: 
          0.47,0.296,0.521,0.195,0.591,0.145,0.664,0.196,0.726,0.36,0.796,0.451,0.906,0.597,1,0.735,0.999,1,0.653,1
        loitering_time: 5
      Henley:
        coordinates: 0.492,0.045,0.467,0.046,0.47,0.101,0.773,0.251,0.815,0.209,0.515,0.049
        loitering_time: 0
    motion:
      mask: 0.36,0.045,0,0.047,0,0.004,0.358,0.006
      threshold: 30
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones:
          - Walkway
          - Window
          - Foilage
      detections:
        required_zones: Henley
  backyard: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    zones:
      Lawn:
        coordinates: 
          0.544,0.475,0.485,0.575,0.201,0.607,0.008,0.82,0,1,0.999,0.994,0.922,0.832,0.898,0.623,0.781,0.485
        loitering_time: 0
        inertia: 3
      Foliage:
        coordinates: 
          0.801,0.2,0.752,0.088,0.744,0,0.693,0.01,0,0,0,0.823,0.204,0.603,0.485,0.571,0.546,0.469,0.779,0.491
        loitering_time: 0
        objects: person
        inertia: 3
      Carport:
        coordinates: 0.803,0.197,0.901,0.262,0.899,0.622,0.786,0.486
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.003,0.084,0.17,0.082,0.172,0.038,0.354,0.05,0.35,0,0.001,0.001
      threshold: 40
      contour_area: 20
      improve_contrast: true
    objects:
      mask:
        - 0.145,0.402,0.151,0.527,0.199,0.523,0.192,0.393
        - 0.379,0.334,0.407,0.337,0.404,0.408,0.379,0.401
      filters:
        person:
          mask:
            - 0.608,0.31,0.574,0.421,0.636,0.424,0.632,0.319
            - 0.379,0.334,0.407,0.337,0.401,0.49,0.367,0.494
            - 0.145,0.402,0.151,0.527,0.199,0.523,0.192,0.393
            - 0.379,0.334,0.407,0.337,0.404,0.408,0.379,0.401
  Laundry: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Laundry?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
      annotation_offset: 4550
    motion:
      mask: 0.001,0.049,0.362,0.046,0.36,0.002,0,0
      threshold: 40
      contour_area: 30
      improve_contrast: true
    zones:
      All:
        coordinates: 0.001,0.313,0.613,0.01,0.917,0.014,0.997,0.018,0.997,0.986,0.009,0.984
        loitering_time: 0
    objects:
      filters:
        person: {}
  MasterBed: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/MasterBed?video&audio # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 0.001,0.001,0.357,0,0.356,0.05,0.002,0.042
        - 0.054,0.117,0.052,0.039,0.106,0.043,0.121,0.212,0.133,0.307,0.107,0.36,0.091,0.424,0.047,0.419,0.044,0.233
      threshold: 30
      contour_area: 30
    objects:
      filters:
        person:
          mask: 
            0,0.043,0.156,0.048,0.165,0.4,0.104,0.426,0.111,0.511,0.102,0.517,0.09,0.433,0.001,0.44
      mask: 0,0.778,0,1,0.262,1,0.245,0.88
    zones:
      All:
        coordinates: 0.163,0.184,0.579,0.119,0.995,0.143,0.995,0.99,0.008,0.994,0.01,0.192
        loitering_time: 0
detectors:
  coral:
    type: edgetpu
    device: usb
#detectors:
#  ov:
#    type: openvino
#    device: CPU
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
#version: 0.15-1
#semantic_search:
#  enabled: false
#  reindex: false
#  model_size: small
version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
No log entries during these events
```

### Relevant go2rtc log output

```shell
No log entries during these events
```

### FFprobe output from your camera

```shell
ffprobe not installed?
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/frigate:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Object Detector

Coral

### Network connection

Mixed

### Camera make and model

TPlink CW320

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/7179e43c-0b43-42e5-b47a-0c8b548c8c45)

**Comment by hawkeye217** [comment]
Most of your go2rtc streams are incorrectly referring to the `backyard` camera in the audio transcode. You need to match the camera names appropriately, eg:

```
go2rtc:
  streams:
    Driveway:
      - tapo://x@192.168.1.193
      - ffmpeg:Driveway#audio=aac
    FrontCourtyard:
      - tapo://x@192.168.1.194
      - ffmpeg:FrontCourtyard#audio=aac
    Laundry:
      - tapo://x@192.168.1.191
    MasterBed:
      - tapo://x@192.168.1.192
      - ffmpeg:MasterBed#audio=aac
    backyard:
      - tapo://x@192.168.1.190
      - ffmpeg:backyard#audio=aac
```

Additionally, if the `tapo:` protocol does not produce h264/5 video, you will need to transcode video as well. I'm just not familiar with how that protocol works.
