### DISCUSSION TITLE
[Config Support]: Two-way audio in Frigate card when accessing via Home Assistant Cloudflare Tunnelling

### DISCUSSION THREAD

**Discussion by junxulai** [blakeblackshear/frigate#17643] [Config Support]
### Describe the problem you are having

I have configured WebRTC and can enable two-way audio in either Frigate web interface or in HA using Frigate card, but only for local access. When accessing HA locally, the microphone icon can be seen, and two-way audio is working
![local access](https://github.com/user-attachments/assets/420794dd-5dad-4fa6-95ef-fd8d221313dc)

I am accessing my HA via Cloudflare tunnel when I am away. My HA and Frigate instances are behind CGNAT, so I have also configured ngrok as suggested, and I can confirm from ngrok dashboard that the tunneling is online.
![ngrok](https://github.com/user-attachments/assets/e2703dc6-5823-4a58-8f52-af8e0c292ba7)

However, when I set up ngrok, the microphone icon won't show up for external access, and the video keeps loading. Can anyone help with this?
![external access](https://github.com/user-attachments/assets/40862d87-6e92-43a7-8d79-290794bf1a5a)

### Version

0.14

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.50.37         # YOUR MQTT IP
  port: 1883
  user: user               # YOUR MQTT USERNAME
  password: password        # YOUT MQTT PASSWORD
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

go2rtc:
  ngrok:
    command: /config/ngrok tcp 8555 --authtoken xxxx
  streams:
    hallway:
      - rtsp://admin:password@192.168.50.87:554/h264Preview_01_main
    hallway_sub:
      - rtsp://admin:password@192.168.50.87:554/h264Preview_01_sub
  webrtc:
    listen: ":8555"
    candidates:
      - 192.168.50.37:8555
      - stun: 8555

cameras:
  hallway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hallway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/hallway_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.50.87
      port: 8000
      user: admin
      password: password
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 7
    motion:
       enabled: true

record:
  enabled: True
  retain:
    days: 10
    mode: all

objects:
  track:
    - person
    - cat
    - door
  filters:
    person:
      min_area: 5000
      min_score: 0.5
      threshold: 0.6
    cat:
      min_area: 5000
      min_score: 0.5
      threshold: 0.6

snapshots:
  enabled: True
  timestamp: true
  retain:
    default: 14

version: 0.14
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ssd/config:/config
      - /mnt/ssd/clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

OpenVino

### Any other information that may be helpful

My Frigate card configuration is:

type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.hallway
    live_provider: go2rtc
    go2rtc:
      modes:
        - webrtc
live:
  controls:
    ptz:
      mode: "on"
  microphone:
    always_connected: false
menu:
  style: outside
  buttons:
    microphone:
      enabled: true
    media_player:
      enabled: false
