### DISCUSSION TITLE
Record alerts and detections not allowed [Config Support]:

### DISCUSSION THREAD

**Discussion by Floriszz** [blakeblackshear/frigate#17648] [Config Support] [answered]
### Describe the problem you are having

I'm on 0.14.1-f4f3cfa for a while, but I had not cleaned up the event part under record.
Now I wanted to add the alerts and detections under record as stated in the documentation for Raspberry PI:
https://docs.frigate.video/configuration/#raspberry-pi-home-assistant-addon-with-usb-coral

But when I edit my yaml in the configuration editor in the Frigate UI, it says that alerts and detections is not allowed. See screenshot below. 
![frigate record alerts option not allowed](https://github.com/user-attachments/assets/9ab39fed-9a7f-43ca-b8f2-4eca6518caf4)

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  host: 10.10.133.28
  port: 1883
  user: frigatemqtt
  password: xxxxx
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
database:  # <----- # Change database path in the container to other location
  path: /config/frigate.db
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - dog
    - cat
record: # <----- # Enable recording
  enabled: true
  retain:
    days: 30
    mode: active_objects
snapshots: # <----- Enable snapshots
  enabled: true
  timestamp: true
  bounding_box: true
  crop: true
  quality: 100
  retain:
    default: 60
    mode: active_objects
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p
  output_args:
    record: preset-record-generic
cameras:
  Backdoor: # Backdoor
    ffmpeg:
      input_args: -avoid_negative_ts make_zero
      inputs:
        - path: rtsp://127.0.0.1:8554/Backdoor
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    snapshots:
      required_zones:
        - AtTheBackDoor
        - RightToBackDoor
    detect:
      enabled: true
    live: #live stream als substream
      stream_name: Backdoor_sub
    motion:
      mask:
        - 0,31,476,34,530,0,268,0,268,0,0,0   # timestamp
    zones:
      AtTheBackDoor:
        coordinates: 0.29,0.892,0.202,0.726,0.25,0.039,0.388,0.081   # window
        objects:
          - person
          - dog
          - cat
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
      RightToBackDoor:
        coordinates: 
          1,0.298,1,1,0.632,1,0.566,0.935,0.644,0.451,0.771,0.522,0.83,0.383,0.87,0.382,0.898,0.243 #window
        objects:
          - person
          - dog
          - cat
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - AtTheBackDoor
          - RightToBackDoor
      detections:
        required_zones:
          - AtTheBackDoor
          - RightToBackDoor
  Parking: # Parkinglot
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Parking
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/Parking_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
    live: #live stream als substream
      stream_name: Parking_sub
    motion:
      mask:
        - 0.879,0.896,0.699,0.975,0.652,0.934,0.575,0.934,0.529,0.9,0.413,0.932,0.326,1,0.883,1
        - 1,0,1,0.489,0.703,0.436,0.209,0.425,0.147,0.439,0.139,0.497,0.047,0.548,0.036,0.604,0,0.551,0,0
        - 0,0.553,0.039,0.601,0.028,0.758,0.095,0.752,0.189,0.872,0.187,1,0.077,1,0,0.934
      threshold: 40
      contour_area: 20
      improve_contrast: 'true'
    zones:
      WholeParking:
        coordinates: 
          0.047,0.559,0.217,0.54,0.23,0.48,0.692,0.453,1,0.493,1,1,0.888,1,0.886,0.878,0.701,0.963,0.661,0.925,0.574,0.92,0.533,0.887,0.407,0.924,0.325,1,0.19,1,0.192,0.865,0.093,0.746,0.032,0.752
        loitering_time: 2
        inertia: 3
    snapshots:
      required_zones:
        - WholeParking
    review:
      alerts:
        required_zones: WholeParking
      detections:
        required_zones: WholeParking
  Schuur: # Schuur
    ffmpeg:
      inputs:
      # - path: rtsp://127.0.0.1:8554/Schuur_sub
      # input_args: preset-rtsp-restream
      #  roles:
      #      - detect
        - path: rtsp://127.0.0.1:8554/Schuur
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
    live: #live stream als substream
      stream_name: Schuur_sub
    motion:
      mask: 0.974,0.092,0.974,0.022,0.746,0.023,0.747,0.094
    zones:
      BijDeSchuur:
        coordinates: 
          0.372,0.774,0.443,1,0.68,1,0.687,0.845,0.875,0.888,0.995,0.871,1,0.466,1,0.085,0.735,0.098,0.736,0,0.222,0,0.126,0,0,0.155,0.006,0.276,0.11,0.3,0.159,0.482,0.054,0.755,0.089,0.814,0.26,0.833 # bij de schuur
        inertia: 3
        loitering_time: 0
    snapshots:
      required_zones:
        - BijDeSchuur
    review:
      alerts:
        required_zones: BijDeSchuur
      detections:
        required_zones: BijDeSchuur
  Back: # back cam
    ffmpeg:
      input_args: -avoid_negative_ts make_zero
      inputs:
        - path: rtsp://127.0.0.1:8554/Back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
    live: #live stream as substream not used, as camera is slow swithing
      stream_name: Back_sub
    motion:
      mask:   # <-- back Camera Timestamp
        - 0.525,0.013,0.543,0.252,1,0.265,1,0,0.242,0,0.246,0.015
        - 0.293,1,0,1,0,0.628,0,0,0.166,0
    zones:
      AtTheBackGate:
        coordinates: 
          0.335,0.986,0.991,0.982,0.989,0.391,0.537,0.274,0.516,0.06,0.4,0.053,0.421,0.318,0.296,0.411 #gate
        objects:
          - person
          - dog
          - cat
          - bicycle
          - motorcycle
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: AtTheBackGate
      detections:
        required_zones: AtTheBackGate
ui:
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  date_style: medium
go2rtc:
  streams:
    Backdoor: # Backdoor main stream - H264 1280x720 fps 29.97.. audio PCM ALAW 8000Hz mono 16bit
      - rtsp://admin:xxx@10.10.133.40:554/live/av0?
    Backdoor_sub: # Backdoor sub stream - H264 640x480 fps 29.97.. audio PCM ALAW 8000Hz mono 16bit
      - rtsp://admin:xxx@10.10.133.40:554/live/av1?
    Parking: # H.264 2688x1520 vbr 25fps max bitrate ....
      - rtsp://frigate:xxx@10.10.132.42/Streaming/Channels/101
    Parking_sub: # H.264 1280x720 vbr 20fps max bitrate ...
      - rtsp://frigate:xxx8@10.10.132.42/Streaming/channels/102
    Schuur: # Schuur main stream - H264H 1920x1080 15fps
      - rtsp://admin:xx@10.10.132.37:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    Schuur_sub: # Schuur sub stream - # H264H 640x480 10fps
      - rtsp://admin:xxx@10.10.132.37:554/cam/realmonitor?channel=1&subtype=1
    Back: # main 1280x720 15FPS H264 720p
      - rtsp://10.10.132.10:554/user=flo_password=xxx_channel=1_stream=0.sdp
    Back_sub: #substream 704x576 10FPS H264 D1
      - rtsp://10.10.132.10:554/user=flo_password=xxx_channel=1_stream=1.sdp
    # Zuid: # 1280x720 h264 framerate 10
    # - rtsp://10.10.132.25:554/user=admin_password=xxx_channel=1_stream=0.sdp?real_stream
    # Zuid_sub: # 704x576 h264 framerate 10
    # - rtsp://10.10.132.25:554/user=admin_password=xxx_channel=1_stream=1.sdp?real_stream
  webrtc:
    candidates:
      - 10.10.132.22:8555
      - stun:8555 # if you have dynamic public IP-address for external access
version: 0.14
camera_groups:
  Back:
    order: 1
    icon: LuKeySquare
    cameras:
      - Back
      - Backdoor
```

### Relevant Frigate log output

```shell
see screenshot. Did not save and reboot Frigate, because afraid it won't start while it says it is an invalid value
```

### Relevant go2rtc log output

```shell
not relevant
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
docker run -d \
--name frigate \
--restart=unless-stopped \
--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
--device /dev/dri/renderD128 \
--device /dev/bus/usb:/dev/bus/usb \
--shm-size=128m \
--privileged \
-v /volume2/docker/frigate/media:/media/frigate \
-v /volume2/docker/frigate/config:/config \
-v /etc/localtime:/etc/localtime:ro \
-v /dev/bus/usb:/dev/bus/usb \
-e LIBVA_DRIVER_NAME=i965 \
-e FRIGATE_RTSP_PASSWORD='yourpassword' \
-p 5055:5000 \
-p 8554:8554 \
-p 8555:8555/tcp \
-p 8555:8555/udp \
ghcr.io/blakeblackshear/frigate:stable
```

### Object Detector

Coral
