### DISCUSSION TITLE
[Support]: Errors about storage being full

### DISCUSSION THREAD

**Discussion by stewx** [blakeblackshear/frigate#17642] [General Support]
### Describe the problem you are having

I have set Frigate to record constantly, expecting it to just max out my drive and delete older recordings as needed, automatically.

I am getting errors like this, however:

### Version

0.14.1-f4f3cfa

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    driveway: 
      - rtsp://frigate:frigate@192.168.4.200:554/stream1
      - ffmpeg:driveway

cameras:
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
    record:
      enabled: true
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:frigate@192.168.4.201:554/live
          roles:
            - record
    record:
      enabled: true

record:
  enabled: True
  retain:
    days: 365
    mode: all
    
version: 0.14
```

### Relevant Frigate log output

```shell
[Errno 28] No space left on device: '/media/frigate/recordings/2025-04-10'
Error occurred when attempting to maintain recording cache
Unable to keep up with recording segments in cache for garage. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
Unraid installation
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Various: TP-Link, Wyze

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/745e9125-1a05-4479-b4ec-fae4dd258a25)
