### DISCUSSION TITLE
[Detector Support]: Coral USB installed, usable from the container (bash) but Frigate does not detect it

### DISCUSSION THREAD

**Discussion by ringuerel** [blakeblackshear/frigate#17644] [Detector Support] [answered]
### Describe the problem you are having

I've installed a USB Coral TPU, I've managed to confirm from inside the Docker container that it is a device, I managed to execute the Coral example inside the container and yet I get *No EdgeTPU was detected* error in Frigate, please help I got this Coral just for this 🫠 thank you in advance

### Version

0.15

### Frigate config file

```yaml
tls:
  # Optional: Enable TLS for port 8971 (default: shown below)
  enabled: true
auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false
  # Optional: Set secure flag on cookie. (default: shown below)
  # NOTE: This should be set to True if you are using TLS
  cookie_secure: false
  # Optional: Session length in seconds (default: shown below)
  session_length: 86400 # 24 hours
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  failed_login_rate_limit: None
  # Optional: Trusted proxies for determining IP address to rate limit
  # NOTE: This is only used for rate limiting login attempts and does not bypass
  # authentication. See the authentication docs for more details.
  trusted_proxies: []
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000

mqtt:
  enabled: true
  host: mqtt
  port: 1883

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%m/%d/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

logger:
  # Optional: default log level (default: shown below)
  default: warning
  # Optional: module by module log level configuration
  #logs:
    #frigate.mqtt: error

go2rtc:
  rtsp:
    username: '{FRIGATE_GO2RTC_RTSP_USERNAME}'
    password: '{FRIGATE_GO2RTC_RTSP_PASSWORD}'
  streams:
    camera1:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff1:554/stream1
      - ffmpeg:camera1#audio=aac#timeout=10000
    camera1_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff1:554/stream2
      - ffmpeg:camera1_sub#audio=aac#timeout=10000
    camera2:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff2:554/stream1
      - ffmpeg:camera2#audio=aac#timeout=10000
    camera2_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff2:554/stream2
      - ffmpeg:camera2_sub#audio=aac#timeout=10000
    camera3:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff3:554/stream1
      - ffmpeg:camera3#audio=aac#timeout=10000
    camera3_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff3:554/stream2
      - ffmpeg:camera3_sub#audio=aac#timeout=10000
    camera4:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff4:554/stream1
      - ffmpeg:camera4#audio=aac#timeout=10000
    camera4_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@some.ip.stuff4:554/stream2
      - ffmpeg:camera4_sub#audio=aac#timeout=10000

  webrtc:
    candidates:
      - some.ip.stuff25:8555

birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: motion

audio:
  enabled: true
  listen:
    - fire_alarm
    - scream
    - yell

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: auto detect)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: auto
    #-c:v:1
    #- h264_v4l2m2m
  # Optional: global input args (default: shown below)
  #input_args: preset-rtsp-restream
  #input_args: preset-rtsp-restream-low-latency
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic-audio-aac
  # Optional: Time in seconds to wait before ffmpeg retries connecting to the camera. (default: shown below)
  # If set too low, frigate will retry a connection to the camera's stream too frequently, using up the limited streams some cameras can allow at once
  # If set too high, then if a ffmpeg crash or camera stream timeout occurs, you could potentially lose up to a maximum of retry_interval second(s) of footage
  # NOTE: this can be a useful setting for Wireless / Battery cameras to reduce how much footage is potentially lost during a connection timeout.
  retry_interval: 10


detect:
  fps: 5
  enabled: true

cameras:
  camera1:
    enabled: true
    birdseye:
      order: 1
    audio:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera1_sub
          roles:
            - detect
            - audio
    motion:
      mask: 0.068,0.007,0.095,0.608,0.364,0.519,0.25,0.03
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    zones: {}
    objects:
      mask: 0.066,0,0.095,0.605,0.365,0.513,0.249,0.023
  camera2:
    enabled: true
    birdseye:
      order: 2
    audio:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera2_sub
          roles:
            - detect
            - audio
    objects: {}
  camera3:
    enabled: true
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        pre_capture: 7
        retain:
          default: 1
          mode: active_objects
    review:
      alerts:
        labels:
          - person
    birdseye:
      order: 3
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera3
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera3_sub
          roles:
            - detect
            - audio
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
  camera4:
    enabled: true
    birdseye:
      order: 1
    audio:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera4_sub
          roles:
            - detect
            - audio
    objects:
      mask: 0.388,0.237,0.391,0.396,0.548,0.431,0.549,0.257
    motion:
      mask: 0.387,0.239,0.391,0.397,0.548,0.431,0.549,0.258
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 1
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 1

objects:
  track:
    - person
    - car

review:
  alerts:
    labels: []
  detections:
    labels:
      - person
version: 0.15
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    networks:
      network-internal:
        ipv4_address: some.ip.stuff.here
    shm_size: "512mb" # update for your cameras based on calculation above
    env_file:
      - .env
    devices:
      - /dev/bus/usb/002/005
      #- /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11  # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/share/frigate/config:/config
      - /mnt/share/frigate/recordings:/media/frigate/recordings
      - /mnt/share/frigate/clips:/media/frigate/clips
      - /mnt/share/frigate/exports:/media/frigate/exports
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    expose:
      - 5000
    ports:
      #- "5000:5000"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

networks:
  network-internal:
    external: true
```

### Relevant Frigate log output

```shell
2025-04-10 21:16:10.319775972  2025/04/10 21:16:10 [error] 156#156: *16 auth request unexpected status: 502 while sending to client, client: 11.0.0.2, server: , request: "GET /api/version HTTP/1.1", host: "frigate:5000"
2025-04-10 21:16:14.397265694  [2025-04-10 21:16:14] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2025-04-10 21:16:14.403069958  Process detector:coral:
2025-04-10 21:16:14.403074039  Traceback (most recent call last):
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

Can't as it can't start

### Any other information that may be helpful

I bashed into the container, installed git and pycoral and all that, performed the [Coral test ](https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu) and it worked which tells me that Coral is recognized by the Frigate container
Bash log inside the container running coral example:

root@ce4db9920e43:/opt/frigate/coral# git clone https://github.com/google-coral/pycoral.git
Cloning into 'pycoral'...
remote: Enumerating objects: 337, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 337 (delta 36), reused 27 (delta 27), pack-reused 275 (from 1)
Receiving objects: 100% (337/337), 6.32 MiB | 20.49 MiB/s, done.
Resolving deltas: 100% (117/117), done.
root@ce4db9920e43:/opt/frigate/coral# cd pycoral
root@ce4db9920e43:/opt/frigate/coral/pycoral# bash examples/install_requirements.sh classify_image.py
DOWNLOAD: mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4197k  100 4197k    0     0  11.9M      0 --:--:-- --:--:-- --:--:-- 11.9M
DOWNLOAD: mobilenet_v2_1.0_224_inat_bird_quant.tflite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3495k  100 3495k    0     0  10.6M      0 --:--:-- --:--:-- --:--:-- 73.1M
DOWNLOAD: inat_bird_labels.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 37146  100 37146    0     0   164k      0 --:--:-- --:--:-- --:--:--  164k
DOWNLOAD: parrot.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  582k  100  582k    0     0  2167k      0 --:--:-- --:--:-- --:--:-- 2167k
root@ce4db9920e43:/opt/frigate/coral/pycoral# bash examples/install_requirements.sh classify_image.py
DOWNLOAD: mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4197k  100 4197k    0     0  13.2M      0 --:--:-- --:--:-- --:--:-- 63.5M
DOWNLOAD: mobilenet_v2_1.0_224_inat_bird_quant.tflite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3495k  100 3495k    0     0  10.6M      0 --:--:-- --:--:-- --:--:-- 30.2M
DOWNLOAD: inat_bird_labels.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 37146  100 37146    0     0   159k      0 --:--:-- --:--:-- --:--:--  159k
DOWNLOAD: parrot.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  582k  100  582k    0     0  2350k      0 --:--:-- --:--:-- --:--:-- 2350k
root@ce4db9920e43:/opt/frigate/coral/pycoral# python3 examples/classify_image.py \
--model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels test_data/inat_bird_labels.txt \
--input test_data/parrot.jpg
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
11.4ms
3.0ms
2.7ms
2.7ms
3.3ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.75781

**Comment by ElectronicBattle** [comment]
Yours says this:

```
devices:
      - /dev/bus/usb/002/005
      #- /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
```

but I think it should say this:

```
devices: 
   # - /dev/bus/usb/002/005
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
```


As far as I have seen, you have to tell docker how to map the host to the container ("mount" points for both hardware and software).

**Reply by ringuerel** [reply]
Thanks @ElectronicBattle , I've tried that at first, did not work, I thought that as I've the entire /dev/bus/usb/ shared to other container it would be the cause, then I shared specific ports (i.e /dev/bus/usb/002/005 to Frigate and /dev/ttyUSB0 to the other container) the other container works as expected, and in Frigate I can bash to the container and interact with the initialized Coral TPU (execute the Coral.ai example that identifies the Scarlet Macaw), so I'd not think the issue is the container not being able to interact with the device.

**Reply by ElectronicBattle** [reply]
I thought you had probably already tried it but I was hoping I had spotted something obvious for you - sorry!

**Reply by ringuerel** [reply]
You're good, it makes me want to try again as I might have missed/messed something, thanks

**Comment by ringuerel** [comment, marked as answer]
Found the issue, it was caused by leftover on the config.yml for CPU detectors, I did have the model section:
```
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```
Which seems to have caused the error No EdgeTPU detected, now I'll.... play with this thing.
