### DISCUSSION TITLE
Errors parsing config.yml (frigate:0.9.0-89e317a-amd64)

### DISCUSSION THREAD

**Discussion by Minglarn** [blakeblackshear/frigate#1765] [Ask A Question] [answered]
Hi.. Tried to use the latest docker "**frigate:0.9.0-89e317a-amd64**" and encountered a bunch of config related errors. 
```
frigate    | Error parsing config: 17 validation errors for FrigateConfig
frigate    | cameras -> frigate_parkering -> record -> events -> enabled
frigate    |   extra fields not permitted (type=value_error.extra)
frigate    | cameras -> frigate_parkering -> snapshots -> retrain
frigate    |   extra fields not permitted (type=value_error.extra)
```
And a snippet from my config.yam:
```
#############################
#        PARKERING          #
#############################
  frigate_parkering:
    ffmpeg:
      inputs:
        - path: ...

    record:
      enabled: True
      retain_days: 0
      events:
        enabled: True
        retain:
          default: 4
  ...
    snapshots:
      enabled: True
      height: 960
      crop: True

```
I'm suspecting that the config.yml parameters are obsolete but I cant find any info about this.
