### DISCUSSION TITLE
go2rtc config in Frigate not getting copied to go2rtc

### DISCUSSION THREAD

**Discussion by bobloadmire** [blakeblackshear/frigate#17657] [Ask A Question] [answered]
I have a valid config, I even commented out everything except one simple stream. But for some reason go2rtc is not getting the config from Frigate. webui is completely blank in go2rtc. I feel like there is something basic i'm missing. I never had an issue in 0.14.1

sample:

```
go2rtc:
  streams:
    # Using simple key: value format for this test, not a list item
    driveway: rtsp://username:pass@192.168.0.32:554/stream1
```

**Comment by hawkeye217** [comment]
Your indentation is incorrect. You need two spaces, not three.

```
go2rtc:
  streams:
    driveway: rtsp://username:pass@192.168.0.32:554/stream1
```

**Reply by bobloadmire** [reply]
That was just a typo when formatting it in the post, in the config it's 2 spaces, and 4 for the comment and driveway line. I validated my entire config with https://www.yamllint.com/

**Reply by hawkeye217** [reply]
We'll need to see your full Frigate config and your docker compose file in order to help.

**Reply by bobloadmire** [reply]
I reduced the go2rtc streams to just 1 for testing.

 
``` 
mqtt:
  enabled: false
go2rtc:
  streams:
    driveway: rtsp://x:x@192.168.0.32:554/stream1
cameras:
  driveway:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: driveway
    zones:
      Driveway:
        coordinates: 0.254,0.159,0.648,0.205,1,0.894,1,1,0.249,0.996
        loitering_time: 0
    review:
      alerts:
        required_zones: Driveway
      detections:
        required_zones: Driveway
  lincs_room:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/lincs_room?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lincs_room_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: lincs_room
  lyras_room:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/lyras_room?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lyras_room_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: lyras_room
  kitchen:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: kitchen
  bonus_room:
    enabled: true
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/bonus_room?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bonus_room_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: bonus_room
  hot_tub:
    enabled: false
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/hot_tub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/hot_tub_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: hot_tub
  side_yard:
    enabled: false
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/side_yard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_yard_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: side_yard
  spare:
    enabled: false
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/spare?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/spare_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: spare
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  cpu:
    type: cpu
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
objects:
  track:
    - person
    - dog
  filters:
    person:
      min_score: 0.5
      threshold: 0.8
audio:
  enabled: false
birdseye:
  enabled: false
version: 0.15-1
```

docker compose:

```                   
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be upda>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" #go2rtc
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
