### DISCUSSION TITLE
[Config Support]: Trying to update my Frigate to a more updated configuration.

### DISCUSSION THREAD

**Discussion by phox04** [blakeblackshear/frigate#17654] [Config Support] [answered]
### Describe the problem you are having

I setup my frigate on 0.10 I think and the config updated itself through the versions. Was realizing my recordings were missing chunks. Like I would only get the last 20-30s of a recording vs the whole thing. I looked at Frigate and it seems a lot has changed since my original config. I tried the updated config for my reolink's and I cannot get it to work.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
#this is my working config.

ottiuqseamqtt:
  host: 192.168.40.12
  user: mosquitto
  password: ottiuqsom

database:
  path: /db/frigate.db

birdseye:
  enabled: true
  mode: continuous

# below for hardware video card accel
ffmpeg:
  hwaccel_args: preset-vaapi

objects:
  track:
    - person
    - cat
    - dog
      #- car

detectors:
  ov:
    type: openvino
    device: CPU
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

record:
  enabled: true
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7
cameras:
  Backyard:
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: 
            http://192.168.50.5/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=iseeyou
          roles:
            - record
             # - rtmp
        - path: 
            http://192.168.50.5/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=iseeyou
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 5

# This is what I am trying to use.

mqtt:
  host: 192.168.40.12
  user: mosquitto
  password: ottiuqsom

database:
  path: /db/frigate.db

birdseye:
  enabled: true
  mode: continuous

objects:
  track:
    - person
    - cat
    - dog

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

record:
  enabled: true
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7

# Camera Config Below 

go2rtc:
  streams:
    backyard:
      - "ffmpeg:http://192.168.50.5/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=iseeyou#video=copy#audio=copy#audio=opus"
    backyard_sub:
      - "ffmpeg:http://192.168.50.5/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=iseeyou"

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.50.5:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.50.5:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant Frigate log output

```shell
2025-04-11 15:58:02.792683501  [2025-04-11 15:58:02] watchdog.backyard              ERROR   : Ffmpeg process crashed unexpectedly for backyard.
2025-04-11 15:58:02.792733111  [2025-04-11 15:58:02] watchdog.backyard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-04-11 15:58:02.792782481  [2025-04-11 15:58:02] ffmpeg.backyard.detect         ERROR   : [tcp @ 0x557c0b9d9080] Connection to tcp://192.168.50.5:8554?timeout=5000000 failed: Connection timed out
2025-04-11 15:58:02.792854772  [2025-04-11 15:58:02] ffmpeg.backyard.detect         ERROR   : [in#0 @ 0x557c0b9d7d80] Error opening input: Connection timed out
2025-04-11 15:58:02.792935296  [2025-04-11 15:58:02] ffmpeg.backyard.detect         ERROR   : Error opening input file rtsp://192.168.50.5:8554/backyard_sub.
2025-04-11 15:58:02.792995524  [2025-04-11 15:58:02] ffmpeg.backyard.detect         ERROR   : Error opening input files: Connection timed out
2025-04-11 15:58:02.812170332  [2025-04-11 15:58:02] ffmpeg.backyard.record         ERROR   : [tcp @ 0x55a405a1bfc0] Connection to tcp://192.168.50.5:8554?timeout=5000000 failed: Connection timed out
2025-04-11 15:58:02.812245263  [2025-04-11 15:58:02] ffmpeg.backyard.record         ERROR   : [in#0 @ 0x55a405a1acc0] Error opening input: Connection timed out
2025-04-11 15:58:02.812277634  [2025-04-11 15:58:02] ffmpeg.backyard.record         ERROR   : Error opening input file rtsp://192.168.50.5:8554/backyard.
2025-04-11 15:58:02.812332535  [2025-04-11 15:58:02] ffmpeg.backyard.record         ERROR   : Error opening input files: Connection timed out
2025-04-11 15:58:02.812384449  [2025-04-11 15:58:02] watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
2025-04-11 15:58:02.812435725  [2025-04-11 15:58:02] watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
2025-04-11 15:58:07.827774468  [2025-04-11 15:58:07] frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
2025-04-11 15:58:07.828018250  [2025-04-11 15:58:07] frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
2025-04-11 15:58:09.243031977  127.0.0.1 - - [11/Apr/2025:15:58:09 +0000] "" 400 0 "-" "-" "-"
2025-04-11 15:58:12.819991320  [2025-04-11 15:58:12] watchdog.backyard              ERROR   : Ffmpeg process crashed unexpectedly for backyard.
2025-04-11 15:58:12.820093449  [2025-04-11 15:58:12] watchdog.backyard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-04-11 15:58:12.820177480  [2025-04-11 15:58:12] ffmpeg.backyard.detect         ERROR   : [tcp @ 0x5569f8b35080] Connection to tcp://192.168.50.5:8554?timeout=5000000 failed: Connection timed out
2025-04-11 15:58:12.820319802  [2025-04-11 15:58:12] ffmpeg.backyard.detect         ERROR   : [in#0 @ 0x5569f8b33d80] Error opening input: Connection timed out
2025-04-11 15:58:12.820481796  [2025-04-11 15:58:12] ffmpeg.backyard.detect         ERROR   : Error opening input file rtsp://192.168.50.5:8554/backyard_sub.
2025-04-11 15:58:12.820626746  [2025-04-11 15:58:12] ffmpeg.backyard.detect         ERROR   : Error opening input files: Connection timed out
2025-04-11 15:58:12.845477463  [2025-04-11 15:58:12] ffmpeg.backyard.record         ERROR   : [tcp @ 0x5599459bdfc0] Connection to tcp://192.168.50.5:8554?timeout=5000000 failed: Connection timed out
2025-04-11 15:58:12.845575360  [2025-04-11 15:58:12] ffmpeg.backyard.record         ERROR   : [in#0 @ 0x5599459bccc0] Error opening input: Connection timed out
2025-04-11 15:58:12.845697065  [2025-04-11 15:58:12] ffmpeg.backyard.record         ERROR   : Error opening input file rtsp://192.168.50.5:8554/backyard.
2025-04-11 15:58:12.845814104  [2025-04-11 15:58:12] ffmpeg.backyard.record         ERROR   : Error opening input files: Connection timed out
2025-04-11 15:58:12.845949224  [2025-04-11 15:58:12] watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
2025-04-11 15:58:12.846061504  [2025-04-11 15:58:12] watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
```

### Relevant go2rtc log output

```shell
| 2025-04-11 15:46:03 | startup | Preparing new go2rtc config...
info | 2025-04-11 15:46:04 | startup | Starting go2rtc...
info | 2025-04-11 15:46:04 | startup | go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info | 2025-04-11 15:46:04 | startup | config path=/dev/shm/go2rtc.yaml
info | 2025-04-11 15:46:04 | rtsp    | listen addr=:8554
info | 2025-04-11 15:46:04 | api     | listen addr=:1984
info | 2025-04-11 15:46:04 | webrtc  | listen addr=:8555/tcp
info | 2025-04-11 15:46:13 | startup | Starting go2rtc healthcheck service...
```

### Frigate stats

```json
{"cameras":{"backyard":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":509,"capture_pid":512,"ffmpeg_pid":787,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"cpu":{"inference_speed":10.0,"detection_start":0.0,"pid":479}},"detection_fps":0.0,"gpu_usages":{"intel-vaapi":{"gpu":"0.0%","mem":"-%"}},"cpu_usages":{"frigate.full_system":{"cpu":"3.5","mem":"31.5"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"97":{"cpu":"0.1","cpu_average":"0","mem":"0.2","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"106":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"1.6","cpu_average":"6","mem":"3.6","cmdline":"python3 -u -m frigate"},"137":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"nginx: master process nginx"},"183":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"184":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"185":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"186":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"193":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: cache manager process"},"320":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"463":{"cpu":"0.1","cpu_average":"0","mem":"2.1","cmdline":"frigate.recording_manager"},"467":{"cpu":"0.1","cpu_average":"0","mem":"2.1","cmdline":"frigate.review_segment_manager"},"479":{"cpu":"0.1","cpu_average":"0","mem":"2.1","cmdline":"frigate.detector.cpu "},"495":{"cpu":"0.2","cpu_average":"0","mem":"2.2","cmdline":"frigate.output       "},"509":{"cpu":"0.0","cpu_average":"0","mem":"2.1","cmdline":"frigate.process:backyard"},"512":{"cpu":"0.3","cpu_average":"0","mem":"2.1","cmdline":"frigate.capture:backyard"},"542":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"549":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"781":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"786":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"},"787":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.50.5:554/backyard_sub -r 5 -vf fps=5,scale_vaapi=w=1280:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"789":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-cea210d -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.50.5:554/backyard -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4"}},"service":{"uptime":41,"version":"0.15.0-cea210d","latest_version":"0.15.0","storage":{"/media/frigate/recordings":{"total":237772.4,"used":58017.4,"free":169008.9,"mount_type":"ext4"},"/media/frigate/clips":{"total":237772.4,"used":58017.4,"free":169008.9,"mount_type":"ext4"},"/tmp/cache":{"total":953.7,"used":53.2,"free":900.5,"mount_type":"tmpfs"},"/dev/shm":{"total":256.0,"used":0.5,"free":255.5,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1744386439},"processes":{"recording":{"pid":463},"review_segment":{"pid":467},"go2rtc":{"pid":97}}}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
---
version: "3"
services:
   frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /docker/frigate/config.yml:/config/config.yml:rw
      - /docker/frigate/:/config/
      #- /mnt/media/NVR:/media/frigate
      - /docker/frigate/recordings:/media/frigate
      - /docker/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "eagleeye"
    restart: unless-stopped

   mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
      - /docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /docker/mosquitto/config:/mosquitto/config
      - /docker/mosquitto/data:/mosquitto/data
      - /docker/mosquitto/log:/mosquitto/log
      #- /docker/mosquitto/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
```

### Object Detector

CPU (no coral)

**Comment by NickM-27** [comment, marked as answer]
use 127.0.0.1:8554 instead of 192.168.50.5:8554

**Reply by phox04** [reply]
That was it! For all other cameras just use localhost (127.0.0.1)?

One last question are any of these needed anymore?

```
birdseye:
  enabled: true
  mode: continuous

objects:
  track:
    - person
    - cat
    - dog

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

record:
  enabled: true
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7

detectors:
  ov:
    type: openvino
    device: CPU
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi
```

**Reply by NickM-27** [reply]
you use localhost when connecting to the go2rtc restream

**Reply by phox04** [reply]
got it. What about these additional config changes I made. Are these needed or are the deprecated?

birdseye:
  enabled: true
  mode: continuous

objects:
  track:
    - person
    - cat
    - dog

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

record:
  enabled: true
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7

detectors:
  ov:
    type: openvino
    device: CPU
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-vaapi

**Reply by NickM-27** [reply]
yes, these all do different things that are necessary

**Reply by phox04** [reply]
Sorry last question, I set the hardware accel on but my old config was humming around 30% cpu now its at 53% and GPU at 1%. old config was the same. I have this flag on my config.yml but its still not using intel gpu.

ffmpeg:
  hwaccel_args: preset-vaapi

**Reply by NickM-27** [reply]
What CPU?

**Reply by phox04** [reply]
model name      : Intel(R) Core(TM) i7-4785T CPU @ 2.20GHz

**Reply by NickM-27** [reply]
You might need to use i965 driver

**Reply by phox04** [reply]
would that be adding 
LIBVA_DRIVER_NAME=i965
to my environment area in docker-compose?

**Reply by NickM-27** [reply]
yes

**Reply by phox04** [reply]
I did that but dont seem to see any difference in frigate.

I do see this on startup.
`CPU detectors are not recommended and should only be used for testing or for trial purposes.`

**Reply by NickM-27** [reply]
let's see a screenshot of the system metrics

**Reply by phox04** [reply]
version: "3"
services:
   frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /docker/frigate/config.yml:/config/config.yml:rw
      - /docker/frigate/:/config/
      #- /mnt/media/NVR:/media/frigate
      - /docker/frigate/recordings:/media/frigate
      - /docker/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      #FRIGATE_RTSP_PASSWORD: "eagleeye"
      - LIBVA_DRIVER_NAME=i965
    restart: unless-stopped

   mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
      - /docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /docker/mosquitto/config:/mosquitto/config
      - /docker/mosquitto/data:/mosquitto/data
      - /docker/mosquitto/log:/mosquitto/log
      #- /docker/mosquitto/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

**Reply by phox04** [reply]
Here is an image of metrics.
![frigate](https://github.com/user-attachments/assets/cdccd3ab-f06f-4292-bc2e-268387cac0ca)

**Reply by NickM-27** [reply]
the only high cpu usage I see is for object detection, which is how you config is set. You could try changing it to GPU, though technically I think only 6th gen and newer support OpenVINO on GPU

**Reply by phox04** [reply]
would that just be doing this?

detectors:
  ov:
    type: openvino
    device: GPU
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

**Reply by NickM-27** [reply]
yes

**Reply by phox04** [reply]
Must not be possible on my cpu when I changed to GPU it threw an error.

One more for you. My live viewing has audio but my recordings dont. Is there any way for the recordings to also have audio?

**Reply by NickM-27** [reply]
https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Reply by phox04** [reply]
I got this.

2025-04-11 22:08:16.369343581  *************************************************************
2025-04-11 22:08:16.369354922  ***    Config Validation Errors                           ***
2025-04-11 22:08:16.369365461  *************************************************************
2025-04-11 22:08:16.369366862  cameras.Backyard.ffmpeg.inputs.0.output_args: Extra inputs are not permitted

config looks like this

```
cameras:
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream
          roles:
            - record
          output_args:
            record: preset-record-generic-audio-aac
        - path: rtsp://127.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```
