### DISCUSSION TITLE
[Support]: Frigate + RADEON RX560

### DISCUSSION THREAD

**Discussion by sistemasanquan** [blakeblackshear/frigate#17659] [Hardware Acceleration Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Summary:

When using Frigate (latest stable version) with an AMD Radeon RX560 GPU on Ubuntu 22.04 Server, the ffmpeg process gradually consumes all available system memory, eventually leading to a complete system freeze. This issue does not occur when using an NVIDIA GPU under the same setup.

System Configuration:

OS: Ubuntu 22.04.4 LTS (Server)

Frigate Version: Latest stable (as of report date)

GPU: AMD Radeon RX560

GPU Driver: Default amdgpu driver available from Ubuntu’s official repositories

Cameras: 12 IP cameras (generic Chinese brand)

System RAM: 24 GB

FFmpeg Versions Tested: 5.0 and 7.0 — same memory leak behavior observed in both

Docker: [If applicable, insert method of deployment]

Details:

The issue starts shortly after launching Frigate with the RX560 GPU.

Memory usage by ffmpeg increases steadily and is not released, even when load is stable.

Within a few hours, all 24 GB of system RAM is consumed, causing system instability or a complete freeze.

Switching to an NVIDIA GPU resolves the issue entirely, suggesting the root cause may be related to AMD hardware acceleration (VAAPI/AMF), driver compatibility, or how Frigate integrates with FFmpeg.

Temporary Workaround:

Currently, the system is running in CPU-only mode with the RX560 removed. This avoids the issue but results in higher CPU usage and is not sustainable long term.

Additional Notes:

The issue appears to be triggered more aggressively by certain low-cost ONVIF-compatible Chinese cameras.

Frigate was used with its default hardware acceleration behavior — no manual overrides or custom ffmpeg arguments.

### Steps to reproduce

1. Enable Preset-vaapi for radeon use
2. One process increase the use RAM to limit and crashes the entire system
3. Reboot manually is the only option
...

### Version

0.15.0 (stable9

### In which browser(s) are you experiencing the issue with?

Vivaldi, Chrome, edge, and Opera GX

### Frigate config file

```yaml
mqtt:
 #enabled: false
  host: 172.26.4.232
  user: frigate
  password: somepassword
#detectors:
  #ov:
   # type: openvino
   # device: AUTO
   # model:
   #  path: /openvino-model/ssdlite_mobilenet_v2.xml

#model:
 # width: 300
  #height: 300
  #input_tensor: nhwc
  #input_pixel_format: bgr
  #labelmap_path: /openvino-model/coco_91cl_bkgr.txt 
detectors:
  coral:
    type: edgetpu
    device: usb

#ffmpeg:
  #hwaccel_args: preset-vaapi
  #hwaccel_args: preset-rpi-64-h264
  # For H264 stream decoding
ffmpeg:
  hwaccel_args: preset-vaapi


go2rtc:
  streams:
    Oficina_Villarrica_Hik-DOMO_ext:
      - rtsp://admin:somepassword@172.26.4.2:554/Streaming/Channels/301
    Oficina_Villarrica_Hik-Bullet_ext:
      - rtsp://admin:somepassword@172.26.4.2:554/Streaming/Channels/101
    Oficina_Villarrica_Hik-Bullet_ext_2:
      - rtsp://admin:somepassword@172.26.4.2:554/Streaming/Channels/401
    Camera1:
      - rtsp://admin:carlos1234@172.26.3.254:554/Streaming/Channels/101
    Camera2:
      - rtsp://admin:carlos1234@172.26.3.254:554/Streaming/Channels/201
    Camera3:
      - rtsp://admin:carlos1234@172.26.3.254:554/Streaming/Channels/301
    Camera4:
      - rtsp://admin:carlos1234@172.26.3.254:554/Streaming/Channels/401
    #Casa_campo_carecam:
      #- rtsp://admin:admin123456@172.26.1.39:554/onvif1
     # - "ffmpeg:Casa_campo_carecam#audio=opus"
    #help_phone_cam1:
     # - rtsp://r101:somepassword@172.26.4.32:554/user=r101&password=somepassword&channel=1&stream=0.sdp?
   # help_phone_cam2:
   #   - rtsp://r101:somepassword@172.26.4.32:554/user=r101&password=somepassword&channel=2&stream=0.sdp?
    #help_phone_cam3:
    #  - rtsp://r101:somepassword@172.26.4.32:554/user=r101&password=somepassword&channel=3&stream=0.sdp?
   # help_phone_cam4:
   #   - rtsp://r101:somepassword@172.26.4.32:554/user=r101&password=somepassword&channel=4&stream=0.sdp?
    #Oficina_Villarrica_calle:  
     # - rtsp://admin:admin123456@172.26.4.34:554/onvif1
     # - "ffmpeg:Oficina_Villarrica_calle#audio=opus"    
    #help_phone_caja:  
      #- rtsp://admin:admin123456@172.26.4.60:554/onvif1
      #- "ffmpeg:help_phone_caja#audio=opus"  
    anquan_entrada:
      - rtsp://admin:admin123456@10.10.3.15:554/onvif1
    #anquan_calle:
     # - rtsp://admin:admin123456@10.10.3.5:554/onvif1
    #emporio_caja:
      #- rtsp://admin:admin123456@172.26.5.254:554/onvif1
      #- ffmpeg:emporio_caja#video=h264#hardware#audio=opus
    #emporio_caja2:
     # - rtsp://admin:admin123456@172.26.5.250:554/onvif1
     # - ffmpeg:emporio_caja2#video=h264#hardware#audio=opus
   # entrada:
   #   - dvrip://user:user@10.10.3.17:34567
#    test:
 #     - rtsp://admin:admin@172.26.3.249:6002
    user_Camera1:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/101
    user_Camera2:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/201
    user_Camera3:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/301
    user_Camera4:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/401
    user_Camera5:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/501
    user_Camera6:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/601
    user_Camera7:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/701
    user_Camera8:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/801
    user_Camera9:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/901
    user_Camera10:
      - rtsp://admin:somepassword@192.168.1.99:554/Streaming/Channels/1001
    #casa_campo1:
     # - rtsp://admin:admin123456@172.26.1.254:554/onvif1
    casa_campo2:
      - rtsp://admin:admin123456@172.26.1.253:554/onvif1
      - ffmpeg:casa_campo2#video=h264#hardware#audio=opus
    casa_campo3:
      - rtsp://admin:admin123456@172.26.1.252:554/onvif1
      - ffmpeg:casa_campo3#video=h264#hardware#audio=opus
  audio: # <- enable audio events for all camera
  enabled: true


  webrtc:
    candidates:
      - 172.26.4.10:8555

#ui:
 # use_experimental: false

#CAMARAS

cameras:
  Camera1:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Camera2:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Camera3:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera3
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Camera4:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera4
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  Oficina_Villarrica_Hik-DOMO_ext:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Oficina_Villarrica_Hik-DOMO_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - cat
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Oficina_Villarrica_Hik-Bullet_ext:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Oficina_Villarrica_Hik-Bullet_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - cat
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  Oficina_Villarrica_Hik-Bullet_ext_2:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Oficina_Villarrica_Hik-Bullet_ext_2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        #- dog
        - bicycle
        - cat
        #- car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  anquan_entrada:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/anquan_entrada
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  anquan_calle:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/anquan_calle
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  #emporio_caja:
   # ffmpeg:
      #path: '5.0'
     # hwaccel_args: preset-vaapi
     # inputs:
      #  - path: rtsp://127.0.0.1:8554/emporio_caja
       #   input_args: preset-rtsp-restream
       #   roles:
       #     - detect
       #     - record
   # objects:
    #  track:
     #   - person
      #  - dog
       # - bicycle
       # - car
      #  - motorcycle
   # detect:
    #  width: 640
    #  height: 480
   # record:
    #  enabled: true
    #  retain:
       # days: 7
       # mode: all
  #emporio_caja2:
   # ffmpeg:
      #path: '5.0'
     # hwaccel_args: preset-vaapi
    #  inputs:
     #   - path: rtsp://127.0.0.1:8554/emporio_caja2
    #      input_args: preset-rtsp-restream
     #     roles:
     #      - detect
     #       - record
    #objects:
    #  track:
     #   - person
      #  - dog
      #  - bicycle
      #  - car
      #  - motorcycle
   # detect:
    #  width: 640
    # height: 480
   # record:
    #  enabled: true
      #retain:
       # days: 7
       # mode: all
  entrada:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/entrada
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera1:
    ffmpeg:
     # path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera2:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera3:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera3
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera4:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera4
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera5:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera5
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera6:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera6
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera7:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera7
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera8:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera8
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  user_Camera9:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera9
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - cat
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all

  user_Camera10:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/user_Camera10
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 7
        mode: all
 # casa_campo1:
    #ffmpeg:
    #  hwaccel_args: preset-vaapi
    #  inputs:
   #     - path: rtsp://127.0.0.1:8554/casa_campo1
    #      input_args: preset-rtsp-restream-low-latency
    #      roles:
    #        - detect
    #        - record
   # objects:
   #   track:
     #   - person
     #   - dog
     #   - bicycle
     #   - car
     #   - motorcycle
  #  detect:
  #    width: 640
  #    height: 480
  #  record:
  #    enabled: true
  #    retain:
  #      days: 7
  #     mode: all

  casa_campo2:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/casa_campo2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
      #fps: 3
    record:
      enabled: true
      retain:
        days: 7
        mode: all

    motion:
      mask: 0.213,0.508,0.558,0.53,0.601,1,0.205,1
  casa_campo3:
    ffmpeg:
      #path: '5.0'
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/casa_campo3
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
    detect:
      width: 640
      height: 480
      #fps: 3
    record:
      enabled: true
      retain:
        days: 7
        mode: all

    motion:
      mask: 0.226,0.617,0.704,0.462,0.681,0.978,0.263,0.972
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

# Include all cameras by default in Birdseye view

birdseye:
  enabled: true
  restream: true
  mode: motion

logger:
  # Optional: default log level (default: shown below)
  default: info

version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: large
camera_groups:
  ANQUAN_(HQ):
    order: 1
    icon: LuActivitySquare
    cameras:
      - anquan_entrada
      - anquan_calle
      - entrada
  PELUQUERIA-PILOTO:
    order: 2
    icon: LuActivitySquare
    cameras:
      - Camera1
      - Camera2
      - Camera3
      - Camera4
  R101_(Villarrica):
    order: 3
    icon: LuActivitySquare
    cameras:
      - Oficina_Villarrica_Hik-DOMO_ext
      - Oficina_Villarrica_Hik-Bullet_ext
      - Oficina_Villarrica_Hik-Bullet_ext_2
  Casa_Campo:
    order: 4
    icon: LuActivitySquare
    cameras:
      - casa_campo2
      - casa_campo3
  user:
    order: 5
    icon: LuActivitySquare
    cameras:
      - user_Camera1
      - user_Camera2
      - user_Camera3
      - user_Camera4
      - user_Camera5
      - user_Camera6
      - user_Camera7
      - user_Camera8
      - user_Camera9
      - user_Camera10
  EMPORIO:
    order: 6
    icon: LuActivitySquare
    cameras:
      - emporio_caja
      - emporio_caja2
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    cap_add:
      - CAP_PERFMON
    shm_size: "1g" # upeeee for your cameras based on calculation above
   # deploy:    # <------------- Add this section
     # resources:
     #   reservations:
      #    devices:
       #     - driver: nvidia
       #       #device_ids: ['0'] # this is only needed when using multiple GPUs
        #      count: all # number of GPUs
        #      capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    #  - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
     # - /home/anquan/frigate/config.yml:/config/config.yml
      - /home/frigate/config:/config/
      - /home/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "somepassword"
```

### Relevant Frigate log output

```shell
I plan to reinstall the full setup with the RX560 next week in order to collect detailed logs and error messages. These will be added to this report to help further isolate the issue.
```

### Relevant go2rtc log output

```shell
I plan to reinstall the full setup with the RX560 next week in order to collect detailed logs and error messages. These will be added to this report to help further isolate the issue.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision, and chinese generic rtsp cameras 

### Screenshots of the Frigate UI's System metrics pages

I plan to reinstall the full setup with the RX560 next week in order to collect detailed logs and error messages. These will be added to this report to help further isolate the issue.

### Any other information that may be helpful

When I disable the camera that is currently causing the memory spike, the issue shifts to another camera at random. However, the memory leak never occurs with more than one camera at a time — it seems to affect only a single stream at any given moment, and the affected stream varies unpredictably.
