### DISCUSSION TITLE
Detection Works with Snapshots, but no alerts.

### DISCUSSION THREAD

**Discussion by botenjinir** [blakeblackshear/frigate#17675] [Config Support] [answered]
### Describe the problem you are having

I have a configuration that will identify objects in the live stream, and take snapshots.  But there are no alerts that get triggered.

I don't see anything in the logs that seem relevant.  I do get the log messages I put in the log section when it sees something, but nothing looks like there's an error.  It clearly detects objects, and it triggers saving a snapshot.  However, there's nothing in the review screen under any of the topics (alert, detect, motion).

I'm sure once again, I missed something obvious, but cannot seem to figure out what.  Any help would be appreciated.  Thanks!

Note: Object detection is currently on CPU.  I DO have a Coral, but haven't yet gotten it working with Debian 12.   Maybe after tinkering a bit more with that, I'll have some questions for the board there as well.

### Version

15.1

### Frigate config file

```yaml
mqtt:
  enabled: false
objects:
  track:
    - person
    - cat
    - dog
    - car

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True

review:
  alerts:
    labels:
      - person
      - cat
      - car
      - dog
  detections:
    labels:
      - person
      - cat
      - car
      - dog
cameras:
  FrontDoor: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args: "auto"
      inputs:
        #  High Resolution
        - path: rtsp://admin:123456@192.168.88.101:554/stream0
          roles:
            - record
            - detect
            - rtmp
        #  Low Resolution
        #- path: rtsp://admin:123456@192.168.88.101:554/stream1
        #  roles:
        #    - detect
        #    - rtmp
    detect:
      enabled: true

version: 0.15-1
camera_groups:
  Front:
    order: 1
    icon: LuAlignEndVertical
    cameras:
      - birdseye
      - name_of_your_camera
```

### Relevant Frigate log output

```shell
172.18.0.1 - - [12/Apr/2025:17:09:46 -0500] "GET /api/review/summary?timezone=America%2FChicago HTTP/1.1" 200 107 "https://localhost:8971/review" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0" "-"
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "passwordhere"
```

### Object Detector

CPU (no coral)
