### DISCUSSION TITLE
[Detector Support]: Detector shows many small bounding box (using yolonas_s)

### DISCUSSION THREAD

**Discussion by hma02** [blakeblackshear/frigate#17673] [Detector Support] [answered]
### Describe the problem you are having

Hello, I recently set up the frigate in docker on my NanoPi M6. I was able to get camera streams working in go2rtc and rknn was running at  37ms inference speed.  But the detection seems a bit inaccurate.

As shown in the attached image ("Debug" tab in Frigate UI) , when sensing an moving object, the bounding box goes crazy and scattered everywhere on the image, while the red motion box is correctly tracking the moving object.   
![Screenshot from 2025-04-12 17-56-34](https://github.com/user-attachments/assets/94e5f1fb-7263-445a-ac69-fa610893794c)

Not sure what part of my setting is wrong, or it is an issue with the default deci-fp16-yolonas_s model? 

### Version

0.15.0-cea210d

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-rk-h264 

detectors:
  rknn:
    type: rknn
    num_cores: 3 

model:
  path: deci-fp16-yolonas_s    
  input_pixel_format: bgr  
  input_tensor: nchw
  labelmap_path: /labelmap/coco-80.txt
  width: 320
  height: 320

objects:
  track:
    - person
    - car


go2rtc:
  streams:
    LC: 
      rtsp://:@192.168.1.181/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  webrtc:
    listen: :8555
    candidates:
      - 192.168.1.156:8555
      - stun:8555
  log:
    format: text


cameras:
  LC:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream-low-latency  
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/LC_low?video=copy&audio=copy   #this is a 640x480 substream 
          roles:
            - detect
            - record

    detect:
      width: 640
      height: 480
      fps: 10

    zones:
      frontyard:
        coordinates: 0.005,0.818,0.474,0.76,0.991,0.556,0.998,0.994,0.006,0.991
        loitering_time: 3
        inertia: 3
      pedestrians:
        coordinates: 
          0.003,0.671,0.007,0.806,0.457,0.756,0.637,0.688,0.658,0.557,0.606,0.583,0.36,0.628
        loitering_time: 3
        inertia: 3
    motion:
      mask: 0.023,0.046,0.297,0.046,0.296,0.101,0.021,0.103
      threshold: 40
      contour_area: 20
      improve_contrast: true
    review:
      alerts:
        required_zones:
          - frontyard
          - pedestrians
      detections:
        required_zones:
          - frontyard
          - pedestrians
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: no
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    shm_size: "512mb" 
    devices:
      - /dev/dri/renderD128 
      - /dev/dri/renderD129
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ssd/frigate/config:/config 
      - /mnt/ssd/frigate/media:/media/frigate  
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"  
      - "5000:5000" 
      - "8554:8554"  # RTSP feeds
      - "8555:8555/tcp"  # WebRTC over TCP
      - "8555:8555/udp"  # WebRTC over UDP
    environment:
      FRIGATE_RTSP_PASSWORD: "password"  # Change this!
```

### Relevant Frigate log output

```shell
No error for rknn or other parts in log, all are initialized ok.

2025-04-12T21:09:47.424131311Z 2025-04-12 17:09:47.424023307  I RKNN: [17:09:47.423] RKNN Runtime Information, librknnrt version: 2.0.0b0 (35a6907d79@2024-03-24T10:31:14)
2025-04-12T21:09:47.424180313Z 2025-04-12 17:09:47.424072600  I RKNN: [17:09:47.424] RKNN Driver Information, version: 0.9.8
2025-04-12T21:09:47.424546369Z 2025-04-12 17:09:47.424457907  I RKNN: [17:09:47.424] RKNN Model Information, version: 6, toolkit version: 2.0.0b0+9bab5682(compiler version: 2.0.0b0 (35a6907d79@2024-03-24T02:34:11)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
```

### Install method

Docker Compose

### Object Detector

RKNN

### Screenshots of the Frigate UI's System metrics pages

![Screenshot from 2025-04-12 18-03-34](https://github.com/user-attachments/assets/95c88756-4a22-4f84-9fff-7bdb029e6697)
