### DISCUSSION TITLE
Bounding boxes

### DISCUSSION THREAD

**Discussion by Jschacht06** [blakeblackshear/frigate#17670] [Ask A Question] [answered]
Since i moved my frigate away from TrueNAS to a docker container on proxmox i no longer see bounding boxes around the persons or cats etc the camera detects in the clips. Was this feature removed or is there a way to enable this???

Im on 0.15.0 and using a coral usb

**Comment by hawkeye217** [comment]
There's no way to help without seeing your config.

**Reply by Jschacht06** [reply]
sorry i forgot to add it 
```
mqtt:
  host: ..........
  port: ..............
  user: ................
  password: ...................

go2rtc:
  streams:
    tuinhuis: "ffmpeg:.............#video=h264#hardware"

ffmpeg:
  hwaccel_args: preset-vaapi 

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  dome_cam:
    ffmpeg:
      inputs:
        - path: ...............
          roles:
            - record
            - detect
    objects:
      track:
          - person
          - cat
          - dog
    onvif:
      host: ...........
      port: ............
      user: ...............
      password: ......................

  tuinhuis:
    ffmpeg:
      inputs:
        - path: .....................
          roles:
            - detect
            - record
    objects:
      track:
          - person
          - cat
          - dog
record:
  enabled: true
  retain:
    days: 7
```
