### DISCUSSION TITLE
Ffmpeg 7 crashed

### DISCUSSION THREAD

**Discussion by Loic691** [blakeblackshear/frigate#17687] [Hardware Acceleration Support] [answered]
Hi all. I have error on Frigate latest stable 0.15 so ffmpeg 7.
I'm running with docker on LXC on Intel Core i5 12th. Same error on Intel i7 13th
My camera are HIKVISION
Thanks for your help
This issue is randomly and is trigger every 5/10/15 minutes, randomly

```
5-04-13T20:48:55.190805698Z 2025-04-13 22:48:55.190692400      Last message repeated 1 times

2025-04-13T20:48:55.190811008Z 2025-04-13 22:48:55.190693908  [out#0/rtsp @ 0x62cc595b2f40] Error muxing a packet

2025-04-13T20:48:55.190815201Z 2025-04-13 22:48:55.190695198  [out#0/rtsp @ 0x62cc595b2f40] Task finished with error code: -32 (Broken pipe)

2025-04-13T20:48:55.190819346Z 2025-04-13 22:48:55.190696287  [out#0/rtsp @ 0x62cc595b2f40] Terminating thread with return code -32 (Broken pipe)

2025-04-13T20:48:55.231318707Z 2025-04-13 22:48:55.231262561  [out#0/rtsp @ 0x62cc595b2f40] Error writing trailer: Broken pipe

2025-04-13T20:48:56.816542756Z 2025-04-13 22:48:56.816433977  [2025-04-13 22:48:56] watchdog.frigate_cour          ERROR   : Ffmpeg process crashed unexpectedly for frigate_cour.

2025-04-13T20:48:56.816588396Z 2025-04-13 22:48:56.816438080  [2025-04-13 22:48:56] watchdog.frigate_cour          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.

2025-04-13T20:48:56.816594565Z 2025-04-13 22:48:56.816439764  [2025-04-13 22:48:56] ffmpeg.frigate_cour.detect     ERROR   : [AVHWFramesContext @ 0x7d9eb4098b00] Failed to sync surface 0x15: 1 (operation failed).

2025-04-13T20:48:56.816598838Z 2025-04-13 22:48:56.816440991  [2025-04-13 22:48:56] ffmpeg.frigate_cour.detect     ERROR   : [hwdownload @ 0x7d9ec4003980] Failed to download frame: -5.

2025-04-13T20:48:56.816603139Z 2025-04-13 22:48:56.816442276  [2025-04-13 22:48:56] ffmpeg.frigate_cour.detect     ERROR   : [vf#0:0 @ 0x5bfe56ef8800] Error while filtering: Input/output error

2025-04-13T20:48:56.816607173Z 2025-04-13 22:48:56.816443480  [2025-04-13 22:48:56] ffmpeg.frigate_cour.detect     ERROR   : [vf#0:0 @ 0x5bfe56ef8800] Task finished with error code: -5 (Input/output error)

2025-04-13T20:48:56.816611309Z 2025-04-13 22:48:56.816444619  [2025-04-13 22:48:56] ffmpeg.frigate_cour.detect     ERROR   : [vf#0:0 @ 0x5bfe56ef8800] Terminating thread with return code -5 (Input/output error)

2025-04-13T20:48:56.826692438Z 2025-04-13 22:48:56.826635619  22:48:56.826 DBG [rtsp] new consumer stream=cour-webrtc-sub 
```

Here's my conf
```
# aide config : https://www.youtube.com/watch?v=jEgKU5U4kGw

# A utiliser uniquement si on utilise VS CODE par exemple depuis HA pour vérifier le YAML. Pas besoin si on édite directement depuis frigate
#yaml-language-server: $schema=http:/192.168.2.31:5000/api/config/schema.json

version: 0.15-1

ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: Europe/Paris
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour

mqtt:
  enabled: true
  host: 192.168.2.16
  #port: #
  user: mqtt
  password: mqtt

birdseye:
  enabled: true
  mode: continuous

ffmpeg:
  #preset pour les CPU intel (ancien NAS et MS-01)
  hwaccel_args: preset-vaapi

record:
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  retain:
    # Default 10 days
    default: 30

detectors:
  coral_pci:
    type: edgetpu
    device: pci
  #coral_usb:
    #type: edgetpu
    #device: usb   
  # GPU detector
  #ov:
  #  type: openvino
  #  device: GPU

objects:
  # Optional: list of objects to track from labelmap.txt / Otherwise just car and person by default
  track:
    - person
    - car
    - cat
    - dog
    - bicycle

  filters:
    person:
      min_score: 0.7
      threshold: 0.8
    bicycle:
      min_score: 0.65
      threshold: 0.75
    car:
      min_score: 0.7
      threshold: 0.78
    dog:
      min_score: 0.65
      threshold: 0.75
    cat:
      min_score: 0.65
      threshold: 0.75

# On ne veut des "alertes" que si des personnes sont détectées. Le reste reste en detection (d'objet quand meme mais dispo dans detection)
# TODO : a voir si on veut pas quand meme garder les voitures qui restent sur le parking ???? dans ce cas la il faut enlever cette section et la mettre dans cour et cour_est
# Pour moi ce n'est pas vraiment une alerte au sens propre
review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      #- car
      - person
  # en dection, on préfère tout garder donc par défaut
  detections:
    labels:
      - person # entre autre pour l'interphone
      - car
      - cat
      - dog
      - bicycle

# webrtc necessite codec H264. Le 265 ne fonctionne pas. Voir doc compatiliblité webrts android, apple et PC
# https://github.com/AlexxIT/go2rtc#codecs-madness
# l'audio nécessite également le codec opus.
# https://github.com/AlexxIT/go2rtc#codecs-madness
go2rtc:
  log:
  # remove all log section when OK
    format: text
    level: debug

  streams:
    # Config ideale pour webrtc (doc frigate) et compatibilité : H264 et OPUS.
    # Congig idéale dans les caméras pour meilleur transcodage : H264 et AAC
    # On convertit donc les flux comme ci-dessous
    cour-webrtc-main: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/101/#video=copy#audio=copy #audio=opus # pour les enregistrements audio on reste sur le codec d'origine AAC
    cour-webrtc-sub: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/102/#video=copy#audio=opus
    est-webrtc-main: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.4:554/Streaming/Channels/101/#video=copy#audio=copy
    est-webrtc-sub: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.4:554/Streaming/Channels/102/#video=copy#audio=opus
    cour-est-webrtc-main: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.3:554/Streaming/Channels/101/#video=copy#audio=copy
    cour-est-webrtc-sub: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.3:554/Streaming/Channels/102/#video=copy#audio=opus
    terrasse-webrtc-main: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.5:554/Streaming/Channels/101/#video=copy#audio=copy #timeout=20
    terrasse-webrtc-sub: 
      ffmpeg:rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.5:554/Streaming/Channels/102/#video=copy#audio=opus #timeout=20
      # Une ecriture aurait aussi pu etre 1ere ligne le flux RTSP seul sans le mot ffmpeg:
      # Puis rajouter en 2eme ligne : 
      #- "ffmpeg:terrasse-webrtc-sub#audio=opus" #transcodage audio en OPUS
    interphone-webrtc: 
      ffmpeg:rtsp://{FRIGATE_DOORBIRD_LOGIN}:{FRIGATE_DOORBIRD_PASSWORD}@192.168.2.125:554/mpeg/media.amp#video=h264#drawtext=x=30:y=40:fontsize=30:fontcolor=black:box=1:boxcolor=white
    #####tablette-entree-webrtc:
      #####- http://192.168.2.170:2323/?cmd=getCamshot&password={FRIGATE_TABLETTE_PASSWORD}
      # GO2RTC ne sait pas transcoder du HTTP/JPEG vers du RTSP H264. Le transcodage pur échoue.
      # attente info : https://github.com/AlexxIT/go2rtc/issues/246
      #- ffmpeg:http://127.0.0.1:1984/api/stream.mjpeg?src=tablette-entree-webrtc#video=h264"
      #- ffmpeg:tablette-entree-webrtc#video=h264#hardware # ré-enconde dans go2rtc les captures d'images en flux h264

  webrtc:
    #listen: ":8555"
    candidates:
      - 192.168.2.31:8555
      #- 192.168.2.10:8555
      - stun:8555

cameras:
  frigate_cour: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy #les cams HIK sont déjà en AAC, ideal pour le record
      inputs:
        # secondary stream for detection
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
        - path: rtsp://127.0.0.1:8554/cour-webrtc-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/101/ # <----- Add stream you want to record from
        - path: rtsp://127.0.0.1:8554/cour-webrtc-main
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cour-webrtc-sub
    motion:
      mask: 0.015,0.073,0.313,0.068,0.312,0.018,0.016,0.022
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    snapshots: # <----- Enable snapshots
      enabled: true
      # required_zones:
      #   - rue
      #   - cour_all
    zones:
      rue:
        coordinates: 
          0.738,0.028,0.998,0,0.006,0.016,0.003,0.346,0.056,0.303,0.112,0.274,0.124,0.21,0.208,0.108,0.399,0.049,0.406,0.173,0.626,0.123,0.628,0.03 # entrée de la rue
        objects: car
        inertia: 3
        loitering_time: 0
      parking:
        coordinates: 
          0.134,0.211,0.12,0.338,0.085,0.448,0.005,0.546,0.005,0.695,0,1,0.222,1,0.567,1,1,1,1,0.436,1,0.385,1,0.013,0.943,0.017,0.634,0.038,0.632,0.162,0.541,0.17,0.398,0.196,0.394,0.057,0.212,0.117 # zone parking
        inertia: 3
        loitering_time: 0
      voisin:
        coordinates: 0,0.356,0.123,0.273,0.114,0.334,0.084,0.433,0.004,0.539,0,0.4
        loitering_time: 0
        inertia: 3
    ### TODO a verifier ??? Je sais plus ce que c'est ???
    #review:
    #  alerts:
    #    required_zones: rue
    #objects:
    # on peut specifier la taille des objets , threeold and cie spécifique à un objet et une camera du coup
    #  filters:
    #    person: {}

    review:
      alerts:
        #labels: #bien verifier qu'on a les labels définis dans la section générale, pas sur puisqu'on a le reviexw dans la caméras. Est ce que tous les params sous revew sont récupérés ou non ?
        required_zones: parking
      detections:
        #labels: #bien verifier qu'on a les labels définis dans la section générale
        required_zones:
          - voisin
          - rue
  frigate_est: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy # pas de transcodage du flux audio en AAC car la cam est déjà en AAC
      inputs:
        # secondary stream for detection
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
        - path: rtsp://127.0.0.1:8554/est-webrtc-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/101/ # <----- Add stream you want to record from
        - path: rtsp://127.0.0.1:8554/est-webrtc-main
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: est-webrtc-sub
    motion:
      mask: 0.02,0.069,0.318,0.064,0.317,0.014,0.021,0.018
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    snapshots: # <----- Enable snapshots
      enabled: true

  frigate_cour_est: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy # pas de transcodage du flux audio en AAC car la cam est déjà en AAC
      inputs:
        # secondary stream for detection
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
        - path: rtsp://127.0.0.1:8554/cour-est-webrtc-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.6:554/Streaming/Channels/101/ # <----- Add stream you want to record from
        - path: rtsp://127.0.0.1:8554/cour-est-webrtc-main
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: cour-est-webrtc-sub
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    snapshots: # <----- Enable snapshots
      enabled: true
    motion:
      mask: 0.024,0.015,0.024,0.064,0.326,0.068,0.322,0.018,0.137,0.018
    zones:
      parking:
        coordinates: 0.256,0.165,0.253,1,1,1,1,0.22,0.602,0.013,0.561,0.012,0.538,0.089,0.258,0.095
        loitering_time: 0
        inertia: 3
        filters:
          # plus permissif que les parametres globaux pour détecter les personnes arrivant des graviers
          person:
            min_score: 0.6
            threshold: 0.7

    review:
      alerts:
        required_zones: parking
  frigate_terrasse: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy # pas de transcodage du flux audio en AAC car la cam est déjà en AAC
      inputs:
        # secondary stream for detection
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.5:554/Streaming/Channels/102/ # <----- The stream you want to use for detection
        - path: rtsp://127.0.0.1:8554/terrasse-webrtc-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        #- path: rtsp://{FRIGATE_HIK_LOGIN}:{FRIGATE_HIK_PASSWORD}@192.168.2.5:554/Streaming/Channels/101/ # <----- Add stream you want to record from
        - path: rtsp://127.0.0.1:8554/terrasse-webrtc-main
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: terrasse-webrtc-sub
    motion:
      mask: 0.012,0.076,0.326,0.074,0.325,0.014,0.012,0.014
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    snapshots: # <----- Enable snapshots
      enabled: true

  frigate_doorbird: # <------ Name the camera
    enabled: true
    ffmpeg:
      # pas d'audio dans le flx doorbird
      #output_args:
        #record: preset-record-generic-audio-copy # pas de transcodage car webrtc a déjà trancosé l'audio en AAC
        # record: preset-record-generic-audio-aac  # transcodage du flux audio en AAC
        # TODO : verifier le playabck de clip. la doc frigate indique qu'il faut obligatoirement un flux audio meme vide pour lire le strem. Rajouter le preset en commentaire au besoin
      inputs:
        # secondary stream for detection
        #- path: rtsp://{FRIGATE_DOORBIRD_LOGIN}:{FRIGATE_DOORBIRD_PASSWORD}@192.168.2.125:554/mpeg/media.amp # <----- The stream you want to use for detection
        - path: rtsp://127.0.0.1:8554/interphone-webrtc
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: interphone-webrtc
    motion:
      mask:
        - 1233,286,1230,344,1169,349,1168,295  # parking en haut à droite de la caméra (immeuble)
    detect:
      enabled: true #  par defaut pas de déection d'objet <---- disable detection until you have a working camera feed
    record: # <----- Enable recording. Par defaut Frigate voir section gébérale, recording uniquement sur detection d'objet
      enabled: true
    snapshots: # <----- Enable snapshots
      enabled: true
    zones:
      rue:
        coordinates: 0,0.483,0.003,1,0.995,1,1,0.357
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        # Optional: labels that qualify as an alert (default: shown below)
        labels: [] # on ne veut pas d'alerte pour l'interphone, juste des détections sur la zone rue
      detections:
        #labels: #bien verifier qu'on a les labels définis dans la section générale
        required_zones:
          - rue

  # frigate_tab_entree: # <------ Name the camera
  #   enabled: true
  #   ffmpeg:
  #     inputs:
  #        #- path: rtsp://127.0.0.1:8554/tablette-entree-webrtc #pas pris en charge. L'encodage échoue
  #       - path: http://127.0.0.1:1984/api/stream.mjpeg?src=tablette-entree-webrtc
  #          #input_args: preset-rtsp-restream
  #          # Pour l'instant go2rtc ne sait pas gérer autre chose à partir de capture HTTP
  #         input_args: preset-http-mjpeg-generic
  #         roles:
  #           - detect
  #           - record
  #   # commentaire car le webrtc ne fonctionne pas pour cette cam jpeg
  #   #live:
  #    # stream_name: tablette-entree-webrtc
  #   detect:
  #     enabled: false  # <---- disable detection until you have a working camera feed
  #   record:  # <----- Enable recording
  #     enabled: true
  #   snapshots:  # <----- Enable snapshots
  #     enabled: true

camera_groups:
  Cour_Groupe:
    order: 1
    icon: LuMountain
    cameras:
      - frigate_cour
      - frigate_cour_est
```

And my docker-compose config 

```
version: '3.9'

services:

  frigate:
    environment:
      - FRIGATE_HIK_LOGIN=XXXXXXX
      - FRIGATE_HIK_PASSWORD=XXXXXXXXXX
      - FRIGATE_DOORBIRD_LOGIN=XXXXXXXXX
      - FRIGATE_DOORBIRD_PASSWORD=XXXXXXXX
      - FRIGATE_TABLETTE_PASSWORD=XXXXXXX
                
    container_name: frigate
    privileged: false # Because LXC is already in privileged mode
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    #cap_add:
    #  - CAP_PERFMON
    # shm_size est utilisé pour la mémoire pour la détection en RAM 
    shm_size: "256MB" # update for your cameras based on calculation above
    #256, 1024 to test
    devices:
      #- /dev/bus/usb:/dev/bus/usb # for CORAL USB
      - /dev/apex_0:/dev/apex_0 # for CORAL PCIe or M2
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      #- /etc/timezone:/etc/timezone:ro #ne semble pas exister sur le LXC. Frigate travaille de toute façon avec l'UTC
      - /etc/localtime:/etc/localtime:ro
      - /mnt/config/config:/config               # config.yaml et database. Le /mnt/cnfig est monté en fstab dans le conteneur LXC
      #- /config-local:/config            # config en local pour tests
      - /mnt/frigate:/media/frigate       # stockage des medias en records 
      # /tmp/cache est utilisé pour reconstruire les fichiers mp4 avant stockage. 
      # il vaut mieux laisser les lignes suivantes car l'utilisation de la RAM évite l'utilisation du SSD donc augmente sa durée de vie
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
       
      
    ports:
      - "5000:5000"     # API and web gui
      - "8554:8554"     # RTSP feed 
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"     # Go2RTC web interface


```
