### DISCUSSION TITLE
[Support]: Incorrect record directory, time zone is not considered.

### DISCUSSION THREAD

**Discussion by seizu** [blakeblackshear/frigate#17706] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

The time within the Docker container is correct, but the record directory is created based on UTC.

/frigate/record/maintainer.py
Actual:
` 
directory = os.path.join(
            RECORD_DIR,
            start_time.strftime("%Y-%m-%d/%H"),
            camera,
        )
`
Possible fix:
`directory = os.path.join(
            RECORD_DIR,
            start_time.astimezone().strftime("%Y-%m-%d/%H"),
            camera,
        )`  

### Steps to reproduce

Set a TZ in docker-compose.yml
```
environment:
      TZ: Europe/Berlin
```
Record directory looks like
Actual:
> 
> Apr 15 03:45 2025-04-15/01/door_cam/44.31.mp4
> Apr 15 03:46 2025-04-15/01/door_cam/45.31.mp4
> 
Expected:
> 
> Apr 15 03:45 2025-04-15/03/door_cam/44.31.mp4
> Apr 15 03:46 2025-04-15/03/door_cam/45.31.mp4
> 

### Version

0.15.0-cea210d

### Frigate config file

```yaml
cameras:
  door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://myendpoint.local/stream1
          roles:
            - detect
        - path: rtsp://myendpoint.local/stream0
          roles:
            - record
      output_args:
        record: -f segment -segment_time 60 -strftime 1 -segment_format mp4 -c:v copy -c:a aac -strict -2
    detect:
      width: 720
      height: 576
      fps: 5
    record:
      enabled: true
      retain:
        days: 0
      detections:
        retain:
          days: 10
          mode: motion
        pre_capture: 5
        post_capture: 5
    zones: {}
    objects:
      track:
        - person
    motion:
      mask:
        - 0.465,0.511,0.463,0.624,0.595,0.626,0.593,0.509
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri  # (wenn du VAAPI / Intel GPU Beschleunigung nutzt, optional)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/sda1/cloud/ftp:/media/frigate/recordings
    ports:
      - "5000:5000"    # Web-Interface
    environment:
      TZ: Europe/Berlin
```

### Relevant Frigate log output

```shell
no errors
```

### Relevant go2rtc log output

```shell
no errors
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

VKCAM112

### Screenshots of the Frigate UI's System metrics pages

not relevant
