### DISCUSSION TITLE
Frigate 0.15.1 version not updated

### DISCUSSION THREAD

**Discussion by tpjanssen** [blakeblackshear/frigate#17702] [Ask A Question] [answered]
@blakeblackshear 

Thanks for publishing Frigate 0.15.1. However, the docker still says 0.15.0 after installing.

**Comment by tobz-au** [comment]
yep same issue here. shows 0.15.0-6cb5cfb. not exactly the most important thing ever though, just confused me after I upgraded

**Comment by hawkeye217** [comment, marked as answer]
We just forgot to update the version number before publishing. There are only two one-line changes in 0.15.1, so we likely won't be updating the version number with another build.

**Reply by hawkeye217** [reply]
You are running 0.15.1 if the build hash after your version number is `6cb5cfb`.

**Reply by Sarnog** [reply]
Will it be possible with a simple action to change that version number by my self? Or will it be difficult? If it's easy, can you explain to me where i need to change it?

**Reply by NickM-27** [reply]
you could bind mount a newer file to /opt/frigate/frigate/version.py

**Reply by Sarnog** [reply]
I have it installed on an LXC container in proxmox, when i try to go to /opt/frigate/frigate/version.py the directory doesn't excist in my installation. Only /opt/frigate/ and in there are 2 folders config and database, not another frigate folder.

**Reply by NickM-27** [reply]
you need to go into the docker container, you are just in the LXC.

**Reply by MilesTEG1** [reply]
This fix is working fine ;)
Thanks.
![image](https://github.com/user-attachments/assets/8f23e8c0-3366-4b13-a7ad-2cc10ed50b9d)

For those who want to know, here what I did, for my docker installation:
1. Create a version.py file in the folder hosting your frigate data. For it's `/srv/docker/frigate/version_0.15-1_temp_fix/version.py`. This file must contain this (with a ligne return at the end):

```python
    VERSION = "0.15.1-6cb5cfb"

```
3. Create a bind-mount in the `docker-compose.yaml` file:

```yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/frigate/config:/config
      - /srv/docker/frigate/logs:/dev/shm/logs
      - frigate_nas:/media/frigate
       
      # Tempoary fix for the 0.15.1 version not reported as 0.15.1
      - /srv/docker/frigate/version_0.15-1_temp_fix/version.py:/opt/frigate/frigate/version.py
      
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

5. Recreate the container with this new volume.
6. See the version in Sytem Metrics ;)

Normally, no more update in Home Assistant is seen if Frigate is on the 0.15-1.
