### DISCUSSION TITLE
[Detector Support]: Cuda runtime error building models with nVidia 5070

### DISCUSSION THREAD

**Discussion by partofthething** [blakeblackshear/frigate#17714] [Detector Support] [answered]
### Describe the problem you are having

I've been using the tensorrt image for a long time on my ancient nVidia 1060 but started getting hard crashes indicating hardware failure so I upgraded to a 5070. When I swapped them out and upgraded my nvidia drivers (from 560 closed to 570 open) frigate gave helpful messages on boot saying I had to rebuild my models. So I wiped the model cache and restarted. When it tries to build the models, I get the error shown below (`Cuda Runtime (no kernel image is available for execution on the device)`). I'm running on an ubuntu linux machine with ubuntu 24.10.

I suspect that this is because the tensorrt Dockerfile is pointing to a 2023 version of TRT and needs a more recent version for this new card? If that's the case, are there easy instructions somewhere for bumping versions and rebuilding the tensorrt image?

### Version

0.15.1-tensorrt   861d89fe2b0e

### Frigate config file

```yaml
mqtt:
  host: mqtt.local
  enabled: true
  user: username
  password: '{FRIGATE_MQTT_PASSWORD}'

tls:
  enabled: true

auth:
  reset_admin_password: false

record:
  enabled: true
  retain:
    days: 10
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10
birdseye:
  enabled: true
  mode: continuous

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
  labelmap:
    16: dog

motion:
  threshold: 32
  contour_area: 15
  improve_contrast: false
  frame_alpha: 0.03

objects:
  track:
    - person
    - dog
    - car

ffmpeg:
  hwaccel_args: preset-nvidia

go2rtc:
  log:
    exec: trace
  streams:
    kitchen:
      - rtsp://admin:{FRIGATE_KITCHEN_PASS}@192.168.165.229:554/cam/realmonitor?channel=1&subtype=1
    fireplace:
      - rtsp://admin:{FRIGATE_FIREPLACE_PASS}@192.168.165.175:554/cam/realmonitor?channel=1&subtype=1
    ground:
      - rtsp://admin:{FRIGATE_GROUND_PASS}@192.168.165.132:554/cam/realmonitor?channel=1&subtype=1
    ground_high:
        - rtsp://admin:{FRIGATE_GROUND_PASS}@192.168.165.132:554/cam/realmonitor?channel=1&subtype=0
      # back:
      #- rtsp://admin:{FRIGATE_BACK_PASS}@192.168.165.230:554/h264Preview_01_sub

cameras:
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: 
            rtsp://admin:{FRIGATE_KITCHEN_PASS}@192.168.165.229:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 704
      height: 480
    onvif:
      host: 192.168.165.229
      port: 80
      user: admin
      password: '{FRIGATE_KITCHEN_PASS}'
  fireplace:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fireplace
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: 
            rtsp://admin:{FRIGATE_FIREPLACE_PASS}@192.168.165.175:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 640
      height: 480
    onvif:
      host: 192.168.165.175
      port: 80
      user: admin
      password: '{FRIGATE_FIREPLACE_PASS}'
  ground:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ground
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/ground_high
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 640
      height: 480
    onvif:
      host: 192.168.165.132
      port: 80
      user: admin
      password: '{FRIGATE_GROUND_PASS}'

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1-tensorrt
    shm_size: "400mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/homeassistant/.homeassistant/frigate-config:/config/
      - /srv/cams:/media/frigate
      - /opt/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      USE_FP16: true
      YOLO_MODELS: yolov7-320,yolov7x-640
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
rigate  | Creating yolov7-320.cfg and yolov7-320.weights
frigate  | Creating yolov7x-640.cfg and yolov7x-640.weights
frigate  | 
frigate  | Done.
frigate  | 
frigate  | Generating yolov7-320.trt. This may take a few minutes.
frigate  | 
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 244, in <module>
frigate  |     main()
frigate  |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 229, in main
frigate  |     engine = build_engine(
frigate  |   File "/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py", line 114, in build_engine
frigate  |     with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
frigate  | TypeError: pybind11::init(): factory function returned nullptr
frigate  | [04/15/2025-08:40:53] [TRT] [E] 1: [caskUtils.cpp::createCaskHardwareInfo::857] Error Code 1: Cask (no further information)
frigate  | [04/15/2025-08:40:53] [TRT] [E] 1: [checkMacros.cpp::catchCudaError::202] Error Code 1: Cuda Runtime (no kernel image is available for execution on the device)
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

(Can't show because the system will not boot)
