### DISCUSSION TITLE
Recordings seem to take the wrong stream

### DISCUSSION THREAD

**Discussion by jkoopmann** [blakeblackshear/frigate#17721] [Ask A Question]
Hi,

```
Garage: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.x/Streaming/channels/101
          roles:
            - record
        - path: rtsp://x.x.x.x/Streaming/channels/102
          roles:
            - detect
    detect:
      enabled: true
    motion:
      threshold: 40
```

What I observe (even in exports or downloads from frigate): When a recording starts (likely due to motion triggering it) the first stream with HD quality is used. Once an object is detected the recording switches to the second stream. From the above configuration I would have expected the second stream being used for detection but all recording being done on the first stream.

Why is this and is there a way around it (other than putting detect to the HD stream together with record)=
