### DISCUSSION TITLE
Script to post CPU load and CPU temp to MQTT

### DISCUSSION THREAD

**Discussion by tubalainen** [blakeblackshear/frigate#1772] [Show and tell]
Depending on your Frigate setup and how many cameras you are using the machine you are running Frigate on can be tormented with high CPU usage for a long time (if the wind is blowing, lots of movements in the motion areas etc).

Ive created this cron script that posts the CPU temp and CPU usage to MQTT.

**EDIT** - Or just use Glances instead https://github.com/nicolargo/glances thanks Minglarn!
`docker run -d --name glances -e GLANCES_OPT="-w" -v /usr/share/dockers/glances:/glances/conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host nicolargo/glances:latest-full
`

The temperature only works if you are running the OS on directly on your machine, not in a VM.

**Pre-reqs**
`apt install lm-sensors mosqutto-clients coreutils
`
The script ( i placed it in /root/inform_mqtt_status.sh)
You will need to check that all awk/sed etc are working hence the reporting is different of each machine architecture.

```
#!/bin/bash
sensors -j | tr -d '[:space:]' > /tmp/cputemp
mosquitto_pub -h 192.168.1.10 -u username -P passwd -t docker05/cputemp -f /tmp/cputemp

# grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage ""}' > /tmp/cpuload
awk '{u=$2+$4; t=$2+$4+$5; if (NR==1){u1=u; t1=t;} else print ($2+$4-u1) * 100 / (t-t1) ""; }' <(grep 'cpu ' /proc/stat) <(sleep 1;grep 'cpu ' /proc/stat) > /tmp/cpuload
mosquitto_pub -h 192.168.1.10 -u username -P passwd -t docker05/cpuload -f /tmp/cpuload

```
`Add it to crontab
`crontab -e (as root, in my case) runs every minute
`*/1 * * * * /root/inform_mqtt_status.sh`

**Sensors in Home Assistant**
I use a custom integration called "average", can be found in the HACS. How ever, it doesnt support `units_of_measurement` so thats why ive got the template sensors.

```
- platform: mqtt
  state_topic: 'docker05/cputemp'
  name: Docker05 CPU Temp All
  unit_of_measurement: "°C"
  value_template: "{{ value_json['coretemp-isa-0000']['Packageid0']['temp1_input'] }}"
- platform: mqtt
  state_topic: 'docker05/cputemp'
  name: Docker05 CPU Temp Core 0
  unit_of_measurement: "°C"
  value_template: "{{ value_json['coretemp-isa-0000']['Core0']['temp2_input'] }}"
- platform: mqtt
  state_topic: 'docker05/cputemp'
  name: Docker05 CPU Temp Core 1
  unit_of_measurement: "°C"
  value_template: "{{ value_json['coretemp-isa-0000']['Core1']['temp3_input'] }}"
- platform: mqtt
  state_topic: 'docker05/cputemp'
  name: Docker05 CPU Temp Core 2
  unit_of_measurement: "°C"
  value_template: "{{ value_json['coretemp-isa-0000']['Core2']['temp4_input'] }}"
- platform: mqtt
  state_topic: 'docker05/cputemp'
  name: Docker05 CPU Temp Core 3
  unit_of_measurement: "°C"
  value_template: "{{ value_json['coretemp-isa-0000']['Core3']['temp5_input'] }}"

- platform: mqtt
  state_topic: 'docker05/cpuload'
  name: Docker05 CPU Load
  unit_of_measurement: "%"
  value_template: "{{ value_json | round(1) }}"

- platform: average
  name: 'Docker05 average cpu load no unit'
  duration:
    minutes: 15
  entities:
    - sensor.docker05_cpu_load

- platform: average
  name: 'Docker05 average cpu temp no unit'
  duration:
    minutes: 15
  entities:
    - sensor.docker05_cpu_temp_all

- platform: template
  sensors:
    docker05_average_cpu_load:
      friendly_name: 'Docker05 average CPU Load'
      unit_of_measurement: "%"
      value_template: >-
        {{ states.sensor.docker05_average_cpu_load_no_unit.state | round(1) }}
    docker05_average_cpu_temp:
      friendly_name: 'Docker05 average CPU Temp'
      unit_of_measurement: "°C"
      value_template: >-
        {{ states.sensor.docker05_average_cpu_temp_no_unit.state | round(1) }}

```
![image](https://user-images.githubusercontent.com/26795429/133036622-bcd17890-6b1c-456d-8676-93fb74fe2c12.png)
