### DISCUSSION TITLE
go2rtc.yml not updating and streams not showing in go2rtc Web UI

### DISCUSSION THREAD

**Discussion by pdrlmfr** [blakeblackshear/frigate#17734] [Ask A Question] [answered]
I'm currently having an issue with go2rtc integration in Frigate. I've added the following configuration under the go2rtc section in my config.yml:

```
go2rtc:
  streams:
    entrada:
      - rtsp://user:pass@192.168.1.2:554/h264Preview_01_main
    entrada_sub:
      - rtsp://user:pass@192.168.1.2:554/h264Preview_01_sub
 ```
However, after restarting Frigate, these streams do not appear in the go2rtc Web UI (accessible on port 1984). It seems that the go2rtc.yml file is not being updated with the streams I've defined in the Frigate configuration.

Thanks in advance!
