### DISCUSSION TITLE
OpenVino on Intel N100 / N150

### DISCUSSION THREAD

**Discussion by hassos246** [blakeblackshear/frigate#17743] [Ask A Question]
What inference speed is normal on an Intel N150 or N100 CPU? How do I know if I have enough of detectors? Can I have to many?

Im running a yolonas model.

**Comment by NickM-27** [comment]
The docs show various hardware running openvino and the inference speeds. You know you have enough detectors if there is not consistent skipped fps.

**Reply by hassos246** [reply]
I have seen that page. Which CPU on the list would you say is comparable with N100 / N150?

**Reply by NickM-27** [reply]
For some reason I thought the N100 was already on there, I will add it. But the 12600K is similar

**Reply by hassos246** [reply]
And what are the down side of have to many detectors? Or that isn't a thing?

**Reply by NickM-27** [reply]
more GPU RAM usage

**Reply by hassos246** [reply]
I'm getting 25-30 ms on a N150 running a 320 model. I know that the CPU is new and all that. So time will tell if it gets lower as updates rolls out.

**Reply by NickM-27** [reply]
is that running on CPU or GPU though?

**Reply by hassos246** [reply]
GPU according to intel gpu top. Do I need to add more to `model:` in the config?

<img width="1422" alt="Screenshot 2025-04-16 at 21 24 33" src="https://github.com/user-attachments/assets/73184889-c44d-4d5b-a0c4-77785090f9a5" />

<img width="1422" alt="Screenshot 2025-04-16 at 21 27 17" src="https://github.com/user-attachments/assets/de76d0d0-b634-4d13-aaf7-777d1c2a018f" />

```
detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
  ov_2:
    type: openvino
    device: GPU

model:
  path: plus://7efe1d2424d8522a3f292a4efXXXXXXX
```
