### DISCUSSION TITLE
[Support]: Parked car detection

### DISCUSSION THREAD

**Discussion by TimNiceButDim** [blakeblackshear/frigate#17742] [General Support]
### Describe the problem you are having

I read that car park detection is supposed to be better in newer version of Frigate but this doesn't seem to be the case for me. 
<img width="1320" alt="Screenshot 2025-04-16 at 19 14 22" src="https://github.com/user-attachments/assets/fe9a8433-7634-4b6f-bc49-0797fdfa7369" />

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
detectors:
  ov:
    type: openvino
    device: GPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
go2rtc:
  streams:
    front_camera:
      - ffmpeg:http://192.168.1.51/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx#video=copy#audio=copy#audio=opus
    front_camera_sub:
      - ffmpeg:http://192.168.1.51/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx
    garage_camera:
      - ffmpeg:http://192.168.1.219/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx#video=copy#audio=copy#audio=opus
    garage_camera_sub:
      - ffmpeg:http://192.168.1.219/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxx
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - dog
    - car
    - mouse
cameras:
  front_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_camera_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_camera # <----- The stream you want to use for record
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    zones:
      Driveway:
        coordinates: 
          0.086,0.439,0,0.446,0.21,0.248,0.344,0.204,0.442,0.278,0.557,0.29,0.665,0.309,0.737,0.321,1,0.936,1,1,0.685,1,0.675,0.864,0.503,0.866,0.151,0.732,0.088,0.708,0.06,0.581,0.106,0.479
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - mouse
          - person
      Drive:
        coordinates: 
          0.436,0.273,0.437,0.273,0.159,0.692,0.677,0.843,0.689,0.962,0.918,0.972,0.732,0.156,0.463,0.13,0.439,0.251
        inertia: 3
        loitering_time: 4
        objects: car
    motion:
      mask:
        - 0.009,0.925,0.422,0.926,0.423,0.978,0.007,0.983
        - 0,0.336,0.108,0.256,0.136,0.218,0.171,0.218,0.221,0.108,0.275,0.11,0.328,0.045,0.399,0.048,0.404,0,0.001,0.002
        - 0.701,0,0.828,0.269,0.997,0.264,0.997,0.002
  garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_camera_sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garage_camera # <----- The stream you want to use for record
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    motion:
      mask:
        - 0.01,0.93,0.421,0.926,0.422,0.974,0.01,0.978
        - 0,0,0,0.18,1,0.093,1,0
        - 0.553,0.131,0.641,0.125,0.633,0.236,0.552,0.219
        - 0.71,0.118,0.805,0.314,0.831,0.398,1,0.904,1,0.087,0.777,0.109
version: 0.15-1
camera_groups:
  Home:
    order: 1
    icon: LuActivity
    cameras:
      - front_camera
      - garage_camera
notifications:
  enabled: 'true'
  email: 
tls:
  enabled: false
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Unsure how to do this.
```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Reolink CX410
