### DISCUSSION TITLE
[Bug]: Container 6cb5cfb tagged 0.15.1 but is 0.15.0

### DISCUSSION THREAD

**Discussion by ejpenney** [blakeblackshear/frigate#17740] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Got the notification that 0.15.1 was available but when I try to pull `ghcr.io/blakeblackshear/frigate:stable` I still get 0.15.0. Looking at [the release](https://github.com/blakeblackshear/frigate/pkgs/container/frigate/394110795?tag=6cb5cfb) I suspect this is wrong, as the image is tagged 0.15.1

Home assistant custom component is reporting 0.15.0 (via API), and I see the same in System Metrics on all browsers.

### Steps to reproduce

1. docker compose down
2. docker image prune
3. docker compose up
...

### Version

0.15.0

### Frigate config file

```yaml
mqtt:
  host: x.x.x.8
  user: mqtt
  password: REDACTED

go2rtc:
  streams:
    dashboard_stream: ffmpeg:http://x.x.x.67:2971/camera/stream#video=h264#hardware
    original_run_cam:
      - rtsp://REDACTED:REDACTED@x.x.x.70/live
    rotated_run_cam:
      - ffmpeg:original_run_cam#video=h264#rotate=90#hardware

cameras:
  Coop:
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED:REDACTED@x.x.x.59/live
          roles:
            - rtmp
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080

    objects:
      track:
        - bird

  Catio:
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.32:8554/catio-cam
          roles:
            - rtmp
            - detect
            - record

    detect:
      enabled: true
      width: 1920
      height: 1080

    objects:
      track:
        - cat

  Chicken_Run:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/rotated_run_cam
          input_args: preset-rtsp-restream
          roles:
            - rtmp
            - detect
            - record
    detect:
      enabled: true
      width: 1080
      height: 1920

    objects:
      track:
        - bird
        - person

  Gate:
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.32:8554/gate-cam
          roles:
            - rtmp
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080

    motion:
      mask:
        - 362,554,84,0,0,0,0,720,495,720
        - 263,35,259,0,1280,0,1280,720

  Dashboard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dashboard_stream
          roles:
            - rtmp
            - detect
    detect:
      enabled: true
      width: 1920
      height: 1080

detectors:
  coral:
    type: edgetpu
    device: usb


record:
  enabled: true
  retain:
    days: 3
    mode: active_objects
  sync_recordings: true

ffmpeg:
  hwaccel_args: preset-vaapi


environment_vars:
  LIBVA_DRIVER_NAME: i965
version: 0.15-1
camera_groups:
  Chickens:
    order: 1
    icon: LuBird
    cameras:
      - Chicken_Run
      - Coop
  Backyard:
    order: 2
    icon: LuSunMoon
    cameras:
      - Gate
      - Chicken_Run
      - Catio
```

### docker-compose file or Docker CLI command

```yaml
services:
#######################FRIGATE
  frigate:
    privileged: true # EJP: Seems to be necessary for GPU usage in my env (still/WIP)
    # Check host system's actual render/video/plugdev group IDs with 'getent group render', 'getent group video', and 'getent group plugdev'
    # Must add these exact IDs in container's group_add section or OpenVINO GPU acceleration will fail
    group_add:
      - "106" # render
      - "44"  # video
      - "46"  # plugdev
    deploy: # EJP: Added because ffmpeg is very badly behaved
      resources:
        limits:
          cpus: '2'
          memory: 4gb
    container_name: frigate
    devices:
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
      - /dev/bus/usb:/dev/bus/usb # Uncomment for Google Coral USB
      - /dev/dri/renderD128:/dev/dri/renderD128
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/frigate/config:/config
      - /home/frigate/media:/media/frigate
      - /dev/bus/usb:/dev/bus/usb # Uncomment for Google Coral USB
      - type: tmpfs # EJP: Added to make ffmpeg behave better
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      YOLO_MODELS: ""
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

N/A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b117d547-4e33-4d9c-b532-23026dfc6141)
Image depicts System Metrics panel that states 0.15.0-6cb5cfb while this same image is tagged 0.15.1 in GHCR.
