### DISCUSSION TITLE
[Support]: Unable to update to 0.15.1 from 0.15.0

### DISCUSSION THREAD

**Discussion by woody4165** [blakeblackshear/frigate#17756] [General Support] [answered]
### Describe the problem you are having

Hi

I'm trying to update from 0.15.0 to 0.15.1 in docker but I still get `Starting Frigate (0.15.0-6cb5cfb)` when restarting 
I've followed the update instruction at [https://docs.frigate.video/frigate/updating](https://docs.frigate.video/frigate/updating) with `stable` tag and also with `0.15.1` tag with same result

What can I check?

Thanks

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Opra 117.0.5408.197 and Chrome 135.0.7049.96

### Frigate config file

```yaml
is it needed in this situation?
```

### Relevant Frigate log output

```shell
2025-04-17 13:12:42.762947527  [2025-04-17 13:12:42] frigate.app                    INFO    : Starting Frigate (0.15.0-6cb5cfb)
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate15
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri:/dev/dri # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config:/config
      - /root/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984/tcp" # go2rtc
    environment:
      - FRIGATE_RTSP_PASSWORD=pass
      - LIBVA_DRIVER_NAME=iHD
      - VAAPI_DRIVER=iHD
      - PLUS_API_KEY=xxxxx
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Imou
