### DISCUSSION TITLE
Gemini GenAi challenge

### DISCUSSION THREAD

**Discussion by jkoopmann** [blakeblackshear/frigate#17767] [Ask A Question] [answered]
Hi,

just trying to get GenAI to work. 

```
genai:
  enabled: True
  provider: gemini
  api_key: "hidden"
  model: gemini-1.5-flash


semantic_search:
  enabled: True
  reindex: False
```

When I regenerate on an event I can see the green "sent this request to Gemini" popup. But no description comes. In the Google Dashboard I see

google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent Error 100%.

The requests reach google but the run into an error. I have no clue how to look for the error or debug this. Any help would be greatly appreciated.

And is "use snapshot = True" recommended?

Regards
   JP
