### DISCUSSION TITLE
Audio working live, no audio in recordings

### DISCUSSION THREAD

**Discussion by HelloMihai** [blakeblackshear/frigate#17765] [Ask A Question] [answered]
Audio is working in firefox / chrome (not safari) for Live playback, but theres no audio in the recordings.

heres my config.  Thank you

```
mqtt: {enabled: false} ## if sending alerts to outher services like Home Assistant

## go2rtc restream combining audio with the video
go2rtc:
  streams:
    CAM_NAME_wyzeV2: [rtsp://myuser:mypassword@123.321.123.321/live, "ffmpeg:CAM_NAME_wyzeV2#audio=opus"]
    CAM_NAME_wyzeV3: [rtsp://myuser:mypassword@123.321.123.321/live, "ffmpeg:CAM_NAME_wyzeV3#audio=opus"]

## play stream created from go2rtc with audio mixed
cameras:
  CAM_NAME_wyzeV2:
    enabled: true
    audio: { enabled: true }
    record: { enabled: true, retain: {days: 5, mode: all} }
    ffmpeg:
      output_args: { record: preset-record-generic-audio-copy }
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV2, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]
      
  CAM_NAME_wyzeV3:
    enabled: true
    audio: {enabled: true}
    record: {enabled: true, retain: {days: 5, mode: all}}
    ffmpeg:
      output_args: { record: preset-record-generic-audio-copy }
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV3, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]

version: 0.15-1
```

**Comment by hawkeye217** [comment]
See the documentation: https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Reply by HelloMihai** [reply]
Sorry, it still doesnt work.  I have previously tried the output args but theres still not audio in the recordings

```
cameras:
  CAM_NAME_wyzeV2:
    enabled: true
    audio: { enabled: true }
    record: { enabled: true, retain: {days: 5, mode: all} }
    ffmpeg:
      output_args: { record: preset-record-generic-audio-aac } # TRIED BASED DOCS FOR RECORDINGS WITH AUDIO
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV2, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]
   
```

**Reply by hawkeye217** [reply, marked as answer]
I'd suggest encoding to AAC directly with go2rtc, then.

```
go2rtc:
  streams:
    CAM_NAME_wyzeV2: ["ffmpeg:rtsp://myuser:mypassword@123.321.123.321/live#video=copy#audio=aac", "ffmpeg:CAM_NAME_wyzeV2#audio=opus"]
    CAM_NAME_wyzeV3: ["ffmpeg:rtsp://myuser:mypassword@123.321.123.321/live#video=copy#audio=aac", "ffmpeg:CAM_NAME_wyzeV3#audio=opus"]
```

**Reply by HelloMihai** [reply]
thank you, I can hear the audio in the alerts and past recordings.

for anyone looking, heres the working config with wyze v2 and v3 using the RTSP custom firmware

```
mqtt: {enabled: false}

go2rtc:
  streams:
    CAM_NAME_wyzeV2: ["ffmpeg:rtsp://myuser:mypassword@123.321.123.321/live#video=copy#audio=aac", "ffmpeg:CAM_NAME_wyzeV2#audio=opus"]
    CAM_NAME_wyzeV3: ["ffmpeg:rtsp://myuser:mypassword@123.321.123.321/live#video=copy#audio=aac", "ffmpeg:CAM_NAME_wyzeV3#audio=opus"]

cameras:
  CAM_NAME_wyzeV2:
    enabled: true
    audio: { enabled: true }
    record: { enabled: true, retain: {days: 5, mode: all} }
    ffmpeg:
      output_args: { record: preset-record-generic-audio-copy }
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV2, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]
      
  CAM_NAME_wyzeV3:
    enabled: true
    audio: {enabled: true}
    record: {enabled: true, retain: {days: 5, mode: all}}
    ffmpeg:
      output_args: { record: preset-record-generic-audio-copy }
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV3, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]

version: 0.15-1
```
