### DISCUSSION TITLE
Frigate Android apps -> I can't reorder cameras

### DISCUSSION THREAD

**Discussion by dvb-code** [blakeblackshear/frigate#17769] [Ask A Question] [answered]
Hi,

I am using Frigate since a few days, and I am really impressed by its features. 
Thanks a lot for this clever solution !

I am trying to modify order on my cameras. 
As the documentation explains, I used "ui order" syntax like this :

```
cameras:

  Doorbird:
    ui:
      order: 0  
      dashboard: True
...        

  cam01_gge-ma:
    ui:
      order: 3  
...

  cam09_jardin_av:
    ui:
      order: 2  

```

It's OK in web ui (Firefox/Chromium) , but it's not working in "Frigate Android apps".
-> Did I missed something, or it's impossible to reorder in Android apps ?

Thank you.
