### DISCUSSION TITLE
Performance -- Detection on Google Coral vs CPU

### DISCUSSION THREAD

**Discussion by HelloMihai** [blakeblackshear/frigate#17768] [Show and tell]
just installed the USB google coral TPU today and it was a breeze.  Wanted to share the performance results monitoring with `btop`

my setup.  ubuntu headless 24.04, plugged USB Coral in, added the line to docker compose
```
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral
```
updated the frigate config
```
detectors:
  coral: { type: edgetpu, device: usb }
    
cameras:
  my_camera:
    ...
    ffmpeg:
      inputs:
        roles: [record, detect] ## add detect
```
![image](https://github.com/user-attachments/assets/ddf2f469-a444-4dc1-951e-9409b9a1921d)

can easily identify with `btop` and filter for `detector` to see the process
![image](https://github.com/user-attachments/assets/c4b854d7-84e1-47aa-a9f5-f1b59d148e3d)
