### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by Amadou91** [blakeblackshear/frigate#17766] [Config Support] [answered]
### Describe the problem you are having

Hello,

With the new bird classifier in Frigate 0.16, I'm wondering if it's currently possible to adjust detection thresholds for specific bird labels individually.

i.e.
  bird.starling:            {min_score: 0.7,  threshold: 0.9}
  bird.wild_turkey:            {min_score: 0.7,  threshold: 0.9}

I understand this might not be supported, but I’d like to confirm whether:

  1. Per-label tuning like the above is possible or on the roadmap
  2. There’s a workaround using label-specific zones or events (i.e. Turkey can be in a zone, but not a Starling)

### Version

0.16

### Frigate config file

```yaml
objects:
  track:
    [person, face, car, license_plate, amazon, fedex, ups, dhl, purolator,
     dog, cat, deer, bird, raccoon, fox, squirrel, rabbit, package, waste_bin]
  filters:
    dog:            {min_score: 0.7,  threshold: 0.9}
    cat:            {min_score: 0.65, threshold: 0.8}
    face:           {min_score: 0.5}
    package:        {min_score: 0.65, threshold: 0.7}
    license_plate:  {min_score: 0.4,  threshold: 0.5}
    amazon:         {min_score: 0.75}
    ups:            {min_score: 0.75}
    fedex:          {min_score: 0.75}
    person:         {min_score: 0.65, threshold: 0.85}
    car:            {min_score: 0.65, threshold: 0.85}
    bird:           {min_score: 0.5,  threshold: 0.65}
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Home Assistant OS

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral
