### DISCUSSION TITLE
Add to frigate button missing / Cannot tech false positive

### DISCUSSION THREAD

**Discussion by jkoopmann** [blakeblackshear/frigate#17774] [Ask A Question] [answered]
Hi,

in rare occasions I have something similar to this:

A few minutes ago frigate decided there is a package on the porch (alert). Well there isn't. Ok. So I went to review, clicked the little package symbol in the "event" and see a picture of my torch without any boundary boxes. I wanted to hit the frigate+ button but it is not there....

There also is not snapshot in the snapshot dir for this event (while others from the sam camera are saved).

I fail to understand the logic. Also I wanted to see what boundary box kicked of the package alert but cannot do so. With an unchanged configs other alerts same region/camera behave totally correct.

Regards
   JP

**Comment by jkoopmann** [comment]
Little correction: in case of the package I CAN hit an existing frigate+ button but do not get the "This is a package" or "This is NOT a package" dialog and cannot upload it.

I have other instances in which the button is not there at all.

**Reply by jkoopmann** [reply]
At least in the package instance it looks as if the event is in a "loop". Looking at the object cycle I get

"Package entered ZoneName" 

every few seconds. I never get a leave... That in this instance might explain why I cannot proceed but what could be a reason for the ongoing new events? It might discover a million packages but why. :-) It is far away from the camera. For some of the events I get "no image" in the object lifecycle. For others a small red boundary box. But still I cannot report as a false positive...

**Reply by jkoopmann** [reply]
Maybe related.

Just got an alert:

<img width="244" alt="image" src="https://github.com/user-attachments/assets/381f5ccb-60b7-49cc-bde4-d030d553deb5" />


There was a package. There was a person. There was no bicycle. I have three photos beneath this. First one showing a package with the boundary box. Second one showing the person with a boundary box. Third one without any detection and without boundary boxes. When I hit the magnify glasses to the right of the object name for the first two I get thumbnails. For the bicycle I get "no tracked objects found" (which is pretty inconsistent since the screen before explicitly listed a bicycle with 90%. And I cannot send it to frigate+ since there is no object. 

For the first two when I hit the frigate+ button I get the snapshot with boundary box and "this is a xxx" dialog. For the third one I get the said snapshot of the camera without any object or boundary boxes and no "this is a xxx" dialog.

**Reply by hawkeye217** [reply]
We'll need to see your full frigate config to be able to help.

**Reply by jkoopmann** [reply]
Just excluded the cameras not necessary for this debugging. Otherwise:

```
go2rtc:
  streams:
    Haustuer:
      - rtsp://XXX
      - ffmpeg:Haustuer#audio=aac

cameras:
  Haustuer: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Haustuer
          roles:
            - record
            - detect
    detect:
      enabled: true
    genai:
      enabled: True
      use_snapshot: False
      objects:
        - person
    motion:
      threshold: 50
      mask:
        - 0.005,0.01,0.328,0.01,0.325,0.062,0.006,0.066
        - 0.326,0.05,0.332,0.223,0.443,0.241,0.51,0.369,0.564,0.391,0.796,0.636,0.998,0.888,0.997,0.004,0.325,0.004
      contour_area: 35
      improve_contrast: false
    zones:
      Essecke_Kueche:
        coordinates: 0.176,0.23,0.325,0.196,0.426,0.252,0.43,0.354,0.179,0.39
        loitering_time: 0
      Haustuer_Koopmann:
        coordinates: 
          0.176,0.527,0.349,0.499,0.382,0.604,0.513,0.564,0.902,0.994,0.003,0.997,0.004,0.078,0.168,0.078
        loitering_time: 0
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - bicycle
        - amazon
        - ups
        - package
        - gls
        - dhl
        - motorcycle
        - deer
      mask: 
        0.328,0.011,0.332,0.224,0.444,0.246,0.555,0.322,0.556,0.382,0.825,0.668,1,0.878,0.994,0.009
      filters:
        person:
          mask:
            - 0.328,0.011,0.332,0.224,0.444,0.246,0.555,0.322,0.556,0.382,0.825,0.668,1,0.878,0.994,0.009
            - 0.546,0.8,0.797,0.795,0.811,0.99,0.54,0.987

  

detect:
  fps: 5


record:
  enabled: true
  retain:
    days: 2
    mode: motion  # Retain recordings with motion detected for 3 days
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 30
      mode: active_objects  # Retain alert recordings for 30 days
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: active_objects  # Retain detection recordings for 30 days


snapshots:
  enabled: true  # Aktiviert das Speichern von Snapshots
  clean_copy: true  # Optional: Speichert eine saubere PNG-Version des Snapshots
  timestamp: true  # Optional: Fügt einen Zeitstempel auf dem Snapshot hinzu
  bounding_box: true  # Optional: Zeichnet eine Begrenzungsbox um erkannte Objekte
  crop: false  # Optional: Schneidet den Snapshot zu
  retain:
    default: 10
    objects:
      person: 30
      car: 30



detectors:
   coral:
    type: edgetpu
    device: pci


model:
   path: plus://XXX


timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tr
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%d.%m.%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid

motion:
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8


objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - bicycle
    - car
    - amazon
    - ups
    - package
    - gls
    - dhl
    - motorcycle
  filters:
    person:
      min_score: .65
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    package:
      min_score: .65
      threshold: .85


review:
  alerts:
    labels:
      - person
      - bicycle
      - car
      - motorcycle
      - package
  detections:
    labels:
      - face
      - license_plate
      - dog
      - cat
      - amazon
      - gls
      - dhl
      - ups


ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac


auth:
  enabled: true

genai:
  enabled: True
  provider: gemini
  api_key: „XXX“
  model: gemini-2.0-flash


semantic_search:
  enabled: True
  reindex: False

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
```
