### DISCUSSION TITLE
Adding audio to "Doorbird D1101V"

### DISCUSSION THREAD

**Discussion by dvb-code** [blakeblackshear/frigate#17771] [Ask A Question]
Hello,

I am trying to configure go2rtc to add audio to "Doorbird" video streams .
I found this discussion **https://github.com/blakeblackshear/frigate/issues/7403** , but I am sticky with **go2rtc dashboard** ( I didn't find it in settings menu).

Is there any tutorial for Doorbird ?
Could someone help me to configure go2rtc please ?

Thank you

**Comment by hawkeye217** [comment]
See the official documentation: https://docs.frigate.video/guides/configuring_go2rtc/

**Reply by dvb-code** [reply]
I've read the documentation and I've tried different configurations, but I can't afford to get sound :
```

doorbird_sub:
        - ffmpeg:http://user:password@172.x.y.z/bha-api/video.cgi#video=h264
        - ffmpeg:http://user:password@172.x.y.z/bha-api/audio-receive.cgi#audio=opus#audio=aac

    doorbird_sub:
        - ffmpeg:http://user:password@172.x.y.z/bha-api/video.cgi#video=h264
        - exec:ffmpeg -f mulaw -ar 8000 -i http://user:password@172.x.y.z/bha-api/audio-receive.cgi -f rtsp {output}

    doorbird_sub:
    - ffmpeg:http://user:password@172.x.y.z/bha-api/video.cgi#video=h264
    - ffmpeg:http://user:password@172.x.y.z/bha-api/audio-transmit.cgi#audio=opus
```

If someone using Doorbird D1101v with sound could share his configuration, it would be great.
Thanks !

**Reply by dvb-code** [reply]
I managed to get the right command line. I am sharing,  it might help users.
-> Working with Doorbird D1101v :

```
go2rtc:
  ffmpeg:
    input_mulaw: -f mulaw -ar 8000 -i {input}
    noise_filter: -af highpass=200,lowpass=3000,afftdn

  streams:
    doorbird_sub:
      - rtsp://user:password@ip_doorbird/mpeg/media.amp
      - ffmpeg:http://user:password@ip_doorbird/bha-api/audio-receive.cgi#media=audio#backchannel=0#input=input_mulaw#audio=opus#audio=noise_filter

    doorbird_main:
      - rtsp://user:password@ip_doorbird/mpeg/media.amp#media=video
      - ffmpeg:http://user:password@ip_doorbird/bha-api/audio-receive.cgi#media=audio#backchannel=0#input=input_mulaw#audio=opus#audio=noise_filter
```

```
cameras:

  Doorbird:
    ui:
      order: 0
      dashboard: true
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbird_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbird_main
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: doorbird_main

    detect:
      enabled: true
      height: 480
      width: 640
      fps: 5

    objects:
      track:
        - person
        - cat
        - dog
```
