### DISCUSSION TITLE
[Support]: h.265 is not recorded but working in Live view (sound is not)

### DISCUSSION THREAD

**Discussion by 2Belette** [blakeblackshear/frigate#17777] [General Support]
### Describe the problem you are having

I would like to switch my cameras to h.265 to save some bandwidth/storage, with the same configuration everything is working perfectly fine on h.264 but when I turn ON h.265 on my UNV cameras, I can see the cameras on Live view, but every time I click on any type of detection (Alerts or Detection) I got a "no recording found for this time". I also have another issue on live where the sound is not working anymore on h.265, nor the microphone.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

record:
  enabled: true
  retain:
    days: 10
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10

go2rtc:
  streams:
    main_entrance:
      - rtsp://admin:xxxx@1.1.1.1:554/media/video0
      - ffmpeg:main_entrance#audio=aac

  webrtc:
    candidates:
      - 2.2.2.2:8555
      - stun:8555

audio:
  enabled: true

cameras:
  main_entrance:
    ui:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/main_entrance
          roles:
            - detect
            - audio
            - record

version: 0.15-1
```

### Relevant Frigate log output

```shell
unknown
2025-04-18 09:32:21
unknown
[ WARN:0@15.847] global cap_ffmpeg_impl.hpp:1167 open Unable to read codec parameters from stream (Invalid data found when processing input)
unknown
2025-04-18 09:32:21
unknown
[ERROR:0@15.848] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
unknown
2025-04-18 09:32:51
unknown
25-04-18 09:32:21.533551617
unknown
2025-04-18 09:32:21
unknown
OpenCV(4.9.0) /io/opencv/modules/videoio/src/cap_images.cpp:274: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
unknown
2025-04-18 09:32:51
unknown
25-04-18 09:32:21.533559699
unknown
2025-04-18 09:32:51
unknown
25-04-18 09:32:21.533562130
warning
2025-04-18 09:32:21
frigate.record.maintainer
Failed to probe corrupt segment /tmp/cache/main_entrance@20250418093209+0000.mp4
warning
2025-04-18 09:32:21
frigate.record.maintainer
Discarding a corrupt recording segment: /tmp/cache/main_entrance@20250418093209+0000.mp4
```

### Relevant go2rtc log output

```shell
No error
```

### FFprobe output from your camera

```shell
Can't test
```

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate-0.15.1 --restart=unless-stopped --cap-add=CAP_PERFMON --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/bus/usb:/dev/bus/usb --device
 /dev/dri/renderD128 --shm-size=1524m -v /tmp:/media/frigate -v /etc/frigate/config:/config -e FRIGATE_RTSP_PASSWORD='xxx' -p 8971:8971 -p 8555:8555/tcp -p 8555:8555/udp ghcr.i
o/blakeblackshear/frigate:0.15.1
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

UNV (Uniview) IPC3615SB-ADF28KMC-I0

### Any other information that may be helpful

The frigate log output is repeated every 10 sec continuously, and this seems to be related to the issue to watch the recording.
I tried to play with some parameters on my camera (bitrate, I Frame Interval, SVC, U-Code, Bitrate type between CBR and VBR) but the issue is the same

**Comment by ElectronicBattle** [comment]
I have had endless problems in the past with h.265 (hevc) and I still don't understand exactly why. It is along the lines of h.265 being a partially-closed source solution which means that the way it is implemented by different manufacturers (different chipsets, different firmware) varies greatly and it is difficult to achieve a common approach. In other words, Frigate might be able to do (say) all h.264 cameras because h.264 is open source, but not all h.265 cameras. 

However, very recent changes mean that e.g. Firefox can now render h.265 due to some of the h.265 codec info becoming open source in the last few months. Perhaps some of the above is the reason why you are struggling ... I don't think using FF 137 will solve the problem but it might shed extra light on things.

Note that I am very much a user of Frigate rather than a developer or contributor, and I have very poor understanding of most aspects of it so the above might be entirely irrelevant. If so - sorry!

**Reply by 2Belette** [reply]
Thanks for that and always interesting to read the other experience with h265! and yes you are right the reason I am trying now h.265 is because FF is finally supporting it..

**Reply by ElectronicBattle** [reply]
Mine *is* working so I think you should be able to succeed eventually! 
I am using Floureon cameras

![image](https://github.com/user-attachments/assets/7fe2da19-ce32-4593-bc06-277da263eccd)

Floureon might possibly be  Hikvision clones but they're certainly loaded with Xiongmai firmware which is what the Chinese OEMs all seem to use:

![image](https://github.com/user-attachments/assets/74833e1f-894a-44f0-aafc-5a936229f444)

Here's a couple of snippets from my Frigate `config.yaml` which shows one of my eight cameras (which are h.265 output only), in case it is useful to you. 

![image](https://github.com/user-attachments/assets/2803f561-a3f5-489c-8854-c285738fbbb7)


I have another ("doorbell") camera which is h.264 only which I mention merely to show that you can easily mix and match types (this other camera's config  is not shown below).

![image](https://github.com/user-attachments/assets/3bdc4857-dd5e-46ca-abf0-16c7a8053c01)


```
version: 0.15-1
...
go2rtc:
  log:
    exec: trace
  streams:
    greenhouse:
      - ffmpeg:rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0#video=h264#audio=copy
      - ffmpeg:greenhouse#audio=opus
    
####rtsp is 30060 and webRTC is 30061 (TN Frigate app internals)
  webrtc:
    candidates:
      - 192.168.1.194:30061
      - stun:30061

ffmpeg:
  hwaccel_args: preset-nvidia
  output_args:
    record: preset-record-generic-audio-aac

cameras: 
  greenhouse:
    genai:
      enabled: false # <- enable GenAI for this camera

    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=1/track0 #level1 = SD 640x360 (checked CORRECT); track0 media=0 are the only working options tested in ffplay
          roles:
            - detect

        - path: rtsp://192.168.1.123:554/media=0/channel=0&level=0/track0 #level0 = HD 1920x1080(checked CORRECT);  track0 media=0 are the only working options tested in ffplay
          roles:
            - record

```
