### DISCUSSION TITLE
Using a dedicated go2rtc instance to proxy my cameras to frigate (15.1)

### DISCUSSION THREAD

**Discussion by sshort1955** [blakeblackshear/frigate#17784] [Ask A Question]
With that in mind, how should that impact how I use got2rtc in Frigate? 
Right now (version 15.0, Docker compose :stable:) I am using this global ffmpeg preset:
ffmpeg:
#  hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264

I then have the integrated go2rtc set up to pull streams from the 8554 stream from my dedicated proxy:

```
go2rtc:
  streams:
    1_frontyard_cam: rtsp://192.168.0.99:8554/1_frontyard_cam
```
What about the ffmpeg presets for each input? For each input  I have  these settings:

```
  1_frontyard_cam:
    ffmpeg:
#      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/1_frontyard_cam
          input_args: preset-rtsp-restream
          roles:
            - record
```
Things are mostly OK, but sometimes get a watchdog and  ffmpeg error in the frigate go2rtc. The proxy go2rtc instance is pretty much error free.

I guess that the root of my question is regarding whether the go2rtc in frigate is redundant and only adding to my latency? 

I don't want to move the camera's streams directly to frigate because I have other systems that feed off of the proxy, and I need to shut frigate down during the day while I'm at home to reduce the load on my systems, but need the feeds for other systems while frigate is down.
