### DISCUSSION TITLE
Slow Detector Inference speed - ROCm

### DISCUSSION THREAD

**Discussion by megaratboy96** [blakeblackshear/frigate#17786] [General]
Hello everyone. I recently setup Frigate on Debian 12 using docker compose. I have a Radeon RX6700 XT. I setup ROCm using AMDs  instructions at rocm.docs.amd.com. My onnx detector is sitting at 52-85ms with one camera, I am using Yolo nas S. Did I so something wrong, or is this expected behavior? I am unsure if the slow speeds are because I use an uncommon GPU.

Docker compose:
```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-rocm
    shm_size: 256mb # update for your cameras based on calculation above
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    devices:
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/stacks/frigate/data/config:/config
      - /mnt/data/frigate/media:/media/frigate
      - /opt/stacks/frigate/data/models:/models
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    env_file:
      - .env
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
      - HSA_OVERRIDE_GFX_VERSION=${HSA}
      - FRIGATE_RTSP_PASSWORD: ${PASS}
```

Frigate config:
```
mqtt:
  enabled: false

detectors:
  onnx:
    type: onnx

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/models/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

semantic_search:
  enabled: true
  reindex: false

genai:
  enabled: true
  provider: ollama
  base_url: http://192.168.8.163:11434
  model: llava-llama3
  prompt: Analyze the {label} in these images from the {camera} security camera. Focus
    on the actions, behavior, and potential intent of the {label}, rather than describing
    its appearance.
  object_prompts:
    person: Examine the main person in these images. What are they doing and what
      might their actions suggest about their intent (e.g., approaching a door, leaving
      an area, standing still)? Do not describe the surroundings or static details.
    car: Observe the primary vehicle in these images. Focus on its movement, direction,
      or purpose (e.g., parking, approaching, circling). If it's a delivery vehicle,
      mention the company.
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
snapshots:
  enabled: true
  timestamp: true
go2rtc:
  webrtc:
    candidates:
      - 192.168.8.163:8555
  streams:
    Baby_cam_1_main:
      - rtsp://admin:redacted@192.168.8.25:554/Preview_01_main
      - ffmpeg:Baby_cam_1_main#audio=opus#hardware


audio:
  enabled: false
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 200
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - crying
    - meow
    - growl
    - hiss
    - purr
    - biting
    - crackling
    - scraping
    - whisking
    - gunshot

cameras:
  Baby_cam_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:redacted@192.168.7.25:554/Preview_01_sub
          roles:
            - detect
            - audio
        - path: rtsp://admin:redacted@192.168.7.25:554/Preview_01_main
          roles:
            - record
    genai:
      enabled: true # <- enable GenAI for your front camera
      use_snapshot: true
    detect:
      width: 640 # <- optional, by default Frigate tries to automatically detect resolution
      height: 360 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 7
    objects:
      track:
        - cat
    onvif:
      host: 192.168.7.25
      port: 8000
      user: admin
      password: redacted

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

version: 0.15-1

notifications:
  enabled: 'true'
  email: redacted@gmail.com
```
