### DISCUSSION TITLE
[Config Support]: Help with Package detection / No alert will be generated

### DISCUSSION THREAD

**Discussion by AdmiralRaccoon** [blakeblackshear/frigate#17799] [Config Support] [answered]
### Describe the problem you are having

Hi there,
I would be grateful if someone can tell if there´s something wrong/missing in my config file, as I´m out of ideas
My goal is to recieve a notification with a screenshot when a package will be delivered through the gap in my carpot cover.

What happens now is that the package will be pushed  through the cover, but no alert will be triggered.
However, If I look into the debug view, I can see that frigate identifies the package:

![Screenshot 2025-04-19 122418](https://github.com/user-attachments/assets/f30e3f68-5bf2-4632-9e71-5dc8b4294375)

But that´s it. No recorded event ot something to look at in the Explore section. I do get a notification, when I´m picking up the package from the rear entrance, though, but that´s a little late:

![image](https://github.com/user-attachments/assets/f13d1173-0c3e-4471-b0d2-a2632689591c)

I shortened the config file below to the affected camera, as the other cams doing their job perfectly.
Thank you for some hints and happy Easter!
Philipp

### Version

0.15.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.99
  user: xxxxxx
  password: xxxxxx

#birdseye:
#  enabled: True
#  mode: objects

go2rtc:
  streams:
    cam_carport:
      - rtsp://administrator:xxxxxxx@192.168.1.85:554/stream1


genai:
  enabled: false
  provider: gemini
  api_key: xxxxxx
  model: gemini-1.5-flash

cameras:
  cam_carport:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://administrator:xxxxx@192.168.1.85:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - package
        - face
        - cat
        - dog
      filters:
        dog:
          mask: 0.461,0.013,0.973,0.279,0.893,0.715,0.446,0.306
        package:
          min_area: 0
          min_ratio: 0
          max_ratio: 1000
          min_score: 0
          threshold: 0.2          
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          package: 30
    genai:
      enabled: false
    review:
      alerts:
        labels:
          - package
          - person
          - cat
          - dog
        required_zones: carport_post
      detections:
        required_zones: carport_post
    motion:
      threshold: 15
      contour_area: 10
      improve_contrast: true
    zones:
      carport_post:
        coordinates: 
          0.074,0.123,0.09,0.464,0.185,0.446,0.353,0.996,0.998,0.999,0.999,0.259,0.461,0.009
        loitering_time: 0
        inertia: 3


detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://xxxx

version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### Relevant Frigate log output

```shell
not important i guess
```

### Relevant go2rtc log output

```shell
not important i guess
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
    frigate:
      container_name: frigate
      image: ghcr.io/blakeblackshear/frigate:stable
      restart: always
      shm_size: "512mb"
      privileged: true
      devices:
        - /dev/bus/usb/002:/dev/bus/usb/002
        - /dev/dri/renderD128 # for intel hwaccel
      volumes:
        - /etc/localtime:/etc/localtime
        - /root/frigate:/config:rw
        - /root/frigate/clips:/media/frigate/clips:rw
        - /root/frigate/recordings:/media/frigate/recordings:rw
      ports:
        - 5000:5000
        - 1935:1935
      environment:
        #FRIGATE_RTSP_PASSWORD: "frigate" 
        - PLUS_API_KEY=xxxx
```

### Object Detector

Coral

**Comment by NickM-27** [comment]
If I had to guess Frigate detects the package but since it never moves it doesn't create an alert. 

One option would be to create a separate zone only for packages and make it a loitering zone. This will make an alert last as long as a package is there.

**Reply by AdmiralRaccoon** [reply]
Thanks and sorry for the late answer, as I was busy somewhere else.
Unfortunately, i expected a package today (which also arrived), but no notification from frigate. :-( 
Before it arrived, I followed your hint and created an extra-zone with loitering (I guess), but still no alert, although the package is detected in the debug view again.
I just wonder why there is no motion detection, that would create the alert, after the package is being pushed into the zone?


Is something missing within the edited config?

```
  cam_carport:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://*********@192.168.1.85:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - package
        - face
        - cat
      filters:
        package:
          min_area: 0
          min_ratio: 0
          max_ratio: 1000
          min_score: 0
          threshold: 0.2
        cat:
          mask: 0.875,0.733,0.445,0.354,0.46,0.018,0.723,0.076,0.977,0.247
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          package: 30
    genai:
      enabled: false
    review:
      alerts:
        required_zones: 
          - carport_general
          - carport_package
      detections:
        required_zones: 
          - carport_general
          - carport_package
    motion:
      threshold: 15
      contour_area: 10
      improve_contrast: true
    zones:
      carport_general:
        coordinates: 0.074,0.123,0.09,0.464,0.2,0.405,0.4,0.987,0.998,0.999,0.999,0.259,0.461,0.009
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - person
      carport_package:
        coordinates: 0.269,0.454,0.44,0.399,0.684,0.635,0.534,0.767,0.476,0.845
        loitering_time: 4
        objects: package
        inertia: 3
```

![image](https://github.com/user-attachments/assets/45e6457b-1d23-4071-acdb-4c32312171a8)

**Reply by hawkeye217** [reply]
By default, only `person` and `car` objects are alerts. You should specify `package` as a label for alerts.

**Reply by AdmiralRaccoon** [reply]
I thought that would be done here?

```
    objects:
      track:
        - person
        - package
        - face
        - cat
```

**Reply by hawkeye217** [reply, marked as answer]
No, this only defines what objects will be tracked by your camera, it does not specify how those tracked objects will be classified. You need to specify that you want `package` as an alert, eg:

```
    review:
      alerts:
        labels:
          - package
          - person
        required_zones: 
          - carport_general
          - carport_package
```
