### DISCUSSION TITLE
Updating Frigate from 0.15.0 to 0.15.1 with Portainer - nothing happens

### DISCUSSION THREAD

**Discussion by AdmiralRaccoon** [blakeblackshear/frigate#17801] [Ask A Question] [answered]
Hello,
Home Assistant still reminds me that there is an update from 0.15.0 to 0.15.1, but with my current docker-compose file, nothing happens, even if i change the "stable" to "0.15.1". Frigate itself still says "0.15.0" on the system page.

![image](https://github.com/user-attachments/assets/3e547d9a-612d-4e37-a305-a570c013870e)

Anything wrong with this docker rcompose? I used to trigger an "Update stack" within Portainer, and usually it worked that way:

```
services:
    frigate:
      container_name: frigate
      image: ghcr.io/blakeblackshear/frigate:stable
      restart: always
      shm_size: "512mb"
      privileged: true
      devices:
        - /dev/bus/usb/002:/dev/bus/usb/002
        - /dev/dri/renderD128 # for intel hwaccel
      volumes:
        - /etc/localtime:/etc/localtime
        - /root/frigate:/config:rw
        - /root/frigate/clips:/media/frigate/clips:rw
        - /root/frigate/recordings:/media/frigate/recordings:rw
      ports:
        - 5000:5000
        - 1935:1935
      environment:
        #FRIGATE_RTSP_PASSWORD: "frigate" 
        - PLUS_API_KEY=xxxxxx`
```

Thank you and have nice Easter!
