### DISCUSSION TITLE
Cannot install hardware acceleration successfully

### DISCUSSION THREAD

**Discussion by birdman7160** [blakeblackshear/frigate#17810] [Hardware Acceleration Support]
### Describe the problem you are having

I have successfully implemented Frigate without hardware acceleration. I am now trying to incrementally enable hardware acceleration. It appears that Frigate is not finding a LIBVA module. The error refers to "nlibva" which seems odd as when i installed libva i don't remember a directory or file named "nlibva".  I am not a Linux person so i  may be off base on this.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.38:5000/api/config/schema.json

mqtt:
  host: 192.168.0.140
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  enabled: true
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60
ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    front_porch:
      - rtsp://admin:Jmmreolink01@192.168.0.81:554/h264Preview_01_sub
      - ffmpeg:rtsp://admin:Jmmreolink01@192.168.0.81:554/h264Preview_01_sub#audio=pcm#audio=volume#


record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

snapshots:
  enabled: true
  retain:
    default: 10

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          roles:
            - detect
            - audio


    motion:
      mask:
        - 0.226,0,0.228,0.036,0.721,0.034,0.719,0.004,0.47,0.001
        - 0.151,0.632,0.478,0.63,0.486,0.377,0.314,0.333,0.156,0.388
    zones:
      front_porch_entry:
        coordinates: 0.131,0.652,0.474,0.688,0.478,0.768,0.308,0.774,0.139,0.754
        loitering_time: 10
        objects: person
    review:
      alerts:
        required_zones: front_porch_entry
      detections:
        required_zones: front_porch_entry
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:LAGGJW@192.168.0.57:554/Streaming/Channels/101/  #HIGH RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:LAGGJW@192.168.0.57:554/Streaming/Channels/102/  #LOW RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      enabled: true


version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
notifications:
  enabled: 'true'
  email: JOHNM8059@GMAIL.COM
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    cap_add:
      - CAP_PERFMON
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/millerdebian/frigate/config.yml:/config/config.yml
      - /home/millerdebian/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
        FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
frigate  | 2025-04-19 13:29:11.396106583  [2025-04-19 13:29:11] frigate.app                    INFO    : ********************************************************
frigate  | 2025-04-19 13:29:11.396509422  [2025-04-19 13:29:11] frigate.app                    INFO    : ********************************************************
frigate  | 2025-04-19 13:29:11.396871798  [2025-04-19 13:29:11] frigate.app                    INFO    : ***    Auth is enabled, but no users exist.          ***
frigate  | 2025-04-19 13:29:11.402303642  [2025-04-19 13:29:11] frigate.app                    INFO    : ***    Created a default user:                       ***
frigate  | 2025-04-19 13:29:11.407806522  [2025-04-19 13:29:11] frigate.app                    INFO    : ***    User: admin                                   ***
frigate  | 2025-04-19 13:29:11.418483577  [2025-04-19 13:29:11] frigate.app                    INFO    : ***    Password: d7df9ce694c11be3f0e46deb48680196   ***
frigate  | 2025-04-19 13:29:11.423937900  [2025-04-19 13:29:11] frigate.app                    INFO    : ********************************************************
frigate  | 2025-04-19 13:29:11.429459364  [2025-04-19 13:29:11] frigate.app                    INFO    : ********************************************************
frigate  | 2025-04-19 13:29:11.429669776  [2025-04-19 13:29:11] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate  | 2025-04-19 13:29:11.735322710  [2025-04-19 13:29:11] frigate.api.fastapi_app        INFO    : FastAPI started
frigate  | 2025-04-19 13:29:15.026745643  [2025-04-19 13:29:15] frigate.util.services          ERROR   : Unable to poll vainfo: b"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nlibva info: VA-API version 1.22.0\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so\nlibva info: Found init function __vaDriverInit_1_17\nlibva error: /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so init failed\nlibva info: va_openDriver() returns 2\nvaInitialize failed with error code 2 (resource allocation failed),exit\n"
frigate  | 2025-04-19 13:29:15.061187823  [2025-04-19 13:29:15] frigate.util.services          ERROR   : Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found
frigate  | 2025-04-19 13:29:15.061194116
frigate  | 2025-04-19 13:29:15.962409234  [2025-04-19 13:29:15] frigate.video                  ERROR   : front_porch: Unable to read frames from ffmpeg process.
frigate  | 2025-04-19 13:29:15.963197516  [2025-04-19 13:29:15] frigate.video                  ERROR   : front_porch: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-04-19 13:29:16.577253260  [2025-04-19 13:29:16] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
frigate  | 2025-04-19 13:29:16.577910863  [2025-04-19 13:29:16] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-04-19 13:29:30.830181272  [2025-04-19 13:29:30] watchdog.front_porch           ERROR   : Ffmpeg process crashed unexpectedly for front_porch.
frigate  | 2025-04-19 13:29:30.830231441  [2025-04-19 13:29:30] watchdog.front_porch           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-04-19 13:29:30.830234045  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : [AVHWDeviceContext @ 0x558f825ecdc0] libva: /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so init failed
frigate  | 2025-04-19 13:29:30.830300336  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : [AVHWDeviceContext @ 0x558f825ecdc0] Failed to initialise VAAPI connection: 2 (resource allocation failed).
frigate  | 2025-04-19 13:29:30.830447739  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : Device creation failed: -5.
frigate  | 2025-04-19 13:29:30.830450442  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : [vist#0:0/h264 @ 0x558f825ec180] [dec:h264 @ 0x558f825fc300] No device available for decoder: device type vaapi needed for codec h264.
frigate  | 2025-04-19 13:29:30.830487393  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : [vist#0:0/h264 @ 0x558f825ec180] [dec:h264 @ 0x558f825fc300] Hardware device setup failed for decoder: Input/output error
frigate  | 2025-04-19 13:29:30.830502915  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : [vost#0:0/rawvideo @ 0x558f825ecb00] Error initializing a simple filtergraph
frigate  | 2025-04-19 13:29:30.830588733  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : Error opening output file pipe:.
frigate  | 2025-04-19 13:29:30.830625884  [2025-04-19 13:29:30] ffmpeg.front_porch.detect      ERROR   : Error opening output files: Input/output error
frigate  | 2025-04-19 13:29:30.837078060  [2025-04-19 13:29:30] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
frigate  | 2025-04-19 13:29:30.843938298  [2025-04-19 13:29:30] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-04-19 13:29:30.843988167  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x5642ef8f0080] Missing PPS in sprop-parameter-sets, ignoring
frigate  | 2025-04-19 13:29:30.844107230  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : [AVHWDeviceContext @ 0x5642ef9aa3c0] libva: /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so init failed
frigate  | 2025-04-19 13:29:30.844126958  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : [AVHWDeviceContext @ 0x5642ef9aa3c0] Failed to initialise VAAPI connection: 2 (resource allocation failed).
frigate  | 2025-04-19 13:29:30.844253832  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : Device creation failed: -5.
frigate  | 2025-04-19 13:29:30.844293286  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : [vist#0:0/h264 @ 0x5642ef930b40] [dec:h264 @ 0x5642ef92f780] No device available for decoder: device type vaapi needed for codec h264.
frigate  | 2025-04-19 13:29:30.844372195  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : [vist#0:0/h264 @ 0x5642ef930b40] [dec:h264 @ 0x5642ef92f780] Hardware device setup failed for decoder: Input/output error
frigate  | 2025-04-19 13:29:30.844418058  [2025-04-19 13:29:30] ffmpeg.garage.detect           ERROR   : [vost#0:0/rawvideo @ 0x5642ef930280] Error initializing a simple filtergraph
```

### Relevant go2rtc log output

```shell
2025-04-19 13:42:26.474007155  [INFO] Preparing new go2rtc config...
2025-04-19 13:42:27.417254697  [INFO] Starting go2rtc...
2025-04-19 13:42:27.540265583  13:42:27.540 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-04-19 13:42:27.540269477  13:42:27.540 INF config path=/dev/shm/go2rtc.yaml
2025-04-19 13:42:27.541292548  13:42:27.541 INF [api] listen addr=:1984
2025-04-19 13:42:27.541352059  13:42:27.541 INF [rtsp] listen addr=:8554
2025-04-19 13:42:27.541574127  13:42:27.541 INF [webrtc] listen addr=:8555/tcp
2025-04-19 13:42:36.488874899  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
millerdebian@Office-PC:~/frigate$ ffprobe https://localhost:5000
ffprobe version 5.1.6-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[tls @ 0x5623732453c0] An unexpected TLS packet was received.
https://localhost:5000: Input/output error
```

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Doorbell POE camera, Hikvision DS-HDI doorbell camera

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/fc803bbb-ed30-401f-9d6b-b64e3df79e5b)
 
This image was created after I commented out the config and docker compose hardware acceleration lines so that the frigate system would start up.

### Any other information that may be helpful

I am running this on a Dell Optiplex 7090 with iGPU using Debian12 Linux. I installed LIBVA as well as OpenCL.
