### DISCUSSION TITLE
[Detector Support]: Hailo8L not working on latest commit

### DISCUSSION THREAD

**Discussion by CorwinDev** [blakeblackshear/frigate#17811] [Detector Support] [answered]
### Describe the problem you are having

No frames recieved error in stream

### Version

0.16.0-80a13e4

### Frigate config file

```yaml
detectors:
  hailo8l:
    type: hailo8l
    device: PCIe
    model_path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:80a13e4
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - /etc/localtime:/etc/localtime
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    shm_size: 256MB
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555"
      - "1984:1984"
      - "5000:5000"
    devices:
      - /dev/hailo0
```

### Relevant Frigate log output

```shell
frigate  | 2025-04-19 21:39:51.798868747  Traceback (most recent call last):
frigate  | 2025-04-19 21:39:51.798870136    File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
frigate  | 2025-04-19 21:39:51.798870914      self.run()
frigate  | 2025-04-19 21:39:51.798871951    File "/usr/lib/python3.11/threading.py", line 975, in run
frigate  | 2025-04-19 21:39:51.798872858      self._target(*self._args, **self._kwargs)
frigate  | 2025-04-19 21:39:51.798873969    File "/opt/frigate/frigate/detectors/plugins/hailo8l.py", line 205, in run
frigate  | 2025-04-19 21:39:51.798874710      job.wait(100)
frigate  | 2025-04-19 21:39:51.798875377      ^^^
frigate  | 2025-04-19 21:39:51.798876618  UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

-
