### DISCUSSION TITLE
[Bug]: Incorrect display of alerts and detections in the calendar

### DISCUSSION THREAD

**Discussion by ArtemVladimirov** [blakeblackshear/frigate#17826] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

The calendar on the review page highlights only the last 30 days in red, creating the impression that older records are unavailable, which isn’t true.
For example, my alert retention is set to 45 days. Today is April 21, yet the calendar shows entries only up to March 22. However, if I select March 17 in the calendar, those entries are still available for viewing.

### Steps to reproduce

1. Set the retention period for alerts and detections to more than 30 days.
2. Wait until records older than 30 days exist.
3. Navigate to Review.
4. Open the calendar.

### Version

v0.15.1

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 45
  detections:
    retain:
      days: 35
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    shm_size: "500mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - "/mnt/camera/frigate/storage:/media/frigate"
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "32200:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
no logs
```

### Relevant go2rtc log output

```shell
no logs
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/14b033b5-5631-42bb-9097-9a7bf62f2536)
