### DISCUSSION TITLE
[Bug]: Container labelled "frigate:0.15.1" reporting version "0.15.0-6cb5cfb"

### DISCUSSION THREAD

**Discussion by gsadlier** [blakeblackshear/frigate#17823] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Using the official `ghcr.io/blakeblackshear/frigate:0.15.1` container image, frigate is emitting a 'stats' payload container the version string `0.15.0-6cb5cfb` rather than something 0.15.1 related.  It is also saying that there's a newer version available -- `0.15.1`, which is what it should be running.

System page reports:  0.15.0-6cb5cfb

### Steps to reproduce

```
$ docker ps | grep frigate
9b19ddac34b2   ghcr.io/blakeblackshear/frigate:0.15.1   "/bin/bash /frigate-…"   2 days ago     Up 45 hours (healthy)  [...elided...]
$ mosquitto_sub -h mqtt -t frigate/stats -C 1 | jq ".service.version"
"0.15.0-6cb5cfb"
$ mosquitto_sub -h mqtt -t frigate/stats -C 1 | jq ".service.latest_version"
"0.15.1"
```

### Version

0.15.0-6cb5cfb or 0.15.1 depending on your perspective

### In which browser(s) are you experiencing the issue with?

n/a

### Frigate config file

```yaml
n/a
```

### docker-compose file or Docker CLI command

```yaml
name: frigate
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    privileged: true
    shm_size: "512mb"  # REVISIT
    pull_policy: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config:/config
      - /home/frigate/data:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - ./frigate-start.sh:/frigate-start.sh
    entrypoint:  ["/bin/bash", "/frigate-start.sh"]
    environment:
      - TZ=Pacific/Auckland
      - FRIGATE_RTSP_PASSWORD=[...elided...]
    attach: false
    ports:
      - 0.0.0.0:1935:1935/tcp
      - 0.0.0.0:5001:5000/tcp # REMAP!
      - 0.0.0.0:8554:8554/tcp
      - 0.0.0.0:8554:8554/udp
      - 0.0.0.0:8555:8555/udp
      - 0.0.0.0:8555:8555/tcp
    devices:
      - /dev/bus/usb:/dev/bus/usb
    restart: always
    container_name: frigate
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "{{.Name}}"
        cache-disabled: "false"
        cache-max-size: "10m"
        cache-max-file: 5
        cache-compress: "false"
```

### Relevant Frigate log output

```shell
$ mosquitto_sub -h mqtt -t frigate/stats -C 1 | jq ".service.version"
"0.15.0-6cb5cfb"
$ mosquitto_sub -h mqtt -t frigate/stats -C 1 | jq ".service.latest_version"
"0.15.1"
```
```


### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c3a82733-9a00-4da7-b85a-1904d7d23583)
