### DISCUSSION TITLE
[Config Support]: Cant get Reolink RLC-811A working with Frigate

### DISCUSSION THREAD

**Discussion by chitchco** [blakeblackshear/frigate#17838] [Config Support] [answered]
I cant seem to get frigate to work for RLC-811A; unfortunately there are multiple threads all of which are confusing. Some say lower resolution from 4K to 2K to enable H.264 get it working; others to contrary. I have tried a couple of options from multiple posts but no wins.  What is the recommended approach. I am not looking for fancy; just so it works. If lower resolution is the solution; so bet it, but is there are recommended config for this.

I am currently using blue iris but planning to move to frigate as I appreciate its community spirit and interoperability. I am also looking for integration with home assistant but wanted to start small. I have a mixture of camera's including the RLC-811A which has caused me some pause in this journey.

Currently running frigate of dedicated hardwware with debian o/s running dockge for docker manager. The processor is i7-6700T with 32GB ram with PCI Coral TPU. The coral drivers are loaded and working from my testing. I have  ssingle NIC trunk port  connected to managed switch running VLAN to isolate camera traffic from the reset of my network.

PS. Audio is optional/not required. 
PS. Although I can login; the GUI is not working so perhaps there are other issues besides the camera.

### Version

15-1

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  log:
    format: text
    #exec: trace
  streams:
    backdoor:
      - rtsp://admin:secret@192.168.20.80:554/h265Preview_01_main
      #- ffmpeg:backdoor#audio=opus
    backdoor_sub:
      - rtsp://admin:secret@192.168.1.20.80:554/h264Preview_01_sub
      #- ffmpeg:backdoor_sub#audio=opus

cameras:
  BackDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backdoor?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

version: 0.15-1
```

### Relevant Frigate log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2025-04-22 02:07:28.096377828  [INFO] Preparing new go2rtc config...
frigate  | 2025-04-22 02:07:28.097104869  [INFO] Preparing Frigate...
frigate  | 2025-04-22 02:07:28.097678479  [INFO] Starting NGINX...
frigate  | 2025-04-22 02:07:28.166190951  [INFO] Starting Frigate...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2025-04-22 02:07:28.193825415  [INFO] Starting certsync...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2025-04-22 02:07:28.308014188  127.0.0.1 - - [22/Apr/2025:02:07:28 +1000] "" 400 0 "-" "-" "-"
frigate  | 2025-04-22 02:07:28.528990675  [INFO] Starting go2rtc...
frigate  | 2025-04-22 02:07:28.632986106  02:07:28.632 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigate  | 2025-04-22 02:07:28.632990218  02:07:28.632 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2025-04-22 02:07:28.633329769  02:07:28.633 INF [api] listen addr=:1984
frigate  | 2025-04-22 02:07:28.633375486  02:07:28.633 INF [rtsp] listen addr=:8554
frigate  | 2025-04-22 02:07:28.633537744  02:07:28.633 INF [webrtc] listen addr=:8555/tcp
frigate  | 2025-04-22 02:07:30.508547541  [2025-04-22 02:07:30] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2025-04-22 02:07:30.530422016  [2025-04-22 02:07:30] frigate.util.config            INFO    : frigate config does not need migration...
frigate  | 2025-04-22 02:07:30.541610459  02:07:30.541 WRN [rtsp] error="streams: dial tcp: lookup 192.168.1.20.80: no such host" stream=backdoor_sub
frigate  | 2025-04-22 02:07:30.556689542  [2025-04-22 02:07:30] frigate.app                    INFO    : Starting Frigate (0.15.0-6cb5cfb)
frigate  | 2025-04-22 02:07:30.562998592  [2025-04-22 02:07:30] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2025-04-22 02:07:30.563383646  [2025-04-22 02:07:30] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2025-04-22 02:07:30.573430419  [2025-04-22 02:07:30] frigate.app                    INFO    : Recording process started: 357
frigate  | 2025-04-22 02:07:30.573883152  [2025-04-22 02:07:30] frigate.app                    INFO    : Review process started: 359
frigate  | 2025-04-22 02:07:30.577629231  [2025-04-22 02:07:30] frigate.app                    INFO    : go2rtc process pid: 96
frigate  | 2025-04-22 02:07:30.588396132  [2025-04-22 02:07:30] detector.coral                 INFO    : Starting detection process: 373
frigate  | 2025-04-22 02:07:30.597605301  [2025-04-22 02:07:30] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
frigate  | 2025-04-22 02:07:30.597797340  [2025-04-22 02:07:30] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
frigate  | 2025-04-22 02:07:30.597911028  [2025-04-22 02:07:30] frigate.app                    INFO    : Output process started: 401
frigate  | 2025-04-22 02:07:30.610940853  [2025-04-22 02:07:30] frigate.app                    INFO    : Camera processor started for BackDoor: 416
frigate  | 2025-04-22 02:07:30.623730116  [2025-04-22 02:07:30] frigate.app                    INFO    : Capture process started for BackDoor: 426
frigate  | 2025-04-22 02:07:30.644322804  02:07:30.644 WRN [rtsp] error="streams: dial tcp: lookup 192.168.1.20.80: no such host" stream=backdoor_sub
frigate  | 2025-04-22 02:07:30.647068677  [2025-04-22 02:07:30] frigate.video                  ERROR   : BackDoor: Unable to read frames from ffmpeg process.
frigate  | 2025-04-22 02:07:30.647203834  [2025-04-22 02:07:30] frigate.video                  ERROR   : BackDoor: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-04-22 02:07:30.743634863  [2025-04-22 02:07:30] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate  | 2025-04-22 02:07:30.870840713  [2025-04-22 02:07:30] frigate.api.fastapi_app        INFO    : FastAPI started
frigate  | 2025-04-22 02:07:38.098009598  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-04-22 02:07:50.660209083  [2025-04-22 02:07:50] watchdog.BackDoor              ERROR   : Ffmpeg process crashed unexpectedly for BackDoor.
frigate  | 2025-04-22 02:07:50.660485790  [2025-04-22 02:07:50] watchdog.BackDoor              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-04-22 02:07:50.660693874  [2025-04-22 02:07:50] ffmpeg.BackDoor.detect         ERROR   : [rtsp @ 0x557f80c96080] method DESCRIBE failed: 404 Not Found
frigate  | 2025-04-22 02:07:50.660981573  [2025-04-22 02:07:50] ffmpeg.BackDoor.detect         ERROR   : [in#0 @ 0x557f80c95d80] Error opening input: Server returned 404 Not Found
frigate  | 2025-04-22 02:07:50.661205014  [2025-04-22 02:07:50] ffmpeg.BackDoor.detect         ERROR   : Error opening input file rtsp://127.0.0.1:8554/backdoor_sub?video=copy.
frigate  | 2025-04-22 02:07:50.661469998  [2025-04-22 02:07:50] ffmpeg.BackDoor.detect         ERROR   : Error opening input files: Server returned 404 Not Found
frigate  | 2025-04-22 02:07:50.683523466  02:07:50.683 WRN [rtsp] error="streams: dial tcp: lookup 192.168.1.20.80: no such host" stream=backdoor_sub
frigate  | 2025-04-22 02:07:50.685180052  [2025-04-22 02:07:50] frigate.video                  ERROR   : BackDoor: Unable to read frames from ffmpeg process.
frigate  | 2025-04-22 02:07:50.685324904  [2025-04-22 02:07:50] frigate.video                  ERROR   : BackDoor: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-04-22 02:08:00.680315982  [2025-04-22 02:08:00] watchdog.BackDoor              ERROR   : Ffmpeg process crashed unexpectedly for BackDoor.
frigate  | 2025-04-22 02:08:00.680570528  [2025-04-22 02:08:00] watchdog.BackDoor              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-04-22 02:08:00.680800438  [2025-04-22 02:08:00] ffmpeg.BackDoor.detect         ERROR   : [rtsp @ 0x55eb91406080] method DESCRIBE failed: 404 Not Found
frigate  | 2025-04-22 02:08:00.681050142  [2025-04-22 02:08:00] ffmpeg.BackDoor.detect         ERROR   : [in#0 @ 0x55eb91405d80] Error opening input: Server returned 404 Not Found
frigate  | 2025-04-22 02:08:00.681341478  [2025-04-22 02:08:00] ffmpeg.BackDoor.detect         ERROR   : Error opening input file rtsp://127.0.0.1:8554/backdoor_sub?video=copy.
frigate  | 2025-04-22 02:08:00.681545917  [2025-04-22 02:08:00] ffmpeg.BackDoor.detect         ERROR   : Error opening input files: Server returned 404 Not Found
frigate  | 2025-04-22 02:08:00.701485446  02:08:00.701 WRN [rtsp] error="streams: dial tcp: lookup 192.168.1.20.80: no such host" stream=backdoor_sub
frigate  | 2025-04-22 02:08:00.703168518  [2025-04-22 02:08:00] frigate.video                  ERROR   : BackDoor: Unable to read frames from ffmpeg process.
frigate  | 2025-04-22 02:08:00.703343731  [2025-04-22 02:08:00] frigate.video                  ERROR   : BackDoor: ffmpeg process is not running. exiting capture thread...
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2025-04-22 02:08:02.862956412  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2025-04-22 02:08:02.866309273  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | s6-rc: info: service certsync successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service certsync-log: stopping
frigate  | s6-rc: info: service certsync-log successfully stopped
frigate  | 2025-04-22 02:08:02.994666383  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2025-04-22 02:08:03.138135800  [2025-04-22 02:08:03] frigate.app                    INFO    : Stopping...
frigate  | 2025-04-22 02:08:03.139928759  [2025-04-22 02:08:03] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate  | 2025-04-22 02:08:03.140190535  [2025-04-22 02:08:03] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate  | 2025-04-22 02:08:03.142137455  [2025-04-22 02:08:03] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate  | 2025-04-22 02:08:03.142640772  [2025-04-22 02:08:03] frigate.watchdog               INFO    : Exiting watchdog...
frigate  | 2025-04-22 02:08:03.142829158  [2025-04-22 02:08:03] frigate.stats.emitter          INFO    : Exiting stats emitter...
frigate  | 2025-04-22 02:08:03.143037623  [2025-04-22 02:08:03] frigate.storage                INFO    : Exiting storage maintainer...
frigate  | 2025-04-22 02:08:03.145473040  [2025-04-22 02:08:03] frigate.app                    INFO    : Waiting for capture process for BackDoor to stop
frigate  | 2025-04-22 02:08:03.147328970  [2025-04-22 02:08:03] watchdog.BackDoor              INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-04-22 02:08:03.147542051  [2025-04-22 02:08:03] watchdog.BackDoor              INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-04-22 02:08:03.147804972  [2025-04-22 02:08:03] watchdog.BackDoor              INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-04-22 02:08:03.148006197  [2025-04-22 02:08:03] watchdog.BackDoor              INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-04-22 02:08:03.379229717  [2025-04-22 02:08:03] frigate.app                    INFO    : Waiting for process for BackDoor to stop
frigate  | 2025-04-22 02:08:03.653083713  [2025-04-22 02:08:03] frigate.object_processing      INFO    : Exiting object processor...
frigate  | 2025-04-22 02:08:03.676468686  [2025-04-22 02:08:03] frigate.video                  INFO    : BackDoor: emptying frame queue
frigate  | 2025-04-22 02:08:03.676616789  [2025-04-22 02:08:03] frigate.video                  INFO    : BackDoor: exiting subprocess
frigate  | 2025-04-22 02:08:03.685903166  [2025-04-22 02:08:03] frigate.app                    INFO    : Closing frame queue for BackDoor
frigate  | 2025-04-22 02:08:03.769278508  [2025-04-22 02:08:03] frigate.events.maintainer      INFO    : Exiting event processor...
frigate  | 2025-04-22 02:08:04.187836987  [2025-04-22 02:08:04] root                           INFO    : Waiting for detection process to exit gracefully...
frigate  | 2025-04-22 02:08:04.644524594  [2025-04-22 02:08:04] detector.coral                 INFO    : Exited detection process...
frigate  | 2025-04-22 02:08:04.653632938  [2025-04-22 02:08:04] root                           INFO    : Detection process has exited...
frigate  | 2025-04-22 02:08:05.155272381  [2025-04-22 02:08:05] frigate.app                    INFO    : Detection queue closed
frigate  | 2025-04-22 02:08:05.656573744  [2025-04-22 02:08:05] frigate.app                    INFO    : Detected frames queue closed
frigate  | 2025-04-22 02:08:06.157868191  [2025-04-22 02:08:06] frigate.app                    INFO    : Timeline queue closed
frigate  | 2025-04-22 02:08:07.181243913  [2025-04-22 02:08:07] frigate.output.output          INFO    : exiting output process...
frigate  | 2025-04-22 02:08:10.764046674  [2025-04-22 02:08:10] frigate.review.maintainer      INFO    : Exiting review maintainer...
frigate  | 2025-04-22 02:08:11.147804781  [2025-04-22 02:08:11] frigate.comms.ws               INFO    : Exiting websocket client...
frigate  | 2025-04-22 02:08:11.623611570  [2025-04-22 02:08:11] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate  | 2025-04-22 02:08:11.655022341  [INFO] Service Frigate exited with code 0 (by signal 0)
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | 2025-04-22 02:08:11.658103448  exit with signal: terminated
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2025-04-22 02:08:11.662449521  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 143
```

### Relevant go2rtc log output

```shell
sorry logs not available; cant locate them using CLI
```

### Frigate stats

```json
sorry stats not available; cant located using CLI
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 512mb # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver 
      # instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/mydrive/frigate/config:/config
      - /mnt/mydrive/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: password
networks:
  dockge_default:
    external: true
```

### Object Detector

Coral
