### DISCUSSION TITLE
[Config Support]: HA + Frigate, cannot get audio/WebRTC to work

### DISCUSSION THREAD

**Discussion by Staene** [blakeblackshear/frigate#17840] [Config Support] [answered]
### Describe the problem you are having

Hi,

I have two Nest cams (I know): one doorbell, one floodlight. It doesn't matter whether I'm pulling the streams into Frigate directly or into HomeAssistant first (via go2rtc), I cannot get them into Frigate with audio. 

On live view, I'm topping out at jsmpeg—but in recordings, I'm getting full 1080p quality. What I don't understand is that the feed from HomeAssistant and from Nest directly both have crisp H.264 video and opus audio configured correctly. I'm able to hear sound and do two-way talk in HomeAssistant. The feed being provided to Frigate from HA is fully functional—but it's losing audio along the way.

Best I can tell, something is wrong in either my go2rtc config or my ffmpeg setup, but I cannot figure out what.

I've troubleshooted this for roughly 24h and just need new eyes on it.

Thanks!

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: <REDACTED>
  password: <REDACTED>

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  path: "5.0"
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    doorbell:
      - rtsp://10.1.0.197:8554/nest-doorbell
      - ffmpeg:doorbell#audio=opus
    driveway:
      - rtsp://10.1.0.197:8554/nest-driveway
      - ffmpeg:doorbell#audio=opus
    webrtc:
      candidates:
        - 10.1.0.35:8555
        - stun:8555

cameras:
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
            - record
      output_args: 
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    zones:
      The_Driveway:
        coordinates: 
          0.053,0.588,0,1,0.958,0.993,0.991,0.794,1,0.569,0.821,0.503,0.904,0.391,0.786,0.351
        loitering_time: 0
        inertia: 1
    review:
      alerts:
        required_zones: The_Driveway
        labels:
          - car
          - cat
          - dog
          - person
      detections:
        labels:
          - car
          - cat
          - dog
          - person

  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - record
      output_args: 
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    review:
      alerts:
        required_zones: Yard
        labels:
          - cat
          - dog
          - person
      detections:
        labels:
          - car
          - cat
          - dog
          - person

    zones:
      Yard:
        coordinates: 0.392,0.537,1,0.554,0.998,0.995,0.004,0.997,0.004,0.05,0.395,0.358
        loitering_time: 0
        inertia: 1
record:
  enabled: true
  retain:
    days: 3
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 30
      mode: motion

objects:
  track:
    - person
    - car
    - cat
    - dog

version: 0.15-1
notifications:
  enabled: 'true'
  email: <REDACTED>

genai:
  enabled: true
  provider: openai
  api_key: <REDACTED>
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"driveway":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":492,"capture_pid":496,"ffmpeg_pid":506,"audio_rms":0.0,"audio_dBFS":0.0},"doorbell":{"camera_fps":5.1,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":495,"capture_pid":515,"ffmpeg_pid":523,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":7.92,"detection_start":0.0,"pid":457}},"detection_fps":0.0,"gpu_usages":{"error-gpu":{"gpu":"","mem":""}},"cpu_usages":{"frigate.full_system":{"cpu":"1.9","mem":"23.4"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"44":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"86":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"1.9","cpu_average":"1","mem":"0.1","cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml"},"107":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"109":{"cpu":"1.1","cpu_average":"1","mem":"0.6","cmdline":"python3 -u -m frigate"},"124":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"173":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"174":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"175":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"176":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"179":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"353":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"441":{"cpu":"0.5","cpu_average":"0","mem":"0.3","cmdline":"frigate.recording_manager"},"443":{"cpu":"0.1","cpu_average":"0","mem":"0.3","cmdline":"frigate.review_segment_manager"},"457":{"cpu":"0.0","cpu_average":"2","mem":"0.3","cmdline":"frigate.detector.coral"},"478":{"cpu":"0.3","cpu_average":"0","mem":"0.3","cmdline":"frigate.output       "},"492":{"cpu":"0.7","cpu_average":"2","mem":"0.3","cmdline":"frigate.process:driveway"},"495":{"cpu":"0.7","cpu_average":"4","mem":"0.3","cmdline":"frigate.process:doorbell"},"496":{"cpu":"0.3","cpu_average":"0","mem":"0.3","cmdline":"frigate.capture:driveway"},"506":{"cpu":"1.5","cpu_average":"1","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"515":{"cpu":"1.1","cpu_average":"1","mem":"0.3","cmdline":"frigate.capture:doorbell"},"523":{"cpu":"3.7","cpu_average":"3","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1600:h=1200,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"561":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"568":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1600x1200 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"575":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/5.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"7735":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"},"7829":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"}},"service":{"uptime":1556,"version":"0.15.0-6cb5cfb","latest_version":"0.15.1","storage":{"/media/frigate/recordings":{"total":54902784.0,"used":23128311.4,"free":31774472.6,"mount_type":"nfs"},"/media/frigate/clips":{"total":54902784.0,"used":23128311.4,"free":31774472.6,"mount_type":"nfs"},"/tmp/cache":{"total":953.7,"used":13.8,"free":939.8,"mount_type":"tmpfs"},"/dev/shm":{"total":512.0,"used":155.7,"free":356.3,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1745259238},"processes":{"recording":{"pid":441},"review_segment":{"pid":443},"go2rtc":{"pid":98}}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate:/config
      - /mnt/media-nas/Cameras:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" #go2rtc webUI
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1459" alt="Screenshot 2025-04-21 at 1 15 51 PM" src="https://github.com/user-attachments/assets/44c867c2-740b-421b-b5ff-ae2b854a78e5" />
