### DISCUSSION TITLE
[HW Accel Support]: HEVC doesn't work on Jetson Orin Nano with jetpack 6 (645c84b-tensorrt-jp6 docker image)

### DISCUSSION THREAD

**Discussion by bogdanr** [blakeblackshear/frigate#17851] [Hardware Acceleration Support]
### Describe the problem you are having

I am using the Docker image built for JetPack 6. It mostly works OK except for HW decoding of H265. Without HW decoding the CPU usage on Jetson Orin Nano is ~50%.

### Version

645c84b-tensorrt-jp6

### Frigate config file

```yaml
cameras:
  cat-feeder:
    genai:
      enabled: false
    ffmpeg:
      #hwaccel_args: preset-jetson-hevc
      inputs:
        - path: rtsp://bla-bla:554
          roles:
            - detect
            - record
    objects:
      track:
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
        objects:
          cat: 14
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:645c84b-tensorrt-jp6
    privileged: true
    runtime: nvidia
    shm_size: "176mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/frigate:/media/frigate
      - /tmp/cache:/tmp/cache
    ports:
      - "5000:5000"
      - "8554:8554"
      - "1935:1935" # RTMP feeds
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0
```

### Relevant Frigate log output

```shell
frigate  | 2025-04-22 11:57:13.682709579  [2025-04-22 11:57:13] frigate.video                  ERROR   : cat-feeder: Unable to read frames from ffmpeg process.
frigate  | 2025-04-22 11:57:13.683246907  [2025-04-22 11:57:13] frigate.video                  ERROR   : cat-feeder: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-04-22 11:57:22.160602102  [2025-04-22 11:57:22] watchdog.cat-feeder            ERROR   : Ffmpeg process crashed unexpectedly for cat-feeder.
frigate  | 2025-04-22 11:57:22.160742554  [2025-04-22 11:57:22] watchdog.cat-feeder            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-04-22 11:57:22.160825244  [2025-04-22 11:57:22] ffmpeg.cat-feeder.detect       ERROR   : [hevc @ 0xaaaacd9b2f40] high_precision_offsets_enabled_flag not yet implemented
frigate  | 2025-04-22 11:57:22.160919423  [2025-04-22 11:57:22] ffmpeg.cat-feeder.detect       ERROR   :     Last message repeated 1 times
frigate  | 2025-04-22 11:57:22.161014786  [2025-04-22 11:57:22] ffmpeg.cat-feeder.detect       ERROR   : [NULL @ 0xaaaacd9ef250] Unable to find a suitable output format for 'preset-jetson-hevc'
frigate  | 2025-04-22 11:57:22.161116421  [2025-04-22 11:57:22] ffmpeg.cat-feeder.detect       ERROR   : preset-jetson-hevc: Invalid argument
frigate  | 2025-04-22 11:57:32.374935271  [2025-04-22 11:57:32] frigate.video                  ERROR   : cat-feeder: Unable to read frames from ffmpeg process.
frigate  | 2025-04-22 11:57:32.375363284  [2025-04-22 11:57:32] frigate.video                  ERROR   : cat-feeder: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-04-22 11:57:42.166255550  [2025-04-22 11:57:42] watchdog.cat-feeder            ERROR   : Ffmpeg process crashed unexpectedly for cat-feeder.
frigate  | 2025-04-22 11:57:42.166360545  [2025-04-22 11:57:42] watchdog.cat-feeder            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-04-22 11:57:42.166460964  [2025-04-22 11:57:42] ffmpeg.cat-feeder.detect       ERROR   : [hevc @ 0xaaab173c4f40] high_precision_offsets_enabled_flag not yet implemented
frigate  | 2025-04-22 11:57:42.166667051  [2025-04-22 11:57:42] ffmpeg.cat-feeder.detect       ERROR   :     Last message repeated 1 times
frigate  | 2025-04-22 11:57:42.166683531  [2025-04-22 11:57:42] ffmpeg.cat-feeder.detect       ERROR   : [NULL @ 0xaaab174048e0] Unable to find a suitable output format for 'preset-jetson-hevc'
frigate  | 2025-04-22 11:57:42.166978452  [2025-04-22 11:57:42] ffmpeg.cat-feeder.detect       ERROR   : preset-jetson-hevc: Invalid argument
```

### Relevant go2rtc log output

```shell
irelevant
```

### FFprobe output from your camera

```shell
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --cc='ccache gcc' --cxx='ccache g++' --enable-shared --disable-static --prefix=/rootfs/usr/lib/ffmpeg/jetson --enable-gpl --enable-libx264 --enable-libx265 --enable-nvmpi --enable-ffnvcodec --enable-cuda-llvm --disable-cuvid --disable-nvenc --disable-nvdec
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[hevc @ 0xaaaae83d3cb0] high_precision_offsets_enabled_flag not yet implemented
    Last message repeated 1 times
Input #0, rtsp, from 'rtsp://bla-bla:554':
  Metadata:
    title           : Session 
  Duration: N/A, start: -0.026556, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 1920x1080, 25 fps, 24.92 tbr, 90k tbn
  Stream #0:1: Audio: adpcm_g726le, 8000 Hz, mono, s16, 16 kb/s
[hevc @ 0xaaaae84315b0] high_precision_offsets_enabled_flag not yet implemented
```

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

It's a cat feader that exposes the camera through rtsp

### Screenshots of the Frigate UI's System metrics pages

irelevant
