### DISCUSSION TITLE
[Support]: libcublasLt.so.12.1.0.26: no space left on device

### DISCUSSION THREAD

**Discussion by repomanz** [blakeblackshear/frigate#17857] [General Support] [answered]
### Describe the problem you are having

I'm trying to upgrade to the latest version of frigate.  I understand shim has been re-written and have increased my shim value from 1gb to 16gb (--shm-size=16gb).   I still get this error when trying to upgrade below:

Error: failed to register layer: write /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12.1.0.26: no space left on device.

0.14 frigate it working perfectly.

### Version

0.15

### What browser(s) are you using?

Mozilla 137.0.2 

### Frigate config file

```yaml
mqtt:
  host: 10.180.50.20
  user: frigate_mqtt
  password: 2xdda2662767gahjaj432767@#$

go2rtc:
  streams:
    garage: # <- for RTSP streams
#     - ffmpeg:http://10.180.50.70/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=jjames&password=flo1344ski2021#video=copy#audio=copy#audio=opus
      - rtsp://x:fx@10.180.50.70:554/h264Preview_01_sub
    backdoor: # <- for RTSP streams
      - rtsp://x:fxxx0xx@10.180.50.71:554/h264Preview_01_sub
    backyard: # <- for RTSP streams
      - ffmpeg:http://10.180.50.72/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxxAPE#video=copy#audio=copy#audio=opus
    insidegarage: # <- for RTSP streams
      - ffmpeg:http://10.180.50.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=#video=copy#audio=copy#audio=opus
    owlcam_1: # <- for RTSP streams
      - ffmpeg:http://10.180.50.73:554/user=admin&password=h&channel=1&stream=1.sdp?real_stream#video=copy#audio=copy#audio=opus
    #owlcam_2: # <- for RTSP streams
    #  - ffmpeg:http://10.180.50.76:554/user=admin&password=h2l&channel=1&stream=1.sdp?real_stream#video=copy#audio=copy#audio=opus
    main_room: # <- for RTSP streams
      - ffmpeg:http://10.180.50.74/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=V5!gTsRTg%J#video=copy#audio=copy#audio=opus

birdseye:
  enabled: true
  restream: true
  mode: continuous
  width: 1280
  height: 720

cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:21@10.180.50.70:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://adx:xx21@10.180.50.70:554/h264Preview_01_main
          roles:
            - record
    birdseye:
      order: 1
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
        - car
      filters:
        person:
          mask: 
            0.721,0.003,0.712,0.076,0.676,0.121,0.636,0.194,0.655,0.226,0.687,0.254,0.72,0.249,0.743,0.206,0.747,0.176,0.744,0.128,0.746,0.076,0.754,0.02
    motion:
      threshold: 60
      contour_area: 10
      lightning_threshold: 1.0
      frame_height: 150
      mask: 0,0,0,0.281,0.233,0.169,0.506,0.058,0.706,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      required_zones:
        - front_driveway
        - front_yard
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 3
    zones:
      front_driveway:
        coordinates: 0.569,0.325,0.948,0.549,0.862,0.835,0.791,1,0,1,0,0.367,0.295,0.188
        objects: person
        inertia: 3
        loitering_time: 0
      front_yard:
        coordinates: 
          0.5,0.089,0.289,0.186,0.573,0.326,0.937,0.541,0.991,0.346,1,0.231,0.938,0.16,0.684,0.023
        objects: person
        inertia: 3
        loitering_time: 0
  backdoor:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:x1@10.180.50.71:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:x21@10.180.50.71:554/h264Preview_01_main
          roles:
            - record
    birdseye:
      order: 2
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      threshold: 60
      contour_area: 10
      lightning_threshold: 1.0
      frame_height: 150
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      required_zones:
        - zone_back_door
        - zone_back_deck
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 3
    zones:
      zone_back_door:
        coordinates: 0,67,140,0,259,0,273,206,436,395,396,438,389,480,0,480
      zone_back_deck:
        coordinates: 
          350,0,474,79,472,197,558,271,544,303,514,323,480,347,460,382,422,389,265,195,255,0
  backyard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:fxx021@10.180.50.72:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:flo13xx1E@10.180.50.72:554/h264Preview_01_main
          roles:
            - record
    birdseye:
      order: 3
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask: 0.8,0.227,0.797,0.275,0.843,0.29,0.844,0.237
    motion:
      threshold: 60
      contour_area: 10
      lightning_threshold: 1.0
      frame_height: 150
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
      required_zones:
        - zone_back_yard_near
        - zone_back_yard_far
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 3
    zones:
      zone_back_yard_near:
        coordinates: 640,480,640,171,402,201,78,246,115,380,171,480
        objects:
          - person
      zone_back_yard_far:
        coordinates: 
          0.824,0.384,0.619,0.047,0.345,0.068,0.126,0.044,0.065,0.061,0.088,0.288,0.121,0.51
        objects: person
        inertia: 3
        loitering_time: 0
  insidegarage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://adsn:nxE=5h8EC&6df]@10.180.50.75:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://asmin:nwxRrE=5h8EC&6df]@10.180.50.75:554/h264Preview_01_main
          roles:
            - record
    birdseye:
      order: 4
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      threshold: 60
      contour_area: 10
      lightning_threshold: 1.0
      frame_height: 150
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 3
    zones:
      room2:
        coordinates: 0,0,640,0,640,480,0,480
  owlcam_1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 500M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: 
            rtsp://10.180.50.73:554/user=admin&password=h2xTFCl&channel=1&stream=1.sdp?real_stream
          roles:
            - detect
        - path: 
            rtsp://10.180.50.73:554/user=admin&password=h29xCl&channel=1&stream=0.sdp?real_stream
          roles:
            - record
    birdseye:
      order: 5
    detect:
      width: 640
      height: 480
      fps: 25
    objects:
      track:
        - bird
    motion:
      threshold: 40
      contour_area: 20
      lightning_threshold: 1.0
      frame_height: 150
      improve_contrast: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
    zones:
      zone_owlcam1:
        coordinates: 39,0,602,0,598,480,33,480
  owlcam_2:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 500M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: 
            rtsp://10.180.50.76:554/user=admin&password=h2xTFCl&channel=1&stream=1.sdp?real_stream
          roles:
            - detect
        - path: 
            rtsp://10.180.50.76:554/user=admin&password=h29xaOTFCl&channel=1&stream=0.sdp?real_stream
          roles:
            - record
    birdseye:
      order: 6
    detect:
      width: 640
      height: 480
      fps: 25
    objects:
      track:
        - bird
    motion:
      threshold: 60
      contour_area: 10
      lightning_threshold: 1.0
      frame_height: 150
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
    zones:
      zone_owlcam2:
        coordinates: 39,0,602,0,598,480,33,480
  main_room:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -probesize
        - 1000M
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:V2xgTsRTg%J@10.180.50.74:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:Vx!gTsRTg%J@10.180.50.74:554/h264Preview_01_main
          roles:
            - record
    birdseye:
      order: 4
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      threshold: 60
      contour_area: 10
      lightning_threshold: 1.0
      frame_height: 150
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 7
        pre_capture: 8
        post_capture: 3
      detections:
        retain:
          days: 3
    zones:
      room1:
        coordinates: 0,0,640,0,640,480,0,480
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

version: 0.15-1
camera_groups:
  Outside:
    order: 1
    icon: LuAlertTriangle
    cameras:
      - backdoor
      - backyard
      - garage
  Inside:
    order: 2
    icon: LuActivity
    cameras: insidegarage
  Owl_houses:
    order: 3
    icon: LuAnnoyed
    cameras:
      - owlcam_1
      - owlcam_2
semantic_search:
  enabled: true
  reindex: true
  model_size: large
```

### Relevant Frigate log output

```shell
Error: failed to register layer: write /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12.1.0.26: no space left on device.
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
other:  unraid frigate install / template
```

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

multiple brands

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/eddcbaa8-79e3-4521-a838-efc758a9fb6b)

### Any other information that may be helpful

Get the error when trying to upgrade to .15 in unraid.
