### DISCUSSION TITLE
[Camera Support]: Sricam SP008 ONVIF PTZ

### DISCUSSION THREAD

**Discussion by Luarion** [blakeblackshear/frigate#17863] [Camera Support]
### Describe the problem you are having

Hey folks, I basically get the following errors in the Frigate's log while attempting to set up my "ONVIF" camera and I couldn't figure it out.
The PTZ function works "perfectly" with Onvif Device Manager, also works with ZoneMinder

### Version

0.15-1

### What browser(s) are you using?

Google Chrome

### Frigate config file

```yaml
# yaml-language-server: $schema=../schema.json
mqtt:
  enabled: false

go2rtc:
  streams:
    sricam:
      - rtsp://10.1.3.254:554/onvif1
      - rtsp://10.1.3.254:554/onvif2
      - onvif://admin:admin@10.1.3.254:5000?subtype=IPCProfilesToken0
      - onvif://admin:admin@10.1.3.254:5000?subtype=IPCProfilesToken1

cameras:
  test:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sricam?substream=3
          roles:
            - detect
            - record
    audio:
      enabled: false
    onvif:
      host: 10.1.3.254
      port: 5000
      user: ""
      password: ""
      tls_insecure: true
      ignore_time_mismatch: true
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: false
      retain:
        days: 7
    zones:
      calle:
        coordinates: 
          0.682,0,0.678,1,0,1,0.468,0.178,0.473,0.255,0.533,0.173,0.54,0.088,0.586,0.037,0.588,0
        loitering_time: 0
    review:
      alerts:
        required_zones: calle
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-04-23 00:43:51.825390827  [2025-04-23 00:43:51] frigate.ptz.onvif              ERROR   : No appropriate Onvif profiles found for camera: test.
2025-04-23 00:50:51.084627790  [2025-04-23 00:50:51] frigate.ptz.onvif              ERROR   : Onvif connection to test failed: Unknown error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

### Relevant go2rtc log output

```shell
2025-04-23 00:50:39.327671050  [INFO] Preparing new go2rtc config...
2025-04-23 00:50:42.257118317  [INFO] Starting go2rtc...
2025-04-23 00:50:42.785470790  00:50:42.785 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-04-23 00:50:42.785478191  00:50:42.785 INF config path=/dev/shm/go2rtc.yaml
2025-04-23 00:50:42.795704080  00:50:42.788 INF [api] listen addr=:1984
2025-04-23 00:50:42.795710580  00:50:42.788 INF [rtsp] listen addr=:8554
2025-04-23 00:50:42.813905084  00:50:42.813 INF [webrtc] listen addr=:8555/tcp
2025-04-23 00:50:49.336779220  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
uwu
```

### Operating system

Windows

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Sricam SP008

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/2a0cdd76-3546-4beb-8a6f-c7358d27a501)

**Comment by hawkeye217** [comment]
Frigate closely mimics how Home Assistant works with ONVIF cameras. Are you a Home Assistant user?

It'd be helpful to see debug logs.

```
logger:
  default: info
  logs:
    frigate.ptz.onvif: debug
```
