### DISCUSSION TITLE
Camera on low-bandwidth connection

### DISCUSSION THREAD

**Discussion by lpaolini** [blakeblackshear/frigate#17862] [Ask A Question]
One of my cameras is reachable via VPN on a low-bandwidth 4G connection.
Given that a high-framerate live feed from that camera is not feasible, would it be possible to acquire jpeg snapshots (like one every few seconds) to be shown in the live view along with other cameras providing live feed?

**Comment by hawkeye217** [comment]
This is not possible in the current version (0.15). In the next version of Frigate (0.16), you can choose a lower resolution substream (or transcode something and provide it with go2rtc, for example) and use that for your live view, which can be selected separately on each device.

**Comment by lpaolini** [comment]
Could you please provide an example on how to do that? 

I'm on dev version, and I'm using go2rtc on all of my cams.
Ideally I would like to create a very low framerate stream out of jpg snapshots, say 1fps.

```
go2rtc:
  streams:
    ...
    cam_ext:
      - rtsp://<main_url>
      - ffmpeg:cam_ext#audio=aac
    cam_ext_sub:
      - rtsp://<sub_url>
      - ffmpeg:cam_ext_sub#audio=aac
```
