### DISCUSSION TITLE
Snapshot quality

### DISCUSSION THREAD

**Discussion by primzele** [blakeblackshear/frigate#17887] [Ask A Question]
Hi,

I have a question regarding snapshot quality, i probably don't understand how this works, but when we say "snapshot" that means the screenshot you can browse through in review, right? If you click on camera and then history, there's a vertical time bar on the right side:

<img width="590" alt="image" src="https://github.com/user-attachments/assets/4c94f5dd-222e-4a8e-ba21-11c5b6cb53af" />

This is it right ?

Why is the quality of this so bad? Doesn't it take it from a high res stream ? 

I read this [issue here](https://github.com/blakeblackshear/frigate/issues/2199) but i am not sure I understand ... can't snapshot be taken periodically, say every 10s, why the need for detection?

I also get longer periods of "No preview found" and i could not find anything in the logs, debug enabled.

Could this be due to hardware issues if it's doing detection ?

Thank you for answers and this beautiful software

running in docker on latest stable image

my config:

```
logger:
  default: debug

tls:
  enabled: false

mqtt:
  host: 10.0.23.11
  port: 15883

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - dog
    - cat
    - bird
    - horse
    - sheep
    - cow
    - bear

birdseye:
  enabled: true
  # width: 800
  width: 1280

  #height: 600
  quality: 10
  mode: continuous

cameras:
  front:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://10.0.23.11:19554/front
          roles:
            - record
        #- path: rtsp://10.0.23.11:19554/front_sub
        - path: rtsp://10.0.23.11:19554/front
          roles:
            - detect

    detect:
      #width: 1280
      #height: 720
      #fps: 5
      width: 1920
      height: 1080
      fps: 2

    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 1
    motion:
      threshold: 25
      contour_area: 15
      improve_contrast: true
      mask:
        - 0,0,0.012,0.15,0.186,0.054,0.414,0,0.5,0.027,0.501,0
        - 0.767,0.044,0.767,0.101,0.994,0.103,0.996,0.043
        - 0.764,0.179,0.714,0.265,0.882,0.361,0.892,0.26
        - 0.573,0.062,0.545,0.125,0.613,0.177,0.668,0.146,0.676,0.116
    snapshots:
      enabled: true
      retain:
        default: 30

    zones: {}
    review: {}
    objects:
      mask: 0,0.151,0.189,0.061,0.418,0.008,1,0.184,1,1,0,1
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p

go2rtc:
  streams:
    front: 
      ffmpeg:rtsp://admin:password@10.0.23.50:554/user=admin_password=adminpassword_channel=1_stream=0&protocol=unicast.sdp?real_stream#video=h264
    front_sub: 
      ffmpeg:rtsp://admin:password@10.0.23.50:554/user=admin_password=adminpassword_channel=1_stream=1&protocol=unicast.sdp?real_stream#video=h264
  webrtc:
    candidates:
      - 10.0.23.11:19554
version: 0.15-1

```
