### DISCUSSION TITLE
[Detector Support]: A+E M.2 Coral support with PCI-E adapter in Dell Optiplex

### DISCUSSION THREAD

**Discussion by chitchco** [blakeblackshear/frigate#17897] [Detector Support] [answered]
### Describe the problem you are having

I waiting of dual Coral PCI card and associated PCI dual card to arrive; but as interim installed a single Coral A+E M.2 module in TP-LINK AC1200 wifi PCI-E adapter in my production machine Del Optiplex. The PCI-E adapter is [https://www.tp-link.com/au/home-networking/pci-adapter/archer-t5e/  ](https://www.tp-link.com/au/home-networking/pci-adapter/archer-t5e/ )
The module is recognised by lspci command but cant get the driver to load. I am just checking if anyone else has tried using similar adapter and did it work. I tested the module in my non prod lab machine which has dedicated A+E slot and works fine using the same procedure and operaiting system - debian bookworm.  I tried debugging the driver issue with no joy with dmesg not even including any reference to it. The issue is the "ls /dev/apex_0" command returns no response. Not sure if I should continue with this arrangement until my new card and module arrives. 

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  log:
    format: text
    #exec: trace
  streams:
    backdoor:
      - rtsp://admin:JGZ5rjqd43iL8UEh@192.168.20.80:554/h265Preview_01_main
      #- ffmpeg:backdoor#audio=opus
    backdoor_sub:
      - rtsp://admin:JGZ5rjqd43iL8UEh@192.168.20.80:554/h264Preview_01_sub
      #- ffmpeg:backdoor_sub#audio=opus

cameras:
  BackDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backdoor?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

#auth:
  #reset_admin_password: true


    motion:
      mask: 0,0.284,0,0,1,0,1,0.175,0.667,0.07,0.452,0.129
      threshold: 30
      contour_area: 30
      improve_contrast: true
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 512mb # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver 
      # instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/mydrive/frigate/config:/config
      - /mnt/mydrive/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      #- 5000:5000 # Internal unauthenticated access. Expose carefully.
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: password
networks:
  dockge_default:
    external: true
```

### Relevant Frigate log output

```shell
no reference to coral
```

### Install method

Docker

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

no appliable
