### DISCUSSION TITLE
[Bug]: /logs doesn't show full tag, wrong system version

### DISCUSSION THREAD

**Discussion by maxx-ukoo** [blakeblackshear/frigate#17891] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Tag doesn't contain camera name in UI logs. But copy to clipboard copy full tag:
![image](https://github.com/user-attachments/assets/e03fcf24-1cda-45cd-9813-bb0d0b21849a)
UI logs doesn't contain name like R-PTZ-CAM05

/system#general show version 0.15.0-6cb5cfb but I guess correct is 0.15.1 because 0.15.1 release has 6cb5cfb tag:

![image](https://github.com/user-attachments/assets/673a699e-bbb2-4dde-a834-f1c3b748380e)

![image](https://github.com/user-attachments/assets/6fb665b0-017b-4f4f-a222-954aafe8266d)

### Steps to reproduce

1.
2.
3.
...

### Version

ghcr.io/blakeblackshear/frigate:0.15.1

### Frigate config file

```yaml
N/A
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    privileged: true
    container_name: frigate

    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    shm_size: "768mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tb-pool/docker-opt/frigate/config.yml:/config/config.yml
      - /mnt/tb-pool/docker-opt/frigate/db:/opt/db
      - fr_cifs_mount:/media/frigate

    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:

      FRIGATE_RTSP_PASSWORD: "password"

volumes:
    fr_cifs_mount:
      driver: local
      driver_opts:
        type: cifs
        device: *******************************************
```

### Relevant Frigate log output

```shell
On screen
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

N/A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/3b0a9434-98d8-46ee-96c1-e94b47027089)
