### DISCUSSION TITLE
Generative AI - Need clarification on options for prompt

### DISCUSSION THREAD

**Discussion by WorldOfGZ** [blakeblackshear/frigate#17901] [Ask A Question] [answered]
Hello

I tried Generative AI with Gemini, this is really interesting. I just need your help on a point I don't understand on documentation.

If I take this example taken from documentation : 
```
genai:
  enabled: True
  provider: ollama
  base_url: http://localhost:11434
  model: llava
  prompt: "Analyze the {label} in these images from the {camera} security camera. Focus on the actions, behavior, and potential intent of the {label}, rather than just describing its appearance."
  object_prompts:
    person: "Examine the main person in these images. What are they doing and what might their actions suggest about their intent (e.g., approaching a door, leaving an area, standing still)? Do not describe the surroundings or static details."
    car: "Observe the primary vehicle in these images. Focus on its movement, direction, or purpose (e.g., parking, approaching, circling). If it's a delivery vehicle, mention the company."
```

What is sent to provider, in case of a person is detected ?
Is is `prompt` +` object_prompt.person`. Or just ` object_prompt.person`. I tried various generation, but I can't understand on which prompt I have to focus to have best results.

Thanks
