### DISCUSSION TITLE
[Camera Support]: Jennov PTZ Tracking outside Frigate

### DISCUSSION THREAD

**Discussion by Arokha** [blakeblackshear/frigate#17906] [Camera Support] [answered]
### Describe the problem you are having

I have a Jennov PTZ camera (which is probably just rebranded Hikvision) and PTZ works fine in the interface. Autotracking won't work with this camera (no FOV-relative PTZ) but the camera itself has a tracking system, oddly enabled by sending PTZ preset request for preset # 92 (it has some others like this, 81-83 being controls for IR lights, etc).

My issue is that the camera is apparently too dumb to return to a home position after tracking has ended, despite saying it does this in the manual (it says it returns to wherever it was before tracking started. It does not).

I've set PTZ Preset 1 to where I'd like the camera to sit usually... can I get Frigate to send PTZ Preset 1 'every now and then' if there's not currently a detection going? Or after each detection+60 seconds or something?

~~Like can I enable the autotracking but without any weights or whatever? And just make use of the return preset?~~ It just turns itself back off after deciding it's incompatible.

Also unrelated to anything in case anyone ever searches 'Jennov' on here, don't buy a Jennov. The clock is the worst RTC I've ever used. It drifts by ~50 minutes over 8 hours. I had to set up NTP to sync every 1 minute just to keep it in check.

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Firefox

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe

audio:
  enabled: false # CPU intensive, sorta pointless
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - bang
    - smash
    - breaking
    - cap_gun
    - artillery_fire
    - fireworks
    - explosion
    - gunshot

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

cameras:
  coyotes:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.99.10:554/stream0 # high res
          roles:
            - record
        - path: rtsp://192.168.99.10:554/stream1 # low res
          roles:
            - detect
            - audio
    detect:
      enabled: true
      width: 1280
      height: 720
    onvif:
      host: 192.168.99.10
      port: 80
      user: ''
      password: ''
      autotracking:
        enabled: false
        calibrate_on_startup: false # Once this camera has movement_weights, set this to false
        zooming: disabled # Maybe okay, maybe not! set to 'absolute' (usually works) or 'relative' (not supported everywhere)
        zoom_factor: 0.3 # greater number means less of scene visible, 0.1-0.75
        required_zones:
          - fullscreen
        return_preset: '1'
        timeout: 10 # seconds before returning to preset
    zones:
      fullscreen:
        coordinates: 0,1,0.615,1,0.615,0.888,1,0.884,1,0,0,0
        loitering_time: 0
    motion:
      mask: 0.621,0.906,0.98,0.904,0.98,0.955,0.621,0.957
      threshold: 20
      contour_area: 10
      improve_contrast: true
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Jennov M-Series Videolink

### Screenshots of the Frigate UI's System metrics pages

N/A
