### DISCUSSION TITLE
[Camera Support]: Reolink PoE Doorbell

### DISCUSSION THREAD

**Discussion by broyuken** [blakeblackshear/frigate#17907] [Camera Support] [answered]
### Describe the problem you are having

I have a reolink poe doorbell that I have set up ALMOST perfectly. The only issue I am running into now is that I am not getting audio into recordings when I have the 2 way audio active. 

Live view audio works, audio is also recorded in frigate UNTIL I start the 2 way audio, then it gets glitchy and isn't hearable. 

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Chrome, iOS App

### Frigate config file

```yaml
mqtt:
  host: 10.x.x.138
  user: homeassistant
  password: mqttpassword


detectors:
  coral:
    type: edgetpu
    device: usb


go2rtc:
  webrtc:
    listen: :8555
    candidates:
      - 10.x.x.138:8555
      - stun:8555
  streams:
    frigate_garage_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:PASSWORD@10.y.y.33/main
      - ffmpeg:frigate_garage_camera#audio=aac
    frigate_office_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:PASSWORD@10.y.y.12/main
      - ffmpeg:frigate_office_camera#audio=aac
    frigate_basement_back_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:PASSWORD@10.y.y.13/main
      - ffmpeg:frigate_basement_back_camera#audio=aac
    frigate_basement_playroom_camera:
      - rtsp://broyadmin:PASSWORD@10.y.y.10:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:frigate_basement_playroom_camera#audio=aac
    frigate_spare_camera:
      - ffmpeg:#input=-timeout 30000000 -i rtsp://thingino:PASSWORD@10.y.y.11/main
      - ffmpeg:frigate_spare_camera#audio=aac
    frigate_front_door_camera:
      -  rtsp://admin:PASSWORD@10.y.y.14/h264Preview_01_main
#      - "ffmpeg:frigate_front_door_camera#audio=aac"
    frigate_front_door_camera_sub:
      -  rtsp://admin:PASSWORD@10.y.y.14/h264Preview_01_sub
#      - "ffmpeg:frigate_front_door_camera#audio=aac"

objects:
  track:
    - person
    - face
    - dog
  filters: 
    person: 
    # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75


snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  height: 1080
  quality: 100
  retain:
    default: 30


live:
  height: 1080
  quality: 8


record:
  enabled: true
  retain:
    days: 90
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30


cameras:
  frigate_garage_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_garage_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:PASSWORD@10.y.y.33/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.793,0.204,0.789,0.205,0.833,0,0.834
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: false
    objects:
      track:
        - person
        - face
        - dog
        - car
        - bicycle


  frigate_office_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_office_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:PASSWORD@10.y.y.12/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      filters:
        person:
          mask:
            - 0.786,0.061,0.936,0.11,0.928,0.305,0.784,0.241
            - 0.525,0.032,0.522,0.5,0.619,0.554,0.628,0.04
            - 0.058,0.114,0.312,0.032,0.328,0.626,0.121,0.775,0.071,0.477
        dog:
          mask:
            - 0.524,0.032,0.524,0.5,0.619,0.552,0.63,0.04
            - 0.062,0.109,0.312,0.029,0.33,0.627,0.123,0.773,0.071,0.483
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.794,0.204,0.79,0.206,0.831,0,0.832
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: false
    zones:
      Desk:
        coordinates: 0.686,0.877,0.94,1,1,0.308,1,0,0.776,0
        loitering_time: 30
        objects: person
        inertia: 3


  frigate_basement_back_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_basement_back_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:PASSWORD@10.y.y.13/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0,0.791,0.205,0.791,0.205,0.833,0,0.833
      lightning_threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
      fps: 5
    mqtt:
      timestamp: false


  frigate_basement_playroom_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_basement_playroom_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://broyadmin:PASSWORD@10.y.y.10:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.664,0.036,0.973,0.037,0.972,0.075,0.664,0.078
      lightning_threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704
      height: 480
      fps: 5
    mqtt:
      timestamp: false

  frigate_spare_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_spare_camera # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://thingino:PASSWORD@10.y.y.11/sub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      lightning_threshold: 0.8
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
    mqtt:
      timestamp: false

  frigate_front_door_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frigate_front_door_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frigate_front_door_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 480
      height: 640
      fps: 5
    mqtt:
      timestamp: false

version: 0.15-1
camera_groups:
  Inside_Cameras:
    order: 1
    icon: LuCamera
    cameras:
      - frigate_basement_front_camera
      - frigate_office_camera
      - frigate_basement_playroom_camera
      - frigate_basement_back_camera
  Birdseye:
    order: 2
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
No relevant logs
```

### Relevant go2rtc log output

```shell
No relevant logs
```

### FFprobe output from your camera

```shell
No relevant logs
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink PoE Doorbell

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/43f49032-3667-4a32-98b6-8c890a4f0c00)
![image](https://github.com/user-attachments/assets/0d1ddcf6-7c48-49ef-b38c-3788bd03932e)

### Any other information that may be helpful

I'm assuming this is because the audio goes through the stun server for the 2 way and this isn't recorded correctly even though it plays back fine during live view.
