### DISCUSSION TITLE
[Camera Support]: Yi-hack camera not splitting recording

### DISCUSSION THREAD

**Discussion by a-bali** [blakeblackshear/frigate#17911] [Camera Support]
### Describe the problem you are having

I have a Yi Home Pro 2K camera running the latest [Yi-hack](https://github.com/roleoroleo/yi-hack-Allwinner-v2) firmware. I have recording set up in Frigate for the high resolution stream and my problem is that after some hours, ffmpeg gets stuck recording into the same file in /tmp/cache, i.e. there is a file that is growing continuously and Frigate shows no recordings in the history. My other cameras are recording properly, including an other model of exactly the same camera with the same firmware and settings.

Any ideas what extra ffmpeg parameters I could use to force splitting the recording properly?

Example (simon_camera is the problematic one):

```
bali@frigate:~$ docker exec frigate ls -l /tmp/cache/
total 170608
srwxr-xr-x 1 root root         0 Apr 25 16:32 comms
srwxr-xr-x 1 root root         0 Apr 25 16:32 config
-rw-r--r-- 1 root root   1298483 Apr 26 08:47 entry_camera@20250426084725+0200.mp4
-rw-r--r-- 1 root root        48 Apr 26 08:47 entry_camera@20250426084736+0200.mp4
-rw-r--r-- 1 root root    524336 Apr 26 08:47 garden_camera@20250426084726+0200.mp4
-rw-r--r-- 1 root root     37113 Apr 26 08:35 preview_entry_camera_1745648452.397714-1745648507.936728.mp4
-rw-r--r-- 1 root root     14178 Apr 26 08:35 preview_entry_camera_1745648535.377298-1745648551.979675.mp4
-rw-r--r-- 1 root root     20085 Apr 26 08:35 preview_entry_camera_1745648638.570301-1745648661.173004.mp4
-rw-r--r-- 1 root root     24230 Apr 26 08:35 preview_entry_camera_1745648824.800116-1745648840.977387.mp4
-rw-r--r-- 1 root root     17539 Apr 26 08:35 preview_entry_camera_1745648868.398685-1745648884.563876.mp4
-rw-r--r-- 1 root root     24881 Apr 26 08:35 preview_entry_camera_1745648926.789493-1745648953.555601.mp4
-rw-r--r-- 1 root root     20499 Apr 26 08:35 preview_entry_camera_1745649027.552783-1745649043.552783.mp4
-rw-r--r-- 1 root root     16089 Apr 26 08:35 preview_entry_camera_1745649212.968056-1745649230.767721.mp4
drwxr-xr-x 2 root root    141980 Apr 26 08:47 preview_frames
-rw-r--r-- 1 root root    138841 Apr 26 08:35 preview_simon_camera_1745648466.597729-1745648547.783314.mp4
-rw-r--r-- 1 root root     29492 Apr 26 08:35 preview_simon_camera_1745648932.396287-1745648948.600267.mp4
srwxr-xr-x 1 root root         0 Apr 25 16:32 proxy_pub
srwxr-xr-x 1 root root         0 Apr 25 16:32 proxy_sub
-rw-r--r-- 1 root root 170393648 Apr 26 08:47 simon_camera@20250425205606+0200.mp4
-rw-r--r-- 1 root root   1310768 Apr 26 08:47 simon_camera_new@20250426084727+0200.mp4
-rw-r--r-- 1 root root    786480 Apr 26 08:47 street_camera@20250426084730+0200.mp4
```

### Version

15.1

### Frigate config file

```yaml
ffmpeg:
  path: '5.0'

go2rtc:
  streams:
    simoncam_hi:
      - rtsp://simoncam.lan/ch0_0.h264
      - ffmpeg:simoncam_hi#audio=aac
    simoncam_lo:
      - rtsp://simoncam.lan/ch0_1.h264
      - ffmpeg:simoncam_lo#audio=aac
    [...]

cameras:
  simon_camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/simoncam_hi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/simoncam_lo
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: simoncam_hi
```

### Relevant Frigate log output

```shell
There is nothing in the logs
```

### Relevant go2rtc log output

```shell
There is nothing in the logs
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Other

### Network connection

Wireless

### Camera make and model

Xiaomi Yi Home Pro 2K

### Screenshots of the Frigate UI's System metrics pages

n/a
