### DISCUSSION TITLE
[Config Support]: Unable to get audio from Reolink Doorbell

### DISCUSSION THREAD

**Discussion by anyoneyun** [blakeblackshear/frigate#17918] [Config Support] [answered]
### Describe the problem you are having

Hi there. I'm unable to get any audio from my Reolink Doorbell in the live view. I tried a lot and I can't figure out what's wrong. In the config I am using two reolink cameras, one of them is the doorbell (named "reolink_doorbell"). Do you have any idea of what I'm missing? Thanks

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
auth:
  enabled: true
mqtt:
  enabled: false
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - localhost:8555
      - stun:8555
  ffmpeg:
    volume: -af "volume=10dB"
  streams:
    front_yard_camera_stream:
      - ffmpeg:http://192.168.1.27/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****#video=copy#audio=copy
    front_yard_camera_stream_sub:
      - ffmpeg:http://192.168.1.27/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****
    reolink_doorbell:
      - "ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****#video=copy#audio=copy#audio=opus#audio=volume"
      - rtsp://admin:EbE@tAG$HGFF5w@192.168.1.151:554/h264Preview_01_main
      - "ffmpeg:reolink#audio=opus"
    reolink_doorbell_sub:
      - "ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****"

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  front_yard_camera: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@192.168.1.27/Preview_01_main
          roles:
            - record
        - path: rtsp://192.168.1.150:8554/front_yard_camera_stream_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-vaapi
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    objects:
      mask: 0.291,0,0.717,0,0.719,0.086,0.292,0.094
      track:
        - person
        - car
        - motorcycle
        - bycicle
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  doorbell: 
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          roles:
            - record
            - audio
      hwaccel_args: preset-vaapi
    record:
      enabled: false
      retain:
        days: 2
        mode: all
    objects:
      mask: 0.291,0,0.717,0,0.719,0.086,0.292,0.094
      track:
        - person
        - car
        - motorcycle
        - bycicle
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-04-26 17:49:43.298708855  [2025-04-26 17:49:43] frigate.comms.dispatcher       ERROR   : Recordings must be enabled in the config to be turned on via MQTT.
2025-04-26 17:49:45.452933761  [2025-04-26 17:49:45] frigate.comms.dispatcher       ERROR   : Recordings must be enabled in the config to be turned on via MQTT.
2025-04-26 17:51:55.914887995  [2025-04-26 17:51:55] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2025-04-26 17:51:55.914987384  [2025-04-26 17:51:55] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2025-04-26 17:51:58.894158493  [2025-04-26 17:51:58] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2025-04-26 17:51:58.894276540  [2025-04-26 17:51:58] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-04-26 17:51:58.894376360  [2025-04-26 17:51:58] ffmpeg.doorbell.detect         ERROR   : [AVHWFramesContext @ 0x7f1de80aeb00] Failed to sync surface 0x15: 1 (operation failed).
2025-04-26 17:51:58.894460874  [2025-04-26 17:51:58] ffmpeg.doorbell.detect         ERROR   : [hwdownload @ 0x7f1de4003980] Failed to download frame: -5.
2025-04-26 17:51:58.894539616  [2025-04-26 17:51:58] ffmpeg.doorbell.detect         ERROR   : [vf#0:0 @ 0x56456cd7af80] Error while filtering: Input/output error
2025-04-26 17:51:58.894617426  [2025-04-26 17:51:58] ffmpeg.doorbell.detect         ERROR   : [vf#0:0 @ 0x56456cd7af80] Task finished with error code: -5 (Input/output error)
2025-04-26 17:51:58.894694588  [2025-04-26 17:51:58] ffmpeg.doorbell.detect         ERROR   : [vf#0:0 @ 0x56456cd7af80] Terminating thread with return code -5 (Input/output error)
```

### Relevant go2rtc log output

```shell
2025-04-26 17:48:53.659125531  [INFO] Preparing new go2rtc config...
2025-04-26 17:48:53.871222019  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2025-04-26 17:48:53.953833653  [INFO] Starting go2rtc...
2025-04-26 17:48:54.029045380  17:48:54.028 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-04-26 17:48:54.029048816  17:48:54.029 INF config path=/dev/shm/go2rtc.yaml
2025-04-26 17:48:54.029324473  17:48:54.029 INF [api] listen addr=:1984
2025-04-26 17:48:54.029525214  17:48:54.029 INF [rtsp] listen addr=:8554
2025-04-26 17:48:54.029687809  17:48:54.029 INF [webrtc] listen addr=:8555
2025-04-26 17:49:03.661284211  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    labels:
      - "glance.name=Frigate"
      - "glance.icon=di:frigate-light"
      - "glance.url=https://domain:8972"
      - "glance.description=NVR"
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # 108mb per 4k stream
    devices:
      - /dev/bus/usb:/dev/bus # USB Coral
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/francesca/docker_files/frigate/config:/config
      - /srv/dev-disk-by-uuid-885ed52b-1bf3-4cdf-8024-e59931c76563/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971"
    environment:
      FRIGATE_RTSP_PASSWORD: "****"
```

### Object Detector

OpenVino

**Comment by hawkeye217** [comment]
You need to either match your camera names to your go2rtc stream names, or you need to use the `live --> stream_name` directive.

See the official documentation: 

https://docs.frigate.video/configuration/restream#reduce-connections-to-camera
https://docs.frigate.video/configuration/live/

**Reply by anyoneyun** [reply]
Hi there, thank you for pointing this out. It helped me already! Now I can speak to the camera and it will broadcast the audio from my pc and my phone. However, I'm still unable to receive any audio from the camera itself.

**Reply by hawkeye217** [reply]
The errors in your Frigate log also indicate you need to change your hwaccel preset.

See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/16391), Upgrade Issues question 1.

**Reply by hawkeye217** [reply]
Additionally, you should be using the recommended Reolink config. See the documentation: https://docs.frigate.video/configuration/camera_specific/#reolink-cameras

**Reply by anyoneyun** [reply]
All right, I changed the things you pointed out. Thanks! However I'm still unable to get audio from the doorbell. Here's the updated configuration:

```
auth:
  enabled: true
mqtt:
  enabled: false
go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - localhost:8555
      - stun:8555
  ffmpeg:
    volume: -af "volume=10dB"
  streams:
    front_yard_camera:
      - ffmpeg:http://192.168.1.27/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****#video=copy#audio=copy
    front_yard_camera_sub:
      - ffmpeg:http://192.168.1.27/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****
    reolink_doorbell:
      - "ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=****#video=copy#audio=copy#audio=opus#audio=volume"
      - rtsp://admin:****@192.168.1.151:554/h264Preview_01_sub
    reolink_doorbell_sub:
      - "ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=****"

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  front_yard_camera: 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      hwaccel_args: preset-intel-qsv-h264
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    objects:
      mask: 0.291,0,0.717,0,0.719,0.086,0.292,0.094
      track:
        - person
        - car
        - motorcycle
        - bycicle
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  reolink_doorbell: 
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          roles:
            - record
            - audio
      hwaccel_args: preset-intel-qsv-h264
    record:
      enabled: false
      retain:
        days: 2
        mode: all
    objects:
      mask: 0.291,0,0.717,0,0.719,0.086,0.292,0.094
      track:
        - person
        - car
        - motorcycle
        - bycicle
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
version: 0.15-1
```
