### DISCUSSION TITLE
[Config Support]: Getting wrong version number in Portainer for Frigate

### DISCUSSION THREAD

**Discussion by Alfagek** [blakeblackshear/frigate#17910] [Config Support] [answered]
### Describe the problem you are having

If getting a "update" message from Home Assistant, that my Frigate have to update from 15.0 to 15.1.

And if i do a "recreate container" with "new pull" from portainer, it recreate the container. And still i got the message that i have to update Frigate.

When i see a the details of the container, it looks like that there is something wrong in the "latest version".

I see:

![image](https://github.com/user-attachments/assets/672003c6-1e4e-48bd-906a-ffc152e67d8e)

And if i compare that with the latest version on github, the HEX ( 6cb5cfb ) code is indentical.

![image](https://github.com/user-attachments/assets/aeb3140f-2e8f-4d09-b05b-32acbd2bcb9a)

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
Not needed
```

### Relevant Frigate log output

```shell
Not needed
```

### Relevant go2rtc log output

```shell
not needed
```

### Frigate stats

```json
not needed
```

### Operating system

Proxmox

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": false,
        "AttachStdout": true,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "FRIGATE_RTSP_PASSWORD=nl2mml",
            "PATH=/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/tempio/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NVIDIA_VISIBLE_DEVICES=all",
            "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
            "S6_LOGGING_SCRIPT=T 1 n0 s10000000 T",
            "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
            "TOKENIZERS_PARALLELISM=true",
            "TRANSFORMERS_NO_ADVISORY_WARNINGS=1",
            "OPENCV_FFMPEG_LOGLEVEL=8"
        ],
        "ExposedPorts": {
            "1935/tcp": {},
            "5000/tcp": {},
            "8554/tcp": {},
            "8555/tcp": {},
            "8555/udp": {}
        },
        "Healthcheck": {
            "Interval": 15000000000,
            "Retries": 3,
            "StartPeriod": 120000000000,
            "Test": [
                "CMD-SHELL",
                "curl --fail --silent --show-error http://127.0.0.1:5000/api/version || exit 1"
            ],
            "Timeout": 5000000000
        },
        "Hostname": "eee3e431b6f9",
        "Image": "ghcr.io/blakeblackshear/frigate:stable",
        "Labels": {
            "com.docker.compose.config-hash": "606a5aa2a0a67d3589445870b0a778d634069afdc6731f7f6a7232a82c77dc6b",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.depends_on": "",
            "com.docker.compose.image": "sha256:d1502760b3b1eb627b63bb4f7f44b786228930d98403a12852f9708f1a6fd4c0",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "frigate",
            "com.docker.compose.project.config_files": "/data/compose/4/docker-compose.yml",
            "com.docker.compose.project.working_dir": "/data/compose/4",
            "com.docker.compose.replace": "52ce604828183413b3c470f6ae6d83eead8a3a4b431a3c19cae0d3fb30f7e4ba",
            "com.docker.compose.service": "frigate",
            "com.docker.compose.version": "2.29.2"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": "/opt/frigate"
    },
    "Created": "2025-04-26T06:01:50.811728833Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/0723fd70a18e4b7c7907a007c3578f43f529a95d4149756199ef4c44d9076373-init/diff:/var/lib/docker/overlay2/86cf45624e17f6a7b2021e9e21cb5ac98f844da32a909a2b69629b4694da619c/diff:/var/lib/docker/overlay2/b2483d8714ae86bcae541769b71eb174d07be4674394c6094c155241edd1fdb2/diff:/var/lib/docker/overlay2/adbab83eb2625d7bbac663c6061a4e5bcd218b236407c9b6c765d9cbaaf44ea6/diff:/var/lib/docker/overlay2/adac8e1b14fa6d90d983422147422a00cb4240b0c6c9ef62c6ea5b030bb4140e/diff:/var/lib/docker/overlay2/30ff935a7113952e2e2eab7b1705c3cd6011ff7cbdf8995b78ba81b8a27f923d/diff:/var/lib/docker/overlay2/6f7ef17199ab8f82fc76dfb7408bf704a7d0931c7ac8eb517734d7be9db95a5d/diff:/var/lib/docker/overlay2/bc6585233bffafa695443373810dd0ffa5cf096f76d4e88797a990f8dfd22c9f/diff",
            "MergedDir": "/var/lib/docker/overlay2/0723fd70a18e4b7c7907a007c3578f43f529a95d4149756199ef4c44d9076373/merged",
            "UpperDir": "/var/lib/docker/overlay2/0723fd70a18e4b7c7907a007c3578f43f529a95d4149756199ef4c44d9076373/diff",
            "WorkDir": "/var/lib/docker/overlay2/0723fd70a18e4b7c7907a007c3578f43f529a95d4149756199ef4c44d9076373/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/shared/frigate:/media/frigate:rw",
            "/frigatedb:/media/frigate/db:rw",
            "/shared/frigate/config:/config:rw"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "private",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [
            {
                "CgroupPermissions": "rwm",
                "PathInContainer": "/dev/bus/usb",
                "PathOnHost": "/dev/bus/usb"
            },
            {
                "CgroupPermissions": "rwm",
                "PathInContainer": "/dev/dri/renderD128",
                "PathOnHost": "/dev/dri/renderD128"
            }
        ],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "Mounts": [
            {
                "Target": "/tmp/cache",
                "TmpfsOptions": {
                    "SizeBytes": 1000000000
                },
                "Type": "tmpfs"
            }
        ],
        "NanoCpus": 0,
        "NetworkMode": "frigate_default",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "1935/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "1935"
                }
            ],
            "5000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "5000"
                }
            ]
        },
        "Privileged": true,
        "PublishAllPorts": false,
        "ReadonlyPaths": null,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "Runtime": "runc",
        "SecurityOpt": [
            "label=disable"
        ],
        "ShmSize": 2147483648,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/95a2fb9120d7ce80785c0771ba7befb4923a3b5ef5cbebff9da04bf70a7bfaab/hostname",
    "HostsPath": "/var/lib/docker/containers/95a2fb9120d7ce80785c0771ba7befb4923a3b5ef5cbebff9da04bf70a7bfaab/hosts",
    "Id": "95a2fb9120d7ce80785c0771ba7befb4923a3b5ef5cbebff9da04bf70a7bfaab",
    "Image": "sha256:79c58d8956435e20905cb1d32b89a08c9f90b9b473b82bf5736af0f3b5dd0ba3",
    "LogPath": "/var/lib/docker/containers/95a2fb9120d7ce80785c0771ba7befb4923a3b5ef5cbebff9da04bf70a7bfaab/95a2fb9120d7ce80785c0771ba7befb4923a3b5ef5cbebff9da04bf70a7bfaab-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/tmp/cache",
            "Mode": "",
            "Propagation": "",
            "RW": true,
            "Source": "",
            "Type": "tmpfs"
        },
        {
            "Destination": "/media/frigate",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/shared/frigate",
            "Type": "bind"
        },
        {
            "Destination": "/media/frigate/db",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/frigatedb",
            "Type": "bind"
        },
        {
            "Destination": "/config",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/shared/frigate/config",
            "Type": "bind"
        }
    ],
    "Name": "/Frigate",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "frigate_default": {
                "Aliases": [
                    "frigate-",
                    "frigate",
                    "eee3e431b6f9",
                    "c90aa1d7aef9",
                    "96dac503e085",
                    "95a2fb9120d7"
                ],
                "DriverOpts": null,
                "EndpointID": "30af56292e6d2600854c147407a76625291619af46c4a8ca5c1c8307f2c34c65",
                "Gateway": "172.20.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "172.20.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:14:00:02",
                "NetworkID": "0c46ccd7b8448f571b365aa12926bbe45976a90c085e044f3373ddaed44756d9"
            }
        },
        "Ports": {
            "1935/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "1935"
                }
            ],
            "5000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "5000"
                }
            ],
            "8554/tcp": null,
            "8555/tcp": null,
            "8555/udp": null
        },
        "SandboxID": "68f16ece75fe36eacd3bb5e0f35bb093f798e119b346027563fbd9bfd48e1ac1",
        "SandboxKey": "/var/run/docker/netns/68f16ece75fe",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 24,
            "ResourceId": "2_frigate",
            "SubResourceIds": [],
            "Type": 6,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/95a2fb9120d7ce80785c0771ba7befb4923a3b5ef5cbebff9da04bf70a7bfaab/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "Health": {
            "FailingStreak": 0,
            "Log": [
                {
                    "End": "2025-04-26T08:21:25.460744245+02:00",
                    "ExitCode": 0,
                    "Output": "0.15.0-6cb5cfb",
                    "Start": "2025-04-26T08:21:25.417320103+02:00"
                },
                {
                    "End": "2025-04-26T08:21:40.515158473+02:00",
                    "ExitCode": 0,
                    "Output": "0.15.0-6cb5cfb",
                    "Start": "2025-04-26T08:21:40.47787183+02:00"
                },
                {
                    "End": "2025-04-26T08:21:55.569234541+02:00",
                    "ExitCode": 0,
                    "Output": "0.15.0-6cb5cfb",
                    "Start": "2025-04-26T08:21:55.529903685+02:00"
                },
                {
                    "End": "2025-04-26T08:22:10.62249171+02:00",
                    "ExitCode": 0,
                    "Output": "0.15.0-6cb5cfb",
                    "Start": "2025-04-26T08:22:10.582993288+02:00"
                },
                {
                    "End": "2025-04-26T08:22:25.684930918+02:00",
                    "ExitCode": 0,
                    "Output": "0.15.0-6cb5cfb",
                    "Start": "2025-04-26T08:22:25.640748225+02:00"
                }
            ],
            "Status": "healthy"
        },
        "OOMKilled": false,
        "Paused": false,
        "Pid": 124558,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2025-04-26T06:01:51.240005061Z",
        "Status": "running"
    }
}
```

### Object Detector

Coral

### Any other information that may be helpful

Running Frigate in a LXC container maintained by Portainer.
