### DISCUSSION TITLE
IOPs/CPU  consumption peak

### DISCUSSION THREAD

**Discussion by Rsptsa** [blakeblackshear/frigate#17929] [General]
Hello everyone,

I discovered the amazing Frigate a few months ago but I feel like I have some performance issues since I upgraded to v15.1

As you can see from screenshots below, the CPU load is increasing very frequently ( each 15min) and it seems that the cause is on the frigate side.

![Capture d'écran 2025-04-27 195637](https://github.com/user-attachments/assets/2ebe504c-a372-4c89-aff4-e014966d7568)
![Capture d'écran 2025-04-27 195102](https://github.com/user-attachments/assets/275f6be1-8347-47c9-bf0a-cf76f83547ef)
![Capture d'écran 2025-04-27 195049](https://github.com/user-attachments/assets/62b1dc5b-d510-431a-95ce-e9cc793558f7)
![Capture d'écran 2025-04-27 195010](https://github.com/user-attachments/assets/8df55ae1-4f5c-438a-8914-9ed26bdd67c6)

My config file :
```
logger:
  logs:
    frigate.ptz.onvif: debug

ffmpeg:
  hwaccel_args: preset-vaapi

mqtt:
  enabled: true
  host: 10.0.10.254
  port: 1883
  topic_prefix: frigate
  user: mqtt_user
  password: secure_pass

record:
  enabled: True
  retain:
    days: 5
    mode: motion
  alerts:
    retain:
      days: 7
      mode: motion
  detections:
    retain:
      days: 7
      mode: motion

birdseye:
  mode: continuous

detect:
  enabled: true
  width: 352
  height: 288

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    toit-arriere_hd: rtsp://cctv:secure_pass_@10.0.20.107:554/cam/realmonitor?channel=1&subtype=0
    toit-arriere_ld: rtsp://cctv:secure_pass_@10.0.20.107:554/cam/realmonitor?channel=1&subtype=1
    toit-route_hd:
      - rtsp://cctv:secure_pass_@10.0.20.108:554/cam/realmonitor?channel=1&subtype=0
    toit-route_ld: rtsp://cctv:secure_pass_@10.0.20.108:554/cam/realmonitor?channel=1&subtype=1
    portail_hd:
      - rtsp://cctv:secure_pass_@10.0.20.103:554/cam/realmonitor?channel=1&subtype=0#video=copy#audio=copy#audio=aac#hardware
    portail_ld: rtsp://cctv:secure_pass_@10.0.20.103:554/cam/realmonitor?channel=1&subtype=1
    rue_hd:
      - rtsp://cctv:secure_pass_@10.0.20.154:554/cam/realmonitor?channel=1&subtype=0
    rue_ld: rtsp://cctv:secure_pass_@10.0.20.154:554/cam/realmonitor?channel=1&subtype=1
    dafang-01:
      - rtsp://10.0.20.229:554/unicast
cameras:
  toit-arriere:
    enabled: true
    detect:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/toit-arriere_hd
          input_args: preset-rtsp-restream
          roles:
            - record
 
    live:
      stream_name: toit-arriere_hd
  dafang:
    enabled: true
    detect:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dafang-01
           

  toit-route:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/toit-route_hd
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/toit-route_ld
          roles:
            - detect
    zones:
      root:
        coordinates: 9,10,691,9,690,566,2,564
    onvif:
      host: 10.0.20.108
      port: 80
      user: onvifusr
      password: secure_pass
      ignore_time_mismatch: true
      autotracking:
        enabled: false
        calibrate_on_startup: false
        zooming: absolute
        zoom_factor: 0.2
        track:
          - person
        required_zones:
          - root
        return_preset: home
        timeout: 10
        movement_weights: 0.04, 1.0, 3.0810298919677734, 3.218813463949389, 0.012187412477308692
    objects:
      track:
        - person
    live:
      stream_name: toit-route_hd

  rue:
    enabled: true
    detect:
      enabled: true
      width: 352
      height: 288
      fps: 5
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rue_hd
          input_args: preset-rtsp-restream
          roles:
            - record
 #       - path: rtsp://127.0.0.1:8554/rue_ld
 #        input_args: preset-rtsp-restream
 #         roles:
 #           - detect
    live:
      stream_name: rue_hd
    onvif:
      host: 10.0.20.154
      port: 80
      user: onvifusr
      password: secure_pass
      ignore_time_mismatch: true
    zones:
      FDP:
        coordinates: 0,0.479,0,1,0.801,1,0.941,1,0.933,0.367,0.871,0.323,0.71,0.326,0.592,0.357,0.338,0.408
        inertia: 1
        loitering_time: 0
        objects: person
    motion:
      threshold: 10
      contour_area: 5
      improve_contrast: true
      mask: 0.268,0.569,0.31,0.651,0.385,0.761,0.426,0.875,0.595,0.883,0.608,0.643,0.595,0.55,0.624,0.408,0.706,0.098,0.568,0.013,0.091,-0.002,0.286,0.488,0.325,0.542,0.373,0.551,0.311,0.547

  portail:
    enabled: true
    detect:
      enabled: true
      width: 352
      height: 288
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/portail_hd
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/portail_ld
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: True
      retain:
        days: 5
        mode: all
    objects:
      track:
        - person
        - car
      filters:
        person: {}
    live:
      stream_name: portail_hd
    zones:
      portail_zone_vehicle:
        coordinates: 0.148,0.174,0.137,0.505,0.381,0.516,0.376,0.172
        loitering_time: 0
        objects: car
        inertia: 3
      portail_zone_personne2:
        coordinates: 0.006,0.143,0.151,0.171,0.138,0.501,0.375,0.508,0.373,0.167,0.986,0.092,0.986,0.982,0.01,0.994
        loitering_time: 0
        objects: person
        inertia: 1
      Portail_zone_personne1:
        coordinates: 0.145,0.37,0.14,0.502,0.368,0.503,0.373,0.408,0.373,0.308,0.371,0.172,0.155,0.171
        inertia: 1
        loitering_time: 0
        min_score: 0.1
        threshold: 0.5
        min_area: 500
        objects: person
    motion:
      improve_contrast: true
      threshold: 10
      contour_area: 5
    onvif:
      host: 10.0.20.103
      port: 80
      user: cctv
      password: secure_pass
      ignore_time_mismatch: true

camera_groups:
  PTZ:
    order: 1
    icon: LuAlignVerticalDistributeEnd
    cameras: toit-route
  BirdsEye:
    order: 2
    icon: LuAngry
    cameras:
      - birdseye
      - portail
      - toit-route

version: 0.15-1
```

result of : /usr/sbin/iotop -ao

![Capture d'écran 2025-04-28 090319](https://github.com/user-attachments/assets/31a7ffeb-19cd-4d09-aecf-033d4eafea21)

Do you have any idea why the frigate activity is so high every 15 minutes or can I optimise my conf ?

Thanks.
