### DISCUSSION TITLE
[Bug]: Cannot read properties of null (reading 'npu')

### DISCUSSION THREAD

**Discussion by oDestroyeRo** [blakeblackshear/frigate#17926] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

![image](https://github.com/user-attachments/assets/e2d1a104-06ad-4abb-b7b4-497014f19afc)

### Steps to reproduce

1. go to http://{frigate_url}}:5000/system#general
2. not show anything on screen

### Version

 0.16.0-2610cfc

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-rk-h264

detect:
  enabled: true
  fps: 5

objects:
  track:
    - person
    - cat
    - dog

detectors: # required
  rknn: # required
    type: rknn # required
    # number of NPU cores to use
    # 0 means choose automatically
    # increase for better performance if you have a multicore NPU e.g. set to 3 on rk3588
    num_cores: 3

model: # required
  model_type: yolonas
  # name of model (will be automatically downloaded) or path to your own .rknn model file
  # possible values are:
  # - deci-fp16-yolonas_s
  # - deci-fp16-yolonas_m
  # - deci-fp16-yolonas_l
  # - /config/model_cache/your_custom_model.rknn
  path: deci-fp16-yolonas_m
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolo models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc
  # needs to be adjusted to model, see below
  labelmap_path: /labelmap/coco-80.txt # required

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  streams:
    camera1:
      - rtsp://odestroyero:1111@192.168.88.182:554/stream1#input=rtsp/udp
      - ffmpeg:camera1#video=h265#audio=aac#hardware=rkmpp
    camera2:
      - rtsp://odestroyero:1111@192.168.88.183:554/stream1#input=rtsp/udp
      - ffmpeg:camera2#video=h265#audio=aac#hardware=rkmpp
    camera3:
      - rtsp://odestroyero:1111@192.168.88.184:554/stream1#input=rtsp/udp
      - ffmpeg:camera3#video=h265#audio=aac#hardware=rkmpp
    camera4:
      - rtsp://odestroyero:1111@192.168.88.185:554/stream1#input=rtsp/udp
      - ffmpeg:camera4#video=h265#audio=aac#hardware=rkmpp

cameras:
  camera1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 192.168.88.182
      port: 2020
      user: odestroyero
      password: 1111
    live:
      streams:
        camera1: camera1
    motion:
      mask: 0,0,0.354,0,0.353,0.04,0,0.038
  camera2: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 192.168.88.183
      port: 2020
      user: odestroyero
      password: 1111
    live:
      streams:
        camera2: camera2
    motion:
      mask: 0,0.001,0.352,0,0.352,0.037,0.001,0.04
  camera3: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera3
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 192.168.88.184
      port: 2020
      user: odestroyero
      password: 1111
    live:
      streams:
        camera3: camera3
    motion:
      mask: 0,0,0.351,0,0.35,0.043,0,0.041
  camera4: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera4
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 192.168.88.185
      port: 2020
      user: odestroyero
      password: 1111
    live:
      streams:
        camera4: camera4
    motion:
      mask: 0.001,0.003,0.351,0.002,0.351,0.038,0.001,0.04
camera_groups: {}
version: 0.16-0
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: false
classification:
  bird:
    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
---
# https://github.com/blakeblackshear/frigate
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:2610cfc-rk
    shm_size: "1024mb"
    devices:
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-uuid-4fb7f68e-db44-4518-8b30-1d9005dc2e1f/data/frigate/config:/config
      - /srv/dev-disk-by-uuid-4fb7f68e-db44-4518-8b30-1d9005dc2e1f/data/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971"
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tapo c230

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/e2d1a104-06ad-4abb-b7b4-497014f19afc)
