### DISCUSSION TITLE
[Config Support]: Self-signed TLS certificate without Letsencrypt (LXC without Docker)

### DISCUSSION THREAD

**Discussion by V4ler1an** [blakeblackshear/frigate#17920] [Config Support] [answered]
### Describe the problem you are having

I'm trying to get the Frigate web UI to use my own self-signed TLS certificate and enforce authentication. I already have (tested, working, used elsewhere) cert privkey.pem and fullchain.pem files, I don't need to use tools like Letsencrypt. I've tried copying the files into the following folders but after restarting, Frigate continues using its own default self-signed cert. I'm accessing Frigate on https://[my FQDN]:8971 because i'm running an LXC without Docker so cannot easily map 443 : 8971. When not using a cert bot, do the certificate files need to be put somewhere else for Frigate to find and use them?

/etc/letsencrypt/live/frigate/
/etc/letsencrypt/live/[my FQDN]/

Second issue, i've tried enforcing authentication but Frigate still takes me straight in on http://[my FQDN]:5000 without an auth challenge? https://[my FQDN]:8971 does ask for login. Why is anonymous still working on 5000?

I've added these lines to my config.yml:

auth:
  enabled: true
tls:
  enabled: true

### Version

0.14.1

### Frigate config file

```yaml
auth:
  enabled: true
  reset_admin_password: false
tls:
  enabled: true
mqtt:
  enabled: true
  host: <my hostname>
  port: 1883
  user: mqtt_frigate
  password: <my mqtt password>
cameras:
  <my camera>:
    enabled: true
    snapshots:
      enabled: true
      required_zones:
        - Street
        - Drive
        - Path
      # - Footpath
        - Lawn
      retain:
        default: 90
        mode: active_objects
    record:
      sync_recordings: true
      enabled: true
      retain:
        days: 1
        mode: active_objects
      events:
        retain:
          default: 1
          mode: active_objects
    mqtt:
      enabled: true
      crop: true
      timestamp: false
      required_zones:
        - Street
        - Drive
        - Path
        - Footpath
        - Lawn
    ffmpeg:
      #GPU accel - Intel Gen8 to 12, automatically detects h264 or h265. Same arg also works for AMD/Radeon 2000(+) GPUs.
      hwaccel_args: preset-vaapi
      inputs:
        # High Resolution Stream
        - path: 
            rtsp://<my user + pass>@<my camera address>:554/h265Preview_01_main
          roles:
            - record
        # Low Resolution Stream
        - path: 
            rtsp://<my user + pass>@<my camera address>:554/h264Preview_01_sub
          roles:
            - detect
            - audio
    detect:
      enabled: true
      height: 512
      width: 896
      fps: 6
    motion:
      mask: <co-ordinates>
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bicycle
        - motorcycle
      filters:
        car:
          mask: 
            <co-ordinates>
    zones:
      Street:
        coordinates: 
          <co-ordinates>
        loitering_time: 6
        inertia: 3
        objects: car
      Drive:
        coordinates: 
          <co-ordinates>
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - person
      Path:
        coordinates: <co-ordinates>
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - dog
          - cat
      Footpath:
        enabled: false
        coordinates: 
          <co-ordinates>
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - bicycle
          - cat
          - dog
      Lawn:
        coordinates: <co-ordinates>
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones:
          - Street
          - Path
        # - Footpath
          - Lawn
          - Drive
        labels:
          - car
          - cat
          - dog
          - person
          - bicycle
          - motorbike
      detections:
        required_zones:
          - Drive
          - Lawn
          - Path
        # - Footpath
          - Street
        labels:
          - car
          - cat
          - dog
          - person
          - bicycle
          - motorbike
detectors:
  #OpenVino - Intel Arc GPUs, Intel integrated GPUs, and Intel CPUs
  ov:
    type: openvino
    device: GPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
version: 0.14
```

### Relevant Frigate log output

```shell
I'm seeing none that relate to TLS or authentication.
```

### Relevant go2rtc log output

```shell
n/a?
```

### Operating system

Debian

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
LXC without Docker.
```

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/6cc50a36-84d8-4e5a-9b99-be6c8cf3dac0)
