### DISCUSSION TITLE
Frigate Docker-Compose will not start after recovering Debian12 from backup. Docker compose returning "services.frigate.environment.[0]: unexpected type map[string]interface {}"

### DISCUSSION THREAD

**Discussion by birdman7160** [blakeblackshear/frigate#17939] [Config Support] [answered]
### Describe the problem you are having

Frigate was running fine until i ran out of storage space on my C: drive. I copied Frigate "storage" to another disk on my PC since i was running out of space on my C: drive. I was unable to recover the storage space after removing the storage directory so i had to remove Debian and recover Debian12 from a  backup. After recovering Debian I uninstalled Docker Desktop and reinstalled it.  The only change to my "docker-compose.yaml" was the volume entry pointing to the D: drive for the Frigate storage. I have not been able to start Frigate since the Debian recovery which is when i began getting the "services.frigate.environment.[0]: unexpected type map[string]interface {}" error.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.38:5000/api/config/schema.json

mqtt:
  host: 192.168.0.140
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  enabled: true
  user: mqtt-user
  password: Jmmmqtt
  stats_interval: 60
# ffmpeg:
#  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    front_porch:
      - rtsp://admin:Jmmreolink01@192.168.0.81:554/h264Preview_01_sub
      - ffmpeg:rtsp://admin:Jmmreolink01@192.168.0.81:554/h264Preview_01_sub#audio=pcm#audio=volume#


record:
  enabled: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 2
  detections:
    retain:
      days: 2

audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell

snapshots:
  enabled: true
  retain:
    default: 2

cameras:
  front_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_main #HIGH RESOLUTION
          roles:
            - record
        - path: rtsp://admin:Jmmreolink01@192.168.0.81:554/Preview_01_sub #LOW RESOLUTION
          roles:
            - detect
            - audio


    motion:
      mask:
        - 0.226,0,0.228,0.036,0.721,0.034,0.719,0.004,0.47,0.001
        - 0.151,0.632,0.478,0.63,0.486,0.377,0.314,0.333,0.156,0.388
    zones:
      front_porch_entry:
        coordinates: 0.131,0.652,0.474,0.688,0.478,0.768,0.308,0.774,0.139,0.754
        loitering_time: 10
        objects: person
    review:
      alerts:
        required_zones: front_porch_entry
      detections:
        required_zones: front_porch_entry
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:LAGGJW@192.168.0.57:554/Streaming/Channels/101/  #HIGH RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:LAGGJW@192.168.0.57:554/Streaming/Channels/102/  #LOW RESOLUTION
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    detect:
      enabled: true


version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
notifications:
  enabled: 'true'
  email: JOHNM8059@GMAIL.COM
```

### Relevant Frigate log output

```shell
None available since Frigate will not start
```

### Relevant go2rtc log output

```shell
None available since Frigate will not start
```

### Frigate stats

```json
None available since Frigate will not start
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/millerdebian/frigate/config.yml:/config/config.yml
#      - /home/millerdebian/frigate/storage:/media/frigate
      - D:\frigate\storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

None available since Frigate will not start

### Any other information that may be helpful

I am running this on a Dell Optiplex 7090 with iGPU using Debian12 Linux. I installed LIBVA as well as OpenCL.
