### DISCUSSION TITLE
What would cause a detection and snapshot to save, but a clip to NOT be saved?

### DISCUSSION THREAD

**Discussion by bobloadmire** [blakeblackshear/frigate#17941] [Ask A Question]
I have a bunch of cameras setup, they are all identical cameras with the same config, except different IPs and zones. One camera in particular is detecting events, saving a snapshot, but not providing a clip. If I play back the recording, the footage of the detection event is there. 

camera config: 

```
  driveway:
    enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic
#        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: driveway
    zones:
      Driveway:
        coordinates: 0.016,0.195,0.272,0.153,0.8,0.721,0.757,1,0.006,0.996,0,0.299
        loitering_time: 0
        inertia: 3
      Street:
        coordinates: 1,0.926,1,0.578,0.365,0.055,0.191,0.074
        loitering_time: 8
        objects: car
        inertia: 3
    review:
      alerts:
        required_zones:
          - Driveway
          - Street
      detections:
        required_zones:
          - Driveway
          - Street
    objects:
      filters:
        car:
          mask: 0.043,0.65,0.553,0.453,0.401,0.302,0.021,0.424
```

record config:

```
record:
  enabled: true # Keep disabled for testing
  retain: # Settings for continuous recording (if applicable when enabled)
    days: 3
    mode: motion
  # Settings for clips associated with alerts/detections:
  alerts:
    # You can add pre/post capture here if desired
    retain:
      days: 30 # Your desired retention
      mode: motion # Your desired retention mode
  detections:
    # You can add pre/post capture here if desired
    retain:
      days: 30 # Your desired retention
      mode: motion # Your desired retention mode
objects:
  track:
    - person
    - dog
    - cat
    - car
  filters:
    person:
      min_score: 0.5
      threshold: 0.8
audio:
  enabled: false
birdseye:
  enabled: false
semantic_search:
  enabled: true
  reindex: false
  model_size: large
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 70
```

Note the other cameras I have, are all detecting, snapshotting, and saving clips fine, however I'm not using zones on those cameras, related?

**Comment by NickM-27** [comment]
the object did not enter one of the required zones, you don't have required zones set for snapshots

**Reply by bobloadmire** [reply]
Guess I need to reread the docs because my feble mind isn't comprehending why there would be an event detected in my zone, and a snapshot saved, but it wouldn't save a clip? because it appears cars are coming into my zone and after the loitering time is met, a snapshot is being made, but no clip. I think I have a fundamental misunderstanding of how zones work. If I set up zones, is frigate still looking for detections outside of the zones? guess I need to exclude the frame outside my zones for detection?

**Reply by bobloadmire** [reply]
for instance I have 2 zones, driveway and street. 

Alerts I have Driveway and Street checked.
Detections i have just Driveway checked.
Limite detections to specific zones is also checked.

**Reply by NickM-27** [reply]
you have only configured required_zones for reviews (clips). Nowhere did you set required zones for snapshots, meaning snapshots will be saved for every object regardless of if they enter the zone

**Reply by bobloadmire** [reply]
got it! I thought the "Limit detections to specific zones" would basically stop Frigate for looking for stuff outside my zones

**Reply by NickM-27** [reply]
No, alerts and detections are just different categories of reviews

**Reply by bobloadmire** [reply]
ok so here is my config with required zones, I'm still getting snapshots: 
```
cameras:
  driveway:
    enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
#        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: driveway
    snapshots:
      required_zones:
        - Driveway
        - Street
    zones:
      Driveway:
        coordinates: 0.016,0.195,0.272,0.153,0.8,0.721,0.757,1,0.006,0.996,0,0.299
        loitering_time: 0
        inertia: 3
      Street:
        coordinates: 1,0.926,1,0.578,0.365,0.055,0.191,0.074
        loitering_time: 8
        objects: car
        inertia: 3
    review:
      alerts:
        required_zones:
          - Driveway
          - Street
      detections:
        required_zones: Driveway
    objects:
      filters:
        car:
          mask: 0.043,0.65,0.553,0.453,0.401,0.302,0.021,0.424
    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true
      mask: 0,0,0.354,0,0.354,0.045,0,0.042
```
