### DISCUSSION TITLE
[Support]: Can a snapshot be taken only when object become Stationary?

### DISCUSSION THREAD

**Discussion by tyanai** [blakeblackshear/frigate#17947] [General Support]
### Describe the problem you are having

Hi,

I'm using Frigate/Frigate+ with ALPR detection, and everything generally works well. However, I've noticed that occasionally — especially after dark — the snapshot captured during an event (of car detection) ends up being either blurry due to low light and the car's high speed, or it's simply too late to have a clear view of the license plate.

I understand that Frigate offers a stationary mode and selects the optimal frame for the snapshot. Therefore, I was thinking it might be beneficial to modify the system so that the snapshot is optionally taken once the object transitions into stationary mode.

Thanks,

Tal.

### Version

0.15.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.XXX
  user: xxxxx
  password: xxxxx
go2rtc:
  streams:
    reolink_entry_road:
      - rtsp://192.168.1.xxx:33xxx/xxxxxxxxxxxxxxxx


cameras:
  reolink_entry_road:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_entry_road
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      contour_area: 15
      improve_contrast: true
      mask:
        - 0.746,0,0.352,0,0.331,0.114,0.532,0.109,0.98,0.989,1,0.497,1,0.146,1,0
        - 0,0,0,0.735,0.322,0.398,0.361,0
    detect:
      width: 2560
      height: 1440
      fps: 10
    objects:
      filters:
        car:
          min_score: 0.8
          min_area: 200000
      track:
        - car
        - license_plate
      mask:
        - 0.746,0,0.352,0,0.331,0.114,0.532,0.109,0.98,0.989,1,0.497,1,0.146,1,0
        - 0,0,0,0.735,0.322,0.398,0.361,0
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 8
      required_zones:
        - entry_road_only
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1440
      required_zones:
        - entry_road_only
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 0
        mode: motion
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 1
    zones:
      entry_road_only:
        coordinates: 0.809,0.792,0.312,0.8,0.332,0.524,0.405,0.325,0.582,0.317
        inertia: 3
        loitering_time: 0
        objects: car
        filters:
          car:
            min_score: 0.8
    review:
      alerts:
        required_zones: entry_road_only
      detections:
        required_zones: entry_road_only
  
detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 0
    mode: motion
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
logger:
  default: error
birdseye:
  enabled: false
  layout:
    scaling_factor: 3.0
  mode: continuous

ffmpeg:
  hwaccel_args: preset-nvidia
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic-audio-copy

model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

version: 0.15-1
camera_groups:
  Birdeye_Camera:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
No errors in the log
```

### Relevant go2rtc log output

```shell
No errors in the log
```

### FFprobe output from your camera

```shell
Ran it from the OS, as I didn't login to the container, ut its the same feed (rstp) source.

ffprobe version 4.4.5-0ubuntu1~22.04.sav2 Copyright (c) 2007-2025 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr --extra-version='0ubuntu1~22.04.sav2' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x55a61ef10800] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://192.168.1.xxx:xxxxx/xxxxxxxxxxx':
  Metadata:
    title           : Session streamed by "preview"
    comment         : reolink rtsp stream
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 10 fps, 10 tbr, 90k tbn, 20 tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
xxx@ccc-xxx:/xxxx/dockercompose$
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/frigate/config:/config
      - /share/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxx"
      PLUS_API_KEY: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx:xxxxx"
    #network_mode: host
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink E1 Outdoor (Ethernet connected)

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/2c3913bc-f06e-47ea-b2f9-6eb3aeef1f80)
### Any other information that may be helpful

Below are the relevant masks and zones of the driveway.

![image](https://github.com/user-attachments/assets/f6280ee3-f7d8-494d-b61e-3431d09556f5)
