### DISCUSSION TITLE
[Config Support]: Update not taking effect?

### DISCUSSION THREAD

**Discussion by templeowls21** [blakeblackshear/frigate#17959] [Config Support] [answered]
### Describe the problem you are having

I'm running Frigate via docker and docker compose via Portainer. I wanted to update to 0.15.1.

So I updated my compose file (see below). However, the update is not being reflected in my frigate UI or frigate integration in HA. Both still say I'm 0.15.0. Did I miss a step? First time updating so I prolly did something stupid

![image](https://github.com/user-attachments/assets/d087fc07-fa2a-4198-b350-5fc0d3502111)

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: [ip address]
  port: 1883
  user: [username]
  password: [password]
  topic_prefix: frigate

go2rtc:
  streams:
    Driveway:
      - rtsp://admin:admin@192.168.207.2:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://admin:admin@192.168.207.2:554/cam/realmonitor?channel=1&subtype=1
    FrontPorch:
      - rtsp://admin:admin@192.168.207.3:554/cam/realmonitor?channel=1&subtype=0
    FrontPorch_sub:
      - rtsp://admin:admin@192.168.207.3:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.107.3:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  FrontPorch:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://192.168.107.3:8554/FrontPorch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontPorch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3
        mode: active_objects
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    objects:
      track:
        - person
        - dog
        - cat
        - bear
      filters:
        person:
          min_score: 0.7
        dog:
          min_score: 0.7
        cat:
          min_score: 0.7
        bear:
          min_score: 0.7
  Driveway:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3
        mode: active_objects
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.7
version: 0.15-1
```

### Relevant Frigate log output

```shell
can include if needed. no visible errors
```

### Relevant go2rtc log output

```shell
can include if needed. no visible errors
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/frigate:/config
      - /media/user/T7:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Object Detector

Coral
