### DISCUSSION TITLE
[Detector Support]: Another USB Coral Getting Stuck

### DISCUSSION THREAD

**Discussion by ianwood** [blakeblackshear/frigate#17957] [Detector Support]
Like some others have seen with the Coral USB, I am seeing intermittent issues where detection gets stuck and restarts along with a series of USB related messages. The Coral was used on another system with no issue so I don't think it is a bad unit, has thermal issues or has a bad cable. 

This is on a Beelink S12Pro (N100) which has 4 USB3.2 ports. The system where the Coral was used prior with no issue was a J3160 system with USB3.0. 

Note that I am also using USB for Frigate media storage (a 512GB mSATA via SATAIII USB adapter). With only two cameras, there shouldn't be a bandwidth issue. 

The events occur at random. Sometimes none for hours. Then three back to back at 5:39am Nothing I can identify correlates with that time. 

I did have a prior issue with the Coral on the Beelink S12Pro where the Coral would simply stop working after a while. I had both it and the mSATA USB adapter plugged into the the two rear ports. When I moved the Coral to one of the front USB while leaving the external SATA on the back the issue went away. I assume this was a power issue. 

Other information: 
In Proxmox, I am passing USB ports to the Docker VM, not USB IDs.
Using SR-IOV vGPU for i915 passing a single GPU instance to the Docker VM (required iHD graphics for Frigate). 
Proxmox is 8.4.1
Docker VM kernel is 6.12.12+bpo-amd64. 

dmesg docker VM:
```
[26259.798785] xhci_hcd 0000:07:1b.0: ERROR Transfer event TRB DMA ptr not part of current TD ep_index 2 comp_code 1
[26259.798847] xhci_hcd 0000:07:1b.0: Looking for event-dma 0000000101ab2880 trb-start 0000000101ab2810 trb-end 0000000101ab2810 seg-start 0000000101ab2000 seg-end 0000000101ab2ff0
[26262.805619] usb 8-2: reset SuperSpeed USB device number 3 using xhci_hcd
[26262.822557] usb 8-2: LPM exit latency is zeroed, disabling LPM.
```

dmesg Proxmox host:
```
[31901.963069] usb 2-1: reset SuperSpeed USB device number 3 using xhci_hcd
[31901.975329] usb 2-1: LPM exit latency is zeroed, disabling LPM.
```
lsusb -tvv docker VM:
```
/:  Bus 08.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/15p, 5000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/usb8  /dev/bus/usb/008/001
    |__ Port 1: Dev 2, If 0, Class=Mass Storage, Driver=uas, 5000M
        ID 174c:55aa ASMedia Technology Inc. ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge, ASM1153E SATA 6Gb/s bridge
        /sys/bus/usb/devices/8-1  /dev/bus/usb/008/002
    |__ Port 2: Dev 3, If 0, Class=Vendor Specific Class, Driver=usbfs, 5000M
        ID 18d1:9302 Google Inc. 
        /sys/bus/usb/devices/8-2  /dev/bus/usb/008/003
```
lsusb -tvv Proxmox host:
```
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    /sys/bus/usb/devices/usb2  /dev/bus/usb/002/001
    |__ Port 1: Dev 4, If 0, Class=Vendor Specific Class, Driver=usbfs, 5000M
        ID 18d1:9302 Google Inc. 
        /sys/bus/usb/devices/2-1  /dev/bus/usb/002/004
    |__ Port 3: Dev 3, If 0, Class=Mass Storage, Driver=usbfs, 5000M
        ID 174c:55aa ASMedia Technology Inc. ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge, ASM1153E SATA 6Gb/s bridge
        /sys/bus/usb/devices/2-3  /dev/bus/usb/002/003
```

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: [removed]
  user: [removed]
  password: [removed]

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    front-detect:
      - rtsp://[removed]:[removed]@[removed]/H264/ch1/sub/av_stream#backchannel=0
    front-record:
      - rtsp://[removed]:[removed]@[removed]/channels/101#backchannel=0
    rear-detect:
      - rtsp://[removed]:[removed]@[removed]/channels/102#backchannel=0
    rear-record:
      - rtsp://[removed]:[removed]@[removed]/channels/101#backchannel=0
  webrtc:
    candidates:
      - [removed]:8555
      - stun:8555

birdseye:
  enabled: true
  mode: objects

model:
  path: [removed]

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  quality: 85

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  alerts:
    retain:
      days: 5
  detections:
    retain:
      days: 5
audio:
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - emergency_vehicle
    - police_car
    - fire_engine
    - explosion
    - gunshot
    - fireworks
    - firecracker
    - shatter
    - helicopter

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:8554/front-detect
          roles:
            - detect
            - audio
        - path: rtsp://[removed]:8554/front-record
          roles:
            - record
    detect:
      width: 1920
      height: 540
      fps: 6
      annotation_offset: -900
    motion:
      mask: 
        0.696,0.059,0.499,0,0.35,0.072,0.189,0.28,0.21,0.454,0.174,0.5,0.234,0.993,0.192,0.993,0.128,0.572,0.065,0.68,0.04,0.993,0,0.993,0,0,1,0,1,0.557
    zones:
      porch:
        coordinates: 67,536,615,536,408,416,222,312,123,363
      frontyard:
        coordinates: 0.765,0.38,0.353,0.33,0.224,0.563,0.246,0.757,0.41,1,1,0.993
        inertia: 3
        loitering_time: 0
      street:
        coordinates: 
          0.699,0.09,0.501,0.024,0.351,0.088,0.191,0.287,0.213,0.493,0.317,0.31,0.503,0.304,0.668,0.337
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - dog
        - cat
        - fedex
        - ups
        - amazon
      filters:
        person:
          threshold: 0.80
          min_score: 0.60
          min_area: 1000
          max_area: 125000
        dog:
          threshold: 0.75
          min_score: 0.55
        cat:
          threshold: 0.75
          min_score: 0.55
        fedex:
          threshold: 0.65
        ups:
          threshold: 0.65
        amazon:
          threshold: 0.65

    review:
      alerts:
        required_zones:
          - frontyard
          - porch
      detections:
        required_zones: street

  rear:
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:8554/rear-detect
          roles:
            - detect
            - audio
        - path: rtsp://[removed]:8554/rear-record
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
      annotation_offset: -900
    motion:
      mask:
        - 1280,318,1045,146,1026,84,982,80,980,0,1280,0
        - 0,0,0,296,373,181,960,179,955,0
        - 1245,683,1245,705,895,705,895,683
    zones:
      backyard:
        coordinates: 1142,329,1280,720,56,720,0,633,0,410,333,254,974,299,971,196,1047,202
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.85
          min_score: 0.65
          min_area: 3000
          max_area: 50000
        dog:
          threshold: 0.80
          min_score: 0.60
        cat:
          threshold: 0.80
          min_score: 0.60
    review:
      alerts:
        required_zones: backyard
version: 0.15-1
semantic_search:
  enabled: false
  reindex: true
  model_size: small
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nvr/frigate/config:/config
      - /mnt/nvr/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" # go2rtc
    environment:
      FRIGATE_RTSP_PASSWORD: "[removed]"
      PLUS_API_KEY: [removed]
```

### Relevant Frigate log output

```shell
2025-04-29 05:39:15.275377535  [2025-04-29 05:39:15] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2025-04-29 05:39:15.275435866  [2025-04-29 05:39:15] root                           INFO    : Waiting for detection process to exit gracefully...
2025-04-29 05:39:22.451651647  127.0.0.1 - - [29/Apr/2025:05:39:22 -0700] "" 400 0 "-" "-" "-"
2025-04-29 05:39:45.295235069  [2025-04-29 05:39:45] root                           INFO    : Detection process didn't exit. Force killing...
2025-04-29 05:39:45.305259626  2025/04/29 05:39:45 [error] 163#163: *12743 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001/version", host: "127.0.0.1:5000"
2025-04-29 05:39:45.305969656  [2025-04-29 05:39:45] root                           INFO    : Detection process has exited...
2025-04-29 05:39:45.341367611  [2025-04-29 05:39:45] detector.coral                 INFO    : Starting detection process: 46643
2025-04-29 05:39:48.103164010  [2025-04-29 05:39:45] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-04-29 05:39:48.106851298  [2025-04-29 05:39:48] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Install method

Proxmox via Docker

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/6ff2a68f-7d90-48f8-8bbe-d0c027a05478" />
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/2180437b-fec6-478b-8fa7-f52272446726" />
Note: running SR-IOV vGPU passthrough which I understand does not support the current method of retrieving GPU stats.
