### DISCUSSION TITLE
Retention configuration

### DISCUSSION THREAD

**Discussion by beginner2047** [blakeblackshear/frigate#17976] [Config Support] [answered]
### Describe the problem you are having

I have the following configuration for retention and only this part contain retain day

![image](https://github.com/user-attachments/assets/09b4ef5a-a0f3-42ef-a9a0-ae4a03dc4d63)

Due to nearly disk full on my nas, I found that most detect / alert / snapshot and object are kept in my storage

![image](https://github.com/user-attachments/assets/9a211b59-ddf3-4c9b-8d62-88a85849d378)

The earlist date is 20 Apr 2025. 

How can i remove those record?

### Version

frigate:stable 

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 5
  detections:
    retain:
      days: 5

snapshots:
  enabled: True
  retain:
    default: 5
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 60s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb"
    devices:
      - /dev/apex_0:/dev/apex_0  
      - /dev/apex_1:/dev/apex_1 
      - /dev/dri:/dev/dri  
    env_file: .env
    environment:
      TZ: Europe/London
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"

    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/frigate/config:/config
      - /mnt/media/frigate:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 8000000000
    ports:
      - "5000:5000"   
      - "8554:8554"   
      - "8555:8555/tcp" 
      - "8555:8555/udp"
    networks:
      - frigate_net
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  frigate_net:
    driver: bridge
```

### Object Detector

Coral

**Comment by NickM-27** [comment]
are you sure these settings are changed at the global level? it seems like this might be a case where one camera has a different configuration which is using the default 10 days retention

**Reply by beginner2047** [reply]
It should be global setting but I have two cameras which defined 10 days retention for snapshot in order to keep the image without video (i hope so). 

```
    snapshots:
      retain:
        default: 10
          person: 10
```

Will it affect all cameras? or will it keep the video too?

**Reply by beginner2047** [reply]
I have changed all retain day for detech/alert/snaphot to 3 days and restart frigate. May I know when the frigate will remove those records from DB and file system?

**Reply by NickM-27** [reply]
typically after a minute the cleanup will run for all things. The best way to get help is to paste your entire current configuration

**Reply by beginner2047** [reply]
Here is updated to 3 days config

```
mqtt:
  enabled: true
  host: <MANUALLY_REMOVED>
  user: <MANUALLY_REMOVED>
  password: <MANUALLY_REMOVED>

detect:
  enabled: true

record:
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 3
  detections:
    retain:
      days: 3

snapshots:
  enabled: True
  retain:
    default: 3

motion:
  threshold: 45
  contour_area: 10
  improve_contrast: true

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  path: default
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: auto
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-copy
  retry_interval: 10

go2rtc:
  streams:
    garage_camera: rtsp://<MANUALLY_REMOVED>:8554/unicast
    doorbell_camera:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_01_main
    doorbell_camera_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_01_sub
    gate_camera:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_01_main
    gate_camera_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_01_sub
    gate_camera_2:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_02_main
    gate_camera_2_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_02_sub
    garden_main_camera:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/h264Preview_01_main
    garden_main_camera_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/h264Preview_01_sub
    garden_left_camera:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_01_main
    garden_left_camera_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_01_sub
    garden_right_camera:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_02_main
    garden_right_camera_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/Preview_02_sub
    driveway_camera:
      - rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/h264Preview_01_main
    driveway_camera_sub:
      rtsp://<MANUALLY_REMOVED>:<MANUALLY_REMOVED>@<MANUALLY_REMOVED>:554/h264Preview_01_sub

cameras:
  garage_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_camera
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      fps: 10
      width: 1920
      height: 1080
    objects:
      track:
        - person
    motion:
      mask: 0.002,0,0.094,0,0.095,0.028,0,0.031
  doorbell_camera:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    zones:
      Driveway:
        coordinates:
          0.457,0.57,0.632,0.61,0.69,0.61,0.931,0.624,0.98,0.614,0.955,0.822,0.895,0.996,0.003,0.999,0.007,0.389,0.013,0.286,0.214,0.341,0.219,0.719
        loitering_time: 0
    motion:
      mask: 0.002,0,0.998,0.006,0.998,0.479,0.662,0.48,0.006,0.285
    review:
      alerts:
        required_zones: Driveway
      detections:
        required_zones: Driveway
    detect:
      max_disappeared: 50
      fps: 10
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.6 
          threshold: 0.75
        car:
          min_score: 0.6
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 175
      retain:
        default: 3
        objects:
          person: 3
      quality: 100
  gate_camera:
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0.582,0.009,0.582,0.081,0.994,0.084,0.995,0
        - 0.513,0.249,0.516,0.343,0.251,0.327,0.251,0.267
    zones:
      Carport:
        coordinates: 0,0,0.25,0.182,0.247,0.342,0.524,0.354,0.519,0.183,1,0.241,1,1,0,1
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones: Carport
      detections:
        required_zones: Carport
    detect:
      fps: 10
      width: 896
      height: 512
    live:
      height: 512
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.6  # Confidence threshold (default is 0.5)
          threshold: 0.75  # Motion threshold (lower is more sensitive)
        car:
          min_score: 0.6
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 175
      retain:
        default: 3
        objects:
          person: 3
      quality: 70
  gate_camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gate_camera_2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_camera_2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
    live:
      height: 512
    motion:
      mask: 0.002,0,0.002,0.138,0.55,0.224,0.553,0.084,0.997,0.081,0.995,0.007
  garden_main_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_main_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_main_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Garden:
        coordinates:
          0.001,0.693,0.133,0.467,0.269,0.406,0.298,0.284,0.297,0.006,0.992,0.003,0.986,0.99,0.003,0.993
        loitering_time: 0
    motion:
      mask:
        - 0.75,0.007,0.746,0.064,0.993,0.07,0.997,0.007
        - 0.001,0.002,0.003,0.681,0.131,0.458,0.266,0.393,0.296,0.279,0.289,0.009
    review:
      alerts:
        required_zones: Garden
      detections:
        required_zones: Garden
    detect:
      fps: 5
      width: 1536
      height: 576
    live:
      height: 576
    objects:
      track:
        - person
        - bird
        - cat
        - dog
  garden_left_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_left_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_left_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Garden:
        coordinates:
          0,0.402,0.424,0.387,0.435,0.341,0.534,0.34,0.539,0.356,0.782,0.247,0.783,0.137,1,0.13,1,1,0,1
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.818,0.01,0.819,0.073,0.997,0.081,0.997,0.003
    review:
      alerts:
        required_zones: Garden
      detections:
        required_zones: Garden
    detect:
      fps: 5
      width: 896
      height: 512
    live:
      height: 512
    objects:
      track:
        - person
        - bird
        - cat
        - dog
      filters:
        person:
          min_score: 0.6  # Confidence threshold (default is 0.5)
          threshold: 0.75  # Motion threshold (lower is more sensitive)
        car:
          min_score: 0.6

    onvif:
      host: <MANUALLY_REMOVED>
      port: 8000
      user: '<MANUALLY_REMOVED>'
      password: '<MANUALLY_REMOVED>'
  garden_right_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_right_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_right_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: false
    live:
      height: 512
    onvif:
      host: <MANUALLY_REMOVED>
      port: 8000
      user: '<MANUALLY_REMOVED>'
      password: '<MANUALLY_REMOVED>'
    motion:
      mask:
        0.002,0.003,0.001,0.189,0.289,0.209,0.288,0.09,0.563,0.091,0.568,0.148,0.999,0.07,0.999,0.005
  driveway_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Driveway:
        coordinates:
          0,0.509,0.035,0.679,0.184,0.384,0.231,0.526,0.34,0.165,0.515,0.164,0.733,0.291,0.918,0.773,1,0.572,1,1,0,1
        loitering_time: 0
        inertia: 3
    motion:
      mask:
        - 0.66,0,0.689,0.254,0.912,0.801,1,0.545,0.998,0.004
        - 0.85,0.754,0.909,0.959,0.998,0.799,1,0.53
        - 0.474,0.101,0.521,0.099,0.524,0.145,0.475,0.147
        - 0,0.485,0.36,0.081,0.491,0.07,0.601,0.132,0.68,0.193,0.659,0,0,0
    review:
      alerts:
        required_zones: Driveway
      detections:
        required_zones: Driveway
    detect:
      fps: 10
      width: 1536
      height: 576
    live:
      height: 576
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.6
          threshold: 0.75 
        car:
          min_score: 0.6

database:
  path: /config/frigate.db
version: 0.15-1

```
