### DISCUSSION TITLE
[Config Support]: 1 of 2 cameras does not detect when using plus model

### DISCUSSION THREAD

**Discussion by ayostepht** [blakeblackshear/frigate#17972] [Config Support]
### Describe the problem you are having

My camera "backyard" does not detect any objects when I use my tuned plus model. It detects motion appropriately; however know object detections, recordings, or snapshots are ever made. On the other hand, the front-door camera works perfectly fine. As I've been troubleshooting, I decided to remove the plus model from my config (that is why it is commented out below), and when I did that (and changed nothing else at all), the object detection began working correctly again. 

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.0.115:5000/api/config/schema.json

mqtt:
  enabled: true
  host: 192.168.0.111
  port: 1883
  user: xxx
  password: xxx

# model:
#   path: plus://d4cf35a7dd2b8a65d15e091d5155ee6c

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  crop: true
  retain:
    default: 10

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: 
            rtsp://xxx:yyy@192.168.0.218:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi

    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: true
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7

    objects:
      track:
        - bird
        - cat
        - squirrel
        - deer
      filters:
        bird:
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
        squirrel:
          min_score: 0.5
          threshold: 0.7
        deer:
          min_score: 0.5
          threshold: 0.7

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 
        0,0.003,0.998,0,0.998,0.443,1,1,0.678,1,0.787,0.709,0.761,0.681,0.745,0.517,0.651,0.515,0.66,0.712,0.624,0.741,0.643,0.785,0.677,0.802,0.772,0.785,0.678,0.997,0.274,0.999,0.286,0.831,0.371,0.905,0.539,0.905,0.544,0.844,0.516,0.761,0.291,0.754,0.278,1,0.232,1,0.131,1,0,1,0,0.346,0,0.086,0.387,0.249,0.341,0.617,0.41,0.629,0.42,0.426,0.418,0.285,0,0.111
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    review:
      alerts:
        labels:
          - bird
          - squirrel
          - raccoon

  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.0.107:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac

    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5


    record:
      enabled: true
      detections:
        retain:
          days: 1

    objects:
      track:
        - person
        - face
        - dog
        - cat
        - car
        - amazon
        - usps
        - fedex
        - ups
        - license_plate
        - deer
        - raccoon
        - squirrel
        - package
        - waste_bin
      filters:
        person:
          mask:
            - 0.423,0.413,0.42,0.506,0.454,0.506,0.451,0.424
            - 0.567,0.484,0.567,0.535,0.596,0.523,0.589,0.475
            - 0.677,0.484,0.684,0.548,0.722,0.56,0.718,0.48
            - 0.742,0.518,0.742,0.556,0.754,0.554,0.756,0.516
            - 0.361,0.518,0.345,0.613,0.392,0.624,0.388,0.532
      mask: 0.404,0.516,0.438,0.64,0.386,0.632

    motion:
      mask: 
        0,0.667,0,0.289,0,0,0.17,0,1,0,1,1,0.822,0.9,0.738,0.906,0.654,0.856,0.61,0.82,0.514,0.636,0.449,0.636,0.459,0.856,0.374,1,0,1

    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    review:
      alerts:
        labels:
          - car
          - person
          - package
          - usps
          - amazon
        required_zones:
          - atdoor

    zones:
      driveway:
        coordinates: 0.758,0.653,0.769,0.62,0.803,0.56,0.899,0.566,0.998,0.612,0.997,0.708
        inertia: 3
        loitering_time: 10
        objects: car

      curb:
        coordinates: 0.468,0.51,0.461,0.611,0.65,0.634,0.647,0.56
        loitering_time: 30
        objects: waste_bin
        inertia: 3

      atdoor:
        coordinates: 0.243,0.607,0.671,0.659,0.997,0.999,0.002,0.997
        loitering_time: 0
        objects:
          - package
          - person
          - usps
          - fedex
          - amazon
        inertia: 3

      street:
        coordinates: 0.011,0.372,0,0.497,1,0.692,1,0.567
        loitering_time: 10
        objects:
          - usps
          - car
          - fedex
          - amazon
        inertia: 3
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='bridge'
  --pids-limit 2048
  --privileged=true
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='xxxx'
  -e 'PLUS_API_KEY'='xxxx'
  -e 'LIBVA_DRIVER_NAME'='iHD'
  -e 'NVIDIA_VISIBLE_DEVICES'=''
  -e 'NVIDIA_DRIVER_CAPABILITIES'=''
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '5001:5000/tcp'
  -p '8554:8554/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -p '1984:1984/tcp'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/user/frigate/':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/bus/usb'
  --device='/dev/dri/renderD128'
  --shm-size=256mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable'
81e03faa7af7f45fd7fe8affd91a258aac902dda24347053d08ecb79ec0355c3
```

### Object Detector

Coral
