### DISCUSSION TITLE
Generative AI with ollama is not working

### DISCUSSION THREAD

**Discussion by Gaute2000** [blakeblackshear/frigate#17985] [Ask A Question]
Hi all,

Im a bit new to this Generative AI. But I have been running Frigate NVR for some years with some up`s and down`s.
Recently I wanted to try this Generative AI and Semantic Search. But the problem is that I dont get it to work probably. 
When I go to the "explore" section, then to the camera that have this enable. Its nothing in the description. When I click "regenerate from Snapshot/Thumbnails" many times it show up a text in the description. And I see that the load on the ollama server goes up. When I go an trigger the camera I see that my ollama server load go up as well, without getting any description text.

On the ollama I have only setup it up and installed the correct model (llava:7b), not else except from that.

Here is part of my config.

```
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral1:
    type: edgetpu
    device: usb:0
semantic_search:
  enabled: true
  reindex: false
  model_size: large
genai:
  enabled: true
  provider: ollama
  base_url: http://x.x.x.x:30068
  model: llava:7b
  prompt: Analyze the {label} in these images from the {camera} security camera. Focus
    on the actions, behavior, and potential intent of the {label}, rather than just
    describing its appearance.
  object_prompts:
    person: Examine the main person in these images. What are they doing and what
      might their actions suggest about their intent (e.g., approaching a door, leaving
      an area, standing still)? Do not describe the surroundings or static details.
    car: Observe the primary vehicle in these images. Focus on its movement, direction,
      or purpose (e.g., parking, approaching, circling). If it's a delivery vehicle,
      mention the company.
    cat: Observe the cat in these images. Focus on its movement and intent (e.g.,
      wandering, hunting, interacting with objects). If the cat is near the flower
      pots or engaging in any specific actions, mention it.

cameras:
  hovedinngang_2etg:
    genai:
      enabled: true
      use_snapshot: true
      objects:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@x.x.x.x:554/live1s1.sdp
          roles:
            - detect
            - rtmp
            - record
```
Any idea what could be wrong, and where to start troubleshooting?
