### DISCUSSION TITLE
Frigate crashed regularly - reconnect coral

### DISCUSSION THREAD

**Discussion by avunculo** [blakeblackshear/frigate#17982] [Ask A Question]
Good morning,
I use Frigate 0.15 on my Proxmox as Docker in Portainer. 
The system crashes regularly. I have already increased the ram to 8gb. I then have to reconnect coral usb. It is particularly annoying when I am on the road and have no physical contact with my system. 
The tmp cache frigate also fills up regularly. Is it worth outsourcing to the nas? Attached are my latest reports and frigate config. 
google coral connect on usb 3.0. i changed the usb cable. I use a a Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz processor 
 Can anyone help me?

```
mqtt:
  enabled: true
  host: ip
  user: user
  password: pw
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  restream: true
  mode: objects
objects:
  track:
    - person
    - cat
    - dog
    - bicycle
cameras:
  Eingang:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://user:pw@ip1:554/H264/ch3/main/av_stream
          roles:
            - record
        - path: rtsp://user:pw@ip1:554/H264/ch2/sub/av_stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    zones: {}
    objects: {}
    review: {}
  carport:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://user:pw@ip2:554/H264/ch3/main/av_stream
          roles:
            - record
        - path: rtsp://user:pw@ip2:554/H264/ch2/sub/av_stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
  carport_hwr:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://user:pw@ip3:554/H264/ch3/main/av_stream
          roles:
            - record
        - path: rtsp://user:pw@ip3:554/H264/ch2/sub/av_stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      mask: 0.028,0.052,0.316,0.044,0.31,0.082,0.02,0.079
  Garten:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://user:pw@ip4:554/H264/ch3/main/av_stream
          roles:
            - record
        - path: rtsp://user:pw@ip4:554/H264/ch2/sub/av_stream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    onvif:
      host: ip
      port: 80
      user: user
      password: pw
camera_groups:
  Eingang:
    order: 1
    icon: LuDoorClosed
    cameras:
      - Eingang
      - carport
version: 0.15-1
```
[frigate-logs.txt](https://github.com/user-attachments/files/19997624/frigate-logs.txt)

<img width="1371" alt="Bildschirmfoto 2025-05-01 um 09 19 47" src="https://github.com/user-attachments/assets/80333df2-058e-422a-a406-2d55ddcefeb8" />

<img width="480" alt="Bildschirmfoto 2025-05-01 um 09 21 03" src="https://github.com/user-attachments/assets/63e836ce-4efb-47ee-938a-0d4d0fa39525" />
