### DISCUSSION TITLE
[Support]: Really long reviews soaking up all events due to a parked car

### DISCUSSION THREAD

**Discussion by darnmason** [blakeblackshear/frigate#17980] [General Support] [answered]
### Describe the problem you are having

I've been suffering with this issue for a while, since the time of the 0.15 update, I don't think I noticed it before the update but can't say for certain if it was pre-existing. All I know is that in recent weeks it's a daily occurrence.

We park our car on the street in front of our house, so it's usually our car, while it's parked there all events that occur are merged into a single monster review item. Multiple comings and goings from my house that should trigger different alerts, due to zones being entered by people, are buried in this single review item that can span days. So I lose all granularity of alerts.

Using the Explore tab I can see all objects detected during this period, and the object lifecycle shows that the zones are being entered, so that all looks correct.

I looked at one review item with the issue.

- Hitting the API I can see the start and end time makes the duration over 12 hours.
- The response includes over 130 detections.
- Running these event IDs through a script I found one of a car with duration 11:59:01.

I can see now it's occurring again since I parked the car this morning.
- The review has no end time, the start time is 3 hours ago.
- It already includes 28 detections.
- One of which has no end time.
- Looking at the debug view I can see the car sitting there, there's some shadows from foliage on it but otherwise really clear, fine grey bounding box I understand indicates it's known to be stationary.
- It's breezy out, there's motion detected elsewhere in the frame, however the green region boxes seem to take up the whole frame.
- I can see sometimes the bounding box blinks bold blue, with periods of 10s over a minute as grey.
- I understand that reviews are designed to merge multiple events, but shouldn't count stationary objects? But if the event never ends then the review item will never end.
- So what are the criteria for this event to end?
- And what can I do to debug further?

Here's the car in Debug view:
![Screenshot 2025-05-01 at 12 57 07](https://github.com/user-attachments/assets/70a09227-b79b-4396-b704-4f71716fb38f)

Here's the current event API response:
```json
{
    "id": "1746056627.82945-mspq8h",
    "label": "car",
    "sub_label": null,
    "camera": "entrance",
    "start_time": 1746056627.82945,
    "end_time": null,
    "false_positive": null,
    "zones": [
        "kerb"
    ],
    "thumbnail": "...",
    "has_clip": true,
    "has_snapshot": true,
    "retain_indefinitely": false,
    "plus_id": null,
    "model_hash": "5fe41895782729507d4d4ad39cb8c84f",
    "detector_type": "edgetpu",
    "model_type": "ssd",
    "data": {
        "box": [
            0.3148148148148148,
            0.20416666666666666,
            0.3055555555555556,
            0.2722222222222222
        ],
        "region": [
            0.18518518518518517,
            0.0,
            0.4888888888888889,
            0.7333333333333333
        ],
        "score": 0.984375,
        "top_score": 0.99609375,
        "attributes": [],
        "type": "object",
        "max_severity": "detection"
    }
}
```

Config included below, removed 4 unnecessary cameras.
I've gone through some changes recently, not making any difference to the issue:
- At some point in the past I had tweaked the stationary threshold as I was getting too many alerts when people stood still briefly, I removed that so now it's using defaults.
- I was using substream on the camera but it's only 640x480 so I recently updated to scale the main stream down to 720, to see if detection improves in some scenarios.

### Version

0.15.0-6cb5cfb (0.15.1)

### What browser(s) are you using?

Chrome

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.5
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

tls:
  enabled: false

auth:
  session_length: 2592000 # 30 days
  refresh_time: 864000 # 10 days

ffmpeg:
  hwaccel_args: preset-vaapi

semantic_search:
  enabled: true
  model_size: small

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://5fe41895782729507d4d4ad39cb8c84f

detect:
  enabled: true

record:
  enabled: true
  retain:
    days: 28
    mode: motion
  alerts:
    retain:
      days: 56
      mode: active_objects
  detections:
    retain:
      days: 28
      mode: active_objects

snapshots:
  enabled: true
  retain:
    default: 28
    objects:
      person: 56
      waste_bin: 1

# car, person, motorcycle, bicycle, cat, dog, package, waste_bin
# crying, cough, groa, yell, scream, speech, fart
objects:
  filters:
    car:
      min_area: 1500
      min_score: .65
      threshold: .85
    person:
      min_area: 800
      min_score: .65
      threshold: .85
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    face:
      min_score: .7
    package:
      min_score: .65
      threshold: .9
    license_plate:
      min_score: .6

go2rtc:
  rtsp:
    username: '{FRIGATE_RESTREAM_USER}'
    password: '{FRIGATE_RESTREAM_PASSWORD}'
  streams:
    entrance:
      - rtsp://{FRIGATE_HIK_USER}:{FRIGATE_HIK_PASSWORD}@192.168.0.11:{FRIGATE_HIK_PORT}/streaming/channels/101
  webrtc:
    candidates:
      - 192.168.0.8:8555
      - stun:8555

cameras:

  # --- Entrance Camera --- #
  entrance:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    webui_url: http://192.168.0.11/doc/page/config.asp
    detect: # scale down main stream (3072x2048) 20fps
      width: 1080
      height: 720
      fps: 5
      annotation_offset: -950
    objects:
      track:
        - person
        - car
        - package
        - dog
        - cat
        - motorcycle
        - bicycle
    review:
      alerts:
        labels:
          - person
          - package
        required_zones: steps
    motion:
      mask:
        - 0.041,0.053,0.042,0.077,0.333,0.077,0.333,0.052
        - 0.725,0.884,0.826,0.889,0.827,0.91,0.725,0.91
        - 0,0,0,0.205,0.097,0.153,0.215,0.118,0.347,0.098,0.926,0.115,0.712,0
      threshold: 30
      contour_area: 20
      improve_contrast: true
    zones:
      steps:
        coordinates: 0.927,0.606,0.671,0.875,0.71,1,1,1,1,0.631
        inertia: 1
        loitering_time: 0
        objects:
          - person
          - package
      grass:
        coordinates: 0.969,0.423,0.894,0.365,0.457,0.468,0,0.606,0,0.818,0.48,0.664
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - package
          - dog
          - cat
      path:
        coordinates: 0.954,0.435,0.5,0.67,0,0.839,0,1,0.257,1,0.706,0.798,0.922,0.586
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - package
          - dog
          - cat
      kerb:
        coordinates: 0.76,0.416,0.725,0.351,0.624,0.328,0,0.484,0,0.658
        inertia: 3
        loitering_time: 5
        objects:
          - car
          - person
          - package
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":3072,"height":2048,"display_aspect_ratio":"3:2","avg_frame_rate":"15/1"}]}}]
```

### Frigate stats

```json
{
    "cameras": {
        "garage": {
            "camera_fps": 5.0,
            "process_fps": 5.1,
            "skipped_fps": 0.0,
            "detection_fps": 13.7,
            "detection_enabled": true,
            "pid": 457,
            "capture_pid": 497,
            "ffmpeg_pid": 501,
            "audio_rms": 0.0,
            "audio_dBFS": 0.0
        },
        "entrance": {
            "camera_fps": 5.0,
            "process_fps": 5.0,
            "skipped_fps": 0.0,
            "detection_fps": 4.9,
            "detection_enabled": true,
            "pid": 465,
            "capture_pid": 500,
            "ffmpeg_pid": 504,
            "audio_rms": 0.0,
            "audio_dBFS": 0.0
        },
        "corner": {
            "camera_fps": 5.1,
            "process_fps": 5.0,
            "skipped_fps": 0.0,
            "detection_fps": 3.3,
            "detection_enabled": true,
            "pid": 473,
            "capture_pid": 506,
            "ffmpeg_pid": 513,
            "audio_rms": 0.0,
            "audio_dBFS": 0.0
        },
        "garden": {
            "camera_fps": 6.0,
            "process_fps": 6.0,
            "skipped_fps": 0.0,
            "detection_fps": 0.1,
            "detection_enabled": true,
            "pid": 481,
            "capture_pid": 510,
            "ffmpeg_pid": 515,
            "audio_rms": 0.0,
            "audio_dBFS": 0.0
        },
        "monitor": {
            "camera_fps": 5.1,
            "process_fps": 5.0,
            "skipped_fps": 0.0,
            "detection_fps": 0.0,
            "detection_enabled": false,
            "pid": 489,
            "capture_pid": 514,
            "ffmpeg_pid": 525,
            "audio_rms": 52.8876,
            "audio_dBFS": -55.8419
        }
    },
    "detectors": {
        "coral": {
            "inference_speed": 6.08,
            "detection_start": 0.0,
            "pid": 376
        }
    },
    "detection_fps": 22.0,
    "gpu_usages": {
        "error-gpu": {
            "gpu": "",
            "mem": ""
        }
    },
    "cpu_usages": {
        "frigate.full_system": {
            "cpu": "23.1",
            "mem": "79.8"
        },
        "1": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
        },
        "15": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise s6-linux-init-shutdownd"
        },
        "16": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
        },
        "24": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise nginx-log"
        },
        "25": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise frigate-log"
        },
        "26": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise certsync"
        },
        "27": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise s6rc-fdholder"
        },
        "28": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise go2rtc-healthcheck"
        },
        "29": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise nginx"
        },
        "30": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise frigate"
        },
        "31": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise certsync-log"
        },
        "32": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise s6rc-oneshot-runner"
        },
        "33": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise go2rtc"
        },
        "34": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-supervise go2rtc-log"
        },
        "45": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
        },
        "46": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
        },
        "83": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
        },
        "84": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
        },
        "88": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
        },
        "95": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
        },
        "98": {
            "cpu": "11.5",
            "cpu_average": "10",
            "mem": "0.2",
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
        },
        "114": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "bash ./run.user go2rtc-healthcheck"
        },
        "123": {
            "cpu": "3.5",
            "cpu_average": "4",
            "mem": "9.0",
            "cmdline": "python3 -u -m frigate"
        },
        "133": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "nginx: master process nginx"
        },
        "160": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "nginx: worker process"
        },
        "193": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "nginx: worker process"
        },
        "194": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "nginx: worker process"
        },
        "195": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "nginx: worker process"
        },
        "198": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "nginx: cache manager process"
        },
        "311": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "bash ./run.user certsync"
        },
        "360": {
            "cpu": "3.1",
            "cpu_average": "3",
            "mem": "1.0",
            "cmdline": "frigate.recording_manager"
        },
        "369": {
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "frigate.review_segment_manager"
        },
        "376": {
            "cpu": "7.5",
            "cpu_average": "2",
            "mem": "0.5",
            "cmdline": "frigate.detector.coral"
        },
        "381": {
            "cpu": "0.1",
            "cpu_average": "1",
            "mem": "2.7",
            "cmdline": "frigate.embeddings_manager"
        },
        "401": {
            "cpu": "3.5",
            "cpu_average": "2",
            "mem": "0.6",
            "cmdline": "frigate.output       "
        },
        "407": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -threads 1 -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "414": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -threads 1 -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "421": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1080x720 -i pipe: -threads 1 -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "428": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 720x480 -i pipe: -threads 1 -f mpegts -s 1080x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "435": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
        },
        "457": {
            "cpu": "7.8",
            "cpu_average": "1",
            "mem": "0.9",
            "cmdline": "frigate.process:garage"
        },
        "465": {
            "cpu": "4.6",
            "cpu_average": "2",
            "mem": "0.9",
            "cmdline": "frigate.process:entrance"
        },
        "473": {
            "cpu": "4.4",
            "cpu_average": "2",
            "mem": "0.9",
            "cmdline": "frigate.process:corner"
        },
        "481": {
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.6",
            "cmdline": "frigate.process:garden"
        },
        "489": {
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.6",
            "cmdline": "frigate.process:monitor"
        },
        "497": {
            "cpu": "0.9",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "frigate.capture:garage"
        },
        "500": {
            "cpu": "1.2",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "frigate.capture:entrance"
        },
        "501": {
            "cpu": "2.8",
            "cpu_average": "2",
            "mem": "0.4",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garage -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "504": {
            "cpu": "3.5",
            "cpu_average": "2",
            "mem": "0.4",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/entrance -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/entrance@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "506": {
            "cpu": "1.1",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "frigate.capture:corner"
        },
        "510": {
            "cpu": "0.5",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "frigate.capture:garden"
        },
        "513": {
            "cpu": "3.5",
            "cpu_average": "3",
            "mem": "0.4",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/corner -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/corner@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=1080:h=720,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "514": {
            "cpu": "0.3",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "frigate.capture:monitor"
        },
        "515": {
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.2",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden_sub -r 6 -vf fps=6,scale_vaapi=w=720:h=480,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "518": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5",
            "cmdline": "python3 -u -m frigate"
        },
        "525": {
            "cpu": "1.0",
            "cpu_average": "0",
            "mem": "0.2",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/monitor_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
        },
        "538": {
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/monitor_sub -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:"
        },
        "540": {
            "cpu": "0.6",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4"
        },
        "541": {
            "cpu": "0.2",
            "cpu_average": "0",
            "mem": "0.1",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp:127.0.0.1:8554/monitor -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/monitor@%Y%m%d%H%M%S%z.mp4"
        },
        "552": {
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.0",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/monitor_sub?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/7cb7fc66b4f49f6d4e1eb28d28941342"
        },
        "557": {
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.0",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/monitor?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/c6e563ba51f85d608d42e81c0b9a2c4d"
        },
        "160187": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "sleep 9999"
        },
        "172586": {
            "cpu": "0.0",
            "cpu_average": "1",
            "mem": "0.4",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -y -protocol_whitelist pipe,file -f concat -safe 0 -i /tmp/cache/playlist_entrance_1746012126.737649-1746055268.01257.txt -c copy -movflags frag_keyframe+empty_moov -f mp4 pipe:"
        },
        "172656": {
            "cpu": "0.0",
            "cpu_average": "1",
            "mem": "0.4",
            "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -y -protocol_whitelist pipe,file -f concat -safe 0 -i /tmp/cache/playlist_entrance_1746012126.737649-1746055268.01257.txt -c copy -movflags frag_keyframe+empty_moov -f mp4 pipe:"
        },
        "177240": {
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0",
            "cmdline": "sleep 30s"
        }
    },
    "service": {
        "uptime": 54814,
        "version": "0.15.0-6cb5cfb",
        "latest_version": "0.15.1",
        "storage": {
            "/media/frigate/recordings": {
                "total": 2815556.2,
                "used": 2000154.3,
                "free": 672306.5,
                "mount_type": "ext4"
            },
            "/media/frigate/clips": {
                "total": 2815556.2,
                "used": 2000154.3,
                "free": 672306.5,
                "mount_type": "ext4"
            },
            "/tmp/cache": {
                "total": 953.7,
                "used": 123.3,
                "free": 830.4,
                "mount_type": "tmpfs"
            },
            "/dev/shm": {
                "total": 128.0,
                "used": 57.0,
                "free": 71.0,
                "mount_type": "tmpfs"
            }
        },
        "temperatures": {},
        "last_updated": 1746066938
    },
    "processes": {
        "recording": {
            "pid": 360
        },
        "review_segment": {
            "pid": 369
        },
        "go2rtc": {
            "pid": 98
        },
        "embeddings": {
            "pid": 381
        },
        "audio_detector": {
            "pid": 518
        }
    }
}
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    group_add:
      - "107"  # stat -c '%g' /dev/dri/renderD128
      - "10000" # lxc_shares
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    cap_add:
      - CAP_PERFMON
    shm_size: "128mb"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /mnt/cctv:/media/frigate
      - /opt/frigate/logs:/dev/shm/logs
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Necessary for home assistant
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984" # go2rtc web interface
    environment:
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision DS-2CD2355FWD-I

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-05-01 at 12 41 20](https://github.com/user-attachments/assets/ca1f3ea5-6953-48d6-9c68-8eefccc01867)
