### DISCUSSION TITLE
[Detector Support]: Developing a detector plugin

### DISCUSSION THREAD

**Discussion by swdee** [blakeblackshear/frigate#17983] [Detector Support] [answered]
### Describe the problem you are having

I am wanting to develop a detector plugin for the Orion O6 to make use of its NPU.   Before doing any integration with the NPU, my first goal is to purely hook into Frigates detector plugin system.

I have created file `detectors/plugins/oriono6.py` with contents;
```
import logging
from typing import Literal

from frigate.detectors.detection_api import DetectionApi
from frigate.detectors.detector_config import BaseDetectorConfig

logger = logging.getLogger(__name__)

DETECTOR_KEY = "oriono6"


class OrionO6DetectorConfig(BaseDetectorConfig):
    type: Literal[DETECTOR_KEY]


class OrionO6(DetectionApi):
    type_key = DETECTOR_KEY

    def __init__(self, config: OrionO6DetectorConfig):
        super().__init__(config)
        self.height = config.model.height
        self.width = config.model.width
        model_path = config.model.path
        self.model_type = config.model.model_type
        logger.info("OrionO6 Init called, config: %s", config.model_dump_json(indent=2))

    # tensor_input is a H×W×C BGR frame?
    def detect_raw(self, tensor_input):
        # raise RuntimeError("🚨 detect_raw() called")
        logger.info(
            "OrionO6 detect_raw called with type=%s, dtype=%s, shape=%s",
            type(tensor_input),
            tensor_input.dtype,
            tensor_input.shape,
        )
```

Then I connect to the shell of the dev container and start frigate with;
```
python3 -m frigate
```

As frigate starts I can see in the log output that the plugin's init() call has been triggered;
```
[2025-05-01 16:34:03] detector.orion                 INFO    : Starting detection process: 17946
[2025-05-01 16:34:03] frigate.detectors.plugins.oriono6 INFO    : OrionO6 Init called, config: {
  "type": "oriono6",
  "model": {
    "path": "/config/model_cache/oriono6/yolov8_l.cix",
    "labelmap_path": "/labelmap/coco-80.txt",
    "width": 640,
    "height": 640,
    "labelmap": {},
    "attributes_map": {
      "person": [
        "amazon",
        "face"
      ],
      "car": [
        "amazon",
        "an_post",
        "dhl",
        "dpd",
        "fedex",
        "gls",
        "license_plate",
        "nzpost",
        "postnl",
        "postnord",
        "purolator",
        "ups",
        "usps"
      ],
      "motorcycle": [
        "license_plate"
      ]
    },
    "input_tensor": "nhwc",
    "input_pixel_format": "bgr",
    "input_dtype": "int",
    "model_type": "yolo-generic"
  },
  "model_path": null
}
[2025-05-01 16:34:03] frigate.comms.mqtt             DEBUG   : MQTT connected
```

However I don't see any logging output for calls made to `detect_raw()`, meaning this function is not being called so detection is not working.

What am I missing with the plugin hooks/configuration?

### Version

0.16.0-a9f139e0

### Frigate config file

```yaml
mqtt:
  host: mqtt

logger:
  default: debug
    
detectors:
  orion:
    type: oriono6

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: bgr
  input_dtype: int
  model_type: yolo-generic
  labelmap_path: /labelmap/coco-80.txt
  path: /config/model_cache/oriono6/yolov8_l.cix

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/palace.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720      
      fps: 5
      enabled: true        

version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
Using the default devcontainer.json setup running Frigate in a Dev Container via VS Code.
```

### Relevant Frigate log output

```shell
As above.
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

n/a
