### DISCUSSION TITLE
[Config Support]: How to configure record buffer before and after an object detection ?

### DISCUSSION THREAD

**Discussion by iparout** [blakeblackshear/frigate#17994] [Config Support]
### Describe the problem you are having

Hi.

I am using Frigate 0.15-1 and unfortunately frigate cuts every recording a few seconds BEFORE the tracked object exits the camera's view.

What is the correct configuration in order for frigate to keep the recording from 10 seconds before an object enters the view up until 10 seconds after an object exits the view ?

The camera is a TP-Link Tapo C510W, if it matters.

Thanks a lot !

### Version

0.15-1

### Frigate config file

```yaml
Tapo C510W:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://XXXXXX/stream1
          roles:
            - record
        - path: rtsp://xxxxxx/stream2
          roles:
            - detect
    detect:
      height: 720
      width: 1280
      fps: 25
    record:
      enabled: true
      retain:
        days: 30
        mode: active_objects
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 30
    objects:
      track:
        - person
        - car
```

### Relevant Frigate log output

```shell
none relevant
```

### Relevant go2rtc log output

```shell
none relevant
```

### Operating system

Home Assistant OS

### Install method

Proxmox via TTeck Script

### docker-compose file or Docker CLI command

```yaml
none relevant
```

### Object Detector

OpenVino
