### DISCUSSION TITLE
[Support]: Getting an mqtt detection message but nothing in web gui

### DISCUSSION THREAD

**Discussion by bug2k19** [blakeblackshear/frigate#17998] [General Support]
### Describe the problem you are having

I have frigate+, mosquitto is configured to pick up messages from frigate+ and a python script running to pick up these messages and forward an email including a snapshot of any events.
I have received a few detection notifications via mqtt none of which are shown in the web gui?
These happen to be false positives, but a detection event of a 'person' should be shown in the web gui.
Where would I start looking to find out why this is happening?

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

135.0.7049.114

### Frigate config file

```yaml
model:
  path: plus://<model_id>

mqtt:
  enabled: true
  host: <IP>
  port: 1883
  user: username
  password: password
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 30
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
cameras:
  CAMERA1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://username:password@<IP>:554/Streaming/channels/102
          roles:
            - detect
        - path: rtsp://username:password@<IP>:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: true

    zones:
      CAMERA1_detect:
        coordinates: 0,0.79,0,0.607,0.11,0.539,0.386,0.39,0.657,0.271,0.801,0.17,1,0.206,1,1,0.062,1
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0.025,0.022,0.313,0.021,0.315,0.061,0.025,0.065
        - 0.829,0.947,0.97,0.947,0.97,0.987,0.83,0.984
        - 0,0.302,0.11,0.23,0.145,0.274,0.15,0.465,0.064,0.531,0.056,0.505,0,0.561
    review:
      alerts:
        required_zones: CAMERA1_detect
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
  CAMERA2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://username:password@<IP>:554/Streaming/channels/102
          roles:
            - detect
        - path: rtsp://username:password@<IP>:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: true
    zones:
      CAMERA2_zone:
        coordinates: 
          0,0.938,0.18,0.734,0.507,0.408,0.698,0.213,0.753,0.166,0.82,0.13,0.901,0.08,0.893,0,1,0,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: CAMERA2_zone
    motion:
      mask:
        - 0.828,0.946,0.97,0.946,0.969,0.988,0.829,0.99
        - 0.022,0.02,0.313,0.017,0.312,0.059,0.024,0.061
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
version: 0.15-1
```

### Relevant Frigate log output

```shell
#
```

### Relevant go2rtc log output

```shell
#
```

### FFprobe output from your camera

```shell
#
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
#
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision
