### DISCUSSION TITLE
Detect CPU Usage over 500%

### DISCUSSION THREAD

**Discussion by NexGen-3D-Printing** [blakeblackshear/frigate#17995] [Ask A Question] [answered]
Not sure if this is expected behaviour, but the Frigate PWA reports over 500%+ detect CPU usage, mainly on a camera that is extremely active, but the actual system CPU is never higher than 30%

I'm running a A310 GPU with Yola-NAS under Openvino and all seems to be working, I have under 20ms detect time, I have 20 CPU cores allocated to Frigate, there is no errors in the log, everything is running perfectly, just this warning, and I really think its reporting incorrectly, possibly its using 100% of 5 to 6 CPU cores??

The camera over looks a busy intersection with cars and people triggering it on a steady basis at certain times of the day, and I have seen this warning hit figures as high as 680%.

There is no ram issues either, I have allocated 16GB of ram and 2048 SHM Ram, throwing more resources at it, doesn't fix anything either.

Image below is what I'm referring too:
![Screenshot 2025-05-02 055228](https://github.com/user-attachments/assets/190f4e6c-5d66-4dbd-8db0-90cd076a7820)

This is the system stats:
![Screenshot 2025-05-02 055421](https://github.com/user-attachments/assets/561d9ce7-4b39-47ac-8124-7327e2c66be3)

**Comment by hawkeye217** [comment]
We can't help without seeing your config.

**Reply by NexGen-3D-Printing** [reply]
Sorry:
```
cameras:
  Front-Yard-1:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Yard-1_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front-Yard-1
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Front-Yard-1_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.004,0.009,0.174,0.017,0.201,0.308,0.203,0.321,0.128,0.352,0.103,0.32,0.008,0.321
        - 0.564,0.008,0.995,0.013,0.996,0.668,0.954,0.709,0.93,0.698,0.892,0.661,0.867,0.641,0.848,0.598,0.828,0.482,0.833,0.424,0.845,0.35,0.854,0.315,0.84,0.291,0.811,0.271,0.776,0.265,0.757,0.274,0.754,0.3,0.745,0.358,0.747,0.414,0.736,0.435,0.703,0.428,0.718,0.369,0.717,0.322,0.699,0.274,0.566,0.116
    zones:
      Window:
        coordinates: 0.181,0.014,0.394,0.009,0.393,0.162,0.251,0.708
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
      Front_Entry:
        coordinates: 
          0.455,0.003,0.559,0.007,0.561,0.115,0.602,0.172,0.659,0.235,0.695,0.276,0.71,0.319,0.714,0.368,0.709,0.4,0.697,0.428,0.717,0.444,0.737,0.442,0.751,0.422,0.748,0.366,0.754,0.315,0.762,0.29,0.785,0.275,0.825,0.283,0.84,0.301,0.845,0.325,0.83,0.381,0.823,0.435,0.822,0.483,0.829,0.538,0.838,0.593,0.86,0.649,0.883,0.67,0.913,0.694,0.923,0.717,0.922,0.771,0.915,0.808,0.898,0.849,0.879,0.905,0.882,0.936,0.903,0.917,0.92,0.87,0.938,0.808,0.953,0.725,0.969,0.692,0.984,0.667,0.999,0.689,0.998,0.994,0.004,0.993,0.003,0.333,0.067,0.32,0.102,0.327,0.12,0.368,0.166,0.353,0.2,0.337,0.243,0.716,0.256,0.702,0.399,0.163,0.402,0.009
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
  Front-Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Door_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front-Door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    live:
      stream_name: Front-Door_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.009,0.02,0.148,0.027,0.175,0.067,0.194,0.182,0.206,0.16,0.239,0.172,0.233,0.221,0.239,0.24,0.262,0.232,0.292,0.236,0.334,0.244,0.356,0.273,0.368,0.298,0.394,0.341,0.407,0.401,0.402,0.419,0.403,0.441,0.422,0.454,0.441,0.483,0.42,0.519,0.381,0.528,0.355,0.544,0.328,0.563,0.294,0.559,0.269,0.541,0.26,0.5,0.248,0.481,0.235,0.473,0.222,0.468,0.197,0.453,0.214,0.423,0.21,0.401,0.203,0.39,0.191,0.396,0.183,0.424,0.171,0.464,0.152,0.489,0.101,0.513,0.054,0.535,0.023,0.552,0.004,0.557
        - 0.003,0.006,0.198,0.009,0.195,0.026,0.007,0.027
        - 0.452,0.387,0.461,0.385,0.479,0.382,0.492,0.383,0.5,0.389,0.513,0.406,0.519,0.428,0.514,0.45,0.503,0.466,0.491,0.474,0.476,0.474,0.466,0.468,0.455,0.458,0.442,0.443,0.44,0.421,0.447,0.403
        - 0.576,0.461,0.566,0.462,0.558,0.47,0.55,0.477,0.541,0.485,0.535,0.494,0.53,0.513,0.533,0.526,0.536,0.543,0.54,0.552,0.547,0.561,0.558,0.569,0.567,0.567,0.573,0.563
        - 0.039,0.992,0.061,0.969,0.067,0.96,0.094,0.938,0.124,0.918,0.149,0.903,0.169,0.929,0.165,0.953,0.167,0.967,0.218,0.97,0.263,0.98,0.279,0.995
    zones:
      Front_Door:
        coordinates: 0.002,0.004,0.995,0.006,0.998,0.993,0.004,0.997
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
  Front-Yard-2:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Yard-2_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front-Yard-2
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Front-Yard-2_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion: {}
  Pool-Area:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Pool-Area_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Pool-Area
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Pool-Area_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion: {}
  Patio:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Patio_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Patio
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Patio_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true
  Side-Area-1:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Side-Area-1_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Side-Area-1
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Side-Area-1_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion: {}
  Side-Area-2:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Side-Area-2_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Side-Area-2
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Side-Area-2_sub
    detect:
      width: 848
      height: 480
      fps: 5
    motion: {}
  Backyard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Backyard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Backyard_sub
    detect:
      width: 848
      height: 480
      fps: 5
  Roundabout:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Roundabout_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Roundabout
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: Roundabout_sub
    detect:
      width: 1280
      height: 720
      fps: 10

    zones:
      Intersection:
        coordinates: 0.001,0.002,0.002,0.997,0.997,0.995,0.999,0.007
        loitering_time: 0
        objects:

          - person
          - car
        inertia: 3
    onvif:
      host: 192.168.0.196
      port: 80
      user: admin
      password: FuckYou123
      tls_insecure: true
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        # Optional: calibrate the camera on startup (default: shown below)
        # A calibration will move the PTZ in increments and measure the time it takes to move.
        # The results are used to help estimate the position of tracked objects after a camera move.
        # Frigate will update your config file automatically after a calibration with
        # a "movement_weights" entry for the camera. You should then set calibrate_on_startup to False.
        calibrate_on_startup: false
        # Optional: the mode to use for zooming in/out on objects during autotracking. (default: shown below)
        # Available options are: disabled, absolute, and relative
        #   disabled - don't zoom in/out on autotracked objects, use pan/tilt only
        #   absolute - use absolute zooming (supported by most PTZ capable cameras)
        #   relative - use relative zooming (not supported on all PTZs, but makes concurrent pan/tilt/zoom movements)
        zooming: absolute
        # Optional: A value to change the behavior of zooming on autotracked objects. (default: shown below)
        # A lower value will keep more of the scene in view around a tracked object.
        # A higher value will zoom in more on a tracked object, but Frigate may lose tracking more quickly.
        # The value should be between 0.1 and 0.75
        track:
          - person
          #- car
        # Required: Begin automatically tracking an object when it enters any of the listed zones.
        required_zones:
          - Intersection
        # Required: Name of ONVIF preset in camera's firmware to return to when tracking is over. (default: shown below)
        return_preset: Home
        # Optional: Seconds to delay before returning to preset. (default: shown below)
        timeout: 5

        movement_weights: 0.25, 1.0, 1.9325408935546875, 1.7771518543202383, 0.505798205252617
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: true

detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU

#model:
  #width: 300
  #height: 300
  #input_tensor: nhwc
  #input_pixel_format: bgr
  #path: /openvino-model/ssdlite_mobilenet_v2.xml
  #labelmap_path: /openvino-model/coco_91cl_bkgr.txt

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

objects:
  track:
    - person
    - car
    - cat
    - dog

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: false
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14

birdseye:
  enabled: true
  restream: true
  width: 1920
  height: 1080
  quality: 1
  mode: continuous
  layout:
    max_cameras: 9

version: 0.15-1

camera_groups:
  Main_View:
    order: 15
    icon: LuAirplay
    cameras:
      - Backyard
      - Front-Yard-1
      - Front-Yard-2
      - Patio
      - Pool-Area
      - Roundabout
      - Side-Area-1
      - Side-Area-2
      - Front-Door
  Overview:
    order: 2
    icon: LuBird
    cameras: birdseye
semantic_search:
  enabled: false
  reindex: false
  model_size: small
```
