### DISCUSSION TITLE
Light flashing causing superfluous alerts

### DISCUSSION THREAD

**Discussion by rea-ducks** [blakeblackshear/frigate#17991] [Ask A Question]
On our frontyard we're having a night light. Every minute it goes off so its ambient light sensor can see if it's still dark and if it is, the light switches back on. This takes only a blink of an eye but the frontyard camera (5 fps) still sees it (I  and often (but by far not always) creates an alert seemingly recognizing our car standing there as a new object.

So each night there's a bunch of unnecessary cars in the alerts list. I already have a "lightning_threshold: 0.4" in the config which lowered the number of alerts. But a) I don't want to lower it even more because it could then miss real motions as I b) already have the hunch the current value is the reason it sometimes misses the paper boy in the dawn on this camera.

Any idea on what else I could do?

Config:
```
detectors:
  ov:
    type: openvino
    device: GPU
model:
  model_type: yolonas
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nchw
  path: /models/yolo_nas_s_320.onnx
  labelmap_path: /models/coco-80.txt
go2rtc:
  streams:
    HD:
      - rtsp://user:password@192.168.80.14:554/Streaming/channels/101
    SD:
      - rtsp://user:password@192.168.80.14:554/Streaming/channels/102
  webrtc:
    candidates:
      - 192.168.80.15:8555
      - stun:8555
cameras:
  FrontEye:
    live:
      stream_name: ANKSD
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/HD
          roles:
            - record
          input_args: preset-rtsp-restream
        - path: rtsp://127.0.0.1:8554/SD
          roles:
            - detect
          input_args: preset-rtsp-restream
      hwaccel_args: preset-intel-qsv-h264
    detect:
      enabled: true
    motion:
      lightning_threshold: 0.4
    zones:
      porch:
        coordinates: 
          858,281,642,50,570,48,669,315,757,536,906,536,1153,323,1131,255,1084,295,1026,280,986,246
        objects:
          - person
      parking_area:
        coordinates: 0.721,1,0.821,0.782,0.706,0.507,0.533,0.103,0.312,0.146,0.029,0.763,0.152,1
        objects:
          - person
          - car
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        car:
          min_area: 1000
          mask:
            - 0.977,0.493,0.973,0.586,0.738,1,0.826,0.767,0.713,0.522,0.525,0.08,0.73,0,0.783,0.09
            - 0.033,0.666,0.003,0.594,0.003,0.005,0.299,0.005,0.302,0.097
        person:
          min_area: 1000
          mask:
            - 1058,158,918,219,947,262,855,280,655,62,783,60,871,0,940,48
            - 0.033,0.666,0.003,0.594,0.003,0.005,0.299,0.005,0.302,0.097
      track:
        - person
        - face 
        - car
    review:
      alerts:
        required_zones:
          - parking_area
          - porch
    snapshots:
      required_zones:
        - parking_area
        - porch
birdseye:
  enabled: true
  mode: continuous
snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 3
record:
  enabled: true
  retain:
    days: 1
    mode: active_objects
  alerts:
    retain:
      days: 2
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 2
    pre_capture: 15
    post_capture: 15
database:
  path: /db/frigate.db
version: 0.15-1
```
