### DISCUSSION TITLE
USB disk is very hot - Frigate on pure Debian image

### DISCUSSION THREAD

**Discussion by gamer06** [blakeblackshear/frigate#18008] [Ask A Question]
Hello everybody,
Here's the thing, I use a nuc i3 for the frigate, only on pure debian. And I have an m.2 ssd disk connected via usb (with its own aluminum case) just for frigate recordings.
I had to do some commands, namely "mount" to mount the USB disk to a folder, and direct it to a folder/path. Like: "sudo mount /dev/sdb1 /media/usb1tb/".
Also change the "/etc/fstab" file.
But like this, it has some high temperatures. Is it normal? the disk box itself almost burns when touched, it's really hot.

P.S: I remember that, when I was trying to get my entire system working, I also tried installing Frigate in a VM in Proxmox, using passthrough from the USB disk only for recordings, and it didn't heat up as much as it does now.

![20250503_111609](https://github.com/user-attachments/assets/d276de40-b83e-496e-a2b2-09161a5265ab)
![image](https://github.com/user-attachments/assets/23a8a06c-a760-4f3b-96b5-1bc2da84dddf)
![image](https://github.com/user-attachments/assets/fcb3b3c9-6465-44b4-a04b-3ea91a6d7264)

Thanks

**Comment by hawkeye217** [comment]
This is a question more suited to your drive manufacturer. What is your frigate config and docker compose?

**Reply by gamer06** [reply]
> This is a question more suited to your drive manufacturer. What is your frigate config and docker compose?

my frigate conifg:

```
mqtt:
  enabled: true
  host: IP
  user: USER
  password: PASS

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  rtsp:
    username: USER
    password: PASS
  streams:
    hall:
      - rtsp://USER:PASS@IP:554/stream1#timeout=30
      - ffmpeg:hall#audio=aac#audio=opus
    hall_sub:
      - rtsp://USER:PASS@IP:554/stream2#timeout=30
      - ffmpeg:hall_sub#audio=aac#audio=opus

    aoqee_1:
      - rtsp://thinginoUSER:thinginoPASS@IP:554/ch0
    aoqee_1_sub:
      - rtsp://thinginoUSER:thinginoPASS@IP:554/ch1

    aoqee_2:
      - rtsp://thinginoUSER:thinginoPASS@IP:554/ch0
    aoqee_2_sub:
      - rtsp://thinginoUSER:thinginoPASS@IP:554/ch1

    video_doorbell_1:
      - ffmpeg:#input=-timeout 15000000 -i rtsp://thinginoUSER:thinginoPASS@IP:554/ch0#video=h264#rotate=90

cameras:

  hall:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/hall
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/hall_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat

  aoqee_1:
    enabled: false
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/aoqee_1
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/aoqee_1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car

  aoqee_2:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/aoqee_2
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/aoqee_2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car

  video_doorbell_1:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/video_doorbell_1?timeout=15
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio

    detect:
      enabled: true
      width: 426
      height: 240

audio:
  enabled: false

motion:
  enabled: true
  threshold: 20
  contour_area: 10

record:
  enabled: true

  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 15
      mode: motion
    pre_capture: 15
    post_capture: 20
  detections:
    retain:
      days: 15
      mode: motion
    pre_capture: 15
    post_capture: 20
snapshots:
  enabled: true
  retain:
    default: 15

version: 0.15-1
```
 
and docker compose:

```
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    cap_add:
      - CAP_PERFMON
    shm_size: "357mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/card0
      - /dev/dri/renderD128
    volumes:
      - ./config:/config
      - /media/usb1tb/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "5000:5000"
```
