### DISCUSSION TITLE
[Bug]: openvino_telemetry references and sends telemetry to Google Analytics by default

### DISCUSSION THREAD

**Discussion by SkyGolem** [blakeblackshear/frigate#18013] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

openvino_telemetry references and sends telemetry to Google Analytics by default
This is not expected for an opensource solution.

The frigate container includes the Python package openvino_telemetry, and it contains code that sends telemetry to Google Analytics by default, specifically:
backend_url = 'https://www.google-analytics.com/collect'
and
self.backend_url = "https://www.google-analytics.com/mp/collect?measurement_id={}&api_secret={}"
These are standard GA endpoints used for client- and server-side tracking.

Frigate uses OpenVINO as one of its supported acceleration backends (particularly for Intel hardware). Unfortunately, the openvino_telemetry module is part of the official OpenVINO distribution from Intel — and it defaults to enabling telemetry, including Google Analytics tracking.
This is not Frigate’s fault, but a side effect of OpenVINO's packaging, however this privacy issue should be mitigated.

Attempting to Disable OpenVINO Telemetry at Runtime as per their ?? Official ref: 
https://docs.openvino.ai/2025/about-openvino/additional-resources/telemetry.html
to try and disable OpenVINO’s built-in telemetry, is not respected by the openvino_telemetry Python package bundled in the Frigate image, i.e. 
Setting the following environment variable in your Docker container:
```
    environment:
      - OV_TF_DISABLE_TELEMETRY=1
```

### Steps to reproduce

### Example: Using a vanilla install of the docker container on Ubuntu 24.04.2 LTS Server minimised, with the google-analytics output shown directly after being composed:
```
user1@frigate:~$ mkdir frigate
user1@frigate:~$ cd  frigate/
user1@frigate:~/frigate$ docker compose up -d
[+] Running 8/8
 ? frigate Pulled                                                                                                                                                                                                                                                       398.6s
   ? b983e127c643 Pull complete                                                                                                                                                                                                                                          19.4s
   ? 9561d7da5b61 Pull complete                                                                                                                                                                                                                                         367.4s
   ? 1e09f9dc7e03 Pull complete                                                                                                                                                                                                                                         396.1s
   ? 856cb1708827 Pull complete                                                                                                                                                                                                                                         397.2s
   ? 90ffa7e70cd3 Pull complete                                                                                                                                                                                                                                         397.3s
   ? 6c2bf1d6b5e4 Pull complete                                                                                                                                                                                                                                         397.3s
   ? 98aba4877af2 Pull complete                                                                                                                                                                                                                                         397.7s
[+] Running 2/2
 ? Network frigate_default  Created                                                                                                                                                                                                                                       0.1s
 ? Container frigate        Started                                                                                                                                                                                                                                       1.2s
user1@frigate:~/frigate$ docker exec -it frigate grep -r "google-analytics" /usr/
/usr/local/lib/python3.9/dist-packages/openvino_telemetry/backend/backend_ga4.py:        self.backend_url = "https://www.google-analytics.com/mp/collect?measurement_id={}&api_secret={}".format(
/usr/local/lib/python3.9/dist-packages/openvino_telemetry/backend/backend_ga.py:    backend_url = 'https://www.google-analytics.com/collect'
grep: /usr/local/lib/python3.9/dist-packages/openvino_telemetry/backend/__pycache__/backend_ga4.cpython-39.pyc: binary file matches
grep: /usr/local/lib/python3.9/dist-packages/openvino_telemetry/backend/__pycache__/backend_ga.cpython-39.pyc: binary file matches
```

### Version

0.15.0-6cb5cfb

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 30

snapshots:
  enabled: true
  retain:
    default: 14

detectors:
  cpu1:
    type: cpu

objects:
  track:
    - person
    - dog
    - cat

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.201:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5

  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.202:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
version: 0.15-1
```


### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/dri:/dev/dri  # VAAPI device for AMD
    ports:
      - "5000:5000"  # Web UI
      - "8554:8554"  # RTSP restream
      - "1935:1935"  # Live stream
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /media/frigate:/media/frigate
```


### Relevant Frigate log output

```shell
N/A
```


### Relevant go2rtc log output

```shell
N/A
```


### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

All

### Screenshots of the Frigate UI's System metrics pages

N/A

### Any other information that may be helpful

Suggested Fix:
Strip the OpenVINO Telemetry Package from your standard Frigate docker images, removing the telemetry package.

Dockerfile:
```
# Base image from Frigate
FROM ghcr.io/blakeblackshear/frigate:stable

# Remove openvino-telemetry (and any cached .pyc)
RUN pip uninstall -y openvino-telemetry && \
    find /usr/local/lib/python3.9/ -name '*openvino_telemetry*' -exec rm -rf {} + && \
    find /usr/local/lib/python3.9/ -name '*.pyc' -exec rm -f {} +
```
