### DISCUSSION TITLE
[Bug]: Single core NPU Rockchip doesnt display NPU stats

### DISCUSSION THREAD

**Discussion by GDCAU** [blakeblackshear/frigate#18011] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

The recent update to support displaying NPU stats for Rockchip only works on NPU's with multiple cores such as the 358x. The single NPU core 356x fails.

This is due to this line https://github.com/blakeblackshear/frigate/blob/5c3ac75c315136ce5b6305af5ebd0b8a08ad50d2/frigate/util/services.py#L411
which is designed for the 3 core Rockchip 3588.

For example the current code is based on the file being formatted like:
```
sudo cat /sys/kernel/debug/rknpu/load
NPU load:  Core0:  0%, Core1:  0%, Core2:  0%,
```

Whereas the Rockchip 3566 has the file format like:
```
sudo cat /sys/kernel/debug/rknpu/load
NPU load:  9%
```

Modifying https://github.com/blakeblackshear/frigate/blob/5c3ac75c315136ce5b6305af5ebd0b8a08ad50d2/frigate/util/services.py#L411
to:
`core_loads = re.findall(r"NPU load:\s+(\d+)%", npu_output)`
works fine on the single core NPU Rockchip.

### Steps to reproduce

Find a rk356x based board, confirm the NPU stats do not display.
Modify the line above in the code
Run again and see that NPU stats display fine.

### Version

0.16.0-beta1-rk

### In which browser(s) are you experiencing the issue with?

Chrome 135.0.7049.115

### Frigate config file

```yaml
Dont judge my config, its been hacked around during 0.16 testing so its a bit of a mess....

mqtt:
  enabled: false
#  host: mqtt.server.com


ffmpeg:
  hwaccel_args: -hwaccel_device /dev/dri/renderD128 -hwaccel_device /dev/dri/renderD129
  #hwaccel_args: preset-rk-h264 #h264_rkmpp
cameras:
  Frontdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://user:pass@camera.domain.com:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 8
      min_initialized: 1
    record:
      enabled: true
      retain:
        days: 1
        mode: active_objects
    lpr:
      enabled: false
    zones:
      Frontdoor_Camera:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - cat
          - dog
          - person
          - bird
          - car
          - backpack
          - handbag
          - suitcase
          - motorcycle
          - bicycle
          - package
          - face
          - licence_plate
    review:
      alerts:
        required_zones: Frontdoor_Camera
      detections:
        required_zones: Frontdoor_Camera
    motion:
      mask: 0.762,0.951,0.761,0.996,1,1,1,0.951
      threshold: 45
      contour_area: 10
      improve_contrast: true
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://user:pass@camera.domain.com:554/cam/realmonitor?channel=3&subtype=2
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 8
      min_initialized: 1
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
    zones:
      Driveway_Camera:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - cat
          - dog
          - person
          - bird
          - car
          - backpack
          - handbag
          - suitcase
          - motorcycle
          - bicycle
          - package
          - face
          - licence_plate
    review:
      alerts:
        required_zones: Driveway_Camera
      detections:
        required_zones: Driveway_Camera
    motion:
      mask:
        - 0.753,0.943,0.751,1,1,1,1,0.942
        - 0.32,0.989,0.453,0.627,0.449,0.305,0.006,0.15,0.004,0.998
  Backdeck:
    enabled: false
    ffmpeg:
      inputs:
        - path: 
            rtsp://user:pass@camera.domain.com:554/cam/realmonitor?channel=4&subtype=2
          roles:
            - detect
            - record
    lpr:
      enabled: false
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
    zones:
      Backdeck_Camera:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
        objects:
          - car
          - cat
          - dog
          - person
          - bird
          - car
          - backpack
          - handbag
          - suitcase
          - motorcycle
          - bicycle
          - package
          - face
    review:
      alerts:
        required_zones: Backdeck_Camera
      detections:
        required_zones: Backdeck_Camera
    motion:
      mask: 0.745,0.952,0.747,1,1,1,1,0.945

      threshold: 45
      contour_area: 10
      improve_contrast: true
detectors:
  rknn0:
    type: rknn
  rknn1:
    type: rknn

review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person
      - bird
      - car
      - backpack
      - handbag
      - suitcase
      - motorcycle
      - bicycle
      - package
      - face
      - licence_plate

objects:
  track:
    - car
    - cat
    - dog
    - person
    - bird
    - car
    - backpack
    - handbag
    - suitcase
    - motorcycle
    - bicycle
    - package
    - face
    - licence_plate

detect:
  enabled: true

model:
  path: frigate-fp16-yolov9-t
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nhwc
  input_dtype: float
  labelmap_path: /labelmap/coco-80.txt

#model:
#  path: deci-fp16-yolonas_s
#  model_type: yolonas
#  width: 320
#  height: 320
#  input_pixel_format: bgr
#  input_tensor: nhwc
#  labelmap_path: /labelmap/coco-80.txt
semantic_search:
  enabled: false
  reindex: false
  model_size: large
telemetry:
  network_interfaces:
    - eth0
  stats:
    network_bandwidth: true

lpr:
  device: GPU
  enabled: true
  known_plates:
    Ford:
      - 'abc-xyz'
    BMW:
      - A-aaa-A


face_recognition:
  enabled: true
  detection_threshold: 0.70
  model_size: small

logger:
  default: info
  logs:
    frigate.data_processing.common.license_plate: debug

version: 0.16-0
classification:
  bird:
    enabled: true
```

### docker-compose file or Docker CLI command

```yaml
#version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta1-rk
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
      - /dev/dri/renderD128
      - /dev/dri/renderD129
      - /dev/dri
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/:/sys/:ro
      - /nvme/config:/config
      - /nvme/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
Nothing in logs
```

### Relevant go2rtc log output

```shell
Dont use go2rtc
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Dahua 5442

### Screenshots of the Frigate UI's System metrics pages

<img width="1224" alt="Screenshot 2025-05-03 at 10 05 57 pm" src="https://github.com/user-attachments/assets/c5562a71-32ac-49f6-b068-60b811a5b0ca" />
