### DISCUSSION TITLE
[Bug]:  [0.16.0‑beta1] Config validator rejects `type: hailo8` (accepts only `hailo8l`)

### DISCUSSION THREAD

**Discussion by MayorBug** [blakeblackshear/frigate#18027] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Versions  
| Item | Value |
|---|---|
| Add‑on | **ccab4aaf_frigate‑fa‑beta (0.16.0‑beta1)** |
| Hardware | Raspberry Pi 5 + Hailo‑8 PCIe (26 TOPS) |
| OS / Supervisor | Home Assistant OS 15.2 / Supervisor 2024.05.0 |

### Bug  
Saving a config that contains:

```yaml
detectors:
  hailo8:
    type: hailo8 # ← rejected
    device: PCIe

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: rgb
  input_dtype: int
  model_type: yolo-generic
  #labelmap_path: /labelmap/coco-80.txt
  path: 
    https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.15.0/hailo8/yolov11m.hef
```

fails with the UI banner:

```
Your configuration is invalid.
Input tag 'hailo8' … does not match any of the expected tags:
'cpu', 'deepstack', 'edgetpu', 'hailo8l', 'onnx', 'openvino', 'rknn', 'tensorrt'
```

If I change the line to `type: hailo8l`, the config validates and Frigate starts, even though the YAML key is still `hailo8:`.

### Expected  
`type: hailo8` should validate for full‑speed Hailo‑8 hardware, or the docs should state that `hailo8l` is the canonical value for both SKUs.

### Notes  
* The issue is cosmetic; `hailo8l` works fine on the full‑speed card.  
* Release notes mention “Hailo‑8 and Hailo‑8L” support, so the schema/docs likely need aligning.

### Minimal config to reproduce  

```yaml
mqtt:
  host: 192.168.1.100      # any broker

detectors:
  hailo8:
    type: hailo8           # validator trips here
    device: PCIe

cameras:
  dummy:
    ffmpeg:
      inputs:
        - path: rtsp://0.0.0.0/stream
          roles: [detect]
    detect:
      width: 640
      height: 360
```

### Version

0.16.0-5c3ac75

### In which browser(s) are you experiencing the issue with?

Chrome 136.0.7103.48

### Frigate config file

```yaml
-
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Network connection

Wired

### Camera make and model

-

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-05-04 102837](https://github.com/user-attachments/assets/365d3092-e995-4de7-a6cb-f54b59008d18)

**Comment by hawkeye217** [comment]
Perhaps the docs could be clarified further, but they do list the same configuration and indicate it is for both the 8 and 8l: https://deploy-preview-16390--frigate-docs.netlify.app/configuration/object_detectors#hailo-8

**Comment by MayorBug** [comment]
Docs do mention both. Docs seprately show what default model variant is used by specific hw, but it doesn't tell if the hw variant is auto detected or if it should be manually defined.

The default config example from docs

```
detectors:
  hailo8l:   #<= accepts hailo8 here
    type: hailo8l.  #<= But does not accept hailo8 here
    device: PCIe

```

Also one note. When I used the default config with my hailo8 and looked at the logs I recall that it said along the lines of: the model "YOLOv6n" was compiled for hailo8l and my hw is not used to the full potential. 


I could help to write improved docs if I knew what the expected usage should look like
