### DISCUSSION TITLE
[Question] Healthcheck endpoint for recordings

### DISCUSSION THREAD

**Discussion by bsacharski** [blakeblackshear/frigate#18028] [Ask A Question]
Hello.

For whatever reason, my frigate instance sometimes won't record camera streams and I end up with some segments where history scrollback reports "No recordings found for this time". Usually, a restart help with that.

Is there any API endpoint which I could query that would return health status of my recordings, so I could automate frigate restart when necessary?

**Comment by mguyard** [comment]
Hello,

I had the same few day ago for one of my cameras.
Restart resolved issue but I've the same question. How monitor programmatically if recording really works ?

**Comment by hawkeye217** [comment]
What is your Frigate config and do you see any errors in the Frigate logs?

**Reply by bsacharski** [reply]
@hawkeye217  Errors in logs:

```text
frigate  | 2025-05-04 08:23:22.764910984  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for garaz. This likely indicates an issue with the detect stream, keeping the 6 mo
st recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.767042130  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for dzwonek. This likely indicates an issue with the detect stream, keeping the 6 
most recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.768147950  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for ogrod. This likely indicates an issue with the detect stream, keeping the 6 mo
st recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.770266503  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for szopa. This likely indicates an issue with the detect stream, keeping the 6 mo
st recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.774517649  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for wschod. This likely indicates an issue with the detect stream, keeping the 6 m
ost recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.776296421  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for drzwi. This likely indicates an issue with the detect stream, keeping the 6 mo
st recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.778523339  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for front. This likely indicates an issue with the detect stream, keeping the 6 mo
st recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 08:23:22.780737315  [2025-05-04 08:23:22] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for zachod. This likely indicates an issue with the detect stream, keeping the 6 m
ost recent segments out of 7 and discarding the rest...
```

Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    wschod:
      - rtsp://login:pass@wschod.cam:554/h264Preview_01_main#audio=opus
      #- ffmpeg:wschod#audio=opus
    wschod_sub:
      # - ffmpeg:http://wschod.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass # 896x512@19fps substream
      - ffmpeg:http://wschod.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass # 640x360@4fps substream

    zachod:
      - rtsp://login:pass@zachod.cam:554/h264Preview_01_main#audio=opus
      # - ffmpeg:zachod#audio=opus
    zachod_sub:
      - ffmpeg:http://zachod.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass

    garaz:
      - rtsp://login:pass@garaz.cam:554/h264Preview_01_main#audio=opus
    garaz_sub:
      - ffmpeg:http://garaz.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass

    front:
      - rtsp://login:pass@front.cam:554/h264Preview_01_main#audio=opus
    front_sub:
      - ffmpeg:http://front.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass

    taras:
      - rtsp://login:pass@taras.cam:554/h264Preview_01_main#audio=opus
    taras_sub:
      - ffmpeg:http://taras.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass

    drzwi:
      - rtsp://login:pass@drzwi.cam:554/h264Preview_01_main#audio=opus
    drzwi_sub:
      - ffmpeg:http://drzwi.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass

    ogrod:
      - rtsp://login:pass@ogrod.cam:554/h264Preview_01_main#audio=opus
    ogrod_sub:
      - ffmpeg:http://ogrod.cam/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=login&password=pass

    garaz_srodek:
      - rtspx://192.168.11.1:7441/REDACTED
    garaz_srodek_sub:
      - rtspx://192.168.11.1:7441/REDACTED

    dzwonek:
      - rtspx://192.168.11.1:7441/REDACTED
    dzwonek_sub:
      - rtspx://192.168.11.1:7441/REDACTED
    szopa:
      - rtspx://192.168.11.1:7441/REDACTED
    szopa_sub:
      - rtspx://192.168.11.1:7441/REDACTED
  webrtc:
    candidates:
      - 192.168.11.116:8555
      - 100.124.73.35:8555
      - stun:8555

cameras:
  wschod:
    ffmpeg:
      inputs:
        #- path: 
        #    http://wschod.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
        #  input_args: preset-http-reolink
        - path: rtsp://127.0.0.1:8554/wschod_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/wschod?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask: 1,0.702,0.521,0.775,0.197,0.78,0,0.763,0,1,1,1
  zachod:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/zachod_sub
          input_args: preset-rtsp-restream
            # http://zachod.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
          # input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/zachod?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
        - 0,0,0,0.07,0.316,0.075,0.314,0.009
        - 0.907,0.009,0.914,0.082,0.997,0.082,0.992,0.005
  garaz:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garaz_sub
          input_args: preset-rtsp-restream
            # http://garaz.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
          # input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garaz?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4
    birdseye:
      mode: continuous
    zones:
      podjazd:
        coordinates: 
          0.263,0.664,0.571,0.651,0.452,0.564,0.438,0.362,0.66,0.35,0.87,0.509,0.994,0.7,0.987,0.988,0.27,1,0.262,0.754
        loitering_time: 0
        inertia: 3
      wejscie_do_garazu:
        coordinates: 0.208,0.117,0.261,0.754,0.266,1,0.199,1,0.123,0.733,0.154,0.502
        loitering_time: 0
    motion:
      mask:
        - 0.004,0.003,0.309,0.005,0.31,0.08,0.003,0.085
        - 0.177,1,0.113,0.732,0.198,0.089,0,0.087,0,1
  garaz_srodek:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garaz_srodek_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garaz_srodek?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    detect:
      width: 640
      height: 360
      fps: 10
    motion:
      mask:
        - 117,22,122,0,0,0,0,21
    objects:
      filters:
        person:
          min_score: 0.75
          threshold: 0.80

  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          #   http://front.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
          # input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4
    birdseye:
      mode: continuous
    zones:
      podjazd:
        coordinates: 0.518,0.425,0.37,0.793,0.086,0.556,0.36,0.235,0.517,0.27
        loitering_time: 0
        inertia: 3
      drzwi_frontowe:
        coordinates: 0.621,0.484,0.625,0.138,0.776,0.132,0.707,0.997,0.463,0.991
        inertia: 3
        loitering_time: 0
        objects: person
    motion:
      mask:
        - 0.697,0.014,0.702,0.087,0.985,0.071,0.991,0.021
        - 0.753,1,0.999,0.997,1,0,0.785,0
  taras:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/taras_sub
          input_args: preset-rtsp-restream
          #   http://taras.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
          # input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/taras?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
        - 0.211,0.998,0.173,0.744,0.21,0,0,0,0,1
        - 0.427,0.003,0.764,0.084,1,0.524,1,0
  drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drzwi_sub
          input_args: preset-rtsp-restream
          #   http://drzwi.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
          # input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/drzwi?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4
    zones:
      drzwi_frontowe:
        coordinates: 
          0.433,0.462,0.616,0.47,0.664,0.998,0.378,0.995,0.233,1,0.311,0.459,0.281,0.115,0.351,0,0.422,0
        inertia: 3
        loitering_time: 0
        objects: person
        filters:
          person:
            threshold: 0.8
    motion:
      mask:
        - 0.007,0.077,0.305,0.068,0.306,0.005,0.006,0
        - 0.923,0.03,0.923,0.061,0.993,0.066,0.993,0.026
  ogrod:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ogrod_sub
          input_args: preset-rtsp-restream
          #   http://ogrod.cam/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=login&password=pass
          # input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/ogrod?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 4

    motion:
      mask:
        - 0.003,0.233,0.312,0.059,0.469,0.021,0.826,0,0.003,0.002
        - 0.697,0,0.699,0.071,0.998,0.07,1,0
        - 0.83,1,0.888,0.545,0.871,0.08,1,0.08,1,1
  dzwonek:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dzwonek_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/dzwonek?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    objects:
      track:
        - person
        - car
        - cat
        - dog
    detect:
      width: 480
      height: 360
      fps: 10
    motion:
      mask:
        - 0,28,120,28,123,0,0,0
        - 480,0,480,360,430,360,420,132,396,0
        - 81,39,236,15,415,39,408,0,231,0,81,0,0,0,0,57
        - 81,32,0,0,0,360,58,358
  szopa:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/szopa_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/szopa?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 10

    motion:
      mask: 0,0.001,0.191,0,0.192,0.033,0,0.032
record:
  enabled: true
  retain:
    days: 5
    mode: all
  alerts:
    retain:
      days: 7
    pre_capture: 30
    post_capture: 60
  detections:
    retain:
      days: 7
    pre_capture: 30
    post_capture: 60
snapshots:
  enabled: true
  bounding_box: true

birdseye:
  enabled: false
  mode: objects
  restream: true

objects:
  track:
    - person
    - car
  # filters:
  #   person:
  #     min_score: 0.6
  #     threshold: 0.8

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264
camera_groups:
  Frontowe:
    order: 1
    icon: LuDoorOpen
    cameras:
      - front
      - drzwi
      - dzwonek
      - garaz
  Tył:
    order: 2
    icon: LuTrees
    cameras:
      - ogrod
      - taras
      - szopa
  Boki:
    order: 3
    icon: LuArrowDownUp
    cameras:
      - wschod
      - zachod
version: 0.15-1
```

I would say that the question is somewhat irrelevant from the cause of errors - having a programmatic way of detecting issues within Frigate and being able to simply shoot the instance in the head, would definitely help.

**Reply by hawkeye217** [reply]
Those logs are indicative of another problem, usually visible in the logs beforehand. What is your full log?

As for an endpoint, you can always query the HTTP API for recordings yourself to see if anything exists: https://docs.frigate.video/integrations/api/recordings-camera-name-recordings-get

**Reply by bsacharski** [reply]
Providing whole, full log will be difficult, as the instance was running for quite a while. I've looked for other messages in the output and looks like we've got our culprit:

```plain
frigate  | 2025-05-04 06:39:03.463528436  192.168.11.226 - - [04/May/2025:06:39:03 +0000] "GET / HTTP/1.1" 200 2651 "-" "Gatus/1.0" "-"
frigate  | 2025-05-04 06:39:30.153085925  127.0.0.1 - - [04/May/2025:06:39:30 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-05-04 06:40:04.145803332  192.168.11.226 - - [04/May/2025:06:40:04 +0000] "GET / HTTP/1.1" 200 2651 "-" "Gatus/1.0" "-"
frigate  | 2025-05-04 06:40:30.200285924  127.0.0.1 - - [04/May/2025:06:40:30 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-05-04 06:40:53.340741176  [2025-05-04 06:40:53] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504064042+0000.mp4 to /media/frigate/recordings/2025-05-04/06/zachod/40.42.mp4
frigate  | 2025-05-04 06:40:53.341159750  [2025-05-04 06:40:53] frigate.record.maintainer      ERROR   : Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/cache/zachod@20250504064042+0000.mp4':
frigate  | 2025-05-04 06:40:53.341163366    Metadata:
frigate  | 2025-05-04 06:40:53.341164473      major_brand     : isom
frigate  | 2025-05-04 06:40:53.341165496      minor_version   : 512
frigate  | 2025-05-04 06:40:53.341166422      compatible_brands: isomiso2avc1mp41
frigate  | 2025-05-04 06:40:53.341167326      title           : go2rtc/1.9.2
frigate  | 2025-05-04 06:40:53.341168187      encoder         : Lavf61.1.100
frigate  | 2025-05-04 06:40:53.341169232    Duration: 00:00:10.07, start: 0.000000, bitrate: 8383 kb/s
frigate  | 2025-05-04 06:40:53.341170627    Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 2560x1440, 8372 kb/s, 24.95 fps, 24.92 tbr, 90k tbn (default)
frigate  | 2025-05-04 06:40:53.341171403        Metadata:
frigate  | 2025-05-04 06:40:53.341172265          handler_name    : VideoHandler
frigate  | 2025-05-04 06:40:53.341173184          vendor_id       : [0][0][0][0]
frigate  | 2025-05-04 06:40:53.341174307    Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 49 kb/s (default)
frigate  | 2025-05-04 06:40:53.341175132        Metadata:
frigate  | 2025-05-04 06:40:53.341175942          handler_name    : SoundHandler
frigate  | 2025-05-04 06:40:53.341176687          vendor_id       : [0][0][0][0]
frigate  | 2025-05-04 06:40:53.341177830  [out#0/mp4 @ 0x5cc2a7303e80] Error opening output /media/frigate/recordings/2025-05-04/06/zachod/40.42.mp4: No space left on device
frigate  | 2025-05-04 06:40:53.341178872  Error opening output file /media/frigate/recordings/2025-05-04/06/zachod/40.42.mp4.
frigate  | 2025-05-04 06:40:53.341179824  Error opening output files: No space left on device
frigate  | 2025-05-04 06:40:53.341180541  
frigate  | 2025-05-04 06:40:57.905787784  [2025-05-04 06:40:57] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504064042+0000.mp4 to /media/frigate/recordings/2025-05-04/06/zachod/40.42.mp4
frigate  | 2025-05-04 06:40:57.905832505  [2025-05-04 06:40:57] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/szopa@20250504064043+0000.mp4 to /media/frigate/recordings/2025-05-04/06/szopa/40.43.mp4
frigate  | 2025-05-04 06:40:57.905955339  [2025-05-04 06:40:57] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/garaz_srodek@20250504064047+0000.mp4 to /media/frigate/recordings/2025-05-04/06/garaz_srodek/40.47.mp4

--- TIMESKIP ---

frigate  | 2025-05-04 07:45:07.705425168  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/front@20250504074331+0000.mp4 to /media/frigate/recordings/2025-05-04/07/front/43.31.mp4
frigate  | 2025-05-04 07:45:07.705426565  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/front@20250504074341+0000.mp4 to /media/frigate/recordings/2025-05-04/07/front/43.41.mp4
frigate  | 2025-05-04 07:45:07.705427928  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/front@20250504074351+0000.mp4 to /media/frigate/recordings/2025-05-04/07/front/43.51.mp4
frigate  | 2025-05-04 07:45:07.705429334  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/front@20250504074401+0000.mp4 to /media/frigate/recordings/2025-05-04/07/front/44.01.mp4
frigate  | 2025-05-04 07:45:07.705430834  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504074321+0000.mp4 to /media/frigate/recordings/2025-05-04/07/zachod/43.21.mp4
frigate  | 2025-05-04 07:45:07.705432339  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504074331+0000.mp4 to /media/frigate/recordings/2025-05-04/07/zachod/43.31.mp4
frigate  | 2025-05-04 07:45:07.705433781  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504074341+0000.mp4 to /media/frigate/recordings/2025-05-04/07/zachod/43.41.mp4
frigate  | 2025-05-04 07:45:07.705435209  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504074351+0000.mp4 to /media/frigate/recordings/2025-05-04/07/zachod/43.51.mp4
frigate  | 2025-05-04 07:45:07.705436700  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Unable to convert /tmp/cache/zachod@20250504074401+0000.mp4 to /media/frigate/recordings/2025-05-04/07/zachod/44.01.mp4
frigate  | 2025-05-04 07:45:07.707795157  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/cache/garaz@20250504074317+0000.mp4':
frigate  | 2025-05-04 07:45:07.707798844    Metadata:
frigate  | 2025-05-04 07:45:07.707799751      major_brand     : isom
frigate  | 2025-05-04 07:45:07.707800532      minor_version   : 512
frigate  | 2025-05-04 07:45:07.707801401      compatible_brands: isomiso2avc1mp41
frigate  | 2025-05-04 07:45:07.707802194      title           : go2rtc/1.9.2
frigate  | 2025-05-04 07:45:07.707802993      encoder         : Lavf61.1.100
frigate  | 2025-05-04 07:45:07.707803974    Duration: 00:00:10.08, start: 0.000000, bitrate: 8376 kb/s
frigate  | 2025-05-04 07:45:07.707805381    Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 2560x1440, 8371 kb/s, 24.95 fps, 24.92 tbr, 90k tbn (default)
frigate  | 2025-05-04 07:45:07.707806107        Metadata:
frigate  | 2025-05-04 07:45:07.707806946          handler_name    : VideoHandler
frigate  | 2025-05-04 07:45:07.707807785          vendor_id       : [0][0][0][0]
frigate  | 2025-05-04 07:45:07.707808847    Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 47 kb/s (default)
frigate  | 2025-05-04 07:45:07.707809649        Metadata:
frigate  | 2025-05-04 07:45:07.707810435          handler_name    : SoundHandler
frigate  | 2025-05-04 07:45:07.707811251          vendor_id       : [0][0][0][0]
frigate  | 2025-05-04 07:45:07.707812412  [out#0/mp4 @ 0x5971e2949640] Error opening output /media/frigate/recordings/2025-05-04/07/garaz/43.17.mp4: No space left on device
frigate  | 2025-05-04 07:45:07.707813444  Error opening output file /media/frigate/recordings/2025-05-04/07/garaz/43.17.mp4.

--- TIMESKIP  ---

frigate  | 2025-05-04 07:45:07.710612425  [2025-05-04 07:45:07] frigate.record.maintainer      ERROR   : Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/cache/zachod@20250504074401+0000.mp4':
frigate  | 2025-05-04 07:45:07.710613069    Metadata:
frigate  | 2025-05-04 07:45:07.710613769      major_brand     : isom
frigate  | 2025-05-04 07:45:07.710614464      minor_version   : 512
frigate  | 2025-05-04 07:45:07.710615207      compatible_brands: isomiso2avc1mp41
frigate  | 2025-05-04 07:45:07.710615962      title           : go2rtc/1.9.2
frigate  | 2025-05-04 07:45:07.710616729      encoder         : Lavf61.1.100
frigate  | 2025-05-04 07:45:07.710617610    Duration: 00:00:10.05, start: 0.000000, bitrate: 8400 kb/s
frigate  | 2025-05-04 07:45:07.710832168    Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 2560x1440, 8372 kb/s, 24.95 fps, 24.92 tbr, 90k tbn (default)
frigate  | 2025-05-04 07:45:07.710833593        Metadata:
frigate  | 2025-05-04 07:45:07.710834400          handler_name    : VideoHandler
frigate  | 2025-05-04 07:45:07.710835158          vendor_id       : [0][0][0][0]
frigate  | 2025-05-04 07:45:07.710836161    Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 50 kb/s (default)
frigate  | 2025-05-04 07:45:07.710836812        Metadata:
frigate  | 2025-05-04 07:45:07.710837554          handler_name    : SoundHandler
frigate  | 2025-05-04 07:45:07.710838302          vendor_id       : [0][0][0][0]
frigate  | 2025-05-04 07:45:07.710839403  [out#0/mp4 @ 0x612266a11d80] Error opening output /media/frigate/recordings/2025-05-04/07/zachod/44.01.mp4: No space left on device
frigate  | 2025-05-04 07:45:07.710840333  Error opening output file /media/frigate/recordings/2025-05-04/07/zachod/44.01.mp4.
frigate  | 2025-05-04 07:45:07.710841150  Error opening output files: No space left on device
frigate  | 2025-05-04 07:45:07.710841765  
frigate  | 2025-05-04 07:45:30.771612149  [2025-05-04 07:45:30] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for garaz. This likely indicates an issue with the detect stream, keeping the 6 mo
st recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 07:45:30.774472492  [2025-05-04 07:45:30] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for garaz_srodek. This likely indicates an issue with the detect stream, keeping t
he 6 most recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 07:45:33.366596107  127.0.0.1 - - [04/May/2025:07:45:33 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-05-04 07:45:35.775610394  [2025-05-04 07:45:35] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for szopa. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 07:45:35.777747858  [2025-05-04 07:45:35] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for ogrod. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 07:45:35.780166288  [2025-05-04 07:45:35] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for dzwonek. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...
frigate  | 2025-05-04 07:45:35.780806983  [2025-05-04 07:45:35] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for wschod. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...
```

So it looks like Frigate ran out of space - did the video rotation logic fail? Or maybe Frigate should be configured to leave "larger" buffer of free space?

**Reply by NickM-27** [reply]
This is recording storage space. Is the drive actually full? Frigate will delete old recordings to ensure 2 hours worth of free space so it seems something outside of Frigate caused the issue. Maybe there's a larger minimum space set at the os level for example

**Reply by bsacharski** [reply]
I've set up my instance to keep recordings on a separate ZFS pool:

```
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
nvr   3.62T  3.49T   139G        -         -    44%    96%  1.00x    ONLINE  -
```

```yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /nvr/storage:/media/frigate
      - type: tmpfs # Optional: 4GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4294967296
```

There are no snapshot rules configured for the pool so pretty much whole pool can only be eaten by recordings. 

Plus the restart helps, so maybe it's some race condition between recorder and storage manager?
