### DISCUSSION TITLE
Create event via API and record for 5s - can't find event in frigate

### DISCUSSION THREAD

**Discussion by marc107** [blakeblackshear/frigate#18032] [Ask A Question]
Hello everyone,

i would like to create an event for a camera via a manual call of curl and start a recording. Later, fhem should send the curl command when someone rings the doorbell.

I found the following command in the API documentation:

```
curl -L 'http://192.168.178.1:5000/api/events/front/:doorbell/create' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
  "source_type": "string",
  "sub_label": "string",
  "score": 0,
  "duration": 5,
  "include_recording": true,
  "draw": {}
}'
```

If I issue the obove command manually on the command line, I get the following response in the shell:

`{"success":true,"message":"Successfully created event.","event_id":"1746365585.429216-arfpa5"}`

So far this looks good in my opinion, but in frigate I can't find a corresponding event for the camera. Do I have to define the label beforehand so that it is also displayed in frigate? Or do you have another tip for me?

Best regards & thanks in advance

Marc

**Comment by NickM-27** [comment]
Where are you looking for the event? Do you have recordings enabled for that camera?

**Reply by marc107** [reply]
frigate => camera => history => events

Recording is enabled:

```
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.178.2:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: true # <---- turn on detection

    motion:
      improve_contrast: true

    record: # <----- Enable recording
      enabled: true
      alerts:
        retain:
          days: 14
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 14
        pre_capture: 5
        post_capture: 5
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true

    objects:
      filters:
        person:
          min_area: 14000
          min_ratio: 0
          max_ratio: 0.8
```

**Reply by NickM-27** [reply]
you'll have to remove the source_type as this will affect how it works

**Comment by hawkeye217** [comment]
Also important to note, `source_type` is an internal field and not something for users to set.

**Reply by marc107** [reply]
I didn't set it myself, it came from https://docs.frigate.video/integrations/api/create-event-events-camera-name-label-create-post/ (right upper corner, curl).

**Reply by hawkeye217** [reply]
Yes, the API documentation in particular is auto-generated and lists all possible fields. In this case, `source_type` should be left unset. This could probably be documented better.

If you remove `source_type` from your query, does it work?

**Comment by marc107** [comment]
So, using  the following code creates an event:

```
curl -L 'http://192.168.178.1:5000/api/events/back/:doorbell/create' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
  "sub_label": "string",
  "score": 0,
  "duration": 5,
  "include_recording": true,
  "draw": {}
}'
```

Unfortunately, when you click on the preview image, the message “No recording for this event found” appears.

**Reply by NickM-27** [reply]
did any motion occur during this time? You are using the default retention for alerts which is motion

**Reply by marc107** [reply]
no motion at this time.

is it possible to create an event and record when one of the following conditions occur?
a) motion
b) external trigger via API call

Later on there will be another camera which should only match to condition b).

**Reply by NickM-27** [reply]
The recordings still have to match your retention config as it's configured. You'll need to change the retention mode for alerts to all

**Reply by marc107** [reply]
Thank u very much!

This seems to do the trick - different camera:

```
  front:
    ffmpeg:
      inputs:
        - path: rtsp://X:X@192.168.178.1:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
              # - record
              #- rtmp      
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: false # <---- turn on detection

    motion:
      improve_contrast: true
    record: # <----- Enable recording
      enabled: true
      alerts:
        retain:
          days: 14
          mode: all
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 14
        pre_capture: 5
        post_capture: 5
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true

    objects:
      filters:
        person:
          min_area: 14000
          min_ratio: 0
          max_ratio: 0.8
```

In combination with
```
curl -L 'http://192.168.178.24:5000/api/events/front/alert/create' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{
  "sub_label": "string",
  "score": 0,
  "duration": 5,
  "include_recording": true,
  "draw": {}
}'
```

I now get a recording for my front-camera.

One last question:
In former version of frigate you could see, if there is any ongoing recording. Is there any place you can find this information in the newest version?
