### DISCUSSION TITLE
[Detector Support]: Using Coral dual TPU makes unraid unstable

### DISCUSSION THREAD

**Discussion by bmrowe** [blakeblackshear/frigate#18038] [Detector Support]
I have a coral dual TPU plugged into this pcie adapter: https://www.makerfabs.com/dual-edge-tpu-adapter.html?srsltid=AfmBOorFfIb0tFJk7EvTSAjgGIHqytS6y9fDgoaJakAV_RjztfuqG_Zw.

I have no issue getting the coral to work in Frigate. However, after some time, my entire unraid system will hard crash and reboot. 

I can get the system to be stable by switching the detector to use the CPU. Relevant screenshots below. 

<img width="878" alt="image" src="https://github.com/user-attachments/assets/235b5afc-ece1-49b0-ad71-8624b653b3b7" />

<img width="215" alt="image" src="https://github.com/user-attachments/assets/e7b849f7-2b7e-487c-8cbe-51ccf232ec85" />

### Version

0.16.0-5c3ac75

### Frigate config file

```yaml
environment_vars:
  OPENCV_LOG_LEVEL: FATAL

mqtt:
  enabled: true
  host: 192.168.1.198
  port: 1883
  topic_prefix: frigate
  client_id: frigate

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-copy

model:
#  path: plus://xxxxxx
  path: plus://xxxxxx

#detectors:
#  coral1:
#    type: edgetpu
#    device: pci:0
#  coral2:
#    type: edgetpu
#    device: pci:1
detectors:
  ov:
    type: openvino
    device: CPU

semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: true
  provider: gemini
  api_key: xxxxx
  model: gemini-2.0-flash-lite

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 365
      mode: motion

birdseye:
  enabled: true
  mode: continuous

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  retain:
    default: 10

objects:
  track:
    - person
    - face
    - dog
    - cat
    - deer
    - car
    - motorcycle
    - boat
    - license_plate
    - amazon
    - fedex
    - ups
    - package
    - horse
    - brid
    - raccoon
    - fox
    - bear
    - squirrel
    - rabbit
    - waste_bin
  filters:
    person:
      min_score: 0.65
      threshold: 0.85
    deer:
      min_score: 0.7
      threshold: 0.9
    car:
      min_score: 0.6
      threshold: 0.8
    cat:
      min_score: 0.7
      threshold: 0.85
    dog:
      min_score: 0.7
      threshold: 0.85
    face:
      min_score: 0.6
    package:
      min_score: 0.6
      threshold: 0.8

go2rtc:
  streams:
    frontdoor:
      - ffmpeg:http://192.168.1.106/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy#audio=opus
    frontdoor_sub:
      - ffmpeg:http://192.168.1.106/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx#video=copy#audio=copy
    doorbell:
      - ffmpeg:http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.108/Preview_01_sub
    doorbell_sub:
      - ffmpeg:http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy
    driveway:
      - ffmpeg:http://192.168.1.134/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxxx#video=copy#audio=copy#audio=opus
    driveway_sub:
      - ffmpeg:http://192.168.1.134/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy
    backyard_left:
      - ffmpeg:http://192.168.1.28/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy#audio=opus
    backyard_left_sub:
      - ffmpeg:http://192.168.1.28/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy
    pool:
      - ffmpeg:http://192.168.1.23/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy#audio=opus
    pool_sub:
      - ffmpeg:http://192.168.1.23/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxxx#video=copy#audio=copy
    sideyard_left:
      - ffmpeg:http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxxx#video=copy#audio=copy#audio=opus
    sideyard_left_sub:
      - ffmpeg:http://192.168.1.55/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxxx&password=xxxx#video=copy#audio=copy
    backyard_right:
      - ffmpeg:http://192.168.1.132/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxxx#video=copy#audio=copy#audio=opus
    backyard_right_sub:
      - ffmpeg:http://192.168.1.132/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx#video=copy#audio=copy
    sideyard_right:
      - ffmpeg:http://192.168.1.32/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxxx#video=copy#audio=copy#audio=opus
    sideyard_right_sub:
      - ffmpeg:http://192.168.1.32/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx#video=copy#audio=copy

cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Sidewalk:
        coordinates: 0.444,0.012,0.446,0.059,0.708,0.133,0.71,0.053,0.485,0.018
        loitering_time: 4
        objects:
          - car
          - person
          - dog
          - deer
          - cat
          - package
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
    zones:
      sidewalk:
        coordinates: 0.476,0,0.525,0,0.682,0,0.859,0.083,0.863,0.143,0.682,0.086
        loitering_time: 3
        objects:
          - car
          - cat
          - deer
          - dog
          - package
          - person
  backyard_left:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_left
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_left_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
      filters:
        person: {}
    motion:
      threshold: 30
      contour_area: 10
      mask:
        - 0.198,0.527,0.277,0.414,0.251,0.175,0.188,0.034,0.089,0.061,0.057,0.28,0.135,0.525
        - 1,0.534,1,1,0.831,1,0.942,0.708
      improve_contrast: false
  pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 10
      mask:
        - 0.2,0.151,0.142,0.344,0.105,0.478,0.07,0.641,0.046,0.783,0.029,0.905,0.02,1,0.451,0.998,0.494,1,0.651,0.969,0.844,0.892,0.942,0.829,0.71,0.315,0.547,0.283,0.517,0.171
        - 0.531,0.039,0.61,0.029,0.595,0.128,0.558,0.125,0.538,0.112
        - 0.629,0,0.623,0.073,0.665,0.091,0.678,0
      improve_contrast: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    zones:
      Sidewalk:
        coordinates: 0.387,0.448,0.583,0.454,0.581,0.43,0.342,0.421
        loitering_time: 4
        objects:
          - car
          - cat
          - deer
          - dog
          - package
          - person
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
  sideyard_left:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sideyard_left
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sideyard_left_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
      mask: 0.509,0.002,0.784,0.373,0.996,0.802,0.996,0.002
  backyard_right:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_right
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_right_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
      mask:
        - 0.645,0.827,0.818,0.623,0.586,0.404,0.414,0.255,0.177,0.31,0.35,0.687,0.481,0.609
        - 0.359,0.042,0.435,0.034,0.442,0.198,0.36,0.192,0.357,0.115
    motion:
      threshold: 40
      contour_area: 10
      mask:
        - 0.068,0.342,0.073,0.463,0.095,0.641,0.27,0.547,0.346,0.727,0.481,0.619,0.641,0.846,0.827,0.641,0.828,0.619,0.814,0.59,0.646,0.434,0.511,0.312,0.424,0.244,0.384,0.222,0.282,0.249,0.242,0.263,0.165,0.288
        - 0.112,0.03,0.168,0.006,0.169,0.182,0.113,0.211
        - 0.237,0.154,0.235,0,0.296,0.001,0.298,0.136
        - 0.31,0.166,0.332,0.16,0.331,0.003,0.31,0
        - 0.359,0.046,0.428,0.04,0.447,0.203,0.361,0.197,0.357,0.084
        - 0.989,0.704,0.941,0.807,0.948,0.919,1,0.945,0.998,0.733
        - 0.838,0,0.877,0.352,0.933,0.375,1,0.388,0.999,0.003
        - 0.245,0.263,0.247,0.242,0.261,0.229,0.278,0.236,0.287,0.245,0.285,0.267
      improve_contrast: true
  sideyard_right:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sideyard_right
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sideyard_right_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
      mask: 0.924,0.825,0.906,0.809,0.889,0.853,0.885,0.911,0.922,0.867
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
      mask: 0.805,0,0.805,0.062,0.838,0.074,0.858,0.062,0.864,0
version: 0.16-0

detect:
  enabled: true
#face_recognition:
#  enabled: true
#  model_size: small

#lpr:
#  enabled: true
#classification:
#  bird:
#    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='br0'
  --ip='192.168.1.5'
  --pids-limit 2048
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unraid"
  -e HOST_CONTAINERNAME="frigate"
  -e 'TCP_PORT_5000'='80'
  -e 'TCP_PORT_8554'='8554'
  -e 'FRIGATE_RTSP_PASSWORD'='admin'
  -e 'LIBVA_DRIVER_NAME'='iHD'
  -e 'TCP_PORT_8555'='8555'
  -e 'UDP_PORT_8555'='8555'
  -e 'TCP_PORT_1984'='1984'
  -e 'cap-add'='CAP_PERFMON'
  -e 'PLUS_API_KEY'='xxxxx'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/disks/security/':'/media/frigate':'rw,slave'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/dri/renderD128'
  --shm-size=1028mb
  --cap-add=CAP_PERFMON
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:0.16.0-beta1'
aadba27866ce5392eb35b8baed5ae85307719fcc0911f3358859d90acf882e42
```

### Relevant Frigate log output

```shell
The only relevant output are two lines each time frigate starts up with one error for each of the TPUs like this:

frigate.detecto:29004 map pfn RAM range req uncached-minus for [mem 0x6f1c4c000-0x6f1c4ffff], got write-back
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

not relevant, the coral appears healthy up until the crash.
