### DISCUSSION TITLE
face detection to trigger automation in home assistant?

### DISCUSSION THREAD

**Discussion by r11a** [blakeblackshear/frigate#18049] [Ask A Question] [answered]
Hi,

How can I trigger Automation when face is recognized for a spesfic camera? (Eric detected in DoorBell Camera) 

Frigate 0.16 Beta1 Home Assistant Addon

**Comment by hawkeye217** [comment]
See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/18048), Usage question 2.

**Reply by r11a** [reply]
Thank you, but Im not sure that I'm understand how to configure it using home assistant automation...

**Reply by hawkeye217** [reply]
Something like this should work (untested):

```
alias: Face Recognition Notification
description: "Send notification when a face is recognized by Frigate"
trigger:
  - platform: mqtt
    topic: frigate/tracked_object_update 
condition:
  - condition: template
    value_template: "{{ trigger.payload_json.type == 'face' }}"
  - condition: template
    value_template: "{{ trigger.payload_json.name != 'unknown' }}"
  - condition: template
    value_template: "{{ trigger.payload_json.score > 0.7 }}"
action:
  - service: notify.mobile_app_your_device
    data:
      title: "Face Detected: {{ trigger.payload_json.name }}"
      message: >-
        {{ trigger.payload_json.name }} detected on {{ trigger.payload_json.camera | replace('_', ' ') | title }}
        Confidence: {{ (trigger.payload_json.score * 100) | round }}%
```
