### DISCUSSION TITLE
[Support]: Getting this in logs: s6-applyuidgid: fatal: unable to exec exec: Permission denied

### DISCUSSION THREAD

**Discussion by shopboy3** [blakeblackshear/frigate#18040] [General Support]
### Describe the problem you are having

I have Frigate running as a container in Open Media Vault (OMV) using the built in Compose. It started freezing up on me lately and when I go into the OMV compose logs it keeps showing this "s6-applyuidgid: fatal: unable to exec exec: Permission denied". By freezing up I it just doesn't open and nothing seems to be working (GUI not accessible and HomeAssistant cannot see the camera feeds). I've tried several things including deleting everything and starting over but not super familiar with all of this. Has anyone seen anything similar?

System logs in the UI do not load (Frigate Go2rtc Nginx)

### Version

0.15.0-cea210d

### What browser(s) are you using?

Chrome 135.0.7049.116

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.42.18:5000/api/config/schema
#-------------------------------------------------------------------------------------------------------
mqtt:
  host: 192.168.42.18 # address of home assistant plus mqtt user credentials
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: frigate
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: passworrd
#-------------------------------------------------------------------------------------------------------
detectors:
  # Required: name of the detector
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
#    num_threads: 3
#-------------------------------------------------------------------------------------------------------
# Optional: Database configuration
#database:
  # The path to store the SQLite DB (default: shown below)
  #path: /srv/dev-disk-by-uuid-6eb5aa21-c43a-47d2-ba96-1a2263e699a8/Frigate/config/database/frigate.db
  #path: /srv/dev-disk-by-uuid-6eb5aa21-c43a-47d2-ba96-1a2263e699a8/Frigate/media/frigate/frigate.db
  #path: /media/frigate/frigate.db
  #-------------------------------------------------------------------------------------------------------
#go2rtc:
##  streams:
##    test_cam: ...
#  webrtc:
#    candidates:
#      - 192.168.42.18:8555
#      - stun:8555
#-------------------------------------------------------------------------------------------------------
# Optional: ffmpeg configuration
# More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  #global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  #hwaccel_args:
    #- -c:v
    #- h264_v4l2m2m
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -an # <----- previous
  output_args:
    record: preset-record-generic-audio-aac
    #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy <----- other options
#-------------------------------------------------------------------------------------------------------
#Global Object Settings
objects:
  track:
    - person
    - bus
  #  - cat
    - car
  #  - dog
  #  - horse
    - bicycle
  #  - bird
    - motorcycle
  #  - sheep
  # filters:
  #   person:
  #     min_area: 5000
  #     max_area: 100000
#-------------------------------------------------------------------------------------------------------
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  retain:
    default: 365
#-------------------------------------------------------------------------------------------------------
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 90
  detections:
    retain:
      days: 90
timestamp_style:
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S" 
  format: '%m/%d/%Y %H:%M:%S'
  # Optional: Color of font
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 0
    blue: 0
#-------------------------------------------------------------------------------------------------------
# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: True)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
#  width: 1920
  # Optional: Height of the output resolution (default: shown below)
#  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
#-------------------------------------------------------------------------------------------------------
environment_vars: # Optional: set environment variables
  #EXAMPLE_VAR: value
  FRIGATE_campass: mypassword
  #FRIGATE_campass {FRIGATE_campass}
#-------------------------------------------------------------------------------------------------------
cameras: # Required
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  UVC_G3_Dome_1:
    # Optional: Enable/Disable the camera.
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.42.27:7447/6455016ee4b04a428fa6101f_2 # <----- low res camera 640 x 360
          roles:
            - detect
        - path: rtsp://192.168.42.27:7447/6455016ee4b04a428fa6101f_0 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      # stationary:
      #   interval: 0
      #   threshold: 50  
      width: 640 # <---- update for your camera's resolution
      height: 368 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion:
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 0,0,0,0.003,0.476,0,0.154,0.053,0.155,0.076,0,0.089,0,0
        - 0.892,0,0.881,0.034,0.705,0.036,0.65,0
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
      #  bicycle:
      #    mask:
      #  bird:
      #    mask:
      #  bus:
      #    mask:
      #  car:
      #    mask:
      #  cat:
      #    mask:
      #  dog:
      #    mask:
      #  horse:
      #    mask:
      #  motorcycle:
      #    mask:
        person:
          mask:
      #  sheep:
      #    mask:
      track:
        - person
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -     
  UVC_G3_Dome_2: # 
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://192.168.42.27:7447/?????_2 # <----- low res camera 640 x 360
          roles:
            - detect
        - path: rtsp://192.168.42.27:7447/?????_0 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 368 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 0,0,120,0,120,12,96,12,96,28,0,32 #<---- time stamp
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  UVC_G3_Bullet_3: # 
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.42.27:7447/65610d4be4b04619df05e176_2 # <----- low res camera 640 x 360
          roles:
            - detect
        - path: rtsp://192.168.42.27:7447/65610d4be4b04619df05e176_0 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 368 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 155,0,0,0,0,131,155,87 #<---- side of the shed above door and time stamp
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        bicycle:
          mask:
        bus:
          mask:
        car:
          mask:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  UVC_G3_Bullet_4: # 
    enabled: true
    ffmpeg:
      inputs: # Required: A list of input streams for the camera. See documentation for more information.
        - path: rtsp://192.168.42.27:7447/65724dbee4b07fb8ffa6e719_2 # <----- low res camera 640 x 360
          roles: # Required: list of roles for this stream. valid values are: detect,record,rtmp
            - detect
        - path: rtsp://192.168.42.27:7447/65724dbee4b07fb8ffa6e719_0 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 368 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 0,0,0.188,0,0.188,0.033,0.154,0.03,0.155,0.076,0,0.077
        - 1,0.668,1,1,0.961,1
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        bus:
          mask:
        car:
          mask:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  UVC_G3_Bullet_5: #
    enabled: true
    ffmpeg:
      inputs: # Required: A list of input streams for the camera. See documentation for more information.
        - path: rtsp://192.168.42.27:7447/65724e72e4b07fb8ffa6e71a_2 # <----- low res camera 640 x 360
          roles: # Required: list of roles for this stream. valid values are: detect,record,rtmp
            - detect
        - path: rtsp://192.168.42.27:7447/65724e72e4b07fb8ffa6e71a_0 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 368 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: 0,0,0.188,0,0.188,0.033,0.153,0.033,0.154,0.076,0,0.076 #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        bus:
          mask:
        car:
          mask:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  UVC_G3_Bullet_6: # 
    enabled: true
    ffmpeg:
      inputs: # Required: A list of input streams for the camera. See documentation for more information.
        - path: rtsp://192.168.42.27:7447/65724e72e4b07fb8ffa6e71b_2 # <----- low res camera 640 x 360
          roles: # Required: list of roles for this stream. valid values are: detect,record,rtmp
            - detect
        - path: rtsp://192.168.42.27:7447/65724e72e4b07fb8ffa6e71b_0 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 368 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 0,0,0.188,0,0.188,0.033,0.154,0.036,0.154,0.08,0,0.079
        - 0.047,1,0,0.661,0,1
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  Reo7: # 
    enabled: true
    ffmpeg:
      inputs: # Required: A list of input streams for the camera. See documentation for more information.
        - path: rtsp://admin:password@192.168.42.37:554//h264Preview_01_sub # <----- low res camera 640 x 480
          roles: # Required: list of roles for this stream. valid values are: detect,record,rtmp
            - detect
        - path: rtsp://admin:password@192.168.42.37:554//h264Preview_01_main # <----- high res camera 2560 x 1920
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 0.013,0.049,0.303,0.048,0.303,0.017,0.013,0.017
        - 0.066,0.954,0.066,0.979,0.013,0.979,0.013,0.954
        - 0,0.285,0.045,0.108,0.07,0,0,0
        - 0.062,1,0,0.569,0,1
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        bus:
          mask:
        car:
          mask:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  Reo8: # 
    enabled: true
    ffmpeg:
      inputs: # Required: A list of input streams for the camera. See documentation for more information.
        - path: rtsp://admin:password@192.168.42.38:554//h264Preview_01_sub # <----- low res camera 640 x 480
          roles: # Required: list of roles for this stream. valid values are: detect,record,rtmp
            - detect
        - path: rtsp://admin:password@192.168.42.38:554//h264Preview_01_main # <----- high res camera 2560 x 1920
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 0,0,0,0,0.303,0,0.303,0.05,0,0.05,0,0
        - 0.066,0.954,0.066,0.979,0.013,0.979,0.013,0.954
        - 0,0.654,0.147,1,0,1
        - 0.694,0,1,0,1,0.087
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        person:
          mask:
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  Smart_Camera_wifi: # unused
    enabled: false
    ffmpeg:
      inputs: # Required: A list of input streams for the camera. See documentation for more information.
        - path: rtsp://192.168.42.115/ch0_0.h264 # <----- low res camera 640 x 360 (not available for this camera)
          roles: # Required: list of roles for this stream. valid values are: detect,record,rtmp
            - detect
        - path: rtsp://192.168.42.115/ch0_0.h264 # <----- high res camera 1920 x 1080
          roles:
            - record
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5 #<---- known camera fps or lower
    motion: #<---- does not detect motion in this region  
      mask: #<---- edit and view: Cameras > select camera > debug > show options > toggle motion masks > mask & zone creator
        - 1280,0,1280,720,0,720,0,0
    objects: #<---- does not detect objects with bottom center of bounding box in this region
      filters:
        person:
          mask:
version: 0.15-1
#-------------------------------------------------------------------------------------------------------
camera_groups: {}
```

### Relevant Frigate log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-rc: info: service frigate-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-applyuidgid: fatal: unable to exec exec: Permission denied
s6-applyuidgid: fatal: unable to exec exec: Permission denied
```

### Relevant go2rtc log output

```shell
System logs in the UI do not load (Frigate Go2rtc Nginx)
```

### FFprobe output from your camera

```shell
?
```

### Frigate stats

```json
?
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
---
# https://github.com/blakeblackshear/frigate
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-uuid-6eb5aa21-c43a-47d2-ba96-1a2263e699a8/Frigate/config:/config
      - /srv/dev-disk-by-uuid-6eb5aa21-c43a-47d2-ba96-1a2263e699a8/Frigate/media:/media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "192.168.42.18:5000:5000"
      - "192.168.42.18:8971:8971" # new restricted access port
      - "192.168.42.18:8555:8555/tcp" # WebRTC over tcp
      - "192.168.42.18:8555:8555/udp" # WebRTC over udp 
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: myapikeyremovedforprivacy
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reo

### Screenshots of the Frigate UI's System metrics pages

![system metrics Cameras](https://github.com/user-attachments/assets/8751a8ed-4089-4068-9235-d1b422965323)
![system metrics Storage](https://github.com/user-attachments/assets/6c5bc246-b65a-44de-abad-2fa8ce0f1bf3)
![system metrics General](https://github.com/user-attachments/assets/b1539cb0-5680-4c08-b068-594a1690cdb5)
