### DISCUSSION TITLE
Viewing frigate clips and snapshots on Android HA app or chrome failing.

### DISCUSSION THREAD

**Discussion by peteDDD** [blakeblackshear/frigate#18041] [Config Support] [answered]
### Describe the problem you are having

1) I can view live videos using Android HA app or chrome on my android phone but 
2) can't view clips of detected events without getting PIPELINE_ERROR_DECODE message.     
3) Also can't view notification clips (I see that there is an 8-second clip but pressing play does nothing).  
4) And "view snapshot" from notifications gives {"success": false, "message: "Snapshot not available"} 

  Is there (there must be...) a setting (or settings) I am missing to allow clips and snapshots to work on the HA app?

(Incidentally, no trouble viewing the equivalent Blue Iris snapshots and clips in HA app on Android phone... I am trying to complete migration from Blue Iris to Frigate)

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.220
  port: 1883
  user: homeassistant
  password: passypass
  topic_prefix: frigate
go2rtc:
  streams:
    se1_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.101:554/11
    se1_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.101:554/12
    cp2_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.102:554/11
    cp2_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.102:554/12
    ne3_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.103:554/11
    ne3_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.103:554/12
    bk4_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.104:554/11
    bk4_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.104:554/12
    nw5_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.105:554/11
    nw5_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.105:554/12
    sw6_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.106:554/11
    sw6_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.106:554/12
    ft7_hi:
      - ffmpeg:rtsp://admin:passypass@192.168.10.107:554/11
    ft7_low:
      - ffmpeg:rtsp://admin:passypass@192.168.10.107:554/12

cameras:
  se1:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/se1_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/se1_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: se1_hi
      height: 720
      quality: 8
    onvif:
      host: 192.168.10.101
      port: 8080
      user: admin
      password: passypass

  cp2:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/cp2_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/cp2_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: cp2_hi
      height: 720
      quality: 8


  ne3:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/ne3_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/ne3_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: ne3_hi
      height: 720
      quality: 8
    onvif:
      host: 192.168.10.103
      port: 8080
      user: admin
      password: passypass

  bk4:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/bk4_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/bk4_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: bk4_hi
      height: 720
      quality: 8


  nw5:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/nw5_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/nw5_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: nw5_hi
      height: 720
      quality: 8
    onvif:
      host: 192.168.10.105
      port: 8080
      user: admin
      password: passypass

  sw6:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/sw6_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/sw6_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: sw6_hi
      height: 720
      quality: 8
    onvif:
      host: 192.168.10.106
      port: 8080
      user: admin
      password: passypass

  ft7:
    ffmpeg:
      inputs:
        # hi res stream
        - path: rtsp://127.0.0.1:8554/ft7_hi
          input_args: preset-rtsp-restream
          roles:
            - record

        # low res stream
        - path: rtsp://127.0.0.1:8554/ft7_low
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      enabled: true
      width: 800
      height: 450
    live:
      stream_name: ft7_hi
      height: 720
      quality: 8



detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
objects:
  track:
    - person

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    #NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    #NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  alerts:
    retain:
      days: 10
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 10
    pre_capture: 5
    post_capture: 5
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: false
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  #NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
version: 0.15-1
```

### Relevant Frigate log output

```shell
nope
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/2484e55e-efbc-4062-9dac-d216322a1ecc)

### Any other information that may be helpful

frigate notification config
```
alias: Frigate Notifications
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.se1
      - camera.cp2
      - camera.ne3
      - camera.bk4
      - camera.nw5
      - camera.sw6
      - camera.ft7
    notify_device: ceffa34274ba72d5c7d2bb999999999
    url_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    title: Frigate Alert
    message: Person Detected
    critical: "true"
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif?format=ts
    final_update: true
    color: "#926bc7"
    sticky: true
```

action buttons:

![image](https://github.com/user-attachments/assets/f7572724-950b-4f81-b4a7-03f66866dfe1)

debug logging to home assistant log is turned on but not showing any warnings or errors related to Frigate.
