### DISCUSSION TITLE
Frigate 0.16 FAQ

### DISCUSSION THREAD

**Discussion by hawkeye217** [blakeblackshear/frigate#18048] [General]
This FAQ is maintained by the Frigate developers to help answer some of the common questions with Frigate 0.16 beta. If you have a question that's not answered here, be sure to read the [release notes](https://github.com/blakeblackshear/frigate/releases/tag/v0.16.0-beta1), the [official documentation](https://docs.frigate.video/), and search the recent discussions first. If you still need help, [open a support discussion](https://github.com/blakeblackshear/frigate/discussions/new/choose).

Some questions may also be answered in the older version, [Frigate 0.15 FAQ](https://github.com/blakeblackshear/frigate/discussions/16391), so be sure to read those as well.

_Updated September 8, 2025_

## Upgrade issues

1. **I just upgraded and Frigate is not detecting objects anymore. Why?**
This was discussed in the breaking changes in the [release notes](https://github.com/blakeblackshear/frigate/releases/tag/v0.16.0-beta1). Frigate 0.16 disables object detection by default. For most users, a config migrator is run to enable detection but if this fails or your config is read-only, you may need to edit your config to enable detection.
   ```
   detect:
     enabled: true
   ```

1. **I see `INFO: Created TensorFlow Lite XNNPACK delegate for CPU.` in my logs. Does this mean my GPU is not being used?**
No. This message comes from the face recognition feature in Frigate 0.16. It doesn't have anything to do with object detection or hardware acceleration. You can ignore it.

1. **I just upgraded my Home Assistant add-on and now my Coral TPU is not being detected.**
The add-on's protection mode switch may be re-enabled by Home Assistant after upgrading. You need to disable protection mode for the add-on or use the standard add-on (not "Frigate Full Access"). 

## Usage

1. **I enabled Face Recognition but I see the message `WARNING : camera is configured to track ['face'] objects, which are not supported by the current model.` in my logs. Why?**
This warning appears when you’ve added `face` (or `license_plate`) to the `objects --> track` list in your config, but you're not using a model that supports those object types, such as Frigate+ or a custom model with native support. If you're running the default free model that ships with Frigate, Face Recognition and License Plate Recognition will still work without those objects in the `track` list. To remove the log warning, simply delete `face` and/or `license_plate` from `objects --> track`. See the model requirements in the [Face Recognition](https://docs.frigate.video/configuration/face_recognition) and [LPR](https://docs.frigate.video/configuration/license_plate_recognition) documentation.

1. **How do I use detected faces and license plates in Home Assistant sensors and automations?**
The Frigate HA Integration version 5.9.2 adds support for a sensor for each camera's last recognized face / license plate. For more advanced used cases, Frigate updates the `frigate/events` and `frigate/tracked_object_update` MQTT topics with recognized faces and license plates. You can create MQTT sensors or use these topics directly in automations. See the [documentation](https://docs.frigate.video/integrations/mqtt/#frigatetracked_object_update). Here is an example automation for faces that can be adapted for license plates easily.
    ```
    alias: Face Recognition Notification
    description: "Send notification when a face is recognized by Frigate"
    trigger:
      - platform: mqtt
        topic: frigate/tracked_object_update 
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.type == 'face' }}"
      - condition: template
        value_template: "{{ trigger.payload_json.name != 'unknown' }}"
      - condition: template
        value_template: "{{ trigger.payload_json.score > 0.7 }}"
    action:
      - service: notify.mobile_app_your_device
        data:
          title: "Face Detected: {{ trigger.payload_json.name }}"
          message: >-
            {{ trigger.payload_json.name }} detected on {{ trigger.payload_json.camera | replace('_', ' ') | title }}
            Confidence: {{ (trigger.payload_json.score * 100) | round }}%
    ```

1. **I've set the `large` model in my config but how can I be sure enrichments are using my iGPU? The usage in System Metrics is 0.**
There is a bug in Intel's GPU tools that prevents correct reporting of the usage to Frigate. You can run `intel_gpu_top` on your host to see GPU usage.

1. **I am using a Coral or Hailo for object detection, can I use it for enrichments like face recognition and LPR?** 
No, a Coral is a TPU (tensor processing unit). Frigate requires a dedicated GPU (graphics processing unit) like an Intel iGPU or Nvidia graphics card to accelerate enrichments with hardware. If you have both a Coral or Hailo and a dedicated GPU, it is possible to still use the Coral for object detection. In all cases, however, you will need to use the appropriate Docker image for your installation to accelerate enrichments. See the [documentation](https://docs.frigate.video/configuration/hardware_acceleration_enrichments).

1. **Frigate loses connection to my cameras and then consumes a lot of memory until it becomes unresponsive. Why?**
Users with this issue are often running WiFi cameras, which are [not recommended](https://ipcamtalk.com/threads/multiple-cameras-high-bandwidth.77100/#post-861110). A few users have reported that this issue can be mitigated by using `preset-rtsp-generic` instead of `preset-rtsp-restream`. But in general, this is usually a result of WiFi cameras or is an ffmpeg issue that only happens with certain cameras.

1. **I'm having trouble using the mask/zone editor, I can't click points and close the polygon.**
This is due to Brave Browser's underlying extreme anti-fingerprinting code that [breaks a common function in JavaScript](https://github.com/konvajs/konva/issues/1132#issuecomment-867339732). To use Brave Browser with Frigate, you should disable Brave Shields.

1. **Can I use the `record` stream for LPR and Face Recognition? I don't get good results with the `detect` stream.**
No, your `record` stream is not decoded by Frigate. Like other enrichments, LPR and Face Recognition run on the stream defined with the `detect` role in your config. However, when using the [recommended cameras](https://docs.frigate.video/frigate/hardware/#cameras), we found through extensive testing that a 1280x720 stream was sufficient for most users for accurate recognition. You could either:
    - Use the main stream from your camera as-is for the `detect` role, or 
    - Use the main stream for the `detect` role but set your `detect` `width` and `height` to 1280 and 720 respectively so that your GPU will be used to scale it.

1. **Why does my Intel GPU usage always show as `0`? Is my iGPU being used?**
We've received many reports of this where users indicate that their Intel GPU stats work for a while, but then eventually show as zero. This is a bug in Intel GPU Tools, there's nothing Frigate can do to fix it at this point.

1. **I'm trying to use the new YOLOv9 Frigate+ models with my iGPU but I'm seeing this error in my logs. `[GPU] Mismatch tensor and port type: f32 vs u8`**
You need to update to Frigate 0.16.1, where support for YOLOv9 Frigate+ models was added.
