### DISCUSSION TITLE
[Detector Support]: Hailo-8 in OrangePI Max

### DISCUSSION THREAD

**Discussion by aspavlikov** [blakeblackshear/frigate#18050] [Detector Support] [answered]
### Describe the problem you are having

Hi Please advise. i configured Frigate as described in the Hailo community manual (driver version 4.20, docker image frigate:678ae87). Frigate starts, work ok but after some time Image embedding Speed goes up from 10 ms to 1060 ms. 
And in general systems looks less balanced in comparison with  pure rknn.
Probably this can be linked with warnings in logs. Please take a look.

### Version

0.16.0-678ae87

### Frigate config file

```yaml
mqtt:
  host: 192.168.89.153  
  port: 1883
  user: frigate
  password:


# RKNN ---------------------------------------------------
#ffmpeg:
#  path: /root/ffmpeg-rockchip
#  hwaccel_args: preset-rk-h265
#  global_args: -hwaccel rkmpp -hwaccel_output_format drm_prime

#detectors:
#  rknn: # required
#    type: rknn # required
    # number of NPU cores to use
    # 0 means choose automatically
    # increase for better performance if you have a multicore NPU e.g. set to 3 on rk3588
#    num_cores: 3

#model: # required
  # name of model (will be automatically downloaded) or path to your own .rknn model file
#  path: deci-fp16-yolonas_l
  # width and height of detection frames
#  width: 320
#  height: 320
  # pixel format of detection frame
  # default value is rgb but yolo models usually use bgr format
#  input_pixel_format: bgr # required
  # shape of detection frame
#  input_tensor: nhwc
  # needs to be adjusted to model, see below
#  labelmap_path: /labelmap.txt # required

# --------------------------------------------------------

# HAILO --------------------------------------------------

ffmpeg:
  # Optional: ffmpeg binry path (default: shown below)
  # can also be set to `7.0` or `5.0` to specify one of the included versions
  # or can be set to any path that holds `bin/ffmpeg` & `bin/ffprobe`
  path: /usr/lib/ffmpeg/6.0/
#  hwaccel_args: preset-rk-h264
#  global_args: -hide_banner -loglevel warning -threads 4 -hwaccel rkmpp -hwaccel_output_format
#    drm_prime
detectors:
  hailo8l:
    type: hailo8l
    device: PCIe


#model:
#  path: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.14.0/hailo8/yolov8m.hef
#  path: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.15.0/hailo8/yolov11l.hef
#  path: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.15.0/hailo8/yolov8l.hef

model:
  width: 320
  height: 320
  input_tensor: nhwc
  input_pixel_format: rgb
  input_dtype: int
  model_type: yolo-generic
  labelmap_path: /labelmap.txt

#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  model_type: ssd
#  path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef

# -----------------------------------------------------------

logger:
  default: warning

review:
  alerts:
    labels:
      - cat
      - car
      - dog
      - person
      - bicycle
      - motorcycle
      - bird

  detections:
    labels:
      - cat
      - car
      - dog
      - person
      - bicycle
      - motorcycle
      - bird
objects:
  track:
    - cat
    - car
    - dog
    - person
    - bicycle
    - motorcycle
    - bird

semantic_search:
  enabled: true
  reindex: false
  model_size: large

go2rtc:
  image: config/go2rtc
  streams:
    cam_parking_backyard:
#      - onvif://admin:admin123456@192.168.89.161:6688/profile001
      - rtsp://admin:admin123456@192.168.89.161:8554/profile0
      - ffmpeg:cam_parking_backyard#video=264#hardware#audio=aac
    cam_parking_facade:
#      - onvif://admin:admin123456@192.168.89.162:6688/profile001
      - rtsp://admin:admin123456@192.168.89.162:8554/profile0
      - ffmpeg:cam_parking_facade#video=264#hardware#audio=aac
    cam_veranda:
#      - onvif://admin:admin123456@192.168.89.163:6688/profile001
      - rtsp://admin:admin123456@192.168.89.163:8554/profile0
      - ffmpeg:cam_veranda#video=264#hardware#audio=aac
    cam_domushka:
#      - onvif://admin:admin123456@192.168.89.164:6688/profile001
      - rtsp://admin:admin123456@192.168.89.164:8554/profile0
      - ffmpeg:cam_domushka#video=264#hardware#audio=aac
    cam_boilernaya:
#      - onvif://admin:admin123456@192.168.89.165:6688/profile001
      - rtsp://admin:admin123456@192.168.89.165:8554/profile0
      - ffmpeg:cam_boilernaya#video=264#hardware#audio=aac
    cam_parking_enterance_left:
#      - onvif://admin:admin123456@192.168.89.166
      - rtsp://admin:admin123456@192.168.89.166:554/stream1
      - ffmpeg:cam_parking_enterance_left#video=264#hardware#audio=aac
    cam_parking_enterance_right:
#      - onvif://admin:admin123456@192.168.89.167
      - rtsp://admin:admin123456@192.168.89.167:554/stream1
      - ffmpeg:cam_parking_enterance_right#video=264#hardware#audio=aac

cameras:
  cam_parking_enterance_left:
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_parking_enterance_left
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: false
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 3200
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1800
       # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    motion:
      mask:
        - 0.016,0.018,0.265,0.018,0.265,0.071,0.013,0.074
        - 0.246,0.173,0.273,0,0.995,0.003,0.991,0.198,0.766,0.218,0.427,0.184
  cam_parking_enterance_right:
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_parking_enterance_right
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: true
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 3200
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1800
       # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    zones:
      Road:
        coordinates: 0.421,0.436,0.14,0.376,0.109,0.463,0,0.551,0.007,0.994,0.771,0.989,0.806,0.546
        inertia: 3
        loitering_time: 0
      Aside:
        coordinates: 0.143,0.358,0.767,0.514,0.778,0.117,0.55,0.213,0.128,0.238
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.016,0.018,0.265,0.018,0.265,0.071,0.013,0.074
      threshold: 25
      contour_area: 10
      improve_contrast: true
  cam_parking_backyard:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_parking_backyard
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: true
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 2880
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1620
       # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    onvif:
      host: 192.168.89.161
      port: 6688
      user: admin
      password: admin123456
    motion:
      mask:
        - 0.016,0.018,0.265,0.018,0.265,0.071,0.013,0.074
        - 0.207,0.428,0.236,0.337,0.264,0.357,0.287,0.325,0.29,0.289,0.292,0.191,0.294,0.132,0.389,0.134,0.392,0.191,0.408,0.257,0.407,0.303,0.407,0.333,0.443,0.359,0.477,0.321,0.495,0.352,0.498,0.391,0.521,0.404,0.527,0.431,0.52,0.465,0.542,0.492,0.547,0.55,0.537,0.599,0.506,0.653,0.481,0.714,0.463,0.756,0.427,0.817,0.391,0.863,0.34,0.873,0.302,0.868,0.269,0.78,0.264,0.68,0.235,0.633,0.218,0.592,0.18,0.582,0.155,0.511,0.142,0.453,0.196,0.467
  cam_parking_facade:
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_parking_facade
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: true
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 2880
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1620
       # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    onvif:
      host: 192.168.89.162
      port: 6688
      user: admin
      password: admin123456
    motion:
      mask: 0.016,0.018,0.265,0.018,0.265,0.071,0.013,0.074

  cam_veranda:
    ffmpeg:
      hwaccel_args: preset-rk-h264
#      output_args:
#        detect: -r 6 -vf scale_rkrga=w=3200:h=1800:format=yuv420p:force_original_aspect_ratio=0,hwmap=mode=read,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe
#        record: -f segment -segment_time 11 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/cam_veranda@%Y%m%d%H%M%S%z.mp4
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_veranda
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: true
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 2880
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1620
       # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bird
      filters:
        bird:
          min_area: 100
          max_area: 5000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.5
    onvif:
      host: 192.168.89.163
      port: 6688
      user: admin
      password: admin123456
    motion:
      mask: 0.016,0.018,0.265,0.018,0.265,0.071,0.013,0.074
      threshold: 30
      contour_area: 10
      improve_contrast: true

  cam_domushka:
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_domushka
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: true
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 2880
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1620
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    onvif:
      host: 192.168.89.164
      port: 6688
      user: admin
      password: admin123456
    motion:
      mask:
        - 0.432,0.342,0.505,0.338,0.566,0.333,0.648,0.33,0.688,0.32,0.794,0.321,0.825,0.313,0.94,0.318,0.994,0.33,0.989,0.234,0.931,0.008,0.275,0.008,0.285,0.046,0.308,0.047,0.327,0.049,0.389,0.137
        - 0.006,0.228,0.04,0.225,0.076,0.247,0.093,0.311,0.103,0.343,0.103,0.391,0.1,0.442,0.107,0.479,0.144,0.509,0.145,0.577,0.152,0.638,0.153,0.701,0.116,0.77,0.076,0.797,0,0.846
  cam_boilernaya:
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_boilernaya
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
    audio:
      enabled: true
    birdseye:
      enabled: false
    detect:
      enabled: true
      # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
      width: 2880
      # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
      height: 1620
       # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 5
    onvif:
      host: 192.168.89.165
      port: 6688
      user: admin
      password: admin123456
    motion:
      mask: 0.016,0.018,0.265,0.018,0.265,0.071,0.013,0.074



birdseye:
  mode: continuous
  restream: true
  quality: 1
  layout:
    scaling_factor: 1

audio:
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - tire_squeal
    - skidding
    - toot
    - honk
    - car
    - motor_vehicle
    - truck
    - yell
    - scream
    - scratching
    - frog
    - speech
    - vehicle
    - stomach_rumble
    - whoosh
    - explosion
    - roaring_cats
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown be>
  # This can be used to reduce the frequency of deleting recording segments fro>
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: sho>
  sync_recordings: false
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of tracked objec>
    # NOTE: This should be set to 0 and retention should be defined in alerts a>
    #       if you only want to retain recordings of alerts and detections.
    days: 5
    # Optional: Mode for retention. Available options are: all, motion, and act>
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Recording Export Settings
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour p>
    # See https://stackoverflow.com/a/58268695 for more info on how these args >
    # As an example: if you wanted to go from 24 hours to 30 minutes that would>
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.04*PTS -r 30
  # Optional: Recording Preview Settings
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: very_high
  # Optional: alert recording settings

  alerts:
    # Optional: Number of seconds before the alert to include (default: shown b>
    pre_capture: 5
    # Optional: Number of seconds after the alert to include (default: shown be>
    post_capture: 5
    # Optional: Retention settings for recordings of alerts
    retain:
      # Required: Retention days (default: shown below)
      days: 14
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for alerts regardless of activity
      #   motion - save all recordings segments for alerts with any detected mo>
      #   active_objects - save all recording segments for alerts with active/m>
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mo>
      #       here, the segments will already be gone by the time this mode is >
      #       For example, if the camera retain mode is "motion", the segments >
      #       never stored, so setting the mode to "all" here won't bring them >
      mode: all
  # Optional: detection recording settings
  detections:
    # Optional: Number of seconds before the detection to include (default: sho>
    pre_capture: 5
    # Optional: Number of seconds after the detection to include (default: show>
    post_capture: 5
    # Optional: Retention settings for recordings of detections
    retain:
      # Required: Retention days (default: shown below)
      days: 14
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for detections regardless of activi>
      #   motion - save all recordings segments for detections with any detecte>
      #   active_objects - save all recording segments for detections with acti>
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mo>
      #       here, the segments will already be gone by the time this mode is >
      #       For example, if the camera retain mode is "motion", the segments >
      #       never stored, so setting the mode to "all" here won't bring them >
      mode: all
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: sho>
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zone>
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: '%H:%M %d/%m/%Y'


version: 0.16-0
camera_groups:
  BY:
    order: 1
    icon: LuActivitySquare
    cameras: birdseye

face_recognition:
  enabled: false
lpr:
  enabled: false
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped

#    image: ghcr.io/blakeblackshear/frigate:stable-rk
#    image: ghcr.io/blakeblackshear/frigate:stable-h8l
#  ----Custom HAilo
    image: ghcr.io/blakeblackshear/frigate:678ae87
    shm_size: "2048mb" # update for your cameras based on calculation above
    devices:
        - /dev/bus/usb:/dev/bus/usb
        - /dev/hailo0:/dev/hailo0
        - /dev/video0:/dev/video0

        - /dev/dri/renderD128:/dev/dri/renderD128
        - /dev/dri/renderD129:/dev/dri/renderD129
        - /dev/dri/card0:/dev/dri/card0
        - /dev/dri/card1:/dev/dri/card1
```

### Relevant Frigate log output

```shell
2025-05-05 16:18:25.734832039  [INFO] Preparing Frigate...
2025-05-05 16:18:25.953711152  [INFO] Starting Frigate...
2025-05-05 16:18:28.560498855  /usr/local/lib/python3.11/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
2025-05-05 16:18:28.560507897    setattr(self, word, getattr(machar, word).flat[0])
2025-05-05 16:18:28.560760186  /usr/local/lib/python3.11/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
2025-05-05 16:18:28.560762811    return self._float_to_str(self.smallest_subnormal)
2025-05-05 16:18:28.560940142  /usr/local/lib/python3.11/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
2025-05-05 16:18:28.560942475    setattr(self, word, getattr(machar, word).flat[0])
2025-05-05 16:18:28.561039307  /usr/local/lib/python3.11/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
2025-05-05 16:18:28.561041057    return self._float_to_str(self.smallest_subnormal)
2025-05-05 16:18:30.130729101  [2025-05-05 16:18:30] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-05-05 16:18:30.196588161  [2025-05-05 16:18:30] frigate.util.config            INFO    : frigate config does not need migration...
2025-05-05 16:18:30.643958740  [2025-05-05 16:18:30] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2025-05-05 16:18:31.303649462  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2025-05-05 16:32:02.944577093  [2025-05-05 16:32:02] frigate.util.services          WARNING : Did not detect hwaccel, using a GPU for accelerated video decoding is highly recommended
2025-05-05 16:32:02.944577093  [LOGGING] Last message repeated 1 times
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

![Screenshot from 2025-05-05 17-40-10](https://github.com/user-attachments/assets/010a0143-ef72-4c3d-a83a-f22ab1e3f1ea)
![Screenshot from 2025-05-05 17-41-11](https://github.com/user-attachments/assets/df2cb5ac-5cc1-4ad8-9d93-5dca9529568e)
![Screenshot from 2025-05-05 17-41-38](https://github.com/user-attachments/assets/16b0b025-e813-4789-8435-512fc00cdc6e)
