### DISCUSSION TITLE
Any ideas why I'm not getting any detections to show up in the webui?

### DISCUSSION THREAD

**Discussion by NonaSuomy** [blakeblackshear/frigate#18051] [Ask A Question] [answered]
When I click on Explore, it just shows a spinning loading symbol. When I click Export it shows nothing to export. When I click 
Docker YAML
```yaml
# Frigate Container for Docker
# Go here for updated repo numbers: https://github.com/blakeblackshear/frigate/pkgs/container/frigate
services:
  frigate:
    container_name: frigate
    privileged: true
    #restart: "no"
    #restart: "unless-stopped"
    restart: "always"
    #image: ghcr.io/blakeblackshear/frigate:stable
    #image: ghcr.io/blakeblackshear/frigate:4e03efa-rocm # last version of 5.7.3 of ROCM
    image: ghcr.io/blakeblackshear/frigate:9fa2b00
    #image: ghcr.io/harakas/frigate:latest-rocm-gfx900
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri
      - /dev/kfd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker-storage/frigate/config/:/config
      - /opt/docker-storage/frigate:/media/frigate
      #- /opt/docker-storage/frigate:/config/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    hostname: "frigate"
    networks:
      dhcp:
        mac_address: "de:ad:be:ef:ca:fe"
    ports:
      - "8971:8971" # Used for external authenticated UI and API access without TLS. Reverse proxies should use this port.
      - "5000:5000" # WebUI. Internal unauthenticated UI and API access. Access to this port should be limited.
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Birdseye In v 0.12
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      HSA_OVERRIDE_GFX_VERSION: "9.0.0"
      MIGRAPHX_ENABLE_NHWC:	1
      ORTMODULE_LOG_LEVEL: VERBOSE
      #DOWNLOAD_YOLOV8: "1"
      #HCC_SERIALIZE_KERNEL=3
      #HCC_SERIALIZE_COPY=3
      #HSA_ENABLE_SDMA=0
      #HSA_ENABLE_INTERRUPT=0
      #HSA_SVM_GUARD_PAGES=0
      #HSA_DISABLE_CACHE=1

networks:
  dhcp:
    name: dbrv700
    external: true
```

Frigate YAML
```yaml
mqtt:
  host: 10.0.10.60
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: password

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: preset-rtsp-restream
#  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000

go2rtc:
  streams:
    HQFrontYardCam:
      - rtsp://frigate:password@10.0.10.201:554/Streaming/Channels/101/
    HQFrontYardCam_sub:
      - rtsp://frigate:password@10.0.10.201:554/Streaming/Channels/102/
    HQBackYardCam:
      - rtsp://frigate:password@10.0.10.202:554/Streaming/Channels/101/
    HQBackYardCam_sub:
      - rtsp://frigate:password@10.0.10.202:554/Streaming/Channels/102/
    #HQFrontDoorFace: 
    #  - rtsp://10.0.10.204:8554/mjpeg/1

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
  #onnx:
  #  type: onnx
  #onnx_0:
  #  type: onnx
  #onnx_1:
  #  type: onnx
#  cpu1:
#    type: cpu
#    num_threads: 2
#  cpu2:
#    type: cpu
#    num_threads: 2
#  rocm:
#    type: rocm
    # model:
    #   path: /config/model_cache/yolov8/yolov8s_320x320.onnx
  #ov:
  #  type: openvino
  #  device: GPU
  #  device: CPU

#database:

#Global Object Settings
objects:
  track:
    - person
    - dog
    - cat
    - mouse
    - bird
    - car
    - bicycle
    - motorcycle
    - bus
  #filters:
   # person:
     # min_area: 5000
     # max_area: 100000

cameras:
  HQFrontYardCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/HQFrontYardCam
          input_args: preset-rtsp-restream
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://127.0.0.1:8554/HQFrontYardCam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    motion:
      improve_contrast: true
      mask:
        - 214,15,214,31,25,31,25,15
    zones:
      zone_0_front_door:
        coordinates: 463,239,360,238,285,206,292,150,369,62,394,33,476,33
      zone_0_Driveway:
        coordinates: 385,228,79,147,204,77,396,64
    objects:
      filters:
        person:
          mask: 0.724,0.479,0.562,0.496,0.445,0.429,0.456,0.312,0.615,0.071,0.743,0.069

  HQBackYardCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/HQBackYardCam
          input_args: preset-rtsp-restream
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://127.0.0.1:8554/HQBackYardCam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10

birdseye:
  enabled: true
  restream: false
  width: 1280
  height: 720
  quality: 1
  mode: objects

live:
  height: 640
  quality: 1

version: 0.16-0

semantic_search:
  enabled: false
  model_size: small

face_recognition:
  enabled: true
  model_size: small

lpr:
  enabled: false

classification:
  bird:
    enabled: false
    
 Startup log
 ```yaml
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service certsync-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service certsync-log successfully started
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service prepare successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2025-05-05 11:21:16.297181062  [INFO] Preparing Frigate...
2025-05-05 11:21:16.299261177  [INFO] Starting NGINX...
2025-05-05 11:21:16.755546336  [INFO] Preparing new go2rtc config...
2025-05-05 11:21:16.897717431  [INFO] Starting Frigate...
2025-05-05 11:21:17.232662714  [INFO] Starting go2rtc...
2025-05-05 11:21:17.269406182  2025/05/05 11:21:17 [error] 185#185: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.10.144, server: , request: "GET /ws HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "10.0.10.53:5000"
2025-05-05 11:21:17.269430361  2025/05/05 11:21:17 [error] 185#185: *1 auth request unexpected status: 502 while sending to client, client: 10.0.10.144, server: , request: "GET /ws HTTP/1.1", host: "10.0.10.53:5000"
2025-05-05 11:21:17.269481024  10.0.10.144 - - [05/May/2025:11:21:17 -0400] "GET /ws HTTP/1.1" 500 579 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"
2025-05-05 11:21:17.311455082  11:21:17.311 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
2025-05-05 11:21:17.311475361  11:21:17.311 INF config path=/dev/shm/go2rtc.yaml
2025-05-05 11:21:17.311956452  11:21:17.311 INF [rtsp] listen addr=:8554
2025-05-05 11:21:17.311979235  11:21:17.311 INF [api] listen addr=:1984
2025-05-05 11:21:17.312360561  11:21:17.312 INF [webrtc] listen addr=:8555
s6-rc: info: service nginx successfully started
s6-rc: info: service certsync: starting
s6-rc: info: service certsync successfully started
s6-rc: info: service legacy-services: starting
2025-05-05 11:21:17.928816819  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
2025-05-05 11:21:18.283565833  2025/05/05 11:21:18 [error] 186#186: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.10.52, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "10.0.10.53:5000"
2025-05-05 11:21:18.283591579  2025/05/05 11:21:18 [error] 186#186: *3 auth request unexpected status: 502 while sending to client, client: 10.0.10.52, server: , request: "GET /api/stats HTTP/1.1", host: "10.0.10.53:5000"
2025-05-05 11:21:18.425513767  127.0.0.1 - - [05/May/2025:11:21:18 -0400] "" 400 0 "-" "-" "-"
2025-05-05 11:21:19.239080739  [2025-05-05 11:21:19] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-05-05 11:21:19.258756218  [2025-05-05 11:21:19] frigate.util.config            INFO    : frigate config does not need migration...
2025-05-05 11:21:19.287894446  [2025-05-05 11:21:19] frigate.app                    INFO    : Starting Frigate (0.16.0-9fa2b00)
2025-05-05 11:21:19.294682178  [2025-05-05 11:21:19] peewee_migrate.logs            INFO    : Starting migrations
2025-05-05 11:21:19.451077361  [2025-05-05 11:21:19] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-05-05 11:21:19.479070465  [2025-05-05 11:21:19] frigate.app                    INFO    : Recording process started: 384
2025-05-05 11:21:19.481236893  [2025-05-05 11:21:19] frigate.app                    INFO    : Review process started: 392
2025-05-05 11:21:19.486275339  [2025-05-05 11:21:19] frigate.app                    INFO    : go2rtc process pid: 123
2025-05-05 11:21:19.498759249  [2025-05-05 11:21:19] detector.ov_0                  INFO    : Starting detection process: 406
2025-05-05 11:21:19.506821374  [2025-05-05 11:21:19] detector.ov_1                  INFO    : Starting detection process: 408
2025-05-05 11:21:19.514225712  [2025-05-05 11:21:19] frigate.app                    INFO    : Embedding process started: 410
2025-05-05 11:21:19.533068816  [2025-05-05 11:21:19] frigate.app                    INFO    : Output process started: 444
2025-05-05 11:21:19.566150550  loading data from : /config/model_cache/facedet/landmarkdet.yaml
2025-05-05 11:21:19.871977736  [2025-05-05 11:21:19] frigate.app                    INFO    : Camera processor started for HQFrontYardCam: 473
2025-05-05 11:21:19.872650905  [2025-05-05 11:21:19] frigate.app                    INFO    : Camera processor started for HQBackYardCam: 481
2025-05-05 11:21:19.895559105  [2025-05-05 11:21:19] frigate.app                    INFO    : Capture process started for HQFrontYardCam: 501
2025-05-05 11:21:19.906578844  [2025-05-05 11:21:19] frigate.app                    INFO    : Capture process started for HQBackYardCam: 511
2025-05-05 11:21:20.079866317  [2025-05-05 11:21:20] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-05-05 11:21:20.351678024  [2025-05-05 11:21:20] frigate.api.fastapi_app        INFO    : FastAPI started
2025-05-05 11:21:20.889243061  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2025-05-05 11:21:26.298057367  [INFO] Starting go2rtc healthcheck service...
2025-05-05 11:22:18.560992110  127.0.0.1 - - [05/May/2025:11:22:18 -0400] "" 400 0 "-" "-" "-"
2025-05-05 11:28:54.377399310  10.0.10.144 - - [05/May/2025:11:28:54 -0400] "GET /api/profile HTTP/1.1" 200 39 "http://10.0.10.53:5000/explore" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"



05 11:28:54.385113038  10.0.10.144 - - [05/May/2025:11:28:54 -0400] "GET /api/config HTTP/1.1" 200 21684 "http://10.0.10.53:5000/explore" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"

2025-05-05 11:28:54.389469226  10.0.10.144 - - [05/May/2025:11:28:54 -0400] "GET /api/profile HTTP/1.1" 200 39 "http://10.0.10.53:5000/explore" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"

2025-05-05 11:29:07.089250443  10.0.10.144 - - [05/May/2025:11:29:07 -0400] "GET /api/profile HTTP/1.1" 200 39 "http://10.0.10.53:5000/explore" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"



05 11:29:07.098373931  10.0.10144 - - [05/May/2025:11:29:07 -0400] "GET /api/config HTTP/1.1" 200 21684 "http://10.0.10.53:5000/explore" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"

2025-05-05 11:29:07.248028909  10.0.10.144 - - [05/May/2025:11:29:07 -0400] "GET /api/exports HTTP/1.1" 200 2 "http://10.0.10.53:5000/export" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"
```

I tried moving my database to a .bak file in case there was just something wrong with it and recreated it from scratch. Not sure what it's doing.

![image](https://github.com/user-attachments/assets/cc13702f-1e04-439d-8f6d-55ceaf26a21b)

If I click on motion there, it shows the two camera feeds and all the motions fine just no detections.

These files seem to exist in the docker:

```
root@frigate:/openvino-model# ls -lah
total 9.0M
drwxr-xr-x 2 root root 4.0K Apr 28 23:05 .
drwxr-xr-x 1 root root 4.0K May  5 10:57 ..
-rw-r--r-- 1 root root  715 Apr 28 23:05 coco_91cl_bkgr.txt
-rw-r--r-- 1 root root 8.6M Apr 28 23:05 ssdlite_mobilenet_v2.bin
-rw-r--r-- 1 root root 440K Apr 28 23:05 ssdlite_mobilenet_v2.xml
root@frigate:/openvino-model# 
```

This looks a little strange, I would expect to see different timings not just 10ms across the board.
![image](https://github.com/user-attachments/assets/daa536af-b455-44bc-a3d3-7628940d580f)
Plenty of space:
![image](https://github.com/user-attachments/assets/e64b5553-1656-4ab1-8678-49259f57ce44)
