### DISCUSSION TITLE
Timeline Camera selection not honored on page refresh.

### DISCUSSION THREAD

**Discussion by mattridrm** [blakeblackshear/frigate#18062] [General Support] [answered]
### Describe the problem you are having

On the camera History page you can select the cameras that you would like to view along with the current camera. When leaving the History page and returning to view it again all cameras are selected as default.  Is this a bug?

I would believe that once a selection is made on the History page the selection should be honored for further views. This would cut down on the bandwidth required especially in bandwidth challenged installations.

### Version

0.16.0-beta1

### Frigate config file

```yaml
mqtt:
  enabled: false

tls:
  enabled: false

go2rtc:
  streams:
    Side-Yard-Record: rtsp://admin:xxxxxxx@192.168.1.65:554/Streaming/channels/101
    Side-Yard-Detect: rtsp://admin:xxxxxxx@192.168.1.65:554/Streaming/channels/102
    Side-Yard: rtsp://admin:xxxxxxx@192.168.1.65:554/Streaming/channels/103


    Front-Yard-Record: rtsp://admin:xxxxxxxx@192.168.1.64:554/Streaming/channels/101
    Front-Yard: rtsp://admin:xxxxxxxxx@192.168.1.64:554/Streaming/channels/102

  webrtc:
    candidates:
      - 192.168.1.6:8555
      - stun:8555
detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
  ov_2:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

cameras:
  Side-Yard: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Side-Yard-Detect # <----- The stream you want to use for detection
          input_args: -loglevel error -hwaccel vaapi -vaapi_device /dev/dri/renderD129
            -hwaccel_output_format vaapi -c:v hevc
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Side-Yard-Record
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    live:
      streams:
        Side-Yard: Side-Yard
    motion:
      mask: 0.017,0.046,0.017,0.101,0.316,0.101,0.316,0.046
  Front-Yard: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front-Yard # <----- The stream you want to use for detection
          input_args: -loglevel error -hwaccel vaapi -vaapi_device /dev/dri/renderD129
            -hwaccel_output_format vaapi -c:v hevc
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front-Yard-Record
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

    motion:
      mask: 0.022,0.003,0.021,0.036,0.267,0.043,0.263,0
version: 0.16-0
camera_groups:
  Exterior:
    order: 1
    icon: LuAirplay
    cameras:
      - Side-Yard
      - Front-Yard
detect:
  enabled: true
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Frigate stats

```json
None
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
None
```

### Object Detector

OpenVino

### Network connection

Mixed

### Camera make and model

Hikvision
