### DISCUSSION TITLE
upgrade to 0.15.1 failed for interphone camera  (it was working properly in 0.14)

### DISCUSSION THREAD

**Discussion by bend94** [blakeblackshear/frigate#18075] [Ask A Question]
hi,

I have serevals cameras under frigate
here is my frigate.yml file

```
logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.stream: debug

mqtt:
  host: 192.168.1.22
  port: 1883
  topic_prefix: frigate
  user: umqtt
  password: pass4UMQTT


detectors:
  coral:
    type: edgetpu
    device: usb
  #cpu1:
  #  type: cpu
#    num_threads: 4
  #cpu2:
  #  type: cpu

go2rtc:
  streams:
    devant:
      - rtsp://test:PWD@192.168.1.200:554/Streaming/Channels/101/
    devant_sub:
      - rtsp://test:PWD@192.168.1.200:554/Streaming/Channels/102/
    interphone:
      - ffmpeg:rtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp
    inter:
      - ffmpeg:rtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp
    terrasse_sub:
      - rtsp://test:PWD@192.168.1.202:554/Streaming/Channels/102/
    terrasse:
      - rtsp://test:PWD@192.168.1.202:554/Streaming/Channels/101/
    salon_sub:
      - rtsp://test:PWD@192.168.1.201:554/Streaming/Channels/102/
    salon:
      - rtsp://test:PWD@192.168.1.201:554/Streaming/Channels/101/
    cuisine_sub:
      - rtsp://test:PWD@192.168.1.203:554/Streaming/Channels/102/
    cuisine:
      - rtsp://test:PWD@192.168.1.203:554/Streaming/Channels/101/
    bureau_sub:
      - rtsp://test:PWD@192.168.1.205:554/Streaming/Channels/102/
    bureau:
      - rtsp://test:PWD@192.168.1.205:554/Streaming/Channels/101/
    couloir_sub:
      - rtsp://test:PWD@192.168.1.204:554/Streaming/Channels/102/
    couloir:
      - rtsp://test:PWD@192.168.1.204:554/Streaming/Channels/101/


  snapshots:
    timestamp: true
    bounding_box: true
    quality: 100

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

birdseye:
  enabled: true
#  width: 896
#  height: 672
  width: 1920
  height: 1080

  quality: 1
  mode: continuous


cameras:
  terrasse:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrasse_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/terrasse
          #input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
        #- dog
        #- cat
    motion:
      mask:
        - 287,159,298,33,320,0,320,240,252,240
        - 0,0,299,0,172,25,153,39,60,65,0,109
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_terrasse_alarme:
        coordinates: 
          0.658,0.203,0.573,0.215,0.399,0.267,0.26,0.311,0.105,0.444,0.098,0.57,0.007,0.82,0.008,0.961,0.008,1,0.777,0.995,0.884,0.663,0.899,0.493,0.911,0.35,0.909,0.273,0.84,0.205,0.774,0.182,0.715,0.166

  interphone:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/inter
          #input_args: preset-rpi-64-h264
          input_args: -rtsp_transport tcp
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/inter
          #input_args: preset-rpi-64-h264
          input_args: -rtsp_transport tcp
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - horse
        - bicycle
        - motorcycle
      filters:
        car:
          mask:
            - 0,0,320,0,320,107,0,109
        person:
          mask:
            - 0,0,320,0,320,107,0,109
        dog:
          mask:
            - 0,0,320,0,320,107,0,109
        cat:
          mask:
            - 0,0,320,0,320,107,0,109
    motion:
      mask:
        - 0,0,192,0,320,0,320,138,170,151,50,142,0,132
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      quality: 100
      retain:
        default: 5
        mode: motion

  devant:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/devant_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/devant
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 2
    objects:
      track:
        - person
    motion:
      mask:
        - 62,480,24,305,85,243,164,196,302,193,547,202,640,263,640,0,159,0,0,0,0,112,0,240,0,480
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      required_zones:
        - zone_devant_alarme
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_devant_alarme:
        coordinates: 130,209,22,229,64,470,632,472,629,232,300,207
  cuisine:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cuisine_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cuisine
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
        - 162,159,159,0,320,0,320,240,83,240,161,240
        - 0,0,113,0,105,45,72,73,0,109
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_cuisine_alarme:
        coordinates: 0.005,0.996,0.002,0.456,0.36,0.156,0.49,0.156,0.496,0.992
  salon:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/salon_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/salon
          roles:
            - record
    detect:
      width: 640 #320
      height: 480 #240
      fps: 4
    objects:
      track:
        - person
      #  - dog
      #  - cat
    motion:
      threshold: 40
      mask:
        - 640,480,640,0,555,0,554,63,496,480
        - 359,0,342,0,217,0,117,0,0,0,0,350,98,260,214,212,212,145,213,52,557,59,550,0
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_salon_alarme:
        coordinates: 13,468,12,243,72,211,210,153,210,77,339,74,375,146,475,158,483,57,556,69,502,468
  bureau:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bureau_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/bureau
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask: 0,0,1,0,1,0.258,1,0.721,0.678,0.562,0.531,0.475,0.429,0.459,0.401,1,0,1
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_bureau_alarme:
        coordinates: 0.42,0.992,0.429,0.56,0.521,0.559,0.986,0.992

  couloir:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/couloir_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/couloir
          roles:
            - record
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
        - 320,0,0,0,0,83,108,47,255,49,320,240
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
        mode: motion
    zones:
      zone_couloir_alarme:
        coordinates: 0.409,0.989,0.304,0.539,0.331,0.205,0.787,0.21,0.982,0.995

version: 0.14
```

When i upgrade to 0.15 or 0.15.1 i catch this error for interphone camera (it was working in 0.14)

```


2025-05-06 13:34:53.610965770  [INFO] Starting certsync...
s6-rc: info: service legacy-services successfully started
2025-05-06 13:34:53.795023824  127.0.0.1 - - [06/May/2025:15:34:53 +0200] "" 400 0 "-" "-" "-"
2025-05-06 13:34:54.062526714  [2025-05-06 15:34:54] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-05-06 13:34:54.132684078  [2025-05-06 15:34:54] frigate.util.config            INFO    : frigate config does not need migration...
2025-05-06 13:34:55.237865374  2025/05/06 15:34:55 [error] 187#187: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
2025-05-06 13:34:55.237872485  2025/05/06 15:34:55 [error] 187#187: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
2025-05-06 13:34:55.282878434  2025/05/06 15:34:55 [error] 188#188: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "ccab4aaf-frigate:5000"
2025-05-06 13:34:55.282886304  2025/05/06 15:34:55 [error] 188#188: *4 auth request unexpected status: 502 while sending to client, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", host: "ccab4aaf-frigate:5000"
2025-05-06 13:34:55.752182587  15:34:55.751 WRN [rtsp] error="streams: exec: [rtsp @ 0x557ed3be60] Unable to open RTSP for listening\nrtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=inter
2025-05-06 13:34:55.793147741  [2025-05-06 15:34:55] frigate.video                  ERROR   : interphone: Unable to read frames from ffmpeg process.
2025-05-06 13:34:55.805979771  [2025-05-06 15:34:55] frigate.video                  ERROR   : interphone: ffmpeg process is not running. exiting capture thread...
2025-05-06 13:34:55.876013432  15:34:55.875 WRN [rtsp] error="streams: exec: [rtsp @ 0x5596f1ae60] Unable to open RTSP for listening\nrtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=inter
2025-05-06 13:35:00.162317744  [INFO] Starting go2rtc healthcheck service...
2025-05-06 13:35:14.936409287  [2025-05-06 15:35:14] watchdog.interphone            ERROR   : Ffmpeg process crashed unexpectedly for interphone.
2025-05-06 13:35:14.937856668  [2025-05-06 15:35:14] watchdog.interphone            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-05-06 13:35:14.937913279  [2025-05-06 15:35:14] ffmpeg.interphone.detect       ERROR   : [rtsp @ 0x55a142ce00] method DESCRIBE failed: 404 Not Found
2025-05-06 13:35:14.938199519  [2025-05-06 15:35:14] ffmpeg.interphone.detect       ERROR   : rtsp://127.0.0.1:8554/inter: Server returned 404 Not Found
2025-05-06 13:35:14.984815422  [2025-05-06 15:35:14] ffmpeg.interphone.record       ERROR   : [rtsp @ 0x557327ce30] method DESCRIBE failed: 404 Not Found
2025-05-06 13:35:14.984890940  [2025-05-06 15:35:14] ffmpeg.interphone.record       ERROR   : rtsp://127.0.0.1:8554/inter: Server returned 404 Not Found
2025-05-06 13:35:15.205653461  15:35:15.205 WRN [rtsp] error="streams: exec: [rtsp @ 0x55a5db2e60] Unable to open RTSP for listening\nrtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=inter
2025-05-06 13:35:15.219078470  [2025-05-06 15:35:15] frigate.video                  ERROR   : interphone: Unable to read frames from ffmpeg process.
2025-05-06 13:35:15.219135933  [2025-05-06 15:35:15] frigate.video                  ERROR   : interphone: ffmpeg process is not running. exiting capture thread...
2025-05-06 13:35:15.319211743  15:35:15.319 WRN [rtsp] error="streams: exec: [rtsp @ 0x5594c13e60] Unable to open RTSP for listening\nrtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=inter
2025-05-06 13:35:17.672671597  15:35:17.672 WRN [rtsp] error="streams: exec: [rtsp @ 0x55b7477e60] Unable to open RTSP for listening\nrtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=interphone
2025-05-06 13:35:25.008162101  [2025-05-06 15:35:24] watchdog.interphone            ERROR   : Ffmpeg process crashed unexpectedly for interphone.
2025-05-06 13:35:25.008614821  [2025-05-06 15:35:24] watchdog.interphone            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-05-06 13:35:25.008678043  [2025-05-06 15:35:24] ffmpeg.interphone.detect       ERROR   : [rtsp @ 0x5593ef4e00] method DESCRIBE failed: 404 Not Found
2025-05-06 13:35:25.008737432  [2025-05-06 15:35:24] ffmpeg.interphone.detect       ERROR   : rtsp://127.0.0.1:8554/inter: Server returned 404 Not Found
2025-05-06 13:35:25.032948629  [2025-05-06 15:35:25] ffmpeg.interphone.record       ERROR   : [rtsp @ 0x5563b33e30] method DESCRIBE failed: 404 Not Found
2025-05-06 13:35:25.033536923  [2025-05-06 15:35:25] ffmpeg.interphone.record       ERROR   : rtsp://127.0.0.1:8554/inter: Server returned 404 Not Found
2025-05-06 13:35:25.245227487  15:35:25.245 WRN [rtsp] error="streams: exec: [rtsp @ 0x558190de60] Unable to open RTSP for listening\nrtsp://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=inter
2025-05-06 13:35:25.253531391  [2025-05-06 15:35:25] frigate.video                  ERROR   : interphone: Unable to read frames from ffmpeg process.
2025-05-06 13:35:25.253536465  [2025-05-06 15:35:25] frigate.video                  ERROR   : interphone: ffmpeg process is not running. exiting capture thread...
2025-05-06 13:35:25.355558117  15:35:25.355 WRN [rtsp] error="streams: exec: [rtsp @ 0x5569057e60] Unable to open RTSP for listening\nrts
```p://ghnfij0002:PWD@192.168.1.173:554/mpeg/media.amp: Cannot assign requested address\n" stream=inter

Can you please help me ?
thx
