### DISCUSSION TITLE
[Detector Support]: High CPU usage using Vino, unable to see GPU usage.

### DISCUSSION THREAD

**Discussion by PapayaPlant** [blakeblackshear/frigate#18089] [Detector Support]
### Describe the problem you are having

I am not sure if the GPU is actually working in the processing of detection. I have the observed screenshot from my dashboard.
![SCR-20250507-itdv](https://github.com/user-attachments/assets/de6d0c48-898c-4286-8df5-371973b77330)

I am using a Beelink EQi12 with the i5 CPU with Debian 12 and Docker Engine (following the install off the Frigate Wiki).

I have video feeds and detection working all working & it all feeding into Home Assistant. This was before looking at hardware acceleration and openvino, it still is working with the configs below.

I am trying to verify if the integrated GPU is working in the system and chatGPT told me to run:

`clinfo | grep -i platform`

In response I get:

`Number of platforms                               0`

From what I have seen on other's setups, they seem to have this section being populated.

Detector.ov seems to be working from the logs, but I am just not seeing the GPU or any mention of openvino or the models loading.

Now, I am not sure if I am being stupid in the as it's an iGPU on the CPU is this data just not coming through because of that & it is working fine? 

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.XX
  port: 1883
  user: frigate
  password: PASSWORD

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: -c:v h264_qsv

cameras:
  channel1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.1.XX:554/ch01/0
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - pet
        - cat

    zones:
      CallyBackDoor:
        coordinates: 0.417,0.204,0.457,0.995,0.705,0.998,0.572,0.114,0.419,0.138
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: CallyBackDoor
  channel2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.1.XX:554/ch02/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - pet
        - cat

  channel3:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.1.XX:554/ch03/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - pet
        - cat
        - dog
    review:
      alerts:
        required_zones:
          - FrontDoorDetection
          - DogPooping
    zones:
      FrontDoorDetection:
        coordinates: 
          0.008,0.495,0.185,0.337,0.2,0.262,0.341,0.177,0.514,0.363,0.714,0.488,0.853,0.634,0.935,0.711,0.869,0.991,0.724,0.993,0.399,0.996,0.138,0.998,0.022,0.608
        loitering_time: 0
        objects: person
      DogPooping:
        coordinates: 0.714,0.165,0.636,0.249,0.974,0.451,0.987,0.297
        loitering_time: 20
        objects: dog
        inertia: 3
  channel4:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.1.XX:554/ch04/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - pet
        - cat

version: 0.15.1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:5000"        # Expose Frigate's web interface
      - "8554:8554"        # RTSP feeds
      - "8555:8555/tcp"    # WebRTC over TCP
      - "8555:8555/udp"    # WebRTC over UDP
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD" # Set a password for Frigate's web UI
      FRIGATE_HOST: "192.168.1.XX"
```

### Relevant Frigate log output

```shell
No error logs, logs just show get commands for the cameras. Only error I had was this when testing config setups, but it no longer shows:

2025-05-06 16:16:30
Tag
frigate.util.services
Message
Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![SCR-20250507-jdaz](https://github.com/user-attachments/assets/ba19d8a7-31a0-4b05-ad08-3167d2d773c4)
![SCR-20250507-jdeb](https://github.com/user-attachments/assets/2e774872-d84b-4cf6-a467-911620fe05cb)
![SCR-20250507-itdv](https://github.com/user-attachments/assets/8eeb9585-e7e5-44e1-9772-3d4990d980b5)

### Any other information that may be helpful

I have asked on Reddit and got some help, and told to check the below which appears to show it running. 

Was just hoping to see if I can get GPU stats in the UI or if there is anything more I can do as I have only recently noticed the higher CPU usage in the UI.

![image](https://github.com/user-attachments/assets/02f281e5-5cfa-4e4f-b076-3cf9a5f28584)
