### DISCUSSION TITLE
Nvidia vs CPU

### DISCUSSION THREAD

**Discussion by DrSpaldo** [blakeblackshear/frigate#1808] [Ask A Question] [answered]
I have been running Frigate from the 0.8 versions through to the 0.9 RC versions in CPU mode. Although I have a Nvidia GTX 1050 in the machine. I haven't had the time to test the Nvidia version due to time, but, would like to in the near future. Previously in the 0.8 versions I had 24/7 recording & clips enabled. Since the new changes of just recording & clips being sourced from them, will this make any more/less difference using the Nvidia version?

I currently use the following ffmpeg args for all my cameras:

```
ffmpeg:
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    rtmp: -c copy -f flv

    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
```

I hope this makes sense :)

**Comment by blakeblackshear** [comment]
Nothing about 0.9.0 should change anything here.

**Reply by DrSpaldo** [reply]
Thanks. Will the nvidia version/cars reduce the cpu usage?

**Reply by blakeblackshear** [reply]
It would only reduce the CPU utilization of the ffmpeg process that decodes the video stream.

**Comment by DrSpaldo** [comment, marked as answer]
I wish I totally understood the difference between what the CPU does when the GPU is present. I've read the docs, threads and checked out the various diagrams, it still doesn't stink in for me.

I have had the chance today to switch over to the Nvidia version of Frigate and I am getting some usage on my GPU. I just don't know if I am totally taking advantage or not.

The config docs for the non-nvidia differ from the nvidia. The [non-nvidia](https://blakeblackshear.github.io/frigate/configuration/optimizing) uses **hwaccel_args:** where the [nvidia docs](https://blakeblackshear.github.io/frigate/configuration/nvdec) say to use **input_args:**

As I followed the docs, this is my current input & output args:


```
  frontdoor:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
```

```
ffmpeg:
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    rtmp: -c copy -f flv
```

Have I interpreted this correctly?
