### DISCUSSION TITLE
[Camera Support]: 0.16 occasionally generating corrupted detect streams

### DISCUSSION THREAD

**Discussion by ProsjektX** [blakeblackshear/frigate#18080] [Camera Support]
### Describe the problem you are having

Streams can run for a couple of days and then suddenly start showing heavily corrupted images, so the detector goes bananas. The original camera streams, which the detect stream is based off, look perfectly fine in live view though.

Anyone got an idea what is going on, and how to fix this more permanently than frequent reboots, as a reboot always returns the system to normal?

My cameras are 3 different types of Dahuas with H265 streams, and it has happened with at least two different types.

Snapshot from video:
![image](https://github.com/user-attachments/assets/49871bda-0e08-48aa-a3b2-5778d27504a3)

Video sample taken from the Debug view below:
https://github.com/user-attachments/assets/2ab4af16-e256-4e05-9b44-560be9d61cfb

### Version

0.16.0-895afcd

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.ptz.onvif: debug
mqtt:
  enabled: true
  host: 192.168.1.100
  port: 1883
  client_id: frigate
  user: xxx
  password: xxx
semantic_search:
  enabled: true
  model_size: large
  reindex: false
classification:
  bird:
    enabled: true
detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU
model:
  path: 'plus://xxx'
audio:
  enabled: false
birdseye:
  enabled: false
ui:
  time_format: 24hour
objects:
  track:
    - bicycle
    - bird
    - car
    - cat
    - deer
    - dog
    - face
    - fox
    - license_plate
    - motorcycle
    - package
    - person
    - postnord
    - rabbit
    - squirrel
    - waste_bin
  filters:
    person:
      min_area: 850
      max_area: 700000
      min_score: 0.5
      threshold: 0.7
    bird:
      min_score: 0.68
      threshold: 0.78
    bicycle:
      min_score: 0.68
      threshold: 0.78
    car:
      min_score: 0.65
      threshold: 0.75
    dog:
      min_ratio: 0.5
      max_ratio: 2.5
      min_score: 0.65
      threshold: 0.72
    deer:
      min_ratio: 0.5
      max_ratio: 2.5
      min_score: 0.65
      threshold: 0.72
review:
  alerts:
    labels:
      - car
      - person
      - package
  detections:
    labels:
      - car
      - person
      - bicycle
      - bird
      - cat
      - deer
      - dog
      - face
      - fox
      - license_plate
      - motorcycle
      - postnord
      - rabbit
      - squirrel
      - waste_bin
snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  quality: 92
  retain:
    default: 180
    objects:
      person: 180
ffmpeg:
  hwaccel_args: preset-intel-qsv-h265
  apple_compatibility: true
  output_args:
    record: preset-record-generic
detect:
  fps: 5
  enabled: true
go2rtc:
  streams:
    Garasje_HQ:
      - >-
        rtsp://xxx:xxx@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
    Bakside_HQ:
      - >-
        rtsp://xxx:xxx@192.168.1.108:554/cam/realmonitor?channel=2&subtype=0
    Trampoline_HQ:
      - >-
        rtsp://xxx:xxx@192.168.1.108:554/cam/realmonitor?channel=3&subtype=0
    Inngangsparti_HQ:
      - >-
        rtsp://xxx:xxx@192.168.1.108:554/cam/realmonitor?channel=4&subtype=0
record:
  enabled: true
  preview:
    quality: high
  expire_interval: 1440
  retain:
    days: 180
    mode: motion
  export:
    timelapse_args: '-vf setpts=PTS/1440 -r 30'
  alerts:
    retain:
      days: 270
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 270
    pre_capture: 5
    post_capture: 5
cameras:
  Inngangsparti:
    enabled: true
    live:
      streams:
        Inngangsparti_HQ: Inngangsparti_HQ
    ui:
      order: 1
    detect:
      fps: 10
      annotation_offset: -750
      width: 1088
      height: 1920
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/Inngangsparti_HQ'
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    motion:
      mask:
        - >-
          0,0.081,0.382,0.053,0.445,0.03,0.488,0.108,0.664,0.108,0.641,0.333,1,0.59,1,0,0,0
        - >-
          0.179,0.104,0.13,0.116,0.104,0.141,0.118,0.162,0.172,0.174,0.22,0.173,0.273,0.161,0.304,0.146,0.311,0.117,0.26,0.101
      threshold: 35
      contour_area: 15
      improve_contrast: true
    zones:
      Gate:
        coordinates: '0.516,0.099,0.654,0.096,0.638,0.085,0.502,0.087'
        distances: '3.16,3.75,3.16,3.75'
        speed_threshold: 10
        loitering_time: 0
        objects:
          - bicycle
          - car
          - motorcycle
          - person
        inertia: 1
      Innkjoring:
        coordinates: '0.444,0.284,0.643,0.263,0.664,0.108,0.513,0.11,0.525,0.122,0.31,0.163'
        loitering_time: 0
        objects:
          - bicycle
          - car
          - person
          - bird
          - cat
          - deer
          - fox
          - rabbit
          - squirrel
        inertia: 3
      Inngangsdor:
        coordinates: '0.638,0.392,0.098,0.46,0.165,0.661,0.314,1,1,1,1,0.653'
        loitering_time: 0
        objects:
          - person
          - package
        inertia: 3
    review:
      alerts:
        required_zones: Inngangsdor
      detections: {}
    objects:
      filters:
        person: {}
      mask: '0.487,0.106,0.664,0.111,0.663,0.03,0.445,0.03'
  Garasje:
    enabled: true
    live:
      streams:
        Garasje_HQ: Garasje_HQ
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/Garasje_HQ'
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - '0.836,0.996,0.836,0.953,0.999,0.954,1,1'
        - >-
          1,0.379,0.875,0.319,0.876,0.346,0.832,0.333,0.838,0.198,0.813,0.19,0.805,0.326,0.73,0.306,0.735,0.167,0.689,0.149,0.677,0.278,0.58,0.272,0.587,0.113,0.53,0.098,0.527,0.149,0,0.189,0,0,1,0
      threshold: 36
      contour_area: 15
      improve_contrast: true
    zones:
      Innkjoring:
        coordinates: >-
          0.484,0.412,0.136,0.455,0.132,0.331,0.037,0.338,0,0.358,0.001,0.996,0.368,0.996,0.564,0.511
        loitering_time: 0
        objects:
          - bicycle
          - car
          - motorcycle
          - person
          - dog
        inertia: 3
      Hage:
        coordinates: >-
          0.874,0.386,0.877,0.326,0.951,0.362,1,0.389,0.999,0.995,0.372,1,0.573,0.508,0.518,0.449,0.926,0.415
        loitering_time: 0
        objects:
          - person
          - cat
          - dog
        inertia: 3
    review:
      alerts:
        required_zones: Innkjoring
    objects:
      filters:
        car:
          mask:
            - '0.119,0.356,0,0.37,0,0,0.126,0'
            - '0.138,0.33,0.366,0.311,0.371,0.142,0.138,0.152'
        bicycle:
          mask:
            - '0.135,0.329,0.365,0.307,0.368,0.139,0.141,0.149'
            - '0.113,0.357,0.112,0.1,0,0.142,0,0.376'
        person:
          mask:
            - '0.578,0.272,0.675,0.297,0.686,0.169,0.585,0.139'
            - '0.73,0.306,0.805,0.326,0.809,0.226,0.736,0.19'
  Bakside:
    enabled: true
    live:
      streams:
        Bakside_HQ: Bakside_HQ
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/Bakside_HQ'
          roles:
            - record
            - detect
    detect:
      width: 1620
      height: 950
    onvif:
      host: 192.168.1.108
      port: 10080
      user: admin
      password: Passord1
    review:
      alerts:
        labels:
          - person
          - face
        required_zones: Hage
      detections:
        labels:
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - rabbit
          - squirrel
    motion:
      threshold: 30
      contour_area: 15
      improve_contrast: true
      mask: >-
        0.223,1,0.174,0.519,0.17,0.232,0.198,0.215,0.191,0.128,0.203,0.123,0.196,0.056,0.178,0.046,0.177,0.024,0.264,0.017,0.45,0.14,0.654,0.3,1,0.696,1,0,0,0,0,1
    zones:
      Hage:
        coordinates: '0,1,1,1,1,0.489,0.679,0.188,0.307,0,0.144,0,0,0.834'
        loitering_time: 0
        inertia: 3
  Trampoline:
    enabled: true
    live:
      streams:
        Trampoline_HQ: Trampoline_HQ
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/Trampoline_HQ'
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
    review:
      alerts:
        labels:
          - person
          - face
        required_zones: Hage
      detections:
        labels:
          - bicycle
          - bird
          - cat
          - deer
          - dog
          - fox
          - rabbit
          - squirrel
    motion:
      mask: >-
        0,0.354,0.08,0.256,0.525,0.194,0.765,0.24,0.772,0.29,0.881,0.282,0.999,0.341,1,0,0,0
      threshold: 35
      contour_area: 25
      improve_contrast: true
    zones:
      Hage:
        coordinates: >-
          0.619,0.409,0.437,0.491,0,0.656,0.003,0.992,0.889,1,1,0.713,1,0.375,0.891,0.331,0.797,0.334
        loitering_time: 0
        inertia: 3
        objects:
          - deer
          - person
          - rabbit
          - fox
          - bicycle
      friomraade:
        coordinates: '0,0.354,0,0.605,0.76,0.322,0.765,0.24,0.517,0.195,0.08,0.256'
        loitering_time: 0
        objects:
          - deer
          - person
          - dog
          - fox
          - rabbit
          - bicycle
    objects:
      filters:
        person: {}
        bicycle: {}
      mask: '0,0.331,0.221,0.209,0.532,0.194,1,0.341,1,0.01,0.002,0'
version: 0.16-0
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
```

### Relevant Frigate log output

```shell
2025-05-05 17:42:15.090863903  You have successfully opted out to send the telemetry data.
2025-05-05 17:42:15.099211721  [INFO] Preparing Frigate...
2025-05-05 17:42:15.436804735  [INFO] Starting Frigate...
2025-05-05 17:42:17.485900524  [2025-05-05 17:42:17] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-05-05 17:42:17.520523424  [2025-05-05 17:42:17] frigate.util.config            INFO    : frigate config does not need migration...
2025-05-05 17:42:17.849048856  [2025-05-05 17:42:17] frigate.app                    INFO    : Starting Frigate (0.16.0-895afcd)
2025-05-05 17:42:17.861505908  [2025-05-05 17:42:17] peewee_migrate.logs            INFO    : Starting migrations
2025-05-05 17:42:17.861685385  [2025-05-05 17:42:17] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-05-05 17:42:17.877598001  [2025-05-05 17:42:17] frigate.app                    INFO    : Recording process started: 424
2025-05-05 17:42:17.883252939  [2025-05-05 17:42:17] frigate.app                    INFO    : Review process started: 435
2025-05-05 17:42:17.884557652  [2025-05-05 17:42:17] frigate.app                    INFO    : go2rtc process pid: 124
2025-05-05 17:42:17.897058436  [2025-05-05 17:42:17] detector.ov_0                  INFO    : Starting detection process: 446
2025-05-05 17:42:17.904940629  [2025-05-05 17:42:17] detector.ov_1                  INFO    : Starting detection process: 448
2025-05-05 17:42:17.905622841  [2025-05-05 17:42:17] frigate.app                    INFO    : Embedding process started: 450
2025-05-05 17:42:17.918642671  [2025-05-05 17:42:17] frigate.app                    INFO    : Output process started: 472
2025-05-05 17:42:18.114761287  [2025-05-05 17:42:18] frigate.app                    INFO    : Camera processor started for Inngangsparti: 552
2025-05-05 17:42:18.121783355  [2025-05-05 17:42:18] frigate.app                    INFO    : Camera processor started for Garasje: 554
2025-05-05 17:42:18.137906075  [2025-05-05 17:42:18] frigate.app                    INFO    : Camera processor started for Bakside: 565
2025-05-05 17:42:18.138460036  [2025-05-05 17:42:18] frigate.app                    INFO    : Camera processor started for Trampoline: 582
2025-05-05 17:42:18.149147833  [2025-05-05 17:42:18] frigate.app                    INFO    : Capture process started for Inngangsparti: 592
2025-05-05 17:42:18.199480579  [2025-05-05 17:42:18] frigate.app                    INFO    : Capture process started for Garasje: 606
2025-05-05 17:42:18.213827573  [2025-05-05 17:42:18] frigate.app                    INFO    : Capture process started for Bakside: 615
2025-05-05 17:42:18.231608650  [2025-05-05 17:42:18] frigate.app                    INFO    : Capture process started for Trampoline: 628
2025-05-05 17:42:18.348940665  [2025-05-05 17:42:18] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-05-05 17:42:18.435528659  [2025-05-05 17:42:18] frigate.api.fastapi_app        INFO    : FastAPI started
2025-05-05 17:42:19.014802969  loading data from : /config/model_cache/facedet/landmarkdet.yaml
2025-05-05 17:42:19.664609348  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2025-05-05 20:14:19.167096857  [2025-05-05 20:14:19] frigate.comms.dispatcher       INFO    : Setting motion threshold for Inngangsparti: 35
2025-05-05 20:14:19.169646428  [2025-05-05 20:14:19] frigate.comms.dispatcher       INFO    : Setting motion contour area for Inngangsparti: 15
2025-05-05 20:14:45.113902742  [2025-05-05 20:14:45] frigate.comms.dispatcher       INFO    : Setting motion threshold for Inngangsparti: 35
2025-05-05 20:14:45.115338961  [2025-05-05 20:14:45] frigate.comms.dispatcher       INFO    : Setting motion contour area for Inngangsparti: 15
2025-05-06 12:15:51.701210680  [2025-05-06 12:15:51] frigate.ptz.onvif              DEBUG   : ONVIF is not configured for Inngangsparti
2025-05-06 19:07:03.513458185  [2025-05-06 19:07:03] frigate.comms.dispatcher       INFO    : Setting motion threshold for Inngangsparti: 35
2025-05-06 19:07:03.514868065  [2025-05-06 19:07:03] frigate.comms.dispatcher       INFO    : Setting motion contour area for Inngangsparti: 15
2025-05-06 19:10:23.753422044  [2025-05-06 19:10:23] frigate.comms.dispatcher       INFO    : Setting motion threshold for Inngangsparti: 35
2025-05-06 19:10:23.754293472  [2025-05-06 19:10:23] frigate.comms.dispatcher       INFO    : Setting motion contour area for Inngangsparti: 15
```

### Relevant go2rtc log output

```shell
2025-05-05 17:42:15.436483492  [INFO] Preparing new go2rtc config...
2025-05-05 17:42:15.751125581  [INFO] Starting go2rtc...
2025-05-05 17:42:15.804958755  17:42:15.804 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
2025-05-05 17:42:15.804962322  17:42:15.804 INF config path=/dev/shm/go2rtc.yaml
2025-05-05 17:42:15.805439790  17:42:15.805 INF [rtsp] listen addr=:8554
2025-05-05 17:42:15.805462091  17:42:15.805 INF [api] listen addr=:1984
2025-05-05 17:42:15.805661446  17:42:15.805 INF [webrtc] listen addr=:8555
2025-05-05 17:42:25.029223613  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)","width":1080,"height":1920,"avg_frame_rate":"20/1"}]}}]
```

### Frigate stats

```json
{
  "cameras": {
    "Inngangsparti": {
      "camera_fps": 10.1,
      "process_fps": 10.1,
      "skipped_fps": 0,
      "detection_fps": 46.5,
      "detection_enabled": true,
      "pid": 552,
      "capture_pid": 592,
      "ffmpeg_pid": 602,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "Garasje": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 0.1,
      "detection_enabled": true,
      "pid": 554,
      "capture_pid": 606,
      "ffmpeg_pid": 611,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "Bakside": {
      "camera_fps": 5.2,
      "process_fps": 5.2,
      "skipped_fps": 0,
      "detection_fps": 0,
      "detection_enabled": true,
      "pid": 565,
      "capture_pid": 615,
      "ffmpeg_pid": 622,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "Trampoline": {
      "camera_fps": 5.1,
      "process_fps": 5.1,
      "skipped_fps": 0,
      "detection_fps": 0.1,
      "detection_enabled": true,
      "pid": 582,
      "capture_pid": 628,
      "ffmpeg_pid": 664,
      "audio_rms": 0,
      "audio_dBFS": 0
    }
  },
  "detectors": {
    "ov_0": {
      "inference_speed": 6.67,
      "detection_start": 0,
      "pid": 446
    },
    "ov_1": {
      "inference_speed": 6.9,
      "detection_start": 0,
      "pid": 448
    }
  },
  "detection_fps": 46.7,
  "embeddings": {
    "image_embedding_speed": 25.67,
    "image_embedding": 0,
    "text_embedding_speed": 10,
    "text_embedding": 0,
    "face_recognition_speed": 19.62,
    "face_recognition": 0,
    "plate_recognition_speed": 14.71,
    "plate_recognition": 0
  },
  "gpu_usages": {
    "intel-qsv": {
      "gpu": "0.0%",
      "mem": "-%",
      "clients": {
        "446": "0.0%",
        "448": "0.0%",
        "450": "0.0%",
        "602": "2.77%",
        "611": "9.11%",
        "622": "4.07%",
        "664": "4.57%"
      }
    }
  },
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
    },
    "15": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6-linux-init-shutdownd"
    },
    "16": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
    },
    "24": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-oneshot-runner"
    },
    "25": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-fdholder"
    },
    "26": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync"
    },
    "27": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync-log"
    },
    "28": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate"
    },
    "29": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate-log"
    },
    "30": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc"
    },
    "31": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-healthcheck"
    },
    "32": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-log"
    },
    "33": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx"
    },
    "34": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx-log"
    },
    "45": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
    },
    "46": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
    },
    "93": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
    },
    "94": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
    },
    "95": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
    },
    "96": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
    },
    "124": {
      "cpu": "1.0",
      "cpu_average": "1",
      "mem": "0.2",
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
    },
    "132": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user go2rtc-healthcheck"
    },
    "133": {
      "cpu": "36.9",
      "cpu_average": "2",
      "mem": "5.6",
      "cmdline": "python3 -u -m frigate"
    },
    "139": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: master process nginx"
    },
    "206": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "207": {
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "208": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "209": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "215": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "nginx: cache manager process"
    },
    "385": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user certsync"
    },
    "424": {
      "cpu": "1.2",
      "cpu_average": "0",
      "mem": "2.2",
      "cmdline": "frigate.recording_manager"
    },
    "435": {
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "1.9",
      "cmdline": "frigate.review_segment_manager"
    },
    "446": {
      "cpu": "7.9",
      "cpu_average": "4",
      "mem": "2.6",
      "cmdline": "frigate.detector.ov_0"
    },
    "448": {
      "cpu": "8.0",
      "cpu_average": "4",
      "mem": "2.6",
      "cmdline": "frigate.detector.ov_1"
    },
    "450": {
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "6.4",
      "cmdline": "frigate.embeddings_manager"
    },
    "472": {
      "cpu": "2.8",
      "cpu_average": "1",
      "mem": "2.1",
      "cmdline": "frigate.output       "
    },
    "509": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1088x1920 -i pipe: -threads 1 -f mpegts -s 408x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "516": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1920x1080 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "523": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1620x950 -i pipe: -threads 1 -f mpegts -s 1227x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "530": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.3",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "552": {
      "cpu": "23.5",
      "cpu_average": "15",
      "mem": "2.4",
      "cmdline": "frigate.process:Inngangsparti"
    },
    "554": {
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "2.2",
      "cmdline": "frigate.process:Garasje"
    },
    "565": {
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "2.2",
      "cmdline": "frigate.process:Bakside"
    },
    "582": {
      "cpu": "0.8",
      "cpu_average": "0",
      "mem": "2.2",
      "cmdline": "frigate.process:Trampoline"
    },
    "592": {
      "cpu": "2.6",
      "cpu_average": "2",
      "mem": "2.0",
      "cmdline": "frigate.capture:Inngangsparti"
    },
    "602": {
      "cpu": "5.7",
      "cpu_average": "5",
      "mem": "0.6",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -load_plugin hevc_hw -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.16.0-895afcd -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/Inngangsparti_HQ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1 /tmp/cache/Inngangsparti@%Y%m%d%H%M%S%z.mp4 -r 10 -vf vpp_qsv=framerate=10:w=1088:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "606": {
      "cpu": "1.2",
      "cpu_average": "1",
      "mem": "2.0",
      "cmdline": "frigate.capture:Garasje"
    },
    "611": {
      "cpu": "3.2",
      "cpu_average": "3",
      "mem": "0.7",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -load_plugin hevc_hw -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.16.0-895afcd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 10000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Garasje_HQ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1 -tag:v hvc1 /tmp/cache/Garasje@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1920:h=1080:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "615": {
      "cpu": "1.0",
      "cpu_average": "1",
      "mem": "2.0",
      "cmdline": "frigate.capture:Bakside"
    },
    "622": {
      "cpu": "2.8",
      "cpu_average": "3",
      "mem": "0.7",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -load_plugin hevc_hw -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.16.0-895afcd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 10000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Bakside_HQ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1 -tag:v hvc1 -tag:v hvc1 /tmp/cache/Bakside@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1620:h=950:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "628": {
      "cpu": "0.6",
      "cpu_average": "0",
      "mem": "2.0",
      "cmdline": "frigate.capture:Trampoline"
    },
    "664": {
      "cpu": "2.6",
      "cpu_average": "2",
      "mem": "0.6",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -load_plugin hevc_hw -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.16.0-895afcd -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 10000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/Trampoline_HQ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1 -tag:v hvc1 -tag:v hvc1 -tag:v hvc1 /tmp/cache/Trampoline@%Y%m%d%H%M%S%z.mp4 -r 5 -vf vpp_qsv=framerate=5:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "550274": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 60"
    },
    "550337": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 30s"
    },
    "frigate.full_system": {
      "cpu": "10.6",
      "mem": "51.7"
    }
  },
  "service": {
    "uptime": 91849,
    "version": "0.16.0-895afcd",
    "latest_version": "0.15.1",
    "storage": {
      "/media/frigate/recordings": {
        "total": 1952559.5,
        "used": 1614880.4,
        "free": 337679.1,
        "mount_type": "xfs"
      },
      "/media/frigate/clips": {
        "total": 1952559.5,
        "used": 1614880.4,
        "free": 337679.1,
        "mount_type": "xfs"
      },
      "/tmp/cache": {
        "total": 953.7,
        "used": 27.9,
        "free": 925.7,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 384,
        "used": 297.9,
        "free": 86.1,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {},
    "last_updated": 1746551587
  },
  "processes": {
    "recording": {
      "pid": 424
    },
    "review_segment": {
      "pid": 435
    },
    "go2rtc": {
      "pid": 124
    },
    "embeddings": {
      "pid": 450
    }
  }
}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Dahua IPC-HDBW1831R, IPC-HFW1831E, IPC-HDBW4433R-ZS

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c983a098-8ece-4177-ad67-01d46acc8a2e)
