### DISCUSSION TITLE
Using a audio stream from a other neighboring camera

### DISCUSSION THREAD

**Discussion by martin-st-81** [blakeblackshear/frigate#18094] [Ask A Question] [answered]
I have several cameras in use, one of which (GartenEingang) doesn't have a built-in microphone. I would like to use the audio stream from a neighboring camera. Is it possible to configure this using ffmpeg?

I would like to use the audio stream from "GartenSeite" also at "GartenEingang"

go2rtc:
  streams:
    GartenEingang:
      - rtsp://xxx:yyy@192.168.25.41:554/ch1/main/av_stream
    GartenSeite:
      - rtsp://xxx:yyy@192.168.25.45:554/ch1/main/av_stream
      - ffmpeg:GartenSeite#audio=opus
    GartenSeiteSub:
      - rtsp://xxx:yyy@192.168.25.45:554/Streaming/Channels/102

cameras:
  GartenEingang:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/GartenEingang
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic
    detect:
      width: 2688 # <---- update for your camera's resolution
      height: 1580 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - cat
    ui:
      order: 4
    motion:
      mask: 0.969,0.015,0.969,0.063,1,0.067,0.999,0.014
  GartenSeite:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/GartenSeiteSub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/GartenSeite
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - cat
      mask:
        - 0.316,0.146,0.316,0.189,0.339,0.193,0.343,0.155
        - 0.216,0.173,0.19,0.177,0.168,0.159,0.17,0.125,0.206,0.126
    ui:
      order: 5

    motion:
      mask: 0.951,0.01,0.953,0.085,1,0.088,0.999,0.001

**Comment by hawkeye217** [comment, marked as answer]
You'll want to do this with go2rtc. Just provide the stream under the camera. For example:
```
go2rtc:
  streams:
    GartenEingang:
      - ffmpeg:rtsp://xxx:yyy@192.168.25.41:554/ch1/main/av_stream#video=copy
      - ffmpeg:GartenSeite#audio=aac
    GartenSeite:
      - rtsp://xxx:yyy@192.168.25.45:554/ch1/main/av_stream
      - ffmpeg:GartenSeite#audio=opus
    GartenSeiteSub:
      - rtsp://xxx:yyy@192.168.25.45:554/Streaming/Channels/102
```
