### DISCUSSION TITLE
Clarification on only recording detections within zones

### DISCUSSION THREAD

**Discussion by PapayaPlant** [blakeblackshear/frigate#18112] [Ask A Question]
Hello!

I have been slowly learning my way around frigate. Today I decided to take the next step and start recording to an external USB spinning drive. 

I have updated my docker-compose for the path of the drive. That seems all good.

I have now just at a very simple level tested recording and snapshots with the code from the wiki:

```
mqtt:
  host: 192.168.1.XXX
  port: 1883
  user: frigate
  password: password

record:
  enabled: True
  alerts:
    retain:
      days: 7 # <- number of days to keep alert recordings
  detections:
    retain:
      days: 7  # <- number of days to keep detections recordings
snapshots:
  enabled: True
  retain:
    default: 30

detectors:
  ov:
    type: openvino
    device: GPU
```

In frigate I get motion detection's coming in to review. So that all looks good.

I became a little unsure reading the wiki about only recording for specific camera's & only when detection's within zones occur.

Below is my current camera config for the camera I'd like the zone based recording only:

```
  channel3:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.72:XX/ch03/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - pet
        - cat
        - dog
    zones:
      FrontDoorDetection:
        coordinates: 
          0.008,0.495,0.185,0.337,0.2,0.262,0.341,0.177,0.514,0.363,0.714,0.488,0.853,0.634,0.935,0.711,0.869,0.991,0.724,0.993,0.399,0.996,0.138,0.998,0.022,0.608
        loitering_time: 0
        objects: person
      DogPooping:
        coordinates: 0.714,0.165,0.636,0.249,0.974,0.451,0.987,0.297
        loitering_time: 20
        objects: dog
        inertia: 3

```

Is my below assumption correct in how I would enable this if I removed the general record/ snapshot code that is working across all cameras, would this result in only recording detection's in the zones?
Should I add the 'review' config in this code block also?

```
 channel3:
  ffmpeg:
    inputs:
      - path: rtsp://admin:password@192.168.1.72:XX/ch03/0
        roles:
          - detect
          - record
  detect:
    width: 1280
    height: 720
    fps: 5
  objects:
    track:
      - person
      - pet
      - cat
      - dog
  zones:
    FrontDoorDetection:
      coordinates: 
        0.008,0.495,0.185,0.337,0.2,0.262,0.341,0.177,0.514,0.363,0.714,0.488,0.853,0.634,0.935,0.711,0.869,0.991,0.724,0.993,0.399,0.996,0.138,0.998,0.022,0.608
      loitering_time: 0
      objects: person
    DogPooping:
      coordinates: 0.714,0.165,0.636,0.249,0.974,0.451,0.987,0.297
      loitering_time: 20
      objects: dog
      inertia: 3
  record:
    enabled: True
    retain:
      days: 7
      mode: motion
    events:
      retain:
        default: 10
        mode: active_objects
      required_zones:
        - FrontDoorDetection
        - DogPooping
  snapshots:
    enabled: True
    timestamp: True
    bounding_box: True
    required_zones:
      - FrontDoorDetection
      - DogPooping
    retain:
      default: 10

```

Thanks for any pointers!
