### DISCUSSION TITLE
[Support]: ONNXRuntimeError when using Face detection Large model

### DISCUSSION THREAD

**Discussion by tslytsly** [blakeblackshear/frigate#18111] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Trying the new version 16 beta, when I enable face detection with the Large model, this error appears in the logs: `onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 2359296`

The UI then runs normally, unless I try to upload a new face or picture to an existing face, then the UI freezes until I restart the container.
I have an Nvidia T400 correctly passed to the container and am using the tensorrt container. (Hardware accel is working ok)

### Steps to reproduce

1. Enable face detection with the large model
2. Restart the container
3. Attempt to upload a new face, or a new picture to an existing face

### Version

0.16.0-5c3ac75

### In which browser(s) are you experiencing the issue with?

Chrome 136.0.7103.93

### Frigate config file

```yaml
# logger:
#   default: info
#   logs:
#     go2rtc: debug
auth:
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - <REDACTED>
  # enabled: False

mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: true
  host: <REDACTED>
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: true
  provider: gemini
  api_key: <REDACTED>
  model: gemini-1.5-pro
#   # provider: gemini
#   # api_key: <REDACTED>
#   # model: gemini-2.0-flash

record:
  enabled: true
  expire_interval: 30
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 20
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 20
    pre_capture: 10
    post_capture: 10
detectors:
  coral:
    type: edgetpu
    device: usb
model:
  path: plus://c241fae21de50ecf6c0f2a63769dcacd

#detectors:
#  tensorrt:
#    type: tensorrt
#    device: 0 #This is the default, select the first GPU

#model:
#  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
#  labelmap_path: /labelmap/coco-80.txt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 416
#  height: 417
#  path: plus://5b74ceacc1695a92d07baeeee490eece
#  width: 320
#  height: 320

birdseye:
  enabled: false
  mode: objects

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  hwaccel_args: preset-nvidia-h265
  input_args: preset-rtsp-restream # check if udp can be used with cameras, may improve performance.
  output_args:
    # record: preset-record-generic-audio-copy
    record: preset-record-generic-audio-aac

go2rtc:
  log:
    format: text
    level: debug
  streams:
    FoH:
      - rtsp://zman:{FRIGATE_RTSP_PASSWORD}@<REDACTED>:554#hardware=cuda
      - ffmpeg:FoH#audio=opus
    # FoH_sub: "ffmpeg:rtsp://zman:{FRIGATE_RTSP_PASSWORD}@<REDACTED>:554#video=h264/cuda#audio=copy#audio=opus#width=1280#hardware=cuda"
    #FoH_sub: "ffmpeg:FoH#video=h264/cuda#audio=copy#audio=opus#width=1280#hardware=cuda"
    Back_Garden:
      - rtsp://zman:{FRIGATE_RTSP_PASSWORD}@<REDACTED>:554#hardware=cuda
      - ffmpeg:Back_Garden#audio=opus
    #Back_Garden_sub: "ffmpeg:Back_Garden#video=h264/cuda#audio=copy#audio=opus#width=1280#hardware=cuda"
    Doorbell: 
      ffmpeg:http://<REDACTED>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
    # Doorbell: "ffmpeg:rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<REDACTED>:554#video=copy#audio=copy#audio=opus#hardware=cuda"



  webrtc:
    candidates:
      - <REDACTED>:8555
      - <REDACTED>:8555
      - stun:8555

cameras:
  Doorbell:
    enabled: true
    webui_url: https://<REDACTED>/
    ui:
      order: 1
    lpr:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell
          roles:
            - record
            - audio
            - detect
    record: # <----- Enable recording
      enabled: true
    audio:
      enabled: true
    detect:
      enabled: true
      fps: 5
      width: 960
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: true
    genai:
      use_snapshot: true
      prompt: Analyze the {label} in these images from the {camera} security camera
        at the front door. Focus on the actions and potential intent of the {label}.
      object_prompts:
        person: Examine the person in these images. What are they doing, and how might
          their actions suggest their purpose (e.g., delivering something, approaching,
          leaving)? If they are carrying or interacting with a package, include details
          about its source or destination.
        cat: Observe the cat in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects). If the cat is near the flower
          pots or engaging in any specific actions, mention it.
        dog: Observe the dog in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects). If the dog is near the flower
          pots or engaging in any specific actions, mention it.
        bird: Observe the bird in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects).
      objects:
        - person
        - cat
        - dog
        - bird
        - bicycle
      required_zones:
        - front_path
        - kitchen_window
        - next_door
        - drive
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - bicycle
        - face
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
      # - car
      # - motorcycle
      # - suitcase
      # - skateboard
        cat:
          mask:
            - 0,720,341,720
    motion:
      # # FOR 720-RES Stream!!!
      mask:
        - 456,374,648,407,563,288,595,223,702,160,809,180,840,347,760,390,838,444,895,388,920,450,798,528,606,533,450,443
        - 0,720,0,390,339,430,335,720
        - 0,0,960,0,960,314,852,329,726,279,567,336,484,362,0,341
    zones:
      front_path:
        coordinates: 791,539,960,645,960,720,478,720,408,477,449,460
        inertia: 3
        # List of objects that can trigger this zone 
        # objects:
        #   - person
        #   - cat
        #   - dog
      kitchen_window:
        coordinates: 960,594,960,429,801,573
        inertia: 3
        # List of objects that can trigger this zone 
        # objects:
        #   - person
        #   - dog
      road:
        coordinates: 49,398,532,383,515,364,0,378
      next_door:
        coordinates: 0,720,302,720,332,434,0,398
        inertia: 3
        # List of objects that can trigger this zone 
        # objects:
        #   - person
        #   - dog
      drive:
        coordinates: 629,434,960,451,928,377,761,381,674,408
        inertia: 3
        # List of objects that can trigger this zone 
        # objects:
        #   - person
        #   - dog

    review:
      alerts:
        required_zones:
          - drive
          - front_path
          - kitchen_window
  Front_of_House: # <------ Name the camera
    enabled: true
    webui_url: https://<REDACTED>/
    ui:
      order: 2
    live:
      # stream_name: FoH_sub
      streams:
        FoH: FoH
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FoH
          roles:
            - record
            - audio
            - detect
      hwaccel_args: preset-nvidia-h265
    record: # <----- Enable recording
      enabled: true
    audio:
      enabled: true
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: true
    genai:
      use_snapshot: true
      prompt: Analyze the {label} in these images from the {camera} security camera
        at the front of my house. Focus on the actions and potential intent of the
        {label}.
      object_prompts:
        person: Examine the person in these images. What are they doing, and how might
          their actions suggest their purpose (e.g., delivering something, approaching,
          leaving)? If they are carrying or interacting with a package, include details
          about its source or destination.
        cat: Observe the cat in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects). If the cat is near the flower
          pots or engaging in any specific actions, mention it.
        dog: Observe the dog in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects). If the dog is near the flower
          pots or engaging in any specific actions, mention it.
        bird: Observe the bird in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects).
        car: Observe the car in these images. Describe the type and colour of the
          car. also try and work out if it is in motion.
      objects:
        - person
        - cat
        - dog
        - bicycle
        - car
      required_zones:
        - drive
        - leighs_path
        - bins
        - drive_steps
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
        - motorcycle
        - license_plate
        - face
      # - suitcase
      # - skateboard
      # FOR 720-RES STREAM!!!
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2500
        cat:
          max_area: 25000
          mask: 
            0.924,1,0.848,0.657,0.942,0.515,0.812,0.305,0.719,0.358,0.512,0.402,0.477,0.395,0.395,0.132,0.198,0.142,0.039,0.251,0,1
        car:
          mask:
            - 0,1,1,1,1,0,0.704,0,0.682,0.105,0.404,0.115,0.452,0.405,0.404,0.579,0.121,0.659
            - 0.089,0,0.16,0.037,0.187,0.119,0,0.11,0,0.033
        license_plate:
          threshold: 0.7
    motion:
      # threshold: 30
      # contour_area: 15
      mask:
        - 0,0.109,0.122,0.112,0.19,0.108,0.094,0.869,0,0.838
        - 0.478,0.411,0.613,0.376,0.737,0.373,0.788,0.351,0.921,0.555,0.959,0.483,0.878,0.356,0.806,0.337,0.714,0.359,0.57,0.324,0.501,0.188,0.417,0.17,0.448,0.273
        - 1,0.358,1,0,0.761,0,0.802,0.112
    zones:
      drive:
        coordinates: 0.099,0.7,0.392,0.733,0.437,0.399,0.453,0.406,0.377,0.181,0.177,0.167
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
          - person
          - dog
        loitering_time: 0
      leighs_path:
        coordinates: 
          0.687,0.149,0.953,0.465,0.919,0.562,0.843,0.775,0.901,1,0.999,1,0.999,0.804,0.999,0.396,0.764,0.089,0.742,0.086,0.705,0.111
        inertia: 3
        # List of objects that can trigger this zone 
        loitering_time: 0
        objects:
          - bicycle
          - dog
          - person
      bins:
        coordinates: 
          0.47,0.649,0.426,0.914,0.468,0.958,0.6,0.959,0.61,1,0.902,1,0.834,0.744,0.874,0.643,0.922,0.553,0.799,0.352,0.438,0.41
        inertia: 3
        # List of objects that can trigger this zone 
        objects:
          - person
          - dog
        loitering_time: 0
      drive_steps:
        coordinates: 0.605,1,0.595,0.964,0.423,0.927,0.395,0.734,0.102,0.702,0.096,0.883,0,0.846,0,1
        inertia: 3
        # List of objects that can trigger this zone 
        loitering_time: 0
        objects:
          - dog
          - person
      road:
        coordinates: 
          0.762,0.085,0.822,0.153,0.824,0.125,0.786,0.054,0.745,0,0,0,0,0.12,0.19,0.12,0.192,0.162,0.372,0.18,0.38,0.113,0.435,0.118,0.444,0.067,0.715,0.11
        inertia: 3
        # List of objects that can trigger this zone 
        loitering_time: 0
        objects:
          - dog
          - person
          - bicycle
      Down_the_Street:
        coordinates: 0.762,0,1,0,1,0.391,0.78,0.107,0.702,0
        loitering_time: 3
        objects:
          - dog
          - person
        inertia: 3
    review:
      alerts:
        required_zones:
          - bins
          - drive
          - drive_steps
          - leighs_path
  Back_Garden: # <------ Name the camera
    enabled: true
    webui_url: https://<REDACTED>/
    ui:
      order: 3
    live:
      # stream_name: Back_Garden_sub
      streams:
        Back_Garden: Back_Garden
    lpr:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Garden
          roles:
            - record
            - audio
            - detect
      hwaccel_args: preset-nvidia-h265
    record: # <----- Enable recording
      enabled: true
      alerts:
        retain:
          days: 15
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 10
        pre_capture: 10
        post_capture: 10
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - yell
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      fps: 5
      width: 1280
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: true
    genai:
      use_snapshot: true
      prompt: Analyze the {label} in these images from the {camera} security camera
        at the rear of my house. Focus on the actions and potential intent of the
        {label}.
      object_prompts:
        person: Examine the person in these images. What are they doing, and how might
          their actions suggest their purpose (e.g., delivering something, approaching,
          leaving)?
        cat: Observe the cat in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects). If the cat is near the flower
          pots or engaging in any specific actions, mention it.
        dog: Observe the dog in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects). If the dog is near the flower
          pots or engaging in any specific actions, mention it.
        bird: Observe the bird in these images. Focus on its movement and intent (e.g.,
          wandering, hunting, interacting with objects).
      objects:
        - person
        - cat
        - dog
      required_zones:
        - lower_patio
        - living_room_window
        - shed
        - flower_bed
        - top_patio
        - Patio_Steps
    objects:
      track:
        - person
        - cat
        - dog
        - face
      filters:
        person:
          mask:
            - 0.066,0.401,0.15,0.328,0.171,0.433,0.088,0.51
            - 0.648,0.08,0.655,0.089,0.713,0.113,0.706,0.198,0.655,0.171
      mask: 0.434,0.326,0.475,0.269,0.524,0.294,0.472,0.357,0.433,0.375
    zones:
      lower_patio:
        coordinates: 0.041,0.395,0.333,0.285,0.436,0.359,0.192,0.668,0.199,0.7,0.105,0.786
        inertia: 3
        loitering_time: 0
      living_room_window:
        coordinates: 0.341,1,0,1,0.034,0.436,0.105,0.765,0.198,0.694
        inertia: 3
        loitering_time: 0
      flower_bed:
        coordinates: 0.449,1,0.91,1,0.976,0.368,0.599,0.224,0.226,0.648
        inertia: 3
        loitering_time: 0
      shed:
        coordinates: 0.569,0.14,0.576,0,0.423,0,0.398,0.144,0.423,0.186
        inertia: 3
        loitering_time: 0
      top_patio:
        coordinates: 0.569,0.23,0.949,0.344,0.956,0.051,0.577,0,0.556,0.152,0.419,0.191
        inertia: 3
        loitering_time: 0
      nans_fence:
        coordinates: 1,1,0.914,1,0.964,0.362,0.96,0.079,1,0.082
        inertia: 3
        loitering_time: 0
      leighs_fence:
        coordinates: 0.032,0.285,0.153,0.194,0.435,0.056,0.415,0,0.029,0
        inertia: 3
        loitering_time: 0
      Patio_Steps:
        coordinates: 0.419,0.185,0.558,0.23,0.451,0.351,0.32,0.27
        loitering_time: 0
    motion:
      mask:
        - 0.408,0.05,0.457,0.056,0.557,0.045,0.584,0,0,0,0,0.156,0.035,0.223,0.08,0.205,0.082,0.122,0.131,0.109,0.2,0.158
        - 0.693,0.117,0.753,0.356,0.451,0.836,0.671,1,0.934,1,0.983,0.327,0.965,0.105,1,0.106,1,0,0.58,0,0.59,0.09
        - 0.232,0.67,0.545,0.249,0.624,0.242,0.682,0.272,0.715,0.365,0.334,0.854,0.236,0.729
        - 0.075,0.432,0.156,0.363,0.17,0.432,0.087,0.513
    review:
      alerts:
        required_zones:
          - lower_patio
          - shed
          - top_patio
version: 0.16-0
camera_groups:
  Front:
    order: 1
    icon: LuCar
    cameras:
      - Doorbell
      - Front_of_House
  Back:
    order: 2
    icon: LuWarehouse
    cameras:
      - Back_Garden
      - Front_of_House
      - Doorbell
notifications:
  enabled: 'true'
  email: <REDACTED>
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
  device: GPU
  known_plates:
    <REDACTED>:
      - '<REDACTED>'
      - '<REDACTED>'
    <REDACTED>:
      - <REDACTED>
      - <REDACTED>
classification:
  bird:
    enabled: true
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='eth1'
  --ip='<REDACTED>'
  --pids-limit 2048
  --privileged=true
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Lofty"
  -e HOST_CONTAINERNAME="frigate"
  -e 'TCP_PORT_5000'='5000'
  -e 'TCP_PORT_8554'='8554'
  -e 'FRIGATE_RTSP_PASSWORD'='<REDACTED>'
  -e 'PLUS_API_KEY'='<REDACTED>'
  -e 'NVIDIA_VISIBLE_DEVICES'='all'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='compute,utility,video'
  -e 'TCP_PORT_8555'='8555'
  -e 'UDP_PORT_8555'='8555'
  -e 'TCP_PORT_1984'='1984'
  -e 'FRIGATE_MQTT_PASSWORD'='<REDACTED>'
  -e 'FRIGATE_MQTT_USER'='<REDACTED>'
  -e 'YOLO_MODELS'='yolov7-tiny-416'
  -e 'FRIGATE_GEMINI_API_KEY'='<REDACTED>'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/user/cctv/':'/media/frigate':'rw'
  -v '/mnt/user/appdata/frigate-logs/':'/dev/shm/logs':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --device='/dev/bus/usb'
  --runtime=nvidia
  --memory=12G
  --gpus=all
  --shm-size=512mb
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:0.16.0-beta1-tensorrt'
```

### Relevant Frigate log output

```shell
2025-05-08 11:03:52.897020768  [2025-05-08 11:03:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +5, GPU +8, now: CPU 143, GPU 70 (MiB)
2025-05-08 11:03:53.062365064  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +11, GPU +10, now: CPU 154, GPU 80 (MiB)
2025-05-08 11:03:53.063094742  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt WARNING : TensorRT was linked against cuDNN 8.9.0 but loaded cuDNN 8.6.0
2025-05-08 11:03:53.077965966  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +19, now: CPU 0, GPU 19 (MiB)
2025-05-08 11:03:53.110135142  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 135, GPU 72 (MiB)
2025-05-08 11:03:53.110629616  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 135, GPU 80 (MiB)
2025-05-08 11:03:53.116996657  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt WARNING : TensorRT was linked against cuDNN 8.9.0 but loaded cuDNN 8.6.0
2025-05-08 11:03:53.131166041  [2025-05-08 11:03:53] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +7, now: CPU 0, GPU 26 (MiB)
2025-05-08 11:03:53.443991436  [2025-05-08 11:03:53] frigate.api.fastapi_app        INFO    : FastAPI started
2025-05-08 11:03:56.034363432  2025-05-08 11:03:56.034278148 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 2 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2025-05-08 11:03:56.102190573  loading data from : /config/model_cache/facedet/landmarkdet.yaml
2025-05-08 11:03:56.354725188  11:03:56.354 DBG [exec] run rtsp launch=3.902679935s
2025-05-08 11:03:56.356440929  11:03:56.354 DBG [streams] start producer url=ffmpeg:http://<REDACTED>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=zk60ZAn0K1arz#video=copy#audio=copy#audio=opus
2025-05-08 11:03:59.502356852  2025-05-08 11:03:59.502268807 [E:onnxruntime:, inference_session.cc:2117 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 51380224
2025-05-08 11:03:59.502365917  
2025-05-08 11:03:59.961946740  Process embeddings_manager:
2025-05-08 11:03:59.962010943  Traceback (most recent call last):
2025-05-08 11:03:59.962032319    File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2025-05-08 11:03:59.962053540      self.run()
2025-05-08 11:03:59.962065456    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
2025-05-08 11:03:59.962086628      return run(*args, **kwargs)
2025-05-08 11:03:59.962107619             ^^^^^^^^^^^^^^^^^^^^
2025-05-08 11:03:59.962149447    File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
2025-05-08 11:03:59.962197099      self._target(*self._args, **self._kwargs)
2025-05-08 11:03:59.962217910    File "/opt/frigate/frigate/embeddings/__init__.py", line 59, in manage_embeddings
2025-05-08 11:03:59.962229777      maintainer = EmbeddingMaintainer(
2025-05-08 11:03:59.962231400                   ^^^^^^^^^^^^^^^^^^^^
2025-05-08 11:03:59.962303338    File "/opt/frigate/frigate/embeddings/maintainer.py", line 122, in __init__
2025-05-08 11:03:59.962305206      FaceRealTimeProcessor(
2025-05-08 11:03:59.962307218    File "/opt/frigate/frigate/data_processing/real_time/face.py", line 91, in __init__
2025-05-08 11:03:59.962308951      self.recognizer = ArcFaceRecognizer(self.config)
2025-05-08 11:03:59.962334203                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-08 11:03:59.962336386    File "/opt/frigate/frigate/data_processing/common/face/model.py", line 268, in __init__
2025-05-08 11:03:59.962338201      self.face_embedder: ArcfaceEmbedding = ArcfaceEmbedding()
2025-05-08 11:03:59.962339975                                             ^^^^^^^^^^^^^^^^^^
2025-05-08 11:03:59.962341755    File "/opt/frigate/frigate/embeddings/onnx/face_embedding.py", line 147, in __init__
2025-05-08 11:03:59.962371174      self._load_model_and_utils()
2025-05-08 11:03:59.962373460    File "/opt/frigate/frigate/embeddings/onnx/face_embedding.py", line 155, in _load_model_and_utils
2025-05-08 11:03:59.962375106      self.runner = ONNXModelRunner(
2025-05-08 11:03:59.962376746                    ^^^^^^^^^^^^^^^^
2025-05-08 11:03:59.962378417    File "/opt/frigate/frigate/embeddings/onnx/runner.py", line 51, in __init__
2025-05-08 11:03:59.962380033      self.ort = ort.InferenceSession(
2025-05-08 11:03:59.962381565                 ^^^^^^^^^^^^^^^^^^^^^
2025-05-08 11:03:59.962384523    File "/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 465, in __init__
2025-05-08 11:03:59.962386434      self._create_inference_session(providers, provider_options, disabled_optimizers)
2025-05-08 11:03:59.962388669    File "/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 537, in _create_inference_session
2025-05-08 11:03:59.962414187      sess.initialize_session(providers, provider_options, disabled_optimizers)
2025-05-08 11:03:59.962418216  onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:376 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 51380224
2025-05-08 11:03:59.962419913
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Reolink 1220A

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/33cdc015-cfad-449c-a04c-9de71701e48b)
