### DISCUSSION TITLE
[Support]: Motion tab in Review panel stuck in fast forward

### DISCUSSION THREAD

**Discussion by spridgeon84** [blakeblackshear/frigate#18121] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I'm currently running the latest 0.16 beta release, but this bug started when I was still running 0.15
In the review panel on the Motion tab, it defaults to 8x playback speed, and I'm only able to select 4x, 8x, 12x and 16x. I can't set it to 1x. It works as expected in other tabs. Present in both desktop and mobile.

### Steps to reproduce

1. Go to review panel
2. Click on motion
3. Look at playback speed selection
...

### Version

0.16.0-5c3ac75

### In which browser(s) are you experiencing the issue with?

Firefox 138.0 (aarch64)

### Frigate config file

```yaml
mqtt:
  host: 192.168.84.109
  port: 1883
  user: homeassistant
  password: xxx

birdseye:
  enabled: false

semantic_search:
  enabled: true
  reindex: false

  model_size: large
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral1:
    type: edgetpu

detect:
  fps: 5
  enabled: true

model:
  path: plus://xxx

objects:
  track:
    - person
    - face
    - car
    - license_plate
    - motorcycle
    - bicycle
    - boat
    - dog
    - cat
    - bird
    - deer
    - raccoon
    - bear
    - squirrel
    - ups
    - fedex
    - amazon
    - package
    - waste_bin
    - bbq_grill
  filters:
    person:
      min_area: 1000
      min_score: 0.8
      threshold: 0.85
    car:
      min_score: 0.6
      threshold: 0.8
    license_plate:
      min_score: 0.8
      threshold: 0.9
    motorcycle:
      min_score: 0.8
      threshold: 0.9
    bicycle:
      min_score: 0.8
      threshold: 0.9
    boat:
      min_score: 0.8
      threshold: 0.9
    dog:
      min_score: 0.8
      threshold: 0.85
    cat:
      min_score: 0.8
      threshold: 0.85
    bird:
      min_score: 0.7
      threshold: 0.8
    deer:
      min_score: 0.7
      threshold: 0.8
    raccoon:
      min_score: 0.4
      threshold: 0.5
    bear:
      min_score: 0.8
      threshold: 0.85
    squirrel:
      min_score: 0.5
      threshold: 0.6
    ups:
      min_score: 0.5
      threshold: 0.7
    fedex:
      min_score: 0.5
      threshold: 0.7
    amazon:
      min_score: 0.5
      threshold: 0.7
    package:
      min_score: 0.5
      threshold: 0.7
    waste_bin:
      min_score: 0.5
      threshold: 0.8
    bbq_grill:
      min_score: 0.8
      threshold: 0.9



snapshots:
  enabled: true
  retain:
    default: 10

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
motion:
  threshold: 40
  contour_area: 10
  improve_contrast: true

cameras:
  fdoor_camera:
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: 
            https://192.168.84.203/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=x
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    zones:
      yard:
        coordinates: 0,0.282,0.304,0.23,0.596,0.217,1,0.282,1,0.995,0,0.995
        inertia: 1
    review:
      alerts:
        required_zones: yard
      detections:
        required_zones: yard
    motion:
      mask: 0.709,0,0.709,0.04,1,0.043,1,0
      threshold: 30
      contour_area: 20
      improve_contrast: true
      lightning_threshold: 0.6
    objects:
      filters:
        car:
          mask: 0,0.281,0.131,0.249,0.4,0.212,0.649,0.213,0.846,0.27,1,0.289,1,0,0,0

#################################   

  bdoor_camera:
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: 
            https://192.168.84.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080

    motion:
      mask: 0.358,0.183,0.75,0.32,0.734,0.797,1,1,1,0,0.356,0
    zones:
      patio:
        coordinates: 
          0,0.423,0.424,0.306,0.425,0.222,0.651,0.279,0.638,0.726,0.328,0.872,0.096,0.997,0,1
        inertia: 1
        loitering_time: 0
    review:
      alerts:
        required_zones: patio

#################################

  garage_camera:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.84.202:554/cam/realmonitor?channel=1&subtype=1
          roles:
          #  - detect
            - record
    detect:
      width: 704
      height: 480

    objects:
      filters:
        car:
          threshold: 1.1

    motion:
      mask: 0.642,0.043,0.953,0.043,0.951,0,0.637,0

      threshold: 40
      contour_area: 60
      improve_contrast: true

#################################   

  screen_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.84.209:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect

    motion:
      mask: 0,1,1,1,1,0,0,0

      threshold: 255
      contour_area: 255

#################################   

  entry_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.84.206:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
    detect:
      width: 480
      height: 704
    objects:
      filters:
        package:
          threshold: 0.5

    motion:
      mask: 0.629,0.127,0.94,0.127,0.938,0.084,0.624,0.084
      threshold: 27
      contour_area: 20
      improve_contrast: true

    zones:
      doorstep:
        coordinates: 0.132,0.666,0.553,0.828,0.697,0.662,0.333,0.568
        loitering_time: 0
    review:
      alerts:
        required_zones: doorstep

#################################   

  byard_camera:
    enabled: true
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: 
            https://192.168.84.205/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1440

    motion:
      mask:
        - 0.795,0.05,0.899,0.049,0.899,0,0.795,0
        - 0,0.892,0.09,0.726,0.067,0.356,0.168,0,0,0
        - 0.321,0.351,0.71,0.533,0.71,0,0.292,0
      threshold: 45
      contour_area: 20
      improve_contrast: true
    zones:
      CatTrapZone:
        coordinates: 0,1,0.238,1,0.595,0.481,0.32,0.36,0,0.665
        inertia: 1
        loitering_time: 0
        objects:
          - cat
          - raccoon

#################################   

  alley_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.84.204:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080

    motion:
      mask: 0.179,0.069,0.179,0.036,0.025,0.039,0.027,0.067
      threshold: 40
      contour_area: 26
      improve_contrast: true
    zones:
      alley_line:
        coordinates: 0.534,1,0.839,0.529,0.847,0.404,1,0.51,1,1
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: alley_line
      detections:
        required_zones: alley_line
    objects:
      filters:
        car: {}
version: 0.16-0
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: true
```

### docker-compose file or Docker CLI command

```yaml
running through unraid
```

### Relevant Frigate log output

```shell
no relevant log entry
```

### Relevant go2rtc log output

```shell
no relevant log entry
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

reolink cx410

### Screenshots of the Frigate UI's System metrics pages

.
