### DISCUSSION TITLE
[Camera Support]: go2rtc streams are switched

### DISCUSSION THREAD

**Discussion by daanolislagers** [blakeblackshear/frigate#18132] [Camera Support]
### Describe the problem you are having

I have two Reolink camera's, one RLC-510WA and one Doorbell. I've added both to my config using go2rtc as per suggested in the camera specific configurations. 

Now both camera's work as intended, only the two go2rtc streams are swapped.

So this stream "tuincamera:
      - ffmpeg:http://192.168.2.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={PASSWORD}#video=copy#audio=copy#audio=opus"" shows the correct camera stream. But when I view this stream "rtsp://127.0.0.1:8554/tuincamera" I get the stream of my other camera.

### Version

0.14.1-

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.2.146
  user: mqtt
  password: mosquitto
detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5
objects:
  track:
    - person
    - bicycle
    - car
    - dog
    - cat
snapshots:
  enabled: True
  timestamp: false
  bounding_box: true
record:
  enabled: True
go2rtc:
  streams:
    tuincamera:
      - ffmpeg:http://192.168.2.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={PASSWORD}#video=copy#audio=copy#audio=opus"
    deurbel:
      - "ffmpeg:http://192.168.2.202/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={PASSWORD}#video=copy#audio=copy#audio=opus"
      - rtsp://frigate:{PASSWORD}@192.168.2.202/Preview_01_sub
cameras:
  tuincamera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tuincamera
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
  deurbel:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deurbel
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
version: 0.14
```

### Relevant Frigate log output

```shell
No errors
```

### Relevant go2rtc log output

```shell
No errors
```

### FFprobe output from your camera

```shell
ffprobe rtsp://frigate:{PASSWORD}@192.168.2.202/Preview_01_sub
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://frigate:{PASSWORD}@192.168.2.202/Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000438, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 10 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Proxmox via TTeck Script

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink RLC-510WA and one Doorbell

### Screenshots of the Frigate UI's System metrics pages

![Schermafbeelding 2025-05-09 112121](https://github.com/user-attachments/assets/7e5bf1a9-2e6f-4912-976f-5ff99b5ad965)
![Schermafbeelding 2025-05-09 112136](https://github.com/user-attachments/assets/e730e2b7-9605-439c-a5ca-46ed7b1f8ef6)
