### DISCUSSION TITLE
Hel getting LPR Automation

### DISCUSSION THREAD

**Discussion by hhrocha000** [blakeblackshear/frigate#18137] [Ask A Question] [answered]
Hi there,
I update to 0.16 Beta and the LPR works great, detects my car in frigate all the time. my question is how can i create an automation with this?
i want to when detects xxxxxx license plate and my garage is closed then open the garage.

My problem is how can i get that event? i have the frigate integration but i only get the last recognize plate that stays always to the known plates name for the plate that is recognized.

the automation that i'm trying to test based on the documentation and my knowledge is this one:

```
alias: Frigate Open Garage Volvo
description: ""
triggers:
  - trigger: mqtt
    topic: frigate/events
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.after.recognized_license_plate == '11JR34'}}"
  - type: is_not_open
    condition: device
    device_id: ff6e2d5aaaae8541dceeabaeb75dee2e
    entity_id: be89da71bbe72911372aa274ef073a1f
    domain: binary_sensor
actions:
  - type: turn_off
    device_id: ff6e2d5aaaae8541dceeabaeb75dee2e
    entity_id: bf3881e894f6ba57ca0431f82275acae
    domain: switch
mode: single
```

Can anyone help me put this to work?
