### DISCUSSION TITLE
Frigate live stream on UNRAID 6.9.2 - AMD  + GPU & Google coral

### DISCUSSION THREAD

**Discussion by Red-ington** [blakeblackshear/frigate#1813] [Ask A Question]
Hi team,
             I have an AMD 3300x CPU & an old R9-390X  for the GPU., also Google coral PCI.

ISSUES 1 - I'm currently having issues with the use of the GPU, it seems to not have any load at all.  I have activated well i think the amdgpu & radeon drivers. I seem to still not be getting any GPU feedback. Nothing doin here. Have GPUsts & radeontop plugins.

ISSUE 2 - I'm currently getting live steaming if I go the the camera in frigate,  the recording side of things are not functional at this stage, i do see that files are generated every 12 seconds  but when going to the file to play the recordings I only get the first frame only while the recording is being played.   Also when an event is logged the same issue here when trying to view the footage.  

Camera's are Annke C800 4K I91BM with H265 & H265+ encoding only. no 264 option even with firmware to HIKvision. 

So with some knowledge ( & this could be dangerous LOL) knowing that figate is not a friend with H265 I was hoping I could get the GPU do do all the work of the decoding of the H265 to bring back to H264 for figate. 
My understanding I need to use vaapi for the AMD GPU decoding. Also HEVC is H265. 

Below is my current config, any help would be great. been pulling whats left of my hair out. 

happy to start from scratch on config file.

```
cameras:
  frontyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
       #output_args:
        #Optional: output args for detect streams (default: shown below)
        #detect: -f rawvideo -pix_fmt yuv420p
        #Optional: output args for record streams (default: shown below)
        #record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -crf 18 -c:a copy -vf format=nv12|vaapi,hwupload -b:v 4M -r 15
        #record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -crf 18 -c:a copy -vf format=nv12|vaapi,hwupload -b:v 4M -r 15
        #Optional: output args for clips streams (default: shown below)
        #Optional: output args for rtmp streams (default: shown below)
        #record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -pix_fmt yuv420p
        #rtmp: -c:v h264_vaapi -c:a copy -vf format=nv12|vaapi,hwupload -f flv
     input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
    inputs:
       #- path: rtsp://user:PW@192.xxx.xx.xxx:554/Streaming/Channels/102
       #   roles:
       #   - rtmp
        - path: rtsp://user:PW@192.xxx.xx.xxx:554/Streaming/Channels/101
          roles:
            - detect
            - record
           # -  rtmp
    record:
      enabled: true
      retain_days: 5
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - car
          - dog
        retain:
          default: 5
          objects:
            person: 30
    detect:
      enabled: true
      max_disappeared: 25
      width: 3840
      height: 2160
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      quality: 100
      crop: false
      retain:
        default: 7
        objects:
          person: 60
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - bicycle
        - car
        - truck
        - motorcycle
    motion:
      mask:
        - 0,0,0,534,1721,181,3519,249,3562,25
    motion:
      mask:
        - 3552,0,3600,207,1675,156,38,534,33,25
        - 1519,2138,1348,2134,1274,1384,1393,1368
detectors:
  coral:
    type: edgetpu
    device: pci
```

**Comment by DrSpaldo** [comment]
Very interesting @Red-ington ; especially that you are able to do the live view & detect from your H265, but, then the physical recording files are not working!   I would like to find out the outcome on this one, I have had a quick search on the discussions as well as the HA forum thread. It feels like others have had a similar issue with no obvious answer being posted...

**Reply by blakeblackshear** [reply]
H265 for live view and detect has never been a problem. That has always worked.

**Reply by DrSpaldo** [reply]
Oh ok, I wasn’t aware. I’ve got H264 streams so been fine for me. I was thinking of H265 cameras but this might scare me off! It’s a shame though, given the potential saving in HDD space…

**Reply by blakeblackshear** [reply]
Yea. Licensing issues prevent Firefox and Chrome from supporting H265.

**Reply by Red-ington** [reply]
So just checking once i sort the ffmpeg code I should be able to steam & record the H265 from my C800 I91MB camera.

Can you help me out with the code that I have put together & see if I can sort out my issue. 

So live view in frigate is working. recording is not, I can see the first frame & thats it.

**Reply by Red-ington** [reply]
Also @DrSpaldo & @blakeblackshear thanks.

**Comment by blakeblackshear** [comment]
I would suggest working with ffmpeg directly on the cli to read your stream and write h264 on its own. Once you have an ffmpeg command that you are happy with, it should be relatively simple to get it working in frigate.

**Reply by Red-ington** [reply]
do you have any code suggestions, as you can see from the code posted up top I have tried to convert with out luck.

**Comment by Red-ington** [comment]
I now have this config as a trial but CPU is 90% usage, poor CPU is melting.   The recordings are now working. is my issue now the fact I don't have the GPU helping out with the decoding??

```
detectors:
  coral:
    type: edgetpu
    device: pci
cameras:
  frontyard:
    ffmpeg:
      input_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c copy -f flv
      inputs:
       #- path: rtsp://user:password@192.168.x.xxx:554/Streaming/Channels/102
       #   roles:
       #   - rtmp
        - path: rtsp://user:password@192.168.x.xxx:554/Streaming/Channels/101
          roles:
            - detect
            - record
            #- rtmp
    record:
      enabled: true
      retain_days: 5
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - car
          - dog
        retain:
          default: 5
          objects:
            person: 30
    detect:
      enabled: true
      max_disappeared: 25
      width: 3840
      height: 2160
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      quality: 100
      crop: false
      retain:
        default: 7
        objects:
          person: 60
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - bicycle
        - car
        - truck
        - motorcycle
```

**Reply by blakeblackshear** [reply]
> is my issue now the fact I don't have the GPU helping out with the decoding??

Your hardware acceleration is set to help with _decoding_, but you are then _encoding_ to h264 with the CPU. It will probably still be using more CPU than you will be happy with, but you can use quicksync for encoding h264 as well. There are plenty of examples on Google for ffmpeg commands, but I don't believe anyone has been able to get this to work well enough to be satisfied. If it was me, I would just replace the camera or accept that you can't view recordings without edge or safari.

**Comment by DrSpaldo** [comment]
@Red-ington did you have any luck getting this going?

**Comment by menkej** [comment]
I have the same cameras @Red-ington and spent ages on figuring out how to make them work.  What worked instantly:

* live view
* detection
* still images
 
But I had issues playing the recordings (see camera haustuer, still in the initial config). Now I can download a clip and play it just fine (on MacBook/iPhone/Win10 - check camera haustuer2 and corresponding output params), trying to view the video in the browser still does not work ("The media could not be loaded, either because the server or network failed or because the format is not supported.").


```
mqtt:
  host: 192.168.27.27

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 7
    mode: motion
    # mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 2
        car: 7

cameras:
  haustuer: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
        rtmp: -c:v copy -c:a aac -f flv
        
      inputs:
        - path: rtsp://frigate:secret123@192.168.27.34:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - record
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
    
    zones:
      autos:
        coordinates: 962,916,2000,938,2180,340,1565,302,1025,332
      eingang:
        coordinates: 2805,348,2272,310,1625,2160,2892,2160
  haustuer2: # <------ Name the camera
    ffmpeg:
      # Hardware acceleration methods:
      # cuda
      # vaapi
      # qsv
      # drm
      # opencl
      # vulkan
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv
        
      inputs:
        - path: rtsp://haustuer:secret123@192.168.27.34:554/H264/ch1/main/av_stream # <----- Update for your camera
          roles:
            - detect
            - record
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
    
    zones:
      autos:
        coordinates: 962,916,2000,938,2180,340,1565,302,1025,332
      eingang:
        coordinates: 2805,348,2272,310,1625,2160,2892,2160

```

Any Ideas about the online playback issue @Red-ington ? Did you get it working maybe?

cheers
Jörg
