### DISCUSSION TITLE
HA advanced camera card | live view | low fps

### DISCUSSION THREAD

**Discussion by Symbiot78** [blakeblackshear/frigate#18146] [Ask A Question]
Hi

I've been fighting with the frame rate in my Advanced camera card. It appears it's using the secondary stream. 

But I can't seem to figure out where I am going wrong.

this is my conf for the card:

`type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.carport
    live_provider: go2rtc
    icon: mdi:camera-iris
    dependencies:
      all_cameras: false
    capabilities:
      disable: []
  - camera_entity: camera.house_front
  - camera_entity: camera.garden
profiles: []
view:
  default: live
  camera_select: live
live:
  preload: false
  auto_play: []
menu:
  buttons:
    iris:
      enabled: true
    camera_ui:
      enabled: true`

And my conf of the cameras for frigate:

 go2rtc:
   streams:
     carport_detect:
    #1280x720@12fps
       - rtsp://userpass@10.20.10.32/Streaming/Channels/102
     carport_record:
    #  
       - rtsp://userpass@10.20.10.32/Streaming/Channels/101
     garden_detect:
    #
       - rtsp://userpass@10.20.10.33/Streaming/Channels/102#video=h264
 
     garden_record:
    #
       - rtsp://userpass@10.20.10.33/Streaming/Channels/101#video=h264
 
     house_front_detect:
    # 640x360@•24fps
       - rtspx://192.168.1.1:7441/jNTfu0xafcD75mYy
     house_front_record:
    # 1280x720@24fps
       - rtspx://192.168.1.1:7441/nLwsijWvdrnipjln

It's probably something annoyingly simple that I've missed - but if so.. I'll take it and enjoy the live stream once I'm over my shame :)

**Comment by hawkeye217** [comment]
This is the repo for Frigate itself, not the Advanced Camera Card. Nonetheless, it looks like you are just missing the `stream` in the go2rtc block in your card configuration. You should specify a go2rtc stream name from your Frigate config. 

See the card docs: https://card.camera/#/configuration/cameras/live-provider?id=go2rtc

**Comment by Symbiot78** [comment]
thank you for the feedback.
I never really noticed - but I am seeing the cirle-thingy in the top right hand corner saying the stream isn't loaded yet. I am guessing that is where the issue "starts". 
I can't quite see where I might find the issue. Nothing showing in frigate logs apart from the :

==

'2025-05-10 21:10:06.399194739  192.168.1.131 - - [10/May/2025:21:10:06 +0200] "GET /api/carport/latest.jpg HTTP/1.1" 200 390154 "-" "HomeAssistant/2025.5.1 aiohttp/3.11.18 Python/3.13" "-"
2025-05-10 21:10:22.395660231  192.168.1.131 - - [10/May/2025:21:10:22 +0200] "GET /api/carport/latest.jpg HTTP/1.1" 200 389472 "-" "HomeAssistant/2025.5.1 aiohttp/3.11.18 Python/3.13" "-"
2025-05-10 21:10:39.395091129  192.168.1.131 - - [10/May/2025:21:10:39 +0200] "GET /api/carport/latest.jpg HTTP/1.1" 200 389844 "-" "HomeAssistant/2025.5.1 aiohttp/3.11.18 Python/3.13" "-"

==

**Reply by hawkeye217** [reply]
See the troubleshooting steps for the card: https://card.camera/#/troubleshooting?id=stream-does-not-load

What is your Frigate config?

**Comment by Symbiot78** [comment]
this is the full config:
```
mqtt:
  host: 192.168.1.131
  user: mqttuser
  password: redacted

logger:
  # Optional: default log level (default: shown below)
  default: info


#####################################
############### Coral ###############
#####################################


detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu

go2rtc:
  streams:
    carport_detect:
      - rtsp://redacted:redacted@10.20.10.32/Streaming/Channels/102
    carport_record:    
      - rtsp://redacted:redacted@10.20.10.32/Streaming/Channels/101
    garden_detect:
      - rtsp://redacted:redacted@10.20.10.33/Streaming/Channels/102#video=h264
     garden_record:
      - rtsp://redacted:redacted@10.20.10.33/Streaming/Channels/101#video=h264

    house_front_detect:
      - rtspx://192.168.1.1:7441/jNTfu0xafcD75mYy
    house_front_record:
      - rtspx://192.168.1.1:7441/nLwsijWvdrnipjln

cameras:

  carport: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/carport_record
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          min_score: 0.7
          threshold: 0.8
          min_area: 700
    motion:
      mask:
        - 1029,0,1280,0,1280,720,961,720
      threshold: 20
      contour_area: 15
#    zones:
#      carport_area:
#        coordinates: 
#          0.557,0.133,0.44,0.118,0.308,0.124,0.192,0.412,0.145,0.392,0.03,0.517,0,0.585,0.089,1,0.755,1,0.769,0.822,0.78,0.675,0.791,0.519,0.793,0.34,0.798,0.197,0.755,0.185,0.619,0.151
#        objects:
#          - person
#          - dog
#          - cat
#        inertia: 3
#      carport_lights_zone:
#        coordinates: 
#          0.778,0.212,0.78,0.353,0.723,0.331,0.698,0.347,0.655,0.599,0.543,0.887,0.352,0.886,0.227,0.804,0.127,0.75,0.116,0.562,0.208,0.457,0.284,0.444,0.326,0.382,0.409,0.274,0.498,0.147
#        objects: person
#        inertia: 3
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 20
      detections:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 20
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      #required_zones:
      #- carport_area
#    review:
#      detections:
#        required_zones:
#          - carport_area
#          - carport_lights_zone

    zones:
      carport_detect:
        coordinates: 
          0.708,0.159,0.506,0.119,0.319,0.12,0.31,0.194,0.296,0.296,0.262,0.376,0.233,0.425,0.143,0.4,0.027,0.523,0.005,0.562,0.016,0.634,0.037,0.694,0.072,0.741,0.096,0.813,0.144,0.881,0.209,0.933,0.281,0.975,0.457,0.995,0.596,0.983,0.749,1,0.791,0.157
        loitering_time: 0
        objects:
          - person
          - dog
          - cat



  garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garden_record
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 700
    motion:
      mask:
        - 0.024,0.095,0.223,0.1,0.347,0.092,0.348,0.058,0.024,0.063,0.022,0.075
        - 0.098,0.383,0.174,0.732,0.255,0.99,0.004,0.992,0.001,-0.002,0.056,0,0.038,0.384
      threshold: 25
      contour_area: 10
      improve_contrast: true
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 20
      detections:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 20
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    zones:
      garden_area:
        coordinates: 
          0.445,0.99,0.26,1,0.163,0.657,0.094,0.363,0.045,0.373,0.052,0.114,0.235,0.129,0.316,0.112,0.315,0.049,0.405,0.135,0.461,0.174,0.506,0.199,0.587,0.256,0.672,0.319,0.846,0.48,1,0.657,1,1
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
        inertia: 3
  house_front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_front_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/house_front_record
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 24
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.5
          threshold: 0.7
          min_area: 700
    motion:
      mask: 0,0,0.259,0,0.449,0,0.474,0.064,0.299,0.127,0,0.591
      threshold: 30
      contour_area: 15
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 20
      detections:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 20
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    zones:
      house_front_detect:
        coordinates: 0.003,0.667,0.24,0.236,0.305,0.132,0.454,0.085,0.709,0.993,0.006,0.993
        loitering_time: 0

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: true
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
#

```

**Reply by hawkeye217** [reply]
I'd suggest changing your go2rtc source in the camera card as I suggested earlier. For `carport`, for example:

```
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
      stream: carport_record
```

Or, you could try setting up [improved live view](https://docs.frigate.video/configuration/live) in Frigate and then letting the advanced camera card just pull your config at that point.

**Reply by Symbiot78** [reply]
hmm. I changed to your suggestion, noticed the stream doesn't autoplay, but plays fine when I hit play. Added the autoplay options but still it only starts when I click the "play" button on the stream

```
cameras:
  - camera_entity: camera.carport
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
      stream: carport_record   
    icon: mdi:camera-iris
    dependencies:
      all_cameras: false
    capabilities:
      disable: []
  - camera_entity: camera.house_front
  - camera_entity: camera.garden
profiles: []
view:
  default: live
  camera_select: live
live:
  preload: false
  auto_play: [selected,visible]
```

**Reply by hawkeye217** [reply]
Since Frigate is working and your stream is displaying, this seems more like a card issue at this point, I'd suggest reaching out on their GitHub for further help. 

https://github.com/dermotduffy/advanced-camera-card

**Comment by Symbiot78** [comment]
tried opening in HA. That works. Opened the go2rtc web-interface, checked logs, checked the stream.
all seems to work as expected. but the issue is the same.

**Comment by Symbiot78** [comment]
added a card in HA using UI config for the card:

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.carport
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
view:
  default: live
  camera_select: live
live:
  preload: true
  auto_play:
    - visible
  show_image_during_load: true


``` 

if I remove the show_image_during_load then there is no 'stream'. 

=== 

EDIT: 
I remmed out the "auto_play" part. 
now it seems to stream as expected.
I'll need to verify some more..
