### DISCUSSION TITLE
Integrating a Custom Model into Frigate

### DISCUSSION THREAD

**Discussion by 7576457** [blakeblackshear/frigate#18145] [General]
Hi.

I saw the section in the documentation about detectors (https://docs.frigate.video/configuration/object_detectors/) — it explains which modules are supported and how to mount them (if I understood it correctly).

I have my own model that I want to integrate with Frigate. I think I’ve figured out how to mount it.

But I’m not sure how to connect my model’s output to Frigate’s backend.
How is Frigate supposed to receive the results from my model so it can save them to its database and show them in the interface like it does with the default model?

Do I need to set up an API in my model that is compatible with Frigate?
How does this work with the built-in model that comes by default?

Sorry if these are obvious questions — and if I missed something in the documentation, please feel free to point me to it.

**Comment by NickM-27** [comment]
What architecture is your model? Assuming your model is a supported architecture and is trained in a standard way it will work without any frigate code changes.

**Reply by 7576457** [reply]
YOLO Model

I read this section: https://docs.frigate.video/configuration/object_detectors/#yolox
From what I understand, I can simply specify my own model — including a YOLO model — and it should work without any changes to Frigate's code.

```yml
detectors:
  onnx:
    type: onnx
model:
  model_type: yolonas
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt
```

However, I don’t fully understand how this actually works.
If I mount the model in the config, how does Frigate interact with it?
How does it use the model to perform object detection?



I feel like I'm missing something simple, but I just can't quite see it...
