### DISCUSSION TITLE
[Config Support]: go2rtc: make main and substream from one source

### DISCUSSION THREAD

**Discussion by Solear** [blakeblackshear/frigate#18158] [Config Support] [answered]
### Describe the problem you are having

Hello! I can't get around a right configuration syntax. 
I would like to get one 4k h265 main stream and split it up to restream the main stream and a reencoded substream (FullHD h265). 
This:
Camerastream 4K => go2rtc => main stream 4k and sub stream FullHD

I do not understand how it's done. 
 

### Version

 0.16.0-5c3ac75

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  global_args: -hide_banner -loglevel warning -threads 2
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
  apple_compatibility: true

go2rtc:
 streams:
    carport:
      - rtsp://admin:password@192.168.1.120:554/h265Preview_01_main     #main restream is working
    carport_sub:
      - rtsp://admin:password@192.168.1.120:554/h265Preview_01_main     #two connections to webcam. how to copy main instead and reencode?
      - "ffmpeg:carport#width=1920#hight=1080"
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Proxmox

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

OpenVino

### Any other information that may be helpful

Intel Core Ultra iGPU, setup works fine with substream from cam. But I would like to make a own substream from the mainstream (because reolink substream is only
