### DISCUSSION TITLE
If motion is detected, then it runs detection also on Motion Mask zones ?

### DISCUSSION THREAD

**Discussion by primski** [blakeblackshear/frigate#18160] [Ask A Question]
It keeps detecting people walking on the street. Probably because it detects motion of the grass at the time when people are walking by ? 

I tried many different options for Threshold and contour area but i can't get it right. either i get tons of notifications or none at all, even if  someone walks to the door. cats also won't trigger it and that's my main focus. i know camera is not the best and it's quite far but cat walking through the yard, will rarely trigger it.

but there's a lot of noise for people walking by, to the point i often disable detection because it keeps spamming and then it defeats the purpose of having it in the first place.

not sure how to set this up for better detection? 

![image](https://github.com/user-attachments/assets/19da163b-254e-4d36-a489-7f0f68cead05)

**Comment by primski** [comment]
ok i just enabled this, didn't see it previously, should this help ? 

![image](https://github.com/user-attachments/assets/12631b2c-c1d3-487e-ab77-9d701e8ab279)

**Reply by primski** [reply]
Nope, this doesn't help either.

**Reply by hawkeye217** [reply]
Motion masks do not stop objects from being detected. You need to use required zones. See this tip post: https://github.com/blakeblackshear/frigate/discussions/13040

Also, remember that presence in a zone is dependent on the bottom center point of an object's bounding box. See the docs: https://docs.frigate.video/configuration/zones

You likely need to slightly move your zone away from the street.

**Reply by primski** [reply]
ah nice, thanks will try it out

**Reply by primski** [reply]
no, i can't get it right ...

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/1800c4d2-fe26-45e3-a9a6-daafe10c5a06" />


this keeps triggering

maybe because i have "All objects" ? 

<img width="491" alt="image" src="https://github.com/user-attachments/assets/79363b20-fad4-4f97-b52e-a2a2177b76bd" />

**Reply by primski** [reply]
i dont remember this being a problem a few versions ago ... has this behavior changed?

**Reply by hawkeye217** [reply]
You should look at the object lifecycle pane in Review or Explore to see where and when your object triggered the zone.

**Reply by primski** [reply]
it doesn't 

<img width="1914" alt="image" src="https://github.com/user-attachments/assets/8b57085c-a476-485d-bd28-480c94f611a6" />

**Reply by hawkeye217** [reply]
If your zone is not triggering, what is your issue, then?

Are you trying to prevent detections altogether on the street?

**Reply by primski** [reply]
yes i am trying to prevent detection on the street. at least HAAS Frigate Notification respects zone setting, so i can filter them out there so my phone doesn't buzz every 20 seconds but it would be better if frigate didn't even detect those. I still want to get notified if someone comes on my driveway, walks to the door or if a cat comes to take a shit on my lawn.

**Reply by hawkeye217** [reply]
You want to use an object mask, then. That will prevent objects from being detected.

See the tip I posted earlier: https://github.com/blakeblackshear/frigate/discussions/13040

And see the official documentation: https://docs.frigate.video/configuration/masks/#object-filter-masks

**Reply by NickM-27** [reply]
I think this would be a case of wanting to use a required zone, it seems likely the zone just needs to be set as required for detections and snapshots.

**Reply by primski** [reply]
i did follow your tip and this didn't work

> Using a zone for the sidewalk and then restricting alerts and/or detections to objects in that zone is the correct solution here. This can easily be done with the Frigate UI (0.14 and later).

i dont know if object mask will wok reliably as the model isn't very good, at least on my system without coral. it often detects cat as cow, dog, bear and smudge on the floor as person. that's why i have "all objects" enabled.

**Reply by NickM-27** [reply]
According to the last config posted required zones hasn't been set in the appropriate places

**Reply by primski** [reply]
i used gui and it added this

    review:
      alerts:
        required_zones: yard
      detections:
        required_zones: yard

**Reply by NickM-27** [reply]
You need to set required zones for snapshots as well

**Reply by hawkeye217** [reply]
>  dont know if object mask will wok reliably as the model isn't very good, at least on my system without coral. it often detects cat as cow, dog, bear and smudge on the floor as person. that's why i have "all objects" enabled.

Just make sure "All Objects" is selected when you create the object mask from the Mask/Zone editor in the UI.

**Reply by primski** [reply]
could you just share how

**Reply by NickM-27** [reply]
Just put the same `required_zones` block under `snapshot` in the config.

**Reply by primski** [reply]
that might have done it yes, will see after more testing

thanks

shouldn't one of the checkboxes in the UI put this in the config as well then ?

**Reply by NickM-27** [reply]
It is a separate setting, one that does not currently have a UI option

**Comment by Marijn0** [comment]
Personally, I would move your zone even further away from the street.
You can also go to 'Explore' and then to the 'Object Lifecycle' tab to easily see when an object entered your zone, 
and adjust your zone accordingly.

**Reply by primski** [reply]
thanks, but objects have not entered my zone at all. i also observed the debug page, waiting for boxes and i saw it live multiple times, there are no objects in my zone

the camera is quite far away and i want it to cover the doorway area if person walks up to the door

**Reply by primski** [reply]
only "label" pases through the zone and surely that can't be it ? 

<img width="1253" alt="image" src="https://github.com/user-attachments/assets/777cb062-aa00-4424-920d-9b4e7f4c7796" />

**Reply by Marijn0** [reply]
Did you read this?
https://docs.frigate.video/configuration/zones/#restricting-alerts-and-detections-to-specific-zones

**Reply by primski** [reply]
yes i read it

**Reply by Marijn0** [reply]
Then I’m not sure either.
It would be helpful if you could share your config.

**Reply by primski** [reply]
```
logger:
  default: info

tls:
  enabled: false

mqtt:
  host: IP
  port: 15883

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - dog
    - cat
    - bird
    - horse
    - sheep
    - cow
    - bear

birdseye:
  enabled: true
  # width: 800
  width: 1280

  #height: 600
  quality: 10
  mode: continuous

cameras:
  front:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://IP:19554/front
          roles:
            - record
        #- path: rtsp://IP:19554/front_sub
        - path: rtsp://IP:19554/front
          roles:
            - detect

    detect:
      #width: 1280
      #height: 720
      #fps: 5
      width: 1920
      height: 1080
      fps: 2

    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 1
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: false
      mask: 0.766,0.045,0.77,0.099,0.998,0.099,0.995,0.04
    snapshots:
      enabled: true
      retain:
        default: 30

    zones:
      yard:
        coordinates: 0,0.204,0.202,0.086,0.335,0.01,0.507,0.059,0.507,0,1,0,1,1,0,1,0,0.417
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: yard
      detections:
        required_zones: yard
    objects: {}
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p

go2rtc:
  streams:
    front: 
      ffmpeg:rtsp://admin:password@IP:554/user=admin_password=password_channel=1_stream=0&protocol=unicast.sdp?real_stream#video=h264
    front_sub: 
      ffmpeg:rtsp://admin:password@IP:554/user=admin_password=password_channel=1_stream=1&protocol=unicast.sdp?real_stream#video=h264
  webrtc:
    candidates:
      - IP:19554
version: 0.15-1

```
