### DISCUSSION TITLE
[Config Support]: Person detection only.

### DISCUSSION THREAD

**Discussion by Jrider64** [blakeblackshear/frigate#18166] [Config Support] [answered]
### Describe the problem you are having

I have been tuning my cameras to try to dial in object detections and performance. Recently I noticed that Frigate is only detection Person objects. This worked before I am assuming that this has to do with all the changes done to the configuration. 

Thank you for any help with trying to get this resolved.

![image](https://github.com/user-attachments/assets/ca895ed2-639b-4be5-84ea-695d5222e632)

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.10.2.199
  port: 1883
  user: **********
  password: *******
  client_id: frigate

go2rtc:
  api:
    origin: '*'
  streams:
    frontleft:
      - rtsp://admin:******@10.10.100.13:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:front_left#video=h264#audio=aac#hardware
    doorbell:
      - rtsp://admin:******@10.10.100.84:554/h264Preview_01_main#backchannel=0
      - ffmpeg:doorbell#audio=opus#hardware
    doorbell_sub:
      - rtsp://admin:******@10.10.100.84:554/h264Preview_01_sub
      - ffmpeg:rtsp://admin:******@10.10.100.84:554/h264Preview_01_sub#audio=opus
      #- "ffmpeg:http://10.10.100.84/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=******"
    driveway:
      - rtsp://admin:******@10.10.100.12:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway#video=h264#audio=aac#hardware
    backleft:
      - rtsp://admin:******@10.10.100.14:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:backleft#video=h264#hardware
    back:
      - rtsp://admin:******@10.10.100.15:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:back#video=h264#hardware
    backright:
      - rtsp://admin:******@10.10.100.16:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:backright#video=h264#audio=aac#hardware
    background:
      - rtsp://admin:******@10.10.100.3:554/H264/ch1/main/av_stream
      - ffmpeg:background#audio=aac#hardware
    background_sub:
      - rtsp://admin:******@10.10.100.3:554/H264/ch1/sub/av_stream
      - ffmpeg:background_sub#video=h264#hardware
    kitchen:
      - rtsp://admin:******@10.10.100.18:554/h264Preview_01_main
      - ffmpeg:kitchen#video=h264#audio=aac#hardware
    stairs:
      - rtsp://admin:******@10.10.100.45:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
      - ffmpeg:stairs#audio=aac#hardware
    stairs_sub:
      - rtsp://admin:******@10.10.100.45:554/Streaming/Channels/102
      - ffmpeg:stairs_sub#video=h264#hardware
  webrtc:
    listen: :8555
    candidates:
      - 10.10.2.190:8555
      - 10.10.2.136:8555
      - stun:8555

objects:
  track:
    - person
    - cat
    - dog
    - vehicle
  #filters:
  #  person:
  #    min_score: 0.5
  #    threshold: 0.7
  #  vehicle:
  #    min_score: 0.5
  #    threshold: 0.7
  #  cat:
  #    min_score: 0.5
  #    threshold: 0.8

birdseye:
  enabled: true
  width: 1280
  height: 720
  mode: objects
  layout:
    max_cameras: 4
    scaling_factor: 3.0

detectors:
  tensorrt:
    type: tensorrt
    device: 0

audio:
  enabled: false

review:
  alerts:
    labels:
      - person
      - car
  detections:
    labels:
      - person
      - car
      - cat
      - dog

snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
      mode: active_objects
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
      mode: active_objects
    pre_capture: 5
    post_capture: 5


ffmpeg:
  hwaccel_args: preset-nvidia
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-rtsp-restream


model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

cameras:
  frontleft:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontleft
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      frontleft_zone_detection:
        coordinates: 
          0.839,0.995,0.93,0.755,0.998,0.41,0.998,0.141,0.867,0.005,0.844,0.207,0.67,0.136,0.565,0.07,0.408,0.037,0.27,0.057,0.002,0.811,0.001,0.999
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - vehicle
      frontleft_zone_alert:
        coordinates: 
          0.828,0.313,0.689,0.231,0.624,0.207,0.091,0.606,0.003,0.821,0.005,0.997,0.836,0.996,0.931,0.76,1,0.411,0.968,0.3,0.887,0.263
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.003,0.114,0.185,0.003,0.002,0.003
        - 0.678,0,0.676,0.026,0.548,0.004
    review:
      alerts:
        required_zones: frontleft_zone_alert
      detections:
        required_zones: frontleft_zone_detection
  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      doorbell_zone_detection:
        coordinates: 
          0.001,0.994,0.001,0.701,0.204,0.586,0.434,0.582,0.537,0.563,0.615,0.574,0.583,0.092,0.633,0.001,0.998,0.001,0.997,0.999
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
      doorbell_zone_alert:
        coordinates: 
          0.003,0.768,0.002,0.697,0.084,0.653,0.571,0.625,0.615,0.639,0.703,0.004,0.999,0,0.999,0.997,0.003,0.995
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
        inertia: 3
    motion:
      threshold: 50
      contour_area: 18
      improve_contrast: true
    review:
      alerts:
        required_zones: doorbell_zone_alert
      detections:
        required_zones: doorbell_zone_detection
  driveway:
    enabled: true
    review:
      alerts:
        required_zones: driveway_zone_alert
      detections:
        required_zones: driveway_zone_detection
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      driveway_zone_detection:
        coordinates: 
          0.003,0.503,0.25,0.242,0.454,0.137,0.66,0.209,0.65,0.255,0.993,0.674,0.997,0.995,0.003,0.997
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - vehicle
      driveway_zone_alert:
        coordinates: 
          0.003,0.599,0.002,0.509,0.142,0.375,0.226,0.385,0.335,0.38,0.521,0.362,0.669,0.348,0.695,0.369,1,0.805,0.998,0.997,0.003,0.997
        loitering_time: 0
        inertia: 3
        objects:
          - cat
          - dog
          - person
          - vehicle
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
      mask: 0.583,0.008,0.649,0.062,0.769,0.098,0.987,0.136,0.993,0.004
  backleft:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backleft
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      backleft_zone_detection:
        coordinates: 0.617,0.285,0.995,0.329,0.998,0.573,0.761,0.999,0.539,0.996
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
      backleft_zone_alert:
        coordinates: 0.138,0.387,0.597,0.358,0.531,0.997,0.007,0.996,0.037,0.764,0.095,0.521
        loitering_time: 0
        objects: person
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
      mask: 0.109,0,0.138,0.232,0.09,0.379,0.004,0.684,0.003,0.003
    review:
      alerts:
        required_zones: backleft_zone_alert
      detections:
        required_zones: backleft_zone_detection
  back:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      back_zone_alert:
        coordinates: 
          0.116,0.226,0.216,0.114,0.289,0.184,0.364,0.15,0.402,0.182,0.42,0.304,0.479,0.485,0.687,0.793,0.622,0.997,0.396,1,0.269,0.736,0.156,0.429
        inertia: 3
        loitering_time: 0
        objects: person
      back_zone_detection:
        coordinates: 
          0.625,0.996,0.998,0.996,0.997,0.885,0.88,0.553,0.743,0.287,0.668,0.174,0.407,0.13,0.267,0.14,0.253,0.142,0.289,0.177,0.363,0.147,0.406,0.179,0.421,0.299,0.481,0.481,0.689,0.79
        loitering_time: 0
        objects: person
    motion:
      threshold: 30
      contour_area: 15
      improve_contrast: true
      mask:
        - 0.726,0.004,0.998,0,0.999,0.639,0.704,0.097
        - 0.073,0,0.105,0.203,0.127,0.317,0.152,0.414,0.177,0.51,0.201,0.592,0.237,0.753,0.297,0.937,0.312,0.997,0.001,0.996,0.002,0.003
    review:
      alerts:
        required_zones: back_zone_alert
      detections:
        required_zones: back_zone_detection
  backright:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backright
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      backright_zone_alert:
        coordinates: 0.129,0.22,0.329,0.122,0.809,0.71,0.837,0.999,0.126,0.997,0.214,0.634
        inertia: 3
        loitering_time: 0
        objects: person
      backright_zone_detection:
        coordinates: 
          0.361,0.156,0.384,0.131,0.538,0.11,0.674,0.273,0.758,0.392,0.877,0.588,0.97,0.796,0.997,0.881,0.998,0.997,0.839,0.996,0.81,0.705
        loitering_time: 0
        objects: person
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: true
      mask: 
        0.934,0.003,0.949,0.114,0.796,0.035,0.713,0.048,0.594,0.062,0.548,0.034,0.389,0.061,0.382,0.004
    review:
      alerts:
        required_zones: backright_zone_alert
      detections:
        required_zones: backright_zone_detection
  background:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/background
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/background_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      backgroud_zone_alert:
        coordinates: 
          0.069,0.321,0.241,0.003,0.788,0.003,0.999,0.607,0.929,0.999,0.002,0.996,0.002,0.621,0.084,0.415
        inertia: 3
        loitering_time: 0
        objects: person
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones: backgroud_zone_alert
      detections:
        required_zones: backgroud_zone_alert
  kitchen:
    birdseye:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      kitchen_zone_detection:
        coordinates: 
          0,0.621,0.002,0.332,0.338,0.272,0.413,0.234,0.67,0.217,0.911,0.29,0.876,0.429,0.767,0.746,0.649,0.997,0.421,1
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      detections:
        required_zones: kitchen_zone_detection
    motion:
      threshold: 41
      contour_area: 10
      improve_contrast: true
      mask: 0.967,0.182,0.006,0.197,0.001,0,0.994,0.001,0.998,0.18
  stairs:
    birdseye:
      enabled: false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/stairs
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/stairs_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      stairs_zone_detection:
        coordinates: 
          0.998,0.994,0.996,0.207,0.903,0.241,0.845,0.032,0.82,0.027,0.585,0.127,0.325,0.382,0.297,0.737,0.578,0.999
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: []
      detections:
        required_zones: stairs_zone_detection
    motion:
      mask: 0.422,0.003,0.142,0.999,0.003,0.997,0.001,0.003
      threshold: 34
      contour_area: 25
      improve_contrast: true
version: 0.15-1
camera_groups:
  Front:
    order: 1
    icon: LuArrowBigUp
    cameras:
      - frontleft
      - doorbell
      - driveway
  Back:
    order: 2
    icon: LuArrowBigDown
    cameras:
      - backleft
      - back
      - backright
      - background
  Inside:
    order: 3
    icon: LuArchiveRestore
    cameras:
      - strairs
      - kitchen
  Outside:
    order: 4
    icon: LuArchive
    cameras:
      - driveway
      - frontleft
      - backleft
      - back
      - backright
      - doorbell
      - background
  Birdseye:
    order: 5
    icon: LuAperture
    cameras: birdseye
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    network_mode: "host"
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    privileged: true
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - YOLO_MODELS=yolov7x-640
    shm_size: "512m"
    volumes:
      - /etc/ssl/********:/etc/letsencrypt/live/frigate:ro
      - /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro
      - ./config:/config
      - ./storage:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "443:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp"
      - "8555:5555/udp"
      - "10.10.2.190:5000:5000" # HA
      - "1984:1984"
```

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/2394aef8-f3bb-4e2b-bf20-eb1b259e1a2d)
