### DISCUSSION TITLE
The files in /storage/clips/review are not being deleted.

### DISCUSSION THREAD

**Discussion by hh-TDA** [blakeblackshear/frigate#18179] [Report a Bug] [answered]
While monitoring the HDD used for recordings on multiple Frigate servers, I noticed that one server has an unusually large amount of recorded data.

Upon checking the directory, I found that the number of files in /storage/clips/review is significantly high:
```bash
find . -type f | wc -l
248698
```
I tried to check the storage size, but it seemed like the system would freeze, so I stopped.

Is it safe to delete the files in the review directory while Frigate is running?

The retain settings are as follows:
```yaml
record:
  enabled: true
  retain:
    days: 19
    mode: all
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1

```

**Comment by hawkeye217** [comment]
Why do you think the system would freeze?

Do you have snapshots set up in your config?

**Reply by hh-TDA** [reply]
I tried to check the files first, but there were too many, and the server stopped responding when I ran the command just to list the file names.
I don't have snapshots set up in my configuration.

**Reply by hawkeye217** [reply]
What version of Frigate are you using?

**Reply by hh-TDA** [reply]
I am using version 0.15.0-cea210d.

**Comment by NickM-27** [comment]
Do you have per-camera retain settings set? You can delete them if they are old enough, but this would be odd. It would be good to see your docker configuration

**Reply by hh-TDA** [reply]
The record settings are configured only in this section:
```yaml
record:
  enabled: true
  retain:
    days: 19
    mode: all
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1


```

**Reply by NickM-27** [reply]
Need to see the docker config then

**Reply by hh-TDA** [reply]
```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.15.0-tensorrt
    container_name: frigate-gpu
    build:
      context: ./Frigate
      dockerfile: Dockerfile
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 48G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] # number of GPUs -> 
              capabilities: [gpu]
    shm_size: "64gb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/NVR_Environment/Frigate/config:/config
      - /home/NVR_Environment/Frigate/trt-models:/trt-models
      - /home/NVR_Environment/Frigate/storage:/media/frigate
      - /mnt/myhdd/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 3000000000
    ports:
      - "8971:8971" # ssl port
      - "5000:5000" # non authenticated API
      - "1984:1984" # go2rtc
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: "myname"
      FRIGATE_RTSP_PASSWORD: "mysecretpassword"
      YOLO_MODELS: yolov7x-320,yolov7x-640 # Add your models here
```

**Comment by hawkeye217** [comment, marked as answer]
This looks like a bug.

This directory contains the thumbnails for your review items. You can probably just manually remove the files with a date outside of your retention period.

**Reply by hh-TDA** [reply]
Thank you. I'll try deleting them manually. Is it safe to delete the files while Frigate is running?

**Reply by hawkeye217** [reply]
Yes

**Reply by hh-TDA** [reply]
Thank you

**Reply by hawkeye217** [reply]
One fast way to do this would be to just run `find . -type f -mtime +19 -delete` (19 matches your retain configuration)

To see the files that would be deleted first, you can run `find . -type f -mtime +19 -ls`

**Reply by hawkeye217** [reply]
This bug is fixed in https://github.com/blakeblackshear/frigate/pull/18176 and will be included in Frigate 0.16.0 beta 2 and later.

**Reply by hh-TDA** [reply]
I was able to delete them. Now I see that there are also old files left in the previews, so I’ll try deleting them as well.
Thank you!

**Reply by hawkeye217** [reply]
Frigate does delete the preview videos themselves, so you shouldn't have nearly as many of these. Perhaps they were orphaned during a crash, unclean shutdown, or upgrade.

**Reply by rhatguy** [reply]
Has this fix been confirmed working?  I have a retain config which keeps alerts and detections up to 365.  I'm running 16.0-beta2.  I have many files in clips/review older than 7 days, but with no recordings/snapshots to go along with them.  Should I manually clean up the clips/review folder of old stuff, or should Frigate clean up the existing mess?  Don't want to orphan any database entries...etc.

```
record: 
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 365
  detections:
    retain:
      days: 365
```
