### DISCUSSION TITLE
[Support]: error="size 1436 < 33000: RTP header size insufficient for extension"

### DISCUSSION THREAD

**Discussion by MartinFerenec** [blakeblackshear/frigate#18173] [General Support] [answered]
### Describe the problem you are having

I have multiple cameras and every once in a while recording for some of them fail until I restart frigate. Please check logs below.

GPU: Nvidia RTX 3050

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
#Irrelevant cameras redacted; some security config redacted.

version: 0.15-1

tls:
  # Optional: Enable TLS for port 8971 (default: shown below)
  enabled: true

mqtt:
  enabled: true
  host: 192.168.1.20
  port: 1883
  topic_prefix: frigate
  client_id: frigate

auth:
  # Optional: Enable authentication
  enabled: true
  # Optional: Reset the admin user password on startup (default: shown below)
  # New password is printed in the logs
  reset_admin_password: false
  # Optional: Cookie to store the JWT token for native auth (default: shown below)
  cookie_name: frigate_token
  # Optional: Set secure flag on cookie. (default: shown below)
  # NOTE: This should be set to True if you are using TLS
  cookie_secure: false
  # Optional: Session length in seconds (default: shown below)
  session_length: 86400 # 24 hours
  # Optional: Refresh time in seconds (default: shown below)
  # When the session is going to expire in less time than this setting,
  # it will be refreshed back to the session_length.
  refresh_time: 43200 # 12 hours
  # Optional: Rate limiting for login failures to help prevent brute force
  # login attacks (default: shown below)
  # See the docs for more information on valid values
  failed_login_rate_limit: 1/second;5/minute;20/hour
  # Optional: Trusted proxies for determining IP address to rate limit
  # NOTE: This is only used for rate limiting login attempts and does not bypass
  # authentication. See the authentication docs for more details.
  trusted_proxies: []
  # Optional: Number of hashing iterations for user passwords
  # As of Feb 2023, OWASP recommends 600000 iterations for PBKDF2-SHA256
  # NOTE: changing this value will not automatically update password hashes, you
  #       will need to change each user password for it to apply
  hash_iterations: 600000

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/8.5.3/yolov7-tiny-416.trt
  labelmap_path: /labelmap/coco-80.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

ffmpeg:
  hwaccel_args: preset-nvidia
  output_args:
    record: preset-record-generic-audio-aac
  input_args: preset-rtsp-restream

audio:
  enabled: true
  listen:
    - dog
    - cat
    - fire_alarm
    - scream
    - speech

record:
  enabled: true
  retain:
    days: 14
    mode: all
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 30
      mode: motion

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: false
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
    objects:
      person: 60
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 90

go2rtc:
  rtsp:
    username: X
    password: Y
  webrtc:
    candidates:
      - 192.168.1.20:8555
      - stun:8555
  streams:
    robomower:
      - rtsp://X:Y@192.168.1.159:554/stream1
      - ffmpeg:robomower#audio=aac
      - tapo://admin:Y@192.168.1.159
    robomower-lq:
      - rtsp://X:Y@192.168.1.159:554/stream2
      - ffmpeg:robomower-lq#audio=aac


cameras:
  robomower:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/robomower-lq
          roles:
            - detect
            - audio

        - path: rtsp://127.0.0.1:8554/robomower
          roles:
            - record
    live:
      stream_name: robomower
      quality: 31
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person
        - animal
        - cat
        - dog
    motion:
      mask: 0.001,0.051,0.335,0.05,0.334,0,0.002,0.006
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Sunseeker_dock:
        coordinates: 0.071,0.935,0.259,0.915,0.232,0.735,0.055,0.745
        loitering_time: 0
      Sunseeker_platform:
        coordinates: 0.306,0.707,0,0.739,0,1,0.798,1,0.858,0.879,0.337,0.713
        loitering_time: 0

camera_groups:
  Outdoor:
    order: 1
    icon: LuTrees
    cameras:
      - robomower
      - terrace
```

### Relevant Frigate log output

```shell
2025-05-12 06:42:21.750888062  06:42:21.750 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="size 1436 < 33000: RTP header size insufficient for extension" url=rtsp://mf737UHs4Byx:4rXmwWZRY3kZDsoQB0j0q5U7Wm1RfQTp@192.168.1.159:554/stream2
2025-05-12 06:42:43.999857085  [2025-05-12 06:42:43] watchdog.robomower             INFO    : robomower exceeded fps limit. Exiting ffmpeg...
2025-05-12 06:42:43.999934399  [2025-05-12 06:42:43] watchdog.robomower             INFO    : Waiting for ffmpeg to exit gracefully...
2025-05-12 06:43:13.308213382  127.0.0.1 - - [12/May/2025:06:43:13 +0200] "" 400 0 "-" "-" "-"
2025-05-12 06:44:13.319890435  127.0.0.1 - - [12/May/2025:06:44:13 +0200] "" 400 0 "-" "-" "-"
2025-05-12 06:44:16.040037251  [2025-05-12 06:44:16] frigate.record.maintainer      WARNING : Too many unprocessed recording segments in cache for robomower. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...

From this point forward the "Too many unprocessed recording segments..." log gets repeated until I restart Frigate.
```

### Relevant go2rtc log output

```shell
/
```

### FFprobe output from your camera

```shell
Stream 1
Video:
Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1280x720 (16/9 aspect ratio)
FPS: 20/1
Audio:
Codec: AAC (Advanced Audio Coding)
Stream 2
Video:
Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2688x1520 (168/95 aspect ratio)
FPS: 20/1
Audio:
Codec: AAC (Advanced Audio Coding)
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    runtime: nvidia
    restart: unless-stopped
    privileged: true
    shm_size: "2048M"  # Required for detection
    memswap_limit: 10240M # Disable SWAP (when set same than memory limit)
    volumes:
      - /mnt/NvmeVolume1/100/Portainer/Frigate/config:/config
      - /mnt/NvmeVolume1/100/Portainer/Frigate/media:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5010:8971  # Web UI with auth
      - 127.0.0.1:5000:5000  # Local only: Web UI
      - 1935:1935  # RTMP
      - 8554:8554  # RTSP Restream
      - 8555:8555  # WebRTC
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - FRIGATE_RTSP_PASSWORD:"redacted"
      - YOLO_MODELS=yolov7-tiny-416
      - NVIDIA_VISIBLE_DEVICES:all
      - NVIDIA_DRIVER_CAPABILITIES:all
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 10240M
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

Tp-Link TAPO C325WB

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/f110cef0-f134-4c04-bb28-865008ba5795)

**Comment by hawkeye217** [comment, marked as answer]
This error from go2rtc indicates errors with your camera stream. One suggestion would be to try the ffmpeg source, eg:

```
go2rtc:
  streams:
    robomower:
      - ffmpeg:rtsp://X:Y@192.168.1.159:554/stream1
      ...
```
