### DISCUSSION TITLE
Feeling that object recognition is getting worse with every model learning

### DISCUSSION THREAD

**Discussion by AdmiralRaccoon** [blakeblackshear/frigate#18177] [Ask A Question]
Hi there,
I´m using Frigate+ since the end of march, submitted 300 images so far and requested 4 Models by now, but I have the feeling that I get more and more false positives. 
Anything that I can do about it?  Submit more images? Creating more object masks?

Thanks for some hints,
Philipp

A few examples:

My dog is a cat (very often)
![image](https://github.com/user-attachments/assets/fe6f4971-1290-48f8-bdf4-950ef8b3e88c)
![image](https://github.com/user-attachments/assets/5a539856-96fe-4db0-bbe0-67c9d3856ca0)

The doorstep is a package, when the sun shines onto it at noon.
![image](https://github.com/user-attachments/assets/6264fa1b-0e52-4624-b8ad-35a2b1707e5f)

Random things are persons:
![image](https://github.com/user-attachments/assets/f8ea8acc-eb18-4147-8651-ea760b49d2d1)
![image](https://github.com/user-attachments/assets/02e73a86-3c8c-4119-b4ec-6eaded909bf1)
![image](https://github.com/user-attachments/assets/342fe603-514e-4b5e-98a4-093bb6919af1)

**Comment by hawkeye217** [comment]
Your scores are extremely low. What is your config?

**Comment by NickM-27** [comment]
It would be good if we could see the config, you might also want to review the labeling guide to ensure the images have been labeled correctly https://docs.frigate.video/plus/improving_model

**Comment by AdmiralRaccoon** [comment]
This is my entire config, I hope it´s not too messed up.
About labeling: I think I did labeling right, in most cases, the "suggestions" tab already corrected the misidentified object (Mostly the dog / cat thing".



````
mqtt:
  host: 192.168.1.99
  user: ****
  password: *****

#birdseye:
#  enabled: True
#  mode: objects

go2rtc:
  streams:
    cam_haustuer:
      - rtsp://administrator:****@192.168.1.97:554/stream1
    cam_wohnzimmer:
      - rtsp://administrator:****@192.168.1.96:554/stream1
    cam_garten:
      - rtsp://administrator:****@192.168.1.94:554/stream1
    cam_garage:
      - rtsp://administrator:****@192.168.1.87:554/stream1
    cam_carport:
      - rtsp://administrator:****@192.168.1.85:554/stream1


genai:
  enabled: false
  provider: gemini
  api_key: *****
  model: gemini-1.5-flash

cameras:
  cam_haustuer:
    mqtt:
      required_zones:
        - zone_eingang
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://administrator:****@192.168.1.97:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: 0.591,0,0,0,0,0.35,0.154,0.219,0.259,0.126,0.253,0.085
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - face
        - dhl
        - amazon
        - ups
        - gls
        - dpd
      mask: 0.003,0.156,0.003,0.004,0.558,0,0.228,0.07
      filters:
        package:
          mask:
            - 0.003,0.156,0.003,0.004,0.558,0,0.228,0.07
            - 0.82,0.004,0.742,0.738,0.749,0.997,0.999,0.997,0.999,0
        dog:
          mask:
            - 0.003,0.156,0.003,0.004,0.558,0,0.228,0.07
            - 0.512,0.271,0.556,0.163,0.585,0.004,0.816,0.002,0.779,0.364
            - 0.003,0.156,0.003,0.004,0.558,0,0.228,0.07
            - 0.002,0.5,0.245,0.193,0.32,0.078,0.399,0.112,0.438,0.171,0.331,0.312,0.302,0.325,0.253,0.36,0.036,0.648
            - 0.003,0.156,0.003,0.004,0.558,0,0.228,0.07
        cat:
          mask:
            - 0.003,0.156,0.003,0.004,0.558,0,0.228,0.07
            - 0.026,0.67,0.005,0.499,0.188,0.264,0.332,0.117,0.43,0.18,0.307,0.313
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - zone_eingang
      retain:
        default: 30
        objects:
          person: 30
          dog: 5
          cat: 5
          package: 5
    genai:
      enabled: false
      use_snapshot: true
    zones:
      zone_eingang:
        coordinates: 1,1,1,0,0.62,0,0.441,0.043,0.261,0.088,0.252,0.137,0.072,0.296,0,0.347,0,1
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: zone_eingang
        labels:
          - car
          - cat
          - dog
          - person
          - face
          - dhl
          - dpd
          - ups
          - amazon
          - package
      detections: {}

  cam_wohnzimmer:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://administrator:****@192.168.1.96:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      alerts:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 7
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - face
        - dog
        - cat
      mask: 0.513,0.61,0.594,0.526,0.494,0.487,0.422,0.467,0.358,0.526,0.352,0.565
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          dog: 10
          cat: 10
    zones:
      zone_schiebetuer:
        coordinates: 0.173,0.763,0.113,0.276,0.008,0.33,0,0.456,0.06,0.852
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
      zone_tueren:
        coordinates: 
          0.621,0.192,0.951,0.191,0.942,0.521,0.866,0.51,0.732,0.879,0.422,0.738,0.596,0.527
        loitering_time: 0
    review:
      alerts:
        required_zones: zone_schiebetuer
        labels:
          - cat
          - dog
          - person
          - face
    genai:
      enabled: false
      use_snapshot: true

  cam_garten:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://administrator:****@192.168.1.94:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - dog
        - cat
        - face
        - raccoon
        - squirrel
        - rabbit
      mask: 0.996,0.34,0.671,0.147,0.673,0.003,0.995,0.008
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - zone_garten
      retain:
        default: 30
        objects:
          person: 30
          dog: 5
          cat: 5
    genai:
      enabled: false
      use_snapshot: true
    motion:
      mask:
        - 0.207,0.465,0.199,0.219,0.142,0.231,0.146,0.483
        - 0.279,0.44,0.274,0.147,0.444,0.051,0.554,0,0.667,0,0.669,0.141,0.58,0.437,0.52,0.479
        - 0.669,0,0.671,0.149,0.993,0.343,0.997,0.003,0.889,0.001
    zones:
      zone_garten:
        coordinates: 
          0,1,0.148,1,1,1,1,0,0.567,0,0.442,0.047,0.426,0.424,0.283,0.444,0.282,0.143,0.205,0.206,0.209,0.455,0.145,0.476,0.139,0.231,0,0.254
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: zone_garten
        labels:
          - cat
          - dog
          - person
      detections: {}

  cam_carport:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://administrator:****@192.168.1.85:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - package
        - face
        - cat
      filters:
        package:
          min_area: 0
          min_ratio: 0
          max_ratio: 1000
          min_score: 0
          threshold: 0.2
          mask: 0.188,1,0.554,1,0.366,0.655,0.266,0.451,0.226,0.474,0.2,0.413,0.076,0.466
        cat:
          mask: 0.875,0.733,0.445,0.354,0.46,0.018,0.723,0.076,0.977,0.247
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          package: 30
    genai:
      enabled: false
    review:
      alerts:
        labels:
          - package
          - cat
          - person
        required_zones:
          - carport_general
          - carport_package
      detections: {}
    motion:
      threshold: 15
      contour_area: 10
      improve_contrast: true
    zones:
      carport_general:
        coordinates: 0.074,0.123,0.09,0.464,0.2,0.405,0.4,0.987,0.998,0.999,0.999,0.259,0.461,0.009
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - person
      carport_package:
        coordinates: 0.269,0.454,0.44,0.399,0.684,0.635,0.534,0.767,0.476,0.845
        loitering_time: 10
        objects: package
        inertia: 3

  cam_garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://administrator:****@192.168.1.87:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
      alerts:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
      detections:
        retain:
          days: 30
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
        - face
        - car
        - license_plate
      mask: 0.771,0.052,1,0.119,1,0.476,1,1,0.843,0.624,0.69,0.42,0.697,0.057
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
        objects:
          person: 30
          package: 30
    genai:
      enabled: false
    review:
      alerts:
        labels:
          - person
          - face
          - car
          - license_plate
        required_zones: zone_garage
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      zone_garage:
        coordinates: 0.206,0.061,0,0.143,0,0.69,0,1,1,1,0.863,0.657,0.666,0.366,0.697,0.008
        loitering_time: 0
        inertia: 3
        objects:
          - car
          - person
          - face
          - 
detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://****

version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```
