### DISCUSSION TITLE
[Config Support]: Config fails to update when editing masks and zones

### DISCUSSION THREAD

**Discussion by MarkSTho** [blakeblackshear/frigate#18185] [Config Support]
### Describe the problem you are having

when editing the camera settings to select/change zones for alerts and detections, i can make the selection in the GUI, but it fails to save the edit into the config file.  the error also occurs when attempting to change of create motion masks.
However, If i try to save annotation offsets from the tracked objects details page, that works ok and writes to the config file.  

### Version

5.9.2/0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: zzzz
  password: xxxxxxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  restream: true  # must be a boolean
  width: 1280
  height: 720
  quality: 9
  mode: continuous  # valid: objects | motion | continuous
  inactivity_threshold: 30
  layout:
    scaling_factor: 1.0      # Zooms the camera boxes to better fill the screen

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-copy

# detect:
  # width: 1920
  # height: 1080
  # fps: 5
  # enabled: true
  # min_initialized: 2
  # max_disappeared: 25
  # stationary:
  #  interval: 50
  #  threshold: 50

objects:
  track:
    - person
    - car

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - car
      - person

motion:
  enabled: true
  # threshold: 30
  lightning_threshold: 0.8
  # contour_area: 10

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 0
    mode: all
  preview:
    quality: high
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: motion
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 14
    objects:
      person: 30
      car: 10
  quality: 95

go2rtc:
  streams:
    front_door:
      - rtsp://admin:xxxxx@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2
      # - ffmpeg:front_door#audio=opus
    garage_ext:
      - rtsp://admin:xxxx@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2
      # - ffmpeg:garage_ext#audio=opus
    front_yard:
      - rtsp://admin:xxxx@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2
    garage_int:
      - rtsp://admin:xxxx@192.168.1.244:554/cam/realmonitor?channel=1&subtype=2
  api:
    listen: 0.0.0.0:1984

ui:
  time_format: 24hour
  date_style: short
  time_style: medium

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 0
    blue: 0
  thickness: 2
  effect:

cameras:
  front_door:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:xxxxx@192.168.1.241:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
        # - path: rtsp://admin:xxxxx@192.168.1.241:554/cam/realmonitor?channel=1&subtype=0
          # input_args: preset-rtsp-restream
          # roles:
            # - record
            # - audio
    live:
      stream_name: front_door
    birdseye:
      order: 3
    audio:
      enabled: false
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true

    zones:
      FP:
        coordinates: 
          0.047,0.312,0.143,0.251,0.3,0.21,0.299,0.544,0.39,0.647,0.459,0.604,0.456,0.544,0.602,0.435,0.623,0.446,0.601,0.742,0.79,0.869,0.768,0.991,0.127,0.991,0.08,0.776,0.12,0.749
        loitering_time: 0
        objects: person


  garage_ext:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@192.168.1.242:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
        # - path: rtsp://admin:xxxxx@192.168.1.242:554/cam/realmonitor?channel=1&subtype=0
          # input_args: preset-rtsp-restream
          # roles:
            # - record
            # - audio
    live:
      stream_name: garage_ext
    birdseye:
      order: 4
    audio:
      enabled: false
    detect:
      enabled: true
      width: 1920
      height: 1080
    objects:
      track:
        - person
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true

    zones:
      GE:
        coordinates: 
          0.007,0.523,0.266,0.487,0.883,0.666,0.913,0.747,0.938,0.761,0.953,0.823,0.93,0.818,0.962,0.986,0.008,0.99
        loitering_time: 0
        objects: person
        inertia: 3
  front_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@192.168.1.243:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
        # - path: rtsp://admin:xxxxx@192.168.1.243:554/cam/realmonitor?channel=1&subtype=0
          # input_args: preset-rtsp-restream
          # roles:
            # - record
    live:
      stream_name: front_yard
    birdseye:
      order: 1
    detect:
      enabled: true
      width: 1920
      height: 1080
      annotation_offset: -2250
    objects:
      track:
        - person
        - car
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true

    zones:
      FY:
        coordinates: 
          0.056,0.258,0.271,0.177,0.384,0.164,0.59,0.15,0.774,0.165,0.998,0.325,0.993,0.594,0.9,0.575,0.859,0.836,0.744,0.84,0.63,0.986,0.006,0.99,0.005,0.287
        loitering_time: 0
        inertia: 3
  garage_int:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@192.168.1.244:554/cam/realmonitor?channel=1&subtype=2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
        # - path: rtsp://admin:xxxxxx@192.168.1.244:554/cam/realmonitor?channel=1&subtype=0
          # input_args: preset-rtsp-restream
          # roles:
            # - record
    live:
      stream_name: garage_int
    birdseye:
      order: 2
    detect:
      enabled: true
      width: 1280
      height: 720
      annotation_offset: -2750
    objects:
      track:
        - person
    motion:
      threshold: 30
      contour_area: 10

version: 0.15-1

semantic_search:
  enabled: true
  reindex: false
  model_size: small

camera_groups:
  Front:
    order: 2
    icon: LuLocateFixed
    cameras:
      - front_door
      - front_yard
  Garage:
    order: 3
    icon: LuWarehouse
    cameras:
      - garage_ext
      - garage_int
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Relevant Frigate log output

```shell
2025-05-12 19:39:44.324554559  172.30.32.2 - - [12/May/2025:15:39:44 -0400] "PUT /api/config/set?=&cameras.front_door.review.detections.required_zones=FP HTTP/1.1" 500 51 "https://izqldln4w8b0o2joy65rnx0sb3lpwcf2.ui.nabu.casa/api/hassio_ingress/v669s0yNAEFGDEs8UNiTK8y7rM2qHyoIWXEdRpQDBmg/settings" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36" "209.49.153.154, 127.0.0.1, 172.30.32.1"
2025-05-12 19:39:44.324919907  [2025-05-12 15:39:44] root                           ERROR   : Error updating config: ''
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

Coral

### Any other information that may be helpful

![image](https://github.com/user-attachments/assets/fa9ef81d-262b-430d-835f-9dd65a09b837)
![image](https://github.com/user-attachments/assets/741fd07c-480e-4e23-9b48-e2080d41b88c)
![image](https://github.com/user-attachments/assets/a692e458-87a1-444e-8a9f-a122cc9a1fc7)
