### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by B0ndo2** [blakeblackshear/frigate#18184] [Config Support]
### Describe the problem you are having

A person is detected (Shows under alert)  on the sidewalk zone even though I only set it up for cars.
I don't want people walking on the sidewalk to trigger an alert. Usually those on the sidewalk show on detections

![image](https://github.com/user-attachments/assets/d98e47eb-e8a2-440d-b179-54e4e852215e)

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
driveway:
    timestamp_style:
      position: tr
      color:
        red: 255
        green: 0
        blue: 0
    zones:
      drive_way:
        coordinates: 
          0.406,0.147,0.491,0.148,0.636,0.152,0.732,0.174,0.768,0.258,0.817,0.552,0.856,0.76,0.857,0.821,0.774,0.909,0.676,0.987,0.246,1,0.257,0.355,0.284,0.171
        objects:
          - person
          - car
        #inertia: 0
        loitering_time: 0
      apron:
        coordinates: 0.612,0.09,0.59,0.045,0.38,0.047,0.363,0.076,0.515,0.076
        inertia: 3
        loitering_time: 0
        objects: car
      sidewalk:
        coordinates: 
          0.21,0.139,0.37,0.082,0.477,0.076,0.595,0.092,0.616,0.101,0.756,0.141,0.758,0.177,0.667,0.149,0.612,0.134,0.561,0.142,0.483,0.142,0.399,0.141,0.225,0.173,0.179,0.191
        inertia: 2
        loitering_time: 1
        objects: car
      #front_yard:
      #  coordinates: 0.734,0.171,0.769,0.254,0.818,0.54,0.862,0.758,0.974,0.606,0.835,0.232
      #  inertia: 1
      #  loitering_time: 0
      #  objects: person
    objects:
      track:
        - person
        - car
      filters:
        person:
          #mask: 
            #0.322,0.133,0.456,0.125,0.489,0.132,0.521,0.135,0.555,0.137,0.597,0.14,0.62,0.138,0.637,0.142,0.625,0.111,0.552,0.083,0.475,0.079,0.441,0.087,0.214,0.129,0.18,0.173
          min_score: 0.6
          threshold: 0.6
          min_area: 1300
          max_area: 120000
        car:
          min_area: 5000
          max_area: 300000
          min_score: 0.55
          threshold: 0.65

    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:Mohamed21@192.168.6.140/1
        #- path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
            - audio
            - record
     #   - path: rtsp://admin:Mohamed21@192.168.6.140/1
          #input_args: preset-rtsp-restream
      #    roles:
      #      - record

    audio:
      enabled: false
      min_volume: 600
      listen:
        - scream
        - speech
        - yell
    detect:
      width: 1280
      height: 720
#      fps: 5
      #stationary:
        #interval: 0
      #  threshold: 50
    motion:
      mask:
        - 0,0,0.283,0,0.156,0.225,0.068,0.499,0.009,0.869,0,0.861
        - 1,0,0.739,0,0.764,0.181,0.892,0.278,1,0.531
        - 0.366,0.039,0.597,0.05,0.628,0.071,0.69,0.082,0.755,0.136,0.741,0,0.284,0,0.241,0.076
        - 1,0.677,0.728,0.993,0.998,0.998
      threshold: 65
      contour_area: 54
      frame_height: 150
      lightning_threshold: 0.7
      improve_contrast: true
    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 1
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - drive_way
        - apron
      #  - front_yard
      timestamp: true
      retain:
        default: 7
    review:
      alerts:
        labels:
          - car
          - person
        required_zones:
          - drive_way
          - apron
        #  - front_yard
      detections: {}
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
NA
```

### Object Detector

Coral
