### DISCUSSION TITLE
[Camera Support]: One camera stopped recording after 0.16.0-beta1 upgrade

### DISCUSSION THREAD

**Discussion by mdacrema** [blakeblackshear/frigate#18190] [Camera Support] [answered]
### Describe the problem you are having

If I upgrade to frigate 0.16.0-beta1 only one of my 5 cameras stop recording. I'm able to see the live stream and also detection is working by also saving snapshots. Changing detection/recording between main and sub streams doesn't show any difference. 
I enabled debug logs and compared between version 0.15.1 which is working and 0.16.0-beta1 and the only difference is that in the working versions I can see the log the line that says it's copying the video to disk: 
`2025-05-13 10:02:46.681381925  [2025-05-13 10:02:46] frigate.record.maintainer      DEBUG   : Copied /media/frigate/recordings/2025-05-13/08/`.

Tried switching between different h264, h265 and h265+ and qsv/vaapi settings but nothing changes.
This camera is different from the others but the configuration is the same.

On the UI I can see recording is enabled. If I disable and then re-enable it appears in the logs but recordings are never saved.

Note that I've rolled back from 0.16.0-beta1 to 0.15.1 so logs are from 0.15.1 version.

### Version

0.16.0-beta1

### Frigate config file

```yaml
logger:
  default: debug
mqtt:
  enabled: true
  host: ######
  port: ######
  user: ######
  password: ######
semantic_search:
  enabled: true
  reindex: false
  model_size: large
    #classification:
    #bird:
    #enabled: false
      #face_recognition:
      #enabled: true
      #model_size: large
      #lpr:
      #enabled: True
      #device: GPU
      #model_size: large
detectors:
  ov:
    type: openvino
    device: GPU
birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080
model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_m.onnx
  labelmap_path: /labelmap/coco-80.txt
    #coral:
    #type: edgetpu
    #device: usb
go2rtc:
  streams:
    patio:
      - rtsp://######:######@######:554/Preview_01_main
      - ffmpeg:rtsp_cam#audio=opus
    patio_sub:
      - rtsp://######:######@######:554/Preview_01_sub
    box_retro:
      - rtsp://######:######@######//Streaming/channels/101
      - ffmpeg:rtsp_cam#audio=opus
    box_retro_sub:
      - rtsp://######:######@######//Streaming/channels/103
    box:
      - rtsp://######:######@######//Streaming/channels/101
    box_sub:
      - rtsp://######:######@######//Streaming/channels/103
    giardino:
      - rtsp://######:######@######//Streaming/channels/101
    giardino_sub:
      - rtsp://######:######@######//Streaming/channels/102
    cancello:
      - rtsp://######:######@######/h264_stream
        #cancello_sub:
        #- rtsp://######:554/h264cif?username=######&password=######
review:
  alerts:
    labels:
      - car
      - cat
      - dog
      - person
      - speech
      - bycicle
      - umbrella

cameras:
  patio:
    enabled: true
    ffmpeg:
      # hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/patio_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
    audio:
      enabled: true # <- enable audio events for the front_camera
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: true
    motion:
      threshold: 20
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.652,0.035,0.639,0,1,0,1,0.207,0.902,0.145,0.819,0.092,0.728,0.054
    zones:
      Patio:
        coordinates:
          0.406,0.147,0.416,0.07,0.422,0,0.001,0.002,0,0.996,0.998,0.998,1,0.765,0.427,0.155
        inertia: 3
        loitering_time: 0
      Giardino_retro:
        coordinates:
          0.416,0,0.632,0,0.648,0.03,0.734,0.055,0.816,0.092,0.932,0.163,1,0.207,1,0.238,0.999,0.258,0.999,0.802,0.788,0.568,0.604,0.369,0.464,0.23,0.41,0.179
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Patio
          - Giardino_retro
      detections:
        required_zones:
          - Patio
          - Giardino_retro
  box:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/box
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/box_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
    snapshots:
      enabled: true
    motion:
      mask:
        1,0,0,0,0,0.27,0.208,0.152,0.213,0.18,0.282,0.152,0.493,0.179,0.486,0.113,0.691,0.132,0.693,0.203,0.856,0.235,0.91,0.291,1,0.333
    zones:
      Vialetto:
        coordinates:
          0.624,0.228,0.432,0.307,0.068,0.498,0.089,0.558,0.056,0.586,0.082,0.71,0.164,0.869,0.258,1,0.835,1,0.882,0.728,0.894,0.468,0.894,0.172,0.62,0.13
        loitering_time: 0
        inertia: 3
      Giardino_ingresso:
        coordinates:
          0.49,0.121,0.491,0.18,0.287,0.155,0.032,0.287,0.043,0.359,0.065,0.349,0.132,0.462,0.271,0.384,0.406,0.316,0.623,0.224,0.619,0.139
        loitering_time: 0
        inertia: 3
      Giardino_cisterna:
        coordinates: 0.911,0.174,0.896,0.134,0.896,0.557,0.879,0.778,0.838,1,1,1,1,0.329,0.908,0.294
        loitering_time: 0
        inertia: 3
      Box:
        coordinates:
          0.029,0.243,0.012,0,0,0,0,0.998,0.255,1,0.15,0.847,0.079,0.705,0.056,0.582,0.091,0.556,0.056,0.424
        loitering_time: 0
        inertia: 3
      marciapiede:
        coordinates: 0.068,0.348,0.132,0.463,0.074,0.488,0.054,0.403,0.049,0.357
        loitering_time: 0
    objects:
      mask:
        0,0,1,0,1,0.32,0.909,0.279,0.911,0.168,0.484,0.108,0.49,0.178,0.281,0.147,0,0.166
  giardino:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/giardino
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/giardino_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
    snapshots:
      enabled: true
    motion:
      mask:
        - 0,0.667,0.177,0.283,0.284,0.261,0.281,0.07,0.578,0.066,0.707,0.154,0.74,0.157,0.742,0.258,0.96,0.349,0.999,0.382,1,0,0.001,0,0.001,0
        - 0.534,0.215,0.553,0.212,0.551,0.238,0.529,0.24
    zones:
      Prato:
        coordinates:
          0.749,0.275,0.349,0.361,0.266,0.315,0.285,0.303,0.284,0.276,0.215,0.3,0.189,0.998,1,1,0.999,0.488,0.914,0.387,0.946,0.348
        loitering_time: 0
      Scarpata_siepe:
        coordinates: 0.284,0.275,0.283,0.255,0.182,0.27,0,0.672,0.002,0.997,0.184,0.997,0.215,0.295
        loitering_time: 0
      Marciapiede:
        coordinates:
          0.288,0.3,0.364,0.343,0.503,0.303,0.499,0.273,0.572,0.253,0.634,0.278,0.707,0.267,0.743,0.275,0.349,0.359,0.269,0.313
        loitering_time: 0
      Scarpata_prato:
        coordinates: 0.958,0.354,0.921,0.389,1,0.488,0.998,0.387
        loitering_time: 0
  cancello:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cancello
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 720
      height: 480
      fps: 7
    snapshots:
      enabled: true
    zones:
      Vialetto:
        coordinates: 0.644,0,0.669,0.099,0.643,0.118,0.67,0.224,0.386,1,0,1,0,0
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: Vialetto
      detections:
        required_zones: Vialetto
    motion:
      mask:
        0.352,1,0.569,0.379,0.602,0.352,0.648,0.242,0.624,0.132,0.669,0.096,0.656,0.042,0.617,0.055,0.603,0,1,0,1,1
  box_retro:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/box_retro
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/box_retro_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    audio:
      enabled: true # <- enable audio events for the front_camera
    detect:
      width: 1920
      height: 1080
      fps: 6
    snapshots:
      enabled: true
    motion:
      mask:
        - 0,0.658,0,0,0.426,0,0.203,0.131,0.105,0.208
        - 0.138,0.39,0.135,0.456,0.135,0.497,0.135,0.516,0.143,0.572,0.15,0.615,0.153,0.651,0.162,0.684,0.163,0.71,0.188,0.802,0.211,0.881,0.244,0.971,0.264,0.998,0.28,0.994,0.173,0.649,0.149,0.499,0.148,0.419,0.148,0.381
    zones:
      scale_box:
        coordinates: 0.892,0.362,0.698,1,1,1,1,0.417
        loitering_time: 0
        inertia: 3
      marciapiede_box:
        coordinates: 0.711,0.156,0.608,0.204,0.888,0.355,0.955,0.397,1,0,0.711,0
        loitering_time: 0
        inertia: 3
      prato:
        coordinates: 0.607,0.042,0.362,0.122,0.318,0.157,0.611,0.207,0.71,0.147,0.714,0
        loitering_time: 0
        inertia: 3
      terreno:
        coordinates: 0.709,0,0.429,0,0.207,0.13,0.107,0.214,0.034,0.502,0.338,0.132
        loitering_time: 0
        inertia: 3
      scarpata_box:
        coordinates:
          0.321,0.159,0.486,0.187,0.532,0.202,0.611,0.209,0.893,0.365,0.828,0.617,0.692,1,0,1,0,0.664,0.041,0.498
        loitering_time: 0
        inertia: 3
    objects:
      filters:
        person:
          mask:
            0.136,0.388,0.147,0.383,0.149,0.499,0.178,0.661,0.211,0.747,0.29,0.994,0.258,1,0.163,0.729,0.138,0.545,0.135,0.454
ffmpeg:
  hwaccel_args: preset-vaapi
    # hwaccel_args: preset-intel-qsv-h265

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  retain:
    default: 30
objects:
  track:
    - person
    - dog
    - car
    - bycicle
    - cat
      #- sports ball
    - cell phone
    - bird
      #- hat
      #- backpack
      #- handbag

audio: # <- disable audio events for all camera
  enabled: false
version: 0.16-0
camera_groups:
  Birdseye:
    order: 2
    icon: LuEye
    cameras: birdseye
detect:
  enabled: true
```

### Relevant Frigate log output

```shell
2025-05-13 10:02:46.671734930  [2025-05-13 10:02:46] frigate.record.maintainer      DEBUG   : Copied /media/frigate/recordings/2025-05-13/08/box_retro/02.23.mp4 in 0.06332206726074219 seconds.
2025-05-13 10:02:46.681381925  [2025-05-13 10:02:46] frigate.record.maintainer      DEBUG   : Copied /media/frigate/recordings/2025-05-13/08/cancello/02.34.mp4 in 0.035182952880859375 seconds.
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

YM500L-NM223N

### Screenshots of the Frigate UI's System metrics pages

N/A

**Comment by hawkeye217** [comment]
Which camera is not recording?

We will need to see logs from the actual problem in order to be able to help.

**Reply by mdacrema** [reply]
The cancello camera is the one that is not recording. Attached the logs for go2rtc and frigate.You can see I've stopped and started recording for the cancello camera near the end of the log.
[go2rtc-logs.txt](https://github.com/user-attachments/files/20187427/go2rtc-logs.txt)
[frigate-logs.txt](https://github.com/user-attachments/files/20187428/frigate-logs.txt)

**Reply by hawkeye217** [reply]
What is the video and audio codec being provided from the `cancello` camera?

**Reply by mdacrema** [reply]
`[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)","width":2592,"height":1944,"avg_frame_rate":"15/1"},{"codec_long_name":"AAC (Advanced Audio Coding)","avg_frame_rate":"0/0"}]}}]`

**Reply by hawkeye217** [reply]
So how do you know that recordings are not being saved? Your logs don't show anything unusual related to that camera.

**Reply by mdacrema** [reply]
From the logs attached above you should see something like `No recordings found for cancello during the requested time range`. If I check inside the recordings folder of frigate I've no files for the camera ( attached the directory tree ).
[frigate-recordings-tree.txt](https://github.com/user-attachments/files/20188247/frigate-recordings-tree.txt)

If I rollback with the same configuration to frigate 0.15.1 it starts recording again but I'll break while searching for recording due to database schema not being compatible anymore.

**Reply by NickM-27** [reply]
if you can get into the container and run `ls /tmp/cache` it would be good to see

**Reply by mdacrema** [reply]
```
root@d4029e486f43:/opt/frigate# ls -l /tmp/cache/
total 18840
-rw-r--r-- 1 root root 2713253 May 13 15:18 box@20250513151832+0200.mp4
-rw-r--r-- 1 root root 1048620 May 13 15:18 box@20250513151838+0200.mp4
-rw-r--r-- 1 root root 3794210 May 13 15:18 box_retro@20250513151826+0200.mp4
-rw-r--r-- 1 root root 1048620 May 13 15:18 box_retro@20250513151838+0200.mp4
srwxr-xr-x 1 root root       0 May 13 14:03 comms
srwxr-xr-x 1 root root       0 May 13 14:03 config
srwxr-xr-x 1 root root       0 May 13 14:03 embeddings
-rw-r--r-- 1 root root 1222155 May 13 15:18 giardino@20250513151828+0200.mp4
-rw-r--r-- 1 root root  524332 May 13 15:18 giardino@20250513151836+0200.mp4
-rw-r--r-- 1 root root 7866127 May 13 15:18 patio@20250513151829+0200.mp4
-rw-r--r-- 1 root root 1048624 May 13 15:18 patio@20250513151839+0200.mp4
drwxr-xr-x 2 root root    8520 May 13 15:18 preview_frames
srwxr-xr-x 1 root root       0 May 13 14:03 proxy_pub
srwxr-xr-x 1 root root       0 May 13 14:03 proxy_sub
```

**Reply by NickM-27** [reply]
and recordings are currently enabled for this camera right? I saw in the logs that MQTT was used to enable / disable. Can you confirm in the UI that recordings are enabled for cancello?

**Reply by hawkeye217** [reply]
You wouldn't happen to have a retained MQTT message for the `frigate/cancello/recordings/set` topic, would you?

**Reply by mdacrema** [reply]
I ran `mosquitto_sub -u user -P pass -t "#" -v --retained-only |grep frigate/cancello`  inside the mosquitto container and the only messages for the `frigate/cancello/*` I got are:

frigate/cancello/recordings/state ON
frigate/cancello/snapshots/state ON
frigate/cancello/audio/state ON
frigate/cancello/detect/state ON
frigate/cancello/motion/state ON
frigate/cancello/improve_contrast/state ON
frigate/cancello/ptz_autotracker/state OFF
frigate/cancello/motion_threshold/state 30
frigate/cancello/motion_contour_area/state 10
frigate/cancello/birdseye/state ON
frigate/cancello/birdseye_mode/state CONTINUOUS
frigate/cancello/person/snapshot ����
frigate/cancello/cell phone/snapshot ����
frigate/cancello/car/snapshot ����
frigate/cancello/sports ball/snapshot ����
frigate/cancello/cat/snapshot ����
frigate/cancello/dog/snapshot ����
frigate/cancello/enabled/state ON
frigate/cancello/review_alerts/state ON
frigate/cancello/review_detections/state ON

**Reply by mdacrema** [reply]
> and recordings are currently enabled for this camera right? I saw in the logs that MQTT was used to enable / disable. Can you confirm in the UI that recordings are enabled for cancello?

@NickM-27 yes, I confirm

**Reply by NickM-27** [reply]
Go ahead and run `ps -aux | grep cancello` in the container

**Reply by mdacrema** [reply]
root         577  2.4  0.9 3169928 236008 ?      Sl   14:03   2:44 frigate.process:cancello
root         635  1.1  0.9 3265352 230980 ?      Sl   14:03   1:17 frigate.capture:cancello
root         641  3.9  5.8 2563372 1436056 ?     Ssl  14:03   4:28 /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.16.0-5c3ac75 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/cancello -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/cancello@%Y%m%d%H%M%S%z.mp4 -r 7 -vf fps=7,scale_vaapi=w=720:h=480,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root         690  0.4  0.0 455184  7976 ?        Ssl  14:03   0:27 /usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-5c3ac75 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/cancello -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:
root       49991  0.0  0.0   3328  1136 pts/0    S+   15:55   0:00 grep cancello

**Reply by NickM-27** [reply]
You may try setting ffmpeg to "5.0"

**Reply by mdacrema** [reply]
Switched to 5.0 but same problem:

root@d4029e486f43:/opt/frigate# ps -aux | grep cancello
root         568  2.0  1.0 3169212 243872 ?      Sl   16:24   0:03 frigate.process:cancello
root         629  0.8  0.9 3265836 238324 ?      Sl   16:24   0:01 frigate.capture:cancello
root         635  3.9  0.3 577836 85596 ?        Ssl  16:24   0:05 /usr/lib/ffmpeg/5.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.16.0-5c3ac75 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/cancello -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/cancello@%Y%m%d%H%M%S%z.mp4 -r 7 -vf fps=7,scale_vaapi=w=720:h=480,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
root         710  0.2  0.0 129240 12380 ?        Ss   16:24   0:00 /usr/lib/ffmpeg/5.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-5c3ac75 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/cancello -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:
root        1986  0.0  0.0   3328  1240 pts/0    S+   16:26   0:00 grep cancello

root@d4029e486f43:/opt/frigate# ls /tmp/cache/
box@20250513162640+0200.mp4  box_retro@20250513162650+0200.mp4	comms  config  embeddings  giardino@20250513162646+0200.mp4  patio@20250513162650+0200.mp4  preview_frames  proxy_pub  proxy_sub

**Reply by NickM-27** [reply]
Something doesn't quite add up, because Frigate has logic to check if there is a file being written. ffmpeg itself also has not changed so it is odd that it would not be writing the segment, we would generally expect it to crash in that case.

**Reply by mdacrema** [reply]
Yes, it's very strange. The host filesystem is ZFS and I don't think the update from debian 11 to debian 12 should cause any issue. Tried also to compare processes between cameras that are recording and this one but they looks identical. I also tried rebooting the host to exclude some open file descriptors or stuff like that but the issue persists.

**Reply by NickM-27** [reply]
what is the docker compose?

**Reply by mdacrema** [reply]
```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta1
    shm_size: "256M" # update for your cameras based on calculation above
    devices:
      # - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/teo/frigate:/config
      - /home/teo/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8080:8080"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "#######"
      NEOReadDebugKeys: 1
      OverrideGpuAddressSpace: 48
```
