### DISCUSSION TITLE
[Camera Support]: No recording found for this time

### DISCUSSION THREAD

**Discussion by Roalkege** [blakeblackshear/frigate#18199] [Camera Support] [answered]
### Describe the problem you are having

Hey, I can live view my cams and also the alerts and detections are Woking. But after clicking on an alert I see `No recording found for this time` and after that only the first frame pixelated. The other cam works fine.

### Version

 0.15.0-6cb5cfb

### What browser(s) are you using?

Brave 1.78.97 and iOS 18.5

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a aac

audio:
  enabled: false
  listen:
    - bark
    - scream
    - yell
    - glass

detectors:
  ov:
    type: openvino
    device: AUTO
    model_path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  tapo_c51a:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.2.211:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true

    motion:
      mask: 0,0.001,0.363,0,0.362,0.048,0,0.05
    zones: {}
  tapo_c320ws:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.2.212:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true

    motion:
      mask:
        - 0,0,0.355,0.004,0.355,0.043,0,0.044
        - 0,0.046,0.064,0.048,0.049,0.371,0.144,0.66,0.228,0.742,0.251,0.79,0.168,0.83,0.094,0.682,0.024,0.741,0.012,0.39
snapshots:
  enabled: true
  bounding_box: true
  height: 1080
  quality: 98
  clean_copy: true
  retain:
    default: 120

live:
  height: 720
  quality: 10

detect:
  enabled: true
  fps: 10

telemetry:
  stats:
    network_bandwidth: true

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_area: 15000

record:
  sync_recordings: true
  enabled: true
  expire_interval: 60
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 180
  detections:
    retain:
      days: 90

semantic_search:
  enabled: true
  reindex: false
  model_size: small
notifications:
  enabled: true
  email: myemail@email.email
version: 0.15-1
camera_groups: {}
```

### Relevant Frigate log output

```shell
error   | 2025-05-13 17:02:35 | frigate.api.media  | No recordings found for tapo_c51a during the requested time range
error   | 2025-05-13 17:02:36 | frigate.api.media  | No recordings found for tapo_c51a during the requested time range
warning | 2025-05-13 17:03:08 | frigate.api.review | No motion data found for the requested time range
warning | 2025-05-13 17:03:09 | frigate.api.review | No motion data found for the requested time range
error   | 2025-05-13 17:03:09 | frigate.api.media  | No recordings found for tapo_c51a during the requested time range

NGINX LOG:

Log details

Type
error
Timestamp
2025-05-13 16:00:07
Tag
frigate.video
Message
tapo_c51a: Unable to read frames from ffmpeg process.
```

### Relevant go2rtc log output

```shell
info | 2025-05-10 10:44:43 | startup | Preparing new go2rtc config...
info | 2025-05-10 10:44:43 | startup | Starting go2rtc...
info | 2025-05-10 10:44:43 | startup | go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
info | 2025-05-10 10:44:43 | startup | config path=/dev/shm/go2rtc.yaml
info | 2025-05-10 10:44:43 | rtsp    | listen addr=:8554
info | 2025-05-10 10:44:43 | webrtc  | listen addr=:8555/tcp
info | 2025-05-10 10:44:43 | api     | listen addr=:1984
info | 2025-05-10 10:44:53 | startup | Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.6-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

### Frigate stats

```json
{"cameras":{"tapo_c51a":{"camera_fps":10.1,"process_fps":10.1,"skipped_fps":0.0,"detection_fps":3.5,"detection_enabled":true,"pid":435,"capture_pid":441,"ffmpeg_pid":333784,"audio_rms":0.0,"audio_dBFS":0.0},"tapo_c320ws":{"camera_fps":10.1,"process_fps":10.1,"skipped_fps":0.0,"detection_fps":4.5,"detection_enabled":true,"pid":437,"capture_pid":454,"ffmpeg_pid":232323,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"ov":{"inference_speed":3.13,"detection_start":0.0,"pid":397}},"detection_fps":8.0,"gpu_usages":{"amd-vaapi":{"gpu":"0.83%","mem":"79.60%"}},"cpu_usages":{"frigate.full_system":{"cpu":"12.7","mem":"67.0"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"86":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"106":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"4.0","cpu_average":"4","mem":"1.4","cmdline":"python3 -u -m frigate"},"129":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"172":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"173":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"174":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"184":{"cpu":"0.1","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"196":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"309":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"381":{"cpu":"0.1","cpu_average":"0","mem":"3.1","cmdline":"frigate.recording_manager"},"390":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.review_segment_manager"},"397":{"cpu":"16.6","cpu_average":"22","mem":"1.0","cmdline":"frigate.detector.ov  "},"399":{"cpu":"0.1","cpu_average":"0","mem":"2.2","cmdline":"frigate.embeddings_manager"},"421":{"cpu":"1.9","cpu_average":"1","mem":"0.6","cmdline":"frigate.output       "},"435":{"cpu":"9.4","cpu_average":"11","mem":"0.7","cmdline":"frigate.process:tapo_c51a"},"437":{"cpu":"7.2","cpu_average":"10","mem":"0.7","cmdline":"frigate.process:tapo_c320ws"},"441":{"cpu":"5.8","cpu_average":"5","mem":"0.6","cmdline":"frigate.capture:tapo_c51a"},"454":{"cpu":"5.7","cpu_average":"5","mem":"0.6","cmdline":"frigate.capture:tapo_c320ws"},"499":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 10 -bf 0 pipe:"},"506":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2304x1296 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 10 -bf 0 pipe:"},"513":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"232323":{"cpu":"12.4","cpu_average":"12","mem":"0.6","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.212:554/stream1 -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/tapo_c320ws@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale=2304:1296 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"333784":{"cpu":"7.3","cpu_average":"7","mem":"2.7","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@192.168.2.211:554/stream1 -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/tapo_c51a@%Y%m%d%H%M%S%z.mp4 -r 10 -vf fps=10,scale=2304:1296 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"338569":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sh"},"338618":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"},"338637":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"}},"service":{"uptime":282296,"version":"0.15.0-6cb5cfb","latest_version":"0.15.1","storage":{"/media/frigate/recordings":{"total":7627169.6,"used":1662498.2,"free":5964671.3,"mount_type":"fuse.shfs"},"/media/frigate/clips":{"total":7627169.6,"used":1662498.2,"free":5964671.3,"mount_type":"fuse.shfs"},"/tmp/cache":{"total":953.7,"used":22.4,"free":931.3,"mount_type":"tmpfs"},"/dev/shm":{"total":256.0,"used":191.2,"free":64.8,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1747148981},"processes":{"recording":{"pid":381},"review_segment":{"pid":390},"go2rtc":{"pid":98},"embeddings":{"pid":399}}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

tapo_c51a and tapo_c320ws

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/70c480ab-ee41-44b3-b0ad-ebabc51feb2d)
![image](https://github.com/user-attachments/assets/54194bbd-af52-4a4a-814f-f991ac8ea144)
![image](https://github.com/user-attachments/assets/9d080789-c55d-449d-8298-e1ac98c7a937)

### Any other information that may be helpful

AMD Ryzen 7 PRO 7840HS w/ Radeon 780M Graphics @ 3800 MHz
