### DISCUSSION TITLE
Masks and zones don't work

### DISCUSSION THREAD

**Discussion by ArieSneek** [blakeblackshear/frigate#18198] [General Support] [answered]
### Describe the problem you are having

Masks and zones don't work at all. 
I made a zone(last year), and thought that was enough. But it wasn't.  So I made objects masks, and even motion masks (even outside the zone) because a house that's not moving isn't a car. But it keeps saying that there's a car detected, no matter what zone or masks I make. This hasn't changed after 6 updates it's still the same. Deleting cameras, deleting zones and masks doesn't help. 
Also a garbage can is more human than humans (garbagecan is 83% human, and a human is about 75%. Masking garbage can also doesn't work). Cats are also human and the certainty is higher than real humans.

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

HAS app

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.108
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ******
  password: *******
  stats_interval: 60

cameras:
  garage_zosi: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.18:554/ucast/11 #Change as per your camera documentation for high quality feed
          roles:
            - record
        - path: rtsp://192.168.1.18:554/ucast/12/ #Change as per your camera documentation for low quality feed
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 480
      fps: 10 #This is the frame rate for detection, between 5-10 fps is sufficient.
    record:
      enabled: true
      retain:
        days: 0 #The number of days a recording will be kept for after a motion is detected.
        mode: all
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 1
    objects:
      track:
        - person
        - car
    motion:
      mask: 
        0.711,0.279,0.708,0.311,0.739,0.353,0.795,0.406,0.823,0.434,0.845,0.439,0.836,0.436,0.846,0.423,0.85,0.436,0.859,0.434,0.871,0.471,0.873,0.483,0.883,0.508,0.9,0.534,0.914,0.576,0.896,0.601,0.871,0.632,0.843,0.665,0.863,0.719,0.872,0.808,0.873,0.836,0.861,1,1,1,0.998,0.746,1,0.427,1,0.243,0.998,0.002,0.921,0.002,0.782,0.002,0.667,0.002,0.594,0.148,0.667,0.188,0.652,0.26,0.685,0.29,0.706,0.28
    zones:
      terrein:
        coordinates: 
          0.001,0,0.532,0,0.668,0,0.591,0.145,0.666,0.19,0.65,0.266,0.689,0.293,0.712,0.311,0.731,0.342,0.792,0.404,0.822,0.437,0.834,0.455,0.838,0.456,0.842,0.456,0.865,0.478,0.893,0.537,0.921,0.569,0.843,0.661,0.854,0.706,0.874,0.736,0.887,0.757,0.89,0.774,0.896,0.807,0.884,0.863,0.855,0.992,0.844,0.998,0.001,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: terrein

version: 0.15-1
```

### Relevant Frigate log output

```shell
There is no error when I get the message of a car(a brick house) being detected. Also no errors for garbage can.
```

### Relevant go2rtc log output

```shell
2025-05-11 19:21:16.443679192  [INFO] Preparing new go2rtc config...
2025-05-11 19:21:16.496383643  [INFO] Got IP address from supervisor: 192.168.1.108
2025-05-11 19:21:16.536800775  [INFO] Got WebRTC port from supervisor: 8556
2025-05-11 19:21:17.604517004  [INFO] Starting go2rtc...
2025-05-11 19:21:17.706598196  21:21:17.706 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2
2025-05-11 19:21:17.706626122  21:21:17.706 INF config path=/dev/shm/go2rtc.yaml
2025-05-11 19:21:17.708089106  21:21:17.707 INF [api] listen addr=:1984
2025-05-11 19:21:17.708093217  21:21:17.707 INF [rtsp] listen addr=:8554
2025-05-11 19:21:17.708097162  21:21:17.707 INF [webrtc] listen addr=:8555/tcp
2025-05-11 19:21:26.447993288  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
??
```

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
What's that?
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Zosi 1080P, but tried with other camera still same results. So not relevant to this problem
