### DISCUSSION TITLE
[Config Support]: High CPU on 9 cameras purely on live view - no detection or recording.

### DISCUSSION THREAD

**Discussion by yannnis** [blakeblackshear/frigate#18191] [Config Support] [answered]
### Describe the problem you are having

Hi everyone,

This is my first question here after installing frigate a week ago.

I have noticed that my cpu is ranging between 45-50% constantly but I m not doing any detection - just live view. By the way it's high even when i m not looking at the live view which is weird.

### Version

0.15.1

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    room0-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:room0-hifi#audio=aac" 
    room0-lofi:
      - rtsp://****@****/stream2
    room1-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:room1-hifi#audio=aac" 
    room1-lofi:
      - rtsp://****@****/stream2
    room2_camera-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:room2-hifi#audio=aac" 
    room2-lofi:
      - rtsp://****@****/stream2
    garage_camera-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:garage_camera-hifi#audio=aac" 
    garage_camera-lofi:
      - rtsp://****@****/stream2
    garden_camera-hifi:
      - rtsp://****@****/Streaming/Channels/101
      - "ffmpeg:garden_camera-hifi#audio=aac" 
    garden_camera-lofi:
      - rtsp://****@****/Streaming/Channels/102
    parking_camera-hifi:
      - rtsp://****@****/Streaming/Channels/101
      - "ffmpeg:parking_camera-hifi#audio=aac" 
    parking_camera-lofi:
      - rtsp://****@****/Streaming/Channels/102
    livingroom_camera-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:livingroom_camera-hifi#audio=aac" 
    livingroom_camera-lofi:
      - rtsp://****@****/stream2
    kitchen_camera-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:kitchen_camera-hifi#audio=aac" 
    kitchen_camera-lofi:
      - rtsp://****@****/stream2
    entrance_camera-hifi:
      - rtsp://****@****/stream1
      - "ffmpeg:entrance_camera-hifi#audio=aac" 
    entrance_camera-lofi:
      - rtsp://****@****/stream2

cameras:
  entrance_camera:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_camera-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrance_camera-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: entrance_camera-lofi

  kitchen_camera:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_camera-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_camera-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: kitchen_camera-lofi

  livingroom_camera:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/livingroom_camera-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/livingroom_camera-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: livingroom_camera-lofi

  parking_camera:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/parking_camera-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/parking_camera-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: parking_camera-lofi
  
  garden_camera:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_camera-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_camera-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: garden_camera-lofi

  room2:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/room2-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/room2-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: room2-lofi
      
  garage_camera:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_camera-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_camera-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: garage_camera-lofi
      
  room1:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/room1-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/room1-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: room1-lofi
      
  room0:    
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/room0-hifi
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/room0-lofi
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: room0-lofi

    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      #width: 1280
      #height: 720
version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

![4](https://github.com/user-attachments/assets/8d63556a-57a1-4e7c-a956-d07587c6d80b)
![5](https://github.com/user-attachments/assets/a338cffa-6fb5-4d62-81fa-037032e1ceed)
![6](https://github.com/user-attachments/assets/f9d1f5a5-ec7b-48fd-a4a0-e546b566afbd)

### Any other information that may be helpful

Hardware Info from Frigate
```

{"return_code":0,"stderr":"","stdout":"vainfo: VA-API version: 1.22 (libva 2.10.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Mobile - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD"}
```
