### DISCUSSION TITLE
[Support]: Logs not respecting timezone

### DISCUSSION THREAD

**Discussion by DPattee** [blakeblackshear/frigate#18209] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

The timestamps in the web log view's Frigate and go2rtc tabes aren't respecting the timezone setting for the container. 

The main 'Frigate' log page and the 'Go2rtc' page are putting time stamps that are 3 hours off. 

I'm in the pacific time zone and have the following in my docker compose: (the host machine and client machines are all set to the same time zone)

```

    environment:
      TZ: America/Los_Angeles

```

The logs are 3 hours behind - aka it is 4pm here now and it is showing 1pm , which would be Honolulu not sure where that's coming from. 

The logs on the Nginx tab *are* correct though.

Logging in to the container's terminal the 'date' command also shows the correct result aka 

```
root@5df9985c95c1:/opt/frigate# date
Tue May 13 16:46:01 PDT 2025
```

### Steps to reproduce

Go to frigateip:5563/logs and look at the time stamps

### Version

0.15.0-6cb5cfb

### In which browser(s) are you experiencing the issue with?

Chrome 136.0.7103.93 (Official Build) (arm64)

### Frigate config file

```yaml
n/a
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    #privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1gb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Corals
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/config
      - /volume1/docker/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5563:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    environment:
      TZ: America/Los_Angeles
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "foo"
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

n/a

### Screenshots of the Frigate UI's System metrics pages

<img width="575" alt="Screenshot 2025-05-13 at 4 50 03 PM" src="https://github.com/user-attachments/assets/5f71946d-5bab-4dbb-8c22-b3e8730c903f" />
<img width="575" alt="Screenshot 2025-05-13 at 4 49 58 PM" src="https://github.com/user-attachments/assets/1df28c43-2ab6-44b4-bf20-1625ab06a006" />
