### DISCUSSION TITLE
[Config Support]: Review Classification: Failed to save config changes: Error updating config

### DISCUSSION THREAD

**Discussion by s-t-dev** [blakeblackshear/frigate#18201] [Config Support] [answered]
### Describe the problem you are having

I can't save the Review Classification
<img width="735" alt="image" src="https://github.com/user-attachments/assets/f695fb96-05f7-444a-afa1-c7122d296614" />

Log file:
<img width="742" alt="image" src="https://github.com/user-attachments/assets/82d3a32b-9c39-4ea6-858b-f0de2389d9a0" />

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: [removed]
  password: [removed]

cameras:
  tuin:
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:[removed]@192.168.1.27:554/Preview_01_main
          roles:
            - record
        - path: rtsp://[removed]:[removed]@192.168.1.27:554/Preview_01_sub
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 4
    snapshots:
      enabled: true
      retain:
        default: 7

    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    motion: {}
    zones:
      tuin_zone:
        coordinates: 0.383,0.218,0.583,0.212,0.737,0.977,0.428,0.959
        
semantic_search:
  enabled: false
  reindex: false
  model_size: large
version: 0.15-1
```

### Relevant Frigate log output

```shell
Type
error
Timestamp
2025-05-13 19:20:27
Tag
root
Message
Error updating config: ''
```

### Relevant go2rtc log output

```shell
No errors
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
None
```

### Object Detector

CPU (no coral)
