### DISCUSSION TITLE
[Detector Support]: CPU detectors are not recommended - High CPU Usage - Nvidia 4060 on Unraid

### DISCUSSION THREAD

**Discussion by kooori** [blakeblackshear/frigate#18210] [Detector Support] [answered]
### Describe the problem you are having

I have sifted through the frigate documentation, and I've made several tweaks to my config to get it going. I could have possibly missed something but I am getting the CPU detectors are not recommended error and high cpu usage. I think I have everything set correctly to use my Nvidia 4060 (plex uses the same) with Frigate. 

- I've brought in detection on sub streams and recording on the main stream. 
- My streams are 265 codec but my system and all devices can view this no problem (as far as I can see)
- I've set up zones and motion masks on the timestamps and garden shrubs.
- disabled audio detection
- change shm size to  --shm-size=1g
- add this to parameters in unraid  --runtime=nvidia 

![image](https://github.com/user-attachments/assets/eb43d2a1-fc10-42d7-98f4-c27153d6432e)

Hardware is:
  Unraid OS v7
  AMD Ryzen 9 5900X / 64gb DDR4 Ram
  Running Frigate in docker from the app store.

I am trying to get the TensorRT engine working instead of my setup, but with the error I don't think TensorRT is running correctly and it instead is using my AMD Ryzen CPU?

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.23
  port: 1883
  user: XXXXXXXXXXXXXXX
  password: XXXXXXXXXXXXXXX
  topic_prefix: frigate
logger:
  logs:
    frigate.detectors: debug
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-nvidia
go2rtc:
  streams:
    garage:
      - rtsp://admin:XXXXXXXXXXXXXXX@192.168.2.91:554/media/video1
      - ffmpeg:garage#audio=aac
    garage_sub:
      - rtsp://admin:XXXXXXXXXXXXXXX@192.168.2.91:554/media/video2
      - ffmpeg:garage_sub#audio=aac
    walkway:
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.92:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:walkway#audio=aac
    walkway_sub:
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.92:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:walkway_sub#audio=aac
    backyard:
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.93:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:backyard#audio=aac
    backyard_sub:
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.93:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:backyard_sub#audio=aac
    sideofhouse:
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.94:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:sideofhouse#audio=aac
    sideofhouse_sub:
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.94:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:sideofhouse_sub#audio=aac
    doorbell:
      - ffmpeg:https://192.168.2.76/flv?port=554&amp;app=bcs&amp;stream=channel0_ext.bcs&amp;user=admin&amp;password=XXXXXXXXXXXXXXX!
      - rtsp://admin:XXXXXXXXXXXXXXX!@192.168.2.76:554/Preview_01_sub
      - ffmpeg:doorbell#audio=opus

objects:
  track:
    - person
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  sync_recordings: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 30
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  alerts:
    retain:
      days: 30
    pre_capture: 2
    post_capture: 2
  detections:
    retain:
      days: 30
    pre_capture: 2
    post_capture: 2

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 60
cameras:
  garage:
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 320
      height: 320
      fps: 5
    zones:
      Property:
        coordinates: 
          0,0.359,0,0.357,0,0.367,0.006,0.358,0.022,0.354,0.055,0.354,0.606,0.342,0.998,0.373,0.999,0.996,0.001,0.999
        loitering_time: 0
        inertia: 3
      Public:
        coordinates: 
          0.001,0.149,0,0.332,0,0.355,0.012,0.354,0.033,0.354,0.053,0.354,0.592,0.34,0.998,0.372,0.999,0.003,0,0
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: false
      mask:
        - 0.046,0.94,0.472,0.942,0.469,0.881,0.042,0.886
        - 0.302,0.335,0.299,0.195,0.579,0.182,0.579,0.493,0.319,0.482
        - 0.752,0.199,0.758,0.466,0.989,0.518,0.999,0.244
    review:
      alerts:
        required_zones: Property
      detections:
        required_zones: Public
  walkway:
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/walkway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/walkway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 320
      height: 320
      fps: 5
    zones:
      Property:
        coordinates: 
          0.004,0.475,0.009,0.624,0.01,0.636,0.15,0.597,0.145,0.462,0.193,0.452,0.756,0.364,0.997,0.502,0.999,0.995,0.003,0.995
        loitering_time: 0
      Public:
        coordinates: 
          0.995,0.389,0.998,0.002,0,0.001,0.016,0.627,0.15,0.6,0.144,0.46,0.197,0.456,0.184,0.355,0.736,0.247
        loitering_time: 0
        inertia: 3
    motion:
      mask:
        - 0.187,0.357,0.221,0.733,0.718,0.616,0.996,0.905,0.995,0.393,0.734,0.25
        - 0.794,0.988,1,1,1,0.942,0.796,0.946
      threshold: 30
      contour_area: 30
      improve_contrast: false
    review:
      alerts:
        required_zones: Property
      detections:
        required_zones: Public
  backyard:
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 320
      height: 320
      fps: 5
    zones:
      Property:
        coordinates: 0,0,0.577,0.032,0.582,0.083,0.756,0.127,0.97,0.398,0.998,0.999,0,0.997
        loitering_time: 0
    motion:
      mask:
        - 0.778,0.989,0.996,0.989,0.989,0.392,0.84,0.226,0.823,0.288,0.925,0.455,0.829,0.743
        - 0,0.048,0.298,0.048,0.29,0.001,0.006,0
    review:
      alerts:
        required_zones: Property
  sideofhouse:
    audio:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sideofhouse
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sideofhouse_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 320
      height: 320
      fps: 5
    zones:
      Property:
        coordinates: 
          0.756,0.26,0.61,0.277,0.419,0.027,0.109,0.027,0.375,0.992,0.998,0.999,0.864,0.507,0.737,0.339
        loitering_time: 0
      Inside_Property:
        coordinates: 0.002,0.057,0.101,0.021,0.368,0.988,0.001,0.995
        loitering_time: 0
      Public:
        coordinates: 
          0.654,0.272,0.756,0.263,0.737,0.342,0.85,0.492,0.968,0.188,0.899,0.068,0.693,0.068
        loitering_time: 0
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask:
        - 0.406,0.017,0.603,0.27,0.653,0.268,0.692,0.068,0.9,0.07,0.969,0.185,0.995,0.074,0.998,0.003,0.325,0.006
        - 0.796,0.949,0.999,0.95,0.992,0.997,0.8,0.987
    objects: {}
    review:
      alerts:
        required_zones:
          - Property
          - Inside_Property
      detections:
        required_zones: Public
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - audio
    zones:
      Property:
        coordinates: 
          0.206,0.553,0.264,0.548,0.261,0.457,0.403,0.447,0.405,0.482,0.419,0.48,0.419,0.529,0.478,0.534,0.476,0.481,0.49,0.482,0.493,0.446,0.695,0.439,0.698,0.472,0.729,0.474,0.72,0.432,0.792,0.407,0.961,0.414,0.966,0.504,0.998,0.502,0.998,0.997,0.004,0.999,0.001,0.005,0.22,0
        loitering_time: 0
      Public:
        coordinates: 
          0.21,0.4,0.307,0.397,0.362,0.309,0.735,0.313,0.995,0.315,0.976,0.498,0.963,0.402,0.791,0.405,0.721,0.431,0.71,0.434,0.7,0.436,0.694,0.44,0.493,0.443,0.487,0.478,0.476,0.483,0.478,0.533,0.424,0.534,0.42,0.48,0.404,0.482,0.402,0.449,0.263,0.455,0.265,0.547,0.206,0.549
        loitering_time: 0
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask:
        - 0.225,0.011,0.22,0.307,0.994,0.318,0.997,0
        - 0.21,0.402,0.307,0.398,0.364,0.307,0.219,0.243
        - 0.734,0.317,0.732,0.335,0.952,0.355,0.96,0.405,0.966,0.501,0.999,0.497,0.999,0.017
    review:
      alerts:
        required_zones: Property
      detections:
        required_zones: Public
version: 0.15-1
semantic_search:
  enabled: true
  reindex: true
  model_size: large
camera_groups:
  Front:
    order: 1
    icon: LuBringToFront
    cameras:
      - garage
      - walkway
```

### docker-compose file or Docker CLI command

```yaml
Unraid Docker from community app store:


docker run
  -d
  --name='frigate'
  --net='bridge'
  --pids-limit 2048
  -e TZ="Australia/Sydney"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="XXXXX"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='XXXXXXXX!'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-85f9ccd2-5500-04d8-5e0d-62fff1130174'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='compute,utility,video'
  -e 'USE_FP16'='true'
  -e 'TRT_MODEL_PREP_DEVICE'='0'
  -e 'PLUS_API_KEY'='XXXXXXXX'
  -e 'YOLO_MODELS'='yolov4-416,yolov4-tiny-416'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8971]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '8971:8971/tcp'
  -p '8554:8554/tcp'
  -p '1984:1984/tcp'
  -p '5000:5000/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -v '/mnt/user/appdata/frigate':'/config':'rw'
  -v '/mnt/disks/VGKW60VG/nvr':'/media/frigate':'rw,slave'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --shm-size=1g
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped
  --runtime=nvidia 'ghcr.io/blakeblackshear/frigate:stable-tensorrt'
efd0bf2500b3bd5e1f0fa5074d8c9d7275f98b0cffb1b66e30e8396ff319a7e9
```

### Relevant Frigate log output

```shell
info    | 2025-05-14 09:33:19 | startup                       | Preparing Frigate...
info    | 2025-05-14 09:33:19 | startup                       | Starting Frigate...
info    | 2025-05-14 09:33:25 | frigate.util.config           | Checking if frigate config needs migration...
info    | 2025-05-14 09:33:25 | frigate.util.config           | frigate config does not need migration...
info    | 2025-05-14 09:33:32 | frigate.app                   | Starting Frigate (0.15.0-6cb5cfb)
info    | 2025-05-14 09:33:33 | peewee_migrate.logs           | Starting migrations
info    | 2025-05-14 09:33:33 | peewee_migrate.logs           | There is nothing to migrate
info    | 2025-05-14 09:33:33 | frigate.app                   | Recording process started: 460
info    | 2025-05-14 09:33:33 | frigate.app                   | Review process started: 469
info    | 2025-05-14 09:33:33 | frigate.app                   | go2rtc process pid: 114
info    | 2025-05-14 09:33:33 | detector.cpu                  | Starting detection process: 476
warning | 2025-05-14 09:33:33 | frigate.detectors             | CPU detectors are not recommended and should only be used for testing or for trial purposes.
info    | 2025-05-14 09:33:33 | frigate.app                   | Embedding process started: 478
info    | 2025-05-14 09:33:33 | frigate.app                   | Output process started: 498
info    | 2025-05-14 09:33:33 | frigate.app                   | Camera processor started for garage: 514
info    | 2025-05-14 09:33:33 | frigate.app                   | Camera processor started for walkway: 528
info    | 2025-05-14 09:33:33 | frigate.app                   | Camera processor started for backyard: 537
info    | 2025-05-14 09:33:33 | frigate.app                   | Camera processor started for sideofhouse: 551
info    | 2025-05-14 09:33:33 | frigate.app                   | Camera processor started for doorbell: 560
info    | 2025-05-14 09:33:33 | frigate.app                   | Capture process started for garage: 575
info    | 2025-05-14 09:33:33 | frigate.app                   | Capture process started for walkway: 592
info    | 2025-05-14 09:33:33 | frigate.app                   | Capture process started for backyard: 605
info    | 2025-05-14 09:33:34 | frigate.app                   | Capture process started for sideofhouse: 613
info    | 2025-05-14 09:33:34 | frigate.app                   | Capture process started for doorbell: 625
info    | 2025-05-14 09:33:34 | frigate.api.fastapi_app       | Starting FastAPI app
info    | 2025-05-14 09:33:34 | frigate.api.fastapi_app       | FastAPI started
info    | 2025-05-14 09:33:37 | frigate.embeddings.embeddings | Indexing tracked object embeddings...
info    | 2025-05-14 09:33:59 | frigate.embeddings.embeddings | Embedded 2094 thumbnails and 0 descriptions in 21.4 seconds
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/6f9f43bd-f652-4365-a750-e7390f0cb541)

### Any other information that may be helpful

Nvidia SMI command:
![image](https://github.com/user-attachments/assets/9166d870-b787-432e-96bd-2e414d63b312)

When I add in the below code in my config.yaml. It causes frigate to not start with the error below.
`detectors:
  tensorrt:
    type: tensorrt
    device: 0`

![image](https://github.com/user-attachments/assets/530dc63c-70e1-4c2a-be30-886e9a9c377b)

CPU Screenshot from Unraid: 
![image](https://github.com/user-attachments/assets/781d1db9-e209-4e23-b5c6-bc426defcaf3)

**Comment by NickM-27** [comment]
We will need to see your config with tensorrt configured.

**Reply by kooori** [reply]
Are you referring to the docker command or the config.yaml?

EDIT: I am using the container image that has the tensorRT built in. Iam providing the grpahics card ID to the container so it should detect it automatically?

**Reply by NickM-27** [reply]
No, you have to define the detector, like it says in the docs https://docs.frigate.video/configuration/object_detectors#configuration-parameters

**Reply by kooori** [reply, marked as answer]
Thanks for the reply. I was able to get it going.

I have added the below in my config.yaml and added 'yolov7-320' to the YOLO_MODELS parameter when launching the container in unraid.

```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```



![image](https://github.com/user-attachments/assets/b41c38bb-a04d-41ed-8136-300f6b06c047)
