### DISCUSSION TITLE
[Bug]: Snapshot displayed in UI with the wrong timestamp

### DISCUSSION THREAD

**Discussion by pascalim** [blakeblackshear/frigate#18214] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

There is a snapshot (`front_yard-1747164862.521554-9lwxx5.jpg`) that has an incorrect `May 13 2025, 11:34 PM` timestamp in the UI.  The filename and timestamp from the filesystem appear correct (`May 14 2025, 06:53 AM`) and I'm sure the garbage truck did not drive by at night.

```
ls -lah
...
-rw-r--r-- 1 root root  5.5M May 13 22:27 front_yard-1747160843.57405-nimnoj-clean.png
-rw-r--r-- 1 root root  1.2M May 13 22:27 front_yard-1747160843.57405-nimnoj.jpg
-rw-r--r-- 1 root root  1.6M May 14 06:53 front_yard-1747164862.521554-9lwxx5-clean.png
-rw-r--r-- 1 root root  445K May 14 06:53 front_yard-1747164862.521554-9lwxx5.jpg   // Snapshot
-rw-r--r-- 1 root root  1.7M May 14 08:23 front_yard-1747164862.521554-q8tqle-clean.png
-rw-r--r-- 1 root root  442K May 14 08:23 front_yard-1747164862.521554-q8tqle.jpg
-rw-r--r-- 1 root root  1.7M May 14 06:29 front_yard-1747189744.547889-55nu70-clean.png
...
```
Incorrect timestamp in explore:
<img width="1518" alt="Screen Shot 2025-05-14 at 10 15 05 AM" src="https://github.com/user-attachments/assets/7e79f6d1-975a-46f4-b4a0-d7923055e5b1" />
Incorrect timestamp in HA's media browser:
<img width="998" alt="Screen Shot 2025-05-14 at 10 17 17 AM" src="https://github.com/user-attachments/assets/04d62051-3d34-4905-b599-3a3843449a9d" />

### Steps to reproduce

Unsure

### Version

0.16.0-5c3ac75

### In which browser(s) are you experiencing the issue with?

Firefox, Safari (Mac), Safari (iOS)

### Frigate config file

```yaml
version: 0.16-0

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-ubiquiti

detectors:
  ov:
    type: openvino
    device: GPU

model:
  path: plus://<redacted>

detect:
  enabled: true
  min_initialized: 2
  max_disappeared: 25
  fps: 5

objects:
  track:
    - person
    - face
    - car
    - motorcycle
    - bicycle
    - license_plate
    - dog
    - cat
    - bird
  filters:
    person:
      min_score: .65
      min_area: 2000
      threshold: .85
    car:
      min_score: .65
      threshold: .85
    license_plate:
      threshold: .7
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    bird:
      min_score: .7
      min_area: 2000

motion:
  threshold: 40
  contour_area: 25
  improve_contrast: false

record:
  enabled: true
  preview:
    quality: high
  alerts:
    post_capture: 3
    retain:
      days: 14
      mode: active_objects
  detections:
    post_capture: 3
    retain:
      days: 14
      mode: active_objects

snapshots:
  retain:
    default: 10
    objects:
      people: 15
  quality: 95

face_recognition:
  enabled: true
  model_size: large

lpr:
  enabled: true
  known_plates:
    pascal:
      - P1986
    sarah:
      - SL 28

classification:
  bird:
    enabled: false

cameras:
  front_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_sub
          roles:
            - detect
    live:
      streams:
        Main: front_yard
    detect:
      width: 1280
      height: 720  
    zones:
      front_yard_default:
        coordinates: 0,1,0,0.778,0.318,0.756,0.547,0.714,0.724,0.665,0.725,0.687,1,0.757,1,0.996
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - face
        filters:
          person:
            min_area: 10000
      front_yard_driveway:
        coordinates: 0.869,0.624,0.867,0.723,0.725,0.687,0.724,0.665
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - face
          - car
          - motorcycle
          - bicycle
          - license_plate
      front_yard_gate_watch:
        coordinates: 0.724,0.665,0.724,0.64,0.87,0.603,0.869,0.624
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - face
          - car
          - motorcycle
          - bicycle
          - license_plate
          - dog
          - cat
      front_yard_pet_watch:
        coordinates: 
          0,1,0,0.778,0.318,0.756,0.532,0.717,0.724,0.665,0.869,0.624,0.869,0.724,1,0.757,1,0.996
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - cat
          - bird
      front_yard_street_watch:
        coordinates: 
          0,0.747,0.155,0.742,0.335,0.726,0.546,0.688,0.724,0.64,0.87,0.601,0.869,0.518,0.717,0.545,0.308,0.593,0,0.613
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - face
          - car
          - motorcycle
          - bicycle
          - license_plate
      front_yard_sidewalk_watch:
        coordinates: 
          0.546,0.688,0.724,0.64,0.724,0.665,0.547,0.714,0.318,0.756,0,0.778,0,0.747,0.318,0.728
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - face
          - car
          - motorcycle
          - bicycle
          - license_plate
    objects:
      filters:
        car: {}
        bird:
          mask:
            - 0.347,0.711,0.387,0.703,0.388,0.76,0.355,0.767
            - 0.526,0.718,0.543,0.715,0.561,0.733,0.548,0.743
            - 0,0,0.837,0,0.864,0.31,0.693,0.336,0.693,0.293,0.242,0.317,0.136,0.368,0,0.361
            - 0.077,0.901,0.085,0.904,0.055,1,0.04,1
            - 0.497,0.806,0.518,0.802,0.52,0.858,0.499,0.863
            - 0,0,0.837,0,0.864,0.31,0.693,0.336,0.693,0.293,0.242,0.317,0.136,0.368,0,0.361
            - 0.077,0.901,0.085,0.904,0.055,1,0.04,1
            - 0.446,0.878,0.459,0.871,0.481,0.913,0.465,0.922
            - 0,0,0.837,0,0.864,0.31,0.693,0.336,0.693,0.293,0.242,0.317,0.136,0.368,0,0.361
            - 0.077,0.901,0.085,0.904,0.055,1,0.04,1
      mask:
        - 0,0,0.837,0,0.864,0.31,0.693,0.336,0.693,0.293,0.242,0.317,0.136,0.368,0,0.361
        - 0.077,0.901,0.085,0.904,0.055,1,0.04,1
    motion:
      mask:
        - 0,0,0.837,0,0.864,0.31,0.693,0.336,0.693,0.293,0.242,0.317,0.136,0.368,0,0.361
        - 0.866,0.376,0.864,0.31,0.839,0.314,0.837,0.401
        - 0.383,0.343,0.386,0.463,0.569,0.451,0.574,0.382,0.527,0.302,0.404,0.308
        - 0,0.361,0.075,0.365,0.096,0.423,0.133,0.445,0.133,0.487,0,0.49
    snapshots:
      enabled: true
      required_zones:
        - front_yard_default
        - front_yard_driveway
        - front_yard_gate_watch
        - front_yard_pet_watch
        - front_yard_sidewalk_watch
        - front_yard_street_watch
    review:
      alerts:
        required_zones:
          - front_yard_default
          - front_yard_driveway
      detections:
        required_zones:
          - front_yard_gate_watch
          - front_yard_pet_watch
          - front_yard_sidewalk_watch
    genai:
      enabled: true
      use_snapshots: true
      required_zones:
        - front_yard_gate_watch
        - front_yard_sidewalk_watch
    notifications:
      enabled: true
  pool:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_sub
          roles:
            - detect
    live:
      streams:
        Main: pool
        Sub: pool_sub
    detect:
      width: 640
      height: 360    
    zones:
      pool_default:
        coordinates: 
          0,0.73,0.126,0.662,0.355,0.691,0.645,0.691,0.762,0.675,0.827,0.785,0.911,0.79,0.883,1,0,1
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - face
      pool_sidewalk_watch:
        coordinates: 
          0.922,0.654,0.924,0.633,0.645,0.67,0.356,0.67,0.125,0.643,0,0.705,0,0.73,0.126,0.662,0.355,0.691,0.645,0.691
        loitering_time: 4
        inertia: 3
        objects:
          - person
          - face
      pool_track_watch:
        coordinates: 
          0,0.596,0.123,0.613,0.354,0.631,0.647,0.627,0.925,0.604,0.924,0.633,0.645,0.67,0.355,0.67,0.125,0.643,0,0.705
        loitering_time: 0
        objects:
          - person
        inertia: 3
      pool_pet_watch:
        coordinates: 
          0,0.73,0.126,0.662,0.355,0.691,0.645,0.691,0.762,0.675,0.827,0.785,0.911,0.79,0.885,1,0.002,1
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - cat
          - bird
    motion:
      mask:
        - 0,0,0.892,0,0.917,0.214,0.762,0.367,0.63,0.423,0.303,0.432,0.304,0.385,0,0.212
        - 0.487,0.427,0.487,0.51,0.632,0.506,0.632,0.422
        - 0.86,0.27,0.762,0.367,0.752,0.562,0.805,0.625,0.855,0.65,0.882,0.593,0.886,0.518,0.881,0.417
        - 0,0.324,0,0.212,0.246,0.352,0.287,0.463,0.283,0.565,0.189,0.566,0.095,0.461
        - 0.891,0,1,0,1,1,0.886,1,0.918,0.734,0.93,0.514,0.923,0.282
    snapshots:
      enabled: true
      required_zones:
        - pool_default
        - pool_pet_watch
        - pool_sidewalk_watch
        - pool_track_watch
    review:
      alerts:
        required_zones:
          - pool_default
      detections:
        required_zones:
          - pool_sidewalk_watch
          - pool_pet_watch
    genai:
      enabled: true
      use_snapshots: true
      required_zones:
        - pool_sidewalk_watch
        - pool_track_watch
    notifications:
      enabled: true
  porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porch_sub
          roles:
            - detect
    live:
      streams:
        Main: porch
        Sub: porch_sub
    detect:
      width: 640
      height: 360
    zones:
      porch_default:
        coordinates: 0.084,0.422,0.053,0,0.002,0.003,0,1,1,1,1,0.845,0.874,0.525
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - face
      porch_pool:
        coordinates: 0.084,0.422,0.071,0.247,0.461,0.249,0.342,0.456
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - face
      porch_yard:
        coordinates: 0.343,0.456,0.461,0.249,0.659,0.267,0.892,0.302,1,0.434,1,0.846,0.874,0.525
        loitering_time: 0
        inertia: 3
        objects:
          - person
          - face
      porch_sidewalk_watch:
        coordinates: 
          0.068,0.246,0.067,0.229,0.461,0.23,0.66,0.246,0.894,0.283,1,0.401,1,0.434,0.892,0.302,0.659,0.267,0.461,0.249
        loitering_time: 4
        objects:
          - person
          - face
        inertia: 3
      porch_track_watch:
        coordinates: 
          0.067,0.226,0.065,0.201,0.462,0.196,0.661,0.21,1,0.254,1,0.401,0.894,0.283,0.66,0.246,0.461,0.23
        inertia: 3
        loitering_time: 0
        objects:
          - person
      porch_pet_watch:
        coordinates: 
          0.659,0.267,0.446,0.249,0.068,0.247,0.053,0,0.002,0.003,0,1,1,1,1,0.434,0.892,0.302
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - cat
          - bird
    motion:
      mask: 
        0.676,0,0.654,0.084,0.61,0.15,0.588,0.21,0.544,0.262,0.477,0.252,0.452,0.204,0.387,0.197,0.388,0.119,0.427,0.059,0.385,0.089,0.363,0
    snapshots:
      enabled: true
      required_zones:
        - porch_default
        - porch_pool
        - porch_yard
        - porch_pet_watch
        - porch_sidewalk_watch
        - porch_track_watch
    review:
      alerts:
        required_zones:
          - porch_default
          - porch_pool
          - porch_yard
      detections:
        required_zones:
          - porch_sidewalk_watch
          - porch_pet_watch
    genai:
      enabled: true
      use_snapshots: true
      required_zones:
        - porch_sidewalk_watch
        - porch_track_watch

    notifications:
      enabled: true
go2rtc:
  webrtc:
    candidates:
      - <redacted>:8555
  streams:
    front_yard:
      - rtspx://<redacted>:7441/u2ZIkbbLdox2U49m
    front_yard_sub:
      - rtspx://<redacted>:7441/qxcGkOox6Pggbp6r
    pool:
      - rtspx://<redacted>:7441/VgtSd5oU7wyLS2ZT
    pool_sub:
      - rtspx://<redacted>:7441/xTWJdMYoYRXVK7gP
    porch:
      - rtspx://<redacted>:7441/pCZbKdOaUsk2Zg82
    porch_sub:
      - rtspx://<redacted>:7441/sbs8caCSC5yvNVfM

semantic_search:
  enabled: true
  reindex: false
  model_size: small

genai:
  enabled: false
  provider: openai
  api_key: '{FRIGATE_OPENAI_API_KEY}'
  model: gpt-4o
  prompt: >
    In a neutral, observational tone, factually document the most prominent subject's
    visible characteristics and behavior.
    Focus on directly observable traits such as size, shape, posture, and movement.
    The subject appears in surveillance footage from the {camera} area, which may
    have been recorded under low light or infrared conditions.
    Do not guess the subject's type or identity—describe only what can be plainly
    seen.
    Do not describe the surrounding environment unless it directly clarifies the subject's
    action or position.
    Avoid referring to the images or camera.
  object_prompts:
    person: >
      In a neutral, observational tone, factually document a {label}'s visible clothing,
      appearance, posture, and behavior.
      The {label} appears in surveillance footage from the {camera} area, which may
      have been recorded under low light or infrared conditions.
      Do not describe the surrounding environment unless it directly clarifies the
      {label}'s action or position.
      Avoid referring to the images or camera.

    car: >
      In a neutral, observational tone, factually document the visible features of
      a vehicle, including its type, color, orientation, and any distinguishing details
      such as wheels, lights, or windows.
      The vehicle appears in surveillance footage from the {camera} area, which may
      have been recorded under low light or infrared conditions.
      Do not describe the surrounding environment unless it directly clarifies the
      vehicle's state or action.
      Avoid referring to the images or camera.

    dog: >
      In a neutral, observational tone, factually document a {label}'s visible size,
      build, coat color and pattern, posture, and behavior.
      The {label} appears in surveillance footage from the {camera} area, which may
      have been recorded under low light or infrared conditions.
      Do not describe the surrounding environment unless it directly clarifies the
      {label}'s action or position.
      Avoid referring to the images or camera.

    cat: >
      In a neutral, observational tone, factually document a {label}'s visible size,
      fur type and pattern, posture, and behavior.
      The {label} appears in surveillance footage from the {camera} area, which may
      have been recorded under low light or infrared conditions.
      Do not describe the surrounding environment unless it directly clarifies the
      {label}'s action or position.
      Avoid referring to the images or camera.

    bird: >
      In a neutral, observational tone, factually document a {label}'s visible size,
      coloring, posture, and behavior.
      The {label} appears in surveillance footage from the {camera} area, which may
      have been recorded under low light or infrared conditions.
      Do not describe the surrounding environment unless it directly clarifies the
      {label}'s action or position.
      Avoid referring to the images or camera.

mqtt:
  enabled: true
  host: mqtt

tls:
  enabled: false

auth:
  enabled: false
  trusted_proxies:
    - proxy

proxy:
  header_map:
    user: Remote-User
    role: Remote-Groups
  logout_url: <redacted>

notifications:
  enabled: true
  email: <redacted>
camera_groups: {}

database:
  path: /config/data/frigate.db

logger:
  default: info
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta1
    container_name: nvr-frigate
    restart: unless-stopped    
    stop_grace_period: 30s
    shm_size: 256mb
    security_opt:
      - no-new-privileges:true
    privileged: true
    cap_add:
      - CAP_PERFMON
    labels:
      traefik.enable: true
      traefik.http.routers.frigate.rule: Host(`<redacted>`)
      traefik.http.routers.frigate.entrypoints: websecure
      traefik.http.routers.frigate.middlewares: chain-auth@file
      traefik.http.services.frigate.loadbalancer.server.port: 8971
    environment:
      FRIGATE_OPENAI_API_KEY: ${FRIGATE_OPENAI_API_KEY}
      PLUS_API_KEY: ${PLUS_API_KEY}
    networks:
      - default  
      - proxy
      - hass
    ports:
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate-conf:/config
      - frigate-storage:/media/frigate
      - frigate-data:/config/data
      - frigate-models:/config/model_cache
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000      
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: json-file
      options:
        max-size: '5m'
        max-file: '3'

volumes:
  frigate-conf:   
    name: frigate-conf
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /conf/frigate
  frigate-storage:
    name: frigate-storage
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/shared/cache/frigate/storage
  frigate-data:
    name: frigate-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/shared/cache/frigate/data
  frigate-models:
    name: frigate-models
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/shared/cache/frigate/models

networks:
  default:
    name: nvr
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-nvr
  proxy:
    external: true
  hass:
    external: true
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Home Assistant OS

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Unifi G5 Bullet, G3 Instant, G3 Flex

### Screenshots of the Frigate UI's System metrics pages

N/A
