### DISCUSSION TITLE
Frigate+ Model Not Detecting Objects – Need Help Verifying Setup

### DISCUSSION THREAD

**Discussion by rashane** [blakeblackshear/frigate#18212] [Ask A Question]
Hi,
I'm using the Frigate+ subscription, but I'm having an issue. Even after following your instructions, the system still doesn't detect anything as if it's not using the Frigate+ model. How can I verify if the model is working correctly? Please advise.

**Comment by hawkeye217** [comment]
We will need to see your full config in order to be able to help.

**Reply by rashane** [reply]
```
mqtt:
  host: 10.0.0.5
  port: 1883
#  topic_prefix: frigate
#  client_id: frigate
  user: xxxxx
  password: xxxxx
  stats_interval: 300

model:
  path: plus://4cc0654665cf9f6aae58662fd086ea90
  labelmap:
    0: person
    1: face
    2: car
    3: license_plate


snapshots:
  enabled: true
  retain:
    default: 14
record:
  expire_interval: 10
  enabled: true
  retain:
    days: 0
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7
detectors:
  coral1:
    type: edgetpu
    device: pci:0

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

#detectors:
#  coral_usb:
#    type: edgetpu
#    device: usb
#  coral_pci:
#    type: edgetpu
#    device: pci

logger:
  default: info

auth:
#  failed_login_rate_limit: "1/second;5/minute;20/hour"
  trusted_proxies:
    - 172.17.0.0/16

go2rtc:
  streams:
    lee_front_tree:
      - rtsp://admin:MUKVTK@10.0.0.19:554/h.264
    lee_front_main:
      - rtsp://admin:P@ssw0rd!234@10.0.0.35:554/media/video1
#    lee_hikpad:
#      - rtsp://admin:123456@10.0.0.242:554/Streaming/Channels/102
    lee_front_acti:
      - rtsp://admin:123456@10.0.0.24:7070/stream1
    lee_acti_2nd:
      - rtsp://admin:123456@10.0.0.186:7070/stream1
    lee_2nd_back_left:
      - rtsp://admin:123456@10.0.0.30:554/cam/realmonitor?channel=1&subtype=0
    lee_2nd_back_right:
      - rtsp://admin:123456@10.0.0.29:554/cam/realmonitor?channel=1&subtype=0
    lee_1st_back:
      - rtsp://admin:123456@10.0.0.32:554/cam/realmonitor?channel=1&subtype=0
    lee_2nd_side_right:
      - rtsp://admin:123456@10.0.0.25:7070
    lee_2nd_side_left:
      - rtsp://admin:123456@10.0.0.9:554/Streaming/Channels/101/
    lee_living:
      - rtsp://rtsp:12345678@10.0.0.12:554/av_stream/ch0
    lee_dining:
      - rtsp://rtsp:12345678@10.0.0.13:554/av_stream/ch0
    lee_bedroom:
      - rtsp://rtsp:12345678@10.0.0.14:554/av_stream/ch0
    lee_kitchen:
      - rtsp://10.0.0.91:554/ch0_0.h264
    lee_ceiling:
      - rtsp://10.0.0.92:554/ch0_0.h264


timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tl
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: '%m/%d/%Y %H:%M:%S'
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

cameras:
  ezviz01:
    genai:
      enable: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_front_tree
          roles:
            - detect
            - record            
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        rtmp: -c copy -f flv
      output_args:
        record: preset-record-generic-audio-aac

    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
        - motorcycle
        - car
        - license_plate
      filters:
        face:
          min_score: .7
        package:
          min_score: .65
          threshold: .9
        license_plate:
          min_score: .6
        person:
          min_score: .65
          threshold: .85
        car:
          min_score: .65
          threshold: .85
          mask: 0.343,0,0,0,0,0.576
        cat:
          min_score: .65
          threshold: .8
          mask: 0,0,0,1,0.397,1,0.512,0
        dog:
          min_score: .7
          threshold: .9
          mask: 0,0,0,1,0.397,1,0.512,0




  lee_hikpad:
    enabled: true
    genai:
      enable: true
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:123456@10.0.0.7:554/Streaming/Channels/102
#          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - record
#      output_args:
#        record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - face
      filters:
        face:
          min_score: .7
        package:
          min_score: .65
          threshold: .9
        person:
          min_score: .65
          threshold: .85

  lee_front_acti:
    enabled: true
    genai:
      enable: false
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_front_acti
#          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - record

  lee_acti_2nd:
    enabled: false
    genai:
      enable: false
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_acti_2nd
#          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - record

  front:
    genai:
      enable: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_front_main
          roles:
            - detect
            - record
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        rtmp: -c copy -f flv
      output_args:
        record: preset-record-generic-audio-aac

    objects:
      track:
        - person
        - face
        - cat
        - dog
        - bicycle
        - motorcycle
        - car
#      filters:
#        person:
#          min_score: 0.8  # 80% confidence required to trigger detection
#          threshold: 0.8 

  rear_left:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_2nd_back_left
          roles:
            - detect
            - record

    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat


  rear_right:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_2nd_back_right
          roles:
            - detect
            - record

    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat


  back:
    genai:
      enable: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_1st_back
#         - path: rtsp://admin:123456@10.0.0.191:554/cam/realmonitor?channel=1&subtype=0 
          roles:
            - detect
            - record

    detect:
      width: 1280
      height: 720
    objects:
      filters:
        person:
          mask:
            - 940,720,0,720,0,0,461,0,365,656,553,631,532,518,666,417


  side_front:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_2nd_side_left
          roles:
            - detect
            - record

    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - motorcycle
        - car
        - bird


  side_back:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_2nd_side_right
          roles:
            - detect
            - record

    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - bird


  lee_kitchen:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_kitchen
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720

  lee_ceiling:
    enabled: false
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_ceiling
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720

  sonoff_living:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_living
          roles:
            - detect
            - record
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        rtmp: -c copy -f flv
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
    objects:
      filters:
        person:
          mask: 0.238,0.004,0.289,0.262,0.139,0.719,0.591,0.989,0.006,0.992,0.005,0.002
          min_score: .65
          threshold: .85
        face:
          min_score: .7
          mask: 0.238,0.004,0.289,0.262,0.139,0.719,0.591,0.989,0.006,0.992,0.005,0.002

  sonoff_dining:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_dining
          roles:
            - detect
            - record
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        rtmp: -c copy -f flv
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
    objects:
      filters:
        person:
          mask: 
            0,1,1,1,1,0,0.263,0,0.255,0.089,0.529,0.108,0.579,0.309,0.507,0.487,0.399,0.519,0,0.574
  sonoff_bedroom:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_bedroom
#          roles:
#            - detect
#            - record
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        rtmp: -c copy -f flv
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person




version: 0.15-1
notifications:
  enabled: true
  email: [rashane@nvk.co.th](mailto:rashane@nvk.co.th)
semantic_search:
  enabled: true
  reindex: false
  model_size: small

camera_groups:
  outdoor:
    order: 1
    icon: LuAccessibility
    cameras:
      - ezviz01
      - lee_hikpad
      - lee_front_acti
      - front
      - rear_left
      - rear_right
      - side_front
      - back
      - side_back
  indoor:
    order: 2
    icon: LuActivity
    cameras:
      - sonoff_living
      - sonoff_dining
      - sonoff_bedroom
      - lee_ceiling
      - lee_kitchen


 above is our yaml configuration. let me know if you need more information.
```

**Reply by hawkeye217** [reply]
You should not be specifying a `labelmap`. Frigate will set this automatically for Frigate+ models. All you need is:
```
model:
  path: plus://4cc0654665cf9f6aae58662fd086ea90
```

**Reply by rashane** [reply]
I already try no labelmap. the same result.

**Reply by NickM-27** [reply]
We'll want to see a screenshot of your system metrics

**Reply by rashane** [reply]
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/e5a3fc41-5993-4a51-ba66-8e92086f4052" />

**Reply by hawkeye217** [reply]
Your inference speed is showing that detection is occurring.

Can you watch the debug view (Settings --> Debug) for detected objects?

**Reply by rashane** [reply]
yes detected only person. no face detected.

**Reply by hawkeye217** [reply]
You could try lowering your `min_score` for face:
```
      filters:
        face:
          min_score: .5
```

You should also define `face` in your list of objects to track.

**Reply by NickM-27** [reply]
Where are you looking for a face to be detected? How do you know it wasn't detected? 

Also worth mentioning some of your cameras don't have face detection enabled

**Reply by rashane** [reply]
still no face detected .

      filters:
        face:
          min_score: .5 
          
       
<img width="420" alt="image" src="https://github.com/user-attachments/assets/53d31bce-2afb-4874-b953-48b5f66a93f7" />

**Reply by hawkeye217** [reply]
Do you have `face` defined in your objects --> track for this camera?

```
objects:
  track:
    - person
    - face
    ...
```

**Reply by rashane** [reply]
```
  sonoff_living:
    genai:
      enable: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lee_living
          roles:
            - detect
            - record
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#        rtmp: -c copy -f flv
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1280
      height: 720
    objects:
      filters:
        person:
          mask: 0.238,0.004,0.289,0.262,0.139,0.719,0.591,0.989,0.006,0.992,0.005,0.002
          min_score: .65
          threshold: .85
        face:
          min_score: .5
          mask: 0.238,0.004,0.289,0.262,0.139,0.719,0.591,0.989,0.006,0.992,0.005,0.002
```
          
          
          please recheck my yaml config.?
