### DISCUSSION TITLE
[Support]: No Video in Recordings only Audio

### DISCUSSION THREAD

**Discussion by spikked27** [blakeblackshear/frigate#18221] [General Support] [answered]
### Describe the problem you are having

New issue that's come up, one of my cameras no longer records video, only audio.  Nothing's changed in my camera config and not sure if it's an issue with the 16 betas but the stream codecs are:
<img width="277" alt="image" src="https://github.com/user-attachments/assets/702968e7-3546-4e57-ad50-a422343bca0b" />

The physical recording files just entirely lack a video stream and only contain and audio stream:
<img width="251" alt="image" src="https://github.com/user-attachments/assets/de581459-200f-4737-8171-0b953a9c34b7" />

I've tried both
output_args:
        record: preset-record-generic-audio-copy

and 

output_args:
        record: preset-record-generic-audio-acc

### Version

16.0.0 Beta 2

### What browser(s) are you using?

Chrome Mobile/Desktop

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.0.107
  port: 1883
  user: 
  password: 
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

tls:
  enabled: false

semantic_search:
  enabled: true
  reindex: false
  model_size: large

#logger:
  #default: debug
  #logs:
  #  frigate.ffmpeg.front_door: error

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

ffmpeg:
  hwaccel_args: preset-nvidia

go2rtc:
  streams:
    front_door:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=#video=copy#audio=copy#audio=opus      - rtsp://xxx:xxx@192.168.0.112:554/h264Preview_01_sub
    front_door_sub:
      - ffmpeg:http://192.168.0.112/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=
    driveway:
      - ffmpeg:rtsp://xxx:xxx@192.168.0.113:554/11#video=copy#audio=aac#hardware
    driveway_sub:
      - rtsp://xxx:xxx@192.168.0.113:554/12
    driveway_snapshot:
      - http://xxx:xxx@192.168.0.113/tmpfs/auto.jpg
    # kitchen_display:
    #  - ffmpeg:rtsp://192.168.0.107:8554/kitchen_display#video=copy#audio=copy
    webrtc:
      candidates:
        - 192.168.0.101:8555
        - stun:8555

cameras:

#################################
#######    Front Door    ########
#################################
  front_door:
    ffmpeg:
 #     hwaccel_args: 
 #       - c:v hevc_cuvid
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    lpr:
      enabled: false
    detect:
      width: 672
      height: 896
      fps: 4
    live:
      streams:
        front_door: front_door
    motion:
      threshold: 30
      contour_area: 94
      improve_contrast: true
      mask: 
        1,0.474,1,0.391,1,0,0,0,0,0.314,0,0.545,0,0.644,0.133,0.652,0.395,0.647,0.593,0.632,0.786,0.605,0.843,0.598,0.887,0.595,0.914,0.595,0.932,0.597,0.969,0.602,1,0.607
    objects:
      filters:
        car:
          mask: 
            0.001,0.515,0.076,0.521,0.14,0.494,0.205,0.496,0.263,0.498,0.357,0.51,0.44,0.5,0.482,0.489,0.486,0.459,0.568,0.457,0.699,0.461,0.878,0.456,0.877,0.506,1,0.508,1,0.609,0.953,0.6,0.862,0.6,0.657,0.628,0.539,0.648,0.414,0.665,0.313,0.668,0.175,0.67,0.053,0.664,0,0.663
        person:
          mask: 
            0,0.526,0.077,0.531,0.117,0.493,0.197,0.498,0.191,0.543,0.42,0.534,0.484,0.528,0.482,0.489,0.486,0.456,0.694,0.463,0.785,0.46,0.878,0.458,0.839,0.523,0.97,0.531,0.967,0.602,0.811,0.6,0.697,0.615,0.535,0.631,0.41,0.645,0.312,0.65,0.175,0.653,0.048,0.64,0,0.663
    zones:
      Stoop:
        coordinates: 0.217,0.998,0.239,0.724,0.631,0.704,0.764,0.773,1,0.837,0.999,0.998
        loitering_time: 0
        inertia: 3
      Front_of_House:
        coordinates: 
          0.143,0.656,0.396,0.652,0.632,0.634,0.767,0.609,0.898,0.596,0.962,0.605,1,0.61,1,0.832,0.778,0.775,0.632,0.7,0.232,0.721,0.21,1,0,1,0,0.649
        loitering_time: 0

        inertia: 3
    review:
      alerts:
        required_zones: Stoop

##################################
#######    Driveway     ##########
##################################
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 352
      fps: 4
    live:
      streams:
        driveway: driveway
    review:
      alerts:
        required_zones:
          - Front_of_House
          - Driveway_Area
          - Driveway_Entry
      detections:
        labels:
          - person
          - bicycle
          - motorcycle
          - bird
          - cat
          - dog
          - suitcase
    lpr:
      enabled: true
      min_area: 1500 # Ignore plates with an area (length x width) smaller than 1500 pixels
      enhancement: 8

    zones:
      Front_of_House:
        coordinates: 0.443,0.45,0.675,0.427,0.752,0.417,0.751,0.483,0.744,0.553,0.554,0.513
        loitering_time: 0
        inertia: 3
      Driveway_Area:
        coordinates: 
          0.048,0.534,0.077,0.517,0.1,0.507,0.288,0.474,0.44,0.453,0.556,0.518,0.62,0.53,0.773,0.568,0.784,0.373,0.789,0.304,1,0.367,1,1,0,1,0,0.638
        inertia: 60
        loitering_time: 0
        objects:
          - bicycle
          - bird
          - cat
          - dog
          - motorcycle
          - person
          - suitcase
      Driveway_Entry:
        coordinates: 0.116,0.469,0.414,0.426,0.436,0.447,0.112,0.498
        loitering_time: 0
        inertia: 3
        objects: car
      Street:
        coordinates: 
          0,0.342,0.163,0.297,0.378,0.284,0.38,0.268,0.418,0.265,0.432,0.311,0.7,0.313,0.754,0.336,0.753,0.383,0.578,0.399,0.409,0.417,0.3,0.433,0.198,0.447,0.145,0.456,0.112,0.46,0.042,0.47,0,0.481
        loitering_time: 0
        inertia: 15
        objects:
          - bird
          - bicycle
          - cat
          - dog
          - motorcycle
          - person
          - suitcase
      Sidewalk:
        coordinates: 
          0.001,0.482,0.042,0.472,0.202,0.447,0.405,0.417,0.751,0.385,0.752,0.414,0.618,0.425,0.44,0.443,0.249,0.472,0.116,0.491,0,0.513
        loitering_time: 0
        objects:
          - bicycle
          - bird
          - cat
          - dog
          - person
          - suitcase
          - motorcycle
        inertia: 3
    motion:
      mask:
        - 0,0.337,0.001,0,1,0,1,0.361,0.775,0.292,0.77,0.374,0.662,0.329,0.577,0.31,0.432,0.311,0.419,0.265,0.377,0.268,0.378,0.282,0.297,0.286,0.163,0.294
        - 0,0.966,0.361,0.944,0.576,0.866,0.683,0.818,0.766,0.725,0.833,0.705,0.9,0.679,0.932,0.643,0.972,0.641,1,0.659,1,1,0,1
      threshold: 30
      contour_area: 10
      improve_contrast: true
    objects:
      filters:
        car:
          mask:
            - 0,0.301,0.131,0.265,0.162,0.234,0.289,0.226,0.486,0.224,0.505,0.225,0.505,0.157,0.671,0.155,0.766,0.156,0.759,0.41,0.674,0.417,0.526,0.431,0.435,0.443,0.409,0.42,0.375,0.372,0.123,0.405,0.114,0.476,0.087,0.493,0.055,0.506,0,0.613
            - 0,0.64,0.046,0.534,0.075,0.516,0.107,0.513,0.447,0.457,0.558,0.519,0.773,0.568,0.789,0.302,1,0.367,1,1,0,1
        person:
          mask: 0.662,0.307,0.778,0.385,0.786,0.158,0.51,0.155,0.506,0.312

##################################
#######  Kitchen Display   #######
##################################
  # kitchen_display:
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-aac
  #     inputs:
  #       - path: rtsp://192.168.0.107:8554/kitchen_display
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
  #   lpr:
  #     enabled: false
  #   #detect:
  #   #  width: 640
  #   #  height: 480
  #   motion:
  #     mask: 
  #       0,0.324,0.022,0.282,0.039,0.284,0.274,0.56,0.35,0.575,0.624,0.579,0.71,0.532,0.806,0.425,1,0.181,1,0,0,0
  #   objects:
  #     track:
  #       - person
  #       - cat


  #   zones:
  #     Kitchen:
  #       coordinates: 
  #         0,0.767,0,0.324,0.021,0.284,0.039,0.284,0.274,0.56,0.346,0.574,0.624,0.579,0.71,0.532,0.998,0.184,1,1,0,1
  #       loitering_time: 0
  #   review:
  #     alerts:
  #       required_zones: Kitchen

 # END CAMERA CONFIG       



##################################
#######  General Config    #######
##################################
record:
  enabled: true
  export:
    timelapse_args: -vf setpts=PTS/3600 -r 60
  retain:
    days: 60
    mode: all
  sync_recordings: true

  alerts:
    retain:
      days: 182
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 182
    pre_capture: 15
    post_capture: 15
snapshots:
  enabled: true
  retain:
    default: 365

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - suitcase

#audio:
#  enabled: true
#  listen:
#    - bark
#    - fire_alarm
#    - scream
#    - speech
#    - yell

version: 0.16-0
camera_groups: {}
notifications:
  enabled: true
  email: xxxxxxx
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
classification:
  bird:
    enabled: true
```

### Relevant Frigate log output

```shell
unknown | 2025-05-14 10:13:33 | unknown | OpenCV(4.11.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
unknown | 2025-05-14 10:13:46 | unknown | 25-05-14 10:13:33.140916854
unknown | 2025-05-14 10:13:46 | unknown | 25-05-14 10:13:33.140917368
unknown | 2025-05-14 10:13:43 | unknown | [ WARN:0@791.959] global cap.cpp:175 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
unknown | 2025-05-14 10:13:46 | unknown | 25-05-14 10:13:43.141534805
unknown | 2025-05-14 10:13:43 | unknown | OpenCV(4.11.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
unknown | 2025-05-14 10:13:46 | unknown | 25-05-14 10:13:43.141536222
unknown | 2025-05-14 10:13:46 | unknown | 25-05-14 10:13:43.141536737
unknown | 2025-05-14 10:13:53 | unknown | [ WARN:0@801.959] global cap.cpp:175 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
unknown | 2025-05-14 10:13:53 | unknown | 25-05-14 10:13:53.141480557
unknown | 2025-05-14 10:13:53 | unknown | OpenCV(4.11.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
unknown | 2025-05-14 10:13:53 | unknown | 25-05-14 10:13:53.141481936
unknown | 2025-05-14 10:13:53 | unknown | 25-05-14 10:13:53.141482439
```

### Relevant go2rtc log output

```shell
info | 2025-05-14 10:00:30 | startup | Preparing new go2rtc config...
info | 2025-05-14 10:00:30 | startup | Starting go2rtc...
info | 2025-05-14 10:00:30 | startup | go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
info | 2025-05-14 10:00:30 | startup | config path=/dev/shm/go2rtc.yaml
info | 2025-05-14 10:00:30 | api     | listen addr=:1984
info | 2025-05-14 10:00:30 | rtsp    | listen addr=:8554
info | 2025-05-14 10:00:30 | webrtc  | listen addr=:8555
info | 2025-05-14 10:00:40 | startup | Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe command not found
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
UnRaid App install
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

SV3C 5MP WiFi IP Camera Outdoor, Dual Band 2.4GHZ 5GHZ WiFi Security Camera

### Screenshots of the Frigate UI's System metrics pages

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/8d6d1ea7-11b8-4c40-b8f2-b0b5851ecc02" />
