### DISCUSSION TITLE
Understanding how to configure Detection settings for a 180degree Stream with a Coral TPU

### DISCUSSION THREAD

**Discussion by jeeftor** [blakeblackshear/frigate#18224] [Ask A Question] [answered]
As I understand CoralTPU is optimized for a small detection box.

I have an Apnviz 4K PoE Dual Lense 180 degree camera (HIKVISION oem)

- The raw Main stream is: `4096x1840`

- Sub Stream can either be set to: `1200x536` or `960x432`

As I understand CoralTPU works best with a `320x320` stream for the `TFLite` model it works with.

I'm trying to best understand how to handle detection in frigate as both of these streams are obviously to big.

### Confusion?

1) Do I use the `detect:` directive in my config to "modify" the stream?
2) Which sub stream config should I use if its just being downsampled?
3) If I'm downsampling in frigate why do I need the sub stream at all?
4) Does the full frame get processed or just the motion area get processed by the coralTPU?

Any guidance would be appreciated? 

I'm using go2rtc because I think this is the only way to get 2-way audio working. Although I'm not sure I need it for the sub stream.

```yaml
go2rtc:
    backyard_main: # https://github.com/AlexxIT/go2rtc#source-isapi
      - rtsp://Operator:Password@192.168.1.181:554/Streaming/channels/101?transport=tcp#backchannel=0
      - isapi://Operator:Password@192.168.1.181:80
    backyard_sub:
      - rtsp://Operator:Password@192.168.1.181:554/Streaming/channels/102?transport=udp
```

And the backyard config:

```yaml

  backyard:
    genai:
      enabled: false
    # onvif:
    #   host: 192.168.1.181
    #   port: 80
    #   user: Onvifuser
    #   password: Onvifpass

    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://localhost:8554/backyard_main 
          input_args: preset-rtsp-restream 
          roles:
            - audio
            - record
        - path: rtsp://localhost:8554/backyard_sub         
          input_args: preset-rtsp-restream 
          roles:
            - detect
    audio:
      enabled: true
    live:
      streams:
        backyard_main: backyard_main
    detect:
      width: 960
      height: 432
      fps: 5
```
