### DISCUSSION TITLE
[Detector Support]: TensorRT model problem

### DISCUSSION THREAD

**Discussion by sergiobaiao** [blakeblackshear/frigate#18238] [Detector Support]
### Describe the problem you are having

I'm trying to run Frigate with gpu detector using the tensorrt models and having some weird issues with it.

### Version

stable

### Frigate config file

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    privileged: true
    restart: unless-stopped
    shm_size: "1024mb"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
#              count: 1
              capabilities: [gpu]
    environment:
      FRIGATE_RTSP_PASSWORD: "senha123"
      YOLO_MODELS: yolov7x-640
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
      USE_FP16: "False"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /media/frigate:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
```

### docker-compose file or Docker CLI command

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    cam01_main:
      - rtsp://admin:Teste123@192.168.1.101:554/stream1
    cam01_sub:
      - rtsp://admin:Teste123@192.168.1.101:554/stream0
    cam02_main:
      - rtsp://admin:Teste123@192.168.1.10:554/stream1
    cam02_sub:
      - rtsp://admin:Teste123@192.168.1.10:554/stream0
    cam03_main:
      - rtsp://admin:Teste123!@192.168.1.147/media/video1
    cam03_sub:
      - rtsp://admin:Teste123!@192.168.1.147/media/video2

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
    model:
      path: "/config/model_cache/tensorrt/yolov7x-640.trt"
      labelmap_path: /labelmap/coco-80.txt
      input_tensor: nchw
      input_pixel_format: rgb
      width: 640
      height: 640

detect:
  width: 704
  height: 576
  fps: 5
  enabled: true

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 7

record:
  enabled: true
  retain:
    days: 7
    mode: motion

cameras:
  cam_01:
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/cam01_main
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/cam01_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams: # <--- Multiple streams for Frigate 0.16 and later
        Main Stream: cam01_main # <--- Specify a "friendly name" followed by the go2rtc stream name
        Sub Stream: cam01_sub
    detect:
      width: 720
      height: 480
      fps: 8

  cam_02:
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/cam02_main
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/cam02_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams: # <--- Multiple streams for Frigate 0.16 and later
        Main Stream: cam02_main # <--- Specify a "friendly name" followed by the go2rtc stream name
        Sub Stream: cam02_sub

  cam_03:
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/cam03_main
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/cam03_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams: # <--- Multiple streams for Frigate 0.16 and later
        Main Stream: cam03_main # <--- Specify a "friendly name" followed by the go2rtc stream name
        Sub Stream: cam03_sub

version: 0.16.0

ffmpeg:
  hwaccel_args: preset-nvidia

semantic_search:
  enabled: true
  model_size: large
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: false
classification:
  bird:
    enabled: false
```

### Relevant Frigate log output

```shell
docker compose up
[+] Running 1/1
 ✔ Container frigate  Recreated                                                                                         0.3s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service certsync-log: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service certsync-log successfully started
frigate  | s6-rc: info: service prepare successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2025-05-15 02:05:37.749443264  [INFO] Preparing new go2rtc config...
frigate  | 2025-05-15 02:05:38.073911214  [INFO] Starting go2rtc...
frigate  | 2025-05-15 02:05:38.140197856  02:05:38.140 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
frigate  | 2025-05-15 02:05:38.140200936  02:05:38.140 INF config path=/dev/shm/go2rtc.yaml
frigate  | 2025-05-15 02:05:38.140749520  02:05:38.140 INF [rtsp] listen addr=:8554
frigate  | 2025-05-15 02:05:38.140752443  02:05:38.140 INF [api] listen addr=:1984
frigate  | 2025-05-15 02:05:38.141075961  02:05:38.141 INF [webrtc] listen addr=:8555
frigate  | 2025-05-15 02:05:47.397968513  [INFO] Starting go2rtc healthcheck service...
frigate  |
frigate  | Generating the following TRT Models: yolov7x-640
frigate  | Downloading yolo weights
frigate  |
frigate  | Creating yolov7x-640.cfg and yolov7x-640.weights
frigate  |
frigate  | Done.
frigate  |
frigate  | Generating yolov7x-640.trt. This may take a few minutes.
frigate  |
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:149: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
frigate  |   builder.max_batch_size = MAX_BATCH_SIZE
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:151: DeprecationWarning: Use set_memory_pool_limit instead.
frigate  |   config.max_workspace_size = 1 << 30
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:174: DeprecationWarning: Use build_serialized_network instead.
frigate  |   engine = builder.build_engine(network, config)
frigate  | Generated yolov7x-640.trt in 148 seconds
frigate  | Available tensorrt models:
frigate  | yolov7x-640.trt
frigate  | s6-rc: info: service trt-model-prepare successfully started
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2025-05-15 02:10:20.441355207  [INFO] Starting NGINX...
frigate  | 2025-05-15 02:10:20.465196574  [INFO] No TLS certificate found. Generating a self signed certificate...
frigate  | 2025-05-15 02:10:20.490200537  You have successfully opted out to send the telemetry data.
frigate  | 2025-05-15 02:10:20.879122558  [INFO] Preparing Frigate...
frigate  | 2025-05-15 02:10:21.266382306  [INFO] Starting Frigate...
frigate  | 2025-05-15 02:10:23.653588195  [2025-05-15 02:10:23] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigate  | 2025-05-15 02:10:23.669785152  [2025-05-15 02:10:23] frigate.util.config            INFO    : copying config as backup...
frigate  | 2025-05-15 02:10:23.684884265  [2025-05-15 02:10:23] frigate.util.config            INFO    : Finished frigate config migration...
frigate  | 2025-05-15 02:10:23.691977011  [2025-05-15 02:10:23] frigate.app                    INFO    : Starting Frigate (0.16.0-1fa7ce5)
frigate  | 2025-05-15 02:10:23.692168264  [2025-05-15 02:10:23] frigate.app                    INFO    : Creating directory: /tmp/cache
frigate  | 2025-05-15 02:10:23.701301592  [2025-05-15 02:10:23] peewee_migrate.logs            INFO    : Starting migrations
frigate  | 2025-05-15 02:10:23.702048566  [2025-05-15 02:10:23] peewee_migrate.logs            INFO    : There is nothing to migrate
frigate  | 2025-05-15 02:10:23.711935311  [2025-05-15 02:10:23] frigate.app                    INFO    : Recording process started: 670
frigate  | 2025-05-15 02:10:23.720204105  [2025-05-15 02:10:23] frigate.app                    INFO    : Review process started: 681
frigate  | 2025-05-15 02:10:23.722809107  [2025-05-15 02:10:23] frigate.app                    INFO    : go2rtc process pid: 138
frigate  | 2025-05-15 02:10:23.741584716  [2025-05-15 02:10:23] frigate.app                    INFO    : Embedding process started: 695
frigate  | 2025-05-15 02:10:23.757679900  [2025-05-15 02:10:23] frigate.app                    INFO    : Output process started: 714
frigate  | 2025-05-15 02:10:23.788150633  [2025-05-15 02:10:23] frigate.app                    INFO    : Camera processor started for cam_01: 761
frigate  | 2025-05-15 02:10:23.798251726  [2025-05-15 02:10:23] frigate.app                    INFO    : Camera processor started for cam_02: 767
frigate  | 2025-05-15 02:10:23.798603278  [2025-05-15 02:10:23] frigate.app                    INFO    : Camera processor started for cam_03: 777
frigate  | 2025-05-15 02:10:23.798643893  [2025-05-15 02:10:23] detector.tensorrt              INFO    : Starting detection process: 692
frigate  | 2025-05-15 02:10:23.816580185  [2025-05-15 02:10:23] frigate.app                    INFO    : Capture process started for cam_01: 793
frigate  | 2025-05-15 02:10:23.827077872  [2025-05-15 02:10:23] frigate.app                    INFO    : Capture process started for cam_02: 804
frigate  | 2025-05-15 02:10:23.840524949  [2025-05-15 02:10:23] frigate.app                    INFO    : Capture process started for cam_03: 815
frigate  | 2025-05-15 02:10:23.941722181  Process detector:tensorrt:
frigate  | 2025-05-15 02:10:23.941725082  Traceback (most recent call last):
frigate  | 2025-05-15 02:10:23.941726251    File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
frigate  | 2025-05-15 02:10:23.941729278      self.run()
frigate  | 2025-05-15 02:10:23.941730777    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2025-05-15 02:10:23.941731575      return run(*args, **kwargs)
frigate  | 2025-05-15 02:10:23.941754027             ^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941754903    File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
frigate  | 2025-05-15 02:10:23.941756081      self._target(*self._args, **self._kwargs)
frigate  | 2025-05-15 02:10:23.941763927    File "/opt/frigate/frigate/object_detection/base.py", line 112, in run_detector
frigate  | 2025-05-15 02:10:23.941764868      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate  | 2025-05-15 02:10:23.941765666                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941798371    File "/opt/frigate/frigate/object_detection/base.py", line 57, in __init__
frigate  | 2025-05-15 02:10:23.941799452      self.detect_api = create_detector(detector_config)
frigate  | 2025-05-15 02:10:23.941812008                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941813050    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
frigate  | 2025-05-15 02:10:23.941813863      return api(detector_config)
frigate  | 2025-05-15 02:10:23.941814602             ^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941815511    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 243, in __init__
frigate  | 2025-05-15 02:10:23.941816333      self.engine = self._load_engine(detector_config.model.path)
frigate  | 2025-05-15 02:10:23.941817100                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941817994    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 87, in _load_engine
frigate  | 2025-05-15 02:10:23.941829401      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
frigate  | 2025-05-15 02:10:23.941830292           ^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941831149  TypeError: expected str, bytes or os.PathLike object, not NoneType
frigate  | 2025-05-15 02:10:23.941832158  Exception ignored in: <function TensorRtDetector.__del__ at 0x766ff0fae520>
frigate  | 2025-05-15 02:10:23.941832958  Traceback (most recent call last):
frigate  | 2025-05-15 02:10:23.941833974    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 262, in __del__
frigate  | 2025-05-15 02:10:23.941834685      if self.outputs is not None:
frigate  | 2025-05-15 02:10:23.941849814         ^^^^^^^^^^^^
frigate  | 2025-05-15 02:10:23.941850807  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate  | 2025-05-15 02:10:24.264229926  [2025-05-15 02:10:24] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigate  | 2025-05-15 02:10:24.386644272  [2025-05-15 02:10:24] frigate.api.fastapi_app        INFO    : FastAPI started
frigate  | 2025-05-15 02:10:25.279823696  loading data from : /config/model_cache/facedet/landmarkdet.yaml
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service certsync: starting
frigate  | 2025-05-15 02:10:26.375597304  [INFO] Starting certsync...
frigate  | s6-rc: info: service certsync successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2025-05-15 02:10:26.873301955  127.0.0.1 - - [15/May/2025:02:10:26 +0000] "" 400 0 "-" "-" "-"
frigate  | 2025-05-15 02:10:44.252003908  [2025-05-15 02:10:44] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | s6-rc: info: service certsync: stopping
frigate  | 2025-05-15 02:10:44.271611453  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2025-05-15 02:10:44.293230931  [INFO] Service CERTSYNC exited with code 256 (by signal 15)
frigate  | s6-rc: info: service certsync successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service certsync-log: stopping
frigate  | s6-rc: info: service certsync-log successfully stopped
frigate  | 2025-05-15 02:10:44.339202335  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2025-05-15 02:10:44.457098536  [2025-05-15 02:10:44] frigate.app                    INFO    : Stopping...
frigate  | 2025-05-15 02:10:44.459315512  [2025-05-15 02:10:44] frigate.storage                INFO    : Exiting storage maintainer...
frigate  | 2025-05-15 02:10:44.459629535  [2025-05-15 02:10:44] frigate.events.cleanup         INFO    : Exiting event cleanup...
frigate  | 2025-05-15 02:10:44.462023849  [2025-05-15 02:10:44] frigate.ptz.autotrack          INFO    : Exiting autotracker...
frigate  | 2025-05-15 02:10:44.462197717  [2025-05-15 02:10:44] frigate.stats.emitter          INFO    : Exiting stats emitter...
frigate  | 2025-05-15 02:10:44.462218843  [2025-05-15 02:10:44] frigate.watchdog               INFO    : Exiting watchdog...
frigate  | 2025-05-15 02:10:44.463407100  [2025-05-15 02:10:44] frigate.ptz.onvif              INFO    : Exiting ONVIF controller...
frigate  | 2025-05-15 02:10:44.463559735  [2025-05-15 02:10:44] frigate.record.cleanup         INFO    : Exiting recording cleanup...
frigate  | 2025-05-15 02:10:44.463565076  [2025-05-15 02:10:44] frigate.app                    INFO    : Waiting for capture process for cam_01 to stop
frigate  | 2025-05-15 02:10:44.558862784  [2025-05-15 02:10:44] watchdog.cam_01                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-05-15 02:10:44.559237106  [2025-05-15 02:10:44] watchdog.cam_01                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-05-15 02:10:44.797979454  [2025-05-15 02:10:44] frigate.track.object_processing INFO    : Exiting object processor...
frigate  | 2025-05-15 02:10:45.109093992  [2025-05-15 02:10:45] watchdog.cam_01                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-05-15 02:10:45.109096979  [2025-05-15 02:10:45] watchdog.cam_01                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-05-15 02:10:45.273340171  [2025-05-15 02:10:45] frigate.events.maintainer      INFO    : Exiting event processor...
frigate  | 2025-05-15 02:10:45.687864489  [2025-05-15 02:10:45] frigate.app                    INFO    : Waiting for capture process for cam_02 to stop
frigate  | 2025-05-15 02:10:45.763201545  [2025-05-15 02:10:45] watchdog.cam_02                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-05-15 02:10:45.763446267  [2025-05-15 02:10:45] watchdog.cam_02                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-05-15 02:10:46.542345902  [2025-05-15 02:10:46] watchdog.cam_02                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-05-15 02:10:46.542349500  [2025-05-15 02:10:46] watchdog.cam_02                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-05-15 02:10:46.874228776  [2025-05-15 02:10:46] frigate.app                    INFO    : Waiting for capture process for cam_03 to stop
frigate  | 2025-05-15 02:10:47.058978443  [2025-05-15 02:10:47] watchdog.cam_03                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-05-15 02:10:47.059014487  [2025-05-15 02:10:47] watchdog.cam_03                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-05-15 02:10:47.850491679  [2025-05-15 02:10:47] watchdog.cam_03                INFO    : Terminating the existing ffmpeg process...
frigate  | 2025-05-15 02:10:47.850494788  [2025-05-15 02:10:47] watchdog.cam_03                INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | 2025-05-15 02:10:48.130916109  [2025-05-15 02:10:48] frigate.app                    INFO    : Waiting for process for cam_01 to stop
frigate  | 2025-05-15 02:10:49.422735659  [2025-05-15 02:10:49] frigate.video                  INFO    : cam_01: emptying frame queue
frigate  | 2025-05-15 02:10:49.423566286  [2025-05-15 02:10:49] frigate.video                  INFO    : cam_01: exiting subprocess
frigate  | 2025-05-15 02:10:49.441453868  [2025-05-15 02:10:49] frigate.app                    INFO    : Closing frame queue for cam_01
frigate  | 2025-05-15 02:10:49.942982672  [2025-05-15 02:10:49] frigate.app                    INFO    : Waiting for process for cam_02 to stop
frigate  | 2025-05-15 02:10:50.399166713  [2025-05-15 02:10:50] frigate.video                  INFO    : cam_02: emptying frame queue
frigate  | 2025-05-15 02:10:50.399843493  [2025-05-15 02:10:50] frigate.video                  INFO    : cam_02: exiting subprocess
frigate  | 2025-05-15 02:10:50.417158077  [2025-05-15 02:10:50] frigate.app                    INFO    : Closing frame queue for cam_02
frigate  | 2025-05-15 02:10:50.918651146  [2025-05-15 02:10:50] frigate.app                    INFO    : Waiting for process for cam_03 to stop
frigate  | 2025-05-15 02:10:51.262926788  [2025-05-15 02:10:51] frigate.video                  INFO    : cam_03: emptying frame queue
frigate  | 2025-05-15 02:10:51.263681347  [2025-05-15 02:10:51] frigate.video                  INFO    : cam_03: exiting subprocess
frigate  | 2025-05-15 02:10:51.281071395  [2025-05-15 02:10:51] frigate.app                    INFO    : Closing frame queue for cam_03
frigate  | 2025-05-15 02:10:52.284184952  [2025-05-15 02:10:52] frigate.app                    INFO    : Detection queue closed
frigate  | 2025-05-15 02:10:52.786194506  [2025-05-15 02:10:52] frigate.app                    INFO    : Detected frames queue closed
frigate  | 2025-05-15 02:10:53.287277359  [2025-05-15 02:10:53] frigate.app                    INFO    : Timeline queue closed
frigate  | 2025-05-15 02:10:54.312087645  [2025-05-15 02:10:54] frigate.output.output          INFO    : exiting output process...
frigate  | 2025-05-15 02:10:58.724061768  [2025-05-15 02:10:58] frigate.record.maintainer      INFO    : Exiting recording maintenance...
frigate  | 2025-05-15 02:10:59.771225754  [INFO] Service Frigate exited with code 0 (by signal 0)
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service trt-model-prepare: stopping
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | 2025-05-15 02:10:59.774942540  exit with signal: terminated
frigate  | s6-rc: info: service trt-model-prepare successfully stopped
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2025-05-15 02:10:59.782259078  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service prepare: stopping
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service prepare successfully stopped
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container frigate  Stopped
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

Frigate doesn't start

### Any other information that may be helpful

docker exec -it frigate nvidia-smi
Thu May 15 02:16:35 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.07             Driver Version: 570.133.07     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050        Off |   00000000:02:00.0  On |                  N/A |
| 33%   39C    P2             21W /   70W |    1151MiB /   6144MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A             453      C   frigate.embeddings_manager              748MiB |
|    0   N/A  N/A             594      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          158MiB |
|    0   N/A  N/A             605      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          102MiB |
|    0   N/A  N/A             625      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          104MiB |
+-----------------------------------------------------------------------------------------+

lshw -C display
  *-display
       description: VGA compatible controller
       product: GA107 [GeForce RTX 3050 6GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:02:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=nvidia latency=0 resolution=1600,900
       resources: iomemory:400-3ff iomemory:420-41f irq:143 memory:80000000-80ffffff memory:4000000000-41ffffffff memory:4200000000-4201ffffff ioport:3000(size=128) memory:81000000-8107ffff
