### DISCUSSION TITLE
[Support]: Review API duration (48.396 s) does not match clip.mp4 length (30.9 s)

### DISCUSSION THREAD

**Discussion by pk802** [blakeblackshear/frigate#18246] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

When I call the review API /review/1747316009.687994-wnpvbb, I get:

`{
    "id": "1747316009.687994-wnpvbb",
    "camera": "outside_camera",
    "start_time": 1747316009.687994,
    "end_time": 1747316058.084018,
    "severity": "alert",
    "thumb_path": "/media/frigate/clips/review/thumb-outside_camera-1747316009.687994-wnpvbb.webp",
    "data": {
        "detections": [
            "1747316008.077495-0yztpd",
            "1747316054.24269-drabzk",
            "1747316028.877367-xxt7fj"
        ],
        "objects": [
            "person"
        ],
        "sub_labels": [],
        "zones": [],
        "audio": []
    }
}`

By subtraction, the review duration is 48.396 s.
However, when I fetch the clip via

/outside_camera/start/1747316009/end/1747316058/clip.mp4

the video file is only ~30.9 s long.

### Steps to reproduce

This happens when there is multiple events in review and each event's end and start are not overlapping. 

### Version

0.16.0 Beta 2

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: pass
  enabled: true

tls:
  enabled: false

go2rtc:
  streams:
    outside_camera:
      - rtsp://<REDACTED>@<HOST>:<PORT>/cam/realmonitor?channel=3&subtype=0
  webrtc:
    candidates:
      - stun:8555

cameras:
  outside_camera:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:8554/outside_camera
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      streams:
        outside_camera: outside_camera
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask:
        - 0.733,0.03,0.735,0.085,0.997,0.093,0.998,0.032
        - 0.262,0,0.341,0.641,0.079,1,0,1,0,0

objects:
  track:
    - person
  filters:
    person:
      min_area: 0
      max_area: 1000000
      min_score: 0.6
      threshold: 0.8

snapshots:
  enabled: true
  timestamp: false
  clean_copy: true
  bounding_box: false
  crop: false
  retain:
    default: 1

review:
  alerts:
    labels:
      - person

record:
  enabled: true
  retain:
    days: 0.5
    mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 0.5
      mode: active_objects
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 0.5
      mode: active_objects

birdseye:
  enabled: true
  mode: continuous

motion:
  threshold: 50
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50

detectors:
  coral:
    type: edgetpu
    device: usb

semantic_search:
  enabled: true
  model_size: small
  reindex: false

version: 0.16-0

detect:
  enabled: true
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Network connection

Wired

### Camera make and model

Dahua

### Screenshots of the Frigate UI's System metrics pages

NA

### Any other information that may be helpful

Also it seems the pre_capture and post_capture is not working and due to that recording stops as soon as event ends.
