### DISCUSSION TITLE
[Config Support]:

### DISCUSSION THREAD

**Discussion by DarvinIT** [blakeblackshear/frigate#18241] [Config Support]
### Describe the problem you are having

Please correct my configuration. Storing only movement for 2 days, 5 seconds before movement and 5 seconds after movement.

### Version

0.15-1

### Frigate config file

```yaml
mqtt:
  enabled: false

record:
  enabled: true
  pre_capture: 5
  post_capture: 5
  events:
    retain:
      default: 2

cameras:
  Piwnica_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.3.197/profile1
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true

version: 0.15-1
```

### Relevant Frigate log output

```shell
Traceback (most recent call last):
  File &#34;/opt/frigate/frigate/api/app.py&#34;, line 200, in config_save
    FrigateConfig.parse_yaml(new_config)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 689, in parse_yaml
    return cls.parse(config_yaml, is_json=False, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 685, in parse
    return cls.parse_object(config, **context)
  File &#34;/opt/frigate/frigate/config/config.py&#34;, line 695, in parse_object
    return cls.model_validate(
  File &#34;/usr/local/lib/python3.9/dist-packages/pydantic/main.py&#34;, line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 3 validation errors for FrigateConfig
record.pre_capture
  Extra inputs are not permitted [type=extra_forbidden, input_value=5, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
record.post_capture
  Extra inputs are not permitted [type=extra_forbidden, input_value=5, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
record.events
  Extra inputs are not permitted [type=extra_forbidden, input_value={&#39;retain&#39;: {&#39;default&#39;: 2}}, input_type=CommentedMap]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
```

### Relevant go2rtc log output

```shell
---
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/config:/config
      - /srv/frigate/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_USER=xxx
      - FRIGATE_RTSP_PASSWORD=xxx
```

### Object Detector

CPU (no coral)
