### DISCUSSION TITLE
[Detector Support]: Could I use a mini PCIe Coral with a Dell M6600 Laptop?

### DISCUSSION THREAD

**Discussion by iamapuzzle** [blakeblackshear/frigate#18249] [Detector Support]
### Describe the problem you are having

I have Frigate running on a Dell M6600 Laptop and it's doing a pretty good job with 3 cameras and only the CPU as a detector, but I'd like to see if I can improve that with a Coral. It detects people most of the time, but I'm hoping I can reduce the missed detections. I've extensively tuned the motion settings and object sizes already. The CPU doesn't appear to be maxing out and I rarely see skipped frames on the camera stats page, but 113ms Detector Inference Speed is asking to be improved.

I'm thinking of a mini PCIe Coral like this:
https://coral.ai/products/pcie-accelerator/

According to the Dell Spec sheet, the Laptop has "Slots: 2 full and 2 half Mini-Card slots".  One half slot is occupied by the WLAN chip (works fine), the other half slot is labelled DMC (empty), and the other 2 full slots are labelled SATA and WWAN (with antenna cables ready for insertion) and are both empty in my Laptop. I've been looking for more details on these slots and I believe they're mini PCI slots. I believe the SATA slot takes an mSATA SSD, which I don't intend to purchase as I'm happy with my regular 2.5in SATA drive. I'm fairly certain none of the slots are M.2 capable, it's too old for that. I've read enough about some motherboard implementations not allowing anything other than their intended uses, with missing lanes, locked configs and all sorts of proprietary nonsense that I'm scared to go ahead. I don't even know where to start verifying the port supplies enough power, I doubt Dell releases this info.

Potentially I've got 4 free slots (I could ditch the WLAN chip), but I imagine I only need 1 Coral as I think my completed system won't be more than 6 cameras.

This website shows a similar Laptop to mine:
https://www.parts-people.com/blog/2015/07/07/dell-precision-m6600-motherboard-removal-and-installation/
Steps 7, 8 and 9 show removal of cards from these slots.
This same website lists a suitable WWAN chip:
https://www.parts-people.com/index.php?action=item&id=11192
which says: "Interface (Bus) Type: PCI Express Half Mini Card" which looks pretty similar to the mini PCIe Coral.

Can someone please help me learn if this will work or not?

I know a USB Coral will do, but I understand a mini PCIe may be faster and it certainly is a lot cheaper. I'm running Frigate in Docker on a Xubuntu Linux system and I'm ok with installing PCI drivers. I know a USB Coral is driver free. I'm a little worried the USB ports can supply enough power to the Coral and I'm hoping the Mini Card slots don't have the same power limitation as at least one was designed to power a WWAN chip which could be power hungry.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    Zoom:
      - rtsp://<user>:<password>@192.168.1.201:554/Preview_01_main
      - ffmpeg:Zoom#audio=aac
    West:
      - rtsp://<user>:<password>@192.168.1.202:554/Preview_01_main
      - ffmpeg:West#audio=aac
    East:
      - rtsp://<user>:<password>@192.168.1.203:554/Preview_01_main
      - ffmpeg:East#audio=aac

#detectors:
#  coral:
#    type: edgetpu
#    device: pci
#    device: usb

record: # <----- Enable recording
  enabled: true
  retain:
    days: 60
    mode: all
  alerts:
    retain:
      days: 60
      mode: motion
  detections:
    retain:
      days: 60
      mode: motion

review:
  alerts:
    labels:
      - person
      - umbrella
      - hat
  detections:
    labels:
      - dog

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 60

#environment_vars:
#  LIBVA_DRIVER_NAME: i965
# Seems to load i965 without this line

cameras:
  Zoom: # <------ Reolink RLC-811A
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://<user>:<password>@192.168.1.201:554/Preview_01_main # <----- The main stream you want to use for recording
          roles:
            - record
            - audio
        - path: rtsp://<user>:<password>@192.168.1.201:554/Preview_01_sub # <----- The sub stream you want to use for detection
          roles:
            - detect
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
        yuv420p
    ui:
      order: 0 # <---- order of cameras instead of alphabetical
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 360
    objects:
      track:
        - person
        - face
        - umbrella
        - hat
        - dog
      filters:
        person:
          min_area: 800
          max_area: 12000
          min_ratio: 0.4
          max_ratio: 1.1 # 1.0 any object wider than it is tall is rejected
          min_score: 0.2
          threshold: 0.6
        dog:
          min_score: 0.3
          threshold: 0.6
    motion:
      mask: 
        0,0,0,1,0.083,1,0.161,0.578,0.23,0.396,0.222,0.254,0.52,0.179,0.601,0.221,0.685,0.158,1,0.158,1,0
      threshold: 36
      contour_area: 30
      improve_contrast: true
    zones:
      LowerPathZoom:
        coordinates: 0,0.309,0,1,1,1,1,0.074
        inertia: 3
        loitering_time: 0
      StreetZoom:
        coordinates: 0,0.305,1,0.071,1,0,0,0
        loitering_time: 0
    review:
      alerts:
        required_zones: LowerPathZoom
      detections: {}
  West: # <------ Reolink RLC-810A
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://<user>:<password>@192.168.1.202:554/Preview_01_main # <----- The main stream you want to use for recording
          roles:
            - record
            - audio
        - path: rtsp://<user>:<password>@192.168.1.202:554/Preview_01_sub # <----- The sub stream you want to use for detection
          roles:
            - detect
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
        yuv420p
    ui:
      order: 1 # <---- order of cameras instead of alphabetical
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 360
    objects:
      track:
        - person
        - face
        - umbrella
        - hat
        - dog
      filters:
        person:
          min_area: 1000
          max_area: 10000
          min_ratio: 0.4
          max_ratio: 1.0 # 1.0 any object wider than it is tall is rejected
          min_score: 0.2
          threshold: 0.6
        umbrella:
          min_ratio: 0.8
          max_ratio: 1.5
        dog:
          min_score: 0.3
          threshold: 0.6
    motion:
      mask:
        - 0,0,0,0.549,0.094,0.454,0.137,0.536,0.167,0.38,0.282,0.378,0.366,0.31,0.493,0.131,0.546,0.071,0.649,0.067,0.651,0
        - 1,0,1,0.117,0.769,0.146,0.742,0
      threshold: 34
      contour_area: 20
      improve_contrast: true
    zones:
      WestStairsPath:
        coordinates: 0,0.556,0.129,0.236,0.249,0.237,0.448,0.342,0.761,0.421,1,0.576,1,1,0,1
        inertia: 3
        loitering_time: 0
      LowerPathWest:
        coordinates: 0.451,0.341,0.241,0.232,0.253,0.074,1,0.077,1,0.571,0.764,0.42
        inertia: 3
        loitering_time: 0
      StreetWest:
        coordinates: 0,0,1,0,1,0.073,0,0.068
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: WestStairsPath
      detections: {}
  East: # <------ Reolink RLC-810A
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://<user>:<password>@192.168.1.203:554/Preview_01_main # <----- The main stream you want to use for recording
          roles:
            - record
            - audio
        - path: rtsp://<user>:<password>@192.168.1.203:554/Preview_01_sub # <----- The sub stream you want to use for detection
          roles:
            - detect
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
        yuv420p
    ui:
      order: 2 # <---- order of cameras instead of alphabetical
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640
      height: 360
    objects:
      track:
        - person
        - face
        - umbrella
        - hat
        - dog
#        - cat # never detected so removing to reduce load
#        - mouse # never detected so removing to reduce load
#        - bird # sometimes people got detected as birds, so removing birds (never detected an actual bird)
      filters:
        person:
          min_area: 800
          max_area: 12000
          min_ratio: 0.4
          max_ratio: 1.1 # 1.0 any object wider than it is tall is rejected
          min_score: 0.2
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.6
#        cat:
#          min_score: 0.3
#          threshold: 0.8
#        mouse:
#          min_score: 0.3
#          threshold: 0.8
#        bird:
#          min_score: 0.3
#          threshold: 0.8
    motion:
      mask:
        - 0,0,0,0.08,0.138,0.337,0.336,0.282,0.4,0.151,0.468,0.085,0.622,0.202,0.595,0.382,1,0.381,1,0
        - 0,0.943,0.059,1,0,1
        - 0.941,1,1,0.948,1,1
      threshold: 34
      contour_area: 30
      improve_contrast: true
    zones:
      PathEast:
        coordinates: 0,0.394,1,0.386,1,1,0,1
        inertia: 3
        loitering_time: 0
      LowerEast:
        coordinates: 1,0,1,0.382,0,0.388,0,0
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: PathEast
      detections: {}
camera_groups:
  Garden:
    order: 1
    icon: LuTrees
    cameras:
      - Zoom
      - West
      - East
notifications:
  enabled: true
  email: <email>

version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # required for intel GPU stats (was hoping not to need this)
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON # For Intel GPU Stats (was hoping to use this instead of privileged)
    shm_size: "128mb" # updated for my cameras
    devices:
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel (works)
      - /dev/dri/renderD129 # don't think this is required, but doesn't seem to hurt
      - /dev/dri/card1 # don't think this is required, but doesn't seem to hurt (no card0)
      - /dev/dri/card2 # don't think this is required, but doesn't seem to hurt
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel (untested)
#    environment_vars:
#      LIBVA_DRIVER_NAME=i965
#      LIBVA_DRIVER_NAME: i965
# gives error: additional property environment_vars is not allowed
    volumes:
      - ./config:/config
      - ./certificates:/etc/letsencrypt/live/frigate:ro
#      - ./storage:/media/frigate
      - ./storagemerged:/media/frigate # mergerfs with main and archive disk (script on timer copies main -> archive then shuts down archive disk until next timer, can only see older recordings when archive disk spinning)
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "443:8971"
      - "8554:8554" # RTSP feeds
```

### Relevant Frigate log output

```shell
Warnings about CPU detectors.

No errors other than when archive disk is off and older recordings are accessed, but the web interface gracefully handles this.
```

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Screenshots of the Frigate UI's System metrics pages

Detector Inference Speed 113ms, not good! But otherwise the system works well. Idle (just recording) is very low CPU usage. During motion and detections, usage goes up to 50-60%.
There is no noticeable improvement with hardware acceleration enabled. The GPU stats page says intel-vaapi 0.26%. I'm not currently running the NVIDIA drivers so the Quadro 3000M card is not being used currently. I don't believe this card is any use for detections.

### Any other information that may be helpful

Looking up the version, I now see it a new release. From the release notes, I don't think the fixes affect me, but I'll look at updating when I have some available download quota.
