### DISCUSSION TITLE
Switching from Coral to OpenVino, cripples live overview

### DISCUSSION THREAD

**Discussion by Calimerorulez** [blakeblackshear/frigate#18263] [Ask A Question]
Hi all,

Running a Coral PCI a couple of months, I've decided to upgrade my machine with an Arc a310, for detection and transcoding. When I'm running on the OpenVino detector, the live overview of all cameras randomly displays the infamous "No frames received, check log for errors" message, but no errors are shown in the log. When switching back to the Coral, the live view normally shows all live views.

Running 0.16 beta 2

Changed to the Plus Yolonas 640x640 model when switching to OpenVino.

**Comment by hawkeye217** [comment]
We'll need to see your config, logs, what hardware you are running on, the Frigate installation method, and screenshots of the metrics pages in order to be able to help.

**Reply by Calimerorulez** [reply]
Sorry, I should have known better :)

Running on an AMD Ryzen 3 4100, Arc a310, Frigate runs in a Proxmox VM, GPU and Coral are passed through and detected. Running on OpenVino, detector CPU is relatively high I think:

<img width="907" alt="image" src="https://github.com/user-attachments/assets/36ef78da-9513-4e97-bccd-bb61fdb14827" />

```
detectors:
  ov_0:
    type: openvino
    device: GPU

semantic_search:
  enabled: true
  model: jinav2
  model_size: large

detect:
  enabled: true

lpr:
  enabled: true
  format: 
    ^(\w{2}-\d{2}-\d{2})|(\d{2}-\d{2}-\w{2})|(\d{2}-\w{2}-\d{2})|(\w{2}-\d{2}-\w{2})|(\w{2}-\w{2}-\d{2})|(\d{2}-\w{2}-\w{2})|(\d{2}-\w{3}-\d{1})|(\d{1}-\w{3}-\d{2})|(\w{2}-\d{3}-\w{1})|(\w{1}-\d{3}-\w{2})|(\w{3}-\d{2}-\w{1})|(\d{1}-\w{2}-\d{3})$

face_recognition:
  enabled: true

logger:
  default: info

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 7
    pre_capture: 10
    post_capture: 10

objects:
  track:
    - person
    - car
    - truck
    - bicycle
    - motorcycle
    - cat
    - dog
    - dpd
    - postnl
    - gls
    - sports ball
    - backpack
    - bus
    - suitcase
    - handbag
    - horse
    - skateboard
    - waste_bin
    - license_plate
    - face

audio:
  enabled: true
  listen:
    - children_playing
    - cat
    - bird
    - dog
    - dogs
    - footsteps
    - clapping
    - bark
    - scream
    - speech
    - yell
    - whispering
    - laughter
    - honk
    - fireworks
    - firecracker
    - music
    - gasp
    - pant
    - snort
    - cough
    - throat_clearing
    - sneeze
    - sniff
    - run
    - chatter
    - reversing_beeps
    - bus
    - emergency_vehicle
    - police_car
    - ambulance
    - fire_engine
    - motorcycle
    - aircraft
    - aircraft_engine
    - jet_engine
    - propeller
    - helicopter
    - fixed-wing_aircraft
    - bicycle
    - skateboard
    - engine
    - light_engine
    - lawn_mower
    - chainsaw
    - medium_engine
    - heavy_engine
    - engine_knocking
    - engine_starting
    - idling
    - accelerating
    - door

ffmpeg:
  global_args: -hide_banner -loglevel warning # -threads 2

  hwaccel_args: preset-intel-qsv-h264
  #hwaccel_args: preset-vaapi
  #hwaccel_args: -r {0} -vf fps={0},scale_vaapi=w={1}:h={2},hwdownload,format=yuv420p

  input_args: preset-rtsp-restream
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p # -threads 2
    record: preset-record-ubiquiti
```

I'm running detect at 2K resolution for some of my 12 cameras, maybe that's not good either? If I change to al lower detect resolution, the thumbnails in the detected objects are lower resolution too, I do not like that very much, but that could be understandable :)
