### DISCUSSION TITLE
[Support]: Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory

### DISCUSSION THREAD

**Discussion by Zsoltt-dom** [blakeblackshear/frigate#18272] [Detector Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have an Nvidia A2000 6GB card.
Running Frigate docker image inside an LXC container.
I'd like to use ONNX detector with yolonas. On start the Frigate loads the model, it can be seen with the nvidia-smi also, but the detection falls back to cpu due to the following error:

`2025-05-17 14:17:00.943935593  [2025-05-17 14:17:00] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
2025-05-17 14:17:00.944058393  [2025-05-17 14:17:00] frigate.detectors.plugins.onnx INFO    : ONNX: loading /config/yolo_nas_l.onnx
2025-05-17 14:17:00.944420398  2025-05-17 14:17:00.944331303 [E:onnxruntime:Default, provider_bridge_ort.cc:1848 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory
2025-05-17 14:17:00.944430738  
2025-05-17 14:17:00.944611074  [2025-05-17 14:17:00] frigate.app                    INFO    : Embedding process started: 910
2025-05-17 14:17:00.971108858  [2025-05-17 14:17:00] frigate.app                    INFO    : Output process started: 955`

I have checked and in the frigate container I have libnvinfer.so.8 under /usr/local/lib/python3.11/dist-packages/tensorrt_libs.
Probably it needs to be updated to 10 in the image.

**nvidia-smi output**
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.51.02              Driver Version: 575.51.02      CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A2000               Off |   00000000:01:00.0 Off |                  Off |
| 47%   72C    P2             36W /   70W |    2437MiB /   6138MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A           14006      C   frigate.detector.onnx                   632MiB |
|    0   N/A  N/A           14008      C   frigate.embeddings_manager              532MiB |
|    0   N/A  N/A           14170      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          140MiB |
|    0   N/A  N/A           14182      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          124MiB |
|    0   N/A  N/A           14198      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          120MiB |
|    0   N/A  N/A           14211      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          116MiB |
|    0   N/A  N/A           14222      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          118MiB |
|    0   N/A  N/A           14233      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          116MiB |
|    0   N/A  N/A           14244      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          136MiB |
|    0   N/A  N/A           14256      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          156MiB |
|    0   N/A  N/A           14267      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          158MiB |
+-----------------------------------------------------------------------------------------+
```

**Detector configuration:**
`  onnx:
    type: onnx 
    device: Tensorrt
    device_id: 0

model:
  model_type: yolonas
  width: 640
  height: 640
  input_tensor: nchw
  path: /config/yolo_nas_l.onnx
  labelmap_path: /labelmap/coco-80.txt
  input_pixel_format: bgr`

### Steps to reproduce

1. User docker image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2-tensorrt
2. Configure ONNX with Tensorrt device
3. Use model_type: yolonas and load a yolonas model
...

### Version

0.16.0-1fa7ce5

### In which browser(s) are you experiencing the issue with?

Not browser dependent

### Frigate config file

```yaml
mqtt:
  host: 192.168.86.201
  port: 1883
  client_id: frigate
  stats_interval: 20

go2rtc:
  streams:
    Doorbell:
 #     - rtsp://admin:kicsirahi81@192.168.81.50:554/h264Preview_01_main
      - ffmpeg:http://192.168.81.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=x&password=y#video=copy#audio=copy#audio=opus
      - rtsp://192.168.81.50/Preview_01_sub
    Doorbell_sub:
#      - rtsp://admin:kicsirahi81@192.168.81.50:554/h264Preview_01_sub
      - ffmpeg:http://192.168.81.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=x&password=y
cameras:
# DOORBELL CAMERA
  Doorbell:
    lpr:
      enabled: true
#      known_plates:
#            Hyundai:
#             - "6703 KXT"
#             - "6703KXT" # Accounts for potential confusion between the number one (1) and capital letter I
#            Camry:
#               - "3397 MMH"
#               - "3397MMH" # 
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
#      height: 1080
#      width: 1920
      fps: 7
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        car:
          mask: 
            0.563,0.524,0.577,0.57,0.568,0.628,0.559,0.678,0.476,0.696,0.307,0.684,0.184,0.642,0.13,0.602,0.143,0.562,0.171,0.512,0.284,0.51
        person:
          min_score: 0.80
        cat:
          min_score: 0.80
    record:
      enabled: true
      retain:
        days: 120 #The number of days a recording will be kept for after a motion is detected.
        mode: active_objects
#      events:
#        retain:
#          default: 30 #The event data will be kept for 1 day. After this period, the event data will be automatically deleted.
#          mode: motion
    snapshots:
      enabled: true
      timestamp: false
      retain:
        default: 120
      bounding_box: true
    motion:
      mask:
        - 0.153,0,0.147,0.043,0.798,0.046,0.794,0.002
        - 0.093,0.42,0.073,0.443,0.058,0.459,0.071,0.474,0.105,0.495,0.142,0.51,0.192,0.514,0.239,0.511,0.289,0.51,0.349,0.49,0.389,0.451,0.388,0.389,0.343,0.354,0.268,0.33,0.208,0.343,0.139,0.372,0.094,0.395
        - 0.411,0.48,0.406,0.503,0.516,0.511,0.598,0.509,0.615,0.5,0.618,0.463
      threshold: 30
      contour_area: 10
      improve_contrast: false
    zones:
      Kapu:
        coordinates: 0.996,0.997,-0.001,0.999,0,0.692,0.418,0.504,0.434,0.002,0.998,0.002
        loitering_time: 0
      Utca:
        coordinates: 
          0,0.692,0.153,0.623,0.154,0.57,0.165,0.548,0.154,0.511,0.085,0.501,0.028,0.518,0.027,0.545,0.002,0.564
        loitering_time: 0
```

### docker-compose file or Docker CLI command

```yaml
GNU nano 7.2                                                                                                                     ./docker-compose.yml                                                                                                                               
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2-tensorrt
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000

    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    runtime: nvidia
    environment:
      FRIGATE_RTSP_PASSWORD: "x"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility,video"
      YOLO_MODELS: yolov7-320,yolov7x-640
#      USE_FP16: "false"
      LD_LIBRARY_PATH: /usr/local/lib/python3.11/dist-packages/tensorrt_llm/libs:/usr/local/lib/python3.11/dist-packages/nvidia/cublas/lib:/usr/local/lib/python3.11/dist-packages/tensorrt_libs
#  frigate:
#    environment:
#      - YOLO_MODELS=yolov7-320,yolov7x-640
#      - USE_FP16=false
```

### Relevant Frigate log output

```shell
2025-05-17 14:17:00.943935593  [2025-05-17 14:17:00] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
2025-05-17 14:17:00.944058393  [2025-05-17 14:17:00] frigate.detectors.plugins.onnx INFO    : ONNX: loading /config/yolo_nas_l.onnx
2025-05-17 14:17:00.944420398  2025-05-17 14:17:00.944331303 [E:onnxruntime:Default, provider_bridge_ort.cc:1848 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory
2025-05-17 14:17:00.944430738  
2025-05-17 14:17:00.944611074  [2025-05-17 14:17:00] frigate.app                    INFO    : Embedding process started: 910
2025-05-17 14:17:00.971108858  [2025-05-17 14:17:00] frigate.app                    INFO    : Output process started: 955
```

### Relevant go2rtc log output

```shell
info | 2025-05-17 14:16:07 | startup | Preparing new go2rtc config...
info | 2025-05-17 14:16:07 | startup | Starting go2rtc...
info | 2025-05-17 14:16:07 | startup | go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
info | 2025-05-17 14:16:07 | startup | config path=/dev/shm/go2rtc.yaml
info | 2025-05-17 14:16:07 | api     | listen addr=:1984
info | 2025-05-17 14:16:07 | rtsp    | listen addr=:8554
info | 2025-05-17 14:16:07 | webrtc  | listen addr=:8555
info | 2025-05-17 14:16:16 | startup | Starting go2rtc healthcheck service...
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink Doorbell Wifi

### Screenshots of the Frigate UI's System metrics pages

<img width="2363" alt="Screenshot 2025-05-17 at 15 25 37" src="https://github.com/user-attachments/assets/87b3df4e-c90a-4775-86cc-535220d8e672" />
