### DISCUSSION TITLE
[Camera Support]:

### DISCUSSION THREAD

**Discussion by Jonnehs** [blakeblackshear/frigate#18271] [Camera Support]
### Describe the problem you are having

Hello!

Replacing my estate of Reolink cameras with some EmpireTech IPC-T549M-ALED-S3 2.8MM turret low light cameras.

I read some comments that said the h.264 and aac audio. I limited the sub stream to 10 FPS, anyone have any tips for bitrate, iframe interval or SVC settings? Or if the smooth vs clear slider needs adjusting? 

Just trying to get this first one half configured before I rip down the old camera and stick this up

![image](https://github.com/user-attachments/assets/35e82074-7622-4396-9e0e-7d96c5fc51cd)

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: 10.25.1.15
  user: MQTTUser
  password: mqttpassword
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
go2rtc:
  streams:
    Driveway_CAM:
      - rtsp://frigate:frigatepassword@10.25.101.201:554/cam/realmonitor?channel=1&subtype=0
    Driveway_CAM_sub:
      - rtsp://frigate:frigatepassword@10.25.101.201:554/cam/realmonitor?channel=1&subtype=1
    Doorbell:
      - ffmpeg:https://10.25.101.105/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=frigatepassword#video=copy#audio=copy#audio=opus
      - rtsp://frigate:frigatepassword@10.25.1.104:554/h264Preview_01_sub
    Doorbell_sub:
      - ffmpeg:https://10.25.101.105/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=frigatepassword
  candidates:
    - 10.25.1.16:8555
    - stun:8555
cameras:
  Driveway_CAM:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_CAM_sub
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway_CAM
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell_sub
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Doorbell
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
motion:
  threshold: 40
  contour_area: 40
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 21
record:
  enabled: true
  preview:
    quality: very_high
  retain:
    days: 21
    mode: motion
  alerts:
    retain:
      days: 21
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 21
    pre_capture: 10
    post_capture: 10
live:
  height: 720
  quality: 5
objects:
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog
    - bird
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

IPC-T549M-ALED-S3 2.8MM

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/20193853-8718-42eb-a005-e14a55a9e029)

{"return_code":0,"stderr":"","stdout":"vainfo: VA-API version: 1.22 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP"}

**Comment by NickM-27** [comment]
1. Leave svc off, don't touch the slider
2. Might as well disable substream1 and just use substream2 (select on the right drop down) as it supports higher resolution

**Reply by NickM-27** [reply]
Note that substream2 is subtype=2

**Reply by Jonnehs** [reply]
What would you set the bitrates to for each stream?

**Reply by NickM-27** [reply]
![Screen Shot 2025-05-17 at 09 07 53 AM](https://github.com/user-attachments/assets/d477a748-6faa-4ef5-b455-6da5ca3dedd8)

**Reply by Jonnehs** [reply]
thanks, any recommendations for the detect settings in frigate? Do you use the full 1080p res?

**Reply by NickM-27** [reply]
This particular cameras has 3 sub streams so I use this for live and then the 3rd sub is 1280x720 and I use that for detect

**Reply by Jonnehs** [reply]
hm, it looks a bit choppy for me - dancing pixels when a capture happens, doesn't look like the full res - not sure how to describe it

![image](https://github.com/user-attachments/assets/d7cb2999-275a-4aa6-8060-42e1c68e1003)


```
mqtt:
  host: 10.25.1.15
  user: MQTTUser
  password: MQTTPassword
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime
      1 -c:v copy -c:a copy
go2rtc:
  streams:
    Driveway:
      - rtsp://frigate:frigatepassword@10.25.101.201:554/cam/realmonitor?channel=1&subtype=0
    Driveway_sub:
      - rtsp://frigate:frigatepassword@10.25.101.201:554/cam/realmonitor?channel=1&subtype=2
    Front:
      - ffmpeg:https://10.25.101.102/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=frigatepassword#video=copy#audio=copy#audio=opus
    Front_sub:
      - ffmpeg:https://10.25.101.102/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=frigatepassword
    Garage:
      - ffmpeg:https://10.25.101.103/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=frigatepassword#video=copy#audio=copy#audio=opus
    Garage_sub:
      - ffmpeg:https://10.25.101.103/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=frigatepassword
    Rear:
      - ffmpeg:https://10.25.101.104/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=frigatepassword#video=copy#audio=copy#audio=opus
    Rear_sub:
      - ffmpeg:https://10.25.101.104/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=frigatepassword
    Doorbell:
      - ffmpeg:https://10.25.101.105/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=frigatepassword#video=copy#audio=copy#audio=opus
      - rtsp://frigate:frigatepassword@10.25.1.104:554/h264Preview_01_sub
    Doorbell_sub:
      - ffmpeg:https://10.25.101.105/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=frigatepassword
  candidates:
    - 10.25.1.16:8555
    - stun:8555
cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Driveway
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15
    zones:
      Alert:
        coordinates: 0.015,0.246,0.021,0.353,0.08,0.33,0.07,0.218
        loitering_time: 0
        objects: person
      driveway:
        coordinates: 0.147,0.211,0.315,0.195,0.319,0.237,0.156,0.251
        loitering_time: 0
        objects:
          - car
          - motorcycle
      drivewayparked:
        coordinates: 
          0.157,0.282,0.344,0.249,0.414,0.215,0.978,0.186,0.857,0.904,0.822,1,0.374,0.996,0.254,0.666
        loitering_time: 0
        inertia: 3
        objects:
          - bird
          - cat
          - dog
          - motorcycle
          - person
    review:
      alerts:
        required_zones:
          - driveway
          - drivewayparked
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell_sub
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Doorbell
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
  Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front
          input_args: preset-rtsp-restream
          roles:
            - record
    zones:
      frontgarden:
        coordinates: 
          0.002,0.42,0.122,0.418,0.269,0.411,0.494,0.375,0.661,0.359,0.882,0.292,1,0.425,1,0.999,0,0.999
        inertia: 3
        loitering_time: 0
    detect:
      width: 1280
      height: 720
      fps: 10
    review:
      alerts:
        required_zones: frontgarden
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
  Rear:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Rear_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Rear
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    motion:
      threshold: 35
      contour_area: 40
      improve_contrast: 'true'
motion:
  threshold: 40
  contour_area: 40
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 21
record:
  enabled: true
  preview:
    quality: very_high
  retain:
    days: 21
    mode: motion
  alerts:
    retain:
      days: 21
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 21
    pre_capture: 10
    post_capture: 10
live:
  height: 720
  quality: 5
objects:
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog
    - bird
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```
