### DISCUSSION TITLE
[Config Support]: Using drawtext with customized text doesn't work in Frigate but does in go2rtc.

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#18287] [Config Support]
### Describe the problem you are having

When trying to insert a timestamp into the camera feed using go2rtc I can get it working using the go2rtc docker (1.9.9) but when I try to bring it over to Frigate's go2rtc configuration it throws an invalid frigate configuration file.

This works in go2rtc standalone:

```
streams:
    # Driveway
  driveway:
    - ffmpeg:rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0#audio=opus#video=h264#drawtext=text='%{localtime\:Driveway - %a %Y-%m-%d %I\\\:%M\\\:%S%p}':x=3200:y=2:fontsize=32:fontcolor=white:box=1:boxcolor=black
```

But when I copy it over into Frigate I get the following error:

```
Error: bad file '/config/config.yml': yaml: line 160: found unknown escape character
[2:20 PM]
```

I've tried all types of ways of escaping the configuration in  Frigate's go2rtc section but no luck. The pasted config below works but of course looking to customize the drawtext using the text field. 

### Version

0.16.0-f4d5ebf

### Frigate config file

```yaml
go2rtc:
  webrtc:
    listen: :8555
    candidates:
      - frigate.ip:8555
      - stun:8555
  rtsp:
    username: '{FRIGATE_RTSP_USER}'
    password: '{FRIGATE_RTSP_PASSWORD}'
  streams:
    # Driveway
    driveway:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=0#audio=opus#video=h264#drawtext=x=3200:y=2:fontsize=32:fontcolor=white:box=1:boxcolor=black
      #- ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=0#audio=opus#video=h264#drawtext=text=\'%{localtime\:Driveway - %a %Y-%m-%d %I\\\:%M\\\:%S%p}\':x=3200:y=2:fontsize=32:fontcolor=white:box=1:boxcolor=black
    driveway_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@driveway.camera:554/cam/realmonitor?channel=1&subtype=2
    # BBQ Deck
    bbq_deck:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@bbqdeck.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:bbq_deck#audio=opus
    bbq_deck_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@bbqdeck.camera:554/cam/realmonitor?channel=1&subtype=2
    # Basement with AC units
    basement_side:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@basementside.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:basement_side#audio=opus
    basement_side_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@basementside.camera:554/cam/realmonitor?channel=1&subtype=2
    # Front walkway
    front_walkway:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontwalkway.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:front_walkway#audio=opus
    front_walkway_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontwalkway.camera:554/cam/realmonitor?channel=1&subtype=2
    # Mudroom
    mudroom:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@mudroom.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:mudroom#audio=opus
    mudroom_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@mudroom.camera:554/cam/realmonitor?channel=1&subtype=2
    # Kiddo's room
    charlotte:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@charlotte.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:charlotte#audio=opus
    # Double Fence
    double_fence:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@double-fence.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:double_fence#audio=opus
    double_fence_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@double-fence.camera:554/cam/realmonitor?channel=1&subtype=2
    # Patio
    patio:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@patio.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:patio#audio=opus
    patio_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@patio.camera:554/cam/realmonitor?channel=1&subtype=2
    # Backyard
    backyard:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@backyard.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:backyard#audio=opus
    backyard_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@backyard.camera:554/cam/realmonitor?channel=1&subtype=2
    # Playroom
    playroom:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom.camera:554/Streaming/Channels/101#backchannel=0
      - ffmpeg:playroom#audio=opus
    playroom_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom.camera:554/Streaming/Channels/102#backchannel=0
    # Richie Office
    richie_office:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@richie-office.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:richie_office#audio=opus
    richie_office_sub:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@richie-office.camera:554/cam/realmonitor?channel=1&subtype=2
    playroom_ptz:
      - ffmpeg:http://playroom-ptz.camera/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
      #- ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@playroom-ptz.camera:554/Preview_01_main
      #- ffmpeg:playroom_ptz#audio=opus
      #- "ffmpeg:http://playroom-ptz.camera/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    # Frontyard
    frontyard:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontyard.camera:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:frontyard#audio=opus
    frontyard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontyard.camera:554/cam/realmonitor?channel=1&subtype=2
```

### Relevant Frigate log output

```shell
Error: bad file '/config/config.yml': yaml: line 160: found unknown escape character
[2:20 PM]
```

### Relevant go2rtc log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

TensorRT
