### DISCUSSION TITLE
[Detector Support]: nvidia P2200  [h264 @ 0x5a8f91ab5cc0] Failed setup for format cuda: hwaccel initialisation returned error.

### DISCUSSION THREAD

**Discussion by alsimms** [blakeblackshear/frigate#18280] [Detector Support] [answered]
### Describe the problem you are having

I am having issues configuring P2200, I can see the stream but detect is not working. Not sure if I have something incorrect in my config, testing with only one camera at the moment and it is complaining that my P2200 Hardware is lacking required capabilities.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false
detectors:
  onnx:
    type: onnx 
    device: '2' #This is the default, select the first GPU
ffmpeg:
  hwaccel_args: preset-nvidia-h264
model:
  width: 320 
  height: 320 
  input_tensor: nchw
  model_type: yolonas
  input_pixel_format: bgr
  labelmap_path: /config/models/yolonas/coco_80cl.txt  
  path: /config/models/yolonas/yolo_nas_s.onnx

go2rtc:
#  log:
#    exec: trace
#    webrtc: trace
#    stream: trace
#    rtsp: trace
# Optional: Live stream configuration for WebUI.
# NOTE: Can be overridden at the camera level
  live:
  # Optional: Set the name of the stream configured in go2rtc
  # that should be used for live view in frigate WebUI. (default: name of camera)
  # NOTE: In most cases this should be set at the camera level only.
    stream_name: test
  # Optional: Set the height of the jsmpeg stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
    height: 720
  # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
    quality: 8

  streams:
    front:
      - onvif://xx:xx@xx.xx.xx.xx:2020?subtype=profile_1
      - ffmpeg:front#video=video=h264#audio=aac#hardware

    front_sub:
      - onvif://xx:xx@xx.xx.xx.xx:2020?subtype=profile_2
      - ffmpeg:front_sub#video=h264#audio=aac#hardware
    deck:
      - onvif://xx:xx@xx.xx.xx.xx:2020?subtype=profile_1
      - ffmpeg:deck#video=h264#audio=aac#hardware

    deck_sub:
      - onvif://xx:xx@xx.xx.xx.xx:2020?subtype=profile_2
      - ffmpeg:deck_sub#video=h264#audio=aac#hardware
    swing:
      - onvif:xx:xx@xx.xx.xx.xx:2020?subtype=profile_1
      - ffmpeg:swing#video=h264#audio=aac#hardware
    swing_sub:
      - onvif://xx:xx@xx.xx.xx.xx:2020?subtype=profile_2
      - ffmpeg:swing_sub#video=h264#audio=aac#hardware

  webrtc:
    candidates:
      - xx.xx.xx.xx:8555
      - stun:8555


cameras:
  front: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          hwaccel_args: preset-nvidia-h264
#          input_args: preset-rtsp-restream
          roles:
            - detect
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigateplus
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "750mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/xx/Docker/frigateplus/config:/config/
      - /mnt/xx/Docker/frigateplus/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
#      - "1935:1935" # rtmp
      - "1984:1984" # go2rtc's web interface
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
Container frigateplus  Created                                                                                                                                                                                                      0.0s 
Attaching to frigateplus
frigateplus  | s6-rc: info: service s6rc-fdholder: starting
frigateplus  | s6-rc: info: service s6rc-oneshot-runner: starting
frigateplus  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigateplus  | s6-rc: info: service fix-attrs: starting
frigateplus  | s6-rc: info: service s6rc-fdholder successfully started
frigateplus  | s6-rc: info: service fix-attrs successfully started
frigateplus  | s6-rc: info: service legacy-cont-init: starting
frigateplus  | s6-rc: info: service legacy-cont-init successfully started
frigateplus  | s6-rc: info: service trt-model-prepare: starting
frigateplus  | s6-rc: info: service log-prepare: starting
frigateplus  | s6-rc: info: service log-prepare successfully started
frigateplus  | s6-rc: info: service nginx-log: starting
frigateplus  | s6-rc: info: service go2rtc-log: starting
frigateplus  | No models to convert.
frigateplus  | s6-rc: info: service frigate-log: starting
frigateplus  | s6-rc: info: service certsync-log: starting
frigateplus  | s6-rc: info: service trt-model-prepare successfully started
frigateplus  | s6-rc: info: service nginx-log successfully started
frigateplus  | s6-rc: info: service go2rtc-log successfully started
frigateplus  | s6-rc: info: service go2rtc: starting
frigateplus  | s6-rc: info: service frigate-log successfully started
frigateplus  | s6-rc: info: service certsync-log successfully started
frigateplus  | s6-rc: info: service go2rtc successfully started
frigateplus  | s6-rc: info: service go2rtc-healthcheck: starting
frigateplus  | s6-rc: info: service frigate: starting
frigateplus  | s6-rc: info: service frigate successfully started
frigateplus  | s6-rc: info: service nginx: starting
frigateplus  | s6-rc: info: service go2rtc-healthcheck successfully started
frigateplus  | 2025-05-18 03:12:23.291039336  [INFO] Preparing new go2rtc config...
frigateplus  | 2025-05-18 03:12:23.293090554  [INFO] Starting NGINX...
frigateplus  | 2025-05-18 03:12:23.293559899  [INFO] Preparing Frigate...
frigateplus  | 2025-05-18 03:12:23.380857762  [INFO] Starting Frigate...
frigateplus  | 2025-05-18 03:12:23.660140770  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
frigateplus  | 2025-05-18 03:12:23.783365266  [INFO] Starting go2rtc...
frigateplus  | 2025-05-18 03:12:23.891641117  03:12:23.891 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
frigateplus  | 2025-05-18 03:12:23.891648112  03:12:23.891 INF config path=/dev/shm/go2rtc.yaml
frigateplus  | 2025-05-18 03:12:23.892712615  03:12:23.892 INF [rtsp] listen addr=:8554
frigateplus  | 2025-05-18 03:12:23.892855469  03:12:23.892 INF [api] listen addr=:1984
frigateplus  | 2025-05-18 03:12:23.894277761  03:12:23.894 INF [webrtc] listen addr=:8555
frigateplus  | s6-rc: info: service nginx successfully started
frigateplus  | s6-rc: info: service certsync: starting
frigateplus  | s6-rc: info: service certsync successfully started
frigateplus  | s6-rc: info: service legacy-services: starting
frigateplus  | 2025-05-18 03:12:24.395006847  [INFO] Starting certsync...
frigateplus  | s6-rc: info: service legacy-services successfully started
frigateplus  | 2025-05-18 03:12:24.483399129  127.0.0.1 - - [18/May/2025:03:12:24 +0000] "" 400 0 "-" "-" "-"
frigateplus  | 2025-05-18 03:12:25.665078645  [2025-05-18 03:12:25] frigate.util.config            INFO    : Checking if frigate config needs migration...
frigateplus  | 2025-05-18 03:12:25.690022559  [2025-05-18 03:12:25] frigate.util.config            INFO    : frigate config does not need migration...
frigateplus  | 2025-05-18 03:12:27.376956055  2025/05/18 03:12:27 [error] 177#177: *2 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: , request: "GET /ws HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "xx.xx.xx.xx:5000"
frigateplus  | 2025-05-18 03:12:27.377016447  2025/05/18 03:12:27 [error] 177#177: *2 auth request unexpected status: 502 while sending to client, client: xx.xx.xx.xx, server: , request: "GET /ws HTTP/1.1", host: "xx.xx.xx.xx:5000"
frigateplus  | 2025-05-18 03:12:27.377121297  xx.xx.xx.xx - - [18/May/2025:03:12:27 +0000] "GET /ws HTTP/1.1" 500 177 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0" "-"
frigateplus  | 2025-05-18 03:12:28.152027988  2025/05/18 03:12:28 [error] 178#178: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
frigateplus  | 2025-05-18 03:12:28.152072616  2025/05/18 03:12:28 [error] 178#178: *4 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
frigateplus  | 2025-05-18 03:12:29.316182384  [2025-05-18 03:12:29] frigate.app                    INFO    : Starting Frigate (0.15.0-6cb5cfb)
frigateplus  | 2025-05-18 03:12:29.329775622  [2025-05-18 03:12:29] peewee_migrate.logs            INFO    : Starting migrations
frigateplus  | 2025-05-18 03:12:29.332096576  [2025-05-18 03:12:29] peewee_migrate.logs            INFO    : There is nothing to migrate
frigateplus  | 2025-05-18 03:12:29.346738167  [2025-05-18 03:12:29] frigate.app                    INFO    : Recording process started: 422
frigateplus  | 2025-05-18 03:12:29.356703306  [2025-05-18 03:12:29] frigate.app                    INFO    : Review process started: 423
frigateplus  | 2025-05-18 03:12:29.359506004  [2025-05-18 03:12:29] frigate.app                    INFO    : go2rtc process pid: 105
frigateplus  | 2025-05-18 03:12:29.376753595  [2025-05-18 03:12:29] detector.onnx                  INFO    : Starting detection process: 438
frigateplus  | 2025-05-18 03:12:29.389871607  [2025-05-18 03:12:29] frigate.app                    INFO    : Output process started: 458
frigateplus  | 2025-05-18 03:12:29.416635747  [2025-05-18 03:12:29] frigate.app                    INFO    : Camera processor started for tapofront: 472
frigateplus  | 2025-05-18 03:12:29.434132317  [2025-05-18 03:12:29] frigate.app                    INFO    : Capture process started for tapofront: 473
frigateplus  | 2025-05-18 03:12:29.440371280  [2025-05-18 03:12:29] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
frigateplus  | 2025-05-18 03:12:29.612133748  [2025-05-18 03:12:29] frigate.detectors.plugins.onnx INFO    : ONNX: loading /config/models/yolonas/yolo_nas_s.onnx
frigateplus  | 2025-05-18 03:12:29.612392932  [2025-05-18 03:12:29] frigate.detectors.plugins.onnx INFO    : ONNX: /config/models/yolonas/yolo_nas_s.onnx loaded
frigateplus  | 2025-05-18 03:12:29.624992618  [2025-05-18 03:12:29] frigate.api.fastapi_app        INFO    : Starting FastAPI app
frigateplus  | 2025-05-18 03:12:29.726634550  [2025-05-18 03:12:29] frigate.api.fastapi_app        INFO    : FastAPI started
frigateplus  | 2025-05-18 03:12:32.787197116  [2025-05-18 03:12:32] frigate.video                  ERROR   : tapofront: Unable to read frames from ffmpeg process.
frigateplus  | 2025-05-18 03:12:32.787435577  [2025-05-18 03:12:32] frigate.video                  ERROR   : tapofront: ffmpeg process is not running. exiting capture thread...
frigateplus  | 2025-05-18 03:12:33.295456544  [INFO] Starting go2rtc healthcheck service...
frigateplus  | 2025-05-18 03:12:49.464417202  [2025-05-18 03:12:49] watchdog.tapofront             ERROR   : Ffmpeg process crashed unexpectedly for tapofront.
frigateplus  | 2025-05-18 03:12:49.481614010  [2025-05-18 03:12:49] watchdog.tapofront             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigateplus  | 2025-05-18 03:12:49.481700089  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [h264 @ 0x56ca88f9ed40] Hardware is lacking required capabilities
frigateplus  | 2025-05-18 03:12:49.481780797  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [h264 @ 0x56ca88f9ed40] Failed setup for format cuda: hwaccel initialisation returned error.
frigateplus  | 2025-05-18 03:12:49.481840030  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
frigateplus  | 2025-05-18 03:12:49.481947555  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [vf#0:0 @ 0x56ca88274840] Error reinitializing filters!
frigateplus  | 2025-05-18 03:12:49.482001540  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [vf#0:0 @ 0x56ca88274840] Task finished with error code: -38 (Function not implemented)
frigateplus  | 2025-05-18 03:12:49.482032154  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [vf#0:0 @ 0x56ca88274840] Terminating thread with return code -38 (Function not implemented)
frigateplus  | 2025-05-18 03:12:49.482152486  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [vost#0:0/rawvideo @ 0x56ca8827e340] Could not open encoder before EOF
frigateplus  | 2025-05-18 03:12:49.482262047  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [vost#0:0/rawvideo @ 0x56ca8827e340] Task finished with error code: -22 (Invalid argument)
frigateplus  | 2025-05-18 03:12:49.482461022  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [vost#0:0/rawvideo @ 0x56ca8827e340] Terminating thread with return code -22 (Invalid argument)
frigateplus  | 2025-05-18 03:12:49.482557131  [2025-05-18 03:12:49] ffmpeg.front.detect        ERROR   : [out#0/rawvideo @ 0x56ca882f5d00] Nothing was written into output file, because at least one of its streams received no packets
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![front2](https://github.com/user-attachments/assets/063d9147-f759-492d-acef-c21a1c484a82)
![frigate1](https://github.com/user-attachments/assets/67d84abf-c10b-4c2a-8ebd-0b6940651f7d)

### Any other information that may be helpful

Output of nvidia-smi inside the container.
![frigate4](https://github.com/user-attachments/assets/fdd972c5-e09a-4c52-ac86-f8fac09f5bf6)

# sudo apt list --installed |grep nvid    --> on host, not on vm.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvidia-cfg1-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
libnvidia-common-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 all [installed,automatic]
libnvidia-compute-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
libnvidia-container-tools/unknown,now 1.17.6-1 amd64 [installed,upgradable to: 1.17.7-1]
libnvidia-container1/unknown,now 1.17.6-1 amd64 [installed,upgradable to: 1.17.7-1]
libnvidia-decode-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
libnvidia-egl-wayland1/noble,now 1:1.1.13-1build1 amd64 [installed,automatic]
libnvidia-encode-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
libnvidia-extra-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
libnvidia-fbc1-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
libnvidia-gl-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
linux-modules-nvidia-570-6.8.0-59-generic/noble-updates,noble-security,now 6.8.0-59.61+1 amd64 [installed,automatic]
linux-modules-nvidia-570-6.8.0-60-generic/noble-updates,noble-security,now 6.8.0-60.63+1 amd64 [installed,automatic]
linux-modules-nvidia-570-generic/noble-updates,noble-security,now 6.8.0-60.63+1 amd64 [installed]
linux-objects-nvidia-570-6.8.0-59-generic/noble-updates,noble-security,now 6.8.0-59.61+1 amd64 [installed,automatic]
linux-objects-nvidia-570-6.8.0-60-generic/noble-updates,noble-security,now 6.8.0-60.63+1 amd64 [installed,automatic]
linux-signatures-nvidia-6.8.0-59-generic/noble-updates,noble-security,now 6.8.0-59.61+1 amd64 [installed,automatic]
linux-signatures-nvidia-6.8.0-60-generic/noble-updates,noble-security,now 6.8.0-60.63+1 amd64 [installed,automatic]
nvidia-compute-utils-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
nvidia-container-toolkit-base/unknown,now 1.17.6-1 amd64 [installed,upgradable to: 1.17.7-1]
nvidia-container-toolkit/unknown,now 1.17.6-1 amd64 [installed,upgradable to: 1.17.7-1]
nvidia-driver-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed]
nvidia-firmware-570-570.133.07/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
nvidia-firmware-570-server-570.133.20/noble-updates,noble-security,now 570.133.20-0ubuntu0.24.04.1 amd64 [installed,auto-removable]
nvidia-kernel-common-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
nvidia-kernel-source-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
nvidia-prime/noble,now 0.8.17.2 all [installed,automatic]
nvidia-settings/noble,now 510.47.03-0ubuntu4 amd64 [installed,automatic]
nvidia-utils-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-570/noble-updates,noble-security,now 570.133.07-0ubuntu0.24.04.1 amd64 [installed,automatic]

----------------------------------------------

ffprobe of camera.

Input #0, rtsp, from 'rtsp://xxx:xxx@xxx.xxx.xxx.xxx/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 2688x1520, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
  
  Input #0, rtsp, from 'rtsp://xxx:xxx@xxx.xxx.xxx.xxx/stream2':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 1280x720, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

---------------------------------------------

ffmpeg codecs available in the container.

 V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)

---------
Support matrix for P2200

https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

Not really sure if my camera profile is not supported by card or if I have other issues.

Thanks in advance.

PS. I would like to add that the same card is working fine on another docker container on the same server and can read and transcode files fine. So hardware accel is working on this other container.
