### DISCUSSION TITLE
[Camera Support]: How to set up PTZ on Dahua IPC-T54IR-AS-6mm-S3?

### DISCUSSION THREAD

**Discussion by ZogKarndon** [blakeblackshear/frigate#18293] [Camera Support] [answered]
### Describe the problem you are having

I'm trying to set up PTZ on my new IPC-T54IR-AS-6mm-S3 cameras that I finally got installed and working.   The camera works, and I can get to the config page, and it *says* that ONVIF is enabled and supported, but Frigate says:
`Unable to get Onvif capabilities for camera: front_left: Unknown error: Device doesn`t support service: ptz`

Frigate can stream 

### Version

 0.15.0-6cb5cfb

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate2.lan:5000/api/config/schema
mqtt:
  host: homeassistant.lan
  user: frigate
  password: "{FRIGATE_LORYTA_PASSWORD}"

detectors:
  coral:
    type: edgetpu
    device: usb
#  ov:
#    type: openvino
#    device: GPU

go2rtc:
  streams:
    office:
      - rtsp://foscamera:{FRIGATE_OFFICE_PASSWORD}@192.168.1.231:88/videoMain # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
#      - "ffmpeg:office#audio=opus" # <- copy of the stream which transcodes audio to opus
    office_sub:
      - rtsp://foscamera:{FRIGATE_OFFICE_PASSWORD}@192.168.1.231:88/videoSub # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
#      - "ffmpeg:office_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    birdcam_sub:
      - rtsp://birdcam:{FRIGATE_BIRD_PASSWORD}@192.168.0.137:88/videoSub  # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:birdcam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    birdcam:
      - rtsp://birdcam:{FRIGATE_BIRD_PASSWORD}@192.168.0.137:88/videoMain # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:birdcam#audio=opus" # <- copy of the stream which transcodes audio to opus
    front_left:
      - rtsp://admin:{FRIGATE_LORYTA_PASSWORD}@192.168.0.214:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:birdcam#audio=opus" # <- copy of the stream which transcodes audio to opus
    front_left_sub:
      - rtsp://admin:{FRIGATE_LORYTA_PASSWORD}@192.168.0.214:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:birdcam#audio=opus" # <- copy of the stream which transcodes audio to opus
    front_left_rotated:
      - "ffmpeg:front_left#video=h264#rotate=180"
    walkway:
      - rtsp://admin:{FRIGATE_LORYTA_PASSWORD}@192.168.3.109:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:birdcam#audio=opus" # <- copy of the stream which transcodes audio to opus
    walkway_sub:
      - rtsp://admin:{FRIGATE_LORYTA_PASSWORD}@192.168.3.109:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:birdcam#audio=opus" # <- copy of the stream which transcodes audio to opus
#    walkway_rotated:
#      - "ffmpeg:walkway#video=h264#rotate=90"

cameras:
  front_left:
    ffmpeg:
      hwaccel_args:  preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front_left_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_left_rotated
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
      host: 192.168.0.214
      port: 80
      user: onvif
      password: "{FRIGATE_LORYTA_PASSWORD}"
    detect:
      width: 704
      height: 360
    objects:
      track:
        - person
        - dog
        - car
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      alerts:
        retain:
          days: 5
        pre_capture: 2
      detections:
        retain:
          days: 5
        pre_capture: 2
  walkway:
    ffmpeg:
      hwaccel_args:  preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/walkway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/walkway
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 704
      height: 360
    objects:
      track:
        - person
        - dog
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      alerts:
        retain:
          days: 5
        pre_capture: 2
      detections:
        retain:
          days: 5
        pre_capture: 2
  office:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/office_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/office # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
    motion:
      mask:
        - 640,0,640,360,495,360,493,0
    objects:
      filters:
        person:
          mask:
            - 84,172,261,159,247,87,74,37
      track:
        - person
        - dog
    record:
      enabled: true
      retain:
        days: 20
        mode: motion
      alerts:
        retain:
          days: 20
        pre_capture: 2
      detections:
        retain:
          days: 20
        pre_capture: 2
  birdcam:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/birdcam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/birdcam
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    motion:
      improve_contrast: true
      mask:
        - 640,224,590,194,548,217,0,148,0,0,34,0,1280,0,1280,260
#        - 640,0,640,139,342,109,285,79,243,111,0,123,0,0
    objects:
      track:
        - bird
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
        mode: active_objects
        objects:
          bird: 10
          dog: 1
    record:
      enabled: true
      alerts:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
    mqtt:
      enabled: true
      bounding_box: false
      timestamp: false
      quality: 95 
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-05-19 04:02:55.613882195  [INFO] Preparing Frigate...
2025-05-19 04:02:55.681430122  [INFO] Starting Frigate...
2025-05-19 04:02:57.313797399  [2025-05-19 04:02:57] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-05-19 04:02:57.335435286  [2025-05-19 04:02:57] frigate.util.config            INFO    : frigate config does not need migration...
2025-05-19 04:02:57.496257547  [2025-05-19 04:02:57] frigate.util.services          INFO    : Automatically detected vaapi hwaccel for video decoding
2025-05-19 04:02:57.508518510  [2025-05-19 04:02:57] frigate.app                    INFO    : Starting Frigate (0.15.0-6cb5cfb)
2025-05-19 04:02:57.516231432  [2025-05-19 04:02:57] peewee_migrate.logs            INFO    : Starting migrations
2025-05-19 04:02:57.516475064  [2025-05-19 04:02:57] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-05-19 04:02:57.667029896  [2025-05-19 04:02:57] frigate.app                    INFO    : Recording process started: 541
2025-05-19 04:02:57.667034454  [2025-05-19 04:02:57] frigate.app                    INFO    : Review process started: 542
2025-05-19 04:02:57.668283629  [2025-05-19 04:02:57] frigate.app                    INFO    : go2rtc process pid: 98
2025-05-19 04:02:57.679770313  [2025-05-19 04:02:57] detector.coral                 INFO    : Starting detection process: 557
2025-05-19 04:03:00.293600345  [2025-05-19 04:02:57] frigate.app                    INFO    : Output process started: 576
2025-05-19 04:03:00.293659992  [2025-05-19 04:02:57] frigate.app                    INFO    : Camera processor started for front_left: 597
2025-05-19 04:03:00.296699602  [2025-05-19 04:02:57] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-05-19 04:03:00.296886500  [2025-05-19 04:02:57] frigate.app                    INFO    : Camera processor started for walkway: 599
2025-05-19 04:03:00.297011066  [2025-05-19 04:02:57] frigate.app                    INFO    : Camera processor started for office: 602
2025-05-19 04:03:00.297105417  [2025-05-19 04:03:00] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-05-19 04:03:00.297211841  [2025-05-19 04:02:57] frigate.app                    INFO    : Camera processor started for birdcam: 614
2025-05-19 04:03:00.297213992  [2025-05-19 04:02:57] frigate.app                    INFO    : Capture process started for front_left: 632
2025-05-19 04:03:00.297215218  [2025-05-19 04:02:57] frigate.app                    INFO    : Capture process started for walkway: 657
2025-05-19 04:03:00.297219402  [2025-05-19 04:02:57] frigate.app                    INFO    : Capture process started for office: 661
2025-05-19 04:03:00.297237766  [2025-05-19 04:02:57] frigate.app                    INFO    : Capture process started for birdcam: 665
2025-05-19 04:03:00.297246446  [2025-05-19 04:02:57] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-05-19 04:03:00.297261609  [2025-05-19 04:02:57] frigate.api.fastapi_app        INFO    : FastAPI started
2025-05-19 04:03:00.297284201  [2025-05-19 04:02:58] frigate.comms.dispatcher       INFO    : Turning on snapshots for office
2025-05-19 04:04:15.243867485  [2025-05-19 04:04:15] frigate.ptz.onvif              ERROR   : Unable to get Onvif capabilities for camera: front_left: Unknown error: Device doesn`t support service: ptz
2025-05-19 04:04:27.756957473  [2025-05-19 04:04:27] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front_left. Keeping the 6 most recent segments out of 8 and discarding the rest...
```

### Relevant go2rtc log output

```shell
2025-05-19 04:02:55.613103142  [INFO] Preparing new go2rtc config...
2025-05-19 04:02:56.017143896  [INFO] Starting go2rtc...
2025-05-19 04:02:56.092837142  04:02:56.092 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-05-19 04:02:56.092843596  04:02:56.092 INF config path=/dev/shm/go2rtc.yaml
2025-05-19 04:02:56.093383121  04:02:56.093 INF [rtsp] listen addr=:8554
2025-05-19 04:02:56.093386340  04:02:56.093 INF [api] listen addr=:1984
2025-05-19 04:02:56.093398991  04:02:56.093 INF [webrtc] listen addr=:8555/tcp
2025-05-19 04:03:05.613489988  [INFO] Starting go2rtc healthcheck service...
2025-05-19 04:04:15.388012155  04:04:15.387 INF [streams] can't add track error="wrong response on DESCRIBE"
2025-05-19 04:04:15.388203800  04:04:15.388 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="start from CONN state" url=rtsp://admin:Ch3Ga3Ly3@192.168.0.214:554/cam/realmonitor?channel=1&subtype=0
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":704,"height":480,"avg_frame_rate":"30/1"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":2688,"height":1520,"avg_frame_rate":"30/1"}]}}]
```

### Frigate stats

```json
{"cameras":{"front_left":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":6.3,"detection_enabled":true,"pid":597,"capture_pid":632,"ffmpeg_pid":640,"audio_rms":0.0,"audio_dBFS":0.0},"walkway":{"camera_fps":5.0,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":6.5,"detection_enabled":true,"pid":599,"capture_pid":657,"ffmpeg_pid":666,"audio_rms":0.0,"audio_dBFS":0.0},"office":{"camera_fps":5.0,"process_fps":5.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":602,"capture_pid":661,"ffmpeg_pid":679,"audio_rms":0.0,"audio_dBFS":0.0},"birdcam":{"camera_fps":10.1,"process_fps":10.1,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":true,"pid":614,"capture_pid":665,"ffmpeg_pid":680,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"coral":{"inference_speed":8.21,"detection_start":0.0,"pid":557}},"detection_fps":12.8,"gpu_usages":{"intel-vaapi":{"gpu":"0.0%","mem":"-%","clients":{"640":"10.8%","666":"10.06%","679":"3.09%","680":"189.93%"}},"intel-qsv":{"gpu":"0.0%","mem":"-%","clients":{"640":"10.28%","666":"14.21%","679":"3.02%","680":"7.76%"}}},"cpu_usages":{"frigate.full_system":{"cpu":"34.6","mem":"9.2"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"85":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"89":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"90":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"98":{"cpu":"9.5","cpu_average":"9","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"106":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"3.8","cpu_average":"4","mem":"1.1","cmdline":"python3 -u -m frigate"},"124":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: master process nginx"},"172":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"173":{"cpu":"0.1","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"174":{"cpu":"0.1","cpu_average":"0","mem":"0.2","cmdline":"nginx: worker process"},"175":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: worker process"},"176":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"310":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"541":{"cpu":"18.6","cpu_average":"13","mem":"0.6","cmdline":"frigate.recording_manager"},"542":{"cpu":"0.7","cpu_average":"0","mem":"0.6","cmdline":"frigate.review_segment_manager"},"557":{"cpu":"5.0","cpu_average":"5","mem":"0.6","cmdline":"frigate.detector.coral"},"576":{"cpu":"2.4","cpu_average":"1","mem":"0.6","cmdline":"frigate.output       "},"581":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x360 -i pipe: -threads 1 -f mpegts -s 1408x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"597":{"cpu":"5.4","cpu_average":"7","mem":"0.6","cmdline":"frigate.process:front_left"},"598":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 704x360 -i pipe: -threads 1 -f mpegts -s 1408x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"599":{"cpu":"4.7","cpu_average":"2","mem":"0.6","cmdline":"frigate.process:walkway"},"602":{"cpu":"1.0","cpu_average":"0","mem":"0.6","cmdline":"frigate.process:office"},"614":{"cpu":"2.1","cpu_average":"4","mem":"0.7","cmdline":"frigate.process:birdcam"},"632":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:front_left"},"639":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"640":{"cpu":"2.0","cpu_average":"1","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_left_sub -r 5 -vf fps=5,scale_vaapi=w=704:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"649":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"650":{"cpu":"4.5","cpu_average":"4","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_left_rotated -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_left@%Y%m%d%H%M%S%z.mp4"},"657":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:walkway"},"659":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"661":{"cpu":"0.4","cpu_average":"0","mem":"0.6","cmdline":"frigate.capture:office"},"662":{"cpu":"537.0","cpu_average":"507","mem":"0.8","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:8554/front_left?video -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v superfast -tune:v zerolatency -pix_fmt:v yuv420p -an -vf transpose=1,transpose=1 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ebd1d3b7a0fc583830a3041f64d7bcb1"},"665":{"cpu":"1.6","cpu_average":"1","mem":"0.6","cmdline":"frigate.capture:birdcam"},"666":{"cpu":"1.9","cpu_average":"1","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/walkway_sub -r 5 -vf fps=5,scale_vaapi=w=704:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"679":{"cpu":"1.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/office_sub -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"680":{"cpu":"3.2","cpu_average":"3","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv -bsf:v dump_extra -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/birdcam_sub -r 10 -vf vpp_qsv=framerate=10:w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"685":{"cpu":"0.6","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/walkway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/walkway@%Y%m%d%H%M%S%z.mp4"},"686":{"cpu":"0.4","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/office -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/office@%Y%m%d%H%M%S%z.mp4"},"689":{"cpu":"0.4","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/birdcam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/birdcam@%Y%m%d%H%M%S%z.mp4"},"17479":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"17669":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":912,"version":"0.15.0-6cb5cfb","latest_version":"0.15.1","storage":{"/media/frigate/recordings":{"total":100220.9,"used":78687.1,"free":16397.8,"mount_type":"ext4"},"/media/frigate/clips":{"total":100220.9,"used":78687.1,"free":16397.8,"mount_type":"ext4"},"/tmp/cache":{"total":953.7,"used":111.7,"free":842.0,"mount_type":"tmpfs"},"/dev/shm":{"total":160.0,"used":79.7,"free":80.3,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1747628289},"processes":{"recording":{"pid":541},"review_segment":{"pid":542},"go2rtc":{"pid":98}}}
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Dahua IPC-T54IR-AS-6mm-S3

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/8f065322-34b0-474f-8157-0749ae8e0b7c)

![image](https://github.com/user-attachments/assets/5ccc0e6c-e730-42a9-bd82-595ecd6d906e)
