### DISCUSSION TITLE
[Config Support]: Unable to sync DB. Deleting X% of recordings DB entries, could be due to configuration error. Aborting...

### DISCUSSION THREAD

**Discussion by amosyuen** [blakeblackshear/frigate#18312] [Config Support] [answered]
### Describe the problem you are having

I changed my storage directory for recordings to a brand new disk and forgot to copy over the recordings. However, now frigate can't find the clips for past events.

I tried to clean it up by setting sync recordings in my frigate.yml, but the cleanup seems to fail with error message: `Deleting 0.912409% of recordings DB entries, could be due to configuration error. Aborting...` so how do I fix this?

I could go in UI and select all the recordings and delete, but there's no easy way to select all or multiple. Clicking through hundreds of recordings seems unideal. I guess I could just delete my frigate.db, but since I already have some new recordings on it, would prefer not to.

Unless I am missing something, perhaps we could do:
1. Have UI option to select multiple clips (shift+click slect to select between two clicks would be great)
2. Have an option to do the cleanup even if above the expected 0.5% storage check.

### Version

0.15-1

### Frigate config file

```yaml
record:
  enabled: true
  alerts:
    retain:
      days: 7
      mode: motion
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 7
      mode: motion
    pre_capture: 5
    post_capture: 5
  sync_recordings: true
```

### Relevant Frigate log output

```shell
info    | 2025-05-19 22:37:05 | frigate.record.util | Deleting 125 recording DB entries with missing files
warning | 2025-05-19 22:37:05 | frigate.record.util | Deleting 0.912409% of recordings DB entries, could be due to configuration error. Aborting...
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

OpenVino
