### DISCUSSION TITLE
[Config Support]: System (docker) crashes with Tapo C320WS when on stream 1 or high res

### DISCUSSION THREAD

**Discussion by Anto79-ops** [blakeblackshear/frigate#18317] [Config Support] [answered]
Hello,

I'm running docker frigate (0.15.0-6cb5cfb) on my Ubuntu 24.04 (AMD Ryzen 7) bare metal system using Coral TPU.

I have only 1 camera, the Tapo C320WS. It's hw 2 version with fw 1.2.2. 3rd party integration and camera account enabled. I updated FW the moment I got it ( maybe that was a mistake).

Here is my compose and config files:

docker compose: https://pastebin.com/gLaZ9WLT

config: https://pastebin.com/5KdKKPM1

At the moment, i have the camera set to 720p and config set to stream 2. If i increase the resolution to 1080p and/or change the config files to stream 1, the container crashes within 10 minutes, and this error repeats at 20 lines/second:

"Shed: Unable to read frames from ffmpeg process"

It makes my system so unstable, that i cannot stop or kill the container. I have to shutdown the computer and quickly stop the container before it gets into this unstable loop again.

Why is this happening? It works for several minutes and then loop crashes.

Is my config incorrect or so i have a hardware issue?

Any insight would be greatly appreciated

Thank you

**Comment by Anto79-ops** [comment]
updated yaml on 0.16.0 beta 2, still crashes when using the high res stream 1. Camera is set to output 720p output.

```
mqtt:
  host: 192.168.1.234 #Insert the IP address of your Home Assistant
  port: 1883 #Leave as default 1883 or change to match the port set in yout MQTT Broker configuration
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-core #Change to match the username set in your MQTT Broker
  password: password #Change to match the password set in your MQTT Broker
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://c241fae21de50ecf6c0f2a63769dcacd

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - face
    - dog
    - cat
    - mouse
    - bird
    - sports ball
    - rabbit

snapshots:
  enabled: true
  retain:
    default: 30

genai:
  enabled: true
  provider: ollama
  base_url: http://192.168.1.195:11434
  model: llava:7b

go2rtc:
  streams:
    shed:
      - ffmpeg:rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.1.150:554/stream2#input=rtsp/udp

cameras:
  shed:
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/shed
          roles:
            - detect
            - audio
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.281,0.144,0.273,0.26,0.336,0.266,0.345,0.15
        - 0.486,0.201,0.485,0.299,0.537,0.312,0.537,0.215
        - 0.813,0.871,0.812,0.895,0.838,0.916,0.853,0.907,0.981,0.792,0.995,0.733
    zones:
      Smokers:
        coordinates: 0.768,0.62,0.774,0.471,0.988,0.478,0.992,0.646
        loitering_time: 2
        inertia: 1
        filters:
          person:
            min_score: .50
            threshold: .65
            min_area: 200
            max_area: 1500
        objects: person
      North_Side_of_House:
        coordinates: 0.081,0.76,0.2,0.763,0.198,0.492,0.161,0.498,0.067,0.581
        loitering_time: 0
        objects:
          - person
          - cat
          - dog
        inertia: 3
      South_Side_of_House:
        coordinates: 0.564,0.686,0.612,0.688,0.609,0.529,0.566,0.52
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
      Grass:
        coordinates: 
          0.011,0.992,0.085,0.767,0.456,0.739,0.462,0.687,0.612,0.691,0.995,0.864,0.975,0.962,0.895,0.997
        loitering_time: 1
        objects:
          - person
          - dog
          - cat
          - mouse
          - sports ball
          - bird
        inertia: 1
    review:
      alerts:
        required_zones: Smokers
      detections:
        required_zones:
          - North_Side_of_House
          - South_Side_of_House
          - Grass
          - bbq
    genai:
      use_snapshot: true
      prompt: Analyze the {label} in these images from the {camera} security camera.
       Focus on the actions and potential intent of the {label}.
      object_prompts:
        person: Examine the person in these images. What are they doing, and how might
          their actions suggest their purpose (e.g., approaching, leaving)? 
      objects:
        - person
      required_zones:
        - steps

    objects:
      filters:
        person:
          mask:
            - 0.029,0.05,0,0.441,0.15,0.41,0.148,0.256,0.118,0.009
            - 0.213,0.084,0.196,0.323,0.585,0.364,0.593,0.167,0.486,0.004
            - 0.59,0.385,0.784,0.395,0.887,0.396,0.961,0.411,0.965,0.3,0.939,0.225,0.892,0.146,0.79,0.18,0.596,0.252
            - 0.266,0.456,0.387,0.464,0.388,0.622,0.263,0.627
      mask:
        - 0.213,0.084,0.196,0.323,0.585,0.364,0.593,0.167,0.486,0.004
        - 0.59,0.385,0.784,0.395,0.887,0.396,0.961,0.411,0.965,0.3,0.939,0.225,0.892,0.146,0.79,0.18,0.596,0.252
        - 0.451,0.463,0.538,0.467,0.536,0.589,0.449,0.59
version: 0.16-0

semantic_search:
  enabled: true
  reindex: false
  model_size: small
detect:
  enabled: true
  ```
