### DISCUSSION TITLE
[Camera Support]: Camera streams become unstable after turning on Frigate

### DISCUSSION THREAD

**Discussion by stewx** [blakeblackshear/frigate#18324] [Camera Support]
### Describe the problem you are having

I have 4 cameras made by TP-Link: 

1. C520WS
2. C120 x2 
3. D130 (doorbell cam)

With my Frigate container shut off, I can view the streams perfectly well through the TP-Link app without any performance issues.

When I turn the Frigate container on, there are severe issues streaming from the cameras. The streams are difficult to view in both Frigate and through the official TP-Link app.

### Version

 0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    driveway:
      - rtsp://frigate:frigate@192.168.4.200:554/stream1
      - ffmpeg:driveway
    doorbell:
      - rtsp://frigate:frigate@192.168.4.202:554/stream1
      - ffmpeg:doorbell
    backyard1:
      - rtsp://frigate:frigate@192.168.4.203:554/stream1
      - ffmpeg:backyard1
    backyard2:
      - rtsp://frigate:frigate@192.168.4.204:554/stream1
      - ffmpeg:backyard2


cameras:
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: false
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:frigate@192.168.4.201:554/live
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: false
  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: false
  backyard1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard1
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: false
  backyard2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard2
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: false


record:
  enabled: true
  retain:
    days: 10
    mode: all

version: 0.15-1
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### FFprobe output from your camera

```shell
Command did not work
```

### Operating system

UNRAID

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

See above

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/9bbc64c8-b46f-4102-84c6-ee5930723554)
