### DISCUSSION TITLE
[Config Support]:  faces are no longer recognized & no Sound at Recordings

### DISCUSSION THREAD

**Discussion by mbay0r** [blakeblackshear/frigate#18334] [Config Support] [answered]
### Describe the problem you are having

Hi,

Unfortunately, faces are no longer recognized with my current config, is it due to the model used?
I also have the problem that I have sound in the live view, but not in the recordings. :-(

Im using 0.16.0 Beta 2

Would someone be so kind and take a look at my config or maybe someone has an idea?

many thanks

### Version

0.16.0-1fa7ce5

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.178.92
  user: frigate
  password: XX
  port: 1883
  topic_prefix: frigate
  stats_interval: 60


objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7

detectors:
  hailo8:
    type: hailo8l
    device: PCIe

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: rgb
  input_dtype: int
  model_type: yolo-generic
  labelmap_path: /labelmap/coco-80.txt
  path: /config/yolov8m.hef

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 100

ffmpeg:
   hwaccel_args: preset-vaapi

go2rtc:
  streams:
    hoftor:
      - "ffmpeg:rtsp://view:XX@192.168.178.79:554/Streaming/Channels/101/#video=copy#audio=opus"
    hoftor_sub:
      - "ffmpeg:rtsp://view:XX@192.168.178.79:554/Streaming/Channels/102/#video=copy#audio=opus"
    parkplatz:
      - "rtsp://view:XX@192.168.178.25:554/Streaming/Channels/101/#video=1"
    parkplatz_sub:
      - "rtsp://view:XX@192.168.178.25:554/Streaming/Channels/102/#video=1"
  webrtc:
    candidates:
      - 192.168.178.160:8555
    ice_transport_policy: all


  api:
    listen: ":1984"
  rtsp:
    listen: ":8554"
  ws:
    listen: ":8555"


cameras:
  hoftor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: "rtsp://127.0.0.1:8554/hoftor"
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: "rtsp://127.0.0.1:8554/hoftor_sub"
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 640
      enabled: true
      annotation_offset: -200
    zones:
      zone_0:
        coordinates: 
          0.256,0.26,0.473,0.235,0.594,0.213,0.776,0.218,0.798,0.094,0.973,0.231,1,0.064,1,1,0.197,1,0,1,0.008,0,0.092,0.018,0.164,0.633,0.242,0.102
        inertia: 3
        objects: person
        loitering_time: 0
    mqtt:
      required_zones: [zone_0]
    snapshots:
      required_zones: [zone_0]
    review:
      detections:
        required_zones: zone_0
      alerts:
        required_zones: zone_0
    objects:
#      filters:
#        person: {}
      mask: 0.623,0.493,0.495,0.35,0.448,0.235,0.516,0.104,0.585,0.215,0.637,0.328
    motion:
      mask: 
        0.227,0.096,0.26,0.26,0.458,0.215,0.703,0.17,0.765,0.183,0.791,0.072,0.985,0.223,1,0,0.249,0,0.095,0,0.126,0.309
    live:
     streams:
      main_stream: hoftor
      sub_stream: hoftor_sub
  parkplatz:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/parkplatz
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/parkplatz_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 640
      enabled: true
      annotation_offset: -900
    zones:
      zone_0:
        coordinates: 
          0,1,0,0,0.502,0,0.51,0.132,0.322,0.142,0.334,0.447,0.534,0.394,0.63,0.392,0.782,0.533,0.81,0.646,0.928,0.639,1,0.787,1,1
        inertia: 3
        objects: person
        loitering_time: 0
    mqtt:
      required_zones: [zone_0]
    snapshots:
      required_zones: [zone_0]
    review:
      detections:
        required_zones: zone_0
      alerts:
        required_zones: zone_0
    motion:
      mask: 
        0.333,0.167,0.331,0.383,0.625,0.327,0.659,0.387,0.75,0.504,0.79,0.564,0.815,0.616,0.997,0.613,0.992,0.406,0.85,0.329,0.565,0.117
    objects:
      mask: 0.674,0.522,0.715,0.501,0.724,0.569,0.648,0.584
    live:
     streams:
      main_stream: parkplatz
      sub_stream: parkplatz_sub
telemetry:
  stats:
    intel_gpu_stats: true
detect:
  fps: 24
  enabled: true
version: 0.16-0

semantic_search:
  enabled: true
  model_size: large

face_recognition:
  enabled: true
  model_size: large
  unknown_score: 0.85
  recognition_threshold: 0.95


lpr:
  enabled: true

classification:
  bird:
    enabled: false
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### Operating system

UNRAID

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate1:
    container_name: frigate1
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2

    shm_size: "2048mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/hailo0:/dev/hailo0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nvme/docker/frigate:/config
      - /mnt/sata/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    networks:
      br0:
        ipv4_address: 192.168.178.160  # Statische IP im LAN
networks:
  br0:
    external: true  # Nutzt das bestehende Netzwerk
```

### Object Detector

Other

**Comment by hawkeye217** [comment]
MSE is the default live view type in Frigate with go2rtc configured for advanced live view. WebRTC will only be chosen if MSE fails. 

See the documentation: https://deploy-preview-16390--frigate-docs.netlify.app/configuration/live/#live-view-faq

**Reply by mbay0r** [reply]
haha, how stupid of me, I had even read the document. unfortunately I had overlooked it. thank you very much!

Any idea about face recognition?
I also have the problem that I have sound in the live view, but not in the recordings. :-(

**Reply by hawkeye217** [reply]
For audio in the recordings, see the docs:

https://deploy-preview-16390--frigate-docs.netlify.app/troubleshooting/faqs#audio-in-recordings

You may need to transcode your camera's audio to AAC.

**Reply by hawkeye217** [reply, marked as answer]
For face recognition, you've set your `unknown_score` and `recognition_threshold` differently than the defaults. I'd suggest removing these and running with the defaults first to see if that improves things for you.

**Reply by mbay0r** [reply]
Great, that's it. The face recognition works again, strange, maybe due to a change in the resolution.

thanks a lot !

As for the sound:

My camera actually delivers the sound in AAC, what surprises me is that it works in the livestream but not in the recordings or is that normal behavior?

**Reply by mbay0r** [reply]
output_args:
    record: preset-record-generic-audio-aac

I have now set it, but now I often have a hammering in the sound and unfortunately still nothing in the recordings, should I still throw out audio=opus?

**Reply by hawkeye217** [reply]
> My camera actually delivers the sound in AAC, what surprises me is that it works in the livestream but not in the recordings or is that normal behavior?

In your go2rtc config, you are transcoding the audio to `opus` in two of your cameras. In the other two, you are only providing video. 

See the documentation: https://deploy-preview-16390--frigate-docs.netlify.app/guides/configuring_go2rtc

If you're providing AAC already, then I would just provide opus in a separate stream:

```
go2rtc:
  streams:
    hoftor:
      - "ffmpeg:rtsp://view:XX@192.168.178.79:554/Streaming/Channels/101/"
      - ffmpeg:hoftor#audio=opus
    hoftor_sub:
      - "ffmpeg:rtsp://view:XX@192.168.178.79:554/Streaming/Channels/102/"
    parkplatz:
      - "rtsp://view:XX@192.168.178.25:554/Streaming/Channels/101/"
    parkplatz_sub:
      - "rtsp://view:XX@192.168.178.25:554/Streaming/Channels/102/"
```

**Reply by mbay0r** [reply]
thanks a lot, seems to work !

**Reply by hawkeye217** [reply]
Great. Happy to help.

**Comment by mbay0r** [comment]
Hi @hawkeye217 

could you perhaps take another look at my config? I'm getting desperate. Everything is working fine now. People are recognized and cars too, everything is fine.

But unfortunately once again no faces are recognized, no matter what I do. Maybe I'm just on the wrong end of the stick.

Thank you very much




```
mqtt:
  enabled: true
  host: 192.168.178.92
  user: frigate
  password: XX
  port: 1883
  topic_prefix: frigate
  stats_interval: 60


objects:
  track:
    - person
    - car 
    - motorcycle
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7

#detectors:
#  coral:
#    type: edgetpu
#    device: usb


detectors:
  hailo8:
    type: hailo8l
    device: PCIe

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: rgb
  input_dtype: int
  model_type: yolo-generic
  labelmap_path: /labelmap/coco-80.txt
  path: /config/yolov8m.hef

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 100

ffmpeg:
  hwaccel_args: preset-vaapi
#   output_args:
#    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    hoftor:
      #- "ffmpeg:rtsp://view:XX@192.168.178.79:554/Streaming/Channels/101/#video=copy#audio=aac"      
      - rtsp://view:XX@192.168.178.79:554/Streaming/Channels/101/
      #  - "ffmpeg:hoftor#audio=aac"
    hoftor_sub:
      - rtsp://view:XX@192.168.178.79:554/Streaming/Channels/102/#video=1
    parkplatz:
      - rtsp://view:XX@192.168.178.25:554/Streaming/Channels/101/#video=1
    parkplatz_sub:
      - rtsp://view:XX@192.168.178.25:554/Streaming/Channels/102/#video=1
  webrtc:
    candidates:
      - 192.168.178.160:8555
    ice_transport_policy: all


#  api:
#    listen: :1984
#  rtsp:
#    listen: :8554
#  ws:
#    listen: :8555


cameras:
  hoftor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy # preset-record-generic-audio-copy preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/hoftor
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/hoftor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 640
      enabled: true
      annotation_offset: -200
      fps: 25
    zones:
      zone_0:
        coordinates: 
          0.256,0.26,0.473,0.235,0.594,0.213,0.776,0.218,0.798,0.094,0.973,0.231,1,0.064,1,1,0.197,1,0,1,0.008,0,0.092,0.018,0.164,0.633,0.242,0.102
        inertia: 3
        objects: person
        loitering_time: 0
    mqtt:
      required_zones: [zone_0]
    snapshots:
      required_zones: [zone_0]
    review:
      detections:
        required_zones: zone_0
      alerts:
        required_zones: zone_0
    objects:
      mask: 0.623,0.493,0.495,0.35,0.448,0.235,0.516,0.104,0.585,0.215,0.637,0.328
    motion:
      mask: 
        0.227,0.096,0.26,0.26,0.458,0.215,0.703,0.17,0.765,0.183,0.791,0.072,0.985,0.223,1,0,0.249,0,0.095,0,0.126,0.309
    live:
      streams:
        main_stream: hoftor
        sub_stream: hoftor_sub
  parkplatz:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/parkplatz
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/parkplatz_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 640
      enabled: true
      annotation_offset: -100
      fps: 25
    zones:
      zone_0:
        coordinates: 
          0,1,0,0,0.502,0,0.51,0.132,0.322,0.142,0.334,0.447,0.534,0.394,0.63,0.392,0.782,0.533,0.81,0.646,0.928,0.639,1,0.787,1,1
        inertia: 3
        objects: person

        loitering_time: 0
    mqtt:
      required_zones: [zone_0]
    snapshots:
      required_zones: [zone_0]
    review:
      detections:
        required_zones: zone_0
      alerts:
        required_zones: zone_0
    motion:
      mask: 
        0.333,0.167,0.331,0.383,0.625,0.327,0.659,0.387,0.75,0.504,0.79,0.564,0.815,0.616,0.997,0.613,0.992,0.406,0.85,0.329,0.565,0.117
    objects:
      mask: 0.674,0.522,0.715,0.501,0.724,0.569,0.648,0.584
    live:
      streams:
        main_stream: parkplatz
        sub_stream: parkplatz_sub
telemetry:
  stats:
    intel_gpu_stats: true
detect:
  fps: 25
  enabled: true

semantic_search:
  enabled: true
  model_size: large

face_recognition:
  enabled: true
  model_size: large

lpr:
  enabled: true
  device: GPU
  model_size: large
  format: "^[A-Z]{1,3} [A-Z]{1,2} [0-9]{1,4}$"
  debug_save_plates: true
  min_plate_length: 4 # Only recognize plates with 4 or more characters


classification:
  bird:
    enabled: false
version: 0.16-0
```

**Reply by hawkeye217** [reply]
You've set the `detect` width and height to 640x640. Is your camera's substream really a square aspect ratio? This is likely your issue. 

Also, your detect `fps` is set very high. It does not need to match the output of your camera. 5 is the recommend value. 

https://deploy-preview-16390--frigate-docs.netlify.app/frigate/camera_setup

**Reply by mbay0r** [reply]
> You've set the `detect` width and height to 640x640. Is your camera's substream really a square aspect ratio? This is likely your issue.
> 
> Also, your detect `fps` is set very high. It does not need to match the output of your camera. 5 is the recommend value.
> 
> https://deploy-preview-16390--frigate-docs.netlify.app/frigate/camera_setup

The substream can only be 1280*720, or 640x480. I have therefore selected 1280x720, shouldn't frigate or ffmpeg then calculate this down to 480x480? Otherwise I could select 640x480, but then of course the quality would suffer and the image would be too small. What can or should I do?

I have now set 5 FPS, but unfortunately it doesn't help. My hardware is actually powerful enough for 25 FPS.

Is there perhaps a bug somewhere?

Thanks!

**Reply by NickM-27** [reply]
>  shouldn't frigate or ffmpeg then calculate this down to 480x480?

no, nothing should ever be running as a square unless your camera has a square resolution stream, you should not be overriding the detect resolution

**Reply by hawkeye217** [reply]
> The substream can only be 1280*720, or 640x480. I have therefore selected 1280x720,

Set your detect width and height to 
```
detect:
  width: 1280
  height: 720
  fps: 5
```

Running higher than 5fps is unnecessary for normal setups. If you are trying to track *extremely* fast moving objects, 10fps is the recommendation. There are no performance gains for values higher than that - you are just putting undue pressure on Frigate's object detection pipeline.

**Comment by mbay0r** [comment]
Thank you both! I have now implemented this as recommended, but unfortunately still nothing. :-(

Here is the current config. No success with FPS5 either

The Hail8 and yolov8m work wonderfully and recognize people and cars

```
mqtt:
  enabled: true
  host: 192.168.178.92
  user: frigate
  password: XX
  port: 1883
  topic_prefix: frigate
  stats_interval: 60


objects:
  track:
    - person
    - car 
    - motorcycle
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7

#detectors:
#  coral:
#    type: edgetpu
#    device: usb


detectors:
  hailo8:
    type: hailo8l
    device: PCIe

model:
  width: 640
  height: 640
  input_tensor: nhwc
  input_pixel_format: rgb
  input_dtype: int
  model_type: yolo-generic
  labelmap_path: /labelmap/coco-80.txt
  path: /config/yolov8m.hef

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 100

ffmpeg:
  hwaccel_args: preset-vaapi
#   output_args:
#    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    hoftor:
      #- "ffmpeg:rtsp://view:XX@192.168.178.79:554/Streaming/Channels/101/#video=copy#audio=aac"      
      - rtsp://view:XX@192.168.178.79:554/Streaming/Channels/101/
      #  - "ffmpeg:hoftor#audio=aac"
    hoftor_sub:
      - rtsp://view:XX@192.168.178.79:554/Streaming/Channels/102/#video=1
    parkplatz:
      - rtsp://view:XX@192.168.178.25:554/Streaming/Channels/101/#video=1
    parkplatz_sub:
      - rtsp://view:XX@192.168.178.25:554/Streaming/Channels/102/#video=1
  webrtc:
    candidates:
      - 192.168.178.160:8555
    ice_transport_policy: all


#  api:
#    listen: :1984
#  rtsp:
#    listen: :8554
#  ws:
#    listen: :8555


cameras:
  hoftor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy # preset-record-generic-audio-copy preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/hoftor
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/hoftor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      enabled: true
      annotation_offset: -200
      fps: 10
    zones:
      zone_0:
        coordinates: 
          0.256,0.26,0.473,0.235,0.594,0.213,0.776,0.218,0.798,0.094,0.973,0.231,1,0.064,1,1,0.197,1,0,1,0.008,0,0.092,0.018,0.164,0.633,0.242,0.102
        inertia: 3
        objects: person
        loitering_time: 0
    mqtt:
      required_zones: [zone_0]
    snapshots:
      required_zones: [zone_0]
    review:
      detections:
        required_zones: zone_0
      alerts:
        required_zones: zone_0
    objects:
      mask: 0.623,0.493,0.495,0.35,0.448,0.235,0.516,0.104,0.585,0.215,0.637,0.328
    motion:
      mask: 
        0.227,0.096,0.26,0.26,0.458,0.215,0.703,0.17,0.765,0.183,0.791,0.072,0.985,0.223,1,0,0.249,0,0.095,0,0.126,0.309
    live:
      streams:
        main_stream: hoftor
        sub_stream: hoftor_sub
  parkplatz:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/parkplatz
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/parkplatz_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      enabled: true
      annotation_offset: -100
      fps: 10
    zones:
      zone_0:
        coordinates: 
          0,1,0,0,0.502,0,0.51,0.132,0.322,0.142,0.334,0.447,0.534,0.394,0.63,0.392,0.782,0.533,0.81,0.646,0.928,0.639,1,0.787,1,1
        inertia: 3
        objects: person

        loitering_time: 0
    mqtt:
      required_zones: [zone_0]
    snapshots:
      required_zones: [zone_0]
    review:
      detections:
        required_zones: zone_0
      alerts:
        required_zones: zone_0
    motion:
      mask: 
        0.333,0.167,0.331,0.383,0.625,0.327,0.659,0.387,0.75,0.504,0.79,0.564,0.815,0.616,0.997,0.613,0.992,0.406,0.85,0.329,0.565,0.117
    objects:
      mask: 0.674,0.522,0.715,0.501,0.724,0.569,0.648,0.584
    live:
      streams:
        main_stream: parkplatz
        sub_stream: parkplatz_sub
telemetry:
  stats:
    intel_gpu_stats: true
#detect:
#  enabled: true

semantic_search:
  enabled: true
  model_size: large

face_recognition:
  enabled: true
  model_size: large

lpr:
  enabled: true
  device: GPU
  model_size: large
  format: "^[A-Z]{1,3} [A-Z]{1,2} [0-9]{1,4}$"
  debug_save_plates: true
  min_plate_length: 4 # Only recognize plates with 4 or more characters


classification:
  bird:
    enabled: false
version: 0.16-0

```

**Reply by hawkeye217** [reply]
Everything looks fine in your config. Where are you looking for faces to be detected?

Just to be sure, you've trained a face according to the documentation, right? https://deploy-preview-16390--frigate-docs.netlify.app/configuration/face_recognition/#usage

It should be noted that the default `min_area` for a face is 500px, which is about a 22px x 22px square in your camera image. What camera are you looking for faces on?

**Reply by mbay0r** [reply]
Thank you, I'm looking for a face on both cameras. At least that's how I configured it? I have added a person with a picture of me. Now when I walk through the camera or someone else new recognized faces should show up under /faces? At least that's how it used to work. But not anymore.

![image](https://github.com/user-attachments/assets/1dac4390-ca6b-4e2c-8e77-8567e52db2f2)

**Reply by hawkeye217** [reply]
Are you still seeing `person` detections?

**Reply by mbay0r** [reply]
> Are you still seeing `person` detections?

Yes

![image](https://github.com/user-attachments/assets/fba4633b-5842-407f-b67b-fee3930b0392)

**Reply by hawkeye217** [reply]
I'd start by lowering your `detection_threshold` score then:

https://deploy-preview-16390--frigate-docs.netlify.app/configuration/face_recognition/#detection

**Reply by mbay0r** [reply]
i have now set recognition_threshold: 0.5, unfortunately no real improvement.
Should I go even lower?

Is the resolution of the substream perhaps too low?

**Reply by NickM-27** [reply]
Detection threshold is what you care about, not recognition

**Reply by mbay0r** [reply]
> recognition

I'm a fool, thank you 😂

**Reply by mbay0r** [reply]
ok I have now set it as follows, so it works quite well. Thank you both very much.

But why do I have to go so deep? Is it because of the low resolution of the substream?

```
face_recognition:
  enabled: true
  model_size: large
  detection_threshold: 0.2
  min_area: 400
```

**Reply by NickM-27** [reply]
potentially, or the angle of a face

**Reply by mbay0r** [reply]
Can I go even higher with the resolution or is that rather bad?

For example, the substream of the cam parkplatz can only be 

 width: 640
 height: 480

in the substream, but the camera is very far away, can I use the main stream with 3840x2160 or is that not recommended?

If such a resolution is generally OK, I could do without the substream completely.

**Reply by hawkeye217** [reply]
You could try using the main stream and scale it down with:

```
detect:
  width: 1920
  height: 1080
  fps: 5
```

This uses more resources than an already-scaled substream, but still would use significantly less resources than if you did not scale it.
