### DISCUSSION TITLE
[Detector Support]:

### DISCUSSION THREAD

**Discussion by basvdl** [blakeblackshear/frigate#18344] [Detector Support]
### Describe the problem you are having

I'm trying to understand why the 4th car in the object list is being included. The area falls within the defined range, but the ratio is outside the specified bounds. Based on that, I would expect it not to be added to the object list.

Here are the current settings:

```
min_ratio: 1
max_ratio: 1.8
min_area: 3500
max_area: 56000
min_score: 0.5
threshold: 0.6
```

To determine these values, I used the screenshot below and manually drew bounding boxes in Photoshop to measure the width and height in pixels.

<img width="778" alt="image" src="https://github.com/user-attachments/assets/0ff47881-be76-42f7-9ff7-251dd1963951" />

### Version

0.15.1

### Frigate config file

```yaml
mqtt:
    enabled: true
    host: 192.168.50.156
    port: 1883
    topic_prefix: frigate
    stats_interval: 60
  
  detectors:
    coral:
      type: edgetpu
      device: usb
  
  model:
    # Base model
    path: plus://c241fae21de50ecf6c0f2a63769dcacd
  
  tls:
    enabled: false
  
  auth:
    enabled: true
  
  audio:
    enabled: false
  
  logger:
    default: info
    logs:
      frigate.event: info
  
  environment_vars:
    LIBVA_DRIVER_NAME: i965 # iHD
  
  birdseye:
    enabled: false
  
  # More information about presets at https://docs.frigate.video/configuration/ffmpeg_presets
  ffmpeg:
    global_args: -hide_banner -loglevel warning -threads 2
    hwaccel_args: preset-vaapi # preset-vaapi, preset-intel-qsv-h264, preset-intel-qsv-h265
    input_args: preset-rtsp-generic
    output_args:
      detect: -threads 2 -f rawvideo -pix_fmt yuv420p
      record: preset-record-generic
  
  detect:
    enabled: true
    # width: 640
    # height: 360
    # to keep the aspect ratio, you need 854x480 or 720x480
    width: 854
    height: 480
    # Optional: desired fps for your camera for the input with the detect role (default: shown below)
    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
    fps: 5
    # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
    min_initialized: 3
    # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
    max_disappeared: 35
    stationary:
      # Optional: Frequency for confirming stationary objects (default: same as threshold)
      # When set to 1, object detection will run to confirm the object still exists on every frame.
      # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
      interval: 50
      # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
      threshold: 25
  
  objects:
    track:
      - person
      - car
      - bicycle
  
  review:
    alerts:
      labels:
        - car
        - person
        - bicycle
    detections:
      labels:
        - car
        - person
        - bicycle
  
  motion:
    enabled: true
    # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
    # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
    # The value should be between 1 and 255.
    threshold: 30
    # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
    #           needs to recalibrate. (default: shown below)
    # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
    # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
    # a doorbell camera.
    lightning_threshold: 0.8
    # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
    # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
    # make motion detection more sensitive to smaller moving objects.
    # As a rule of thumb:
    #  - 10 - high sensitivity
    #  - 30 - medium sensitivity
    #  - 50 - low sensitivity
    contour_area: 10
    # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
    # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
    # Low values will cause things like moving shadows to be detected as motion for longer.
    # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
    frame_alpha: 0.01
    # Optional: Height of the resized motion frame  (default: 100)
    # Higher values will result in more granular motion detection at the expense of higher CPU usage.
    # Lower values result in less CPU, but small changes may not register as motion.
    frame_height: 100
    improve_contrast: true
    # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
    mqtt_off_delay: 30
  
  notifications:
    enabled: false
  
  record:
    enabled: true
    # Optional: Number of minutes to wait between cleanup runs (default: shown below)
    # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
    expire_interval: 60
    sync_recordings: false
    retain:
      days: 7
      # Optional: Mode for retention. Available options are: all, motion, and active_objects
      #   all - save all recording segments regardless of activity
      #   motion - save all recordings segments with any detected motion
      #   active_objects - save all recording segments with active/moving objects
      mode: all
    preview:
      # Options are: very_low, low, medium, high, very_high
      quality: medium
    alerts:
      pre_capture: 10
      post_capture: 10
      retain:
        days: 14
        # Optional: Mode for retention. (default: shown below)
        #   all - save all recording segments for alerts regardless of activity
        #   motion - save all recordings segments for alerts with any detected motion
        #   active_objects - save all recording segments for alerts with active/moving objects
        mode: motion
    detections:
      pre_capture: 10
      post_capture: 10
      retain:
        days: 14
        # Optional: Mode for retention. (default: shown below)
        #   all - save all recording segments for detections regardless of activity
        #   motion - save all recordings segments for detections with any detected motion
        #   active_objects - save all recording segments for detections with active/moving objects
        mode: motion
  
  snapshots:
    enabled: true
    clean_copy: true
    timestamp: true
    bounding_box: true
    crop: false
    required_zones: []
    retain:
      default: 14
    quality: 70
  
  semantic_search:
    enabled: true
  
    reindex: false
    model_size: small
  genai:
    enabled: false
  
  go2rtc:
    streams:
      demo:
        - rtsp://admin:***@192.168.50.218:554/h264Preview_01_main
      demo_detect:
        - ffmpeg:rtsp://127.0.0.1:8554/demo#video=h264#hardware=vaapi#width=854#height=480#raw=-r 5
      demo2:
        - rtsp://admin:***@192.168.50.30:554/h264Preview_01_main
      demo2_low:
        - rtsp://admin:***@192.168.50.30:554/h264Preview_01_sub
  
  cameras:
    demo:
      enabled: true
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/demo
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/demo_detect
            roles:
              - detect
      live:
        stream_name: demo
      motion:
        mask:
          - 0.291,0.992,0.673,0.992,0.673,0.934,0.291,0.934
          - 0.932,0,1,0,1,0.196
        threshold: 30
        contour_area: 10
        improve_contrast: true
      zones:
        Parking_1:
          coordinates: 0.033,0.283,0.433,0.054,0.942,0.039,1,0.203,0.07,0.884
          loitering_time: 3
          objects: car
          inertia: 3
          filters:
            car:
              min_ratio: 1
              max_ratio: 1.8
              min_area: 3500
              max_area: 56000
              min_score: 0.5
              threshold: 0.6
      review:
        alerts:
          required_zones: Parking_1
        detections:
          required_zones: Parking_1
      objects: {}
    demo2:
      enabled: true
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/demo2
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/demo2_low
            roles:
              - detect
      live:
        stream_name: demo2
      motion:
        mask:
          - 0.297,0.972,0.679,0.972,0.679,0.914,0.297,0.914
          - 0.448,0.148,0.576,0.181,0.547,0.492,0.429,0.43
          - 0.625,0.176,0.566,0.661,0.745,0.779,0.823,0.258
        threshold: 30
        contour_area: 10
        improve_contrast: true
  
  version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    cap_add:
      - CAP_PERFMON
    shm_size: "128MB"
    devices:
      - /dev/dri
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - /var/cold/frigate/config:/config
      - /var/cold/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp

    environment:
      FRIGATE_RTSP_PASSWORD: "***"
      # LIBVA_DRIVER_NAME: "iHD"
      LIBVA_DRIVER_NAME: "i965"
      PLUS_API_KEY: ***
```

### Relevant Frigate log output

```shell
No logs captured
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b1e30db0-922a-4352-acd2-f3eccec9dc8b)
