### DISCUSSION TITLE
[Config Support]: Repeatedly detecting the same license plate

### DISCUSSION THREAD

**Discussion by mabnz** [blakeblackshear/frigate#18345] [Config Support] [answered]
### Describe the problem you are having

I'm using 0.16 beta2, and clearly I need to tune it more as it keeps detecting the plate over and over. What do I need to tweak in order for the same plate not to be detected constantly?

The camera in question I've assigned to be LPR-only, and has a 1/1000th shutter (so it detects plates very well, but is under-exposed during the day). I'm using a Frigate+ trained model.

From my brief reading, there seems to be a large number of configuration options which all work together to create a well-oiled detection framework. However, it seems to be overly complex to understand.

Is the problem here motion tuning, object thresholds, min detection, something else entirely?

<img width="1282" alt="Screenshot 2025-05-22 at 7 24 49 AM" src="https://github.com/user-attachments/assets/8552eea8-e032-42dd-9934-be8c260b1371" />

### Version

0.16beta2

### Frigate config file

```yaml
lprcam:
    enabled: true
    type: lpr
    lpr:
      enabled: true
      enhancement: 3 
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h265
      inputs:    
        - path: rtsp://127.0.0.1:8554/garage2-rec
          roles:
            - record
            - detect
      
    review:
      alerts:
        labels: []

    objects:
      track:
        - license_plate
      filters:
        license_plate:
          threshold: 0.7 
           
    zones: {}
    detect:
      enabled: true 
      width: 3072
      height: 1728
      fps: 8
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral
