### DISCUSSION TITLE
[Detector Support]: ONNX detectors on Jetson Orin NX

### DISCUSSION THREAD

**Discussion by zeroflow** [blakeblackshear/frigate#18368] [Detector Support] [answered]
### Describe the problem you are having

When running a tensorrt detector (yolov7x-640), everything works as expected. The model is running on the GPU with ~35ms detection speed.

But when changing the detector to run an ONNX model, it's running on the CPU. Regarding to the [Documentation](https://deploy-preview-16390--frigate-docs.netlify.app/configuration/object_detectors), ONNX models should automatically use TensorRT on Jetson devices.

### Version

0.16.0-5c3ac75

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.4.11

ffmpeg:
  hwaccel_args: preset-jetson-h264

detectors:
  onnx:
    type: onnx

model:
  model_type: yolox
  width: 640 
  height: 640
  input_tensor: nchw
  input_dtype: float_denorm
  path: /config/model_cache/yolox_x.onnx
  labelmap_path: /labelmap/coco-80.txt

cameras:
  Terrasse_Garage: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Terrasse_Garage
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.26
      port: 2020
      user: <removed>
      password: <removed>
    detect:
      enabled: true
    objects:
      filters:
        car:
          min_area: 50000
      mask: 0,0,0.549,0,0.522,0.079,0.071,0.467,0,0.446
    notifications:
      enabled: true
    zones:
      Main:
        coordinates: 0.067,0.471,0.531,0.071,1,0.204,1,1,0.455,1
        loitering_time: 0
    motion:
      threshold: 30
      contour_area: 5
      improve_contrast: true
  Terrasse: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Terrasse
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.27
      port: 2020
      user: <removed>
      password: <removed>
    detect:
      enabled: true
    notifications:
      enabled: true
    zones:
      Main:
        coordinates: 0.001,0.295,0.317,0.154,1,0.228,1,1,0,1
        loitering_time: 0
        inertia: 3
  Eingang: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.25
      port: 2020
      user: <removed>
      password: <removed>

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Main:
        coordinates: 0,0.28,0.281,0.117,0.689,0.136,1,0.222,1,1,0,1
        loitering_time: 0
        inertia: 3
      Strasse:
        coordinates: 0,0,1,0,1,0.201,0,0.19
        loitering_time: 0
        speed_threshold: 10
        distances: 53,4,53,4
        inertia: 3
    notifications:
      enabled: true
    objects:
      mask: 0,0,1,0,1,0.222,0.673,0.135,0.28,0.118,0,0.28
    review:
      alerts:
        required_zones: Main
      detections:
        required_zones: Main
  Einfahrt: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Einfahrt
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.23
      port: 2020
      user: <removed>
      password: <removed>
    detect:
      enabled: true
    notifications:
      enabled: true
    zones:
      Main:
        coordinates: 0,0.251,0.329,0.113,0.533,0,1,0,1,1,0,1
        loitering_time: 0
  Wohnzimmer: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Wohnzimmer
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.20
      port: 2020
      user: <removed>
      password: <removed>
    record: # Don't keep constant recordings
      retain:
        days: 0
    detect:
      enabled: true
    notifications:
      enabled: true
    zones:
      Main:
        coordinates: 0,0.158,1,0.143,1,1,0,1
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  Keller: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Keller
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.21
      port: 2020
      user: <removed>
      password: <removed>
    record: # Don't keep constant recordings
      retain:
        days: 0
    detect:
      enabled: true
    notifications:
      enabled: true
    zones:
      Main:
        coordinates: 0,0.196,1,0.202,1,1,0,1
        loitering_time: 0
        inertia: 3
  Garage: # --------------------------------------------------
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          input_args: preset-rtsp-restream
          roles:
            - detect
    onvif:
      host: 192.168.5.22
      port: 2020
      user: <removed>
      password: <removed>
    record: # Don't keep constant recordings
      retain:
        days: 0
    detect:
      enabled: true
    notifications:
      enabled: true
    objects:
      mask: 0,0.573,0.405,0.578,0.405,0.578,0.323,1,0,1
    zones:
      Main:
        coordinates: 0.394,0,1,0,1,1,0.319,1,0.405,0.578
        loitering_time: 0

# ---------------
# go2rtc restream
# ---------------
go2rtc:
  streams:
    Terrasse_Garage: rtsp://<removed>@192.168.5.26:554/stream1
    Terrasse: rtsp://<removed>@192.168.5.27:554/stream1
    Eingang: rtsp://<removed>@192.168.5.25:554/stream1
    Einfahrt: rtsp://<removed>@192.168.5.23:554/stream1
    Wohnzimmer: rtsp://<removed>@192.168.5.20:554/stream1
    Keller: rtsp://<removed>@192.168.5.21:554/stream1
    Garage: rtsp://<removed>@192.168.5.22:554/stream1

# -----------------------
# General Motion Settings
# -----------------------
motion:
  mask: 0,0,0.365,0,0.365,0.05,0,0.05 # Timestamps

# # ----------------------
# # Detector Settings / AI
# # ----------------------
# detect:
#   enabled: true
#   stationary:
#     interval: 50
#     threshold: 50

# # Settings for TensorRT (known good)
# detectors:
#   tensorrt:
#     type: tensorrt
#     device: 0

# model:
#   path: /config/model_cache/tensorrt/yolov7x-640.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 640
#   height: 640
# #-------------------

objects:
  track:
    - car
    - bus
    - person
    - bicycle
    - motorcycle
    - cat
    - dog
    - bird
    - horse

  filters:
    person:
      threshold: 0.85
      min_area: 10000
    car:
      threshold: 0.8
      min_area: 10000
    bus:
      threshold: 0.8
      min_area: 10000
    bicycle:
      min_area: 10000

# Optional: Configuration for semantic search capability
semantic_search:
  # Optional: Enable semantic search (default: shown below)
  enabled: false
  # Optional: Re-index embeddings database from historical tracked objects (default: shown below)
  reindex: false
  # Optional: Set the model size used for embeddings. (default: shown below)
  # NOTE: small model runs on CPU and large model runs on GPU
  model_size: large

# ---------------------
# Recording & Snapshots
# ---------------------

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 62
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 62
      mode: active_objects

snapshots:
  enabled: true
  bounding_box: true

# ------
# Review
# ------
review:
  alerts:
    labels:
      - car
      - bus
      - person
    #  - bicycle
      - motorcycle
    required_zones:
      - Main
  detections:
    labels:
      - car
      - bus
      - motorcycle
      - bicycle
      - person
      - cat
      - dog
      - bird
      - horse
    #required_zones:
    #  - Main

version: 0.16-0

# -------------
# Camera Groups
# -------------

camera_groups:
  Outdoor:
    order: 1
    icon: LuTrees
    cameras:
      - Terrasse_Garage
      - Terrasse
      - Eingang
      - Einfahrt
  Einfahrt:
    order: 2
    icon: LuCar
    cameras:
      - Terrasse_Garage
      - Eingang
notifications:
  enabled: true
  email: <removed>
```

### docker-compose file or Docker CLI command

```yaml
version: '2.4'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta1-tensorrt-jp6
    shm_size: "2048mb" # 920MB in use
    runtime: nvidia 
    volumes:
      - /var/frigate/config:/config
      - /var/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
      - /etc/localtime:/etc/localtime:ro
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
    ports:
      - "1984:1984" # go2rtc
      - "8971:8971" # HTTPS port
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      YOLO_MODELS: "yolov7x-640,yolov7x-640-dla"
      USE_FP16: true
      PLUS_API_KEY: "<removed>"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```

### Relevant Frigate log output

```shell
info | 2025-05-23 18:30:53 | detector.onnx                  | Starting detection process: 686
info | 2025-05-23 18:30:53 | frigate.app                    | Output process started: 712
info | 2025-05-23 18:30:53 | frigate.detectors.plugins.onnx | ONNX: loaded onnxruntime module
info | 2025-05-23 18:30:53 | frigate.detectors.plugins.onnx | ONNX: loading /config/model_cache/yolox_x.onnx
info | 2025-05-23 18:30:54 | frigate.detectors.plugins.onnx | ONNX: /config/model_cache/yolox_x.onnx loaded
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![system metrics general](https://github.com/user-attachments/assets/0339ab92-5bff-4800-abb2-df159c0cae93)

![system metrics cameras](https://github.com/user-attachments/assets/a179e1f0-58aa-4dc0-8b95-c34ea5b7eeda)

### Any other information that may be helpful

I have tried different onnx models (selfmade from ultralytics, yolox, ...) but none run on GPU.

If it helps, I have a second Jetson Xavier NX which I could provide remotely in an isolated network for running tests or for access of the devs if none are available locally. Not sure if this is an option, but remote access could be provided.

Device:
Orin NX 16 GB
Jetpack 6.2 / L4T 36.4.3
