### DISCUSSION TITLE
HA crashes after reading recorded video when plate or and face recognition is activated:

### DISCUSSION THREAD

**Discussion by chris669** [blakeblackshear/frigate#18376] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

HA crashes after reading recorded video when plate or and face recognition is activated. 

### Steps to reproduce

1. Update to latest version 
2. Activate plate recognition and or face recognition 
3. Try to visualize a video recorded
4. The wait symbol appears but HA is restarting 
5. I have to say that I was able to run successfully plate and face recognition, but when I try to run a video, it crashes. I'm not running go2rtc
6. When I desactivate both face and plate detection, after reboot, I can read a recorded video

### Version

0.16.0-1fa7ce5

### In which browser(s) are you experiencing the issue with?

Chrome 136.0.7103.125 with mobile, it also crash on my desktop but no access now 

### Frigate config file

```yaml
mqtt:
  host: myhost
  user: myadmin
  password: 123456'

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  cpu1:
    type: cpu
    num_threads: 2

#go2rtc:
#  streams:
#    cam_nord:
#      - rtsp://onvifuser:mylogin@camip/stream0
genai:
  enabled: true
  provider: gemini
  api_key: myapikey
  model: gemini-1.5-flash
cameras:
  cam_nord:
    ffmpeg:
      # output_args:
      #  record: preset-record-generic
      inputs:
        - path: rtsp://onvifuser:mypassword @camip/stream0 # <--- the name here must match the name of the camera in restream
        #- path: rtsp://127.0.0.1:18554/cam_nord 
          roles:
            - record
            - detect
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
        - cat
        - dog
    detect:
      width: 720
      height: 480
      fps: 10

      stationary:
        interval: 50
        threshold: 50
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - frontdoor_west
        - frontdoor_east
    zones:
      frontdoor_east:
        coordinates: 1,0.217,1,0.909,0.731,0.911,0.731,1,0.511,1,0.516,0.256
        objects:
          - person
          - car
          - motorcycle
          - bicycle
          - cat
          - dog
        inertia: 3
        loitering_time: 0
      frontdoor_west:
        coordinates: 
          0,1,0,0.171,0.038,0.172,0.091,0.292,0.343,0.263,0.339,0.054,0.382,0.052,0.382,0.259,0.508,0.257,0.506,1
        objects:
          - person
          - cat
        inertia: 3
        loitering_time: 0
    motion:
      improve_contrast: 'true'
      mask: 
        1,0,1,0.21,0.387,0.257,0.387,0.042,0.334,0.046,0.338,0.26,0.097,0.284,0.039,0.161,0,0.164,0,0
      threshold: 35
      contour_area: 10
    review:
      alerts:
        required_zones:
          - frontdoor_west
          - frontdoor_east
      detections:
        required_zones:
          - frontdoor_east
          - frontdoor_west

  cam_sud:
    ffmpeg:
      inputs:
        - path: rtsp://camlogin:campassword@camip:554/11
          roles:
            - detect
        - path: rtsp://camlogin:campassword@camip:554/11
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - cat
    detect:
      width: 720
      height: 480
      fps: 10
    record:
      enabled: true
    snapshots:
      enabled: true
      required_zones:
        - south_west
        - south_east
    zones:
      south_east:
        coordinates: 1,0.217,1,0.909,0.731,0.911,0.731,1,0.511,1,0.516,0.256
        objects:
          - person
          - dog
          - cat
        inertia: 3
        loitering_time: 0
      south_west:
        coordinates: 
          0,1,0,0.171,0.038,0.172,0.091,0.292,0.343,0.263,0.339,0.054,0.382,0.052,0.382,0.259,0.508,0.257,0.506,1
        objects:
          - person
          - cat
        inertia: 3
        loitering_time: 0
    motion:
      improve_contrast: 'true'
      mask: 
        1,0,1,0.21,0.387,0.257,0.387,0.042,0.334,0.046,0.338,0.26,0.097,0.284,0.039,0.161,0,0.164,0,0
      threshold: 35
      contour_area: 10
    review:
      alerts:
        required_zones:
          - south_west
          - south_east
      detections:
        required_zones:
          - south_east
          - south_west
version: 0.16-0
semantic_search:
  enabled: true
  reindex: false
  model_size: small
detect:
  enabled: true
face_recognition:
  enabled: false
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
Do not have this with my phone
```

### Relevant Frigate log output

```shell
Unable to find log as system crashes
```

### Relevant go2rtc log output

```shell
I do not use go2rtc
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Network connection

Wired

### Camera make and model

Chinese hikvision that was working for more than 2 years with frigate previous versions 

### Screenshots of the Frigate UI's System metrics pages

Sorry, unable I'm using now with phone

### Any other information that may be helpful

I'm using frigate full access, once again, I cannot provide logs as the system crashes. Frigate works perfectly without activating face and plate recognition. I'm running a small amd mini pc
