### DISCUSSION TITLE
Running Frigate as a non-root user in Docker

### DISCUSSION THREAD

**Discussion by rickyelopez** [blakeblackshear/frigate#18375] [Show and tell]
Hi! Just spent a bunch of time trying to get this to work and I wanted to share all of the changes I ended up having to make in order to run Frigate in Docker as a non-root user within the container. **This is not rootless Docker**.

As far as I can tell, everything appears to be working properly. Please let me know if I missed something or if you are having issues!

My configuration is using an Intel iGPU and a PCIe Coral TPU, but I don't see why it wouldn't work for other hardware setups as well, although more modifications may be required.

## `compose.yml`
See the inline comments for relevant details where applicable. Most of the required changes are just mounting various files/dirs, but there are a couple of changes to the top-level as well
```yaml
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128

    user: 1010:1010 # make sure to set the UID/GID you want to run as!

    group_add:
      # I think the following group IDs should be pretty common across different linux hosts, but you can
      # double-check which groups you should mount by checking permissions on the devices, e.g. with
      # `ls -lap /dev/apex_0` and `ls -lap /dev/dri/renderD128`, and then get the GIDs with
      # `cat /etc/group | grep "<group name>"`
      - 992 # add "coral" group to get access to the Coral device
      - 303 # add "render" group to get access to the iGPU

    environment:
      TRANSFORMERS_CACHE: /tmp/cache/huggingface/hub

    cap_add:
      - CAP_PERFMON # you probably also need to set `kernel.perf_event_paranoid=0`, but that's not unique to this configuration
    
    tmpfs:
      # permissions don't seem to work properly using `shm_size`. I don't know for sure that this is actually a suitable alternative, but it seems to be working fine so far
      - /dev/shm:mode=770,uid=1010,gid=1010,size=268435456 # don't forget to set the UID/GID here!
      - /tmp/cache:mode=770,uid=1010,gid=1010,size=1G # don't forget to set the UID/GID here!
    
    volumes:
      # Not shown here: the typical mounts required for frigate such as the config dir, media dirs, and timezone

      # The following overrides are required to support running as a non-root user
      # each of these is documented below

      # s6 overrides
      - ./overrides/s6/log-prepare-run:/etc/s6-overlay/s6-rc.d/log-prepare/run
      - ./overrides/s6/nginx-check:/etc/s6-overlay/s6-rc.d/nginx/data/check
      - ./overrides/s6/s6-applyuidgid:/package/admin/s6/command/s6-applyuidgid

      # letsencrypt dirs need to exist so that we can provide certs or so that the container can generate self-signed certs and store them here
      - ./overrides/letsencrypt/live/frigate:/etc/letsencrypt/live/frigate
      - ./overrides/letsencrypt/www:/etc/letsencrypt/www
      
      # nginx overrides
      - ./overrides/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./overrides/nginx/conf/base_path.conf:/usr/local/nginx/conf/base_path.conf
      - ./overrides/nginx/conf/listen.conf:/usr/local/nginx/conf/listen.conf
      - ./overrides/nginx/logs:/usr/local/nginx/logs
      - ./overrides/nginx/temp_dirs:/usr/local/nginx/temp_dirs
```

# Overrides mounted in the above compose file:
## `./overrides/nginx/conf/nginx.conf`
At the top level, remove the `user` directive, and update the `pid` path. The pid path can be any directory that is writeable by the user you've selected, just make sure you make the corresponding change to `overrides/s6/nginx-check` as documented later in this post.

You may also want to specify an actual number of workers instead of `auto`, since the frigate startup script (which usually selects a number from 0-4 based on the system configuration) won't be able to update this anymore

In the `http` block, add directives to relocate all of the temp directories into a path that is writeable by your user

The relevant part of the file after modification (in my case) looks like:
```conf
daemon off;
worker_processes auto;

error_log /dev/stdout warn;
pid /usr/local/nginx/temp_dirs/nginx.pid;

http {
    # relocate temporary directories
    client_body_temp_path /usr/local/nginx/temp_dirs/client_body_temp;
    proxy_temp_path /usr/local/nginx/temp_dirs/proxy_temp;
    fastcgi_temp_path /usr/local/nginx/temp_dirs/fastcgi_temp;
    uwsgi_temp_path /usr/local/nginx/temp_dirs/uwsgi_temp;
    scgi_temp_path /usr/local/nginx/temp_dirs/scgi_temp;

...

```

## `./overrides/s6/log-prepare-run`
the only change from the one in the container is commenting out the `chown` and `chmod` at the bottom, which are no longer needed since we set the perms on `/dev/shm` when mounting the tmpfs
```bash
#!/command/with-contenv bash
# shellcheck shell=bash
# Prepare the logs folder for s6-log

set -o errexit -o nounset -o pipefail

dirs=(/dev/shm/logs/frigate /dev/shm/logs/go2rtc /dev/shm/logs/nginx /dev/shm/logs/certsync)

umask 022
mkdir -p "${dirs[@]}"
# chown nobody:nogroup "${dirs[@]}"
# chmod 02755 "${dirs[@]}"
```

## `./overrides/nginx/nginx-check`
just needs the path to the PID file updated
```bash
#!/usr/bin/env bash
set -e

# Wait for PID file to exist.
while ! test -f /usr/local/nginx/temp_dirs/nginx.pid; do sleep 1; done
```

## `./overrides/s6/s6-applyuidgid`
This one is pretty hacky and there's almost certainly a better way to do this. Despite the [patchnotes in the s6 repo](https://github.com/skarnet/s6/blob/19a795b3441f0c0b01bad33487a6ab060c20dcd7/NEWS#L117), `s6-applyuidgid` does not appear to be runnable by a non-root user. All of the calls to `s6-log` appear to run through `s6-applyuidgid` which (if it worked) would be a no-op since our user owns all of the relevant files. So, we patch it to just `exec` the program that the call to `s6-applyuidgid` would have ended up `exec`ing
```bash
#!/bin/bash

ARGS=( "$@" );
echo "'s6-applyuidgid' called with args '$@', 'exec'ing manually instead"
exec ${ARGS[@]:2}
```

## empty files
Create and mount these two files. You can leave them empty as the nginx startup script will write to them.
  - `./overrides/nginx/conf/base_path.conf`
  - `./overrides/nginx/conf/listen.conf`

## empty directories
All of the following directories just need to exist and be mounted so that the user can write to them. You don't need to put anything in them. Don't forget to set the permissions so that your frigate user can read/write to them!
  - `./overrides/letsencrypt/live/frigate`
  - `./overrides/letsencrypt/www`
  - `./overrides/nginx/logs`
  - `./overrides/nginx/temp_dirs`

I've just started running this but so far everything appears to be working. I'll update the thread if something breaks. I am totally open to suggestions for improvements here!

**Comment by audunmg** [comment]
This is wonderful, I can't wait to test with my nvidia gpu.

Last time i tried, the s6 was preventing me, but you've solved that.

I'll be so happy if i can finally get this running without root access, thank you for your effort!

**Reply by rickyelopez** [reply]
Glad it helps! Let me know if there are any issues.

**Comment by kinghrothgar** [comment]
FYI, the linked to s6 doesn't appear to be the one that's actually being installed which is why it doesn't correspond with the patch notes. [This](https://github.com/blakeblackshear/frigate/blob/dev/docker/main/install_s6_overlay.sh) is installing this [one](https://github.com/just-containers/s6-overlay).

**Comment by kinghrothgar** [comment]
Thanks to the original author for this. This is what I settled on to get Frigate working in **Kubernetes**, specifically Talos, with NVIDIA GPU acceleration. The changes needed to the statefulset and the configmap with scripts are in a diff below as an example. This assumes you have followed the installation guide and have already at a bare minimum a statefulset setup with the correct volumes mounted in:

- `/config` - PVC
- `/media/frigate` - PVC
- `/tmp/cache` - emptyDir of medium memory
- `/dev/shm` - emptyDir of medium memory

If you are migrating an existing Kube install, you will need to chown to the new UID:GID all the files and folders that Frigate has already written to `/config` and `/media/frigate`

## Set pod securityContext to correct user and group:

```yaml
      securityContext:
        fsGroup: 500
        runAsGroup: 500
        runAsNonRoot: true
        runAsUser: 500
```
## group_add:
this is not needed at least with my GPU setup (nvidia-container-toolkit)

## Environment Variables:

- `HOME`: several processes / libraries default to writing the the home directory which defaults to /. Set this to something writable, in my case I set it to an emptyDir mounted at `/tmp/home`. This is instead of setting `TRANSFORMERS_CACHE` which according to this [stackoverflow](https://stackoverflow.com/questions/63312859/how-to-change-huggingface-transformers-default-cache-directory) is deprecated in future releases. As more things in the future may need to write to a home folder, I felt this a more robust solution.
- `S6_CATCHALL_USER`: set to what UID you're running the container as, details found [here](https://github.com/just-containers/s6-overlay) (may not be needed)
- `S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES`: set to 1, details found [here](https://github.com/just-containers/s6-overlay)
- `USER`: set to what UID you're running the container as, details found [here](https://github.com/just-containers/s6-overlay) (may not be needed)

## Capabilities:
It seems like I was able to do drop ALL and did not need to `CAP_PERFMON`, but I may not understand what this was needed for. With nvidia-container-toolkit it seems like the pod is able to monitor both the CPU and the GPU.

## tmpfs:
While you still need both of these mounted in correctly, you don't need to change anything if it was working as root as Kube will create these emptyDir medium memory volumes with correct permissions

## Volumes and ConfigMap file mounts:

- `/etc/s6-overlay/s6-rc.d/log-prepare/run` - still needed, same as above
- `/package/admin/s6/command/s6-applyuidgid` - still needed, same as above
- `/usr/local/nginx` - Here I differed from the above guide. To satisfy the remaining issues, I used an init container that copies the contents of `/usr/local/nginx` from the frigate image to a emptyDir. Then this emptyDir is mounted into the real container at `/usr/local/nginx` and is writable. This route was taken because there is no way to mount in a single writable file like is being done with `base_path.conf` and `listen.conf` above in Kube.
- `/run` - needs to be writable, so mount in an emptyDir of medium memory
- `/tmp/home` - some processes / libraries try to write to the home folder, so mount in an emptyDir and set the HOME env to this path
- `/etc/letsencrypt` - emptyDir: if you're running in Kube, I would assume you have an Ingress or Gateway terminating TLS which is my case. Because of this, I don't mount in any TLS certs or need the TLS certs that Frigate automatically generates. I have TLS disabled in the `config.yaml`.

## Warnings and Errors:

This setup still has some warnings and errors printed in the log:

```
/package/admin/s6-overlay/libexec/preinit: warning: /run belongs to uid 0 instead of 500, but we can still work in single-uid mapping.
```

This is expected and why `S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES` is set.

```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/nginx/conf/nginx.conf:2
```

This is fine. Normally one would start nginx as root and then configure a user in the config that nginx runs the worker processes as. It correctly ignores the user in the conf as we're already running as non-root.

## Example Diff:

There are some extra changes in the diff to lock it down more to satisfy Talos' secure default profile:
```diff
diff --git a/frigate-StatefulSet.yaml b/frigate-StatefulSet.yaml
index 344c260..886b4f6 100644
--- a/frigate-StatefulSet.yaml
+++ b/frigate-StatefulSet.yaml
@@ -22,8 +22,16 @@ spec:
     spec:
       containers:
       - env:
+        - name: HOME
+          value: /tmp/home
+        - name: S6_CATCHALL_USER
+          value: "500"
+        - name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
+          value: "1"
         - name: TZ
           value: America/Denver
+        - name: USER
+          value: "500"
         envFrom:
         - secretRef:
             name: frigate
@@ -39,6 +47,11 @@ spec:
           name: rtsp
         - containerPort: 8555
           name: webrtc
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+            - ALL
         volumeMounts:
         - mountPath: /media/frigate
           name: nfs-nzxt01-frigate-media-lildata-frigate
@@ -46,10 +59,26 @@ spec:
           name: frigate-cm
           readOnly: true
           subPath: config.yaml
+        - mountPath: /etc/s6-overlay/s6-rc.d/log-prepare/run
+          name: frigate-cm-executable
+          readOnly: true
+          subPath: run
+        - mountPath: /package/admin/s6/command/s6-applyuidgid
+          name: frigate-cm-executable
+          readOnly: true
+          subPath: s6-applyuidgid
+        - mountPath: /usr/local/nginx
+          name: nginx
         - mountPath: /dev/shm
           name: shm
         - mountPath: /tmp/cache
           name: cache
+        - mountPath: /run
+          name: run
+        - mountPath: /etc/letsencrypt
+          name: letsencrypt
+        - mountPath: /tmp/home
+          name: home
         - mountPath: /config
           name: config
       initContainers:
@@ -59,7 +88,24 @@ spec:
         volumeMounts:
         - mountPath: /config
           name: config
+      - command:
+        - /bin/sh
+        - -c
+        - cp -r /usr/local/nginx/* /nginx/
+        image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
+        imagePullPolicy: IfNotPresent
+        name: frigate-init-nginx
+        volumeMounts:
+        - mountPath: /nginx
+          name: nginx
       runtimeClassName: nvidia
+      securityContext:
+        fsGroup: 500
+        runAsGroup: 500
+        runAsNonRoot: true
+        runAsUser: 500
+        seccompProfile:
+          type: RuntimeDefault
       volumes:
       - emptyDir:
           medium: Memory
@@ -69,6 +115,14 @@ spec:
           medium: Memory
           sizeLimit: 1Gi
         name: cache
+      - emptyDir:
+          medium: Memory
+          sizeLimit: 1Gi
+        name: run
+      - emptyDir: {}
+        name: letsencrypt
+      - emptyDir: {}
+        name: home
       - name: nfs-nzxt01-frigate-media-lildata-frigate
         persistentVolumeClaim:
           claimName: nfs-nzxt01-frigate-media-lildata-frigate
@@ -78,6 +132,17 @@ spec:
             path: config.yaml
           name: frigate-cm
         name: frigate-cm
+      - configMap:
+          defaultMode: 365
+          items:
+          - key: run
+            path: run
+          - key: s6-applyuidgid
+            path: s6-applyuidgid
+          name: frigate-cm
+        name: frigate-cm-executable
+      - emptyDir: {}
+        name: nginx
       - name: config
         persistentVolumeClaim:
           claimName: config
diff --git a/frigate-cm-ConfigMap.yaml b/frigate-cm-ConfigMap.yaml
index 3617a8c..ebdf9b7 100644
--- a/frigate-cm-ConfigMap.yaml
+++ b/frigate-cm-ConfigMap.yaml
@@ -74,6 +74,22 @@ data:
       "model_size": "large"
     "tls":
       "enabled": false
+  run: |
+    #!/command/with-contenv bash
+    # shellcheck shell=bash
+    # Prepare the logs folder for s6-log
+
+    set -o errexit -o nounset -o pipefail
+
+    dirs=(/dev/shm/logs/frigate /dev/shm/logs/go2rtc /dev/shm/logs/nginx /dev/shm/logs/certsync)
+
+    mkdir -p "${dirs[@]}"
+  s6-applyuidgid: |
+    #!/bin/bash
+
+    ARGS=( "$@" );
+    # s6-applyuidgid called with args $@, execing manually instead
+    exec ${ARGS[@]:2}
 kind: ConfigMap
 metadata:
   labels:
```
