### DISCUSSION TITLE
[Bug]: Homeassistant craps out when reviewing video with Frigate proxy

### DISCUSSION THREAD

**Discussion by SteveLobdell** [blakeblackshear/frigate#18374] [Report a Bug]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have HA running on a Pi5, Frigate running on a separate Ubuntu server, and using the proxy addon for HA.  I've just started using Frigate 0.16.0 Beta 2, and since then when I start playing videos in the explore tab through HA, for some reason my HA goes to lunch for like 5 minutes.  During this time, HA is inaccessible, but I can connect directly to Frigate with no issues.  I hooked a monitor up to my Pi and I see the terminal, there aren't any errors or anything.  Not really sure what the deal is and I know this is beta, but it seems weird that Frigate is fine but my HA isn't when I'm only using the proxy.  Also curious if anyone else has seen this issue.  Thanks, love Frigate!

### Steps to reproduce

1. Review some video using 0.16.0 Beta 2 in Homeassistant using Frigate proxy?

### Version

0.16.0 Beta 2

### In which browser(s) are you experiencing the issue with?

All browsers

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.67
  user: mqtt-user
  password: you_wish

tls:
  enabled: false

birdseye:
  enabled: true
  mode: continuous

model:
  path: plus://c241fae21de50ecf6c0f2a63769dcacd

detectors:
  coral:
    type: edgetpu
    device: usb

face_recognition:
  enabled: true
  model_size: large

lpr:
  enabled: true

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 30
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

snapshots:
  enabled: true
  bounding_box: false
  retain:
    default: 180

detect:
  enabled: true
  width: 640
  height: 360
  fps: 5

audio:
  enabled: true

live:
  height: 1440
  quality: 1

go2rtc:
  webrtc:
    candidates:
      - 192.168.0.2:8555
      - stun:8555

  streams:
    front_yard:
      - rtsp://Homeassistant:you_wish@192.168.0.205:554/stream1#backchannel=0
      - tapo://you_wish@192.168.0.205
      - ffmpeg:front_yard#audio=aac
    front_yard_sub:
      - rtsp://Homeassistant:you_wish@192.168.0.205:554/stream2#backchannel=0
      - tapo://you_wish@192.168.0.205
      - ffmpeg:front_yard_sub#audio=aac

    steve_office:
      - rtsp://Homeassistant:you_wish@192.168.0.3:554/stream1#backchannel=0
      - tapo://you_wish@192.168.0.3
      - ffmpeg:steve_office#audio=aac
    steve_office_sub:
      - rtsp://Homeassistant:you_wish@192.168.0.3:554/stream2#backchannel=0
      - tapo://you_wish@192.168.0.3
      - ffmpeg:steve_office_sub#audio=aac

    play_room:
      - rtsp://Homeassistant:you_wish@192.168.0.6:554/stream1#backchannel=0
      - tapo://you_wish@192.168.0.6
      - ffmpeg:play_room#audio=aac
    play_room_sub:
      - rtsp://Homeassistant:you_wish@192.168.0.6:554/stream2#backchannel=0
      - tapo://you_wish@192.168.0.6
      - ffmpeg:play_room_sub#audio=aac

    garage:
      - rtsp://Homeassistant:you_wish@192.168.0.72:554/stream1#backchannel=0
      - tapo://you_wish@192.168.0.72
      - ffmpeg:steve_office#audio=aac
    garage_sub:
      - rtsp://Homeassistant:you_wish@192.168.0.72:554/stream2#backchannel=0
      - tapo://you_wish@192.168.0.72
      - ffmpeg:garage_sub#audio=aac

    front_door:
      - rtsp://admin:you_wish@192.168.0.81:554/h264Preview_01_main
      - ffmpeg:https://192.168.0.81/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=you_wish!#video=copy#audio=copy#audio=aac
    front_door_sub:
      - rtsp://admin:you_wish@192.168.0.81:554/h264Preview_01_sub

cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    review:
      alerts:
        required_zones:
          - Car_Zone
    detect:
      width: 2560
      height: 1440
    live:
      streams:
        front_yard: front_yard
    objects:
      track:
        - person
        - dog
        - car
        - bicycle
        - motorcycle
        - cat
        - sports ball
        - amazon
        - usps
        - ups
        - fedex
        - dhl
    face_recognition:
      enabled: false
    motion:
      mask: 
        0,0.43,0.179,0.406,0.275,0.277,0.225,0.206,0.27,0.153,0.327,0.147,0.468,0.067,0.611,0.104,0.748,0.16,0.788,0.42,1,0.426,1,0,0,0
    zones:
      Car_Zone:
        coordinates: 
          0.479,0.067,0.403,0.104,0.326,0.149,0.27,0.153,0.244,0.184,0.225,0.206,0.215,0.236,0.237,0.27,0.352,0.292,0.379,0.219,0.585,0.217,0.617,0.284,0.739,0.25,0.772,0.23,0.774,0.182,0.736,0.149,0.679,0.132,0.632,0.108,0.583,0.098,0.534,0.085
        loitering_time: 0
        objects:
          - bicycle
          - car
          - motorcycle
        inertia: 3
  steve_office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/steve_office?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/steve_office_sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    objects:
      track:
        - person
    review:
      alerts:
        required_zones:
          - Person_Zone
    live:
      streams:
        steve_office: steve_office
    face_recognition:
      enabled: false
    lpr:
      enabled: false
    motion:
      mask: 0.001,0.063,0,1,0.154,1,0.332,1,0.349,0.494,0.354,0.05,0.355,0,0,0
    zones:
      Person_Zone:
        coordinates: 0.332,1,0.343,0.662,0.35,0.442,0.355,0,1,0,1,1
        loitering_time: 0

        inertia: 3
  play_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/play_room?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/play_room_sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    objects:
      track:
        - person
        - dog
      filters:
        dog:
          mask: 0.467,0.992,0.477,0.607,0.684,0.514,1,0.585,1,1
    face_recognition:
      enabled: false
    lpr:
      enabled: false
    live:
      streams:
        play_room: play_room

    motion:
      mask: 0.357,0.056,0,0.054,0,0,0.36,0
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    objects:
      track:
        - person
        - dog
    face_recognition:
      enabled: false
    lpr:
      enabled: false
    live:
      streams:
        garage: garage
    motion:
      mask: 0,0,1,0,0.914,0.178,0.735,0.4,0.319,0.397,0,0.055

  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_door_sub?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - face
    detect:
      width: 2560
      height: 1920
    live:
      height: 1920
      streams:
        front_door: front_door
    lpr:
      enabled: false
    zones:
      Front_Door_Zone:
        coordinates: 0.266,0,0.292,0.602,0.316,0.864,0.571,0.885,0.578,0,1,0,1,1,0,1,0,0
        loitering_time: 0
        inertia: 3
        objects:
          - dog
          - person
          - face
    motion:
      mask:
        - 0,0.057,0.348,0.054,0.348,0,0,0
        - 0.303,0.243,0.538,0.217,0.537,0.377,0.575,0.383,0.573,0.642,0.296,0.645,0.285,0.44
version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    privileged: true
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2
    volumes:
      - ./config:/config
      - /storage/Frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5001:5000"
      - "1984:1984"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    shm_size: "2000mb"
    environment:
     - PLUS_API_KEY=you_wish
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Tapo C120s

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/90827b09-c9d3-4300-ab3c-8b0f51b02e0f)
