### DISCUSSION TITLE
[Config Support]: Tapo Cameras with go2rtc spews errors, drops from hoass

### DISCUSSION THREAD

**Discussion by rqbanerjee** [blakeblackshear/frigate#18385] [Config Support]
### Describe the problem you are having

I have 3 tapo cameras. I am having a hard time setting up a reliable feed with go2rtc that has audio and stays connected over days/weeks at a time.

Pretty consistently, to go2rtc streams become "unavailable" overnight, even though the regular streams stay up. I would like to remove the direct streams and only use the go2rtc streams, but due to unreliability of the go2rtc streams, I have record/detect set up on the direct streams. Also I would love to show these in my home assistant and it sounds like go2rtc is required for hoass.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mqtt.lan
  user: mqtt
  password: 'myPassword'

detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - dog
    - cat
    - mouse

go2rtc:
  streams:
    back_porch_go: 
      - rtsp://frigate:myPassword@tapobackporch.lan:554/stream1
      - "ffmpeg:back_porch#audio=aac"
    fr_porch_go:
      - rtsp://frigate:myPassword@c120.lan:554/stream1
      - "ffmpeg:fr_porch#audio=aac"
    driveway_camera_go:
      - rtsp://frigate:myPassword@TC55.lan:554/stream1
      - "ffmpeg:driveway_camera#audio=aac"

cameras:
  back_porch_go:
    enabled: True
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/back_porch_go
        input_args: preset-rtsp-restream
  fr_porch_go:
    enabled: True
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/fr_porch_go
        input_args: preset-rtsp-restream
  driveway_camera_go:
    enabled: True
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_camera_go
        input_args: preset-rtsp-restream
  back_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:myPassword@tapobackporch.lan:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    detect:
      enabled: true
      fps: 5
    objects:
      filters:
        car:
          mask: 0.612,0.349,0.773,0.308,0.786,0.467,0.458,0.48,0.446,0.392
  fr_porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:myPassword@c120.lan:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    detect:
      enabled: true
      fps: 5

    motion:
      mask:
        - 0.873,0.74,0.925,0.686,0.999,0.698,1,0.999,0.594,1
        - 0.747,0.722,0.76,0.816,0.869,0.748,0.858,0.694,0.811,0.689
    objects:
      filters:
        person:
          mask: 0.73,0.707,0.878,0.654,0.905,0.74,0.756,0.838
  driveway_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:myPassword@TC55.lan:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: motion
      detections:
        retain:
          days: 30
          mode: motion
    detect:
      enabled: true
      fps: 5
    motion:
      mask: 0.002,0.451,0.257,0.255,0.276,0.196,0.259,0.002,0.004,0.002
    objects:
      filters:
        car:
          mask: 0.727,0.081,0.774,0.094,0.768,0.214,0.72,0.194
version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: large
notifications:
  enabled: true
  email: xxx@gmail.com
```

### Relevant Frigate log output

```shell
error | 2025-05-24 15:05:20 | ffmpeg.fr_porch_go.detect | Last message repeated 2 times
error | 2025-05-24 15:05:20 | ffmpeg.fr_porch_go.detect | [h264 @ 0x55fbef22e180] SEI type 764 size 34 truncated at 32
error | 2025-05-24 15:05:20 | ffmpeg.fr_porch_go.detect | Last message repeated 2 times
error | 2025-05-24 15:05:20 | ffmpeg.fr_porch_go.detect | [h264 @ 0x55fbef5a7800] SEI type 764 size 34 truncated at 32
```

### Relevant go2rtc log output

```shell
warning | 2025-05-24 13:50:51 | rtsp    | error="streams: dial tcp: lookup tapobackporch.lan: i/o timeout, exec: [in#0 @ 0x55811e617980] Error opening input: No such file or directory\nError opening input file back_porch.\nError opening input files: No such file or directory\n" stream=back_porch_go
warning | 2025-05-24 13:50:51 | rtsp    | error="streams: dial tcp: lookup c120.lan: i/o timeout, exec: [in#0 @ 0x56344a6e5980] Error opening input: No such file or directory\nError opening input file fr_porch.\nError opening input files: No such file or directory\n" stream=fr_porch_go
warning | 2025-05-24 13:50:51 | rtsp    | error="streams: dial tcp: lookup TC55.lan: i/o timeout, exec: [in#0 @ 0x5570b0be2980] Error opening input: No such file or directory\nError opening input file driveway_camera.\nError opening input files: No such file or directory\n" stream=driveway_camera_go
warning | 2025-05-24 14:05:14 | startup | github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.2:40104->192.168.27.220:554: i/o timeout" url=rtsp://frigate:myPassword@c120.lan:554/stream1
warning | 2025-05-24 15:04:55 | startup | github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.2:41750->192.168.27.220:554: i/o timeout" url=rtsp://frigate:myPassword@c120.lan:554/stream1
```

### Frigate stats

```json
{
"cameras": {
"back_porch_go": {
"camera_fps": 5,
"process_fps": 5.2,
"skipped_fps": 0,
"detection_fps": 14.3,
"detection_enabled": true,
"pid": 511,
"capture_pid": 550,
"ffmpeg_pid": 764,
"audio_rms": 0,
"audio_dBFS": 0
},
"fr_porch_go": {
"camera_fps": 5.1,
"process_fps": 2.8,
"skipped_fps": 2.3,
"detection_fps": 22.9,
"detection_enabled": true,
"pid": 512,
"capture_pid": 563,
"ffmpeg_pid": 15681,
"audio_rms": 0,
"audio_dBFS": 0
},
"driveway_camera_go": {
"camera_fps": 5.1,
"process_fps": 4.5,
"skipped_fps": 0.5,
"detection_fps": 8.8,
"detection_enabled": true,
"pid": 514,
"capture_pid": 567,
"ffmpeg_pid": 11902,
"audio_rms": 0,
"audio_dBFS": 0
},
"back_porch": {
"camera_fps": 5,
"process_fps": 4.5,
"skipped_fps": 0.5,
"detection_fps": 11.9,
"detection_enabled": true,
"pid": 524,
"capture_pid": 571,
"ffmpeg_pid": 581,
"audio_rms": 0,
"audio_dBFS": 0
},
"fr_porch": {
"camera_fps": 5.4,
"process_fps": 2.8,
"skipped_fps": 2.5,
"detection_fps": 22.5,
"detection_enabled": true,
"pid": 534,
"capture_pid": 574,
"ffmpeg_pid": 580,
"audio_rms": 0,
"audio_dBFS": 0
},
"driveway_camera": {
"camera_fps": 5,
"process_fps": 4.6,
"skipped_fps": 0.3,
"detection_fps": 5.9,
"detection_enabled": true,
"pid": 539,
"capture_pid": 584,
"ffmpeg_pid": 592,
"audio_rms": 0,
"audio_dBFS": 0
}
},
"detectors": {
"coral": {
"inference_speed": 9.68,
"detection_start": 1748113684.864062,
"pid": 475
}
},
"detection_fps": 86.3,
"gpu_usages": {
"intel-vaapi": {
"gpu": "0.0%",
"mem": "-%"
}
},
"cpu_usages": {
"1": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
},
"15": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6-linux-init-shutdownd"
},
"16": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
},
"24": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync"
},
"25": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-fdholder"
},
"26": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc"
},
"27": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise s6rc-oneshot-runner"
},
"28": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise certsync-log"
},
"29": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx-log"
},
"30": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate-log"
},
"31": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-log"
},
"32": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise frigate"
},
"33": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise nginx"
},
"34": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-supervise go2rtc-healthcheck"
},
"45": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
},
"46": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
},
"86": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
},
"88": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
},
"89": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
},
"90": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
},
"98": {
"cpu": "3.4",
"cpu_average": "3",
"mem": "0.2",
"cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
},
"120": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user go2rtc-healthcheck"
},
"123": {
"cpu": "9.5",
"cpu_average": "10",
"mem": "8.9",
"cmdline": "python3 -u -m frigate"
},
"129": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: master process nginx"
},
"160": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"161": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"162": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"163": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "nginx: worker process"
},
"164": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "nginx: cache manager process"
},
"310": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "bash ./run.user certsync"
},
"459": {
"cpu": "2.0",
"cpu_average": "2",
"mem": "1.5",
"cmdline": "frigate.recording_manager"
},
"461": {
"cpu": "0.9",
"cpu_average": "0",
"mem": "1.4",
"cmdline": "frigate.review_segment_manager"
},
"475": {
"cpu": "55.7",
"cpu_average": "51",
"mem": "1.4",
"cmdline": "frigate.detector.coral"
},
"496": {
"cpu": "5.8",
"cpu_average": "5",
"mem": "1.6",
"cmdline": "frigate.output       "
},
"511": {
"cpu": "9.9",
"cpu_average": "12",
"mem": "1.8",
"cmdline": "frigate.process:back_porch_go"
},
"512": {
"cpu": "13.3",
"cpu_average": "10",
"mem": "1.9",
"cmdline": "frigate.process:fr_porch_go"
},
"514": {
"cpu": "5.8",
"cpu_average": "9",
"mem": "1.8",
"cmdline": "frigate.process:driveway_camera_go"
},
"524": {
"cpu": "8.0",
"cpu_average": "11",
"mem": "1.8",
"cmdline": "frigate.process:back_porch"
},
"534": {
"cpu": "13.7",
"cpu_average": "11",
"mem": "1.8",
"cmdline": "frigate.process:fr_porch"
},
"539": {
"cpu": "3.8",
"cpu_average": "8",
"mem": "1.8",
"cmdline": "frigate.process:driveway_camera"
},
"550": {
"cpu": "4.1",
"cpu_average": "3",
"mem": "1.5",
"cmdline": "frigate.capture:back_porch_go"
},
"563": {
"cpu": "4.0",
"cpu_average": "3",
"mem": "2.0",
"cmdline": "frigate.capture:fr_porch_go"
},
"567": {
"cpu": "4.2",
"cpu_average": "3",
"mem": "1.6",
"cmdline": "frigate.capture:driveway_camera_go"
},
"571": {
"cpu": "4.2",
"cpu_average": "3",
"mem": "1.7",
"cmdline": "frigate.capture:back_porch"
},
"574": {
"cpu": "4.1",
"cpu_average": "3",
"mem": "2.0",
"cmdline": "frigate.capture:fr_porch"
},
"580": {
"cpu": "15.1",
"cpu_average": "14",
"mem": "0.7",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@c120.lan:554/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/fr_porch@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"581": {
"cpu": "14.4",
"cpu_average": "14",
"mem": "0.9",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@tapobackporch.lan:554/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_porch@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"584": {
"cpu": "4.1",
"cpu_average": "3",
"mem": "1.6",
"cmdline": "frigate.capture:driveway_camera"
},
"592": {
"cpu": "14.5",
"cpu_average": "13",
"mem": "0.8",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://*:*@TC55.lan:554/stream1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_camera@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"594": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"601": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"608": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"615": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.4",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"622": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.5",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"629": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.5",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 2560x1440 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"636": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.1",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
},
"764": {
"cpu": "13.7",
"cpu_average": "13",
"mem": "0.8",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/back_porch_go -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"11902": {
"cpu": "14.2",
"cpu_average": "13",
"mem": "0.7",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/driveway_camera_go -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"15681": {
"cpu": "13.9",
"cpu_average": "13",
"mem": "0.6",
"cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/fr_porch_go -r 5 -vf fps=5,scale_vaapi=w=2560:h=1440,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
},
"16170": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 60"
},
"16207": {
"cpu": "0.0",
"cpu_average": "0",
"mem": "0.0",
"cmdline": "sleep 30s"
},
"frigate.full_system": {
"cpu": "63.6",
"mem": "36.0"
}
},
"service": {
"uptime": 4637,
"version": "0.15.0-6cb5cfb",
"latest_version": "0.15.1",
"storage": {
"/media/frigate/recordings": {
"total": 3754443,
"used": 552000.3,
"free": 3011654.4,
"mount_type": "ext4"
},
"/media/frigate/clips": {
"total": 3754443,
"used": 552000.3,
"free": 3011654.4,
"mount_type": "ext4"
},
"/tmp/cache": {
"total": 953.7,
"used": 27.1,
"free": 926.6,
"mount_type": "tmpfs"
},
"/dev/shm": {
"total": 1024,
"used": 921.6,
"free": 102.4,
"mount_type": "tmpfs"
}
},
"temperatures": {},
"last_updated": 1748113685
},
"processes": {
"recording": {
"pid": 459
},
"review_segment": {
"pid": 461
},
"go2rtc": {
"pid": 98
}
}
}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      # - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rajat/frigate/config:/config
      - /mnt/data:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "myPassword"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-05-24 at 3 13 13 PM](https://github.com/user-attachments/assets/301be6e4-ef26-47c8-98a1-b68f20cc489d)

**Comment by hawkeye217** [comment]
You could try using the `tapo` source with go2rtc: https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-tapo

In general, wifi cameras are not recommended: https://ipcamtalk.com/threads/multiple-cameras-high-bandwidth.77100/#post-861110

**Reply by rqbanerjee** [reply]
Got it. I am stuck with wifi unfortunately, too hard to drag wires to these remote corners. 

The tapo: prefix didn't work with go2rtc, but i did put it into the frigate config. This bypasses go2rtc, and i have no audio on the stream.

**Reply by hawkeye217** [reply]
go2rtc is required if you want audio in the live stream: 

https://docs.frigate.video/configuration/live
https://docs.frigate.video/guides/configuring_go2rtc/

If you don't have audio in your recordings, see the FAQ: https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Comment by pipip** [comment]
My Tapo Wifi cams work quite stable with the following go2rtc config:
```
ffmpeg:
  ...
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac 

go2rtc:
  streams:
    main
      - ffmpeg:rtsp://user:pw@x.x.x.x:554/stream1#video=copy#audio=copy#audio=aac#hardware`
    sub
      - ffmpeg:rtsp://user:pw@x.x.x.x:554/stream2#video=copy#audio=copy#audio=aac#hardware`
```
