### DISCUSSION TITLE
I stuffed up somewhere - only now realise and dont know if to start from scratch or not ?

### DISCUSSION THREAD

**Discussion by vw-kombi** [blakeblackshear/frigate#18407] [Config Support] [answered]
### Describe the problem you are having

I notices when in settings that every time I do a save on a zone motion mask change, I get a message 'Failed to save config changes: Error updating config'.  I can make zone size changes and they save, so its not a config security issue.  I tried removing and re-adding zones bit by bit but no help.  The logs just say the same as the the error.  This is installed as addon to HA.  

I later found that the changes are actually being mode, but only one at a time (ie restart after every change that throws that error - if no restart, then the second change also throws error - but is not changed after a restart).

I also cant make any changes to the camera settings tab - I cant click on them to 'select zones for alerts' - throws an error the same also - and they are NOT saving after a restart - so I cant set alerts for the zones.

Frigate has been very good to me until this issue.

I am thinking I made changes direct into the config file in the past and something is conflicting.  I had quite the config (4 cameras, 12 ish zones, AI etc etc - but now I am thinking - stuff it, lets load the beta 0.16 and start from scratch.  

What is the process to delete everything (After saving the config.yaml so I have the camera data to copy in at least) ?  And have a blank sheet in home assistant too - 

### Version

0.15

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.30.249:5005/api/config/schema.json

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  width: 1280
  height: 720

database:
  path: /config/frigate.db

mqtt:
  host: core-mosquitto
  topic_prefix: frigate
  user: MQTT
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

semantic_search:
  enabled: true
  model_size: large
  reindex: false

genai:
  enabled: true
  provider: gemini
  api_key: xxx
  model: gemini-1.5-flash

cameras:
  Front-Cam:
    enabled: true
    genai: # <- Custom AI Prompts for objects can go here
      enabled: true
      use_snapshot: false
      prompt: Summarize what's happening in the camera feed (one sentence max). Don't
        describe the scene! If there is a person, describe what they're doing and
        what they look like. If they look like a courier mention that! Ignore a tortoise.
#     objects:
#       - person
      required_zones:
        - frontpath
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://hikvision:xxx@10.10.40.18:554/Streaming/Channels/102 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://hikvision:xxx@10.10.40.18:554/Streaming/Channels/101 # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 6
    objects:
      track:
        - person
        - dog
        - motorcycle
      filters:
        motorcycle:
          min_score: 0.60
        person:
          min_score: 0.65
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 3
      detections:
        retain:
          days: 3
    snapshots:
      enabled: true
      required_zones:
        - frontleft
        - frontright
        - frontpath
        - driveway
      bounding_box: true
      timestamp: true
      retain:
        default: 3
    motion:
      mask:
        - 0.402,1,0.394,0.939,0.284,0.933,0.172,0.877,0.14,0.946,0.002,0.943,0.004,0.997
        - 0.707,0,0.708,0.039,0.896,0.081,0.894,0.104,0.89,0.138,0.907,0.232,0.865,0.407,0.939,0.924,0.999,0.8,1,0.002
        - 0.112,0.173,0.111,0.092,0.141,0.064,0.14,0,0.11,0.004,0,0.002,0,0.377,0.175,0.209,0.166,0.177
      threshold: 40
      contour_area: 15
      improve_contrast: true
    zones:
      driveway:
        coordinates: 0.214,0.183,0,0.389,0,1,0.421,1,0.737,1,0.747,0.366,0.405,0.241
        inertia: 3
        loitering_time: 2
        objects:
          - person
          - dog
      frontpath:
        coordinates: 0.744,1,0.752,0.37,0.804,0.385,0.862,0.404,0.889,0.607,0.937,0.932,0.901,1
        inertia: 3
        loitering_time: 0
        objects:
          - person
          - dog
      frontleft:
        coordinates: 
          0.119,0.159,0.488,0.254,0.508,0.13,0.524,0,0.213,0,0.141,0,0.145,0.064,0.115,0.09
        inertia: 3
        loitering_time: 5
        objects:
          - person
          - dog
      frontright:
        coordinates: 
          0.891,0.09,0.887,0.139,0.905,0.235,0.868,0.4,0.81,0.376,0.705,0.335,0.5,0.263,0.54,0,0.703,0,0.702,0.041
        inertia: 3
        loitering_time: 4
        objects:
          - person
          - motorcycle
          - dog
    review:
      alerts:
        required_zones:
          - driveway
          - frontpath
          - frontleft
          - frontright
      detections:
        required_zones:
          - driveway
          - frontpath
          - frontleft
          - frontright
  Front-Door:
    enabled: true
    genai: # <- Custom AI Prompts for objects can go here
      enabled: true
      prompt: Summarize what's happening in the camera feed (one sentence max). Don't
        describe the scene! If there is a person or a dog, describe what they're doing
        and what they look like. If they look like a courier mention that! Ignore
        the tortoise.
#      object_prompts:
#         person: "Observe the person in these images, describe what they're doing and what they look like (one sentence max). Don't describe the scene! If they look like a courier mention that! If nothing is happening, say so."
#         cat: "Observe the cat in these images. Focus on its movement and intent (e.g., wandering, hunting, interacting with objects). If the cat is near the flower pots or engaging in any specific actions, mention it."
#      objects:
#        - person
#        - cat
#      required_zones:
#        - doorway
#        - pathway
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://dahua:xxx@10.10.40.15/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://dahua:xxx@10.10.40.15/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.65
    record:
      enabled: true
      retain:
        days: 4
        mode: motion
      alerts:
        retain:
          days: 4
      detections:
        retain:
          days: 4
    snapshots:
      enabled: true
      required_zones:
        - doorway
        - pathway
      bounding_box: true
      timestamp: true
      retain:
        default: 4
    motion:
      threshold: 35
      contour_area: 10
      lightning_threshold: 0.8
      improve_contrast: true
    zones:
      pathway:
        coordinates: 
          0.754,0.173,0.756,0.144,0.697,0.074,0.66,0,0.638,0.672,0.857,0.75,0.832,0.271,0.811,0.269,0.808,0.188
        inertia: 3
        loitering_time: 0
        objects:
          - dog
          - person
      doorway:
        coordinates: 0,0,0,1,0.806,1,0.806,1,0.586,0.941,0.61,0
        loitering_time: 0
        objects:
          - dog
          - person
        inertia: 3
    review: {}
  Loki-Cam:
    enabled: true
    genai: # <- Custom AI Prompts for objects can go here
      enabled: false
      prompt: Summarize what's happening in the camera feed (one sentence max). Don't
        describe the scene! If there is a person, describe what they're doing and
        what they look like. If they look like a courier mention that! If nothing
        is happening, say so. Ignore the tortoise.
    ffmpeg:
      inputs:
        - path: rtsp://foscam:xxx@10.10.40.16:88/videoSub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://foscam:xxx@10.10.40.16:88/videoMain # <----- The stream you want to use for recording
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - dog
      filters:
        dog:
          min_score: 0.65
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      alerts:
        retain:
          days: 1
      detections:
        retain:
          days: 1
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 3
    motion:
      threshold: 30
      contour_area: 10
      lightning_threshold: 0.8
      improve_contrast: 'true'
      mask: 0.002,0.001,0.36,0.001,0.36,0.047,-0.001,0.048
    zones:
      Loki-Zone:
        coordinates: 0.002,0.047,0.995,0.052,0.995,0.986,0.001,0.984
        loitering_time: 2
        inertia: 3
        objects: dog
    review:
      alerts:
        required_zones: Loki-Zone
      detections:
        required_zones: Loki-Zone
  Back-Cam:
    enabled: true
    genai: # <- disable GenAI for your indoor camera
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://foscam:xxx@10.10.40.14:554/videoSub # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://foscam:xxx@10.10.40.14:554/videoMain # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.70
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      alerts:
        retain:
          days: 3
      detections:
        retain:
          days: 3
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 3
    motion:
      mask:
        - 0.998,0.005,0,0.004,0.001,0.354,0.398,0.264,0.653,0.218,0.999,0.166
        - 0.377,0.991,0.373,0.878,0.297,0.8,0.242,0.8,0.216,0.834,0.193,0.874,0.185,0.919,0.145,0.94,0.126,0.993
        - 0.001,0.984,0.086,0.952,0.061,0.699,0.002,0.611
        - 0.132,0.86,0.203,0.841,0.203,0.694,0.12,0.687,0.108,0.756
      threshold: 35
      contour_area: 15
      improve_contrast: true
    zones:
      Backyard-Seating:
        coordinates: 0.656,0.281,0.998,0.251,1,0.766,0.629,0.68,0.636,0.512,0.668,0.483
        loitering_time: 3
        objects: person
      Backyard-Main:
        coordinates: 
          0.002,0.361,0.005,0.996,0.507,0.996,0.465,0.646,0.483,0.607,0.622,0.627,0.63,0.497,0.661,0.476,0.646,0.228
        loitering_time: 3
        objects: person
    review:
      alerts:
        required_zones:
          - Backyard-Seating
          - Backyard-Main
      detections:
        required_zones:
          - Backyard-Seating
          - Backyard-Main
version: 0.15-1
```

### Relevant Frigate log output

```shell
2025-05-27 13:17:49
Tag
root
Message
Error updating config: ''
```

### Relevant go2rtc log output

```shell
N/A
```

### Frigate stats

```json
Dont know how to do this ?
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

OpenVino
