### DISCUSSION TITLE
How to check if go2rtc really works?

### DISCUSSION THREAD

**Discussion by Dzonzi** [blakeblackshear/frigate#18406] [Config Support]
### Describe the problem you are having

Hello, I am newbie. I have 4 cameras and I think I dont know how to configure go2rtc restream. I copy-paste from docu but still I don't see the difference between original stream from camera and from go2rtc while docu says "It should look much clearer and more fluent than the original jsmpeg stream." I don't think so. It's very similar to a stream opened in Potplayer.

Also live instruction doesn't work. As you might see I put last two cameras the same live stream name but in webUI I see video from 2 different cameras. Also quality of this live view is low, sometimes jump to high.... i don't know whats going on. 
When I go to go2rtc WebUI under http://100.xxx.xxx.xxx:8123/core_configurator/ingress the stream are ok, I mean low res is low res, high is high. I use tailscale by the way. 

Camera codec is H264, no smart codec etc.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
############################################################################
#============================== MQTT ======================================#
############################################################################

mqtt:
  enabled: true
  host: xxx.xxx.xxx.xxxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: password
  stats_interval: 30

############################################################################
#====================== In-feed TIMESTAMP configuration ===================#
############################################################################

timestamp_style:
  position: bl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow #solid #shadow

############################################################################
#============================== LOGGER ====================================#
############################################################################

logger:
  logs:
    frigate.record.maintainer: debug
    detector.coral: debug

############################################################################
#================================= GO2RTC =================================#
############################################################################

go2rtc:
  streams:
    Dahua_1_HiRes:
      - rtsp://admin:password@192.168.xxx.xxx/cam/realmonitor?channel=1&subtype=0
    Dahua_1_LowRes:
      - rtsp://admin:password@192.168.xxx.xxx/cam/realmonitor?channel=1&subtype=1     
    Dahua_2_HiRes:
      - rtsp://admin:password@192.168.xxx.xxx/cam/realmonitor?channel=1&subtype=0
    Dahua_2_LowRes:
      - rtsp://admin:password@192.168.xxx.xxx/cam/realmonitor?channel=1&subtype=1
    Asecam_1_HiRes:
      - rtsp://admin:password@192.168.xxx.xxx:554/stream1
    Asecam_1_LowRes:
      - rtsp://admin:password@192.168.xxx.xxx:554/stream0     
    Asecam_2_HiRes:
      - rtsp://admin:password@192.168.xxx.xxx:554/stream1
    Asecam_2_LowRes:
      - rtsp://admin:password@192.168.xxx.xxx:554/stream0     
      

############################################################################
#============================= BIRDSEYE ===================================#
############################################################################

birdseye:
  enabled: true
  mode: continuous

############################################################################
#============================ DETECTORS ===================================#
############################################################################

detectors:
  coral:
    type: edgetpu
    device: usb

############################################################################
#======================== GLOBAL DETECTIONS ===============================#
############################################################################

detect:
  width: 704
  height: 576
  fps: 5
  stationary:
    interval: 50
    threshold: 30
    max_frames:
      objects:
        person: 300
        car: 50000
objects:
  track:
    - person
    - car

############################################################################
#========================= GLOBAL SPANSHOTS ===============================#
############################################################################

snapshots:
  enabled: true
  bounding_box: true
  clean_copy: false
  timestamp: true
  retain:
    default: 30

############################################################################
#============================ GLOBAL RECORD ===============================#
############################################################################

record:
  enabled: true
  retain:
    days: 0
    mode: active_objects
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects

############################################################################
#                                                                          #
#============================== CAMERAS ===================================#
#                                                                          #
###########################################################################

cameras:
  Dahua_1_HiRes:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/Dahua_1_HiRes?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dahua_1_LowRes?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 0.55,0.026,0.55,0.086,0.959,0.095,0.962,0.021
        - 0.646,0.34,0.666,0.416,0.741,0.437,0.752,0.401,0.741,0.375,0.737,0.347,0.729,0.333,0.723,0.29,0.705,0.266,0.687,0.269
        - 0.572,0.673,0.669,0.805,0.74,0.753,0.726,0.632,0.66,0.537,0.608,0.558
        - 0.187,0,0.088,0,0.054,0.024,0,0.079,0,0.145,0.074,0.071
        - 0.204,0.04,0.158,0.003,0.511,0.003,0.605,0.014,0.555,0.059,0.434,0.04,0.363,0.038
      threshold: 35
      contour_area: 10
      improve_contrast: true

  Dahua_2_HiRes:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://127.0.0.1:8554/Dahua_2_HiRes?video=copy&audio=aac
          input_args: preset-rtsp-restream      
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dahua_2_LowRes?video=copy&audio=aac
          input_args: preset-rtsp-restream            
          roles:
            - record
    motion:
      mask:
        - 0.551,0.031,0.554,0.088,0.96,0.085,0.959,0.021
        - 0.647,0.161,0.796,0.249,0.85,0.292,0.929,0.355,0.999,0.429,0.997,0.488,0.945,0.455,0.873,0.386,0.844,0.334,0.646,0.209
        - 0.24,0.261,0.283,0.325,0.327,0.327,0.318,0.232,0.273,0.228
        - 0.526,0.424,0.44,0.426,0.431,0.362,0.525,0.285
        - 0.243,0.042,0.394,0.064,0.486,0.093,0.528,0.107,0.574,0.126,0.597,0.14,0.521,0.131,0.517,0.159,0.399,0.119,0.241,0.123
    live:
        stream_name: Dahua_2_HiRes
        
  Asecam_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Asecam_1_LowRes?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Asecam_1_HiRes?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask: 0.006,0.012,0.008,0.04,0.231,0.048,0.232,0.01
    
    live:
        stream_name: Asecam_2_HiRes
        
  Asecam_2_HiRes:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Asecam_2_LowRes?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Asecam_2_HiRes?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
        stream_name: Asecam_2_HiRes
    
    motion:
      mask:
        - 0.005,0.009,0.004,0.04,0.23,0.045,0.23,0.012
        - 0.029,0.144,0.021,0.313,0.199,0.3,0.25,0.12,0.191,0.125

      threshold: 35
      contour_area: 15
      improve_contrast: true
version: 0.15-1

camera_groups:
  FAK:
    order: 1
    icon: LuAirplay
    cameras: birdseye
```

### Relevant Frigate log output

```shell
no relevant logs
```

### Relevant go2rtc log output

```shell
2025-05-26 19:31:58.501434502  [INFO] Preparing new go2rtc config...
2025-05-26 19:31:58.553406427  [INFO] Got IP address from supervisor: 192.168.137.226
2025-05-26 19:31:58.591788783  [INFO] Got WebRTC port from supervisor: 8555
2025-05-26 19:31:59.481828431  [INFO] Starting go2rtc...
2025-05-26 19:31:59.599676563  21:31:59.599 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-05-26 19:31:59.601507933  21:31:59.601 INF config path=/dev/shm/go2rtc.yaml
2025-05-26 19:31:59.602969247  21:31:59.602 INF [rtsp] listen addr=:8554
2025-05-26 19:31:59.603330628  21:31:59.602 INF [api] listen addr=:1984
2025-05-26 19:31:59.603861534  21:31:59.603 INF [webrtc] listen addr=:8555/tcp
2025-05-26 19:32:08.508050524  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
no docker
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/3e1547e7-2829-448a-b1c3-4c0254310aca" />
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/4653d1aa-5a2d-4846-9e5f-cab2a5e53bca" />
