### DISCUSSION TITLE
Regions sent to detector too large

### DISCUSSION THREAD

**Discussion by leon-Glitchking** [blakeblackshear/frigate#18438] [Camera Support] [answered]
Hello

Sorry if this has already been answered, I have tried searching the issues and discussion and could not get an answer.

I have a doorbell camera with a wide-angle lens, and I’m have trouble getting the detection to work on it. The stream size is 896x672 and I’m using a google coral.

I am having an issue where the “Region” (in debug mode view) is much larger than the motion detection box. And I think what is happening is the people coming down the driveway are too small for the tpu to detect as they are only making up about 10-20% of the Region box.

how do I “tighten” up the region sent to the detector so its is a similar size to the motion box?

Thank you

### Version

System 0.15.0-cea210d

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.6

cameras:
  doorbell:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    motion:
      mask: 0,0,1,0,0.992,0.306,0.338,0.211,0,0.27
      threshold: 25
      contour_area: 40
      improve_contrast: true

version: 0.15-1
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":2560,"height":1920,"avg_frame_rate":"20/1"},{"codec_long_name":"AAC (Advanced Audio Coding)","avg_frame_rate":"0/0"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"stream_groups":[],"streams":[{"codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10","width":896,"height":672,"avg_frame_rate":"20/1"},{"codec_long_name":"AAC (Advanced Audio Coding)","avg_frame_rate":"0/0"}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell PoE

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/66552667-34ce-4de8-81d8-8aba70c22c47)

**Comment by leon-Glitchking** [comment]
Here are some examples

![image](https://github.com/user-attachments/assets/4f3ca381-24b2-4980-8444-d619f758f7e8) ![image](https://github.com/user-attachments/assets/1ae48731-fe83-414a-ac86-533150b082c8)

**Comment by hawkeye217** [comment]
This is expected behavior. A region is different than a bounding box. See the documentation: https://docs.frigate.video/frigate/camera_setup/#choosing-a-detect-resolution

**Reply by leon-Glitchking** [reply]
I'm sorry I still think I'm missing something.

I have read through all the documentation multiple times and cannot figure out how to get the detection better. In both of the examples above and more even clearer ones I cannot get a detection. Only if I'm right up close to the camera taking up most of the shot.

I have tried playing with all the settings I can see and still cannot get a consistent detection day or night.

I am even using the frigare+ model and still not getting anything.
This is happening on  all my cameras, but the doorbell is the worst.

Is there something I am missing?

How can I improve detection?

**Reply by hawkeye217** [reply]
What is your full config file? What you pasted above isn't using Frigate+.

**Reply by NickM-27** [reply]
You need to remove your object filters

**Reply by leon-Glitchking** [reply]
Sorry here is the Full config, i thought i would only supply the bit i thought were relivent.

Is it the filters part im getting the issue from?

```
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.6
```

Full Config
```
database:
  path: /config/frigate.db

mqtt:
  enabled: true
  host: IP
  port: 1883
  topic_prefix: frigate
  client_id: REDACTED
  user: REDACTED
  password: REDACTED
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://c241fae21de50ecf6c0f2a63769dcacd

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  enabled: true
  mode: continuous
  restream: true

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: active_objects

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.6

detect:
  fps: 5
  enabled: True
  min_initialized: 2

snapshots:
  enabled: true
  crop: false
  retain:
    default: 20
    objects:
      person: 30
  quality: 70

review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - person

go2rtc:
  webrtc:
    candidates:
      - IP:8555
      - stun:8555
  rtsp:
    listen: :8554

  streams:
    doorbell:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
      - rtsp://REDACTED:REDACTED@192.168.1.20:554/Preview_01_sub
    doorbell_sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED
    backyard:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
    backyard_sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED
    house_side:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
    house_side_sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED
    frontyard:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=REDACTED&password=REDACTED#video=copy#audio=copy#audio=opus
    frontyard_sub:
      - ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=REDACTED&password=REDACTED
    drivewayandlights:
      - rtsp://REDACTED:REDACTED@IP:554/Preview_01_main
      - ffmpeg:camera_terras#video=h264#hardware#audio=opus
    drivewayandlights_sub:
      - rtsp://REDACTED:REDACTED@IP:554/Preview_01_sub
    patio:
      - rtsp://REDACTED:REDACTED@IP:554/Preview_01_main
      - ffmpeg:camera_terras#video=h264#hardware#audio=opus
    patio_sub:
      - rtsp://REDACTED:REDACTED@IP:554/Preview_01_sub

cameras:

  doorbell:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0,1,0,0.992,0.306,0.338,0.211,0,0.27
      threshold: 25
      contour_area: 40
      improve_contrast: true

  patio:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 35
      contour_area: 67
      improve_contrast: true
      mask: 0.579,0.929,0.581,0.977,0.996,0.976,0.993,0.923

  drivewayandlights:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drivewayandlights
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drivewayandlights_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 20
      improve_contrast: true
      mask: 
        0.069,0.511,0.246,0.307,0.47,0.25,0.482,0.218,0.59,0.227,0.602,0.273,0.66,0.248,1,0.72,1,0,0,0,0.002,0.401,0.047,0.414
    objects:
      filters:
        person:
          mask: 0.661,0.245,0.995,0.68,0.998,0.013,0.669,0

  backyard:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,0.242,0.304,0.093,0.488,0.079,0.61,0.066,0.687,0.114,1,0.206,1,0,0,0
      threshold: 44
      contour_area: 43
      improve_contrast: true

  frontyard:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0,1,0.138,1,0.045,0.511,0.08,0.203,0.541,0.223,1,0.275,1,0,0,0
      threshold: 30
      contour_area: 25
      improve_contrast: true

  house_side:
    enabled: true
    detect:
      enabled: true
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/house_side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/house_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 18
      improve_contrast: true
      mask: 
        0.144,0.152,0.268,0.091,0.263,0.064,0.436,0.058,1,0.126,1,0,0,0,0,0.062,0.066,0.062,0.098,0.06,0.128,0.067
    objects:
      track:
        - person

version: 0.15-1
camera_groups:
  Front:
    order: 2
    icon: LuCamera
    cameras:
      - doorbell
      - drivewayandlights
      - frontyard
      - house_side
semantic_search:
  enabled: true
  reindex: false
  model_size: large
```
