### DISCUSSION TITLE
[Config Support]: Specify buffer pre and post roll for manual storage trigger

### DISCUSSION THREAD

**Discussion by raindropworks** [blakeblackshear/frigate#18433] [Config Support] [answered]
### Describe the problem you are having

I'm hoping I got the right forum, if not just let me know. I know this may be something of an edge case, but I have a multi-camera setup providing ~250 degree coverage on a residential building, and as I'm building out Frigate, I'm wanting to put in an MQTT capability to trigger a manual recording (would be called from Home Assistant) that would save the last 30 seconds of all three cameras as well as the following 5 minutes. This way if something happens that the resident is concerned about, but may be outside the normal detection settings (too far away, false negative, what have you) there is still an override to get documentation.

I think there used to be options for forcing a specific pre-save on the record buffer without doing a 24/7 recording, but they may have been depreciated/removed.

Please keep in mind the current config is before I've set up detection or anything because I wanted the manual system working before I try to make it 'smart'. Also, all cameras are being fed to a MediaMTX server, hence why everything shares same IP

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: 127.0.0.1
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  midland_b_front: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.95:8554/front_b_detect # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://10.0.0.95:8554/front_b_record # <----- The stream you want to use for recording
          roles:
            - record
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record:
      enabled: false

  midland_b_cul_de_sac: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.95:8554/cul_de_sac_detect # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://10.0.0.95:8554/cul_de_sac_record # <----- The stream you want to use for recording
          roles:
            - record
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record:
      enabled: false

  midland_b_parking: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.95:8554/parking_b_detect # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://10.0.0.95:8554/parking_b_record # <----- The stream you want to use for recording
          roles:
            - record
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record:
      enabled: false
version: 0.15-1
```

### Relevant Frigate log output

```shell
n/a
```

### Relevant go2rtc log output

```shell
n/a
```

### Frigate stats

```json
{
  "cameras": {
    "midland_b_front": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 0,
      "detection_enabled": false,
      "pid": 552,
      "capture_pid": 575,
      "ffmpeg_pid": 584,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "midland_b_cul_de_sac": {
      "camera_fps": 5,
      "process_fps": 5,
      "skipped_fps": 0,
      "detection_fps": 0,
      "detection_enabled": false,
      "pid": 561,
      "capture_pid": 598,
      "ffmpeg_pid": 605,
      "audio_rms": 0,
      "audio_dBFS": 0
    },
    "midland_b_parking": {
      "camera_fps": 5.1,
      "process_fps": 5.1,
      "skipped_fps": 0,
      "detection_fps": 0,
      "detection_enabled": false,
      "pid": 565,
      "capture_pid": 604,
      "ffmpeg_pid": 620,
      "audio_rms": 0,
      "audio_dBFS": 0
    }
  },
  "detectors": {
    "coral": {
      "inference_speed": 10,
      "detection_start": 0,
      "pid": 518
    }
  },
  "detection_fps": 0,
  "gpu_usages": {
    "intel-vaapi": {
      "gpu": "0.63%",
      "mem": "-%"
    }
  },
  "cpu_usages": {
    "frigate.full_system": {
      "cpu": "5.0",
      "mem": "36.7"
    },
    "1": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service"
    },
    "15": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6-linux-init-shutdownd"
    },
    "16": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
    },
    "24": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-fdholder"
    },
    "25": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc"
    },
    "26": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync"
    },
    "27": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-healthcheck"
    },
    "28": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate"
    },
    "29": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx"
    },
    "30": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise frigate-log"
    },
    "31": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise s6rc-oneshot-runner"
    },
    "32": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise go2rtc-log"
    },
    "33": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise certsync-log"
    },
    "34": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-supervise nginx-log"
    },
    "45": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
    },
    "46": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
    },
    "86": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
    },
    "88": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
    },
    "89": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
    },
    "90": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"
    },
    "98": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
    },
    "104": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user go2rtc-healthcheck"
    },
    "109": {
      "cpu": "4.7",
      "cpu_average": "4",
      "mem": "3.7",
      "cmdline": "python3 -u -m frigate"
    },
    "129": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "nginx: master process nginx"
    },
    "166": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "167": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "168": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "256": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: worker process"
    },
    "257": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.1",
      "cmdline": "nginx: cache manager process"
    },
    "323": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "bash ./run.user certsync"
    },
    "502": {
      "cpu": "0.5",
      "cpu_average": "0",
      "mem": "2.2",
      "cmdline": "frigate.recording_manager"
    },
    "511": {
      "cpu": "0.9",
      "cpu_average": "0",
      "mem": "2.1",
      "cmdline": "frigate.review_segment_manager"
    },
    "518": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "2.3",
      "cmdline": "frigate.detector.coral"
    },
    "537": {
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "2.3",
      "cmdline": "frigate.output       "
    },
    "551": {
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.4",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "552": {
      "cpu": "3.1",
      "cpu_average": "2",
      "mem": "2.2",
      "cmdline": "frigate.process:midland_b_front"
    },
    "561": {
      "cpu": "3.3",
      "cpu_average": "3",
      "mem": "2.2",
      "cmdline": "frigate.process:midland_b_cul_de_sac"
    },
    "563": {
      "cpu": "0.1",
      "cpu_average": "0",
      "mem": "0.4",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "565": {
      "cpu": "3.2",
      "cpu_average": "2",
      "mem": "2.2",
      "cmdline": "frigate.process:midland_b_parking"
    },
    "575": {
      "cpu": "1.0",
      "cpu_average": "0",
      "mem": "2.1",
      "cmdline": "frigate.capture:midland_b_front"
    },
    "578": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.4",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x360 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "584": {
      "cpu": "2.0",
      "cpu_average": "1",
      "mem": "0.5",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.0.95:8554/front_b_detect -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "598": {
      "cpu": "1.0",
      "cpu_average": "0",
      "mem": "2.1",
      "cmdline": "frigate.capture:midland_b_cul_de_sac"
    },
    "604": {
      "cpu": "1.0",
      "cpu_average": "0",
      "mem": "2.1",
      "cmdline": "frigate.capture:midland_b_parking"
    },
    "605": {
      "cpu": "2.2",
      "cpu_average": "1",
      "mem": "0.5",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.0.95:8554/cul_de_sac_detect -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "606": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
    },
    "620": {
      "cpu": "2.3",
      "cpu_average": "1",
      "mem": "0.5",
      "cmdline": "/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.15.0-6cb5cfb -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://10.0.0.95:8554/parking_b_detect -r 5 -vf fps=5,scale_vaapi=w=640:h=360,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
    },
    "30468": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 60"
    },
    "30492": {
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0",
      "cmdline": "sleep 30s"
    }
  },
  "service": {
    "uptime": 34672,
    "version": "0.15.0-6cb5cfb",
    "latest_version": "0.15.1",
    "storage": {
      "/media/frigate/recordings": {
        "total": 60358.8,
        "used": 1055.2,
        "free": 56205.8,
        "mount_type": "ext4"
      },
      "/media/frigate/clips": {
        "total": 60358.8,
        "used": 1055.2,
        "free": 56205.8,
        "mount_type": "ext4"
      },
      "/tmp/cache": {
        "total": 953.7,
        "used": 0.1,
        "free": 953.6,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 512,
        "used": 51.6,
        "free": 460.4,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {

    },
    "last_updated": 1748372159
  },
  "processes": {
    "recording": {
      "pid": 502
    },
    "review_segment": {
      "pid": 511
    },
    "go2rtc": {
      "pid": 98
    }
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
#      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/heatheriac/docker-frigate:/config
      - /home/heatheriac/frigate-clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
#      - "8554:8554" # RTSP feeds
#      - "8555:8555/tcp" # WebRTC over tcp
#      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "MASKED"
```

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a00c2743-680a-41a5-9361-202ba8966f0e)

**Comment by NickM-27** [comment]
> I think there used to be options for forcing a specific pre-save on the record buffer without doing a 24/7 recording,

This only ever existed for events (now review items).

As long as you set a pre_capture of 30 seconds to alerts then using the manual event API (http, not MQTT) will allow for achieving what you want.

**Reply by raindropworks** [reply]
Okay, so what would be the proper process then for meshing this in with detection? Since I don't necessarily need the pre capture on a car driving by and definitely not five minutes post capture

**Reply by NickM-27** [reply]
for pre capture you will just need to accept that this is how it works for anything you classify as an alert. If you have required_zones for alerts then the car just driving by would be a detection which has a separate pre capture. 

For post capture you should not configure that, just set the duration of the manual event API to 5 minutes

**Reply by raindropworks** [reply]
I mostly get it. Sorry, I'm still new to frigate so I'm still working out the syntax and everything

**Comment by raindropworks** [comment, marked as answer]
Okay, so it took me a long time, a lot of trial and error, but finally got the system doing what I was looking for. It turned out chasing the idea of Frigate 'starting' the recording was the wrong move to begin with. I'm noting this here for future people who may want the same thing. At the core, what I needed was the export API, and figuring out how to wrap it into HA, since the docs weren't too clear to me on some of the formatting.

My build now has extra ram, so I pointed /media/frigate to a 3gb tmpfs mount (can buffer my 3 cameras for about 12 hours each). That introduces some other issues with restarts confusing Frigate's database when files get deleted, so I'd recommend avoiding that unless you're ready to muck with some sql cleaners to clean up the recording database. Here is the snip of the global record settings I used in Frigate:

```
record:
  retain:
    days: 10 # <----- How many days to keep recordings
    mode: all # <----- Keep all recordings
  enabled: true
  alerts:
    pre_capture: 5 # <----- How many seconds to record before the event starts
    retain:
      mode: all # <----- Keep all recordings

```
Beyond that, in HA, I have two number helpers (set for a range of 0 to 9999999999) for start time and end time (frigate will use Unix Epoch timestamps, so I prefer setting them now). Mine are called emergency_event_start_epoch and emergency_event_end_epoch.

A rest command needed to be added to Home Assistant's configuration.yaml, formatted like this (replace 10.0.0.95:5000 with your Frigate's IP and local API port):
```
rest_command:
  frigate_export_event:
    url: "http://10.0.0.95:5000/api/export/{{ camera }}/start/{{ start_time }}/end/{{ end_time }}"
    method: POST
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    payload: >
      {
        "playback": "realtime",
        "source": "recordings"
      }
 ```
 
 Then the following automations as a template (I have a binary toggle I also added for conditional cards in the dashboard, but that's outside the scope of this)
 
 Start:
 ```
alias: Emergency Recording Start
description: ""
triggers:
  - entity_id: input_boolean.camera_emergency_recording
    to: "on"
    trigger: state
actions:
  - target:
      entity_id: input_number.emergency_event_start_epoch
    data:
      value: "{{ (as_timestamp(now()) - 30) | int }}"
    action: input_number.set_value
mode: single
```

Stop (replace each camera in the 'for each' section with the exact camera name from Frigate's config.yml):
```
alias: Emergency Recording Stop
description: ""
triggers:
  - entity_id: input_boolean.camera_emergency_recording
    to: "off"
    trigger: state
actions:
  - target:
      entity_id: input_number.emergency_event_end_epoch
    data:
      value: "{{ (as_timestamp(now())) | int }}"
    action: input_number.set_value
  - repeat:
      for_each:
        - camera a
        - camera_b
        - camera_c
      sequence:
        - data:
            camera: "{{ repeat.item }}"
            start_time: "{{ states('input_number.emergency_event_start_epoch') | int }}"
            end_time: "{{ states('input_number.emergency_event_end_epoch') | int }}"
          action: rest_command.frigate_export_event
mode: single
```

The use would be:
1) Run the 'start' script. HA saves the time 30 seconds in the past
2) Run the 'end' script when done. HA saves the current time
3) HA calls Frigate through the API for each camera and says 'export all video between these two timestamps'
4) Frigate saves the videos in the export folder, just like if you exported from it's dashboard.
