### DISCUSSION TITLE
[Detector Support]: 0.15.1 -> 0.16.0-beta2 fails to train yolov7x-320 with "Could not find any implementation for node 001_convolutional + 001_convolutional_bn"

### DISCUSSION THREAD

**Discussion by aik** [blakeblackshear/frigate#18442] [Detector Support] [answered]
### Describe the problem you are having

Replaced   image: ghcr.io/blakeblackshear/frigate:stable-tensorrt     with
 image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2-tensorrt
in my docker-compose.yaml , restarted and it did not start. Wonder why.

### Version

0.16.0-1fa7ce5

### Frigate config file

```yaml
logger:
  default: debug
ui:
  time_format: 24hour
mqtt:
  enabled: true
  host: hass
detectors:
  tensorrt:
    type: tensorrt
model:
  path: /config/model_cache/tensorrt/yolov7x-320.trt
  labelmap_path: /labelmap/coco-80.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    driveway:
      - rtsp://shitcam:554/user=admin&password=&channel=&stream=.sdp?real_stream--rtp-caching=100
      - "ffmpeg:driveway#audio=aac"
      - isapi://admin@shitcam:80/ # <- for two-way audio
ffmpeg:
  hwaccel_args: preset-nvidia

cameras:
  driveway:
    enabled: true
    audio:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
caching=100
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: shitcam
      port: 8899
      user: admin
      password: admin
    detect:
      enabled: true
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
    zones:
      frontdoor_zone:
        coordinates: 0.753,0.174,0.91,0.174,0.905,0.518,0.745,0.516
        loitering_time: 0
      driveway_zone:
        coordinates: 0.925,0.962,0.933,0.523,0.295,0.199,0.165,0.864
        loitering_time: 0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 15s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2-tensorrt
#    runtime: nvidia
    environment:
      - FRIGATE_RTSP_PASSWORD="password"
      - YOLO_MODELS=yolov7x-320
#      - USE_FP16=false
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
    shm_size: "2048mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/aik/frigate/config:/config
      - /mnt/hdd4/home/aik/frigate_storage:/media/frigate
      - /mnt/hdd4/home/aik/frigate_model_cache:/config/model_cache
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant Frigate log output

```shell
aik@srv ~/frigate> docker-compose -f docker-compose-aik.yaml rm -f ; docker-compose -f docker-compose-aik.yaml up
Going to remove frigate
Removing frigate ... done
Creating frigate ... done
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service trt-model-prepare: starting
frigate    | s6-rc: info: service prepare: starting
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | Generating the following TRT Models: yolov7x-320
frigate    | Downloading yolo weights
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service certsync-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service certsync-log successfully started
frigate    | s6-rc: info: service prepare successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | 2025-05-28 21:19:48.806571308  [INFO] Preparing new go2rtc config...
frigate    | 2025-05-28 21:19:49.166426559  [INFO] Starting go2rtc...
frigate    | 2025-05-28 21:19:49.237726589  21:19:49.237 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
frigate    | 2025-05-28 21:19:49.237766626  21:19:49.237 INF config path=/dev/shm/go2rtc.yaml
frigate    | 2025-05-28 21:19:49.238188824  21:19:49.238 INF [api] listen addr=:1984
frigate    | 2025-05-28 21:19:49.238265762  21:19:49.238 INF [rtsp] listen addr=:8554
frigate    | 2025-05-28 21:19:49.238651250  21:19:49.238 INF [webrtc] listen addr=:8555
frigate    |
frigate    | Creating yolov7x-320.cfg and yolov7x-320.weights
frigate    |
frigate    | Done.
frigate    | 2025-05-28 21:19:58.431053260  [INFO] Starting go2rtc healthcheck service...
frigate    |
frigate    | Generating yolov7x-320.trt. This may take a few minutes.
frigate    |
frigate    | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:149: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
frigate    |   builder.max_batch_size = MAX_BATCH_SIZE
frigate    | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:151: DeprecationWarning: Use set_memory_pool_limit instead.
frigate    |   config.max_workspace_size = 1 << 30
frigate    | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:174: DeprecationWarning: Use build_serialized_network instead.
frigate    |   engine = builder.build_engine(network, config)
frigate    | ERROR: failed to build the TensorRT engine!
frigate    | [05/28/2025-21:21:30] [TRT] [W] TensorRT was linked against cuDNN 8.9.0 but loaded cuDNN 8.6.0
frigate    | [05/28/2025-21:21:30] [TRT] [E] 10: Could not find any implementation for node 001_convolutional + 001_convolutional_bn.
frigate    | [05/28/2025-21:21:30] [TRT] [E] 10: [optimizer.cpp::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node 001_convolutional + 001_co
nvolutional_bn.)
frigate    | Loading the ONNX file...
frigate    | Adding yolo_layer plugins.
frigate    | Adding a concatenated output as "detections".
frigate    | Naming the input tensort as "input".
frigate    | Building the TensorRT engine.  This would take a while...
frigate    | (Use "--verbose" or "-v" to enable verbose logging.)
frigate    | Available tensorrt models:
frigate    | ls: cannot access '*.trt': No such file or directory
frigate    | s6-rc: warning: unable to start service trt-model-prepare: command exited 2

^CGracefully stopping... (press Ctrl+C again to force)
Stopping frigate ... done
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

none

### Any other information that may be helpful

Intel i5-4670, Ubuntu 24.04.2 LTS, NVIDIA Corporation GM204 [GeForce GTX 970].
I tried
```
cd /usr/local/src/tensorrt_demos/yolo
python3 yolo_to_onnx.py -m yolov7x-320
```
seems fine, here is the [yolo.txt](https://github.com/user-attachments/files/20481836/yolo.txt)
so something fails later on.

**Comment by NickM-27** [comment]
Interesting, can you show nvidia smi for this hardware?

**Comment by aik** [comment]
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.144                Driver Version: 570.144        CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 970         Off |   00000000:01:00.0 Off |                  N/A |
| 50%   33C    P2             52W /  200W |    1771MiB /   4096MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A          154533      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          138MiB |
|    0   N/A  N/A          154542      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          134MiB |
|    0   N/A  N/A          154551      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          134MiB |
|    0   N/A  N/A          154560      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          195MiB |
|    0   N/A  N/A          154564      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          148MiB |
|    0   N/A  N/A          154570      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg           83MiB |
|    0   N/A  N/A          154580      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg           91MiB |
|    0   N/A  N/A          154589      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          124MiB |
|    0   N/A  N/A          154599      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          316MiB |
|    0   N/A  N/A          154603      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          212MiB |
|    0   N/A  N/A          154609      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg           83MiB |
|    0   N/A  N/A         4119923      G   /usr/lib/xorg/Xorg                       66MiB |
|    0   N/A  N/A         4120129      G   /usr/bin/gnome-shell                      9MiB |
|    0   N/A  N/A         4126796      G   /usr/bin/gnome-control-center            14MiB |
+-----------------------------------------------------------------------------------------+
```
and there was cuda detector too in 0.15.

**Reply by NickM-27** [reply]
Interesting, the slightly newer version shouldn't be affecting older hardware, many users have confirmed this is working. I would probably suggesting using the onnx detector perhaps with yolov9 model and see if that works.

**Reply by aik** [reply]
Cannot figure out how to run onnx on nvidia, tensorrt was somewhat easier :-/
```
detectors:                            
  onnx:                               
    type: onnx                        
model:                                
  path: frigate-fp16-yolov9-t         
  model_type: yolo-generic            
  width: 320                          
  height: 320                         
  input_tensor: nhwc                  
  input_dtype: float                  
  labelmap_path: /labelmap/coco-80.txt
```
not working, any hints? :)

**Reply by NickM-27** [reply]
you need to generate the model, you can generate yolov7 to keep using the same model or follow yolov9 instructions for a potentially better model

https://deploy-preview-16390--frigate-docs.netlify.app/configuration/object_detectors#downloading-yolo-models

**Reply by aik** [reply]
the yolo9 downloading guide does not work on both fedora40 and ubuntu2404 :-/
```
aik@srv:~/hass/yolov9$ bin/pip install onnx-simplifier>=0.4.1                                             
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix
 your #egg=onnx-simplifier fragments.                                                                     
...
 error: subprocess-exited-with-error                                                                     
                                                                                                         
 × Preparing metadata (pyproject.toml) did not run successfully.                                         
 │ exit code: 1                                                                                          
 ╰─> [34 lines of output]                                                                                
     <string>:26: DeprecationWarning: Use shutil.which instead of find_executable                        
     fatal: not a git repository (or any of the parent directories): .git                                
     fatal: not a git repository (or any of the parent directories): .git                                
...
        File "/tmp/pip-build-env-lbpwuwv_/overlay/lib/python3.13/site-packages/setuptools/_vendor/packaging/version.py", line 202, in __init__
          raise InvalidVersion(f"Invalid version: {version!r}")
      packaging.version.InvalidVersion: Invalid version: 'unknown'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```
google says to install cmake, gcc-9, etc, nothing helps.
oh well, okay, let's try the yolov7x intructions from the same page, got the onnx model, trying as:
```
detectors:
  onnx_0:
    type: onnx
model:
  model_type: yolo-generic
  path: /config/model_cache/yolov7x-320.onnx
  labelmap_path: /labelmap/coco-80.txt
  input_tensor: nchw
  input_dtype: float
  width: 320
  height: 320
```
fails with:
```
frigate    | 2025-05-29 00:41:22.034381684  onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /config/model_cache/yolov7x-320.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:180 onnxruntime::Model::Model(onnx::ModelProto&&, const onnxruntime::PathString&, const onnxruntime::IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsup
ported model IR version: 11, max supported IR version: 10                                                                                            
```
uff. okay, hacked yolo_to_onnx.py to `yolo_model_def.ir_version = 10`, now the error is:
```
frigate    | 2025-05-29 00:48:52.976844546  onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /config/model_cache/yolov7x-320.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::__cxx11::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const std::string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 23 is under development and support for this is  limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 21.                                                                      
```
/me wants to cry :-(

**Reply by NickM-27** [reply]
The yolov9 error is likely because you're using python 3.12, 3.11 or earlier needs to be used. 

regarding your second model attempt, that is likely just because a newer onnx version is used or perhaps the opset version is not set. That should also be fixable, but it appears this GPU may generally be at the edge of supportability since converting to trt is also not working with the built in script. If this is concerned to be the case we will update the release notes, but I would expect that the onnx model should work.

**Reply by aik** [reply]
uff. changed the default from 3.12 to 3.11....
```
aik@srv:~/hass/yolov9$ python3 --version                                                                                                
Python 3.11.12                                                                                                                          
aik@srv:~/hass/yolov9$ python3 -m venv ./                                                                                               
Error: Command '['/home/aik/hass/yolov9/bin/python3', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
true that GPU is old but still capable for home cameras...

**Reply by NickM-27** [reply]
that would presumably be some system issue, no reason that creating a venv should fail

**Reply by aik** [reply]
with 3.11 by default,  yolo_to_onnx.py fails: `AttributeError: module 'numpy' has no attribute 'product'`...
and yeah, needed to install python3.11-venv, python3.11-dev, pycuda, nvidia toolkit (for cuda.h) and million of other things....

while I am doing this - is there a chance that fixing tensorrt starting scripg is more feasible? :-)

**Reply by NickM-27** [reply]
> with 3.11 by default, yolo_to_onnx.py fails: AttributeError: module 'numpy' has no attribute 'product'...

I have run this on debian bookworm so I know it works with python 3.11, not sure why it would have this issue, unless the requirements.txt was not installed or something

> while I am doing this - is there a chance that fixing tensorrt starting scripg is more feasible? :-)

possibly, though due to the script working correctly for other users I don't know if it is an env issue with the older GPU or something that would be solvable

**Reply by aik** [reply]
"TensorRT was linked against cuDNN 8.9.0 but loaded cuDNN 8.6.0" seems to be a good place to start. It is a learning curve :-/

**Reply by aik** [reply]
one step back. Remove everything, create a new container and everything. Start, bash into the container, manually run `yolo_to_onnx.py`, then `cp yolov7x-320.onnx /config/model_cache/onnx/` and start frigate16 with:
```
detectors:
  onnx_0:
    type: onnx
model:
  model_type: yolo-generic
  path: /config/model_cache/onnx/yolov7x-320.onnx
  labelmap_path: /labelmap/coco-80.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```
Is the above - correct syntax?

Then I get a bunch of warnings like this:
`frigate16  | 2025-05-29 10:37:21.941550971  2025-05-29 10:37:21.941490855 [W:onnxruntime:, graph.cc:1348 Graph] Initializer 001_convolutional_bn_scale appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.` and then it gives up and shuts down after:
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))`.

When I try the same with frigate15 - I get exact same errors so I am guessing I am not doing ONNX right in the first place, what do I miss?

**Reply by NickM-27** [reply]
You are just missing input_dtype: float

**Reply by aik** [reply, marked as answer]
Uff. 0.15 failed like this (`model_type: yolonas` as there is no `yolo-generic` in 0.15):
```
[2025-05-29 11:31:41] frigate.detectors.plugins.onnx INFO    : ONNX: /config/model_cache/onnx/yolov7x-320.onnx loaded
Process detector:onnx_0:                                                                                             
Traceback (most recent call last):                                                                                   
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap                                      
    self.run()                                                                                                       
  File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper                                               
    return run(*args, **kwargs)                                                                                      
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run                                             
    self._target(*self._args, **self._kwargs)                                                                        
  File "/opt/frigate/frigate/object_detection.py", line 145, in run_detector                                         
    detections = object_detector.detect_raw(input_frame)                                                             
  File "/opt/frigate/frigate/object_detection.py", line 95, in detect_raw                                            
    return self.detect_api.detect_raw(tensor_input=tensor_input)                                                     
  File "/opt/frigate/frigate/detectors/plugins/onnx.py", line 69, in detect_raw                                      
    (_, x_min, y_min, x_max, y_max, confidence, class_id) = prediction                                               
ValueError: too many values to unpack (expected 7)                                                                   
```
but I finally got 0.16 going with:
```
detectors:                                            
  onnx_0:                                             
    type: onnx                                        
model:
  model_type: yolo-generic
  path: /config/model_cache/onnx/yolov7x-320.onnx
  labelmap_path: /labelmap/coco-80.txt
  input_dtype: float
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.144                Driver Version: 570.144        CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 970         Off |   00000000:01:00.0 Off |                  N/A |
| 50%   45C    P2             54W /  200W |    2294MiB /   4096MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A          781383      C   frigate.detector.onnx_0                 593MiB |
|    0   N/A  N/A          781587      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          138MiB |
|    0   N/A  N/A          781596      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          128MiB |
|    0   N/A  N/A          781607      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          124MiB |
|    0   N/A  N/A          781617      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          195MiB |
|    0   N/A  N/A          781621      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          148MiB |
|    0   N/A  N/A          781628      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg           83MiB |
|    0   N/A  N/A          781638      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg           98MiB |
|    0   N/A  N/A          781647      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          128MiB |
|    0   N/A  N/A          781656      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          249MiB |
|    0   N/A  N/A          781660      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg          212MiB |
|    0   N/A  N/A          781666      C   /usr/lib/ffmpeg/7.0/bin/ffmpeg           84MiB |
|    0   N/A  N/A         4119923      G   /usr/lib/xorg/Xorg                       66MiB |
|    0   N/A  N/A         4120129      G   /usr/bin/gnome-shell                      9MiB |
|    0   N/A  N/A         4126796      G   /usr/bin/gnome-control-center            16MiB |
+-----------------------------------------------------------------------------------------+
```
thanks for the help! and the patience :)

ps. the original tensorrt config worked just fine on my laptop with `GeForce GTX 1650 Mobile` but copying trt from there to the old machine did not work as `The engine plan file is generated on an incompatible device, expecting compute 5.2 got compute 7.5, please rebuild.` which was expected, I guess.
