### DISCUSSION TITLE
Aspect ratio has changed due to my restreaming - how to fix?

### DISCUSSION THREAD

**Discussion by ElectronicBattle** [blakeblackshear/frigate#18449] [Config Support] [answered]
### Describe the problem you are having

I used Frigate AI to help me make one (`main`) rather than two (`main` and `sub`) connections to my doorbell; I then restreamed so that the record (`main`) was 1536x1536 as usual but the restreamed sub was 720x720. It works but now my Birdseye grid looks like this:

![image](https://github.com/user-attachments/assets/a200927c-2fec-4f69-9bf0-62e2e5fa7ef8)

rather than this:

![image](https://github.com/user-attachments/assets/7800a084-2ebb-40a3-8025-c115990d9858)

You can see that the ninth image, the doorbell, has reverted to the square 1536x1536 format due to my Frigate yaml changes, which are:

```
go2rtc:
doorbell_main: # 101 is HD & 102 is SD 
       - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.192:554/Streaming/Channels/101#video=h264#audio=copy#raw=-vf "split=2[main][sub];[main]lenscorrection=k1=-0.6:k2=0.2[corrected_main];[sub]crop=150:25:1300:1300,lenscorrection=k1=-0.6:k2=0.2[cropped];[corrected_main][cropped]overlay=0:5"
       - ffmpeg:doorbell_sub#audio=opus #admin:QXQODG
    
doorbell_sub:
        - "ffmpeg:doorbell_main#video=h264#hardware"  # This will rescale and re-encode ADDED 280525
    
...
cameras:

doorbell:
    genai:
      enabled: false # <- enable GenAI for this camera true false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 720
      height: 720 
```
I can't see what I have done wrong - please can yu point me in the right direction?

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
go2rtc:
doorbell_main: # 101 is HD & 102 is SD 
       - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.192:554/Streaming/Channels/101#video=h264#audio=copy#raw=-vf "split=2[main][sub];[main]lenscorrection=k1=-0.6:k2=0.2[corrected_main];[sub]crop=150:25:1300:1300,lenscorrection=k1=-0.6:k2=0.2[cropped];[corrected_main][cropped]overlay=0:5"
       - ffmpeg:doorbell_sub#audio=opus #admin:QXQODG
    
doorbell_sub:
        - "ffmpeg:doorbell_main#video=h264#hardware"  # This will rescale and re-encode ADDED 280525
    
...
cameras:

doorbell:
    genai:
      enabled: false # <- enable GenAI for this camera true false
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 720
      height: 720
```

### Relevant Frigate log output

```shell
2025-05-28 18:21:00
watchdog.doorbell
Ffmpeg process crashed unexpectedly for doorbell.
error
2025-05-28 18:21:00
watchdog.doorbell
The following ffmpeg logs include the last 100 lines prior to exit.
error
2025-05-28 18:21:00
ffmpeg.doorbell.detect
[in#0 @ 0x557f40876cc0] Error opening input: Invalid data found when processing input
error
2025-05-28 18:21:00
ffmpeg.doorbell.detect
Error opening input file rtsp://127.0.0.1:8554/doorbell_sub.
error
2025-05-28 18:21:00
ffmpeg.doorbell.detect
Error opening input files: Invalid data found when processing input
```

### Relevant go2rtc log output

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

Coral
