### DISCUSSION TITLE
Understanding Re-streaming + Audio on streams

### DISCUSSION THREAD

**Discussion by jeeftor** [blakeblackshear/frigate#18448] [Ask A Question] [answered]
# Question:

I'm trying to better understand why what looks like similar setups isn't working as expected in Frigate/Go2RTC. I have 2 similar Anpviz/Hikvision cameras and one seems to be pushing Audio to Frigate Beta16 - 2 - and one doesn't.

### Backyard Frigate

`Stream View in Frigate`
<img width="212" alt="image" src="https://github.com/user-attachments/assets/28ddb875-330e-4119-b263-35780f33dc12" />

`Probe in frigate`
<img width="562" alt="image" src="https://github.com/user-attachments/assets/04caaade-6a3f-4d8c-b74f-b6e08a5071cb" />

`FFProbe of raw stream`

```
Input #0, rtsp, from 'rtsp://Operator:Password@192.168.1.181:554/Streaming/channels/101?transport=tcp&retry=5&timeout=3s#backchannel=0':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc), 4096x1840 [SAR 1:1 DAR 256:115], 20 fps, 10 tbr, 90k tbn, 20 tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```    

`go2rtc net`
<img width="902" alt="image" src="https://github.com/user-attachments/assets/cb75ec67-e560-4169-b334-605963408a01" />

### Garage Frigate

`Stream View in Frigate`
<img width="207" alt="image" src="https://github.com/user-attachments/assets/5e09f946-3b55-4f9a-a366-1deb6f838c6f" />

`Probe in frigate`
<img width="543" alt="image" src="https://github.com/user-attachments/assets/b085bf44-4261-46d0-9745-f6db05a68b21" />

`Raw ffprobe`

```
    Last message repeated 81 times
Input #0, rtsp, from 'rtsp://Operator:Password@192.168.1.195:554/stream0?retry=5&timeout=3s':
  Metadata:
    title           : RTSP/RTP stream from icamra ipc
  Duration: N/A, start: 0.048000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 2560x1440, 20 fps, 20 tbr, 90k tbn, 20 tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```    

`go2rtc net`

<img width="674" alt="image" src="https://github.com/user-attachments/assets/56d21ca5-989c-4bc0-86ed-6e39d66070dc" />

### Frigate Configuration

This is the relevant Go2RCT Configuration

```yaml
go2rtc:
  rtsp:
    default_query: video&audio  # Includes both video and audio streams by default when clients connect
    timeout: 30s

  rtmp:
    listen: :1935    # Default RTMP port

  webrtc:
    candidates:
      - 192.168.1.120:8555  # Use the external port for external access
      - stun:18555  # Update STUN to use the external port 
  streams:
    backyard_main: # https://github.com/AlexxIT/go2rtc#source-isapi
      - rtsp://Operator:Password@192.168.1.181:554/Streaming/channels/101?transport=tcp&retry=5&timeout=3s#backchannel=0
      - isapi://Operator:Password@192.168.1.181:80?retry=5&timeout=3s
    garage_main:      
      - rtsp://Operator:Password@192.168.1.195:554/stream0?retry=5&timeout=3s
      - isapi://Operatore:Password@192.168.1.181:8000?retry=5&timeout=3s
```

And here is the camera configs:

```yaml
cameras:

#-------[GARAGE]------#
#      ______         #
#     /|_||_\`.__     #
#    (   _    _ _\    #
#    =`-(_)--(_)-'    #
#---------------------#
  garage:
    genai:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record:  preset-record-generic-audio-aac
      inputs:
        - path: rtsp://localhost:8554/garage_main # 2560, 1440
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - face
        - dog
        - car
        - frisbee
        - bicycle
        - waste_bin


#--------------------#
#      _.(-)._       #           
#    .'  back   '.   #               
#   /    yard     \  #                
#   |'-...___...-'|  #                
#    \    '='    /   #               
#     `'._____.'`    #              
#      /   |   \     #             
#     /.--'|'--.\    #              
#  []/'-.__|__.-'\[] #                 
#          |         #         
#         []         #
  backyard:
    genai:
      enabled: false
    # onvif:
    #   host: 192.168.1.181
    #   port: 80
    #   user: Onvifuser
    #   password: Onvifpass

    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://localhost:8554/backyard_main
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
            - detect
    audio:
      enabled: true
    live:
      streams:
        backyard_main: backyard_main
    detect:
      width: 1920
      height: 864
      fps: 5
    objects:
      track:
        # People
        - person
        - face
        # Vehicles
        - bicycle
        # Delivery
        # Animals
        - dog
        - cat
        - deer
        - bird
        - racoon
        - fox
        - bear
        - squirrel
        - rabbit
        # Other
        - bbq_grill
        - umbrella
        - waste_bin
    motion:
      mask:
        - 0.001,0.995,0.174,0.997,0.111,0.835,0.086,0.736,0.01,0.55,0.141,0.372,0.241,0.233,0.37,0.102,0.368,0.004,0,0
        - 0.725,0,0.822,0.221,0.918,0.519,0.898,0.577,0.927,0.672,0.948,0.738,0.838,0.996,1,0.997,1,0
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Deck_Area:
        coordinates: 
          0.086,0.736,0.185,0.532,0.346,0.572,0.357,0.537,0.685,0.538,0.779,0.489,0.798,0.466,0.916,0.702,0.816,0.942,0.817,0.996,0.182,0.997,0.098,0.805
        loitering_time: 0
      StupidNeighbors:
        coordinates: 0.01,0.55,0.047,0.64,0.094,0.558,0.059,0.435
        loitering_time: 0
        objects: person
    review:
      alerts:
        enabled: true
        labels:
          - dog
          - cat
          - deer
          - racoon
          - fox
          - bear
          - squirrel
          - rabbit
        required_zones: []
```

Is there a better way to debug whats going on?

I've tweaked some of the presets: `preset-record-generic-audio-aac` for example and still I seem to end up with the same situation.

Tracking this down to the recorded files I see that the Garage recordings don't seem to have audio.

<img width="932" alt="image" src="https://github.com/user-attachments/assets/3d52ed14-7c4e-488a-a7b2-7e3e97172fab" />

<img width="972" alt="image" src="https://github.com/user-attachments/assets/188c2a99-2664-46cd-8d0b-308d1629b1a9" />

So thats interesting...

### Next Steps

- tweak audio settings on camera back to ulaw and see if that helps letting Go2RTC re-encode them to aac
