### DISCUSSION TITLE
New storage but missing recordings

### DISCUSSION THREAD

**Discussion by primski** [blakeblackshear/frigate#18478] [Ask A Question] [answered]
Hello, i have a weird issue I have not pinpointed yet, perhaps someone can share an idea

I bought a new ( cheap ) external SSD off aliexpress and i am not sure if it works or not ... it appears to but sometimes there are no recordings. i also updated frigate to 0.16.0 beta2

i found this in logs at the times of missing recordings, not sure if related or not ? 

`WARNING : Too many unprocessed recording segments in cache for front. This likely indicates an issue with the detect stream, keeping the 6 most recent segments out of 7 and discarding the rest...`

thanks

**Comment by banthungprong** [comment]
Please add you config and your logs completely. Much more easy to start helping.
The warning has nothing to do with your SSD.
And you should test your mounted SSD from your linux system not from "inside" of frigate.

**Comment by primski** [comment]
Drive appears to be working from my linux shell, i have mounted it in /etc/fstab, it has 1 4TB exfat parition

```
$ df -h
...
/dev/sdb1       3,9T  396G  3,5T  11% /mnt/external-ssd
```

I copied the frigate media folder on it and mounted is as volume to my frigate docker container
```

$ ls -la /mnt/external-ssd/frigate/media/
total 640
drwxrwxr-x 5 user user 131072 feb  1  2024 .
drwxrwxr-x 3 user user 131072 maj 27 18:12 ..
drwxrwxr-x 9 user user 131072 maj 30 12:39 clips
drwxrwxr-x 2 user user 131072 feb  1  2024 exports
drwxrwxr-x 7 user user 131072 maj 30 08:25 recordings
```
```

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2
    container_name: frigate-security
    volumes:
      - ./data/frigate/config:/config
      - /mnt/external-ssd/frigate/media:/media/frigate
...
```

But then after a while, maybe day or two max, i get the aforementioned error entry in my frigate logs and there are no more recordings

I haven't seen that error message before i put this drive in, so i figured maybe ( because it's cheap 20$ 4tb drive ) it doesn't work properly and frigate can't write anymore, thus the error message about cache full? i don't know what that means 

but my full frigate config is this:
```

logger:
  default: info

tls:
  enabled: false

mqtt:
  host: 10.0.23.11
  port: 15883

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - dog
    - cat
    - bird
    - horse
    - sheep
    - cow
    - bear

birdseye:
  enabled: true
  # width: 800
  width: 1280

  #height: 600
  quality: 10
  mode: continuous

cameras:
  front:
    ffmpeg:
      # new
      #output_args:
      #  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
      #    1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac

      # old
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://10.0.23.11:19554/front
          roles:
            - record
            - detect
        #- path: rtsp://10.0.23.11:19554/front_sub
        #- path: rtsp://10.0.23.11:19554/front
        #  roles:
        #    - detect

    detect:
      #width: 1280
      #height: 720
      #fps: 5
      width: 1920
      height: 1080
      fps: 2

    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 30
      detections:
        retain:
          days: 7
    motion:
      threshold: 26
      contour_area: 6
      improve_contrast: false
      mask: 0.766,0.045,0.77,0.099,0.998,0.099,0.995,0.04
    snapshots:
      enabled: true
      required_zones:
        - zone
      retain:
        default: 30

    zones:
      zone:
        coordinates: 0,0.186,0.32,0.009,1,0.22,1,0.407,1,1,0,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: zone
      detections:
        required_zones: zone
    objects: {}
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format
    yuv420p

go2rtc:
  streams:
    front: 
      ffmpeg:rtsp://admin:pass@10.0.23.50:554/user=admin_password=pass_channel=1_stream=0&protocol=unicast.sdp?real_stream#video=h264
    front_sub: 
      ffmpeg:rtsp://admin:pass@10.0.23.50:554/user=admin_password=pass_channel=1_stream=1&protocol=unicast.sdp?real_stream#video=h264
  webrtc:
    candidates:
      - 10.0.23.11:19554
version: 0.16-0
detect:
  enabled: true

```

i've been experimenting with ffmpeg output_args, but didn't get far. I also noticed older video files, like 10 hours+ old recordings, don't play anymore. i copied them to local machine, and not even vlc won't open them. as if they gett corrupted somehow. it could be just the crap ssd drive, but it's weird in any case.
