### DISCUSSION TITLE
[Config Support]: No audio in sub stream

### DISCUSSION THREAD

**Discussion by Dzonzi** [blakeblackshear/frigate#18488] [Config Support]
### Describe the problem you are having

Hi, I want to add audio to the recordings and to live view. For HiRes stream there is video in live view, but not for LowRes stream. Whats going on? Config look the same for both streams. In camera software audio in enabled for both streams, ACC. When I put rstp links into PotPlayer I have audio in both streams.

### Version

0.15.0-6cb5cfb

**Comment by hawkeye217** [comment]
The correct audio codec is `aac`, not `acc`.

**Reply by Dzonzi** [reply]
Sorry, i forgot to hide password and IPs. Paste my code again. I changed to AAC, but still nothing ;/

**Comment by Dzonzi** [comment]
```
############################################################################
#========================== GLOBAL FFMPEG =================================#
############################################################################

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac
  input_args: preset-rtsp-restream
  
############################################################################
#================================= GO2RTC =================================#
############################################################################

go2rtc:
  streams:
    Dahua_1_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Dahua_1_HiRes#audio=aac"
    Dahua_1_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:Dahua_1_LowRes#audio=aac"
    Dahua_2_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Dahua_1_LowRes#audio=aac"
    Dahua_2_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:Dahua_1_LowRes#audio=aac"      
    Asecam_1_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX:554/stream1
      - "ffmpeg:Dahua_1_LowRes#audio=aac"
    Asecam_1_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX:554/stream0     
      - "ffmpeg:Dahua_1_LowRes#audio=aac"
    Asecam_2_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX:554/stream1
      - "ffmpeg:Dahua_1_LowRes#audio=aac"
    Asecam_2_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX554/stream0 
      - "ffmpeg:Dahua_1_LowRes#audio=aac"      
  webrtc:
    candidates:
      - 100.125.XXX.XXX.:8555
      - stun:8555      

############################################################################
#============================ DETECTORS ===================================#
############################################################################

detectors:
  coral:
    type: edgetpu
    device: usb

############################################################################
#============================= VARIABLES ==================================#
############################################################################

environment_vars:
  LIBVA_DRIVER_NAME: iHD  
  
############################################################################
#======================== GLOBAL DETECTIONS ===============================#
############################################################################

detect:
#  width: 1280
#  height: 720
  width: 704
  height: 576
  fps: 5
objects:
  track:
    - person
    - car


############################################################################
#============================ GLOBAL RECORD ===============================#
############################################################################

record:
  enabled: true
  retain:
    days: 0
    mode: active_objects
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects

############################################################################
#                                                                          #
#============================== CAMERAS ===================================#
#                                                                          #
###########################################################################

cameras:
  Dahua_1_HiRes:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://127.0.0.1:8554/Dahua_1_LowRes?video=copy&audio=copy
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dahua_1_HiRes?video=copy&audio=copy
          roles:
            - record
    motion:
      mask:
        - 0.55,0.026,0.55,0.086,0.959,0.095,0.962,0.021
        - 0.646,0.34,0.666,0.416,0.741,0.437,0.752,0.401,0.741,0.375,0.737,0.347,0.729,0.333,0.723,0.29,0.705,0.266,0.687,0.269
        - 0.572,0.673,0.669,0.805,0.74,0.753,0.726,0.632,0.66,0.537,0.608,0.558
        - 0.187,0,0.088,0,0.054,0.024,0,0.079,0,0.145,0.074,0.071
        - 0.204,0.04,0.158,0.003,0.511,0.003,0.605,0.014,0.555,0.059,0.434,0.04,0.363,0.038
      threshold: 35
      contour_area: 10
      improve_contrast: true

  Dahua_2_HiRes:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Dahua_2_LowRes?video=copy&audio=copy
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dahua_2_HiRes?video=copy&audio=copy
          roles:
            - record
    motion:
      mask:
        - 0.551,0.031,0.554,0.088,0.96,0.085,0.959,0.021
        - 0.647,0.161,0.796,0.249,0.85,0.292,0.929,0.355,0.999,0.429,0.997,0.488,0.945,0.455,0.873,0.386,0.844,0.334,0.646,0.209
        - 0.24,0.261,0.283,0.325,0.327,0.327,0.318,0.232,0.273,0.228
        - 0.526,0.424,0.44,0.426,0.431,0.362,0.525,0.285
        - 0.243,0.042,0.394,0.064,0.486,0.093,0.528,0.107,0.574,0.126,0.597,0.14,0.521,0.131,0.517,0.159,0.399,0.119,0.241,0.123
    live:
        stream_name: Dahua_2_HiRes
        
  Asecam_1_HiRes:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Asecam_1_LowRes?video=copy&audio=aac
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Asecam_1_HiRes?video=copy&audio=aac
          roles:
            - record
    motion:
      mask: 0.006,0.012,0.008,0.04,0.231,0.048,0.232,0.01
        
  Asecam_2_HiRes:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Asecam_2_LowRes?video=copy&audio=aac
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Asecam_2_HiRes?video=copy&audio=aac
          roles:
            - record
    motion:
      mask:
        - 0.005,0.009,0.004,0.04,0.23,0.045,0.23,0.012
        - 0.029,0.144,0.021,0.313,0.199,0.3,0.25,0.12,0.191,0.125

      threshold: 35
      contour_area: 15
      improve_contrast: true
version: 0.15-1
```

**Reply by hawkeye217** [reply]
Also, in your go2rtc config, you have a mismatched stream name in your second streams that transcode the audio. For example, you have this:

```
    ...
    Dahua_2_HiRes:
      - rtsp://admin:***@192.168.137.102/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Dahua_1_LowRes#audio=acc"
```
It should be this:
```
    ...
    Dahua_2_HiRes:
      - rtsp://admin:***@192.168.137.102/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Dahua_2_HiRes#audio=aac"
```

**Comment by hawkeye217** [comment]
It should also be noted that Frigate intelligently selects the live streaming technology based on a number of factors (user-selected modes like two-way talk, camera settings, browser capabilities, available bandwidth) and prioritizes showing an actual up-to-date live view of your camera's stream as quickly as possible.

When you have go2rtc set up, Live view initially attempts to load and play back your stream with a clearer, fluent stream technology (MSE). An initial timeout, a low bandwidth condition that would cause buffering of the stream, or decoding errors in the stream will cause Frigate to switch to the stream defined by the `detect` role, using the jsmpeg format.

The jsmpeg format does not support audio.

https://docs.frigate.video/configuration/live/

**Comment by Dzonzi** [comment]
After update:
```  
############################################################################
#========================== GLOBAL FFMPEG =================================#
############################################################################

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac
  input_args: preset-rtsp-restream
  
############################################################################
#================================= GO2RTC =================================#
############################################################################

go2rtc:
  streams:
    Dahua_1_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Dahua_1_HiRes#audio=aac"
    Dahua_1_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:Dahua_1_LowRes#audio=aac"
    Dahua_2_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:Dahua_2_HiRes#audio=aac"
    Dahua_2_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:Dahua_2_LowRes#audio=aac"      
    Asecam_1_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX:554/stream1
      - "ffmpeg:Asecam_1_HiRes#audio=aac"
    Asecam_1_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX:554/stream0     
      - "ffmpeg:Asecam_1_LowRes#audio=aac"
    Asecam_2_HiRes:
      - rtsp://admin:password@192.168.XXX.XXX554/stream1
      - "ffmpeg:Asecam_2_HiRes#audio=aac"
    Asecam_2_LowRes:
      - rtsp://admin:password@192.168.XXX.XXX:554/stream0 
      - "ffmpeg:Asecam_2_LowRes#audio=aac"      
  webrtc:
    candidates:
      - 100.125.XXX.XXX:8555
      - stun:8555      

############################################################################
#============================= BIRDSEYE ===================================#
############################################################################

birdseye:
  enabled: true
  mode: continuous

############################################################################
#============================ DETECTORS ===================================#
############################################################################

detectors:
  coral:
    type: edgetpu
    device: usb

############################################################################
#============================= VARIABLES ==================================#
############################################################################

environment_vars:
  LIBVA_DRIVER_NAME: iHD  
  
############################################################################
#======================== GLOBAL DETECTIONS ===============================#
############################################################################

detect:
#  width: 1280
#  height: 720
  width: 704
  height: 576
  fps: 5
objects:
  track:
    - person
    - car

############################################################################
#============================ GLOBAL RECORD ===============================#
############################################################################

record:
  enabled: true
  retain:
    days: 0
    mode: active_objects
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects

############################################################################
#                                                                          #
#============================== CAMERAS ===================================#
#                                                                          #
###########################################################################

cameras:
  Dahua_1_HiRes:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://127.0.0.1:8554/Dahua_1_LowRes?video=copy&audio=aac
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dahua_1_HiRes?video=copy&audio=aac
          roles:
            - record
    motion:
      mask:
        - 0.55,0.026,0.55,0.086,0.959,0.095,0.962,0.021
        - 0.646,0.34,0.666,0.416,0.741,0.437,0.752,0.401,0.741,0.375,0.737,0.347,0.729,0.333,0.723,0.29,0.705,0.266,0.687,0.269
        - 0.572,0.673,0.669,0.805,0.74,0.753,0.726,0.632,0.66,0.537,0.608,0.558
        - 0.187,0,0.088,0,0.054,0.024,0,0.079,0,0.145,0.074,0.071
        - 0.204,0.04,0.158,0.003,0.511,0.003,0.605,0.014,0.555,0.059,0.434,0.04,0.363,0.038
      threshold: 35
      contour_area: 10
      improve_contrast: true

  Dahua_2_HiRes:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Dahua_2_LowRes?video=copy&audio=aac
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Dahua_2_HiRes?video=copy&audio=aac
          roles:
            - record
    motion:
      mask:
        - 0.551,0.031,0.554,0.088,0.96,0.085,0.959,0.021
        - 0.647,0.161,0.796,0.249,0.85,0.292,0.929,0.355,0.999,0.429,0.997,0.488,0.945,0.455,0.873,0.386,0.844,0.334,0.646,0.209
        - 0.24,0.261,0.283,0.325,0.327,0.327,0.318,0.232,0.273,0.228
        - 0.526,0.424,0.44,0.426,0.431,0.362,0.525,0.285
        - 0.243,0.042,0.394,0.064,0.486,0.093,0.528,0.107,0.574,0.126,0.597,0.14,0.521,0.131,0.517,0.159,0.399,0.119,0.241,0.123
        
  Asecam_1_HiRes:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Asecam_1_LowRes?video&audio
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Asecam_1_HiRes?videoy&audio
          roles:
            - record
    motion:
      mask: 0.006,0.012,0.008,0.04,0.231,0.048,0.232,0.01
        
  Asecam_2_HiRes:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Asecam_2_LowRes?video&audio
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Asecam_2_HiRes?video&audio
          roles:
            - record
    motion:
      mask:
        - 0.005,0.009,0.004,0.04,0.23,0.045,0.23,0.012
        - 0.029,0.144,0.021,0.313,0.199,0.3,0.25,0.12,0.191,0.125

      threshold: 35
      contour_area: 15
      improve_contrast: true
version: 0.15-1

camera_groups:
  FAK:
    order: 1
    icon: LuAirplay
    cameras: birdseye

```

I don't know if I have audio or not. Should it be in recordings? 
Would Webrtc help me for better live experience? 
I use advanced card addon, maybe with webrtc it will be smoother stream and audio?
