### DISCUSSION TITLE
Dropped frames and broken recordings (FFmpeg errors)

### DISCUSSION THREAD

**Discussion by gnajmacz** [blakeblackshear/frigate#18495] [Ask A Question]
Hi, I'm having an issue with Frigate — both the live view and recordings show noticeable dropped frames, with the video sometimes skipping ahead by several seconds. The logs are full of errors (I've attached them as a file). Does anyone have an idea of what I could try?

When I check the stream in VLC, everything looks normal — no interruptions or stuttering.

**Cameras:**

* 2x ANNKE AC500
* 1x Dahua IPC-HFW1530S-0280B-S6

**Hardware:**

* VM with 12-core Xeon 4310
* NVIDIA Quadro P620
* Coral USB
* 32GB RAM
  CPU usage inside the VM doesn’t exceed 30%. Running on Debian 12 with Docker Compose.

**Frigate Config:**

```
mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 28
    mode: all

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia

cameras:
  front:
    enabled: true
    ffmpeg:
      inputs:
        - path: (Dahua stream path)
          roles:
            - detect
            - record
    detect:
      width: 2880
      height: 1620
      fps: 20
    objects:
      track:
        - person
        - dog
        - cat
        - bus
        - truck
        - car
        - horse

  wejscie:
    enabled: true
    ffmpeg:
      inputs:
        - path: (ANNKE stream path)
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 3072
      height: 1728
      fps: 20
    objects:
      track:
        - person
        - dog
        - cat
        - bus
        - truck
        - car
        - horse

  ogrod:
    enabled: true
    ffmpeg:
      inputs:
        - path: (ANNKE stream path)
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 3072
      height: 1728
      fps: 20
    objects:
      track:
        - person
        - dog
        - cat
version: 0.15-1
```
[frigate-logs.txt](https://github.com/user-attachments/files/20527777/frigate-logs.txt)
