### DISCUSSION TITLE
[Detector Support]: ov is very slow (174859289954.25ms)

### DISCUSSION THREAD

**Discussion by Anaerin** [blakeblackshear/frigate#18490] [Detector Support]
### Describe the problem you are having

When Frigate has been running for a while, the ov detector gets into a weird state and reports "very slow" performance on one or both of the ov processors I have set up. A save and restart of the config fixes it.

### Version

0.16.0-1fa7ce5

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: homeassistant.localdomain
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: <REDACTED>

detectors:
  ov_0:
    type: openvino
    device: GPU
  ov_1:
    type: openvino
    device: GPU

logger:
  default: info

model:
  model_type: yolonas
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: bgr
  # path: /openvino-model/ssdlite_mobilenet_v2.xml
  # labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

go2rtc:
  webrtc:
    listen: :8655
    candidates:
      - 10.7.0.0:8655
      - stun:8655
  streams:
    front-door-cam: rtsp://wyze-bridge:8554/front-door-cam
    front-door-cam-sub: rtsp://wyze-bridge:8554/front-door-cam-sub
#    car-cam: rtsp://wyze-bridge:8554/car-cam
#    car-cam-sub: rtsp://wyze-bridge:8554/car-cam-sub
    garden-cam: rtsp://wyze-bridge:8554/garden-cam
    garden-cam-sub: rtsp://wyze-bridge:8554/garden-cam-sub
    garden-cam-2: rtsp://wyze-bridge:8554/garden-cam-2

cameras:
  front-door-cam: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-door-cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front-door-cam-sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution

    objects:
      filters:
        person: {}
    zones: {}
    review: {}
    motion:
      mask: 0.721,0.933,0.976,0.932,0.977,0.986,0.724,0.987
    live:
      streams:
        front-door-cam: front-door-cam
  garden-cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden-cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden-cam-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360

    lpr:
      enabled: false

    live:
      streams:
        garden-cam: garden-cam

    motion:
      mask: 0.721,0.933,0.976,0.932,0.977,0.986,0.724,0.987

  garden-cam-2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden-cam-2
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360

    lpr:
      enabled: false

    live:
      streams:
        garden-cam-2: garden-cam-2

    motion:
      mask: 0.721,0.933,0.976,0.932,0.977,0.986,0.724,0.987
record:
  enabled: true
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 60
  detections:
    retain:
      days: 60
birdseye:
  enabled: true
  mode: objects
  restream: true

objects:
  track:
    - person
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - car
    - motorcycle
    - truck
    - bus
    - vehicle
    - face

detect:
  fps: 10

  enabled: true
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
version: 0.16-0
camera_groups:
  Live:
    order: 1
    icon: LuAlertCircle
    cameras:
      - car-cam
      - front-door-cam
      - garden-cam
      - garden-cam-2
telemetry:
  stats:
    intel_gpu_stats: true
    network_bandwidth: true

semantic_search:
  enabled: true
  reindex: false
  model_size: small
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
classification:
  bird:
    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    networks:
      - webcam-bridge
      - default
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2
    runtime: runc
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/vpu_service:/dev/vpu_service
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate-config:/config
      - /mnt/storage/nvr:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8500:5000"

      - "8554:8554" # RTSP feeds
      - "8655:8655/tcp" # WebRTC over tcp
      - "8655:8655/udp" # WebRTC over udp
      - "1984:1984" # go2RTC web interface
      - "8971:8971" # ? New WebUI?
    environment:
      FRIGATE_RTSP_PASSWORD: "<REDACTED>"
volumes:
  frigate-config:
    external: true

networks:
  webcam-bridge:
    name: webcam-bridge
    external: true
```

### Relevant Frigate log output

```shell
error   | 2025-05-30 02:16:03 | ffmpeg.garden                | Error opening input files: Server returned 404 Not Found
info    | 2025-05-30 02:16:03 | watchdog.garden              | Terminating the existing ffmpeg process...
info    | 2025-05-30 02:16:03 | watchdog.garden              | Waiting for ffmpeg to exit gracefully...
info    | 2025-05-30 02:16:33 | detector.ov_0                | Starting detection process: 20628
warning | 2025-05-30 02:30:13 | frigate.track.tracked_object | Unable to create jpg because frame 1748593760.004095 is not in the cache
error   | 2025-05-30 05:21:37 | frigate.comms.mqtt           | MQTT disconnected
error   | 2025-05-30 06:19:34 | frigate.video                | garden-cam: Unable to read frames from ffmpeg process.
error   | 2025-05-30 06:19:35 | frigate.video                | garden-cam: ffmpeg process is not running. exiting capture thread...
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/cb601fec-8738-441c-a8d4-58050dd1939e)
![image](https://github.com/user-attachments/assets/e6ca03de-e7d1-4924-9026-cf470f1b68c3)

### Any other information that may be helpful

System Specs: Intel i5-13600K
vainfo output:
```
{"return_code":0,"stderr":"","stdout":"vainfo: VA-API version: 1.22 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.3.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP"}
```
