### DISCUSSION TITLE
[Support]: High ffmpeg process usage on camera with disabled motion and detection

### DISCUSSION THREAD

**Discussion by majkrzak** [blakeblackshear/frigate#18499] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

FFmpeg process on camera is gihly loading the CPU despite it is suposed to do nothing.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
go2rtc:
  streams:
    camera1: rtsp://camera1.lan/ch0
    camera1_sub: rtsp://camera1.lan/ch1
    camera2: rtsp://camera2.lan/ch0
    camera2_sub: rtsp://camera2.lan/ch1
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera1_sub
          roles:
            - audio
            - detect
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          roles:
            - record
    motion:
      enabled: false
    detect:
      enabled: false
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Network connection

Wireless

### Camera make and model

Xiaomi MJSXJ03HL

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/afbaf892-3fc2-48a1-9b48-4acff9107f65)

**Comment by majkrzak** [comment]
Same happens on `0.16.0-1fa7ce5` with
```
go2rtc:
  streams:
    camera1: rtsp://camera1.lan/ch0
    camera1_sub: rtsp://camera1.lan/ch1
    camera2: rtsp://camera2.lan/ch0
    camera2_sub: rtsp://camera2.lan/ch1

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera1
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera1_sub
          roles:
            - audio
            - detect
    detect:
      enabled: true
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera2
          roles:
            - record
    motion:
      enabled: false
    detect:
      enabled: false
```
