### DISCUSSION TITLE
[Detector Support]: Detection at dusk

### DISCUSSION THREAD

**Discussion by ops244** [blakeblackshear/frigate#18496] [Detector Support]
### Describe the problem you are having

Hi, I decided to try the frigate again, I didn't detect people in the dark before, it's better now, but it still doesn't detect them at dusk... is there no solution? I tried yolov9, yolov-nas, openvino

### Version

0.16.0-beta2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 
  user: 
  password: 


go2rtc:
  streams:
    camera:
      - rtsp://***/stream1
      - ffmpeg:camera#audio=aac#video=h264#hardware

cameras:
  camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

      hwaccel_args: preset-vaapi
    live:
      streams:
        camera: camera
    motion:
      threshold: 30
      lightning_threshold: 1.0
      contour_area: 10
      improve_contrast: true


detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


detect:
  width: 1280
  height: 720
  fps: 5
  min_initialized: 2
  max_disappeared: 25

  enabled: true
objects:
  track:
    - person
  filters:
    person:
      min_score: 0.6
      threshold: 0.6

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 0
    mode: motion
  alerts:
    retain:
      days: 5
      mode: motion
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 0
      mode: motion
    pre_capture: 5
    post_capture: 5


logger:
  default: error

ui:
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%D/%m/%y %H:%M'
version: 0.16-0
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: false
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
---
```

### Relevant Frigate log output

```shell
---
```

### Install method

Home Assistant Add-on

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

--
