### DISCUSSION TITLE
[Camera Support]: ffmpeg doesnt recover after "camera exceeded fps limit. Exiting ffmpeg..."

### DISCUSSION THREAD

**Discussion by foxtrotcz** [blakeblackshear/frigate#18502] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Note: Logs and configs cropped to only include relevant camera and info.

I have wifi Tapo camera that sometimes times out as seen from attached go2rtc log.
This for some reason causes `tapo exceeded fps limit. Exiting ffmpeg...`
It then exits ffmpeg `Waiting for ffmpeg to exit gracefully`
But after this point ffmpeg stays down and doesnt recover which causes recording not working.

To be clear, go2rtc and live view works after the timeout. Only ffmpeg which handles recording doesnt recover.

Also, in different cases when ffmpeg crashes for different reason it recovers successfully with this same camera.

**Example when ffmpeg recovers successfully:**
Go2rtc timeout:
`2025-05-29 12:36:39.138648802  12:36:39.138 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.16.1.2:54300->192.168.1.204:554: i/o timeout" url=rtsp://username:password@192.168.1.204/stream1`
Frigate error:
```
2025-05-29 12:37:02.988405851  [2025-05-29 12:37:02] watchdog.tapo                  INFO    : No frames received from tapo in 20 seconds. Exiting ffmpeg...
2025-05-29 12:37:02.988433704  [2025-05-29 12:37:02] watchdog.tapo                  INFO    : Waiting for ffmpeg to exit gracefully...
2025-05-29 12:37:03.271226513  [2025-05-29 12:37:03] frigate.video                  ERROR   : tapo: Unable to read frames from ffmpeg process.
2025-05-29 12:37:03.271271448  [2025-05-29 12:37:03] frigate.video                  ERROR   : tapo: ffmpeg process is not running. exiting capture thread...
2025-05-29 12:37:13.274593618  [2025-05-29 12:37:13] watchdog.tapo                  ERROR   : Ffmpeg process crashed unexpectedly for tapo.
2025-05-29 12:37:13.274637751  [2025-05-29 12:37:13] watchdog.tapo                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-05-29 12:37:13.274661826  [2025-05-29 12:37:13] ffmpeg.tapo.detect             ERROR   : [vost#0:0/copy @ 0x55f659c458c0] Non-monotonic DTS; previous: 1307548120, current: 1221884642; changing to 1307548121. This may result in incorrect timestamps in the output file.
```

So it looks like if ffmpeg really crashes it does recover. But in my specific case there is no crash logged, only attempt to exit and it doesnt recover.

In System metrics - Cameras the Tapo chart shows 92 FPS, but when I use probe it shows FPS: 57/4.
When I access the camera stream either directly or via go2rtc in VLC is shows 14 FPS.
This means that FPS is good but Frigate and ffmpeg still refuses to recover.

I also checked list of processes in container and the ffmpeg process responsible for recording the tapo camera was missing so it looks like it exited successfully.
On the other hand the ffmpeg process responsible for live view was running.

So it looks like: If ffmpeg process crashes it recovers. If its gracefully shutdown or because of exceeded fps limit it does not recover.
So I wonder if Frigate can add some ffmpeg handling to make sure the recording process actually recovers even in this case.

Relevant source code: https://github.com/blakeblackshear/frigate/blob/f141b585bcbaa3e2b5831bc12cff979156f14aec/frigate/video.py#L263

From what I see in source code, if fps exceeds limit ffmpeg gets shutdown. But I dont understand why I kept seeing 92 FPS in stats when ffmpeg probe and VLC confirmed fps of camera stream is actually 14 fps. Maybe because of the killed ffmpeg process Frigate cant update the stats correctly? I wasnt able to find down how exactly Frigate gets the camera_fps value.
But I think after the ffmpeg exits because of this there should be mechanism to auto-recover.

I saw threads here with similar issue but I want to focus this more on the recovery of ffmpeg process.
Thanks.

### Steps to reproduce

1. Wait until wifi camera TP-Link Tapo C100 has a timeout in go2rtc.
2. It needs to report error `tapo exceeded fps limit. Exiting ffmpeg...` and `Waiting for ffmpeg to exit gracefully` in Frigate.
3. Now it doesnt recover and recording doesnt work until manual restart.

### Version

0.15.0-6cb5cfb

### In which browser(s) are you experiencing the issue with?

Google Chrome 137.0.7151.56

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi


go2rtc:
  streams:
    tapo:
      - rtsp://usarname:password@192.168.1.204/stream1

cameras:
  tapo: # <------ tapo
    enabled: true
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - record

    motion:
      mask: 0.001,0.044,0.329,0.046,0.331,0.003,0.001,0


tls:
  enabled: false

record:
  enabled: true
  retain:
    days: 4
motion:
  enabled: true
detect:
  enabled: false
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: 1024mb # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/hdd1/frigate-storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1G
    ports:
      - 30058:8971
      - 1984:1984
      - 28554:8554
    devices:
      - /dev/dri/renderD128
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
networks: {}
```

### Relevant Frigate log output

```shell
2025-05-31 05:55:17.057263206  [2025-05-31 05:55:17] watchdog.tapo                  INFO    : tapo exceeded fps limit. Exiting ffmpeg...
2025-05-31 05:55:17.057336414  [2025-05-31 05:55:17] watchdog.tapo                  INFO    : Waiting for ffmpeg to exit gracefully...
2025-05-31 13:31:03.258494562  [2025-05-31 13:31:03] frigate.api.media              ERROR   : No recordings found for tapo during the requested time range
```

### Relevant go2rtc log output

```shell
2025-05-31 05:54:51.335789507  05:54:51.335 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.16.1.2:50068->192.168.1.204:554: i/o timeout" url=rtsp://user:password@192.168.1.204/stream1
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

TP-Link Tapo C100

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/58bce032-02fd-48be-9ec5-f7761ab7ec44)
![image](https://github.com/user-attachments/assets/6f339513-ffae-4d7a-a7c5-b7ebc2bc3b0f)
![image](https://github.com/user-attachments/assets/1df3ef50-744c-445f-8e27-cf437e850a5c)
![image](https://github.com/user-attachments/assets/3c9f8f37-15b9-4637-a8c0-b1a04fbbc430)
