### DISCUSSION TITLE
[Support]: Motion detection doesn't get turned off again along with detection

### DISCUSSION THREAD

**Discussion by Zinurist** [blakeblackshear/frigate#18508] [General Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

This is just a small UI bug, not high priority.

I have motion and event detection completely turned off in my config like this:
```
detect:
  enabled: false
motion:
  enabled: false
```

I still have a button "Enable Detect" in the UI when choosing a camera. Clicking on that button produces these logs:
```
2025-06-01 10:12:06.236623458  [2025-06-01 10:12:06] frigate.comms.dispatcher       INFO    : Turning on detection for e1_outdoor
2025-06-01 10:12:06.236935811  [2025-06-01 10:12:06] frigate.comms.dispatcher       INFO    : Turning on motion for e1_outdoor due to detection being enabled.
```
It does turn on motion detection, but not the normal event detection from what I can tell, which is a bit confusing, but not really the issue here.

I can tell it turns on motion detection, since the yellow bars start appearing in the timeline.

When I click the button again to disable it, this is logged:
```
2025-06-01 10:12:24.930867838  [2025-06-01 10:12:24] frigate.comms.dispatcher       INFO    : Turning off detection for e1_outdoor
```
But motion detection isn't turned off again. The yellow bars still keep appearing in the timeline. Restarting frigate fixes this, and motion detection is turned off again.

### Steps to reproduce

1. Disable motion detection in the server config
2. Click "Enable Detect" to enable detection, and then again to disable it again
3. motion detection is still turned on, even though it should be off

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false
detect:
  enabled: false
motion:
  enabled: false
tls:
  enabled: false

cameras:
  <redacted>:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>
          roles:
            - record
        - path: rtsp://<redacted>
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 20
        mode: all
      export:
        timelapse_args: -vf setpts=PTS/300 -r 30
      alerts:
        retain:
          days: 20
        pre_capture: 10
        post_capture: 30
      detections:
        retain:
          days: 20
        pre_capture: 10
        post_capture: 30
    detect:
      enabled: false
    motion:
      enabled: false
    onvif:
      <redacted>
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
.
```

### Relevant Frigate log output

```shell
2025-06-01 10:12:06.236623458  [2025-06-01 10:12:06] frigate.comms.dispatcher       INFO    : Turning on detection for e1_outdoor
2025-06-01 10:12:06.236935811  [2025-06-01 10:12:06] frigate.comms.dispatcher       INFO    : Turning on motion for e1_outdoor due to detection being enabled.
...
2025-06-01 10:12:24.930867838  [2025-06-01 10:12:24] frigate.comms.dispatcher       INFO    : Turning off detection for e1_outdoor
```

### Relevant go2rtc log output

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

.

### Screenshots of the Frigate UI's System metrics pages

.
