### DISCUSSION TITLE
[Support]: strange behavior of detector on rockchip

### DISCUSSION THREAD

**Discussion by Vladd1980** [blakeblackshear/frigate#18517] [Detector Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I successfully use freegate 0.15 on orange pi5 and have no problems with it. But after installing freegate 0.16 beta 1,2,3 the detector's behavior is illogical. It constantly detects a huge number of small objects (30-50 pixels) but does not see the true object. No methods of combating such as min_area or object mass give results, detection simply stops. This happens on all cameras
![photo_2025-05-31_11-59-13](https://github.com/user-attachments/assets/3165e854-6af0-455e-a4d2-fb3f57d948d3)
![photo_2025-05-31_11-57-32](https://github.com/user-attachments/assets/d4a04241-e68c-465f-a14e-05a08ea09fe4)

### Steps to reproduce

1.
2.
3.
...

### Version

0.16 beta3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.150
  port: 1883
  topic_prefix: frigate
  user: ******
  password: ******

detectors:
  rknn:
    type: rknn
    num_cores: 3

model:
  path: deci-fp16-yolonas_s
  model_type: yolonas
  width: 320
  height: 320
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /labelmap/coco-80.txt

semantic_search:
  enabled: false
  reindex: false
  model_size: small

genai:
  enabled: false
  provider: gemini
  api_key: chren_tebe_a_ne_api
  #model: gemini-1.5-flash
  model: gemini-2.0-flash-exp
  prompt: Analyze the {label} in these images from the {camera} security camera at
    the front door. Focus on the actions and potential intent of the {label}. Reply
    in Russian
  object_prompts:
    person: Examine the person in these images. What are they doing, and how might
      their actions suggest their purpose (e.g., delivering something, approaching,
      leaving)? If they are carrying or interacting with a package, include details
      about its source or destination. Reply in Russian

face_recognition:
  enabled: false
  model_size: small
  min_area: 1000
#  recognition_threshold: 0.7
#  unknown_score: 0.5


lpr:
  enabled: false
  model_size: small
  debug_save_plates: true

record:
  sync_recordings: true
  expire_interval: 720
  enabled: true
  retain:
    days: 1
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

ffmpeg:
  input_args: preset-rtsp-restream
#  hwaccel_args: preset-rk-h264

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  clean_copy: false
  retain:
    default: 30

go2rtc:
  rtsp:
    listen: :8554
    username: admin
    password: ****
  streams:
    ogorod:
      - rtsp://192.168.1.42:554/user=admin_password=*****_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    ogorod_sub:
      - rtsp://192.168.1.42:554/user=admin_password=*****_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    Podval:
      - rtsp://192.168.1.40:554/user=admin_password=*****_channel=1_stream=0&onvif=0.sdp?real_stream#video=copy#audio=copy#audio=aac#audio=opus
    Podval_sub:
      - rtsp://192.168.1.40:554/user=admin_password=*****_channel=1_stream=1&onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    Ploshatka:
      - rtsp://192.168.1.43:554/user=admin_password=******_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    Ploshatka_sub:
      - rtsp://192.168.1.43:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    Banya_basein:
      - rtsp://192.168.1.44:554/user=admin_password=*****_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    Banya_basein_sub:
      - rtsp://192.168.1.44:554/user=admin_password=*****_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    Basein:
      - rtsp://192.168.1.45:554/user=admin_password=*****_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    Basein_sub:
      - rtsp://192.168.1.45:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    stoyanka:
      - rtsp://192.168.1.46:554/user=admin_password=*****K_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    stoyanka_sub:
      - rtsp://192.168.1.46:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    vihod:
      - rtsp://192.168.1.48:554/user=admin_password=*****_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    vihod_sub:
      - rtsp://192.168.1.48:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    Krisha_stoyanka:
      - rtsp://192.168.1.49:554/user=admin_password=*****_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    Krisha_stoyanka_sub:
      - rtsp://192.168.1.49:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp.#video=copy#audio=copy#audio=aac#audio=opus
    Krisha_podval:
      - rtsp://admin:5686648L@192.168.1.50:554/cam/realmonitor?channel=1&subtype=0#video=copy#audio=copy#audio=aac#audio=opus
    Krisha_podval_sub:
      - rtsp://admin:5686648L@192.168.1.50:554/cam/realmonitor?channel=1&subtype=1#video=copy#audio=copy#audio=aac#audio=opus
    Kotel:
      - rtsp://192.168.1.51:554/user=admin_password=****K_channel=1_stream=0&amp;onvif=0.sdp?real_st#video=copy#audio=copy#audio=aac#audio=opus
    Kotel_sub:
      - rtsp://192.168.1.51:554/user=admin_password=******_channel=1_stream=1&amp;onvif=0.sdp.#video=h264#audio=copy#audio=aac#audio=opus
    Krisha_dvor:
      - rtsp://192.168.1.41:554/user=admin_password=*****_channel=1_stream=0.sdp?real_stream#video=copy#audio=copy#audio=aac#audio=opus
    Krisha_dvor_sub:
      - rtsp://192.168.1.41:554/user=admin_password=*****_channel=1_stream=1.sdp?real_stream#video=copy#audio=copy#audio=aac#audio=opus
    Banya_vhod:
      - rtsp://admin:@192.168.1.47:554#video=copy#audio=copy#audio=aac#audio=opus
    Banya_vhod_sub:
      - rtsp://admin:@192.168.1.47:554/0/av1#video=copy#audio=copy#audio=aac#audio=opus
    Banya_ptz:
      - rtsp://192.168.1.137:554/user=admin_password=*****_channel=0_stream=0&onvif=0.sdp?real_stream#video=copy#audio=copy#audio=aac#audio=opus
    Banya_ptz_sub:
      - rtsp://192.168.1.137:554/user=admin_password=*****_channel=0_stream=1&onvif=0.sdp?real_stream#video=copy#audio=copy#audio=aac#audio=opus

cameras:
  ogorod:
    enabled: true
    detect: 
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@127.0.0.1:8554/ogorod
          roles:
            - record
        - path: rtsp://admin:*****@127.0.0.1:8554/ogorod_sub
          roles:
            - detect
    live:
      streams:
        ogorod_sub: ogorod_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 43
      threshold: 43
      mask: 0.005,0,0.133,0.004,0.284,0.987,0.002,0.996
      improve_contrast: false
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 1000

  Podval:
    enabled: true
    detect: 
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@127.0.0.1:8554/Podval
          roles:
            - record
        - path: rtsp://admin:****@127.0.0.1:8554/Podval_sub
          roles:
            - detect
    live:
      streams:
        Podval_sub: Podval_sub
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bus
      filters:
        car:
           min_area: 500
        person:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 48
      threshold: 43
      mask: 0.004,0.003,0.45,0,0.453,0.255,0.345,0.988,0.002,0.986
      improve_contrast: true
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 1000

  Banya_basein:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:***@127.0.0.1:8554/Banya_basein
          roles:
            - record
        - path: rtsp://admin:****@127.0.0.1:8554/Banya_basein_sub
          roles:
            - detect
    live:
      streams:
        Banya_basein_sub: Banya_basein_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
#          threshold: 0.7
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 44
      threshold: 44
      improve_contrast: false
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 1000

  Ploshatka:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Ploshatka
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Ploshatka_sub
          roles:
            - detect
    live:
      streams:
        Ploshatka_sub: Ploshatka_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 38
      threshold: 36
      improve_contrast: false
    mqtt:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: true
      quality: 100
      height: 1000

  Basein:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Basein
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Basein_sub
          roles:
            - detect
    live:
      streams:
        Basein_sub: Basein_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
          threshold: 0.85
    motion:
#      lightning_threshold: 0.6
      contour_area: 33
      threshold: 33

      improve_contrast: false
      mask: 
        0.645,-0.001,0.62,0.179,0.584,0.251,0.497,0.269,0.446,0.291,0.395,0.431,0.599,0.692,0.335,0.894,0.135,0.527,0.136,0.375,0.136,0.216,0.121,0.154,0.1,0.122,0.111,0.08,0.16,0.006


  stoyanka:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/stoyanka
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/stoyanka_sub
          roles:
            - detect
    live:
      streams:
        stoyanka_sub: stoyanka_sub
    objects:
      track:
        - person
        - dog
        - cat
        - bus
        - car
      filters:
        person: 
          min_area: 500
        car:
#          threshold: 0.4
          min_area: 500
#        bus:
#          threshold: 0.5
    motion:
#      lightning_threshold: 0.6
      contour_area: 45
      threshold: 47
      mask:
        - 0.001,0.182,0,0,1,0,1,0.36,0.431,0.2,0.265,0.202
        - 0.179,0.67,0.47,0.53,0.679,0.383,0.8,0.45,0.999,0.607,0.998,0.991,0.298,0.995
      improve_contrast: false


  vihod:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/vihod
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/vihod_sub
          roles:
            - detect
    live:
      streams:
        vihod_sub: vihod_sub
    objects:
      track:
        - person
        - dog
        - cat

      mask: 0.853,1,0.894,0.011,0.991,0.002,1,1
      filters:
        person:
          min_area: 500
#          threshold: 0.85
    motion:
      threshold: 39
      contour_area: 43
      improve_contrast: false
      mask: 0.889,0.007,0.996,0.005,0.998,0.993,0.855,0.994

  Krisha_stoyanka:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Krisha_stoyanka
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Krisha_stoyanka_sub
          roles:
            - detect
    live:
      streams:
        Krisha_stoyanka_sub: Krisha_stoyanka_sub
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bus
      filters:
        car:
          min_area: 500
        person:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 32
      threshold: 35
      improve_contrast: false
      mask: 0.353,0,0.358,0.308,0.268,0.327,0.236,0.356,0.238,0.428,0.003,0.442,0.002,0.006


  Krisha_podval:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Krisha_podval
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Krisha_podval_sub
          roles:
            - detect
    live:
      streams:
        Krisha_podval_sub: Krisha_podval_sub
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bus
      filters:
        person:
          min_area: 500
        car:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 40
      threshold: 44

      mask: 0.003,0.124,0.386,0.13,0.392,0.548,0.455,0.841,0.294,0.961,0.064,0.909,0,0.886
      improve_contrast: false

  Kotel:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Kotel
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Kotel_sub
          roles:
            - detect
    live:
      streams:
        Kotel_sub: Kotel_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 30
      threshold: 30
      improve_contrast: false


  Krisha_dvor:
    enabled: true
    detect: 
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Krisha_dvor
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Krisha_dvor_sub
          roles:
            - detect
    live:
      streams:
        Krisha_dvor_sub: Krisha_dvor_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.85
          min_area: 500
          mask: 0.573,-0.001,0.865,0.201,0.998,0.24,0.997,0
    motion:
#      lightning_threshold: 0.6
      contour_area: 41
      threshold: 37
      improve_contrast: false


  Banya_vhod:
    enabled: true
    detect:
      enabled: true
    onvif:
      host: 192.168.1.47
      port: 8899
      user: admin
      password: tlJwpbo6
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Banya_vhod
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Banya_vhod_sub
          roles:
            - detect
    live:
      streams:
        Banya_vhod_sub: Banya_vhod_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
          threshold: 0.8
    motion:
#      lightning_threshold: 0.6
      contour_area: 40
      threshold: 40
      mask:
        - 0.016,0.029,0.266,0.029,0.268,0.084,0.018,0.082
        - 0.137,0.989,0.136,0.852,0.238,0.712,0.22,0.475,0.318,0.45,0.311,0.357,0.371,0.342,0.488,0.562,0.596,0.525,0.583,0.402,0.643,0.355,0.689,0.461,0.724,0.514,0.786,0.461,0.843,0.631,0.98,0.771,0.982,0.839,0.88,0.817,0.785,0.9,0.73,0.998
      improve_contrast: false


  Banya_ptz:
    enabled: true
    detect:
      enabled: true
    onvif:
      host: 192.168.1.137
      port: 8899
      user: admin
      password: tlJwpbo6
    ffmpeg:
      inputs:
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Banya_ptz
          roles:
            - record
        - path: rtsp://admin:GKVn@127.0.0.1:8554/Banya_ptz_sub
          roles:
            - detect
    live:
      streams:
        Banya_ptz_sub: Banya_ptz_sub
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
    motion:
#      lightning_threshold: 0.6
      contour_area: 57
      threshold: 50
      mask:
        - 0.989,0.098,0.98,0.061,0.7,0.061,0.701,0.094
        - 0.998,0.19,0.696,0.478,0.85,0.994,0.995,0.991
      improve_contrast: false
version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate0.16
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3-rk
    privileged: true 
    restart: unless-stopped
    group_add:
      - "106" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "2500mb" 
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/rga
      - /dev/video-dec0:/dev/video-dec0
      - /dev/video-enc0:/dev/video-enc0
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigatte-16:/config:rw # Папка размещения контейнера
      - /mnt/frigate/recordings:/media/frigate:rw
      - type: tmpfs # Опционально: уменьшение износа SSD/SD карты
        target: /tmp/cache
        tmpfs:
          size: 3000000000
    ports:
      - "1984:1984"
      - "5000:5000"
      - "1935:1935"
      - "8554:8554" # RTSP-потоки
      - "8555:8555/tcp" # WebRTC по TCP
      - "8555:8555/udp" # WebRTC по UDP
    device_cgroup_rules:
      - "c 189:* rmw"
```

### Relevant Frigate log output

```shell
no
```

### Relevant go2rtc log output

```shell
no
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

xmey

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/a7ecd6c0-acc2-45ea-9933-6d9b27f87e20)
