### DISCUSSION TITLE
[Config Support]: Notifications of alerts not all detections & only alert if in a zone

### DISCUSSION THREAD

**Discussion by mad-tunes** [blakeblackshear/frigate#18516] [Config Support]
### Describe the problem you are having

I'm trying to get Frigate set up with a couple of esp32cam cameras, to be the cheapest DVR possible.
Frigate's running in my HA VM in Hyper-v on a PC.
I'm aware it'll never be amazing but this is the gear I have to play with.

Using one of the cameras as an example:
The esp32cam is currently set to 1280x1024. I've used to go2rtc to get the stream.
I've used the Frigate Notifications blueprint to get notifications sent to my android phone.

![image](https://github.com/user-attachments/assets/8694043a-bcf9-4504-9fc9-06ccd65ac453)
I'd like to be sent notifications on my phone, and have video recorded, when people or cats are detected on the lawn/path, but would like anything past the edge of the lawn to be completely ignored.

Motion detection and detection of people seem to be working pretty well, but there are some things I haven't been able to get right:
![image](https://github.com/user-attachments/assets/cd7547b5-aa4a-4783-8ed3-faef0e91dd62)
I've defined a zone that covers the lawn and set that in required_zones, but I'm notified about detected objects that are on the other site of the road nowhere near the zone. 
I rigged up a recent recording of people walking on the far side of the road as a camera, In Debug it looks like this:
![image](https://github.com/user-attachments/assets/197e2312-2585-42fd-9250-fd0e64b03f65)
..the light green box is covering everything for the entire time they're in the cameras view.

Browsing to http://HA_IP:5000/api/Test/grid.jpg shows this:
![image](https://github.com/user-attachments/assets/46e0ad43-c772-4c71-91c4-be3672b0bb4c)
..which tbh I just don't understand.

In Frigates gui, the video/period shows under Detections.
I was sent a notification on my phone.

I'd like to notified if they walked up the path to the door or on the lawn (in the zone), but not with them being over the other side of the road.
Can anyone see what I'm doing wrong, or suggest what I need to change please?

### Version

0.15.1

### Frigate config file

```yaml
go2rtc:
  streams:
    Front: ffmpeg:http://192.168.5.59:8080#video=h264#hardware=preset-vaapi

cameras:
  Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front
          roles:
            - detect
            - record
    review:
      alerts:
        required_zones: Front_grass
    detect:
      # enabled: false
      enabled: true
      width: 320
      height: 240
      fps: 5
    objects:
      track:
        - person
        - bird
        - cat
    motion:
      enabled: true
      threshold: 40
      contour_area: 35
      improve_contrast: false
      mask: 0,0,0,0.078,0.478,0.078,0.478,0
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: false
      crop: false
      retain:
        default: 14
        mode: active_objects
        objects:
          person: 30
      quality: 100
    zones:
      Front_grass:
        coordinates: 1,0.698,1,1,0,1,0,0.8,0.194,0.717,0.555,0.668,0.848,0.656
        loitering_time: 0
        objects:
          - bird
          - person
          - cat
        inertia: 3
```

### Relevant Frigate log output

```shell
I dont have frigates log for the period I'm using as an example, if its required I'll have to wait for another event.
```

### Relevant go2rtc log output

```shell
I dont have go2rtcs log for the period I'm using as an example, if its required I'll have to wait for another event.
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Object Detector

CPU (no coral)

**Comment by NickM-27** [comment]
You need to configure your blueprint to only sent notifications for alerts.

**Comment by mad-tunes** [comment]
Thanks.
I swear I'd looked before and not found it, so then I started looking more at Frigate.
Just taken another look though and there it is, a simple tick box:
![image](https://github.com/user-attachments/assets/1027814b-80c1-43f5-8eee-abadad6d3271)

Is there a way to have Frigate completely ignore people on the other side of the road though, rather than it recording a detection and the blueprint filtering that out? It just doesnt need any attention/detection/recording at all.

Is the green box covering the whole frame (3rd pic) normal and not a problem?
Because this is running on a CPU, I'm trying to keep the work Frigate's doing to the minimum possible

**Reply by NickM-27** [reply]
Make the zone required for detections too

**Reply by mad-tunes** [reply]
I cant add it to Detect: without it complaining.
Should it be in Review too like this?
```
    review:
      alerts:
        required_zones: Front_grass
      detections:
        required_zones: Front_grass
```
