### DISCUSSION TITLE
Frigate crashes when frigate+ fine tuned models used

### DISCUSSION THREAD

**Discussion by nfarrar3** [blakeblackshear/frigate#18521] [Config Support]
### Describe the problem you are having

I'm running TrueNAS 25.04.01 on an AMD Ryzen 9 9950x3d processor and iGPU. Storage for Frigate is on NVME. I'm using the ROCM based im. When I add the fine tuned model to my config, frigate crashes. I need help finding relevant logs, please. I'm using the app from the TrueNAS library. 

I'm passing the frigate+ key in env variables and can send images to frigate+. Thats how I trained the model but frigate crashes when I add 

model:
  path: plus://keyxyz

My reindexing appears to utilize the GPU. Could I have frigate to detect objects in streams via CPU?

### Version

0.15.1

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  Garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:xxxx@10.0.0.91:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif         # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
      filters:
        car:
          mask: 
            0.636,0.985,0.819,0.473,0.711,0.118,0.537,0.082,0.476,0.061,0.381,0.081,0.332,0.057,0.254,0.076,0.215,0.13,0.208,0.191,0.223,0.306,0.211,0.465,0.239,0.571,0.459,0.932
  Front_PTZ:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@10.0.0.92:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
    onvif:
      host: 10.0.0.92
      port: 80
      user: admin
      password: xxxx
      autotracking:
        enabled: true
        required_zones:
          - Street
        return_preset: preset2
        calibrate_on_startup: true
        movement_weights: 0.0, 1.0, 0.00010895729064941406, 1226028596.2061021, -620108260.133529
    detect:
      enabled: true
    zones: {}
    motion: {}
  Front_Yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:xxxx@10.0.0.93:554/cam/realmonitor?channel=1&subtype=0    # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
      filters:
        car: {}
  Frontdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:xxxx@10.0.0.94:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif         # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    motion:
      mask:
        - 0.857,0.146,0.857,0.186,0.837,0.417,0.822,0.439,0.789,0.451,0.771,0.493,0.753,0.606,0.757,0.679,0.784,0.751,0.835,0.787,0.868,0.814,0.896,0.912,0.913,0.998,1,1,1,0.673,0.999,0.249
        - 0.247,0.488,0.255,0.469,0.275,0.467,0.311,0.494,0.323,0.599,0.295,0.685,0.251,0.686,0.238,0.586
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
      filters:
        car:
          mask: 
            0.671,-0.002,0.67,0.132,0.808,0.164,0.834,0.172,0.9,0.179,0.853,0.132,0.753,0.048
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:xxxx@10.0.0.97:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif         # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
  Corner_PTZ:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:xxxx@10.0.0.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif         # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
    onvif:
      host: 10.0.0.95
      port: 80
      user: frigate
      password: xxxxx
  DataCenter:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:XXXX@10.0.0.96:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif         # <----- The stream you want to use for detection
          roles:
            - record
            - detect
    detect:
      width: 3840
      height: 2160
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: motion
    objects:
      track:
        - car
        - person
        - dog
        - cat
        - cell
semantic_search:
  enabled: true
  reindex: true
  model_size: large
version: 0.15-1
# model:
# path: plus://947374528965df664cf8dexxxxxxxxxx
camera_groups:
  Main:
    order: 1
    icon: LuHome
    cameras:
      - Front_PTZ
      - Front_Yard
      - Frontdoor
      - Driveway
      - Garage
  Birdseye:
    order: 2
    icon: LuEye
    cameras: birdseye
```

### Relevant Frigate log output

```shell
Frigate crasheed too quickly for me to be able to grab logs. 

I saw ffmpeg complaining about pytorch.

Then ffmpeg starts shutting down and that's all she wrote.
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
Using the TrueNAS cataloged app.
```

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

![Screen Shot 2025-06-01 at 05 43 49 860 PM](https://github.com/user-attachments/assets/b6c59a7f-8f42-46da-ba53-e80636883e38)

**Comment by hawkeye217** [comment]
First, you should disable `reindex: true` (set it to `false`). You shouldn't be reindexing your tracked object embeddings on every startup. This is only needed once.

Second, you are still using your CPU for object detection. This is not recommended. See the documentation: https://docs.frigate.video/configuration/object_detectors/

What variant of Frigate+ model did you train? mobiledet or yolonas/onnx?

**Reply by nfarrar3** [reply]
Could you please give me a hand? I've been reading that page for a few days. I am running the ROCM-specific image, and that should detect the AMD GPU and use ONNX automatically, based on the instructions. When I add the detectors:
  onnx_0:
    type: onnx
Frigate crashes on me.

**Reply by hawkeye217** [reply]
There is no default model provided with the `rocm` image - you need to generate one. https://docs.frigate.video/configuration/object_detectors/#supported-models-1

**Reply by nfarrar3** [reply]
Git isn't installed on the container. Do I need to download and build the model on a PC or does it need to be done within the container itself?

**Reply by NickM-27** [reply]
If it use onnx detector and have a yolonas frigate+ model then it will work. Do you have frigate+?

**Reply by nfarrar3** [reply]
> There is no default model provided with the `rocm` image - you need to generate one. https://docs.frigate.video/configuration/object_detectors/#supported-models-1

Thank you very much!

I used the note on the documentation page to build and download the yolonas model. Then put it in the config dir. Next, I added the rocm detector.

I'm now running on GPU! Thank you very much for the help.

**Reply by hawkeye217** [reply]
Great! Glad it's working for you.

As @NickM-27 said above, if you have a Frigate+ model, you should just be able to use the onnx detector, assuming you submitted the model request with the "yolonas" type.

![Screenshot 2025-06-01 at 7 19 52 PM](https://github.com/user-attachments/assets/7aab1974-e205-40d0-b870-5e4f10503a37)


```
detectors:
  onnx_0:
    type: onnx

model:
  path: plus://...
```
