### DISCUSSION TITLE
[Config Support]: Frigate isn't clearing old files?

### DISCUSSION THREAD

**Discussion by MitchWuk** [blakeblackshear/frigate#18527] [Config Support]
### Describe the problem you are having

I have set the retention period to 21 days, but I can see that in my Cloud Storage, there is 8.6TB of data, whereas I know that it should be around 3-4TB, but I have just double checked and it is currently 8.6TB.

I've also checked, and there is LOTS of items that is left from well-over 21 days ago (as this is set on all of my retentions)

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
(Stripped for size)
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    DrivewayCam:
      - rtsp://admin:{PASSWORD}@{IP ADDRESS}:554/h264Preview_01_main
    DrivewayCam_Detect:
      - rtsp://admin:{PASSWORD}@{IP ADDRESS}:554/h264Preview_01_main
    DrivewayCam_Live:
      - rtsp://admin:{PASSWORD}@{IP ADDRESS}:554/h264Preview_01_sub
cameras:
  DrivewayCam: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/DrivewayCam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/DrivewayCam_Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    record: ##Recording Settings
      enabled: true
      retain:
        days: 21
    live:
      stream_name: DrivewayCam_Live
    detect: ##Detection settings for quality and Framerate
      width: 1280
      height: 720
      fps: 7
    motion:  ##Masking and Threshold to determine events
      threshold: 50
      contour_area: 25
      improve_contrast: true
      mask: 0,0.833,0.432,0.615,0.984,0.749,0.983,0.99,0.006,0.992
    objects: ##Object Setup
      track:
        - person
        - car
        - horse
        - dog
        - cat
        - truck
      filters:
        car:
          mask: 0.637,0.566,0.984,0.639,0.986,0.399,0.693,0.364
        truck: {}
    zones:
      Driveway:
        coordinates: 0.055,0.513,0.115,0.777,0.665,0.5,0.595,0.369
        inertia: 2
        loitering_time: 1
        objects:
          - car
          - dog
          - person
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "8192mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/:/config/
      - /opt/frigate/media/:/media/frigate/
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "443:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "{PASSWORD}"
```

### Object Detector

CPU (no coral)

**Comment by hawkeye217** [comment]
Do your tracked objects have snapshots? Those are governed by a separate retention policy, and will prevent tracked objects from being purged.

**Reply by MitchWuk** [reply]
Where would i check to see this? Also - what settings would be needed to stop this from happening if it is?

**Reply by hawkeye217** [reply]
The default snapshot retention is 10 days. If you have enabled snapshots in your config, you would see them in the Tracked Object Details pane in Explore. 

If you haven't enabled them, there's likely another issue. 

Frigate doesn't use cloud storage, can you describe your setup more?

**Reply by MitchWuk** [reply]
Ah, this may be it.

![image](https://github.com/user-attachments/assets/bcc25f2c-6076-43b2-8269-11a60288c3e0)

Is there a way to have it so that once there has been an activation, it waits until the object is out of frame before re-activating? (i.e. the horses can be on the yard for up to 4 hours at a time, but it goes off continuously)

--

I am using rclone to mount a network drive to /opt/frigate/media then linking folder to Frigate so that it directly stores into the GDrive cloud storage (I've been through S3, and Shared Drives, found this to be the most stable).

**Reply by hawkeye217** [reply]
> Is there a way to have it so that once there has been an activation, it waits until the object is out of frame before re-activating? (i.e. the horses can be on the yard for up to 4 hours at a time, but it goes off continuously)

You could try lowering your threshold and min_score for `horse` so that the same object is not lost and then re-tracked as a new object. But this won't reduce the amount of space that these tracked objects use.

**Reply by MitchWuk** [reply]
Is this applicable to non-pro versions? If so, could you please send me the config for this as I would gladly do this!

--
I believe it is probably down to the amount of detections rather than anything else

**Reply by hawkeye217** [reply]
> Is this applicable to non-pro versions? If so, could you please send me the config for this as I would gladly do this!

I'm referring to just a standard object filter, Frigate+ is not necessary.

https://docs.frigate.video/configuration/object_filters

> I believe it is probably down to the amount of detections rather than anything else

Yes, it's likely just related to the number of detections and how long they remain in your scene. You could adjust the retention time for `horse` only, if you want.

For example:
```
record:
  enabled: True
  alerts:
    retain:
      days: 30  # Default retention for alerts
      mode: motion
  detections:
    retain:
      days: 14  # Default retention for detections
      mode: motion

review:
  alerts:
    labels:
      - person  # Only persons trigger alerts (longer retention)
  detections:
    labels:
      - horse     # Horses only trigger detections (shorter retention)
```

**Reply by MitchWuk** [reply]
Ahh cool cool - Horses already come under detections anyway, so it'll just be a case of setting the retention time (We only have them on there for 1 camera anyway because we only want to know when they come on the Yard).

Where would I add the threshold value for this camera? I can see that motion is already tuned for 65 / 30 contor:

  Yard1: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Yard1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Yard1_Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    record: ##Recording Settings
      enabled: true
      retain:
        days: 21
    live:
      stream_name: Yard1_Live
    detect: ##Detection settings for quality and Framerate
      width: 1280
      height: 720
      fps: 4
    objects:
      track:
        - horse
    motion:
      threshold: 60
      contour_area: 35
      improve_contrast: true

**Reply by hawkeye217** [reply]
This is an object threshold, so you could try:

```
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - horse
    ...
  # Optional: filters to reduce false positives for specific object types
  filters:
    horse:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
```

You could just leave out the area and ratio values and leave those at the defaults, but I showed them here for completeness.
