### DISCUSSION TITLE
[Detector Support]: Can't detect birds

### DISCUSSION THREAD

**Discussion by Struggle2020** [blakeblackshear/frigate#18523] [Detector Support] [answered]
### Describe the problem you are having

I stripped back my initial config and have sent a vlc rtsp stream loop for testing birds. No matter what it won't detect them but is detecting motion fine. My old config works brilliantly for people/dogs etc. Just trying to get a basic config worknig before i merge iti all back to the old one. Thank you

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.68.51
  port: 1883

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30


cameras:
  TEST:
    objects:
      track:
        - bird
      filters:
        bird:
          # Optional: minimum score for the object to initiate tracking
          min_score: 0.1
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.68.193:8554/loop
          input_args: preset-rtsp-udp
          roles:
            - detect
    detect:
      width: 862
      height: 480
    motion:
      threshold: 16
      contour_area: 10
      improve_contrast: false
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    privileged: true
    container_name: "frigate"
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/user/containers/frigate/config:/config
      - /mnt/user/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
    environment:
      TZ: "<removed>"
      FRIGATE_RTSP_PASSWORD: "<removed>"
      PLUS_API_KEY: "<removed>"
```

### Relevant Frigate log output

```shell
n/a
```

### Install method

Docker Compose

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

n/a

### Any other information that may be helpful

![bird test](https://github.com/user-attachments/assets/dcbb8849-9aed-44ec-9f18-1adcb5c75ee0)
