### DISCUSSION TITLE
Add ability to create alias names for PTZ presets and suppress display of unused presets

### DISCUSSION THREAD

**Discussion by peteDDD** [blakeblackshear/frigate#18537] [Ideas]
Some cameras allow one to name the PTZ presets on the camera... others do not and only provide default names like "preset001".  It would be very useful to be able to provide alias names for each camera's presets.  

Also, allow for supressing the display of unused or undesired presets.  So, for example, maybe something like this:

```
cameras:
  camera1:
  ... 
     onvif:
       ... 
         presets:
            - rename:
                name: "preset001"
                alias "Front Gate"
            - rename:
                 name: "preset002"
                 alias: "West"
            - rename: 
                 name: "preset003"
                 alias: "East"
             - supress:
                 - "preset004"
                 - "preset005"
                ...
                 - "preset009"
```
                
Thank you for your consideration.  (this is a feature in Blue Iris that I miss having).
