### DISCUSSION TITLE
[Support]: Random Cameras stop recording and start again on reboot

### DISCUSSION THREAD

**Discussion by MitchWuk** [blakeblackshear/frigate#18546] [General Support]
### Describe the problem you are having

Every now and then, one of the cameras seems to drop off recording or the detection stream, but never comes back up.

After rebooting Frigate, it seems to restore the feed, but leaves me without a chunk of recordings for sections.

Happy to supply logs etc... but was too long for the body of Github

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Chrome Version 136.0.7103.114

### Frigate config file

```yaml
.
```

### Relevant Frigate log output

```shell
.
```

### Relevant go2rtc log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
.
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Custom

**Comment by MitchWuk** [comment]
**Config**

```
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
 
    Yard2:
      - rtsp://[IP RANGE].203:554/user=admin_password=[PASSWORD]_channel=0_stream=0
      - ffmpeg:Yard2#video=h264#hardware
    Yard2_Detect:
      - rtsp://[IP RANGE].203:554/user=admin_password=[PASSWORD]_channel=0_stream=1
      - ffmpeg:Yard2_Detect#video=h264#hardware
    Yard2_Live:
      - rtsp://[IP RANGE].203:554/user=admin_password=[PASSWORD]_channel=0_stream=1
      - ffmpeg:Yard2_Live#video=h264#hardware
	  
cameras:
  Yard2: ##Camera Name
    enabled: true ##Whether it is enabled or not
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Yard2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Yard2_Detect
          input_args: preset-rtsp-restream
          roles:
            - detect
    record: ##Recording Settings
      enabled: true
      retain:
        days: 21
    live:
      stream_name: Yard2_Live
    detect: ##Detection settings for quality and Framerate
      width: 1280
      height: 720
      fps: 4
    objects:
      track:
        - plane
    motion:
      threshold: 60
      contour_area: 30
      improve_contrast: true
      mask: 
        0.048,0.145,0.315,0.068,0.439,0.062,0.642,0.072,0.814,0.109,0.966,0.135,0.994,0.143,0.997,0.007,0.239,0,0.007,0.007,0.005,0.059,0.032,0.116
    zones: {}
version: 0.15-1
```
