### DISCUSSION TITLE
[Bug]: If embeddings manager crashes there is no indication of failure in UI

### DISCUSSION THREAD

**Discussion by jamesh76** [blakeblackshear/frigate#18547] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

One of my tensorrt systems is fairly restricted on video memory, and I've found that the embeddings manager can run out of memory and crash. When this happens, the service does not automatically restart, and the only indication of a problem within the UI is that the semantic search will not work.  I don't think this is a problem with the embeddings manager itself, but I would expect a warning that the service is not running within the UI similar to other warnings.

### Steps to reproduce

1. Install Frigate-tensorrt with all hardware accelerated embeddings enabled.
2. Allow just enough video memory for everything to load and initially operate normally.
3. Wait for the embeddings manager to attempt to address more video memory and crash.  On my system this can take between hours and days.
...

### Version

0.16.0-1fa7ce5

### Frigate config file

```yaml
mqtt:
  host: 172.17.0.1
  user: [USER]
  password: [PASSWORD]
  topic_prefix: frigate
  enabled: true
motion:
  threshold: 35
record:
  enabled: true
  retain:
    days: 90
    mode: active_objects
  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
birdseye:
  enabled: true
  mode: continuous
  restream: true
  width: 1920
  height: 1080
audio:
  enabled: false
detect:
  stationary:
    interval: 50
    threshold: 50
  enabled: true
snapshots:
  enabled: true
  timestamp: false
  crop: true
timestamp_style:
  position: tl
  effect: solid
ffmpeg:
#  hwaccel_args: ''
  hwaccel_args: preset-nvidia
detectors:
  TensorRT1:
    type: tensorrt
  TensorRT2:
    type: tensorrt
  TensorRT3:
    type: tensorrt
  TensorRT4:
    type: tensorrt
model:
  path: /config/model_cache/tensorrt/yolov4-tiny-288.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 288
  height: 288
  labelmap:
    1: car
    2: car
    3: car
    4: car
    5: car
    6: car
    7: car
    8: car
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal
objects:
  track:
    - person
    - animal
    - car
#detectors:
#  onnx_0:
#    type: onnx
#  onnx_1:
#    type: onnx
#model:
#  path: plus://[PLUSMODEL]
go2rtc:
  streams:
    Fisheye_Origin:
      - rtsp://[USER]:[PASSWORD]@192.168.70.214:554/Streaming/Channels/1
    Office_Fisheye:
      - ffmpeg:Fisheye_Origin#video=h264#raw=-vf 
        scale=1500:2000,v360=fisheye:equirect:ih_fov=180:iv_fov=180:roll=90:pitch=90:rorder=rpy,crop=2250:1000:750:1000
#      - ffmpeg:Office_Fisheye#video=h264#raw=-vf 
#        scale=1500:2000,v360=fisheye:equirect:ih_fov=180:iv_fov=180:roll=90:pitch=90:rorder=rpy,crop=3000:1000:0:1000
    PTZ_1:
      - rtsp://[USER]:[PASSWORD]@192.168.70.201:554/Streaming/Channels/1
    PTZ_2:
      - rtsp://[USER]:[PASSWORD]@192.168.70.203:554/Streaming/Channels/1
    PTZ_3:
      - rtsp://[USER]:[PASSWORD]@192.168.70.204:554/Streaming/Channels/1
    PTZ_4:
      - rtsp://[USER]:[PASSWORD]@192.168.70.205:554/Streaming/Channels/1
    AXIS_1:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.226/axis-cgi/mjpg/video.cgi?camera=1#video=h264#hardware
    AXIS_2:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.226/axis-cgi/mjpg/video.cgi?camera=2#video=h264#hardware
    AXIS_3:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.226/axis-cgi/mjpg/video.cgi?camera=3#video=h264#hardware
    AXIS_4:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.226/axis-cgi/mjpg/video.cgi?camera=4#video=h264#hardware
    AXIS_5:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.227/axis-cgi/mjpg/video.cgi?camera=1#video=h264#hardware
    AXIS_6:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.227/axis-cgi/mjpg/video.cgi?camera=2#video=h264#hardware
    AXIS_7:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.227/axis-cgi/mjpg/video.cgi?camera=3#video=h264#hardware
    AXIS_8:
      - ffmpeg:http://[USER]:[PASSWORD]@192.168.70.227/axis-cgi/mjpg/video.cgi?camera=4#video=h264#hardware
    Storage_Parking:
      - rtsp://[USER]:[PASSWORD]@192.168.70.202:554/Streaming/Channels/1
    Laminators:
      - rtsp://[USER]:[PASSWORD]@192.168.70.206:554/Streaming/Channels/1
    T-Shirt_Garage:
      - rtsp://[USER]:[PASSWORD]@192.168.70.207:554/Streaming/Channels/1
    Storage_Hallway_2:
      - rtsp://[USER]:[PASSWORD]@192.168.70.208:554/Streaming/Channels/1
    Vinyl:
      - rtsp://[USER]:[PASSWORD]@192.168.70.209:554/Streaming/Channels/1
    Sewing:
      - rtsp://[USER]:[PASSWORD]@192.168.70.210:554/Streaming/Channels/1
    Aluminum_Dumpsters:
      - rtsp://[USER]:[PASSWORD]@192.168.70.211:554/Streaming/Channels/1
    Storage_Behind:
      - rtsp://[USER]:[PASSWORD]@192.168.70.212:554/Streaming/Channels/1
    Storage_Behind_2:
      - rtsp://[USER]:[PASSWORD]@192.168.70.228:554/Streaming/Channels/1
    Storage_Hallway_3:
      - rtsp://[USER]:[PASSWORD]@192.168.70.218:554/Streaming/Channels/1
    Storage_Hallway_1:
      - rtsp://[USER]:[PASSWORD]@192.168.70.219:554/Streaming/Channels/1
    Storage_Front_Hallway:
      - rtsp://[USER]:[PASSWORD]@192.168.70.222:554/Streaming/Channels/1
    Storage_Parking_2:
      - rtsp://[USER]:[PASSWORD]@192.168.70.223:554/Streaming/Channels/1
    Router:
      - rtsp://[USER]:[PASSWORD]@192.168.70.224:554/Streaming/Channels/1
    T-Shirt_Shop:
      - rtsp://[USER]:[PASSWORD]@192.168.70.225:554/Streaming/Channels/1
    Print_Room_1:
      - rtsp://[USER]:[PASSWORD]@192.168.70.215:554/Streaming/Channels/101
    Print_Room_2:
      - rtsp://[USER]:[PASSWORD]@192.168.70.215:554/Streaming/Channels/201
    Print_Room_3:
      - rtsp://[USER]:[PASSWORD]@192.168.70.215:554/Streaming/Channels/301
    Print_Room_4:
      - rtsp://[USER]:[PASSWORD]@192.168.70.215:554/Streaming/Channels/401
cameras:
#  REOLINK:
#    ffmpeg:
#      inputs:
#        - path: rtsp://[USER]:[PASSWORD]@192.168.70.105:554/Preview_01_main
#          roles:
#            - record
#            - detect
#    zones:
#      Sign_Planet:
#        coordinates: 0,0,3000,0,5000,3000,0,5000
#    detect:
#      width: 1920
#      height: 1080
#      fps: 4
#     birdseye:
#      enabled: false
#  pagnozzi1:
#    ffmpeg:
#      inputs:
#        - path: /config/pagnozzi1.mp4
#          input_args: -re -stream_loop -1 -fflags +genpts
#          roles:
#            - record
#            - detect
#    detect:
#      width: 1920
#      height: 1080
#      fps: 4
#    birdseye:
#      enabled: false
  PTZ_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/PTZ_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 4
    birdseye:
      enabled: false
    onvif:
      host: 192.168.70.201
      port: 80
      user: [USER]
      password: [PASSWORD]
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zoom_factor: 0.3
        zooming: relative
        required_zones:
          - any
#        return_preset: 1
    notifications:
      enabled: false
  PTZ_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/PTZ_2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 4
    birdseye:
      enabled: false
    onvif:
      host: 192.168.70.203
      port: 80
      user: [USER]
      password: [PASSWORD]
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zoom_factor: 0.3
        zooming: relative
        required_zones:
          - any
#        return_preset: 1
    notifications:
      enabled: false
  PTZ_3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/PTZ_3
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 4
    birdseye:
      enabled: false
    onvif:
      host: 192.168.70.204
      port: 80
      user: [USER]
      password: [PASSWORD]
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zoom_factor: 0.3
        zooming: relative
        required_zones:
          - any
#        return_preset: 1
    notifications:
      enabled: false
  PTZ_4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/PTZ_4
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 4
    birdseye:
      enabled: false
    onvif:
      host: 192.168.70.205
      port: 80
      user: [USER]
      password: [PASSWORD]
      autotracking:
        enabled: true
        calibrate_on_startup: true
        zoom_factor: 0.3
        zooming: relative
        required_zones:
          - any
 #       return_preset: 1
    notifications:
      enabled: false
  Storage_Parking:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Parking
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 1255,335,466,439,0,394,0,25
      Sign_Planet:
        coordinates: 1280,487,1280,960,0,960,0,780
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      mask: 0,0,0,0.149,1,0.184,0.995,0.002
    notifications:
      enabled: false
  Office_Fisheye:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Office_Fisheye
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    audio:
      enabled: true
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 2250
      height: 1000
      fps: 4
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Laminators:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Laminators
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_Garage:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/T-Shirt_Garage
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Storage_Hallway_2:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Hallway_2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 0,0,1280,0,1280,960,0,960
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Vinyl:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Vinyl
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Sewing:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Sewing
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Aluminum_Dumpsters:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Aluminum_Dumpsters
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    objects:
      filters:
        car: {}
    motion:
      mask: 0,0,1,0,1,0.271,0,0.188
    notifications:
      enabled: false
  Storage_Behind:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Behind
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 0,0,1280,0,1280,960,0,960
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    notifications:
      enabled: true
  Storage_Behind_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Behind_2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 0,0,1280,0,1280,960,0,960
    detect:
      width: 3840
      height: 2160
      fps: 4
    birdseye:
      enabled: false
    notifications:
      enabled: true
  Storage_Hallway_3:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Hallway_3
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 0,0,1280,0,1280,960,0,960
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Storage_Hallway_1:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Hallway_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 0,0,1280,0,1280,960,0,960
    detect:
      width: 1280
      height: 960
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Storage_Front_Hallway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Front_Hallway
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 2560
      height: 1920
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Storage_Parking_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Storage_Parking_2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Storage:
        coordinates: 1101,367,3840,1202,3840,2160,0,2160,0,487
    detect:
      width: 3480
      height: 2160
      fps: 4
    birdseye:
      enabled: false
    notifications:
      enabled: false
  Router:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Router
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 3480
      height: 2160
      fps: 4
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    notifications:
      enabled: false
  T-Shirt_Shop:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/T-Shirt_Shop
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 3480
      height: 2160
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO1:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_1
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO2:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_2
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO3:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_3
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO4:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_4
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO5:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_5
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO6:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_6
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO7:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_7
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  T-Shirt_VIDEO8:
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/AXIS_8
          roles:
            - record
            - detect
    zones:
      T-Shirt:
        coordinates: 0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
    detect:
      width: 704
      height: 480
      fps: 4
    birdseye:
      enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Print_Room_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Print_Room_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 2560
      height: 1920
      fps: 4
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Print_Room_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Print_Room_2
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 2560
      height: 1920
      fps: 4
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Print_Room_3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Print_Room_3
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 2560
      height: 1920
      fps: 4
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
  Print_Room_4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Print_Room_4
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      Sign_Planet:
        coordinates: 0,0,3000,0,5000,3000,0,5000
    detect:
      width: 2560
      height: 1920
      fps: 4
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    notifications:
      enabled: false
version: 0.16-0
notifications:
  enabled: false
  email: james@signplanet.com
semantic_search:
  enabled: true
  reindex: false
  model_size: large
camera_groups:
  Outdoor:
    order: 1
    icon: LuFlag
    cameras:
      - PTZ_1
      - PTZ_2
      - PTZ_3
      - PTZ_4
      - Storage_Parking
      - Aluminum_Dumpsters
      - Storage_Parking_2
      - Storage_Behind_2
      - Storage_Behind
  Sign_Planet:
    order: 2
    icon: LuSlice
    cameras:
      - Office_Fisheye
      - Laminators
      - Vinyl
      - Sewing
      - Router
      - Print_Room_1
      - Print_Room_2
      - Print_Room_3
      - Print_Room_4
  Storage:
    order: 3
    icon: LuPackageOpen
    cameras:
      - Storage_Parking
      - Storage_Hallway_2
      - Storage_Hallway_3
      - Storage_Hallway_1
      - Storage_Front_Hallway
      - Storage_Parking_2
  T-Shirt_Shop:
    order: 4
    icon: LuShirt
    cameras:
      - T-Shirt_Garage
      - T-Shirt_Shop
      - T-Shirt_VIDEO1
      - T-Shirt_VIDEO2
      - T-Shirt_VIDEO3
      - T-Shirt_VIDEO5
      - T-Shirt_VIDEO7
      - T-Shirt_VIDEO8
      - T-Shirt_VIDEO6
      - T-Shirt_VIDEO4
face_recognition:
  enabled: true
  model_size: large
  save_attempts: 500
  min_area: 1000
lpr:
  enabled: true
  device: GPU
classification:
  bird:
    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: false
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "3072mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/james/frigate/config/:/config/
      - /home/james/frigate/storage:/media/frigate
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "8971:8971" # Authenticated Web UI
      - "5000:5000" # Port used by the Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "[USER]:[PASSWORD]"
      PLUS_API_KEY: "[PLUSKEY]"
      YOLO_MODELS: "yolov4-288,yolov4-tiny-288,yolov4-tiny-416"
```

### Relevant Frigate log output

```shell
Forgot to grab these, will add if needed.
```

### Relevant go2rtc log output

```shell
Forgot to grab these, will add if needed.
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision

### Screenshots of the Frigate UI's System metrics pages

Forgot to grab these.  Will add if needed.
