### DISCUSSION TITLE
[Config Support]:  transition from zone to zone

### DISCUSSION THREAD

**Discussion by Vladd1980** [blakeblackshear/frigate#18551] [Config Support]
### Describe the problem you are having

I have a garden_in and garden_out zone. I want to track exactly the transition of a person from garden_out to garden_in, thus excluding detection of myself, but only strangers. I read this: 
https://docs.frigate.video/configuration/zones/ I have repeatedly tried to repeat this, but I can not get a trigger for automation. Perhaps someone could post their example or explain how to implement this

### Version

0,16beta3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.200.9
  port: 1883
  topic_prefix: frigate2
  client_id: frigate2
  user: *****
  password: *****

detectors:
  ov:
    type: openvino
    device: CPU
  ov_1:
    type: openvino
    device: CPU
  ov_2:
    type: openvino
    device: CPU

ui:
  time_format: 24hour

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  path: /openvino-model/ssdlite_mobilenet_v2.xml


semantic_search:
  enabled: true
  model_size: small
  reindex: false

genai:
  enabled: true
  provider: gemini
  api_key: *****
  model: gemini-2.5-flash-preview-04-17
  prompt: |
    ******
logger:
  default: info

face_recognition:
  enabled: true
  model_size: small
  min_area: 10000
  recognition_threshold: 0.95
  unknown_score: 0.95
#  recognition_threshold: 0.7
#  unknown_score: 0.5


lpr:
  enabled: true
  model_size: small
  debug_save_plates: true
#  min_plate_length: 4
#  match_distance: 1
#  min_area: 5000
#  format: ^[A-Z]{2}[0-9]{4} [A-Z]{2}$
#  min_area: 1500 # Ignore plates smaller than 1500 pixels
#  min_plate_length: 4 # Only recognize plates with 4 or more character


record:
  sync_recordings: true
  expire_interval: 720
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 15

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  clean_copy: false
  retain:
    default: 30

ffmpeg:
#  hwaccel_args: preset-vaapi
  input_args:
    - -re
    - -rtsp_transport
    - tcp
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:

    TGarden1:
      - rtsp://192.168.201.3:554/user=****&password=*****&channel=8_stream=0?.sdp#video=h265#audio=aac#audio=opus
    TGarden1_sub:
      - rtsp://192.168.201.3:554/user=****&password=******&channel=8_stream=1?.sdp#audio=h265#audio=aac#audio=opus
cameras:
TGarden1:
    enabled: true
    detect:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:Star0679405359.@127.0.0.1:8554/TGarden1 #go2rtc
          roles:
            - record
        - path: rtsp://admin:Star0679405359.@127.0.0.1:8554/TGarden1_sub
          roles:
            - detect
    live:
      streams:
        none: none
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.5
          min_area: 1000
          max_ratio: 1
        dog:
          min_ratio: 1
    genai:
      enabled: false
    motion:
      contour_area: 53
      threshold: 47
      mask: 0,0,0,0.124,1,0.118,1,0
      improve_contrast: true

    review:
      detections:
        required_zones:
          - garden1_out
      alerts:
        required_zones:
          - garden1_in

    zones:
      garden1_in:
        coordinates: 0,0.406,0.001,0.999,1,1,1,0.032,0.633,0.036
        loitering_time: 0
        objects:
          - person
        inertia: 3
      garden1_out:
        coordinates: 0.001,0.394,0,0.006,1,0,1,0.018,0.628,0.021
        loitering_time: 0
        objects:
          - person
        inertia: 3
     version: 0.16-0
```

### Relevant Frigate log output

```shell
*****
```

### Relevant go2rtc log output

```shell
*****
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
******
```

### Object Detector

OpenVino
