### DISCUSSION TITLE
[Config Support]: Entities for Audio Triggers

### DISCUSSION THREAD

**Discussion by TheSimTek** [blakeblackshear/frigate#18558] [Config Support] [answered]
### Describe the problem you are having

I would like to create an automation to play a 20 KHz tone every time the neighbour brings her dog onto my nature strip and it starts barking.
I have many triggers for visual objects but cannot find the entities for the audio triggers.
For this camera I am using -
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - speech
        - siren
        - yell
        - police_car
        - motorcycle

The camera picks up speech and sirens but as yet the pest barking.  
I do not want to trigger the automation unless it starts barking.

### Version

0.15-1

### Frigate config file

```yaml
Frigate file -
  Streetview:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://***secret****@192.168.254.112:554/Streaming/Channels/102
          roles:
            - detect
            - clips
            - record
            - rtmp
            - audio
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
#     - car
        - motorcycle
        - bicycle
        - person
        - dog
        - cat
#      filters:
#        person:
#          min_area: 150
#          max_area: 5000
#          threshold: 0.6
#        motorcycle:
#          min_area: 150
#          max_area: 5000
#          threshold: 0.6
    audio:
      enabled: true
      listen:
        - bark
        - scream
        - speech
        - siren
        - yell
        - police_car
        - motorcycle
    snapshots:
      enabled: true
    record:
      sync_recordings: true
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 7
```

### Relevant Frigate log output

```shell
Nothing in the log regarding audio events
```

### Relevant go2rtc log output

```shell
Nil
```

### Frigate stats

```json
Nil
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
Nil
```

### Object Detector

Coral
