### DISCUSSION TITLE
[Camera Support]: Reolink 5MP Doorbell often hangs with "missing frames" and skipped_fps >100 in overview, but stream loads correctly on detail view

### DISCUSSION THREAD

**Discussion by cg089** [blakeblackshear/frigate#18555] [Camera Support]
### Describe the problem you are having

I’m experiencing an issue with my Reolink Doorbell camera in Frigate (running in Docker). In the main overview of all cameras, the preview of the Reolink Doorbell frequently turns black and displays the error message missing frames. However, when I click on the individual camera to view the live stream, the feed loads correctly and shows the video without issues.

While the preview is black, the UI shows the camera is running at over 100 fps, and the skipped_frames counter spikes to values well above 100 as well. This behavior is persistent and happens multiple times a day.

affected:
frigate 0.15
frigate 0.16-b2
frigate 0.16-b3

Temporary workaround:

I have implemented a cron-triggered script that checks the camera feed every minute and restarts the Frigate container if needed. This restart process is triggered approximately 10 times per day to resolve the issue temporarily.

Workaround Script:
```
#!/bin/bash
response=$(curl -s http://127.0.0.1:5000/api/stats)
skipped_fps=$(echo "$response" | jq '.cameras.Eingang.skipped_fps')
timestamp=$(date "+%Y-%m-%d %H:%M")
if (( $(echo "$skipped_fps > 5" | bc -l) )); then
    echo "$timestamp Docker restart because skipped_fps $skipped_fps" >> /home/docker/frigate-watchdog.log
    cd /home/docker/frigate && docker compose down && docker compose up -d
else
    echo "skipped_fps ist $skipped_fps, all okay."
fi
```

This happens 5-10x per day.

```
2025-06-01 13:22 Docker restart because skipped_fps 101.8
2025-06-01 20:03 Docker restart because skipped_fps 105.8
2025-06-02 02:46 Docker restart because skipped_fps 34.6
2025-06-02 03:24 Docker restart because skipped_fps 48.5
2025-06-02 16:32 Docker restart because skipped_fps 102.4
2025-06-02 17:30 Docker restart because skipped_fps 109.8
2025-06-02 22:13 Docker restart because skipped_fps 102
2025-06-02 22:38 Docker restart because skipped_fps 65.7
2025-06-03 00:55 Docker restart because skipped_fps 109.5
2025-06-03 01:06 Docker restart because skipped_fps 109.1
2025-06-03 02:52 Docker restart because skipped_fps 101.7
2025-06-03 05:23 Docker restart because skipped_fps 106.1
2025-06-03 05:39 Docker restart because skipped_fps 51.9
2025-06-03 05:49 Docker restart because skipped_fps 7.9
2025-06-03 05:53 Docker restart because skipped_fps 104.8
2025-06-03 14:22 Docker restart because skipped_fps 102.5
2025-06-03 15:24 Docker restart because skipped_fps 80.2
2025-06-03 16:12 Docker restart because skipped_fps 104.6
2025-06-03 16:35 Docker restart because skipped_fps 109.7
2025-06-03 17:53 Docker restart because skipped_fps 102.5
2025-06-03 22:01 Docker restart because skipped_fps 12.5
```

### Version

0.16-b3

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci:0

go2rtc:
  streams:
    Eingang:
      - ffmpeg:rtsp://admin:123@192.168.1.100:554/h264Preview_01_main
    Eingang_Sub:
      - rtsp://admin:123@192.168.1.100:554/h264Preview_01_sub
  api:
    listen: :1984

cameras:
  Eingang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Eingang?video&audio
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
    detect:
      width: 640
      height: 480
    motion:
    snapshots:
      enabled: true
      required_zones:
        - Wohnungstuer
    zones:
      Wohnungstuer:
        coordinates: 0,480,640,480,640,0,0,0
        objects:
          - person
          - cat
          - dog
    review:
      alerts:
        required_zones: Wohnungstuer
      detections:
        required_zones: Wohnungstuer
    live:
      streams:
        Eingang: Eingang

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_height: 50

  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
#  mask: 0,900,1080,900,1080,1920,0,1920

  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: false
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30

ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  input_args: preset-rtsp-restream-low-latency


record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 21
  detections:
    retain:
      days: 21
version: 0.16-0
```

### Relevant Frigate log output

```shell
n/a after docker restart
```

### Relevant go2rtc log output

```shell
n/a after docker restart
```

### FFprobe output from your camera

```shell
n/a after docker restart
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink Doorbell PoE 5MP

### Screenshots of the Frigate UI's System metrics pages

n/a after docker restart
