### DISCUSSION TITLE
[Support]:  motion triggering and storage

### DISCUSSION THREAD

**Discussion by chitchco** [blakeblackshear/frigate#18559] [General Support]
### Describe the problem you are having

Hi I have lenovo 1 L pc with coral card running. I have couple camera types and trying to get it work. So far all is working however I have issues with motion being detected quite a deal. I had storage turned on to record motion but this was filling my disk fast at 4K resolution. I have tried tuning but had limited success. Currently I am recording on object detection only to save on disk space. I would like to record all motion but only if I don't get continuous false positives. A couple of issues relates to bugs at night and general trees and shadows. I had motion turned well in blue iris before moving to frigate and have not been able to achieve the same results.  I could overcome some of my issues by recording low resolution 7x24 and high resolution for alerts. this is what I was doing on Blue Iris and worked ok, One of the features I found in blue iris was to trigger only on continuous motion period for say 0.5 sec. I cant see a similar feature in Frigate or am I missing it.  I read that I can run duplicate camera stream for 7x24 sub stream recording but the details are fairly sparse so I have not tried it and concerned that it will create to much load for my machine

### Version

 0.15.0-6cb5cfb

### What browser(s) are you using?

chrome

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: 192.168.1.215
  port: 1883
  # #topic_prefix: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

tls:
  enabled: false

# auth:
#   reset_admin_password: true

ffmpeg:
  hwaccel_args: preset-vaapi

objects:
  track:
    - car
    - person
    - dog
    - cat

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  # coral2:
  #   type: edgetpu
  #   device: pci:1

record:
  enabled: true
  # sync_recordings: true
  retain:
    days: 0
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

go2rtc:
  log:
    format: text
    #exec: trace
  streams:
    backdoor:
      - rtsp://{FRIGATE_RTSP_USER1}:{FRIGATE_RTSP_PASSWORD1}@192.168.xxx.xxx:554/h265Preview_01_main
      #- ffmpeg:backdoor#audio=opus
    backdoor_sub:
      - rtsp://{FRIGATE_RTSP_USER1}:{FRIGATE_RTSP_PASSWORD1}@192.168.xxx.xxx:554/h264Preview_01_sub
      #- ffmpeg:backdoor_sub#audio=opus
    sidedoor:
      - rtsp://{FRIGATE_RTSP_USER1}:{FRIGATE_RTSP_PASSWORD1}@192.168.xxx.xxx:554/h265Preview_01_main
      #- ffmpeg:backdoor#audio=opus
    sidedoor_sub:
      - rtsp://{FRIGATE_RTSP_USER1}:{FRIGATE_RTSP_PASSWORD1}@192.168.xxx.xxx:554/h264Preview_01_sub
      #- ffmpeg:backdoor_sub#audio=opus
    driveway:
      - rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@192.168.xxx.xxx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
      # this is the main stream
    driveway_sub:
      - rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@192.168.xxx.xxx:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
      # this is the sub stream
    pool:
      - rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@192.168.xxx.xxx:xxx/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
      # this is the main stream
    pool_sub:
      - rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@192.168.xxx.xxx:xxx/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
      # this is the sub stream
    sidegate:
      - rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@192.168.xxx.xxx:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    # this is the main stream
    sidegate_sub:
      - rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@192.168.xxx.xxx:554/Streaming/Channels/102?transportmode=unicast&profile=Profile_2
    # this is the sub stream

cameras:
  BackDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backdoor?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask: 0.253,0.171,0.732,0.087,1,0.174,1,0,0.593,0,0,0,0,0.307
  SideDoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sidedoor?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sidedoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask: 0.999,0.038,1,0.158,0.371,0.064,0,0.362,0,0,1,0
  DriveWay:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask: 
        0,0,0,0.284,0.282,0.131,0.566,0.146,0.682,0.197,0.869,0.272,1,0.286,1,0.064,1,0.06,1,0,0.937,0,0.707,0
  Pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask: 0,0,0,0.363,0.096,0.221,0.456,0.045,0.846,0.135,1,0.226,1,0.099,1,0.062,1,0
  SideGate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sidegate?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/sidegate_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 30
      contour_area: 30
      improve_contrast: true
      mask: 
        0.085,0,0.058,0.226,0.348,0.213,0.582,0.25,0.773,0.542,0.783,0.67,1,0.895,0.997,0.136,1,0.051,1,0
version: 0.15-1
```

### Relevant Frigate log output

```shell
Not applicable
```

### Relevant go2rtc log output

```shell
Not appliable
```

### FFprobe output from your camera

```shell
Not applicable
```

### Frigate stats

```json
Not appliable
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
standard docker
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

annke and reolink 4K
