### DISCUSSION TITLE
[Bug]: embeddings_maintainer face detection FileNotFound crashes thread

### DISCUSSION THREAD

**Discussion by RaidMax** [blakeblackshear/frigate#18557] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

After some arbitrary time running the face detection thread encounters a FileNotFoundError and does not recover. This seems to impact any subsequent genai processing as well.

### Steps to reproduce

1. Enable face detection with small model
2. Wait for some time
3. FileNotFoundError occurs while attempting to detect 

### Version

0.16.0-1fa7ce5

### In which browser(s) are you experiencing the issue with?

Firefox 138.0.4 (aarch64)

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.29
  user: mqtt-frigate
  password: ...

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-rtsp-restream


detectors:
  coral:
    type: edgetpu
    device: pci

model:
  path: plus://c241fae21de50ecf6c0f2a63769dcacd

genai:
  enabled: false
  provider: openai
  api_key: n/a
  model: internvl3-2b-instruct
  prompt: Provide a unified behavioral analysis of the {label} (or primary object)
    across the image sequence. Synthesize its actions into a single event, focusing
    on its intent, current activity, underlying motivation, and probable next move.
    Do not describe its appearance, the surroundings, or stationary objects.

objects:
  track:
    - person
    - dog
    - cat
    - deer
    - bird
    - raccoon
    - fox
    - squirrel
    - car
    - package
    - face
    - amazon
    - usps
    - ups
    - fedex
    - dhl
    - bicycle

review:
  alerts:
    labels:
      - package
      - face
      - amazon
      - usps
      - ups
      - fedex
      - dhl
  detections:
    labels:
      - dog
      - cat
      - person
      - deer
      - bird
      - raccoon
      - fox
      - squirrel
      - car
      - bicycle

go2rtc:
  streams:
    front_yard_main:
      - ffmpeg:http://192.168.1.57/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=...#video=copy#audio=copy#hardware=vaapi
    front_yard_live:
      - ffmpeg:front_yard_main#video=h264#width=1280#height=960#audio=copy#raw=-fpsmax
        5#hardware=vaapi

    back_yard_main:
      - ffmpeg:http://192.168.1.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=...#video=copy#audio=copy#hardware=vaapi
    back_yard_live:
      - ffmpeg:back_yard_main#video=h264#width=1280#height=960#audio=copy#raw=-fpsmax
        5#hardware=vaapi

    bonus_room_main:
      - ffmpeg:rtsp://stream:...@192.168.1.59:554/h264Preview_01_main#hardware=vaapi
    bonus_room_live:
      - ffmpeg:bonus_room_main#video=h264#width=1280#height=720#audio=copy#raw=-fpsmax
        5#hardware=vaapi

    living_room_main:
      - ffmpeg:https://192.168.1.94/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=stream&password=...#video=copy#audio=copy#hardware=vaapi
    living_room_live:
      - ffmpeg:living_room_main#video=h264#width=1280#height=720#audio=copy#raw=-fpsmax
        5#hardware=vaapi

    dining_room_main:
      - ffmpeg:rtsp://stream:...@192.168.1.62:554/h264Preview_01_main#hardware=vaapi
    dining_room_live:
      - ffmpeg:dining_room_main#video=h264#width=1280#height=720#audio=copy#raw=-fpsmax
        5#hardware=vaapi

    kitchen_main:
      - ffmpeg:rtsp://Admin:...@192.168.1.18/live0#hardware=vaapi
    kitchen_live:
      - ffmpeg:kitchen_main#video=h264#width=1280#height=540#audio=copy#raw=-fpsmax
        5#hardware=vaapi
cameras:
  front_yard_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard_main
          roles:
            - record
            - detect
    onvif:
      host: 192.168.1.57
      port: 8000
      user: onvif_admin
      password: ...
    genai:
      enabled: true
      objects:
        - person
        - dog
        - cat
        - deer
        - bird
        - raccoon
        - fox
        - squirrel
    objects:
      mask:
        - 0.161,0.372,0.158,0.422,0.251,0.415,0.245,0.369
        - 0.553,0.366,0.558,0.451,0.616,0.448,0.62,0.368
        - 0.076,0.513,0.052,0.414,0.001,0.417,0.001,0.524
      filters:
        car: {}
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
          - bicycle
          - motorcycle
      detections:
        labels:
          - car
    live:
      streams:
        front_yard_live: front_yard_live
    detect:
      enabled: true
      fps: 5
      width: 2560
      height: 1920
      annotation_offset: -250
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      export:
        timelapse_args: -vf setpts=0.00005*PTS -r 30
      alerts:
        retain:
          days: 30
        pre_capture: 2
        post_capture: 2
      detections:
        retain:
          days: 30
        pre_capture: 2
        post_capture: 2
    snapshots:
      enabled: true
      quality: 100
    motion:
      mask:
        - 0,0,1,0,1,0.187,1,0.71,0.9,0.697,0.73,0.666,0.688,0.591,0.632,0.521,0.61,0.441,0.596,0.371,0.619,0.17,0,0.16
        - 0.118,0.344,0.119,0.299,0.13,0.277,0.178,0.277,0.182,0.295,0.186,0.333,0.185,0.35,0.144,0.349
        - 0.232,0.295,0.224,0.309,0.223,0.32,0.235,0.337,0.252,0.352,0.273,0.343,0.284,0.326,0.28,0.308,0.259,0.294,0.245,0.29
        - 0.286,0.346,0.284,0.326,0.294,0.291,0.321,0.305,0.361,0.294,0.383,0.347,0.324,0.359,0.29,0.36
      threshold: 35
      contour_area: 15
      improve_contrast: 'true'

    zones: {}
  back_yard_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard_main
          roles:
            - record
            - detect
    onvif:
      host: 192.168.1.11
      port: 8000
      user: onvif_admin
      password: ...
    genai:
      enabled: true
      objects:
        - person
        - dog
        - cat
        - deer
        - bird
        - raccoon
        - fox
        - squirrel
    objects:
      mask: 0.211,0.322,0.177,0.336,0.183,0.403,0.212,0.395
      filters:
        car:
          mask:
            - 0.316,0.294,0.534,0.29,0.532,0.395,0.423,0.467,0.382,0.489,0.323,0.52
            - 0.211,0.322,0.177,0.336,0.183,0.403,0.212,0.395
    live:
      streams:
        back_yard_live: back_yard_live
    detect:
      enabled: true
      fps: 5
      width: 2560
      height: 1920
      annotation_offset: -1000
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      export:
        timelapse_args: -vf setpts=0.00005*PTS -r 30
      alerts:
        retain:
          days: 30
        pre_capture: 2
        post_capture: 2
      detections:
        retain:
          days: 30
        pre_capture: 2
        post_capture: 2
    snapshots:
      enabled: true
      quality: 100

    motion:
      mask:
        - -0.001,0.187,0.341,0.203,0.459,0.214,0.683,0.231,0.746,0.312,0.791,0.326,0.849,0.318,1,0.334,1,0,0.002,-0.002
        - 0.763,1,0.806,0.779,0.881,0.616,1,0.562,1,1
      threshold: 38
      contour_area: 20
      improve_contrast: true
  bonus_room_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bonus_room_main
          roles:
            - record
            - detect
    onvif:
      host: 192.168.1.59
      port: 8000
      user: onvif_admin
      password: ...
    live:
      streams:
        bonus_room_live: bonus_room_live
    detect:
      enabled: true
      fps: 5
      width: 1280
      height: 720
    record:
      enabled: false
    snapshots:
      enabled: true
      quality: 100
    motion:
      mask: 
        0.601,0.562,0.642,0.679,0.791,0.651,0.864,0.672,0.944,0.641,0.977,0.539,0.951,0.423,0.897,0.392,0.878,0.385,0.82,0.52,0.797,0.58,0.765,0.588
  living_room_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_main
          roles:
            - record
            - detect
    onvif:
      host: 192.168.1.94
      port: 8000
      user: onvif_admin
      password: ...
    live:
      streams:
        living_room_live: living_room_live
    detect:
      enabled: true
      fps: 5
      width: 1280
      height: 720
      stationary:
        interval: 10
        threshold:
    record:
      enabled: false
      retain:
        days: 0
        mode: motion
      alerts:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
      detections:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
    snapshots:
      enabled: true
      quality: 100
    motion:
      mask: 0.546,0.235,0.534,0.401,0.376,0.398,0.302,0.379,0.308,0.282,0.319,0.236
  dining_room_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dining_room_main
          roles:
            - record
            - detect
    onvif:
      host: 192.168.1.62
      port: 8000
      user: onvif_admin
      password: ...
    live:
      streams:
        dining_room_live: dining_room_live
    detect:
      enabled: true
      fps: 5
      width: 1280
      height: 720
    record:
      enabled: false
      retain:
        days: 0
        mode: motion
      alerts:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
      detections:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
    snapshots:
      enabled: true
      quality: 100

  kitchen_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_main
          roles:
            - record
            - detect
    live:
      streams:
        kitchen_live: kitchen_live
    detect:
      enabled: true
      fps: 5
      width: 1920
      height: 1080
    record:
      enabled: false
      retain:
        days: 0
        mode: motion
      alerts:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
      detections:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
    snapshots:
      enabled: true
      quality: 100
    motion:
      mask: 
        0.098,0.839,0.272,0.609,0.41,0.595,0.418,0.497,0.539,0.478,0.542,0.174,0.227,0.169,0.089,0.174,0.038,0.265
  bedroom_live:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtmp://host.docker.internal:1935/live/bedroom
          input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental
            -fflags +genpts+discardcorrupt -rw_timeout 30000000 -f live_flv
          roles:
            - detect
            - record
    detect:
      enabled: true
      fps: 5
      width: 1280
      height: 768
    record:
      enabled: false
      retain:
        days: 0
        mode: motion
      alerts:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
      detections:
        retain:
          days: 1
        pre_capture: 1
        post_capture: 1
    snapshots:
      enabled: true
      quality: 90
version: 0.16-0
detect:
  enabled: true
semantic_search:
  enabled: true
  model_size: large
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: true
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    shm_size: "1024mb"
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 8192M
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/nas/Frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5555:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD=...
      - LIBVA_DRIVER_NAME=iHD
      - PLUS_API_KEY=...
      - OPENAI_BASE_URL=http://192.168.1.90:1234/v1
    extra_hosts:
            - "host.docker.internal:host-gateway"
```

### Relevant Frigate log output

```shell
025-06-03 09:38:57.803473167  Exception in thread embeddings_maintainer:
2025-06-03 09:38:57.803481130  Traceback (most recent call last):
2025-06-03 09:38:57.803482626    File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2025-06-03 09:38:57.803483572      self.run()
2025-06-03 09:38:57.803484792    File "/opt/frigate/frigate/embeddings/maintainer.py", line 173, in run
2025-06-03 09:38:57.803485795      self._process_updates()
2025-06-03 09:38:57.803486818    File "/opt/frigate/frigate/embeddings/maintainer.py", line 268, in _process_updates
2025-06-03 09:38:57.803487802      processor.process_frame(data, yuv_frame)
2025-06-03 09:38:57.803488877    File "/opt/frigate/frigate/data_processing/real_time/face.py", line 286, in process_frame
2025-06-03 09:38:57.803653100      self.write_face_attempt(
2025-06-03 09:38:57.803654439    File "/opt/frigate/frigate/data_processing/real_time/face.py", line 526, in write_face_attempt
2025-06-03 09:38:57.803738469      os.unlink(os.path.join(folder, files[-1]))
2025-06-03 09:38:57.803740268  FileNotFoundError: [Errno 2] No such file or directory: '/media/frigate/clips/faces/train/1748923451.528532-2vcmm9-1748923455.427278-unknown-0.71.webp'
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

REOLINK

### Screenshots of the Frigate UI's System metrics pages

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/d024adea-f8fd-4f5d-9158-a62000c6aed4" />
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/2b30684a-9d13-48bd-a30f-de262e4c1ae3" />
