### DISCUSSION TITLE
[Detector Support]: How do I use my Coral for general object/face detection, but tensorrt for face recognition?

### DISCUSSION THREAD

**Discussion by jvrobert** [blakeblackshear/frigate#18567] [Detector Support] [answered]
### Describe the problem you are having

Currently I've got a dual coral I'd like to use (it also had better detection times than onnx). I currently have 2x type:onnx detectors on a T600, but they seem slow.
Ideally I would use the corals for detection then farm out to the GPU for facial recognition, is this possible?

### Version

0.10.16.0-beta3-tensorrt

### Frigate config file

```yaml
...
detectors:
  #coral1:
  #type: edgetpu
  #device: pci:0
  #coral2:
  #type: edgetpu
  #device: pci:1
  onnx_0:
    type: onnx
  onnx_1:
    type: onnx
  #tensorrt:
  #type: tensorrt
  #device: 1
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant Frigate log output

```shell
NA
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/c6332023-5872-406c-9594-516a3656ad50)
