### DISCUSSION TITLE
[Config Support]: What is the difference between "re-encode the video using FFmpeg parameters" and "ffmpeg module"?

### DISCUSSION THREAD

**Discussion by aik** [blakeblackshear/frigate#18575] [Config Support]
### Describe the problem you are having

My camera does h264 and pcm_ulaw so I need pcm->aac.  https://docs.frigate.video/guides/configuring_go2rtc/ suggests 2 options:
```
living1:
  - rtsp://eggcam2:554/user=admin&password=&channel=&stream=.sdp?real_stream--rtp-caching=100
  - ffmpeg:living1#audio=aac
living2:
  - ffmpeg:rtsp://eggcam2:554/user=admin&password=&channel=&stream=.sdp?real_stream--rtp-caching=100#audio=aac
```
and the doc says about the module `This has the downside of slower startup times, but has compatibility with more stream types`.

1) what is the difference really between `living1` and `living2`? In both cases ffmpeg starts.

2) does not `living1` has 2 streams (one "rtsp", one "ffmpeg")? Should not this runs 2 ffmpegs? Or just one and only for aac?

### Version

0.16.0-1fa7ce5

### Frigate config file

```yaml
```
```


### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
none
```

### Object Detector

Coral

**Comment by banthungprong** [comment]
![image](https://github.com/user-attachments/assets/7f98e400-7fe2-4cc9-b1ce-b08478488fa8)

You can use rtsp as one type of input to go2rtc (no ffmpeg used). This is fast and has no overhead and no conversion.
Sometimes (like bad rtsp-implementation in camera) it helps if you use ffmpeg as input (go2rtc starts ffmpeg with the best parameters and delivers a reliable output. And that adds a delay.

In living1 only audio stream ist converted without using much ressources. It adds simply aac to the original video/audio stream.

**Reply by aik** [reply]
`living1`:
1) go2rtc runs ffmpeg with "-c:v none -c:a aac", no ffmpeg for video, but it is still ffmpeg so => delay, no?
2) frigate runs ffmpeg with 2 inputs streams - one is rtsp "as it" and another from go2rtc's aac ffmpeg.

`living2`:
3) go2rtc runs ffmpeg with "-c:v copy -c:a aac"
4) frigate runs ffmpeg with one stream from go2rtc which includes both video and audio which does not require transcoding.

Is that right? Is the overhead from "-c:v copy" vs "-c:v none" (or whatever the word "no video" is in ffmpeg)?

and btw don't I need quotes for `living2` as "#" from "#audio=aac" means "a comment"?

**Reply by banthungprong** [reply]
Please check the frigate docs for formatting and go2rtc docs for the details about ffmpeg. Or even better: ask AlexIT how go2rtc works regarding these details.

**Reply by NickM-27** [reply]
The delay in most cases is not relevant for frigate because it is only a startup delay (reaction time, basically). But Frigate maintains a constant connection to the camera as it is recording so this does not have an affect for most use cases.

**Reply by aik** [reply]
But there is some difference which I am missing. 2 identical cameras:
```
backyard:
  - rtsp://eggcam3:554/user=admin&password=&channel=&stream=1.sdp?real_stream--rtp-caching=100
  - "ffmpeg:backyard#audio=aac"
backyard_hd:
  - rtsp://eggcam3:554/user=admin&password=&channel=&stream=.sdp?real_stream--rtp-caching=100
  - "ffmpeg:backyard_hd#audio=aac"
kitty:
  - "ffmpeg:rtsp://eggcam:554/user=admin&password=&channel=&stream=1.sdp?real_stream--rtp-caching=100#audio=aac"
kitty_hd:
  - "ffmpeg:rtsp://eggcam:554/user=admin&password=&channel=&stream=.sdp?real_stream--rtp-caching=100#audio=aac"
```
```
backyard:
  enabled: true
  audio:
    enabled: true
  ffmpeg:
    input_args: preset-rtsp-restream
    inputs:
      - path: rtsp://127.0.0.1:8554/backyard_hd
        roles:
          - record
      - path: rtsp://127.0.0.1:8554/backyard
        roles:
          - detect
          - audio
    output_args:
      record: preset-record-generic-audio-aac
  onvif:
    host: eggcam3
    port: 8899
    user: admin
  detect:
    enabled: true
  record:
    enabled: true
  objects:
    mask: 1,0.362,0.81,0.427,0.752,0.838,1,0.832
kitty:
  enabled: true
  audio:
    enabled: true
  ffmpeg:
    input_args: preset-rtsp-restream
    inputs:
      - path: rtsp://127.0.0.1:8554/kitty_hd
        roles:
          - record
      - path: rtsp://127.0.0.1:8554/kitty
        roles:
          - detect
          - audio
    output_args:
      record: preset-record-generic-audio-aac
  onvif:
    host: eggcam
    port: 8899
    user: admin
  detect:
    enabled: true
  record:
    enabled: true
  zones:
    kitty_sleeping:
      coordinates: 0.407,0.381,0.517,0.384,0.522,0.579,0.409,0.576
      loitering_time: 0
```

`backyard` + `kitty` are for `audio` and `detect`, the `_hd` variants for `-record`. And it barfs tons of `raised OpenCV exception` which ends with `Ffmpeg process crashed` but only for `kitty`, the other one works fine:
```
[ WARN:0@59.889] global cap.cpp:175 open VIDEOIO(CV_IMAGES): raised OpenCV exception:                                                  
OpenCV(4.11.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'                                                                                                                                                                      
[2025-06-06 11:07:14] watchdog.kitty                 ERROR   : Ffmpeg process crashed unexpectedly for kitty. 
```

And then I look at `ps` and it appears so that either syntax generates the exact same command line for `_hd` (== record) 
```
aik@srv ~> ps ax | grep ffmpeg | egrep  '(kitty|backyard)'
 138844 ?        Ssl    0:06 /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.16.0-1fa7ce5 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/backyard -r 5 -vf fps=5,scale_cuda=w=800:h=448,hwdownload,format=nv12,eq=gamma=1.4:gamma_weight=0.5 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:
 138849 ?        Ssl    0:01 /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-1fa7ce5 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/backyard_hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/backyard@%Y%m%d%H%M%S%z.mp4
 138860 ?        Ssl    0:00 /usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-1fa7ce5 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/kitty_hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/kitty@%Y%m%d%H%M%S%z.mp4
 138983 ?        Ssl    0:00 /usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-1fa7ce5 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/backyard -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:
 138997 ?        Ssl    0:00 /usr/lib/ffmpeg/7.0/bin/ffmpeg -vn -threads 1 -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-1fa7ce5 -rtsp_transport tcp -timeout 10000000 -i rtsp://127.0.0.1:8554/kitty -threads 1 -f s16le -ar 16000 -ac 1 -y pipe:
```

Really looks like "avoid ffmpeg module if you can" thing :-)
Using the `backyard`s format for `kitty` solves the OpenCV crashes.
