### DISCUSSION TITLE
[Camera Support]: Reolink RLC-820a shows blackscreen stream.

### DISCUSSION THREAD

**Discussion by AussiSG** [blakeblackshear/frigate#18588] [Camera Support] [answered]
### Describe the problem you are having

As mentioned in the title. I've recently added a Reolink RLC-820a to my system.
But it shows the stream in a black image. 
While the detection part seems to be doing it's thing.

The red boxes mark the RLC-820a camera.
![image](https://github.com/user-attachments/assets/c6dcefae-5f80-4901-a016-d78fb22ee1af)

When using VLC and trying to reach out 
rtsp://###########3@192.168.0.26:554/h264Preview_01_main
This give a nice footage of the camera.

### Version

0.15.0-33825f6

### What browser(s) are you using?

Firefox 0.15.0-33825f6

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.12
  user: ######
  password: #####

semantic_search:
  enabled: true
  reindex: false
  model_size: small

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream 
  output_args:
    record: preset-record-generic-audio-copy

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    front: # <- for RTSP streams
      #- ffmpeg:http://192.168.0.26/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=#&password=#video=copy#audio=copy#audio=opus
      - rtsp://###########3@192.168.0.26:554/h264Preview_01_main
    front_sub:
      #- ffmpeg:http://192.168.0.26/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=#&password=#
      - rtsp://##############@192.168.0.26:554/h264Preview_01_sub
    backyard: # <- for RTSP streams
      #- ffmpeg:http://192.168.0.15/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=#&password=###video=copy#audio=copy#audio=opus
      - rtsp://#:#@192.168.0.15:554/h264Preview_01_main
    backyard_sub:
      #- ffmpeg:http://192.168.0.15/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=#&password=#
      - rtsp://#:#@192.168.0.15:554/h264Preview_01_sub
    doorbell:
      #- ffmpeg:http://192.168.0.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=#&password=##video=copy#audio=copy#audio=opus
      #- rtsp://#:#@192.168.0.21:554/Preview_01_sub
      - rtsp://#:#@192.168.0.21:554/h264Preview_01_main
    doorbell_sub:
      #- ffmpeg:http://192.168.0.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=#&password=#
      - rtsp://#:#!Nvr192.168.0.21:554/h264Preview_01_sub
    doorbell_snapshot:
      - onvif://#:#@192.168.0.21:8000?subtype=MediaProfile00000&snapshot


  webrtc:
    candidates:
      - 192.168.0.12:8555
  log:
    exec: trace
  ffmpeg:
    volume: -af "volume=30dB"

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bird
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 29
      mode: motion
  detections:
    retain:
      days: 29
      mode: motion

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          roles:
            - detect
      output_args: {}
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
    # Optional: Record configuration
    # NOTE: Can be overridden at the camera level
    record:
      # Optional: Enable recording (default: shown below)
      # WARNING: If recording is disabled in the config, turning it on via
      #          the UI or MQTT later will have no effect.
      # WARNING: Frigate does not currently support limiting recordings based
      #          on available disk space automatically. If using recordings,
      #          you must specify retention settings for a number of days that
      #          will fit within the available disk space of your drive or Frigate
      #          will crash.
      enabled: true
      # Optional: Number of minutes to wait between cleanup runs (default: shown below)
      # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
      expire_interval: 60
      # Optional: Retention settings for recording
      retain:
        # Optional: Number of days to retain recordings regardless of events (default: shown below)
        # NOTE: This should be set to 0 and retention should be defined in events section below
        #       if you only want to retain recordings of events.
        days: 0
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      # Optional: Event recording settings
      alerts:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
    motion:
      mask: 
        0.363,0.501,0.549,0.414,0.704,0.499,0.744,0.658,0.744,0.827,0.709,0.886,0.578,0.858,0.574,0.958,0.54,0.996,0.5,0.995,0.484,0.972,0.444,0.931,0.415,0.918,0.381,0.929,0.367,0.891,0.355,0.853,0.355,0.813,0.358,0.784,0.356,0.746,0.346,0.726,0.336,0.687,0.322,0.676,0.339,0.63,0.341,0.598,0.341,0.555
 
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          roles:
            - detect
      output_args: {}
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
    # Optional: Record configuration
    # NOTE: Can be overridden at the camera level
    record:
      # Optional: Enable recording (default: shown below)
      # WARNING: If recording is disabled in the config, turning it on via
      #          the UI or MQTT later will have no effect.
      # WARNING: Frigate does not currently support limiting recordings based
      #          on available disk space automatically. If using recordings,
      #          you must specify retention settings for a number of days that
      #          will fit within the available disk space of your drive or Frigate
      #          will crash.
      enabled: true
      # Optional: Number of minutes to wait between cleanup runs (default: shown below)
      # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
      expire_interval: 60
      # Optional: Retention settings for recording
      retain:
        # Optional: Number of days to retain recordings regardless of events (default: shown below)
        # NOTE: This should be set to 0 and retention should be defined in events section below
        #       if you only want to retain recordings of events.
        days: 0
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      # Optional: Event recording settings
      alerts:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
    motion:
      mask: 
        0.363,0.501,0.549,0.414,0.704,0.499,0.744,0.658,0.744,0.827,0.709,0.886,0.578,0.858,0.574,0.958,0.54,0.996,0.5,0.995,0.484,0.972,0.444,0.931,0.415,0.918,0.381,0.929,0.367,0.891,0.355,0.853,0.355,0.813,0.358,0.784,0.356,0.746,0.346,0.726,0.336,0.687,0.322,0.676,0.339,0.63,0.341,0.598,0.341,0.555
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: doorbell
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
    # Optional: Record configuration
    # NOTE: Can be overridden at the camera level
    record:
      # Optional: Enable recording (default: shown below)
      # WARNING: If recording is disabled in the config, turning it on via
      #          the UI or MQTT later will have no effect.
      # WARNING: Frigate does not currently support limiting recordings based
      #          on available disk space automatically. If using recordings,
      #          you must specify retention settings for a number of days that
      #          will fit within the available disk space of your drive or Frigate
      #          will crash.
      enabled: true
      # Optional: Number of minutes to wait between cleanup runs (default: shown below)
      # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
      expire_interval: 60
      # Optional: Retention settings for recording
      retain:
        # Optional: Number of days to retain recordings regardless of events (default: shown below)
        # NOTE: This should be set to 0 and retention should be defined in events section below
        #       if you only want to retain recordings of events.
        days: 0
        # Optional: Mode for retention. Available options are: all, motion, and active_objects
        #   all - save all recording segments regardless of activity
        #   motion - save all recordings segments with any detected motion
        #   active_objects - save all recording segments with active/moving objects
        # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all
      # Optional: Event recording settings
      alerts:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 10
        pre_capture: 5
        post_capture: 5
    motion:
      mask: 
        0.171,0,0.003,0.186,0.002,0.367,0.142,0.427,0.375,0.425,0.476,0.421,0.507,0.347,0.498,0.26,0.482,0.193,0.452,0.185,0.421,0.118,0.41,0.081,0.401,0
version: 0.15-0
```

### Relevant Frigate log output

```shell
There are no errors
```

### Relevant go2rtc log output

```shell
There are no errors
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.6-0+deb12u1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://#:#@192.168.0.26:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000063, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Reolink RLC-820a

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/b000ce9c-06ab-4308-a726-f47ebc4f12f2)
