### DISCUSSION TITLE
Frigate+ activation

### DISCUSSION THREAD

**Discussion by umtsti** [blakeblackshear/frigate#18584] [Ask A Question] [answered]
I would like to use frigate+ with yolonas for better results with my nvdia gpu. But I couldnt enable it with docker config. I got my api key from frigate+ website and added to my docker config as below. But when I start container, it doesnt enable frigate+ buttons on explore page also I cannot download models.

```
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:0.15.1-tensorrt
    shm_size: "8gb"  # RTX A5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, video, utility]
    environment:
      - YOLO_MODELS=yolov7-tiny-416,yolov7-640,yolov7-416,yolov7x-320
      - USE_FP16=true  # RTX A5000 FP16 destekliyor
      - TRT_MODEL_PREP_DEVICE=0
      - PLUS_API_KEY=xxxxxxxxxxxxxxxxxx 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/frigate_recordings:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 8000000000  # 4GB RAM disk
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "1935:1935"  # RTMP
```

**Comment by NickM-27** [comment]
> it doesnt enable frigate+ buttons on explore

Where are you looking for these buttons, do you have snapshots and clean snapshots enabled?

> also I cannot download models.

What model ID are you using? Have you gotten the correct model ID from your models list on Frigate+ website?

**Comment by umtsti** [comment]
Yes I have snapshots options enabled as below in my config.

```
# Snapshot settigs
snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10
  quality: 70
```
On frigate plus page the model ID I would like to use is : 94cf39f8a42bf67ad1892b4925e8d2bf which is yolonas 640x640. I have put that info on my config like;
```
model:
  path: plus://94cf39f8a42bf67ad1892b4925e8d2bf
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
```
