### DISCUSSION TITLE
[Support]: Performance and MSE Issues on Chromium-Based Browsers

### DISCUSSION THREAD

**Discussion by Drarox** [blakeblackshear/frigate#18597] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Hi,

After 3 days of testing and research, I’ve decided to open this GitHub issue to share some problems I’m encountering with Frigate — mainly related to Chromium-based browsers.

### Summary of Issues:

1. **Slow Stream Loading in Live View:**

   * All my camera streams take a long time to load in Live View (anywhere from 3 to 15 seconds).
   * This happens even after properly configuring the keyframe interval on the cameras and using `go2rtc` with H.264.
   * The behavior is similar across both Firefox and Chromium, **except** for two cameras (Garage_Oben and Eingang_Steve in the config) that **won’t load via MSE on Chrome**. After about 30 seconds, they fall back to `jsmpeg`. On Firefox, MSE works fine for those same cameras and loads much faster (under 30 seconds).

2. **MSE Freezing on Firefox:**

   * On Firefox, one camera (Garage_Oben) freezes in MSE mode and only refreshes a single frame every 3–5 seconds.

3. **Incorrect Aspect Ratio in Chrome:**

   * One camera (Hinten) displays with an incorrect aspect ratio **only on Chrome** in Live View. The same camera shows correctly in recordings and in Firefox.

### Additional Info:

* I’ve tested across **multiple platforms**: Windows, macOS, and Android.
* The issues are **consistent** between Chrome and Firefox across all platforms.
* The server running Frigate has **plenty of resources** available (CPU, RAM, etc.), so I don’t think this is a performance bottleneck.

### Main Concern:

The **long loading time** for Live View is my biggest issue with Frigate right now. Otherwise, I’m loving it! I recently migrated from ZoneMinder, and with ZoneMinder all the same cameras loaded **instantly (under 1 second)**.

### Questions:

* Any ideas why I’m seeing these behaviors specifically on Chrome?
* Are there any optimizations or configuration tweaks to improve Live View loading time?

Thanks for your work on Frigate — it’s a great project, and I really hope to resolve this so I can fully enjoy it.

### Steps to reproduce

-

### Version

 0.15.0-6cb5cfb

### In which browser(s) are you experiencing the issue with?

All latest chromium browsers

### Frigate config file

```yaml
database:
  path: /db/frigate.db

#======================================
#          go2rtc Config
#======================================
go2rtc:
  streams:
    Schweinchen:
      - rtsp://XXX:XXX@192.168.1.146:554/stream1
    Schweinchen_sub:
      - rtsp://XXX:XXX@192.168.1.146:554/stream2
    
    Eingang:
      - rtsp://XXX:XXX@192.168.1.63:554/11
    Eingang_sub:
      - rtsp://XXX:XXX@192.168.1.63:554/12
    
    Pool:
      - rtsp://XXX:XXX@192.168.1.43:554/stream1
    Pool_sub:
      - rtsp://XXX:XXX@192.168.1.43:554/stream2
    
    Hinten:
      - rtsp://XXX:XXX@192.168.1.50:554/H264/ch1/main/av_stream
      #- ffmpeg:Hinten#video=h264
    Hinten_sub:
      - rtsp://XXX:XXX@192.168.1.50:554/H264/ch1/sub/av_stream
    
    Garage_Oben:
      - rtsp://XXX:XXX@192.168.1.106:554/11
      #- "ffmpeg:Garage_Oben#video=h264"
    Garage_Oben_sub:
      - rtsp://XXX:XXX@192.168.1.106:554/12
    
    Garage_Unten:
      - rtsp://XXX:XXX@192.168.1.136:554/onvif1
    Garage_Unten_sub:
      - rtsp://XXX:XXX@192.168.1.136:554/onvif2
    
    Haus_Steve:
      #- rtsp://XXX:XXX@192.168.1.65:554/udp/av0_0
      - "ffmpeg:rtsp://XXX:XXX@192.168.1.65:554/udp/av0_0#input=rtsp/udp#video=h264"
    
    Eingang_Steve:
      - rtsp://XXX:XXX@192.168.1.237:554/11
    Eingang_Steve_sub:
      - rtsp://XXX:XXX@192.168.1.237:554/12
    
    Garage_Steve:
      - rtsp://192.168.1.196:554/realmonitor?channel=0&stream=0.sdp


#=====================================================================
#               CAMERAS CONFIGURATION
#=====================================================================
cameras:

#===================================================================== 
  Schweinchen:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Schweinchen
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Schweinchen_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 1
        mode: all

#===================================================================== 
  Eingang:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Eingang_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 960
      fps: 5

    motion:
      enabled: false
      mask:
        - 1114,547,1280,560,1280,960,693,960,674,738,648,548,739,508,939,547
        - 1280,0,1280,32,978,31,980,0

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Pool:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Pool
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Pool_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 960
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Hinten:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Hinten
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Hinten_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Garage_Oben:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage_Oben
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_Oben_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 960
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Garage_Unten:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage_Unten
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_Unten_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 960
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Haus_Steve:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Haus_Steve
          roles:
            - record
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Eingang_Steve:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Eingang_Steve
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Eingang_Steve_sub
          roles:
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all

#===================================================================== 
  Garage_Steve:
#===================================================================== 
    enabled: true

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage_Steve
          roles:
            - record
            - detect

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true

    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5

    motion:
      enabled: false

    record:
      enabled: true
      retain:
        days: 60
        mode: all


#======================================
#          Camera Groups
#======================================
camera_groups:
  Haus_21:
    order: 1
    icon: LuHome
    cameras:
      - Schweinchen
      - Eingang
      - Hinten
      - Pool
      - Garage_Oben
      - Garage_Unten
  Haus_23:
    order: 2
    icon: LuUsers2
    cameras:
      - Garage_Steve
      - Eingang_Steve
      - Haus_Steve
  Birdseye:
    order: 3
    icon: LuEye
    cameras: birdseye


#======================================
#          Settings
#======================================

objects:
  track:
    - person
    - car
    - cat
    - bicycle
    - motorcycle
    - dog
    - horse

record:
  enabled: true
  retain:
    days: 60
    mode: all
  alerts:
    retain:
      days: 60
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 60
    pre_capture: 10
    post_capture: 10

ui:
  time_format: 24hour

mqtt:
  enabled: false

birdseye:
  enabled: true
  mode: continuous
  width: 1920
  height: 1080

auth:
  enabled: true
  session_length: 157784760 #seconds
  failed_login_rate_limit: "1/second;5/minute;20/hour"
  trusted_proxies: #only used for rate limiter
    - 172.17.0.0/16
    - 172.31.0.0/16

proxy:
  auth_secret: "XXX"

tls:
  enabled: false
  
version: 0.15-1
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Annke, Jennov, Oriscam

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/1f277f1c-a680-4864-81fa-35a9e6315a61)
![image](https://github.com/user-attachments/assets/0cba37c9-3877-4fd3-a4e5-e45cc61738ee)
