### DISCUSSION TITLE
[Config Support]: change detect sensitivity based on inputs (wind, etc) from HA

### DISCUSSION THREAD

**Discussion by gspitale** [blakeblackshear/frigate#18598] [Config Support]
### Describe the problem you are having

I live in a heavy forest area, and I've found motion sensitivity is necessarily a compromise.  If I set it high enough that the system doesn't overload on windy days it fails to catch some objects on calm days.  I've seen some people say they adjust this motion tuning based on external inputs from HA, but I cannot figure out how.

I have very good system performance - normal CPU/GPU use is 12%/2% with 13 cameras running 24/7 record/detect, but on windy days this shoots up to very high loads and TPU temperature gets very hot - which is why I would like to be able to adjust *some* of my cameras to a lower sensitivity on those days.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
#  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
  input_args: preset-rtsp-restream

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: true
  provider: gemini
  api_key: xxx
  model: gemini-2.0-flash

detectors:
#  ov:
#    type: openvino
#    device: GPU
  coral_1:
    type: edgetpu
    device: pci:0
  coral_2:
    type: edgetpu
    device: pci:1

model:
  path: plus://xxx #coral
#  path: plus://xxx #yolonas

objects:
  filters:
    person:
      min_score: .65
      threshold: .85
    face:
      min_score: .7
    car:
      min_score: .7
      threshold: .85
    license_plate:
      min_score: .6
    motorcycle:
      min_score: .65
      threshold: .85
    bicycle:
      min_score: .65
      threshold: .85
    amazon:
      min_score: .75
    usps:
      min_score: .75
    ups:
      min_score: .75
    fedex:
      min_score: .75
    package:
      min_score: .65
      threshold: .9
    dog:
      min_score: .7
      threshold: .9
    cat:
      min_score: .65
      threshold: .8
    deer:
      min_score: .65
      threshold: .8
    horse:
      min_score: .65
      threshold: .8
    bird:
      min_score: .65
      threshold: .8
    raccoon:
      min_score: .65
      threshold: .8
    fox:
      min_score: .65
      threshold: .8
    bear:
      min_score: .65
      threshold: .8
    squirrel:
      min_score: .65
      threshold: .8
    rabbit:
      min_score: .6
      threshold: .75
    waste_bin:
      min_score: .65
      threshold: .85

review:
  alerts:
    labels:
      - person
      - face
      - car
      - license_plate
      - motorcycle
      - bicycle
      - amazon
      - usps
      - ups
      - fedex
      - package
      - dog
      - cat
      - deer
      - horse
      - bird
      - raccoon
      - fox
      - bear
      - squirrel
      - rabbit
      - waste_bin

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  retain:
    default: 20

record:
  enabled: true
  retain:
    days: 20
    mode: all

audio:
  enabled: true

go2rtc:
  streams:
    FrontYard:
      - rtsp://frontyard.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:FrontYard#audio=aac
    FrontYardsub:
      - rtsp://frontyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:FrontYardsub#audio=aac
    FrontYardmain:
      - rtsp://frontyard.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:FrontYardmain#audio=aac
    FrontDoor:
      - rtsp://frontdoor.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:FrontDoor#audio=aac
    FrontDoormain:
      - rtsp://frontdoor.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:FrontDoormain#audio=aac
    Driveway1:
      - rtsp://driveway1.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:Driveway1#audio=aac
    Driveway1sub:
      - rtsp://driveway1.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Driveway1sub#audio=aac
    Driveway1main:
      - rtsp://driveway1.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:Driveway1main#audio=aac
    Driveway2:
      - rtsp://frigate:!frigate1245@driveway2.camera.havenwood:554/cam/realmonitor?channel=1&subtype=1
#      - ffmpeg:Driveway2#audio=aac
    Driveway2sub:
      - rtsp://frigate:!frigate1245@driveway2.camera.havenwood:554/cam/realmonitor?channel=1&subtype=2
#      - ffmpeg:Driveway2sub#audio=aac
    Driveway2main:
      - rtsp://frigate:!frigate1245@driveway2.camera.havenwood:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:Driveway2main#audio=aac
    Garage:
      - rtsp://garage.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:Garage#audio=aac
    Garagesub:
      - rtsp://garage.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Garagesub#audio=aac
    Garagemain:
      - rtsp://garage.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:Garagemain#audio=aac
    NorthYard:
      - rtsp://northyard.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:NorthYard#audio=aac
    NorthYardsub:
      - rtsp://northyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:NorthYardsub#audio=aac
    NorthYardmain:
      - rtsp://northyard.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:NorthYardmain#audio=aac
    BackYard1:
      - rtsp://backyard1.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:BackYard1#audio=aac
    BackYard1sub:
      - rtsp://backyard1.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackYard1sub#audio=aac
    BackYard1main:
      - rtsp://backyard1.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:BackYard1main#audio=aac
    BackYard2:
      - rtsp://backyard2.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:BackYard2#audio=aac
    BackYard2sub:
      - rtsp://backyard2.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackYard2sub#audio=aac
    BackYard2main:
      - rtsp://backyard2.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:BackYard2main#audio=aac
    NorthDeck:
      - rtsp://northdeck.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:NorthDeck#audio=aac
    NorthDeckmain:
      - rtsp://northdeck.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:NorthDeckmain#audio=aac
    BackPatio:
      - rtsp://backpatio.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:BackPatio#audio=aac
    BackPatiosub:
      - rtsp://backpatio.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:BackPatiosub#audio=aac
    BackPatiomain:
      - rtsp://backpatio.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:BackPatiomain#audio=aac
    Garden:
      - rtsp://garden.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:Garden#audio=aac
    Gardensub:
      - rtsp://garden.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:Gardensub#audio=aac
    Gardenmain:
      - rtsp://garden.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:Gardenmain#audio=aac
    SouthDeck:
      - rtsp://frigate:!frigate1245@southdeck.camera.havenwood:554/cam/realmonitor?channel=1&subtype=1
#      - ffmpeg:SouthDeck#audio=aac
    SouthDecksub:
      - rtsp://frigate:!frigate1245@southdeck.camera.havenwood:554/cam/realmonitor?channel=1&subtype=2
#      - ffmpeg:SouthDecksub#audio=aac
    SouthDeckmain:
      - rtsp://frigate:!frigate1245@southdeck.camera.havenwood:554/cam/realmonitor?channel=1&subtype=0
#      - ffmpeg:SouthDeckmain#audio=aac
    SouthYard:
      - rtsp://southyard.camera.havenwood:554/media/video3#backchannel=0
      - ffmpeg:SouthYard#audio=aac
    SouthYardsub:
      - rtsp://southyard.camera.havenwood:554/media/video2#backchannel=0
      - ffmpeg:SouthYardsub#audio=aac
    SouthYardmain:
      - rtsp://southyard.camera.havenwood:554/media/video1#backchannel=0
#      - ffmpeg:SouthYardmain#audio=aac

cameras:
  FrontYard:
    enabled: true
    ui:
      order: 1
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: FrontYardmain
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/FrontYard #restream
        - path: rtsp://frontyard.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontYardsub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.823,0.92,0.99,0.918,0.99,0.965,0.825,0.966
        - 0.663,0,0.706,0.143,0.827,0.26,0.923,0.384,1,0.429,1,0
      threshold: 29
      contour_area: 9
      improve_contrast: true
  FrontDoor:
    enabled: true
    ui:
      order: 2
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: FrontDoormain
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/FrontDoor #restream
        - path: rtsp://frontdoor.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoor
          roles:
            - audio
            - detect
    motion:
      mask: 0.008,0.978,0.14,0.978,0.137,0.938,0.008,0.937
      threshold: 29
      contour_area: 9
      improve_contrast: true
  Driveway1:
    enabled: true
    ui:
      order: 3
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: Driveway1main
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/Driveway1 #restream
        - path: rtsp://driveway1.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway1sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.014,0.021,0.182,0.024,0.18,0.076,0.013,0.074
      threshold: 29
      contour_area: 9
      improve_contrast: true
  Driveway2:
    enabled: true
    ui:
      order: 4
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: Driveway2main
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - amazon
        - usps
        - ups
        - fedex
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
        - package
        - waste_bin
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/Driveway2 #restream
        - path: 
            rtsp://frigate:!frigate1245@driveway2.havenwood:554/cam/realmonitor?channel=1&subtype=0     #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway2sub
          roles:
            - audio
            - detect
    motion:
      mask: 0.014,0.063,0.217,0.064,0.218,0.014,0.014,0.009
      threshold: 29
      contour_area: 9
      improve_contrast: true
  Garage:
    enabled: true
    ui:
      order: 5
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: Garagemain
    objects:
#      filters:
#        car:
#          min_score: .75
#          threshold: .9
      track:
        - person
        - face
        - motorcycle
        - license_plate
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/Garage #restream
        - path: rtsp://garage.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garagesub
          roles:
            - audio
            - detect
    motion:
      mask: 0.268,0.959,0.024,0.961,0.023,0.904,0.269,0.906
      threshold: 30
      contour_area: 10
      improve_contrast: true
  NorthYard:
    enabled: true
    ui:
      order: 6
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: NorthYardmain
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/NorthYard #restream
        - path: rtsp://northyard.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthYardsub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.013,0.972,0.179,0.974,0.18,0.921,0.013,0.915
        - 0,0,0,0.311,0.116,0.155,0.843,0.208,1,0.287,1,0,0.584,0
      threshold: 29
      contour_area: 9
      improve_contrast: true
  BackYard1:
    enabled: true
    ui:
      order: 7
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: BackYard1main
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/BackYard1 #restream
        - path: rtsp://backyard1.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard1sub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.02,0.956,0.269,0.961,0.268,0.904,0.02,0.899
        - 0.831,0,1,0,1,0.174,1,1,0.933,1,0.902,0.547,0.824,0.437,0.733,0.229,0.7,0
      threshold: 29
      contour_area: 9
      improve_contrast: true
  BackYard2:
    enabled: true
    ui:
      order: 8
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: BackYard2main
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/BackYard2 #restream
        - path: rtsp://backyard2.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackYard2sub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.815,0.973,0.985,0.973,0.986,0.923,0.815,0.93
        - 0.805,0,0.815,0.1,0.893,0.218,1,0.389,1,0
        - 0.06,0.853,0.156,0.879,0.164,0.998,0.067,0.997
        - 0.392,0.214,0.356,0.307,0.24,0.303,0.225,0.413,0.212,0.893,0.281,0.974,0.469,0.867,0.57,0.729,0.581,0.55,0.613,0.456,0.485,0.173
      threshold: 29
      contour_area: 9
      improve_contrast: true
  NorthDeck:
    enabled: true
    ui:
      order: 9
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: NorthDeckmain
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/NorthDeck #restream
        - path: rtsp://northdeck.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/NorthDeck
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.007,0.054,0.142,0.051,0.144,0.02,0.007,0.017
        - 0.339,0.628,0.478,0.917,0.568,0.835,0.612,0.665,0.444,0.427,0.358,0.448
      threshold: 29
      contour_area: 9
      improve_contrast: true
  BackPatio:
    enabled: true
    ui:
      order: 10
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: BackPatiomain
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/BackPatio #restream
        - path: rtsp://backpatio.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/BackPatiosub
          roles:
            - audio
            - detect
    motion:
      mask: 0.017,0.937,0.183,0.94,0.184,0.897,0.017,0.897
      threshold: 29
      contour_area: 9
      improve_contrast: true
    zones:
      BackPatioPest:
        coordinates: 
          0.357,0.158,0.419,0.129,0.595,0.181,0.662,0.294,0.68,0.411,0.661,0.498,0.289,0.418,0.296,0.25
        inertia: 3
        loitering_time: 0
        objects:
          - bear
          - deer
          - person
          - rabbit
          - raccoon
          - squirrel
          - bird
  Garden:
    enabled: true
    ui:
      order: 11
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: Gardenmain
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
      filters:
        dog:
          min_score: .65
          threshold: .8
        cat:
          min_score: .65
          threshold: .8
        deer:
          min_score: .6
          threshold: .75
        horse:
          min_score: .65
          threshold: .8
        bird:
          min_score: .6
          threshold: .75
        raccoon:
          min_score: .6
          threshold: .75
        fox:
          min_score: .6
          threshold: .75
        bear:
          min_score: .6
          threshold: .75
        squirrel:
          min_score: .6
          threshold: .75
        rabbit:
          min_score: .55
          threshold: .70
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/Garden #restream
        - path: rtsp://garden.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Gardensub
          roles:
            - audio
            - detect
    motion:
      threshold: 29
      contour_area: 7
      improve_contrast: true
      mask:
        - 0.821,0.024,0.991,0.02,0.99,0.067,0.822,0.065
        - 0.359,0,0.365,0.03,0.627,0.087,1,0.451,1,0
    zones:
      GardenPest:
        coordinates: 
          0.25,0.179,0.302,0.541,0.367,0.984,0.785,0.989,0.917,0.809,0.921,0.626,0.815,0.405,0.678,0.212,0.641,0.18,0.313,0.107
        inertia: 1
        loitering_time: 0
        objects:
          - deer
          - rabbit
          - raccoon
          - bird
          - bear
          - squirrel
          - person
          - cat
          - fox
          - horse
    review:
      alerts:
        required_zones: GardenPest
  SouthDeck:
    enabled: true
    ui:
      order: 12
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: SouthDeckmain
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
    ffmpeg:
      inputs:
#       - path: rtsp://127.0.0.1:8554/SouthDeck #restream
        - path: 
            rtsp://frigate:!frigate1245@southdeck.camera.havenwood:554/cam/realmonitor?channel=1&subtype=0     #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthDecksub
          roles:
            - audio
            - detect
    motion:
      threshold: 29
      contour_area: 9
      improve_contrast: true
      mask: 0.791,0.986,0.992,0.99,0.991,0.94,0.791,0.946
  SouthYard:
    enabled: true
    ui:
      order: 13
    detect:
      enabled: true
    record:
      enabled: true
    live:
      stream_name: SouthYardmain
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - license_plate
        - dog
        - cat
        - deer
        - horse
        - bird
        - raccoon
        - fox
        - bear
        - squirrel
        - rabbit
      mask: 0.494,0.859,0.549,0.864,0.554,0.962,0.473,0.943
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
#        - path: rtsp://127.0.0.1:8554/SouthYard #restream
        - path: rtsp://southyard.camera.havenwood:554/media/video1#backchannel=0 #direct
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SouthYardsub
          roles:
            - audio
            - detect
    motion:
      mask:
        - 0.02,0.087,0.267,0.092,0.267,0.044,0.023,0.044
        - 0.537,0,0.538,0.16,0.79,0.254,0.986,0.159,1,0.155,1,0,0.804,0
        - 0,0,0,0.251,0,0.353,0.073,0.308,0.124,0.203,0.159,0
      threshold: 29
      contour_area: 9
      improve_contrast: true
    zones: {}
version: 0.15-1
```

### Relevant Frigate log output

```shell
NA
```

### Relevant go2rtc log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
GNU nano 7.2                                               docker-compose.yml                                                   M     
services:
  frigate:
    container_name: frigate
#    network_mode: host
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "1500mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./config:/config
      - /mnt//frigate_storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "5000:5000"
      - "1984:1984"
    environment:
      - PLUS_API_KEY=xxx
```

### Object Detector

Coral
