### DISCUSSION TITLE
[Detector Support]: RTX 5060 Outdated/Unsupported TensorRT Version

### DISCUSSION THREAD

**Discussion by justbendev** [blakeblackshear/frigate#18605] [Detector Support] [answered]
### Hello :wave:   
  
After building Frigate **(0.16.0 Beta 2)** docker image with TensorRT  support for an RTX 5060.
I unfortunately got an error while generating the .trt files (Error in the dedicated section)

After some research, i have deducted that the most probable cause was an unsupported Cuda/TensorRT Versions which i later confirmed with the content of `docker/tensorrt/Dockerfile.amd64` that mention the use of TRT Version 8.6.1

From [NVIDIA Tensor support matrix](https://docs.nvidia.com/deeplearning/tensorrt/latest/getting-started/support-matrix.html) and later confirmed on NVIDIA Forums by `AakankshaS` (mod).

![image](https://github.com/user-attachments/assets/f0a63450-c684-4d6d-ad95-effe05dac280)

---

_I will **try** on my end to create a compatible Dockerfile.amd64 when i have some free time and will add a pull request if  not already done by someone else :+1:_ 

**Have a great day :wave:**

### Version

0.16.0 Beta 2 tag (TensorRT) 

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  labelmap_path: /labelmap/coco-80.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  devfrigate:
    container_name: devfrigate
    privileged: true
    restart: unless-stopped
    image: devtest:0.16.0b2-tensorrt

    shm_size: "2048mb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    group_add:
      - video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      NVIDIA_VISIBLE_DEVICES: all
      YOLO_MODELS: yolov7-320,yolov7x-640
      USE_FP16: false
```

### Relevant Frigate log output

```shell
Creating yolov7-320.cfg and yolov7-320.weights
Creating yolov7x-640.cfg and yolov7x-640.weights

Done.

Generating yolov7-320.trt. This may take a few minutes.

/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:149: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
  builder.max_batch_size = MAX_BATCH_SIZE
/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:151: DeprecationWarning: Use set_memory_pool_limit instead.
  config.max_workspace_size = 1 << 30
/usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:174: DeprecationWarning: Use build_serialized_network instead.
  engine = builder.build_engine(network, config)
ERROR: failed to build the TensorRT engine!
[06/06/2025-20:54:08] [TRT] [E] 2: [helpers.h::smVerHex2Dig::694] Error Code 2: Internal Error (Assertion major >= 0 && major < 10 failed. )
Loading the ONNX file...
Adding yolo_layer plugins.
Adding a concatenated output as "detections".
Naming the input tensort as "input".
Building the TensorRT engine.  This would take a while...
(Use "--verbose" or "-v" to enable verbose logging.)

Generating yolov7x-640.trt. This may take a few minutes.
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

N/A
