### DISCUSSION TITLE
Avoid Detection Car in a specific Zone - Frigate 16 beta 3

### DISCUSSION THREAD

**Discussion by kiloptero** [blakeblackshear/frigate#18615] [General]
![Uploading Screenshot 2025-06-07 at 8.45.32 AM.png…]()
Hi everyone! I'm trying to prevent car detection in a specific area. However, despite setting up an object mask and a detection zone that should exclude cars, the system continues to detect them. Any ideas on what might be causing this issue?

```yaml
mqtt:
  host: 10.1.2.100
  user: mqtt_user
  password: pass
  topic_prefix: frigate

#environment_vars:   # esto es para las amd
#  LIBVA_DRIVER_NAME: radeonsi

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - car

  filters:
          #  bicycle:
          #    threshold: 0.8
    person:
      threshold: 0.75
      min_score: 0.65
    cat:
      threshold: 0.6
      min_score: 0.5
    car:
      threshold: 0.7
      min_score: 0.65



review:
  alerts:
    labels:
      - cat
      - person



  detections:
    labels:
      - cat
      - person
      - car
      - bird
      - dog
      - bike



record:
  sync_recordings: true
  enabled: true
  retain:
    days: 30
    mode: all
  alerts:
    retain:
      days: 30
      mode: all
  detections:
    retain:
      days: 30
      mode: all
snapshots:
  enabled: true
  retain:
    default: 1000



ffmpeg:
  hwaccel_args: preset-vaapi




go2rtc:
  streams:
    EntradaCasasub:
      - rtsp://admin:pass@10.1.2.110:554/h265Preview_01_sub
      - ffmpeg:EntradaCasasub#audio=opus
    EntradaCasa:
      - rtsp://admin: pass@10.1.2.110:554/h265Preview_01_main
      - ffmpeg:EntradaCasa#audio=opus
    Reolinkduo21:
      - rtsp://casaka: pass@IP:554/h265Preview_01_main
      - ffmpeg:reolink#audio=opus
    Reolinkduo21sub:
      - rtsp://casaka: pass@IP:554/h265Preview_01_sub
      - ffmpeg:reolink#audio=opus



  webrtc:
    candidates:
      - 10.1.2.100:8555
      - stun:8555







cameras:
  EntradaCasasub:
    lpr:
      enabled: true

    birdseye:
      order: 1
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 720


    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/EntradaCasa?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/EntradaCasasub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
            #- record


    live:
      streams:
        EntradaCasa: EntradaCasa
        #EntradaCasasub: EntradaCasasub
    motion:
      mask: 0.335,0.01,0.337,0.071,0.641,0.079,0.636,0.01
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones: {}
    review:
      alerts: {}
      detections: {}




      
  Reolinkduo21:
    lpr:
      enabled: false

    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 720

    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Reolinkduo21?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Reolinkduo21sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio
    live:
      streams:
        Reolinkduo21sub: Reolinkduo21sub
    audio:
      enabled: false
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell

    zones: {}
    review: {}
    motion:
      mask: 0.357,0,0.363,0.089,0.608,0.077,0.611,0.01
    objects:
      filters:
        car:
          mask: 0.593,0.237,0.629,0.391,0.699,0.429,0.674,0.23
        cat: {}
detectors:
  coral_1:
    type: edgetpu
    device: usb:0
  coral_2:
    type: edgetpu
    device: usb:1

database:
  path: /config/frigate.db
    # model:
    #  path: "/custom_model.tflite"

birdseye:
  enabled: true
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 20
  mode: continuous
  restream: true
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true

#ui:
#  live_mode: mse


version: 0.16-0
lpr:
  enabled: true
  min_area: 1500 # Run recognition on larger plates only (4000 pixels represents a 63x63 pixel square in your image)
  recognition_threshold: 0.6
  known_plates:
    Mazda_Kathy:
      - MP-77-48
      - MR-33-65
      - MO-38-11
      - MK-62-15

semantic_search:
  enabled: true
  reindex: false
  model_size: small
camera_groups:
  bird:
    order: 1
    icon: LuBird
    cameras: birdseye
  camaras:
    order: 2
    icon: LuAnnoyed
    cameras:
      - EntradaCasasub
      - comedero
classification:
  bird:
    enabled: false
```
