### DISCUSSION TITLE
[Detector Support]: Using 2 USB coral TPU's in 2 Proxmox LXC's

### DISCUSSION THREAD

**Discussion by goedh452** [blakeblackshear/frigate#18618] [Detector Support]
### Describe the problem you are having

Hi forum!
I hope someone can help me here. I have Proxmox running with 2 USB EdgeTPU's connected. I would like to pass them to different LXC's. One is running the stable frigate and the other one the beta.

Both TPU's are listed on the host:
```
root@proxmox:~# lsusb
Bus 002 Device 005: ID 05e3:0620 Genesys Logic, Inc. GL3523 Hub
Bus 002 Device 008: ID 18d1:9302 Google Inc.
Bus 002 Device 003: ID 0bda:0420 Realtek Semiconductor Corp. 4-Port USB 3.0 Hub
Bus 002 Device 007: ID 18d1:9302 Google Inc.
```

They are added to a separate group so the LXC's have access:
```
root@proxmox:~# ls -la /dev/bus/usb/002
total 0
drwxr-xr-x 2 root root                  160 Jun  6 17:45 .
drwxr-xr-x 6 root root                  120 Jun  6 17:41 ..
crw-rw-r-- 1 root root             189, 128 Jun  6 17:41 001
crw-rw-r-- 1 root root             189, 129 Jun  6 17:41 002
crw-rw-r-- 1 root root             189, 130 Jun  6 17:41 003
crw-rw-r-- 1 root root             189, 132 Jun  6 17:41 005
crw-rw-rw- 1 root lxc-frigate-root 189, 134 Jun  6 17:44 007
crw-rw-rw- 1 root lxc-frigate-root 189, 135 Jun  6 17:45 008
```

I pass them through in the GUI with device passthrough and the exact path (/dev/bus/usb/002/007 and 008). In the LXC's they are available with the appropriate rights (this is the LXC running the stable version):
```
root@frigate-main:/# ls -la /dev/bus/usb/002/
total 0
drwxr-xr-x 2 root root       60 Jun  7 09:21 .
drwxr-xr-x 3 root root       60 Jun  7 09:21 ..
crw-rw-rw- 1 root root 189, 134 Jun  7 16:30 007
```

The problem:
Passing them both to 1 LXC and using both in that frigate works fine. When I pass them to different LXC's I can startup one of the LXC's. The other one will not find the TPU. Any ideas? Could it be the the running LXC "locks" the driver or something?

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    cap_add:
      - CAP_PERFMON
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /media/frigate-data:/media/frigate
      - /opt/frigate/db:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    devices:
      - 'dev/dri/card0:/dev/dri/card0'
      - '/dev/dri/renderD128:/dev/dri/renderD128'
      - '/dev/bus/usb:/dev/bus/usb'
    ports:
      - 5000:5000
      - 1935:1935
      - 8554:8554
      - 8555:8555/tcp
```

### Relevant Frigate log output

```shell
info | 2025-06-07 09:30:48 | frigate.detectors.plugins.edgetpu_tfl | Attempting to load TPU as usb:0
info | 2025-06-07 09:30:51 | frigate.detectors.plugins.edgetpu_tfl | TPU found
```

### Install method

Proxmox via Docker

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

<img width="1414" alt="Scherm­afbeelding 2025-06-07 om 16 33 13" src="https://github.com/user-attachments/assets/70f60182-e868-411d-b002-aac9909d0338" />
