### DISCUSSION TITLE
[Config Support]: Italian Language

### DISCUSSION THREAD

**Discussion by Tinux-Git** [blakeblackshear/frigate#18622] [Config Support]
### Describe the problem you are having

I've installed and configure Frigate with Semantic Search and Google AI for detection description but I would want the desciption in italian languages. Is it possibile ? 

### Version

0.15.1

### Frigate config file

```yaml
semantic_search:
  enabled: true
  reindex: false
  model_size: large
genai:
  enabled: True
  provider: gemini
  api_key: "xxxxxxxxxxxxxxxxxxxxxxx"
  model: gemini-1.5-flash
```

### Relevant Frigate log output

```shell
Not Available
```

### Relevant go2rtc log output

```shell
Not Available
```

### Operating system

Debian

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
Not Available
```

### Object Detector

Coral
