### DISCUSSION TITLE
[Config Support]: tracking not supported by current model

### DISCUSSION THREAD

**Discussion by ohadlevy** [blakeblackshear/frigate#18624] [Config Support]
### Describe the problem you are having

Hello,

trying to enable face recognition in the beta version, using the small mode, I see the following in the logs:
```
frigate.config.config          WARNING : camera is configured to track ['face', 'license_plate'] objects, which are not supported by the current model
```

I'm pretty sure I have a misconfiguration somewhere, but not sure where, I was under the assumption that a specialized model is not required, and I did see frigate fetching a model from the internet when loading initially.

### Version

0.16.0-beta3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: host
  user: USER
  password: PASS

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - face
    - license_plate

go2rtc:
  streams:
    cam1_camera:
      - ffmpeg:http://192.x.x.227/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=aac
    cam1_camera_sub:
      - ffmpeg:http://192.x.x.227/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    cam2_camera:
      - ffmpeg:http://192.x.x.170/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=aac
    cam2_camera_sub:
      - ffmpeg:http://192.x.x.170/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    cam3_camera:
      - ffmpeg:http://192.x.x.157/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=aac
    cam3_camera_sub:
      - ffmpeg:http://192.x.x.157/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
    cam4_camera:
      - rtsp://admin:password@192.x.x.188:554/Streaming/Channels/101
      - ffmpeg:cam4_camera#audio=opus
      - isapi://admin:password@192.x.x.188:80
    cam4_camera_sub:
      - rtsp://admin:password@192.x.x.188:554/Streaming/Channels/102
    cam5:
      - rtsp://192.x.x.164:554/live/ch00_1
    # cam5_sub:
    #   - rtsp://192.x.x.164:554/live/ch00_0

cameras:
  cam1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam1_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        cam1_camera: cam1_camera
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 896 # <---- update for your camera's resolution
      height: 672 # <---- update for your camera's resolution
    motion:
      mask: 0.288,0.01,0.712,0.014,0.712,0.057,0.289,0.053
  cam2: # <------ Name the camera
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam2_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        cam2_camera: cam2_camera
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 896 # <---- update for your camera's resolution
      height: 672 # <---- update for your camera's resolution
    zones:
      inside_cam2:
        coordinates: 658,672,153,672,203,334,252,160,499,163,676,324,896,576
    motion:
      mask: 0.295,0.021,0.298,0.052,0.703,0.054,0.707,0.019
  cam3: # <------ Name the camera
    ffmpeg:
      #hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam3_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        cam3_camera: cam3_camera
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 896 # <---- update for your camera's resolution
      height: 672 # <---- update for your camera's resolution
    motion:
      mask: 0.294,0.021,0.707,0.019,0.705,0.046,0.295,0.051
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam4_camera?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        cam4_camera: cam4_camera
    detect:
      enabled: true
      width: 704
      height: 576
    # motion:
      # mask:
        # - 562,377,717,381,718,71,571,75
    zones:
      gate:
        coordinates: 60,576,378,576,380,252,318,150,56,0
    review:
      detections:
        required_zones: gate
      alerts:
        required_zones: gate
    motion:
      mask:
        - 0.538,0.027,0.661,0.3,0.621,0.426,0.465,0.182
        - 0.709,0.864,0.563,0.904,0.604,0.955,0.666,0.976,0.712,0.925
  cam5:
    ffmpeg:
      inputs:
        # - path: rtsp://127.0.0.1:8554/cam5_sub?video=copy
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
        - path: rtsp://127.0.0.1:8554/cam5?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        cam5: cam5
    onvif:
      host: 192.x.x.164
      port: 8899
      user: admin
      password: password

    zones: {}
    motion:
      mask:
        - 0.982,0.023,0.745,0.019,0.745,0.055,0.981,0.059
        - 0.91,0.092,0.951,0.089,0.952,0.385,0.929,0.372
record:
  enabled: true
  retain:
    days: 6
    mode: motion
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
snapshots:
  enabled: true
version: 0.16-0

ffmpeg:
  hwaccel_args: auto
camera_groups:
  a:
    order: 1
    icon: LuSprout
    cameras:
      - cam1
      - cam3
      - cam2
semantic_search:
  enabled: true
  reindex: false
  model_size: small
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: false
```

### Relevant Frigate log output

```shell
frigate.config.config          WARNING : camera is configured to track ['face', 'license_plate'] objects, which are not supported by the current model
```

### Relevant go2rtc log output

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    shm_size: "197mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ohad/frigate/config:/config
      - /home/ohad/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
        #      LIBVA_DRIVER_NAME: "i965"
```

### Object Detector

Coral
