### DISCUSSION TITLE
[Support]: Live view switches from MSE to MJPEG and back for no apparent reason - why?

### DISCUSSION THREAD

**Discussion by aik** [blakeblackshear/frigate#18634] [General Support]
### Describe the problem you are having

$subj. It is MSE for some time then switches to MJPEG and then after few seconds or minutes back to MSE, and again and again.

MJPEG is slow and laggy, why would go2rtc/frigate even try MJPEG if it can do MSE?

I am watching the stream type via "Show stream stats", I see the switching in both 1 camera view and all cameras view.

Is onnx one to blame here? For some reason always 100% of one of 4 cores, wonder if this can be optimized.

### Version

0.16.0-1fa7ce5

### What browser(s) are you using?

Firefox 137

### Frigate config file

```yaml
detectors:
  onnx_0:
    type: onnx
model:
  model_type: yolo-generic
  path: /config/model_cache/onnx/yolov7x-320.onnx
  labelmap_path: /labelmap/coco-80.txt
  input_dtype: float
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

go2rtc:
  streams:
    bedroom:
      - "ffmpeg:rtsp://neweggcam1:554/user=admin&password=admin&channel=&stream=1.sdp?real_stream--rtp-caching=100#video=h264#audio=aac#hardware"
    bedroom_hd:
      - rtsp://neweggcam1:554/user=admin&password=admin&channel=&stream=.sdp?real_stream--rtp-caching=100

cameras:
  bedroom:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom
          roles:
            - detect
            - audio
        - path: rtsp://127.0.0.1:8554/bedroom_hd
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: neweggcam1
      port: 8899
      user: admin
      password: admin
    detect:
      enabled: true
    record:
      enabled: true
    lpr:
      enabled: false
```

### Relevant Frigate log output

```shell
?
```

### Relevant go2rtc log output

```shell
?
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://neweggcam1:554/user=admin&password=admin&channel=&stream=.sdp?real_stream--rtp-caching=100':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 2304x1296, 6 fps, 6 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
bedroom	
camera_fps	5.5
process_fps	0.4
skipped_fps	5.1
detection_fps	2.1
detection_enabled	true
pid	739
capture_pid	836
ffmpeg_pid	841
audio_rms	0.0JS:0
audio_dBFS	0.0JS:0
```

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
1
```

### Object Detector

TensorRT

### Network connection

Wired

### Camera make and model

XMeye or similar

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/48412739-91bf-4a1b-98d5-7063e3757da9)
