### DISCUSSION TITLE
Best practice to route view/record and detect streams through go2rtc or only record/view streams?

### DISCUSSION THREAD

**Discussion by ptr727** [blakeblackshear/frigate#18648] [Ask A Question] [answered]
Wondering what the recommended best practices are for routing all RTSP video through go2rtc, or only route viewing/recording video through go2rtc and keep detect video direct from the cameras/ffmpeg section?

It does make life easy to have a single place to edit camera feeds in go2rtc vs. needing to double on record config in one place and detect config in another place.

On the other hand given two different camera feeds are used, one for record (highest quality) and one for detect (low fps low res), each camera will serve two feeds anyway (my cameras only support max 2 concurrent feeds), so going camera -> go2rtc -> detect vs. camera -> detect just ads an extra hop.

Any strong opinions for route all or only as needed?

P.s. wish there was some kind of variable substitution or common string reuse in the config, or the ability to use any environment variables in config for substitution, typing out `rtsp://username:password@ip:554/axis-media/media.amp?streamprofile=detect/record` for every single camera for record and detect feeds gets tiresome and is error prone.

**Comment by NickM-27** [comment]
When you restream everything through go2rtc you will have higher CPU usage, especially when restreaming high resolution (4K+) streams. If you are okay with the higher load and have the hardware to handle that then it gives a simplest config. 

I personally have all record streams directly from the camera, and then I use the cameras mid stream as the restream constant connection. And then I have go2rtc also able to connect to the record stream for live view, but this only works for better cameras that can support multiple main stream connections at once. 

> P.s. wish there was some kind of variable substitution or common string reuse in the config, or the ability to use any environment variables in config for substitution, typing out rtsp://username:password@ip:554/axis-media/media.amp?streamprofile=detect/record for every single camera for record and detect feeds gets tiresome and is error prone.

there is, you can use any substitution in the rtsp paths https://docs.frigate.video/configuration/#environment-variable-substitution

**Reply by ptr727** [reply]
Thanks for the insight.\
My Axis cameras only support 2 concurrent streams, so for a record and view and detect I need at least 1 to go to go2rtc.

Regarding variable substitution, and reading the docs, and looking at the docker secrets code (you just helped answer), the variables are restricted to the ones that explicitly state they can be used. So if I have different passwords for my different cameras, I have to type the different password in the clear, or I need to change all usernames and passwords to the same (which I did). It also does not really help with vanilla substitution of other variables, e.g. if I wanted to to reuse the record path I'd do `DETECT_PATH=:554/axis-media/media.amp?streamprofile=detect`, and then `path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.24{DETECT_PATH}`, or `AUTH=rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@` then `path: {AUTH}192.168.1.24{DETECT_PATH}`\
Anyway, more about consistency in config, same auth for same camera just different path, or same config just different IP.

**Reply by NickM-27** [reply]
No, your understanding is wrong. The docs simply tell you where you can put the passwords. You can name them whatever you want. 

For example my config:

```
  office_cam:
    enabled: true
    webui_url: http://192.168.50.154
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office_cam
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_OFFICE_PW}@192.168.50.154:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
```

**Reply by NickM-27** [reply]
The only restriction is that it must start with `FRIGATE_`

**Reply by ptr727** [reply]
Hmm, I then think the docs are wrong or at minimum confusing: "Frigate supports the use of environment variables starting with FRIGATE_ **only** where specifically indicated in the reference config." I did not read that as I can create any variable I want and use it anywhere in the config as long as it starts with `FRIGATE_`?

To confirm, can I create any `FRIGATE_somethingsomething` config, including docker secrets, and use it anywhere in the config file?

**Reply by NickM-27** [reply]
> To confirm, can I create any FRIGATE_somethingsomething config, including docker secrets, and use it anywhere in the config file?

No, not anywhere in the config. You can only use it in the areas designed in the reference config. Such as camera stream url, go2rtc stream url, mqtt user/pass, etc.

**Reply by ptr727** [reply, marked as answer]
Yeah, that's the doc I quoted.

Anyway, this works, thank you:

Config:

`- rtsp://{FRIGATE_CAMERA_AUTH}@192.168.1.24:{FRIGATE_CAMERA_RECORD}`

Compose:

```
      - FRIGATE_CAMERA_DETECT=554/axis-media/media.amp?streamprofile=detect
      - FRIGATE_CAMERA_RECORD=554/axis-media/media.amp?streamprofile=record
      # /run/secrets/FRIGATE_CAMERA_AUTH
```

**Reply by Cold-Lemonade** [reply]
@NickM-27 Can you please point me to an example of the config that does what you've described here:

> I personally have all record streams directly from the camera, and then I use the cameras mid stream as the restream constant connection. And then I have go2rtc also able to connect to the record stream for live view, but this only works for better cameras that can support multiple main stream connections at once.

**Reply by NickM-27** [reply]
```yaml
go2rtc:
  streams:
    my_camera:
      - rtsp://192.168.1.5:554/live1

cameras:
  my_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/my_camera  # detect stream via go2rtc restream
          roles:
            - detect
        - path: rtsp://192.168.1.5:554/live0     # record stream direct to camera
          roles:
            - record
```
