### DISCUSSION TITLE
[Support]: Initial Install - Google Coral Step, instructions not working

### DISCUSSION THREAD

**Discussion by ReticentRobot** [blakeblackshear/frigate#18647] [General Support] [answered]
### Describe the problem you are having

I had Frigate running on Ubuntu server, but it kept crashing. Finally giving up on that, I decided to start all over with everything and follow the Frigate instructions to the letter. Everything went well, until it came time to install the PCIe driver for my Coral. The instructions don't seem to be working. I realize that this isn't a Frigate specific issue, but I'm hoping since it is linked in the instructions for Frigate and there are many users on here using Coral that someone may be able to help me. I figure my chances of finding help here are higher than trying to get help from Google.

Anyway, I'm following the link from the Frigate docs to here: https://coral.ai/docs/m2/get-started/#2-install-the-pcie-driver-and-edge-tpu-runtime

```
robert@frigate:~$ uname -r
6.1.0-37-amd64
robert@frigate:~$ lsmod | grep apex
robert@frigate:~$ echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
deb https://packages.cloud.google.com/apt coral-edgetpu-stable main
robert@frigate:~$ curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
100  1022  100  1022    0     0   5750      0 --:--:-- --:--:-- --:--:--  5774
**curl: (23) Failed writing body**
robert@frigate:~$ sudo apt-get update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 https://download.docker.com/linux/debian bookworm InRelease
Hit:4 http://deb.debian.org/debian-security bookworm-security InRelease
Get:5 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease [1,423 B]
Err:5 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3
Reading package lists... Done
W: GPG error: https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0BA5CE6DC6315A3
E: The repository 'https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Version

Current Stable

### Frigate config file

```yaml
Can't really check the version or get the config file, Frigate isn't really working well enough to load at this point I think because I told it I have a Coral but don't have that installed yet. I just get blank black pages.
```

### Relevant Frigate log output

```shell
Can't get to it
```

### Relevant go2rtc log output

```shell
Can't get to it
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/9d067f1b-3a7b-4a68-a868-c33ea3a190b0:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Amcrest
