### DISCUSSION TITLE
[Detector Support]: OpenVINO detector ignores GPU device configuration and uses CPU instead

### DISCUSSION THREAD

**Discussion by mezwick** [blakeblackshear/frigate#18657] [Detector Support] [answered]
### Describe the problem you are having

# Problem Description Field

OpenVINO detector is configured to use GPU but always uses CPU instead. The Frigate UI shows "Detector CPU Usage" at 50-60% despite having a working Intel GPU that's properly configured and accessible to the container.

Testing confirms:
- GPU is available and working in the container (intel_gpu_top shows the device)
- OpenVINO can see and use the GPU (manual testing succeeds)  
- Config file correctly specifies `device: GPU`
- Frigate reads the config correctly
- But the detector process still uses CPU

### Possible causes:
Looking at `/opt/frigate/frigate/detectors/plugins/openvino.py`, the `device` field has `default=None`:
```python
class OvDetectorConfig(BaseDetectorConfig):
    type: Literal[DETECTOR_KEY]
    device: str = Field(default=None, title="Device Type")
```

When OpenVINO's compile_model receives `device_name=None`, it defaults to AUTO mode.

**Potential issues could be:**
1. The device value from the YAML config might not be properly passed to the detector initialization
2. There could be an issue in how the detector configuration is instantiated
3. The detector subprocess might not be receiving the correct configuration
4. Or there could be another reason the GPU device setting isn't being applied

Whatever the cause, the result is that the detector uses CPU instead of the configured GPU.

### Diagnostic commands that confirm this:

1. **Config is set to GPU and read correctly:**
```bash
docker exec -it frigate python3 -c "
import yaml
with open('/config/config.yml', 'r') as f:
    config = yaml.safe_load(f)
    print('Config says:', config['detectors']['openvino']['device'])
"
# Output: Config says: GPU
```

2. **GPU works perfectly when explicitly requested:**
```bash
docker exec -it frigate python3 -c "
from openvino.runtime import Core
core = Core()
model = core.read_model('/openvino-model/ssdlite_mobilenet_v2.xml')
compiled_gpu = core.compile_model(model, 'GPU')
print('GPU compilation:', compiled_gpu.get_property('EXECUTION_DEVICES'))
"
# Output: GPU compilation: ['GPU.0']
```

3. **But detector uses CPU (shown in Frigate UI as "Detector CPU Usage" at 50-60%)**

4. **For reference, AUTO mode would select CPU:**
```bash
docker exec -it frigate python3 -c "
from openvino.runtime import Core
core = Core()
model = core.read_model('/openvino-model/ssdlite_mobilenet_v2.xml')
compiled = core.compile_model(model, 'AUTO')
print('AUTO selects:', compiled.get_property('EXECUTION_DEVICES'))
"
# Output: AUTO selects: ['(CPU)']
```

The detector is configured to use GPU but is actually using CPU. The device parameter is either not being passed correctly or is being overridden.

### Version

0.16.0-beta2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: <REDACTED>
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: <REDACTED>
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi  # Hardware acceleration for Intel (working)

detectors:
  openvino:
    type: openvino
    device: GPU  # Also tried GPU.0 - both result in CPU usage

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  C500:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<REDACTED>@<CAMERA_IP>:554/Streaming/channels/101
          roles:
            - record
        - path: rtsp://<REDACTED>@<CAMERA_IP>:554/Streaming/channels/102
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
    motion:
      mask: <REDACTED_COORDINATES>
      threshold: 18
      contour_area: 8
      improve_contrast: true
    zones:
      <REDACTED>

face_recognition:
  enabled: true
  model_size: large

classification:
  bird:
    enabled: true

version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta2
    privileged: true  # Required for hardware access
    restart: unless-stopped
    shm_size: "256mb"
    devices:
      - /dev/dri:/dev/dri  # Intel GPU hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"        # Web UI
      - "8554:8554"        # RTSP feeds
      - "8555:8555/tcp"    # WebRTC over TCP
      - "8555:8555/udp"    # WebRTC over UDP
    environment:
      FRIGATE_RTSP_PASSWORD: <REDACTED>
      TZ: "Europe/London"
```

### Relevant Frigate log output

```shell
# Frigate startup sequence - no errors
[2025-06-10 09:36:00] frigate.app                    INFO    : Starting Frigate (0.16.0-1fa7ce5)
[2025-06-10 09:36:00] frigate.app                    INFO    : Recording process started: 367
[2025-06-10 09:36:00] frigate.app                    INFO    : Review process started: 378
[2025-06-10 09:36:00] frigate.app                    INFO    : go2rtc process pid: 125
[2025-06-10 09:36:00] detector.openvino              INFO    : Starting detection process: 389
[2025-06-10 09:36:00] frigate.app                    INFO    : Embedding process started: 391
[2025-06-10 09:36:00] frigate.app                    INFO    : Output process started: 421
[2025-06-10 09:36:00] frigate.app                    INFO    : Camera processor started for C500: 448
[2025-06-10 09:36:00] frigate.app                    INFO    : Capture process started for C500: 455

# Detector restarts periodically (normal behavior)
[2025-06-10 09:13:36] detector.openvino              INFO    : Starting detection process: 209
[2025-06-10 09:35:45] detector.openvino              INFO    : Exited detection process...
[2025-06-10 09:36:00] detector.openvino              INFO    : Starting detection process: 389

# No GPU-related errors in logs
# No OpenVINO initialization errors
# Hardware acceleration (VAAPI) working normally for video encoding
```

### Install method

Proxmox via Docker

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

<img width="1509" alt="with env GPU variables" src="https://github.com/user-attachments/assets/912b4f31-0422-4bf8-82a3-f9e87c1643dc" />

### Any other information that may be helpful

# Additional Information

## System Environment
- **Proxmox Host**: Version 8.4.1, Kernel 6.8.12-10-pve
- **VM OS**: Debian 12 (bookworm), 8GB RAM, 4 vCPUs
- **Docker**: Version 28.2.0
- **Hardware**: Intel N100 S12 Mini Pro (Alderlake_n Gen12)
- **GPU**: Intel UHD Graphics (iGPU) passed through to VM
- **Container**: Running privileged with `/dev/dri` devices mapped

### 1. GPU is accessible and working in container:
```bash
$ docker exec -it frigate intel_gpu_top
# Shows: Intel Alderlake_n (Gen12) @ /dev/dri/card1
# GPU is functional for VAAPI video encoding

$ docker exec -it frigate ls -la /dev/dri/
crw-rw---- 1 root video 226,   1 Jun  8 21:19 card1
crw-rw---- 1 root   105 226, 128 Jun  8 21:19 renderD128
```

### 2. OpenVINO can see and use the GPU:
```bash
$ docker exec -it frigate python3 -c "
from openvino.runtime import Core
core = Core()
print('Available devices:', core.available_devices)
model = core.read_model('/openvino-model/ssdlite_mobilenet_v2.xml')
compiled = core.compile_model(model, 'GPU')
print('GPU compilation successful:', compiled.get_property('EXECUTION_DEVICES'))"

# Output:
# Available devices: ['CPU', 'GPU']
# GPU compilation successful: ['GPU.0']
```

### 3. Intel GPU compute runtime is installed:
```bash
$ docker exec -it frigate dpkg -l | grep -i opencl
ii  intel-level-zero-gpu     1.3.29735.27-914~22.04
ii  intel-opencl-icd         24.35.30872.31-996~22.04
ii  libigc1                  1.0.17791.16-1032~22.04
ii  ocl-icd-libopencl1       2.3.1-1
```

### 4. Configuration is being read correctly:
```bash
$ docker exec -it frigate python3 -c "
import yaml
with open('/config/config.yml', 'r') as f:
    config = yaml.safe_load(f)
    print(config['detectors']['openvino'])"

# Output: {'type': 'openvino', 'device': 'GPU'}
```

## Summary
- GPU hardware acceleration works perfectly for video encoding (VAAPI)
- OpenVINO can successfully use the GPU when explicitly requested
- All necessary drivers and libraries are present
- Configuration specifies GPU and is read correctly
- But the detector still uses CPU instead of GPU

This appears to be an issue with how the device configuration is passed from Frigate's config to the OpenVINO detector initialization.
