### DISCUSSION TITLE
[Bug]: Last detected snapshot is not always updated in MQTT

### DISCUSSION THREAD

**Discussion by nacree** [blakeblackshear/frigate#18655] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I'm having problem that last detected object (person) is not updated correctly in my HA instance. I can see that persons are detected correctly in Frigate, but I think that the snapshot does not update always to MQTT. It does sometimes, but clearly not every time.

I cannot see the the actual image on the MQTT server, but when reloading the Frigate integration in HA side, it at least does not show the latest image, but something from yesterday, even there have been persons detected today as well.

I don't know how to debug this anymore, or if there is anything else to provide.

I'm using the 0.16 beta, is it supported by the Frigate integration in the stable HA, and Advanced camera card, or are there some combability issues?

### Steps to reproduce

1. Have some objects detected by Frigate
2. Detected objects shown in Frigate
3. Last detected object published in MQTT does not update, or updates randomly

### Version

0.16.0-1fa7ce5

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.72.8
  client_id: frigate
  port: 1883
  user: username
  password: password

tls:
  # Disable TLS for port 8971
  enabled: false

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-generic-audio-aac
#  input_args: preset-rtsp-restream

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
  ...
    etuovi:
      - ffmpeg:rtsp://....:......@192.168.72.158:554/user=xxxxxxx_password=xxxxxxxx_channel=1_stream=0.sdp?real_stream#video=h264#audio=copy#hardware
  ...

record:
  enabled: true
  retain:
    days: 5
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  bounding_box: true

detect:
  enabled: true
  height: 720
  width: 1280
  fps: 1

live:
  height: 480

motion:
  enabled: true
  threshold: 30
  mqtt_off_delay: 30
  lightning_threshold: 0.8
  improve_contrast: true

cameras:

  etuovi:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/etuovi
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1152
      height: 648
      fps: 5
    record:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - deer
      filters:
        person:
          mask: 0.028,0.574,0.123,0.985,0.215,0.933,0.127,0.505
    motion:
      enabled: true
      mask:
        - 0,0,0,1,0.212,1,0.15,0
        - 0.719,0,0.71,0.099,1,0.356,1,0
      threshold: 40
      contour_area: 15
      improve_contrast: true

....

version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
Not related
```

### Relevant Frigate log output

```shell
Full of disconnected camera outputs..
```

### Relevant go2rtc log output

```shell
Nothing relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Not relevant

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/44544b3b-900a-4945-bb62-caadd04cd424)

### Any other information that may be helpful

This has been working fine until I switched to new PC and updated Frigate to beta version. It's hard to say which one triggered the issue. Previously MQTT broker was running on the same PC as Frigate, but they are still connected with ethernet cable, so I doubt that this is the issue.
