### DISCUSSION TITLE
[Config Support]: recoding stopped: Frigate thinks there is no free space

### DISCUSSION THREAD

**Discussion by mpeter50** [blakeblackshear/frigate#18669] [Config Support]
### Describe the problem you are having

Currently my camera has some spider web in front of it, and being set to record motion it now records constantly. As a consequence, storage space frequently runs out, and so the connected camera cannot be viewed, and also of course its not being recorded either. Due to this situation, I may have found 2 issues:
- Frigate not always being able to delete recordings
- Frigate not always being able to continue recording after making some free space

I did not clean off the spider web to be able to debug this issue.

According to [this](https://docs.frigate.video/configuration/record/#will-frigate-delete-old-recordings-if-my-storage-runs-out) in the documentation, I assume that Frigate should delete the last 2 hours of recordings when the space is running out, regardless of whether it is just recorded motion or if it is also part of an alert/detection.  
Watching the logs, I see that storage cleanup runs regularly. Sometimes it says that it wasnt able to clear 2163 MB, but after several such messages repeated every 5 minutes at one point it will log that it cleared up a similar amount of storage.

Repeated errors like these below lead me to believe that Frigate knows which recording segments it should delete, but for some reason it fails in actually deleting them:
```
2025-06-10 15:38:24.927225300  [2025-06-10 15:38:24] frigate.storage                INFO    : Less than 1 hour of recording space left, running storage maintenance...
2025-06-10 15:38:26.184191917  [2025-06-10 15:38:26] frigate.storage                ERROR   : Could not clear 2163.01 MB, currently 0 MB have been cleared. Retained recordings must be deleted.
```
```
2025-06-10 17:04:06.594052643  [2025-06-10 17:04:06] frigate.storage                INFO    : Less than 1 hour of recording space left, running storage maintenance...
2025-06-10 17:04:06.780270436  [2025-06-10 17:04:06] frigate.storage                INFO    : Cleaned up 2170.1 MB of recordings
```

Right now if I check the storage space usage on the `/system#storage` page, it seems there is ~3 GB available, I assume because of the recent successful deletion above, but the "Too many unprocessed recording segments" warnings continue, and the camera view on the main page keeps showing "No frames have been received, check error logs".

![image](https://github.com/user-attachments/assets/ed37d1a7-0a0d-4f52-aef6-e7cca60d015b)

I have been observing what is happening for a few days now, and from time to time the errors will go away, and then come back by itself. Sometimes if I open Frigate's main page the camera view will work, and sometimes it'll just show the error message.
Restarting Frigate will solve the issues temporarily, following it Frigate will be immediately able to record and display the camera feed.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: false

tls:
  enabled: false

detectors:
  cpu1:
    type: cpu
    num_threads: 1

birdseye:
  enabled: true
  mode: motion

cameras:
  cam-1:   # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://10.1.8.10:554/stream=0.sdp
          roles:
            - record
        - path: rtsp://@10.1.8.10:554/stream=1.sdp
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true

    motion:
      mask:
        - 0.015,0.024,0.309,0.028,0.311,0.075,0.014,0.083

    timestamp_style:
      effect: solid

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true

timestamp_style:
  position: tr
  format: '%Y-%m-%d %H:%M:%S'
  thickness: 1

ui:
  timezone: Europe/Budapest
  time_format: 24hour
  strftime_fmt: '%Y-%m-%d %H:%M:%S'

telemetry:
  version_check: false

logger:
  logs:
    frigate.record.maintainer: debug

version: 0.15-1
```

### Relevant Frigate log output

```shell
Too big to paste, uploaded it as attachment.
```

### Relevant go2rtc log output

```shell
not used
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
volumes:
    frigate_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /srv/frigate/config/

    frigate_media:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /srv/frigate/media

    frigate_cache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /srv/frigate/cache

networks:
    proxy:
        external: true
        name: proxy-internal

    camera-vlan:
        driver: macvlan
        driver_opts:
            ...

services:
    frigate:
        image: ghcr.io/blakeblackshear/frigate:0.15.1
        restart: unless-stopped
        networks:
            - proxy
            - camera-vlan
        volumes:
            - frigate_config:/config
            - frigate_media:/media/frigate
            - frigate_cache:/tmp/cache
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        container_name: frigate
        shm_size: "128mb"
        healthcheck:
            disable: true
```

### Object Detector

CPU (no coral)

### Any other information that may be helpful

Frigate log output: [frigate-logs.txt](https://github.com/user-attachments/files/20678596/frigate-logs.txt)

Points of interest in the log file:
- 2025-06-05 22:37:58 - Frigate startup
- 2025-06-09 17:27:43 - first unsuccessful clearing
- 2025-06-09 18:52:32 - errors started with receiving the camera stream

---

Storage statistics of the Frigate data directories made with ncdu: [frigate-1-2025-06-10.ncdu.txt](https://github.com/user-attachments/files/20678555/frigate-1-2025-06-10.ncdu.txt)
You can browse it with `ncdu -f frigate-1-2025-06-10.ncdu.txt` or view it in a text editor.

This export was made after Frigate succeeded in deleting some recordings at "2025-06-10 17:04:06".
