### DISCUSSION TITLE
LPR Not Working

### DISCUSSION THREAD

**Discussion by jamesonuk** [blakeblackshear/frigate#18670] [Ask A Question]
I setup LPR some weeks ago but I have never seen it actually label anything.    I am running Frigate+ model and I have seen plenty license_plate bounding boxes in snapshots).

<details>

<summary>Config</summary>

```yaml
version: 0.16-0

mqtt:
  enabled: true
  host: mosquitto
  port: 8883
  tls_ca_certs: /config/mqtt_certs/root-ca.pem
  tls_client_cert: /config/mqtt_certs/ha_mqtt.cert.pem
  tls_client_key: /config/mqtt_certs/ha_mqtt.key.pem
  tls_insecure: false

go2rtc:
  streams:
    landing_camera_frigate:
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@landing-camera.fqdn/Preview_01_main
    hall_camera_frigate:
      - ffmpeg:rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@hall-camera.fqdn/Preview_01_main#video=copy
    doorbell_frigate:
      - ffmpeg:https://doorbell.fqdn/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REOLINK_USER}&password={FRIGATE_REOLINK_PWD}#video=copy#audio=opus#audio=copy
      - rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@doorbell.fqdn/h264Preview_01_main
    child1_camera_frigate:
      - rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@child1-tapo-camera.fqdn/stream1
      - ffmpeg:child1_camera_frigate#audio=aac#audio=copy
    spare_tapo_frigate:
      - rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@10.111.111.105/stream1
  webrtc:
    candidates:
      - 10.99.99.2:8555
      - 10.99.99.7:8555
      - 10.99.99.8:8555
      - 192.168.40.201:8555
      - stun:8555

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://f6e5635923492009dfffcec1ec461839

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: true
  expire_interval: 1440
  retain:
    days: 7
    mode: motion

detect:
  enabled: true

snapshots:
  enabled: true

lpr:
  enabled: true
  #device: CPU
  #debug_save_plates: true
  enhancement: 3
  known_plates:
    my_car:
      - xxx
    her_car:
      - yyy

semantic_search:
  enabled: false
  model_size: small

face_recognition:
  enabled: true
  model_size: small

classification:
  bird:
    enabled: true

auth:
  cookie_secure: true
  session_length: 259200 # 3 days default is 24h

cameras:
  landing_camera_frigate:
    enabled: true
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@landing-camera.fqdn/Preview_01_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/landing_camera_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask: 0.348,0.076,0.348,0.004,0.658,0.006,0.659,0.076
    lpr:
      enabled: false
  hall_camera_frigate:
    enabled: true
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@hall-camera.fqdn/Preview_01_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/hall_camera_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask: 0.691,0.91,0.999,0.913,0.998,0.993,0.692,0.998
    lpr:
      enabled: false
  doorbell_frigate:
    ui:
      order: 1
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_REOLINK_USER}:{FRIGATE_REOLINK_PWD}@doorbell.fqdn/Preview_01_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 0.648,0,0.648,0.062,0.342,0.06,0.345,0
        - 0.545,0.573,0.795,0.664,0.8,0.554,0.78,0.415,0.707,0.289,0.581,0.231,0.449,0.263,0.354,0.371,0.316,0.45,0.289,0.531,0.395,0.529,0.398,0.552,0.497,0.551
    zones:
      drive_entry_zone:
        coordinates: 0.545,0.576,0.702,0.635,0.354,0.66,0.367,0.59
        inertia: 1
        loitering_time: 0
      parking_zone:
        coordinates: 0.32,1,1,1,1,0.729,0.709,0.632,0.273,0.662,0,0.658,0,1
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - dog
        - car
        - bird
        - dog
        - license_plate
      filters:
        car: {}
    review:
      alerts:
        #labels:
          #- license_plate
        required_zones:
          - drive_entry_zone
          - parking_zone
      detections:
        #labels:
          #- license_plate
        required_zones:
          - drive_entry_zone
          - parking_zone
  child1_camera_frigate:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_TAPO_USER}:{FRIGATE_TAPO_PWD}@child1-tapo-camera.fqdn/stream2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/child1_camera_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: child1-tapo-camera.fqdn
      port: 2020
      user: '{FRIGATE_TAPO_USER}'
      password: '{FRIGATE_TAPO_PWD}'
    motion:
      mask: 0,0.074,0.366,0.076,0.367,0,0,0,0,0
    lpr:
      enabled: false
  spare_tapo_frigate:
    enabled: true
    ui:
      order: 99
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/spare_tapo_frigate
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    onvif:
      host: 10.111.111.105
      port: 2020
      user: '{FRIGATE_TAPO_USER}'
      password: '{FRIGATE_TAPO_PWD}'
    motion:
      mask: 0,0.05,0.322,0.056,0.319,0,0,0,0,0
    lpr:
      enabled: false
```

</details>

It is the doorbell camera that I have been playing with (I know it isn't ideal but there are clear images of license plates)

This seems to match the docs for it to work but nothing has ever been labelled.

If I uncomment the labels section on the camera it actually stops any reviews getting created (there is nothing at all in logs but I can walk in front of the camera and it doesn't create a review even though it flags a person as being detected)

**Comment by NickM-27** [comment]
Are you sure the plate is higher than the min area for lpr?

**Reply by jamesonuk** [reply]
> Are you sure the plate is higher than the min area for lpr?

Ummm....   How do I check?

> You should follow the LPR debugging steps in the docs: https://deploy-preview-16390--frigate-docs.netlify.app/configuration/license_plate_recognition/#how-do-i-debug-lpr-issues

I did enable this but haven't had chance to look properly yet.
It might be an understanding this but I am not sure where I should be seeing the license plate data.   I can see the last recognised plate entity in HA is unknown (and has always been unknown) which I guess means I have missed something.

In the object lifecycle I see
![image](https://github.com/user-attachments/assets/34707d62-9c0d-40ef-adce-30349093a224)

I believe when it is working I should see license plate as a label on the explore tab and recognised plates on the more filters panel?   I have also seen people with the recognised plate name in brackets in the label of the details tab of explore screen?

**Reply by NickM-27** [reply]
> Ummm.... How do I check?

check the snapshot for the cars and see what the area of the license plate is

> I believe when it is working I should see license plate as a label on the explore tab and recognised plates on the more filters panel?

No, license plate is only shown in explore tab for dedicated LPR cameras. When using it alongside car detection you will simply see the recognized plate characters for the car in explore. And yes you will be able to search through license plates in the more filters panel.

**Reply by hawkeye217** [reply]
> I believe when it is working I should see license plate as a label on the explore tab and recognised plates on the more filters panel? I have also seen people with the recognised plate name in brackets in the label of the details tab of explore screen?

That's correct, if you're running with dedicated LPR Mode. Plates will show in the tracked object details pane in Explore for car objects if not. Recognized plate numbers will not appear in the object lifecycle pane.

**Reply by jamesonuk** [reply]
> check the snapshot for the cars and see what the area of the license plate is

I am struggling a bit here as I simply cannot find the right docs to say where you get the area.   Is the number after the object detection % the number of pixels?

> No, license plate is only shown in explore tab for dedicated LPR cameras. 

As in you will only see an image strip for licence plate as in where I see Person, Car and Bird here you will only see License Plate if you have configured a dedicated LPR camera?
![image](https://github.com/user-attachments/assets/2f1c25ce-92f1-4318-9c61-c756bb2480b0)


> When using it alongside car detection you will simply see the recognized plate characters for the car in explore. And yes you will be able to search through license plates in the more filters panel

What is the right config.    I am a bit lost as to what options apply for Frigate+ / Dedicated LPR camera etc.

Using Frigate+ and a non-dedicated LPR camera should I have license plate in my camera detect object list
```
    objects:
      track:
        - person
        - dog
        - car
        - bird
        - dog
        - license_plate
```

and what about labels?

```
    review:
      alerts:
        #labels:
          #- license_plate
        required_zones:
          - drive_entry_zone
          - parking_zone
      detections:
        #labels:
          #- license_plate
        required_zones:
          - drive_entry_zone
          - parking_zone
```
When I actually uncomment the label entries here I stop getting any reviews at all from that camera.
