### DISCUSSION TITLE
How I manually tell Frigate to record?

### DISCUSSION THREAD

**Discussion by SergioRius** [blakeblackshear/frigate#18672] [Ask A Question] [answered]
I'll have a big delivery tomorrow, and as a part of the procedure I must record the entire unload process and send the footage to the source party. I have a Frigate camera in the perfect spot and I thought of using it, but I always seen like gaps or jumps in the recordings. I suppose it omits sections without interest or events.

Can I push some button on the interface and tell Frigate to unconditionally record until I push that button again?
Just like dashcam in teslas (and all other dashcam), that one can push the cam button in case of an accident or any issue on the road.

**Comment by hawkeye217** [comment, marked as answer]
Frigate 0.16, currently in beta, adds an "on demand recording" button to the UI in the single camera Live view. This manually creates a recording that is retained based on the [retention policy](https://docs.frigate.video/configuration/record/#most-conservative-ensure-all-video-is-saved) you've defined in your config.

If you are not running Frigate 0.16, you could use the [manual event API](https://docs.frigate.video/integrations/api/create-event-events-camera-name-label-create-post/), or you could temporarily adjust your retention policy to retain all recorded footage until the delivery is over.

**Reply by SergioRius** [reply]
Mmmm.... the problem is that if I leave the recording as I have it now, it naturally does jumps between in/out events. The timeline, I mean. It's always jumping.
They request me for a continuous recording, so it doesn't appear manipulated. And if possible from two angles. It may be 45m, between unload, leave it in place and opening for inspection. Yeah, We're having big issues with transportation lately.
It's scheduled for tomorrow, I'll continue thinking on solutions.

This is what I have for recording:
```yaml
record:
  enabled: true
  sync_recordings: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 2
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 2
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  # crop: True
  retain:
    # Required: Default retention days (default: shown below)
    default: 2
```

I don't understand what has to be done to record continuously. Change motion for all or removing all the record section and just put the first code described [HERE](https://docs.frigate.video/configuration/record/#continuous-recording).
I'm afraid I end with the inverse effect and record nothing.

The Api endpoint you describe, what exactly does? Force record until called again? Record for an amount of time?
