### DISCUSSION TITLE
Coral Edge TPU configured and detected by Frigate does not detect objects

### DISCUSSION THREAD

**Discussion by andregoncalvespires** [blakeblackshear/frigate#18679] [Detector Support]
### Describe the problem you are having

I have been using Frigate for over 2 years with Coral USB in a HASSOS installation and a month ago I added a PCIE. In this short period I have used both together and also just the PCIE. On one occasion when I was using just the PCIE, I noticed that object detection was not working, even though all the inference metrics were showing. I went back to using the devices together and everything was normal.

I am now migrating my infrastructure to a mini PC I3 1220p running Proxmox. I configured Frigate in Docker on Debian in an LXC. At first, I did not intend to use Coral USB, just the PCIE. However, to my surprise, object detection is not working again, even though all the information indicates that it was recognized.

With USB or Openvino, detection works perfectly.

Could you suggest a reason and/or fix for this to happen?

### Version

 0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  host: 192.168.77.109
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate@

database:
  path: /config/frigate.db

detectors:
#  coral:
#    type: edgetpu
#    device: usb
  coral_pci:
    type: edgetpu
    device: pci
#  coral_usb:
#    type: edgetpu
#    device: usb

##openvino
#  ov_0:
#    type: openvino
#    device: GPU
#  ov_1:
#    type: openvino
#    device: GPU
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  path: /openvino-model/ssdlite_mobilenet_v2.xml
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: true
  mode: continuous
  restream: true
  layout:
    max_cameras: 10

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264

  #Válido para Reolink
  output_args:
    record: preset-record-generic-audio-copy

record:
  enabled: true
  retain:
    days: 5
    mode: all
  sync_recordings: true

  alerts:
    retain:
      days: 5
  detections:
    retain:
      days: 5
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 5

detect:
  enabled: true
  fps: 6

go2rtc:
  streams:

    #DVR
    sacada_frente: #Frente da Casa - Beco
      - ffmpeg:rtsp://admin:agp201471@192.168.77.178:554/chID=2&streamType=main&linkType=tcpa#video=copy
#      - rtsp://admin:agp201471@192.168.77.178:554/chID=2&streamType=main&linkType=tcpa

    frente_da_casa_beco: #Frente da Casa - Beco
      - ffmpeg:rtsp://admin:agp201471@192.168.77.178:554/chID=3&streamType=main&linkType=tcpa#video=copy
#      - rtsp://admin:agp201471@192.168.77.178:554/chID=3&streamType=main&linkType=tcpa

    sacada_fundos: #Frente da Casa - Beco
      - ffmpeg:rtsp://admin:agp201471@192.168.77.178:554/chID=4&streamType=main&linkType=tcpa#video=copy
#      - rtsp://admin:agp201471@192.168.77.178:554/chID=4&streamType=main&linkType=tcpa

    porta_lateral: #Fundos - Piscina
      - ffmpeg:rtsp://admin:agp201471@192.168.77.178:554/chID=5&streamType=main&linkType=tcpa#video=copy
#      - rtsp://admin:agp201471@192.168.77.178:554/chID=5&streamType=main&linkType=tcpa


    # Reolink
    visao_da_rua_garagem: #Visão da Rua - Garagem
      - ffmpeg:http://192.168.77.28/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
    visao_da_rua_garagem_ext:
      - ffmpeg:http://192.168.77.28/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
#    visao_da_rua_garagem_sub:
#      - ffmpeg:http://192.168.77.28/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471

    visao_da_rua_calcada: #Visão da Rua - Calçada
      - ffmpeg:http://192.168.77.38/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
    visao_da_rua_calcada_ext:
      - ffmpeg:http://192.168.77.38/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
#    visao_da_rua_calcada_sub:
#      - ffmpeg:http://192.168.77.38/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471

    fundos_area_servico: #Fundos - Área de Serviço
      - ffmpeg:http://192.168.77.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
    fundos_area_servico_ext:
      - ffmpeg:http://192.168.77.42/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
#    fundos_area_servico_sub:
#      - ffmpeg:http://192.168.77.42/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471

    fundos_piscina: #Fundos - Piscina
      - ffmpeg:rtsp://admin:agp201471@192.168.77.53:554/h265Preview_01_main
    fundos_piscina_ext:
      - ffmpeg:http://192.168.77.53/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
#    fundos_piscina_sub:
#      - ffmpeg:http://192.168.77.53/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471

    frente_da_casa_garagem: #Frente da Casa - Garagem
      - ffmpeg:http://192.168.77.22/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
    frente_da_casa_garagem_ext:
      - ffmpeg:http://192.168.77.22/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
#    frente_da_casa_garagem_sub:
#      - ffmpeg:http://192.168.77.22/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471

    videoporteiro: #Videoporteiro
      - ffmpeg:http://192.168.77.47/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus

    videoporteiro_ext:
      - ffmpeg:http://192.168.77.47/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
      - rtsp://admin:agp201471@192.168.77.47:554/h264Preview_01_sub

#    videoporteiro_sub:
#      - "ffmpeg:http://192.168.77.47/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471"

    sala: #sala
      - ffmpeg:http://192.168.77.70/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
    sala_ext:
      - ffmpeg:http://192.168.77.70/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471
      - rtsp://admin:agp201471@192.168.77.70:554/h264Preview_01_sub

#    sala_sub:
#      - "ffmpeg:http://192.168.77.70/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471"

  webrtc:
    candidates:
      - 192.168.77.109:8555
      - stun:8555

cameras:

  #REOLINK#########################
  videoporteiro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/videoporteiro
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
        - path: rtsp://127.0.0.1:8554/videoporteiro_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
#    live:
#      stream_name: videoporteiro_ext
#    audio:
#      enabled: True
    objects:
      track:
        - person
      mask:
        - 1,0,0.561,0,0.566,0.671,0.603,0.678,0.722,1,1,1
        - 0.224,1,0.226,0,0,0,0,1
    motion:
      mask:
        - 1,0,0.561,0,0.566,0.671,0.602,0.68,0.72,1,1,1
        - 0.224,1,0.226,0,0,0,0,1
    zones:
      portão_social:
        coordinates: 0.235,1,0.485,1,0.712,1,0.579,0.743,0.55,0.685,0.549,0.519,0.539,0,0.238,0
        objects: person
        inertia: 3
        loitering_time: 0
    mqtt:
      enabled: false
    ui:
      order: 1
    birdseye:
      order: 1
    review:
      detections:
#      alerts:
        required_zones: portão_social

#####REOLINK
  #REOLINK#########################
  sala:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sala
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
        - path: rtsp://127.0.0.1:8554/sala_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
    record:
      enabled: false
      retain:
        mode: motion
    objects:
      track:
        - person
    mqtt:
      enabled: false
    ui:
      order: 11
    birdseye:
      order: 11
    onvif:
      # Required: host of the camera being connected to.
      # NOTE: HTTP is assumed by default; HTTPS is supported if you specify the scheme, ex: "https://0.0.0.0".
      host: 192.168.77.70
      # Optional: ONVIF port for device (default: shown below).
      port: 8000
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: agp201471

  #REOLINK#########################
    zones: {}
    motion:
      mask:
        - 0,0,0.425,0,0.428,0.055,0,0.063
        - 0.712,0.004,0.698,0.159,0.766,0.178,0.778,0.004
  visao_da_rua_garagem:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/visao_da_rua_garagem
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/visao_da_rua_garagem_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
#    live:
#      stream_name: visao_da_rua_garagem_ext
    objects:
      track:
        - person
        - car
        - motorcycle
      mask: 1,0,0.034,0,0.032,0.155,0.135,0.139,0.246,0.302,0.754,1,1,1
    motion:
      mask: 1,0,0.036,0,0.034,0.155,0.135,0.139,0.246,0.302,0.754,1,1,1
    zones:
      calcada:
        coordinates: 
          0,0.254,0.029,0.229,0.034,0.165,0.133,0.155,0.164,0.203,0.345,0.447,0.743,1,0.079,1
        objects:
          - person
          - motorcycle
          - car
        inertia: 3
        loitering_time: 0
      Entrada_Garagem:
        coordinates: 0.048,0.545,0.083,0.546,0.16,1,0,1,0,0.31
        loitering_time: 0
        objects: person
        inertia: 3
    ui:
      order: 2
    birdseye:
      order: 2
    review:
#      alerts:
#        required_zones: Entrada_Garagem
      detections:
        required_zones: calcada


  #REOLINK#########################
  visao_da_rua_calcada:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/visao_da_rua_calcada
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/visao_da_rua_calcada_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
#    live:
#      stream_name: visao_da_rua_calcada_ext
    objects:
      track:
        - person
        - motorcycle
        - car
      mask: 
        0.005,0.985,0,0.006,0.942,0,0.945,0.174,0.777,0.188,0.723,0.259,0.479,0.663,0.246,1
    motion:
      mask: 
        -0.001,0.006,1,0,0.958,0.054,0.949,0.162,0.771,0.182,0.679,0.316,0.557,0.52,0.214,1,0,1
    zones:
      calcada:
        coordinates: 0.895,1,0.273,1,0.593,0.534,0.783,0.199,0.948,0.193,0.959,0.309,0.942,0.716
        loitering_time: 0
        inertia: 3
    ui:
      order: 3
    birdseye:
      order: 3

#### DVR
  sacada_frente:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sacada_frente
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic
    objects:
      track:
        - person
        - bird
      mask:
        - 0.266,0,0,0,0,1,0.326,1
        - 1,0.419,1,0,0.906,0,0.299,0,0.361,0.105,0.395,0.112,0.443,0.171,0.486,0.213,0.579,0.324,0.722,0.522,1,0.931
    motion:
      mask:
        - 0.266,0,0,0,0,1,0.326,1
        - 1,0.419,1,0,0.906,0,0.299,0,0.357,0.103,0.396,0.119,0.441,0.179,0.485,0.217,0.576,0.326,0.648,0.434,0.722,0.524,0.862,0.729,1,0.939
    record:
      retain:
        mode: motion
    ui:
      order: 5
    birdseye:
      order: 5
    zones:
      Muro_da_Frente:
        coordinates: 
          0.957,0.992,0.681,0.541,0.624,0.528,0.566,0.432,0.572,0.366,0.531,0.315,0.493,0.269,0.459,0.218,0.409,0.204,0.363,0.108,0.403,0.139,0.448,0.184,0.513,0.257,0.689,0.489,0.993,0.934,0.997,0.994
        loitering_time: 0
        inertia: 3

  ######REOLINK
  frente_da_casa_garagem: #Frente da Casa - Garagem
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frente_da_casa_garagem
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
        - path: rtsp://127.0.0.1:8554/frente_da_casa_garagem_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
#    live:
#      stream_name: frente_da_casa_garagem_ext
#    audio:
#      enabled: True
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
      mask: 
        0.988,0,0,0,0,0.108,0.147,0.025,0.379,0,0.56,0,0.66,0.078,0.811,0.047,0.987,0.109
      filters:
        person:
          threshold: 0.73
    motion:
      mask: 
        0.987,0,0,0,0,0.112,0.146,0.021,0.303,0,0.552,0,0.66,0.079,0.812,0.045,0.985,0.123
    zones:
      garagem:
        coordinates: 
          0,1,1,1,1,0.817,0.774,0.663,0.602,0.578,0.654,0.086,0.535,0.013,0.296,0.012,0.147,0.034,0,0.134
        inertia: 3
        loitering_time: 0
    ui:
      order: 4
    birdseye:
      order: 4
    review:
      detections:
        required_zones: garagem

  #### Câmera do DVR######################
  frente_da_casa_beco:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frente_da_casa_beco
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic
    objects:
      track:
        - person
        - motorcycle
        - car
        - dog
      filters:
        person:
          mask: 0.982,0.456,0.911,0.45,0.901,0.621,0.97,0.636
    motion:
      mask: 0.883,0,0.704,0,0.702,0.056,0.891,0.047
    zones:
      beco:
        coordinates: 0.974,0.479,0.993,0.328,1,0,0.791,0,0.778,0.499,0.676,0.775,0.905,0.923
        objects: person
        filters:
          person:
            threshold: 0.75
        inertia: 3
        loitering_time: 0
      varanda:
        coordinates: 0.669,0.77,0.77,0.494,0.783,0,0.209,0,0.238,0.304,0.17,0.381
        objects:
          - person
          - motorcycle
        filters:
          person:
            threshold: 0.8
        inertia: 3
        loitering_time: 0
      Gramado:
        coordinates: 0.079,0.985,0.005,0.73,0.035,0.63,0.2,0.441,0.895,0.942,0.885,0.998
        loitering_time: 0
    record:
      retain:
        mode: motion
    ui:
      order: 6
    birdseye:
      order: 6

#### Câmera do DVR######################
  sacada_fundos:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sacada_fundos
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic
    objects:
      track:
        - person
      mask: 
        0.242,0.986,-0.001,0.99,0.001,0,0.997,-0.002,0.998,0.062,0.683,0.062,0.646,0.049,0.415,0.097,0.274,0.255,0.554,0.441
    motion:
      mask:
        - 710,320,344,190,520,75,821,38,888,45,1280,49,1280,0,609,0,0,0,0,720,311,720
    record:
      retain:
        mode: motion
    ui:
      order: 7
    birdseye:
      order: 7
    zones:
      Telhado_Area_Serviço:
        coordinates: 0.534,0.408,0.29,0.254,0.412,0.116,0.642,0.064,0.703,0.071,0.691,0.131
        loitering_time: 0

#### Câmera do DVR######################
  porta_lateral:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porta_lateral
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    objects:
      track:
        - person
      mask:
        - 0.016,0.409,0.104,0.385,0.114,0.075,0.145,0.082,0.143,0.21,0.233,0.274,0.321,0.306,0.347,0,0.245,0,0,0,0,1,0.054,1
        - 0.714,0,0.712,0.07,1,0.068,1,0
    motion:
      mask:
        - 0.016,0.409,0.104,0.385,0.114,0.075,0.145,0.082,0.143,0.21,0.233,0.274,0.321,0.306,0.347,0,0.245,0,0,0,0,1,0.054,1
        - 0.714,0,0.712,0.07,1,0.068,1,0
    zones:
      entrada_lateral:
        coordinates: 
          0.54,0.988,0.289,0.625,0.137,0.36,0.138,0.086,0.122,0.09,0.112,0.398,0.023,0.42,0.065,1
        objects: person
        inertia: 3
        loitering_time: 0
    record:
      retain:
        mode: motion
    ui:
      order: 8
    birdseye:
      order: 8

  #REOLINK#########################
  fundos_piscina:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fundos_piscina
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/fundos_piscina_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
    audio:
      enabled: false
      listen:
        - alarm
        - yell
        - crying
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.73
      mask:
        - 0.577,0,0.572,0.073,1,0.075,1,0
        - 0.921,0.08,0.865,0.075,0.808,0.078,0.811,0.252,0.919,0.286
        - 1,0.065,0.942,0.072,0.94,0.289,1,0.298
        - 0,0.002,0,0.064,0.165,0
    motion:
      mask:
        - 0.577,0,0.572,0.073,1,0.075,1,0
        - 0.921,0.08,0.865,0.075,0.808,0.078,0.811,0.252,0.919,0.286
        - 1,0.065,0.942,0.072,0.94,0.289,1,0.298
        - 0,0.002,0,0.064,0.165,0
    zones:
      telhado_fundos:
        coordinates: 0.174,0.006,0,0.08,0,0.197,0.291,0.073,0.512,0.02,0.567,0.006
        objects: person
        inertia: 3
        loitering_time: 0
      area_de_servico:
        coordinates: 
          0.622,0.086,0.569,0.085,0.566,0.03,0.455,0.046,0.263,0.106,0.286,0.406,0.363,0.44,0.497,0.341,0.581,0.287,0.751,0.337,0.896,0.389,1,0.446,1,0.349,0.801,0.264,0.801,0.169,0.633,0.124
        objects: person
        inertia: 3
        loitering_time: 0
      piscina:
        coordinates: 1,0.451,0.799,0.36,0.579,0.294,0,0.739,0,1,0.453,1,1,1
        objects: person
        inertia: 3
        loitering_time: 0
      nadando:
        coordinates: 0.666,1,0.786,0.693,0.875,0.435,0.606,0.329,0.153,0.69,0.422,1
        objects:
          - person
          - dog
        inertia: 3
        loitering_time: 0
      churrasqueira:
        coordinates: 0.257,0.105,0.131,0.156,0,0.229,0,0.716,0.354,0.445,0.281,0.418
        objects: person
        inertia: 3
        loitering_time: 0
    record:
      retain:
        mode: motion
    ui:
      order: 9
    birdseye:
      order: 9
    review:
      detections:
        required_zones:
          - telhado_fundos
          - churrasqueira
          - nadando
          - area_de_servico
          - piscina

  #REOLINK#########################
  fundos_area_servico:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fundos_area_servico
          input_args: preset-rtsp-restream
          roles:
            - record
#            - audio
        - path: rtsp://127.0.0.1:8554/fundos_area_servico_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
#            - record
#    live:
#      stream_name: fundos_area_servico_ext
#    audio:
#      enabled: True
#      listen:
#        - alarm
#        - yell
#        - crying
    objects:
      track:
        - person
        - dog
      mask: 0.001,0.049,0,0.003,0.997,0,0.998,0.22,0.669,0.07,0.432,0.028,0.42,0.052
    motion:
      mask:
        - 600,50,896,150,896,0,538,0,0,0,0,38,377,37,387,22
    zones:
      area_de_servico:
        coordinates: 896,145,896,311,896,672,584,467,752,346,561,248,602,213,611,61
        objects:
          - person
        filters:
          person:
            threshold: 0.50
            min_area: 3000
      piscina:
        coordinates: 
          0.156,1,0.439,0.845,0.593,0.723,0.798,0.542,0.332,0.201,0.32,0.118,0,0.214,0,0.646,0,1
        objects:
          - person
      nadando:
        coordinates: 395,415,567,336,376,222,267,158,171,192,55,229,98,339,177,502
        objects:
          - person
          - dog
      churrasqueira:
        coordinates: 602,63,393,24,379,37,350,43,352,109,330,138,544,239,591,207
        objects:
          - person
    record:
      retain:
        mode: motion
    ui:
      order: 10
    birdseye:
      order: 10

version: 0.15-1
camera_groups:
  Geral:
    order: 4
    icon: LuEye
    cameras: birdseye
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /mnt/md0/cameras/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxxxxxx"
```

### Relevant Frigate log output

```shell
2025-06-11 11:05:01.155152224  [INFO] Preparing Frigate...
2025-06-11 11:05:01.411310784  [INFO] Starting Frigate...
2025-06-11 11:05:03.967379264  [2025-06-11 11:05:03] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-06-11 11:05:04.023938928  [2025-06-11 11:05:04] frigate.util.config            INFO    : frigate config does not need migration...
2025-06-11 11:06:11.215336373  [2025-06-11 11:06:11] frigate.app                    INFO    : Starting Frigate (0.15.0-6cb5cfb)
2025-06-11 11:06:11.230185517  [2025-06-11 11:06:11] peewee_migrate.logs            INFO    : Starting migrations
2025-06-11 11:06:11.230330620  [2025-06-11 11:06:11] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-06-11 11:06:11.577749338  [2025-06-11 11:06:11] frigate.app                    INFO    : Recording process started: 593
2025-06-11 11:06:11.577788105  [2025-06-11 11:06:11] frigate.app                    INFO    : Review process started: 595
2025-06-11 11:06:11.579165893  [2025-06-11 11:06:11] frigate.app                    INFO    : go2rtc process pid: 96
2025-06-11 11:06:11.589841960  [2025-06-11 11:06:11] detector.coral_pci             INFO    : Starting detection process: 609
2025-06-11 11:06:11.599691349  [2025-06-11 11:06:11] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2025-06-11 11:06:11.605497763  [2025-06-11 11:06:11] frigate.app                    INFO    : Output process started: 628
2025-06-11 11:06:11.609287147  [2025-06-11 11:06:11] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-06-11 11:06:12.648908194  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for videoporteiro: 736
2025-06-11 11:06:12.648913332  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for sala: 737
2025-06-11 11:06:12.648918959  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for visao_da_rua_garagem: 743
2025-06-11 11:06:12.657158624  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for visao_da_rua_calcada: 753
2025-06-11 11:06:12.664819217  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for sacada_frente: 761
2025-06-11 11:06:12.672074751  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for frente_da_casa_garagem: 769
2025-06-11 11:06:12.679154230  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for frente_da_casa_beco: 775
2025-06-11 11:06:12.688053035  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for sacada_fundos: 787
2025-06-11 11:06:12.696778998  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for porta_lateral: 798
2025-06-11 11:06:12.705449776  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for fundos_piscina: 803
2025-06-11 11:06:12.712730039  [2025-06-11 11:06:12] frigate.app                    INFO    : Camera processor started for fundos_area_servico: 809
2025-06-11 11:06:12.731874812  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for videoporteiro: 824
2025-06-11 11:06:12.739848160  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for sala: 827
2025-06-11 11:06:12.764738627  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for visao_da_rua_garagem: 836
2025-06-11 11:06:12.772331374  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for visao_da_rua_calcada: 839
2025-06-11 11:06:12.781967853  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for sacada_frente: 845
2025-06-11 11:06:12.799665388  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for frente_da_casa_garagem: 854
2025-06-11 11:06:12.815783494  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for frente_da_casa_beco: 867
2025-06-11 11:06:12.856673735  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for sacada_fundos: 886
2025-06-11 11:06:12.877192748  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for porta_lateral: 963
2025-06-11 11:06:12.887077566  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for fundos_piscina: 988
2025-06-11 11:06:12.898187120  [2025-06-11 11:06:12] frigate.app                    INFO    : Capture process started for fundos_area_servico: 1007
2025-06-11 11:06:13.239565138  [2025-06-11 11:06:13] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-06-11 11:06:13.420008598  [2025-06-11 11:06:13] frigate.api.fastapi_app        INFO    : FastAPI started
```

### Install method

Proxmox via Docker

### Object Detector

Coral

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/62413870-a918-45ce-88b9-7b2ea3c6532f)
![image](https://github.com/user-attachments/assets/de22696a-d116-4061-9862-04bc63b62d2d)

![image](https://github.com/user-attachments/assets/f3d6d570-c465-46ba-a50e-aabeeea97ed8)
