### DISCUSSION TITLE
Can't increase shm size

### DISCUSSION THREAD

**Discussion by Pilou44** [blakeblackshear/frigate#18689] [Ask A Question] [answered]
Hi,
I'm trying to increase shm size. I've tried many things, read a lot of topics and didn't find anything working. If I put another value than 64mb, Frigate doesn't run, ending with "Fatal Python error: Fatal Python error: Bus errorBus error"
I'm running on a Raspberry Pi 4B with 4GB RAM. 

Here's my docker-compose.yml:
```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.1-standard-arm64
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "*********"

```

I've changed shm_size from 64mb to 128mb, but I keep having message "The current SHM size of 64.0MB is too small, recommend increasing it to at least 116.4MB."
Any idea ?
