### DISCUSSION TITLE
[Config Support]: High FFMPEG CPU Usage (93%)

### DISCUSSION THREAD

**Discussion by szoller** [blakeblackshear/frigate#18693] [Config Support]
### Describe the problem you are having

Hello,

i experience high CPU load by frigate even when using a Google Coral TPU (USB) which seems to be successfully connected.

Frigate runs as docker container on my Synology 918+ (16GB RAM).

I was told that using a Coral TPU it would not take much ressources, but it does. My Synology has around 35-40% CPU load, before it was like <10%.

Maybe i just have some wrong settings, so I attached my config below.

I'm just running one single camera with maybe a second one later. Just FullHD.

Detector CPU Usage is around 4% - at least thats shown on metrics page

So is there something I can improve?

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
database:
  path: /config/frigate.db
  
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: auto

cameras:
  Vorgarten: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWORD@192.168.xx.xxx:554/H.264 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 2560
      height: 1440
    zones:
      Parkbereich:
        coordinates: 0.111,0.577,0,0.585,0.039,0.288,0.125,0.305
        loitering_time: 0
      Haustür:
        coordinates: 0.626,0.605,0.633,0.123,0.496,0.169,0.498,0.48,0.514,0.599
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Parkbereich
          - Haustür
record:
  enabled: True
  retain:
    days: 1
    mode: motion
  alerts:
    retain:
      days: 7
      mode: motion
  detections:
    retain:
      days: 7
      mode: motion

objects:
  track:
    - person
    - cat
    - dog
    - car

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - car
      - cat
      - dog
      - person

detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: small
```

### Relevant Frigate log output

```shell
info    | 2025-06-12 15:09:18 | frigate.api.fastapi_app               | FastAPI started
info    | 2025-06-12 15:09:20 | frigate.detectors.plugins.edgetpu_tfl | TPU found
error   | 2025-06-12 15:09:43 | frigate.util.services                 | Unable to poll intel GPU stats: Failed to initialize PMU! (Invalid argument)
unknown | 2025-06-12 15:29:49 | unknown                               | 25-06-12 15:09:43.481635755
info    | 2025-06-12 15:18:49 | frigate.comms.dispatcher              | Setting motion threshold for Vorgarten: 30
info    | 2025-06-12 15:18:49 | frigate.comms.dispatcher              | Setting motion contour area for Vorgarten: 10
```

### Relevant go2rtc log output

```shell
none
```

### Operating system

Other

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
     # - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
     # - /dev/video11:/dev/video11 # For Raspberry Pi 4B
     # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/config
      - /volume1/surveillance:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "XYXY:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "XYXYXY"
```

### Object Detector

Coral
