### DISCUSSION TITLE
[Support]: Camera Audio Keeps Getting Disabled

### DISCUSSION THREAD

**Discussion by BrianRich88** [blakeblackshear/frigate#18706] [General Support]
### Describe the problem you are having

I'm having this weird issue where all of my camera audio keeps getting disabled after a little bit. This is killing my WAF with Frigate as I'm replacing any type of cloud integration with Frigate. I'm running this on my Unraid server (5700x, 32gb RAM, GTX 1660 Super) in a docker container with 3000MB shm size. I realize this is a huge shm size; I have been increasing it as part of troubleshooting.

The DrivewayCam is a Reolink Duo 2 (the panoramic one). I've tried removing this from my config entirely and it will still happen. Cam1, Cam2, Kitchen, Garage, SumpPump, Basement, Shop, Utility are all Tapo C110's running at 1080p 30fps. Backyard and BackPorch are Reolink RLC-820A's.

I have been playing with h264 and h265 and would highly prefer h265 for the recording efficiency, and Chrome now supports h265 viewing so I think this should work ok.

From what I can tell, all cameras do in fact have native AAC audio, however I have recently tried re-encoding it to ensure that it's AAC, however audio still gets disabled.

I can reboot frigate, and camera audio will be enabled. Sometimes it's only for 10 minutes, other times it will last an hour or two (which unfortunately gives me hope thinking that I fixed it). I feel I've tried almost everything which is why I'm reaching out for help today.

This is causing audio to be disabled in Live View, as well as in the recordings. It gets disabled in both, and happens to all cameras (not just the Tapo or Reolink cameras).

I can provide go2rtc or frigate logs if that will help at all. I appreciate anyone who takes the time to read this.

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Chrome Version 137.0.7151.104

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.###
  user: mqtt-user
  password: ###

#ui:
#  live_mode: webrtc

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  #hwaccel_args: preset-nvidia-h264
  hwaccel_args: preset-nvidia-h265
  output_args:
    #record: preset-record-generic-audio-aac
    record: preset-record-generic-audio-copy

model:
  path: plus://###

go2rtc:
  streams:
    Cam1:
      - rtsp://user:pass@192.168.1.105:554/stream1
      - "ffmpeg:Cam1#audio=aac"
    Cam2:
      - rtsp://user:pass@192.168.1.108:554/stream1
      - "ffmpeg:Cam2#audio=aac"
    KitchenCam:
      - rtsp://user:pass@192.168.1.107:554/stream1
      - "ffmpeg:KitchenCam#audio=aac"
    GarageCam:
      - rtsp://user:pass@192.168.1.106:554/stream1
      - "ffmpeg:GarageCam#audio=aac"
    DoorbellCam:
      - rtsp://user:pass@192.168.1.99:554/h265Preview_01_main
      - "ffmpeg:DoorbellCam#audio=aac"
    BackPorchCam:
      - rtsp://user:pass@192.168.1.100:554/h265Preview_01_main
      - "ffmpeg:BackPorchCam#audio=aac"
    DrivewayCam:
       - rtsp://user:pass@192.168.1.243:554/h265Preview_01_main
       - "ffmpeg:DrivewayCam#audio=aac"
    DrivewayCamSub:
       - rtsp://user:pass@192.168.1.243:554/h265Preview_01_sub
       - "ffmpeg:DrivewayCamSub#audio=aac"
    BackyardCam:
      - rtsp://user:pass@192.168.1.109:554/h265Preview_01_main
      - "ffmpeg:BackyardCam#audio=aac"
    SumpPumpCam:
      - rtsp://user:pass@192.168.1.110:554/stream1
      - "ffmpeg:SumpPumpCam#audio=aac"
    BasementCam:
      - rtsp://user:pass@192.168.1.111:554/stream1
      - "ffmpeg:BasementCam#audio=aac"
    ShopCam:
      - rtsp://user:pass@192.168.1.112:554/stream1
      - "ffmpeg:ShopCam#audio=aac"
    UtilityCam:
      - rtsp://user:pass@192.168.1.113:554/stream1
      - "ffmpeg:UtilityCam#audio=aac"

cameras:
  Cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: Cam1
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        labels:
          - person
    objects:
      track:
        - person
      mask: 0.136,0.166,0.211,0.93,0.444,0.802,0.45,0.571,0.36,0.162
  Cam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Cam2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: Cam2
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        labels:
          - person
    objects:
      track:
        - person
      mask: 0.662,0.191,0.544,0.677,0.591,0.854,0.812,0.881,0.837,0.237
  KitchenCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/KitchenCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: KitchenCam
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    #review:
    #  detections:
    #    labels:
    #      - person
    #      - cat
    #      - dog
  GarageCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/GarageCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: GarageCam
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    #review:
    #  detections:
    #    labels:
    #      - person
    #      - cat
    #      - dog
  DoorbellCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/DoorbellCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: DoorbellCam
    detect:
      enabled: true
      width: 1280  # Reduced from 2560
      height: 960  # Reduced from 1920
      fps: 5       # Reduced from 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        labels:
          - person
          - amazon
          - fedex
          - ups
          - package
    objects:
      track:
        - person
        #- cat
        #- dog
        - amazon
        - fedex
        - ups
        - package
      mask: 0.148,0.099,0.366,0.148,0.371,0.471,0,0.565,0,0.349
  BackPorchCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BackPorchCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
            - audio
    live:
      stream_name: BackPorchCam
    detect:
      enabled: true
      width: 1920  # Reduced from 3840
      height: 1080 # Reduced from 2160
      fps: 5       # Reduced from 10
    objects:
      track:
        - person
        #- cat
        - dog
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    audio:
      enabled: true
      listen:
        - bark
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        labels:
          #- person
          #- cat
          - dog
    zones:
      DogZone:
        coordinates: 0.171,0.25,0.221,0.858,0.597,0.84,0.529,0.273
        loitering_time: 10
        objects: dog
  BackyardCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BackyardCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: BackyardCam
    detect:
      enabled: true
      width: 1920  # Reduced from 3840
      height: 1080 # Reduced from 2160
      fps: 5       # Reduced from 10
    objects:
      track:
        #- person
        - cat
        - dog
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        labels:
          - person
          - cat
          - dog
  DrivewayCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/DrivewayCam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/DrivewayCamSub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: DrivewayCam
    detect:
      enabled: false
      width: 4608
      height: 1728
      fps: 10
    objects:
      track:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    review:
      detections:
        labels:
          - person
          - cat
          - dog
    # objects:
    #   track:
    #     - person
    #     - cat
    #     - amazon
    #     - fedex
    #     - ups
    #     - package
  BasementCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/BasementCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: BasementCam
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    #review:
    #  detections:
    #    labels:
    #      - person
    #      - cat
    #      - dog
  ShopCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ShopCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: ShopCam
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
   #review:
   #  detections:
   #    labels:
   #      - person
   #      - cat
   #      - dog
  SumpPumpCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/SumpPumpCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: SumpPumpCam
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    #review:
    #  detections:
    #    labels:
    #      - person
    #      - cat
    #      - dog
  UtilityCam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/UtilityCam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
            - record
    live:
      stream_name: UtilityCam
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: 'true'
    #review:
    #  detections:
    #    labels:
    #      - person
    #      - cat
    #      - dog
objects:
  track:
    - person
    - cat
    - dog
    - car
    #- bird
    #- airplane
    - bicycle
    #- motorcycle
    - bus
    - license_plate
    - amazon
    - fedex
    - ups
    - package

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: false
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 1
    objects:
      person: 1
      car: 1
      package: 1
      fedex: 1
      ups: 1
      amazon: 1

version: 0.15-1
camera_groups:
  Kids:
    order: 1
    icon: LuPersonStanding
    cameras:
      - Cam1
      - Cam2
  House:
    order: 2
    icon: LuArchiveRestore
    cameras:
      - GarageCam
      - KitchenCam
      - DoorbellCam
      - BackPorchCam
      #- BackyardCam
      - DrivewayCam
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
Unraid via Docker
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Tapo C110, Reolink RLC-820A's, Reolink Duo 2

### Any other information that may be helpful

I also have Cam1 and Cam2 in Home Assistant as WebRTC cards on my dashboard. I've noticed that if I'm listening to music on my phone, and pull up the Home Assistant app, it will mute my music and the audio of the two WebRTC camera cards will take over. I also have them muted within Home Assistant on the cards. I am connecting directly to the camera here, instead of using go2rtc from Frigate which might be an issue? However, I have tried removing these two cards and audio will still get disabled.

```
type: custom:webrtc-camera
url: rtsp://Cam1:Cam1@192.168.1.105:554/stream1
muted: true
ui: true
style: ".pictureinpicture {display: none}"
```
