### DISCUSSION TITLE
[Detector Support]: RX 5500XT

### DISCUSSION THREAD

**Discussion by fucksophie** [blakeblackshear/frigate#18709] [Detector Support]
### Describe the problem you are having

RX 5500XT doesn't work at all on frigate through ONNX nor through rocBLAS (on 0.15).
Override set to `9.0.0` freezes the whole system and restarts it, override set to `10.3.0` hangs forever.

### Version

(0.16.0-f141b58)

### Frigate config file

```yaml
mqtt:
  enabled: false
detectors:
  onnx:
    type: onnx

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_tensor: nchw
  input_pixel_format: bgr
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

tls:
  enabled: false
record:
  enabled: true
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
cameras:
  pagalms:
    enabled: true
    ffmpeg:
      inputs:
        - path: ..
          roles:
            - record
        - path: ..
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
    motion:
      threshold: 43
      contour_area: 41
      improve_contrast: true
  aizmugure:
    enabled: true
    ffmpeg:
      inputs:
        - path: ..
          roles:
            - record
        - path: ..
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
    motion:
      threshold: 55
      contour_area: 30
      improve_contrast: true
    objects:
      mask: 
        0.188,0.381,0.516,0.372,0.479,0.643,0.39,0.71,0.282,0.711,0.233,0.656,0.224,0.616,0.21,0.536,0.189,0.419
version: 0.16-0
notifications:
  enabled: 'true'
  email: ..
semantic_search:
  enabled: true
  reindex: false
  model_size: large
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: true
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    hostname: frigate
    privileged: true # this may not be necessary for all setups
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri/card1:/dev/dri/card1" 
    networks:
      - frigate
    restart: always
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3-rocm
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/../frigate/config:/config
      - /mnt/hdd/frigate_media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "gj912rjegmmm"
      HSA_OVERRIDE_GFX_VERSION: "10.3.0"
      TF_ROCM_USE_IMMEDIATE_MODE: "1"
  frigate-notify:
    container_name: frigate-notify
    hostname: frigate-notify
    networks:
      - frigate
    image: ghcr.io/0x2142/frigate-notify:latest
    environment:
      - TZ=Europe/RIga
    volumes:
      - /home/../frigate/notify_config.yml:/app/config.yml
    restart: always
    depends_on:
      - frigate

networks:
  frigate:
    driver: bridge
```

### Relevant Frigate log output

```shell
frigate         | 2025-06-13 18:48:16.662177285  [2025-06-13 18:48:16] detector.onnx                  INFO    : Starting detection process: 546
frigate         | 2025-06-13 18:48:16.662557852  [2025-06-13 18:48:16] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
frigate         | 2025-06-13 18:48:16.662748967  [2025-06-13 18:48:16] frigate.detectors.plugins.onnx INFO    : ONNX: loading /config/yolo_nas_s.onnx

frigate         | 2025-06-13 18:48:36.883195985  [2025-06-13 18:48:36] ffmpeg.pagalms.detect          ERROR   : amdgpu: amdgpu_cs_query_fence_status failed.
frigate         | 2025-06-13 18:48:36.883413761  [2025-06-13 18:48:36] ffmpeg.pagalms.detect          ERROR   : amdgpu: The CS has been rejected (-125), but the context isn't robust.
frigate         | 2025-06-13 18:48:36.883692854  [2025-06-13 18:48:36] ffmpeg.pagalms.detect          ERROR   : amdgpu: The process will be terminated.
frigate         | 2025-06-13 18:48:36.895942708  [2025-06-13 18:48:36] watchdog.aizmugure             ERROR   : Ffmpeg process crashed unexpectedly for aizmugure.
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

Irrelevant

### Any other information that may be helpful

All the issues/combinations I tried:
1. HFX_OVERRIDE set to 9.0.6, and frigate 0.16, ONNX detector. This leads to a system wide reboot.
2. HFX_OVERRIDE set to 9.0.0, and frigate 0.16, ONNX detector. This leads to the error showed before (the CS has been rejected). If TF_ROCM_USE_IMMEDIATE_MODE is unset, it also does a system wide reboot.
3. HFX_OVERRIDE set to 10.3.0, and frigate 0.15, ROCM detector. This leads to a OOM error.
4. HFX_OVERRIDE set to 10.3.0, and frigate 0.16, ONNX detector. Overflow error, `The agent attempted to access memory beyond the largest legal address. code: 0x29`.
