### DISCUSSION TITLE
[Config Support]: Events have no recorded video

### DISCUSSION THREAD

**Discussion by bulburDE** [blakeblackshear/frigate#18711] [Config Support]
### Describe the problem you are having

I have events that have no video footage. I first noticed it when I tried to play events from the home assistant frigate-card and for some events I got the error `Error starting stream, see logs for details (Server failure)`. I then looked it up in the frigate review section and I can see the even there. 
It has a timestamp of 17:31:16 and is 3s long according to the frigate card.

But when I click on it in the review overview section the video loads at 17:32:02.

And when I click on the event on the right sidebar the event before (05:28 / 17:28) gets highlighted, but the video starts playing at 17:32:02

I clicked on the upper one:
![image](https://github.com/user-attachments/assets/9c6f3793-0280-4dc7-91ff-e87082f458a5)

What bothers me is that that timerange where the event should be is empty in the timeline.
When I play back the available video the video before stops at 17:29:58 and the next one starts at 17:32:02.
![image](https://github.com/user-attachments/assets/84f1abae-ca8d-41e3-9f91-7885c821b3aa)

Another thing I noticed is that there is only video for motion (yellow lines), but not for alerts (red areas).

I am not sure if those are problems are bugs or configuration problems. Any help is appreciated.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.90.33

go2rtc:
  streams:
    carport: 
      http://192.168.90.100/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx
    gewaechshaus: 
      http://192.168.90.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx
    vorgarten: 
      http://192.168.90.105/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx
    doorbell: 
      http://192.168.90.108/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx
    emilia:
      - rtsp://192.168.90.104:8554/unicast
      - ffmpeg:emilia#audio=aac
    clara:
      - rtsp://homeassistant:xxxxxx@192.168.90.106:554/stream1

cameras:
  emilia:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/emilia
          input_args: preset-rtsp-restream
    record:
      enabled: false
    motion:
      enabled: false
      mask: 0,0.072,0,0,0.265,0,0.267,0.07
    detect:
      enabled: false
  clara:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/clara
          input_args: preset-rtsp-restream
    record:
      enabled: false
    motion:
      enabled: false
      mask: 0,0.081,0,0,0.365,0,0.365,0.084
    detect:
      enabled: false
  carport:
    ffmpeg:
      inputs:
        - path: 
            http://192.168.90.100/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxxx
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
    detect:
      width: 896
      height: 672
      fps: 5
      enabled: true
      max_disappeared: 25

    zones:
      einfahrt:
        coordinates: 0,213,0,672,896,672,896,313,896,38,468,68,333,109
        objects:
          - person

    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below
      filters:
        person:
            # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 3500
            # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 130000

    motion:
      mask: 0,0.918,0.439,0.92,0.439,1,0,1
  gewaechshaus:
    ffmpeg:
      inputs:
        - path: 
            http://192.168.90.101/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxxxx
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/gewaechshaus
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      mask: 0,0.121,0,0,0.472,0,0.468,0.108
    detect:
      width: 896
      height: 672
      fps: 5
      enabled: true
      max_disappeared: 25

  vorgarten:
    ffmpeg:
      inputs:
        - path: 
            http://192.168.90.105/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxxx
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/vorgarten
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      improve_contrast: true
      mask:
        - 0,0,0.438,0,0.44,0.037,0.297,0.047,0.156,0.345,0.09,0.446,0,0.567,0,0.755,0,0.766
        - 0.669,0,0.622,0,0.555,0,0.576,0.359,0.617,0.516,0.616,0.789,0.622,0.82,0.613,0.844,0.616,0.896,0.628,1,1,1,1,0,0.846,0
        - 0.233,0.804,0,0.788,0,1,0.249,1
        - 0.34,0.346,0.426,0.344,0.431,0.447,0.329,0.453
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person


    zones:
      einfahrt:
        coordinates: 501,24,280,54,153,102,137,250,503,201
        objects:
          - person
      haustuer:
        coordinates: 
          551,323,565,672,378,672,380,561,395,557,283,558,214,530,144,525,0,519,38,424,47,298,381,281,440,205,507,190
        objects:
          - person

    detect:
      width: 896
      height: 672
      fps: 5
      enabled: true
      max_disappeared: 25

  doorbell:
    ffmpeg:
      inputs:
        - path: 
            http://192.168.90.108/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxxx
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
    motion:
      improve_contrast: 'true'
      threshold: 30
      mask: 0,0,1,0,1,0.196,0,0.197
      contour_area: 10
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
            # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 2000
            # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 130000
            # Optional: minimum score for the object to initiate tracking (default: shown below)
            #min_score: 0.5
            # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
            #threshold: 0.7
            # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
            # Checks based on the bottom center of the bounding box of the object
            #mask: 491,274,1419,138,1455,549,469,686
    detect:
      width: 896
      height: 672
      fps: 5
      enabled: true
      max_disappeared: 25

    zones: {}
record:
  enabled: true
  expire_interval: 2880
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 14
    pre_capture: 10
    post_capture: 10
  detections:
    retain:
      days: 14
    pre_capture: 10
    post_capture: 10
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 30

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 3000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

ffmpeg:
  hwaccel_args: preset-vaapi
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.15-1
```

### Relevant Frigate log output

```shell
nothing relevant
```

### Relevant go2rtc log output

```shell
nothing relevant
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    restart: always
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:0.15.1
    #cap_add:
      #- CAP_PERFMON
    shm_size: '200m'
    volumes:
      #- /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      # - /mnt/user/Frigate:/media/frigate
      - ./db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
      - '1984:1984' # go2rtc dashboard
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      LIBVA_DRIVER_NAME: radeonsi
```

### Object Detector

Coral

**Comment by NickM-27** [comment]
we will need to see logs after trying to playback, you should also try to view the event in the explore page and see what happens.

**Reply by bulburDE** [reply]
When I click on it in the explore page the details and snapshot page looks fine. The object lifecycle page has no images (events with working video have them). The video does not load. This produces the following error in the logs:

`No recordings found for carport during the requested time range`

![image](https://github.com/user-attachments/assets/fdb93d9c-4d93-496b-8aef-68f87c634854)

I searched my frigate logs and there a lot of those errors:
![image](https://github.com/user-attachments/assets/3d1a6d31-d551-4119-a87d-53bd1821c308)
They have always been there so I didn't associate them with this problem. But I will do some more research if can get rid of them. 

Also this:
![image](https://github.com/user-attachments/assets/6b4a3c1a-ffde-4f09-a9bb-b3cebdf76195)

and this looks odd:
![image](https://github.com/user-attachments/assets/8baf7178-6005-4679-bafd-6ff7daf6f1da)


[frigate-logs.txt](https://github.com/user-attachments/files/20733166/frigate-logs.txt)

**Reply by NickM-27** [reply]
yes, this indicates a lot of problems with the recordings

**Comment by bulburDE** [comment]
Thanks to the advice from @NickM-27 I rechecked my configuration to try to get rid of the error messages. I don't know what of the single changes were responsible but after applying best practices from the documentation the errors are gone. And so far all events I have checked have videos now.

This is my working config for multiple reolink cameras (RLC-520A, RLC-410-5MP, PoE Doorbell):

```
go2rtc:
  streams:
    carport: 
      ffmpeg:http://192.168.90.100/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx#video=copy#audio=copy#audio=opus
    carport_sub: 
      ffmpeg:http://192.168.90.100/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx

  carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/carport_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/carport
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
```
