### DISCUSSION TITLE
[Support]: Frigate leaves clips folder in local media/frigate during shutdown when shut down using hyper-v

### DISCUSSION THREAD

**Discussion by mad-tunes** [blakeblackshear/frigate#18718] [General Support]
### Describe the problem you are having

I run the Frigate add-on on HAOS in a Hyper-V VM. I have HA connect a Frigate media share for storing Frigates footage on rather than it being stored within the VM.
If I shut down the VM using the host Hyper-V then HA always has an issue mounting the share when it next boots, reporting that the local folder isn't empty.
It's right, it isn't..

This leads to Frigate storing its clips, exports and recordings folders within the VM from that point onwards.. Unless I stop frigate, remove any files/folders in the Frigate media share (that are within the VM), remount the share and start Frigate.

The problem seems to be caused as I shut down the VM, and only when done from Hyper-V. It's fine if I use HAs own shutdown or restart options.

I've found that if I:

Have HA and the Frigate addon running
Set the addon to not start at boot
Shut down the HA VM using Hyper-Vs shutdown button
Start the HA VM and let it boot
..then I find one folder in media/frigate, clips. It's not been created as the addon starts because it was set to not start on its own at boot, so must be happening during shutdown.
Inside the clips folder is preview_restart_cache, and inside that are a bunch of .webp files that have creation times spanning approx 30 minutes (which seems a bit strange, there hasn't been that amount of time since I hit the shutdown button and the clips folder was created).

When making changes I often shut down HA and take a snapshot in Hyper-V first, so any change can very easily be rolled back.
To avoid the clips folder being created locally I have to either shut down the Frigate addon and then the VM, or use HAs own shutdown option.

Frigate's the only thing stopping me just clicking Hyper-Vs shutdown button, and it'd be very nice to be able to shut it down using Hyper-V, take a snapshot and then start the VM back up without any any other steps.

What are these files for, and is there any way to the behaviour please?

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Brave

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.5.11
  user: mqtt
  password: mqtt

detectors:
  cpu0:
    type: cpu
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu

go2rtc:
  ffmpeg:
    timestamp: -vf 
      drawtext=text='%{localtime}':x=5:y=5:fontsize=h/25:fontcolor=black:shadowx=2:shadowy=2
  streams:
    Garden: ffmpeg:http://192.168.5.57:8080#video=h264#hardware#raw=timestamp
    Front: ffmpeg:http://192.168.5.59:8080#video=h264#hardware#raw=timestamp

cameras:
  Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front
          roles:
            - detect
            - record
    review:
      alerts:
        required_zones: Front_grass
      detections:
        required_zones: Front_grass
    detect:
      enabled: true
      width: 320
      height: 240
      fps: 5
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - bicycle
        - sports ball
    motion:
      enabled: true
      threshold: 35
      contour_area: 10
      improve_contrast: false
      mask:
        - 0,0,0,0.05,0.35,0.05,0.35,0
        - 0.002,0.258,0.081,0.274,0.128,0.324,0.161,0.415,0.207,0.466,0.238,0.633,0.182,0.637,0,0.745
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: false
      retain:
        default: 14
        mode: active_objects
        objects:
          person: 30
      quality: 100
    zones:
      Front_grass:
        coordinates: 1,1,0,1,0,0.751,0.184,0.642,0.578,0.592,0.873,0.567,1,0.607
        loitering_time: 0
        objects:
          - person
          - bird
          - cat
          - dog
          - bicycle
          - sports ball
        inertia: 3

  Garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 320
      height: 240
      fps: 5
    objects:
      track:
        - person
        - bird
        - cat
    motion:
      enabled: true
      threshold: 30
      contour_area: 10
      improve_contrast: false
      mask:
        - 0,0,0,0.05,0.35,0.05,0.35,0
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: false
      retain:
        default: 14
        mode: active_objects
        objects:
          person: 30
      quality: 100

timestamp_style:
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 1
  effect: shadow

version: 0.15-1
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
-
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

esp32cam
