### DISCUSSION TITLE
History will not playback but only sometimes

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#18735] [Ask A Question]
Hey guys any idea why when looking at the history for my cameras it just sits there and spins and will not load. Scrubbing seems to work but as soon as I let go it just spins forever. I remember kind of having this problem before but it went away and now it has come back. Any ideas what I can do to see what the issue is?

Config
```
mqtt:
  enabled: false

auth:
  enabled: false

tls:
  enabled: false

record:
  enabled: true
  retain:
    days: 10
    mode: all

ffmpeg:
#  hwaccel_args: preset-nvidia
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  enabled: false

motion:
  enabled: true

detect:
  enabled: false

#detectors:
#  NVIDIA GeForce GTX 1080:
#    type: tensorrt
#    device: 0

#model:
#  path: /config/model_cache/tensorrt/yolov7-320.trt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 320
#  height: 320

go2rtc:
  rtsp:
    username: '{FRIGATE_HA_USER}'
    password: '{FRIGATE_HA_PASS}'
  streams:
    Front_Yard: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.212/Preview_01_main
    Front_Yard_Sub: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.212/Preview_01_sub
    Driveway: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.213/Preview_01_main
    Driveway_Sub: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.213/Preview_01_sub
    Garage: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.210/Preview_01_main
    Garage_Sub: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.210/Preview_01_sub
    Front_Door: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.217/Preview_01_main
    Front_Door_Sub: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.217/Preview_01_sub
    Ripleys_Room: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.211/Preview_01_main
    Ripleys_Room_Sub: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.211/Preview_01_sub
    Back_Yard: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.218/Preview_01_main
    Back_Yard_Sub: rtsp://frigate:{FRIGATE_RTSP_PASS}@192.168.86.218/Preview_01_sub


cameras:

  Front_Yard:
  ###################################
  ## Reolink 8MP/4K, E1 Outdoor Pro
  ## Record Stream (Clear)  3840*2160 H.265  25FPS  Bitrate 8192 Kbps I-Frame 1
  ## Detect Stream (Fluent) 640*360   H.264  4FPS   Bitrate 512  Kbps I-Frame 1
  ################################################################################
  ## Detect: Must be a proper 16:9 ratio, 656*369

    ui:
      order: 1

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Yard
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Front_Yard_Sub
          roles:
            - detect

    motion:
      mask:
        - 0.634,0.009,0.634,0.079,0.999,0.076,0.996,0.01
        - 0.325,0.324,0.291,0.271,0.272,0.207,0.276,0.136,0.271,0.053,0.283,0,0.355,0,0.416,0,0.437,0.048,0.445,0.175,0.425,0.275,0.376,0.319
        - 0.785,0.374,0.746,0.347,0.723,0.318,0.709,0.255,0.709,0.175,0.734,0.098,0.763,0.041,0.783,0,0.821,0.011,0.843,0.085,0.861,0.161,0.878,0.246,0.875,0.315,0.858,0.38,0.832,0.372
        - 0.166,0.162,0.151,0.162,0.136,0.133,0.137,0,0.18,0,0.21,0,0.215,0.053,0.215,0.094,0.214,0.139,0.192,0.157
        - 0.718,0.206,0.725,0.233,0.745,0.233,0.745,0.206
        - 0.001,0.12,0.001,0,0.533,0.001,0.505,0.032,0.374,0.035,0.301,0.037,0.241,0.04,0.239,0.057,0.198,0.049,0.126,0.058,0.097,0.095,0.08,0.076,0.015,0.102
      threshold: 39
      contour_area: 10
      improve_contrast: 'true'

  Driveway:
  ###################################
  ## Reolink 8MP/4K, E1 Outdoor Pro
  ## Record Stream (Clear)  3840*2160  H.265  25FPS  Bitrate 8192 Kbps I-Frame 1
  ## Detect Stream (Fluent) 640*360    H.264  4FPS   Bitrate 512  Kbps I-Frame 1
  ################################################################################
  ## Detect: Must be a proper 16:9 ratio, 656*369

    ui:
      order: 2

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Driveway_Sub
          roles:
            - detect

    motion:
      mask:
        - 0.634,0.023,0.632,0.073,0.988,0.071,0.988,0.022
        - 0.851,0.144,0.887,0.155,0.917,0.116,0.923,0.059,0.929,0,0.871,0.003,0.847,0.086
        - 0.174,0.804,0.211,0.814,0.215,0.857,0.209,0.928,0.187,0.924,0.156,0.871


  Ripleys_Room:
  ## Reolink E1 Pro, 4MP/2K
  ## Record Stream (Clear)  2560*1440  H.264  25FPS  Bitrate 5160  I-Frame 1x
  ## Detect Stream (Fluent) 640*360    H.264  4FPS   BitRate 512   I-Frame 1x
  ######################################################################
  ## Detect: Must be a proper 16:9 ratio, 656*369
    ui:
      order: 3

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Ripleys_Room
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Ripleys_Room_Sub
          roles:
            - detect

    motion:
      mask: 0.642,0,0.644,0.08,1,0.084,1,0


  Back_Yard:
  ## Reolink 8MP/4K, E1 Outdoor Pro
  ## Record Stream (Clear)  3840*2160  H.265  25FPS  Bitrate 8192 Kbps I-Frame 1
  ## Detect Stream (Fluent) 640*360    H.264  4FPS   Bitrate 512  Kbps I-Frame 1
  ########################################################################
  ## Detect: Must be a proper 16:9 ratio, 656*369

    ui:
      order: 4

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Yard
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Back_Yard_Sub
          roles:
            - detect

    motion:
      mask: 
        0,0.383,0.205,0.309,0.426,0.211,0.502,0.2,0.561,0.192,0.61,0.188,0.669,0.17,0.726,0.14,0.773,0.08,1,0.088,1,0,0.871,0,0.521,0,0.287,0,0,0,0,0.159


  Front_Door:
  ## Reolink, Wifi Doorbell, 5MP/2K+
  ## Record Stream (Clear)  2560*1920  H.264 20FPS  Bitrate 6144 Kbps I-Frame 1
  ## Detect Stream (Fluent) 640*480    H.264 4FPS   Bitrate 512  Kbps I-Frame 1
  ###############################################################################

    ui:
      order: 5

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Front_Door_Sub
          roles:
            - detect

    motion:
      mask:
        - 0.63,0.009,0.63,0.058,0.992,0.059,0.993,0.009
        - 0.51,0.516,0.47,0.494,0.475,0.429,0.486,0.398,0.516,0.417,0.532,0.458,0.537,0.504
        - 0.585,0.505,0.577,0.488,0.587,0.465,0.609,0.48,0.612,0.501,0.597,0.522
        - 0.006,0.089,0.055,0.123,0.119,0.193,0.156,0.247,0.206,0.313,0.237,0.412,0.264,0.409,0.264,0.453,0.36,0.456,0.386,0.46,0.413,0.461,0.446,0.465,0.54,0.483,0.569,0.487,0.617,0.494,0.667,0.493,0.691,0.483,0.724,0.445,0.7,0.445,0.689,0.41,0.694,0.381,0.72,0.369,0.719,0.312,0.759,0.313,0.726,0.094,0.706,0,0.223,0,0.006,0.006
  Garage:
  ## Reolink, E1 Zoom, 5MP/2K+
  ## Record Stream (Clear)  2560*1920  H.264  20FPS  Bitrate 5120 Kbps I-Frame 1
  ## Detect Stream (Fluent) 640*480    H.264  4FPS   Bitrate 512  Kbps I-Frame 1
  ################################################################################

    ui:
      order: 6

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record

        - path: rtsp://127.0.0.1:8554/Garage_Sub
          roles:
            - detect

    motion:
      mask:
        - 0.642,0.009,0.642,0.06,0.988,0.061,0.984,0.01
        - 0.351,0.116,0.836,0.131,0.816,0,0.377,0

version: 0.15-1
```
