### DISCUSSION TITLE
[Config Support]: live

### DISCUSSION THREAD

**Discussion by ops244** [blakeblackshear/frigate#18734] [Config Support] [answered]
### Describe the problem you are having

hi, can you tell me how to make it give the main stream live instead of 5 fps in this configuration?
(without go2rtc)?

### Version

0.16.0-beta3

### Frigate config file

```yaml
cameras:
  camera:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.1.168/1
          input_args: ""
          roles:
            - detect
        - path: rtsp://******:******@192.168.1.168/0
          input_args: ""
          roles:
            - record

      hwaccel_args: preset-vaapi

    motion:
      threshold: 30
      lightning_threshold: 1.0
      contour_area: 10
      improve_contrast: true

      mask: 0.045,0.057,0.309,0.056,0.309,0.1,0.045,0.103
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


detect:
  width: 1280
  height: 720
  fps: 5
  min_initialized: 1
  max_disappeared: 25
```

### Relevant Frigate log output

```shell
There are no errors
```

### Relevant go2rtc log output

```shell
There are no errors
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
--------
```

### Object Detector

OpenVino
