### DISCUSSION TITLE
[Detector Support]: model download

### DISCUSSION THREAD

**Discussion by ops244** [blakeblackshear/frigate#18737] [Detector Support] [answered]
### Describe the problem you are having

hi, why doesn't beta 3 upload models to the model_cache folder, as it should be?
the openvino detector

### Version

0.16.0-beta3

### Frigate config file

```yaml
go2rtc:
  streams:
    camera:
      - rtsp://********@192.168.1.168/0

cameras:
  camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://*********@192.168.1.168/1
          roles:
            - detect

      hwaccel_args: preset-vaapi

    motion:
      threshold: 30
      lightning_threshold: 1.0
      contour_area: 10
      improve_contrast: true

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


detect:
  width: 1280
  height: 720
  fps: 5
  min_initialized: 1
  max_disappeared: 25
```

### docker-compose file or Docker CLI command

```yaml
------
```

### Relevant Frigate log output

```shell
-----
```

### Install method

Home Assistant Add-on

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

-----
