### DISCUSSION TITLE
[Bug]:  Safari Browser - "Invalid time" and "Label" UI errors

### DISCUSSION THREAD

**Discussion by streetcap** [blakeblackshear/frigate#18746] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

"Invalid time" is displayed when I open Frigate in Safari.  This happen on both desktop and mobile.  It does work if I click the refresh button.  If I close Safari, then re-open it, the behavior will repeat.  It appears to work correctly in Chrome.  I added the following to my config, but it did not resolve the problem:

# Optional
ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/New_York
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: "%Y/%m/%d %H:%M"

### Steps to reproduce

1.
2.
3.
...

### Version

0.16.0 Beta 3

### In which browser(s) are you experiencing the issue with?

Safari 18.5 (both Mac and IOS)

### Frigate config file

```yaml
mqtt:
  enabled: false

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  retain:
    default: 366

# Optional: Configuration for semantic search capability
semantic_search:
  # Optional: Enable semantic search (default: shown below)
  enabled: true
  # Optional: Re-index embeddings database from historical tracked objects (default: shown below)
  reindex: false

birdseye:
  enabled: true
  quality: 8
  mode: motion

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  # width: 1280
  # height: 720
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    #max_frames:
      # Optional: Default for all object types (default: not set, track forever)
     #default: 3000
      # Optional: Object specific values
      #objects:
        #person: 1000

record:
  enabled: true
  retain:
    days: 45
    mode: all
  alerts:
    retain:
      days: 366
  detections:
    retain:
      days: 366
tls:
  enabled: false


objects:
  track:
    - person
    - dog
    - car
    - motorcycle
    - bus
    - bicycle
    - bear
  filters:
    person:
      threshold: 0.75
      min_score: 0.70
    dog:
      threshold: 0.75
      min_score: 0.70

go2rtc:
  #webrtc:
    #listen: ":8555"
    #candidates:
      #- 192.168.0.241:8555
      #- stun:8555
  streams:
    01_Doorbell:
      - rtsp://
      - ffmpeg:01_Doorbell#audio=opus
    02_FrontDoor:
      - rtsp://
    03_Parking_PTZ:
      - rtsp://
    04_Incoming_PTZ:
      - rtsp://
    05_Driveway_Path:
      - rtsp://
    06_Parking:
      - rtsp://
    07_LPR_House:
      - rtsp://
    08_LPR_Street:
      - rtsp://
    09_DeckSteps:
      - rtsp://
    10_Playground1:
      - rtsp://
    11_Playground2:
      - rtsp://
    12_Playground3:
      - rtsp://
    13_Front_Office:
      - rtsp://
    14_Street_Thermal:
      - rtsp://
    15_FamilyRoom:
      - rtsp://
    16_Den:
      - rtsp://
    #17_Bar:
      #- ffmpeg:rtsp://
    18_Office:
      - rtsp://
    19_Garage:
      - rtsp://
    20_MachineRoom:
      - rtsp://
    01_Doorbell_sub:
      - rtsp://
      #- "ffmpeg:01_Doorbell#audio=opus"
    02_FrontDoor_sub:
      - rtsp://
    03_Parking_PTZ_sub:
      - rtsp://
    04_Incoming_PTZ_sub:
      - rtsp://
    05_Driveway_Path_sub:
      - rtsp://
    06_Parking_sub:
      - rtsp://
    07_LPR_House_sub:
      - rtsp://
    08_LPR_Street_sub:
      - rtsp://
    09_DeckSteps_sub:
      - rtsp://
    10_Playground1_sub:
      - rtsp://
    11_Playground2_sub:
      - rtsp://
    12_Playground3_sub:
      - rtsp://
    13_Front_Office_sub:
      - rtsp://
    14_Street_Thermal_sub:
      - rtsp://
    15_FamilyRoom_sub:
      - rtsp://
    16_Den_sub:
      - rtsp://
    #17_Bar_sub:
      #- rtsp://
    18_Office_sub:
      - rtsp://
    19_Garage_sub:
      - rtsp://
    20_MachineRoom_sub:
      - rtsp://

cameras:
  01_Doorbell: # <------ Amcrest AD410 4MP Doorbell Pro
    ui:
      order: 3
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/01_Doorbell
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/01_Doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
      mask: 0.002,0.004,0,0.347,1,0.345,0.997,0.003
    motion:
      mask: 0.005,0.003,0.002,0.343,0.998,0.341,0.996,0.005
    lpr:
      enabled: false

  02_FrontDoor: # <------ Axis M3027 using Channel 8 of 8
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/02_FrontDoor
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/02_FrontDoor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
    lpr:
      enabled: false


  03_Parking_PTZ: # <------ Sunba Performance Series P636 V2 36x
    ui:
      order: 18
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/03_Parking_PTZ
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/03_Parking_PTZ_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 352 # <---- update for your camera's resolution
      height: 288 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
    onvif:
      # Required: host of the camera being connected to.
      host: 192.168.0.197
      # Optional: ONVIF port for device (default: shown below).
      port: 80
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user: admin
      # Optional: password for login.
      password: Harmony16037!
    lpr:
      enabled: false

  04_Incoming_PTZ: # <------ Sunba Performance Series P636 V2 36x
    ui:
      order: 18
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/04_Incoming_PTZ
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/04_Incoming_PTZ_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 352 # <---- update for your camera's resolution
      height: 288 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
    onvif:
      # Required: host of the camera being connected to.
      host: 
      # Optional: ONVIF port for device (default: shown below).
      port: 
      # Optional: username for login.
      # NOTE: Some devices require admin to access ONVIF.
      user:
      # Optional: password for login.
      password:
    lpr:
      enabled: false

  05_Driveway_Path: # <------ Axis M3027 using Channel 2 of 8
    ui:
      order: 20
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/05_Driveway_Path
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/05_Driveway_Path_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 
        0,0.468,0.24,0.485,0.439,0.432,0.606,0.356,0.703,0.308,0.838,0.261,0.996,0.253,0.999,0.003,0.003,0.003
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 240 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
      mask: 0.001,0.456,0.248,0.476,0.842,0.253,0.996,0.244,0.999,0.005,0.002,0.002
    lpr:
      enabled: false

  06_Parking: # <------ Axis M3027 using Channel 2 of 8
    ui:
      order: 19
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/06_Parking
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/06_Parking_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 640,0,640,240,463,240,483,0
        - 0,0,0,240,53,240,74,0
        - 0,0,640,0,640,98,0,98
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 240 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.60
          min_score: 0.55
        dog:
          threshold: 0.60
          min_score: 0.55
        car:
          threshold: 0.60
          min_score: 0.55
        motorcycle:
          threshold: 0.60
          min_score: 0.55
        bus:
          threshold: 0.60
          min_score: 0.55
        bicycle:
          threshold: 0.60
          min_score: 0.55
        bear:
          threshold: 0.60
          min_score: 0.55
      mask: 0.001,0.003,0.088,0.36,0.763,0.351,0.836,0.01
    lpr:
      enabled: false

  07_LPR_House: # <------ Geovision GV-IP LPR CAM 5R
    ui:
      order: 30
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/07_LPR_House
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/07_LPR_House_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 1,0,1,0.41,0,0.456,0,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 512 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.60
          min_score: 0.55
        dog:
          threshold: 0.60
          min_score: 0.55
        car:
          threshold: 0.60
          min_score: 0.55
        motorcycle:
          threshold: 0.60
          min_score: 0.55
        bus:
          threshold: 0.60
          min_score: 0.55
        bicycle:
          threshold: 0.60
          min_score: 0.55
        bear:
          threshold: 0.60
          min_score: 0.55
      mask: 0,0.002,0,0.455,1,0.404,0.998,0.002
    lpr:
      enabled: true

  08_LPR_Street: # <------ Amcrest UltraHD 5MP Bullet
    enabled: true
    ui:
      order: 30
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/08_LPR_Street
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/08_LPR_Street_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 1,1,1,0.721,0,0.827,0,1
        - 1,0,1,0.384,0,0.325,0,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.60
          min_score: 0.55
        dog:
          threshold: 0.60
          min_score: 0.55
        car:
          threshold: 0.60
          min_score: 0.55
        motorcycle:
          threshold: 0.60
          min_score: 0.55
        bus:
          threshold: 0.60
          min_score: 0.55
        bicycle:
          threshold: 0.60
          min_score: 0.55
        bear:
          threshold: 0.60
          min_score: 0.55

      mask:
        - 0,0.003,0.001,0.317,0.998,0.38,0.998,0.006
        - 0.001,0.825,0.004,0.996,0.997,0.99,0.997,0.726
    zones:
      Driveway:
        coordinates: 1,0.552,0.591,0.542,0.005,0.526,0.002,0.818,0.997,0.715
        loitering_time: 0
        inertia: 3
      Street:
        coordinates: 1,0.549,0,0.523,0,0.338,0.111,0.339,0.243,0.352,1,0.385
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Driveway
      detections:
        required_zones:
          - Street
          - Driveway
    lpr:
      enabled: true

  09_DeckSteps: # <------ Axis M3027 using Channel 2 of 8
    ui:
      order: 34
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/09_DeckSteps
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/09_DeckSteps_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 240 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70

      mask: 0.633,0.009,0.734,0.594,0.997,0.633,0.998,0.004
    motion:
      mask: 0.635,0,0.852,1,1,1,0.996,0
    lpr:
      enabled: false

  10_Playground1: # <------ Axis M3027 using Channel 2 of 8
    ui:
      order: 35
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/10_Playground1
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/10_Playground1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 240 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
      mask: 
        0,0,0,0.708,0.337,0.737,0.583,0.576,0.664,0.511,0.688,0.409,0.77,0.38,0.839,0.398,0.982,0.336,1,0
    motion:
      mask: 
        0,0,0,0.701,0.336,0.735,0.663,0.511,0.69,0.412,0.772,0.383,0.841,0.398,0.96,0.334,0.992,0
    lpr:
      enabled: false

  11_Playground2: # <------ Axis M3027 using Channel 2 of 8
    ui:
      order: 40
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/11_Playground2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/11_Playground2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70

      mask: 0.003,0.003,0.005,0.312,0.562,0.171,0.937,0.206,0.997,0.119,0.999,0.003
    motion:
      mask: 
        0.002,0.001,0.003,0.316,0.563,0.169,0.693,0.194,0.936,0.208,0.998,0.12,0.998,0.001
    lpr:
      enabled: false

  12_Playground3: # <------ Axis M3027 using Channel 2 of 8
    ui:
      order: 45
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/12_Playground3
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/12_Playground3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - bear
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70

      mask:
        - 0.17,0.352,0.213,0.415,0.302,0.395,0.278,0.32
        - 0.036,0.403,0.071,0.472,0.147,0.439,0.117,0.373
        - 0,0.002,0.003,0.409,0.502,0.259,0.513,0.2,0.609,0.204,0.622,0.086,0.328,0.084,0.164,0.002
    motion:
      mask:
        - 0.169,0.355,0.211,0.417,0.302,0.395,0.276,0.319
        - 0.036,0.401,0.111,0.376,0.149,0.443,0.074,0.474
    lpr:
      enabled: false

  13_Front_Office: # <------ Axis M3027 using Channel 7 of 8
    ui:
      order: 48
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/13_Front_Office
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/13_Front_Office_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70
    lpr:
      enabled: false

  14_Street_Thermal: # <------ Axis Q1541-E Thermal
    enabled: true
    ui:
      order: 50
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/14_Street_Thermal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/14_Street_Thermal_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 640,134,640,0,0,0,0,105
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.55
          min_score: 0.50
        dog:
          threshold: 0.55
          min_score: 0.50
        car:
          threshold: 0.55
          min_score: 0.50
        motorcycle:
          threshold: 0.55
          min_score: 0.50
        bus:
          threshold: 0.55
          min_score: 0.50
        bicycle:
          threshold: 0.55
          min_score: 0.50
        bear:
          threshold: 0.55
          min_score: 0.50

      mask:
        - 0.001,0.003,0.002,0.216,1,0.275,0.999,0.003
        - 0.002,0.356,0.481,0.405,0.626,0.482,0.534,0.538,0.419,0.529,0.208,0.52,0.1,0.507,0.005,0.493
    zones:
      Street:
        coordinates: 0.999,0.472,0.005,0.354,0.004,0.222,0.999,0.283
        loitering_time: 0
      Property:
        coordinates: 
          0.524,0.419,0.641,0.434,0.999,0.479,1,1,0.001,0.996,0.007,0.501,0.532,0.543,0.634,0.483
        loitering_time: 0
    review:
      alerts:
        required_zones: Property
      detections:
        required_zones:
          - Street
          - Property
    lpr:
      enabled: false

  15_FamilyRoom: # <------ Axis M3026
    ui:
      order: 55
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/15_FamilyRoom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/15_FamilyRoom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.70
          min_score: 0.65
        dog:
          threshold: 0.70
          min_score: 0.65

    zones:
      Indoor_Zone:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
      Outdoor_Zone:
        coordinates: 0.182,0.075,0.208,0.225,0.036,0.309,0,0.171
        loitering_time: 0
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: Outdoor_Zone
      detections:
        required_zones:
          - Indoor_Zone
          - Outdoor_Zone
    lpr:
      enabled: false

  16_Den: # <------ Axis M3026
    ui:
      order: 60
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/16_Den
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/16_Den_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.70
          min_score: 0.65
        dog:
          threshold: 0.70
          min_score: 0.65


    zones:
      Indoor:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
      Outdoor:
        coordinates: 0.915,0.515,0.938,0.846,0.979,0.929,1,0.891,1,0.505
        loitering_time: 0
    review:
      detections:
        required_zones:
          - Indoor
          - Outdoor
      alerts:
        required_zones: Outdoor
    lpr:
      enabled: false

  17_Bar: # <------ Hikvision DS-2CD2532F-IS
    ui:
      order: 95
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 6
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.75
          min_score: 0.70
        dog:
          threshold: 0.75
          min_score: 0.70


    zones:
      Indoor:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
      Outdoor:
        coordinates: 0.669,0.003,0.67,0.07,0.868,0.096,0.86,0
        loitering_time: 0
    review:
      detections:
        required_zones:
          - Indoor
          - Outdoor
      alerts:
        required_zones: Outdoor
    lpr:
      enabled: false

  18_Office: # <------ Hikvision DS-2CD2442FWD-IW
    ui:
      order: 95
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/18_Office
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/18_Office_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0.784,0.61,0.775,0.41,0.636,0.45,0.648,0.631
        - 0,0,0,1,0.28,1,0.298,0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.65
          min_score: 0.60
        dog:
          threshold: 0.65
          min_score: 0.60


    zones:
      Indoor:
        coordinates: 0,0,1,0,1,1,0,1
        loitering_time: 0
      Outdoor:
        coordinates: 0.863,0,0.868,1,1,1,1,0
        loitering_time: 0
    review:
      detections:
        required_zones:
          - Indoor
          - Outdoor
      alerts:
        required_zones: Outdoor
    lpr:
      enabled: false

  19_Garage: # <------ Hikvision DS-2CD2442FWD-IW
    ui:
      order: 95
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/19_Garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/19_Garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - bicycle
        - bear
      filters:
        person:
          threshold: 0.65
          min_score: 0.60
        dog:
          threshold: 0.65
          min_score: 0.60
        car:
          threshold: 0.65
          min_score: 0.60
        motorcycle:
          threshold: 0.65
          min_score: 0.60
        bus:
          threshold: 0.65
          min_score: 0.60
        bicycle:
          threshold: 0.65
          min_score: 0.60
        bear:
          threshold: 0.65
          min_score: 0.60
    lpr:
      enabled: false

  20_MachineRoom: # <------ Amcrest UltraHD 5MP Bullet
    enabled: true
    ui:
      order: 100
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/20_MachineRoom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/20_MachineRoom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.65
          min_score: 0.60
        dog:
          threshold: 0.70
          min_score: 0.65
      mask:
        - 0.619,0,0.588,0.368,0.597,0.997,0.999,0.998,0.999,0.004
        - 0,0.003,0.004,0.772,0.153,0.691,0.292,0.243,0.246,0.005
    lpr:
      enabled: false

# Optional
ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: America/New_York
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: 24hour
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: '%Y/%m/%d %H:%M'

camera_groups:
  Driveway_Alert:
    order: 1
    icon: LuCar
    cameras:
      - 01_Doorbell
      - 02_FrontDoor
      - 03_Parking_PTZ
      - 04_Incoming_PTZ
      - 05_Driveway_Path
      - 06_Parking
      - 07_LPR_House
      - 08_LPR_Street
      - 19_Garage
      - 14_Street_Thermal
      - 13_Front_Office
  Playground:
    order: 2
    icon: LuTreePine
    cameras:
      - 10_Playground1
      - 09_DeckSteps
      - 11_Playground2
      - 12_Playground3
      - 04_Incoming_PTZ
  Indoors:
    order: 3
    icon: LuArmchair
    cameras:
      - birdseye
      - 15_FamilyRoom
      - 16_Den
      - 17_Bar
      - 18_Office
      - 19_Garage
      - 20_MachineRoom
  LPRs:
    order: 4
    icon: LuShieldAlert
    cameras:
      - 07_LPR_House
      - 08_LPR_Street
      - 14_Street_Thermal
  Birdseye:
    order: 5
    icon: LuBird
    cameras: birdseye


face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: false
version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-rocm
    shm_size: "16384mb"   # Having it this large might be unnecessary.  I increased it from 1024 due to errors, but the dev build above is supposed to fix it.  Using the dev build to attempt to fix the "Unable to keep up with recording segments in cache" errorscausing frigate to crash.
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume2/Frigate/config:/config
      - /volume2/Frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5033:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: 19541954
    mem_swappiness: 0 # Added these 6 lines due to crashes caused by log error that said Unable to keep up with recording segments in cache
    memswap_limit: "16384mb"
    deploy:
      resources:
        limits:
          memory: "16384mb"
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Various

### Screenshots of the Frigate UI's System metrics pages

![CleanShot 2025-06-16 at 09 26 46@2x](https://github.com/user-attachments/assets/f928c3ac-ca18-49f6-a637-56f5a3d5ca13)

![CleanShot 2025-06-16 at 09 25 59@2x](https://github.com/user-attachments/assets/f2a56201-2667-43b1-a37d-699a583ace2e)

![CleanShot 2025-06-16 at 09 26 23@2x](https://github.com/user-attachments/assets/6e255aec-76c2-4863-944c-bb187a4706a8)

### Any other information that may be helpful

This is installed on a Synology
