### DISCUSSION TITLE
[Support]: go2rtc cpu usage spikes after some time

### DISCUSSION THREAD

**Discussion by tlanfer** [blakeblackshear/frigate#18749] [Camera Support] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I have four cameras in my setup. One of them is an esphome based camera, which i send through go2rtc via ffmpeg, which transcodes it to h264. Unfortunately i cant use hardware acceleration, because the HP microserver gen8 i am using does not allow me to access the iGPU of the Xeon, and the PCIe slot is used an nvme drive. Still, CPU usage is quite low at around 20% most of the time. Everything works fine.

At some point, the CPU usage spikes up though, and stays high until i restart frigate:

![image](https://github.com/user-attachments/assets/4bdf4e3d-e418-45b8-a5ce-e57cb4888a98)

This is the CPU usage of the whole server, and i dont think i need to point out where it spikes up. When i restart frigate, it immediately drops down to normal levels. When i check `htop` i can see that it is a go2rtc process that runs at ~400% cpu usage. 

There are a few remnants in the configuration from me trying to get hardware acceleration working, before i realized i'm out of luck on the microserver gen8.
I should probably remove the `#hardware`, but go2rtc gracefully falls back to not running everything on CPU, so it should be fine.

As you can see theres a long list of input_args i give to ffmpeg, because the esphome camera stream is not exactly the most stable. Chances are, the ffmpeg stream of go2rtc also needs those settings, but i'm not sure.

Either way, the CPU usage spiking up until restarting frigate is definitely not right. 
I wish i could give you more info. I couldnt find anyone having similar issues so far.

### Steps to reproduce

1. Get an esphome based esp32 camera
2. Use the given config
3. Wait, i guess

I wish i could narrow it down more.

### Version

0.15.0-6cb5cfb (ghcr.io/blakeblackshear/frigate:stable)

### Frigate config file

```yaml
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac

cameras:birdfeeder:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/birdfeeder
          input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay
            -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps
            1
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy

go2rtc:
  streams:
    birdfeeder:
      - ffmpeg:http://192.168.1.191:8080#video=h264#hardware
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: "256MB" # update for your cameras based on calculation above
    restart: unless-stopped
    devices:
      - "/dev/dri:/dev/dri:rwm"
      - "/dev/bus/usb:/dev/bus/usb"
    device_cgroup_rules:
      - 'c 189:* rmw'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate:/config
      - ./frigate-data:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554"
      - "1984:1984"
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      LIBVA_DRIVER_NAME: i965
      FRIGATE_RTSP_PASSWORD: "...."
      PLUS_API_KEY: "....."
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.85:3100/loki/api/v1/push"

  prometheus-exporter:
    image: rhysbailey/prometheus-frigate-exporter
    restart: unless-stopped
    ports:
      - "9102:9100"
    environment:
      FRIGATE_STATS_URL: http://frigate:5000/api/stats
```

### Relevant Frigate log output

```shell
None
```

### Relevant go2rtc log output

```shell
22:15:32.284 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:http://192.168.1.191:8080#video=h264#hardware
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

esp32 running esphome

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d03a506a-b5fc-4792-95f6-62a7eb264e4e)

**Comment by hawkeye217** [comment]
`22:15:32.284 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error=EOF url=ffmpeg:http://192.168.1.191:8080#video=h264#hardware`

The `EOF` error is indicating that go2rtc can no longer read the stream from your camera.

You could enable go2rtc trace logs to see more.
```
go2rtc:
  log:
    exec: trace
  ...
```

**Reply by tlanfer** [reply]
I've added the parameter, restarted frigate and will report back once i've managed to reproduce the issue. Thanks!

**Comment by tlanfer** [comment, marked as answer]
So when setting the log level to trace, i've added all the ffmpeg parameters to the go2rtc configuration too, because as a good scientist i change multiple parameters at the same time /s

```yaml
go2rtc:
  log:
    exec: trace
  streams:
    birdfeeder:
      - ffmpeg:http://192.168.1.191:8080#video=h264#choppy
  ffmpeg:
    choppy: "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps"
```

It looks like that fixed the issue of go2rtc exploding. So my issue is kinda fixed. If you want to find the underlying issue _why_ go2rtc is exploding, i can take it out again to capture some trace logging of it.
Let me know.
