### DISCUSSION TITLE
Yolov9 not working after storage fills up.

### DISCUSSION THREAD

**Discussion by nckrwlmn** [blakeblackshear/frigate#18745] [Ask A Question]
Spoke too soon. Yesterday my 10tb hard drive filled up to the brim and everything broke. Frigate was only showing five terabytes of usage and there is nothing else on that drive. The actual frigate folder was way more full than that. 

After that point, nothing got detected anymore. Motion is showing in the timeline, but no more detections or events. Even after the storage was cleared out. Redeployed the app and reset the database file and still no detections or events. The logs were showing that the model couldn't detect a whole bunch of objects. That doesn't make sense because I have the same yolov9 that was working before. If I manually add the labels to the label map config then the error is not there anymore, but I still get no events. I have the logs in debug mode, but I can't see any errors. Am I lying to the app with the config file that this model is able to detect these objects? Sure was able to detect them before.

**Comment by NickM-27** [comment]
We can't help without seeing your config

**Comment by nckrwlmn** [comment]
```

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - truck
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - cell phone
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.55
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
    car:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 500
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.55
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
    bicycle:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      min_ratio: 0.8
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.55
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7


review:
  alerts:
    labels:
      - car
      - truck
      - person
      - motorcycle
  detections:
    labels:
      - person
      - bicycle
      - car
      - truck
      - motorcycle
      - airplane
      - bus



go2rtc:
  streams:
    NorthShop-WaterjetRoom:
      - rtsp://admin:Seccam5!@192.168.50.23:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:NorthShop-WaterjetRoom#audio=aac

ffmpeg:
  hwaccel_args: preset-nvidia

record:
  enabled: true
  expire_interval: 30
  retain:
    days: 30
    mode: all
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: high
  alerts:
    pre_capture: 3
    retain:
      days: 100
  detections:
    retain:
      days: 30
    # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: true

detect:
  enabled: true

face_recognition:
  enabled: true
  unknown_score: 0.8 #individual face
  model_size: large

lpr:
  enabled: true

classification:
  bird:
    enabled: true


audio:
  # Optional: Enable audio events (default: shown below)
  enabled: true
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #  - 200 - high sensitivity
  #  - 500 - medium sensitivity
  #  - 1000 - low sensitivity
  min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  # Optional: Filters to configure detection.
  filters:
    # Label that matches label in listen config.
    speech:
      # Minimum score that triggers an audio event (default: shown below)
      threshold: 0.8

snapshots:
  enabled: true
  retain: # retain snapshots for x days
    default: 150
  quality: 100 # 1-100 quality of snapshots
  timestamp: true
  bounding_box: true
  crop: true
  height: 175
  clean_copy: true


model:
  path: /config/model_cache/tensorrt/yolov9-e.engine
  labelmap_path: /labelmap/coco-80.txt
  labelmap:
    0: person
    1: bicycle
    2: car
    3: motorcycle
    4: airplane
    5: bus
    6: train
    7: truck
    8: boat
    9: traffic light
    10: fire hydrant
    11: stop sign
    12: parking meter
    13: bench
    14: bird
    15: cat
    16: dog
    17: horse
    18: sheep
    19: cow
    20: elephant
    67: cell phone
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
  width: 640
  height: 640
  model_type: yolo-generic



#model:
  #path: /config/model_cache/tensorrt/yolov9-e.onnx
  #labelmap_path: /labelmap/coco-80.txt
  #labelmap:
   # 8: truck
  #input_tensor: nchw
  #input_pixel_format: bgr
  #input_dtype: float
  #width: 640
  #height: 640
  #model_type: yolo-generic

#model:
  #path: /config/model_cache/tensorrt/yolov7x-640.trt
  #labelmap_path: /labelmap/coco-80.txt
  #input_tensor: nchw
  #input_pixel_format: rgb
  #width: 640
  #height: 640
  #model_type: yolo-generic

#detectors:
  #onnx:
  #  type: onnx

detectors:
  tensorrt:
    type: tensorrt
    device: 0


semantic_search:
  enabled: true
  reindex: false
  model_size: large

mqtt:
  enabled: false

tls:
  enabled: false

logger:
  default: info
  logs:
    frigate.record.maintainer: info
    frigate.app: debug
version: 0.16-0

camera_groups:
  Yard:
    order: 1
    icon: LuActivity
    cameras: SWxE_Yard

notifications:
  enabled: false
  email: dsfghwaesg
auth:
  failed_login_rate_limit: 10/minute;30/hour
  trusted_proxies:
    - 192.168.50.102
  session_length: 843000
  refresh_time: 432000

```
