### DISCUSSION TITLE
Export function "Name the Export" doesn't seem to work - the filename created is "camera name_" + "5 random characters.mp4"

### DISCUSSION THREAD

**Discussion by nzkiwi68** [blakeblackshear/frigate#18754] [General Support]
### Describe the problem you are having

When I export video and name the export, the filename created that is is "camera name_" + "5 random characters.mp4" 

e.g. "backyard_im35tg.mp4"

The export name I entered in the UI is not used at all.

![export name UI](https://github.com/user-attachments/assets/3a776206-e695-431c-b4a9-6c837be2b09f)

### Version

0.15.0-6cb5cfb

### What browser(s) are you using?

Frifefox 139.0.4 (64 bit)

### Frigate config file

```yaml
mqtt:
  host: 10.220.220.155
  user: camera
  password: REDACTED

# model:
#   path: plus://e63b7345cc83a84ed79dedfc99c16616

go2rtc:
  streams:
#    entrance:
#      - rtsp://admin:REDACTED@10.220.226.41:554/cam/realmonitor?channel=1&subtype=0
#    entrance_detect:
#      - rtsp://admin:REDACTED@10.220.226.41:554/cam/realmonitor?channel=1&subtype=1
    entrance_live:
      - rtsp://admin:REDACTED@10.220.226.41:554/cam/realmonitor?channel=1&subtype=2
    backyard:
      - rtsp://admin:REDACTED@10.220.226.42:554/Preview_01_main
#    backyard_sub:
#      - rtsp://admin:REDACTED@10.220.226.42:554/Preview_01_sub
    backyard_zoom:
      - rtsp://admin:REDACTED@10.220.226.42:554/Preview_02_main
#    backyard_zoom_sub:
#      - rtsp://admin:REDACTED@10.220.226.42:554/Preview_02_sub
#    dining:
#      - rtsp://admin:Total0224641SubDelivery@10.220.226.43:554/cam/realmonitor?channel=1&subtype=0

birdseye:
  enabled: true
  mode: motion
  width: 1920
  height: 1080

ffmpeg:
  # hwaccel_args: preset-intel-qsv-h265
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: pci:0

record:
  enabled: true
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 90
      mode: motion
  detections:
    retain:
      days: 0
      mode: motion
snapshots:
  enabled: true
  retain:
    default: 90

cameras:
  entrance:
    ui:
      order: 1
    birdseye:
      order: 1
    detect:
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@10.220.226.41:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - audio
        - path: rtsp://admin:REDACTED@10.220.226.41:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    live:
      stream_name: entrance_live
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
        - alarm
        - thunder
        - thunderstorm
    objects:
      track:
        - person
        - car
        - dog
        - motorcycle
        - bicycle
      filters:
        person:
          min_score: 0.7
          threshold: 0.7
        car:
          min_score: 0.7
          threshold: 0.7
          mask: 0.393,0.671,0.207,1,0,1,0,0.28,0.042,0.252,0.069,0.482
        dog:
          min_score: 0.7
          threshold: 0.7
        motorcycle:
          min_score: 0.7
          threshold: 0.7
        bicycle:
          min_score: 0.7
          threshold: 0.7
    snapshots:
      required_zones:
        - frontyard
    zones:
      frontyard:
        coordinates: 
          0,401,0,720,576,720,836,720,1072,720,1233,720,1209,579,1166,446,1045,153,679,147,400,146
        interia: 1
    motion:
      contour_area: 10
      mask:
        - 1280,0,1280,176,1081,76,1081,0
        - 341,79,0,199,0,0,335,0
        - 652,30,1080,31,1080,0,650,0
      improve_contrast: false
      threshold: 30
    review:
      alerts:
        required_zones: frontyard
      detections:
        labels: []
  backyard:
    ui:
      order: 2
    birdseye:
      order: 2
    onvif:
      host: 10.220.226.42
      port: 80
      user: admin
      password: REDACTED
    detect:
      width: 896
      height: 512
      fps: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:REDACTED@10.220.226.42:554/Preview_01_sub
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - motorcycle
        - bicycle
      filters:
        person:
          min_score: 0.7
          threshold: 0.7
        dog:
          min_score: 0.7
          threshold: 0.7
        motorcycle:
          min_score: 0.7
          threshold: 0.7
        bicycle:
          min_score: 0.7
          threshold: 0.7
    zones: {}
    motion:
      contour_area: 10
      mask: 0.578,0,0.575,0.08,1,0.081,1,0
    review:
      detections:
        labels: []
  backyard_zoom:
    ui:
      order: 3
    birdseye:
      order: 3
    onvif:
      host: 10.220.226.42
      port: 80
      user: admin
      password: REDACTED
    detect:
      width: 896
      height: 512
      fps: 6
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_zoom
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://admin:REDACTED@10.220.226.42:554/Preview_02_sub
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - motorcycle
        - bicycle
      filters:
        person:
          min_score: 0.7
          threshold: 0.7
        dog:
          min_score: 0.7
          threshold: 0.7
        motorcycle:
          min_score: 0.7
          threshold: 0.7
        bicycle:
          min_score: 0.7
          threshold: 0.7
    zones: {}
    motion:
      contour_area: 10
      threshold: 30
      improve_contrast: false
      mask: 0.576,0,1,0,1,0.086,0.576,0.086
    review:
      detections:
        labels: []
version: 0.15-1
```

### Relevant Frigate log output

```shell
none
```

### Relevant go2rtc log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: false # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    cap_add:
      - CAP_PERFMON
    shm_size: "256mb" # update for your cameras based on calculation above
    secrets:
      - PLUS_API_KEY
    cpuset: "1-7"       # Only run on CPUs 1-7 and elave CPU 0 free
    devices:
      - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config:/config
      - /frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"

secrets:
  PLUS_API_KEY:
    file: plus_api_key.txt
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

not relevant
