### DISCUSSION TITLE
Frigate+ and TensorRT models

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#18764] [General]
I've noticed Frigate+ only supports ONNX models for NVidia instead of TensorRT so are any real world benefits of TensorRT models over ONNX? If so can you convert the ONNX model produced by Frigate+ to TensorRT using utilities in the container since this isn't a viable path in Frigate+ today? Will Frigate+ ever support TensorRT created models?

Thanks!

**Comment by NickM-27** [comment]
No, there is no benefit. In fact using TensorRT has shown to use considerably higher system memory while only being a few milliseconds faster. So  it is much easier to run two ONNX detector instances which will be substantially faster than running one tensorrt detector.

Frigate 0.17 is planned to remove the TensorRT detector entirely in favor of just using the ONNX detector.

**Reply by yousaf465** [reply]
In my testing I found the opposite. TensorRT gives better Detector Inference Speed. 

Multiple ONNX
![image](https://github.com/user-attachments/assets/bc45cb90-ba8e-47ef-bd07-05d9c097ced6)

```
mqtt:
  enabled: false

detectors:
  onnx_0:
    type: onnx
  onnx_1:
    type: onnx


model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

ffmpeg:
  hwaccel_args: preset-nvidia

```

TensorRT
![image](https://github.com/user-attachments/assets/f0702cc4-c55a-44a7-9e80-106cf0cd08db)


```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/8.6.1/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

ffmpeg:
  hwaccel_args: preset-nvidia

```


Single ONNX

![image](https://github.com/user-attachments/assets/92aebafa-039a-4a39-91f5-9cdcbea3f638)

```
detectors:
  onnx_0:
    type: onnx

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

ffmpeg:
  hwaccel_args: preset-nvidia
```
