### DISCUSSION TITLE
[Support]: frigate homeassistant notification's video cannot be played on ios

### DISCUSSION THREAD

**Discussion by tellok** [blakeblackshear/frigate#18788] [General Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I's using the frigate notification blueprint to send notifications to my ios device, the notification's snapshot image works fine, however the notificatons's clip video cannot played.

the working snapshot url:
https://ha.kezhen.xyz:4443/api/frigate/notifications/1750321476.625515-7mm6lc/snapshot.jpg

the not working clip url:
http://10.10.10.12:8123/api/frigate/notifications/1750321617.043851-ikmndf/TAPO-C120-29C9/clip.mp4

the working clip mp4 file cannot open on ios safari or desktop safari browser, however it's can be opened in macos chrome desktop broweser.

here are some debug information
```
# ffprobe -i http://10.10.10.12:8123/api/frigate/notifications/1750321617.043851-ikmndf/TAPO-C120-29C9/clip.mp4
ffprobe version 7.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://10.10.10.12:8123/api/frigate/notifications/1750321617.043851-ikmndf/TAPO-C120-29C9/clip.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso6iso2avc1mp41
    encoder         : Lavf61.1.100
  Duration: 00:00:02.18, start: 0.000000, bitrate: N/A
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 2560x1440, 1444 kb/s, 18.48 fps, 20 tbr, 10240 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 28 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
```

here is the video clip:

https://github.com/user-attachments/assets/47b82d05-eb28-4e6e-b525-a70f7c554c55

### Steps to reproduce

1. install frigate on unraid server using docker
2. homeassistant install frigate integration
3. homeassistant install frigate notification blueprint
4. add a notification automation with frigate notification blueprint
...

### Version

0.16.0-f141b58

### In which browser(s) are you experiencing the issue with?

macOS safari 17.5 (19618.2.12.11.6)

### Frigate config file

```yaml
version: 0.16-0

go2rtc:
  # log:
  #   level: trace
  streams:
    aqara_g100_main: rtsp://10.10.10.11:44425/9e5ccb0b76f30cc9

ffmpeg:
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: auto
  # hwaccel_args: preset-vaapi
  # hwaccel_args: preset-intel-qsv-h264
  # hwaccel_args: preset-intel-qsv-h265
  # output_args:
    # record: preset-record-generic-audio-aac
    # record: preset-record-generic-audio-copy

face_recognition:
  enabled: true
  model_size: large

mqtt:
  enabled: true #打開才會用MQTT去做通知
  host: 10.10.10.12 #MQTT網址
  port: 1883
  user: piok
  password: Itcloud@123
  stats_interval: 15

objects:
  track:
    - person
    - cat
  filters:
    person:
      min_score: 0.2
      threshold: 0.1
    cat:
      min_score: 0.3
      threshold: 0.5

# detectors:
#   detector_name:
#     type: cpu

# detectors:
#   ov:
#     type: openvino
#     device: AUTO
# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   path: /openvino-model/ssdlite_mobilenet_v2.xml
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detectors:
  coral:
    type: edgetpu
    device: usb
    delay: 10

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  crop: true
  retain:
    default: 10
    objects:
      person: 15
  quality: 100

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 10
    mode: all
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  preview:
    quality: medium
  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5

detect:
  enabled: true

semantic_search:
  enabled: false
  model_size: small

lpr:
  enabled: false

classification:
  bird:
    enabled: false


cameras:
  TAPO-C120-29C9:
    enabled: true
    # live:
    #   stream_name: tapo_c120_sub
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-aac
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://10.10.10.11:42657/a9635be7f5add150 #high
          roles:
            - record
        - input_args: preset-rtsp-restream
          path: rtsp://localhost:42657/2c78731c73556c97 #low
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 2
    detect:
      enabled: true
    mqtt:
      enabled: true
      # Optional: crop the snapshot (default: shown below)
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    # audio:
    #   enabled: false
    motion:
      mask:
        - 0.636,0.166,0.677,0.182,0.695,0.224,0.683,0.271,0.65,0.264,0.626,0.234
        - 0,0,0.13,0,0.224,0,0.224,0.044,0.133,0.051,0.136,0.331,0.12,0.867,0.176,1,0,1
        - 0.713,0,1,0.309,1,0
      threshold: 35
      contour_area: 10
      improve_contrast: true
    objects:
      mask:
        - 0.865,0.672,0.848,0.763,0.876,0.82,0.954,0.669,0.913,0.637
        - 0.869,0.272,0.851,0.342,0.898,0.403,0.926,0.325
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          min_score: 0.8
        cat:
          min_score: 0.8
      track:
        - person
        - cat
    zones:
      dining_room:
        coordinates: 
          0.704,0.326,0.712,0.38,0.776,0.486,0.84,0.529,0.889,0.447,0.845,0.369,0.827,0.422,0.802,0.382,0.786,0.376,0.788,0.314,0.763,0.256
        loitering_time: 1
        inertia: 1
        objects:
          - person
        filters:
          person:
            # min_area: 5000
            # max_area: 100000
            min_score: 0.01
            threshold: 0.01
      work_desk:
        coordinates: 0.22,0.175,0.427,0.216,0.464,0,0.206,0
        loitering_time: 0
        inertia: 8
        objects:
          - person
        filters:
          person:
            min_score: 0.01
            threshold: 0.01
```

### docker-compose file or Docker CLI command

```yaml
docker inspect 156b58790815
[
    {
        "Id": "156b5879081538336ff12456f490b090c97569eacb508c80a9f4aee8c38d1588",
        "Created": "2025-06-19T08:26:31.869156615Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 498,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2025-06-19T08:26:32.248268017Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2025-06-19T16:55:39.185303422+08:00",
                        "End": "2025-06-19T16:55:39.25074625+08:00",
                        "ExitCode": 0,
                        "Output": "0.16.0-f141b58"
                    },
                    {
                        "Start": "2025-06-19T16:55:54.273780949+08:00",
                        "End": "2025-06-19T16:55:54.308219577+08:00",
                        "ExitCode": 0,
                        "Output": "0.16.0-f141b58"
                    },
                    {
                        "Start": "2025-06-19T16:56:09.330709358+08:00",
                        "End": "2025-06-19T16:56:09.366276121+08:00",
                        "ExitCode": 0,
                        "Output": "0.16.0-f141b58"
                    },
                    {
                        "Start": "2025-06-19T16:56:24.388714592+08:00",
                        "End": "2025-06-19T16:56:24.430052173+08:00",
                        "ExitCode": 0,
                        "Output": "0.16.0-f141b58"
                    },
                    {
                        "Start": "2025-06-19T16:56:39.45316123+08:00",
                        "End": "2025-06-19T16:56:39.48539925+08:00",
                        "ExitCode": 0,
                        "Output": "0.16.0-f141b58"
                    }
                ]
            }
        },
        "Image": "sha256:2883d8721399dc2a118473eba1fb7dcfa669615fbd29e19149cbb9e0b92d1ec9",
        "ResolvConfPath": "/var/lib/docker/containers/156b5879081538336ff12456f490b090c97569eacb508c80a9f4aee8c38d1588/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/156b5879081538336ff12456f490b090c97569eacb508c80a9f4aee8c38d1588/hostname",
        "HostsPath": "/var/lib/docker/containers/156b5879081538336ff12456f490b090c97569eacb508c80a9f4aee8c38d1588/hosts",
        "LogPath": "/var/lib/docker/containers/156b5879081538336ff12456f490b090c97569eacb508c80a9f4aee8c38d1588/156b5879081538336ff12456f490b090c97569eacb508c80a9f4aee8c38d1588-json.log",
        "Name": "/frigate",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user/appdata/frigate:/config:rw",
                "/mnt/user/surveillance/frigate/:/media/frigate:rw",
                "/mnt/user/tempo/frigate/tmp:/tmp:rw",
                "/etc/localtime:/etc/localtime:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "50m"
                }
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 1073741824,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "0,1,4,5",
            "CpusetMems": "",
            "Devices": [
                {
                    "PathOnHost": "/dev/bus/usb",
                    "PathInContainer": "/dev/bus/usb",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/dri/renderD128",
                    "PathInContainer": "/dev/dri/renderD128",
                    "CgroupPermissions": "rwm"
                }
            ],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 2048,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "tmpfs",
                    "Target": "/tmp/cache",
                    "TmpfsOptions": {
                        "SizeBytes": 1073741824
                    }
                }
            ],
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/frigate",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/surveillance/frigate",
                "Destination": "/media/frigate",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/tempo/frigate/tmp",
                "Destination": "/tmp",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "tmpfs",
                "Source": "",
                "Destination": "/tmp/cache",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "Tower",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5000/tcp": {},
                "8554/tcp": {},
                "8555/tcp": {},
                "8555/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PLUS_API_KEY=",
                "TCP_PORT_1984=1984",
                "TCP_PORT_8971=8971",
                "TCP_PORT_8554=8554",
                "TCP_PORT_8555=8555",
                "HOST_CONTAINERNAME=frigate",
                "TCP_PORT_5000=5000",
                "HOST_HOSTNAME=Tower",
                "FRIGATE_RTSP_PASSWORD=Itcloud@123",
                "LIBVA_DRIVER_NAME=iHD",
                "USE_FP16=false",
                "TZ=Asia/Shanghai",
                "HOST_OS=Unraid",
                "PATH=/usr/local/go2rtc/bin:/usr/local/tempio/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
                "TOKENIZERS_PARALLELISM=true",
                "TRANSFORMERS_NO_ADVISORY_WARNINGS=1",
                "OPENCV_FFMPEG_LOGLEVEL=8",
                "HAILORT_LOGGER_PATH=NONE",
                "DEFAULT_FFMPEG_VERSION=7.0",
                "INCLUDED_FFMPEG_VERSIONS=7.0:5.0",
                "S6_LOGGING_SCRIPT=T 1 n0 s10000000 T",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "test -f /dev/shm/.frigate-is-stopping && exit 0; curl --fail --silent --show-error http://127.0.0.1:5000/api/version || exit 1"
                ],
                "Interval": 15000000000,
                "Timeout": 5000000000,
                "StartPeriod": 300000000000,
                "Retries": 3
            },
            "Image": "ghcr.io/blakeblackshear/frigate:0.16.0-beta3",
            "Volumes": null,
            "WorkingDir": "/opt/frigate",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "net.unraid.docker.icon": "https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png",
                "net.unraid.docker.managed": "dockerman",
                "net.unraid.docker.webui": "http://[IP]:[PORT:5000]"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "339cd84723530972a73c5c43f7a1cb36ea5e3a3fe09cb4ab7986eeb62eb510a6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "7c744df8974139aa116d3cb4de74b3f7f4234f42b382f9e70116627786363d79",
                    "EndpointID": "7100b47d53f701fb04ec2a3fa6991ecfcd9c93a33cc02a7978c3b32c958b8c78",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

### Relevant Frigate log output

```shell
2025-06-19 16:58:12.880926333  10.10.10.12 - - [19/Jun/2025:16:58:12 +0800] "GET /api/events/1750321617.043851-ikmndf/clip.mp4 HTTP/1.1" 200 400800 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "10.10.10.1"
2025-06-19 16:58:13.384202283  10.10.10.12 - - [19/Jun/2025:16:58:13 +0800] "GET /api/events/1750321617.043851-ikmndf/clip.mp4 HTTP/1.1" 200 400792 "http://10.10.10.12:8123/api/frigate/notifications/1750321617.043851-ikmndf/TAPO-C120-29C9/clip.mp4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15" "10.10.10.1"
```

### Relevant go2rtc log output

```shell
do not see any go2rtc logs
```

### Operating system

Home Assistant OS

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

TPLink Tapo C120

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/08b3068c-b322-43d2-82ac-40c25226d513)

### Any other information that may be helpful

I diged the problems a little, it seems safari needs the video stream to support "range" headers with http status code 206. however, the frigate is now returnning status code 200.
