### DISCUSSION TITLE
PiP-for one Cam doesn't work anymore

### DISCUSSION THREAD

**Discussion by albotroz** [blakeblackshear/frigate#18791] [Ask A Question] [answered]
Since yesterday, the browser-internal PiP function no longer works for one camera, but continues to work for the other cameras.
The PiP symbol is simply not displayed when I move the mouse cursor over it.
The problem occurs in the Frigate web interface and in the HomeAssistantOS interface. PiP icon is displayed in Reolink web interface.

Frigate and HomeAssistantOS work separately. within Proxmox.
So they have their own containers.

As a comparison because of config I left another of my cameras in the config.

Linux Mint 22.1 Cinnamon 6.4.8
Linux Kernel 6.8.0-60-generic
Firefox 139.0.4 (64-Bit)

```
mqtt:
  enabled: true
  host: 192.168.xxx.xxx
  port: 1883
  topic_prefix: frigate
#  client_id: frigate
  user: mqtt-user
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

logger:
#  default: debug
  default: info
  logs:
    frigate.mqtt: error
    frigate.video: error
    frigate.events: error
    frigate.object_processing: error

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

go2rtc:
  streams:
    front:
      - http://192.168.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
      - ffmpeg:front#video=copy
    front_sub:
      - http://192.168.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxx&password=xxx
      - ffmpeg:front_sub#video=copy

    hof:
      - rtsp://xxx:xxx@192.168.xxx.xxx:554/11
    hof_sub:
      - rtsp://xxx:xxx@192.168.xxx.xxx:554/12

  webrtc:
    candidates:
      - 192.168.xxx.xxx:8555
      - stun:8555
      - stun.l.google.com:19302

#####################################################
# Camera Front - Reolink E1 Outdoor PoE via PoE
#####################################################

cameras:
  front:
    enabled: true
    ui:
      order: 1
      dashboard: true
    ffmpeg:
#      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
#      hwaccel_args: "auto"
      output_args:
        record: preset-record-generic
#        record: preset-record-generic-audio-copy
      inputs:
        # Stream High Res
        - path: 
            http://192.168.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
          input_args: preset-http-reolink
#        - path: rtsp://127.0.0.1:8554/front
#          input_args: preset-rtsp-restream
          roles:
            - record
        # Stream Low Res
        - path: 
            http://192.168.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=xxx&password=xxx
          input_args: preset-http-reolink
#        - path: rtsp://127.0.0.1:8554/front_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true
      width: 640
      height: 360
      fps: 4

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 7
        mode: all
      preview:
        quality: medium
      events:
        pre_capture: 15
        post_capture: 15
        retain:
          default: 7
          mode: motion

    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: false
      crop: false
      required_zones: []
      retain:
        default: 0
        objects:
          person: 7
          dog: 7
      quality: 100

    objects:
      track:
        - person
        - dog
#        - car
#      mask: 0.764,0.936,0.691,1,0.586,0.98,0.587,0.51,0.737,0.42,0.974,0.488
      filters:
        person:
          threshold: 0.6
#          mask: 0.764,0.936,0.691,1,0.586,0.98,0.587,0.51,0.737,0.42,0.974,0.488
        dog:
          threshold: 0.6
#          mask: 0.764,0.936,0.691,1,0.586,0.98,0.587,0.51,0.737,0.42,0.974,0.488

    birdseye:
      enabled: true
      restream: true
      width: 1280
      height: 720
      quality: 15
      mode: continuous
      order: 1

    live:
      stream_name: front_sub
      height: 360
      quality: 8

    timestamp_style:
      position: tl
      format: '%d.%m.%Y %H:%M:%S'
      color:
        red: 255
        green: 140
        blue: 0
      thickness: 2
#      effect: solid

#####################################################
# Camera Hof - upCam Tornado HD S via WLAN
#####################################################

  hof:
    enabled: true
    ui:
      order: 2
      dashboard: true
    ffmpeg:
#      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-intel-qsv-h264
#      hwaccel_args: "auto"
      output_args:
        record: preset-record-generic
#        record: preset-record-generic-audio-copy
      inputs:
        # Stream High Res
        - path: rtsp://127.0.0.1:8554/hof
          input_args: preset-rtsp-generic
          roles:
            - record
        # Stream Low Res
        - path: rtsp://127.0.0.1:8554/hof_sub
          input_args: preset-rtsp-generic
          roles:
            - detect
      retry_interval: 30

    detect:
      width: 640
      height: 352
      fps: 5
      enabled: true

    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 7
        mode: all
      preview:
        quality: medium
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: motion

    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: false
      crop: false
      required_zones: []
      retain:
        default: 0
        objects:
          person: 7
      quality: 100

    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.7

    birdseye:
      enabled: true
      restream: true
      width: 1280
      height: 720
      quality: 15
      mode: continuous
      order: 2

    live:
      stream_name: hof_sub
      height: 352
      quality: 8

    timestamp_style:
      position: tl
      format: '%d.%m.%Y %H:%M:%S'
      color:
        red: 255
        green: 140
        blue: 0
      thickness: 2
#      effect: solid

#####################################################
ui:
  timezone: Europe/Berlin
  time_format: 24hour
  date_style: full
  time_style: medium
  strftime_fmt: '%d/%m/%Y %H:%M'


version: 0.14
```

**Edit: Strange. After I wrote the post it works again after all the hours before it didn't work.**
