### DISCUSSION TITLE
[Camera Support]: Connection timed out after firmware upgrade

### DISCUSSION THREAD

**Discussion by brundage** [blakeblackshear/frigate#18798] [Camera Support] [answered]
### Describe the problem you are having

I have three Amcrest ip8m-t2599ew cameras and I updated their firmware to Amcrest_IPC-HX25(8)XX-Molec_Eng_NP_V2.820.00AC002.0.R.230408.bin. Frigate is now throwing a time out error when establishing the go2rtc session.

The cameras all respond on their web interfaces.

### Version

ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
version: 0.15-1


mqtt:
  enabled: false


ffmpeg:
  hwaccel_args: preset-vaapi


auth:
  reset_admin_password: false
  # 


go2rtc:
  streams:
    inside_hq:
      - ffmpeg:rtsp://{FRIGATE_VIEWER_USER}:{FRIGATE_VIEWER_PASS}@inside-cam.internal/cam/realmonitor?channel=1&subtype=0

    inside_lq:
      - ffmpeg:rtsp://{FRIGATE_VIEWER_USER}:{FRIGATE_VIEWER_PASS}@inside-cam.internal/cam/realmonitor?channel=1&subtype=1




cameras:


  inside:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://127.0.0.1:8554/inside_hq
          input_args: preset-rtsp-restream
    detect:
      enabled: false
      width: 640
      height: 480
      fps: 5
```

### Relevant Frigate log output

```shell
frigate  | 2025-06-19 12:59:06.640234419  12:59:06.640 WRN [rtsp] error="streams: exec: [tcp @ 0x559368ccd180] Connection to tcp://inside-cam.internal:554?timeout=5000000 failed: Connection timed out\n[in#0 @ 0x559368ccbd00] Error opening input: Connection timed out\nError opening input file rtsp://correct_user:correct_pass@inside-cam.internal/cam/realmonitor?channel=1&subtype=0.\nError opening input files: Connection timed out\n" stream=inside_hq
frigate  | 2025-06-19 12:59:06.644246754  [2025-06-19 12:59:06] frigate.video                  ERROR   : inside: Unable to read frames from ffmpeg process.
frigate  | 2025-06-19 12:59:06.644253705  [2025-06-19 12:59:06] frigate.video                  ERROR   : inside: ffmpeg process is not running. exiting capture thread...
frigate  | 2025-06-19 12:59:21.605281782  [2025-06-19 12:59:21] watchdog.inside                ERROR   : Ffmpeg process crashed unexpectedly for inside.
frigate  | 2025-06-19 12:59:21.605344196  [2025-06-19 12:59:21] watchdog.inside                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2025-06-19 12:59:21.605578616  [2025-06-19 12:59:21] ffmpeg.inside.detect           ERROR   : [rtsp @ 0x559c60d0d080] method DESCRIBE failed: 404 Not Found
frigate  | 2025-06-19 12:59:21.605712269  [2025-06-19 12:59:21] ffmpeg.inside.detect           ERROR   : [in#0 @ 0x559c60d0cd80] Error opening input: Server returned 404 Not Found
frigate  | 2025-06-19 12:59:21.605718282  [2025-06-19 12:59:21] ffmpeg.inside.detect           ERROR   : Error opening input file rtsp://127.0.0.1:8554/inside_hq.
frigate  | 2025-06-19 12:59:21.605850235  [2025-06-19 12:59:21] ffmpeg.inside.detect           ERROR   : Error opening input files: Server returned 404 Not Found
```

### Relevant go2rtc log output

```shell
streams: exec: [tcp @ 0x55cdc7fdf180] Connection to tcp://inside-cam.internal:554?timeout=5000000 failed: Connection timed out\n[in#0 @ 0x55cdc7fddd00] Error opening input: Connection timed out\nError opening input file rtsp://corret_user:correct_pass@inside-cam.internal/cam/realmonitor?channel=1&subtype=0.\nError opening input files: Connection timed out\n" stream=inside_hq
```

### FFprobe output from your camera

```shell
1 panopt /root # docker exec  frigate /usr/lib/ffmpeg/7.0/bin/ffprobe rtsp://correct_user:correct_pass@inside-cam.internal/cam/realmonitor\?channel=1\&subtype=0
ffprobe version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100

[tcp @ 0x55a3c6ed8040] Connection to tcp://inside-cam.internal:554?timeout=0 failed: Connection timed out
rtsp://user:pass@inside-cam.internal/cam/realmonitor?channel=1&subtype=0: Connection timed out
```

### Frigate stats

```json
{"cameras":{"inside":{"camera_fps":0.0,"process_fps":0.0,"skipped_fps":0.0,"detection_fps":0.0,"detection_enabled":false,"pid":391,"capture_pid":398,"ffmpeg_pid":603,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"cpu":{"inference_speed":10.0,"detection_start":0.0,"pid":361}},"detection_fps":0.0,"gpu_usages":{"intel-vaapi":{"gpu":"0.0%","mem":"-%"}},"cpu_usages":{"frigate.full_system":{"cpu":"1.6","mem":"7.8"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"15":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"16":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"},"24":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"25":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"26":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"45":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"},"46":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"85":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"87":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"88":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"91":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"94":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"105":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"107":{"cpu":"1.0","cpu_average":"3","mem":"1.7","cmdline":"python3 -u -m frigate"},"127":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: master process nginx"},"177":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"178":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"179":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"198":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"219":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"nginx: cache manager process"},"317":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"345":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.recording_manager"},"347":{"cpu":"0.1","cpu_average":"0","mem":"1.0","cmdline":"frigate.review_segment_manager"},"361":{"cpu":"0.0","cpu_average":"0","mem":"1.1","cmdline":"frigate.detector.cpu "},"376":{"cpu":"0.2","cpu_average":"0","mem":"1.1","cmdline":"frigate.output       "},"390":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -threads 1 -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"391":{"cpu":"0.1","cpu_average":"0","mem":"1.1","cmdline":"frigate.process:inside"},"398":{"cpu":"0.1","cpu_average":"0","mem":"1.0","cmdline":"frigate.capture:inside"},"407":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"577":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 60"},"589":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":150,"version":"0.15.0-6cb5cfb","latest_version":"0.15.1","storage":{"/media/frigate/recordings":{"total":841840.7,"used":16151.7,"free":825689.0,"mount_type":"xfs"},"/media/frigate/clips":{"total":841840.7,"used":16151.7,"free":825689.0,"mount_type":"xfs"},"/tmp/cache":{"total":953.7,"used":0.0,"free":953.7,"mount_type":"tmpfs"},"/dev/shm":{"total":2048.0,"used":0.5,"free":2047.5,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1750340266},"processes":{"recording":{"pid":345},"review_segment":{"pid":347},"go2rtc":{"pid":94}}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest ip8m-t2599ew

### Screenshots of the Frigate UI's System metrics pages

N/A

### Any other information that may be helpful

```
0 panopt /root # nmap -p 1-65535 inside-cam.internal
Starting Nmap 7.95 ( https://nmap.org ) at 2025-06-19 13:48 -00
Nmap scan report for inside-cam.internal (10.0.3.69)
Host is up (0.00090s latency).
Not shown: 65531 closed tcp ports (reset)
PORT      STATE SERVICE
80/tcp    open  http
554/tcp   open  rtsp
1935/tcp  open  rtmp
37777/tcp open  unknown
MAC Address: A0:60:32:..:..:.. (Amcrest Technologies)

Nmap done: 1 IP address (1 host up) scanned in 4.25 seconds
```

**Comment by hawkeye217** [comment]
Perhaps there is a setting in the camera that needs to be enabled for RTSP to function?

**Reply by brundage** [reply]
Don't see anything to enable RTSP and nmap shows that the cameras are listening on port 554.

**Reply by hawkeye217** [reply]
You might try nmap from inside the Frigate container. That may reveal if there's a networking or Docker issue.

**Reply by brundage** [reply]
Verified that I can access the camera stream via VLC to the same rtsp uri. I'll play around with connectivity from inside the Frigate container

**Reply by brundage** [reply]
ffprobe in docker times out while ffprobe on the host works.

**Comment by brundage** [comment]
ffprobe in docker times out while ffprobe on the host works

I'm new to docker. What would be the next step in testing connectivity?

**Reply by brundage** [reply]
Also getting this error:

```
2025-06-20 10:03:25.518486005  2025/06/20 10:03:25 [error] 161#161: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
2025-06-20 10:03:25.518502105  2025/06/20 10:03:25 [error] 161#161: *2 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"

```

**Reply by hawkeye217** [reply]
For that particular error, see the [FAQ](https://github.com/blakeblackshear/frigate/discussions/16391), Usage question 4.

What is your docker compose file?

**Reply by brundage** [reply]
I've allocated 2048mb for shm and don't see symptoms consistent with question 4 in the FAQ.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb" # python -c 'print("{:.2f}MB".format( <camera count> * (<width> * <height> * 1.5 * 20 + 270480) / 1048576))'
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /var/frigate/storage:/media/frigate
      - type: tmpfs # 1GB of memory reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_TAPO_USER: "viewer"
      FRIGATE_TAPO_PASS: "super secret password"
      FRIGATE_TAPO_PASS_SHA: "super secret password"
      FRIGATE_VIEWER_USER: "viewer"
      FRIGATE_VIEWER_PASS: "super secret password"
```
