### DISCUSSION TITLE
Frigate on RK3588 loads single core to 100% while others 10%

### DISCUSSION THREAD

**Discussion by zzp-oai** [blakeblackshear/frigate#18801] [Ask A Question]
Hi,

I am running Frigate on RK3588, I found the load is mostly on a single core. Is there a way to spread the load on multiple cores?

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/9e4a69be-5a4f-48a4-9428-0746c10ad19f" />

key configurations

```
ffmpeg:
  hwaccel_args: preset-rk-h264

go2rtc:
  streams:
    driveway_3200_1800:
      - rtsp://192.168.1.68/streaming/channels/101
    driveway_768_432:
      - rtsp://192.168.1.68/streaming/channels/102
    backyard_3200_1800:
      - rtsp://192.168.1.42/streaming/channels/101
    backyard_1280_720:
      - rtsp://192.168.1.42/streaming/channels/102
    sidedoor_3200_1800:
      - rtsp://192.168.1.43/streaming/channels/101
    sidedoor_768_432:
      - rtsp://192.168.1.43/streaming/channels/102

detectors:
  rknn:
    type: rknn # required
    # core mask for npu
    core_mask: 0b111

model:
  path: /config/yolo_i8/i8-yolonas_m-rk3588.rknn
  #path: deci-fp16-yolonas_m
  model_type: yolonas
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 14
      mode: active_objects
  detections:
    retain:
      days: 14
      mode: active_objects

```
