### DISCUSSION TITLE
[Config Support]: Frigate Auto Deleting Old Recordings

### DISCUSSION THREAD

**Discussion by davideferrero** [blakeblackshear/frigate#18803] [Config Support]
### Describe the problem you are having

I've recently updated frigate to the 0.15, precisely I have made a newer installation. 
It's all working quite well for my needs, but there's an issue: Frigate doesn't automatically delete recordings older than 7 days while keeping detections for 183 days.

### Version

0.15-1

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

review:
  alerts:
    labels:
      - person

record:
  enabled: True
  retain:
    days: 5
    mode: all
  alerts:
    retain:
      days: 183
      mode: motion
  detections:
    retain:
      days: 183
      mode: motion


logger:
  default: info
  logs:
    frigate.video: debug

cameras:

  00-hk-camera-name:
    record:
      enabled: true
    ffmpeg:
      
      inputs:
        - path: rtsp://username:password@192.168.0.0:554/streaming/channels/102
          roles:
            - detect
          input_args: preset-rtsp-restream
        - path: rtsp://username:password@192.168.0.0:554/streaming/channels/101
          roles:
            - record
          input_args: preset-rtsp-restream
    detect:
      width: 704
      height: 480
      fps: 5

version: 0.15-1
```

### Relevant Frigate log output

```shell
i don't know what to paste there for this specific issue.
```

### Relevant go2rtc log output

```shell
2025-06-20 09:27:34.067372402  [INFO] Preparing new go2rtc config...
2025-06-20 09:27:34.625555096  [INFO] Starting go2rtc...
2025-06-20 09:27:34.712665556  09:27:34.712 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2025-06-20 09:27:34.712670985  09:27:34.712 INF config path=/dev/shm/go2rtc.yaml
2025-06-20 09:27:34.713159571  09:27:34.713 INF [rtsp] listen addr=:8554
2025-06-20 09:27:34.713184032  09:27:34.713 INF [api] listen addr=:1984
2025-06-20 09:27:34.713251804  09:27:34.713 INF [webrtc] listen addr=:8555/tcp
2025-06-20 09:27:44.068239922  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
---
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "4096mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb    # Coral USB
    volumes:
      - ./config:/config
      - /mnt/FILESERVER_NVR/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554"   # RTSP feeds
```

### Object Detector

Coral

**Comment by davideferrero** [comment]
I tried to use image: ghcr.io/blakeblackshear/frigate:stable instead of image: ghcr.io/blakeblackshear/frigate:stable-tensorrt

I'll let you know if this change something, how frequently the recording was deleted?

**Comment by NickM-27** [comment]
More information is needed about what behavior you are seeing

**Reply by davideferrero** [reply]
As you can see from my config file, I set it so that the full recordings are kept for 5 days, and after that only the alerts and detections should be retained for 183 days. Which kind of information do you need?

**Reply by NickM-27** [reply]
You never described what is actually happening, what part of that is not working as expected, etc etc

**Reply by davideferrero** [reply]
Frigate keep every recording also with the config file that says:

record:
  enabled: True
  retain:
    days: 5
    mode: all
  alerts:
    retain:
      days: 183
      mode: motion
  detections:
    retain:
      days: 183
      mode: motion
      
In a previous version with events, instead of detections and alerts it works.

**Reply by NickM-27** [reply]
What do you mean by keep every recording, can you show an example of files that you expect to have been deleted but have not been. What does the storage metrics page say?

**Comment by davideferrero** [comment]
@NickM-27 Under /storage/recordings/insert_your_date, the folders are around 300–400GB each for a full day of continuous recording. Once only detections are retained, the folders drop to around 10GB.

As I mentioned in my first comment, I switched the Docker image from frigate:stable-tensorrt to frigate:stable, and that solved the issue. I was using the tensorrt version to try using GPU and Coral together, without any success for the moment.

For anyone interested, here’s the final configuration block I’m using for recordings:
```
record:
  enabled: true
  retain:
    days: 5
    mode: all
  alerts:
    retain:
      days: 183
      mode: motion
  detections:
    retain:
      days: 183
      mode: motion
```

Thank you all for your help and time!
