### DISCUSSION TITLE
[Support]:  Issues with Frigate on iOS – Streams and Tabs Not Working Properly

### DISCUSSION THREAD

**Discussion by pawelkot123** [blakeblackshear/frigate#18818] [General Support]
### Checklist

- [x] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I've been having issues with Frigate on iOS. The interface loads, but the streams only work occasionally—sometimes they load, sometimes they don't. Additionally, most of the other functionality doesn't work at all: the recordings,  tab, and the detections tab are unresponsive.

### Steps to reproduce

1.Open Frigate in a browser on iOS (tested with Safari and Chrome).
2.Log in to the Frigate interface.
3.Wait for the dashboard to load.
4.Observe that:

The live streams sometimes load, and sometimes stay black or frozen.

The "Recordings", "FR" (Face Recognition), and "Detections" tabs do not load at all — they remain blank or display an error.

### Version

0.16

### In which browser(s) are you experiencing the issue with?

google chrome

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.107
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 

detectors:
  onnx:
    type: onnx


model:
  model_type: yolonas
  path: plus://
  width: 640
  height: 640
  input_pixel_format: bgr
  input_tensor: nchw

objects:
  track:
    - license_plate
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog
    - face
  filters:
    face:
      min_area: 6000
      min_score: 0.7
      threshold: 0.75


review:
  alerts:
    labels:
      - license plate
      - car
      - person
      - bicycle
      - motorcycle
      - cat
      - dog
      - face

cameras:
  livingroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.72:554/stream1
          roles:
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440

  ganz1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.90:554/snl/live/1/1
          roles:
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion: {}
    objects:
      filters:
        car:
          mask: 0.621,0.415,0.659,0.358,0.787,0.388,0.87,0.461,1,0.607,1,0.887
    zones:
      deptak:
        coordinates: 0.337,0.327,0.558,1,0.687,1,0.385,0.294
        inertia: 3
        loitering_time: 0
  ganz2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.91:554/snl/live/1/1
          roles:
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440
    motion:
      mask: 0.231,0.996,0.482,0.291,0.456,0.003,0,0.001,0,0.997
  ganz3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.79:554/snl/live/1/1
          roles:
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440
  ganz4:
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.92:554/snl/live/1/1
          roles:
            - detect
            - record

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    objects:
      filters:
        car:
          mask: 
            0.325,0.345,0.883,0.63,0.902,0.047,0.662,0.031,0.38,0.142,0.253,0.216,0.263,0.316
    zones:
      wjazd_garaz:
        coordinates: 0.277,0.322,0.25,0.345,0.375,1,1,0.693
        inertia: 3
        loitering_time: 0
        speed_threshold: 1
        distances: 2.2,25,2.2,25
        objects: car
  ganz5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.93:554/snl/live/1/1
          roles:
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440

    motion:
      mask: 
        0.071,0,0.071,0.211,0.085,0.299,0.095,0.378,0.106,0.47,0.116,0.518,0.133,0.58,0.15,0.635,0.176,0.661,0.193,0.679,0.226,0.678,0.257,0.652,0.276,0.612,0.311,0.554,0.343,0.491,0.382,0.452,0.434,0.406,0.47,0.375,0.516,0.341,0.575,0.311,0.624,0.284,0.671,0.259,0.745,0.218,0.795,0.193,0.85,0.157,0.891,0.13,0.942,0.093,0.975,0.07,0.997,0.044,0.999,0.004
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.102:554/h264/ch01/main/av_stream
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

  kitchen:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://:@192.168.1.100:554/stream1
          roles:
            - record
    detect:
      enabled: true
      width: 2560
      height: 1440

record:
  enabled: true
  retain:
    days: 21
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion

version: 0.16-0
camera_groups:
  outside:
    order: 1
    icon: LuCar
    cameras:
      - ganz1
      - ganz2
      - ganz3
      - ganz4
      - ganz5
  inside:
    order: 2
    icon: LuAlarmCheck
    cameras:
      - kitchen
      - garage
      - livingroom
semantic_search:
  enabled: false
  reindex: false
  model_size: small
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
classification:
  bird:
    enabled: false
```

### docker-compose file or Docker CLI command

```yaml
i dont have it now
```

### Relevant Frigate log output

```shell
the error is all the time
```

### Relevant go2rtc log output

```shell
i dont have go2rtc on for the streams
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

GANZ ZN8-VD4M212-NIR          GANZ ZN8-B4M212-DS  tapoc120   tapoc210 tapo

**Comment by hawkeye217** [comment]
The only way we can help is with Frigate logs, browser console logs, and browser network tab screenshots.

**Comment by hawkeye217** [comment]
In looking at your config, you have not defined a `detect` role for some of your cameras, and you are using a very high `detect` resolution. See the note in the documentation on why this is problematic, and why this may be causing some of your issues: 

https://docs.frigate.video/configuration/cameras#setting-up-camera-inputs

Also, see the documentation on choosing a detect resolution:

https://docs.frigate.video/frigate/camera_setup/#choosing-a-detect-resolution

**Reply by pawelkot123** [reply]
i changed them and it works better but this is still happening with the face recognition and the detections and for the events not only on the phone evets dont load also on pc and is there any way to fix that?
![Zdjęcie WhatsApp 2025-06-23 o 10 00 17_7579d6f2](https://github.com/user-attachments/assets/a9ab0380-1a83-437b-b7a9-ac39db59cf51)

**Reply by hawkeye217** [reply]
What is your config now?

**Reply by pawelkot123** [reply]
it's the same except the  i changed the detections from 2k to 1080p

**Reply by hawkeye217** [reply]
It would be helpful to see your new full config, a full copy of the frigate logs, your docker compose file, and screenshots of the system metrics, camera metrics, and storage metrics pages.

**Reply by pawelkot123** [reply]
here is my config: 
```
mqtt:
  enabled: true
  host: 192.168.1.107
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user:
  password: 

detectors:
  onnx:
    type: onnx


model:
  model_type: yolonas
  path: plus://
  width: 640
  height: 640
  input_pixel_format: bgr
  input_tensor: nchw

objects:
  track:
    - license_plate
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog
    - face
  filters:
    face:
      min_area: 6000
      min_score: 0.7
      threshold: 0.75


review:
  alerts:
    labels:
      - license plate
      - car
      - person
      - bicycle
      - motorcycle
      - cat
      - dog
      - face

cameras:
  livingroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

  ganz1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

    motion: {}
    objects:
      filters:
        car:
          mask: 0.621,0.415,0.659,0.358,0.787,0.388,0.87,0.461,1,0.607,1,0.887
    zones:
      deptak:
        coordinates: 0.337,0.327,0.558,1,0.687,1,0.385,0.294
        inertia: 3
        loitering_time: 0
  ganz2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask: 0.231,0.996,0.482,0.291,0.456,0.003,0,0.001,0,0.997
  ganz3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      ktos_wchodzi_albo_wychodzi:
        coordinates: 0.755,1,0.858,0.59,0.701,0.519,0.648,0.603,0.684,0.661,0.532,0.784
        inertia: 3
        loitering_time: 2
        objects: person
  ganz4:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - detect
            - record

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0.263,0.316,0.254,0.215,0.369,0.129,0.662,0.031,0.904,0.031,0.884,0.634
    objects:
      filters:
        car:
          mask: 
            0.325,0.345,0.883,0.63,0.902,0.047,0.662,0.031,0.38,0.142,0.253,0.216,0.263,0.316
    zones:
      wjazd_garaz:
        coordinates: 0.277,0.322,0.25,0.345,0.375,1,1,0.693
        inertia: 3
        loitering_time: 0
        speed_threshold: 1
        distances: 2.2,25,2.2,25
        objects: car
  ganz5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

    motion:
      mask: 
        0.071,0,0.071,0.211,0.085,0.299,0.095,0.378,0.106,0.47,0.116,0.518,0.133,0.58,0.15,0.635,0.176,0.661,0.193,0.679,0.226,0.678,0.257,0.652,0.276,0.612,0.311,0.554,0.343,0.491,0.382,0.452,0.434,0.406,0.47,0.375,0.516,0.341,0.575,0.311,0.624,0.284,0.671,0.259,0.745,0.218,0.795,0.193,0.85,0.157,0.891,0.13,0.942,0.093,0.975,0.07,0.997,0.044,0.999,0.004
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

    motion:
      mask: 0.039,0.924,0.332,0.924,0.332,0.991,0.037,0.988
  kitchen:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720

record:
  enabled: true
  retain:
    days: 21
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion

version: 0.16-0
camera_groups:
  outside:
    order: 1
    icon: LuCar
    cameras:
      - ganz1
      - ganz2
      - ganz3
      - ganz4
      - ganz5
  inside:
    order: 2
    icon: LuAlarmCheck
    cameras:
      - kitchen
      - garage
      - livingroom
semantic_search:
  enabled: false
  reindex: false
  model_size: small
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
classification:
  bird:
    enabled: false
```

Metrics 
![image](https://github.com/user-attachments/assets/351ff40b-1038-4814-a089-470c782f1995)
![image](https://github.com/user-attachments/assets/a83f375c-de0b-4571-8ff5-311cca689f25)
frigate logs
[frigate-logs.txt](https://github.com/user-attachments/files/20903288/frigate-logs.txt)
