### DISCUSSION TITLE
[Support]: Detections not showing up under review

### DISCUSSION THREAD

**Discussion by jkoopmann** [blakeblackshear/frigate#18829] [General Support]
### Describe the problem you are having

Hi,

I have several detections that show up under the search icon but not when I go to review and e.g. search for them. 

Since they show up correctly in search the detection itself seems to work correctly. E.g. deers in the garden show up as such but when I go to review, filter the appropriate camera (mark show reviewed) as well "deer" does not even come up. When I switch to motion and go to the appropriate time the deers show up. 

This also happens to detections that usually DO show up (like cars from the garage camera). These detections are in a masked zone which would explain why they do not show up in "review" (but should they also not show up in the search function then if they are masked out?). I would expect review and search to be somewhat aligned. Yes, several events in review are grouped etc.

For one camera in question I have:

`   objects:
      track:
        - person
        - car
        - license_plate
        - face
        - dog
        - cat
        - bicycle
        - amazon
        - ups
        - package
        - gls
        - dhl
        - motorcycle
        - deer`

Moreover:

`record:
  enabled: true
  retain:
    days: 2
    mode: motion  # Retain recordings with motion detected for 3 days
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 30
      mode: active_objects  # Retain alert recordings for 30 days
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: active_objects  # Retain detection recordings for 30 days`

So why am I not seeing them in review?

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
cameras:
  Halle: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Halle
          roles:
            - record
            - detect
    detect:
      enabled: true
    motion:
      threshold: 45
      mask: 0.177,0.034,0.997,0.584,1,0,0.176,0.004
      contour_area: 35
      improve_contrast: false
    zones:
      Halle_Halle:
        coordinates: 0.001,0.993,0,0.456,0.573,0.408,1,0.831,0.999,0.997
        loitering_time: 0
        inertia: 3
      Halle_Wiese:
        coordinates: 0.002,0.069,0.177,0.056,0.572,0.405,0,0.449
        loitering_time: 0
        inertia: 3
    objects:
      track:
        - person
        - car
        - license_plate
        - face
        - dog
        - cat
        - bicycle
        - amazon
        - ups
        - package
        - gls
        - dhl
        - motorcycle
        - deer


record:
  enabled: true
  retain:
    days: 2
    mode: motion  # Retain recordings with motion detected for 3 days
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 30
      mode: active_objects  # Retain alert recordings for 30 days
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: active_objects  # Retain detection recordings for 30 days
```

### Relevant Frigate log output

```shell
None I found
```

### Relevant go2rtc log output

```shell
None I found
```

### FFprobe output from your camera

```shell
ffprobe version 7.1.1 Copyright (c) 2007-2025 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.6)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[rtsp @ 0x131604a60] RTP: dropping old packet received too late
    Last message repeated 4 times
Input #0, rtsp, from 'rtsp://10.10.10.152:554/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 2688x1520 [SAR 1:1 DAR 168:95], 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Install method

Docker CLI

### docker-compose file or Docker CLI command

```yaml
unraid
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision
