### DISCUSSION TITLE
[Bug]: 0.16 Beta 3: Snapshot Image not reliably sending over MQTT when using required_zones for MQTT under Camera Settings

### DISCUSSION THREAD

**Discussion by DarrenGReilly** [blakeblackshear/frigate#18834] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Observed from test upgrade from successfully working 0.15 to 0.16 Beta 3.

My config uses the camera->mqtt->requied_zones parameter.  Objects (people and cars in my case) are correctly identified as having entered the defined zones in 0.16 Beta 3 shown under lifecylce in UI.  However, unlike 0.15, the snapshot image is not reliably sent over MQTT when a known object enters the required zone.  Most of the time, when I for example enter the required zone, it will not send the snapshot over MQTT.  On very rare occasions it may do so but I have been unable to work out under what specific conditions that it works.  I have tried disabling the required_zones section of the config and the snapshots are then reliably sent over MQTT.  Re-enabling the required_zones parameter again, once the object enters the required zone, no snapshot is sent over MQTT but the lifecycle in the UI shows what you would expect, i.e. showing the person of vehicle entering the required zone area.

This worked as expected in 0.15 but not reliably in Beta 3.  I have also tested in Beta 2 and it didn't work for it either.

### Steps to reproduce

1. Start with basic config with one camera and MQTT globally enabled
2. Set up initially without any required zones for MQTT to verify that for example, a person walking by on camera will trigger a snapshot image to be sent over MQTT.
3. Once working, now in config file under mqtt, under the defined camera, specify a required zone so that a snapshot image is only sent whenever an identified object enters the zone.
4. The snapshot will not be reliable sent, even though the lifecylce in the UI shows the identified object having entered the zone.

### Version

0.16.0-f141b58

### In which browser(s) are you experiencing the issue with?

N/A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.100
  port: 1883

logger:
  default: info

snapshots:
  enabled: true
  retain:
    default: 30

detect:
  enabled: true
  min_initialized: 2
  max_disappeared: 25

ffmpeg:
  hwaccel_args: preset-nvidia

objects:
  track:
    - person
    - car
    - dog
    - cat
    - cow

cameras:
  BackStreet:
    ui:
      order: 2
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://user:pass@192.168.1.52:554/Streaming/Channels/101/
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://user:pass@192.168.1.52:554/Streaming/Channels/102/
          roles:
            - detect
    zones:
      GaragePath:
        coordinates: 0,0.621,0.713,0.486,0.982,0.545,0.903,1,0,1
        loitering_time: 0
        inertia: 3
        objects:
          - person
    mqtt:
      required_zones:
        - GaragePath
detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
version: 0.16-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: Frigate0.16_Beta3
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    deploy:	 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Frigate16b3/config:/config
      - /Frigate16b3/media/frigate:/media/frigate
      #- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #  target: /tmp/cache
      #  tmpfs:
      #    size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
2025-06-22 20:54:06.964553470  You have successfully opted out to send the telemetry data.
2025-06-22 20:54:06.987155725  [INFO] Preparing Frigate...
2025-06-22 20:54:10.398564546  [INFO] Starting Frigate...
2025-06-22 20:54:22.996618533  [2025-06-22 20:54:22] frigate.util.config            INFO    : Checking if frigate config needs migration...
2025-06-22 20:54:23.033538467  [2025-06-22 20:54:23] frigate.util.config            INFO    : frigate config does not need migration...
2025-06-22 20:54:28.182954998  [2025-06-22 20:54:28] frigate.app                    INFO    : Starting Frigate (0.16.0-f141b58)
2025-06-22 20:54:28.282069585  [2025-06-22 20:54:28] peewee_migrate.logs            INFO    : Starting migrations
2025-06-22 20:54:28.283693506  [2025-06-22 20:54:28] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-06-22 20:54:28.318836165  [2025-06-22 20:54:28] frigate.app                    INFO    : Recording process started: 442
2025-06-22 20:54:28.319566891  [2025-06-22 20:54:28] frigate.app                    INFO    : Review process started: 445
2025-06-22 20:54:28.322246252  [2025-06-22 20:54:28] frigate.app                    INFO    : go2rtc process pid: 128
2025-06-22 20:54:28.344098768  [2025-06-22 20:54:28] detector.coral                 INFO    : Starting detection process: 447
2025-06-22 20:54:28.345911511  [2025-06-22 20:54:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2025-06-22 20:54:28.364367257  [2025-06-22 20:54:28] frigate.app                    INFO    : Output process started: 484
2025-06-22 20:54:28.571384932  [2025-06-22 20:54:28] frigate.app                    INFO    : Camera processor started for BackStreet: 518
2025-06-22 20:54:28.590045629  [2025-06-22 20:54:28] frigate.app                    INFO    : Capture process started for BackStreet: 520
2025-06-22 20:54:28.880740262  [2025-06-22 20:54:28] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-06-22 20:54:29.109264661  [2025-06-22 20:54:29] frigate.api.fastapi_app        INFO    : FastAPI started
2025-06-22 20:54:31.156083083  [2025-06-22 20:54:31] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2025-06-22 20:54:31.244772382  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

### Relevant go2rtc log output

```shell
2025-06-22 20:54:10.398323070  [INFO] Preparing new go2rtc config...
2025-06-22 20:54:10.732733089  [INFO] Starting go2rtc...
2025-06-22 20:54:11.052823673  20:54:11.052 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
2025-06-22 20:54:11.052849104  20:54:11.052 INF config path=/dev/shm/go2rtc.yaml
2025-06-22 20:54:11.053276736  20:54:11.053 INF [rtsp] listen addr=:8554
2025-06-22 20:54:11.053322124  20:54:11.053 INF [api] listen addr=:1984
2025-06-22 20:54:11.053754255  20:54:11.053 INF [webrtc] listen addr=:8555
2025-06-22 20:54:15.945750070  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2365G1-I

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-06-22 210932](https://github.com/user-attachments/assets/6398dd24-3f5e-4cda-a697-6db907d9e353)

### Any other information that may be helpful

This is my first use of github, so please accept my apologies if I have overlooked something silly!  I've also observed a change to the zone coordinates in the config file.  The scaling seems different...only mentioning this in the event it may be related but I feel it is not since object detection in the defined zones is working going by the lifecycle shown in the UI.

**Comment by hawkeye217** [comment]
A change was made in this commit that might affect you: https://github.com/blakeblackshear/frigate/pull/18245/commits/599699aef8e6fa58f4fd381c049f61235539fc33

If an object is stationary, a snapshot will not be sent through MQTT. 

This is different behavior than 0.15. Could this explain what you are seeing?

**Reply by DarrenGReilly** [reply]
Thank you for the very prompt response.  In answer to your question, no, but perhaps yes.  I have tested whilst continually walking/moving across the required zone.  I've also just retested with different scenarios including not stopping in zone, stopping in the zone, etc.  All correctly identified in the object lifecycle but no snapshot sent. I say 'perhaps yes', since if this is the only code change related to this logic, then it must in some way relate to the obj.is_stationary() definition.  If that is the case, then is it returning true unexpectedly thereby preventing snapshot sent over mqtt?

**Reply by hawkeye217** [reply]
There was some pretty large refactoring done in this area for 0.16, so this may require a second look to ensure the snapshot callback is being called at the right time. Stay tuned.

**Reply by DarrenGReilly** [reply]
Perfect, many thanks. If you need any further info from me in the meantime, just let me know and I'll provide what I can.  Thanks again.

**Reply by NickM-27** [reply]
You likely need to reduce the best_image_timeout

**Reply by DarrenGReilly** [reply]
Hi Nick,  many thanks for the suggestion.  I have tried reducing this as you suggested.  I tried reducing it from 60 to 30, then 10 and then 1 to be extreme!  But no difference.  I had no prior knowledge of the existence of that parameter until your suggestion and then found out where it resides from the config schema!  For clarity, frigate is identifying correctly that I have entered the zone, and also takes an appropriate snapshot all of which I see in the object lifecycle and snapshot screens.  The issue is that it now does not reliably send this snapshot over mqtt.  It has done once or twice but it is so infrequent that it is difficult to ascertain the precise conditions/scenario in which it does work.  The above config works as expected in frigate version 0.15.0-6cb5cfb.  If there is anything else you think may be worth trying, please feel free to suggest and I will give it a try. Thanks again for your suggestion.

**Reply by NickM-27** [reply]
Thanks, I have found the issue and will have a fix up for it

**Reply by DarrenGReilly** [reply]
That's great.  Thanks Nick.  In the clarification in my previous message, I should have also re-iterated that the issue is only present whenever required_zones is used under mqtt settings.  If I comment these lines out of the config, snapshots are sent over mqtt as normal. I know this is already mentioned above but I should have had it included in that clarification!  Hopefully the issue you have found covers this. Many thanks.

**Reply by DarrenGReilly** [reply, marked as answer]
Hi, I can confirm that this issue has been resolved in 0.16 Beta 4 and now works as expected.  Many thanks guys for the fix...much appreciated.

**Comment by rogerquake** [comment]
@NickM-27 Do we know if this should be fixed in the 17 beta releases? I made a similar post about this issue and got no response. 

I'm running the 17 beta2 release now, but worried about re-enabling the mqtt snapshot zone config due to the issues I noticed.

https://github.com/blakeblackshear/frigate/discussions/21064
https://github.com/blakeblackshear/frigate/discussions/21027

**Reply by NickM-27** [reply]
I don't believe we have seen other reports of this since 0.16 and I haven't see issues on my side, I can't remember for sure but don't think 0.17 has had any changes in this regard

**Reply by thelabexpedition67** [reply]
I have the same issue on 0.17.0-f0d69f7.

The snapshot are being sent if I have the configuration like this:


```
 home_front_top: #
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/home_front_top_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/home_front_top
          roles:
            - record
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 896
      height: 512
      fps: 10
      annotation_offset: -4200
    record:
      enabled: true
    live:
      streams:
        home_front_top: home_front_top
    objects:
      track:
        - person
        - motorcycle
        - bicycle
        - dog
        - car
        - cat
        - license_plate
        - face
      genai:
        enabled: false
      filters:
        car: {}
    motion:
      mask:
        - 0,0.087,0.431,0.086,0.43,0,0,0
        - 0,0.873,0.218,0.391,0.193,0.129,0,0.186
      threshold: 39
      contour_area: 10
      improve_contrast: true
    zones:
      zones_home_front_top_primary:
        coordinates: 
          0,1,0.331,0.264,0.374,0.259,0.377,0.322,0.51,0.319,0.587,0.304,0.652,0.3,0.704,0.281,0.753,0.289,0.826,0.311,0.863,0.383,1,0.673,1,0.673,0.999,0.996,0.301,1,0.191,1,0.094,1
        inertia: 3
        loitering_time: 0
    review:
      alerts:
        required_zones: zones_home_front_top_primary
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: []
```

But no snapshot is sent to MQTT if:

```
mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
      required_zones: [zones_home_front_top_primary]
```

I can see the event on the frigate ui, with the "Tracked Object Details", the zone is correctly triggered.

In my case I have never received any snapshot via MQTT when the zone was set.
