### DISCUSSION TITLE
[Support]: Missing thumbnails in "review" page

### DISCUSSION THREAD

**Discussion by dagord** [blakeblackshear/frigate#18838] [General Support]
### Describe the problem you are having

In the "review" section, I can no longer see the thumbnails of the detected events after 9:09 PM yesterday (a broken link icon is displayed). However, if I hover the cursor over them, the preview is shown correctly, and the recordings themselves also work fine. The issue is strictly with the thumbnails: inspecting the browser, I can see that the requested images are actually missing (e.g. https://frigate.mydomain.com/clips/review/thumb-field-camera-1750619575.358362-4jb9o3.webp returns a 404 error), but this problem does not affect recordings prior to the mentioned time.

I haven’t made any configuration changes; the issue appeared spontaneously. This happens on multiple devices

I found another thread (https://github.com/blakeblackshear/frigate/discussions/15794) describing the same situation, but in my case, restarting Frigate did not solve the problem. I couldn’t find anything relevant in the logs.

### Version

0.15.0-cea210d

### Frigate config file

```yaml
mqtt:
  enabled: false
tls:
  enabled: false
ui:
  time_format: 24hour

go2rtc:
  streams:
    front-camera: 
      ffmpeg:rtsp://user:password$@192.168.0.212:554/h265Preview_01_main#video=h264#width=1365#height=1024#audio=copy#hardware
    terrace-camera: 
      ffmpeg:rtsp://admin:password$@192.168.0.213/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46VmlkZW9QdzIwMjUt#video=h264#audio=copy#hardware
    field-camera: 
      ffmpeg:rtsp://user:password$@192.168.0.209:554/h265Preview_01_main#video=h264#width=1365#height=1024#audio=copy#hardware
    reolink-camera: 
      ffmpeg:rtsp://user:password$@192.168.0.214:554/h265Preview_01_main#video=h264#width=2048#height=768#audio=copy#hardware
    indoor-camera: 
      ffmpeg:rtsp://A4dC0oPOc8Lx:w6xMU4oCJLOj@192.168.0.211/live0#video=h264#width=1280#height=720#audio=copy#hardware
    indoor-living-camera: 
      ffmpeg:rtsp://admin:password$@192.168.0.210:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - bike
    - cat

cameras:
  front-camera: # <------ Name the camera
    ui:
      order: 0
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-camera?video&audio
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      path: '5.0'
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    motion:
      mask:
        - 0.801,1,0.868,0.834,0.81,0.703,0.716,0.721,0.645,0.84,0.681,0.991
        - 0.774,0.616,0.815,0.619,0.851,0.459,0.794,0.071,0.57,0,0.327,0,0.179,0.117,0.141,0.264,0.251,0.363,0.357,0.449,0.383,0.59,0.418,0.686,0.476,0.692,0.501,0.603,0.625,0.526,0.746,0.613
    objects:
      mask:
        - 0.732,0.626,0.816,0.617,0.857,0.446,0.779,0.063,0.671,0.031,0.371,0,0.288,0,0.197,0.07,0.139,0.267,0.337,0.447,0.367,0.556,0.418,0.692,0.476,0.693,0.513,0.594,0.632,0.533
        - 0.648,0.845,0.689,1,0.809,1,0.829,0.913,0.869,0.832,0.821,0.699,0.725,0.711
  terrace-camera: # <------ Name the camera
    ui:
      order: 3
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrace-camera
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      path: '5.0'
      input_args: preset-rtsp-generic
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
  indoor-living-camera: # <------ Name the camera
    ui:
      order: 4
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor-living-camera
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      path: '5.0'
      input_args: preset-rtsp-generic
      output_args:
        record: preset-record-generic
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: false
  field-camera: # <------ Name the camera
    ui:
      order: 1
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/field-camera?video&audio
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      path: '5.0'
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    zones: {}
    review: {}
    motion:
      mask:
        - 0.788,0,0.788,0.129,0.801,0.314,0.838,0.674,0.776,1,1,1,1,0.178,1,0,0.657,0
        - 0.028,0.703,0.112,0.709,0.285,0.537,0.467,0.368,0.469,0.329,0.597,0.242,0.588,0.063,0.347,0.093,0.208,0.206,0,0.37,0.003,0.687
    objects:
      mask:
        - 0.782,0.126,0.783,0.989,0.999,0.989,1,0,0.791,0.007
        - 0.004,0.695,0.099,0.715,0.474,0.357,0.5,0.325,0.602,0.241,0.582,0.057,0.5,0.07,0.364,0.081,0.214,0.196,0,0.36
  reolink-camera: # <------ Name the camera
    ui:
      order: 5
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink-camera?video&audio
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      path: '5.0'
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
    motion:
      mask: 
        0.199,0.188,0.308,0.056,0.432,0.014,0.65,0.015,0.734,0.114,0.877,0.273,0.914,0.298,0.94,0.23,0.853,0.023,0.806,0,0.537,0,0.194,0,0.166,0.046
  indoor-camera: # <------ Name the camera
    ui:
      order: 2
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor-camera
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
      path: '5.0'
      input_args: preset-rtsp-generic
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
    record: # <----- Enable recording
      enabled: true
version: 0.15-1
camera_groups:
  outdoor:
    order: 1
    icon: LuTreePine
    cameras:
      - front-camera
      - field-camera
      - terrace-camera
      - reolink-camera
  Indoor:
    order: 2
    icon: LuBedDouble
    cameras:
      - indoor-camera
      - indoor-living-camera
detectors:
  ov:
    type: openvino
    device: GPU

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -hwaccel_output_format
    - yuv420p

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
semantic_search:
  enabled: false
  reindex: false
  model_size: large
```

### Relevant Frigate log output

```shell
no errors dispayed
```

### Relevant go2rtc log output

```shell
no errors dispayed
```

### FFprobe output from your camera

```shell
nothing relevant
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```        
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "640mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a>
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/matteo/projects/frigate/config:/config
      - /home/matteo/usb/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

 

```

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

all cameras are affected
