### DISCUSSION TITLE
[Bug]: `null` sub_label gets included in db `reviewsegment.data` for objects where a sub-label was previously cleared; causes frontend crash on Review page

### DISCUSSION THREAD

**Discussion by zhongfu** [blakeblackshear/frigate#18832] [Report a Bug] [answered]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

On version 0.16.0-beta3 (the latest tagged version), if:
- an object has a sub-label added (in my case, automatically, due to a spurious `fedex` detection),
- that sub-label is later cleared (e.g. by editing it in Explore -> (object) -> Edit sub label), and
- another event involving the same object occurs, triggering a detection (or alert?)...

the resulting row for this detection in the `reviewsegment` table may end up having `"sub_labels": [null]` in the JSON object in the `data` column.

This then appears to cause a frontend crash (blank page) on the Review page, when the corresponding review card for the detection gets rendered: https://github.com/blakeblackshear/frigate/blob/8a9ebe92921d5a06a3b5228a526c6961c29acd03/web/src/components/card/ReviewCard.tsx#L187

where `item` is `null`, and `null.includes(...)` is called because the `!== undefined` check doesn't catch the `null`.

Could possibly be related to #16779, but I'm not sure

### Steps to reproduce

1. Have an object be detected and *stay detected*
2. Add a sub-label to said object, then clear it (by setting it to a blank string?)
3. Do something that causes another detection (and/or alert?) to be triggered on that same object
4. Attempt to preview the triggered detection/alert on the Review page of the UI 

### Version

0.16.0-f141b58

### In which browser(s) are you experiencing the issue with?

Google Chrome 132.0.6834.159

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  coral1:
    type: edgetpu
    device: pci

model:
  path: plus://REDACTED

go2rtc:
  streams:
    cam-1:
      - REDACTED
    cam-2:
      - REDACTED
    cam-3:
      - REDACTED

detect:
  enabled: true

objects:
  track:
    - person
    - face
    - bicycle
    - car
    - license_plate
    - fedex
    - ups
    - dhl
    - motorcycle
    - bird
    - cat
    - dog
    - waste_bin
    - package

review:
  alerts:
    labels:
      - person
      - bicycle
      - car
      - motorcycle

record:
  enabled: true

snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true

cameras:
  cam-1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam-1
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam-1
          roles:
            - record
      hwaccel_args: preset-intel-qsv-h264
    motion:
      threshold: 38
      contour_area: 10
      improve_contrast: true
  cam-2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam-2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam-2
          roles:
            - record
      hwaccel_args: preset-intel-qsv-h264
    motion:
      threshold: 33
      contour_area: 10
      improve_contrast: true
  cam-3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam-3
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam-3
          roles:
            - record
      hwaccel_args: preset-intel-qsv-h264
    motion:
      threshold: 35
      contour_area: 10
      improve_contrast: true

version: 0.16-0

semantic_search:
  enabled: true
  reindex: false
  model_size: small

notifications:
  enabled: true
  email: REDACTED

face_recognition:
  enabled: true
  model_size: small

lpr:
  enabled: true

classification:
  bird:
    enabled: false

telemetry:
  stats:
    network_bandwidth: true

auth:
  enabled: true
  cookie_secure: true
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    group_add:
      - 44 # video
      - 103 # render
      - 120 # apex
    cap_add:
      - CAP_PERFMON
    container_name: frigate
    privileged: true
    restart: always
    stop_grace_period: 30s
    shm_size: "8gb"
    devices:
      - /dev/apex_0:/dev/apex_0 # PCIe Coral
      - /dev/dri/renderD128:/dev/dri/renderD128 # Intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /data/frigate:/media/frigate
      - /opt/frigate/certs:/etc/letsencrypt/live/frigate:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2147483648
    ports:
      - "443:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "REDACTED"
      PLUS_API_KEY: "REDACTED"
    logging:
      driver: journald
      options:
        tag: "frigate"
```

### Relevant Frigate log output

```shell
(no errors in logs during/after UI crash)
```

### Relevant go2rtc log output

```shell
(not relevant)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2232-I5

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/d66d58f4-ce83-4a2e-bde8-775f54068b3e)
![image](https://github.com/user-attachments/assets/4b0d3350-10a6-400e-a2c5-970a4ef2e83f)
![image](https://github.com/user-attachments/assets/163baaa8-f175-4649-b52c-deda35795bd7)
![image](https://github.com/user-attachments/assets/04a47752-0baa-4364-bb2d-2b69ff76c054)

### Any other information that may be helpful

Browser dev console logs:

```
TypeError: Cannot read properties of null (reading 'includes')
    at Events-CH8WxFQY.js:1:34373
    at Array.filter (<anonymous>)
    at Ha (Events-CH8WxFQY.js:1:34348)
    at Bs (i18n-Dm2t6b-c.js:38:17392)
    at Mp (i18n-Dm2t6b-c.js:40:44652)
    at Lp (i18n-Dm2t6b-c.js:40:40254)
    at mg (i18n-Dm2t6b-c.js:40:40182)
    at Pl (i18n-Dm2t6b-c.js:40:40035)
    at wf (i18n-Dm2t6b-c.js:40:36331)
    at Nl (i18n-Dm2t6b-c.js:40:35279)
```

After this happens and the page goes blank, the websocket connection also gets closed (but this is probably just a side-effect of the crash).

Manually editing the broken (?) entry in the `reviewsegment` table to remove the `null` sub-label fixes this issue and allows the Review page to be loaded properly again
