### DISCUSSION TITLE
[Config Support]: Live view shows alerts/detection for objects outside of zones

### DISCUSSION THREAD

**Discussion by Unspec7** [blakeblackshear/frigate#18835] [Config Support] [answered]
### Describe the problem you are having

For whatever reason, Live view does not appear to care about zones. I'm unsure if this is normal or not, but it's highly irritating.

As you can see, a car is detected:

<img width="477" alt="image" src="https://github.com/user-attachments/assets/eae7652a-abaa-45ad-9b1c-4eaf59ffcfc2" />

However, no car is within any of my zones (the parked SUV is masked out):

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/1f389129-19a5-42a4-a6d6-a639f8870793" />

The yellow box is detection for vehicles (car, bicycle, bus, motorcycle)

The blue box is for everything I am currently tracking. I have set up Frigate so that there is detection for both zones, but only alerts for the blue zone (e.g. someone actually enters my yard)

Please help me understand why Live view insists on detecting a car even though it should not be.

### Version

0.15.0-6cb5cfb

### Frigate config file

```yaml
go2rtc:
  streams:
    ## #video=copy is needed for a single line ffmpeg config when using audio tags, or else video stream is dropped
    Doorway:
      - rtsp://[redated]:{FRIGATE_RTSP_PASSWORD}@192.168.52.2:554/stream=0
      - ffmpeg:Doorway#audio=opus
    Doorway_sub:
      - rtsp://[redated]:{FRIGATE_RTSP_PASSWORD}@192.168.52.2:554/stream=1
      - ffmpeg:Doorway#audio=opus
  webrtc:
    candidates:
      - 192.168.20.6:8555
      - stun:8555

cameras:
  Doorway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/Doorway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Doorway
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask: 0,0,0,0.439,1,0.424,1,0
    zones:
      Doorway_Vehicles:
        coordinates: ...
        inertia: 3
        loitering_time: 3
        objects:
          - bicycle
          - bus
          - car
          - motorcycle
      Doorway_Front_Yard:
        coordinates: ...
        inertia: 3
        loitering_time: 2
    review:
      detections:
        required_zones:
          - Doorway_Vehicles
          - Doorway_Front_Yard
      alerts:
        required_zones: Doorway_Front_Yard
    objects:
      filters:
        person: {}
        car:
          mask: ...
```

### Relevant Frigate log output

```shell
N/A
```

### Relevant go2rtc log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Object Detector

Coral
