### DISCUSSION TITLE
Beelink EQ14 support

### DISCUSSION THREAD

**Discussion by gokalpakgul** [blakeblackshear/frigate#18850] [Ask A Question]
As I read from documentation, Beelink EQ14 has compatibility issues. Do we still have this problem or it is solved somehow? E.g.
https://www.amazon.de/-/en/gp/product/B0BYZ32M2Z/ref=ox_sc_act_title_1?smid=AXH2SW380BDWO&psc=1

**Comment by hawkeye217** [comment]
Some users have reported that the EQ14 doesn't support the Coral.

**Reply by Jimmi61** [reply]
The support for Coral is the compatibility issue at which the documentation refers to? I plan to use a Hailo8 PCIe card, therefore there should not be any problem I guess.
I prefer the EQ14 compared with the S13 beacuse at the same price I have the internal power supply and the double 2.5G ports.

**Reply by NickM-27** [reply]
We're not aware of anyone that has tried the Hailo with that

**Reply by Jimmi61** [reply]
I compiled the Hailo drivers and RT succesfully on a [ME Mini](https://www.bee-link.com.cn/catalog/product/index?id=1041) that has a very similar hardware. I think I'll get the EQ14 and test it soon.

**Reply by Jimmi61** [reply]
I have now an EQ14 with a Hailo 8 PCIe card and Debian 13 running on bare metal with Docker, Frigate is working like a charm.

**Reply by Jimmi61** [reply]
I spoke too early, I have experienced few system freeze, most probably due to Hailo card.

Anytime I start the container I get the messages in the attached file, I attach because there are several thousands of lines, most of them repetition of the same warning, someone different, example starting from line 2613. They are all warnings no errors.
[logs.txt](https://github.com/user-attachments/files/22555108/logs.txt)

After one freeze I could catch the following lines in the log:
```
list_del corruption. next->prev should be ffffe136c74b5dc8, but was f7ffe136c74b5dc8. (next=ffffe136c74b5d48)
------------[ cut here ]------------
kernel BUG at lib/list_debug.c:65!
BUG: unable to handle page fault for address: 000003fffffffff8
#PF: supervisor read access in kernel mode
#PF: error_code(0x0000) - not-present page
```
Someone understand what is the matter?

**Reply by ristomatti** [reply]
I did not get any logs ever to show up before crashes. My EQ14 ran couple of weeks without issues but then after not touching anything it started resetting itself first every few hours, then at some point it could run only minutes..

Your issue might be different, but if you go Beelink's support forum, you'll notice issues with power supplies are a common theme with all their mini PC's. In my case the issue first seemed to occur most often when I a) restarted Frigate, b) I ran a backup of the Frgigate LXC from a NVME disk to another disk.. But then sometimes it crashed while idle.

I spent a full weeekend troubleshooting the damn thing and was pulling my hair out w/o finding any way to reliably reproduce the crash. I went through the BIOS settings trying to enable/disable suspicious looking settings countless times. I even tried lowering the RAM speed 200-400MHz which some had reported as a fix (to a N100 based mini PC from another brand), but it had no effect.

The symptoms fit either memory or PSU issues. I saw 2-3 posts (Beelink support forum, Reddit) which said they got rid of the issue after they replaced the integrated power supply. I didn't have a spare RAM stick to try, so I decided to detach the PSU and do some tests with.

I hooked the PSU to an electronic load, run it for an hour while testing it at varying loads. To my surprise the PSU was able to hold up a >=12V output at all times, even during my 15min stress test at its maximum rated 4A current (it did get toasty hot!).

What I did find out though was that it's voltage ripple is terrible and it increases with load. Around 1A (12W) load it was ~0.1 VPK and at 3A (36W) load ~0.2 VPK. As a comparison my lab/adjustable power supply had 0.005VPK at 12V 4A load.

This could very well explain crashes at times of heavy CPU and IO. I've measured the whole unit to pull in over 25W with both CPU/IO intensive tasks. The output ripple got much worse with high load which is never great for sensitive electronics.

I then run the EQ14 from my lab PSU for a week w/o crashes. Then briefly tried once again with the original PSU and it run ok a few days, then constant crashes. I then pulled it out and added a buck converter module in its place to convert 19V from an old brand name laptop power brick to the 12V it expects as is my planned permanent solution. EQ14's uptime is now past 3 days with zero crashes after my mod.

I want to see it reaches at least 2-4 weeks of uptime before I can say with quite high certainty that it was the PSU.⏳

**Reply by ristomatti** [reply]
In case you feel confident trying this mod, this video is an excellent guide https://youtu.be/POFyzOw609c. It is for a different Beelink model and the PSU is 19V, but otherwise the procedure is exactly the same. PSU looks the same, is at the same place and held in place exactly the same.

**Reply by Jimmi61** [reply]
Thanks @ristomatti , do you think power issues may cause also system freeze? Is this related to low power capacity or something in the PSU quality? I'm searching the threads mentioned by you on Beelink and Reddit but I cannot find them, may you post any link?

 It's fancy because I choose Beelink to avoid external PSU, otherwise I would choose a GTK.

I use the EQ14 headless, as I said I installed a very basic system with no GUI and no other servers except Frigate on Docker, therefore the power consumption now should be quite low. The Wifi interface is disabled, but I'l also try disonnecting the Wifi card to reduce it even more.

If I have a PSU suitable in the pile of leftovers I have and I'll also give a try replacing the internal.

**Reply by Jimmi61** [reply]
Frigate was up without camera for 2 days now and no freeze. I think most probably the freeze is consequence of detection or recording. I'll continue the testing.

**Reply by ristomatti** [reply]
@Jimmi61 Freezing is not how I'd describe the PSU related issues I had. Initially it was instant power off, then instant reset/reboot after I configured it to start automatically when it has power. I think it's intended for "restart after power outage" type of scenarios, but it's a nice safeguard in case it still crashes. I haven't yet seen any after I removed the integrated PSU.

It was one of the reasons I picked this model as well, so I feel the frustration if you too will discover the PSU to be the culprit. I could've tried contacting Beelink support for a replacement PSU, but I decided not to bother. I'm not an electronics engineer, but I would doubt they could do much to improve the design. There's just not enough space. The PSU is smaller than common phone chargers which for sure cannot produce 48 watts.

**Reply by ristomatti** [reply]
@Jimmi61 In case you're having the same issue as I am, it indeed occurred most often during high IO+CPU activity. I couldn't get mine to freeze/crash when running various stress tests for example. It required real life load. When the issues first started to appear, I found two ways to trigger it: 1) Restart Frigate Docker container, 2) Do a backup of the Frigate container from NVMe drive to anotehr.

But in my case the freezing becamo more an more common each day. At one point my EQ14 crashed within minutes, each and every time. What was weird is the fact the system first run ~2 weeks before the first freeze. When I eventually tried using external PSU, I got a week of steady running, then decided to try the original PSU once more. To my surprise, it was not freezing anymore for ~5 days straight. Enough to make me think the adjustments in BIOS had fixed the problem and having better experience with external PSU was just coincidence... But after the 3 days, it started failing faster and faster. I truly hope it won't resurface anymore with the externa PSU.🤞 (otherwise it's going into the bin 🚮)

**Reply by Jimmi61** [reply]
> But in my case the freezing becamo more an more common each day. At one point my EQ14 crashed within minutes, each and every time.

@ristomatti if I understood correct your probelm is not OS freezing but reboot. By freezing I mean that the system is still on but does not respond to any connection. It is necessary to power off manually by power button or disconnecting the power cable.

After I reinstalled everything now is almost one week that I do not experience problems anymore. I'll keep it monitored

**Reply by ristomatti** [reply]
IIRC when the issue first occurred, it appeared like the EQ14 was suspended (power LED lit, and machine not responding). Initially I thought I had accidentally pressed the power button as it was sitting next to my keyboard and the power button defaults to suspend/sleep mode.

It only turned into rebooting after I changed the machine to power on after recovering a power outage. (I don't remember the setting, but it was about which CPU/power state to resume or something like that). Only after this change the freeze turned into "reboot". I assume this setting is primarily intended for recovering after an actual power outage. In my case it was likely the power supply browning out / glitching briefly, which would be equivalent to an actual power outage.

My EQ14 is still running stable without a single freeze/power reset after I replaced the PSU.

**Reply by Jimmi61** [reply]
@ristomatti which OS are you using on the EQ14? May you check if in your logs are present the same warnings that I posted in the [attachment](https://github.com/user-attachments/files/22555108/logs.txt)?
Before starting the frigate container open a shell and type the command: `journalctl -f` after that start the container and check the logs.

**Reply by ristomatti** [reply]
@Jimmi61 Proxmox VE 9.0.11 (Debian 13 with Proxmox kernel).

I do not get that warning. I use a USB Coral TPU. Based on this, it looks like the warning your getting is related to Hailo's driver/kernel module:
```
Call Trace:
 <TASK>
 hailo_vdma_buffer_map+0x90/0x500 [hailo_pci]
 hailo_vdma_buffer_map_ioctl+0xc0/0x1b0 [hailo_pci]
 hailo_pcie_fops_unlockedioctl+0x1ca/0x490 [hailo_pci]
```

 Have you got a PCIe Hailo working? If so, which port did you install it?

I do get similar kernel traces during boot from `r8157` (Realtek RTL8157 driver) and also some Intel DRM related one which looks like this:

```
------------[ cut here ]------------
i915 0000:00:02.0: [drm] Port B asks to use VBT vswing/preemph tables
WARNING: CPU: 3 PID: 400 at drivers/gpu/drm/i915/display/intel_bios.c:2701
 intel_bios_init+0x1470/0x1930 [i915]
Modules linked in: polyval_generic ghash_clmulni_intel snd_hda_ext_core sh
a256_ssse3 sha1_ssse3 snd_soc_core i915(+) snd_compress ac97_bus snd_pcm_dmaengine aesni_
intel snd_hda_intel snd_intel_dspcfg snd_intel_sdw_acpi crypto_simd cryptd snd_hda_codec 
snd_hda_core snd_hwdep snd_pcm rapl snd_timer drm_buddy intel_cstate ttm wmi_bmof drm_dis
play_helper cmdlinepart snd pcspkr cec spi_nor intel_pmc_core mtd ee1004 soundcore pmt_te
lemetry rc_core mei_me pmt_class mei i2c_algo_bit igen6_edac intel_vsec acpi_tad acpi_pad
 mac_hid zfs(PO) spl(O) vhost_net vhost vhost_iotlb tap it87(OE) hwmon_vid efi_pstore nfn
etlink dmi_sysfs ip_tables x_tables autofs4 btrfs blake2b_generic xor raid6_pq r8152(OE) 
cdc_ncm cdc_ether usbnet mii dm_thin_pool dm_persistent_data dm_bio_prison dm_bufio spi_p
xa2xx_platform dw_dmac dw_dmac_core spi_pxa2xx_core 8250_dw nvme r8169 i2c_i801 intel_lps
s_pci xhci_pci nvme_core realtek spi_intel_pci intel_lpss i2c_mux i2c_smbus spi_intel xhc
i_hcd nvme_auth idma64 video wmi pinctrl_alderlake
CPU: 3 UID: 0 PID: 400 Comm: (udev-worker) Tainted: P           OE      6.
14.11-3-pve #1
Tainted: [P]=PROPRIETARY_MODULE, [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
Hardware name: AZW EQ/EQ, BIOS TWEQF003 03/31/2025
RIP: 0010:intel_bios_init+0x1470/0x1930 [i915]
Code: 24 48 8b 78 08 4c 8b 67 50 4d 85 e4 75 03 4c 8b 27 e8 a4 2a 9e f4 89
 d9 4c 89 e2 48 c7 c7 58 04 58 c1 48 89 c6 e8 c0 20 f9 f3 <0f> 0b e9 26 fd ff ff 0f b7 83
 60 04 00 00 83 e8 03 66 83 f8 04 76
```

Both seem to be harmless in practice though.

**Comment by gokalpakgul** [comment]
Thks a lot for the answer

With coral support you mean EQ14 also does not support coral while using usb port.
I found 2 beelink devices.

Beelink Mini PC, EQ13 Intel Alder Lake N200 Processor (up to 3.70GHz), 16GB DDR4 RAM 500GB PCIe3.0 SSD, Dual 1000Mbps LAN/Dual HDMI/WiFi6/BT5.2, Low Power Mini Desktop Computer
https://amzn.eu/d/1bui3Dl 

Beelink Mini S13 Mini PC, Intel N150 (4C/4T, up to 3.6Ghz), 16G DDR4 500G SSD Mini Desktop Computer, 4K Display, HDMI/Type-C/WiFi6/BT5.2/Dual 2.5G RJ45
https://amzn.eu/d/6keDTL8 

I will prefer S13 mini because both support extra nvme for ssd hd connection, but S13 supports 2x2.5 lan port. I am planning only 3-4 cameras. Comments will be appreciated.

Thks in advance

Regards

Gokalp

**Reply by hawkeye217** [reply]
A number of users have reported using the N150 processor without issues when running on bare metal Debian with Docker. You can use the OpenVINO detector. 

See these related threads: 

https://github.com/blakeblackshear/frigate/discussions/17743 
https://github.com/blakeblackshear/frigate/discussions/15735

**Reply by ristomatti** [reply]
The EQ14 runs great also in a nested virtualization setup under Proxmox 9.x (Debian 13 LXC running Docker).

It took quite a while to figure out how to get GPU acceleration working though. I started of with a Debian 12 LXC but it turned out Debian 13 was required to get new enough Intel GPU drivers (at the time there was no official Debian 13 LXC template available). After a manual upgrade GPU acceleration worked right away. The GPU and USB Coral TPU passthrough configuration was no different than with earlier Intel CPUs.

For running Frigate the Beelink EQ14 has been a huge quality of life improvement over my old ThinkCentre M910q. The M910q fan was oscillating between 50-100% speed day and night and was driving me crazy. The EQ14 handles the same 8 camera streams at ~25 CPU utilization and is quiet enough for me to not hear it over the ambient noise. 🙂

**Reply by mpking828** [reply]
> The EQ14 runs great also in a nested virtualization setup under Proxmox 9.x (Debian 13 LXC running Docker).
> 
Essentially this was my exact question.

What else are you running on the EQ14?  I'm shooting for HomeAssistant, and maybe something else on there (As dockers).  Are you hitting any performance issues?

**Reply by ristomatti** [reply]
I was considering moving Home Assistant on it, but I think I'll dedicate it to Frigate usage. Now when autumn winds started blowing, my 4 outdoor cameras have so much to process the CPU use gets maxed out sporadically. When the weather is calm, so is the CPU usage. 🙂

But I do now think I should've picked one with an Intel Core CPU instead.

**Comment by cardinjt** [comment]
New Frigate user here... Running on BeeLink EQ14 MiniPC Intel N150 - 2.5G Dual LAN Ethernet ports

Some platform feedback :
- Initial difficulty with Intel GPU hardware acceleration (drivers) under the following OSes:
     Ubuntu 24.04.3 LTS
     Ubuntu 25.04
     Debian 12
- Currently running Debian 13.1 desktop bare metal with "openvino" GPU hardware accel operational
     ffmpeg: hwaccel_args: preset-intel-qsv-h264
     working better than "preset-vaapi"
- Frigate 0.16.2 version
- Two Armcrest 5MP cameras connected on sub LAN off second LAN port. 
  Configured Caddy proxy to allow LAN access to camera native UIs.
- Have not seen any power supply related issues... yet ... although I did have to tweak EQ14 to prevent from
   sleeping , hibernating, under Debian 13 and did set BIOS to startup after power on (as I do on all my servers). 

- Overall initial impression is that system stable and working well to date.

**Reply by ristomatti** [reply]
> Have not seen any power supply related issues... yet ... although I did have to tweak EQ14 to prevent from
sleeping , hibernating, under Debian 13 and did set BIOS to startup after power on (as I do on all my servers).
> Overall initial impression is that system stable and working well to date.

I did all these as well. How long have you been running it? Let's hope your unit does not suffer from this issue. 🤞

Out of curiosity, did you do any tweaks in the CPU performance settings? When Frigate is running, what kind of numbers do you get from `turbostat`? If missing, `turbostat` comes with `linux-cpupower` package.

```
COLS="Core,Avg_MHz,Busy%,Bzy_MHz,TSC_MHz,CoreTmp,PkgTmp,PkgWatt"
sudo turbostat -q -i 3 -n 1 --show "$COLS" | column -t
```

Mine looks like this, currently only 5 camera streams and low activity.

```
Core  Avg_MHz  Busy%  Bzy_MHz  TSC_MHz  CoreTmp  PkgTmp  PkgWatt
-     589      20.92  2815     806      52       52      9.48
0     661      24.03  2750     806      52       52      9.48
1     545      19.24  2832     806      52               
2     604      21.22  2847     806      52               
3     546      19.20  2844     806      52      
```

**Reply by cardinjt** [reply]
I've been running the EQ14 for ~1 month.  Took the first week or so playing OS roulette and tweaking Frigate config.yaml.

Lately have installed and running YOLOv9 models.

Running BIOS version TWEQF003 - no tweaks to CPU performance settings.

2 Active Cameras - CPU usage reported by Frigate runs ~12%

"turbostat" output :


```
Core  Avg_MHz  Busy%  Bzy_MHz  TSC_MHz  CoreTmp  PkgTmp  PkgWatt
-     180      13.42  1340     806      38       38      3.86
0     230      15.95  1444     806      38       38      3.86
1     219      14.50  1511     806      38               
2     131      11.36  1154     806      38               
3     139      11.86  1169     806      38    
```

**Reply by Jimmi61** [reply]
Since Hailo card keep giving problems I switched to system GPU for testing but the performances I get are worse than yours. I have 1 camera only for test purpose, using Yolov4 and Yolov7 models the inference time jumped above 100ms. With Yolov9 **s** the inference is about 25ms but the precisions is low, with **m** the precision is acceptable but the inference is more than 50ms and the CPU usage is more than 30%,:
```
Core  Avg_MHz  Busy%  Bzy_MHz  TSC_MHz  CoreTmp  PkgTmp  PkgWatt
-     493      31.24  1577     806      41       43      4.84
0     546      35.16  1554     806      41       43      4.84
1     409      26.19  1561     806      41
2     403      24.77  1627     806      41
3     613      38.83  1578     806      41
```
I wonder what I can do to reduce it, which other setting I can work on. Here is my config:
```
mqtt:
  enabled: false
  host: homeassistant.local
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 10
    objects:
      person: 15

timestamp_style:
  position: tl
  format: '%H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 4

objects:
  track:
    - person
    - cat
    - dog
    - car

review:
  alerts:
    enabled: true
    labels:
      - car
      - person
      - cat
      - dog
  detections:
    enabled: true
    labels:
      - car
      - person
      - cat
      - dog

motion:
  enabled: true

record:
  enabled: true
  retain:
    days: 0
  alerts:
    retain:
      days: 10
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 10
    pre_capture: 15
    post_capture: 15

detect:
  enabled: true
  stationary:
    interval: 1
    threshold: 20

go2rtc:
  streams:
    CCTV_1:
      - ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.18/cam/realmonitor?channel=1&subtype=0#video=h264#rotate=180

cameras:
  dahua_0:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CCTV_1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog

detectors:
  ov_0:
    type: openvino
    device: GPU

model:
  model_type: yolo-generic
  width: 320 # <--- should match the imgsize set during model export
  height: 320 # <--- should match the imgsize set during model export
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-t-320.onnx
  labelmap_path: /labelmap/coco-80.txt

version: 0.16-0
```
