### DISCUSSION TITLE
Raspberry Pi5 No audio on record (aac transcode)? [Support]:

### DISCUSSION THREAD

**Discussion by laleeroy** [blakeblackshear/frigate#18852] [General Support] [answered]
### Describe the problem you are having

I can configure my camera to set the audio as aac, but it is fixed in 16000hz sample rate so when playing/browsing through recorded footage, the browser just wont load it and the button interface will not show after  clicking the play button.

Setting the audio to G.711 A-Law/PCM A-Law with 8000hz sample rate and adding this flag in gortc `ffmpeg:CAM01#audio=aac` and in ffmpeg `preset-record-generic-audio-aac` I can finally play the recorded footage and I can hear audio aswell in my lxc container but in raspberry pi 5, no sound is being recorded.

### Version

0.15-1

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    CAM01:
      - rtsp://10.1.1.100/live/ch00_0
      - ffmpeg:CAM01#audio=aac
    CAM01_SD:
      - rtsp://10.1.1.100/live/ch00_1
      - ffmpeg:CAM01_SD#audio=aac
    CAM02:
      - rtsp://10.1.1.200/live/ch00_0
      - ffmpeg:CAM02#audio=aac
    CAM02_SD:
      - rtsp://10.1.1.200/live/ch00_1
      - ffmpeg:CAM02_SD#audio=aac
                                                        
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30                                                mode: motion
  export:                                                   timelapse_args: -vf setpts=PTS/60 -r 25
  sync_recordings: true

snapshots:
  enabled: true
  retain:
    default: 30

detect:
  enabled: false

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
  input_args: preset-rtsp-restream

cameras:
  CAM01:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM01
          roles: [record, detect]

    motion:
      mask: 0.676,0,0.67,0.069,1,0.059,1,0

  CAM02:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM02
          roles: [record, detect]

    motion:
      mask: 0.676,0,0.67,0.069,1,0.059,1,0

- version: 0.15-1
```

### Relevant Frigate log output

```shell
No error/warning
```

### Relevant go2rtc log output

```shell
No error/warning
```

### FFprobe output from your camera

```shell
I noticed in system metric page, clicking the info button on my lxc container, it provides data, while in my raspberrypi 5 frigate docker version, it just say error but the camera stream and record works fine, just no audio
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /home/$USER/CCTV;/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - PUID=1000
      - GUID=1000
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

K6s for V380 app

**Comment by hawkeye217** [comment]
Try providing a single stream for each of your cameras, eg:

```
go2rtc:
  streams:
    CAM01:
      - ffmpeg:rtsp://10.1.1.100/live/ch00_0#video=copy#audio=aac
    ...
```

**Reply by laleeroy** [reply]
Hi, I have just tested it now in my raspberrypi, the line you provided works perfectly well in my lxc container from my mini pc but I will attach the logs in my raspberrypi docker install
[frigate-logs.txt](https://github.com/user-attachments/files/20896688/frigate-logs.txt)
[go2rtc-logs.txt](https://github.com/user-attachments/files/20896689/go2rtc-logs.txt)

Also here is my config file in my raspberrypi 

mqtt:
  enabled: false

go2rtc:
  streams:
    CAM01:
      - rtsp://11.1.1.11/live/ch00_1
    CAM01_SD:
      - rtsp://11.1.1.11/live/ch00_0
    CAM02:
      - rtsp://11.1.1.12/live/ch00_1
    CAM02_SD:
      - rtsp://11.1.1.12/live/ch00_0
    CAM03:
      - ffmpeg:rtsp://11.1.1.13/live/ch00_0#video=copy#audio=aac
    CAM03_SD:
      - ffmpeg:rtsp://11.1.1.13/live/ch00_1#video=copy#audio=aac

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
  export:
    timelapse_args: -vf setpts=PTS/60 -r 25
  sync_recordings: true

snapshots:
  enabled: true
  retain:
    default: 30

detect:
  enabled: false
  fps: 5

ffmpeg:
  input_args: preset-rtsp-restream

cameras:
  CAM01:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM01
          roles: [record]

    motion:
      mask:
        - 0.719,0,1,0.003,1,0.076,0.723,0.076
        - 0.128,0.379,0.554,0.33,1,0.322,1,1,0,1,0,0.446
  CAM02:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM02
          roles: [record]

    motion:
      mask:

        - 0.719,0,1,0.003,1,0.076,0.723,0.076
        - 0.216,0.201,-0.009,0.242,0,1,1,1,1,0.965,1,0.5,0.726,0.397,0.622,0.251,0.405,0.16

  CAM03:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM03
          roles: [record]

    live:
      stream_name: CAM03_SD

    motion:
      mask: 0.665,0,1,0,1,0.072,0.658,0.083

version: 0.15-1

**Reply by hawkeye217** [reply, marked as answer]
You can try using ffmpeg 5. Set this in your go2rtc config:

```
go2rtc:
  ffmpeg:
    bin: /usr/lib/ffmpeg/5.0/bin/ffmpeg
  streams:
    ...
```
