### DISCUSSION TITLE
[Config Support]: shares the video

### DISCUSSION THREAD

**Discussion by ops244** [blakeblackshear/frigate#18864] [Config Support]
### Describe the problem you are having

hi, why does he split the video into 3-minute chunks? is there a person (or two) constantly moving around?

### Version

beta-3

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: ******
  user: ******
  password: *******


go2rtc:
  streams:
    camera:
      - rtsp://********/stream1

cameras:
  camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

      hwaccel_args: preset-vaapi
    live:
      streams:
        camera: camera
    motion:
      threshold: 30
      lightning_threshold: 1.0
      contour_area: 10
      improve_contrast: true

    notifications:
      enabled: true
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt


detect:
  width: 1280
  height: 720
  fps: 5
  min_initialized: 1
  max_disappeared: 25

  enabled: true
objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.5

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 0
    mode: motion
  alerts:
    retain:
      days: 5
      mode: motion
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 0
      mode: motion
    pre_capture: 5
    post_capture: 5


logger:
  default: error

ui:
  time_format: 24hour
  date_style: short
  time_style: medium
  strftime_fmt: '%D/%m/%y %H:%M'
version: 0.16-0
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: false
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
```

### Relevant Frigate log output

```shell
no logs
```

### Relevant go2rtc log output

```shell
---------
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
---------
```

### Object Detector

OpenVino

### Any other information that may be helpful

![2025-06-24_21-57-02](https://github.com/user-attachments/assets/a0a4e410-b2b2-437e-a179-c7285ad1be66)
