### DISCUSSION TITLE
[Support]: bad aspect ratio in review panel

### DISCUSSION THREAD

**Discussion by myB0B** [blakeblackshear/frigate#18871] [Camera Support]
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

my camera is 16:9 ratio (720p) but in review panel records are display in 4:3
When I click on a recording, the camera briefly displays in 16:9, but right after, the display switches to 4:3

### Steps to reproduce

1. click on review
2. camera show in 4:3
3.
...

### Version

0.15.1

### Frigate config file

```yaml
cameras:
  Portail:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.x.x:554/user=x&password=x&channel=0&stream=1.sdp
          roles:
            - record
        - path: rtsp://192.168.x.x:554/user=x&password=x&channel=1&stream=1.sdp
          roles:
            - detect
    detect:
      width: 352
      height: 198
      fps: 5
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant Frigate log output

```shell
-
```

### Relevant go2rtc log output

```shell
-
```

### Operating system

Home Assistant OS

### Install method

Home Assistant Add-on

### Network connection

Wired

### Camera make and model

Cheap Chinese camera

### Screenshots of the Frigate UI's System metrics pages

not usefull
