### DISCUSSION TITLE
[Camera Support]: PTZ not working for auto tracking despite on screen controls working

### DISCUSSION THREAD

**Discussion by Nicarim** [blakeblackshear/frigate#18879] [Camera Support] [answered]
### Describe the problem you are having

I've ran the following script: https://gist.github.com/hawkeye217/152a1d4ba80760dac95d46e143d37112

It gets the following output
```
YES - GetServiceCapabilities shows that the camera supports MoveStatus.
YES - MoveStatus is reporting IDLE.
YES - RelativeMove Pan/Tilt (FOV) is supported.
YES - RelativeMove Zoom is supported.
```

Frigate detects the onvif properly and provides on screen controls for panning which do work. 

My camera is `sdt2a200-2f-nb-a-pv`.
![image](https://github.com/user-attachments/assets/87264d19-6577-46cf-937f-d5a4511046e4)

However, neither autotracking, nor automatic calibration works. Even though frigate shows that it is trying to calibrate it - camera doesn't move at all. Same for auto tracking that doesn't seem to work at all - do you have any guidance or recommendation on how to debug that?

(I'm comfortable with Python, so feel free to throw me the source code / snippets to test this out)

### Version

0.16.0-f141b58

### What browser(s) are you using?

Firefox / doesn't matter

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  name_of_your_camera: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://<cut>@<cut>:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - detect
    onvif:
      host: <cut>
      port: 80
      user: admin
      password: <cut>
      tls_insecure: false
      ignore_time_mismatch: true
      autotracking:
        # Optional: enable/disable object autotracking. (default: shown below)
        enabled: true
        calibrate_on_startup: true
        required_zones:
          - test
        movement_weights: 0.0, 1.0, 0.6022210121154785, 0.7134777351092266, 0.027727758499883917,
          0.0
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    zones:
      test:
        coordinates: 0.311,0.079,0.639,0.073,0.621,0.731,0.267,0.758
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: test
version: 0.16-0
detect:
  enabled: true
```

### Relevant Frigate log output

```shell
Pasted in the screenshot.
```

### Relevant go2rtc log output

```shell
Not sure if relevant
```

### FFprobe output from your camera

```shell
Not sure if relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

OpenVino

### Network connection

Wired

### Camera make and model

Dahua sdt2a200-2f-nb-a-pv

### Screenshots of the Frigate UI's System metrics pages

Not relevant I think

**Comment by hawkeye217** [comment]
If the camera is not responding to relative movement commands, this would be an issue with the firmware itself. Some users have reported this with lower end Dahuas.

**Reply by Nicarim** [reply]
But it seems to respond to frigate's UI buttons, so it sort of responds.

**Comment by hawkeye217** [comment]
I'd be curious to see the output of ONVIF debug logs on startup:

```
logger:
  default: info
  logs:
    frigate.ptz: debug
```
