### DISCUSSION TITLE
[Detector Support]: GenAI not updating descriptions at lifetime object end but works manually pushing "regenerate"

### DISCUSSION THREAD

**Discussion by gericho** [blakeblackshear/frigate#18872] [Detector Support]
### Describe the problem you are having

![Screenshot 2025-06-25 100046](https://github.com/user-attachments/assets/7a95acb5-f3d4-4837-b4c9-1b1b97a45d79)
![Screenshot 2025-06-25 100219](https://github.com/user-attachments/assets/19db9ff9-e98a-4367-8042-965ecd98a580)
![Screenshot 2025-06-25 100318](https://github.com/user-attachments/assets/8745a210-a271-49eb-8f0b-e096b81210bd)

1. I'm using:
 [ghcr.io/blakeblackshear/frigate:0.16.0-beta3](url)
2. LocalAI with Moondream2 model on OpenVino

My cofiguration

```
genai: # OPEANAI_BASE_URL in docker compose
  enabled: true
  provider: openai
  api_key: noneed
  model: moondream2-20250414
  prompt: Describe {label} intentions using only 20 words
```

Camera Setup

```
Garage:
    genai:
      enabled: True
      #use_snapshot: True
      #prompt: Describe {label} intentions using only 20 words
      objects:
        - motorcycle
        - person
        - dog
        - cat
        - car
      required_zones:
        - in_garage
        - terrazzo
```

I also attempted to activate the option by setting `use_snapshot: True` and specifying a prompt for each camera, but it didn’t work.

### Version

0.16.0-beta3

### Frigate config file

```yaml
specified above
```

### docker-compose file or Docker CLI command

```yaml
0.16.0-beta3version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    shm_size: "372mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config:/config
      - /home/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD="********"
      - OPENAI_BASE_URL=http://192.168.0.19:8080
```

### Relevant Frigate log output

```shell
no errors
```

### Install method

Docker Compose

### Object Detector

OpenVino

### Screenshots of the Frigate UI's System metrics pages

![Screenshot 2025-06-25 103045](https://github.com/user-attachments/assets/53d210a9-1739-471d-8404-22b6fcb6f577)

**Comment by hawkeye217** [comment]
See this related issue:

https://github.com/blakeblackshear/frigate/discussions/18351

I'm not quite sure how Local AI processes incoming requests, but if parallel requests are not supported, you may run into this issue. It could also be the moondream model itself. You might want to try another model like `llava`.

**Reply by gericho** [reply]
I enabled the LLAMACPP_PARALLEL option since moondream2 is loaded using that backend, as shown in the log:

` INF BackendLoader starting backend=llama-cpp modelID=moondream2-20250414 o.model=moondream2-text-model-f16_ct-vicuna.gguf`

I also checked the LocalAI logs when an event occurs, but the request does not even reach the endpoint. However, it works when I press the "regenerate" button.

**Reply by hawkeye217** [reply]
Frigate does not request a description from your provider until the tracked object's lifecycle has ended. You can enable debug logs to see exactly what Frigate is doing:

```
logger:
  default: info
  logs:
    frigate.embeddings.maintainer: debug
    frigate.genai: debug
```

You can also enable debug images to see what gets sent to your provider:

```
cameras:
  my_camera:
    genai:
      debug_save_thumbnails: true
```

The images will be in `/media/frigate/clips/genai`.

**Reply by gericho** [reply]
> See this related issue:
> 
> #18351
> 
> I'm not quite sure how Local AI processes incoming requests, but if parallel requests are not supported, you may run into this issue. It could also be the moondream model itself. You might want to try another model like `llava`.

After a System Reboot I got some clues:

It doesn’t seem to be the same issue. The LocalAI log level is set to DEBUG, but it appears that Frigate is not sending automated requests to LocalAI. There may be a problem with my Frigate configuration (posted above).

`Frigate does not request a description from your provider until the tracked object's lifecycle has ended.`

Yes, I noticed this as well.

This is the Frigate log

```
2025-06-25 15:56:59.414542250  [2025-06-25 15:56:59] frigate.genai                  DEBUG   : Sending images to genai provider with prompt: Describe person intentions using only 20 words
2025-06-25 15:57:00.370641387  [2025-06-25 15:57:00] frigate.embeddings.maintainer  DEBUG   : Failed to generate description for 1750859808.772252-gsjkce
```
LocalAI logs
`
localai  | 2:04PM DBG GRPC(moondream2-20250414-127.0.0.1:41859): stderr srv    send_error: task id = 25, error: the request exceeds the available context size. try increasing the context size or enable context shift`


The Image received by localAI seems to be HUGE

**Reply by hawkeye217** [reply]
Right, the error indicates that your input is exceeding the available context window size for the moondream with LocalAI.

I'm not familiar with LocalAI but you could try to increase the context size.

If you've enabled debug thumbnails, you can see the images sent in `/media/frigate/clips/genai`.

**Reply by gericho** [reply]
#The images will be in /media/frigate/clips/genai.

I enabled debug thumbnails but I do not have that directory. Since I recently updated to version 0.16.b3, it might be best to recreate the container.

**Reply by hawkeye217** [reply]
Sorry, the correct directory would be `/media/frigate/clips/genai-requests`. Note that `/media/frigate` may be mapped differently based on your docker compose - in your case, it would be `/media/frigate/storage/clips/genai-requests`.

**Reply by gericho** [reply]
```
drwxr-xr-x 2 root root    4096 Jun 20 18:03 cache
drwxr-xr-x 2 root root    4096 Jun 21 09:59 export
drwxr-xr-x 7 root root    4096 Jun 22 11:09 faces
drwxr-xr-x 8 root root    4096 Dec  7  2024 previews
drwxr-xr-x 2 root root  249856 Jun 25 16:15 review
drwxr-xr-x 5 root root    4096 Jun 21 10:01 thumbs
root@frigate160b3://home/frigate/storage/clips#
```
Thank you for your patience, no genai-requests directory unfortunately

**Reply by hawkeye217** [reply]
To confirm - the `debug_save_thumbnails: true` must be applied to the `genai` config *at the camera level*, not at the global level. Is that what you did?

**Reply by gericho** [reply]
```
cameras:
    NordOvest:
    genai:
      enabled: true
      debug_save_thumbnails: true
      #use_snapshot: True
      #prompt: Describe {label} intentions using only 20 words
      objects:
        - person
        - cat
        - dog
        - car
```
Here is the configuration. I hope it is correct.
