### DISCUSSION TITLE
[Support]: Mac mini m4 shows Unable to keep up with recording segments in cache

### DISCUSSION THREAD

**Discussion by ronbruins** [blakeblackshear/frigate#18889] [General Support]
### Describe the problem you are having

I recently purchased a Mac mini M4 as it is supposed to handle Frigate nicely, however I get the mentioned error messages, also as pasted below:

```
warning | 2025-06-26 06:40:13 | frigate.record.maintainer | Unable to keep up with recording segments in cache for balkon. Keeping the 6 most recent segments out of 9 and discarding the rest...
```

I had de debug log enabled and the copied time was < 0.05 seconds writing to a SSD

I reduced the cameras from 4 to 2 and increased the threads to 8

### Version

0.16B3

### What browser(s) are you using?

Safari 

### Frigate config file

```yaml
mqtt:
  enabled: false
  host: 192.168.1.35
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ******
  password: *****

tls:
  enabled: false

ui:
  time_format: 24hour
  date_style: short

logger:
  default: info
  # logs:
  #   frigate.record.maintainer: debug

go2rtc:
  log:
    format: text
    level: error

  streams:
    balkon:
      - rtsp://***:***@192.168.1.123:554/h264Preview_01_main
    balkon_sub:
      - ffmpeg:http://192.168.1.123/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=***&password=***
    voordeur:
      - rtsp://***:***@192.168.1.37:554/h264Preview_01_main
    voordeur_sub:
      - rtsp://***:***@192.168.1.37:554/h264Preview_01_sub

detectors:
  cpu:
    type: cpu
    num_threads: 8

model:
  path: plus://****5b7

snapshots:
  enabled: true
  retain:
    default: 1

detect:
  enabled: true

record:
  enabled: true
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7
objects:
  track:
    - person
    - face
    - license_plate
    - dog
    - cat
    - car
    - amazon
    - fedex
    - ups
    - package
  filters:
    cat:
      min_area: 3000
      threshold: 0.83
    dog:
      min_area: 3000
      threshold: 0.8
    person:
      # min_area: 5500
      threshold: 0.7
    car:
      threshold: 0.8
    face:
      min_score: 0.5

cameras:
#### START BALKON CONFIG ####
  balkon:
    ffmpeg:
      inputs:
        #- path: rtsp://192.168.1.220:8554/balkon
        - path: rtsp://localhost:8554/balkon
          input_args: preset-rtsp-restream
          roles:
            - record
        #- path: rtsp://192.168.1.220:8554/balkon_sub
        - path: rtsp://localhost:8554/balkon_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0.49,0,0.492,0.072,0.641,0.078,0.637,0.009
        - 0,0.433,0.235,0,0.001,0
      threshold: 50
      contour_area: 10
      improve_contrast: false
    objects:
      filters:
        car:
          mask:
            - 0.003,0.437,0,0.581,0.251,0.529,0.715,0.423,1,0.347,0.997,0.24
            - 0.002,0.687,0.341,0.671,0.707,0.642,1,0.561,1,0.683,1,1,0.305,1,0,1
            - 0,0.433,0.235,0,0.001,0.004
            - 0.832,0.005,0.816,0.167,0.912,0.314,0.919,0.005
            - 0.198,0.068,0.327,0.077,0.326,0.006,0.234,0.001
      mask: 0,0.433,0.235,0,0.001,0.004
    zones:
      weglinks:
        coordinates: 0.003,0.511,0.002,0.687,0.51,0.58,0.478,0.413
        loitering_time: 0
      wegrechts:
        coordinates: 0.483,0.418,0.512,0.584,0.999,0.453,0.997,0.293
        loitering_time: 0

  voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/voordeur
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/voordeur_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    motion:
      mask: 0.773,0.005,0.774,0.073,0.924,0.071,0.924,0.005
      threshold: 50
      contour_area: 10
      improve_contrast: true
    zones:
      fietsen:
        coordinates: 0.261,0.625,0.565,0.734,0.598,0.044,0.488,0.04
        loitering_time: 0
        inertia: 3
      pad:
        coordinates: 0.234,0.592,0.145,0.863,0.417,0.999,0.529,0.995,0.57,0.736,0.256,0.627,0.263,0.6
        loitering_time: 0
        inertia: 3
      stoepje_voordeur:
        coordinates: 0.578,0.698,0.78,0.758,0.779,0.999,0.533,0.995
        loitering_time: 0
      trottoir:
        coordinates: 
          0.039,0.995,0.003,0.998,0.002,0.712,0.189,0.362,0.403,0,0.454,0.008,0.384,0.14,0.208,0.508,0.227,0.612,0.144,0.848,0.102,0.786
        loitering_time: 0
      weg:
        coordinates: 0.003,0.701,0.397,0,0.207,0,0,0.274
        loitering_time: 0
    objects:
      filters:
        car:
          mask:
            - 0.117,0.941,0.003,0.671,0.262,0.142,0.374,0.169
            - 0.172,0,0.298,0,0,0.348,0,0.171
        cat:
          mask: 0.485,0.769,0.628,0.804,0.652,0.496,0.469,0.466

version: 0.16-0
lpr:
  enabled: false
classification:
  bird:
    enabled: false
```

### Relevant Frigate log output

```shell
warning | 2025-06-26 06:40:13 | frigate.record.maintainer | Unable to keep up with recording segments in cache for balkon. Keeping the 6 most recent segments out of 9 and discarding the rest...
warning | 2025-06-26 06:40:18 | frigate.record.maintainer | Unable to keep up with recording segments in cache for balkon. Keeping the 6 most recent segments out of 10 and discarding the rest...
warning | 2025-06-26 06:40:18 | frigate.record.maintainer | Unable to keep up with recording segments in cache for voordeur. Keeping the 6 most recent segments out of 10 and discarding the rest...
warning | 2025-06-26 06:40:23 | frigate.record.maintainer | Unable to keep up with recording segments in cache for balkon. Keeping the 6 most recent segments out of 10 and discarding the rest...
warning | 2025-06-26 06:40:23 | frigate.record.maintainer | Unable to keep up with recording segments in cache for voordeur. Keeping the 6 most recent segments out of 9 and discarding the rest...
warning | 2025-06-26 06:40:28 | frigate.record.maintainer | Unable to keep up with recording segments in cache for voordeur. Keeping the 6 most recent segments out of 10 and discarding the rest...
warning | 2025-06-26 06:40:28 | frigate.record.maintainer | Unable to keep up with recording segments in cache for balkon. Keeping the 6 most recent segments out of 9 and discarding the rest...
```

### Relevant go2rtc log output

```shell
info | 2025-06-26 06:38:57 | startup | Preparing new go2rtc config...
info | 2025-06-26 06:38:58 | startup | Starting go2rtc...
info | 2025-06-26 06:39:07 | startup | Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.108_146fee5)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --disable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=aarch64-ffbuild-linux-gnu-gcc --cxx=aarch64-ffbuild-linux-gnu-g++ --ar=aarch64-ffbuild-linux-gnu-gcc-ar --ranlib=aarch64-ffbuild-linux-gnu-gcc-ranlib --nm=aarch64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, rtsp, from 'rtsp://admin:5mei2006@192.168.1.37:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000625, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"cameras":{"balkon":{"camera_fps":5.0,"process_fps":5.0,"skipped_fps":0.0,"detection_fps":3.1,"detection_enabled":true,"pid":595,"capture_pid":604,"ffmpeg_pid":621,"audio_rms":0.0,"audio_dBFS":0.0},"voordeur":{"camera_fps":5.0,"process_fps":4.9,"skipped_fps":0.1,"detection_fps":0.5,"detection_enabled":true,"pid":597,"capture_pid":629,"ffmpeg_pid":636,"audio_rms":0.0,"audio_dBFS":0.0}},"detectors":{"cpu":{"inference_speed":8.56,"detection_start":0.0,"pid":551}},"detection_fps":3.6,"embeddings":{},"cpu_usages":{"frigate.full_system":{"cpu":"15.5","mem":"37.1"},"1":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service"},"17":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6-linux-init-shutdownd"},"18":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -d3 -c /run/s6/basedir -g 3000 -C -B"},"27":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync"},"28":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate"},"29":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx"},"30":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise nginx-log"},"31":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-oneshot-runner"},"32":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-log"},"33":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc-healthcheck"},"34":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise go2rtc"},"35":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise s6rc-fdholder"},"36":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise certsync-log"},"37":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-supervise frigate-log"},"48":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6-2.13.2.0/command/s6-fdholderd -1 -n 256 -i data/rules"},"49":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"},"91":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"},"100":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"},"102":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/certsync"},"103":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"},"127":{"cpu":"3.6","cpu_average":"3","mem":"0.4","cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"},"134":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user go2rtc-healthcheck"},"136":{"cpu":"0.5","cpu_average":"1","mem":"4.2","cmdline":"python3 -u -m frigate"},"143":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"nginx: master process nginx"},"199":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"200":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"201":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"202":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: worker process"},"203":{"cpu":"0.0","cpu_average":"0","mem":"0.1","cmdline":"nginx: cache manager process"},"337":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"bash ./run.user certsync"},"390":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 9999"},"401":{"cpu":"0.0","cpu_average":"0","mem":"2.3","cmdline":"python3 -u -m frigate"},"526":{"cpu":"0.3","cpu_average":"0","mem":"2.8","cmdline":"frigate.recording_manager"},"528":{"cpu":"0.1","cpu_average":"0","mem":"2.5","cmdline":"frigate.review_segment_manager"},"551":{"cpu":"15.5","cpu_average":"3","mem":"2.7","cmdline":"frigate.detector.cpu "},"574":{"cpu":"0.5","cpu_average":"0","mem":"2.6","cmdline":"frigate.output       "},"595":{"cpu":"0.9","cpu_average":"0","mem":"2.7","cmdline":"frigate.process:balkon"},"597":{"cpu":"0.5","cpu_average":"0","mem":"2.7","cmdline":"frigate.process:voordeur"},"604":{"cpu":"0.3","cpu_average":"0","mem":"2.6","cmdline":"frigate.capture:balkon"},"621":{"cpu":"1.9","cpu_average":"1","mem":"0.5","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-f141b58 -rtsp_transport tcp -timeout 10000000 -i rtsp://localhost:8554/balkon_sub -r 5 -vf fps=5,scale=896:512 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"628":{"cpu":"0.3","cpu_average":"0","mem":"0.4","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://192.168.1.123/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/1338d0a8a44db7b6dd18a3f7f0c529ed"},"629":{"cpu":"0.3","cpu_average":"0","mem":"2.6","cmdline":"frigate.capture:voordeur"},"636":{"cpu":"1.3","cpu_average":"1","mem":"0.6","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-f141b58 -rtsp_transport tcp -timeout 10000000 -i rtsp://localhost:8554/voordeur_sub -r 5 -vf fps=5,scale=896:512 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"},"641":{"cpu":"0.7","cpu_average":"0","mem":"0.6","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-f141b58 -rtsp_transport tcp -timeout 10000000 -i rtsp://localhost:8554/voordeur -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/voordeur@%Y%m%d%H%M%S%z.mp4"},"643":{"cpu":"0.9","cpu_average":"0","mem":"0.6","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.16.0-f141b58 -rtsp_transport tcp -timeout 10000000 -i rtsp://localhost:8554/balkon -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/balkon@%Y%m%d%H%M%S%z.mp4"},"658":{"cpu":"0.0","cpu_average":"0","mem":"0.3","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"665":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 896x512 -i pipe: -threads 1 -f mpegts -s 1260x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"672":{"cpu":"0.0","cpu_average":"0","mem":"0.2","cmdline":"/usr/lib/ffmpeg/7.0/bin/ffmpeg -threads 1 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -threads 1 -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"},"6685":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sh"},"7268":{"cpu":"0.0","cpu_average":"0","mem":"0.0","cmdline":"sleep 30s"}},"service":{"uptime":356,"version":"0.16.0-f141b58","latest_version":"0.15.1","storage":{"/media/frigate/recordings":{"total":953836.0,"used":718197.8,"free":235638.2,"mount_type":"virtiofs"},"/media/frigate/clips":{"total":953836.0,"used":718197.8,"free":235638.2,"mount_type":"virtiofs"},"/tmp/cache":{"total":1907.4,"used":17.8,"free":1889.5,"mount_type":"tmpfs"},"/dev/shm":{"total":256.0,"used":67.0,"free":189.0,"mount_type":"tmpfs"}},"temperatures":{},"last_updated":1750920304},"processes":{"recording":{"pid":526},"review_segment":{"pid":528},"go2rtc":{"pid":127}}}
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate_016B
    privileged: true # this may not be necessary for all setups
    network_mode: "host"
    restart: unless-stopped
#    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3-standard-arm64
    shm_size: "256mb" # update for your cameras based on calculation above
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
    #  - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/ron/Docker/Frigate/config:/config
      - /Volumes/SanDisk1TB/Frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
#    ports:
#      - "8971:8971"
#      - "5000:5000"
#      - "1984:1984"
#      - "8554:8554" # RTSP feeds
#      - "8555:8555/tcp" # WebRTC over tcp
#      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "52c9************92bfb"
      #LIBVA_DRIVER_NAME: "radeonsi"
```

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

reeling track mix

### Screenshots of the Frigate UI's System metrics pages

<img width="2006" alt="image" src="https://github.com/user-attachments/assets/af840ad9-2af3-4068-aa2a-b6dfa8cab3be" />
<img width="1975" alt="image" src="https://github.com/user-attachments/assets/9b477b57-8cb7-41d2-b922-8403c7107b31" />
<img width="1995" alt="image" src="https://github.com/user-attachments/assets/0237876d-a84f-459e-aac0-105ba7d6cfbe" />
