### DISCUSSION TITLE
[Support]: Getting the snapshot out from mqtt in Home Assistant automation

### DISCUSSION THREAD

**Discussion by enoquelights** [blakeblackshear/frigate#18919] [General Support]
### Describe the problem you are having

I am trying to get the encoded image out of the mqtt with in an Home assistant Automation. Following format in the docs: 
frigate/<camera_name>/<object_name>/snapshot

My code is below

```
alias: FrigateSnapshotTrigger
description: Triggered when a snapshot is published
triggers:
  - topic: frigate/reolink_doorbell/person/snapshot
    trigger: mqtt
actions:
  - variables:
      snapshot_base64: "{{ trigger.payload }}"
mode: single
```
It doesnt trigger. frigate/events does trigger, so there isnt a problem with connection.

The name is the same my config for the camera. which is working fine taking snapshot that i can see in the folder:

```
reolink_doorbell:
      - /usr/lib/ffmpeg/7.0/bin/ffmpeg:https://192.168.40.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.40.2:554/h264Preview_01_main#audio=pcm#audio=volume
```

 Am I missing something?

### Version

0.15.1

### Frigate config file

```yaml
reolink_doorbell:
      - /usr/lib/ffmpeg/7.0/bin/ffmpeg:https://192.168.40.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - rtsp://admin:password@192.168.40.2:554/h264Preview_01_main#audio=pcm#audio=volume
```

### Relevant Frigate log output

```shell
None from the automation.
```

### Relevant go2rtc log output

```shell
Not having an issue with go2rtc
```

### FFprobe output from your camera

```shell
No issues getting video.
```

### Install method

Home Assistant Add-on

### docker-compose file or Docker CLI command

```yaml
No issue with the platform.
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink PoE Doorbell
