### DISCUSSION TITLE
[Support]: Explore video is only 1 sec instead of the expected time

### DISCUSSION THREAD

**Discussion by bgmastermind** [blakeblackshear/frigate#18911] [General Support]
### Describe the problem you are having

When viewing video from the explore menu the video is only 1 sec long. When viewing the same from review it is as expected. 
I tried bumping pre_capture and post_capture to 20, but it did not help. Object lifecycle shows it as expected as well. Attached capture with the issue
[screen-capture.webm](https://github.com/user-attachments/assets/0ceaf845-f07a-4784-94f3-769c669fe2b0)

I have many recordings from this camera that are shorter than expected. But i also have some with normal length. Can it be related to the car speed?
I also have two other cameras further on that road, and they rarely have such issue, but they are filming more sideways than than that camera. 

### Version

0.16.0-f141b58 but it was the same on 0.14

### What browser(s) are you using?

Latest Chrome or Firefox

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: mqtt
  user: frigate
  password: password

go2rtc:
  streams:
    camera_1_record:
      - rtsp://user:password@xxx.xxx.xxx.30:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    camera_1_detect:
      - rtsp://user:password@xxx.xxx.xxx.30:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_2
    camera_2_record:
      - rtsp://user:password@xxx.xxx.xxx.31:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    camera_2_detect:
      - rtsp://user:password@xxx.xxx.xxx.31:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_2
    camera_3_record:
      - rtsp://user:password@xxx.xxx.xxx.32:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
    camera_3_detect:
      - rtsp://user:password@xxx.xxx.xxx.32:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_2

cameras:
  camera_1:
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 6
    record:
      detections:
        pre_capture: 20
        post_capture: 5
      alerts:
        pre_capture: 20
        post_capture: 5
    enabled: true
    face_recognition:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_1_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera_1_record
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: false
    motion:
      threshold: 30
      contour_area: 20
      lightning_threshold: 0.6
      improve_contrast: true
      mask: 
        0.551,0.317,0.566,0.438,0.71,0.776,1,0.934,1,0,0.491,0,0,0,0,0.409,0.067,0.39,0.107,0.226,0.209,0.274,0.306,0.236,0.508,0.18
    mqtt:
      timestamp: true
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    zones:
      camera_1_road:
        coordinates: 
          0.474,0.302,0.52,0.303,0.548,0.364,0.544,0.451,0.514,0.616,0.396,1,0,1,0,0.718,0.234,0.562,0.344,0.453
        loitering_time: 0
        inertia: 1
  camera_2:
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 6
      annotation_offset: -500
    enabled: true
    face_recognition:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_2_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera_2_record
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: false
    motion:
      threshold: 30
      contour_area: 25
      improve_contrast: true
      mask: 0.207,0,0,0,0,0.064,0.184,0.144,0.439,0.144,0.653,0.111,0.85,0.187,1,0.193,1,0
    mqtt:
      timestamp: true
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    objects:
      filters:
        car:
          mask: 
            0.311,0.223,0.371,0.202,0.409,0.191,0.435,0.199,0.455,0.308,0.407,0.336,0.364,0.331,0.309,0.331,0.311,0.287
  camera_3:
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 6
      annotation_offset: -500
    enabled: true
    face_recognition:
      enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_3_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera_3_record
          input_args: preset-rtsp-restream
          roles:
            - record
    audio:
      enabled: false
    motion:
      threshold: 30
      contour_area: 15
      improve_contrast: true
      mask: 0,0,0,0.077,0.313,0.072,0.313,0
    mqtt:
      timestamp: true
      bounding_box: false
      crop: true
      quality: 100
      height: 500
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 6
objects:
  track:
    - car
    - person
    - bicycle
    - cat
    - dog
    - motorcycle
    - horse
    - bear
motion:
  enabled: true
record:
  enabled: true
  expire_interval: 60
  sync_recordings: true
  # Retention settings for general recordings
  retain:
    # Number of days to save recordings
    days: 90
    # Save only recordings with movement
    mode: active_objects
  alerts:
    # Seconds of recording before movement is registered, to also be saved
    pre_capture: 15
    # Seconds of recording after movement is disappeared, to also be saved
    post_capture: 5
    retain:
      # Number of days to retain/save recordings
      days: 90
      # This mode saves all recording segments with active/moving objects
      mode: active_objects
  detections:
    pre_capture: 15
    post_capture: 5
    retain:
      days: 90
      mode: active_objects

face_recognition:
  enabled: true
  model_size: small
  detection_threshold: 0.5
lpr:
  enabled: true
  device: CPU
  model_size: small
snapshots:
  quality: 80
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 90
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
detectors:
  coral1:
    type: edgetpu
    device: pci:0
ui:
  time_format: 24hour
  date_style: medium
  time_style: medium
live:
  height: 720
  quality: 1
timestamp_style:
  position: tl
  format: '%d.%m.%Y %H:%M:%S'
  effect: shadow
version: 0.16-0
camera_groups:
  Gore:
    order: 1
    icon: LuWebcam
    cameras:
      - camera_1
      - camera_2
      - camera_3
semantic_search:
  enabled: false
  model_size: small
classification:
  bird:
    enabled: false
```

### Relevant Frigate log output

```shell
not required
```

### Relevant go2rtc log output

```shell
not required
```

### FFprobe output from your camera

```shell
not required
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:0.16.0-beta3
    #runtime: nvidia
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #       - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/d1/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - LIBVA_DRIVER_NAME=i965
    networks:
      - nvr-network
networks:
    nvr-network:
        external: true
        name: nvr-network
        driver: bridge
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

hikvision DS-2CD1643G2-LIZU

### Screenshots of the Frigate UI's System metrics pages

![image](https://github.com/user-attachments/assets/4be50f3f-285c-400f-8649-6f5fd10bc859)
