### DISCUSSION TITLE
How are retain/motion, reviews, alert pre/post_capture and explore connected?

### DISCUSSION THREAD

**Discussion by jkoopmann** [blakeblackshear/frigate#18929] [Ask A Question] [answered]
Hi,

so my record setting is:

```
record:
  enabled: true
  retain:
    days: 2
    mode: motion  # Retain recordings with motion detected for 3 days
  alerts:
    pre_capture: 15
    post_capture: 15
    retain:
      days: 30
      mode: all
  detections:
    pre_capture: 15
    post_capture: 15
    retain:
      days: 14
      mode: all
```

What I notice is that the recordings often do not seem to honor the pre/post_capture setting so the recording starts pretty much when the detected object is first seen and stops earlier than 15 seconds after leaving the picture. I can only suspect that this is due to no motion being detected anymore and the underlying stream stopping. Is this correct?

In one case the video starts at 2:34:13, the object that alerted was detected 2:34:19. The object according to the lifecycle left the picture 2:34:22 and the video stops at 2:34:25. So it had 6 seconds pre and 3 seconds post... That is surprising to me. 

My dream would have been that the stream is always there and while detection etc. starts only when movement is detected the 15 seconds would have been gotten from some sort of "stream cache". While that is difficult to achieve for the pre_capture phase it sounds easier for post_capture if the recording/streaming does not stop when motion stop IF there is an active alert/detection present.

Then today I looked at the reviews for one of my cameras because I was searching for something specific. I was surprised to see that no reviews older than 2d existed even though plenty of events were there. Is this because the review page relies on the motion retention?

In the "Explore" part things were existent and this is fine (I was just surprised and want to understand how things connect to each other).

Any shed of light or help on how to improve this in case I am just once more too stupid would be greatly appreciated!

Regards
 JP
