### DISCUSSION TITLE
Config File - Use Local RTSP Streams

### DISCUSSION THREAD

**Discussion by strickdd** [blakeblackshear/frigate#18944] [Ask A Question]
NOTE: sensitive info scrubbed, but the config works as indicated.

I am trying to use the local go2rtc streams for my recordings/dashboards. I was table to get it working with my Reolink camera (FrontDoorDoorbell), but not on an Anpviz camera. I am able to view all the go2rtc streams from my laptop using VLC and the IP address of my Frigate host.

Frigate:
![image](https://github.com/user-attachments/assets/1b616673-bca7-4eb9-83ed-f2ac8b6d15bc)

VLC:
![image](https://github.com/user-attachments/assets/182aeba2-c739-4875-885c-5a3163b66f69)

This works fine, but as I understand it, it is creating new ffmpeg processes instead of sharing a common stream:
```Yaml
mqtt:
  enabled: true
  host: XXXX # HomeAssistant's MQTT
  port: 1883
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_USER_PASSWORD}'
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264 # preset-vaapi

go2rtc:
  streams:
    Backyard:
      - ffmpeg:rtsp://{FRIGATE_NVRUSER}:{FRIGATE_NVRUSER_PASSWORD}@{FRIGATE_CAMERA_IPPREFIX}1:554/stream0#video=copy#audio=copy
    Backyard_Sub:
      - ffmpeg:rtsp://{FRIGATE_NVRUSER}:{FRIGATE_NVRUSER_PASSWORD}@{FRIGATE_CAMERA_IPPREFIX}1:554/stream1
    FrontDoorDoorbell:
      - ffmpeg:http://{FRIGATE_CAMERA_IPPREFIX}20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_NVRUSER}&password={FRIGATE_NVRUSER_PASSWORD}#video=copy#audio=copy#audio=opus
      - rtsp://{FRIGATE_CAMERA_IPPREFIX}20/Preview_01_sub
    FrontDoorDoorbell_Sub:
      - ffmpeg:http://{FRIGATE_CAMERA_IPPREFIX}20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_NVRUSER}&password={FRIGATE_NVRUSER_PASSWORD}

record:
  enabled: true
  retain:
    days: 10
    mode: motion
  alerts:
    retain:
      days: 10
  detections:
    retain:
      days: 10
snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 10

telemetry:
  version_check: true

cameras:
  Backyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://{FRIGATE_NVRUSER}:{FRIGATE_NVRUSER_PASSWORD}@{FRIGATE_CAMERA_IPPREFIX}1:554/stream0     # High res stream
          roles:
            - record
        - path: 
            rtsp://{FRIGATE_NVRUSER}:{FRIGATE_NVRUSER_PASSWORD}@{FRIGATE_CAMERA_IPPREFIX}1:554/stream1     # Low res stream
          roles:
            - detect
    live:
      stream_name: Backyard
    detect:
      width: 480
      height: 360
    motion:
      mask:
        - 0.467,1,1,1,1,0.894,0.477,0.889
        - 0.822,0,0.815,0.447,0.777,0.515,0.724,0.656,0.76,0.697,0.809,0.705,0.873,0.557,0.891,0
        - 0,0,0,0.16,0.192,0.14,0.293,0.093,0.413,0.06,0.48,0.054,0.504,0
    ui:
      order: 1
  FrontDoorDoorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/FrontDoorDoorbell # High res stream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/FrontDoorDoorbell_Sub # Low res stream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: FrontDoorDoorbell
    detect:
      width: 480
      height: 640
    motion:
      mask:
        - 0.303,1,1,1,1,0.948,0.324,0.95
        - 0.005,0.256,0.372,0.238,0.367,0.309,0.223,0.548,0.088,0.543,0.002,0.371
    ui:
      order: 2

version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: small
camera_groups:
  Birdseye:
    order: 1
    icon: LuCastle
    cameras: birdseye

```

When I change the `Backyard:` camera section to the following, it shows "No frames have been received, check error logs". on the dashboard for the Backyard camera. The FrontDoorDoorbell continues to work as expected. VLC still works for both cameras

Frigate:
![image](https://github.com/user-attachments/assets/29e4dc88-5d48-4020-83aa-cb0da9983bfc)

VLC:
![image](https://github.com/user-attachments/assets/dd43c9d2-20e2-4eaa-8b29-66189a533ee1)

```Yaml
Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard # High res stream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Backyard_Sub # Low res stream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: Backyard
    detect:
      width: 480
      height: 360
    motion:
      mask:
        - 0.467,1,1,1,1,0.894,0.477,0.889
        - 0.822,0,0.815,0.447,0.777,0.515,0.724,0.656,0.76,0.697,0.809,0.705,0.873,0.557,0.891,0
        - 0,0,0,0.16,0.192,0.14,0.293,0.093,0.413,0.06,0.48,0.054,0.504,0
    ui:
      order: 1
```

Here are the error logs. This confuses me since I can view the stream via VLC but not on the dashboard. Ignore the other camera names, I removed all other cameras to reduce complexity of my config and make testing easier. What I'm seeing happens the same with the other cameras or not.

[frigate-logs.txt](https://github.com/user-attachments/files/20986213/frigate-logs.txt)

Any thoughts? I feel I'm missing something obvious, but I've copied and pasted the working version "FrontDoorDoorbell" and replaced with the name of the other camera "Backyard".

Thanks in advance,
strickdd

**Comment by hawkeye217** [comment]
Since you're using go2rtc, you'll want to look at the go2rtc logs for why this might be happening.

And since you're using the ffmpeg module with go2rtc, you can enable trace logs:

```
go2rtc:
  log:
    exec: trace
  streams:
    ...
```

See the FAQ about why your camera might still be working in VLC: https://docs.frigate.video/troubleshooting/faqs/#my-rtsp-stream-works-fine-in-vlc-but-it-does-not-work-when-i-put-the-same-url-in-my-frigate-config-is-this-a-bug
