### DISCUSSION TITLE
Does Birdseye support 2 cameras only?

### DISCUSSION THREAD

**Discussion by szaske** [blakeblackshear/frigate#2036] [Ask A Question]
Birdseye works for me, but I think I have the configuration messed up. Does Birdseye mode support 2 cameras only? There is a large black area beneath my two cameras in Birdseye mode, like it wants to display 4 cameras. In that area is some strange white shape. Is there a way to remove this black area?
<img width="300" alt="Screen Shot 2021-10-17 at 9 46 21 AM" src="https://user-images.githubusercontent.com/19757740/137636926-0a043ad8-63df-47ee-aa0f-dde30e74ea29.png">
a?

**Comment by Minglarn** [comment]
Show us you birdseye settings...
This is my settings.. Shows all 9 cams if there are any motion..
```

birdseye:
  enabled: true
  height: 480
  width: 640
#  mode: objects
#  mode: continuous
  mode: motion
  quality: 1
```

**Reply by stamandr** [reply]
Is this a global setting, or do you have to specify it for each camera ?

**Reply by Minglarn** [reply]
Global settings...

**Reply by stamandr** [reply]
thanks...

**Reply by szaske** [reply]
My birdseye section is:
```
birdseye:
  enabled: True
  width: 3840
  height: 2160
  mode: continuous
```
My guess is that they assume a minimum of 2 rows of cameras...and with 2 cameras I only need one row. When looking at Birdseye it does appear like it wants to show 4 cameras since this bottom black area appears to be the same size as my first row.  I tried changing the height to 1080 to see if that would get rid of the black area, but it didn't. I have no idea why this white shape is appearing.
