### DISCUSSION TITLE
Help for config.yml & zone question

### DISCUSSION THREAD

**Discussion by McPaHa** [blakeblackshear/frigate#2039] [Ask A Question]
Hi!

Couple of questions:

How and where add events & snapshots required zones if wanted that:

- at "parking_area" detects "everything" instead of car
- at " etupihaan_sisääntulo" (entrance) detect & save clips and snapshots every objects which tracked and
- everywhere else which are not inside of those zones are saving clips and snapshots which are tracked

If somebody helps me - please tell me correct place and indention to those lines (ver 0.9.1)

I am asking this because I am not sure about limitations about "https://docs.frigate.video/configuration/zones". I am not sure that if I am defining zones - does camera saving clips and snapshot still everywhere else outside of zones? (might be stupid question but I am not native Englishspeaking so sometimes hard to understand)

Also could somebody add output arg line here which is default but camera is saving audio also?

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.1.60
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: xxx

 birdseye:
   enabled: True
   width: 1280
   height: 720
   quality: 8    
   mode: objects

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

record:
  enabled: true
  retain_days: 10
  events:
    retain:
      default: 14

snapshots:
  enabled: True
  bounding_box: True
  crop: false
  retain:
    default: 14
      
cameras:
  etupiha:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.1.67:554/Streaming/Channels/1
          roles:
            - rtmp
            - detect
            - record
    detect:    
      width: 1920
      height: 1080
      fps: 5
    zones:
      parking_area_etupiha:
        coordinates: 236,655,97,1080,630,1080,915,640,648,486,425,418
        objects:
          - person
          - dog
          - cat
      etupihaan_sisääntulo:
        coordinates: 360,429,789,446,904,255,507,254
        objects:
          - person
          - dog
          - cat
          - car

    motion:
      mask:
        - 357,387,179,0,659,0,673,128
    rtmp:
      enabled: True    
    objects:
      track:
        - person
        - dog
        - cat
        - car
```

**Comment by McPaHa** [comment]
Could somebody help me stupid ;)

camera:
  record:
    events:
      required_zones:
        - entire_yard
        - front_yard_street
  snapshots:
    required_zones:
      - entire_yard
      - front_yard_street

Where to add required zones if "parking_area_etupiha" save clips&snapshots only from person, dog & cat and entrance "etupihan_sisääntulo" saving clips&snapshots from "every objects I like to save. And what happens outside of these 2 zones? Does frigate saving clips & snapshot "normally".

**Comment by blakeblackshear** [comment]
Do you mind posting a screenshot of your camera? It is hard to visualize what you are describing.

**Reply by McPaHa** [reply]
Sure... my bad...

**Comment by McPaHa** [comment]
Here (where car is) is zone "parking_area_etupiha" and yellow line zone is: "etupihaan_sisääntulo"

So what I'd like to achieve is that at zone where car is located frigate detect & save clips & snapshots (but not car object) and everywhere else including "etupihan_sisääntulo" aka entrance to from yard everything.

What I don't know / understand is that if I put required zones to the config.yml - does frigate still saving events, clips & snapshots everywhere else? Like that picture from my summer cottage... Those "1" zones I don't want car detects but all other objects and everywhere every other objects.

![image](https://user-images.githubusercontent.com/36406452/138300524-7f92b728-c61d-4cd2-8599-1becbd9e2aa9.png)

And same thing is at my summer cottage:

Where zones "1" are places where cars parked and "2" is where cars coming in...

![image](https://user-images.githubusercontent.com/36406452/138301552-0d84ffe9-6017-49c8-9fbd-d8ffafe94b9e.png)

**Reply by blakeblackshear** [reply]
So at your summer cottage, you only need zones for the areas where cars enter, not where cars are parked. You also need one more for everywhere else for the remaining object types. Make sense?

```yaml
cameras:
  summer_cottage:
    ...
    zones:
      car_entrance_area_1:
        coordinates: ...
        objects:
          - car
      car_entrance_area_2:
        coordinates: ...
        objects:
          - car
      active_area:
        coordinates: ...
        objects:
          - person
          - dog
          - cat
    snapshots:
      required_zones:
        - car_entrance_area_1
        - car_entrance_area_2
        - active_area
    record:
      ...
      events:
        required_zones:
          - car_entrance_area_1
          - car_entrance_area_2
          - active_area
 
    objects:
      track:
        - person
        - dog
        - cat
        - car
```
