### DISCUSSION TITLE
Zones Issue

### DISCUSSION THREAD

**Discussion by stamandr** [blakeblackshear/frigate#2041] [Ask A Question]
How do I stop detecting cars ( top of car picture ). I understand that with zones you can specify the area for detection and the objects. I keep picking up cars passing by on the road. Am I missing something ?  Thanks in advance....

I have the following in my config
```yaml
snapshots:
    required_zones:
      -driveway_only
zones:
driveway_only:
        coordinates: 398,38,450,292,704,302,704,480,0,480,0,233,190,40
        objects:
          - car
 ```
 
![Car](https://user-images.githubusercontent.com/51379504/137640613-0598fdaf-1fe6-43ff-a79a-5168fdff11e0.jpg)
![Zones](https://user-images.githubusercontent.com/51379504/137640618-ade9f35b-4c67-4361-b830-a3b3f666df21.jpg)
