### DISCUSSION TITLE
0.9.0-rc4-amd64 config review

### DISCUSSION THREAD

**Discussion by tlundste** [blakeblackshear/frigate#2113] [Ask A Question] [answered]
I recently started over, going from the stable-amd64 renaming my existing frigate folder in my mount-folder, and creating a new frigate folder (and media and config) for 0.9.0-rc4-amd64.  I used the old config as a starting point, and kept restarting the image/container watching the docker logs, and making config changes along the way until I stopped getting errors.  I had to re-do all my masks and zones to support the higher resolution (previous "detect" was at the lower res stream from the camera, and only clips were recorded from the high-res stream).  It seems to be working except I am not recording any streams, and therefore, when it indicates there is a clip to view, it doesn't work.  There is nothing in my ./recordings folder, and the only thing in the ./clips folder is .png and .jpg files.
There is only one camera in my config, so far.
1.  What do I have set wrong to get recordings to start recording?
2. Other than the fact I don't have a tensor device, and am using CPU, what else is wrong, or out of place in my config?
3. Is the documentation on the site geared toward the old stable-xxx release, or 0.9.0 release?  Is there an indication that feature/option is available in one and not the other?

```
mqtt:
  host: <my-cam-ip>
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
cameras:
  frontdoor:
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
        rtmp: -c copy -f flv -c:v copy -c:a aac
      inputs:
        - path: rtsp://my-user:my-pw@<my-cam-ip>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - dog
        - person
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    motion:
      mask:
        - 693,619,1195,647,1623,635,1636,446,1729,386,1598,97,1682,0,1625,0,1485,0,1265,226,889,94,540,302,462,394
    zones:
      fntdr_drvwy:
        coordinates: 890,741,622,807,612,713,720,709
      fntdr_prch:
        coordinates: 191,1080,139,812,1140,1080
      fntdr_strt:
        coordinates: 1366,735,1421,681,609,672,618,704,913,730
      fntdr_wlkwy:
        coordinates: 962,814,1228,1055,701,1019,776,914,787,837,641,812,722,779,743,776
      fntdr_yard:
        coordinates: 1576,1080,1202,1080,1044,902,894,795,736,783,888,730,1612,791```

**Comment by shred86** [comment]
Couple things I'm seeing:

- The `global_args:`, `hwaccel_args: []`, `input_args:` and `output_args:` are all set to the [default settings](https://docs.frigate.video/configuration/index) so it is unnecessary to have this in your config file. It's just preference, but I think it's less things to mess up by only defining the settings that differ from default.
- I don't see anything for `record:` defined. By default, it's set to `false`. You can see the default settings in the [docs here](https://docs.frigate.video/configuration/index/).

The documentation is updated for 0.90+. You can see the [release notes](https://github.com/blakeblackshear/frigate/releases) to get an idea of what are the break changes from pre-0.90 though.

**Reply by tlundste** [reply]
Thank you @shred86.
Regarding the four things I have a default levels... in my old config, I read that all of them had to be listed even if I wasn't overriding them, if I was overriding one.  I must have had to remove the one thing I was overriding to get the service to come up, at some point.  Still not  exactly sure what that was.  I'll leave those statements in there until I can figure that part out if it's not hurting anything.

Reading in the docs you linked about the configuration file... I'm still a little confused.
--- "can be overridden at the camera level"
What does that mean?  Does "record:" start at (indent to) the same level as mqtt, detectors and cameras? or underneath cameras at the same level as the camera name? or underneath the name, at the same level as ffmpeg, detect, and objects? or underneath inputs, or one of the other ones at that level?  In my original config, I had "record:" listed several times in the config, admittedly it was commented out a few times while I tried to figure out how this thing worked.  I had to remove all of the uncommented "record" statements, as those were causing problems starting up the service on 0.90.  I then removed the commented lines out before posting it here.
Can you please help me with the "record:" statement, again... describe where it goes, or maybe copy a bit of my code, and show me where in the code (indented to where, too) it is supposed to go?
Thank you very much for the assist!

**Comment by shred86** [comment, marked as answer]
In regards to the default settings, they're definitely not required. Even if you only want to override say, `input_args:` for some reason, you would only need to specify those parameter and you can leave out `global_args:`, `hwaccel_args:` and `input_args:`. However, you would have to specify everything you want on the `input_args:` line. In other words, by default it's set to `input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1`, and if you wanted to add another parameter, you would have to list all those out in addition to the new parameter. Otherwise, if you just list the new parameter you want, the rest of those defaults will not be applied since you overrode the default. Hopefully that makes sense. Looking at your config, you're using the default settings so they can safely be removed.

There's many settings that can be defined globally (applies to all cameras) or for a specific camera. If you define something both globally and for a specific camera, the camera settings will apply as they override the global settings. That's what's meant by "can be overriden at the camera level".

Anything that is defined globally should start with no spaces so it's not nested under anything else (just how YAML works... might be helpful to google a video on YAML if you're unfamiliar with it as it can save a lot of headaches). In your case with one camera, `record:` can be specified globally or at the camera level. If you only have one camera, it doesn't really matter if you define it at the global or camera level. When you have multiple cameras, it's best to define things the global level if it applies to all cameras so you don't have to specify the same settings multiple times.

Here's an example of how I would probably set up your config file (realize I removed the default ffmpeg stuff):

````
mqtt:
  host: <my-cam-ip>

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://my-user:my-pw@<my-cam-ip>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record    
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - dog
        - person
        - car
    record:
      enabled: True
      retain_days: 7
      events:
        retain:
          default: 14
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    motion:
      mask:
        - 693,619,1195,647,1623,635,1636,446,1729,386,1598,97,1682,0,1625,0,1485,0,1265,226,889,94,540,302,462,394
    zones:
      fntdr_drvwy:
        coordinates: 890,741,622,807,612,713,720,709
      fntdr_prch:
        coordinates: 191,1080,139,812,1140,1080
      fntdr_strt:
        coordinates: 1366,735,1421,681,609,672,618,704,913,730
      fntdr_wlkwy:
        coordinates: 962,814,1228,1055,701,1019,776,914,787,837,641,812,722,779,743,776
      fntdr_yard:
        coordinates: 1576,1080,1202,1080,1044,902,894,795,736,783,888,730,1612,791```
````

You can see I added the `record:` at the camera level. If you wanted to specify `detect:`, `record:` and `snapshots:` at the global level, your config would look something like this:

````
mqtt:
  host: <my-cam-ip>

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://my-user:my-pw@<my-cam-ip>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record    
    objects:
      track:
        - dog
        - person
        - car
    motion:
      mask:
        - 693,619,1195,647,1623,635,1636,446,1729,386,1598,97,1682,0,1625,0,1485,0,1265,226,889,94,540,302,462,394
    zones:
      fntdr_drvwy:
        coordinates: 890,741,622,807,612,713,720,709
      fntdr_prch:
        coordinates: 191,1080,139,812,1140,1080
      fntdr_strt:
        coordinates: 1366,735,1421,681,609,672,618,704,913,730
      fntdr_wlkwy:
        coordinates: 962,814,1228,1055,701,1019,776,914,787,837,641,812,722,779,743,776
      fntdr_yard:
        coordinates: 1576,1080,1202,1080,1044,902,894,795,736,783,888,730,1612,791```

detect:
  width: 1920
  height: 1080
  fps: 5

record:
  enabled: True
  retain_days: 7
  events:
    retain:
      default: 14

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7
````
