### DISCUSSION TITLE
Hard time getting igpu or gpu going in proxmox lxc

### DISCUSSION THREAD

**Discussion by mkono87** [blakeblackshear/frigate#2189] [Ask A Question]
Iv been looking at the numerous posts here and been going at it for hours but I just cant seem any hw acceleration going. I do not have a Coral so atm im interested in just using it for processing video. Im using an 3th gen intel system (i5-3570) and I also have a older gpu in it. Im using debian 10 standard lxc When I use lscpu on promox I get
```
root@proxmox:~# lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller #1 (rev 04)
00:16.2 IDE interface: Intel Corporation 7 Series/C210 Series Chipset Family IDE-r Controller (rev 04)
00:16.3 Serial controller: Intel Corporation 7 Series/C210 Series Chipset Family KT Controller (rev 04)
00:19.0 Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation Q77 Express Chipset LPC Controller (rev 04)
00:1f.2 RAID bus controller: Intel Corporation SATA Controller [RAID mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos XT [Radeon HD 7470/8470 / R5 235/310 OEM]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Caicos HDMI Audio [Radeon HD 6450 / 7450/8450/8490 OEM / R5 230/235/235X OEM]

```

The gpu is the only thing that shows up for vga. I figured that there would be an entry for the gpu. Here are the rest of my configs
```
version: "3.7"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    privileged: true
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/appdata/frigate/config.yml:/config/config.yml
      - /mnt/frigate:/media/frigate
      - /mnt/frigate:/db

      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/dri/renderD128 /dev/dri/renderD128
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
 ```

I started using the LIBVA after when then trying to get the AMD passed through instead.

```
mqtt:
  host: 192.168.0.30
  user: xxxxxxxx
  password: xxxxxxxxx
database:
  path: /db/frigate.db

objects:
  track:
    - person

live:
  height: 1440

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.0.21:554/h264Preview_01_main
          roles:
            - rtmp
            - detect
       hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    detect:
      width: 2560
      height: 1440
      fps: 10
    snapshots:
      enabled: true
    record:
      enabled: true
      retain_days: 3
      events:
        retain:
          default: 10
    motion:
      mask:
        - 0,0,815,0,988,0,1212,0,1280,0,1280,0,1280,94,950,50,502,49,0,130
        

  Deck:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.0.22:554/h264Preview_01_main
          roles:
            - rtmp
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p

    detect:
      width: 2560
      height: 1440
      fps: 10
    snapshots:
      enabled: true
    record:
      enabled: true
      retain_days: 3
      events:
        retain:
          default: 10

```

```
arch: amd64
cores: 4
features: nesting=1
hostname: Docker
memory: 4096
mp0: /mnt/frigate,mp=/mnt/frigate
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=0A:D0:B4:F4:B8:F4,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: local:102/vm-102-disk-0.raw,size=64G
swap: 4096
lxc.cgroup.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:

```
Any help would be be much appreciated. I had it working with the gpu in a VM but it just made sense to use lxc instead.
