### DISCUSSION TITLE
Cache in wrong directory

### DISCUSSION THREAD

**Discussion by mcondren** [blakeblackshear/frigate#2220] [Ask A Question]
Hi All. 

I wanted to ask here first to see if I am doing anything wrong. I noticed my disk filled up and the culprit was 200GB in the docker overlay for frigate, which I assume is the default cache folder location. 

I’m confused as to why it’s in that location.  I had created a ram disk as specified in the docs and put this in my docker-compose file. 

volumes:                                                                                      
   - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear                           
      target: /tmp/ramdisk                                                                      
      tmpfs:                                                                                    
        size: 1000000000      

however, that is empty and it’s dumping hundreds of gigs in 

du -h --max-depth=1 2> /dev/null | sort -hr | tail -n +2 | head
201G     ./merged
200G    ./diff
8.0K    ./work
❯ pwd
/var/lib/docker/overlay2/a5ab7a4b2509061bb8ed9a56f7e7d346f64c03a4291f18a396a3c8ca1208a669

And /tmp/ramdisk is empty

**Comment by blakeblackshear** [comment]
Can you post your full compose file?

**Reply by mcondren** [reply]
> Can you post your full compose file?

```
version: "3.6"
services:
  Frigate:
    container_name: Frigate
    domainname: XXXX
    hostname: frigate
    image: blakeblackshear/frigate:stable-amd64
    networks:
      macvlan:
        ipv4_address: XXXXXX
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m
    #privileged: true
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - frigate:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/ramdisk
        tmpfs:
          size: 1000000000
        
```
