### DISCUSSION TITLE
Possible to use substream for detection but mainstream for live view?

### DISCUSSION THREAD

**Discussion by jonadis** [blakeblackshear/frigate#2225] [Ask A Question] [answered]
I think I've got things setup so detection uses the lower resolution substream and the recordings use the full resolution mainstream, but it looks like the live view and birdseye view use the lower resolution substream.  Is it possible to leave the detector using the substream but have the live view use the mainstream?

```
  frontporch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nunya@10.0.71.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:nunya@10.0.71.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
```
