### DISCUSSION TITLE
Multiple Zone config shows incorrect zone within Frigate

### DISCUSSION THREAD

**Discussion by chvvkumar** [blakeblackshear/frigate#2292] [Ask A Question]
Any idea how I can fix this?

Problem Camera: Upstairs

Mask I created:
![image](https://user-images.githubusercontent.com/16548147/142708195-47c4560e-1dfe-43db-9f28-4bf5cb6e1849.png)

What shows up in Frigate:
![image](https://user-images.githubusercontent.com/16548147/142708204-48f90773-8374-4afa-a064-4126c2b0b2e3.png)

Config file:

```
mqtt:
  host: 192.168.1.250
  user: DVES_USER
  password: PASSWORD

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

record:
  enabled: True
  retain_days: 2
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects: &objects
      - airplane
      - apple
      - backpack
      - banana
      - baseball bat
      - baseball glove
      - bear
      - bed
      - bench
      - bicycle
      - bird
      - boat
      - book
      - bottle
      - bowl
      - broccoli
      - bus
      - cake
      - car
      - car
      - carrot
      - cat
      - cell phone
      - chair
      - clock
      - couch
      - cow
      - cup
      - dining table
      - dog
      - donut
      - elephant
      - fire hydrant
      - fork
      - frisbee
      - giraffe
      - hair drier
      - handbag
      - horse
      - hot dog
      - keyboard
      - kite
      - knife
      - laptop
      - microwave
      - motorcycle
      - mouse
      - orange
      - oven
      - parking meter
      - person
      - pizza
      - potted plant
      - refrigerator
      - remote
      - sandwich
      - scissors
      - sheep
      - sink
      - skateboard
      - skis
      - snowboard
      - spoon
      - sports ball
      - stop sign
      - suitcase
      - surfboard
      - teddy bear
      - tennis racket
      - tie
      - toaster
      - toilet
      - toothbrush
      - traffic light
      - train
      - tv
      - umbrella
      - vase
      - wine glass
      - zebra
    required_zones: 
      - upstairs_top
      - upstairs_bottom
      - backyard
      - driveway
    retain:
      default: 4
  
snapshots:
  enabled: True
  height: 350
  timestamp: True
  bounding_box: False
  crop: False
  retain:
    default: 4

cameras:
  Front Yard:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@192.168.1.135/live
          roles:
            - detect
            - rtmp
    zones:
      driveway:
        coordinates: 325,682,638,695,919,694,1404,677,1920,809,1920,1080,0,1080,0,641
        objects: *objects
    snapshots:
      required_zones:
        - driveway
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

  Back Yard:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@192.168.1.134/live
          roles:
            - detect
            - rtmp
    zones:
      backyard:
        coordinates: 415,1080,284,653,402,577,701,543,926,522,1033,525,1639,973,1920,454,1920,0,0,0,0,1080
        objects: *objects
    snapshots:
      required_zones:
        - backyard
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

  Back Yard Basement:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@192.168.1.232/live
          roles:
            - detect
            - rtmp
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []
      
  Upstairs:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@192.168.1.175/live
          roles:
            - detect
            - rtmp
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []
    zones:
      upstairs_top:
        coordinates: 1916,624,1709,629,1514,644,1274,642,964,641,754,629,567,620,365,620,203,593,4,581,1,3,1917,0
        objects: *objects
      upstairs_bottom:
        coordinates: 2,827,196,910,447,969,876,1024,1222,1030,1546,996,1782,942,1917,898,1912,1081,1351,1080,4,1080
        objects: *objects
    snapshots:
      required_zones:
        - upstairs_top
        - upstairs_bottom

  Basement:
    ffmpeg:
      inputs:
        - path: rtsp://USER:password@reolinkzoom.lan:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []


objects:
  track:
    - airplane
    - apple
    - backpack
    - banana
    - baseball bat
    - baseball glove
    - bear
    - bed
    - bench
    - bicycle
    - bird
    - boat
    - book
    - bottle
    - bowl
    - broccoli
    - bus
    - cake
    - car
    - car
    - carrot
    - cat
    - cell phone
    - chair
    - clock
    - couch
    - cow
    - cup
    - dining table
    - dog
    - donut
    - elephant
    - fire hydrant
    - fork
    - frisbee
    - giraffe
    - hair drier
    - handbag
    - horse
    - hot dog
    - keyboard
    - kite
    - knife
    - laptop
    - microwave
    - motorcycle
    - mouse
    - orange
    - oven
    - parking meter
    - person
    - pizza
    - potted plant
    - refrigerator
    - remote
    - sandwich
    - scissors
    - sheep
    - sink
    - skateboard
    - skis
    - snowboard
    - spoon
    - sports ball
    - stop sign
    - suitcase
    - surfboard
    - teddy bear
    - tennis racket
    - tie
    - toaster
    - toilet
    - toothbrush
    - traffic light
    - train
    - tv
    - umbrella
    - vase
    - wine glass
    - zebra

```
