### DISCUSSION TITLE
Full HD in Frigate Live page

### DISCUSSION THREAD

**Discussion by alfwro13** [blakeblackshear/frigate#2306] [Ask A Question] [answered]
Hi,
I am in the process o migrating from zoneminder to frigate. All my cams are setup with two streams one in full HD with 15fps (stream0), 2nd  720x480 with 5 fps (stream1)

my camera section of the config looks as follows:
```
cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.123.123:554/stream0?username=admin&password=password
          roles:
            - record
            - rtmp
        - path: rtsp://192.168.123.123:554/stream1?username=admin&password=password
          roles:
            - detect
    detect:
      width: 720
      height: 480
```

With this config when I go to my Frigate web portal and browse to the Camera cam1 I get stream1 (729x480 5fps). How do I change that so I get the full HD stream0 ?
Thanks
