### DISCUSSION TITLE
http streams

### DISCUSSION THREAD

**Discussion by alfwro13** [blakeblackshear/frigate#2312] [Ask A Question] [answered]
I have couple of old IP cameras that only have http streams (I believe that they are mjpg outputs).
In frigate I have this config:
```
  cam1:
    ffmpeg:
      inputs:
        - path: http://admin:password@192.168.123.123/video.cgi
          roles:
            - detect
            - record
            - rtmp
```
but all I get is just a green box in the GUI. This makes me think that they are not supported or I need additional config in order to receive that stream.

frigate log output:
```
[2021-11-23 09:13:34] frigate.app                    INFO    : Capture process started for cam1: 228
[2021-11-23 09:13:40] frigate.video                  INFO    : cam1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-11-23 09:13:40] frigate.video                  INFO    : cam1: ffmpeg process is not running. exiting capture thread...
```

**Comment by blakeblackshear** [comment, marked as answer]
https://docs.frigate.video/configuration/camera_specific#mjpeg-cameras

**Reply by vertexgamer** [reply]
```
mqtt:
  host: 192.168.1.88
  user: user
  password: password
  
cameras:
  camera: # <------ Name the camera
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://192.168.1.84/
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1600
      height: 1200
      fps: 5
    record:
      enabled: True
```
m8 any tips for esp32? i tried many variations but none of them were working
