### DISCUSSION TITLE
What's wrong with my camera definition?

### DISCUSSION THREAD

**Discussion by ksignorini** [blakeblackshear/frigate#2323] [Ask A Question] [answered]
What am I doing wrong here? I've tried "clips:" and now "record:" but the record section is invalid.

```
cameras:
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://user:usernamehere@10.0.0.9:8554/Video-113
          roles: 
            - detect
            - clips
    objects:
       track:
         - person
         - cat
         - dog
    record:
      enabled: true
      events:
        retain: 2
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
```

**Comment by ksignorini** [comment, marked as answer]
Nevermind. Got it. Retain in the record: section was wrong.

```
record:
  enabled: true
  events:
    retain:
      default: 2
```
