### DISCUSSION TITLE
Home Assistant allowlist_external_urls issue

### DISCUSSION THREAD

**Discussion by mpfl** [blakeblackshear/frigate#2332] [Ask A Question]
I have a Pi camera pointing at my front door and want to receive Pushover notifications when a person is detected. So far, so good.

The issue is when I try to attach an image in the notification. Even though I have the internal network URL of my Frigate instance allowlisted, Home Assistant insists that it isn't when I make the service call.

Snippet from configuration.yaml:

```yaml
homeassistant:
  allowlist_external_urls:
    - 'http://192.168.1.4:5000/api/events'
```

Snippet from automation:

```yaml
action:
    - service: notify.mpfl
      data_template:
        message: "Someone's at the door"
        title: "Object detected"
        data:
          sound: bugle
          url: "https://private"
          attachment: 'http://192.168.1.4:5000/api/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=0&crop=1'
```

I'm running Frigate and Home Assistant in docker containers, on separate docker networks. Frigate port 5000 is being exposed via docker. Home Assistant port 8123 is being routed by Traefik.

I've tried shortening the allowlisted URL down to `http://192.168.1.4`,  but that gives me no love either.

Does anyone have any ideas?
