### DISCUSSION TITLE
Cats being detected as persons

### DISCUSSION THREAD

**Discussion by ronrath** [blakeblackshear/frigate#2394] [Ask A Question]
Person detection is working great and the system consistently detects the cats, however, it detects the cats as people.

Version 2.3 Running in supervised install of HA on Pi with Raspian OS
Camera is Amcrest IP8M-T2599EW

Frigate config file:
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://<UID:PWD@<IP address:port>/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://<UID:PWD@<IP address:port>/live
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          threshold: 0.5
    motion:
      mask:
        - 700,0,700,46,515,46,515,0
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 5

birdseye:
  enabled: True
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 3
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
```
