### DISCUSSION TITLE
environment_vars not being migrated into frigate container environment? Help!

### DISCUSSION THREAD

**Discussion by dspears0809** [blakeblackshear/frigate#2422] [Ask A Question]
Hi, all,

I have been spending way too much time trying to get my LIBVA_DRIVER_NAME set for Radeon hardware acceleration...

```
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
  FRIGATE_LIBVA_DRIVER_NAME: radeonsi
  MYTEST: value
```

None of these shows up in my "env" listing in the frigate container after a container restart. 

What am I doing wrong?
