### DISCUSSION TITLE
Error 02

### DISCUSSION THREAD

**Discussion by pr0bar** [blakeblackshear/frigate#2454] [Ask A Question] [answered]
Hello,

I keep getting an error 02 when trying to start up Frigate NVR on a pi 4. Wasn't having much luck looking up this particular error. Below is the error and config.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-15 21:36:59] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-12-15 21:36:59] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-12-15 21:36:59] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-12-15 21:36:59] peewee_migrate                 INFO    : There is nothing to migrate
[Errno -2] Name or service not known
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```
mqtt:
  host: 192.168.1.10:1883

detectors:
  coral:
    type: cpu

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.30:554/live0
          roles:
            - detect
```
