### DISCUSSION TITLE
Camera w/H265 main and H264 sub, record main but use sub for event page?

### DISCUSSION THREAD

**Discussion by transplier** [blakeblackshear/frigate#2470] [Ask A Question] [answered]
Howdy, finally upgraded beyond my 0.8.4 installation. I'm having some trouble with the event viewer if someone has a moment to point me in a direction.

My cameras provide 2 streams, a 4k H.265 `main` stream and a low resolution H.264 `sub` stream. I cannot change the codec.

My intent is to record `main` to disk for archival purposes (I view it with other tools) and use the `sub` stream for detection and clips. This worked well because the Frigate clips UI got the H.264 stream which is playable in the browser. This worked fine in 0.8.4.

Now that "clips" are gone, it appears to me that it is no longer possible to use the sub stream for event display while also recording the main stream to disk. Is this true? Is there another way of restoring video playback capability to the event page that doesn't involve re-encoding on the fly? My machine would definitely not keep up reencoding multiple 4k streams to H.264, not to mention the power use.

One workaround I was thinking is defining each camera twice - one using the `sub` stream just for detection and events with zero retain_days, and another using the `main` stream with no detection role. Maybe there's a better way?

**Comment by blakeblackshear** [comment, marked as answer]
You can setup a duplicate camera and use ffmpeg to generate a low-res black stream as the detect stream. This should use minimal CPU.

```yaml
cameras:
  duplicate_for_record_only:
    ffmpeg:
      inputs:
        - path: /dev/zero
          input_args: -re -s 640x480 -f rawvideo -pix_fmt rgb24 -r 1
          roles:
            - detect
        - path: rtsp://<high_res>
          roles:
            - record
    detect:
        enabled: False
        height: 480
        width: 640
        fps: 1
```
