### DISCUSSION TITLE
Request: Pre-selected live view in Birdseye mode

### DISCUSSION THREAD

**Discussion by kongjudas** [blakeblackshear/frigate#2489] [Ideas]
I would love to see the "Basic" camera or any pre-selected camera in the Birdseye display. That way I can use cameras or webcams from my porch, alpine centre, the cottage or any camera worth having up when there's no detection going on locally. Thanks, by the way, for a fantastic HA integration!

**Comment by hugalafutro** [comment]
put 
```
birdseye:
  mode: continuous
```
in your config.yml it will make birdeye show all your cams live in a grid. Can't do single cam, can do only these: 
```
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
```
