### DISCUSSION TITLE
Help me understand why my recordings don't save a clip for event

### DISCUSSION THREAD

**Discussion by hugalafutro** [blakeblackshear/frigate#2498] [Ask A Question] [answered]
Hi, as the title says, everything I set up in following config works, apart from no clips for events being created. The continuous recording is working, but when I open any event and press Download Clip there's nothing, and the whole Recordings menu is empty. 

I have a sub stream (640*352) set up for rtmp and detect, and main stream (1920x1072) set for record and rtmp. I enabled record: for the main stream camera with retain set to 30 days. I presume I made mistake / misunderstood the config, but I can't figure out where. If it's relevant, the main camera has only recordings enabled, the sub camera has snapshots and detect enabled.
```
cameras:
  outside:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv
      hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128
      inputs:
        - path: rtmp://outside.lan/bcs/channel0_main.bcs?channel=0&stream=0&user=[REDACTED]&password=[REDACTED]
          roles:
            - record
            - rtmp
    best_image_timeout: 10
    detect:
      enabled: False
      width: 1920
      height: 1072
      fps: 10
    mqtt:
      enabled: False
    snapshots:
      enabled: False
    live:
      height: 720
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 30
          objects:
            person: 30

  outside_cast:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv
      hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128
      inputs:
        - path: rtmp://outside.lan/bcs/channel0_sub.bcs?channel=0&stream=0&user=[REDACTED]&password=[REDACTED]
          roles:
            - rtmp
            - detect
    motion:
      mask:
        - 0,360,640,360,640,254,640,163,479,32,640,57,640,0,366,0,595,219,467,283,189,276,140,276,76,160,37,160,203,32,205,0,0,0
    detect:
      width: 640
      height: 352
      fps: 7
      max_disappeared: 35
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 439,126,450,171,410,166,405,126,371,33,394,33
    snapshots:
      enabled: True
    mqtt:
      enabled: False
    live:
      height: 352
```
Thanks for any insights!
