### DISCUSSION TITLE
Mini PC for HA and Frigate - anyone firsthand recommendations?

### DISCUSSION THREAD

**Discussion by gulo101** [blakeblackshear/frigate#2511] [General]
Hello,
Does anyone have firsthand experience with sub $300 mini PC that can take M.2 Coral card and will run Home Assistant?  I am currently running HA on PI4 and Frigate as Docker on a separate Unraid PC. I ordered USB Coral but who knows if it will ever get here. I would like to move my HA to a mini PC and ideally grab M.2 coral and run it there as well. 

I am looking for something like J4125 CPU. Ideally I could put in regular SATA SSD and use M.2 slot for the Coral. 8 GB of RAM. 

I saw Odyssey Blue mentioned, but looks like it’s not really sold anymore, and several reviewers on Amazon mentioned RAM going bad. 

Does anyone own a unit that meets the criteria and is actually confirmed to work with coral board? Thank you!

**Comment by shred86** [comment]
I’m running the Odyssey X86 Blue and that’s what I would recommend. I was one of the folks that wrote the review about bad RAM, but the second one I ordered has been running flawlessly with Debian 11, ten docker containers (HA, Frigate, Unifi Controller, etc.), one internal 2.5” HDD and one external 2.5” HDD. I went through several mini PCs in an attempt to find the ideal HA + Frigate solution with M.2 PCI-E support for the EdgeTPU and in the end, the Odyssey ended up being the best solution. Others out there, like AWOW, has an M.2 PCI-E slot but will not work with the EdgeTPU and the CPU runs significantly hotter (cheaper heatsink). 

You can order them directly from Seeed Studio or other vendors sell them like Mouser electronics. You do need the additional case extension, hard drive mounting plate and SATA cable if you plan on adding an internal drive.

**Reply by gulo101** [reply]
Thanks, would it be this one? [https://www.seeedstudio.com/Odyssey-Blue-J4105-128GB-p-4668.html](url) Looks like it comes with 128 GB SSD. Is there a version that has everything I need to add SATA SSD, but without actual drive so I can put in my own?

Which specific version of Coral do I get to use with it? Thank you!

**Reply by shred86** [reply]
Yeah, that’s it. It does come with an M.2 SATA SSD. There is no version that I could find which comes with the stackable middle frame, 2.5” mounting plate and SATA cable. These have to be ordered separately:

https://www.seeedstudio.com/re-computer-stackable-case-p-4679.html
https://www.seeedstudio.com/re-computer-2-5-inch-SSD-and-HDD-mounting-bracket-p-4703.html
https://www.seeedstudio.com/SATA-26AWG-200mm-p-4680.html

If you’re in the U.S., I would highly recommend ordering from mouser.com as you’ll get everything much faster. If you just type in the SKU of those part numbers on Seeed’s website into Google or Mouser’s website, you’ll find them.

I’m using the [M.2 B+M Key Edge TPU](https://coral.ai/products/m2-accelerator-bm).

**Reply by gulo101** [reply]
Thank you, I found all the parts on Mouser. However the M.2 B+M Coral seems to be discontinued? It's  not only showing out of stock everywhere (like the USB one) but it actually says discontinued? I will assume that I cannot use any one of the ones listed here? [https://www.mouser.com/new/google][(url)](https://www.mouser.com/new/google)

**Reply by shred86** [reply]
Hm, that is strange. I don't see any postings on their [official page](https://coral.ai/products/m2-accelerator-bm) about the product being discontinued or reaching EOL. You're correct though, you need the M.2 B/M version.

**Reply by gulo101** [reply]
Thanks, I was able to place order for B/M version on one website with ship date in January....we'll see. How are you running your dockers? Are you suing something like ProxMox? Thank you for your help btw. I did also end up ordering the Odyssey Blue on Mouser. The J4105 model seems discontinued, but they now offer J4125 version which appears to be exactly the same thing with slightly higher CPU clock speed.

**Reply by shred86** [reply]
Nice! I really hope they don't discontinue the B/M key version. Might need to pick one up as a back up just in case. :)

I'm just running Docker on a bare metal Debian 11 install. I also have the J4125 version which has been great. I'm sitting around 20-22% CPU usage with 4x 4MP cameras, a fairly extensive Home Assistant setup, Unifi Controller, PiHole, Samba, etc.

I actually documented some notes for setting up my home server [here](https://github.com/shred86/smart-home/blob/main/server-setup.md). I wrote it mostly for my reference (i.e. not really intended to be a tutorial) so if something doesn't make sense, feel free to ask and I can clarify. I don't have my docker compose posted on my GitHub repo but I'll post it below for reference.

The first thing I did with the Odyssey X86 is [update the BIOS](https://wiki.seeedstudio.com/ODYSSEY-X86J4105-Installing-OS/#how-to-upgrade-the-bios), then installed Debian 11.

Some additional info on my setup to help make sense of the docker compose: 
- My main home network is 172.16.16.0/24.
- I use docker named volumes for all my persistent data (could just as easily use a bind mount, which is actually probably easier).
- I specify the IP address with my ports because I also have my home server connected to my camera network on a separate VLAN. I made a [post about that here](https://github.com/blakeblackshear/frigate/discussions/2524).

````
services:
  frigate:
    image: blakeblackshear/frigate:0.10.0-beta6-amd64
    container_name: frigate
    restart: unless-stopped
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
    volumes:
      - /home/username/frigate:/media/frigate
      - /home/username/frigate/config.yml:/config/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 172.16.16.1:5000:5000
      - 172.16.16.1:1935:1935 # RTMP feeds
  
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - heimdall:/config
    ports:
      - 172.16.16.1:7080:80
      - 172.16.16.1:7443:443

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro

  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8090
      - TZ=America/Los_Angeles
    volumes:
      - homebridge:/homebridge

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - 172.16.16.1:1883:1883
      - 172.16.16.1:9001:9001

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
      PIHOLE_DNS: "1.1.1.1;1.0.0.1"
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    ports:
      - 172.16.16.1:53:53/tcp
      - 172.16.16.1:53:53/udp
      - 172.16.16.1:67:67/udp
      - 172.16.16.1:80:80/tcp
    
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 172.16.16.1:8000:8000
      - 172.16.16.1:9000:9000

  samba:
    image: mbentley/timemachine:smb
    container_name: samba
    restart: unless-stopped
    environment:
      - PASSWORD=<redacted>
      - SET_PERMISSIONS=true
    volumes:
      - /home/username/backup:/opt/timemachine
      - timemachine-var-lib-samba:/var/lib/samba
      - timemachine-var-cache-samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
    ports:
      - 172.16.16.1:137:137/udp
      - 172.16.16.1:138:138/udp
      - 172.16.16.1:139:139
      - 172.16.16.1:445:445
    
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - unifi-controller:/config
    ports:
      - 172.16.16.1:10001:10001/udp # Required for AP discovery
      - 172.16.16.1:8880:8880/tcp # Unifi guest portal HTTP redirect port
      - 172.16.16.1:8843:8843/tcp # Unifi guest portal HTTPS redirect port
      - 172.16.16.1:8443:8443/tcp # Unifi web admin port
      - 172.16.16.1:8080:8080/tcp # Required for device communication
      - 172.16.16.1:6789:6789/tcp # For mobile throughput test
      - 172.16.16.1:3478:3478/udp # Unifi STUN port
      - 172.16.16.1:1900:1900/udp # Required for Make controller discoverable on L2 network option

  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwavejs2mqtt
    restart: unless-stopped
    environment:
      - SESSION_SECRET=<redacted>
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_<redacted>-if00-port0:/dev/zwave
    volumes:
      - zwavejs2mqtt:/usr/src/app/store
    ports:
      - 8091:8091
      - 3000:3000

volumes:
  heimdall:
    external: true
  homeassistant:
    external: true
  homebridge:
    external: true
  mosquitto-config:
    external: true
  mosquitto-data:
    external: true
  mosquitto-log:
    external: true
  pihole:
    external: true
  dnsmasq:
    external: true
  portainer_data:
    external: true
  timemachine-var-lib-samba:
    external: true
  timemachine-var-cache-samba:
    external: true
  timemachine-run-samba:
    external: true
  unifi-controller:
    external: true
  zwavejs2mqtt:
    external: true
````
