### DISCUSSION TITLE
[Errno 99] Cannot assign requested address

### DISCUSSION THREAD

**Discussion by alexturpin** [blakeblackshear/frigate#2595] [Ask A Question] [answered]
Hey all,

Trying to setup frigate with docker and I get this in the container logs when I restart it:

```
frigate          | 2022-01-06T06:21:58.542524232Z [s6-finish] sending all processes the KILL signal and exiting.
frigate          | 2022-01-06T06:22:45.237179095Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate          | 2022-01-06T06:22:45.270347420Z [s6-init] ensuring user provided files have correct perms...exited 0.
frigate          | 2022-01-06T06:22:45.271675519Z [fix-attrs.d] applying ownership & permissions fixes...
frigate          | 2022-01-06T06:22:45.272600914Z [fix-attrs.d] done.
frigate          | 2022-01-06T06:22:45.273605789Z [cont-init.d] executing container initialization scripts...
frigate          | 2022-01-06T06:22:45.274376136Z [cont-init.d] done.
frigate          | 2022-01-06T06:22:45.275249500Z [services.d] starting services
frigate          | 2022-01-06T06:22:45.280370462Z [services.d] done.
frigate          | 2022-01-06T06:22:45.925114944Z [2022-01-06 06:22:45] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
frigate          | 2022-01-06T06:22:45.945836531Z Starting migrations
frigate          | 2022-01-06T06:22:45.945884861Z [2022-01-06 06:22:45] peewee_migrate                 INFO    : Starting migrations
frigate          | 2022-01-06T06:22:45.949269013Z There is nothing to migrate
frigate          | 2022-01-06T06:22:45.949312524Z [2022-01-06 06:22:45] peewee_migrate                 INFO    : There is nothing to migrate
frigate          | 2022-01-06T06:22:45.953164682Z [Errno 99] Cannot assign requested address
frigate          | 2022-01-06T06:22:46.058453203Z [cmd] python3 exited 1
frigate          | 2022-01-06T06:22:46.063672571Z [cont-finish.d] executing container finish scripts...
frigate          | 2022-01-06T06:22:46.064433350Z [cont-finish.d] done.
frigate          | 2022-01-06T06:22:46.064889483Z [s6-finish] waiting for services.
frigate          | 2022-01-06T06:22:46.308156089Z [s6-finish] sending all processes the TERM signal.
frigate          | 2022-01-06T06:22:49.314671813Z [s6-finish] sending all processes the KILL signal and exiting.
```

config.yml

```
mqtt:
  host: localhost
  port: 1883
```

Relevant part of the docker-compose.yml
```
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: unless-stopped
    shm_size: "128mb"
    volumes:
      - ${ROOT}/config/frigate/config.yml:/config/config.yml:ro
      - ${ROOT}/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # HTTP
      - "1935:1935" # RTMP
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}   
```

I also know that the MQTT broker is running correctly on that port because zwavejs2mqtt is connecting to it, and so can I with MQTT explorer. I can also stream my configured RTSP streams with VLC without a problem.

Any ideas? Thanks!
