### DISCUSSION TITLE
Home Assitant Install-Configuration error

### DISCUSSION THREAD

**Discussion by mani94321** [blakeblackshear/frigate#2615] [Ask A Question] [answered]
I install home assistant add on ,below is my frigate.yml code
```
mqtt:
  host: 192.168.30.30
  port: 1883
  user: mqtt_username
  password: mqtt passord

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://login:passowrd@192.168.20.110:554/Streaming/Channels/102/
          roles:
            - detect
  detect:
    width: 640
    height: 480
    fps: 6
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

When is start the add on, i get following error while starting it. I am not able to start the frigate add on. Tried many times restarting but same issue. Can anyone help.

Home assistant supervisor version: supervisor-2021.12.2 
on Raspberri Pi4, 4gb

![Error](https://user-images.githubusercontent.com/62215453/148692316-94797519-f83c-410f-b613-bb30d0d80b39.JPG)

**Comment by shred86** [comment]
Could you edit your post and put \``` before and \``` after your frigate.yml? It should look something like this:

```
cameras:
  garage:
```

**Reply by mani94321** [reply]
done, apology for not add ``` initially

**Comment by shred86** [comment, marked as answer]
You need to move the `detect:` section over two spaces so it's nested under the `garage:` line (see [example in documentation](https://docs.frigate.video/guides/getting_started#step-3-add-a-minimal-camera-configuration)). So your frigate.yml should look like:

```
mqtt:
  host: 192.168.30.30
  port: 1883
  user: mqtt_username
  password: mqtt passord

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://login:passowrd@192.168.20.110:554/Streaming/Channels/102/
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 6

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

You could also define the `detect:` section globally so it would apply to all cameras. For example:

```
mqtt:
  host: 192.168.30.30
  port: 1883
  user: mqtt_username
  password: mqtt passord

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://login:passowrd@192.168.20.110:554/Streaming/Channels/102/
          roles:
            - detect

detect:
  width: 640
  height: 480
  fps: 6

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

Some other techniques/notes:
- `port: 1883` under `mqtt:` isn't required since that is the [default](https://docs.frigate.video/configuration/index#full-configuration-reference).
- Any particular reason for `fps: 6` for detect? 5 usually works for most situations (unless you're trying to record fast moving objects). 5 is also the default so you could omit that line if you wanted.
