### DISCUSSION TITLE
How to record H265 main stream while detect on H264 sub

### DISCUSSION THREAD

**Discussion by hagak** [blakeblackshear/frigate#2624] [Ask A Question]
I have a reolink 820 which has a 4K main stream in H265 and a lower res sub in H264.  Question I have is how can I have detect work on the sub while record and rtmp work on the main?

Currently I am setup as such.

```
ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        # Optional: output args for detect streams (default: shown below)
        detect: -f rawvideo -pix_fmt yuv420p
        # Optional: output args for record streams (default: shown below)
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -c:a aac
        # Optional: output args for clips streams (default: shown below)
        #clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
        # Optional: output args for rtmp streams (default: shown below)
        rtmp: -c copy -f flv -c copy -c:a aac
      inputs:
        - path: rtmp://<xxx>:1935/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
        - path: rtmp://<xxx>:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - rtmp
            - record
 ```

Seems like I would need a separate input args for the two. can you have the separate similar to the output?

Thanks

**Comment by NickM-27** [comment]
It would help if you formatted your current setup so it was readable, can't tell if you have `input` defined. This is already covered in the docs:

```yaml
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/live
          roles:
            - record
    detect:
      width: 1280
      height: 720
```

**Comment by hagak** [comment]
Updated formatting.  Note I am doing what is in the docs.  What is not in the docs is how to handle a H265 stream and H264 stream at the same time.

**Comment by NickM-27** [comment]
Gotcha, what is happening that makes it seem it is not currently working correctly?

**Comment by hagak** [comment]
I get no recordings on the one camera that has H265 stream.  My other cameras are fine but they are H264.

**Comment by NickM-27** [comment]
Which browser are you using? There is an important note in this part of the docs: https://docs.frigate.video/configuration/record/

`H265 recordings can be viewed in Edge and Safari only. All other browsers require recordings to be encoded with H264.`

**Comment by hagak** [comment]
Well good point on the browser but the issue is not actually viewing them it is that Frigate gets no recordings.

This is the only logs i get that might indicate an issue:
```

[2022-01-12 00:44:36] watchdog.dooryard              INFO    : Waiting for ffmpeg to exit gracefully...

[2022-01-12 00:44:46] watchdog.dooryard              INFO    : Terminating the existing ffmpeg process...
```

dooryard is the camera in question.  these 2 lines repeat over and over.

**Comment by NickM-27** [comment]
I see, what does your record: config look like, and is it defined per camera or the same for all cameras?

**Comment by hagak** [comment]
```
record:
  enabled: true
  retain_days: 2
  events:
    retain:
      default: 10
```
