### DISCUSSION TITLE
Objects being detected outside of its zone

### DISCUSSION THREAD

**Discussion by MisterTdog** [blakeblackshear/frigate#2636] [Ask A Question]
Hi !
I set several zones for my front yard:
- the road
- the yard
- the front yard (a zone between road and yard)
- the letter box ( a small one to test if I can detect when I've some letters.. anyway).
ROAD, YARD and FRONT YARD are completementary and there is not overlap between YARD and the others.

The night, my car is parked on YARD and is far away from the ROAD.

I saw 3 wrong situations:
°1 and °2: this night (night vision), my car was detected (as a vehicule - I customize my labelmap) on the ROAD. Well... I watched at the full clip and there was absolutely no movement neither on the ROAD nor from my car. The only movement I could see was from a cobweb that go through my camera and is placed over the YARD, from top to bottom of the picture (but not ROAD). The clip is 

°3: this morning, my sons and myselft went to the car, and leave our home. Frigate detected only a CAR on ROAD. Whereas, there was PERSONs going into the CAR on YARD. and then the CAR going on FRONT YARD and ROAD.

any help?

**Comment by blakeblackshear** [comment]
You need to post your config file if you want help. Also, an image from your camera showing where your zones are configured would be helpful.

**Comment by MisterTdog** [comment]
I changed a bit my configuration since this night, so it would not be relevant to analysize case °1, °2 and °3.
Nevertheless, I watched again the clip of °1 and 2°. I forgot to mention it, but both clips where quite long: 9min50 and 23min. That time, I saw a car going in ROAD at (respectively) 5min50/9min50 and 19mn31/23min30. The two snapshots were showing me my parked car on YARD and not the two from the ROAD...

I had the exact same behavior during daytime with my last config (see at the end):
![2022-01-13_14h33_12](https://user-images.githubusercontent.com/80855488/149341416-64ab7791-69d0-4e7d-b90d-7297dbd22d55.png)


Case °4 : my car was completely parked on YARD (="terrain" from my config, in brown on the screenshot). at 13:21 (event + 3min26), a truck went on the road (="route" from my config, in pink on the screenshot). 
The event details say: a vehicule (ok) on FRONT_YARD (="entree garage" from my config, in blue on the screenshot) and the snapshot focuses on my stationary car, parked on YARD ("terrain", brown).
![2022-01-13_14h32_47](https://user-images.githubusercontent.com/80855488/149342207-bcf4a9c0-adaf-4096-91d7-483dc4cb9611.png)

Case °5 : still, my car, on YARD (="terrain", brown). At start+4sec, a car went on the ROAD (="route", pink). The event details say ROAD (pink), but the snapshot focuses on my car.
![2022-01-13_14h40_43](https://user-images.githubusercontent.com/80855488/149341437-cd662011-fd80-4470-b22d-2d58e1d7e0f2.png)

The config:
```
mqtt:
  host: 192.168.1.9
  user: mqtt
  password: password

birdseye:
  enabled: False

model:
  labelmap:
    0: personne # person
    1: vehicule # bicycle
    2: vehicule # car
    3: vehicule # motorcycle
    # 4: # airplane
    5: vehicule # bus
    # 6: # train
    7: vehicule # car
    # 8: # boat
    # 9: # traffic light
    # 10:  # fire hydrant
    # 12:  # stop sign
    # 13:  # parking meter
    # 14:  # bench
    15: animal # bird
    16: animal # cat
    17: animal # dog
    18: animal # horse
    19: animal # sheep
    20: animal # cow
    21: animal # elephant
    22: animal # bear
    23: animal # zebra
    24: animal # giraffe
    # 26:  # backpack
    # 27:  # umbrella
    # 30:  # handbag
    # 31:  # tie
    # 32:  # suitcase
    # 33:  # frisbee
    # 34:  # skis
    # 35:  # snowboard
    # 36:  # sports ball
    # 37:  # kite
    # 38:  # baseball bat
    # 39:  # baseball glove
    # 40:  # skateboard
    # 41:  # surfboard
    # 42:  # tennis racket
    # 43:  # bottle
    # 45:  # wine glass
    # 46:  # cup
    # 47:  # fork
    # 48:  # knife
    # 49:  # spoon
    # 50:  # bowl
    # 51:  # banana
    # 52:  # apple
    # 53:  # sandwich
    # 54:  # orange
    # 55:  # broccoli
    # 56:  # carrot
    # 57:  # hot dog
    # 58:  # pizza
    # 59:  # donut
    # 60:  # cake
    # 61:  # chair
    # 62:  # couch
    # 63:  # potted plant
    # 64:  # bed
    # 66:  # dining table
    # 69:  # toilet
    # 71:  # tv
    # 72:  # laptop
    # 73:  # mouse
    # 74:  # remote
    # 75:  # keyboard
    # 76:  # cell phone
    # 77:  # microwave
    # 78:  # oven
    # 79:  # toaster
    # 80:  # sink
    # 81:  # refrigerator
    # 83:  # book
    # 84:  # clock
    # 85:  # vase
    # 86:  # scissors
    # 87:  # teddy bear
    # 88:  # hair drier
    # 89:  # toothbrush

objects:
  track:
    - personne
    - vehicule
    - animal
  filters:
    vehicule:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 300000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      # mask: 0,0,1000,0,1000,200,0,200

record:
  enabled: true  
  retain_days: 2
  events:
    required_zones:
      - terrain
      - entree_allee
      - route
      - boite_aux_lettres
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10
      objects:
        personne: 15
    
snapshots:
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  #required_zones: []
  retain:
    default: 10
    objects:
      personne: 15

cameras:
  cam_garage:
    ffmpeg:
      inputs:
        - path: rtsp://u.....      # <= high res
          roles:
            - detect
            - rtmp
            - record
        #- path: rtsp://....      # <= low res
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    zones:
      terrain:
        coordinates: 567,0,1280,616,1280,720,0,720,0,0
        objects:
          - personne
          - animal
      entree_allee:
        coordinates: 1280,466,1280,538,1280,573,847,216,951,211,1146,348
        objects:
          - personne
          - vehicule
          - animal
      route:
        coordinates: 808,122,1280,457,1280,222,829,39
        objects:
          - personne
          - vehicule
          - animal
      boite_aux_lettres:
        coordinates: 823,157,843,169,845,190,834,204,807,190,794,177,782,150,802,144
        objects:
          - personne
          - vehicule
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 1234,41,1232,84,932,84,928,43
    snapshots:
      required_zones:
        - terrain
        - entree_allee
        - route
        - boite_aux_lettres
    record:
      events:
        required_zones:
          - terrain
          - entree_allee
          - route
```
