### DISCUSSION TITLE
Best way to install HA+ Frigate on Odyssey Blue

### DISCUSSION THREAD

**Discussion by gulo101** [blakeblackshear/frigate#2718] [Ask A Question]
Hello

I just got Odyssey Blue Mini PC and M.2 B+M Coral card. I am currently running Home Assistant on Raspberry pi, and Frigate as Docker on Unraid (CPU only).

I would like to move my Home Assistant and Frigate to the Odyssey. What is the best approach?

- I am planning to install all the software on M.2 SSD, but I also got SATA SSD where I want to store Frigate snapshots and recordings so it needs to be able to access this drive
- I want Frigate to be able to use CPU Quicksync acceleration for ffmpeg
- I can follow instructions and mess with stuff some, but I am not looking for something crazy complicated where I have to compile bunch of images and spend hours/days in command line just to get anything working 
- If I only get HA+Frigate I guess that's fine (and I assume I could just do HA install and Frigate as add-on?) but I would like to be able to potentially install other small things on the PC in addition to HA

I was potentially looking at something like Proxmox but I wonder how hard will it be to install Frigate there and still access all the HW it needs?

What other options are there? Thanks!

**Comment by blakeblackshear** [comment]
Personally I always install a plain debian OS and install nothing but the Coral drivers and docker. I run everything in docker via compose.

You may also want to consider running home assistant supervised if you like the addon ecosystem.

**Comment by shred86** [comment]
I have the Odyssey Blue as well (Celeron J4125) and run an M.2 SSD for the OS (Debian 11) and apps with a SATA HDD for Frigate. Everything runs on Docker except for Network UPS Tool (NUT). I’m running about 10 containers to include Home Assistant, Frigate, Pihole, UniFi Controller, Scrypted, etc. with CPU usage hovering around 30% (mostly from using 1080p detect streams on four PoE cameras). Pretty happy with this setup. I posted the steps I take to build my setup [here](https://github.com/shred86/smart-home/blob/main/server-setup.md). It’s intended to be a guide for me in case I need to rebuild my setup so some parts probably don’t make complete sense (i.e. it was never really intended to be a user guide), but it might be helpful to get some ideas.

**Reply by Firerouge** [reply]
You can run NUT in a docker container as well with instantlinux/nut-upsd<details><summary>docker-compose example</summary>

```
  upsd:
    image: instantlinux/nut-upsd:latest
    restart: always
    container_name: upsd
    environment:
      SERIAL: <for apc ups'>
    secrets:
      - nut-upsd-password
    devices:
      - /dev/bus/usb:/dev/bus/usb #or specific device
    networks:
      haoverlaynet:
```

</details>
