### DISCUSSION TITLE
Problems with setting up Frigate with EMQX as MQTT broker

### DISCUSSION THREAD

**Discussion by poperigby** [blakeblackshear/frigate#2742] [Ask A Question] [answered]
I'm trying to do what I said in the title, but I'm getting this error:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-02-03 18:49:57] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
Starting migrations
[2022-02-03 18:49:57] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-02-03 18:49:57] peewee_migrate                 INFO    : There is nothing to migrate
```

From the research I've done, it seems this happens when Frigate can't communicate with the MQTT server, but I'm not sure why it isn't able to. This is my Docker Compose file for Frigate:
```
services:
  frigate:
    container_name: frigate
    hostname: frigate
    image: blakeblackshear/frigate:stable-amd64
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml:ro
      - /media/hdd0/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935 # RTMP feeds
    shm_size: "64mb" # update for your cameras based on calculation above
    privileged: true
    restart: unless-stopped
```
My Frigate config file:
```
mqtt:
  host: 192.168.1.184
  port: 1883
  user: admin
  password: admin
cameras:
  reolink:
    ffmpeg:
      # hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
          roles:
            - record
            - rtmp
        - path: http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
```
And here's my EMQX Docker Compose file:
```
services:
  emqx:
    image: emqx/emqx
    container_name: emqx
    hostname: emqx
    ports:
      - 1883:1883
      - 18083:18083
    volumes:
      - data:/opt/emqx/data
      - config:/opt/emqx/etc
      - log:/opt/emqx/log
volumes:
  data:
  config:
  log:
```

**Comment by blakeblackshear** [comment]
I don't see an error in the frigate log you posted. Are these in the same compose file? Are they on the same machine?

**Reply by poperigby** [reply]
> Are these in the same compose file?

I wasn't before, but I am now. 

> Are they on the same machine?

Yeah, they are.

I'm still getting the same problem though. Here's my new compose file:
```yaml
services:
  app:
    container_name: frigate
    hostname: frigate
    image: blakeblackshear/frigate:stable-amd64
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml:ro
      - /media/hdd0/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935 # RTMP feeds
    shm_size: "64mb" # update for your cameras based on calculation above
    privileged: true
    restart: unless-stopped
  mqtt:
    image: emqx/emqx
    container_name: emqx
    # ports:
    #   - 1883:1883
    #   - 18083:18083
    volumes:
      - data:/opt/emqx/data
      - config:/opt/emqx/etc
      - log:/opt/emqx/log
networks:
  default:
    name: reverse_proxy
    external: true
volumes:
  data:
  config:
  log:
```
