### DISCUSSION TITLE
Jetson Nano PR #2548 + RTMP ReoLink GST Pipelines

### DISCUSSION THREAD

**Discussion by cap9qd** [blakeblackshear/frigate#2752] [Show and tell]
I felt like I was doing wrong cluttering up the PR comments my stuff so I moved the info here. This only works with the PR request from @yury-sannikov here: https://github.com/blakeblackshear/frigate/pull/2548

ReoLink RTMP pipelines:
```
    gstreamer:
      inputs:
        - path: rtmp://192.168.1.1/bcs/channel0_main.bcs?channel=0&stream=1&user=frigate&password=TheFrigatePassword123
          raw_pipeline:
            - rtmpsrc location="rtmp://192.168.1.1/bcs/channel0_main.bcs?channel=0&stream=1&user=frigate&password=TheFrigatePassword123" do-timestamp=true timeout=20
            - flvdemux 
            - h264parse config-interval=1
            - nvv4l2decoder enable-max-performance=true
            - nvvidconv
            - videorate 
            - "video/x-raw(memory:NVMM),framerate=5/1"
            - nvvidconv 
            - "video/x-raw, width=(int)640, height=(int)480, format=(string)I420"
            - fdsink
          roles:
            - detect
        - path: rtmp://192.168.1.1/bcs/channel0_main.bcs?channel=0&stream=0&user=frigate&password=TheFrigatePassword123
          raw_pipeline:
            - rtmpsrc location="rtmp://192.168.1.1/bcs/channel0_main.bcs?channel=0&stream=0&user=frigate&password=TheFrigatePassword123" do-timestamp=true timeout=20
            - flvdemux 
            - h264parse config-interval=1
            - splitmuxsink async-handling=true location=/tmp/cache/back-yard-gstsplitmuxchunk-%05d.mp4 max-size-time=10000000000
          roles:
            - record
    detect:
      width: 640
      height: 480
```

This has the raw pipelines I am using: 
[frigate.yml.txt](https://github.com/blakeblackshear/frigate/files/8009129/frigate.yml.txt)

Docker files: 
[docker-compose.yml.txt](https://github.com/blakeblackshear/frigate/files/8009128/docker-compose.yml.txt)
[startFrigate.sh.txt](https://github.com/blakeblackshear/frigate/files/8009131/startFrigate.sh.txt)

I mistakenly mounted the localtime file from a different docker compose config; if you do this it will mess up the sync between the events DB and the recordings storeage and the web wont be able to find the recordings for the events.

**Comment by cap9qd** [comment]
I noticed when using the pipeline splitmuxsink the first part of the file name MUST MATCH case and format. I have "Back-Yard" and the location must be "/tmp/cache/Back-Yard-gstsplitmuxchunk-%05d.mp4"

```
_Back-Yard:
gstreamer:
      inputs:
        - path: rtmp://192.168.1.1/bcs/channel0_main.bcs?channel=0&stream=1&user=frigate&password=TheFrigatePassword123
          raw_pipeline:
...
            - splitmuxsink async-handling=true location=/tmp/cache/Back-Yard-gstsplitmuxchunk-%05d.mp4 max-size-
..._
```
Also, the pipeline caps for video/x-raw in the detector input section must match the camera resulution and must match the "detector" section resolution.
```
Back-Yard
  gstreamer:
      inputs:
        - path: rtmp://192.168.1.1/bcs/channel0_main.bcs?channel=0&stream=1&user=frigate&password=TheFrigatePassword123
          raw_pipeline:
           ...
            - "video/x-raw, width=(int)640, height=(int)480, format=(string)I420"
           ...
    detect:
      width: 640
      height: 480
```

**Reply by cap9qd** [reply]
JTop:
![image](https://user-images.githubusercontent.com/33727568/152663432-f810460c-23eb-4f54-ae2d-3e7becfe6b8c.png)
![image](https://user-images.githubusercontent.com/33727568/152663437-0602ff41-b3b0-405b-aee8-114ccb2c6a58.png)
![image](https://user-images.githubusercontent.com/33727568/152663441-27f8eccf-039d-4106-9389-c2ff34489475.png)
![image](https://user-images.githubusercontent.com/33727568/152663445-26316346-a74d-407f-abe2-3a6c1333ef96.png)

**Reply by cap9qd** [reply]
This 4x HD cameras at 2560x1920 @ 5FPS.

**Comment by jmorris644** [comment]
So I have 5 HD cameras running successfully. All detecting at full resolution. I am not doing any recording yet at this time. Not much CPU usage either. It is getting dark, so I am going to play more tomorrow.

![image](https://user-images.githubusercontent.com/8661459/152663207-067e8542-d8ff-4184-8735-8b1d0f041240.png)

**Comment by jmorris644** [comment]
I am going to call it a night but I am starting to see some Python bus errors
```
Fatal Python error: Bus error
```

**Reply by cap9qd** [reply]
> I am going to call it a night but I am starting to see some Python bus errors
> 
> ```
> Fatal Python error: Bus error
> ```

Did you increase the shm size to match based on the calculation [here?](https://docs.frigate.video/installation/#calculating-required-shm-size)

**Reply by jmorris644** [reply]
Ah, I restarted this process so many times, I forgot. I am not using docker-compose, where do I put it?

**Reply by jmorris644** [reply]
I tried putting it in /etc/docker/daemon.json and was still getting the errors until I restarted Docker. I am not getting the bus errors anymore.

**Comment by cap9qd** [comment]
Just an FYI... The dahua camera IPC-HFW1431S-S4 doesn't have audio.  My ReoLink cameras do have audio and just assumed...whoops.

**Comment by cap9qd** [comment]
I am struggling with audio from an RTMP stream.  Anyone have any ideas...? I am pretty clueless about GST and only stumbled around with it doing the Jetson tutorials. Any help would be appreciated! The audio isn't a deal breaker but now that I cant make it work I want to!

This is one of my many attempts that has not worked...If I comment out the last 3 lines of the record pipeline the video works.
```
  Back-Yard:
    gstreamer:
      inputs:
        - path: rtmp://192.168.x.x/bcs/channel0_main.bcs?channel=0&stream=1&user=user&password=password
          raw_pipeline:
            - rtmpsrc location="rtmp://192.168.x.x/bcs/channel0_main.bcs?channel=0&stream=1&user=user&password=password" do-timestamp=true timeout=20
            - flvdemux 
            - h264parse config-interval=1
            - nvv4l2decoder enable-max-performance=true
            - nvvidconv
            - videorate 
            - "video/x-raw(memory:NVMM),framerate=5/1"
            - nvvidconv 
            - "video/x-raw, width=(int)640, height=(int)480, format=(string)I420"
            - fdsink
          roles:
            - detect
        - path: rtmp://192.168.x.x/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password
          raw_pipeline:
            - rtmpsrc location="rtmp://192.168.x.x/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password" do-timestamp=true timeout=20
            - flvdemux name=demux demux.
            - queue
            - h264parse config-interval=1
            - splitmuxsink name=mux muxer=mp4mux async-handling=true location=/tmp/cache/Back-Yard-gstsplitmuxchunk-%05d.mp4 max-size-time=10000000000
            - queue
            - aacparse
            - mux.audio_0
          roles:
            - record
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - dog
        - cat
    snapshots:
      enabled: True
    record:
      enabled: True
```

If I comment out the lines below the video works:
```
- queue
- aacparse
- mux.audio_0
```

Here is the stream info from VLC.
![image](https://user-images.githubusercontent.com/33727568/152667973-ed091d67-08ef-4f8f-95e1-34ca50d95562.png)

**Comment by LordNex** [comment]
What model of ReoLink are you running. I have 1 RCL520A up currently with 3 more still in boxes waiting for it to be warm enough. The decoding kind sucks though

**Reply by cap9qd** [reply]
I have ReoLink RLC-410-5MP.  I have been using them outside for over a year.  In MotionEyeOs/Motion-Project I have been using the RTMP stream with no issues for most of that time.  I had the smearing/broken-stream issues until I updated motion and could use the RTMP stream. I dont recall the stream settings for FFMPEG now but it should be doable easily in Frigate 0.9 and this PR.

**Comment by jmorris644** [comment]
OT: How do I set up notifications just for this discussion? When I enabled 'watch' I get all posts form the complete repository.

**Reply by cap9qd** [reply]
I am not sure...I just made it and get just the notifications for this discussion and the PR.

Edit: There is a button at the top right of the page for notifications in this discussion:
![image](https://user-images.githubusercontent.com/33727568/152690193-fdec98fc-9e0f-49b6-a9a6-27cf113bc81a.png)

**Comment by jmorris644** [comment]
Ah, github had an information comment over it. So I did not see it. In the meantime I created a macro in Outlook to move all github notifications into their own folder. That actually is working well. :)

**Comment by jmorris644** [comment]
@cap9qd a couple of questions about your config file.

1. Why are you not using any "video/x-rar..." parameters in your Dahua config?
2. Is there a reason for only using a frame rate of 5 for the REO cams and not the Dahua?

**Reply by cap9qd** [reply]
I used the stock rtsp pipelines for the Dahua camera and not a raw pipeline. I was trying to get the audio into the record file not realizing it didn't have a microphone like the ReoLink.

I have the substream on both Dahua and ReoLink set to 5fps. I copied the config from the PR without changing them much.

I guess the answer is the config were a bit erroneous from piecing it together. Once I have it more stable I'll post the latest configs.

**Comment by jmorris644** [comment]
I am still getting this error but everything seems to be working correctly. Is this something that I need to fix?
```
(gst-plugin-scanner:215): GStreamer-WARNING **: 18:02:41.963: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so': libgstbadvideo-1.0.so.0: cannot open shared object file: No such file or directory
```

**Reply by cap9qd** [reply]
I haven't had any issues with this warning. I think it shows the color bar pattern if the stream/pipeline is bad or unavailable. I haven't been able to figure out how to fix this error yet. If I do I'll post back.

**Comment by LordNex** [comment]
Looks like it’s missing one of the files. Have you tried a sudo apt update and sudo apt full-upgrade -y yet?


On Feb 6, 2022, at 12:04 PM, Joe Morris ***@***.***> wrote:

﻿

I am still getting this error but everything seems to be working correctly. Is this something that I need to fix?

(gst-plugin-scanner:215): GStreamer-WARNING **: 18:02:41.963: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so': libgstbadvideo-1.0.so.0: cannot open shared object file: No such file or directory

**Reply by jmorris644** [reply]
Everything is fully updated and upgraded.

The file is there in /usr/lib/aarch64-linux-gnu/. I have added that directory to LD_LIBRARY_PATH, did an export, and ran ldconfig. It did not help.

**Comment by jmorris644** [comment]
I am also getting many of these errors:
```
(gst-discoverer-1.0:272): GStreamer-CRITICAL **: 21:35:24.428: gst_buffer_resize_range: assertion 'bufmax >= bufoffs + offset + size' failed
```
Any thoughts?

**Reply by cap9qd** [reply]
I think the dev in the PR is still working on that one. I have it as well without issue. They talked in the pr comments about these errors being erroneous and that adding the jitter buffer helps. I haven't had success getting rid of them with pipeline changes but will keep you posted if I do.

**Comment by cap9qd** [comment]
I am going to try building the image from the repo and see if some of the things are fixed. I'll keep yall posted...

**Reply by yury-sannikov** [reply]
Hi @cap9qd, sorry, just seeing this discussion. If you want to build it manually, use this [commit](https://github.com/blakeblackshear/frigate/pull/2548/commits/47710795bad25e22370effa274c9bbed9546336c) I'm updating gstreamer logic to make audio work and some other improvements. It generally works, but I tested it against h265 streams. I believe h264 will not work, except you're using raw_pipeline.

To make audio works, you can try this pipeline ([from unit tests](https://github.com/blakeblackshear/frigate/pull/2548/files#diff-c961ca204aa38bb5361f79faa71ae1d89f57fc69486a19de6c95516c9d979a6aR405))

**Reply by cap9qd** [reply]
No worries at all. I wanted to move the discussion out of the PR about getting it running and setup so it didn't get too cluttered. I guess I should have asked first... I hope this is okay? 

If you want me to test anything against my cameras let me know. They are difficult ReoLink cameras with audio and require the rtmp streams to work reliably I have found. I have two different model Dahua cameras and the other might have audio...

Once I get the build environment up and running I can test whatever commit you'd like.

**Comment by yury-sannikov** [comment]
```
(gst-discoverer-1.0:272): GStreamer-CRITICAL
```
Those errors are coming from `gst-discoverer-1.0` a tool to inspect the RTP stream and detect audio and video codecs. The command itself is just as simple as `gst-discoverer-1.0 -v $URL`. I would ignore all warnings from `gst-discoverer` although, I'm pretty new to gstreamer and might be wrong.

**Reply by cap9qd** [reply]
Ah makes sense. Thanks for the heads up.

I am new to gst and was dumping log files and dot files trying to get audio from the ReoLink RTMP stream... Didn't even think to look for an auto detect gst function! Thanks for the tip!

**Comment by jmorris644** [comment]
FYI: Just in case you run into the error. I had mistyped a username for one of my cameras. What I saw in the Docker log was an ffmpeg error. This is totally understandable, I just wanted to mention it so no one spends too much time looking too long.

**Reply by yury-sannikov** [reply]
yeah, I need to rename all FFmpeg-related errors to something more neutral or pass the GStreamer instead

**Comment by jmorris644** [comment]
An interesting tidbit: When I had all of my cameras (5 of them) set at high resolutions the inference speed was between 17 and 25 most of the time. Now that all of the cameras are set at 720 or less the inference speed is higher than 50. I would have thought the opposite.

**Comment by jmorris644** [comment]
Caution on Docker Upgrade: On the Jetson Nano docker version docker.io_20.10.2-0ubuntu1_18.04.3 will cause issues on the Nano. Errors similar to 
```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown
```

If you get these errors you need to downgrade to docker.io_20.10.2-0ubuntu1_18.04.2

It is a known issue with no resolution yet.

**Reply by cap9qd** [reply]
https://github.com/blakeblackshear/frigate/pull/2548#issuecomment-1030670478

I need to pin my docker and containerd so I can get the rest of the updates. Or go experimental... But I'll do that on a separate SD card.

**Reply by jmorris644** [reply]
Here is where I got the info:

https://forums.developer.nvidia.com/t/docker-containers-wont-run-after-recent-apt-get-upgrade/194369

**Reply by cap9qd** [reply]
Thanks for the info.

**Comment by LordNex** [comment]
So your running frigate on the Jetson Nano? Do you also have a Jetson Coral?

I have DeepStack running on the Nano doing facial recognition. And Frigate in a RPi4 8gig with a Coral TPU.

I then use DoubleTake as a add on to Home Assistant to pull it all together with a GUI interface for creating and training new faces and people.

Curious how your use case is



On Feb 8, 2022, at 10:06 AM, Joe Morris ***@***.***> wrote:

﻿

An interesting tidbit: When I had all of my cameras (5 of them) set at high resolutions the inference speed was between 17 and 25 most of the time. Not that all of the cameras are set at 720 or less the inference speed is higher than 50. I would have thought the opposite.

**Reply by jmorris644** [reply]
I have Frigate running on a jetson nano. I then spun up a 2nd jetson nano and am trying to install deepstate on it. That is when I ran into the docker version issue. I plan to also put Doubletake and Compreface on the 2nd nano. All of this will feed node-red via MQTT. From node-red I can pretty do anything I want. My first attempt will be to have Alexa announce who is at the door.

**Reply by LordNex** [reply]
> I have Frigate running on a jetson nano. I then spun up a 2nd jetson nano and am trying to install deepstate on it. That is when I ran into the docker version issue. I plan to also put Doubletake and Compreface on the 2nd nano. All of this will feed node-red via MQTT. From node-red I can pretty do anything I want. My first attempt will be to have Alexa announce who is at the door. 

That the one tool I just haven't played with much, NodeRed. All of my automations I build manually through the Automations page. 

I think I'm just going to keep frigate on the Nano with a USB Coral TPU and then use CompreFace as my detector inside HA addon inside my 40 core PowerEdge R620. I'm also running DoubleTake inside HA that pulls all the prices together and gives a very nice interface for training new facial models and keeping them up to date. 

At one point I was running 3 detectors. Facebox, DeepStack, and Conpreface and by far ConpreFace was faster, more accurate, and has plugins for age, gender, and if they are wearing a mask. 

I'll have to come up with another use for the RPi4B 8gig

**Comment by LordNex** [comment]
From what I understand and have tried, Frigate can’t utilize the GPU of the Nano. Now that may have changed but the last time I tried I ram into issues as well which is why I just broke down and got the TPU and tied it to a RPi4. Also remember to call the aarch64 version of the docker container in your docker compose file. That and statically setting the OS to boot using the 64 bit version of the OS.

I just bought a 40 ***@***.*** 256gig PowerEdge R620 off eBay that eventually have a VM with the TPU passed through. Well technically is a dual processor config with 10 cores each and hyper-threading so a total of 40 manageable CPU cores. I though about looking for a good PCIe TPU/GPU card along with a Haupeg encoder/decoder. But the Haupeg I currently have I don’t think will handle certain digital things.

What we need is an all in one hardware solution that does NVR with detection, recognition, and verification, that can handle let’s say 20 streams PoE. It wouldn’t be cheap cause you would have to virtualization inside and would need enough power to handle that and also have 2.5/5GBE interfaces. I wonder if you could use a kubernet cluster of something similar to the Nano.

Since the Nano has been declared EOL, the developer of the DeepStack interface has decided to no longer maintain support for it on the Nano so we’re going to have to find another choice or run at a lower software version with possible security issues.


 On Feb 8, 2022, at 2:09 PM, Joe Morris ***@***.***> wrote:

﻿

I have Frigate running on a jetson nano. I then spun up a 2nd jetson nano and am trying to install deepstate on it. That is when I ran into the docker version issue. I plan to also put Doubletake and Compreface on the 2nd nano. All of this will feed node-red via MQTT. From node-red I can pretty do anything I want. My first attempt will be to have Alexa announce who is at the door.

**Reply by jmorris644** [reply]
Whew, you had me worried about the Nano EOL. I use that in production!! :) The TX1 was EOL last month. The Nano is 2025. Was there a deepstack post somewhere stating ending of support for the Nano?

I have Frigate running and using GPUs on the Jetson Nano. See https://github.com/blakeblackshear/frigate/discussions/2752

Nice buy on Ebay. I have tried server class machines before. In my experience they are very loud. Plus my equipment rack is 17" and a lot of those are 24". 

I have never been a fan of Docker before, but because everything seems to be being delivered in it lately I watched a few youtube classes.  From what I read, you would be better off using docker images on your new machine rather than VMs. Although having said that, you do have a lot of hardware to share. :)

**Reply by Elkropac** [reply]
Hi guys, i'm curious about buying and using nano for frigate for long time.
Now, I run frigate in VM on dell T1700, without TPU. Recently, I bought R420 to move my home VM's to it.
So is nano capable of running frigate (with changes from PR 2752)? I will need some external USB drive for recordings, right?
Or is it better to buy some TPU to my new R420?

**Reply by jmorris644** [reply]
I have it running very well with 5 cameras. One cam is 2MP and the other 4 are 5MP cameras. The detect is working great and the MQTT is also working great. I am not doing any recording yet and I am not using any zones yet. So I cannot attest to those.

**Reply by cap9qd** [reply]
> From what I understand and have tried, Frigate can’t utilize the GPU of the Nano. Now that may have changed but the last time I tried

The referenced PR adds GST and TensorRT to add GPU support to Frigate.

**Reply by cap9qd** [reply]
> Hi guys, i'm curious about buying and using nano for frigate for long time. Now, I run frigate in VM on dell T1700, without TPU. Recently, I bought R420 to move my home VM's to it. So is nano capable of running frigate (with changes from PR 2752)? I will need some external USB drive for recordings, right? Or is it better to buy some TPU to my new R420?

I have a USB3 256GB SSD for media. And I have TensorRT running the included Yolo-v4 and gpu NV decoding.

**Reply by cap9qd** [reply]
> I have it running very well with 5 cameras. One cam is 2MP and the other 4 are 5MP cameras. The detect is working great and the MQTT is also working great. I am not doing any recording yet and I am not using any zones yet. So I cannot attest to those.

I am doing 3x 5mp cameras (ReoLink RTMP stream) and 1x 4mp camera (Dahua RTSP stream). I am using the low res substream for detection (480p) and recording/dumping the high res to disk for recording. I have missed a recording here and there but that's been my only issue. Like Joe I have not used zone yet but do have HA configured and working.

**Reply by Elkropac** [reply]
Ok looks good. I have 4 cameras and plan to add 2 or 3 more. 
But i have just found out, that jetson nano is not available for reasonable price anywhere. I have had it sitting in my shopping cart for about 70$ , i was waiting for frigate to support it ;)
I think, i will probably go with some industrial pc with dual LAN and m.2 connector for coral TPU - but it's not available either

Crazy ...

**Reply by jmorris644** [reply]
Yeah, Even PIs are going for over $100

**Reply by cap9qd** [reply]
I am in the same boat. I had the 2GB version of the Jetson "laying around" when MotionEye seems to have died off and wanted a better alternative. So I'll deal with this until I can get another 4gb Jetson or NX and use the 2gb version for deepstack or something like that to play around with. I have a TPU M.2 but it's the wrong key for everything I own now... :( I also have a Coral Dev but I guess frigate support is broken by some issue... Didn't dig too far before finding this and jumping at it.

**Reply by LordNex** [reply]
Well today is the day. My RPi4 8gig with a tiny 32 gig SD said it was full trying to upgrade from 0.11.0RC2 to stable. So no I'm going to reimage the 4gig Nano with a custom image built for DeepStack, but has everything already enable and built in. So I'll just disable DeepStack. Then use the USB TPU on it for detection. And the GPU for the encoding and decoding. Then have that tied into Home Assistant with DoubleTake and CompreFace as the detector running through MQTT. Im going to use a Class 10 128GB SD Card this time. All my storage goes to my OpenMediaVault NAS running on the PowerEdge. So hopefully when I'm done, it'll run faster and have better and faster encoding and decoding (before there was almost a 1 min lag between what happen on camera and when it was seen on screen, not great for a doorbell cam) and free up a very in demand Raspberry Pi 4B 8gig for something else somewhere down the road. 

What Pi based media servers does everyone like. Plex sucked I though and I haven't really found anything else. Music Assistant inside Home Assistant rocks but I was curious

**Comment by jmorris644** [comment]
@cap9qd Would yo u mind reposting your docker-compose file? I am trying to move to that instead of the CLI and getting errors. I am guessing there are some paste errors in the original file you uploaded? Granted, I am just learning about Docker-Compose.

**Reply by cap9qd** [reply]
Sure!  I have changed a few things. I have moved my config and media to a USB3 case with an SSD and linked it to /opt/frigate for the service.

docker-compose.yml
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: yury1sannikov/frigate.l4t:latest
    shm_size: "256mb" # update for your cameras based on calculation above
    runtime: nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /opt/frigate/frigate.yml:/config/config.yml:ro
      - /mnt/sda1/frigate/media:/media/frigate
      - type: tmpfs # Optional: 0.5GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
```
docker-frigate.service
```
# /etc/systemd/system/docker-frigate.service

[Unit]
Description=Docker Compose Frigate Service
Requires=docker.service
After=docker.service

[Service]
User=frigate
Group=frigate
WorkingDirectory=/opt/frigate
ExecStart=/usr/local/bin/docker-compose up
ExecStop=/usr/local/bin/docker-compose down
TimeoutStartSec=0
Restart=on-failure
StartLimitIntervalSec=60
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
```
EDIT: I made a user frigate and moved the media to an SSD plugged into the USB3.0 port; I still get slow cache flush warnings on startup. I also linked the docker-compose.yml and frigate.yml from the SSD to /opt/frigate/.  Why I did that...I dont know I was going to put the stuff in opt but if the sd crashes I like it being on the SSD.

**Reply by jmorris644** [reply]
I don't get why I am having so much trouble with the docker-compose.yml file. I am getting this error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'frigate'
```
Here is my docker-compose file:
```
version: "3.4"
services:

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #image: blakeblackshear/frigate:<specify_version_tag>
    image: yury1sannikov/frigate.l4t:latest
    shm_size: "350mb" # update for your cameras based on calculation above
    runtime: nvidia
    #devices:
      # - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions \
    volumes:
      - /home/frigate/config.yml:/config/config.yml:ro
      - /home/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds

    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
```
