### DISCUSSION TITLE
Database size

### DISCUSSION THREAD

**Discussion by DrSpaldo** [blakeblackshear/frigate#2755] [Ask A Question] [answered]
I was wondering about the database size and what it should be. Mine is currently 934 megs. I am not concerned about the hdd space being used, Frigate is using around 4TB in media. 

I was interested to know if that is the usual database size? The event viewer does take some time to load when it first starts up.

**Comment by blakeblackshear** [comment]
How many cameras do you have and what are your retain settings?

**Comment by DrSpaldo** [comment]
6 cameras. 

```yaml
    record:
      enabled: true
      retain:
        days: 10
        mode: all
      events:
        pre_capture: 10
        post_capture: 15
        objects:
          - person
        retain:
          default: 15
          mode: active_objects
          objects:
            person: 30 
```

Tracking dog, person & car

snapshots for 7 days default and 60 days for person
