### DISCUSSION TITLE
Possible to use a RTSP stream for record and a RTMP stream for detect?

### DISCUSSION THREAD

**Discussion by thunderwolf66102** [blakeblackshear/frigate#2768] [Ask A Question]
I've been trying to get all my reolink cameras to work well and thus far I have been able to accomplish this excepting with the 3 4K cameras that I have.  They should work properly, it just appears that I lack the processor/GPU power in the current configuration to pull it off as my CPU is running @ 100 percent constantly now for the NVR system (per top).

The current working config (with lag on the three 4K cameras on both record and live view)  Relevant parts clipped - let me know if I need a full config dump

```yaml
ffmpeg:
  global_args:
    -hide_banner -loglevel error
  hwaccel_args:
    -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p -c:a none
#    detect: -hwaccel vaapi -hwaccel_output_format yuv420p  -vf "format=yuv420p,hwupload,scale_vaapi=w=2048:h=1192,hwdownload,format=yuv420p" -c:a none
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -c:v copy
  input_args: -avoid_negative_ts make_zero

  front:
    rtmp:
      enabled: false
    snapshots:
      enabled: true
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p -vf scale=2048:1192 -r 5 -c:a none
      input_args: -avoid_negative_ts make_zero -rtsp_transport tcp
      inputs:
        - path: rtsp://admin:1camera7@192.168.45.251:8554/front
          roles:
            - record
            - detect
```

I want to try using hardware acceleration (vaapi - radeon) on the detect: ouput stream but I get a message stating that I cannot use that with a ffmpeg -f rawvideo pipe.

Trying to use a lower resolution stream available via rtmp (with output args: detect: width: 896 height: 512 and detect: under the camera changed to -f rawvideo -pix_fmt yuv420p -c:a none) results in the following -

```
[2022-02-07 15:22:59] frigate.video                  INFO    : streetsouth: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-02-07 15:22:59] frigate.video                  INFO    : streetsouth: ffmpeg process is not running. exiting capture thread...
```

Is it possible to hardware accelerate the detect stream/pipe on these three cameras or straight up use the lower resolution rtmp stream for object detection without error?
