### DISCUSSION TITLE
Config Validation Errors  - Motion Mask (per camera)

### DISCUSSION THREAD

**Discussion by Hoosier-IT** [blakeblackshear/frigate#2774] [Ask A Question] [answered]
Greetings, I seem to be having some significant issue with trying to add a motion mask per camera. I'm sure there is something I am clearly doing wrong, just not seeing what that is. I've been advised a few times you can add a motion mask per camera. This is what I am trying to accomplish.

https://pastebin.com/frJuAkQ6

```
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
2 validation errors for FrigateConfig
cameras -> North -> ffmpeg -> motion
  extra fields not permitted (type=value_error.extra)
cameras -> Dorbell -> ffmpeg -> motion
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

**Comment by blakeblackshear** [comment, marked as answer]
It doesn't go underneath ffmpeg

```yaml
mqtt:
  host: 192.168.1.254
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  EXAMPLE_VAR: value

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv

detect:
  width: 720
  height: 576
  fps: 5
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person
    - car
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  #mask: 269,68,429,49,621,46,852,61,1117,113,1280,207,1280,0,0,0,0,246
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
#      mask: 0,0,1000,0,1000,200,0,200

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  #mask: 0,0,720,0,720,169,653,103,579,75,461,52,350,42,250,42,136,63,0,208

record:
  enabled: true
  retain_days: 8
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    required_zones: []
    retain:
      default: 8
      objects:
        person: 30

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  #height: 175
  required_zones: []
  retain:
    default: 8
    objects:
      person: 30

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: false

live:
  height: 720
  quality: 8

cameras:
  North:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.40:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.40:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - record
    motion:
      threshold: 25
      contour_area: 100
      delta_alpha: 0.2
      frame_alpha: 0.2
      frame_height: 180
      mask: 
        - 0,0,720,0,720,169,653,103,579,75,461,52,350,42,250,42,136,63,0,208
    best_image_timeout: 60

    zones:
      easement:
        coordinates: 0,224,185,51,251,39,0,324
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      driveway:
        coordinates: 354,41,280,576,0,576,0,323,245,43
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      yard:
        coordinates: 720,186,720,322,676,282,528,265,341,259,356,47,461,58,534,73,591,91,648,112
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      walkway:
        coordinates: 464,263,676,287,720,344,720,576,286,576,321,267
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
  Dorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.156:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.156:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      threshold: 25
      contour_area: 100
      delta_alpha: 0.2
      frame_alpha: 0.2
      frame_height: 180
      mask: 
        - 0,0,0,373,176,360,287,370,441,369,564,358,562,305,553,195,720,21,720,0
    best_image_timeout: 60

    zones:
      pourch:
        coordinates: 0,576,720,576,562,463,504,475,453,475,420,451,358,459,244,449,85,414,0,428
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      doorbell_yard:
        coordinates: 279,370,552,372,551,465,459,475,428,441,337,450,212,436,95,415
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      doorbell_driveway:
        coordinates: 0,426,0,382,211,363,265,371
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []
```
