### DISCUSSION TITLE
All recordings are at low resolution, what am I missing?

### DISCUSSION THREAD

**Discussion by smith-scot** [blakeblackshear/frigate#2795] [Ask A Question]
```
mqtt:
  host: x.x.x.5
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass
  stats_interval: 60

database:
  path: /media/frigate/clips/frigate.db

cameras:
  front_garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@x.x.x.101:554//h264Preview_01_main
          roles:
            - rtmp
            - record
      inputs:
        - path: rtsp://user:pass@x.x.x.101:554//h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
      enabled: True

    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        person:
          threshold: 0.6

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5

    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 5

motion:
  mask:
    - 10,32,228,35,227,17,10,14
    - 640,0,640,88,458,0
```

After an event is recorded I download it an use VLC to determine what the video size is, and all inspected video it is 640x480.

Any thoughts?  Thanks.

**Comment by blakeblackshear** [comment]
Your config has two entries for inputs, so I think the second is overwriting the first. Try this:

```yaml
mqtt:
  host: x.x.x.5
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass
  stats_interval: 60

database:
  path: /media/frigate/clips/frigate.db

cameras:
  front_garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@x.x.x.101:554//h264Preview_01_main
          roles:
            - rtmp
            - record
        - path: rtsp://user:pass@x.x.x.101:554//h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
      enabled: True

    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        person:
          threshold: 0.6

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5

    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 5

motion:
  mask:
    - 10,32,228,35,227,17,10,14
    - 640,0,640,88,458,0
```
