### DISCUSSION TITLE
Snapshot on events

### DISCUSSION THREAD

**Discussion by pvillanyi** [blakeblackshear/frigate#2807] [Ask A Question] [answered]
Is it possible to create also a cam_latest.jpg snapshot like in doods?
I can't get notification to discord running with a template for the actual snapshot.
Or have you a suggestion how to automate sending the snapshot to discord? I know it is found also in camera.cam_person entity, but I couldn't manage to send it to discord.

**Comment by blakeblackshear** [comment]
https://docs.frigate.video/integrations/api#get-apicamera_namelatestjpgh300

You can also use the snapshot service in HA for the automatic camera entity.

**Reply by pvillanyi** [reply]
Thanks, this I could attach as URL which I can unfortunately only open from home. Discord notification accepts for attached images only local path. Is there a way to get the cam/latest.jpg on a local path?

**Comment by blakeblackshear** [comment]
Here is an example of how to use the `camera.snapshot` service from [another issue](https://github.com/blakeblackshear/frigate/issues/260) for saving the latest image:

```yaml
- id: '1602485767351'
  alias: Face recognition - ESP Opener
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_motion_stefan
    to: 'on'
  - platform: state
    entity_id: binary_sensor.front_motion_steffi
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 22c7bc60925d40cb8b32e026ecc7f7f2
    entity_id: switch.esp32_frontdoor_opener
    domain: switch
  - service: camera.snapshot
    data:
      entity_id: camera.front
      filename: /config/www/snapshots/door_open/door_open_{{ now().strftime("%Y%m%d-%H%M")}}.jpg
  - service: notify.slack
    data_template:
      message: '{{ trigger.to_state.name }} Known Face detected.  Open Door 
                Confidence: {{ states("sensor.front_confidence")}}                
                <https://URL/lovelace/esp|Homeassistant> | <https://URL/lovelace/cams|Image> | <https://URL/jXavSrgGOX4bH0BA9P6Oo4uIrQpbE7/mjpeg/kxZcRuJLJY/front |Stream> '
      title: '{{ trigger.to_state.name }} - Confidence: {{ states("sensor.front_confidence")}} '
      data:
        file:
          path: /config/www/snapshots/door_open/door_open_{{ now().strftime("%Y%m%d-%H%M")}}.jpg
  mode: single
```
