### DISCUSSION TITLE
24/7 Recording plus events

### DISCUSSION THREAD

**Discussion by toinopt** [blakeblackshear/frigate#2815] [Ask A Question]
Is it possible to record 24/7 and have the events be recorded to another folder, before enabling detection i had 1 hour videos, since i enabled detection it splits the 1 hour videos and for some reason its not recording some seconds/minutes after the event.
I would to have the 1 hour videos intact for better viewing and the events be recorded to another folder.
Couldn't find any way to do this.
Thanks for the Help

```yaml

mqtt:
 host: x.x.x.x
 user: homeassistant
 password: xxxx
  
cameras:
 Quintal:
  rtmp:
      enabled: False
  ffmpeg:
   inputs:
    - path: rtsp://xxxx/h.265
      roles:
      - record
      - detect
  detect:
    enabled: True
    width: 640
    height: 480
    fps: 5  
  motion:
    mask:
      - 0,328,0,480,287,480,284,431,274,411,261,386,252,366,220,329,181,273,28,208
  record: # <----- Enable recording
    enabled: True
    retain_days: 5 

 Garagem:
  rtmp:
      enabled: False
  ffmpeg:
   inputs:
    - path: rtsp://xxxx//h265Preview_01_main
      roles:
      - record    
    - path: rtsp://xxxx//h264Preview_01_sub
      roles:
      - detect  
  detect:
    enabled: True
    width: 640
    height: 480
    fps: 5
  motion:
    mask:
      - 203,472,421,471,417,456,209,456
  record: # <----- Enable recording
    enabled: True
    retain_days: 5

 Jardim:
  rtmp:
      enabled: False
  ffmpeg:
   inputs:
    - path: rtsp://xxxx//h265Preview_01_main
      roles:
      - record
    - path: rtsp://xxxx//h264Preview_01_sub
      roles:
        - detect    
  detect:
    enabled: True
    width: 640
    height: 480
    fps: 5    
  motion:
    mask:
      - 210,471,413,470,419,457,210,456  
  record: # <----- Enable recording
    enabled: True
    retain_days: 5

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

ffmpeg:
  output_args:
    # Optional: output args for detect streams (default: shown below)
    #detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 3600 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    #rtmp: -c copy -f flv

```
