### DISCUSSION TITLE
Frigate HA addon, Telegram went grazy

### DISCUSSION THREAD

**Discussion by Kotitonttu1** [blakeblackshear/frigate#2849] [Ask A Question] [answered]
I have tried this with Frigate 2.3 and 3.0. I dont think that the fault is with Frigate, because event log looks ok there.

The problem is that Telegram keeps sending constantly (1-4 per minute) old events to phone. This worked at first but then suddenly few days ago it started the continuous sending. 

HA automation looks like this:
```
- alias: Notify of events
  trigger:
    platform: mqtt
    topic: frigate/events
  action:
  - service: notify.telegram
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected.
      data:
        photo:
        - url: http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
          caption: A {{trigger.payload_json["after"]["label"]}} was detected on {{
            trigger.payload_json["after"]["camera"] }} camera
  id: 2678cff491a3475bb273dd02b5af65b1
```

**Comment by adamderuwe** [comment]
I use Frigate with Telegram and Home Assistant.  I'm getting old images sent via Telegram as well.  But, I would disagree with you that its an issue with Telegram.

Frigate is sending messages to `frigate/events` constantly.  That's why the automation is triggering and messages are being sent constantly.

**Comment by blakeblackshear** [comment]
You need to define some conditions so you only get notified of events messages that you want. Frigate sends lots of messages for the same object to the events topic.

**Reply by adamderuwe** [reply]
Thanks. Can definitely do that. Seems like this is a change in functionality. Didn't act like this until 0.10.0

**Reply by blakeblackshear** [reply]
It has always published multiple messages for each tracked object. The difference is that 0.10.0 keeps tracking stationary objects and will send an update every minute for those stationary objects indefinitely.

**Reply by adamderuwe** [reply]
Makes sense. Appreciate the explanation.

**Reply by Kotitonttu1** [reply]
Any hint what kind of conditions I could define? I liked the speed of messages when the above automatication worked.

Just tried to replace:
```
  trigger:
    platform: mqtt
    topic: frigate/events
```

With this, but this doesnt work:
```
 trigger:
    platform: state
    entity_id: binary_sensor.terassi_person_motion
```

But it doesnt send.

Edit: Should have read documentation more, I will try these: https://docs.frigate.video/guides/ha_notifications/

**Reply by blakeblackshear** [reply]
The full set of properties are available here: https://docs.frigate.video/integrations/mqtt#frigateevents

You may also want to look at how the blueprint is setup and use parts of it: https://community.home-assistant.io/t/frigate-mobile-app-notifications/311091

**Comment by adamderuwe** [comment, marked as answer]
Here's my updated automation that works for sending images on new detections.
```

  - alias: Notify Camera Events Telegram
    id: "NotifyCameraEventsTelegram"
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      condition: and
      conditions:
        - "{{'new' in trigger.payload_json['type']}}"
        - condition: or
          conditions:
            - "{{ 'driveway' in trigger.payload_json['after']['entered_zones'] }}"
            - "{{ 'frontdoorzone' in trigger.payload_json['after']['entered_zones'] }}"
    action:
      - service: telegram_bot.send_photo
        data_template:
          url: 'https://hass.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=1'
```
