### DISCUSSION TITLE
Frigate Detect and Motion

### DISCUSSION THREAD

**Discussion by stamandr** [blakeblackshear/frigate#2861] [Ask A Question]
If detect is turned off will motion still work ? In other words, I don't need object detection, only motion detection for any motion. I also need motion detection to save the clips/recordings. Is this possible ?

**Comment by NickM-27** [comment]
With the latest version `0.10.0` you can disable detect and motion detection will still run. 

Then you will need your config to be:

```
record:
  enabled: true
  retain:
    days: x
    mode: motion // this means for 24/7 recording only segments with motion will be saved
````

I don't believe there will be events as that requires an object, but 24/7 recording with only segments that include motion is possible

**Reply by stamandr** [reply]
Will snapshots be saved as well ? I'm trying to get away from Frigates high inference and CPU load in the absence of Coral USB availability
Do my settings look correct ?
record:
  enabled: true
  retain:
    days: 1
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    retain:
      default: 1
      mode: motion
      objects:
        person: 5
        car: 5

snapshots:
  enabled: true
  timestamp: false
  bounding_box: false
  retain:
    default: 1
``

**Reply by blakeblackshear** [reply]
No. Snapshots are dependent on object detection.

**Reply by stamandr** [reply]
Can I add the following below to snapshots to save the snaps ?

mode: motion
objects:
  person: 5
  car: 5

**Reply by NickM-27** [reply]
> Can I add the following below to snapshots to save the snaps ?
> 
> 
> 
> mode: motion
> 
> objects:
> 
>   person: 5
> 
>   car: 5
> 
> 
> 
> 

That config is not supported for snapshots as snapshots do not have motion data.

**Reply by blakeblackshear** [reply]
There is no way to configure Frigate to take a snapshot for motion currently.

**Reply by stamandr** [reply]
Understood.....  This is my config for record (global args), but still can't get it to record motion events with detect off. Do I have something wrong here ?

```record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
     max_seconds: 300
     pre_capture: 3
     post_capture: 3
     objects:
       - person
       - car
     retain:
       default: 1
       mode: motion
       objects:
         person: 5
         car: 5
```

**Reply by NickM-27** [reply]
@stamandr It depends what you mean by "record motion events". Currently, with **detect disabled** there will be nothing in the `events` tab. You will just view your 24/7 recordings and the only parts that will show up will be parts with motion.

**Reply by stamandr** [reply]
Noted.... What I am trying to do is have my HA automation announce that someone is at the front door when motion is detected with my settings above. If detect is on, it works perfect. Any ideas on what I am missing ?

![trigger](https://user-images.githubusercontent.com/51379504/155813849-9e95a2cd-04d3-47e8-82f8-9f7626279903.jpg)

**Reply by NickM-27** [reply]
@stamandr The sensor you are using is "Person Motion Started". While there is motion in the name it does require `Person` which only works with object detection being on.

**Reply by stamandr** [reply]
Thanks... Is there anyway that you know of to make this automation work without using detect ?

**Reply by NickM-27** [reply]
> Thanks... Is there anyway that you know of to make this automation work without using detect ?

Not currently. Is the reason you don't want to use detect a lack of a coral accelerator?

**Reply by stamandr** [reply]
Yes it is.... I keep thinking that if Frigate knows about motion detection and creates recordings, there must be a way to tag onto that process for an automation....

**Reply by NickM-27** [reply]
> Yes it is.... I keep thinking that if Frigate knows about motion detection and creates recordings, there must be a way to tag onto that process for an automation....

I mean there is a way in the sense that it could be added, but today that functionality doesn't exist.

**Reply by joaldes** [reply]
> With the latest version `0.10.0` you can disable detect and motion detection will still run.
> 
> Then you will need your config to be:
> 
> ```
> record:
>   enabled: true
>   retain:
>     days: x
>     mode: motion // this means for 24/7 recording only segments with motion will be saved
> ```
> 
> I don't believe there will be events as that requires an object, but 24/7 recording with only segments that include motion is possible

Will Frigate send a MQTT message if motion is detected?  I am also currently without a coral (on a pi4), so trying to find a good balance between usage and features.  So I could turn off detect and enable motion only and reduce the demand on the CPU.

My short term goal is to trigger security lights on motion, but long term would be only if people, etc. I understand I need a coral to really leverage the features for Frigate.

**Reply by NickM-27** [reply]
No, there are currently not any MQTT messages sent for motion, only object detection.

**Reply by joaldes** [reply]
Thanks for the quick reply!  It really does look like I would need to upgrade my hardware to a NUC (or similar) in order to detect with Frigate without a coral.

**Reply by blakeblackshear** [reply]
I want to add more sensors specific to motion for users without a coral in the next version.

**Reply by joaldes** [reply]
That would be great!  I'm super bummed I'm not able to find a coral, because I wish I could utilize more Frigate features.

**Reply by Eyeball753** [reply]
> No, there are currently not any MQTT messages sent for motion, only object detection.

Is this why I can't just have Frigate detect motion without recording?
I was looking for a way to use my camera as a motion sensor without recording anything. To trigger lights, for example. That's how I stumbled upon this thread. I do not have a coral, in case that matters to motion detection.

**Reply by NickM-27** [reply]
@eyeball753 this is outdated. With frigate 0.11 it is supported.

**Reply by jschwalbe** [reply]
@NickM-27 Sorry to resurrect this, but I'm not sure I see how to do this. To be clear, my goal is to record ANY motion. (Catching a mouse!) Is this doable? Thanks!

**Reply by NickM-27** [reply]
So just make the motion detection extremely sensitive?

**Reply by jschwalbe** [reply]
I don't think the level of motion detection is the problem; I don't understand how to tell it to record *motion only* events (when there isn't a person detected, for example). Any guidance you can provide is appreciated!

Here is my relevant config: 
```
  garage:                             #### GARAGE ####
    ffmpeg:
      inputs:
        - path:  rtsp://login@ip:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # rtsp://127.0.0.1:8554/familyroom?video=copy&audio=aac
          roles:
            - record
            - detect
          input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy

    detect:
      width: 1920
      height: 1080
      fps: 5
      #interval: 10
      #threshold: 50
    motion:
      mask:
        - 640,21,640,45,450,45,436,21
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:   
        default: 0
        objects:
          person: 15
    record:
      enabled: true
      retain:
        days: 10
        mode: motion
      events:
        retain:
      # Required: Default retention days (default: shown below)
          default: 10       
          mode: motion
    objects:
      track:
        - person
```
