### DISCUSSION TITLE
Frigate, add masks to captured video?

### DISCUSSION THREAD

**Discussion by Fettkeewl** [blakeblackshear/frigate#2866] [Ideas]
Hello! 

Thank you for an amazing NVR! 
Frigate is awesome in all aspects. I'm so satisfied that I don't
have to rely on Blue Iris och Netcam and the likes. 

**I have a question:**
Here in Sweden, we got strict laws in regards to private camera surveillance.
In short we are allowed to surveil our own property and nothing else, that means a camera that
shows even a part of the public sidewalk is to be considered illegally installed. 

Now I have a camera which I can't angle any better than it is already to minimize the public areas seen.
I was wondering if it was possible to apply the masks we create for "non-detect" areas to the video that is recorded
when motion is detected. So basically making some areas black as a part of the video...
 

With regards!

This area would have to be blackened in captured video
![image](https://user-images.githubusercontent.com/25577040/155292878-89885cc8-ad69-4f25-9951-24618e66cf4e.png)

**Comment by blakeblackshear** [comment]
In order to modify the recorded video, you will need to re-encode. You can use ffmpeg to [overlay images on the video](https://video.stackexchange.com/a/12111). This will take a lot of CPU resources, so I would suggest replacing the camera with one that can add these privacy filters to the stream directly.

**Reply by Fettkeewl** [reply]
> In order to modify the recorded video, you will need to re-encode. You can use ffmpeg to [overlay images on the video](https://video.stackexchange.com/a/12111). This will take a lot of CPU resources, so I would suggest replacing the camera with one that can add these privacy filters to the stream directly.

Ah .. was worth a shot, I figured that might be an issue. Thank you for your time :)

**Reply by KostyaSha** [reply]
even if it consume resources it would be good to has. CPU detector is also a pure performance thing, but it available.

**Comment by antan951** [comment]
Hello
I also need to mask some areas of the camera feed to comply with local rules and the cameras I already acquired are not up to the task. was hoping that it would be possible to mask at least the reduced resolution feed that is used for detection and did some trials outside of frigate.

This command sequence seem to do the trick:
`ffmpeg -loglevel info -hide_banner -c:v h264_qsv -i 'rtsp://username:password@camera_ip:554/cam/realmonitor?channel=1&subtype=2' -i triangle-overlay.png -filter_complex 'overlay' test.mp4`
I tried both on a local computer and from within the docker container and they both produce a video file that has been correctly masked.

Then I tried to "fool" Frigate into doing the same by squeezing the mask into the - path: section for the camera.
`path: rtsp://username:password@camera_ip:554/cam/realmonitor?channel=1&subtype=2 -i /media/frigate/triangle-overlay.png -filter_complex 'overlay'`

Unfortunately it does not seem to work. Frigate starts without anything unusual in the log, but the mask has not been applied.
In the debug section, I see this ffmpeg cmd:`
"cmd": "ffmpeg -loglevel info -hide_banner -c:v h264_qsv -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://username:password@camera_ip:554/cam/realmonitor?channel=1&subtype=2 -i /media/frigate/triangle-overlay.png -filter_complex 'overlay' -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",`
This looks quite good to me, and it seems that the additional arguments survived the configuration parser.

Any advice how to proceed would be highly appreciated.

**Reply by NickM-27** [reply]
They would need to be part of the output args for the given role, not the input.

**Reply by antan951** [reply]
Hi Nick
I tried this and it works!
This is the new ffmpeg cmd:`
"cmd": "ffmpeg -loglevel info -hide_banner -c:v h264_qsv -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:password@camera_ip:554/cam/realmonitor?channel=1&subtype=2 -r 5 -s 1280x720 -i /media/frigate/back-cam_overlay.png -filter_complex 'overlay' -f rawvideo -pix_fmt yuv420p pipe:",`

The only difference I can make out from before, is that the arguments `-r 5 -s 1280x720` have shifted, so that they are now placed between the rtsp-stream input and the overlay. I'm happy it works now, but I'd like to learn why... Until now I thought they were needed by the rawvideo output that is piped to the further frigate processing steps, but does this imply that they are needed to clarify the rtsp input?

**Reply by NickM-27** [reply]
`-r 5 -s 1280x720` need to be applied to the incoming rtsp feed before output, they do not apply to the mask that is being added. Just like how -filter_complex output arg is applied to the png and not the rtsp feed. Then the output format and pixel format are set

**Reply by hotzen** [reply]
Could you please share how to incorporate this into an actual frigate config.yml, i cant find any `cmd` key in https://docs.frigate.video/configuration/reference/

**Reply by hotzen** [reply]
@antan951 @NickM-27 could you please give me a kickstart with some frigate-yaml config? i fail to understand where to define a `cmd`

**Reply by NickM-27** [reply]
you don't change the config. You would add the output args to the

```
output_args:
  record: 
```

section

**Reply by antan951** [reply]
Hi everyone
Yes, this is exactly what I did.
```
output_args:
  record: -i /media/frigate/back-cam_overlay.png -filter_complex 'overlay' -f rawvideo -pix_fmt yuv420p
```
I made this quite long time ago, but I remember that it took some trial and error to get the format and transparency of the PNG image working correctly. This trick can also be applied to the detect channel, so that Frigate won't be able to detect anything outside of the non-masked areas.

**Reply by ProfessorBoemmel** [reply]
Thanks Antan, 

and that is still working for you with the current version ? Can you share your config and what build you are running on ?  

Just testing your config line - complains about a missing -segment

Will test to add some segment options on my own but so far no luck either,

**Reply by deanpm70** [reply]
Exactly the same result for me. Have spent the day trying various (somewhat random) permutations of config without success.

**Reply by NickM-27** [reply]
The easiest way to do this is inside of go2rtc and then consume that masked stream in frigate for recordings

**Reply by antan951** [reply]
I have not updated the Frigate container in a very long time, could be a year or so...
The systems page on the dashboard says: 0.12.1-367d724
Maybe I should consider myself lucky that it works as well as it does...

I run Frigate on a rather overpowered i7 NUC and I have the following arguments for ffmpeg:
```
ffmpeg:
  hwaccel_args: -c:v h264_qsv
  global_args: -loglevel info -hide_banner
```

**Reply by deanpm70** [reply]
> The easiest way to do this is inside of go2rtc and then consume that masked stream in frigate for recordings

Hi Nick,

Appreciate you've got a lot of stuff going on but a working example of how to do this would be fantastically useful.

Dean

**Reply by ProfessorBoemmel** [reply]
Hi everyone .. 

so i got it working (following examples in [https://hhsprings.bitbucket.io/docs/programming/examples/ffmpeg/] ) 
in an external and also the internal go2rtc - hope it helps. 

If you see improvement, please let me know. 

Now i think i need to live with the CPU used 
and to play with the pre_ and post_capture parameters to fight the delay i might have due to the pre-processing.

```
go2rtc:
  streams:
    mycam: 
      - rtsp://YOURACCOUNT:YOURPASSWORD@YOURIP/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    mycam_small: 
      - rtsp://YOURACCOUNT:YOURPASSWORD@YOURIP/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    mycam_small_blur: 
       - ffmpeg:mycam_small#video=h264#raw=-i /media/frigate/masks/mycam_small_mask.png -filter_complex "[1:v]loop=-1:size=2,scale=320:240,setsar=1[alpha];[0:v]boxblur=10[blur];[0:v][alpha]alphamerge[vt];[blur][vt]overlay"
    mycam_blur: 
       - ffmpeg:mycam#video=h264#raw=-i /media/frigate/masks/mycam_big_mask.png -filter_complex "[1:v]loop=-1:size=2,scale=1280:720,setsar=1[alpha];[0:v]boxblur=10[blur];[0:v][alpha]alphamerge[vt];[blur][vt]overlay"

cameras:
  mycam:
    enabled: true
    ffmpeg:
      inputs:
      - path: 
          rtsp://127.0.0.1:8554/mycam_small_blur
        roles:
        - detect
      - path: 
          rtsp://127.0.0.1:8554/mycam_blur
        roles:
        - record
 ```
