### DISCUSSION TITLE
Coral inference speeds grew by 600% with new server

### DISCUSSION THREAD

**Discussion by mcondren** [blakeblackshear/frigate#2878] [Ask A Question] [answered]
Hi All,

I’m trying to figure out what happened when I moved to my new server. I was using an i5 8th gen with 16gb ram, and a USB Coral on Debian. I had very low inference times. 8-10.  I just moved to a 7th gen celeron J1900 2.4ghz (4 core) as it was more power efficient. It has intel HD graphics on-board, same as my old server.  However, with my new one the Frigate debug stats are showing 68-78 inference times with the exact same usb coral. I’m confused. I realize the cpu is a bit less powerful, but I reduced the resolution of my detect streams and it should still be doing the detections on the coral. The frigate container was copied over with the existing config from the old server. Logs say TPU found. 

Any ideas? I get lots of activity in intel_gpu_top, so hardware decode is working fine, it’s the coral part that doesn’t seem to be. Config below. (Same config as old server). 

```
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: mosquitto.ansible.house
  topic_prefix: frigate

ffmpeg:
  #  global_args:
  #    - -hide_banner
  #    - -loglevel
  #    - panic
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  #  input_args:
  #    - -avoid_negative_ts
  #    - make_zero
  #    - -fflags
  #    - nobuffer
  #    - -flags
  #    - low_delay
  #    - -strict
  #    - experimental
  #    - -fflags
  #    - +genpts+discardcorrupt
  #    - -rtsp_transport
  #    - tcp
  #    - -stimeout
  #    - '10000000'
  #    - -use_wallclock_as_timestamps
  #    - '1'
  #  # Optional: global output args (default: shown below)
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

objects:
  track:
    - person
  filters:
    person:
      threshold: 0.75
      min_area: 0

record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    retain:
      default: 30
      mode: all

snapshots:
  enabled: true
  bounding_box: true

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.247:7447/RgXKgNO2IbjVfLPQ
          roles:
            - record
        - path: rtsp://192.168.1.247:7447/sqZQcMFExX1pyDdz
          roles:
            - detect
    rtmp:
      enabled: False
    detect:
      fps: 5
      width: 1024
      height: 576
    live:
      quality: 1
    mqtt:
      timestamp: true
      bounding_box: true
      quality: 100
    objects:
      filters:
        person:
          mask:
            - 0,279,638,89,576,0,0,0

  backporch:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.247:7447/Vd0XQkWIOcQZT2JE
          roles:
            - record
        - path: rtsp://192.168.1.247:7447/aKJmMe4LhSoCEe2w
          roles:
            - detect
    detect:
      fps: 5
      width: 1024
      height: 576
    rtmp:
      enabled: False
    live:
      quality: 1
    mqtt:
      timestamp: true
      bounding_box: true
      quality: 100

  sidedoor:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.247:7447/d5sYi9WdmZQC2gMI
          roles:
            - record
        - path: rtsp://192.168.1.247:7447/kj0bemgzqNaZLu1D
          roles:
            - detect
    detect:
      fps: 5
      width: 1024
      height: 576
    rtmp:
      enabled: False
    live:
      quality: 1
    mqtt:
      timestamp: true
      bounding_box: true
      quality: 100


  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.247:7447/8WhVadvTDKdgrF7Z
          roles:
            - record
        - path: rtsp://192.168.1.247:7447/l2W9W83Wmsf2SFK6
          roles:
            - detect
    detect:
      width: 960
      height: 720
    rtmp:
      enabled: False
    live:
      quality: 1
    mqtt:
      timestamp: true
      bounding_box: true
      quality: 100
    objects:
      filters:
        person:
          mask:
            - 181,204,575,221,472,356,169,334

```
