### DISCUSSION TITLE
Is there a viable alternative to Coral?

### DISCUSSION THREAD

**Discussion by kspearrin** [blakeblackshear/frigate#2918] [Ask A Question]
I have been trying to find a Coral TPU for the past 4 months, but they are out of stock everywhere. Most of the stores I check don't show stock available until later this year. I would really like to adopt Frigate as an NVR, but my understanding is that I need a Coral. Is there a viable alternative to running Frigate in production with 10 cameras?

**Comment by jmorris644** [comment]
Some of us are using a Jetson Nano. But those are getting pricey as well.

**Reply by rgobbel** [reply]
Just started looking at Frigate today, and see this in the **Detectors** section of the documentation:

"There is no support for Nvidia GPUs to perform object detection with Tensorflow."

Has someone actually implemented NVIDIA GPU support, and if so, where's the code?

I have four NVIDIA Jetsons of various types, 3 of them just gathering dust at the moment, and I'd rather not have to buy a hardware device whose basic compute power is less than what I already have on hand. If it's not  crazy amount of effort, I'd be willing to do the implementation myself, but if the basics are already there, that would obviously be preferred.

**Reply by NickM-27** [reply]
Jetson nano support is being added in #2548

**Comment by tube0013** [comment]
M1 based Macs also seem to work well. def high on the price range though.

**Reply by cloudandy** [reply]
@tube0013 except for the networking issues with Docker on MacOS…

**Reply by ireuben** [reply]
@cloudandy do you have any more details of the networking issues? Do they affect Frigate specifically? I've been running Frigate on Docker on macOS for a couple months now, and seems to be working fine.

**Comment by jvrobert** [comment]
If you have a reasonably fast machine multi-core CPU with hardware decode acceleration you may be alright, maybe just give it a try. I was able to get ahold of one of the m.2 dual tpu ones pretty easily, but my machine only uses one of the tpus. Some guy was making adapters to allow both tpus to be used but, umm, we may not be seeing products from the country I think he was from anytime soon.

**Comment by kbrouder** [comment]
I have been running cpu detectors for several weeks now and it works very well. I shut down my blue iris VM completely after testing for just a few days because it worked so well. To be honest, I was left scratching my head a bit as to why there are all the warnings about not using CPU detectors because my setup is working well and overall using less resources than my previous blue iris config. 

I am running it in a dedicated Hyper-v ubuntu VM with docker compose on a dell poweredge R610 (very old server). I believe I have the VM set to 8-10vcpus and ~7-8gb memory. I have 7 cameras, 6 are recording 4k, streaming 2k, and detectors on 640p (hikvision), the last one is a 1080p wireless camera I havent replaced yet. 

Probably not the most power efficient, but it works just fine. Most people probably don't have a hyper-v host server, and I would not recommend that as optimal, but many of the cheap mini pc's available today have celeron processors that are around the same performance as my old dell server (given it has 2 cpus). So anything with a decent processor I would imagine would do just as well. I tested a sub $200 mini pc and it was working just fine as well.

**Reply by kbrouder** [reply]
Oh, and I did manage to get my hands on a dual tpu e-key coral, but have not gotten adapters to work in either my hyper-v server (which doesnt support pci passthrough I now know) or that mini pc... yet...and I have an odyssey blue (backorder) and jetson nano on order (overpaid)..... So, if you want my advice try it on CPU detectors and run that until the stock comes back, or you will waste a lot of $ and time fiddling.

**Reply by kspearrin** [reply]
@kbrouder Thanks. If you ever want to get rid of that Coral TPU, let me know 😄 

I too am on BlueIris now, and looking to replace it with Frigate hosted on a Proxmox server. I will give the CPU detectors a go with all 10 cameras and see how it fares. Would you mind sharing your frigate config.yaml? Are you using hardware acceleration from your CPU as well?

**Reply by kbrouder** [reply]
@kspearrin I was actually going to say that...I have a different adapter on the way to try with the current mini-pc, depending on how that goes and the lead time for the jetsan nano and odyssey blue, I may be willing to sell that TPU and a bundle of adapters for a great price lol. In my research I did see Proxmox come up a lot as probably being able to support the pcie passthrough, so you might be able to do it. I finally came to the conclusion I can't with my current setup. Windows server 2016 and a 10th gen poweredge r610 (11th gen chipset required). That host runs a bunch of VMs including my hass server, so not willing to rebuild to try it just yet lol. 

For HW acceleration I do have this line in my docker-compose.yaml in the devices section:
` /dev/dri/renderD128`
 
Not sure if that is actually doing anything....I am also not entirely sure what I should have for the  "num_threads" setting on the cpu detectors, I tested a few different ways, but didnt see much of a difference...

Here is my config.yml sanitized:

```
mqtt:
  host: <ip>
  user: <hass_user>
  password: <pass>
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3
  cpu5:
    type: cpu
    num_threads: 3
  cpu6:
    type: cpu
    num_threads: 3
  cpu7:
    type: cpu
    num_threads: 3
record:
  enabled: True
  retain:
    days: 4
    mode: motion
  events:
    max_seconds: 300
    pre_capture: 3
    post_capture: 2
    retain:
      default: 5
      mode: active_objects
snapshots:
  enabled: True
  retain:
    default: 5
detect:
  width: 1280
  height: 720
  fps: 7
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 100
    max_frames:
      objects:
        person: 1000
        dog: 200

objects:
  track:
    - person
    - car
    - dog
  filters:
    person:
      min_score: 0.5
      threshold: 0.68
    dog:
      min_score: 0.5
      threshold: 0.68
    car:
      min_area: 1000
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

cameras:
  Front_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://<uname:pass@ip:port>/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://<uname:pass@ip:port>/Streaming/Channels/103
          roles:
            - rtmp
        - path: rtsp://<uname:pass@ip:port>/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 10
    motion:
      mask:
        <..use debug view to draw these>
    zones:
      <..use debug view to draw these>
    objects:
      # below settings different for some cameras depending on objects / zoom etc
      track:
        - person
        - dog
        - car
      filters:
        car:
          min_area: 10000
  <Other Cameras.....>

```

In hyper-v I gave the VM 8 vcpus and over the past week its only peaked around 20-25% load, I started giving it tons of memory before I remembered hyper-v doesnt really know how to deal with linux memory, I have dropped the memory to 7gb, but in reviewing my zabbix charts I really think its only peaking around 2-3gb.
