### DISCUSSION TITLE
Wind triggers motion/object detection

### DISCUSSION THREAD

**Discussion by EmmanuelVella** [blakeblackshear/frigate#2971] [Ask A Question]
Hello all,

I have the following issue : when there is some wind, the camera moves a little bit, and my parked car triggers motion/object detection. How can I improve this ? Thank you !

![snapshot-1647356454 145895-keywls](https://user-images.githubusercontent.com/663607/158440461-22a1d78d-d02d-466b-a069-2e9570ec2282.jpg)

```yaml
mqtt:
  host: 192.168.1.254
  user: mqtt
  password: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

detect:
  enabled: True
  fps: 4
  width: 640
  height: 360

snapshots:
  enabled: True

record:
  enabled: True

birdseye:
  enabled: False

rtmp:
  enabled: False

cameras:
  nord:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Starwars83@192.168.4.10:554/H264/ch1/sub/av_stream
          roles:
            - detect
        - path: rtsp://admin:Starwars83@192.168.4.10:554/H264/ch1/main/av_stream
          roles:
            - record
    motion:
      mask:
        - &camera_nord_mask 640,0,0,0,0,360,52,305,67,103,170,60,640,96
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - *camera_nord_mask
        car:
          mask:
            - *camera_nord_mask
```

**Comment by NickM-27** [comment]
If wind is moving your camera... that is very difficult since that means the entire image has motion. Do you not want your vehicle to be detected at all there or what is the desired behavior?

**Reply by EmmanuelVella** [reply]
I would like that any vehicule triggers an object detection, but not when they are parked. Is there a way to reduce the motion sensitivity, so little movement caused by wind wouldn't be enough to trigger motion, but a rolling vehicle will trigger motion ?

**Reply by NickM-27** [reply]
Reference [this part of the docs](https://docs.frigate.video/configuration/index)

Please don't copy and paste this but use as a reference to adjust values. Also keep in mind this will make general motion detection (besides the wind) also less sensitive.

```yaml
# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: False
```
