### DISCUSSION TITLE
Help w/ Zones?

### DISCUSSION THREAD

**Discussion by efaden** [blakeblackshear/frigate#2973] [Ask A Question]
Hey All,

I am struggling a bit getting my zones correct.  I have a camera facing my driveway.  When I enabled cars in addition to the dog/cat/person I was originally tracking I started getting my parked cars tracked.  I looked at the page on avoiding stationary objects and am a little confused about how to get this config all squared away.  I made 3 zones.  Two where the cars park and a third that is the actual driveway.  I only want to track a car when it moves into or out of the driveway zone like the example.  All well and good, but how do I do that while allowing people/cats/dogs to be tracked in any zone?  Thanks

**Comment by NickM-27** [comment]
There's a few ways you can go about it, but the general way to do this is to essentially have this setup:

- Driveway entrance zone that only does car.
- Another zone that does car, dog, person
- Both zones added into the `required_zones` list. 

The main thing to keep in mind is by adding `required_zones` you then need to make sure you have zone(s) that cover all the areas of interest for car / dog / person.

**Reply by efaden** [reply]
I guess I'm a little confused by how that would work.  Wouldn't that detect the car in the other zone also?  What I'm trying to do is exclude the car from the parked zones so I don't have hours of my car parked recorded.

Would this work....

Zone 1 - Driveway - Cars
Zone 2 - Parking Spot 1 (Used only for events)
Zone 3 - Parking Spot 2 (Used only for events)
Zone 4 - Whole area - People/Dog/Cat

Required zones 1 and 4.  And then I can use Zones 2 and 3 to track when cars go through more than one zone (e.g. from driveway to parking spot)?

**Reply by NickM-27** [reply]
yeah, that's exactly what you'd need to do

**Reply by efaden** [reply]
This is what I have so far.  Going to let it run and see how it works.


```
zones:
      driveway:
        coordinates: 237,416,674,343,646,306,248,349
        objects:
          - car
      garage_parking:
        coordinates: 720,576,220,537,244,411,662,357,720,323
        objects:
          - car
      side_parking:
        coordinates: 277,354,185,337,84,380,239,420
        objects:
          - car        
      everywhere:
        coordinates: 0,576,720,576,720,263,0,265
        objects:
          - person
          - dog
          - cat

    record:
      events:
        required_zones:
          - driveway
          - everywhere

```

**Reply by efaden** [reply]
Not working correctly....

It's detecting a car in the garage_parking zone.... but its also recording it?


```
mqtt:
  host: 10.0.0.110
  user: homeassistant
  password: ZZZZ

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
            - rtmp

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

  side_door:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - record
        - path: rtsp://
          roles:
            - detect
            - rtmp

    # Mask 1 Is Middle Trees
    # Mask 2 Is Pool Gazebo
    # Mask 3 Is Time
    motion:
      mask:
        - 344,0,490,46,526,244,180,262,204,52
        - 0,0,198,0,190,261,0,256
        - 720,0,720,23,495,23,495,0

    zones:
      driveway:
        coordinates: 237,416,674,343,646,306,248,349
        objects:
          - car
      garage_parking:
        coordinates: 720,576,220,537,244,411,662,357,720,323
        objects:
          - car
      side_parking:
        coordinates: 277,354,185,337,84,380,239,420
        objects:
          - car        
      everywhere:
        coordinates: 0,576,720,576,720,263,0,265
        objects:
          - person
          - dog
          - cat

    record:
      events:
        required_zones:
          - driveway
          - everywhere
          
    snapshots:
        required_zones:
          - driveway
          - everywhere

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

detect:
  width: 720
  height: 576
  fps: 5
  enabled: True

objects:
  track:
    - person
    - dog
    - cat
    - car

record:
  enabled: True
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True

```
