### DISCUSSION TITLE
Intel Hardware Acceleration args n/w

### DISCUSSION THREAD

**Discussion by Morphy99** [blakeblackshear/frigate#2976] [Ask A Question]
I'm not sure if this is an issue with my config but whenever I enable the recommended hw acc. args I get more CPU usage. My CPU is a Intel Celeron N4000 which is a gen 9.5 CPU (Gemini Lake). I'm running on docker with a debian based distro and have the correct /dev/dri/renderD128 passthrough specified on the container.

I also have LIBVA_DRIVER_NAME=i965 defined in the container.

Output of  `ls -alh /dev/dri/render*` is
`crw-rw---- 1 root render 226, 128 Feb 22 08:25 /dev/dri/renderD128`

With the recommended args,
```
ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```
the CPU looks like this:
![image](https://user-images.githubusercontent.com/5853979/158636877-16fcbe52-caec-413e-8eda-2e7d0aac330f.png)

And with just, 
```
ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  hwaccel_args:
    - -hwaccel_output_format
    - yuv420p
```
it looks like this:
![image](https://user-images.githubusercontent.com/5853979/158637086-f37b5fad-b08e-4f2b-a505-952a4be8ba9c.png)

I have Reolink RTMP cameras in my config. Have tried with the suggested http streams even though RTMP has been reliable for me and no change.
