### DISCUSSION TITLE
Use local videofile as camera

### DISCUSSION THREAD

**Discussion by riskendemism** [blakeblackshear/frigate#2983] [Ask A Question] [answered]
Hello from Vienna,

i would like to use a local videofile (mp4, mkv, etc.) as "camera" but I could not find anything about it in the documentation.

Where do I have to put it on the local machine (where frigate ist running in a docker container) and what input is needed in the path section of the configfile?

Thank you for your help!
Cheers Chris

**Comment by blakeblackshear** [comment, marked as answer]
Here is an example from the developer docs: https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing

**Reply by inspired27** [reply]
> Here is an example from the developer docs: https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing

Hi,

I am running Frigate in docker in LXC Promox container.

I have put the following in /home/frigate/config.yml and the pano.mp4 in /home/frigate/pan0.mp4  however I get an error see the portainer log: 

```
cameras:
  test:
    ffmpeg:
      inputs:
        - path: /home/frigate/pano.mp4
          roles:
            - detect
            - rtmp

    detect:
      width: 1920
      height: 540
      fps: 5
```

Portainer Log:

[2022-11-14 11:51:44] ffmpeg.test.detect             ERROR   : /home/frigate/pano.mp4: No such file or directory
[2022-11-14 11:51:44] frigate.video                  ERROR   : test: Unable to read frames from ffmpeg process.
[2022-11-14 11:51:44] frigate.video                  ERROR   : test: ffmpeg process is not running. exiting capture thread...

Do you know where the ffmpeg log is located?

**Reply by NickM-27** [reply]
What does your docker compose look like? Odds are you're only passing the config.yml fine directly and not the whole config directory so frigate can't see it

**Reply by inspired27** [reply]
> What does your docker compose look like? Odds are you're only passing the config.yml fine directly and not the whole config directory so frigate can't see it

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/frigate/config.yml:/config/config.yml
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
