### DISCUSSION TITLE
Which Substream to Choose?

### DISCUSSION THREAD

**Discussion by efaden** [blakeblackshear/frigate#2991] [Ask A Question]
So I have a little issue and I'm trying to figure out how to solve.  I have 2 AD410s.  The only have two streams, one is really low resolution and one is 2k.  I am currently running detect on the lower resolution camera and recording on the higher.  This is all well and good, except that I when it sends the snapshots over the double take the resolution of the snapshot is SO low it can't do any recognition on it.  

Suggestions for how to modify my config to send higher resolution images over to double take?

Config is 

```
mqtt:
  host: 10.0.0.110
  user: homeassistant
  password: 

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: URL
          roles:
            - record
        - path: URL
          roles:
            - detect
            - rtmp

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

  side_door:
    ffmpeg:
      inputs:
        - path: URL
          roles:
            - record
        - path: URL
          roles:
            - detect
            - rtmp

    # Mask 1 Is Middle Trees
    # Mask 2 Is Pool Gazeebo
    # Mask 3 Is Time
    motion:
      mask:
        - 344,0,490,46,530,179,190,191,204,52
        - 0,0,198,0,190,261,0,256
        - 720,0,720,23,495,23,495,0

    zones:
      driveway:
        coordinates: 237,416,674,343,646,306,248,349
        objects:
          - car
      garage_parking:
        coordinates: 720,576,220,537,244,411,662,357,720,323
        objects:
          - car
      side_parking:
        coordinates: 277,354,185,337,84,380,239,420
        objects:
          - car        
      everywhere:
        coordinates: 0,576,720,576,720,263,0,265
        objects:
          - person
          - dog
          - cat
          - bicycle

    record:
      events:
        required_zones:
          - driveway
          - everywhere

    snapshots:
        required_zones:
          - driveway
          - everywhere

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500

detect:
  width: 720
  height: 576
  fps: 5
  enabled: True
  stationary:
    max_frames:
      objects:
        person: 100
        cat: 100
        dog: 100
        bicycle: 100

objects:
  track:
    - person
    - dog
    - cat
    - car
    - bicycle

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 5
      mode: motion
    pre_capture: 5
    post_capture: 15

snapshots:
  enabled: True
  timestamp: False
  crop: False
  bounding_box: False
  retain:
    default: 10
    objects:
      person: 15
```
