### DISCUSSION TITLE
"recordings" page - weird behaviour when clicking through events

### DISCUSSION THREAD

**Discussion by mu71rd** [blakeblackshear/frigate#2998] [Ask A Question]
firstly, amazing software - am really impressed with how easy it has been to set up and get working. the object detection is amazing to watch in the debug window. 

My use is that I have recording turn on/off via an automation in HA so that it's only recording on my (test) indoor camera when the alarm is set or we are out. I don't need or wish to record people routinely going about their day. 

What I cannot work out is how best to use the 'recordings' page. If I click on that, it shows me a bunch of events on the right hand side, but when I click on each one it takes me to the same place in the same video (generally when I last rebooted or started recording). I would have thought it would jump to the part of the recording relating to that action, but it does not. Am i missing something here? 

I have the system record (with a 3 day full 24/7 retention i think, and 30 days for events) and so when I click on a recording, it could potentially play for a long long time. How is this 'recordings' window (which I get to by clicking 'recordings' under the camera list) supposed to work? If I go to events, each event is listed and they all bring up the correct clip - but I thought i'd be able to view more either side with the recordings window. 

Here's a redacted version of my config file, in case it's useful...

thanks for any help in advance. 

```yaml
mqtt:
  host: XXXXXX
  user: XXXX
  password: XXXX

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

record:
  enabled: True
  retain: 
    days: 3
    mode: all
  events:
    retain:
      default: 30

cameras:
  Kitchen: 
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.147:554/stream1 
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False 
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,344,284,225,612,121,925,112,1125,111,1472,162,1595,198,1920,343,1920,0,0,0
        
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
```
