### DISCUSSION TITLE
Disabling Detection, Recording, etc. Using Home Assistant

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#3065] [Ask A Question] [answered]
I asked in a previous post about disabling detection and received the answer:

> Hi, yes detection, snapshots, and recording are all completely toggleable and can be disabled by default. They can also be controlled using the HomeAssistant integration in case you wanted to run detection on two or three at a time, but different cameras at different times of the day / night.

I thought I could easily figure out how to do that, but I'm at a loss. I looked under home assistant entities for frigate to see if there was a switch for that, but nothing was obvious. A web search didn't turn up anything. So, how do I turn on and off those options? All my automations are in Node-Red if that makes any difference.

**Comment by NickM-27** [comment, marked as answer]
This can be done multiple ways. Through the frigate UI is easiest for manually doing it. These are the home assistant entities (excuse the hidden part, that is my setup) that are under each camera device:

`switch.backyard_cam_detect`

<img width="323" alt="Screen Shot 2022-04-07 at 8 16 20 PM" src="https://user-images.githubusercontent.com/14866235/162350080-b399ac77-371d-4487-9f07-ca892f7b8c53.png">

**Reply by gcortes** [reply]
And I looked right at them. Thanks

**Reply by loocd** [reply]
> This can be done multiple ways. Through the frigate UI is easiest for manually doing it. These are the home assistant entities (excuse the hidden part, that is my setup) that are under each camera device:
> 
> `switch.backyard_cam_detect`
> 

Just found this issue because I have the exact same need. I'd want to use HA automations to activate/deactivate streams (e.g. turn off indoor cams if someone is home, turn them on as soon as everyone leaves).

Looking at the three switches you mentioned: this doesn't really stop the live stream, only the recordigns, right?

**Comment by MStapelfeldt** [comment]
Hi, I have a similar problem with the detection to switch off and on:
This is my frigate screen:
![Screenshot_2024-01-28-11-35-16-898_io homeassistant companion android-edit](https://github.com/blakeblackshear/frigate/assets/6480145/31185634-f71d-47ea-bccf-74f9329e9ab5)
And this is the HA integration:
![Screenshot_2024-01-28-11-35-47-214_io homeassistant companion android-edit](https://github.com/blakeblackshear/frigate/assets/6480145/37c14cd9-ec45-4605-abab-c6dd81c5aa50)
As you see, HA says integration on, Frigate says off. Whenever I toggle one of these, the other doesn't know. 😅 Do my automation to switch detection on/of when I leave the house, doesn't work as well.
Here is the relevant config:
```
mqtt:
  host: 192.168.178.***
  port: 1883
  user: *********
  password: ******************
cameras:
  fri_wohnzimmer_cam:
    ffmpeg:
      input_args: preset-rtsp-udp
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:*****************:554/onvif1
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.6
          threshold: 0.8
          min_area: 700
        dog:
          min_score: 0.6
          threshold: 0.3
          min_area: 600
          max_area: 10000
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
          objects:
            person: 5
            dog: 7
  
detectors:
  coral:
    type: edgetpu
    device: usb
```

Any idea what's wrong? I'm using the full access version 0.12.1 and the logs don't give me a hint why it's not working.
