### DISCUSSION TITLE
Using RTMP with Home Assistant

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#3073] [Ask A Question] [answered]
I'm fine tuning my initial setup of Frigate. The documentation mentioned using RTMP with Home Assistant:

> Frigate can re-stream your video feed as a RTMP feed for other applications such as Home Assistant to utilize it at rtmp://<frigate_host>/live/<camera_name>. Port 1935 must be open. This allows you to use a video feed for detection in frigate and Home Assistant live view at the same time without having to make two separate connections to the camera.

I added the option to one of my cameras:
```
cameras:
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
```
After a restart, the camera appears to be working normally. In Home Assistant, I'm using the frigate card to display live feeds. For a given card, the camera is set to auto and is using the camera.drive_way entity. Is there anything I have to do to use the RTMP feed? Can I change the -rtmp to the high res camera, 101? All my cameras are HIKVision.
