### DISCUSSION TITLE
Entities Have Become Unavailable in Home Assistant

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#3074] [Ask A Question] [answered]
I had Frigate set up and working fine with Home Assistant. Since then I've been making a number of changes to my frigate config for various purposes. When I checked the Home Assistant entities, it now looks like this:

<img width="1100" alt="2022-04-09_09-40-13" src="https://user-images.githubusercontent.com/5271010/162583365-d113dfc5-8368-4309-bf0c-fc8001181c40.png">

The error is unavailable. This is my config for the camera in the image:
```
cameras:
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 51,480,42,418,152,354,151,308,207,265,246,275,380,292,487,311,506,343,553,367,566,480
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,246,40,403,142,357,151,307,112,271,170,250,316,275,504,347,586,480,640,480,640,0,0,0
    zones:
      near_driveway:
        coordinates: 159,360,163,307,233,279,358,318,496,343,604,480,213,480,0,480,36,406
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
```
The errors appear on all cameras. What did I screw up?
