### DISCUSSION TITLE
Starter config file for Raspberry Pi 4B with the camera port

### DISCUSSION THREAD

**Discussion by yllekz** [blakeblackshear/frigate#3079] [Ask A Question]
Hi folks, I'm running into a wall trying to configure Frigate with my Pi 4B (4GB RAM) that has a singular camera attached to the dedicated camera port. 

Up to this point I've been using it with [kerberos](https://github.com/kerberos-io/kerberos-docker/) with no issues.  That app only requires you to map the device in the docker-config file to get started. Frigate oddly seems to require a separate config file to get the app to start up and see the camera.

I've experimented with a few iterations of the docker-compose/config files for Frigate but I can't get it to work. I always get errors stating either the config file is invalid or something of the sort.

I'm also not sure what the "MQTT" portion is for. I don't have an MQTT server..I simply have Home Assistant. I'm not sure if that portion is needed or not.

Can anyone let me know what the correct syntax/config should look like for this?

Here's what I have so far (I tried to put my questions inline):

**docker-compose.yml:**
```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerconfig/frigate/config/frigate-config.yml:/config/config.yml:rw
      - /dockerconfig/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

**frigate-config.yml:**
```
---
#Not sure if this is needed?
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

#Not sure if this is needed?
mqtt:
  host: 192.168.1.100
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: "password"

#Is this correct? Do I need to know the address/ports if I'm just using a directly attached RPi camera?
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:ABCDEFG@192.168.1.140:554/H.264
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -c:v
        - h264_mmal
    height: 1080
    width: 1920
    fps: 60
```

**Comment by NickM-27** [comment]
This needs some work, I updated your camera section with some notes:

```yaml
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:ABCDEFG@192.168.1.140:554/H.264
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -c:v
        - h264_mmal
     
    detect: # <------ you were mising the detect header and needed the other parts to be indented
      height: 1080
      width: 1920
      fps: 60 # <------ this is WAYYY too much fps for frigate to be doing detection on, that will be way more than a Pi can handle
```

1. The frigate config file is needed because otherwise the docker config would be absolutely massive. There is loads of behavior to define as you can see.
2. MQTT is required, this is the way that frigate can communicate with home assistant and also allow its state to be configurable.
