### DISCUSSION TITLE
Frigate Stopped Logging Events

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#3094] [Ask A Question] [answered]
I've been into fine tuning Frigate to capture events I'm not interested in. Last evening was my last recorded event. I was trying to adjust one camera today by walking right up to it to get it to trigger, but it doesn't I've rebooted frigate a couple of time since and don't see any errors in the log. My Quickcam app also stopped displaying last night. I restart fixed it. In the frigate app, I'm seeing action on the live feed. I'm running top on the Ubuntu instance running frigate in docker and see frigate.detecto at the top of CPU usage most of the time. I have eight camera with detection disabled on six of them. In debug, I'm not seeing any skipped frames. Any thoughts on how I can fix this?

**Comment by NickM-27** [comment]
What is your config? Odds are based on what you described it is working just that the config is setup such that events aren't being created

**Comment by gcortes** [comment]
I don't think I changed it in that regard, but I could have. Here's most of it. Additional cameras aren't included. It was the front_porch camera I was walking under. I commented out the person zone to eliminate it as the cause. I notice in a search on the problem that an example had clips defined as an input role. I've never had it.

```
mqtt:
  host: 10.0.0.185
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: curt
  password: REDACTED
#  password: {FRIGATE_MQTT_PASSWORD}
  stats_interval: 60

detectors:
  cpu1:
    type: cpu
    num_threads: 3

cameras:
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 51,480,42,418,152,354,151,308,207,265,246,275,380,292,487,311,506,343,553,367,566,480
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,246,40,403,142,357,151,307,112,271,170,250,316,275,504,347,586,480,640,480,640,0,0,0
    zones:
      near_driveway:
        coordinates: 159,360,163,307,233,279,358,318,496,343,604,480,213,480,0,480,36,406
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  

  north_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 144,0,205,480,0,480,0,0
        - 422,480,338,299,340,258,241,139,215,80,220,0,640,0,640,480
    zones:
      north_yard_walk:
        coordinates: 420,480,338,299,338,253,304,206,270,164,243,127,224,79,213,0,149,0,154,169,210,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  

  back_door:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      enabled: False
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,0,402,0,640,0,640,117,515,142,31,235,229,187,67,229,101,480,0,480
    zones:
      back_door_isolation:
        coordinates: 73,456,31,235,345,169,523,150,560,225,559,332,560,436
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  

  south_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      enabled: False
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 523,0,640,0,640,117,640,480,532,480,400,480,407,191,525,88
        - 0,0,0,480,113,313,68,169,221,102,386,55,378,0
    zones:
      south_yard_isolation:
        coordinates: 63,480,128,278,111,210,304,139,410,149,406,233,370,332,408,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  

  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
      # filters:
      #   person:
      #     mask:
      #       - 431,480,458,406,517,268,552,177,640,177,640,277,640,366,608,480    
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,0,402,0,640,0,640,136,515,142,454,233,257,359,202,426,101,480,0,480
    zones:
      front_porch_isolation:
        coordinates: 414,480,472,376,518,262,467,230,462,189,526,199,554,166,619,159,619,322,607,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
```
