### DISCUSSION TITLE
Making My Detection Efficient

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#3100] [Ask A Question] [answered]
I've set up my driveway camera with a near_driveway zone for detection in which I have an interest. It appears to be working fine. I also get detection events for outside that zone, which it lists being from the driveway camera, but not in a zone. I don't care about these events as there is a fair amount of foot traffic on my side walk. Is it worthwhile to eliminate those detections in the interest of reducing CPU/disk overhead? I don't have a Coral. Hopefully, I'll get it in June.

Here's the config for the camera:

```
cameras:
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 262,129,367,116,438,116,640,133,640,0,230,0,0,0,0,62,0,172,69,171,168,158
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,365,51,346,21,224,32,184,151,131,228,123,353,114,442,114,545,121,640,121,640,0,0,0
    zones:
      near_driveway:
        coordinates: 138,358,163,327,144,271,206,263,287,292,367,311,496,343,604,480,213,480,50,480,36,406
        objects:
          - person
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
```
Here's an example of a capture that isn't useful:
<img width="519" alt="2022-04-13_12-29-19" src="https://user-images.githubusercontent.com/5271010/163255795-bef0b320-2036-47a4-9f13-b699eb97b0e4.png">

Here's the debug view with the zones, masks, etc. on:

<img width="792" alt="2022-04-13_12-31-04" src="https://user-images.githubusercontent.com/5271010/163256179-32b7f836-7fd2-4655-bc6c-4c8bb028d5af.png">

I didn't mask out more of the area based on what I read on the Mask page in the documentation. My understanding was that it needed additional unmasked data to make an accurate determination. The person mask is about the same as the motion mask. Would making the person mask much larger take away from Frigates ability to analyze events?
