### DISCUSSION TITLE
Mailbox and Garbage can as person

### DISCUSSION THREAD

**Discussion by ExceedingLife** [blakeblackshear/frigate#3103] [Ask A Question]
Hello all,

So I been researching the forums and I believe  i know the answer, but i wanted to ask and see if there are any other options as well. So i have a garbage can across my alley that has been making my detection go off all the time. it doesnt ever move so I dont really understand why it thinks its a person. Now a new one the mailbox in my front yard made the person detection go off as well. This also doesnt move.
I'm going to assume I should set a zone and set a min_area property for this zone to help with these detections? 
I just have to figure out the size needed for min_area. (Not really sure about this yet) Is there any other options possible for this? I thought a recent update the camera would look at previous frames and only detect something if the object has moved in a frame,
Anyways I would live to hear everyones input.

Thank you
![garbagecan](https://user-images.githubusercontent.com/8807604/163409682-66bef1c0-2758-4eb7-800d-54b091592b99.PNG)
![mailbox](https://user-images.githubusercontent.com/8807604/163409685-f41b1b35-29b5-4053-88ec-3aa5e45e2e42.PNG)
!

**Comment by NickM-27** [comment]
Since these objects don't move and are false positives, the best solution is to put a person mask at the bottom center of their bounding boxes

**Comment by blakeblackshear** [comment]
Setting min_area on a zone won't prevent anything from being detected. That only changes when a zone is triggered.

You want to start by applying object filters for the camera. If you have static objects in the frame that the models regularly gets confused about, object filter masks can be used as a last resort.

**Comment by ExceedingLife** [comment]
So this is what I currently have in my frigate.yml.

I have an object mask I believe already which should be stopping from having a person in this area which is a zone on my camera.
This is the object mask and motion mask right? to stop false positives in an area? 
I'm still learning the yml and config of frigate.
Thank you all for the help I greatly appreciate it.

```
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.14:554/11
          roles: 
            - detect
            - record
            - rtmp
    zones:
      back_alley:
        coordinates: 547,432,230,637,185,557,110,424,261,324,428,230,735,78,784,213
        objects:
          - car
          - person

        # Optional: Zone level object filters.
        filters:
          dog:
            threshold: 0.6
      back_porch:
        coordinates: 1920,1080,1920,622,1626,588,1204,548,562,578,381,512,0,790,0,1080
        objects:
          - person
          - dog
          - cat
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
            mask:
              - 1920,961,1920,1080,1804,1058,1762,1043,1763,973,1796,879,1742,855,1671,849,1575,978,1491,952,1578,801,1599,688,1654,582,1748,451,1820,356,1920,332
              - 259,309,340,246,384,237,715,75,582,76,568,0,660,62,797,0,0,0,0,411,62,418,72,373,105,359,123,386
          dog:
            min_area: 1000
            max_area: 75000
            threshold: 0.6
    motion:
      mask:        
        # Grill Mask (False Positives)
        #- 1920,961,1920,1080,1804,1058,1753,1080,1538,1014,1431,954,1578,801,1599,688,1638,582,1733,450,1813,323,1920,332
        - 1920,961,1920,1080,1804,1058,1762,1043,1763,973,1796,879,1742,855,1671,849,1575,978,1491,952,1578,801,1599,688,1654,582,1748,451,1820,356,1920,332
        #- 1920,961,1920,1058,1796,1044,1760,1024,1793,968,1796,879,1762,942,1671,849,1619,869,1605,822,1635,687,1707,591,1782,459,1852,370,1920,360
```

![image](https://user-images.githubusercontent.com/8807604/163608068-e986acee-1375-41c1-bb59-dbc7041fd484.png)

**Reply by NickM-27** [reply]
Motion mask won't help with that (as the docs describe). The object mask should be remember that it is based on the bottom center of the bounding box, not how much the mask overlaps the object

**Reply by ExceedingLife** [reply]
Is there a way I can put an object filter mask on my whole camera and not just have it in a specific zone? I don't have any zones that cover the whole area I;m looking for. The object part that is commented out is my main camera. I have tried something like this. but my Frigate.yml is not valid.

```
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.14:554/11
          roles: 
            - detect
            - record
            - rtmp
    # rtmp: 
    #   enabled: true
    # objects:
    #   - person
    #   - dog
    #   - cat
    #   - car
    # filters:
    #   person:
    #     mask:
    #       - 259,309,340,246,384,237,715,75,582,76,568,0,660,62,797,0,0,0,0,411,62,418,72,373,105,359,123,386
    zones:
      back_alley:
        coordinates: 547,432,230,637,185,557,110,424,261,324,428,230,735,78,784,213
        objects:
          - car
          - person
        # filters:
        #   person:
        #     # min_area: 5000
        #     # max_area: 100000
        #     # threshold: 0.7
        #     mask:
        #       - 259,309,340,246,384,237,715,75,582,76,568,0,660,62,797,0,0,0,0,411,62,418,72,373,105,359,123,386
```

**Reply by blakeblackshear** [reply]
```yaml
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.14:554/11
          roles: 
            - detect
            - record
            - rtmp
    # rtmp: 
    #   enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          mask:
            - 259,309,340,246,384,237,715,75,582,76,568,0,660,62,797,0,0,0,0,411,62,418,72,373,105,359,123,386
    zones:
      back_alley:
        coordinates: 547,432,230,637,185,557,110,424,261,324,428,230,735,78,784,213
        objects:
          - car
          - person
        # filters:
        #   person:
        #     # min_area: 5000
        #     # max_area: 100000
        #     # threshold: 0.7
        #     mask:
        #       - 259,309,340,246,384,237,715,75,582,76,568,0,660,62,797,0,0,0,0,411,62,418,72,373,105,359,123,386
```

**Reply by ExceedingLife** [reply]
Thank you! I will try it out and after a few days let you know how it goes.

**Reply by ExceedingLife** [reply]
Thank you very much for your input on this, this significantly reduced the false positives, now it happens so much less!
Here is another question, awhile back I thought I read on the update there was an update about the last few frames if something doesnt move it shouldn't trigger the detection.
I'm wondering if maybe I dont have this set up correctly? 
```
record:
  enabled: true
  retain:
    days: 3
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  events:
    retain:
      default: 3
      mode: active_objects
      objects:
        person: 10
```
I see in my comment maybe I need to set 'days' ?

Well anyways here is what happens?
I see parked cars on the street and every few mins to hours  these get triggered and i get tons of recordings of this object and its nothing different in the frames from before...
Tons of space is used GBs that shouldnt need to be used.
![image](https://user-images.githubusercontent.com/8807604/164743039-39f34729-6293-49be-b280-d78984276095.png)
Opening it up, it looks like this.
![image](https://user-images.githubusercontent.com/8807604/164743341-c12e6741-6e6b-46b0-b74b-898e95f71577.png)

Any input would be hugely appreciated. Figuring out how to compare with the past frames could help me alot with false active object/motion detection.

Thank you!

**Reply by NickM-27** [reply]
It's not exactly clear what you're referring to. You already have `active_objects` as your retention mode so as long as your `stationary` settings allow the car to be marked as stationary then those segments where it is still (inactive) will be discarded. Unfortuntely, with this looking like it is across the street, any car that drives by will likely cause this to be considered active. 

This is a case where if you don't care about getting events for those vehicles across the street, a zone along with `required_zones` should be used so events / recordings aren't kept for those vehicles.

**Reply by ExceedingLife** [reply]
This is my stationary setting:

```
detect:
  width: 1920
  height: 1080
  # width: 1280
  # height: 720
  fps: 5
    # Optional: Configuration for stationary object tracking
  stationary:
    # Frequency for running detection on stationary objects 
    # When set to 0, object detection will never be run on stationary objects. If set to 10, it will be run on every 10th frame.
    interval: 10   #0
    
objects:
  track:
    - person
    - car
    - dog
  #mask: stops objects from being tracked here
  filters:
    person:
      min_score: 0.4 # min score for object to initiate tracking (default: 0.5
      threshold: 0.55
    car:
      threshold: 0.6
```

I will have to look into a zone or mask if this is what should fix this issue I;m having.
