### DISCUSSION TITLE
Need help fine tune settings to catch a bird

### DISCUSSION THREAD

**Discussion by bradphillips921** [blakeblackshear/frigate#3126] [General]
Some bird flys onto my patio everyday and spends an hour attacking my window and pooping on my furniture. I installed frigate on Home Assistant to solve this problem. I want to play audio through speakers when it detects the bird. The problem is it's not detecting the bird.

Here is my config. Is there something I can do differently to make Frigate see the bird?

```
cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.1.89:554/cam/realmonitor?channel=1&subtype=0
          roles: 
            - detect
    objects:
      track:
        - person
        - bird
      filters:
        bird:
          # Optional: minimum score for the object to initiate tracking
          min_score: 0.2
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.3
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
```
Here is the bird. He spends most of his time by the window, but I would think Frigate could see the bird fly in and out or perched on the railing.
![Patio 2022-04-19 09 40 46 144 AM](https://user-images.githubusercontent.com/39811495/164144749-ddf8a06e-b49a-4e02-b2eb-bfd0a8e8606c.jpg)

**Comment by NickM-27** [comment]
Have you tried watching the debug view to see what frigate sees, does it see motion (red box)? 

It is quite small... also, what resolution is your camera? i don't see `detect` defined in your config so you should keep in mind that if you don't specify the detect resolution then the image will be resized to 1080x720, so if your camera is higher resolution definitely want to define that.

**Comment by bradphillips921** [comment]
Thanks for the quick reply, Nick!

I did not have the resolution defined. I added that, they are 8MP cameras.

```
detect:
  width: 3840
  height: 2160

cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.1.89:554/cam/realmonitor?channel=1&subtype=0
          roles: 
            - detect
    objects:
      track:
        - person
        - bird
      filters:
        bird:
          # Optional: minimum score for the object to initiate tracking
          min_score: 0.2
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
          threshold: 0.3
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
```
I don't see how I can view video in debug mode. I click the debug section and it just shows me stats

![Untitled](https://user-images.githubusercontent.com/39811495/164147619-e60a7440-1e07-4300-a20a-464f078f4770.jpg)

Also, on the debug screen it lists the code. This code on the debug screen doesn't match my config. It shows the height and width is still at 720x1280 and it has different values for the min_score and threshold. I restart Frigate after changing my config file.

Code shown on debug page

```
    "patio": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
.....
      },
      "name": "patio",
      "objects": {
        "filters": {
          "bird": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
......
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },

```

**Reply by NickM-27** [reply]
To view debug mode go cameras -> open camera -> debug in the top right

Just making sure that you restarted after changing the config? Setting that globally should make it apply to the camera

**Comment by bradphillips921** [comment]
I found out how to get debug to work when viewing live, but not when looking back at recordings.

However, I caught the bird with Frigate! The only problem is the bird was there for about 10 minutes before Frigate saw it. I'm going to try increasing the sensitivity by lowering the threshold for a bird.  I assume I do that by setting the threshold number lower, correct? So the code below would consider it a positive hit on a bird if Frigate is 20% sure?

```
      filters:
        bird:
          min_score: 0.1
          threshold: 0.2
```
