### DISCUSSION TITLE
24*7 recording in Frigate

### DISCUSSION THREAD

**Discussion by mishrankit9** [blakeblackshear/frigate#3163] [Ask A Question]
Hello All,

Given below is my configuration for a camera in frigate.
I have configured mode: all, so that I can do 24*7 recording. Though I noticed that the recording is only happening for event. When there are no events like in night time there is no video at all. I just wanted to be sure if the configuration is right for 24*7 recording.
```
cameras:
  youentry:
    ffmpeg:
      inputs:
        - path: rtsp://abc:12345@192.168.1.100/Streaming/Channels/101
          roles:
            - detect
            - record
    record:
      enabled: True
      events:
        retain:
          default: 7
          mode: all
    objects:
      track:
        - person
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 10
```

**Comment by NickM-27** [comment]
There's a few things that are incorrect here.
1. You have set the mode `all` for events, you need to set that for `record` to affect 24/7 recording. Check out [this docs topic](https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean) to get a better idea of how each behaves.
2. You need to define `days` for recording as well so it knows how many days of 24/7 recording to keep.

You can reference [the config file in docs](https://docs.frigate.video/configuration/index) for how the formatting works

**Comment by mishrankit9** [comment]
Thanks @NickM-27 for the Quick response.

I have made the corrections now, in case you can validate it once.

```
cameras:
  youentry:
    ffmpeg:
      inputs:
        - path: rtsp://abc:12345@192.168.1.100/Streaming/Channels/101
          roles:
            - detect
            - record
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      objects:
        track:
          - person
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 10
```
