### DISCUSSION TITLE
JPEG Vivotek camera - can't get stream, with ffmpeg it's OK

### DISCUSSION THREAD

**Discussion by tootai** [blakeblackshear/frigate#3192] [General]
Hi all,
I have an old PZ 6122 caméra and get get it to work with frigate. I successfully get the stream form ffmpeg with
ffmpeg -y -loop 1 -f image2pipe -i http://user:passwd@camera IP/cgi-bin/video.jpg -map 0 /tmp/video.avi
but I'm unable to report those datas in frigate.yml With this file for instance I get

frigate  | [2022-05-04 16:43:42] ffmpeg.camp13.detect           ERROR   : [rtmp @ 0x561b42d3d400] Cannot open connection tcp://127.0.0.1:1935
frigate  | [2022-05-04 16:43:42] ffmpeg.camp13.detect           ERROR   : rtmp://127.0.0.1/live/camp13: Immediate exit requested

Definition:
```yaml
cameras:
  camp13: # <------ Name the camera
    ffmpeg:
      input_args:
        - -y
        - -loop
        - 1
        - -f
        - image2pipe
      inputs:
        - path: http://user:passwd@camera IP/cgi-bin/video.jpg # <----- Update for your camera
          roles:
            - detect
            - record
      output_args:
        record: -map 0 -c:v libx264 -an /tmp/video.avi
    detect:
      width: 352 # <---- update for your camera's resolution
      height: 288 # <---- update for your camera's resolution 
```
If I add 
   rtmp:
     enabled: False
I get ERROR   : Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

What's wrong with my definition ? No need to say that I tried the jpeg configuration from docs, no more luck.

Thanks for any hint, Daniel.
