### DISCUSSION TITLE
esp32cam in frigate?

### DISCUSSION THREAD

**Discussion by Lallassu** [blakeblackshear/frigate#3196] [Ask A Question] [answered]
Has someone got an esp32 with camera module working with rtsp/mjpeg in frigate?

I've tried _a lot_ of settings for mjpeg but it always ends up with a lot of warnings and green image in the dashboard.

Errors such as these:
```
frigate          | [2022-05-07 13:09:30] watchdog.kitchen               ERROR   : Ffmpeg process crashed unexpectedly for kitchen.
frigate          | [2022-05-07 13:09:30] watchdog.kitchen               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate          | [2022-05-07 13:09:30] ffmpeg.kitchen.detect          ERROR   : [AVHWFramesContext @ 0x5619cd7163c0] Failed to read image from surface 0x6: 1 (operation failed).
frigate          | [2022-05-07 13:09:30] ffmpeg.kitchen.detect          ERROR   : [mjpeg @ 0x5619cd719080] Failed to transfer data to output frame: -5.
frigate          | [2022-05-07 13:09:30] ffmpeg.kitchen.detect          ERROR   : Error while processing the decoded data for stream #0:0
```
This is the last config I tried:
```
  kitchen:
    ffmpeg:
      inputs:
        - path: http://192.168.1.195/
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
      output_args:
        detect: -f rawvideo -pix_fmt yuvj422p
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 800
      height: 600
      fps: 5
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
```
Same issue when trying to use rtsp. Here is the output from ffprobe on the rtsp endpoint:
```
Input #0, rtsp, from 'rtsp://192.168.1.195:8554/mjpeg/1':
  Metadata:
    title           : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 800x600 [SAR 1:1 DAR 4:3], 9.90 fps, 9.90 tbr, 90k tbn, 90k tbc
```

Any tips/ideas?

**Comment by NickM-27** [comment, marked as answer]
Here's a couple issues where users had esp32 working:
https://github.com/blakeblackshear/frigate/issues/2903
https://github.com/blakeblackshear/frigate/issues/2030

**Reply by Lallassu** [reply]
Thanks, made it work with the config from #2903 ! :)

**Comment by neilbacon** [comment]
The config involving “rtmp” is no longer valid and it’s desirable to use go2rtc to generate a h264 stream from the esp32cam mjpeg. Here is my working config for that:
```
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

go2rtc:
  streams:
    cam1:   'ffmpeg:http://192.168.1.141:8080#video=h264#width=1280#height=1024#hardware'

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1
          roles:
            - record
            - detect
```
Just adjust the width & height to match the size of the image from the esp32cam.
This is running on a Intel N150 which has an iGPU that supports ffmpeg hardware acceleration.
