### DISCUSSION TITLE
Doesn't record events at night

### DISCUSSION THREAD

**Discussion by rnaff** [blakeblackshear/frigate#3201] [Ask A Question]
I've been using frigate for over a year and I love it.

I just realized that my setup only detects objects during the day. All of my events are during the day.

I can clearly see myself on camera at night but it's not detecting me.

I don't see anything in the yammal having to do with time etc

**Comment by blakeblackshear** [comment]
Have you tried using the improve_contrast setting in the motion config? You could also try adjusting your night profile settings on the camera to improve the contrast.

**Comment by rnaff** [comment]
I have very bright lights turned on at night so maybe this is what's
causing the issue.

I'll play with the contrast setting.

Is there a minimum contrast for it to find an object?

**Reply by NickM-27** [reply]
It's not about finding the object. If there is not enough contrast (different between parts of the image) then there will be no motion detected. The `improve_contrast` option will take steps to improve this after the fact which will increase that. Once motion is detected, the object should be detected.

**Comment by rnaff** [comment]
Ok thanks for explaining.

Does the contrast settings increase cpu usage?

Should I do it at the camera level?

I'm assuming it'll also make the picture a bit darker during the day?

Maybe I'll just tell my wife to not turn our lights on lol

**Reply by NickM-27** [reply]
Have you tried the `improve_contrast` setting in frigate? This doesn't affect the viewable image at all and won't increase CPU usage

**Comment by rnaff** [comment]
No I haven't.

Let me Google and see where I input it into yammal

**Reply by NickM-27** [reply]
https://docs.frigate.video/configuration/index

**Comment by rnaff** [comment]
It used to record at night without any issue so I'm not sure what changed?

I can edit my contrast for night recording on my camera.

What direction should I move the scale towards?

**Reply by NickM-27** [reply]
Latest version of frigate starts with `improve_contrast` set as false because it caused some over-sensitivity for some people. All you need to do is set `improve_contrast` to true in the config for that camera

**Comment by rnaff** [comment]
Is that in frigate.yml or elsewhere?

**Reply by NickM-27** [reply]
yes, please use the https://docs.frigate.video/configuration/index docs for reference

**Comment by rnaff** [comment]
I don't have the line in my frigate.yml

🤣

**Reply by NickM-27** [reply]
The frigate.yml file has defaults so if there is nothing there then it is just using the default. Under where the camera is defined you'll need to add

```yaml
cameras:
  your_camera_that_needs_this:
    ffmpeg:
      ...
    motion:
      improve_contrast: true
```

**Reply by NickM-27** [reply]
... is meant to convey there is stuff there that I don't know about. The only important part is adding the motion and improve contrast

**Comment by rnaff** [comment]
I added it under motion for both cameras.

Hopefully it doesn't break it haha

**Reply by NickM-27** [reply]
Make sure to restart the addon so it takes affect

**Comment by rnaff** [comment]
ugh, i added this line under motion for both cameras, restarted, and now i
just get a buffering sign when trying to view frigate in home assistant.

improve_contrast: True

**Reply by NickM-27** [reply]
please paste your entire config (use ``` so it formats correctly). odds are your spacing is incorrect

\```
paste
\```

**Comment by rnaff** [comment]
```
mqtt:
  host: 192.168.1.39
  user: rnaff
  password: sKrillaz-21

cameras:
  Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    width: 3840
    height: 2160
    fps: 12
    motion:
      improve_contrast: True
      mask:
        - 2761,794,2820,0,1119,0,0,0,0,393,0,1119,305,819
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30
  Garage2 :
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    width: 3840
    height: 2160
    fps: 12
    motion:
      improve_contrast: True
      mask:
        -
605,932,1421,865,1469,647,1924,644,3789,715,3840,0,0,0,0,882,0,1492
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Reply by NickM-27** [reply]
You are missing `detect` header

```
    width: 3840
    height: 2160
    fps: 12
```
all should be under detect and it isn't

**Comment by rnaff** [comment]
I'm messing it up somehow.

I'm just a 40 year old newb, no coding experience really, sorry for the
hassle but I do love Frigate.
```
mqtt:
  host: 192.168.1.39
  user: rnaff
  password: sKrillaz-21

cameras:
  Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
  detect:
    width: 3840
    height: 2160
    fps: 12
    motion:
      improve_contrast: True
      mask:
        - 2761,794,2820,0,1119,0,0,0,0,393,0,1119,305,819
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30
  Garage2 :
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
  detect:
    width: 3840
    height: 2160
    fps: 12
    motion:
      improve_contrast: True
      mask:
        -
605,932,1421,865,1469,647,1924,644,3789,715,3840,0,0,0,0,882,0,1492
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Reply by NickM-27** [reply]
yaml (`.yml`) is a space dependent language so spaces are required to be consistent. every 2 spaces in indicates a new "level".

You added `detect` but it is not indented enough. You should indent it so it is two more spaces indented from the name of the camera:

```yaml
cameras:
  your_camera:
    detect:
      width: num
      height: num
      fps: num
```

**Comment by rnaff** [comment]
Moved them over, restarted, and still getting a buffering sign.

thx for your help on this btw
```
mqtt:
  host: 192.168.1.39
  user: rnaff
  password: sKrillaz-21

cameras:
  Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
    width: 3840
    height: 2160
    fps: 12
    motion:
      improve_contrast: True
      mask:
        - 2761,794,2820,0,1119,0,0,0,0,393,0,1119,305,819
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30
  Garage2 :
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
    width: 3840
    height: 2160
    fps: 12
    motion:
      improve_contrast: True
      mask:
        -
605,932,1421,865,1469,647,1924,644,3789,715,3840,0,0,0,0,882,0,1492
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Reply by NickM-27** [reply]
Sure 👍 

Look at how mine is vs how yours is. You have `detect` and `width`, `height`, etc. at the same number of spaces where in my example those are all indented two more spaces than detect (since they are an attribute of detect). Hopefully this starts to make more sense

**Comment by rnaff** [comment]
now i'm getting a 502 bad gateway on frigate page within home assistant LOL

```
mqtt:
  host: 192.168.1.39
  user: rnaff
  password: sKrillaz-21

cameras:
  Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
      width: 3840
      height: 2160
      fps: 12
      motion:
      improve_contrast: True
      mask:
          - 2761,794,2820,0,1119,0,0,0,0,393,0,1119,305,819
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30
  Garage2 :
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
      width: 3840
      height: 2160
      fps: 12
      motion:
      improve_contrast: True
      mask:
        -
605,932,1421,865,1469,647,1924,644,3789,715,3840,0,0,0,0,882,0,1492
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Reply by NickM-27** [reply]
In this case you have `motion` indented too much. motion should be at the same level as detect

**Comment by rnaff** [comment]
well now we are just back to the buffering sign

```
mqtt:
  host: 192.168.1.39
  user: rnaff
  password: sKrillaz-21

cameras:
  Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
      width: 3840
      height: 2160
      fps: 12
    motion:
      improve_contrast: True
      mask:
          - 2761,794,2820,0,1119,0,0,0,0,393,0,1119,305,819
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30
  Garage2 :
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
      width: 3840
      height: 2160
      fps: 12
    motion:
      improve_contrast: True
      mask:
        -
605,932,1421,865,1469,647,1924,644,3789,715,3840,0,0,0,0,882,0,1492
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Reply by NickM-27** [reply]
It seems like all of your indentation is off. By the way "buffering", "error" don't really matter as it just means frigate isn't running (since it stops with an invalid config).

You can also view the addon logs to see the error that it is complaining about.

**Reply by NickM-27** [reply]
All the camera names seem to be only 1 space indented and that throws everything below off as well

**Comment by rnaff** [comment]
LOL

dude i'm just continually breaking it.

```
mqtt:
  host: 192.168.1.39
  user: rnaff
  password: sKrillaz-21

cameras:
   Garage1:
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
      width: 3840
      height: 2160
      fps: 12
    motion:
      improve_contrast: True
      mask:
          - 2761,794,2820,0,1119,0,0,0,0,393,0,1119,305,819
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30
   Garage2 :
    ffmpeg:
      inputs:
        - path: rtsp://
***@***.***:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
          - detect
          - clips
    detect:
      width: 3840
      height: 2160
      fps: 12
    motion:
      improve_contrast: True
      mask:
        -
605,932,1421,865,1469,647,1924,644,3789,715,3840,0,0,0,0,882,0,1492
    objects:
      filters:
        dog:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
        person:
          mask:
            -
3815,2133,3840,1303,3637,969,3464,921,3040,845,2710,664,1500,653,1305,904,865,1014,616,913,65,1529,0,2136
      track:
        - person
        - dog
    clips:
      enabled: True
      retain:
        default: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

```
