### DISCUSSION TITLE
detection gets "stuck", event doesn't end.

### DISCUSSION THREAD

**Discussion by ve6rah** [blakeblackshear/frigate#3204] [Ask A Question]
I have a 3 camera setup in frigate. 2 of the 3 cameras work perfectly, but the third is doing something rather odd. I would be in your debt if you could point me in the right direction to troubleshoot this!

When someone comes to the front door, they trigger detection and an event properly, but when they leave again the event doesn't end. when looking at the frigate events screen I see:
![Screenshot 2022-05-10 12 38 43](https://user-images.githubusercontent.com/16531454/167699231-2dd269ce-3d04-426e-b429-6541141dd011.png)
In the debug window I see a live view of the camera, with a bounding box covering the area where the person was last seen (if it matters, this bounding box is completely covered by my motion mask), and with a very high person score, but there's no person there, nor is there anything else that could even remotely be confused for one (in fact it shows a completely blank grey asphalt street most of the time)

In this case there are 2 bounding boxes, because it was 2 kids (hence the small boxes)
![download (1)](https://user-images.githubusercontent.com/16531454/167698658-a630d719-577e-41d1-9548-1cafc8dd0219.png)

Note that this event is now almost 5 hours long and I know from past experience that it will only end under one of 2 conditions:
1) another person triggers the recognition and starts a new event
2) night time comes and the camera switches to night mode (whole screen changes, probably shows as a motion event making the whole thing wake up again?) 

A few important points to note:
- The bounding box that remains is always where the person last was before leaving the scene
- The score above the box remains constant and unchanging at a very high value, the same value as when the person was last seen
- I don't get any other false positives not associated with this sort of event, so I'm pretty sure it's not a case of the system mis-categorizing something else as a person.

This does not  happen 100% of the time, but it is well over 50%, and enough to be a serious issue for me.

My frigate config is below, before anyone mentions the lack of a Coral, there's one rule, you can only criticize me for not having one if you're willing to ship me one. I've been looking for many months now, I'm on all the waiting lists, and I've even tried buying one of the ridiculously overpriced ones scalpers are selling only to find out that even that one didn't exist. They are 100% completely and utterly unavailable. Don't tell me I should have one.

Camera in question is "front_door", I've never had any issues with the back door or garage cameras.

```
mqtt:
  host: <REDACTED>
  user: <REDACTED>
  password: <REDACTED>

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3

birdseye:
  enabled: False


rtmp:
  enabled: True

cameras:
  garage_entry_door:
    ffmpeg:
      inputs:
        - path: rtsp://<REDACTED>:<REDACTED>@10.42.3.70:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
        - path: rtsp://<REDACTED>:<REDACTED>@10.42.3.70:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 480
      fps: 5
    motion:
      mask:
        - 218,85,195,165,120,94,0,94,0,0,704,0,704,350
    record:
      enabled: True
      retain_days: 2
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 5
          objects:
            person: 20
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 5
        objects:
           person: 20
    mqtt:
      enabled: True
      bounding_box: False
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://<REDACTED>:<REDACTED>@10.42.3.101:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
        - path: rtsp://<REDACTED>:<REDACTED>@10.42.3.101:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 704
      height: 480
      fps: 5
    motion:
      mask:
         - 0,0,0,343,45,337,91,349,142,359,218,367,308,362,408,355,519,345,600,325,704,295,704,0
    record:
      enabled: True
      retain_days: 2
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
        retain:
          default: 5
          objects:
            person: 20
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 5
        objects:
           person: 20
    mqtt:
      enabled: True
      bounding_box: False
  back_door:
    ffmpeg:
      inputs:
        - path: rtsp://<REDACTED>:<REDACTED>@10.42.3.102:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
        - path: rtsp://<REDACTED>:<REDACTED>@10.42.3.102:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 704
      height: 480
      fps: 5
    motion:
      mask:
         - 0,0,0,267,24,237,117,236,119,271,369,281,427,321,497,367,534,370,581,381,704,436,704,0
    record:
      enabled: True
      retain_days: 2
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
         retain:
          default: 5
          objects:
            person: 20
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 10
        objects:
           person: 25
    mqtt:
      enabled: True
      bounding_box: False
```
