### DISCUSSION TITLE
Trouble setting up bare metal docker-compose "exited with code 1"

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#3269] [Ask A Question] [answered]
I am having trouble getting frigate up and running. When I do `docker-compose up` I get the following block of logs repeating several times:

```
frigate      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate      | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate      | [fix-attrs.d] applying ownership & permissions fixes...
frigate      | [fix-attrs.d] done.
frigate      | [cont-init.d] executing container initialization scripts...
frigate      | [cont-init.d] done.
frigate      | [services.d] starting services
frigate      | [services.d] done.
frigate      | [2022-05-28 19:23:35] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
frigate      | Starting migrations
frigate      | [2022-05-28 19:23:35] peewee_migrate                 INFO    : Starting migrations
frigate      | There is nothing to migrate
frigate      | [2022-05-28 19:23:35] peewee_migrate                 INFO    : There is nothing to migrate
frigate      | [Errno 99] Cannot assign requested address
frigate      | [cmd] python3 exited 1
frigate      | [cont-finish.d] executing container finish scripts...
frigate      | [cont-finish.d] done.
frigate      | [s6-finish] waiting for services.
frigate      | [s6-finish] sending all processes the TERM signal.
frigate      | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 1
```

When I visit the web ui the page partially loads but the console says that it can;t find `/api/config`.

My `config.yml` is as follows:

```
mqtt:
  host: localhost
  user: my_user_name
  password: my_password
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://@front-door.cams.sub.domain.com:554/11
          roles:
            - record
        - path: rtsp://baz:bizwiz@front-door.cams.sub.domain.com:554/12
          roles:
            - detect
    rtmp:
      enabled: false
    detect:
      enabled: true
      fps: 5
      width: 640
      height: 352
    record:
      enabled: true
    snapshots:
      enabled: true
```

My docker-compose is as follows:

```
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - /home/nas/mosquitto/conf:/mosquitto/conf
      - /home/nas/mosquitto/data:/mosquitto/data
      - /home/nas/mosquitto/log:/mosquitto/log

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-beta2
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/beast/frigate/config.yml:/config/config.yml:ro
      - /mnt/beast/frigate/data:/media/frigate
      - /home/nas/frigate/db:/db
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

I have no idea if mosquitto is setup and connected correctly so the issue might be there. Any help would be greatly appreciated.

Thanks!

**Comment by NickM-27** [comment, marked as answer]
> I have no idea if mosquitto is setup and connected correctly so the issue might be there. Any help would be greatly appreciated.

I think this is due to an error connecting to mqtt. I would try adding

```yaml
ports:
  - "1883:1883"
```

to the mqtt part to ensure that the port is exposed as expected. Also might want to try using something like [mqtt explorer](http://mqtt-explorer.com/) which can help you verify that the mqtt server is up and running as expected. (it is also useful once you get frigate going in case you want to troubleshoot and watch anything that frigate sees.)

> When I visit the web ui the page partially loads but the console says that it can;t find /api/config.

The web UI requires the backend to be running (which is what got the error) so that makes sense.

**Reply by thinkloop** [reply]
Thanks a lot. I added `ports` to my docker-compose:

```
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto
    network_mode: host
    ports:
      - "1883:1883"
    volumes:
      - /home/nas/mosquitto/conf/:/mosquitto/conf/
      - /home/nas/mosquitto/data/:/mosquitto/data/
      - /home/nas/mosquitto/log/:/mosquitto/log/
    restart: unless-stopped
```

Do I need to add a `network: default` or similar?

I also installed MQTT Explorer on my windows machine to try and connect to the Ubuntu MQTT server on my LAN but I am unable to connect. Ubuntu firewalll is turned off. Is this what my `mosquitto.conf` is supposed to look like:

```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883
## Authentication ##
# allow_anonymous false
password_file /mosquitto/conf/mosquitto.passwd
````

Thanks again!
