### DISCUSSION TITLE
frigate not able to record

### DISCUSSION THREAD

**Discussion by bend94** [blakeblackshear/frigate#3274] [General]
Hi
I need your help .
My frigate is running, it can detect personn (bound box is shown) i now try to record clips and snapshots but it is not working
Here is my frigate.yml
```
mqtt:
  host: 192.168.1.22
  port : 1883
  topic_prefix : frigate
  
  
detectors:
  cpu1:
    type: cpu
    
    
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://test:PWD@192.168.1.200:554/Streaming/Channels/102/
          roles:
            - detect
            - clips
            - record
    detect:
      width: 320
      height: 240
      fps: 4
      object:
        track:
          - person
        filters:
          person:
            threshold: 0.5
      clips:
        enabled: True
        retain:
          default: 2
      record:
        enabled: True
        retain:
          default: 2
      snapshots:
        enabled: true
        bounding_box: true
        retain:
          default: 2

```

please advise
thx

**Comment by bend94** [comment]
ok i is working now with that

```
mqtt:
  host: 192.168.1.22
  port : 1883
  topic_prefix : frigate
  
  
detectors:
  cpu1:
    type: cpu
    
    
cameras:
  back1:
    ffmpeg:
      inputs:
        - path: rtsp://test:PWD@192.168.1.200:554/Streaming/Channels/102/
          roles:
            - detect
            - clips
            - record
    detect:
      width: 320
      height: 240
      fps: 4
      
    record:
      enabled: True
      retain:
         days: 5
snapshots:
  enabled: True
```
