### DISCUSSION TITLE
frigate green stream with Reolink cameras over RTMP or HTTP

### DISCUSSION THREAD

**Discussion by lukasig** [blakeblackshear/frigate#3277] [Ask A Question] [answered]
I have been using [motioneye](https://github.com/motioneye-project/motioneye) for a few years now and I love it. But frigate seems to have more potential so I want to switch to it.

I am trying to set up my reolink cameras, but when i use RTMP or HTTP streams, I only get green screens.

I can get them to display somewhat correctly when i use RTSP, but even then I get a lot of smearing and green.

The cameras work perfectly well with RTMP streams running in motioneye which is running in parallel on the same machine until i figure this out.

I use frigate inside a docker container (not through HA), on a server running ubuntu 22.04 and my cpu is a i3-10110U.

my cameras are reolink RLC-410-5MP and RLC-511W running the latest firmware (v3.0.0.136_20121100 & v3.0.0.142_20121804 respectively).

I don't want to overpopulate this posting with the full frigate config.yml file, but here are (I believe) the relevant parts:
```
cameras:
  CAM1:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
    ffmpeg:
      inputs:
        - path: rtmp://192.168.X.X/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=xxxx
          roles:
            - detect
    detect:
      width: 640
      height: 480
```

I have tried the following streams using all variations of main, sub or ext, which work ok in VLC:

http://192.168.x.x/flv?&app=bcs&stream=channel0_sub.bcs&user=admin&password=xxxx

http://192.168.x.x/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=xxxx

the shomewhat working RTSP version is:

rtsp://admin:[xxxx@192.168.X.X](mailto:xxxx@192.168.X.X):554//h264Preview_01_sub

any help is appreciated

Thanks

**Comment by NickM-27** [comment]
Have you tried the reolink recommended args from the docs? https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others

**Reply by lukasig** [reply]
yes
no difference at all...

**Reply by NickM-27** [reply]
What version of frigate are you running?

**Comment by lukasig** [comment, marked as answer]
Thanks for all your feedback.
The problem seems to be related to the SUB stream. As soon as I switched to the EXT stream, and removed the extra "ffmpeg:" above "inputs:", it worked ok.
For some reason my RTSP streams did not work without that extra "ffmpeg:", but the HTTP or RTMP streams don't work with it.
My current working (relevant) config:

```
cameras:
  CAM1:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
      inputs:
        - path: http://192.168.X.X/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
          roles:
            - detect
    detect:
      width: 896
      height: 672
```

Pay attention to the hardware acceleration arguments, as it might not be relevant to your hardware:
https://docs.frigate.video/configuration/hardware_acceleration/
