### DISCUSSION TITLE
Clarification About Stationary Objects

### DISCUSSION THREAD

**Discussion by bmight** [blakeblackshear/frigate#3279] [Ask A Question] [answered]
Over the last several days I have been all over the docs trying to understand how stationary objects work. I am currently testing Frigate with a single camera in docker first. My questions are:

1. When an object becomes stationary inside a zone, should that end the event within frigate by default?

2. In debug view, should a stationary object still show a bounding box once it becomes in active? If it always contains a bounding box does that mean it is still running object detection for that object?

3. Will motion, lights or other objects, cause the stationary object to be come active again even if the stationary object (car) hasn't moved? The docs seem to conflict on this answer to me.
    - ["... Shadows or other lighting changes will be detected as motion. This will often cause a new event for a parked car. ..."](https://docs.frigate.video/guides/stationary_objects)
    - [".... Lighting changes for a parked car won't make an object active. ...."](https://docs.frigate.video/configuration/stationary_objects)
  
4. For required_zones in record -> events in the [stationary objects guide](https://docs.frigate.video/guides/stationary_objects), if zone2 is the only one in required zones does that mean an event will not be created for any other object?

     4b. Would adding zone -> zone1 -> objects -> list all objects but car and leaving off required_zones have a similar effect?

5. Is there any way to tell frigate to record the debug view? Sometimes the issues I have with stationary objects and I am not around to look at the debug view. Would be cool to see what object it is detecting and in what zone (although I guess the zone is already noted in the event details)

6. Not a stationary object question but what is the number after the percentage on a detected object?

7. Does the event retain mode change how long an event is "In Progress" or is that only connected to how long videos are saved on disk for?

Hopefully I didn't just miss all of this in the documentation. I can create some more specific examples with the issues I am having if needed.

**Comment by NickM-27** [comment, marked as answer]
1. With the **default config** stationary objects will continue to be tracked and the event is `in progress` until the object is not seen anymore. Being in a zone does not affect this.
2. In the debug view there is currently no direct indication that an object is `stationary` or not. The best way to tell is if the bounding box is resizing / changing at all. If it isn't then it is likely considered stationary.
3. Motion itself will not directly cause an object to be considered active. Motion will trigger a single object detection, if the bounding box for the object has moved considerably from when it was stationary, it will then be considered active again.
4. If you don't define objects for zone2 then it will allow any zone that is defined for that camera. So if you have (not saying this is a valid config just for demonstration)

```yaml
camera:
  some_camera:
    objects:
      track:
        - person
        - dog
    record:
      events:
        required_zones:
          - zone2
```

then both `person` and `dog` will have an event created if they enter that zone. However, you can define specific objects for a zone at which point only those objects can trigger that zone.

4b. Without required_zones the effect would be entirely different as events are created for all objects even if they never enter a zone. I think there should be some further discussion about this as there seems to be some confusion regarding zones & objects interaction.

5. If you download the mp4 for the event you can [use these docs](https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing) to provide the mp4 as a camera and watch what happens (need to make sure all the settings including resolution are the same to get reproducible result)
6. The number after the percentage is the area of the bounding box
7. The `record -> event -> retain -> mode` affects which segments of the events recording are kept, it has no effect on the actual behavior of tracking.

**Comment by bmight** [comment]
@NickM-27 Thanks for such a quick reply. I have a few follow up questions for Q4. Using the [stationary objects guide](https://docs.frigate.video/guides/stationary_objects) example. In my head I have two configs:

### Option 1
The config shown in the guide. This would only allow events to be created when any tracked object enters `zone_2`. `zone_1` will never create an event for any tracked objects entering into the zone. Ex: A person enters from the left side of `zone_1` they will not create a new event.

```
objects:
  track:
    - person
    - car

camera:
  record:
    events:
      required_zones:
        - zone_2
  zones:
    zone_1:
      coordinates: ... (parking area)
    zone_2:
      coordinates: ... (entrance to driveway)
```

### Option 2
This version will allow a person entering `zone_1` to create an event but a parked (stationary) car will not be detected in `zone_1`. Not sure if there are any consequences to this. Also not sure if required_zones is still required to prevent events from the street?

```
camera:
  record:
    events:
      required_zones:
        - zone_1
        - zone_2
  zones:
    zone_1:
      coordinates: ... (parking area)
      objects:
        - person
    zone_2:
      coordinates: ... (entrance to driveway)
```
