### DISCUSSION TITLE
Clarification about motion masks

### DISCUSSION THREAD

**Discussion by selmaohneh** [blakeblackshear/frigate#3285] [Ask A Question] [answered]
Hi!
I just want to install my second IP camera and integrate it into frigate.

I noticed that the motion.mask config entry is not camera specific. So the mask of my first camera is automatically applied to my now new second camera. But that's not what I want. The new camera will have a totally different motion mask.

What's the why to define different masks for different cameras? Couldn't find an example in the docs, neither in the masks nor the camera section.

https://docs.frigate.video/configuration/masks
https://docs.frigate.video/configuration/cameras

Thanks in advance for any help!

**Comment by NickM-27** [comment, marked as answer]
The `motion -> mask` can be "overridden at the  camera level" meaning there is no specific example because it is just meant to be applied to the camera. See the below example:

```yaml
cameras:
  camera_1:
    ffmpeg:
      ...
    motion:
      mask: ...,...,...,...

  camera_2:
    ffmpeg:
      ...
    motion:
      mask: ...,...,...,...
```

**Reply by selmaohneh** [reply]
Short and on point. Thanks!

**Reply by selmaohneh** [reply]
Hi again! Finally managed to mount the second camera to the wall. Now I want to implement your advice and override the mask at camera level. This is part of my conifg:

```
detectors:
  cpu1:
    type: cpu
mqtt:
  host: 192.168.xxx.yy
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://bla:blub@192.168.zzz.ppp/live/ch0
          roles:
            - detect
    motion:
      mask:
        - 0,187,0,373,477,0,0,0
        - 1021,0,1015,106,512,99,533,0
        - 1280,720,1280,0,972,0,833,223
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://bla:blub@192.168.uuu.aaa/live/ch0
          roles:
            - detect
    motion:
      mask:    
        - 0,720,39,153,178,127,169,181,294,169,298,0,0,0
snapshots:
  enabled: True
```
Unfortunately it does not yet work. 
When I look at the debug live feed inside frigate and activate the frontyard's motion mask, I can clearly see part of the backyard's mask.

![image](https://user-images.githubusercontent.com/29881939/177592163-791ff99a-78ba-432e-a109-92e2dea764cc.png)

Is this just a "bug/feature" in frigate which always shows ALL masks? Or does frigate really apply that wrong mask?

Thanks in advance!
