### DISCUSSION TITLE
Help with config.yml

### DISCUSSION THREAD

**Discussion by tknx** [blakeblackshear/frigate#3300] [Ask A Question] [answered]
Hi all - I am setting up Frigate on my Unraid server and got it almost working, just missing something.

Goals are to have it record when people or cars go by and retain for 10 days. I've been building up my config.yml files, but it is unclear to me:
(1) the events section is throwing an error
(2) if i have objects for a person, will it not bother if a car drives by?

```
mqtt:
  host: 10.0.20.41
  user: frigate
  password: redacted

detectors:
  coral:
    type: edgetpu
    device: pci

objects:
  track:
    - person

motion:
  threshold: 25

record:
  enabled: true
  retain:
    days: 0  

events:
  retain:
      default: 10

cameras:
  deck:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:redacted@10.0.20.65:554/profile2/media.smp
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:redacted@10.0.20.66:554/profile2/media.smp
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:redacted@10.0.20.64:554/profile2/media.smp
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:redacted@10.0.20.63:554/profile2/media.smp
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
```
