### DISCUSSION TITLE
[Errno 21] Is a directory: '/config/config.yml' (other solutions haven't worked)

### DISCUSSION THREAD

**Discussion by ryanandrewbaker** [blakeblackshear/frigate#3310] [General]
Hey, 

I've seen lots of other threads with this exact error, but none of those solutions have solved my issue, frustratingly. 

I've installed frigate using docker compose with portainer, and no matter what I change it doesn't find the config.yml file, and always looks for it in /config/config.yml. 

I'm very quickly going more bald. Can someone point me in the right direction?

This is the compose file i'm trying to use (although I've tried many others I've found in other solutions, and tried different variants from the docs).

```
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/ryan/frigate/config.yml:/config/config.yml
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

No matter what I try, I end up with  "[Errno 21] Is a directory: '/config/config.yml'"
