### DISCUSSION TITLE
Please help with detection and MQTT

### DISCUSSION THREAD

**Discussion by pinkfloydFR** [blakeblackshear/frigate#3312] [General]
Hi all !

After a LOT of test i cannot figure how to solve this. I have Home assistant + node red and a frigate docker.

My goal is to receive a notification when someone enter in a zone 0, but i receive a notification too when someone is detected anywhere in the camera.

EDIT : in frigate event i see recording with people NOT in my zone_0, i feel stupid to not understand the problem

Do i need a motion mask with same coordonate of my zone_0 ?

As french, i think i don't understand well the difference between zone, mask and regions.

Will be gratefull is someone can help me for this ! Thanks !

```
# -------------
  entree:
    ffmpeg:
      inputs:
        - path: rtsp://pinkfloyd:ToDf219555!@192.168.0.97:554/stream1
          roles:
            - detect
            - rtmp
            - record
    motion:
      mask: 0,129,0,0,1920,0,1920,946,1920,618,1592,280,0,290
    detect:
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: True
      events:
        required_zones:
          - zone_0
    snapshots:
      required_zones:
        - zone_0
    zones:
      zone_0:
        coordinates: 0,129,0,0,1920,0,1920,946,1920,618,1592,280,0,290
        objects:
          - person

```

And the MQTT topic i read : "frigate/entree/person"
