### DISCUSSION TITLE
NVIDIA acceleration: Unsupported config option for services.frigate: 'runtime' for

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#3342] [Ask A Question] [answered]
I am trying to implement NVIDIA hardware acceleration using the instructions here: https://docs.frigate.video/configuration/nvdec

However docker-compose is giving the error `Unsupported config option for services.frigate: 'runtime'`

My config as is follows:

```
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64nvidia #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    runtime: nvidia #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    shm_size: "128mb" 
    devices:
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/beast/frigate/config.yml:/config/config.yml:ro
      - /mnt/beast/frigate/data:/media/frigate
      - /home/nas/frigate/db:/db
    ports:
      - "5000:5000"
      - "1935:1935"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

Any idea what is wrong with the `runtime` config?

Additionally I am unclear how to include the environment variable `FRIGATE_RTSP_PASSWORD` with the two new variables `NVIDIA_VISIBLE_DEVICES` and `NVIDIA_DRIVER_CAPABILITIES`. The latter are preceded by dashes, while the former is not, and it seems these are incompatible?

Any help appreciated.

Thanks!
