### DISCUSSION TITLE
Issues running nvidia acceleration with 0.11

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#3363] [Ask A Question] [answered]
I am trying to use an nvidia gpu for hardware acceleration on the 0.11 build using [these instructions](https://deploy-preview-2829--frigate-docs.netlify.app/configuration/hardware_acceleration/#nvidia-gpu). 

The first issue I am running into is that the instructions say to use the image `blakeblackshear/frigate:stable`, however I get an error that the manifest for it does not exist: `ERROR: manifest for blakeblackshear/frigate:stable not found: manifest unknown: manifest unknown`

So I changed it to `blakeblackshear/frigate:0.11.0-beta4` and that runs (not sure if I should do this tho).

Next the instructions say to add a "deploy" section:

```
  deploy:    # <------------- Add this section
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
```

But the instructions show that section at the same indent level as "frigate" which caused errors, so I indented it one level in so that it is within/under the "frigate" config and that seems to work (not sure if that's correct tho).

Finally I updated the ffmpeg config in `config.yml`:

```
ffmpeg:

  # nvidia acceleration
  hwaccel_args: -c:v h264_cuvid

  # enable audio
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```

Everything runs now, however when I go to "debug" in the ui it says I am still running on CPU:

![Screenshot from 2022-06-18 14-58-08@2x](https://user-images.githubusercontent.com/118814/174452635-38acb15c-f5d3-47c1-a9ea-85722ab8622d.png)

Any ideas of what I'm doing wrong?
