### DISCUSSION TITLE
nvidia gpu acceleration docker error

### DISCUSSION THREAD

**Discussion by paultanger** [blakeblackshear/frigate#3381] [Ask A Question]
Hi, 
I am trying the instructions described in this Q&A (https://github.com/blakeblackshear/frigate/discussions/3363)  but I'm not able to get it to run, the container fails to start with:

```
Error: failed to start container "frigate-gpu-docker-compose": Error response from daemon: OCI runtime create
 failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: 
Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: ldcache error: process
 /sbin/ldconfig failed with error code: 2: unknown
```

There is a similar older thread here (https://github.com/blakeblackshear/frigate/discussions/2547) with someone who was on TrueNAS SCALE (like my system).. they used the older `blakeblackshear/frigate:stable-amd64nvidia` image, but I couldn't get that working either.. an error regarding the nvidia runtime parameter.

Maybe it is this bug in truenas? https://jira.ixsystems.com/browse/NAS-109192 but that appears fixed (I'm running version TrueNAS-SCALE-22.02.2

my docker compose (wasn't sure if env vars were required, I tried with and without those..)

```
version: "3.9"
services:
  frigate:
    container_name: frigate-gpu
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    # try the beta
    image: blakeblackshear/frigate:0.11.0-beta4
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/zoneminder/apps-data/frigate/frigate-config-gpu.yml:/config/config.yml:ro
      - /mnt/zoneminder/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds external:internal
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

not quite sure where to being troubleshooting this, I verified in the system that the GPU is recognized:

```nvidia-smi
Fri Jun 24 14:01:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 00000000:01:00.0 Off |                  N/A |
| 34%   36C    P8    N/A /  N/A |      0MiB /  2000MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I suspect this should work somehow? Any help appreciated!
