### DISCUSSION TITLE
Repeating of "[cmd] python3 exited 1" over and over restarting

### DISCUSSION THREAD

**Discussion by DanGarion** [blakeblackshear/frigate#3396] [General]
After lots of trial and error I've finally got to a point where I'm sure Frigate should work in my docker setup but I keep running into a loop. I'm running everything on one device at the moment with no network shares or anything. I'm using Docker on debian. When I start the Frigate container it appears that everything starts as it should but I keep seeing what appears to be the container looping. This is what I see in my log over and over. If I try to go to Frigate it just hangs like it is loading. 

> There is nothing to migrate
> [2022-06-28 11:14:33] peewee_migrate                 INFO    : There is nothing to migrate
> 
> t
> [cmd] python3 exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [2022-06-28 11:15:41] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
> Starting migrations
> [2022-06-28 11:15:41] peewee_migrate                 INFO    : Starting migrations
> There is nothing to migrate
> [2022-06-28 11:15:41] peewee_migrate                 INFO    : There is nothing to migrate
> 
> t
> [cmd] python3 exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [2022-06-28 11:16:49] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
> Starting migrations
> [2022-06-28 11:16:49] peewee_migrate                 INFO    : Starting migrations
> There is nothing to migrate
> [2022-06-28 11:16:49] peewee_migrate                 INFO    : There is nothing to migrate
> 
> t
> [cmd] python3 exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.

**Comment by NickM-27** [comment]
Can you please provide your config.yaml?

**Reply by DanGarion** [reply]
I have confirmed the db files are in the directory... It took a lot of trial and error when on my initial install I wanted to have the db on my local device and the media directory on my network share. So I took a step back to try and just get it working on my local device before I go back to working on setting up the network share for the media directory.
```
mqtt:
  host: 172.30.33.2
  user: mqtt
  password: XXXXXX
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXX@XXXXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
detectors:
  coral:
    type: edgetpu
    device: pci
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/db/frigate.db
```

**Reply by DanGarion** [reply]
![image](https://user-images.githubusercontent.com/1666375/176288656-d6882de8-5ccf-4301-9d27-0ebe20496101.png)

`    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/appstorage/frigate/config/config.yml:/config/config.yml:ro
      - /home/docker/appstorage/frigate:/media/frigate`

**Reply by NickM-27** [reply]
Okay, I would say it's most likely either
1. Your mqtt server is not reachable by frigate or some config is incorrect there
2. coral is not being found by frigate. 

If the mqtt server is good then I would try commenting out the detectors section and see what happens. 

Edit: usually there are lots that call this out but maybe something is not showing for some reason, these are the prerequisites for starting up fully

**Reply by DanGarion** [reply]
Ok, I will keep at it. I initially used HASSIO add-on and I was able to get it working (even though I couldn't get mqtt functional yet). The coral was working fine with the add on. I decided against using the add-on since I want my storage to be in a network share on my NAS instead of on my local device. Let me figure out the mqtt issue that I didn't care to work on yet... :)

**Comment by DanGarion** [comment]
Well... since I couldn't figure out what it was I went back to the HASSIO add-on setup, since it works. I just fixed my network shares for the clips and recording folders and called it a day instead. I'm not sure why stuff was having issues outside of the add-on setup but this at least makes it "cleaner" when I'm try _not_ to install anything outside of add-ons.

**Comment by redelacruz** [comment]
In case anyone runs into this issue in the future, I solved this by making sure that my mosquitto container was using the same network as my mqtt container.

I did so by changing my config file like so:
```
frigate:
    ...                                   # other config before
    container_name: frigate
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    network_mode: host                     # <-- add this line or change it to be the same as your mqtt container
    ...                                    # other config after
```
