### DISCUSSION TITLE
Cannot open video device /dev/video0: Operation not permitted

### DISCUSSION THREAD

**Discussion by chaosbunker** [blakeblackshear/frigate#3398] [General]
Hi!

I am using the frigate (full access) addon in Home Assistant (supervised) on a rpi4 and am confused about how to use /dev/video0 as direct input for the raspberry pi camera that is connected to the pi.

I was running into "Cannot open video device /dev/video0: Operation not permitted" when I used the regular Frigate addon, then realized that the Full Access would probably have permission to access /dev/video0, but after switching to Frigate FA I kept having the same issue. I then saw in the [home assistant addon configuration documentation page](https://developers.home-assistant.io/docs/add-ons/configuration/) that there is an optional configuration option `video: true`("Mark this add-on to use the internal video system. All available devices will be mapped into the add-on.") that wasn't set in the Frigate (Full Access) config.yaml, so i added it .. and I also added `- /dev/video0` to `devices:`

I then uninstalled and rebuilt the addon, started it, which didn't work. Then I restarted the host, stopped the addon, clicked rebuild, started it and then it worked. I tried to reproduce this, but would find myself stopping, starting, (re-adding to config,yaml, because it would be overwritten with the repos version, i think after restarting home assistant (but not when rebooting the host)), and rebuilding until it suddenly and finally works again .. 

As you can imagine, i am really confused about how this is done the right way:) What is the correct way to directly access and use /dev/video0 with home assistant supervised?

```
cameras:
  rpicam:
    ffmpeg:
      inputs:
        - path: /dev/video0
          roles:
            - detect
            - rtmp
            - record
          input_args:
            - -f
            - video4linux2
            - -input_format
            - h264
            - -video_size
            - 1440x1080
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - 1
    detect:
      width: 640
      height: 480
      fps: 5
```
