### DISCUSSION TITLE
HA Media browser thinks the camera directory is a video

### DISCUSSION THREAD

**Discussion by jasonjgeiger** [blakeblackshear/frigate#3451] [Ask A Question] [answered]
Running into issues getting the Home Assistant media browser to navigate the Frigate recordings directory properly and playback video.

When navigating through the media browser it makes it to the camera directory but tries to playback back the directory rather than the mp4s in directory. Any help or ideas would be appreciated.

<img width="721" alt="Screen Shot 2022-07-10 at 1 49 55 PM" src="https://user-images.githubusercontent.com/448523/178162516-fc4fa782-018c-4be9-8b23-359f3dfb9305.png">

## Here's the path the media browser should be traversing:
You'll notice from the above screenshot that it never makes it to the mp4s.
```
$ pwd
/media/frigate/recordings/2022-07/10/13/garage_back
$ ls
07.13.mp4  12.13.mp4  17.14.mp4  22.14.mp4  27.13.mp4  32.14.mp4  37.14.mp4  42.13.mp4
```

## HA media_dirs looks to be configured properly:
```
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 740
  unit_system: imperial
  media_dirs:
    frigate: "/media/frigate/"
```

## And the Docker volumes look correct too
<img width="1017" alt="Screen Shot 2022-07-10 at 1 51 59 PM" src="https://user-images.githubusercontent.com/448523/178162567-f1fbb52e-fc60-433a-83cb-07322548d35d.png">

## Running
- HA 2021.9.7
- Frigate 0.10.1
