### DISCUSSION TITLE
BIRDSEYE camera order

### DISCUSSION THREAD

**Discussion by icsboyx** [blakeblackshear/frigate#3453] [General]
Hi to all
Is it possible to put in order camera sequence in BIRDSEYE view?

```
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous
```

regards
