### DISCUSSION TITLE
Struggling to separate database from media

### DISCUSSION THREAD

**Discussion by kentloving** [blakeblackshear/frigate#3462] [Ask A Question] [answered]
I think I am following the docs and example for specifying the database on a local path, and the media on a NAS. (https://docs.frigate.video/configuration/advanced/ and https://docs.frigate.video/installation/). But I can't get the database to any other location on the host.

I have not yet mapped /media/frigate to a NAS; I am just trying to map the database to a host path that is separate from /media/frigate. 

When I finally got them separated, the database exists only inside the container. I think I want it outside so it isn't lost if I get a new image.

I am running Home assistant and Frigate in Docker on an Ubuntu host (which is an old Mac Mini)

the Frigate service from my docker-compose:
```
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml:ro
      - /opt/frigate/media:/media/frigate:rw
      - /opt/frigate/db:/db:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

```

My /opt/frigate/config/config.yml has:
```
database:
  path: /db/frigate.db
```
I created an empty directory at /opt/frigate/db

What Happens:
1) first container start: Constant restarts. Log says 'unable to open database file'
Log has these lines, over and over:
```
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-07-13 09:21:15] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
unable to open database file
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.

```

2) I stopped the container, removed that database: path: setting, then restarted container. Now runs normal. The database is on the host at /opt/frigate/media
3) I execute a shell in the container and created a /db directory inside the container.
4) I stopped the container put back in that database: path: setting, then restarted container. Now runs normal.

BUT, the database is inside the container (at /db). The database does not exist on the host, outside the container.

I don't know Docker very well, but doesn't the image have to allow a folder or file to be mapped? I didn't see "/db" in the list of volumes  when I did a 'docker inspect'.
