### DISCUSSION TITLE
Banana Pi M5 ffmpeg hw acceleration

### DISCUSSION THREAD

**Discussion by pszafer** [blakeblackshear/frigate#3464] [Ask A Question]
Hi,
I have `Banana Pi M5` and I wanted to test camera stream on it.
Unfortunately I can't get hardware acceleration working with either Home Assistant addon or docker image.

It's based on Debian 10, ffmpeg on host shows:
```bash
root@bananapi:~# ffmpeg -hide_banner -hwaccels
Hardware acceleration methods:
vdpau
vaapi
drm
```

Current docker-compose looks like this:
```
version: "3"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/frigate/frigate.yml:/config/config.yml:ro
      - /home/pi/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - 5002:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

Is it possible to enable hardware accelleration on this machine?
