### DISCUSSION TITLE
Recording 24/7 without starting automatically

### DISCUSSION THREAD

**Discussion by chatziko** [blakeblackshear/frigate#3465] [Ask A Question] [answered]
Hello all,

I want to record from cameras only when a certain HA event happens. For this to work, `recording` needs to be enabled in the config. However, when `recording` is enabled, it starts **automatically** every time frigate restarts. On the other hand, if `recording` is disabled in the config, it cannot be enabled via UI/HA/MQTT.

Is there a way to be able to activate recording from HA, but without starting automatically when frigate starts?

I'm just afraid that after some random restart, recording will stay on indefinately filling up my disc.

**Comment by NickM-27** [comment, marked as answer]
I have a camera like this, I simply setup an HA automation that runs when the `camera.office_cam` state goes `from: unavailable` `to: ` (leave blank) and disable recording in this case

That way anytime frigate is restarted and the camera is unavailable and then becomes available it will have recordings disabled

**Reply by chatziko** [reply]
I see, it can certainly be done from the HA side, thanks!

Btw it's a bit weird that `recording: false` in the config cannot be later changed from HA. Essentially `recording` can be changed from `true` to `false`, but not from `false` to `true`. I would expect the config file to be the default, until it's changed by some user action. I guess there must be some reason, it just feels weird :smile: 

PS. many thanks for this awesome project!

**Reply by NickM-27** [reply]
> I would expect the config file to be the default, until it's changed by some user action. I guess there must be some reason, it just feels weird 😄

As far as recording is concerned, `recording: false` is essentially a hard disable

when you use MQTT (HA integration) to "disable" recording it actually doesn't stop, it continues to record and write the files frigate just doesn't move these files to permanent storage (as it is disabled). 

So while it might be misconstrued as the same thing, it is actually different and using the recording toggle is more of a "ignore all recordings" instead of "disable recordings"

**Reply by chatziko** [reply]
Thanks for the explanation, the naming is indeed a bit misleading but I see the point.

**Reply by reidprichard** [reply]
It seems that Frigate entities no longer go `unavailable` when Frigate is restarted. Any idea how to accomplish this now? I suppose I could have an automation run whenever recording gets turned on. If the condition I wanted to use to temporarily enable automation were a state, I could check that and only disable automation if it were false, but that wouldn't work if I wanted to enable recording based on an event.

**Comment by marcgarciamarti** [comment]
> > I would expect the config file to be the default, until it's changed by some user action. I guess there must be some reason, it just feels weird 😄
> 
> As far as recording is concerned, `recording: false` is essentially a hard disable
> 
> when you use MQTT (HA integration) to "disable" recording it actually doesn't stop, it continues to record and write the files frigate just doesn't move these files to permanent storage (as it is disabled).
> 
> So while it might be misconstrued as the same thing, it is actually different and using the recording toggle is more of a "ignore all recordings" instead of "disable recordings"

Hi @NickM-27 !

I'm a bit confused with what I'm experiencing with frigate lately. I would say that even when ```recording```is set to ```true``` in the config file, my recent experience is that when I restart my frigate add-on, even when ```detect``` is set to ```enabled: false```, recordings start to fill up the disk on my server. 

Not only do I have this setting, I can also confirm that _movement detection_ visual cue on the front-end is greyed out, meaning that frigate should not trigger image recording upon movement being detected, right?  

Apologies if there is a gap in my understanding.

Thanks

**Reply by NickM-27** [reply]
> Not only do I have this setting, I can also confirm that movement detection visual cue on the front-end is greyed out, meaning that frigate should not trigger image recording upon movement being detected, right?

There is no movement detection toggle on the frontend. The only way they turn this off is via MQTT / frigate integration

**Reply by marcgarciamarti** [reply]
Will this button not enable movement detection?

<img width="455" alt="Screenshot 2023-10-15 at 16 48 15" src="https://github.com/blakeblackshear/frigate/assets/12695572/287d8649-2517-4851-8ebc-bed96bd5170a">

**Reply by NickM-27** [reply]
That is a toggle for object detection only, motion detection is separate

**Comment by marcgarciamarti** [comment]
> That is a toggle for object detection only, motion detection is separate

@NickM-27 
Could you possibly elaborate a bit more? My use case is:
- I only enable the frigate add-on when I go on holidays or when I go away for more than a couple of days. I'm considering automating this, but I manually enable the add-on right now.
- my cameras are not on. They are hooked up to an snmp port and I power them up manually as well. Will try to automate this as well in the future.
- I have detection enabled as per my above comments. Happy to share my whole configuration file if that's ok.

I would like to make sure I can enable recording when something moves inside my home, and only record the video feed if what has triggered the recording is a person (I have a Coral TPU dongle).

I would be very very thankful if you helped me set this up properly. I clearly don't have it correctly setup based on what I understand from the above.

**Reply by NickM-27** [reply]
You should only configure recording for events then https://docs.frigate.video/configuration/record#what-if-i-dont-want-247-recordings

**Reply by marcgarciamarti** [reply]
Like this?

```
mqtt:
  host: 192.168.1.5
  user: _redacted_
  password: _redacted_

birdseye:
  enabled: True
  mode: motion

cameras:
  anpviz-camera-dome-comedor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.31:554/stream2
        roles:
          - detect
      - path: rtsp://192.168.1.31:554/stream0
        roles:
          - record
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects

  anpviz-camera-dome-recibidor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.32:554/stream0
        roles:
          - record
      - path: rtsp://192.168.1.32:554/stream1
        roles:
          - detect
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 720
      height: 480
      fps: 5
    motion:
      mask:
        - 453,170,459,204,482,198,498,182,509,154,518,103,511,82,489,79,469,87
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects

detectors:
  coral:
    type: edgetpu
    device: usb
```

**Reply by NickM-27** [reply]
No, you are configuring frigate to keep 7 days of 24/7 motion based recordings, which sounds like exactly what you don't want

**Reply by marcgarciamarti** [reply]
> No, you are configuring frigate to keep 7 days of 24/7 motion based recordings, which sounds like exactly what you don't want 
I've removed that. What about this config?
```

mqtt:
  host: 192.168.1.5
  user: _redacted_
  password: _redacted_

birdseye:
  enabled: True
  mode: motion

cameras:
  anpviz-camera-dome-comedor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.31:554/stream2
        roles:
          - detect
      - path: rtsp://192.168.1.31:554/stream0
        roles:
          - record
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects

  anpviz-camera-dome-recibidor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.32:554/stream0
        roles:
          - record
      - path: rtsp://192.168.1.32:554/stream1
        roles:
          - detect
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 720
      height: 480
      fps: 5
    motion:
      mask:
        - 453,170,459,204,482,198,498,182,509,154,518,103,511,82,489,79,469,87
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      events:
        retain:
          default: 14
          mode: active_objects

detectors:
  coral:
    type: edgetpu
    device: usb
```

**Reply by NickM-27** [reply]
The other camera still has it

**Reply by marcgarciamarti** [reply]
> The other camera still has it

pfffff 🤣 I'm dumb 😃 
Say, how do I now enable object detection from within HA? I assume the toggle I enclosed above is one way, but I wonder if I can do a service call from within an automation? 
I'm asking this because I read you mentioned MQTT?
THANKS A MILION for your support!

**Reply by NickM-27** [reply]
The frigate HA integration has a toggle for object detection as well

**Reply by marcgarciamarti** [reply]
> The frigate HA integration has a toggle for object detection as well

Gotcha! Thanks!

If you spot any other strange thing on my config, do please let me know. Thanks again!

**Reply by marcgarciamarti** [reply]
Hi @NickM-27 

just used this new setup today for the first time, and when motion was detected, no video feed was captured on disk. All I saw when I wanted to check the recorded footage is the following message:

```
No Recordings Found. Make sure you have enabled the record role in your configuration for the X camera
```

This is the confirmation that I have in my system. I may have messed something up :(

```

mqtt:
  host: 192.168.1.5
  user: REDACTED
  password: REDACTED

birdseye:
  enabled: True
  mode: motion

cameras:
  anpviz-camera-dome-comedor:
    ffmpeg:
 #     hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.31:554/stream2
        roles:
          - detect
      - path: rtsp://192.168.1.31:554/stream0
        roles:
          - record
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7

    record:
      enabled: True
      events:
        retain:
          default: 14
          mode: active_objects

  anpviz-camera-dome-recibidor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.32:554/stream0
        roles:
          - record
      - path: rtsp://192.168.1.32:554/stream1
        roles:
          - detect
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 720
      height: 480
      fps: 5
#    motion:
#      mask:
#        - 1337,510,1361,499,1408,493,1449,467,1498,424,1530,364,1547,302,1551,249,1549,206,1534,186,1489,174,1444,178,1412,195
#        - 1517,103,1541,101,1539,77,1515,77
    motion:
      mask:
        - 453,170,459,204,482,198,498,182,509,154,518,103,511,82,489,79,469,87
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7

    record:
      enabled: True
      events:
        retain:
          default: 14
          mode: active_objects

detectors:
  coral:
    type: edgetpu
    device: usb

```
