### DISCUSSION TITLE
Clips don't start with event

### DISCUSSION THREAD

**Discussion by rea-ducks** [blakeblackshear/frigate#3469] [General]
Hi,

all the clips frigate saves start about 10 seconds after what it says is the start of the event. That often leads to really missing action, e.g. the postman comes through our frontyard, throws in the post and leaves. Takes about 30 seconds.
Frigate shows one event 08:38:36 to 08:39:07 which is about right. The snapshot is from 08:38:49 when the postman is right at the postbox, that's okay too. But the video is 08:38:47 to 08:39:11.
So why doesn't start the footage at the start of the event or even before (5 seconds should be the default)?

Reah

**Comment by NickM-27** [comment]
Please post your config

**Reply by rea-ducks** [reply]
Oh, of course:

```
mqtt:
  host: 192.168.1.2
  user: username
  password: password
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  Kamera:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.0.0:554/stream=1
          roles:
            - detect
            - rtmp
          input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
        - path: rtsp://username:password@192.168.1.100:554/stream=0
          roles:
            - record
    rtmp:
      enabled: True
    detect:
      enabled: True
      width: 448
      height: 800
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0,21,0,97,145,91,146,21
snapshots:
  enabled: True
  timestamp: True
  retain:
    default: 3
timestamp_style:
  position: "tl"
  format: "%Y-%m-%d %H:%M:%S"
record:
  enabled: True
  retain:
    days: 0
    mode: active_objects
  events:
    retain:
      default: 2
      mode: active_objects
database:
  path: /db/frigate.db
```
