### DISCUSSION TITLE
Motion mask not working on specific camera

### DISCUSSION THREAD

**Discussion by vyruz1986** [blakeblackshear/frigate#3476] [Ask A Question]
Hi everyone!
Thanks for this great product, I spent an afternoon setting it up with 3 camera's and it's mostly working fine!

I have 1 issue though: Some of my camera's see a portion of the street I live in, and I'm not interested in all people/cars passing through my street, I tried masking the street area with a motion mask, since by reading the docs that seems to be the recommended way to disable object detection completely in a certain area.
For 1 camera this works fine, on another camera however, it just keeps detecting objects passing through the street.
I can see the mask in the debug view, and can confirm there are no motion boxes appearing in the masked area, so why is Frigate still detecting objects there?

**Comment by NickM-27** [comment]
> I tried masking the street area with a motion mask, since by reading the docs that seems to be the recommended way to disable object detection completely in a certain area.

Where did you see that? Motion masks are explicitly not to be used for this purpose as explained here https://docs.frigate.video/configuration/masks

Frigate is designed to have only non objects masked off. Use zones to ignore objects that don't enter an area of interest

**Reply by NickM-27** [reply]
This may be helpful as well https://github.com/blakeblackshear/frigate/issues/2965#issuecomment-1069056364

> I think this is the most common error in configuring Frigate. Many people assume that a motion mask is how you block off areas of your camera where you don't want detections, but it's not designed to work that way at all. Frigate is designed to track objects across the entire frame and allow you only be notified about objects that enter the areas that you do care about. Motion masks should be used to mask timestamps and trees that blow in the wind. Object masks should be used to filter guaranteed false positives such as something on a roof that gets detected as a car, not prevent true positives from triggering alerts. It is designed to detect a car way down the street and track it as it approaches your driveway. You may only want to be notified if a car enters your driveway, but you want the event to start as soon as the car was visible.

**Comment by vyruz1986** [comment]
OK, that clarifies why it's not working.
From [the docs](https://docs.frigate.video/configuration/masks):
>Motion masks: Motion masks are used to prevent unwanted types of motion from triggering detection.

And further down:

>It is helpful to understand a bit about how Frigate uses motion detection and object detection together.
>First, Frigate uses motion detection as a first line check to see if there is anything happening in the frame worth checking with object detection.

So I concluded: No motion == no object detection
But the comment you then quoted seems to contradict that

> This may be helpful as well [#2965 (comment)](https://github.com/blakeblackshear/frigate/issues/2965#issuecomment-1069056364)
> 
> > I think this is the most common error in configuring Frigate. Many people assume that a motion mask is how you block off areas of your camera where you don't want detections, but it's not designed to work that way at all. Frigate is designed to track objects across the entire frame and allow you only be notified about objects that enter the areas that you do care about. Motion masks should be used to mask timestamps and trees that blow in the wind. Object masks should be used to filter guaranteed false positives such as something on a roof that gets detected as a car, not prevent true positives from triggering alerts. It is designed to detect a car way down the street and track it as it approaches your driveway. You may only want to be notified if a car enters your driveway, but you want the event to start as soon as the car was visible.

Good to know that's how Frigate works. I would argue that it's not desirable to have continuous object detection in uninterested areas, since it demands resources of the host system for detecting objects in places the user has no interest in.

I'll try using zones instead of motion masks, thanks for explaining!

**Reply by NickM-27** [reply]
> No motion == no object detection
But the comment you then quoted seems to contradict that

Motion is required, but motion boxes are joined together when they occur in the same frame so motion masks especially for cars will not necessarily cover the bottom center of the motion box which causes the detection anyway (hence, another reason why it isn't designed to work this way)

> I would argue that it's not desirable to have continuous object detection in uninterested areas, since it demands resources of the host system for detecting objects in places the user has no interest in.

It's not continuous as motion is required to trigger the first object detection, after that the object is tracked. Also a person in the street is uninteresting but if they walk into your front yard odds are you'd like to have the entire time that person was in frame recorded, not just when they entered the yard.

**Reply by NickM-27** [reply]
An example of this is the car drives by and the car itself is motion masked but the car casts a shadow part of which isn't covered and that's registered as motion. Even a non masked tree blowing in the wind could cause motion if it's close enough to include the car in which case it's detected and starts being tracked

**Comment by vyruz1986** [comment]
I think I need some help on the zone configuration, since it's still detecting cars in the street even after defining a zone for the area excluding the street.

My camera config looks like so:
```yaml
  street:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://x.x.x.x/videostream.cgi
          roles:
            - detect
            - record
            - rtmp
    zones:
      without_street:
        coordinates: 0,0,170,0,160,71,287,126,271,243,433,381,532,480,0,480
        objects:
          - person
          - car
          - cat
          - dog
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
        - cat
        - dog
```
The docs aren't quite clear (to me at least) about how to configure the tracked objects (in general this is not very clear in the docs, just a list of objects frigate can track) vs objects limited to a specific zone. Should I remove the `objects.track` object from my config?

**Reply by NickM-27** [reply]
You define your list of objects to track per camera (or globally). The zones can be set to only track a subset of those objects. If you only want events when the object enters that zone you need to use `required_zones`

**Reply by vyruz1986** [reply]
Hmm I still can't seem to get it to work, this is my current config:
```yaml
  street:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://hass:3Cmo0rbo@192.168.10.103/videostream.cgi
          roles:
            - detect
            - record
            - rtmp
    zones:
      without_street:
        coordinates: 0,0,170,0,160,71,287,126,271,243,433,381,532,480,0,480
    record:
      events:
        required_zones:
          - without_street
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
        - cat
        - dog
```
This is what my zone looks like:
![image](https://user-images.githubusercontent.com/3620147/179370154-c703aabb-f74c-46aa-b39d-bc19865aa296.png)

And this is the clip which was recorded:
![image](https://picoshare.fastlikehell.com/!8pajYKnoVF)
[Link ](https://picoshare.fastlikehell.com/!8pajYKnoVF) since gif as image doesn't seem to work

**Reply by NickM-27** [reply]
A couple things. 

1. `required_zones` needs to be added under snapshots as well
2. Zones presence is based on the bottom center of the objects bounding box. Looks like in some edge cases the bottom center of a cars bounding box could hit the top right of that zone (not sure, probably just try 1 and see what happens).

**Reply by vyruz1986** [reply]
Giving it another try with those 2 points resolved. I do have snapshots disabled globally (or better said: I didn't configure it, and it seems to be disabled by default) are you sure I need to add the `required_zones` to the `snapshots` object of the camera? It would be a bit counterintuitive that we need to configure the `required_zones` for snapshots even though it's disabled globally

**Reply by vyruz1986** [reply]
Still not working unfortunately :(

Latest config:
```yaml
  street:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://hass:3Cmo0rbo@192.168.10.103/videostream.cgi
          roles:
            - detect
            - record
            - rtmp
    zones:
      without_street:
        coordinates: 0,480,0,480,0,97,128,110,297,235,534,480
    record:
      events:
        required_zones:
          - without_street
    snapshots:
      required_zones:
        - without_street
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
        - cat
        - dog
```
Debug view while a car was passing through the street (this specific car did not show up in the events though):
![image](https://user-images.githubusercontent.com/3620147/179395441-4e2872d5-0415-4621-94a0-7a868675dd17.png)
Snapshot of event which captured car in the street:
![image](https://user-images.githubusercontent.com/3620147/179395505-8034ca73-67ed-4636-b8cb-6564c0b73713.png)
