### DISCUSSION TITLE
new installation bad old configuration

### DISCUSSION THREAD

**Discussion by matteopizzoli** [blakeblackshear/frigate#3503] [General]
Hi,
i use frigate for a couple of years on docker and worked very well but a couple of days ago the ssd was broken an i reinstalled everityng (home assistant on VM and docker for frigate).
the problem is that with the SAME old working well configuration give me a config validation error,
i update from ubuntu 20 to 22 and the installation of frigate is fresh and updated.
i've tried with the basic configuration wiith only 1 camera (same path and parameters of cameras) but still give me errors:

frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-07-21 09:47:50] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Your config file is not valid!                     ***
frigate  | ***    Please check the docs at                           ***
frigate  | ***    https://docs.frigate.video/configuration/index     ***
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Config Validation Errors                           ***
frigate  | *************************************************************
frigate  | mapping values are not allowed here
frigate  |   in "<unicode string>", line 19, column 16:
frigate  |               roles:
frigate  |                    ^
frigate  | Traceback (most recent call last):
frigate  |   File "/opt/frigate/frigate/app.py", line 312, in start
frigate  |     self.init_config()
frigate  |   File "/opt/frigate/frigate/app.py", line 77, in init_config
frigate  |     user_config = FrigateConfig.parse_file(config_file)
frigate  |   File "/opt/frigate/frigate/config.py", line 900, in parse_file
frigate  |     config = yaml.safe_load(raw_config)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 162, in safe_load
frigate  |     return load(stream, SafeLoader)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 114, in load
frigate  |     return loader.get_single_data()
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
frigate  |     node = self.get_single_node()
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
frigate  |     document = self.compose_document()
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document
frigate  |     node = self.compose_node(None, None)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  |     item_value = self.compose_node(node, item_key)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  |     item_value = self.compose_node(node, item_key)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  |     item_value = self.compose_node(node, item_key)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  |     item_value = self.compose_node(node, item_key)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 82, in compose_node
frigate  |     node = self.compose_sequence_node(anchor)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
frigate  |     node.value.append(self.compose_node(node, index))
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
frigate  |     while not self.check_event(MappingEndEvent):
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event
frigate  |     self.current_event = self.state()
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
frigate  |     if self.check_token(KeyToken):
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 116, in check_token
frigate  |     self.fetch_more_tokens()
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
frigate  |     return self.fetch_value()
frigate  |   File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 577, in fetch_value
frigate  |     raise ScannerError(None, None,
frigate  | yaml.scanner.ScannerError: mapping values are not allowed here
frigate  |   in "<unicode string>", line 19, column 16:
frigate  |               roles:
frigate  |                    ^
frigate  |
frigate  | *************************************************************
frigate  | ***    End Config Validation Errors                       ***
frigate  | *************************************************************
frigate  | [cmd] python3 exited 1
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 1

the config i use here is:
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  user: xxx
  password: xxx
cameras:
  back:
    ffmpeg:
      hwaccel_args:
       - -hwaccel
       - vaapi
       - -hwaccel_device
       - /dev/dri/renderD128
       - -hwaccel_output_format
       - yuv420p
      inputs:
       - path: rtsp://user:pass@192.168.1.130:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
  detect:
    height: 480
    width: 640
    fps: 4

version: '3.9'
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: blakeblackshear/frigate:stable-amd64
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /home/server/frigate/config/config.yml:/config/config.yml:ro
      - /home/server/frigate/clips:/frigate/clips   
      - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
        target: /cache
        tmpfs:
          size: 100000000
    ports:
      - '5000:5000'
      - '1935:1935'
    environment:
      FRIGATE_RTSP_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m

very simple, but i doesent'work,
it is a configuration error or an installation error? (maybe i did a mistake)

**Comment by NickM-27** [comment]
Please format your config, it's impossible to tell what the spacing is correctly (just repaste:

\```
Paste
\```

Unless that is how it is in the fine in which case spacing needs to be corrected

**Comment by matteopizzoli** [comment]
```
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  user:xxx
  password: xxx
cameras:
  back:
    ffmpeg:
      hwaccel_args:
       - -hwaccel
       - vaapi
       - -hwaccel_device
       - /dev/dri/renderD128
       - -hwaccel_output_format
       - yuv420p
      inputs:
       - path: rtsp://xxx:xxx@192.168.1.130:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
  detect:
    height: 480
    width: 640
    fps: 4

```

**Reply by matteopizzoli** [reply]
this is the complete (but only one camera ,not all) old configuration:

```
detectors:
  coral_pci:
    type: edgetpu
    device: pci
logger:
  # Optional: default log level (default: shown below)
  default: debug
  # Optional: module by module log level configuration
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  user: xxx
  password: xxx
clips:
  max_seconds: 300
  retain:
    default: 30



snapshots:
  retain:
    default: 30
ffmpeg: {}
cameras:
  IPCcancelloAnteriore:
    ffmpeg:
      hwaccel_args:
       - -hwaccel
       - vaapi
       - -hwaccel_device
       - /dev/dri/renderD128
       - -hwaccel_output_format
       - yuv420p
      inputs:
        - path: >-
            rtsp://xxx:xxx@192.168.1.130:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: >-
            rtsp://xxx:xxx@192.168.1.130:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
    height: 480
    width: 640
    fps: 4
    motion:
      mask: >-
        0,246,275,170,418,216,415,480,640,480,640,0,0,0
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 0,0,413,0,410,480,0,480
    snapshots:
      enabled: true
      bounding_box: true

```
