### DISCUSSION TITLE
Camera on vlc is work but in frigate is not

### DISCUSSION THREAD

**Discussion by boyphongsakorn** [blakeblackshear/frigate#3522] [Ask A Question]
Camera on VLC is work but in frigate is not
my brain is blank, i don't know how to do that
in VLC everything look normal
but in frigate is green screen
Codec
![image](https://user-images.githubusercontent.com/3013842/180730610-3e34be76-c546-4327-867c-e9a6f4033393.png)
My Config
```
mqtt:
  host: 192.168.31.227
  user: mqtt
  password: team1556th

cameras:
  {other camera}
  dw_camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:team1556th@192.168.31.205:554/onvif1
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 2

record:
  enabled: true
  retain:
    days: 0
    mode: motion

```
