### DISCUSSION TITLE
CPU Usage seems quite high with HW Accel and EdgeTPU?

### DISCUSSION THREAD

**Discussion by realroywalker** [blakeblackshear/frigate#3542] [Ask A Question]
Just started out with Frigate and added two cameras to test out - I'm running it in docker on an Intel i5-4590, with a Coral (USB) attached.

I have my camera stream resolutions set to the lowest setting and have configured detect to 6fps (to match the rate on the camera stream - I also configured i-frame to 6 on the cameras).
When Frigate is running I'm seeing an increase in CPU usage by around 20% (solidly), I've used intel_gpu_top and confirm that it looks like the GPU is active when the container is running.. to me, this CPU usage seems pretty high, given i'm working with relatively low resolutions, and the GPU should be accelerating the decode.. then the coral should be picking up any detection workload.

Am I expecting too much here, or does it sound like I've not got the config quite right?

Here is the config I have;

```
mqtt:
  host: <mqtt_ip>
  user: <mqtt_user>
  password: <mqtt_pass>
  
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
   
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@<door-cam>:554
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: true
    detect:
      width: 384 
      height: 512
      fps: 6
    record:
      enabled: True
      events:
        retain:
          default: 10        
  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@<garden-cam>:554/Streaming/Channels/102
          roles:
            - detect
            - record  
            - rtmp   
    rtmp:
      enabled: true 
    detect:
      width: 640 
      height: 480
      fps: 6      
    record:
      enabled: True
      events:
        retain:
          default: 10 
```

**Comment by NickM-27** [comment]
That's an older gen CPU, motion detection is somewhat computationally expensive as well. 

If you are on 0.10.1 may be worth checkout out 0.11 which is currently in RC. It uses the jellyfin ffmpeg build and in the docs there are instructions for older CPUs to try a different hwaccel driver which may decrease your CPU usage some. Can always use htop to see what processes are taking up the most CPU.

**Reply by realroywalker** [reply]
Thanks - I think I found the issue, my front door camera wasn't using the right address for the substream so it was automatically sending the full stream which is 1536x2048 so explains the extra load..

I've fixed that now and CPU hovers around 5% which is more like it!

However, with the following config I only see the low resolution stream in the Frigate webui and in Home Assistant (using the camera that automatically get created there by the Frigate integration)

```
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@<doorcam>/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://<user>:<password>@<doorcam>/Streaming/Channels/1
          roles:
            - rtmp
            - record    
    detect:
      width: 384
      height: 512
      fps: 6
    motion:
      mask:
        - 0,238,136,211,235,206,384,232,384,0,0,0      
    record:
      enabled: True
      events:
        retain:
          default: 10  
```

I see the same issue for both my cameras, only the low res stream seems to display - I have confirmed the URLs via VLC and in the example above the URL ending '/2' is 384x512 and '/1' is 1536x2048.

I wondered if I could just use the high res stream and use VAAPI to re-scale it so I'm only pulling one stream from the camera, using this: https://github.com/blakeblackshear/frigate/issues/2383 as a pointer, I tried the following but no joy there either..

```
output_args:
        detect: -vf fps=fps=5,scale_vaapi=w=384:h=512:format=nv12,hwdownload,format=nv12,format=yuv420p -an -f rawvideo
```
