### DISCUSSION TITLE
Error on startup

### DISCUSSION THREAD

**Discussion by biggen1684** [blakeblackshear/frigate#358] [General]
Getting this error when starting with `docker-compose` using the `docker-compose file` on the instruction page:

`ffmpeg_input = get_ffmpeg_input(ffmpeg['input'])
 KeyError: 'input'`

Here is my config file.  Any ideas?

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  user: xxxx
  password: xxxx

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.200.200.13:554/cam/realmonitor?channel=1&subtype=1   
          roles:
            - rtmp
            - detect
    fps: 5
```

**Comment by blakeblackshear** [comment]
This looks like an error from `0.7.3`, but your config is the new format for the `0.8.0` beta.

**Reply by jamos77** [reply]
If this is for 0.80 beta you're missing the height and width from your config

```YAML
mqtt:
  host: mqtt.server.com
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
    height: 720
    width: 1280
    fps: 5
```

**Comment by biggen1684** [comment]
Ahh ok.  Yeah, I had started with the official Frigate and then moved to the Beta.  Ok, I'll give it another go.  The older version said it auto detected the height/width so I assume the beta did as well.

Thanks for cleaning up that markdown by the way.

**Comment by biggen1684** [comment]
So I'm beyond frustrated with Frigate.  I've worked with computers since the mid-90s and I'm not sure another program has frustrated more than this one just to get it up and running.

So if I want to use the newer **Beta version** of Frigate is the docker-compose file [here](https://github.com/blakeblackshear/frigate/tree/release-0.8.0#docker) the correct one to use???  I can tell you that file does not work with up to date version of Docker and Docker-Compose. The error message is:
`Unsupported config option for frigate: 'healthcheck'
frigate.volumes contains an invalid type, it should be a string`

I'm running a fresh Debian install with the latest Docker, Docker Engine, and Docker-Compose:

```Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:50 2020

docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

The only way to make that file work is to add `version` and `services` to the top of it like so:

    version: "3.8"
    services:
      frigate:
        container_name: frigate
        restart: unless-stopped
        ....

So if I add `version` and `services` it will at least begin to download the image listed in the docker file but then error out with an `input`  error when it tries to start Frigate.  The error is: 
```
On connect called
frigate    | Traceback (most recent call last):
frigate    |   File "detect_objects.py", line 441, in <module>
frigate    |     main()
frigate    |   File "detect_objects.py", line 196, in main
frigate    |     ffmpeg_input = get_ffmpeg_input(ffmpeg['input'])
frigate    | KeyError: 'input
```

  Here is my `config`:

```mqtt:
  host: xxx.xxx.xxx.xxx
  user: user
  password: password

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.200.200.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
    height: 704
    width: 480
    fps: 5
```

So I don't get it.  What am I doing wrong?  I'm using the exact `docker-compose` file listed [here](https://github.com/blakeblackshear/frigate/tree/release-0.8.0#docker) and then I'm using a pretty vanilla config file based off of [this](https://github.com/blakeblackshear/frigate/tree/release-0.8.0#configuration).  I've bet I've spent a total of 5 - 6 hours working on this the last couple of days.  I'm so far invested in this even if I don't like it, I plan on seeing it through till the end because its pissed me off enough now I want to conquer it.

**Reply by paularmstrong** [reply]
You must also have a `- detect` role defined for an input:
```yaml
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.200.200.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
            - detect # add this
    height: 704
    width: 480
    fps: 5
```

**Reply by biggen1684** [reply]
Thanks for the reply paul.  No change when I add that.  Still the same error message I listed above.

**Comment by blakeblackshear** [comment]
Sorry for all the confusion. You are getting stuck in the middle of a bunch of changes to the documentation, and the beta version's documentation is **also** in beta. Let's reset and I can use this to update the docs for others. Just so I have context, you are running the Frigate container with docker compose on Debian. What about the rest of your setup? Are you running homeassistant somewhere else? Are you already running an mqtt server as well?

**Reply by biggen1684** [reply]
Hey Blake!  I'm running Frigate on Debian bare metal on a NUC via Docker-Compose.  I have a VM setup on Proxmox for HomeAssistant with Mosquito for an MQTT there as well.  

So two systems: One NUC for main Frigate install that the Coral device will install directly to and then a HA VM on Proxmox for everything else.

**Comment by blakeblackshear** [comment]
This should work for docker compose:
```yaml
version: "3.6"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: blakeblackshear/frigate:0.8.0-beta1-amd64
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - <path_to_config>:/config
      - <path_to_directory_for_clips>:/media/frigate/clips      
      - <path_to_directory_for_recordings>:/media/frigate/recordings      
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 100000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

Your config for frigate should be:
```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  user: user
  password: password

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.200.200.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    height: 480
    width: 704
    fps: 5
```
