### DISCUSSION TITLE
Can someone help me with enabling nVidia support for Frigate? GT710 Debian

### DISCUSSION THREAD

**Discussion by drock1985** [blakeblackshear/frigate#3590] [Ask A Question]
Hi,

I've been trying for a day or so to enable nVidia driver support to take some of the strain off my CPU that is running 4 HD 1080P cameras currently, as the CPU usage is hovering around 80% most of the time. This is the configuration for docker-compose that I am using:

'
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64nvidia
    runtime: nvidia
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/vpu_service
      - /dev/dri/card0
      - /dev/dri/card1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "rtsp_passowrd_here"
'

This is my config.yml for frigate

'mqtt:
  host: 192.168.1.56
  user: frigate
  password: mqtt_password_here
  
detectors:
  cpu1:
    type: cpu
    num_threads: 4

cameras:
  side_window: # <------ Name the camera
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://192.168.1.62:8554/driveway # <----- Update for your camera
          roles:
            - detect
            - rtmp
'#'            - record
            - clips
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
        required_zones:
          - awalt_road
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 4
          bear: 5
    zones:
      driveway:
        coordinates: 240,836,845,878,1361,845,1186,711,363,734
      awalt_road:
        coordinates: 0,703,484,613,576,639,0,821
        
  porch: # <------ Name the camera
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://192.168.1.62:8554/porch-cam # <----- Update for your camera
          roles:
            - detect
            - rtmp
'#'            - record
            - clips
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
        - bear
        - bird
        - dog
        - knife
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 4
          bear: 5          
  wyzepan: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.62:8554/wyze-pan # <----- Update for your camera
          roles:
            - detect
            - rtmp
'# '           - record
            - clips
      input_args:
        - -c:v
        - h264_cuvid
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 4
          bear: 5          
  wyze: # <------ Name the camera
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://192.168.1.62:8554/back-yard-cam # <----- Update for your camera
          roles:
            - detect
            - rtmp
'#'            - record
            - clips
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 15
          bear: 5
'

And when looking at nvidia-smi is either the docker terminal or just in the OS; it never shows any usage. I do see around 400/1000mb of ram being used on the card though; just no processes. What am I configuring wrong? Is it because it's a GT 710?

-Cheers,

**Comment by NickM-27** [comment]
I'd recommend trying frigate 0.11.0 (currently in release candidate). It is much simpler to enable and use: https://deploy-preview-2829--frigate-docs.netlify.app/configuration/hardware_acceleration#nvidia-gpu

**Reply by drock1985** [reply]
hi @NickM-27 

So I've installed 0.11-RC1 and have it booting successfully with the nvidia GPU added. So far i'm at the same point using the same config.yml as I was before where I can see the GPU memory being used up (102mb per camera) but there are no processes running. When does the GPU get tasked in Frigate? Maybe i'm missing something.

**Reply by NickM-27** [reply]
The GPU will run as it is decoding the frames for the `detect` stream so should be used constantly. 

Did you change your config according to the docs I linked as far as adding the 

```yaml
  deploy:    # <------------- Add this section
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
```

**Reply by drock1985** [reply]
Yes I did. If those lines are not present, then nvidia-smi fails to run. 

Here is my full config that works in docker-compose. 


```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-rc1
    deploy:    # <------------- Add this section
      resources:
        reservations:
         devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password_goes_here"

```

**Reply by NickM-27** [reply]
What happens if you run `nvidia-smi` in the host instead of inside the container

**Reply by drock1985** [reply]
I get the same output from both.

# from the host
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   73C    P0    N/A /  N/A |    408MiB /   973MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

# Inside the container
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   73C    P0    N/A /  N/A |    408MiB /   973MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Reply by drock1985** [reply]
I should add that if I turn off the container with Frigate the video ram drops to 0mb so I know something is connected just not sure what.

**Reply by NickM-27** [reply]
Okay, at this point then it may be that your GPU isn't supported for HW Accel. I am not sure if jellyfin has a list (which may be helpful, but it really should be working). That or maybe try a different driver from the host.

**Reply by drock1985** [reply]
@NickM-27 

You are correct. Just went through the Jellyfin docs and they point to  link on nVidia's website that states the GTX 745 is the lowest series cart to support the decoding. Guess i'm on the hunt for another low profile single slot video card.

**Reply by NickM-27** [reply]
Sorry to hear that, can you please share that link? Will likely be useful in the future

**Reply by drock1985** [reply]
Sure. The link on the Jellyfin documentation is [here](https://jellyfin.org/docs/general/administration/hardware-acceleration.html) and under the nvidia section they have a link pointing to [here](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) on nvidia's website. Encoding and Decoding both have the GTX745 as the min.

**Reply by drock1985** [reply]
Also to add to that. On nvidia's website if you punch in the model number of the card you have you can see the maximum allowable encode/decode streams per model of card. May be helpful for anyone buying a graphics card to offload some of the CPU load. 

Ex. a GT1030 has no encoding capabilities whatsoever. Looks like for anyone with a SFF PC (ex. Dell Optiplex) the best goto cards are Quadro. T400 or P600 IMHO.

**Reply by drock1985** [reply]
Ok final update: I was able to find locally a Quadro P620 and installed that in my system along with 0.11-RC1 of Frigate. All is working as it should with the config above given and I can see 4 ffmpeg processes with nvidia-smi. Only thing is my PC is still pegging 95% use; so my guess that is detections now and not detections/encoding mixed. 

```
Sat Aug  6 17:04:38 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P620         Off  | 00000000:01:00.0 Off |                  N/A |
| 37%   54C    P0    N/A /  N/A |    598MiB /  1998MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3498      C   ffmpeg                            149MiB |
|    0   N/A  N/A      3499      C   ffmpeg                            149MiB |
|    0   N/A  N/A      3502      C   ffmpeg                            149MiB |
|    0   N/A  N/A      3504      C   ffmpeg                            149MiB |
+-----------------------------------------------------------------------------+

```

**Reply by NickM-27** [reply]
One thing to make sure is that your `detect` resolution for each camera matches the actual resolution of the stream. CPU is still used to resize the stream  so if that doesn't match then it can add a decent amount of CPU

**Reply by drock1985** [reply]
> One thing to make sure is that your `detect` resolution for each camera matches the actual resolution of the stream. CPU is still used to resize the stream so if that doesn't match then it can add a decent amount of CPU

Ok.. maybe that could be it. The cameras are 1080p (wyze cams) so the resolution I have set is 1920x1080...... where would I configure the detect resolution?

**Reply by NickM-27** [reply]
In the frigate configuration, if you have 

```yaml
detect:
  width: 1920
  height: 1080
```

then it is already setup correctly

**Reply by drock1985** [reply]
Yup; looks like it is right. Here's to hoping the coral takes care of the rest then. 

```
mqtt:
  host: 192.168.1.56
  user: frigate
  password: password_goes_here

detectors:
  cpu1:
    type: cpu
    num_threads: 4

ffmpeg:
  hwaccel_args: -c:v h264_cuvid  #<-- nvidia acceleration
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p #<-- Intel

cameras:
  side_window: # <------ Name the camera
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://192.168.1.62:8554/driveway # <----- Update for your camera
          roles:
            - detect
            - rtmp
#            - record
            - clips
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
        required_zones:
          - awalt_road
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 4
          bear: 5
    zones:
      driveway:
        coordinates: 240,836,845,878,1361,845,1186,711,363,734
      awalt_road:
        coordinates: 0,703,484,613,576,639,0,821

  porch: # <------ Name the camera
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://192.168.1.62:8554/porch-cam # <----- Update for your camera
          roles:
            - detect
            - rtmp
#            - record
            - clips
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
#        - person
#        - bear
#        - bird
#        - dog
#        - knife
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 4
          bear: 5
  wyzepan: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.62:8554/wyze-pan # <----- Update for your camera
          roles:
            - detect
            - rtmp
#            - record
            - clips
      input_args:
        - -c:v
        - h264_cuvid
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 4
          bear: 5
  wyze: # <------ Name the camera
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://192.168.1.62:8554/back-yard-cam # <----- Update for your camera
          roles:
            - detect
            - rtmp
#            - record
            - clips
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    objects:
      track:
        - cat
        - person
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
        objects:
          person: 15
          bear: 5
```
