### DISCUSSION TITLE
Frigate H264 on (some) 8MP Reolink Cameras Working

### DISCUSSION THREAD

**Discussion by ChuckBuilds** [blakeblackshear/frigate#3594] [General]
Hello,

There's been a ton of posts all over the internet about getting Reolink 8MP cams to work in Frigate and I have personally seen many posts on github, reddit, forums saying to give up BUT with the excellent support from Reolink I was able to get my cameras working.

Posting this here for searches / google / maybe to help another person in the future. I am no means an expert but wanted to share my steps.

Considerations: I can only confirm this working on the RLC-810A and RLC-842A. I saw a post from 7 days ago on here that a D800 does not support the h264 at this time. I also edited all my settings on windows using the reolink application, I bet it would work on the mobile app but worth mentioning.

1. Ensure you are on the latest firmware, simply clicking update firmware in the application did not work for me. I emailed Reolink Support and the firmware they sent me did work.

    a. This is done manually in the Reolink App, under the camera's settings (gear Icon) > System > Maintenance > Browse to upload firmware

2. In the Reolink App, under the camera's settings (gear Icon) > Network Settings > Advanced > Port Settings > Setup> Ensure that RTSP or RTMP (depending on which you plan to use)  is ENABLED and take note of the port.

3. In the Reolink App, under the camera's settings (gear Icon) > Camera > Stream > Set your resolution lower. I opted for the lowest setting on my cameras (2304x1296) and left the FPS and Bitrate Alone.

4. Restart the Camera in the Reolink App, under the camera's settings (gear Icon) > System > Maintenance > Reboot

5. Open VLC > Media > Open Network Stream > enter your cameras connection info.

    a. FOR RTSP: Formatted as: rtsp://[LOGIN]:[PASSWORD]@[IPOFCAMERA]:[RTSP PORT FROM STEP2]/h265Preview_01_main

    b. Mine is rtsp://admin:[password]@192.168.86.231:554/h265Preview_01_main

    c. FOR RTMP: Formatted as: http://[IPOFCAMERA]/flv?port=[RTMP PORT FROM STEP2]&app=bcs&stream=channel0_main.bcs&user=[LOGIN]&password=[PASSWORD]

    d. Mine is http://192.168.86.25/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=[password]

6. Give it a second but your stream should show up in VLC

7. Right click the video feed > Tools> Codec Information or type Ctrl+J

8. You can verify that "Stream 0" codec is H264

    a. NOTE: At the bottom of this window you can see "location", the location still says h265Preview but the codec is h264. So if you are using a substream, it will be h264 and main stream is h265 BUT the video will be h264.

Below is my Frigate Camera Config for my RLC-842A, note my hwaccel_args are using nvidia drivers for the video stream. I don't really know what the input args do but I tried using the recommended ones on Reolinks website and it failed. I removed one at a time until it worked and this is what I was left with.

```
cameras:
  FrontPorch:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:[password]@192.168.86.231:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:[password]@192.168.86.231:554/h265Preview_01_main
          roles:
            - record
            - rtmp
```
EDIT 8/23/2022: I removed the Input args from the RTSP camera feed as apparently they are not necessary.

EDIT 8/31/2022 : I started having artifacting in the video stream. Solution is to switch to RTMP. Very Similar steps as above but with RTMP. Still need to change the resolution but be sure that the RTMP port is enabled in the Reolink Networking settings.

https://github.com/blakeblackshear/frigate/discussions/3746

If your RTMP doesn't work, check your password for special characters.

New Camera Config below:

```
cameras:
 FrontPorch:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args: preset-http-reolink
      inputs:
        - path: http://192.168.86.231/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=[password]
          roles:
            - record
            - rtmp
            - detect
  ```

Note: I am no longer using a substream as I wanted better accuracy for facial recognition. I believe the substream is just "channel1". Also please note the inclusion of input_args for RTMP. Please also note the removal of  "rtmp enabled: false"

I hope this helps! I am happy to try and field any questions but I am NOT an expert on this.

**Comment by finalbillybong** [comment]
Using your work as a base I managed to get this working through the NVR with 810-A cameras too.

 ```

 driveway:
    record:
      enabled: True
      events:
        retain:
          default: 10
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M       
      inputs:
        - path: rtsp://USERNAME:PASSWORD@192.168.0.222/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://USERNAME:PASSWORD@192.168.0.222/h264Preview_01_main
          roles:
            - record
            - rtmp


```

I needed to use h264 in the URL and not H265 as well as dropping '_cuvid' from the hwaccel_args. For each camera connetd to the NVR you want to use just use the next numbered stream, 02, 03, 04 etc

**Reply by NickM-27** [reply]
Those hardware accel args won't do any hwaccel, you can remove that section or check out https://docs.frigate.video/configuration/hardware_acceleration to get it setup

**Reply by finalbillybong** [reply]
Thanks. I have edited my comment with the correct args for my system

**Comment by ChuckBuilds** [comment]
Shout out to @NickM-27  for the help on this thread: https://github.com/blakeblackshear/frigate/discussions/3746

I am updating the above post to include the steps for RTMP as well.

**Comment by JonLaliberte** [comment]
Just wanted to comment here that this was the key for me (with a RLC-811A):
> In the Reolink App, under the camera's settings (gear Icon) > Camera > Stream > Set your resolution lower. I opted for the lowest setting on my cameras (2304x1296) and left the FPS and Bitrate Alone.

Before this, even opening the stream in VLC wasn't working. I was getting suspicious because the preview stream was working in Frigate, but clicking in to the live view wasn't working.

**Reply by Sabrimjd** [reply]
Using the 811WA, fixed the issue but now I have a narrower FOV, do you have the same behavior ?

**Comment by FlexxFR** [comment]
Thanks a lot, this is also working great for a RCL510WA. (firmware v3.1.0.764_21121712)
I'm using the RTMP variant.

However, I checked the all the streams via VLC and noticed that the sub stream (fluent) has always a fixed resolution of **896x672**  when using RTMP. (The setting in the Reolink app only affects the RTSP sub stream). Strange enough the settings for the main stream appear to be working for both RTMP and RTSP.

So I updated the detect config to: 

    detect:
      width: 896
      height: 672
      fps: 5

(Although it also worked with 640x480)

**Comment by simondsmason** [comment]
Reviving this very useful thread.  @Chmynard - I am about to start configuring for go2rtc.  I tried a few things but was not successful.  I wonder if anyone has some suggestions on this?  @finalbillybong.

I have 4x820a, 1x842a cameras.

**Reply by ChuckBuilds** [reply]
What’s not working? What have you tried? I’m rusty on this as I haven’t touched it since I’ve posted this. I’ll try to give it a run through tomorrow and see if something changed.

**Comment by BushTrocity** [comment]
I'm not sure what the cause is but i can sometimes connect to the stream in VLC and other times i can spend a whole day trying to get it to connect and the next day it will instantly connect like there was no issues yesterday. I'm using unraid with frigate as a docker. If i use rtsp://192.168.2.10:8554/Camera1?video=copy&audio=aac I get connection refused error and if i use rtsp://192.168.2.10:554/Camera1?video=copy&audio=aac I get 401 authentication error. Right now i can stream from the the go2rtc dashboard but it will not show video on the frigate home screen and it will not record with unable to read frames but i can clearly see the stream in go2rtc. 


```
mqtt:
  enabled: False
  
go2rtc:
  streams:
    Camera1: rtsp://admin:admin@192.168.1.10:554/h264Preview_01_main
    Camera1sub: rtsp://admin:admin!@192.168.1.10:554/h264Preview_01_sub
    
    
detectors:
  coral:
    type: edgetpu
    device: usb
    
objects:
  track:
    - person
    
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy

birdseye:
  enabled: True
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 4
  
cameras:
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/Camera1?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
           - record
        - path: rtsp://192.168.1.10:8554/Camera1sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: True
      retain:
        days: 5
    detect:
      enabled: True
      width: 3840
      height: 2160
      fps: 10
    motion:
      mask:
        - 0,880,997,546,1799,418,2395,411,3840,615,3840,0,1047,0,0,0
```

**Reply by simondsmason** [reply]
What model reolink?  Thanks

**Reply by BushTrocity** [reply]
I have 3 reolink 810A's

**Reply by BushTrocity** [reply]
The fix for my issue was to use the loopback IP 127.0.0.1 for the camera inputs instead of the lan ip

**Reply by ChuckBuilds** [reply]
Just spitballing here: are you on VLANs? Can frigate access the camera directly ? Just wondering if it’s a routing issue

**Reply by BushTrocity** [reply]
No vlans and yes. Frigate has direct access to them. Reolink will only allow 1 direct connection at a time. That is why I wanted the restreams so multi things can grab the stream like home assistant

**Comment by BushTrocity** [comment]
> What model reolink? Thanks



> What model reolink? Thanks

**Comment by simondsmason** [comment]
I did get this working with my cameras.  820s and an 842.  The only thing I can't get working with the restream is audio - either in the UI or in the record.  Configuration is below - any help appreciated.  Thanks.

```
mqtt:
  host: 192.168.2.110
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: ******
  stats_interval: 60
ffmpeg:
  hwaccel_args:
    -hwaccel_device
    -hwaccel_output_format yuv420p
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#  hwaccel_args: preset-intel-qsv-h264
#  hwaccel_args: preset-vaapi
#  hwaccel_args: -c:v h264_qsv
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#  hwaccel_args: preset-nvidia-h264
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 30
    mode: all
birdseye:
  enabled: True
  mode: continuous
  restream: True
#  width: 1920
#  height: 1080
#  quality: 4
go2rtc:
  streams:
    driveway:
      - rtsp://admin:******@192.168.2.234:554//h264Preview_01_main
    drivewaysub:
      - rtsp://admin:******@192.168.2.234:554//h264Preview_01_sub
    back_garden:
      - rtsp://admin:******@192.168.2.33:554//h264Preview_01_main
    back_gardensub:
      - rtsp://admin:******@192.168.2.33:554//h264Preview_01_sub
    front_door:
      - rtsp://admin:******@192.168.2.160:554//h264Preview_01_main
    front_doorsub:
      - rtsp://admin:******@192.168.2.160:554//h264Preview_01_sub
    porch:
      - rtsp://admin:******@192.168.2.161:554//h264Preview_01_main
    porchsub:
      - rtsp://admin:******@192.168.2.161:554//h264Preview_01_sub
    front_garden:
      - rtsp://admin:******@192.168.2.149:554//h264Preview_01_main
    front_gardensub:
      - rtsp://admin:******@192.168.2.149:554//h264Preview_01_sub
    kitchen:
      - rtsp://admin:******@192.168.2.227:554//h264Preview_01_main
    kitchensub:
      - rtsp://admin:******@192.168.2.227:554//h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.2.110:8555
      - stun:8555
cameras:
  driveway:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
#            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/drivewaysub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 0,720,441,720,632,283,806,179,795,106,950,105,981,217,1060,293,1280,415,1280,0,513,0,0,0
  back_garden:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
#            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/back_gardensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 441,707,437,671,11,676,11,710
    zones:
      back_step:
        coordinates: 979,720,1122,720,1086,564,1059,533,965,533
  front_door:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
#            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/front_doorsub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 14,676,437,672,439,704,16,703
    zones:
      front_step:
        coordinates: 0,361,244,225,664,720,253,720
  porch:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/porch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
#            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/porchsub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
       - 442,707,442,664,14,665,12,711
  front_garden:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
#            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/front_gardensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 12,705,439,703,437,666,11,671
        - 0,0,1280,0,1280,274,908,292,351,354,0,452  
  kitchen:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kitchensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    detect:
      enabled: true
    motion:
      mask:
        - 0,720,433,720,433,677,0,676
        - 856,123,1193,125,1222,505,1193,720,700,720,735,530,851,521,854,315,730,306,732,141
  garage:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://192.168.2.110:8556/garage_inside
          roles:
            - rtmp
            - detect
    detect:
      enabled: true
    birdseye:
      enabled: true
    motion:
      mask:
        - 771,720,1280,720,1280,669,769,668
  home_office:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://admin:******@192.168.2.217:554/live
          roles:
            - rtmp
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    birdseye:
      enabled: true
    motion:
      mask:
        - 918,718,1251,716,1253,664,915,669
  home_theater:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://admin:******@192.168.2.233:554/live
          roles:
            - rtmp
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    detect:
      enabled: false
    birdseye:
      enabled: False
    motion:
      mask:
        - 920,712,1255,712,1253,666,916,666
ui:
  live_mode: webrtc


```

**Reply by NickM-27** [reply]
You haven't enabled recording audio and you'll still need opus audio transcoding for WebRTC. 

Also recommend using preset-vaapi for hwaccel_args

**Reply by simondsmason** [reply]
ok, I changed to preset-vaapi.  As for getting audio to work - can you point me to docs that help in setting this up.  I have looked and not found what I need.  I am assuming it is fairly simple as all of my cameras use aac.  Thanks.

**Reply by NickM-27** [reply]
https://docs.frigate.video/troubleshooting/faqs#audio-in-recordings

**Reply by simondsmason** [reply]
It turns out that preset-record-generic-audio-copy and preset-record-generic-audio-aac both are working to record audio.  How do I get audio to play in the frigate ui when watching a live view of the camera?  I use WebRTC by default, and when I unmute this I hear nothing.  Thanks.

**Reply by NickM-27** [reply]
you need to add a secondary audio transcode for every camera

```
go2rtc:
  streams:
    driveway:
      - rtsp://admin:******@192.168.2.234:554//h264Preview_01_main
      - "ffmpeg:driveway#audio=opus"
```
