### DISCUSSION TITLE
Disable tracked object for a specific camera

### DISCUSSION THREAD

**Discussion by TheSleepySlee** [blakeblackshear/frigate#3600] [Ask A Question] [answered]
Hi

Been using Frigate for along time.
I have car & person as global config tracked objects.
I'm trying to disable car tracking for a specific camera. This sounds easy, but I'm not able to find how.
I see in the doc there are mention of objects in zones, but not sure how to apply to entire camera.

Thanks for your help

**Comment by NickM-27** [comment, marked as answer]
```yaml
cameras:
  your_camera:
    ffmpeg:
      ...
    objects:
      track:
        - person
```

**Reply by TheSleepySlee** [reply]
It would be good if this was added to this page: https://docs.frigate.video/configuration/cameras
Not sure how to do this myself... :)

**Reply by NickM-27** [reply]
Thanks, will look into updating the docs

**Comment by flyize** [comment]
If I want to remove an item for a specific camera from the global list, I just add it as a tracked object for the camera? Am I understanding that correctly?

**Reply by NickM-27** [reply]
just define the objects you do want to track on that camera

**Reply by flyize** [reply]
Ahhh, if I define it for the camera, it ignores the globals? Got it. I should have read the example in the OP better. Thank you.

**Comment by bucklevision** [comment]
I can't seem to get this to work, if I pull the objects: track: -car out of the general config and drop it into a camera specific section I get a config syntax error saying 
detectors -> filters
Discriminator 'type' is missing.

**Reply by selbstmacher** [reply]
same here, but it was a configuration issue:
the objects have to be under records:
```
    record:
      enabled: True
      events:
        pre_capture: 3
        post_capture: 2
        objects:
          - person
          - dog
          - cat

```
