### DISCUSSION TITLE
Working Reolink  config for 0.8 beta?

### DISCUSSION THREAD

**Discussion by walthowd** [blakeblackshear/frigate#369] [Ask A Question] [answered]
I've been having a terrible time trying to get my Reolink 520s happy on the 0.8 beta. If anyone has a working config, would you mine sharing? I'm trying to do clips and 24x7 record with the sub stream for detect and the main stream for everything else. 

Here is my camera config:

![Screenshot from 2020-12-11 17-25-27](https://user-images.githubusercontent.com/864569/101964112-e3bfc200-3bd5-11eb-962e-a1ef5e49a088.png)

I see these errors:

```
watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5593b11aa140] moov atom not found
/tmp/cache/backyard-20201211170947.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: backyard-20201211170947.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56158c702140] moov atom not found
/tmp/cache/backyard-20201211171139.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: backyard-20201211171139.mp4
watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b670729140] moov atom not found
/tmp/cache/backyard-20201211171619.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: backyard-20201211171619.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55eb5d740140] moov atom not found
/tmp/cache/backyard-20201211171818.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: backyard-20201211171818.mp4
watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" NOT IN (?, ?))', ['backporch', 'backyard'])
peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" = ?)', ['backporch'])
peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" = ?)', ['backyard'])
watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55938a62c140] moov atom not found
/tmp/cache/backyard-20201211172240.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: backyard-20201211172240.mp4
```

Here is my config:

```
cameras: 
  backporch: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.109/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XX"
          roles:
            - detect
        - path: "rtmp://192.168.1.109/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XX"
          roles:
            - clips
            - rtmp
            - record
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true 
    record:
      enabled: true 
      retain_days: 30
  backyard: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.42/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XX"
          roles:
            - detect
        - path: "rtmp://192.168.1.42/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XX"
          roles:
            - clips
            - rtmp
            - record
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true 
    record:
      enabled: true 
      retain_days: 30

detectors: 
  coral: 
    device: usb
    type: edgetpu

ffmpeg: 
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
  hwaccel_args: 
    - "-hwaccel"
    - vaapi
    - "-hwaccel_device"
    - /dev/dri/renderD128
    - "-hwaccel_output_format"
    - yuv420p


mqtt: 
  host: "192.168.1.124"
  password: XXX
  topic_prefix: frigate
  user: homeassistant

objects: 
  track: 
    - person

save_clips: 
  max_seconds: 300
  retain:
    default: 30

logger:
  default: debug 
  logs:
    frigate.mqtt: error
```

**Comment by cben0ist** [comment]
I've only had them working using the rtsp feed so far, not the rtmp.
<img width="538" alt="Screen Shot 2020-12-11 at 6 43 58 PM" src="https://user-images.githubusercontent.com/9885693/101964931-04d9e000-3be1-11eb-8f48-d0095f863a2d.png">

```
cameras:
  front:
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@10.1.60.14:554/h264Preview_01_sub'
          roles:
            - detect
        - path: 'rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@10.1.60.14:554/h264Preview_01_main'
          roles:
            - clips
            - rtmp
            - record
    height: 480
    width: 640
    fps: 5
    mask: poly,0,0,219,0,113,209,41,278,0,281
    record:
      enabled: True
      retain_days: 10
    rtmp:
      enabled: True
    save_clips:
      enabled: true
      pre_capture: 5
    objects:
      track:
        - person
    snapshots:
      show_timestamp: True
      draw_zones: False
      draw_bounding_boxes: True
      crop_to_region: True
      height: 175
```

**Reply by bm55** [reply]
I use the rtmp stream with following ffmpeg input flags which provides consistent fps compared to rtsp with reolink cameras:

input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'

**Comment by daveaus** [comment]
Here is my full setup using the RTMP stream on the hassio addon. It took quite a bit of messing around to get here but its doing an amazing job.

https://hastebin.com/dimedamoyi.less

**Comment by walthowd** [comment, marked as answer]
Thank you everyone for the kind comments.  I ended up getting everything work, with the exception of RTMP proxying. 

I had two issues

- RTMP proxy (role rtmp) on my main RTMP stream from the reolink would always bomb FFMPEG -- https://hastebin.com/abitafuqow.sql
- My `tmpfs` volume was 2GB and was too small for seven cameras, using sub and main streams, detect, clips and 24x7 record for all

What is interesting about the RTMP proxy, is that I could restart a camera after Frigate was running and the RTMP proxy would be fine. However if I then restarted frigate, it would keep restarting FFMPEG with the same errors (https://hastebin.com/abitafuqow.sql). The RTMP role *does work* fine on the sub stream (640x480)

The `tmpfs` filling up would only occur after I enabled four of more of the cameras -- the logs for it were only exposed after turning up ffmpeg logging

```
ffmpeg.backporch.clips_record  ERROR   : Conversion failed!
ffmpeg.backyard.clips_record   ERROR   : frame=  932 fps= 16 q=-1.0 q=-1.0 size=N/A time=00:01:01.86 bitrate=N/A speed=1.04x    
ffmpeg.backyard.clips_record   ERROR   : frame=  944 fps= 16 q=-1.0 q=-1.0 size=N/A time=00:01:02.30 bitrate=N/A speed=1.04x    
ffmpeg.backyard.clips_record   ERROR   : av_interleaved_write_frame(): No space left on device
ffmpeg.backyard.clips_record   ERROR   : [segment @ 0x5568c8869c00] Failure occurred when ending segment '/tmp/cache/backyard-20201216122622.mp4'
ffmpeg.backyard.clips_record   ERROR   : Error writing trailer of /tmp/cache/backyard-%Y%m%d%H%M%S.mp4: No space left on device
```

I increased the tmps mount to 8GB which should hopefully be enough -- I made not need it at all as the underlying disk is NVMe. 

Here is the Reolink camera encoding I used:
![Screenshot from 2020-12-16 13-24-06](https://user-images.githubusercontent.com/864569/102396404-08cf7e80-3fa2-11eb-835c-9257fcb60dd4.png)


Here is my final config:

```
cameras: 
  backporch: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.109/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - detect
        - path: "rtmp://192.168.1.109/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - clips
            - rtmp
            - record
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  backyard: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.42/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - detect
        - path: "rtmp://192.168.1.42/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - clips
            - record
            - rtmp
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  backyard-nw: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.247/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - detect
        - path: "rtmp://192.168.1.247/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - clips
            - record
            - rtmp
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  driveway: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.24/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - detect
        - path: "rtmp://192.168.1.24/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  garage: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.128/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - detect
        - path: "rtmp://192.168.1.128/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  sideyard: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.21/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - detect
        - path: "rtmp://192.168.1.21/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=XXXX"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  doorbell: 
    ffmpeg: 
      inputs:
        - path: "rtsp://admin:XXXX@192.168.1.48:554/h264/ch01/sub/av_stream"
          roles:
            - detect
        - path: "rtsp://admin:XXXX@192.168.1.48:554/h264/ch01/main/av_stream"
          roles:
            - clips
            - record
    fps: 10
    height: 512
    save_clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      track: 
        - person
        - car
        - truck
    width: 384

detectors: 
  coral: 
    device: usb
    type: edgetpu

ffmpeg: 
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
  hwaccel_args: 
    - "-hwaccel"
    - vaapi
    - "-hwaccel_device"
    - /dev/dri/renderD128
    - "-hwaccel_output_format"
    - yuv420p

mqtt: 
  host: "192.168.1.XXX"
  password: XXXX
  topic_prefix: frigate
  user: XXXX

objects: 
  track: 
    - person

save_clips: 
  max_seconds: 300
  retain:
    default: 30

logger:
  default: info 
  logs:
    frigate.mqtt: error
```
