### DISCUSSION TITLE
Working: Clips + Recordings on network share, database local

### DISCUSSION THREAD

**Discussion by Trashmee** [blakeblackshear/frigate#372] [Show and tell]
Hi,

I like to have clips + recordings on a dedicated disk on my NAS - I expect it to die early, so it shouldn't be on the same volume with my persistent container content (mariadb, ..), docker-compose files or even worse personal documents.

The following works for me - quite easy, but initially some permission problems kept it from working. I'm now able to get clips + recordings stored via NAS & replayed via media browser in HA.

```
docker-compose.yml
version: "2.4"

volumes:
  frigateclips:
    driver: nfs
    driver_opts:
      share: "<nasip>:<nfs_export_path_clips>"
  frigaterecordings:
    driver: nfs
    driver_opts:
      share: "<nasip>:/shares/frigate/recordings"

[...]

services:
  frigate:
    [..]
    volumes:
    [..]
      - frigateclips:/media/frigate/clips
      - /local_docker_vol/frigate/clips/frigate.db:/media/frigate/clips/frigate.db
      - frigaterecordings:/media/frigate/recordings
```
