### DISCUSSION TITLE
Hardware acceleration for RC1/RC2

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#3726] [Ask A Question] [answered]
Frigate has become laggy for me since I upgraded to RC1/RC2. I'm not sure what it's related to. Streams are choppy only updating every 30s or so. When I look in "debug" in the webui it shows me that the detector is "cpu". The release notes mention that there might be things that break with regards to hardware acceleration. 

I have a decent amount of cpu usage, although I am not sure what the baseline was:

![image](https://user-images.githubusercontent.com/118814/187086254-60f37d97-e599-4a5e-a8cc-577717cfac8f.png)

When I run nvidia-smi I get the following output:

![image](https://user-images.githubusercontent.com/118814/187086157-c1ba149c-7ef5-41e6-9c9b-b6bb79618d7a.png)

My docker-compose currently looks like this:

```
version: '3.0'
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-rc2
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/beast/frigate/config.yml:/config/config.yml:ro
      - /mnt/beast/frigate/data:/media/frigate
      - /home/nas/frigate/db:/db
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - FRIGATE_RTSP_PASSWORD=xxx
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
  
    # frigate nvidia acceleration
    deploy:  
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

And my frigate config looks lie:

```
ffmpeg:

  # nvidia acceleration
  hwaccel_args: -c:v h264_cuvid

  # enable audio
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    
detect:
  enabled: true
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 720
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 480
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 50

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 3840
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 3
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  
record:
  enabled: true
  events:
      retain:
        # Required: Default retention days (default: shown below)
        default: 60
        
snapshots:
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: true

rtmp:
  enabled: true
  
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://un:pw@lan.network.com:554/11
          roles:
            - record
        - path: rtsp://un:pw@lan.network.com:554/12
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 352
    ui:
      order: 1
      
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://un:pw@lan.network.com:554/stream0
          roles:
            - record
        - path: rtsp://un:pw@lan.network.com:554/stream1
          roles:
            - detect
            - rtmp
    ui:
      order: 2 
      
  ...
```

Any ideas?

**Comment by NickM-27** [comment]
There seems to be a bit of confusion here. The detector is your object detector, options being cpu or coral so based on your setup that is expected. 

Can you elaborate more on what is laggy and also what your other performance metrics are (RAM, CPU, etc)

**Reply by thinkloop** [reply]
I updated the question with a couple of screenshots including "top" for cpu/mem usage and nvidia-smi.

Basically the streams in birdseye are delayed by a few minutes, and/or freeze completely then update after 30s+, then everything catches up, only to begin being delayed again.

**Reply by NickM-27** [reply]
Does this happen with the single camera live view?

**Reply by thinkloop** [reply]
Just tested, yes, in single camera live, or debug, the stream only updates every 15s or so.

**Reply by thinkloop** [reply]
Looking a bit more today, the problem does seem to be birdseye related, the single camera view is working better, and even yesterday it was in the 15s range rather than a lag of 1-2 minutes. Something else I noticed is that the lag is much less in a browser on my laptop than it is on my Fire tablet. In fact the laptop almost works ok - still not as good as before but survivable, whereas the tablet is minutes delayed and very choppy. Do you think the new videojs could be the culprit consuming more resources?

**Reply by NickM-27** [reply]
> Looking a bit more today, the problem does seem to be birdseye related, the single camera view is working better, and even yesterday it was in the 15s range rather than a lag of 1-2 minutes. Something else I noticed is that the lag is much less in a browser on my laptop than it is on my Fire tablet. In fact the laptop almost works ok - still not as good as before but survivable, whereas the tablet is minutes delayed and very choppy. Do you think the new videojs could be the culprit consuming more resources?

That is interesting for sure, definitely something related to the client. videojs is only used for event and recording playback. 

You can see in https://github.com/blakeblackshear/frigate/blob/release-0.11.0/web/src/routes/Birdseye.jsx#L10 that birdseye uses JSMPEG player which I don't believe has had any changes.

To be clear, you're saying the laptop viewing the stream is behind but not choppy, meanwhile the fire tablet stream view is further behind as well as being choppy?

**Reply by thinkloop** [reply]
> To be clear, you're saying the laptop viewing the stream is behind but not choppy, meanwhile the fire tablet stream view is further behind as well as being choppy?

Both are delayed and choppy, but the Fire tablet took a major nose dive with multi-minute lags and variable choppiness, running smooth for a few seconds, then freezing for ~30s, then back to smooth for a couple of seconds, then back to freezing (on a 2 minute old stream). The laptop is only marginally worse but still very usable, but I can sense it is struggling more than before with greater variability in performance.

**Reply by NickM-27** [reply]
That is interesting. Have you tried it without hwaccel? Would be curious if this affects the behavior at all

**Reply by thinkloop** [reply]
Actually I did, and there wasn't much difference. When I first enabled it a month or two ago, I did notice a positive effect. To be sure, to disable hwaccel I commented out this part in docker-compose:

![image](https://user-images.githubusercontent.com/118814/187218432-f53a04b4-1ccd-4c52-b022-bd3ac17ead3c.png)

and this part in config.yml:

```
  #hwaccel_args: -c:v h264_cuvid
```

**Reply by thinkloop** [reply]
I also have this in config.yml for audio:

```
  # enable audio
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```

**Reply by NickM-27** [reply]
I would say that's a positive at least, nice that it isn't hwaccel.

Could potentially be ffmpeg but I'll have to see what other changes were made that could affect this.

**Reply by thinkloop** [reply]
And I have a constant stream of these errors in the docker logs:

![image](https://user-images.githubusercontent.com/118814/187219149-46223a2b-43bf-404e-a577-8dbd5e107a12.png)

**Reply by NickM-27** [reply]
Oh, that's probably a big part of it then. For the cameras with flv errors, I would recommend trying to disable RTMP and see if that helps. 

For the cameras with audio issues, not sure there's much that can be done with the camera itself. Maybe try CBR instead of VBR or maybe you could potentially try using rtsp-simple-server as a proxy

**Reply by thinkloop** [reply]
I will try that and report back. Was something changed recently related to those things?

**Reply by NickM-27** [reply]
> I will try that and report back. Was something changed recently related to those things?

Not sure which part you're referring to?

**Reply by thinkloop** [reply]
I guess to either recommendation: disable rtmp, check audio. I'm coming from a perfectly working system that has degraded recently so just wondering if you know of something related to those that has been changed recently.

Btw I haven't had any audio issues, does something in the log point to that? Is this not the correct way to enable audio:

```
  # enable audio
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```

For one of the cameras that has errors in the logs it doesn't seem like I can disable rtmp:

![image](https://user-images.githubusercontent.com/118814/187223645-dda23a31-a602-4d04-ac9e-2956538c754c.png)

For the other camera with errors rtmp is already disabled:

![image](https://user-images.githubusercontent.com/118814/187223769-212f549d-1e34-444b-a657-802d6c00841c.png)

And while we're here these are some other settings:

![image](https://user-images.githubusercontent.com/118814/187224037-39febd58-0f62-4f18-9d61-138d38a57f8e.png)

Can the existence of rtmp cause issues?

**Reply by NickM-27** [reply]
We changed ffmpeg build and version, but I am just reacting to the logs. 

You did enable audio correctly as the docs recommend. 

Also "disable RTMP" means in the frigate config, not on the camera itself

```yaml
cameras:
  your_camera:
    rtmp:
      enabled: false
```

**Reply by NickM-27** [reply]
Also the aac logs are just complaining that the Timestamps are incorrect for the audio. ffmpeg tries to fix it so likely won't see issues but I believe that does take more processing (not necessarily sure how much it would affect in this case)

**Reply by NickM-27** [reply]
After thinking about this some more, I am pretty sure it isn't actually "load" issue and more like the camera streams seem delayed / choppy because they are coming in and out with the ffmpeg crashing due to `rtmp` crashing. I would definitely recommend disablign the rtmp relay for all cameras just to see if it makes a difference.

at the top level:
```yaml
rtmp:
  enabled: false
```

**Reply by thinkloop** [reply]
I disabled rtmp for all cameras like this:

```
rtmp:
  enabled: false

cameras:     
  driveway-maison:
    ffmpeg:
      inputs:
        - path: rtsp://un:pw@lan.network.com:554/stream0
          roles:
            - record
        - path: rtsp://un:pw@lan.network.com:554/stream1
          roles:
            - detect
#            - rtmp
```

And I completely removed one of the cameras that was causing errors. I no longer have any errors showing in the docker logs but performance/lag is still the same/bad. The detection seems to have degraded as well, the camera in front of me that I wave my arms at for testing is not triggering as consistently as before. Odd.

Anything else you would like me to try?
