### DISCUSSION TITLE
How does HA and notifications work?

### DISCUSSION THREAD

**Discussion by biggen1684** [blakeblackshear/frigate#377] [Ask A Question]
I'm new to HA. Only had it running for a couple days.  I know there are instructions [here](https://github.com/blakeblackshear/frigate/tree/release-0.8.0#integration-with-homeassistant) but I'm a bit confused on where that stuff goes.  Yes, I have installed HA Integration.  Doing some reading it appears I need to create a `configuration.yaml` on HA itself.  Is this correct?  I've tried to go Configuration -> Automation -> Add Automation but am a bit confused on how to set it up from here.

So I installed the File Editor add-on for HA and created a `configuration.yaml` file from there.  If I just wanted a simple notification to my phone when motion is detected and have it send me the snapshot, what is a working config?  I've tried something like:

```automation:
  - alias: Backyard Motion
    trigger:
      platform: mqtt
      topic: frigate/backyard/person/snapshot
    action:
      - service notify.mobile_app_sm_g950u
      data:
        message: "Backyard Motion
```

But this doesn't work and I'm not surprised as I don't really know what I'm doing.  Any just real simple notification with snapshots examples I could base mine off of??

**Comment by blakeblackshear** [comment]
See some examples from the beta version docs [here](https://github.com/blakeblackshear/frigate/tree/release-0.8.0#notifications) and [here](https://github.com/blakeblackshear/frigate/blob/release-0.8.0/docs/notification-examples.md). Once you add automations to your HA config, you will need to reload or restart HA. Then you will see the automations you added in the UI at Configuration > Automations.

**Comment by biggen1684** [comment]
I guess there isn't a simple way just to setup _When person is detected -> notify phone_?  Is it really as complicated as having to write a .yml file?

Those configurations seem so complicated with zones.  I just need a notification of motion when it picks up the object that is 'person'.  Something a simple as:
````
automation:
  - alias: Backyard Motion
    trigger:
      platform: mqtt
      topic: frigate/backyard/person/snapshot
    action:
      - service notify.mobile_app_sm_g950u
        data_template:
          message: "Backyard Motion"
````

**Comment by blakeblackshear** [comment]
It is built for flexibility. Most users of HomeAssistant want to incorporate their own specific conditions such as only notifying at night, or when they are not home, or when their alarm is armed, etc. Here is the simplest automation for notifications of a person:

```yaml
automation:
  - alias: Notify of events
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    action:
      - service: notify.mobile_app_sm_g950u
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
          data:
            tag: '{{trigger.payload_json["after"]["id"]}}'
```

Since you are new to HA, did you setup HomeAssistant Cloud? Or are you using something else for access when you are not home? In order for your images to show in the notification, your phone will need to be able to pull the image when you are not home. You will need to replace `your.public.hass.address.com` with whatever you setup below to get images in the notifications.

```yaml
automation:
  - alias: Notify of events
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    action:
      - service: notify.mobile_app_sm_g950u
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
          data:
            image: 'https://your.public.hass.address.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}.jpg?format=android'
            tag: '{{trigger.payload_json["after"]["id"]}}'
```

**Reply by Trashmee** [reply]
Hi,

I'm trying to get Telegram notifications on person detection, thought it should be pretty straight forward with the useful samples you provided.. There is not public access to HA, but I understand telegram does a push, so not a requirement. Anyhow, I'm in the WLAN for now, so the phone would be able to get there.

Automation - works, however the image link as in your example doesn't work for me and I'm not sure where to debug.
(Need to implement a cool down :-) 
```
  - alias: 'Frigate Telegram'
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    action:
      - service: notify.telegram_edelfull
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} with ID {{trigger.payload_json["after"]["id"]}} was detected.'
          data:
            image: 'https://192.168.177.136/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}.jpg?format=android'
            tag: '{{trigger.payload_json["after"]["id"]}}'
```


Calling the URL with the eventid I see via mqtt doesn't work:
```
curl https://192.168.177.136/api/frigate/notifications/keller-1607861215.204048-8n7efc.jpg?format=android --insecure; echo
Event not found
```
```
{"before": {"id": "1607861215.204048-8n7efc", "camera": "keller", "frame_time": 1607861220.209122, "label": "person", "top_score": 0.87890625, "false_positive": false, "start_time": 1607861215.204048, "end_time": null, "score": 0.73046875, "box": [598, 0, 1651, 1072], "area": 1128816, "region": [598, 0, 1678, 1080], "current_zones": [], "entered_zones": [], "thumbnail": null}, "after": {"id": "1607861215.204048-8n7efc", "camera": "keller", "frame_time": 1607861221.011756, "label": "person", "top_score": 0.87890625, "false_positive": false, "start_time": 1607861215.204048, "end_time": 1607861223.212672, "score": 0.58203125, "box": [878, -17, 1764, 1064], "area": 957766, "region": [692, 0, 1772, 1080], "current_zones": [], "entered_zones": [],
"thumbnail": null}}
```

**Reply by blakeblackshear** [reply]
For telegram, get the image directly from frigate at `http://<frigate_ip>:5000/events/keller-1607861215.204048-8n7efc/snapshot.jpg`. You don't need the API.

**Reply by Trashmee** [reply]
Thanks, working now.

```
- automation
  - alias: 'Frigate Telegram'
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - "{{ states('input_boolean.isalarmon') == 'on' }}"
    action:
      - service: notify.telegram_full
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} with ID {{trigger.payload_json["after"]["id"]}} was detected at {{ trigger.payload_json["after"]["camera"] }} {{ "\n" -}} found at: http://192.168.177.177:5000/{{ trigger.payload_json["after"]["camera"] }}-{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?h=720 '
          data:
            photo:
              - url: 'http://192.168.177.177:5000/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?format=android'
                caption : 'A {{trigger.payload_json["after"]["label"]}} was detected at {{ trigger.payload_json["after"]["camera"] }} '
              #- url: 'http://192.168.177.177:5000/{{trigger.payload_json["after"]["camera"]}}/latest.jpg?h=720'
```

**Reply by biggen1684** [reply]
So even if I maintain a VPN connection back to my home, I still need the HA cloud service?

**Reply by biggen1684** [reply]
@blakeblackshear 

Edit: It works!  The issue with `conditions` vs `condition`.  In the below code block you have to drop the "s".  It must be `condition`.
----

I'm still struggling with HA. Good lord I hate yaml.

So where does the below go?  In the `configuration.yaml` file, right?
```
   automation:
  - alias: Notify of events
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    action:
      - service: notify.mobile_app_sm_g950u
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
          data:
            tag: '{{trigger.payload_json["after"]["id"]}
```

My `configuration.yaml` has this line in it `automation: !include automations.yaml`.  So if I go to the `automations.yaml` file and add the above I get an error with HA.  Is it best to not use the `automations.yaml` file and just put everything in the `configuration.yaml`?

If I comment out the `automation: !include automations.yaml` from the `configuration.yaml` and paste the above code block that you included inside the actual `configuration.yaml` I get an error upon restarting HA:

`Invalid config for [automation]: [conditions] is an invalid option for [automation]. Check: automation->conditions. `

Man oh man. I appreciate you taking the time here to help me.  I feel like I gotta be close to having automations sent.
