### DISCUSSION TITLE
Disable event recording for specific objects

### DISCUSSION THREAD

**Discussion by tpjanssen** [blakeblackshear/frigate#3787] [Ideas]
What I would like is an option to disable event recording for specific objects through MQTT and/or HA. Now I have lots of false positives when I'm watering my garden during the night. Frigate detects lots of birds during that period, and of course I'm not interested in seeing these recordings. Another use case can be to count the number of cars parked in a specific zone, but do not record them.

Are there more people that would like to see this option? In can imagine there are a lot of more use cases for this function.

**Comment by MYanello** [comment]
Did you ever figure this out? I think maybe something like this to tell it what object to track should help with the birds:
```  
Front_Left_Cam:
    zones:
      front_yard:
        coordinates: 460,720,136,720,239,495,287,386,806,384,749,447,667,506,608,556,579,615,575,720
        objects:
          - person
```
Haven't confirmed this behavior but it may be worth a shot
