### DISCUSSION TITLE
Validation Error in config.yml

### DISCUSSION THREAD

**Discussion by barans99** [blakeblackshear/frigate#3811] [Ask A Question] [answered]
Hi all,

Please be patient with me as I'm very new to the world of HA/Frigate.

my config is:

```yaml
 mqtt:
  host: 192.168.1.167
  port: 1883
  user: "mqtt-user"
  password: "xxx"
 cameras:
   floorone:
     ffmpeg:
       inputs:
         - path: rtsp://admin:xxx@192.168.1.87
           roles:
             - detect
     detect:
       width: 1280
       height: 720
       fps: 5
       objects:
          - person
          - dog
 detectors:
   cpu1:
     type: cpu
   cpu2:
     type: cpu
   cpu3:
     type: cpu
   cpu4:
     type: cpu
```

the error in the log i'm seeing is:

1 validation error for FrigateConfig
cameras -> floorone -> detect -> objects
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> floorone -> detect -> objects
  extra fields not permitted (type=value_error.extra)

Any help and preferably an explanation where I've been a donut would be appreciated.

Ty in advance!
