### DISCUSSION TITLE
Error in 'Clips'

### DISCUSSION THREAD

**Discussion by barans99** [blakeblackshear/frigate#3815] [Ask A Question] [answered]
Hi,

Could anyone explain what I've done wrong here? Error is as follows:

Any explanation would be kindly appreciated as I'm pulling my hair out. I have had a look at the frigate documentation but I can't see much mentioning clips.

"1 validation error for FrigateConfig
clips
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
clips
  extra fields not permitted (type=value_error.extra)"

```
mqtt:
 host: 192.168.1.167
 port: 1883
 user: "mqtt-user"
 password: "xxx"
cameras:
  floorone:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.1.87
          roles:
            - detect
            - clips
    detect:
      width: 1280
      height: 720
      fps: 5
objects:
  track:
         - person
         - dog
snapshots:
  enabled: True
  timestamp: false
  bounding_box: true
  retain:
    default: 3
clips:
  enabled: True
  retain:
    default: 2
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```
