### DISCUSSION TITLE
Adding multiple USB corals

### DISCUSSION THREAD

**Discussion by Cliomjh1022020** [blakeblackshear/frigate#3817] [Ask A Question]
Hello, I’m trying to add two USB corals for frigate. I have tried but failed.

```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
```

My HA recognises the two corals, but I’m unsure how to configure my frigate.yml file to point it to the corals…..here’s how HA sees one of the corals 
![D2DFA598-1625-48C4-B1D8-D4EB3E2707D8](https://user-images.githubusercontent.com/72868928/189540257-873ba8e6-8859-4824-bc5c-5a81a2b3205a.png)

any help how to rectify this issue is much appreciated.

**Comment by NickM-27** [comment]
/002 is just one coral in the second slot of the second bus. 

What does the other USB coral look like?

**Reply by Cliomjh1022020** [reply]
![3539C72F-AB08-4288-A74D-21357A26118E](https://user-images.githubusercontent.com/72868928/189709792-bf153ead-985e-4b8d-b75f-fe3823f9de22.png)

**Reply by NickM-27** [reply]
What you put in the config above is correct, have you tried it and it didn't work? If so, what is the error message?

**Comment by moandcompany** [comment]
Assuming your host operating system can see both Coral USB devices, and the usb bus devices are exposed to the Frigate container, you should be able to specify the following in your Frigate `config.yml` configuration file:

```
detectors:
  coral_1:
    type: edgetpu
    device: usb:0
  coral_2:
    type: edgetpu
    device: usb:1
```
