### DISCUSSION TITLE
Where is the video clip stored?

### DISCUSSION THREAD

**Discussion by thematrixdev** [blakeblackshear/frigate#3824] [General]
According to the documentation, video is stored in "recordings" and image is stored in "clips".
I want the trimmed video (with detection) file to be sent by Telegram as a file.

Thanks.

**Comment by NickM-27** [comment]
If you want the video of an event then you should use the API https://docs.frigate.video/integrations/api#get-apieventsidclipmp4

**Reply by thematrixdev** [reply]
Currently I am using this approach. I have integrated Frigate with Home-Assistant. The video I have received in Telegram seems to be imcomplete. The one in Frigate is 1x seconds, while the one I have got in Telgram is several seconds.

The flow is, when MQTT frigate/events is received, HA gets the video with the API, and send via Telegram as a URL. Is it possible when the MQTT event is made, the file has not be full saved to disk?

Is there any way I can get the file physically, withoug going through network? Is it being generated dynamically when the API is called?

**Reply by NickM-27** [reply]
Yes it is entirely possible that if you get the clip immediately it has not been generated yet or some of the segments are still in the cache. 

The file does not exist physically, it is generated dynamically with the relevant segments

**Reply by thematrixdev** [reply]
I see. I think it would be nice of the MQTT message is published after the video is fully created.
Maybe I should hardcode waiting 1 minute after the MQTT message is received.
Thanks.

**Reply by NickM-27** [reply]
The MQTT events topic is verbose so it sends many messages and right as they happen and they're filterable. In my experience the clip is available at the `end` message or 10 seconds after it.

**Reply by thematrixdev** [reply]
This is the HA Automation I am using. I am waiting for the next run to see the result.
```
- id: 'dummyid'
  alias: Frigate Telegram Notification
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
    payload: atom-entrance
    value_template: '{{ value_json[''after''][''camera''] }}'
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''type''] != ''end'' }}'
  action:
  - service: telegram_bot.send_photo
    data:
      target: mytelegramchatid
      url: https://myid.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/snapshot.jpg
  - repeat:
      sequence:
      - wait_for_trigger:
        - platform: mqtt
          topic: frigate/events
          payload: '{{ trigger.payload_json[''after''][''id''] }}'
          value_template: '{{ value_json[''after''][''id''] }}'
        timeout: 180
        continue_on_timeout: false
      - condition: template
        value_template: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: telegram_bot.send_video
        data:
          target: mytelegramchatid
          url: https://myid.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/atom-entrance/clip.mp4
      until:
      - condition: template
        value_template: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
  mode: single
```
