### DISCUSSION TITLE
Cats and cars detected as person

### DISCUSSION THREAD

**Discussion by ppruneau** [blakeblackshear/frigate#3828] [Ask A Question]
Hi,

pretty sure it's a "code 18" kind of problem, but I can't manage to find the issue.

As the title of the suggestion says, Frigate detect "everything" as person, for example :
![image](https://user-images.githubusercontent.com/796493/189701336-9f7619ef-d602-4088-b1da-528a3c65b031.png)

I already tried messing with threshold and min_score for the "person" filter as suggested in another discussion without success.

Here is my configuration (at least the "interesting" part of it) : 
```
objects:
  filters:
    person:
      min_score: 0.5
      threshold: 0.78

#Cameras configuration
cameras:
  veezoom:
    ffmpeg:
      inputs:
        - path: rtsp://hidden:hidden@192.168.10.92
          roles:
            - detect
            - clip
    record:
       enabled: True
      events:
        retain:
          default: 14
        required_zones:
          - stationnement
        objects:
          - person
          - car
          - cat
    snapshots:
      enabled: True
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 1920,0,704,0,867,415,1920,704
        - 0,1080,0,0,797,0,1031,462,423,458,337,576,398,1080
    zones:
      stationnement:
        coordinates: 930,525,579,608,530,543,472,946,638,1080,1920,1080,1920,722
```

Thanks in advance for your help!

**Comment by NickM-27** [comment]
I would recommend `min_area` for person as no person would be that small. 

The model used in frigate is a demo model from google and it's heavily biased towards person. This is why https://frigate.video/plus exists

**Reply by ppruneau** [reply]
Sorry, got some stuff to take car in the last days....

Thanks for your answer, and will certainly look into frigate plus someday.

But for now I'll try the min_area and see the result. And for the fact that frigate doesn't detect my car at all, would i have to set a max_area to person or something like that?

Thanks!

**Reply by NickM-27** [reply]
I just realized your problem, you never defined objects to track. You have to add that or the events part does nothing. 

```yaml
objects:
  track:
    - person
    - car
    - cat
```

That would also explain why you were getting the other issue too.
