### DISCUSSION TITLE
Low res video in live camera view

### DISCUSSION THREAD

**Discussion by rugene76** [blakeblackshear/frigate#3834] [General]
Perhaps I'm missing something obvious, but I am not getting the high res video (2560x1920) in the live camera display for frigate. I'm using Reolink rlc-510wa cameras. Elsewhere, i.e., the home assistant feed using the lovelace card does provide the expected high res image. Captured video is also at the expected image quality.

Is this a reolink problem or is there some setting that needs to be adjusted in the frigate.yaml to get the high res live camera video?

I also use wyse cameras with the rtsp firmware and they work fine.

I'm running the latest frigate release as an addon to HA in a dedicated intel PC

Any ideas?

**Comment by NickM-27** [comment]
The live frigate view comes from the detect stream, so whatever you have as your detect stream is what will be displayed in the Frigate live UI

**Comment by rugene76** [comment]
thanks, that's good to know about the detect stream, but after changing the detect streams to rtsp://admin:xxxxxx@10.0.0.xx:554/h264Preview_01_main and adjusting the detect width and height, I'm still getting a low res live stream. The snapshots and captures are at the high resolution however. I tried the rtsp feed using VLC and there I do get the high res video as expected.

here's a snippet of my yaml:
  reolink:
    ffmpeg:
      hwaccel_args:
       - -hwaccel
       - vaapi
       - -hwaccel_device
       - /dev/dri/renderD128
       - -hwaccel_output_format
       - yuv420p
      output_args:
         record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:xxxxx@10.0.0.xx:554/h264Preview_01_main
    detect:
      width: 2560
      height: 1920
      fps: 10

**Reply by NickM-27** [reply]
You'd also need to update your live config

```yaml
# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
```
