### DISCUSSION TITLE
hardware acceleration doubles CPU usage

### DISCUSSION THREAD

**Discussion by paularmstrong** [blakeblackshear/frigate#392] [General]
Using an Intel 10th gen CPU

I have set `LIBVA_DRIVER_NAME=iHD`. Using the following config:

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
```

> NOTE: Previously, I was receiving all green output from the cameras. The instructions in the README neglected to remind me that I need to mount `/dev/dri/renderD128` into the container. Once I did that, the camera feeds came through clearly. Happy to take a stab at updating the README soon

When running with the ffmpeg hwaccel, I get about 160% CPU usage. Without it I'm at about 80%. Is anyone else experiencing similar or were able to drop the CPU usage down?

**Comment by tubalainen** [comment]
Does the endpoint exists on the docker server/machine?
Check it by typing: `ls -alh /dev/dri/render*`

Do you run your linux installation with docker directly on the machine at hand or do you use a virtual env?

**Reply by paularmstrong** [reply]
Yep, the endpoint exists `crw-rw-rw- 1 root 1008 226, 128 Dec 17 15:22 /dev/dri/renderD128`

I'm running it through portainer, no virtualenv.

**Comment by paularmstrong** [comment]
Looks like a recent change recommends using `qsv` instead of `vaapi` in this gen processor and it _looks_ like it's helping a bit!

Here's what I'm using now:

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
```
