### DISCUSSION TITLE
Anyway to send just one notification via HA within X amount of time of detection

### DISCUSSION THREAD

**Discussion by biggen1684** [blakeblackshear/frigate#393] [General]
So I know that using something like the below code block you have for an example will only trigger HA notifications for camera `front` with object of `dog` with a score of greater than `98%`:

```- alias: Notify for dogs in the front with a high top score
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'dog' }}"
      - "{{ trigger.payload_json['after']['camera'] == 'front' }}"
      - "{{ trigger.payload_json['after']['top_score'] > 0.98 }}"
    action:
      - service: notify.mobile_app_pixel_3
        data_template:
          message: 'High confidence dog detection.'
          data:
            image: "https://url.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}.jpg"
            tag: "{{trigger.payload_json['after']['id']}}"
```

However, if frigate finds another frame with a higher accuracy rating it will still push another notification.  Is there anyway to write that HA automation so that only one image (during X time duration) is pushed that meets the `conditions` criteria?

I'd like to adjust to 90% accuracy but have it only send me one notification in a 45 second time span.  For me, having a 45 second sleep timer between notification means I'm not getting the same notification over and over again that are seconds apart.

**Comment by Ysbrand** [comment]
I had a simar case when I encountered multiple trigger event. solved in the following manner:

```
- alias: "when a person enters oprit"
  trigger:
    platform: mqtt
    topic: frigate/events
  condition: 
    - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    - "{{ 'oprit' in trigger.payload_json['after']['entered_zones'] }}"
    - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.when_a_person_enters_oprit', 'last_triggered')) |int(0) ) > 60 }}"
  action:
    - service: notify.telegram_YJ
      data:
        message: "A {{trigger.payload_json['after']['label']}} has entered the oprit."
        data:
          photo:
            - url: "https://hass.domain.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}.jpg?format=android"
              caption: "A {{trigger.payload_json['after']['label']}} has entered the oprit."
```
