### DISCUSSION TITLE
0.11.0 occupancy detection slower then 0.10?

### DISCUSSION THREAD

**Discussion by hagak** [blakeblackshear/frigate#3958] [Ask A Question]
So one of my main use-cases for Frigate is to turn lights on when I walk into a room.  Previously with v.0.10 it was fast enough for this function.  My office camera would trigger the lights well before I reached my desk, however after upgrading to v.0.11 it is noticeable slower to the point where I get to the desk and sit down before it triggers.

Note I have not made any changes to my system other then updating frigate.

Systems has 14 cameras and 4 mini-pci coral devices running on docker and triggers are handled through Home Assistant.  I did disable ALL of the frigate motion sensors in HA to try and reduce the load on it.

Any ideas?

**Comment by NickM-27** [comment]
It's probably bad hardware acceleration causing latency, but without seeing your config and an example there's no way to know. You should watch the debug view and see how far behind it is. 

To be clear, we had no changes in the detection or model so there's nothing on that side that would have increased things.

**Comment by hagak** [comment]
```
office:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtmp://XXXXXX:1935/bcs/channel0_sub.bcs?channel=0&stream=0
          roles:
            - detect
        - path: rtmp://XXXXXX:1935/bcs/channel0_main.bcs?channel=0&stream=0
          roles:
            - rtmp
            - record
`
`
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
    
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -use_wallclock_as_timestamps 1
    
  # Optional: global output args (default: shown below)
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    # Optional: output args for clips streams (default: shown below)
    #clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -f flv -c:v copy -c:a aac
```

**Reply by hagak** [reply]
Note from the DEBUG window it is almost 5 seconds behind.

**Reply by NickM-27** [reply]
We have new reolink args so recommend changing to those https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others

Also looks like you're not using hwaccel, hwaccel is always recommended

**Reply by NickM-27** [reply]
> Note from the DEBUG window it is almost 5 seconds behind.

Yeah, try those new args first.

**Reply by hagak** [reply]
yeah not sure what HWACCEL i can use since this is running on a machine with a pair of E5-2695v2 and just basic server board video (no offboard video card).

**Reply by hagak** [reply]
Interesting the use of http link for the reolink, have not tried that.  Will give those settings a shot.

**Reply by hagak** [reply]
Probably should add a video card to this machine to do HWACCEL

**Reply by NickM-27** [reply]
That's what I use with reolink cam and it is basically instant.

**Reply by hagak** [reply]
So that shaved about a second off of the lagg.  I still need to make the changes to the other cameras which could help.

On your system do you have HWACCEL?  If so what are you using, thinking of getting a board just wondering what would be the best bang for the buck that also is half-height capable.

**Reply by NickM-27** [reply]
I used to use my integrated AMD graphics on my 5700G. I still use it for my 1080p cameras that I don't care about latency, but it didn't help much with that. 

I now use an nvidia 3050 and it greatly reduced the latency to be almost instant on both my 5 MP cameras.

**Reply by hagak** [reply]
Not a whole lot of options for low-profile graphics cards.  However the Quadro P600 with 4GB RAM might help, seems to be somewhat popular for Plex transcoding.

**Reply by hagak** [reply]
So I added a T1000 nvidia card, setup my docker container to use it and I get the output of nvidia-smi in the container but no processes listed.  I have hwacel_args: -c:v h264_cuvid

Am I missing something?
`
docker exec -it frigate nvidia-smi
Tue Oct  4 16:03:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1000        Off  | 00000000:03:00.0 Off |                  N/A |
| 35%   52C    P0    N/A /  50W |   1359MiB /  4096MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
`

**Reply by NickM-27** [reply]
Try running nvidia-smi on your host, running in the container sometimes removes some of the data

**Reply by NickM-27** [reply]
The % shows it's running so should be good

**Reply by hagak** [reply]
Yep ran it on the host and have a number of processes listed.  Hmm detection and debug is still lagging by about 3-4 seconds

**Reply by hagak** [reply]
I am getting a bunch of these in my logs:
[2022-10-04 16:03:06] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
[2022-10-04 16:03:06] frigate.record                 ERROR   : could not convert string to float: ''

Maybe a cause?

**Reply by NickM-27** [reply]
> I am getting a bunch of these in my logs:
> 
> [2022-10-04 16:03:06] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
> 
> [2022-10-04 16:03:06] frigate.record                 ERROR   : could not convert string to float: ''
> 
> 
> 
> Maybe a cause?

Did you restart recently? That's just a weird bug with ffprobe and corrupt video segments so it's unrelated. 

I'm not sure how to debug where the latency is coming from. Can you update with your current frigate config?

**Reply by hagak** [reply]
I did restart after installing the nvidia drivers

Seems like putting in my config.yml even inside the code tags makes a mess.  I suspect it is the "#" in the yml.  Suggesstions?

**Reply by NickM-27** [reply]
You're not putting it in right, either put it in and I can edit to fix or be sure you're putting \``` on its own line

**Reply by hagak** [reply]
Removed all but one camera to keep it brief.

```
# Optional: port for http server (default: shown below)
#web_port: 5000
database:
  path: /media/frigate/data/frigate.db
# Optional: detectors configuration
# USB Coral devices will be auto detected with CPU fallback
detectors:
  # Required: name of the detector
  coral_usb:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
  coral_pci0:
    type: edgetpu
    device: pci:0
  coral_pci1:
    type: edgetpu
    device: pci:1
  coral_pci2:
    type: edgetpu
    device: pci:2
  coral_pci3:
    type: edgetpu
    device: pci:3

# Required: mqtt configuration
mqtt:
  # Required: host name
  host: homeasssistant_mqtt
  
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: XXXXXXXX
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}. 
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: XXXXXXXX
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

record:
  enabled: true
  events:
    retain:
      default: 3

# Optional: Global ffmpeg args
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning

  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: -c:v h264_cuvid
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -use_wallclock_as_timestamps 1
  
  # Optional: global output args (default: shown below)
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -f flv -c:v copy -c:a aac

# Optional: Global object filters for all cameras.
# NOTE: can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: max_int)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.6

# Required: configuration section for cameras
cameras:
  office:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://XXXXXXXX/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXXXXXX&password=XXXXXXXX
          roles:
            - detect
        - path: http://XXXXXXXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXXXXXX&password=XXXXXXXX
          roles:
            - rtmp
            - record
    
    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: Camera level detect settings
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
      max_disappeared: 30
      height: 672
      width: 896
      fps: 7

    # Optional: camera specific mqtt settings
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270

    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True

    # Optional: Configuration for the snapshots in the debug view and mqtt
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: False
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

    # Optional: Camera level object filters config. If defined, this is used instead of the global config.
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 2000
          max_area: 200000
          min_score: 0.35
          threshold: 0.7
  ```

**Reply by NickM-27** [reply]
Looks like you're still using the older reolink input args, recommend moving to the new ones https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others

also in general wouldn't recommend overriding the default input_args globally. Should let frigate set them unless you need specific ones like in the reolink case

**Reply by hagak** [reply]
Ok so you mean leave the default input_args OUT of the global section?

I removed the comments just to make it smaller.  I removed the nobuffer option to match the reolink suggestion and removed the global input_arg section.  The lag after restart seems to be about 1-2s now. Measure via debug screen, raise my arm and count until I see my arm move in the image (one one thousand, two one thousand, etc).  Before I could get to 5 one thousand, not just 2.
```

database:
  path: /media/frigate/data/frigate.db

detectors:
  coral_usb:
    type: edgetpu
    device: usb
  coral_pci0:
    type: edgetpu
    device: pci:0
  coral_pci1:
    type: edgetpu
    device: pci:1
  coral_pci2:
    type: edgetpu
    device: pci:2
  coral_pci3:
    type: edgetpu
    device: pci:3


record:
  enabled: true
  events:
    retain:
      default: 3

ffmpeg:
  global_args: -hide_banner -loglevel warning

  hwaccel_args: -c:v h264_cuvid
  
  output_args:
     detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
     rtmp: -f flv -c:v copy -c:a aac

objects:
  track:
    - person
    - car
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: max_int)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.6
cameras:
  office:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://XXXXXXXX/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXXXXXX&password=XXXXXXXX
          roles:
            - detect
        - path: http://XXXXXXXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXXXXXX&password=XXXXXXXX
          roles:
            - rtmp
            - record
    
    best_image_timeout: 60
   
    detect:
      enabled: True
      max_disappeared: 30
      height: 672
      width: 896
      fps: 7

    mqtt:
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
    rtmp:
      enabled: True

    snapshots:
      enabled: False
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      retain:
        default: 10
        objects:
          person: 15

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 2000
          max_area: 200000
          min_score: 0.35
          threshold: 0.7
  ```
