### DISCUSSION TITLE
Multi zone (record/snapshots)

### DISCUSSION THREAD

**Discussion by cooper7012** [blakeblackshear/frigate#4026] [Ask A Question]
Hi,
I want events for object person (record & snapshots) in zone1 & zone2

I want events for object car (record & snapshots) only in zone2

Is this possible?
<img width="658" alt="Screen Shot 2022-10-05 at 3 12 18 PM 2" src="https://user-images.githubusercontent.com/64494055/194145472-38207c0f-5ac6-4d4e-9e79-64fd3f17b757.png">

**Comment by NickM-27** [comment]
Yes, objects can be specified per zone

```yaml
zones:
  zone_1:
    objects:
      - person 
```

**Reply by cooper7012** [reply]
With the following code I'm getting events (record & snapshots) for object car in zone1.
```yml
  front_walkway:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - detect
            - rtmp
        - path: rtsp://...
          roles:
            - record
    detect:
      width: 640
      height: 480
    motion:
      mask:
        - 242,48,23,50,25,30,243,28
        - 460,295,442,426,640,447,640,188,640,92,591,53,556,41,520,45,505,73,492,98,490,122,486,154,501,204
    zones:
      zone2:
        coordinates: 455,145,491,129,463,109,370,105
        objects:
          - person
          - car
      zone1:
        coordinates: 455,480,445,449,443,415,433,357,458,297,477,263,547,210,457,151,375,119,314,96,248,78,318,77,392,81,494,97,533,42,551,0,0,0,0,480
        objects:
          - person
    record:
      enabled: True
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 10
          objects:
            person: 15
    snapshots:
      enabled: True
      clean_copy: False
      bounding_box: True
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0,91,51,64,101,52,166,48,194,0,68,0,0,0,0,0,0,0
        person:
          mask:
            - 10,84,73,86,140,76,138,27,36,32
            - 472,95,486,98,489,68,471,67
```
            -

**Reply by NickM-27** [reply]
You need to set `required_zones` on events and snapshots to make it so events only occur when a zone has been entered.

**Reply by cooper7012** [reply]
would a required zone exist for each object?

**Reply by NickM-27** [reply]
No, you just list the zones

```yaml
record:
  events:
    required_zones:
      - zone_1
      - zone_2

snapshots:
  required_zones:
    - zone_1
    - zone_2
```
