### DISCUSSION TITLE
TCP connection to camera timing out?

### DISCUSSION THREAD

**Discussion by EverlyScott** [blakeblackshear/frigate#4046] [Ask A Question]
Hello, I have a Jidetech 5MP POE BULLET IP CAMERA and it doesn't seem to be working. I've tried using the same config as they have in #1994 because they also have the same brand as I do but it hasn't helped.

Here is the log I get:
```
root@srv3:/var/frigate# docker-compose up
[+] Running 1/0
 ⠿ Container frigate  Created                                                                                                                       0.0s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-10-08 17:13:36] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
frigate  | Starting migrations
frigate  | [2022-10-08 17:13:36] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-10-08 17:13:36] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-10-08 17:13:36] detector.cpu                   INFO    : Starting detection process: 224
frigate  | [2022-10-08 17:13:36] frigate.app                    INFO    : Output process started: 226
frigate  | [2022-10-08 17:13:36] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-10-08 17:13:36] ws4py                          INFO    : Using epoll
frigate  | [2022-10-08 17:13:36] frigate.app                    INFO    : Camera processor started for driveway: 230
frigate  | [2022-10-08 17:13:36] frigate.app                    INFO    : Capture process started for driveway: 232
frigate  | [2022-10-08 17:13:41] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
frigate  | [2022-10-08 17:13:41] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-10-08 17:13:56] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
frigate  | [2022-10-08 17:13:56] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-10-08 17:13:56] ffmpeg.driveway.detect         ERROR   : [tcp @ 0x5588a0278240] Connection to tcp://192.168.1.51:554?timeout=5000000 failed: Connection timed out
frigate  | [2022-10-08 17:13:56] ffmpeg.driveway.detect         ERROR   : rtsp://192.168.1.51:554/1/h264major: Connection timed out
```

And here is my config:
```yml
mqtt:
  host: 192.168.1.103
  port: 1883

record:
  enabled: True
  retain:
    days: 10

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.51:554/1/h264major
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2592
      height: 1944
      fps: 15
```

When I connect to the camera in vlc it works.
