### DISCUSSION TITLE
Working automation with Pushover and HA with attachments?

### DISCUSSION THREAD

**Discussion by biggen1684** [blakeblackshear/frigate#406] [Ask A Question] [answered]
The built-in HA notifications don't always send immediately to my phone.  Even using `ttl` and `priority` I still don't get consistent immediate notifications so I wanted to play around with using Pushover.  I can get notifications but no attachments.  Here is my config:

```
automation:
  - alias: "driveway notification"
    trigger:
      platform: mqtt
      topic: frigate/events
    condition: 
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.driveway_notfication', 'last_triggered')) |int(0) ) > 45 }}"
    action:            
      - service: notify.rodman_phone
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected in the driveway.'
          data:
            attachment: 'http://10.200.200.65:5000/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg'
```

I'm not getting the attachment however.  Its probably because of the `attachment` and it being wrong.  What am I missing here?

**Comment by hawkeye217** [comment]
You likely need the public address of your HA instance instead of ``10.200.200.65``.

**Reply by biggen1684** [reply]
Well this is all internal testing so that should work.

**Comment by biggen1684** [comment]
I've also tried this as the action:
```
action:            
      - service: notify.rodman_phone
        data:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected in the driveway.'
          data:
            attachment: 'http://10.200.200.54:5000/driveway/person/best.jpg'
```

And that doesn't work either.  That is the frigate installation which has the `HTTP` endpoints.  I also know that the `attachment` address is valid because I can see the `best.jpg` from my laptop.

Again, I'm getting the notifications but not the attachment.

Strange.

**Comment by blakeblackshear** [comment]
Try using a public jpg file to make sure this is actually a frigate specific issue.

**Comment by asemev** [comment]
i have exactly the same issue (i know, i reported already - sorry). i just cant get the snapshot attached to the notifications (internally in my wifi or from the outside). I have been trying several things for days but to no avail.

alias: Notify Person Detection
description: ''
trigger:
  - platform: mqtt
    topic: frigate/events
condition: []
action:
  - service: notify.notify
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: >-
          "https://asemev.duckdns.org/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}.jpg?format=android"
        tag: '{{trigger.payload_json["after"]["id"]}}'
mode: single

Direct IP address entry also doesnt work:

action:
  - service: notify.notify
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: >-
          "http://192.168.178.84:5000/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}.jpg?format=android"
        tag: '{{trigger.payload_json["after"]["id"]}}'
mode: single

(sorry to post my issue here again)
-asemev

**Comment by msekoranja** [comment, marked as answer]
I had the same problem. I have checked pushover notification integration code and it just does not handle URLs as attachment (the documentation states that it does).

What I did is the following:
```
shell_command:
  url_to_file: "curl {{ url }} -o {{ to_file }}"
```
```
- id: car_at_entrance
  alias: Car at entrance
  trigger:
    platform: mqtt
    topic: frigate/events
  condition:
    - condition: template
      value_template: "{{ trigger.payload_json['after']['camera'] == 'entrance' }}"
    - condition: template
      value_template: "{{ trigger.payload_json['after']['label'] == 'car' }}"
    - condition: template   # only notify once every 5 minutes
      value_template: "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.car_at_entrance', 'last_triggered'))|float(0) ) > 300 }}"
  action:
    - service: shell_command.url_to_file
      data_template:
        url: "http://<ha ip>:5000/events/{{trigger.payload_json['after']['id']}}/snapshot.jpg"
        to_file: "/config/snapshots/frigate.jpg"
    - service: notify.pushover
      data_template:
        title: "Car at entrance"
        message: "{{ trigger.payload_json['after']['label'] }} with score {{  trigger.payload_json['after']['top_score'] }}"
        data:
          sound: siren
          priority: 1
          attachment: "/config/snapshots/frigate.jpg"
```
