### DISCUSSION TITLE
Snake Detection

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#4084] [Ask A Question]
In the fall we get snakes entering the basement of our cottage. I would like to setup Frigate to alert us if a snake is detected crawling around the floor. I do not see snake listed in the object detection list. [https://docs.frigate.video/configuration/objects](url)
Any suggestions how I can add detect "snake" option.

**Comment by NickM-27** [comment]
You may need to find a custom model that does this, perhaps it could work with frigate but I'm unsure of what options exist. 

Snake seems like a pretty difficult one from a camera perspective depending on how big they are.

**Reply by 18923** [reply]
Thank you,
Found this but have no idea how to use it in Frigate [https://github.com/SaiKrishnaTheGreat/Snake_Detection](url)

**Comment by 18923** [comment]
Since there generally is no motion in the area of interest I tried setting a bottle in the camera view so that whenever there is motion from say a mouse or snake the bottle object would be detected and I would get an alert. This turned out to be unreliable as the stationary object is not always detected.
I tried tuning values (below) but not having much luck. Any suggestions to detect stationary objects on motion much appreciated.
detect:
      stationary:
        interval: 10      # default 0
        threshold: 50   # default 50, tried 20, 30, 60, 80

**Reply by NickM-27** [reply]
I'm not sure what you mean, but I'd recommend setting a max_frames for `bottle` so it won't ever be detected as stationary and a new event will be created when there is motion.

to be clear this is generally NOT recommended but I think in this edge case it will work fairly well.

**Reply by 18923** [reply]
Tried max_frames but stationary bottle still not being detected on motion. Only detected again if I move the bottle.

Thank you, I'll keep trying

**Reply by NickM-27** [reply]
Odds are the snake or other animal is not big enough to trigger motion with the default motion settings

**Reply by 18923** [reply]
It seem that max_frames did it.... this configuration is working for me. Any time I walk by, the "bottle" gets detected and an event is saved.

```
  detect:
      stationary:
        interval: 0      # default 0

        threshold: 50    # default 50
        max_frames:
          # default: 3000
            # Optional: Object specific values
          objects:
            bottle: 100  
```
