### DISCUSSION TITLE
Camera config for IP5M-T1179EW

### DISCUSSION THREAD

**Discussion by MrksHfmn** [blakeblackshear/frigate#4127] [General]
Hi all, I would like to get the camera to run in frigate, unfortunately the second stream in frigate does not work. What is the correct URL?

```
cameras:
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.26:554/cam/realmonitor?channel=1&subtype=2  // <-- not working; second stream 
          roles:
            - detect
        - path: rtsp://admin:password@192.168.1.26:554/live  // <--- works! first stream
          roles:
            - record
```

**Comment by AML225** [comment]
I have the same cameras, the subtypes should be 0 for the main stream, and 1 for the substream:

```
cameras:
 <camera_name>:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@<ip>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://<user>:<password>@<ip>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
```
