### DISCUSSION TITLE
Help/clarification with how event retention works

### DISCUSSION THREAD

**Discussion by bluesk1d** [blakeblackshear/frigate#4172] [Ask A Question] [answered]
My goal is to record all footage 24/7 but retain all motion events for 7 days and then specific object types for longer. I was hoping to be able to see uncategorized motion events in the recordings timeline along with identified object events in order to quickly find motion that Frigate may have otherwise discarded but maybe it doesn't actually work that way. Person/cat/dog events are retained as expected but none of the motion only events are.

Should this config do what I want or do saved motion events just not show up as recordings/events?

v0.11.1

```
cameras:
   backyard:
    rtmp:
      enabled: False
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.30.116:554/H264/ch1/main/av_stream
          roles:
            - detect
            - record
    detect:
      fps: 6
      stationary:
        interval: 150
        threshold: 30
    motion:
      mask:
        - 94,225,231,146,391,67,494,36,495,0,0,0,0,300 # Timestamp
        - 354,221,558,380,505,441,392,367,318,299,255,231,255,158,338,134,357,141 # Lower bushes
        - 624,82,616,44,673,24,734,54,762,72,748,98,797,111,765,146,734,104 # Upper bushes
objects:
  track:
    - person
    - cat
    - dog
record:
  enabled: True
  retain:
    days: 14
  events:
    retain:
      default: 7
      mode: motion
      objects:
        person: 180
        dog: 30
        cat: 30
```
