### DISCUSSION TITLE
h265/hevc support

### DISCUSSION THREAD

**Discussion by jacoblannerbro** [blakeblackshear/frigate#4197] [Ask A Question]
Is there some setting in the yaml file that has to be done to get h265 streams working in your browser? I got the latest chrome browser with h265 support but I can't watch h265 streams in frigate.

**Comment by NickM-27** [comment]
What version of frigate are you running?

**Comment by jacoblannerbro** [comment]
Latest version.

**Reply by NickM-27** [reply]
Please give a specific version number from the debug screen, seen plenty of users who think they're on the latest version and ended up not. 

Also, when you try to watch h.265 what are the frigate logs? What are the browser console logs?

**Comment by jacoblannerbro** [comment]
Version: 0.11.1-2EADA21.
This is the error in the frigate log:

[2022-10-29 20:03:06] watchdog.forradet              ERROR   : The
following ffmpeg logs include the last 100 lines prior to exit.
[2022-10-29 20:03:06] ffmpeg.forradet.detect         ERROR   :
WARNING: defaulting hwaccel_output_format to qsv for compatibility
with old commandlines. This behaviour is DEPRECATED and will be
removed in the future. Please explicitly set "-hwaccel_output_format
qsv".
[2022-10-29 20:03:06] ffmpeg.forradet.detect         ERROR   : [flv @
0x562356851fc0] Video codec hevc not compatible with flv
[2022-10-29 20:03:06] ffmpeg.forradet.detect         ERROR   : Could
not write header for output file #0 (incorrect codec parameters ?):
Function not implemented
[2022-10-29 20:03:06] ffmpeg.forradet.detect         ERROR   : Error
initializing output stream 0:0 --
[2022-10-29 20:03:06] ffmpeg.forradet.detect         ERROR   :
[2022-10-29 20:03:10] frigate.video                  ERROR   :
forradet: Unable to read frames from ffmpeg process.
[2022-10-29 20:03:10] frigate.video                  ERROR   :
forradet: ffmpeg process is not running. exiting capture thread...
[2022-10-29 20:03:11] frigate.video                  ERROR   : bastun:
Unable to read frames from ffmpeg process.
[2022-10-29 20:03:11] frigate.video                  ERROR   : bastun:
ffmpeg process is not running. exiting capture thread...
[2022-10-29 20:03:16] watchdog.forradet              ERROR   : Ffmpeg
process crashed unexpectedly for forradet.
[2022-10-29 20:03:16] watchdog.forradet              ERROR   : The
following ffmpeg logs include the last 100 lines prior to exit.
[2022-10-29 20:03:16] ffmpeg.forradet.detect         ERROR   :
WARNING: defaulting hwaccel_output_format to qsv for compatibility
with old commandlines. This behaviour is DEPRECATED and will be
removed in the future. Please explicitly set "-hwaccel_output_format
qsv".
[2022-10-29 20:03:16] ffmpeg.forradet.detect         ERROR   : [flv @
0x563b09b18fc0] Video codec hevc not compatible with flv
[2022-10-29 20:03:16] ffmpeg.forradet.detect         ERROR   : Could
not write header for output file #0 (incorrect codec parameters ?):
Function not implemented
[2022-10-29 20:03:16] ffmpeg.forradet.detect         ERROR   : Error
initializing output stream 0:0 --
[2022-10-29 20:03:16] ffmpeg.forradet.detect         ERROR   :


Den fre 28 okt. 2022 kl 16:09 skrev Nicolas Mowen ***@***.***

**Reply by NickM-27** [reply]
You have to disable RTMP, it does not support h.265

**Comment by jacoblannerbro** [comment]
Still not working after disabling RTMP.
Get this log now:

[2022-10-30 11:06:46] frigate.video                  ERROR   :
forradet: Unable to read frames from ffmpeg process.
[2022-10-30 11:06:46] frigate.video                  ERROR   :
forradet: ffmpeg process is not running. exiting capture thread...
[2022-10-30 11:06:52] watchdog.forradet              ERROR   : Ffmpeg
process crashed unexpectedly for forradet.
[2022-10-30 11:06:52] watchdog.forradet              ERROR   : The
following ffmpeg logs include the last 100 lines prior to exit.
[2022-10-30 11:06:52] ffmpeg.forradet.detect         ERROR   :
WARNING: defaulting hwaccel_output_format to qsv for compatibility
with old commandlines. This behaviour is DEPRECATED and will be
removed in the future. Please explicitly set "-hwaccel_output_format
qsv".
[2022-10-30 11:06:52] ffmpeg.forradet.detect         ERROR   : [flv @
0x55b3706cffc0] Video codec hevc not compatible with flv
[2022-10-30 11:06:52] ffmpeg.forradet.detect         ERROR   : Could
not write header for output file #0 (incorrect codec parameters ?):
Function not implemented
[2022-10-30 11:06:52] ffmpeg.forradet.detect         ERROR   : Error
initializing output stream 0:0 --
[2022-10-30 11:06:52] ffmpeg.forradet.detect         ERROR   :


Den lör 29 okt. 2022 kl 20:36 skrev Nicolas Mowen ***@***.***

**Reply by blakeblackshear** [reply]
That indicates that you didn't disable rtmp. Maybe you just removed it from the list of roles. You need to specify:

```yaml
rtmp:
  enabled: False
```

**Comment by jacoblannerbro** [comment]
Still no luck:

[2022-10-30 13:33:56] ffmpeg.forradet.detect         ERROR   : [flv @
0x563e4bfc6fc0] Video codec hevc not compatible with flv
[2022-10-30 13:33:56] ffmpeg.forradet.detect         ERROR   : Could
not write header for output file #0 (incorrect codec parameters ?):
Function not implemented
[2022-10-30 13:33:56] ffmpeg.forradet.detect         ERROR   : Error
initializing output stream 0:0 --
[2022-10-30 13:33:56] ffmpeg.forradet.detect         ERROR   :
[2022-10-30 13:34:00] frigate.video                  ERROR   :
forradet: Unable to read frames from ffmpeg process.
[2022-10-30 13:34:00] frigate.video                  ERROR   :
forradet: ffmpeg process is not running. exiting capture thread...
[2022-10-30 13:34:06] watchdog.forradet              ERROR   : Ffmpeg
process crashed unexpectedly for forradet.


Den sön 30 okt. 2022 kl 12:55 skrev Blake Blackshear <
***@***.***>:

**Reply by NickM-27** [reply]
Please repaste your config, the logs indicate that rtmp is still enabled

`ffmpeg.forradet.detect ERROR : [flv @ 0x563e4bfc6fc0] Video codec hevc not compatible `

**Comment by jacoblannerbro** [comment]
```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt
-rtsp_transport tcp -timeout 5000000 -an

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - fox
    - horse

database:
  path: /media/frigate/frigate.db

cameras:
  forradet:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://192.168.1.109:554/Streaming/Channels/101/
          roles:
            #- record
            #- rtmp
            - detect
        # Low Resolution Stream
        #- path: rtsp://192.168.1.109:554/Streaming/Channels/102/
          #roles:
            #- detect
    rtmp:
      enabled: False
    detect:
      width: 2560
      height: 1440
    snapshots:
      enabled: False
    record:
      enabled: False
      retain:
        days: 2
      events:
        retain:
          default: 3
```
