### DISCUSSION TITLE
Can't play back events from one camera, other identical camera is fine.

### DISCUSSION THREAD

**Discussion by ve6rah** [blakeblackshear/frigate#4203] [Ask A Question] [answered]
I have 2 identical doorbell cameras (Dahua DH-DB6I) They both have the exact same firmware, they both have identical settings in the Dahua app, and they both have identical (except for names and zone coordinates) configurations in Frigate.
The back door camera works perfectly as expected. The front doorbell camera works great for live view, and it shows events properly in the frigate UI, but you can't play any of the events through frigate, and downloading them gives a file only a couple hundred bytes in size.
The underlying files do exist on the hard drive, and if you try playing them directly all appears as it should (though in very short chunks as those files are only a few seconds long each).

Chrome shows "The media could not be loaded, either because the server or network failed or because the format is not supported"

frigate.yml
```
detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: False


rtmp:
  enabled: True

objects:
  track:
    - person
    - car

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://<anonymized>:<anonymized>@<anonymized>:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
        - path: rtsp://<anonymized>:<anonymized>@<anonymized>:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 502,0,524,104,513,180,560,203,599,204,704,191,704,0
        - 219,84,239,181,237,236,215,255,206,268,140,257,0,263,0,0,209,0
    zones:
      front_yard:
        coordinates: 0,480,0,343,44,347,79,351,112,357,172,363,270,368,351,360,427,354,514,343,589,328,668,308,704,304,704>
        objects:
          - person
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
          - front_yard
        objects:
          - person
        retain:
          objects:
            person: 20
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      required_zones:
        - front_yard
      retain:
        objects:
          person: 20
  back_door:
    ffmpeg:
      inputs:
        - path: rtsp://<anonymized>:<anonymized>@<anonymized>:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
        - path: rtsp://<anonymized>:<anonymized>@<anonymized>:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
         - 704,0,0,0,0,203,52,206,111,218,143,232,191,236,234,233,325,234,421,261,543,258,704,267
    zones:
      back_yard:
        coordinates: 0,480,0,267,25,257,52,255,55,309,362,345,433,329,497,367,534,370,581,381,704,436,704,480
        objects:
          - person
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
          - back_yard
        objects:
          - person
        retain:
          objects:
            person: 20
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      required_zones:
        - back_yard
      retain:
        objects:
           person: 20
```

Docker container log from when trying to play the event is completely empty, nothing when recording the event either

Chrome console shows the following trying to play the event
```
videojs-seek-buttons.4eebf803.js:10          GET http://<anonymized>:5000//vod/event/1666980408.314241-gb2rbd/master.m3u8 503 (Service Temporarily Unavailable)
id @ videojs-seek-buttons.4eebf803.js:10
Tt @ videojs-seek-buttons.4eebf803.js:10
r @ videojs-seek-buttons.4eebf803.js:54
r.start @ videojs-seek-buttons.4eebf803.js:54
r.load @ videojs-seek-buttons.4eebf803.js:54
t @ videojs-seek-buttons.4eebf803.js:63
r.src @ videojs-seek-buttons.4eebf803.js:63
handleSource @ videojs-seek-buttons.4eebf803.js:63
s.setSource @ videojs-seek-buttons.4eebf803.js:33
t @ videojs-seek-buttons.4eebf803.js:33
r.loadTech_ @ videojs-seek-buttons.4eebf803.js:43
r.src_ @ videojs-seek-buttons.4eebf803.js:45
(anonymous) @ videojs-seek-buttons.4eebf803.js:45
ei @ videojs-seek-buttons.4eebf803.js:33
ei @ videojs-seek-buttons.4eebf803.js:33
(anonymous) @ videojs-seek-buttons.4eebf803.js:33
(anonymous) @ videojs-seek-buttons.4eebf803.js:33
setTimeout (async)
t.setTimeout @ videojs-seek-buttons.4eebf803.js:33
o0 @ videojs-seek-buttons.4eebf803.js:33
r.handleSrc_ @ videojs-seek-buttons.4eebf803.js:45
r.src @ videojs-seek-buttons.4eebf803.js:45
t @ videojs-seek-buttons.4eebf803.js:33
t.addChild @ videojs-seek-buttons.4eebf803.js:33
a @ videojs-seek-buttons.4eebf803.js:33
t.initChildren @ videojs-seek-buttons.4eebf803.js:33
t @ videojs-seek-buttons.4eebf803.js:34
I @ videojs-seek-buttons.4eebf803.js:45
(anonymous) @ VideoPlayer.510ca061.js:1
Rt @ vendor.153a2319.js:1
Si @ vendor.153a2319.js:1
setTimeout (async)
o @ vendor.153a2319.js:1
requestAnimationFrame (async)
(anonymous) @ vendor.153a2319.js:1
v.diffed @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
(anonymous) @ vendor.153a2319.js:1
Je @ vendor.153a2319.js:1
Promise.then (async)
Ot @ vendor.153a2319.js:1
T.setState @ vendor.153a2319.js:1
n.__c.n.__ @ vendor.153a2319.js:1
onClick @ Events.e0c3b75b.js:14
br @ vendor.153a2319.js:1
videojs-seek-buttons.4eebf803.js:31 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Ge {code: 4, message: 'The media could not be loaded, either because the …rk failed or because the format is not supported.'}
(anonymous) @ videojs-seek-buttons.4eebf803.js:31
Zd.n.error @ videojs-seek-buttons.4eebf803.js:31
r.error @ videojs-seek-buttons.4eebf803.js:45
r.handleTechError_ @ videojs-seek-buttons.4eebf803.js:45
(anonymous) @ videojs-seek-buttons.4eebf803.js:43
n.dispatcher.n.dispatcher @ videojs-seek-buttons.4eebf803.js:33
error (async)
tt @ videojs-seek-buttons.4eebf803.js:33
Zt @ videojs-seek-buttons.4eebf803.js:33
on @ videojs-seek-buttons.4eebf803.js:33
Zt @ videojs-seek-buttons.4eebf803.js:33
on @ videojs-seek-buttons.4eebf803.js:33
t @ videojs-seek-buttons.4eebf803.js:63
handleSource @ videojs-seek-buttons.4eebf803.js:63
s.setSource @ videojs-seek-buttons.4eebf803.js:33
t @ videojs-seek-buttons.4eebf803.js:33
r.loadTech_ @ videojs-seek-buttons.4eebf803.js:43
r.src_ @ videojs-seek-buttons.4eebf803.js:45
(anonymous) @ videojs-seek-buttons.4eebf803.js:45
ei @ videojs-seek-buttons.4eebf803.js:33
ei @ videojs-seek-buttons.4eebf803.js:33
(anonymous) @ videojs-seek-buttons.4eebf803.js:33
(anonymous) @ videojs-seek-buttons.4eebf803.js:33
setTimeout (async)
t.setTimeout @ videojs-seek-buttons.4eebf803.js:33
o0 @ videojs-seek-buttons.4eebf803.js:33
r.handleSrc_ @ videojs-seek-buttons.4eebf803.js:45
r.src @ videojs-seek-buttons.4eebf803.js:45
t @ videojs-seek-buttons.4eebf803.js:33
t.addChild @ videojs-seek-buttons.4eebf803.js:33
a @ videojs-seek-buttons.4eebf803.js:33
t.initChildren @ videojs-seek-buttons.4eebf803.js:33
t @ videojs-seek-buttons.4eebf803.js:34
I @ videojs-seek-buttons.4eebf803.js:45
(anonymous) @ VideoPlayer.510ca061.js:1
Rt @ vendor.153a2319.js:1
Si @ vendor.153a2319.js:1
setTimeout (async)
o @ vendor.153a2319.js:1
requestAnimationFrame (async)
(anonymous) @ vendor.153a2319.js:1
v.diffed @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
di @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
_n @ vendor.153a2319.js:1
Bt @ vendor.153a2319.js:1
(anonymous) @ vendor.153a2319.js:1
Je @ vendor.153a2319.js:1
Promise.then (async)
Ot @ vendor.153a2319.js:1
T.setState @ vendor.153a2319.js:1
n.__c.n.__ @ vendor.153a2319.js:1
onClick @ Events.e0c3b75b.js:14
br @ vendor.153a2319.js:1

```

Any ideas/suggestions?
