### DISCUSSION TITLE
config.yml vs debug config

### DISCUSSION THREAD

**Discussion by erte1** [blakeblackshear/frigate#4213] [Ask A Question] [answered]
I've noticed the debug config does not match the settings I have in config.yml.   For example, I have record and rtmp on main stream, and detect on the sub stream.   Debug config leads me to believe that record, rtmp, and detect are all working off the main stream...

### Config.yml
```   ffmpeg:
      inputs:
        - path: rtsp://XXX@192.168.54.201:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
      inputs:
        - path: rtsp://XXX@192.168.54.201:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            - rtmp
```

### Debug Config
```        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://XXX@192.168.54.201:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ]
```

Which one is Frigate using?

**Comment by NickM-27** [comment, marked as answer]
This is happening because you incorrectly created the config. You are overwriting `inputs` which is putting all roles on the single stream.

It should be:

```yaml
      inputs:
        - path: rtsp://XXX@192.168.54.201:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://XXX@192.168.54.201:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            - rtmp
```
