### DISCUSSION TITLE
Not sure why ffmpeg is running

### DISCUSSION THREAD

**Discussion by paragbatavia** [blakeblackshear/frigate#4215] [Ask A Question]
Hello,

I'm trying to create a setup that only records streams to disk, no detection. My cameras output native h264. I've got 5 cameras running, and when I fire up frigate, I see 5 ffmpeg processes, with a substantial load. I thought if I wasn't running detect there wouldn't be any transcoding? 

This is my config.yml

I appreciate the help! I've googled, and poked around documentation and on here, without luck. 

```
mqtt:
  host: 127.0.0.1

logger:
  default: info

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  
cameras:
  frig_backyard_pool:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@192.168.10.11
          roles:
            - detect
  frig_basement_stairway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@192.168.10.12
          roles:
  frig_front_left:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@192.168.10.13
          roles:
  frig_front_right:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@192.168.10.14
          roles:
  frig_garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@192.168.10.15
          roles:

rtmp:
  enabled: False
detect:
  width: 1280
  height: 720
record:
  enabled: True
  retain:
    days: 5
snapshots:
  enabled: True

```
