### DISCUSSION TITLE
Need some help accessing the rtmp stream generated by frigate

### DISCUSSION THREAD

**Discussion by ovizii** [blakeblackshear/frigate#4216] [Ask A Question] [answered]
First some info: 

running Home Asssistant and frigate as an addon: Frigate (Full Access) 
I have defined a camera and assigned it the rtmp role. 
I am trying to access the rtmp stream from within home assistant to do noise detection on this rtmp stream like this:

```
binary_sensor:
  - platform: ffmpeg_noise
    name: Bark Detector
    input: rtmp://???/live/doggycam
    initial_state: false
    peak: -45
    reset: 60
    duration: 3
```

The docs state
- `rtmp://<frigate_host>/live/<camera_name> ` 
- `Port 1935 must be open.`

but what do I use for frigate-host? 

I tried the following options: 

- `input: rtmp://ha-ip/live/doggycam`
- `input: rtmp://ccab4aaf-frigate-fa/live/doggycam`

Any other ideas? I assume I can ignore the part about opening the port since frigate runs as an add-on and should be accessible from home assistant. 

I even accessed the add-on settings and made sure port 1935 is set up:
![image](https://user-images.githubusercontent.com/837902/199022675-c095d5bd-b45b-4d59-912b-0b459a0d5a1e.png)
