### DISCUSSION TITLE
Request for help with setting up Dahua IP Camera 4MP IPC-HDW4433C-A

### DISCUSSION THREAD

**Discussion by ndbroadbent** [blakeblackshear/frigate#4223] [General]
I bought [this Dahua IP camera from AliExpress](https://www.aliexpress.com/item/32990164624.html?spm=a2g0o.order_list.0.0.597e1802XmHEFQ) to try out Frigate. I also got a Google Coral USB TPU.

I'm having a hard time figuring out how to configure the sub stream so that the sub stream isn't being stretched (4:3) when it should be 16:9. My camera only seems to have 2 streams, so it doesn't look like I can follow the example in the docs with 3 streams: https://docs.frigate.video/guides/camera_setup#example-camera-configuration

```
Device Type: VD-2T41-AS
System Version: V2.820.003C001.0.R, Build Date: 2022-03-31
WEB Version: V3.2.1.1210837
ONVIF Version: 21.06(V3.1.0.1170003)
```

<img width="1536" alt="Screen Shot 2022-11-01 at 10 55 42 PM" src="https://user-images.githubusercontent.com/139536/199207797-c31022b5-af7b-4eb0-9a78-e3c5542db9e7.png">

<img width="414" alt="Screen Shot 2022-11-01 at 10 49 15 PM" src="https://user-images.githubusercontent.com/139536/199206564-b55b3948-a4f5-4fcd-89bb-a3ae68b75e84.png">

Max sub stream resolution: 704x576 (D1) - squashed 4:3 aspect ratio, looks like it should be 16:9

This doesn't look good in the Frigate UI, or in the Home Assistant card:

<img width="512" alt="Screen Shot 2022-11-01 at 10 52 10 PM" src="https://user-images.githubusercontent.com/139536/199207116-3ea3bf6d-94b9-4f68-80cc-4249edec9f09.png">

<img width="432" alt="Screen Shot 2022-11-01 at 10 52 24 PM" src="https://user-images.githubusercontent.com/139536/199207161-3c28d6b4-e0bd-4f9e-aff7-d82b17533d8c.png">

I read through https://github.com/blakeblackshear/frigate/issues/416 but I couldn't find a clear solution

Here's my `frigate.yml`:

```
mqtt:
  host: *********
  user: *********
  password: **********

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - bird
 
birdseye:
  enabled: True
  mode: continuous

cameras:
  living_room_camera:
    ffmpeg:
      inputs:
        - path: rtsp://***************:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://*****************:554/live
          roles:
            - record
      output_args:
        # detect: -vf scale=16:9 -f rawvideo -pix_fmt yuv420p
        rtmp: -vf "setdar=16/9" -f flv # -aspect 16:9 -c copy -f flv
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp:
      enabled: True
    detect:
      width: 704
      height: 576
      fps: 5
    # detect:
    #   width: 2560
    #   height: 1440

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

I can't figure out these `output_args`, nothing seems to be working

**Comment by blakeblackshear** [comment]
You can set the detect resolution to whatever you want and that will fix the detect aspect ratio.

Try without the quotes:
`rtmp: -vf setdar=16/9 -f flv -c copy`

**Reply by ndbroadbent** [reply]
Hi @blakeblackshear, thanks for the reply! That's great to know about the detect resolution, I wasn't sure how to test that.

This config is crashing for me:

```
      output_args:
        rtmp: -vf setdar=16/9 -f flv -c copy
    detect:
      width: 1024
      height: 576
      fps: 5
```

```
[2022-11-01 23:59:15] watchdog.living_room_camera    ERROR   : Ffmpeg process crashed unexpectedly for living_room_camera.
[2022-11-01 23:59:15] watchdog.living_room_camera    ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-01 23:59:15] ffmpeg.living_room_camera.detect ERROR   : Filtergraph 'setdar=16/9' was defined for video output stream 0:0 but codec copy was selected.
[2022-11-01 23:59:15] ffmpeg.living_room_camera.detect ERROR   : Filtering and streamcopy cannot be used together.
```

**Reply by ndbroadbent** [reply]
This worked! `rtmp: -vf setdar=16/9 -f flv`

<img width="1273" alt="Screen Shot 2022-11-02 at 12 07 39 AM" src="https://user-images.githubusercontent.com/139536/199219938-0fb73886-6794-488c-83bd-54022d06a02d.png">

I guess the quotes broke it in my earlier attempt: `rtmp: -vf "setdar=16/9" -f flv`

Thanks for your help!

---

P.S. I'm also a bit confused about the relationship between rtmp and detect. I am configuring `rtmp`, but the error logs seem to be coming from `ffmpeg.living_room_camera.detect`. I guess "detect" is also using the video from rtmp?

**Reply by NickM-27** [reply]
> I'm also a bit confused about the relationship between rtmp and detect. I am configuring rtmp, but the error logs seem to be coming from ffmpeg.living_room_camera.detect. I guess "detect" is also using the video from rtmp?

No, detect uses the video from the camera. Frigate created one ffmpeg process for each `path` and it just gets named detect even though rtmp and Steve are both running in that process

**Comment by ndbroadbent** [comment]
I finally figured something out! I had to use the `force_original_aspect_ratio=increase` option for ffmpeg - https://trac.ffmpeg.org/wiki/Scaling

Here's my working camera config:

```
cameras:
  living_room_camera:
    ffmpeg:
      inputs:
        - path: rtsp://*****:********@*******:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://*****:********@*******:554/live
          roles:
            - record
      output_args:
        detect: '-vf scale=1024:576:force_original_aspect_ratio=increase -f rawvideo -an -pix_fmt yuv420p'
        rtmp: -vf scale=1024:576:force_original_aspect_ratio=increase -an -f flv
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1024
      height: 576
      fps: 5
```

<img width="864" alt="Screen Shot 2022-11-01 at 11 56 42 PM" src="https://user-images.githubusercontent.com/139536/199218199-e26aafcb-b4c5-40a7-b7e1-e33a33a9cc02.png">

<img width="1278" alt="Screen Shot 2022-11-01 at 11 56 59 PM" src="https://user-images.githubusercontent.com/139536/199218249-e7742852-bb31-4260-87e8-b3fb1de4ae7d.png">


<img width="428" alt="Screen Shot 2022-11-01 at 11 56 18 PM" src="https://user-images.githubusercontent.com/139536/199218119-d37267dc-34d5-4b1e-bd55-b4a484ad5585.png">

**Reply by Heathy65** [reply]
I think I have a similar issue.  I have a pair of Dahua PC-HFW1431S cameras which have dual streams

- Main: 2304 x 1296
- Sub: 704 x 576

Prior to using the sub-stream all was good (the view in HA had the correct aspect ratio).  However when I introduced the sub-stream then the viewed aspect ratio is wrong in HA (although the sub-stream looks fine in VLC).

I have narrowed the issue down to this configuration 
```
    detect:
      width: 704
      height: 576
```
I thought the above was specific to the detect role but strangely even if I have the 'rtmp' role on the main stream and 'detect' on the sub stream the HA aspect ratio is wrong.  Changing the above to 1280 / 720 fixes the view but I thought the w/h for the detect should match the stream so should be 704 x 576 in my configuration?

```
cameras:
  ipc_garden_front:
    ffmpeg:
      inputs:

#         Main Stream
        - path: rtsp://(REDACTED)/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record

#         Sub Stream
        - path: rtsp://(REDACTED)/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif  
          roles:
            - detect
            - rtmp

    rtmp:
      enabled: True
    detect:
      #width: 1280
      #height: 720
      width: 704
      height: 576

**Reply by NickM-27** [reply]
if you check in VLC the media codec info you will see that the actual aspect ratio is different. VLC simply does some adjusting to make it appear the same (but it is in fact different)

**Reply by Heathy65** [reply]
Ah ok.  So am I correct that I should be using this configuration (since it is the chosen resolution of my sub stream?).
```
detect:
      width: 704
      height: 576
```
And if so what can I easily do to make the HA visualisation have the correct aspect ratio?

**Reply by NickM-27** [reply]
> Ah ok. So am I correct that I should be using this configuration (since it is the chosen resolution of my sub stream?).
> 
> ```
> detect:
>       width: 704
>       height: 576
> ```

the recommended setup is to use whatever the actual resolution is of the sub stream

> And if so what can I easily do to make the HA visualisation have the correct aspect ratio?

give the RTMP role to the main stream instead of the sub stream

**Reply by Heathy65** [reply]
Thanks for the suggestion, I previously tried that and the detect configuration is still causing issues with the HA view.

```
  ipc_garden_front: 
    ffmpeg:
      inputs:

#         Main Stream
        - path: rtsp://(REDACTED)/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp

#         Sub Stream
        - path: rtsp://(REDACTED)/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif  
          roles:
            - detect

    rtmp:
      enabled: True
    detect:
      width: 704
      height: 576
```
