### DISCUSSION TITLE
Should the example docker compose include an mqtt broker?

### DISCUSSION THREAD

**Discussion by tleyden** [blakeblackshear/frigate#4253] [Ask A Question] [answered]
I'm trying to install frigate as a standalone system (not with home-assistant.io for now), and I'm trying to figure out what I should use for an mqtt broker.  

I noticed in the default docker compose example in the [installation docs](https://docs.frigate.video/installation#docker), it doesn't start an mqtt broker, but it does start one in the github repo example [docker-compose](https://github.com/blakeblackshear/frigate/blob/d8123d249764c8004df2b9a9b37576445ea88b46/docker-compose.yml#L34-L38):

```
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
```

What is the recommended approach to run an mqtt broker?

Also if installing locally, is eclipse mosquitto recommended?  Any special config to be aware of?
