### DISCUSSION TITLE
MQTT events no events published

### DISCUSSION THREAD

**Discussion by eisentor** [blakeblackshear/frigate#4265] [Ask A Question] [answered]
Hi,

i do not receive any mqtt messages on my broker, but i can see events in the frigate ui.
This are my configurations for mosquitto and frigate, both of them running in a docker container on Windows.

I can publish and subscribe to Mosquitto over websocket with [http://www.hivemq.com/demos/websocket-client/](http://www.hivemq.com/demos/websocket-client/):
- don't be confused the port configuration is not fully visible in the screenshot :-)
![image](https://user-images.githubusercontent.com/79728148/200180565-3cf7f455-1390-49d6-9b14-29a71e74e64d.png)

As soon as i write a wrong IP-Adress in the configuration, i will get an host unknown message in the logs, but if its the correct there is not error message at all. By the way there is no logging from the module frigate.mqtt.

This is my log on startup:
```
[36mfrigate    |[0m [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[36mfrigate    |[0m [s6-init] ensuring user provided files have correct perms...exited 0.
[36mfrigate    |[0m [fix-attrs.d] applying ownership & permissions fixes...
[36mfrigate    |[0m [fix-attrs.d] done.
[36mfrigate    |[0m [cont-init.d] executing container initialization scripts...
[36mfrigate    |[0m [cont-init.d] done.
[36mfrigate    |[0m [services.d] starting services
[36mfrigate    |[0m [services.d] done.
[36mfrigate    |[0m [2022-11-06 15:53:19] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[36mfrigate    |[0m Starting migrations
[36mfrigate    |[0m [2022-11-06 15:53:19] peewee_migrate                 INFO    : Starting migrations
[36mfrigate    |[0m [2022-11-06 15:53:19] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[36mfrigate    |[0m [2022-11-06 15:53:19] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
[36mfrigate    |[0m There is nothing to migrate
[36mfrigate    |[0m [2022-11-06 15:53:19] peewee_migrate                 INFO    : There is nothing to migrate
[36mfrigate    |[0m [2022-11-06 15:53:19] detector.cpu                   INFO    : Starting detection process: 224
[36mfrigate    |[0m [2022-11-06 15:53:19] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[36mfrigate    |[0m [2022-11-06 15:53:19] ws4py                          INFO    : Using epoll
[36mfrigate    |[0m [2022-11-06 15:53:19] frigate.app                    INFO    : Output process started: 225
[36mfrigate    |[0m [2022-11-06 15:53:19] frigate.app                    INFO    : Camera processor started for mycam: 230
[36mfrigate    |[0m [2022-11-06 15:53:19] frigate.app                    INFO    : Capture process started for mycam: 232
[36mfrigate    |[0m [2022-11-06 15:53:19] urllib3.connectionpool         DEBUG   : Starting new HTTPS connection (1): api.github.com:443
[36mfrigate    |[0m [2022-11-06 15:53:19] urllib3.connectionpool         DEBUG   : https://api.github.com:443 "GET /repos/blakeblackshear/frigate/releases/latest HTTP/1.1" 200 1216
[36mfrigate    |[0m [2022-11-06 15:53:19] ws4py                          INFO    : Using epoll
[36mfrigate    |[0m [2022-11-06 15:53:19] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)
[36mfrigate    |[0m [2022-11-06 15:53:19] peewee                         DEBUG   : ('UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)', [30, None])
[36mfrigate    |[0m [2022-11-06 15:53:24] peewee                         DEBUG   : ('SELECT DISTINCT "t1"."sub_label" FROM "event" AS "t1"', [])
[36mfrigate    |[0m [2022-11-06 15:53:24] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera", "t1"."label", "t1"."zones", "t1"."start_time", "t1"."end_time", "t1"."has_clip", "t1"."has_snapshot", "t1"."plus_id", "t1"."retain_indefinitely", "t1"."sub_label", "t1"."top_score" FROM "event" AS "t1" WHERE ? ORDER BY "t1"."start_time" DESC LIMIT ?', [True, '25'])
[36mfrigate    |[0m [2022-11-06 15:53:24] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."label", "t1"."sub_label", "t1"."camera", "t1"."start_time", "t1"."end_time", "t1"."top_score", "t1"."false_positive", "t1"."zones", "t1"."thumbnail", "t1"."has_clip", "t1"."has_snapshot", "t1"."region", "t1"."box", "t1"."area", "t1"."retain_indefinitely", "t1"."ratio", "t1"."plus_id" FROM "event" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?', ['1667749935.829574-8wto0p', 1, 0])
[36mfrigate    |[0m [2022-11-06 15:53:56] peewee                         DEBUG   : ('SELECT DISTINCT "t1"."sub_label" FROM "event" AS "t1"', [])
[36mfrigate    |[0m [2022-11-06 15:53:56] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera", "t1"."label", "t1"."zones", "t1"."start_time", "t1"."end_time", "t1"."has_clip", "t1"."has_snapshot", "t1"."plus_id", "t1"."retain_indefinitely", "t1"."sub_label", "t1"."top_score" FROM "event" AS "t1" WHERE ? ORDER BY "t1"."start_time" DESC LIMIT ?', [True, '25'])
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Start expire recordings (new).
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Start deleted cameras.
[36mfrigate    |[0m [2022-11-06 15:54:19] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera", "t1"."path", "t1"."start_time", "t1"."end_time", "t1"."duration", "t1"."motion", "t1"."objects" FROM "recordings" AS "t1" WHERE (("t1"."camera" NOT IN (?)) AND ("t1"."end_time" < ?))', ['mycam', 1667750059.772886])
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Expiring 0 recordings
[36mfrigate    |[0m [2022-11-06 15:54:19] peewee.sqliteq                 DEBUG   : received query DELETE FROM "recordings" WHERE (0 = 1)
[36mfrigate    |[0m [2022-11-06 15:54:19] peewee                         DEBUG   : ('DELETE FROM "recordings" WHERE (0 = 1)', [])
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : End deleted cameras.
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Start all cameras.
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Start camera: mycam.
[36mfrigate    |[0m [2022-11-06 15:54:19] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera", "t1"."path", "t1"."start_time", "t1"."end_time", "t1"."duration", "t1"."motion", "t1"."objects" FROM "recordings" AS "t1" WHERE (("t1"."camera" = ?) AND ("t1"."end_time" < ?)) ORDER BY "t1"."start_time"', ['mycam', 1667750059.78729])
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Expiring 0 recordings
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : End camera: mycam.
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : End all cameras.
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : End expire recordings (new).
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Start expire files (legacy).
[36mfrigate    |[0m [2022-11-06 15:54:19] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera", "t1"."path", "t1"."start_time", "t1"."end_time", "t1"."duration", "t1"."motion", "t1"."objects" FROM "recordings" AS "t1" ORDER BY "t1"."start_time" LIMIT ? OFFSET ?', [1, 0])
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : Oldest recording in the db: 1667750059.797165
[36mfrigate    |[0m [2022-11-06 15:54:19] frigate.record                 DEBUG   : End expire files (legacy).
```

**Frigate - Docker-Compose**
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - C:/docker/frigate/config/config.yml:/config/config.yml:ro
      - C:/docker/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 15000:5000 # WebUI
      - 11935:1935 # RTMP feeds
    environment:
      #FRIGATE_RTSP_PASSWORD: "rtspFrigatePass"
      MQTT_USER: Frigate
      MQTT_PASS: Frigate1!
```

**Frigate - Config**
```
logger:
  default: info
  logs:
    frigate.mqtt: debug

mqtt:
  host: 10.40.0.91
  port: 11883
  user: frigate
  password: Frigate1!

objects:
  track:
    - person

snapshots:
  enabled: true
  retain:
    default: 1

cameras:
  mycam:
    mqtt:
      enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        rtmp: -c:v copy -f flv -ar 44100 -c:a aac
      inputs:
        - path: rtsp://10.10.0.1:7447/NmjJtJIX0TEtpjmu
          roles:
            - detect
            - rtmp
    detect:
      width: 2688
      height: 1512
      fps: 1
```

**Mosquitto - Docker-Compose**
```
services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - C:/docker/mosquitto/broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - C:/docker/mosquitto/broker/config/password.txt:/mosquitto/config/password.txt
      - C:/docker/mosquitto/broker/log:/mosquitto/log
      - C:/docker/mosquitto/broker/data:/mosquitto/data
    ports:
      - 11883:1883
      - 19001:9001
volumes:
  data: ~
```

**Mosquitto - Config**
```
listener 1883 0.0.0.0
persistence true
persistence_location /mosquitto/data
log_dest file /mosquitto/log/mosquitto.log

## Protocols
protocol websockets mqtt

## Authentication ##
# By default, Mosquitto >=2.0 allows only authenticated connections. Change to true to enable anonymous connections.
allow_anonymous false
password_file /mosquitto/config/password.txt
```

What i'am doing wrong? 
Thanks for any advice!

PS: "I have done a search for similar discussions" .. i hope so ..
