### DISCUSSION TITLE
Need help with Frigate triggering automation in Home Assistant

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#4312] [Ask A Question] [answered]
First, let me just say that I think Frigate is awesome! However, I don't have much coding experience and I'm finding it a bit challenging to get Frigate to trigger automations in Home Assistant. I am hoping someone here can point me in the right direction. I've posted my automation code below and welcome your comments.

Here is what I am trying to do: I have two cameras in the front of my house. In Frigate, I define a zone in each camera's field of view called "front_flood_light_zone". When Frigate detects a person in this zone, I want Frigate to send me a notification. I have gotten this to work, but problems start when I try to make it an actionable notification. Specifically, I want to add to buttons. The first button is to start a siren; the second tells the HA to take no further action. Is the automation code below correct? Many thanks. (For some reason, some of my dashes are being coverted to bullets, but they are dashes in my code.)

```yaml
alias: "Notify: Frigate detects person in front flood light zone"
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
  - condition: template
    value_template: >-
      {{ 'front_flood_light_zone' in
      trigger.payload_json['after']['entered_zones'] }}
  - condition: template
    value_template: >-
      {{ 'front_flood_light_zone' in
      trigger.payload_json['after']['current_zones'] }} 
  - condition: state
    entity_id: input_boolean.switch_notify_front_flood_light_zone
    state: "on"
action:
  - service: notify.mobile_app_andrew_s_iphone
    data:
      message: >-
        Person detected in front flood light zone at {{ now().strftime("%-I:%M
        %p") }}.
      title: "Warning: Front Flood Light"
      data:
        image: >-
          /api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
      actions:
        - action: START_FRONT_SIREN
          title: Start siren
          icon: sfsymbols:sun.max.fill
        - action: IGNORE
          title: Ignore
          icon: sfsymbols:xmark
          destructive: true
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: START_FRONT_SIREN
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: IGNORE
    timeout:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
    continue_on_timeout: false
  - choose:
      - conditions: "{{ wait.trigger.event.data.action == START_FRONT_SIREN }}"
        sequence:
          - service: shell_command.front_siren_on
            data: {}
      - conditions: "{{ wait.trigger.event.data.action == IGNORE }}"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 15
              milliseconds: 0
mode: single
```

**Comment by Cold-Lemonade** [comment, marked as answer]
After some trial and error, I've figured it out. The Home Assistant automation yaml code below sends a notification to my iPhone when Frigate detects a person in the front of my house (in a zone that I call the "front flood light zone") along with a snapshot showing the camera's view. This notification also has two action buttons: (1) I can start my siren; or (2) ignore the event. If I click on the start siren button, then Home Assistant starts the siren built into the camera and then sends me another notification to confirm that it has started the siren. Otherwise, if I press the ignore button, nothing happens.

```

alias: "Notify: Frigate detects person in front flood light zone (ver. 4)"
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
  - condition: template
    value_template: >-
      {{ 'front_flood_light_zone' in
      trigger.payload_json['after']['entered_zones'] }}
  - condition: template
    value_template: >-
      {{ 'front_flood_light_zone' in
      trigger.payload_json['after']['current_zones'] }} 
  - condition: state
    entity_id: input_boolean.switch_notify_front_flood_light_zone
    state: "on"
action:
  - service: notify.mobile_app_andrew_s_iphone
    data:
      message: >-
        Person detected in front flood light zone at {{ now().strftime("%-I:%M
        %p") }}.
      title: "Warning: Front flood light"
      data:
        image: >-
          /api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        actions:
          - action: START_FRONT_SIREN
            title: Start siren
            icon: sfsymbols:sun.max.fill
            destructive: true
          - action: IGNORE
            title: Ignore
            icon: sfsymbols:xmark
  - wait_for_trigger:
      - platform: event
        event_type: ios.notification_action_fired
        event_data: {}
    timeout:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
    continue_on_timeout: false
  - choose:
      - conditions: "{{ wait.trigger.event.data.actionName == \"START_FRONT_SIREN\" }}"
        sequence:
          - service: shell_command.front_siren_on
            data: {}
          - service: notify.mobile_app_andrew_s_iphone
            data:
              message: Front siren manually initiated.
              title: "Confirmation: Front siren"
      - conditions: "{{ wait.trigger.event.data.actionName == \"IGNORE\" }}"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 15
              milliseconds: 0
mode: single
```
