### DISCUSSION TITLE
possibility of google drive/dropbox integration?

### DISCUSSION THREAD

**Discussion by Gahrlaag** [blakeblackshear/frigate#4315] [Ideas]
So I was wondering about the possibility to connect frigate to google drive to do an automatic upload of snaps and/or clips as they're recorded. The reasoning is that as some of us are using frigate as an NVR in a home security setup, and storing the clips on, for example a nas, the risk of an intruder actually taking the video/snaps with them is possible. Having it available in drive eliminates the risk of loosing the data.

**Comment by NickM-27** [comment]
Google drive, Dropbox, and others can be mounted as a volume and used as a volume in frigate or have rsync mirror it from a local volume (most likely the recommended approach)

https://www.google.com/amp/s/ubunlog.com/en/how-to-mount-dropbox-folder-as-virtual-filesystem/amp/

**Reply by Gahrlaag** [reply]
I guess it could work but it would be a lot easier (and better imho) to just have it working like googe drive backup for home assistant.

**Reply by NickM-27** [reply]
The google drive backup addon should already support this if frigate is also run as an addon

**Reply by Gahrlaag** [reply]
yeah but what I'm after is basically that frigate stores the snapshots or clips in parallel into google drive. Google drive does indeed support the backup of my entire ha instance, but if someone broke into the house the files wouldn't have been uploaded before the sync occurs. I'm talking on the fly sync, as soon as a new snap is captured

**Comment by subpardaemon** [comment]
just chiming in: i also have this concern. i'm converting from agent dvr, and frigate is eons better in reducing false positives, but this functionality is achingly absent.

i was thinking of using MQTT events, and writing a custom app that uses rclone or something to quickly sync up a recording. however, frigate does not exactly have an MQTT event that tells us when a snapshot or a recording was made. how could this be solved?

**Reply by NickM-27** [reply]
I use rclone for this and haven't had any issues.

If you wanted to do it immediately that would be possible using the mqtt /events

**Reply by subpardaemon** [reply]
so in theory if i start listening to, say `frigate/maincam/person`, each time the count changes from a previous state, i could do a sync. or, even better, `frigate/maincam/person/snapshot`, do an rsync. or should i turn on a flag to sync every 30 seconds until `frigate/maincam/person` decreases to 0? (obviously i'm only interested in person detection, and the system is configured for that.)

**Reply by NickM-27** [reply]
I'd suggest using frigate/events and use the end type

**Reply by subpardaemon** [reply]
if i use the end type, wouldn't this scenario be possible:
- stakeout person constantly in camera (no end event)
- people break in, take the recorder, so nothing gets synced?

i was thinking, instead of waiting for the end:
- i would have an internal table of frigate events that are ongoing, tracked by the `id` ("new" and "update" create or keep them as active, "end" would remove them)
- if the table changes from empty to having at least one item, it schedules a sync every N seconds, with a delay of M seconds for the first
- if the table changes from nonempty to empty, it removes the scheduled sync and does a last sync with a delay of M seconds.

this way if something starts happening rclone would regularly sync until the end of all active events.

**Reply by NickM-27** [reply]
Snapshots are not saved to disc until the event ends recordings are gradually but with a ~ 10 second latency

**Reply by subpardaemon** [reply]
so `frigate/<camera_name>/<object_name>/snapshot` is not concurrent with a snapshot file being written to disk? are they synchronous to end events then?

and according to what you say, the final sync should happen cca 15 seconds after the last event is ended so that everything would be flushed out by then?

makes one wonder if a `frigate/flush` or `frigate/write` event with the file path in it would be worth emitting through mqtt?

**Reply by NickM-27** [reply]
There's already a feature request for an mqtt message when frigate finished writing recordings. 

/frigate/camera/object/snapshot has nothing to do with a snapshot being written to disk

**Reply by subpardaemon** [reply]
ok, so in theory when that feature is implemented i can rely on that -- in the meantime i'll go with the new/update/end events. i'll post the link for the watcher program once i'm done. thanks for the help!

**Reply by ministryofsillywalks** [reply]
> * people break in, take the recorder, so nothing gets synced?
> 
> i was thinking, instead of waiting for the end:
> 
> * i would have an internal table of frigate events that are ongoing, tracked by the `id` ("new" and "update" create or keep them as active, "end" would remove them)

did you ever finish this? I am in the same boat and would love to backup clips to the cloud.

**Comment by GitittomeNow** [comment]
I’ve been doing a lot of research on this. The best solution I found is for a Home Assistant to send the images and videos to Telegram for a real time offsite back up. Everything else requires some kind of sync based on a certain time, at least that I found.

**Reply by justinbyoung** [reply]
I think I found a roundabout way of using rclone via Home Assistant. It uses the downloader integration on Home Assistant. The download folder is a mounted samba share hosted on my Frigate VM. The frigate subfolder in the share is a google drive folder mounted using rclone mount.

I wasn't able to use rclone how I wanted directly on the Home Assistant VM, which is why I send the files back to the Frigate VM as I can use rclone mount there and both are hosted on the same machine.

I adapted the notification script to also download the thumbnail and clip to the rclone folder.

I haven't really tested this much yet but it seems to work.

Here is the HA script I am currently using.

```
alias: Frigate - Upload Test
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - condition: template
        value_template: "{{ trigger.payload_json['after']['camera'] == 'backyard' }}"
action:
  - service: notify.mobile_device
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected on backyard.
      data:
        image: >-
          https://home_assistat_address/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
  - service: downloader.download_file
    data:
      url: >-
        https://home_assistat_address/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
      subdir: frigate
      filename: "{{ now().strftime(\"%d-%m-%Y-%H.%M.%S\") }}.jpg"
  - service: downloader.download_file
    data:
      url: >-
        http://frigate_address:5000/api/events/{{trigger.payload_json["after"]["id"]}}/clip.mp4
      subdir: frigate
      filename: "{{ now().strftime(\"%d-%m-%Y-%H.%M.%S\") }}.mp4"
mode: single
```
