### DISCUSSION TITLE
required_zones: How to only apply it to cars?

### DISCUSSION THREAD

**Discussion by KevinPeters80** [blakeblackshear/frigate#4352] [Ask A Question]
Hi, I have followed this page: https://docs.frigate.video/guides/stationary_objects/ to stop the detection of stationary cars. This is what my relevant config looks like:

```
cameras:
  Driveway:
...
    record:
      events:
        required_zones:
          - Driveway_Entrance_Car_Zone

#Driveway Zones
    zones:
      Driveway_Main_Car_Zone:
        coordinates: 368,360,527,360,640,230,575,187,534,199,439,167,372,140,169,149,127,227,76,360
        objects:
          - car
      Driveway_Entrance_Car_Zone:
        coordinates: 377,142,353,124,177,130,169,153
        objects:
          - car

```
Whilst this does work for cars, it has now stopped people events that don't enter the "Driveway_Main_Car_Zone". How can I make the required_zones rule only apply to cars, or have I misunderstood it?

TIA!
