### DISCUSSION TITLE
Dahua IPC-T5442TM-AS-3.6mm Green Screens, other makes work fine........

### DISCUSSION THREAD

**Discussion by pm1961** [blakeblackshear/frigate#4360] [General]
Hi,
 
 I have Frigate working as a Docker in Unraid.
 
 I have a working Home Assistant VM through Unraid with the Frigate Proxy addon.
 
 Frigate works fine with two other brands of cameras, however my Dahua refuses to do anything else but "green screen". It has previously worked, but I don't know at what point it broke.
 
 I have the simple config below, with no extra hardware arguments.
 The rtsp line works fine with VLC and also within HA using the Custom WebRTC Camera card.
 
 The camera also works fine within a web browser.
 
 Also below are the log lines.
 
 I'm frustrated, so any pointers gratefully received thanks.
 
 Paul
 
  
 
 Garden: #dahua IPC-T5442TM-AS-3.6mm
    ffmpeg:
      inputs:
        # HiRes Stream
        - path: rtsp://admin:xxxxxx@10.10.40.60:554/cam/realmonitor?channel=1&subtype=0
          roles:
          - rtmp
          - record
		  
		  
[2022-11-10 12:48:30] frigate.video                  ERROR   : Garden: Unable to read frames from ffmpeg process.
[2022-11-10 12:48:30] frigate.video                  ERROR   : Garden: ffmpeg process is not running. exiting capture thread...
[2022-11-10 12:48:40] watchdog.Garden                ERROR   : Ffmpeg process crashed unexpectedly for Garden.
[2022-11-10 12:48:40] watchdog.Garden                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-10 12:48:40] ffmpeg.Garden.detect           ERROR   : [rtsp @ 0x55f9f5b06b40] method DESCRIBE failed: 404 Not Found
[2022-11-10 12:48:40] ffmpeg.Garden.detect           ERROR   : rtsp://admin:xxxxxxx@10.10.40.60:554/cam/realmonitor?channel=1&subtype=2: Server returned 404 Not Found
[2022-11-10 12:48:40] frigate.video                  ERROR   : Garden: Unable to read frames from ffmpeg process.
[2022-11-10 12:48:40] frigate.video                  ERROR   : Garden: ffmpeg process is not running. exiting capture thread...

**Comment by NickM-27** [comment]
Something doesn't seem right with the config you're providing. the logs complain of `rtsp://admin:xxxxxxx@10.10.40.60:554/cam/realmonitor?channel=1&subtype=2` which is different than the snippet you provided

**Reply by pm1961** [reply]
Hi, ah, I thought that was because I had a substream entry as well? I didn't include it because I didn't believe it was part of the problem... but here is the entry for that camera............ Thanks for looking.

```yaml
 Garden: #dahua IPC-T5442TM-AS-3.6mm
    ffmpeg:
      inputs:
        # HiRes Stream
        - path: rtsp://admin:xxxxxxx@10.10.40.60:554/cam/realmonitor?channel=1&subtype=0
          roles:
          - rtmp
          - record
        # LowRes Stream 
        - path: rtsp://admin:xxxxxxx@10.10.40.60:554/cam/realmonitor?channel=1&subtype=2
          roles:
          - detect
    detect:
      width: 640
      height: 480
      fps: 5
    rtmp:
      enabled: True
    record:
      enabled: True
      retain:
        days: 1
      events:
        retain:
          default: 3
```
