### DISCUSSION TITLE
Adding timestamp to recording?

### DISCUSSION THREAD

**Discussion by foureight84** [blakeblackshear/frigate#4442] [Ask A Question] [answered]
I was looking through the docs and searched the discussion and perhaps I missed something but I can't seem to find the configuration to add the timestamp to recordings instead of using the timestamp on my camera. Is this possible? I can see the option to add a timestamp to a snapshot but not recordings and live view other than the debug menu.

**Comment by NickM-27** [comment, marked as answer]
Adding timestamps to a recording is very expensive operation as it requires decoding the frames, inserting the timestamp, then re-encoding. Most cameras support this so that is the recommended path. If not, then you can use the `ffmpeg -> output_args` to include a timestamp https://superuser.com/questions/1491264/ffmpeg-filter-to-add-timestamp-on-video

**Reply by foureight84** [reply]
Gotcha. Thanks for clarifying that. I'll stick to using camera timestamp.

**Comment by jljl1337** [comment]
I have to add the timestamp to the recording since I am using a webcam which by itself does not have the timestamp.

This is probably too late, but I figured it out:

```
go2rtc:
  streams:
    usb_camera:
      - ffmpeg:device?video=0&video_size=1280x720#video=h264

cameras:
  usb_camera:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/usb_camera
          input_args: preset-rtsp-restream
          roles:
            - record

ffmpeg:
  output_args:
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vf "drawtext=text='%{localtime}':fontcolor=white:fontsize=24:x=10:y=10:box=1:boxcolor=black@0.5" -c:a aac
```

If anyone managed to add the timestamp in the rtsp stream, please let me know!
