### DISCUSSION TITLE
ffmpeg   Cannot assign requested address

### DISCUSSION THREAD

**Discussion by kryptonneke** [blakeblackshear/frigate#4451] [Ask A Question] [answered]
Hi all, 

I'm trying to run frigate in a docker container on a raspberry PI 4.

Always get these error messages:
```
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-11-20 19:11:32] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-11-20 19:11:32] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-11-20 19:11:32] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-11-20 19:11:32] detector.cpu1                  INFO    : Starting detection process: 210
frigate  | [2022-11-20 19:11:32] frigate.app                    INFO    : Output process started: 212
frigate  | [2022-11-20 19:11:32] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-11-20 19:11:32] frigate.app                    INFO    : Camera processor started for back: 214
frigate  | [2022-11-20 19:11:33] ws4py                          INFO    : Using epoll
frigate  | [2022-11-20 19:11:33] frigate.app                    INFO    : Capture process started for back: 216
frigate  | [2022-11-20 19:11:33] ws4py                          INFO    : Using epoll
frigate  | [2022-11-20 19:11:33] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:11:33] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:11:53] watchdog.back                  ERROR   : Ffmpeg process crashed unexpectedly for back.
frigate  | [2022-11-20 19:11:53] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:11:53] ffmpeg.back.detect             ERROR   : [rtsp @ 0x7d9f00] Unable to open RTSP for listening
frigate  | [2022-11-20 19:11:53] ffmpeg.back.detect             ERROR   : rtsp://user:pass@192.168.1.62:88/videoMain: Cannot assign requested address
frigate  | [2022-11-20 19:11:53] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:11:53] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:12:03] watchdog.back                  ERROR   : Ffmpeg process crashed unexpectedly for back.
frigate  | [2022-11-20 19:12:03] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:12:03] ffmpeg.back.detect             ERROR   : [rtsp @ 0x7fff00] Unable to open RTSP for listening
frigate  | [2022-11-20 19:12:03] ffmpeg.back.detect             ERROR   : rtsp://user:pass@192.168.1.62:88/videoMain: Cannot assign requested address
frigate  | [2022-11-20 19:12:03] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:12:03] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...

```

Docker compose file:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
#    shm_size: "64mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/frigate/config.yml:/config/config.yml:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

config.yml file:
```

mqtt:
  host: 192.168.1.59
  user: mqttuser
  password: password

detectors:
  cpu1:
    type: cpu
    num_threads: 3

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.62:88/videoMain
```
(of course credentials have been redacted)

The raspberry pi is running bullseye 11.5

Note: 
I also have an exact same raspberry pi with homeassistant hasio installed and the exact same config.yml file. That works!
So the path seems to be correct?

when doing a tcpdump on the docker host I can see connections to the mqtt host but NOT to the camera...

camera is a foscam R4M

I did search for the error message, but that points toward the fact that you cannot use localhost.
