### DISCUSSION TITLE
Has anyone managed to get Frigate working with Caddy 2?

### DISCUSSION THREAD

**Discussion by chrislentz** [blakeblackshear/frigate#4525] [Ask A Question] [answered]
I am using Caddy 2 (via https://github.com/lucaslorentz/caddy-docker-proxy) as my Docker reverse proxy. I have it working great for my 10 other containers, but for some reason, the Frigate UI just doesn't want to work with Caddy.

```yaml
# compose.yaml
frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128
    environment:
      - FRIGATE_MQTT_PASSWORD=(redacted)
      - FRIGATE_AMCREST_PASSWORD=(redacted)
      - FRIGATE_EUFY_PASSWORD=(redacted)
    ports:
      - 5000:5000
      - 1935:1935
    networks:
      - caddy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml:ro
      - ./frigate/db:/db
      - ./frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    labels:
      caddy: "frigate.(redacted).com"
      caddy.reverse_proxy: "{{upstreams 5000}}"
      caddy.tls.dns: "route53"
    shm_size: "200mb"
    depends_on:
      - mosquitto
```

I am using this same network and same set of Caddy labels on 10 other containers with no issue. But when I try to access Frigate through https://frigate.(redacted).com, all I get is a 502 Bad Gateway.

Anyone have any theories or thoughts?

**Comment by blakeblackshear** [comment]
I don't see anything obvious, but I use traefik just fine. Can you access the frigate UI without going through the proxy? Wanted to point out that `blakeblackshear/frigate:stable-amd64` no longer points to the latest stable release. Builds are now multiarch, so you should be using `blakeblackshear/frigate:stable`.

**Comment by chrislentz** [comment, marked as answer]
I just upgraded my image. Thanks for the tip on that.

I have been doing some digging and the only things I have found so far.
- The XHR request to `https://frigate.(redacted).com/api/config` fails with a 502 Bad Request
- Looking at the container logs, I did find the below errors:
   ```
   [Errno -3] Temporary failure in name resolution
   [cmd] python3 exited 1
   ```
   
See comment below for solution.

**Reply by blakeblackshear** [reply]
Looks like frigate is failing to start, so the 502 makes sense. That looks like an error when connecting to mqtt.

**Reply by chrislentz** [reply]
Alright. As soon as you said that, a light bulb went off. I added the "caddy" network, which removed it from the default network. I only have UI containers on caddy, which doesn't include my mqtt container. I added the container to both the default and caddy networks and it started working.

```yaml
# compose.yaml
frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128
    environment:
      - FRIGATE_MQTT_PASSWORD=(redacted)
      - FRIGATE_AMCREST_PASSWORD=(redacted)
      - FRIGATE_EUFY_PASSWORD=(redacted)
    ports:
      - 5000:5000
      - 1935:1935
    networks:
      - default
      - caddy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml:ro
      - ./frigate/db:/db
      - ./frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    labels:
      caddy: "frigate.(redacted).com"
      caddy.reverse_proxy: "{{upstreams 5000}}"
      caddy.tls.dns: "route53"
    shm_size: "200mb"
    depends_on:
      - mosquitto
```

Thanks
