### DISCUSSION TITLE
Defining record retention period

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#4528] [Ask A Question]
Which is the proper syntax for retention for recorded files:

```
record:
  enabled: true
  events:
    retain:
      default: 4

OR

record:
  enabled: true
  events:
    retain:
      days: 4
```

My files do not get deleted after 4 days no matter which syntax I use.

Thank you

**Comment by blakeblackshear** [comment]
This is not a valid config. If frigate starts when you use this config, then you may be changing a different file than the one frigate uses when running. It should immediately exit with an error message.

```yaml
record:
  enabled: true
  events:
    retain:
      days: 4
```

**Reply by 18923** [reply]
Sorry that was a cut and paste error, should have been

```
   record:
      enabled: true
        # events:
      retain:
        days: 2
        # mode: motion
```

Hard to keep things straight after having been around the sun 79 times

I'll set up a test machine with a single camera to try and work this out.

Thanks to both of you for the quick response.

**Comment by blakeblackshear** [comment]
By default frigate will retain recordings of events for 10 days and discard recordings not related to events.

```yaml
record:
  enabled: true
  retain:
    days: 0
  events:
    retain:
      default: 10
```

Setting retain -> days will increase the number of days to keep all recordings regardless of events, but will not impact event storage:

```yaml
record:
  enabled: true
  retain:
    days: 4    # <---- keeps all recordings, not just events for 4 days
  events:
    retain:
      default: 10
```

Setting events -> retain -> default will adjust the number of days to keep recordings related to events:

```yaml
record:
  enabled: true
  retain:
    days: 0
  events:
    retain:
      default: 4     # <---- deletes recordings related to events after 4 days 
```
