### DISCUSSION TITLE
Help with notification snapshots

### DISCUSSION THREAD

**Discussion by poblabs** [blakeblackshear/frigate#4545] [Ask A Question] [answered]
Hey there, I'm using MQTT and Node-RED to send me my notifications outside of home assistant. 

One question I have is I'd like the snapshot sent in the notification to have the bounding box burned onto the image. It seems like it only burns the image when the MQTT payload "type" is "end", is that true? Right now I'm firing the notification on "new" and I don't get the image with the box on it. Sometimes it's tough to find the portion of the image which was detected. 

My node-red config is rather basic. Upon new message to `frigate/events`, if the payload type is "new", then grab the snapshot url. Right now the URL I'm using for snapshot is: `'https://mysite/api/frigate/notifications/' + msg.payload.after.id + '/snapshot.jpg'`

My frigate config is really basic too. It's below. 

I guess my question is two fold:
1. Should I be using the "first" type in the payload? If so, how can I have the burned image snapshot available?
2. Or should I just use the "end" type? Is there a significant delay between these 2 payloads? I'm trying to capture the motion asap as it's found

Thoughts?

```
mqtt:
  host: 192.168.0.25
cameras:
  floodlight: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution 
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: True
      clean_copy: False
      bounding_box: True
      retain:
        default: 2 # days
      required_zones:
        - driveway
    motion:
      mask:
        - 0,272,555,269,589,189,681,188,779,260,1142,286,1280,255,1280,0,0,0
    zones:
      driveway:
        coordinates: 1280,720,1280,313,894,305,792,271,705,190,575,209,508,257,263,294,0,435,0,720
        objects:
          - car
          - person
motion:
  improve_contrast: True
 ```
