### DISCUSSION TITLE
Frigate i HA not recording

### DISCUSSION THREAD

**Discussion by KristianT1981** [blakeblackshear/frigate#4551] [General]
I have connected a  TP-link C100 snapshot is working fine and i can watch live video but it is not recording.
My frigate.yml look like this::

```yaml
mqtt:
  host: 192.168.x.x
  user: user
  password: password

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.x.x/x1
          roles:
            -rtmp
            -detect
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    record:
      enable: true
    detect:
      width: 1280
      height: 720
```
