### DISCUSSION TITLE
Hardware Acc w/ nVidia = No running processes found?

### DISCUSSION THREAD

**Discussion by mlg9000** [blakeblackshear/frigate#4566] [Ask A Question]
I have an old Geforce GT 730 running the 470 driver that from that I can tell supports decoding based on "ffmpeg -decoders | grep cuvid" showing h264_cuvid (this card does not show up on the support matrix for decoders).  From what I can also tell I've managed to get it working under docker as I get the same output there.  However, running nvidia-smi either in the container or on the host directly I get "No running processes found".  There are no errors in the container logs but the CPU usage is high still so it doesn't appear hardware decoding is working.  Anyone have any ideas what the issue might be?  Do I need to buy a new card?

**Comment by NickM-27** [comment]
What version of frigate are you running (need the number, not latest)

**Reply by mlg9000** [reply]
I am on 0.11.1

**Reply by NickM-27** [reply]
If the hwaccel wasn't working ffmpeg would crash so it should be doing something. Even without the processes does nvidia-smi show usage on the GPU?

**Reply by mlg9000** [reply]
No usage on the GPU.  The CPU usage is still as high as it previously was before enabling GPU support.

**Reply by NickM-27** [reply]
Can you share your config?

**Reply by mlg9000** [reply]
> Can you share your config?

```yaml
mqtt:
  host: hass.my.domain
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: fakepass
cameras:
  shop_front:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtmp://cam-1.my.domain/bcs/channel0_main.bcs?token=254&channel=0&stream=0&user=user&password=fakepass
          roles:
            - detect
            - rtmp
            - clips
            - record
    detect:
      width: 2560
      height: 1920
      fps: 5
    motion:
      mask:
        - 0,1182,105,934,172,808,266,705,340,687,419,665,483,632,514,592,572,552,622,509,673,434,792,363,835,321,851,210,853,108,904,100,1014,90,1116,81,1196,72,1437,67,1810,89,1994,116,2299,198,2496,0,0,0
        - 997,1920,410,1920,0,1920,0,1412,418,1675
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 1719,1920,959,1920,0,1920,0,1505,0,1123,2071,1184,2053,981,2560,995,2560,1920
            - 2154,291,2126,231,2015,226,1874,219,1748,203,1651,199,1512,182,1377,156,1196,95,1098,0,2560,0,2560,848
            - 505,1102,0,1049,0,120,754,123,869,119,949,152,956,289,942,137,981,209,890,387
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.72
detectors:
  coral:
    type: edgetpu
    device: usb
```
