### DISCUSSION TITLE
Frigate zones suggestions/question

### DISCUSSION THREAD

**Discussion by dnestico** [blakeblackshear/frigate#4577] [Ask A Question] [answered]
**Just trying to optimize frigate as good as it can be to get the fastest detection/notifications and have some questions and thought It would be better to make it a discussion rather then an actual issue.**

**So I have some questions about if I'm doing zones correctly.** 

Here is the 1st zone which is "porch_deck" and I just want to know if the zone should be that whole thing or if should I reduce it to just actual ground and not the walls like it is now?
<img width="823" alt="Screen Shot 2022-12-02 at 11 15 22 AM" src="https://user-images.githubusercontent.com/3034555/205338369-51824c23-fd95-45ec-ae16-ddc3011cd052.png">

Here is zone 2 which is "porch_stairs", pretty much the same question here.
<img width="817" alt="Screen Shot 2022-12-02 at 11 19 14 AM" src="https://user-images.githubusercontent.com/3034555/205338538-ec256c9a-4e0e-4571-bebd-66f0d5329dba.png">

And here are what all my masks look like.
<img width="819" alt="Screen Shot 2022-12-02 at 11 20 25 AM" src="https://user-images.githubusercontent.com/3034555/205338675-81ecf814-d888-47cf-b0ba-fa841c206051.png">
<img width="822" alt="Screen Shot 2022-12-02 at 11 20 09 AM" src="https://user-images.githubusercontent.com/3034555/205338678-4d690ad1-1ea8-4daa-975b-a34b3a818faa.png">
<img width="822" alt="Screen Shot 2022-12-02 at 11 20 18 AM" src="https://user-images.githubusercontent.com/3034555/205338679-f1095190-cc9e-4523-b99e-80cfbd9610b6.png">

Code:

```
porch:
    ffmpeg:
      inputs:
        - path: ****
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    motion:
      improve_contrast: true
      mask:
        - 1403,664,1450,351,1473,0,1920,0,1920,1080,1324,1080
        - 0,504,169,469,441,392,377,0,0,0
        - 192,669,269,835,210,926,30,772,84,620
    zones:
      porch_deck:
        coordinates: 426,1080,485,980,635,982,675,933,605,851,509,619,391,0,1489,0,1442,532,1343,1080
        objects:
          - person
        filters:
          person:
            threshold: 0.75
      porch_stairs:
        coordinates: 578,999,512,1080,144,1080,264,968
        objects:
          - person
        filters:
          person:
            threshold: 0.7
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
        pre_capture: 5
        post_capture: 10
        required_zones:
          - porch_deck
          - porch_stairs
    snapshots:
      enabled: true
      bounding_box: true
      crop: false
      timestamp: false
      retain:
        default: 7 
      required_zones:
        - porch_deck
        - porch_stairs
    mqtt:
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      enabled: true
```
