### DISCUSSION TITLE
Video feed can be "laggy"

### DISCUSSION THREAD

**Discussion by simondrake** [blakeblackshear/frigate#4603] [Ask A Question]
I'm unsure if this is expected behaviour, but I'm curious if there's anything I can do to improve it if it's not. When I view my cameras live feeds through either Home Assistant (using the Frigate card) or the Birdseye view of the Frigate UI, the feed is "laggy" (for want of a better word).

For example, if somebody is walking in view of the camera, it's not a smooth video. It halts for a few milliseconds and then catches up, then halts again etc etc. 

If I use VLC to use the RTSP stream directly to the camera, there is no lag whatsoever. 

The logs don't indicate anything is going wrong, other than the odd `Discarding a corrupt recording segment` warning, and the warnings related to using CPU detectors. 

The following is my config file:

```yaml
mqtt:
  host: <host>
  user: <user>
  password: <password>

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

objects:
  track:
    - person
    - car

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

snapshots:
  timestamp: True
  bounding_box: True

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: <stream>
          roles:
            - record
        - path: <stream>
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    rtmp:
      enabled: True
    # Only include the camera in Birdseye view when objects are detected
    birdseye:
      mode: objects
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
  side_garden:
    ffmpeg:
      inputs:
        - path: <stream>
          roles:
            - record
        - path: <stream>
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    rtmp:
      enabled: True
    # Only include the camera in Birdseye view when objects are detected
    birdseye:
      mode: objects
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
  back_garden:
    ffmpeg:
      inputs:
        - path: <stream>
          roles:
            - record
        - path: <stream>
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    rtmp:
      enabled: True
    # Only include the camera in Birdseye view when objects are detected
    birdseye:
      mode: objects
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
  drive:
    ffmpeg:
      inputs:
        - path: <stream>
          roles:
            - record
        - path: <stream>
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    rtmp:
      enabled: True
    # Only include the camera in Birdseye view when objects are detected
    birdseye:
      mode: objects
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 10
```

The CPUs do have a fairly high inference speed, but I'm assuming that's normal as it's all CPU bound and there's no Google Coral in the mix.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/62928647/205629973-d46284a3-c0e8-49a1-85ca-178fdcca82cf.png">
