### DISCUSSION TITLE
Recordings don't get produced for H265 stream mixed with H264 using nvidia acceleration

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#4658] [Ask A Question] [answered]
Hello,

I am having the exact same issue as https://github.com/blakeblackshear/frigate/discussions/2624 but the issue was left unresolved. I get the same error messages and same symptoms. I have a reolink camera who's main stream is h265 (unchangeable) and a secondary stream that is h264. I would like to record the h265 stream and use the h264 for the rest. Everything works fine except that no recordings for that specific camera are generated in the "recordings" folder, and of course none are viewable in the UI. 

I have nvidia acceleration enabled like this:

[docker-compose.yml]
```yml
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.1
    shm_size: "1024mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nvme-data/frigate/config.yml:/config/config.yml:ro
      - /mnt/beast/frigate/data:/media/frigate
      - /mnt/nvme-data/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 10000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - FRIGATE_RTSP_PASSWORD=xxxx
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
  
    # frigate nvidia acceleration
    deploy:  
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

[frigate-config.yml]
```yml
ffmpeg:

  # nvidia acceleration
  hwaccel_args: -c:v h264_cuvid

  # enable audio
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```

As shown the acceleration is tuned globally for h264 (`hwaccel_args: -c:v h264_cuvid`) so it seems I need to specify `hevc_cuvid` somewhere. I tied under the specific camera:

```yml
  lightwall-maison:
    ffmpeg:    
      hwaccel_args: -c:v hevc_cuvid #<---------------------------------
      inputs:
        - path: rtsp://un:pw@192.168.23.19:554/h265Preview_01_main
          roles:
            - record
        - path: rtsp://un:pw@192.168.23.19:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
                           
    detect:
      width: 640
      height: 360            
    ui:
      order: 3
```

But that made the whole camera stop working and it doesn't seem right anyway since it's not specified for a specific record stream. 

How do you specify h265 for a single specific stream?

Unrelated but maybe related, if I do nvidia-smi in the docker container `docker exec -it frigate nvidia-smi` I get no processes:

![image](https://user-images.githubusercontent.com/118814/206814129-74c1817f-3812-4807-a527-1693f875c9b5.png)

However if I simply do `nvidia-smi` in the OS itself I do get processes:

![image](https://user-images.githubusercontent.com/118814/206814182-1ac28137-5686-4eb0-8c3b-60c31c6cbf5f.png)

Is this strange?

Any help would be appreciated.

**Comment by NickM-27** [comment, marked as answer]
Just set the args per stream

```yaml

lightwall-maison:
    ffmpeg:    
      inputs:
        - path: rtsp://un:pw@192.168.23.19:554/h265Preview_01_main
          roles:
            - record
          hwaccel_args: -c:v hevc_cuvid
        - path: rtsp://un:pw@192.168.23.19:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
          hwaccel_args: -c:v h264_cuvid
                           
    detect:
      width: 640
      height: 360            
    ui:
      order: 3
```

Also that nvidia-smi behavior is expected https://github.com/NVIDIA/nvidia-docker/issues/179#issuecomment-645579458
