### DISCUSSION TITLE
How to use the Google Coral Cam 5MP

### DISCUSSION THREAD

**Discussion by Redsandro** [blakeblackshear/frigate#4698] [General]
I'm using the official [Google Coral Cam 5MP](https://coral.ai/docs/camera/datasheet/) camera connected via MIPI-CSI to an [Asus Tinker Edge T](https://tinker-board.asus.com/product/tinker-edge-t.html) running Frigate on Mendel Linux with docker.

I can get any remote camera to work with Frigate using the documented [examples](https://docs.frigate.video/configuration/camera_specific/). It's pretty straightforward.
However, I can't seem to get the locally attached official Coral Cam to work. It is attached to `/dev/video1`.

```yml
cameras:
  coral:
    ffmpeg:
      inputs:
        - path: /dev/video1
          roles:
            - detect
          input_args:
            - -f
            - video4linux2
            - -input_format
            - h264
            - -video_size
            - 1280x720
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - 1
 ```

I'm getting the following error:

```
ffmpeg.coral.detect ERROR: [video4linux2,v4l2] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
ffmpeg.coral.detect ERROR: /dev/video1: Invalid argument
```

So just for debugging purposes and having merely a slight hint of knowing what I am doing, I check those commands outside of Frigate in Mendel:

```bash
$ v4l2-ctl -d /dev/video1 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 720x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 2592x1944
			Interval: Discrete 0.067s (15.000 fps)
		Size: Discrete 0x0

$ ffmpeg -f v4l2 -input_format h264 -pix_fmt yuyv422 -i /dev/video1 -c:v copy -f mp4 file.mp4
[video4linux2,v4l2] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
# (Seems like the same error message. Let's add pix_fmt.)

$ ffmpeg -f v4l2 -input_format h264 -pix_fmt yuyv422 -i /dev/video1 -c:v copy -f mp4 file.mp4
[video4linux2,v4l2] Cannot find a proper format for codec 'none' (id 0), pixel format 'yuyv422' (id 1)
```

And idea where I'm going wrong in my approach?

Secretly I assumed it would be the other way around; easily use the local camera, and harder to use the remote cameras. :sweat_smile:

**Comment by NickM-27** [comment]
There's no way the hardware camera is presenting the feed as h264 which is of course why v4l2 is needed. Recommend looking up how to use ffmpeg with webcam

**Reply by Redsandro** [reply]
Oops I always assumed the camera module contained some chips to do h264 encoding. So this happens on the GPU in stead. Makes sense.

So I guess it's unlucky that the Vivante GC7000Lite GPU on the Tinker Edge T development board does not do hardware encoding. While I believe the Broadcom VideoCore IV on a $5 Raspberry Pi Zero W does. 😂

**Reply by NickM-27** [reply]
It is possible that can be done but it certainly would be done in a different way than accessing the webcam device directly

**Comment by NickM-27** [comment]
Can also reference https://github.com/blakeblackshear/frigate/issues/1184 which has a good example

**Reply by Redsandro** [reply]
Thanks. Using your hints, I've managed to get _one single frame_ using the following config:

```yml
  coral:
    ffmpeg:
      inputs:
        - path: /dev/video1
          roles:
            - detect
          input_args: -f v4l2 -input_format yuyv422 -video_size 640x480 make_zero -fflags +genpts+discardcorrupt -strict experimental -use_wallclock_as_timestamps 1
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
    detect:
      width: 640
      height: 480
      fps: 5
```

After seeing one frame, I get the following error:

```
watchdog.coral      ERROR   : Ffmpeg process crashed unexpectedly for coral.
watchdog.coral      ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ffmpeg.coral.detect ERROR   : Finishing stream 0:0 without any data written to it.
ffmpeg.coral.detect ERROR   : Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
```

Interestingly, the Google Coral Camera is now softbricked and cannot be used in any capacity until I reboot the Asus Tinker Edge T dev board.

I guess I can forget about the frigate `record` or `rtmp` role using this camera. The Vivante GC7000 Lite GPU doesn't support hardware encoding so I need to use the slow software libx264 encoder. It was a really really bad choice for this [Google Coral Dev Board](https://coral.ai/products/dev-board#tech-specs), or the version from its [official partner](https://developers.googleblog.com/2022/05/coral-googles-platform-for-edge-ai.html), the [Asus Tinker Edge T](https://tinker-board.asus.com/product/tinker-edge-t.html). Better off buying the USB Coral to use with Raspberry Pi. Cheaper also.

**Comment by Redsandro** [comment]
Ah, I get a consistent stream now using this configuration. Very big CPU load compared to other cameras even without record/encode. It semi-persistently crashes on `docker-compose restart`; I guess the ffmpeg thread cannot end gracefully leaving the camera in a broken state.

```yml
cameras:
  coral:
    ffmpeg:
      inputs:
        - path: /dev/video1
          roles:
            - detect
          input_args: -f v4l2 -input_format yuyv422 -video_size 640x480 -framerate 30 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        detect:
          - -f
          - rawvideo
          - -pix_fmt
          - yuv420p
    detect:
      width: 640
      height: 480
      fps: 1
```

Opening issue here: #4711
