### DISCUSSION TITLE
Recording not working

### DISCUSSION THREAD

**Discussion by the1robbo** [blakeblackshear/frigate#4720] [Ask A Question]
Hi,

My config is below...

```yaml
cameras:
    Garden_Front:
        ffmpeg:
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: http://192.158.x.x/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=admin&password=x
              roles:
                - record
                - rtmp
            - path: http://192.168.x.x/flv?port=1935&app=bcs&stream=channel1_ext.bcs&user=admin&password=x
              roles:
                - detect
        detect:
          width: 2560
          height: 1440
          fps: 30
        record:
          enabled: True
          retain:
            days: 60
            mode: motion
          events:
            retain:
              default: 60
              mode: active_objects
              objects:
                  dog: 2
                  car: 7
            pre_capture: 5
            post_capture: 5
            objects:
                - person
                - car
```

I am wanting to record 24/7 but then went motion is detected, show the clip 5 seconds before the motion was detected.

Is this available at all please?
Thanks

**Comment by NickM-27** [comment]
You're running detect on the main stream at 30 fps, this is most likely unnecessary and we recommend against doing that. Is there a reason you're doing that?

And when you say motion, do you mean object detection or general motion?

**Reply by the1robbo** [reply]
I'm using reolink cameras and thought I had to do the same as what was on the reolink app. What is good enough to view the recording if needed please?

Object detection please. Only after certain objects.

**Reply by NickM-27** [reply]
Please read the docs. You should use the substream for detection and the full resolution for recording

https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others shows this exactly

**Reply by the1robbo** [reply]
done that. I think I put the ip address down wrong, I'll soon see later.

Any way to sort out the recording regarding object detection?

**Reply by NickM-27** [reply]
> Any way to sort out the recording regarding object detection?

What exactly is not working the way you want? It's not clear to me, your config currently is set to record 60 days of 24/7 and keep 60 days of events (objects)

**Reply by the1robbo** [reply]
sorry -  I am looking to record 24/7 on but then went motion is detected, when you view the clip, it goes back 5 seconds before the motion was detected.

**Comment by NickM-27** [comment]
```yaml
        record:
          enabled: True
          retain:
            days: 60
            mode: all
          events:
            retain:
              default: 60
              mode: all
              objects:
                  dog: 2
                  car: 7
            pre_capture: 5
            post_capture: 5
```

Will do that for you
