### DISCUSSION TITLE
Retains 10 days of recordings despite 3 or 7 days in config for each camera

### DISCUSSION THREAD

**Discussion by max-christian** [blakeblackshear/frigate#4782] [Ask A Question] [answered]
Can anyone help me understand why the config below results in Frigate keeping 10 days of recordings rather than the 3 or 7 configured for each camera? I want to retain all video for the specified period, not just motion. Thanks!

```
mqtt:
  host: localhost
  topic_prefix: frigate
  client_id: frigate
cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.52/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.0.52/Streaming/Channels/101
          roles:
            - record
    detect:
      width: 704
      height: 576
      max_disappeared: 50
    record:
      enabled: True
      retain:
        days: 7
        mode: all
    zones:
      doorbell:
        coordinates: 0,73,0,576,704,576,704,0,208,0,211,135,44,208,36,62
  Patio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.53/Streaming/Channels/102
          roles:
            - rtmp
            - detect
        - path: rtsp://admin:@192.168.0.53/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: false
    record:
      enabled: True
      retain:
        days: 3
        mode: all
  Side:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.139/Streaming/Channels/102
          roles:
            - rtmp
            - detect
        - path: rtsp://admin:@192.168.0.139/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: false
    record:
      enabled: True
      retain:
        days: 3
        mode: all
  Bins:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.192/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
            - detect
        - path: rtsp://admin:@192.168.0.192/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: false
    record:
      enabled: True
      retain:
        days: 7
        mode: all
  Rear:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.0.133/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
            - detect
        - path: rtsp://admin:@192.168.0.133/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: false
    record:
      enabled: True
      retain:
        days: 3
        mode: all
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
motion:
  improve_contrast: True

```

**Comment by NickM-27** [comment, marked as answer]
This is because you have not configured the amount of days to keep event recordings (`record -> events -> retain -> default`) which defaults to 10. You have setup 24/7 recordings and the events recording is a separate setting

**Reply by max-christian** [reply]
Thanks, I appended the below to the config and it's not working yet but hopefully will kick in soon!

```
record:
  enabled: True
  events:
    retain:
      default: 3


```
