### DISCUSSION TITLE
Frigate failing to start - timed out - python3 exited 1

### DISCUSSION THREAD

**Discussion by jmemax** [blakeblackshear/frigate#4805] [Ask A Question]
Hello -

Sorry, I know this issue seems to come up from time to time, but looking over those issues I wasn't able to resolve anything based on their issues.

I had frigate running on a Rpi3 B+ and have been working to move it over to a bare metal install - but I seem to be running into an issue I cannot resolve.  I'm running frigate standalone without HA.

The computer is an older Intel 82Q33 board, running a core 2 duo Q9400.

  `Model name:           Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz`

OS is Ubuntu Server 22.04.1 LTS - fresh install.

Looking at my issue I've seen other recommendations in the discussions that maybe its the MQTT broker, but I'm not sure what would be wrong?

**Docker Compose**

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/--username-removed--/docker-compose/frigate/frigate.yml:/config/config.yml:ro
      - /home/--username-removed--/docker-compose/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "--password-removed--"
```

**Frigate Config**

```yaml
mqtt:
  host: --subdomain-removed--.s2.eu.hivemq.cloud
  port: 8883
  user: --username-removed--
  password: --password-removed--
detectors:
  cpu1:
    type: cpu
    num_threads: 2
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://--camera-info-removed--:88/videoMain
          roles:
            - detect
    detect:
      width: 1280
      height: 720
logger:
  default: debug
  logs:
    frigate.event: debug
```

**Frigate Log**

```
frigate    | [2022-12-28 23:38:29] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate    | Starting migrations
frigate    | [2022-12-28 23:38:29] peewee_migrate                 INFO    : Starting migrations
frigate    | [2022-12-28 23:38:29] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate    | [2022-12-28 23:38:29] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate    | There is nothing to migrate
frigate    | [2022-12-28 23:38:29] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | timed out
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-12-28 23:38:41] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate    | Starting migrations
frigate    | [2022-12-28 23:38:41] peewee_migrate                 INFO    : Starting migrations
frigate    | [2022-12-28 23:38:41] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate    | [2022-12-28 23:38:41] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate    | There is nothing to migrate
frigate    | [2022-12-28 23:38:41] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | timed out
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.`

Every so often, and rarely though (1 in 20 startup error messages), I get this error:

`frigate    | There is nothing to migrate
frigate    | [2022-12-28 22:46:20] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | timed out
frigate    | [2022-12-28 22:46:25] frigate.mqtt                   ERROR   : Unable to connect to MQTT server: timed out
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
```

Which indicates an error here -

**edited**

Sorry, looks like I was looking at the wrong file -

https://github.com/blakeblackshear/frigate/blob/master/frigate/mqtt.py

Line 278

` try:
        client.connect(mqtt_config.host, mqtt_config.port, 60)
    except Exception as e:
        logger.error(f"Unable to connect to MQTT server: {e}")
        raise`

Which throws me off because it seems pretty cut and dry error, but I've confirmed that my MQTT settings are correct, at least as far as I can tell.  As a test I was able to send out a message directly to HiveMQ from the box

`mosquitto_pub -h --subdomain-removed--.s2.eu.hivemq.cloud -p 8883 -t frigate -m Test -u "--username-removed--" -P "--password-removed--"`

And did confirm that HiveMQ did receive the message.  I'm not seeing any activity in HiveMQ for Frigate though.

Oddly this is the same config/host/user/password that I was using for the RPI that was working.

Is there a reason that I am getting different error messages, or is there somewhere else in the logs I can look, or other logs elsewhere that I am missing to help me debug this?  Do I need to open a port for 8883?

I've tried varying config settings, verified my url to the camera works in VLC.  

Maybe its having an issue with my CPU as the detector?  I can't seem to locate other settings that replace the /dev/dri/renderD128 setting, or is there only one for CPU?

I would appreciate any help!
