### DISCUSSION TITLE
Problems using docker compose sample in docs

### DISCUSSION THREAD

**Discussion by Drizzt321** [blakeblackshear/frigate#4814] [Ask A Question]
So I'm trying to setup Frigate separate from HA so I can have a separate data 'drive'. My system is FreeBSD host, HA running as a HassOS VM image, Frigate will be running in a VM with latest Debian. I grabbed the Docker Compose sample from the *Docker* section, and put my own settings in.

I've got the Coral Dual Edge via PCIe Passthru into the Debian VM, which Debian see it and has the drivers/etc installed successfully.

The Docker yml I'm using is:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/frigate/conf/frigate/yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /media/frigate/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "<PASSWORD>"
```
When I try and run it, here is what I get:

```
$ docker-compose -f docker.yml up
ERROR: Version in "./docker.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

When I comment out the `version` line at the top, I get:

```
$ docker-compose -f docker.yml up
ERROR: The Compose file './docker.yml' is invalid because:
Unsupported config option for services: 'frigate'
```

But I have no clue what might be invalid in there.

**Comment by NickM-27** [comment]
Based on the log, try putting the version as "3.3" instead. Otherwise, the docker compose may not be up to date in your VM.

**Reply by Drizzt321** [reply]
@NickM-27 I've got the latest docker from the Debian 11.6/bullseye repo/Docker repo installed. 

```
$ docker-compose  version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```

So unless there's a newer version that's not even in the [docker apt repo](https://docs.docker.com/engine/install/debian/#set-up-the-repository), I dunno. 

I verified that Docker runs fine for the user via `docker run hello-world`, so that's fine.

When I try and run it with version 3.3 as you suggest, I get the following error

```
ERROR: The Compose file './docker.yml' is invalid because:
services.frigate.volumes contains unsupported option: 'tmpfs'
```

**Reply by NickM-27** [reply]
not sure then, not had any users run into this AFAIK. Seems different approaches https://stackoverflow.com/questions/42139982/version-in-docker-compose-yml-is-unsupported-you-might-be-seeing-this-error to solve

**Reply by Drizzt321** [reply]
@NickM-27 looks like `docker-compose` is the old, and `docker compose` with the compose plugin is the newer way to do things, and that seemed to start things up correctly. Well, until I get some frigate config errors, but I suspect what I had from the HA settings that worked, are actually missing some things, so I'll start poking at that independently. 

Frigate Docker installation certainly directions could use at least a _tiny_ bit of information as to suggested/possible docker invocation commands IMO.

**Reply by NickM-27** [reply]
Sure, they are very dependent on the install though. For example, if you install docker desktop then `docker-compose` is the correct command (which is the case on my dev mac). I'm sure they could be more clear, but it is not as simple as "these are the right ones"

**Reply by Drizzt321** [reply]
Jeeze, really? Ugh. Didn't realize Docker had so much craziness. 

Can't figure out my frigate config issue now, getting this from docker. Can't see what the error might be. Worked when I gave it a quick try as HomeAssistant Frigate install/Add-On to give it a try. Unfortunately HA doesn't handle a secondary storage/media drive, super annoying, but outside of this discussion.

```
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | [2022-12-29 11:19:28] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | ***    Your config file is not valid!                     ***
frigate  | ***    Please check the docs at                           ***
frigate  | ***    https://docs.frigate.video/configuration/index     ***
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Config Validation Errors                           ***
frigate  | *************************************************************
frigate  | [Errno 21] Is a directory: '/config/config.yml'
frigate  | Traceback (most recent call last):
frigate  |   File "/opt/frigate/frigate/app.py", line 332, in start
frigate  |     self.init_config()
frigate  |   File "/opt/frigate/frigate/app.py", line 82, in init_config
frigate  |     user_config = FrigateConfig.parse_file(config_file)
frigate  |   File "/opt/frigate/frigate/config.py", line 934, in parse_file
frigate  |     with open(config_file) as f:
frigate  | IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
frigate  |
frigate  | *************************************************************
frigate  | ***    End Config Validation Errors                       ***
frigate  | *************************************************************
```

My frigate.yml is
```
mqtt:
  host: homeassistant
  user:  frigate
  password: <PASSWORD>

detectors:
  cpu1:
    type: cpu
    num_threads: 2
    
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 10
      mode: active_objects
      
cameras:
  alley_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:<PASSWORD>@10.30.255.244/stream1 # 640x480 25fps
          roles:
            - detect
        - path: rtsp://admin:<PASSWORD>@10.30.255.244/stream0 # 1920x1080 10fps
          roles:
            - rtmp
            - record
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 25
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
```
