### DISCUSSION TITLE
How do I stop a particular camera from tracking objects?

### DISCUSSION THREAD

**Discussion by simondsmason** [blakeblackshear/frigate#4821] [Ask A Question] [answered]
I have four cameras that I don't want to detect objects on.  I see that the default is person, and I am getting events.  But how do I stop it detecting objects on these cameras?  Thanks.

**Comment by NickM-27** [comment, marked as answer]
If you don't want to detect at all then just disable detect

```yaml
cameras:
  camera:
    detect:
      enabled: false 
```
