### DISCUSSION TITLE
object detected in zone restricted to not include that object type

### DISCUSSION THREAD

**Discussion by jsbowling42** [blakeblackshear/frigate#4823] [Ask A Question] [answered]
I'm having an issue where an person object is detected in a zone that is restricted to object types excluding "person". I'm not sure if I'm just setting this up incorrectly or not. any help would be appreciated. 

event snapshot: 
![image](https://user-images.githubusercontent.com/35424582/210085435-dfd5c199-50aa-4120-a4e9-4664ee5aedb2.png)
zone snapshot:
![image](https://user-images.githubusercontent.com/35424582/210085517-23872573-8892-432a-bcb0-ba19b5bbfbe1.png)
code:

```yaml
cameras:
  driveway_cam:
    rtmp:
      # Optional: Enable the RTMP stream (default: True)
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 2048
      height: 1536
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          mask: 
            - 0,0,572,0,2048,0,1846,144,1887,195,1862,342,1855,420,1606,345,1408,300,1209,265,990,244,753,345,336,575,238,648,0,595
          threshold: 0.7
        cat:
          mask: 
            - 0,0,572,0,2048,0,1846,144,1887,195,1862,342,1855,420,1606,345,1408,300,1209,265,990,244,753,345,336,575,238,648,0,595
          threshold: 0.7
        car:
          mask:
            - 0,0,572,0,2048,0,1846,144,1887,195,1862,342,1856,405,1823,550,1780,526,1713,508,1643,481,1552,446,1489,416,1451,366,1426,327,1207,297,1194,307,1135,338,1073,357,984,360,895,372,764,443,628,556,523,654,473,705,417,738,322,838,255,894,0,1175,0,595
          threshold: 0.7
        person:
          mask:
            - 0,0,572,0,2048,0,1846,144,1887,195,1862,342,1856,405,1606,345,1408,300,1209,265,990,244,753,345,336,575,238,648,0,595
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
    record:
      enabled: True
      retain:
        days: 7
        mode: active_objects
      events:
        required_zones:
          - driveway_entrance
          - side_yard
          - front_yard
          - driveway
        retain:
          default: 7
          mode: active_objects
    zones:
      driveway_entrance:
        coordinates: 1135,347,1455,389,1427,353,1410,330,1183,296,1169,331
        objects:
          - person
          - dog
          - cat
          - car
      driveway:
        coordinates: 0,1536,2048,1536,2048,1242,2048,1139,2048,1065,2048,1043,2048,1016,2048,983,2027,952,2009,916,1970,867,1941,808,1906,750,1887,707,1870,666,1822,645,1804,622,1793,592,1804,568,1808,544,1780,538,1744,526,1688,505,1634,487,1558,454,1486,426,1463,399,1121,354,1064,362,1014,369,972,366,928,375,835,405,433,726,0,1177
        objects:
          - dog
          - cat
      side_yard:
        coordinates: 0,1178,74,1077,184,971,293,858,399,738,492,673,576,605,663,537,737,481,799,437,878,390,923,378,995,367,1043,365,1085,361,1141,345,1180,316,1194,289,1169,283,1141,276,1111,271,1073,265,1037,260,998,254,954,271,912,283,830,325,741,356,667,393,593,424,166,684,0,602
        objects: 
          - person
          - dog
          - cat
      front_yard:
        coordinates: 1598,353,1830,421,1841,441,1834,477,1822,519,1796,543,1750,529,1703,517,1641,488,1579,466,1557,452,1503,429,1474,413,1444,370,1409,316
        objects: 
          - person
          - dog
          - cat
```
[FrigateCode.txt](https://github.com/blakeblackshear/frigate/files/10325287/FrigateCode.txt)

**Comment by NickM-27** [comment]
Can you include a screenshot of the actual detection in the events page? 

I think you may just be misunderstanding, an event snapshot does not get saved at the time that the object enters a particular zone, they are somewhat random. So just because the event snapshot shows that does not mean the object was considered part of that zone

**Comment by jsbowling42** [comment, marked as answer]
@NickM-27 this what you mean?
![image](https://user-images.githubusercontent.com/35424582/210086775-1ca441de-6361-4f8a-9e6c-b4565b483d01.png)

**Reply by NickM-27** [reply]
yes, it looks like your problem is that you didn't set `required_zones` for snapshot. You only set it for record

**Reply by jsbowling42** [reply]
Ah! thanks! is there a `required_zones` list in the parent camera object to use it as a "global" for that camera?

**Reply by NickM-27** [reply]
no it just needs to be set in both places

**Reply by jsbowling42** [reply]
@NickM-27 getting an error:
![image](https://user-images.githubusercontent.com/35424582/210091480-873a33eb-fc5d-4a9b-8e3d-1489378168ca.png)

changed snapshots to this:
```yaml
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
      events:
        required_zones:
          - driveway_entrance
          - side_yard
          - front_yard
          - driveway
```

**Reply by NickM-27** [reply]
it is just

```yaml
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
      required_zones:
        - driveway_entrance
        - side_yard
        - front_yard
        - driveway
```
