### DISCUSSION TITLE
Camera with auto-tracking records choppy

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#4829] [Ask A Question]
I have a Reolink RLC-823A which has auto-tracking where a motor moves to follow subjects as they cross the frame. The video looks great in birds-eye, however when I go to recordings the image is broken with artifacts and sometimes half-recorded, then corrects itself, then broken again, especially when it moves:

![image](https://user-images.githubusercontent.com/118814/210107988-17ac6f18-e8e1-4c91-96fe-e84c64d5fde3.png)

Is there any way to fix this?

**Comment by NickM-27** [comment]
need to include your config? Sounds like classic reolink rtsp issue and why we highly recommend using the http-flv source instead

**Reply by thinkloop** [reply]
Thank you for your help.

I just saw this page: https://docs.frigate.video/configuration/camera_specific/

I updated my settings to match. Live stream and birdseye work, however in recordings only "snapshot" is available with "clip" greyed out. This is likely due to this error in the docker logs which I am unsure how to fix:

```
frigate        | [2022-12-30 15:40:36] ffmpeg.lightwall-maison.record_rtmp ERROR   : Codec AVOption flags () specified for input file #0 (http://192.168.23.19/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some decoder which was not actually used for any stream.
````

Config:

```
cameras:
  lightwall-maison:
    ffmpeg:   
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"    
      inputs:
        - path: http://192.168.23.19/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxxx
          hwaccel_args: -c:v hevc_cuvid
          roles:
            - record
            - rtmp
        - path: http://192.168.23.19/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx
          roles:
            - detect
                           
    detect:
      width: 640
      height: 360       
      fps: 7
    ui:
      order: 3
```

**Reply by NickM-27** [reply]
maybe try setting the hwaccel_args for that role as `[]` as hwaccel isn't used for record anyway. I'm not familiar with that error so not really sure

**Reply by thinkloop** [reply]
I will continue to update findings here for others. Disabling `hwaccel_args` had no effect. I did find that VLC does not play the record link but does play the detect link, which matches what I am experiencing. Perhaps the url structure is different for this camera, I am investigating. One thing to note is that the main stream on this camera is h265 while the secondary stream is h264.

**Reply by thinkloop** [reply]
The interwebs seems to think that my problems are due to the reolink firmware, especially for the new h265 streams. I am back to my previous settings except with "fluency first" and "Interframe Space 1x" and the following input_args:

```
  lightwall-maison:
    ffmpeg:   
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M 
```

I had to remove the `- -rw_timeout` `- "5000000"` option, ffmpeg complained that it didn't know what it was. Let's see if there is improvement.
