### DISCUSSION TITLE
New to Frigate. Secondary SSD...

### DISCUSSION THREAD

**Discussion by rucanunes** [blakeblackshear/frigate#5003] [General]
I'm running HA Supervised on Debian Linux 11 Bullseye on a NUC i5.

1. I would like to "tell" frigate to record all media in disk sd1 directory "mnt/media". Is this possible?
![1](https://user-images.githubusercontent.com/44728693/211636796-e0897f9a-db33-4270-b8d3-e20d9f936563.png)

3. How can I reduce the video quality for Fully Kisok only? My tablets (Galaxy A7) are having trouble displaying the video.

4. I have a USB Coral in my NUC. Is this config ok?

```
mqtt:
  host: 192.168.0.x
  port: 1883
  user: xxxxxx 
  password: xxxxxxxxxxxxxxx
  topic_prefix: frigate
  client_id: frigate

# ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p


snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 0

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

cameras:

# Câmara da Porta
  porta:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxx@192.168.0.xxx:554/av_stream/ch0
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    motion:
      mask:
        - "931,720,916,119"
        - "870,720,924,410"
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2

# Câmara do Ginásio
  ginasio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxxxx@192.168.0.xxx:554/av_stream/ch0
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2

# Câmara do Terraço
  terraco:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxx@192.168.0.xxx:554/av_stream/ch0
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2

# Câmara do Hall r/c
  hall_rc:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxxx@192.168.0.xxx:554/av_stream/ch0
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2

# Câmara do Hall 1º
  hall_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxxxxx@192.168.0.xxx:554/av_stream/ch0
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2
```

I've read a bunch of stuff about Frigate but I cannot find the answers for these questions.
I don't even know if I'm taking advantage of the USB Coral CPU.

I would be very grateful if someone could help me configure it.
