### DISCUSSION TITLE
Zones and objects

### DISCUSSION THREAD

**Discussion by Mustang1966** [blakeblackshear/frigate#502] [Ask A Question]
I don't want my cars to be detected at my parking space, only persons. Can i exclude objects to be detected in a specific zone? 

I tried the filter option with only the person option, but it still sends notification that a car is detected.

**Comment by RealKanashii** [comment]
Just use the "-person" filter and delete the "-car" option inside the configuration if it's configured: 

```
# Optional: Global object filters for all cameras.
# NOTE: can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person     # <--- Use only this one.
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: max_int)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.85
```

**Reply by RealKanashii** [reply]
If it still detecting then look for your specific camera definition: there's an override option. Look for a "object" string that is not in the root level. You will find the override "object" definition inside the "camera" object.

Mind the spaces in your config, this object is related to "camera object" not "root object". 

I point it as is defined in the main example:

```
    # Optional: Camera level object filters config. If defined, this is used instead of the global config.
    objects:
      track:
        - person
        - car #<------------------- Here
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
```

Comment the "-car" track object.

**Comment by Mustang1966** [comment]
Thanks for the reply. 

I want it to detect cars, only not in the zone 'Parking'. Removing the -car won't detect cars in other zones defined for that camera.

**Reply by RealKanashii** [reply]
In you camera config put two zone definitions (one look for cars, the other no) inside you camera configuration, one with the car label and another without it ( you can still add other labels like dog, person, etc).

Example (don't use exactly as you need to define the coordinates):

```
cameras:  
  parking_camera:
      # all camera config here
 # Optional: zones for this camera
    zones:    # zones definition
      # Required: name of the zone
      # NOTE: This must be different than any camera names, but can match with another zone on another
      #       camera.
      parking_zone: # <--- your defined parking zone which don't want to detect cars.
        # Required: List of x,y coordinates to define the polygon of the zone.
        # NOTE: Coordinates can be generated at https://www.image-map.net/
        coordinates: xxx,xxxx,xxx,xxx,xxx,xxx # <-- Follow tutorial to make get the coordinates. The areas definition must no overlap
        # Optional: Zone level object filters.
        # NOTE: The global and camera filters are applied upstream.
        filters:
          person: # <---- Put person, dog, cat or any other "label" but (except) car.
            min_area: 5000
            max_area: 100000
            threshold: 0.8
      non_parking_zone: # <--- your defined zone (parking which don't want to detect cars
        # Required: List of x,y coordinates to define the polygon of the zone.
        # NOTE: Coordinates can be generated at https://www.image-map.net/
        coordinates: xxx,xxxx,xxx,xxx,xxx,xxx # <-- Follow tutorial to make get the coordinates. The areas definition must no overlap 
        # Optional: Zone level object filters.
        # NOTE: The global and camera filters are applied upstream.
        filters:
          car:  # <---- Here you neeed to put "car" if you want to look for car outside the parking zone.
            min_area: 5000
            max_area: 100000
            threshold: 0.8
          person:  # <---- you can add other object to look for outside the parking zone. 
            min_area: 5000
            max_area: 100000
            threshold: 0.8
```

Tell me if it worked for you.

**Reply by LeifSbr** [reply]
i've done something similar - i just filtered it out in the template condition in the home assistant automation.

create an automation with mqtt trigger for frigate/events. add a new condition with condition type template. then just punch this in the value template field (edit according to your zone/object labels):
`{{ ('zone_frontyard' in trigger.payload_json['after']['entered_zones']) and (trigger.payload_json['after']['label'] == 'person') }}`

good luck (:

**Reply by smartelnovo** [reply]
@Mustang1966 did you figure out a way to use the filters in your zones? I could not get this to work. I used the example that @RealKanashii suggested, but it still detects cars in the parking zone, 

I would rather stop the detection at the source, than filter out the alerts fro HA

**Reply by Mustang1966** [reply]
Yes, from my config. It's important to mask a whole area(see screenshot), not just the car(s)

```
objects:
      track:
        - person
        - car
        - truck
      filters:
        car:
          mask:
            - 2465,515,2572,526,2688,587,2688,710,2564,687,2375,539
          min_area: 5000
          max_area: 24000000
          min_score: 0.8
          threshold: 0.6
        person:
          min_area: 50
          max_area: 24000000
          min_score: 0.8
          threshold: 0.6
```
![Knipsel](https://user-images.githubusercontent.com/43118018/116852589-e22e7f00-abf4-11eb-8004-494f2044d77d.PNG)
