### DISCUSSION TITLE
Any reason to use CPU detector vs OpenVINO CPU?

### DISCUSSION THREAD

**Discussion by leccelecce** [blakeblackshear/frigate#5034] [General]
From what I can see on a Xeon E3, the OpenVINO detector in CPU mode is much faster (4-10x) than the "testing only" default CPU detector.

Is there any reason to use the original CPU detector over the OpenVINO one? I am thinking of considerations like accuracy, range of object types recognised, scalability etc.

I will be doing some basic testing in my own environment but not knowing much about models I am curious as to whether there are any key points to be aware of.

**Comment by NickM-27** [comment]
There will be differences between the models accuracy, speed, etc. but probably nothing big. They're trained on the same dataset just with different parameters.

**Comment by dev77-07** [comment]
I've been running with the OpenVino CPU detector on my Haswell era I5 since it doesn't support the OpenVino GPU detector without issue for a few months now.

**Comment by krk628** [comment]
In my experience the out of box CPU detector puts far more load on my i7-3930K (6 core/12 thread Haswell).  Recently switched to OpenVino w/the mobilenet-ssd model (only need person, dog, car classes).

So far so good; Frigate normally consumes 1 of 6 cores on that i7.

```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/mobilenet-ssd.xml

model:
  width: 300
  height: 300
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: ssd
  labelmap_path: /openvino-model/voc_20cl_bkgr.txt
```

![2023_02_09_10_19_55_Admin_Dashboards](https://user-images.githubusercontent.com/19540206/217889658-2fdd3a1b-6822-4d5c-aa6f-06fd35e94e8f.png)
