### DISCUSSION TITLE
Failed docker-compose, "No space left on device"?

### DISCUSSION THREAD

**Discussion by capnjip** [blakeblackshear/frigate#5059] [Ask A Question] [answered]
Hello all,

I am trying to get this up and running on a Debian server. I'm hoping that someone can point me to what I'm doing wrong. This is my result of $sudo docker-compose up:
![error](https://user-images.githubusercontent.com/96850819/212218930-511ba7bf-2cdd-4ee0-a2d0-307992bc071d.PNG)

here is my drive space:
![df -h output](https://user-images.githubusercontent.com/96850819/212219056-5e943920-24e4-41a6-ab50-1d3ff7f5e32f.PNG)

here is my docker-compose.yml, if that could be useful:
![compose](https://user-images.githubusercontent.com/96850819/212219277-39197abd-5c1c-4270-98ce-0ded51e5b3c8.PNG)

I'm certain that this is above my understanding, any help would be appreciated.

**Comment by NickM-27** [comment]
No space on device in this case is referring to RAM not disk, what device are you running on?

If I had to guess you're using a Pi and you haven't allocated enough ram to the GPU

**Reply by capnjip** [reply]
Hi Nick,

It's actually an old, cobbled-together Dell Optiplex 7010. 
![free](https://user-images.githubusercontent.com/96850819/212356501-f3ca45cb-9417-4363-b8fb-999ed40f1d84.PNG)

Do i need to allocate more to swap? FYI, I am currently running ZoneMinder on this box (and that's all). I'm guessing that's what is eating all my "Mem".

I just looked at the minimum requirements for Frigate and it's looking for minimum 4G Ram. My 1.6G Free/3.6G available is probably the problem?

**Reply by NickM-27** [reply]
I think that's a reasonable place to start and see if that helps

**Comment by capnjip** [comment]
I went ahead and killed the ZoneMinder and it freed up a lot of memory:
![kill zmc](https://user-images.githubusercontent.com/96850819/212386532-8f7e0644-8309-4bb0-b109-47da57f06b4d.PNG)

"sudo docker-compose up" yields the same result as original post. 

Any other ideas?

**Reply by NickM-27** [reply]
Maybe try increasing shm size, otherwise would like to see your actual frigate config.

**Comment by capnjip** [comment]
I tried increasing SHM to 256, but didn't change anything. This is obviously my first attempt with frigate, so I'm fully expecting issues here. Happy hunting! 

frigate.yml:

`## First install, 08Jan2022. Following https://www.digimoot.com/frigate-nvr-linux-manual-install/

```yaml
mqtt:
  host: 192.168..xx.xx
  user: mqtt
  password: <password omitted here>

detectors:
  coral:
    type: edgetpu
    device: pci:0

cameras:
## Required: name of the camera
  sidedoor:
## Required: width of the frame for the input with the detect role
    width: 640
## Required: height of the frame for the input with the detect role
    height: 480
## Optional: desired fps for your camera for the input with the detect role
## NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
##       Frigate will attempt to autodetect if not specified.
    fps: 5
## Required: ffmpeg settings for the camera
    ffmpeg:
## Optional: camera specific global args (default: inherit)
      global_args:
## Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args:
        - -hwaccel_output_format
        - yuv420p
## Optional: camera specific input args (default: inherit)
      input_args:
        - -avoid_negative_ts
        - make_zero
## Optional: camera specific output args (default: inherit)
      output_args:
## Required: A list of input streams for the camera. See documentation for more information.
      inputs:
## Required: the path to the stream
## NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        - path: rtmp://192.168.xx.xx/bcs/channel0_sub.bcs?channel=0&stream=0&user=<user omitted>&password=<omitted>
## Required: list of roles for this stream. valid values are: detect,record,clips,rtmp
## NOTICE: In addition to assigning the record, clips, and rtmp roles,
## they must also be enabled in the camera config.
          roles:
            - detect
            - rtmp
        - path: rtmp://192.168.xx.xx/bcs/channel0_main.bcs?channel=0&stream=0&user=<omitted&password=<omitted>
          roles:
            - clips
## Optional: stream specific global args (default: inherit)
          global_args:
## Optional: stream specific hwaccel args (default: inherit)
          hwaccel_args:
## Optional: stream specific input args (default: inherit)
          input_args:
## Optional: camera level motion config
#    motion:
## Optional: motion mask
## NOTE: see docs for more detailed info on creating masks
#      mask: 0,900,1080,900,1080,1920,0,1920
 
## Optional: timeout for highest scoring image before allowing it
## to be replaced by a newer image. (default: shown below)
      best_image_timeout: 60
 
## Optional: zones for this camera
#    zones:
## Required: name of the zone
## NOTE: This must be different than any camera names, but can match with another zone on another
##       camera.
#      front_steps:
## Required: List of x,y coordinates to define the polygon of the zone.
## NOTE: Coordinates can be generated at https://www.image-map.net/
#        coordinates: 545,1077,747,939,788,805
## Optional: Zone level object filters.
## NOTE: The global and camera filters are applied upstream.
#        filters:
#          person:
#            min_area: 5000
#            max_area: 100000
#            threshold: 0.7

## Optional: Camera level detect settings
    detect:
## Optional: enables detection for the camera (default: True)
## This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
## Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

## Optional: save clips configuration
    clips:
## Required: enables clips for the camera (default: shown below)
## This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
## Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 10
## Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 10
## Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - dog
        - cat
## Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
## Optional: Camera override for retention settings (default: global values)
      retain:
## Required: Default retention days (default: shown below)
        default: 10
## Optional: Per object retention days
        objects:
          person: 15
          dog: 15
          cat: 15

## Optional: 24/7 recording configuration
    record:
## Optional: Enable recording (default: global setting)
      enabled: False
## Optional: Number of days to retain (default: global setting)
      retain_days: 15

## Optional: RTMP re-stream configuration
    rtmp:
## Required: Enable the live stream (default: True)
      enabled: False

## Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
## Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
## This value can be set via MQTT and will be updated in startup based on retained value
      enabled: False
## Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
## Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
## Optional: crop the snapshot (default: shown below)
      crop: False
## Optional: height to resize the snapshot to (default: original size)
      height: 175
## Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
## Optional: Camera override for retention settings (default: global values)
      retain:
## Required: Default retention days (default: shown below)
        default: 10
## Optional: Per object retention days
#        objects:
#          person: 15

## Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
## Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
## NOTE: Only applies to publishing image data to MQTT via 'frigate///snapshot'.
## All other messages will still be published.
      enabled: True
## Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
## Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
## Optional: crop the snapshot (default: shown below)
      crop: True
## Optional: height to resize the snapshot to (default: shown below)
      height: 270
## Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

## Optional: Camera level object filters config.
#    objects:
#      track:
#        - person
#        - car
#        - dog
#        - cat
## Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
## Checks based on the bottom center of the bounding box of the object.
## NOTE: This mask is COMBINED with the object type specific mask below
#      mask: 0,0,1000,0,1000,200,0,200
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          min_score: 0.5
#          threshold: 0.7
## Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
## Checks based on the bottom center of the bounding box of the object
#          mask: 0,0,1000,0,1000,200,0,200`
```
