### DISCUSSION TITLE
Birdseye is great is their a plan to make full screen use the entire screen.

### DISCUSSION THREAD

**Discussion by vjmaz** [blakeblackshear/frigate#5061] [Ask A Question]
Birdseye is great is their a plan to make full screen use the entire screen.
I was was wandering if the full screen can use the entire screen when in full screen mode please .
Currently i have been changing sizes of the output in birdseye to try get best fit , but their is always spaces on the left and right !.
can or will this be removed so the full screen can be a true full screen please .

as I use Birdseye on a spare monitor to watch all cameras at once .  ( testing at the moment as my NVR is too old and broke down but Frigate works well with IP cams Direct using two TPU on older laptop :) ) 

![image](https://user-images.githubusercontent.com/81817593/212237449-6b1b9061-587e-4837-8141-2380fac11732.png)

**Comment by NickM-27** [comment]
It depends on the resolution of your cameras and the resolution you have set for birdseye. It goes full screen for my usage.

**Reply by vjmaz** [reply]
Thank you NickM-27   what have you set the Birdseye view width and height on yours I have tried many different sizes , but cant get the left and right on my screen shot with yellow through them removed

**Reply by NickM-27** [reply]
You can put your config back I will show you how to fix it

**Reply by vjmaz** [reply]
```yaml
# Optional: birdseye configuration
birdseye:
# Optional: Enable birdseye view (default: shown below)
  enabled: True
# Optional: Width of the output resolution (default: shown below)
  width: 1408
# Optional: Height of the output resolution (default: shown below)
  height: 1152
# Optional: Encoding quality of the mpeg1 feed (default: shown below)
# 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
# Optional: Mode of the view. Available options are: objects, motion, and continuous
#   objects - cameras are included if they have had a tracked object within the last 30 seconds
#   motion - cameras are included if motion was detected in the last 30 seconds
#   continuous - all cameras are included always
  mode: continuous
```
