### DISCUSSION TITLE
MQTT Motion detection change in 8.0 beta 3

### DISCUSSION THREAD

**Discussion by mattheys** [blakeblackshear/frigate#508] [General]
Hi all,

In 7.3 and before, Motion detection was a simple true or false, this worked well with HA as you could setup the sensor as follows.

```yaml
binary_sensor:
  - name: Camera Person Garage
    platform: mqtt
    state_topic: "rockfrigate/garage/person"
    device_class: motion
    availability_topic: "rockfrigate/available"
    unique_id: "camera_person_garage"
```

Now it comes through as a count, this is nice and I like that it's available, but the previous method allowed me to expose it to Alexa via https://www.home-assistant.io/integrations/alexa.smart_home/ and it would appear as a motion sensor allowing me to create Alexa routines to do something like telling me there is someone at the front door if they step in a zone.

I'm not looking to ask to revert it but to see if anyone knows of a way to add a HA configuration so that it works the same as before, e.g. can I create a different type of binary_sensor so if count > 0 it's true otherwise false?

I'd like to do it all in HA but I can think of a way to do it Node Red if all else fails.

Cheers in advance.

**Comment by mattheys** [comment]
A very nice person on the HA forum has helped me so I'm posting here in case anyone else was using the 'motion' sensor with Alexa or anything else. It's the last 3 lines that make it work, payload_on, payload_off and value_template.

```yaml
binary_sensor:
  - name: Camera Person Garage
    platform: mqtt
    state_topic: "rockfrigate/garage/person"
    device_class: motion
    availability_topic: "rockfrigate/available"
    unique_id: "camera_person_garage"
    payload_on: true
    payload_off: false
    value_template: '{{ value | int > 0 }}'

```
