### DISCUSSION TITLE
(0.12-beta4) New ReoLink config for the age of go2rtc?

### DISCUSSION THREAD

**Discussion by jonadis** [blakeblackshear/frigate#5143] [Ask A Question] [answered]
Looking at the beta docs:
[https://deploy-preview-4055--frigate-docs.netlify.app/configuration/camera_specific/#reolink-cameras](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/camera_specific/#reolink-cameras)
I see the ReoLink specific config still mentions RTMP...
```
          roles:
            - record
            - rtmp
        - path: ...
```
Is that just the best we can hope for since ReoLink (at least the 410) cameras are terrible at stable RTSP feeds?
Or does that section of the doc need updated to reflect the new go2rtc way of doing things?
I tried changing it around on my own, and I came up with this, but it doesn't seem to work:
```
go2rtc:
  streams:
    ...
    garage_se: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
    garage_se_sub: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
    garage_sw: http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
    garage_sw_sub: http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
   
cameras:
  ...
  garage_se:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_se
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_se_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ...
  garage_sw:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_sw
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sw_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    ...
```

**Comment by NickM-27** [comment, marked as answer]
```yaml
go2rtc:
  streams:
    ...
    garage_se: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
    garage_se_sub: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
    garage_sw: http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
    garage_sw_sub: http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted
```

should work fine you just need to use `ffmpeg:`

```yaml
go2rtc:
  streams:
    ...
    garage_se: ffmpeg:http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted#video=copy#audio=copy#audio=opus
    garage_se_sub: ffmpeg:http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted#video=copy#audio=copy#audio=opus
    garage_sw: ffmpeg:http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted#video=copy#audio=copy#audio=opus
    garage_sw_sub: ffmpeg:http://10.0.71.161/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted#video=copy#audio=copy#audio=opus
```
