### DISCUSSION TITLE
how does frigate config overwrite work?

### DISCUSSION THREAD

**Discussion by alez007** [blakeblackshear/frigate#5163] [Ask A Question] [answered]
Hey, sorry if this has been answered before, couldn't find a proper answer about it. 

I'm trying to figure out how frigate config overwrite works. For example, I've got a global objects filter:

```
objects:
  track:
    - person
    - cat
  filters:
    person:
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.70
      threshold: 0.70
    cat:
      min_score: 0.70
      threshold: 0.70
```

then I'm overwriting it on camera level:
```
cameras:
  camera1:
    objects:
      filters:
        person:
          min_ratio: 0.5
          max_ratio: 2.0
          threshold: 0.65
          min_area: 4000

```

the camera overwrite doesn't have `min_score` or `max_score` defined, will it take those values from the global config ? E.g. will the global config merge with the camera level config therefore resulting into:

```
    person:
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.70
      threshold: 0.65
      min_area: 4000
```

Thanks
