### DISCUSSION TITLE
Events are recognized outside from desired Zone

### DISCUSSION THREAD

**Discussion by snoozeghub** [blakeblackshear/frigate#5164] [General]
Hello to all Frigate User,

I configured following Zone for my parking area.

![image](https://user-images.githubusercontent.com/114864549/213449846-e3b2601a-1898-4002-b5f9-445f5f642b3b.png)

If a car or person drives past / walks by on the street, an event is triggered.
In the documentation I read following sentence:

Presence in a zone is evaluated based on the bottom center of the bounding box for the object

In the debug mode I can't see that the bottom center of the bounding box touches the marked zone.

Here you can see a person walking by "outside of the zone" and an event is triggered.

![image](https://user-images.githubusercontent.com/114864549/213452166-71345129-3f5d-448c-a854-9f56d7239e41.png)

What I'm doing wrong or misunderstood?

Best Regards
René

frigate.yml for this Cam looks like this:

```yaml
carport:
    ffmpeg:
      inputs:
              # High Resulution Stream
        - path: rtsp://userandpwd@192.168.178.42:554/11
          roles:
            - record
            # Low Resulution Stream
        - path: rtsp://userandpwd@192.168.178.42:554/12
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False
    detect:
      width: '640' 
      height: '352' # <---- update for your camera's resolution
      fps: 15
      stationary:
        interval: 0
        threshold: 50
        max_frames:
          default: 3000
          objects:
            car: 1000
    snapshots:
      enabled: True
      retain:
        default: 2
      required_zones:
        - parked
    record:
      enabled: True
      retain: 
        days: 2
        mode: active_objects
      events:
        retain:
          default: 2 
          mode: active_objects
        required_zones:
          - parked 
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones:
        - parked
    zones:
      parked:
        coordinates: 0,193,376,74,640,157,554,352,0,352
        objects:
          - person
          - car
        filters:
          car:
            min_area: 70000
            max_area: 100000
            threshold: 0.7  
    motion:
      mask:
        - 640,43,640,0,410,0,410,30
        - 640,282,640,352,588,352,595,311
```

**Comment by NickM-27** [comment]
The snapshot for the event won't necessarily be from the moment the object entered the zone. I can easily see how that person walking by would be in the zone though as the bottom center of the bounding box is already really close (right on the edge of) the zone.

**Reply by snoozeghub** [reply]
Hello NickM

thank you for your fast reply.
I cut now the zone back to half.

![image](https://user-images.githubusercontent.com/114864549/213461603-fa3c7ee2-ce2e-4a1f-a9f6-05a4e1040eeb.png)

But still events were recognized.
It seem that not only the bottom center of the bounding box will trigger an event for my opinion it is also the corner / edges of the bounding box.

**Reply by NickM-27** [reply]
> It seem that not only the bottom center of the bounding box will trigger an event for my opinion it is also the corner / edges of the bounding box.

that is incorrect. This logic has not changed for some time and works as expected. I don't see any example of an object that triggered this event, so no way to know what happened there without more info

**Reply by snoozeghub** [reply]
It is really hard to capture in debug mode.

I could capture in debug mode a car passing by (red arrow).

![image](https://user-images.githubusercontent.com/114864549/213464418-bba0dec2-e76f-4f8e-af79-133b14261a92.png)

For my understanding the defined zone is far away from the bounding box.

**Reply by NickM-27** [reply]
I'm not sure what you mean, there are 3 cars in the zone.

**Reply by snoozeghub** [reply]
Here I found in events under clips the movie I captured the car. :-)

![image](https://user-images.githubusercontent.com/114864549/213465355-cdb3f88b-2808-46d7-8a65-dda325a40ee5.png)

**Reply by NickM-27** [reply]
Frigate's tracking is currently not very sophisticated, this means that when multiple objects of the same type are close together and if they overlap, the IDs for these objects can be switched so frigate thinks the car driving by was the one parked. 


The fact that you have

```yaml
         max_frames:
          default: 3000
          objects:
            car: 1000
```

in your config is only going to make this worse

we are looking to improve this in a future version

**Reply by snoozeghub** [reply]
> I'm not sure what you mean, there are 3 cars in the zone.

From the left to right the first two cars are my parked cars.
When a car or a person drives / walks by the bounding boxes outside of my cars appear.

I meant the blue box with the red arrow. I couldn't capture it the car was gone.


> Frigate's tracking is currently not very sophisticated, this means that when multiple objects of the same type are close together and if they overlap, the IDs for these objects can be switched so frigate thinks the car driving by was the one parked.
> 
> The fact that you have
> 
> ```yaml
>          max_frames:
>           default: 3000
>           objects:
>             car: 1000
> ```
> 
> in your config is only going to make this worse
> 
> we are looking to improve this in a future version


Okay, can you give me a hint what I can do to do it better?
Just deleting this part in my config?

**Reply by NickM-27** [reply]
yes, by having max_frames you are forcing frigate to forget known objects. Then when motion happens near it (like a car driving by) these cars will be detected again for the first time which increases the odds that they have IDs switched.

**Reply by snoozeghub** [reply]
Thank you Nick, I will try and see what happens after deleting this config part. 
I thought it has only to do with stationary objects.

**Reply by NickM-27** [reply]
> I thought it has only to do with stationary objects.

well, those cars are stationary. as soon as the car is considered stationary for 200 seconds you are telling frigate to forget they exist. That setting is really only there for objects that are not actually cars

**Reply by snoozeghub** [reply]
After deleting the max_frames: section in my config file it is different. Since yesterday in Events it is displaying "IN Progress".
Watching the Clip shows again cars and people passing by on the street.

![image](https://user-images.githubusercontent.com/114864549/213632808-93d5f53f-d0e3-481f-ad06-2a734afe9a82.png)

Shouldn't Frigate recognize that the parked cars are stationary, even if new motion is detected and object detecting is starting again.
Or is this issue explained with your statement above?
If objects of the same type are close together and they overlap, the IDs for these objects can switch or do they switch?

> Frigate's tracking is currently not very sophisticated, this means that when multiple objects of the same type are close together and if they overlap, the IDs for these objects can be switched so frigate thinks the car driving by was the one parked.
> 
> The fact that you have
> 
> ```yaml
>          max_frames:
>           default: 3000
>           objects:
>             car: 1000
> ```
> 
> in your config is only going to make this worse
> 
> we are looking to improve this in a future version

The other thing is about the required_zones  the bottom center of the bounding box of the new detected objects are not touching the defined zone.
As far as I understood from the documentation, no event recording should take place.

**Reply by blakeblackshear** [reply]
Those cars are still in view, so they are being tracked and "in progress". This is the intended behavior. While objects are being tracked, any motion that occurs anywhere in the frame will be retained. 

Do you have separate events in your events list for the cars and people passing on the street? I don't see any.

**Reply by snoozeghub** [reply]
Thank you Blake for explanation. 
Does this mean when "in progress" is displayed it is recording the whole time?
Now it is 20:30 local time and I still see one event still "in progress" it is from 16:38.
When will this stop?

<img width="397" alt="image" src="https://user-images.githubusercontent.com/114864549/213788440-eb95e478-8c64-41c3-98d6-d29f2bae15df.png">

First I thought it is solved but then I found new events.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/114864549/213787286-0e2eca6d-d7a1-4b4f-a9eb-67922ebed58b.png">

Here you see on the other side of the road a car driving.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/114864549/213787689-e16dfc35-6574-48ab-8261-5fcddc0264cf.png">

I watched today the debug mode a long time the bottom center of the bounding box is not touching the defined zone.

**Reply by NickM-27** [reply]
> Thank you Blake for explanation. Does this mean when "in progress" is displayed it is recording the whole time? 

No, when recordings are saved depends on your recording retention policy https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

> Now it is 20:30 local time and I still see one event still "in progress" it is from 16:38. When will this stop?

when the object is no longer visible

**Reply by snoozeghub** [reply]
Okay this is why I choose active_objects. I read the policy:

With the active_objects it would only keep segments where the object was active. In this case the only segments that would be saved would be the ones where the car was driving up, you going inside, you coming outside, and the car driving away. Essentially reducing the 4 hours to a minute or two of event footage.

The documentation dosen't say anything about the object has to be no longer visible.

What is about the other question from Blake with my new events and  the car driving by.

**Reply by NickM-27** [reply]
> The documentation dosen't say anything about the object has to be no longer visible.

An event is "in progress" as long as the object is visible. "In progress" has nothing to do with whether or not the recordings are being saved, that's the point being made. 

> I watched today the debug mode a long time the bottom center of the bounding box is not touching the defined zone.

The silver car is inside the zone and that's what the event is of. 

> What is about the other question from Blake with my new events and the car driving by.

Not sure what you're referring to

**Reply by snoozeghub** [reply]
That an event was triggered with a car driving by on the street and the bottom center of the bounding box is not touching the defined zone.

![image](https://user-images.githubusercontent.com/114864549/213795367-7351a8e9-fed6-407d-8152-a6a8c3e33149.png)

**Reply by NickM-27** [reply]
> That an event was triggered with a car driving by on the street and the bottom center of the bounding box is not touching the defined zone.

the picture you are showing, both of those cars, the bottom center of the bounding boxes are inside the zone

![213795367-7351a8e9-fed6-407d-8152-a6a8c3e33149](https://user-images.githubusercontent.com/14866235/213796160-709bbab2-9a53-4a9a-90f4-677c86239ab5.png)

**Reply by NickM-27** [reply]
the fact that it was caused by a car driving by is just because the car driving by caused motion, but the snapshot is of the car which is parked because that is what the event is referring to

**Reply by snoozeghub** [reply]
Hello Nick, thank you for your response. In this short discussion I learned a lot about frigate and the AI.
I'm now a little bit confused.
The Zone in the picture is a required_zone and I see that the bottom center of the bounding boxes are inside the zone.
These two cars standing their the whole night and most of the day.
So Frigate AI should know they are stationary objects because they aren't moving at all.

The documentation says:

- Sometimes you want to limit a zone to specific object types to have more granular control of when events/snapshots are saved. The  
   following example will limit one zone to person objects and the other to cars.

- Only car objects can trigger the front_yard_street zone and only person can trigger the entire_yard. You will get events for person  
  objects that enter anywhere in the yard, and events for cars only if they enter the street.

These two cars are not entering the required_zone they are already in this zone (stationary objects).

I recognized that cars or people using the street or the sidewalk will trigger the required zone.
(Or like you explained the cars that are already parked in the required_zone due to motion in the screen)
**In the debug view in my example the bounding box of the moving object person or car, only the right side or one side of the bottom line of the bounding box triggers an event.
Not the "red square" center of the bounding box.**

I thought I can reduce with Frigate AI events that are recorded.
My "old" Camera has a motion detection build inside of its OS.
This records only a lot of events when it is raining or in this season when it is snowing.

Maybe you can help me with config improvement or you consider to take a look into this part of Frigate code maybe you finde something what can lead to this behavior.

**Reply by NickM-27** [reply]
> These two cars are not entering the required_zone they are already in this zone (stationary objects).

Frigate won't start the event until there's motion by these objects but yet it'll create an event because they are inside the zone.

> Not the "red square" center of the bounding box.

The red box is the motion box which IS NOT considered for the zone. It is the object bounding boxes which are considered for the zone. Perhaps this is where your confusion is stemming from. 

> I thought I can reduce with Frigate AI events that are recorded.
My "old" Camera has a motion detection build inside of its OS.
This records only a lot of events when it is raining or in this season when it is snowing.
> 
> Maybe you can help me with config improvement or you consider to take a look into this part of Frigate code maybe you finde something what can lead to this behavior.

I mean frigate won't be recording rain or other things like that. It's not really clear what behavior you're referring to. As has been said previously the event being in progress doesn't mean it's being recorded constantly. 

Frigate currently does not have a way to only save recording segments of the specific object that caused the event when it comes to stationary objects, that would be a feature request.

**Reply by snoozeghub** [reply]
Dear Nick I think we are talking past each other. 


> > These two cars are not entering the required_zone they are already in this zone (stationary objects).
> 
> Frigate won't start the event until there's motion by these objects but yet it'll create an event because they are inside the zone.
> 
> > Not the "red square" center of the bounding box.
> 
> The red box is the motion box which IS NOT considered for the zone. It is the object bounding boxes which are considered for the zone. Perhaps this is where your confusion is stemming from.
> 
I meant that red box you put to my picture to show me the bottom center of the bounding box.

I changed my setup after your explanation.
The 2 cars aren't anymore in the required_zone "parked".
My intention is to get notified only when the car leaves the parked zone.
But Frigate should record every event when a person walks around in the paring area.

![image](https://user-images.githubusercontent.com/114864549/213990154-667ad940-4d37-4d61-878f-e0042ddfbf6c.png)

The yellow Zone is the complete Zone to recognize persons.

> > I thought I can reduce with Frigate AI events that are recorded.
> > My "old" Camera has a motion detection build inside of its OS.
> > This records only a lot of events when it is raining or in this season when it is snowing.
> > Maybe you can help me with config improvement or you consider to take a look into this part of Frigate code maybe you finde something what can lead to this behavior.
> 
> I mean frigate won't be recording rain or other things like that. It's not really clear what behavior you're referring to. As has been said previously the event being in progress doesn't mean it's being recorded constantly.
> 
It does:
![image](https://user-images.githubusercontent.com/114864549/213989286-4fc22f07-f771-4b2d-bc10-c8f2025163ce.png)

Rain the whole night:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/114864549/213989713-de984b29-5ea7-4816-bc69-378b0dd82ee0.png">

The recording stoped after 1 hour and the second black car had a bounding box around with "car".

As you can see the bottom center of the bounding box is not in the defined zone "parked".
Do you now understand what I'm talking about?

> Frigate currently does not have a way to only save recording segments of the specific object that caused the event when it comes to stationary objects, that would be a feature request.

Where can I issue this as a feature request? Do you have a list or system where user can place this?

Thank you for your patience and answering my questions.
Kind Regards
René

**Reply by NickM-27** [reply]
You need to share your config file otherwise there's no way for me to know what your setup actually is and how it's behaving. 

> > Frigate currently does not have a way to only save recording segments of the specific object that caused the event when it comes to stationary objects, that would be a feature request.
> 
> Where can I issue this as a feature request? Do you have a list or system where user can place this?

Create a feature request issue in the issue section of this GitHub repo.

**Reply by snoozeghub** [reply]
Here is my config


```yaml
mqtt:
  host: 192.168.xxx.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60
#Detectors
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

#Global Object Settings
objects:
  track:
    - person
    - car
ffmpeg:
  hwaccel_args: -c:v h264_qsv
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1

cameras:
  Frontdoor:
    ffmpeg:
      inputs:
        # High Resulution Stream
        - path: rtsp://user:password@192.168.xxx.xxx:xxx/11
          roles:
          - record
        # Low Resulution Stream
        - path: rtsp://user:password@192.168.xxx.xxx:xxx/12
          roles:
          - detect
          - rtmp
    restream:
      enabled: false
      force_audio: false
    rtmp:
      enabled: False 
    detect:
      width: '640' 
      height: '352' # <---- update for your camera's resolution
      fps: 15
    snapshots:
      enabled: True
      retain:
        default: 2
      required_zones:
        - door4a
        - driveway4b
    record:
      enabled: True
      retain: 
        days: 2
        mode: active_objects
      events:
        retain:
          default: 2
          mode: active_objects
        required_zones:
          - door4a
          - driveway4b
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones:
        - door4a
        - driveway4b
    zones:
      door4a:
        coordinates: 39,351,523,352,435,291,189,264,41,280
        objects:
          - person
      driveway4b:
        coordinates: 209,135,310,192,490,166,455,124,473,86,494,29,188,43
        objects:
          - person
          - car
        filters:
          car:
            min_area: 30000
            max_area: 100000
            threshold: 0.7 
    motion:
      mask:
        - 468,184,520,154,640,189,634,307,522,322,485,294,467,265
        - 176,252,270,255,232,225,218,192,175,155,130,178,143,234
        - 639,0,498,6,550,41,591,136,640,174
  carport:
    ffmpeg:
      inputs:
              # High Resulution Stream
        - path: rtsp://user:password@192.168.xxx.xxx:xxx/11
          roles:
            - record
            # Low Resulution Stream
        - path: rtsp://user:password@192.168.xxx.xxx:xxx/12
          roles:
            - detect
            - rtmp
    restream:
      enabled: false
      force_audio: false
    rtmp:
      enabled: False
    detect:
      width: '640' 
      height: '352' # <---- update for your camera's resolution
      fps: 15
      stationary:
        interval: 0
        threshold: 50
    snapshots:
      enabled: True
      retain:
        default: 2
      required_zones:
        - parked
        - complzone
    record:
      enabled: True
      retain: 
        days: 2
        mode: active_objects
      events:
        retain:
          default: 2 
          mode: active_objects
        required_zones:
          - parked
          - complzone
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones:
        - parked
        - complzone
    zones:
      parked:
        coordinates: 327,149,473,41,563,59,388,180,143,352,0,352
        objects:
          - car
        filters:
          car:
            min_area: 70000
            max_area: 100000
            threshold: 0.7
      complzone:
        coordinates: 501,0,0,253,0,352,619,352,640,36
        objects:
          - person
        filters:
          person:
            threshold: 0.7       
    motion:
      mask:
        - 640,43,640,0,410,0,410,30
        - 640,282,640,352,588,352,595,311
  ```
        

The above described problems are with the carport cam.
