### DISCUSSION TITLE
Frigate works in close collab with BlueIris and PIR sensors to trigger highres recording

### DISCUSSION THREAD

**Discussion by tubalainen** [blakeblackshear/frigate#517] [Show and tell]
I am using Frigate to trigger my BlueIris instance. This is being done via an automation in Home Assistant that triggers highres recording in BlueIris via the HTTP endpoint of blue iris.

Ive got nine cameras and I do not use all of them with Frigate (I do not have that computing power to spare).
I also combine Frigate with two PIR sensors (shelly switch) to help with other movments than humans (person)

Here is an Home Assistant example automation if anyone´s interested.

```
- id: cam1_3_9_person_detected_send_bi
  alias: "Frigate Cam 1 3 9 Framsidan BI"
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.cam1_framsidan_frigate_person
    platform: state
    to: 'on'
  - entity_id: binary_sensor.cam3_framsidan_frigate_person
    platform: state
    to: 'on'
  - entity_id: binary_sensor.cam9_uppfart_frigate_person
    platform: state
    to: 'on'
  - entity_id: binary_sensor.cam9_uppfart_frigate_car
    platform: state
    to: 'on'
  - entity_id: binary_sensor.shelly_11_switch
    platform: state
    to: 'on'
  - entity_id: binary_sensor.shelly_19_switch
    platform: state
    to: 'on'
  condition: []
  action:
    - service: shell_command.alert_bi
      data:
        url: 'http://192.168.1.xx:81/admin?trigger&camera=cam9_hd&user=mmhm&pw=bleh'
    - service: shell_command.alert_bi
      data:
        url: 'http://192.168.1.xx:81/admin?trigger&camera=cam3_hd&user=mmhm&pw=bleh'
    - service: shell_command.alert_bi
      data:
        url: 'http://192.168.1.xx:81/admin?trigger&camera=cam1_sd&user=mmhm&pw=bleh'
```

In Home Assistant configuration.yaml
```
shell_command:
  alert_bi: "curl {{ url }}"

```
