### DISCUSSION TITLE
Frigate.yml error - well formed yaml but still getting error

### DISCUSSION THREAD

**Discussion by kiwipaulrob** [blakeblackshear/frigate#5197] [Ask A Question] [answered]
Sorry to trouble you all but I am getting the below error from the following.

What am I missing?

```
cameras:
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.214.106:8554/video4_unicast
          roles:
            - detect
        - path: rtsp://192.168.214.106:8554/video3_unicast
          roles:
            - record
            - rtmp
      objects:
        track:
          - person
          - dog
          - cat
          - bird
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      events:
        retain:
          default: 10
```

************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> garden -> ffmpeg -> objects
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> garden -> ffmpeg -> objects
  extra fields not permitted (type=value_error.extra)
