### DISCUSSION TITLE
Reolink cameras & RTSP

### DISCUSSION THREAD

**Discussion by DrSpaldo** [blakeblackshear/frigate#5198] [Show and tell]
I've got a few different Reolink cameras (RLC-410-5MP, RLC-511 & RLC-811A) at two places. By default, they don't play well with some NVR's, such as Frigate. There are work arounds and most people get them working eventually. Some here may know, but, Reolink have an updated beta version of the firmware that allows you to turn on options that by default are not supported with Reolink cameras. 

Such as i-frame rate (key frame / Interframe Space), RTSP/ONVIF. The docs for Frigate are helpful in the work arounds, adding extra flags & using http feeds. However, with the beta firmware you can just use the normal type of rtsp feed such as:

rtsp://USER:PASS@192.168.x.x:554/h264Preview_01_main
rtsp://USER:PASS@192.168.x.x:554/h264Preview_01_sub

The way you get the beta firmware is by just creating a ticket and they will send them to you... 

@blakeblackshear @NickM-27 , I am happy to host/post the ones they sent me if you like, I'm not sure security wise if you would want me to do that or not?

Hopefully this is of some help to anyone who comes searching ;)

**Comment by NickM-27** [comment]
My newer camera has these settings already but still has the pixel smearing due to bad compression on rtsp, this is not present on http streams. Curious if that's not there for these cameras

**Reply by DrSpaldo** [reply]
I will keep an eye on the ones I have updated to the beta firmware and post if it is better.

**Reply by Red-ington** [reply]
@DrSpaldo great questions please keep us updated. mmmm very interesting.

**Comment by asaworld** [comment]
I have RLC-820A running the latest firmware (v3.1.0.956_22041501). The best solution I could find was to use all the frigate defaults with the two rtsp links above. I have tried all the Reolink camera specific settings and none work for some reason or other. I am able to use the main stream for 'record' and the sub stream for 'rtmp' and 'detect'.

I cannot view any recordings in the UI as it says "Playback cannot continue. No available working or supported playlists." but I can download the clips and view those in VLC. Those are recorded at 3840*2160@15 (8MP). I would love to get the in UI playback working. I do not get any errors except the odd "frigate.record WARNING : Discarding a corrupt recording segment:" I do not have a lot of experience with ffmpeg and would really appreciate any help I can have with this one.

I cannot use the main stream for 'rtmp' as I get lots of errors:
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   : Input #0, rtsp, from 'rtsp://admin:makcam@192.168.1.59:554/h264Preview_01_main':
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :   Metadata:
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     title           : Session streamed by "preview"
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     comment         : h264Preview_01_main
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :   Duration: N/A, start: 1674466131.466313, bitrate: N/A
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     Stream #0:0: Video: hevc, yuv420p(tv), 3840x2160, 90k tbr, 90k tbn, 90k tbc
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   : [segment @ 0x56332770f5c0] Opening '/tmp/cache/front_door-20230123092853.mp4' for writing
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   : Output #0, segment, to '/tmp/cache/front_door-%Y%m%d%H%M%S.mp4':
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :   Metadata:
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     title           : Session streamed by "preview"
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     comment         : h264Preview_01_main
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     encoder         : Lavf58.45.100
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     Stream #0:0: Video: hevc, yuv420p(tv), 3840x2160, q=2-31, 90k tbr, 90k tbn, 90k tbc
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   : [flv @ 0x56332770e400] Video codec hevc not compatible with flv
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   : Could not write header for output file #1 (incorrect codec parameters ?): Function not implemented
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   : Stream mapping:
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :   Stream #0:0 -> #0:0 (copy)
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :   Stream #0:0 -> #1:0 (copy)
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :   Stream #0:1 -> #1:1 (copy)
[2023-01-23 09:29:11] ffmpeg.front_door.record_rtmp  ERROR   :     Last message repeated 1 times
[2023-01-23 09:29:11] watchdog.front_door            INFO    : Terminating the existing ffmpeg process...

**Comment by DrSpaldo** [comment]
Not sure if it helps, but, this is how mine is currently running:

```
  street3:
    ffmpeg:
      inputs:
        - path: http://192.168.x.x/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=USER&password=PASS
          input_args: preset-http-reolink
          roles:
            - detect
            - restream
        - path: rtsp://USER:PASS@192.168.x.x:554/h264Preview_01_main
          roles:
            - record
```

**Reply by quenthal** [reply]
Can you tell me the version number of firmware your old RLC-410 or 510 uses, just to compare since I found similar beta version last november thru some old discussion from Reolinks(?) Google Drive. It also has Interframe Space (1-4s).

For example my RLC-410-5MP is using build 21102203, ie. the version is v3.0.0.660_21102203.

**Comment by asaworld** [comment]
Thank you for this. I have just realised that I was pulling an old version 'stable-amd64'=v0.10 and I have just upgraded to 0.12-beta5 and it is running very nicely.

**Comment by quenthal** [comment]
> @blakeblackshear @NickM-27 , I am happy to host/post the ones they sent me if you like, I'm not sure security wise if you would want me to do that or not?

I assume that these beta versions for aforementioned Reolink cameras are available below:
https://github.com/AT0myks/reolink-fw-archive

**Reply by jurasjo** [reply]
Yes it is the one. I have updated my 4 cameras (RLC-510A and RLC-510WA) myself to the newest firmware.

**Reply by stefesciberras** [reply]
@jurasjo I have just got the 510WA, and initially was happy with old firmware. I then updated the camera, and now the imaeg is of much less clarity.

What config are you using, please?

**Comment by danielszilagyi** [comment]
Thank you for this everyone. Have to mention that if you use a Reolink NVR, the same RTSP streams can be used, and all channels can be streamed from the nvr by using `h264Preview_01_main`, `h264Preview_02_main` in the URL. At least on my RLN16-410, the older hardware, version H3MB02, with the latest available firmware.

**Comment by Caddyman68** [comment]
I am having problems with an older Reolink - RLC-410. It won't allow me to check/uncheck streams in "Settings/Network/Advanced" and recordings & events get green screen 90% of the time. Firmware will not update to new (ver 3.0....) from ver 2.0.00 and support can't get me an intermediate firmware. I will try the configuration DrSpaldo sited for that cam and a RLC-410-5mp that has the viewing problem asaworld mentioned. 
Too late to try tonight since I don't want my other cameras down potentially.

**Comment by itkfilelor** [comment]
For my RLC-410-5MP, I am currently using what is now live firmware v3.0.0.2356_23062000 (OCT 2023) with the links @DrSpaldo posted. 
After needing to re-download the Windows app (the mobile app sucks) to turn all the necessary servers back on, it works so much better than the HTTP stream. As @NickM-27 mentioned, there is a touch more 'smudging' in night mode , but the stream doesn't drop off near as much as does with HTTP. I'll take consistency over quality in this case, as it is primarily to keep an eye on our bear problem 😁

**Reply by Caddyman68** [reply]
I forgot to update - as usual (sorry). I am using the rtsp config DrSpaldo listed for his record as both record (main) and detect (sub); no restream. I think I tried the http but since I can't update my firmware it didn't cooperate. Haven't had green screen for awhile - knock on wood.

**Comment by tomfrogger** [comment]
I found that using neolink  0.6.2 as the bridge to frigate for my reolink cameras fixed quality issues. Before using neolink the stream quality was always terrible, drop outs smearing etc. Since using neolink, no drops, no smearing or any other artifacts in the stream. I have 4 E1 Pro cameras and 3 Duo 2 Wifi's with multiple streams connected with wifi. Neolink connects to the reolinks using reolink's proprietary "Baichuan" protocol and converts to perfect rtsp streams. I run this as Home Assistant add-on container alongside the Frigate add-on. 

 https://github.com/QuantumEntangledAndy/neolink
 https://github.com/dm82m/hassio-addons

**Reply by TacoBodaco** [reply]
This is the first I've heard of Neolink. Can you share your config, or an example of what you're using for the camera stream and substream? I have 4 RLC-811A's that have been buggy since the day I got them. I've tried almost every possible stream configuration to no real success, so the sound of this Neolink gives me some hope.

**Reply by tomfrogger** [reply]
Yes sure. The links in my post should cover the documentation you need. I'm just using the main stream for everything in frigate (detect record) on all my cameras. With the resolution for the stream set to be 1080p inside the cam as this is plenty for my needs.

Neolink.toml config: connection to the Reolink cameras Note: it is set to use port 8855 in the docker expose so it can run alongside frigate using it's default 8554 for RTSP:

[neolink.toml.txt](https://github.com/user-attachments/files/16540496/neolink.toml.txt)

Fragte.yml config: for frigate 0.14 connected to the neolink docker instance. 

[frigate.yml.txt](https://github.com/user-attachments/files/16540514/frigate.yml.txt)

**Reply by thomasjsweet** [reply]
I have a Reolink camera working. I don't think it is set perfectly, but it works. Maybe this helps others.

Model RLC-811A
Config Version v3.1.0.0
Firmware Version v3.1.0.989_22051908

main display 2560x1440

My config is as follows 
```
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: pci  I bought the M2 chip

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  your_reolink_camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Passwrd@192.168.55.115:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:Passwrd@192.168.55.115:554/h264Preview_01_main
          roles:
            - record
    detect:
      fps: 7
      enabled: true
      width: 640
      height: 360

 zones, detection, alerts deleted from this post as they are user specific.
version: 0.14
```
