### DISCUSSION TITLE
Utility to send Frigate event notifications to other messengers

### DISCUSSION THREAD

**Discussion by maylorian** [blakeblackshear/frigate#5233] [Show and tell]
Hey everyone!

For us uninitiated that do not run a HA instance, I have created a dead-simple utility that will poll MQTT for new detections and pipe them through to a messenger of choice. Currently, only discord and slack are supported but I plan on adding more in the future. 

https://github.com/andreasavg/Frigatier

So the utility can and will send messages to all enabled messengers. It will construct a message like the following:

`A <detection label> was detected by <camera name>` 

And it will also make a request to `/api/events/<event id>/thumbnail.jpg` to get a thumbnail to send. 

The repo README explains what you need to  run it but here's an overview:

You need to either download or compile the binary and then create a config.yml file next to the binary:

```
frigate:
  host: <frigate IP>
  port: <frigate port>
  
mqtt:
  host: <mqtt IP>
  port: <mqtt port>
  user: <username> #optional
  password: <password> #optional 

messengers:
  slack:
    enabled: True
    token: <slack token>
    channel: <channel ID>

  discord:
    enabled: True
    token: <discord bot token>
    channel: <channel or user id>
```

I've already published pre-compiled binaries for linux and windows (God I hope I've done the release correctly) or you can just compile your own:

```
git clone https://github.com/andreasavg/Frigatier
cd Frigatier && cd app
go build
```

Now I do have a question, I've noticed that the MQTT message in `frigate/events` contains both a `before` and `after` entry. For the moment, I always read the `before` entry and just sit idle until `false_positive` is set to `false`. Once that's true, I trigger a message. When subsequent events with the same ID come in, I just ignore them until `end_date` is set and that's when I discard the event completely. 

Is there any point where I should be paying attention to the `after` event?

This is a very VERY early release without much testing. I just wanted to get your opinion on how useful something like this would be. Expect wormholes consuming your cat.
