### DISCUSSION TITLE
Getting duplicate notifications from Home Assistant, suspect Frigate.

### DISCUSSION THREAD

**Discussion by superdong69** [blakeblackshear/frigate#5249] [General]
So basically what is happening, is I get A event, get a notification from home assistant, and the video. Perfect. 6 hours later I get B event. I get notification in home assistant app on phone. But I ALSO get a repeat notification of event A, with the video. When I watch either A video or B video, if they are the same event, I.e car, or person, the two videos will be mushed into one video. I SUSPECT, that's why I'm getting the duplicate notifications, because frigate is mushing the videos together, and creating a new event.

My question is, what setting do I need to change to stop this behavior? I want frigate to record EACH event on it's own. I don't want it to append to other events in the day. 

Simple I'm sure,  I just can't figure it out. 
Thank you SO MUCH!

**Comment by NickM-27** [comment]
You need to show your config and what automation you're using for notifications

**Comment by superdong69** [comment]
Using Blueprint: Frigate Notification (0.11.0.8) - SgtB

Yaml:

```
alias: Frigate Notify Driveway
description: ""
use_blueprint:
  path: SgtBatten/frigate_0.11_notification.yaml
  input:
    color: grey
    notify_group: notify.group1
    labels:
      - person
      - car
    camera: camera.front
    critical: "true"
    alert_once: true
    update_thumbnail: true
```

Frigate YAML is:

```
mqtt:
  host: 10.1.20.1
  port: 1883
  user: user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
    enabled: True
    width: 1280
    height: 720
    quality: 8
    mode: continuous 

cameras:
  Side:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy - 
       tag:v hvc1 -c:a aac
      inputs:
   ### 3840x2160 Mainstream 30 FPS AAC Audio ###
    - path: rtsp://10.1.20.20:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      roles:
        - record
   ### 1080P Substream ###
    - path: rtsp://10.1.20.20:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      roles:
        - detect
        - rtmp
detect:
  width: 1920
  height: 1080
  fps: 30
objects:
  track:
    - person
    - car
    - dog
  filters:
    person:
      threshold: 0.7
      min_area: 2500
      max_area: 100000
snapshots:
  enabled: True
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 2
rtmp:
  enabled: False
motion:
  mask:


  Front:
   ffmpeg:
      inputs:
       ### 2048x1536 Mainstream ###
        - path: rtsp://10.1.20.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
       ### 704x480 Substream ###
        - path: rtsp://10.1.20.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 480
      fps: 30
    objects:
      track:
        - person
        - car
        - dog
  filters:
    person:
      threshold: 0.7
      min_area: 2000
      max_area: 100000
snapshots:
  enabled: True
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 2
rtmp:
  enabled: False
motion:
  mask:


  Rear:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy - 
   tag:v hvc1 -c:a aac

  inputs:
   ### 3840x2160 Mainstream 30 FPS AAC Audio ###
    - path: rtsp://10.1.20.22:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      roles:
        - record
   ### 1080P Substream ###
    - path: rtsp://10.1.20.22:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      roles:
        - detect
        - rtmp
detect:
  width: 1920
  height: 1080
  fps: 30
objects:
  track:
    - person
    - car
    - dog
  filters:
    person:
      threshold: 0.7
      min_area: 2500
      max_area: 100000
snapshots:
  enabled: True
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 2
rtmp:
  enabled: False
motion:
   mask:
```

**Reply by NickM-27** [reply]
For one I would suggest reducing your fps to 5 as it doesn't need to match the camera value and 30 won't help. 

As far as the notifications issue, I'm not familiar with that blueprint but I have a guide I wrote which may help https://github.com/blakeblackshear/frigate/discussions/2898

**Comment by superdong69** [comment]
I just want to stop recorded events from being appended to one another in one file. One event, one file. 

I've gone through:
https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean

And it has everything BUT what I want to do, unless I'm reading this wrong. active_objects is closest, but I don't want all the events merged into one video. I want each event to have it's own event, own video, etc. I am not in an area where there is much traffic in my cameras. As it is now, a car comes in, like the mailman, and the camera stays active ALL day after they leave, I drive in, and the video gets merged. Or the dog triggers the camera, comes back in the house, and the video keeps going and merges with a car later.

https://codesti.com/issue/blakeblackshear/frigate/4977
This guy wanted the same thing, but unfortunately there wasn't a conclusion to the post.

How do I get this behavior?

**Reply by NickM-27** [reply]
This is likely because the car leaves and it sees a different car and assumes it is the same car in which case this will be fixed by better object tracking

**Reply by superdong69** [reply]
I'm using a google coral TPU, how would I increase the object tracking?
I literally just want Frigate to stop putting multiple events in one video. That's what I want. I want One event, one video. 
Certainly it can do that no? That will fix all my problems. I don't care if there are 10 different videos for one 10 min event. I just want to know how to tell Frigate to do that, and stop trying to put all cars into one cars event video.

**Reply by blakeblackshear** [reply]
You are asking the wrong question. What you are describing is how Frigate already works. It should be creating an event for each unique object unless there is an issue such as a false positive hanging around. We would need to work through a specific example. Also, if you see "in progress" events after an object has left the view, you should be able to watch the debug video and see what it is tracking.

**Reply by superdong69** [reply]
Ok,  but it's not.  Today i had my wife's car pulling out of the garage,  event and notification. Then i leave 30 minutes later,  I get an event and notification showing my car,  and another notification showing her car.  I watch the video,  it shows her car leaving,  then it cuts to the video 30 mins later of my car leaving. 

Then 4 hours later,  I get a notification showing MY Car Again,  and the video starts with my wife's car leaving,  mine,  then a giant ups truck driving up my driveway. 

There are NO cars in my driveway,  ever.  They go in the garage.  There are no people walking around,  I live down a secluded 500 foot driveway.  I have the areas where any potential trees could be visible masked out. 

So if frigate is working as intended,  I want to fix that,  and have it do what I already said I was looking for. 
This isn't just one camera,  it happens with every camera,  so it's not an anomaly.

**Reply by NickM-27** [reply]
> Then 4 hours later, I get a notification showing MY Car Again, and the video starts with my wife's car leaving, mine, then a giant ups truck driving up my driveway.

That means you either have a false positive or another car in view of the camera which frigate believes as the same car that was in your driveway. You can use the live debug view with bounding boxes enabled to see if there are false positives (currently, you may need to wait until a car arrives / leaves to verify this). You will also notice the `In Progress` which means that event is currently active (frigate still is tracking that object).

**Reply by superdong69** [reply]
Gotcha.  I'll check it out.  But like I said,  there isn't anything in frame to keep it recording.  Ever.  So once I prove that out,  where do I look next? Cause i can promise you there aren't cars to keep frigate in progress monitoring.

**Reply by NickM-27** [reply]
Like has been said multiple times, if there is no actual car then it would be a false positive (frigate thinks it sees a car where there isn't one).

**Reply by blakeblackshear** [reply]
> Cause i can promise you there aren't cars to keep frigate in progress monitoring.

Nobody is disagreeing with you. It probably thinks something that is not a car looks like a car. This is what we mean by a false positive.

**Reply by superdong69** [reply]
Totally understand you. I just don't understand what could make a false positive in these shots. Here is a current shot of one of the cams, with the debug masks shown.
https://i.imgur.com/lLMQrfw.png
Something would seriously be wrong. LOL

**Reply by blakeblackshear** [reply]
Just come back and see what the debug view shows in terms of bounding boxes next time you have an in progress event when nothing is there. It can also be that the object fully entered a motion mask and frigate is assuming it's a stationary object and still present. This is why the docs recommend against using motion masks to block off large areas in several places.

**Reply by superdong69** [reply]
The docs recommend against blocking out large areas of the searchable area? How's that? What's the point of having them then? All the tutorials I've seen online tell you to use masks to mask out all the areas in the feed you don't want to search for movement. You're saying that's incorrect?

**Reply by NickM-27** [reply]
> The docs recommend against blocking out large areas of the searchable area? How's that? What's the point of having them then? All the tutorials I've seen online tell you to use masks to mask out all the areas in the feed you don't want to search for movement. You're saying that's incorrect?

Object masks are meant to block out things like timestamps, trees, etc. They are not meant to block out areas that are not of interest. That is what zones are used for (to only get events for areas of interest). A large motion mask will cause an object to get "stuck" because the motion of the object leaving is forcefully being ignored by the config. https://docs.frigate.video/configuration/masks

**Reply by superdong69** [reply]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
Understood. So instead I should have everywhere I WANT detected to be a Zone. So things can go into and out of a zone safely, which will change the way the events occur. Gotcha.

**Reply by blakeblackshear** [reply]
This is one of the reasons we have an issue template for support requests where we ask for your config and other information. The portion of your config you provided didn't include a motion mask. Otherwise this may have been immediately obvious to us.

**Reply by superdong69** [reply]
So I've created a zone, and Frigate continues to say in progress in the events viewer. When I look at the debug video, there is nothing showing a trigger. The zone worked properly, the event says Zone 0, but is still in progress. Is there a threshold I need to set so that the event only stay in progress recording for say like 120 secs, then finalizes the event?

**Reply by superdong69** [reply]
https://i.imgur.com/JONjItA.png
A picture of the new zone, and debug showing NOTHING triggering the event to continue.

Yet as you can see, it's been in progress now for at least 12 minutes, and will continue to be in progress all day long.
https://i.imgur.com/1ptWMWe.png

**Reply by blakeblackshear** [reply]
Just to be sure, you expanded the options and you turned on the switch for bounding boxes in the debug view, correct?

**Reply by NickM-27** [reply]
It's also worth noting that it looks like you're running an older version of frigate, the latest version is 0.11.1

**Reply by superdong69** [reply]
> Just to be sure, you expanded the options and you turned on the switch for bounding boxes in the debug view, correct?

That is correct.

**Reply by superdong69** [reply]
> It's also worth noting that it looks like you're running an older version of frigate, the latest version is 0.11.1

Understood,  I thought I saw the newest version was a beta,  and not supported with home assistant,  which was why I haven't update it yet.  Is there a stable I didn't see where I don't need to mess around with HA? I've finally got it working just so,  and don't want to piss the gremlins in the machine off. Lol

**Reply by superdong69** [reply]
And for more info,  when I left the house 30 mins after the wife,  I got the notification for my car,  and hers again,  so that's why the duplicate notifications like you guys thought.  The event was still in progress.

**Reply by blakeblackshear** [reply]
If you have an in_progress event and you aren't seeing a bounding box, then I would expect you to have an error message in the logs. Otherwise we would have thousands of reported issues like this. Did you turn off the switch for masks? Maybe the mask is being drawn on top of the bounding box.

Either way, the image you posted shows that you still have a large motion mask in your config, and that is one of the common causes of this behavior.

**Reply by superdong69** [reply]
Understood.  The problem is,  the mask is there to block trees that wave.  Fairly certain that was the intention of the mask,  no?

**Reply by blakeblackshear** [reply]
Yes, but we are trying to track down the issue with events not ending right now. If you turn off the switch to draw the mask on the debug view, do you see the bounding box when there is an in progress event?

**Reply by NickM-27** [reply]
> Understood. The problem is, the mask is there to block trees that wave. Fairly certain that was the intention of the mask, no?

Yes, but that doesn't negate the fact that an object can get stuck. You should use the switch on the debug live view to stop showing the motion mask and see if there are any bounding boxes for objects that are detected. If not then as Blake said there will likely be errors in the logs.

> > It's also worth noting that it looks like you're running an older version of frigate, the latest version is 0.11.1
>
> Understood, I thought I saw the newest version was a beta, and not supported with home assistant, which was why I haven't update it yet. Is there a stable I didn't see where I don't need to mess around with HA? I've finally got it working just so, and don't want to piss the gremlins in the machine off. Lol

The newest version is 0.12 (in beta), but there is also 0.11. Looks like you are on 0.10

**Reply by superdong69** [reply]
Roger all that!

**Reply by superdong69** [reply]
Rebooted the box and tested it again.  There is an active motion box,  and I think I've got it sorted. I'll have to mess with it later,  but I think even with the zone,  because there is a mask RIGHT BEHIND L behind the zone,  it doesn't pick up that the car actually left,  even though it SHOULD be able to detect there's nothing there,  because well,  there's nothing there.... I'll report back with my findings

**Reply by superdong69** [reply]
Guys, I'm pulling my freaking hair out here. How do I get zones to work properly? I added a zone, removed the motion masks except around the time, and I'm getting alerted from things outside my zone. When I try and delete the `    objects:
      track:
        - person
        - car
        - dog
`
and leave just the track in the zone, frigate won't freaking start.

**Reply by NickM-27** [reply]
> I added a zone, removed the motion masks except around the time, and I'm getting alerted from things outside my zone. 

Please read the docs. You need to add `required_zones` for snapshots and recordings if you want events restricted to only when an object enters the zone

> When I try and delete the `    objects:
> 
>       track:
> 
>         - person
> 
>         - car
> 
>         - dog
> 
> `
> 
> and leave just the track in the zone, frigate won't freaking start. 

Well, probably a config or indentation issue. Can't help without seeing the current config

**Reply by superdong69** [reply]
```
mqtt:
  host: 10.1.20.1
  port: 1883
  user: user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
    enabled: True
    width: 1280
    height: 720
    quality: 8
    mode: continuous 

cameras:
  Side:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy - 
       tag:v hvc1 -c:a aac
      inputs:
   ### 3840x2160 Mainstream 30 FPS AAC Audio ###
    - path: rtsp://10.1.20.20:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      roles:
        - record
   ### 1080P Substream ###
    - path: rtsp://10.1.20.20:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
      roles:
        - detect
        - rtmp
detect:
  width: 1920
  height: 1080
  fps: 5

  filters:
    person:
      threshold: 0.7
      min_area: 2500
      max_area: 100000
snapshots:
  enabled: True
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 2
rtmp:
  enabled: False
motion:
  mask:
    - 1846,34,1851,84,1440,83,1440,40
zones:
  monitor_front:
    coordinates: 308,212,711,32,745,36,790,42,882,29,924,34,1003,21,1177,26,1240,27,1310,34,1464,42,1517,53,1675,86,1825,132,1920,162,1920,0,0,0,0,389
    objects:
      track:
        - person
        - car
        - dog
```

**Reply by NickM-27** [reply]
okay, so:
1. your `Side -> ffmpeg -> output_args -> record` is split on two lines but it needs to be on 1
2. you have filters being applied to detect which is entirely incorrect
3. you're setting the motion mask globally which probably isn't a good idea, should be set on the camera level
4. you're trying to apply zones globally which isn't allowed, it needs to be set on the camera level

**Reply by superdong69** [reply]
Ok, please understand, you know literally a million times more than I do on this system, I'm a set it and forget it kinda guy. I put this config file together about 6 months ago, got everything "working" and haven't messed with, or want to mess with it again.

Could you kindly just tell me how I go about getting this working the proper way? It's clear I have no idea how to do this, and I've admittedly spent far too much of the time I don't have trying to figure this out, and I'm far beyond the point of frustration. I've got number 1, but if you could tell me what code I need to correct, I'd forever be in your debt.

**Reply by superdong69** [reply]
So correction, that area you spoke about in 1. is actually intact on the server. Dunno why it copied across like that here.

**Reply by NickM-27** [reply]
I generally don't like fixing code for people since there's no learning, but this has been a long process so I will make the edits I think should be made and also add comments to explain what certain things do

**Reply by superdong69** [reply]
I normally REALLY enjoy the learning process, but my wife has been up my rear about the notifications, and I'm gonna be honest, I can't take much more of her. It's been a terrible couple weeks. LOL I'm trying to tip you, but no window is opening to allow me to do so. The "Send a tip" balloon pops up, and when I click it, the emojis pop up. I've turned off my adblock, etc and still won't let me.

**Reply by NickM-27** [reply]
Okay here you go:

```yaml
mqtt:
  host: 10.1.20.1
  port: 1883
  user: user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

# disable RTMP restream
rtmp:
  enabled: False

# enable snapshots
snapshots:
  enabled: True

# enable recordings
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 2

cameras:
  Side:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://10.1.20.20:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif ### 3840x2160 Mainstream 30 FPS AAC Audio ###
          roles:
            - record
        - path: rtsp://10.1.20.20:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif ### 1080P Substream ###
          roles:
            - detect

    detect:
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
        - car
        - dog
        - person
      filters:
        person:
          threshold: 0.7
          min_area: 2500
          max_area: 100000

    # area of interest that we want events for
    zones:
      monitor_front:
        coordinates: 308,212,711,32,745,36,790,42,882,29,924,34,1003,21,1177,26,1240,27,1310,34,1464,42,1517,53,1675,86,1825,132,1920,162,1920,0,0,0,0,389

    snapshots:
      required_zones:
        - monitor_front # <- only save snapshots for objects that enter the monitor_front zone

    record:
      events:
        required_zones:
          - monitor_front # <- only record objects that enter the monitor_front zone

    # motion mask which needs to be minimal, not covering large area
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
```

one thing to note is if you don't want notifications for objects that never enter that zone, you'll need to fill in the zones field of your notification blueprint with monitor_front

**Reply by superdong69** [reply]
AHHH yeah gotcha. Off to try to it! Thank you!

**Reply by superdong69** [reply]
So I've been able to get all cams back up, but I can't view the events, or live feeds. Either in the HA app, HA dashboards, or frigate.

**Reply by NickM-27** [reply]
Your config had rtmp disabled so no live views is expected based on the config you put here. 

Not being able to view events need to see the logs

**Reply by superdong69** [reply]
Not to sound like an idiot, but would you be so kind as to point me to where I could find those logs?
I noticed that as well, as set RTMP to true, and added it to the substreams, and it still didn't work.

**Reply by NickM-27** [reply]
How are you running frigate?

And not sure then, should work as expected unless there's errors in the logs

**Reply by superdong69** [reply]
Running frigate on a bare metal machine running linux and docker

**Reply by NickM-27** [reply]
> Running frigate on a bare metal machine running linux.

From CLI run `docker logs frigate`

**Reply by superdong69** [reply]
```
[2023-02-02 20:46:04] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2023-02-02 20:46:04] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-02-02 20:46:04] peewee_migrate                 INFO    : There is nothing to migrate
[2023-02-02 20:46:04] detector.coral                 INFO    : Starting detection process: 225
[2023-02-02 20:46:04] frigate.app                    INFO    : Output process started: 227
[2023-02-02 20:46:04] ws4py                          INFO    : Using epoll
[2023-02-02 20:46:04] frigate.app                    INFO    : Camera processor started for driveway: 233
[2023-02-02 20:46:04] frigate.app                    INFO    : Camera processor started for house_front: 236
[2023-02-02 20:46:04] frigate.app                    INFO    : Camera processor started for garage_rear: 238
[2023-02-02 20:46:04] frigate.app                    INFO    : Capture process started for driveway: 239
[2023-02-02 20:46:04] frigate.app                    INFO    : Capture process started for house_front: 243
[2023-02-02 20:46:04] frigate.app                    INFO    : Capture process started for garage_rear: 246
[2023-02-02 20:46:04] ws4py                          INFO    : Using epoll
[2023-02-02 20:46:04] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2023-02-02 20:46:07] frigate.edgetpu                INFO    : TPU found
[2023-02-02 20:46:11] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41820]
[2023-02-02 20:47:09] frigate.http                   ERROR   : No recordings found for the requested time range
[2023-02-02 20:47:09] frigate.http                   ERROR   : Event does not have recordings: 1675372845.308337-g4nqp8
[2023-02-02 20:47:10] frigate.http                   ERROR   : Event does not have recordings: 1675372845.308337-g4nqp8
[2023-02-02 20:47:11] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41820]
[2023-02-02 20:49:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57228]
[2023-02-02 20:49:46] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:35214]
[2023-02-02 20:49:48] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:35214]
[2023-02-02 20:51:02] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:35484]
[2023-02-02 20:51:04] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:35484]
[2023-02-02 20:51:15] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57228]
[2023-02-02 20:51:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49356]
[2023-02-02 20:51:42] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49356]
[2023-02-02 20:53:19] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:46688]
[2023-02-02 20:53:22] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:46688]

```
So this is all I got. I walked around the house, and only one camera recorded an event. None of the cameras work in HA or HA app, but I WAS able to view the video clip on the HA app via the notification. It's weird, because with the exception of the RTMP disabled, nothing has changed that should have broken the rtmp streams, or recording.

**Reply by NickM-27** [reply]
Paste your current config

**Reply by superdong69** [reply]
```
---
mqtt:
  host: ip
  port: 1883
  user: user
  password: password
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous
rtmp:
  enabled: true
snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 2
cameras:
  driveway:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://stream
          roles:
            - record
        - path: rtsp://stream
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - car
        - dog
        - person
      filters:
        person:
          threshold: 0.7
          min_area: 2500
          max_area: 100000
    zones:
      monitor_front:
        coordinates: 0,459,84,385,213,310,391,216,505,156,596,117,694,71,748,65,819,52,905,44,1002,37,1127,43,1303,48,1377,56,1409,68,1431,96,1513,99,1582,109,1650,107,1700,128,1760,138,1846,157,1920,171,1920,1080,0,1080
    snapshots:
      required_zones:
        - monitor_front
    record:
      events:
        required_zones:
          - monitor_front
    motion:
      mask:
        - 1846,34,1851,84,1440,83,1440,40
  house_front:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://stream
          roles:
            - record
        - path: rtsp://stream
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - car
        - dog
        - person
      filters:
        person:
          threshold: 0.7
          min_area: 1500
          max_area: 100000
    zones:
      monitor_front_angle:
        coordinates: 0,176,27,167,33,135,58,133,90,128,125,127,162,121,204,121,244,121,281,120,329,127,377,131,430,127,485,130,540,139,565,145,619,157,704,181,704,480,0,480
    snapshots:
      required_zones:
        - monitor_front_angle
    record:
      events:
        required_zones:
          - monitor_front_angle
    motion:
      mask:
        - 704,0,704,43,514,48,515,0
  garage_rear:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://stream
          roles:
            - record
        - path: rtsp://stream
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - car
        - dog
        - person
      filters:
        person:
          threshold: 0.7
          min_area: 2500
          max_area: 100000
    zones:
      monitor_garage_rear:
        coordinates: 0,182,115,119,207,68,395,0,1409,0,1425,107,1757,122,1920,133,1920,269,1920,1080,0,1080
    snapshots:
      required_zones:
        - monitor_garage_rear
    record:
      events:
        required_zones:
          - monitor_garage_rear
    motion:
      mask:
        - 1436,80,1845,83,1845,34,1439,38

```

So I'm looking at this and wondering why all your comments are gone, it appears as though yamllint.com/ cleans the code up and removes all comments in the code. Which is SUPER annoying.
