### DISCUSSION TITLE
Share - HA basic automations to handle issues (workaround)

### DISCUSSION THREAD

**Discussion by S-Przybylski** [blakeblackshear/frigate#525] [Show and tell]
I set up two actions to cover frigate issues using HA itself (simplified solution, not bullet proved) as a workaround. Maybe its usable for others. Feel free to enhance!

**Problem**
Currently I have two bugs using Frigate on RASPI
- Reboot of Raspi disables the TPU (docker container)
- Crashes within Frigate, container still runs (restart of container doesn't help) 

**Workaround**
- Use HA itself to reboot the RASPI or restart the container (TPU issue)

**Version of frigate**
Docker image on RASPI4 (arm 32bit) beta 0.8beta3 (and manual test of beta4) [no HASS OS]

**Configuration**
- RASPI 4 32bit using Docker for FRIGATE (exclusive)
- Use docker Image philhawthorne/ha-dockermon to interact with docker container
- Use ssh to log into external frigate RASPI to initiate reboot. ssh key is setup within homeassistant config folder (/config/ssh)
```yaml
configuration.yaml:
input_boolean:
  docker_maintenance:
    name: "Docker Maintenance"
    initial: off
    icon: mdi:bell-ring

shell_command:
  restart_frigate: 'curl http://<hostnamefrigate>:8126/container/frigate/restart'
  reboot_frigate: 'ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i /config/ssh/sshkey <user>@<hostnamefrigate> /usr/bin/sudo reboot'
# use ssh-copy-id to setup ssh inside a container and protect the ssh key! Essential command on HA system/bash (not inside the HA container):
#   ssh-copy-id -i /xyz/homeassistant/ssh/sshkey <user>@<hostnamefrigate> 
# test the ssh statement using docker exec -it homeassistant /bin/bash ...
#   ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i /config/ssh/sshkey <user>@<hostnamefrigate> /usr/bin/sudo reboot

binary_sensors.yaml:
# FRIGATE Identify if frigate is crashed - needs to reboot Raspi
- platform: template
  sensors:
    frigate_online:
      value_template: >-
        {%-set timestamp = (as_timestamp(now()) - as_timestamp(states.sensor.coral_inference_speed.last_updated) )| int -%}
        {%-if timestamp > 60 -%} {{false}}
          {%-else-%} {{true}}
        {%-endif-%}
      friendly_name: 'Frigate Online'

# FRIGATE Identify if frigate uses CPU instead of TPU (after reboot) - needs to restart Frigate container
- platform: template
  sensors:
    frigate_tpu:
#perhaps to simple, unavailable = OK
      value_template: >-
        {%-if (states('sensor.coral_inference_speed') | int) > 150 -%} {{false}}
          {%-else-%} {{true}}
        {%-endif-%}
      friendly_name: 'Frigate TPU'

automations.yaml:
- alias: 'frigate_offline'
  mode: single
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.frigate_online
      to: 'off'
      for:
        seconds: 120
  condition:
    condition: state
    entity_id: input_boolean.docker_maintenance
    state: 'off'
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.docker_maintenance
    - service: script.reboot_frigate
    - delay: '00:00:30'
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.docker_maintenance

# frigate tpu offline (coral interference speed >150 ms) for 1 minute and no docker maintenance
- alias: 'frigate_tpu_offline'
  mode: single
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.frigate_tpu
      to: 'off'
      for:
        seconds: 60
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'input_boolean.docker_maintenance'
        state: 'off'
      - condition: state
        entity_id: 'switch.frigate'
        state: 'on'
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.docker_maintenance
    - service: script.restart_frigate
    - delay: '00:00:30'
    - service: input_boolean.turn_off
      data_template:
        entity_id: input_boolean.docker_maintenance

scripts.yaml:
  restart_frigate:
    alias: Restart Frigate
    mode: single
    sequence:
      - service: shell_command.restart_frigate

  reboot_frigate:
    alias: Reboot Frigate System
    mode: single
    sequence:
      - service: shell_command.reboot_frigate


```

**Screenshots**
