### DISCUSSION TITLE
stationary by object

### DISCUSSION THREAD

**Discussion by Vincentig** [blakeblackshear/frigate#5274] [General]
Hello,

Is there a way to disable stationary object by tracking type ?
Like only for car but not for person

Because as you can see in my capture below, I have often false positive for a person.
![image](https://user-images.githubusercontent.com/18244824/215218355-5c5d1f04-2898-4606-8bac-263239c7832b.png)

I have an automation that send me notification when a person is in front of my door. 
And with this false stationary person i am spammed all night :)

Thanks

**Comment by NickM-27** [comment]
Do you have motion masks setup? this usually happens when a motion mask is too large. 

if not, you can disable it

```yaml
detect:
  stationary:
    max_frames:
      objects:
        person: 300
```

keep in mind this setting is not recommended in most cases except to deal with false positive stationary objects.

**Comment by Vincentig** [comment]
Yes I have set a mask like this in order to don't register my neighbor in there garden

![image](https://user-images.githubusercontent.com/18244824/215219533-787b5882-9fc5-4908-99b7-358f8b140c83.png)

```
cameras:
  exterieur:
    motion:
      mask: 
        - 217,0,305,0,600,0,896,0,896,110,605,56,438,55,272,127,167,173,0,275,0,0
```

Thanks i will try your solution.
