### DISCUSSION TITLE
Can't start my freshly installed Frigate

### DISCUSSION THREAD

**Discussion by The-NinthWave** [blakeblackshear/frigate#5279] [General]
Installed HassOS in an indenpendant VM with MQTT addon.
A test shows MQTT is working.

Here is my compose yml

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable

    shm_size: "96mb" # update for your cameras based on calculation
    networks:
      IOT:
        ipv4_address: 172.18.10.30
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
 #     - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
 #     - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral
 #     - /dev/apex_1:/dev/apex_1 # passes a PCIe Coral      
 #     - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/nick/Documents/frigate/config/config.yml:/config/config.yml:ro  # modify to match your setup
      - storage:/media/frigate                   # modify to match your setup
      - database:/db           # modify to match your setup
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"  #modify to whatever if using rtsp

volumes:
  config:
  storage:
  database:

networks:
  IOT:
    external: true
```

Here is my config.yml
```
# yaml-language-server: $schema=http://10.0.0.20:5000/api/config/schema
detectors:
  cpu1:
    type: cpu

mqtt:
  host: 10.0.10.8
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistant
  password: "hidden"
  stats_interval: 60

cameras:
  locker:
    ffmpeg:
      inputs:
        - path: rtsp://admin:tlJwpbo6@10.0.40.11:554/channel=1_stream=0.sdp?real_stream
          roles:
            - detect
            - rtmp
      rtmp:
      enabled: True
      detect:
        width: 720
        height: 480

```
Here is the log at the stack deploy

```
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-28 10:13:19] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
3 validation errors for FrigateConfig
cameras -> locker -> ffmpeg -> detect
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> enabled
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> rtmp
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for FrigateConfig
cameras -> locker -> ffmpeg -> detect
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> enabled
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> rtmp
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-28 10:13:26] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
3 validation errors for FrigateConfig
cameras -> locker -> ffmpeg -> detect
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> enabled
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> rtmp
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for FrigateConfig
cameras -> locker -> ffmpeg -> detect
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> enabled
  extra fields not permitted (type=value_error.extra)
cameras -> locker -> ffmpeg -> rtmp
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

I don't understand the problem.

**Comment by NickM-27** [comment]
your indentation is incorrect and the config is invalid: https://docs.frigate.video/guides/getting_started

**Reply by The-NinthWave** [reply]
That I can see but could you be more specific?
I copy-pasted the config from nano to Notepad++, and cannot see where the indentation is wrong.

And for the "getting-started", again I can't seem to understand what's wrong.

**Comment by NickM-27** [comment]
Compare

```yaml
# yaml-language-server: $schema=http://10.0.0.20:5000/api/config/schema
detectors:
  cpu1:
    type: cpu

mqtt:
  host: 10.0.10.8
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistant
  password: "hidden"
  stats_interval: 60

cameras:
  locker:
    ffmpeg:
      inputs:
        - path: rtsp://admin:tlJwpbo6@10.0.40.11:554/channel=1_stream=0.sdp?real_stream
          roles:
            - detect
            - rtmp
      rtmp:
      enabled: True
      detect:
        width: 720
        height: 480
```

to 

```yaml
mqtt:
  host: <ip of your mqtt server>

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

notice the differences in indentation of rtmp, enabled, detect, width, height are all too indented. If you are using tabs you should definitely switch to using spaces

**Reply by The-NinthWave** [reply]
Damn... I am blind
How many time have l looked at it...
Thanks.

**Reply by The-NinthWave** [reply]
> notice the differences in indentation of rtmp, enabled, detect, width, height are all too indented. If you are using tabs you should definitely switch to using spaces

Am I blind again... It won'T start again no matter how bad I look at indentation.

```
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
yaml-language-server
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-31 22:00:48] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
yaml-language-server
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
yaml-language-server
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-31 22:00:54] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
yaml-language-server
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
yaml-language-server
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```
```
yaml-language-server: $schema=http://10.0.0.20:5000/api/config/schema
detectors:
  cpu1:
    type: cpu
mqtt:
  host: 10.0.10.8
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistant
  password: "hiddenpwd"
  stats_interval: 60
cameras:
  locker:
    ffmpeg:
      inputs:
        - path: rtsp://admin:tlJwpbo6@10.0.40.11:554/channel=1_stream=0.sdp
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 720
      height: 480

```
