### DISCUSSION TITLE
Docker Setup Recommendations

### DISCUSSION THREAD

**Discussion by gregeeh** [blakeblackshear/frigate#5284] [Ask A Question]
Hi all,

I've setup Frigate and Mosquitto in separate containers on my NAS.  The two containers are in a Stack within Portainer (another Container)

My Stack is like so:

```
services:
### Mosquitto ###
    eclipse-mosquitto:
        container_name: mosquitto
        ports:
            - '1883:1883'
            - '9001:9001'
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Australia/Sydney
        volumes:
            - '/share/appdata/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf'
            - '/share/appdata/mosquitto/data:/mosquitto/data'
            - '/share/appdata/mosquitto/log:/mosquitto/log'
        hostname: mosquitto.localdomain
        labels:
            - "diun.enable=true"    
        network_mode: bridge
        restart: unless-stopped
        image: eclipse-mosquitto

### Frigate ###
    frigate:
        container_name: frigate
        depends_on:
          - eclipse-mosquitto
        shm_size: "64mb"
        devices:
            - /dev/bus/usb:/dev/bus/usb
            - /dev/dri/renderD128
        network_mode: bridge
        volumes:
            - /share/Frigate:/media/frigate
            - /share/appdata/frigate/config/config.yml:/config/config.yml
            - type: tmpfs
              target: /tmp/cache
              tmpfs:
                size: 1000000000
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Australia/Sydney
            - PLUS_API_KEY=zzzzzzzzzzzz-xxxxxxxxx-vvvvvvvvv
            - FRIGATE_RTSP_PASSWORD=password
        labels:
            - "diun.enable=true"
        ports:
            - '5000:5000'
            - '1935:1935'
        restart: unless-stopped
        image: 'blakeblackshear/frigate:stable'
```

My Frigate Config is:

```
mqtt:
    host: 192.168.10.2
    user: mqtt-user
    password: mqtt-password
cameras:
    Villa333:
        rtmp:
            enabled: false
        ffmpeg:
            input_args:
               - -avoid_negative_ts
               - make_zero
               - -fflags
               - +genpts+discardcorrupt
               - -flags
               - low_delay
               - -strict
               - experimental
               - -analyzeduration
               - 1000M
               - -probesize
               - 1000M
            inputs:
                - path: rtsp://admin:password@192.168.10.70:554/h264Preview_01_sub
                  roles:
                    - detect
                - path: rtsp://admin:password@192.168.10.70:554/h264Preview_01_main
                  roles:
                    - record
                    - rtmp
        detect:
            enabled: false
            width: 640
            height: 360
        record:
            enabled: True
            events:
                pre_capture: 15
                post_capture: 5
                retain:
                    default: 10
                    mode: active_objects
snapshots:
    enabled: True
    retain:
        default: 10
birdseye:
    enabled: True
    mode: continuous
    quality: 6
```

Is this setup considered best practise, or should I be doing it another way?

TIA
