### DISCUSSION TITLE
Hardware Acceleration puts CPU Load at 100%

### DISCUSSION THREAD

**Discussion by mjoed** [blakeblackshear/frigate#5286] [Ask A Question] [answered]
Hi,

i have a docker setup on debian in an LXC container on proxmox running 0.12.0-beta5. everything seems to be working quite fine and the cpu is strong enough to handle 4 1080p cameras pretty easily:

![image](https://user-images.githubusercontent.com/7069749/215325063-a1f02914-7a49-4d41-a430-3da21fc16150.png)

now i thought, why not use hardware acceleration to make it even better - i have a Intel(R) Celeron(R) J4125 cpu which is 10th gen, so i tried adding it to my lxc config, passing it through to the docker container and enabling it in the config with

```
ffmpeg:
  hwaccel_args: -c:v h264_qsv
```

(i also tried the <10th generation option with the same result) and it seems to get recognized and works:

![image](https://user-images.githubusercontent.com/7069749/215324526-218e9f99-7aa8-42b5-9b4f-7ad73da0b6d4.png)

but now it seems to complete max out my cpu and the recordings get laggy etc:

![image](https://user-images.githubusercontent.com/7069749/215324537-d9d92ec6-c821-4965-94d9-32efa886d1e8.png)

can someone tell me what's happening here? i would imagine enabling hardware acceleration would decrease cpu load, not increase it? tell me if you need any additional info

my lxc conf:

```
root@pve:~# cat /etc/pve/lxc/101.conf 
arch: amd64
cores: 4
features: nesting=1
hostname: dockerenv
memory: 7000
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=42:51:74:D9:79:47,ip=dhcp,type=veth
ostype: debian
rootfs: local-lvm:vm-101-disk-0,size=25G
swap: 2000
lxc.apparmor.profile: unconfined
lxc.cap.drop: 
lxc.cgroup.devices.allow: a
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/bus/usb/002 dev/bus/usb/002 none bind,optional,create=dir
```

my docker compose:

```
version: '3'

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta5
    privileged: true
    shm_size: '100m'
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /mnt/NAS/frigate:/config
      - /mnt/NAS/frigate/store:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate:/mnt/local
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 100000000 ## 75MB, good for 3 1080p cameras with 10s of cache each, this depends on your setup.
    ports:
      - "5000:5000" # [local port]:[container port]
      - "1935:1935"
    restart: unless-stopped
```

my frigate config:

```
mqtt:
  host: 192.168.0.2
  
database:
  path: /mnt/local/frigate.db
  
ffmpeg:
  hwaccel_args: -c:v h264_qsv
  
cameras:
  VorzimmerTapo:
    ffmpeg:
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: xx
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
    snapshots:
      enabled: True
        
  BueroTapo:
    ffmpeg:
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: xx
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
    snapshots:
      enabled: True
        
  KuecheEufy:
    ffmpeg:
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: xx
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
    snapshots:
      enabled: True
    motion:
      mask:
        - 1880,58,1877,0,1465,0,1460,52
        - 0,0,247,0,258,136,0,208
        
  WZReolink:
    ffmpeg:
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: xx
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1072
    record:
      enabled: True
      retain:
        days: 10
        mode: motion
    snapshots:
      enabled: True
      
objects:
  track:
    - person
    - cat
  filters:
    person:
      threshold: 0.70
    cat:
      threshold: 0.65
      
detectors:
  coral:
    type: edgetpu
    device: usb
    
birdseye:
    enabled: False
```
 
vainfo on proxmox node:
```
root@pve:~# vainfo
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

vainfo on lxc container running docker:
```
root@dockerenv:~# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
