### DISCUSSION TITLE
Failing to start, weird "t" line in logs

### DISCUSSION THREAD

**Discussion by hockeymikey** [blakeblackshear/frigate#5334] [Ask A Question] [answered]
Here are the logs from the bootloop
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2023-02-01 11:38:57] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)

Starting migrations

[2023-02-01 11:38:57] peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

[2023-02-01 11:38:57] peewee_migrate                 INFO    : There is nothing to migrate


t

[cmd] python3 exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.`

And my config is
```
detectors:
  cpu1:
    type: cpu
    num_threads: 4
record:
  enabled: True
  retain:
    days: 15
    mode: motion
  events:
    retain:
      default: 15
      mode: active_objects
snapshots:
  enabled: True
  retain:
    default: 15
  retain:
    default: 15
    objects:
      person: 30
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
mqtt:
  host: 192.168.22.20
  user: pokeball
  password: blah
cameras:
  front1:
    ffmpeg:
      inputs:
        - path: rtsp://blah@192.168.1.40:554/h264_stream
          roles:
            - detect
            - rtmp
            - record
    record:
      events:
        required_zones:
          - driveway
          - entirescreen
    snapshots:
      required_zones:
        - driveway
        - entirescreen
    detect:
      width: 2592
      height: 1944
    zones:
      entirescreen:
        coordinates: 2592,1944,2592,0,0,0,0,1944
        objects:
          - person
      driveway:
        coordinates: 2592,789,2592,413,2061,372,1777,290,1577,400
        objects:
          - car
          - person
    motion:
      mask:
        - 1926,1019,2059,789,2343,1073,2315,1292,2209,1505,1917,1606,1812,1479,1728,1404,1795,1376,1711,1260,1694,1150,1741,1083,1915,1174
        - 1075,1944,1623,1944,1541,1627,1322,1537
```

It worked before. All I did was update the host and then it stopped working. That "t" line is strange too and there's another character above it.
