### DISCUSSION TITLE
config.yml | Proper ffmpeg indentation for RTMP camera ???

### DISCUSSION THREAD

**Discussion by The-NinthWave** [blakeblackshear/frigate#5347] [Ask A Question] [answered]
I have RTSP cameras

My container started until I added the "global" ffmpeg "input_args"in the config.yml

I am a bit confused because https://docs.frigate.video/configuration/camera_specific shows different ways of typing the arguments:

I first tried as seen from "RTMP Cameras"

```
# Optional: ffmpeg configuration specific for RTMP Cameras
ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv
```

and it failed so I kept the same arguments but tried the indentations used for Reolink cameras:

```
# Optional: ffmpeg configuration specific for RTMP Cameras
ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rw_timeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - 1
    - -f
    - live_flv
```
but it failed again

So I thought maybe it wasn't the way I typed them but the arguments themselves.
