### DISCUSSION TITLE
Time

### DISCUSSION THREAD

**Discussion by trythatagain** [blakeblackshear/frigate#5351] [Ideas]
I thought I had Firefox set for UK, but when it was showing M/D/Y and 12h instead of D/M/Y 24h, I went and checked. It seems as though you have to click a number of boxes to get it setup for UK and to use local time settings.

So can we use the pc settings itself? Or use tz=europe/london in the container? Or use something like TZ in the config file or as homepage does - 'language: en-UK # Force your locale to the UK version of English'

It seems a lot of faff when we can set it and forget it from the config file.

**Comment by NickM-27** [comment]
This is already supported in 0.12

**Reply by trythatagain** [reply]
Where? I've obviously missed it somewhere.

**Reply by trythatagain** [reply]
I'm talking about when showing events

**Reply by NickM-27** [reply]
https://deploy-preview-4055--frigate-docs.netlify.app/configuration/

```yaml
# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: None
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  experimental_ui: False
```

**Reply by NickM-27** [reply]
> I'm talking about when showing events

yes, this applies to the entire frontend

**Reply by trythatagain** [reply]
Thank you. Can't believe I missed that. I thought I looked at the configuration section for all the betas. I feel a bit stupid now.  :)

**Comment by trythatagain** [comment]
I'm obviously doing something wrong
```
ui:
  live_mode: mse
  timezone: europe/london
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  #experimental_ui: True
```
When I set Firefox to English (US) and uncheck to use operating settings etc...
I then look at the events and it's not in the UK display mode. When editing from within Frigate and saved no error's come up.
Do I need to set something else up?
