### DISCUSSION TITLE
Config File for Amcrest IP Camera

### DISCUSSION THREAD

**Discussion by mmitch2k** [blakeblackshear/frigate#5366] [Ask A Question]
Hi, does anyone have an example of a working camera config file for Amcrest IP camera (Amcrest UltraHD 4K (8MP)

The feed shows up in HA, VLC, but Frigate refuses to load when the camera is added to the config file

This is the rtsp url I am using

rtsp://admin:pswd@xx.xx.xx.xx:554/cam/realmonitor?channel=1&subtype=0&authbasic=64

**Comment by NickM-27** [comment]
You need to make an issue so we can see the logs. Amcrest works with a default config usually.

**Comment by mmitch2k** [comment]
@NickM-27 understood. trying to figure out how to generate logs. can you point me in the right direction?

**Reply by NickM-27** [reply]
how are you running frigate?

**Comment by mmitch2k** [comment]
via a docker container

**Reply by NickM-27** [reply]
from CLI run `docker logs frigate`

**Comment by mmitch2k** [comment]
can i post the results here or should i create an issue?

**Reply by NickM-27** [reply]
you should create an issue, answering all the prompts

**Comment by mmitch2k** [comment]
thanks you for your help

**Comment by trythatagain** [comment]
This is what I have for 2 Amcrest IP8M-T2499EB 4K UltraHD, they are using Dahua Firmware, but I didn't change anything when changing from Amcrest firmware. 
```
go2rtc:
  streams:
    #Front1
    front1-sub: rtsp://{FRIGATE_USER}:{FRIGATE_PASSWORD}@192.168.xx.xx/cam/realmonitor?channel=1&subtype=1
```

```
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front1-sub?video=copy
          input_args: preset-rtsp-restream
          roles: 
            - detect
```
I also have a stream for the hi stream for recording and they work fine.
