### DISCUSSION TITLE
Configuration for Reolink RLC-1212A (12MP)

### DISCUSSION THREAD

**Discussion by n3de** [blakeblackshear/frigate#5387] [Ask A Question]
Hey,

I have a Reolink RLV-1212A and based on the documentation and a few post here, I have a working config:

```yaml
detect:
  width: 896
  height: 512
  fps: 10

ffmpeg:
  #hwaccel_args: -hwaccel_output_format qsv -c:v h264_qsv
  output_args: # record audio
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy # -an

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://test:123456@192.168.0.212:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://test:123456@192.168.0.212:554/h265Preview_01_main
          roles:
            - record
            - rtmp
```
Maybe this will help someone, if searching for a valid config. However, I think the config is not perfect. I had to comment out the first line of ffmpeg. The 1212A uses h265 for the main stream and h264 for the detection. Maybe someone can optimze the config.

I also tried to us rtmp, but no configuration works. But I don't know, if rtmp will be a better config. In the past it was recommended because you get a better resolution for detection and a lower delay which is nice. If someone has an idea how to use rtmp I can try.

best regards

**Comment by NickM-27** [comment]
The 12mp won't support http_flv since it is h264 only and the reolink uses h265. That's also why your QSV hwaccel args didn't work. You should be using hevc_qsv instead.

**Reply by n3de** [reply]
Hey @NickM-27 NickM-27 thanks, The last days where bussy, so I play today a little bit. Actually I'm using a test hyper-v system with a Intel Broadwell CPU with don't support h.265 decoding. Maybe this is the reason why I didn't not get the hwaccel args working.

hwaccel_args: -hwaccel qsv -c:v hevc_qsv -load_plugin hevc_hw

frigate is using the cam, take snapshots and videos of a person is identified, but the video is lost after processing. But I hope it will work if the final server is set up, right? Because I want to test it, befor I order all reolink cams.

**Reply by NickM-27** [reply]
> Hey @NickM-27 NickM-27 thanks, The last days where bussy, so I play today a little bit. Actually I'm using a test hyper-v system with a Intel Broadwell CPU with don't support h.265 decoding. Maybe this is the reason why I didn't not get the hwaccel args working.
> 
> 
> 
> hwaccel_args: -hwaccel qsv -c:v hevc_qsv -load_plugin hevc_hw
> 
> 
> 
> frigate is using the cam, take snapshots and videos of a person is identified, but the video is lost after processing. But I hope it will work if the final server is set up, right? Because I want to test it, befor I order all reolink cams.

You'll need to elaborate I don't know what you're asking exactly or what the issue is

**Reply by n3de** [reply]
I want to setup frigate with homeassistant using reolink 1212a camaras. Actually I'm using a test system on my windows machine with hyper-v. The final server will be setup with proxmox and an google core tpu. I just want to ensure, that on my configuration will work on my final setup. The goel is to use 6 cameras to secure my home.

Actually I'm getting a live video (delayed and low fps) in homeassistant and person detection is also working. Two problems exists:

1. ffmpeg (hwaccel)
2. Videos are recorded and I see that they are processed, but after the processing there are gone. No option to view or download.

I assume, that I can fix the problems with on my final setup/server. Right?

**Reply by NickM-27** [reply]
> Actually I'm getting a live video (delayed and low fps) in homeassistant and person detection is also working. Two problems exists:
> 
> 
> 
> 1. ffmpeg (hwaccel)

If your iGPU doesn't support decoding h265 then there's no changing that. You can run `vainfo` to see what profiles are supported by your hardware

> 2. Videos are recorded and I see that they are processed, but after the processing there are gone. No option to view or download.

What do you mean by processed? Frigate does no processing on recorded videos, if they are moved to storage then they are there. You view them in the events page or the recordings page. It's really unclear if there's actually a problem (need to see error message) or if there's just confusion on how to use the frigate ui

> I assume, that I can fix the problems with on my final setup/server. Right?

There's no reason they can't be fixed now, I wouldn't pay money for more hardware until you have a better understanding of how things work and know what issues you're actual seeing / not seeing.

**Comment by n3de** [comment]
Hey, 

Under Events I see the clip and thumbnail but the clip cann't be displayed 
![image](https://user-images.githubusercontent.com/81101039/218268164-d5840ddb-245e-45a9-a9bc-eb577434e3d1.png)

After a few moments only the thumbnail can be displayed later the events are also empty. Under Media in HA I can't find any video.

In the logs I see this i a loop:

```
[2023-02-11 17:01:00] ffmpeg.reolink.record_rtmp     ERROR   : [flv @ 0x563c1bce7b40] Video codec hevc not compatible with flv
[2023-02-11 17:01:00] ffmpeg.reolink.record_rtmp     ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
[2023-02-11 17:01:00] ffmpeg.reolink.record_rtmp     ERROR   : Error initializing output stream 0:1 -- 
[2023-02-11 17:01:00] ffmpeg.reolink.record_rtmp     ERROR   : 
[2023-02-11 17:01:00] watchdog.reolink               INFO    : Terminating the existing ffmpeg process...
[2023-02-11 17:01:00] watchdog.reolink               INFO    : Waiting for ffmpeg to exit gracefully...
```

**Reply by NickM-27** [reply]
You must disable RTMP as it is not compatible with h265

```
rtmp:
  enabled: false
```

**Reply by n3de** [reply]
OK, looks better. I restart frigate with this config and the error is thrown, when a movment is dedected

```
mqtt:
  host: homeassistant
  user: usr
  password: pw
  port: 1883

detect:
  width: 896
  height: 512
  fps: 10

rtmp:
  enabled: false

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://usr:pwd@192.168.0.xxx:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://usr:pwd@192.168.0.xxx:554/h265Preview_01_main
          roles:
            - record
```
Log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-02-11 17:12:45] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2023-02-11 17:12:45] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2023-02-11 17:12:45] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-02-11 17:12:45] peewee_migrate                 INFO    : There is nothing to migrate
[2023-02-11 17:12:45] frigate.app                    INFO    : Output process started: 217
[2023-02-11 17:12:45] ws4py                          INFO    : Using epoll
[2023-02-11 17:12:45] detector.cpu                   INFO    : Starting detection process: 216
[2023-02-11 17:12:45] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2023-02-11 17:12:45] frigate.app                    INFO    : Camera processor started for reolink: 223
[2023-02-11 17:12:45] frigate.app                    INFO    : Capture process started for reolink: 224
[2023-02-11 17:12:45] frigate.mqtt                   INFO    : Turning on recordings for reolink via mqtt
[2023-02-11 17:12:45] ws4py                          INFO    : Using epoll
[2023-02-11 17:13:22] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56648]
[2023-02-11 17:13:49] frigate.http                   ERROR   : No recordings found for the requested time range
```
Here is the Events, after a few moments:
![image](https://user-images.githubusercontent.com/81101039/218268774-42df0b89-5201-4ed3-938b-c1b33162dfe4.png)

**Reply by NickM-27** [reply]
You have to enable recordings in the config

**Reply by n3de** [reply]
Hey @NickM-27 thank you very much!! I reduce the resolution to 8MP to get 25fps but it still do not look as smooth as hoped. But I can only watch the video if I download it. In frigate and HA the video is not playable.

**Reply by NickM-27** [reply]
That's because it is H265, you need your browser to support h265 playback

**Reply by n3de** [reply]
I thought Edge supports h.265 but with Chrome it works. But my mobile device can't show it. Is it possible, to transcode the files automatically?

**Reply by NickM-27** [reply]
You could setup transcoding but on a CPU that doesn't do hwaccel that would be quite computationally expensive

**Reply by n3de** [reply]
Is a Ryzen 7 Pro CPU enough to transcode a video from h265 to h264? But the 8MP setting with 25fps seems to be h.264 because I can view the videos. Great!! Thank you very much!!

**Reply by NickM-27** [reply]
> Is a Ryzen 7 Pro CPU enough to transcode a video from h265 to h264? 

It might be enough but it is still inefficient and would use considerably more CPU resources

> But the 8MP setting with 25fps seems to be h.264 because I can view the videos. Great!! Thank you very much!!

No, reolink only supports h265 for 8MP setting. Chrome supports h265 as of version 108 on desktop and 109 on mobile

**Comment by haralake** [comment]
Hello @n3de , @NickM-27 !
I read that reolink cameras has h264 main stream on a lower resolution.
https://www.reddit.com/r/homeassistant/comments/sopd9a/hidden_h264_stream_in_reolink_rlc_810a_probably/

For example rlc-810a and rlc-811a have h264 main stream on 2304x1296 and 2560x1440 resolutions.

Can you please confirm if the same occurs on rlc-1212a?

Also i read that the only h264 sub stream is on 640x320 resolution. Is that true for the rlc-1212a?

**Comment by n3de** [comment]
@haralake 
Actually I do not have a 1212a. I bought it from a friend to test if it works and for me it works. I actually setting up my server and get my own 1212a. But I can ask my friend, if he can check the videos with different resolutions.

**Comment by tomtom215** [comment]
The way to get it to work is to use the [desktop app to enable RTMP](https://support.reolink.com/hc/en-us/articles/900004435763/) and then adding the [correct URL scheme](https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player/)

**Comment by mirisbowring** [comment]
Is your cam still working? Got a 1212A yesterday and i cannot use rtsp...
Everything is enabled in the settings but when i paste the rtsp link (with username and password) into VLC (to test), VLC continuously asks me for username and password.

**Reply by maxi1134** [reply]
> Is your cam still working? Got a 1212A yesterday and i cannot use rtsp... Everything is enabled in the settings but when i paste the rtsp link (with username and password) into VLC (to test), VLC continuously asks me for username and password.

MAnaged to do it? I am thinking of ordering it now

**Reply by n3de** [reply]
I had to pause my project and unfortunately didn't get any further. At the time, I had tested it with a cam from a neighbor and therefore can't help you at the moment.

**Reply by mirisbowring** [reply]
For me it's working 😄 

```yaml
go2rtc:
  streams:
    K41:
      - rtsp://username:password@10.100.3.47:554/h265Preview_01_main
    K41_sub:
      - rtsp://username:password@10.100.3.47:554/h264Preview_01_sub
...
cameras:
  K41: # <------ Name the camera
    detect:
      enabled: true
      width: 896
      height: 512
      fps: 10
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/K41_sub
          roles:
            - detect
          hwaccel_args: preset-intel-qsv-h264
        - path: rtsp://127.0.0.1:8554/K41
          roles:
            - record
          hwaccel_args: preset-intel-qsv-h265
    live:
      stream_name: K41_sub
    objects:
      filters:
        person:
          min_area: 1000
          min_score: 0.7

    zones:
      zone_2:
        coordinates: 0.527,0.284,0.539,0,0.767,0,0.801,1,0.189,1,0.274,0.818
        inertia: 3
        loitering_time: 0
    review:
      detections:
        required_zones: zone_2
      alerts:
        required_zones: zone_2
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
```
