### DISCUSSION TITLE
Avoiding fake events

### DISCUSSION THREAD

**Discussion by lorenzomartini1** [blakeblackshear/frigate#5427] [Ask A Question]
Hi, i'm a newbie on frigate...
I get a lot of fake events like this:
[[![https://i.ibb.co/2NzwRyd/71f77556-560f-42dd-b6b6-d6da53d29d86.jpg](url)](https://i.ibb.co/2NzwRyd/71f77556-560f-42dd-b6b6-d6da53d29d86.jpg)](https://i.ibb.co/2NzwRyd/71f77556-560f-42dd-b6b6-d6da53d29d86.jpg)
i'm listening to MQTT and i get lot of fake events with type _update_.

I've got 3 reolink cameras, this is my `frigate.yaml`:
```
mqtt:
  host: 192.168.1.232
  port: 1883
  user: mqtt_user
  password: mqtt_pw

detect:
  enabled: true
  width: 960
  height: 540
  fps: 10
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 60

cameras:
  retro_alto:
    ffmpeg:
      inputs:
        - path: rtmp://<ip>/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password
          roles:
            - clips
            - record
            - detect

  porta_vista_nord:
    ffmpeg:
        inputs:
          - path: rtmp://<ip>/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password
            roles:
              - clips
              - record
              - detect
              
  porta_vista_sud:
    ffmpeg:
      inputs:
          - path: rtmp://<ip>/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password
            roles:
              - clips
              - record
              - detect
            
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 7
    mode: all
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 10

ffmpeg:
  hwaccel_args:
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
    
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "solid"

rtmp:
  enabled: False
  
live:
  height: 480
  quality: 8
    
birdseye:
  enabled: True
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

```
