### DISCUSSION TITLE
Restream & gortc config

### DISCUSSION THREAD

**Discussion by DrSpaldo** [blakeblackshear/frigate#5432] [Ask A Question] [answered]
I've been holding off updating beta's due to time constraints (currently on 3) and will update to Beta 7. Before doing so, I just wanted to clarify the new restream config as I am a little confused after reading the docs.

https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream/#with-sub-stream

This mentions the config:

```
go2rtc:
  streams:
    rtsp_cam: 
```

it also has the following all in the same config file:

```
cameras:
  rtsp_cam:
    ffmpeg:
```

Can I confirm that the go2rtc streams section now goes all in the same config file? config.yaml ?

Thanks

**Comment by NickM-27** [comment, marked as answer]
yes, the go2rtc config is placed under the go2rtc header exactly as their docs explain (so 100% of go2rtc features are supported in frigate)

**Comment by DrSpaldo** [comment]
Thanks @NickM-27, so that section goes inside the config.yml? Then does that mean the frigate-go2rtc.yaml file still exists as well?

**Reply by NickM-27** [reply]
> Thanks @NickM-27, so that section goes inside the config.yml?

Yes

> Then does that mean the frigate-go2rtc.yaml file still exists as well?

No, that file is no longer existing.

**Comment by DrSpaldo** [comment]
Alright, thanks @NickM-27 . Do we add the old part of the frigate-go2rtc.yaml inside as well:

```
log:
  format: text

webrtc:
  listen: ":8555"
  candidates:
    - 192.168.1.100:8555 
    - stun:8555
```

**Reply by NickM-27** [reply]
You'll want to add your webRTC candidates but everything else is done automatically

**Comment by DrSpaldo** [comment]
Thanks @NickM-27 , looks like I missed the change in the docs/release notes

**Comment by DrSpaldo** [comment]
If I'm currently using nvidia acceleration as follows:

```
cameras:
  frontdoor:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://USER:PASS@192.168.1.101:554/cam/realmonitor?channel=1&subtype=1
```

Would I instead put that into the go2rtc section? then just use the **input_args: preset-rtsp-restream** in the camera area?

**Reply by NickM-27** [reply]
The nvidia part stays in frigate

**Reply by DrSpaldo** [reply]
Alright, so it would look something like this then?

```
cameras:
  rtsp_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
```
