### DISCUSSION TITLE
Wyze V3 working unable to view recordings on Wyze Pan V1 wz_mini_hacks

### DISCUSSION THREAD

**Discussion by pdobrien3** [blakeblackshear/frigate#5493] [Ask A Question]
I have a V3 and a Pan V1 both with wz_mini installed and using rtsp streams (both hi rez and low rez). I am using Frigate to record streams and do object detection. The V3 work pretty flawless outside of a little pixilation here and there. My settings are exactly the same for both cameras. I can see both streams on both cameras in frigate and can see object detection clips on both cameras in frigate. The problem comes when i try to view recoded video clips in frigate. the V3 plays fine, the Pan V1 wont play the clips. I started to play and noticed that if i download the V3 files from frigate, they will play in just about anything, including windows media player. The Pan V1 will only play in VLC. I am stuck on where to turn to further diagnosis this issue.

here are the ffmpeg probes for both cameras from frigate:

V3
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "20/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 360, "width": 640 } ] } },

{ "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "20/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1080, "width": 1920 }, { "avg_frame_rate": "0/0", "bit_rate": "256000", "codec_long_name": "PCM signed 16-bit big-endian" } ] } } ]

Pan V1
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "5/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 360, "width": 640 } ] } },

{ "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1080, "width": 1920 }, { "avg_frame_rate": "0/0", "bit_rate": "128000", "codec_long_name": "PCM signed 16-bit big-endian" } ] } } ]

The V3 is running 4.36.9.139 and the Pan V1 is running 4.10.8.1002. I am under the impression that 4.10.8.1002 is the last version before Wyze started to work against wz_mini.

any assistance would be greatly appreciated. thanks.

**Comment by NickM-27** [comment]
there's not really much to go off of here. Would need to see logs, config, etc.

**Comment by pdobrien3** [comment]
Here is the Pan V1 config:

```
  Pan_V1_camera: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-udp
      output_args: 
        record: preset-record-generic-audio-aac
        detect: -dn -an -f rawvideo -pix_fmt yuv420p
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video7_unicast # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video6_unicast
          roles:
            - record          
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
      max_disappeared: 25
      stationary:
        interval: 10
        threshold: 60
    best_image_timeout: 30
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
    motion:
      contour_area: 20
      threshold: 25
      mask:
        - 640,330,640,360,435,360,440,329  # Date and Time
      improve_contrast: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
```

I can bug los to debug but already looked at that and not really sure what I am looking for as it happens during playback.

**Reply by NickM-27** [reply]
You might try using `preset-record-generic` so no audio is saved and see if that works better, I have a feeling it is the audio that is causing problems

**Comment by pdobrien3** [comment]
Didnt fix it.  Snapshot work perfect.  When I switch to recordings i get:

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

**Reply by NickM-27** [reply]
what do the frigate logs show though?

**Comment by pdobrien3** [comment]
If I try to play the file direct from frigates data folder in windows media player, it plays with no video and sound.  If I export out of frigate, it gives an error.  Both files play fine with VLC.  The one played directly from frigates data folder was recorded with preset-record-generic-audio-aac the other with preset-record-generic

**Comment by pdobrien3** [comment]
so many logs.  give me something to target/look for

**Reply by NickM-27** [reply]
there should be no problem just using the copy button to copy the logs and paste them all here, if there's a lot then there is likely something interesting to see

**Comment by pdobrien3** [comment]


**Reply by NickM-27** [reply]
oh, you have debug logs on, nevermind seems like there's nothing useful. If the video has issues then I don't know why it is failing but seems something is encoded incorrectly keeping it from being playable by a browser but VLC has some handling for it.

**Reply by blakeblackshear** [reply]
Generally speaking, debug logs make it harder to find error messages. I recommend leaving the default values in place unless you are trying to troubleshoot something specific and want to know what is happening at a detailed level. Otherwise, they just make it difficult to provide support.

**Comment by pdobrien3** [comment]
anything i can use to analyze both the v3 and pan v1 video to see what is different?

**Comment by pdobrien3** [comment]
i only changed to debug from info when you asked for logs. otherwise, there was nothing in the logs other than the general startup stuff

**Reply by NickM-27** [reply]
Right, then that is what is important to know. Debug won't provide better info about crashes / failure to play. Anyway, you could maybe try comparing the codec differences between each camera clip in VLC and see if there is a difference.

**Comment by pdobrien3** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/28842285/218790804-d7b31393-5126-47d7-9348-fcba73066e52.jpg)
![unnamed](https://user-images.githubusercontent.com/28842285/218790892-6531c98b-aad9-48d6-9fe9-47fdcc2546a9.jpg)
does that provide any info?

**Reply by NickM-27** [reply]
Well it's interesting they have different audio rates and one has more video information. It's not clear however which is which. I'd expect if you set the audio to none that one wouldn't have audio

**Comment by pdobrien3** [comment]
those are more than likely before the audio change in the config.yaml. the top one is the one that doesnt play in frigate

**Reply by NickM-27** [reply]
I'm not sure, seems it's including extra encoding image information which I guess could be the problem.

**Comment by pdobrien3** [comment]
if i change something in config.yaml, does it matter if i do a restart through the ui or a container start/stop?

**Reply by NickM-27** [reply]
No, it is the same as long as a restart occurs

**Comment by pdobrien3** [comment]
Just an update on where I am with the Pan V1.  I have recordings working without audio.  I also have been unable to get the `ENABLE_SELFHOSTED_MODE="true"` to work.  Even though it is enabled, I can still see video in the app.  Here are my settings;

```
RTSP_HI_RES_ENABLED="true"
RTSP_HI_RES_ENABLE_AUDIO="false"
RTSP_HI_RES_MAX_BITRATE="2048"
RTSP_HI_RES_TARGET_BITRATE="1024"
RTSP_HI_RES_ENC_PARAMETER="4"
RTSP_HI_RES_FPS="15"

RTSP_LOW_RES_ENABLED="true"
RTSP_LOW_RES_ENABLE_AUDIO="false"
RTSP_LOW_RES_MAX_BITRATE="2048"
RTSP_LOW_RES_TARGET_BITRATE="1024"
RTSP_LOW_RES_ENC_PARAMETER="4"
RTSP_LOW_RES_FPS="5"

```
The encoding parameter setting of 4 is what made everything start working.

relevant frigate config:

```
  Pan_V1_camera: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-udp
      output_args: 
        record: preset-record-generic
        detect: -dn -an -f rawvideo -pix_fmt yuv420p
```

**Comment by mitchross** [comment]
Try using https://github.com/mrlt8/docker-wyze-bridge and integrating that into frigate and see if your issues still appear. This is a hackless firmwareless approach. This is what I use personally.

**Reply by pdobrien3** [reply]
> Try using https://github.com/mrlt8/docker-wyze-bridge and integrating that into frigate and see if your issues still appear. This is a hackless firmwareless approach. This is what I use personally.

kinda wonky but i got it up.  i dont really get what streams to use for the wyze bridge. would you mind sharing your frigate config?  Right now i am using one stream from wz_mini and one from the wyze-bridge.  no motion or events yet so not sure if it is working. and no audio record yet either. 

```
  wyze_pan_camera: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args: 
        record: preset-record-generic
        detect: -dn -an -f rawvideo -pix_fmt yuv420p
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video7_unicast # <----- Update for your camera
          input_args: preset-rtsp-udp
          roles:
            - detect
        - path: rtsp://192.168.xx.xxx:8555/wyze-pan-camera
          roles:
            - record 
```
