### DISCUSSION TITLE
Only detect person if zone hit on at least 2 cameras

### DISCUSSION THREAD

**Discussion by errolsancaktar** [blakeblackshear/frigate#5500] [Ask A Question]
Not sure if this is a thing but I run into false positives in my front yard both from weird angles preventing good zone lines to holiday decorations throughout the year. Is there a good way to require a person within a zone to be seen by at least 2 cameras?

**Comment by kdill00** [comment]
I would just use home assistant or mqtt and create some kind of outside notification only triggered when those two zones are crossed. I do this as a work around for enter exit count on a building as frigate reports the order an object crosses zones on each camera when tracking it. You could set up multiple smaller zones on each camera and require both to be hit for an event(I think, required zones may just be any of them each is required haven’t tested). Or raise the threshold for an object detected in the zone. It’s still not perfect but I’m okay with it as this isn’t a perfect science. When an object is seen by a camera in frigate it does not communicate information about that object to other cameras. Frigate is supremely complimented by home assistant and making use of automations. You will need bootleg a solution.

**Reply by errolsancaktar** [reply]
That's kind of what I was thinking. How do you handle it? Node red/automation?  I tried doing an automation with each camera being a trigger and the condition of the other camera but I can't get it to fire.

**Reply by itkfilelor** [reply]
I haven't need this so this is only a theory, but you might try using the mqtt events described [here](https://deploy-preview-4055--frigate-docs.netlify.app/guides/ha_notifications). Use the ```before``` and ```after``` endpoints to toggle an input_boolean in HA for the two(or more) zones.
in the same automation used to trigger the booleans, set a [choose](https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions) path the send the relevant motion data also depicted in the docs if both are 'x' are true. 
something like:
```
  trigger:
    - platform: mqtt
      topic: frigate/events
      value_template: "{{ value_json.after.camera }}"
      payload: flood_light
      id: flood_light
    - platform: mqtt
      topic: frigate/events
      value_template: "{{ value_json.after.camera }}"
      payload: front_door
      id: front_door
    - platform: mqtt
      topic: frigate/events
      value_template: "{{ value_json.before.camera }}"
      payload: flood_light
      id: flood_light
    - platform: mqtt
      topic: frigate/events
      value_template: "{{ value_json.before.camera }}"
      payload: front_door
      id: front_door
  action:
    - choose:
      - condtions: 
        # set the bool to true if motion event in front yard is detected by flood_light
        - "{{'front_yard_flood' in trigger.payload_json.after.entered_zones }}"
        - "{{ trigger.id == 'flood_light' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.front_yard_motion_detected_flood_light
      - condtions:
        # set the bool to true if motion event in front yard detected by flood_light has ended  
        - "{{'front_yard_flood' in trigger.payload_json.before.entered_zones }}"
        - "{{ trigger.id == 'flood_light' }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.front_yard_motion_detected_flood_light
      - condtions:
        # set the bool to true if motion event in front yard is detected by flood_light
        - "{{'front_yard_front_door' in trigger.payload_json.after.entered_zones }}"
        - "{{ trigger.id == 'front_door' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.front_yard_motion_detected_front_door
      - condtions:
        # set the bool to true if motion event in front yard detected by flood_light has ended  
        - "{{'front_yard_front_door' in trigger.payload_json.before.entered_zones }}"
        - "{{ trigger.id == 'front_door' }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.front_yard_motion_detected_front_door
    - condition: 
      # stops the whole automation here if both do not equate true
      # if you will need more that one of these 'multi-zones' you will need to 
      # set up more 'chooses' for each, if you need more than 2 it can get very
      # lengthy jinja is not as versitile as its parent, Python.
        - "{{ states('input_boolean.front_yard_motion_detected_front_door') == 'on'}}"
        - "{{ states('input_boolean.front_yard_motion_detected_fllod_light') == 'on'}}"
    - service: # This is where the action happens if both camera zones detect a person/cat/bear/etc. 
    
    ```

**Reply by kdill00** [reply]
Here’s my example automation for the entry at my business for counting people entering and disregarding exits. I just use a regular home assistant automation, created a “utility meter” that resets daily that tracks a counter helper which is increased by the automation every time it runs. In my automation I have it set to only trigger at the end of the event to reduce double counting. You may not want that.  Conditions are the key to making this work.

```
alias: counter
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: slidingdoors
    value_template: "{{ value_json.after.camera }}"
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.payload_json['after']['entered_zones'] ==
          ['personcount','personcount2'] }}
      - condition: template
        value_template: >-
          {{ trigger.payload_json['before']['entered_zones'] ==
          ['personcount','personcount2'] }}
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'end' }}"
action:
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.personcounttest
mode: queued
max: 100
```

as the zones show in the order the object enters them, you use that order to track direction.  The best way to start is to go to integrations in homeassistant and hit configure on MQTT broker and put frigate/events into the listening box, select json format and hit listen. Then go hop and dance and walk around your cameras to tweak it. Here are a few more example automations I did which can help you get to the information you need in the event. I use these when I need to find object sizes and ratios averages on new cameras or when things change. It spits the numbers to a HA sensor that averages it. 

```
alias: garagedrivecarratioarea
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: garagedrive
    value_template: "{{ value_json.after.camera }}"
condition:
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'end' }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['has_clip'] == true }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'car' }}"
action:
  - event: garagedrivecarratio
    event_data:
      name: garagedrivecarratio
      customData: "{{ trigger.payload_json['after']['ratio'] | round(5) }}"
  - event: garagedrivecararea
    event_data:
      name: garagedrivecararea
      customData: "{{ trigger.payload_json['after']['area'] | int }}"
mode: queued
max: 10


And then under template platform in your home assistant config, sensors to catch the posted data


template:
  -  trigger:
      - platform: event
        event_type: garagedrivecarratio
     sensor:
      - name: "GarageDriveCarRatio"
        state: '{{ trigger.event.data.customData }}'
        unit_of_measurement: ratio 
  -  trigger:
      - platform: event
        event_type: garagedrivecararea
     sensor:
      - name: "GarageDriveCarArea"
        state: '{{ trigger.event.data.customData }}'
        unit_of_measurement: Area
```
