### DISCUSSION TITLE
Preferred esp32cam firmware?

### DISCUSSION THREAD

**Discussion by 18923** [blakeblackshear/frigate#5529] [General]
I am using an esp32cam with Tasmota firmware. I can view the Snapshots but cannot play the Clips. Is there a preferred firmware to use for this camera? Here is the code I am using, with results below.

```
  Cam48:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.48:8554/mjpeg/1
        # - path: http://192.168.0.48:81/stream

          roles:
            - detect # only if you want object detection
            - clips # only if you want to record video and stills
    detect:    
      width: 640 #800     # e.g. 1280
      height: 360 #600 # < your camera resolution height >   # e.g. 720            
    rtmp:
      enabled: false

```

![Frig1](https://user-images.githubusercontent.com/59022856/219678924-641e06ad-346f-4439-9391-ceb09184b760.jpg)
![Frig2](https://user-images.githubusercontent.com/59022856/219678958-71d5478c-7fe8-43e6-94e2-789e18f77c7d.jpg)
