### DISCUSSION TITLE
No Still Images on RC2

### DISCUSSION THREAD

**Discussion by bm55** [blakeblackshear/frigate#553] [Ask A Question] [answered]
@blakeblackshear It appears that RC2 is not saving snapshots (jpg) file. If I run docker with RC1 image, I do see both jpg and mp4 in http://192.168.0.55:5000/clips/

**Comment by paularmstrong** [comment, marked as answer]
Have you updated your config to enable snapshots?

```yaml
cameras:
  my_camera:
    clips:
      enabled: true
    snapshots:
      enabled: true
```

Please share your config to double check.
