### DISCUSSION TITLE
Trigger only one notification based on event

### DISCUSSION THREAD

**Discussion by farnots** [blakeblackshear/frigate#559] [Ask A Question] [answered]
Hello,

I just tried the RC1 and I'm impressed by the number of new features and the awesome new HomeAssistant integration.
I follow the [Notification Exemple](https://github.com/blakeblackshear/frigate/blob/release-0.8.0/docs/notification-examples.md) for Telegram :

```
  - alias: Notify of events
    trigger:
      platform: mqtt
      topic: frigate/events
    action:
      - service: notify.telegram_full
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
          data:
            photo:
              # this url should work for addon users
              - url: 'http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg'
                caption : 'A {{trigger.payload_json["after"]["label"]}} was detected on {{ trigger.payload_json["after"]["camera"] }} camera'
```

But as specified all event from mqtt are directly published in my Telegram feed.

> Here is a simple example of a notification automation of events which will update the existing notification for each change. This means the image you see in the notification will update as frigate finds a "better" image.

This means for an event around 30sec I get **5** notifications on Telegram (and 3 of them are the same thumbnail). Does anyone have an idea how to tweaks the automation to have only **1** notification (not necessary the best image).
I would love to have the same kind of data found in the events panel on frigate and **1** (and only one) notification for each event. 

Also, do you have any idea why I got 3 of them with exactly the same thumbnail ? I understand having multiple mqtt message so multiple event, but I dont understand why I got events with the same data.

Thanks a lot for you help and thanks @blakeblackshear for your hard work ❤️
