### DISCUSSION TITLE
go2rtc streams don't start unless triggered by vlc?

### DISCUSSION THREAD

**Discussion by thinkloop** [blakeblackshear/frigate#5607] [Ask A Question]
I migrated my streams from direct access to go2rtc like so:

```
go2rtc:
  webrtc:
    candidates:
      - nas.example.com:8555
      - stun:8555
  rtsp:
    username: "qqq"
    password: "zzz"  
    driveway:
      - rtsp://xxx:yyy@driveway.cams.example.com:554/11
    driveway-sub:
      - rtsp://xxx:yyy@driveway.cams.example.com:554/12
    lightwall:
      - http://lightwall.cams.example.com/flv?port=1935&app=bcs&stream=channel0_main.bcs
    lightwall-sub:
      - http://lightwall.cams.example.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs
    package:
      - "ffmpeg:rtsp://xxx:yyy@package.cams.example.com:554/stream0#video=copy#audio=copy"
    package-sub:
      - "ffmpeg:rtsp://xxx:yyy@package.cams.example.com:554/stream1#video=copy#audio=copy"

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway-sub
          roles:
            - detect

  lightwall:
    ffmpeg:   
      #input_args: preset-http-reolink
      inputs:
        - path: rtsp://127.0.0.1:8554/lightwall
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lightwall-sub
          roles:
            - detect
            - 
  package:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/package
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/package-sub
          roles:
            - detect

```
There are 13 pairs of main/sub streams, some with direct access to the camera, and some through ffmpeg if direct access did not work. When frigate starts up, 5 streams start up normally, but the rest show the black error screen "No frames have been received, check error logs". They remain like that indefinitely until I access the go2rtc streams through vlc. Then 5-10s after that they "start up" in frigate. It's like vlc triggered them. 

Any idea what that's about?
