### DISCUSSION TITLE
Not quite understanding zones

### DISCUSSION THREAD

**Discussion by Buckeyes1995** [blakeblackshear/frigate#5620] [Ask A Question]
Probably a stupid question, but...

I set up a zone for an area I don't want events detected.  In my config.yml I set that zone to only detect a 'zebra', assuming that the rest of the frame not covered by the zone would continue reporting people, cats, and dogs (sorry, at work and can't paste my config).  It looks like that is not happening and having a 'zone' overrides all other event detection?

If so, how can I ignore people in the zone and still get reports for people outside of the zone?

Thanks.

**Comment by NickM-27** [comment]
If you make zones required then an object must enter that zone for an event to be created. 

Basically, you should create zone(s) for all areas of interest and make them all required.

**Reply by Buckeyes1995** [reply]
Ah.. so just so I'm clear...

I should create a zone(s) for areas that I *DO* want a person detected and Frigate will ignore detection for any person outside of that zone(s)?

**Reply by NickM-27** [reply]
Assuming that you set required_zones https://deploy-preview-4055--frigate-docs.netlify.app/configuration/zones#restricting-events-to-specific-zones

**Reply by Buckeyes1995** [reply]
Yup, I did.  That's the best way to handle it?; i.e. there's no way to simply exclude a defined zone and the rest is detected as if no zones were set?

**Reply by NickM-27** [reply]
There's no way to do that because you could easily just create one zone that covers all the parts that are interesting. Also no reason to define objects if it matches all objects that camera is tracking

**Reply by Buckeyes1995** [reply]
Great, thanks. Will update tonight and report back.  It's weird.. I did just notice I got a notification this morning about the Amazon guy dropping off something on the front porch AFTER I had set up the zone as described above.  Interestingly the page said no clip was available.

**Comment by kirsch33** [comment]
@NickM-27 related to this topic, i want to record 24/7 but i only want an event to be created for my required zones. does setting required zones in events under "record" in the config file contradict or overrule setting the retain mode to all? For example I have:
```
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    required_zones:
      - back_yard
      - front_yard
      - front_driveway
```

would this setup still save 24/7 recordings for 14 days or only events in those required zones for 14 days? i just want to limit the creation of an event for notification reasons, not limit my recordings.

**Reply by NickM-27** [reply]
As you can see by the config structure, the required_zones is only applied to `events`. 24/7 recordings are not affected by zones at all

**Reply by Buckeyes1995** [reply]
Nick,

Is that snippet of code under your individual cameras or is it global in your config.yaml file?  When I put put similiar code to yours under my camera record: I get errors and it won't start.

**Reply by NickM-27** [reply]
Looks like you commented then deleted. Your config was invalid because you forgot the `retain` part, the same config can be applied per camera.

**Reply by Buckeyes1995** [reply]
ah, yeah I had another issue.. just put it back and it's working now.

PS. How did you post your 'neat' config above?  When I post in a code block it runs it all horitontal; not vertical like yours.

**Reply by NickM-27** [reply]
You need to use three backticks above and below the code. You can also put a language type at the top. 

```yaml
some:
  config: thing
```

![Screen Shot 2023-03-01 at 14 32 40 PM](https://user-images.githubusercontent.com/14866235/222269683-86c558d7-7ea2-46b8-83a7-1fa73c9a746a.png)

**Comment by Buckeyes1995** [comment]
Clearly I'm still doing something stupid.. looked at the zone in the Debug feed and people walking by are triggering the event even though they are clearly outside of the zone.  Any ideas?

```
cameras:
  front_porch:
    ffmpeg:
      inputs:
        - path: ****
          roles:
            - detect
        - path: ****
          roles:
            - record     
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p  
    record:
      enabled: True
      retain:
        mode: all
        days: 4
      events:
        required_zones:
          - front_yard_and_porch  
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 4
      required_zones:
        - front_yard_and_porch 
    zones:
      front_yard_and_porch:
        coordinates: 1175,489,1280,577,1120,720,1014,720,640,720,224,720,245,720,193,619,66,400,24,221,141,147,258,143,369,109,499,132,789,217,1189,347
        objects:
          - person
          - dog
          - cat
```
