### DISCUSSION TITLE
Best practices or good ideas for long term storage?

### DISCUSSION THREAD

**Discussion by veqryn** [blakeblackshear/frigate#5626] [Ask A Question]
### Describe the problem you are having

So I'm new to Frigate, and have been playing around getting the docker container running successfully, etc, to see if I can use this to replace my current setup (Alarm dot com).

I was wondering what best practices or at least what some good options were for long term storage of 24/7 recordings?

I can see that the `/media/frigate/recordings` folder contains 8-12 second segments of video, and having looked at a few other issue/tickets raised I see that this is on purpose (smaller cache needed, faster alerting of events, etc) and that these files should be treated as internal to Frigate and not a place to hook up or mount to other systems like Plex or whatever.

I saw that there is an endpoint for getting the event videos, which I assume concatenates the 10s videos of each event together for download.
But what if you are doing 24/7 recording, and want to store it all long term, as efficiently as possible.  Or they want to mount the files to another application for viewing?
Are people concatenating videos by script into 1 hour segments and transcoding to H.265 or AV1 or something more efficient, before moving to a NAS?

I'm definitely not an expert, and this is one of my first forays into replacing my expensive and inadequate vendor controlled and locked-in system, so I'm open to ideas and suggestions.

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  enabled: False

detectors:
  cpu1:
    type: cpu
    num_tthreads: 3

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    pre_capture: 10
    post_capture: 20
    retain:
      default: 15
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: False
  timestamp: False
  bounding_box: False
  crop: False
  retain:
    default: 10
    objects:
      person: 15

ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  wifi_cam1_4mp_pan_tilt:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.z.z:554/cam/realmonitor?unicast=true&proto=Onvif&channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:yyy@192.168.z.z:554/cam/realmonitor?unicast=true&proto=Onvif&channel=1&subtype=1
          roles:
            - detect
    record:
      enabled: True
    detect:
      enabled: True
      # Main stream is 2560x1440@25fps
      # Substream is 640x480@15fps
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: True
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
"[\n  {\n    \"return_code\": 1,\n    \"stderr\": {},\n    \"stdout\": {}\n  },\n  {\n    \"return_code\": 1,\n    \"stderr\": {},\n    \"stdout\": {}\n  }\n]"
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"103":{"cpu":"1.7","mem":"1.8"},"113":{"cpu":"0.0","mem":"0.2"},"129":{"cpu":"0.0","mem":"0.1"},"130":{"cpu":"0.0","mem":"0.1"},"131":{"cpu":"0.0","mem":"0.1"},"132":{"cpu":"0.0","mem":"0.1"},"16":{"cpu":"0.0","mem":"0.0"},"18":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"277":{"cpu":"0.0","mem":"1.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"0.1"},"283":{"cpu":"0.3","mem":"1.2"},"285":{"cpu":"1.0","mem":"1.1"},"287":{"cpu":"1.7","mem":"1.1"},"289":{"cpu":"3.3","mem":"1.1"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"0.0","mem":"0.8"},"294":{"cpu":"18.3","mem":"0.7"},"295":{"cpu":"0.0","mem":"0.5"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"1.3","mem":"0.5"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"548":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"5957.3","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"1.11,"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":106.39,"pid":283}},"service":{"last_updated":1677748135,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":84.9,"mount_type":"tmpfs","total":86.0,"used":1.1},"/media/frigate/clips":{"free":113430.7,"mount_type":"ext4","total":125524.4,"used":6934.8},"/media/frigate/recordings":{"free":113430.7,"mount_type":"ext4","total":125524.4,"used":6934.8},"/tmp/cache":{"free":999.7,"mount_type":"tmpfs","total":1000.0,"used":0.3}},"temperatures":{},"uptime":374,"version":"0.12.0-27a31e7"},"wifi_cam1_4mp_pan_tilt":{"camera_fps":5.0,"capture_pid":289,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":294,"pid":287,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Amcrest ASH41 Smart Home 4MP Wi-Fi PTZ Camera
