### DISCUSSION TITLE
Simplifying my config

### DISCUSSION THREAD

**Discussion by dimmanramone** [blakeblackshear/frigate#5635] [Ask A Question]
Hi,

I'm quite new to Frigate. I started with setting it up yesterday and I now it is up and runnning but I'm looking into simplifying my configuration (I guess I have things that are not needed)  as well as get the best results with it, performance and quality of the stream and snapshots.

My config is a combination of the documentation but as well configs from other people that are using Wyze v3.

For the RSTP stream I use Wyze Bridge and my config file is the following. 

The Frigate container is running right now in a QNAP NAS (Intel based with hardware accelaration) with a Coral USB, and I'm using 2 Wyze v3 cameras

```
mqtt:
  host: ip
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -vsync
    - drop
    - -use_wallclock_as_timestamps
    - '1'

objects:
  track:
    - person

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects

cameras:
  hall_cam:
    ffmpeg:
      input_args:
        - -fflags
        - nobuffer+genpts+discardcorrupt
      inputs:
        - path: rtsp://ip/hall-cam
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False

  living_room_cam:
    ffmpeg:
      input_args:
        - -fflags
        - nobuffer+genpts+discardcorrupt
      inputs:
        - path: rtsp://ip/living-room-cam
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False
```

Any help would be appreciated.

**Comment by NickM-27** [comment]
Your camera config is overriding the input_args with just

```yaml
      input_args:
        - -fflags
        - nobuffer+genpts+discardcorrupt
```

this is highly discouraged as there are many other input args which are needed. Your args which are defined globally are also being completely ignored when you set the args at the camera level.

There's also no reason to be setting 

```yaml
database:
  path: /media/frigate/frigate.db
```

since that is the default

**Comment by dimmanramone** [comment]
@NickM-27 

What about `detect`, `snapshots` and `roles`? Can I set them globally?

Anything in the `input_args` that shouldn't be there or something that I'm missing?

Does record have any setting for the fps?

**Reply by NickM-27** [reply]
> @NickM-27
> 
> What about `detect`, `snapshots` and `roles`? Can I set them globally?

If you only have one stream then there is no reason to set roles as all roles are automatically applied if there is only 1 stream for that camera.

> Anything in the `input_args` that shouldn't be there or something that I'm missing?

I'd suggest not setting it and letting Frigate use its defaults

> Does record have any setting for the fps?

Recordings are a direct copy of the stream written directly to mp4, no aspects of the stream are changed

**Reply by dimmanramone** [reply]
> If you only have one stream then there is no reason to set roles as all roles are automatically applied if there is only 1 stream for that camera.

Not really sure what you mean by that :) But I guess I can't simplify my configuration more, `detect`, `snapshots` and `roles` should be there for both cameras configuration?

Do you have any experience with Wyze cameras? I'm wondering which works best with frigate, the official RSTP firmware, wyze bridge or wz_mini_hacks?

**Reply by NickM-27** [reply]
> > If you only have one stream then there is no reason to set roles as all roles are automatically applied if there is only 1 stream for that camera.
> 
> Not really sure what you mean by that :) But I guess I can't simplify my configuration more, `detect`, `snapshots` and `roles` should be there for both cameras configuration?

Frigate recommends better cameras which have multiple streams (a full res stream, and then 1 or more sub streams which are lower resolution). In this case you would define one stream for recording and then a sub stream for detect. In your case you only have one stream so it does not matter. You could just remove the roles part entirely.

> Do you have any experience with Wyze cameras? I'm wondering which works best with frigate, the official RSTP firmware, wyze bridge or wz_mini_hacks?

I originally used wyze cams when I first started with frigate over a year ago and then once I got good cameras I never used it again because its stream was incredibly buggy. Anecdotally I have heard wyze users have had success with wyze bridge.

**Comment by dimmanramone** [comment]
@NickM-27 Which cameras did you got? And is it big difference with the wyze?

**Reply by NickM-27** [reply]
I have a few reolink which I also wouldn't recommend. They are working well now but were a lot of hassle. I have an amcrest camera which has been rock solid as well as bench testing a hikvision camera which has been solid as well.

The problem is wyze does not stick to the rtsp protocol so there are all kinds of stream issues, packet loss, invalid timestamps, etc. which cause problems

**Reply by dimmanramone** [reply]
Thanks it seems that everything still running smoothly after removing all the unneeded configuration. I did also found out that there is a test version of wyze bridge with multiple stream, so i hope that is going to be released soon.

**Comment by dimmanramone** [comment]
So after your recommendations @NickM-27 and after installing the new wyze bridge with the substreams I finally have the following configuration. 

```
mqtt:
  host: ip
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 1920
  height: 1080

objects:
  track:
    - person

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects

snapshots:
  enabled: True
  timestamp: True

cameras:
  hall_cam:
    ffmpeg:
      inputs:
        - path: rtsp://ip/hall-cam
          roles:
            - record
        - path: rtsp://ip/hall-cam-sub
          roles:
            - detect
            - rtmp

  living_room_cam:
    ffmpeg:
      inputs:
        - path: rtsp://ip/living-room-cam
          roles:
            - record
        - path: rtsp://ip/living-room-cam-sub
          roles:
            - detect
            - rtmp
```

Is there anything else that I can remove or something that I'm missing?

One thing that I noticed (but I can be wrong, as I said before quite new and still figuring out the configurations) is that I get worse matches or not even at all in doubletake with compreface. Can that be the quality of the substream? Or should I check my double take configuration instead?

**Reply by NickM-27** [reply]
> One thing that I noticed (but I can be wrong, as I said before quite new and still figuring out the configurations) is that I get worse matches or not even at all in doubletake with compreface. Can that be the quality of the substream? Or should I check my double take configuration instead?

That's most likely a config issue in doubletake. What is the resolution of the substream now vs before?

**Reply by dimmanramone** [reply]
> > One thing that I noticed (but I can be wrong, as I said before quite new and still figuring out the configurations) is that I get worse matches or not even at all in doubletake with compreface. Can that be the quality of the substream? Or should I check my double take configuration instead?
> 
> That's most likely a config issue in doubletake. What is the resolution of the substream now vs before?

I didn't have a substream before. But if I'm not mistaken it was 1080p before and 360p now.

**Reply by NickM-27** [reply]
> > > One thing that I noticed (but I can be wrong, as I said before quite new and still figuring out the configurations) is that I get worse matches or not even at all in doubletake with compreface. Can that be the quality of the substream? Or should I check my double take configuration instead?
> > 
> > 
> > That's most likely a config issue in doubletake. What is the resolution of the substream now vs before?
> 
> I didn't have a substream before. But if I'm not mistaken it was 1080p before and 360p now.

ah, then yeah that could be an issue, might just want to stick with the original size

**Reply by dimmanramone** [reply]
> > > > One thing that I noticed (but I can be wrong, as I said before quite new and still figuring out the configurations) is that I get worse matches or not even at all in doubletake with compreface. Can that be the quality of the substream? Or should I check my double take configuration instead?
> > > 
> > > 
> > > That's most likely a config issue in doubletake. What is the resolution of the substream now vs before?
> > 
> > I didn't have a substream before. But if I'm not mistaken it was 1080p before and 360p now.
> 
> ah, then yeah that could be an issue, might just want to stick with the original size

I'll go back to one stream and check if I get better results.

Here is my double take configuration. Maybe you can see an issue there?

```
detectors:
  compreface:
    url: ip
    key: !secret compreface_key
    timeout: 15
    det_prob_threshold: 0.75

cameras:
  camera:
    detect:
      match:
        save: true 
        confidence: 90
        min_area: 3000 
      unknown:
        min_area: 1500 
        confidence: 85 

mqtt:
  host: ip
  username: !secret mqtt_user
  password: !secret mqtt_password

  topics:
    frigate: frigate/events
    homeassistant: homeassistant
    matches: double-take/matches
    cameras: double-take/cameras

frigate:
  url: ip
  update_sub_labels: true 

  events:
    camera:
      attempts:
        latest: 16 
        snapshot: 
        mqtt: false 
      image:
        height: 640
```
