### DISCUSSION TITLE
Gaps in recordings

### DISCUSSION THREAD

**Discussion by wimg** [blakeblackshear/frigate#5636] [Ask A Question]
I seem to be having an issue where recordings are very partial. Sometimes the recordings have gaps of anywhere between 10 seconds and 5 minutes.
My config is :

```
mqtt:
   host: 172.17.0.1
   port: 1883
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@192.168.xxx.xxx:554
          roles:
            - detect
    rtmp:
      enabled: False
    detect:
      width: 1920
      height: 1080
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 60
      mode: motion
detect:
  enabled: True
  stationary:
    interval: 0
    threshold: 50
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - backpack
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```

Does anyone have any idea what might be happening ?

**Comment by NickM-27** [comment]
What version of frigate are you running and have you checked the logs for errors?

**Reply by wimg** [reply]
I'm running version 0.11.1-2EADA21.
The logs have nothing special, except the occassional :
[2023-02-23 14:58:32] frigate.object_processing      WARNING : Unable to create jpg because frame 1677164308.582529 is not in the cache
[2023-02-23 14:58:34] frigate.object_processing      WARNING : Unable to create jpg because frame 1677164308.582529 is not in the cache
[2023-02-23 14:58:34] frigate.object_processing      WARNING : Unable to save snapshot for 1677164004.198879-d5ld7b.
[2023-02-23 14:58:34] frigate.object_processing      WARNING : Unable to create clean png because frame 1677164308.582529 is not in the cache
[2023-02-23 14:58:34] frigate.object_processing      WARNING : Unable to save clean snapshot for 1677164004.198879-d5ld7b.
[2023-02-23 14:58:34] frigate.object_processing      WARNING : Unable to create jpg because frame 1677164308.582529 is not in the cache
[2023-02-23 15:02:37] frigate.object_processing      WARNING : Unable to create jpg because frame 1677164556.621615 is not in the cache


However this is on average 2-3 times per day, but there are gaps every few minutes.

**Reply by NickM-27** [reply]
It's possible your HDD is unable to keep up. In 0.11 if too many segments are left unmoved frigate will delete them silently. In 0.12 we have added a warning log for this.

**Reply by wimg** [reply]
This is the disk activity graph of that system. It has a Samsung EVO SSD installed :
![image](https://user-images.githubusercontent.com/313511/222836890-3f0ef4f7-44e8-4f24-8382-137dc0909e26.png)

**Reply by NickM-27** [reply]
Try enabling debug logs and see what it shows

```yaml
logger:
  logs:
    frigate.record: debug
```
