### DISCUSSION TITLE
record rtsp stream via Frigate when person is detected, and clear recordings after 3 days (not working)

### DISCUSSION THREAD

**Discussion by Dimgoossens** [blakeblackshear/frigate#5654] [Ask A Question] [answered]
Hi,

I'm starting to use Home Assistant, and am trying to use Frigate to monitor/record from my RTSP stream (monitor front door).
At the moment, I'm able to view the rtsp stream in the Frigate plugin (had a green screen for a while :-) )

Now I'd like to record to .mp4 when it detects a person, and remove the generated files (clips) after 3 days.

My Frigate.yaml

```
mqtt:
    host: 192.168.2.100
    port: 1883
    user: MQTTHA
    password: xahz9uv1aih6Agrhtjykuilj§(èyntu,--hs2eamaog1aetiaLoo3dahnge6quaagh0ieZae

cameras:
  Voordeur3: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.2.11:8001 # <----- Update for your camera
          roles:
            - rtmp
            - detect            
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5

   clips: 
      objects: 
        - person  
``` 
This config doesn't work however, and I get the following 

```
Failed to receive response from Home Assistant for request. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////Voordeur3//",
    "id": 41
  },
  "response": {
    "code": "unknown_error",
    "message": "Forbidden media source identifier: frigate/event-search/clips////Voordeur3//"
  }
}    
```    

Can someone assist ?
I guess I have wrong permissions somewhere? Or a wrong folder  structure?

PS : with this config, I don't even see the stream anymore (it does work, when i leave out the clips part :-))
