### DISCUSSION TITLE
On TP-Link Tapo cameras "cam exceeded fps limit. Exiting ffmpeg..." config fix. (kind of) 0.12b9

### DISCUSSION THREAD

**Discussion by kpcz** [blakeblackshear/frigate#5668] [Show and tell]
So I have multiple Tapo C210 cameras, and all where crashing ffmpeg service because of bad stream. With error:

`livingroom2_cam exceeded fps limit. Exiting ffmpeg...`

so config that works without any errors, and Birdseye does not freeze is: 

```
go2rtc:
  webrtc:
    candidates:
      - 192.168.1.6:8555
      - stun:8555
  streams:
    livingroom2_cam:
      - rtsp://X:XXX!@192.168.1.136:554/stream1
    livingroom2_cam_sub:
      - rtsp://X:XXX!@192.168.1.136:554/stream2
      - ffmpeg:livingroom2_cam_sub      

cameras:
  livingroom2_cam:
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/livingroom2_cam_sub  
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/livingroom2_cam 
          input_args: preset-rtsp-restream
          roles:
            - record       
    detect:
      width: 640
      height: 360           
      fps: 5
```
`   - ffmpeg:livingroom2_cam_sub ` This was the missing bit in gazzilion of config variations I tried. 
`ffmpeg:rtsp://X:XXX!@192.168.1.136:554/stream2` like this it did not work
Maybe this should be added to "Camera specific configurations" As I was pulling my hair out for few days :)

**Comment by NickM-27** [comment]
> So I have multiple Tapo C210 cameras, and all where crashing ffmpeg service because of bad stream. With error:
> 
> `livingroom2_cam exceeded fps limit. Exiting ffmpeg...`
> 
> so config that works without any errors, and Birdseye does not freeze is: 
> 
> ```
> go2rtc:
>   webrtc:
>     candidates:
>       - 192.168.1.6:8555
>       - stun:8555
>   streams:
>     livingroom2_cam:
>       - rtsp://X:XXX!@192.168.1.136:554/stream1
>     livingroom2_cam_sub:
>       - rtsp://X:XXX!@192.168.1.136:554/stream2
>       - ffmpeg:livingroom2_cam_sub      
> 
> cameras:
>   livingroom2_cam:
>     ui:
>       order: 2
>     ffmpeg:
>       hwaccel_args: preset-intel-qsv-h264
>       inputs:
>         - path: rtsp://127.0.0.1:8554/livingroom2_cam_sub  
>           input_args: preset-rtsp-restream
>           roles:
>             - detect
>         - path: rtsp://127.0.0.1:8554/livingroom2_cam 
>           input_args: preset-rtsp-restream
>           roles:
>             - record       
>     detect:
>       width: 640
>       height: 360           
>       fps: 5
> ```
> `   - ffmpeg:livingroom2_cam_sub ` This was the missing bit in gazzilion of config variations I tried. 
> `ffmpeg:rtsp://X:XXX!@192.168.1.136:554/stream2` like this it did not work
> Maybe this should be added to "Camera specific configurations" As I was pulling my hair out for few days :)

Doing that won't do anything except be the same as if ffmpeg: wasn't there. That's because the original stream and ffmpeg stream offer the same codecs so go2rtc will never ask for the streams from the ffmpeg: module

**Reply by kpcz** [reply]
With this config the errors are gone, and there is no more stream freezes in birdseye (sub stream), 
If I take out ffmpeg:livingroom2_cam_sub all tapo cameras start Exiting ffmpeg.. and stream freezes for few seconds, then restarts. 
Strange, so it is kind of placebo, but it works.

**Reply by NickM-27** [reply]
Have you tried using the tapo:// source? This is new in go2rtc 1.2.0 included in beta9

**Reply by NickM-27** [reply]
https://github.com/AlexxIT/go2rtc#source-tapo

**Reply by kpcz** [reply]
will try that. Thanks. But also previous config suits me, as it works.

with tapo:// I dont quite understand how to get stream and substream

**Reply by kpcz** [reply]
theres somethig not right. Got the same result as: https://github.com/AlexxIT/WebRTC/issues/448

**Reply by atv2016** [reply]
@kpcz So did your 'placebo' solution work ? I get these fps exceeded errors as well, from eufy cameras. Or did you still get the messages later on?

**Reply by kpcz** [reply]
Oddly enough it works, no more fps exceeded errors on any of 4 tapo cameras. Did you tried this placebo solution?

**Comment by jmtatsch** [comment]
Didn't know the tapo cameras have a sub stream. What a nice discovery.

**Comment by atv2016** [comment]
Not yet, but i intend to, might be some weird glitch i guess.
________________________________

**Comment by nsmauriciosti** [comment]
Had the same errors with Tapo C200, Made ur config and all errors gone. Thx dude.

**Comment by pShota** [comment]
I have the same error, same config except I don't use the main stream,
on frigate UI, the stream looks okay , but in the log, it keep crashing

**Reply by pShota** [reply]
I managed to sort it out by using @kpcz method,
but I have to use double quote around the string 
```
 living_cam_sub:
      - rtsp://acc:pw@192.168.x.x/stream2
      - "ffmpeg:living_cam_sub"
```

I have the other old dlink camera with the same issue
but that one is solved by using 
`preset-rtsp-generic` instead of `preset-rtsp-restream`

I'm on frigate 0.12.1
tapo c200 firmware 1.3.11

**Comment by KelvinVenancio** [comment]
thanks, man! your solution still works and helped me a lot! here is my final config also:

```yaml
mqtt:
  host: core-mosquitto
  user: user
  password: pass

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.20:8555
      - stun:8555
  streams:
    camera_living:
      - rtsp://user:pass@192.168.1.50:554/stream1
    camera_living_sub:
      - rtsp://user:pass@192.168.1.50:554/stream2
      - "ffmpeg:camera_living_sub"
    camera_kids:
      - rtsp://user:pass@192.168.1.51:554/stream1
    camera_kids_sub:
      - rtsp://user:pass@192.168.1.51:554/stream2
      - "ffmpeg:camera_kids_sub"

cameras:
  camera_living:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_living
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_living_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
  camera_kids:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera_kids
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera_kids_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
```
