### DISCUSSION TITLE
Nas and local DB configuration

### DISCUSSION THREAD

**Discussion by johnvprcam24573455623** [blakeblackshear/frigate#5672] [Ask A Question]
Hi All,

I'm struggling to configure the Recording on network folder and DB on local drive. I keep getting   **unable to open database file**

I have using UBUNTU and this is the mount with the shared folder **" /media/frigademedia"**:
`//192.168.1.3/frigate /media/frigademedia cifs credentials=/home/john/.server_creds,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0`

Then in Potainer on Ubuntu  this composer:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta9
    shm_size: "64mb" 
    devices:
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/john/frigate/config.yml:/config/config.yml
      - /media/frigatemedia/clips:/media/frigate/clips 
      - /media/frigatemedia/recordings:/media/frigate/recordings
      #- /media/frigatemedia:/media/frigate
      - /home/john/frigate/db:/db          # <--------------  EDIT 1: THIS FIXED IT 
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
```
 
 

and this is my config.yaml which I keep on **/home/john/frigate/** in Ubuntu
```
#fmpeg:
#  hwaccel_args: preset-vaapi

cameras:
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXXXX
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080


# **********  GLOBAL **************  
record:
  enabled: True
  events:
    retain:
      default: 30

snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:

database:
    path: /db/frigate.db     # <--- ***********  EDIT 2: THIS FIXED IT   ************
```

Found similar issues however I didn't figure it out:
https://github.com/blakeblackshear/frigate/issues/712
https://github.com/blakeblackshear/frigate/issues/570
https://github.com/blakeblackshear/frigate/issues/1409
