### DISCUSSION TITLE
Hwaccell low load on intel GPU, is that normal?

### DISCUSSION THREAD

**Discussion by kpcz** [blakeblackshear/frigate#5683] [Ask A Question]
HI. I got i3 10100 cpu and have enabled hwaccel on my frigata setup with 9 cameras, running on Unraid frigata12-beta9,  All cameras uses h254 codec, and using go2rtc restream option for all camaras. But my cpu usage is overall really high ~40%. Tweaked all camera substreams, for lower res and lower fps/bitrate, added detect resolutions for all cameras. But still cpu is high, but the GPU usage is low. So I am wondering, is there something wrong with hacccel, or the low GPU usage is normal for encoding. I am also using TPU Coral.

Tried various configurations, but could not utilize gpu card more than few %.

Frigate System page shows that most CPU is used for ffmpeg process when there is no motion, when motion ,then Detect process uses more % cpu. Shouldnt GPU decrease the ffmpeg cpu load, or am I missing something?

![image](https://user-images.githubusercontent.com/26654090/224003165-8ff148e7-ed8e-4aed-9d06-e0725a81b025.png)

found that best config for me is:

```
ffmpeg:
  global_args: '-hide_banner -loglevel fatal' #fatal' 
  hwaccel_args: 
    - '-hwaccel_device' 
    - /dev/dri/renderD128 
    - -hwaccel
    - qsv
    - -c:v
    - h264_qsv

  input_args:
   - -rtsp_transport 
   - udp
   - -stimeout 
   - '5000000'
   
  output_args:
    detect: -f rawvideo -vf hwdownload,format=nv12 -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac    
```

also tried

```
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
```
But that did not improve things much. 

If I run

`ffmpeg -loglevel verbose -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -i "rtsp://XXXX:XXXX@192.168.1.11:554/cam/realmonitor?channel=3&subtype=0" -c h264_qsv -an -f null -
`
comand runs with out errors and my GPU stats show ~20% load on my gpu, so it is working, but is it normal for such a low load in friagtate. Thanks,
