### DISCUSSION TITLE
beta 9 go2rtc ffmpeg not starting so no detection

### DISCUSSION THREAD

**Discussion by ediguidedog** [blakeblackshear/frigate#5694] [Ask A Question]
I've just had a play with the go2rtc and while most of my cameras worked fine I have some that refuse to do anything.

```
go2rtc:
    streams:
        front:
            - rtsp://admin:xxxx@192.168.68.238:554/stream0
        drive:
            - rtsp://admin:xxxx@192.168.68.231:554/11
        patio:
            - rtsp://admin:xxxx@192.168.68.236:554/stream0
```

Of the three above the first two work and the third returns the following error in the logs

ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="parse \"192.168.68.236:554/stream0/\": first path segment in URL cannot contain colon" url=rtsp://admin:xxxx@192.168.68.236/stream0

The path I'm sending fir the patio is the same (apart from ip address) to a working camera and indeed changing a single digit of the ip address to the working one gets it going so I'm confident there isn't a typo 

Changing the patio camera to 
```
      patio:
            - ffmpeg:rtsp://admin:xxxx@192.168.68.236:554/stream0
```
means it now works but until I actually click on the camera and wait for about 10 seconds it doesn't start dislaying the stream.

What this means is if I restart frigate and don't go into the gui and select each camera in turn the stream isn't generated so detection simply doesnt work for that camera.

Is this known or expected behaviour?
