### DISCUSSION TITLE
Difference between record -> retain -> mode vs record -> events -> retain -> mode

### DISCUSSION THREAD

**Discussion by edgardha** [blakeblackshear/frigate#5699] [Ask A Question]
Hi all,

today is my second day using frigate. Thanks a lot for this great software!

By the moment, I'm fine tuning it, but I have a question about retain mode.

Which is the sense of events -> retain -> mode: motion/all if only register an events if object detected?

I want record only when a motion detect (it's working) and if an object is detect, generate an event (also is working). But which is the sense when I put mode: all/motion on a retain of the events if an event doesn't appear if only is motion? (only appear as event when object is detected). I attach an example:

```yaml
cameras:
  camera1:    
    record:
      enabled: True
      retain:
        days: 8
        mode: motion
      events:
        retain:
          mode: all
```

Thanks!
