### DISCUSSION TITLE
Issue with HWaccel

### DISCUSSION THREAD

**Discussion by askpet** [blakeblackshear/frigate#5720] [Ask A Question] [answered]
Hi

I have searched here (and everywhere else it seems) and I can't get any further.

I keep getting "_Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found_"

My Frigate image:  ghcr.io/blakeblackshear/frigate:dev-4dc6c93-tensorrt
Intel NUC i5 (5th gen) and HD Graphics 6000 (rev 9)
OS: Ubuntu 22.04 LTS

**Command "lspci -v" gives**
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 6000 (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Intel Corporation HD Graphics 6000
	Flags: bus master, fast devsel, latency 0, IRQ 49
	Memory at a9000000 (64-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

**docker-compose.yaml:**

```yaml
version: '3.9'
services:
  frigate:
    container_name: Myfrigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-4dc6c93-tensorrt
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/askpet/Docker/Frigate/frigate.yml:/config/config.yml:ro
      - /home/askpet/Docker/Frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of mem~Docory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "foo_foo"
```

**the hwaccel command in frigate.yml**
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

It seems as if my docker container does not have access to the GPU - but I am lost.
Maybe someone in here can point in the right direction?
