### DISCUSSION TITLE
High res stream via Home Assistant plugin and go2rtc?

### DISCUSSION THREAD

**Discussion by badnbusy** [blakeblackshear/frigate#5737] [General]
I am now using the following config in Frigate and thus use the go2rtc and restream option for both the detect (front_sub) and record (front) go2rtc streams. All working well within Frigate and I can view the high res stream in the UI using the MSE view.

When using the Frigate HA addon, and the HA lovelace card, you can add the camera live feed but its only the low res "detect" stream. How can I get the full res stream in there utilising the restream option that go2rtc offers so the stream relays from Frigate?

```
go2rtc:
  streams:
    front:
      - rtsp://a:b@192.168.2.254:554/Streaming/Channels/101
    front_sub:
      - rtsp://a:b@192.168.2.254:554/Streaming/Channels/102

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record
```
