### DISCUSSION TITLE
Mask not Masking, triggers event

### DISCUSSION THREAD

**Discussion by johnvprcam24573455623** [blakeblackshear/frigate#5750] [Ask A Question]
Hi guys, 

Any idea what I am doing wrong in my config, I have set masks and I still triggers person alert:

  ```
garage-door-wz-2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-door-wz-2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
    record:
      enabled: True
      events:
        retain:
          default: 2
          mode: motion
    motion:
      mask:
        - 468,709,385,273,0,360,0,1080,216,1080,213,1080
        - 1920,1080,1920,266,1424,308,1403,429,1423,605,1757,1080
    detect:
      width: 1920
      height: 1080
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - bird
        - mouse
```

**Comment by NickM-27** [comment]
I'd suggest reading the docs. As it says there, motion masks will not stop objects from being detected https://docs.frigate.video/configuration/masks

**Reply by johnvprcam24573455623** [reply]
@NickM-27 Thank you so much for the quick answer!

so to don't have events trigger in some areas what is the best practice. use Zones or Object Masks?

Thank you!

John

**Reply by NickM-27** [reply]
Zones for areas of interest are absolutely the recommended approach https://deploy-preview-4055--frigate-docs.netlify.app/configuration/zones#restricting-events-to-specific-zones

**Comment by johnvprcam24573455623** [comment]
So I've done some progress but I'm now stucked i am getting this error:
` Zone garage_event_no_person is configured to track dog but that object type is not added to objects -> track.`

Not sure why is giving me a warning on dog.....
```
  garage-door-wz-2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-door-wz-2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
    record:
      enabled: True
      events:
        retain:
          default: 30
          mode: motion        
        required_zones:
          - garage_event_person
          - garage_event_no_person
    snapshots:
      required_zones:
         - garage_event_person
         - garage_event_no_person

    zones:
      garage_event_person:
        coordinates: 462,701,459,291,70,340,48,33,1859,25,1883,212,1329,231,1321,528,1677,1080,262,1080 
        objects:
         - person
         - dog
         - cat
         - package
         - bird
         - mouse
      garage_event_no_person:
        coordinates: 1323,537,1344,217,1898,193,1885,26,41,26,46,347,444,294,457,707,249,1080,0,1080,0,0,1920,0,1920,572,1920,728,1920,1080,1764,1080
        objects:
         - dog
         - cat
         - package
         - bird
         - mouse
```
