### DISCUSSION TITLE
Anything special required for H.265 to work with Home Assistant

### DISCUSSION THREAD

**Discussion by dison4linux** [blakeblackshear/frigate#5751] [Ask A Question]
I know the general consensus is to use H.264 whenever possible for best compatibility, but I recently found that one of my cameras seems to have a much more stable stream when using H.265.  Everything seems to work great within Frigate itself after switching the camera feed to H.265 but the Frigate card within Home Assistant that displays the camera only shows 1 - 2 seconds of video and then says "Error with media stream contents"

The camera config is:
```
  front_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_driveway_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
```
The HA Lovelace card config is:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_driveway
    live_provider: auto
live:
  controls:
    title:
      mode: none
```

Switching the live_provider from auto to frigate-jsmpeg seems to work but I'm not sure that's the best way to work around this.

**Comment by NickM-27** [comment]
Which device is running the home assistant app? The upcoming Frigate card should handle this better with go2rtc

**Reply by dison4linux** [reply]
I'm just looking at the webpage of HA from Chrome on Windows.
Works on my android phone with frigate-jsmpeg, I hadn't tried on auto but I can switch it back to auto and try it on my android phone if you want.

**Reply by dison4linux** [reply]
I just realized I should have included some version #s in my original post...
Frigate 0.12b9
Frigate Card v4b4

**Reply by NickM-27** [reply]
Right, frigate card 4.1 supports go2rtc which works much better

**Reply by badnbusy** [reply]
I see it's here but how do I get 4.1 in to HA via HACS or manually? https://github.com/dermotduffy/frigate-hass-card/tree/release-4.1.0

**Reply by NickM-27** [reply]
> I see it's here but how do I get 4.1 in to HA via HACS or manually? https://github.com/dermotduffy/frigate-hass-card/tree/release-4.1.0

Build it manually or wait for a new beta

**Reply by badnbusy** [reply]
How do I manually compile this to get the new frigate-hass-card.js please?

**Reply by NickM-27** [reply]
> How do I manually compile this to get the new frigate-hass-card.js please?

https://github.com/dermotduffy/frigate-hass-card#building

**Comment by badnbusy** [comment]
@NickM-27 So I'm still having issues with this. I have 7 x h265 cameras, that while work perfectly fine in Frigate, both for the live view in MSE and the clips/recordings/playback, but refuse to playback in HA even using the following latest integrations:

v5.0.0-beta.1 hass-card
v4.0.0-rc1 frigate-hass
v0.12-rc2 frigate

The one h264 camera I have works fine in HA for playback of clips/full recordings, so I am assuming it's to do with h265.

The error is simply "Error with media stream contents" - nothing showing in the HA log or the Frigate log.

Camera config:

```
go2rtc:
  streams:
    front:
      - rtsp://x@192.168.2.254:554/Streaming/Channels/101
    back:
      - rtsp://x@192.168.2.253:554/Streaming/Channels/101
    side:
      - rtsp://x@192.168.2.252:554/Streaming/Channels/101
    garden:
      - rtsp://x@192.168.2.251:554/Streaming/Channels/101
    office:
      - rtsp://x@192.168.2.250:554/Streaming/Channels/101
    porch:
      - rtsp://x@192.168.2.249:554/Streaming/Channels/101
    drive:
      - rtsp://x@192.168.2.248:554/Streaming/Channels/101
    office-inside:
      - rtsp://x@192.168.2.247/stream1
    front_sub:
      - rtsp://x@192.168.2.254:554/Streaming/Channels/102
    back_sub:
      - rtsp://x@192.168.2.253:554/Streaming/Channels/102
    side_sub:
      - rtsp://x@192.168.2.252:554/Streaming/Channels/102
    garden_sub:
      - rtsp://x@192.168.2.251:554/Streaming/Channels/102
    office_sub:
      - rtsp://x@192.168.2.250:554/Streaming/Channels/102
    porch_sub:
      - rtsp://x@192.168.2.249:554/Streaming/Channels/102
    drive_sub:
      - rtsp://x@192.168.2.248:554/Streaming/Channels/102
    office-inside_sub:
      - rtsp://x@192.168.2.247/stream2
    
  webrtc:
    candidates:
      - 192.168.1.252:8555
      - stun:8555

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record

  back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back
          roles:
            - record

  garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garden
          roles:
            - record

  side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/side
          roles:
            - record

  porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/porch
          roles:
            - record

  office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/office
          roles:
            - record

  drive:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drive_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/drive
          roles:
            - record

  office-inside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office-inside_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/office-inside
          roles:
            - record

```

Any pointers?

Thanks

**Reply by NickM-27** [reply]
What browser are you using? Have you tried looking through chrome://media-internals to see why it's failing?

**Reply by dison4linux** [reply]
As soon as Frigate-HASS-Card 5.0-beta1 came out, I updated to that.
Then I adjusted the "live-provider" on the cards to go2rtc and now it "just works"
... both Chrome on Windows, and also HA app on Android

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.chicken
    live_provider: go2rtc
```
