### DISCUSSION TITLE
ffmpeg using an unknown resolution?

### DISCUSSION THREAD

**Discussion by badnbusy** [blakeblackshear/frigate#5753] [General]
I have my cameras all set to use 640x480 for the detect rtsp stream from my cameras sub-stream. When looking at ps, I see that it's setting the frame size to 960x720:

```
ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
```

Where is 960x720 coming from and is it increasing processing as the actual camera is set to 640x480 ?

Thanks!

**Comment by NickM-27** [comment]
This is likely for the jsmpeg view which has its own height set in config

**Reply by idle-user** [reply]
@NickM-27, I've set the detection sizes to match my cams' sub-stream's resolution. But I notice that the jsmpeg view is upsizing from the detection size. Is that expected?

This is what I see for the conversions.
```shell
ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 720x576 -i pipe: -f mpegts -s 900x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:
```

**Reply by badnbusy** [reply]
> This is likely for the jsmpeg view which has its own height set in config

Where is this set so that msjpeg doesn't change the res?

**Reply by NickM-27** [reply]
@idle-user you set the jsmpeg size under `live -> height`

**Reply by idle-user** [reply]
Thank you!

 I got my cams configured now to match the detect stream sizes. ffmpeg shows the same resolutions now.
I was a bit confused reading the documentation since the sample showed `live:` as its own parent section that overrides all cams.

Then I saw [this page](https://docs.frigate.video/configuration/live#setting-stream-for-live-ui) and with your comment it made sense. My config looks like this now:

(this might be TMI for the reply, but might prove useful for anyone else googling around)

```yml

...

go2rtc:
  rtsp:
    username: "admin"
    password: "some_raw_pass-envVar-supported-later-i-hope"
  streams:
    front-doorbell:
      - rtsp://admin:{FRIGATE_RTSP_AMCREST_PASSWORD}@X.X.X.X:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - "ffmpeg:front-doorbell#audio=opus"
...
    back-entrance:
      - http://X.X.X.X/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_REOLINK_PASSWORD}
      - "ffmpeg:back-entrance#audio=opus"
...

cameras:
  front-doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_AMCREST_PASSWORD}@X.X.X.X:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 720
      height: 576
    live:
      height: 576
...
  back-entrance:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back-entrance?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_REOLINK_PASSWORD}@X.X.X.X:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
    live:
      height: 480
...

```

For any Amcrest AD410 doorbell owners, I also like to add that adding `#backchannel=0` (seen above) is a must, or else the doorbell button presses no longer work or respond.
