### DISCUSSION TITLE
How to disable detect on startup

### DISCUSSION THREAD

**Discussion by gregeeh** [blakeblackshear/frigate#5772] [Ask A Question]
Hi all,

Is it possible to disable detect with Frigate starts? I've added the enabled: false to the config but that has not helped.

TIA

```
mqtt:
    host: 192.168.10.2
    user: mqtt-user
    password: mqtt-password
cameras: # Reolink E1 Pro
    Villa333:
        rtmp:
            enabled: false
        ffmpeg:
            input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - +genpts+discardcorrupt
              - -flags
              - low_delay
              - -strict
              - experimental
              - -analyzeduration
              - 1000M
              - -probesize
              - 1000M
              - -timeout
              - "5000000"
            inputs:
                - path: rtsp://admin:password@192.168.10.70:554/h264Preview_01_sub
                  roles:
                    - detect
                - path: rtsp://admin:password@192.168.10.70:554/h264Preview_01_main
                  roles:
                    - record
                    - rtmp
        detect:
            enabled: false
            width: 640
            height: 360
        record:
            enabled: True
            events:
                pre_capture: 15
                post_capture: 5
                retain:
                    default: 10
                    mode: active_objects
snapshots:
    enabled: True
    retain:
        default: 10
birdseye:
    enabled: True
    mode: continuous
    quality: 6
```
