### DISCUSSION TITLE
Can Frigate Grab JPEG Images From URL

### DISCUSSION THREAD

**Discussion by justynbell** [blakeblackshear/frigate#5809] [Ask A Question] [answered]
Sorry for the basic question, but I'd like to get images at 1 or 2 FPS from my Fire HD 10 tablet running Fully Kiosk.  In a browser I can enter this URL and it will return a JPEG:

`http://<ip_of_tablet>:2323/?cmd=getCamshot&password=<simple_password>`

I've tried following a few configuration examples [here](https://docs.frigate.video/configuration/camera_specific/#jpeg-stream-cameras), but I don't think any apply to this situation (MJPEG, streaming JPEG, etc).  It's a lack of understanding on my part, I admit.

**Comment by blakeblackshear** [comment, marked as answer]
You can use go2rtc (now included in the 0.12 beta release) to do this: https://github.com/AlexxIT/go2rtc/tree/v1.2.0#source-http

**Reply by justynbell** [reply]
Hell yeah, I got it working.  I'm going to outline the steps here for future me, or other people who specifically use the Fire HD 10, and maybe you can comment if you see a better way of getting this done.

- Add the go2rtc component to your config:
```yml
go2rtc:
  streams:
    tablet:
      - http://<ip_of_tablet>:2323/?cmd=getCamshot&password=<password>
```
- You can now see your tablet's webcam in the go2rtc dashboard
  - In your Frigate web interface, go to System -> "go2rtc dashboard" in the upper right (you won't see this in the HA Frigate Proxy (if your Frigate is setup outside HA, like mine is))
  - Click on "links" under 'tablet'
  - The stream.mjpeg was the only link that worked for me.  Copy this URL
- Configure Frigate to use this MJPEG stream by following the configuration [here](https://docs.frigate.video/configuration/camera_specific/#mjpeg-cameras).  My configuration example:
```yml
  tablet:
    ffmpeg:
      inputs:
        - path: <that URL you copied>
          roles:
            - detect
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 320
      height: 240
      fps: 2
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
```

**Reply by NickM-27** [reply]
a better way of doing this would be to setup an h264 stream in go2rtc so you avoid the work of transcoding to h264 multiple times

```yaml
go2rtc:
  streams:
    tablet:
      - http://<ip_of_tablet>:2323/?cmd=getCamshot&password=<password>
      - ffmpeg:tablet#video=h264 #(you may also want to use #hardware if your host has hardware acceleration available)
```

**Reply by justynbell** [reply]
@NickM-27 Thank you for the pointer!  I made the change, but I haven't profiled whether the CPU usage is higher/lower, or what the latency looks like.  Just so I understand: it wasn't doing h264 transcodes multiple times the way I originally had it setup, right?  We just shifted the transcoding from Frigate to go2rtc, but go2rtc was doing some http+jpeg to mpeg transcoding in addition to the h264 transcoding Frigate was doing?

**Reply by NickM-27** [reply]
> @NickM-27 Thank you for the pointer! I made the change, but I haven't profiled whether the CPU usage is higher/lower, or what the latency looks like. Just so I understand: it wasn't doing h264 transcodes multiple times the way I originally had it setup, right? We just shifted the transcoding from Frigate to go2rtc, but go2rtc was doing some http+jpeg to mpeg transcoding in addition to the h264 transcoding Frigate was doing?

That is incorrect. With your config

```yaml
  tablet:
    ffmpeg:
      inputs:
        - path: <that URL you copied>
          roles:
            - detect
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
```

you were doing transcoding to h264 two times, one for record and one for rtmp. RTMP is also deprecated so this is another reason that it is not recommended and using go2rtc would be preferable.
