### DISCUSSION TITLE
Hardware Acceleration and J4125

### DISCUSSION THREAD

**Discussion by dimmanramone** [blakeblackshear/frigate#5826] [Ask A Question] [answered]
Hi,

I'm a little confused which are the right `hwaccel_args` fot the J4125. If I'm not wrong the J4125 is a Gen 10 CPU and I'm already using in my docker-compose the environment variable `LIBVA_DRIVER_NAME=i965`

```
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
```

or

```
ffmpeg:
  hwaccel_args: -c:v h264_qsv
```

**Comment by NickM-27** [comment, marked as answer]
In general I would recommend vaapi for all as it has automatic profile selection, you can of course try both and see which works better for your device.

**Reply by dimmanramone** [reply]
Ok thanks I'll try both of them.

**Reply by cry4r** [reply]
Hi, did you solve with VAAPI or QSV? 
I have the same CPU J2145, with Frigate docker under Proxmox, but with both i have ffmpeg error on log. I have a container on Proxmox with "Protection: no" and "Unprivileged container: no" and the docker stack with:

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware    
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/frigate:/config:rw
      - /root/frigate/clips:/media/frigate/clips:rw
      - /root/frigate/recordings:/media/frigate/recordings:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "1935:1935"
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "*******"
      LIBVA_DRIVER_NAME: i965
```
