### DISCUSSION TITLE
Docker container from frigate can not connect to cameras

### DISCUSSION THREAD

**Discussion by jorisrymenants** [blakeblackshear/frigate#5829] [Ask A Question]
Frigate was working, and connecting to cameras, but now this does not work anymore. All connections to all cameras time out.
I can connect to the RSTP streams via VLC.
If I ffprobe the camera's from the host I get an answer back.
If I ffprobe the same url from within the container, I get a connection time out.
It seems that my networkconnection in the container is not working any more.
I am using IP-addresses in the streams, so no dns-lookup is necessary.

example ffprobe from host:
```
ffprobe rtsp://XXXX:XXXXX@192.168.0.98:554/                                       
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://XXXX:XXXXX@192.168.0.98:554/':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

my docker-compose:

```
version: '3.9'
services:
  frigate:
    container_name: frigate2
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta10
    shm_size: '512mb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/jorisrymenants/Docker containers/Frigate/config/config.yml:/config/config.yml
      - /Users/jorisrymenants/Docker containers/Frigate/media/frigate:/media/frigate
      
#      - /mnt/footage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5555:5000"
      - "8556:8554" # RTSP feeds
      - "8557:8555/tcp" # WebRTC over tcp
      - "8557:8555/udp" # WebRTC over udp4"
#    environment:
#      FRIGATE_RTSP_PASSWORD: password

```
