### DISCUSSION TITLE
Increase clip duration?

### DISCUSSION THREAD

**Discussion by Spreadcamp** [blakeblackshear/frigate#5856] [Ask A Question]
Hi, is there any way to increase the recorded clips durations before and after detecting a motion? I'm on Beta 12 RC1 and I had this situation the other day where we accidentally forgot to lock the car and someone went in it to search it (nothing of value was taken)

Frigate recorded a clip of the guy walking up to the car and opening the door, but the clip stops right after he stuck his head inside. The total amount of recorded activity was just 14 seconds, most of that was him walking into frame.

Now my question is can I increase the length of the clips through the config somehow? Basically I want to set a amount of time after a motion was detected that will be recorded. I'd prefer that over trying to record everything all the time and it would allow me to see more of what happens in a situation like this.

Here is my current config

```
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 7
```

**Comment by jurasjo** [comment]
You can use: pre_capture and post_capture. Check full config example here:
https://deploy-preview-4055--frigate-docs.netlify.app/configuration/

**Reply by blakeblackshear** [reply]
You can, but it still won't save any segments without motion in the first 7 days or an actively moving object after 7 days based on the config.

**Comment by blakeblackshear** [comment]
Motion mode will keep any 10s recording segment with even a single frame of detected motion, so I would expect it to be there. 

Since you have both general retain mode and person events set to retain for 7 days, I think motion mode would apply unless you marked the clip as a favorite. Past 7 days it would drop segments where the object wasn't moving. 

I would guess that either your motion detection is not sensitive enough or a segment went missing for another reason. It could have been corrupted or something. Do you have the logs from that time?

**Reply by Spreadcamp** [reply]
It was not set as favorite and unfortunately I don't have the log for it. I have found an extra 10 second clip in the recordings folder though that was not shown to me on the web UI so that was helpful. I'm gonna try out the pre_ and post_capture in the config as well maybe it will help. I've also widened the zones around the car maybe that had something to do with it.

**Comment by TheSleepySlee** [comment]
Hello, sorry I have same type of question. Here is my config:

```
record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 7
    pre_capture: 20
    post_capture: 120
```

Camera config:
```
  detect:
      width: 1920
      height: 1080
      enabled: True
      max_disappeared: 10
```

Only 10 secs of footage is kept after last object is detected instead of 120s.
I run Frigate 0.12.0-DA3E197

Any bad config? I read the doc but not sure to understand.
