### DISCUSSION TITLE
nvidia support including `nvidia-smi` missing from 0.11.1

### DISCUSSION THREAD

**Discussion by mpfl** [blakeblackshear/frigate#5912] [Ask A Question]
I'm finally upgrading to 0.11.1 but for some reason the container doesn't seem to have any nvidia support installed. All I did was to remove the `-amd64nvidia` from the image tag.

Relevant parts of docker-compose:

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
```

And then I bring up my containers as usual:

```
mpfl@thyme:~/stacks/thyme/cctv$ docker compose up -d
[+] Running 5/5
 ⠿ Network cctv_default   Created                                                                                  0.1s
 ⠿ Volume "cctv_cctv"     Created                                                                                  0.0s
 ⠿ Container double-take  Started                                                                                  1.5s
 ⠿ Container facebox      Started                                                                                  1.3s
 ⠿ Container frigate      Started                                                                                  1.5s
mpfl@thyme:~/stacks/thyme/cctv$ docker exec -it frigate bash
root@57e522bcb9f7:/opt/frigate# nvidia-smi
bash: nvidia-smi: command not found
root@57e522bcb9f7:/opt/frigate#
```

Is there some other magical invocation I need to do to make sure the nvidia support is installed in the container?
