### DISCUSSION TITLE
Issue with nvidia driver

### DISCUSSION THREAD

**Discussion by hagak** [blakeblackshear/frigate#5933] [General]
Not sure what changed I am on frigate 11.1 using the following compose
```
frigate:
    container_name: frigate
    privileged: true
    image: registry.home.thetank.org/home-server/cctv:latest
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]
    shm_size: 2048M
    environment:
      - TZ=America/New_York
      - LIBVA_DRIVER_NAME=i965
 ```

Which I had not changed nor changed the config.yaml.  This had been working for months and then today on a server restart I started getting this error:
"failed to deploy a stack: Container frigate Creating Container frigate Created Container frigate Starting Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown"

I removed the nvidia and hwaccel and can deploy now but obviously without hwaccel.
