### DISCUSSION TITLE
use both primary stream and substream with go2rtc?

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#5947] [Ask A Question]
In Frigate 0.12.0, what is the recommended approach for a camera with a primary stream and substream? I want to view live the higher resolution primary stream and also record it. I understand from the docs that this stream needs to be configured in the go2rtc section of the config file. If I am *only* using the substream for detection, should also configure it the go2rtc section?

**Comment by NickM-27** [comment]
If you are only using the sub steam for detect and nothing else, there's no purpose adding it to go2rtc. In the future frigate may offer dynamic stream switching (for example, use sub stream on mobile to reduce bandwidth use) in which case it would need both

**Reply by Cold-Lemonade** [reply]
That makes perfect sense. I definitely want to use the substream on my mobile. At present, if I configured both through go2rtc, how do I choose which one to view?

**Reply by NickM-27** [reply]
You can't choose which to view right now (in frigate at least)

**Reply by Cold-Lemonade** [reply]
Something to look forward to. In the mean time, v0.12.0 is AMAZING!!! Thank you @NickM-27 and everyone else. It's awesome. So awesome!

**Reply by idle-user** [reply]
> If you are only using the sub steam for detect and nothing else, there's no purpose adding it to go2rtc. In the future frigate may offer dynamic stream switching (for example, use sub stream on mobile to reduce bandwidth use) in which case it would need both

Your comment caught my attention.

In the docs is shows adding detect only sub stream to go2rtc. My current config follows this. What would be the ideal way to config the sample config showed there?

https://docs.frigate.video/configuration/camera_specific#reolink-cameras

**Reply by NickM-27** [reply]
@idle-user I am not sure what you are asking. Ideal depends on your goals, and that sample config shows both main and sub stream being added

**Reply by idle-user** [reply]
> @idle-user I am not sure what you are asking. Ideal depends on your goals, and that sample config shows both main and sub stream being added

my bad for not getting my message across. 

Pretty much I'm just trying to see if this config what should be followed if the sub stream is only for detection:
At least until Frigate gets updated to swap between streams automatically

```yml
go2rtc:
  streams:
    reolink: 
      - http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
      - "ffmpeg:reolink#audio=opus"

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password
          roles:
            - detect
```
