### DISCUSSION TITLE
With RTMP being disabled will that prevent a simple update?

### DISCUSSION THREAD

**Discussion by tomhusband** [blakeblackshear/frigate#5950] [General]
I'm running Frigate in a Home Assistant 4.2 VM in Proxmox. I'm reading that, "RTMP is now disabled by default and the role is not automatically added. It is highly recommend to move to the new RTSP streams via the bundled go2rtc."

Does that mean a Frigate update will be a problem? Will I need to add go2rtc first? I'm pretty sure it isn't installed now.

Thanks.

**Comment by NickM-27** [comment]
1. You just simply need to set rtmp as enabled in the config 

2. Go2rtc is bundled inside the frigate container

**Reply by tomhusband** [reply]
Yes, I believe it is.

```
cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.1.14:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - record
    rtmp:
      enabled: True
    detect:
      width: 1280
      height: 720
      fps: 10
```
I thought the new update disabled rtmp but I guess that's the default and my config will override it?
