### DISCUSSION TITLE
Rotating video feed using FFMPEG Transpose=1?

### DISCUSSION THREAD

**Discussion by Bod1985** [blakeblackshear/frigate#598] [Ask A Question] [answered]
Good Afternoon!

I have a camera that I have strategically mounted at the wrong angle (90 degrees) so I get a long portait image of a pathway

In BlueIris I view it using the 90 degree rotation option. How would I make it so that Frigate also views (or displays) it in portrait?

I've tried adding transpose=1 into various ffmpeg argument locations but can't seem to get it right.

Thank you in advance.

![latest](https://user-images.githubusercontent.com/1529155/105633383-1b19c380-5e50-11eb-8984-d2631c4e400b.jpg)

**Comment by blakeblackshear** [comment]
Can you post your config? I am not sure that Frigate will be able to rotate clips/recordings/rtmp without re-encoding, but the detect feed should just be a matter of getting the args right.

**Comment by farnots** [comment]
You couldn't set a rotation on the camera side ? Many camera vendors add this parameters when you configure the camera, this help to be able to put a camera upside down and will help Frigate to avoid any re-encoding.

**Comment by jschwalbe** [comment]
Well I'll post my config since I have a similar issue. My camera is mounted upside down, is a Wyzecam v2, running openmiko firmware.

```
  basement:                  #### BASEMENT ####
    ffmpeg:     
      inputs:       
        - path: rtsp://192.168.25.13:8554/video3_unicast 
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920   
      height: 1080
      fps: 5       
    rtmp:
      enabled: true     
    snapshots:   
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False   
      retain:
        default: 10
        objects: 
          person: 15
    objects:       
      track:    
        - person    
        - car
```
