### DISCUSSION TITLE
Why am I receiving detections seemingly outside of a required_zone?

### DISCUSSION THREAD

**Discussion by cameronetchart** [blakeblackshear/frigate#6002] [Ask A Question] [answered]
Hello! I am constantly receiving events for cars driving up and down my street, even though I have events limited to only a zone of my driveway. The frigate UI says each event is detected within driveway_zone, but I keep making it smaller and smaller.

Am I doing something wrong or misunderstanding how zones work? On the debug screenshot below, it's the area _inside_ the gold box that is the zone right?

**My config:**

```
database:
  path: /db/frigate.db
mqtt:
  host: redacted
  user: redacted
  password:redacted
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: pci
birdseye:
  enabled: True
  mode: continuous

objects:
  track:
   - person
   - car
   - dog
   - motorcycle
   - umbrella

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
    required_zones: 
      - driveway_zone
      - porch_zone
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  bounding_box: true
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones:
    - driveway_zone
    - porch_zone
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 14

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: URL
          roles:
            - detect
            - rtmp
            - record
    zones:
      driveway_zone:
        coordinates: 651,1080,1761,1080,1795,308,1660,299,1630,436,1259,367
    objects:
      filters:
        car:
          mask:
            - 571,272,1238,0,0,0,0,0,0,0,0,627
            - 1612,304,1286,258,1402,57,1653,92
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
      - 1694,1059,1868,1059,1873,1014,1689,1015
      - 571,272,1238,0,0,0,0,0,0,0,0,627

  Front_Door:
    ffmpeg:
      inputs:
        - path: URL
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
       - 1868,1015,1864,1056,1687,1059,1692,1011
       - 1107,0,1121,272,1031,546,763,778,511,0
    zones:
      porch_zone:
        coordinates: 477,0,635,534,1065,387,1920,773,1920,1080,0,1080,0,0
```

https://user-images.githubusercontent.com/6248778/231278812-90b186d1-9565-4dd6-a2ed-401bfee7c0bb.mp4

![snapshot-1681240530 207276-65uwe6](https://user-images.githubusercontent.com/6248778/231278815-58e31245-ac7c-40b9-bd02-8f991814df79.jpg)
![zones and mask](https://user-images.githubusercontent.com/6248778/231278816-c017e613-8e58-4fb9-8b77-67e6d579d0db.PNG)
