### DISCUSSION TITLE
Migration from rmtp

### DISCUSSION THREAD

**Discussion by geiseri** [blakeblackshear/frigate#6016] [Ask A Question]
In my case, I have quite a few different models of cameras (mjpeg,h264, h265) and I used the output options to transcode them to the same format for recording and restreaming.  It looks like I can do the same for the webrtc connections, but it was unclear how to convert some of the ffmpeg arguments I used for the transcode.
 
ex for mjpeg camera:
```yaml
cameras:
  yard:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_qsv -an
        rtmp: -c:v h264_qsv -an -f flv
      inputs:
        - path: http://10.0.11.12:8080
          roles:
            - record
            - detect
            - rtmp
```

The [Advanced Restream Configurations](https://docs.frigate.video/configuration/restream#advanced-restream-configurations) had an example, but there seem to be parts missing that I didn't need with the original configuration.  Is the guidance on how to change from the original configuration?

**Comment by NickM-27** [comment]
go2rtc makes this really easy, it is covered in the camera specific docs https://docs.frigate.video/configuration/camera_specific#mjpeg-cameras

**Reply by geiseri** [reply]
So its more or less replace the `-` with a `#`?

**Reply by NickM-27** [reply]
I am not sure what you mean replace `-` with `#`

you should just entirely forget your current config that you have above, the entirety of the config needed is in those docs, go2rtc will create the ffmpeg command and do all the work

**Reply by geiseri** [reply]
I will give it a try.  I will take a look at [ffmpeg_presets.py](https://github.com/blakeblackshear/frigate/blob/master/frigate/ffmpeg_presets.py).  I had no end of fun trying to get the right magic since my i915 revision hates nice things.  The presets approach would make things substantially cleaner!

**Reply by NickM-27** [reply]
That's the wrong place to look if you are following the docs I linked

**Reply by geiseri** [reply]
Yeah, I must be missing something.  If I look at the line: ` mjpeg_cam: "ffmpeg:{your_mjpeg_stream_url}#video=h264#hardware"` it seems to imply that it will do the transcoding at that step.  But in the input in the camera section, there is a "preset" for the `input_args`.   In the case of my h265 camera, it looks like I do not need to do anything in the `streams` section, I would put it in the `input_args` profile so that they save to recordings as h264.  Since none of my devices can consume h265, I would like to transcode the rtsp?   The configuring go2rtc page implies there, but I am concerned that since I needed to mess with my ffmpeg options for my funky Axis camera I will get stuck.  I will give the above a try, I just didn't want to go on messing with things without understanding the `#video=...` and the `input_args: preset-rtsp-generic` and if I will end up with multiple transcode/decodes.

Does that make more sense?

**Reply by NickM-27** [reply]
> But in the input in the camera section, there is a "preset" for the input_args. In the case of my h265 camera, it looks like I do not need to do anything in the streams section, I would put it in the input_args profile so that they save to recordings as h264

no, that is incorrect. an input will never transcode or change anything about the stream, because it is input.

there are also no supported presets for transcoding the video part of the stream for recordings

if your devices don't support h.265 then you will want the streams to be h.264 as well which means you will want to use a go2rtc setup just the same as mjpeg cameras to transcode it to h264

**Reply by geiseri** [reply]
Yeah, I must be missing something obvious.  It looks like I can only pass through.  My H265 and mjpeg cameras both seem to not connect with the `ffmpeg:` paths.
ex: `"ffmpeg:http://10.0.11.12:8080#video=h264"` fails with `ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:http://10.0.11.12:8080#video=h264`
 on the stream path, but I use `-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1` for my ffmpeg input args in the camera section.   

For giggles I tried the 
```
  yard:
      - http://10.0.11.12:8080
      - "ffmpeg:yard#video=h264"
```
But that failed with being unable to parse the URL. 

Originally I had to play games with the ffmpeg args for the input args to correctly decode the video stream, so I am sure it's somewhere in there.   So that was really the foundation for my original query.

**Reply by NickM-27** [reply]
I would suggest setting go2rtc exec logs to trace level so we can see what ffmpeg is complaining about

```yaml
go2rtc:
  streams:
    ...
  log:
    exec: trace

```
