### DISCUSSION TITLE
go2rtc audio lag

### DISCUSSION THREAD

**Discussion by chatziko** [blakeblackshear/frigate#6021] [General]
Hello, I'm trying the new amazing stuff in 0.12 (special thanks to all the devs) and have the following issue: my camera's audio (Tapo C210) is not aac, so I re-encode with:
```
go2rtc:
  streams:
    frigate_livingroom:
      - "rtsp://<camera-feed>"
      - "ffmpeg:frigate_livingroom#audio=aac"
```

This works, but there's a noticable (1-2 secs) audio lag (audio comes later than the image). Re-encoding both the audio and video (with `#video=h264#audio=aac`) does not improve the lag. Opening the camera feed directly in vlc has no audio lag at all.

Any ideas on how to fix this?
