### DISCUSSION TITLE
Seeking some FFMPEG Advise.

### DISCUSSION THREAD

**Discussion by cliffkujala** [blakeblackshear/frigate#6059] [Ask A Question]
I have Frigate 0.12 running with Coral TPU Inference Speed at 7-8ms, so we seem good there.  Struggling to find the correct FFMPEG settings however to take advantage of my GPU passthrough, so I receive the notice on Frigate status page that Hardware Accel is not setup. I have two types of cameras. Most are h265 streams, and then I also have ReoLink PoE Doorbell which is h264.  With the available power of this system and the low resolution of the sub-streams of these cameras, I think I want to ignore the substream all together, Transcode the main streams down and then detect off the transcoded main streams at a reasonable resolution and framerate.  I could be totally wrong about that though, and I certainly don't want to do that unless I can leverage the GPU accel.

I would appreciate any advise on what I should do inside the Frigate config.yml file to optimize this.

**System:**
- CPU - 12th Gen Intel(R) Core(TM) i5-12400
- 64gb RAM total (can give the Frigate container 12gb)
- Linux Kernel 6.2.9 (upgraded this because 5.15 kernel supposedly couldn't handle the GPU for the 12th Gen Intel CPUs)
- Proxmox 7.4.3 LXC Debian 11 Container with USB and GPU passthrough

[https://imgur.com/a/67JXhdk](https://imgur.com/a/67JXhdk)

**Below is my VAINFO when checked from the Frigate System page.**
_So I'm pretty sure I am actually passing through the GPU all the way to Frigate._
```
VAINFO OUTPUT
Return Code: 0

Process Output:

vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
VAProfileNone : VAEntrypointVideoProc
VAProfileNone : VAEntrypointStats
VAProfileMPEG2Simple : VAEntrypointVLD
VAProfileMPEG2Simple : VAEntrypointEncSlice
VAProfileMPEG2Main : VAEntrypointVLD
VAProfileMPEG2Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointVLD
VAProfileH264Main : VAEntrypointEncSlice
VAProfileH264Main : VAEntrypointFEI
VAProfileH264Main : VAEntrypointEncSliceLP
VAProfileH264High : VAEntrypointVLD
VAProfileH264High : VAEntrypointEncSlice
VAProfileH264High : VAEntrypointFEI
VAProfileH264High : VAEntrypointEncSliceLP
VAProfileVC1Simple : VAEntrypointVLD
VAProfileVC1Main : VAEntrypointVLD
VAProfileVC1Advanced : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointVLD
VAProfileJPEGBaseline : VAEntrypointEncPicture
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264ConstrainedBaseline: VAEntrypointFEI
VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointFEI
VAProfileHEVCMain : VAEntrypointEncSliceLP
VAProfileHEVCMain10 : VAEntrypointVLD
VAProfileHEVCMain10 : VAEntrypointEncSlice
VAProfileHEVCMain10 : VAEntrypointEncSliceLP
VAProfileVP9Profile0 : VAEntrypointVLD
VAProfileVP9Profile0 : VAEntrypointEncSliceLP
VAProfileVP9Profile1 : VAEntrypointVLD
VAProfileVP9Profile1 : VAEntrypointEncSliceLP
VAProfileVP9Profile2 : VAEntrypointVLD
VAProfileVP9Profile2 : VAEntrypointEncSliceLP
VAProfileVP9Profile3 : VAEntrypointVLD
VAProfileVP9Profile3 : VAEntrypointEncSliceLP
VAProfileHEVCMain12 : VAEntrypointVLD
VAProfileHEVCMain12 : VAEntrypointEncSlice
VAProfileHEVCMain422_10 : VAEntrypointVLD
VAProfileHEVCMain422_10 : VAEntrypointEncSlice
VAProfileHEVCMain422_12 : VAEntrypointVLD
VAProfileHEVCMain422_12 : VAEntrypointEncSlice
VAProfileHEVCMain444 : VAEntrypointVLD
VAProfileHEVCMain444 : VAEntrypointEncSliceLP
VAProfileHEVCMain444_10 : VAEntrypointVLD
VAProfileHEVCMain444_10 : VAEntrypointEncSliceLP
VAProfileHEVCMain444_12 : VAEntrypointVLD
VAProfileHEVCSccMain : VAEntrypointVLD
VAProfileHEVCSccMain : VAEntrypointEncSliceLP
VAProfileHEVCSccMain10 : VAEntrypointVLD
VAProfileHEVCSccMain10 : VAEntrypointEncSliceLP
VAProfileHEVCSccMain444 : VAEntrypointVLD
VAProfileHEVCSccMain444 : VAEntrypointEncSliceLP
VAProfileAV1Profile0 : VAEntrypointVLD
VAProfileHEVCSccMain444_10 : VAEntrypointVLD
VAProfileHEVCSccMain444_10 : VAEntrypointEncSliceLP
```

**Below is the FFPROBE result for the Doorbell**
```
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1920
FPS: 15/1

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: 15/1

Audio:

Codec: AAC (Advanced Audio Coding)
```

**Below is the FFPROBE result for the other 4k h265 Cameras**
```
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 3840x2160
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

**Frigate config.yml**
```
database:
  path: /db/frigate.db

mqtt:
  host: XXX.XXX.XXX.XXX
  user: USERNAME
  password: SUPERSECRET

detectors:
  coral:
    type: edgetpu
    device: usb

#ffmpeg:
#  hwaccel_args: preset-intel-qsv-h264

birdseye:
  enabled: True
  restream: False
  width: 1280
  height: 720
  quality: 8
  mode: continuous

detect:
  width: 1280
  height: 720
  fps: 15

record:
  enabled: True
  retain:
    days: 0
  events:
    pre_capture: 8
    post_capture: 8
    retain:
      default: 30

snapshots:
  enabled: True

go2rtc:
  streams:
    driveway:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h265Preview_01_main
      - "ffmpeg:driveway#video=h264"
    driveway_sub:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h264Preview_01_sub
    entryway:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h265Preview_01_main
      - "ffmpeg:entryway#video=h264"
    entryway_sub:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h264Preview_01_sub
    pool:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h265Preview_01_main
      - "ffmpeg:pool#video=h264"
    pool_sub:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h264Preview_01_sub
    back-patio:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX.14:554/h265Preview_01_main
      - "ffmpeg:back-patio#video=h264"
    back-patio_sub:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h264Preview_01_sub
    front-doorbell:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h264Preview_01_main
    front-doorbell_sub:
      - rtsp://USERNAME:SUPERSECRET@XXX.XXX.XXX.XXX:554/h264Preview_01_sub
  webrtc:
    candidates:
      - XXX.XXX.XXX.XXX:8555
      - stun:8555

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  entryway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entryway
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/entryway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  pool:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pool
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/pool_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  back-patio:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back-patio
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/back-patio_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  front-doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            #- detect
        - path: rtsp://127.0.0.1:8554/front-doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```
