### DISCUSSION TITLE
[support ?] HA+lovelace card : livestream stops/fails after a few seconds

### DISCUSSION THREAD

**Discussion by Karmak23** [blakeblackshear/frigate#6067] [General]
Sorry if this is a misconfiguration issue but it drives me nuts.

## Description of the issue

When loading any HA page in firefox containing a `frigate-card`, the live stream cards show immediately, video goes on as expected (with v0.12 the reactivity blows my mind). 

But after a fixed number of seconds (sooner for the *birdseye* [8secs] that for the other cards [~13 secs]), all `frigate-card` streams fail with this error :
```json
Failed to receive response from Home Assistant for request.[ Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).

{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////birdseye//",
    "id": 37
  },
  "response": {
    "code": "unknown_error",
    "message": "Unknown error"
  }
}
```

The other card fails the same way, which makes me think it’s a configuration issue:
```json
Failed to receive response from Home Assistant for request.[ Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).

{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////Jardin//",
    "id": 87
  },
  "response": {
    "code": "unknown_error",
    "message": "Unknown error"
  }
}
```

I’ve read the troubleshooting section, but didn't find anything related to this.

## Context / configuration

- frigate 0.12 (latest, pulled yesterday) docker-compose install. (but the problem occurs since 0.10)
- HA 20230404 supervised install, everything up-to-date.
- frigate hass integration 4.0.0 (problem occurs since before 3.0.0)

In HA lovelace, the failing birdseye card :
```yaml
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: birdseye
menu:
  style: overlay
  buttons:
    cameras:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    frigate_ui:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
    frigate:
      enabled: false
  position: right
live:
  preload: true
  draggable: false
view_layout:
  column: 2
```

But any simple card like this one also exhibits the issue :
```yaml
type: custom:frigate-card
cameras:
  - camera_entity: camera.jardin
    live_provider: webrtc-card
    webrtc_card:
      entity: camera.jardin
live:
  webrtc_card:
    ui: true
```

Note: any "non-hass" stream card does not have the problem:
```yaml
type: vertical-stack
cards:
  - show_state: true
    show_name: true
    camera_view: live
    type: picture-entity
    entity: camera.atelierexterieur
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: switch.atelierexterieur_detect
            name: Détection
      - type: entities
        entities:
          - entity: button.atelier_exterieur_reboot
            name: Reboot
```
This card streams for hours and never fails.

## Question

I{m pretty sure this is a configuration issue, but i’m stuck. How to debug the problem ? Where to search ? What can I provide to narrow it down ? Thanks for your time.
