### DISCUSSION TITLE
View only/Monitor cameras

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#6074] [Ask A Question] [answered]
Hello,

I have few cameras in some areas like 3d printers, basement and inside the home, that I would not like to do any detection or recording on.  I would like to view them in Home Assistant. This is is the current setup I have, is there a better way to do this? 

```
  trident:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264     
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://view:{FRIGATE_RTSP_PASSWORD}@ip_camera07:554/videoMain # <--- the name here must match the name of the camera in restream
          roles: []
```

```
go2rtc:
  streams: 
    trident:
      - rtsp://view:{FRIGATE_RTSP_PASSWORD}@ip_camera05:554/videoMain
```

```
