### DISCUSSION TITLE
WebRTC available in Frigate but HA uses MSE despite WebRTC Camera integration enabled

### DISCUSSION THREAD

**Discussion by Karmak23** [blakeblackshear/frigate#6084] [Ask A Question]
Hi,

after having resolved [all my woes](https://github.com/blakeblackshear/frigate/discussions/6067#discussioncomment-5617358), I now have:

- 10 TP-link Tapo cameras (7×C310, 2×C200, 1×C110), all configured at full resolution (2304×1296p) on RTSP `stream1`
- Frigate 0.12 in docker-compose container (working RTSP restream for all `record` roles ; `detect` still beeing directly mapped to low-def `/stream2` from Tapo cameras). 
  - go2rtc config OK for my 10 cameras, like:
```yaml
go2rtc:
  webrtc:
    candidates:
      - 192.168.1.11:8555
      - stun:8555
  streams:
    AbriBois:
      - rtsp://user:pass@c310-abribois.flaoueur.lan/stream1
      - "ffmpeg:AbriBois#audio=aac"
    Jardin: 
        - rtsp://user:pass@c310-jardin.flaoueur.lan/stream1
        - "ffmpeg:Jardin#audio=aac"
    [and so on]
```
- HA 202304* (latest) supervised
  - Frigate HASS Card v5.0.0.beta1 as suggested
  - `WebRTC Camera` integration successfully configured to `http://localhost:1984` (the problem I pointed in my previous topic was a typo in `PORTS` section of `docker-compose.yml`, thus resolved), localhost:1984 beeing the `go2rtc` from the Frigate container.

## What works

- WebRTC is fully working in the Frigate interface for all cameras, even with sound support.
- on local network, if I run from my notebook `mpv rtsp://server:8554/AnyCameraName`, it also works.

## What does not work

Using the following card, HA always switches to MSE and the stream is slow and flaky:

```yaml
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: Jardin
    live_provider: webrtc-card
    webrtc_card:
      url: rtsp://localhost:8554/Jardin
live:
  webrtc_card:
    ui: true
  preload: true
  draggable: false
performance:
  profile: high
```

Still, with this card, sound works.

It does not make any difference if I switch the performance profile, if I use a camera entity instead of the frigate+camera_name, nor if I set webrtc_card:entity to camera.Jardin. **It always fallsback to MSE.**

How I am supposed to make webrtc-card make use of a the WebRTC camera integration ? Or use the WebRTC stream provided by `go2rtc` from the frigate container ? 

Setting the webrtc_card:url to `webrtc://localhost:8555/Jardin` results in `stream not found` error (same with `webrtc://192.168.1.11:8555/Jardin`)

I think I miss just the last thing to make the whole thing fly.

## Subsidiary question

in Frigate go2rtc config, If I specify the srteam paths as `tapo://admin:CLOUDHEXMD5SUM@cam` or `tapo://my_cloud_pass@cam`, go2rtc fails to open the camera stream. I have to stick to the RTSP streams. 

Is the frigate container go2rtc compiled without some modules support ?

[The tapo cams are supposed to offer bi-directional audio via this streaming method](https://github.com/AlexxIT/go2rtc#source-tapo) (I’ve double checked the uppercase md5 hex value).

**Comment by NickM-27** [comment]
tapo:// only supports two way talk, not video or audio 

I'd suggest using the go2rtc provider not the WebRTC card provider in the frigate card. 

You're supposed to setup the WebRTC card with frigate_ip:1984

**Reply by Karmak23** [reply]
> tapo:// only supports two way talk, not video or audio

Thanks for the precision, it’s not that clear in the doc.
 
> I'd suggest using the go2rtc provider not the WebRTC card provider in the frigate card.

I would like, but cannot find any reference to `go2rtc` [provider] in the [frigate-hass-card README](https://github.com/dermotduffy/frigate-hass-card). How am I supposed to write it ? Could you provide an example please ?

> You're supposed to setup the WebRTC card with frigate_ip:1984

Yup, I’ve done it when installing the integration. And after ?

I cannot find any example of this use case on the net. I found [this](https://github.com/blakeblackshear/frigate-hass-integration/issues/428) and [this one](https://github.com/blakeblackshear/frigate/issues/6001) where you suggest the same (use frigate_ip:1984 in url) but cannot find any reference example to convert to my setup anywhere.

**Reply by Karmak23** [reply]
OK, narrowed it a little more with the reading of [this issue](https://github.com/AlexxIT/go2rtc/issues/138).
Going to http://frigate_ip:1984/ and watching the camera stream directly from there, it’s "RTC" in firefox.

But using `http://192.168.1.11:1984/stream.html?src=Jardin&mode=webrtc` as `webrtc-card:url` gives *“MSE: source 0 error: unsupported content-type: text-html”* (not surprising…).

Using a simple card:
```yaml
type: custom:webrtc-camera
entity: camera.jardin
```
Shows MSE again.

Using a simple card:
```yaml
type: custom:webrtc-camera
url: rtsp://127.0.0.1:8554/Jardin
```
Shows MSE too, and works for only 12 seconds (after that: infinite spinner).

Where is the go2rtc `webrtc-card:url` syntax documented ? An example would be very helpful.

**Reply by Karmak23** [reply]
I finally succeeded. Sort of.

With:
```yaml
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: Jardin
    live_provider: webrtc-card
    webrtc_card:
      entity: camera.jardin
      mode: webrtc
      muted: false
live:
  webrtc_card:
    ui: true
    background: true
  preload: true
  draggable: false
```

I get an "RTC" indication in the video card, so it seems to work. 

But the stream playback is awful, it plays for 2-3 seconds then stops for 5-10, and so on.
My CPU is not particularly hogged. In MSE I get a smoother playback (only a delay to begin after loading the HA page) with the same amount of CPU used.

kind of disapointing.

**Reply by Karmak23** [reply]
When using:
```
type: custom:frigate-card
cameras:
  - frigate:
      camera_name: jardin
    camera_entity: camera.jardin
    live_provider: go2rtc
live:
  preload: true
  draggable: false
```
I get a "one image per second" live preview… At least my CPU is let alone :rofl: 
I’ll stop trying for a while, AFK-life is calling.
