### DISCUSSION TITLE
Can't get working config...

### DISCUSSION THREAD

**Discussion by oguruma1218** [blakeblackshear/frigate#6098] [Ask A Question]
Trying to run Frigate as a standalone on a Ubuntu 22.04 VPS.

I want to start with as basic a config as possible. The camera is a Reolink E1 Zoom. I verified the rtsp stream works with VLC.

The config below produces the errors below it when I run docker-compose up

```yaml
mqtt:
  enabled: True
  host: 192.168.2.1
  port: 1883

cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.44.3:554/h264Preview_01_main # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
```

`frigate    | *************************************************************
frigate    | *************************************************************
frigate    | ***    Your config file is not valid!                     ***
frigate    | ***    Please check the docs at                           ***
frigate    | ***    https://docs.frigate.video/configuration/index     ***
frigate    | *************************************************************
frigate    | *************************************************************
frigate    | ***    Config Validation Errors                           ***
frigate    | *************************************************************
frigate    | 2 validation errors for FrigateConfig
frigate    | mqtt -> host
frigate    |   field required (type=value_error.missing)
frigate    | mqtt -> enabled
frigate    |   extra fields not permitted (type=value_error.extra)
frigate    | Traceback (most recent call last):
frigate    |   File "/opt/frigate/frigate/app.py", line 312, in start
frigate    |     self.init_config()
frigate    |   File "/opt/frigate/frigate/app.py", line 77, in init_config
frigate    |     user_config = FrigateConfig.parse_file(config_file)
frigate    |   File "/opt/frigate/frigate/config.py", line 904, in parse_file
frigate    |     return cls.parse_obj(config)
frigate    |   File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
frigate    |   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
frigate    | pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
frigate    | mqtt -> host
frigate    |   field required (type=value_error.missing)
frigate    | mqtt -> enabled
frigate    |   extra fields not permitted (type=value_error.extra)`
