### DISCUSSION TITLE
Recording: a lot of small files

### DISCUSSION THREAD

**Discussion by maxx-ukoo** [blakeblackshear/frigate#6103] [Ask A Question] [answered]
I am going to configure detection and 24/7 recording. As result I have a lot of small files 5-15 seconds. Is it possible to configure object detection with continuous recording and have 15 minutes recordings (as example)?

```
mqtt:
  host: mqtt.ххххххххххх

database:
  path: /opt/db/frigate.db

record:
  enabled: True
  retain:
    days: 30
    mode: all
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog
    - bird

detectors:
  cpu1:
    type: cpu
    num_threads: 2

cameras:
  8KPTZ-1:
    ffmpeg:
      inputs:
        - path: rtsp://10.ххххххххххххххххххххххххххххххххххххххххххххххххххх
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840
      height: 2144
    motion:
      improve_contrast: True
  8KPTZ-2:
    ffmpeg:
      inputs:
        - path: rtsp://10.ххххххххххххххххххххххххххххххххххххххххххххххххххх
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840
      height: 2144
    motion:
      improve_contrast: True
```
