### DISCUSSION TITLE
questions about stationary objects

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#6122] [Ask A Question] [answered]
I have searched and understood a bit more about stationary objects.

I have following scenario where we park a car in the driveway. This triggers very long events,  I have the recordinging set to only `active_objects`, but is this an issue to have this very long running events? what is the best practice here? things I have considered.

- object mask to include parked car area, but this precludes other cars in the driveway entering and exiting, while this car is away.
- motion mask, similar issues. 
- required_zones, where person is yard zone that includes driveway, and car is only on the driveway zone as described. 

![image](https://user-images.githubusercontent.com/152501/232486363-e7399f76-18d3-4be9-9916-1a25e9eeb97a.png)

```
 front: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264     
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://frigate:8554/front # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@ip_camera01:554/cam/realmonitor?channel=1&subtype=1 # <--- the name here must match the name of the camera in restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640  # <---- update for your camera's resolution
      height: 400 # <---- update for your camera's resolution
      stationary:
        interval: 0
        threshold: 30
        max_frames:
          objects:
            person: 300   
            car: 50000     
    motion:
      mask:
      - 640,0,640,47,426,46,423,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 10
        objects:
          person: 15
      required_zones:
          - driveway
          - yard 
    objects:
      filters:
        car:
          mask:
             - 119,243,197,143,336,0,160,0,67,96,0,179,0,256 # exluding driway
          #  - 119,243,264,259,341,112,194,144,336,0,160,0,67,96,0,179,0,256 # inc.driveway 
          # min_score: 0.7
          # threshold: 0.85
        person:
          mask:
            - 255,243,295,162,113,176,271,0,195,0,153,11,117,61,68,108,0,194,3,400,117,248
          # min_score: 0.
          # threshold: 0.85
    record:
      events:
        objects:
          - car
          - person
          - truck
        required_zones:
          - driveway
          - yard
        retain:
          default: 7
          mode: active_objects
    zones:
      driveway:
        coordinates: 134,400,640,400,597,68,419,63,348,116,298,214,144,211,47,338
        objects:
          - car
      yard:
        coordinates: 101,400,640,400,640,0,461,0,411,0,308,0,221,86,43,340
        objects:
          - person
          - bicycle
    ui:
      order: 2
```

**Comment by NickM-27** [comment]
a long event is the expected and intended behavior, forcefully blocking the event just creates more opportunity for frigate to get confused as a car randomly comes in and out of existence due to motion, other cars driving by, etc.

**Comment by vajonam** [comment]
So,

remove 

```
        max_frames:
          objects:
            person: 300   
            car: 50000  
``` 

the `person` entry is to avoid false positives for person that appears in the low light, IR lighting. the `car` entry was meant to identify a parked car and consider it stationary.
