### DISCUSSION TITLE
Is there a typo for amd cpu?

### DISCUSSION THREAD

**Discussion by moskovskiy82** [blakeblackshear/frigate#6185] [General]
Running latest frigate in docker. Made sure ti's latest with docker pull just now.
Have an AMD 8xxx series card

Ubuntu 20.03 Server

Relevant docker compose env added

```
cat compose.yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "2048mb" # update for your cameras based on calculation above
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - Docker/frigate/config.yml:/config/config.yml:ro
      - Docker/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
      - PGID=1001
```

  hwaccel_args: preset-vaapi added to config.yml.

```
ffmpeg:
  hwaccel_args: preset-vaapi

```
And get an error of. Did i miss something in the docs?

[2023-04-20 21:28:28] watchdog.x              ERROR   : Ffmpeg process crashed unexpectedly for x
[2023-04-20 21:28:28] watchdog.x              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2023-04-20 21:28:28] ffmpeg.x.detect         ERROR   : [NULL @ 0x561e4722ae80] Unable to find a suitable output format for 'preset-vaapi'
