### DISCUSSION TITLE
Audio stream through generic camera using webrtc

### DISCUSSION THREAD

**Discussion by Remko76** [blakeblackshear/frigate#6190] [Ask A Question] [answered]
I have a setup with Frigate and homeassistant running in Docker on Ubuntu on a NUC 5th gen i5. All working good and stable so far. I just have one issue which I cannot seem to figure out: I am trying to use go2rtc to have a low res stream with audio for viewing in Homeassisant. The relevant part of my config:

```
go2rtc:
  streams:
    esszimmer:
      - rtsp://USER:PASS@192.168.76.63:554/live/ch0
      - "ffmpeg:esszimmer#audio=opus"
    esszimmer_sub:
      - rtsp://USER:PASS@192.168.76.63:554/live/ch1
      - "ffmpeg:esszimmer_sub#audio=opus"
    carport:
      - rtsp://USER:PASS@192.168.76.61:554/live/ch0
      - "ffmpeg:carport#audio=opus"      
    carport_sub:
      - rtsp://USER:PASS@192.168.76.61:554/live/ch1
      - "ffmpeg:carport_sub#audio=opus"
  
cameras:
  esszimmer: # <------ Name the camera
    ffmpeg:
      inputs:
        #High Res
        - path: rtsp://127.0.0.1:8554/esszimmer # <--- the name here must match the name of the camera in restream
          roles:
            - record
        #Low Res    
        - path: rtsp://127.0.0.1:8554/esszimmer_sub # <--- the name here must match the name of the camera in restream
          roles:
            - detect

  carport: # <------ Name the camera
    ffmpeg:
      inputs:
        #High Res
        - path: rtsp://127.0.0.1:8554/carport# <--- the name here must match the name of the camera in restream
          roles:
            - record
        #Low Res    
        - path: rtsp://127.0.0.1:8554/carport_sub # <--- the name here must match the name of the camera in restream
          roles:
            - detect
```

Through the official integration it all works and I get audio in Homeassistant. It uses the high res stream by default, so I wanted to set up a camera in Homeassistant using the low res stream. I did following steps:
- Install the RTSP2WebRTC integration and configured it to connect to go2rtc
- Setup a generic camera with the following url: ```rtsp://127.0.0.1:8554/carport_sub```

When I now open the stream from the generic camera in Homeassistant I get video but no audio. The info about the stream in go2rtc shows following:
```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://127.0.0.1:8554/carport_sub",
      "remote_addr": "127.0.0.1:8554",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 97 MPEG4-GENERIC/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1"
      ],
      "recv": 547703
    }
  ],
  "consumers": [
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 92.116.95.243:59653 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
      "send": 522289
    }
  ]
}
```

When I compare that to one of the streams used by Frigate, it shows this:
```
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.76.61:554/live/ch1/",
      "remote_addr": "192.168.76.61:554",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 97 MPEG4-GENERIC/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=2",
        "97 MPEG4-GENERIC/8000, sinks=2"
      ],
      "recv": 30569291
    },
    {
      "url": "ffmpeg:carport_sub#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://127.0.0.1:8554/carport_sub",
      "remote_addr": "127.0.0.1:45682",
      "user_agent": "FFmpeg Frigate/0.12.0-da3e197",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 97 MPEG4-GENERIC/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=2",
        "97 MPEG4-GENERIC/8000, sinks=2"
      ],
      "send": 30569291
    },
    {
      "type": "RTSP client",
      "url": "rtsp://127.0.0.1:8554/carport_sub",
      "remote_addr": "127.0.0.1:44370",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 97 MPEG4-GENERIC/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=2",
        "97 MPEG4-GENERIC/8000, sinks=2"
      ],
      "send": 2255026
    }
  ]
}
```

Under the "tracks" section, I can see that it also uses the reencoded audio stream, but not when I try to use the generic camera integration. The strangest thing though, is that it is not consistent. If I restart frigate, go2rtc, reload the integrations etc...sometimes I do get audio and everything works. Again, this is highly inconsistent and it only works around 1 in 5 times, so something must be wrong.

Any ideas what I am missing here,  or anyone can explain this behavior? I am going crazy over this.
