### DISCUSSION TITLE
Zones and detections

### DISCUSSION THREAD

**Discussion by kimbo1st** [blakeblackshear/frigate#6197] [General]
For my driveway I have configured this way that the street is masked zone and one place on my driveway no detection of a car because it is parked there.
I notice that sometimes it does trigger an event on the masked zones and detect a car or person.
The same counts for the space where the car is parked, where it only needs to detect person or cat.

This is my config for this specific camera:

```


  oprit:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/oprit # <--- the name here must match the name of the camera in restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/oprit_sub # <--- the name here must match the name of the camera_sub in restream
          roles:
            - detect
    zones:
      inrit:
        coordinates: 466,292,354,408,219,436,0,401,0,720,227,720,531,720,1280,720,1280,224,970,110,750,55,737,136,745,122,696,135,467,148,440,158,479,218
        objects:
          - person
          - car
          - cat
      auto_plaats:
        coordinates: 414,132,469,229,306,472,45,407,204,164
        objects:
          - person
          - cat
    objects:
      track:
        - person
        - car
        - cat
    motion:
      mask:
        - 303,0,300,44,0,48,0,0
        - 746,0,743,130,317,140,301,0
        - 0,599,69,615,127,511,82,420,0,440
        - 1280,0,1280,226,981,105,743,58,745,0
    snapshots:
      enabled: true
      required_zones:
        - inrit
        - auto_plaats
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      events:
        required_zones:
          - inrit
          - auto_plaats
      retain:
        days: 10
```

Aside of this I also notice that it makes also long clips... recording 20min, one hour and even 2 hours... don't know why... ie when it rains it records the rain probably while I only want objects to record for the time it is there.

Running it in docker on my Synology NAS.

![coral](https://user-images.githubusercontent.com/14580768/233773825-0f83312f-71d1-4369-8315-31896baa473d.png)
