### DISCUSSION TITLE
Clarification on CPU vs GPU loads

### DISCUSSION THREAD

**Discussion by hagak** [blakeblackshear/frigate#6199] [General]
I understand that the detect phase relies on CPU and/or GPU.  Should I expect my CPU load to still be high on the detect when I have an NVIDIA T1000 GPU configured?
Per camera I see CPU usage in the 300% range while GPU only around 4-5%.  
I have updated my config to use the presets as well.

My feeds are either the _ext reolink or the _sub reolink so not trying to run detect on 4k video.

Note I currently have the system running fine, just making sure I have it optimized properly for my config so understanding if these loads are what I should expect or not.

**Comment by NickM-27** [comment]
Without a config or the system page it is difficult to give advice or see what is going on.

But in general for the detect process:
- **video decoding:** runs on CPU (not recommended) or runs on GPU
- **motion detection:** always runs on CPU
- **object detection:** runs on CPU (not recommended) or runs on AI accelerator (GPU, coral, etc.)

**Comment by hagak** [comment]
```
---
# yaml-language-server: $schema=http://frigate.home.thetank.org/api/config/schema

database:
  path: /media/frigate/data/frigate.db

detectors:
  coral_pci0:
    type: edgetpu
    device: pci:0
  coral_pci1:
    type: edgetpu
    device: pci:1
  coral_pci2:
    type: edgetpu
    device: pci:2
  coral_pci3:
    type: edgetpu
    device: pci:3

# Required: mqtt configuration
mqtt:
  host: homeasssistant_mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

record:
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 14
      mode: active_objects

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac
    rtmp: preset-rtmp-generic

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

go2rtc:
  webrtc:
    candidates:
      - X.X.X.X:8555
      - stun:8555
  streams:
    dooryard:
      - http://X.X.X.X/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:dooryard#audio=opus"
    den:
      - http://X.X.X.X/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:den#audio=opus"

cameras:
  dooryard:
    ffmpeg:
      inputs:
        - path: 'http://X.X.X.X/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}'
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/dooryard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      enabled: true
      max_disappeared: 35
      height: 512
      width: 896
      fps: 7
    motion:
      mask:
        - 896,388,829,377,757,360,404,512,896,512
        - 385,0,385,47,0,55,0,0
    zones:
      driveway:
        coordinates: 380,512,754,375,896,382,896,263,838,157,680,0,532,0,657,167,303,203,360,404
      parkingarea:
        coordinates: 0,160,299,174,444,204,600,462,0,512
      yard:
        coordinates: 0,0,527,0,602,53,634,199,0,275
    # Optional: Camera level object filters config. If defined, this is used instead of the global config.
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          min_area: 800
          max_area: 20000
          min_score: 0.45
          threshold: 0.7
        car:
          mask:
            - 216,307,212,123,0,134,0,358
          min_area: 2000
          max_area: 400000
          min_score: 0.35
          threshold: 0.7

  den:
    ffmpeg:
      inputs:
        - path: 'http://X.X.X.X/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}'
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/den?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      enabled: true
      max_disappeared: 35
      height: 480
      width: 640
      fps: 7

    zones:
      basement_stairs:
        coordinates: 896,22,896,640,521,651,577,83
    # Optional: Camera level object filters config. If defined, this is used instead of the global config.
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 7000
          max_area: 90000
          min_score: 0.55
          threshold: 0.75
        cat:
          min_area: 1000
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
```

Note I have more cameras but just removed the extras because the configs are just repeated
