### DISCUSSION TITLE
Little confusion in the docs

### DISCUSSION THREAD

**Discussion by moskovskiy82** [blakeblackshear/frigate#6202] [Ask A Question]
I have a UDP only camera which works in the following manner when setup under camera:

```
  road:
    ffmpeg:
      inputs:
        - path: rtsp://xx.xx.2.95:554/user=admin&password=xx&channel=1&stream=0?.sdp
          input_args: preset-rtsp-udp
          roles:
            - record
```

Looking at the docs the go2rtc acts as a server in between
So do i put the ffmpg: preset-rtsp-udp in the go2rtc section or just in the camera section under

If i leave it in the camera section - get ffmpeg errors
