### DISCUSSION TITLE
access to camera GUI via Frigate?

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#6250] [Ask A Question]
Is there any way to access the camera GUI through Frigate?

Specifically, I have my cameras sequestered on a separate network. My Frigate runs in a docker container on a Minisforum GK41 with two nics. One nic is connected to this camera-only network, the other to my router. Is there any way for me to bring up a camera's GUI on my laptop connected to the router?

Currently, I have to physically connect to my laptop to the camera-only network to bring up a camera's GUI. I've read online that a SOCKS proxy might allow me to connect to the cameras via the Minisforum GK41. I am curious if there is any built-in functionality in Frigate 0.12 that already provides this access.

**Comment by NickM-27** [comment]
Frigate does not offer this functionality

**Reply by Cold-Lemonade** [reply]
Any plans to add it?

**Reply by NickM-27** [reply]
I don't think that really falls into the usecase of frigate, that's more of a networking issue

**Reply by Cold-Lemonade** [reply]
Well, it would make it easier to manage the cameras.

If I wanted to create this functionality myself, how would I do it? From what I've read online--and I make no claim of being an expert on these matters--I think I need to install and set up a SOCKS proxy server on the Minisforum GK41 that will pass along its ip address on the camera-only network to my laptop. Is that right?

**Reply by NickM-27** [reply]
there's many different ways to setup segment networks / VLANs / etc. There's many different ways that it could be setup so the laptop could configure a camera, and much more information would be needed to give a helpful answer on what to do. In any case, like I said I think this is outside the scope of frigate itself.

**Reply by blakeblackshear** [reply]
I do this with traefik and it works very well. I will post an example soon.

**Reply by Cold-Lemonade** [reply]
@blakeblackshear I look forward to seeing your example! Thank you.

**Comment by blakeblackshear** [comment]
I use traefik to make each camera's web ui available at a dedicated subdomain. Note that most camera UIs are unlikely to support being nested under a path like `frigate.your-domain.com/camera/ui` because the path rewriting will not work. This is why frigate will almost certainly never support anything like this directly. 

This is going to be a lot more information than you asked for but, here is a starting point for a docker compose file with traefik that does this and more. It includes the config for putting frigate and the camera UIs behind google authentication on top of their built in auth (which i would never trust enough to expose directly). I even use the same approach to give my robot vacuum its own subdomain with auth.

```yaml
---
version: "3.9"

secrets:
  # used by traefik to do DNS verification for wildcard certificates
  cf_api_key:
    file: ./secrets/cf_api_key
  # used by traefik-forward-auth for google oidc logins
  forward_auth:
    file: ./secrets/forward_auth

services:

  # since the cameras are on a static network with no internet,
  # I run this ntp server for them to sync there timestamps
  # cameras have their ntp server set to 10.0.11.1
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      # 10.0.11.1 is the static ip I have configured for my second NIC
      - 10.0.11.1:123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
      - TZ=America/Chicago
  
  # i didnt include all the other config since its in the official docs
  frigate:
    container_name: frigate
    ...
    ports:
      # bind to the docker gateway ip because the home assistant container runs in host network mode
      # and this allows the integration to access frigate at 172.17.0.1:5000 without exposing 5000
      - "172.17.0.1:5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.your-domain.com`)"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.tls.certresolver=le"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
      - "traefik.http.routers.frigate.middlewares=traefik-forward-auth"

  # there are lots of ways to do this. I prefer to use DNS verification with lets encrypt
  # so I get one wildcard certificate for all domains
  traefik:
    container_name: traefik
    restart: always
    image: traefik:v2.9
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=false"
      # this file is where I provide traefik config for the camera services
      - "--providers.file.filename=/etc/traefik/services.yml"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--serversTransport.insecureSkipVerify=true"
      - "--certificatesresolvers.le.acme.dnschallenge"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.le.acme.email=your-email@email.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.http.tls.domains[0].main=your-domain.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.your-domain.com"
      - "--entrypoints.websecure.http.tls.certresolver=le"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.your-domain.com`)"
      - "traefik.http.routers.dashboard.service=dashboard"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=traefik-forward-auth"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
    environment:
      - CF_API_EMAIL=your-email@email.com
      - CF_API_KEY_FILE=/run/secrets/cf_api_key
    secrets:
      - cf_api_key
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      # IMPORTANT: this file is where I map in services for traefik to handle that dont run in
      # docker compose. You can proxy anything on your network.
      - ./traefik-services.yml:/etc/traefik/services.yml
    extra_hosts: 
      # this is necessary to ensure traefik can proxy to containers running in host networking mode
      - host.docker.internal:172.17.0.1

  traefik-forward-auth:
    container_name: traefik_forward_auth
    restart: always
    image: thomseddon/traefik-forward-auth:2
    secrets:
      - source: forward_auth
        target: /config
    environment:
      - CONFIG=/config
      - COOKIE_DOMAIN=your-domain.com
      - AUTH_HOST=auth.your-domain.com
      - WHITELIST=your-email@gmail.com
      - LOGOUT_REDIRECT=https://your-domain.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.your-domain.com`)"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=websecure"
      - "traefik.http.routers.traefik-forward-auth.tls.certresolver=le"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
```

Here is the `traefik-services.yml` file that I mount in the traefik container at `/etc/traefik/services.yml`:

```yaml
http:
  routers:
    back:
      entryPoints:
        - "websecure"
      rule: "Host(`back.your-domain.com`)"
      tls:
        certResolver: le
      middlewares:
        - traefik-forward-auth@docker
      service: back
    door:
      entryPoints:
        - "websecure"
      rule: "Host(`door.your-domain.com`)"
      tls:
        certResolver: le
      middlewares:
        - traefik-forward-auth@docker
      service: door
  services:
    back:
      loadBalancer:
        servers:
        # here is where you forward to the camera web portal
        - url: "http://10.0.11.10/"
    door:
      loadBalancer:
        servers:
        # here is where you forward to a second camera web portal
        - url: "http://10.0.11.11/"
```

**Reply by shred86** [reply]
@blakeblackshear Thank you for sharing this - I just recently setup Traefik and was able to learn a lot from your `docker-compose.yml` and `services.yml`. One quick question, and I apologize for this being slightly off topic but I've spent a considerable amount of time trying to get this to work. When I attempt to do something like this:

````
    environment:
      - CF_API_KEY_FILE=/run/secrets/cf_api_key
```` 

When I go into the container and `echo $CF_API_KEY_FILE`, it's returning the path `/run/secrets/cf_api_key` (i.e. what I set in the docker-compose file) instead of the contents of `/run/secrets/cf_api_key` which contains the actual key I'm trying to use. Any ideas why this is?

**Reply by blakeblackshear** [reply]
Docker secrets don't replace the value of the environment variable. https://docs.docker.com/engine/swarm/secrets/

1. Create a folder called `secrets` next to your docker-compose.yml file
2. In that folder, create a file named `cf_api_key` with the contents of the file being your actual api key
3. In docker compose, register that file as a secret with:
    ```yaml
    secrets:
      # used by traefik to do DNS verification for wildcard certificates
      cf_api_key:
        file: ./secrets/cf_api_key
    ```
4. Tell docker that the traefik container should have the secret injected (secrets are mounted as a file in `/run/secrets/`)
    ```yaml
    secrets:
      - cf_api_key
    ```
5. The environment variable tells Traefik to look for the CF_API_KEY in the file at `/run/secrets/cf_api_key` within the container.
