### DISCUSSION TITLE
Stationary grill detected as person/dog

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#6251] [Ask A Question]
Hello fellow Frigators!

I have been working to tune out false positives based information I've seen on the official documentation as well as over Github and Reddit but I am coming to an impasse with a problem I am having.

I have a camera facing my patio called "BBQ Deck" and there is a grill on there that is covered or some times the cover is off and seen in either situation from time to time Frigate classifies the grill covered or not covered as a Person or Dog from time to time. I've removed all masking after reading other feed back and even created a zone but haven't gone as so far to create a zone for just the grill but was hoping to find a better way. 

Here are a few sample snapshots showing the problem:

![snapshot-1682383102 417542-788n4o](https://user-images.githubusercontent.com/108703/234321664-8249d796-82d7-46bb-845b-2014ba57f664.jpg)
![snapshot-1682430302 339636-rya6x0](https://user-images.githubusercontent.com/108703/234321666-c9a5642d-54cc-477b-9bda-5e309ec030a1.jpg)
![snapshot-1682189464 40846-5d7im1](https://user-images.githubusercontent.com/108703/234321671-95f31a9a-ecf8-4576-b5af-8dd5855feb81.jpg)

Here is one example where things were fine showing the Dog and the grill actually with the cover off:

![snapshot-1682260630 500931-dya9dw](https://user-images.githubusercontent.com/108703/234321782-0dfb940c-56da-4b2a-a3cd-60df9da13f91.jpg)

Here is my configuration for the camera:

```
  bbq_deck: # <------ Name the camera, VI 18 lines for detect
    ui:
      order: 5
    record:
      events:
        required_zones:
          - BBQ
    snapshots:
      required_zones:
          - BBQ
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bbq_deck # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bbq_deck_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704
      height: 480
      enabled: True
      fps: 5
    zones:  
      BBQ:
        coordinates: 0,480,0,314,221,0,416,0,495,121,577,293,657,480
        objects:
          - person
          - dog
```

I really appreciate any help or guidance on how to tune this so it doesn't occur anymore.

**Comment by NickM-27** [comment]
Seems that the location is consistent, probably suggest a small object mask on the bottom center of the bounding box

**Reply by pyrodex** [reply]
So something like this?

![image](https://user-images.githubusercontent.com/108703/234328068-d454dc37-85cf-4217-a3af-7922cbf04ff0.png)

```
  bbq_deck: # <------ Name the camera, VI 18 lines for detect
    ui:
      order: 5
    record:
      events:
        required_zones:
          - BBQ
    snapshots:
      required_zones:
          - BBQ
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bbq_deck # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bbq_deck_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704
      height: 480
      enabled: True
      fps: 5
    zones:  
      BBQ:
        coordinates: 0,480,0,314,221,0,416,0,495,121,577,293,657,480
        objects:
          - person
          - dog
		filters:
		  person:
		    mask: 297,419,450,418,412,103,299,103
		  dog:
		    mask: 297,419,450,418,412,103,299,103
```

**Reply by NickM-27** [reply]
No, like I said you only need to cover the bottom center of the bounding box with an object mask. That is the only part that matters

**Reply by pyrodex** [reply]
Are you saying move the mask into the Zone? Sorry I am not understanding that fully.

**Reply by NickM-27** [reply]
I am saying that, an object mask blocking an object is solely based on if the mask overlaps with the bottom center pixel of the objects bounding box. So, you don't need a large mask on the entire BBQ you simply need a small mask on that one point.

![234321664-8249d796-82d7-46bb-845b-2014ba57f664](https://user-images.githubusercontent.com/14866235/234332414-6e58f7b6-5d54-4935-8c6c-752991f77321.jpg)

**Reply by pyrodex** [reply]
Oh, thank you for that input. Going to try that now!

**Reply by pyrodex** [reply]
Was my configuration example for the masks correct minus the size?

**Reply by NickM-27** [reply]
I believe so

**Comment by pyrodex** [comment]
So I am still having this issue and not sure what is going on and I've tried everything. Seems like with the recent wind in my area I am getting more and more false positives. 

Any help is appreciated!

![image](https://user-images.githubusercontent.com/108703/235464107-e7872e37-35a4-476e-a16d-b863c22ba3c4.png)

Config:
```
  bbq_deck: # <------ Name the camera, VI 18 lines for detect
    ui:
      order: 5
    record:
      events:
        required_zones:
          - BBQ
    snapshots:
      required_zones:
          - BBQ
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/bbq_deck # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bbq_deck_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704
      height: 480
      enabled: True
      fps: 5
    zones:  
      BBQ:
        coordinates: 0,480,0,314,221,0,416,0,495,121,577,293,657,480
        filters:
          person:
            mask: 
              - 315,392,427,381,387,124,313,120
              - 257,0,262,53,207,57,205,0
            max_area: 15000
            min_area: 2000
            threshold: 0.7
          dog:
            mask: 
              - 315,392,427,381,387,124,313,120
              - 257,0,262,53,207,57,205,0
            max_area: 15000
            min_area: 2000
            threshold: 0.7
```
