### DISCUSSION TITLE
unable to hear audio in recording

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#6257] [Ask A Question]
Here are my relevant sections. I am able to hear the audio in the live stream on webrtc when click on the camera webrtc. 

ffprobe output

```
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"8/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":720,"width":1280},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"24/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1624,"width":2880}]}}]
```

```
go2rtc:
  streams:
    doorbell:
      - rtsp://ip_camera08:554/live/0/MAIN
        ffmpeg:doorbell#audio-aac
```

```
cameras:
  doorbell: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
          record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://ip_camera08:554/live/0/SUB # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://frigate:8554/doorbell # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
```

What am I missing?

**Comment by NickM-27** [comment]
you have `ffmpeg:doorbell#audio-aac` but the docs have `ffmpeg:doorbell#audio=aac`

**Comment by vajonam** [comment]
good catch but that didn't change it, the fact that I can hear it on webrtc means the go2rtc is streaming restreaming it correctly. Its got a G711.U codec vs aac, I am leaning towards a ffmpeg preset that needs to re-encode that to aac or somthing similar?

**Reply by NickM-27** [reply]
if you restart that should definitely fix it. The problem is that by default frigate will only provide aac audio from the restream, so there is not even audio to transcode. You can check the go2rtc dashboard to see what is being sent. worst case you need to use `rtsp://frigate:8554/doorbell?video&audio` to override the default query and get all audio included

**Comment by vajonam** [comment]
tried the`preset-record-generic-audio-copy` as well on the record args.

**Comment by vajonam** [comment]
hmm 

this seemed to fix it 

```
go2rtc:
  streams:
    doorbell:
      - ffmpeg:rtsp://ip_camera08:554/live/0/MAIN#video=copy#audio=aac
        # ffmpeg:doorbell#audio=aac
```

shouldn't the previous config have worked? it turned out the rtsp://frigate:8554/doorbell stream did not have an audio track. even though i asked it to have one.
