### DISCUSSION TITLE
MSE view not available

### DISCUSSION THREAD

**Discussion by moskovskiy82** [blakeblackshear/frigate#6269] [General]
Have 2 cameras under frigate. One allows MSE view and the second one doesn't. Looking at codec in vlc i don't see any difference. The one failing although also translates some info on the color spectrum ITU-R 709 which I don't think should be the case.
Both are H264
The roads one doesn't give any options except for jsmpeg

```
go2rtc:
  streams:
    mains:
      - "http://192.168.99/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=someone&password=password"
      - "ffmpeg:reolink#audio=opus"
    mains_sub:
      - "http://192.168.99/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=someone&password=password"
    roads:
      - "rtsp://192.168.95:554/user=someone&password=password&channel=1&stream=0?.sdp#input=rtsp/udp"
    roads_sub:
      - "rtsp://192.168.95:554/user=someone&password=password&channel=1&stream=1?.sdpinput=rtsp/udp"

cameras:
  mains:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/mains?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: mains

  road:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/roads?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/roads_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: road
```
