### DISCUSSION TITLE
Camera Video Pulsing?

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#6272] [Ask A Question] [answered]
I've setup Frigate with mostly AMCREST cameras along with one linger HIKVISION I am working to replace. When I view the clips of events produced by Frigate or even view the camera feed live on the MAIN feed I see what I can only describe as is a "pulsing" effort on the video that isn't there if I view the debug of the same camera on the SUB feed. 

I am using the go2rtc re-streaming to help reduce the number of connections to my cameras and ensure if something else needs to consume them it goes through the go2rtc feeds. I didn't know if there are any tuning changes in the go2rtc setup to prevent this but I am using the Amcrest recommended URLs from the vendor and if pull it myself directly I don't see this "pulsing". Prior to Frigate, was an old Zoneminder user and gave up on it and issues in the past, I opted to record myself and just comb over footage as needed. All those self records were using ffmpeg so similar to what go2rtc does but not sure why this pulsing is there. 

All of my cameras are of a more recent model from Amcrest and I've confirmed the firmware is at the latest:

![image](https://user-images.githubusercontent.com/108703/234687716-592eb301-f8ae-48a0-b06f-07fd0e55dfb5.png)

I am running this in Docker with an 13th Gen Intel(R) Core(TM) i7-13700 on a ASRock Z790 Steel Legend WiFi motherboard with one Coral TPU and one Coral Dual EDGE TPU. 

Here is an example clip:

Sorry for URL but it was too big (23MB) to upload here.

https://www.dropbox.com/s/k6gorpo6vw5vho4/clip_driveway_1682535468.514582-1682535503.872154.mp4?dl=0

And as always here is my configuration for the go2rtc and the camera in this example:

```
go2rtc:
  rtsp:
    username: "blah"
    password: "blah"
  streams:
    driveway: 
      - rtsp://blah:blah@<IP>:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - "ffmpeg:driveway#audio=opus"
    driveway_sub: 
      - rtsp://blah:blah@<IP>:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
      - "ffmpeg:driveway_sub#audio=opus"
cameras:
  driveway: # <------ Name the camera
    ui:
      order: 1
    record:
      events:
        required_zones:
          - Driveway
    snapshots:
      required_zones:
          - Driveway
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 704
      height: 480
      enabled: True
      fps: 5
    zones:  
      Driveway:
        coordinates: 0,480,704,480,704,141,508,81,305,81,166,108,70,145,0,204
        objects:
          - person
          - bicycle
          - car
          - motocycle
          - truck
          - dog
        filters:
          car: 
            min_area: 5000
            threshold: 0.7
      Street:
        coordinates: 97,109,298,77,495,69,704,133,704,0,529,0,365,0,125,0,0,0,0,160
        filters:
          car: 
            mask: 167,37,301,30,301,0,160,0
          person: 
            mask: 704,0,704,137,652,123,660,0
```

Any assistance or guidance is much appreciated.
