### DISCUSSION TITLE
Frigate with TrueNAS scale docker-compose app?

### DISCUSSION THREAD

**Discussion by oguruma1218** [blakeblackshear/frigate#6277] [General]
I'm trying to get Frigate set up in a TrueNAS Scale Docker container using the docker-compose app. My docker-compose and config are below

My docker-compose.yml is 

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-lin>
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/fasttank/appdata/frigate/frigate.yml:/config/config.yml
      - /mnt/fasttank/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "50000:5000"
      - "18554:8554" # RTSP feeds
      - "18555:8555/tcp" # WebRTC over tcp
      - "18555:8555/udp" # WebRTC over udp
#    environment:
#      FRIGATE_RTSP_PASSWORD: "password"

```

my config is

```
mqtt:
  host: 192.168.2.1

go2rtc:
  streams:
    nursery:
      - rtsp://admin:password@192.168.44.1:554/h264Preview_01_sub
      - "ffmpeg:reolink#audio=opus"


cameras:
  camera_1: # <------ Reolink Duo
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.44.1:554/h264Preview_01_sub # <----- The stream you want to use for detection
          roles:
            - record
  kitchen: # <------ Axis 1065-LW
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.44.2/axis-media/media.amp
          roles:
            - record
#   camera_2: # <------ HikVision Bullet
#    ffmpeg:
#      inputs:
#        - path: rtsp://admin:password@192.168.44.6:554/Streaming/Channels/101
#            - detect
  nursery: # <------ ReoLink E1 Zoom
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nursery
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution

```
