### DISCUSSION TITLE
Increase log level for

### DISCUSSION THREAD

**Discussion by moskovskiy82** [blakeblackshear/frigate#6295] [General]
Have a reolink camera B800 which feeds 265 through the Neolink server (server emulates the proprietary Reolink protocol). I can easily open the Neolink rtsp stream in vlc.  Which gives me that it's an h265 HEVC at a resolution of 3840x2160

Unfortunately putting this stream to cameras part of frigate didn't give any stream. So i've decided to feed it to go2rtc and do some conversions.

```
go2rtc:
  streams:
    tmbr: 
      - "rtsp://192.168.2.8:8551/Main"
      - "ffmpeg:tambur#video=h264"
    tmbr_sub: 
      - "rtsp://192.168.2.8:8551/Main/substream" 
```

The later one is already H264.

Cameras

```
  tmbr:
    ffmpeg:
      inputs:

        - path: rtsp://127.0.0.1:8554/tmbr?video=copy
          input_args: preset-rtsp-restream        
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tmbr_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```

In ffmpeg logs for frigate i only get

2023-04-27 20:36:15.026131560  [2023-04-27 20:36:15] ffmpeg.tmbr.detect           ERROR   : [rtsp @ 0x559d70f75c40] method DESCRIBE failed: 404 Not Found
2023-04-27 20:36:15.026363514  [2023-04-27 20:36:15] ffmpeg.tmbr.detect           ERROR   : rtsp://127.0.0.1:8554/tmbr_sub?video=copy: Server returned 404 Not Found
2023-04-27 20:36:15.039931275  [2023-04-27 20:36:15] ffmpeg.tmbr.record           ERROR   : [rtsp @ 0x55e9cbb1fd80] method DESCRIBE failed: 404 Not Found
2023-04-27 20:36:15.045580552  [2023-04-27 20:36:15] ffmpeg.tmbr.record           ERROR   : rtsp://127.0.0.1:8554/tmbr?video=copy: Server returned 404 Not Found

And  unfortunately in go2rtc

```
2023-04-27 20:35:23.223868914  [INFO] Starting go2rtc...
2023-04-27 20:35:23.327642215  20:35:23.327 INF go2rtc version 1.2.0 linux/amd64
2023-04-27 20:35:23.327984555  20:35:23.327 INF [api] listen addr=:1984
2023-04-27 20:35:23.328424796  20:35:23.328 INF [rtsp] listen addr=:8554
2023-04-27 20:35:23.328854726  20:35:23.328 INF [srtp] listen addr=:8443
2023-04-27 20:35:23.329131524  20:35:23.329 INF [webrtc] listen addr=:8555
2023-04-27 20:35:33.224242199  [INFO] Starting go2rtc healthcheck service...
```

I also cannot connect to go2rtc streams for this camera from VLC (other ones - with no problem). SO how can i debug this problem?

**Comment by NickM-27** [comment]
the logs are 404 not found meaning there is no stream coming from that URL to go2rtc.

**Reply by moskovskiy82** [reply]
> the logs are 404 not found meaning there is no stream coming from that URL to go2rtc.

I think not. In this case that is that frigate doesn't get anything from the go2rtc. Otherwise. Comment this cam in go2rtc section.
Put everything under cameras config


```
  tmbr:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.8:8551/Main/substream
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
```

And everything flows nice and easy. 
```

2023-04-27 20:50:17.287943955  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 10 leaked shared_memory objects to clean up at shutdown
2023-04-27 20:50:17.287952064    warnings.warn('resource_tracker: There appear to be %d '
2023-04-27 20:50:17.291458579  [INFO] Service Frigate exited with code 0 (by signal 0)
2023-04-27 20:50:22.538923968  [INFO] Starting Frigate...
2023-04-27 20:50:24.156628464  [2023-04-27 20:50:24] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
```

**Reply by NickM-27** [reply]
the same log happens on Frigate's side in both cases, go2rtc will send a 404 if the stream is not connecting on go2rtc side.

If it works in frigate, then it does seem it is some issue with getting a response from go2rtc. Most likely the issue is that you have put `ffmpeg:tambur#video=h264` in your config but you called the camera `tmbr` so of course that is referencing a stream that doesn't exist

**Reply by moskovskiy82** [reply]
> the same log happens on Frigate's side in both cases, go2rtc will send a 404 if the stream is not connecting on go2rtc side.
> 
> If it works in frigate, then it does seem it is some issue with getting a response from go2rtc. Most likely the issue is that you have put `ffmpeg:tambur#video=h264` in your config but you called the camera `tmbr` so of course that is referencing a stream that doesn't exist

This was actually a copy paste mistake (now commented out). The stream is referenced correctly. Also i can't see any CPU increase on the conversion 

```
#    tambur: 
#      - "rtsp://192.168.2.8:8551/Main"
#      - "ffmpeg:tambur#video=h264"

```
And once again i can connect to the original stream via VLC but not to the one which go2rtc shall provide (ports are exposed in docker)

**Reply by NickM-27** [reply]
if everything is commented out then naturally it won't work. Also, we would only expect the CPU for conversion to be used once a stream actually connects to go2rtc which hasn't happened. More info like full config, logs after running, etc. are needed

**Comment by moskovskiy82** [comment]
> if everything is commented out then naturally it won't work. Also, we would only expect the CPU for conversion to be used once a stream actually connects to go2rtc which hasn't happened. More info like full config, logs after running, etc. are needed

Appreciate the help. Well commented out as per 2 posts above switched to using only camera section where it works. Which means frigate can access the stream from the camera.

Full config below.   uchastok and roads streams are working fine.  Tambur is a semi working solution (go2rtc commented out camera stream only in camera section) where i can get a sub_stream which is a H254. Main stream throws errors as expected.
vaapi acceleration is useless in my case as it's an AMD 8xxx card not supporting HW H256. Ordered an RX550 but that still leaves the problem of solving a  404 error

As per go2rtc - uncomment the cam in question in go2rtc section and go2rtc streams in camera section. Comment out direct path to cam in camera section and get 404 errors like above

```

logger:
  default: error

detectors:
   coral:
     type: edgetpu
     device: pci
mqtt:
  host: 192.168.2.8
  user: mq
  password: mq
ffmpeg:
  input_args:
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-rw_timeout'
    - '5000000'

go2rtc:
  streams:
    uchastok:
      - "http://192.168.2.99/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=root&password=pass"
      - "ffmpeg:uchastok#audio=opus"
    uchastok_sub:
      - "http://192.168.2.99/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=root&password=pass"
    roads:
      - "rtsp://192.168.2.95:554/user=root&password=pass&channel=1&stream=0?.sdp#input=rtsp/udp"
    roads_sub:
      - "rtsp://192.168.2.95:554/user=root&password=pass&channel=1&stream=1?.sdpinput=rtsp/udp"
#    tambur:  
#      - "rtsp://192.168.2.8:8551/Main"
#      - "ffmpeg:tambur#video=h264"
#    tambur_sub:
#      - "rtsp://192.168.2.8:8551/Main/substream"


cameras:
  uchastok:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/uchastok?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/uchastok_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: uchastok

  roads:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/roads?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/roads_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

    live:
      stream_name: roads

  tambur:
    ffmpeg:
      inputs:

#        - path: rtsp://127.0.0.1:8554/tambur?video=copy
#          input_args: preset-rtsp-restream        
#          roles:
#            - record
        - path: rtsp://192.168.2.8:8551/Main/substream
#        - path: rtsp://127.0.0.1:8554/tambur_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record

objects:
  track:
    - person
    - cat
    - car

record:
  enabled: true

snapshots:
  enabled: true
detect:
  enabled: true

birdseye:
  enabled: True
  mode: motion
  restream: False

```
