### DISCUSSION TITLE
only one GPU showing up?

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#6308] [Ask A Question]
I have 2 GPUs (P106 and 1050ti) I have created 2 detectors. 

```
detectors:
  p106:
    type: tensorrt
    device: 1 #P106
  1050ti:
    type: tensorrt
    device: 0 #1050ti
```

![image](https://user-images.githubusercontent.com/152501/235181042-6f1ce4ee-da00-40ce-9fac-50cfb386d928.png)

only one GPU shows up, should there be another one?
