### DISCUSSION TITLE
filtering out a particular false positive under IR conditions.

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#6339] [Ask A Question]
a parked car in the driveway causes a false positive. in the middle of the night, usually under IR conditions. I am using tensorrt, yolov7-tiny-416 model.  I have tried filtering by ratio, but max_ratio of 0.8 sometimes also picks up real people carrying objects or just with a long stride. 

currently my solution is create a zone around the the car, but this hurts the detection when the car ins't on the driveway. Any other ideas on how I can get rid of this false positive? 

![image](https://user-images.githubusercontent.com/152501/235450813-77c0005a-a052-48a2-8dee-ecac6a37a6fe.png)

```
    "after": {
      "id": "1682931867.863728-87h1if",
      "camera": "front",
      "frame_time": 1682931871.372676,
      "snapshot_time": 1682931871.372676,
      "label": "person",
      "sub_label": null,
      "top_score": 0.8174733519554138,
      "false_positive": false,
      "start_time": 1682931867.863728,
      "end_time": null,
      "score": 0.8174733519554138,
      "box": [
        365,
        111,
        479,
        224
      ],
      "area": 12882,
      "ratio": 1.008849557522124,
      "region": [
        211,
        0,
        627,
        416
      ],
      "stationary": false,
      "motionless_count": 14,
      "position_changes": 1,
      "current_zones": [
        "yard"
      ],
      "entered_zones": [
        "yard"
      ],
      "has_clip": true,
      "has_snapshot": true
    },
    "type": "new"
  }
```

```
front: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264     
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://frigate:8554/front # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@ip_camera01:554/cam/realmonitor?channel=1&subtype=1 # <--- the name here must match the name of the camera in restream
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 854  # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 8.0
      stationary:
        max_frames:
          objects:
            person: 300   
 
    motion:
      mask:
        - 854,0,854,48,579,44,582,0 # timestamp
        - 241,0,90,114,32,0 # neighbour's tree
      delta_alpha: 0.4
      improve_contrast: false

    snapshots:
      required_zones:
          - driveway
          - yard
          - gargae
          - road
    objects:
      filters:
        car:
          min_score: 0.7
          threshold: 0.85
        person:
          # min_score: 0.78
          # threshold: 0.88
          mask:
            - 348,0,195,0,0,194,0,368
          # min_ratio: 0.2
          max_ratio: 0.75
        #   min_score: 0.7
        #   threshold: 0.85
    record:
      events:
        objects:
          - car
          - person
          - truck
          - bus
        required_zones:
          - driveway
          - yard
          - gargae
          - road
        retain:
          default: 7
          mode: active_objects


    zones:
      driveway:
        coordinates: 146,480,568,480,625,309,676,129,514,119,314,162,79,425
        objects:
          - car
      yard:
        coordinates: 790,480,854,256,801,214,780,0,478,0,392,104,486,117,433,246,225,249,33,480
        objects:
          - person
          - bicycle
      road:
        coordinates:  0,480,81,354,206,218,322,110,445,0,257,0,96,165,0,267
        objects:
          - car
          - bus
          - truck
      garage:
        coordinates: 661,284,605,480,854,480,854,270,825,117,696,134
        objects:
            - car


    ui:
      order: 2
```
