### DISCUSSION TITLE
Using an engine plan Warning in the logs.

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#6379] [Ask A Question] [answered]
I am seeing this in my Logs.

```2023-05-04 07:10:14.025363448  [2023-05-04 07:10:14] frigate.detectors.plugins.tensorrt WARNING : Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.```

is this because I am using two detectors? 

```
detectors:
  p106:
    type: tensorrt
    device: 1 #P106
  1050ti:
    type: tensorrt
    device: 0 #1050ti
    
model:
  path: /trt-models/yolov7-640.trt # yolov7-tiny-416.trt  
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
```
