### DISCUSSION TITLE
Can't Get Go2rtc to Work After Upgrade to the latest stable release.

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#6389] [Ask A Question] [answered]
I did the upgrade to the latest stable release without go2rtc and it works fine. I do get warnings on RTMP being disabled, which I'll remove. When I added go2rtc for one camera, I got the error:

`2023-05-04 15:55:18.261118361  [2023-05-04 15:55:15] frigate.video                  ERROR   : drive_way: Unable to read frames from ffmpeg process.`

The Go2rtc log looked normal.

The config for go2rtc is:
>go2rtc:
  streams:
    drive_way:
      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
    drive_way_sub:
      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101

The indentation is correct in the config. I can't figure out how to get it to show here. The code option was worse 
The config for the camera is:

>cameras:
  drive_way:
    ffmpeg:
      inputs:
        #- path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
        - path: rtsp://10.0.0.114:554/drive_way_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
         #   - rtmp
        #- path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
        - path: rtsp://10.0.0.114:554/drive_way
          input_args: preset-rtsp-restream
          roles:
            - record

I got the input args line from a blog on the upgrade. It didn't without it as well. The blog used port 8554 in the camera portion of the config. I tried that and it doesn't work either. When I defined port 8554 in the Docker compose file, I got an error that said there was a conflict IIRC. Do I need that port if I'm not using Birdseye? I am using it with Home Assistant.

**Comment by NickM-27** [comment]
You're not following the guide which was clear to use 127.0.0.1:8554 using your external port won't work unless you map the port. 

Also you can format code by using (without the \\)
 ```
\```

\```
```

**Reply by gcortes** [reply]
I read the go2rtc doc and missed the link at the bottom to restream. As mentioned changing it to 8554 doesn't work. Do I need to add it to Docker compose? I found the error when I did have it:

>Error starting userland proxy: listen tcp4 0.0.0.0:8554: bind: address already in use

If it's a requirement, I can look into finding out where it's being used.

**Reply by NickM-27** [reply, marked as answer]
Are you specifically using 127.0.0.1 ? And if so you should show those logs.

**Reply by gcortes** [reply]
You lost me with 127.0.0.1. I know it's localhost but I don't know where it is that I would be specifically using it. This is my Docker compose:
```
services:
  frigate:
    container_name: frigate
    #privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    # image: blakeblackshear/frigate:0.10.1-amd64
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /home/curt/media/frigate:/media/frigate
      - /home/curt/frigate/config/config.yml:/config/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      # - "8554:8554" # Birdseye In v 0.12
    environment:
      FRIGATE_RTSP_PASSWORD: 'xxx'

```
Also:
```
curt@ibex:~$ sudo netstat -pna | grep 8554
tcp6       0      0 :::8554                 :::*                    LISTEN      1833049/go2rtc-1.2.
```
