### DISCUSSION TITLE
Port 8554 already in use

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#6399] [Ask A Question] [answered]
I'm running the latest stable release and appears to be working including the interface to Home Assistant. In order to bring Frigate up in Docker, I had to exclude exposing port 8554 as well as 8555. When I do include them, I get the error:

>Error starting userland proxy: listen tcp4 0.0.0.0:8554: bind: address already in use

I get the same error for 8555. When I run netstat, I get this response:

```
curt@ibex:~$ sudo netstat -pna | grep 8554
tcp6       0      0 :::8554                 :::*                    LISTEN      1833049/go2rtc-1.2.
```
I've never installed go2rtc as I never heard of it prior to the latest release of Frigate. I run a number of other Docker containers on the Ubuntu OS, including Home Assistant. None of them specify the port. Could I have some sort of phantom go2rtc running?

```
services:
  frigate:
    container_name: frigate
    #privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /home/curt/media/frigate:/media/frigate
      - /home/curt/frigate/config/config.yml:/config/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # browser interface
      # - "1935:1935" # RTMP feeds
      # - "8554:8554" # RTSP feeds
      # - "8555:8555/tcp" # WebRTC over tcp
      # - "8555:8555/udp" # WebRTC over udp

    environment:
```
I tried setting privileged to true to no avail.
