### DISCUSSION TITLE
How to keep 24/7 recording for 1 day and events for longer

### DISCUSSION THREAD

**Discussion by marleyjaffe** [blakeblackshear/frigate#6404] [Ask A Question]
Hello, I see in the documentation how to restrict recording down to specific events and time lengths but don't see how to keep all footage for a certain period of time and keep events for a longer time period. Below is my config.

```
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.170:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
      # hwaccel_args: preset-intel-qsv-h264
    detect:
      enabled: true
      # enabled: false
      width: 1920
      height: 1080
    snapshots: # <----- Enable snapshots
      enabled: True
    record: # <----- Enable recording
      enabled: True
      events:
        retain:
          default: 35
```

**Comment by blakeblackshear** [comment]
There are several examples here: https://docs.frigate.video/configuration/record

If you feel like something is unclear on that page, we would appreciate a suggestion for how to improve it.

**Reply by marleyjaffe** [reply]
The config listed here: https://github.com/blakeblackshear/frigate/discussions/6354#discussion-5154157 seems to answer my question. In general I am confused about the nesting of the recording settings. Using the documentation example below, is the 7 days of motion not an event? (I think it is but the config doesn't read that way to me) How can I set a `mode: all` in the below example keeping the other retention periods as is? Also, what is the difference between `days` and `default`? I think an example in the documentation with all 3 modes listed would address my main confusion. Thanks for the great product and quick response!

```
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 2
        car: 7
```

**Reply by marleyjaffe** [reply]
OK, so I've reread the documentation and now I'm questioning my understanding. Under the section [What do the different retain modes mean?](https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean) it reads to me that there essentially 6 modes, `all, motion, active_objects`  for events **and** for _straight_ record, am I understanding that correctly? This doesn't make a ton of sense to me since motion is motion, but it does sorta explains how the YAML config is structured.

**Reply by blakeblackshear** [reply]
The top level setting sets what video is retained regardless of whether or not an event exists. So all motion will be kept including motion not during an event. You can disable detect and you will still have retained video. 

Events in frigate are tracked objects, so motion is not an event. A detected and tracked person would be an event. The config nested under events determines what is kept for recordings during events.

If you want to retain all recordings for 3 days you would set 3 days and all mode at the top level. Beyond those 3 days, you can set it to retain only recordings with motion in them for up to 10 days during events by setting that to 10 days with motion mode.

**Comment by brujoand** [comment]
I came looking for an answer to the same question, wanting to keep recordings for 1 day only, but keep event clips for 7 days. However, now I've got segments of 1 hour recordings from the day I added this configuration. In other words, the 1 days isn't effective, but both the event clips and recordings are gone after 7 days. So the `record.events.retain.default` seems to override the `record.retain.days` 

```
record:
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      mode: active_objects
      default: 7
```

@marleyjaffe did you figure this out?
