### DISCUSSION TITLE
Guide to enable high contrast motion detection automatically via MQTT and Home Assistant automation (night time etc)

### DISCUSSION THREAD

**Discussion by LaurenceGough** [blakeblackshear/frigate#6420] [Show and tell]
Hi all,

I just thought I'd do a very quick guide on how to enable high contrast motion detection automatically via MQTT and Home Assistant automation for night time etc.

My personal reason: I find the high contrast mode helps detect activity at night with the lower camera contrast of the IR light, but with this on way too much stuff was being detected as motion during the day, causing higher CCTV and Coral usage.

You'll need an MQTT server running such as Mosquitto which most have already.

In Home assistant setup an automation as follows:

**Trigger:** 
When the sun sets (sunset) - add optional offset if required here

**Actions:**
MQTT: publish
Topic: frigate/CamNameHereCaseSensitive/improve_contrast/set
Payload (tick): ON

You'll need to setup another automation at sunrise to turn it off. The only difference being the trigger and the payload is OFF instead.

In the Frigate logs around the time of these triggers you should hopefully see:
"frigate.comms.dispatcher       INFO    : Turning off improve contrast for CameraNameHere" or
"frigate.comms.dispatcher       INFO    : Turning on improve contrast for CameraNameHere"

Enjoy, hopefully it helps someone!

**Comment by blacknell** [comment]
Is there anyway frigate could listen on a wildcard for cameras so I can switch improve contrast on them with one message

eg `frigate/all/improve_contrast`

**Reply by brujoand** [reply]
I've come close, but not yet:

```
- alias: Frigate disable high contrast
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - variables:
      camera_names:
      - bassenget
      - hagen
      - homelab
      - stua
      - veien
      - inngang
      - baksiden
  - repeat:
      count: '{{ camera_names | length }}'
      sequence:
      - service: mqtt.publish
        data_template:
          topic: frigate/{{ camera_names[count] }}/improve_contrast/set
          payload: 'OFF'
          qos: 0
          retain: false
  mode: single
```

Just need to figure out how to fetch each camera_names item, because now the resulting output is:

```
Result:
params:
  domain: mqtt
  service: publish
  service_data:
    topic: frigate//improve_contrast/set
    payload: 'OFF'
    qos: 0
    retain: false
  target: {}
running_script: false
```

**Reply by brujoand** [reply]
and I figured it out:

```
alias: Frigate disable high contrast
description: ""
trigger:
  - platform: sun
    event: sunrise
    offset: 0
condition: []
action:
  - variables:
      camera_names:
        - bassenget
        - hagen
        - homelab
        - stua
        - veien
        - inngang
        - baksiden
  - repeat:
      count: "{{ camera_names | length }}"
      sequence:
        - variables:
            camera_name: "{{ camera_names[repeat.index - 1] }}"
        - service: mqtt.publish
          data_template:
            topic: |
              frigate/{{ camera_name }}/improve_contrast/set
            payload: "OFF"
            qos: 0
            retain: false
mode: single
```

Now it works as expected. I just wish I could get the list of camera_names from frigate, but that's for another day.
