### DISCUSSION TITLE
Only detecting "Person"

### DISCUSSION THREAD

**Discussion by jrussell05** [blakeblackshear/frigate#6425] [General]
I've gotten Frigate up and running and loving the integration with Home Assistant.

Perhaps there's something I'm not understanding though.  Per the documentation for version 0.12:

  - With the `motion` option all segments for the duration of the event with motion would be saved. This means any segment where a car drove by in the street, person walked by, lighting changed, etc. would be saved.
  - With the `active_objects` it would only keep segments where the object was active. In this case the only segments that would be saved would be the ones where the car was driving up, you going inside, you coming outside, and the car driving away. Essentially reducing the 4 hours to a minute or two of event footage.

I have a camera in front of the garage that I want to record all motion (cars, people, animals).  However, in my setup, the only events that are recorded are "Person".  If I drive in and out of my garage, no event is recorded.  Here's my setup for my garage camera:

```
cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://XXXXX:{FRIGATE_RTSP_PASSWORD}@garage-camera:554/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://XXXXXX:{FRIGATE_RTSP_PASSWORD}@garage-camera:554/Streaming/Channels/1
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    record:
      enabled: True
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
```
Any help is greatly appreciated!
