### DISCUSSION TITLE
FPS interrogations

### DISCUSSION THREAD

**Discussion by Answer-1** [blakeblackshear/frigate#6447] [General]
I've been using Frigate for like 2 weeks and love it, but got some questions about FPS.

I'm using Wyze-Bridge to get the streams from my Wyze cams, getting them in HD format. Although, in the system page in Frigate, I'm always only seeing like 5 fps for ffmpeg and capture processes, I thought it would be the same as the input fps (which is 15 fps).

I'm also often seeing more than 5 fps for the Detect fps (I've seen 10-11), but my config specifies 5 fps

Wondering if that an expected behavior?

Here's a part of my config (running 5 cams with very similar configs)

```
  ####################
  ### Side Camera ###
  ####################
  side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      cour:
        coordinates: 1655,1080,1735,863,1802,604,1833,145,1562,113,1213,107,919,207,473,266,250,298,0,358,0,1080
    motion:
      mask:
        - 0,379,561,260,568,180,779,160,967,131,1134,132,1223,109,1517,111,1920,165,1920,0,1920,0,0,0
        - 1875,1080,1871,995,1376,1002,1378,1080
    objects:
      track:
        - person
    record:
      enabled: true
      events:
        retain:
          default: 2
          mode: active_objects
```

ffprobe does report 15 fps:

```
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 15/1
```

Thx!!
