### DISCUSSION TITLE
Corrupt Camera Data Using Go2rtc Running on Another Computer

### DISCUSSION THREAD

**Discussion by gcortes** [blakeblackshear/frigate#6466] [Ask A Question]
I was getting a lot of go2rtc errors using the version in the Frigate instance in Docker. I also had problems viewing feeds using the go2rtc interface (port 1984). As a test, I installed go2rtc on another machine (Mac Pro) and pointed the Frigate config to it. I no longer get any go2rtc errors and can display multiple streams on the Mac Pro without issue. Mean while, I'm getting errors in the Frigate log from every 15 minutes to two hours. They're almost all decoding errors. The errors switch from one camera to another every couple of hours.

```
2023-05-11 08:37:13.609627067  [2023-05-11 08:37:13] ffmpeg.living_room.detect      ERROR   : [h264 @ 0x55fd80c25600] error while decoding MB 118 21, bytestream -5
```

When I try to view the cameras in Frigate, the images are corrupted and run about 30 seconds behind. This is one of the camera configs:

```
cameras:
  drive_way:
    ffmpeg:
      inputs:
#        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/drive_way_sub
        - path: rtsp://10.0.0.143:8554/drive_way_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
#        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/drive_way
        - path: rtsp://10.0.0.143:8554/drive_way
          input_args: preset-rtsp-restream
          roles:
            - record
```

CPU utilization is about 85% with eight ffmpeg tasks being the top consumers. I have eight cameras. 

I wasn't having these problems when I went directly to the camera (the first commented out line above). I plan on going back to it, but wanted to bring it up here in case there something else I could try. This is my Docker compose file for Frigate.

```
services:
  frigate:
    container_name: frigate
    # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /home/curt/media/frigate:/media/frigate
      - /home/curt/frigate/config/config.yml:/config/config.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "5000:5000" # browser interface
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    environment:
```
It's one of eight Docker instances running on Ubuntu.

## Update
I switched back to direct connections to the camera and CPU usage dropped to about 14%. There are no errors in the log although it's only been ten minutes. The streams are now clean and not lagging. My guess is that the ffmpeg tasks were overwhelming the Mac Mini  resulting in corrupts streams. I have an open ticket on the go2rtc github site although this seems to be a Frigate issue given that my go2rtc image is running on another computer.
