### DISCUSSION TITLE
How to upgrade to 0.13

### DISCUSSION THREAD

**Discussion by yanivf38** [blakeblackshear/frigate#6467] [Ask A Question]
I saw good fixes that went into 0.13 as well as Go2RTC. is there away to update my software to it. How can I build it myself and install it. I'm running frigate as HA add-on.

Thanks for the help

**Comment by NickM-27** [comment]
As an addon user there's no easy way to run the dev build.

**Reply by yanivf38** [reply]
Is there a way to update just go2rtc build?

**Reply by blakeblackshear** [reply]
https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Reply by yanivf38** [reply]
Thank you @blakeblackshear easier than I thought. I'll give it a try

**Reply by joelegg** [reply]
How can you run 0.13 in Docker ( non-addon user?) I'm really keen to try the PTZ features. As we have some rampid crime happening in our area right now. My PTZ is not very smart and just looks at lights. Lol

**Reply by NickM-27** [reply]
Just use one of the dev images in the sidebar on the main project page

**Comment by claudy-us** [comment]
I've been using version 12.1 on docker-compose in an Ubuntu computer with google coral, it works great.
I got this LAView camera that only has ONVIF, ant this is a feature supported by the new version 13 of frigate.
I tried to update it to version 13 (beta) but got stuck on a error about moving the old db to a new location.
But I don't know how to mount the folder inside docker-compose as this was the solution I found in a post for the problem.
Can anyone help me mounting this config folder and setting up the new version?
[docker-compose.yml](https://github.com/blakeblackshear/frigate/files/13848593/docker-compose.txt)
[frigate.yml](https://github.com/blakeblackshear/frigate/files/13848594/frigate.txt)

**Reply by NickM-27** [reply]
`- ./config/frigate.yml:/config/config.yml` becomes `- ./config//config/` except you are also going to need to rename `frigate.yml` to `config.yml`

**Reply by claudy-us** [reply]
First off thanks to @NickM-27 for your time.

On version 12, I was able to move the footage folder to an external drive by creating a link to it using the following command:
```
sudo ln -sT /media/USER/seagate5TB/footage /mnt/footage2
```
then:
```
sudo docker-compose down
sudo docker-compose up -d
```
my docker compose file is on:
- ~/docker-compose/frigate/docker-compose.yml
my config files is on:
- ~/docker-compose/frigate/config/frigate.yml

I am not sure if I understood that right, but I made the change on my docker-compose.yml file:
from this:
``` - ./config/frigate.yml:/config/config.yml```
to:
``` - ./config//config/```
That didn't work tho.
I tried changing it to:
``` - ./config//config/:/config/config.yml```
and it didn't work neigher.

Any other suggestion?

**Reply by PatSloan** [reply]
you don't need the file name

`- /home/pat/docker/frigate_beta/config:/config`

**Reply by claudy-us** [reply]
Well, I was about to post a message saying it's still not working when I made a last minute change and now it's finally working, Thanks @NickM-27 for the help again.
This is the final docker-compose.yml working file in case someone needs it:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta3
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0 
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/USER/docker-compose/frigate/config:/config/
      - /mnt/footage2:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "PASSWORD"
```
