### DISCUSSION TITLE
Is it possible to take multiple snapshots per event?

### DISCUSSION THREAD

**Discussion by jonadis** [blakeblackshear/frigate#6501] [Ask A Question]
I've got a camera pointed at the road and I'd like to grab the side view of every vehicle that drives by.  This is working pretty well so far but the best side view of a given vehicle may be 0.5 seconds after the initial detection because of the angle and there's some trees/etc that block part of the the view.
Plan A is to tweak the detection with masks/etc so that I can try to get the one and only snapshot right at the right time, but I'm only having limited success so far with that.
Plan B would be to simply take multiple snapshots as the vehicles go by, hoping that at least one of them is good.  Is there any supported way to do that?  I didn't see what seemed like the right option in the config, but maybe someone else knows and can point it out.

My config at the moment before any masks/etc is simply:
```
snapshots:
  enabled: True
  bounding_box: True
...
cameras:
  ...
  road:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/road
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: False
```
