### DISCUSSION TITLE
Reolink PoE Doorbell - Unable to get any stream at all - Total Newbie

### DISCUSSION THREAD

**Discussion by Dashrendar2507** [blakeblackshear/frigate#6540] [Ask A Question] [answered]
Hi everyone! First time using Frigate and have spent the last 3 days trying to diagnose my problem. 

Setup info:
- Frigate Docker running on Synology NAS
- Reolink PoE doorbell
- HassOS

I am starting the Frigate container and I can access the webui, but the streams never worked no matter what the config.yml. I'm now down to what I think is the most basic config for troubleshooting but still can't get it to work.

The Frigate logs say that:
ERROR   : doorbell: Unable to read frames from ffmpeg process.
ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...

And Go2RTC says this:
can't get track url=rtsp://admin:XXXXX@192.168.2.34:554/h264Preview_01_main
can't get track 14:44:59.983 WRN [rtsp] error="codecs not match: H264,AAC" stream=doorbell
ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp 192.168.2.34:554: connect: connection refused" url=rtsp://admin:XXXXX@192.168.2.34:554/h264Preview_01_main

Not sure which is the cause and which is the symptom.

I'm attaching the config.yml, let me know if I can get you anything else. Thank you!

[config.txt](https://github.com/blakeblackshear/frigate/files/11518087/config.txt)

**Comment by NickM-27** [comment, marked as answer]
Connection refused means it doesn't like the user / password or the rtsp stream has not been enabled. Also worth noting that we recomend using the http-flv stream with reolink not rtsp

**Reply by Dashrendar2507** [reply]
Thank you for your reply. The user and password combination is indeed correct. RTSP is also enabled in the doorbell's webui, on port 554.

In fact. the RTSP URL was copied from a working RTSPtoWebRTC config on HA.

I had tried the flv stream earlier, but I'm assuming there was an issue somewhere else in the config at the time because I am now (partially) able to see the stream! Thank you for that. MSE and jsmpeg work, but WebRTC does not. I'll try to troubleshoot that now and see if I can figure it out.

FYI, here is what I see in the browser's console: "received a broken close frame containing a reserved status code."

Thanks again!

**Reply by raenji-sk** [reply]
@Dashrendar2507 Did you manage to find a solution? I am having a similar problem I belive. The RTPS strem is refusing connection. Can not get it to play in VLC or Home Assistant or Scrypted. Connecting via Reolink app works just fine. The RTPS stream works sometimes for a short while and then it stops. Most of the time it does not and only shows a snapshot but the video does not play. And yes it is enabled in Reolink network settings.

**Reply by NickM-27** [reply]
@raenji-sk have you updated the firmware?

**Reply by raenji-sk** [reply]
Yes running the latest firmware.

Just going through some router logs and it seems the doorbell is dropping connection now and then. It's the Wi-Fi version. Need to investigate further.

Both router and scrypted camera logs show the disconnects happening... 

The signal is not best but also not the worst. Some devices have weaker signal and remain connected. Not sure what's causing this.

**Reply by Dashrendar2507** [reply]
> @Dashrendar2507 Did you manage to find a solution? I am having a similar problem I belive. The RTPS strem is refusing connection. Can not get it to play in VLC or Home Assistant or Scrypted. Connecting via Reolink app works just fine. The RTPS stream works sometimes for a short while and then it stops. Most of the time it does not and only shows a snapshot but the video does not play. And yes it is enabled in Reolink network settings.

I was able to get it working for a bit. I'm not really sure what worked, but I think it's mostly because I had specified different external ports in Docker and thus had to change my URLs.

Also, WebRTC **requires** OPUS audio. I had to add this below the path to my doorbell, in the Go2RTC section:

`- "ffmpeg:doorbell#audio=opus"`

To transcode the audio to opus instead of the AAC provided by Reolink. Just change "doorbell" for the name of your camera.

It worked great for a bit, then the WebRTC stream started getting extremely choppy the next day and the logs mentioned ffmpeg kept crashing. I couldn't get it working well again so I'm back to MSE. The only thing I'm losing is 2-way audio, otherwise I'm happy with the delay, which is almost non-existent.

As for the connection dropping, I had the same thing happening with the wired PoE doorbell.

**Reply by NickM-27** [reply]
WebRTC requires OPUS, PCMA, or PCMU to be clear

**Reply by raenji-sk** [reply]
I wrote to Reolink support today, sent them logs and screenshots. Will see what they come up with. I changed some WiFi settings and it works most of the time. But still drops connection from time to time. And when I try to open the stream in VLC it drops dead instantly... 
And thanks for the audio info. 
I can only get audio from camera if I use the the stream from go2rtc webUI. It works without any transcoding settings from my side. But once I play it via home asisstant there is no audio in the same stream. In both cases it is a restream from Scrypted plugin which uses ONVIF for the doorbell camera connection.

**Reply by raenji-sk** [reply]
Just an update. Reolink sent me an updated firmware for the WiFi Doorbell. All issues have been resolved I belive. It's been up and running without any issues now for over 3 hours now and it also feels more responsive overall.

**Reply by slepiavka** [reply]
Nice. Mind sharing which firmware version/name?

**Reply by raenji-sk** [reply]
Sure @slepiavka firmware name is "DB_566128M5MP_W.2153_23051501.Reolink-Video-Doorbell-WiFi.OV05A10.5MP.WIFI8812.REOLINK"
Here's a link to dropbox download [WiFi Doorbell Firmware](https://www.dropbox.com/s/3v9w2xyyk8rc0ba/DB_566128M5MP_W.2153_23051501.Reolink-Video-Doorbell-WiFi.OV05A10.5MP.WIFI8812.REOLINK.pak?dl=0)

Not sure if it also works for PoE version. But hopefully they will do an official release soon.

**Reply by jhonathas** [reply]
Work for me too! Thanks

**Comment by cloudbr34k84** [comment]
totally newbie as well, trying to understand how everyone's config files look for reolink cameras. It would be good to see this 

The doorbell was working fine for ages, no idea whats changed to be honest. i have the same issue with my reolink doorbell. connect: connection refused". I know the credentials are correct
```
2023-08-02 19:42:37.578899095  [2023-08-02 19:42:37] ffmpeg.front_video_doorbell_frigate.detect ERROR   : rtsp://*:*@192.168.68.72:554/h264Preview_01_sub: Connection refused
2023-08-02 19:42:37.602717242  [2023-08-02 19:42:37] watchdog.front_video_doorbell_frigate ERROR   : No new recording segments were created for front_video_doorbell_frigate in the last 120s. restarting the ffmpeg record process...
2023-08-02 19:42:37.602730259  [2023-08-02 19:42:37] watchdog.front_video_doorbell_frigate INFO    : Terminating the existing ffmpeg process...
2023-08-02 19:42:37.602732675  [2023-08-02 19:42:37] watchdog.front_video_doorbell_frigate INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-02 19:42:37.614248922  [2023-08-02 19:42:37] frigate.video                  ERROR   : front_video_doorbell_frigate: Unable to read frames from ffmpeg process.
2023-08-02 19:42:37.615022876  [2023-08-02 19:42:37] frigate.video                  ERROR   : front_video_doorbell_frigate: ffmpeg process is not running. exiting capture thread...
2023-08-02 19:42:47.618226930  [2023-08-02 19:42:47] watchdog.front_video_doorbell_frigate ERROR   : Ffmpeg process crashed unexpectedly for front_video_doorbell_frigate.
2023-08-02 19:42:47.618234326  [2023-08-02 19:42:47] watchdog.front_video_doorbell_frigate ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-08-02 19:42:47.618237238  [2023-08-02 19:42:47] ffmpeg.front_video_doorbell_frigate.detect ERROR   : [tcp @ 0x55fdf609a2c0] Connection to tcp://192.168.68.72:554?timeout=5000000 failed: Connection refused
2023-08-02 19:42:47.618239719  [2023-08-02 19:42:47] ffmpeg.front_video_doorbell_frigate.detect ERROR   : rtsp://*:*@192.168.68.72:554/h264Preview_01_sub: Connection refused
2023-08-02 19:42:47.642498440  [2023-08-02 19:42:47] watchdog.front_video_doorbell_frigate ERROR   : No new recording segments were created for front_video_doorbell_frigate in the last 120s. restarting the ffmpeg record process...
2023-08-02 19:42:47.642505761  [2023-08-02 19:42:47] watchdog.front_video_doorbell_frigate INFO    : Terminating the existing ffmpeg process...
2023-08-02 19:42:47.642508147  [2023-08-02 19:42:47] watchdog.front_video_doorbell_frigate INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-02 19:42:47.688009431  [2023-08-02 19:42:47] frigate.video                  ERROR   : front_video_doorbell_frigate: Unable to read frames from ffmpeg process.
2023-08-02 19:42:47.688287654  [2023-08-02 19:42:47] frigate.video                  ERROR   : front_video_doorbell_frigate: ffmpeg process is not running. exiting capture thread...
```

Frigate Docker running on Synology NAS
Reolink wifi doorbell
HassOS
Below is my config
```
mqtt:
  host: xxx.xxx.xx.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: xxxxxxx
  stats_interval: 60

# birdseye:
#   enabled: True
#   mode: continuous
#   restream: False

rtmp:
  enabled: false

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

go2rtc:
  streams:
    rtsp_cam:
      front_video_doorbell_frigate:
        - ffmpeg:http://xxx.xxx.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=PASSWORD#audio=opus#audio=copy
        - ffmpeg:front_video_doorbell_frigate
      frontyard_camera_frigate:
        - ffmpeg:http://xxx.xxx.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=PASSWORD#audio=opus#audio=copy
        - ffmpeg:frontyard_camera_frigate
      driveway_camera_frigate:
        - ffmpeg:http://xxx.xxx.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=PASSWORD#audio=opus#audio=copy
        - ffmpeg:driveway_camera_frigate
      backyard_camera_frigate:
        - ffmpeg:http://xxx.xxx.xx.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=PASSWORD#audio=opus#audio=copy
        - ffmpeg:backyard_camera_frigate

######## Camera Configuration ########
cameras:

######## Video Doorbell ########    
  front_video_doorbell_frigate:
    ffmpeg:
      hwaccel_args: preset-vaapi  
      inputs:
        - path: rtsp://username:PASSWORD@xxx.xxx.xx.xx:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://username:PASSWORD@xxx.xxx.xx.xx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
    record:
      enabled: True
      events:
        required_zones:
          - frigate_zone_front_video_doorbell_front_patio_area
          - frigate_zone_front_video_doorbell_front_yard_steps
        
    detect:
      enabled: True
      fps: 5
      width: 2560 #max 2560
      height: 1920 #max 1920

    snapshots:
      enabled: true
      retain:
        default: 1
      required_zones:
        - frigate_zone_front_video_doorbell_front_patio_area
        - frigate_zone_front_video_doorbell_front_yard_steps
    objects:
      track:
        - person
        - car
        - cat
        - dog
    zones:
      frigate_zone_front_video_doorbell_front_patio_area:
        coordinates: 835,1804,872,1920,2354,1920,2466,1696,1962,1519,1840,1625,1701,1691,1580,1599,1032,1701,1054,1802
        objects:
          - person
          - cat
          - dog
      frigate_zone_front_video_doorbell_front_yard_steps:
        coordinates: 1086,1695,1284,1677,1539,1612,1284,1401,991,1414
        objects:
          - person
          - cat
          - dog
    
    motion:
      mask:
        - 1259,1257,1702,1217,1690,1103,748,1125,755,1274
```
