### DISCUSSION TITLE
What's the right config to keep only database entries and not recordings?

### DISCUSSION THREAD

**Discussion by glossyio** [blakeblackshear/frigate#6588] [Ask A Question] [answered]
What's the right config file entry for this?  I would like to keep only the database event entries (using default Sqlite on a Docker container) but all the recording to expire.  I would like to keep the database entries forever (or let's say 30 days, and I would do periodic backups) to use for analytics purposes (historical bike and car counts) but let the recordings expire every 5 days.

Would it look like this?  Is this 30 days of database event entries and 5 days of event recording/clips?

```
record:
  enabled: True
  retain:
    days: 30
    mode: active_objects
  events:
      retain:
        default: 5
        mode: active_objects
```

I am trying this right now on my install, but I wanted to confirm and have a record since I couldn't find anything like this on the web or in discussions.

**Comment by NickM-27** [comment, marked as answer]
What you're asking for doesn't exist. The DB is used to keep track of the file so the recordings segments will last as long as the recordings DB entry. 

You could setup snapshots to be retained longer than events but the `record` config controls when recordings segments are retained

**Reply by glossyio** [reply]
Understood. I'll probably end up pulling over any `event.id` that doesn't exist into an archive DB with the same schema on a regular schedule (maybe every 14 days to cover myself).

Snapshots are good idea, since they take up _much less space_ I could set a very long retention time for them.  Does it keep the same DB entries in the `event` Table and must add a `snapshots` table?

So, I would change it to be like this, to keep 30 days of history in the `event` table in the DB?

```
record:
  enabled: False
snapshots:
  enabled: True
  retain:
    default: 30
```

**Reply by NickM-27** [reply]
There is no snapshots table, the events table keeps track of everything related to events.

**Comment by glossyio** [comment]
Just for my learning.  What does my OP config file do then?  Does it effectively keep only 5 days of recordings and 5 days of events in the DB?

**Reply by NickM-27** [reply]
No. It keeps 30 days of 24/7 recording segments and keeps 5 days of recordings segments that are relevant for events. Which really doesn't make sense since you would usually keep event recordings longer than 24/7 recordings

**Reply by glossyio** [reply]
Well, that's pretty much the opposite of what I want!  Thank you.

**Comment by glossyio** [comment]
I may have prematurely closed this.  With the following config, I am still getting only 3 rolling days of history in the `events` table.  I thought the below config would give me 60 days worth of records (because of snapshots) in the db, but only 3 rolling days worth of recordings. Do snapshots even get recorded in the `events` table?  The db file is at  46 MiB in size, if that matters.

```
record:
  enabled: True
  retain:
    days: 0
  events:
      retain:
        default: 3
        mode: active_objects

snapshots:
  enabled: True
  retain:
    default: 60
```

At the end of the day, I would like to know:  How do I get 60 days of `events` records in the database with the least amount of disk space used?

_edited grammar, clarified request_

**Reply by glossyio** [reply]
OK.  Answered my own Q here after looking into the [cleanup code](https://github.com/blakeblackshear/frigate/blob/1e17dbaa91d1987bbfb8bf28e7fade90b7e6b68e/frigate/events/cleanup.py#L172).  It _does_ check for both "clips"/recordings and "snapshots" before cleaning the database.  My problem was that I enabled snapshots only 2 day ago... so it was still cleaning out the old `event` records that had only "clips" associated with them.  I should be getting 60 days of retention because of snapshots once I hit the day I started capturing them. :)

Side note: the snapshots are also pretty large files - the "*-clean.png" file is over 8 MiB for myself.  So, they are often larger than the short recordings. So, I am going to set clean copy false

```
snapshots:
  enabled: True
  clean_copy: False
  retain:
    default: 60
```
