### DISCUSSION TITLE
Can someone please have a look att my frigate.yml code?

### DISCUSSION THREAD

**Discussion by digitalit** [blakeblackshear/frigate#6592] [Ask A Question] [answered]
I run HAOS in an Intel NUC with the Frigate add on and it works great but i read so many different settings so i would be super happy if any one could maybe correct me in some places if i can make it even better/ cleaner  

```yaml 
mqtt:
  host: xxx.xxx.xxx.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxxxxx
  password: "xxxxxxxxx"
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
rtmp:
  enabled: False
birdseye:
  enabled: True
detect:
  width: 704
  height: 576
  fps: 5
objects:
  track:
    - person
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
cameras:
  front:
    record:
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.4.101:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:xxx@192.168.4.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    motion:
      mask:
        - 0,0,0,576,50,576,426,161,453,43,529,45,625,0
  parking:
    record:
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.4.102:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:xxx@192.168.4.102:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    motion:
      mask:
        - 704,0,704,576,50,232,0,263,0,0
  back:
    record:
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.4.103:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:xxx@192.168.4.103:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    motion:
      mask:
        - 658,218,704,0,0,0,0,176
        - 0,439,0,183,181,180
  vrum:
    record:
      enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.4.104:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://xxx:xxx@192.168.4.104:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
logger:
  default: info
```

**Comment by blakeblackshear** [comment]
Looks good to me. You have a little bit of redundancy. Settings set globally don't need to be repeated under the camera unless they have different values. Also, some of your settings are the default values, so they could be removed too.

Unless you have problems, I think you are good.

**Reply by digitalit** [reply]
Thank you so much for answering @blakeblackshear 

I guess you are super busy but what i can se i could probably remove:

 ```
    record:
      enabled: True
 ``` 
in every camera config?

Could you also please tell me what default code i can remove?

Again, thank you so much

**Reply by NickM-27** [reply, marked as answer]
yes you can remove that. 

You can also remove

```
rtmp:
  enabled: False
birdseye:
  enabled: True
```

as these are defaults for example
