### DISCUSSION TITLE
HA Snapshot camera entity and multiple zones help required

### DISCUSSION THREAD

**Discussion by picotrain77** [blakeblackshear/frigate#6596] [Ask A Question]
Hi All
Stupid question but cant work it out. I had 1 of my cam's set up with track person and the same required zone for recording, mqtt, and snapshots. This has always worked perfectly and within home assistant I see a camera.garage_cam_person entity and this has always shown the latest snapshot - so far so good.

Today I decided to add a 2nd zone and and have added the 2ns zone to the frigate.yaml and listed in it required zones for recording, mqtt, and snapshots. I can see in frigate and media folder etc that movement of people within either zone causes frigate to snapshot and record with the correct zone labels - so all good.

However the bit I cant get my head round is if there is a snapshot created in the first and original long standing zone the HA camera.garage_cam_person entity is updated to show this latest snapshot - however if a snapshot is created in the new zone added today then the HA camera entity is not updated and continues to show the old snapshot.

So what have I missed, am I being stupid here?

PS Happy to post up some config if required but can help thinking I am missing something stupid?

**Comment by NickM-27** [comment]
Which HA camera entity is not updated?

**Reply by picotrain77** [reply]
Hi Nick. The snapshot camera entity. It only ever updates when a snapshot is created for the original zone, frigate can create multiple snapshots for the new zone but the camera entity only updates in HA if I move around in the original zone and cant work out why!

**Reply by NickM-27** [reply]
That is still not helpful as there are many "snapshot" entities. Do you mean `camera.garage_cam_person` ? If so then posting your config would be helpful but you most likely have a typo somewhere

**Reply by picotrain77** [reply]
```
  garage_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://127.0.0.1:8554/garage_cam
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      width: 960
      height: 576
      fps: 6
      enabled: true
      max_disappeared: 25
      stationary:
        max_frames:
          default: 3000

    motion:
      mask:
        - 0,551,278,551,281,517,0,518
          
    objects:
      track:
        - person
      filters:
        person:
          min_area: 7000
          max_area: 145000

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      required_zones:
        - home_garage_person_zone
        - home_garage_person_2_zone

    record:
      enabled: true
      retain:
        days: 0
      events: 
        required_zones:
          - home_garage_person_zone
          - home_garage_person_2_zone

        pre_capture: 5
        post_capture: 5
        retain:
          default: 60

    snapshots:
      required_zones:
        - home_garage_person_zone
        - home_garage_person_2_zone
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 60
    
    best_image_timeout: 30

    zones:
      home_garage_person_zone:
        coordinates: 0,576,704,576,704,576,522,325,372,171,270,129,0,132
      home_garage_person_2_zone:
        coordinates: 713,576,880,576,960,461,960,332,726,172,397,153

    live:
      height: 576
      quality: 12
```
