### DISCUSSION TITLE
How to retain events/snapshots "forever"

### DISCUSSION THREAD

**Discussion by JanickGers85** [blakeblackshear/frigate#6616] [Ask A Question]
Hi!
I set up my camera as if follows, to gain:
- 60 days of continuos recording
- keeping forever video related to events

But seems that old videos before the continuous recording date are not playble, while snapshots are retained.
What's wrong? It is not possibile?
I have plenty of space on my HDD.

```yaml
  garage:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: '***'
          roles:
            - detect
            - record
    snapshots:
      required_zones:
        - "garage_stanza"
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 36500
        mode: active_objects
    detect:
      height: 720
      width: 1280
      fps: 15
    best_image_timeout: 5
    mqtt:
      enabled: true
      crop: true
      height: 500
    objects:
      track:
        - person
    record:
      enabled: true
      retain:
        days: 60
        mode: all
      events:
        required_zones:
          - "garage_stanza"
        retain:
          default: 36500
          mode: active_objects
    zones:
      garage_stanza:
        coordinates: ***
      lavanderia:
        coordinates: ***
```
This is the error I get when trying to play a video

![20230526_025247](https://github.com/blakeblackshear/frigate/assets/21289907/46db7598-5edd-4281-9d2f-b735fb736d8b)

The video is from 10 of March, my latest stored video is of 11 of April.
