### DISCUSSION TITLE
CPU usage seem really high

### DISCUSSION THREAD

**Discussion by Cold-Lemonade** [blakeblackshear/frigate#6626] [Ask A Question]
I have a Minisforum GK41 with 8 Dahua/Dahua-clone cameras running and streams are encoded using h.264. Frigate is using the substream (generally 704x480 resolution) for detection. I have two usb corals and am using ```hwaccel_args: preset-vaapi```. Should I be getting high CPU usage like the ones in the screenshots below?

It wasn't this high before. But I recently added filters to reduce the number of false positives. Could this be contributing to the high CPU usage?

![CPU-usage](https://github.com/blakeblackshear/frigate/assets/5651490/4a7aa558-a710-4f96-a151-a7bea73fe7d0)

**Comment by NickM-27** [comment]
What does your detector config look like? Filters shouldn't increase cpu usage.

**Reply by Cold-Lemonade** [reply]
Here it is:

```
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
```
