### DISCUSSION TITLE
Unable to use a newer version of go2rtc

### DISCUSSION THREAD

**Discussion by Cytomax55** [blakeblackshear/frigate#6646] [General]
I am running frigate docker container

I went to 
https://docs.frigate.video/configuration/advanced#custom-go2rtc-version
to find out the steps needed to upgrade go2rtc

I then got go2rtc version 1.5
https://github.com/AlexxIT/go2rtc/releases/download/v1.5.0/go2rtc_linux_amd64

renamed it to 
go2rtc

placed it in the config folder of frigate
/frigate/config

chmod +x go2rtc

ls -al  shows

5241 -rwxr-xr-x 1 user root 5356360 May 29 23:11 go2rtc

Restarted frigate and i keep seeing 1.2 being loaded instead of 1.5 
What am i doing wrong?

Thanks in Advance

**Comment by blakeblackshear** [comment]
Is this file mounted in the container? What does your docker compose look like?

**Comment by Cytomax55** [comment]
Thank you for the reply

The docker container frigate is running perfectly fine

I am trying to get a reolink door bell to work with 2 way audio that was mentioned in version 1.5 of go2rtc

I have placed go2rtc inside of 

/media/user/frigate/config/

which is right next to the config.yml file

++++++++++++++++++++++++++++++++++++++++++++++++

I just noticed when i log into the frigate container i dont see the go2rtc file though

root@470008882a83:/config# ls -al
total 13
drwxr-xr-x 2 root root  4096 May 29 23:49 .
drwxr-xr-x 1 root root  4096 May 29 23:49 ..
-rw-r--r-- 1 1000 root 11323 May 29 23:25 config.yml


I am going to to try to add it to the docker compose file like this

/media/user/frigate/config/go2rtc:/config/go2rtc

+++++++++++++++++++++++++++++++++++++++++++++

```
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "80mb" # update for your cameras based on calculation above
    devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/user/frigate/config/config.yml:/config/config.yml
      - /media/user/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

**Reply by NickM-27** [reply]
Your docker compose config only mounts the config file not the config directory so the go2rtc binary is not being passed into the container.

**Comment by Cytomax55** [comment]
@NickM-27 
Thank you
i just tried adding to my docker compose file

- /media/user/frigate/config/go2rtc:/config/go2rtc

and it works now!

I see the option at the bottom of 
firgatedomain.com/live/webrtc

WebRTC Magic
video+audio+microphone = two way audio from camera

I did notice the mic only works with

FrontDoorBell_go2rtc:
      - rtsp://admin:password@192.168.0.52:554/h264Preview_01_sub
      - ffmpeg:FrontDoorBell_go2rtc#audio=opus


It does not work with 

FrontDoorBell:
      - http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
      - ffmpeg:FrontDoorBell#audio=opus


I did notice that is much more clear video

- http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password

than

- rtsp://admin:password@192.168.0.52:554/h264Preview_01_sub


Is 
 http://192.168.0.52/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
The clear stream

and

the 
 rtsp://admin:password@192.168.0.52:554/h264Preview_01_sub
fluent stream?


thanks in Advance

**Reply by NickM-27** [reply]
Right, only rtsp supports backchannel audio. 

And you can use rtsp://admin:password@192.168.0.52:554/h264Preview_01_main for the main stream

**Reply by Cytomax55** [reply]
Thank you!

**Reply by cigas4** [reply]
I can't get this to work.. I am using Reolink Doorbell camera. If I open two way audio link (WebRTC Magic: video+audio+microphone = two way audio from camera) on a browser I can see image and have sound but can't speak..

My frigate is also running on docker container. 
Thanks to this thread I have managed to update go2rtc to 1.6.2 version from standard 1.2. 
On Frigate go2rtc log there are no error messages.

```
2023-08-15 15:16:11.440903055  [INFO] Preparing go2rtc config...
2023-08-15 15:16:11.628124643  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-08-15 15:16:11.656502366  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-08-15 15:16:11.656507154  [INFO] Starting go2rtc...
2023-08-15 15:16:11.728164478  15:16:11.728 INF go2rtc version 1.6.2 linux/amd64
2023-08-15 15:16:11.728475393  15:16:11.728 INF [api] listen addr=0.0.0.0:1984
2023-08-15 15:16:11.728727939  15:16:11.728 INF [rtsp] listen addr=0.0.0.0:8554
2023-08-15 15:16:11.728870689  15:16:11.728 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-08-15 15:16:11.729304144  15:16:11.729 INF [srtp] listen addr=0.0.0.0:8443
2023-08-15 15:16:21.443743562  [INFO] Starting go2rtc healthcheck service...
```

My frigate config for go2rtc:

```
go2rtc:
  streams:
    doorbell:
      - rtsp://admin:pass@192.168.1.88:554/h264Preview_01_sub
      - ffmpeg:doorbell#audio=opus
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  webrtc:
    candidates:
      - 192.168.1.13:8555
      - stun:8555

cameras:
  doorbell:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtmp://192.168.1.88/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=pass
          roles:
            - detect
            - record
    live:
      stream_name: doorbell
    detect:
      enabled: True
      width: 2560
      height: 1920
      fps: 15
      max_disappeared: 25
```

My link looks like this: 

`http://192.168.1.13:5000/live/webrtc/webrtc.html?src=doorbell&media=video+audio+microphone
`

I have tried opening this link with Safari and Chrome on mac. I only get image and audio, but no voice to the camera..
Could it be some microphone permission issue or something else?
You don't need to press anything to activate microphone on this stream right? 
Any ideas?

**Reply by NickM-27** [reply]
only rtsp supports two way talk, not http-flv

**Reply by cigas4** [reply]
Ok so I have updated my Frigate config to this:

```
go2rtc:
  streams:
    doorbell_go2rtc:
      - rtsp://admin:pass@192.168.1.88:554/h264Preview_01_sub
      - "ffmpeg:doorbell_go2rtc#audio=opus"
  webrtc:
    candidates:
      - 192.168.1.13:8555
      - stun:8555

cameras:
  doorbell_go2rtc:
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_go2rtc
          roles:
            - record
    snapshots:
      enabled: True
      crop: True
      timestamp: False
      bounding_box: True
      retain:
        default: 100
    record:
      enabled: True
      retain:
        days: 15
        mode: motion
    live:
      stream_name: doorbell_go2rtc
```

But still no luck.. 
I am testing using web url and also integrated to Home Assistant Frigate card. In both cases I have image and audio, but no mic.

Any ideas?

**Reply by NickM-27** [reply]
Are you using http or https to access the dashboard?

**Reply by cigas4** [reply]
It is:

`http://192.168.1.13:5000/live/webrtc/`

Same as Frigate itself.

**Reply by NickM-27** [reply]
Two way talk requires https

**Reply by cigas4** [reply]
Ahh... I only use local connection between Frigate and doorbell camera, why would I need https?

**Reply by NickM-27** [reply]
You need https when you are viewing the dashboard, web browsers do not allow the use of a microphone over an unencrypted connection. This is covered in the go2rtc docs

**Reply by cigas4** [reply]
Ok that's clear. 
I have set up  SSL on my HomeAssistant. I am using custom Frigate card in HA to get go2rtc stream from Frigate container. 
Now once I press microphone icon on Frigate card in HA webpage on Safari I got pop-up asking to allow microphone usage - that's seems promising!
Hmmm.. once I press mic icon in Frigate card, after few seconds my camera image starts flickering and soon whole Frigate freezes...
From Frigate Logs:

```
2023-08-15 19:53:05.851014123  [2023-08-15 19:53:05] watchdog.doorbell_go2rtc       INFO    : doorbell_go2rtc exceeded fps limit. Exiting ffmpeg...
2023-08-15 19:53:05.851244314  [2023-08-15 19:53:05] watchdog.doorbell_go2rtc       INFO    : Waiting for ffmpeg to exit gracefully...
```

**Reply by NickM-27** [reply]
I would recommend following the frigate recommended setup https://docs.frigate.video/configuration/camera_specific#reolink-cameras

and then adding the rtsp_url after the others in the go2rtc config, that way go2rtc will only use rtsp for backchannel audio when it is called upon

**Comment by gdumonteil** [comment]
Hello guys, 

I'm trying to accomplish the same as @Cytomax55. I think I have almost the same setup but Frigate does not pick the go2rtc in the config folder. 

I think it's because the go2rtc binary does not have the proper execution rights. 

Frigate runs in a docker container on a LXC ubuntu container, on this LXC I have mounted my HA config folder. 
I use this folder in my docker compose. But even if the go2rtc file as the proper right in HA ssh terminal, in the frigate container it does not. 

I can certainly, push go2rtc on the LXC container to overcome this issue, but I would like to know if you have an idea. 

Thanks

**Reply by NickM-27** [reply]
What does your compose look like?

**Reply by gdumonteil** [reply]
Here is my compose (same as @Cytomax55):

```
version: "3.9"
services:
  frigate:
    container_name: frigate-0.12
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: '128mb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/ha_config/frigate/config.yml:/config/config.yml
      - /media/ha_config/frigate/go2rtc:/config/go2rtc
      - /media/ha_media/frigate:/media/frigate
      - /root/frigate/db:/db:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "1984:1984" # Go2rtc
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "camerapass"
```
HA VM
![image](https://github.com/blakeblackshear/frigate/assets/10962129/002620e1-22e9-4754-93af-d05b7e41af20)

Frigate Container
![image](https://github.com/blakeblackshear/frigate/assets/10962129/786d3d06-8d1e-4970-99cb-4a4bd7162c5d)

Ok interesting, the mounting point on the LXC container doesn't have the proper rights:
![image](https://github.com/blakeblackshear/frigate/assets/10962129/9a29862b-c72b-4658-8294-a60b94470e3f)
It might be due to an improper mounting command!! I going to investigate my fstab

Edit: that was it!! For whatever raison, my mounting command was changing the file rights!! 
Now frigate use the proper go2rtc version.
