### DISCUSSION TITLE
No frames have been received when using coral on proxmox LXC

### DISCUSSION THREAD

**Discussion by TheZoker** [blakeblackshear/frigate#6651] [Ask A Question] [answered]
Hi there,

I'm running frigate within a alpine based proxmox LXC container using docker. 
This is my config for the container:
```conf
arch: amd64
cores: 2
features: keyctl=1,nesting=1
hostname: Frigate
memory: 1024
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.3.1,hwaddr=B2:48:07:6D:F4:CC,ip=192.168.3.170/32,type=veth
ostype: alpine
protection: 1
rootfs: local-lvm:vm-170-disk-0,size=8G
swap: 512
unprivileged: 1
usb0: host=1a6e:089a,usb3=1
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/bus/usb/002 dev/bus/usb/002 none bind,optional,create=dir
```

My docker compose file:
```yml
version: '3.8'
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: Frigate
    restart: always
    ports:
      - 80:5000
    volumes:
      - ~/files/frigate/config.yml:/config/config.yml
      - ~/files/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
```

And this my frigate config:
```yml
mqtt:
  host: 192.168.3.200
  user: mqtt
  password: pass
cameras:
  wg:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.2.34:8554/unicast
          roles:
            - record
ffmpeg:
  hwaccel_args: []
record:
  enabled: True
  retain:
    days: 3
    mode: all
detectors:
  coral:
    type: edgetpu
    device: usb
```

The coral is detected correctly within frigate:
![image](https://github.com/blakeblackshear/frigate/assets/1368405/98f04cb2-ee8a-44c9-9153-d0810e5601d2)

But all I see for the camera is this:
![image](https://github.com/blakeblackshear/frigate/assets/1368405/c52d8121-116e-46e3-97a0-d0a6d48b79ca)

As soon as I comment out the `detectors` part of the frigate config, the error is gone and I see the expected video image. 

The frigate logs only show me this:
```
2023-05-30 14:03:17.865950479  [INFO] Starting Frigate...
2023-05-30 14:03:18.716251314  [2023-05-30 14:03:18] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-30 14:03:18.716496908  [2023-05-30 14:03:18] peewee_migrate                 INFO    : Starting migrations
2023-05-30 14:03:18.716783376  [2023-05-30 14:03:18] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-30 14:03:18.729496055  [2023-05-30 14:03:18] frigate.app                    INFO    : Output process started: 350
2023-05-30 14:03:18.736462530  [2023-05-30 14:03:18] frigate.app                    INFO    : Camera processor started for wg: 353
2023-05-30 14:03:18.740063684  [2023-05-30 14:03:18] frigate.app                    INFO    : Capture process started for wg: 355
```

How can I debug this? Does anyone have the same issue? Thanks!

**Comment by NickM-27** [comment, marked as answer]
> The coral is detected correctly within frigate:
> ![image](https://user-images.githubusercontent.com/1368405/241992123-98f04cb2-ee8a-44c9-9153-d0810e5601d2.png)

This does not mean it is detected, the inference speed will show as 10 until inferences are run.

The logs shown here look like it is stalling on initializing the coral most likely meaning the proxmox setup is not done correctly or there is some other issue

**Reply by TheZoker** [reply]
Ah ok good to know! With that I was able to find the missing part from my LXC container config:
```yml
usb0: host=1a6e:089a,usb3=1
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
lxc.mount.entry: /dev/bus/usb/002 dev/bus/usb/002 none bind,optional,create=dir 0, 0
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.mount.auto: cgroup:rw
```

Thanks for the help!
