### DISCUSSION TITLE
Birdseye View Empty

### DISCUSSION THREAD

**Discussion by caronc** [blakeblackshear/frigate#6701] [Ask A Question] [answered]
First off,

This software is amazing!  My camera feeds work from the **Camera** view, but the Birdseye view is always empty.   If I view the Chrome Browser console, there are no web errors or anything....
![image](https://github.com/blakeblackshear/frigate/assets/850374/79a87d98-b85a-4617-9e97-1b118ec0ecb1)

Here is the configuration:
```yaml
mqtt:
  # Optional: Enable mqtt server
  enabled: True
  host: <redacted>
  port: 1883
  user: <redacted>
  password: <redacted>

cameras:
  garage:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://user:redacted@host/rtsp/defaultPrimary?streamType=u
          input_args: preset-rtsp-restream
          roles:
            - record

        - path: rtsp://user:redacted@host/rtsp/defaultSecondary?streamType=u
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      width: 2592
      height: 1944

detectors: 
   cpu1:
     type: cpu

   cpu2:
     type: cpu
```

The only other thing i'd add is that i'm using Nginx to host the product incase the problem lies there.  My config comes down to this:
```nginx
server {
    listen      80;
    server_name redacted;

    # Note: All parameters require that $base be set!
    set                     $base /var/www/;
    root                    $base/html;

    # index
    index index.html index.htm;

    #
    # Main
    #
    location / {
       # Map back to frigate instance running
       proxy_pass http://127.0.0.1:5000;

       # unsafe-eval was the key reason for this line
       add_header Content-Security-Policy "default-src 'self' 'unsafe-eval' 'unsafe-inline' https: data:; base-uri 'self';";

       # support websockets
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $http_connection;

       # General Configuration
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Scheme $scheme;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Just another view of the first image but with the developer console open (console itself is empty - no errors, network tab (illustrated below) shows that everything downloaded okay and websocket is open.... Just not sure why nothing is being put on the page :slightly_frowning_face: 

![Screenshot from 2023-06-04 15-58-48](https://github.com/blakeblackshear/frigate/assets/850374/87bd0d41-4684-40b0-a802-c549f8f736e6)

**Comment by NickM-27** [comment, marked as answer]
This is the expected behavior, by default cameras only show if they see an object. It is all configurable of course.

**Reply by caronc** [reply]
Yeah, i ran back here to pull this discussion out of embarrassment, it just had to wave and dance in-front of the camera to get it to show up (as clearly identified in the docs too)... :man_facepalming:

Thanks for your prompt reply! Everything is working very nicely! :rocket:

**Reply by geerlingguy** [reply]
Just to add a note, you can also force a camera (or all cameras) to appear in birdseye all the time with something like:

```yaml
birdseye:
  enabled: True
  mode: continuous
```
