### DISCUSSION TITLE
Record audio from another camera

### DISCUSSION THREAD

**Discussion by diogopmartins** [blakeblackshear/frigate#6704] [Ask A Question] [answered]
Hello!
I have two cameras in one location, but only one camera has audio. That audio from the audio camera works flawlessly in Frigate.
Is it possible to add the same audio stream to the camera recording that doesn't have have audio?
Many thanks!

**Comment by NickM-27** [comment]
This is possible with go2rtc and then just use the restream as the source for frigate camera

**Reply by diogopmartins** [reply]
How do I do that? 

This is my current Config for those cameras:

```
   Garden1:
  - rtsp://192.168.10.242:554/user=admin_password=_channel=1_stream=0.sdp
  - ffmpeg:back#video=h264#audio=aac
  Garden1_sub:
  - rtsp://192.168.10.242:554/user=admin_password=_channel=1_stream=1.sdp
  Garden2:
  - rtsp://192.168.10.243:554/user=admin_password=_channel=1_stream=0.sdp
  Garden2_sub:
  - rtsp://192.168.10.243:554/user=admin_password=_channel=1_stream=1.sdp`
```

Thank you!

**Reply by NickM-27** [reply, marked as answer]
Well for one ffmpeg:back#video=h264#audio=aac is incorrect and `back` is supposed to be replaced with the actual name of the camera. Secondly you would just make a similar line to that on the camera without audio pointing at the camera with audio

**Reply by diogopmartins** [reply]
It's now working! Thank you!

Leave my working config here if useful for someone else.
```

    Garden1:
      - rtsp://192.168.10.242:554/user=admin_password=_channel=1_stream=0.sdp
      - "ffmpeg:Garden1#video=h264#audio=aac"
    Garden1_sub:
      - rtsp://192.168.10.242:554/user=admin_password=_channel=1_stream=1.sdp
    Garden2:
      - rtsp://192.168.10.243:554/user=admin_password=_channel=1_stream=0.sdp
      - "ffmpeg:Garden1#audio=aac"
    Garden2_sub:
      - rtsp://192.168.10.243:554/user=admin_password=_channel=1_stream=1.sdp 
```

**Reply by Mincka** [reply]
Hi @diogopmartins,

Can you confirm you have audio in recordings? I only have audio in live view with this method.

I'm using this for the camera:

```
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
```

**Comment by kobelka** [comment]
Hi,
I have the same question, but this above does not work for me. 

```
    hausseitecam:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.72:88/videoMain
    - ffmpeg:hausseitecam#audio=aac
    hausseitecam_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.72:88/videoSub   # <- stream which supports video & aac audio.
    - ffmpeg:hausseitecam_sub#audio=aac
    terrassecam:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.75:88/videoMain
    - ffmpeg:hausseitecam_sub#audio=aac
    terrassecam_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.11.1.75:88/videoSub   # <- stream which supports video & aac audio.
    - ffmpeg:hausseitecam_sub#audio=aac
```

```
  hausseitecam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/hausseitecam
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/hausseitecam_sub   # <--- the name here must match the name of the camera_sub in restream
        input_args: preset-rtsp-restream
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    webui_url: http://hausseitecam.kobelka.de:88
    live:
      stream_name: hausseitecam_sub
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
      - 988,720,1280,720,1280,586,1280,411,1136,271,1055,201,907,107,758,34,715,123
 terrassecam:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/terrassecam
       # input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/terrassecam_sub
       # input_args: preset-rtsp-restream
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-aac
    webui_url: http://terrassencam.kobelka.de:88/
    motion:
      mask:
      - 338,237,0,622,0,94,277,0
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      stream_name: terrassecam_sub
    objects:
      filters:
        handbag:
          threshold: 0.8
        person:
          threshold: 0.76
```

Can you help ? @NickM-27 
Regards 
Jörg
