### DISCUSSION TITLE
Rotate the Record stream

### DISCUSSION THREAD

**Discussion by StarMonkey1** [blakeblackshear/frigate#6756] [Ask A Question] [answered]
So I've managed to get my detect feed rotated which means on the Frigate home page the view is correctly rotated.
```
    Back_Door:
      - rtsp://user:password@192.168.1.103/av_stream/ch0
    Back_Door_Rotated:
      - "ffmpeg:Back_Door#video=h264#rotate=90"
 ```
When I click on the Camera feed to view the Live view the feed is then not rotated. If I click on Debug to view the detect feed then it is correctly rotated again.
```
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Rotated
          roles:
            - record
            - detect
```
Is there anyway to rotate the live/record stream?

**Comment by NickM-27** [comment, marked as answer]
The record should be correctly rotated as well. To get your live feed rotated simply set

```
live:
  stream_name: Back_door_Rotated
```

on the back door camera in frigate config

**Reply by StarMonkey1** [reply]
But then don't I lose the ability to view in webrtc? The view then becomes jsmpg which I thought was limited in terms of fps.

**Reply by NickM-27** [reply]
No not at all, you are simply telling frigate the name of the stream that should be used for mse / WebRTC. 

If you lose the mse / WebRTC options then you have spelled something wrong or made some other error.

**Reply by StarMonkey1** [reply]
Webrtc is working fine, this is the only change I made and it immediately switches to jsmpg, the other cameras stay on webrtc.
```
  Back_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Rotated
          roles:
            - record
            - detect
    live:
      stream_name: Back_Door_Rotated
    objects:
      track:
        - person
        - bicycle
      filters:
        person:
          min_area: 5000
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain: 
          default: 14
          mode: active_objects
        pre_capture: 15
        post_capture: 15
    detect:
      width: 720
      height: 1080
      fps: 5
    ui:
      order: 5
```

**Reply by NickM-27** [reply]
And when you press the drop-down there are no other options? That means something isn't setup right. Please show the whole config.

**Reply by StarMonkey1** [reply]
Nope, no other options.
```
mqtt:
  enabled: true
  host: 192.168.1.10
  port: 1883
  user: frigate_mqtt
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: true

ui:
  live_mode: webrtc

cameras:
  Front_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          roles:
            - record
        - path: rtsp://user:password@192.168.1.108:554/Streaming/channels/101
          roles:
            - detect
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 0

  Front_Garden:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Garden
          roles:
            - record
        - path: rtsp://user:password@192.168.1.107:554/Streaming/channels/101
          roles:
            - detect
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 1

  Utility_External:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Utility_External
          roles:
            - record
        - path: rtsp://user:password@192.168.1.105:554/Streaming/channels/101
          roles:
            - detect
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
        car:
          min_area: 25000
    ui:
      order: 2

  Office_External:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Office_External
          roles:
            - record
        - path: rtsp://user:password@192.168.1.106:554/Streaming/channels/101
          roles:
            - detect
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - horse
      filters:
        person:
          min_area: 1000
    motion:
      mask:
        - 643,305,645,720,1080,720,1080,0,621,0
    ui:
      order: 3

  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
        - path: rtsp://rtsp:password@192.168.1.102/av_stream/ch0
          roles:
            - detect
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 4

  Back_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Rotated
          roles:
            - record
            - detect
    live:
      stream_name: Back_Door_Rotated
    objects:
      track:
        - person
        - bicycle
      filters:
        person:
          min_area: 5000
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain: 
          default: 14
          mode: active_objects
        pre_capture: 15
        post_capture: 15
    detect:
      width: 720
      height: 1080
      fps: 5
    ui:
      order: 5

go2rtc:
  streams:
    Front_Door:
      - rtsp://user:password@192.168.1.108:554/Streaming/channels/101
    Front_Garden:
      - rtsp://user:password@192.168.1.107:554/Streaming/channels/101
    Utility_External:
      - rtsp://user:password@192.168.1.105:554/Streaming/channels/101
    Office_External:
      - rtsp://user:password@192.168.1.106:554/Streaming/channels/101
    Garage:
      - rtsp://rtsp:password@192.168.1.102/av_stream/ch0
    Back_Door:
      - rtsp://rtsp:password@192.168.1.103/av_stream/ch0
    Back_Door_Rotated:
      - "ffmpeg:Back_Door#video=h264#rotate=90"

  webrtc:
    candidates:
      - 192.168.1.4:8555
      - stun:8555
```
