### DISCUSSION TITLE
Reduce latency on older hardware ( Hardware Acceleration not supported )

### DISCUSSION THREAD

**Discussion by MatthewReed303** [blakeblackshear/frigate#6758] [General]
Hi,  I have 4x cheap IP cameras I will be mounting on some machinery for operator to help see and align logs on a saw mill to the laser line, The operators station is remote and no one is close to the saw, it's just for alignment purposes. The issue I'm having is the latency is 1-2 sec in frigate, I did get it down from around 4-5 sec factory settings. Here is a link to the cam:

https://www.aliexpress.us/item/3256803348748715.html?spm=a2g0o.order_list.order_list_main.11.44ab1802nCqUaz&gatewayAdapt=glo2usa4itemAdapt

It supports all the normal features such as rstp, onvif etc it is using H265 and not H264 so not sure if that's a cause or not. If I run there xmeye VMS software in a windows VM the latency it almost nothing <1 sec . I have tried the stream in VLC with low latency settings and also OpenCV directly and these have around the same latency as Frigate at 1-2sec which makes me believe this is an RTSP limitation or an issue with FFMPEG? 

Here is my Frigate Config. 

```
mqtt:
  enabled: False

go2rtc:
  streams:
    rtsp_cam51:
      - rtsp://:@192.168.1.51:554/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#video=h264"
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus

    rtsp_cam52:
      - rtsp://:@192.168.1.52:554/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#video=h264"
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus

    rtsp_cam53:
      - rtsp://:@192.168.1.53:554/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st # <- stream which supports video & aac audio.
      #- "ffmpeg:rtsp_cam#video=h264"
      #- "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to opus

cameras:
  cam51:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam51 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
#      hwaccel_args: preset-vaapi
#    live:
#      stream_name: rtsp_cam
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10

  cam52:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam52 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
#      hwaccel_args: preset-vaapi
#    live:
#      stream_name: rtsp_cam
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10

  cam53:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam53 # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
#      hwaccel_args: preset-vaapi
#    live:
#      stream_name: rtsp_cam
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous

# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: True
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html 
```
