### DISCUSSION TITLE
Automatically updating frigate when there's a new release, using watchtower

### DISCUSSION THREAD

**Discussion by ronisaacson** [blakeblackshear/frigate#6769] [Show and tell]
A while back I set up watchtower to automatically update frigate when the stable release changes. Today it ran for the first time and it worked! I got an email notification and checked to find 0.12.1 running normally. I'll share my docker-compose.yml in case anyone wants to do the same thing. The frigate service is mostly copied from the docs, and then the watchtower service is below:

```
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .../config.yml:/config/config.yml
      - .../frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "..."
    logging:
      driver: syslog
      options:
        tag: "frigate"
    labels:
      - "com.centurylinklabs.watchtower.scope=frigate"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-frigate
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope frigate
    network_mode: "host"
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ...
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ...
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: 127.0.0.1
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: frigate
    logging:
      driver: syslog
      options:
        tag: "watchtower-frigate"
    labels:
      - "com.centurylinklabs.watchtower.scope=frigate"
```

The `network_mode` setting for the watchtower container is needed because my frigate server is also my local mailserver, and containers can't talk to the host server in the default network mode. If you want email notifications and have a different mailserver (which is more common) then you don't need this setting.
