### DISCUSSION TITLE
No events after enabling yolov8 model

### DISCUSSION THREAD

**Discussion by seidler2547** [blakeblackshear/frigate#6770] [Ask A Question] [answered]
I have stared using frigate very recently. In order to reduce false positives, I am trying to use the yolov8 model. I used the Google Colab to create and download the model files, and it appears to be in use without problems:
```
2023-06-12 09:24:08.541897835  [2023-06-12 09:24:08] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 3, 416, 416}
2023-06-12 09:24:08.541904031  [2023-06-12 09:24:08] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 84, 3549}
2023-06-12 09:24:08.541910782  [2023-06-12 09:24:08] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```
However, it doesn't ever seem to detect anything. This is my config:
```
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  ov:
    type: openvino
    model:
      path: /custom/models/yolov8s/yolov8s.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /custom/models/yolov8s/yolov8s.mapping

record:
  enabled: True
  retain:
    days: 7
    mode: motion

motion:
  threshold: 50

cameras:
  Testcam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.48:554//h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```
I am running frigate in docker-compose, on an Intel i7-7500U CPU with hw acceleration.

**Comment by NickM-27** [comment]
This usually happens due to an incorrect model width / height. If that is correct then you may want to enable debug logs for openvino

**Reply by seidler2547** [reply]
Thanks. I would have thought that it would throw an error if that was the case. But I set it to 416x416 in both the generating process as well as the config file. I enabled DEBUG logging but there's no output, at least not from the detectors. All that added were some SQL queries when I browse the web interface. I tried setting ` device` to `CPU` now, just to see if it helps.

**Comment by mknjc** [comment, marked as answer]
Hi, I think your labelmap is wrong. The generated .mapping file isn't a labelmap. The real mapping is inside the yolov8s.xml under net->rt_info->framework->names.
As far as I see yolov8 uses this labelmap (only cross checked some entries): https://github.com/openvinotoolkit/open_model_zoo/blob/master/data/dataset_classes/coco_80cl.txt

Just download this file and use it for model->labelmap_path

**Reply by seidler2547** [reply]
Thanks. I literally just figured this out myself seconds ago. Thanks! I think I just copied the labelmap line from somewhere.

**Comment by philippedegeer** [comment]
Hi, identical situation for me with Frigate and Yolov8. Everything seems ok but no detection.
@NickM-27, could you please indicate how to enable debug logs for openvino. I have searched the documentation but could not find any reference to this
Many thanks - Philippe

**Reply by NickM-27** [reply]
If it is an identical situation then I'd suggest checking your config as OP had an error in theirs

**Comment by philippedegeer** [comment]
Thanks NickM-27 but my labelmap file & path are correct. Model size also. Things worked well with YoloX, although with a lot of false positives. With Yolov8, no detection at all

**Reply by seidler2547** [reply]
This config works for me now:
```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /custom/models/yolov8s/yolov8s.xml

model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
```

**Reply by philippedegeer** [reply]
thanks seidler2547, I am giving it a try without the reference to the labelmap path as in your kindly provided config file.

Did you also have a number of dependencies warnings/errors when running the Google Colab Notebook ? I did have several but the three files (xml, mapping and bin) were generated at the end.

**Comment by jaredmcqueen** [comment]
how did the false positive rates go after using the new model?  Better?  Worse?

**Reply by seidler2547** [reply]
Much better. Detects bicycles as bicycles and not as persons. Though sometimes detects me as a cat, who knows.

**Comment by John10240** [comment]
much less events than before, so I try to decrease the "min_score" and "threshold", and see what happens.
~~same as you, after using yolov8m no events and no errors.~~

```
detectors:
 ov:
    type: openvino
    device: AUTO
    model:
      path: /custom_data/yolov8m/yolov8m.xml
model:
  width: 416
  height: 416
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  labelmap_path: /config/coco_80cl.txt
```
