### DISCUSSION TITLE
Turn of motion and person detection by default and only turn it on via Home Assistant

### DISCUSSION THREAD

**Discussion by TheZoker** [blakeblackshear/frigate#6776] [Ask A Question]
Hi there,

How can I set a camera to not detect motion and persons by default and only do that, if I enable it via home assistant? 
We have a camera inside the house and it should only notify me, if I'm not at home. 
I currently have this config:
```yaml
mqtt:
  host: 192.168.3.200
  user: mqtt
  password: xxx
cameras:
  wg:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - record
  g4:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - record
ffmpeg:
  hwaccel_args: []
record:
  enabled: True
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 10
      mode: motion
birdseye:
  enabled: False
detectors:
  coral:
    type: edgetpu
    device: usb
```

I then have an automation in HA, that turns on and off the `Detect` and `Motion` toggle. But for some reason, these stitches turn themselves on after some time without any automation triggering. My guess it, that this happens, since the motion and person detections is turned on in the config. How can I fix this? 

Thanks!
