### DISCUSSION TITLE
Problem with Motion Detected events

### DISCUSSION THREAD

**Discussion by swingking** [blakeblackshear/frigate#6781] [Ask A Question] [answered]
I'm a new Frigate user and I've run into a problem that I can't figure out.  I've installed Frigate as a Docker container on Ubuntu 20.04.  I don't have a HW-accelerator for a detector, so right now I'm just using the CPU.  My problem is events don't appear to be created or stored.  I have a single Tapo C200 connected and I do get live video in the Frigate UI.  When I run the UI in debug mode with Motion Boxes turned on, I see it is detecting motion.  What doesn't happen is an Event showing up in the log or in the the Events tab.  BTW, the reported Inference Speed is 126.37 ms and the CPU % is 190% when motion is happening.  

Here's my config.  I got most of it from other posts here.  Any idea what is wrong?
```
logger:
  default: debug

mqtt:
  enabled: False

database:
  path: /media/frigate/frigate.db

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
    rtmp: preset-rtmp-generic

detectors:
  cpu1:
    type: cpu
    num_threads: 3

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

objects:
  track:
    - person
  mask: 0,0,1000,0,1000,200,0,200
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.7
      mask: 0,0,1000,0,1000,200,0,200

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mask: 0,900,1080,900,1080,1920,0,1920
  improve_contrast: False
  mqtt_off_delay: 30

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: true
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

# go2rtc:
#  streams:
#    tapa_1:
#      - "ffmpeg:rtsp://username:password@192.168.128.117:554/stream2#video=copy#audio=copy#audio=opus"

cameras:
  tapa_1: 
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.128.117:554/stream2
          roles:
            - detect
            - record
```

**Comment by NickM-27** [comment]
I'd highly suggest not copying from other posts (which often have incorrect config anyway) and just follow the getting started docs: https://docs.frigate.video/guides/getting_started

I see quite a few different issues here

**Reply by swingking** [reply]
Thanks for the quick response.  I had added a bunch of this to try and get things working.  I've simplified the config based on the guide and here's what I have now.  I'm still not seeing events in the Events tab, but I did see this message in the logs:

2023-06-12 16:22:35.128962142  [2023-06-12 16:22:35] frigate.events                 DEBUG   : Event received: start tapo_1 1686604954.784089-ao3c7r
...
2023-06-12 16:22:46.292352190  [2023-06-12 16:22:46] frigate.events                 DEBUG   : Event received: end tapo_1 1686604954.784089-ao3c7r

Here's the updated config:
```
logger:
  default: debug

mqtt:
  enabled: False

cameras:
  tapo_1: 
    ffmpeg:
      inputs:
        - path: rtsp://ksmelcer:vorlon1@192.168.128.117:554/stream1
          roles:
            - detect
            - record
 
detectors:
  cpu1:
    type: cpu
    num_threads: 3

detect:
  enabled: true
  width: 1280
  height: 720

record:
  enabled: true
```
