### DISCUSSION TITLE
Is it possible to have different retention settings per camera?

### DISCUSSION THREAD

**Discussion by cvocvo** [blakeblackshear/frigate#6792] [Ask A Question]
I was looking at the documentation here: 
https://docs.frigate.video/configuration/record/

And I'm wondering if it's possible to have different retention settings per camera? For example, my cat cam would be fine with a shorter retention than my security camera, for example.

Thank you!

**Comment by NickM-27** [comment]
Yes, all settings are overrideable at the camera level

**Reply by cvocvo** [reply]
Neat, so does this work (as an example)? Or do I have to put this somewhere else?

Edit: I tried it -- no errors -- not sure how to test.

```
cameras:
  catcam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/catcam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
```
