### DISCUSSION TITLE
Lag every 2 seconds on recordings

### DISCUSSION THREAD

**Discussion by Engine1992** [blakeblackshear/frigate#6805] [Ask A Question]
Hi! I 

I noticed that every recording in Frigate, from any camera, has lags every 2 seconds, i.e. the image freezes every two seconds and goes on. What could this be the cause of? I asked a friend to check at home, also lags occur. I have a standard configuration from docs.frigate. Coral detector.

**Comment by NickM-27** [comment]
You should show your config otherwise there is no way to help. Usually it is a problem with the config or a problem with the camera

**Comment by Engine1992** [comment]
I attach part of the configuration (the whole config is very long) but every camera has the same config (excluding addresses, masks and names):

```
mqtt:
  host: xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  stats_interval: 60

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

birdseye:
  enabled: true
  restream: true
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

database:
  path: /db/frigate.db

ui:
   # live_mode: webrtc
    use_experimental: false

telemetry:
    version_check: true

go2rtc:
  streams:
    Home_front:
      - rtsp://xxx:xxx@x.x.x.x:554/h264Preview_01_main
    Home_front_sub:
      - rtsp://xxx:xxx@x.x.x.x:554/h264Preview_01__sub

  webrtc:
    candidates:
      - x.x.x.x:8555

cameras:
  Home_front:
    detect:
      enabled: true
      fps: 15
      max_disappeared: 75
      stationary:
        interval: 0
        threshold: 150
    objects:
      track:
        - person
        - car
    motion:
      threshold: 25
      contour_area: 30  
      mask:
        - 1280,0,1280,445,657,0
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 5
    rtmp:
      enabled: false
    ui:
      order: 0
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Home_front
          roles:
            - record
        #    - rtmp
        - path: rtsp://127.0.0.1:8554/Home_front_sub
          roles:
            - detect
```
