### DISCUSSION TITLE
cannot rotate live wiew 90 degrees

### DISCUSSION THREAD

**Discussion by ILgazEZEN08** [blakeblackshear/frigate#6807] [Ask A Question]
Recently I installed frigate on docker compose and home assistant. I've been trying to rotate footage vit ffmpeg but it doesn't work. I want to rotate it 90 degrees because of my IP camera is mounted like that. (I tried to rotate it from camera's interface but there is nothing like rotate or so. I'm using an hikvision 2043. 
there is my config file

```
mqtt:
  host: 192.168.1.104
  user: nex
  password: 1231a1231a

cameras:
  outside:
    ffmpeg:
      inputs:
        - path: rtsp://admin:1231a1231aILgaz@192.168.1.113:554/Streaming/Channels/1
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2560
      height: 1440
      fps: 25
    
    record:
      enabled: True
  bodrum:
    ffmpeg:
      inputs:
        - path: rtsp://admin:1231a1231aILgaz@192.168.1.114:554/Streaming/Channels/1
          roles:
              - detect
              - rtmp
              - record
    detect:
      width: 2560
      height: 1440
      fps: 20
    record:
      enabled: True
go2rtc:
  streams:
    outside:
      - rtsp://admin:1231a1231aILgaz@192.168.1.113:554/Streaming/Channels/1
      - "ffmpeg:outside#video=h264#rotate=90"
      
```

**Comment by NickM-27** [comment]
You need to keep it all in the same line otherwise the rotated stream will be ignored

```
go2rtc:
  streams:
    outside:
      - "ffmpeg:rtsp://admin:1231a1231aILgaz@192.168.1.113:554/Streaming/Channels/101#video=h264#rotate=90"
```
