### DISCUSSION TITLE
really bad false positive rate for "bicycle" and "dog", no other detections

### DISCUSSION THREAD

**Discussion by rknobbe** [blakeblackshear/frigate#6819] [Ask A Question]
I'm running 0.12.1-367D724 in a docker container on a linux box with a Coral USB as a detector

```
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 2.0
      threshold: 0.7
    bicycle:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 2.0
      threshold: 0.8
motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
detectors:
  coral:
    type: edgetpu
    device: usb
```

The only objects that get detected are "Dog" and "Bicycle", however as you can see below, dog is spotty and bicycle is pretty much always wrong.  How do I improve my detection rate?

![Bicycle](https://github.com/blakeblackshear/frigate/assets/802457/489b248d-398c-4433-b29b-3f995f9f2fce)
![Dog](https://github.com/blakeblackshear/frigate/assets/802457/41b408a7-c67b-459c-8865-332ae1506fd6)

**Comment by NickM-27** [comment]
The config seems wrong, it has filters for dog and bicycle but then the only objects listed under track is person. 

Also in general this is just a factor of the fact that the current default model is not trained on images from security cameras as it is a Google Demo Model. This is why Frigate+ is being worked on.

**Reply by rknobbe** [reply]
I have per-camera track settings, since some cameras (like my patio) ought never have to worry about tracking a truck.
I could still very well be doing it wrong, but this seems like it's a valid config.

The NorthEast camera config is as follows:
```

cameras:
  NorthEast:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://:@192.168.1.230:554/mpeg4?username=xxx&password=xxx
          roles:
            - detect
            - record
    detect:
      stationary:
        interval: 5
        threshold: 50
      width: 2592
      height: 1944
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - bicycle
        - van
        - truck
        - dog
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
```
