### DISCUSSION TITLE
Frigate not detecting events

### DISCUSSION THREAD

**Discussion by gregeeh** [blakeblackshear/frigate#6826] [Ask A Question] [answered]
Hi all,

Firgate 12.1 and Mosquitto installed in a Docker Container via Portainer Stack.

Frigate is not detecting any motion when enabled and if it does and it records the video is all broken up and no email notifications are sent.  Restarting the Container usually fixes it, at least for a little while, which does not make for a very reliable system.

Logs don't show any motion detection, just the enabling of it.

Birdseye shows no issues with the video.

Config:
```
mqtt:
    host: 192.168.10.2
    user: mqtt-user
    password: mqtt-password
cameras: # Reolink E1 Pro
    Villa333:
        rtmp:
            enabled: false
        ffmpeg:
            inputs:
                - path: rtsp://admin:mypassword@192.168.10.70:554/h264Preview_01_sub
                  input_args: preset-rtsp-generic
                  roles:
                    - detect
                - path: rtsp://admin:mypassword@192.168.10.70:554/h264Preview_01_main
                  input_args: preset-rtsp-generic
                  roles:
                    - record
                    - rtmp
        detect:
            enabled: true
            width: 640
            height: 360
        record:
            enabled: True
            events:
                pre_capture: 15
                post_capture: 5
                retain:
                    default: 10
                    mode: active_objects
snapshots:
    enabled: True
    retain:
        default: 10
birdseye:
    enabled: True
    mode: continuous
    quality: 6
```
Any ideas on how to find out what the issue is would be appreciated.

TIA
