### DISCUSSION TITLE
How to disable "access log" from frigate logs

### DISCUSSION THREAD

**Discussion by trunet** [blakeblackshear/frigate#6871] [Ask A Question]
How to get rid of the access log from frigate logs running in a docker container?

I'm getting lots of that I don't care:

`2023-06-21 13:52:07.562489514  [REDACTED] - - [21/Jun/2023:13:52:07 +0200] "GET /api/stats HTTP/1.1" 200 2338 "-" "HomeAssistant/2023.6.1 aiohttp/3.8.4 Python/3.11" "-"`

My logger in config.yml is like this:

```yaml
logger:
  default: warning
  logs:
    frigate.mqtt: info
```

"access_log" should be considered INFO in my opinion, and warning should disable it.

**Comment by NickM-27** [comment]
those logs are for python only not nginx. Also, using the log viewer in the webUI is recommended since it splits out the logs into different types

**Comment by trunet** [comment]
Yes, but I don't want frigate container filling up my docker log. Can't on the entrypoint add a check to logger default or a logs nginx per example to disable access_log?

**Reply by NickM-27** [reply]
it's not that simple, nginx starts as a service via S6 and the frigate config is entirely unconnected from the nginx config

**Reply by trunet** [reply]
we just need a `sed` to comment this out: https://github.com/blakeblackshear/frigate/blob/7c1568fcb941ad17256ab73438cb997b23fb7f33/docker/rootfs/usr/local/nginx/conf/nginx.conf#L20

probably running it from here: https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/etc/s6-overlay/s6-rc.d/nginx/run

**Reply by NickM-27** [reply]
Right, discussion is already happening here https://github.com/blakeblackshear/frigate/pull/6852

**Reply by trunet** [reply]
ahh, thanks... haven't found that. will close this.

**Comment by jr-k** [comment]
Old but if someone need a quick solution

1. Add a script `custom-start.sh` next to `docker-compose.yml`
```bash
#!/bin/bash

sed -i 's/access_log \/dev\/stdout main;/access_log \/dev\/null main;/g' /usr/local/nginx/conf/nginx.conf

# Delegate to original entrypoint
exec /init "$@"
```

2. Edit `docker-compose.yml`, add a volume and a custom entrypoint
```yaml
services:
  frigate:
    # ...
    volumes:
      # ...
      - ./custom-start.sh:/custom-start.sh
    entrypoint: ["/bin/bash", "/custom-start.sh"]
```
