### DISCUSSION TITLE
Possible to set overall threshold for all objects at once?

### DISCUSSION THREAD

**Discussion by paultanger** [blakeblackshear/frigate#6933] [Ask A Question]
Is it possible to set a threshold for all objects in the config file without having to specify for each object? Is the default 0.7 for everything? Just curious if there is a way to set it to 0.6 without having to add a filter for each object.   Here is the way I see it being done:

```
      filters:
        animal:
          threshold: .55
```

but it would be great if I could do something like this:

```
objects:
  track:
    - person
    - more objects..
  threshold: 0.6 # would work for all objects
```
