### DISCUSSION TITLE
Cant increase shm size - please help!!

### DISCUSSION THREAD

**Discussion by ChangoMunk** [blakeblackshear/frigate#6944] [Ask A Question] [answered]
Hi, 

firstly - LOVE this project. I have it running on a mini PC with coral and it's truly awesome.

I set this up in docker container last night and it's been running great. The only thing is that no matter what I do to the docker-compose.yaml file, i just cannot increase the size of the shm beyond the default 64mb.

I've tried it in all kinds of ways, such as:

frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    build:
      context: .
      shm_size: '2gb'
    shm_size: '2gb'

and

frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: '2gb'

I've tried it in " " instead.

I've repeatedly stopped and restarted docker each time I try something new and still I get the following error:

WARNING : The current SHM size of 67.1MB is too small, recommend increasing it to at least 90.49999999999999MB.

The only containers I am running are portainer and frigate.

I'm brand new to all of this, so please, if anyone helps, try and keep things simple haha.

Thanks in advance!

Cheers,

Will.

**Comment by ChangoMunk** [comment]
Hmm, the formatting hasnt worked too well there - made it all left aligned unfortunately.

**Comment by NickM-27** [comment]
the location is covered in the docs https://docs.frigate.video/frigate/installation#docker

**Reply by ChangoMunk** [reply]
Thanks mate, yea I've done everything as stated in those docs to be honest, but no joy.

**Reply by NickM-27** [reply]
I would suggest just copying it but only doing like "96mb" instead of "2gb"

**Reply by ChangoMunk** [reply]
Cheers bud, I'll give that a go. I tried 256MB to start with, so yea, maybe I'm being to ambitious haha.. Standby.

**Reply by ChangoMunk** [reply]
Same result with 96MB I'm afraid. I must be missing something, but have no idea what.

**Reply by NickM-27** [reply]
Please use a code share site or github code formatting to share your docker compose for frigate

**Reply by florisvangeel** [reply]
Noticed today it like MB, not mb
i run it at
```
shm_size: "256MB"
```
since i have some cameras

**Comment by ChangoMunk** [comment]
Lets see if this shows correctly....

```
version: '3.9'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "96MB"
       
    detectors:
      coral:
      type: edgetpu
      device: usb
      model:
      path: "/custom_model.tflite"   
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
