### DISCUSSION TITLE
Recordings on motions, without object detection

### DISCUSSION THREAD

**Discussion by ABATAPA** [blakeblackshear/frigate#6945] [Ask A Question]
Hello! I have object recognition set up and running, but I want to record just by movement. And I can't: either the recording doesn't work, or everything is recognized as a person. Can you share an example of recording by movement, without recognition?

<details><summary>Below is a working configuration with object detection. What should I remove/disable?</summary>
<p>

```
ui:
  live_mode: webrtc
  use_experimental: False
mqtt:
  enabled: False
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    Camera1:
      - rtsp://user:password@IP:554/live
    CameraCat:
      - rtsp://user:password@IP:554/live
cameras:
  Camera1:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Camera1
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True
      max_disappeared: 25
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
        - dog
    motion:
      threshold: 20
      contour_area: 15
      improve_contrast: True
      mask: 
        - 1920,0,1920,644,1508,678,1355,552,1351,399,1129,392,1113,534,1233,733,1178,887,539,905,0,775,0,0
    record:
      enabled: True
      events:
        pre_capture: 4
        post_capture: 8
        required_zones: []
        retain:
          default: 1
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3
  CameraCat:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CameraCat
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True
      max_disappeared: 25
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      threshold: 20
      contour_area: 15
      improve_contrast: True
    record:
      enabled: True
      events:
        pre_capture: 4
        post_capture: 8
        required_zones: []
        retain:
          default: 10
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 10

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
birdseye:
  enabled: True
  mode: continuous
  ``` 
</p>
</details>

**Comment by NickM-27** [comment]
you need to enable 24/7 recording

```
# keep 4 days of motion
record:
  enabled: True
  retain:
    days: 4
    mode: motion
  events:
    pre_capture: 4
    post_capture: 8
    required_zones: []
    retain:
      default: 10
```
