### DISCUSSION TITLE
Please help, adding a Aqara Camera Hub G3

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#6946] [Ask A Question]
Hi,

I've got a Aqara Camera Hub G3 that I'd like to add to my Frigate config for detection, recording etc.

I'm struggling to understand how I add this camera. I've added all previous via rtsp but I believe this needs to potentially be added via go2rtc (I could be wrong). Could someone help me with a definition of what the config should potentially look like to achieve this?

Here's what I've tried so far which doesn't appear to work:
```
go2rtc:
  streams:
    Bedroom_2:
      - hass:Camera-Hub-G3-E44E
      - ffmpeg:Bedroom_2#audio=aac#audio=opus#async
```

Many Thanks
