### DISCUSSION TITLE
Non-monotonous DTS in output stream 0:0

### DISCUSSION THREAD

**Discussion by moskovskiy82** [blakeblackshear/frigate#7067] [General]
Have the whole log filled with Non-monotonous DTS in output stream 0:0 errors from all of my cams. Any ideas. Googling didn't help that much

Frigate Config

```
logger:
  default: error

detectors:
  coral:
    type: edgetpu
    device: pci

mqtt:
 sensitive info
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args:
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-rw_timeout'
    - '5000000'
    

go2rtc:
  streams:

    uchastok:
      - "http://ip
      - "ffmpeg:uchastok#audio=opus"
    lesnoy:
      - "http://ip
      - "ffmpeg:uchastok#audio=opus"
    lesnoy_sub:
      - "http://ip
    roads:
      - "rtsp://ip
      - "ffmpeg:roads#audio=opus"
    roads_sub:
      - "rtsp://ip



cameras:
  uchastok:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/uchastok?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    live:
      stream_name: uchastok

    mqtt:
      enabled: True
      timestamp: false
      bounding_box: false
      crop: True
      height: 1920
      quality: 100
    objects:
      track:
        - person




  lesnoy:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/lesnoy?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    live:
      stream_name: lesnoy

    mqtt:
      enabled: True
      timestamp: false
      bounding_box: false
      crop: True
      height: 1920
      quality: 100
      
    objects:
      track:
        - person
        - cat

  roads:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/roads?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      width: 1280
      height: 960
      fps: 5
 
    live:
      stream_name: roads
    birdseye:
      mode: motion
    mqtt:
      enabled: True
      timestamp: false
      bounding_box: false
      crop: True
      height: 1944
      quality: 100
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          min_area: 3000
          min_ratio: 0.5


  tambur:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://ip:8551/Main
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 760
      fps: 5
    birdseye:
      mode: motion

    mqtt:
      enabled: True
      timestamp: false
      bounding_box: false
      crop: True
      height: 1920
      quality: 100
    objects:
      track:
        - person
        - cat

record:
  enabled: true

snapshots:
  enabled: true
detect:
  enabled: true

birdseye:
  enabled: True
  mode: continuous
  restream: False
```
