### DISCUSSION TITLE
No recordings or clips

### DISCUSSION THREAD

**Discussion by dodavies** [blakeblackshear/frigate#7105] [Ask A Question]
Hi,

I have a home assistant blue with a coral attached and an nfs share.

my detections have thumbnails but no clips and I have no recordings.

here is the last few line of a very long log with mostly the same output.
My config is at the bottom, does anyone have any ideas.

its a Reolink 810A camera

-10 12:44:48.326058421  [2023-07-10 13:44:48] watchdog.gate                  ERROR   : No new recording segments were created for gate in the last 120s. restarting the ffmpeg record process...
2023-07-10 12:44:48.326690571  [2023-07-10 13:44:48] watchdog.gate                  INFO    : Terminating the existing ffmpeg process...
2023-07-10 12:44:48.327296221  [2023-07-10 13:44:48] watchdog.gate                  INFO    : Waiting for ffmpeg to exit gracefully...
2023-07-10 12:44:58.355680050  [2023-07-10 13:44:58] watchdog.gate                  ERROR   : No new recording segments were created for gate in the last 120s. restarting the ffmpeg record process...
2023-07-10 12:44:58.356596504  [2023-07-10 13:44:58] watchdog.gate                  INFO    : Terminating the existing ffmpeg process...
2023-07-10 12:44:58.356608046  [2023-07-10 13:44:58] watchdog.gate                  INFO    : Waiting for ffmpeg to exit gracefully...
2023-07-10 12:45:08.384774844  [2023-07-10 13:45:08] watchdog.gate                  ERROR   : No new recording segments were created for gate in the last 120s. restarting the ffmpeg record process...
2023-07-10 12:45:08.385176444  [2023-07-10 13:45:08] watchdog.gate                  INFO    : Terminating the existing ffmpeg process...
2023-07-10 12:45:08.386781510  [2023-07-10 13:45:08] watchdog.gate                  INFO    : Waiting for ffmpeg to exit gracefully...
2023-07-10 12:45:18.420161210  [2023-07-10 13:45:18] watchdog.gate                  ERROR   : No new recording segments were created for gate in the last 120s. restarting the ffmpeg record process...
2023-07-10 12:45:18.420774568  [2023-07-10 13:45:18] watchdog.gate                  INFO    : Terminating the existing ffmpeg process...
2023-07-10 12:45:18.421299507  [2023-07-10 13:45:18] watchdog.gate                  INFO    : Waiting for ffmpeg to exit gracefully...
2023-07-10 12:45:18.582414171  [2023-07-10 13:45:18] frigate.http                   ERROR   : No recordings found for the requested time range
2023-07-10 12:45:18.636053613  [2023-07-10 13:45:18] frigate.http                   ERROR   : Event does not have recordings: 1688985383.509604-x5utph

```
mqtt:
  host: 192.168.0.160
  user: redacted
  password: redacted
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true 

database:
  path: /config/frigate.db

go2rtc:
  streams:
    gate: 
      - "http://192.168.0.77/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted"
      - "ffmpeg:gate#audio=opus"
    gate_sub: 
      - http://192.168.0.77/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted

cameras:
  gate:
    detect:
      enabled: true
    ffmpeg:
      hwaccel_args: -hwaccel drm -hwaccel_device /dev/dri/renderD128
      inputs:
#        - path: rtsp://127.0.0.1:8554/gate?video=h264&audio=aac
        - path: http://192.168.0.77/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted
          input_args: preset-http-reolink
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - boat
 ```
