### DISCUSSION TITLE
Cheap and Most Stable Frigate compatible Wifi Cameras

### DISCUSSION THREAD

**Discussion by johnvprcam24573455623** [blakeblackshear/frigate#7115] [Polls]
What are the most Stable Frigate Compatible WIFI cameras under $100 that you suggest to buy? 

Have 10 wyze cameras and having a lots of problems/instability and container goes OOM.

**Comment by johnvprcam24573455623** [comment]
blakeblackshear  suggests Dahua and Hikvision and Amcrest  on this post:
https://github.com/blakeblackshear/frigate/discussions/1540


 

**_In my experience Dahua and Hikvision both have multiple streams with configurable resolutions and frame rates. They are also rock solid streams. Frigate runs for months without a single hiccup in the streams. They also both have models with large sensors well known for excellent image quality at night. Not all the models are equal. Larger sensors are better than higher resolutions.

For me, Dahua edges out Hikvision because they are easier to find and order, not because they are better cameras.

Amcrest is my fallback recommendation because they are rebranded Dahuas. They are just rebranding the lower end models with smaller sensors or less configuration options._**

**Reply by jameslivulpi** [reply]
Agreed on Dahua ones. 

this camera is amazing and my favorite all around having 4 streams and varifocal, its a rebranded dahua:
https://empiretech01.com/products/empiretech-ipc-t54ir-ze-s3-1-1-8-cmos-4mp-ir-starlight-vari-focal-turret-security-camera?variant=46950104498461

**Comment by dopeytree** [comment]
This is quite old but I also started with some Wansview wifi cams then some wyze & tried the mini hacs but I've just sold them on ebay.

Recently found ANNKE c500 3k cameras poe for £32 each!!! and the quality at 3k is insane. I have 6x running on one 40w poe switch from TP-Link.

Completely customisable and lockdownable. Highly recommend. Annke seem to be a subdivision or something of hikvision as they share firmware.

Yes have to run cable but you can just buy a 30m run off amazon and some POE extenders (they split 1 cable into 4) and its so easy and more secure.

**Reply by johnvpr** [reply]
@dopeytree 

so how can you split 1 ope cable in 4?

Thanks

John

**Reply by johnvpr** [reply]
@dopeytree 

Ed and what is your config for ANNKE c500?

Thanks!

John

**Reply by dopeytree** [reply]
Hi poe splitter like this 

https://www.amazon.co.uk/Passthrough-Extender-IEEE802-3af-Ethernet-din-rail/dp/B0BJQ4JLL9/ref=sr_1_3_pp?crid=33F7MXWAGSDNA&dib=eyJ2IjoiMSJ9.Raqh--F4EWHlifhu273UIY9cKGJ9ZfjDnCokgttmI_behzFPTi6vqgMWsSeuSfuUf5hV_bG_v3X2gjxH5vBHj7lvlYinrfzU460UQ2GXQ9xau2duBizViys_wify4ex4kh-8JEIkJFoxDBYZela6yfCx6SbHFByXCa-2g8D7sNuoirhrqP6mqK6zJKw261IM3FcIP_p-0FQWnp8Ofo0yO-DSMh1l-AoDI25qt6tRNrM.sFqLtMvd4jLZ53YFwySKjM-W-bKkvwaQvHlqygvru2k&dib_tag=se&keywords=poe+splitter&qid=1708201320&sprefix=poe+spl%2Caps%2C130&sr=8-3

or like this 

https://www.amazon.co.uk/YuanLey-Port-PoE-Passthrough-Amplifier/dp/B0BVR3C92S/ref=sr_1_5?crid=33F7MXWAGSDNA&dib=eyJ2IjoiMSJ9.Raqh--F4EWHlifhu273UIY9cKGJ9ZfjDnCokgttmI_behzFPTi6vqgMWsSeuSfuUf5hV_bG_v3X2gjxH5vBHj7lvlYinrfzU460UQ2GXQ9xau2duBizViys_wify4ex4kh-8JEIkJFoxDBYZela6yfCx6SbHFByXCa-2g8D7sNuoirhrqP6mqK6zJKw261IM3FcIP_p-0FQWnp8Ofo0yO-DSMh1l-AoDI25qt6tRNrM.sFqLtMvd4jLZ53YFwySKjM-W-bKkvwaQvHlqygvru2k&dib_tag=se&keywords=poe+splitter&qid=1708201320&sprefix=poe+spl%2Caps%2C130&sr=8-5

**Reply by dopeytree** [reply]
I have the cameras set up to do 8fps on sub stream and at 640x360 turn the bit rate as high as it will go on both sub stream & main stream. Mainstream is 3k quality. To set this you login to the actual camera's IP.

Enjoy.


below is my detect settings for the cameras within frigate config.

```
# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 640
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 360
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 8
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 4
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 120
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 8
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 800
```

Here is an example camera:
```
go2rtc:
  streams:
    road_cam HQ: ffmpeg:rtsp://admin:annke2023@10.0.0.2:554/H265/ch1/main/av_stream

cameras:
  bird_cam: #Cam Name: Bird Cam (kitchen cat flap)   #Brand: Annke c500   #Quality:3k    #Link:POE
    enabled: true
    ui:
      # Optional: Configuration for how camera is handled in the GUI.
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 4
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: true
    live:
      stream_name: bird_cam HQ
    ffmpeg:
      inputs:
      - path: rtsp://admin:annke2023@10.0.0.7:554/Streaming/Channels/102   # SQ Link
        input_args: preset-rtsp-generic
        roles:
        - detect
        - audio
      - path: rtsp://192.168.22.2:8554/bird_cam%20HQ?mp4    # HQ Link
        input_args: preset-rtsp-restream
        roles:
        - record
    objects:
      track:
      - person
      - cat
      filters:
        cat:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
          # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
          # Checks based on the bottom center of the bounding box of the object
          mask:
          - 52,272,151,265,153,239,139,176,61,184,45,222
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 3000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.9
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.8
          # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
          # Checks based on the bottom center of the bounding box of the object
          #mask: 
          #  - 28,228,80
    motion:
      mask:
      - 0,37,189,37,190,0,0,0
      - 51,262,144,257,153,239,136,187,66,195,45,222
    audio:
      enabled: true # <- enable audio events for the this camera
```
