### DISCUSSION TITLE
Help with my config- Reolink Cameras

### DISCUSSION THREAD

**Discussion by tech2mar** [blakeblackshear/frigate#7153] [General]
Hey friends,

I have some problems with my config, it works.
But I know it could be better,
The problem is that when i want to use a sub stream frigate won't start.

I'm using 3 Reolink cams,
I paste the config here:
https://pastebin.com/eu6cL6yf

If someone could have a look at it and guide me it would be great.
Thanks.

**Comment by NickM-27** [comment]
I would highly suggest going back through the docs https://docs.frigate.video/guides/getting_started

This config looks like it was made following an old guide which is very much out of date

**Reply by tech2mar** [reply]
Oh I see, I noticed that it is changing a lot here. I will need to update the config.

**Comment by moskovskiy82** [comment]
This is what i use for reolinks

```
go2rtc:
  streams:
    uchastok:
      - "http://xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx"
      - "ffmpeg:uchastok#audio=opus"
```

And then (pay attention to preset-vaapi as that is for AMD HW)
```

  uchastok:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/uchastok?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```
