### DISCUSSION TITLE
Go2Rtc hardware acceleration

### DISCUSSION THREAD

**Discussion by moskovskiy82** [blakeblackshear/frigate#7166] [General]
In the documentation is states that docker users are supposed to install master-hardware branch of go2rtc
So is the hardware acceleration supported?

Tried running on amd rx550. This works for frigate (latest 12.1), 
![image](https://github.com/blakeblackshear/frigate/assets/15857592/2f24bb5c-2d94-4d71-b284-53becc946117)

But when adding

    roads_rendered:
      - "ffmpeg:roads#video=h264#width=1280#height=960#raw=-fpsmax 10#hardware=vaapi"
My CPU load rises from 15 to >90%

**Comment by NickM-27** [comment]
Hardware acceleration is supported. There are a lot of loads for the CPU that the GPU can't help with. Need to check what is using the CPU

**Reply by moskovskiy82** [reply]
I have 5 cams. All of them running 1080 or even 4K (no sub streams)
Under cameras section use the following. 
  roads:
    ffmpeg:
      hwaccel_args: preset-vaapi
```
and on one set it to

```
    detect:
      width: 1280
      height: 960
      fps: 5
```

Under this circumstances the CPU load was around 15% GPU load as posted above 5-9% 
```But as soon as i have tried making a substream under go2rtc like above - CPU load went to it's maximum with no changes in GPU load

```
roads_rendered:
  - "ffmpeg:roads#video=h264#width=1280#height=960#raw=-fpsmax 10#hardware=vaapi"
```

Original stream is h264 2592x1944.

**Reply by NickM-27** [reply]
Yes, I used to have a similar setup and didn't have any issues. I'd suggest using htop to figure out what is using the CPU in this case

**Comment by moandcompany** [comment]
Hi, I was recently looking at re-encoding/transcoding Frigate's birdseye and other streams myself using `go2rtc` with different codecs and bitrates while applying hardware acceleration. 

YES, Frigate's built-in go2rtc module does support hardware acceleration already, as the hardware acceleration comes from `ffmpeg` , and the described is related to how ffmpeg parameters are provided to go2rtc, and passed on to ffmpeg when invoked.

I believe when you look at the actual process invocation for `ffmpeg` with this go2rtc configuration, you'll find that many of the input parameters being passed in the following manner are not actually being used by ffmpeg. I was also trying to use the `raw` option as described in the [go2rtc documentation](https://github.com/AlexxIT/go2rtc#source-ffmpeg) in my experiments.

```
roads_rendered:
  - "ffmpeg:roads#video=h264#width=1280#height=960#raw=-fpsmax 10#hardware=vaapi"
```

However, when defining a custom ffmpeg template in your go2rtc config (e.g. via Frigate's `config.yaml`, as described in the go2rtc documentation, you should find that hardware acceleration will work as expected.


Here's a custom ffmpeg template example based on Intel iGPU VAAPI hardware acceleration.

- In the Intel VAAPI example, ffmpeg requires us to pass specific device information and expects certain implementation-specific parameters to also be provided, such as `format`. You may need to define a similar ffmpeg template, with any other required paramters for AMD VAAPI.

```
go2rtc:
      ffmpeg:
            h264_vaapi": "-init_hw_device vaapi=intel:/dev/dri/renderD128 -filter_hw_device intel -c:v h264_vaapi -g 50 -bf 0 -profile:v high -an -vf format=vaapi|nv12,hwupload -level:v 4.1 -preset:v superfast -tune:v zerolatency <ADD YOUR ADDITIONAL FFMPEG PARAMETERS HERE>"

      streams:
            roads:
                  ...
            roads_rendered:
                  - ffmpeg:roads#video=h264_vaapi
```


You can find some additional info related to required hardware acceleration implementation details in the [go2rtc source](https://github.com/AlexxIT/go2rtc/blob/master/internal/ffmpeg/ffmpeg.go) definitions for ffmpeg presets.
