### DISCUSSION TITLE
Rock5B with M2 Coral Chip - some help with configs...

### DISCUSSION THREAD

**Discussion by cstrat** [blakeblackshear/frigate#7167] [Ask A Question] [answered]
Hey Frigators,

I just got everything setup tonight, seem to have it all working quite well, coral chip working really well!

Although I can't seem to get any hardware acceleration working for the decoding. As soon as I use anything in the config the ffmpeg crashes.
Just need some help with suggested `ffmpeg hwaccel_args` options because I know when I add more cameras it will be needed.

The docs have a suggested config for RPIs but not Rocks - does anyone have anything I can use?

<img width="991" alt="image" src="https://github.com/blakeblackshear/frigate/assets/4209076/5e2dbe03-6e81-44af-aea0-11b9d99bb413">

Also something else I have noticed, my recordings seem to often begin with large sections in green:

<img width="940" alt="image" src="https://github.com/blakeblackshear/frigate/assets/4209076/039c6c87-4f2f-40a1-809a-6b83cea1343a">

**Comment by NickM-27** [comment, marked as answer]
I don't know if hwaccel is supported for the device right now, there have been other discussions about it so I'd recommend checking it out. 

Also, frigate does not decode for the recordings so any artifacts like that are coming from the camera

**Reply by cstrat** [reply]
Hi Nick!

Thanks, I had a look through the discussions but couldn't find anything that worked - some discussion was quite old looking at earlier Radxa boards. I was hoping someone had this running and could share their config.

Given I don't have hwaccel working right now, I am best just using native res for detection then right?
This will just pass the video frame through to the Coral TPU.

Strange I'd never seen that green artifact before using the Reolink app. I think it might actually be the browser media player being funny. Will keep an eye on this.

**Reply by NickM-27** [reply]
The reolink app doesn't use rtsp so that's irrelevant, reolink is very well known for having glitches like that in their rtsp streams

**Reply by cstrat** [reply]
Ahh cheers, just assumed their app would use the same.
Thanks for clearing that up, I am still pretty impressed with the quality from the cameras - for the money spent.

**Reply by jbishop129** [reply]
Hi @cstrat , would you mind sharing how you were able to get your M.2 Coral working in Rock5, presumably Armbian 23.8? Mine is recognized under `lspci`, but I cannot get Google's Apex or Gasket drivers to install on aarch64, which I think is the problem. As a result, I have no `/dev/apex_0` device :(

**Reply by cstrat** [reply]
Honestly I don't remember what guide I followed, this is my bash history for when I got it up and running.
I am running Debian 11 (bullseye).

````
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
curl -sS https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/coral-edgetpu.gpg
sudo apt-get update
sudo apt-get install gasket-dkms libedgetpu1-std
sudo sh -c "echo 'SUBSYSTEM==\"apex\", MODE=\"0660\", GROUP=\"apex\"' >> /etc/udev/rules.d/65-apex.rules"
sudo groupadd apex
sudo adduser $USER apex
sudo reboot
lspci -nn | grep 089a
su -
ls /dev/apex_0
vi docker-compose.yml
````

docker compose is below.

````
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "250mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config:/config
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_USER: "xxxx"
      FRIGATE_RTSP_PASSWORD: "xxxx"
````

![image](https://github.com/blakeblackshear/frigate/assets/4209076/b8ed758f-3244-4d3d-bc3f-2653d98bccec)
