### DISCUSSION TITLE
Recording too short

### DISCUSSION THREAD

**Discussion by gregeeh** [blakeblackshear/frigate#7232] [Ask A Question] [answered]
Hi all,

I have Frigate, 12.1,  in a docker container on my OMV NAS.  Been away from home for 3 weeks now and received an email today saying motion was detected inside our home, where the camera is situated.

It was only my neighbour coming in to drop off some parcels that had been delivered.  However the Event showed 35 secs duration but the actual recording was only 9 secs long.  9 secs is really too short as I have a 15 sec pre event time setup..

What has happened and how can I stop this from happening again.

**Comment by hagak** [comment]
Check for warnings like this in the logs:
WARNING : Unable to keep up with recording segments in cache

**Comment by NickM-27** [comment]
> It was only my neighbour coming in to drop off some parcels that had been delivered. However the Event showed 35 secs duration but the actual recording was only 9 secs long. 9 secs is really too short as I have a 15 sec pre event time setup..

what is your config? if you only have it configured for motion or active objects then that is all that will be kept

**Reply by gregeeh** [reply]
Config and logs here:
[https://pastebin.com/raw/nM1uUMMe](url)

EVENT (AEST - GMT -10):  
20/7/23, 3:21:56 pm
-15h ago
( 35s )

**Reply by NickM-27** [reply]
you have a lot of errors in the logs with the recordings stream failing on your camera `tcp://192.168.10.70:554?timeout=5000000 failed: Connection timed out`

**Reply by gregeeh** [reply]
Could this be a Camera (Reolink) issue or something else?

**Reply by NickM-27** [reply]
yes, the docs recommend not using rtsp and instead using http-flv

**Reply by gregeeh** [reply]
This camera only has rtsp.

Did you note the event occured on 20th July and the latest date on the logs is 15th July.  Strange??

**Reply by NickM-27** [reply, marked as answer]
I did not notice that, in that case it is most likely just that your configuration is set to only keep segments with active_objects. The object was likely only visible for ~ 10 seconds so that is the only part of the recording that was kept

**Reply by gregeeh** [reply]
Is not the date being 5 days behind an issue?

How can I tell if only segments with active_objects is set in my config?

**Reply by NickM-27** [reply]
> Is not the date being 5 days behind an issue?

No, your config keeps events for 10 days

> How can I tell if only segments with active_objects is set in my config?

You just check your config? It is right there

```
        record:
            enabled: True
            events:
                pre_capture: 15
                post_capture: 5
                retain:
                    default: 10
                    mode: active_objects <- you are telling frigate to only keep recordings with active_objects
```
