### DISCUSSION TITLE
Restarting Frigate Docker container in Home Assistant

### DISCUSSION THREAD

**Discussion by stamandr** [blakeblackshear/frigate#7245] [Ask A Question]
Occasionally I need to restart my Frigate Docker container. I do this by logging in to the host and running "docker restart frigate"

Is there a way to do this in Home Assistant so that I can automate this command "docker restart frigate"  to restart my Frigate Docker container without having to log on to the host PC

Thanks....

**Comment by NickM-27** [comment]
Home assistant doesn't have a button yet, but you can easily just send an mqtt message on the topic `frigate/restart` and it will be restarted

**Reply by stamandr** [reply]
Can this automated in HA ? I'm not certain how to do this. Can you please give me an example ?  Thanks...

**Reply by NickM-27** [reply]
yes, just use the mqtt publish service

**Reply by stamandr** [reply]
Is this what it should look like ?

```
alias: Frigate Docker Container Restart
description: 
trigger: []
condition: []
action:
  - service: mqtt.publish
    data:
      topic: frigate/restart
mode: single
```

**Reply by Cold-Lemonade** [reply]
@stamandr I'd like to do the same thing. Did you get this working?

**Reply by stamandr** [reply]
Yes, I did. Create this automation

```
alias: (Frigate Docker Container Restart)
description: ""
trigger:
  - platform: time_pattern
    hours: /2
condition: []
action:
  - service: mqtt.publish
    data:
      topic: frigate/restart
mode: single
```
