### DISCUSSION TITLE
Detection triggered where IMO it should not happen

### DISCUSSION THREAD

**Discussion by bortek** [blakeblackshear/frigate#7246] [Ask A Question]
Hi

Can anyone explain how this is even possible? I have masked out motion like this

<img width="1134" alt="image" src="https://github.com/blakeblackshear/frigate/assets/9476606/e3dc08af-872e-44cf-a2f8-1e184774e4ce">

and created a zone like this

<img width="1121" alt="image" src="https://github.com/blakeblackshear/frigate/assets/9476606/f065247d-4f2a-4787-901d-05576cdd4396">

But regardless of that the objects passing by on the road are still triggering, like for example this one.

<img width="963" alt="image" src="https://github.com/blakeblackshear/frigate/assets/9476606/e33cfb3b-bba3-46d4-88e5-57eaedaf7c2d">

The car's bounding box and and not even close to the zone's area. 

Unfortunately there is little traffic on the road så I cannot sit and monitor the debug window, especially since this triggering happens quite seldom. Any ideas or suggestions?

I am running Frigate 0.11.1-2EADA21

**Comment by NickM-27** [comment]
1. Motion masks are not meant to be used to block out objects like that and they will cause issues, I would highly suggest removing the large motion mask on the street.
2. Zones do not stop events from being created unless they are made required for recordings and snapshots. You have not provided your config but I'd guess that this has not been done.

**Reply by bortek** [reply]
Reason for creating large motion mask on the street is because I am not interested in any traffic on the street. It's only a little slim portion of the driveway that I am interested in monitoring traffic on. Removing the large mask from the street should not actually not make any difference in detection but IMO it minimizes the load since a lot of "noise" on the street can be ignored.

My only zone is for the events to be created which saves snapshots and recordings since I need them.

In this particular case I understand why the motion was triggered regardless of the mask. There are other bushes and grass that was moving by the wind and triggered motion detection. But what I would like to understand is why the car which was outside of the zone somehow was detected. Do you have any clue why this happened. 

Here come my config

```
root@frigate:~# cat /frigate-config/config.yml
mqtt:
  host: 192.168.X.Y
  user: frigate
  password: PWD

# Enable this for TPU detectors
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  jo-frontside-1:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000
      inputs:
        - path: rtmp://192.168.X.176/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=PWD
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
      fps: 25
    motion:
      mask:
        - 1064,354,1099,418,1646,399,1958,429,2273,487,2560,557,2560,0,981,0
        - 1117,464,1152,647,1329,690,1503,647,1487,561,1437,497,1257,437
        - 2269,649,2560,844,2560,717,2560,614,2413,501,2324,485,2265,546,2103,518
    zones:
      zone_0:
        coordinates: 1089,1920,2560,1920,2560,1584,2560,1081,2560,623,2530,582,2331,495,2097,437,1809,406,1472,416,1070,414

  jo-driveway-1:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000
      inputs:
        - path: rtmp://192.168.X.150/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=PWD
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 25
    motion:
      mask:
        - 1557,351,1331,350,1151,371,1006,435,867,503,654,600,424,653,0,1021,0,380,0,0,1577,0
    zones:
      driveway_1:
        coordinates: 1555,369,1385,360,1217,395,1083,451,878,501,687,576,424,653,0,1037,0,1440,1514,1440

rtmp: # Restream RTMP to e.g. HASS, not now.
  enabled: true

record:
  enabled: true
  retain:
    days: 20
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 20
  expire_interval: 60

objects:
  track:
    - person
    - car
    - bicycle
    - bus
    - skis
    - snowboard

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: False
  retain:
    default: 30

timestamp_style:
  position: "tl"
  format: "%Y-%m-%d %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

birdseye:
  enabled: True
  width: 1920
  height: 1130
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

database:
  path: /media/frigate/frigate.db

logger:
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
    frigate.record: debug
```

**Reply by NickM-27** [reply]
> Reason for creating large motion mask on the street is because I am not interested in any traffic on the street. It's only a little slim portion of the driveway that I am interested in monitoring traffic on. Removing the large mask from the street should not actually not make any difference in detection but IMO it minimizes the load since a lot of "noise" on the street can be ignored.

I know why you are doing it and it is incorrect in frigate, the docs cover this clearly. This is what zones are for and the large motion mask will cause issues.

> In this particular case I understand why the motion was triggered regardless of the mask. There are other bushes and grass that was moving by the wind and triggered motion detection. But what I would like to understand is why the car which was outside of the zone somehow was detected. Do you have any clue why this happened.

Because you have not configured the zones to be required, like I said previously

**Reply by bortek** [reply]
I removed the motion mask and added required_zones . New config looks like but it is no good since events are triggered traffic passing by.


```
cameras:
  jo-frontside-1:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000
      inputs:
        - path: rtmp://192.168.2.176/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
      fps: 25
    objects:
      track:
        - person
        - car
        - bicycle
        - bus
        - skis
        - snowboard
    record:
      events:
        required_zones:
          - zone_0
    zones:
      zone_0:
        coordinates: 1089,1920,2560,1920,2560,1584,2560,1081,2560,623,2530,582,2331,495,2097,437,1809,406,1472,416,1070,414

  jo-driveway-1:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000
      inputs:
        - path: rtmp://192.168.2.150/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 25
    objects:
      track:
        - person
        - car
        - bicycle
        - bus
        - skis
        - snowboard
    record:
      events:
        required_zones:
          - driveway_1
    zones:
      driveway_1:
        coordinates: 1555,369,1385,360,1217,395,1083,451,878,501,687,576,424,653,0,1037,0,1440,1514,1440

rtmp: # Restream RTMP to e.g. HASS, not now.
  enabled: true

record:
  enabled: true
  retain:
    days: 20
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 20
  expire_interval: 60

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: False
  retain:
    default: 30

timestamp_style:
  position: "tl"
  format: "%Y-%m-%d %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

birdseye:
  enabled: True
  width: 1920
  height: 1130
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

database:
  path: /media/frigate/frigate.db

logger:
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
    frigate.record: debug
```

**Reply by NickM-27** [reply]
You only made the zone required for recordings, not snapshots. You need to make it required for snapshots as well.

I also notice that you are running detect at 25 fps, this is a waste of resources and not recommended. The fps variable there does not need to match the cameras fps. The default and generally recommended detect fps is 5

**Reply by bortek** [reply]
changed detect fps to 5 and added snapshots. It seems to have calmed down. :) Let me monitor it for a while. But I still don't understand the logic here and why motion masks should not be used. Perhaps time to watch some videos explaining all that. Any tip for a favourite one? :) 

```
    record:
      events:
        required_zones:
          - zone_0
    snapshots:
      required_zones:
        - zone_0
```
