### DISCUSSION TITLE
Hardware acceleration intel mini pc celeron j4125

### DISCUSSION THREAD

**Discussion by Triskelen** [blakeblackshear/frigate#7254] [General]
Hey 

I'm running HAOS on a intel mini pc celeron J4125 and frigate keeps telling me i should activated hardware acceleration .
but when ever i try that the system doesn't work anymore i read there is a problem with the J4125 and that i should add LIBVA_DRIVER_NAME=i96 to my config file so i tried adding it to my config file 

```
environment_vars:
  LIBVA_DRIVER_NAME=i96
```
  
```
Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1083, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
environment_vars
  value is not a valid dict (type=type_error.dict)
```

**Comment by NickM-27** [comment]
That is not the correct format, it should be

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: i965
```

**Reply by Triskelen** [reply]
Oh indeed in my haste of past copy it seemed i did not copy the whole thing

and after i should add:
```
ffmpeg:
  hwaccel_args: preset-vaapi
```

**Comment by Triskelen** [comment]
I got the hardware accelerator working after i disabled safe mode for the addon in HAOS

now my cpu went from 40% to 60% while running frigate thought this would lower the cpu usage not increase it

edit: removed the hardware acceleration CPU went to 90% and above

**Reply by NickM-27** [reply]
So is it higher or lower without hwaccel?

**Reply by Triskelen** [reply]
just with hwaccel it's about the same as before

when i add the hardware accelerator it hits 90% and up eassy
thought with acces to my GPU the cpu load would go down not up

**Reply by NickM-27** [reply]
What's your whole config, which camera, etc?

**Reply by Triskelen** [reply]
```
mqtt:
  host: XXX.XXX.XXX.XXX
  port: 1883
  user: XXXX
  password: XXXX
  topic_prefix: frigate

environment_vars:
  LIBVA_DRIVER_NAME: i965

birdseye:
  enabled: False

cameras:
  woonkamer:
    ffmpeg:
      inputs:
        - path: rtsp://XXX
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 25
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 10
        required_zones:
          - "woonkamer_area"
    mqtt:
      required_zones:
        - "woonkamer_area"
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - woonkamer_area
      retain:
        default: 15
        objects:
          person: 20
    motion:
      mask:
        - 303,0,304,28,0,36,0,0
        - 0,801,0,1080,1920,1080,1920,792
    zones:
      woonkamer_area:
        coordinates: 0,819,1920,796,1920,73,0,70
        objects:  
          - person
        filters:
            person:
              threshold: 0.5


  keuken:
    ffmpeg:
      inputs:
        - path: rtsp://XXX
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 25
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - keuken_area
    motion:
      mask:
        - 0,0,635,0,635,1080,0,1080
        - 633,0,626,84,788,102,975,124,1212,158,1523,227,1920,129,1920,0
    zones:
      keuken_area:
        coordinates: 1920,0,1920,1080,631,1080,635,0
        objects:  
          - person
          - cat
        filters:
            person:
              threshold: 0.5



objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
  filters:
      person:
          min_area: 5000
          max_area: 100000  
```

This is my full config running with 2 Foscam C2M
on a intel minipc celeron j4125 8gb RAM 256 Gb M.2
