### DISCUSSION TITLE
WebRTC not working in frigate WebUI but the link from go2RTC work

### DISCUSSION THREAD

**Discussion by janusn** [blakeblackshear/frigate#7258] [Ask A Question]
I have a frigate set up with 3 cameras, 2 rtsp streams from each.

Strangely, the WebRTCs does not work on the frigate WebUI but they work fine on the go2RTC link on Google Chrome.

The MSEs work fine.

The environment:

- NUC13 with Intel iCore 1340P
- Coral TPU
- 32GB RAM
- Host OS: Ubuntu 23.04 64bit / Linux 6.2.0-25-generic
- Docker version: 24.0.4, build 3713ee1
- frigate version: 0.12.1-367D724

compose.yaml
```
---
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # It is for gathering GPU Load inside the container.
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "352mb" # update for your cameras based on calculation above
    devices:
      - "/dev/dri:/dev/dri"
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions linux
    volumes:
      - ./config/config.yaml:/config/config.yaml:rw
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/cctv/frigate:/media/frigate:rw
      - /tmp:/tmp/cache:rw
    ports:
      - "5000:5000" # WebUI
      - "8554:8554" # RTSP feeds Default 8554 is used by container homeassistant-ring-mqtt
      - "8555:8555/tcp" # WebRTC over tcp 
      - "8555:8555/udp" # WebRTC over udp
```

configuration.yaml
```
mqtt:
  enabled: True
  host: 10.27.0.50
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: [removed]
  password: [removed]
  stats_interval: 5
  
detectors:
   coral:
     type: edgetpu
     device: usb

# Include all cameras by default in Birdseye view
birdseye:
  enabled: False
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

objects:
  track:
    - person
    - dog
    - cat

go2rtc:
  rtsp:
    username: [removed]
    password: [removed]

  webrtc:
    listen: ":8555"
    candidates:
      - 10.27.0.50:8555
      - stun:8555

  streams:

    # stream backyard =======================================================================
    backyard:
      - rtsp://frigate:d7mA4rVJJ@10.27.0.203:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:backyard#audio=opus" # required by WebRTC
    backyard_sub:
      - rtsp://frigate:d7mA4rVJJ@10.27.0.203:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:backyard_sub#audio=opus" # required by WebRTC

    # stream frontyard ======================================================================
    frontyard:
      - rtsp://frigate:d7mA4rVJJ@10.27.0.202:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:frontyard#audio=opus" # required by WebRTC
    frontyard_sub:
      - rtsp://frigate:d7mA4rVJJ@10.27.0.202:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:frontyard_sub#audio=opus" # required by WebRTC

    # stream shed ===========================================================================
    shed:
      - rtsp://frigate:d7mA4rVJJ@10.27.0.206:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:shed#audio=opus" # required by WebRTC
    shed_sub:
      - rtsp://frigate:d7mA4rVJJ@10.27.0.206:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:shed_sub#audio=opus" # required by WebRTC
      
cameras:
  # Camera ========================== Backyard =============================================
  backyard: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://[removed]
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://[removed]
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: backyard # default main channel for live stream
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      events:
        pre_capture: 7
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 60 # default 10 days
          mode: motion
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        default: 60
    motion:
      mask:
        - 1280,0,1280,304,1173,352,1100,324,1046,201,906,219,857,80,884,0
        - 0,225,53,82,105,67,116,0,0,0
        - 606,93,829,80,837,0,159,0,162,135
    objects:
      track:
        - person
        
  # Camera ========================== Frontyard =============================================
  frontyard: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://[removed]
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://[removed]
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: frontyard # default channel for live stream
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      events:
        pre_capture: 7
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 60 # default 10 days
          mode: motion
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 60
    motion:
      mask:
        - 233,0,371,211,0,395,0,0
        - 1226,561,1259,297,1236,59,1178,0,1280,0,1280,720,1092,720
        - 999,64,1215,68,1217,29,995,25
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask:
            - 0,372,0,461,121,399,136,353,319,280,363,315,413,289,390,247,320,239

  # Camera ========================== Shed ==================================================
  shed: # <------ Name the camera
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://[removed]
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://[removed]
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: shed # default main channel for live stream
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      events:
        pre_capture: 7
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 60 # default 10 days
          mode: motion
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 60
    motion:
      mask:
        - 0,720,155,720,600,298,576,182,523,109,705,77,685,0,503,0,0,0
        - 1229,70,1223,0,1000,0,1005,67
    objects:
      track:
        - person
```

Go2rtc log:
```
2023-07-23 14:02:40.746869749  [INFO] Preparing go2rtc config...
2023-07-23 14:02:40.916105812  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-07-23 14:02:40.948029294  [INFO] Starting go2rtc...
2023-07-23 14:02:41.026217936  14:02:41.026 INF go2rtc version 1.2.0 linux/amd64
2023-07-23 14:02:41.026416721  14:02:41.026 INF [api] listen addr=:1984
2023-07-23 14:02:41.026642680  14:02:41.026 INF [rtsp] listen addr=:8554
2023-07-23 14:02:41.026887915  14:02:41.026 INF [srtp] listen addr=:8443
2023-07-23 14:02:41.027083439  14:02:41.027 INF [webrtc] listen addr=:8555
2023-07-23 14:02:50.750306823  [INFO] Starting go2rtc healthcheck service...
```

The output of chrome://media-internals/ for a working WebRTC
<img width="688" alt="Screen Shot 2023-07-23 at 3 09 37 pm" src="https://github.com/blakeblackshear/frigate/assets/21253783/682e6295-7457-4c45-a2d0-7d4fef468070">

The output of chrome://media-internals/ for a non-working WebRTC
<img width="694" alt="Screen Shot 2023-07-23 at 3 11 32 pm" src="https://github.com/blakeblackshear/frigate/assets/21253783/cf478a48-1434-4872-ac55-722293384971">

The output of chrome://media-internals/ for a MSE
<img width="2560" alt="Screen Shot 2023-07-23 at 3 15 52 pm" src="https://github.com/blakeblackshear/frigate/assets/21253783/6ca4c1c7-83dc-4adc-bd86-e143a30fa1e6">
