### DISCUSSION TITLE
Using Frigate behind Traefik with basicauth

### DISCUSSION THREAD

**Discussion by shred86** [blakeblackshear/frigate#7262] [Ask A Question]
I setup Traefik a few months back with basicauth for Frigate. One "issue" I've noticed is I have to basically authenticate whenever I change to a new page in Frigate. Anyone tips on how to setup Traefik basicauth with Frigate to just ask for authentication once, and not require authentication whenever I change pages?

I'm using labels in my docker-compose for Frigate which looks like this for the Frigate container:

````yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.mydomain.com`)"
      - "traefik.http.routers.frigate.entrypoints=websecure"
      - "traefik.http.routers.frigate.tls.certresolver=cloudflare"
      - "traefik.http.routers.frigate.middlewares=traefik-auth"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
````

Commands and labels for my Traefik container:

````yaml
    command:
      - "--api.dashboard=true"
      - "--accesslog=false"
      - "--providers.file.filename=/services.yml"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--serversTransport.insecureSkipVerify=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.cloudflare.acme.email=user@email.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.http.tls.domains[0].main=mydomain.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.mydomain.com"
      - "--entrypoints.websecure.http.tls.certresolver=cloudflare"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=username:password"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mydomain.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
````
