### DISCUSSION TITLE
coral tpu 10ms inference and still skipping frames

### DISCUSSION THREAD

**Discussion by cdblind** [blakeblackshear/frigate#7269] [Ask A Question]
Hi
I am not sure what is my problem, I have a dell mini PC i5 7500T 8GB ram 2 GB NVME, and it was working fine with 3 cameras (2 2k and 1 4k) but decided to bye a Coral TPU (USB). The inference speed is between 9.5ms and 10.5ms, but detector still skips frames pretty regularly. I am just about to change back to using the iGPU. I have tried changing the detector ratios to 1280x720 and no difference except the detection seems to be slower at those ratios, as Alarmo on my HA takes about an extra 30 seconds or more to activate the alarm using the binary sensors from Frigate. Frigate and HA are on separate PC's. I also get regular Frigate warnings "frigate.output WARNING : Unable to copy frame to carxxxxxxxxxxxxxx birdseye". Anyone have any idea what's going on?

My config:
```
# Frigate needed settings
mqtt:
  host: 192.168.xx.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 60
database:
  path: /db_frigate/frigate.db
detectors:
  coral:
    type: edgetpu
    device: usb  
go2rtc:
  streams:
    front:
      - rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/live0
    car:
      - rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/live0
    back:
      - rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/live0
  webrtc:
    candidates:
      - 192.168.xx.xx:8555
      - stun:8555
ffmpeg:
  hwaccel_args: preset-vaapi
# Camera settings
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/101
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
      # enabled: True    
    record:
      events:
        required_zones:
          - back_zone            
    zones:
      back_zone:
        coordinates: 154,247,197,360,351,360,356,128,284,78,225,84,182,66,136,83
        objects:
          - person
    ui:
      order: 20
  front:
    ffmpeg:
      inputs:
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/101
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
      # enabled: True    
    record:
      events:
        required_zones:
          - front_zone    
    zones:
      front_zone:
        coordinates: 126,360,586,303,449,270,353,172,110,234
        objects:
          - person
    ui:
      order: 0
  car:
    ffmpeg:
      inputs:
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@192.168.xx.xx:554/Streaming/Channels/101
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5      
    record:
      events:
        required_zones:
          - car_zone            
    zones:
      car_zone:
        coordinates: 187,339,640,331,640,242,578,104,309,23,59,111
        objects:
          - person
    ui:
      order: 10
# Global settings
#logger:
  #default: debug
rtmp:
  enabled: False
objects:
  track:
    - person
record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 30
    post_capture: 15    
    retain:
      default: 14
      # objects:
        # person: 14        
live:
  height: 720
  quality: 5
birdseye:
  enabled: True
  quality: 5
  mode: continuous
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  height: 500
  retain:
    default: 14
ui:
  live_mode: webrtc
  time_format: 24hour
  date_style: short
  time_style: medium
```
