### DISCUSSION TITLE
PTZ in frigate

### DISCUSSION THREAD

**Discussion by joelegg** [blakeblackshear/frigate#7292] [General]
i'm excited to see this was merged in recently. I am on 12.1 and have a Hikvision ptz i'm keen to try this with (built in tracking sucks!) 

I have this in my config:
```
  Front_PTZ:
    ffmpeg:
      inputs:
        - path: rtsp://xxx
          roles:
            - record
        - path: [xxx](rtsp://xxx)
          roles:
            - detect
            - rtmp
    onvif:
      host: xxx.xxx.xxx.xxx
      port: 8000
      user: user
      password: password
    detect:
```

but frigate doesn't like the config - it fails saying it's invalid. Not sure what i'm doing wrong. i have the onvif enabled on the hikvision camera. 

onvif
2023-07-25 22:42:56.641260305    extra fields not permitted (type=value_error.extra)

thank you
