### DISCUSSION TITLE
When the network share goes offline...

### DISCUSSION THREAD

**Discussion by PyrokineticDarkElf** [blakeblackshear/frigate#7351] [Ask A Question] [answered]
I noticed the other week, after goofing up my NAS temporarily, that when the network share for storage gets unmounted or isn't mounted at boot, Frigate will create a directory /mnt/frigate and use up all the host storage.

I've done some searching and from what I gather, the container could be prevented from booting using a script, if the mount directory is not already present. I'm a little out of my depth here as I've not tried setting up scripts in a Docker compose file before. Is there any documentation on this or a resource someone might recommend?

**Comment by phabibjr** [comment]
I had a race condition where Frigate would start before fstab would mount my SMB shares causing the host drive to fill. 

I switched from mounting via fstab to a systemd.mount units and changed the docker ststemd file to require the systemd mount so docker wouldn’t start until the SMB shares mounted. 

I also made the mount folder immutable using chattr +i command so if the share mount fails no files can be written to that folder. This will keep the host system disk from filling up with recordings.

**Reply by PyrokineticDarkElf** [reply]
Thanks for the quick response! Sorry I couldn't offer the same haha
This seems viable but I've decided to follow @erkexzcx's method as I find it easier to have all my config in the compose file.

**Comment by erkexzcx** [comment, marked as answer]
Some time ago I've been messing with network shares and fstab. I always ended up spending more time than I should, while the actual fix is very easy and always work.

The secret of getting it to work perfectly is:

1. Use NFS storage instead of Samba. It is generally faster.
2. Tune NFS parameters. Below is what I am using to store recordings/events to my Synology NAS.
3. **Mount NFS storage using docker-compose (docker) and not host's fstab or host's mount.** Docker will handle connection to NFS and personally I never had such case when NFS is not mounted, but application still works.

Here is how my (relevant parts of) `docker-compose.yml` look like:
```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb" # I guess 2G Should be more than enough
    volumes:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml # my Frigate config
      - ./frigate/db:/db # This must be on local storage
      - frigate:/media/frigate # This is using below NFS volume
      - ./frigate/labelmap.txt:/labelmap.txt # I renamed/combined some object types
      - type: tmpfs # Optional: 4GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      - "5000:5000" # WebUI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

volumes:
  frigate:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.123,rsize=32768,wsize=32768,hard,timeo=600,retrans=2,noresvport,nconnect=16,vers=4.1"
      device: ":/volume2/frigate"
```

**Reply by PyrokineticDarkElf** [reply]
This seems to be working for me! I'm not using NFS and don't plan to at the minute. That being said, if you think the speed improvements are worthwhile, I might have to give it a go.

I modified the compose file to work with cifs:

```
volumes:
  frigate:
    driver_opts:
      type: "cifs"
      o: "username=myUsername,password=myPassword,iocharset=utf8,file_mode=0777,dir_mode=0777"
      device: "//192.168.0.123/Frigate"
```

Really appreciate the help with this!
