### DISCUSSION TITLE
How to apply ffmpeg -vf filter to rtsp input stream?

### DISCUSSION THREAD

**Discussion by jerblack** [blakeblackshear/frigate#7390] [Ask A Question] [answered]
I am using Frigate with RTSP cameras, and one of them is pointing out my front door at a bright light that I can't control. I figured out how to take a clip of the video from the camera and use the ffmpeg drawbox filter to create translucent boxes over the light so it's not so bright. Here's how I do that with ffmpeg:

```
ffmpeg -y -i input.mp4 -vf "drawbox=x=1470:y=0:w=450:h=250:color=black@0.70:t=fill, drawbox=x=1250:y=0:w=1000:h=450:color=black@0.30:t=fill, drawbox=x=1370:y=0:w=820:h=340:color=black@0.50:t=fill" -r 15 -c:a aac output.mp4
```

My question is how do I apply that same filter to the incoming RTSP stream so that when the stream is seen anywhere (record, detect, web UI, HA) they all have that ffmpeg video filter pre-applied. Thanks.

**Comment by NickM-27** [comment]
You would want to do this in go2rtc so the work only needs to be done once, and then use that stream in frigate

**Comment by jerblack** [comment, marked as answer]
Ok cool, I was able to make that work. Thanks.

```
go2rtc:
  streams:
    front_door:
      - 'ffmpeg:rtsp://----:----@10.--.--.--:554/stream1#video=h264#audio=aac#raw=-vf "drawbox=x=1470:y=0:w=450:h=250:color=black@0.70:t=fill,drawbox=x=1250:y=0:w=1000:h=450:color=black@0.30:t=fill,drawbox=x=1370:y=0:w=820:h=340:color=black@0.50:t=fill"'

cameras:
  front_door:
    birdseye:
      order: 6
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
        - 348,283,345,165,353,41,415,41,418,0,112,0,0,0,0,407
```
