### DISCUSSION TITLE
Enabled/Disabled the camera by a button on home assistant

### DISCUSSION THREAD

**Discussion by Sirioux** [blakeblackshear/frigate#7393] [Ideas]
When my alarm goes off, my indoor camera closes and cuts off the rtsp stream.
But Frigate is still looking for the rtsp stream.

2023-08-04 20:33:08.874749437  [INFO] Starting Frigate...
2023-08-04 20:33:10.619248661  [2023-08-04 22:33:10] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-04 20:33:10.665846325  [2023-08-04 22:33:10] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-04 20:33:10.666498288  [2023-08-04 22:33:10] peewee_migrate                 INFO    : Starting migrations
2023-08-04 20:33:10.672344323  [2023-08-04 22:33:10] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-04 20:33:10.789307328  [2023-08-04 22:33:10] detector.cpu1                  INFO    : Starting detection process: 227
2023-08-04 20:33:10.812771278  [2023-08-04 22:33:10] frigate.app                    INFO    : Output process started: 231
2023-08-04 20:33:10.823096913  [2023-08-04 22:33:10] detector.cpu2                  INFO    : Starting detection process: 229
2023-08-04 20:33:10.823102922  [2023-08-04 22:33:10] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-08-04 20:33:10.824183820  [2023-08-04 22:33:10] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-08-04 20:33:10.827352095  [2023-08-04 22:33:10] frigate.app                    INFO    : Camera processor started for garage: 233
2023-08-04 20:33:10.832637811  [2023-08-04 22:33:10] frigate.app                    INFO    : Camera processor started for salon: 234
2023-08-04 20:33:10.841644456  [2023-08-04 22:33:10] frigate.app                    INFO    : Capture process started for garage: 236
2023-08-04 20:33:10.854408540  [2023-08-04 22:33:10] frigate.app                    INFO    : Capture process started for salon: 237
2023-08-04 20:33:16.232088818  [2023-08-04 22:33:16] frigate.video                  ERROR   : salon: Unable to read frames from ffmpeg process.
2023-08-04 20:33:16.232359809  [2023-08-04 22:33:16] frigate.video                  ERROR   : salon: ffmpeg process is not running. exiting capture thread...
2023-08-04 20:33:26.223527861  [2023-08-04 22:33:26] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/salon-20230804223321.mp4
2023-08-04 20:33:30.944356918  [2023-08-04 22:33:30] watchdog.salon                 ERROR   : Ffmpeg process crashed unexpectedly for salon.
2023-08-04 20:33:30.944365030  [2023-08-04 22:33:30] watchdog.salon                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-08-04 20:33:30.944367118  [2023-08-04 22:33:30] ffmpeg.salon.detect            ERROR   : [rtsp @ 0x55bb75e72c40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2023-08-04 20:33:30.944372932  [2023-08-04 22:33:30] ffmpeg.salon.detect            ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2023-08-04 20:33:30.944391732  [2023-08-04 22:33:30] ffmpeg.salon.detect            ERROR   : Output file #0 does not contain any stream
2023-08-04 20:33:30.966300116  [2023-08-04 22:33:30] ffmpeg.salon.record_rtmp       ERROR   : [rtsp @ 0x557675320d80] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2023-08-04 20:33:30.966304201  [2023-08-04 22:33:30] ffmpeg.salon.record_rtmp       ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2023-08-04 20:33:30.966307870  [2023-08-04 22:33:30] ffmpeg.salon.record_rtmp       ERROR   : Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 0, only the last option '-c:a aac' will be used.
2023-08-04 20:33:30.966309569  [2023-08-04 22:33:30] ffmpeg.salon.record_rtmp       ERROR   : rtsp://192.168.x.58:8554/camera.salon: Connection timed out
2023-08-04 20:33:30.966736815  [2023-08-04 22:33:30] watchdog.salon                 INFO    : Terminating the existing ffmpeg process...
2023-08-04 20:33:30.966738354  [2023-08-04 22:33:30] watchdog.salon                 INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-04 20:33:36.330954282  [2023-08-04 22:33:36] frigate.video                  ERROR   : salon: Unable to read frames from ffmpeg process.
2023-08-04 20:33:36.330957523  [2023-08-04 22:33:36] frigate.video                  ERROR   : salon: Unable to read frames from ffmpeg process.
2023-08-04 20:33:36.331827800  [2023-08-04 22:33:36] frigate.video                  ERROR   : salon: Unable to read frames from ffmpeg process.
2023-08-04 20:33:36.331830525  [2023-08-04 22:33:36] frigate.video                  ERROR   : salon: ffmpeg process is not running. exiting capture thread...

It would be cool to have the possibility to switch the camera to disabled with a button

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/1911

**Reply by Sirioux** [reply]
I read wide and across the #1911 but I don't understand how to do it..
My English may be limited

Frigate Config : 
```
  salon:
    enabled: true
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://xxx.xxx.x.xxx:xxxx/camera.salon
          input_args: preset-rtsp-restream
          roles: 
            - record
            - rtmp
        - path : rtsp://xxx.xxx.x.xxx:xxxx/camera.salon_sub
          input_args: preset-rtsp-restream
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 859,90,1280,90,1280,0,874,0
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
    rtmp:
      enabled: false
```

I tried with:

```
input_boolean:
  toggle_frigate_camera:
    name: Basculer Caméra Frigate
    initial: off
    icon: mdi:camera
```

```
automation:
  - alias: Désactiver Caméra Frigate
    trigger:
      platform: state
      entity_id: input_boolean.toggle_frigate_camera
      to: 'off'
    action:
      - service: mqtt.publish
        data:
          topic: "frigate/config"
          retain: true
          payload: |-
            {
              "cameras": {
                "salon": {
                  "enabled": false,
                  ...  # Autres paramètres de configuration de votre caméra
                }
              }
            }

```

But it doesn't work
