### DISCUSSION TITLE
Frigate Docker + Home Assistant Sensors not updating

### DISCUSSION THREAD

**Discussion by cloudbr34k84** [blakeblackshear/frigate#7402] [General]
It appears none of my frigate sensors in Home Assistant are updating. below is my frigate config file. for mqtt. I know its connected because when I create zones in frigate they are then created as devices in HA. but for example, car counts, and person counts are not tallying up per say. Also, the because it creates a camera. entity for each object and it has the last image for that object, this isn't being updated as well

my mqtt integration is also being used by Zigbee2mqtt, does that matter?

```
mqtt:
  host: xxx.xxx.xx.xx - this is my HA IP address
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: xxxxxxxxx
  stats_interval: 60
  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt
  enabled: true
```

![image](https://github.com/blakeblackshear/frigate/assets/58960644/30ba6767-9607-4ed2-84cb-13bea8224717)
