### DISCUSSION TITLE
0% CPU on my Coral TPU

### DISCUSSION THREAD

**Discussion by lipcikm** [blakeblackshear/frigate#7407] [Ask A Question]
Hello,

I've noticed that my HA is running high CPU, I related this to Frigate. After spending some time troubleshooting, I've noticed that issue was somewhere else. 

When reviewing the configuration, I've noticed my Frigate interface showing CPU 0% usage on Coral TPU. Seems that my RPi4 is running the show. 

![BD09A9F0-C1F7-4135-98CA-2EB6A62B1D2E](https://github.com/blakeblackshear/frigate/assets/102188607/29d27530-8ecb-4a82-9234-ebb22767d01e)

RPi4 is running on 2023.8.1 with OS version 10.4 and in total 5 cameras connected to Frigate. In the example bellow, I only provide one camera as the other 4 are similar. 

```
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
# ----------------------------------------------------
  Vchod:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.xx.yyy:5541/1
          roles:
            - detect
        - path: rtsp://admin:xxxxxxxx@192.168.xx.yyy:5541/0
          roles:
            - record
            #- restream
            #- rtmp
    rtmp:
      enabled: False
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - vstup_zone
          - ulicka_zone
        retain:
          default: 30
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      required_zones:
        - vstup_zone
        - ulicka_zone
      retain:
        default: 5
    objects:
      track:
        - cat
        - person
      filters:
        cat:
          min_score: 0.4
          threshold: 0.6
    zones:
      vstup_zone:
        coordinates: 203,181,220,351,183,350,184,408,145,355,157,401,127,431,180,480,265,434,315,480,527,480,428,275,317,161
        objects:
          - person
          - cat
      ulicka_zone:
        coordinates: 541,378,581,480,650,434,485,192,396,140,348,163,471,248
        objects:
          - person
          - cat
    motion:
      threshold: 20
      mask:
        - 0,27,279,25,281,0,0,0
        - 157,480,0,480,0,0,129,0,116,89,115,250,113,355,139,408,130,452
        - 175,0,404,0,403,143,186,178
        - 598,161,720,360,720,0,457,0
    detect:
      width: 720
      height: 480
      fps: 5
```

![E92409CE-B6E4-4DE2-A437-0104B7DAACF7](https://github.com/blakeblackshear/frigate/assets/102188607/4c6b2510-6cc0-4841-a2ec-7449cd32fa43)

Frigate CPU load:
![image](https://github.com/blakeblackshear/frigate/assets/102188607/bf7740cc-7908-4860-9978-e20915c56e70)

RPi4 load:
![image](https://github.com/blakeblackshear/frigate/assets/102188607/678f1ad6-6a8c-4215-a322-a6f005334ec5)

Any help is welcomed :)
