### DISCUSSION TITLE
Setup ok or not?

### DISCUSSION THREAD

**Discussion by Sirioux** [blakeblackshear/frigate#7433] [General]
Hi !

I am new to Frigate CCTV on HA.
But also in English because I am French aha..
I wanted to get opinions. Know whether or not the configuration is relevant? 
If you have any improvements I'm a taker :)

I am with IMOU cameras in H264
My HA Frigate configuration is running on a Windows computer with a virtual machine.

I am in detection on the substream and in live/record on the high stream

Thank you very much for Frigate and thank you for sharing

```
#################  config.yml ##########################

mqtt:
  host: 192.168.1.XXX
  user: mqtt-XXX
  password: XXX

go2rtc:
  streams:
    camera.garage: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.200:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.garage#audio=opus
    camera.garage_sub: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.200:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.garage_sub#audio=opus
    camera.salon: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.salon#audio=opus
    camera.salon_sub: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.201:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.salon_sub#audio=opus
    camera.entree: 
      - rtsp://xxx:xxx@192.168.1.202:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.entree#audio=opus
    camera.entree_sub:
      - rtsp://xxx:xxx@192.168.1.202:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.entree_sub#audio=opus
    camera.jardin: 
      - rtsp://xxx:xxx@192.168.1.203:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.jardin#audio=opus
    camera.jardin_sub:
      - rtsp://xxx:xxx@192.168.1.203:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.jardin_sub#audio=opus

cameras:
  garage:
    enabled: true
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.garage
          input_args: preset-rtsp-restream
          roles: 
            - record
            - rtmp
        - path : rtsp://127.0.0.1:8554/camera.garage_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
    rtmp:
      enabled: false

  salon:
    enabled: true
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.salon
          input_args: preset-rtsp-restream
          roles: 
            - record
            - rtmp
        - path : rtsp://127.0.0.1:8554/camera.salon_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
    rtmp:
      enabled: false

  entree:
    enabled: true
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.entree
          input_args: preset-rtsp-restream
          roles: 
            - record
            - rtmp
        - path : rtsp://127.0.0.1:8554/camera.entree_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
        - 529,586,451,631,446,661,352,667,351,634,450,532,525,532
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
    rtmp:
      enabled: false

  jardin:
    enabled: true
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.jardin
          input_args: preset-rtsp-restream
          roles: 
            - record
            - rtmp
        - path : rtsp://127.0.0.1:8554/camera.jardin_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
    rtmp:
      enabled: false

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

birdseye:
  enabled: true
  restream: false
  mode: continuous
  width: 1280
  height: 720
  quality: 8

##########################################################################
```

**Comment by NickM-27** [comment]
You can remove the `input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1` from the configs, it is doing nothing because you are overriding the input args at the stream level

Should still be using the restream preset for the sub streams as well

You can remove the `- rtmp` role from each camera because it is not being used. You can also remove the rtmp -> enabled from each camera because `false` is the default

**Comment by Sirioux** [comment]
Thank you very much for your response !
I just edited the code with your adjustments.
I hope I haven't forgotten anything.

I don't know if you saw it as I edited the code when I saw your answer, but I also have "cpus" hope it can't slow down the processing of the video stream

```
#################  config.yml ##########################

mqtt:
  host: 192.168.1.XXX
  user: mqtt-XXX
  password: XXX

go2rtc:
  streams:
    camera.garage: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.200:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.garage#audio=opus
    camera.garage_sub: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.200:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.garage_sub#audio=opus
    camera.salon: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.salon#audio=opus
    camera.salon_sub: # <- for RTSP streams
      - rtsp://xxx:xxx@192.168.1.201:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.salon_sub#audio=opus
    camera.entree: 
      - rtsp://xxx:xxx@192.168.1.202:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.entree#audio=opus
    camera.entree_sub:
      - rtsp://xxx:xxx@192.168.1.202:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.entree_sub#audio=opus
    camera.jardin: 
      - rtsp://xxx:xxx@192.168.1.203:554/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:camera.jardin#audio=opus
    camera.jardin_sub:
      - rtsp://xxx:xxx@192.168.1.203:554/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio
      - ffmpeg:camera.jardin_sub#audio=opus

cameras:
  garage:
    enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.garage
          input_args: preset-rtsp-restream
          roles: 
            - record
        - path : rtsp://127.0.0.1:8554/camera.garage_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects

  salon:
    enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.salon
          input_args: preset-rtsp-restream
          roles: 
            - record
        - path : rtsp://127.0.0.1:8554/camera.salon_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects

  entree:
    enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.entree
          input_args: preset-rtsp-restream
          roles: 
            - record
        - path : rtsp://127.0.0.1:8554/camera.entree_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
        - 529,586,451,631,446,661,352,667,351,634,450,532,525,532
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects

  jardin:
    enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera.jardin
          input_args: preset-rtsp-restream
          roles: 
            - record
        - path : rtsp://127.0.0.1:8554/camera.jardin_sub
          input_args: preset-rtsp-generic
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_ratio: 0.5
          max_ratio: 2.0
          min_score: 0.5
          threshold: 0.6
          mask: 640,0
    motion:
      mask: 
        - 879,41,1228,38,1223,71,883,68
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
      crop: false
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

birdseye:
  enabled: true
  restream: false
  mode: continuous
  width: 1280
  height: 720
  quality: 8

##########################################################################
```
