### DISCUSSION TITLE
Cannot play downloaded clips in VLC

### DISCUSSION THREAD

**Discussion by Kofl** [blakeblackshear/frigate#7479] [General]
Hi,

running latest Frigate and everything works fine so far, but when I download the clips from Frigate, VLC is unable to play it (Hikvision camera).

No error message, pressing play immediately changes to stop again.

Opening the video camera stream directly in VLC works fine with all provided video streams. The clip also plays fine in the browser.

Thanks for any hint.

```
mqtt:
  host: 10.x.0.xx
  user: mqttlogin
  password: secretxyz
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Ostbalkon:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xy@10.y.0.yy:554/Streaming/channels/202
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:xy@10.y.0.yy:554/Streaming/channels/101
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: True
      events:
        pre_capture: 20
        post_capture: 30
    snapshots:
      enabled: True
    objects:
      filters:
        bird:
          mask:
            - 117,720,329,644,253,449,27,516
        person:
          mask:
            - 886,340,669,469,303,423,368,324

objects:
  track:
    - person
    - bird
```

**Comment by Kofl** [comment]
Sovled via:

```
cameras:
  Ostbalkon:
    ffmpeg:
      inputs:
     .....
      output_args:
          record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -pix_fmt yuv420p -an 
```
