### DISCUSSION TITLE
Reolink person detection better then Frigate?

### DISCUSSION THREAD

**Discussion by fbloemhof** [blakeblackshear/frigate#7482] [Ask A Question]
I'm new to Frigate (and camera's in general). I have an Reolink doorbell (on wifi) and an Reolink RLC-520A (PoE) running, both integrated in Frigate. Also added an Coral TPU (via USB) to the Frigate host. Running Frigate in a Docker on a Dell Optiplex 3020 (i3-4160T). Everything seems to run smoothly.

After some testing I started to notice that the Reolink built-in person detection has more hits then Frigate, mostly true positives. Is this because of a misconfiguration I did?

My config posted below. I tried both the FLV and the RTSP streams (commented out), not much difference noticed. 

```
database:
  path: /media/db/frigate.db

mqtt:
  enabled: true
  host: 192.168.1.199
  user: [redacted]
  password: [redacted]

go2rtc:
  streams:
    deurbel:
      - "ffmpeg:http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=[redacted]#video=copy#audio=copy#audio=opus"
      #- rtsp://frigate:[redacted]@192.168.1.108:554/h264Preview_01_main
      #- "ffmpeg:deurbel#audio=aac"
    deurbel_sub:
      - "ffmpeg:http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=[redacted]"
      #- rtsp://frigate:[redacted]@192.168.1.108:554/h264Preview_01_sub
    oprit:
      - "ffmpeg:http://192.168.1.110/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=[redacted]#video=copy#audio=copy#audio=opus"
      #- rtsp://frigate:[redacted]@192.168.1.110:554/h265Preview_01_main
      #- "ffmpeg:oprit#audio=aac"
    oprit_sub:
       - "ffmpeg:http://192.168.1.110/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=[redacted]"
      #- rtsp://frigate:[redacted]@192.168.1.110:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.1.198:8555
      - stun:8555

cameras:
  deurbel:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deurbel?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deurbel_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 5
  oprit:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/oprit?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/oprit_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 5

detect:
  fps: 5
  enabled: true

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - cat

record:
  enabled: true
  events:
    objects:
      - person

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

snapshots:
  enabled: true
```

I also tried the 640x480 resolution as documented. My impression is that the 896x672 (the native resolution of the sub-streams) has a slightly better result.
