### DISCUSSION TITLE
Just a question about my Hardware Setup

### DISCUSSION THREAD

**Discussion by AdmiralRaccoon** [blakeblackshear/frigate#7513] [General]
Hello,
I used to have the Home Assistant Frigate Addon installed, but I wasn´t able to get the Coral USB running with Proxmox passthrough.

I got hands on a Mini-PC, which runs a "Intel Pentium Silver J5005 CPU @ 1.50GHz" and a "Intel(R) UHD Graphics 605 1 GB"
It´s running only Docker with a frigate container, 2 cameras attached and got these stats:

![image](https://github.com/blakeblackshear/frigate/assets/41727850/82627e41-5cd8-476d-934b-f554341db67c)

The CPU load is always between 25-35 %, htop shows that this comes from the ffmpeg stream processes?:
![image](https://github.com/blakeblackshear/frigate/assets/41727850/dcd99129-72c3-410c-a3c0-ed828ecb0f27)

Is this a rather unsuitable type of hardware for Frigate, or is this the usual cpu load when running frigate?

Thank you and have a nice weekend

**Comment by NickM-27** [comment]
This doesn't seem that unreasonable in general, but it would be best to see a config. You didn't mention how many cameras you have, resolutions, etc.

**Comment by AdmiralRaccoon** [comment]
here is my config, quiet basic i think? Are there some unneccessary or obsolete settings?
There are just 2 Tapo FullHD Cams for my entrance and the livingroom (yet):

```
mqtt:
  host: 192.168.1.99
  user: mqtt
  password: mqtt

cameras:
  cam_haustuer:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://192.168.1.97:554/stream1
          roles:
            - detect
            - clip
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      events:
        retain:
          default: 7
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
        enabled: true
        timestamp: true
        bounding_box: true
        retain:
            default: 14
    motion:
      mask:
        - 0,0,471,0,480,59,412,35,0,163
        - 916,0,547,0,557,55
  cam_wohnzimmer:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.1.96:554/stream1
          roles:
            - detect
            - clip
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      events:
        retain:
          default: 7
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
        enabled: true
        timestamp: true
        bounding_box: true
        retain:
            default: 14

    
detectors: 
  coral:
    type: edgetpu
    device: usb
```
