### DISCUSSION TITLE
Frigate Recording Continuously in mode = motion

### DISCUSSION THREAD

**Discussion by emayo** [blakeblackshear/frigate#7562] [Ask A Question] [answered]
Hey can anyone help me understand why Frigate is recording continuously as well as motion when the record.retain.mode = motion?

I see many posts from folks how to get 24/7 recording as well as motion recording and I have the opposite question of how to stop the 24/7 (or continuous) recording and only have motion recordings.

Ultimately, I just want motion recorded.  Below is my full configuration file:

```yaml
mqtt:
  host: localhost

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  cam01:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        # High resolution stream
        - path: rtsp://admin:#REDACED#@192.168.1.23/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
        # Low resolution stream
        - path: rtsp://admin:#REDACED#@192.168.1.23/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true 
    # NOTE: detect widthxheight matches the low resolution stream size since it has the detect role
    detect:
      enabled: true
      width: 640
      height: 480
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 14
          mode: motion
 
birdseye:
  enabled: true
```
