### DISCUSSION TITLE
frigate on esxi ubuntu 23 VM with A4000 Nvidia Pass-Through

### DISCUSSION THREAD

**Discussion by Blu-Eagle** [blakeblackshear/frigate#7600] [Show and tell]
Hi,

it took me some time to figure out how to make it work, but in the end I did it.
I would like to share the config and docker-compose file so that in case someone else needs it can be of some help.
Any additional suggestions are welcome.
by the way, it would be useful to mention in the docs to use as container "frigate:stable-tensorrt".
PS: for the formatting, I am not able to maintain correctly.

**Docker compose**

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "64mb"
    devices:
      #      - /dev/bus/usb:/dev/bus/usb # Passthrough of Coral USB TPU
      - /dev/dri/renderD129 # Passthrough Intel NUC iGPU (optional)
      - /dev/dri/card1:/dev/dri/card1 # Passthrough Intel NUC iGPU (optional)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/beppe/frigate/config.yml:/config/config.yml
      - /home/beppe/frigate/storage:/media/frigate
      - /home/beppe/frigate/trt-models:/trt-models
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - FRIGATE_RTSP_USER=user
      - FRIGATE_RTSP_PASSWORD=password
      - USE_FP16=true
      - YOLO_MODELS=yolov7-tiny-416
    deploy:    # https://docs.frigate.video/configuration/hardware_acceleration/
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]

```
**config.yml**

```
mqtt:   
  host: 192.168.1.26
  port: 1883
  enabled: false
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

cameras:   
  cucina:     
    ffmpeg:       
      inputs:         
        - path: rtsp://login:password@192.168.1.207:88/videoSub           
          roles:             
            - detect
        - path: rtsp://login:password@192.168.1.207:88/videoMain
          roles:
            - record
      hwaccel_args: preset-nvidia-h264
    objects:
      track:
        - person
        - dog
    detect:       
      enabled: false
      width: 1280       
      height: 720
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects

birdseye:
  enabled: True
  restream: False
  mode: objects
  width: 1280
  height: 720

detect:
  fps: 5

detectors:
 tensorrt:
   type: tensorrt
   device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

snapshots:
  enabled: False
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 175
  retain:
    default: 10
    objects:
      person: 15
 
```

as usual: enjoy 😉
