### DISCUSSION TITLE
A working configuration on old jetson nano

### DISCUSSION THREAD

**Discussion by Blu-Eagle** [blakeblackshear/frigate#7614] [Show and tell]
Finally, a working configuration.... the thing that bothers me is that any time I  run docker-compose it has to recreate the yolo model.

anyway this is it:

**docker-compose.yml**

```
version: '2.4'
services:
  frigate:
    container_name: frigate
    image: madsciencetist/frigate-jetson:jetpack4.6.1   # this docker image
    privileged: true
    shm_size: "164mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/beppe/frigate/:/config
      - /home/beppe/frigate/storage:/media/frigate
      - /home/beppe/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "5000:5000"
      - "18554:8554" # RTSP feeds
      - "18555:8555/tcp" # WebRTC over tcp
      - "18555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
    runtime: nvidia
    environment:
      YOLO_MODELS: "yolov7-320" 
```

**config.yml**

```
mqtt:
  host: mqtt.server.com
cameras:
  cucina:
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://login:password@192.168.1.207:88/videoSub
          roles:
            - detect

detectors:
  tensorrt:
    type: tensorrt
    model:
      path: /config/model_cache/tensorrt/yolov7-320.trt

model:
  input_tensor: nchw                              # yolo models are nchw
  width: 320                                      # must match model size
  height: 320                                     # must match model size
```

any suggestion or improvement is well accepted :)

**Comment by klutzzykitty** [comment]
Hello @Blu-Eagle 
That's good that you've shared how you got it working on Jetson nano ! 

I guess it would add more meaning to this if you can share your Jetson nano configs as in Jetpack verion etc 
and some details on how you've gotten the model conversion working. (basically a brief overall procedure that's required to get it up and going).

That would make this an excellent reference on frigate discussion board as currently people have to jump across 
multiple discussions to understand how to set up things on Jetson.

**Reply by Blu-Eagle** [reply]
Hi,
nothing special, I just installed the last release of jetson nano sdk and updated it as usual. 
I installed docker-compose and simply run the docker-compose.yaml
now I give you all the info you asked, just a side note: the maintainer of frigate told me that jetson nano support will be included in the next version.

version of jetson os

```
Software part of jetson-stats 4.2.3 - (c) 2023, Raffaello Bonghi
Model: NVIDIA Jetson Nano Developer Kit - Jetpack 4.6.4 [L4T 32.7.4]
NV Power Mode[0]: MAXN

Hardware:
 - P-Number: p3448-0000
 - Module: NVIDIA Jetson Nano (4 GB ram)
Platform:
 - Distribution: Ubuntu 18.04 Bionic Beaver
 - Release: 4.9.337-tegra
jtop:
 - Version: 4.2.3
 - Service: Active
Libraries:
 - CUDA: 10.2.300
 - cuDNN: 8.2.1.32
 - TensorRT: 8.2.1.8
 - VPI: 1.2.3
 - Vulkan: 1.2.70
 - OpenCV: 4.1.1 - with CUDA: NO
```

after installation of a clean os I have simply run:
```
sudo  apt update && sudo apt dist-upgrade -y
sudo apt  install python3-pip
pip3 install --upgrade pip
sudo apt-get install libhdf5-dev
sudo apt-get install libssl-dev
sudo pip3 install docker-compose

```

that's it
I created a directory called frigate where I have put 

docker-compose.yaml

and

frigate.yml

as above.
the yolov7-320.trt is created automatically by the container at first run.
during the first run, and for debugging, I usually run:

`docker-compose up`

so I get all the logs and eventually also the errors.

that is really simple and easy. you do not have to create any tflite model, it is all done by the maintainer of the container.

I hope it helps anyone. :) If you need any additional info do not hesitate to ask .

enjoy :)

**Reply by klutzzykitty** [reply]
@Blu-Eagle Awesome details. That actually helped. 
A minor change would be that      `       - /home/beppe/frigate/trt-models:/trt-models`  isn't required anymore isn't it ? 

I've got it working on my Jetson as well - Nano, 4GB, jetpack 4.6.0
Also used jetpack 4.6.1,4.6.4. 

Have you tried stopping your frigate container and starting it again a few times? 
I've been seeing the container  behavior change upon a few restarts. 
Wanted to see if others were encountering it or if you can restart it a few times and see the debug window. 
Here's a link to the observations: https://github.com/blakeblackshear/frigate/pull/6458#issuecomment-1705226189

PS: Wouldn't want to create a new issue for it's discussions as i'm the only one seeing it so far. 
Thanks : )

**Reply by NickM-27** [reply]
Using tmpfs for /tmp/cache is highly recommended

**Reply by klutzzykitty** [reply]
Oops, typo. I've edited the comment.  
Was referencing the line above  `- type: tmpfs`      -->  mounting trt-models to container as that's not required anymore.

**Reply by NickM-27** [reply]
oh yes, that should not be used with the community jetson build / tesnorrt build

**Reply by wohali** [reply]
Updated version now that `model` has its own block:

```yaml
mqtt:
  host: mqtt.server.com
  enabled: true

ffmpeg:
  hwaccel_args: preset-jetson-h264

cameras:
  cucina:
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        - path: rtsp://login:password@192.168.1.207:88/videoSub
          roles:
            - detect

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw                              # yolo models are nchw
  width: 320                                      # must match model size
  height: 320                                     # must match model size
```

This should suppress the complaint about not being able to customize anything other than the detector type. I think it also sets the defaults for ffmpeg use everywhere, so they don't have to be supplied on a per-camera basis.
