### DISCUSSION TITLE
using Jetson Nano and Coral USB at the same time

### DISCUSSION THREAD

**Discussion by Blu-Eagle** [blakeblackshear/frigate#7627] [Show and tell]
As you probably understood I have a jetson nano laying around doing nothing, so I thought of using frigate....
here are my configurations in case you would like to reproduce:

docker-compose.yaml

```
version: '2.4'
services:
  frigate:
    container_name: frigate
    image: madsciencetist/frigate-jetson:jetpack4.6.1   # this docker image
    privileged: true
    shm_size: "164mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/beppe/frigate/:/config
      - /home/beppe/frigate/storage:/media/frigate
      - /home/beppe/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "5000:5000"
      - "18554:8554" # RTSP feeds
      - "18555:8555/tcp" # WebRTC over tcp
      - "18555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "xxx"
    runtime: nvidia
    environment:
      YOLO_MODELS: "yolov7-320"                         # generate the model (match the model path)
~ 
```

config.yml

```
mqtt:
  host: 192.168.1.26
  port: 1883
  enabled: false
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

cameras:   
  cucina:     
    ffmpeg:       
      hwaccel_args: preset-jetson-h264
      inputs:         
        - path: rtsp://login:pwd@192.168.1.207:88/videoSub           
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
    detect:
      enabled: false
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects


detectors:
  tensorrt:
    type: tensorrt
    model:
      path: /config/model_cache/tensorrt/yolov7-320.trt 
    input_tensor: nchw                              # yolo models are nchw
    width: 320                                      # must match model size
    height: 320                                     # must match model size
  coral:
    type: edgetpu
    device: usb
    model:
      path: /trt-models/edgetpu_model.tflite

      #model:
      #  input_tensor: nchw                              # yolo models are nchw
      #  width: 320                                      # must match model size
      #  height: 320                                     # must match model size

birdseye:
  enabled: True
  mode: objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: true
  retain:
    default: 3


```

I have put the edgetpu_model.tflite in trt-models because it was already mounted, so I did not need to mount another one...

as usual, enjoy
