### DISCUSSION TITLE
288 GB of go2rtc recordings every day

### DISCUSSION THREAD

**Discussion by tfcarlin** [blakeblackshear/frigate#7630] [Ask A Question] [answered]
Hi,

It appears as though go2rtc is creating many mp4 files every hour which results in 288 GB of files every day. An example day for 1 camera follows the yaml.

Any ideas on how to prevent this or automatically trim them? 

Thanks!

Tim

config.yml

```
mqtt:
  enabled: False

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
model:
  width: 320
  height: 320
  labelmap:
    1: vehicle
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal
go2rtc:
  streams:
    garage:
      - rtsp://user:password@192.168.1.171:554/h264Preview_01_main
    garage_sub:
      - rtsp://user:password@192.168.1.171:554/h264Preview_01_sub
    toolshed:
      - rtsp://user:password@192.168.1.127:554/h264Preview_01_main
    toolshed_sub:
      - rtsp://user:password@192.168.1.127:554/h264Preview_01_sub
    drivecam:
      - rtsp://user:password@192.168.1.135:554/h264Preview_01_main
    drivecam_sub:
      - rtsp://user:password@192.168.1.135:554/h264Preview_01_sub
    backyard:
      - rtsp://user:password@192.168.1.176:554/h264Preview_01_main
    backyard_sub:
      - rtsp://user:password@192.168.1.176:554/h264Preview_01_sub
    doorbell:
      - rtsp://user:password@192.168.1.58:554/h264Preview_01_main
    doorbell_sub:
      - rtsp://user:password@192.168.1.58:554/h264Preview_01_sub
    netcloset:
      - rtsp://user:password@192.168.1.209:554/h264Preview_01_main
    netcloset_sub:
      - rtsp://user:password@192.168.1.209:554/h264Preview_01_sub
birdseye:
  enabled: True
  mode: continuous
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 100
    mode: all
cameras:
  toolshedcam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/toolshed
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/toolshed_sub
          roles:
            - detect
    live:
      stream_name: toolshed
    record:
      enabled: True
    detect:
      enabled: true
      width: 640
      height: 480
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - vehicle

  garage:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: garage
    detect:
      enabled: true
      width: 640
      height: 360
    record:
      enabled: true
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - animal

  drivecam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
#      hwaccel_args: []
#        - hevc_cuvid
      inputs:
        - path: rtsp://127.0.0.1:8554/drivecam
#          input_args: -s:v 3840x2160 -c:v yuv4 -analyzeduration 250M -probesize 100M
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drivecam_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 896
      height: 512
    record:
      enabled: true
      events:
        required_zones:
          - vehicleplaces
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - vehicle
        - animal

  backyard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
 #     hwaccel_args: []
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
#          input_args: -s:v 3840x2160 -c:v yuv4 -analyzeduration 250M -probesize 100M
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
    record:
      enabled: true
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - vehicle
        - animal
  netcloset:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/netcloset
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/netcloset_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: netcloset
    detect:
      enabled: true
      width: 640
      height: 360
    record:
      enabled: true
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - vehicle
        - animal
  doorbell:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell
    detect:
      enabled: true
      width: 640
      height: 480
    record:
      enabled: true
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - animal
```

```
00.04.mp4  04.44.mp4  09.24.mp4  14.04.mp4  18.44.mp4  23.24.mp4  28.04.mp4  32.44.mp4  37.24.mp4  42.03.mp4  46.44.mp4  51.23.mp4  56.03.mp4
00.14.mp4  04.54.mp4  09.34.mp4  14.14.mp4  18.54.mp4  23.34.mp4  28.14.mp4  32.54.mp4  37.34.mp4  42.13.mp4  46.54.mp4  51.33.mp4  56.13.mp4
00.24.mp4  05.04.mp4  09.44.mp4  14.24.mp4  19.04.mp4  23.44.mp4  28.24.mp4  33.04.mp4  37.44.mp4  42.23.mp4  47.03.mp4  51.43.mp4  56.23.mp4
00.34.mp4  05.14.mp4  09.54.mp4  14.34.mp4  19.14.mp4  23.54.mp4  28.34.mp4  33.14.mp4  37.54.mp4  42.33.mp4  47.14.mp4  51.53.mp4  56.33.mp4
00.44.mp4  05.24.mp4  10.04.mp4  14.44.mp4  19.24.mp4  24.04.mp4  28.44.mp4  33.24.mp4  38.04.mp4  42.43.mp4  47.24.mp4  52.03.mp4  56.43.mp4
00.54.mp4  05.34.mp4  10.14.mp4  14.54.mp4  19.34.mp4  24.14.mp4  28.54.mp4  33.34.mp4  38.14.mp4  42.53.mp4  47.34.mp4  52.13.mp4  56.53.mp4
01.04.mp4  05.44.mp4  10.24.mp4  15.04.mp4  19.44.mp4  24.24.mp4  29.04.mp4  33.44.mp4  38.24.mp4  43.03.mp4  47.44.mp4  52.23.mp4  57.03.mp4
01.14.mp4  05.54.mp4  10.34.mp4  15.14.mp4  19.54.mp4  24.34.mp4  29.14.mp4  33.54.mp4  38.34.mp4  43.13.mp4  47.54.mp4  52.33.mp4  57.13.mp4
01.24.mp4  06.04.mp4  10.44.mp4  15.24.mp4  20.04.mp4  24.44.mp4  29.24.mp4  34.04.mp4  38.44.mp4  43.24.mp4  48.04.mp4  52.43.mp4  57.23.mp4
01.34.mp4  06.14.mp4  10.54.mp4  15.34.mp4  20.14.mp4  24.54.mp4  29.34.mp4  34.14.mp4  38.54.mp4  43.33.mp4  48.14.mp4  52.53.mp4  57.33.mp4
01.44.mp4  06.24.mp4  11.04.mp4  15.44.mp4  20.24.mp4  25.04.mp4  29.44.mp4  34.24.mp4  39.04.mp4  43.43.mp4  48.23.mp4  53.03.mp4  57.43.mp4
01.54.mp4  06.34.mp4  11.14.mp4  15.54.mp4  20.34.mp4  25.14.mp4  29.54.mp4  34.34.mp4  39.14.mp4  43.53.mp4  48.34.mp4  53.13.mp4  57.53.mp4
02.04.mp4  06.44.mp4  11.24.mp4  16.04.mp4  20.44.mp4  25.24.mp4  30.04.mp4  34.44.mp4  39.24.mp4  44.04.mp4  48.44.mp4  53.23.mp4  58.03.mp4
02.14.mp4  06.54.mp4  11.34.mp4  16.14.mp4  20.54.mp4  25.34.mp4  30.14.mp4  34.54.mp4  39.34.mp4  44.13.mp4  48.53.mp4  53.33.mp4  58.13.mp4
02.24.mp4  07.04.mp4  11.44.mp4  16.24.mp4  21.04.mp4  25.44.mp4  30.24.mp4  35.04.mp4  39.44.mp4  44.23.mp4  49.04.mp4  53.43.mp4  58.23.mp4
02.34.mp4  07.14.mp4  11.54.mp4  16.34.mp4  21.14.mp4  25.54.mp4  30.34.mp4  35.14.mp4  39.54.mp4  44.33.mp4  49.13.mp4  53.53.mp4  58.33.mp4
02.44.mp4  07.24.mp4  12.04.mp4  16.44.mp4  21.24.mp4  26.04.mp4  30.44.mp4  35.24.mp4  40.04.mp4  44.43.mp4  49.23.mp4  54.03.mp4  58.43.mp4
02.54.mp4  07.34.mp4  12.14.mp4  16.54.mp4  21.34.mp4  26.14.mp4  30.54.mp4  35.34.mp4  40.14.mp4  44.53.mp4  49.34.mp4  54.13.mp4  58.53.mp4
03.04.mp4  07.44.mp4  12.24.mp4  17.04.mp4  21.44.mp4  26.24.mp4  31.04.mp4  35.44.mp4  40.24.mp4  45.04.mp4  49.43.mp4  54.23.mp4  59.03.mp4
03.14.mp4  07.54.mp4  12.34.mp4  17.14.mp4  21.54.mp4  26.34.mp4  31.14.mp4  35.54.mp4  40.34.mp4  45.14.mp4  49.53.mp4  54.33.mp4  59.13.mp4
03.24.mp4  08.04.mp4  12.44.mp4  17.24.mp4  22.04.mp4  26.44.mp4  31.24.mp4  36.04.mp4  40.44.mp4  45.24.mp4  50.03.mp4  54.43.mp4  59.23.mp4
03.34.mp4  08.14.mp4  12.54.mp4  17.34.mp4  22.14.mp4  26.54.mp4  31.34.mp4  36.14.mp4  40.53.mp4  45.34.mp4  50.13.mp4  54.53.mp4  59.33.mp4
03.44.mp4  08.24.mp4  13.04.mp4  17.44.mp4  22.24.mp4  27.04.mp4  31.44.mp4  36.24.mp4  41.03.mp4  45.44.mp4  50.23.mp4  55.03.mp4  59.43.mp4
03.54.mp4  08.34.mp4  13.14.mp4  17.54.mp4  22.34.mp4  27.14.mp4  31.54.mp4  36.34.mp4  41.14.mp4  45.53.mp4  50.33.mp4  55.13.mp4  59.53.mp4
04.04.mp4  08.44.mp4  13.24.mp4  18.04.mp4  22.44.mp4  27.24.mp4  32.04.mp4  36.44.mp4  41.23.mp4  46.03.mp4  50.43.mp4  55.23.mp4
04.14.mp4  08.54.mp4  13.34.mp4  18.14.mp4  22.54.mp4  27.34.mp4  32.14.mp4  36.54.mp4  41.33.mp4  46.13.mp4  50.53.mp4  55.33.mp4
04.24.mp4  09.04.mp4  13.44.mp4  18.24.mp4  23.04.mp4  27.44.mp4  32.24.mp4  37.04.mp4  41.44.mp4  46.23.mp4  51.03.mp4  55.43.mp4
04.34.mp4  09.14.mp4  13.54.mp4  18.34.mp4  23.14.mp4  27.54.mp4  32.34.mp4  37.14.mp4  41.54.mp4  46.33.mp4  51.13.mp4  55.53.mp4
```
