### DISCUSSION TITLE
Missing Trigger/Recording

### DISCUSSION THREAD

**Discussion by Cah1982** [blakeblackshear/frigate#7637] [General]
So my camera does normally pick up people in the bedroom

but, on my Tapo C225 there is a privacy button, on other NVR software triggering this would create a event (not ideal) as this can be turned on/off remotly in app, So on each opening and close it would have a recording

But I have noticed, in Frigate when this is privacy is turned on/off if there is someone just come into room there is no recording events saved

Config is below

```yaml
detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    motion:
      mask:
      - 422,30,422,0,0,0,0,30
    record:
      enabled: True
      events:
        pre_capture: 20
        post_capture: 30
        objects:
          - person
        required_zones:
          - Bathroom_Door
          - Bedroom_Door
        retain:
          default: 10
          mode: all
    zones:
      Bathroom_Door:
        coordinates: 74,322,97,589,370,479,389,40,104,43
        objects:
          - person
      Bedroom_Door:
        coordinates: 893,424,958,435,966,171,904,151
        objects:
          - person 
```
          
My only other issue is the pre event trigger never seems to be done e.g person enters room, i cant see the 20 seconds before, e.g. they enter room, so there already half way into the room
