### DISCUSSION TITLE
Install a Frigate non-stable docker version

### DISCUSSION THREAD

**Discussion by lorenzomartini1** [blakeblackshear/frigate#7638] [Ask A Question]
Hi there,
I would like to test/use these features:
https://github.com/blakeblackshear/frigate/pull/3184

I see it's merged into dev... is there a way to install this and not the stable version?

My current version is 0.12.0-DA3E197.

My current docker compose file:
```
services:
  frigate:
    container_name: frigate-test-update
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/hdd/frigate:/media/frigate
      - config:/config
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935   # RTMP feeds

volumes:
  config:
```
