### DISCUSSION TITLE
Why is this triggering a zone not even close?

### DISCUSSION THREAD

**Discussion by pyrodex** [blakeblackshear/frigate#7665] [Ask A Question]
I have my "Driveway" camera broken out into three zones; FrontYard, Driveway, and Street. 

I am running the latest Stable docker container but this one is confusing for me and would like to make sure I am not crazy or maybe guidance on how to fix it? 

I've noticed a few "cars" getting triggered in the events for the Zone FrontYard  and here is the zone for FrontYard:

![Screenshot 2023-09-03 at 09-23-17 Frigate](https://github.com/blakeblackshear/frigate/assets/108703/1695767b-6420-433a-9200-54f2aa413563)

Here are a few examples from last night showing Frigate and the zone being shown as FrontYard.

This one I have no explanation for at all:
<img width="1788" alt="Screenshot 2023-09-03 at 9 25 25 AM" src="https://github.com/blakeblackshear/frigate/assets/108703/adcf9821-15d7-4b0b-81e6-35241d461e72">

This one I could MAYBE see where the car bounding box is in the FrontYard zone barely but not sure:
<img width="1794" alt="Screenshot 2023-09-03 at 9 25 40 AM" src="https://github.com/blakeblackshear/frigate/assets/108703/cdc4eaf5-c7db-4691-8210-a066b34a18bc">

Here is the configuration for the Driveway camera:

```
  driveway: # <------ Name the camera
    ui:
      order: 1
    record:
      events:
        required_zones:
          - Driveway
          - FrontYard
    snapshots:
      required_zones:
          - Driveway
          - FrontYard
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      enabled: True
      fps: 5
    zones: 
      FrontYard:
        coordinates: 1920,1080,1920,386,1509,219,1181,270,623,227,470,180,308,229,0,380,0,1080
        objects:
          - person
          - bicycle
          - dog
          - car
#        filters:
#         person: 
#            mask: 
#              - 775,144,688,150,698,102,760,95
#            min_area: 30000
      Driveway:
        coordinates: 652,210,1193,252,1231,195,1363,157,1011,119,827,147
        objects:
          - person
          - bicycle
          - motocycle
          - truck
          - dog
          - car
      Street:
        coordinates: 348,143,687,113,1144,107,1446,140,1735,223,1920,302,1920,0,529,0,0,0,0,306,183,227
        objects:
          - car
          - person
          - truck
          - motocycle
          - person
        filters:
          car: 
            mask: 348,143,1092,120,1684,223,1920,302,1920,0,529,0,0,0,0,297,183,227
            min_area: 1000000
            min_score: 1.0
          bicycle: 
            mask: 348,143,1092,120,1684,223,1920,302,1920,0,529,0,0,0,0,297,183,227
            min_area: 1000000
            min_score: 1.0
          truck: 
            mask: 348,143,1092,120,1684,223,1920,302,1920,0,529,0,0,0,0,297,183,227
            min_area: 1000000
            min_score: 1.0
          person: 
            mask: 
              - 348,143,1092,120,1684,223,1920,302,1920,0,529,0,0,0,0,297,183,227
              - 775,144,688,150,698,102,760,95
            min_area: 1000000
            min_score: 1.0
          motocycle: 
            mask: 348,143,1092,120,1684,223,1920,302,1920,0,529,0,0,0,0,297,183,227
            min_area: 1000000
            min_score: 1.0
```
