### DISCUSSION TITLE
How do I set a stream to track objects but not keep the snapshot for one of those object types?

### DISCUSSION THREAD

**Discussion by nthulke** [blakeblackshear/frigate#7674] [Ask A Question] [answered]
I have this setup for one of my streams:

```
############################################################ Kids Hallway
  hallway:
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        dog:
          mask:
            - 679,561,689,615,857,699,837,720,449,720,303,511,276,436,451,389,464,441
            - 0,0,822,0,1280,0,1280,232,1096,223,1091,471,591,346,0,507,0,211
    ffmpeg:
      hwaccel_args: preset-vaapi      
      inputs:
        - path: rtsp://removed:removed@10.0.0.179:554/stream1
          roles:
            - record
        - path: rtsp://removed:removed@10.0.0.179:554/stream2
          roles:
            - detect         

```
What I would like to know is how can I set this stream to only record the Cat and Dog and not the Person (also dont want it to keep snapshots of people)

What I want to do is have the trigger of a person detection turn on some night lights for my kids in the middle of the night, but not save me waking around half naked (no one needs to see that).

This is the record/snapshot part of my config file:

```
record:
  enabled: true

snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: true
      crop: False

```

**Comment by NickM-27** [comment, marked as answer]
There are a couple different ways this could be done but I think the most straightforward would be to make a required zone and limit that zone to the objects you want events from https://docs.frigate.video/configuration/zones

**Reply by nthulke** [reply]
Thanks!

This is what I ended up with and so far its working great. The MQTT Feed on HA still shows the Snapshot but thats the only place and I dont think I can stop that without disabling it in HA which is probably the easiest way.

```
  hallway:
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        dog:
          mask:
            - 679,561,689,615,857,699,837,720,449,720,303,511,276,436,451,389,464,441
            - 0,0,822,0,1280,0,1280,232,1096,223,1091,471,591,346,0,507,0,211
        person:
          mask:
            - 0,0,424,0,470,429,670,552,674,602,829,689,794,720,0,720             
    ffmpeg:
      hwaccel_args: preset-vaapi      
      inputs:
        - path: rtsp://removed:removed@10.0.0.179:554/stream1
          roles:
            - record
        - path: rtsp://removed:removed@10.0.0.179:554/stream2
          roles:
            - detect
  
    record:
      events:
        required_zones:
          - hallwaydog
        
    snapshots: 
      required_zones:
        - hallwaydog
    
    zones:  
        hallwayperson:
          coordinates: 1060,0,1039,188,441,186,471,429,568,490,669,557,671,603,829,720,1160,720,1249,443,1247,0          
          objects:
            - person
          snapshots:
            enalbe: False

        hallwaydog:
          coordinates: 0,720,1280,720,1280,0,0,0
          objects:
            - dog
            - cat
```
