### DISCUSSION TITLE
Set up media saving on shared smb share on docker compose

### DISCUSSION THREAD

**Discussion by SofaSurfer76** [blakeblackshear/frigate#7688] [Ask A Question]
Hi, 
I'm pretty a newbie with Linux, I have a mini pc Proxmox with  Frigate on docker compose in a container, and I have added a second HD for my media, I share it in my home network in SMB with Openmediavault. I already use it as server with Plex, that is in the same stack, so my drive is correctly mounted in the container. 
From Frigate I can see that in the storage section the size of my Hd, so it's correctly seen, but impossible to save on it, I have error : [errno 13] permission denied.
I think I have to give my user and password to Frigate, what do I have to add in my docker compose file?

```
services:


  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped #always
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/frigate:/config:rw
      - /mnt/pve/omv/Media/frigate/clips:/media/frigate/clips:rw
      - /mnt/pve/omv/Media/frigate/recordings:/media/frigate/recordings:rw
```

I have tried to add credentials in the env variables, but it looks wrong:

    environment:
       FRIGATE_RTSP_PASSWORD: "jijinho"
       SMB_USER: "your_smb_username"
       SMB_PASS: "your_smb_password"
