### DISCUSSION TITLE
Recording and Detection on Streams

### DISCUSSION THREAD

**Discussion by tibmeister** [blakeblackshear/frigate#7705] [Ask A Question]
I'm moving away from ZoneMinder in favor of Frigate, but one thing I am struggling with is the streams.  So let me go back to how I had ZM setup for this particular camera, which is a 4k camera.
I created Monitor1 in ZM, that was using the sub-stream at a resolution of 704x480.  I created Monitor2 using the main stream at a resolution of 3840x2160.
Monitor1 would always record to disk (24/7) and also performed motion analysis.  Monitor2 was linked to Monitor1 and used it as the trigger to record motion events.  So, what I got was a lower resolution 24/7 recording stream that I would keep for 72 hours, then a high resolution stream that would only record motion events and I would keep for 14 days.
I am struggling on how to recreate this setup in Frigate.
Currently, I have the camera setup with the two inputs, with the detect role on the low-res and the record role on the high-res, but I also want to record on the low-res.  I'm thinking I will need to have a second camera that has the record role and only has the low-res stream.  Is this the only way or is there some odd thing that I'm missing that would make this magically work with a single camera config?

**Comment by NickM-27** [comment]
Yes that's the way it needs to be done for now, there's a pinned feature request to also have the sub stream recorded.

**Reply by tibmeister** [reply]
So not sure what I'm doing wrong, but on the one with the two inputs (driveway), all I am getting is snapshots, not any clips.  On the other one, the 24/7 recording (driveway_constant), there's no events or anything showing in the UI.  I'm sure it's something I'm missing, not understanding, or just plain goofing on.  Here's my config, sanitized of course.

```
birdseye:
  enabled: True
  mode: continuous
  quality: 6
  
mqtt:
  enabled: True
  host: 192.168.200.5
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: someuser
  password: 'xxx'

ui:
  live_mode: mse
  timezone: America/Chicago

telemetry:
  version_check: False

detectors: 
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2

timestamp_style:
  position: tl
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: false
  retain:
    default: 14

record:
  enabled: True
  retain:
    days: 14
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

cameras:
  h2_carport:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.15:36521/355457f710902ea6 # lowres
          roles:
            - detect
        - path: rtsp://192.168.200.15:36521/01afc119707a781d # highres
          roles:
            - record
      output_args:
        record: preset-record-generic
    detect:
      width: 640
      height: 480
      stationary:
        interval: 10
        threshold: 30
    objects:
      track:
        - person
        - car
        - dog
        - cat
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: false
      quality: 90
      required_zones: []

  h2_yardnw:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.15:39257/2f04d4cc135e4b20
          roles:
            - detect
      output_args:
        record: preset-record-generic
    detect:
      width: 640
      height: 480
      stationary:
        interval: 10
        threshold: 30
    objects:
      track:
        - person
        - car
        - dog
        - cat
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: false
      quality: 90
      required_zones: []

  driveway_constant:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.15:34291/2241daa352ac2f60 #lowres
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.15:34291/2241daa352ac2f60 #lowres
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.200.15:34291/5fa430ba3ac08011 #highres
          roles:
            - record
      output_args:
        record: preset-record-generic
    record:
      events:
        required_zones:
          - driveway_end
    detect:
      width: 704
      height: 480
      stationary:
        interval: 10
        threshold: 30
    objects:
      track:
        - person
        - car
        - dog
        - cat
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: false
      quality: 90
      required_zones: 
        - driveway_end
    motion:
      mask:
        - 32,0,704,0,704,182,704,221,465,106,381,92,279,82,57,139 # Road and neighbors yard
        - 704,480,704,170,633,156,594,314,429,266,136,401,172,480 # Bottom right
        - 47,90,38,0,0,0,0,480,175,480 # Front wall of house
    zones:
      driveway_end:
        coordinates: 3419,956,3543,737,2595,491,2389,645
      driveway_mid:
        coordinates: 1772,946,3168,1537,3423,954,2373,655

  deckcam:
    enabled: True
    ffmpeg:
      inputs:
        - path: http://192.168.202.80:8080
          roles:
            - detect
            - record
          input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
    detect:
      width: 800
      height: 600
    objects:
      track:
        - person
        - dog
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      quality: 70
      required_zones: []
```

**Reply by NickM-27** [reply]
there's a lot going on here so it is difficult to understand the issue. For one, you don't have the objects tracking list defined for driveway_constant so we wouldn't expect any events for that camera except for `person`

driveway likely only has snapshots because you have made recordings require the driveway_end zone but you did not apply the same to snapshots

**Reply by tibmeister** [reply]
For driveway_constant, I don't want to track objects, I just want to dump the video stream to disk for later.
Going to have to look at the driveway record node.  Seems there's a lot of repetition in the config.  I'm assuming in this case it's pulling down the global default portion and overlaying it onto the camera since I am not specifically overriding the snapshot.

**Reply by NickM-27** [reply]
> For driveway_constant, I don't want to track objects, I just want to dump the video stream to disk for later.

Right, then you will not have any events for that camera

**Reply by tibmeister** [reply]
Without the events, how would I be able to see the recordings then?
Also, on the other camera, where I am detecting on the low-res feed and recording on the high-res feed, not sure why I'm only getting snapshots and no clips during the events.  Seems like it should work like I expect (see below)

```
driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.15:34291/2241daa352ac2f60 #lowres
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.200.15:34291/5fa430ba3ac08011 #highres
          roles:
            - record
      output_args:
        record: preset-record-generic
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - driveway_end
    detect:
      width: 704
      height: 480
      stationary:
        interval: 10
        threshold: 30
    objects:
      track:
        - person
        - car
        - dog
        - cat
```
