### DISCUSSION TITLE
Trying to figure out why 1 of my 14 cameras keeps eating a ton of space

### DISCUSSION THREAD

**Discussion by hagak** [blakeblackshear/frigate#7718] [General]
So the config of the dooryard camera is basically the same as another identical camera that has never had this issue and all my cameras are reolink but the dooryard one and rivercam are both 8mp with the rest 5mp.

I noticed the dooyard one seems to eat up a ton of the cache space and never refreshes, if you see the dates the dooryard one is rather old were the others are how you would expect.

In an attempt to rule out a corrupted DB, I wiped my db and all recordings and started fresh today.  Still same issue after a few hours.  Currently have tmpfs set to ~5GB which should be way more then needed but I am about to run out soon after a few hours.

![Image 9-6-23 at 19 02](https://github.com/blakeblackshear/frigate/assets/9702199/71316f94-cb5d-47a7-8613-19a4d7f87f1f)

NOTE: kitchens and lowerdooryard are old wyze cams which is why they are so much smaller

**Comment by NickM-27** [comment]
This is an issue with the cameras sending bad timestamps leading to ffmpeg not cutting the segment off (the segment is only supposed to last ~10 seconds)

What is the config?

**Reply by hagak** [reply]
```
---

database:
  path: /data/frigate.db

detectors:
  coral_pci0:
    type: edgetpu
    device: pci:0
  coral_pci1:
    type: edgetpu
    device: pci:1
  coral_pci2:
    type: edgetpu
    device: pci:2
  coral_pci3:
    type: edgetpu
    device: pci:3

logger:
  logs:
    frigate.record: debug

# Required: mqtt configuration
mqtt:
  host: homeasssistant_mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 0
    mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 14
      mode: active_objects

birdseye:
  restream: false

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio-aac
    rtmp: preset-rtmp-generic

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

go2rtc:
  rtsp:
    username: "{RTSP_USER}"
    password: "{RTSP_PASSWORD}"
  webrtc:
    candidates:
      - 10.100.10.82:8555
      - stun:8555
  streams:
    catcam:
      - http://192.168.30.35/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:catcam#audio=opus"
    garage:
      - http://192.168.30.40/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:garage#audio=opus"
    garage_lab:
      - http://192.168.30.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:garage_lab#audio=opus"
    garageEntrance:
      - http://192.168.30.36/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:garageEntrance#audio=opus"
    dooryard:
      - http://192.168.30.46/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:dooryard#audio=opus"
    den:
      - http://192.168.30.38/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:den#audio=opus"
    boilerRoom:
      - http://192.168.30.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:boilerRoom#audio=opus"
    tank:
      - http://192.168.30.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:tank#audio=opus"
    backyard:
      - http://192.168.30.48/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:backyard#audio=opus"
    backyardnorth:
      - http://192.168.30.49/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:backyardnorth#audio=opus"
    lowerbackyard:
      - http://192.168.30.47/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:lowerbackyard#audio=opus"
    office:
      - http://192.168.30.32/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:office#audio=opus"
    rivercam:
      - http://192.168.30.29/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}
      - "ffmpeg:rivercam#audio=opus"

cameras:
  
  dooryard:
    ffmpeg:
      inputs:
        - path: 'http://192.168.30.46/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}'
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/dooryard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      enabled: true
      height: 512
      width: 896
    motion:
      mask:
        - 896,388,829,377,757,360,404,512,896,512
        - 385,0,385,47,0,55,0,0
    zones:
      driveway:
        coordinates: 380,512,754,375,896,382,896,263,838,157,680,0,532,0,657,167,303,203,360,404
      parkingarea:
        coordinates: 0,160,299,174,444,204,600,462,0,512
      yard:
        coordinates: 0,0,527,0,602,53,634,199,0,275
    # Optional: Camera level object filters config. If defined, this is used instead of the global config.
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          min_area: 800
          max_area: 20000
          min_score: 0.45
          threshold: 0.7
        car:
          mask:
            - 216,307,212,123,0,134,0,358
          min_area: 2000
          max_area: 400000
          min_score: 0.35
          threshold: 0.7

  rivercam:
    ffmpeg:
      inputs:
        - path: 'http://192.168.30.29/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}'
          input_args: preset-http-reolink
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/rivercam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      enabled: true
      height: 512
      width: 896

    motion:
      mask:
        - 404,672,347,536,187,300,0,172,0,672
        - 618,192,896,284,896,512,575,512
        - 387,0,388,48,0,38,0,0
        - 733,104,742,233,600,247,578,105

    objects:
      track:
        - person
        - boat
        - cat
        - dog
        - bird
      filters:
        person:
          mask:
            - 232,0,179,0,199,106,260,98
          min_area: 400
          max_area: 2000
          min_score: 0.45
          threshold: 0.7
        boat:
          mask:
            - 606,192,824,155,864,294,601,357
          min_area: 750
          max_area: 100000
          min_score: 0.55
          threshold: 0.65
        bird:
          min_area: 100
          max_area: 2000
          min_score: 0.55
          threshold: 0.7
        cat:
          min_area: 100
          max_area: 2000
          min_score: 0.45
          threshold: 0.7
        dog:
          min_area: 150
          max_area: 2000
          min_score: 0.45
          threshold: 0.7

```

**Reply by hagak** [reply]
Note i removed some of the cameras configs just cause it is mostly copies so did not think it was needed.

**Reply by NickM-27** [reply]
I'd suggest adjusting the config to match https://docs.frigate.video/configuration/camera_specific#reolink-cameras

**Reply by hagak** [reply]
Maybe I am missing something but the only difference is I am not using a restream for my DETECT and since I only have that stream for DETECT and no other clients I did not see the point.

**Reply by NickM-27** [reply]
the recommended config has go2rtc configuring `ffmpeg:` for the entire stream not just for opus audio

**Reply by hagak** [reply]
But the detect is fine then?  Or should I put that up into the go2rtc section as well?

**Reply by NickM-27** [reply]
Like you said, no reason to use go2rtc if you're not using it for anything else

**Reply by hagak** [reply]
So I implemented the following changes:

```
go2rtc:
  streams:
    catcam:
      - "ffmpeg:http://192.168.30.35/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    garage:
      - "ffmpeg:http://192.168.30.40/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    garage_lab:
      - "ffmpeg:http://192.168.30.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    garageEntrance:
      - "ffmpeg:http://192.168.30.36/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    dooryard:
      - "ffmpeg:http://192.168.30.46/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    den:
      - "ffmpeg:http://192.168.30.38/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    boilerRoom:
      - "ffmpeg:http://192.168.30.31/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    tank:
      - "ffmpeg:http://192.168.30.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    backyard:
      - "ffmpeg:http://192.168.30.48/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    backyardnorth:
      - "ffmpeg:http://192.168.30.49/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    lowerbackyard:
      - "ffmpeg:http://192.168.30.47/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    office:
      - "ffmpeg:http://192.168.30.32/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"
    rivercam:
      - "ffmpeg:http://192.168.30.29/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USER}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=opus"

```

However now on the record I get this for every camera every 10s. 
No new recording segments where created for XXX
