### DISCUSSION TITLE
Need help with getting go2rtc to re-encode a stream (with is Nvidia NVENC)

### DISCUSSION THREAD

**Discussion by domenicdistefano** [blakeblackshear/frigate#7755] [Ask A Question] [answered]
Not sure if this just isn't possible or my syntax isn't right. 

Here is a snippet in my working current config where I am not re-encoding anything and just bringing in my two streams as usual where further down I am using the main for recording and the sub for detection - all standard stuff.

**--------------------------original config----------------------------------------**
```
go2rtc:
  streams:
     back_yard:
      - rtsp://admin:password@10.10.10.72:554/media/video0
     back_yard_sub:
      - rtsp://admin:password@10.10.10.72:554/media/video1
```
**--------------------------original config----------------------------------------**

Now this works but the resolution and FPS of my sub stream isn't ideal so I want to adjust / re-encode the main stream to what I want. Since I have an NVIDA GPU (P600) that has an NVENC encoder this should be much better than trying to use vaapi or the CPU.

Below is what I came up with but it doesn't work. Thinking it was the nvidia part at the end I tried using vaapi instead but that also failed. I suspect I am just not formatting this correctly. My understand of what should be happening here is that since after `fmpeg:` I am referencing the same stream name (back_yard) as the line above it should know to use that stream instead of having to re-reference the original main stream via RTSP again redundantly re-pulling it again. 

So I guess my first question is with the decoder hardware piece of the puzzle aside for a minute is the concept sound and should this work provided I can figure out the proper syntax in general? Next question is should I be able to utilize the Nvidia P600 card (i.e. is it supported by FFMPEG within the frigate container provided I have the NVIDIA drivers passed through and working). I have already verified the card works as it is recognized for decoding within the container and working. 

Thank you in advance for any help.

**--------------------------new config not working----------------------------------------**
```
go2rtc:
  streams:
     back_yard:
      - rtsp://admin:password-@10.10.10.72:554/media/video0
     back_yard_sub:
      - "ffmpeg:backyard_yard#video=h264#width=1920#height=1080#raw=-fpsmax 10#hardware=nvidia-h264"
```
**--------------------------new config not working----------------------------------------**
 
**go2rtc log errors**
_2023-09-10 15:02:05.584777342  15:02:05.584 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:backyard_yard#video=h264#width=1920#height=1080#raw=-fpsmax 10#hardware=vaapi"
2023-09-10 15:02:05.584780851  15:02:05.584 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=back_yard_sub_
