### DISCUSSION TITLE
Frigate MQTT: Best sequence for act a detection alert

### DISCUSSION THREAD

**Discussion by ghost** [blakeblackshear/frigate#7774] [General]
Good morning,

For a few days/weeks I have been using the features of Frigate (within the limits of my knowledge of the different configurations) in order to eventually replace the "motion" software.
I must say that frigate seems to suit me more and more, apart from certain finesse of configuration which still remains not very clear to me (that will come)

I am ultimately considering to push to smartphone  to be notified of detections/movements and/or to suspend detections, etc.
**-> I don't use Home Assistant, I don't have any use for it to date.**

I am therefore developing an external "tools" (currently in the analysis phase) for interaction between MQTT frigate message and the actions to be carried out (push, commands, etc.) towards a smartphone.

Could you tell me the order of the sequences to take into account to signify/or not a detection

Currently I use the following MQTT topics:
- frigate/events (before/after)
- frigate/<Camera>/person
- frigate/+/person/snapshot
https://i.goopics.net/jke01l.jpg

On the other hand, depending on the circumstances (number of people or others), I receive a multitude of MQtt streams, with different IDs, for the same camera, the same period.
_-> look for sample the ID: 1694444269.10899-vh216y in this screen_

So I don't really know the "right" time to trigger a push to the smartphone to have: A detection, a snapshot, a Clips link.
I'm afraid of constantly triggering pushes for the same period (because there are several different IDs or constant ID Updates)

Thank you in advance for clarifying the rules of use to take into account.

**Comment by NickM-27** [comment]
The `/events` topic has 3 types for each object that is detected and tracked:
- new
- update
- end

`new` occurs when the object with `id` is first verified as a true positive object
many `update` occur in circumstances like: object enters a zone, object exits a zone, object becomes stationary, object has been stationary for 1 minute (and keeps updating every minute), object has a new best image, etc.
`end` occurs when that object stops being detected

**Comment by mostlychris** [comment]
I think my question follows along with this thread so I will ask it here rather than start a new thread. 

I upgraded from v12 to v13. After that, it seems that my alerts via Home Assistant aren't working as they used to. What I have figured out is that when a "new" type event is created, it doesn't list the zone(s) that the object entered. My automation relies on type new to tell there is a new event and won't send an alert unless an object enters a zone. This prevents people walking down the street from triggering alerts on my driveway camera, for example. Did something change between 12 and 13 that doesn't send the entered_zones on the new event but only on the update events?

**Reply by NickM-27** [reply]
That's why I have this condition and a separate condition that verifies the after_zones

```
condition: or
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'new' }}"
  - condition: template
    value_template: "{{ before_zones | length == 0 }}"
alias: new event or an object has not previously entered a zone
```

there was never a guarantee that a `new` type would have zones listed

**Reply by mostlychris** [reply]
What is the after zones condition? Also, what are you using to define "before_zones"?

**Reply by NickM-27** [reply]
Here is the whole condition block

```yaml
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['type'] == 'new' }}"
      - condition: template
        value_template: "{{ before_zones | length == 0 }}"
      - condition: template
        value_template: "{{ [\"street\"] | select(\"in\", before_zones) | list | length == 1 }}"
    alias: new event or an object has not previously entered a zone
  - condition: template
    value_template: "{{ after_zones | length > 0 }}"
    alias: Object is currently in a zone
  - condition: state
    entity_id: switch.front_cam_monitoring
    state: "on"
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ ["driveway", "side_yard", "front_yard"] | select("in", after_zones)
          | list | length > 0 }}
        alias: Object is in Driveway, Side Yard, or Front Yard
      - condition: template
        value_template: >-
          {{ label == "car" and ["street"] | select("in", after_zones) | list |
          length > 0 and after_attributes | length > 0 }}
        alias: Object is in the street and is a delivery truck
    alias: Object is in primary zone or delivery truck in street
```

**Reply by mostlychris** [reply]
That's helpful. One last question (I hope). Are before_zones and after_zones defined elsewhere in your automation? I ask because the mqtt packet returns curent_zones and entered_zones.

**Reply by NickM-27** [reply]
```yaml
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: front_cam
    value_template: "{{ value_json['after']['camera'] }}"
    variables:
      after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
      before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
      score: "{{ trigger.payload_json['after']['score'] }}"
      time_clip_start: "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"
      after_attributes: "{{ trigger.payload_json['after']['current_attributes'] }}"
```
