### DISCUSSION TITLE
nvidia docker compose file?

### DISCUSSION THREAD

**Discussion by bbrendon** [blakeblackshear/frigate#782] [Ask A Question]
Does anyone have a full compose file for nvidia? The partial snipet in the docs throws errors so I'm guessing there is more to it than documented.

**Comment by ozett** [comment]
you have to have an updated docker and docker-compose,
you have to install nvidia-driver on the host, disable the noveau-linux driver.
than install cuda-support in nvidia container,
and at the end you could use this docer compose with "    runtime: nvidia"

more info: 
https://blakeblackshear.github.io/frigate/configuration/nvdec
and -> https://github.com/blakeblackshear/frigate/issues/767

```
root@ub20-frigate4:/usr/src# cat docker-compose.yml
version: "3.9"
#version: "3.8"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    #restart: unless-stopped
    # restart: on-failure
    #restart: no

    ## image: blakeblackshear/frigate:<specify_version_tag>
    # normal
    #image: blakeblackshear/frigate:stable-amd64
    # nvidia
    image: blakeblackshear/frigate:stable-amd64nvidia
    runtime: nvidia
#    build:
#      shm_size: '2G'
#      context: .
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/src/frigate.yml:/config/config.yml:ro
      - /usr/src/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 512000000000    # ~64gb     shmz?
          #size: 16000000000 # ~16gb
          #size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      #FRIGATE_RTSP_PASSWORD: "password"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
     ```
