### DISCUSSION TITLE
Reolink Doorbell and RLC-811a support - Working with go2rtc

### DISCUSSION THREAD

**Discussion by BradleyFord** [blakeblackshear/frigate#7859] [Show and tell]
Finally got all my Reolink RLC-811a cameras up and working, and it took me a long time to get it figured out so sharing this for everyone else.
Actually I got them working without go2rtc a while ago, but never with go2rtc.

Note: This is with 0.13 Beta 1 (But potentially could work in 0.12)

**Reolink Doorbell POE**
```
go2rtc:
  log:
    format: text
    exec: trace
  streams:
    camerafrontdoor:
      - rtsp://USERNAME:PASSWORD@192.168.1.211:554/h265Preview_01_main
      - "ffmpeg:camerafrontdoor#audio=opus"    
    camerafrontdoor_sub:
      - rtsp://USERNAME:PASSWORD@192.168.1.211:554/h265Preview_01_sub
      - "ffmpeg:camerafrontdoor_sub#audio=opus"
cameras:
  Camerafrontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camerafrontdoor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camerafrontdoor_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```

**Reolink RLC-811a**
Note: a key point is the selection of h264 for the sub-stream. When running both as h265 it didnt work, then disabling the sub-stream it was ok again... until I switched it to h264.
```
go2rtc:
  log:
    format: text
    exec: trace
  streams:
    camerasideroad: 
      - rtsp://USERNAME:PASSWORD@192.168.1.185:554/h265Preview_01_main
      - "ffmpeg:camerasideroad#audio=opus"
    camerasideroad_sub:
      - rtsp://USERNAME:PASSWORD@192.168.1.185:554/h264Preview_01_sub
      - "ffmpeg:camerasideroad_sub#audio=opus"

cameras:
  CameraSideRoad:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camerasideroad?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camerasideroad_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
```
