### DISCUSSION TITLE
Webrtc in frigate live view from external go2rtc source instead of restream from bundled go2rtc

### DISCUSSION THREAD

**Discussion by dasb00ter** [blakeblackshear/frigate#7896] [Ask A Question]
I have some cameras that run bundled go2rtc to stream out rtsp. The go2rtc webui from the camera definitely will stream in RTC in chrome but when used as input rtsp for frigate I just have the jsmpeg option for the live view? Seems silly to restream from one go2rtc to another? I do have webrtc working for another camera without a bundled go2rtc using restream in the go2rtc bundled in frigate.

camera config 
```
somecamera:
#    objects:
#      track:
#        - person
#        - car    
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    ffmpeg:

      inputs:

        - path: rtsp://10.0.0.115:8554/1080p # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
      enabled: false
    motion:
      threshold: 15
      contour_area: 20
```

relevant go2rtc config from camera 
```
streams:
  1080p:

  - exec:ffmpeg -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 100 -analyzeduration 50 -probesize 50 -pix_fmt yuv420p -r 30 -i /dev/video6  -flags +global_header -movflags +empty_moov+default_base_moof+frag_keyframe -framerate 30 -video_size 1920x1080 -pix_fmt yuv420p -c:v copy -copyts -rtsp_transport tcp -f rtsp {output}
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper0 -c:a copy -muxdelay 0 -muxpreload 0 -f rtsp {output}
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper0 -c:a libfdk_aac -afterburner 1 -channels 1 -b:a 128k -profile:a aac_he -ar 16000 -strict experimental -muxdelay 0 -muxpreload 0 -ac:a 1 -f rtsp {output}
# libopus has higher cpu requirements, audio may studder.
#  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper0 -c:a libopus -muxdelay 0 -muxpreload 0 -ac:a 1 -af adelay=0|0 -f rtsp {output}
```

not sure but maybe an audio problem looks like aac is there and so I wont get webrtc but should get MSE? 
Looking for some direction. Thanks
