### DISCUSSION TITLE
Harware Acceleration on a Synology DS918+

### DISCUSSION THREAD

**Discussion by chinswain** [blakeblackshear/frigate#7899] [General]
Hi all,

I've installed Frigate on my Synology DS918+ (Running DSM 7.2).
I attached a Coral USB accelerator this morning which appears to have been found:

![image](https://github.com/blakeblackshear/frigate/assets/4403897/f1f9ecc1-9d5f-47c6-838b-487e5725be02)

My question is, can I use hardware acceleration? I believe the DS918+ has an Intel Celeron J3455 CPU.
After some googling and searching past discussions on here, I've added an environmental variable: LIBVA_DRIVER_NAME='i965' and added the below to my config.yml:

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
 ```

I get this error from Frigate - which I believe is expected on Synology, is there any way to verify hardware acceleration is working?
![image](https://github.com/blakeblackshear/frigate/assets/4403897/5bd26ebd-c1a3-4484-8e57-25b4f8a58ba0)

Frigate config.yml
```yaml
mqtt:
  host: xxx.xxx.xx.xx
  user: xxxxxx
  password: xxxxxx
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  kitchen:
   objects:
    track:
      - person
      - cat   
   ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxx@xxx.xx.xx.xx:8554/unicast
          roles:
            - detect
            - rtmp
            - record
   snapshots:
      enabled: True
   record:
      enabled: True
      retain:
       days: 5
      events:
       retain:
        default: 10      
go2rtc:
  streams:
    kitchen:
      - rtsp://xxxxxx:xxxxxx@xxx.xxx.xx.xx:8554/unicast  
``` 

Docker created with:

```
docker run -d \
--name frigate \
--restart=unless-stopped \
--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
--device /dev/bus/usb:/dev/bus/usb \
--device /dev/dri/renderD128 \
--shm-size=640m \
--privileged \
-v /volume1/video:/media/frigate \
-v /volume2/docker/frigate/config.yml:/config/config.yml \
-v /etc/localtime:/etc/localtime:ro \
-v /dev/bus/usb:/dev/bus/usb \
-e FRIGATE_RTSP_PASSWORD='xxxxxx' \
-e LIBVA_DRIVER_NAME='i965'\
-p 5200:5000 \
-p 1984:1984\
-p 8554:8554 \
-p 8555:8555/tcp \
-p 8555:8555/udp \
ghcr.io/blakeblackshear/frigate:stable
```
