### DISCUSSION TITLE
How to fix green picture on Raspberry Pi 4B? h264_v4l2m2m "can't configure decoder"

### DISCUSSION THREAD

**Discussion by nuansed** [blakeblackshear/frigate#795] [Ask A Question]
Hi! 

I'm running Frigate as follows: 
Hardware: Raspberry Pi 4B 4GB
Detector: USB Google Coral
OS: Home Assistant Operating System
Frigate: Home Assistant Add-on: Frigate NVR v1.10, with Protection mode DISABLED
Camera stream: H264 12FPS

When enabling hardware acceleration by adding the following into frigate.yml, all streams in Frigate only display a solid, unchanging green frame: 
![Screenshot 2021-02-13 at 9 35 15 PM](https://user-images.githubusercontent.com/12543435/107851274-b7c5f480-6e43-11eb-85f1-cc3d96f7b482.jpg)

This is my frigate.yml: 
```
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
  Hikvision1:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.10:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
```

When removing the following from the config, the stream from the camera is displayed correctly, but only at 2-3 FPS:  
```
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
```

The ffmpeg debug logs show the following: 
```
ffmpeg.HikVision1-high.detect  ERROR   : Successfully parsed a group of options.
ffmpeg.HikVision1-high.detect  ERROR   : Opening an output file: pipe:.
ffmpeg.HikVision1-high.detect  ERROR   : [pipe @ 0x559fef7ef0] Setting default whitelist 'crypto,data'
ffmpeg.HikVision1-high.detect  ERROR   : Successfully opened the file.
ffmpeg.HikVision1-high.detect  ERROR   : [h264_mp4toannexb @ 0x559fef3300] The input looks like it is Annex B already
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video12
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video11
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video10
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video16
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video15
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video14
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] probing device /dev/video13
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] Could not find a valid device
ffmpeg.HikVision1-high.detect  ERROR   : [h264_v4l2m2m @ 0x55a0405120] can't configure decoder
ffmpeg.HikVision1-high.detect  ERROR   : Stream mapping:
ffmpeg.HikVision1-high.detect  ERROR   :   Stream #0:0 -> #0:0 (copy)
ffmpeg.HikVision1-high.detect  ERROR   :   Stream #0:0 -> #1:0 (copy)
ffmpeg.HikVision1-high.detect  ERROR   :   Stream #0:1 -> #1:1 (copy)
ffmpeg.HikVision1-high.detect  ERROR   :   Stream #0:0 -> #2:0 (h264 (h264_v4l2m2m) -> rawvideo (native))
ffmpeg.HikVision1-high.detect  ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
ffmpeg.HikVision1-high.detect  ERROR   : [AVIOContext @ 0x55a0405560] Statistics: 0 seeks, 0 writeouts
ffmpeg.HikVision1-high.detect  ERROR   : [rtmp @ 0x559ff14790] UnPublishing stream...
ffmpeg.HikVision1-high.detect  ERROR   : [rtmp @ 0x559ff14790] Deleting stream...
ffmpeg.HikVision1-high.detect  ERROR   : [AVIOContext @ 0x559ff01d80] Statistics: 0 seeks, 0 writeouts
frigate.video                  INFO    : HikVision1-high: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : HikVision1-high: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : HikVision1-high: ffmpeg process is not running. exiting capture thread...
```

This stands out to me: 
**_h264_v4l2m2m Could not find a valid device / can't configure decoder_**

Since I'm running Home Assistant Operating System, I can't configure things like gpu_mem. 
Instead of the h264_v4l2m2m option, I have also tried  h264_mmal (unsuccessfully). 
Protection mode is disabled.
