### DISCUSSION TITLE
Trying to avoid recording cars on the road especially on the exports.

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#7953] [Ask A Question] [answered]
I have a camera configured.

```
  front: # <------ Name the camera
    ffmpeg:
      inputs:
      - path: rtsp://frigate:8554/front   # <--- the name here must match the name of the camera in restream
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@ip_camera01:554/cam/realmonitor?channel=1&subtype=1       # <--- the name here must match the name of the camera in restream
        roles:
        - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 864  # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 8.0
      stationary:
        max_frames:
          objects:
            person: 300

    motion:
      mask:
      - 830,17,833,41,576,41,575,14 # timestamp
      delta_alpha: 0.4
      improve_contrast: false
      threshold: 45
      contour_area: 25

    snapshots:
      required_zones:
      - driveway
      - yard
      - gargae
      - road
    objects:
      filters:
        car:
          min_score: 0.8
          threshold: 0.85
          mask: [] # 347,251,517,248,524,175,356,182
        person:
          mask: 575,222,576,192,504,192,502,221
          # min_ratio: 0.2
          max_ratio: 0.90
          min_score: 0.78
          # threshold: 0.88
    record:
      events:
        required_zones:
        - driveway
        - yard
        - gargae
        retain:
          default: 7
          mode: active_objects


    zones:
      driveway:
        coordinates: 215,480,854,480,854,400,694,244,527,133,343,159,128,205
        objects:
        - car
      yard:
        coordinates: 854,480,854,157,714,83,367,95,0,145,0,480
        # 790,480,854,256,801,214,780,0,478,0,392,104,486,117,433,246,225,249,33,480
        objects:
        - person
        - bicycle
      road:
        coordinates: 0,48,0,126,220,84,451,64,608,61,803,64,796,0,487,0,180,0
        objects:
        - car
        - bus
        - truck
        filters:
          car:
            threshold: 0.85
            min_area: 11000
      garage:
        coordinates: 191,445,211,480,854,480,854,380,765,310
        objects:
        - car
```

and a global record section that looks like 

```
record:
  enabled: true
  events:
    pre_capture: 8
    post_capture: 8
    objects:
    - person
    - car
    - bird
    - cat
    - dog
    retain:
      default: 10
      mode: active_objects
      objects:
        person: 15
        car: 15
```

I wan to capture a snapshot of the car on the road zone, but don't want to record them. However I want to record things like cars on the driveway, person in yard and car in garage. Is this config correct?  Looks like I am still seeing car on road in the VOD api m3u8 when exporting the events. I want clean up the exports to only events in the required zones.
