### DISCUSSION TITLE
Process Frigate images with DeepStack, Facebox, CompreFace, and AWS Rekognition

### DISCUSSION THREAD

**Discussion by jakowenko** [blakeblackshear/frigate#801] [Show and tell]
[![Double Take](https://badgen.net/github/release/jakowenko/double-take/stable)](https://github.com/jakowenko/double-take) [![Double Take](https://badgen.net/github/stars/jakowenko/double-take)](https://github.com/jakowenko/double-take/stargazers) [![Docker Pulls](https://flat.badgen.net/docker/pulls/jakowenko/double-take)](https://hub.docker.com/r/jakowenko/double-take) [![Discord](https://flat.badgen.net/discord/members/3pumsskdN5?label=Discord)](https://discord.gg/3pumsskdN5)

# Double Take

Unified UI and API for processing and training images for facial recognition.

<p align="center">
  <img src="https://user-images.githubusercontent.com/1081811/126434926-cf2275f7-f3a8-43eb-adc2-903c0071f7d1.jpg" width="100%">
</p>

## Why?

There's a lot of great open source software to perform facial recognition, but each of them behave differently. Double Take was created to abstract the complexities of the detection services and combine them into an easy to use UI and API.

## Features

- UI and API bundled into single Docker image
- Ability to password protect UI and API
- Support for multiple detectors
- Train and untrain images for subjects
- Process images from NVRs
- Publish results to MQTT topics
- REST API can be invoked by other applications

### Supported Detectors

- [DeepStack](https://deepstack.cc) v2021.02.1-2021.06.01
- [CompreFace](https://github.com/exadel-inc/CompreFace) v0.5.0-0.5.1
- [Facebox](https://machinebox.io)

### Supported NVRs

- [Frigate](https://github.com/blakeblackshear/frigate) v0.8.0-0.9.0

### [Frigate](https://github.com/blakeblackshear/frigate)

Subscribe to Frigate's MQTT topics and process images for analysis.

```yaml
mqtt:
  host: 192.168.1.1

frigate:
  url: http://192.168.1.1:5000
```

When the `frigate/events` topic is updated the API begins to process the [`snapshot.jpg`](https://blakeblackshear.github.io/frigate/usage/api/#apieventsidsnapshotjpg) and [`latest.jpg`](https://blakeblackshear.github.io/frigate/usage/api/#apicamera_namelatestjpgh300) images from Frigate's API. These images are passed from the API to the configured detector(s) until a match is found that meets the configured requirements. To improve the chances of finding a match, the processing of the images will repeat until the amount of retries is exhausted or a match is found.

When the `frigate/+/person/snapshot` topic is updated the API will process that image with the configured detector(s). It is recommended to increase the MQTT snapshot size in the [Frigate camera config](https://blakeblackshear.github.io/frigate/configuration/cameras#full-example).

```yaml
cameras:
  front-door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
```

If a match is found the image is saved to `/.storage/matches/${filename}`.

### [Home Assistant](https://www.home-assistant.io)

Trigger automations / notifications when images are processed.

If the MQTT integration is configured within Home Assistant, then sensors will automatically be created.

#### Notification Automation

```yaml
alias: Notify
trigger:
  - platform: state
    entity_id: sensor.double_take_david
  - platform: state
    entity_id: sensor.double_take_unknown
condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
action:
  - service: notify.mobile_app
    data:
      message: >-
        {{trigger.to_state.attributes.friendly_name}} is near the
        {{trigger.to_state.state}} @
        {{trigger.to_state.attributes.match.confidence}}% by
        {{trigger.to_state.attributes.match.detector}}:{{trigger.to_state.attributes.match.type}}
        taking {{trigger.to_state.attributes.attempts}} attempt(s) @
        {{trigger.to_state.attributes.duration}} sec
      data:
        attachment:
          url: http://192.168.1.2:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}
        actions:
          - action: URI
            title: View Image
            uri: http://192.168.1.2:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}
```

I was hoping for feedback from the community and wanted to see if others would find something like this useful.

Github: https://github.com/jakowenko/double-take
Docker Hub: https://hub.docker.com/r/jakowenko/double-take

**Comment by hawkeye217** [comment]
I do something similar but I just use HA automations and the Facebox integration (https://www.home-assistant.io/integrations/facebox/) 

Looks like your solution could work for folks on other home automation platforms too.

**Reply by jakowenko** [reply]
How are you liking that integration? The main difference I see is that the Facebox integration relies on that camera entity being updated to perform the processing, right?  So you would need to have an entity setup for each camera and then process the jpgs with the integration. 

The way my current API works is that when a Frigate event is POSTed to it, it will process up to X number of snapshot.jpg images from Frigate for that event ID and also process the latest.jpg images from that camera feed. So it's looking at two images at once and looping that process until the threshold is met or a match is found.

**Reply by hawkeye217** [reply]
Yeah, your method as described works better than my existing setup.  I just have a ```local_file``` camera entity that gets updated with the image from Frigate based on the mqtt message (using the ```camera.snapshot``` service), and then I call ```image_processing.detect_face``` on that generic camera entity.

**Reply by jakowenko** [reply]
Ya that makes sense. I wanted to process as many images as possible within reason when a new event comes in to better increase the chances of finding a matching face.

If you end up trying this out and run into any issues, let me know!

**Reply by hawkeye217** [reply]
Definitely. Thanks for the contribution!

**Comment by jakowenko** [comment]
I recently added support for subscribing and publishing to MQTT directly, instead of the REST API having to be invoked.

Also found out about the the [CompreFace](https://github.com/exadel-inc/CompreFace) project and added support for their facial recognition. So far the results have been pretty promising!

README now includes all the configuration options that can be passed to the Docker container.

https://github.com/jakowenko/double-take

**Comment by jakowenko** [comment]
I've made quite a few updates over the past few weeks including support for DeepStack and added a lot more information in the [README](https://github.com/jakowenko/double-take#readme).

I'm going to work on supporting just face detection next since DeepStack supports that out of the box.

**Comment by jakowenko** [comment]
I've made quite a few UI updates over the past few weeks and the root of the API at `http://YOUR-IP:PORT` will now serve a frontend that shows all matches and misses from the detectors. You can either retrain the models with the images or delete them. More updates to follow!

<img src="https://community-assets.home-assistant.io/original/3X/8/3/83675c23e56fa5750b6a7faef8a77a00d33ac96a.png">

**Comment by jakowenko** [comment]
I pushed quite a few updates and small performance improvements last night. If you are using multiple detectors, then the same image is passed on each processing loop. This allows me to display a single image on the UI with the results per detector.

<img src="https://user-images.githubusercontent.com/1081811/116505792-cc822800-a889-11eb-91f3-f6a192767aa8.png" width="100%">

I've also added some more [documentation](https://github.com/jakowenko/double-take/blob/master/docs/home-assistant-node-red.md) on how I setup my Node-Red and Home Assistant notifications.

More notes on what's included in this release can be found [here](https://github.com/jakowenko/double-take/releases/tag/v0.3.2).

**Comment by jakowenko** [comment]
More updates 🚀

Frigate's `config.yml` file inspired me to do the same.

- I've migrated the ENV variables to a more readable [`config.yml`](https://github.com/jakowenko/double-take#configuration) file.
  Here's a small sample:
  ```yaml
  server:
    port: 3000

  mqtt:
    host: 192.168.1.1

  home_assistant:
    url: http://192.168.1.1:8123
    token: xxx.xxx-xxx

  confidence:
    match: 60
    unknown: 40

  save:
    matches: true
    unknown: true

  frigate:
    url: http://192.168.1.1:4000

  detectors:
    compreface:
      url: http://192.168.1.1:8000
      key: xxx-xxx-xxx-xxx-xxx
    deepstack:
      url: http://192.168.1.1:8001
  ```
- Added Home Assistant support. Entities for people and cameras will automatically be created

Any feedback or feature suggestions would be appreciated.

**Reply by Alfiegerner** [reply]
I'm currently testing out compreface and deepstack with this, working really well thanks.

I find compreface more reliable and faster, and thinking there's little value running both. What's your experience with the different detectors @jakowenko ?

**Reply by jakowenko** [reply]
@Alfiegerner I also run CompreFace and DeepStack side by side. CompreFace is the clear winner for me too. I agree, if you're happy with the results from CompreFace, then there's not much value in running DeepStack.

I do want to add support for object recognition in the future which DeepStack supports. But that's still a little ways out. Need to figure out how to best fit it in with the UI.

**Comment by jakowenko** [comment]
Just released [v0.6.0](https://github.com/jakowenko/double-take/releases/tag/v0.6.0) which now includes the processing of Frigate's snapshot MQTT image.

### Added
- UI: /config route to make live config changes
- UI: /files route to view currently trained images
- API: process Frigate snapshot MQTT messages
- API: support for CompreFace plugins

**Comment by osos** [comment]
What is the best way to install CompreFace and/or Deepstack to use with double-take?

Could you provide full docker-compose examples with double-take and compreface ?
Any specific settings you recommend?

**Reply by jakowenko** [reply]
Here's what a Double Take and DeepStack docker-compose file would look like.

```yaml
version: '3.7'

services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take:beta
    restart: unless-stopped
    volumes:
       - ${PWD}/double-take/storage:/.storage
    ports:
      - 3000:3000

  deepstack:
    container_name: deepstack
    image: deepquestai/deepstack
    restart: unless-stopped
    environment:
      VISION-FACE: 'True'
      VISION-DETECTION: 'True'
      MODE: High
    volumes:
      - ${PWD}/deepstack:/datastore
    ports:
      - 5000:5000
```

For CompreFace, I use the [docker-compose](https://github.com/exadel-inc/CompreFace/blob/master/docker-compose.yml) and [.env](https://github.com/exadel-inc/CompreFace/blob/master/.env) file from their GitHub

**Comment by D34DC3N73R** [comment]
If I have frigate set up in double-take, do I need to also define cameras in double-take? My current config is below for reference
```
# Double Take
server:
  port: 3000

mqtt:
  host: 192.168.0.178
  username: user
  password: pass
  topics:
    frigate: frigate/events
    matches: double-take/matches
    cameras: double-take/cameras

confidence:
  match: 60
  unknown: 40

objects:
  face:
    min_area_match: 10000

save:
  matches: true
  unknown: true

purge:
  matches: 168
  unknown: 8

frigate:
  url: http://192.168.0.178:5000 #doesn't work with http://frigate:5000 
  image:
    height: 500
  attempts:
    latest: 10
    snapshot: 0
  cameras:
    - front1
    - front2
    - back1
    - back2
    - side1
    - side2
    - doorbell
#  zones:
#    - camera: driveway
#      zone: zone-1

#cameras:
#  driveway:
#    snapshot:
#      topic: driveway/snapshot
#      url: http://192.168.1.1/latest.jpg

detectors:
#  compreface:
#    url: http://192.168.1.1:8000
#    key: xxx-xxx-xxx-xxx-xxx # key from recognition service in created app
  deepstack:
    url: http://deepstack:5000
#    key: xxx-xxx-xxx-xxx-xxx # optional api key
#  facebox:
#    url: http://192.168.1.1:8002

time:
  format: F
  timezone: America/Los_Angeles
```

sidenote, it seems like double-take has an issue connecting to frigate when using docker dns.
frigate:
  url: http://frigate:5000
![image](https://user-images.githubusercontent.com/9123670/126014549-9f895c49-5307-435e-8936-86f607aa1dcf.png)
frigate:
  url: http://192.168.0.178:5000
![image](https://user-images.githubusercontent.com/9123670/126014612-0db6b063-930d-4e32-9112-545821bd5934.png)
```
$ docker exec -it double-take ping frigate:5000
PING frigate:5000 (172.18.0.31): 56 data bytes
64 bytes from 172.18.0.31: seq=0 ttl=64 time=0.157 ms
64 bytes from 172.18.0.31: seq=1 ttl=64 time=0.064 ms
64 bytes from 172.18.0.31: seq=2 ttl=64 time=0.046 ms
64 bytes from 172.18.0.31: seq=3 ttl=64 time=0.052 ms
^C
--- frigate:5000 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.046/0.079/0.157 ms
```

**Reply by jakowenko** [reply]
Hey, thanks for checking out my project. You don't need to define the Frigate cameras if you want to process images from all of them. Also, if you want to keep your config file a little slimmer, you can remove any of the default settings you have in there, such as the server port. Any of those will be automatically applied unless overwritten.

Good catch on the DNS resolution. The UI was hitting the Frigate URL directly which would've been client side. I pushed an update to the beta build to proxy this through the API so it resolves. I was able to test it with my setup and it's working as intended. Let me know if this fixes your issue.

Let me know if you have any other suggestions or run into issues.

**Reply by D34DC3N73R** [reply]
Yeah I'm just trying it out for the first time, so I wanted all the default configs mainly as a reference while messing around. 

For cameras, I'm talking about the separate `cameras:` section. Is that just for cameras not part of frigate?

**Reply by jakowenko** [reply]
You don't need to worry about that extra camera section. That allows you to define other cameras outside of Frigate.

**Reply by D34DC3N73R** [reply]
Thanks for the info. I thought that was the case but wanted to double check. I thought they might be used as the photos in your HA notifications. BTW, could you post a sample notification? Your previous link seems to be broken (https://github.com/jakowenko/double-take/blob/master/docs/home-assistant-node-red.md)

Also, docker dns is now working for frigate - Thanks!

**Reply by jakowenko** [reply]
Here's what my HA notification looks like. Replace the `IP-ADDRESS` below with yours. Let me know if this works for you. It will only send a notification when the state has changed for the trigger entities.

```yaml
alias: Notify
description: ''
trigger:
  - platform: state
    entity_id: sensor.double_take_david
condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
action:
  - service: notify.mobile_app_iphone
    data:
      message: >-
        {{trigger.to_state.attributes.friendly_name}} is near the
        {{trigger.to_state.state}} @
        {{trigger.to_state.attributes.match.confidence}}% by
        {{trigger.to_state.attributes.match.detector}}:{{trigger.to_state.attributes.match.type}}
        taking {{trigger.to_state.attributes.attempts}} attempt(s) @
        {{trigger.to_state.attributes.duration}} sec
      data:
        attachment:
          url: >-
            http://IP-ADDRESS:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true
mode: single
```
