### DISCUSSION TITLE
[Intel NUC7i5BNH] Another "Reduce CPU load" guy

### DISCUSSION THREAD

**Discussion by SHU-red** [blakeblackshear/frigate#8048] [Ask A Question] [answered]
I know that there are already many threads out there for reducing CPU load for transcoding but im an absolute noob in ffmeg, transcoding, different drivers and the hardware-combination for that

So im trying to ask for help, where i can reduce the cpu load of my Intel NUC7i5BNH
--> So its a 7th gen Intel i5

I already decreased the main streams of my two IP Cameras to h264-1280x720
But i dont see a very big impact on the CPU load

This is my current state of my config-file and i have no idea where to start
Maybe someone can give me a hint

Is it possible to correctly setup HW-Acceleration on this thing because in the docs there is a section for 'Intel QSV with h264 stream'

Thanks a lot

```
mqtt:
  host: 192.168.178.55
  port: 1883
  user: admin
  password: xxxx
birdseye:
  enabled: False
  mode: motion
ffmpeg:
  output_args:
    record: -f segment -segment_time 20 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
  hwaccel_args: preset-intel-qsv-h264
objects:
	track:
    - person
    - car
    - cat
    - dog
    - horse
snapshots:
  enabled: True
  clean_copy: False
record:
  enabled: True
  retain:
    days: 14
    mode: active_objects
  events:
    retain:
      default: 21
      mode: active_objects
cameras:
  front_door:
    ffmpeg:
      inputs:
       	- path: rtsp://admin:xxx@192.168.178.120:554/live/main
          input_args: preset-rtsp-generic
          roles:
            - detect
            - rtmp
    birdseye:
      enabled: False
    detect:
      #width: 2304
      #height: 1296
      #width: 704
      #height: 576
      #width: 1920
      #height: 1080
      width: 1280
      height: 720
  garage:
    ffmpeg:
      inputs:
       	- path: rtsp://admin:xxx@192.168.178.121:554/live/main
          input_args: preset-rtsp-generic
          roles:
            - detect
            - rtmp
    birdseye:
      enabled: False
    detect:
      #width: 2304
      #height: 1296
      #width: 704
      #height: 576
      #width: 1920
      #height: 1080
      width: 1280
      height: 720
```

**Comment by NickM-27** [comment]
1. I'd suggest using `preset-vaapi` instead
2. are you not able to use sub streams on these cameras?
3. can you show a screenshot of the system page so we can see the different CPU usages

**Reply by SHU-red** [reply]
Thanks for your fast reply!
Below the frigate and top shown load

I fear my config file is a bit messy and im scared to screw this up
I'll try the preset-vaapi also but can you please describe in detail what i have to do? Otherwise i think i will screw this up -.-'

![2023-10-03-170139_grim](https://github.com/blakeblackshear/frigate/assets/68030498/2631d017-f4c8-428a-aefe-df3626f9abdc)
![2023-10-03-170159_grim](https://github.com/blakeblackshear/frigate/assets/68030498/8e211d37-f807-4b6d-829d-5e85ae780751)

**Reply by SHU-red** [reply]
And btw im using Fedora CoreOS which is only a very lightweight OS

**Reply by NickM-27** [reply, marked as answer]
Oh, looks like your main cpu usage is because you are not using openvino, you are running detect on your CPU https://docs.frigate.video/configuration/detectors#openvino-detector

for the other one just change `preset-intel-qsv-h264` to `preset-vaapi`

**Reply by SHU-red** [reply]
Oh Crazy!
I neves stumbled upon this

I just added
```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

And now the CPU load is drastically lower
![2023-10-03-171142_grim](https://github.com/blakeblackshear/frigate/assets/68030498/da97029c-b37e-4b8b-8efc-547dd398bdcd)


Thank you so much!!!

Last question: I do not have to change the model widht and height to the video-stream widht and height right?
