### DISCUSSION TITLE
Recordings are not saved more than 4 hours

### DISCUSSION THREAD

**Discussion by ronniekw** [blakeblackshear/frigate#8050] [Ask A Question]
Hi,

I have a problem with my recorings that are not retained more than aprox 4 hours.  In my world I have configured this to 7 days for all my three cameras.

config.yml:

```
mqtt:
  enabled: false

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb
    
ffmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration
  output_args:
    record: preset-record-generic-audio-aac

cameras:
  QF003_back: #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://192.168.14.106:554/user=***&password=***=&channel=1&stream=1.sdp #The Stream you want to monitor
          roles:
            - detect
        - path: rtsp://192.168.14.106:554/user=***&password=&channel=1&stream=0.sdp #The Stream you want to monitor
          roles:
            - record
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 7
        mode: all
    detect:
      enabled: true # Detection is disabled
      width: 740 # The Cameras resolution
      height: 480 # The Cameras resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - bird
        - dog
        - cat
        - bicycle
        - motorcycle
  Dahua: #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.14.103:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://***:***@192.168.14.103:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 7
        mode: all
    detect:
      enabled: true # Detection is disabled
      width: 704 # The Cameras resolution
      height: 576 # The Cameras resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - bird
        - dog
        - cat
        - bicycle
        - motorcycle
  Axis: #Name for your comment
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.14.110:554/mpeg4/media.3gp
          roles:
            - record
    record: # <----- Enable recording
      enabled: True
      retain:
        days: 7
        mode: all
    detect:
      enabled: false # Detection is disabled
```

Any thoughts?

Regards
Ronnie

**Comment by NickM-27** [comment]
check your logs

**Reply by ronniekw** [reply]
Logging from Frigate GUI :

2023-10-03 17:17:34.977804664  [INFO] Starting Frigate...
2023-10-03 17:17:38.347170986  [2023-10-03 17:17:38] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-03 17:17:38.428250898  [2023-10-03 17:17:38] peewee_migrate                 INFO    : Starting migrations
2023-10-03 17:17:38.441665182  [2023-10-03 17:17:38] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-03 17:17:38.495631440  [2023-10-03 17:17:38] frigate.app                    INFO    : Output process started: 290
2023-10-03 17:17:38.511618808  [2023-10-03 17:17:38] frigate.app                    INFO    : Camera processor started for QF003_back: 295
2023-10-03 17:17:38.531100985  [2023-10-03 17:17:38] frigate.app                    INFO    : Camera processor started for Dahua: 297
2023-10-03 17:17:38.546460124  [2023-10-03 17:17:38] frigate.app                    INFO    : Camera processor started for Axis: 299
2023-10-03 17:17:38.569551534  [2023-10-03 17:17:38] frigate.app                    INFO    : Capture process started for QF003_back: 302
2023-10-03 17:17:38.583105241  [2023-10-03 17:17:38] frigate.app                    INFO    : Capture process started for Dahua: 303
2023-10-03 17:17:38.609582518  [2023-10-03 17:17:38] frigate.app                    INFO    : Capture process started for Axis: 305
2023-10-03 17:17:41.211152393  [2023-10-03 17:17:38] detector.coral                 INFO    : Starting detection process: 289
2023-10-03 17:17:41.227848971  [2023-10-03 17:17:38] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-03 17:17:41.228631346  [2023-10-03 17:17:41] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

**Reply by NickM-27** [reply]
can you send a picture of the storage page in the frigate webui

**Reply by ronniekw** [reply]
![image](https://github.com/blakeblackshear/frigate/assets/52671597/09d2c402-7979-41a5-a7f1-c3615296925c)

**Reply by ronniekw** [reply]
I'm storing all recordings on an USB disk with 10 TB. Is it not strange that the Data total storage is only 30.34 GB? My Pi SDHC has 32 GB.

**Reply by ronniekw** [reply]
Maybe my storage record i docker-compose.yml is wrong?

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ronnie/frigate-nvr/config.yml:/config/config.yml
      - /media/ronnie/Elements/frigate-recordings/:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000

**Reply by NickM-27** [reply]
Yeah, the medium used for storage is not nearly enough. 

If that's not correct then I'd look into the args used for mounting.

**Reply by ronniekw** [reply]
Any ideas what to correct?

My USB disk is on /media/ronnie/Elements/frigate-recordings/

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10 #Map the Pi hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ronnie/frigate-nvr/config.yml:/config/config.yml
      - /media/ronnie/Elements/frigate-recordings/:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ***

**Reply by didi3r** [reply]
This happened to me once, it turned out that when Ubuntu booted the docker container started before the external drive was mounted. Resulting in frigate writing in the internal disk. 

I had to create a docker volume:

```yml
volumes:
  frigate:
    driver: local
    driver_opts:
      type: none
      device: /mnt/path
      o: bind
```

Then use that volume instead:

```yml
frigate:
  ...
  volumes:
    - frigate:/media/frigate
```

That forces docker to not to start the container until the volume is actually mounted.
