### DISCUSSION TITLE
Why is my object detection triggered even without motion?

### DISCUSSION THREAD

**Discussion by vajonam** [blakeblackshear/frigate#8082] [Ask A Question] [answered]
I am running ` 0.13.0-9A4F970` . Dont understand why the object detection in kicking in all t he time, even when there is no motion detected, what am I missing? 

https://github.com/blakeblackshear/frigate/assets/152501/bd6696e1-f7d6-465d-8756-a03d414957ac

```
front: # <------ Name the camera
    ffmpeg:
      inputs:
      - path: rtsp://frigate:8554/front   # <--- the name here must match the name of the camera in restream
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: 
          rtsp://admin:{FRIGATE_RTSP_PASSWORD}@ip_camera01:554/cam/realmonitor?channel=1&subtype=1       # <--- the name here must match the name of the camera in restream
        roles:
        - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 864  # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 8.0
      # stationary:
      #   max_frames:
      #     objects:
      #       person: 300

    motion:
      mask:
      - 830,17,833,41,576,41,575,14 # timestamp
      delta_alpha: 0.4
      improve_contrast: false
      threshold: 45
      contour_area: 25

    snapshots:
      required_zones:
      - driveway
      - yard
      - garage
      - road
    objects:
      filters:
        car:
          min_score: 0.8
          threshold: 0.85
          mask: []    # 347,251,517,248,524,175,356,182
          #- 523,186,399,215,448,266,574,230
        person:
          mask: []
          # 575,222,576,192,504,192,502,221
          # min_ratio: 0.2
          max_ratio: 0.90
          min_score: 0.78
          # threshold: 0.88
        bicycle:
          mask: 147,385,187,480,35,480,40,400
    record:
      events:
        required_zones:
        - driveway
        - yard
        - garage
        retain:
          mode: active_objects


    zones:
      driveway:
        # inertia: 3
        coordinates: 215,480,854,480,854,400,694,244,527,133,343,159,128,205
        objects:
        - car
      yard:
        coordinates: 854,480,854,157,714,83,367,95,0,145,0,480
        # 790,480,854,256,801,214,780,0,478,0,392,104,486,117,433,246,225,249,33,480
        # inertia: 3
        objects:
        - person
        - bicycle
      road:
        coordinates: 0,48,0,126,220,84,451,64,608,61,803,64,796,0,487,0,180,0
        objects:
        - car
        - bus
        - truck
        filters:
          car:
            threshold: 0.85
            min_area: 11000

      garage:
        coordinates: 570,437,211,480,854,480,864,392
        # intertia: 3
        objects:
        - car

    ui:
      order: 2
```
