### DISCUSSION TITLE
Questions regarding Frigate on it's own server with the HA Frigate integration

### DISCUSSION THREAD

**Discussion by yuckypants** [blakeblackshear/frigate#8102] [Ask A Question]
I have HA running on an RPi4 and Frigate running bare metal using docker. I have notifications set up thru HA using the blueprint from SgtBatten and am using the stable branch. 

On my Frigate config, I have zones configured to only pick up objects in specific areas, but in HA I constantly get notifications in these areas. They ARE the objects I defined, but I've literally masked off an entire section, yet keep getting object detection in this section. One of the notifications I regularly get is a light fixture on the wall, that doesn't move, but thinks is a "person."

1. Does HA respect the zones or is a separate config required? 
2. If HA does respect the zones, can someone see where I've gone wrong? 

My frigate.yml is below: 

```
mqtt:
  enabled: true
  host: myhost
  user: myuser
  password: mypassword

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous
  quality: 8

detect:
  enabled: True
  width: 1920
  height: 1080
  stationary:
    interval: 0
    threshold: 50

objects:
  track:
    - person
    - dog
    - cat
    - car
    - motorcycle
    - bird

go2rtc:
  streams:
    rtsp_cam_frontDoor:
      - rtsp://myuser:mypassword@192.168.1.1:554/live0
      - "ffmpeg:rtsp_cam_frontDoor#audio=opus"
    rtsp_cam_frontDoor_sub:
      - rtsp://myuser:mypassword@192.168.1.1:554/live1
      - "ffmpeg:rtsp_cam_frontDoor_sub#audio=opus"

snapshots:
  enabled: true
  retain:
    default: 3
  clean_copy: false
  
cameras:
  frontDoor:
    ffmpeg:
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://myuser:mypassword@192.168.1.1/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      hwaccel_args: preset-vaapi
    motion: 
      threshold: 40
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 3
          mode: active_objects
          objects:
            dog: 1
            cat: 1
            person: 3
            car: 3
            motorcycle: 3
            bird: 1
        required_zones:
          - entry_area
    zones:
      entry_area:
        coordinates: 1579,495,1040,626,891,266,1137,271,1205,259,1233,0,666,0,516,56,522,126,490,129,509,346,518,463,690,465,994,1080,1920,1080,1920,522,1607,360,1522,324
        objects:
          - person
          - dog
          - cat
      street:
        coordinates: 1382,227,1403,59,1850,237,1920,320,1920,509,1440,274
        objects:
          - dog
          - cat
    live:
      stream_name: rtsp_cam_frontDoor_sub
```

**Comment by NickM-27** [comment]
You need to filter the MQTT messages in HA based on what you want notifications for

**Reply by yuckypants** [reply]
I filtered them in HA using the notification blueprint - this is not enough? 

```
alias: "Notification: Front Door Camera"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frontdoor
    notify_device: 59645d17abc0a69c553b3374c7dd7bd6
    labels:
      - person
      - package
      - dog
      - cat
    zones:
      - entry_area
    zone_filter: true
```

How do I filter the MQTT messages in HA otherwise? Not sure I know how.
