### DISCUSSION TITLE
Synology DS718+ DSM 7.2 Update 3 With Coral USB using Container Manager

### DISCUSSION THREAD

**Discussion by chrisuthe** [blakeblackshear/frigate#8127] [Show and tell]
Hello all, after a bit of trail and error I got Frigate running successfully on my Synology DS718+ (Celeron J3455) using the currently latest DSM version (7.2-64570 Update 3) with the Coral USB TPU by creating the frigate container in container manager.

### For the Coral USB detection
I have installed from the SynoCommunity:
"SynoKernel USB Serial drivers"
"SynoCLI Kernel Tools" 
**I am unsure if either of these are required or doing anything but they were already installed prior to me starting setup so I wanted to ensure I listed them**
My Coral is plugged into a front USB port on my Syno and I have restarted syno since plugging it in

Here is what shows under "Control Panel -> Info Center -> Hardware": 
![image](https://github.com/blakeblackshear/frigate/assets/26907395/edf7e528-b645-4444-956e-2ecf66bfdefb)

As you can see I have a Zwave stick, a UPS and the Coral plugged in and detected.

### Other packages that might be relevant: 
FFmpeg 4
Python 2
PHP 7.4
Advanced Media Extensions
(Again, these may have zero to do with this working, I am not a docker or frigate guru by any stretch)

### Setup/Install on Syno

First I created a new folder in /volume1/docker/ called frigate - I had previously used the "Docker" package to run Home Assistant and others prior to upgrading to 7.2.x so this is my first project but the path /docker/ existed)

I created a new project in Container Manager and named it frigate. 

I selected create YAML, and this is the sanitized version (customize volumes as needed):

>version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
         - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config/:/config/
      - /volume1/frigate-media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5005:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - LIBVA_DRIVER_NAME=i965 # if hwacl isn't working properly with the default iHD driver

As you can see it's a mix of the default suggestion and moving the USB item into volumes for some odd reason instead of devices.  I also modified the port 5000 as it conflicts with the DSM CP.  

**Note this is referencing a specific beta image don't do that use the stable version instead!!!** 
(13.0 beta 2 is working fine for me in this configuration)

I started with the suggested minimum config and expanded from there and have added 4 cameras, detection is working and CPU usage is acceptable. 

![image](https://github.com/blakeblackshear/frigate/assets/26907395/8fdd17a5-fcf0-44d9-b351-bb3f2aec7973)

I have the HA Integration running and Go2rtc is working great.

**Comment by Devstored** [comment]
hi @chrisuthe , add - "/dev/bus/usb:/dev/bus/usb" in "devices" list

**Reply by chrisuthe** [reply]
hi @Devstored  doesn't seem to need it?

**Comment by chrisuthe** [comment]
Side note, I set HWAccel to VAAPI, and now each camera is taking about 2% CPU down from 9-10% without hardware accel.

**Reply by igalg99** [reply]
Thank you for sharing. this has helped me to setup the container on my DS923+ 
although I cant find anywhere yet any info what hardware accel is suitable to use on my NAS as I am AMD Ryzen R1600. I can't understand if hardware acceleration is even supported with AMD Ryzen R1600.

**Reply by NickM-27** [reply]
Most AMD cpus do not contain a GPU so they do not support hwaccel

**Comment by igalg99** [comment]
Oh that's a shame i guess. I am still  confused about all this
configuration options and hardware acceleration but this is also the
conclusion i was getting at . Was just hoping I am wrong. So I just comment
out everything related to hardware acceleration I guess. It does make it
simpler though :) although probably less effective.

**Comment by aisbergde** [comment]
@igalg99 - did you find a way to use hardware acceleration on a DS923+? For now I am using CPU for detection. And what I read about using Coral on Synology - maybe it's not just plug and play.

**Reply by igalg99** [reply]
No I did not. In my searches I concluded (maybe wrong) that it is not possible due no GPU in Ds923+
I use coral via Docker with frigate but it's just for detection not for hardware encoding/acceleration

**Reply by mx-vatte** [reply]
I can confirm sadly that there is no possibility to use hardware acceleration due to the lack of a GPU. The Ryzen 1600 just don't have a GPU.

**Reply by chrisuthe** [reply]
FYI @aisbergde  HW accel is not the same as different detectors. 

HW Accel in this context is just decoding the streams as they arrive

Coral vs CPU detection is doing the actual image analysis and is MUCH more important to accelerate in some way (via coral or vino etc)

**Reply by aisbergde** [reply]
Yes, I got this. And after adding a coral USB stick for detection I am very happy with the performance and don't need any additional hardware acceleration. I was impressed about the big difference, when using the coral stick. Before using it my NAS CPU was completely occupied by frigate and detection results where not the best. Now the stick is doing the work, CPU is fine and detection results are much better.

**Comment by jace** [comment]
I tried doing this on a DS920+ with a Coral USB accelerator plugged in, but the Frigate container shuts down shortly after startup, far too soon to even open the terminal in docker. Any suggestions for how I can diagnose what is wrong? Here's my project YAML:

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2
    shm_size: "256mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /dev/bus/usb:/dev/bus/usb  # For USB Coral Accelerator
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config/:/config/
      - /volume1/docker/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5005:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD="…"
      # - LIBVA_DRIVER_NAME=i965 # if hwacl isn't working properly with the default iHD driver
```
