### DISCUSSION TITLE
Refining my configuration to reduce CPU usage even further

### DISCUSSION THREAD

**Discussion by marcgarciamarti** [blakeblackshear/frigate#8140] [Ask A Question]
Hello,

I inspired myself in[ this article](https://github.com/blakeblackshear/frigate/issues/3860) and managed to reduce my cpu consumption a lot. I'm very grateful I found it and discovered that my cameras are able to stream more than one simultaneous stream with various resolutions. Awesome! 

Once I had configured I noticed however a few false positives, and I sort of assumed lower resolution feeds may be more prone to triggering false positives. So now I'm in the process of cranking up a notch the resolution of the lower resolution feed, hoping I will experience fewer false positives, but my cpu consumption has gone up a bit (along of course the cpu temperature).

I wonder if there is still room for refining my configuration so that my cpu consumption goes down a bit, while eliminating (or reducing) the false positives.

I would appreciate a lot your help with this.

This is my current configuration. I'm on an Intel NUC 8th gen with a USB Coral TPU dongle. 

```

birdseye:
  enabled: True
  mode: motion

#go2rtc:
#  streams:
#    back:
#      - rtsp://xxxxx:xxxxx@192.168.1.31:554/stream0
      
cameras:
  anpviz-camera-dome-comedor:
    ffmpeg:
 #     hwaccel_args: preset-vaapi
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.31:554/stream2
        roles:
          - detect
      - path: rtsp://192.168.1.31:554/stream0
        roles:
          - record
    objects:
      track:
        - person
    detect:
      enabled: false
      width: 1920  
      height: 1080 
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects

  anpviz-camera-dome-recibidor:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
      - path: rtsp://192.168.1.32:554/stream0
        roles:
          - record
      - path: rtsp://192.168.1.32:554/stream1
        roles:
          - detect
    objects:
      track:
        - person
    detect:
      enabled: false 
      width: 720 
      height: 480 
      fps: 5
    motion:
      mask:
        - 453,170,459,204,482,198,498,182,509,154,518,103,511,82,489,79,469,87
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects

detectors:
  coral:
    type: edgetpu
    device: usb

```
thanks!
