### DISCUSSION TITLE
Guide: Local License Plate Recognition With Home Assistant, CodeProject.AI, and Frigate

### DISCUSSION THREAD

**Discussion by NickM-27** [blakeblackshear/frigate#8165] [Tips]
I spent quite a while trying different ideas to get a working & fully local license plate setup and I am quite happy with this one so I am sharing a guide on how to do this. 

## Prerequisites
- You must have [CodeProject.AI](https://www.codeproject.com/Articles/5322557/CodeProject-AI-Server-AI-the-easy-way) setup with the [license plate plugin installed](https://www.codeproject.com/AI/docs/api/api_reference.html#license-plate-reader), that is outside the scope of this guide.
- [Frigate+](https://github.com/blakeblackshear/frigate/discussions/7932) is recommended for its built in license plate detection, however this can definitely work without Frigate+ with some modifications that are called out in the code comments

## Preliminary Info

The approach in this guide requires using a python script to run some of the logic because it would be much more difficult to do in a Home Assistant automation. This script is called directly from home assistant.

### Python Script

1. Create a folder to hold your scripts (if you don't already have one) inside of the Home Assistant `/config` directory. For this guide I will call mine `/config/bashscript`
2. Create a file called `license_plate.py` in `/config/bashscript`

The contents of the file should be

```python
import datetime
import io
import json
import requests
import sys

from PIL import Image

# host for frigate instance
FRIGATE_HOST = "http://10.0.0.0:5000"

# host for CodeProject.AI instance
CODE_PROJECT_HOST = "http://10.0.0.0:4100"

event_id = sys.argv[1]
json = requests.get(f"{FRIGATE_HOST}/api/events/{event_id}").json()
camera = json["camera"]

# get clean snapshot if event has bended otherwise get snapshot without bounding boxes
if json["end_time"]:
    img_bytes = requests.get(f"{FRIGATE_HOST}/clips/{camera}-{event_id}-clean.png").content
else:
    img_bytes = requests.get(f"{FRIGATE_HOST}/api/events/{event_id}/snapshot.jpg?bbox=0").content

img = Image.open(io.BytesIO(img_bytes))

attributes = json["data"]["attributes"]

# Checks to ensure that license plate is detected
# this will need to be removed if not using a model that detects license plates (like frigate+)
if not attributes:
    with open("/config/bashscript/detected_plates.log", "a") as log:
        log.write(f"[{datetime.datetime.now()}]: {camera} - could not find license plate in {json}\n")
        sys.exit()

box = attributes[0]["box"]

detect = requests.get(f"{FRIGATE_HOST}/api/config").json()["cameras"][camera]["detect"]
known_res = (detect["width"], detect["height"])

# find coordinates of image to send to detector
x_mid = (box[0] + (box[2] / 2)) * known_res[0]
y_max = (box[1] + box[3]) * known_res[1]

cropped_image = img.crop((max(0, x_mid - 150), 0, min(known_res[0], x_mid + 150), known_res[1]))
cropped_image.save("/config/bashscript/crop.jpg")

# you will likely need to create multiple iterations for each vehicle
# 0/8/B for example are often mixed up
known_plates = {
    # Bob's Car
    "ABC128": "Bob's Car",
    "ABC12B": "Bob's Car",
    
    # Steve's Truck
    "123TR0": "Steve's Truck",
    "123TRO": "Steve's Truck",
}

with open('/config/bashscript/crop.jpg', 'rb') as fp:
    response = requests.post(
        f'{CODE_PROJECT_HOST}/v1/image/alpr',
        files=dict(upload=fp),
    )
    print(response.json())
    plates = response.json()
    plate = None

    if len(plates["predictions"]) > 0 and plates["predictions"][0].get("plate"):
        plate = str(plates["predictions"][0]["plate"]).replace(" ", "")
        score = plates["predictions"][0]["confidence"]
        print(f"Checking plate: {plate} in {known_plates.keys()}")

        with open("/config/bashscript/detected_plates.log", "a") as log:
            log.write(f"[{datetime.datetime.now()}]: {camera} - detected {plate} as {known_plates.get(plate)} with a score of {score}\n")

        if plate in known_plates.keys():
            print(f"{camera} - Found a known plate: {known_plates[plate]}")
        else:
            plate = None
    else:
        with open("/config/bashscript/detected_plates.log", "a") as log:
            log.write(f"[{datetime.datetime.now()}]: {camera} - No plates detected in run: {plates}\n")

    if plate is None:
        print(f"No valid results found: {plates['predictions']}")
        sys.exit()

vehicle_name = known_plates[plate]

# Add Sub Label To Car Event
requests.post(f"{FRIGATE_HOST}/api/events/{event_id}/sub_label", json={"subLabel": vehicle_name, "subLabelScore": round(score, 2)})
```

There are a few things to note here:
- CodeProject.AI port might be different depending on where and how it is setup
- Some characters are commonly mixed up like 0/O and 8/B, these variations should be added so this works more reliably.
- This will create a file `detected_plates.log` which will provide info on what plates are detected and if it matches a known plate
- The latest image sent to ALPR will be saved as `/config/bashscript/crop.jpg`

### Home Assistant Configuration

The next step is adding this python script to the Home Assistant `configuration.yaml` file. This is done via the `shell_command` type:

```yaml
shell_command:
  # run license plate inference for vehicle
  check_license_plate: python3 /config/bashscript/license_plate.py "{{ event_id }}"
```

### Home Assistant Automation

The final step is setting up the Home Assistant automation, this will run on a car event only when it has a license plate attribute detected. It will then run 3 iterations of checking for the license plate and stop when a license plate is detected.

This single automation will run on all cameras that detect a car with a license plate in the zones defined, so if you have a driveway zone specified for the garage and driveway camera it will run on both.

```yaml
alias: >-
  Outside - Driveway - Frigate Try To Read License Plate - License Plate
  Seen
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: license_plate
    # will just want to check that the label == "car" if not using a model that supports license_plate
    value_template: "{{ value_json[\"after\"][\"current_attributes\"][0]['label'] }}"
    variables:
      after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
      before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
      current_zones: "{{ trigger.payload_json[\"after\"][\"current_zones\"] }}"
      camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
      id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
      label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
condition:
  - condition: and
    conditions:
      # setup zones that you want to look for cars with license plates for detection
      - condition: template
        value_template: >-
          {{ ["street", "driveway"] | select("in", after_zones) | list | length
          > 0 }}
        alias: Has been in the street
      - condition: template
        value_template: "{{ [\"driveway\"] | select(\"in\", current_zones) | list | length > 0 }}"
    alias: Was in the street and is now in the driveway
  - condition: template
    value_template: "{{ trigger.payload_json['after']['sub_label'] is none }}"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: frigate-event
        sequence:
          - service: shell_command.check_license_plate
            data_template:
              event_id: "{{id}}"
              camera: "{{camera}}"
          - repeat:
              count: 2
              sequence:
                - wait_for_trigger:
                    - platform: mqtt
                      topic: frigate/events
                      payload: "{{ trigger.payload_json['after']['id'] }}"
                      value_template: "{{ value_json['after']['id'] }}"
                  timeout:
                    hours: 0
                    minutes: 10
                    seconds: 0
                    milliseconds: 0
                  continue_on_timeout: false
                - condition: template
                  value_template: >-
                    {{ wait.trigger.payload_json['after']['sub_label'] is none
                    }}
                - service: shell_command.check_license_plate
                  data_template:
                    event_id: "{{id}}"
                    camera: "{{camera}}"
    default: []
trace:
  stored_traces: 20
mode: parallel
max: 10

```

**Comment by weitheng** [comment]
Thank you for sharing. How do I get this to work without Frigate+?

**Reply by NickM-27** [reply]
You'll need to remove the parts that are commented for requiring frigate+, and then change the logic to crop the image based on the car bounding box to grab where the license plate (should) be.

**Reply by NickM-27** [reply]
I'd change it to car

**Reply by weitheng** [reply]
> You'll need to remove the parts that are commented for requiring frigate+, and then change the logic to crop the image based on the car bounding box to grab where the license plate (should) be.


Would this work? I am not sure if I still need to multiply it by `known_res`
```
attributes = json["box"]

box = attributes["box"]

detect = requests.get(f"{FRIGATE_HOST}/api/config").json()["cameras"][camera]["detect"]
known_res = (detect["width"], detect["height"])

# find coordinates of image to send to detector
x_mid = (box[0] + (box[2] / 2)) * known_res[0]
y_max = (box[1] + box[3]) * known_res[1]

cropped_image = img.crop((max(0, x_mid - 150), 0, min(known_res[0], x_mid + 150), known_res[1]))
cropped_image.save("/config/bashscript/crop.jpg")
```

**Reply by NickM-27** [reply]
yes you do need to multiply it by known res because the object box is also saved as relative coordinates + relative size

you will need to play around with the image cropping to make sure it crops the part of the car that has the license plate. But that looks good to me

**Reply by weitheng** [reply]
I changed the code to that but looks like something is not right, getting this in Home Assistant.
```
Error running command: `python3 /config/bashscript/license_plate.py "{{ event_id }}"`, return code: 1
NoneType: None
```
Tried looking up the internet, but got to nowhere. Appreciate if you could help. Thank you

**Reply by NickM-27** [reply]
What do you get when you run it from the cli directly?

**Reply by weitheng** [reply]
I am running Home Assistant OS, I tried running the commands on the cli interface, not sure if I am supposed to run it here but I get this
```
Error: unknown command "python3" for "ha"
Run 'ha --help' for usage. 
FATA[0000] Error while executing rootCMd: unknown command "python3" for "ha"
```
However when I tried to call the shell command service in the Developer Tools page, I get
```
stdout: ""
stderr: |-
  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
      return complexjson.loads(self.text, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
      return _default_decoder.decode(s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
      obj, end = self.raw_decode(s)
                 ^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
      return self.scan_once(s, idx=_w(s, idx).end())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/config/bashscript/license_plate.py", line 16, in <module>
      json = requests.get(f"{FRIGATE_HOST}/api/events/{event_id}").json()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
  requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
returncode: 1
```
Looks like python3 is not installed in the OS?

**Reply by NickM-27** [reply]
> Looks like python3 is not installed in the OS?

yeah, I personally run HA container and get a shell there, so you may need to see if that is possible.

to be clear when running from within HA you are sending a valid event_id correct?

**Reply by BradFD** [reply]
@weitheng Hi I am having the same issue as you, how did you solve this? Thank you. 

> I am running Home Assistant OS, I tried running the commands on the cli interface, not sure if I am supposed to run it here but I get this
> 
> ```
> Error: unknown command "python3" for "ha"
> Run 'ha --help' for usage. 
> FATA[0000] Error while executing rootCMd: unknown command "python3" for "ha"
> ```
> 
> However when I tried to call the shell command service in the Developer Tools page, I get
> 
> ```
> stdout: ""
> stderr: |-
>   Traceback (most recent call last):
>     File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
>       return complexjson.loads(self.text, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
>       return _default_decoder.decode(s)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
>       obj, end = self.raw_decode(s)
>                  ^^^^^^^^^^^^^^^^^^
>     File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
>       return self.scan_once(s, idx=_w(s, idx).end())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
>   During handling of the above exception, another exception occurred:
> 
>   Traceback (most recent call last):
>     File "/config/bashscript/license_plate.py", line 16, in <module>
>       json = requests.get(f"{FRIGATE_HOST}/api/events/{event_id}").json()
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
>       raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
>   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> returncode: 1
> ```
> 
> Looks like python3 is not installed in the OS?

**Reply by BradFD** [reply]
Figured out this does not work in Hass OS because Pillow and Requests are not installed. You can pip install them but they don't stay installed after any update or restart so this script doesn't see workable with Hass OS.

**Comment by gavink2** [comment]
I'm doing a similar function using a local instance of ALPR Snapshot from [Plate Recognizer](https://platerecognizer.com/), together with the [Plate Recognizer HA integration](https://github.com/robmarkcole/HASS-plate-recognizer). It's working perfectly and was pretty simple to set up. It's also possible to use their free cloud-based product for up to 2500 detections a month. Local is much faster if you have a good machine with an Nvidia GPU as well as being more private, of course.

In short, I set up a zone on a Frigate camera and when a car is detected in that zone, an automation is triggered and one frame is sent to ALPR Snapshot via the HA integration. That then triggers an HA event if a plate is detected. If the license plate is our car's and our gate is closed or closing, then open the gate.

configuration.yaml:
```yaml
image_processing:
  - platform: platerecognizer
    api_token: xxxx
    server: http://192.168.x.x:8080/v1/plate-reader/
    regions:
      - gb
    watched_plates:
      - ab12cde
    detection_rule: strict
    region: strict
    source:
      - entity_id: camera.gate #  Supplied by Frigate integration
```
automation:
```yaml
alias: Open gate when our car detected in driveway
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.plate_car_occupancy # Provided by Frigate integration, state changes to 'on' when a car is detected in the 'plate' zone.
    to: "on"
condition: []
action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_gate
  - wait_for_trigger:
      - platform: event
        event_type: platerecognizer.vehicle_detected
        event_data:
          plate: aa12cde # Plate to check for
    timeout:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
    continue_on_timeout: false
  - condition: state
    entity_id: cover.gate
    state:
      - closed
      - closing
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.gate
mode: single

```
docker-compose.yaml for ALPR Snapshot
```yaml
version: "3.8"
services:
  alpr-snapshot:
    container_name: alpr-snapshot
    restart: unless-stopped
    image: platerecognizer/alpr-gpu
    environment:
      - LICENSE_KEY=xxxxx
      - TOKEN=xxxxx
      - WORKERS=8 # Adjust based on number of CPU cores. See docs.
    volumes:
      - ./alpr-snapshot/license:/license
    ports:
      - "192.168.x.x:8080:8080/tcp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
Frigate config:
```yaml
cameras:
  gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gate # go2rtc
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
            - detect
    motion:
      mask:
        - 1920,0,1920,406,1138,381,824,412,0,464,0,0
    zones:
      plate:
        coordinates: 1316,714,589,711,424,1080,1534,1080
```

**Reply by rjdainty1** [reply]
Interesting setup, thanks for sharing.

Out of interest, how do you go about getting a license key for the Snapshot Docker container?  I see the Cloud version of Snapshot is $50 for their minimum subscription but don't see any way to get a license key for offline / local.  I do have my token from the PlateRecognizer website.

Thanks

**Reply by gavink2** [reply]
Once you sign up you can request a trial licence key. Think you can start the process from https://app.platerecognizer.com/products/snapshot-sdk/

**Reply by rjdainty1** [reply]
Ah yes, I've been declined from that as not using a corporate email address.  Not so sure this is a viable longer term option for me then.  Thanks

**Reply by gavink2** [reply]
Oh. That's weird. I signed up using a gmail address and had no issues. Guess your only Plate Recognizer option is their cloud-hosted Snapshot product then. I tried that at first but consistently found the round-trip time too be way to long, around 10-12 seconds.

**Reply by rjdainty1** [reply]
I've uploaded the email that I received from their team, maybe they're pushing everyone towards the Cloud model a bit more now.  Agreed though, that's far too long

<img width="950" alt="Screenshot 2023-10-31 at 09 14 07" src="https://github.com/blakeblackshear/frigate/assets/51188734/4d8cb5b5-881e-4bb7-97b3-919bc0628005">

**Reply by Jens-Wymeersch** [reply]
I've been looking at the snapshots and the quality is really not good enough to do any recognition of this sort. @gavink2 I see you have only use one feed (no secondary feed). This was reason for this ?

**Reply by NickM-27** [reply]
@Jens-Wymeersch that is why frigate recommends using high quality cameras that have configurable substreams, so you can configure a resolution suitable for your needs.

**Reply by gavink2** [reply]
@Jens-Wymeersch the camera is a Doorbird, which has a very basic rtsp implementation and a low-power CPU. The device can just about handle 2 simultaneous streams - one from go2rtc/frigate and one from the Doorbird intercom and that's it - another substream towards frigate is a no-go.

**Reply by Jens-Wymeersch** [reply]
@NickM-27 Planning to buy for my parking array, a unify G5 Pro with vision enhancer. In the meanwhile I took the substream out to see if the snapshots are better but still kept the detection at 640 X 480.

**Reply by Jens-Wymeersch** [reply]
Here you find an example of the snapshot 

![image](https://github.com/blakeblackshear/frigate/assets/70786498/961bb57f-56cd-4746-9f6f-6dc67ffb6f6d)

Although the following configuration, I'm still getting the box and timestamp around it

```
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
      retain:
        default: 7 
      required_zones:
          - parking_key_zone
          - parking_entry_zone
```
Any idea why ?

**Reply by NickM-27** [reply]
where are you viewing this?

**Reply by Jens-Wymeersch** [reply]
What do you mean ? We have a shared parking array. This image is about 5m from the camera.

**Reply by NickM-27** [reply]
where in frigate are you viewing this image

**Reply by Jens-Wymeersch** [reply]
@NickM-27 
I've added the following code now to my config to eliminate the boxes, time stamp, etc in home assistant 

```
parking:
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
```
Now a few questions pop up, how can I increase the quality (what is the maximum) and potential other variables in order to do plate recognition. 

The second observation is that the image that has been sent to platerecognizer.com isn't the same as the entity. Not sure why ?

Here is the image on the entity camera.parking_car

![image](https://github.com/blakeblackshear/frigate/assets/70786498/cfc9aa4d-cc98-4ae4-bd2c-358c2e4cdecb)

And here is the image that I find in platerecognizer.com

![image](https://github.com/blakeblackshear/frigate/assets/70786498/dd0a287f-3a42-4cc0-a728-cf124dc88450)

As this would be an easier implementation for plate recognition as to implement codeproject.ai, I wonder if you can give additional guidance.

**Reply by NickM-27** [reply]
the entity is based on the mqtt snapshot, you have not really shown what code you are working with so I can't really give any guidance

**Reply by Jens-Wymeersch** [reply]
Here is the code 

```
  parking:
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
    rtmp:
      enabled: false
    ffmpeg:
#      hwaccel_args:
#      output_args:
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
#        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        # High Resolution Stream
        - path: rtsp://url/parkingHigh_Rotated
          roles:
            - record
            - detect
            - rtmp
        #Low Resolution Stream
        #- path: rtsp://url/parkingLow_Rotated
        #  roles:
        #    - detect
        #    - rtmp
    detect:
      width: 640
      height: 480
      fps: 25
    objects:
      track:
        - person
        - cat
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          threshold: 0.7
          min_area: 5000
          max_area: 100000      
        car:
          threshold: 0.7
          min_area: 5000
          max_area: 100000   
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 7 
      required_zones:
          - parking_key_zone
          - parking_entry_zone
    record:
      enabled: True
      events:
        retain:
          default: 7
          mode: motion
        pre_capture: 5
        post_capture: 15
        required_zones:
          - parking_key_zone
          - parking_entry_zone
    motion:
      mask: 
        - 0,480,0,0,137,0,97,98,149,115,89,109,86,190,91,280,196,263,224,303,182,361,135,480
        - 128,0,640,0,640,223,454,206,412,226,352,223,287,214,250,198,204,185,154,193,134,182,78,193,81,103
    zones:
      parking_key_zone:
        coordinates: 640,270,640,480,148,480,97,393,416,318
        objects:
          - person
          - cat 
      parking_entry_zone:
        coordinates: 87,208,233,195,295,221,330,232,405,221,569,219,640,230,640,278,119,408,133,372,221,307,191,265,103,276
        objects:
          - car
          - motorcycle
          - bicycle
```

**Reply by Jens-Wymeersch** [reply]
The point is that the snapshot should be taken at the "best" moment. In my case it would be just after the entry zone

![image](https://github.com/blakeblackshear/frigate/assets/70786498/9730b92f-a64d-491c-ad74-ee672ea21761)
Yellow being the entry zone and orange being the key zone

**Reply by NickM-27** [reply]
what I mean is the code that is used for platerecognizer.

**Reply by Jens-Wymeersch** [reply]
Here you go

```
image_processing:
  - platform: platerecognizer
    api_token: token
    regions:
      - il
    save_file_folder: /config/www/plates
    save_timestamped_file: True
    always_save_latest_file: True
    watched_plates:
      - plate1 
      - plate2 
      - plate3
      - plate4
      - plate5
    detection_rule: strict
    region: strict
    source:
      - entity_id: camera.parking_car #  Supplied by Frigate integration
```
and the following automation 

```
alias: Plate Recognition
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.parking_entry_zone_car_occupancy
    to: "on"
condition: []
action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_parking_car
mode: single
```
