### DISCUSSION TITLE
Update frigate container

### DISCUSSION THREAD

**Discussion by BigChris** [blakeblackshear/frigate#8244] [Ask A Question]
Hi!

I still have frigate running in version 12.0. Now I would like to update it to version 12.1. 
How do I do that?

My config looks like this:

```
version: "3.9
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "192mb" # update for your cameras based on calculation above
    devices:
```

I thought if I restarted the Docker container (docker compose -f frigate.yml up) it would update the version. But it doesn't :)

I tried it with:
`docker compose pull frigate.yml`
but that didn't work either.

How can I update to 12.1?
