### DISCUSSION TITLE
frigate.record reports "ERROR   : Error occurred when attempting to maintain recording cache" on start up

### DISCUSSION THREAD

**Discussion by janusn** [blakeblackshear/frigate#8247] [Ask A Question]
On the logs, there are 2 errors pop up every time after frigate starts:
```
2023-10-20 15:06:07.598888678  [2023-10-20 15:06:07] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-10-20 15:06:07.598967791  [2023-10-20 15:06:07] frigate.record                 ERROR   : list index out of range
```
How can I get rid of these errors?

Environment:
- Dcoker version: 24.0.6, build ed223bc
- Frigate version: 0.12.1-367D724
- go2rtc version: 1.2.0
- Intel VNC 13 Core i5-1340P 32GB RAM

compose.yaml:
```
---
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true # It is for gathering GPU Load inside the container.
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
    shm_size: "67MB" # update for your cameras based on calculation above
    devices:
      - "/dev/dri:/dev/dri" # for Intel Quick Sync driver
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1073741824
      - ./config/config.yaml:/config/config.yaml:rw
      - /home/frigate/cctv/frigate:/media/frigate:rw
    ports:
      - "5000:5000" # WebUI
      - "8554:8554" # RTSP feeds Default 8554 is used by container homeassistant-ring-mqtt
      - "8555:8555/tcp" # WebRTC over tcp 
      - "8555:8555/udp" # WebRTC over udp
```

frigate.conf
```
mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: True
  # Required: host name
  host: 10.27.0.50
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: '[omtted]'
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: '[omtted]'
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
 #  tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
#  tls_client_cert: /path/to/client.crt
#  tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
#  tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: 60)
  stats_interval: 5
  
detectors:
  # Google Coral Detector
   coral:
     type: edgetpu
     device: usb

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  # generic Intel hardware acceleration
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat

go2rtc:
  rtsp:
    username: "[omtted]"
    password: "[omtted]"

  streams:

    # stream backyard =======================================================================
    backyard:
      - rtsp://[omtted]:[omtted]@10.27.0.203:554/cam/realmonitor?channel=1&subtype=0
    backyard_sub:
      - rtsp://[omtted]:[omtted]@10.27.0.203:554/cam/realmonitor?channel=1&subtype=2

    # stream frontyard ======================================================================
    frontyard:
      - rtsp://[omtted]:[omtted]@10.27.0.202:554/cam/realmonitor?channel=1&subtype=0
    frontyard_sub:
      - rtsp://[omtted]:[omtted]@10.27.0.202:554/cam/realmonitor?channel=1&subtype=2

    # stream shed ===========================================================================
    shed:
      - rtsp://[omtted]:[omtted]@10.27.0.206:554/cam/realmonitor?channel=1&subtype=0
    shed_sub:
      - rtsp://[omtted]:[omtted]@10.27.0.206:554/cam/realmonitor?channel=1&subtype=2
      
cameras:
  # Camera ========================== Backyard =============================================
  backyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[omtted]:[omtted]@127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[omtted]:[omtted]@127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: backyard # default main channel for live stream
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      events:
        pre_capture: 7
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 60 # default 10 days
          mode: motion
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 60
    motion:
      mask:
        - 1280,0,1280,304,1173,352,1100,324,1046,201,906,219,857,80,884,0
        - 0,225,53,82,105,67,116,0,0,0
        - 606,93,829,80,837,0,159,0,162,135
    objects:
      track:
        - person
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 3000
    birdseye:
      enable: object
        
  # Camera ========================== Frontyard =============================================
  frontyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[omtted]:[omtted]@127.0.0.1:8554/frontyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[omtted]:[omtted]@127.0.0.1:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: frontyard # default channel for live stream
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      events:
        pre_capture: 7
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 60 # default 10 days
          mode: motion
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 60
    motion:
      mask:
        - 233,0,371,211,0,395,0,0
        - 1226,561,1259,297,1236,59,1178,0,1280,0,1280,720,1092,720
        - 999,64,1215,68,1217,29,995,25
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          mask:
            - 0,372,0,461,121,399,136,353,319,280,363,315,413,289,390,247,320,239
    birdseye:
      enable: object

  # Camera ========================== Shed ==================================================
  shed: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[omtted]:[omtted]@127.0.0.1:8554/shed_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[omtted]:[omtted]@127.0.0.1:8554/shed
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: shed # default main channel for live stream
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record: # <----- Enable recording
      enabled: True
      events:
        pre_capture: 7
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        retain:
          default: 60 # default 10 days
          mode: motion
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 60
    motion:
      mask:
        - 0,720,210,720,568,448,576,182,523,109,705,77,685,0,503,0,0,0
        - 1229,70,1223,0,1000,0,1005,67
    objects:
      track:
        - person
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 4000
    birdseye:
      enable: object
```
