### DISCUSSION TITLE
Understanding go2rtc vs. camera streams and configuration

### DISCUSSION THREAD

**Discussion by natevw** [blakeblackshear/frigate#8293] [Ask A Question] [answered]
There's several things that are really unclear to me about "streams" to me. For starters, I think I kind of get how I can set up multiple separate streams per-camera, like:

```
go2rtc:
  streams:
    some_name: 
      - "ffmeg/rtsp:…"
    some_name_sub: 
      - "…"
```

That mostly makes sense, but already a few things don't seem super well-documented. How important is the name of each stream? Is the suffix `_sub` specially meaningful or could I just as well pick any other arbitrary name/ending like `some_name_alternate` or `lofi-some_name`? I wouldn't think the names had any meaning at all except that I noticed that with full redundancy like:

```
go2rtc:
  streams:
    exact_shared_name: 
      - "ffmpeg:…"

cameras:
  exact_shared_name:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/exact_shared_name
```

then Frigate would enable multiple options `mse` and `webrtc` but if I tried to split up the more permanent camera device/host name from a more semantic "where this camera is currently deployed/aimed" name like:

```
go2rtc:
  streams:
    device_name: 
      - "ffmpeg:…"

cameras:
  name_how_used:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/device_name
```

then Frigate would revert back to only showing the `jsmpeg` option alone. So it seems I'm really "supposed to" keep the names the same everywhere which is a bit of a bummer; is there a way to get the `mse` option *without* having the go2rtc section names matching exactly the camera section names?

---

The other thing that's still fairly unclear even after reading the camera-related guide pages repeatedly is all the multiple lines and places that all the options can go. For example in the go2rtc guide it gives an example:

```
go2rtc:
  streams:
    back:
      - rtsp://user:password@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:back#video=h264"
```

Now if I reference `rtsp://127.0.0.1:8554/back` as my camera ffmpeg path, which of those do I get? The first "rtsp" line or the second "h264" line? What does it mean to put *multiple* URLs within a single stream config block?

And also in the Reolink guides I see some examples like:

```
go2rtc:
  streams:
    your_reolink_camera: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/your_reolink_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
```

Now why does that have lines for `#video=copy#audio=copy#audio=opus` both in the go2rtc config section, but then **also** in the camera inputs there's a separate `?video=copy&audio=aac` line in its link too! Under what circumstances would I need to or want to add `video=copy` also in the *camera* section instead of just in the go2rtc section?

Sorry for the long post with several questions, but I suspect they're all kind of interrelated. E.g. I just noticed in this last Reolink example that that go2rtc name does NOT match exactly the camera name, which seems to sort of halfway break Frigate in practice and force it to use only `jsmpeg`.

My best guess is that even within a single "stream" go2rtc actually can negotiate multiple video/audio *sub*options — at least at the *codec* level? But then to actually provide a different *resolution* you can't do that as a suboption but have to set up a whole separate stream?
