### DISCUSSION TITLE
Ideas for improving Frigate+ submissions and questions about Frigate+ Model

### DISCUSSION THREAD

**Discussion by sberryman** [blakeblackshear/frigate#8304] [Ask A Question] [answered]
I recently switched from a TensorRT `yolov7-tiny-416.trt` model to a fine-tuned Frigate+ model and noticed one of the cameras is not detecting vehicles anymore. I have the computational resources to run both models on every camera, and I'm considering supporting this to improve the Frigate+ model's performance.

My idea is to run the fine-tuned Frigate+ model and the TensorRT model simultaneously and send events to Frigate+ for review when the IoU between detection's is low (e.g., <= 0.5). This approach could potentially improve the accuracy of the Frigate+ model by "automatically" catching detection's that are missed by the Frigate+ model.

What are your thoughts on this approach? Do you have any suggestions or recommendations for improving the Frigate+ model's performance on smaller cameras?

**Comment by NickM-27** [comment]
I think a lot more information would be useful, like how many images you've submitted and what your config is. There are many suggestions and things [in the Frigate+ docs](https://deploy-preview-6262--frigate-docs.netlify.app/plus/) that are important to follow.

Many users have shared their experience. So far the consensus has been that it currently takes many examples and is important to follow the docs recommendation of 100+ per camera to start, but users have found true positive detection to be much improved.

- https://github.com/blakeblackshear/frigate/discussions/7932#discussioncomment-7189445
- https://github.com/blakeblackshear/frigate/discussions/7932#discussioncomment-7166293
- https://github.com/blakeblackshear/frigate/discussions/7932#discussioncomment-7279505
- https://github.com/blakeblackshear/frigate/discussions/7932#discussioncomment-7322146

I don't think running multiple detectors is feasible for most people and there are plans for other ways to submit specific frames from the recordings as well as annotate the image as a first pass using the detector.

All that being said I'm moving this to a discussion that I think is better suited

**Reply by sberryman** [reply]
I would agree that Frigate+ does seem to be doing a better job than yolov7 overall. There are certainly quite a few cases of incorrect predictions and I'll be submitting those as they come up so I know it is going to improve over time. Especially once a new base model is trained.

I'm very familiar with training ML models in video and audio modalities. My last job involved building out the ML pipeline for Bird scooters to evaluate every single end of ride image for compliance.

My image count is quite low right now as seen below. This was based on submitting incorrect/low accuracy detection's from the yolo model.

![image](https://github.com/blakeblackshear/frigate/assets/324437/2952455a-0b10-420c-b420-51b8a88cefa5)

The problem right now is that missing vehicles are not going to show up in events timeline which means there is no "send to frigate+" button. I've been watching the debug view with `bounding box`, `motion boxes` and `zones` turned on an I can see motion boxes for the vehicles but no detection box. I was trying to come up with a somewhat hacky/easy solution... (I'll try and capture a screen shot when the next vehicle goes by)
![image](https://github.com/blakeblackshear/frigate/assets/324437/f81b3314-b7bb-472a-be3f-af930ece2ff3)

**Reply by NickM-27** [reply]
> My image count is quite low right now as seen below. This was based on submitting incorrect/low accuracy detection's from the yolo model.

yeah, that is a very low amount of image submissions per camera. an example screenshot with motion / regions would be helpful and seeing your config would also be helpful. 

also, it is important to submit a balance of true and false positive detections.

we have also made many improvements after beta2 to the regions, motion detection, and other things that may help with initial detection results as well. these will come in 0.13 beta 3

> The problem right now is that missing vehicles are not going to show up in events timeline which means there is no "send to frigate+" button.

currently you can use the recordings viewer and save a frame via right click then upload that manually. a future solution will allow using any keyframe from recordings and having that annotated by the model before the user adjusts the annotations and submits from within frigate itself.

**Reply by sberryman** [reply]
> also, it is important to submit a balance of true and false positive detections.

I have recording setup for 24/7 so finding those will be like a needle in a haystack. Hence me wanting a more "automated" way of finding missed detections.

> we have also made many improvements after beta2 to the regions, motion detection, and other things that may help with initial detection results as well. these will come in 0.13 beta 3

Is beta3 going to be cut soon? I'll probably just build a new image so I can use my MQTT changes for birdseye.

**Reply by NickM-27** [reply]
> I have recording setup for 24/7 so finding those will be like a needle in a haystack. Hence me wanting a more "automated" way of finding missed detections.

not with the changes to the recordings viewer that are also planned for a future version

> Is beta3 going to be cut soon? I'll probably just build a new image so I can use my MQTT changes for birdseye.

hopefully within a week but still working on a few improvements that have come to mind

**Reply by sberryman** [reply]
Forgot to share the config:
```yaml
# yaml-language-server: $schema=http://192.168.7.178:5000/api/config/schema.json
mqtt:
  enabled: true
  host: 192.168.7.178
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  # tensorrt:
  #   type: tensorrt
  coral_pci:
    type: edgetpu
    device: pci

birdseye:
  enabled: true
  restream: true
  quality: 3

# tensorRT
# model:
#   path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 416
#   height: 416

model:
  path: plus://{FRIGATE_MODEL_ID}

go2rtc:
  streams:
    front_yard:
      - "ffmpeg:rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.7.89:554/live"
    front_yard_sub:
      - "ffmpeg:rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.7.89:554/cam/realmonitor?channel=1&subtype=2"

    west_gate:
      - rtsp://admin:{FRIGATE_RTSP_ALT_PASSWORD}@192.168.7.152:554/live
    west_gate_sub:
      - rtsp://admin:{FRIGATE_RTSP_ALT_PASSWORD}@192.168.7.152:554/cam/realmonitor?channel=1&subtype=1

    doorbell:
      - rtsp://admin:{FRIGATE_RTSP_DOORBELL_PASSWORD}@192.168.7.180:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:doorbell#audio=aac#hardware"

    backyard_door:
      - 'ffmpeg:rtsp://admin:{FRIGATE_RTSP_ALT_PASSWORD}@192.168.7.156:554/cam/realmonitor?channel=1&subtype=0'
      - "ffmpeg:backyard_door#audio=aac#hardware"

    backyard_west:
      - 'ffmpeg:rtsp://admin:{FRIGATE_RTSP_ALT_PASSWORD}@192.168.7.181:554/live'
      - "ffmpeg:backyard_west#audio=aac#hardware"

ffmpeg:
  hwaccel_args:
    - preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  front_yard:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/front_yard
        input_args: preset-rtsp-restream
        roles:
          - record
      - path: rtsp://127.0.0.1:8554/front_yard_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
    motion:
      mask:
        - 1197,57,1236,59,1236,26,1191,25
    detect:
      width: 1280
      height: 720
    live:
      stream_name: front_yard_sub
    zones:
      driveway:
        coordinates: 137,254,352,260,288,286,123,345,206,369,113,417,90,263
      yard:
        coordinates: 233,363,0,485,0,720,1280,720,1280,362,363,263,139,343

  west_gate:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/west_gate
        input_args: preset-rtsp-restream
        roles:
          - record
      - path: rtsp://127.0.0.1:8554/west_gate_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
    detect:
      width: 640
      height: 480
    live:
      stream_name: west_gate_sub
    motion:
      mask:
        - 417,41,626,40,622,18,414,17

  doorbell:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell?mp4
          input_args: preset-rtsp-restream
          roles:
          - record
          - detect
          - audio
    birdseye:
      mode: continuous
    detect:
      width: 1440
      height: 1080
    live:
      stream_name: doorbell
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 1000
    objects:
      track:
        - person
    zones:
      entry:
        coordinates: 0,1080,1440,1080,1440,640,930,614,514,600,0,615
        filters:
          person:
            threshold: 0.88
    motion:
      mask:
        - 1360,85,1440,86,1440,0,1360,0
    audio:
      enabled: true
      min_volume: 250

  backyard_door:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/backyard_door?mp4
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect
          - audio
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 1189,63,1235,63,1234,26,1184,28
    audio:
      enabled: true
      min_volume: 250

  backyard_west:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
      - path: rtsp://127.0.0.1:8554/backyard_west
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect
          - audio
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 1175,59,1234,60,1234,24,1174,22
    audio:
      enabled: true
      min_volume: 250

record:
  enabled: true
  retain:
    days: 3
  events:
    retain:
      default: 30
    pre_capture: 2
    post_capture: 2

snapshots:
  enabled: true
  bounding_box: true

# objects:
#   track:
#     - person
#     - car
#     - bus
#     - cat
#     - dog
#   filters:
#     person:
#       min_score: 0.65
#       threshold: 0.75
#     car:
#       min_score: 0.65
#       threshold: 0.75
#     bus:
#       min_score: 0.65
#       threshold: 0.75
#     cat:
#       min_score: 0.65
#       threshold: 0.75
#     dog:
#       min_score: 0.65
#       threshold: 0.75

detect:
  fps: 15
  stationary:
    interval: 10

audio:
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - rain
    - thunder
    - car_alarm
    - emergency_vehicle

motion:
  mqtt_off_delay: 5

```
