### DISCUSSION TITLE
[0.13-beta2] CodeProject seems to be getting requests for detection over and over

### DISCUSSION THREAD

**Discussion by rykr** [blakeblackshear/frigate#8339] [Ask A Question] [answered]
got beta2 setup with 4 cameras.  connected to CodeProject and detection works good and detects properly.  But the CodeProject dashboard is showing continuous requests for detection.  There is no movement out there right now on the cameras but it seems Frigate is continually asking for detection.  Do I have some config messed up?

```
mqtt:
  host: 192.168.1.200
record:
  enabled: True
  events:
    objects:
      - person
      - dog
      - car
      - truck
      - bicycle
      - motorcycle
      - horse  
snapshots:
  enabled: True
detectors:
  deepstack:
    api_url: http://192.168.1.200:32168/v1/vision/detection
    type: deepstack
    api_timeout: 0.1 # seconds

cameras:
  ##### camera on back of house
  house_rear:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.34/stream0?username=admin&password=4928C53C394E8D06EE1D4A37F9C7950C
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.1.34/stream1?username=admin&password=4928C53C394E8D06EE1D4A37F9C7950C
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog

  ##### camera on back of pool house
  pool_rear:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:111111@192.168.1.113:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:111111@192.168.1.113:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - car
        - truck
        - bicycle
        - motorcycle
        - horse  

  #### camera over pool
  pool:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:111111@192.168.1.164:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:111111@192.168.1.164:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog       
      filters:
        person:
          mask:
            - 247,95,239,118,203,117,202,77     
    detect:
      width: 640
      height: 480
      fps: 7

  ### camera in kitchen
  kitchen:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.1.41/live0
          input_args: preset-rtsp-restream
          roles:
            - record
```
