### DISCUSSION TITLE
Reducing CPU usage from reflections and shadows

### DISCUSSION THREAD

**Discussion by victpork** [blakeblackshear/frigate#8393] [Ask A Question]
Hi all, thanks for the great software! 

I installed Frigate a few days ago on my Synology DS220+ and the results were great so far, except for missing event recordings sometimes. At first I thought it was the upstream cam format issue, but then I realised the footage had triggered a lot of motions due to reflections on windshields and shadows on ground, and causing continuous high CPU usage(40-60% on the python process). Is there some way I could ask Frigate to filter out motion due to shadows and reflections?

Cheers

**Comment by NickM-27** [comment]
I would suggest using hwaccel and an accelerated detector if you are not https://docs.frigate.video/configuration/detectors#openvino-detector https://docs.frigate.video/configuration/hardware_acceleration#intel-based-cpus

**Reply by victpork** [reply]
Hardware accelerated decoding and detector were already configured, you may check my config attached. 
docker-compose.yml
```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta3
    shm_size: "381mb"
    devices:
      - /dev/dri/renderD128
      - /dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/frigate/config:/config
      - /volume1/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "4000:5000"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: xxxxx
      PLUS_API_KEY: xxxxx
      LIBVA_DRIVER_NAME: "i965"
```
config.yml
```yaml
mqtt:
  host: 192.168.1.xxx
  user: frigate
  password: xxxxxxxx

go2rtc:
  streams:
    back:
      - rtsp://admin:xxxxxx@192.168.1.xxx/live/profile.0
    back_sub:
      - rtsp://admin:xxxxxx@192.168.1.xxx/live/profile.1
    front:
      - rtsp://admin:xxxxxx@192.168.1.xxx/cam/realmonitor?channel=3&subtype=0

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  input_tensor: nhwc
  input_pixel_format: bgr
  width: 300
  height: 300
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream

snapshots:
  enabled: True

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 1846,58,1854,95,1446,91,1448,54
    zones:
      driveway:
        coordinates: 328,1080,162,782,73,562,622,308,1174,561,1162,659,579,1080
      front_lawn:
        coordinates: 556,1080,1537,1080,1633,909,1180,654
    record:
      enabled: True
      retain:
        mode: active_objects
      events:
        objects:
          - person
  back:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub
          roles:
            - detect
    motion:
      mask:
        - 553,0,554,37,0,39,0,0
        - 1029,450,1008,499,715,285,748,239,600,210,508,96,472,144,447,125,343,0,1280,0,1280,495
    detect:
      width: 1280
      height: 720

record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
      - dog
      
objects:
  track:
    - person
    - cat
    - dog
    - bird
```
Confirm the hwaccel working as ffmpeg process only take 2.5% max CPU (opposed to 40% before I use the i965 driver)
Anyway my concern is that sometimes frigate fails to create recordings, though the event is still generated and snapshots are taken. I am perplexed as there are no related error logs generated at that time from that camera or ffmpeg
There are error coming from another camera though:
```
frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for back. Keeping the 5 most recent segments out of 8 and discarding the rest...
```
Maybe it is related?
