### DISCUSSION TITLE
Frigate records all the time

### DISCUSSION THREAD

**Discussion by ajocius** [blakeblackshear/frigate#8416] [General]
I am new beginner with frigate and certainly messed up somewhere in config.yml file. Frigate is constantly recording as a result, I have added motion mask, still keeps recording. Can you help me find error in config file?

```
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  FrontCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://192.168.1.217:554
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://192.168.1.217:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 480
      height: 360
      fps: 24

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 175
      retain:
        default: 14

    record:
      enabled: true
      retain:
        days: 1
      events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
        retain:
          default: 1
    motion:
      mask:
        - 379,47,375,197,392,207,435,164,480,178,480,123,410,74,347,104,320,120,295,136,292,159,331,173,382,207
        - 174,150,286,155,333,99,44,93,56,215
```

**Comment by NickM-27** [comment]
Your config is asking frigate to keep 1 day of 24/7 recording 

```
    record:
      enabled: true
      retain:
        days: 1
```

**Reply by ajocius** [reply]
I thought that following code limits to record only when person is detected with 5 sec prior and 10 sec after?

```
events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
        retain:
          default: 1
```
