### DISCUSSION TITLE
Amcrest Floodlight Camera (ASH26)

### DISCUSSION THREAD

**Discussion by Tokynet** [blakeblackshear/frigate#8432] [Ask A Question]
I searched the issues/and discussions and could not find anything about this camera.

Was wondering if anyone is using it w/ Frigate. I have been able to add the "bullet" like cameras and the "dome" like ones but this floodlight one is kicking my behind.

I can see it on my network, but can't find a web interface for it (google searches seem to point at no web-interface being available at all).
PORT     STATE SERVICE
80/tcp   open  http
554/tcp  open  rtsp
8086/tcp open  d-s-n

Other cameras connect to port 554 (rtsp) but trying some strings like the other cameras I have configured is failing to work.
```
...
    backdoor:
      ffmpeg:
        inputs:
          - path: rtsp://$USER:$PASS@192.168.200.167:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
              - rtmp
      detect:
        width: 1280
        height: 720
...
```

If anyone is using this camera successfully, any pointers will be greatly appreciated!

**Comment by JohnNeville** [comment]
I am not sure if you ever got it working but this is what I have:

```
go2rtc:
  streams:
    driveway_floodlight_camera:
      - rtsp://admin:{FRIGATE_AMCREST_PASSWORD}@172.16.30.28:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway_floodlight_camera#audio=aac#audio=copy#hardware

    driveway_floodlight_camera_sub:
      - rtsp://admin:{FRIGATE_AMCREST_PASSWORD}@172.16.30.28:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:driveway_floodlight_camera#audio=aac#audio=copy#hardware

cameras:
  driveway_floodlight_wide_camera:
    detect:
      width: 704
      height: 480

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_camera
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_floodlight_camera_sub
          roles:
            - detect
```

With FRIGATE_AMCREST_PASSWORD being my "device password" as defined in the app.
