### DISCUSSION TITLE
Configuration issue when adding snapshots or clips

### DISCUSSION THREAD

**Discussion by alexphredorg** [blakeblackshear/frigate#850] [General]
I'm trying to configure my snapshots and am getting this error:
Error parsing config: extra keys not allowed @ data['snapshots']['enabled']

I get this even if I just cut and paste the sample from the documentation.  Here is a sample minimal config that is reproducing the issue:

```
mqtt:
  host: 192.168.171.XXX
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: XXXXX
  password: XXXXX

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX@192.168.171.XXXX/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - clips
            - record
    width: 1920
    height: 1080
    fps: 5
    objects: 
      track:
        - person

snapshots:
  enabled: True
```

I've checked this in yaml checkers and searched for other threads where this has occured, but don't think that I'm seeing the spacing issues that normally cause it.  What else should I look for?

Maybe related, but I installed through HassOS and the configuration file also doesn't show up on the Frigate configuration page.  I had to edit the file directly using the HassOS file editor plug-in.

Otherwise it's working well and I like the system compared to what I was using (Shinobi and Synology).
