### DISCUSSION TITLE
Old Nuc performance issue

### DISCUSSION THREAD

**Discussion by mbrocke123** [blakeblackshear/frigate#8513] [Ask A Question]
Hi everyone,

I hope this is the correct area to ask a hardware question: I am using an Intel DN2820FYKH NUC-Kit (Intel Celeron Prozessor N2820) with Coral TPU and I was really happy that I got everything running. Nevertheless this hardware seems to be to "low" to run ubuntu with portainer and skrypted container and frigate container with 5 1080p cameras. CPU has 100% and then it breaks.

I took a look at the hardware recommendation. Do you think the 

MINIS FORUM Mini PC 8GB DDR4 256GB SSD with Celeron Prozessor J4125 Quad-Core

has enough power for my setup? With scrypted I make my 5 cameras visible in homekit. Or should I use something else?

Thanks so much,
MB

**Comment by NickM-27** [comment]
I think it would be good to see your config, it is possible the issue is just a misconfiguration

**Reply by mbrocke123** [reply]
Hi, here is my config:

Intel DN2820FYKH NUC-Kit (Intel Celeron Prozessor N2820)

```
# Optional: Enable the RTMP stream (default: True)
  enabled: false  

#Global Object Settings
objects:
  track:
    - person
    - cat

ffmpeg:
  hwaccel_args: 
   #Optional: global input args (default: shown below)
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128

go2rtc:
  streams:
    Grillecke: 
      - "ffmpeg:http://192.168.x.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"
    Grillecke_sub: 
      - "ffmpeg:http://192.168.x.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password"
    Garage: 
      - "ffmpeg:http://192.168.x.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"
    Garage_sub: 
      - "ffmpeg:http://192.168.x.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password!"  

cameras:
  Grillecke:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Grillecke?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Grillecke_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect 
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4  
      enabled: true 
    record:
      enabled: false  
      retain: 
        days: 5 
    snapshots:
      enabled: true
      retain: 
        default: 7          
    motion:
      mask:
        - 0,348,0,0,87,0,157,0,181,0,288,0,598,0,177,201,178,347 
        - 437,480,640,480,640,444,441,441 
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect  
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4  
      enabled: true 
    record:
      enabled: false   
      retain: 
        days: 5
    snapshots:
      enabled: true
      retain: 
        default: 7     
    motion:
      mask:
        - 0,167,96,171,155,232,164,378,0,428
        - 640,164,640,208,109,214,103,169
        - 640,480,484,480,503,270,508,170,640,163
        - 0,480,0,441,65,425,246,480         
        - 0,0,640,0,640,223,0,199  
  Vorne: # <------ Name the camera
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://user:admin@192.168.x.xxx:554/11 # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://user:admin@192.168.x.xxx:554/12 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5   
      enabled: true
    snapshots:
      enabled: true
      retain: 
        default: 7
    record:
      enabled: false
      retain: 
        days: 5
    motion:
      mask:
        - 502,363,448,231,373,138,317,50,205,0,449,0,640,0,640,480,549,480 
        - 145,58,176,132,201,128,206,0,154,0,100,0,108,44 
        - 0,480,0,0,92,0,208,480
  Gartenseite: # <------ Name the camera
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://user:admin@192.168.x.xxx:554/11 # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://user:admin@192.168.x.xxx:554/12 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5  
      enabled: true 
    snapshots:
      enabled: true  
      retain: 
        default: 7
    record:
      enabled: false
      retain: 
        days: 5
    motion:
      mask:
        - 0,480,0,0,101,0,134,0,275,0,240,43,132,259,243,293,263,480    
        - 640,480,640,0,425,0,359,480

detectors:
  coral:
    type: edgetpu
    device: usb
```

and the docker-compose file:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Birdseye In v 0.12
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
