### DISCUSSION TITLE
Recording events - can mode: be set by object type?

### DISCUSSION THREAD

**Discussion by jay-kub** [blakeblackshear/frigate#8528] [Ask A Question] [answered]
My current recording config is listed below, with the _mode:_ set to _motion_.  I would prefer if the mode for car objects was "motion" while the mode for other objects was "all". 

Is it possible to set the mode: setting at the object level?

```
record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 60
      mode: motion
```
