### DISCUSSION TITLE
Docker container & system lockup

### DISCUSSION THREAD

**Discussion by lostage** [blakeblackshear/frigate#8557] [Ask A Question]
I've been having an issue for the past few months where after 12-24 hours, my entire computer will be unresponsive. After much testing/trial & error, I've narrowed it down to it only happening when I'm running Frigate. When Frigate isn't running, the system will stay up at least for a couple weeks (that's the longest I've gone without intentionally restarting for updates). I'd love to get down to what's causing this to happen (my cameras? my Frigate config?), but I can't trial and error this because my entire computer becomes unresponsive (including keyboard/mouse/network) and I have to hold the power button down to shut it down. It would be amazing if the Frigate container would just crash, leaving the rest of the computer alone. I don't remember this happening before the go2rtc integration.

Here's the relevant portion of my compose file:
```
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "250mb"
#     group_add:
#       - 110
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/configs/frigate/config.yml:/config/config.yml
      - /opt/docker-storage/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "pass"
    labels:
      - "diun.enable=true"
```

Frigate config (you can see most of the things I've tried in the comments):
```
# yaml-language-server: $schema=http://192.168.1.131:5000/api/config/schema.json

# Reolink camera resolutions:
# main: 2560x1440
# sub:  640x352


mqtt:
  host: 192.168.1.38
  user: user
  password: pass

# detectors:
#   cpu1:
#     type: cpu
#   cpu2:
#     type: cpu
#   cpu3:
#     type: cpu
#   cpu4:
#     type: cpu

# detectors:
#   coral:
#     type: edgetpu
#     device: usb

# go2rtc:
#   webrtc:
#     candidates:
#       - 192.168.1.131:8555
#       - stun:8555
#   streams:
#     Camera1:
#       - rtsp://user:password@192.168.10.26//h264Preview_01_main
#       # - "ffmpeg:Camera1#audio=opus"
#     Camera2:
#       - rtsp://user:password@192.168.10.27//h264Preview_01_main
#       # - "ffmpeg:Camera2#audio=opus"
#     Camera3:
#       - rtsp://user:password@192.168.10.28//h264Preview_01_main
#       # - "ffmpeg:Camera3#audio=opus"
#     Camera4:
#       - rtsp://user:password@192.168.10.197//h264Preview_01_main
#       # - "ffmpeg:Camera4#audio=opus"
#     Camera5:
#       - rtsp://user:password@192.168.10.25//h264Preview_01_main
#     #   - "ffmpeg:Camera5#audio=opus"

birdseye:
  mode: motion
  # width: 640
  # height: 352
  # width: 1920
  # height: 1072
  width: 1280
  height: 720
  # restream: true
  restream: false

detect:
  # enabled: true
  enabled: false
  # width: 640
  # height: 352
  # width: 1920
  # height: 1072
  width: 1280
  height: 720
  fps: 5

record:
  enabled: true
  retain:
    days: 7
    mode: motion


snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
      
motion:
  mask:
  #  - 620,352,620,325,400,325,400,352
  #  - 1876,1072,1876,1000,1235,1000,1235,1072
    - 1899,1072,1899,1010,1248,1003,1248,1072

# live:
#   #height: 352
#   height: 720

ffmpeg:
  # hwaccel_args: preset-intel-qsv-h264
  hwaccel_args: preset-vaapi

  # input_args: preset-rtsp-restream
  # output_args:
  #   record: preset-record-generic-audio-copy

  # output_args:
  #   record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  # hwaccel_args:
  #   - -hwaccel
  #   - vaapi
  #   - -hwaccel_device
  #   - /dev/dri/renderD128
  #   - -hwaccel_output_format
  #   - yuv420p

cameras:

  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.10.26//h264Preview_01_main
        # - path: rtsp://127.0.0.1:8554/Camera1
          roles:
            - record
            - detect
        # - path: rtsp://user:pass@192.168.10.26//h264Preview_01_sub
        #   roles:
        #     - detect
    motion:
      mask:
        - 1899,1072,1899,1010,1248,1003,1248,1072
        - 1920,0,1920,233,0,247,0,0

  Camera2:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.10.27//h264Preview_01_main
        # - path: rtsp://127.0.0.1:8554/Camera2
          roles:
            - record
            - detect
        # - path: rtsp://user:pass@192.168.10.27//h264Preview_01_sub
        #   roles:
        #     - detect

  Camera3:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.10.28//h264Preview_01_main
        # - path: rtsp://127.0.0.1:8554/Camera3
          roles:
            - record
            - detect
        # - path: rtsp://user:pass@192.168.10.28//h264Preview_01_sub
        #   roles:
        #     - detect
    zones:  
      zone_0:
        coordinates: 1807,0,1820,415,1707,514,1658,937,1609,921,1607,805,1638,415,1632,0
      zone_1:
        coordinates: 1461,373,1454,709,1461,925,1599,931,1630,172,1626,0,1480,0

  Camera4:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.10.197//h264Preview_01_main
        # - path: rtsp://127.0.0.1:8554/Camera4
          roles:
            - record
           # - detect
        # - path: rtsp://user:pass@192.168.10.197//h264Preview_01_sub
        #   roles:
        #     - detect

  Camera5:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.10.25//h264Preview_01_main
        # - path: rtsp://127.0.0.1:8554/Camera5
          roles:
            - record
            - detect
        # - path: rtsp://user:pass@192.168.10.25//h264Preview_01_sub
        #   roles:
        #     - detect
```

I'm using 5 Reolink E1 Pro cameras, an old Intel i7-3770K CPU @ 3.50GHz with 32gb ram. The logs I've found have been really unhelpful (consistent HomeAssistant connections and then nothing; once I saw one of the cameras caused ffmpeg to crash).

Anything stand out that I should try? Ideally I'd love to isolate the crash to the container rather than the entire computer locking up.

Currently when I try to look at the logs I'm getting `Error grabbing logs: invalid character '\x00' looking for beginning of value`, so here's the JSON log if that helps (you can see the unresponsiveness starts after the last call to Home Assistant):

```
{"log":"2023-11-06 03:46:07.793399940  192.168.1.38 - - [06/Nov/2023:03:46:07 -0600] \"GET /api/stats HTTP/1.1\" 200 3420 \"-\" \"HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11\" \"-\"\n","stream":"stdout","time":"2023-11-06T09:46:07.793565043Z"}
{"log":"2023-11-06 03:46:15.782942603  192.168.1.38 - - [06/Nov/2023:03:46:15 -0600] \"GET /api/stats HTTP/1.1\" 200 3455 \"-\" \"HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11\" \"-\"\n","stream":"stdout","time":"2023-11-06T09:46:15.783135409Z"}
{"log":"2023-11-06 03:46:23.783513471  192.168.1.38 - - [06/Nov/2023:03:46:23 -0600] \"GET /api/stats HTTP/1.1\" 200 3420 \"-\" \"HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11\" \"-\"\n","stream":"stdout","time":"2023-11-06T09:46:23.783662395Z"}
{"log":"2023-11-06 03:46:31.775946642  192.168.1.38 - - [06/Nov/2023:03:46:31 -0600] \"GET /api/stats HTTP/1.1\" 200 3421 \"-\" \"HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11\" \"-\"\n","stream":"stdout","time":"2023-11-06T09:46:31.776033054Z"}
{"log":"2023-11-06 03:46:39.794558617  192.168.1.38 - - [06/Nov/2023:03:46:39 -0600] \"GET /api/stats HTTP/1.1\" 200 3420 \"-\" \"HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11\" \"-\"\n","stream":"stdout","time":"2023-11-06T09:46:39.79482708Z"}
{"log":"s6-rc: info: service s6rc-fdholder: starting\n","stream":"stderr","time":"2023-11-06T13:39:41.588371043Z"}
{"log":"s6-rc: info: service s6rc-oneshot-runner: starting\n","stream":"stderr","time":"2023-11-06T13:39:41.597414425Z"}
{"log":"s6-rc: info: service s6rc-oneshot-runner successfully started\n","stream":"stderr","time":"2023-11-06T13:39:41.941279649Z"}
{"log":"s6-rc: info: service fix-attrs: starting\n","stream":"stderr","time":"2023-11-06T13:39:41.955491625Z"}
{"log":"s6-rc: info: service s6rc-fdholder successfully started\n","stream":"stderr","time":"2023-11-06T13:39:41.997327781Z"}
{"log":"s6-rc: info: service fix-attrs successfully started\n","stream":"stderr","time":"2023-11-06T13:39:42.489191283Z"}
{"log":"s6-rc: info: service legacy-cont-init: starting\n","stream":"stderr","time":"2023-11-06T13:39:42.489239104Z"}
{"log":"s6-rc: info: service legacy-cont-init successfully started\n","stream":"stderr","time":"2023-11-06T13:39:42.592242887Z"}
{"log":"s6-rc: info: service log-prepare: starting\n","stream":"stderr","time":"2023-11-06T13:39:42.707875416Z"}
{"log":"s6-rc: info: service log-prepare successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.348519713Z"}
{"log":"s6-rc: info: service nginx-log: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.348661629Z"}
{"log":"s6-rc: info: service go2rtc-log: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.348784172Z"}
{"log":"s6-rc: info: service frigate-log: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.348874301Z"}
{"log":"s6-rc: info: service nginx-log successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.45849231Z"}
{"log":"s6-rc: info: service frigate-log successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.537338373Z"}
{"log":"s6-rc: info: service go2rtc-log successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.540992556Z"}
{"log":"s6-rc: info: service go2rtc: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.54125308Z"}
{"log":"s6-rc: info: service go2rtc successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.648583468Z"}
{"log":"s6-rc: info: service go2rtc-healthcheck: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.648735067Z"}
{"log":"s6-rc: info: service frigate: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.648892314Z"}
{"log":"2023-11-06 07:39:44.661302415  [INFO] Preparing go2rtc config...\n","stream":"stdout","time":"2023-11-06T13:39:44.661651537Z"}
{"log":"s6-rc: info: service go2rtc-healthcheck successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.740049529Z"}
{"log":"s6-rc: info: service frigate successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.742935951Z"}
{"log":"s6-rc: info: service nginx: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.743514813Z"}
{"log":"2023-11-06 07:39:44.745602171  [INFO] Starting Frigate...\n","stream":"stdout","time":"2023-11-06T13:39:44.745722579Z"}
{"log":"s6-rc: info: service nginx successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.756901743Z"}
{"log":"s6-rc: info: service legacy-services: starting\n","stream":"stderr","time":"2023-11-06T13:39:44.756923585Z"}
{"log":"2023-11-06 07:39:44.758420492  [INFO] Starting NGINX...\n","stream":"stdout","time":"2023-11-06T13:39:44.758532771Z"}
{"log":"s6-rc: info: service legacy-services successfully started\n","stream":"stderr","time":"2023-11-06T13:39:44.920544966Z"}
```
