### DISCUSSION TITLE
[List] Proper Camera Config, lets go!

### DISCUSSION THREAD

**Discussion by Fettkeewl** [blakeblackshear/frigate#8567] [General]
Hello peeps, 
Instead of everyone with the same cameras struggling with the frigate.yml setup process I was thinking we could make this thread about the most optimal setup for Cameras as in regards to setting up the actual camera in frigate.yml, 

I'll start off by inserting my config as it works for me and my cameras, if anyone sees better settings that I could apply please feel free to post about it and I could then update this post. For cameras I don't have, ill strictly adhere to what you post and update accordingly as people see fit.

Post config and camera models that it works for!

<details><summary>Tapo C200, C310, C520WS</summary>
<p>

Remember to create a camera account with your custom
**Username** and **Password**
From within your Tapo App > Camera > Camera Settings > Advanced Settings > Camera Account

```yaml
# Camera stream definitions
go2rtc:
  streams:
     # High res main stream name
    CameraName:
      - "ffmpeg:rtsp://Username:Password@CameraIP:554/stream1#video=copy#audio=copy#audio=aac"
     # Low res sub stream name
    CameraName_sd:
      - rtsp://Username:Password@CameraIP:554/stream2
``` 

```yaml
# Camera entity definitions and settings
cameras:
  # camera entity name
  CameraName:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/CameraName
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CameraName_sd
          input_args: preset-rtsp-restream
          roles:
            - detect 
    detect:
      width: 640 
      height: 360
      fps: 5
``` 
</p>
</details>

**Comment by XT-Martinez** [comment]
Hi,

I just came across this post and just wanted to add a better protocol for high quality stream.
Since **go2rtc v1.2,** the proprietary camera protocol that the Tapo App use is now supported.
This works much better for me as it connects almost instantly unlike RTSP where I often get timeout errors from go2rtc logs.
The tapo protocol also supports 2-way audio which is great. It was the only reason I use the Tapo App.

```YAML
streams:
    camera.livingroom:
        - tapo://admin:<TP_LINK_TAPO_ACCOUNT_PASSWORD_SHA256_UPPERCASE>@<CameraIP>
```

P.S. I have the Tapo C200 model

**Reply by PatSloan** [reply]
this does not work on the C325wb cameras from tapo.

I tried all variations of this with Frigate 13rc1 and got 

```
- tapo://camadmin:PW@192.168.30.43:554/stream1
- "ffmpeg:driveway#audio=aac#timeout=5"
```

logs show after doing a ffprobe

```
2024-01-24 10:26:52.199483804  [2024-01-24 10:26:52] ffmpeg.driveway.record         ERROR   : rtsp://127.0.0.1:8554/driveway: Invalid data found when processing input
2024-01-24 10:26:52.199578613  [2024-01-24 10:26:52] watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
2024-01-24 10:26:52.199627193  [2024-01-24 10:26:52] watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
```

**Reply by XT-Martinez** [reply]
I think the username should be specifically `admin` and the password should be the SHA256 encrypted string (Uppercase) of the Tapo account password, not the rtsp password that you set via Tapo App. There should also be no rtsp port like this:

```
tapo://admin:<TAPO_SHA256_PASSWORD>@CameraIP
```

You can see the documentation for tapo protocol here https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-tapo

**Reply by PatSloan** [reply]
Thanks, will check that out.

**Reply by BornInThe50s** [reply]
I seem to be having issues with getting the Tapo protocol to connect. I've tried the 3 dfferent authentication methods (MD5, SHA256 & Cloud password) as shown on the protocol readme https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-tapo as below

frigate.yml - Got2RTC

![Go2RTC1](https://github.com/user-attachments/assets/60719f53-fc0c-4dfd-b4ee-70e1f5f6e370)

frigate.yml - Camera config ( I put the audio detect in the main stream otherwise it wouldn't save the frigate.yml file)

![Frigate](https://github.com/user-attachments/assets/8c15be07-eb80-4683-8210-aeb679c0c06a)

With those configs set I can view the cameras etc but get this in the log

![log](https://github.com/user-attachments/assets/670d97e1-9864-4493-8532-f4e50773ebe7)

If I remove the second stream from both the Go2RTC and camera configs, and uncomment the detect/record on the main stream I get no video just the authorisation error.  

The MD5 and SHA256 hash are created from the Tapo Cloud password (is this the Tapo app password as I don't actually use the Tapo cloud service?) I have also tried the Tapo RTSP stream account password as hash's without success.

Frigate - 0.13.2-6476f8a
Go2RTC - go2rtc 1.8.4
HAOS on a NUC - Core 2024.7.4
                              Supervisor 2024.06.2
                              Operating System 12.4
                              Frontend 20240710.0

Any ideas how I can get the main stream working with the tapo protocol - it works fine when using the regular frigate rtsp connection format and not using Go2RTC. I'd like to get away from the rtsp stream and using the rtsp account on the camera's for Frigate altogether (if posible) and just use the tapo stream for detect/record.

**EDIT**

After some digging around it seems that Tapo have rolled out a firmware fix that causes this issue. The issue appears to have been fixed for the Home Assistant integration but not Go2RTC as far as I can tell.  
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551#issuecomment-2241111249

I'll leave this here for reference.

**Comment by Fettkeewl** [comment]
> Hi,
> 
> I just came across this post and just wanted to add a better protocol for high quality stream. Since **go2rtc v1.2,** the proprietary camera protocol that the Tapo App use is now supported. This works much better for me as it connects almost instantly unlike RTSP where I often get timeout errors from go2rtc logs. The tapo protocol also supports 2-way audio which is great. It was the only reason I use the Tapo App.
> 
> ```yaml
> streams:
>     camera.livingroom:
>         - tapo://admin:<TP_LINK_TAPO_ACCOUNT_PASSWORD_SHA256_UPPERCASE>@<CameraIP>
> ```
> 
> P.S. I have the Tapo C200 model

Cool! trying it out now :) Interesting to see how many errors dissappear from my go2rtc logs
thanks for the tip

**Reply by muunk1e** [reply]
How do you set up the sub stream for detection?

**Comment by Fettkeewl** [comment]
@XT-Martinez it's strange, video is working flawlessly.
however in frigate I get no sound viewing through MSE but I do have sound in my frigate card that I think is using the Go2rtc stream.
How did you resolve this? I want my recordings (that i think use MSE stream) to have audio aswell
![image](https://github.com/blakeblackshear/frigate/assets/25577040/2169ecd1-b63a-4190-9b3e-7165114bacf9)

**Reply by raeserfisk** [reply]
I'll +1 this question. I have full sound in MSE and 2RTC but not in any recordings. Have anyone solved this? Apart from sound the tapo://-solution is amazing! :)

**Reply by WegnerDan** [reply]
Were you able to solve the audio issue?

**Reply by raeserfisk** [reply]
I switched back and forth between rtsp:// and tapo:// without a final conclusion - got sounds working on both though with the FFMpeg#aac-solution. Currently running rtsp but I'll try to set the cams on ethernet to make sure I've covered all ends.

**Comment by Waank1** [comment]
Still learning, this code works with Foscam VZ4 4MP:

'''
mqtt:
  enabled: True

cameras:
  front_east:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://USERNAME:PASSWORD@192.168.X.XX:443/videoMain
          roles:
            - detect
detect:
 width: 3480 # <---- update for your camera's resolution
 height: 2160 # <---- update for your camera's resolution
 fps: 5
record: # <----- Enable recording
  enabled: True 
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 7
      mode: active objects
      objects:
        cat: 2
        person: 7
'''

I only have one camera working, I have yet to figure out how to add a second I always get Frigate.yaml errors.

**Reply by michaellunzer** [reply]
thank you!!!! this was exactly what worked for me. I was getting a ton of 401 UNAUTHORIZED on Docker Wyze Bridge.

```rtsp://USERNAME:PASSWORD@192.168.X.XX):PORT```

**Comment by piyushpranjal03** [comment]
IDK what's this hack but I changed this:
```
      inputs:
        - path: rtsp://127:0:0:1:8554/roadside
```
to this:
```
      inputs:
        - path: rtsp://localhost:8554/roadside
```

I am using Tapo C222. Added `gortc` like this:
```
# Camera stream definitions
go2rtc:
  streams:
    roadside:
      # Final correct working without any issues at http://localhost:1984/stream.html?src=roadside
      - rtsp://your_custom_username:user_custom_non_hashed_password@192.168.18.102:554/stream1
```

I was able to access this gortc via http using this link `http://localhost:1984/stream.html?src=roadside` but still it was giving error `unable to ready frames` inside frigate ui.

Then i tried to use this link `rtsp://127:0:0:1:8554/roadside` inside VLC and somehow VLC is removing everything after 127 so I replaced entire ip `127.0.0.1` to `localhost` and now it is working.

**Reply by frehall** [reply]
> IDK what's this hack but I changed this:
> 
> ```
>       inputs:
>         - path: rtsp://127:0:0:1:8554/roadside
> ```
> 
> to this:
> 
> ```
>       inputs:
>         - path: rtsp://localhost:8554/roadside
> ```
> 
> I am using Tapo C222. Added `gortc` like this:
> 
> ```
> # Camera stream definitions
> go2rtc:
>   streams:
>     roadside:
>       # Final correct working without any issues at http://localhost:1984/stream.html?src=roadside
>       - rtsp://your_custom_username:user_custom_non_hashed_password@192.168.18.102:554/stream1
> ```
> 
> I was able to access this gortc via http using this link `http://localhost:1984/stream.html?src=roadside` but still it was giving error `unable to ready frames` inside frigate ui.
> 
> Then i tried to use this link `rtsp://127:0:0:1:8554/roadside` inside VLC and somehow VLC is removing everything after 127 so I replaced entire ip `127.0.0.1` to `localhost` and now it is working.

Can you try

        - path: rtsp://127.0.0.1:8554/roadside

And report back please.

**Reply by piyushpranjal03** [reply]
I pulled the images yesterday again and now this ip is also working without any issues

**Comment by gabrielssanches** [comment]
after googling around, I ended up with this:

- 2 streams, one for detection, one for recording
- PTZ setup with onvif
- camera auth with camera account.

Recordings have audio thanks to "audio=aac" and "preset-record-generic-audio-aac" settings

obs: <subdomain>.home.lab is just an alias in my network

I use a mix of C200, C500 and C310 cameras

```
go2rtc:
  streams:
    camera-frontdoor:
      - rtsp://<camera_user>:<camera_pass>@camera-frontdoor.home.lab:554/stream1
      - "ffmpeg:camera-frontdoor#video=h264#audio=aac#hardware"
    camera-frontdoor-detect:
      - rtsp://<camera_user>:<camera_pass>@camera-frontdoor.home.lab:554/stream2
      
 cameras:
  camera-frontdoor:
    enabled: True
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/camera-frontdoor
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/camera-frontdoor-detect
          roles:
            - detect
    onvif:
      host: camera-frontdoor.home.lab
      port: 2020
      user: "<camera_user>"
      password: "<camera_pass>"

record:
  enabled: True

detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  height: 175
```

**Comment by substeeze** [comment]
Tapo C220:

```
go2rtc:
  streams:
    tapoC220:
      ffmpeg:rtsp://<camera_user>:<camera_pass>@<camera_ip>/stream2#video=h264#audio=aac#hardware
```

**Comment by Etregin** [comment]
I know im late to the party but hopefully someone can help me, i have a Deco mesh network and 4 Tapo C220 cameras and 2 Tapo C520WS cameras and 2 EZVIZ TY1 cameras and its been a nightmare to get them to work together on frigate even on seperate instances of frigate

My 2 Tapo C520WS i have no issues with (so far) but for my 4 Tapo C220 cameras i had to disable one and set another to stream2 because if i dont im riddled with ffmpeg errors in the frigate log which messes up with the rest of the cameras views and recording

even with the current setup i get the occasional burst of ffmpeg errors which messes up the view and sometime it even congests my network that i cant even view the cameras from the tapo app and i have to turn off frigate or reboot it to resolve the issues, have anyone faced anything similar to this?

**Reply by Etregin** [reply]
Note, im not gonna get into the EZVIZ ones for now, just want to figure out getting the tapo ones to play nice first before going down the other rabbit hole :D

**Reply by ElectronicBattle** [reply]
I wonder if this might help:

https://github.com/eduard256/Strix

I'm using it to search my cameras (Hikvision, Tapo and one unknown) and Strix gives me example snippets for Frigate and others e.g.

<img width="653" height="651" alt="image" src="https://github.com/user-attachments/assets/7a5fdf8c-a624-4507-b115-6338e47f9bd7" />
<img width="630" height="569" alt="image" src="https://github.com/user-attachments/assets/1058c8ed-b827-406c-aa97-4df1cddf4c6a" />
<img width="739" height="789" alt="image" src="https://github.com/user-attachments/assets/34df5aa8-8fba-43c0-8535-7185ed20fa75" />
<img width="1059" height="1774" alt="image" src="https://github.com/user-attachments/assets/c6ee12ef-9752-4682-b6d9-c6234e0dd59c" />

and then the next screen gives example snippets for frigate and go2rtc.

My Tapos (C320WS and C325WB) all work with e.g.

```      
go2rtc:
  streams:
    tapo_upper_patio:
      - rtsp://admin:password@192.168.1.144:554/stream1#video=h264 #transport=tcp # stream1 is main
    tapo_upper_patio_sub:
      - rtsp://admin:password@192.168.1.144:554/stream2 #transport=tcp # stream2 is sub
```

and

```
cameras:
  tapo_upper_patio:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/tapo_greenhouse_sub
          roles: [detect]
        - path: rtsp://localhost:8554/tapo_greenhouse
          roles: [record]
```
