### DISCUSSION TITLE
Restream rtsp url does not work in VLC?

### DISCUSSION THREAD

**Discussion by Fettkeewl** [blakeblackshear/frigate#8569] [Ask A Question] [answered]
Hello 
I have go2rtc setup and have working restream-streams I can view from home assistant and through frigate addon.
My environment is HASSOS on VirtualBox, network adapter in promiscious mode so no portforwarding is required. 
HASSOS is available at 192.168.1.100 in my lan

Now I would like to test using this rtsp restream for other purposes but can't get past trying it out in vlc. 
as per the documentation @ [https://docs.frigate.video/configuration/restream/](https://docs.frigate.video/configuration/restream/)
I should be able to access my cameras by the rtsp url below but I can't manage a connection at all. So am I missing some crucial setting not documented at the previously mentioned link?

**rtsp://192.168.1.100:8554/livingroom**

All my cameras are setup similiarly to below

```yaml
go2rtc:
  streams:
    livingroom:
      - "ffmpeg:rtsp://user:pw@192.168.1.231:554/stream1#video=copy#audio=copy#audio=aac"
    livingroom_sd:
      - rtsp://user:pw@192.168.1.231:554/stream2

cameras:
  # Kamera i Vardagsrummet, TP-LINK Tapo C200
  livingroom:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/livingroom
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/livingroom_sd
          input_args: preset-rtsp-restream
          roles:
            - detect 
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    motion:
      mask:
        - 0,0,230,0,230,22,0,22
```
