### DISCUSSION TITLE
How to properly update via Docker Compose

### DISCUSSION THREAD

**Discussion by Drizzt321** [blakeblackshear/frigate#8571] [Ask A Question] [answered]
How exactly do I properly update my Frigate docker image. I installed following the Docker Compose instructions, although back over a year ago. However, one thing I noticed, is the yaml I copied from the instructions has `image: blakeblackshear/frigate:stable`, whereas the current install (no upgrade instructions!!) instructions for docker compose says `image: ghcr.io/blakeblackshear/frigate:stable`. How do I properly upgrade/migrate or what not?

**Comment by NickM-27** [comment]
it's not really clear what you are asking. `image: ghcr.io/blakeblackshear/frigate:stable` should be used and whenever a new stable update is put out it will be downloaded on the same tag

**Reply by Drizzt321** [reply]
@NickM-27 my original installed used the first form, which I copied straight from the install instructions.

So as not to b0rk anything, as I don't really use docker much anywhere or fully understand the semantics of it, how the heck do I properly migrate/switch to this different `ghcr.io` image location?

**Reply by NickM-27** [reply]
You edit the docker compose file and then run 

```
docker compose down
docker compose up -d
```

**Reply by Drizzt321** [reply]
@NickM-27 Ah, ok. That worked. Would you recommend a cron job to automatically restart to re-fetch the latest regularly?

**Reply by NickM-27** [reply]
No I would not, it is best to see the releases and read the release notes before updating or you may find that your system does not work after automatically updating

**Reply by bitvilag** [reply]
This was a constant debate on one the HA forums. I prefer auto-update even if it brakes as I can always revert, but the number of minutes I spend with updates (with no issues) is way more than revert and honestly I never read readmes. There have been some breaking changes wihch I fixed by reading forums. These days I just ask ChatGPT. I am not doing this because I am not equipped with knowledge. I do it because I have limited time and this method seems take less time.

**Reply by blakeblackshear** [reply, marked as answer]
The correct way to fetch an updated image in a docker compose is

```
docker compose pull
docker compose up -d
```

This will pull down a new image and then recreate the container with the updated image.

**Reply by FoUStep** [reply]
I've been trying to update to 0.13.2 from 0.13.1 using the proper way according to your instruction on my Pi 5.

```
step@stepi5:~/frigate $ sudo docker compose down
[+] Running 2/2
 ✔ Container frigate        Removed                                                                                         10.2s
 ✔ Network frigate_default  Removed                                                                                          0.3s
step@stepi5:~/frigate $ sudo docker compose pull
[+] Pulling 1/1
 ✔ frigate Pulled                                                                                                            0.6s
step@stepi5:~/frigate $ sudo docker compose up -d
[+] Running 1/2
 ⠼ Network frigate_default  Created                                                                                          0.4s
 ✔ Container frigate        Started
```

With my docker-compose.yml:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config:/config
      - ./storage/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
```

Has it not been pushed to stable yet? Is it also possible to check if it's available, next to manually checking on github?
