### DISCUSSION TITLE
All is disabled ( detect/recording etc...) but huge cpu use

### DISCUSSION THREAD

**Discussion by pinkfloydFR** [blakeblackshear/frigate#8582] [Ask A Question]
hi,

when my frigate is in state pause, ie no detect or recording, i am aware of the cpu usage

I understand this cpu usage when detecting, but when it does nothing, why the comsumption is so high ? do i miss something ?

Machine is a Ubuntu Hyper-v (  12 vCpu / 16 Go RAM ) on Physical : double Xeon-E5260 @ 2.60 Ghz ( 32 cores )

Thanks !

![image](https://github.com/blakeblackshear/frigate/assets/49475899/936b59ab-6002-41f6-b4fb-44c0daf43875)

![image](https://github.com/blakeblackshear/frigate/assets/49475899/315ba607-9ca8-4d8e-864b-0cc4928be49a)

```
mqtt:
  host: xxxx
  user: xxx
  password: xxxxxx

database:
  path: /db/frigate.db

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous

ffmpeg:
  global_args: -hide_banner -loglevel warning

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False

record:
  enabled: True
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 14
      mode: active_objects

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to 
      # be considered a true positive (default: shown below)
      threshold: 0.7



cameras:

# ---------------

  sonette:
    ffmpeg:
      inputs:
        - path: xxxxx
          roles:
            - detect
            - rtmp
            - record
#      ouput_args:
#        record: preset-record-generic-audio-copy
    motion:
      mask: 791,535,819,680,879,631,1128,605,1366,591,1450,641,1815,661,1821,363,1727,295,1820,218,1662,26,367,36,0,22,0,544
    detect:
      width: 1920
      height: 1080
      fps: 10


  jardin:
    ffmpeg:
      inputs:
        - path: xxxxxx
          roles:
            - detect
            - rtmp
            - record
    motion:
      mask: 390,720,220,141,471,58,853,36,1333,30,1728,107,1920,134,1920,75,1920,0,115,0,0,0,0,1080,415,1080
    detect:
      width: 1920
      height: 1080
      fps: 10

# --------------
  salon:
    ffmpeg:
      inputs:
        - path: xxxxxx
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10

# -------------
  entree:
    ffmpeg:
      inputs:
        - path: xxxxxx
          roles:
            - detect
            - rtmp
            - record
    motion:
      mask:
        - 0,129,0,0,1920,0,1920,946,1920,618,1477,174,1261,122,1183,175,678,175,0,187
    detect:
      width: 1920
      height: 1080
      fps: 10
```
