### DISCUSSION TITLE
Dell Optiplex 7050 Micro with Coral TPU -> high CPU

### DISCUSSION THREAD

**Discussion by mbrocke123** [blakeblackshear/frigate#8635] [Ask A Question] [answered]
Hi everyone,
I switched from an old Intel Nuc to a Dell Optiplex 7050 with Coral TPU: CPU is a Core i5-6500T 2.5GHz. This is a running Ubuntu 22.04.

I think my CPU (50%) is pretty high. It was lower with the Intel Nuc. Does anybody have an idea how to improve this? I have 5 cameras.

```
mqtt:
  enabled: False 

birdseye:
  enabled: False

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow  

#Global Object Settings
objects:
  track:
    - person
    - cat

ffmpeg:
  hwaccel_args: 
   #Optional: global input args (default: shown below)
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128

go2rtc:
  streams:
    xxxx: 
      - "ffmpeg:http://xxxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx#video=copy#audio=copy#audio=opus"
    xxxx: 
      - "ffmpeg:http://xxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx"
    xxxx: 
      - "ffmpeg:http://xxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx#video=copy#audio=copy#audio=opus"
    xxxx: 
      - "ffmpeg:http://xxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx"  
    xxxx: 
      - "ffmpeg:http://xxxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx#video=copy#audio=copy#audio=opus"
    xxxx: 
      - "ffmpeg:http://xxxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx"   

cameras:
  xxxx:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect 
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4  
      enabled: true 
    record:
      enabled: false  
      retain: 
        days: 5 
    snapshots:
      enabled: true
      timestamp: true
      retain: 
        default: 7          
    motion:
      mask:
        - 229,366,104,355,0,321,0,44,0,0,94,0,183,0,367,0,640,0,640,277,481,353
  xxxx:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect 
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4  
      enabled: true 
    record:
      enabled: false  
      retain: 
        days: 5 
    snapshots:
      enabled: true
      timestamp: true
      retain: 
        default: 7          
    motion:
      mask:
        - 0,348,0,0,87,0,157,0,181,0,288,0,598,0,177,201,178,347 
        - 437,480,640,480,640,444,441,441 
  xxxx:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/xxxx?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect  
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 4  
      enabled: true 
    record:
      enabled: false   
      retain: 
        days: 5
    snapshots:
      enabled: true
      timestamp: true
      retain: 
        default: 7     
    motion:
      mask:
        - 0,167,96,171,155,232,164,378,0,428
        - 640,164,640,208,109,214,103,169
        - 640,480,484,480,503,270,508,170,640,163
        - 0,480,0,441,65,425,246,480         
        - 0,0,640,0,640,223,0,199  
  xxxx: # <------ Name the camera
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://admin:xxxx@xxxx/11 # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://admin:xxxx@xxxx/12 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5   
      enabled: true
    snapshots:
      enabled: true
      timestamp: true
      retain: 
        default: 7
    record:
      enabled: false
      retain: 
        days: 5
    motion:
      mask:
        - 502,363,448,231,373,138,317,50,205,0,449,0,640,0,640,480,549,480 
        - 145,58,176,132,201,128,206,0,154,0,100,0,108,44 
        - 0,480,0,0,92,0,208,480
  xxxx: # <------ Name the camera
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://admin:xxxx@xxxx/11 # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://admin:xxxx@xxxx/12 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5  
      enabled: true 
    snapshots:
      enabled: true  
      timestamp: true
      retain: 
        default: 7
    record:
      enabled: false
      retain: 
        days: 5
    motion:
      mask:
        - 0,480,0,0,101,0,134,0,275,0,240,43,132,259,243,293,263,480    
        - 640,480,640,0,425,0,359,480

detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

live:
  height: 640
  quality: 1    
```

Thanks so much!
