### DISCUSSION TITLE
Cant get RTMP re-stream to work

### DISCUSSION THREAD

**Discussion by goulaobangzi** [blakeblackshear/frigate#870] [Ask A Question]
path: rtsp://driveway_cam:password@192.168.1.13/live

Ha address 192.168.1.130:8213

rtsp://192.168.1.130:1935/cameras/ 

tried on the VLC got nothing.

          roles: has added 
            - rtmp
         rtmp: enabled 
            - enabled 

detect, clips are working fine. 

Need some help .

Please

**Comment by HIT2022** [comment]
Please re-review the [docs](https://frigate-paularmstrong1.vercel.app/configuration/cameras#rtmp-streams).

```
  MyCamera:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://myCameraPath
          roles:
            - rtmp
    rtmp:
      enabled: true
```

Accessible at **rtmp**://myHA/**live**/MyCamera
