### DISCUSSION TITLE
Can't toggle on / off camera detection from HA into Frigate.

### DISCUSSION THREAD

**Discussion by Vampyrebe** [blakeblackshear/frigate#8720] [Ask A Question] [answered]
Hey everyone, 

I'm encountering a bit of an issue when I try to create an automation for activation and desactivation of the detection on my cameras. 

I also searched for solutions, but either I don't quite understand what they mean and how they do it, or it just doesn't work for me. One of the post I read was mentioning something about injecting a code in MQTT with HA Red (if I remember right), but I absolutely have no idea on how to do that. I have HA OS installed on its own machine, so I'm not sure if it's something specific for HA red. 
Another post mentioned using the switch state on the entity with the detect in the end, which is what I use here. And another post was mentioning this is not possible in Frigate, and the answer was to create an executable file to swap configurations and restart frigate. So from what I read, it's going all over the place. 

I've installed Frigate NVR, added the frigate integration inside HA. I do have access to the sensors inside HA, and I see all cameras working inside Frigate. Sure I can activate and desactivate the detection inside Frigate, but I would prefer it being automated. 

Sadly, it's where it stops. I have created a quite complex automation based on different scenarios. The automation triggers fine, and give no error, but the toggle doesn't happen in frigate. 

So I created a very light test automation, driven by a helper. Once again, the automation triggers and HA shows me it has done it completely, but Frigate stays with the same status unchanged on detection. 

I give you here my small test automation, I think it's way easier to read rather than trying to understand a complex 4 cases scenario. 

```
alias: test
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.test
    from: "off"
    to: "on"
condition: []
action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.camera_hall_detect
mode: single
```
I'm not entirely sure why that automation doesn't trigger inside Frigate. I would appreciate any help, I'm quite new with HA (not a month old with it yet). 

Thank you very much for reading,
