### DISCUSSION TITLE
Docker Compose stack on macvlan in portainer

### DISCUSSION THREAD

**Discussion by johnvpr** [blakeblackshear/frigate#8722] [General]
Did anyone managed to get frigate docker compose stack on portainer working on   macvlan

I have this nixos on lan 192.168.**10**.2 and wanted to have frigate on  192.168.**20**.6

NixOs network config
```
  vlans = {
    vlan10 = { id=10; interface="eno1"; };
    vlan20 = { id=20; interface="eno1"; };
    vlan40 = { id=40; interface="eno1"; };
    vlan99 = { id=99; interface="eno1"; };
  };

  bridges = {
      vbr20 = { interfaces = [ "vlan20" ];# rtsp = true;
              };
  };

 interfaces.vbr20.ipv4.addresses = [{
   address = "192.168.20.2";
   prefixLength = 24;
 }];
```

and was trying this config without luck:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true  
    mem_limit: "2g"   
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta5
    shm_size: "256mb" 
    devices:
      - /dev/bus/usb:/dev/bus/usb  
 
    networks:
      # Same name of network defined above
      macvlan_network:
        ipv4_address: 192.168.20.6
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml 
      - /home/frigate/config:/config 
      - /media/frigate:/media/frigate
      - /home/media:/media/frigate
      
      - type: tmpfs  
        target: /tmp/cache
        tmpfs:
          size: 1000000000
          
    ports:
      - "5000:5000"
      - "1935:1935"  
      - "8554:8554" 
     
networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: eno1.20
    ipam:
      config:
        - subnet: "192.168.20.0/24"
          ip_range: "192.168.20.64/26"
          gateway: "192.168.20.1"
```
