### DISCUSSION TITLE
Snapshots uses low resolution feed

### DISCUSSION THREAD

**Discussion by cliffm** [blakeblackshear/frigate#874] [Ask A Question] [answered]
I am using the Clips and Snapshots features. I use a low resolution input for detection, and a higher resolution for clips. I expected snapshots to use the higher resolution feed, since it seems to be related to clips, but instead it uses the low resolution input. Is there an option or configuration to change this?

My camera config:

```
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: <low resolution url>
          roles:
            - detect    
        - path: <high resolution url>
          roles:
            - rtmp
            - clips
    height: 360 
    width: 480
    fps: 5
    motion:
      mask:
        - 480,0,480,360,357,360,358,136,0,136,0,0
    best_image_timeout: 3
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_area: 10000
          max_area: 1000000
          min_score: 0.5
          threshold: 0.7
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 14
```
