### DISCUSSION TITLE
Help Transcodding H265

### DISCUSSION THREAD

**Discussion by dellorianes** [blakeblackshear/frigate#8751] [General]
Hi, I have frigate running in a docker.
First thing, I passed throug a nvidia GTR 905 to frigate.
Here you have `ffmpeg -decoders | grep cuvid` info:
```
` V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)`
```

So, I understand that mi gpu can decode H265 videos.

I have 2 cameras:
 - Reolin Duo 2 that streams in H265 (main) and H264 )(sub)
 - Chinesse cam only in H264

```
`mqtt:
  host: 192.168.1.7
  port: 1883
  user: mqtt
  password: mypass

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h265

go2rtc:
  streams:
    recinto_sub:
      - rtsp://192.168.1.51:554/user=admin&password=xxxxxxx&channel=1&stream=1.sdp?real_stream--rtp-caching=100
    recinto:
      - rtsp://192.168.1.51:554/user=admin&password=xxxxxxx&channel=1&stream=0.sdp?real_stream--rtp-caching=100
    entrada:
      - rtsp://home:xxxxxxx@192.168.1.73:554/h265Preview_01_main
#      - http://192.168.1.73/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx.
      - "ffmpeg:back#video=h264"
    entrada_sub:
      - rtsp://home:xxxxxxxx@192.168.1.73:554/h264Preview_01_sub 
  webrtc:
    candidates:
      - 192.168.1.2:8555

cameras:
  recinto:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/recinto_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/recinto?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 2
          mode: active_objects
  entrada:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrada?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrada_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 25 
#      mask:
#        - 238,456,382,169,413,106,437,60,410,0,385,0,287,0,0,0,0,576,160,576
#        - 378,426,441,402,451,321,466,142,615,126,629,209,637,510,363,514
#        - 1065,172,1316,183,1164,0,493,0,471,133
    detect:
      enabled: True
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
    objects:
      track:
        - person`
```
 
My problem is that my GPU do not transcode the H265 signal of the Riolink camera

This is what is see when running `nvidia-smi`
```
`# nvidia-smi
Sun Nov 26 14:23:19 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 950         Off | 00000000:03:00.0 Off |                  N/A |
| 39%   29C    P0              29W / 115W |    187MiB /  2048MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+`
```

Everithing works except the go2rtc of the "Entrada" camera, that continues streaming in H265

Thank you

**Comment by NickM-27** [comment]
you are using `      - "ffmpeg:back#video=h264"` which is referencing a back stream which does not exist. Also there is no `#hardware` which means it would be done on the CPU not on the GPU

**Reply by dellorianes** [reply]
How should I include "#hardaware" 

I thought that, for colling the nvidia gpu,  it was enough to include 
```
ffmpeg:
  hwaccel_args: preset-nvidia-h265
```

Thank you again

**Reply by NickM-27** [reply]
that is for frigate hardware acceleration, go2rtc is its own separate config with its own separate settings

**Reply by dellorianes** [reply]
Sorry for my lack of knowledge,
should i include 
```
    entrada:
      - rtsp://home:xxxxxxx@192.168.1.73:554/h265Preview_01_main
      - "ffmpeg:back#video=h264#hardare=¿what?"
```

Thank you

**Reply by NickM-27** [reply]
`"ffmpeg:back"` is incorrect, you do not have a stream called back so it is referencing nothing. you would want it to be

```
    entrada:
      - "ffmpeg:rtsp://home:xxxxxxx@192.168.1.73:554/h265Preview_01_main#video=h264#audio=copy#hardware"
```

**Comment by dellorianes** [comment]
OK, I got to setup it. Know, I think I have a problem with ffmpeg transcoding.

At night, when the signal is black and white y transcodes but at day, in color signal, I get the following erros in logs:

````
2023-12-07 17:08:22.942430204  [2023-12-07 17:08:22] frigate.video                  ERROR   : entrada: Unable to read frames from ffmpeg process.
2023-12-07 17:08:22.942543090  [2023-12-07 17:08:22] frigate.video                  ERROR   : entrada: ffmpeg process is not running. exiting capture thread...
2023-12-07 17:08:37.782697584  [2023-12-07 17:08:37] watchdog.entrada               ERROR   : Ffmpeg process crashed unexpectedly for entrada.
2023-12-07 17:08:37.782810966  [2023-12-07 17:08:37] watchdog.entrada               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-12-07 17:08:37.782912351  [2023-12-07 17:08:37] ffmpeg.entrada.detect          ERROR   : [rtsp @ 0x557d53a07d40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2023-12-07 17:08:37.782989525  [2023-12-07 17:08:37] ffmpeg.entrada.detect          ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2023-12-07 17:08:37.783059191  [2023-12-07 17:08:37] ffmpeg.entrada.detect          ERROR   : Output file #0 does not contain any stream
2023-12-07 17:08:37.792270666  [2023-12-07 17:08:37] ffmpeg.entrada.record          ERROR   : rtsp://127.0.0.1:8554/entrada?video=copy: Invalid data found when processing input
2023-12-07 17:08:37.792332673  [2023-12-07 17:08:37] watchdog.entrada               INFO    : Terminating the existing ffmpeg process...
2023-12-07 17:08:37.792444289  [2023-12-07 17:08:37] watchdog.entrada               INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-07 17:08:47.800574751  [2023-12-07 17:08:47] ffmpeg.entrada.record          ERROR   : rtsp://127.0.0.1:8554/entrada?video=copy: Invalid data found when processing input
2023-12-07 17:08:47.800653473  [2023-12-07 17:08:47] watchdog.entrada               INFO    : Terminating the existing ffmpeg process...
2023-12-07 17:08:47.800739546  [2023-12-07 17:08:47] watchdog.entrada               INFO    : Waiting for ffmpeg to exit gracefully...
````

**Reply by NickM-27** [reply]
need to see go2rtc logs but sounds like a camera issue where it is sending bad data

**Comment by jubjubrsx** [comment]
might not be ghettoriffic but...

```
cameras:

 Driveway: # <------ Name the camera
    ffmpeg:
      output_args:
record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -b:v 4M -r 5 -vaapi_device /dev/dri/renderD128
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
```

^^^ this was a snippet from my config that would re-encode the stream from the input h265 to h.264 so I can view it in homeassistant...just modify it for your setup (last 2 arguements in the record section?)

but I found it ate up my gpu/cpu quite a bit for 10cams @ 4k..... but I do re-encode the low def 24/7 stream and that doesnt seem to put a huge load on the gpu/cpu.
