### DISCUSSION TITLE
Frigate + Home Assistant Automations (recording motion + recording clips on intervals)

### DISCUSSION THREAD

**Discussion by hpoon** [blakeblackshear/frigate#8782] [Ask A Question] [answered]
Right now I've got a few cameras configured on Frigate and is working quite well recording motion events.  I would like to expand this by recording additional clips of say 1 minute each every 15 minutes (or even just a snapshot would suffice).  My understanding is that this is not available under Frigate on its own (please correct me if I'm wrong), and that this potentially can be done via the Frigate integration in Home Assistant (which I also have set up).

My guess is the following approach:
Use an automation that runs every 15 mins, turn on recording for each camera, wait 1 minute, and then turn off recording

But there are some unknowns that I am not sure how to reconcile
- When I use the automation of "Turn on recording" wthin HA, what recording settings are used - is this considered a 24/7 recording or do they respect the settings in Frigate's config.yml? My current recording config is like this:
```
record:
  enabled: True
  expire_interval: 60
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: motion
```
- If this recording is enabled during an existing motion detection recording event, will these clip merge into 1 big clip?
