### DISCUSSION TITLE
Logging Birdseye RTSP Access / connects (ie vlc client connects to -> frigate birdseye) ?

### DISCUSSION THREAD

**Discussion by bob454522** [blakeblackshear/frigate#8791] [Ask A Question] [answered]
is there any way to enable logging of when a client connects to bird's eye via RTSP?

I have tried settings:
```
logger:
  default: debug
```
and then Searched through the logs but could not find any mentions of when a client connects (in my case i'm using VLC from a different computer to connect to the bird's eye stream)

ie maybe is there a option like:

````
logger:
  ..
    logs:
     frigate.birdseye: debug
````

thanks

**Comment by NickM-27** [comment]
go2rtc is what orchestrates the rtsp viewing so you'd need to enable and view rtsp logs there

**Reply by bob454522** [reply]
Thanks!  this is how i was able to get this logging (ie the client connections to birdseye)  
Updated solution:
to get logging of RTSP connects INTO frigate Birdseye,  you need to increase the log level of go2rtc ,  like this (added to your frigate config file):

```
go2rtc:
  log:
    format: text
    level: info
    rtsp: trace
```
(nb- i tried other levels including debug,  but trace is the only level that gives client connection info, so it may be higher than most want logged,  in my case all goes -> splunk)

thanks to NickM  for help on this!

~~edit go2rtc config inside of frigate via:~~
~~http :// your-frigate-ip:5000/live/webrtc/editor.html~~

~~then modify the log level...~~

**Reply by NickM-27** [reply]
there is no reason to update that, you can simply edit the go2rtc config in frigate itself like the docs show

**Reply by bob454522** [reply, marked as answer]
ah,  i see-  very cool! thanks for that-  so it looks like you only have to add this to your frigate config (confirmed working on my end):

```
go2rtc:
  log:
    format: text
    level: info
    rtsp: trace

```
