### DISCUSSION TITLE
Version problem...port problem...Docker

### DISCUSSION THREAD

**Discussion by matteopizzoli** [blakeblackshear/frigate#881] [Ask A Question] [answered]
Hi,
i use frigate like an add on on on home assistant on a VM hosted by virtualbox on unbuntu...everithing work more than fine!...but..
i've bought a minipcie coral device and i need to install with docker
i'm running docker compose 
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 
i've try to install with thin config:
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: blakeblackshear/frigate:stable-amd64
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /home/server/frigate/config/config.yml:/config/config.yml:ro
      - /home/server/frigate/clips:/media/frigate   
      - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
        target: /cache
        tmpfs:
          size: 100000000
    ports:
      - '5000:5000'
      - '1938:1938'
    environment:
      FRIGATE_RTSP_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m
```

**and get this error:**
```
Attaching to frigate
frigate    |  * Starting nginx nginx
frigate    |    ...done.
frigate    | Error parsing config: extra keys not allowed @ data['web_port']
```

**i can't understand where is the problem with the ports!!**

thank you
