### DISCUSSION TITLE
Dynamically change mask

### DISCUSSION THREAD

**Discussion by MikEarpp** [blakeblackshear/frigate#885] [Ideas]
The user interface is really great.
Well done and thank you to everyone involved in the development.

There is one feature that I miss a lot and I'm not the only one I think. 
I haven't seen a discussion about it but maybe the idea is already growing in someone's head?

It is not only useful for the PTZ camera.

For example, the fixed camera which films the entrance to my property is slightly plunging. It allows me to see over the gate when it is closed.
So I have two masks:
- one when the gate is open (this films the interior and exterior).
- one when the gate is closed (it only films the outside).

Currently I am making the modifications with my hands in the config file. I comment out a mask and restart Frigate.

I could also have multiple camera with the same url. Each with its mask.
Then activate / activate a particular camera via the user interface.

But in any case it's really not practical.

Visually it could look like:
![Frigate0](https://user-images.githubusercontent.com/72660689/110235735-f2e2b180-7f31-11eb-856a-9f3922d44a52.png)
```
  cam_name:
    motion:
      mask:
        - x,y,x,y,x,y,x,y,x,y,x,y
        - x,y,x,y,x,y,x,y,x,y,x,y,x,y,x,y

  ptz_cam:
    motion:
      mask:
        - x,y,x,y,x,y,x,y,x,y,x,y,x,y,x,y,/opt/frigate/scripts/moveto.sh ptz_cam position_1
        - x,y,x,y,x,y,x,y,x,y,x,y,/opt/frigate/scripts/moveto.sh ptz_cam position_4
```
Or better
![Frigate2](https://user-images.githubusercontent.com/72660689/110235764-1c9bd880-7f32-11eb-9cbe-4bc8f1dc0c5e.png)
```
  cam_name:
    motion:
      mask:
        - Closed gate,x,y,x,y,x,y,x,y,x,y,x,y
        - Opened gate,x,y,x,y,x,y,x,y,x,y,x,y,x,y,x,y

  ptz_cam:
    motion:
      mask:
        - Mask name 1,x,y,x,y,x,y,x,y,x,y,x,y,x,y,x,y,/opt/frigate/scripts/moveto.sh ptz_cam position_1
        - Mask name 2,x,y,x,y,x,y,x,y,x,y,x,y,/opt/frigate/scripts/moveto.sh ptz_cam position_4
```
I use Frigate everyday, thank you @blakeblackshear
