### DISCUSSION TITLE
Record a camera non-stop, without consideration for events/movement

### DISCUSSION THREAD

**Discussion by AnnoyingTechnology** [blakeblackshear/frigate#8901] [General]
Hello,

Is there a way to make Frigate records non-stop for a specific camera ?

I tried the following
```
    record:
      enabled: True
      expire_interval: 30
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
```

But in the Recordings tab all I see is events and in the storage folder It appears to still only record events.

I don't trust the motion detection for fast moving objects. 
I had the case of a car that damaged stuff but drove by too quickly to trigger the motion detection (on Shinobi at the time). Permanent recording is a safety net in such situations.
