### DISCUSSION TITLE
Frigate compatible PTZ cameras for auto-tracking

### DISCUSSION THREAD

**Discussion by Trakkasure** [blakeblackshear/frigate#8945] [Ask A Question] [answered]
I've bought 3 very nice PTZ outdoor cameras (with good optical zoom and night vision) but none of them support the relative FOV that is required.
In order to not spend more money on cameras that do not support this feature, in addition to wanting higher quality video and optical zoom, is there a list of cameras that support the required features for auto-tracking?

**Comment by NickM-27** [comment, marked as answer]
https://deploy-preview-6262--frigate-docs.netlify.app/configuration/cameras#onvif-ptz-camera-recommendations

**Reply by Coldknife2** [reply]
https://frigate-docs.netlify.app/configuration/cameras/#onvif-ptz-camera-recommendations

**Comment by Trakkasure** [comment]
I know about that (your answer is correct) but almost all cameras in that list are not supported.
I'm looking for additional feedback here from users who have gotten their camera tracking working with cameras not on that list.

**Comment by psCLE** [comment]
I just purchased one of these DH-SD22404DB-GNY from a Chinese seller on ebay. The camera works great with Frigate auto tracking and the camera arrived 35 days ahead of schedule, well packed and flawless, the return address was Los Angeles. According to Duhua website the model DH-SD22404DB us coming to the US soon. I gambled on it because it is a new model but since the older models work I assumed this one did. And I was impatient and want to see for myself how it worked.

**Reply by psCLE** [reply]
Not going to share results because at the moment because it is sitting on a cat tree through a screen window with the plastic on the lens. I have it tracking people and even through the window screen and plastic wrap, my Coral PCI detects and Frigate tracks and zooms the target.

**Reply by Trakkasure** [reply]
I have 2 Dahua cameras and both do not support relative fov for frigate auto-tracking.
I will  check that one out.

**Reply by Trakkasure** [reply]
Correction, They are sunbatech. Very nice video quality. I wouldn't buy them again for me needs.

**Reply by chuacher** [reply]
is it possible to publish your frigate config of your DH-SD22404DB-GNY camera.
I also have a DH-SD22404DB-GNY.
thanks

**Reply by psCLE** [reply]
> is it possible to publish your frigate config of your DH-SD22404DB-GNY camera. I also have a DH-SD22404DB-GNY. thanks

This is the basic config for the DH-SD22404DB-GNY, sorry this is so late.

```
  11_Front_PTZ:
    best_image_timeout: 180
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.27:554/cam/realmonitor?channel=1&subtype=1 # <- detection
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.88.27:554/cam/realmonitor?channel=1&subtype=0  # <- full resolution
          roles:
            - record
    onvif:
      host: 192.168.88.27
      port: 80
      user: admin
      password: PASSWORD
      autotracking:
        enabled: true
    motion:
      threshold: 32
      contour_area: 18
      improve_contrast: 'true'
```

**Reply by dogger27** [reply]
Awesome, thanks! I did the exact same as you... gambled on this camera purchase on ebay.  Great price for it's feature set.  Can't wait to receive it.

**Comment by Trakkasure** [comment]
Anyone tried and Annke C800 for auto-tracking?

**Comment by ehn** [comment]
Is there any chance that Frigate might support autotracking without relative FOV in the future?

**Reply by NickM-27** [reply]
it's a very difficult proposition because without relative FOV movement, many parameters will need to be tuned to the camera specifically which will require a full manual user setup for each camera if it is possible at all.

**Reply by Trakkasure** [reply]
Is there any information that is required that would not be available from the ONVIF media profile, other than the lens type?
Also, could automated calibration/configuration be done by having a  pattern printed on paper and walked around the field of view? Or placed up close?

**Reply by Trakkasure** [reply]
A poor-mans tracker (no relative FOV) could be something like the system attempting to move the camera plus or minus at a high or low speed, calibrated ahead of time, in the hopes that it could keep up with the target.
There are video applications that can map text on a wall and track placement while the camera is moving...
I'm no expert, and probably am way off, but it seems it could be possible given the abundance of real-time video processing apps that, when capabilities combined, could lend a hand at a solution.

**Reply by hawkeye217** [reply]
This would be a very difficult task to get right for the variety of cameras available today. Motor speed, latency, tracking model, etc. would make it extremely problematic.

With that said, some improvements are in the works for future versions to be able to support more cameras.

**Comment by anktababa** [comment]
Hello, 
I didn't wanted to created a thread and i found this one.
My question is exactly, i discovered frigate and using it for some weeks with my basic low cost camera (dafang, foscam c1)
I received my Coral and now i would to buy "good" camera cameras, after reading the doc (very great btw) i understand that dahua, hikvision/armcrest are very good. Dahua seems to support almost everything needed on ONVIF (RelativeMove) which is needed for PTZ Tracking. 

My question :
Do you have some camera that you are using  that you would recommend ? Focusing on dahua as i want something that is working easy and working out of the box properly but if you have other suggestions that are working great always open.
Thank you

**Reply by NickM-27** [reply]
the recommendation for a ptz camera can vary greatly depending on your intended usecase (general spotter cam, license plate reading, far distance tracking, etc.)

**Reply by anktababa** [reply]
Yes you are right, I would say a general outdoor camera that can be use to detect things that are entering a zone and follow it, no need for a big zoom, just a good image quality (coming from a low cost camera the step is easy lol)
License plate would be amazing but too complicated for a home usage I think
Thank you for your answer

**Reply by NickM-27** [reply]
I believe this is one of the smaller ones https://www.bhphotovideo.com/c/product/1808627-REG/dahua_technology_lite_series_1a404dbnr_4mp.html/?ap=y&ap=y&smp=y&smp=y&smpm=ba_f2_lar&lsft=BI%3A514&gad_source=1&gclid=EAIaIQobChMIifL5k5ekhQMV5tjCBB2PSAqWEAQYAiABEgIasfD_BwE

**Reply by dogger27** [reply]
I have heard that the "lite" series are the only Dahua cameras that may likely NOT support frigate autotracking.  Check out this one instead:  Dahua SD22404DB-GNY

**Comment by joelegg** [comment]
I'm thinking of getting a new one as I've had my hikvision ptz for like 4 years. and i dont think it works right with frigate anway 

I'm after one that woudl zoom in well and have the best night vision. 

Looks like these are pretty good; https://www.dahuasecurity.com/products/All-Products/PTZ-Cameras/WizSense-Series

i assume these would go ok with frigate as they are duhua. 

anyone tried any of these models?  the wizsense series? 

thanks

**Comment by joelegg** [comment]
I'm looking at this one now https://www.securitywholesalers.com.au/product/dahua-dh-sd6c3425xb-hnr-a-pv1-4mp-tioc-ip-25x-ptz-camera-ir-150m/ 

it says ONVIF (Profile S&G&T) so can I be pretty confident this would work with frigate @NickM-27 ? thank you

**Reply by dsokoloski** [reply]
I've tried many cameras that support "Profile S & G & T".  But only one of them supported Pan/Tilt Translation Space in FOV.  Unfortunately the only way to know if a camera supports this translation space is if someone with experience tells you it does, or if you take a chance, buy and try it yourself.

Section A. 3.2 of the ONVIF PTZ Specification describes the requirement.  Without this, Frigate can not support auto-tracking.
https://www.onvif.org/specs/srv/ptz/ONVIF-PTZ-Service-Spec-v1612.pdf

To reduce the guess work, more Frigate users who have a camera where auto-tracking is supported need to contribute to the recommended cameras list on this page (PTZ Controls, Autotracking):

https://github.com/blakeblackshear/frigate/blob/dev/docs/docs/configuration/cameras.md

**Reply by hawkeye217** [reply]
👆🏻
This is the correct answer. As the author of the autotracking code in Frigate, I've had users ask me often if a camera is supported or not. We need as much community help on this as possible! If your camera works with Frigate's autotracking and isn't already listed in the documentation, please either make a PR for the docs or comment here so I can add it to the docs.

**Reply by kronenpj** [reply]
> 👆🏻 This is the correct answer. As the author of the autotracking code in Frigate, I've had users ask me often if a camera is supported or not. We need as much community help on this as possible! If your camera works with Frigate's autotracking and isn't already listed in the documentation, please either make a PR for the docs or comment here so I can add it to the docs.

@hawkeye217 I have a litokam LF-P1t_Pro (https://www.amazon.com/dp/B0CHFHRQWK?ref=ppx_yo2ov_dt_b_fed_asin_title) that supports ONVIF, but not relative PTZ. It has two channels with different size video, both have audio. here's an excerpt from my config:
```
cameras:
  litokam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.40:5543/live/channel0
          roles:
            - record
        - path: rtsp://192.168.0.40:5543/live/channel1
          roles:
            - audio
            - detect
```
