### DISCUSSION TITLE
24/7 Recording config not working

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#8946] [Ask A Question] [answered]
Hey,

Part of my config contains the following:

```
  room_1:
    ui:
      order: 4
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/room_1
          roles:
            - detect
            - record
    objects:
      track:
          - person
          - cat
    zones:
      zone_0:
        coordinates: 0,720,0,432,209,351,1178,618,1132,720
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 15
      stationary:
        interval: 0
        threshold: 50
    record: 
      enabled: True
      events:
        #required_zones:
        #  - zone_0
        retain:
          default: 14
          mode: all
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      enabled: True
      # Optional: save a clean PNG copy of the snapshot image (default: shown below)
      clean_copy: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones:
        - zone_0
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
```

I was expecting this setup to mean it is recording 24/7 but also making events of persons/cats. However it seems to only record persons/cats and I am unable to see recordings in between. Could you highlight the error I've made for this to occur. My understanding was "mode: all" should equal 24/7 recording.

Many Thanks

**Comment by NickM-27** [comment]
The preview docs hopefully make this more clear https://deploy-preview-6262--frigate-docs.netlify.app/configuration/record

**Reply by Lockie85** [reply]
Humm not sure I'm seeing what I want to achieve. Or Im missing it.

I want to record 24/7 so I can check things that aren't picked up but still of interested. But I also want the know where in my recordings a person or cat has been detected.

**Reply by NickM-27** [reply]
Yes, so you enable 24/7 recording like the docs show

**Reply by Lockie85** [reply, marked as answer]
I understand my issue now. I was defining the length for events but not the recording itself.

So I WAS doing this:
```
    record: 
      enabled: True
      events:
        retain:
          default: 14
          mode: all
```
But I NEEDED this:
```
    record: 
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 14
          mode: all
```
