### DISCUSSION TITLE
Records are not deleted after a day

### DISCUSSION THREAD

**Discussion by Georgy-pioneer** [blakeblackshear/frigate#8952] [Ask A Question]
Hello everyone, I recently started installing cameras and got acquainted with software such as frigate. After reading the documentation, I wrote my config, taking into account the test server. The server runs on Truenas.
The essence of the problem: I set 1 day in the settings to save records. But in the end, we came across the fact that frigate does not comply with these settings. As a result, the application crashes, because all the memory on the server is clogged.
Version:  0.12.1_1.1.4

This is my config:
mqtt:
  enabled: false

```
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
ffmpeg:
  hwaccel_args: preset-nvidia-h264

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 1
    mode: all
  

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://######:#########/rtsp
          roles:
          
          - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 #  2560
      height: 1440 # 1440
      fps: 25  
  camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://######:#########/rtsp
          roles:
          - detect
          - record
    detect:
      enabled: True # 
      width: 1920 # 
      height: 1080
      fps: 25
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 1
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - cat
        required_zones: []
        retain:
          default: 1
          mode: active_objects
          # Optional: Per object retention days
          objects:
            person: 15
  camera_3:
    ffmpeg:
      inputs:
        - path: rtsp://######:#########/rtsp
          roles:
          
          - record
    detect:
      enabled: True # 
      width: 1920 # 
```
