### DISCUSSION TITLE
[Frigate 0.13 beta6] Why sometimes (most of time) I get: No frames have been received, check error logs

### DISCUSSION THREAD

**Discussion by rodrigoratan** [blakeblackshear/frigate#8956] [Ask A Question]
![image](https://github.com/blakeblackshear/frigate/assets/964066/6026e68d-c67a-44b6-a08f-d03c9974626b)

When I use the Cameras page I almost always get a message in all of my cameras saying "No frames have been received, check error logs"... and sometimes it will show recent snapshots.. If I click in any of the cameras, it all works (in MSE, WebRTC or MSJPG) and in the Debug view it also have the same issues (no frames have been received) and sometimes it works... 

The only error(s) I see in the logs are like this:
2023-12-13 22:22:20.150317187  [2023-12-13 22:22:20] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for calcada-gol. Keeping the 6 most recent segments out of 7 and discarding the rest...
2023-12-13 22:22:20.150762297  [2023-12-13 22:22:20] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for calcada-visita. Keeping the 6 most recent segments out of 7 and discarding the rest...
2023-12-13 22:22:20.150990802  [2023-12-13 22:22:20] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for cozinha. Keeping the 6 most recent segments out of 7 and discarding the rest...
2023-12-13 22:22:20.151384710  [2023-12-13 22:22:20] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for garagem-visita. Keeping the 6 most recent segments out of 7 and discarding the rest...

(and the timestamp is also wrong, by the way)

**Comment by NickM-27** [comment]
the reason for this error is most likely that your device is unable to keep up with the decoding frames load. Seeing the config and full copy of the logs would be helpful

**Comment by rodrigoratan** [comment]
docker compose:

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta6-tensorrt
    deploy:    
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    shm_size: "462mb" # update for your cameras based on calculation above

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../frigate_config:/config:rw
      - ../frigate_data/media:/media/frigate:rw
      - ../frigate_data/db:/db:rw
      - ../frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    ports:
      - "5001:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

**Comment by rodrigoratan** [comment]


**Reply by NickM-27** [reply]
need to see the entire config

**Comment by rodrigoratan** [comment]
Logs:
[frigate_log_2023-12-13.txt](https://github.com/blakeblackshear/frigate/files/13666441/frigate_log_2023-12-13.txt)

**Reply by NickM-27** [reply]
okay, the reason this occurs is because the connection to deepstack is timing out. You probably need to increase the timeout there

**Reply by rodrigoratan** [reply]
hmmm most of time deepstack will return in ~50ms
12:18:27:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...186716) took 45ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...479198) took 46ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...4b27b9) took 56ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...23a796) took 43ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...6efeb2) took 49ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...085992) took 52ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...0b29b3) took 45ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...2e9af5) took 48ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...599584) took 46ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...1386e3) took 43ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...46f49b) took 44ms
12:18:28:Object Detection (YOLOv5 6.2): Rec'd request for Object Detection (YOLOv5 6.2) command 'detect' (...215eb0) took 49ms

**Comment by rodrigoratan** [comment]
Full Config:

```
mqtt:
  enabled: False

logger:
  default: info

detectors:
  deepstack:
    api_url: http://192.168.100.8:32168/v1/vision/detection
    type: deepstack
    api_timeout: 10 # seconds


snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: True
  required_zones: []
  retain:
    default: 31

record:
  enabled: True
  retain:
    days: 14
    mode: motion
  events:
    retain:
      default: 31
      mode: active_objects

audio:
  enabled: False
  max_not_heard: 30
  min_volume: 350
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
  filters:
    # Label that matches label in listen config.
    speech:
      threshold: 0.8

birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  quality: 10

go2rtc:
  webrtc:
    candidates:
      - 192.168.100.8:8555
      - stun:8555
  streams:

    calcada-gol:
    - rtsp://admin:password@192.168.100.65:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    calcada-gol_sub:
    - rtsp://admin:password@192.168.100.65:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    
    calcada-visita:
    - rtsp://admin:password5@192.168.100.88:554/live0_0.sdp
    calcada-visita_sub:
    - rtsp://admin:password@192.168.100.88:554/live0_1.sdp

    
    garagem-gol:
    - rtsp://admin:password@192.168.100.64:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    garagem-gol_sub:
    - rtsp://admin:password@192.168.100.64:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    
    garagem-visita:
    - rtsp://admin:password@192.168.100.158:554/stream1
    
    garagem-visita_sub:
    - rtsp://admin:password@192.168.100.158:554/stream0


    sala-de-tv:
    - rtsp://admin:password@192.168.100.63:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    sala-de-tv_sub:
    - rtsp://admin:password@192.168.100.63:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif

    sala-de-jantar:
    - rtsp://admin:password@192.168.100.61:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    sala-de-jantar_sub:
    - rtsp://admin:password@192.168.100.61:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif

    cozinha:
    - rtsp://admin:password@192.168.100.60:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    cozinha_sub:
    - rtsp://admin:password@192.168.100.60:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif


    corredor-central:
    - rtsp://admin:password@192.168.100.33:554/?channel=1&stream=0.sdp
    corredor-central_sub:
    - rtsp://admin:password@192.168.100.33:554/?channel=1&stream=1.sdp
    
    escritorio-rodrigo:
    - rtsp://admin:password@192.168.100.80:554/?channel=1&stream=0.sdp
    escritorio-rodrigo_sub:
    - rtsp://admin:password@192.168.100.80:554/?channel=1&stream=1.sdp
    
    escritorio-r2:
    - rtsp://admin:password@192.168.100.84:554/0/video0
    escritorio-r2_sub:
    - rtsp://admin:password@192.168.100.84:554/0/video1

    terraco:
    - rtsp://admin:password@192.168.100.162:554/11
    terraco_sub:
    - rtsp://admin:password@192.168.100.162:554/11

cameras:
  calcada-gol:
    birdseye:
      order: 1
      mode: objects

    ui:
      order: 1
      dashboard: True

    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/calcada-gol
        roles:
        - record
        
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/calcada-gol_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - car
        - horse
        - motocycle
        - bicycle
        - skate
        - skateboard
        - bike
        - motorbike
        - truck
        - bus
        - minibus
        - school bus
        - aircraft
        - helicopter
        - garbage truck
        - tractor
        - police van
        - ambulance
        - sports car
        - balloon
        - fire
        - gun
        - firearm
        - pistol
        - rifle
        - revolver
        - knife
        - backpack
        - suitcase
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - adult
        - kid
        - female
        - male
        - dog
        - cat
        - bird
        - mouse
        - snake
        - spider

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

  calcada-visita:
    birdseye:
      order: 2
      mode: objects

    ui:
      order: 2
      dashboard: True

    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/calcada-visita
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/calcada-visita_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - car
        - horse
        - motocycle
        - bicycle
        - skate
        - skateboard
        - bike
        - motorbike
        - truck
        - bus
        - minibus
        - school bus
        - aircraft
        - helicopter
        - garbage truck
        - tractor
        - police van
        - ambulance
        - sports car
        - balloon
        - fire
        - gun
        - firearm
        - pistol
        - rifle
        - revolver
        - knife
        - backpack
        - suitcase
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - adult
        - kid
        - female
        - male
        - dog
        - cat
        - bird
        - mouse
        - snake
        - spider

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

  garagem-gol:
    birdseye:
      order: 3
      mode: objects

    ui:
      order: 3
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/garagem-gol
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/garagem-gol_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - car
        - vehicle
        - horse
        - motocycle
        - bicycle
        - skate
        - skateboard
        - bike
        - motorbike
        - truck
        - bus
        - minibus
        - school bus
        - aircraft
        - helicopter
        - garbage truck
        - tractor
        - police van
        - ambulance
        - sports car
        - balloon
        - fire
        - gun
        - firearm
        - pistol
        - rifle
        - revolver
        - knife
        - backpack
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - adult
        - kid
        - female
        - male
        - dog
        - cat
        - bird
        - mouse
        - snake
        - spider

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

  garagem-visita:
    birdseye:
      order: 4
      mode: objects

    ui:
      order: 4
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/garagem-visita
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/garagem-visita_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - car
        - horse
        - motocycle
        - bicycle
        - skate
        - skateboard
        - bike
        - motorbike
        - truck
        - bus
        - minibus
        - school bus
        - aircraft
        - helicopter
        - garbage truck
        - tractor
        - police van
        - ambulance
        - sports car
        - balloon
        - fire
        - gun
        - firearm
        - pistol
        - rifle
        - revolver
        - knife
        - backpack
        - suitcase
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - adult
        - kid
        - female
        - male
        - dog
        - cat
        - bird
        - mouse
        - snake
        - spider

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14


  cozinha:
    birdseye:
      order: 5
      mode: motion

    ui:
      order: 5
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/cozinha
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/cozinha_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

  sala-de-tv:
    birdseye:
      order: 6
      mode: objects

    ui:
      order: 6
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/sala-de-tv
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/sala-de-tv_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

  
  sala-de-jantar:
    birdseye:
      order: 7
      mode: objects

    ui:
      order: 7
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/sala-de-jantar
        roles:
        - record
        
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/sala-de-jantar_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14


  corredor-central:
    birdseye:
      order: 8
      mode: objects

    ui:
      order: 8
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/corredor-central
        roles:
        - record
        
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/corredor-central_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264

    detect:
      width: 1280
      height: 720
      fps: 5

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14


  escritorio-r2:
    birdseye:
      order: 9
      mode: objects

    ui:      
      order: 9
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/escritorio-r2
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/escritorio-r2_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    
    detect:
      width: 1280
      height: 720
      fps: 5
    
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects

    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

  escritorio-rodrigo:
    birdseye:
      order: 10
      mode: objects

    ui:
      order: 10
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/escritorio-rodrigo
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/escritorio-rodrigo_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    
    detect:
      width: 1280
      height: 720
      fps: 5
    
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects
    
    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14


  terraco:
    birdseye:
      order: 11
      mode: objects

    ui:
      dashboard: True
      
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream # rtsp-restream-low-latency
        path: rtsp://127.0.0.1:8554/terraco
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/terraco_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
      hwaccel_args: preset-nvidia-h264
    
    detect:
      width: 1280
      height: 720
      fps: 5
    
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 31
          mode: active_objects
    
    objects:
      track:
        - mask
        - face mask
        - person
        - cell phone
        - remote
        - dog
        - cat
        - bird

    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 14

```
