### DISCUSSION TITLE
2 identical cam brands/models - 2 different stream qualities ???

### DISCUSSION THREAD

**Discussion by MadOtis** [blakeblackshear/frigate#8967] [General]
I'm new to Frigate, but have been able to thus far get things rolling smoothly thanks to the YT community.  I have 2 Amcrest IP5M-T1179EW-28MM cameras (currently while getting set up) and both work with Frigate seemingly fine.  However, using virtually identical configurations (with a few different zones/masks defined), for "detection" view, they are both displaying the expected reduced resolution streamd, however for "live" view, they are displaying both in Frigate and in HASS in different resolutions (backyard is displaying in "HD", but FrontDoor is displaying in "SD" but if looking at the direct camera IP's "LIVE" view, the front cam also displays in "HD", so I know the cam seems to be fine. I've pasted the relevant portions of the frigate config below, hopefully someone can point out where I've mucked something up.  I've compared the in-camera settings meticulously and both are configured identically with the exception of the IP addresses (I'm using static IPs on a VLan).

Config settings (I snipped out most for brevity):
```
go2rtc:
  streams:
    backyard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.190:554/cam/realmonitor?channel=1&subtype=0
    backyard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.190:554/cam/realmonitor?channel=1&subtype=1
    front_door:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.191:554/cam/realmonitor?channel=1&subtype=0
    front_door_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.0.1.191:554/cam/realmonitor?channel=1&subtype=1

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
<snip>
    best_image_timeout: 60
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_door
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
<snip>
    best_image_timeout: 60

```
Any ideas or suggestions on where to look?

Thanks in advance!
