### DISCUSSION TITLE
New to using Nvidia for detection

### DISCUSSION THREAD

**Discussion by lordratner** [blakeblackshear/frigate#8972] [Ask A Question]
Hi,
My setup: Proxmox Host, frigate in a Privileged LXC, GTX 1070Ti, Coral PCIe 2x TPU

I've been using the PCIe Coral for detection, but I wanted to try some of the yolo models to see if object detection in night-mode is better, because it's pretty bad on the TPU. 

When I follow the instructions I get an Error that no GPU was detected. I have the Nvidia drivers and container Runtime toolkit installed, and the frigate instance is able to use the GPU for stream encoding, so I think the LXC is set up correctly for using the GPU in docker. 

But when running the script tp generate the models, I get this error:

```
[...]
  return %030_convolutional, %037_convolutional
}
Checking ONNX model...
Saving ONNX file...
Done.
+ python3 onnx_to_tensorrt.py -m yolov4-tiny-288
Loading the ONNX file...
[12/15/2023-15:36:11] [TRT] [W] Unable to determine GPU memory usage
[12/15/2023-15:36:11] [TRT] [W] Unable to determine GPU memory usage
[12/15/2023-15:36:11] [TRT] [W] CUDA initialization failure with error: 100. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 214, in <module>
    main()
  File "onnx_to_tensorrt.py", line 202, in main
    engine = build_engine(
  File "onnx_to_tensorrt.py", line 112, in build_engine
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(*EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
TypeError: pybind11::init(): factory function returned nullptr
```

Earlier in the output I see this:

```
**ERROR: No supported GPU(s) detected to run this container**

Failed to detect NVIDIA driver version.

+ CUDA_HOME=/usr/local/cuda
+ LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
+ OUTPUT_FOLDER=/tensorrt_models
+ echo 'Generating the following TRT Models: yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416'
Generating the following TRT Models: yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416
```

What I can't tell is whether the GPU just isn't being passed to the docker container, or if the GTX1070ti is not supported. I'm running driver version 545.23.06

Another possibility is that I need to install the Cuda Toolkit on the LXC? I didn't see this anywhere in the instructions, but I'm very capable of misreading instructions. 

Any ideas? Here's my compose and config for reference

**Docker Compose:**
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "2048mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_1:/dev/apex_1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/frigate/config:/config
      - /mnt/nvr/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "pass"
```

**Frigate Config (doens't use tensor yet because I can't get the models generated)**
```
mqtt:
  host: 192.168.30.105
  port: 1883
  user: frigate
  password: tilapia45samurai

detectors:
  # coralusb:
  #   type: edgetpu
  #   device: usb
  coralpci1:
     type: edgetpu
     device: pci:0
  coralpci2:
     type: edgetpu
     device: pci:1

database:
  path: /media/frigate/frigate.db

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
#  logs:
#    frigate.event: debug

environment_vars:
  EXAMPLE_VAR: value

birdseye:
  enabled: True
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

detect:
  fps: 5
  enabled: True
  # stationary:
  #   interval: 50
  #   threshold: 50

go2rtc:
  streams:
    living_room:
      - rtsp://frigate:eatcheesedonuts@192.168.41.100:554//h264Preview_01_main # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:living_room#audio=opus" # <- copy of the stream which transcodes audio to opus
    living_room_sub:
      - rtsp://frigate:eatcheesedonuts@192.168.41.100:554//h264Preview_01_sub # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    nursery:
      - rtsp://frigate:eatcheesedonuts@192.168.41.102:554//h265Preview_01_main # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      # - "ffmpeg:nursery#audio=opus" # <- copy of the stream which transcodes audio to opus
    nursery_sub:
      - rtsp://frigate:eatcheesedonuts@192.168.41.102:554//h264Preview_01_sub # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg

    litter_box:
      - http://192.168.41.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=eatcheesedonuts # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:litter_box#audio=opus" # <- copy of the stream which transcodes audio to opus
    litter_box_sub:
      - http://192.168.41.101/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=eatcheesedonuts # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg

ffmpeg:
  hwaccel_args: preset-nvidia-h264

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
#    objects:
#      - cat
#    required_zones:
#    - feeder
    retain:
      default: 5
      mode: all

snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  crop: True
  retain:
    default: 7

# rtmp:
#   enabled: True

live:
  height: 720
  quality: 8

timestamp_style:
  position: "bl"
  format: "%Y/%m/%d %H:%M:%S"
  color:
    red: 252
    green: 111
    blue: 3
  thickness: 3

objects:
  track:
    - person
    - cat
  filters:
    cat:
      min_score: 0.5
      threshold: 0.7

cameras:
  living_room:
    ffmpeg:
      inputs:
        # - path: rtsp://127.0.0.1:8554/living_room_sub
        #   roles:
        #     - detect
        - path: rtsp://127.0.0.1:8554/living_room
          roles:
            - record
            - detect
    detect:
    #  width: 640 # <---- update for your camera's resolution
    #  height: 360 # <---- update for your camera's resolution
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 2287,177,2303,355,2133,328,2167,151
    zones:
      front_door:
        coordinates: 690,1068,1394,1064,1490,276,579,277
        objects:
          - person
    snapshots:
      required_zones:
        - front_door
    record:
      enabled: True
      events:
        objects:
          - person
        required_zones:
          - front_door
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True
      height: 500
      quality: 100
      #required_zones: []

  litter_box:
    ffmpeg:
      inputs:
#        - path: rtsp://127.0.0.1:8554/litter_box_sub
#          roles:
#            - detect
        - path: rtsp://127.0.0.1:8554/litter_box
          roles:
            - record
            - detect
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
#      width: 640 # <---- update for your camera's resolution
#      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - cat
    zones:
      entrance:
        coordinates: 2202,1747,2161,759,2036,556,2014,302,1963,134,1700,0,1287,127,1192,453,917,633,894,1753
        objects:
          - cat
      litter_room:
        coordinates: 0,0,2560,0,2560,1920,0,1920
#         coordinates: 1251,743,1234,596,1267,480,1354,384,1465,338,1591,334,1756,397,1849,460,1907,568,1931,691,1913,817,1872>
        objects:
          - cat
#          - person
    snapshots:
      required_zones:
        - entrance
    record:
      enabled: True
      events:
        objects:
          - cat
        required_zones:
          - entrance
          - litter_room
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 500
      quality: 100
      #required_zones: []

  nursery:
    ffmpeg:
      input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
#        - path: rtsp://frigate:eatcheesedonuts@192.168.40.141:554//h264Preview_01_sub
#          roles:
#            - detect
        - path: rtsp://127.0.0.1:8554/nursery
          # input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2304 # <---- update for your camera's resolution
      height: 1296 # <---- update for your camera's resolution

    objects:
      track:
        - person
        - cat
    zones:
      crib:
        coordinates: 541,1296,343,1063,773,641,1072,824,1101,905,760,1296
        objects:
         - person
         - cat
      changing_table:
        coordinates: 1543,469,1866,627,1655,1073,1237,874
        objects:
         - person
         - cat
      nursery_room:
        coordinates: 0,0,2304,0,2304,1296,0,1296
        objects:
          - cat
          - person
#    zones:
#      front_door:
#        coordinates: 690,1068,1394,1064,1490,276,579,277

#    snapshots:
#      required_zones:
#        - front_door
    record:
      enabled: True
      events:
        objects:
          - person
          - cat
        required_zones:
          - crib
          - changing_table
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True
      height: 500
      quality: 100
```
