### DISCUSSION TITLE
OS keeps crashing when using Frigate 0.12.1 on Asrock N100M

### DISCUSSION THREAD

**Discussion by bsacharski** [blakeblackshear/frigate#8993] [Ask A Question]
Hello. I'm having problems with running Frigate on Asrock N100M. Basically, after some time of running Frigate (sometimes it's 2 hours, sometimes it's 15 minutes), the OS hangs, with a purple/violet color flashing (in an epilepsy-triggering way) on a connected display. 

At first I've thought it was faulty RAM, but after running few passes of Memtest, it would seem that it's not the issue.
Then I've thought that it might be related to system overheating, but after stressing machine for few minutes with 100% load the OS was still on.

I'm thinking it might be related to either GPU processing or maybe something related to communication with Coral via USB (though my bet is on the integrated iGPU). 

Maybe someone has encountered this kind of issue and solved it? Or maybe it's configuration issue causing graphics to go crazy?

## Specs:

- OS: Ubuntu 23.10 (`kernel 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`)
- Motherboard: Asrock N100M
- CPU: Intel N100
- RAM: 1 stick of ADATA 16 GB something (was in QVL for that motherboard)
- PSU: Seasonic GX 650 (so more than enough)
- Storage: OS installed on m.2 SSD, video being saved on SATA HDD (mounted in `/nvr`)
- Frigate installation method: `docker compose`
- Docker version: `Docker version 24.0.7, build afdd53b`
- Frigate version: 0.12.1
- Detector: Coral USB TPU 

### `docker-compose.yml`

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.1
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - ./models/efficientdet_lite0_320_ptq_edgetpu.tflite:/edgetpu_model.tflite:ro
      - /nvr/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### `config.yml`

```yaml
mqtt:
  enabled: true
  host: mqttserver.localnetwork
  user: MQTT_USER
  password: MQTT_PASS
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    eastcam:
      - rtsp://LOGIN:PASS@eastcam.localnetwork:554/h264Preview_01_main
      - "ffmpeg:eastcam#audio=opus"
    westcam:
      - rtsp://LOGIN:PASS@westcam.localnetwork:554/h264Preview_01_main
      - "ffmpeg:westcam#audio=opus"
    garage:
      - rtsp://LOGIN:PASS@garage.localnetwork:554/h264Preview_01_main
      - "ffmpeg:garage#audio=opus"
    front:
      - rtsp://LOGIN:PASS@front.localnetwork:554/h264Preview_01_main
      - "ffmpeg:front#audio=opus"
    porch:
      - rtsp://LOGIN:PASS@porch.localnetwork:554/h264Preview_01_main
      - "ffmpeg:porch#audio=opus"
    doors:
      - rtsp://LOGIN:PASS@doors.localnetwork:554/h264Preview_01_main
      - "ffmpeg:doors#audio=opus"
    garden:
      - rtsp://LOGIN:PASS@garden.localnetwork:554/h264Preview_01_main
      - "ffmpeg:garden#audio=opus"
    garage_inside:
      - rtspx://console:7441/HASH1
    garage_inside_sl:
      - rtspx://console:7441/HASH2
    doorbell:
      - rtspx://console:7441/HASH3
    doorbell_sl:
      - rtspx://console:7441/HASH4
  webrtc:
    candidates:
      - MY_IP:8555
      - stun:8555

cameras:
  eastcam:
    ffmpeg:
      inputs:
        - path: http://eastcam.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/eastcam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 10
    motion:
      mask:
        - 896,512,896,340,683,370,282,400,0,376,0,512

  westcam:
    ffmpeg:
      inputs:
        - path: http://westcam.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/westcam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 10
    motion:
      mask:
        - 0,0,379,0,377,42,0,46
        - 896,0,896,42,787,41,789,0

  garage:
    ffmpeg:
      inputs:
        - path: http://garage.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 10
    birdseye:
      mode: continuous
    motion:
      mask:
        - 199,42,197,0,0,0,0,339,0,512,187,512,124,336
        - 382,0,380,38,0,41,0,0
        - 896,0,896,86,697,30,470,0
    zones:
      wejscie_do_garageu:
        coordinates: 209,39,255,344,539,330,703,512,195,512,125,363,164,171
      podjazd:
        coordinates: 278,512,896,512,896,332,758,218,556,333,255,347

  garage_inside:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_inside_sl?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/garage_inside?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    detect:
      width: 640
      height: 360
      fps: 24

  front:
    ffmpeg:
      inputs:
        - path: http://front.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 10
    birdseye:
      mode: continuous
    motion:
      mask:
        - 896,512,896,0,724,0,654,512
        - 352,34,403,0,162,0,0,0,0,81
        - 343,161,463,102,607,38,896,42,896,0,451,0,344,0,267,83,265,120,301,112,299,153
    zones:
      doors_frontowe:
        coordinates: 619,512,679,259,703,79,556,58,544,293,424,512
      podjazd:
        coordinates: 557,187,331,169,185,250,550,259

  porch:
    ffmpeg:
      inputs:
        - path: http://porch.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/porch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896
      height: 512
      fps: 10
    motion:
     mask:
      - 687,43,517,39,384,0,896,0,896,42,896,264
      - 0,0,0,512,194,512,146,394,191,0

  doors:
    ffmpeg:
      inputs:
        - path: http://doors.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/doors?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    zones:
      doors_frontowe:
        coordinates: 596,512,341,512,206,512,287,231,256,0,370,0,385,231,550,241
    motion:
      mask:
        - 0,0,242,0,202,40,0,271
        - 0,0,381,0,378,39,0,40
        - 896,0,896,39,810,37,806,0
    detect:
      width: 896
      height: 512
      fps: 10
  garden:
    ffmpeg:
      inputs:
        - path: http://garden.localnetwork/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=LOGIN&password=PASS
          input_args: preset-http-reolink
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask:
        - 896,512,896,0,627,0,642,52,732,31,773,23,784,246,742,512
        - 896,0,896,39,519,40,519,0
        - 180,46,423,0,0,0,0,119
    detect:
      width: 896
      height: 512
      fps: 10

  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sl?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
           - detect
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
    objects:
      track:
        - person
        - car
        - cat
        - dog
    detect:
      width: 480
      height: 360
      fps: 24

record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 30
    post_capture: 60
    retain:
      default: 7

snapshots:
  enabled: True
  bounding_box: True

birdseye:
  enabled: True
  mode: objects
  restream: True

objects:
  track:
    - person
    - car

rtmp:
  enabled: False

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  hwaccel_args: preset-vaapi
```

Note: Frigate works fine on my Dell Wyze 5070, so it doesn't seem like the issue is related directly to cams or the detector device (Wyze uses pretty much the same config file).
