### DISCUSSION TITLE
my front house camera detects only cars no person

### DISCUSSION THREAD

**Discussion by Zoiao81** [blakeblackshear/frigate#8994] [General]
Setup:
1.) Frigate on proxmox docker with HA Proxy Add on and Notification Integration Blueprint
2. ) 8 Cameras with one Google Coral TPU Stick
3.) 3 Camera over POE connect, 3 lan normal, 2 Wlan (2 cameras higher with 8mp show below)

Hello, I have the problem that my front house camera doesn't track people in the distance. I have set up two zones. One zone in front and one zone2 in distance. I did this so that when I was away, I would only be notified of person in the front zone. But it should also record everyone in the zones behind it, also in both zones.

Now I have the problem that it only detects cars, but not person in the distance zone2.

I have a Hikvision camera and have always used the secondary stream for detected with 640 x 480 stream and 5 fps. But I've now tried increasing it to 1280 x 720 and 6 fps, but the people are still not tracked. It's about 15 meters max to the rear zone and the camera hangs at about 2.40 meters. It is one Hikvison 4k 8MP AcuSense  DS-2CD2386G2.

If my yaml wrong?
Or need i a secondary google TPU? The TPU is only for the detect i know. I stream the Videos for this and a another cam with the max 3840 x 2160 and 25 fps, should I reduce it? But with detection that shouldn't play a role?

My Coral Inference Speed 33,78 ms, CPU 10,3% Memory 0,3%
Hardware acceleration has not been setup, GPU off

```
`  Strasse:
    ffmpeg:
      inputs:
        - path: rtsp://Frigatexxxxx
          roles:
            - detect
        - path: rtsp://Frigatexxx
          roles:
            - record
    rtmp:
      enabled: False
    detect:                                                        
      width: 1280
      height: 720
      fps: 6
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - cat
        - dog
        - car
        - truck
        - motorcycle
        - bicyle
        - truck
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: True
      events:
        required_zones:
          - zone_1front
          - zone_2distance
        retain:
          default: 14
          mode: motion

    ui:
      order: 8
    zones:
      zone_1front:
        coordinates: 0,720,1280,720,1280,397,893,123,0,236
        filters:
          person:
            min_area: 1200
            max_area: 50000
            min_score: 0.1
            threshold: 0.7
          cat:
            threshold: 0.8
          dog:
            threshold: 0.8

      zone_2distance:
        coordinates: 512,88,1023,143,1020,96,771,0,0,0,0,186
        filters:
          person:
            min_area: 5
            max_area: 5000000
            min_score: 0.1
            threshold: 0.4
          car:
            min_area: 1500 
            max_area: 100000
            min_score: 0.3
            threshold: 0.5
          truck:
            min_area: 1500
            max_area: 100000
            min_score: 0.5
            threshold: 0.7
          dog:
            min_area: 300
            max_area: 10000
            min_score: 0.3
            threshold: 0.7
          cat:
            min_area: 300
            max_area: 10000
            min_score: 0.3
            threshold: 0.7
          motorcycle:
            min_area: 2000
            max_area: 100000
            min_score: 0.3
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            min_score: 0.3
            threshold: 0.7

# Live view settings
live:
  height: 720
  quality: 8


birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 10
  mode: continuous

`
```

Thank you for any help and sorry for my bad english

**Comment by NickM-27** [comment]
I would suggest watching the debug view and seeing what happens. Also, in general if detection issues are happening it is recommended to remove the filters

**Comment by Zoiao81** [comment]
Thank you. Now i make the filters off and tested it with the debug funktion (mse) but the person do not track.

**Reply by Zoiao81** [reply]
![Screenshot_20231217_202611_Gallery](https://github.com/blakeblackshear/frigate/assets/115667910/ac487617-2447-4515-842f-965b8f97878f)

**Reply by NickM-27** [reply]
Is motion detected? This looks like quite low resolution quality

**Comment by Zoiao81** [comment]
Hello, yes its no motion detected.  Only the car but the person in the right on the picture is not detected.
I had at the camera and the yaml 1280 x 720, then i scale it higher and tested later.
Thank you

**Reply by NickM-27** [reply]
you'll need to increase motion detection sensitivity then

**Comment by Zoiao81** [comment]
Ok,  that means when i scale the resolution higher, i must set a Filter for person lower? Or what do you mean? At the moment i erease the filters for this camera in the yaml and i think i had the standart 0,7? Ah you mean more fps? I increase it from 6 to 15?

**Reply by NickM-27** [reply]
those are for object detection, I am referring to motion detection. need to see if the person is detected as motion first using the debug live view with motion boxes enabled

**Reply by NickM-27** [reply]
https://deploy-preview-6262--frigate-docs.netlify.app/configuration/motion_detection

**Reply by Zoiao81** [reply]
Ok thank you very much, i read it and tested.

**Reply by Zoiao81** [reply]
Hello, I tested it and adjusted the yaml as follows

```
` motion:
      threshold: 20
     contour_area: 20
     mask:
       - 1091,463,1113,473,1137,438,1107,409`
```
Now people in the distance are recognized, but there are a lot of false alarms. I added a motion mask to a flower, but a watering can is now also recognized as a person, etc.

Now I have to set the threshold
      contour_area: Increase  until I only recognize the people I want and have few false alarms?

Or do I have to record another command? Maybe filter people x%? Does it also come with Motion or Object?

and make more motion mask? or should I create a motion box? I'm thinking about the best way to proceed, I wanted to increase the contour_area first?

**Reply by NickM-27** [reply]
I'd suggest providing examples of the false positives you're seeing. 

Also please read https://deploy-preview-6262--frigate-docs.netlify.app/guides/false_positives

**Reply by Zoiao81** [reply]
Can you help me which I have to change the setting so that the small box nearby is not recognized as a human

**Comment by Zoiao81** [comment]
I read the article, but I didn't fully understand it.  I adjusted the yaml and attached a few wrong images.  I don't know which command I have to adapt to.  Sometimes it recognizes boxes that are too large as a person, see photo, and sometimes it recognizes small ones.  In addition, the dog is not recognized, see photo.
 Thanks for the help

![Screenshot_20231221_082107_Home Assistant](https://github.com/blakeblackshear/frigate/assets/115667910/62f5dbbd-26cb-4b39-a6d8-e3b9ba1b3d0c)
![Screenshot_20231221_113038_Home Assistant](https://github.com/blakeblackshear/frigate/assets/115667910/2c896293-7eda-4772-b3be-7fdb4f41cb76)
![Screenshot_20231221_082135_Home Assistant](https://github.com/blakeblackshear/frigate/assets/115667910/388a1417-9142-41c8-9f34-856f32468e90)
![Screenshot_20231221_082120_Home Assistant](https://github.com/blakeblackshear/frigate/assets/115667910/1d74f714-fe56-4867-b7ec-efb17cf717ac)
![Screenshot_20231221_063407_Home Assistant](https://github.com/blakeblackshear/frigate/assets/115667910/9bde9f53-cdcd-4203-9fd4-15cbadfc2dd2)

**Comment by Zoiao81** [comment]
Dog
![Screenshot_20231221_082232_Home Assistant](https://github.com/blakeblackshear/frigate/assets/115667910/a3aabc68-5675-477a-894c-8705c10fcf48)

**Comment by Zoiao81** [comment]
my new yaml, I commented out # min and max values, because i did not have correct recognition with this standart values
````
objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - cat
        - dog
        - car
        - truck
        - motorcycle
        - bicyle
        - truck
      filters:
        person:
          # min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
         #  max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
         # min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          # max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.2
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.6
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
        cat:
          threshold: 0.5
        dog:
          threshold: 0.5
```
    `

**Reply by NickM-27** [reply]
if you are having false positive problems, lowering the threshold to 0.6 causes part of that, I'd suggest the default 0.7

**Comment by Zoiao81** [comment]
Can you help me which I have to change the setting so that the small box nearby is not recognized as a human

**Reply by NickM-27** [reply]
```
objects:
      filters:
        person:
          min_area: 1000
```
