### DISCUSSION TITLE
Frigate Card - Hide Side Hamburger Button

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#9004] [Ask A Question] [answered]
Hey,

Sorry I've tried to find an option for this but can't. Within a Frigate Card I think they are called "Thumbnail Drawers", the little hamburger on the side which displays clips.

I want to turn it off but can't find the option to do so. Can anyone help highlight where that might be?

Many Thanks.

**Comment by Lockie85** [comment]
Adding an image of the button I'm referring to:
![image](https://github.com/blakeblackshear/frigate/assets/7091582/15d2d753-d3c5-4313-8716-276ffe83a8ec)

**Comment by Lockie85** [comment]
@NickM-27 sorry to @ you but I wondered if you might know where this option is if it is available?

Many Thanks.

**Reply by NickM-27** [reply]
just change the menu style

**Reply by Lockie85** [reply]
I tried all the options including "No Menu" and "Hidden Menu" but the hamburger icon/menu is still there.

**Reply by NickM-27** [reply]
this is my card yaml, I don't have that button

```yaml
type: custom:frigate-card
cameras:
  ...
live:
  lazy_unload: hidden
  auto_play: all
  auto_mute: all
  auto_unmute: never
  controls:
    title:
      mode: none
    thumbnails:
      mode: below
      media: snapshots
      show_details: false
    next_previous:
      style: none
  zoomable: false
  auto_pause: all
  transition_effect: none
  display:
    mode: grid
media_viewer:
  controls:
    title:
      mode: none
    next_previous:
      style: none
menu:
  style: outside
  position: bottom
  buttons:
    frigate:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    media_player:
      enabled: false
    microphone:
      enabled: true
    timeline:
      enabled: false
performance:
  profile: high
```

**Reply by Lockie85** [reply, marked as answer]
Got it, from a UI perspective it looks to be this option which disables it:
Live > Live Controls > Thumbnails > Thumbnails mode > No thumbnails

Code for this is:
```
live:
  controls:
    thumbnails:
      mode: none
```

Thanks for helping me.
