### DISCUSSION TITLE
[HW Accel]: NVIDIA GPU Not working

### DISCUSSION THREAD

**Discussion by antwal** [blakeblackshear/frigate#9028] [General]
I changed hardware to try to have a decoding and encoding that supports HEVC for h265 as the detail of the images is higher than h264, but it seems that the nvidia driver does not work correctly; I used the "preset-nvidia-h264" preset which will certainly need to be changed, but for the moment I'm interested in making decoding/encoding work via GPU:

**Error VA INFO:**
<img width="554" alt="Schermata 2023-12-19 alle 20 10 02" src="https://github.com/blakeblackshear/frigate/assets/410736/d2e6ea84-e585-46a5-a51c-bfb5707f5abc">

**Docker Container - Frigate (Debian 11):**
<img width="1022" alt="Schermata 2023-12-19 alle 20 10 42" src="https://github.com/blakeblackshear/frigate/assets/410736/6dfcae72-1f45-43c0-ab81-88a5f64e281d">
<img width="865" alt="Schermata 2023-12-19 alle 20 10 52" src="https://github.com/blakeblackshear/frigate/assets/410736/2bf5b069-0022-483a-a91e-51885365a0b4">

**Host (Debian 12):**
<img width="755" alt="Schermata 2023-12-19 alle 20 11 43" src="https://github.com/blakeblackshear/frigate/assets/410736/bd7faf63-bbd6-4450-973b-f9add8b52a5a">

To use VA-API (Video Acceleration API) for nvidia in Debian 12, you need to install the "[nvidia-vaapi-driver](https://debian.pkgs.org/12/debian-main-amd64/nvidia-vaapi-driver_0.0.8-1_amd64.deb.html)" package

**Frigate Config:**
```
#environment_vars:
#  LIBVA_DRIVER_NAME: i965

mqtt:
  host: mqtt
  user: frigate
  password: W2D6fdBoBIjLqTI8

detectors:
  coral_pci:
    type: edgetpu
    device: pci

birdseye:
  enabled: True
  mode: motion

ffmpeg:
  hwaccel_args: preset-nvidia-h264 # preset-vaapi

detect:
  enabled: True
  width: 640
  height: 480

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects

snapshots:
  enabled: True
  bounding_box: True
  timestamp: true

cameras:
  camera1:
    ffmpeg:
      inputs:
        # High Resolution Stream 2304x1296
        - path: rtsp://172.16.87.14/stream0
          input_args: preset-rtsp-restream
          roles:
            - record
#            - rtmp
        # Low Resolution Stream 640x480
        - path: rtsp://172.16.87.14/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - dog
        - cat
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.87.10/stream0
          input_args: preset-rtsp-restream
          roles:
            - record
#            - rtmp
        - path: rtsp://172.16.87.10/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.87.19/stream0
          input_args: preset-rtsp-restream
          roles:
            - record
#            - rtmp
        - path: rtsp://172.16.87.19/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - cat
        - dog
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.87.20/stream0
          input_args: preset-rtsp-restream
          roles:
            - record
#            - rtmp
        - path: rtsp://172.16.87.20/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - dog
  camera5:
    ffmpeg:
      inputs:
        - path: rtsp://172.16.87.21/stream0
          input_args: preset-rtsp-restream
          roles:
            - record
#            - rtmp
        - path: rtsp://172.16.87.21/stream1
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
```

**Docker Compose:**
```
version: "3.9"
services:
  frigate:
    networks:
      - bridgenet
    hostname: frigate
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
#            device_ids: ['0']
            count: 1
            capabilities: [gpu]
    shm_size: "364mb"
    devices:
      - /dev/apex_0:/dev/apex_0   # passes the PCIe Coral
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral
#      - /dev/dri/renderD128       # for intel hwaccel
#      - /dev/dri/card0            # for intel hwaccel
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/frigate/config.yml:/config/config.yml
      - /mnt/storage/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PLUS_API_KEY: ****


networks:
  bridgenet:
    name: container-net
    external: true
```
