### DISCUSSION TITLE
Frigate prevents HomeKit Secure Video from detecting events on Amcrest camera

### DISCUSSION THREAD

**Discussion by ClemTiger0408** [blakeblackshear/frigate#9107] [Ask A Question]
I am running Frigate to Home Assistant and then in parallel I am running Scrypted to HomeKit everything in separate docker containers. I have a Reolink doorbell and Amcrest floodlight. With this setup the Reolink doorbell is able to do detection in HK and Frigate no issue. With the Amcrest, if Frigate is running then HKSV can connect to a live view of the camera but it does not detect any motion or create recordings. If I set up the Amcrest in HKSV while Frigate is disabled then HKSV detects and records no issue. Its when Frigate starts up that it stops. Is there anything I can do to make them both detect and record?

Config is below. Note: the hashed out cameras were an attempt to use the rebroadcast RTSP from Scrypted but there was no difference between using the rebroadcast RTSP or the camera's direct RTSP stream.

```
go2rtc:
  streams:
    front_doorbell_cam:
      - "ffmpeg:http://xxx.xxx.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=bW2IdvmhcH2C#video=copy#audio=copy#audio=opus"
    #  - "ffmpeg:rtsp_cam#audio=opus"
    front_doorbell_cam_sub: 
      - "ffmpeg:http://xxx.xxx.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=bW2IdvmhcH2C"
    front_spotlight_cam:
      - "rtsp://xxx.xxx.xxx.xxx:46041/794550aa645cedbf" #/cam/realmonitor?channel=1&subtype=0"
    #  - "ffmpeg:rtsp_cam#audio=opus"
    front_spotlight_cam_sub: 
      - "rtsp://xxx.xxx.xxx.xxx:46041/a1ac46aec4f49027" #/cam/realmonitor?channel=1&subtype=1"
    spot_cam:
      - "rtsp://admin:<pass>@xxx.xxx.xxx.xxx554/cam/realmonitor?channel=1&subtype=0"
    spot_cam_sub:
      - "rtsp://admin:<pass>@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1&subtype=1"

cameras:
  front_doorbell:
    ffmpeg:
      #output_args:
      #  record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_cam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
#  front_spotlight:
 #   ffmpeg:
  #    output_args:
   #     record: preset-record-generic-audio-aac
    #  inputs:
     #   - path: rtsp://127.0.0.1:8554/front_spotlight_cam #?video=copy&audio=aac
      #    input_args: preset-rtsp-restream
       #   roles:
        #    - record
#        - path: rtsp://127.0.0.1:8554/front_spotlight_cam_sub #?video=copy
 #         input_args: preset-rtsp-restream
  #        roles:
   #         - detect
    #snapshots:
     # enabled: true
    #zones:
     # driveway:
      #  coordinates: 0,720,132,720,241,720,367,720,511,720,676,720,831,720,986,720,1162,720,1280,720,1280,490,1280,283,1236,267,1170,243,1058,214,981,203,790,177,614,163,437,166,329,169,204,180,77,206,0,226
    #motion:
     # mask:
      #  - 1105,0,1087,113,1002,99,1007,0
    #rtmp:
     # enabled: false
  front_spot:
    ffmpeg:
      #output_args:
      #  record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/spot_cam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/spot_cam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect



record:
  enabled: True

  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - cat
      - dog
    required_zones: []
    retain:
      default: 5
      mode: motion
      objects:
        person: 1000
```
