### DISCUSSION TITLE
How to use Nvidia GTX 1080 card for Object detection and also off loading to the GPU

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#9110] [Ask A Question] [answered]
So I have read that you can use your NVIDIA card for doing detection ([source](https://docs.frigate.video/configuration/detectors/#nvidia-tensorrt-detector)) But there is not a lot of information on this. I have already exposed my GPU to Frigate and it can see it but how do I use it for detection. It feels like i am reading another language when i read this section.  How do i get started ?

**Comment by MrCaspan** [comment]
This document says "Also the GPU must support a Compute Capability of 5.0 or greater." I can see that my GPU supports 6.1
![2023 12 28-000125](https://github.com/blakeblackshear/frigate/assets/19710296/7e381b7c-fd98-4611-a3e8-df9aeccf86f0)

But i get to this section that says that you have to generate models from my hardware. and I try to run the following commands on my TrueNAS Scale server and on the last command i get an error that docker is not an installed app

`
mkdir trt-models
wget https://github.com/blakeblackshear/frigate/raw/master/docker/tensorrt_models.sh
chmod +x tensorrt_models.sh
docker run --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:22.07-py3 /tensorrt_models.sh
`

How do I run this command in TrueNAS to generate these models?

**Reply by jmtatsch** [reply]
Look into how to installing docker on your TrueNas.
I can confirm my 1080 TI works well for a dozen cameras.

**Reply by NickM-27** [reply]
running nvidia is easier in 0.13 as the models are generated automatically for you

**Reply by MrCaspan** [reply]
How do I install 0.13 on TrueNAS?

**Reply by MrCaspan** [reply]
@NickM-27 So I am now running 0.13.2-6476F8A how do I use the GPU to do detecting? Any help would be appreciated

**Reply by NickM-27** [reply]
https://docs.frigate.video/configuration/object_detectors#nvidia-tensorrt-detector

**Reply by MrCaspan** [reply]
I have read this but have no idea what how to enable this support. Sorry for not understanding but all i can get form this is that I have to enable it

```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
```
Then I have to give it a model to use, but i am not sure where to get the model information from?

```
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

**Reply by jmtatsch** [reply]
Your frigate  config seems identical to mine which worked.
Maybe you are missing these env variables:

```
    environment:
      - YOLO_MODELS=yolov7-320
      - USE_FP16=false
```

I think the first line defines which model to generate for download and convert to tensorrt.
The latter turns off FP16 support which the 1080 in theory supports but is not very accelerated for.  Not sure it's absolutely necessary but its recommended in the readme for pascal based  cards.


How are you launching frigate? 
This was my docker compose file for reference:

```
version: "3.8"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.2-tensorrt
    group_add:
      - "109" # render
      - "110" # render
      - "44" # video
      - "46" # plugdev
    shm_size: "256mb"
    privileged: true
    hostname: "frigate"
    restart: "unless-stopped"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - YOLO_MODELS=yolov7-320
      - USE_FP16=false
    env_file:
      - ./secrets.env
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config:rw
      - ./media:/media/frigate:rw
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8001:5000" # web interface
      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555" # webrtc
      - "1984:1984" # go2rtc ui
```

**Reply by MrCaspan** [reply]
Here is my config:

```
mqtt:
  enabled: false

# Enable recording of all cameras and retain it for 14 days
record:
  enabled: true
  retain:
    days: 14

# Use the GPU to help with decoding streams and record audio!
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

# Enable birdseye option to see any cameras with motion on them 
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

detect:
  enabled: False
  width: 1920
  height: 1080

#detectors:
#  tensorrt:
#    type: tensorrt
#    device: 0 #This is the default, select the first GPU


motion:
  mask:
    - 1364,76,1894,68,1891,0,1361,0 # Mask off time on all cameras

cameras:
  Garage:
    onvif:
      host: 192.168.86.210
      port: 8000
      user: 9oWLCdbmLKvd7
      password: 0jNlFeIj1iXT!
    ffmpeg:
      inputs:
        - path: rtsp://##:##@192.168.86.210/h264Preview_01_main
          roles:
            - record
        - path: rtsp://##:##@192.168.86.210/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: False
      width: 640
      height: 480
      fps: 4
    motion:
      mask:
        - 385,21,640,21,640,0,385,0 # Mask of time

  Deck:
    ffmpeg:
      inputs:
        - path: rtsp://##:##@192.168.86.214/live0
          roles:
            - record

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://##:##@192.168.86.213/h264Preview_01_main
          roles:
            - record
        - path: rtsp://##:##@192.168.86.213/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: False
      width: 640
      height: 360
      fps: 4
    motion:
      mask:
        - 385,21,640,21,640,0,385,0 # Mask of time

  Front_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://##:##@192.168.86.212/live0
          roles:
            - record
    motion:
      mask:
        - 1364,76,1894,68,1891,0,1361,0 # Mask of time
        - 1920,1080,1806,1080,1800,1053,1805,992,1803,899,1838,797,1920,761 # Mask off Christmas lights

  Ripleys_Room:
    ffmpeg:
      inputs:
        - path: rtsp://##:##@192.168.86.211/live0
          roles:
            - record

  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://##:##@192.168.86.217/h264Preview_01_main
          roles:
            - record
        - path: rtsp://##:##@192.168.86.217/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: False
      width: 640
      height: 480
      fps: 4
    motion:
      mask:
        - 385,21,640,21,640,0,385,0 # Mask of time

```

If you look at my detector setting. If I uncomment this line it crashes my frigate.. And I am using Frigate in TrueNAS Scale!

**Reply by NickM-27** [reply]
Are you using the correct tensorrt image?

**Reply by MrCaspan** [reply]
I have no idea how to know that :) Sorry I am so new at this.. I do have a Coral TPU that I wanted to use but its an NVMe one and TrueNAS does not alowo this in the config to be passed through yet it seems, only USB. Thats why I thought use the GPU if I have it! Sorry for the dumb answers of I dont know!

**Reply by jmtatsch** [reply]
TrueNAS seems to be freebsd based and there does not seem to exist NVIDIA CONTAINER TOOLKIT for it https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.14.5/supported-platforms.html

**Reply by MrCaspan** [reply]
Also just as an FYI looking at my /config/model_cache I have no model files
![2024 03 05-000166](https://github.com/blakeblackshear/frigate/assets/19710296/02fd70f0-23bd-450e-8490-f356f0961a90)

**Reply by MrCaspan** [reply]
I do have GPU support in my frigate as it sees my card in System settings if that matters?
![2024 03 05-000167](https://github.com/blakeblackshear/frigate/assets/19710296/a80b78d1-f082-41c1-a32a-4f069e697c72)

**Reply by jmtatsch** [reply]
in config/model_cache/tensorrt(dev*)
there should be                              
8.5.3  yolov7-320.trt

**Reply by NickM-27** [reply]
@jmtatsch OP is not running the tensorrt image variant, that is the problem here.

**Reply by MrCaspan** [reply]
Yeah my entire model_cache folder is empty.. sorry for all the confusion!

**Reply by jmtatsch** [reply]
@NickM-27 He also won't be able to run the tensorrt image variant without nvidia container toolkit ... its pointless

**Reply by MrCaspan** [reply]
So I cannot use my GPU to do tensor checking with TrueNAS Scale?

**Reply by jmtatsch** [reply]
TrueNAS Scale is Debian-based NAS. So there should be a chance to get nvidia docker support running.

**Reply by MrCaspan** [reply]
I can pass enviroment arguments to my image when it boots if that is required? Or can I copy the files i need form an existing image and just pu thtem in my cache folder?

**Reply by NickM-27** [reply]
no, you need to change the image that is pulled from as that contains the tensorrt libraries needed

**Reply by MrCaspan** [reply]
Is this somthing simple to do with TrueNAS, do you have any idea?

**Reply by NickM-27** [reply]
It should be assuming you update to 0.13 it is just adding `-tensorrt` to the end of the image. I have never used truenas so I have no idea

**Reply by MrCaspan** [reply]
I am running 0.13 so I just need to find a way to add this switch to the startup?

**Reply by NickM-27** [reply]
No, there are multiple images for 0.13 and you're most likely using the basic one. https://docs.frigate.video/frigate/installation#docker

**Reply by MrCaspan** [reply]
Thanks for all your help!!

**Reply by MrCaspan** [reply]
So Nick i stupidly realized that on TrueNAS you can install the tensor version (madefor nvidia GPUs) but the option did not show untill I had to reinstall frigate. So i am going to now try to enable this using the models that you suggested!

**Reply by MrCaspan** [reply, marked as answer]
And that seems to have worked. I have a proper tensor model in my model_cache folder. So TrueNAS users you need to install the iX application not testted on TreuCharts but they seem to have the same option but their image is named more accuratly and led me to look for this on my iX application. Edit your frigate app and look at the image selection and select the "Frigate TensorRT Image"

![2024 03 14-000176](https://github.com/blakeblackshear/frigate/assets/19710296/8ab48937-a040-460e-91de-62e432826a63)

Then add this to your config

```
detectors:
  NVIDIA GeForce GTX 1080: #Yes you can have spaces
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

I knew to use the yolov7-320.trt model because when i used the shell to navagate to the /config/model_cache/tensorrt/ folder there was only one model in that folder that was linked to a model that was in the version number folder that was also in there. So it looks like frigate detected my GPU and added the model symbolic link to this folder for me.
