### DISCUSSION TITLE
Reolink Doorbell Stream Differences

### DISCUSSION THREAD

**Discussion by Spectre5** [blakeblackshear/frigate#9124] [Ask A Question] [answered]
I have the Reolink doorbell (wifi sadly) setup and working fairly well overall.  However, I have a couple of questions.  In the docs, the recommended setup for reolink in general uses go2rtc for both streams:

```yaml
go2rtc:
  streams:
    your_reolink_camera: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"
    your_reolink_camera_sub: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"
```

Why is the recommendation to use go2rtc for both streams?  I would think we'd only use it for the main stream (to view live in the browser or home assistant via web2rtc) and then just use the substream for the detection without go2rtc.  What is the advantage or using go2rtc here?

Second, I've seen 3 streams used at times, `stream=channel0_main`, `stream=channel0_ext`, and `stream=channel0_sub`.  The first is obviously the main high res stream, but I've seen both of the second two indicated for the substream.  What is the difference between those two?  I can open either one in VLC and the "_sub" one appears to be slightly lower resolution than "_ext", I think, but both a bit less than the main stream.

**Comment by NickM-27** [comment, marked as answer]
The recommendation is simply for simplicity of configuring the camera, you are correct it is more efficient to only restream one stream.

Yes, ext is a mid stream that provides better resolution

**Reply by Spectre5** [reply]
Thanks for the quick help.  When logged into the camera directly, I can setup the "Clear" stream (main, I assume) and "Fluent" stream (sub, I assume), but how do I configure (or determine) the "Ext Stream" resolution and fps?  The resolution should match the "detect" setting I think:

```yaml
    detect:
      enabled: True
      width: 640
      height: 480
```
