### DISCUSSION TITLE
Ingesting streams uses a lot of CPU even though I have a GPU enabled

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#9126] [Ask A Question] [answered]
So question I am ingesting 5 Eufy cameras that support 1920x1080 15fps I have a 4 core 8 thread Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz i am recording ONLY nothing else. as soon as I turn on Frigate my CPU sits at 20% up to 50% consistantly.  I have enabeled GPU support for H.264 on my Nvidia Gfroce GTX 1080 but it says its only using 1% GPU and 15% memory.. My CPU seems to still bear the brunt of the workload. Im just curious if this is typical or should my GPU be doing all the work? Is it because it's an integrated Network card to the motherboard and bring in that much data form the network all the time puts load on the CPU? Would installing a network card on the PCIe channel change this?

Just curious what my expected results should be from turning on the GPU support becuase it really does not seem to be doing much..

Photos of GPU and CPU usage if it helps
![2023 12 29-000126 - Copy](https://github.com/blakeblackshear/frigate/assets/19710296/4fa1834e-bc27-4c63-9a90-ca6e093b5959)
![2023 12 29-000127 - Copy](https://github.com/blakeblackshear/frigate/assets/19710296/4ad543bd-e2b2-434a-b27c-5e849677dcae)

Copy of config

```
mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 14

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://6qONiFt2cHVz:2wTT4pU2mQeM@192.168.86.84/live0
          roles:
            - record

  Deck:
    ffmpeg:
      inputs:
        - path: rtsp://SMAIN270b:catFROGS213@192.168.86.211/live0
          roles:
            - record
  
  Driveway:
    ffmpeg:
      inputs:
        - path:  rtsp://3BmjmLRcgRkK:8IWndVCcOOFD@192.168.86.96/live0
          roles:
            - record

  HouseFront:
    ffmpeg:
      inputs:
        - path:  rtsp://7KvGYY0AG3F1:6BIwcoItbGrE@192.168.86.151/live0
          roles:
            - record

  Baby:
    ffmpeg:
      inputs:
        - path:  rtsp://2hQRDO7wRkl1:1wklmLp5f11h@192.168.86.136/live0
          roles:
            - record
```

**Comment by NickM-27** [comment]
Frigate always decodes streams, according to your screenshot object detection is enabled too. Also you haven't set a detect resolution so frigate is downscaling the streams to 1280x720 as well. 

Changing roles does not disable any features.

**Reply by MrCaspan** [reply]
I don't want to detect anything I just wnat it to record that is why I have no detect settings. Is it not possible to just bring in video and store it without doing anything to it?

**Reply by NickM-27** [reply]
Object detection is enabled by default so "no detect settings" does not mean it is disabled. 

You need to configure to disable object detection and in that case only recording and motion detection are enabled.

Some recording modes require motion detection but for `all` it could be disabled

In any case the decoding of the stream can't be disabled, you should set the detect resolution to match the camera resolution

**Reply by MrCaspan** [reply, marked as answer]
So i should do 

```
detect:
  enabled: False
  width: 1920
  height: 1080
```
This would disable detection?
