### DISCUSSION TITLE
Proxmox with PCIe Coral to VM

### DISCUSSION THREAD

**Discussion by benroscoe** [blakeblackshear/frigate#916] [Show and tell]
Wanted to share what I had so far for a setup. As I saw discussion of this not working well in some cases. 

I have a server running Proxmox that I installed a Coral M.2 with B/M keying into a PCIe to M.2 adapter that I already had from using an NVMe drive into a system that didn't need it. This system doesn't have an M.2 slot or I could have used that.

I used the PCIe device as I saw warnings about passing through USB devices and maybe adding a lot of overhead. In general I've had more issues with USB devices than PCIe devices. Plus it was in stock and cheaper.

The setup below assumes you've already set your server up to pass through PCIe devices. I didn't have to do that on mine as it was already done, so I don't have notes on doing that.

In Proxmox I then had to black list the driver by adding a new file under /etc/modprobe.d/tpu.conf. I also added a second entry while trying to figure out how to pass this through the VM. I'm not entirely sure this was needed though.

blacklist apex
options vfio-pci ids=1ac1:089a disable_idle_d3=1

Then make sure to refresh you initramfs 
update-initramfs -u -k all

I never did get the gui to let me assign this device. For some reason it didn't work. However, you can use the command line to do it manually. Use your VM ID for VM##. Look at your PCIe tree to replace 03:00.0 below.
qm set VM## -hostpci0 03:00.0

I am using that with a Ubuntu server VM. From there a normal docker install worked fine. See my docker compose entry below. 

```yaml
frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    privileged: true
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - type: volume
        source: frigate_media
        target: /media/frigate
      - type: volume
        source: frigate_config
        target: /config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935 #RTMP
    networks:
      - localnet
    environment:
      TZ: "America/Chicago"
      FRIGATE_RTSP_PASSWORD: 'password'
    restart: always
```

Note: I did try using this with my HA VM but sadly the driver for the PCIe device isn't included in there. So I had to go the Docker route.
