### DISCUSSION TITLE
"No files to concat" error when trying to download a custom clip of a recording

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#9194] [Ask A Question] [answered]
I am running 0.12.1-367D724 on TrueNAS (official iX app)  I am only using Frigate as a backup storage server for my Eufy cameras. So all I have enabled is 24/7 recording. Becuase of this I dont get the option for downloading anything from the recordings page and the files are all stored in 10s segments on the files system so thats not really an option. I read [here](https://github.com/blakeblackshear/frigate/issues/2369#issuecomment-987531072) that there is a backend option for exporting a custom time segment of a recording. When I try to do this I get the following errors:

This is the URI that I am using to try and downlaod a 10 minute clip:
~~`http://192.168.86.232:30058/api/deck/start/946702800000/end/946703400000/clip.mp4`~~
`http://192.168.86.232:30058/api/deck/start/1704103200/end/1704103800/clip.mp4`

Error the webpage shows when i visit the URI above:
`Could not create clip from recordings for deck.`

Frigate Error logs:
```2024-01-03 20:29:29.261570161  [2024-01-03 20:29:29] frigate.http                   ERROR   : ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
2024-01-03 20:29:29.261572071    built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
2024-01-03 20:29:29.261577260    configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
2024-01-03 20:29:29.261578272    libavutil      57. 28.100 / 57. 28.100
2024-01-03 20:29:29.261579119    libavcodec     59. 37.100 / 59. 37.100
2024-01-03 20:29:29.261579905    libavformat    59. 27.100 / 59. 27.100
2024-01-03 20:29:29.261580700    libavdevice    59.  7.100 / 59.  7.100
2024-01-03 20:29:29.261581494    libavfilter     8. 44.100 /  8. 44.100
2024-01-03 20:29:29.261582278    libswscale      6.  7.100 /  6.  7.100
2024-01-03 20:29:29.261583072    libswresample   4.  7.100 /  4.  7.100
2024-01-03 20:29:29.261583857    libpostproc    56.  6.100 / 56.  6.100
2024-01-03 20:29:29.261584677  [concat @ 0x55f8f3f80a80] No files to concat
2024-01-03 20:29:29.261585533  /dev/stdin: Invalid data found when processing input```

I have 14 days of recording retentions turned on and I have watched this footage so I know it is there. I am only going back 2 days so I am not sure why I am getting this error. Any ideas?

**Comment by NickM-27** [comment]
your timestamp is incorrect, `946702800000` is 24 years ago

![Screen Shot 2024-01-03 at 14 03 47 PM](https://github.com/blakeblackshear/frigate/assets/14866235/dc317fb7-5fca-4ce6-af70-c5f217b7c3bf)

**Reply by MrCaspan** [reply]
Sorry this is the URI:
`http://192.168.86.232:30058/api/deck/start/1704103200/end/1704103800/clip.mp4` I also updated it in the OP. I was using the proper epoch time when testing but for some reason in the OP I pasted teh URI I was experimenting with! I am still getting the same error with this URI

**Reply by NickM-27** [reply]
what is your config?

**Reply by MrCaspan** [reply]
```
mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 14

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-aac

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

detect:
  enabled: False
  width: 1920
  height: 1080

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://*:*@192.168.86.84/live0
          roles:
            - record

  Deck:
    ffmpeg:
      inputs:
        - path: rtsp://*:*@192.168.86.211/live0
          roles:
            - record

  Driveway:
    ffmpeg:
      inputs:
        - path:  rtsp://*:*@192.168.86.96/live0
          roles:
            - record

  HouseFront:
    ffmpeg:
      inputs:
        - path:  rtsp://*:*@192.168.86.151/live0
          roles:
            - record

  Baby:
    ffmpeg:
      inputs:
        - path:  rtsp://*:*@192.168.86.136/live0
          roles:
            - record
```
