### DISCUSSION TITLE
Error starting Frigate - always get: IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'

### DISCUSSION THREAD

**Discussion by rkozsan** [blakeblackshear/frigate#9213] [General]
I have read many, many discussions about this, but cannot find an explanation or working resolution.
Attempting to run in Docker on Ubuntu 20.04.3 LTS

What am I missing - any thoughts?

From docker compose file:
```    
volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/data:/media/frigate
      - /frigate/config.yml:/config/config.yml
```
Path and config file most definitely exist:
```
# ls -l /frigate
total 8
-rw-r--r-- 1 root root  229 Jan  4 22:47 config.yml
drwxr-xr-x 5 root root 4096 Jan  4 22:33 data
```
Per the instructions, a minimalist config:

```
# cat /frigate/config.yml 
mqtt:
  host: mqtt.server.com
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.0.138/Streaming/Channels/1
          roles:
            - detect
    detect:
      width: 1280
      height: 720
```

I have confirmed the use of spaces (and not tabs) in config file.
