### DISCUSSION TITLE
Minimal configuration to identify people

### DISCUSSION THREAD

**Discussion by array81** [blakeblackshear/frigate#9228] [Ask A Question]
I have installed Frigate and I would like to understand what the minimum configuration is to find people.
I'm not interested in recording footage (I have an NVR for that). My goal is to have alarms in Home Assistant when people are detected (people only).

This is my code:

```
mqtt:
  enabled: false
cameras:
  Taverna:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://myaddress
          roles:
            - record
            - detect
    objects:
      track:
        - person
    detect:
      enabled: True
      width: 1920
      height: 1080
    record:
      enabled: False
      retain:
        days: 7
        mode: all
  Soggiorno:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://myaddress
          roles:
            - record
            - detect
    objects:
      track:
        - person
    detect:
      enabled: True
      width: 1920
      height: 1080
    record:
      enabled: False
      retain:
        days: 7
        mode: all
  Mansarda:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://myaddress
          roles:
            - record
            - detect
    objects:
      track:
        - person
    detect:
      enabled: True
      width: 1920
      height: 1080
    record:
      enabled: False
      retain:
        days: 7
        mode: all
detectors:
    cpu1:
      type: cpu
      num_threads: 3
```
Frigate shows footage from the 3 cameras but I don't see any events on detecting people.
