### DISCUSSION TITLE
Critique my config - seems like high CPU usage

### DISCUSSION THREAD

**Discussion by bradphillips921** [blakeblackshear/frigate#9244] [General]
I'm trying to work out some high CPU usage on my Home Assistant server, looking for some help on the Frigate config.

Hardware:
Intel i5-11600K @ 3.90GHz
Google Coral (PCIe Version) https://www.ebay.com/itm/384965292499
16GB DDR4 RAM

My CPU is pretty consistently around 30-40% usage, but if I turn Frigate off it drops to 2-3%.

Here is my Frigate config

```
# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci

record:
  enabled: true
  retain:
    days: 0
  events:
    max_seconds: 300
    retain:
      default: 1
      mode: motion

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: 25)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 20
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 18
```

An example of a camera. I'm monitoring 11 cameras.

```
  driveway_west:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX:XXXXXXX@192.168.1.95:554/cam/realmonitor?channel=1&subtype=0
          roles: 
            - detect
    detect:
      width: 3840
      height: 2160
    objects:
      track:
        - person
        - car 
#     filters:
    motion:
      mask:
        - 3837,438,1984,147,1975,0,3834,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
```

Is this a pretty normal CPU load? Or can improvements be made?

**Comment by NickM-27** [comment]
you are running detect on a 4k stream, this is specifically discouraged in the docs as higher resolution generally does not lead to better detection results https://docs.frigate.video/frigate/camera_setup#choosing-a-detect-resolution

**Comment by bradphillips921** [comment]
Thanks for the feedback. I had read somewhere else that I should match the
```
    detect:
      width: 3840
      height: 2160
```
to the camera's resolution. Is that accurate? My camera has a sub-stream, but the highest sub-stream resoultion is 704x480. Is that too low? If I use the sub stream do I need to change my detect settings to the same resolution?

**Reply by NickM-27** [reply]
that high of detect resolution is not recommended. If you have a GPU to do hwaccel then you can specify a different size in detect and frigate will use the GPU to downscale the stream, but this is only recommended when the cameras sub stream is not enough.

and to reiterate, this is why frigate recommends cameras with good sub streams

**Comment by bradphillips921** [comment]
Thanks! I'll drop my detect down to 1920x1080 to see if that helps.

**Reply by NickM-27** [reply]
be sure that you have ffmepg hwaccel_args added

**Reply by bradphillips921** [reply]
Do I add that to the config for each camera?

**Reply by NickM-27** [reply]
it can be added globally

**Reply by bradphillips921** [reply]
Thanks!

**Reply by bradphillips921** [reply]
I added the ffmpeg to my config. Now I just get green squares for all my camera feeds in the Frigate integration. Did I add it incorrectly?

```
# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci

#https://github.com/blakeblackshear/frigate/discussions/9244#discussioncomment-8056622
#https://docs.frigate.video/configuration/hardware_acceleration/
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
```
