### DISCUSSION TITLE
Help integrating Frigate in home assistant

### DISCUSSION THREAD

**Discussion by The-NinthWave** [blakeblackshear/frigate#9247] [Ask A Question] [answered]
Running Frigate in Docker/Portainer
latest:stable
Web UI is working fine.

Portainer Stack
```
services:
  frigate:
    container_name: frigate
    privileged: true                     # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    hostname: kontrolisto2
    networks:
      IOT:
        ipv4_address: 172.18.10.45
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    shm_size: "96mb"                     # update for your cameras based on calculation
    devices:
      - /dev/dri:/dev/dri                # VAAPI/NVDEC/NVENC render nodes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/trt-models:/trt-models
      - config:/config/
      - storage:/media/frigate           # modify to match your setup
      - database:/db                     # modify to match your setup
      - type: tmpfs                      # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
    environment:
      USE_FP16: False
      FRIGATE_RTSP_PASSWORD: "password"  # modify to whatever if using rtsp
volumes:
  config:
  storage:
  database:
networks:
  IOT:
    external: true
```

Excerpt of Frigate config.yml
```
# yaml-language-server: $schema=http://10.0.0.20:5000/api/config/schema
mqtt:
  enabled : True
  host: 10.0.10.8
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistant
  password: "none of anyone business"
  stats_interval: 60

```
**Mosquitto-MQTT broker addon installed and configured**
```
logins: []
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: false
  folder: mosquitto
```

**MQTT Integration installed and configured**

**Frigate-proxy addon installed and configured**
```
server: http://10.0.0.20:5000
proxy_pass_host: true
```
Frigate proxy logs show a connexion error
```
-----------------------------------------------------------
 Add-on: Frigate Proxy
 Proxy addon for Frigate
-----------------------------------------------------------
 Add-on version: 1.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.3  (amd64 / qemux86-64)
 Home Assistant Core: 2024.1.2
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:18:07] INFO: Starting NGinx...
2024/01/07 17:18:11 [error] 349#349: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: 4601ec1a-frigate-proxy, request: "GET // HTTP/1.1", upstream: "http://10.0.0.20:5000//", host: "10.0.10.8:8123", referrer: "http://10.0.10.8:8123/hassio"
2024/01/07 17:19:50 [error] 349#349: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: 4601ec1a-frigate-proxy, request: "GET // HTTP/1.1", upstream: "http://10.0.0.20:5000//", host: "10.0.10.8:8123", referrer: "http://10.0.10.8:8123/4601ec1a_frigate-proxy"
2024/01/07 17:34:34 [error] 349#349: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: 4601ec1a-frigate-proxy, request: "GET // HTTP/1.1", upstream: "http://10.0.0.20:5000//", host: "10.0.10.8:8123", referrer: "http://10.0.10.8:8123/hassio"
```

But what have I missed ?
