### DISCUSSION TITLE
Object Detected/Recorded Outside of Zone/Mask

### DISCUSSION THREAD

**Discussion by DC651F82053AD314** [blakeblackshear/frigate#9264] [Ask A Question] [answered]
I've been searching for the answer from others who may have asked this, but I am not understanding what may be wrong in my config which is allowing the recording of objects outside of my zones.

I have setup masks and zones for my cameras, and I'm only tracking one type of object: "car", but I'm still getting recordings of objects in the events that are not within the zone I set.  I understand that the mask does not prevent object detection/tracking, but I thought that specifying a `required_zone` in the config for the camera would avoid recording of objects outside of the zone.  Is there perhaps something I need to change in my config file to get only recordings of the intended object that took place within the zone?

I'm on version: 0.13.0-C35C7DA

Here is an example.  The "car" was detected and recorded to this event:
![image](https://github.com/blakeblackshear/frigate/assets/127766978/61eae4c4-40aa-44ed-b738-44b94f783dbc)

But the vehicle was moving outside of my mask and zone, please see this example showing my mask area and zone box:
![image](https://github.com/blakeblackshear/frigate/assets/127766978/0b31cfc0-126a-47e6-899f-27d749f67807)

Here's my current config file:

```
cameras:
  truckcam1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.123.8:554/11
          roles:
            - record
            - detect
    detect:
      width: 800 # <---- update for your camera's resolution
      height: 600 # <---- update for your camera's resolution
      fps: 15
    motion:
      mask:
      - 800,600,589,600,800,180
      - 608,0,613,21,800,21,800,0,800,0,800,0
      - 263,0,0,0,0,142
    zones:
      entry_lane:
        coordinates: 779,128,778,69,216,0,0,270,0,438,0,600,596,600
        objects:
          - car
    snapshots:
      enabled: True
      timestamp: true
      bounding_box: true
      retain:
        default: 60
      required_zones:
        - entry_lane
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - entry_lane
    objects:
      track:
        - car
  truckcam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:41HBY44YwPAA@192.168.123.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 15
    motion:
      mask:
      - 216,0,704,0,704,95,441,77,404,66,227,72
      - 0,0,0,480,243,480,243,0
      - 704,0,396,0,704,451
    zones:
      exit_lane:
        coordinates: 704,480,426,57,234,46,244,480
        objects:
          - car
    snapshots:
      enabled: True
      timestamp: true
      bounding_box: true
      retain:
        default: 60
      required_zones:
        - exit_lane
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - exit_lane
    objects:
      track:
        - car


# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /db/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: usb
#  coral2:
#    type: edgetpu
#    device: pci:1

#objects:
#  track:
#    - car

#snapshots:
#  enabled: True
#  timestamp: true
#  bounding_box: true
#  retain:
#    default: 60
mqtt:
  host: 192.168.123.7

ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
  output_args:
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

#record:
#  enabled: True
#  events:
#    pre_capture: 20
#    post_capture: 20
#    retain:
#      default: 60
#      mode: active_objects
#    objects:
#      - car

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
```
