### DISCUSSION TITLE
help and understand Stationary Objects

### DISCUSSION THREAD

**Discussion by mabed-fr** [blakeblackshear/frigate#9274] [General]
Hello

I not understand how my car (cars) triger the motion

I don't understand why my car after 19 minutes is still not a stationary object

![image](https://github.com/blakeblackshear/frigate/assets/25350431/b8977a45-b46f-4d9c-a212-bc7e8f428bcb)

Config

```
mqtt:
  host: 192.168.1.254

birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
 track:
   - person
   - car
   - bicycle
   - motorcycle
   - cat
   - dog
   - plate
   - traffic light

go2rtc:
  streams:
    TELECOM:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main

cameras:
  TELECOM:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    onvif:
      host: 192.168.1.146
      port: 8000
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 10

record:
  expire_interval: 60
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 1

snapshots:
  enabled: true
```

I do not understand well ...

Thank
