### DISCUSSION TITLE
Why is the HD-Switchbutton no longer displayed in my Card?

### DISCUSSION THREAD

**Discussion by albotroz** [blakeblackshear/frigate#9305] [Ask A Question]
Any idea why the HD-switch button is no longer displayed with this config?

- Frigate Addon, Frigate Integration, Frigate Hass Cards
```
square: false
type: grid
cards:
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.hof
        title: Hof SD
        hide: false
        frigate:
          camera_name: hof_sub
        triggers:
          occupancy: false
          motion: true
          entities:
            - binary_sensor.hof_all_occupancy
        dependencies:
          cameras:
            - hof
        webrtc_card: {}
        go2rtc:
          modes: []
        live_provider: go2rtc
        id: hof_sub
    view:
      default: live
      camera_select: live
      dark_mode: 'off'
      update_seconds: 5
      timeout_seconds: 10
      update_force: true
      scan:
        enabled: true
        untrigger_seconds: 10
    menu:
      style: hidden
      buttons:
        substreams:
          icon: mdi:high-definition
        expand:
          enabled: false
    live:
      preload: true
      auto_mute: all
      auto_pause: never
      auto_play: all
      lazy_load: false
      controls:
        next_previous: {}
      layout:
        fit: cover
      microphone:
        disconnect_seconds: 2
    media_gallery:
      controls:
        thumbnails:
          show_details: true
    media_viewer:
      auto_pause: hidden
      auto_mute: all
      auto_play: never
    image:
      layout: {}
  - type: custom:frigate-card
    cameras:
      - camera_entity: camera.front
        title: Front SD
        hide: false
        frigate:
          camera_name: front_sub
        triggers:
          occupancy: false
          motion: true
          entities:
            - binary_sensor.front_all_occupancy
        dependencies:
          cameras:
            - front
        webrtc_card: {}
        go2rtc:
          modes: []
        live_provider: go2rtc
        id: front_sub
    view:
      default: live
      camera_select: live
      dark_mode: 'off'
      update_seconds: 5
      timeout_seconds: 10
      update_force: true
      scan:
        enabled: true
        untrigger_seconds: 10
    menu:
      style: hidden
      buttons:
        substreams:
          icon: mdi:high-definition
        expand:
          enabled: false
    live:
      preload: true
      auto_mute: all
      auto_pause: never
      auto_play: all
      lazy_load: false
      controls:
        next_previous: {}
      layout:
        fit: cover
      microphone:
        disconnect_seconds: 2
    media_gallery:
      controls:
        thumbnails:
          show_details: true
    media_viewer:
      auto_pause: hidden
      auto_mute: all
      auto_play: never
    image:
      layout: {}
columns: 2

```
