### DISCUSSION TITLE
Is there a way to disable motion completely on certain cameras?

### DISCUSSION THREAD

**Discussion by jakeprice-me** [blakeblackshear/frigate#9321] [General]
I've not been able to find anything solid through searching, but apart from disabling motion for a camera through the Home Assistant integration (which get's turned back on once Frigate is restarted) is there a way to disable it permanently in the Frigate's `config.yml`?

I have a number of cameras that I really don't need motion detection on for and the motion events are coming in thick and fast on my Home Assistant Logbook. If it's not yet possible, is there a workaround - i.e. would increasing the motion threshold to it's highest value help a bit for now? I presume the Home Assistant integration is calling some sort of API function to disable motion, or am I wrong - is that something we can call ourselves?

**Comment by NickM-27** [comment]
Currently it is only possible via mqtt which is what the integration uses. There is an existing request to add it to the config as well. Regardless, it is not difficult to set up an automation that listens to the state of the switch going from unavailable to any state and then setting it to the default state - I use this to disable audio detection by default after frigate is restarted

**Reply by jakeprice-me** [reply]
Great thanks for the information @NickM-27.

Yes, that's a good idea. I'll use an automation for now! Thanks.

For future reference (anybody searching for similar question), this looks to be the outstanding issue: https://github.com/blakeblackshear/frigate/issues/4326

**Reply by jakeprice-me** [reply]
Also for future reference, the automation I've created is below. This turns off the motion detection switch if it gets turned on (manually or by a Frigate restart).

```yaml
alias: "[FRIGATE] Disable Motion Detection on Indoor Cameras"
description: >-
  As of 2024-01-12 there is no way to permanently disable motion for specific
  cameras in Frigate. You can however turn it off in Home Assistant, but if
  Frigate is restarted it is automatically turned back on. This automation
  listens for this event, and when detected turns it right back off!
trigger:
  - platform: state
    entity_id:
      - switch.lounge_motion
      - switch.hallway_motion
      - switch.kitchen_motion
      - switch.master_bedroom_motion
      - switch.kids_bedroom_motion
      - switch.landing_motion
    to: "on"
    from: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - switch.lounge_motion
        - switch.hallway_motion
        - switch.kitchen_motion
        - switch.master_bedroom_motion
        - switch.kids_bedroom_motion
        - switch.landing_motion
  - service: telegram_bot.send_message
    data:
      title: 🔵 <strong>Motion Detection Turned off for Indoor Cameras</strong>
      message: >-
        Home Assistant has automatically turned off Frigate motion detection on
        indoor cameras. The automation responsible can be found at
        <url>
      parse_mode: html
mode: single
```
