### DISCUSSION TITLE
Whats wrong with my config file? Frigate crashes at startup

### DISCUSSION THREAD

**Discussion by nixxon94** [blakeblackshear/frigate#9326] [General]
```
mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: password1

detectors:
    coral:
        type: edgetpu
        device: usb

cameras:
    garage:
        ffmpeg:
            inputs:
                - path: rtsp://admin:VJLYKII@192.168.178.31:554/H.264
                  roles:
                    - detect
        snapshots:
            enbabled: True
        detect:
            enabled: True
        objects:
            track:
                - person

```

I had it running for a few hours but never got it back up 

It doesnt even start the container currently.
the coral tpu is recognized and the camera feed works fine.

Any input is greatly appreciated, TIA!
