### DISCUSSION TITLE
How to use / access different streams of ONVIF cameras?

### DISCUSSION THREAD

**Discussion by aisbergde** [blakeblackshear/frigate#9353] [Ask A Question]
frigate suggestion is to use different streams for recording and detection.
I have one camera, which I can access only via ONVIF (because IP CENTCOM can discover). This camera has 3 different "Media Profiles"
- Profile_000(H264:1920x1080)
- Profile_001(H264:704x576)
- Profile_002(JPEG:704x578)

In "IP CENTCOM" I can select a stream. But how I should define the go2rtc configuration in frigate?
The documentation at https://github.com/AlexxIT/go2rtc/tree/v1.8.4?tab=readme-ov-file#source-onvif only says
```
streams:
  dahua1: onvif://admin:password@192.168.1.123
  reolink1: onvif://admin:password@192.168.1.123:8000
  tapo1: onvif://admin:password@192.168.1.123:2020
```
There is no hint, how to access sub streams.

Other Cameras (reolink and foscam) I can access via ONVIF or rtsp. 
ONVIF setup seams to be easier, because it is easier to find the required url. But currently I use all other cameras via rtsp, because otherwise I don't know, how to distinguish between different streams using ONVIF.

BTW, what kind of ONVIF support was added in frigate 0.13 compared to 0.12?
Yesterday I installed frigate the first time (0.12), today I upgraded to 0.13-rc. but I can't find something what could help to discover ONVIF cameras.

I still need to find out, how to install HACS into my HA (in docker on Synology) to be able to use the frigate integration into HA.

**Comment by arhills** [comment]
You set different streams for different roles in the config file under the ffmpg: heading

`    ffmpeg:
      inputs:
      - path: rtsp://192.168.1.xxx:554/12
        roles:
        - detect
      - path: rtsp://192.168.1.xxx:554/11
        roles:
        - record`

https://docs.frigate.video/configuration/cameras/

**Reply by aisbergde** [reply]
not sure, maybe this way?

```
go2rtc:
  streams:
    kaninchen_onvif:
      - onvif://user:pass@192.168.178.122:8899
    kaninchen_onvif_sub:
      - onvif://user:pass@192.168.178.122:8899/Profile_001
```


```
  kaninchen_onvif:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kaninchen_onvif # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kaninchen_onvif_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
```
