### DISCUSSION TITLE
Play h265 with Browser

### DISCUSSION THREAD

**Discussion by Bettman66** [blakeblackshear/frigate#9374] [General]
Since I usually try not to use go2rtc, here are my experiences with playing h265 in the browser.
Hardware: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz   3.41 GHz
Software:
Windows 11, should also work with Windows 10:
Edge: Install Option 2 [[Free] HEVC Codec Packs for Windows 11](https://www.winxdvd.com/video-transcoder/install-hevc-codec-windows-11.htm)
Chrome: Settings -> System -> Use hardware acceleration if available
Firefox: [solution](https://github.com/blakeblackshear/frigate/discussions/9374#discussioncomment-8166911)

further tests follow

My Config with Reolink Cameras and frigate 0.13-rc1:

```
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

mqtt:
  topic_prefix: testfrigate
  client_id: testfrigate
  host: 192.168.22.15
  user: admin
  password: password


birdseye:
  enabled: False
  mode: continuous

cameras:
  rtsp_cam_1:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:password@192.168.22.79:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@192.168.22.79:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 360
    onvif:
      host: 192.168.22.79
      port: 8000
      user: admin
      password: password

  rtsp_cam_2:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:password@192.168.22.100:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@192.168.22.100:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 360

objects:
      track:
        - person
        - car

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 5
    post_capture: 120
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 14
```
