### DISCUSSION TITLE
Click Frigate Card To Nav To Different HASS Page?

### DISCUSSION THREAD

**Discussion by Lockie85** [blakeblackshear/frigate#9379] [Ask A Question]
Hey,

Within a HASS Dashboard View I've got a camera. What I'd like to achieve is when I press on the camera, I navigate to another HASS view. I'm sure it's somewhere, I'm just struggling to find the option and could do with some help. Here's an outline of my current definition for the frigate card, you'll see I've disabled all overlays and other interactions on purpose, so the view is clean and the hope is the only action for the card is to take me to the other view.

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.bedroom_3_stream
    hide: false
menu:
  style: none
  buttons:
    frigate:
      enabled: true
view:
  default: live
performance:
  profile: high
  style:
    border_radius: false
    box_shadow: false
media_gallery:
  controls:
    thumbnails:
      show_timeline_control: true
live:
  controls:
    thumbnails:
      mode: none
    title:
      mode: none
    builtin: false
```

**Comment by Lockie85** [comment]
@NickM-27 as you were very helpful with my last UI based question, perhaps you might know the answer to this one?

Many thanks.

**Comment by mdisabato** [comment]
Looking at the docs for the Lovelace card (https://github.com/dermotduffy/frigate-hass-card#actions) under the Actions section, it states "The format for actions is the standard Home Assistant [action format](https://www.home-assistant.io/lovelace/actions/#tap-action), with the exception of differences called out below." That means you can do a tap, hold or double-tap. Any of those can be set to "action: navigate" followed by where the navigation should go. I use that in several cards, one brings me to the Frigate web page using a web page card in a panel view. 

Let me know if you need any further help.

**Reply by Lockie85** [reply]
Thanks, but I can't seem to get it working. Here's my new example:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.bedroom_3_stream
    hide: false
tap_action:
  action: navigate
  navigation_path: /lovelace-minimalist/page_bedroom_3_stream
menu:
  style: none
  buttons:
    frigate:
      enabled: true
view:
  default: live
performance:
  profile: high
  style:
    border_radius: false
    box_shadow: false
media_gallery:
  controls:
    thumbnails:
      show_timeline_control: true
live:
  controls:
    thumbnails:
      mode: none
    title:
      mode: none
    builtin: false

```

Do you have an example you could share so I can see how your action section differs?

**Reply by Lockie85** [reply]
This doesn't appear to work.

**Comment by wiredolphin** [comment]
This seems not warking already, with the last version of the frigate card.

As for the documentation ([https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#user-content-card--view-actions](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#user-content-card--view-actions)):
> If an action is configured for both the whole card (view.actions) and a more specific view (e.g. live.actions) then the actions are merged...

we should be able to set an action for the whole card through `view.actions`, but neither of the below seems to work:
```
view:
  actions:
    tap_action:
      - action: navigate
        navigation_path: /path/to/other/dashboard
```

```
view:
  actions:
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: fullscreen
```
Not even does using the `live` specific view instead:

```
live:
  actions:
    tap_action:
      - action: custom:frigate-card-action
        frigate_card_action: fullscreen
```

UPDATE: After some furter tests I've discovered that the following will work if clicking an emtpy area of the menu row:
```
view:
  actions:
    tap_action:
      - action: navigate
        navigation_path: /path/to/other/dashboard
```
