### DISCUSSION TITLE
Why some events have very long recordings? How to limit recording time per event?

### DISCUSSION THREAD

**Discussion by aisbergde** [blakeblackshear/frigate#9387] [Ask A Question]
Often the recording of some events is very long (could be 25 minutes or longer). Events are showing as "in progress". It looks like nothing happens, but maybe something happens, what is interpreted by frigate as whatever: sometimes this could be just rain or snow or blinking (solar) lamps.

What are possible reasons for long recordings per event?

Can we limit the recording time per event?
If these are really continuing events, I would prefer to split them into separate events. Something like "create a new event after x minutes, if the event did not yet finish".

**Comment by aisbergde** [comment]
It looks like, my issues are related to wrong detected "stationary objects". (lamps are detected as persons, garbage in the garage is detected as person, ...)
I will check the docs, if there is something I could do. My issues are related to #9133

**Comment by NickM-27** [comment]
if you are having issues with false positives then https://deploy-preview-6262--frigate-docs.netlify.app/guides/false_positives would be a good read

**Comment by aisbergde** [comment]
I would like to combine a threshold with a required motion. This way, I could better exclude stationary false positive. Any ideas?

**Reply by NickM-27** [reply]
it's not clear what you mean, motion is already required for an object to be initially detected

**Reply by aisbergde** [reply]
"required motion" - the bounding box should be in motion, its position should change (however this could be defined) 
![image](https://github.com/blakeblackshear/frigate/assets/9020187/e7096cc0-db25-4cf1-a53c-6e956bdec483)
![image](https://github.com/blakeblackshear/frigate/assets/9020187/deea115a-8d55-4d37-8463-cf14af178a5f)
![image](https://github.com/blakeblackshear/frigate/assets/9020187/51920be7-25d8-4c34-b94e-23d87c2f45ef)
![image](https://github.com/blakeblackshear/frigate/assets/9020187/ea1db9ca-bcea-440e-b1db-176bffbeb0b8)

**Reply by NickM-27** [reply]
you can set `detect -> stationary -> max_frames` for `person` so the events are ended after a person is stationary for the defined amount of time

**Reply by aisbergde** [reply]
I try to understand, what happens, when I set `max_frames` for `person`, for example `1000`.
It is not very clear for me from the comment in the example:

```
detect:
  ...
  # Optional: Configuration for stationary object tracking
  stationary:
    ...
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person,
    # but leave car at the default.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
```

- will I still get an event, when a movement (and the box) first times is classified as object?
- will I get the event notification only in the case, if the box changes in these 1000 frames? And the event will not trigger, if it stays stationary?
- will it only stop to record? (but I think, this is defined as described here: https://docs.frigate.video/configuration/record/#what-do-the-different-retain-modes-mean)

In general, it looks like "stationary" is an important concept, and it is not so easy to get a full understanding on the fly.
What is the difference (What are the different consequences) between "track forever" and "should only be stationary for a limited amount of time"?

**Reply by NickM-27** [reply]
stationary object tracking allows frigate to efficiently track objects while they are stationary for long amounts of time. This is especially relevant for cars that are parked as it allows frigate to know that the car that is in the driveway is the same one that arrived 2 hours ago. This means frigate is aware of the object and only needs to periodically check that the object is still there. 

max_frames is a way to say "I know better, if X object type is stationary for Y frames then it is not a real object so frigate should be forced to forget it exists and end the event". In general this is not recommended, but your cameras seem to be a difficult case with such small objects so it may make sense for person

**Reply by aisbergde** [reply]
It looks like my cameras will just re-detect solar lamps as `person`, when they switch on and off or change brightness.
When I set `max_frames` I get even more events, because after `max_frames` I get a new detection of the lamp and a new event for 1000 frames. Maybe the default (track forever) could be better in my case, to receive fewer events.

And I should try to play with the https://docs.frigate.video/configuration/record/ settings and `mode: active_objects`, to record only the first few minutes of these events. Maybe these settings could have the desired effect (stop event recording if it is a stationary event):

```
    record:
      enabled: true
      events:
        retain:
          # default: 14
          mode: active_objects
```
