### DISCUSSION TITLE
Hiseeu camera compatibility

### DISCUSSION THREAD

**Discussion by imatech** [blakeblackshear/frigate#9395] [Ask A Question]
Can someone share a frigate yaml file who uses these cameras?

**Comment by allaboutmikey** [comment]
<Edited a couple of hours later, after I fixed up a few things in my config>
<twice! :)>

I have 6 Hiseeu cameras working very nicely on Frigate. 
I had to pre-configure the cameras with the painful windows software first, to set up DHCP, NTP, choose frame-rates, etc. 
It was a bit of a struggle, but I'm not sure if it was the cameras or just the software.
I'm sure there must be a better way, but I haven't looked into it.
As per docs, I am using the secondary stream for detection. That drops the resolution to 800x448 and the CPU usage (motion detection I think) from ~25% to ~2.5% for each camera.
The password seems to be the same for all cameras and nothing to do with anything I set in the software. Odd.
Anyway, the config file looks like this:
```
# yaml-language-server: $schema=http://frigate:5000/api/config/schema.json
database:
  path: /media/frigate/db/frigate.db

mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 800
  height: 448
  fps: 5

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True

cameras:
  back_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@cam_back_door/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
        - path: rtsp://admin:admin@cam_back_door/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
          roles:
            - record
    motion:
      mask:
        - 0,112,0,720,62,720,39,69
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@cam_driveway/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
        - path: rtsp://admin:admin@cam_driveway/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
          roles:
            - record
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@cam_front_door/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
        - path: rtsp://admin:admin@cam_front_door/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
          roles:
            - record
  south_wall:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@cam_south_wall/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
        - path: rtsp://admin:admin@cam_south_wall/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
          roles:
            - record
  front_left:
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@cam_front_left/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
        - path: rtsp://admin:admin@cam_front_left/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
          roles:
            - record
  back_yard:
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@cam_back_yard/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
          roles:
            - detect
        - path: rtsp://admin:admin@cam_back_yard/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
          roles:
            - record
```

**Reply by lun4cy** [reply]
What camera are you using?

**Comment by allaboutmikey** [comment]
I have some of each of these two:
Hiseeu HC615-P-3.6 5MP POE IP Camera
Hiseeu HB613 POE Camera
They both give nice bright clear images. Colourful in daylight, monochrome at night (they have inbuilt infrared illumination).
I've had them running for just over a month now and they work well.
For paranoia's sake, my router has firewall rules to deny access to or from the internet for all my cameras.

**Reply by niklasvogt13** [reply]
Which software did you use on windows to preconfigure your cameras?

**Reply by allaboutmikey** [reply]
The software linked from the Banggood store where I bought it.
https://xmeye.org/instructions-for-using-xmeye-pc-client/

**Comment by allaboutmikey** [comment]
I have since changed my configuration to use go2rtc. Here's an example config for each type of camera.
```
go2rtc:
  api:
    listen: :1984
  streams:
    # IPC_GK7205V200_G5C_S38, V5.00.R02.000659MB.10010.140d00..ONVIF 16.12
    back_door:
      - rtsp://admin:admin@cam_back_door/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
    back_door_detect:
      - rtsp://admin:admin@cam_back_door/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
```
...
```
    # IPC_GK7205V200_G4F_S38, V5.00.R02.000659N7.10010.140d00.S.ONVIF 21.06
    driveway:
      - rtsp://admin:admin@cam_driveway/user=admin_password=tlJwpbo6_channel=1_stream=0&amp;onvif=0.sdp?real_st
      - ffmpeg:driveway#audio=opus#video=h264
    driveway_detect:
      - rtsp://admin:admin@cam_driveway/user=admin_password=tlJwpbo6_channel=1_stream=1&amp;onvif=0.sdp?real_st
      - ffmpeg:driveway_detect#audio=opus#video=h264
```

The camera section now looks like this:
```
cameras:
  back_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/back_door_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/back_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
      hwaccel_args: preset-vaapi
```
...
```
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_detect # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
      hwaccel_args: preset-vaapi
```

I initially had the preset-generic-audio-aac set to something else (trying to pass the audio through directly), but that caused ffmpeg errors and flooded the logs with garbage. This setup works nicely and uses little CPU. The sound quality isn't all that great, but I wasn't expecting much anyway.
