### DISCUSSION TITLE
Node-RED Notification flow for Home Assistant Companion (IOS) users

### DISCUSSION THREAD

**Discussion by walthowd** [blakeblackshear/frigate#940] [Show and tell]
**Node-RED notification flow for IOS Users** - Send notification when an object is detected, 3D/force touch into notification for live view of camera, use actionable notification to send the clip (intelligently waits for clip to be ready) 

Example:
https://imgur.com/YB6hCT7

NodeRED Flow:
![Screenshot from 2021-03-26 12-19-51](https://user-images.githubusercontent.com/864569/112670945-8facb680-8e2f-11eb-8784-bfc888d05a95.png)

Requirements:

* Frigate HA Integration 
* Home Assistant Companion App (IOS)
* Home Assistant accessible from the internet (or via Nabu Casa)

 Installation:

Copy the flow to NodeRED (Hamburger Menu => Import):
https://paste.ubuntu.com/p/XD62VwNj7s/

Edit the first "Format notification" function node and add your external URL. Optionally, edit case statement to customize your camera to location mapping. (For example, I customize the camera.doorbell location to be "front door") 

Add following to your home assistant configuration for actionable notifications. 

```
ios:
  push:
    categories:
      - name: camera
        identifier: 'camera'
        actions:
          - identifier: 'SENDSTILLANDCLIP'
            title: 'Send still and video clip'
            authenticationRequired: false
```

Restart HA and sync push categories to your phone (HA App => App Configuration => Notifications => Categories)

That's it, you're all done!

For my personal setup, I also add in history checking of my external doors and current state of doors to limit alerts. For example, don't notify if someone is at the front door if the front door opened in the last five minutes.  I also use a input_boolean.person_notification to control if alerts are enabled, and add a actionable notifcation above called "SNOOZEPERSON" that temporarily disables notifications for four hours (useful when the kids are playing in the yard). 

I also push all Frigate clips to my Roku TV (if it's idle) as well and announce alerts on Google Homes / Amazon Dots.

That full flow, for advanced users, is here:
https://paste.ubuntu.com/p/bPjDwDC9ms/
