### DISCUSSION TITLE
Different masks on different cameras?

### DISCUSSION THREAD

**Discussion by Eiritj** [blakeblackshear/frigate#9403] [Ask A Question] [answered]
Hi all. 
I'm having some trouble understanding how I can place a mask on a single camera instead the mask being applied to of all of the cameras. 
I use the "Mask & Zone creator" and get a mask such as this that I want to apply to the camera "terrasse" only: 

`  mask:
    - 2560,641,2560,229,1634,230,1536,734,2120,1440`

The purpose is to not have Frigate record cat/ dog/ person within that area.

Could anyone help me place this mask in my config? Config below:

```
mqtt:
  enabled: True
  host: 192.168.1.111
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: yyy

detectors:
  coral_pci:
    type: edgetpu
    device: pci
    
model:
  width: 320
  height: 320

cameras:
  garasje:
    ffmpeg:
      output_args:
              record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://YYYY:XXXX@192.168.1.127:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution 
      # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1440
      # Optional: jpeg encode quality (default: shown below)
      quality: 100    
  
  #stue:
  #  ffmpeg:
  #    output_args:
  #            record: preset-record-generic-audio-aac
  #    inputs:
  #      - path: rtsp://YYYY:XXXX@192.168.1.76:554/h264Preview_01_main
  #        roles:
  #          - detect
  #          - record
  #  detect:
  #    enabled: True # <---- disable detection until you have a working camera feed
  #    width: 2560 # <---- update for your camera's resolution
  #    height: 1440 # <---- update for your camera's resolution 
  #    # Optional: Configuration for the jpg snapshots published via MQTT
  #  mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
  #    enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
  #    timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
  #    bounding_box: True
      # Optional: crop the snapshot (default: shown below)
  #    crop: False
      # Optional: height to resize the snapshot to (default: shown below)
  #    height: 1440
      # Optional: jpeg encode quality (default: shown below)
  #    quality: 100    

  inngang:
    ffmpeg:
      output_args:
              record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://YYYY:XXXX@192.168.1.229:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution 
      # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1920
      # Optional: jpeg encode quality (default: shown below)
      quality: 100    

  terrasse:
    ffmpeg:
      output_args:
              record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:YYYY:XXXX@192.168.1.227:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution 

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1440
      # Optional: jpeg encode quality (default: shown below)
      quality: 100

  Bakgaard:
    ffmpeg:
      output_args:
              record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://YYYY:XXXX@192.168.1.123:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution 

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1440
      # Optional: jpeg encode quality (default: shown below)
      quality: 100

objects:
  track:
    - person
    - cat
    - dog
  

record:
  enabled: True
  retain:
    days: 160
    mode: active_objects
  events:
    pre_capture: 15
    post_capture: 25
    objects:
      - motion
      - person
      - cat
      - dog
      - sports ball
    retain:
      default: 160
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 1920
  required_zones: []
  retain:
    default: 160
    objects:
      motion: 160
      person: 160
      cat: 160
      dog: 160
      default: 160
```

**Comment by NickM-27** [comment]
apply to the camera level instead of globally, so it would be

```yaml
cameras:

  terrasse:
    ffmpeg:
      output_args:
              record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:YYYY:XXXX@192.168.1.227:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution 
  
    objects:
      filters:
        dog:
          mask: 1,2,3,4
```

**Reply by Eiritj** [reply]
Hi Nick, thanks a lot! Bot-speed reply! 😄 

I added your suggestion for all the objects:
```
  terrasse:
    ffmpeg:
      output_args:
              record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:Gpr5005Reo@192.168.1.227:554/h264Preview_01_main
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution 

    objects:
      filters:
        dog:
          mask: 2560,641,2560,229,1634,230,1536,734,2120,1440
        cat:
          mask: 2560,641,2560,229,1634,230,1536,734,2120,1440
        person:
          mask: 2560,641,2560,229,1634,230,1536,734,2120,1440
```

Did I get you right?

Can I basically take all these config lines that I have at the bottom of my config and add under the individual cameras for more customization options?

```
objects:
  track:
    - person
    - cat
    - dog
  

record:
  enabled: True
  retain:
    days: 160
    mode: active_objects
  events:
    pre_capture: 15
    post_capture: 25
    objects:
      - motion
      - person
      - cat
      - dog
      - sports ball
    retain:
      default: 160
      mode: active_objects

snapshots:
  enabled: True
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 1920
  required_zones: []
  retain:
    default: 160
    objects:
      motion: 160
      person: 160
      cat: 160
      dog: 160
      default: 160
```

I
