### DISCUSSION TITLE
Frigate not recording persons

### DISCUSSION THREAD

**Discussion by Triskelen** [blakeblackshear/frigate#9422] [Ask A Question]
I have two of the same camera's : Foscam C2M 

The first one records the living area and the second one records the kitchen area
they both run with the same code in the config file.

```
mqtt:
  host :XXX
  port: 1883
  user: XXX
  password: XXX
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  LIBVA_DRIVER_NAME: i965

ffmpeg:
    hwaccel_args: preset-vaapi

birdseye:
  enabled: False

cameras:
  woonkamer:
    ffmpeg:
      inputs:
        - path: XXX
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 10
        required_zones:
          - "woonkamer_area"
          - "deur_area"
    mqtt:
      required_zones:
        - "woonkamer_area"
        - "deur_area"
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - "woonkamer_area"
        - "deur_area"
      retain:
        default: 15
        objects:
          person: 20
    objects:
      filters:
        person:
          mask: 1880,377,1890,475,1726,457,1717,351
    motion:
      mask:
        - 1920,876,1920,1080,0,1080,0,881
        - 1920,0,1920,119,0,126,0,0
    zones:
      woonkamer_area:
        coordinates: 0,901,1920,893,1920,73,0,70
        objects:  
          - person
        filters:
            person:
              min_score: 0.6
              threshold: 0.7
      deur_area:
          coordinates: 839,239,815,793,1211,799,1229,261
          objects:  
            - person
          filters:
            person:
              min_score: 0.6
              threshold: 0.7


  keuken:
    ffmpeg:
      inputs:
        - path: XXX
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 10
        required_zones:
          - "keuken_area"
          - "yard_area"
    mqtt:
      required_zones:
        - "keuken_area"
        - "yard_area"
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - "keuken_area"
        - "yard_area"
    objects:
      filters:
        person:
          mask: 951,398,951,608,855,597,873,394
          min_score: 0.5
          threshold: 0.6
    motion:
      mask:
        - 372,363,374,768,418,843,471,939,580,1080,0,1080,0,768,0,403,0,0,411,0
        - 1920,1080,1920,873,1795,849,1381,1080
        - 1272,190,1734,101,1920,0,421,0
    zones:
      keuken_area:
        coordinates: 1920,868,1796,843,1745,869,1580,970,1407,1080,930,1080,582,1080,540,1030,462,923,386,763,381,666,390,395,421,35,1283,198,1920,106
        objects:  
          - person
        filters:
            person:
              min_score: 0.6
              threshold: 0.7
      yard_area:
        coordinates: 759,182,749,533,740,953,711,955,603,973,500,982,478,946,429,847,435,147
        objects:  
          - person
        filters:
            person:
              min_score: 0.6
              threshold: 0.7



objects:
  track:
    - person
  filters:
      person:
          min_area: 5000
          max_area: 100000
          min_score: 0.6
          threshold: 0.7
```
          
The second i step in frame of the living area the frigate detects that there is a person there.
The kitchen camera is a whole other story i can step in frame dance around and it will still not detect that there is a person in the kitchen.

i even reduced the min_score and threshold for keuken camera but it's still the same
what is going wrong ?
