### DISCUSSION TITLE
Another question about stationary objects

### DISCUSSION THREAD

**Discussion by rocket59** [blakeblackshear/frigate#9426] [Ask A Question] [answered]
I have stationary object filtering set on a per camera basis like so:
 
>   detect:
>       enabled: True
>       fps: 5
>       stationary:
>         interval: 0
>         threshold: 50

However I'm still getting multiple events (generated in the camera tab) every few minutes that look like this:
![frigate 1](https://github.com/blakeblackshear/frigate/assets/5474400/9d9c2b09-8646-4e14-85c7-086e0101389e)

There is no actual snapshot but in its place is what looks like a broken image link. (there is a parked car in the zone that is generating these events). There is a reflection in the car's windscreen that shows the sky which I can only assume is generating the event, but why the 'broken image'?

The most recent image taken of this series has an "in progress" message in the left thumbnail but has an actual snapshot.

**Comment by NickM-27** [comment, marked as answer]
to be clear what you configured is not a stationary object filter, it just adjusts the characteristics of stationary object detection (and you are using the default values)

the broken image is likely because the event was deleted but the ui was loaded while it wasn't deleted and it did not refresh, I'd suggest checking the logs

**Reply by rocket59** [reply]
Got it - thanks again! So in order to reduce the number of unwanted snapshots I should increase the interval. I assume that the appropriate setting is a matter of trial and error?

**Reply by NickM-27** [reply]
no, "snapshots" are a single event. Frigate is designed to have a single event for each object so ideally there would be one in progress event for the car the entire time the car is there. I have not seen your config so it is possible there is some other config causing issues here, otherwise this is something that frigate 0.13 has improved upon

**Reply by rocket59** [reply]
Attached is the camera specific config. I don't have any global settings other than for the usual TPU/MQTT etc

As far as I can tell there's nothing particularly special about it. As I mentioned earlier the windscreen is in full view of the camera and shows a reflection of the sky. Would any movement over the reflection trigger a snapshot?

```
front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxx/1080p
          roles:
            - detect
            - record
    mqtt:
      enabled: True
      required_zones:
        - driveway
        - garden
    snapshots:
      enabled: True
      retain:
        default: 5
      required_zones:
        - garden
        - snapshots
    record:
      enabled: False
      events:
        required_zones:
        - driveway
        - garden
        retain:
          default: 10
    detect:
      enabled: True
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    objects:
      track:
        - person
        - car
        - umbrella 
      filters:
        car:
          mask: 130,228,304,170,713,114,866,112,1028,81,1280,287,1280,0,209,0,136,0,0,0,0,290
        person:
          min_score: 0.6
          threshold: 0.7
          mask: 130,228,304,170,713,114,866,112,1028,81,1048,160,1058,207,1087,128,1280,287,1280,0,209,0,136,0,0,0,0,290
        umbrella:
          mask: 130,228,304,170,713,114,866,112,1028,81,1280,287,1280,0,209,0,136,0,0,0,0,290
    motion:
      mask:
       - 1280,0,1280,253,1132,155,1013,99,882,101,868,136,716,138,710,121,311,163,0,247,0,0
       - 228,316,559,376,860,392,954,584,804,589,544,588,244,591,0,596,0,269,71,252,34,468,40,480
    zones:
      driveway:
        coordinates: 892,434,986,720,1280,720,1280,615,1112,391,949,208,752,214,819,327
        objects:
            - car
            - person
            - umbrella
      garden:
        coordinates: 88,359,343,318,575,410,876,412,737,188,344,224,73,263
        objects:
            - person
            - umbrella
      snapshots:
        coordinates: 672,441,941,587,1280,552,1280,280,1072,113,936,172,577,187
```
