### DISCUSSION TITLE
Frigate RTSP Server

### DISCUSSION THREAD

**Discussion by tliaresq** [blakeblackshear/frigate#9429] [General]
Is it possible for Frigate to act as an RTSP server and accept an RTSP stream from something that is not a server itself? 

For example if I want to display a stream coming directly from an ffmpeg command (The below example does not work):
ffmpeg command:
`ffmpeg -re -i video.mp4 -c copy -f rtsp rtsp://localhost:8554/mystream`

config.yml:
```
mqtt:
  enabled: False

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/mystream
          roles:
            - record
```

I do not think it is supported based on the docs but I just wanted to confirm here!
