### DISCUSSION TITLE
output_args individually for stream

### DISCUSSION THREAD

**Discussion by albotroz** [blakeblackshear/frigate#9439] [Ask A Question] [answered]
I'm a bit overwhelmed right now with the global vs. individual camera settings.
I want no sound to be recorded for the camera in mainstream, but sound to be output in the livestream (substream).

The current situation is that sound can be heard in mainstream and substream.

What is the recommendation with the setting?
Remove this?
      output_args:
        record: preset-record-generic-audio-copy
And then instead put it under inputs like this?

```
front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front # RTSP Stream High Res
          input_args: preset-rtsp-restream
          roles:
            - record
          output_args: preset-record-generic
        - path: rtsp://127.0.0.1:8554/front_sub # RTPS Stream Low Res
          input_args: preset-rtsp-restream
          roles:
            - detect
          output_args: preset-record-generic-audio-copy
```

My actual settings:
```
go2rtc:
  streams:
    front:
      - rtsp://NAME:PW@192.168.xxx.xxx:554/h264Preview_01_main
      - "ffmpeg:front#audio=opus" 
    front_sub:
      - rtsp://NAME:PW@192.168.xxx.xxx:554/h264Preview_01_sub
      - "ffmpeg:front_sub#audio=opus"
```

```
cameras:
  # Cameraname
  front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front # RTSP Stream High Res
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub # RTPS Stream Low Res
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True                                                        
      width: 640
      height: 360
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    snapshots:
      enabled: True
      retain:
        default: 5
    record:
      enabled: True
      events:
        retain:
          default: 5
        pre_capture: 3
        post_capture: 10
    live:
      stream_name: front_sub
```
