### DISCUSSION TITLE
Home assistant camera resolution?

### DISCUSSION THREAD

**Discussion by intrinseca** [blakeblackshear/frigate#944] [General]
I'm using the Home Assistant custom integration. The camera streams inside hass are at a much lower resolution than the camera is providing. I have a main and substream running into frigate, and the RTMP role is set to the main stream. Is this a intentional, a bug, or a misconfiguration? Wanted some input before raising an issue.

**Comment by blakeblackshear** [comment]
If you don't have the stream component enabled in homeassistant, it will attempt to play an mjpeg feed, and that will be lower resolution. Make sure you have stream enabled to actually play from the rtmp feed.

**Reply by intrinseca** [reply]
Ah yes I don't have that on because it wasn't playing nicely with iOS safari or Firefox. I will investigate again.

**Reply by SaschaHenning** [reply]
Question: is there a documentation on how to configure this? I have stream enabled and set rtmp for one of my cams but see not difference from the other cams in HA

**Reply by iMiMx** [reply]
I needed to set the below in the lovelace config:

`camera_view: live
`

So I have the below in a vertical stack, with the Canary in-card addon:

```
cards:
  - aspect_ratio: 100%
    entity: camera.outside_front
    type: picture-entity
    name: Outside - Front
    camera_view: live
  - aspect_ratio: 100%
    entity: camera.outside_back
    type: picture-entity
    name: Outside - Back
    camera_view: live
type: vertical-stack
in-card: true
```
