### DISCUSSION TITLE
New firmware for reolink RLC-410-5MP

### DISCUSSION THREAD

**Discussion by dison4linux** [blakeblackshear/frigate#9454] [General]
I have two reolink RLC-410-5MP cameras that I was just about ready to throw in the bin, but I just went out and checked and they do have a new firmware (v3.0.0.2356_23062000) on their [site](https://reolink.com/download-center/).  
In the past I had been using the [recommended HTTP-FLV config](https://deploy-preview-6262--frigate-docs.netlify.app/configuration/camera_specific#reolink-cameras) for these cameras but still had the occasional hiccup in the logs and I was tired of it so I was just going to toss them.  I'm wondering if anyone has any experience with this new version and Frigate?
Are you still using HTTP-FLV or are you trying RTSP?
I'm going to give these a try with RTSP for a few days just to see what happens.
I will caution anyone thinking of upgrading their cameras, this seems to be a pretty major upgrade and the cameras lose HTTP access after the upgrade.  You have to use the reolink client on Windows to change the config to enable HTTP (and RTSP).
If it helps, here's the output of FFProbe in RTSP mode:
```
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1920
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: Unknown

Audio:

Codec: AAC (Advanced Audio Coding)
```

**Comment by bluearcher-bc** [comment]
Reolink firmware is a rabbit hole mixed with a train wreck, and it's unclear from your post what your exact concerns are, but there is a beta firmware link floating around (at least for the RLC-520, which I think are the same or similar firmware) where they fixed the iframes issues that were plaguing a lot of NVRs. It makes iframe configurable to 1 so that you don't have issues with smearing just because you miss an iframe. It's important to note, that even after the update, this setting is not available on the HTTP admin page, you can only set it using the Reolink app under Device > Stream. I use the Windows app, not sure if it's applicable to other OS.

firmware on my 520s is v3.0.0.660_21111507, which is not available on their public downloads site, and it may never be, since the non-A cameras aren't supported anymore. your 23062000 looks like it might be "newer" but I don't know anything about that one or what is supposed to be fixed. the iframe setting is important, though.

**Comment by bluearcher-bc** [comment]
Also, this is my config in Frigate, I am using go2rtc:

```
go2rtc:
  ffmpeg:
    http-reolink: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i {input}"
```

**Reply by nmschulte** [reply]
This!  After deciphering all the nuggets of information and detail throughout the various doc pages, I determined that to use restream w/ reolink, requires some finangling -- you have to avoid the "use wallclock 1" option but add the "low latency" options (and I also opted for `-f live_flv`) to `go2rtc`, and some of the styles in the docs simply don't work.

Bad form:
```yaml
go2rtc:
  streams:
    camera_1:
      - rtmp://camera_1.domain:1935/...
      - "ffmpeg:camera_1#input=...#hardware=vaapi"
```

I use the RTMP stream, as I had best results with it in ZoneMinder.  It seems to me like the `http://` protocol is a wrap upon whatever is serving `rtmp://` protocol and will have more (likely negligible) overhead -- I'd be happy to be proven wrong, but it doesn't seem to much matter from my experience: both streams still output wonky timestamps/PTS.

I use the 5MP stream for both detect and record, with the single restream, w/ VAAPI hardware accel decode for detect.

_Model: RLC-410-5MP
UID: ...
Build No.: build 20092900
Hardware No.: IPC_515B16M5M
Config Version: v3.0.0.0
Firmware Version: v3.0.0.111_20092900
Details: IPC_515B16M5MS10E1W01100000001_

**Reply by adb045** [reply]
I am using the same camera with the same firmware but in Frigate. Having issues with stream corruption, especially at night. 

Could you share the flags you used to to avoid the "use wallclock 1" option but add the "low latency" options?

**Reply by lawrence-jeff** [reply]
I don't use any wallclock flags, but this config is very stable for restream

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay
    -strict experimental
go2rtc:
  streams:
    driveway:
      - ffmpeg:http://192.168.0.140/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxx#video=copy#audio=copy#audio=opus
    driveway_small:
      - ffmpeg:http://192.168.0.140/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
    driveway_entry:
      - ffmpeg:http://192.168.0.140/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx#video=h264#raw=-vf
        crop=500:300:600:1

**Comment by bluearcher-bc** [comment]
https://github.com/AT0myks/reolink-fw-archive/

**Comment by dison4linux** [comment]
> it's unclear from your post what your exact concerns are

I had tried using RTSP in the past and things looked promising for the first 12-18 hours but then I experienced the "train wreck" you mentioned.  I'm trying RTSP again on the newer firmware and again things look promising out of the gate, but if someone else has already tried and encountered the same issues, that would save me the attempt.

**Comment by dison4linux** [comment]
Unfortunately RTSP is still unreliable with the new firmware.
On the plus side, I've had them configured as HTTP-FLV for a couple days now and I don't have any errors in the Frigate logs yet.

**Reply by lawrence-jeff** [reply]
Have you tried the RTMP feed, I generally have better luck with that on mine. RTSP seems to go wonky with green blocks frequently, and HTTP works but seems to use more CPU (with all settings the same).

I'm upgrading my firmware now to this new version to see if that changes anything.

**Comment by USBAkimbo** [comment]
I also upgraded one of my cameras (`RLC-410` and `IPC_51516M5M`) and found the same issue - luckily their app also works for re-enabling HTTP and RTSP

I only knew there was an update because I added the cameras to Home Assistant for live view and it said there was an update

Did Reolink pull this firmware? I can't find it on their website anymore

https://reolink.com/download-center/ and searching for `RLC-410` and `IPC_51516M5M` returns `V3.0.0.136_20121100` with date `11 Dec. 2020 Updated`

Either way, these cameras should be on their own VLAN with no internet access, except for DNS and NTP only so time can be updated

Here is my working config using 4 cameras as a reference

```
version: 0.15-1

# https://docs.frigate.video/configuration/

# Disable TLS as we're using a reverse proxy
tls:
  enabled: false

# Turn off MQTT because I'm not using Home Assistant
mqtt:
  enabled: false

# Keep 24/7 recorded video for 30 days
record:
  enabled: true
  retain:
    days: 30
    mode: all

# Set the live view to all cameras all the time
birdseye:
  mode: continuous

detect:
  width: 640
  height: 480

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog

# Unused - using Coral instead
##### Start of OpenVino config for CPU detection #####

#detectors:
#  ov:
#    type: openvino
#    model_path: /openvino-model/ssdlite_mobilenet_v2.xml
#model:
#  width: 300
#  height: 300
#  input_tensor: nhwc
#  input_pixel_format: bgr
#  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

##### End of OpenVino config for CPU detection #####

# Coral AI USB accelerator for object detection
detectors:
  coral:
    type: edgetpu
    device: usb

# Go2rtc config
go2rtc:
  streams:
    c1-side:
      - ffmpeg:http://10.10.8.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_C1_PASS}#video=copy#audio=copy#audio=aac
    c2-garden:
      - ffmpeg:http://10.10.8.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_C2_PASS}#video=copy#audio=copy#audio=aac
    c3-garage:
      - ffmpeg:http://10.10.8.13/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_C3_PASS}#video=copy#audio=copy#audio=aac
    c4-front:
      - ffmpeg:http://10.10.8.14/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_C4_PASS}#video=copy#audio=copy#audio=aac

ffmpeg:
  input_args: preset-rtsp-restream
  output_args: 
    record: preset-record-generic-audio-copy

cameras:
  c1-side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/c1-side
          roles:
            - detect
            - record
    objects:
      filters:
        car:
          mask: 0.265,0.446,0.551,0.598,0.419,0.996,0.004,0.987,0.033,0.818

  c2-garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/c2-garden
          roles:
            - detect
            - record

  c3-garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/c3-garage
          roles:
            - detect
            - record
    objects:
      filters:
        car:
          mask: 0.427,0.456,0.819,0.431,1,0.665,1,1,0.463,1

  c4-front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/c4-front
          roles:
            - detect
            - record
    objects:
      filters:
        car:
          mask: 0,0.654,0.175,0.513,0.596,0.989,0.148,0.994

camera_groups:
  Cameras:
    order: 1
    icon: LuAirplay
    cameras:
      - c1-side
      - c2-garden
      - c3-garage
      - c4-front
```
