### DISCUSSION TITLE
Frigate NVR entity

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#9465] [General]
# Hi.

## I have one question and I'm not sure if `I did something wrong` or Frigate NVR does not allow/doesn't have this in entity?

`I have it set to view objects through coral TPU, which works almost perfectly!`

![Frigat NVR](https://github.com/blakeblackshear/frigate/assets/40424965/33592c04-78d1-4a0f-8238-bad19ea5abe3)

`I found this one and as much as I tried it's not the same`

![Frigat camera-Motion](https://github.com/blakeblackshear/frigate/assets/40424965/eae5b5cc-569e-4309-ae79-5d444641e633)

# I want to say that I can't find an entity anywhere that triggers the creation of clips and videos for storage on disk through object recognition.

## I would like to have a condition card that would monitor the sensor, `which I can't find`, so I'm currently using motion to show me a video on the card (floor plan) if an object that is moving is detected.

`example of the code in the card:`

```yaml
              - type: conditional
                conditions:
                  - condition: state
                    entity: binary_sensor.jedilnica_motion
                    state: 'on'
                card:
                  type: custom:webrtc-camera
                  card_mod:
                    style: |
                      :host {
                        position: absolute !important;
                        heigh: auto;
                        max-width: 18vw !important;
                        top: 100px !important;
                        left: 40px !important;
                        z-index: 1 !important;
                        }
                  url: rtsp://192.168.1.42:8554/Jedilnica
                  ui: true
                  poster: /local/img/fp/prosojna.png
                  muted: true
                  background: true
                  intersection: 0.75
                  mode: webrtc,webrtc/tcp,mse,hls,mjpeg
```

**Comment by NickM-27** [comment]
It's not clear to me what you're trying to accomplish. The motion entity is just basic motion

**Reply by Trzinka** [reply]
Yes. 

Frigate, on the other hand, `uses object recognition` for recording and storage, which is `not equivalent to these sensors`, which I see as entity. 

`These entities are before passing them through the filter/calculation if I understood correctly!`

**Reply by NickM-27** [reply]
The occupancy sensors are exactly the same as frigates object detection, they are only triggered after the filters

**Reply by Trzinka** [reply]
# It's not the same!

## This checks if the object is in the field of view of the camera, and since this condition is followed by another condition, whether the object is moving, the real state is not displayed.

## The car in the picture is `standing/does not move` on a frigate, but the object is detected!!

`I'm not sure what the pre-requisite is, but it doesn't matter.`

# If I understand correctly, the sensor that gives the command to start recording is missing. `But I could also be wrong.`

**Reply by NickM-27** [reply]
There is no sensor because there is no command to start recording. Recordings are saved when events are created, events are created when objects are detected and that is what the sensor represents as well.

**Reply by Trzinka** [reply]
But now I'm confused. Looking at this card:
### Diane cam `shows recording`
### All occupancy `is clear`
### car `is active`
### motion `is clear`
### motorcycle `is active // is old picture during the day. It's night now`
### person `is active // is old picture during the day. It's night now`

![Frigate entyti](https://github.com/blakeblackshear/frigate/assets/40424965/8dca348c-c5a5-4362-baba-caa17459ffd0)

# The last recording was made 22 minutes ago

![Frigat card](https://github.com/blakeblackshear/frigate/assets/40424965/be06fb15-6811-41c6-bb6c-54146ec1bc19)

**Reply by Trzinka** [reply]
# There is no logic here

**Reply by Trzinka** [reply]
# Sorry for the question
### 1.) do you participate in the creation of the program?
### 2.) Do you just want to help me?

**Reply by NickM-27** [reply]
You are looking at the picture entities which don't represent what I am referring to. I am saying you should use the occupancy entity. 

Also `recording` just means that the camera has recording enabled but that it is saving recordings this second.

**Reply by Trzinka** [reply]
# Hi! Thanks to replay.

`Let's look at this situation:`

![Frigate-Cards-](https://github.com/blakeblackshear/frigate/assets/40424965/a4abbf61-5e8a-459f-97d3-a134c0838f6a)

**In the left picture you can see that the last actual recording was made 22 minutes ago! "let's ignore that he is wrongly recognized as a person"**

**On the right picture, let's see an example of a camera called Diane:**
`Does it show as you wrote that recording is enabled? (why, or rather, the sensor is missing when it is actually recording)`
`After that, it shows that the camera has detected a car object (ok, let's say this information is "interesting")`
`This makes All **** useless! (misleading but true)`
`then if you look at motion (which really doesn't detect motion because the car is parked)! By the way, motion detects the movement of the shadow of the branches on the dining room camera in the wind, but since the object does not move, the recording does not start!`

# Now the crux of the question:
`- which sensor to use that actually triggers the recording?`

**Reply by NickM-27** [reply]
If I had to guess there is probably an in progress event further down in the events page for the car that is currently detected. 

Only the `motion` entity has to do with motion. Occupancy entities consider stationary objects as well. 

There is no "recording" entity, why are you specifically looking for this entity vs just an entity that shows what is detected?

**Comment by Trzinka** [comment]
# That's what I'm looking for (just an entity that shows what is detected)!!!

`However, no entities match the criteria I'm looking for!`

### When I look at the current entity from the camera, there is no entity that starts the actual recording (recorded = set of entity conditions).

`As far as I can see now, I should make a template that would look if entity: motion is detected, then look at the occupancy status of each object (car, bike, person, motorcycle) and from that I should get the conditions for recording!`

# Am I right or did I miss something?

**Reply by NickM-27** [reply]
>That's what I'm looking for (just an entity that shows what is detected)

That is exactly what the integration occupancy sensors are

> I should make a template that would look if entity: motion is detected, then look at the occupancy status of each object (car, bike, person, motorcycle) and from that I should get the conditions for recording!

And this is not "just an entity that shows what is detected" so it is very confusing what you are looking for.

**Reply by Trzinka** [reply]
# Let's see what the conditions in frigate.yaml are, for the actual recording to begin!

```yaml
detect:
  enabled: True
  width: 1920
  height: 1080
  fps: 10
  max_disappeared: 30 
  stationary:
    interval: 10
    threshold: 30

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
   filters:
    person: 
      threshold: 0.65
    car:
      threshold: 0.65
    bicycle:
      threshold: 0.65
    motorcycle:
      threshold: 0.65    

records:
   enabled: True
   retain:
     days: 31
     mode: active_objects
   events:
     pre_capture: 2
     post_capture: 10
     retain:
       default: 31
       mode: active_objects

cameras:
  Jedilnica:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/Jedilnica-HD     # Full resolution 1920 X 1080
          roles:
            - record
            - detect
            - clips
      output_args:
        record: preset-record-generic-audio-aac
    best_image_timeout: 10
```

# Isn't that the setting I'm talking about?
