### DISCUSSION TITLE
Different hardware acceleration for detect and record stream possible?

### DISCUSSION THREAD

**Discussion by Tibladar** [blakeblackshear/frigate#9473] [Ask A Question] [answered]
Is it possible to have different hardware acceleration for detect and record stream?

I have a Reolink RLC-811A which provides h264 for substreams and h265 for the main stream.

It looks like I can only use one `hwaccel_args` for both streams resulting in one stream decoding with the wrong decoder.

Config:
```
go2rtc:
  streams:
    Basket:
      - rtsp://username:password@IP/h265Preview_01_main
    Basket_sub:
      - "ffmpeg:http://IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"

cameras:
  Basket:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h265
      inputs:
      - path: rtsp://127.0.0.1:8554/Basket_sub
        roles:
        - detect
        input_args: preset-rtsp-restream
      - path: rtsp://127.0.0.1:8554/Basket
        roles:
        - record
        input_args: preset-rtsp-restream
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      width: 896
      height: 672
    record:
      enabled: true
```

ffmpeg command line (both using `hevc_v4l2m2m`):

```
ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 hevc_v4l2m2m -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -stimeout 5000000 -i rtsp://127.0.0.1:8554/Basket_sub -r 5 -vf fps=5,scale=896:672 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:

ffmpeg -hide_banner -loglevel warning -threads 2 -c:v:1 hevc_v4l2m2m -user_agent FFmpeg Frigate/0.13.0-49814b3 -rtsp_transport tcp -stimeout 5000000 -i rtsp://127.0.0.1:8554/Basket -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Basket@%Y%m%d%H%M%S%z.mp4
```

**Comment by NickM-27** [comment, marked as answer]
There is no decoding done for recordings so it shouldn't be an issue. But in any case you can set hwaccel args at the stream level 

```

cameras:
  Basket:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/Basket_sub
        roles:
        - detect
        input_args: preset-rtsp-restream
        hwaccel_args: preset-rpi-64-h264
      - path: rtsp://127.0.0.1:8554/Basket
        roles:
        - record
        input_args: preset-rtsp-restream
        hwaccel_args: preset-rpi-64-h265

```
