### DISCUSSION TITLE
Allow the ability to import global settings at a camera level so you can add to the global settings

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#9489] [Ideas]
Some times its really handy to set a bunch of setting at a global level as most of your settings might be universal to all your cameras. For example on my cameras the time is always in the top right corner. I can set a global Motion Mask to mask out this area. It makes sense to set it at a global level becuase every camera I have has this time stamp on it. The idea i have occures when on one camera you want to also mask off a tree or a bush. If I set a mask at the camera level to mask off this bush it overrides the global settings for the time (This is expected behaviour) Now I have to copy down the mask form the global settings and then add to that the mask for my bush and my tree.

It would be really handy to have an option like `- import` that could only be used on any camera level setting. That import command would take the global setting and apply it to the camera and then add any camera level settings to the global creating a combined setting that uses both global settings and camera level settings. Extreamly useful!

So for instance with my setup I would have a global setting to mask off the time in the top right corner and then on the few one off cameras that I have to mask somthing else off i would mask off those items but also import the global setting to mask off the time

IE
```
motion:
  mask:
    # Mask off the top right corner of all camera as this is where the time is and is always moving
    - 1364,76,1894,68,1891,0,1361,0

cameras:
  Garage:
     motion:
       mask:
          - import # Import any global masks
          - 1920,1080,1806,1080,1800,1053,1805,992,1803,899,1838,797,1920,761 # Mask off the bush
```
