### DISCUSSION TITLE
Update The Config file Page to show Camera names with spaces

### DISCUSSION THREAD

**Discussion by MrCaspan** [blakeblackshear/frigate#9490] [Ideas]
On the following documentation page [https://docs.frigate.video/configuration/](https://docs.frigate.video/configuration/) Where it has camera name:

```
# Required
cameras:
  # Required: name of the camera
  back:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: True
```

This section should be updated with a caemra name that makes more sense than 'back' and describe how to deal with cameras that might have spaces in the name IE.. Front Door, Front Lawn, South Side of House, Back Pool Gate

An example change would look like this
```
# Required
cameras:
  # Required: name of the camera. 
  # NOTE: Camera names cannot have spaces, use an underscore in place of a space
  Back_Yard:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: True
```

Much easy to follow for new people I think
