### DISCUSSION TITLE
Help with setting up rtsp restream

### DISCUSSION THREAD

**Discussion by rocket59** [blakeblackshear/frigate#9549] [Ask A Question] [answered]
Frigate 0.12.1 installed in docker (standalone).

In the config file I have this included from my wyze camera (BTW this is a go2rtc stream from the camera itself):

```
go2rtc:
  streams:
    back_yard:
      - rtsp://user:passwd@camera-ip:8554/1080p



cameras:
  back_yard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```
I can see the mse stream in the camera live view within Frigate so all ok there.

However for some reason I can't get to the go2rtc streams @ http://frigate_ip:5000/api/go2rtc/streams (404 not found) nor can I access the restream @ rtsp://frigate_ip:8554/back_yard via VLC (note: no authentication set).

Any help would be much appreciated!

**Comment by NickM-27** [comment]
What is the docker config

**Comment by rocket59** [comment]
Here it is

```
frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: always
    shm_size: "95mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

    volumes:
      - /etc/localtime:/etc/localtime
      - /home/frigate/config.yml:/config/config.yml
      - /mnt/frigatedata:/media/frigate

    ports:
      - 5000:5000
      - 1935:1935
    environment:
       FRIGATE_RTSP_PASSWORD: “password”
```
