### DISCUSSION TITLE
Object mask not working?

### DISCUSSION THREAD

**Discussion by a-bali** [blakeblackshear/frigate#9591] [Ask A Question] [answered]
In a certain area of one of my camera's view I frequently get a false positive for a person due to a tree that looks very much alike. Therefore I would like to mask that area for the person object type. I have this in my config (excerpt), but I still get the false positives. Any ideas why this configuration does not work?

```
cameras:
  street_camera:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - record
        - path: ...
          roles:
            - detect
    detect:
      width: 640
      height: 360
    zones:
      street:
        coordinates: 0,161,640,123,640,0,0,0
      inside:
        coordinates: 640,360,640,139,0,176,0,360
    motion:
      mask: # mask for timestamp
        - 398,38,625,38,625,19,398,19
    objects:
        filters:
          person: # mask for false positives
            mask: 0,0,261,0,263,45,0,74
    live:
      stream_name: street_camera

detectors:
  detector_name:
    type: cpu

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog

```
