### DISCUSSION TITLE
Config file for people who dont want to learn rocket science?

### DISCUSSION THREAD

**Discussion by CurlyFlow** [blakeblackshear/frigate#9593] [General]
Cool thing, really, ive even got it working the first time with nvidia detection and everything.

But can i suggest something?

Can we have a minimal config file? I didnt changed anything, but everything is broken and he throws some errors out i dont want to have anything to do.

I dont need detection, but there is no way to disabled it... 

Cant we have a config just for CAMERA RECORD when movement without detection and everything? Is detection needed for detecting movement? (i dont want to know if its a car or not)

(the cpu detect part was added after having problems with trt models) 

If there are steps to do after adding docker... why is that not automatic? (like the trt models thing) It would help people who are not that technical to use your product.

Maybe just offer some example files for 1 camera 

with cpu detection
with nvidia detection
with coral detection

So you could start fast and keep chaning the default config file....

```
mqtt:
  enabled: False

cameras:
  Parkplatz: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://123:123@123.168.0.112:1338/11/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      enabled: True
      retain:
        days: 60
        mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        mode: motion
        default: 3
        objects:
          person: 30
          car: 30
          motorcycle: 30

detectors:
#  tensorrt:
#    type: tensorrt
#    device: 0 #This is the default, select the first GPU
  cpu6: 
    type: cpu
    num_threads: 4


model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
  
ffmpeg:
  hwaccel_args: preset-nvidia-h265
  
objects:
  track:
    - person
    - car
    - motorcycle
database:
  path: /config/frigate.db
```

edit:
Btw your "code" system in here is very well broken lol

edit2: after nick posted it, it worked...

**Comment by NickM-27** [comment]
>I dont need detection, but there is no way to disabled it...

Sure there is 

```
detect:
  enabled: false
```

Also the docs do have example configs https://docs.frigate.video/configuration/

**Reply by CurlyFlow** [reply]
I wouldnt write here, if there were sufficient???

Also if u disable detect, still high cpu.

Am i right that if i use a coral usb, i dont need to fiddle around with those trt models?

**Reply by NickM-27** [reply]
If you use a coral you don't need to use trt models, that is correct.

**Reply by CurlyFlow** [reply]
good i ordered one, i got the message like a version mismatch (and yes i recreated the trt models) with nvidia 1080ti

It was working relativly long without problems and then yesterday or so it keeps looping in a restart because of trt...

**Reply by CurlyFlow** [reply]
currently im using 

```
mqtt:
  enabled: False

cameras:
  Parkplatz: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://123:123@123.168.0.112:1338/11/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: True
      retain:
        days: 60
        mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        mode: motion
        default: 3
        objects:
          person: 30
          car: 30
          motorcycle: 30

detectors:
#  tensorrt:
#    type: tensorrt
#    device: 0 #This is the default, select the first GPU
  cpu1:
    type: cpu


#model:
#  path: /trt-models/yolov7-tiny-416.trt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 416
#  height: 416
  
ffmpeg:
  hwaccel_args: preset-nvidia-h265
  
#objects:
#  track:
#    - person
#    - car
#    - motorcycle
database:
  path: /config/frigate.db
```

till the coral thing is here

do you have any suggestion? Like how could i add pip? https://github.com/blakeblackshear/frigate/issues/8534

**Reply by CurlyFlow** [reply]
I changed it now to (and pip works :)) is it possioble to disable the other methods? I jsut want to use webrtc?

```
mqtt:
  enabled: False

cameras:
  Parkplatz: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://123:123@123.168.0.112:1338/11/ # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: True
      retain:
        days: 60
        mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        mode: motion
        default: 3
        objects:
          person: 30
          car: 30
          motorcycle: 30

detectors:
#  tensorrt:
#    type: tensorrt
#    device: 0 #This is the default, select the first GPU
  cpu1:
    type: cpu


#model:
#  path: /trt-models/yolov7-tiny-416.trt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 416
#  height: 416
  
ffmpeg:
  hwaccel_args: preset-nvidia-h265
  
#objects:
#  track:
#    - person
#    - car
#    - motorcycle

go2rtc:
  streams:
    Parkplatz: rtsp://admin:0cX2Yw4t@192.168.0.112:1338/11/#media=video#backchannel=0


database:
  path: /config/frigate.db
```
