### DISCUSSION TITLE
Frigate NVR template sensor/automation/MQTT or otherwise SHOW STATUS IF ALL CONDITIONS ARE MET!!!

### DISCUSSION THREAD

**Discussion by Trzinka** [blakeblackshear/frigate#9604] [Ask A Question]
**Hi it's me again!**

# I'm linking to disscusion https://github.com/blakeblackshear/frigate/discussions/9465 because I haven't found a satisfactory solution yet, especially since the `Frigate NVR upgrade`, changed the operation of the `motion sensor`!

`I was thinking according to the scheme which I don't know if it is genuine/actual condition:`

![Video pipeline _ Frigate](https://github.com/blakeblackshear/frigate/assets/40424965/3fa44c07-8d8f-4956-982c-feebc760734e)

### After upgrading the Frigate NVR, motion stopped working for me because I didn't read the instructions about the key changes, which I supplemented with the help of disscusion https://github.com/blakeblackshear/frigate/discussions/9557

**Then I watched our video for a possible solution at https://www.mostlychris.com/frigate-nvr-updates/**

`Since I have no programming knowledge and would not like to guess what the code means, I am attaching it only as a possible solution direction.`

```yaml
alias: Frigate Driveway w Image
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: driveway
    value_template: "{{ value_json['after']['camera'] }}"
    id: frigate-event
    variables:
      after_zones: "{{ trigger.payload_json['after']['entered_zones'] }}"
      before_zones: "{{ trigger.payload_json['before']['entered_zones'] }}"
      camera: "{{ trigger.payload_json['after']['camera'] }}"
      id: "{{ trigger.payload_json['after']['id'] }}"
      label: "{{ trigger.payload_json['after']['label'] }}"
      score: "{{ trigger.payload_json['after']['score'] }}"
      time_clip_start: "{{ trigger.payload_json['after']['start_time'] - 10.0 }}"
condition:
  - condition: template
    value_template: >-
      {{ not this.attributes.last_triggered or (now() -
      this.attributes.last_triggered).seconds > cooldown }}
    alias: Wait for cooldown
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.payload_json['type'] == 'new' }}"
      - condition: template
        value_template: "{{ trigger.payload_json['before']['entered_zones'] | length == 0 }}"
  - condition: template
    value_template: "{{ trigger.payload_json['after']['entered_zones']|length > 0 }}"
  - condition: template
    value_template: >-
      {{ ["driveway_left_side", "driveway_right_side"] | select("in",
      after_zones) | list | length > 0 }}
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] != 'car' }}"
action:
  - choose:
      - alias: Frigate Event
        conditions:
          - condition: trigger
            id: frigate-event
        sequence:
          - variables:
              id: "{{ trigger.payload_json['after']['id'] }}"
          - alias: Notify on new object
            choose:
              - conditions: []
                sequence:
                  - service: notify.mobile_app_sm_s906u1
                    data:
                      message: Driveway Motion
                      title: Driveway Alert
                      data:
                        image: "{{base_url}}/{{id}}/thumbnail.jpg?format=android"
                        clickAction: "{{action_url}}/api/events/{{id}}/clip.mp4"
                        actions:
                          - action: URI
                            title: View Clip
                            uri: "{{action_url}}/api/events/{{id}}/clip.mp4"
                        channel: drive_Cam
                        priority: high
                        ttl: 0
                  - service: notify.hass_agent_superman
                    data:
                      message: Driveway Motion
                      title: Driveway Alert
                      data:
                        image: "{{base_url}}/{{id}}/thumbnail.jpg"
mode: parallel
variables:
  base_url: >-
    https://{mynabucasa_URL}.ui.nabu.casa/api/frigate/notifications
  action_url: https://{remotely_accessible_url_to_my_frigate_instance}.com
  cooldown: 90
```

`Display example:`

![Frigate Diane - Motion](https://github.com/blakeblackshear/frigate/assets/40424965/09dbbb5f-9107-4f1e-ab74-f3d6c81a3eea)

## When I looked in the folder where the video is saved, the pictures and the video were saved, but the entities showed me as shown in the picture.

# Any ideas how I could resolve this issue?
