### DISCUSSION TITLE
Only car detection is working

### DISCUSSION THREAD

**Discussion by fawadrashid** [blakeblackshear/frigate#9620] [Ask A Question] [answered]
Person detection was working for me but i noticed recently that frigate for me is only detecting cars and nothing else. I am not sure why, my config is as below

```
mqtt:  
  enabled: True  
  host: ####  
  port: ####
  topic_prefix: frigate  
  client_id: frigate  
  user: ####  
  password: #### 

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True  
  restream: False    
  quality: 20  
  mode: continuous

ffmpeg:  
  global_args: -hide_banner -loglevel warning -threads 2  
  hwaccel_args: preset-rpi-64-h264   
  input_args: -rtsp_transport tcp  
  output_args:    
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p    
    record: preset-record-generic
    rtmp: preset-rtmp-generic

detect:  
  width: 640  
  height: 360  
  fps: 25  
  enabled: True  
  max_disappeared: 25  
  stationary:    
    interval: 50    
    threshold: 50    
    max_frames:      
      default: 3000

objects:
  track:
    - person
    - motorcycle
    - bicycle
    - car
 
  filters:
    person:      
      min_area: 5000      
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.7


motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2 
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: False

record:
  enabled: True  
  expire_interval: 60
  retain:
    days: 2
    mode: motion  
  events:    
    pre_capture: 20    
    post_capture: 20
    retain:
      default: 2  
      mode: motion

snapshots:  
  enabled: True  
  clean_copy: True  
  timestamp: True  
  bounding_box: True  
  crop: True  
  height: 500  
  retain:
    default: 5

rtmp:
  enabled: False

cameras:
  porch_camera_1:
    birdseye:
      mode: motion
    enabled: True
    ffmpeg:
      inputs:        
        - path: rtsp://####
          input_args: preset-rtsp-generic        
          roles:
            - detect
        - path: rtsp://####
          input_args: preset-rtsp-generic
          roles:
            - record       
    best_image_timeout: 60


    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True      
      height: 500      
      quality: 70      
      required_zones: []    
    ui:      
      order: 0      
      dashboard: True

ui:  
  live_mode: mse  
  timezone: #### 
  use_experimental: False  
  time_format: browser  
  date_style: short  
  time_style: medium
  strftime_fmt: "%Y/%m/%d %H:%M"
go2rtc:
  streams:
    porch_camera_1:
      - rtsp://####
      - "ffmpeg:porch_camera_1#video=h264"

telemetry:  
  version_check: True
```

**Comment by Trzinka** [comment, marked as answer]
# Try replacing with this:

```yaml
detect:  
  width: 640  
  height: 360  
  fps: 25  
  enabled: True  
  max_disappeared: 25  
  stationary:    
    interval: 10    
    threshold: 30 
```

```yaml
objects:
  track:
    - person
    - motorcycle
    - bicycle
    - car
 
  filters:
    person:      
      threshold: 0.7
    motorcycle
      threshold: 0.7
    bicycle
      threshold: 0.7
    car
      threshold: 0.7
```

```yaml
motion:
  threshold: 13
  contour_area: 30
  frame_height: 50
  improve_contrast: False
```

```yaml
record:
  enabled: True  
  retain:
    days: 2
    mode: motion  
  events:    
    pre_capture: 2    
    post_capture: 10
    retain:
      default: 2  
```

```yaml
cameras:
  porch_camera_1:
    enabled: True
    ffmpeg:
      inputs:        
        - path: rtsp://####
          input_args: preset-rtsp-generic        
          roles:
            - detect
        - path: rtsp://####
          input_args: preset-rtsp-generic
          roles:
            - record      
      output_args:
        record: preset-record-generic-audio-aac     # for audio record
    best_image_timeout: 10
```
