### DISCUSSION TITLE
Retain different objects

### DISCUSSION THREAD

**Discussion by Nisbo** [blakeblackshear/frigate#9630] [Ask A Question]
Deal all,

I use Frigate at the Moment only to detect Events. No Recording, only Snapshots. 
I want to keep the Events and Screenshots for Bus ——> 7 days and for car ——> 1 day
How do I have to use retain in my configuration?

```
mqtt:
  host: 192.168.178.27
  port: 1884

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Strasse:
    ffmpeg:
      inputs:
      - path: rtsps://192.168.178.1:7441/L91w*********
        roles:
        - detect
    detect:
      max_disappeared: 10
      width: 640
      height: 360
    objects:
      track:
      - bus
      - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    motion:
      mask:
      - 640,104,49,137,50,192,81,360,0,360,0,0,584,0,640,0


```
