### DISCUSSION TITLE
2 way audio not available with frigate card in HA

### DISCUSSION THREAD

**Discussion by Nooton92** [blakeblackshear/frigate#9637] [Ask A Question] [answered]
I am trying to get 2 way audio set up in home assistant for my reolink wifi doorbell camera.

I have the camera in HA but when I toggle the microphone button on in the config the button does not appear on the card. Am I missing something in my config to get this working?

```
mqtt:
  host: ip address
  port: 1883
go2rtc:
  streams:
    DoorCam: 
      - ffmpeg:https://[DoorCam_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[Username&password=[Password]#video=copy#audio=copy#audio=opus
      - rtsp://[Username]:[Pasword]@[DoorCam_IP]/Preview_01_sub
    DoorCam_sub: 
      - ffmpeg:https://[DoorCam_IP]/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=[Username]&password=[Password]
cameras:
  DoorCam:
    ffmpeg:
      inputs:   
        - path: rtsp://127.0.0.1:8554/DoorCam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record			
        - path: rtsp://127.0.0.1:8554/DoorCam_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record:  preset-record-generic-audio-copy 
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 1258,610,482,424,464,233,1280,158
    objects:
      track:
        - person
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10 

Frigate card yaml:
type: custom:frigate-card
cameras:
  - camera_entity: camera.doorcam
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
menu:
  buttons:
    microphone:
      enabled: true
      alignment: matching
      type: toggle
    timeline:
      enabled: false
    cameras:
      enabled: false
    frigate:
      enabled: false
    download:
      enabled: false
    media_player:
      enabled: false
    mute:
      enabled: true
      alignment: opposing
    camera_ui:
      enabled: false
    live:
      enabled: false
    snapshots:
      enabled: false
    clips:
      enabled: false
  style: overlay
  position: left
  button_size: 80
live:
  controls:
    thumbnails:
      mode: none
  auto_mute: all
  preload: false
dimensions: {}
media_gallery:
  controls:
    thumbnails:
      size: 140
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
    filter:
      mode: none
```

Any advise is appreciated.
