### DISCUSSION TITLE
Frigate is recording everything, not respecting motion mask

### DISCUSSION THREAD

**Discussion by soonerfan237** [blakeblackshear/frigate#9718] [Ask A Question]
Until recently I had my config set up to record only "events" and that's been working great. However, I've decided I'd also like to record all other motion as well, and store that for a shorter amount of time.

Here is the relevant part of my config under my camera:
```
record:
  enabled: True
  retain:
    days: 2 
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects
```

However, with this config, absolutely everything is getting recorded, it never stops. What I found is that this is due to the timestamp at the top of the screen being detected as motion. I tested this by going into the camera settings and disabling the timestamp overlay. And Frigate properly stopped recording when there was no real motion.

So, I re-enabled the timestamp overlay and created a Motion Mask over that area of the screen. But Frigate went right back to recording all the time. Does the mode:motion record setting not respect motion masks?

How can I accomplish retaining all event footage for 7 days, and all other motion footage for 2 days?

**Comment by NickM-27** [comment]
Motion masks are respected. Either the mask wasn't done properly or something else is being detected as motion. The easiest way to do this is to go into the debug live view and enable motion boxes

**Reply by soonerfan237** [reply]
Thanks for the quick response and the tip on the debug view for motion boxes. I was able to make some big improvements to the detection. I'm still not totally clear on the right config I need. I found some information in the documentation but still have some remaining questions.

What is an "event" in the context of the "record > events" section? I'm a bit unclear on exactly how the modes are working in this section.

active_objects: I know that a tracked object that is in motion will be recorded. Does this mode also record when a tracked object is stationary? What makes it an "active" object?

motion: I'm unclear on how this works in the context of the event tag. From my understanding an "event" is when an object is detected. When I click on "Events" in the UI I get a list of clips where an object was detected. So what gets recorded when I set "events > retain > mode: motion"? Is any motion recorded even if there is no"event" where object is detected. Or does it have to be motion during an "event"?

all: I'm also unclear on this one. Can you give an example of a scenario that falls into the "events > retain > mode: all" category but not the "events > retain > mode: motion" category?

**Reply by blakeblackshear** [reply]
I believe this section of the docs answers your questions. 

https://docs.frigate.video/configuration/record

If not, it would be great if you could offer suggestions on how to improve it.

**Reply by oodlexaps** [reply]
I think I am having the same problem.  It records all the time, (I think) because of the time stamp.
When I look at the debug live view, only the occasional motion box shows up (and where I expect them to).

Does the record section need to be under the camera in the cameras section for masks to be followed?

Here is my config:

```
record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 10
    pre_capture: 1
    post_capture: 3

cameras:
  CAM_my_camera:
    ffmpeg:
      inputs:
        - path:
        <snip>

    motion:
      mask:
        - 1111,36,1280,146,1163,269,1077,230,998,57
        - 1238,21,1241,63,874,63,873,21
```
