### DISCUSSION TITLE
27ms Inference with USB Coral

### DISCUSSION THREAD

**Discussion by mrrodge2020** [blakeblackshear/frigate#9720] [Ask A Question]
Hi,

I've had Frigate running well for a couple of years now in an LXC CT via Proxmox however I never fully managed to get the GPU working via this setup.  As I have other heavy loads to put on my server now I thought I'd be best moving Frigate to bare metal.  I was getting around 12ms inference speeds on the Coral before.

I have an Optiplex 7050 with SSD, 8GB RAM and i5-7500T CPU.  I installed Debian 12, set up Docker Compose, passed the USB to the container (docker-compose below) and plugged in the exact same config I've been running for years on the other machine.
```

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Documents/frigate/config/config.yml:/config/config.yml
      - /Documents/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

```
The Frigate log reports "TPU found" and the system screen typically shows:

![image](https://github.com/blakeblackshear/frigate/assets/59414259/a7385246-e61f-415f-a4c1-eef2f4070ad9)

my config is:

```
mqtt:
  host: 10.0.0.1
  user: mqtt
  password: xxxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car
    - cat

cameras:
  house_rear:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://frigate:
          roles:
            - rtmp
        - path: rtsp://frigate:
          roles:
            - record
        - path: rtsp://frigate:
          roles:
            - detect

    detect:
      width: 1280
      height: 720
  garden:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://frigate:
          roles:
            - rtmp
        - path: rtsp://frigate:
          roles:
            - record
        - path: rtsp://frigate:
          roles:
            - detect

    detect:
      width: 1280
      height: 720
  garage:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://frigate:
          roles:
            - rtmp
        - path: rtsp://frigate:
          roles:
            - record
        - path: rtsp://frigate:
          roles:
            - detect

    detect:
      width: 1280
      height: 720
  driveway:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://frigate:
          roles:
            - rtmp
        - path: rtsp://frigate:
          roles:
            - record
        - path: rtsp://frigate:
          roles:
            - detect

    detect:
      width: 1280
      height: 720
    zones:
      paving:
        coordinates: 186,720,1039,720,978,514,863,282,711,31,499,35
        objects:
          - person
          - car
          - cat
      blockedupdoor:
        coordinates: 304,720,0,720,0,276
        objects:
          - person
          - cat
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - paving
          - blockedupdoor
  porch:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://frigate:
          roles:
            - rtmp
        - path: rtsp://frigate:
          roles:
            - record
        - path: rtsp://frigate:
          roles:
            - detect

    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 777,720,1280,720,1280,568,778,567
        - 293,65,420,67,422,42,296,40
    zones:
      front_garden:
        coordinates: 0,720,890,720,1280,720,1280,720,1280,720,1280,720,1280,557,1280,508,1280,443,1220,419,1129,382,1009,343,882,306,765,276,655,245,562,225,477,215,347,221,0,312
        objects:
          - person
          - car
          - cat
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - front_garden
```

I'm just wondering if I'm asking too much of the machine I have it running on now... But the specs suggest not?!  Does anyone know of any BIOS settings that might affect the performance of the USB3?  I've tried different ports etc.

Thanks!
