### DISCUSSION TITLE
How to pass raw parameters to go2rtc/ffmpeg?

### DISCUSSION THREAD

**Discussion by janusn** [blakeblackshear/frigate#9765] [Ask A Question] [answered]
How to pass raw parameters into go2rtc?

Particularly, I would like to add a timestamp to the rstp stream. Here is the config.yaml that does it in go2rtc 1.8.5:
```
ffmpeg:
  vaapi_input: "-hwaccel vaapi -hwaccel_output_format nv12 -fflags nobuffer -flags low_delay -i {input}"
  vaapi_h264: "-c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0"
  timestamp: >-
    -vf "drawtext=text='%{localtime}':x=w/25:y=(h-th)-h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2,format=vaapi|nv12,hwupload"

streams:
  doorbell:
    - ffmpeg:rtsp://user:password@192.168.0.232:554/doorbell#input=vaapi_input#video=vaapi_h264#raw=timestamp
```

How do I achieve it in frigate?

environment:

- host: Ubuntu Linux 23.10
- docker: version 25.0.2, build 29cf629
- firgate: 0.13.1-34FB1C2
