### DISCUSSION TITLE
Missing audio from stream on ffmpeg source

### DISCUSSION THREAD

**Discussion by janusn** [blakeblackshear/frigate#9768] [Ask A Question] [answered]
Hi all. I have made a custom ffmpeg configuration in order to draw timestamp on my Nest Video Doorbell.

The video stream is first extracted from HASS with the script from [ass-expose-camera-stream-source](https://github.com/felipecrs/hass-expose-camera-stream-source) and it is ingested by go2rtc. There are both video stream (h.264) and audio stream (aac) in the resulting stream.

And I restream it again in go2rtc with timestamp added. This new stream lost audio. Could someone give me a suggestion on how to fix it?

The relevant section of the config.yaml is shown in the following
```
go2rtc:
  ffmpeg:
      vaapi_input: "-hwaccel vaapi -hwaccel_output_format nv12 -fflags nobuffer -flags low_delay -i {input}"
      vaapi_h264: "-c:a copy -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0"
      timestamp: >-
        -vf "drawtext=text='%{localtime}':x=w/25:y=(h-th)-h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2,format=vaapi|nv12,hwupload"
  streams:
    doorbell_raw:
      # the stream extracted from HASS
      - "echo:/config/get_ha_stream.sh camera.hello_video_doorbell"
    video_doorbell:
      # restream from doorbell_raw above with time stamp added.
      - "ffmpeg:rtsp://user:password@127.0.0.1:8554/doorbell_raw#input=vaapi_input#video=vaapi_h264#raw=timestamp"
```
doorbell_raw has a audio stream but video_doorbell does not. 😖

**Comment by janusn** [comment, marked as answer]
I have found the solution.
The audio settings has to be passed in an #audio tag instead. Here is the working version:
```
go2rtc:
  ffmpeg:
      vaapi_input: "-hwaccel vaapi -hwaccel_output_format nv12 -fflags nobuffer -flags low_delay -i {input}"
      vaapi_h264: "-c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0"
      timestamp: >-
        -vf "drawtext=text='%{localtime}':x=w/25:y=(h-th)-h/25:fontsize=h/25:fontcolor=white:shadowx=2:shadowy=2,format=vaapi|nv12,hwupload"
  streams:
    doorbell_raw:
      # the stream extracted from HASS
      - "echo:/config/get_ha_stream.sh camera.hello_video_doorbell"
    video_doorbell:
      # restream from doorbell_raw above with time stamp added.
      - "ffmpeg:rtsp://user:password@127.0.0.1:8554/doorbell_raw#input=vaapi_input#video=vaapi_h264#audio=copy#raw=timestamp"
```
