### DISCUSSION TITLE
Masks causing me a headache.

### DISCUSSION THREAD

**Discussion by bucklevision** [blakeblackshear/frigate#9844] [General]
I'm really struggling with Zones. 

Problem 1: When I use the debug page for Zone creator, and hit "Save" it doesn't save, I still have to copy-paste it into the config. It also doesn't seem to show the current camera config, despite multiple restarts after config changes. 

Problem 2: I can view my mask via a mobile and get a mask that is too small for the camera feed, but then when I fix it, and restart, when I next view it on the desktop machine, I get a mask that is too big (see attachment). It's really starting to become a rolling joke for me, I never know if my zone or mask will work.
![Untitled-1](https://github.com/blakeblackshear/frigate/assets/29090176/973e5e01-284c-4488-999a-14d1e83a941e)

**Comment by NickM-27** [comment]
this sounds like an issue with the docker config if saving the config is not working via the save button

**Reply by bucklevision** [reply]
Hmm what sort of issue might it be? Can you highlight what might be awry?

I fixed the above mask on the desktop to match the drive area, copied and pasted into the config via the web GUI, and restarted. I go back to the mask creator and get this
![Untitled-2](https://github.com/blakeblackshear/frigate/assets/29090176/d71799f5-fa7e-459a-8880-1c0dadaacbe6)

**Reply by NickM-27** [reply]
can you paste your docker compose?

also what browser are you using? If I had to guess you may be using the full res camera stream for detect and it is too large to fit on your monitor which is causing issues. Sub streams are recommended

**Reply by bucklevision** [reply]
Browser is Chrome on both an android phone and a desktop with a 4K monitor (both those images were from the desktop screen). 

My camera config is using dual streams per camera

```
 ffmpeg:
      inputs:
       - path: 
          rtsp://192.168.1.10/user=_password=channel=0_stream=0.sdp?real_stream
        roles:
        - record
      - path: 
          rtsp://192.168.1.10/user=_password=channel=0_stream=1.sdp?real_stream
        roles:
        - detect
    zones:
      driveway:
        coordinates: 0,167,0,229,0,576,119,576,356,576,623,576,704,576,704,481,704,442,704,324,704,290,704,215,704,36,641,35,590,78,588,108,574,105,559,105,547,100,549,158,511,125,505,92,434,89,427,0,209,0,113,0,0,0


Stream 0 is a 1080P/18FPS stream and Stream 1 is a 704x576 4FPS stream and it seems to select which one to use on the debug screen almost at random.

Docker Compose:
'
version: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta5
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxx"
      PLUS_API_KEY: xxx
```

**Reply by NickM-27** [reply]
are you defining the detect resolution in the config? I'd definitely recommend doing that

**Comment by simondsmason** [comment]
I think I am having a similar issue - and if not please accept my apologies.  This started a few weeks ago - I originally noticed because my HASS notifications were not firing anymore.  During this time period I did have to do quite a bit of work on my unraid as a cache drive failed but I am fully backed up so the config did (should) not have changed.

What is most noticeable is that before when I went into the Mask and Zone creator the image used to be twice the size.  And the mask as it appears in the examples below was within the image boundaries.  Now the image has shrunk.  I have not tried re-saving the motion masks etc. since this happened.  First I wanted to see what was going on before I did that.  Thanks.

Here are some examples.

<img width="1255" alt="image" src="https://github.com/blakeblackshear/frigate/assets/6063262/7c539214-ba06-4ff1-8dac-dba6bb3dbf25">

<img width="906" alt="image" src="https://github.com/blakeblackshear/frigate/assets/6063262/1dce6556-1d9e-427e-8394-93dd282649db">

Config:

```
mqtt:
  host: 192.168.2.110
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: ###########6667
  stats_interval: 60
ffmpeg:
  hwaccel_args: preset-nvidia-h264
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 30
    mode: all
birdseye:
  enabled: True
  mode: continuous
  restream: True
rtmp:
  enabled: False
#  width: 1920
#  height: 1080
#  quality: 4
go2rtc:
  streams:
    driveway:
      - rtsp://admin:###########@192.168.2.234:554//h264Preview_01_main
      - "ffmpeg:driveway#audio=opus"
    drivewaysub:
      - rtsp://admin:###########@192.168.2.234:554//h264Preview_01_sub
      - "ffmpeg:driveway#audio=opus"
    back_garden:
      - rtsp://admin:###########@192.168.2.33:554//h264Preview_01_main
      - "ffmpeg:back_garden#audio=opus"
    back_gardensub:
      - rtsp://admin:###########@192.168.2.33:554//h264Preview_01_sub
      - "ffmpeg:back_garden#audio=opus"
    front_door:
      - rtsp://admin:###########@192.168.2.160:554//h264Preview_01_main
      - "ffmpeg:front_door#audio=opus"
    front_doorsub:
      - rtsp://admin:###########@192.168.2.160:554//h264Preview_01_sub
      - "ffmpeg:front_door#audio=opus"
    porch:
      - rtsp://admin:###########@192.168.2.161:554//h264Preview_01_main
      - "ffmpeg:porch#audio=opus"
    porchsub:
      - rtsp://admin:###########@192.168.2.161:554//h264Preview_01_sub
      - "ffmpeg:porch#audio=opus"
    front_garden:
      - rtsp://admin:###########@192.168.2.149:554//h264Preview_01_main
      - "ffmpeg:front_garden#audio=opus"
    front_gardensub:
      - rtsp://admin:###########@192.168.2.149:554//h264Preview_01_sub
      - "ffmpeg:front_garden#audio=opus"
#    kitchen:
#      - rtsp://admin:###########@192.168.2.227:554//h264Preview_01_main
#      - "ffmpeg:kitchen#audio=opus"
#    kitchensub:
#      - rtsp://admin:###########@192.168.2.227:554//h264Preview_01_sub
#      - "ffmpeg:kitchen#audio=opus"
    garage:
      - rtsp://192.168.2.110:8556/garage_inside
      - "ffmpeg:garage#audio=opus"
#    home_office:
#      - rtsp://admin:###########@192.168.2.217:554/live
#      - "ffmpeg:home_office#audio=opus"
#    home_theater:
#      - rtsp://admin:###########@192.168.2.233:554/live
#      - "ffmpeg:home_theater#audio=opus"
    birdseye:
      - rtsp://127.0.0.1:8554/birdseye
  webrtc:
    candidates:
      - 192.168.2.110:8555
      - stun:8555
cameras:
  driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/drivewaysub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
##    detect:
##      width: 1280
##      height: 720            
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 0,720,441,720,632,283,806,179,795,106,950,105,981,217,1060,293,1280,415,1280,0,513,0,0,0
  back_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/back_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_gardensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      width: 1280
#      height: 720            
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 441,707,437,671,11,676,11,710
        - 910,371,904,512,939,562,1046,557,1085,411,1083,307,1044,246,974,240,929,281
    zones:
      back_step:
#        coordinates: 979,720,1122,720,1086,564,1059,533,965,533
        coordinates: 895,720,1122,720,1086,564,1059,533,893,536
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
#        - path: rtsp://127.0.0.1:8554/front_doorsub?video=copy&audio=aac
#          input_args: preset-rtsp-restream
#          roles:
            - detect
    detect:
      width: 1280
      height: 720            
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    motion:
      mask:
        - 14,676,437,672,439,704,16,703
    zones:
      front_step:
        coordinates: 0,361,244,225,664,720,253,720
  porch:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/porch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porchsub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      width: 1280
#      height: 720            
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
       - 442,707,442,664,14,665,12,711
  front_garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_garden?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_gardensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
#    detect:
#      width: 1280
#      height: 720            
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    motion:
      mask:
        - 12,705,439,703,437,666,11,671
        - 0,0,1280,0,1280,274,908,292,351,354,0,452  
  kitchen:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kitchensub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 2
        post_capture: 2
    detect:
      enabled: true
    motion:
      mask:
        - 0,720,433,720,433,677,0,676
        - 856,123,1193,125,1222,505,1193,720,700,720,735,530,851,521,854,315,730,306,732,141
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          roles:
            - rtmp
            - detect
    detect:
      enabled: true
    birdseye:
      enabled: true
    motion:
      mask:
        - 771,720,1280,720,1280,669,769,668
  home_office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/home_office?video=copy&audio=aac
          roles:
            - rtmp
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    birdseye:
      enabled: true
    motion:
      mask:
        - 918,718,1251,716,1253,664,915,669
  home_theater:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/home_theater?video=copy&audio=aac
          roles:
            - rtmp
            - detect
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 30
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        pre_capture: 1
        post_capture: 1
    detect:
      enabled: false
    birdseye:
      enabled: True
    motion:
      mask:
        - 920,712,1255,712,1253,666,916,666
ui:
  live_mode: webrtc
#logger:
#  logs:
#    frigate.record: debug

```
