### DISCUSSION TITLE
Audio treshold

### DISCUSSION THREAD

**Discussion by jokerigno** [blakeblackshear/frigate#9863] [General]
Hi,

I'm testing audio detection with a reolink E1 Zoom camera and reliability changes a lot based on the type of sound. For example speech is very sensitive while cough cry require some time to trigger.

Due to the fact that my main purpose is baby monitoring (so cry and cough are my most common potential triggers) there's a way to enhance sensitiivy or create a generic sound detection based on decibel instead of sound type?

below my config:

```
cameretta:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cameretta
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        # - path: rtsp://127.0.0.1:8554/cameretta_sub
        #   input_args: preset-rtsp-restream
        #   roles:
        #     - detect
    audio:
      enabled: True
      listen:
        - crying
        - cough
        - scream
        - speech
        - yell
        - babbling
        - whispering
        - sigh
        - groan
        - grunt
        - pant
      min_volume: 200 
      filters:
        crying:
          threshold: 0.5
        cough:  
          threshold: 0.5
        scream:
          threshold: 0.5
        sigh:     
          threshold: 0.5                 
        whispering:     
          threshold: 0.8 
      #width: 640 # <---- update for your camera's resolution
      #height: 360 # <---- update for your camera's resolution
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 1
          mode: active_objects
    snapshots: # <----- Enable snapshots
      enabled: True 

```
