### DISCUSSION TITLE
Zone min_area configuration not being honored, maybe I did something wrong?

### DISCUSSION THREAD

**Discussion by airadier** [blakeblackshear/frigate#9870] [Ask A Question]
Hi! 

I have defined a camera, and I want to set a min_area for the `near` zone, as from time to time I get false positives of cats being detected as person.

This is the relevant configuration section:
```
  jardin:  
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jardin 
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    motion:
      mask:
        - 0,0,0,0,1232,0,1232,220,0,724
        - 1446,112,1920,112,1920,47,1446,47
    objects:
      filters:
        person:
          min_area: 30000
    zones:
      far:
        coordinates: 1920,245,1920,0,0,0,0,562
        objects:
          - person        
        filters:
          person:
            # High res
            min_area: 10000
      near:
        coordinates: 1920,1080,1920,579,0,795,0,1080
        objects:
          - person
        filters:
          person:
            min_area: 80000
    mqtt:
      crop: False
```

As you can see, I have a zone "near" with a set of coordinates, and I define a filter for person with min_area 80000.

The zone, in debug, seems to be correct:

![image](https://github.com/blakeblackshear/frigate/assets/244729/fe7e22b2-ca4a-4b03-ab6b-837c145d61f3)

But then I still get events of "cats" being triggered with an area of 42000, and I see no zone attached to it:

![image](https://github.com/blakeblackshear/frigate/assets/244729/e4ab2316-22ae-490c-8f14-505585e99eca)

The strange thing is that no zone is reported, while in other events I see "near" or "far", like in this example:

![image](https://github.com/blakeblackshear/frigate/assets/244729/429722c6-06f6-4c2e-b9ca-e8fd35acfede)

is there a problem with my configuration, or is this an issue? I understand that the more specific zone in near should override the general min_area for the camera (set to 30000?). But maybe the zone-specific "near" configuration filters out the detection, but then this is triggered at the camera configuration, which has a lower area threshold?

Thanks!

**Comment by NickM-27** [comment]
If you want your zone to be enforced you need to make it required for events

**Comment by blakeblackshear** [comment]
Zone filters limit when a zone is activated by an object. They are not a way to apply object filters in a specific area to avoid false positives. The behavior you are seeing is exactly the intended use. Objects smaller than the min_area do not have the zone.

**Reply by airadier** [reply]
Thanks for the answers! Now I was able to prevent recording the event and the snapshot using:
```
   record:
      events:
        required_zones:
          - near
          - mid
          - far
    snapshots:
      required_zones:
        - near
        - mid
        - far  
    zones:
      far:
        coordinates: 0,0,1920,0,1920,245,0,562
        objects:
          - person        
        filters:
          person:
            # High res
            min_area: 10000
      mid:
        coordinates: 0,562,1920,245,1920,579,0,795
        objects:
          - person        
        filters:
          person:
            # High res
            min_area: 30000
      near:
        coordinates: 0,795,1920,579,1920,1080,0,1080
        objects:
          - person
        filters:
          person:
            # High res
            min_area: 80000
    mqtt:
      crop: False
      required_zones:
        - near
        - mid
        - far
```

So I require record.events and snapshots to have "required_zones". Also, I tried preventing the mqtt event with the mqtt.required_zones. But unfortunately that seems to prevent the event in the camera, but not the global one, according to the docs:

      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.

So in HomeAssistant I still get an MQTT event that triggers the alert:

```
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: mqtt
  topic: frigate/events
  payload: >-
    {"before": {"id": "1708207686.602412-kcp0kl", "camera": "jardin",
    "frame_time": 1708207686.602412, "snapshot": null, "label": "person",
    "sub_label": null, "top_score": 0.0, "false_positive": true, "start_time":
    1708207686.602412, "end_time": null, "score": 0.86865234375, "box": [1682,
    822, 1747, 1059], "area": 15405, "ratio": 0.2742616033755274, "region":
    [1517, 692, 1905, 1080], "stationary": false, "motionless_count": 0,
    "position_changes": 0, "current_zones": [], "entered_zones": [], "has_clip":
    false, "has_snapshot": false, "attributes": {}, "current_attributes": []},
    "after": {"id": "1708207686.602412-kcp0kl", "camera": "jardin",
    "frame_time": 1708207686.602412, "snapshot": {"frame_time":
    1708207686.752886, "box": [1682, 822, 1747, 1059], "area": 15405, "region":
    [1517, 692, 1905, 1080], "score": 0.86865234375, "attributes": []}, "label":
    "person", "sub_label": null, "top_score": 0.76904296875, "false_positive":
    false, "start_time": 1708207686.602412, "end_time": null, "score":
    0.86865234375, "box": [1682, 822, 1747, 1059], "area": 15405, "ratio":
    0.2742616033755274, "region": [1517, 692, 1905, 1080], "stationary": false,
    "motionless_count": 0, "position_changes": 0, "current_zones": [],
    "entered_zones": [], "has_clip": false, "has_snapshot": false, "attributes":
    {}, "current_attributes": []}, "type": "new"}
  qos: 0
  description: mqtt topic frigate/events
  payload_json:
    before:
      id: 1708207686.602412-kcp0kl
      camera: jardin
      frame_time: 1708207686.602412
      snapshot: null
      label: person
      sub_label: null
      top_score: 0
      false_positive: true
      start_time: 1708207686.602412
      end_time: null
      score: 0.86865234375
      box:
        - 1682
        - 822
        - 1747
        - 1059
      area: 15405
      ratio: 0.2742616033755274
      region:
        - 1517
        - 692
        - 1905
        - 1080
      stationary: false
      motionless_count: 0
      position_changes: 0
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
      attributes: {}
      current_attributes: []
    after:
      id: 1708207686.602412-kcp0kl
      camera: jardin
      frame_time: 1708207686.602412
      snapshot:
        frame_time: 1708207686.752886
        box:
          - 1682
          - 822
          - 1747
          - 1059
        area: 15405
        region:
          - 1517
          - 692
          - 1905
          - 1080
        score: 0.86865234375
        attributes: []
      label: person
      sub_label: null
      top_score: 0.76904296875
      false_positive: false
      start_time: 1708207686.602412
      end_time: null
      score: 0.86865234375
      box:
        - 1682
        - 822
        - 1747
        - 1059
      area: 15405
      ratio: 0.2742616033755274
      region:
        - 1517
        - 692
        - 1905
        - 1080
      stationary: false
      motionless_count: 0
      position_changes: 0
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
      attributes: {}
      current_attributes: []
    type: new
``` 

The topic is frigate/events

Is there a way to prevent sending messages there?

The problem I am facing is that I trigger an alarm when a person is detected in that camera. I was getting many false positives for cats, so I defined the 3 zones and a min_area. That seems to be solving the problem of false positives for the cats, as they are not detected in the zone due to the min_area. But still, I don't know how to prevent the alarm being triggered in home assistant because the MQTT message is being sent.

Maybe I could chec kthe "has_clip" or "has_snapshot"? As the snapshots and recordings are now disabled, I guess this might work?
