### DISCUSSION TITLE
[Camera Support]: Audio Works in MSE, but not WebRTC

### DISCUSSION THREAD

**Discussion by jamesphw** [blakeblackshear/frigate#9896] [Camera Support]
### Describe the problem you are having

I can get video fine from my Reolink Wifi doorbell, but audio is more difficult! This is both in Frigate and in the Frigate Home Assistant dashboard card.

When I use MSE in the Frigate UI, everything (including audio) loads fine. If I choose WebRTC, the video simply does not load at all in the Frigate UI. In Home Assistant, video is fine with both MSE and WebRTC, but WebRTC has no audio.

Ultimately what I want to get to is two-way audio, so the lack of WebRTC audio is blocking me...

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.XX
  port: 1883
  topic_prefix: frigate
  user: MQTTUSER
  password: MQTTPASS

go2rtc:
  rtsp:
    username: USER
    password: PASS
  streams:
    front_doorbell:
      - "ffmpeg:https://192.168.50.XX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=USER&password=PASS#video=copy#audio=copy#audio=opus"
      - rtsp://USER:PASS@192.168.50.XX:554/h264Preview_01_main
    front_doorbell_sub:
      - "ffmpeg:https://192.168.50.XX/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=USER&password=PASS#audio=copy#audio=opus"
      - rtsp://USER:PASS@192.168.50.XX:554/h264Preview_01_sub 

cameras:
  front_doorbell: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_doorbell?video=copy&audio=aac  
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/front_doorbell_sub?video=copy&audio=aac 
        input_args: preset-rtsp-restream
        roles:
        - detect
        - rtmp
      hwaccel_args: preset-vaapi
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      enabled: false
    motion:
      mask:
      - 0,259,0,0,476,0,493,91,517,284,290,285
    objects:
      track:
        - person
```

### Relevant log output

```shell
The only error in the logs is the following:

2024-02-17 07:21:51.375471520  [2024-02-17 07:21:51] frigate.util.services          ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
2024-02-17 07:21:51.375480550
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://USER:PASS@192.168.50.XX:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 15 fps, 15 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"cameras":{"front_doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":332,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":338,"pid":331,"process_fps":5.0,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"79":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"4.0","cpu_average":"3","mem":"0.5"},"108":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"110":{"cmdline":"python3 -u -m frigate","cpu":"1.6","cpu_average":"1","mem":"2.5"},"117":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.2"},"145":{"cmdline":"nginx: worker process","cpu":"0.7","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.1","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"153":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"296":{"cmdline":"frigate.logger       ","cpu":"0.1","cpu_average":"0","mem":"1.3"},"314":{"cmdline":"frigate.recording_manager","cpu":"0.5","cpu_average":"0","mem":"1.7"},"323":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)","cpu":"0.1","cpu_average":"0","mem":"0.1"},"324":{"cmdline":"frigate.detector.cpu ","cpu":"0.0","cpu_average":"0","mem":"1.5"},"326":{"cmdline":"frigate.output       ","cpu":"0.7","cpu_average":"0","mem":"1.5"},"330":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"331":{"cmdline":"frigate.process:front_doorbell","cpu":"2.7","cpu_average":"2","mem":"1.5"},"332":{"cmdline":"frigate.capture:front_doorbell","cpu":"1.4","cpu_average":"1","mem":"1.4"},"333":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.2"},"338":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_doorbell_sub?video=copy&audio=aac -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"3.6","cpu_average":"3","mem":"0.7"},"346":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.50.171/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/0e256e2e345acc44b61eb7cf2181156c","cpu":"4.4","cpu_average":"4","mem":"0.4"},"347":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/front_doorbell?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"0.7","cpu_average":"0","mem":"0.3"},"348":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.50.171/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/b85f02234abac0e6f368feb6098ff14b","cpu":"4.8","cpu_average":"4","mem":"0.3"},"1159":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":324}},"gpu_usages":{"error-gpu":{"gpu":-1,"mem":-1}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":296},"recording":{"pid":314}},"service":{"last_updated":1708154005,"latest_version":"0.13.1","storage":{"/dev/shm":{"free":63.0,"mount_type":"tmpfs","total":64.0,"used":1.0},"/media/frigate/clips":{"free":30620.7,"mount_type":"ext4","total":58245.9,"used":24634.9},"/media/frigate/recordings":{"free":30620.7,"mount_type":"ext4","total":58245.9,"used":24634.9},"/tmp/cache":{"free":953.4,"mount_type":"tmpfs","total":953.7,"used":0.3}},"temperatures":{},"uptime":649,"version":"0.13.1-34fb1c2"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Reolink Wifi Doorbell 

### Any other information that may be helpful

Below is the configuration for the Home Assistant lovelace card. Note that I have tried both MSE and WebRTC as the go2rtc modes (see problem description).

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.front_doorbell
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
      stream: front_doorbell_sub
menu:
  style: outside
  position: bottom
  buttons:
    microphone:
      enabled: true
    mute:
      enabled: true
live:
  controls:
    thumbnails:
      mode: none
  auto_mute: all
  preload: true
  transition_effect: slide

```
