### DISCUSSION TITLE
[Config Support]: Reolink 510WA Preview Stream resolution and ratio

### DISCUSSION THREAD

**Discussion by fabiankrei** [blakeblackshear/frigate#9900] [Config Support]
### Describe the problem you are having

Hello all,
I'm currently trying to setup my Reolink with frigate and there is a thing I do not understand.
As detection of small objects like cats did not work very well with the sub stream of the reeling I followed the suggestion to increase resolution of detection stream.
I wanted to uses the main Reolink steam, which is set up to 2048x1536 (Ratio 4:3), which I also use for recording. The strange thing is now that according to documentation Frigate uses for jsmpeg preview the same stream like for detection. But the quality/reolusion is not increasing when I use main stream for detection. And also the ration is not 4:3, I looks more like 16:9.
How is that possible? In the config file there is link used to another steam like the main stream. 
What is also strange: when I set wide and height for detect to 2048 X 1536 the preview is changing to 4:3 but quality is still very poor.
The records are correctly with high resolution and ratio.
Is frigate automatically compressing the preview/detection stream?

Regards
Fabian

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.1.55

#birdseye:
#  enabled: True
#  width: 1280
#  height: 720
#  quality: 8
#  mode: objects

record:
  enabled: True
#  retain_days: 10
  events:
    retain:
      default: 14



snapshots:
  enabled: True
  bounding_box: True
  crop: false
  retain:
    default: 14
 
cameras:
  frontyard:
    ffmpeg:  
      hwaccel_args: preset-rpi-64-h264
      input_args: preset-http-reolink
      inputs:
        - path: http://192.168.1.152/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
          roles:
            - record
        - path: http://192.168.1.152/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx
          roles:
            - detect
            - rtmp
        

    detect:
      width: 2048
      height: 1536
      fps: 10

    rtmp:
      enabled: False
```

### Relevant log output

```shell
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
