### DISCUSSION TITLE
[Support]: what's frigate trying to do when this occurs?

### DISCUSSION THREAD

**Discussion by g13092** [blakeblackshear/frigate#9904] [General Support] [answered]
### Describe the problem you are having

Anyone seen this in the log when starting up?

`2024-02-17 20:36:08.130576176  [INFO] Starting Frigate...

2024-02-17 20:36:08.192497997  2024/02/17 20:36:08 [error] 145#145: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.253, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001stats", host: "192.168.1.249:5000"

2024-02-17 20:36:08.538897404  [INFO] Starting go2rtc...`

253 is where homeassistant lives.  249:5001 is where wyzebridge lives.  What is http://127.0.0.1:5001stats for?  It's not even correctly formed...  I'm nothing on 127.0.0.1 responds, so I'm not surprised there's an error.

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.253
  user: homeassistant
  password: ********

ffmpeg:
  #hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream 
  #avoid_negative_ts make_zero

detectors:
  coral:
    type: edgetpu
    device: pci

#Global Object Settings
objects:
  track:
    - person
    - dog
    - cat
    - horse
    - car
  filters:
    person:
      min_area: 5000
      max_area: 100000

record:
  enabled: true
  retain:
    days: 10
    mode: all

birdseye:
  enabled: true
  mode: motion

# go2rtc:
#   streams:
#     DoorCam: 
#       - rtsp://192.168.1.249:8554/back-door


#Cameras
cameras:
  DoorCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://192.168.1.249:8554/back-door?mp4
          roles:
            - record
            - detect
    detect:
      enabled: True
      width: 768
      height: 1024
      fps: 5
    birdseye:
      mode: continuous

  NorthCam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.249:8554/new-north-cam
          roles:
            #- record
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 4
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
          objects:
            dog: 2
            car: 2
            person: 5
            horse: 4
    birdseye:
      mode: continuous

  SouthCam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.249:8554/new-south-cam
          roles:
           # - record
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      filters:
        car:
          mask:
            - 251,44,54,84,89,111,255,90,480,94,480,53 
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 4
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
          objects:
            dog: 2
            car: 2
            person: 5
            horse: 4
    birdseye:
      mode: continuous

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.249:8554/driveway
          roles:
           # - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: True
      retain:
        days: 4
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
          objects:
            dog: 2
            car: 2
            person: 5
    birdseye:
      mode: continuous

#   pasture:
#     ffmpeg:
#       inputs:
#         - path: rtsp://192.168.1.249:8554/pasture
#           roles:
#           #  - record
#             - detect
#     detect:
#       enabled: true
#       width: 480
#       height: 360
#       fps: 5
#     record:
#       enabled: True
#       retain:
#         days: 4
#         mode: active_objects
#       events:
#         retain:
#           default: 10
#           mode: active_objects
#           objects:
#             dog: 2
#             car: 2
#             person: 5
#             horse: 5
#     birdseye:
#       mode: continuous
```

### Relevant log output

```shell
see above
```

### FFprobe output from your camera

```shell
not camera related
```

### Frigate stats

```json
cameras	
DoorCam	
audio_dBFS	0
audio_rms	0
camera_fps	4.9
capture_pid	337
detection_enabled	1
detection_fps	0.5
ffmpeg_pid	857
pid	328
process_fps	4.8
skipped_fps	0.1
NorthCam	
audio_dBFS	0
audio_rms	0
camera_fps	5.1
capture_pid	349
detection_enabled	1
detection_fps	1.6
ffmpeg_pid	361
pid	330
process_fps	5.1
skipped_fps	0
SouthCam	
audio_dBFS	0
audio_rms	0
camera_fps	3.4
capture_pid	357
detection_enabled	1
detection_fps	7.6
ffmpeg_pid	364
pid	332
process_fps	3.4
skipped_fps	0
driveway	
audio_dBFS	0
audio_rms	0
camera_fps	3.5
capture_pid	362
detection_enabled	1
detection_fps	2.6
ffmpeg_pid	765
pid	335
process_fps	3.5
skipped_fps	0
cpu_usages	
1	
cmdline	"/package/admin/s6/command/s6-svscan -d4 -- /run/service"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
15	
cmdline	"s6-supervise s6-linux-init-shutdownd"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
16	
cmdline	"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
24	
cmdline	"s6-supervise frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
25	
cmdline	"s6-supervise frigate-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
26	
cmdline	"s6-supervise go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
27	
cmdline	"s6-supervise go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
28	
cmdline	"s6-supervise nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
29	
cmdline	"s6-supervise nginx-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
30	
cmdline	"s6-supervise go2rtc-log"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
31	
cmdline	"s6-supervise s6rc-fdholder"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
32	
cmdline	"s6-supervise s6rc-oneshot-runner"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
41	
cmdline	"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
42	
cmdline	"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
80	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
81	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
82	
cmdline	"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
89	
cmdline	"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml"
cpu	"0.0"
cpu_average	"0"
mem	"0.3"
106	
cmdline	"bash ./run.user go2rtc-healthcheck"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
112	
cmdline	"python3 -u -m frigate"
cpu	"2.0"
cpu_average	"2"
mem	"3.7"
119	
cmdline	"nginx: master process nginx"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
145	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
146	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
147	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
150	
cmdline	"nginx: worker process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
160	
cmdline	"nginx: cache manager process"
cpu	"0.0"
cpu_average	"0"
mem	"0.1"
295	
cmdline	"frigate.logger       "
cpu	"0.0"
cpu_average	"0"
mem	"1.4"
297	
cmdline	"frigate.recording_manager"
cpu	"1.5"
cpu_average	"1"
mem	"1.8"
306	
cmdline	"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(53)"
cpu	"0.2"
cpu_average	"0"
mem	"0.1"
307	
cmdline	"frigate.detector.coral"
cpu	"3.0"
cpu_average	"3"
mem	"1.8"
311	
cmdline	"frigate.output       "
cpu	"1.2"
cpu_average	"1"
mem	"1.6"
325	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 768x1024 -i pipe: -f mpegts -s 540x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
326	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.3"
328	
cmdline	"frigate.process:DoorCam"
cpu	"2.4"
cpu_average	"2"
mem	"1.8"
329	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.2"
330	
cmdline	"frigate.process:NorthCam"
cpu	"3.5"
cpu_average	"4"
mem	"2.0"
332	
cmdline	"frigate.process:SouthCam"
cpu	"3.3"
cpu_average	"2"
mem	"1.8"
334	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.3"
335	
cmdline	"frigate.process:driveway"
cpu	"2.2"
cpu_average	"3"
mem	"2.1"
337	
cmdline	"frigate.capture:DoorCam"
cpu	"1.3"
cpu_average	"1"
mem	"1.7"
338	
cmdline	"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:"
cpu	"0.0"
cpu_average	"0"
mem	"0.3"
349	
cmdline	"frigate.capture:NorthCam"
cpu	"2.7"
cpu_average	"2"
mem	"1.7"
357	
cmdline	"frigate.capture:SouthCam"
cpu	"1.1"
cpu_average	"1"
mem	"1.7"
361	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.249:8554/new-north-cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/NorthCam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"25.9"
cpu_average	"25"
mem	"0.7"
362	
cmdline	"frigate.capture:driveway"
cpu	"1.3"
cpu_average	"1"
mem	"1.7"
364	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.249:8554/new-south-cam -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/SouthCam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"10.8"
cpu_average	"19"
mem	"0.8"
765	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.249:8554/driveway -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=1280:720 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"11.4"
cpu_average	"19"
mem	"0.7"
857	
cmdline	"ffmpeg -hide_banner -loglevel warning -threads 2 -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://192.168.1.249:8554/back-door?mp4 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/DoorCam@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale=768:1024 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:"
cpu	"5.8"
cpu_average	"6"
mem	"0.6"
1391	
cmdline	"sleep 30s"
cpu	"0.0"
cpu_average	"0"
mem	"0.0"
detection_fps	12.3
detectors	
coral	
detection_start	0
inference_speed	9.36
pid	307
processes	
go2rtc	
pid	89
logger	
pid	295
recording	
pid	297
service	
last_updated	1708224213
latest_version	"0.13.2"
storage	
/dev/shm	
free	120.4
mount_type	"tmpfs"
total	128
used	7.6
/media/frigate/clips	
free	588179.3
mount_type	"ext4"
total	703077.9
used	114882.6
/media/frigate/recordings	
free	588179.3
mount_type	"ext4"
total	703077.9
used	114882.6
/tmp/cache	
free	950.7
mount_type	"tmpfs"
total	953.7
used	3
temperatures	
apex_0	44.55
uptime	443
version	"0.13.1-34fb1c2"
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

wyze cams

### Any other information that may be helpful

using wyze bridge 2.6
