### DISCUSSION TITLE
High RAM and CPU Usage, Broken OpenVINO Support, and Stability Issues with RTMP and go2rtc After Upgrade to 0.13.1

### DISCUSSION THREAD

**Discussion by VoidNullNil** [blakeblackshear/frigate#9926] [General]
### Issue Summary

After upgrading to version 0.13.1, we are experiencing multiple critical issues that significantly degrade the performance and functionality of our application. The problems include unexpectedly high RAM and CPU usage, apparent broken support for OpenVINO, RTMP functionality ceasing, and instability in go2rtc (versions 1.7.1 and up).

### Detailed Description

- **Increased Resource Usage:** Post-upgrade, the application's RAM usage has more than doubled 500->1200, and CPU usage has also unexpectedly spiked. This increase is observed under normal operating conditions, without any changes to our usage patterns or configurations.
  
- **OpenVINO Support:** The integration with OpenVINO now seems to be broken, with processors showing much higher usage than expected. This suggests a possible issue with OpenVINO support or optimization in the latest version.
  
- **RTMP and go2rtc Stability:** RTMP functionality has stopped working entirely post-upgrade. Additionally, the go2rtc integration has become highly unstable, with issues beginning from version 1.7.1. The specific go2rtc issue is documented here: [go2rtc issue #947](https://github.com/AlexxIT/go2rtc/issues/947).

### Environment

- **Software Version:** 0.13.1
- **Operating System:** Ubuntu 22.04 LTS with OpenVino and VAAPI support
- **Relevant Software Versions:** OpenVINO, go2rtc 1.7.1 and above
- **Hardware:** CPU: Intel N5105, 16 Gigs of RAM
### Expected Behavior

Prior to the upgrade, the application was running efficiently with manageable RAM and CPU usage. OpenVINO support was stable, and both RTMP and go2rtc functionalities were working as expected without any issues.

### Actual Behavior

- **Resource Usage:** The application now consumes double the amount of RAM and significantly more CPU, impacting performance and scalability.
- **OpenVINO Support:** Integration with OpenVINO is no longer stable, leading to excessive CPU usage.
- **RTMP and go2rtc:** RTMP has ceased to function, and go2rtc stability issues have emerged, directly affecting our operational capabilities.

### Steps to Reproduce

1. Upgrade to version 0.13.1.
2. Observe the increased RAM and CPU usage under normal operation.
3. Test OpenVINO integration and note the high processor usage.
4. Attempt to use RTMP and go2rtc functionalities, noting any failures or stability issues.

### Request

We are seeking guidance on mitigating these issues or an update that addresses these critical problems. Any workarounds or patches that can temporarily alleviate these issues would also be greatly appreciated.

**Comment by NickM-27** [comment]
There is not much information to go off of here, I'd suggest providing your full config, logs, and a screenshot of the system page. 

The release notes noted that motion detection changed and would be more sensitive by default potentially resulting in higher CPU usage for some users. Sounds like this may be the case and motion detection should be tuned https://docs.frigate.video/configuration/motion_detection

**Reply by VoidNullNil** [reply]
Thank you for the response. However, please note that motion detection is currently turned off in our system; we exclusively monitor individuals. I'm uncertain about the modifications between versions that have resulted in a doubling of CPU usage.

```
objects: # Object to detect - https://docs.frigate.video/configuration/objects/
  track:
    - person
  filters:
    person:
      min_area: 3500
      min_score: 0.8
      threshold: 0.8
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

**Reply by VoidNullNil** [reply]
Could you provide insights into why RTMP functionality was not tested in the new version, and what factors may have led to the observed increase in RAM usage? 
Not to mention the CPU usage with OpenVINO integration.

**Reply by NickM-27** [reply]
> However, please note that motion detection is currently turned off in our system; we exclusively monitor individuals.

if you are detecting objects then motion detection is enabled, motion detection is required for object detection

> Could you provide insights into why RTMP functionality was not tested in the new version, and what factors may have led to the observed increase in RAM usage?

it was tested, many users use this without issues. Just because it doesn't work for you doesn't mean it wasn't tested.

**Reply by VoidNullNil** [reply]
> it was tested, many users use this without issues. Just because it doesn't work for you doesn't mean it wasn't tested.

Alright, please visit the go2rtc issues page where you'll find instructions on how to reproduce the issue. 
However, note that version 1.7.1 does not have this problem.

**Reply by NickM-27** [reply]
I looked at it. I just tested RTMP with my reolink camera and it is working normally so this is likely not an across the board rtmp issue

**Reply by NickM-27** [reply]
also worth noting that you can replace the included version of go2rtc with whatever version you want

https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Reply by VoidNullNil** [reply]
Thank you, I have already determined the version that has issues, as detailed here: https://github.com/AlexxIT/go2rtc/issues/947.

**Reply by NickM-27** [reply]
yes, but in that case you can use 1.7.1 and it will work for you without issues until go2rtc resolves the problem

**Reply by VoidNullNil** [reply]
No, CPU and RAM usage was the same (doubled) from 0.12.1.

**Comment by VoidNullNil** [comment]
> I'd suggest providing your full config, logs, and a screenshot of the system page.

I'd suggest initiating an issue tracker and welcoming bug reports. It appears that the introduction of new features might be impacting the performance and functionality of existing ones.

**Reply by NickM-27** [reply]
there are many issue templates available in the discussion, you as the user chose `general discussion` instead of using one of the issue templates

**Reply by NickM-27** [reply]
> It appears that the introduction of new features might be impacting the performance and functionality of existing ones.

0.13 was under beta and RC testing for 6 months total. Just because you are seeing issues doesn't mean it wasn't tested. Frigate has tens of thousands of users at this point and there were multiple thousands of users during the beta testing phase

**Reply by VoidNullNil** [reply]
Specifically for your request, I can perform an upgrade and capture all monitoring data, but this won't explain why the CPU and RAM usage has doubled.

**Reply by VoidNullNil** [reply]
Additionally, you're so proficient that concerns about rollback migrations seem irrelevant to you. Excellent job.

**Reply by NickM-27** [reply]
I have supported many users with support requests regarding CPU usage. If you don't want to provide the information that will help me help you then there is no support that can be provided. 

The system page provides a lot of information about _what is using CPU_ so we can provide suggestions.

**Reply by NickM-27** [reply]
> Additionally, you're so proficient that concerns about rollback migrations seem irrelevant to you. Excellent job.

DB rollbacks are not easily done with the version of sqlite that is included in python 3.9 due to the need to drop tables and other things which would require a full DB rebuild. Future versions of python make this much easier but we are currently bound to 3.9 due to various dependencies.

**Reply by VoidNullNil** [reply]
CPU usage increased from 15% in version 0.12.1 to 30-40% in version 0.13.2, and memory usage rose from 400 megabytes in version 0.12.1 to 1200 megabytes in version 0.13.2, all without any changes to the configuration. I continued using the older version of go2rtc that supports RTMP.

**Reply by NickM-27** [reply]
Please provide your full config and a screenshot of the entire system page, that is the info that is needed to further help with cpu and ram usage

**Reply by VoidNullNil** [reply]
Only a few tables were created and some indexes were added, all of which can be reverted safely.

**Reply by VoidNullNil** [reply]
Example after upgrade, and statistic after I downgrade and rollback database ![Screenshot_1](https://github.com/blakeblackshear/frigate/assets/3663022/213dba9c-e5e5-44ee-8213-1abad231bbad)

**Reply by NickM-27** [reply]
> Only a few tables were created and some indexes were added, all of which can be reverted safely.

I already explained why that is not the case.

> Example after upgrade, and statistic after I downgrade and rollback database

please provide the information requested, that is what I need to help you

**Reply by VoidNullNil** [reply]
Configuration:

```
# yaml-language-server: $schema=http://192.168.1.25:5000/api/config/schema.json

database:
  path: /media/frigate/frigate.db
mqtt:
  enabled: False
go2rtc:
  streams:
    court:
      - rtmp://192.168.1.20/stream/6f3aa9c3-1ccc-4a7f-9561-623e9faa314b.stream
    corner:
      - rtmp://192.168.1.20/stream/2b3ef742-e0af-4248-8ba5-949ac7666ef0.stream
    street:
      - rtmp://192.168.1.20/stream/0a4e446c-f3b2-435e-b3eb-609fa01f9863.stream
  webrtc:
    candidates:
      - 192.168.1.25:8555
      - stun:8555
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
    # This is the section for the H/W Accelaration, you will need to figure out what settings you need to enable - https://docs.frigate.video/configuration/hardware_acceleration/
  hwaccel_args: preset-intel-qsv-h264
objects: # Object to detect - https://docs.frigate.video/configuration/objects/
  track:
    - person
  filters:
    person:
      min_area: 3500
      min_score: 0.8
      threshold: 0.8
    # - car
    # - bicycle
    # - motorcycle
detectors:
  # cpu:
  #     type: cpu
  #     num_threads: 1
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
record: # how long to record before and after motion
  events:
    pre_capture: 5
    post_capture: 5
birdseye:
  enabled: False
  mode: continuous
cameras:
  Court:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/court
          input_args: preset-rtsp-restream
          roles:
            # - record
            - detect
    live:
      stream_name: court
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      # width: 640
      # height: 360
      fps: 3
    record: # what you want Frigate to record
      enabled: True
      # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
      #     days: 1
      #     mode: all
      events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 30
    snapshots:
      enabled: True
      retain:
        default: 30
  Corner:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/corner
          input_args: preset-rtsp-restream
          roles:
            # - record
            - detect
    live:
      stream_name: corner
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      # width: 1280
      # height: 720
      fps: 3
    record: # what you want Frigate to record
      enabled: True
      # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
      #     days: 1
      #     mode: all
      events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 30
    snapshots:
      enabled: True
      retain:
        default: 30
  Street:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street
          input_args: preset-rtsp-restream
          roles:
            # - record
            - detect
    live:
      stream_name: street
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
      # width: 1280
      # height: 720
      fps: 3
    record: # what you want Frigate to record
      enabled: True
      # retain: # uncomment this section if you want Frigate to record this camera 24/7. This can use a lot of space, you have been warned!
      #     days: 1
      #     mode: all
      events: # this is the default recording mode where events are recorded, the number of days it saves events for is 10.
        retain:
          mode: active_objects
          default: 30
    snapshots:
      enabled: True
      retain:
        default: 30
```

**Reply by VoidNullNil** [reply]
> The system page provides a lot of information about what is using CPU so we can provide suggestions.

Ok, I'll add screenshot. After upgrade I'll in any case downgrade frigate.

**Reply by VoidNullNil** [reply]
![screencapture-frigate-system-2024-02-20-02_10_41](https://github.com/blakeblackshear/frigate/assets/3663022/bb11896a-54d7-4eac-aee0-f656e5235c3b)

**Reply by NickM-27** [reply]
Thanks, it would be good to see an htop output. This shows none of the processes are using much cpu besides openvino and I don't see any processes using much RAM at all

**Reply by VoidNullNil** [reply]
It's Docker, so which statistics are you expecting? Currently, it's nighttime in my country, so there's nothing to track.
But as I see CPU usage is nothing for you. 
![Screenshot_3](https://github.com/blakeblackshear/frigate/assets/3663022/b9cf0764-7beb-49c2-8aec-d3753d9f4a5e)

**Reply by NickM-27** [reply]
Actually the last camera does have high detect cpu usage and they all have higher detect fps. This is most likely due to the more sensitive motion detection. I'd suggest following the docs and tuning motion detection

**Reply by NickM-27** [reply]
Especially if there is nothing to track ^

**Reply by VoidNullNil** [reply]
I'll rolback version and add screenshot.

**Reply by VoidNullNil** [reply]
![screencapture-frigate-system-2024-02-20-02_27_46](https://github.com/blakeblackshear/frigate/assets/3663022/dcf762bc-246f-46c8-aa7d-b42b3f6a583e)
![Screenshot_4](https://github.com/blakeblackshear/frigate/assets/3663022/87f9b847-eaa5-4d9d-9fe2-4841c2a0b221)

**Reply by NickM-27** [reply]
Yes, we can see the detect fps is much lower. This is definitely due to motion detection being more sensitive, suggestion is to tune your motion detection.

**Reply by VoidNullNil** [reply]
What's the status of CPU usage? Why is the Detect fps indicating 0 in version 0.12.1, despite functioning correctly? Additionally, could you explain the differences between Intel QSV and so on?

I could conduct many more tests, but unfortunately, the outcome would be the same: CPU usage has increased from 12-15% to over 30% without changes in configuration. 

As you can see, go2rtc version was used the same (1.2.0).

**Reply by NickM-27** [reply]
Detection only runs when motion is detected or when objects are being tracked. Detect fps is 0 because motion is not detected in 0.12 but is in 0.13. This is the source of the additional cpu usage. 

Qsv and vaapi are similar but qsv is proprietary api built on top of vaapi by intel. Generally I recommend vaapi as it is less buggy and supports automatic profile selection.

**Reply by VoidNullNil** [reply]
I don't intend to accuse anyone; I simply aim to enhance this product. My apologies if my blunt responses caused any offense.

**Reply by VoidNullNil** [reply]
> This is the source of the additional cpu usage.
🤦

Does it imply that it's expected for the system to behave differently without any alterations in the configuration? Where can I find information about these changes in the documentation? Is it acceptable for you to increase CPU usage without any justification?

**Reply by VoidNullNil** [reply]
Is this considered not a bug, but a feature? If that's the case, we'll stick with version 0.12.1, as the current situation is unacceptable.

**Reply by NickM-27** [reply]
The release notes specifically said that motion is more sensitive and cpu usage may increase for some users. 

https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0

![image](https://github.com/blakeblackshear/frigate/assets/14866235/7154cfac-d9fe-43dd-ac61-e74bb6101e05)

The docs specifically walk through how to adjust this, it takes a couple minutes to tune and make motion work well for your specific camera conditions. 

There are many reasons for motion detection changing, including many users in 0.12 not seeing motion detected (and missing true objects) when it should have been detected and the objects should have been detected. it is rather bold of you to assume that there is no reason for the changes.

**Reply by NickM-27** [reply]
Multiple months were spent in the motion detection implementation across multiple iterations and feedback from users with a couple cameras to users with 30+ cameras.

**Reply by VoidNullNil** [reply]
However, there are no movements observed. Additionally, CPU usage has doubled.

I can't find a justification for the CPU usage. What's particularly strange is the inability to disable new logic. You've essentially left us with no choice.

**Reply by NickM-27** [reply]
> What's particularly strange is the inability to disable new logic. You've essentially left us with no choice.

I've said 4 times now you can configure it. You have unlimited choice

**Reply by VoidNullNil** [reply]
Alright, how can I adjust the configuration to maintain the same CPU usage percentage as in version 0.12.1?

**Reply by NickM-27** [reply]
https://docs.frigate.video/configuration/motion_detection

**Reply by VoidNullNil** [reply]
I don't have a server rack and can't afford to allocate CPU resources to detecting white noise.

**Reply by NickM-27** [reply]
The docs walk through step by step how to get motion detection to work optimally for your cameras. This will reduce cpu usage.

**Reply by VoidNullNil** [reply]
I provided you with the configuration; there is no motion detection whatsoever. It's fun. Who knows what those streams are detecting.

**Reply by NickM-27** [reply]
Right, so you should make motion detection less sensitive like I've said many times. For example, you could try disabling improve_contrast and see how it improves. The docs walk through step by step how to ensure excess motion is not detected but objects that you want to detect are detected even when there is low contrast like at night. 

Otherwise, if you don't want to configure anything, you may be best off just using 0.12

I don't think there's any more support that I can offer at this point.

**Comment by VoidNullNil** [comment]


**Reply by NickM-27** [reply]
![Screen Shot 2024-02-19 at 16 31 34 PM](https://github.com/blakeblackshear/frigate/assets/14866235/a0192724-d817-488b-a13c-b0efeb71eef3)

**Reply by VoidNullNil** [reply]
Does the term "discussion category" not resonate with you? I was inquiring about the section for issues.

**Reply by NickM-27** [reply]
we recently moved from issues to discussions as this is what GitHub recommends. Issues are for things that can be closed with a PR like feature requests.

**Reply by VoidNullNil** [reply]
Sure, feel free to submit a new PR request regarding this issue: https://github.com/AlexxIT/go2rtc/issues/947.

**Comment by VoidNullNil** [comment]
Thanks, @NickM-27, for your patience with the responses in this thread. Your answers prompted me to conduct some tests. The first thing I noticed was a change in how motion detection works for all cameras. The parameters in `detect` are somewhat unclear compared to version 0.12. Specifying global parameters:

```yaml
detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
```

partially reduced CPU usage. Memory usage increased, but I understand this is the cost for the new motion detection method. Considering all these changes, even OpenVINO struggles to keep up with tracking the changes. Therefore, one must pay attention to the parameter:

```yaml
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
```

If you have a mini PC, the only solution is to buy an Edge TPU and set up the correct model. The one that comes with Frigate for Edge TPU is about twice as bad as the one for OpenVINO.

I'll say this: if you have a lot of time, you can play around and even get good results. But for the average person, it's all too complicated. It probably also played a role that the backend uses Python, where solutions in, for example, Go/Rust would probably use half as many resources.

In any case, thanks to the team for your work and your contribution to open source. And once again, my apologies to @NickM-27 for my harsh messages.
