### DISCUSSION TITLE
[Support]: 13.2 breaks video compression? Run out of diskspace in 2 hours

### DISCUSSION THREAD

**Discussion by Moondevil-ha** [blakeblackshear/frigate#9930] [General Support] [answered]
### Describe the problem you are having

I upgraded to 13.2 last night, just before bed. When checking the system this morning, all recordings had been deleted (last 5 days). The logs showed that the system ran out of space within 2 hours and initiated a purge. I didn't capture logs as I had to immediately get the system working again, and reverted to backup. 13.1 is again stable. If I get a chance, I'll reapply and get the log output at a quiet time. Have I missed a change that means I need additional settings?

### Version

13.2

### Frigate config file

```yaml
# frigate.yml
mqtt:
  host: 192.168.1.248
  user: mqtt-user
  password: xxxxxxxx
  
#birdseye:
  # Optional: Enable birdseye view (default: shown below)
#  enabled: False
  # Optional: Width of the output resolution (default: shown below)
#  width: 1280
  # Optional: Height of the output resolution (default: shown below)
#  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
#  mode: continuous
    
go2rtc:
  streams:
  #  rtsp_cam: # <- for RTSP streams
  #    - rtsp://192.168.1.5:554/live0 # <- stream which supports video & aac audio
  #    - "ffmpeg:rtsp_cam#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Back_Garden: # <- for other streams
  #    - http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx # <- stream which supports video & aac audio
  #    - "ffmpeg:Back_Garden#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
      - rtsp://admin:xxxxxxxx@192.168.1.75:554/h264Preview_01_main 
      - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Sideway:
  #    - http://192.168.1.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
  #    - "ffmpeg:Sideway#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
      - rtsp://admin:xxxxxxxx@192.168.1.11:554/h264Preview_01_main 
      - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Front_Yard:
  #    - http://192.168.1.8/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
  #    - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
      - rtsp://admin:xxxxxxxx@192.168.1.8:554/h264Preview_01_main 
      - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Downstairs:
      - rtsp://admin:xxxxxxxx@192.168.1.65:554/h264Preview_01_main 
      - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Upstairs:
      - rtsp://admin:xxxxxxxx@192.168.1.66:554/h264Preview_01_main
      - "ffmpeg:Front_Yard#audio=opus" # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
  webrtc:
    candidates:
      - 192.168.1.248:8555
      - stun:8555

cameras:
  Back_Garden:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args:  preset-vaapi
      #  - -hwaccel
      #  - vaapi
      #  - -hwaccel_device
      #  - /dev/dri/renderD128
      #  - -hwaccel_output_format
      #  - yuv420p
      #  - -c:v 
      #  - h264_cuvid
      input_args:
        #- preset-rtsp-restream-low-latency
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    #    record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Garden?video=copy&audio=aac
      #  - path: rtmp://192.168.1.75/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
      #  - path: http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75

    snapshots:
      enabled: True
      timestamp: True
    record:
      # Optional: Enable recording (default: shown below)
      enabled: True
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 5
          mode: all
          # Optional: Per object retention days
          objects:
            person: 10
    motion:
      mask:
        - 0,410,710,390,876,1158,379,1920,0,1920
        - 2560,234,1891,214,2560,633
  Sideway:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      #  - -hwaccel
      #  - vaapi
      #  - -hwaccel_device
      #  - /dev/dri/renderD128
      #  - -hwaccel_output_format
      #  - yuv420p
      #  - -c:v 
      #  - h264_cuvid
      input_args:
        #- preset-rtsp-restream-low-latency
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    #    record: preset-record-generic-audio-aac
      
      inputs:
        - path: rtsp://127.0.0.1:8554/Sideway?video=copy&audio=aac
      #  - path: rtmp://192.168.1.75/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
      #  - path: http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1440
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
          mask:
            - 2389,1440,1588,818,1233,519,2560,0,2560,1440

    snapshots:
      enabled: True
      timestamp: True
    record:
      # Optional: Enable recording (default: shown below)
      enabled: True
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 5
          mode: all
          # Optional: Per object retention days
          objects:
            person: 10
    motion:
      mask:
        - 2389,1440,1588,818,1233,519,2560,0,2560,1440
    
  Front_Yard:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      #  - -hwaccel
      #  - vaapi
      #  - -hwaccel_device
      #  - /dev/dri/renderD128
      #  - -hwaccel_output_format
      #  - yuv420p
      #  - -c:v 
      #  - h264_cuvid
      input_args:
        #- preset-rtsp-restream-low-latency
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    #    record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Yard?video=copy&audio=aac
      #  - path: rtmp://192.168.1.75/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
      #  - path: http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
  
    snapshots:
      enabled: True
      timestamp: True
    record:
            # Optional: Enable recording (default: shown below)
      enabled: True
            # Optional: Number of days to retain recordings regardless of events (default: shown below)
            # NOTE: This should be set to 0 and retention should be defined in events section below
            #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
            # Optional: Event recording settings
      events:
              # Optional: Maximum length of time to retain video during long events. (default: shown below)
              # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
              #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
              # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
              # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
              # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
              # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
                # Required: Default retention days (default: shown below)
          default: 5
          mode: all
                # Optional: Per object retention days
          objects:
            person: 15

  Downstairs:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      #  - -hwaccel
      #  - vaapi
      #  - -hwaccel_device
      #  - /dev/dri/renderD128
      #  - -hwaccel_output_format
      #  - yuv420p
      #  - -c:v 
      #  - h264_cuvid
      input_args:
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    #    record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://127.0.0.1:8554/Downstairs?video=copy&audio=aac
      #  - path: rtmp://192.168.1.75/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
      #  - path: http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1440
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
  
    snapshots:
      enabled: True
      timestamp: True
    record:
            # Optional: Enable recording (default: shown below)
      enabled: True
            # Optional: Number of days to retain recordings regardless of events (default: shown below)
            # NOTE: This should be set to 0 and retention should be defined in events section below
            #       if you only want to retain recordings of events.
      retain: 
        days: 1
        mode: all
            # Optional: Event recording settings
      events:
              # Optional: Maximum length of time to retain video during long events. (default: shown below)
              # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
              #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
              # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
              # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
              # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
              # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
                # Required: Default retention days (default: shown below)
          default: 5
          mode: all
                # Optional: Per object retention days
          objects:
            person: 5

  Upstairs:
    #rtmp:
    #  enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      #  - -hwaccel
      #  - vaapi
      #  - -hwaccel_device
      #  - /dev/dri/renderD128
      #  - -hwaccel_output_format
      #  - yuv420p
      #  - -c:v 
      #  - h264_cuvid
      input_args:
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    #    record: preset-record-generic-audio-aac      
      inputs:
        - path: rtsp://127.0.0.1:8554/Upstairs?video=copy&audio=aac
      #  - path: rtmp://192.168.1.75/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
      #  - path: http://192.168.1.75/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
            #- rtmp
    detect:
      width: 2560
      height: 1440
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
  
    snapshots:
      enabled: True
      timestamp: True
    record:
            # Optional: Enable recording (default: shown below)
      enabled: True
            # Optional: Number of days to retain recordings regardless of events (default: shown below)
            # NOTE: This should be set to 0 and retention should be defined in events section below
            #       if you only want to retain recordings of events.
      retain: 
        days: 1
        mode: all
            # Optional: Event recording settings
      events:
              # Optional: Maximum length of time to retain video during long events. (default: shown below)
              # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
              #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
              # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
              # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
              # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
              # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
                # Required: Default retention days (default: shown below)
          default: 5
          mode: all
                # Optional: Per object retention days
          objects:
            person: 5

detectors:
  coral_pci:
    type: edgetpu
    device: pci
  coral_usb:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
Couldn't capture - will reapply
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink 511W, 410W, E1 Pro
