### DISCUSSION TITLE
[Camera Support]: PTZ on Reolink E1?

### DISCUSSION THREAD

**Discussion by lloydsmart** [blakeblackshear/frigate#9940] [Camera Support] [answered]
### Describe the problem you are having

Hi, is it possible to get PTZ control working via Frigate for the Reolink E1? I see that it is supported for the E1 Pro and E1 Zoom.

Thanks.

### Version

0.13.2

### Frigate config file

```yaml
# yaml-language-server: $schema=http://apoc.mydomain.com:5000/api/config/schema.json
mqtt:
  enabled: true
  host: mqtt.mydomain.com
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  stats_interval: 300

detectors:
  coral1:
    type: edgetpu
    device: pci:0

model:
  path: plus://*************************************

audio:
  enabled: true
  max_not_heard: 10
  min_volume: 1000
  listen:
    - bark
    - fire_alarm
    - scream
    - yell

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 4
  output_args:
    record: preset-record-generic-audio-copy

detect:
  stationary:
    threshold: 100

objects:
  filters:
    dog:
      threshold: 0.85

record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 3
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

rtmp:
  enabled: false

go2rtc:
  streams:
    front_door:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@doorbell.mydomain.com:554/h264Preview_01_main #h264/AAC - MSE/Record/Audio
      - "ffmpeg:front_door#audio=opus" #h264/OPUS - WebRTC
    front:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@front.mydomain.com:554/h265Preview_01_main #h265/AAC - MSE/Record/Audio
    side:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@side.mydomain.com:554/h265Preview_01_main #h265/AAC - MSE/Record/Audio
    garden:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@garden.mydomain.com:554/h265Preview_01_main #h265/AAC - MSE/Record/Audio
    kitchen:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@kitchen.mydomain.com:554/h264Preview_01_main #h264/AAC - MSE/Record/Audio
      - "ffmpeg:kitchen#audio=opus" #h264/OPUS - WebRTC
    livingroom:
      - "ffmpeg:rtsp://neolink:9554/livingroom/mainStream#video=copy#audio=copy#audio=aac" #h264/AAC - MSE/Record/Audio
      - "ffmpeg:rtsp://neolink:9554/livingroom/mainStream#video=copy#audio=copy#audio=opus" #h264/OPUS - WebRTC
  webrtc:
    candidates:
      - apoc.mydomain.com:8555
      - 192.168.188.5:8555
      - stun:8555
    listen: ":8555"

cameras:
  front_door:
    detect:
      width: 896
      height: 672
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: https://doorbell.mydomain.com/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
    webui_url: "https://doorbell.mydomain.com"
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - motorcycle
        - horse
        - package
      filters:
        car:
          mask:
            - 0,386,142,289,101,267,42,233,0,227 # Next door driveway
    motion:
      mask:
        - 640,0,640,40,255,40,255,0 # Timestamp
        - 182,367,180,430,413,476,421,432,399,407,414,379,390,361,312,348,202,348 # Left bush
        - 762,473,896,455,896,357,787,350,538,376,524,415,519,485 # Right bush
    zones:
      near_front_door:
        coordinates: 434,456,505,468,431,672,0,672,0,597,122,545,145,627,194,662
        objects:
          - person
          - package
  front:
    detect:
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: https://front.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
    webui_url: "https://front.mydomain.com"
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - motorcycle
        - horse
      filters:
        car:
          mask: 565,0,640,0,640,42 # Motorway
    motion:
      mask:
        - 420,0,420,30,220,30,220,0 # Timestamp
        - 565,0,640,0,640,42 # Motorway
        - 308,272,323,230,267,199,235,208,160,232,21,296,0,364,0,419 # Left bush
        - 458,137,491,124,571,122,640,127,640,166,640,205,572,183,490,185,367,258,339,227,350,161,379,170,401,154,418,168 # Right bush
    zones:
      lawn_left:
        coordinates: 489,480,0,480,0,426,304,278,466,391,511,447
        objects:
          - person
          - dog
          - cat
      lawn_right:
        coordinates: 501,354,606,195,562,177,498,183,354,258
        objects:
          - person
          - dog
          - cat

  side:
    detect:
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/side
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: https://side.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
    webui_url: "https://side.mydomain.com"
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - motorcycle
    motion:
      mask:
        - 410,0,410,25,218,25,218,0 # Timestamp
        - 575,55,577,122,333,93,335,43 # Motorway / bridge
        - 0,51,248,36,368,113,0,233 # Other street
        - 450,180,500,180,500,130,450,130 # Tree
        - 435,237,476,231,480,204,454,186,427,205,398,216,382,241,384,269 # Hedge by driveway
    zones:
      back_path:
        coordinates: 557,316,555,288,381,270,363,290
      lawn_side:
        coordinates: 530,480,554,313,374,286,139,480
  garden:
    detect:
      width: 640
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garden
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: https://garden.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
    webui_url: "https://garden.mydomain.com"
    audio:
      min_volume: 500
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
        - 410,0,410,25,218,25,218,0
    zones:
      mud:
        coordinates: 640,88,421,39,221,31,121,47,56,93,78,138,137,86,172,148,474,194,394,449,640,480
        objects:
          - dog
          - cat
          - person
      gate:
        coordinates: 48,97,125,102,76,151
        objects:
          - person
  kitchen:
    detect:
      width: 1024
      height: 1024
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: https://kitchen.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
    webui_url: "https://kitchen.mydomain.com"
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 217,526,362,566,348,625,181,730,112,666,87,588,84,532,110,487,178,494 # Sofa
        dog:
          mask:
            - 217,526,362,566,348,625,181,730,112,666,87,588,84,532,110,487,178,494 # Sofa
    motion:
      mask:
        - 700,0,700,40,325,40,325,0 # Timestamp
        - 268,185,311,235,207,269,174,244 # TV
    zones:
      utility_room:
        coordinates: 423,326,551,342,611,90,470,72,306,119
        objects:
          - person
          - dog
      back_door:
        coordinates: 180,333,125,558,40,569,48,417,99,287
        objects:
          - person
          - dog
  livingroom:
    detect:
      width: 704
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/livingroom
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://neolink:9554/livingroom/subStream
          input_args: preset-rtsp-generic
          roles:
            - detect
    motion:
      mask:
        - 540,0,540,40,160,40,160,0 # Timestamp
    objects:
      track:
        - dog

ui:
  live_mode: webrtc
  time_format: browser
  date_style: medium
  time_style: medium
  strftime_fmt: "%d/%m/%Y %H:%M"

telemetry:
  version_check: true
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55789e9c1140] max delay reached. need to consume packet
[rtsp @ 0x55789e9c1140] RTP: missed 8 packets
[h264 @ 0x55789e9c4f80] error while decoding MB 55 33, bytestream -5
[h264 @ 0x55789e9c4f80] concealing 6906 DC, 6906 AC, 6906 MV errors in P frame
Input #0, rtsp, from 'rtsp://neolink:9554/livingroom/mainStream':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2304x1296, 19.67 tbr, 90k tbn
  Stream #0:1: Audio: pcm_s16be, 16000 Hz, stereo, s16, 512 kb/s
```

### Frigate stats

```json
{"cameras":{"front_door":{"audio_dBFS":-33.2244,"audio_rms":714.8729,"camera_fps":5.0,"capture_pid":505,"detection_enabled":1,"detection_fps":3.5,"ffmpeg_pid":509,"pid":493,"process_fps":5.0,"skipped_fps":0.0},"garden":{"audio_dBFS":-52.4541,"audio_rms":78.1169,"camera_fps":5.1,"capture_pid":518,"detection_enabled":1,"detection_fps":6.8,"ffmpeg_pid":528,"pid":498,"process_fps":5.1,"skipped_fps":0.0},"kitchen":{"audio_dBFS":-54.7829,"audio_rms":59.7456,"camera_fps":5.0,"capture_pid":525,"detection_enabled":1,"detection_fps":0.8,"ffmpeg_pid":537,"pid":501,"process_fps":5.0,"skipped_fps":0.0},"livingroom":{"audio_dBFS":-55.4782,"audio_rms":55.1493,"camera_fps":5.0,"capture_pid":532,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":726774,"pid":502,"process_fps":5.0,"skipped_fps":0.0},"side":{"audio_dBFS":-27.4711,"audio_rms":1386.415,"camera_fps":5.0,"capture_pid":512,"detection_enabled":1,"detection_fps":5.1,"ffmpeg_pid":167567,"pid":497,"process_fps":5.0,"skipped_fps":0.0},"front":{"audio_dBFS":-32.5184,"audio_rms":775.4045,"camera_fps":5.1,"capture_pid":508,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":513,"pid":494,"process_fps":5.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"92":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"97":{"cmdline":"/config/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"25.7","cpu_average":"27","mem":"0.8"},"106":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"107":{"cmdline":"python3 -u -m frigate","cpu":"8.6","cpu_average":"5","mem":"5.5"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.2","cpu_average":"0","mem":"0.3"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"150":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"158":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"174":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"204":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"238":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"265":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"438":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.5"},"440":{"cmdline":"frigate.recording_manager","cpu":"7.0","cpu_average":"4","mem":"1.8"},"449":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(63)","cpu":"0.3","cpu_average":"0","mem":"0.0"},"450":{"cmdline":"frigate.detector.coral1","cpu":"2.6","cpu_average":"2","mem":"0.7"},"452":{"cmdline":"frigate.output       ","cpu":"1.9","cpu_average":"1","mem":"0.6"},"455":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 896x672 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"456":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"458":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"473":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"474":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1024x1024 -i pipe: -f mpegts -s 720x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"475":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"476":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"493":{"cmdline":"frigate.process:front_door","cpu":"7.6","cpu_average":"5","mem":"0.9"},"494":{"cmdline":"frigate.process:front","cpu":"2.4","cpu_average":"5","mem":"0.9"},"497":{"cmdline":"frigate.process:side","cpu":"12.4","cpu_average":"7","mem":"0.9"},"498":{"cmdline":"frigate.process:garden","cpu":"7.6","cpu_average":"7","mem":"0.9"},"501":{"cmdline":"frigate.process:kitchen","cpu":"1.5","cpu_average":"4","mem":"1.1"},"502":{"cmdline":"frigate.process:livingroom","cpu":"1.7","cpu_average":"5","mem":"0.9"},"505":{"cmdline":"frigate.capture:front_door","cpu":"1.5","cpu_average":"1","mem":"0.7"},"508":{"cmdline":"frigate.capture:front","cpu":"0.9","cpu_average":"0","mem":"0.7"},"509":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i https://doorbell.mydomain.com/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -r 5 -vf fps=5,scale=896:672 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"8.6","cpu_average":"9","mem":"0.2"},"512":{"cmdline":"frigate.capture:side","cpu":"0.7","cpu_average":"0","mem":"0.7"},"513":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i https://front.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.4","cpu_average":"2","mem":"0.1"},"518":{"cmdline":"frigate.capture:garden","cpu":"0.9","cpu_average":"0","mem":"0.7"},"524":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_door -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front_door@%Y%m%d%H%M%S%z.mp4","cpu":"1.2","cpu_average":"1","mem":"0.1"},"525":{"cmdline":"frigate.capture:kitchen","cpu":"2.1","cpu_average":"2","mem":"0.7"},"528":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i https://garden.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.8","cpu_average":"2","mem":"0.1"},"529":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/front@%Y%m%d%H%M%S%z.mp4","cpu":"1.2","cpu_average":"1","mem":"0.1"},"532":{"cmdline":"frigate.capture:livingroom","cpu":"0.9","cpu_average":"0","mem":"0.8"},"533":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/side -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/side@%Y%m%d%H%M%S%z.mp4","cpu":"1.7","cpu_average":"1","mem":"0.1"},"537":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i https://kitchen.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -r 5 -vf fps=5,scale=1024:1024 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"4.8","cpu_average":"5","mem":"0.2"},"540":{"cmdline":"frigate.audio_manager","cpu":"5.7","cpu_average":"7","mem":"1.3"},"541":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garden -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4","cpu":"1.6","cpu_average":"1","mem":"0.1"},"555":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front_door -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.0","cpu_average":"1","mem":"0.1"},"556":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/front -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.0","cpu_average":"1","mem":"0.0"},"559":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/side -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.2","cpu_average":"1","mem":"0.1"},"563":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/garden -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.0","cpu_average":"1","mem":"0.1"},"566":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/kitchen -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"1.4","cpu_average":"1","mem":"0.1"},"167567":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i https://side.mydomain.com/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=*&password=* -r 5 -vf fps=5,scale=640:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.4","cpu_average":"2","mem":"0.2"},"249080":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/kitchen -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/kitchen@%Y%m%d%H%M%S%z.mp4","cpu":"1.6","cpu_average":"1","mem":"0.1"},"726629":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/livingroom -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/livingroom@%Y%m%d%H%M%S%z.mp4","cpu":"0.9","cpu_average":"0","mem":"0.3"},"726630":{"cmdline":"ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://neolink:9554/livingroom/mainStream -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 aac -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/5a5f4300913006e693c01bac9afbb32d","cpu":"16.4","cpu_average":"19","mem":"0.4"},"726631":{"cmdline":"ffmpeg -vn -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://localhost:8554/livingroom -f s16le -ar 16000 -ac 1 -y pipe:","cpu":"0.7","cpu_average":"0","mem":"0.4"},"726774":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 4 -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://neolink:9554/livingroom/subStream -r 5 -vf fps=5,scale=704:480 -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"2.9","cpu_average":"3","mem":"0.5"},"763190":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"763948":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":16.3,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":6.09,"pid":450}},"processes":{"audioDetector":{"pid":540},"go2rtc":{"pid":97},"logger":{"pid":438},"recording":{"pid":440}},"service":{"last_updated":1708446356,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":375.4,"mount_type":"tmpfs","total":384.0,"used":8.6},"/media/frigate/clips":{"free":1684140.1,"mount_type":"xfs","total":3760810.8,"used":2076670.7},"/media/frigate/recordings":{"free":1684140.1,"mount_type":"xfs","total":3760810.8,"used":2076670.7},"/tmp/cache":{"free":934.2,"mount_type":"tmpfs","total":953.7,"used":19.5}},"temperatures":{"apex_0":38.55},"uptime":113795,"version":"0.13.2-6476f8a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink E1

### Any other information that may be helpful

Got the Reolink E1 to work via Neolink.
