### DISCUSSION TITLE
[Config Support]: Recordings without motion are being saved to filesystem

### DISCUSSION THREAD

**Discussion by JohnLuc** [blakeblackshear/frigate#9951] [Config Support] [answered]
### Describe the problem you are having

Frigate is apparently saving more recordings to the filesystem than there are in the Events view of the UI.

Example: if I look at the Events page of the UI, I see event clips of all people that have come into view of my cameras. This seems to be working perfectly: every instance of a person coming into view of any camera shows up in the Events page with a video clip I can view. However, if I look at the filesystem where frigate places all recordings, I see hundreds of recordings, from all seven of my cameras, with no apparent motion (no person found).

What combination of configuration values would make it so only recordings that are found in the Events page are persisted to the filesystem?

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: true
  restream: false
  quality: 8
  width: 1280
  height: 720
  mode: continuous

detect:
  width: 640
  height: 480
  fps: 4
  stationary:
    interval: 50
    threshold: 50

detectors:
  openvino:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  enabled: true
  retain:
    default: 30

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion

objects:
  track:
    - person
    - cat
    #- umbrella
  filters:
    person:
      min_area: 10000
      max_area: 1000000
      threshold: 0.80
    umbrella:
      threshold: 0.95

cameras:
  BackDoor:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.133:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.133:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 1
    ui:
      order: 1
    motion:
      threshold: 50

  SideGate:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.132:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.132:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 2
    ui:
      order: 2
    record:
      events:
        required_zones:
          - inside_yard
    snapshots:
      required_zones:
        - inside_yard
    motion:
      mask:
        - 640,371,640,0,307,0
      threshold: 50
    zones:
      inside_yard:
        coordinates: 0,0,0,480,640,480,640,369,332,35,244,0

  EastPerimeter-Back:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.131:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.131:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 3
    ui:
      order: 3
    record:
      events:
        required_zones:
          - inside_yard
    snapshots:
      required_zones:
        - inside_yard
    motion:
      mask:
        - 0,0,455,0,0,338
      threshold: 50
    zones:
      inside_yard:
        coordinates: 0,480,640,480,640,323,396,405,640,141,640,0,437,0,0,346

  EastPerimeter-Front:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.135:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.135:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 4
    ui:
      order: 4
    record:
      events:
        required_zones:
          - inside_yard
    snapshots:
      required_zones:
        - inside_yard
    motion:
      mask:
        - 640,395,640,0,156,0
      threshold: 50
    zones:
      inside_yard:
        coordinates: 266,480,640,480,640,405,149,0,0,0,0,101

  FrontYard-East:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.136:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.136:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 5
    ui:
      order: 5
    record:
      events:
        required_zones:
          - inside_yard
    snapshots:
      required_zones:
        - inside_yard
    motion:
      mask:
        - 640,480,486,480,323,480,616,0,640,0
        - 350,448,326,480,298,480,154,349,175,328
      threshold: 50
    zones:
      inside_yard:
        coordinates: 640,0,0,0,0,480,0,480,343,480

  FrontYard-West:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.134:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.134:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 6
    ui:
      order: 6
    record:
      events:
        required_zones:
          - inside_yard
    snapshots:
      required_zones:
        - inside_yard
    motion:
      mask:
        - 197,44,640,193,640,0,0,0,0,123
      threshold: 50
    zones:
      inside_yard:
        coordinates: 0,480,640,480,640,194,200,47,0,127

  WestPerimeter:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.130:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://username:password@192.168.1.130:554/Streaming/Channels/202
          roles:
            - detect
            - rtmp
    birdseye:
      order: 7
    ui:
      order: 7
    motion:
      threshold: 50
```

### Relevant log output

```shell
I don't believe an error is occurring here so no relevant log output to show.
```

### Frigate stats

```json
{
  "cameras": {
    "BackDoor": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4,
      "capture_pid": 906,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 913,
      "pid": 888,
      "process_fps": 4,
      "skipped_fps": 0
    },
    "EastPerimeter-Back": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4.1,
      "capture_pid": 919,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 941,
      "pid": 892,
      "process_fps": 4.1,
      "skipped_fps": 0
    },
    "EastPerimeter-Front": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4.1,
      "capture_pid": 939,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 949,
      "pid": 895,
      "process_fps": 4.1,
      "skipped_fps": 0
    },
    "FrontYard-East": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4,
      "capture_pid": 943,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 955,
      "pid": 898,
      "process_fps": 4,
      "skipped_fps": 0
    },
    "FrontYard-West": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4,
      "capture_pid": 952,
      "detection_enabled": 1,
      "detection_fps": 0,
      "ffmpeg_pid": 969,
      "pid": 901,
      "process_fps": 4,
      "skipped_fps": 0
    },
    "SideGate": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4,
      "capture_pid": 911,
      "detection_enabled": 1,
      "detection_fps": 0.4,
      "ffmpeg_pid": 938,
      "pid": 890,
      "process_fps": 4,
      "skipped_fps": 0
    },
    "WestPerimeter": {
      "audio_dBFS": 0,
      "audio_rms": 0,
      "camera_fps": 4.1,
      "capture_pid": 958,
      "detection_enabled": 1,
      "detection_fps": 0.4,
      "ffmpeg_pid": 968,
      "pid": 904,
      "process_fps": 4.1,
      "skipped_fps": 0
    }
  },
  "cpu_usages": {
    "1": {
      "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "15": {
      "cmdline": "s6-supervise s6-linux-init-shutdownd",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "16": {
      "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd 
-c /run/s6/basedir -g 3000 -C -B",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "24": {
      "cmdline": "s6-supervise go2rtc-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "25": {
      "cmdline": "s6-supervise go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "26": {
      "cmdline": "s6-supervise frigate-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "27": {
      "cmdline": "s6-supervise go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "28": {
      "cmdline": "s6-supervise nginx-log",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "29": {
      "cmdline": "s6-supervise nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "30": {
      "cmdline": "s6-supervise s6rc-oneshot-runner",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "31": {
      "cmdline": "s6-supervise frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "32": {
      "cmdline": "s6-supervise s6rc-fdholder",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "41": {
      "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i 
data/rules",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "42": {
      "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- 
/package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- 
/package/admin/s6/command/s6-sudod -t 30000 -- 
/package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "80": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "81": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "82": {
      "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "89": {
      "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "97": {
      "cmdline": "python3 -u -m frigate",
      "cpu": "5.0",
      "cpu_average": "2",
      "mem": "0.3"
    },
    "98": {
      "cmdline": "bash ./run.user go2rtc-healthcheck",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "113": {
      "cmdline": "nginx: master process nginx",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "145": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "146": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "147": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "148": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "151": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "166": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "195": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "223": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "251": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "268": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "285": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "315": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "358": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "386": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "425": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "461": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "501": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "538": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "582": {
      "cmdline": "nginx: worker process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "634": {
      "cmdline": "nginx: worker process",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "674": {
      "cmdline": "nginx: cache manager process",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "870": {
      "cmdline": "frigate.logger       ",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "872": {
      "cmdline": "frigate.recording_manager",
      "cpu": "0.0",
      "cpu_average": "3",
      "mem": "0.2"
    },
    "880": {
      "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker 
import main;main(62)",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "881": {
      "cmdline": "frigate.detector.openvino",
      "cpu": "46.1",
      "cpu_average": "6",
      "mem": "0.4"
    },
    "882": {
      "cmdline": "frigate.output       ",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "886": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "888": {
      "cmdline": "frigate.process:BackDoor",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "889": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "890": {
      "cmdline": "frigate.process:SideGate",
      "cpu": "7.1",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "892": {
      "cmdline": "frigate.process:EastPerimeter-Back",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "893": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "895": {
      "cmdline": "frigate.process:EastPerimeter-Front",
      "cpu": "2.1",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "897": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "898": {
      "cmdline": "frigate.process:FrontYard-East",
      "cpu": "0.7",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "900": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "901": {
      "cmdline": "frigate.process:FrontYard-West",
      "cpu": "1.4",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "903": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "904": {
      "cmdline": "frigate.process:WestPerimeter",
      "cpu": "6.4",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "906": {
      "cmdline": "frigate.capture:BackDoor",
      "cpu": "1.4",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "907": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i 
pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "911": {
      "cmdline": "frigate.capture:SideGate",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "912": {
      "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i 
pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
      "cpu": "0.0",
      "cpu_average": "3",
      "mem": "0.1"
    },
    "913": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.133:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.5",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "919": {
      "cmdline": "frigate.capture:EastPerimeter-Back",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "938": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.132:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.8",
      "cpu_average": "1",
      "mem": "0.2"
    },
    "939": {
      "cmdline": "frigate.capture:EastPerimeter-Front",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "940": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.133:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/BackDoor@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "941": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.131:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "4.3",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "943": {
      "cmdline": "frigate.capture:FrontYard-East",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "949": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.135:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.8",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "952": {
      "cmdline": "frigate.capture:FrontYard-West",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "953": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.132:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/SideGate@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "954": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.131:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/EastPerimeter-Back@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "955": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.136:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.8",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "958": {
      "cmdline": "frigate.capture:WestPerimeter",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.2"
    },
    "968": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.130:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "2.1",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "969": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.134:554/Streaming/Channels/202 -r 4 -vf 
fps=4,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p 
-threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
      "cpu": "3.5",
      "cpu_average": "2",
      "mem": "0.2"
    },
    "970": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.135:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/EastPerimeter-Front@%Y%m%d%H%M%S%z.mp4",
      "cpu": "1.4",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "975": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.134:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/FrontYard-West@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "976": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.130:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/WestPerimeter@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "977": {
      "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 
-hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device 
/dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg 
Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags 
+genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 
-use_wallclock_as_timestamps 1 -i 
rtsp://*:*@192.168.1.136:554/Streaming/Channels/1 -f segment -segment_time 10 
-segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an 
/tmp/cache/FrontYard-East@%Y%m%d%H%M%S%z.mp4",
      "cpu": "0.7",
      "cpu_average": "0",
      "mem": "0.0"
    },
    "271049": {
      "cmdline": "sleep 30s",
      "cpu": "0.0",
      "cpu_average": "0",
      "mem": "0.0"
    }
  },
  "detection_fps": 0.8,
  "detectors": {
    "openvino": {
      "detection_start": 0,
      "inference_speed": 14.63,
      "pid": 881
    }
  },
  "gpu_usages": {
    "error-gpu": {
      "gpu": -1,
      "mem": -1
    }
  },
  "processes": {
    "go2rtc": {
      "pid": 89
    },
    "logger": {
      "pid": 870
    },
    "recording": {
      "pid": 872
    }
  },
  "service": {
    "last_updated": 1708481023,
    "latest_version": "0.13.2",
    "storage": {
      "/dev/shm": {
        "free": 492.9,
        "mount_type": "tmpfs",
        "total": 500,
        "used": 7.1
      },
      "/media/frigate/clips": {
        "free": 11006491,
        "mount_type": "btrfs",
        "total": 22888448,
        "used": 11881993.5
      },
      "/media/frigate/recordings": {
        "free": 11006491,
        "mount_type": "btrfs",
        "total": 22888448,
        "used": 11881993.5
      },
      "/tmp/cache": {
        "free": 1876.3,
        "mount_type": "tmpfs",
        "total": 1907.4,
        "used": 31
      }
    },
    "temperatures": {},
    "uptime": 22518,
    "version": "0.13.2-6476f8a"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment, marked as answer]
```
  enabled: true
  retain:
    days: 7
    mode: motion
```

You have configured frigate to record all motion continuously, this does not show on the events page but in the recordings page.
