### DISCUSSION TITLE
[Support]: After upgrading to Frigate 0.13 "new" MQTT events do not have zones

### DISCUSSION THREAD

**Discussion by mstolpner** [blakeblackshear/frigate#9967] [General Support]
### Describe the problem you are having

After upgrading to Frigate 0.13 "new" MQTT events have empty before and after zone lists. The next "update" message arrives with zones populated.

### Version

0.13.2

### Frigate config file

```yaml
database:
  path: /media/frigate/frigate.db


logger:
  default: info
  logs:
    frigate.event: debug


mqtt: 
  host: mqtt.domain.com
  user: mqtt
  password: ""
  client_id: frigate
  topic_prefix: frigate
  stats_interval: 60


go2rtc:   
  rtsp:   
    username: "user"
    password: "password"
  streams:
    entrance:       # Full resolution stream 
      - rtsp://user:password@cam1:554/Streaming/channels/101
      - "ffmpeg:entrance#audio=pcm#audio=volume"
    entrance_sub:   # Low resolution stream 
      - rtsp://user:password@cam1:554/Streaming/channels/102
      - "ffmpeg:entrance_sub#audio=pcm#audio=volume"
    doorbell:       # Full resolution stream 
      - "ffmpeg:http://doorbell/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
    doorbell_sub:       # Low resolution stream 
      - "ffmpeg:http://doorbell/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password#video=copy#audio=copy#audio=opus"
  ffmpeg:    
    bin: ffmpeg
    volume: "-af \"volume=30dB\""
  webrtc:
    candidates:
      - 192.168.171.10:8555
      - stun:8555


ffmpeg:
  hwaccel_args: preset-vaapi
  

cameras:
  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - rtmp
        - path: rtsp://127.0.0.1:8554/doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    zones:
      front_door:
        coordinates: 30,1920,2530,1892,2560,907,2086,1168,1332,1196,1297,557,30,585
      garage_parking:
        coordinates: 2228,1173,2297,1041,2121,988,1281,1045,1134,1205
      street:
        coordinates: 146,1069,1381,1075,1379,995,146,946
    objects:
      track:
        - person
        - car
        - motorcycle
        - face
        - amazon
        - ups
        - fedex
        - package
      filters:
        person:
          min_score: 0.65
          threshold: 0.8
    detect:
      enabled: True
      width: 2560           
      height: 1920
      fps: 4
      max_disappeared: 20   
    record:
      enabled: True
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 1920
      quality: 100
    live:
      stream_name: doorbell_sub

  entrance:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance      # High Resolution Stream
          roles:
            - record
            - detect                                # Use full resolution for detect due to large camera viewing angle
        - path: rtsp://127.0.0.1:8554/entrance_sub  # Low Resolution Stream
          roles:
            - rtmp
    zones:
      driveway:
        coordinates: 2193,891,2645,761,2891,362,2106,277,1453,346,1025,671,2019,698
      front_steps:
        coordinates: 3840,2160,3076,1763,2217,1078,1982,716,1060,671,45,1094,24,2123,853,2136
      front_trail:
        coordinates: 1083,470,909,362,45,573,45,951
      street:
        coordinates: 2138,98,785,87,1083,378,1805,296,2494,320,3152,423,3818,637,3840,412
      garage_parking: 
        coordinates: 3813,2088,3840,888,2920,465,2230,935
    objects:
      track:
        - person
        - car
        - motorcycle
        - face
        - amazon
        - ups
        - fedex
        - package
      filters:
        person:
          min_score: 0.65
          threshold: 0.8
    detect:
      enabled: True
      width: 3840           # Use large resolution due to large camera viewing angle to satisfy pixel area requirements for face frame
      height: 2160
      fps: 4
      max_disappeared: 20   # Optional. Number of frames without a detection before Frigate considers an object to be gone. (default 5x the frame rate)
    record:
      enabled: True
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 2160
      quality: 100
    live:
      stream_name: entrance_sub  
    motion:
      mask:
        - 2111,951,2423,914,3182,1163,3840,1694,3514,2135,2613,2111,1800,1403
        - 1431,0,0,0,0,853


detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
      
model:
  path: plus://nnnnn

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: False   # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive for daytime.
  mqtt_off_delay: 30        # Delay when updating camera motion through MQTT from ON -> OFF 

record:
  enabled: True
  expire_interval: 60   # Number of minutes to wait between cleanup runs 
  retain:
    days: 5   # Number of days to retain recordings regardless of events
    mode: motion
  events:
    pre_capture: 5    # Number of seconds before the event to include
    post_capture: 5   # Number of seconds after the event to include
    retain:
      default: 7    # Default retention days 
      mode: motion


snapshots:
  enabled: True      # Enable writing jpg snapshot to /media/frigate/clips
  clean_copy: True    # Save a clean PNG copy of the snapshot image 
  timestamp: False
  bounding_box: False
  crop: False
  #height:            # height to resize the snapshot to (default: original size)
  #required_zones: [] #  Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  retain:
    default: 20


birdseye:
  enabled: True
  restream: True
  mode: objects


timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
```

### Relevant log output

```shell
Here is a sample 1st event after restarting Frigate:

2024-02-21 12:44:11.441 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on frigate/events (qos=0): b'{"before": {"id": "1708548250.168574-9vik3n", "camera": "entrance", "frame_time": 1708548250.168574, "snapshot": null, "label": "car", "sub_label": null, "top_score": 0.0, "false_positive": true, "start_time": 1708548250.168574, "end_time": null, "score": 0.98046875, "box": [2619, 476, 3839, 1180], "area": 858880, "ratio": 1.7329545454545454, "region": [2392, 80, 3840, 1528], "stationary": false, "motionless_count": 0, "position_changes": 0, "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot": false, "attributes": {}, "current_attributes": []}, "after": {"id": "1708548250.168574-9vik3n", "camera": "entrance", "frame_time": 1708548251.029763, "snapshot": {"frame_time": 1708548251.029763, "box": [2629, 485, 3838, 1172], "area": 830583, "region": [2380, 91, 3840, 1551], "score": 0.97265625, "attributes": []}, "label": "car", "sub_label": null, "top_score": 0.970703125, "false_positive": false, "start_time": 1708548250.168574, "end_time": null, "score": 0.97265625, "box": [2629, 485, 3838, 1172], "area": 830583, "ratio": 1.759825327510917, "region": [2380, 91, 3840, 1551], "stationary": false, "motionless_count": 0, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true, "attributes": {}, "current_attributes": []}, "type": "new"}'
```

### FFprobe output from your camera

```shell
cam1:
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
http://user:password@cam1: Invalid data found when processing input


From doorbell camera:

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
http://user:password@doorbell: Invalid data found when processing input
```

### Frigate stats

```json
{"cameras":{"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.0,"capture_pid":544,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":2100,"pid":542,"process_fps":4.0,"skipped_fps":0.0},"entrance":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":4.1,"capture_pid":548,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":553,"pid":543,"process_fps":4.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"16":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"5.8","cpu_average":"4","mem":"0.7"},"99":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.1"},"101":{"cmdline":"python3 -u -m frigate","cpu":"2.8","cpu_average":"1","mem":"9.8"},"114":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.3"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"149":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.2"},"156":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"171":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"196":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"247":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"282":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"316":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.1"},"512":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"2.5"},"514":{"cmdline":"frigate.recording_manager","cpu":"1.8","cpu_average":"4","mem":"4.7"},"523":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(44)","cpu":"0.2","cpu_average":"0","mem":"0.3"},"524":{"cmdline":"frigate.detector.cpu1","cpu":"0.0","cpu_average":"1","mem":"3.2"},"526":{"cmdline":"frigate.detector.cpu2","cpu":"2.5","cpu_average":"1","mem":"3.2"},"528":{"cmdline":"frigate.output       ","cpu":"1.1","cpu_average":"1","mem":"3.2"},"531":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2560x1920 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"532":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 3840x2160 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.4"},"533":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.4","cpu_average":"0","mem":"1.2"},"542":{"cmdline":"frigate.process:doorbell","cpu":"0.7","cpu_average":"0","mem":"4.1"},"543":{"cmdline":"frigate.process:entrance","cpu":"0.7","cpu_average":"0","mem":"4.1"},"544":{"cmdline":"frigate.capture:doorbell","cpu":"2.8","cpu_average":"2","mem":"3.8"},"548":{"cmdline":"frigate.capture:entrance","cpu":"4.7","cpu_average":"4","mem":"3.9"},"553":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://127.0.0.1:8554/entrance -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/entrance@%Y%m%d%H%M%S%z.mp4 -r 4 -vf fps=4,scale_vaapi=w=3840:h=2160:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"19.9","cpu_average":"19","mem":"3.6"},"557":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://doorbell/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/c0f004cc5a57d1d2fbdf10ea7a34a1fd","cpu":"0.0","cpu_average":"0","mem":"0.7"},"1060":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.1"},"2100":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbell -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4 -r 4 -vf fps=4,scale_vaapi=w=2560:h=1920:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"6.0","cpu_average":"5","mem":"2.7"},"2102":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i http://doorbell/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/c0f004cc5a57d1d2fbdf10ea7a34a1fd","cpu":"1.2","cpu_average":"1","mem":"0.7"},"2296":{"cmdline":"bash","cpu":"0.0","cpu_average":"0","mem":"0.1"},"3466":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.2,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":107.4,"pid":524},"cpu2":{"detection_start":0.0,"inference_speed":113.06,"pid":526}},"gpu_usages":{"intel-vaapi":{"gpu":"0.68%","mem":"-%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":512},"recording":{"pid":514}},"service":{"last_updated":1708549999,"latest_version":"0.13.2","storage":{"/dev/shm":{"free":234.4,"mount_type":"tmpfs","total":256.0,"used":21.6},"/media/frigate/clips":{"free":427603.0,"mount_type":"nfs","total":510595.0,"used":82992.0},"/media/frigate/recordings":{"free":427603.0,"mount_type":"nfs","total":510595.0,"used":82992.0},"/tmp/cache":{"free":483.8,"mount_type":"tmpfs","total":512.0,"used":28.2}},"temperatures":{},"uptime":924,"version":"0.13.2-6476f8a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

cam1 - hikvision, doorbell - reolink
