### DISCUSSION TITLE
[Support]: /tmp/cache 100% usage

### DISCUSSION THREAD

**Discussion by sshaikh** [blakeblackshear/frigate#9969] [General Support]
### Describe the problem you are having

Over time (around 12 hours) available swap (checked via `free -h`) steadily decreases till it's exhausted. Memory seems stable.

### Version

0.13.2-6476f8a

### Frigate config file

```yaml
mqtt:
  host: mqtt
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  enabled: True
  retain:
    days: 7

snapshots:
  enabled: True

detect:
  enabled: True

objects:
  track:
    - person
    - bicycle
    - car
    - motocycle
    - bird
    - cat
    - dog
    - backpack
    - umbrella
    - suitcase

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

go2rtc:
  streams:
    camera:
      - rtsp://cctv:{FRIGATE_RTSP_PASSWORD}@camera:554/h264Preview_01_main
    camera-sub:
      - rtsp://cctv:{FRIGATE_RTSP_PASSWORD}@camera:554/h264Preview_01_sub

cameras:
  cam:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/camera
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/camera-sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    audio:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 0,30,200,30,200,0,0,0
    zones:
      driveway-zone:
        coordinates: 0,480,640,480,640,319,467,306,0,305
        filters:
          person:
            min_area: 3600
    record:
      events:
        required_zones:
          - driveway-zone
    snapshots:
      required_zones:
        - driveway-zone
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://camera:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
  Duration: N/A, start: 0.000125, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 15 fps, 120 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

Config is truncated - running eight cameras of various makes and models but with similar settings.

Box has 16GB of ram. shm is set to 200bm, tmpfs to 1 000 000 000. Only frigate is running and swap is freed on frigate restart.

**Comment by NickM-27** [comment]
will need info from top, the system page, etc. to know what processes are using memory.

**Comment by sshaikh** [comment]
How can I provide this information?

When sorting by memory, the first 35 or so entries in htop are `python3 -u -m frigate`, then 4 `frigate.recording_manager`, then around 24 `ffmpeg`s. Each camera has around 20 `frigate.process:camera`.

**Reply by NickM-27** [reply]
a screenshot of the system page and a screenshot of the top output would be a good start

**Reply by sshaikh** [reply]
```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       1.9Gi       206Mi        22Mi        13Gi        13Gi
Swap:          979Mi       788Mi       191Mi
```
<img width="961" alt="2024-02-23_22-22 - cctv top" src="https://github.com/blakeblackshear/frigate/assets/68978/b39ebc9a-3b60-4821-a508-bee3a94da4d7">

<img width="858" alt="2024-02-23_22-24 - frigate system" src="https://github.com/blakeblackshear/frigate/assets/68978/41d060cf-f6d5-4f50-b125-831f4265dcb2">

**Reply by NickM-27** [reply]
how much space is used by /tmp/cache? 1.9% is not a whole lot

**Reply by sshaikh** [reply]
How can I check this? I don't have a /tmp/cache. I do have a 1GB swap though (via an LVM LV) if that's what you mean?

**Reply by NickM-27** [reply]
there will be /tmp/cache inside of the container if it was setup correctly according to the docs

**Reply by sshaikh** [reply]
I have this in my dockerfile (deleted other volumes for brevity):

```
    volumes:
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
