### DISCUSSION TITLE
[Support]: Events not added to the event log but sent via MQTT

### DISCUSSION THREAD

**Discussion by Mincka** [blakeblackshear/frigate#9974] [General Support] [answered]
### Describe the problem you are having

I have a notification set on my phone to be notified in case of new event through MQTT.
From time to time, I get the notifications for event start and event end but when I look at the Frigate event log, the event is nowhere.

This event was a false-positive (false detection of a person) and when I've looked at the debug feed, I saw that the "person" was considered as stationary for 2 minutes with detection rechecks with a score between about 50% and 86%. The event never appeared in "In progress" events in the GUI, nor in the log after.

This is my trigger:
```
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: 1/1/1/1/1
    value_template: >-
      {{ iif(value_json["type"] != "end", 1) }}/{{
      iif(value_json["before"]["label"] == "person", 1) }}/{{
      iif(["jardin_avant", "jardin_arriere"]|select("in",
      value_json["before"]["entered_zones"])|list|length == 0, 1) }}/{{
      iif(["jardin_avant", "jardin_arriere"]|select("in",
      value_json["after"]["entered_zones"])|list|length > 0, 1) }}/{{
      iif(value_json["after"]["top_score"] >= 0.86, 1) }}
```

And the relevant part to wait for the end of the event and tell in the notification that the clip is ready:
```
          - repeat:
              until:
                - condition: template
                  value_template: "{{ wait.trigger.payload_json[\"type\"] == \"end\" }}"
              sequence:
                - wait_for_trigger:
                    - platform: mqtt
                      topic: frigate/events
                      payload: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
                      value_template: "{{ value_json[\"after\"][\"id\"] }}"
                  continue_on_timeout: false
                  timeout: "00:02:00"
```

This is the event that triggered the automation:
```
trigger:
  id: frigate-event
  idx: '0'
  alias: null
  platform: mqtt
  topic: frigate/events
  payload: >-
    {"before": {"id": "1708586821.640552-7asr71", "camera":
    "Frigate_Buanderie_Arriere", "frame_time": 1708586821.640552, "snapshot":
    null, "label": "person", "sub_label": null, "top_score": 0.0,
    "false_positive": true, "start_time": 1708586821.640552, "end_time": null,
    "score": 0.7421875, "box": [72, 0, 639, 351], "area": 199017, "ratio":
    1.6153846153846154, "region": [0, 0, 732, 732], "stationary": false,
    "motionless_count": 0, "position_changes": 0, "current_zones": [],
    "entered_zones": [], "has_clip": false, "has_snapshot": false, "attributes":
    {}, "current_attributes": []}, "after": {"id": "1708586821.640552-7asr71",
    "camera": "Frigate_Buanderie_Arriere", "frame_time": 1708586938.648886,
    "snapshot": {"frame_time": 1708586938.648886, "box": [37, 0, 631, 351],
    "area": 208494, "region": [0, 0, 732, 732], "score": 0.88671875,
    "attributes": []}, "label": "person", "sub_label": null, "top_score":
    0.88671875, "false_positive": false, "start_time": 1708586821.640552,
    "end_time": null, "score": 0.88671875, "box": [37, 0, 631, 351], "area":
    208494, "ratio": 1.6923076923076923, "region": [0, 0, 732, 732],
    "stationary": true, "motionless_count": 556, "position_changes": 0,
    "current_zones": ["jardin_arriere"], "entered_zones": ["jardin_arriere"],
    "has_clip": false, "has_snapshot": false, "attributes": {},
    "current_attributes": []}, "type": "new"}
  qos: 0
  description: mqtt topic frigate/events
  payload_json:
    before:
      id: 1708586821.640552-7asr71
      camera: Frigate_Buanderie_Arriere
      frame_time: 1708586821.640552
      snapshot: null
      label: person
      sub_label: null
      top_score: 0
      false_positive: true
      start_time: 1708586821.640552
      end_time: null
      score: 0.7421875
      box:
        - 72
        - 0
        - 639
        - 351
      area: 199017
      ratio: 1.6153846153846154
      region:
        - 0
        - 0
        - 732
        - 732
      stationary: false
      motionless_count: 0
      position_changes: 0
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
      attributes: {}
      current_attributes: []
    after:
      id: 1708586821.640552-7asr71
      camera: Frigate_Buanderie_Arriere
      frame_time: 1708586938.648886
      snapshot:
        frame_time: 1708586938.648886
        box:
          - 37
          - 0
          - 631
          - 351
        area: 208494
        region:
          - 0
          - 0
          - 732
          - 732
        score: 0.88671875
        attributes: []
      label: person
      sub_label: null
      top_score: 0.88671875
      false_positive: false
      start_time: 1708586821.640552
      end_time: null
      score: 0.88671875
      box:
        - 37
        - 0
        - 631
        - 351
      area: 208494
      ratio: 1.6923076923076923
      region:
        - 0
        - 0
        - 732
        - 732
      stationary: true
      motionless_count: 556
      position_changes: 0
      current_zones:
        - jardin_arriere
      entered_zones:
        - jardin_arriere
      has_clip: false
      has_snapshot: false
      attributes: {}
      current_attributes: []
    type: new
targeted_zone: Jardin Arrière
after_zones:
  - jardin_arriere
before_zones: []
camera: Frigate_Buanderie_Arriere
cameraLabel: Frigate Buanderie Arriere
id: 1708586821.640552-7asr71
label: person
```

And this is the ending event:

```
Iteration 6

repeat:
  first: false
  index: 6
wait:
  remaining: 106.69964597187936
  trigger:
    id: '0'
    idx: '0'
    alias: null
    platform: mqtt
    topic: frigate/events
    payload: >-
      {"before": {"id": "1708586821.640552-7asr71", "camera":
      "Frigate_Buanderie_Arriere", "frame_time": 1708587240.323068, "snapshot":
      {"frame_time": 1708586938.648886, "box": [37, 0, 631, 351], "area":
      208494, "region": [0, 0, 732, 732], "score": 0.88671875, "attributes":
      []}, "label": "person", "sub_label": null, "top_score": 0.88671875,
      "false_positive": false, "start_time": 1708586821.640552, "end_time":
      null, "score": 0.69921875, "box": [0, 5, 622, 351], "area": 215212,
      "ratio": 1.7976878612716762, "region": [0, 0, 732, 732], "stationary":
      true, "motionless_count": 1964, "position_changes": 0, "current_zones":
      ["jardin_arriere"], "entered_zones": ["jardin_arriere"], "has_clip":
      false, "has_snapshot": false, "attributes": {}, "current_attributes": []},
      "after": {"id": "1708586821.640552-7asr71", "camera":
      "Frigate_Buanderie_Arriere", "frame_time": 1708587243.392322, "snapshot":
      {"frame_time": 1708586938.648886, "box": [37, 0, 631, 351], "area":
      208494, "region": [0, 0, 732, 732], "score": 0.88671875, "attributes":
      []}, "label": "person", "sub_label": null, "top_score": 0.88671875,
      "false_positive": false, "start_time": 1708586821.640552, "end_time":
      1708587253.582796, "score": 0.69921875, "box": [0, 5, 622, 351], "area":
      215212, "ratio": 1.7976878612716762, "region": [0, 0, 732, 732],
      "stationary": true, "motionless_count": 1979, "position_changes": 0,
      "current_zones": ["jardin_arriere"], "entered_zones": ["jardin_arriere"],
      "has_clip": false, "has_snapshot": false, "attributes": {},
      "current_attributes": []}, "type": "end"}
    qos: 0
    description: mqtt topic frigate/events
    payload_json:
      before:
        id: 1708586821.640552-7asr71
        camera: Frigate_Buanderie_Arriere
        frame_time: 1708587240.323068
        snapshot:
          frame_time: 1708586938.648886
          box:
            - 37
            - 0
            - 631
            - 351
          area: 208494
          region:
            - 0
            - 0
            - 732
            - 732
          score: 0.88671875
          attributes: []
        label: person
        sub_label: null
        top_score: 0.88671875
        false_positive: false
        start_time: 1708586821.640552
        end_time: null
        score: 0.69921875
        box:
          - 0
          - 5
          - 622
          - 351
        area: 215212
        ratio: 1.7976878612716762
        region:
          - 0
          - 0
          - 732
          - 732
        stationary: true
        motionless_count: 1964
        position_changes: 0
        current_zones:
          - jardin_arriere
        entered_zones:
          - jardin_arriere
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      after:
        id: 1708586821.640552-7asr71
        camera: Frigate_Buanderie_Arriere
        frame_time: 1708587243.392322
        snapshot:
          frame_time: 1708586938.648886
          box:
            - 37
            - 0
            - 631
            - 351
          area: 208494
          region:
            - 0
            - 0
            - 732
            - 732
          score: 0.88671875
          attributes: []
        label: person
        sub_label: null
        top_score: 0.88671875
        false_positive: false
        start_time: 1708586821.640552
        end_time: 1708587253.582796
        score: 0.69921875
        box:
          - 0
          - 5
          - 622
          - 351
        area: 215212
        ratio: 1.7976878612716762
        region:
          - 0
          - 0
          - 732
          - 732
        stationary: true
        motionless_count: 1979
        position_changes: 0
        current_zones:
          - jardin_arriere
        entered_zones:
          - jardin_arriere
        has_clip: false
        has_snapshot: false
        attributes: {}
        current_attributes: []
      type: end
```

The "top_score" for the automation is higher (0.86) than the required threshold on Frigate (0.85). I'm doing that because I tune my Frigate+ model with new events that can be false-positive and I don't want to be notified for them.

When the event ended, I clicked on my notification to get the replay and I got :
`{"message": "Event not found", success: "false"}`

So my question is: in which conditions the DB / web UI of Frigate would not record or "discard" an event that was started, updated and ended on MQTT?

### Version

0.13.2

### Frigate config file

```yaml
objects:
  filters:
    person:
      threshold: 0.85
    car:
      threshold: 0.80

cameras:
  Frigate_Buanderie_Arriere:
    ffmpeg:
      inputs:
      - path: rtsp://XXX:XXXX@XXX/Streaming/channels/XXX
        roles:
        - detect
        - record
    zones:
      jardin_arriere:
        coordinates: 640,360,640,0,0,0,0,360
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 2
          mode: active_objects
    detect:
      max_disappeared: 50
    objects:
      track:
      - person
      filters:
        person:
          min_area: 1000
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 7
    motion:
      improve_contrast: false
      mask:
      - 170,330,170,360,148,360,150,328
```

### Relevant log output

```shell
Nothing relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
{
    "cameras": {
        "Frigate_Buanderie_Arriere": {
            "audio_dBFS": 0,
            "audio_rms": 0,
            "camera_fps": 5,
            "capture_pid": 458,
            "detection_enabled": 1,
            "detection_fps": 0,
            "ffmpeg_pid": 463,
            "pid": 435,
            "process_fps": 5,
            "skipped_fps": 0
        }
    },
    "cpu_usages": {
        "1": {
            "cmdline": "/package/admin/s6/command/s6-svscan -d4 -- /run/service",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "15": {
            "cmdline": "s6-supervise s6-linux-init-shutdownd",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "16": {
            "cmdline": "/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "24": {
            "cmdline": "s6-supervise frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "25": {
            "cmdline": "s6-supervise go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "26": {
            "cmdline": "s6-supervise s6rc-fdholder",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "27": {
            "cmdline": "s6-supervise nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "28": {
            "cmdline": "s6-supervise s6rc-oneshot-runner",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "29": {
            "cmdline": "s6-supervise go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "30": {
            "cmdline": "s6-supervise go2rtc-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "31": {
            "cmdline": "s6-supervise nginx-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "32": {
            "cmdline": "s6-supervise frigate-log",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "41": {
            "cmdline": "/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "42": {
            "cmdline": "/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "80": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "81": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "82": {
            "cmdline": "s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "89": {
            "cmdline": "/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "108": {
            "cmdline": "bash ./run.user go2rtc-healthcheck",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "110": {
            "cmdline": "python3 -u -m frigate",
            "cpu": "16.0",
            "cpu_average": "7",
            "mem": "8.4"
        },
        "118": {
            "cmdline": "nginx: master process nginx",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "143": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "144": {
            "cmdline": "nginx: worker process",
            "cpu": "0.1",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "145": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.1"
        },
        "146": {
            "cmdline": "nginx: worker process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.2"
        },
        "148": {
            "cmdline": "nginx: cache manager process",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        },
        "296": {
            "cmdline": "frigate.logger       ",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.5"
        },
        "377": {
            "cmdline": "frigate.recording_manager",
            "cpu": "10.1",
            "cpu_average": "6",
            "mem": "1.6"
        },
        "386": {
            "cmdline": "/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(83)",
            "cpu": "1.2",
            "cpu_average": "1",
            "mem": "0.1"
        },
        "387": {
            "cmdline": "frigate.detector.coral",
            "cpu": "1.0",
            "cpu_average": "3",
            "mem": "0.7"
        },
        "389": {
            "cmdline": "frigate.output       ",
            "cpu": "11.2",
            "cpu_average": "11",
            "mem": "0.8"
        },
        "396": {
            "cmdline": "ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x352 -i pipe: -f mpegts -s 1309x720 -codec:v mpeg1video -q 8 -bf 0 pipe:",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.6"
        },
        "435": {
            "cmdline": "frigate.process:Frigate_Buanderie_Arriere",
            "cpu": "0.7",
            "cpu_average": "0",
            "mem": "0.8"
        },
        "463": {
            "cmdline": "ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.2-6476f8a -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@10.0.0.71/Streaming/channels/402 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Frigate_Buanderie_Arriere@%Y%m%d%H%M%S%z.mp4 -r 5 -vf fps=5,scale_vaapi=w=640:h=352:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:",
            "cpu": "1.1",
            "cpu_average": "1",
            "mem": "0.4"
        },
        "407803": {
            "cmdline": "sleep 30s",
            "cpu": "0.0",
            "cpu_average": "0",
            "mem": "0.0"
        }
    },
    "detection_fps": 5.8,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 5.99,
            "pid": 387
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "4.15%",
            "mem": "-%"
        }
    },
    "processes": {
        "audioDetector": {
            "pid": 506
        },
        "go2rtc": {
            "pid": 89
        },
        "logger": {
            "pid": 296
        },
        "recording": {
            "pid": 377
        }
    },
    "service": {
        "last_updated": 1708588650,
        "latest_version": "0.13.2",
        "storage": {
            "/dev/shm": {
                "free": 993.7,
                "mount_type": "tmpfs",
                "total": 1024,
                "used": 30.3
            },
            "/media/frigate/clips": {
                "free": 291337.6,
                "mount_type": "ext4",
                "total": 502868.2,
                "used": 185914.6
            },
            "/media/frigate/recordings": {
                "free": 291337.6,
                "mount_type": "ext4",
                "total": 502868.2,
                "used": 185914.6
            },
            "/tmp/cache": {
                "free": 936.6,
                "mount_type": "tmpfs",
                "total": 953.7,
                "used": 17
            }
        },
        "temperatures": {},
        "uptime": 57991,
        "version": "0.13.2-6476f8a"
    }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 410w
