### DISCUSSION TITLE
[Config Support]: High CPU usage since upgrading to 0.13

### DISCUSSION THREAD

**Discussion by M1LkZz** [blakeblackshear/frigate#9981] [Config Support] [answered]
### Describe the problem you are having

I am running my Ubuntu server on a Lenovo M70Q Tiny with a i5-10500T with Frigate in a container.

Since upgrading to Frigate 0.13.2-6476F8A my CPU usage went up by 30-70% in my Frigate container. It's bouncing between 35-90% usage for the Frigate container alone (reported by Glances). FFMPEG seems to be the culprit.

While I never had any problems with a lower version of Frigate with great detection.

Already tried setting the detect stream to a lower resolution with pretty much no effect. Also tried setting hwaccel to QSV but also without any effect. I am at a loss.

I don't know what changed in 0.13 but my CPU doesn't like it:

![Screenshot from 2024-02-22 18-03-50](https://github.com/blakeblackshear/frigate/assets/93886610/18b5d099-2e62-4e35-a85f-c2ceb81da92d)

### Version

0.13.2-6476F8A

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: *******
  user: ******
  password: ******

cameras:
  Doorbell: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:******/Streaming/Channels/101/ # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    objects:
      track:
        - person
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 10 # <---- fps live feed and detection (5-10)
    record:
      enabled: True
      retain:
        days: 21
        mode: all
detectors:
    cpu1:
      type: cpu
      num_threads: 12
go2rtc:
  streams:
    Doorbell:
      - rtsp://admin:*******/Streaming/Channels/101
      - isapi://admin:*******/
```

### Relevant log output

```shell
2024-02-22 16:54:18.797045961  [2024-02-22 16:54:18] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
2024-02-22 16:54:21.825050837  [2024-02-22 16:54:21] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for Doorbell. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-02-22 16:54:31.813140117  [2024-02-22 16:54:31] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for Doorbell. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment, marked as answer]
this is most likely caused by the more sensitive motion detection, you will want to tune it. https://docs.frigate.video/configuration/motion_detection

also, you have an  i5-10500T so you really should be using openvino not cpu as a detector https://docs.frigate.video/configuration/object_detectors#openvino-detector

**Reply by M1LkZz** [reply]
Changed settings to this:

```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

And immediately de-stressed the CPU. Now running at a healthy 15%. Thanks!  Completely missed the OpenVino part when setting up.
