### DISCUSSION TITLE
[Question]: Birdseye minimum cameras

### DISCUSSION THREAD

**Discussion by cecc83** [blakeblackshear/frigate#9990] [Ask A Question]
### What is your question:

Hello everybody, I have 5 cameras and I want to show in birdseye view 4 of them. To achieve this I entered this configuration:

```
birdseye:
  enabled: True
  mode: continuous
  restream: True
  layout:
    max_cameras: 4
```

but I would like one of them switch to fifth camera according to detected movement, instead of having always the same 4 fixed. I also tried overriding the single camera configuration with mode: motion but with no luck.
If I set the mode motion at the main level it happens that if there is no movement only one camera is shown. Is there a way to always have a minimum of 4 cameras in this mode?
Thank you in advance.
