### ISSUE TITLE
hardware acceleration errors on Raspberry Pi 4

### ISSUE THREAD

**Issue by hacstest04f** [blakeblackshear/frigate#1006]
**Describe the bug**
On Raspberry Pi 4, mmal error occurs when hardware acceleration enabled in frigate.xml.  The frigate webUI shows a completely green camera view.  When I comment out the hwaccel_args, Frigate works as expected, just with higher than desired CPU consumption.

**Version of frigate**
0.8.4-armv7

**Config file**
```yaml
mqtt:
  host: 192.168.1.50
  port: 1883
  topic_prefix: /frigate
  client_id: frigate
  stats_interval: 60

database:
  path: /local/path/frigate.db

cameras:
  # Name of your camera
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user1:password1@192.168.1.101:554/live
          roles:
            - detect
            - rtmp
            - clips
            - record
      hwaccel_args:
        - -c:v
        - h264_mmal
    width: 2688
    height: 1520
    fps: 5

    clips:
      enabled: True
      #max_seconds: 10
      #tmpfs_cache_size: 256m
      objects:
        - person
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

    snapshots:
      enabled: True
      bounding_box: True

    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - bird
        - cat
        - dog
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 500
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

    detect:
      enabled: True
      max_disappeared: 15
```

**Frigate container logs**
```
pi@raspberrypi:~/docker $ docker-compose up
Creating network "docker_default" with the default driver
Creating frigate ... done
Attaching to frigate
frigate    |  * Starting nginx nginx
frigate    |    ...done.
frigate    | frigate.app                    WARNING : Camera driveway has record assigned to an input, but record is not enabled.
frigate    | Starting migrations
frigate    | peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | peewee_migrate                 INFO    : There is nothing to migrate
frigate    | frigate.mqtt                   INFO    : MQTT connected
frigate    | detector.coral                 INFO    : Starting detection process: 33
frigate    | frigate.app                    INFO    : Camera processor started for driveway: 36
frigate    | frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | frigate.app                    INFO    : Capture process started for driveway: 37
frigate    | frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate    | frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate    | frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x2248350 (EINVAL)
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0x2248350) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x2256e50) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x2248040) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : Error while opening decoder for input stream #0:0 : Unknown error occurred
frigate    | frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate    | frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate    | ffmpeg.driveway.detect         ERROR   : [rtsp @ 0x8cd710] DTS discontinuity in stream 1: packet 18 with DTS 25896235559131, packet 19 with DTS 25896235572122
frigate    | ffmpeg.driveway.detect         ERROR   : [rtsp @ 0x8cd710] DTS discontinuity in stream 1: packet 21 with DTS 25896235572126, packet 22 with DTS 25896235575536
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x8eafe0 (EINVAL)
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0x8eafe0) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x91dbd0) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x8eacd0) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : Error while opening decoder for input stream #0:0 : Unknown error occurred
frigate    | frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate    | frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate    | ffmpeg.driveway.detect         ERROR   : [rtsp @ 0x152f710] DTS discontinuity in stream 1: packet 16 with DTS 25896235718573, packet 17 with DTS 25896235732523
frigate    | ffmpeg.driveway.detect         ERROR   : [rtsp @ 0x152f710] DTS discontinuity in stream 1: packet 19 with DTS 25896235732527, packet 20 with DTS 25896235735938
frigate    | ffmpeg.driveway.detect         ERROR   : [rtsp @ 0x152f710] DTS discontinuity in stream 1: packet 32 with DTS 25896235736660, packet 33 with DTS 25896235748403
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x15e4ed0 (EINVAL)
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0x15e4ed0) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x15e51e0) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x15e4bb0) is not enabled
frigate    | ffmpeg.driveway.detect         ERROR   : Error while opening decoder for input stream #0:0 : Unknown error occurred

```

**Computer Hardware**
 - Raspberry Pi 4, 4GB RAM, booting off microSD
 - OS: Raspbian, Buster  5.10.17-v7l+ #1403 SMP Mon Feb 22
 - Install method: docker compose
 - Virtualization: none
 - Coral Version: USB
 - Network Setup: wired

**Camera Info:**
 - Manufacturer: Dahua
 - Model: 
 - Resolution: 2688 x 1520
 - FPS: 5

The only container running on this raspberry pi is Frigate.  This was a fresh install just to test out Frigate.
