### ISSUE TITLE
120 Second Delay Coral Dev Board Mini

### ISSUE THREAD

**Issue by retrospectvideo** [blakeblackshear/frigate#1010]
**Describe the bug**
I am using a new google coral dev dev board mini. I have compiled kernel support for docker. I am running the stable docker build and I am trying to connect to my 4MP camera at 10fps and the results are extremely delayed. I am looking at a 2 minute delay or more on one camera. Surely there is something wrong or this device isn't capable of handling 1 camera?

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
database:
  path: /media/frigate/frigate.db
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.198
  port: 1883
  topic_prefix: frigate
  client_id: frigate

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.12/media/video1
          roles:
            - detect
            - clips
            - rtmp
    clips:
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 10
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 20
      # Optional: Objects to save clips for. (default: all tracked objects)
      # objects:
      #  - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 120
        # Optional: Per object retention days
        # objects:
        #  person: 15
    snapshots:
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      # height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 120
        # Optional: Per object retention days
        # objects:
        #  person: 15


    width: 2048
    height: 1520
    fps: 10
    objects:
      filters:
        person:
          mask:
            - 1734,0,1746,92,1567,149,1484,0
objects:
  track:
    - person
    - cat
    - car
    - truck
    - gun


```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
{
  "detection_fps": 0.0, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 105.61, 
      "pid": 34
    }
  }, 
  "entrance": {
    "camera_fps": 23.5, 
    "capture_pid": 38, 
    "detection_fps": 0.0, 
    "pid": 37, 
    "process_fps": 23.4, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 58.4, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 8.7
      }, 
      "/media/frigate/clips": {
        "free": 1941.3, 
        "mount_type": "ext4", 
        "total": 5375.6, 
        "used": 3153.4
      }, 
      "/media/frigate/recordings": {
        "free": 1941.3, 
        "mount_type": "ext4", 
        "total": 5375.6, 
        "used": 3153.4
      }, 
      "/tmp/cache": {
        "free": 996.2, 
        "mount_type": "tmpfs", 
        "total": 1000.0, 
        "used": 3.8
      }
    }, 
    "uptime": 798, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
