### ISSUE TITLE
RPi 4 64bit hardware acceleration fails. num_capture_buffers exceeded.

### ISSUE THREAD

**Issue by sebirdman** [blakeblackshear/frigate#1021]
**Describe the bug**

When enabling 
```
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
```

on ubuntu 20.04 LTS 64-bit on a RPi4 with 8GB of ram i frequently get:

```
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaafc003500] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
```

This seems to be effecting the clips portion of my cameras which are 1080p, the detection appear to still be working (still get events over mqtt), i just don't get images for them.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: <IP>
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: <RTSP>
          roles:
            - detect
        - path:  <RTSP>
          roles:
            - clips
    width: 640
    height: 360
    fps: 5
  laundry:
    ffmpeg:
      inputs:
        - path: <RTSP>
          roles:
            - detect
        - path:  <RTSP>
          roles:
            - clips
    width: 640
    height: 360
    fps: 5
  backyard:
    ffmpeg:
      inputs:
        - path: <RTSP>
          roles:
            - detect
        - path: <RTSP>
          roles:
            - clips
    width: 640
    height: 360
    fps: 5

detectors:
  coral:
    type: edgetpu
    device: usb

clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
  tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.65

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating tmpfs of size 256m
frigate.app                    WARNING : Camera driveway has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera driveway has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera laundry has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera laundry has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera backyard has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera backyard has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for driveway: 39
frigate.app                    INFO    : Camera processor started for laundry: 41
frigate.app                    INFO    : Camera processor started for backyard: 42
frigate.app                    INFO    : Capture process started for driveway: 43
frigate.app                    INFO    : Capture process started for laundry: 45
frigate.app                    INFO    : Capture process started for backyard: 49
detector.coral                 INFO    : Starting detection process: 37
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
frigate.app                    INFO    : Stopping...
frigate.object_processing      INFO    : Exiting object processor...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.stats                  INFO    : Exiting watchdog...
frigate.events                 INFO    : Exiting event cleanup...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.events                 INFO    : Exiting event processor...
peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
root                           INFO    : Waiting for detection process to exit gracefully...
frigate.video                  INFO    : laundry: exiting subprocess
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating tmpfs of size 256m
frigate.app                    WARNING : Camera driveway has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera driveway has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera laundry has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera laundry has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera backyard has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera backyard has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for driveway: 39
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for laundry: 40
frigate.app                    INFO    : Camera processor started for backyard: 42
frigate.app                    INFO    : Capture process started for driveway: 43
frigate.app                    INFO    : Capture process started for laundry: 44
frigate.app                    INFO    : Capture process started for backyard: 45
frigate.edgetpu                INFO    : TPU found
watchdog.backyard              INFO    : No frames received from backyard in 20 seconds. Exiting ffmpeg...
watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.backyard              INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : backyard: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : backyard: ffmpeg process is not running. exiting capture thread...
ffmpeg.backyard.detect         ERROR   : [rtsp @ 0xaaaaec3415e0] DTS discontinuity in stream 0: packet 3 with DTS 77725312155729, packet 4 with DTS 77725312159954
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaafc003500] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaac5e11c60] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaab9ff66c0] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaae13c6c60] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaad08bac60] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaaadc6c6e20] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaab113f5c60] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.laundry               INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : laundry: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : laundry: ffmpeg process is not running. exiting capture thread...
ffmpeg.laundry.detect          ERROR   : [h264_v4l2m2m @ 0xaaab04159c60] All capture buffers returned to userspace. Increase num_capture_buffers to prevent device deadlock or dropped packets/frames.
watchdog.laundry               INFO    : No frames received from laundry in 20 seconds. Exiting ffmpeg...
watchdog.laundry               INFO    : Waiting for ffmpeg to exit gracefully...

```

**Frigate stats**
```json
{
  "backyard": {
    "camera_fps": 5.0, 
    "capture_pid": 45, 
    "detection_fps": 4.5, 
    "pid": 42, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 4.5, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 26.32, 
      "pid": 36
    }
  }, 
  "driveway": {
    "camera_fps": 5.1, 
    "capture_pid": 43, 
    "detection_fps": 0.0, 
    "pid": 39, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "laundry": {
    "camera_fps": 2.5, 
    "capture_pid": 44, 
    "detection_fps": 0.0, 
    "pid": 40, 
    "process_fps": 2.6, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 64.7, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 2.5
      }, 
      "/media/frigate/clips": {
        "free": 7966333.7, 
        "mount_type": "nfs", 
        "total": 23030252.2, 
        "used": 15063918.4
      }, 
      "/media/frigate/recordings": {
        "free": 7966333.7, 
        "mount_type": "nfs", 
        "total": 23030252.2, 
        "used": 15063918.4
      }, 
      "/tmp/cache": {
        "free": 206.8, 
        "mount_type": "tmpfs", 
        "total": 268.4, 
        "used": 61.6
      }
    }, 
    "uptime": 829, 
    "version": "0.8.4-5043040"
  }
}

```

**FFprobe from your camera**

Run the following command and paste output below
```
  Metadata:
    title           : 7483C23FDC38_0
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
    Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc

```

**Computer Hardware**
 - OS: ubuntu 20.04 LTS 64bit
 - Install method: docker
 - Virtualization: none
 - Coral Version: usb
 - Network Setup: wired

**Camera Info:**
 - Manufacturer: Unifi
 - Model: multiple
 - Resolution: multiple
 - FPS: 30

**Additional context**
