### ISSUE TITLE
Version for Jetson Nano

### ISSUE THREAD

**Issue by goldiiii** [blakeblackshear/frigate#103]
I would love to use this on my Jetson Nano. Will their be a version for it?

**Comment by asmirnou** [comment]
The support of Nvidia CUDA GPUs including Jetson Nano is added in PR #121. The underlying software matches the components and features inlcuded in [JetPack](https://developer.nvidia.com/embedded/jetpack), so the code should work once deployed into the module board.

**Comment by goldiiii** [comment]
Awesome thank you for the information

**Comment by saket424** [comment]
@asmirnou ,
I had assumed the Dockerfile.gpu that PR121 included was applicable to the Jetson nano also. "use frigate as base" doesn't work and as you point out many of the pieces are already provided by the jetpack. I'll give it a shot to see if Jetson nano can work with all the pieceparts already provided by Nvidia jetpack outside of docker environment and use the docker file.gpu as a stepping stone guide

**Comment by htilly** [comment]
@asmirnou 
Im curious, did you get it to work on the Jetson nano?

**Comment by htilly** [comment]
@saket424 
Im curious, did you get it to work on the Jetson nano?


> @asmirnou ,
> I had assumed the Dockerfile.gpu that PR121 included was applicable to the Jetson nano also. "use frigate as base" doesn't work and as you point out many of the pieces are already provided by the jetpack. I'll give it a shot to see if Jetson nano can work with all the pieceparts already provided by Nvidia jetpack outside of docker environment and use the docker file.gpu as a stepping stone guide

**Comment by htilly** [comment]
Answering my own question:
Works great on the Jetson Nano :-D

As for now it's outside docker.. 

Keep getting the following message, however it keeps running:
I0617 20:26:11.976987 28363 eviction_policy.cc:130] There is not enough space to create this object, so evicting 46 objects to free up 81431040 bytes. The number of bytes in use (before this eviction) is 398574848.

> @saket424
> Im curious, did you get it to work on the Jetson nano?
> 
> > @asmirnou ,
> > I had assumed the Dockerfile.gpu that PR121 included was applicable to the Jetson nano also. "use frigate as base" doesn't work and as you point out many of the pieces are already provided by the jetpack. I'll give it a shot to see if Jetson nano can work with all the pieceparts already provided by Nvidia jetpack outside of docker environment and use the docker file.gpu as a stepping stone guide

**Comment by scstraus** [comment]
Would love to hear what sort of interference times you are getting.

**Comment by htilly** [comment]
My first project running on the Jetson..  
If you tell me how, I will give you the results =)

**Comment by scstraus** [comment]
You can just go to your frigate's port and go to /debug/stats something like:
```
http://localhost:5000/debug/stats
```
and it will be there under the 
```
coral
```
key

or you can set up the sensor for it in homeassistant as described in the readme and monitor it via that:

```
sensor:
  - platform: rest
    name: Frigate Debug
    resource: http://localhost:5000/debug/stats
    scan_interval: 5
    json_attributes:
      - back
      - coral
    value_template: 'OK'  
  - platform: template
    sensors:
      back_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back"]["fps"] }}'
        unit_of_measurement: 'FPS'
      back_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      back_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_coral_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_coral_inference:
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["inference_speed"] }}' 
        unit_of_measurement: 'ms'
```
