### ISSUE TITLE
Unable to Sstart Frigate

### ISSUE THREAD

**Issue by Lawrencezarb** [blakeblackshear/frigate#1037]
**Describe the bug**
In Home Assistant nothing happens when I start Frigate, but I get the following error code in the System Log:

21-04-29 07:57:15 ERROR (SyncWorker_0) [supervisor.docker] Can't start addon_ccab4aaf_frigate: 500 Server Error for http+docker://localhost/v1.41/containers/c0b1b76b77a0d7919680ecbd0ff064e0aae71409723b2f92384a93ff40d363f2/start: Internal Server Error ("driver failed programming external connectivity on endpoint addon_ccab4aaf_frigate (be830556a4d3ae1daed4ddeb60e3cf5f09308458770c5cd22ce160f738754a84): Bind for 0.0.0.0:5000 failed: port is already allocated")

**Version of frigate**
Current version: 1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  cpu:
    type: cpu
mqtt:
  host: 192.168.0.6
  port: 1883
  user: mqtt
  password: password
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.0.12:9003/live/h264/ch02
          roles:
            - detect
    width: 352
    height: 288
    fps: 5
```

**Frigate container logs**
Frigate Log is empty

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: Debian
 - Install method: Addon
 - Virtualization: Docker
 - Coral Version: None
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
