### ISSUE TITLE
do you know how to disable motion record and how to disable best image?thanks!

### ISSUE THREAD

**Issue by yuhuanfan** [blakeblackshear/frigate#10420]
### Describe the problem you are having

[Config Support]: do you know how to disable motion record and how to disable best image?thanks!

### Version

10.1 rasp pi 2

### Frigate config file

```yaml
motion:
      improve_contrast: True
      threshold: 25
      mask:
        - 1222,675,1226,699,913,699,914,676
        - 315,720,148,720,0,307,0,0,458,0,490,260
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 30
    mode: active_objects
  events:
    max_seconds: 600
    pre_capture: 10
    post_capture: 10
```

### Relevant log output

```shell
objects:
      track:
        - person
      filters:
        person:
          min_score: 0.30
          threshold: 0.3
          mask:
            - 493,0,534,388,591,335,563,0
            - 1222,675,1226,699,913,699,914,676
            - 315,720,148,720,0,307,0,0,458,0,490,260
            - 1280,720,925,720,993,0,1280,0
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

_Originally posted by @yuhuanfan in https://github.com/blakeblackshear/frigate/discussions/10419_
