### ISSUE TITLE
Bug? - Unknown Error, see supervisor logs

### ISSUE THREAD

**Issue by Tropaion** [blakeblackshear/frigate#10457]
**Describe what you are trying to accomplish and why in non technical terms**
I installed the frigate addon on my HA installation and created the default frigate.yaml in the config folder.
```
mqtt:
  enabled: False

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect

```

But when starting the addon, I always get: ```Unknown error, see supervisor logs```.

This is what I found in the logs:
```
2024-03-14 17:03:37.757 ERROR (MainThread) [homeassistant.components.hassio.handler] /addons/ccab4aaf_frigate/start return code 400
2024-03-14 17:03:37.758 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/ccab4aaf_frigate/start - 
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
