### ISSUE TITLE
Pull mqtt password from env variable 

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#105]

**Comment by JonGilmore** [comment]
@blakeblackshear thanks for implementing this in rc5! Might want to note for your documentation of this, I had to quote the variable, which is different than when using variables in the `input` for each camera. 
here's an example snippet: 
```
mqtt:
  host: internal_ip
  topic_prefix: frigate
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
cameras:
  deck:
    fps: 6
    ffmpeg:
      input: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@internal_cam_ip:554/Streaming/Channels/1/
    objects:
```
