### ISSUE TITLE
Intel GPU <10th hardware acceleration issue

### ISSUE THREAD

**Issue by federicotravaini** [blakeblackshear/frigate#1065]
I have an intel NUC (Gemini Lake) with Home assistant installed on Proxmox.
I followed [this guide ](https://ipcamtalk.com/threads/proxmox-virtualization-with-hw-acceleration.33175/) to enable the passthroug of the GPU to the container with frigate.

I think I got it right since I can see in `lspci` the GPU (even if it's 00:18.0 while I was expecting it to be 00:02.0)

![photo_2021-05-07_12-43-57](https://user-images.githubusercontent.com/2836634/117438511-eda1e300-af31-11eb-8e6b-22a827d13298.jpg)
![photo_2021-05-07_12-43-46](https://user-images.githubusercontent.com/2836634/117438521-f1356a00-af31-11eb-9450-3bd2d2415274.jpg)

I added the `hwaccel_args` for the <10 intel generation listed on the documentation

My frigate.yml is:

``` yaml
mqtt:
  host: 192.168.91.92
  user: user
  password: password

cameras:
  ingresso:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.91.100:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    width: 640
    height: 352
    fps: 3
    objects:
      track:
        - person
    motion:
      mask:
        - 0,352,200,352,201,326,0,323
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

The issue is: with this setup the fans run like hell, while with no hardware acceleration it runs way more silent.
I think it might be something wrong with the configuration.

I installed intel-gpu-tools and tried to run `intel_gpu_top `but I get the error "Failed to initialize PMU! (Permission denied)"

The frigate log is fine and has no errors.

Hope I didnt forget to mention any useful log or information. If so, please ask and I'll provide them.
