### ISSUE TITLE
how to add a mjpeg camera

### ISSUE THREAD

**Issue by stoneobscurity** [blakeblackshear/frigate#1075]
not a bug, just posting this as a how-to

1] create a xxx.yml file.
protocols: [tcp]

2] rtsp streamer server.
docker run -d -it --name=rtsp-xxx --restart=unless-stopped -v /path/to/xxx.yml:/rtsp-simple-server.yml -p 5001:8554 aler9/rtsp-simple-server

3] mjpeg to rtsp.
docker run -d -u root --restart=unless-stopped --name streamer-xxx linuxserver/ffmpeg -re -i "http://user:pass@camera.ip/video.cgi" -f rtsp -rtsp_transport tcp "rtsp://ip.of.rtsp.server:5001/xxx"

4] test it in VLC.
rtsp://ip.of.rtsp.server:5001/xxx

5] add to frigate config.

i think you can just repeat 3,4,5 to add cams. just make sure the stream name is unique.

**Comment by blakeblackshear** [comment]
Frigate can read the mjpeg feed directly. No need for a translation layer.

**Comment by stoneobscurity** [comment]
`frigate.app                    INFO    : Capture process started for 6_garage: 67
frigate.video                  INFO    : 6_garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : 6_garage: ffmpeg process is not running. exiting capture thread...
ffmpeg.6_garage.detect         ERROR   : Option stimeout not found.
frigate.video                  INFO    : 6_garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : 6_garage: ffmpeg process is not running. exiting capture thread...`

**Comment by blakeblackshear** [comment]
Post your config

**Comment by stoneobscurity** [comment]
```
mqtt:
  host: 10.xx.xx.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
cameras:
  6_garage:
    ffmpeg:
      inputs:
#        - path: http://admin:xxx@10.xx.xx.xx/video.cgi
        - path: rtsp://10.xx.xx.xx:5001/live_stream
          roles:
            - record
            - detect
            - clips
    width: 640
    height: 480
    fps: 10
    record:
      enabled: True
    detect:
      enabled: False
    clips:
      enabled: False
    objects:
      track:
        - person
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
#  coral:
#    type: edgetpu
#    device: pci
logger:
  default: info
  logs:
    frigate.mqtt: error
clips:
  max_seconds: 300
  retain: 
    default: 30
record:
  retain_days: 7
motion:
  threshold: 20
```
