### ISSUE TITLE
Video artifacting

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#1078]
**Describe the bug**
Constant video artifacting on one of 2 cameras. only the front camera has this issue. back camera is a reolink and has no issues.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.178.79
  user: x
  password: x

cameras:


  back:
    zones:
      zone_0:
        coordinates: 2560,45,2537,1375,2171,1350,1802,1324,1786,1440,0,1440,0,728,1358,34
    motion:
      mask:
        - 1805,1440,2560,1440,2560,1298,1801,1305
        - 227,0,0,287,0,133,0,0,48,0,411,0
        - 0,0,787,0,1847,0,1367,34,1276,60,496,141,169,301,0,382
        - 2249,555,2241,57,2108,51,2127,545
        - 1523,276,1539,268,1582,216,1458,178,1398,0,1293,33,1355,219
        - 0,1440,704,1440,937,1203,704,1124,518,1070
        - 0,732,185,602,365,1079,0,1390
    mqtt:
      bounding_box: True
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtmp://192.168.178.113/bcs/channel0_main.bcs?channel=0&stream=0&user=x&password=x
          roles:
            #- record
            - detect
            - rtmp
            - clips
    width: 2560
    height: 1440
    fps: 5
    clips:
      enabled: True
      pre_capture: 10
      post_capture: 20
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True

   

  front:
    zones:
      voordeur:
        coordinates: 1280,444,826,720,0,720,0,470,741,458,806,0,1280,0
    motion:

      mask:
        - 311,720,257,202,341,0,0,0,0,720
    ffmpeg:
      input_args:
#        - an
        - -c:v
        - h264_cuvid
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
#      output_args:
 #       - an
      inputs:
        - path: rtsp://192.168.178.55:8554/unicast
          roles:
            #- record
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    clips:
      enabled: True
      pre_capture: 10
      post_capture: 20
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False


detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: False




ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'
    - -c:v
    - h264_cuvid
  output_args:
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy 

objects:

  track:
  #  - car
    - person
    - bicycle
#    - motorcycle
    - bus
    - train
#    - bird
    - cat
    - dog
    - backpack
#    - umbrella
#    - handbag
#    - suitcase
#    - sports ball
    - skateboard
#    - bottle
#    - wine glass
#    - cup
#    - fork
#    - knife
#    - spoon
#    - chair
#    - couch
#    - bed
#    - dining table
#    - toilet
#    - tv
#    - laptop
#    - mouse
#    - remote
#    - keyboard
    - cell phone
#    - microwave
#    - oven
#    - toaster
#    - sink
#    - refrigerator
#    - book
#    - clock
#    - vase
#    - scissors
#    - teddy bear
##    - hair drier
#    - toothbrush  

clips:
  max_seconds: 240
  retain:
    default: 10
    objects:
      person: 15
   
motion:
  threshold: 50
  delta_alpha: 0.2
  frame_alpha: 0.3
  contour_area: 60

```

**Frigate container logs**
```

[h264 @ 0x55613f5d5f00] error while decoding MB 0 23, bytestream 31244
[h264 @ 0x5620c9ca5f00] left block unavailable for requested intra mode
[h264 @ 0x5620c9ca5f00] error while decoding MB 0 21, bytestream 81631
[h264 @ 0x55a1a34b5f00] error while decoding MB 11 37, bytestream -19
[h264 @ 0x55e505e2df00] error while decoding MB 25 42, bytestream -17
[h264 @ 0x55e432d9bf00] cabac decode of qscale diff failed at 65 25
[h264 @ 0x55e432d9bf00] error while decoding MB 65 25, bytestream 38009
[h264 @ 0x55a2cf038f00] error while decoding MB 28 41, bytestream -51
[h264 @ 0x560889571f00] error while decoding MB 40 36, bytestream -17
[h264 @ 0x55dd19795f00] error while decoding MB 46 43, bytestream -43
[h264 @ 0x5637d8c41f00] error while decoding MB 31 40, bytestream -11
[h264 @ 0x56532bdecf00] cabac decode of qscale diff failed at 65 32
[h264 @ 0x56532bdecf00] error while decoding MB 65 32, bytestream 16902
[h264 @ 0x558ff29d9f00] cabac decode of qscale diff failed at 36 29
[h264 @ 0x558ff29d9f00] error while decoding MB 36 29, bytestream 36447
[h264 @ 0x559818115f00] left block unavailable for requested intra mode
[h264 @ 0x559818115f00] error while decoding MB 0 26, bytestream 7403
[h264 @ 0x5647d4346f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x5647d4346f00] error while decoding MB 0 21, bytestream 73276
[h264 @ 0x55bddf8b4f00] error while decoding MB 52 43, bytestream -53
[h264 @ 0x5587c0302f00] error while decoding MB 23 29, bytestream -9
[h264 @ 0x55f8b77b3f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55f8b77b3f00] error while decoding MB 0 26, bytestream 62017
[h264 @ 0x559d8feacf00] error while decoding MB 11 40, bytestream -9
[h264 @ 0x5578b81fff00] error while decoding MB 19 40, bytestream -43
[h264 @ 0x555c43d29f00] error while decoding MB 46 35, bytestream -37
[h264 @ 0x5634dc299f00] error while decoding MB 28 29, bytestream -15
[h264 @ 0x55e33387cf00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55e33387cf00] error while decoding MB 0 33, bytestream 14718
[h264 @ 0x557ac35b6f00] error while decoding MB 45 30, bytestream -25
[h264 @ 0x559c2fc11f00] error while decoding MB 56 37, bytestream -15
[h264 @ 0x55b968f7ff00] error while decoding MB 29 43, bytestream -15
[h264 @ 0x5638d4c6ff00] error while decoding MB 47 30, bytestream -57
[h264 @ 0x564e8ef08f00] error while decoding MB 39 30, bytestream -25
[h264 @ 0x55c20aa77f00] error while decoding MB 49 30, bytestream -7
[h264 @ 0x5648d78e7f00] error while decoding MB 52 33, bytestream -11
frigate.events                 WARNING : Unable to create clip for back and event 1620716063.486645-6znuxa. There were no cache files for this event.
[h264 @ 0x557995314f00] error while decoding MB 28 37, bytestream -9
[h264 @ 0x55e2fec75f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55e2fec75f00] error while decoding MB 0 24, bytestream 7846
[h264 @ 0x555fe4554f00] error while decoding MB 73 23, bytestream -11
[h264 @ 0x56215816bf00] error while decoding MB 23 37, bytestream -19
[h264 @ 0x561f1cb8ef00] error while decoding MB 17 37, bytestream -7
[h264 @ 0x55b432fb4f00] error while decoding MB 2 33, bytestream -17
frigate.events                 WARNING : Unable to create clip for front and event 1620717912.17741-bq7otc. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for back and event 1620718082.877158-zdc0pe. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for back and event 1620718192.088156-xtgjc8. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for back and event 1620718203.286532-tov8ua. There were no cache files for this event.
[h264 @ 0x55d8a0658f00] error while decoding MB 11 27, bytestream -11
[h264 @ 0x56289eba3f00] error while decoding MB 25 44, bytestream -25
[h264 @ 0x55837e5def00] error while decoding MB 16 33, bytestream -9
[h264 @ 0x5571d7171f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x5571d7171f00] error while decoding MB 0 24, bytestream 32884
[h264 @ 0x55a4147c6f00] error while decoding MB 28 42, bytestream -37
[h264 @ 0x55f1103f6f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55f1103f6f00] error while decoding MB 0 33, bytestream 20389
[h264 @ 0x5595c76f9f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x5595c76f9f00] error while decoding MB 0 28, bytestream 21403
[h264 @ 0x55fb9a9d7f00] error while decoding MB 57 32, bytestream -23
[h264 @ 0x5605ed3def00] error while decoding MB 68 32, bytestream -17
[h264 @ 0x563009386f00] error while decoding MB 74 41, bytestream -17
[h264 @ 0x559791796f00] error while decoding MB 2 37, bytestream -13
[h264 @ 0x56125c850f00] error while decoding MB 68 25, bytestream -5
[h264 @ 0x5620b55cef00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x5620b55cef00] error while decoding MB 0 30, bytestream 3719
[h264 @ 0x55ea374b5f00] error while decoding MB 9 41, bytestream -11
[h264 @ 0x562601832f00] error while decoding MB 4 40, bytestream -21
[h264 @ 0x55c3d4755f00] error while decoding MB 0 31, bytestream -29
[h264 @ 0x555f05349f00] error while decoding MB 1 31, bytestream -5
[h264 @ 0x556481060f00] error while decoding MB 14 35, bytestream -45
[h264 @ 0x558044537f00] cabac decode of qscale diff failed at 42 21
[h264 @ 0x558044537f00] error while decoding MB 42 21, bytestream 53496
[h264 @ 0x55e6ae05ff00] error while decoding MB 25 28, bytestream -29
[h264 @ 0x556f17c0ff00] error while decoding MB 19 26, bytestream -47
[h264 @ 0x55f1a8fbbf00] error while decoding MB 31 39, bytestream -39
[h264 @ 0x5613b83ebf00] error while decoding MB 3 34, bytestream -7
[h264 @ 0x55be7cf8ff00] left block unavailable for requested intra mode
[h264 @ 0x55be7cf8ff00] error while decoding MB 0 24, bytestream 47530
[h264 @ 0x5599e2842f00] cabac decode of qscale diff failed at 64 30
[h264 @ 0x5599e2842f00] error while decoding MB 64 30, bytestream 36393
[h264 @ 0x55c7d7196f00] error while decoding MB 21 38, bytestream -28
[h264 @ 0x55f15eedef00] error while decoding MB 51 34, bytestream -9
[h264 @ 0x55583cf71f00] error while decoding MB 31 28, bytestream -45
[h264 @ 0x5580b013ef00] error while decoding MB 2 31, bytestream -9
[h264 @ 0x560049e25f00] error while decoding MB 18 29, bytestream -55
[h264 @ 0x55be57dfef00] error while decoding MB 70 29, bytestream -26
[h264 @ 0x56057dfaff00] left block unavailable for requested intra mode
[h264 @ 0x56057dfaff00] error while decoding MB 0 39, bytestream 4295
[h264 @ 0x55c887717f00] error while decoding MB 34 44, bytestream -7
frigate.events                 WARNING : Unable to create clip for back and event 1620722957.904242-br436z. There were no cache files for this event.
[h264 @ 0x55f998d8cf00] error while decoding MB 43 39, bytestream -5
[h264 @ 0x55943bf69f00] error while decoding MB 50 39, bytestream -19
[h264 @ 0x55e8df024f00] error while decoding MB 10 44, bytestream -45
[h264 @ 0x55c22332ef00] error while decoding MB 43 30, bytestream -22
[h264 @ 0x557680192f00] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x557680192f00] error while decoding MB 0 25, bytestream 27616
[h264 @ 0x5634087c1f00] left block unavailable for requested intra mode
[h264 @ 0x5634087c1f00] error while decoding MB 0 39, bytestream 5386
[h264 @ 0x55b19733ef00] error while decoding MB 35 38, bytestream -9
[h264 @ 0x556370ca4f00] error while decoding MB 25 30, bytestream -19

```

**Frigate stats**
```json
{
back: {
camera_fps: 5.1,
capture_pid: 58,
detection_fps: 9.7,
pid: 47,
process_fps: 5,
skipped_fps: 0
},
detection_fps: 9.7,
detectors: {
coral: {
detection_start: 1620723608.981051,
inference_speed: 37.15,
pid: 44
}
},
front: {
camera_fps: 5.1,
capture_pid: 62,
detection_fps: 0,
pid: 56,
process_fps: 5.1,
skipped_fps: 0
},
service: {
storage: {
/dev/shm: {
free: 53.7,
mount_type: "tmpfs",
total: 67.1,
used: 13.4
},
/media/frigate/clips: {
free: 745819.2,
mount_type: "ext4",
total: 3936911.9,
used: 2991036.7
},
/media/frigate/recordings: {
free: 745819.2,
mount_type: "ext4",
total: 3936911.9,
used: 2991036.7
},
/tmp/cache: {
free: 13276.5,
mount_type: "ext4",
total: 117608.4,
used: 98313.6
}
},
uptime: 68283,
version: "0.8.4-5043040"
}
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://192.168.178.55:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 2.060067, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 10 tbr, 90k tbn, 50 tbc
```

**Screenshots**
![image](https://user-images.githubusercontent.com/43210224/117788970-2ac6e780-b248-11eb-8c8a-1c7e07879839.png)

**Computer Hardware**
 - OS: UBUNTU server 20.04 LTS
 - Install method: Docker compose
 - Virtualization: N/A
 - Coral Version: USB
 - Network Setup: server wired, both cameras wireless but only front camera has issues

**Camera Info:**
 - Manufacturer: XIAOMI
 - Model:  DAFANG
 - Resolution 1280x720
 - FPS: 5

**Additional context**
Xiaomi cam is running https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks firmware.,
