### ISSUE TITLE
Feature request: Add cURL to Dockerfile for Healthcheck

### ISSUE THREAD

**Issue by aav7fl** [blakeblackshear/frigate#108]
In [this commit](https://github.com/blakeblackshear/frigate/commit/39d64f7ba71cfebafb4eca169ab9a4a4bb987e17#diff-7d64accf17244689e844fc4a9147dc19R70-R72), you added a built-in endpoint to post if the container was healthy. I'd like to use that with my docker-compose file to track the health status of the container.

However, I can't use the following because `cURL` isn't a part of the `dockerfile`:

```yaml
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.5.0-rc3
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
```

Would you be open to the idea of adding it to support an easy way to utilize the healthcheck?
