### ISSUE TITLE
Trigger Camera Flash Light on Motion Detection? (Amcrest)

### ISSUE THREAD

**Issue by b24home** [blakeblackshear/frigate#10804]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have my Amcrest cameras light up the built-in spotlight when there is an object detected at night. 

**Describe the solution you'd like**
I’d like to know if Frigate can accomplish this with object detection, or even motion detection, and how it would effect/change/influence the camera’s settings to turn on the spotlight. 

**Describe alternatives you've considered**
Looking into doing this natively via Amcrest, but the app doesn’t have the function and the Web UI has a lot of issues (I can’t even login right now).

**Additional context**
Curious as to how Home Assistant may be able to help in this, since I’m sure Frigate can’t access the camera settings.

**Comment by NickM-27** [comment]
This would be something that is done via home assistant. Lights are not a feature of onvif and we're currently not looking to support proprietary apis.

**Comment by NickM-27** [comment]
It can depend on your camera and what APIs it supports, but this is for one of my dahua camera, this would go in the HA configuration.yaml

```
command_line:
    - switch:
        name: side_cam_spotlight
        unique_id: "side_cam::spotlight::on_off"
        command_on: curl --user 'USER:PASSWORD' --digest -g "http://IP_ADDRESS/cgi-bin/configManager.cgi?action=setConfig&Lighting[0][2].Mode=Manual"
        command_off: curl --user 'USER:PASSWORD' --digest -g "http://IP_ADDRESS/cgi-bin/configManager.cgi?action=setConfig&Lighting[0][2].Mode=Off"
```

this will only work if the camera is in manual night mode
