### ISSUE TITLE
Clips do not work

### ISSUE THREAD

**Issue by goldiiii** [blakeblackshear/frigate#1083]
**Describe the bug**
Frigate does not create Recordings. Clips do work. Recordings don't.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 10.1.1.200
  port: 1883
  user: mosquitto
  password: password
  topic_prefix: frigate
  client_id: frigate
cameras:
  camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.1.1.114:554/
          roles:
            - detect
            - record
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    detect:
      enabled: True
      max_disappeared: 25
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      required_zones: []
      retain:
        default: 10
    clips:
      enabled: True
      objects:
        - person
        - car
      retain:
        default: 10
        objects:
          person: 15

objects:
  track:
    - person
    - car
    - dog
    - bicycle







detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

logger:
  default: debug
```

**Frigate container logs**
```
frigate          | frigate.events                 DEBUG   : No cache clips for camera. Waiting...
frigate          | frigate.events                 WARNING : Unable to create clip for camera and event 1620757878.092863-maq908. There were no cache files for this event.
frigate          | peewee.sqliteq                 DEBUG   : received query INSERT INTO "event" ("id", "label", "camera", "start_time", "end_time", "top_score", "false_positive", "zones", "thumbnail", "has_clip", "has_snapshot") VALUES (?, ?, ?, ?, ?, ?, ?, json(?), ?, ?, ?)
frigate          | peewee                         DEBUG   : ('INSERT INTO "event" ("id", "label", "camera", "start_time", "end_time", "top_score", "false_positive", "zones", "thumbnail", "has_clip", "has_snapshot") VALUES (?, ?, ?, ?, ?, ?, ?, json(?), ?, ?, ?)', ['1620757878.092863-maq908', 'person', 'camera', 1620757878.092863, 1620757891.933094, 0.71484375, False, '[]', '/9j/4AAQ............A//9k=', False, True])
```

**Frigate stats**
```json
{
  "camera": {
    "camera_fps": 5.0, 
    "capture_pid": 40, 
    "detection_fps": 5.0, 
    "pid": 39, 
    "process_fps": 3.3, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 5.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 1620758251.995247, 
      "inference_speed": 123.46, 
      "pid": 34
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 125.24, 
      "pid": 36
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 54.1, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 13.0
      }, 
      "/media/frigate/clips": {
        "free": 10001.3, 
        "mount_type": "ext4", 
        "total": 31266.3, 
        "used": 19832.8
      }, 
      "/media/frigate/recordings": {
        "free": 10001.3, 
        "mount_type": "ext4", 
        "total": 31266.3, 
        "used": 19832.8
      }, 
      "/tmp/cache": {
        "free": 1000.0, 
        "mount_type": "tmpfs", 
        "total": 1000.0, 
        "used": 0.0
      }
    }, 
    "uptime": 85, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Computer Hardware**
 - OS: Ubuntu Jetson-Nano
 - Install method: Docker Compose
 - Coral Version: None, CPU
 - Network Setup: all wired.. Camera and Jetson

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: DS2CD2732FIS
 - Resolution: 1080p
 - FPS: 25

**Additional context**
```yaml
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64 #-amd64nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/toto/docker/frigate/config:/config
      - /home/toto/docker/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: 'password'
```
