### ISSUE TITLE
BirdsEye with a tall aspect ratio (Portrate) causes strange scrolling messed up view.

### ISSUE THREAD

**Issue by GarethBlain** [blakeblackshear/frigate#10839]
I'm trying to create a BirdsEye view with just two 640x480 camera on top of each other so the image fits on a phone screen nicely.
I've added the following to my config:

```
birdseye:
  enabled: True
  mode: continuous
  restream: true
  width: 640
  height: 960
```

But this results in the following flickering green messed up image:

https://github.com/blakeblackshear/frigate/assets/5220736/3f764122-ebb5-4864-8011-fe6d88cc9dc7

When they are side by side it's fine:

```
birdseye:
  enabled: True
  mode: continuous
  restream: true
  width: 1280
  height: 480
```

I've tried changing the sizes slightly making it wider than needed or taller but it doesn't seem to change. It just tries to fill the space and goes crazy!  🙈
