### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by rourke750** [blakeblackshear/frigate#109]
Has anyone gotten the latest version working with a raspberry pi 4?  I am stuck on the opencv stuff as there arent any packages for arch.

**Comment by kpine** [comment]
opencv-python-headless is provided by piwheels. https://www.piwheels.org/project/opencv-python-headless/

```
pip3 install --extra-index-url https://www.piwheels.org/simple opencv-python-headless
```

**Comment by kpine** [comment]
Some other gotchas with the 0.5.0 update.

You'll need to install the ARM version of the [Tensorflow Lite wheel](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter).

The SharedArray python package was added as a dependency, but there's no binary wheel for it, nor are there any Ubuntu/Debian packages from what I can find. It has a dependency on numpy development files, so it will need to be built from scratch.

**Comment by kpine** [comment]
There's also no wheel for pyarrow.

**Comment by kpine** [comment]
Hmm, well I've been doing a little more research and this is not boding well for Raspberry Pi users.  Hope I'm wrong... :fearful:

The PyArrow python module is now being used in Frigate 0.5.0. As far as I can tell, there is no official support for pyarrow on ARM platforms [1].  It is sounding like it does not build at all for armv7 [2], so if you're using a Raspbian-based OS like I currently am, which only supports 32-bit ARM, you are out of luck.

Otherwise, if you move to an aarch64 based-OS, and you *might* be able to compile it yourself [[3](https://gist.github.com/heavyinfo/04e1326bb9bed9cecb19c2d603c8d521)]. I saw some mention of conda-forge, but I don't see any ARM packages.

[1] https://github.com/apache/incubator-superset/issues/8688
[2] https://issues.apache.org/jira/browse/ARROW-7042
[3] https://gist.github.com/heavyinfo/04e1326bb9bed9cecb19c2d603c8d521

**Comment by blakeblackshear** [comment]
I can drop the SharedArray dependency, but PyArrow is essential to the way I am sharing frames across multiple processes. I don't think there is any way around it. It might be possible to drop it when Python 3.9 comes out and Tensorflow lite supports it. Honestly, Python is such a PITA when it comes to multiprocessing that I considered rewriting it in Go.

**Comment by kpine** [comment]
I was able to install SharedArray 3.0.0 w/o issue, there doesn't seem to be much difference between it and 3.0.2 (also submitted a bug to piwheels).

What's in Python 3.9 that would let you drop PyArrow?

**Comment by blakeblackshear** [comment]
Mainly the new pickle 5 protocol and the way it let's you share memory across multiple processes. At the moment, I am jumping through a bunch of hoops to use a separate process for each camera and share a single process for the Coral across all cameras. There are a lot of efforts in the community to address the issues with the limitations of the GIL in python when it comes to distributed processing.

**Comment by zewelor** [comment]
If pickle 5 is main blocker and it force to use arrow, maybe backport https://github.com/pitrou/pickle5-backport could simplify setup?

**Comment by blakeblackshear** [comment]
Possibly. PyArrow is doing a lot of the legwork for managing shared memory, and it would require substantial changes to recreate that functionality. I would want to take a serious look at porting this project to Go before going down that path.

**Comment by kpine** [comment]
Related question, do you still need to store the frame data in a SharedArray if you are using Plasma?

SharedArray is working in PiWheels again, so it's not an issue at all installing on a Rapsberry Pi. Just curious if it's still necessary.

**Comment by blakeblackshear** [comment]
I don't. It is just leftover from before I switched. I will drop it in a future release.

**Comment by kpine** [comment]
I was able to make a custom built pyarrow wheel from the instructions above for my RPi4. I haven't tried frigate yet but benchmark.py worked (see #111). Hopefully I'll get a chance to try tonight.

**Comment by kpine** [comment]
So far so good, although it's night time so I haven't gotten to test much. I did stick my head out the front door and it detected me, so I can claim some sort of victory at least. Here are the current debug stats:

```json
{
  "coral": {
    "detection_queue": 0,
    "detection_start": 0,
    "fps": 0,
    "inference_speed": 17.47
  },
  "front_door": {
    "detection_fps": 0,
    "fps": 5.1,
    "skipped_fps": 0
  },
  "plasma_store_rc": null,
  "tracked_objects_queue": 0
}
```
Nothing unusual in the container logs. CPU usage looks roughly the same as 0.4.0 for me. I only have one camera.

I've uploaded my Dockerfiles for RPi builds to my [fork](https://github.com/kpine/frigate/commits/rpi), based on 0.5.0. `Dockerfile.rpi-pyarrow` will build the pyarrow python wheel and `Dockerfile.rpi` will build the Frigate image. The wheel binary needs to be copied into the `dist` subdirectory of the root project directory.

I've also got a Frigate test image built [kpine/frigate-raspberrypi:0.5.0-test](https://hub.docker.com/layers/kpine/frigate-raspberrypi/0.5.0-test/images/sha256-c89defeebac2722274b5fdd029fd6fc3a3513b3d27c9f246c4e10508275207ad?context=explore), as well as an image that contains the wheel only, [kpine/raspberrypi-pyarrow-plasma:0.16.0](https://hub.docker.com/layers/kpine/raspberrypi-pyarrow-plasma/0.16.0/images/sha256-7802f3d59b67e99ab63032ae4ffeeb8e0776a333061bc83e500d3592f5ae297f?context=explore).

**Comment by mr-onion-2** [comment]
Hi @kpine 

Thanks for this. I feel like a bit of a noob for asking, but please can you advise how you're meant to use the pyarrow image? When I run it, it just exits after a couple of seconds with no sign of the dist files anywhere

**Comment by rourke750** [comment]
If you don't mind waiting an hour or two I can give you a single dockerfile to run that will do everything for you.

**Comment by mr-onion-2** [comment]
Awesome thanks :)

**Comment by kpine** [comment]
@mr-onion-2 You can create a container and copy the dist directory into the frigate project directory.

```bash
$ cd ~/src/frigate
$ docker create --name pyarrow kpine/raspberrypi-pyarrow-plasma:0.16.0  # or your own image name
7c28c656658efcd79c84ec52e4de50cedfa57f2c9363b8c63cb683495fb07e37
$ docker cp pyarrow:/dist/ .
$ ls dist
pyarrow-0.16.0-cp37-cp37m-linux_armv7l.whl
```

**Comment by mr-onion-2** [comment]
Thanks - worked perfect :)

**Comment by nxtlvlmamba** [comment]
Hi @kpine 
If I may ask, is there any solution in building pyarrow for Raspberry Pi 3B+? I've been installing the Apache Beam SDK to connect my RPi to the Google Cloud Platform (with my virtual environment activated). I'm a bit of a beginner in the Debian OS and I'm encountering an error:
`ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly`

**Comment by Buzztiger** [comment]
Have you tried just to use the Docker image @kpine (kpine/frigate-raspberrypi:0.5.0-test) provided?

Works fine for my pi4. Just follow the original tutorial but adjust in the docker-compose config file the Docker image to the one from kpine

**Comment by nxtlvlmamba** [comment]
Hi @Buzztiger thank you so much for this.

I would like to ask if the image is run in my Raspberry Pi, will it be permanently installed? or does it just work whenever I run it?

**Comment by nxtlvlmamba** [comment]
Hi @Buzztiger thank you so much for this.

I've read some docker documentations and watched some tutorials but most of them are using ubuntu as an example in running images. Can I ask how to run and install the docker image that @kpine provided?

I apologize if this is such a noob question but I can't seem to build pyarrow in my RPi. Thank you for your time and understanding.

**Comment by scstraus** [comment]
What OS are you running on your Pi?

**Comment by nxtlvlmamba** [comment]
@scstraus I've got Raspbian GNU/Linux 10 (buster) installed as my OS. I did the same commands as @kpine has advised:
`$ mkdir pyarrow_kpine`
`$ cd pyarrow_kpine`
`$ docker create --name pyarrow kpine/raspberrypi-pyarrow-plasma:0.16.0`
`$ docker cp pyarrow:/dist/ .`
`$ ls dist`
`pyarrow-0.16.0-cp37-cp37m-linux_armv7l.whl`

I can't seem to figure out how to run and what to do with it as I am just a beginner in these systems.

**Comment by Buzztiger** [comment]
> Hi @Buzztiger thank you so much for this.
> 
> I've read some docker documentations and watched some tutorials but most of them are using ubuntu as an example in running images. Can I ask how to run and install the docker image that @kpine provided?
> 
> I apologize if this is such a noob question but I can't seem to build pyarrow in my RPi. Thank you for your time and understanding.

**Mini Tutorial:**

So I assume we are starting off with a blank raspbian image (Raspbian Buster Lite) on a Pi4 with a coral stick attached. Then just follow one of the various existing tutorials for installing docker and docker-compose on a Pi4 (e.g. https://dev.to/rohansawant/installing-docker-and-docker-compose-on-the-raspberry-pi-in-5-simple-steps-3mgl)

Now for the dry dock for the frigate.

Note: we're directly using @kpine modified version for the Pi4 with the last updates from @blakeblackshear. It's still crashing after a while so we'll add a cronjob to restart it frequently.

1) Create directories
`mkdir /code`
`mkdir /code/02-Frigate`
`mkdir /code/02-Frigate/config`

2) Create config files
`cd /code/02-Frigate`
`/code/02-Frigate# nano docker-compose.yml`

paste the following into this file for the configuration of the docker image:
```
frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
   shm_size: '2g' # should work for 5-7 cameras
   image: kpine/frigate-raspberrypi:latest
   volumes:
     - /dev/bus/usb:/dev/bus/usb
     - /etc/localtime:/etc/localtime:ro
     - /code/02-Frigate/config:/config
   ports:
     - "5000:5000"
```
Config file for the frigate. You will need to adapt this to your own needs e.g. urls to the cam streams etc. 

`/code/02-Frigate/config# nano config.yml`
[config.example.yml]( https://github.com/blakeblackshear/frigate/blob/master/config/config.example.yml)

Now we pull the image and do a first start

`/code/02-Frigate# docker-compose up`

This will take a while but once everything is up you should see lines like:

>Starting frigate ... done
>Attaching to frigate
>frigate   | On connect called

ctrl-c to stop as we want to run this in the background. 

`/code/02-Frigate# docker start frigate`

This should fire up the frigate in the background. Now as mentioned we'll add a cronjob to restart it due to the current bug. 

`/code/02-Frigate# crontab -e` 

Note that the first time you run this it will ask you which editor you prefer. I like nano.

add the following line, which restarts frigate every hour.

> 0 */1 * * * docker restart frigate

This should do it, configuration for home assistant as @blakeblackshear described it [here](https://github.com/blakeblackshear/frigate#integration-with-homeassistant)

**Comment by Fezile01** [comment]
Hi @Buzztiger

Thank you for the mini tutorial.

I am using a Raspberry 3B

When following the tutorial, is pyarrow-0.16.0-cp37-cp37m-linux_armv7l.whl already included in the kpine/frigate-raspberrypi:latest (kpine/frigate-raspberrypi:0.5.1-rc4)?

**Comment by Buzztiger** [comment]
@Fezile01 yes it's already included afaik. At least on my Pi4 this runs out of the box without additional steps.

**Comment by Buzztiger** [comment]
@kpine, @blakeblackshear just to confirm that the recent changes have solved the crash issues for me too. My Pi4 + coral is running stable now for several days. Thank you for all your efforts.

**Comment by andreasfrosig** [comment]
@Buzztiger thanks for the guide! Are you using multiple cameras? My setup seems to have an issue with distinguishing between the cameras for the snapshots and /{camera} feeds. They are jumping (seemingly randomly) between the actual camera rtsp feeds as soon as some object is detected.

**Comment by Buzztiger** [comment]
Yes, I saw your issue. I have currently two cams connected and no issues with swapped channels. I'll hook up the rest of the cams this weekend (4 in total then) and check if I can replicate your problem.

**Comment by Ubique88** [comment]
Thanks @Buzztiger for the mini guild, i have run in to an issue when I try to compose up.

my docker-compose.yml looks like;
```
version: "3.8"

services:
 frigate:
  container_name: frigate
  restart: unless-stopped
  privileged: true
  shm_size: '512m' # should work for 5-7 cameras
  image: kpine/frigate-raspberrypi:latest
  ports:
   - "5000:5000"
  volumes:
   - /dev/bus/usb:/dev/bus/usb
   - /etc/localtime:/etc/localtime:ro
    /code/02-Frigate/config:/config
```
I am not sure if I am missing anything in the config.yml?

But I am getting the error
```
pi@Pi4:/code/02-Frigate $ docker-compose up
Creating frigate ... done
Attaching to frigate
frigate    | Traceback (most recent call last):
frigate    |   File "detect_objects.py", line 345, in <module>
frigate    |     main()
frigate    |   File "detect_objects.py", line 150, in main
frigate    |     client.connect(MQTT_HOST, MQTT_PORT, 60)
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 839, in connect
frigate    |     return self.reconnect()
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 962, in reconnect
frigate    |     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
frigate    |   File "/usr/lib/python3.7/socket.py", line 707, in create_connection
frigate    |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
frigate    |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
frigate    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
frigate    | socket.gaierror: [Errno -2] Name or service not known
frigate    | Traceback (most recent call last):
frigate    |   File "detect_objects.py", line 345, in <module>
frigate    |     main()
frigate    |   File "detect_objects.py", line 150, in main
frigate    |     client.connect(MQTT_HOST, MQTT_PORT, 60)
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 839, in connect
frigate    |     return self.reconnect()
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 962, in reconnect
frigate    |     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
frigate    |   File "/usr/lib/python3.7/socket.py", line 707, in create_connection
frigate    |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
frigate    |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
frigate    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
frigate    | socket.gaierror: [Errno -2] Name or service not known
frigate exited with code 0
frigate    | Traceback (most recent call last):
frigate    |   File "detect_objects.py", line 345, in <module>
frigate    |     main()
frigate    |   File "detect_objects.py", line 150, in main
frigate    |     client.connect(MQTT_HOST, MQTT_PORT, 60)
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 839, in connect
frigate    |     return self.reconnect()
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 962, in reconnect
frigate    |     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
frigate    |   File "/usr/lib/python3.7/socket.py", line 707, in create_connection
frigate    |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
frigate    |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
frigate    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
frigate    | socket.gaierror: [Errno -2] Name or service not known
frigate exited with code 1
frigate    | Traceback (most recent call last):
frigate    |   File "detect_objects.py", line 345, in <module>
frigate    |     main()
frigate    |   File "detect_objects.py", line 150, in main
frigate    |     client.connect(MQTT_HOST, MQTT_PORT, 60)
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 839, in connect
frigate    |     return self.reconnect()
frigate    |   File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 962, in reconnect
frigate    |     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
frigate    |   File "/usr/lib/python3.7/socket.py", line 707, in create_connection
frigate    |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
frigate    |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
frigate    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
frigate    | socket.gaierror: [Errno -2] Name or service not known
frigate exited with code 1
```

**Comment by Buzztiger** [comment]
That looks like some mqtt connection issue. Can you post your config file as well?

**Comment by Ubique88** [comment]
Sorry for the delay we had a rare sunny weekend here in the UK so I sat the garden drinking beer.
Here is my config file, as I said I am not sure if I just have this wrong/misunderstood the example one;
```
web_port: 5000

mqtt:
  host: mqtt.server.com
  topic_prefix: frigate
  # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
  # user: username # Optional
  #################
  ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  ##   password: '{FRIGATE_MQTT_PASSWORD}'
  #################
  # password: password # Optional

#################
# Default ffmpeg args. Optional and can be overwritten per camera.
# Should work with most RTSP cameras that send h264 video
# Built from the properties below with:
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
#################
# ffmpeg:
#   global_args:
#     - -hide_banner
#     - -loglevel
#     - panic
#   hwaccel_args: []
#   input_args:
#     - -avoid_negative_ts
#     - make_zero
#     - -fflags
#     - nobuffer
#     - -flags
#     - low_delay
#     - -strict
#     - experimental
#     - -fflags
#     - +genpts+discardcorrupt
#     - -vsync
#     - drop
#     - -rtsp_transport
#     - tcp
#     - -stimeout
#     - '5000000'
#     - -use_wallclock_as_timestamps
#     - '1'
#   output_args:
#     - -f
#     - rawvideo
#     - -pix_fmt
#     - rgb24

####################
# Global object configuration. Applies to all cameras
# unless overridden at the camera levels.
# Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
# All labels from the model are reported over MQTT. These values are used to filter out false positives.
# min_area (optional): minimum width*height of the bounding box for the detected person
# max_area (optional): maximum width*height of the bounding box for the detected person
# threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
####################
objects:
  track:
    - person
    - car
    - truck
    - cat
    - dog
    - bird
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.5

cameras:
  back:
    ffmpeg:
      ################
      # Source passed to ffmpeg after the -i parameter. Supports anything compatible with OpenCV and FFmpeg.
      # Environment variables that begin with 'FRIGATE_' may be referenced in {}
      ################
      input: rtsp://admin:mypassword@192.168.121.2:554/cam/realmonitor?channel=2&subtype=0
      #################
      # These values will override default values for just this camera
      #################
      # global_args: []
      # hwaccel_args: []
      # input_args: []
      # output_args: []
    
    ################
    ## Optionally specify the resolution of the video feed. Frigate will try to auto detect if not specified
    ################
    # height: 1280
    # width: 720

    ################
    ## Optional mask. Must be the same aspect ratio as your video feed.
    ## 
    ## The mask works by looking at the bottom center of the bounding box for the detected
    ## person in the image. If that pixel in the mask is a black pixel, it ignores it as a
    ## false positive. In my mask, the grass and driveway visible from my backdoor camera 
    ## are white. The garage doors, sky, and trees (anywhere it would be impossible for a 
    ## person to stand) are black.
    ## 
    ## Masked areas are also ignored for motion detection.
    ################
    # mask: back-mask.bmp

    ################
    # Allows you to limit the framerate within frigate for cameras that do not support
    # custom framerates. A value of 1 tells frigate to look at every frame, 2 every 2nd frame, 
    # 3 every 3rd frame, etc.
    ################
    take_frame: 1

    ################
    # The expected framerate for the camera. Frigate will try and ensure it maintains this framerate
    # by dropping frames as necessary. Setting this lower than the actual framerate will allow frigate
    # to process every frame at the expense of realtime processing.
    ################
    fps: 5

    ################
    # Configuration for the snapshots in the debug view and mqtt
    ################
    snapshots:
      show_timestamp: True

    ################
    # Camera level object config. This config is merged with the global config above.
    ################
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.5
```
