### ISSUE TITLE
No Role to Snapshot from main stream

### ISSUE THREAD

**Issue by mattkerrison** [blakeblackshear/frigate#1091]
**Describe the bug**
Using substream for detection but the roles available are:

- detect
- clips
- record
- rtmp

No 'Snapshot' role exists, and I want to capture snapshot with the 4k image not the 640x480 substream.
Any way to accomplish this without having to record clips?

**Version of frigate**
0.8.4 - running on Hassos - 1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: xxxxxxx
  user: frigate
  password: xxxxxxx

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxxxxxx:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    width: 640
    height: 480
    fps: 10
    snapshots:
      enabled: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 10
          car: 10
          truck: 10
          bicycle: 10
          motorcycle: 10
    motion:
      # Optional: motion mask
      # NOTE: see docs for more detailed info on creating masks
      mask: 0,179,0,0,640,0,640,230
   
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - truck
  filters:
    car:
      mask: 640,230,618,341,541,480,363,459

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: Substream - 640x480, Mainstream - 3840 x 2160
 - FPS: 10
