### ISSUE TITLE
list of objects for clips does not seem to work

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#1099]
**Describe the bug**
I think this might be a documentation issue, but I cannot select specific objects for clips

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
clips:
  max_seconds: 240
  objects:
   - person
   - laptop
   - train
   - bus
   - bicycle
  retain:
    default: 10
    objects:
      person: 15
```

**Frigate container logs**
```
Error parsing config: extra keys not allowed @ data['clips']['objects']
```

**Frigate stats**
```json
{
back: {
camera_fps: 5,
capture_pid: 57,
detection_fps: 2.2,
pid: 46,
process_fps: 5,
skipped_fps: 0
},
detection_fps: 7.3,
detectors: {
coral: {
detection_start: 0,
inference_speed: 35.6,
pid: 43
}
},
front: {
camera_fps: 5,
capture_pid: 58,
detection_fps: 5.1,
pid: 55,
process_fps: 5.1,
skipped_fps: 0
},
service: {
storage: {
/dev/shm: {
free: 54.7,
mount_type: "tmpfs",
total: 67.1,
used: 12.4
},
/media/frigate/clips: {
free: 801385.9,
mount_type: "ext4",
total: 3936911.9,
used: 2935470
},
/media/frigate/recordings: {
free: 801385.9,
mount_type: "ext4",
total: 3936911.9,
used: 2935470
},
/tmp/cache: {
free: 10816.7,
mount_type: "ext4",
total: 117608.4,
used: 100773.4
}
},
uptime: 116,
version: "0.8.4-5043040"
}
}```


**Additional context**
in the docs, this is said to be possible. 
https://blakeblackshear.github.io/frigate/configuration/cameras/#clips
