### ISSUE TITLE
Multiple image paths are created, some with previews and some without

### ISSUE THREAD

**Issue by xbmcnut** [blakeblackshear/frigate#1103]
**Describe the bug**
When the add-on is configured in Home Assistant, two media paths are created that are accessible under the media browser; a direct path to Frigate/Clips and another to Local Media/frigate/clips.

I have both snapshots and clips configured and everything is working a treat with a coral USB stick on an i7 NUC with HA. However, when I use the Media Browser in Home Assistant and go to Frigate/Clips, there are no snapshots only clips but at least they have lovely previews and are sorted correctly with the latest top left.

If I browse to Local Media/frigate/clips, there are both clips and snapshots in that folder however there are no image previews and the latest image/clip is all the way at the bottom right so the sort order seems wrong.

Just thought I'd let you know. Screenshots below. Be great if there was only one folder the both snapshots and clips with image previews and the latest clip/snapshot top left.

**Version of frigate**
Output from `/api/version`
0.8.4-5043040
**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 10.0.xxx.xxx
cameras:
  Entry:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://username:password@10.0..xxx.xxx/Streaming/Channels/103
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person

      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 2
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 2
        # Optional: Per object retention days
        objects:
          person: 5

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 2
        # Optional: Per object retention days
        objects:
          person: 5

detectors:
  coral:
    type: edgetpu
    device: usb
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
<html><body>
<!--StartFragment--><div id="content"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filter JSON"></div><div class="panelContent">

  |  
-- | --
Entry |  
camera_fps | 5
capture_pid | 39
detection_fps | 0
pid | 38
process_fps | 5
skipped_fps | 0
detection_fps | 0
detectors |  
coral |  
detection_start | 0
inference_speed | 8.49
pid | 36
service |  
storage |  
/dev/shm |  
free | 8333.8
mount_type | "tmpfs"
total | 8335.7
used | 1.9
/media/frigate/clips |  
free | 223857.9
mount_type | "ext4"
total | 251287.7
used | 14646.7
/media/frigate/recordings |  
free | 223857.9
mount_type | "ext4"
total | 251287.7
used | 14646.7
/tmp/cache |  
free | 8309.5
mount_type | "tmpfs"
total | 8335.7
used | 26.2
uptime | 7399
version | "0.8.4-5043040"

</div></div></div></div><!--EndFragment-->
</body>
</html>
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/1492137/118349008-1b2a0480-b5a2-11eb-8b90-07920f6a945c.png)

![image](https://user-images.githubusercontent.com/1492137/118349012-22e9a900-b5a2-11eb-8039-4c27778e0a65.png)

**Computer Hardware**
 - OS: HassOS on Intel NUC i7
 - Install method: Addon
 - Virtualization: N/A
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: DS-2CD2155FWD-I
 - Resolution: 1280 x 720p
 - FPS: 5 fps

**Additional context**
