### ISSUE TITLE
No more events

### ISSUE THREAD

**Issue by jasonmadigan** [blakeblackshear/frigate#1115]
**Describe the bug**
Frigate working OK for detections, but the `/events` page never shows events - just a message: "No more events"

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

mqtt:
  host: ****
  user: ****
  password: *****

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_cuvid

objects:
  track:
    - person
    - car
    - truck
    - dog
    - cat
    - cow
    - horse
    - motorcycle
    - bus
    - bird
  filters:
    bird:
      min_score: 0.6
      threshold: 0.7
    car:
      min_score: 0.6
      threshold: 0.7
    truck:
      min_score: 0.6
      threshold: 0.7
    person:
      min_score: 0.65
      threshold: 0.75

cameras:
  gate:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 15
    objects:
      filters:
        car:
          min_area: 4000
          threshold: 0.7
          mask: 
            - 0,599,138,615,165,672,184,761,0,786
        cow:
          mask:
            - 2873,547,3284,634,3063,817,2371,799,2117,823,1688,824,1111,840,417,780,388,444
    zones:
      road:
        coordinates: 5,3,8,983,943,1035,1767,1065,2282,1070,2745,1076,3154,1027,3349,951,3371,797,3555,748,3840,726,3835,17
        filters:
          car:
            min_area: 4000
            threshold: 0.7
          person:
            min_area: 1200
            threshold: 0.7
      entrance:
        coordinates: 0,1163,8,2157,3835,2146,3840,1238,3840,832,3572,900,3420,940,3274,1108,3160,1138,2894,1146,2724,1182,2325,1214,1951,1266,1612,1252,1314,1279,911,1252,439,1225
        filters:
          car:
            min_area: 4000
            threshold: 0.7
          person:
            min_area: 1200
            threshold: 0.7
  pumphouse:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
    objects:
      filters:
        car:
          min_score: 0.6
          threshold: 0.7
          mask: 
          - '3832,1167,3716,1162,3638,1216,3613,1274,3585,1356,3585,1439,3634,1484,3758,1476,3836,1472'
          - '1700,1215,1879,1186,1978,1240,1958,1325,1933,1394,1805,1428,1677,1382'
          - 2770,1520,3430,1477,3449,1344,3309,1231,2762,1238
  pumphouseinside:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 1280
    height: 720
    fps: 5
    objects:
      filters:
        person:
          mask:
            - 106,254,196,77,489,82,838,278,621,643,172,458
          min_score: 0.8
          threshold: 0.8
  rear:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
    objects:
      filters:
        car:
          min_score: 0.6
          threshold: 0.7
          mask: 
          - 537,642,1320,542,1637,580,1724,802,1694,995,1504,1125,1116,1201,474,1173,461,835
  garage:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
    objects:
      filters:
        car:
          mask:
            - 2809,257,2939,274,2996,335,3013,414,2916,416,2846,387,2735,356
            - 0,933,579,620,1431,402,1800,697,1730,1243,1505,1476,823,1619,660,1701,387,1774,48,1719            
  patio:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
    objects:
      filters:
        car:
          min_score: 0.6
          threshold: 0.7
          mask: 
           - 3840,628,3488,535,3275,746,3351,1017,3677,1141,3836,1109
  frontlawn:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
    objects:
      filters:
        car:
          min_score: 0.6
          threshold: 0.7
          mask:
            - 0,1557,504,1441,570,1018,0,775
  garageinterior:
    snapshots:
      height: 700
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@****/Streaming/Channels/1/
          roles:
            - detect
    width: 3840
    height: 2160
    fps: 5
    objects:
      track:
        - person
        - bird

```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
