### ISSUE TITLE
list of objects detected by zone

### ISSUE THREAD

**Issue by fanrouge** [blakeblackshear/frigate#1123]
As @blakeblackshear kindly suggested, it would be great to be able to indicate objects detected inside an area.

Maybe like this:

```
camera:
  cour:
    width: 1920
    height: 1080

    ffmpeg:
      inputs:
        - path: rtsp://camera_cour:554/stream=0
          roles:
            - clips
            - detect

    zones:
      A:
        coordinates: 1920,0,1920,280,0,280,0,0
        objects:
          track:
            - person
            - car
      B:
        coordinates: 0,1080,1920,1080,1920,280,0,280
        objects:
          track:
            - dog
            - cat
            - bird

    clips:
      enabled: True
      required_zones:
      - A
      - B

    snapshots:
      enabled: True
      required_zones:
      - A
      - B

```

This has been discussed #1107.

Thank you very much for considering this need :-)
