### ISSUE TITLE
can /tmp/cache and /dev/shm use same mount?

### ISSUE THREAD

**Issue by SlavikCA** [blakeblackshear/frigate#11284]
I'm running Frigate 0.13.1 in Kubernetes.

First I tried to install it via Helm Chart:
https://github.com/blakeblackshear/blakeshome-charts/tree/master/charts/frigate

There are many issues with that chart, but I managed to run it and after running found, that /tmp/cache doesn't use memory, but points to the disc (container overlay disc, not volume).

So, I'm writing my my own Kubernetes manifest here: https://gitlab.acloud.app/system/harvester/-/tree/main/frigate

I noticed, that both  `/tmp/cache` and `/dev/shm` are expected to use memory, not disc space. So, logically the question: can I use one mount for both of these locations?
In Kubernetes it would be:

```
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: dshm
              mountPath: /tmp/cache
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
```

I know, that Docker has special way to handle `tmpfs` and `shm`. It looks like there is nothing like that in Kubernetes - just Memory mount. 
So, will `/dev/shm` and `/tmp/cache` interfere with each other? Is there any reason to keep them separate?
