### ISSUE TITLE
issues connecting to Neolink (Reolink Lumus), various errors

### ISSUE THREAD

**Issue by sorb42** [blakeblackshear/frigate#1146]
Hi,

I have now spent several hours trying to get my Reolink Lumus camera working with Frigate in HomeAssistant. Unfortunately the camera doesn't support RTSP out of the box, but there is an additional tool doing the needed protocol translation: [Neolink](https://github.com/thirtythreeforty/neolink) which also uses GStreamer in it's heart. Neolink is running inside Portainer also on Home Assistant.

It is complicated to boil the problem down to a single point of failure, every time I try it, it turns out a little different. Furthermore I have 3 Reolink Lumus cameras, all the same HW version and SW version, one of them seems to work fine the others causing the below issues.

The obvious error I get is this:
```
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for front: 40
frigate.app                    INFO    : Capture process started for front: 41
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb:0
frigate.edgetpu                INFO    : TPU found
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : stereo
ffmpeg.front.detect            ERROR   : Input #0, rtsp, from 'rtsp://user:pass@10.0.0.2:8554/front':
ffmpeg.front.detect            ERROR   :   Metadata:
ffmpeg.front.detect            ERROR   :     title           : Session streamed with GStreamer
ffmpeg.front.detect            ERROR   :     comment         : rtsp-server
ffmpeg.front.detect            ERROR   :   Duration: N/A, start: 1621786867.494438, bitrate: N/A
ffmpeg.front.detect            ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1920x1088, 90k tbr, 90k tbn, 180k tbc
ffmpeg.front.detect            ERROR   :     Stream #0:1: Audio: pcm_s16be, 16000 Hz, stereo, s16, 512 kb/s
ffmpeg.front.detect            ERROR   : Stream mapping:
ffmpeg.front.detect            ERROR   :   Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
ffmpeg.front.detect            ERROR   : Press [q] to stop, [?] for help
ffmpeg.front.detect            ERROR   : frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
ffmpeg.front.detect            ERROR   : [NULL @ 0x561fbdc6dac0] missing picture in access unit with size 22
ffmpeg.front.detect            ERROR   : [h264 @ 0x561fbdc88940] no frame!
ffmpeg.front.detect            ERROR   : Error while decoding stream #0:0: Invalid data found when processing input
ffmpeg.front.detect            ERROR   : Output #0, rawvideo, to 'pipe:':
ffmpeg.front.detect            ERROR   :   Metadata:
ffmpeg.front.detect            ERROR   :     title           : Session streamed with GStreamer
ffmpeg.front.detect            ERROR   :     comment         : rtsp-server
ffmpeg.front.detect            ERROR   :     encoder         : Lavf58.45.100
ffmpeg.front.detect            ERROR   :     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1088, q=2-31, 250675 kb/s, 10 fps, 10 tbn, 10 tbc
ffmpeg.front.detect            ERROR   :     Metadata:
ffmpeg.front.detect            ERROR   :       encoder         : Lavc58.91.100 rawvideo
ffmpeg.front.detect            ERROR   : frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
ffmpeg.front.detect            ERROR   : video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg.front.detect            ERROR   : Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
ffmpeg.front.detect            ERROR   : Conversion failed!
```
The problem is: once I see the errors in the Frigate log, this also crashes Neolink and it's restarting the container.

ffprobe gives the following details:
```
ffprobe -i rtsp://user:pass@10.0.0.2:8554/front
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
Input #0, rtsp, from 'rtsp://user:pass@10.0.0.2:8554/front':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.005256, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1088, 90k tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: pcm_s16be, 16000 Hz, 2 channels, s16, 512 kb/s
```

Finally my config:
```
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'

mqtt:
  host: 10.0.0.2
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <pass>

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  global_args: 
    -hide_banner 
    -loglevel info
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - "1"
  output_args:
    rtmp: -c:v copy -f flv

cameras:
  front:
    ffmpeg:
      inputs:
        - path: 'rtsp://user:pass@10.0.0.2:8554/front'
          roles:
            - detect
      output_args:
        rtmp: -c:v copy
    width: 1920
    height: 1088
    fps: 10
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

objects:
  track:
    - person
    - cat
    - dog
    - bird
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
```

I have already disabled the RTMP forwarding, as this is crashing right away.

**Comment by blakeblackshear** [comment]
Try removing some of the input args to see if ffmpeg is just being too aggressive when fetching data from neolink.

**Comment by blakeblackshear** [comment]
Maybe this
```yaml
input_args​:
        - ​-avoid_negative_ts​
        - ​make_zero​
        - ​-fflags​
        - ​+genpts​
        - ​-use_wallclock_as_timestamps​
        - ​'​1​'​
        - ​-rtsp_transport​
        - ​tcp 
```

**Comment by sorb42** [comment]
replace the input_args with what has been suggessted by you. Now cause the following errors:
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.coral                 INFO    : Starting detection process: 36
frigate.app                    INFO    : Camera processor started for front: 39
frigate.edgetpu                INFO    : Attempting to load TPU as usb:0
frigate.app                    INFO    : Capture process started for front: 40
frigate.edgetpu                INFO    : TPU found
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : [rtsp @ 0x56055a9e7900] UDP timeout, retrying with TCP
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : stereo
ffmpeg.front.detect            ERROR   : Input #0, rtsp, from 'rtsp://user:pass@10.0.0.2:8554/front':
ffmpeg.front.detect            ERROR   :   Metadata:
ffmpeg.front.detect            ERROR   :     title           : Session streamed with GStreamer
ffmpeg.front.detect            ERROR   :     comment         : rtsp-server
ffmpeg.front.detect            ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
ffmpeg.front.detect            ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1920x1088, 90k tbr, 90k tbn, 180k tbc
ffmpeg.front.detect            ERROR   :     Stream #0:1: Audio: pcm_s16be, 16000 Hz, stereo, s16, 512 kb/s
ffmpeg.front.detect            ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url ​-avoid_negative_ts​ -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
ffmpeg.front.detect            ERROR   : Error parsing options for output file ​-avoid_negative_ts​.
ffmpeg.front.detect            ERROR   : Error opening output files: Invalid argument
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : [rtsp @ 0x55caa47c5900] UDP timeout, retrying with TCP
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : stereo
ffmpeg.front.detect            ERROR   : Input #0, rtsp, from 'rtsp://user:pass@10.0.0.2:8554/front':
ffmpeg.front.detect            ERROR   :   Metadata:
ffmpeg.front.detect            ERROR   :     title           : Session streamed with GStreamer
ffmpeg.front.detect            ERROR   :     comment         : rtsp-server
ffmpeg.front.detect            ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
ffmpeg.front.detect            ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1920x1088, 90k tbr, 90k tbn, 180k tbc
ffmpeg.front.detect            ERROR   :     Stream #0:1: Audio: pcm_s16be, 16000 Hz, stereo, s16, 512 kb/s
ffmpeg.front.detect            ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url ​-avoid_negative_ts​ -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
ffmpeg.front.detect            ERROR   : Error parsing options for output file ​-avoid_negative_ts​.
ffmpeg.front.detect            ERROR   : Error opening output files: Invalid argument
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : [rtsp @ 0x563de926e900] UDP timeout, retrying with TCP
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : stereo
ffmpeg.front.detect            ERROR   : Input #0, rtsp, from 'rtsp://user:pass@10.0.0.2:8554/front':
ffmpeg.front.detect            ERROR   :   Metadata:
ffmpeg.front.detect            ERROR   :     title           : Session streamed with GStreamer
ffmpeg.front.detect            ERROR   :     comment         : rtsp-server
ffmpeg.front.detect            ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
ffmpeg.front.detect            ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1920x1088, 90k tbr, 90k tbn, 180k tbc
ffmpeg.front.detect            ERROR   :     Stream #0:1: Audio: pcm_s16be, 16000 Hz, stereo, s16, 512 kb/s
ffmpeg.front.detect            ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url ​-avoid_negative_ts​ -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
ffmpeg.front.detect            ERROR   : Error parsing options for output file ​-avoid_negative_ts​.
ffmpeg.front.detect            ERROR   : Error opening output files: Invalid argument
``` 

Last time I didn't put the debug info:
```
{
  "cameras": {
    "front": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 50
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel info -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p ​-avoid_negative_ts​ ​make_zero​ ​-fflags​ ​+genpts​ ​-use_wallclock_as_timestamps​ ​'​1​'​ ​-rtsp_transport​ ​tcp -i rtsp://user:pass@10.0.0.2:8554/front -r 10 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "fps": 10,
      "frame_shape": [
        1088,
        1920
      ],
      "height": 1088,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 181,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front",
      "objects": {
        "filters": {
          "bird": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 5000,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": null,
        "track": [
          "person",
          "cat",
          "dog",
          "bird"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 1920,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral": {
      "device": "usb:0",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "10.0.0.2",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "frigate"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

At least it doesn't seem to crash the Neolink container anymore.

**Comment by blakeblackshear** [comment]
Can you post your full config again? Ffmpeg is complaining that your parameters are invalid.

**Comment by sorb42** [comment]
here is the complete frigate.yaml:
```YAML
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'

mqtt:
  host: 10.0.0.2
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <pass>

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  global_args: 
    -hide_banner 
    -loglevel info
  input_args​:
    - ​-avoid_negative_ts​
    - ​make_zero​
    - ​-fflags​
    - ​+genpts​
    - ​-use_wallclock_as_timestamps​
    - ​'​1​'​
    - ​-rtsp_transport​
    - ​tcp 
  output_args:
    rtmp: -c:v copy -f flv

cameras:
  front:
    ffmpeg:
      inputs:
        - path: 'rtsp://user:pass@10.0.0.2:8554/front'
          roles:
            - detect
      output_args:
        rtmp: -c:v copy
    width: 1920
    height: 1088
    fps: 10
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

objects:
  track:
    - person
    - cat
    - dog
    - bird
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
```

**Comment by blakeblackshear** [comment]
Your global args aren't formatted properly. Try this:
```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'

mqtt:
  host: 10.0.0.2
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <pass>

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args​:
    - ​-avoid_negative_ts​
    - ​make_zero​
    - ​-fflags​
    - ​+genpts​
    - ​-use_wallclock_as_timestamps​
    - ​'​1​'​
    - ​-rtsp_transport​
    - ​tcp 
  output_args:
    rtmp: -c:v copy -f flv

cameras:
  front:
    ffmpeg:
      inputs:
        - path: 'rtsp://user:pass@10.0.0.2:8554/front'
          roles:
            - detect
      output_args:
        rtmp: -c:v copy
    width: 1920
    height: 1088
    fps: 10
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

objects:
  track:
    - person
    - cat
    - dog
    - bird
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
```
