### ISSUE TITLE
ffmpeg processes are running when all outputs are disabled

### ISSUE THREAD

**Issue by b3nj1** [blakeblackshear/frigate#1147]
**Describe the bug**
If detection and all outputs are disabled, ffmpeg processes are still running. 

To save system resources and power, I'd rather the system sit idle when all outputs and detection are disabled. Right now, there are ffmpeg processes setup for each camera and role while waiting for the outputs to be enabled. 

If this is an acceptable feature, I'd be willing to create a PR. I think it could be done without much disruption.
 
**Version of frigate**
0.9.0-3fdf789

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
cameras:
  frigate_garage:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@10.0.1.120:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pass@10.0.1.120:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
            - record
    width: 704
    height: 480
    fps: 5
    rtmp:
      enabled: False

```

**Additional context**
HW configuration doesn't seem relevant, but I can add it if it helps.
