### ISSUE TITLE
RTSP IP CAMERA RESOLUTION 640x368

### ISSUE THREAD

**Issue by sebater** [blakeblackshear/frigate#1152]
Hello, I can´t visualize correctly the ip camera video, when open frigate the camera looks like wrong resolution, but,  my camera has a not conventional video resolution, there is a solution for this?
![Captura](https://user-images.githubusercontent.com/70472548/119894760-6255b500-bf13-11eb-85bc-268fb053fe34.JPG)

rtsp://192.168.100.118:554/user=admin_password=q6orzogE_channel=0_stream=1.sdp?real_stream

Resolution: 640x368
Encoding: H264
Hardware H.264 codec	Software H.265 codec
Transport Protocol: HTTP

**Version of frigate**
1.13 

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
    host: 192.168.100.7
    user: mqtt
    password: mqtt
    

cameras:
  backyd:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.100.118:554/user=admin_password=q6orzogE_channel=0_stream=0.sdp?real_stream
          roles:
            - detect
            - clips
    width: 640
    height: 368

    fps: 5
    objects:
        track:
            - person

    snapshots:
        enabled: True
        timestamp: false
        bounding_box: True
        retain:
            default: 2
    clips:
        enabled: True
        retain:
            default: 2

detectors:
  cpu1:
     type: cpu
  cpu2:
     type: cpu
```

**Frigate container logs**
```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera backyd has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 36
detector.cpu2                  INFO    : Starting detection process: 37
frigate.app                    INFO    : Camera processor started for backyd: 41
frigate.app                    INFO    : Capture process started for backyd: 42
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
