### ISSUE TITLE
detect not using fps setting

### ISSUE THREAD

**Issue by gniting** [blakeblackshear/frigate#11715]
**Describe what you are trying to accomplish and why in non technical terms**
Limit detect fps to 5

**Describe the solution you'd like**
detect should use 5 fps and cause fffmpeg to use less CPU

**Describe alternatives you've considered**
N/A

**Additional context**
Even though I have the following in my camera and global config, fps is higher than 5
```
...
detect:
   enabled: true
   fps: 5
...
cameras:
  office:
     enabled: true
     ffmpeg:
       inputs:
       - path: rtsp://@192.168.7.14:554/cam/realmonitor?channel=2&subtype=0
         roles:
         - record
         - detect
     detect:
       fps: 5
```
![image](https://github.com/blakeblackshear/frigate/assets/1123016/728fe889-1c16-4020-bcfb-11171f0df34b)
