### ISSUE TITLE
[UI] Bring back Audio to Camera Live View and Review View

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#11826]
**Describe what you are trying to accomplish and why in non technical terms**
1.) When selecting a Audio capable camera from the start page, be able to listen to the audio of the camera in the Live Playback
2.) When reviewing events, same thing. When reviewing the clip from an Audio Capable Camera, hear the audio 

**Describe the solution you'd like**
Bring back Audio to the new UI in 0.14.0.

**Describe alternatives you've considered**
Roll back to 0.13.x

**Additional context**
The audio is included when exporting clips. :)

**Comment by NickM-27** [comment]
1. This is supported via the buttons in the top right
2. There are audio controls for recordings as well

**Comment by tubalainen** [comment]
> 1. This is supported via the buttons in the top right
> 2. There are audio controls for recordings as well

Hi Nick - Thanks for your reply!

I made a boo-boo for the review part. There are audio options there. My mistake. Sorry.,
![image](https://github.com/blakeblackshear/frigate/assets/26795429/002e7516-7122-431c-a67e-87b39615edfd)

But I cannot get it to work in the "Live View". No Audio options.
![image](https://github.com/blakeblackshear/frigate/assets/26795429/86edf278-e962-48a4-addc-e1c6f981d11b)

Have I missed any config perhaps?

Thanks a billion!

**Comment by NickM-27** [comment]
The audio option only shows up when the camera has audio support

**Comment by tubalainen** [comment]
> The audio option only shows up when the camera has audio support

Odd, it works in the Review part of Frigate but not the Live View. Will check my config if you are 100% sure its not a bug. :)

**Comment by FrankRodelli** [comment]
Here is how I got it working:

```
 kids_camera: 
      - rtsp://user:pass@192.168.1.xxx/live0
      - "ffmpeg:kids_camera#audio=opus"
cameras:
  kids:
    live:
      stream_name: kids_camera
```

**Comment by tubalainen** [comment]
> Here is how I got it working:
> 
> ```
> go2rtc:
>   streams:
>     kids_camera: 
>          - rtsp://user:pass@192.168.1.xxx/live0
>          - "ffmpeg:kids_camera#audio=opus"
> cameras:
>   kids:
>     live:
>       stream_name: kids_camera
> ```

YOU ARE A STAR FRANK! Thanks a billion! Works great!

The reference config doesnt mention that the `live:` option can be used per camera (happy to make a PR).
And the reference config is referring to the camera_name. I think that it might be wrong, it should be stream name from go2rtc.
Do you agree @FrankRodelli ?

Here is my (full) example conf, note that the `camera_name` is different from the `stream_name`:
```
go2rtc:
  streams:
    cam11_ch1:
      - rtsp://user:pass@192.168.1.xx:8554/Streaming/Channels/101
      - ffmpeg:cam11_ch1#audio=aac

cameras:
  cam11_inomhus:
    ffmpeg:
      inputs:
        - path: rtsp:/localhost:8554/cam11_ch1?video&audio
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      stream_name: cam11_ch1

```

Thanks again.
