### ISSUE TITLE
Trying to build Docker under ARM64 - i965-va-driver missing

### ISSUE THREAD

**Issue by OXERY** [blakeblackshear/frigate#120]
Hi there,

just tried to build the container on my rockpro64 arm64 board. 
Did anybody manage this?
Am stuck at "E: Package 'i965-va-driver' has no installation candidate" - ubuntu does only have installations for x86 and amd64..

**Comment by jalbstmeijer** [comment]
search for 'i965-va-driver' in the issues and find https://github.com/blakeblackshear/frigate/issues/60

**Comment by OXERY** [comment]
Thanks for your answer. Next step, that fails: There seems to be no arm64 build of opencv-python-headless.. (neither on pypi, nor on piwheels.org (mentioned in #109

**Comment by kpine** [comment]
You're probably going to have to compile it yourself. I was previously using this for my RPi:
```
# Build Python wheel
RUN cd /tmp \
 && git clone --branch=24 --depth=50 https://github.com/skvark/opencv-python \
 && cd opencv-python \
 && ENABLE_HEADLESS=1 python3 setup.py bdist_wheel

# ... in another multi-stage build step

# Install python-opencv
COPY --from=opencv-builder /tmp/opencv-python/dist/opencv_python_*.whl /tmp/
RUN pip3 install opencv_python_headless-4*
```
The branch is a [release tag](https://github.com/skvark/opencv-python/releases), so pick whichever one works for you, or download the zip/tarball instead of using git.

Or you might try using Debian Sid or Ubuntu 20.04 as a base image and see where that gets you, both currently have python3-opencv (opencv 4.2.0) already packaged.

You will also have to compile PyArrow yourself. The Dockerfiles I posted in #109 do that. Looks like there is also a aarch64 build provided by conda forge. https://anaconda.org/conda-forge/pyarrow

**Comment by scantineau** [comment]
Hi @kpine,

You said "I was previously using this for my RPi" --> Does it mean you stopped trying to use frigate on RPi ? And if yes, why ?

**Comment by kpine** [comment]
No, I still use the RPi, I just don't have any reason to build opencv, it's already a provided package.

**Comment by scantineau** [comment]
Yes ok. I'am using your docker build but I don't understand why I have some "lags" (almost 1 minute) with only one camera.

**Comment by kpine** [comment]
I have never had any problems, I also only have one camera, a Dahua.

I have updated the Docker image to the just released 0.5.1-rc3, you might try that.

**Comment by Buzztiger** [comment]
Same over here, but I'm also using two Dahua cams. I'm running @kpine Rpi docker image on a Pi4. Besides the frequently needed restarts this image works excellent.

**Comment by andreasfrosig** [comment]
I run with 5 reolink cameras on an pi 4 with Coral, using @kpine image. I experience that the feeds are getting mixed up. When I get a person on 1 cam I get the same square on several, and often the /{camera}/last/person mqtt message will have an image from a wrong camera.  Anyone know how this can happen?
I can see that the image stream flickers between the cameras when looking at the /{camera} feed.

**Comment by blakeblackshear** [comment]
Can you post your config?

**Comment by andreasfrosig** [comment]
Of course:
```
web_port: 5000

mqtt:
  host: 192.168.1.25
  topic_prefix: frigate
  user: user 
  password: 'password'

objects:
  track:
    - person
  filters:
    person:
      min_area: 1000
      max_area: 100000
      threshold: 0.5

cameras:
  front_west:
    ffmpeg:
      input: rtsp://user:password@192.168.1.140:554/h264Preview_01_sub
    height: 480
    width: 640
    take_frame: 1
    fps: 4
    snapshots:
      show_timestamp: True
  front_east:
    ffmpeg:
      input: rtsp://user:password@192.168.1.140:554/h264Preview_02_sub
    height: 480
    width: 640
    take_frame: 1
    fps: 4
    snapshots:
      show_timestamp: True
  back_west:
    ffmpeg:
      input: rtsp://user:password@192.168.1.140:554/h264Preview_03_sub
    height: 480
    width: 640
    take_frame: 1
    fps: 4
    snapshots:
      show_timestamp: True
  side_east:
    ffmpeg:
      input: rtsp://user:password@192.168.1.140:554/h264Preview_04_sub
    height: 480
    width: 640
    take_frame: 1
    fps: 4
    snapshots:
      show_timestamp: True
  back_east:
    ffmpeg:
      input: rtsp://user:password@192.168.1.140:554/h264Preview_05_sub
    height: 480
    width: 640
    take_frame: 1
    fps: 4
    snapshots:
      show_timestamp: True
```
