### ISSUE TITLE
Direct URL to full screen of camera group / layout?

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#12048]
**Describe what you are trying to accomplish and why in non technical terms**
(This may already exist - and I'm just not good enough with chrome inspector / developer tools to figure out the request/url).  **Im trying to get a URL that will bring me directly to the live page of a camera group?**  (ie the page in the image below)

(my use case is: I have various windows PCs and raspberry PIs that will display cameras via chrome/chromeium, launching at startup, to load a URL at full screen).

for anyone interested im using a bash script that executes this (in the case of my ras PIs):
```DISPLAY=:0 chromium-browser -start-maximized -kiosk -noerrdialogs "http://10.6.6.114:5000/" &```

is there a URL we can use to go directly to the live page of a camera group?  (ie the page in my image below) 

even better if its possible to "click" the full screen button in the bottom right corner (however i can script this mouse click, if only i could get a URL to a camera group page).

(i could Of course script both mouse clicks, but I'm trying to avoid that if a URL exists or is possible.)

or if not this could be a **feature request** for such a url to be coded, As I'm sure there are use cases beyond mine for this (for example a bookmark on a phone/tablet that when you tap it it opens the web browser directly to a specific camera group).

thanks

![image](https://github.com/blakeblackshear/frigate/assets/60830628/5c97388d-eb86-46e8-bce0-d8d850d4d1a2)

**Comment by hawkeye217** [comment]
> To get to a group it's as simple as `http://10.6.6.114:5000/groupname`
> 
> Individual live camera `http://10.6.6.114:5000/#cameraname`

This is correct for individual cameras, but the group URL is incorrect. Group URLs have been added in this PR: https://github.com/blakeblackshear/frigate/pull/12061

example:

`<frigate_url>/?group=<group_name>`

The `group_name` is case sensitive and spaces are replaced with underscores.

**Comment by elcovv** [comment]
The camera group link doesn't work in my setup. I'm using the nginx reverse proxy in the frigate docker. Can it be that the reverse proxy doesn't pass the /?group=<group_name> URI to frigate?

**Comment by elcovv** [comment]
The camera group link doesn't work in my setup. I'm using the nginx reverse proxy in the frigate docker. Can it be that the reverse proxy doesn't pass the /?group=<group_name> URI to frigate?

**Comment by NickM-27** [comment]
Only if you don't have my configured to handle it

**Comment by elcovv** [comment]
Nothing is changed from the default nginx configuration files that come with the docker. If I go to https://frigate.mydomain/?group=groupname the browser redirects to https://frigate.mydomain/ and shows the camera group that was previously shown.

Are there any changes I should make for this to work?

I'm running frigate version 0.15.0-cea210d 

And this is the compose.yaml for the docker:

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/letsencrypt/<path>:/etc/letsencrypt/live/frigate:ro
      - /etc/localtime:/etc/localtime:ro
      - <path>/config:/config
      - <path>/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "443:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
     - PLUS_API_KEY=<API_KEY>
     - YOLO_MODELS=yolov7-320,yolov7x-640
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: all # number of GPUs
              capabilities: [gpu]
```
