### ISSUE TITLE
Inference Speed Slow

### ISSUE THREAD

**Issue by hkrob** [blakeblackshear/frigate#1208]
**Describe the bug**
Not saying this is a bug - but I am seeing inference speeds around 39.
This is with a Coral connected over USB 3 to Odroid N2+

Trying to figure out if this is expected or something in need of tweaking. 3 cameras, low res streams, 5 fps

**Version of frigate**
Version 1.13 running in Home Assistant Supervised.

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  # Required: host name
  host: ha-prod.REMOVED
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: REMOVED
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: REMOVED
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60  
cameras:
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://REMOVED/ch0_1.h264 # Video resolution: 640x360
          roles:
            - detect
            - rtmp
        - path: rtsp://REMOVED/ch0_0.h264 # high res Video resolution: 1920x1080
          roles:
            - clips
            - record
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      retain:
        default: 5    
    snapshots:
      enabled: true
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 5   
    # resolution of the DETECT role 
    width: 640
    height: 360
    # Optional: desired fps for your camera for the input with the detect role
    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
    #       Frigate will attempt to autodetect if not specified.
    fps: 5       
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://REMOVED/ch0_1.h264 # low res 640x360
          roles:
            - detect
            - rtmp
        - path: rtsp://REMOVED/ch0_0.h264 # high res
          roles:
            - clips
            - record
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      retain:
        default: 5    
    snapshots:
      enabled: true
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 5   
    # Required: width of the frame for the input with the detect role
    width: 640
    # Required: height of the frame for the input with the detect role
    height: 360
    # Optional: desired fps for your camera for the input with the detect role
    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
    #       Frigate will attempt to autodetect if not specified.
    fps: 5       
#
  dahua:
    ffmpeg:
      inputs:
        - path: rtsp://REMOVED:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # low res 704x576
          roles:
            - detect
            - rtmp
        - path: rtsp://REMOVED:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # high res 3072x2048
          roles:
            - clips
            - record
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      retain:
        default: 5    
    snapshots:
      enabled: true
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 5   
    # Required: width of the frame for the input with the detect role
    width: 704
    # Required: height of the frame for the input with the detect role
    height: 576
    # Optional: desired fps for your camera for the input with the detect role
    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
    #       Frigate will attempt to autodetect if not specified.
    fps: 5       
#
ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - "1"
#
#detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
#
detectors:
  coral:
    type: edgetpu
    device: usb
#
#
logger:
  # Optional: default log level (default: shown below)
  default: warning
  # Optional: module by module log level configuration
  logs:
    frigate.edgetpu: debug
  #  frigate.mqtt: info
#    
objects:
  track:
    - person
    - cat
#
detect:
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
#  
clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
  # tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 6
#      
```

**Frigate container logs**
```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera kitchen has record assigned to an input, but record is not enabled.
frigate.app                    WARNING : Camera livingroom has record assigned to an input, but record is not enabled.
frigate.app                    WARNING : Camera dahua has record assigned to an input, but record is not enabled.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found

```
**Computer Hardware**
 - OS: [Armbian]
 - Install method: [e.g. Addon]
 - Coral Version: [e.g. USB]
 - Network Setup: [e.g. Wired]

**Debug**
'''
DEBUG 0.8.4-5043040
detector	inference speed	detection start	pid
coral	39.42	0	41
camera	camera fps	process fps	skipped fps	detection fps	pid	capture pid
kitchen	5.1	5.1	0	0	43	46
livingroom	5.1	5	0	0.9	44	47
dahua	5	5	0	0	45	50
'''
