### ISSUE TITLE
Doorbell not working

### ISSUE THREAD

**Issue by jerryaycock** [blakeblackshear/frigate#1209]
I have cameras that work great in Frigate. Move to My Doorbell and it fails. Doorbell looks great in VLC. I have tried every L x W

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  host: 192.168.xx.xxx
  port: 1883
  client_id: xxxxx
  user: xxxx
  password: xxxx
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
 
cameras:
  office:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.31.233:554/onvif1
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: true
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      track:
        - person
```

```yaml
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for office: 40
detector.cpu1                  INFO    : Starting detection process: 37
frigate.app                    INFO    : Capture process started for office: 41
frigate.video                  INFO    : office: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : office: ffmpeg process is not running. exiting capture thread...
```
