### ISSUE TITLE
Periodic database dumps to ensure consistent backups

### ISSUE THREAD

**Issue by AlexandreRatte** [blakeblackshear/frigate#12172]
## Describe what you are trying to accomplish and why in non technical terms
I want to be able to perform periodic sqlite3 database dumps so that I can have a database backup adhering to the [ACID](https://www.sqlite.org/transactional.html) principle. When used in conjunction with my preferred backup solution, this will enable me to restore my Frigate workload and its recordings in a known working state in case of disaster.

## Describe the solution you'd like
I propose starting small by supporting a single optional daily database dump at midnight.

This could be accomplished by adding a single new `database.daily_db_dumps` boolean value in `config.yaml` with a default value of `false`. At midnight, trigger the `.dump` sqlite3 statement and output to the location defined by `database.path` with the added `.dump.yyyyMMdd` suffix.

Example:

```YAML
database:
  # The path to store the SQLite DB (default: shown below)
  path: /custom_location/db/frigate.db
  # Optional: Enable daily database backups at midnight where the file name is the same as the above path, with the added .dump.yyyyMMdd suffix.
  daily_db_dumps: true
```
With the above example configuration, at midnight on 2024-06-26, Frigate would dump the daily backup into `/custom_location/db/frigate.db.dump.20240626`

Nice-to-haves:
- Ability to schedule the time of day for the backup's execution.
- Compress the database dump.
- Keep only the latest X number of daily backups.

## Describe alternatives you've considered
Having my backup solution trigger a pre-backup script that would exec into the running container, ensure the `sqlite3` client is installed and execute `sqlite3 frigate.db .dump | gzip -c > frigate.dump.gz`. Perhaps this could actually be performed on the container's host instead?

## Additional context
N/A
