### ISSUE TITLE
Frigate cannot detect Coral M2 in Docker

### ISSUE THREAD

**Issue by DanPatten** [blakeblackshear/frigate#1226]
**Describe the bug**
I am unable to get frigate working via docker-compose with my coral m2 (https://www.sparkfun.com/products/15887). 

I successfully see the device in device manager and ran the test and works successfully: https://coral.ai/docs/m2/get-started/#4-run-a-model-on-the-edge-tpu

I tried to run lspci and get no devices back inside the docker container. 

**Version of frigate**
docker compose: blakeblackshear/frigate:stable-amd64

**Config file**
```
mqtt:
  host: 192.168.0.181
  port: 1883
  user: mqtt
  password: xxxx
  topic_prefix: frigate
  client_id: frigate
cameras:
  nursery:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.1:744...
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5
detectors:
  coral:
    type: edgetpu
    device: pci
logger:
  default: debug
```

**Docker Compose**
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - E:\AI\Frigate\config:/config
      - E:\AI\Frigate\media:/media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: 'xxx'
```

**Logs**
```
frigate | detector.coral INFO : Starting detection process: 50

frigate | Process detector:coral:

frigate | frigate.edgetpu INFO : Attempting to load TPU as

frigate | frigate.edgetpu INFO : No EdgeTPU detected.

frigate | Traceback (most recent call last):

frigate | File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate

frigate | delegate = Delegate(library, options)

frigate | File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__

frigate | raise ValueError(capture.message)

frigate | ValueError
```

**Computer Hardware**
 - OS: Windows 10
 - Install method: Docker Compose
 - Coral Version: PCI via M.2 slot (confirmed working on windows)
 - Network Setup: Ethernet
