### ISSUE TITLE
Camera backyard has clips enabled, but clips is not assigned to an input.

### ISSUE THREAD

**Issue by timota** [blakeblackshear/frigate#1227]
**Describe the bug**
Using basic config file with one camera. IN logs during startup got this message
```
frigate.app                    WARNING : Camera backyard has clips enabled, but clips is not assigned to an input.
frigate.app                    WARNING : Camera backyard has rtmp assigned to an input, but rtmp is not enabled.
```
but they are definitely enabled in config file. Also, in UI i can see live stream. But no clips created at all

**Version of frigate**
`0.8.4-5043040`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
#frigate sample config.yml
detectors:
  coral_pci:
    type: edgetpu
    device: usb

mqtt:
  # Required: host name
  host: 192.168.x.x
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate-main
  # Optional: user
  user: USER
  # Optional: 
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: PASS
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWORD@192.168.1.21:554/h264Preview_01_main
          hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
          global_args: -y -hide_banner -loglevel info
          roles:
            - detect
            - rtmp
    width: 2560
    height: 1920
    fps: 10
    rtmp:
      enabled: False
    clips:
      enabled: True
```

**Frigate container logs**
```
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera backyard has clips enabled, but clips is not assigned to an input.
frigate.app                    WARNING : Camera backyard has rtmp assigned to an input, but rtmp is not enabled.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.coral_pci             INFO    : Starting detection process: 45
frigate.app                    INFO    : Camera processor started for backyard: 48
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Capture process started for backyard: 57
frigate.edgetpu                INFO    : TPU found
frigate.events                 WARNING : Unable to create clip for backyard and event 1623786199.292127-toq1la. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for backyard and event 1623786208.942456-rdnu7k. There were no cache files for this event.
```

**Frigate stats**
```json
{
  "cameras": {
    "backyard": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 50
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -y -hide_banner -loglevel info -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:Slackwareroot0@192.168.1.21:554/h264Preview_01_main -r 10 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "fps": 10,
      "frame_shape": [
        1920,
        2560
      ],
      "height": 1920,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 320,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "backyard",
      "objects": {
        "filters": {
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": null,
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 2560,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral_pci": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate-main",
    "host": "192.168.1.1",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "master"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
Input #0, rtsp, from 'rtsp://admin:Pass@192.168.1.21:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 2560x1920, 30 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

**Screenshots**

**Computer Hardware**
 - OS: Debian 10
 - Install method: Addon
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-420-5MP
 - Resolution: Main Stream: 2560x1920 SubStream: 640x480
 - FPS: Main - 30, Sub -10

**Additional context**
