### ISSUE TITLE
Feature request: Docker: Run as a non-root user

### ISSUE THREAD

**Issue by progman32** [blakeblackshear/frigate#1233]
The [docs](https://blakeblackshear.github.io/frigate/installation) suggest running the frigate docker container in privileged mode (presumably for access to Coral devices). This isn't a problem per se, but since the official container runs everything as root, everything from ffmpeg to python also runs effectively as root on the host system, since [privileged containers are not sandboxed from the host](https://phoenixnap.com/kb/docker-privileged).

It should be possible to at least run ffmpeg as a non-root user, though the media folder needs to be correctly permissioned. 

Once I get a coral I might poke at this, but before I do: has this been explored before?

**Comment by blakeblackshear** [comment]
I have tried countless times. I can never get Coral and hwaccel for ffmpeg to work reliability without it. You are more than welcome to give it another try.

**Comment by progman32** [comment]
Thanks! Good to know it's been attempted. I'll take it to the Discussions tab if I pick this up.

**Comment by ElMoribond** [comment]
I'm running Frigate with no problem with these snippets of configurations:

### config.yml
```
ffmpeg:
  global_args: -hide_banner -loglevel info
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb
```

### docker-compose.yml
```
    #privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    - /dev/dri:/dev/dri
```

I think it's for tmpfs.
Personally, all my containers go up tmp like this:

```
    volumes:
    - /tmp/docker/frigate:/tmp/cache
```

Because the /tmp of my host is already in memory via /etc/fstab.

**Comment by highaltidude** [comment]
Without privileged it never found my Coral. I didn't need to add this to my compose file until I installed the Coral.

**Comment by ElMoribond** [comment]
I said something stupid, privilege is necessary. :neckbeard:

**Comment by tunip** [comment]
privileged  is really necessary? I use this to run Frigate and it works fine:
```
  frigate:
    container_name: frigate
    restart: unless-stopped
    shm_size: '512m'
    image: blakeblackshear/frigate:0.8.4-amd64
    volumes:
      - frigate:/config
      - frigate_media:/media/frigate
      - /mnt/ssd/recordings:/media/frigate/recordings
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    environment:
      - TZ=Europe/Berlin
      - HOME=/config
```

Until the new web-ui I was able to run the container as non-root user. Since nginx is part of the container it is more difficult. But the nginx worker process (web-ui) is running as non-root user, which is fine for me.
