### ISSUE TITLE
Detected object incorrectly shown as having entered a zone, wrongly triggering a burglar alarm

### ISSUE THREAD

**Issue by mdelecate** [blakeblackshear/frigate#1246]
**Describe the bug**
Occasionally, an event is recorded where a detected object is marked as having entered a defined zone, when in fact it had never entered the zone. With hundreds of events per day, I have only noticed a handful of examples over several weeks across different cameras & zones, so it is reoccurring, albeit rarely. 
Details of most recent example below. 

**Version of frigate**
Frigate NVR Add-On 1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: username
  password: password
  stats_interval: 60

cameras:
  Pool:
    ffmpeg:
      inputs:
        - path: rtsp://user:passw@192.168.3.51:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 5
    best_image_timeout: 15
    zones:
      zone_garden_front:
        coordinates: 2551,2160,2763,2074,3135,1849,2702,1203,2511,1298,2566,1440,2520,1532,2200,1698,2102,1612,1969,1668,1812,1705,1680,1628,1683,2160
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True

  GardenFront:
    ffmpeg:
      inputs:
        - path: rtsp://user:passw@192.168.3.54:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 5
    best_image_timeout: 15
    zones:
      zone_garden_front:
        coordinates: 3209,855,3840,862,3840,2160,2191,2160,1720,1714,1212,1569,1335,1382,1465,1295,1591,957,1434,812,1458,634,1751,591,3151,591
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    
  GardenTop:
    ffmpeg:
      inputs:
        - path: rtsp://user:passw@192.168.3.52:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 5
    best_image_timeout: 15
    zones:
      zone_garden_back:
        coordinates: 3437,748,2988,363,2603,172,2594,652,2462,671,2218,1000,2228,1092,3172,1446
      zone_garden_back_boundary:
        coordinates: 2732,132,2554,111,2228,0,2237,120,2545,400,2585,129,2751,163,3092,425,3437,717,3566,800,3763,631
      zone_garden_top:
        coordinates: 28,532,437,308,458,154,637,68,1437,31,2083,892,2018,1108,3449,1726,3714,1037,3778,1406,3806,2123,31,2123
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    objects:
      filters:
        umbrella:
          threshold: 0.8

  BackFence:
    ffmpeg:
      inputs:
        - path: rtsp://user:passw@192.168.3.55:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 5
    best_image_timeout: 15
    zones:
      zone_garden_back:
        coordinates: 0,2160,0,1652,588,1625,831,1314,594,1083,1203,818,1809,643,1778,1225,2025,1529,2320,1397,2794,1455,2945,1077,3840,1348,3840,2160
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      
  RoofLeft:
    ffmpeg:
      inputs:
        - path: rtsp://user:passw@192.168.3.56:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 5
    best_image_timeout: 15
    zones:
      zone_roof_left:
        coordinates: 0,1167,492,1280,989,1113,1720,914,2218,723,2591,766,3702,972,3840,1169,3840,2160,0,2160
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True  
    objects: 
      filters:
        person:
          mask:
            - 2908,1218,2803,1188,2849,945,2945,960
        bird:
          mask:
            - 1923,255,1905,409,1788,391,1797,237
      
  RoofRight:
    ffmpeg:
      inputs:
        - path: rtsp://user:passw@192.168.3.53:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 5
    best_image_timeout: 15
    zones:
      zone_roof_right:
        coordinates: 0,2160,3840,2160,3840,212,3665,265,3520,966,3334,1017,3345,483,2914,415,2846,874,1892,689,1012,975,766,911,729,1009,0,1280
    objects:
      filters:
        person:
          mask:
            - 1800,1271,1520,1255,1489,1618,1788,1649
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True

objects:
  # list of objects to track from labelmap.txt
  track:
    - person
    - bird
    - umbrella
    - dog
    - cat
    - backpack
  filters:
    umbrella:
      threshold: 0.78


clips: 
  retain:
    # Required: Default retention days (default: 10)
    default: 10

snapshots: 
  retain: 
    # Required: Default retention days (default: 10)
    default: 10
```

**Frigate stats**
```json
{
  "BackFence": {
    "camera_fps": 5.1, 
    "capture_pid": 107, 
    "detection_fps": 9.7, 
    "pid": 51, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "GardenFront": {
    "camera_fps": 5.0, 
    "capture_pid": 101, 
    "detection_fps": 6.4, 
    "pid": 49, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "GardenTop": {
    "camera_fps": 5.0, 
    "capture_pid": 104, 
    "detection_fps": 0.0, 
    "pid": 50, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "Pool": {
    "camera_fps": 5.1, 
    "capture_pid": 98, 
    "detection_fps": 8.7, 
    "pid": 48, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "RoofLeft": {
    "camera_fps": 5.0, 
    "capture_pid": 113, 
    "detection_fps": 0.0, 
    "pid": 73, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "RoofRight": {
    "camera_fps": 5.1, 
    "capture_pid": 116, 
    "detection_fps": 0.0, 
    "pid": 81, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 24.8, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 9.58, 
      "pid": 45
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 8108.4, 
        "mount_type": "tmpfs", 
        "total": 8198.2, 
        "used": 89.8
      }, 
      "/media/frigate/clips": {
        "free": 426815.1, 
        "mount_type": "ext4", 
        "total": 503317.8, 
        "used": 56020.6
      }, 
      "/media/frigate/recordings": {
        "free": 426815.1, 
        "mount_type": "ext4", 
        "total": 503317.8, 
        "used": 56020.6
      }, 
      "/tmp/cache": {
        "free": 7643.7, 
        "mount_type": "tmpfs", 
        "total": 8198.2, 
        "used": 554.6
      }
    }, 
    "uptime": 122821, 
    "version": "0.8.4-5043040"
  }
}
```

**Screenshots**
Defined zone: 
![Screenshot 2021-06-19 at 2 13 48 AM](https://user-images.githubusercontent.com/12543435/122604920-4922cd00-d0a9-11eb-9368-0d1ce2192d41.jpg)

Event list: 
![Screenshot 2021-06-19 at 2 10 50 AM](https://user-images.githubusercontent.com/12543435/122604937-5049db00-d0a9-11eb-8050-a66de8e20d78.jpg)

Event details: 
![Screenshot 2021-06-19 at 2 11 11 AM](https://user-images.githubusercontent.com/12543435/122604943-5344cb80-d0a9-11eb-8925-15648cf77f10.jpg)

Captured video of the event: https://imgur.com/a/zsoIVwv

**Computer Hardware**
 - OS: Home Assistant OS 6.0
 - Install method: Add-on
 - Virtualization: no
 - Coral Version: USB Coral
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: DS-2CD3T87
 - Resolution: 3840 × 2160
 - FPS: 15

**Additional context**
We've had our fair share of burglaries in the past, so I have implemented Frigate as the main trigger for a burglar alarm with six cameras and eight spot- and floodlights around the property. The last incorrectly detected event occurred an hour ago and triggered spotlights aimed at an innocent security guard, walking past, but never entering, a defined zone. Frigate incorrectly showed an entry into the zone. Unfortunately this also triggered loud alerts for everyone sleeping inside the house, giving everyone a nice scare. 

I haven't been able to work out why/when this occurs and have also seen this occur when the detected object is well away from the zone.

**Comment by blakeblackshear** [comment]
My best guess is there was a single frame where a false positive was detected with the bottom center of the bounding box in the zone. The only way to know for sure would be to maintain a log of all messages sent to the `events` mqtt topic. That will show you the exact frame where the tracked object crossed into the zone and other metrics for the bounding box at that time. If that is what happens, the best bet is to use filters to define a max_area for the person object and any "persons" too large will be flagged as false positives and filtered out.

**Comment by mdelecate** [comment]
Thanks for the suggestions! I've now enabled MQTT logging and have installed MQTT Explorer for good measure as well, will observe everything and possibly follow up with a max_area filter if necessary.

**Comment by adampetrovic** [comment]
This has happened to me a few times as well and every single time it's because the bounding box encroaches on the marked zone (but not the person). In my example below, you can see the box encroach on the balcony which trips my front_balcony zone.

![image](https://user-images.githubusercontent.com/88030/122665868-37e2d900-d1ed-11eb-972f-b2c23df8a0a1.png)

**Comment by blakeblackshear** [comment]
All that matters is the location of the bottom center of the bounding box.

**Comment by mdelecate** [comment]
I managed to capture another case today, this time with logging enabled. The detected person is clearly outside the defined zone, but marked as having entered that zone. The area of the detection remains within a reasonable range. 
For some reason, the location jumps to the opposite corner of the frame with the third event update, putting it inside the zone. 

Here's the zone: 
```
zone_garden_front:
  coordinates: 3209,855,3840,862,3840,2160,2490,1923,1476,1490,1737,691,3159,716
```
<img width="512" alt="zone_garden_front" src="https://user-images.githubusercontent.com/12543435/124004003-2b8b2700-da0a-11eb-9821-011da2734949.png">

Event info:
<img width="739" alt="event-info" src="https://user-images.githubusercontent.com/12543435/124004388-8886dd00-da0a-11eb-8c64-f3771a2f3166.png">

Snapshot of the event:
![GardenFront-1625018285 55039-qaem2a](https://user-images.githubusercontent.com/12543435/124004478-a18f8e00-da0a-11eb-8d31-2ccfb93d4b76.jpg)

Video clip of the event:
https://imgur.com/nCufcY1

All logs of event id 1625018285.55039-qaem2a:
```
2021-06-30 09:58:07 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on frigate/events: b'{"before": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018285.55039, "label": "person", "top_score": 0.0, "false_positive": true, "start_time": 1625018285.55039, "end_time": null, "score": 0.5859375, "box": [946, 639, 1095, 778], "area": 20711, "region": [870, 582, 1170, 882], "current_zones": [], "entered_zones": [], "thumbnail": null}, "after": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018286.084545, "label": "person", "top_score": 0.720703125, "false_positive": false, "start_time": 1625018285.55039, "end_time": null, "score": 0.796875, "box": [894, 638, 1101, 775], "area": 28359, "region": [858, 570, 1158, 870], "current_zones": [], "entered_zones": [], "thumbnail": null}, "type": "new"}'

2021-06-30 09:58:12 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on frigate/events: b'{"before": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018286.084545, "label": "person", "top_score": 0.720703125, "false_positive": false, "start_time": 1625018285.55039, "end_time": null, "score": 0.796875, "box": [894, 638, 1101, 775], "area": 28359, "region": [858, 570, 1158, 870], "current_zones": [], "entered_zones": [], "thumbnail": null}, "after": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018290.745701, "label": "person", "top_score": 0.736328125, "false_positive": false, "start_time": 1625018285.55039, "end_time": null, "score": 0.546875, "box": [571, 1024, 777, 1145], "area": 24926, "region": [543, 890, 843, 1190], "current_zones": [], "entered_zones": [], "thumbnail": null}, "type": "update"}'

2021-06-30 09:58:18 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on frigate/events: b'{"before": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018290.745701, "label": "person", "top_score": 0.736328125, "false_positive": false, "start_time": 1625018285.55039, "end_time": null, "score": 0.546875, "box": [571, 1024, 777, 1145], "area": 24926, "region": [543, 890, 843, 1190], "current_zones": [], "entered_zones": [], "thumbnail": null}, "after": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018296.246617, "label": "person", "top_score": 0.736328125, "false_positive": false, "start_time": 1625018285.55039, "end_time": null, "score": 0.5234375, "box": [3048, 1847, 3133, 2009], "area": 13770, "region": [2928, 1787, 3300, 2159], "current_zones": ["zone_garden_front"], "entered_zones": ["zone_garden_front"], "thumbnail": null}, "type": "update"}'

2021-06-30 09:58:27 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on frigate/events: b'{"before": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018296.246617, "label": "person", "top_score": 0.736328125, "false_positive": false, "start_time": 1625018285.55039, "end_time": null, "score": 0.5234375, "box": [3048, 1847, 3133, 2009], "area": 13770, "region": [2928, 1787, 3300, 2159], "current_zones": ["zone_garden_front"], "entered_zones": ["zone_garden_front"], "thumbnail": null}, "after": {"id": "1625018285.55039-qaem2a", "camera": "GardenFront", "frame_time": 1625018296.246617, "label": "person", "top_score": 0.736328125, "false_positive": false, "start_time": 1625018285.55039, "end_time": 1625018307.06167, "score": 0.5234375, "box": [3048, 1847, 3133, 2009], "area": 13770, "region": [2928, 1787, 3300, 2159], "current_zones": ["zone_garden_front"], "entered_zones": ["zone_garden_front"], "thumbnail": null}, "type": "end"}'
```

Camera configuration: 
```
  GardenFront:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Camdash8@192.168.8.54:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - clips
    width: 3840
    height: 2160
    fps: 6
    best_image_timeout: 15
    zones:
      zone_garden_front:
        coordinates: 3209,855,3840,862,3840,2160,2490,1923,1476,1490,1737,691,3159,716
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    objects:
      filters:
        dog: 
          min_area: 6000
          max_area: 70000
        person:
          min_area: 6000
          max_area: 70000
        umbrella: 
          min_area: 6000
          max_area: 70000
          mask:
            - 1015,295,1391,680,3234,640,3178,351,2606,360,2498,0
            - 975,1551,2988,2055,3037,1772,2582,1711,2431,1452,1662,1320,1129,1372
            - 1538,788,1652,849,1637,1006,1520,1000,1418,889
```
