### ISSUE TITLE
Support for dynamic ONVIF user and password configuration

### ISSUE THREAD

**Issue by jake1164** [blakeblackshear/frigate#12514]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to replace the password and username for the onvif user and password with external secrets like the MQTT user/password or the ffmpeg input path.

```
  garage_driveway:
    enabled: true
    ffmpeg:
      inputs:
      - path: rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.1.x:554/Preview_01_main
        roles:
        - record
      - path: rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.1.x:554/Preview_01_sub
        roles:
        - detect    
    onvif:
      host: 192.168.1.x
      port: 8000
      user: "{FRIGATE_CAMERA_USERNAME}"
      password: "FRIGATE_CAMERA_PASSWORD"
```

This will also require the full [reference ](https://docs.frigate.video/configuration/reference) to be updated to indicate the fields are supported for environmental variable or docker secret replacement.
