### ISSUE TITLE
Errors when setting FPS filter for Nvidia

### ISSUE THREAD

**Issue by jonathanchin** [blakeblackshear/frigate#1252]
**Describe the bug**
I have Nvidia decoding set up and ffmpeg processes running. However when I add output args to set ffmpeg to skip frames, ffmpeg no longer runs and I get a green image. Here are the offending lines:
```
  output_args:
    detect: -filter:v fps=5
```

**Version of frigate**
0.8.2-31d408a

**Config file**
```yaml
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@frontdoor:8554/unicast
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    clips:
      enabled: True
      pre_capture: 3
      post_capture: 3
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
clips:
  max_seconds: 300
  retain:
    default: 14
ffmpeg:
  input_args:
    - -c:v
    - h264_cuvid
  output_args:
    detect: -filter:v fps=5
objects:
  track:
    - person
    - car
```

**Frigate container logs**
```
frigate_1         | frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate_1         | frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
frigate_1         | ffmpeg.frontdoor.detect           ERROR   : [NULL @ 0x56500f67c4c0] Unable to find a suitable output format for 'pipe:'
frigate_1         | ffmpeg.frontdoor.detect           ERROR   : pipe:: Invalid argument
frigate_1         | frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate_1         | frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
```

**Frigate stats**
```json
{
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 10.0, 
      "pid": 42
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 10.0, 
      "pid": 43
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1073.5, 
        "mount_type": "tmpfs", 
        "total": 1073.7, 
        "used": 0.3
      }, 
      "/media/frigate/clips": {
        "free": 124375.3, 
        "mount_type": "ext4", 
        "total": 155923.8, 
        "used": 23556.6
      }, 
      "/media/frigate/recordings": {
        "free": 124375.3, 
        "mount_type": "ext4", 
        "total": 155923.8, 
        "used": 23556.6
      }, 
      "/tmp/cache": {
        "free": 1073.7, 
        "mount_type": "tmpfs", 
        "total": 1073.7, 
        "used": 0.0
      }
    }, 
    "uptime": 190, 
    "version": "0.8.2-31d408a"
  }, 
  "frontdoor": {
    "camera_fps": 0.0, 
    "capture_pid": 48, 
    "detection_fps": 0.0, 
    "pid": 47, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }
}
```

**FFprobe from your camera**

```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://username:password@frontdoor:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 1.309978, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 25 fps, 20 tbr, 90k tbn, 50 tbc
```

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Docker Compose
 - Virtualization: none
 - Coral Version: none
 - Network Setup: WiFi

**Camera Info:**
 - Manufacturer: Xiaomi
 - Model: Dafang
 - Resolution: 1080p
 - FPS: 25
