### ISSUE TITLE
Camera stream rotated when displaying through Nabu Casa / Google Home

### ISSUE THREAD

**Issue by mcarson75** [blakeblackshear/frigate#1259]
**Describe the bug**
When an Amcrest IP5M-T1179EW camera is streamed to a Google Home device, it is rotated 90° to the right.  All show correctly in Home Assistant and the Frigate GUI.  My Amcrest AD110 doorbell camera shows correctly (not rotated) on Google Home.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: ha.<domain>
  port: 1883
  user: <user>
  password: <pass>
  topic_prefix: frigate
#motion:
#  threshold: 5
#  contour_area: 50
#  frame_height: 500
detectors:
  coral:
    type: edgetpu
    device: pci
cameras:
####################################################################################
  Backyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<user>:<pass>@cam-backyard.<domain>:554/cam/realmonitor?channel=1&subtype=0
          global_args: -hide_banner -loglevel info
          roles:
            - clips
            - rtmp
        - path: rtsp://<user>:<pass>@cam-backyard.<domain>:554/cam/realmonitor?channel=1&subtype=1
          global_args: -hide_banner -loglevel info
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        rtmp: '-c copy -f flv'
    width: 704
    height: 480
    fps: 10
    motion:
      mask:
        - 704,0,704,171,503,74,346,55,347,77,230,80,227,59,96,74,99,0
    zones:
      parking:
        coordinates: 100,179,478,141,465,142,489,130,312,60,99,84
      porch:
        coordinates: 144,480,469,480,573,406,322,175,91,217,104,324
      outside:
        coordinates: 131,480,704,480,704,174,414,42,91,52,99,230
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      filters:
        car:
          mask:
            - 704,0,704,171,503,74,346,55,347,77,230,80,227,59,96,74,99,0
            - 374,883,646,825,562,523,355,555
      track:
        - person
        - cat
        - dog
        - car    
####################################################################################
  Back_Porch:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<user>:<pass>@cam-backporch.<domain>:554/cam/realmonitor?channel=1&subtype=0
          global_args: -hide_banner -loglevel info
          roles:
            - clips
            - rtmp
        - path: rtsp://<user>:<pass>@cam-backporch.<domain>:554/cam/realmonitor?channel=1&subtype=1
          global_args: -hide_banner -loglevel info
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        rtmp: '-c copy -f flv'
    width: 704
    height: 480
    fps: 10
    motion:
      mask:
        - 382,39,217,59,219,0,704,0,704,113,528,60
    zones:
      parking:
        coordinates: 547,480,650,252,403,160,224,103,83,159,0,203,0,480
      porch:
        coordinates: 683,170,704,123,595,88,550,109
      outside:
        coordinates: 0,480,553,480,610,398,672,258,704,108,561,53,355,30,0,146
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      filters:
        car:
          mask:
            - 0,0,0,197,168,120,236,106,290,126,704,274,704,0
      track:
        - person
        - cat
        - dog
        - car    
####################################################################################
  Driveway:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<user>:<pass>@cam-driveway.<domain>:554/cam/realmonitor?channel=1&subtype=0
          global_args: -hide_banner -loglevel info
          roles:
            - clips
            - rtmp
        - path: rtsp://<user>:<pass>@cam-driveway.<domain>:554/cam/realmonitor?channel=1&subtype=1
          global_args: -hide_banner -loglevel info
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        rtmp: '-c copy -f flv'
    width: 704
    height: 480
    fps: 10
    motion:
      mask:
        - 204,33,704,277,704,0,0,0,0,66
    zones:
      parking:
        coordinates: 153,196,442,480,704,480,704,410,509,275,135,62,107,32,53,42
      outside:
        coordinates: 124,480,704,480,704,293,490,159,189,28,21,68,32,249
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      filters:
        car:
          mask:
#            - 2592,0,2592,118,2592,1140,2294,934,1944,714,259,175,1482,517,1201,408,1268,315,1384,228,1305,183,1263,204,1183,267,1103,279,1003,290,848,267,777,234,697,189,573,115,0,221,0,0
            - 204,33,704,277,704,0,0,0,0,66
      track:
        - person
        - cat
        - dog
        - car    
####################################################################################
  Garage:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<user>:<pass>@cam-garage.<domain>:554/cam/realmonitor?channel=1&subtype=0
          global_args: -hide_banner -loglevel info
          roles:
            - clips
            - rtmp
        - path: rtsp://<user>:<pass>@cam-garage.<domain>:554/cam/realmonitor?channel=1&subtype=1
          global_args: -hide_banner -loglevel info
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        rtmp: '-c copy -f flv'
    width: 704
    height: 480
    fps: 10
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      track:
        - person
        - cat
        - dog
        - car    
####################################################################################
  Front_Yard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<user>:<pass>@cam-frontyard.<domain>:554/cam/realmonitor?channel=1&subtype=0
          global_args: -hide_banner -loglevel info
          roles:
            - clips
            - rtmp
        - path: rtsp://<user>:<pass>@cam-frontyard.<domain>:554/cam/realmonitor?channel=1&subtype=1
          global_args: -hide_banner -loglevel info
          roles:
            - detect
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        rtmp: '-c copy -f flv'
    width: 704
    height: 480
    fps: 10
    motion:
      mask:
        - 283,73,485,67,704,107,704,0,0,0,0,153
    zones:
      parking:
        coordinates: 284,66,680,116,670,170,213,89
      outside:
        coordinates: 607,480,661,430,672,109,269,70,0,164,0,480
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      filters:
        car:
          mask:
            - 283,73,485,67,704,107,704,0,0,0,0,153
      track:
        - person
        - cat
        - dog
        - car
####################################################################################
  Doorbell:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://<user>:<pass>@cam-doorbell.<domain>:554/
          global_args: -hide_banner -loglevel info
          roles:
            - clips
            - detect
            - rtmp
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        rtmp: '-c copy -f flv'
    width: 1920
    height: 1080
    fps: 10
    motion:
      mask:
        - 118,660,1920,600,1920,499,114,507
    zones:
      outside:
        coordinates: 1920,1080,1920,632,1734,578,687,593,126,701,82,873,147,1080
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    objects:
      filters:
        car:
          mask:
            - 118,660,1920,600,1920,499,114,507
      track:
        - person
        - cat
        - dog
```

**Frigate container logs**
```
2021-06-21T23:41:52.253200924Z  * Starting nginx nginx
2021-06-21T23:41:52.263043945Z    ...done.
2021-06-21T23:41:53.386874429Z Starting migrations
2021-06-21T23:41:53.386908293Z peewee_migrate                 INFO    : Starting migrations
2021-06-21T23:41:53.391863732Z There is nothing to migrate
2021-06-21T23:41:53.391897933Z peewee_migrate                 INFO    : There is nothing to migrate
2021-06-21T23:41:53.415168745Z frigate.mqtt                   INFO    : MQTT connected
2021-06-21T23:41:53.434400378Z detector.coral                 INFO    : Starting detection process: 34
2021-06-21T23:41:53.482429062Z frigate.app                    INFO    : Camera processor started for Backyard: 37
2021-06-21T23:41:53.493062191Z frigate.edgetpu                INFO    : Attempting to load TPU as pci
2021-06-21T23:41:53.493450762Z frigate.edgetpu                INFO    : TPU found
2021-06-21T23:41:53.493798479Z frigate.app                    INFO    : Camera processor started for Back_Porch: 38
2021-06-21T23:41:53.494041111Z frigate.app                    INFO    : Camera processor started for Driveway: 39
2021-06-21T23:41:53.494217096Z frigate.app                    INFO    : Camera processor started for Garage: 40
2021-06-21T23:41:53.494423011Z frigate.app                    INFO    : Camera processor started for Front_Yard: 42
2021-06-21T23:41:53.494647678Z frigate.app                    INFO    : Camera processor started for Doorbell: 44
2021-06-21T23:41:53.494961247Z frigate.app                    INFO    : Capture process started for Backyard: 49
2021-06-21T23:41:53.495305119Z frigate.app                    INFO    : Capture process started for Back_Porch: 57
2021-06-21T23:41:53.501616997Z frigate.app                    INFO    : Capture process started for Driveway: 62
2021-06-21T23:41:53.507695241Z frigate.app                    INFO    : Capture process started for Garage: 65
2021-06-21T23:41:53.514388386Z frigate.app                    INFO    : Capture process started for Front_Yard: 69
2021-06-21T23:41:53.532311382Z frigate.app                    INFO    : Capture process started for Doorbell: 72
2021-06-21T23:42:08.971343743Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5611cb37e140] moov atom not found
2021-06-21T23:42:08.971383631Z /tmp/cache/Doorbell-20210621194140.mp4: Invalid data found when processing input
2021-06-21T23:42:08.974474029Z frigate.events                 INFO    : bad file: Doorbell-20210621194140.mp4
2021-06-21T23:42:09.779664438Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x562e38c58140] moov atom not found
2021-06-21T23:42:09.779770761Z /tmp/cache/Back_Porch-20210621194149.mp4: Invalid data found when processing input
2021-06-21T23:42:09.782850196Z frigate.events                 INFO    : bad file: Back_Porch-20210621194149.mp4
2021-06-21T23:42:12.302184683Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d313827140] moov atom not found
2021-06-21T23:42:12.302221858Z /tmp/cache/Backyard-20210621194150.mp4: Invalid data found when processing input
2021-06-21T23:42:12.305394072Z frigate.events                 INFO    : bad file: Backyard-20210621194150.mp4
2021-06-21T23:42:13.660431385Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x563a19c7b140] moov atom not found
2021-06-21T23:42:13.660476076Z /tmp/cache/Front_Yard-20210621194150.mp4: Invalid data found when processing input
2021-06-21T23:42:13.670527227Z frigate.events                 INFO    : bad file: Front_Yard-20210621194150.mp4
2021-06-21T23:42:19.679786864Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5582f8c62140] moov atom not found
2021-06-21T23:42:19.679898252Z /tmp/cache/Garage-20210621194148.mp4: Invalid data found when processing input
2021-06-21T23:42:19.683277525Z frigate.events                 INFO    : bad file: Garage-20210621194148.mp4
2021-06-21T23:42:21.837449995Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55df93040140] moov atom not found
2021-06-21T23:42:21.837479229Z /tmp/cache/Driveway-20210621194148.mp4: Invalid data found when processing input
2021-06-21T23:42:21.839560339Z frigate.events                 INFO    : bad file: Driveway-20210621194148.mp4
```

**Frigate stats**
```json
{
  "Back_Porch": {
    "camera_fps": 10.1, 
    "capture_pid": 57, 
    "detection_fps": 0.0, 
    "pid": 38, 
    "process_fps": 10.1, 
    "skipped_fps": 0.0
  }, 
  "Backyard": {
    "camera_fps": 10.1, 
    "capture_pid": 49, 
    "detection_fps": 0.0, 
    "pid": 37, 
    "process_fps": 10.1, 
    "skipped_fps": 0.0
  }, 
  "Doorbell": {
    "camera_fps": 10.0, 
    "capture_pid": 72, 
    "detection_fps": 28.1, 
    "pid": 44, 
    "process_fps": 9.9, 
    "skipped_fps": 0.0
  }, 
  "Driveway": {
    "camera_fps": 10.0, 
    "capture_pid": 62, 
    "detection_fps": 0.0, 
    "pid": 39, 
    "process_fps": 10.0, 
    "skipped_fps": 0.0
  }, 
  "Front_Yard": {
    "camera_fps": 10.1, 
    "capture_pid": 69, 
    "detection_fps": 0.0, 
    "pid": 42, 
    "process_fps": 10.1, 
    "skipped_fps": 0.0
  }, 
  "Garage": {
    "camera_fps": 10.0, 
    "capture_pid": 65, 
    "detection_fps": 0.0, 
    "pid": 40, 
    "process_fps": 10.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 28.1, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 8.15, 
      "pid": 34
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 4283.8, 
        "mount_type": "tmpfs", 
        "total": 4295.0, 
        "used": 11.1
      }, 
      "/media/frigate/clips": {
        "free": 797421.6, 
        "mount_type": "ext4", 
        "total": 983433.6, 
        "used": 135985.0
      }, 
      "/media/frigate/recordings": {
        "free": 797421.6, 
        "mount_type": "ext4", 
        "total": 983433.6, 
        "used": 135985.0
      }, 
      "/tmp/cache": {
        "free": 215959.3, 
        "mount_type": "ext4", 
        "total": 244529.7, 
        "used": 16077.5
      }
    }, 
    "uptime": 1360, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x5595eaacbf00] max delay reached. need to consume packet
[rtsp @ 0x5595eaacbf00] RTP: missed 42 packets
[h264 @ 0x5595eaad1480] error while decoding MB 85 82, bytestream -9
[h264 @ 0x5595eaad1480] concealing 6444 DC, 6444 AC, 6444 MV errors in P frame
[rtsp @ 0x5595eaacbf00] max delay reached. need to consume packet
[rtsp @ 0x5595eaacbf00] RTP: missed 2 packets
[h264 @ 0x5595eaad1480] error while decoding MB 36 113, bytestream -7
[h264 @ 0x5595eaad1480] concealing 1471 DC, 1471 AC, 1471 MV errors in P frame
[rtsp @ 0x5595eaacbf00] max delay reached. need to consume packet
[rtsp @ 0x5595eaacbf00] RTP: missed 47 packets
Input #0, rtsp, from 'rtsp://<user>:<pass>@cam-driveway.<domain>:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.084000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2592x1944, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54790846/122843331-34268380-d2cd-11eb-92ce-9e02b6a385e6.png)

**Computer Hardware**
 - OS: Ubuntu 20.04
 - Install method: Docker Compose
 - Virtualization: N/A
 - Coral Version: PCIe
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Amcrest
 - Model: IP5M-1179EW
 - Resolution: 2592x1944
 - FPS: 20

**Additional context**
I have added an nginx reverse proxy / LetsEncrypt to serve TLS for Frigate.
