### ISSUE TITLE
Cat(or objects other than person) is not detected

### ISSUE THREAD

**Issue by t0ny-peng** [blakeblackshear/frigate#1262]
**Describe the bug**

I have a camera pointing at the cat water fountain. However, when the cat enters the camera field, it's not detected as an object. In the camera page, the only available tracked object is person, which leads to an empty event history.

Person detection works well in other camera though.

<img width="1332" alt="Screen Shot 2021-06-22 at 3 56 33 PM" src="https://user-images.githubusercontent.com/4816327/122990961-7f46a200-d372-11eb-9e3c-a15319109fc7.png">

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: REDACTED
  user: "REDACTED"
  password: "REDACTED"

cameras:
  cat:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.159/ch0_0.h264
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      retain:
        default: 1
        objects:
          person: 2
          cat: 7

detectors:
  cpu1:
    type: cpu

```

**Frigate container logs**
```
Nothing special when the cat enter the camera field
```

**Frigate stats**
```json
{
  "cat": {
    "camera_fps": 5.1, 
    "capture_pid": 39, 
    "detection_fps": 0.0, 
    "pid": 37, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 199.3, 
      "pid": 33
    }
  }, 
  "living-room": {
    "camera_fps": 5.0, 
    "capture_pid": 38, 
    "detection_fps": 0.0, 
    "pid": 36, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 63.4, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 3.8
      }, 
      "/media/frigate/clips": {
        "free": 17580.9, 
        "mount_type": "ext4", 
        "total": 33683.2, 
        "used": 14367.6
      }, 
      "/media/frigate/recordings": {
        "free": 17580.9, 
        "mount_type": "ext4", 
        "total": 33683.2, 
        "used": 14367.6
      }, 
      "/tmp/cache": {
        "free": 985.0, 
        "mount_type": "tmpfs", 
        "total": 1000.0, 
        "used": 15.0
      }
    }, 
    "uptime": 123, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
root@8feb8bcd7764:/opt/frigate# ffprobe rtsp://10.0.0.222/ch0_0.h264
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55f124785b80] CSeq 4 expected, 0 received.
Input #0, rtsp, from 'rtsp://10.0.0.222/ch0_0.h264':
  Metadata:
    title           : Session streamed by "rtspv4"
    comment         : ch0_0.h264
  Duration: N/A, start: 0.050000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 1280x720, 20 fps, 20 tbr, 90k tbn, 180k tbc
```

**Screenshots**

**Computer Hardware**
 - OS: Ubuntu
 - Install method: `docker-compose`
 - Virtualization: ESXi
 - Coral Version: None
 - Network Setup: Frigate wired + Camera Wi-Fi

**Camera Info:**
 - Manufacturer: Yi 
 - Model: Yi Home 720P
 - Resolution: 1280*720P
 - FPS: 5

**Additional context**
