### ISSUE TITLE
Reolink RL-410W has a green screen

### ISSUE THREAD

**Issue by Kate222** [blakeblackshear/frigate#1263]
Reolink RL-410W now has a green screen showing in Frigate NVR.
I have not changed anything in yml file, however, I have done an Home Assistant core update recently. The green screen appears after that. 
I use Raspberry pi 4b, with home assistant. 

Camera yml file:

```yaml
cameras:
  driveway:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
      inputs:
        - path: rtmp://ipaddress/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
            - rtmp
            - clips
            - record
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      required_zones: []
      retain:
        default: 10
        objects:
          person: 5
          car: 5
          cat: 5
          dog: 5
          horse: 5
          truck: 5
          bicycle: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 5
          car: 5
          cat: 5
          dog: 5
          horse: 5
          truck: 5
          bicycle: 5
    record:
      enabled: False
      retain_days: 5
    width: 640
    height: 352
    fps: 4
```

Log error:

```
ffmpeg.driveway.detect         ERROR   : [tcp @ 0x55a958cc50] Connection to tcp://ipaddress:1935 failed: Connection refused
ffmpeg.driveway.detect         ERROR   : [rtmp @ 0x55a958c780] Cannot open connection tcp://192.168.1.10:1935
ffmpeg.driveway.detect         ERROR   : rtmp://ipaddress/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx: Connection refused
frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
```

Could you please help?
Many thanks
Kate
