### ISSUE TITLE
Reolink RLC-410-5MP: ffmpeg option rw_timeout not found, green image (otherwise works, but distorted image)

### ISSUE THREAD

**Issue by prankousky** [blakeblackshear/frigate#1268]
Hi everybody,

I recently received my coral and got excited to get started with frigate. I have currently two cameras connected; the cheap no name China camera works fine, but my Reolink RLC-410-5MP does not! 

# Camera

* Reolink RLC-410-5MP
* Firmware
  * build 20121100
  * IPC_51516M5M
  * v3.0.0.136_20121100
  * connection: PoE+ (no WiFi)
 
* Stream
  * Resolution `2304x1296` (but I have tested **all** resolution that the camera offers, same issue)
  * FPS `12` (tried 5, 12, 30 - changing it both in the camera settings **and** in the frigate configuration)
  * Bitrate `2048` (tried all other sorts as well, higher and lower)
 
# Frigate Server

* Linux raspberrypi 5.10.17-v7l+
* 32bit (right? `uname -m` outputs `armv7l`)

# docker-compose.yaml

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config:ro
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 4000000000
          # size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "12345"

```

# Frigate Configuration

```
mqtt:
  host: <ip>
  port: 1883
  topic_prefix: frigate
  client_id: frigate_pi222
  user: mqttuser
  password: mqttpw
cameras:
  einfahrt:
    objects:
      track:
        - person
    motion:
      mask:
        - 0,1536,772,1536,765,1425,0,1431
    zones:
      zone_einfahrt:
        coordinates: 2026,607,1639,1536,0,1536,0,188,450,102,1102,138
    detect:
      enabled: True
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://frigate:frigate@192.168.100.96:554/h264Preview_01_main
          roles:
            - detect
    width: 2304
    height: 1296
    fps: 12
  vorgarten02:
    objects:
      track:
        - person
    zones:
      zone_vorgarten2:
        coordinates: 0,720,0,300,658,77,938,115,717,720
    motion:
      mask:
        - 557,0,993,0,942,88,559,74,0,293,0,0
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_mmal
      inputs:
        - path: rtsp://frigate:frigate@192.168.100.128:554/live/ch0
          roles:
            - detect
    width: 1280
    height: 720
    fps: 5
detectors:
  coral:
    type: edgetpu
    device: usb
  cpu1:
    type: cpu
```

With the current configuration, I will get the output below and **only** a green image. However, when I comment out everything starting at `rw_timeout`, it will display some image.

![grafik](https://user-images.githubusercontent.com/11297070/123101737-dfe1e780-d423-11eb-819e-0fc51d6cb27e.png)

```
### the output
frigate.app                    INFO    : Camera processor started for vorgarten02: 39
detector.cpu1                  INFO    : Starting detection process: 34
frigate.mqtt                   INFO    : MQTT connected
frigate.mqtt                   INFO    : Turning on snapshots for einfahrt via mqtt
frigate.app                    INFO    : Capture process started for einfahrt: 40
frigate.app                    INFO    : Capture process started for vorgarten02: 45
frigate.mqtt                   INFO    : Turning on snapshots for vorgarten02 via mqtt
frigate.video                  INFO    : einfahrt: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : einfahrt: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : einfahrt: ffmpeg process is not running. exiting capture thread...
frigate.edgetpu                INFO    : TPU found
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1530620] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1540970] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1551600] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1561960] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : Option rw_timeout not found.
frigate.video                  INFO    : einfahrt: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : einfahrt: ffmpeg process is not running. exiting capture thread...
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1022620] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1032970] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1043600] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : [udp @ 0x1053960] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.einfahrt.detect         ERROR   : Option rw_timeout not found.
frigate.video                  INFO    : einfahrt: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : einfahrt: ffmpeg process is not running. exiting capture thread...

```

When I change my configuration (everything the same, only changed the part below) to this, I get an image. However, the image is always corrupted and not working reliably.

```
### so it'd look like this 
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        # - -rw_timeout
        # - "5000000"
        # - -use_wallclock_as_timestamps
        # - "1"
``` 

The image *currently* looks like this; however, sometimes it will display the full image (no green box), **but** it will be distorted. For example, the timestamp will visibly be moving, but not be identifiable as numbers (just random pixels changing in that area).

![grafik](https://user-images.githubusercontent.com/11297070/123102148-4961f600-d424-11eb-978b-efe257f22a0e.png)

I have created a dedicated user `frigate` on the camera just to see if it made a difference, but it did not.

The raspberry pi running frigate is currently connected via wifi. However, the other camera doesn't cause any problems (that I noticed), so I don't think that this is just up to the pi and/or its connection.

Can you recommend anything that I can try in order to fix this? As a last thought, I tried using `path: rtsp://frigate:frigate@192.168.100.96:554/h264Preview_01_sub` instead (640x480, 10fps, 384 Kbps bitrate). This currently **seems** to work, however, it is very low resolution and not really suitable to use for snapshots trying to identify people that might be detected when I am not home.

Thank you in advance for your ideas :)
