### ISSUE TITLE
Qnap Docker - no route to host. Cannot start

### ISSUE THREAD

**Issue by weaselchops** [blakeblackshear/frigate#1272]
**Describe the bug**
When trying to run  blakeblackshear/frigate:0.9.0-dada764-amd64 (Have tried an earlier version)
I get "No route to host" (MQTT is running and working)
I have other containers connected to this Docker static interface "qnet-static-eth0-adc76b" with no issues!
**Frigate container logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting migrations
[2021-06-23 16:44:32] peewee_migrate                 INFO    : Starting migrations
[2021-06-23 16:44:32] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[2021-06-23 16:44:32] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
[2021-06-23 16:44:32] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 113] No route to host
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting
```

### Docker command
```
docker run --privileged --net=qnet-static-eth0-adc76b  --ip=172.16.1.20   --name frigate   \
--restart=unless-stopped   --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \ 
-v /dev/bus/usb:/dev/bus/usb    -v /share/CACHEDEV1_DATA/Container/Frigate/media/:/media/frigate   -v \ /share/CACHEDEV1_DATA/Container/Frigate/config/config.yml:/config/config.yml:ro   \
-v /etc/localtime:/etc/localtime:ro   -e FRIGATE_RTSP_PASSWORD='password'   -p 5007:5000   -p 1935:1935  \ blakeblackshear/frigate:0.9.0-dada764-amd64
```

### Hack to get it running
Now if I run the image interactively.. I get the same error. Until I run some other network command!??
... **_-it /bin/bash_**

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
root@3f95ae1c1193:/opt/frigate# python3 -u -m frigate
Starting migrations
[2021-06-23 14:25:59] peewee_migrate                 INFO    : Starting migrations
[2021-06-23 14:25:59] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[2021-06-23 14:25:59] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
[2021-06-23 14:25:59] peewee_migrate                 INFO    : There is nothing to migrate
172.16.0.142
[Errno 113] No route to host
**root@3f95ae1c1193:/opt/frigate# apt-get update ## Do some other network thing**
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease
  Temporary failure resolving 'packages.cloud.google.com'
Err:3 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1032 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [395 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1343 kB]
Fetched 2985 kB in 15s (204 kB/s)
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch https://packages.cloud.google.com/apt/dists/coral-edgetpu-stable/InRelease  Temporary failure resolving 'packages.cloud.google.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@3f95ae1c1193:/opt/frigate# python3 -u -m frigate
Starting migrations
[2021-06-23 14:26:28] peewee_migrate                 INFO    : Starting migrations
[2021-06-23 14:26:28] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[2021-06-23 14:26:28] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
[2021-06-23 14:26:28] peewee_migrate                 INFO    : There is nothing to migrate
[2021-06-23 14:26:28] frigate.mqtt                   INFO    : MQTT connected
[2021-06-23 14:26:28] frigate.app                    INFO    : Output process started: 369
[2021-06-23 14:26:28] frigate.app                    INFO    : Camera processor started for back: 371
[2021-06-23 14:26:28] frigate.app                    INFO    : Capture process started for back: 372
[2021-06-23 14:26:28] ws4py                          INFO    : Using epoll
[2021-06-23 14:26:28] detector.coral                 INFO    : Starting detection process: 368
[2021-06-23 14:26:28] ws4py                          INFO    : Using epoll
[2021-06-23 14:26:28] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-06-23 14:26:33] frigate.edgetpu                INFO    : TPU found
[2021-06-23 14:31:28] peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" NOT IN (?))', ['back'])
[2021-06-23 14:31:28] peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" = ?)', ['back'])
[2021-06-23 14:31:28] peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" NOT IN (?))', ['back'])
[2021-06-23 14:31:28] peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" = ?)', ['back'])
[2021-06-23 14:31:28] peewee.sqliteq                 DEBUG   : received query with grouped_events as (
          select id,
            label,
            camera,
                has_snapshot,
                has_clip,
                row_number() over (
              partition by label, camera, round(start_time/5,0)*5
              order by end_time-start_time desc
            ) as copy_number
          from event

**Version of frigate**
Output from `/api/version`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 172.16.1.142
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
 # user: weasel
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
 # password: chops123$
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
logger:
  # Optional: default log level (default: shown below)
  default: debug
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:PASSWORD@172.16.1.114:554/Streaming/Channels/1
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: Qnap 4.5.3.1697
 - Install method: Docker
 - Virtualization: N/A
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
I get the same if I bridge it, rather that use a static IP.
It's probably some QNAP idiosyncrasy...But worth asking 🛩️
