### ISSUE TITLE
Green screen with Reolink E1 pro

### ISSUE THREAD

**Issue by squireblackdens** [blakeblackshear/frigate#1286]
**Describe the bug**
I am trying to connect Frigate to the rtsp stream of a reolink E1 pro camera, but I just get a green screen and errors in the log. I have tested the stream address with VLC and it works fine. I have tried both main and substream.

xxxx=redacted

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.xx.xx
  user: xxxxx
  password: xxxxx

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.xx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - clips
            - record
            - rtmp
    width: 640
    height: 480
    fps: 5
```

**Frigate container logs**
```
FROM STARTUP....

Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.coral INFO : Starting detection process: 74
frigate.app INFO : Camera processor started for back: 77
frigate.app INFO : Capture process started for back: 79
frigate.edgetpu INFO : Attempting to load TPU as usb
frigate.edgetpu INFO : TPU found
frigate.video INFO : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect ERROR : [tcp @ 0x555728e6c6c0] Connection to tcp://192.168.xx.xxx:554?timeout=5000000 failed: Connection timed out

ffmpeg.back.detect ERROR : rtsp://xxx:xxx@192.168.xx.xx:554/h264Preview_01_sub: Connection timed out

frigate.video INFO : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect ERROR : [tcp @ 0x55f55fd416c0] Connection to tcp://192.168.xx.xxx:554?timeout=5000000 failed: Connection timed out


This last section then just repeats.....
```

**Frigate stats**
```json
{
  "back": {
    "camera_fps": 0.0, 
    "capture_pid": 79, 
    "detection_fps": 0.0, 
    "pid": 77, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 10.0, 
      "pid": 74
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 5368.5, 
        "mount_type": "tmpfs", 
        "total": 5368.7, 
        "used": 0.2
      }, 
      "/media/frigate/clips": {
        "free": 2035522.0, 
        "mount_type": "fuse.shfs", 
        "total": 2999127.8, 
        "used": 963605.8
      }, 
      "/media/frigate/recordings": {
        "free": 2035522.0, 
        "mount_type": "fuse.shfs", 
        "total": 2999127.8, 
        "used": 963605.8
      }, 
      "/tmp/cache": {
        "free": 14824.6, 
        "mount_type": "rootfs", 
        "total": 16751.3, 
        "used": 1926.7
      }
    }, 
    "uptime": 228, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
```

**Screenshots**

**Computer Hardware**
 - OS: Unraid
 - Install method: Apps / docker
 - Virtualization: Unraid
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: E1 pro

Main stream | 4MP (2560x1440), 3MP (2304*1296), 1080p, 720p. Max frame rate 20 fps.
Sub stream | 640x480

**Additional context**
As I said, rtsp streams (main and sub) both working fine on VLC. Any help much appreciated!!

**Comment by webbson** [comment]
Hi. 

I think you are running the wrong resolution. The E1 Pro is 640x360 in substream, not 640x480.
![image](https://user-images.githubusercontent.com/1351961/124591659-d7929f00-de5c-11eb-855a-3a3c33dedd67.png)

However even with correct values from settings in Reolink errors came for me, so I opened the stream in VLC and got the resolution there as 640x352.
![image](https://user-images.githubusercontent.com/1351961/124591785-fee96c00-de5c-11eb-8c42-3a19199e3fb8.png)

After using that in my config  my E1 Pro has been working perfectly in Frigate.

**Comment by Borlean** [comment]
Thanks for the help with the resolution. I had to tweak the config a little, but this is what worked for me.
```
  indoor:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.xxx.x.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - clips
            - record
            - rtmp
    detect:
      width: 640
      height: 352
      fps: 5
```

**Comment by gurkburk76** [comment]
I would like to add some info before someone else wastes time on getting this to work, it would seem like the older firmware version for some reason weren't able to communicate accross network segments, i hade to upgrade fw from 2.x to 3.x for this to work.
It's stuff like this that you notice when redoing network at home and stuff... i hope it helps someone! :D

**Comment by viama** [comment]
Another addendum for the Reoloink E1 Pro. I had to change the h264 profile from 'High' to 'Main' in the encoding seddings on the camera for this to work reliably without the occasional corrupted image. Attached is my config
<img width="692" alt="Screenshot 2022-11-14 at 10 45 02" src="https://user-images.githubusercontent.com/24671122/201650970-50b7cd23-6fd5-4556-962e-5ccc3d4e189d.png">

**Comment by Redsandro** [comment]
> Another addendum for the Reoliink E1 Pro. I had to change the h264 profile from 'High' to 'Main' in the encoding seddings on the camera for this to work reliably without the occasional corrupted image.

@viama In the current software version (August 2023) it appears the profile cannot be changed anymore.

![image](https://github.com/blakeblackshear/frigate/assets/1702193/4cbf6302-f45e-4bc0-86b5-b8f4af0d2a8f)
(Screenshot made on "Clear" stream but "Fluent" stream has same parameters.)

**Comment by gkchim** [comment]
please can you share your config, cannot get audio work

**Comment by viama** [comment]
My config has changed a lot since I last posted. I'm now using go2rtc, and a lot of the 'messy' things that used to have to be done are redundant. Here's an extract of my config.yml Audio works fine, and the selection of bitrates etc is no longer critical to the camera working in Frigate

```
go2rtc:
  streams:
    Workshop:
      - rtsp://admin:password@192.168.1.1:554/h264Preview_01_main#audio=aac
    Workshop_sub:
      - rtsp://admin:password@192.168.1.1:554/h264Preview_01_sub

cameras:      
  Workshop:
    ui:
      order: 1
    birdseye:
      order: 1
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Workshop?video=copy&audio=copy
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/Workshop_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
```
