### ISSUE TITLE
Wrong snapshot and score on the snapshot

### ISSUE THREAD

**Issue by ukrolelo** [blakeblackshear/frigate#1300]
**Describe the bug**
My wife was passing by i see her in the clip, but for whatever reason the screenshot was shot for the dryer 5-15seconds after she passed by.

**Version of frigate**
Current version: 1.13  HASS ADDON

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
#MQTT frigate/back/detect/set   ON/OFF to turn on or off tensorflow
database:
  path: /config/frigate.db
  
detectors:
  coral_pci:
    type: edgetpu
    device: pci


    
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    #longloading-record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
    #longloading-clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an

    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for clips streams (default: shown below)
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an


    
mqtt:
  # Required: host name
  host: 192.168.5.6
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: zzz
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: zzzzz
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60


cameras:
  # Required: name of the camera
  CAM0:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
        - path: rtsp://zzzzz
          # Required: list of roles for this stream. valid values are: detect,record,clips,rtmp
          # NOTICE: In addition to assigning the record, clips, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - clips


    # Required: width of the frame for the input with the detect role
    width: 1920
    # Required: height of the frame for the input with the detect role
    height: 1080
    # Optional: desired fps for your camera for the input with the detect role
    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
    #       Frigate will attempt to autodetect if not specified.
    fps: 5



    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: zones for this camera


    # Optional: Camera level detect settings
    motion:
      mask:
        - 595,116,929,63,1211,116,1571,213,1920,341,1920,0,939,0,295,0,0,0,0,585,0,1080,177,1080,59,541,122,258,311,195
        

    zones:
      zone_0:
        coordinates: 1920,1080,1920,362,1640,232,1240,114,1028,81,876,77,476,132,73,258,181,1080
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    # Optional: save clips configuration
    clips:

      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        #objects:
          #person: 15

    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30

    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      #height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        #objects:
          #person: 15

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: False
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []

    # Optional: Camera level object filters config.
    objects:
      track:
        - person
        - cat
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object. 
      # NOTE: This mask is COMBINED with the object type specific mask below
      # mask: 0,0,1000,0,1000,200,0,200
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77
          # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
          # Checks based on the bottom center of the bounding box of the object
          # mask: 0,0,1000,0,1000,200,0,200

  CAM1:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 1634,262,1744,890,1792,1045,1370,1080,963,994,26,982,22,1080,1920,1080,1920,0,343,0,457,226
    zones:
      zone_0:
        coordinates: 0,545,0,955,1266,996,1843,864,1750,156,1240,57,343,24,24,33
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77
  CAM2:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 142,0,1920,0,1920,1051,1587,992,1126,870,1142,746,1209,646,1477,63,673,95,350,126,0,295,0,0
        - 742,221,1061,264,1063,358,752,652,656,602,744,504,886,421,697,380,650,252
    zones:
      zone_0:
        coordinates: 0,1080,955,1080,1920,1080,1124,864,1422,211,874,106,630,118,402,158,0,284
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 1000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77

  CAM3:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 671,106,1221,104,1642,165,1800,1080,1920,1080,1920,0,0,0,0,252
    zones:
      zone_0:
        coordinates: 22,1080,1555,1080,1567,358,1607,256,1575,179,1398,130,992,95,516,130,427,146,350,156,0,266
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77          
          
  CAM4:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 1920,0,0,0,0,1080,652,1080,240,339,654,146,992,100,1920,156
    zones:
      zone_0:
        coordinates: 343,634,490,1080,1205,1080,1920,1080,1920,882,1920,738,1920,219,1920,77,1740,43,1366,26,1043,49,929,67,791,95,638,142,492,171,222,333
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.6
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77          
  CAM5:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 1920,0,0,0,0,490,949,55,1215,67,1447,89,1355,1080,1920,1080
    zones:
      zone_0:
        coordinates: 0,392,0,1080,130,1080,567,1080,912,1080,1325,1080,1433,530,1449,106,1158,71,916,45,445,179
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 1000
          max_area: 100000
          min_score: 0.6
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77          


  CAM6:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 514,59,927,278,1646,644,1920,980,1920,0,589,0,0,0,0,1080,388,1080,219,433,226,106
    zones:
      zone_0:
        coordinates: 234,1080,1028,1080,1406,1080,1681,1080,1920,1080,1920,1002,1800,898,1679,780,1418,549,1126,744,951,819,599,413,807,203,543,61,201,116
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77

  CAM7:

    ffmpeg:
      inputs:
        - path: zzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 1920,0,1920,1080,1687,1080,1774,660,1811,146,1735,108,1402,83,807,171,910,278,278,545,0,671,0,0
    zones:
      zone_0:
        coordinates: 0,1080,1803,1080,1847,473,1805,150,1689,114,1362,79,831,81,388,209,0,408
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 6000
          max_area: 100000
          min_score: 0.6
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.6
          threshold: 0.77

  CAM8:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 1435,100,1866,96,1878,0,1435,0
    zones:
      zone_0:
        coordinates: 1920,0,1920,1080,0,1080,0,110,323,0
    detect:
      enabled: False
      max_disappeared: 25

    clips:
      enabled: False
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: False
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 1000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77

  CAM9:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 890,0,1321,79,1471,89,1607,122,1536,339,1701,413,1920,478,1920,0,0,0,0,98,108,59,563,0
    zones:
      zone_0:
        coordinates: 0,1080,1920,1080,1898,520,1595,362,1601,102,868,0,453,24,108,61,0,95
    detect:
      enabled: False
      max_disappeared: 25

    clips:
      enabled: False
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 14
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: False
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 14
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 1000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
        cat:
          min_area: 1000
          max_area: 40000
          min_score: 0.5
          threshold: 0.77



  doorbell:

    ffmpeg:
      inputs:
        - path: zzzz
          roles:
            - detect
            - clips

    width: 1920
    height: 1080
    fps: 5
    best_image_timeout: 60
    motion:
      mask:
        - 1920,447,1920,0,0,0,0,630
    zones:
      zone_0:
        coordinates: 43,1080,1855,1080,1920,415,0,545
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 7
        #objects:
          #person: 15
    record:
      enabled: False
      retain_days: 30

    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 7
        #objects:
          #person: 15

    mqtt:
      enabled: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 270

    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 10000
          max_area: 100000
          min_score: 0.5
          threshold: 0.77
```

**Screenshots**
https://drive.google.com/drive/folders/1lNypYveFTmWCjO7TYIPU6roUn1zIz5q_?usp=sharing

**Computer Hardware**
 - OS: hass os
 - Install method: [ Addon,]
 - Virtualization: [ Proxmox
 - Coral Version: [PCIe,]
 - Network Setup: [ Wired]

**Camera Info:**
 - Manufacturer: [Dahua]
 - Resolution: [. 1080p]
 - FPS: [ 5]
