### ISSUE TITLE
No EdgeTPU Detected

### ISSUE THREAD

**Issue by liquidbear99** [blakeblackshear/frigate#1303]
**Describe the bug**
Google Coral is not being detected. No EdgeTPU error pccurs when using the following config for my USB coral. My coral is plugged in and my rtsp link works, but the coral is not being recognized.
```
detectors:
  coral:
    type: edgetpu
    device: usb
```

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
# frigate.yml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: secret
  user: secret
  password: secret
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: secret
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
    width: 2560
    height: 1920
    fps: 4
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for front_door: 40
detector.coral                 INFO    : Starting detection process: 38
frigate.app                    INFO    : Capture process started for front_door: 42
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate.app                    INFO    : Stopping...
frigate.object_processing      INFO    : Exiting object processor...
frigate.events                 INFO    : Exiting event cleanup...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.events                 INFO    : Exiting event processor...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.stats                  INFO    : Exiting watchdog...
peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
root                           INFO    : Waiting for detection process to exit gracefully...
```

**Frigate stats**
```json
I don't know how to do this
```

**FFprobe from your camera**

Run the following command and paste output below
```
the rtsp stream is functional
```

**Screenshots**

**Computer Hardware**
 - OS: Home Assistant
 - Install method: Addon
 - Virtualization: None
 - Coral Version: USB
 - Network Setup: Wireless

**Camera Info:**
 - Manufacturer: Reolink
 - Model: 511W
 - Resolution: 2560x1920
 - FPS: 5

**Additional context**
