### ISSUE TITLE
Prioritize RTC over MSE

### ISSUE THREAD

**Issue by bdoiron74** [blakeblackshear/frigate#13058]
**Describe what you are trying to accomplish and why in non technical terms**
Right now with 0.14.0-da913d8 on Windows 11/Chrome, the live video is always MSE. According to the FAQ, this is being done on purpose:

> How can I switch the live view type?
> In Frigate 0.13, a dropdown menu in the UI allowed users to select between jsmpeg, MSE, or WebRTC. In 0.14, Frigate intelligently selects the best type of live view method for the cameras on your dashboard based on network conditions and features, so this is no longer user selectable.
> 

If I connect to the go2rtc port 1984 and stream video from there, I get RTC - so it is availible. 

**Describe the solution you'd like**
Some way to prioritize RTC over MSE over msjpeg

**Describe alternatives you've considered**

**Additional context**
With MSE, the live view seems to slowly drift away from actual 'live'. By right clicking on a live view tile and showing controls, you can see the progress bar creeping towards the left. Once the progress bar gets all the way to the left, the stream shows a still image from the past. So ultimately the problem is that it never 'catches up', meaning I am constantly refreshing the page to restart the live views. Also, with multiple cameras on a page, they don't all drift at the same rate and fall out of sync. 

With RTC mode through go2rtc, I never have to refresh. Any minor network interruptions might stall the feed briefly, but it immediately recovers on its own - and all cameras stay perfectly in sync. 

MSE progress bar:
![image](https://github.com/user-attachments/assets/7151caa2-67a8-4669-ad50-25e38f83bd9e)
![image](https://github.com/user-attachments/assets/375dd035-b231-451d-96c4-e1669b1c0180)

**Comment by hawkeye217** [comment]
WebRTC requires extra configuration, opening/forwarding ports, etc. and does not support H.265/HEVC. Frigate used to default to WebRTC on Safari, and that caused lots of issues for users. MSE is much more well-supported and doesn't require additional setup, hence why it became the default in 0.14.

We don't have any intention on making the mode user-selectable again at this point, but we're looking at ways of improving the intelligent mode selection in future versions of Frigate.

I'm going to close this, but if you'd like to open a camera support discussion, that could be helpful to us - there are some ways to see why your MSE player is buffering, and we might be able to write some code to mitigate that or use that to more intelligently select the live mode.

**Comment by ss6s** [comment]
Hello, that's a bit of a shame. For me, MSE does not work properly with one camera and goes buffering. I'll probably have to go back to 0.13.

**Comment by NickM-27** [comment]
Have you tried the latest builds which fix the buffering?

**Comment by hawkeye217** [comment]
Feel free to stick with 0.13 if that works best for you. However, the OP and I worked together for a while and because of his help, I committed code to improve MSE so that it performs better than WebRTC now. Feel free to grab the latest dev image and give it a try.

**Comment by ss6s** [comment]
hi, unfortunately no - I have now tested it with 0.14.1-453a8d7. Unfortunately, the buffering via mse is still there. The buffering is also when I call the stream directly via gortc and mse. via webrtc the stream is clean and works without reloading.

**Comment by hawkeye217** [comment]
If you open a separate support discussion with your config and the requested details, perhaps we can help you solve the issue with the one camera.

**Comment by folosleg** [comment]
We got older cameras they produce a h264 feed, but for some odd reason they can't be played through MSE, but works flawless over RTC. Only solution at the moment is to ffmpeg reencode them, but it's resource intensive and absolutely unnecessary.

I'd like to suggest a simle option, something like this:

cameras:
  cam1:
    live:
      stream_name: cam1#rtc
  cam2
    live:
      stream_name: cam2#mse

obviously the default can stay MSE, but maybe it is a viable option, might be useful for some folks out there...

Cheers

**Comment by hawkeye217** [comment]
Frigate 0.14.1 now correctly falls back to WebRTC if configured when MSE fails. However, MSE should work with H.264 without issue. Feel free to open a support discussion and we can try to help sort out your issue.

**Comment by alwon1** [comment]
I created a issue on this without seeing this one but the reason I wanted it is different. In my case I'm using CloudFlare tunnels to allow access and would like to avoid potentially running into problems with the terms of use by streaming a bunch of media through them and webrtc allows too do that but I have no way to even make it try webrtc because mse will always work first. Maybe instead a way to disable mse on the server could be added instead

**Comment by tarvip** [comment]
> Frigate 0.14.1 now correctly falls back to WebRTC if configured when MSE fails.

I wonder what would be the downside of making it configurable per camera. I also have issues with one camera where MSE fails but WebRTC works fine (it is not Frigate issue, it does not work even directly in go2rtc). It will eventually fall back to WebRTC, but it can take 20 or more seconds. For testing purpose modified the code (0.15.2) so that it always uses WebRTC, now loads much faster.

**Comment by amatsoukas** [comment]
I also would like an option to disable mse all together, or at least be able to change the priority to webrtc. I mostly use safari as a browser, and with mse some times it works for a while, but most of the time, after a minute or less the stream breaks and it switches to webrtc. But once it switches to webrtc, it works flawlessly. The thing is, that if you use pip from safari, and this switch happens, the stream in pip freezes and never recovers. So i would prefer to be webrtc from the beginning, which is more stable in safari.

**Comment by charlesmunger** [comment]
Comparing webrtc and MSE side-by-side on the same camera feed, webrtc is much lower latency and consistently so. I would much prefer to use it over MSE, despite limitations and setup complexity.

**Comment by deezid** [comment]
How can we force webrtc?
I can only get webrtc to work with Mic turned on, hovering around 0.00 to 0.01s latency

Once mic is off it sits around 2-5s using MSE. 
Why is that live option for webrtc gone? Feels like intentional sabotage.

**Comment by hawkeye217** [comment]
Frigate 0.14 and later intelligently selects the live streaming technology based on a number of factors (user-selected modes like two-way talk, camera settings, browser capabilities, available bandwidth) and prioritizes showing an actual up-to-date live view of your camera's stream as quickly as possible.

It's not possible to manually force a stream technology in the Frigate UI. WebRTC requires additional setup like opening ports, and is less compatible across browsers and platforms than MSE, which is the open standard that is optimized and supported by all browsers. We've actually enhanced the MSE player in Frigate to improve latency and connection robustness above what WebRTC provides, which is why we've preferred it in the Frigate UI.

A 2-5 second delay with MSE usually indicates a codec misconfiguration or a browser decoding issue, as the enhanced code in Frigate won't allow latency from the backend to increase that much. See the [camera settings recommendations](https://docs.frigate.video/configuration/live/#camera-settings-recommendations) in the official docs.

**Comment by deezid** [comment]
Once I turn on the mic (reolink camera) I have 0.00 latency and a stream that runs for hours, while with MSE it may start at 0.50 but slowly drifts up to 5s easily. 

is there no way to force webrtc even without the mic being off?
Edit: go2rtc (port 1984) automatically switches to webrtc, with the mic being off.

**Comment by hawkeye217** [comment]
No, there is no way to force a stream technology in the Frigate UI.

You can use the [Advanced Camera Card](https://card.camera/) in Home Assistant with the go2rtc source or use the go2rtc dashboard (`frigate_ip:1984`) to manually choose your streaming technology.

**Comment by deezid** [comment]
Both webrtc card and advanced camera card play without any latency. Was hoping to get webrtc working inside frigate as well to use it as camera dashboard. But with MSE it's not usable. Also not a great idea to turn on the mic all the time.

**Comment by tarvip** [comment]
I have also some cameras from aliexpress that do not work with MSE at all, it is not frigate issue, I tested directly with go2rtc, I was unable to get it working there, webrtc works fine though.
I run a separate frigate that I patched with Claude Code for those cameras to use WebRTC and not even try to use MSE. It is stupid, I have to build each release separately with patches, but it works for those cameras.

**Comment by deezid** [comment]
> I have also some cameras from aliexpress that do not work with MSE at all, it is not frigate issue, I tested directly with go2rtc, I was unable to get it working there, webrtc works fine though. I run a separate frigate that I patched with Claude Code for those cameras to use WebRTC and not even try to use MSE. It is stupid, I have to build each release separately with patches, but it works for those cameras.

How did you do that?
Using a docker setup here. 
Webrtc is flawless on my reolink camera, runs for hours/days inside go2rtc ui or HA advanced card/webrtc card here.

MSE on the other hand is just a big nuisance. Never works correctly, drops frames like there's no tomorrow and gets out of sync still.

**Comment by tarvip** [comment]
> > I have also some cameras from aliexpress that do not work with MSE at all, it is not frigate issue, I tested directly with go2rtc, I was unable to get it working there, webrtc works fine though. I run a separate frigate that I patched with Claude Code for those cameras to use WebRTC and not even try to use MSE. It is stupid, I have to build each release separately with patches, but it works for those cameras.
> 
> How did you do that? Using a docker setup here. Webrtc is flawless on my reolink camera, runs for hours/days inside go2rtc ui or HA advanced card/webrtc card here.
> 
> MSE on the other hand is just a big nuisance. Never works correctly, drops frames like there's no tomorrow and gets out of sync still.

Basically took the source code, modified with AI and built the docker image from modified source.

**Comment by deezid** [comment]
I wonder if you could setup a fork?

**Comment by tarvip** [comment]
I am thinking if we could make it configurable per camera in config somehow.

**Comment by hawkeye217** [comment]
Right, it's usually inexpensive cameras with a poor codec implementation that are the most problematic.

Glad you were able to get it working with the help of Claude!

For future readers of this thread - manual stream technology selection isn't something we plan to re-add to Frigate. We removed it and improved the MSE player's robustness to make Frigate simpler to configure and more reliable out of the box. Every option we add becomes permanent surface area - it has to be documented, tested, maintained across releases, and supported when it interacts with other features. We're deliberately conservative about adding configuration knobs, especially ones that increase complexity for all users to solve an edge case for some.

As already noted, if you prefer WebRTC, you can use the [Advanced Camera Card](https://card.camera/) in Home Assistant with the go2rtc source, or use the go2rtc dashboard directly (`frigate_ip:1984`).

If you're experiencing latency drift with MSE (starting near 0.5s and slowly climbing), a few things to check on your camera configuration:

- Camera codec settings - don't use "smart" or "+" codecs that remove keyframes. This will cause issues in recordings and live view. See the [camera settings recommendations](https://docs.frigate.video/configuration/live/#camera-settings-recommendations) in the official docs.
- Keyframe interval - set it to 1x your framerate (e.g. every 30 frames at 30fps). Larger GOP sizes force the browser to maintain a deeper buffer to decode safely, which directly contributes to latency growth.
- Use a lower-bandwidth substream for live view - reducing the bitrate makes it easier for the browser to keep up with incoming data and reduces buffer buildup.
- Network stability - jitter between go2rtc and the browser is the main driver of buffer growth. The MSE player intentionally grows its buffer when delivery is inconsistent to avoid stutter.
- Understand the tradeoff - MSE runs over TCP and guarantees every frame arrives in order, so it must buffer to handle variability. WebRTC uses UDP and drops frames to stay real-time instead. A "0.00s" latency on WebRTC means frames are being dropped rather than buffered. Neither approach is wrong, they just optimize for different things.

**Comment by deezid** [comment]
I can only speak from my own experience.
MSE drops frames a lot, a rate of over 10% is quite normal. 2-5s latency after few minutes as well and audio and video stutter a lot.

Webrtc (mic on moment).
0.00s latency, 0% frame drop rate, 0 dropped frames. 

My cams are setup to use constant bitrate and a keyframe interval of 1, are mostly wired as well. Although that doesn't make any difference in my setup.

The proxmox/docker server where everything is installed is also hardwired.
My PC also has a direct ethernet connection but neither my laptop, tablet or PC can play MSE without any stutter, drops, huge latency etc.

MSE for sure for me and many others doesn't guarantee stable playback. It feels like watching my old Google Nest cameras through the cloude while webrtc inside Go2rtc UI and Home Assistant is basically flawless without any audio playback drops unlike MSE.

**Comment by hawkeye217** [comment]
To be clear, the "0.00s latency / 0 dropped frames" WebRTC stats you see in the Frigate UI can be misleading, and those metrics aren't measuring what many think they're measuring.

WebRTC latency (as reported by browsers as `currentRoundTripTime`) measures the STUN/RTCP network round-trip time, not actual video latency. On a LAN, this will always be near-zero regardless of actual glass-to-glass delay. It does not include encoding, jitter buffering, decoding, or rendering time. MSE's latency stat measures buffer depth (`seekable.end - currentTime`), which is a fundamentally different measurement. So it's essentially comparing apples to oranges.

WebRTC dropped frames (as reported by browsers as `framesDropped`) only counts frames that were fully assembled but then dropped at the decoder or renderer level. It does not count:

- Packets lost on the network (tracked separately by `packetsLost`)
- Packets discarded by the jitter buffer for arriving too late — and Chrome doesn't reliably update `packetsDiscarded` for video
- Frames that could never be assembled because one or more packets were lost — these never appear in `framesReceived` at all, so they're invisible to `framesDropped`

In other words, WebRTC can silently discard incomplete frames at the jitter buffer level and they will never show up in any frame counter. This is by design, it's how WebRTC maintains low latency over UDP. It drops data it can't use in time rather than buffering it.

That is another reason why we've chosen MSE for Frigate - on a mobile or unstable network connection, WebRTC's approach of dropping frames to maintain low latency works against you. If you're checking your cameras over cellular or WiFi with intermittent packet loss, WebRTC will silently discard those incomplete frames, resulting in frozen video, visual corruption, or jumps in the feed that you may not even realize you're missing. You could glance at your camera and see a stale frame without knowing it. MSE over TCP retransmits every lost packet, so the video may buffer briefly, but when it plays, every frame is there - nothing is silently skipped. For a security camera system where the point is to actually see what's happening, delivering every frame reliably matters more than shaving a second off the latency number.

MSE over TCP guarantees every frame arrives and is decoded in order, so any delay is visible in the buffer depth. That's why you see the latency number climb - the data is actually all there, the browser just hasn't played it yet.

**Comment by deezid** [comment]
How you describe MSE sounds like webrtc basically runs over here (even over
5G outside the local network).

Maybe I should do side by side recording of webrtc (go2rtc interface) vs
mse (frigate) to showcase to laggyness and jumping (first 20s) and latency
(after around 20s when it reaches 2-5s with hundreds of frames skipped.

Maybe MSE works great on high-end hardware.
It certainly doesn’t on regular hardware such like reolink.

And forcing mse unless the mic is on doesn’t feel right.

**Comment by TheBlackPlague** [comment]
As someone who just started using Frigate (with my 2x [Reolink PoE](https://www.amazon.com/REOLINK-PoE-Outdoor-Surveillance-E1/dp/B0CYGC7SCM) cameras), the WebUI Dashboard is impossible to work with when viewing a live-view of the cameras. 

Each camera has the Clear configuration set as following:
```
Resolution: 3840*2160
Frame Rate (FPS): 15
Max Bitrate (Kbps): 8192
I-frame Interval: 1x
Encoding Format: H.264
Frame Rate Mode: Constant
```

and my Frigate Config is also a very simple setup:
```
mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: true
  cookie_secure: false
  session_length: 604800

birdseye:
  enabled: false

detect:
  enabled: false

motion:
  enabled: false

audio:
  enabled: false

review:
  alerts:
    enabled: false
  detections:
    enabled: false

snapshots:
  enabled: false

record:
  enabled: false
  continuous:
    days: 14
  motion:
    days: 0
  alerts:
    retain:
      days: 0
  detections:
    retain:
      days: 0

ffmpeg:
  hwaccel_args: preset-vaapi
  apple_compatibility: true
  output_args:
    record: preset-record-generic-audio-copy

go2rtc:
  streams:
    front_driveway:
      - "rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.50.51:554/Preview_01_main#backchannel=0"
      - "ffmpeg:front_driveway#audio=opus"
      - "rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.50.51:554/Preview_01_sub"
    front_driveway_low_res:
      - "rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.50.51:554/Preview_01_sub#backchannel=0"

    back_yard:
      - "rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.50.52:554/Preview_01_main#backchannel=0"
      - "ffmpeg:back_yard#audio=opus"
      - "rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.50.52:554/Preview_01_sub"
    back_yard_low_res:
      - "rtsp://{FRIGATE_CAMERA_USERNAME}:{FRIGATE_CAMERA_PASSWORD}@192.168.50.52:554/Preview_01_sub#backchannel=0"

  webrtc:
    candidates:
      - "192.168.50.2:8555"
      - "stun:8555"

cameras:
  front_driveway:
    enabled: true
    webui_url: "http://192.168.50.51"
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_driveway"
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_driveway_low_res"
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      streams:
        "4K HEVC": front_driveway
    onvif:
      host: "192.168.50.51"
      port: 8000
      user: "{FRIGATE_CAMERA_USERNAME}"
      password: "{FRIGATE_CAMERA_PASSWORD}"
    ui:
      order: 0

  back_yard:
    enabled: true
    webui_url: "http://192.168.50.52"
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/back_yard"
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/back_yard_low_res"
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      streams:
        "4K HEVC": back_yard
    onvif:
      host: "192.168.50.52"
      port: 8000
      user: "{FRIGATE_CAMERA_USERNAME}"
      password: "{FRIGATE_CAMERA_PASSWORD}"
    ui:
      order: 1

ui:
  timezone: "America/Chicago"
  unit_system: metric

version: 0.17-0
```

However, MSE frame rate drop is between 25%-35% when using dashboard over WiFi and between 6%-15% when using dashboard over Ethernet. The stream also freezes (or drifts far behind) when using MSE. In my eyes, this is unacceptable, and I wish the Frigate project wouldn't self-sabotage itself by forcing MSE. I understand making MSE the default option for compatibility, however, forcing it is just taking power away from the users of Frigate. That's something open-source projects shouldn't do. As everyone else in the comments, I would much prefer WebRTC. 

I also hate that this is marked as closed as not planned.
