### ISSUE TITLE
Corrupt image in jsmpeg-player under 0.9.0 container

### ISSUE THREAD

**Issue by noelhibbard** [blakeblackshear/frigate#1308]
**Describe the bug**
Running the 0.9.0 docker I am getting a corrupt image image on one of my cameras when viewing the live stream here:
http://server1.example.com:5000/cameras/Front_Left

It shows a few corrupt frames and then playback freezes and then just rolls jsmpeg-player errors in the debug console which I will include bellow.

I'm guessing there is something about my cameras stream that doesn't play well with jsmpeg-player. I could use ffmpeg to dump some footage if that would help. Just let me know what command line args would generate the most useful capture for debugging.

**Version of frigate**
0.9.0-dada764

**Config file**
```yaml
mqtt:
  host: server1.example.com
  topic_prefix: frigate
cameras:
  Front_Left:
    detect:
      enabled: True
      max_disappeared: 100
    objects:
      track:
        - person
        - car
        - bicycle
        - bus
      filters:
        car:
          threshold: 0.63
          mask:
            - 298,288,293,396,990,348,974,243
            - 1273,1520,1360,1218,846,1320,461,1520
    motion:
      threshold: 25
      mask:
        - 1951,1396,2661,1393,2660,1480,1952,1490
        - 2688,1520,2688,1017,2435,1150,1801,1373,904,1520
        - 1330,464,1361,408,1415,333,1418,255,1365,181,1303,122,1258,136,1193,191,1150,266,1123,328,1122,363,1155,419,1257,501
        - 2393,464,2463,458,2500,433,2560,429,2565,345,2513,306,2458,308,2423,280,2355,276,2282,300,2260,341,2245,388,2330,448
        - 1012,285,1089,215,1162,211,1192,165,1172,108,1094,95,1029,42,930,22,865,32,754,80,749,165,754,233,821,268,897,288
        - 0,340,0,255,356,112,418,170
        - 2688,186,2616,241,2605,394,2601,529,2688,586
        - 1258,636,1388,634,1483,611,1463,568,1348,539,1250,534,1167,538,1084,554,1039,581,1133,617
        - 1739,195,1788,145,2024,230,2017,273
        - 2229,376,2237,350,2212,335,2159,340,2155,379,2207,381
    zones:
      Driveway:
        coordinates: 503,719,288,1007,87,1520,0,1520,0,627,737,549,608,603
      Yard:
        coordinates: 2688,1520,2688,649,1874,599,612,599,399,877,58,1520
        filters:
          car:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    snapshots:
      enabled: True
      crop: True
      height: 300
    clips:
      retain:
        default: 2
      enabled: True
    record:
      enabled: True
      retain_days: 1
    ffmpeg:
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        rtmp: -c copy -f flv
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://hidden:password@10.18.2.202:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - clips
            - record
    width: 2688
    height: 1520
    fps: 10
  ```

**Frigate container logs**
```
frigate    | [2021-06-29 12:40:10] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2021-06-29 12:40:10] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2021-06-29 12:40:10] frigate.mqtt                   INFO    : MQTT connected
frigate    | [2021-06-29 12:40:10] frigate.app                    INFO    : Output process started: 219
frigate    | [2021-06-29 12:40:10] ws4py                          INFO    : Using epoll
frigate    | [2021-06-29 12:40:10] frigate.app                    INFO    : Camera processor started for Front_Left: 221
frigate    | [2021-06-29 12:40:10] frigate.app                    INFO    : Capture process started for Front_Left: 229
frigate    | [2021-06-29 12:40:10] ws4py                          INFO    : Using epoll
frigate    | [2021-06-29 12:40:10] detector.coral                 INFO    : Starting detection process: 217
frigate    | [2021-06-29 12:40:10] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | [2021-06-29 12:40:13] frigate.edgetpu                INFO    : TPU found
frigate    | [2021-06-29 13:44:40] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:40004]
frigate    | [2021-06-29 13:44:47] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:40004]
frigate    | [2021-06-29 13:57:58] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45170]
frigate    | [2021-06-29 13:58:14] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45274]
frigate    | [2021-06-29 13:58:16] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:60360]
frigate    | [2021-06-29 13:59:20] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45170]
frigate    | [2021-06-29 13:59:20] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45274]
```

**Frigate stats**
```json
{
    "Driveway": {
        "camera_fps": 10,
        "capture_pid": 231,
        "detection_fps": 0,
        "pid": 224,
        "process_fps": 0,
        "skipped_fps": 0
    },
    "Front_Left": {
        "camera_fps": 10.1,
        "capture_pid": 229,
        "detection_fps": 0,
        "pid": 221,
        "process_fps": 10.1,
        "skipped_fps": 0
    },
    "detection_fps": 0,
    "detectors": {
        "coral": {
            "detection_start": 0,
            "inference_speed": 8,
            "pid": 217
        }
    },
    "service": {
        "storage": {
            "/dev/shm": {
                "free": 57.2,
                "mount_type": "tmpfs",
                "total": 67.1,
                "used": 9.9
            },
            "/media/frigate/clips": {
                "free": 67785.4,
                "mount_type": "ext4",
                "total": 195835,
                "used": 118047.2
            },
            "/media/frigate/recordings": {
                "free": 67785.4,
                "mount_type": "ext4",
                "total": 195835,
                "used": 118047.2
            },
            "/tmp/cache": {
                "free": 917.7,
                "mount_type": "tmpfs",
                "total": 1000,
                "used": 82.3
            }
        },
        "uptime": 3877,
        "version": "0.9.0-dada764"
    }
}
```

**FFprobe from your camera**
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://hidden:password@10.18.2.202:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.055000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 2688x1520, 30 fps, 100 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

**Screenshots**
<img src=https://i.imgur.com/7MGKyK6.png />

**Computer Hardware**
 - OS: Debian 10
 - Install method: Docker Compose
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Ethernet

**Camera Info:**
 - Manufacturer: Dahua
 - Model: IPC-HDW2531T-ZS-S2
 - Resolution: 2688x1520
 - FPS: 10

**Chromium Console output:**
```
Uncaught RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[44]:0x52c9
    at _mpeg1_decoder_get_write_ptr (<anonymous>:wasm-function[4]:0x469)
    at a.I.bufferWrite (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at a.write (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at a.I.write (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at C.a.packetComplete (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at C.a.parsePacket (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at C.a.write (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at C.a.onMessage (jsmpeg-player.OlBCBXsUQjKV.js:9)
Uncaught RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[46]:0x5443
    at _mpeg1_decoder_decode (<anonymous>:wasm-function[17]:0x84c)
    at a.I.decode (jsmpeg-player.OlBCBXsUQjKV.js:9)
    at C.a.updateForStreaming (jsmpeg-player.OlBCBXsUQjKV.js:12)
    at C.a.update (jsmpeg-player.OlBCBXsUQjKV.js:12)
```
