### ISSUE TITLE
multiple events for a single moving object

### ISSUE THREAD

**Issue by AnduriI** [blakeblackshear/frigate#1313]
**Describe the bug**
I get multiple events in frigate when there is one moving object. For example I have a car moving through the field of view and two events, one starting at 10:55:40 and 10:55:42. Also when a car enters my driveway and a person leaves I get at least two events. Is there a way to specify a min time difference to be counted as separate events?

**Version of frigate**
0.8.4-5043040

**Config file**
```yaml

mqtt:
  host: 192.168.38.46
  port: 1883
  client_id: frigate
  user: [XXX]
  password: [XXX]

cameras:
  Eingang:
    ffmpeg:
      inputs:
        - path: rtsp://[XXX]@192.168.38.39:554/Streaming/Channels/102
          roles:
            - detect
            - clips
            - rtmp
    width: 704
    height: 576
    fps: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 10
      retain:
        default: 10
        objects:
          person: 15

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones: []
      retain:
        default: 5
        objects:
          person: 10

    objects:
      track:
        - person
        - car
        - cat
        - backpack
      filters:
        person:
          min_score: 0.5
          threshold: 0.7
```

**Computer Hardware**
 - OS: RaspiOS
 - Install method: Docker Compose
 - Coral Version: USB
 - Network Setup: WiFi
