### ISSUE TITLE
Keep getting " Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR"

### ISSUE THREAD

**Issue by Gahrlaag** [blakeblackshear/frigate#1315]
**Describe the bug**
A clear and concise description of what your issue is.

The camera overview screens suddenly all turned green and the error "Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR" shows up in the log. 

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 192.168.88.17
  user: homeassistant
cameras:
  huvudingangen:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 10
    objects: 
      track:
        - person
        - cat
        - bird
    motion:
      mask:
        - 0,0,713,0,770,0,1683,0,1920,0,1806,181,1462,115,1160,35,1018,43,886,56,912,114,885,167,821,219,761,238,689,274,672,314,636,334,573,303,504,281,455,277,430,308,458,386,427,483,230,1080,0,1080
  uppfarten:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 10
    motion:
      mask:
        - 0,0,244,0,603,0,601,193,219,285,169,1080,0,1080
        - 645,0,640,55,606,55,605,0
        - 1209,0,1203,84,1113,75,1118,0
        - 1545,0,1531,125,1470,122,1486,0
        - 1898,0,1827,372,1544,231,1569,0
        - 1404,0,1387,90,1313,75,1320,0

detectors:
  coral:
    type: edgetpu
    device: usb
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.app                    INFO    : Camera processor started for huvudingangen: 39
frigate.app                    INFO    : Camera processor started for uppfarten: 41
frigate.app                    INFO    : Capture process started for huvudingangen: 42
frigate.app                    INFO    : Capture process started for uppfarten: 44
frigate.mqtt                   INFO    : MQTT connected
frigate.mqtt                   INFO    : Turning on clips for huvudingangen via mqtt
frigate.mqtt                   INFO    : Turning on snapshots for huvudingangen via mqtt
frigate.mqtt                   INFO    : Turning on clips for uppfarten via mqtt
frigate.mqtt                   INFO    : Turning on snapshots for uppfarten via mqtt
frigate.video                  INFO    : uppfarten: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : uppfarten: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : huvudingangen: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : huvudingangen: ffmpeg process is not running. exiting capture thread...
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
ffmpeg.uppfarten.detect        ERROR   : [rtsp @ 0x5600bbeab900] DTS discontinuity in stream 0: packet 6 with DTS 146263041800938, packet 7 with DTS 146263041813123
ffmpeg.uppfarten.detect        ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.uppfarten.detect        ERROR   : [flv @ 0x5600bbec2880] Video codec hevc not compatible with flv
ffmpeg.uppfarten.detect        ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
ffmpeg.uppfarten.detect        ERROR   : 
ffmpeg.huvudingangen.detect    ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.huvudingangen.detect    ERROR   : [flv @ 0x559727e40e40] Video codec hevc not compatible with flv
ffmpeg.huvudingangen.detect    ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
ffmpeg.huvudingangen.detect    ERROR   : 
frigate.video                  INFO    : huvudingangen: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : huvudingangen: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : uppfarten: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : uppfarten: ffmpeg process is not running. exiting capture thread...
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
