### ISSUE TITLE
Use external stream as live stream

### ISSUE THREAD

**Issue by johnrobertcobbold** [blakeblackshear/frigate#13179]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to use the external stream defined in my configuration file (below), such as `rtsp://192.168.35.5:8554/front_yard_camera`, as the live stream in the Frigate web UI. I am not using the Frigate go2rtc but an external `go2rtc` instance. Apart from the live stream, everything else works (detection, recording, reviewing through Frigate and the Home Assistant `custom:frigate-card` with WebRTC ). I can of course view the live stream in Home Assistant but it's annoying that it does not work in the Frigate web UI.

I tried to use the camera name `front_yard_camera` as defined in the configuration file under live.stream_name but this is not working. When checking the Chrome dev console, I see that a websocket connection is attempted but fails:

```
WebSocket connection to 'ws://192.168.35.5:5000/live/jsmpeg/front_yard_camera' failed: WebSocket is closed before the connection is established.
```

**Describe the solution you'd like**
To be able to view my external go2rtc rtsp using WebRTC the way I can do with the Home Assistant `custom:frigate-card`

**Additional context**

Frigate configuration

```
cameras:
  front_yard_camera:
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://192.168.35.5:8554/front_yard_camera?video&audio
          roles:
            - detect
            - audio
            - record
    live:
      stream_name: front_yard_camera
``` 

go2rtc configuration:

```
streams:
    front_yard_camera:
       - rtsp://xxx:xxx@192.168.35.4/stream1
       - ffmpeg:front_yard_camera#audio=aac
```
