### ISSUE TITLE
No EdgeTPU detected. Falling back to CPU.

### ISSUE THREAD

**Issue by roofuskit** [blakeblackshear/frigate#132]
Getting the error No EdgeTPU detected. Falling back to CPU. The EdgeTPU is setup and working correctly, fully testing and working. Just not with Frigate.

Setup using Docker Compose using the example provided.

```
/arrow/cpp/src/plasma/store.cc:1226: Allowing the Plasma store to use up to 0.4GB of memory.


/arrow/cpp/src/plasma/store.cc:1253: Starting object store with directory /dev/shm and huge page support disabled


Camera_process started for test: 21


Starting detection process: 20


Starting process for test: 21


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.32:8554/unicast -f rawvideo -pix_fmt rgb24 pipe:


 * Serving Flask app "detect_objects" (lazy loading)


 * Environment: production


   WARNING: This is a development server. Do not use it in a production deployment.


   Use a production WSGI server instead.


 * Debug mode: off


No EdgeTPU detected. Falling back to CPU.
```

**Comment by walthowd** [comment]
Post your sanitized docker-compose.yml - From the docker host run `lsusb -v` and post the section including the bus and device for all idVendor Google devices. Also from the docker host run `docker exec -t frigate find /dev/bus` and post the results.

**Comment by roofuskit** [comment]
```
    frigate:
      container_name: frigate
      restart: unless-stopped
      privileged: true
      shm_size: '1g' # should work for 5-7 cameras
      image: blakeblackshear/frigate:stable
      volumes:
        - /dev/bus/usb:/dev/bus/usb
        - /etc/localtime:/etc/localtime:ro
        - /home/tensorflow/frigate:/config
      ports:
        - "5050:5000"
      environment:
        FRIGATE_RTSP_PASSWORD: "password"
```

```
Bus 002 Device 002: ID 18d1:9302 Google Inc.
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         9
  idVendor           0x18d1 Google Inc.
  idProduct          0x9302
  bcdDevice            1.00
  iManufacturer           0
  iProduct                0
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           96
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              224mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           6
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol    255 Vendor Specific Protocol
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst              15
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
        bMaxBurst               0
Device Status:     0x0c00
  (Bus Powered)
```
```
/dev/bus
/dev/bus/usb
/dev/bus/usb/002
/dev/bus/usb/002/002
/dev/bus/usb/002/001
/dev/bus/usb/001
/dev/bus/usb/001/006
/dev/bus/usb/001/005
/dev/bus/usb/001/004
/dev/bus/usb/001/003
/dev/bus/usb/001/002
/dev/bus/usb/001/001
```

**Comment by walthowd** [comment]
That all looks good -- Try switching to `image: blakeblackshear/frigate:0.5.1-rc4` and see if the same behavior continues.

**Comment by roofuskit** [comment]
> That all looks good -- Try switching to `image: blakeblackshear/frigate:0.5.1-rc4` and see if the same behavior continues.

Same behavior, I even stopped the coral pi rest server to see if that was causing some sort of conflict and it still doesn't see it on boot.

**Comment by valantur** [comment]
same issue here

my docker-compose file:

```
frigate:
  container_name: frigate
  restart: unless-stopped
  shm_size: '1g'
  privileged: true
  image: blakeblackshear/frigate:stable
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/opt/docker_data/frigate:/config:ro"
    - "/dev/bus/usb:/dev/bus/usb"
  devices:
    - "/dev/dri/renderD128:/dev/dri/renderD128"
  ports:
    - "5000:5000"
```

I can see the /dev/bus/usb/002/002 device on the docker container, but frigate doesn't seem to recognize it.
Is there a way to specify which device to use via the config.yml file?

Thanks!

**Comment by alex-savin** [comment]
Same issue with 0.7.1 (amd64)

Config file
```
detectors:
  coral:
    type: edgetpu
    device: usb
```

Logs
```
root@frigate:/data/frigate# docker-compose up -d
Creating network "frigate_default" with the default driver
Creating frigate ... done
root@frigate:/data/frigate# docker logs -f frigate
Fontconfig error: Cannot load default config file
On connect called
ffprobe -v panic -show_error -show_streams -of json "rtsp://***REDACTED***"
Starting detection process: 42
Attempting to load TPU as usb
No EdgeTPU detected. Falling back to CPU.
```

```
root@frigate:/data/frigate# docker exec -t frigate find /dev/bus
/dev/bus
/dev/bus/usb
/dev/bus/usb/003
/dev/bus/usb/003/001
/dev/bus/usb/002
/dev/bus/usb/002/004
/dev/bus/usb/002/001
/dev/bus/usb/001
/dev/bus/usb/001/002
/dev/bus/usb/001/001
```
```
root@frigate:/data/frigate#
root@frigate:/data/frigate# find /dev/bus
/dev/bus
/dev/bus/usb
/dev/bus/usb/003
/dev/bus/usb/003/001
/dev/bus/usb/002
/dev/bus/usb/002/004
/dev/bus/usb/002/001
/dev/bus/usb/001
/dev/bus/usb/001/002
/dev/bus/usb/001/001
```

it was working at v0.7.0-rc2

Any ideas how I can fix it?
