### ISSUE TITLE
Unable to switch off `detect`

### ISSUE THREAD

**Issue by mike-code** [blakeblackshear/frigate#1322]
**Describe the bug**
I am unable to turn off `detect` role. I was looking for an NVR to perform a 24/7 recording with seamless option to manage recordings/clips, archive the important ones etc. I'm not really looking into any motion detection, AI recognition etc. Perhaps Frigate is not the tool I'm looking for, nonetheless, I was wondering if that's perhaps not intended to force detect, provided I don't have any TPU thus my poor raspberry CPU would be quickly overwhelmed.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  host: mqtt
cameras:
  foobar:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: rtsp://cam01.home:554/s0
          roles:
            - record
    width: 1920
    height: 1080
    fps: 30
    record:
      enabled: True
      retain_days: 14
    detect:
      enabled: False
```

**Frigate container logs**
```
Creating network "frigate_default" with the default driver
Creating frigate_mqtt_1 ... done
Creating frigate_frigate_1 ... done
Attaching to frigate_mqtt_1, frigate_frigate_1
frigate_1  |  * Starting nginx nginx
frigate_1  |    ...done.
frigate_1  | Error parsing config: The detect role is required for dictionary value @ data['cameras']['foobar']['ffmpeg']['inputs']
frigate_frigate_1 exited with code 1
```

**Frigate stats**
```json
n/a
```

**FFprobe from your camera**

Run the following command and paste output below
```
n/a
```
