### ISSUE TITLE
Camera Feed not working

### ISSUE THREAD

**Issue by DanPatten** [blakeblackshear/frigate#1336]
**Describe the bug**
My Unifi Doorbell Camera RTSP stream is very slow, it renders properly but will not move any frames and ends up getting very far behind.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 192.168.0.181
  port: 1883
  user: xx
  password: xx
  topic_prefix: frigate
  client_id: frigate
cameras:
  nursery:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.1:7447/x
          roles:
            - detect
    width: 1920
    height: 1080
    fps: 5
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.1:7447/x
          roles:
            - detect
    width: 1600
    height: 1200
    fps: 5
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.1:7447/xx
          roles:
            - detect
    width: 1920
    height: 1080
    fps: 5

detectors:
  coral:
    type: edgetpu
    device: usb
logger:
  default: debug
objects:
  filters:
    person:
      mask:
        - 635,910,516,961,545,831
```

**Frigate stats**
```{
  "detection_fps": 0.0, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 10.0, 
      "pid": 34
    }
  }, 
  "doorbell": {
    "camera_fps": 5.1, 
    "capture_pid": 44, 
    "detection_fps": 0.0, 
    "pid": 38, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "garage": {
    "camera_fps": 5.1, 
    "capture_pid": 47, 
    "detection_fps": 0.0, 
    "pid": 40, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "nursery": {
    "camera_fps": 5.2, 
    "capture_pid": 42, 
    "detection_fps": 0.0, 
    "pid": 36, 
    "process_fps": 5.2, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1993.2, 
        "mount_type": "tmpfs", 
        "total": 2005.7, 
        "used": 12.5
      }, 
      "/media/frigate/clips": {
        "free": 31995.4, 
        "mount_type": "ext4", 
        "total": 61472.6, 
        "used": 26336.1
      }, 
      "/media/frigate/recordings": {
        "free": 31995.4, 
        "mount_type": "ext4", 
        "total": 61472.6, 
        "used": 26336.1
      }, 
      "/tmp/cache": {
        "free": 2005.7, 
        "mount_type": "tmpfs", 
        "total": 2005.7, 
        "used": 0.0
      }
    }, 
    "uptime": 117, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
[rtsp @ 00000201370ebf40] decoding for stream 1 failed
Input #0, rtsp, from 'rtsp://192.168.0.1:7447/xx':
  Metadata:
    title           :xx
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
    Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1600x1200 [SAR 1:1 DAR 4:3], 30 fps, 30 tbr, 90k tbn, 60 tbc
```

**Computer Hardware**
 - OS: HassOS
 - Install method: Addon
 - Virtualization: None
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Ubiquiti
 - Model:  G4 Doorbell
 - Resolution: 1600x1200
 - FPS: 5

RTSP stream works fine in VLC player

Edit:
Things tried so far so far is helping:
-Added     input_args: -vsync drop - although it appears its dropping too many bad frames causing the image to do detections too often
-Changed streams to med quality from HD
