### ISSUE TITLE
Onvif PTZ reversed movement config

### ISSUE THREAD

**Issue by Homosanians** [blakeblackshear/frigate#13519]
**Describe what you are trying to accomplish and why in non technical terms**
Some cameras, particularly inexpensive ones from platforms like AliExpress that work with ICSee, have an inverted horizontal movement. While this can be corrected within the ICSee app, the fix does not extend to ONVIF movement commands. Adding an optional configuration to the ONVIF section that allows reversing horizontal and vertical movements would improve the user experience by ensuring that the correct directional arrows are used in the UI. It would also enable the use of auto-tracking capabilities effectively.

**Describe the solution you'd like**
Add configuration entries and implement them.
```
    # Optional: connect to ONVIF camera
    # to enable PTZ controls.
    onvif:
        # Optional: reverse camera movement
        reverse_movement:
            horizontal: False
            vertical: False
```

**Describe alternatives you've considered**
I’ve considered purchasing a different camera that doesn’t have this issue or using another NVR.
