### ISSUE TITLE
[FR} Expand required_zones to prescribe specific zones to specific objects

### ISSUE THREAD

**Issue by HITChris** [blakeblackshear/frigate#1353]
My use case: I have a camera overlooking the entire front yard, driveway, and street. I likewise have a single, corresponding 'camera' defined in Frigate, and it is set to detect both persons and cars. I want clips/snapshots/notifications any time any 'person' is detected anywhere (holy paranoia). My issue though is... I only want to get clips/snapshots/notifications on _cars_ if the car has at some point entered FrontYard_Street (the zone encompassing my street). The idea being to avoid generating clips/snapshots/notifications on the cars just sitting in my driveway all day. So, maybe expanding required_zones to allow for something **like**:
`

    zones:
      FrontYard_Street:
        coordinates: 231,...
      FrontYard_Driveway:
        coordinates: 643,...

    clips:
      objects:
        - car
        required_zones:
          - "FrontYard_Street"

    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 264,...
        car:
          mask:
            - 609,...
  `

**Comment by blakeblackshear** [comment]
You should be able to do this in 0.9.0 with [the new objects list for a zone](https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/cameras.md#zones).

**Comment by HITChris** [comment]
> You should be able to do this in 0.9.0 with [the new objects list for a zone](https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/cameras.md#zones).

I caught that PR, but my understanding of it is that zone-level object definition is more or less just an expansion of object-level masking, and so I don't think it would help me to restrict 'car' detections from being tagged with **either** zone FrontYard_Street or FrontYard_Driveway. My main goal is to avoid generating anything on those cars parked in the driveway... and yet still generate if a new one shows up from the road.

Normally you'd handle this in Nodered or whatever downstream layer is involved, but something more upstream would avoid the clips/snapshots

**Comment by blakeblackshear** [comment]
This should do it:
```yaml
camera:
  clips:
    required_zones:
      - entire_yard
      - front_yard_street
  zones:
    entire_yard:
      coordinates: ... (everywhere you want a person)
      objects:
        - person
    front_yard_street:
      coordinates: ... (just the street)
      objects:
        - car
```

Only car objects can trigger the `front_yard_street` zone and only person can trigger the `entire_yard`. You will get clips for person objects that enter anywhere in the yard, and clips for cars only if they enter the street.
