### ISSUE TITLE
HA entity with HD stream when multi-stream is used via GO2RTC

### ISSUE THREAD

**Issue by xekil** [blakeblackshear/frigate#13540]
Hello,

I would like to have the HD stream via the Frigate integration of Home Assistant, but the available stream is only the SD stream.

Indeed, the goal is to use the HD Stream of Go2RTC which already broadcasts to Frigate 1 HD Stream and an SD Stream, but the Frigate integration only sends one camera entity per camera with only the SD Stream to Home Assistant (i.e. 6 FPS, 640x360 pixels and no audio).

Is it possible to have the HD stream via the Frigate integration without having to configure another camera entity manually in the home assistant? 

Here is my multi-stream configuration with Frigate:

Thanks in advance.

```

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.70:8555          # IP LXC
      - stun:8555              

  streams:
    gate_hd:
      - rtsp://user:password@192.168.1.80:554/Streaming/Channels/101
    gate_sd:
      - rtsp://user:passwordP8@192.168.1.80:554/Streaming/Channels/102

cameras:
  gate:
    live:
      stream_name: gate_hd
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy 
      inputs:
        - path: rtsp://127.0.0.1:8554/gate_hd  
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gate_sd 
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 6
```

For information, I use Frigate 0.14.1 via an LXC container, the integration is up to date as well as home assistant

Thanks in advance.
