### ISSUE TITLE
No clip available for event

### ISSUE THREAD

**Issue by tve** [blakeblackshear/frigate#1388]
**Describe the bug**
For my MJPEG esp32 cameras I see around half of the events having no clip available. Looking into the logs, I consistently see this error:
```
2021-07-14T15:44:37.224138051Z frigate.events                 WARNING : Unable to create clip for bi
rdbath and event 1626277440.949275-icwlxf. There were no cache files for this event.
```
The event time is 8:44:00, the error was logged 37 seconds later.

I ran the following in another window (using docker exec): `while true; do date; ls -ls bird*; df -h .; sleep 2; done`
and the output around the event time is:
```
Wed Jul 14 08:43:59 PDT 2021
3380 -rw-r--r-- 1 root root 3460292 Jul 14 08:43 birdbath-20210714084236.mp4
3076 -rw-r--r-- 1 root root 3145776 Jul 14 08:43 birdbath-20210714084321.mp4
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           477M   59M  419M  13% /tmp/cache
Wed Jul 14 08:44:01 PDT 2021
3380 -rw-r--r-- 1 root root 3460292 Jul 14 08:43 birdbath-20210714084236.mp4
3332 -rw-r--r-- 1 root root 3407920 Jul 14 08:44 birdbath-20210714084321.mp4
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           477M   60M  418M  13% /tmp/cache
```
The output around the error message is:
```
Wed Jul 14 08:44:37 PDT 2021
3380 -rw-r--r-- 1 root root 3460292 Jul 14 08:43 birdbath-20210714084236.mp4
3652 -rw-r--r-- 1 root root 3738429 Jul 14 08:44 birdbath-20210714084321.mp4
3076 -rw-r--r-- 1 root root 3145776 Jul 14 08:44 birdbath-20210714084403.mp4
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           477M   77M  401M  17% /tmp/cache
Wed Jul 14 08:44:39 PDT 2021
3652 -rw-r--r-- 1 root root 3738429 Jul 14 08:44 birdbath-20210714084321.mp4
3332 -rw-r--r-- 1 root root 3407920 Jul 14 08:44 birdbath-20210714084403.mp4
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           477M   60M  418M  13% /tmp/cache
```
In the camera config I have `pre_capture: 2`, so it seems to me that the 20210714084321.mp4 should work for that. I also have `post_capture: 5` and the 20210714084403.mp4 recording should work for that (it's actually still being written to by the time of the error, I can see the file increase in size in subsequent `ls` outputs).

This does look to me like it's neither an ffmpeg issue nor a disk full issue. I'll see whether I can add some info to the error message to print out what it expects.

NB: there seem to be a number of related issues, for example: #932 #896 #1096

**Version of frigate**
0.8.4-5043040⏎

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: core.voneicken.com
  user: frigate
  password: f607ef782c520ccd75ce772f27e38716

cameras:
  gate:
    ffmpeg:
      inputs:
        - path: rtsp://phycam.voneicken.com/live/1/h264.sdp
          roles:
            - detect
            - rtmp
            - clips
            - record
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -stimeout
        - "5000000"
      output_args:
        rtmp: -c:v copy -an -f flv
    width: 768
    height: 432
    fps: 4
    clips:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
    record:
      enabled: True
      retain_days: 3
    motion:
      mask:
        - 768,0,581,0,544,152,540,432,768,432
    objects:
      track: [ 'person', 'car', 'dog', 'cat', 'sheep', 'bycicle', 'motorcycle', 'truck', 'bus' ]

  birdbath:
    ffmpeg:
      inputs:
        - path: http://esp32-cam6.voneicken.com:81
          roles:
            - detect
            - rtmp
            - clips
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -r
        - "4"
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v
 h264_vaapi -vf format=nv12,hwupload -r 4 -an
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v
h264_vaapi -vf format=nv12,hwupload -r 4 -an
        rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 4 -an -f flv
    width: 1024
    height: 768
    clips:
      enabled: True
      pre_capture: 2
      post_capture: 5
      retain:
        default: 7
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    objects:
      track: [ 'bird', 'cat', 'dog', 'sheep' ]

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  cpu1:
    type: cpu
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Computer Hardware**
 - OS: Ubuntu 20.04
 - Install method: docker command
 - Virtualization: just docker
 - Coral Version: None
 - Network Setup: both cameras over wifi

**Camera Info:**
 - Manufacturer: esp32-cam
 - Resolution: XGA 1024x768
 - FPS: ~2

**Comment by highaltidude** [comment]
Can you post your docker-compose config?

**Comment by tve** [comment]
Systemd unit:
```
[Unit]
Description=Frigate Video Recorder
Requires=docker.service
After=docker.service

[Service]
Restart=always
ExecStartPre=-/usr/bin/docker stop %n
ExecStartPre=-/usr/bin/docker rm %n
ExecStartPre=rm -f /dev/shm/*gate* /dev/shm/*bird*
ExecStart=/usr/bin/docker run \
  --name %n \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=500000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  -v /home/frigate/media:/media/frigate \
  -v /home/frigate/config.yml:/config/config.yml:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -p 5000:5000 \
  -p 1935:1935 \
  blakeblackshear/frigate:stable-amd64
ExecStop=/usr/bin/docker stop -t 2 %n
ExecStopPost=/usr/bin/docker rm -f %n

[Install]
WantedBy=multi-user.target
```

**Comment by highaltidude** [comment]
tmpfs-size

Have you tried to double it to 1000000000 ?

**Comment by tve** [comment]
Look at the df output before/after event and error message I posted:
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           477M   77M  401M  17% /tmp/cache
```

**Comment by highaltidude** [comment]
Maybe #788 will help

**Comment by tve** [comment]
Thanks for pointing me in that direction. I added some debug output. It's seeing the clips that are there and it's patiently waiting for the current clip to be "cut", but that doesn't happen in the 4*5 seconds afforded.
Looking at the clips in the cache, they're around 45 seconds long.
The ffmpeg command has `-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -vf format=nv12,hwupload -r 4 -an /tmp/cache/birdbath-%Y%m%d%H%M%S.mp4` so that's not what ffmpeg is asked to do...

**Comment by tve** [comment]
The ffmpeg docs state:
> Note that if you want accurate splitting for a video file, you need to make the input key frames correspond to the exact splitting times expected by the segmenter, or the segment muxer will start the new segment with the key frame found next after the specified start time.

In my case the input is an esp32-cam MJPEG format running ~3fps. I've tried to add `-segment_format_options gop_size=10` or `-force_key_frame 2` and neither worked. The former produces an error ("Some of the provided format options are not recognized") and the latter seems to have no effect. ffmpeg mysteries...

For reference, the full ffmpeg command I'm running is
`ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -r 4 -i http://esp32-cam6.voneicken.com:81 -f segment -segment_time 10 -segment_format mp4 -force_key_frames 2 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -vf format=nv12,hwupload -r 4 -an /tmp/cache/birdbath-%Y%m%d%H%M%S.mp4 -f rawvideo -pix_fmt yuv420p pipe:`

Overall, it seems that the "wait for clip to be cut" loop should wait for 2x the duration of the last clip instead of waiting for a fixed 20s. But finding a solution to the ffmpeg segment cutting would be best...

**Comment by tve** [comment]
Aha, looks like `-g 10` does the trick, I just had it incorrectly under `-segment_format_options`. The ffmpeg cmdline nmow looks as follows:
`ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -r 4
-i http://esp32-cam6.voneicken.com:81 -f segment -segment_time 10 -segment_format mp4 -g 10 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -vf format=nv12,hwupload -r 4 -an /tmp/cache/birdbath-%Y%m%d%H%M%S.mp4 -f rawvideo -pix_fmt yuv420p pipe:`

It now seems to cut segments every 13 seconds:
```
 3256 -rw-r--r-- 1 root root  3332617 Jul 14 20:29 birdbath-20210714202923.mp4
 3176 -rw-r--r-- 1 root root  3249784 Jul 14 20:29 birdbath-20210714202937.mp4
 3144 -rw-r--r-- 1 root root  3215574 Jul 14 20:30 birdbath-20210714202950.mp4
 3116 -rw-r--r-- 1 root root  3190267 Jul 14 20:30 birdbath-20210714203003.mp4
 3096 -rw-r--r-- 1 root root  3170289 Jul 14 20:30 birdbath-20210714203017.mp4
 3080 -rw-r--r-- 1 root root  3151057 Jul 14 20:30 birdbath-20210714203029.mp4
 3068 -rw-r--r-- 1 root root  3139610 Jul 14 20:30 birdbath-20210714203042.mp4
 1284 -rw-r--r-- 1 root root  1310768 Jul 14 20:31 birdbath-20210714203055.mp4
```

**Comment by mitchross** [comment]
@tve can you post your full config with the -g 10 ? I have the same issue.

**Comment by tve** [comment]
Here's a portion of my config:
```
cameras:
  overview:
    ffmpeg:
      inputs:
        - path: http://esp32-cam3.voneicken.com:81
          roles:
            - detect
            - clips
            - record
            - rtmp
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -r
        - "1"
      output_args:
        record: -f segment -segment_time 600 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:
v h264_vaapi -qp 30 -vf format=nv12,hwupload -r 2 -an
        clips: -f segment -segment_time 10 -segment_format mp4 -g 10 -reset_timestamps 1 -strftime 1
 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 2 -an
        rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 2 -an -f flv
    width: 1600
    height: 1200
    record:
      enabled: True
      retain_days: 2
    clips:
      enabled: True
      pre_capture: 2
      post_capture: 5
      retain:
        default: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    motion:
      mask:
        - 0,1200,1600,1200,1266,776,1093,830,917,782,772,717,669,797,519,843,320,690,0,685
    objects:
      track: [ 'person', 'bird', 'cat', 'dog', 'sheep' ]

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```
