### ISSUE TITLE
[Feature Request]: Show Telemetry network bandwidth in UI

### ISSUE THREAD

**Issue by greedily8276** [blakeblackshear/frigate#13908]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/13907

<div type='discussions-op-text'>

<sup>Originally posted by **greedily8276** September 23, 2024</sup>
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

Enabling network_bandwidth under telemetry config does not enable it, is not visible on the UI.

### Steps to reproduce

Relative config:

telemetry:
  stats:
    network_bandwidth: True

### Version

0.14.1-f4f3cfa

### In which browser(s) are you experiencing the issue with?

Google Chrome and Frigate on windows. Sagari on MAC

### Frigate config file

```yaml
telemetry:
  stats:
    network_bandwidth: True
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config:/config
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant Frigate log output

```shell
no relevant log about telemetry
```

### Relevant go2rtc log output

```shell
no relevant log about telemetry
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink E1 Zoom

### Screenshots of the Frigate UI's System metrics pages

![immagine](https://github.com/user-attachments/assets/4b8fcec5-b63f-44db-ac19-985da3b7ed71)

### Any other information that may be helpful

_No response_</div>
