### ISSUE TITLE
Reduce ffmpeg recording size

### ISSUE THREAD

**Issue by Lallassu** [blakeblackshear/frigate#1415]
I've tried to add optimization options for compression of the ffmpeg segments. Running with `-vcodec libx265 -crf 30` makes no real change. But doing so on an previous recording reduces file size with about 50%. Any idea how to make this work on the fly with the recording options in frigate configuration file?

**Comment by blakeblackshear** [comment]
It's just a matter of getting your ffmpeg args right. You need to provide your complete config if you want help. Personally, I just got a larger hard drive to save the CPU resources.

**Comment by Lallassu** [comment]
Yes of course. But the thing is that I choose to use a 512GB m2 for my NUC. I wasn't supposed to use recording but decided to do so. However, what part of the config do you want to see? Im mostly interested to get some optimization if possible.

**Comment by blakeblackshear** [comment]
All of it

**Comment by Lallassu** [comment]
I don't know if my formatting got fubar as I only have access via mobile phone right now. But I hope not :) 
```
detectors:
   coral:
      type: edgetpu
      device: usb

mqtt:
  host: 192.168.98.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 
  stats_interval: 60

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
  global_args:
    - -loglevel 
    - error
  output_args:
    record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

cameras:
  livingroom:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.91:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.91:554/s0
          roles:
            - clips
            - rtmp
            - record
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  carport:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.64:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.64:554/s0
          roles:
            - record
            - clips
            - rtmp
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  terrace:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.240:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.240:554/s0
          roles:
            - clips
            - rtmp
            - record
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  frontyard:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,640,0,612,40,485,62,396,82,384,44,352,42,339,84,0,147"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.101:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.101:554/s0
          roles:
            - clips
            - rtmp
            - record
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  backyard:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.29:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.29:554/s0
          roles:
            - record
            - clips
            - rtmp
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5


clips:
  max_seconds: 300
  retain:
    # Required: Default retention days (default: shown below)
    default: 30

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.70
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      # min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      # max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)

record:
  # Optional: Enable recording
  enabled: true
  # Optional: Number of days to retain
  retain_days: 2

snapshots:
  retain:
    default: 30

motion:
  contour_area: 30
```

**Comment by blakeblackshear** [comment]
Note that H265 videos will not play in most browsers, so you wont be able to view recordings/clips in Frigate's WebUI or in Home Assistant.

You can try this:

```yaml
detectors:
   coral:
      type: edgetpu
      device: usb

mqtt:
  host: 192.168.98.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 
  stats_interval: 60

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
  global_args:
    - -loglevel 
    - error
  output_args:
    record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx265 -crf 26 -preset fast -c:a aac -b:a 128k
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

cameras:
  livingroom:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.91:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.91:554/s0
          roles:
            - clips
            - rtmp
            - record
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  carport:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.64:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.64:554/s0
          roles:
            - record
            - clips
            - rtmp
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  terrace:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.240:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.240:554/s0
          roles:
            - clips
            - rtmp
            - record
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  frontyard:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,640,0,612,40,485,62,396,82,384,44,352,42,339,84,0,147"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.101:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.101:554/s0
          roles:
            - clips
            - rtmp
            - record
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5
  backyard:
    detect:
      enabled: true
      max_disappeared: 120
    motion:
      mask: "0,0,0,23,122,22,125,0"
    rtmp:
      enabled: true
    snapshots:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.29:554/s1
          roles:
            - detect
        - path: rtsp://192.168.1.29:554/s0
          roles:
            - record
            - clips
            - rtmp
    objects:
      track:
        - person
    width: 640
    height: 360
    fps: 5


clips:
  max_seconds: 300
  retain:
    # Required: Default retention days (default: shown below)
    default: 30

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.70
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      # min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      # max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)

record:
  # Optional: Enable recording
  enabled: true
  # Optional: Number of days to retain
  retain_days: 2

snapshots:
  retain:
    default: 30

motion:
  contour_area: 30

```
