### ISSUE TITLE
[Support]:  Lots of false positives

### ISSUE THREAD

**Issue by aguscaba** [blakeblackshear/frigate#14157]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/11296

Hi, I am having similar issues than the reference above, many many false positives, in my case I have the regular frigate installation, any help would be appreciated, my issues started mostly at night, please see my examples:
![image](https://github.com/user-attachments/assets/07ed0844-ebfd-40c9-819b-47ded914d6e0)

![image](https://github.com/user-attachments/assets/e06587f3-2fd7-45fe-8e58-43a691def5f6)
### Operating system
Version
0.13.2-6476F8A

Frigate config file

```
mqtt:
  host: 192.168.0.100
  port: 1883
  topic_prefix: frigate
  client_id: frigate


ffmpeg:
  hwaccel_args: preset-vaapi


detectors:
  coral:
    type: edgetpu
    device: usb
      #ov:
      #type: openvino
      #device: AUTO
      #model:
      #path: /openvino-model/ssdlite_mobilenet_v2.xml

        #model:
  #width: 300
    #height: 300
    #input_tensor: nhwc
    #input_pixel_format: bgr
    #labelmap_path: /openvino-model/coco_91cl_bkgr.txt

objects:
  track:
    - person
    - car
  filters:
    person:
      min_area: 200

go2rtc:
  streams:
    front_principal_dvr:
      - rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/101
    front_secondary_dvr:
      - rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/201

cameras:

  front_principal_dvr:
    ffmpeg:
      inputs:
        # High Resolution Stream
        # - path: rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/101 # <----- The stream you want to use to see the camera
          # roles:
            # - rtmp
        # Low Resolution Stream
        - path: rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/101 # <----- The stream you want to use for detection
          roles:
            - detect
      hwaccel_args: preset-vaapi

    record:
      enabled: true

    detect:
      enabled: true
      fps: 5
      # stationary:
        # threshold: 50
    snapshots:
      enabled: true

    zones:
      Car_Monitoring_Area:
        coordinates: 
          0,0.408,0.074,0.263,0.339,0.472,0.395,0.445,0.407,0.162,0.316,0,0.15,0.007,0,0.366
        objects: person
        loitering_time: 4
        inertia: 3
      Front_personas:
        coordinates: 0.716,1,0.608,0.867,0.516,0.761,0.34,0.479,0.074,0.265,0,0.412,0,0.544,0,1
        objects: person
        inertia: 3
        loitering_time: 0
      Front_Garage:
        coordinates: 0.083,0.187,0.316,0.478,0.257,0.873,0,0.546
        objects: car
        inertia: 3
        loitering_time: 0
    motion:
      mask:
        - 0.08,0.904,0.08,0.933,0.02,0.938,0.02,0.9
        - 0,0.225,0,0,0.08,0,0.284,0.049,0.285,0.098,0.045,0.103,0.025,0.149
        - 0.821,0.23,0.831,0.551,1,0.42,0.998,0.041,0.917,0.12
    review:
      alerts:
        required_zones:
          - Car_Monitoring_Area
          - Front_Garage
          - Front_personas
  front_secondary_dvr: # <------ Name the camera
    ffmpeg:
      inputs:
        # High Resolution Stream
        # - path: rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/201 # <----- The stream you want to use to see the camera
          # roles:
            # - rtmp
        # Low Resolution Stream
        - path: rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/202 # <----- The stream you want to use for detection
          roles:
            - detect
      hwaccel_args: preset-vaapi

    record:
      enabled: true

    detect:
      enabled: true # <---- disable detection until you have a working camera feed

      fps: 7
    snapshots:
      enabled: true

    zones:
      Car_Monitoring_Area:
        coordinates: 
          150,240,106,175,76,158,0,129,0,116,79,101,112,102,142,119,172,126,197,164,194,199,164,240
        objects: person
        loitering_time: 4
      Front_personas:
        coordinates: 0,240,0,129,76,158,106,175,150,240
        objects:
          - person
      Front_Garage:
        coordinates: 22,147,122,144,156,228,91,240,35,240,35,240
        objects:
          - car
    motion:
      mask:
        - 0.406,0.063,0.703,0,1,0,1,0.5,0.985,0.316,0.881,0.145,0.665,0.096,0.52,0.096,0.403,0.1
        - 0.801,1,0.711,1,0.71,0.918,0.73,0.858,0.777,0.849,0.804,0.825,0.821,0.893
        - 0.801,1,0.85,0.842,0.889,0.821,0.941,0.845,1,0.751,1,1
    review:
      alerts:
        required_zones:
          - Car_Monitoring_Area
          - Front_Garage
          - Front_personas

  front_dualptz_nvr:
    ffmpeg:
      inputs:
        # High Resolution Stream
        # - path: rtsp://user:pass@192.168.0.136:554/Streaming/Unicast/channels/101 # <----- The stream you want to use to see the camera
          # roles:
            # - rtmp
        # Low Resolution Stream
        - path: rtsp://user:pass@192.168.0.80:554/channel=0_stream=1.sdp # <----- The stream you want to use for detection
          roles:
            - detect
      hwaccel_args: preset-vaapi

    record:
      enabled: true

    detect:
      enabled: true
      #width: 640
      #height: 360
      fps: 5
      # stationary:
        # threshold: 50
    snapshots:
      enabled: true

    zones:
      Front_personas:
        coordinates: 1,0.5,1,0,0.525,0,0.522,0.121,0.436,0.172,0.351,0.233,0.425,0.449,0.757,0.501
        objects: person
        inertia: 3
        loitering_time: 0
      Car_Monitoring_Area:
        coordinates: 
          0.052,0.356,0.124,0.252,0.212,0.216,0.288,0.211,0.351,0.231,0.426,0.449,0.743,0.501,0.194,0.481
        loitering_time: 4
        objects: person
      Detection_Zone:
        coordinates: 0,0,1,0,1,0.5,0,0.5
    motion:
      mask:
        - 0.99,0.028,0.988,0.06,0.619,0.059,0.621,0.023
        - 1,0.5,1,1,0,1,0,0.5
    review:
      alerts:
        required_zones:
          - Front_personas
          - Car_Monitoring_Area
      detections:
        required_zones: Detection_Zone
version: 0.14
```

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Epcom LB7-TURBO-KIT4 CCTV
