### ISSUE TITLE
Object detection for car parked in driveway or non-moving.

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1417]
**Describe the bug**
Setup frigate docker on ubuntu for the first time with cpu detector (soon will add coral if its all well)

Too many (100s) snapshots and clips saved for a parked car in front of the driveway when object detection enabled for car, I would like to know when the car comes or leave or its moving, i have notification enabled and its sending notification of the parked car every min or two.  anyway to avoid it and still have the car clip stored when it moved only

**Version of frigate**
latest 0.8.4

**Config file**
```
mqtt:
  host: 192.168.99.3
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.99.13/outdoor
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - bus
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    clips:
      enabled: True
      retain:
        default: 1

detectors:
  cpu:
    type: cpu
```

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Docker Compose
