### ISSUE TITLE
Can't get OBS served RTSP stream to display.

### ISSUE THREAD

**Issue by lucifudge** [blakeblackshear/frigate#1427]
**Describe the bug**
Can't connect to RTSP stream, I can connect on the same subnet with vlc using a different computer and the same url I'm using in my frigate yml. Camera picture is completely green in the addon.

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.30
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: secret
  stats_interval: 60
cameras:
  lorexobs:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.88:554/live
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
    width: 1024
    height: 768
    fps: 10

```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
detector.coral                 INFO    : Starting detection process: 38
frigate.app                    INFO    : Camera processor started for lorexobs: 41
frigate.app                    INFO    : Capture process started for lorexobs: 42
frigate.mqtt                   INFO    : MQTT connected
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
frigate.video                  INFO    : lorexobs: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : lorexobs: ffmpeg process is not running. exiting capture thread...
ffmpeg.lorexobs.detect         ERROR   : [rtsp @ 0x556bea66b0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
ffmpeg.lorexobs.detect         ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
ffmpeg.lorexobs.detect         ERROR   : Output file #0 does not contain any stream
frigate.video                  INFO    : lorexobs: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
```

**Frigate stats**

dunno how to do this

**FFprobe from your camera**

Run the following command and paste output below
```
Input #0, rtsp, from 'rtsp://192.168.1.88:554/live':
  Duration: N/A, start: 0.100000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1024x768 [SAR 1:1 DAR 4:3], 10 fps, 10 tbr, 90k tbn, 20 tbc

```

**Screenshots**

**Computer Hardware**
 - OS: pi4
 - Install method: addon
 - Virtualization: no
 - Coral Version: usb
 - Network Setup: wifi

**Camera Info:**
 - Manufacturer:  OBS software (desktop capture)
 - Model: using this rtsp addon https://obsproject.com/forum/resources/obs-rtspserver.1037/
 - Resolution: 1024x768
 - FPS: 10

**Additional context**
