### ISSUE TITLE
Coral Dev Board not working

### ISSUE THREAD

**Issue by pilievwm** [blakeblackshear/frigate#1434]
**Describe the bug**
I have succesfull installation of Frigate at my home, but I purchased Coral Dev Board to make things even better and cosnistant. 
There are several issues that I have and I would like to share it here and to find solution.

1. I am starting the docker container with this command: 
`docker run -d --restart unless-stopped --shm-size=512M --name frigate --privileged -v /home/mendel/config:/config:ro -p 5000:5000 -e FRIGATE_RTSP_PASSWORD='password' blakeblackshear/frigate:0.7.3-aarch64`

It starts succesfully but the output of the debug stats, says that there is no camera detection:
```{
  "detection_fps": 0.0,
  "detectors": {
    "coral": {
      "detection_start": 0.0,
      "inference_speed": 10.0,
      "pid": 20
    }
  },
  "kids": {
    "camera_fps": 0.0,
    "capture_pid": 23,
    "detection_fps": 0.0,
    "frame_info": {
      "detect": 0.0,
      "process": 0.0
    },
    "pid": 24,
    "process_fps": 0.0,
    "skipped_fps": 0.0
  }
}
```

The configuration file is just for testing with one camera stream.

**Version of frigate**
frigate:0.7.3

**Config file**
```
web_port: 5000

detectors:
  coral:
    type: edgetpu
    device: ''

mqtt:
  host: 192.168.1.10
  topic_prefix: frigate
  user: temp
  password: temp

################
# Global configuration for saving clips
################
save_clips:
  ###########
  # Maximum length of time to retain video during long events.
  # If an object is being tracked for longer than this amount of time, the cache  
  # will begin to expire and the resulting clip will be the last x seconds of the event.
  ###########
  max_seconds: 60
  clips_dir: /home/mendel/video
  cache_dir: /home/mendel/cache


objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.92
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
  kids:
    ffmpeg:
      input: rtsp://192.168.1.108:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      height: 1280
      width: 720
      fps: 25
    take_frame: 2
    best_image_timeout: 10
    mqtt:
      crop_to_region: True
      snapshot_height: 300
    zones:
      lso:
        coordinates: 1,386
        filters:
          person:
            min_area: 5000
            max_area: 140000
            threshold: 0.93
```

I don't know if the TPU is started because there is no signal at all. 
I am attaching a screenshot from the preview link
http://192.168.1.125:5000/kids

**Screenshots**
![image](https://user-images.githubusercontent.com/5072036/126866459-1b42fe76-5568-44a9-8d85-ee1c73836d15.png)

**Computer Hardware**
 - OS: Mendel Linux (Debian 8)
 - Install method: Docker Command
 - Coral Version: [Coral Dev Board]
 - Network Setup: [WiFi]

**Camera Info:**
 - Manufacturer: [Dahua]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 25]
