### ISSUE TITLE
Allow different resolutions for main and sub streams within the same input

### ISSUE THREAD

**Issue by craigmdennis** [blakeblackshear/frigate#1440]
I have a Reolink RLC-410W-5MP and have it working using with the sub stream or main stream RTMP. 
Each requires the resolution to match the stream output (640x352 and 2560x1440 respectively) to be shown correctly in the Frigate NVR page.

I would like to understand if I can use the lower resolution sub stream for detection and the main stream for clips.
This appears to not currently be possible because the `width`, `height`, and `fps` part of the `frigate.yml` file is for _all_ inputs within the camera definition but with the Reolink, each stream requires its own width and height in order to render correctly in the Frigate NVR page.

### Current: 
```
cameras:
  driveway:
    ffmpeg: 
      inputs:
        - path: rtmp://192.168.1.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
         - path: rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - clips
    width: 640
    height: 352
    fps: 7
```

### How do I achieve different resolutions?
Do I have to declare the camera twice?

```
cameras:
  driveway:
    ffmpeg: 
      inputs:
        - path: rtmp://192.168.1.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
          width: 640
          height: 352
          fps: 7
         - path: rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - clips
          width: 2560
          height: 1440
          fps: 30
```

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.1.xxx
  user: xxx
  password: xxx
  topic_prefix: frigate

cameras:
  driveway:
    ffmpeg: 
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtmp://192.168.1.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
            - clips
            - rtmp
    width: 640
    height: 352
    fps: 7
    objects:
      track:
        - person
        - dog
        - motorcycle
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
        objects:
          person: 14
    clips:
      enabled: true
      retain:
        default: 2
        objects:
          person: 7
    zones:
      cars:
        coordinates: 2560,1440,2560,0,1652,0,1334,106,1233,388,1134,171,827,124,660,277,0,823,0,1440
      neighbours:
        coordinates: 0,759,872,0,0,0

detectors:
  coral:
    type: edgetpu
    device: ''
```

**Computer Hardware**
 - OS: Windows
 - Install method: Addon
 - Coral Version: PCIe
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-410W-5MP
 - Resolution: 640x352
 - FPS: 7

I'd be happy to contribute to testing/updating documentation.

**Comment by blakeblackshear** [comment]
The resolution and fps only apply to the detect role. The other streams are just passed through, so there is no need to specify the resolution.

**Comment by craigmdennis** [comment]
To clarify, this works and passes the full resolution through to HassOS :)

```
cameras:
  driveway:
    ffmpeg: 
      inputs:
        - path: rtmp://192.168.1.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
        - path: rtmp://192.168.1.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - clips
            - rtmp
    width: 640
    height: 352
    fps: 7
    objects:
      track:
        - person
        - dog
        - motorcycle
```

I didn't see this in the documentation (that's not to say it isn't there). I'll take another look and perhaps submit a PR to note this if it doesn't exist.
