### ISSUE TITLE
Frigate detection process pinning CPU while TPU is working 

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#1442]
hiya!

So my Frigate does detect my TPU - but somehow when I check ``htop`` my CPU is still getting pinned by frigate. 

OS ubuntu server 20.04LTS
Intel(R) Xeon(R) CPU E31270 @ 3.40GHz
NVIDIA GTX 1050TI for image processing

```
detectors:
  coral:
    type: edgetpu
    device: USB
```

#config:

```
```cameras:


  back:
    zones:
      zone_0:
        coordinates: 2560,45,2537,1375,2171,1350,1802,1324,1786,1440,0,1440,0,728,1358,34
    motion:
      mask:
        - 1805,1440,2560,1440,2560,1298,1801,1305
        - 227,0,0,287,0,133,0,0,48,0,411,0
        - 0,0,787,0,1847,0,1367,34,1276,60,496,141,169,301,0,382
        - 2249,555,2241,57,2108,51,2127,545
        - 1523,276,1539,268,1582,216,1458,178,1398,0,1293,33,1355,219
        - 0,1440,704,1440,937,1203,704,1124,518,1070
        - 0,732,185,602,365,1079,0,1390
    mqtt:
      bounding_box: True
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtmp://192.168.178.113/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=XXXX
          roles:
            #- record
            - detect
            - rtmp
            - clips
    width: 2560
    height: 1440
    fps: 5
    clips:
      enabled: True
      pre_capture: 10
      post_capture: 20
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True

   

  front:
    zones:
      voordeur:
        coordinates: 1280,398,826,720,0,720,0,470,124,483,499,454,515,252,806,0,1280,0
    motion:
      mask:
        - 311,720,259,210,342,130,760,127,921,79,936,0,0,0,0,720
        - 311,720,257,202,341,0,0,0,0,720
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts
        - -use_wallclock_as_timestamps
        - '1'
        - -rtsp_transport
        - tcp

      output_args:
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
        rtmp:  -c copy -f flv -c:a aac
      
      inputs:
        - path: rtsp://192.168.178.55:8554/unicast
          roles:
            #- record
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    clips:
      objects:
        - person
        - laptop
        - train
        - bus
        - bicycle
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False


detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: False




ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'
    - -c:v
    - h264_cuvid
  output_args:
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy 
    detect: -f rawvideo -pix_fmt yuv420p

objects:

  track:
#    - car
    - person
    - bicycle
#    - motorcycle
    - bus
    - train
#    - bird
#    - cat
    - dog
    - backpack
#    - umbrella
#    - handbag
#    - suitcase
#    - sports ball
    - skateboard
#    - bottle
#    - wine glass
#    - cup
#    - fork
    - knife
#    - spoon
#    - chair
#    - couch
#    - bed
#    - dining table
#    - toilet
#    - tv
    - laptop
#    - mouse
#    - remote
#    - keyboard
    - cell phone
#    - microwave
#    - oven
#    - toaster
#    - sink
#    - refrigerator
#    - book
#    - clock
#    - vase
#    - scissors
#    - teddy bear
##    - hair drier
#    - toothbrush  

clips:
  max_seconds: 240

  retain:
    default: 10
    objects:
      person: 15
   
motion:
  threshold: 40
  delta_alpha: 0.2
  frame_alpha: 0.2
  contour_area: 100
  ```
