### ISSUE TITLE
FileNotFoundError (0.9.0)

### ISSUE THREAD

**Issue by salleq** [blakeblackshear/frigate#1449]
**Describe the bug**
Live video output on GUI has crashed. Frigate still does something in the background as I can view even new recordings, but no new events and clips are created. Debug view is stuck showing the time of crash on all the cameras, live view shows only blank. Frigate only recovers with a restart.

**Version of frigate**
0.9.0-50f0c05

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: x.x.x.x
  user: xxxx
  password: yyyy
cameras:
  back:
    ffmpeg:
      hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      inputs:
        - path: rtmp:/x.x.x.x/bcs/channel0_main.bcs?channel=0&stream=0
          roles:
            - clips
            - detect
            - record
      output_args:
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 2560
    height: 1920
    fps: 5
    record:
      enabled: true
      retain_days: 1
    motion:
      mask:
        - 223,105,247,736,302,724,317,615,938,470,1287,585,1457,664,1532,715,1414,857,1450,1167,1207,1311,1647,1771,2000,1481,2356,1713,2166,1920,2560,1920,2560,0,323,0,191,0,0,0,0,172,123,147
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        bird:
          max_area: 112000
          threshold: 0.79
        person:
          min_area: 112000
        cat:
          max_area: 112000
          threshold: 0.79
        dog:
          max_area: 112000
          threshold: 0.79
    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 500
    live:
      height: 720
      quality: 8
  front:
    ffmpeg:
      hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      inputs:
        - path:  rtmp://x.x.x.x/bcs/channel0_main.bcs?channel=0&stream=0
          roles:
            - clips         
            - detect
            - record
      output_args:
          clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
          record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 2560
    height: 1920
    fps: 5
    record:
      enabled: true
      retain_days: 1
    motion:
      mask:
        - 2560,398,2560,0,0,0,0,446
        - 1539,1920,2364,1920,2560,1920,2560,1654,2239,1920,1630,1920,1744,1384,1006,1404,912,1920
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        bird:
          max_area: 112000
          threshold: 0.79
        person:
          min_area: 112000
          threshold: 0.79
        cat:
          max_area: 112000
          threshold: 0.79
        dog:
          max_area: 112000
          threshold: 0.79
    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 500
    live:
      height: 720
      quality: 8

  living:
    ffmpeg:
      hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
      inputs:
        - path:  rtsp://x.x.x.x:554/Streaming/Channels/101/
          roles:
            - clips
            - detect 
    width: 1920
    height: 1080
    fps: 5
    motion:
      mask:
      - 167,907,137,525,130,233,379,235,377,351,1920,414,1920,0,327,0,168,0,85,0,0,0,0,360,0,1080,139,1080
    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 500
    snapshots:
      bounding_box: true
      crop: False
    live:
      height: 720
      quality: 8

  guest:
    ffmpeg:
      hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
      inputs:
        - path: rtsp://x.x.x.x:554/av_stream/ch0
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 5
    
  opticam:
    ffmpeg:
      hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
      inputs:
        - path: rtsp://x.x.x.x:554/videoMain
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    fps: 5
    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 500
    live:
      height: 720
      quality: 8
    
detectors:
  coral:
    type: edgetpu
    device: usb

clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 7
      dog: 5
      cat: 5
      bird: 5


```

**Frigate container logs**
```
Process output_processor:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/output.py", line 407, in output_frames
    if birdseye_manager.update(
  File "/opt/frigate/frigate/output.py", line 312, in update
    if self.update_frame() or (now - self.last_output_time) > 1:
  File "/opt/frigate/frigate/output.py", line 275, in update_frame
    self.copy_to_position(
  File "/opt/frigate/frigate/output.py", line 162, in copy_to_position
    frame = self.frame_manager.get(
  File "/opt/frigate/frigate/util.py", line 635, in get
    shm = shared_memory.SharedMemory(name=name)
  File "/usr/lib/python3.8/multiprocessing/shared_memory.py", line 102, in __init__
    self._fd = _posixshmem.shm_open(
FileNotFoundError: [Errno 2] No such file or directory: '/front1627484957.651159'
```

**Frigate stats**
```json

{"back":{"camera_fps":5.0,"capture_pid":245,"detection_fps":0.5,"pid":226,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.5,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.85,"pid":219}},"front":{"camera_fps":5.0,"capture_pid":246,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"living":{"camera_fps":5.0,"capture_pid":259,"detection_fps":0.0,"pid":235,"process_fps":5.0,"skipped_fps":0.0},"opticam":{"camera_fps":5.0,"capture_pid":263,"detection_fps":0.0,"pid":242,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":404.8,"mount_type":"tmpfs","total":536.9,"used":132.0},"/media/frigate/clips":{"free":375175.0,"mount_type":"ext4","total":491182.0,"used":90984.9},"/media/frigate/recordings":{"free":375175.0,"mount_type":"ext4","total":491182.0,"used":90984.9},"/tmp/cache":{"free":894.7,"mount_type":"tmpfs","total":1000.0,"used":105.3}},"uptime":235398,"version":"0.9.0-50f0c05"},"guest":{"camera_fps":5.1,"capture_pid":261,"detection_fps":0.0,"pid":240,"process_fps":0.0,"skipped_fps":0.0}}```


**Computer Hardware**
 - OS: Ubuntu
 - Install method: Docker-Compose
 - Coral Version: USB
 - Network Setup: Wired
