### ISSUE TITLE
Suggestion: Documentation Update shm size

### ISSUE THREAD

**Issue by somejavadev** [blakeblackshear/frigate#1486]
Currently one may specify the shm size when not using Home Assistant directly in the docker-compose file or docker command line arguments. May I suggest that this option is specified with the default value in the documentation to make the documentation the only place you have to look for updating the value without the need to go and search the docker documentation on how to do this.
  
Example 
  
docker-compose:   
  
```yml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:<specify_version_tag>
    shm_size: '64mb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <path_to_config_file>:/config/config.yml:ro
      - <path_to_directory_for_media>:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```     
docker command line:   
```bash
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --shm-size=64m \
  -v <path_to_directory_for_media>:/media/frigate \
  -v <path_to_config_file>:/config/config.yml:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='password' \
  -p 5000:5000 \
  -p 1935:1935 \
  blakeblackshear/frigate:<specify_version_tag>
```   
  
The downside to this may be that if the default docker shm size were to change the documentation would be incorrect or if the persons system were to use a different default shm size on their system it might be incorrect.   
   
Another option might be just to mention that it can be increased on the command line or compose file directly.
