### ISSUE TITLE
record with retain_days 7, old folders not being deleted

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1487]
I have setup record with retain_days:7 and it seem to be keeping 7 days files, but there are folder which is blank not deleted. As you can see from the pic below, from Aug 1 to 10 there are folders, only folder 3 to 10 have video recordings and 1 and 2 are empty folder.  Shouldn't it delete the folders too when cleaning up?

![image](https://user-images.githubusercontent.com/19213088/128862874-75da921b-0169-4772-9d12-cc948647ad27.png)

here is my config:
```
mqtt:
  host: 192.168.1.5
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

database:
  path: /media/frigate/clips/frigate.db

cameras:

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.13:8554/v3-outdoor
          roles:
            - detect
            - rtmp
            - record
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: true
      retain:
        default: 7
        objects:
          person: 7
          animal: 2
          vehicle: 2
    record:
      enabled: true
      retain_days: 7
```
