### ISSUE TITLE
Ability to retain previews outside of recording retention

### ISSUE THREAD

**Issue by jokke-ilujo** [blakeblackshear/frigate#14885]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have main stream and sub stream recorded with different retention rules so that I can have my sub stream which is used for detection also recorded continuously with long retention period while event based retention would apply to the high-res main stream. 

**Describe the solution you'd like**
Most user friendly option would be to create new record_*mode*[all, motion, active_objects] roles for inputs. This way the current behaviour would be simple to keep but would allow something like:
```
cameras:
  Camera1:
    ffmpeg:
      inputs:
        - path: <path to the stream>
          roles:
            - record_active_objects
            - audio
        - path: <path to the sub stream>
          roles:
            - detect
            - record_all
  ...
record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects
```

**Describe alternatives you've considered**
Creating duplicate cameras in separate group with only sub stream defined as path and separate recording config with it's own retention. This makes the config/ui messy and requires lots more effort each time changes happens to track them in multiple places.

Having input specified in the record config. That would require some way to identify stream types in the input list like:
```
cameras:
  Camera1:
    ffmpeg:
      inputs:
        - path: <path to the stream>
          stream: main
          roles:
            - record
            - audio
        - path: <path to the sub stream>
          stream: sub
          roles:
            - detect
            - record
  ...
record:
  enabled: true
  retain:
    days: 10
    mode: all
    stream: sub
  events:
    retain:
      default: 30
      mode: active_objects
      stream: main
```

**Additional context**
I can't be the only one who would like to have the low resolution sub stream recorded continuously/on motion with decent retention period just in case and get the high resolution clips for any highlighted events being it (motion or) object detection. This would save a lot of storage capacity and wear and tear as the low res sub stream takes significantly less space/io. The proposed solution with mode based roles would make it simple to address individual preferences which stream they would like to keep for different modes while the existing deployments would keep working with the simple 'record' role as it has so far.

Something to consider is if the community wants to support mixed config, so for example sub stream having 'record_all' role and main stream having 'record' (this would be catch all for any mode not specified in the camera config) role where defaults are applied. Or require either 'record' only role or all wanted modes defined within camera config, F.E.
```
- path: <sub stream>
  roles:
    - record_all
    - detect
- path: <main stream>
  roles:
"""
    - record_motion
    - record_active_objects
"""
vs
"""
    - record
"""
```

I'd be willing to try to find some cycles to help implement this if needed in case the feature would be considered.
