### ISSUE TITLE
[Bug]: ffprobe move atom not found

### ISSUE THREAD

**Issue by pdrobek** [blakeblackshear/frigate#14917]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/14916

<div type='discussions-op-text'>

<sup>Originally posted by **pdrobek** November 11, 2024</sup>
### Checklist

- [X] I have updated to the latest available Frigate version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [incognito mode](https://www.computerworld.com/article/1719851/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html) to rule out problems with any third party extensions or plugins I have installed.

### Describe the problem you are having

I cannot record anything with frigate. All segments recorded via frigate were discarded. If i record segment via ffmpeg from command line ffprobe not complaining. Video works fine

### Steps to reproduce

Occurs everytime

### Version

0.15.0-33825f6

### Frigate config file

```yaml
database:
  path: /db/frigate.db
detectors:
  cpu:
    type: cpu
    num_threads: 4
ffmpeg:
  hwaccel_args: auto
  retry_interval: 60
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
objects:
  track:
    - person
record:
  preview:
    quality: very_high
  alerts:
    retain: {}
    pre_capture: 7
    post_capture: 10
  detections:
    retain: {}
    pre_capture: 7
    post_capture: 10
logger:
  logs:
    frigate.record.maintainer: debug
live:
  quality: 2
cameras:
  kamera-kotlownia360:
    ffmpeg:
      input_args: -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://CREDENTIALS_REMOVED@IP_REMOVED/udp/av0_0
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
    snapshots:
      enabled: true
tls:
  enabled: false
version: 0.15-0
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "256mb"
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml
      - /opt/frigate/media:/media/frigate
      - /opt/frigate/storage:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
    group_add: 
      - '105'
```

### Relevant Frigate log output

```shell
2024-11-11 08:49:11.907433780  [ WARN:0@237.041] global cap_ffmpeg_impl.hpp:1167 open Unable to read codec parameters from stream (Invalid data found when processing input)
2024-11-11 08:50:11.978757342  [2024-11-11 08:50:11] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/kamera-kotlownia360@20241111084957+0000.mp4
2024-11-11 08:52:12.081420037  [2024-11-11 08:52:12] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/kamera-kotlownia360@20241111085157+0000.mp4
2024-11-11 08:51:42.056197600  [2024-11-11 08:51:42] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/kamera-kotlownia360@20241111085129+0000.mp4

root@8414cdf418e3:/opt/frigate# /usr/lib/ffmpeg/7.0/bin/ffprobe /tmp/cache/kamera-kotlownia360\@20241111090517+0000.mp4                                                                                                                      ffprobe version n7.0.2-18-g3e6cec1286-20240919 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.0 (crosstool-NG 1.26.0.106_ed12fa6)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-openssl --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs='-ldl -lgomp' --extra-ldflags=-pthread --extra-ldexeflags=-pie --cc=x86_64-ffbuild-linux-gnu-gcc --cxx=x86_64-ffbuild-linux-gnu-g++ --ar=x86_64-ffbuild-linux-gnu-gcc-ar --ranlib=x86_64-ffbuild-linux-gnu-gcc-ranlib --nm=x86_64-ffbuild-linux-gnu-gcc-nm --extra-version=20240919
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
**[mov,mp4,m4a,3gp,3g2,mj2 @ 0x560ab0021600] moov atom not found**
/tmp/cache/kamera-kotlownia360@20241111090517+0000.mp4: Invalid data found when processing input
```

### Relevant go2rtc log output

```shell
i don't use it
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

orllo z10 (copy of vstarcam)

### Screenshots of the Frigate UI's System metrics pages

![Zrzut ekranu 2024-11-11 101939](https://github.com/user-attachments/assets/fcdb62ef-e4be-471d-921b-9e7903acc142)

### Any other information that may be helpful

_No response_</div>
