### ISSUE TITLE
Recordings being stored in /var/lib/docker/overlay2/<uuid>/diff/tmp

### ISSUE THREAD

**Issue by joeShuff** [blakeblackshear/frigate#1506]
**Describe the bug**
I've been running the beta builds of frigate to test stuff out and mainly to get rid of the issue #1331 and it went fine for a while. I switched to `blakeblackshear/frigate:0.9.0-8fd12f0-amd64` yesterday and since have seen my disk usage fire up to 100% filled. 

After some `du` rummaging I found 50GB of what is my recordings in the directory `/var/lib/docker/overlay2/<uuid>/diff/tmp` and I see no recordings in the frigate UI or the dedicated storage area. 
**Version of frigate**
0.9.0-8fd12f0

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: ip
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <redacted>
  password: <redacted>
  stats_interval: 60
cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - rtmp
            - detect
            - clips
            - record
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 1920
    height: 1080
    fps: 5
    clips:
      enabled: true
      pre_capture: 3
      post_capture: 3
      objects:
        - person
        - cat
      retain:
        default: 10
        objects:
          person: 14
    record:
      enabled: true
      retain_days: 3
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
        objects:
          person: 14
    objects:
      track:
        - person
        - cat
    zones:
      back_door_zone:
        coordinates: 1774,289,1569,799,1176,624,1230,172
    motion:
      mask:
        - 1376,64,1920,61,1920,0,1376,0
  front_bedroom:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - rtmp
            - detect
            - clips
            - record
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 1920
    height: 1080
    fps: 5
    clips:
      enabled: true
      pre_capture: 3
      post_capture: 3
      objects:
        - person
        - cat
      retain:
        default: 10
        objects:
          person: 14
    record:
      enabled: true
      retain_days: 3
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
        objects:
          person: 14
    objects:
      track:
        - person
        - cat
    motion:
      mask:
        - 1920,0,1920,69,1373,70,1372,0
  back_bedroom:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - rtmp
            - clips
            - record
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 2560
    height: 1920
    fps: 5
    clips:
      enabled: true
      pre_capture: 3
      post_capture: 3
      objects:
        - person
        - cat
      retain:
        default: 7
        objects:
          person: 7
    record:
      enabled: true
      retain_days: 3
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
        objects:
          person: 14
    objects:
      track:
        - person
        - cat    
    motion:
      mask:
        - 1657,0,1662,76,906,72,900,0  
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  mode: continuous
  height: 1080
  width: 1920
```

**Frigate container logs**
I don't see anything specific to recording, but there was a lot of this that I haven't seen before. Just lots of usual `ffmpeg sent a broken frame` which I've seen before and its never been an issue. I can post more logs if needed.

```
[2021-08-12 23:29:13] ffmpeg.living_room.detect      ERROR   : [segment @ 0x560229712700] Non-monotonous DTS in output stream 0:0; previous: 2689, current: 2689; changing to 2690. This may result in incorrect timestamps in the output file.
[2021-08-12 23:29:13] ffmpeg.living_room.detect      ERROR   : [segment @ 0x560229712700] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2021-08-12 23:29:13] ffmpeg.living_room.detect      ERROR   : [flv @ 0x5602296dd3c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2021-08-12 23:29:13] ffmpeg.living_room.detect      ERROR   : [segment @ 0x560229712700] Non-monotonous DTS in output stream 0:0; previous: 135570921, current: 135570921; changing to 135570922. This may result in incorrect timestamps in the output file.
[2021-08-12 23:29:13] ffmpeg.living_room.detect      ERROR   : [flv @ 0x5602296dd3c0] Failed to update header with correct duration.
```

**Frigate stats**
```
{
    "back_bedroom": {
        "camera_fps": 5.0,
        "capture_pid": 237,
        "detection_fps": 0.0,
        "pid": 225,
        "process_fps": 0.0,
        "skipped_fps": 0.0
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 10.0,
            "pid": 218
        }
    },
    "front_bedroom": {
        "camera_fps": 5.0,
        "capture_pid": 232,
        "detection_fps": 0.0,
        "pid": 224,
        "process_fps": 0.0,
        "skipped_fps": 0.0
    },
    "living_room": {
        "camera_fps": 5.0,
        "capture_pid": 227,
        "detection_fps": 0.0,
        "pid": 223,
        "process_fps": 0.0,
        "skipped_fps": 0.0
    },
    "service": {
        "storage": {
            "/dev/shm": {
                "free": 254.3,
                "mount_type": "tmpfs",
                "total": 268.4,
                "used": 14.1
            },
            "/media/frigate/clips": {
                "free": 52696.0,
                "mount_type": "ext4",
                "total": 121029.6,
                "used": 62141.5
            },
            "/media/frigate/recordings": {
                "free": 52696.0,
                "mount_type": "ext4",
                "total": 121029.6,
                "used": 62141.5
            },
            "/tmp/cache": {
                "free": 52696.0,
                "mount_type": "overlay",
                "total": 121029.6,
                "used": 62141.5
            }
        },
        "uptime": 60,
        "version": "0.9.0-8fd12f0"
    }
}
```

**Computer Hardware**
 - OS: Debian
 - Install method: Docker compose
 - Virtualization: 
 - Coral Version: Usb
 - Network Setup: Wired
