### ISSUE TITLE
5fps cap: "Displaying at 5.0fps"

### ISSUE THREAD

**Issue by lukedukeus** [blakeblackshear/frigate#1514]
**Describe the bug**
Frigate won't display more than 5fps

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: yes
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: yes
  password: yes
  stats_interval: 60

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.1.70/cam4/mpeg4
          roles:
            - detect
            - rtmp
    width: 2592
    height: 1944
    fps: 30
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.coral                 INFO    : Starting detection process: 53
frigate.app                    INFO    : Camera processor started for front_door: 56
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Capture process started for front_door: 71
frigate.edgetpu                INFO    : TPU found
```

**Screenshots**
![stuck at 5fps](https://user-images.githubusercontent.com/23089287/129431775-3c30589b-3afb-4d07-85a3-55c71f5019b9.JPG)

**Computer Hardware**
 Intel nuc, also happens on my laptop

**Camera Info:**
 - Manufacturer: JideTech
 - Model: P1-4X-5MP
 - Resolution: 2592x1944
 - FPS: 30
