### ISSUE TITLE
MQTT Traceback Error

### ISSUE THREAD

**Issue by karldonteljames** [blakeblackshear/frigate#152]
I've got an issue that when i'm trying to start the docker in unraid I get the following error in my log file and it fails to start:

```
Traceback (most recent call last):
File "detect_objects.py", line 34, in <module>
MQTT_PASS = MQTT_PASS.format(**FRIGATE_VARS)
ValueError: Single '}' encountered in format string
```

My config.yml starts like this:

```
mqtt:
  host: 192.168.12.201
  topic_prefix: 'frigate'
  user: 'MyMQTTUserName'
  password: 'MyRandomSecurePassword'
```

**Comment by blakeblackshear** [comment]
Any chance you have a `}` in your password?

**Comment by karldonteljames** [comment]
yup! I'm hoping i'm not going to have to change the password, SOOOO many mqtt devices.

**Comment by blakeblackshear** [comment]
Try passing the password as an environment variable called `FRIGATE_MQTT_PASSWORD` and update your config to:
```
mqtt:
  host: 192.168.12.201
  topic_prefix: 'frigate'
  user: 'MyMQTTUserName'
  password: '{FRIGATE_MQTT_PASSWORD}'
```
