### ISSUE TITLE
Clips are not recording

### ISSUE THREAD

**Issue by cjmccoy2** [blakeblackshear/frigate#1526]
**Describe the bug**
Clips are showing up, but appear to be 0 seconds long. Snapshots are working correctly

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: mqttip
  user: user
  password: pass
  
cameras:
  frontyard:
    ffmpeg:
      inputs:
        - path: inserthere
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    clips:
      enabled: true
      retain:
        default: 2

detectors:
  cpu1:
    type: cpu
    
```

**Screenshots**
<img width="1472" alt="Screen Shot 2021-08-15 at 8 00 13 PM" src="https://user-images.githubusercontent.com/88991771/129496640-d8a6334b-d6b9-46c2-a217-55c6b40d237d.png">

**Camera Info:**
Lorex
