### ISSUE TITLE
First hour of recordings missing each day

### ISSUE THREAD

**Issue by D3v01dZA** [blakeblackshear/frigate#1529]
**Describe the bug**
I've been testing out Frigate in my setup and as such only have one camera for now, I was just browsing in Home Assistant and found that there are no recordings for 00:00 - 01:00, the day before records from 23:00 - 00:00 and the next day from 01:00 - 02:00 but when I go into the folder for 00:00 - 01:00 there is no camera listed (in other folders I can go in to 

**Version of frigate**
0.8.4-5043040 (Specifically the Nvidia container)

**Config file**
Include your full config file wrapped in triple back ticks.
```
detectors:
  cpu:
    type: cpu
    num_threads: 6

ffmpeg:
  input_args:
    - -c:v
    - h264_cuvid

record:
  enabled: true
  retain_days: 7

cameras:
  doorbell_camera:
    ffmpeg:
      inputs:
        - path: <blanked>
          roles:
            - detect
            - rtmp
            - clips
            - record
    width: 1920
    height: 1080
    fps: 25
    motion:
      mask:
        - 0,1080,759,1080,766,1053,764,1024,733,965,657,942,692,877,879,932,955,983,1010,1080,1920,1080,1920,0,0,0
```

**Frigate container logs**
```
No obvious relevant logs, there are some errors like this however:
ffmpeg.doorbell_camera.detect  ERROR   : [segment @ 0x55cba120c140] Non-monotonous DTS in output stream 0:0; previous: 633082860, current: 633082680; changing to 633082861. This may result in incorrect timestamps in the output file.
```

**Frigate stats**
```
{
  "detection_fps": 0.0, 
  "detectors": {
    "cpu": {
      "detection_start": 0.0, 
      "inference_speed": 39.66, 
      "pid": 76
    }
  }, 
  "doorbell_camera": {
    "camera_fps": 24.9, 
    "capture_pid": 80, 
    "detection_fps": 0.0, 
    "pid": 79, 
    "process_fps": 24.9, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 2143.8, 
        "mount_type": "tmpfs", 
        "total": 2147.5, 
        "used": 3.7
      }, 
      "/media/frigate/clips": {
        "free": 6906006.4, 
        "mount_type": "ext4", 
        "total": 7937383.5, 
        "used": 631283.0
      }, 
      "/media/frigate/recordings": {
        "free": 6906006.4, 
        "mount_type": "ext4", 
        "total": 7937383.5, 
        "used": 631283.0
      }, 
      "/tmp/cache": {
        "free": 3990.8, 
        "mount_type": "tmpfs", 
        "total": 4000.0, 
        "used": 9.2
      }
    }, 
    "uptime": 172999, 
    "version": "0.8.4-5043040"
  }
}

```

**Screenshots**
Its kind of hard to grab a screenshot since it would require quite a bit of context (HA's media browser doesn't have breadcrumbs to show you where you are in the hierarchy which would help a lot here)
