### ISSUE TITLE
Mixed stream when adding more than two cameras

### ISSUE THREAD

**Issue by finalbillybong** [blakeblackshear/frigate#1530]
**Describe the bug**
When adding more than two cameras the camera preview stream are 'mixed up' the preview will flick between the camera it is supposed to show and a random other camera that is connected. 

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: 192.168.0.238
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: mqtt
  stats_interval: 60
cameras:
  front_door:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://****:****@192.168.0.222/h264Preview_02_sub
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
    width: 640
    height: 360
    fps: 5
  driveway:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://****:****@192.168.0.222/h264Preview_01_sub
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
    width: 640
    height: 360
    fps: 5
  oil_cam:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://****:****@192.168.0.222/h264Preview_03_sub
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
    width: 640
    height: 360
    fps: 5
  alley_cam:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://****:****@192.168.0.222/h264Preview_04_sub
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
    width: 640
    height: 360
    fps: 5
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 46
frigate.app                    INFO    : Camera processor started for front_door: 49
frigate.app                    INFO    : Camera processor started for driveway: 50
frigate.app                    INFO    : Capture process started for front_door: 51
frigate.app                    INFO    : Capture process started for driveway: 54
```

**Frigate stats**
```json
{
  "cameras": {
    "driveway": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:Nofear1809@192.168.0.222/h264Preview_01_sub -c copy -f flv rtmp://127.0.0.1/live/driveway -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "fps": 5,
      "frame_shape": [
        360,
        640
      ],
      "height": 360,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 60,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "driveway",
      "objects": {
        "filters": {
          "car": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": null,
        "track": [
          "person",
          "car",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": true,
        "height": 175,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "width": 640,
      "zones": {}
    },
    "front_door": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:Nofear1809@192.168.0.222/h264Preview_02_sub -c copy -f flv rtmp://127.0.0.1/live/front_door -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "fps": 5,
      "frame_shape": [
        360,
        640
      ],
      "height": 360,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 60,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_door",
      "objects": {
        "filters": {
          "car": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": null,
        "track": [
          "person",
          "car",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": true,
        "height": 175,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "width": 640,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.0.238",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "mqtt"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Computer Hardware**
 - OS: Home Assistant x64 Image
 - Install method: Addon

 - Coral Version: None
 - Network Setup: Home Assistant - Wired Reolink NVR - Wired

**Camera Info:**
 - Manufacturer: Reolink NVR
 - Model: RLK8-810B4-A 
 - Resolution: 640x360
 - FPS: 5
