### ISSUE TITLE
FFmpeg accell  - how to check? (general or in container/nvidia)

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#1535]
**Describe the bug**
i want rtsp h265 convert to h264 for clips. With HW-accel in the nvidia-container of frigate.
simple conversion throws error. looks like no hw-acces for me. how do i verify?

**Version of frigate**
Output from `/api/version`: 0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint

{
  "cat-hilook-132": {
    "camera_fps": 5.0, 
    "capture_pid": 59, 
    "detection_fps": 4.3, 
    "pid": 43, 
    "process_fps": 0.7, 
    "skipped_fps": 0.0
  }, 
  "cat-kueche-130": {
    "camera_fps": 5.0, 
    "capture_pid": 51, 
    "detection_fps": 4.5, 
    "pid": 40, 
    "process_fps": 0.5, 
    "skipped_fps": 0.0
  }, 
  "cat-kueche-133": {
    "camera_fps": 5.0, 
    "capture_pid": 55, 
    "detection_fps": 4.5, 
    "pid": 42, 
    "process_fps": 0.6, 
    "skipped_fps": 0.0
  }, 
  "cat-schlaf-83": {
    "camera_fps": 5.1, 
    "capture_pid": 63, 
    "detection_fps": 4.3, 
    "pid": 47, 
    "process_fps": 0.6, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 17.6, 
  "detectors": {
    "cpu1": {
      "detection_start": 1629182034.465492, 
      "inference_speed": 108.07, 
      "pid": 36
    }, 
    "cpu2": {
      "detection_start": 1629182034.523512, 
      "inference_speed": 115.11, 
      "pid": 37
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 950.9, 
        "mount_type": "tmpfs", 
        "total": 1073.7, 
        "used": 122.8
      }, 
      "/media/frigate/clips": {
        "free": 198536.9, 
        "mount_type": "ext4", 
        "total": 244528.6, 
        "used": 33498.9
      }, 
      "/media/frigate/recordings": {
        "free": 198536.9, 
        "mount_type": "ext4", 
        "total": 244528.6, 
        "used": 33498.9
      }, 
      "/tmp/cache": {
        "free": 509776.9, 
        "mount_type": "tmpfs", 
        "total": 512000.0, 
        "used": 2223.1
      }
    }, 
    "uptime": 1230, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>


root@357f8de0d7b3:/opt/frigate# ffprobe rtsp://admin:pass@192.168.14.83/Streaming/channels/101
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:pass@192.168.14.83/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
    Stream #0:0: Video: hevc, yuvj420p(pc, bt709), 2688x1520 [SAR 190:189 DAR 16:9], 15 fps, 25 tbr, 90k tbn, 15 tbc
root@357f8de0d7b3:/opt/frigate#
```

**Screenshots**

**Computer Hardware**
ubuntu
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

```
root@357f8de0d7b3:/opt/frigate# cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

root@ub20-frigate4:/usr/src# docker-compose --version
docker-compose version 1.29.2, build 5becea4c

root@ub20-frigate4:/usr/src# docker --version
Docker version 20.10.8, build 3967b7d
root@ub20-frigate4:/usr/src#


root@ub20-frigate4:/usr/src# cat docker-compose.yml
version: "3.9"
#version: "3.8"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    #restart: unless-stopped
    # restart: on-failure
    #restart: no

    ## image: blakeblackshear/frigate:<specify_version_tag>
    # normal
    #image: blakeblackshear/frigate:stable-amd64
    # nvidia
    image: blakeblackshear/frigate:stable-amd64nvidia
    runtime: nvidia
#    build:
#      shm_size: '2G'
#      context: .
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/src/frigate.yml:/config/config.yml:ro
      - /usr/src/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 512000000000    # ~64gb     shmz?
          #size: 16000000000 # ~16gb
          #size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      #FRIGATE_RTSP_PASSWORD: "password"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video

    #environment:


      #- <path_to_config_file>:/config/config.yml:ro
      #- <path_to_directory_for_media>:/media/frigate
```

**Camera Info:**
hikviison
DS-2CD2045FWD-I
V5.6.5 build 200316

**Additional context**
nvidia-smi seems to work inside containter. 
```
docker exec -it frigate /bin/bash

```
check from nvidia hints working: https://developer.nvidia.com/blog/nvidia-ffmpeg-transcoding-guide/
```
root@357f8de0d7b3:/opt/frigate# nvidia-smi -q -d UTILIZATION

==============NVSMI LOG==============

Timestamp                                 : Tue Aug 17 07:55:16 2021
Driver Version                            : 470.63.01
CUDA Version                              : 11.4

Attached GPUs                             : 1
GPU 00000000:01:00.0
    Utilization
        Gpu                               : 11 %
        Memory                            : 3 %
        Encoder                           : 10 %
        Decoder                           : 12 %
    GPU Utilization Samples
        Duration                          : 99.23 sec
        Number of Samples                 : 99
        Max                               : 11 %
        Min                               : 9 %
        Avg                               : 10 %
    Memory Utilization Samples
        Duration                          : 99.23 sec
        Number of Samples                 : 99
        Max                               : 3 %
        Min                               : 3 %
        Avg                               : 3 %
    ENC Utilization Samples
        Duration                          : 99.23 sec
        Number of Samples                 : 99
        Max                               : 11 %
        Min                               : 9 %
        Avg                               : 9 %
    DEC Utilization Samples
        Duration                          : 99.23 sec
        Number of Samples                 : 99
        Max                               : 12 %
        Min                               : 11 %
        Avg                               : 11 %

root@357f8de0d7b3:/opt/frigate#
```

simple cmd-line throws error. i dont find the right params for frigate clips output.

inside the containter test (hw-accel output?) cmd-line show no hw-support (?!):
```
root@357f8de0d7b3:/opt/frigate#  ffmpeg -rtsp_transport tcp -i rtsp://admin:pass@192.168.14.83/Streaming/channels/101 -c:v h264_nvenc -b:v 2M  /tmp/cache/cat-schlaf-83-%Y%m%d%H%M%S.mp4
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:pass@192.168.14.83/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
    Stream #0:0: Video: hevc, yuvj420p(pc, bt709), 2688x1520 [SAR 190:189 DAR 16:9], 15 fps, 25 tbr, 90k tbn, 15 tbc
File '/tmp/cache/cat-schlaf-83-%Y%m%d%H%M%S.mp4' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[swscaler @ 0x560d36540b00] deprecated pixel format used, make sure you did set range correctly
[h264_nvenc @ 0x560d3618d4c0] OpenEncodeSessionEx failed: out of memory (10): (no details)
[h264_nvenc @ 0x560d3618d4c0] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
root@357f8de0d7b3:/opt/frigate# ^C
root@357f8de0d7b3:/opt/frigate#


another (hw input/output):

root@357f8de0d7b3:/opt/frigate#  ffmpeg -hwaccel cuda -hwaccel_output_format cuda -rtsp_transport tcp -i rtsp://admin:pass@192.168.14.83/Streaming/channels/101 -c:v h264_nvenc -b:v 5M  /tmp/cache/cat-schlaf-83-%Y%m%d%H%M%S.mp4
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:pass@192.168.14.83/Streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
    Stream #0:0: Video: hevc, yuvj420p(pc, bt709), 2688x1520 [SAR 190:189 DAR 16:9], 15 fps, 25 tbr, 90k tbn, 15 tbc
File '/tmp/cache/cat-schlaf-83-%Y%m%d%H%M%S.mp4' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[h264_nvenc @ 0x5646ea145a00] OpenEncodeSessionEx failed: out of memory (10): (no details)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
root@357f8de0d7b3:/opt/frigate#
```

any hints/help appreciated. how to test conversion wiht hw-accel / hwaccel inside container?

---edit:
don know how to test pix-fmt from input to output, but is this a hint?
https://stackoverflow.com/questions/58660999/ffmpeg-nvenc-hevc-to-h264
