### ISSUE TITLE
[Errno 2] No such file or directory: '/dev/shm'

### ISSUE THREAD

**Issue by nickwild-999** [blakeblackshear/frigate#1537]
Although I have a working version of a frigate.yml file in config directory frigate does not see this when booting.

**Version of frigate**
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 192.168.1.64
  user: user
  password: pw
 
cameras:
  oil:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pw@192.168.1.84:554//h264Preview_01_main
          roles:
            - detect
            - clips
    width: 2560
    height: 1920
    fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    clips:
      enabled: true
      retain:
        default: 7
        
  house:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pw@192.168.1.88:554//h264Preview_01_main
          roles:
            - detect
            - clips
    width: 2560
    height: 1920
    fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
    clips:
      enabled: true
      retain:
        default: 7
        
detectors:
  cpu1:
    type: cpu
    
    



```

**Frigate container logs**

```
* Starting nginx nginx
   ...done.
Error parsing config: [Errno 2] No such file or directory: '/dev/shm'
```

**Computer Hardware**
 - OS: ADM on Asustor
 - Install method: Addon, 
 - Virtualization: Docker
 - Coral Version: None
 - Network Setup: Wired
