### ISSUE TITLE
Can't set the correct RTSP connection string

### ISSUE THREAD

**Issue by MrksHfmn** [blakeblackshear/frigate#1541]
**Describe the bug**
I would like to integrate my webcam (Ezviz) into Frigate. Unfortunately I fail to define the RTSP stream correctly.
Normally I would be able to call the stream with this string: rtsp://admin:password@192.168.1.140/h264_stream

Am I missing any settings in config.yml? I see unfortunately only a green image in the web interface and after some time the container crashes ...

**Computer Hardware**
 - OS: Debian 11
 - Install method: Docker Compose
 - Virtualization: no
 - Coral Version: None
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: EZVIZ
 - Model: CS-CSV206
 - Resolution: 1080p
 - FPS: 29,9

**Frigate container logs**
```
root@HOME-SERVER:[frigate]> docker-compose down --remove-orphans && docker-compose up
Removing frigate ... done
Creating frigate ... done
Attaching to frigate
frigate    |  * Starting nginx nginx
frigate    |    ...done.
frigate    | Starting migrations
frigate    | peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | peewee_migrate                 INFO    : There is nothing to migrate
frigate    | frigate.mqtt                   INFO    : MQTT connected
frigate    | detector.coral                 INFO    : Starting detection process: 36
frigate    | frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | frigate.app                    INFO    : Camera processor started for Arbeitszimmer: 39
frigate    | Process detector:coral:
frigate    | frigate.edgetpu                INFO    : No EdgeTPU detected.
frigate    | frigate.app                    INFO    : Capture process started for Arbeitszimmer: 40
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
frigate    |     delegate = Delegate(library, options)
frigate    |   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
frigate    |     raise ValueError(capture.message)
frigate    | ValueError
frigate    |
frigate    | During handling of the above exception, another exception occurred:
frigate    |
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
frigate    |     object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
frigate    |     edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
frigate    |   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
frigate    |     raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate    | ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate    |
frigate    | frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | frigate.app                    INFO    : Stopping...
frigate    | frigate.events                 INFO    : Exiting event processor...
frigate    | frigate.record                 INFO    : Exiting recording maintenance...
frigate    | frigate.object_processing      INFO    : Exiting object processor...
frigate    | frigate.events                 INFO    : Exiting event cleanup...
frigate    | frigate.watchdog               INFO    : Exiting watchdog...
frigate    | frigate.stats                  INFO    : Exiting watchdog...
frigate    | peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate    | root                           INFO    : Waiting for detection process to exit gracefully...
```

**docker-compose.yaml**
```
---
version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/frigate/config.yml:/config/config.yml:ro
      - /mnt/storage/docker/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000  # 1GB
    network_mode: host
```

**Config file**
```
---
mqtt:
  host: 192.168.1.100
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: *****

cameras:
  Arbeitszimmer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.140:554/H.264
          roles:
            - detect
            - rtmp
    width: 1980
    height: 1080
    fps: 5
    best_image_timeout: 60
```

**FFprobe from your camera**

```
 ./ffprobe rtsp://admin:password@192.168.1.140:554/H.264
ffprobe version 4.4-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

**Comment by itkfilelor** [comment]
I had this issue initially as well. Does your RTSP password or username contain any special characters? e.g. (?!@#$).
You may need to either escape them with a forward slash '\' (eg \! \@) or use single quotes (') around the password. I forget which worked as I ended up changing my passwords to a gigantic string of random words :nerd_face:

**Comment by MrksHfmn** [comment]
> I had this issue initially as well. Does your RTSP password or username contain any special characters? e.g. (?!@#$).
> You may need to either escape them with a forward slash '' (eg ! @) or use single quotes (') around the password. I forget which worked as I ended up changing my passwords to a gigantic string of random words 🤓

Thank you for the reply! The password consists of six capital letters and was set by the manufacturer ("ABCDEFG")

**Comment by MrksHfmn** [comment]
I had to add the detectors statement to get it working:

**Full config now**
```
---
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

mqtt:
  host: 192.168.1.100
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: mqtt

cameras:
  Arbeitszimmer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:ABCDEFG@192.168.1.140:554/H.264
          roles:
            - detect
            - rtmp
    height: 1080
    width: 1920
    fps: 5

```
