### ISSUE TITLE
Unstable

### ISSUE THREAD

**Issue by michaelmadsen72** [blakeblackshear/frigate#1543]
**Describe the bug**
A clear and concise description of what your issue is.

**Version of frigate**
Output from `/api/version`
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.1.30
  user: <mqtt-user>
  password: <mqtt-password>

cameras:
  indkoersel:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.2:7447/WJ3Q2PMIyjdbD5uV
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    clips:
      enabled: true
      retain:
        default: 5
  baghave:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.2:7447/EUMvzaWw6GHQOV4M
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 5    
    objects:
      track:
        - person
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      retain:
        default: 5
    clips:
      enabled: true
      retain:
        default: 5

detectors:
  coral:
    type: edgetpu
    device: usb
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
{
  "baghave": {
    "camera_fps": 5.1, 
    "capture_pid": 47, 
    "detection_fps": 22.1, 
    "pid": 43, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 31.2, 
  "detectors": {
    "coral": {
      "detection_start": 1629221639.608801, 
      "inference_speed": 20.61, 
      "pid": 38
    }
  }, 
  "indkoersel": {
    "camera_fps": 5.0, 
    "capture_pid": 45, 
    "detection_fps": 9.1, 
    "pid": 41, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 4084.8, 
        "mount_type": "tmpfs", 
        "total": 4095.2, 
        "used": 10.3
      }, 
      "/media/frigate/clips": {
        "free": 48371.6, 
        "mount_type": "ext4", 
        "total": 58327.1, 
        "used": 7556.4
      }, 
      "/media/frigate/recordings": {
        "free": 48371.6, 
        "mount_type": "ext4", 
        "total": 58327.1, 
        "used": 7556.4
      }, 
      "/tmp/cache": {
        "free": 4059.1, 
        "mount_type": "tmpfs", 
        "total": 4095.2, 
        "used": 36.0
      }
    }, 
    "uptime": 104, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
I have no idea how to do this :-(
```

**Screenshots**

**Computer Hardware**
 - OS: Home Assistant OS 6.2
 - Install method: Addon
 - Virtualization: none
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Ubiquiti
 - Model: UVC‑G3 Flex
 - Resolution: 1080p
 - FPS: 15

**Additional context**
After running for a while, Home Assistant becomes unresponsive. I have tried disabling Frigate and then Home Assistant runs stable for several days.
