### ISSUE TITLE
Time is sliding

### ISSUE THREAD

**Issue by brettjenkins** [blakeblackshear/frigate#155]
Hey,

I've noticed that after a few hours the camera feed seems to slip behind now, often by 20 seconds, so when watching via :5000 I'm seeing things that happened 20 seconds ago, and notifications are delayed etc.

I feel like this is best summed up by this screenshot, with the camera time underneath and the frigate time on top - note that when frigate is first started, these times match:

![image](https://user-images.githubusercontent.com/1395855/86642265-ae35fd80-bfd3-11ea-885d-97df2f021911.png)

This is my config:

```
web_port: 5000

mqtt:
  host: MQTTHOST
  topic_prefix: frigate
  # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
  user: MQTTUSER # Optional
  #################
  ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  ##   password: '{FRIGATE_MQTT_PASSWORD}'
  #################
  password: MQTTPASS # Optional

#ffmpeg: (commented this out when debugging this issue)
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

objects:
  track:
    - person
    - car
    #- truck
  filters:
    person:
      threshold: 0.70
    car:
      threshold: 0.70


cameras:
  driveway_frontdoor:
    ffmpeg:
      input: rtsp://URL1
    snapshots:
      show_timestamp: True
    take_frame: 3
    mask: driveway_frontdoor.bmp
  driveway_garage:
    ffmpeg:
      input: rtsp://URL2
    snapshots:
      show_timestamp: True
    take_frame: 3
    mask: driveway_garage.bmp
  side_shed:
    ffmpeg:
      input: rtsp://URL3
    mask: side_shed.bmp
    take_frame: 3
    snapshots:
      show_timestamp: True
    objects:
      track:
        - person
```

I have to use take_frame because my cameras aren't great at providing a separate feed at a decent resolution.

top is showing that the computer isn't overloaded at all:

![image](https://user-images.githubusercontent.com/1395855/86642747-0e2ca400-bfd4-11ea-9bbd-9712b67e0c70.png)

Just to add also using a Coral USB Stick

Any ideas?

Thanks!
