### ISSUE TITLE
[Support]: Error when connecting to NAS

### ISSUE THREAD

**Issue by Lulugaot** [blakeblackshear/frigate#15504]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/15499

<div type='discussions-op-text'>

<sup>Originally posted by **Lulugaot** December 13, 2024</sup>
### Describe the problem you are having

Cannot mount bind_frigate at /data/media/frigate because it is not empty

### Version

0.14.1

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xx.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxx-xxx
  password: xxxxxxxxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rpi-64-h265

record:
  enabled: true
  retain:
    days: 3
    mode: all

  events:
    retain:
      default: 3
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 3

cameras:
  Porch:
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 3
          mode: motion

    ffmpeg:
      hwaccel_args: preset-rpi-64-h265

      inputs:
        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record

      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask: 0.657,0.02,0.657,0.067,0.326,0.069,0.325,0.021
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      front_steps:
        coordinates: 
          0.488,0.989,0.491,0.752,0.591,0.764,0.669,0.744,0.692,0.647,0.77,0.647,0.993,0.988
        inertia: 3
        loitering_time: 0
        objects: person
      porch_street:
        coordinates: 
          0.016,0.513,0.109,0.294,0.312,0.236,0.463,0.23,0.592,0.239,0.679,0.604,0.439,0.578,0.217,0.554
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: front_steps
      detections:
        required_zones: porch_street
  Driveway:
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 3
          mode: motion

    ffmpeg:
      hwaccel_args: preset-rpi-64-h264

      inputs:
        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_02_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_02_main
          input_args: preset-rtsp-restream
          roles:
            - record

      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask: 0.324,0.064,0.658,0.066,0.657,0.02,0.323,0.02
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      front_walk:
        coordinates: 
          0.993,0.991,0.903,0.793,0.828,0.802,0.743,0.806,0.64,0.807,0.513,0.812,0.329,0.817,0.135,0.793,0.007,0.763,0.005,0.991
        inertia: 3
        loitering_time: 0
        objects: person
      driveway_street:
        coordinates: 
          0.844,0.747,0.581,0.755,0.292,0.752,0.009,0.712,0.007,0.289,0.273,0.23,0.455,0.222,0.658,0.242
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: front_walk
      detections:
        required_zones: driveway_street
version: 0.14
```

### Relevant Frigate log output

```shell
2024-12-13 16:24:09.700885922  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 16:24:09.700890793  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 51, bytestream 400376
2024-12-13 16:30:00.006102484  [h264 @ 0x7f4c1df5b0] error while decoding MB 110 71, bytestream -33
2024-12-13 16:56:56.290612448  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 16:56:56.290967709  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 58, bytestream 203924
2024-12-13 16:57:06.321384667  [h264 @ 0x7f4c284b90] left block unavailable for requested intra4x4 mode -1
2024-12-13 16:57:06.321392593  [h264 @ 0x7f4c284b90] error while decoding MB 0 75, bytestream 63789
2024-12-13 17:06:16.750117649  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:06:16.750124167  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 50, bytestream 278006
2024-12-13 17:15:07.203857256  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:15:07.203863201  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 64, bytestream 71244
2024-12-13 17:19:17.364064890  [h264 @ 0x7f4c284b90] left block unavailable for requested intra mode
2024-12-13 17:19:17.364073261  [h264 @ 0x7f4c284b90] error while decoding MB 0 55, bytestream 310459
2024-12-13 17:21:57.530280601  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:21:57.530290898  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 70, bytestream 20990
2024-12-13 17:43:58.602106493  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:43:58.602113289  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 53, bytestream 410564
2024-12-13 17:55:14.158724266  [h264 @ 0x7f4c284b90] left block unavailable for requested intra4x4 mode -1
2024-12-13 17:55:14.158728581  [h264 @ 0x7f4c284b90] error while decoding MB 0 46, bytestream 518253
2024-12-13 17:57:54.344854205  [h264 @ 0x7f4c1df5b0] error while decoding MB 126 77, bytestream -12
2024-12-13 17:59:34.429127931  [h264 @ 0x7f4c284b90] left block unavailable for requested intra mode
2024-12-13 17:59:34.429140709  [h264 @ 0x7f4c284b90] error while decoding MB 0 86, bytestream 30293
2024-12-13 18:01:24.515178803  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 18:01:24.515190062  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 65, bytestream 20957
2024-12-13 18:04:44.634362666  [h264 @ 0x7f4c284b90] left block unavailable for requested intra4x4 mode -1
2024-12-13 18:04:44.634370166  [h264 @ 0x7f4c284b90] error while decoding MB 0 53, bytestream 196345
2024-12-13 18:05:04.663886989  [h264 @ 0x7f4c284b90] left block unavailable for requested intra mode
2024-12-13 18:05:04.663891563  [h264 @ 0x7f4c284b90] error while decoding MB 0 62, bytestream 167460
2024-12-13 18:09:04.861509336  [h264 @ 0x7f4c284b90] cabac decode of qscale diff failed at 108 52
2024-12-13 18:09:04.861514595  [h264 @ 0x7f4c284b90] error while decoding MB 108 52, bytestream 371378
```

### Relevant go2rtc log output

```shell
2024-12-13 05:25:08.695026483  [INFO] Preparing new go2rtc config...
2024-12-13 05:25:08.741860095  [INFO] Got IP address from supervisor: 192.168.86.56
2024-12-13 05:25:08.782422119  [INFO] Got WebRTC port from supervisor: 8555
2024-12-13 05:25:09.435536759  [INFO] Starting go2rtc...
2024-12-13 05:25:09.553515235  00:25:09.553 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2
2024-12-13 05:25:09.553521013  00:25:09.553 INF config path=/dev/shm/go2rtc.yaml
2024-12-13 05:25:09.554018080  00:25:09.553 INF [rtsp] listen addr=:8554
2024-12-13 05:25:09.554250112  00:25:09.554 INF [api] listen addr=:1984
2024-12-13 05:25:09.554364119  00:25:09.554 INF [webrtc] listen addr=:8555/tcp
2024-12-13 05:25:18.350850758  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
Don't know how to do this. Cameras recording fine.
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
Running as an add-on integration in Home Assistant on my Pi5
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

_No response_</div>

[Skip to content](https://github.com/blakeblackshear/frigate/discussions/15499#start-of-content)
Navigation Menu

Code
Issues
128
[Support]: Error when connecting to NAS #15499
Unanswered
Lulugaot asked this question in General Support
[Support]: Error when connecting to NAS
#15499
@[Lulugaot](https://github.com/Lulugaot)
4 hours ago · 1 comments · 1 reply

Lulugaot
4 hours ago
Describe the problem you are having
Cannot mount bind_frigate at /data/media/frigate because it is not empty

Version
0.14.1

What browser(s) are you using?
No response

Frigate config file
mqtt:
  host: xxx.xxx.xx.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxx-xxx
  password: xxxxxxxxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rpi-64-h265

record:
  enabled: true
  retain:
    days: 3
    mode: all

  events:
    retain:
      default: 3
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 3

cameras:
  Porch:
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 3
          mode: motion

    ffmpeg:
      hwaccel_args: preset-rpi-64-h265

      inputs:
        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record

      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask: 0.657,0.02,0.657,0.067,0.326,0.069,0.325,0.021
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      front_steps:
        coordinates: 
          0.488,0.989,0.491,0.752,0.591,0.764,0.669,0.744,0.692,0.647,0.77,0.647,0.993,0.988
        inertia: 3
        loitering_time: 0
        objects: person
      porch_street:
        coordinates: 
          0.016,0.513,0.109,0.294,0.312,0.236,0.463,0.23,0.592,0.239,0.679,0.604,0.439,0.578,0.217,0.554
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: front_steps
      detections:
        required_zones: porch_street
  Driveway:
    detect:
      width: 640
      height: 360
      fps: 5
      enabled: true

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 3
          mode: motion

    ffmpeg:
      hwaccel_args: preset-rpi-64-h264

      inputs:
        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_02_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

        - path: rtsp://xxxxx:xxxxxxxxxxxxxxx@xxx.xxx.xx.xx:554/Preview_02_main
          input_args: preset-rtsp-restream
          roles:
            - record

      output_args:
        record: preset-record-generic-audio-aac

    motion:
      mask: 0.324,0.064,0.658,0.066,0.657,0.02,0.323,0.02
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      front_walk:
        coordinates: 
          0.993,0.991,0.903,0.793,0.828,0.802,0.743,0.806,0.64,0.807,0.513,0.812,0.329,0.817,0.135,0.793,0.007,0.763,0.005,0.991
        inertia: 3
        loitering_time: 0
        objects: person
      driveway_street:
        coordinates: 
          0.844,0.747,0.581,0.755,0.292,0.752,0.009,0.712,0.007,0.289,0.273,0.23,0.455,0.222,0.658,0.242
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: front_walk
      detections:
        required_zones: driveway_street
version: 0.14
Relevant Frigate log output
2024-12-13 16:24:09.700885922  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 16:24:09.700890793  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 51, bytestream 400376
2024-12-13 16:30:00.006102484  [h264 @ 0x7f4c1df5b0] error while decoding MB 110 71, bytestream -33
2024-12-13 16:56:56.290612448  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 16:56:56.290967709  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 58, bytestream 203924
2024-12-13 16:57:06.321384667  [h264 @ 0x7f4c284b90] left block unavailable for requested intra4x4 mode -1
2024-12-13 16:57:06.321392593  [h264 @ 0x7f4c284b90] error while decoding MB 0 75, bytestream 63789
2024-12-13 17:06:16.750117649  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:06:16.750124167  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 50, bytestream 278006
2024-12-13 17:15:07.203857256  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:15:07.203863201  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 64, bytestream 71244
2024-12-13 17:19:17.364064890  [h264 @ 0x7f4c284b90] left block unavailable for requested intra mode
2024-12-13 17:19:17.364073261  [h264 @ 0x7f4c284b90] error while decoding MB 0 55, bytestream 310459
2024-12-13 17:21:57.530280601  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:21:57.530290898  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 70, bytestream 20990
2024-12-13 17:43:58.602106493  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 17:43:58.602113289  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 53, bytestream 410564
2024-12-13 17:55:14.158724266  [h264 @ 0x7f4c284b90] left block unavailable for requested intra4x4 mode -1
2024-12-13 17:55:14.158728581  [h264 @ 0x7f4c284b90] error while decoding MB 0 46, bytestream 518253
2024-12-13 17:57:54.344854205  [h264 @ 0x7f4c1df5b0] error while decoding MB 126 77, bytestream -12
2024-12-13 17:59:34.429127931  [h264 @ 0x7f4c284b90] left block unavailable for requested intra mode
2024-12-13 17:59:34.429140709  [h264 @ 0x7f4c284b90] error while decoding MB 0 86, bytestream 30293
2024-12-13 18:01:24.515178803  [h264 @ 0x7f4c1df5b0] left block unavailable for requested intra mode
2024-12-13 18:01:24.515190062  [h264 @ 0x7f4c1df5b0] error while decoding MB 0 65, bytestream 20957
2024-12-13 18:04:44.634362666  [h264 @ 0x7f4c284b90] left block unavailable for requested intra4x4 mode -1
2024-12-13 18:04:44.634370166  [h264 @ 0x7f4c284b90] error while decoding MB 0 53, bytestream 196345
2024-12-13 18:05:04.663886989  [h264 @ 0x7f4c284b90] left block unavailable for requested intra mode
2024-12-13 18:05:04.663891563  [h264 @ 0x7f4c284b90] error while decoding MB 0 62, bytestream 167460
2024-12-13 18:09:04.861509336  [h264 @ 0x7f4c284b90] cabac decode of qscale diff failed at 108 52
2024-12-13 18:09:04.861514595  [h264 @ 0x7f4c284b90] error while decoding MB 108 52, bytestream 371378
Relevant go2rtc log output
2024-12-13 05:25:08.695026483  [INFO] Preparing new go2rtc config...
2024-12-13 05:25:08.741860095  [INFO] Got IP address from supervisor: 192.168.86.56
2024-12-13 05:25:08.782422119  [INFO] Got WebRTC port from supervisor: 8555
2024-12-13 05:25:09.435536759  [INFO] Starting go2rtc...
2024-12-13 05:25:09.553515235  00:25:09.553 INF go2rtc platform=linux/arm64 revision=b2399f3 version=1.9.2
2024-12-13 05:25:09.553521013  00:25:09.553 INF config path=/dev/shm/go2rtc.yaml
2024-12-13 05:25:09.554018080  00:25:09.553 INF [rtsp] listen addr=:8554
2024-12-13 05:25:09.554250112  00:25:09.554 INF [api] listen addr=:1984
2024-12-13 05:25:09.554364119  00:25:09.554 INF [webrtc] listen addr=:8555/tcp
2024-12-13 05:25:18.350850758  [INFO] Starting go2rtc healthcheck service...
FFprobe output from your camera
Don't know how to do this. Cameras recording fine.
Frigate stats
No response

Install method
HassOS Addon

docker-compose file or Docker CLI command
Running as an add-on integration in Home Assistant on my Pi5
Object Detector
Coral

Network connection
Wired

Camera make and model
Reolink

Screenshots of the Frigate UI's System metrics pages
No response

Any other information that may be helpful
No response

Replies:1 comment · 1 reply

NickM-27
3 hours ago
You'll need to follow https://docs.frigate.video/guides/ha_network_storage#move-current-data

1 reply 1 new
@Lulugaot
Lulugaot
2 hours ago
I went to the file editor and the only choices are (three dots) and you can - Download, Rename, Delete. How and where can you access and accomplish this in home assistant. Do you actually type this in the file editor when selecting config.yml ?
If you want to keep the current data
Move the frigate.db, frigate.db-shm, frigate.db-wal files to the /config directory
Rename the /media/frigate folder to /media/frigate_tmp
If you don't want to keep the current data
Delete the /media/frigate folder and all of its contents

How do you find or access these files and move them in Home Assistant ? Is it using the file editor or some other way to do this, sorry I'm lost. I'm fairly proficient with OS's ( MS-DOS, Windows, BSD, Linux since the Commodore etc. throughout the years). Started this YAML journey with HAOS first time on my Pi3 with the Frigate add -on July of 2024. Everything was running fine. Late September bought a new Pi5 and I re-installed everything, HA and Frigate to the Pi5. I Repurposed my Pi 3 with my first NAS ever using the OMV OS. Everything was running fine since. Two weeks ago bought a new Pi5 to use as my new OMV NAS , fresh install etc., formatting my existing NAS drives etc. There is no clear info as to where or how to access, or see exactly where these files are actually located and how this is accomplished step by step. I'm sorry maybe I'm asking too much. Thank you , much appreciated. My HA system drive is filling up.

Suggest an answer
Comment
 
Add your answer here...
 
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Category
#️⃣
[General Support](https://github.com/blakeblackshear/frigate/discussions/categories/general-support)
Labels
support
triage
2 participants
@Lulugaot
@NickM-27
Notifications
