### ISSUE TITLE
Allow configuring separate alerts/detections per zone

### ISSUE THREAD

**Issue by cryptk** [blakeblackshear/frigate#15556]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to define alerts and detections to a specific zone so that I can have different labels alerted/detected for different zones on the same camera

**Describe the solution you'd like**
Supporting a configuration such as this would achieve the goal:
```
cameras:
  front_yard:
    ...
    zones:
      driveway:
        coordinates: ...
        review:
          alerts:
            labels:
              - motorcycle
              - car
              - person
          detections:
            labels:
              - dog
              - cat
              - motorcycle
              - car
              - person
      street:
        coordinates: ...
        review:
          alerts:
            labels:
              - amazon
              - ups
              - fedex
          detections
            labels:
              - amazon
              - ups
              - fedex
              - person
```

Currently with the `required_zones` functionality, when placing a reviews section on a camera, the labels listed are applied to ALL zones defined on that camera.  Nesting the review section under the zone itself would allow having different labels alerted/detected per zone on the same camera.

**Describe alternatives you've considered**
The only alternative is having the same list of labels apply to all of the listed zones on a camera.  It does not currently appear to be possible to a different list of labels for different zones on the same camera.

**Additional context**
I am unsure if the current design is for performance/technical reasons, maybe it's faster/easier to do the detections for the entire camera feed and then just check if they are in a specific zone afterwards, but it would add some nice flexibility to be able to have a different list of labels per zone.  The currently way of configuring the system can be best described as "Watch this camera feed for any of these labels, but only let me know if they happen to be in these specific zones", and what I am asking for is more like "Watch this zone for these specific labels AND watch that other zone for those other specific labels".  Hopefully that makes sense.
