### ISSUE TITLE
frigate on QNAP container docker with Coral

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1561]
I had frigate setup on an NUC first with coral usb and all seem work fine, form the log i was able to see it found Edge TPU.  Because of the CPU its consuming i wanted to move that to my QNAP which has better processor.

So I updated QNAP to the latest firmware (which supports Edge TPU) and plugged in the coral, it did showed the coral details on the hardware section of the qnap.

Installed frigate docker (not thru the qnap container app, but directly with docker-compose from console) and moved my config exactly to qnap.  frigate log did show Edge Tpu found and started working with all the cameras as set in the previous config.  So all good few days.

Yesterday I tried to go to frigate web ui and it was just spinning, so i checked the log and it says 
```
frigate.edgetpu                INFO    : No EdgeTPU detected.
```
and bunch of errors and restarting logs afterwards.

Tried restart the frigate container couple times and still the same, not sure what went wrong.

One thing i did yesterday is put all my photos into qnap because qnap have a app called QuMagie (QuMagie was installed long ago and there was some few photos already) which is AI photo organizing which utilize coral, i was able to see its working showed coral processing status.

Any idea how i can get frigate back to detect Edge TPU?

**Comment by mitchross** [comment]
post your docker compose file and frigate config.

**Comment by balajeek** [comment]
```
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.8.4-amd64
    privileged: true
    shm_size: '100m'
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /share/Container/frigate/config:/config
      - /share/Container/frigate/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
      - /share/Surveillance/frigate/media/clips:/media/frigate/clips
      - /share/Surveillance/frigate/media/recordings:/media/frigate/recordings
      - /share/Container/frigate/config/labelmap.txt:/labelmap.txt      
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 75000000 ## 75MB, good for 3 1080p cameras with 10s of cache each, this depends on your setup.
    ports:
    - "4000:5000" # [local port]:[container port]
    restart: unless-stopped
```

**Comment by balajeek** [comment]
```
mqtt:
  host: 192.168.99.13
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

database:
  path: /media/frigate/clips/frigate.db

cameras:
  reef:
    ffmpeg:
      inputs:
        - path: rtsp://username:pass@192.168.99.41/live
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5

  front:
    ffmpeg:
      inputs:
        - path: rtsp://username:pass@192.168.99.40/live
          roles:
            - detect
            - rtmp
            - record
            - clips
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: true
      retain:
        default: 5
        objects:
          person: 5
          animal: 2
          vehicle: 2
    record:
      enabled: true
      retain_days: 5
    clips:
      enabled: True
      post_capture: 10
      retain:
        default: 1
        objects:
          person: 1
          animal: 1
          vehicle: 1
    motion:
      mask:
        - 0,1080,361,1080,425,1017,485,981,478,816,222,527,1920,356,1920,0,250,0,0,0
        - 709,860,648,771,636,633,808,644,674,519,796,499,854,544,1038,526,1106,616,934,651,1004,1080,793,1080,763,865
        - 1892,1009,1889,1080,1381,1080,1381,1009
    zones:
      zone_front_walkway:
        coordinates: 1307,1080,1030,1080,962,842,908,749,1030,741

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.99.13:8554/v3-outdoor
          roles:
            - detect
            - rtmp
            - record
            - clips
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: true
      retain:
        default: 5
        objects:
          person: 2
          animal: 2
          vehicle: 2
    record:
      enabled: true
      retain_days: 5
    clips:
      enabled: True
      post_capture: 10
      retain:
        default: 1
        objects:
          person: 1
          animal: 1
          vehicle: 1
    motion:
      mask:
        - 760,671,1113,829,1492,1020,1920,1013,1920,1080,1562,1080,1443,1080,1358,1080,957,1080,0,1080,0,656
        - 0,0,0,269,1920,290,1920,213,1920,0,0,0
    zones:
      zone_driveway:
        coordinates: 1376,446,1920,653,1920,986,1723,991,1530,992,1290,929,982,742,811,676,675,646,201,599,26,571,26,493
detectors:
  coral:
    type: edgetpu
    device: usb
  cpu:
    type: cpu
```
