### ISSUE TITLE
Accept environment variables for ONVIF host and port

### ISSUE THREAD

**Issue by sebsebseb1982** [blakeblackshear/frigate#15622]
Hi, 

I'd like to hide public IP and port in my configuration file.
It would be great to hide it with env var [like for user and password](https://docs.frigate.video/configuration/#environment-variable-substitution).

Something like :
```yaml
onvif:
  host: "{FRIGATE_ONVIF_HOST}"
  port: "{FRIGATE_ONVIF_PORT}"
  user: "{FRIGATE_RTSP_USER}"
  password: "{FRIGATE_RTSP_PASSWORD}"
```

**Comment by tonsV2** [comment]
Why is this issue closed? It's super frustrating having something like the below in my config

```
...
    onvif:
      # TODO: Why does this not work?
      #host: "{FRIGATE_YARD_HOST}"
      host: 192.168.1.32
      port: 80
      user: "{FRIGATE_YARD_USERNAME}"
      password: "{FRIGATE_YARD_PASSWORD}"

```
