### ISSUE TITLE
Frigate Docker runtime files are 11 GB+

### ISSUE THREAD

**Issue by timdonovanuk** [blakeblackshear/frigate#1570]
Is this normal?! The docker base OS used here is ubuntu:20.04 which I believe is around 200mb. I am placing clips, db and config files in a seperate volume. After running Frigate my /var/lib/docker/vfs/dir directory grew by 11gb instantly. 

My 16GB LXC ran out of space within a few hours, and not because of clips/recordings x_x

**Comment by blakeblackshear** [comment]
Post your compose file

**Comment by timdonovanuk** [comment]
```
version: '3.3'
services:
    frigate:
        container_name: frigate
        image: blakeblackshear/frigate:stable-amd64
        privileged: true
        volumes:
            - '/opt/frigate/clips:/media/frigate/clips:rw'
            - '/opt/frigate/db:/media/frigate/db:rw'
            - '/opt/frigate/config:/config:ro'
            - '/dev/bus/usb:/dev/bus/usb'
            - '/etc/localtime:/etc/localtime:ro'
        devices:
            - /dev/dri/renderD128
        ports:
            - '5000:5000'
        environment:
            - FRIGATE_RTSP_PASSWORD=password
```
