### ISSUE TITLE
Image and video notification not working in Telegram

### ISSUE THREAD

**Issue by Sarelseekat** [blakeblackshear/frigate#1572]
Hi There

I'm trying to get the video and images sent through to Telegram when an event is triggered. I'm using the instruction on the Frigate Home assistant page, but only get the TEXT - Message section coming through. Nothing under data: ..... gets sent to Telegram.

Frigate Version 1.13

**Config file**

```mqtt:
  host: 10.0.10.20
  user: ...............
  password: ................

cameras:
  34steppingstones:
    ffmpeg:
      inputs:
        - path: rtsp://............................../H264?ch=1&subtype=0
          roles:
            - detect
            - clips
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - car
        - person
        - motorcycle
        - bicycle
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 28
    clips:
      enabled: True
      retain:
        default: 28
    rtmp:
      enable: True

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
  cpu5:
    type: cpu
  cpu6:
    type: cpu
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera 34steppingstones has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 37
detector.cpu2                  INFO    : Starting detection process: 39
detector.cpu4                  INFO    : Starting detection process: 42
detector.cpu6                  INFO    : Starting detection process: 46
detector.cpu3                  INFO    : Starting detection process: 41
frigate.app                    INFO    : Camera processor started for 34steppingstones: 49
frigate.app                    INFO    : Capture process started for 34steppingstones: 51
detector.cpu5                  INFO    : Starting detection process: 43
```

Automation in Question
```
- id: '1629467461691'
  alias: Event Detected
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
  condition: []
  action:
service: notify.cctvgroup
data_template:
  target: -534772942
  message: A {{trigger.payload_json["after"]["label"]}} was detected.
  data:
    image: >-
      https://..............:9443/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
    tag: '{{trigger.payload_json["after"]["id"]}}'
    when: '{{trigger.payload_json["after"]["start_time"]|int}}'
```
