### ISSUE TITLE
Objects mode in Birdseye not working

### ISSUE THREAD

**Issue by MrAnonymous722** [blakeblackshear/frigate#1582]
**Describe the bug**
Seems like regardless of motion or objects setting in frigate.yml, it shows the camera when there's any motion detected. 

**Version of frigate**
0.9.0-3340952

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.0.189
  user: mqttuser
  password: mysupersecureandsecretpassword
detectors:
  coral1:
    type: cpu
  coral2:
    type: cpu
  coral3:
    type: cpu
birdseye:
  enabled: True
  mode: objects 
cameras:
  driveway-cam:
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        enabled: True
        post_capture: 10
    ffmpeg:
      inputs:
       - path: rtsp://192.168.0.4:8554/driveway-cam
         roles:
          - detect
          - record
    snapshots:
      enabled: True
      timestamp: True
      crop: True
    objects:
      filters:
        car:
          mask:
           - 1920,0,1920,206,1550,144,1027,129,609,181,383,229,0,379,0,88,61,0
      track:
       - person
       - car
       - bicycle
       - dog
       - cell phone
       - bus
    motion:
      mask: 1872,1015,1876,1059,1383,1059,1381,1013
    zones:
      yard:
        coordinates: 326,208,423,185,674,139,1034,107,782,424,232,429,64,606,0,585
      driveway:
        coordinates: 1026,146,403,1080,1920,1080,1920,536,1588,161
      porch:
        coordinates: 359,1080,0,1080,0,624,52,634,243,465,764,446
  garage-cam:
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        enabled: True
        post_capture: 10
    ffmpeg:
      inputs:
       - path: rtsp://192.168.0.4:8554/garage-cam
         roles:
          - detect
          - record
    motion:
      mask:
        - 1387,1052,1868,1052,1863,1013,1389,1011
    snapshots:
      enabled: True
      timestamp: True
    objects:
      track:
       - person
       - car
       - backpack
  backyard-cam:
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        enabled: True
        post_capture: 10
    motion:
      mask: 1872,1015,1876,1059,1383,1059,1381,1013
    ffmpeg:
      inputs:
       - path: rtsp://192.168.0.4:8554/back-yard-cam
         roles:
          - detect
          - record
    objects:
      filters:
        bird:
          mask:
           - 1920,781,1619,527,1683,250,1920,396
    snapshots:
      enabled: True
      timestamp: True
    objects:
      track:
       - person
       - bird

```

**Frigate container logs**
I don't have any relevant logging, but I can provide specifics if requested.

**Frigate stats**
```json
{"backyard-cam":{"camera_fps":5.1,"capture_pid":242,"detection_fps":0.0,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":116.45,"pid":219},"coral2":{"detection_start":0.0,"inference_speed":129.7,"pid":221},"coral3":{"detection_start":0.0,"inference_speed":126.04,"pid":223}},"driveway-cam":{"camera_fps":5.1,"capture_pid":233,"detection_fps":0.0,"pid":229,"process_fps":5.1,"skipped_fps":0.0},"garage-cam":{"camera_fps":5.0,"capture_pid":237,"detection_fps":0.0,"pid":231,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":56.6,"mount_type":"tmpfs","total":67.1,"used":10.5},"/media/frigate/clips":{"free":10376.6,"mount_type":"ext4","total":25294.1,"used":13773.7},"/media/frigate/recordings":{"free":10376.6,"mount_type":"ext4","total":25294.1,"used":13773.7},"/tmp/cache":{"free":996.3,"mount_type":"tmpfs","total":1000.0,"used":3.7}},"uptime":239,"version":"0.9.0-3340952"}}
```
**Computer Hardware**
 - OS: Ubuntu VM
 - Install method: Docker-compose
 - Virtualization: Virtualbox
 - Coral Version: CPU (For now)
 - Network Setup: Ethernet to the router, wireless to the cameras from there

**Camera Info:**
 - Manufacturer: Wyze
 - Model: V3
 - Resolution: 1080p
 - FPS: 5
