### ISSUE TITLE
Object mask difficulty

### ISSUE THREAD

**Issue by wrpooley** [blakeblackshear/frigate#1583]
I'm having a tough time implementing an object mask.  After getting the coordinates from the creator and editing the config file (see below) and after restarting Frigate there is no object mask in place.  It's probably a yam thing but I've tried many times with no luck.  Anyone see the issue here?  I have no trouble adding a motion mask.

```yaml
  Driveway:
    ffmpeg:
      hwaccel_args:
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero

      inputs:
        - path: rtmp://192.168.111.50/bcs/channel0_sub.bcs?channel=0&stream=0&user=&password
          roles:
            - detect
            - clips

            
    width: 640
    height: 480
    fps: 5
    objects:
      track:
        - person
      filters:
        person:
          mask: 
            - 214,300,277,311,343,281,242,236
    snapshots:
      enabled: true
      retain:
        default: 2
    clips:
      enabled: true
      retain:
        default: 2
    motion:
      mask:
        - 229,465,19,466,21,448,223,449
        - 474,167,226,67,0,180,0,128,0,108,0,69,0,0,257,0,455,0,640,0,640,134,640,249
```
