### ISSUE TITLE
Dynamic Recording Streams (improved)

### ISSUE THREAD

**Issue by finnaGIT** [blakeblackshear/frigate#15853]
**Describe what you are trying to accomplish and why in non technical terms**
I want to facilitate the use of continuous recording (i.e. `mode: all`) in a low-res substream and enable recording only on clips of interest (i.e., `mode: active_objects`).

**Describe the solution you'd like**
I believe this can be conveniently accomplished using the `record - alerts - detections` config, and by stating the applicable stream at a camera level.

For example:
```
go2rtc:
  streams:
    camera_one_main: rtsp://192.168.0.2:1234 # camera one main stream
    camera_one_sub: rtsp://192.168.0.2:5678 # camera one sub stream

cameras:
  camera_one:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/camera_one_main
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/camera_one_sub
          roles:
            - detect
            - record
            - audio
    record:
      enabled: true
      retain:
        mode: all
        days: -1 # '-1' to record continuously, or until storage is consumed & delete oldest 2 hours with 1 hr remaining, or state a number of days as is currently implemented
        stream: camera_one_sub
      alerts:
        mode: active_objects
        days: -1
        stream: camera_one_main
```

**Describe alternatives you've considered**
It appears to be possible to configure two completely separate cameras, where the main stream is configured as `record` only for `alerts > mode: active_objects` and the sub-stream is configured to record `mode: all` for 10000 days or something arbitrarily large to hit your storage limit. However this requires maintenance and duplication of camera settings, zones, masks, objects, etc.

**Additional context**
Fully recognizing that Frigate has historically centered its focus on detections and alerting, continuous recording of the substream is an important option for me to have, and if it can be enabled more intuitively or conveniently I think others may consider this functionality as well.

*As always, thanks to all of the generosity of the developers, maintainers, and contributors.*
