### ISSUE TITLE
field required (type=value_error.missing)

### ISSUE THREAD

**Issue by npotgieter** [blakeblackshear/frigate#1600]
Latest container (0.9.0-29de723-amd64) does not start. (Last version that worked in my environment was: 0.9.0-b33f4e2-amd64)

From log:

[services.d] starting services
[services.d] done.
Error parsing config: 4 validation errors for FrigateConfig
cameras -> driveway -> detect
  field required (type=value_error.missing)
cameras -> garage -> detect
  field required (type=value_error.missing)
cameras -> basementdoor -> detect
  field required (type=value_error.missing)
cameras -> frontdoor -> detect
  field required (type=value_error.missing)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Example of config file camera declaration below.

```
cameras:
  driveway:
    motion:
      mask:
        - 0,277,640,271,640,0,0,0
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0,274,640,260,640,0,0,0
          threshold: 0.7
        person:
          mask:
            - 0,274,640,260,640,0,0,0
          threshold: 0.7
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs: 
        - path: rtmp://192.168.1.111/bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password={FRIGATE_RTSP_PASSWORD} 
          roles: 
            - detect
            - rtmp
        - path: rtmp://192.168.1.111/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={FRIGATE_RTSP_PASSWORD}
          roles: 
            - clips
    clips:
      enabled: true
      objects:
        - person
        - car
    width: 640
    height: 480
    fps: 4
    rtmp:
      enabled: true
    snapshots:
      enabled: true
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
```
