### ISSUE TITLE
add audio stream to clips 

### ISSUE THREAD

**Issue by Tyrian81** [blakeblackshear/frigate#1601]
**Describe what you are trying to accomplish and why in non technical terms**
I have a stream with this audio Codec: PCM MU-LAW (mlaw) which is 16 bit mono @ 8000Hz

**Describe the solution you'd like**
Add this to my clips

**Describe alternatives you've considered**
removing -an and replacing to -aac didnt work 

the frigate rtmp  stream works excellent with sound , except clips dont do sound ?

**Comment by blakeblackshear** [comment]
This should have been a support request, not a feature suggestion. See [here](https://github.com/blakeblackshear/frigate/discussions/1550#discussioncomment-1202747) for an example of how to properly add `aac` encoding to RTMP. You need to modify the clips output_args in the same way. `-aac` is the wrong parameter.

**Comment by AlexObukhoff** [comment]
For ffmpeg command line I remove `-c copy` and add `-codec:a aac -codec:v copy`

```
    ffmpeg:
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:a aac -codec:v copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:a aac -codec:v copy
```
