### ISSUE TITLE
[Camera Support]: Dahua C5A two-way talk

### ISSUE THREAD

**Issue by mccajm** [blakeblackshear/frigate#16026]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/16025

<div type='discussions-op-text'>

<sup>Originally posted by **mccajm** January 17, 2025</sup>
### Describe the problem you are having

When enabling two-way talk on a Dahua C5A, the video gets replaced by a loading indicator but the two-way talk works correctly.

### Version

0.14.1-f4f3cfa

### What browser(s) are you using?

Google Chrome 131.0.6778.265

### Frigate config file

```yaml
mqtt:
  enabled: false

cameras:
  nursery: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args: auto
      inputs:
        - path: 
            rtsp://127.0.0.1:8554/nursery?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
            - detect 
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720

go2rtc:
  streams:
    nursery:
      - rtsp://X:X@10.10.0.1:554/cam/realmonitor?channel=1&subtype=0
    nursery_sub:
      - rtsp://X:X@10.10.0.1:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 159.69.200.78:8555
      - stun:8555

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 3650
      mode: motion

audio: # <- enable audio events for all camera
  enabled: true
  listen:
    - speech
    - babbling
    - yell
    - bellow
    - whoop
    - whispering
    - laughter
    - crying
    - sigh
    - singing
    - child_singing
    - humming
    - rapping
    - groan
    - grunt
    - whistling
    - breathing
    - snoring
    - gasp
    - pant
    - wheeze
    - snort
    - cough
    - throat_clearing
    - sneeze
    - sniff
    - footsteps
    - shuffle
    - biting
    - gargling
    - burping
    - hiccup
    - fart
    - finger_snapping
    - clapping
    - applause
    - chatter
    - children_playing
    - smoke_detector
    - fire_alarm
    - car_alarm
```

### Relevant Frigate log output

```shell
2025-01-17 14:15:52.367305225  14:15:52.367 INF [streams] can't add track error="wrong media: audio, sendonly, PCMA/8000"
2025-01-17 14:15:52.367783311  14:15:52.367 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:170 > error="start from CONN state" url=rtsp://X:X@10.10.0.1:554/cam/realmonitor?channel=1&subtype=0
2025-01-17 14:15:54.410703532  [2025-01-17 14:15:54] ffmpeg.nursery.audio           ERROR   : Output file #0 does not contain any stream
2025-01-17 14:15:54.410940895  [2025-01-17 14:15:54] audio.nursery                  INFO    : Terminating the existing ffmpeg process...
2025-01-17 14:15:54.410943535  [2025-01-17 14:15:54] audio.nursery                  INFO    : Waiting for ffmpeg to exit gracefully...
2025-01-17 14:15:55.276347481  [2025-01-17 14:15:55] audio.nursery                  ERROR   : ffmpeg process is not running, restarting...
2025
```

### Relevant go2rtc log output

```shell
{
  "producers": [
    {
      "id": 139,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "10.10.0.1:554",
      "url": "rtsp://X:X@10.10.0.1:554/cam/realmonitor?channel=1\u0026subtype=0",
      "sdp": "v=0\r\no=- 2229913047 2229913047 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\na=x-summary:Oversea\r\nm=video 0 RTP/AVP 98\r\na=control:trackID=0\r\na=framerate:30.000000\r\na=rtpmap:98 H265/90000\r\na=fmtp:98 profile-id=1;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABaCAGWfeNrkkya5YwCAAAAwAIAAADAPBA;sprop-pps=RAHgdoaNAwYMZA==;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=1\r\na=rtpmap:8 PCMA/8000\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=5\r\na=rtpmap:8 PCMA/8000\r\na=sendonly\r\n",
      "user_agent": "go2rtc/1.9.8",
      "medias": [
        "video, recvonly, H265",
        "audio, recvonly, PCMA/8000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        {
          "id": 140,
          "codec": {
            "codec_name": "hevc",
            "codec_type": "video"
          },
          "childs": [
            13,
            33,
            72
          ],
          "bytes": 127189,
          "packets": 310
        },
        {
          "id": 141,
          "codec": {
            "codec_name": "pcm_alaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "childs": [
            10,
            14,
            34
          ],
          "bytes": 72320,
          "packets": 226
        }
      ],
      "senders": [
        {
          "id": 142,
          "codec": {
            "codec_name": "pcm_alaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 54
        }
      ],
      "bytes_recv": 206029
    }
  ],
  "consumers": [
    {
      "id": 6,
      "format_name": "webrtc",
      "protocol": "ws+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp+udp",
      "remote_addr": "185.73.44.149:51384 srflx 0.0.0.0:0",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, VP9, H264, AV1",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, L16, PCML"
      ],
      "senders": [
        {
          "id": 10,
          "codec": {
            "codec_name": "pcm_alaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 141,
          "bytes": 3354560,
          "packets": 10483
        }
      ],
      "bytes_send": 3392900
    },
    {
      "id": 5,
      "format_name": "mse/fmp4",
      "protocol": "ws",
      "remote_addr": "185.73.44.149:50472",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
      ],
      "senders": [
        {
          "id": 13,
          "codec": {
            "codec_name": "hevc",
            "codec_type": "video"
          },
          "parent": 140,
          "bytes": 5711973,
          "packets": 14325
        },
        {
          "id": 14,
          "codec": {
            "codec_name": "flac",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 141,
          "bytes": 3354560,
          "packets": 10483
        }
      ],
      "bytes_send": 15099456
    },
    {
      "id": 32,
      "format_name": "mse/fmp4",
      "protocol": "ws",
      "remote_addr": "185.73.44.149:50717",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
      ],
      "senders": [
        {
          "id": 33,
          "codec": {
            "codec_name": "hevc",
            "codec_type": "video"
          },
          "parent": 140,
          "bytes": 4900918,
          "packets": 12317
        },
        {
          "id": 34,
          "codec": {
            "codec_name": "flac",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 141,
          "bytes": 2882880,
          "packets": 9009
        }
      ],
      "bytes_send": 12936567
    },
    {
      "id": 71,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "127.0.0.1:34130",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.9.8\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H265/90000\r\na=fmtp:96 profile-id=1;sprop-sps=QgEBAWAAAAMAAAMAAAMAAAMAlqABaCAGWfeNrkkya5YwCAAAAwAIAAADAPBA;sprop-pps=RAHgdoaNAwYMZA==;sprop-vps=QAEMAf//AWAAAAMAAAMAAAMAAAMAlqwJ\r\na=control:trackID=0\r\n",
      "user_agent": "FFmpeg Frigate/0.14.1-f4f3cfa",
      "medias": [
        "audio, sendonly, MPEG4-GENERIC",
        "video, sendonly, ANY"
      ],
      "senders": [
        {
          "id": 72,
          "codec": {
            "codec_name": "hevc",
            "codec_type": "video"
          },
          "parent": 140,
          "bytes": 3971811,
          "packets": 10024
        }
      ],
      "bytes_send": 4132195
    }
  ]
}
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://X:X@10.10.0.1:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, bitrate: 64 kb/s
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 2880x1620, 30 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Object Detector

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua C5A

### Screenshots of the Frigate UI's System metrics pages

<img width="1355" alt="Screenshot 2025-01-17 at 14 25 29" src="https://github.com/user-attachments/assets/4ff8defa-bf28-4157-9a67-9865284c0cb5" />
<img width="727" alt="Screenshot 2025-01-17 at 14 25 37" src="https://github.com/user-attachments/assets/a62c053a-a34e-47e7-b067-02b497bf8ef3" />

### Any other information that may be helpful

_No response_</div>
