### ISSUE TITLE
Global Detect flag requires height/width/fps - but docs say only for max disappeared

### ISSUE THREAD

**Issue by DeadEnded** [blakeblackshear/frigate#1615]
**Describe the bug**
The global `detect` flag requires height/width/fps - but docs say only for max disappeared.
Commenting out the global `detect` allowed Frigate to start without error.

**Version of frigate**
9.0-cr1

**Config file**
```yaml
# Optional: Global detecttion settings. These may also be defined at the camera level.
# ADVANCED: Most users will not need to set these values in their config
detect:
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
  max_disappeared: 25
```

**Frigate container logs**
```
Error parsing config: 3 validation errors for FrigateConfig
detect -> height
  field required (type=value_error.missing)
detect -> width
  field required (type=value_error.missing)
detect -> fps
  field required (type=value_error.missing)
```

**Additional context**
I expect that it wouldn't be best to force a global height/width/fps setting for detection.  So my thought is that an exception needs to be made if the `detect` flag is nested in a camera.  Another option would be to move the max disappeared to another section and remove the global `detect` flag all together... but I expect you already know the best way to handle it... since I'm just throwing darts at code I haven't read :-).

Anyway, the relevant documentation for this setup is in the `advanced.md` lines 38 - 46.
![image](https://user-images.githubusercontent.com/45110141/131033190-38e6af35-e797-41f6-b870-7b69d8830737.png)

Cheers!
DeadEnd
