### ISSUE TITLE
Birdseye view should default to matching aspect ratio of cameras

### ISSUE THREAD

**Issue by charlesmunger** [blakeblackshear/frigate#1617]
The new birdseye view is fantastic, but defaults to 1280x720. This results in pillarboxing of 640x480 feeds - instead, the width could be fixed and the height scaled to match the known dimensions of video streams.

**Version of frigate**
0.9.0-4efc584
**Config file**
Minimized to repro issue:
```yaml
birdseye:
  mode: continuous
  width: 1280
  # If the following height is not provided, you get black bars
  height: 960 

cameras:
  camera1:
     detect: &detect
      width: 640
      height: 480
      fps: 7

  camera2:
    detect: *detect
  camera3:
    detect: *detect
  camera4:
    detect: *detect
```
This produces a view with large black bars, rather than the minimal square view that it could.

**FFprobe from your camera**

Run the following command and paste output below
```
Input #0, flv, from 'rtmp://host/bcs/channel0_sub.bcs?channel=0&stream=0&user=frigate&password=**********':
  Metadata:
    displayWidth    : 640
    displayHeight   : 480
  Duration: 00:00:00.00, start: 391155.467000, bitrate: N/A
    Stream #0:0: Data: none
    Stream #0:1: Video: h264 (High), yuv420p(progressive), 640x480, 6 fps, 30 tbr, 1k tbn
    Stream #0:2: Audio: aac (LC), 16000 Hz, mono, fltp
```

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Docker Compose
 - Coral Version: PCIe (dual, only one in use)
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-410
 - Resolution: 2560x1920 main, 640x480 sub
 - FPS: 7

**Additional context**
One simple algorithm would be to look at the specified parameters in `detect` for all cameras, and match the aspect ratio they use with the existing fixed width.
