### ISSUE TITLE
Unable to create clip. There were no cache files for this event.

### ISSUE THREAD

**Issue by M4RKOL1V3R** [blakeblackshear/frigate#1618]
**Describe the bug**
Clips will not be saved at all. I cant figure out why. Tried to give more space to /tmp/cache but got an error that /tmp/cache is read only.

**Config file**
```
cameras:
  cam2_esp32:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts
        - -rtsp_transport
        - tcp
        - -r
        - '5'
        - -use_wallclock_as_timestamps
        - '1'
      inputs:
        - path: rtsp://192.168.2.131:8554/mjpeg/1
          roles:
            - detect
            #- rtmp
            - clips
            - record
      output_args:
        detect: -vf transpose=2 -f rawvideo -pix_fmt yuv420p
        #rtmp: -c:a copy -c:v libx264 -f flv
        clips: -vf transpose=2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -pix_fmt yuv420p -an
    width: 768
    height: 1024
    fps: 5
    detect:
      enabled: True
    clips:
      enabled: True
      retain:
        default: 2
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 2
    objects:
      track:
        - bird
        - cat
        - car
        - dog
        - person
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
    rtmp:
      enabled: False

record:
  # Optional: Enable recording
  enabled: True
  # Optional: Number of days to retain
  retain_days: 30 


database:
  path: /media/frigate/clips/frigate.db



detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 37
detector.cpu2                  INFO    : Starting detection process: 39
detector.cpu3                  INFO    : Starting detection process: 40
frigate.app                    INFO    : Camera processor started for cam2_esp32: 46
detector.cpu4                  INFO    : Starting detection process: 43
frigate.app                    INFO    : Capture process started for cam2_esp32: 47
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f38551b140] moov atom not found
/media/frigate/recordings/cam2_esp32-20210826235300.mp4: Invalid data found when processing input
frigate.record                 INFO    : bad file: cam2_esp32-20210826235300.mp4
frigate.events                 WARNING : Unable to create clip for cam2_esp32 and event 1630017661.819293-qbdkar. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for cam2_esp32 and event 1630017676.880997-8zhpda. There were no cache files for this event.
frigate.events                 WARNING : Unable to create clip for cam2_esp32 and event 1630018017.028492-thysfb. There were no cache files for this event.
```
**ffprobe of Camera**
```
ffprobe rtsp://192.168.2.131:8554/mjpeg/1
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 2 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 2 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 3 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 2 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 3 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] Missing packets; dropping frame.
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 2 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 3 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] Missing packets; dropping frame.
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 4 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] Missing packets; dropping frame.
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] Missing packets; dropping frame.
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 2 packets
[rtsp @ 0x557bea6e9f00] Missing packets; dropping frame.
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 3 packets
[rtsp @ 0x557bea6e9f00] Missing packets; dropping frame.
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 2 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 1 packets
[rtsp @ 0x557bea6e9f00] max delay reached. need to consume packet
[rtsp @ 0x557bea6e9f00] RTP: missed 4 packets
Input #0, rtsp, from 'rtsp://192.168.2.131:8554/mjpeg/1':
  Metadata:
    title           : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 1024x768 [SAR 1:1 DAR 4:3], 29.67 tbr, 90k tbn, 90k tbc
```

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Addon,
 - Coral Version: None
 - Network Setup: WiFi

**Camera Info:**
 - Manufacturer: ESP32-Cam
 - Resolution:     768 x 1024
 - FPS: 5
