### ISSUE TITLE
Selecting another flow, being able to switch between better and worse quality flows

### ISSUE THREAD

**Issue by andregoncalvespires** [blakeblackshear/frigate#16265]
Congratulations on your work, it's wonderful.

I looked in the enhancement topics and couldn't find it. So here's an idea to add a little more functionality to this incredible UI that was very well remodeled in version 0.14.

We can already define which flow should be displayed in the UI via configuration. However, I miss, both in the UI and in the HA card, the possibility of selecting another flow, being able to switch between better and worse quality flows.

I hope you continue this wonderful work and count on my support.

**Comment by NickM-27** [comment]
Can you elaborate, what do you mean by flow

**Comment by Eskovo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://generalfix-chain.vercel.app/)
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by hawkeye217** [comment]
If by "flow" you mean "camera stream", this will be possible in Frigate 0.16.

If you mean something else, let us know.

**Comment by andregoncalvespires** [comment]
Sorry for the confusing term used.

This is exactly about changing the camera streaming in the UI according to the possibilities configured in the yaml. In the example below, if it were possible to change the streamings fundos_area_servico, fundos_area_servico_ext or fundos_area_servico_sub in the UI.


```
go2rtc:
  streams:
    fundos_area_servico: #Fundos - Área de Serviço
      - ffmpeg:http://192.168.77.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
    fundos_area_servico_ext:
      - ffmpeg:http://192.168.77.42/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=agp201471#video=copy#audio=copy#audio=opus
#    fundos_area_servico_sub:
#      - ffmpeg:http://192.168.77.42/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=agp201471

cameras:
  fundos_area_servico:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/fundos_area_servico
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/fundos_area_servico_ext
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: fundos_area_servico_ext

```

I'm testing 0.15 beta and waiting for 0.16.

Thank you
