### ISSUE TITLE
Recent Vstarcam c61s working but fails to save clips

### ISSUE THREAD

**Issue by dscoular** [blakeblackshear/frigate#1632]
**Describe the bug**
First of all, thank you for an astounding open source project!

This isn't really a frigate bug but more an issue, I suspect, with the camera stream.

I have 3 "cheap as chips" Vstarcam c61s 360 degree wifi cameras. The most recent of these has some subtle differences and fails to output mp4 clips. The other two older c61s cameras work perfectly with no ffmpeg `input_args` or `output_args` specified and, therefore, using their defaults.

However, the new camera successfully shows the detection stream in the frigate UI and happily creates thumbnails and jpg snapshots when there are events but it fails to produce any clips.

I've spent hours searching on google and trying various combinations and permutations of options and really wanted to avoid using up this site's bandwidth with my issue... but I'm stumped.

```
frigate.events                 INFO    : bad file: frontdoor360-20210828155025.mp4
[extract_extradata @ 0x55eaf0c83ec0] No start code is found.
/tmp/cache/frontdoor360-20210828155046.mp4: Invalid data found when processing input
```

The subtle differences I've noticed between the old and new cameras are that the rtps stream has changed from the crazily non-standard tcp 10544 port to the slightly less crazily non-standard 10554 port (the rtps default being 554). 

It seems like the ffmpeg segments being produced are missing critical headers and fail to be copied from the cache to the clips directory.

I'd love to hear suggestions on what I can do to further debug why I get no clips available in the frigate UI.

Cheers,

Doug

**Version of frigate**
Output from `/api/version`:

```bash
$ curl http://localhost:5000/api/version
0.8.4-5043040
```

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.200.5
  user: me
  password: REDACTED
clips:
  retain:
    # Required: Default retention days (default: shown below)
    default: 10

# Play rtmp via ssh local tunnel with:
#   access them at rtmp://<frigate_host>/live/<camera_name> e.g.
#               vlc rtmp://localhost:1935/live/garage
cameras:
  # New Vstarcam c61s 360 camera fails to make playable mp4 clips.
  frontdoor360:
    motion:
      mask:
        - 201,505,520,693,692,556,1070,437,1196,249,762,186,297,171
    ffmpeg:
      global_args:
        - -hide_banner
        - -loglevel
        - debug
      inputs:
        - path: rtsp://admin:XXXXXX@frontdoor.thepoint.org:10554/tcp/av0_0
          roles:
            - detect
            - rtmp
            - clips
      input_args:
        # Mad experimentation, the defaults produce no mp4 clips this produces unplayable ones.
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "10000000"
        - -use_wallclock_as_timestamps
        - "1"
    width: 1536
    height: 1536
    fps: 5
    clips:
      enabled: True
      pre_capture: 10
    snapshots:
      enabled: True
      bounding_box: true
      retain:
        default: 10

  # Working older Vstarcam c61s 360 camera
  garage:
    motion:
      mask:
        - 1536,1056,1009,388,320,196,331,0,1536,0
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXX@camera3.thepoint.org:10544/tcp/av0_0
          roles:
            - detect
            - rtmp
            - clips
    width: 1536
    height: 1536
    fps: 5
    clips:
      enabled: True
      pre_capture: 10
    snapshots:
      enabled: True
      bounding_box: true
      retain:
        default: 10

objects:
  track:
    - car
    - person

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Frigate container logs**
```
[extract_extradata @ 0x55a0613f5840] No start code is found.
/tmp/cache/frontdoor360-20210828160852.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: frontdoor360-20210828160852.mp4
```

**Frigate stats**
```json
$ curl http://localhost:6001/api/stats
{
  "detection_fps": 0.0,
  "detectors": {
    "cpu1": {
      "detection_start": 0.0,
      "inference_speed": 43.64,
      "pid": 50
    },
    "cpu2": {
      "detection_start": 0.0,
      "inference_speed": 43.2,
      "pid": 52
    },
    "cpu3": {
      "detection_start": 0.0,
      "inference_speed": 43.16,
      "pid": 54
    },
    "cpu4": {
      "detection_start": 0.0,
      "inference_speed": 42.64,
      "pid": 56
    }
  },
  "frontdoor360": {
    "camera_fps": 5.2,
    "capture_pid": 64,
    "detection_fps": 0.0,
    "pid": 60,
    "process_fps": 5.2,
    "skipped_fps": 0.0
  },
  "garage": {
    "camera_fps": 5.1,
    "capture_pid": 61,
    "detection_fps": 0.0,
    "pid": 59,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 59.0,
        "mount_type": "tmpfs",
        "total": 67.1,
        "used": 8.2
      },
      "/media/frigate/clips": {
        "free": 3489065.4,
        "mount_type": "ext4",
        "total": 7938516.5,
        "used": 4049373.0
      },
      "/media/frigate/recordings": {
        "free": 3489065.4,
        "mount_type": "ext4",
        "total": 7938516.5,
        "used": 4049373.0
      },
      "/tmp/cache": {
        "free": 990.6,
        "mount_type": "tmpfs",
        "total": 1000.0,
        "used": 9.4
      }
    },
    "uptime": 1866,
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
# ffprobe -rtsp_transport tcp rtsp://admin:XXXXXX@frontdoor.thepoint.org:10554/tcp/av0_0
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x5624a6d41440] Invalid NAL unit 0, skipping.
    Last message repeated 1 times
Input #0, rtsp, from 'rtsp://admin:XXXXXX@frontdoor.thepoint.org:10554/tcp/av0_0':
  Metadata:
    title           : streamed by the VSTARCAM RTSP server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1536x1536, 30 fps, 20 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
[h264 @ 0x5624a6d5d7c0] Invalid NAL unit 0, skipping.
```

**Screenshots**
N/A

**Computer Hardware**
 - OS: ubuntu 21.04
 - Install method: docker-compose
 - Virtualization: bare metal no virtualization
 - Coral Version: None
 - Network Setup: WiFi

**Camera Info:**
 - Manufacturer: Vstarcam
 - Model: c61s
 - Resolution: 1536x1536 (alt stream 300x300)
 - FPS: 30
**Additional context**

**Comment by blakeblackshear** [comment]
@dscoular You won't be able to do that unfortunately. The cache will fill up with .ts files because it's looking for mp4 files specifically.

**Comment by freeewilly** [comment]
@dscoular did you ever resolve this issue? I just received a new VStarCam and am experiencing the exact same issue. Thanks for any assistance!

**Comment by dscoular** [comment]
@freeewilly , sorry just seeing this now, after over a year... 

More recently I found I couldn't get go2rtc to recognise my more recent Vstarcam c61s but using the following in my camera stanza seems to work:

```yaml
cameras:
  frontdoor: 
    objects:
      track:
        - person
    ffmpeg:
            global_args:
        - -hide_banner
        - -loglevel
        - debug
      inputs:
        - path: rtsp://admin:88888888@frontdoor.thepoint.org:10554/tcp/av0_0
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
```

If anyone knows how to get go2rtc to work with the same arguments... that would be great!
