### ISSUE TITLE
Nuc and H265 with Reolink 4k 

### ISSUE THREAD

**Issue by RobertusIT** [blakeblackshear/frigate#1639]
**Describe the bug**
**I can't record in full size 4k resolution from my reolinks cameras.
I can see preview in low resolution h264 640x360, isn't good but if not possible use h265 to see live preview\streaming, it's ok.
But i wish to record in full size or have no sense have 4k camera, i get a refund and get 5mp h264 reolink.
So preview if isn't possible get full size without waste cpu and electricity, it's ok in low res h264.
But when recognize human or other things, need to record and save in full size 4k.**

**Version of frigate**
**0.8.4-5043040**

**Config file**
```
mqtt:
  host: 192.168.178.36
  user: mqtt_user
  password: mqtt_user

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

cameras:

  balcone_grande:

    ffmpeg:
      inputs:
        - path: rtsp://admin:mypass@192.168.178.50:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:mypass@192.168.178.50:554/
          roles:
            - clips
            - record
            - rtmp
    width: 640
    height: 360
    fps: 3
    detect:
      enabled: True
```

**Frigate container logs**
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dcfdf14140] moov atom not found
/tmp/cache/balcone_grande-20210828214044.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: balcone_grande-20210828214044.mp4
ffmpeg.balcone_grande.clips_record_rtmp ERROR   : [flv @ 0x55ea87a8a340] Video codec hevc not compatible with flv
ffmpeg.balcone_grande.clips_record_rtmp ERROR   : Could not write header for output file #1 (incorrect codec parameters ?): Function not implemented
ffmpeg.balcone_grande.clips_record_rtmp ERROR   : 
watchdog.balcone_grande        INFO    : Terminating the existing ffmpeg process...
watchdog.balcone_grande        INFO    : Waiting for ffmpeg to exit gracefully...
ffmpeg.balcone_grande.clips_record_rtmp ERROR   : [flv @ 0x55c6e5bdd340] Video codec hevc not compatible with flv
ffmpeg.balcone_grande.clips_record_rtmp ERROR   : Could not write header for output file #1 (incorrect codec parameters ?): Function not implemented
ffmpeg.balcone_grande.clips_record_rtmp ERROR   : 
watchdog.balcone_grande        INFO    : Terminating the existing ffmpeg process...
watchdog.balcone_grande        INFO    : Waiting for ffmpeg to exit gracefully...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c277a7f140] moov atom not found
/tmp/cache/balcone_grande-20210828214054.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: balcone_grande-20210828214054.mp4
```

**Frigate stats**
```
{
  "balcone_grande": {
    "camera_fps": 3.0, 
    "capture_pid": 54, 
    "detection_fps": 0.0, 
    "pid": 49, 
    "process_fps": 3.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 1.8, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 103.0, 
      "pid": 39
    }, 
    "cpu2": {
      "detection_start": 1630179711.829199, 
      "inference_speed": 115.89, 
      "pid": 41
    }, 
    "cpu3": {
      "detection_start": 0.0, 
      "inference_speed": 111.41, 
      "pid": 43
    }, 
    "cpu4": {
      "detection_start": 0.0, 
      "inference_speed": 110.9, 
      "pid": 45
    }
  }, 
  "ingresso": {
    "camera_fps": 3.1, 
    "capture_pid": 53, 
    "detection_fps": 1.8, 
    "pid": 48, 
    "process_fps": 3.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 4153.6, 
        "mount_type": "tmpfs", 
        "total": 4169.5, 
        "used": 15.9
      }, 
      "/media/frigate/clips": {
        "free": 4322.6, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 27371.4
      }, 
      "/media/frigate/recordings": {
        "free": 4322.6, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 27371.4
      }, 
      "/tmp/cache": {
        "free": 4140.6, 
        "mount_type": "tmpfs", 
        "total": 4169.5, 
        "used": 28.9
      }
    }, 
    "uptime": 69, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots** 
I can see preview, because i use substream in h264, the only h264 stream that have this camera, at low resolution 640x360.
![image](https://user-images.githubusercontent.com/11599774/131229391-39df6631-20b2-4b4b-973e-8ccc6a3fe244.png)

Recognize myself
![image](https://user-images.githubusercontent.com/11599774/131229400-4034fbbe-392f-4afc-94d0-765987be0d5a.png)

But doesn't create any events and of course, any files
![image](https://user-images.githubusercontent.com/11599774/131229441-664844f9-185c-4dff-a78f-68d79ab47448.png)

**Computer Hardware**
 - OS: Home Assistant OS SUpervised
 - Install method: OS Supervised
 - Virtualization: Proxmox
 - Coral Version: Coral soon, for now cpu
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-822A
 - Resolution: 4k H265
 - FPS: 29fps/30fps in according to info showed in vlc with rtsp

**Comment by blakeblackshear** [comment]
H265 isn't compatible with rtmp.

Try this:

```yaml
mqtt:
  host: 192.168.178.36
  user: mqtt_user
  password: mqtt_user

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

cameras:

  balcone_grande:

    ffmpeg:
      inputs:
        - path: rtsp://admin:mypass@192.168.178.50:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:mypass@192.168.178.50:554/
          roles:
            - clips
            - record
    width: 640
    height: 360
    fps: 3
    detect:
      enabled: True
```
