### ISSUE TITLE
Warning that [camera] has rtmp enabled, but rtmp is not assigned to an input

### ISSUE THREAD

**Issue by jasonpstokes** [blakeblackshear/frigate#1646]
Frigate logs a warning on startup if the optional (still?) `rtmp` role is not assigned to a camera.
```
frigate.app                    WARNING : Camera Driveway has rtmp enabled, but rtmp is not assigned to an input.,
frigate.app                    WARNING : Camera Entrance has rtmp enabled, but rtmp is not assigned to an input.,
... for every camera
```

**Version of frigate**
9.0

**Config file**
```yaml
  Driveway:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.71/bcs/channel0_ext.bcs?channel=0&stream=2&user=admin&password={FRIGATE_RTSP_PASSWORD}
          roles:
            - detect
        - path: rtmp://192.168.1.71/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={FRIGATE_RTSP_PASSWORD}
          roles:
            - record
```

**Comment by itkfilelor** [comment]
`
camera_name:
  ffmpeg: 
     inputs: 
        - path: 
          roles:
  rtmp: 
     enabled: true (or false, default is true)
`

**Comment by blakeblackshear** [comment]
Because you don't have rtmp assigned to an input. It needs to know which stream to use for rtmp.

```yaml
  Driveway:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.71/bcs/channel0_ext.bcs?channel=0&stream=2&user=admin&password={FRIGATE_RTSP_PASSWORD}
          roles:
            - detect
            - rtmp
        - path: rtmp://192.168.1.71/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={FRIGATE_RTSP_PASSWORD}
          roles:
            - record

```
