### ISSUE TITLE
Intel NUC 

### ISSUE THREAD

**Issue by thedexboy** [blakeblackshear/frigate#1648]
**Describe the bug**
No matter what I try to change, I can't get rid of two errors:
`ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures`
and
`ffmpeg process is not running. exiting capture thread...`

Tried 4 different cameras (Ubiqiti NVR, a cheap generic Foscam IP camera, a door video system with RTSP stream and this one in config is from octoprint from my Raspberry PI on my 3D printer. VLC plays all streams with no problems, Frigate won't show even one. All show the same errors.
I've double checked width, height and fps settings.

**Version of frigate**
Current version: 1.13 (pasted from HA supervisor)

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: core-mosquitto
  user: <redacted>
  password: <redacted>
cameras:
  octoprint:
    ffmpeg:
      inputs:
        - path: http://192.168.2.17/webcam/?action=stream
          roles:
            - detect
            - rtmp
    width: 640
    height: 480
    fps: 2

logger:
  default: debug
  logs:
    frigate.app: error


ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
    coral:
      type: edgetpu
      device: usb
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.coral                 INFO    : Starting detection process: 38
frigate.video                  INFO    : octoprint: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.video                  INFO    : octoprint: ffmpeg process is not running. exiting capture thread...
frigate.edgetpu                INFO    : TPU found
ffmpeg.octoprint.detect        ERROR   : Option stimeout not found.
frigate.http                   DEBUG   : Received mqtt message on frigate/stats.
frigate.video                  INFO    : octoprint: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : octoprint: ffmpeg process is not running. exiting capture thread...
ffmpeg.octoprint.detect        ERROR   : Option stimeout not found.
frigate.video                  INFO    : octoprint: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : octoprint: ffmpeg process is not running. exiting capture thread...
```

**Frigate stats**
```json
Can't access console, Running HA OS.
```

**FFprobe from your camera**

Run the following command and paste output below
```
Don't have a Linux machine where I could run this :(
```

**Screenshots**
Green screen instead of picture, screenshot won't help much here.

**Computer Hardware**
 - OS: Home Assistant OS 6.2
 - Install method: Addon
 - Virtualization: /
 - Coral Version: USB
 - Network Setup: Wired, Gbit LAN

**Camera Info:**
 - Manufacturer: USB camera on Raspberry PI running Octoprint
 - Model: /
 - Resolution: 640x480
 - FPS: 15

**Additional context**
I'm running HA on Intel® NUC Kit NUC7i3BNH with 8 GB of RAM. I've set 512 MB RAM to video memory in BIOS, nothing changed (was 128 before).
I tried searching here and on Google for this error combo, couldn't find the same error combination. I tried without `hwaccel_args`, no difference.
If it helps, VLC shows this as Codec info:
```
Codec: Motion JPEG Video (MJPG)
Video resolution: 640x480
Decoded format: Planar 4:2:2 YUV full scale
Color space: ITU-R BT.601 Range
```
I also tried disabling Protection mode in HA for this addon, same result.

**Comment by blakeblackshear** [comment]
Mjpeg streams need special parameters. Search the docs. Also, hwaccel args will not work with mjpeg feeds.

**Comment by thedexboy** [comment]
Oh wow so all my cameras only support Mjpeg. Oof. I knew it had to be something pretty stupid (from my side)... Thanks!

**Comment by blakeblackshear** [comment]
Note that many other features won't work well with mjpeg feeds. You will have to encode them to h264 on the fly for recordings and that will use a good bit of CPU.

**Comment by mruettgers** [comment]
> Note that many other features won't work well with mjpeg feeds. You will have to encode them to h264 on the fly for recordings and that will use a good bit of CPU.

Well, that's not the case when encoding to H264 is possible with hardware accelleration.
On my Intel GPU I'm able to consume a MJPEG stream of an ESP32 with Frigate and to transcode it to h264 without any noticeable increase of the CPU load.

I'm using the following args:
```
bird_cam_1:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -an -vf format=nv12,hwupload -c:v h264_vaapi
      inputs:
        - path: http://10.4.37.131/mjpeg/1
          roles:
            - record
            - detect
    record:
      enabled: True
      retain_days: 3

    rtmp:
      enabled: False
    detect:
      enabled: False
```

I know, a bit late, but maybe it still helps ;-).

**Comment by jshep321** [comment]
@blakeblackshear It would be useful for others to add details to the camera config docs.  I am, as of today  (due to the fix in ffmpeg armhf 7:4.3.4-0+deb11u1+rpt3), able to use RPI hwaccel on an rtsp stream (Unifi G3), but not on an http stream (octoprint).   

Side thought: I'm wondering if there's any pcie (or even USB3.0) GPU that does this type of transcoding for linux/rpi...?  Otherwise it seems that rpi4 is really not useful for multicam setup unless they are all rtsp (preferably h264 native).

```
###
##this fails with hwaccel enabled-->
#  3dprinter:
#    ffmpeg:
#      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
#      output_args:
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
#        rtmp: -c:v libx264 -an -f flv
#      inputs:
#        - path: "http://10.0.0.200/webcam/?action=stream"
#          roles:
#            - detect
#            - record
#            - rtmp
#      hwaccel_args:
#        - -c:v
#        - h264_mmal
#    detect:
#      width: 320
#      height: 320
#      fps: 5
#    snapshots:
#      enabled: True
#    record:
#      enabled: True
#      events:
#        retain:
#          default: 10
###
##this works-->
  unifi:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: rtsp://10.0.0.1:7447/<token here> 
          roles:
            - detect
            - rtmp
            - record
      hwaccel_args:
        - -c:v
        - h264_mmal
    detect:
      width: 320
      height: 320
      fps: 5
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
###

```
