### ISSUE TITLE
Camera feed showing green

### ISSUE THREAD

**Issue by Gnaj** [blakeblackshear/frigate#1650]
**Describe the bug**
getting thes errors only in one camera

ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
ffmpeg process is not running. exiting capture thread...

**Version of frigate**
Current version: 1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 192.168.100.142
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: 
  stats_interval: 60

cameras:
#  front_door:
#    ffmpeg:
#      inputs:
#        - path: rtsp://{FRIGATE_PASSWORD}@192.168.100.149:554/stream1
#          roles:
#            - detect
#            - rtmp
#    width: 1920
#    height: 1080
#    fps: 5

  Reja:
    ffmpeg:
      global_args: -hide_banner -loglevel warning -loglevel error
      inputs:
        - path: rtsp://{FRIGATE_PASSWORD}@192.168.100.36:554/live/ch00_0
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

logger:
  default: debug

```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 45
detector.cpu2                  INFO    : Starting detection process: 47
frigate.app                    INFO    : Camera processor started for Reja: 50
frigate.app                    INFO    : Capture process started for Reja: 51
frigate.video                  INFO    : Reja: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Reja: ffmpeg process is not running. exiting capture thread...
ffmpeg.Reja.detect             ERROR   : rtsp://{FRIGATE_PASSWORD}@192.168.100.36:554/live/ch00_0: Invalid data found when processing input
```

**Frigate stats**  : Cant find this
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera** : Dont know where to input that

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
![Screenshot_9](https://user-images.githubusercontent.com/20749038/131266928-bd3c0dbb-c65d-4798-91a4-463c7db81691.png)

**Computer Hardware**
 - OS: Home Assistant OS
 - Install method: Addon
 - Virtualization: No
 - Coral Version: No
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: ANNA TOSANI
 - Model: EC76-X15
 - Resolution: 1920X1080
 - FPS: 15

**Additional context**

This camera does not work, the commented camera does. the other camera is a tp link tapo c200
