### ISSUE TITLE
HA Custom Component High CPU Usage

### ISSUE THREAD

**Issue by ragenhe** [blakeblackshear/frigate#1654]
**Describe the bug**
HA custom component is causing very high (35%-50%) python cpu usage on frigate host. It's so bad, viewing the camera's via HA is faster than frigate's front end.  When HA is shutdown, frigate returns to normal and is very responsive.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: zcomms.lan

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  Garage:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://wyze-bridge:8554/garage
          roles:
            - detect
            - clips
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
    clips:
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: False
    detect:
      enabled: False
    record:
      enabled: False

  LivingRoom:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1080
    motion:
      mask:
        - 1585,0,1607,188,1285,185,1257,0
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
            - rtmp
            - detect
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
    clips:
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: False
    detect:
      enabled: False
    record:
      enabled: False

  Driveway:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://10.121.242.15:554/11
          roles:
            - clips
            - rtmp
            - detect
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
    clips:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
    detect:
      enabled: True
    record:
      enabled: False

  Mia-cam:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://wyze-bridge:8554/mia-cam
          roles:
            - detect
            - clips
            - rtmp
    clips:
      enabled: False
    rtmp:
      enabled: False
    snapshots:
      enabled: False
    detect:
      enabled: False
    record:
      enabled: False
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - cat
```

**Frigate container logs**
None

**Frigate stats**
```
{
  "Driveway": {
    "camera_fps": 5.1, 
    "capture_pid": 49, 
    "detection_fps": 0.0, 
    "pid": 43, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "Garage": {
    "camera_fps": 5.1, 
    "capture_pid": 46, 
    "detection_fps": 0.0, 
    "pid": 40, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "LivingRoom": {
    "camera_fps": 5.1, 
    "capture_pid": 48, 
    "detection_fps": 0.0, 
    "pid": 41, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "Mia-cam": {
    "camera_fps": 5.1, 
    "capture_pid": 54, 
    "detection_fps": 0.0, 
    "pid": 45, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 25.68, 
      "pid": 37
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 53.8, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 13.4
      }, 
      "/media/frigate/clips": {
        "free": 1263192.5, 
        "mount_type": "ext4", 
        "total": 1959684.5, 
        "used": 596874.0
      }, 
      "/media/frigate/recordings": {
        "free": 1263192.5, 
        "mount_type": "ext4", 
        "total": 1959684.5, 
        "used": 596874.0
      }, 
      "/tmp/cache": {
        "free": 960.5, 
        "mount_type": "tmpfs", 
        "total": 1000.0, 
        "used": 39.5
      }
    }, 
    "uptime": 1087, 
    "version": "0.8.4-5043040"
  }
}
```

**Computer Hardware**
 - OS: Debain
 - Install method: Docker Compose
 - Virtualization: 
 - Coral Version: USB
 - Network Setup: Cameras are wireless
