### ISSUE TITLE
Set go2rtc `webrtc.filter.candidates: []` by default

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#16583]
**Describe what you are trying to accomplish and why in non technical terms**
This is the real-world issue:

- https://github.com/blakeblackshear/frigate-hass-integration/issues/796

**Describe the solution you'd like**
Frigate can set go2rtc config to contain `webrtc.filter.candidates: []` by default.

- https://github.com/AlexxIT/go2rtc/issues/283#issuecomment-2659559377

**Describe alternatives you've considered**
Users can set it by themselves:

```yaml
# frigate.yaml

go2rtc:
  webrtc:
    # it is very important to hardcode "candidates" because of a bug that will otherwise cause "filters" to be ignored
    candidates:
      - 192.168.5.10:8555 # change to your IP
      - stun:8555
    filters:
      candidates: []
```

**Additional context**
I would be nice if there was some check to avoid doing this in case the container is running with `--network=host`.

**Comment by NickM-27** [comment]
Host is not recommended, so IMO the default value should match what is needed for the default frigate user.

**Comment by felipecrs** [comment]
Absolutely. It would just be nice to have and it could be a future improvement too.

**Comment by felipecrs** [comment]
@NickM-27, the new title you wrote is wrong. It should actually be the opposite. `webrtc.filter.candidates: []` should be set when NOT using host network. Otherwise, it's important it's NOT set.

**Comment by felipecrs** [comment]
There is a non-negligible chance this will reduce WebRTC negotiation time for all users. I.e. will make camera streams open faster through WebRTC.

**Comment by felipecrs** [comment]
A heads-up, I noticed the workaround/alternative is not currently working. You write:

```yaml
# frigate.yaml

go2rtc:
  webrtc:
    filters:
      candidates: []
```

And then the generated go2rtc config no longer contains it:

![Image](https://github.com/user-attachments/assets/475f760d-26bd-4598-abfc-6f08deea7e96)

This is probably a separate bug.
