### ISSUE TITLE
fmpeg sent a broken frame. memoryview assignment: lvalue and rvalue 

### ISSUE THREAD

**Issue by backslashV** [blakeblackshear/frigate#1661]
**Describe the bug**
The camera shows a green feed. There are ffmpeg related errors in the log. I am, however, able to see the camera feed just fine in VLC or in HA itself (via the docker-wyze-bridge addon).

**Version of frigate**
Output from `/api/version`
1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```
detectors:
  cpu1:
    type: cpu
mqtt:
  host: 192.168.0.121
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mymqtt
  password: mypass
  stats_interval: 60
cameras:
  garage_cam:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-cam
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    objects:
      track:
        - person
        - car
```

**Frigate container logs**
```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for garage_cam: 41
detector.cpu1                  INFO    : Starting detection process: 38
frigate.app                    INFO    : Capture process started for garage_cam: 42
frigate.video                  INFO    : garage_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage_cam: ffmpeg process is not running. exiting capture thread...
ffmpeg.garage_cam.detect       ERROR   : [tcp @ 0x556d829b80] Connection to tcp://127.0.0.1:8554?timeout=5000000 failed: 
```

**Frigate stats** where is this?
```
```

**FFprobe from your camera** Where do I run this? HA terminal doesn't have ffprobe installed

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8752221/131459686-95b1f6d6-125d-4c83-b01c-3ae5e0b26ab3.png)

**Computer Hardware**
OS: Home Assistant OS
Install method: Addon
Virtualization: No
Coral Version: No
Network Setup: Wfi

**Camera Info:**
 - Manufacturer: Wyze
 - Model: Cam V3
 - Resolution: 1920x1080
 - FPS: 20
