### ISSUE TITLE
DOCU update on keyword environt_vars?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#1662]
i use keyword "environment_vars:" in docker-composr like in documentation stated:
"https://blakeblackshear.github.io/frigate/configuration/advanced#environment_vars

but it throws an error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.frigate: 'environment_vars'
```

if i use keyword "environment:" i got an error on startup on frigate.yml
```
[services.d] starting services
[services.d] done.
Error parsing config: 'CAMPASS'
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
```
also for NVIDA the docu states to use dashes.
but at the end i am unsure about correct syntax.
 [may the docu needs an update](https://github.com/blakeblackshear/frigate/issues/105)? 

How do i pass the password?

edit: 
i cannot use "CAM130_PASS" or "CAMPASS", but i can use "FRIGATE_130=_PASS". 
throws error with start of frigate.yml.

do they envars-names  have to have a certain length? or start with "FRIGATE...."?

![image](https://user-images.githubusercontent.com/5937811/131463606-0e21ce9d-c881-482f-9459-581e9c04da4e.png)

**Comment by jasonpstokes** [comment]
Can't comment on the NVIDIA ones, but from the the [example in the docs](https://blakeblackshear.github.io/frigate/configuration/cameras#full-example) you can pass variables into your config:

`# NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}`

e.g. this works for me:

**docker-compose.yml**
```
    environment:
      FRIGATE_MQTT_PASSWORD: "87654321"
      FRIGATE_USER: "user"
      FRIGATE_PASSWORD: "12345678"

```
Frigate's **config.yml**
```
mqtt:
  host: 192.168.1.111
  port: 1883
  user: username
  password: "{FRIGATE_MQTT_PASSWORD}"

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: http://192.168.1.71/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - detect
        - path: http://192.168.1.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - record

```

**Comment by ozett** [comment]
yeah, looks like all envars have to start with 

```FRIGATE_...```

?

**Comment by ozett** [comment]
i got errors using the environment variables on the nvidia-container.
maybe bcause of mixing dashes and variables in yaml?

error complaints about block-collection:
```
ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./dc-frigate09.yml", line 73, column 7
expected <block end>, but found '?'
  in "./dc-frigate09.yml", line 75, column 7
```

snippet-yml:
```
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds

    environment:
      #environment_vars:
      FRIGATE_RTSP_PASSWORD: "pass"
      FRIGATE_130_PASS: "pass"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
```

anybody a hint? or bug-confirmation?
