### ISSUE TITLE
Ability to rotate the images in the GUI / More GUI customization.

### ISSUE THREAD

**Issue by Pgnee** [blakeblackshear/frigate#16695]
I'd specifically like to be able to rotate one of my cameras 90 degrees in the gui.  Have a dual wide camera in 90 degree rotation to get my whole side driveway.
If you really want more wants drag and drop moving of camera order would be awesome in the browser, I cant seem to figure it out as it sounded like it was supported.  I know we can re-order them with the order variable in the config, which I have done, but rotating the output would be amazing.

**Comment by hawkeye217** [comment]
Both of these features are already supported.


For camera rotation, you can configure this in your go2rtc stream configuration by adding a rotate parameter. Here's an example:

```yaml
go2rtc:
  streams:
    rtsp_cam: 
      - "ffmpeg:rtsp://username:password@192.168.0.49:554/stream1#video=h264#rotate=270#audio=aac"
```

You'll also need to ensure you set the correct width and height in your camera's detect configuration to match the rotated dimensions:

```yaml
detect:
  width: 1080
  height: 1920
```

See the go2rtc docs. https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg

Regarding camera reordering in the browser UI, I don't see any direct documentation about drag-and-drop functionality in the provided information sources, so I cannot provide specific guidance on that feature.

You can also reorder and resize your cameras if you set up a camera group in the UI. Add a camera group with the "+" icon in the left sidebar and then use the grid icon in the bottom right corner of the screen to reorder and resize them.
