### ISSUE TITLE
ver0.9-RC2 Timestamps on all Snapshots?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#1669]
**Describe the bug**
I dont have it configured, but
I see Timestamp on lower left side on all snapshots on all cams.

**Version of frigate**
DEBUG 0.9.0-46FE06E

frigate.yml (snippet of 1 cam)
```
snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 7

    mqtt:
      # per camera, All other messages will still be published.
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      #height: 500
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
```

I see Timestamp on lower left side on all snapshots on all cams.
i have snapshot and mqtt settings per camera, but all are the same.
and timestap is all off. for all cams.

is there a general configurationsetting for snapshots/timestamps which has to be used in 0.9x?
or is somehow a beta-bug?

![image](https://user-images.githubusercontent.com/5937811/131527040-31b0358f-35fa-49f6-98f6-f7f1651e7801.png)
