### ISSUE TITLE
Config defaults of Enabled options should be False

### ISSUE THREAD

**Issue by foxtrotcz** [blakeblackshear/frigate#16878]
**Describe what you are trying to accomplish and why in non technical terms**
I started configuring my first camera and I wanted just simple livestream, nothing else, and then maybe try additional features. I expected Frigate will just run what I configure so I set the most basic default:
```
mqtt:
  enabled: false

cameras:
  dahua1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://PATH # <----- The stream you want to use for detection
```

But framerate was low and CPU usage high so I wondered if maybe detection is enabled even if I didnt enable it. And thats exactly it. I found out detection is enabled by default, so I had to set:

```
    detect:
      enabled: False
```

**Describe the solution you'd like**
I just think it would be much more intuitive if all `Enabled` options were `False` by default. I would expect Frigate will only do what I tell it to do, not additional things by default.

For example the `mqtt` is enabled by default and I have to manually disable it in config. It would seem to me much more intuitive if I could just delete it from config and it would default to `enabled: false`

I would like to start with minimum and then just enable what I need.

**Describe alternatives you've considered**
I understand, I need to read the docs and thats what I will do. I will need to find all the options Frigate enables by default and disable them. And if I miss some my Frigate will do things I dont want just because I forgot to disable them. I just think it would be better the other way around.

I think Frigate is awesome and thanks for developing it. This is just my idea how it could be little more intuitive.
Thanks for consideration.
