### ISSUE TITLE
Camera motion masks override global motion masks

### ISSUE THREAD

**Issue by jasonpstokes** [blakeblackshear/frigate#1694]
**Describe the bug**
Gobal motion masks (e.g. to mask the timestamp on all camera's) are ignored when a camera-specific motion mask is defined. Should Camera motion masks be *added* to the global masks, rather than replace them?

```
motion:
  mask:
    - 265,650,265,625,630,625,630,650    <-- global masks are ignored on cameras with their own motion masks

cameras:
  Driveway:
    motion:
      mask: 
        - 0,585,29,592,60,617,74,672,0,672
```

**Version of frigate**
0.9.0-46fe06e
