### ISSUE TITLE
RC9 Question concerning events as the relate to 24/7 recordings

### ISSUE THREAD

**Issue by ragenhe** [blakeblackshear/frigate#1698]
Is it possible to enable events, without enabling 24/7 recordings?

If so, is this the correct way to accomplish?

```
    record:
      events:
        enabled: True
        objects:
          - person
  ```

**Comment by jasonpstokes** [comment]
No, but this will only keep recording segments which contain events:
```
record:
  enabled: true
  retain_days: 0
  events:
    enabled: true
    retain:
      default: 15
```
