### ISSUE TITLE
Getting an error trying to get object in zones working

### ISSUE THREAD

**Issue by Ming-A** [blakeblackshear/frigate#1702]
the error im getting is `Error parsing config: extra keys not allowed @ data['cameras']['carport-front']['zones']['insidecarport']['objects']`

This is my config. My goal was to create zones to stop parked cars in my carpark from getting events/clips
```
mqtt:
  host: 10.69.40.4
  user: mqtt-user
  password: *my password*
database:
  path: /media/frigate/database/frigate.db
cameras:
    carport-front:
        ffmpeg:
          inputs:
            - path: *rtsp link*
              roles:
                - detect
                - clips
                - record
                - rtmp
        width: 1920
        height: 1080
        fps: 5
        zones:
          insidecarport:
            coordinates: 1920,1080,1920,933,1841,747,1704,495,1351,257,0,276,0,1080
            objects:
              - person
              - motorcycle

          outsidecarport:
            coordinates: 713,260,1255,240,1684,436,1920,866,1920,0,0,0,0,346
            objects:
              - car
              - person
              - motorcycle
        clips:
          enabled: True
          retain:
            default: 28
          required_zones:
            - carport-outside
            - carport-inside
        snapshots:
          enabled: True
          retain:
            default: 28
        record:
          enabled: True
          retain_days: 31

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

```
