### ISSUE TITLE
Frigate in docker prolem: [Errno 21] Is a directory: '/config/config.yml'

### ISSUE THREAD

**Issue by hurleyhan888** [blakeblackshear/frigate#1710]
Trouble getting started, seems to be some mapping of the directory (?).  Relative newbie, have set up a few docker containers successfully though.  Can anyone help understand the issue please...

I ran docker command, stopped container, copied the config.yml to the folder, start again...but it keeps coming up with the same error.

**Version of frigate: docker command (docker compose same issues)**
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  -v /home/media/cctv:/media/frigate \
  -v /home/docker/frigate/config:/config/config.yml:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='##########' \
  -p 5000:5000 \
  -p 8935:1935 \
  blakeblackshear/frigate:stable-amd64

**Config file**
```
MQTT:
  host: 192.168.*.***
  stats_interval: 60

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

cameras:
# from wyze mrlt8 docker
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage-cam
          roles:
            - detect
    width: 1920
    height: 1080
    fps: 5
    objects:
      track:
        - person
```

**Frigate container logs**
```
:/home/docker$ docker logs frigate
 * Starting nginx nginx
   ...done.
Error parsing config: [Errno 21] Is a directory: '/config/config.yml'
 * Starting nginx nginx
   ...done.
```

**Computer Hardware**
 - OS: Ubuntu 20.04
 - Install method: Docker Command
 - Coral Version: None
 - Network Setup: Wired
```
bmax                        
    description: Notebook
    product: Intel (G5E7)
    width: 64 bits
    capabilities: smbios-3.2.0 dmi-3.2.0 smp vsyscall32
     *-cpu
          product: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
          size: 2360MHz
          capacity: 2700MHz
          clock: 100MHz
```

**Camera Info:**
 - Manufacturer: Wyze (running through docker mrlt8)
 - Model: V3
 - Resolution: 1080p
 - FPS: 5

**Additional context**
changed rtmp outside container to 8935 due to wyze streaming through 1935
