### ISSUE TITLE
No clips in events from Beward DC11EP

### ISSUE THREAD

**Issue by AlexObukhoff** [blakeblackshear/frigate#1712]
**Describe the bug**
No clips in detection events

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml

mqtt:
  host: 10.10.1.4

ffmpeg:
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy


cameras:

  #================================================================================================
  wicket:
    ffmpeg:
      inputs:
        - path: rtsp://ha:***@10.10.1.106:554/av0_1
          roles:
            - detect
            - rtmp
        - path: rtsp://ha:***@10.10.1.106:554/av0_0
          roles:
            - clips
            - record            
    width: 640
    height: 480
    fps: 5

    # Optional: Camera level object filters config.
    objects:
      track:
        - person
        - cat
        - dog

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 30

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
        - dog
      required_zones: []
      retain:
        # Required: Default retention days (default: shown below)
        default: 30

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False

  #================================================================================================
  hallway:
    ffmpeg:
      inputs:
        - path: rtsp://ha:***@10.10.1.180:554/ISAPI/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://ha:***@10.10.1.180:554/ISAPI/Streaming/Channels/101
          roles:
            - clips
            - record            
    width: 704
    height: 576
    fps: 5

    # Optional: Camera level detect settings
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    # Optional: Camera level object filters config.
    objects:
      track:
        - person

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 30

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      required_zones: []
      retain:
        # Required: Default retention days (default: shown below)
        default: 30

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False


  #================================================================================================
  porch:
    ffmpeg:
      inputs:
        - path: rtsp://user:***@10.10.1.105:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://user:***@10.10.1.105:554/h264Preview_01_main
          roles:
            - clips
            - record            
    width: 640
    height: 480
    fps: 5

    # Optional: Camera level object filters config.
    objects:
      track:
        - person
        - cat
        - dog

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 30

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
        - dog
      required_zones: []
      retain:
        # Required: Default retention days (default: shown below)
        default: 30

    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      # height: 270
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      # required_zones: []


  #================================================================================================
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://10.10.1.110:554/ch1.h264
          roles:
            - detect
            - rtmp
        - path: rtsp://10.10.1.110:554/ch0.h264
          roles:
            - clips
            - record            
    width: 640
    height: 360
    fps: 5

    # Optional: Camera level detect settings
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: False
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    # Optional: Camera level object filters config.
    objects:
      track:
        - person

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      required_zones: []
      retain:
        default: 30


detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

```

**Frigate container logs**
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5597a3d5f140] moov atom not found
/tmp/cache/wicket-20210904235951.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: wicket-20210904235951.mp4
ffmpeg.wicket.clips_record     ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.wicket.clips_record     ERROR   : [mp4 @ 0x55710524c1c0] Could not find tag for codec pcm_alaw in stream #1, codec not currently supported in container
ffmpeg.wicket.clips_record     ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
ffmpeg.wicket.clips_record     ERROR   : 
watchdog.wicket                INFO    : Terminating the existing ffmpeg process...
watchdog.wicket                INFO    : Waiting for ffmpeg to exit gracefully...
```

**Frigate stats**
```json
{
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 191.86, 
      "pid": 45
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 171.79, 
      "pid": 46
    }, 
    "cpu3": {
      "detection_start": 0.0, 
      "inference_speed": 175.56, 
      "pid": 47
    }, 
    "cpu4": {
      "detection_start": 0.0, 
      "inference_speed": 172.24, 
      "pid": 51
    }
  }, 
  "hallway": {
    "camera_fps": 5.1, 
    "capture_pid": 59, 
    "detection_fps": 0.0, 
    "pid": 55, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "kitchen": {
    "camera_fps": 4.8, 
    "capture_pid": 65, 
    "detection_fps": 0.0, 
    "pid": 57, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "porch": {
    "camera_fps": 5.1, 
    "capture_pid": 62, 
    "detection_fps": 0.0, 
    "pid": 56, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 63.6, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 3.5
      }, 
      "/media/frigate/clips": {
        "free": 3160422.2, 
        "mount_type": "btrfs", 
        "total": 6711487.7, 
        "used": 3551065.5
      }, 
      "/media/frigate/recordings": {
        "free": 3160422.2, 
        "mount_type": "btrfs", 
        "total": 6711487.7, 
        "used": 3551065.5
      }, 
      "/tmp/cache": {
        "free": 3160422.2, 
        "mount_type": "btrfs", 
        "total": 6711487.7, 
        "used": 3551065.5
      }
    }, 
    "uptime": 83896, 
    "version": "0.8.4-5043040"
  }, 
  "wicket": {
    "camera_fps": 5.1, 
    "capture_pid": 58, 
    "detection_fps": 0.0, 
    "pid": 54, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.2.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray -
-enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnapp
y --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --ena
ble-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxv
id --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --ena
ble-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[udp @ 000002c9fe51f200] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 000002c9fe532f80] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 000002c9fe543c80] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 000002c9fe553f80] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
Input #0, rtsp, from 'rtsp://ha:***@10.10.1.106:554/av0_0':
  Metadata:
    title           : av0_0
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x960, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

**Screenshots**

**Computer Hardware**
 - OS: Synology DSM 6.2.4-25556
 - Install method: Docker via Synology web UI
 - Virtualization: None
 - Coral Version: None
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Beward
 - Model: DC11EP
 - Resolution: 1280*960
 - FPS: 5

**Additional context**

**Comment by blakeblackshear** [comment]
It says the audio codec isn't supported by mp4. Can you switch to aac? If not, leave audio disabled in clips and record.

**Comment by AlexObukhoff** [comment]
Will adding a parameter `-na` to the recording settings help me?

```yaml
  #================================================================================================
  wicket:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -na

```

**Comment by blakeblackshear** [comment]
It's `-an`. Or you could remove your custom args entirely since that's in the defaults.

**Comment by AlexObukhoff** [comment]
Thanks!

**Comment by AlexObukhoff** [comment]
I successful resolve my problem:

```
  wicket:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:a aac -codec:v copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:a aac -codec:v copy
```

For ffmpeg command line I remove `-c copy` and add `-codec:a aac -codec:v copy`
