### ISSUE TITLE
Open in new tab, 404 Not Found , but ajax load is OK

### ISSUE THREAD

**Issue by laurentdebricon** [blakeblackshear/frigate#1719]
shift-click or middle-click or even opening manually the url gets me a 404 Not found error
![Screenshot from 2021-09-06 18-09-48](https://user-images.githubusercontent.com/736104/132243381-14f87304-6575-4aad-a203-64073aea7c86.png)

urls affected , all the one in my screenshot : 
- /events?camera=front
- /events/1630943033.916451-h2ye00
- middle click on picture

BUT normal click is working (ajax loaded)

**Version of frigate**
 1.13

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.26
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *****
  password: ******
  stats_interval: 60
cameras:
  front:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://192.168.1.26:8554/front-porch-cam 
          roles:
            - detect
            - clips
            - rtmp
    objects:
      track:
        - person
          #- car
          #- truck
          #- bicycle
          #- motorcycle
          #- dog
          #- cat
        # Optional: save clips configuration
    clips:
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 7
        # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 300
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 7
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 600
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
    record:
      # Optional: Enable recording
      enabled: True
      # Optional: Number of days to retain
      retain_days: 3
    width: 1920
    height: 1080
    fps: 5


```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
