### ISSUE TITLE
[Discussion] Recordings Vs Events vs Clips

### ISSUE THREAD

**Issue by ragenhe** [blakeblackshear/frigate#1720]
Could "clips" (aka Events) be handled independently of "recordings" and called clips?

It might just be me, but I struggle with the current terms and process of recordings and events tied together.

Yes, I know I can just ignore the recordings.  And I am trying LOL.

Just my thoughts / opinions......

Recordings = 24 x 7.
Events = Indicators within the recordings of motion event. Think timeline with marks. Very close already.
Clips = Short videos independent of recordings that would match the event with a + _n_ seconds padding pre and post event.

OK.  I said my "end user" piece.

I hope everyone has a wonderful and relaxing labor day.

**Comment by blakeblackshear** [comment]
What you described is actually how it works. I think it's just confusion around terminology. Clip files are not created automatically because they would just be duplicating video that is already stored, but they can be downloaded on demand.

**Comment by ragenhe** [comment]
Awesome.  Thank you!!

**Comment by ragenhe** [comment]
@blakeblackshear - I'm getting closer.

```
  Livingroom:
    motion:
      mask:
        - 1060,0,1077,129,855,125,840,0
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.121.242.3:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: False
      retain_days: 0
      events:
        enabled: True
        max_seconds: 180
        pre_capture: 5
        post_capture: 5
        objects:
          - person
      retain:
        default: 10
    rtmp:
      enabled: True
    snapshots:
      enabled: True
```

The above config is created an clip/event.  However, it cannot be played.

The white circle just spins or this error message is presented with a low res image behind it.
```The media could not be loaded, either because the server or network failed or because the format is not supported.```
