### ISSUE TITLE
clips removed from CameraRoleEnum

### ISSUE THREAD

**Issue by redbeardmcg** [blakeblackshear/frigate#1728]
**Describe the bug**
When configuring camera input roles, clips is no longer a valid option. If this is just a documentation issue, how do you configure the input for clips?

I see this in config.py for 0.9.2-rc2. missing clips:
```
class CameraRoleEnum(str, Enum):
    record = "record"
    rtmp = "rtmp"
    detect = "detect"
```

**Version of frigate**
0.9.0-rc2

**Config file**
```
cameras:
  front_yard:
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.25.103:554/s1
          roles:
            - detect
            - clips
    width: 640
    height: 360
    fps: 5
    motion:
      mask:
        - 0,139,102,136,123,180,197,175,278,174,373,178,428,181,524,187,544,172,640,178,640,0,0,0
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      bounding_box: True
      crop: True
      timestamp: False
    objects:
      filters:
        person:
          min_area: 1000
          threshold: .73
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - bicycle
        - car
        - motorcycle
```

**Frigate container logs**
```
Error parsing config: 4 validation errors for FrigateConfig
cameras -> front_yard -> ffmpeg -> inputs -> 0 -> roles -> 1
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
```
