### ISSUE TITLE
Objects smaller than zone-specific min_area still create events

### ISSUE THREAD

**Issue by fl42** [blakeblackshear/frigate#1738]
Hello,

**Describe the bug**

I added `min_area` for `person` in `zone1`.

```yaml
zones:
  zone1:
    coordinates: 0,1080,1920,1080,1920,...
    filters:
      person:
        min_area: 50000
```

However I still have person (actually it's a dog labelled as person...) smaller than 50k in events.
Note that these events don't have any zone (particularly they don't have zone1).
I would expect to not have any event (the detection should be considered as false positive) if the object is smaller than the specific min_area for this zone.

I don't know if it's a bug or a feature.
Actually my idea is to filter out false positives (too small persons) but only for zone1 (as in other parts of the camera persons could be smaller than 50k).

Is it expected? How to prevent events from being created?

**Version of frigate**
0.9.0-4b730a9

Thanks
