### ISSUE TITLE
UI - Ability to show/hide selected buttons

### ISSUE THREAD

**Issue by lenisko** [blakeblackshear/frigate#17416]
I would like to add config for UI to hide selected buttons without touching routes, so for example settings or logs could be accessed knowing a route. Opening a ticket before starting a change to get feedback and opinion.

It's meant to be a band-aid till proper user groups will be added and make it harder for trusted users (young or older ones for example) to make accidental changes in configuration or disabling monitoring (and forget to bring it back) leaving access to other features.

I was thinking about adding support for those as they are most destructive or unnecessary, keeping everything visible as default:
```yml
ui:
  ...
  # Optional: Ability to show or hide selected buttons in UI. Set false to hide selected option or button.
  # Changes are UI only, backend calls are still valid.
  buttons:
    # Optional: Camera view buttons
    camera:
      # Optional: Enable/Disable Detect button
      detect: true
      # Optional: Enable/Disable Recording button
      recording: true
      # Optional: Enable/Disable Snapshots button
      snapshots: true
    # Optional: Settings menu
    settings:
      # Optional: System Metrics menu
      system_metrics: true
      # Optional: System Logs menu
      system_logs: true
      # Optional: Settings menu
      settings: true
      # Optional: Configuration Editor menu
      configuration_editor: true
      # Optional: Restart Frigate menu
      restart_frigate: true
```
