### ISSUE TITLE
Marking as Detected over MQTT for any person match

### ISSUE THREAD

**Issue by keatontaylor** [blakeblackshear/frigate#1747]
**Describe the bug**
I've been toying with this for a few days and cannot figure out if this is intended behavior or not. 

I've currently got frigate setup to do person detection from a camera placed in the common area of my apartment. The goal is to use the camera feed to detect if a person is in the room and use the detections to keep the lights on. 

However, once the person has been still for a few minutes frigate will send an MQTT message that the camera is clear, even if the person is technically still being tracked when viewing the frigate Web UI. 

My guess is that while still (see adjustments to motion detection) that there isn't sufficient movement of the tracked object so it marks as clear.

My goal is to ensure that even someone sitting still is detected as shown in the preview. Sure this might produce some false positives about where the person actually is in the view, but traditional PIR sensors are used to turn the lights off. The tracking in frigate is just used to keep the lights on if a person is detected.

I hope all this makes sense and I understand if it is way outside the scope of the standard use case but figured I would make an attempt to ask if my idea is possible.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 10.0.1.27
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://<camera_ip>/live
          roles:
            - detect
    width: 1920
    height: 1080
    fps: 5

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
    
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
```
