### ISSUE TITLE
Detection appears to be stuck. Restarting detection process...

### ISSUE THREAD

**Issue by RobertusIT** [blakeblackshear/frigate#1751]
**Describe the bug**
A lot of trouble.
1 - **Detection appears to be stuck. Restarting detection process...**
So i can't have a stable and secure notification from my cameras. Missing a lot of detection with this error.

2 - GPU works but CPU is too high for 3 camera, i need to add others 3 camera, with 6 in total, so my cpu can't handle them. And i have Coral, with an high inference, 30ms.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```
########################################## MQTT SERVER 
mqtt:
  host: 192.168.178.51
  user: mqtt_user
  password: mqtt_user
########################################## GOOGLE CORAL USB
detectors:
  coral:
    type: edgetpu
    device: usb
#detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
########################################## INGRESSO
cameras:

  ingresso:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
   
      input_args:
        - -avoid_negative_ts
        - make_zero
      output_args:
#        rtmp: -c copy -f flv
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

      inputs:
        - path: rtmp://192.168.178.35/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
#            - detect
            - clips
#            - record
            - rtmp
    

        - path: rtmp://192.168.178.35/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=mypass    
          roles:
            - detect
#    width: 2560
#    height: 1920
    width: 640
    height: 480
    fps: 5
    detect:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: false
    snapshots:
      enabled: true
########################################## BALCONE GRANDE
  balcone_grande:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p

      input_args:
        - -avoid_negative_ts
        - make_zero
      output_args:
#        rtmp: -c copy -f flv
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: rtmp://192.168.178.49/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
#            - detect
            - clips
#            - record
            - rtmp
        - path: rtmp://192.168.178.49/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
            - detect        
#    width: 2560
#    height: 1920
    width: 640
    height: 480
    fps: 3
    detect:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: false
    snapshots:
      enabled: true
#    motion:
#      mask:
#        - 563,193,355,480,240,480,0,480,0,428,0,331,0,181,0,0,252,0,563,0,640,0,640,91,640,447,640,198
########################################## VERANDA
  veranda:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p

      input_args:
        - -avoid_negative_ts
        - make_zero
      output_args:
#        rtmp: -c copy -f flv
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: rtmp://192.168.178.33/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
#            - detect
            - clips
#            - record
            - rtmp
        - path: rtmp://192.168.178.33/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=mypass
          roles:
            - detect        
#    width: 2560
#    height: 1920
    width: 640
    height: 480
    fps: 5
    detect:
      enabled: true
    clips:
      enabled: true
    record:
      enabled: false
    snapshots:
      enabled: true
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for ingresso: 35
frigate.app                    INFO    : Camera processor started for balcone_grande: 36
frigate.app                    INFO    : Camera processor started for veranda: 37
frigate.app                    INFO    : Capture process started for ingresso: 39
frigate.app                    INFO    : Capture process started for balcone_grande: 41
frigate.app                    INFO    : Capture process started for veranda: 43
detector.coral                 INFO    : Starting detection process: 33
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
root                           INFO    : Waiting for detection process to exit gracefully...
root                           INFO    : Detection process didnt exit. Force killing...
detector.coral                 INFO    : Starting detection process: 128
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
```

**Frigate stats**
```{
  "balcone_grande": {
    "camera_fps": 3.0, 
    "capture_pid": 41, 
    "detection_fps": 0.0, 
    "pid": 36, 
    "process_fps": 3.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 33.4, 
      "pid": 128
    }
  }, 
  "ingresso": {
    "camera_fps": 5.0, 
    "capture_pid": 39, 
    "detection_fps": 0.0, 
    "pid": 35, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 2055.4, 
        "mount_type": "tmpfs", 
        "total": 2058.9, 
        "used": 3.6
      }, 
      "/media/frigate/clips": {
        "free": 22115.2, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 9578.8
      }, 
      "/media/frigate/recordings": {
        "free": 22115.2, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 9578.8
      }, 
      "/tmp/cache": {
        "free": 1737.3, 
        "mount_type": "tmpfs", 
        "total": 2058.9, 
        "used": 321.7
      }
    }, 
    "uptime": 514, 
    "version": "0.8.4-5043040"
  }, 
  "veranda": {
    "camera_fps": 5.1, 
    "capture_pid": 43, 
    "detection_fps": 0.0, 
    "pid": 37, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
i can't understand how to do that in windows, when i launch ffprobe.exe rtmp://192.168.178.35/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=mypass

but say:
stream user and password are not recognize, anyway on vlc works

ffprobe version 4.2.1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
rtmp://192.168.178.35/bcs/channel0_main.bcs?channel=0: I/O error
"stream" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
"user" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
"password" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
```

**Screenshots**
ingresso fullsize
![image](https://user-images.githubusercontent.com/11599774/132688968-05dc88a9-0677-46f9-8b47-dc24ca1bde7f.png)
ingresso substream
![image](https://user-images.githubusercontent.com/11599774/132689051-16bb7ee0-1887-42cb-b9e4-37f94149d7e7.png)
balcone_grande fullsize
![image](https://user-images.githubusercontent.com/11599774/132689136-d57370a7-1f46-4480-a81c-6ede1edb8c41.png)
balcone_grande substream
![image](https://user-images.githubusercontent.com/11599774/132689387-0d9bb6ba-fac8-409c-ab61-7b1d87b91a0a.png)
veranda is the same camera of balcone_grande

**Computer Hardware**
 - OS: HASSOS Supervised
 - Install method: HASSOS Supervised Virtual Machine
 - Virtualization: Proxmox
 - Coral Version: Google Coral USB , tried in USB NUC port and also in a usb hub with power DC not from usb.
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-520A (balcone_Grande and veranda) and RLC-410-5MP ( Ingresso )
 - Resolution: 2k
 - FPS: 5

**Additional context**
I have a NUC8i3BEH, with Proxmox.
Installed HASSOS Supervised, and Google Coral is with passtrough in a vm where is HASSOS.
I have a lot of trouble:

1 - I have an inference from coral about 30 46ms, too high, why?
2 - Frigate doesn't works liek expected because i have **Detection appears to be stuck. Restarting detection process...** and process maybe restart every time, so i can't get any notification or clips, only sometimes, but for the most of time, i can't.
3 - With cpu and without coral seems that doesn't happend, but i bought coral to have a better experiences.
4 - With coral i hope to have also a low cpu usage, but isn't this case, and i didn't figure out why.
I setup also a GPU passtrough, to get hw acc, but cpu is anyway high.
Here you can see the usage of CPU and also GPU, that is used.

![image](https://user-images.githubusercontent.com/11599774/132691081-95de506f-2a37-4e5f-b65a-e2a0b0a671c9.png)

[I follow this guide to GPU Passthrough ](https://cetteup.com/216/how-to-use-an-intel-vgpu-for-plexs-hardware-accelerated-streaming-in-a-proxmox-vm/) that share GPU and not dedicate GPU for a single VM, but GPU works, so CPU need to stay down, but... seems that i'm wrong somewhere....
