### ISSUE TITLE
Issue with video

### ISSUE THREAD

**Issue by interbiznw** [blakeblackshear/frigate#1753]
can anyone please tell me why the video on only one of my cameras does this? The actual stream does not do this when viewing directly, and also my actual NVR does not record things like this.. only appears in frigate, and messes up the clips/snapshots. Is there a setting I need to set?

its a REOLINK RLC-423 camera, 640x480 sub stream set for both the detect and clips

![image](https://user-images.githubusercontent.com/16450422/132782245-426aa1ac-d63a-4ccb-80e0-dbafd18f0397.png)

**Comment by joeShuff** [comment]
I have similar, again on reolink cameras (E1 Zoom). Unfortunately I don't have a solution, just commenting to follow if others fine a solution :)

**Comment by interbiznw** [comment]
I think I may have found the solution, check your camera with VLC and see if it responds on this url (replace 0.0.0.0 with camera ip and substitute username and password) :
`rtmp://0.0.0.0/bcs/channel0_sub.bcs?channel=0&stream=0&user=USERNAMEHERE&password=PASSWORDHERE`

Mine worked and I used that in frigate config for the path then also used the extra input args found in the docs

```
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - "5000000"
            - -use_wallclock_as_timestamps
            - "1```

**Comment by joeShuff** [comment]
Interesting, my camera does respond to that URL in VLC. It also works if I substitute `channel0_sub` with `channel0_main` for getting the full quality stream. Do you know what the benefits/drawbacks are with using rtmp instead of rtsp? From a quick google it seems like locally they'd be very similar.

I'm just testing moving from a 0.9.0 beta to a release candidate so I will give those input args a go and let you know!

Thanks!

**Comment by lukedukeus** [comment]
I had a similar issue, but was able to resolve it by giving my cameras more bandwitdth

**Comment by interbiznw** [comment]
> I had a similar issue, but was able to resolve it by giving my cameras more bandwitdth

Not a bandwidth issue here, all mine have full speed of a 1/10Gb network, and most cameras only have 100mbps adapters in them anyway. The above RTMP tweaks seemed to have fixed it for me so far. 


> Interesting, my camera does respond to that URL in VLC. It also works if I substitute `channel0_sub` with `channel0_main` for getting the full quality stream. Do you know what the benefits/drawbacks are with using rtmp instead of rtsp? From a quick google it seems like locally they'd be very similar.
> 
> I'm just testing moving from a 0.9.0 beta to a release candidate so I will give those input args a go and let you know!
> 
> Thanks!

Not sure of any benefits/drawbacks as it was the first I have seen of it or used it, but just thought I would give it a try since the docs mentioned reolink cameras, but just not mine specifically, although it seems to be an issue across the board possibly with reolink rtsp streams(something on their encoding doesn't decode well on the other end)

yes forgot to mention to change "sub" to "main" wherever you want those streams. I just used my reference that I use for the "detect" input so its the low quality one

**Comment by joeShuff** [comment]
After running for a few days on version 0.9.0 RC3, I've not noticed any need for different input args. My reolink camera has been running fine since and neither the recordings nor live view have the artifacts. No idea if there were actually any changes from either frigates end or ffmpegs end or if this is just a placebo effect. Running for like 5 days without issues is probably a good sign!

My config for the reolink camera is as follows

````
camera:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@IP:PORT
          roles:
            - rtmp
            - record
            - detect  
      output_args:    
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 2560
      height: 1920
      fps: 5
    record:
      enabled: true
      retain_days: 3
      events:
        enabled: true
        pre_capture: 3
        post_capture: 3
        objects:
          - person
          - cat
        retain:
          default: 7
          objects:
            person: 7
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
        objects:
          person: 14
    objects:
      track:
        - person
        - cat   
````
