### ISSUE TITLE
Multiple Frigate Proxies

### ISSUE THREAD

**Issue by KenwoodFox** [blakeblackshear/frigate#17669]
So I have two frigate instances running, one at an outbuilding with its own infrastructure for cameras and one at the main house, both have like, 10 or so cameras each. The reason they're separate is just to reduce the load on the bridge between buildings really. 

I noticed though when i was trying to add the second instance to our shared homeassistant ui that the yaml dosn't allow for more than one instance? even though i can hook both instances up to mqtt?

```yaml
server: http://<ip of first server>:5000
proxy_pass_host: true
proxy_pass_real_ip: true
```

I guess it wouldn't be a super big deal but could we just, spawn two frigate proxies? Maybe tweak it so its like this? And you get two sidebar icons?

Example:
```yaml
servers:
 - server: http://<server ip 1>:5000
  proxy_pass_host: true
  proxy_pass_real_ip: true
 - server: http://<server ip 2>:5000
  proxy_pass_host: true
  proxy_pass_real_ip: true
```

Using version `1.5` right now. Thanks!
