### ISSUE TITLE
0.9 RC3 - Live stream configuration for WebUI not working?

### ISSUE THREAD

**Issue by jasonpstokes** [blakeblackshear/frigate#1773]
The (new?) `live:` option does not appear to be working as per the updated docs?

As a global setting:
```yaml
live:
  height: 672
  quality: 8
```

...Frigate will not start, throwing:
```
[services.d] starting services,
[services.d] done.,
live,
Error parsing config: 1 validation error for FrigateConfig,
  extra fields not permitted (type=value_error.extra),
[cmd] python3 exited 1
```

As a camera setting, it does not change the height/size of the live image (my 4:3 camera image is still off the screen) but the quality takes a dive - like the image is resized smaller, then stretched to fit the original/default frame size?

**Version of frigate**
0.9 RC3

**Comment by Ixian** [comment]
I confirm I get the same error if I configure live globally.

It does work if you set it by camera.

**Comment by jasonpstokes** [comment]
Strange - thought it might be a cache issue, but force refreshing doesn't change the frame size for me. Just the resolution goes to crap! Here's my camera config - is this correct? Appreciate your followup.
```yaml
cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: http://192.168.1.71/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - detect
        - path: http://192.168.1.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_PASSWORD}
          roles:
            - record
    objects:
      filters:
        person:
          mask: 510,120,540,120,540,160,510,160
      track:
        - person
        - vehicle
        - dog
    live:
      height: 336  # half frame height
      quality: 8
```
