### ISSUE TITLE
MJPEG camera encoding clips to H 264 results in long video with no detected object

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#1776]
I have an MJPEG camera that works well for detection and clips that are not viewable in the app or the browser. I changed output arguments to encode the clips to H 264. The encoded video duration is more than 2 minutes (defaults on the clip duration were not changed) and doesn't have the detected person. The problem is with the second camera (front_porch).

**Version of frigate**
1.13`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
# frigate.yml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: xxx.xxx.xxx.xx
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  driveway:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,0,367,0,640,0,640,132,640,224,640,220,613,206,575,188,537,167,464,140,397,114,358,122,331,109,305,38,266,21,181,0,126,49,0,22 
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.6.xxx/2
          roles:
            - detect
        - path: rtsp://admin:xxxx@192.168.6.xxx/1
          roles:
            - clips            
    width: 640
    height: 352
    fps: 5  
    motion:
      mask:
        - 0,0,367,0,640,0,640,132,640,224,640,220,613,206,575,188,537,167,464,140,397,114,358,122,331,109,305,38,266,21,181,0,126,49,0,22         

    clips:
      enabled: true
      retain:
        default: 4
    snapshots:
      enabled: False
      bounding_box: True
      retain:
        default: 0
################################################        
  front_porch_camera:
    objects:
      track:
        - person


    ffmpeg:
      inputs:
        - path: http://admin:xxxx@192.168.6.xxx/video.cgi 
          roles:
            - detect
            - clips
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -r
            - "3" # <---- adjust depending on your desired frame rate from the mjpeg image
            - -use_wallclock_as_timestamps
            - "1"
      output_args:
          clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -pix_fmt yuv420p -an 
    width: 640
    height: 480
    fps: 5  
    clips:
      enabled: true
      retain:
        default: 7
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```{
  "detection_fps": 0.2, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 197.98, 
      "pid": 34
    }
  }, 
  "driveway": {
    "camera_fps": 5.1, 
    "capture_pid": 39, 
    "detection_fps": 0.2, 
    "pid": 36, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "front_porch_camera": {
    "camera_fps": 16.8, 
    "capture_pid": 40, 
    "detection_fps": 0.0, 
    "pid": 38, 
    "process_fps": 16.8, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1037.1, 
        "mount_type": "tmpfs", 
        "total": 1038.9, 
        "used": 1.8
      }, 
      "/media/frigate/clips": {
        "free": 999.9, 
        "mount_type": "ext4", 
        "total": 10870.8, 
        "used": 9300.2
      }, 
      "/media/frigate/recordings": {
        "free": 999.9, 
        "mount_type": "ext4", 
        "total": 10870.8, 
        "used": 9300.2
      }, 
      "/tmp/cache": {
        "free": 1014.6, 
        "mount_type": "tmpfs", 
        "total": 1038.9, 
        "used": 24.3
      }
    }, 
    "uptime": 3414, 
    "version": "0.8.4-5043040"
  }
}

```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-libsmbclient --enable-version3 --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzvbi --enable-lv2 --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mpjpeg, from 'http://admin:xxx@192.168.6.xxx/video.cgi':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 25 tbr, 25 tbn, 25 tbc
```

**Computer Hardware**
 - OS: HASS OS
 - Install method: Addon
 - Virtualization:  HASS OS running in a VM on KVM
 - Coral Version: None
 - Network Setup:Wired
 - 
**Camera Info:**
 - Manufacturer: D-Link
 - Model:  DCS-930L
 - Resolution: 480p
 - FPS: 25
