### ISSUE TITLE
Audio working live, no audio in recordings

### ISSUE THREAD

**Issue by HelloMihai** [blakeblackshear/frigate#17764]
Audio is working in firefox / chrome (not safari) for Live playback, but theres no audio in the recordings.

heres my config.  Thank you

```
mqtt: {enabled: false} ## if sending alerts to outher services like Home Assistant

## go2rtc restream combining audio with the video
go2rtc:
  streams:
    CAM_NAME_wyzeV2: [rtsp://myuser:mypassword@123.321.123.321/live, "ffmpeg:CAM_NAME_wyzeV2#audio=opus"]
    CAM_NAME_wyzeV3: [rtsp://myuser:mypassword@123.321.123.321/live, "ffmpeg:CAM_NAME_wyzeV3#audio=opus"]

## play stream created from go2rtc with audio mixed
cameras:
  CAM_NAME_wyzeV2:
    enabled: true
    audio: { enabled: true }
    record: { enabled: true, retain: {days: 5, mode: all} }
    ffmpeg:
      output_args: { record: preset-record-generic-audio-copy }
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV2, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]
      
  CAM_NAME_wyzeV3:
    enabled: true
    audio: {enabled: true}
    record: {enabled: true, retain: {days: 5, mode: all}}
    ffmpeg:
      output_args: { record: preset-record-generic-audio-copy }
      inputs: [{path: rtsp://127.0.0.1:8554/CAM_NAME_wyzeV3, input_args: preset-rtsp-restream, roles: [record, detect, audio]}]

version: 0.15-1
```
