### ISSUE TITLE
Object detected but clip does not include detected object (0.9.0-7B063A1)

### ISSUE THREAD

**Issue by Minglarn** [blakeblackshear/frigate#1779]
**Describe the bug**
Event list show a detected object but when watching the recorded clip the object is not there.

**Version of frigate**
0.9.0-7b063a1

**Config file**
Include your full config file wrapped in triple back ticks.
```
cameras:
#############################
#        PARKERING          #
#############################
  frigate_parkering:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.216/bcs/channel0_main.bcs?channel=0&stream=1&user=admin&password=xxxxxxxx
          roles:
            - record
            - detect

    detect:
      width: 2560
      height: 1920
      fps: 5
      enabled: True
      max_disappeared: 25 

    objects:
      track:
        - person
        - djur
        - motorfordon
        - cykel
      filters:
        person:
          min_score: 0.7
        motorfordon:
          min_score: 0.6

    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 960
      quality: 100

    motion:
      threshold: 20
      mask:
        - 0,1920,347,1920,744,920,156,947,852,142,2560,129,2560,0,0,0
    
   zones:
      street_area:
        # HI-RES
        coordinates: 1093,386,1195,445,2464,496,2428,89,781,48,586,478,771,403
        objects:
          - person
          - djur
          - cykel
          - motorfordon
      parking_area:
        coordinates: 2560,1920,331,1920,748,916,147,932,556,451,579,567,400,898,923,880,1177,487,2560,543      
        objects: 
          - motorfordon
          - person
          - cykel
          - djur
        filters:
          person:
            threshold: 0.7
          motorfordon:
            threshold: 0.7
####################################
#                                  #
#         MAIN SETTINGS            #
#                                  #
####################################

detectors:
  coral1:
    type: edgetpu
    device: 'usb:0'
  coral2:
    type: edgetpu
    device: 'usb:1'

mqtt:
  host: 192.168.1.121
  topic_prefix: frigate
  user: home-assistant-server
  password: xxxxx
  stats_interval: 20

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

  output_args:
    record:
      - -f
      - segment
      - -segment_time
      - 10
      - -segment_format
      - mp4
      - -reset_timestamps
      - 1
      - -strftime
      - 1
      - -c:v
      - copy

  input_args:
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-use_wallclock_as_timestamps'
    - '1' 
  
detect:
  max_disappeared: 20

motion:
  threshold: 20
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180

snapshots:
  bounding_box: true
  clean_copy: false
  crop: true
  enabled: true
  height: 600
  quality: 100
  retain:
    default: 6
  timestamp: false

objects:
  track:
    - djur
    - person
    - cykel
    - motorfordon
    - råtta
  filters:
    djur:
      threshold: 0.7
    person:
      threshold: 0.7
    cykel:
      threshold: 0.7
    motorfordon:
      threshold: 0.7
    råtta:
      threshold: 0.65

rtmp: 
  enabled: False

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    retain:
      default: 6

birdseye:
  enabled: true
  height: 600
  width: 800
  mode: motion
  quality: 10


logger:
  default: info

```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```
{
	"detection_fps": 0.0,
	"detectors": {
		"coral1": {
			"detection_start": 0.0,
			"inference_speed": 11.94,
			"pid": 218
		},
		"coral2": {
			"detection_start": 0.0,
			"inference_speed": 11.65,
			"pid": 220
		}
	},
	"frigate_baksida": {
		"camera_fps": 5.1,
		"capture_pid": 267,
		"detection_fps": 0.0,
		"pid": 243,
		"process_fps": 5.1,
		"skipped_fps": 0.0
	},
	"frigate_entren": {
		"camera_fps": 4.1,
		"capture_pid": 249,
		"detection_fps": 0.0,
		"pid": 234,
		"process_fps": 4.1,
		"skipped_fps": 0.0
	},
	"frigate_inne_garage": {
		"camera_fps": 4.1,
		"capture_pid": 274,
		"detection_fps": 0.0,
		"pid": 246,
		"process_fps": 4.1,
		"skipped_fps": 0.0
	},
	"frigate_lillstugan": {
		"camera_fps": 4.1,
		"capture_pid": 257,
		"detection_fps": 0.0,
		"pid": 240,
		"process_fps": 4.1,
		"skipped_fps": 0.0
	},
	"frigate_parkering": {
		"camera_fps": 5.0,
		"capture_pid": 248,
		"detection_fps": 0.0,
		"pid": 229,
		"process_fps": 5.0,
		"skipped_fps": 0.0
	},
	"frigate_pathway": {
		"camera_fps": 4.1,
		"capture_pid": 260,
		"detection_fps": 0.0,
		"pid": 241,
		"process_fps": 4.1,
		"skipped_fps": 0.0
	},
	"frigate_pryttelverkstad": {
		"camera_fps": 4.0,
		"capture_pid": 270,
		"detection_fps": 0.0,
		"pid": 244,
		"process_fps": 4.0,
		"skipped_fps": 0.0
	},
	"frigate_tomten": {
		"camera_fps": 4.1,
		"capture_pid": 254,
		"detection_fps": 0.0,
		"pid": 238,
		"process_fps": 4.1,
		"skipped_fps": 0.0
	},
	"service": {
		"storage": {
			"/dev/shm": {
				"free": 6400.9,
				"mount_type": "tmpfs",
				"total": 6442.5,
				"used": 41.5
			},
			"/media/frigate/clips": {
				"free": 117205.5,
				"mount_type": "ext3",
				"total": 125488.4,
				"used": 1881.1
			},
			"/media/frigate/recordings": {
				"free": 117205.5,
				"mount_type": "ext3",
				"total": 125488.4,
				"used": 1881.1
			},
			"/tmp/cache": {
				"free": 22861.7,
				"mount_type": "overlay",
				"total": 58275.8,
				"used": 32423.3
			}
		},
		"uptime": 6824,
		"version": "0.9.0-7b063a1"
	}
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/58695742/133296853-c68a70c9-e970-401e-b41c-1f2d5b988e52.png)
![Missing object_2](https://user-images.githubusercontent.com/58695742/133297908-8e9ab0b1-481d-470b-a4f8-3da44c577886.gif)

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: Reolink 
 - Model: 510A
 - Resolution: 2560x1920
 - FPS: 5

**Additional context**

**Comment by blakeblackshear** [comment]
Do you have messages in the logs about bad segments sometimes? I'm wondering if those segments were discarded from the beginning or if they were incorrectly removed afterwards.

**Comment by haggercody** [comment]
im getting a lot of stuff maybe similar-- i see a valid detection in the thumbnail but the clip seems to have just missed it.. one thing that i see is different is when i play the clip it doesnt actually start at frame 0 on the playerback line.. the ball is like at least halfway, as if the first part of the clip is corrupted?

**Comment by Minglarn** [comment]
> Do you have messages in the logs about bad segments sometimes? I'm wondering if those segments were discarded from the beginning or if they were incorrectly removed afterwards.

None what i've seen.. Running with debug at the moment... Will post if I see any errors..

**Comment by Minglarn** [comment]
I'm seeing this behaviour on all my cams. Even HikVisions...
With RC1 this did not exists. So there must be something with my config.yaml settings or a new type of event in RC3.

**Comment by blakeblackshear** [comment]
> im getting a lot of stuff maybe similar-- i see a valid detection in the thumbnail but the clip seems to have just missed it.. one thing that i see is different is when i play the clip it doesnt actually start at frame 0 on the playerback line.. the ball is like at least halfway, as if the first part of the clip is corrupted?

This is expected. It is trying to skip to the point where it thinks the event begins.

**Comment by blakeblackshear** [comment]
> I'm seeing this behaviour on all my cams. Even HikVisions...
> With RC1 this did not exists. So there must be something with my config.yaml settings or a new type of event in RC3.

It is more likely the timestamps are getting out of sync for the video segments. Can you compare the time in the file name against the timestamp in the video from your camera for the files in the recordings folder?

**Comment by haggercody** [comment]
> 
> It is more likely the timestamps are getting out of sync for the video segments. Can you compare the time in the file name against the timestamp in the video from your camera for the files in the recordings folder?

yea i checked one and i do see the timestamps don't match. for example in the web interface the event is listed as starting at 7:17:06 AM.  When i check the file it is named 17.22.mp4.  The content in the clip file matches what I see in frigate.

**Comment by haggercody** [comment]
also interestingly this is happening on an hikvision camera--my other 2 non hikvisions don't seem to have this, so i'll double check those settings (can't access the dashboard from my linux machine boo!).. but i'm pretty sure i am NOT using h264+

**Comment by blakeblackshear** [comment]
@haggercody you didn't provide your config, so your issue could be something very different. @Minglarn is using the same stream for record and detect.

**Comment by haggercody** [comment]
yup sorry here is the config i have for the camera experiencing this--perhaps similar because i use the same stream for record and detect as well?

```
  front:
    ffmpeg:

      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
    
      #input_args: -tag:v hvc1
      inputs:
        - path: rtsp://xxxx:xxx@192.168.10.203:554/Streaming/Channels/101
          roles:
            - detect #blah               
            - record
            - rtmp
    zones:
      front_door:
        coordinates: 132,1386,379,1520,788,1491,367,1205,160,1266

    detect:
      width: 2688
      height: 1520
      fps: 5
      enabled: True
      max_disappeared: 70

    motion:    
     mask:
        - 2688,0,2688,942,822,778,0,679,0,0

    objects:

      track:
        - person
        - dog

      filters:
        person:
          min_score: 0.5
          threshold: 0.7

    record: 
    # Optional: Enable recording (default: shown below)
      retain_days: 0
      enabled: True   
      events:
        objects:
          - person
          - dog
          
        pre_capture: 5
        # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 5
```
