### ISSUE TITLE
Sensor in HA for second zone not named correctly

### ISSUE THREAD

**Issue by ragenhe** [blakeblackshear/frigate#1780]
**Describe the bug**
I have sensors named correctly for my first zone (driveway). But my sensors for the second zone have the camera name, not the zone name.

**Version of frigate**
0.9.0-7b063a1

**Config file**
***Only the camera with the issue is included***
```
mqtt:
  host: 10.121.242.27

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects

cameras:
  Front:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://10.121.242.2:554/11
          roles:
            - record
            - rtmp
            - detect
    objects:
      track:
        - person
        - car
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5

    zones:
      driveway:
        coordinates: 356,583,0,781,0,1080,1557,1080,1722,588,1756,498,1857,445,1009,252,938,326
        objects:
          - car
          - person
      street:
        coordinates: 0,1080,0,169,189,68,757,49,1386,92,1920,230,1920,1080
        objects:
          - person
    record:
      enabled: True
      retain_days: 5
      events:
        max_seconds: 180
        pre_capture: 5
        post_capture: 5
        required_zones: [driveway, street]
        objects:
          - person
          - car
    rtmp:
      enabled: True
    snapshots:
      enabled: False
```

**Frigate stats**
```
{"Front":{"camera_fps":5.1,"capture_pid":239,"detection_fps":14.0,"pid":231,"process_fps":5.0,"skipped_fps":0.0},"Garage":{"camera_fps":5.0,"capture_pid":235,"detection_fps":6.3,"pid":226,"process_fps":5.0,"skipped_fps":0.0},"Livingroom":{"camera_fps":5.1,"capture_pid":237,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"Mia-cam":{"camera_fps":5.0,"capture_pid":232,"detection_fps":6.6,"pid":223,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":26.9,"detectors":{"coral":{"detection_start":1631642804.898189,"inference_speed":26.39,"pid":218}},"service":{"storage":{"/dev/shm":{"free":246.5,"mount_type":"tmpfs","total":268.4,"used":21.9},"/media/frigate/clips":{"free":1269405.0,"mount_type":"ext4","total":1959684.5,"used":590661.5},"/media/frigate/recordings":{"free":1269405.0,"mount_type":"ext4","total":1959684.5,"used":590661.5},"/tmp/cache":{"free":999.5,"mount_type":"tmpfs","total":1000.0,"used":0.5}},"uptime":1409,"version":"0.9.0-7b063a1"}}
```

**Screenshots**
![Screen Shot 2021-09-14 at 2 09 34 PM](https://user-images.githubusercontent.com/19781098/133310877-b9e9ccd9-f031-48a4-9601-f3b194e68db0.png)

**Computer Hardware**
 - OS: Debian
 - Install method: Docker Compose
 - Virtualization: 
 - Coral Version: USB
 - Network Setup:  Mixed
