### ISSUE TITLE
### Describe the problem you are having

### ISSUE THREAD

**Issue by volinvladim** [blakeblackshear/frigate#17888]
### Describe the problem you are having

Frigate 0.14.1 and Frigate 0.15.0-6d8234f restarts exactly every 20 minutes.
System:
Информация о системе
Версия	core-2025.1.4
Тип установки	Home Assistant Supervised
Среда разработки	false
Supervisor	true
Docker	true
Пользователь	root
Виртуальное окружение	false
Версия Python	3.13.1
Семейство операционных систем	Linux
Версия операционной системы	6.1.0-26-amd64
Архитектура ЦП	x86_64
Часовой пояс	Europe/Moscow
Каталог конфигурации	/config
Home Assistant Community Store
GitHub API	ok
GitHub Content	ok
GitHub Web	ok
HACS Data	ok
GitHub API Calls Remaining	5000
Installed Version	2.0.5
Stage	running
Available Repositories	1506
Downloaded Repositories	41
Home Assistant Cloud
Вход в систему	true
Срок действия подписки	1 января 2018 г. в 03:00
Relayer подключен	false
Регион ретранслятора	
Удалённый доступ активирован	true
Удалённый доступ подключен	false
Интеграция с Alexa	false
Интеграция с Google	false
cloud_ice_servers_enabled	true
Удалённый сервер	
Статус сертификата	
Instance ID	181713221ab64xxxxxxxxx
Доступ к серверу сертификатов	ok
Доступ к серверу аутентификации	ok
Доступ к Home Assistant Cloud	ok
Home Assistant Supervisor
Операционная система хоста	Debian GNU/Linux 12 (bookworm)
Канал обновлений	stable
Версия Supervisor	supervisor-2024.12.3
Версия агента	1.6.0
Версия Docker	27.3.1
Памяти доступно	115.4 GB
Памяти использовано	59.0 GB
Исправно	true
Поддержка	true
host_connectivity	true
supervisor_connectivity	true
ntp_synchronized	true
virtualization	
Supervisor API	ok
Version API	ok
Установленные дополнения	File editor (5.8.0), Samba share (12.4.0), ESPHome Device Builder (2024.12.4), Zigbee2MQTT (2.0.0-2), Home Assistant Google Drive Backup (0.112.1), Grafana (10.2.2), Terminal & SSH (9.16.0), RHVoice (1.0.3), VLC (0.3.0), RPC Shutdown (2.5), InfluxDB (5.0.1), Glances (0.21.1), Piper (1.5.2), Matter Server (7.0.0), Frigate (0.14.1), go2rtc (1.9.8), Frigate Beta (0.15.0-rc1)
Dashboards
Панели	2
Ресурсы	23
Вкладки	16
Режим	storage
Recorder
Время начала самого старого цикла	18 января 2025 г. в 05:33
Время начала текущего цикла	29 января 2025 г. в 10:09
Предполагаемый размер базы данных (MiB)	5696.90 MiB
Движок базы данных	sqlite
Версия базы данных	3.47.1
Core
Использование ЦП
4.2 %
Использование ОЗУ
15.1 %
Supervisor
Использование ЦП
0 %
Использование ОЗУ
2.8 %

### Version

 0.15.0-6d8234f and 0.14.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.22
  user: 
  password: 
  port: 8883
database:
  path: /config/frigate.db

review:
  alerts:
    labels:
      - car
      - person
      - cat
      - dog
      - bicycle
      - motorcycle
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:




  naves:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.168:554/1
          roles:
            - detect
        - path: rtsp://admin:pasword@192.168.1.168:554
          roles:
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 3
        pre_capture: 2
        post_capture: 2
      detections:
        retain:
          days: 3
        pre_capture: 2
        post_capture: 2
    detect:
      width: 1280
      height: 720
      fps: 3
    objects:
      track:
        - cat
        - dog
        - person
        - car
        - bicycle
        - motorcycle


  streetcam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.160/stream0
          roles:
            - detect
        - path: rtsp://admin:pasword@192.168.1.160/stream1
          roles:
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: false
      retain:
        default: 3

    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 3
        pre_capture: 2
        post_capture: 2
      detections:
        retain:
          days: 3
        pre_capture: 2
        post_capture: 2
    detect:
      width: 1280
      height: 720
      fps: 3
    objects:
      track:
        - person
        - cat
        - car
        - dog
        - bicycle
        - motorcycle

  ptzcam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.166:554
          roles:
            - detect
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3

    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 3
        pre_capture: 2
        post_capture: 2
      detections:
        retain:
          days: 3
        pre_capture: 2
        post_capture: 2
    detect:
      width: 1280
      height: 720
      fps: 3
    objects:
      track:
        - person
        - cat
        - car
        - dog
        - bicycle
        - motorcycle

  ogorod:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pasword@192.168.1.55:554
          roles:
            - detect
            - record
    snapshots: # <----- Enable snapshots
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 1280
      height: 720
      fps: 3
    objects:
      track:
        - cat
        - dog


      mask:
        - 0.672,0.548,0.672,0.821,0.967,0.721,0.996,0.51
        - 0.298,0.107,0.366,0.005,0.897,0.059,0.886,0.184

    record:
      enabled: true
      retain:
        days: 0
      alerts:
        retain:
          days: 10
        pre_capture: 10
        post_capture: 10
      detections:
        retain:
          days: 10
        pre_capture: 10
        post_capture: 10
  esp32cam2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.4:554/mjpeg/1
          roles:
            - detect
    snapshots:
      enabled: true
      retain:
        default: 3
    detect:
      width: 800
      height: 600
      fps: 5
    objects:
      track:
        - cat
        - dog

  esp32cam1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.2.5:554/mjpeg/1
          roles:
            - detect
    snapshots:
      enabled: true
      retain:
        default: 3
    detect:
      width: 800
      height: 600
      fps: 3
    objects:
      track:
        - cat
        - dog



version: 0.15-1
```

### Relevant Frigate log output

```shell
Log:
2025-01-29 19:44:30.446420761  F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
2025-01-29 19:44:30.446425259  Fatal Python error: Aborted
```

### Relevant go2rtc log output

```shell
not enable go2rts
```

### FFprobe output from your camera

```shell
what is it?
```

### Install method

HassOS Addon

### docker-compose file or Docker CLI command

```yaml
what is it?
```

### Object Detector

Coral

### Network connection

Wired

### Camera make and model

iptronics IPT_IPL1520

_Originally posted by @voldemar2022 in https://github.com/blakeblackshear/frigate/discussions/16220_
