### ISSUE TITLE
IPC socket failed for pathname /tmp/plasma

### ISSUE THREAD

**Issue by edge360** [blakeblackshear/frigate#179]
I'm running the latest release in docker and recently have been having my instance crash due to a plasma error. This has happened several times so far from what I can tell. It runs without issue for a few hours, then within 24 hours or so it crashes. The log is filled with the following errors.

Could RAM be a concern? Should I up it?

```
/arrow/cpp/src/plasma/io.cc:168: Connection to IPC socket failed for pathname /tmp/plasma, retrying 5 more times
/arrow/cpp/src/plasma/io.cc:/arrow/cpp/src/plasma/io.cc:168: Connection to IPC socket failed for pathname /tmp/plasma, retrying 168/arrow/cpp/src/plasma/io.cc: 5 more times:168: 
Connection to IPC socket failed for pathname /tmp/plasma, retrying 5 more times
```

config.yml
```
web_port: 5000

mqtt:
  host: 192.168.1.xxx
  topic_prefix: frigate
  user: xxx # Optional
  password: xxx # Optional

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

objects:
  track:
    - person
    - car
    - truck
    - cat
    - dog
    - bicycle
    - bus
    - boat
    - bird
  filters:
    person:
      min_area: 50000
      max_area: 600000
      threshold: 0.5
  take_frame: 1
  snapshots:
    show_timestamp: False

cameras:
  front_door:
    ffmpeg:
      input: rtsp:/xxx:xxx@192.168.1.xxx:7002/live/7
    take_frame: 1
    snapshots:
      show_timestamp: False
  driveway:
    ffmpeg:
      input: rtsp:/xxx:xxx@192.168.1.xxx:7002/live/2
    take_frame: 1
    snapshots:
      show_timestamp: False
  backyard:
    ffmpeg:
      input: rtsp:/xxx:xxx@192.168.1.xxx:7002/live/3
    take_frame: 1
    snapshots:
      show_timestamp: False
  street:
    ffmpeg:
      input: rtsp:/xxx:xxx@192.168.1.xxx:7002/live/6
    take_frame: 1
    snapshots:
      show_timestamp: False
  pan:
    ffmpeg:
      input: rtsp:/xxx:xxx@192.168.1.xxx:7002/live/5
    take_frame: 1
    snapshots:
      show_timestamp: False
  cat_cam:
    ffmpeg:
      input: rtsp:/xxx:xxx@192.168.1.xxx:7002/live/8
    take_frame: 1
    snapshots:
      show_timestamp: False
    mask: cat_cam_mask.bmp
    save_clips:
      enabled: True
      pre_capture: 5
```

docker-compose
```
frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: '1g' # should work for 5-7 cameras
    image: blakeblackshear/frigate:stable
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate:/config
    ports:
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

**Comment by jameswarner62** [comment]
I cannot assist, but also have seen this once or twice

**Comment by blakeblackshear** [comment]
I am planning to get rid of the plasma store in a future version.

**Comment by edge360** [comment]
I changed my 'shm_size' to '2g' just to try something different out. Also, added the below to my docker-compose as a potential workaround. I don't know if it will work, but worth a try in case others are having the same issue.

'''
    healthcheck:
      test: ["CMD", "test", "-e", "/tmp/plasma"]
      interval: 30s
      timeout: 10s
      retries: 6
'''

**Comment by mario-tux** [comment]
Same error here using 0.6rc1

**Comment by edge360** [comment]
For folks that are still experiencing this issue. Below is my amended health check for the docker container - fails if the plasma process exits and doesn't respawn.  The other was just checking for the existence of the socket file which is still present even if plasma crashes.  I'm using this along with autoheal to restart the container when the health check fails. Seems to be working so far... 

```
    healthcheck:
      test: ["CMD", "pgrep", "plasma"]
      interval: 30s
      timeout: 10s
      retries: 6
```
```
  autoheal:
    container_name: autoheal
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
