### ISSUE TITLE
Snapshots retained more than the set time.

### ISSUE THREAD

**Issue by sheminasalam** [blakeblackshear/frigate#1796]
I have seen that my snapshots are not cleared at the correct time. I have set the default retain to 1 day  but I can still find snapshots from 3 or 4 days back. Even when the majority of the snapshots are removed about 10 to 20% are retained. Here is the config of one of my camera.

```
detectors:
  coral:
    type: cpu
mqtt:
  host: 192.168.1.1
  port: 1883
  user: admin
  password: passowrd
  topic_prefix: frigate
ffmpeg:
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  hwaccel_args:
    - '-c:v'
    - h264
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    rtmp: '-c copy -f flv'
cameras:
  front_left_cam:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://user:pasword@192.168.1.100:554/cam/realmonitor?channel=8&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
    rtmp:
      enabled: false
    detect:      
      fps: 5
      height: 288
      width: 352
    motion:
      mask: >-
        21,288,44,166,107,74,176,30,231,0,269,32,325,42,304,157,253,288,281,288,352,288,352,0,0,0,0,234,0,288
    best_image_timeout: 30
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: false
      height: 352
      retain:
        default: 1 
    mqtt:
      timestamp: False
      crop: false
      height: 288
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.4
          max_area: 10000
          threshold: 0.6
          mask:
            - >-
              21,288,44,166,107,74,176,30,231,0,269,32,325,42,304,157,253,288,281,288,352,288,352,0,0,0,0,234,0,288
```
