### ISSUE TITLE
Camera fps argument not working

### ISSUE THREAD

**Issue by mcondren** [blakeblackshear/frigate#180]
Hello,

I noticed in my stats that my camera_fps was incorrect based on what is being served by my cameras.

`{"backporch":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":43,"frame_info":{"detect":1597328866.917589,"process":1597328866.917589,"read":1597328866.917589},"pid":74,"process_fps":15.1,"read_start":1597328866.918658,"skipped_fps":0.0},"coral":{"detection_start":0.0,"fps":2.3,"inference_speed":8.06,"pid":19},"driveway":{"camera_fps":14.9,"detection_fps":0.9,"ffmpeg_pid":27,"frame_info":{"detect":1597328866.840665,"process":1597328866.840665,"read":1597328866.840665},"pid":73,"process_fps":15.0,"read_start":1597328866.852901,"skipped_fps":0.0},"frontdoor":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":71,"frame_info":{"detect":1597328866.910861,"process":1597328866.910861,"read":1597328866.910861},"pid":76,"process_fps":15.0,"read_start":1597328866.911873,"skipped_fps":0.0},"plasma_store_rc":null,"sidedoor":{"camera_fps":15.0,"detection_fps":1.4,"ffmpeg_pid":47,"frame_info":{"detect":1597328866.882132,"process":1597328866.882132,"read":1597328866.882132},"pid":75,"process_fps":15.1,"read_start":1597328866.883255,"skipped_fps":0.0}}`

They are 15 but my cameras are serving 30 (in one case 25).  I added the -r input arg to 30 but it doesn't seem to be taking effect,  even after a reboot.

Here is an example from my config file.  Am I stipulating the fps wrong somehow?

```
sidedoor:
    ffmpeg:
      input: rtsp://192.168.1.2:7447/bcVBU7bqa8hkIrFO

      hwaccel_args:
        - -hwaccel
        - vaapi
        #- -hwaccel_device
        #- /dev/dri/renderD128
        #- -hwaccel_output_format
        #- yuv420p
      input_args:
        - -r
        - '30'

    take_frame: 1
    snapshots:
      show_timestamp: False
```
