### ISSUE TITLE
RTMP streams suddenly low res?

### ISSUE THREAD

**Issue by eblohm** [blakeblackshear/frigate#1805]
Using 0.9.0RC4, but the issue started on 0.9.0RC3. I haven't touched my config file, and I don't think anything was added as a breaking change that would cause this so I'm not sure what I'm not understanding properly.

Here's the config for one of my cameras:

```
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://USERNAME:PASSWORD@192.168.1.217:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://USERNAME:PASSWORD@192.168.1.217:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    motion:
      mask:
        - 1914,156,2517,160,2513,69,1916,69
    rtmp:
      enabled: true
    record:
      enabled: true
      retain_days: 25
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 25
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:
        default: 25
```

Pre- 0.9.0RC3 my RTMP streams would be full resolution of my camera (2592x1944) but now it's significantly lower. I'm assuming it's using the sub-stream that's being used by detect, but I'm not sure why. This specific camera is an Amcrest IP5M-T1179EW-28MM, but I'm running into it with all of my cameras (all Amcrest).
