### ISSUE TITLE
Support browser locale fully for date/time formats (24h and ISO date options)

### ISSUE THREAD

**Issue by frankvest** [blakeblackshear/frigate#18104]
Hi,

Currently, Frigate's UI uses AM/PM and US-style date formats in most views, even when the browser is set to a locale that prefers 24-hour clocks or ISO dates (e.g., da-DK, en-GB).

Feature request:
It would be great if Frigate’s web UI could fully respect the browser's locale when formatting time and date values. This would allow:

    24-hour time where the locale specifies it (e.g., Danish, German, UK users).

    ISO-style or localised date formats without needing manual configuration.

Why:

    This would improve usability for non-US users without adding complexity to the YAML config.

    It's a standard practice in modern web UIs to follow the user's locale for date/time display.

    For integrations (MQTT, API), keeping the current ISO8601 format is perfectly fine — this request is only for the UI.

Optional idea:
If full locale support is complex, perhaps adding a simple UI option or YAML override for time format could be considered in the future.

Thanks for considering, and thanks for a fantastic project!

**Comment by NickM-27** [comment]
This is already possible, you configure it like below:

```yaml
ui:
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  # timezone: America/Denver
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
```
