### ISSUE TITLE
Per-camera object tracker overrides should support 'excluding' from global

### ISSUE THREAD

**Issue by DPattee** [blakeblackshear/frigate#18108]
I have defined all the things I want to detect at the global level. On a per-camera basis I want to disable a few of the tracked things (eg there will never be a 'car' in the backyard) without having to type everything over. Having to type the full list of 'included' items at the per-camera level means if I decide to add something new (eg. 'deer') I have to update it in many places. 

**Describe the solution you'd like**
An 'exclude' option in the config where the overall global options are all imported MINUS what is listed

eg

```

objects:
  track:
    - person
    - face
    - car
    - bird
    - cat
    - dog
    - deer
    - raccoon
    - squirrel
    - rabbit
    - package

cameras:
  backyard:
    objects:
      track:
         - !car

```

would have the backyard camera track people, birds, dogs, etc the list from global but "not cars"
