### ISSUE TITLE
Same issue as roblamoreaux last November...

### ISSUE THREAD

**Issue by MangoCats** [blakeblackshear/frigate#18142]
I have a new Raspberry Pi 5 with the HAILO AI HAT+ soldered down version.  Followed the [recommended guide](https://www.raspberrypi.com/documentation/accessories/ai-kit.html#ai-kit-installation) for setting up the AI HAT+, and it seems to be working at that level:
```
pi@frigatepi:~ $ hailortcli fw-control identify
Executing on device: 0001:01:00.0
Identifying board
Control Protocol Version: 2
Firmware Version: 4.20.0 (release,app,extended context switch buffer)
Logger Version: 0
Board Name: Hailo-8
Device Architecture: HAILO8
Serial Number: <N/A>
Part Number: <N/A>
Product Name: <N/A>
```

I have setup frigate in a docker container on the Pi following this guide to the best of my ability, with this docker-compose.yaml:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/hailo0 # Our 26 TOPS HAILO AI HAT+ on the Raspberry Pi 5
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      #- /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/.config/frigate:/config
      - /home/pi/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "554:554" # RTSP feeds
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

It is working fine via port 5000 to view my RTSP camera stream, but when I try to activate the detector using this config.yaml:

```
pi@frigatepi:~/.config/frigate $ cat config.yaml 
mqtt:
  enabled: false

detectors:
  hailo0:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef

cameras:
  Tranquility:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://notMyUser:notMyPass@192.168.100.101:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
    zones:
      Near_Gate:
        coordinates: 1,0.523,0.524,0.423,0.536,0.135,1,0.136
        loitering_time: 0
        inertia: 3
      Driveway:
        coordinates: 0.519,0.516,0.534,0.131,0.199,0.152,0.198,0.475
        loitering_time: 0
        inertia: 3
      Mulch:
        coordinates: 0.195,0.511,0.198,0.151,0,0.152,0,0.511
        loitering_time: 0
    motion:
      mask: 0.991,0.07,0.775,0.07,0.776,0.015,0.991,0.018
    review:
      detections:
        required_zones:
          - Near_Gate
          - Driveway
          - Mulch
      alerts:
        required_zones:
          - Near_Gate
          - Driveway
          - Mulch
version: 0.15-1
```

I get the same crash on restart (and looping restart) as roblamoreaux reported below.

Am I missing something obvious?

Thanks,

> I just got a Raspberry Pi AI kit, but installed the HAILO M.2 card in a dual M.2 adapter I already had my SSD in. I am running Home assistant on a Raspberry Pi 5 and hope to use the AI to get frigate to efficiently monitor 2 or 3 cameras.
> 
> 
> 
> I can get Frigate 15 Beta1 running without the Hailo detector configured, And Home Assistant lists the Hailo hardware. 
> 
> 
> 
> But when I configure the Hailo it crashes with the log messages  below. Any idea of what I am doing wrong or if this will work?
> 
> 
> 
> `2024-11-15 00:51:01.368056656  Process detector:hailo8l:
> 
> 2024-11-15 00:51:01.368061656  Traceback (most recent call last):
> 
> 2024-11-15 00:51:01.368063064    File "/opt/frigate/frigate/detectors/plugins/hailo8l.py", line 72, in __init__
> 
> 2024-11-15 00:51:01.368063990      self.target = VDevice()
> 
> 2024-11-15 00:51:01.368069342  NameError: name 'VDevice' is not defined
> 
> 2024-11-15 00:51:01.368070046  
> 
> 2024-11-15 00:51:01.368071138  During handling of the above exception, another exception occurred:
> 
> 2024-11-15 00:51:01.368072823  
> 
> 2024-11-15 00:51:01.368073935  Traceback (most recent call last):
> 
> 2024-11-15 00:51:01.368102343    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
> 
> 2024-11-15 00:51:01.368105009      self.run()
> 
> 2024-11-15 00:51:01.368106102    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
> 
> 2024-11-15 00:51:01.368106935      return run(*args, **kwargs)
> 
> 2024-11-15 00:51:01.368108009    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
> 
> 2024-11-15 00:51:01.368154159      self._target(*self._args, **self._kwargs)
> 
> 2024-11-15 00:51:01.368156270    File "/opt/frigate/frigate/object_detection.py", line 109, in run_detector
> 
> 2024-11-15 00:51:01.368175530      object_detector = LocalObjectDetector(detector_config=detector_config)
> 
> 2024-11-15 00:51:01.368177585    File "/opt/frigate/frigate/object_detection.py", line 61, in __init__
> 
> 2024-11-15 00:51:01.368178715      self.detect_api = create_detector(detector_config)
> 
> 2024-11-15 00:51:01.368179807    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
> 
> 2024-11-15 00:51:01.368180604      return api(detector_config)
> 
> 2024-11-15 00:51:01.368181733    File "/opt/frigate/frigate/detectors/plugins/hailo8l.py", line 105, in __init__
> 
> 2024-11-15 00:51:01.368182659      except HailoRTException as e:
> 
> 2024-11-15 00:51:01.368197012  NameError: name 'HailoRTException' is not defined
> 
> 2024-11-15 00:51:01.371586280  [2024-11-14 19:51:01] detector.hailo8l               INFO    : Starting detection process: 413
> 
> 2024-11-15 00:51:01.371684690  [2024-11-14 19:51:01] frigate.detectors.plugins.hailo8l INFO    : Initializing Hailo device as PCIe
> 
> 2024-11-15 00:51:01.371709264  [2024-11-14 19:51:01] frigate.detectors.plugins.hailo8l INFO    : A model file already exists at /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef not downloading one.
> 
> 2024-11-15 00:51:01.413910687  [2024-11-14 19:51:01] frigate.app                    INFO    : Output process started: 429
> 
> `
> 
>  

 _Originally posted by @roblamoreaux in [#11961](https://github.com/blakeblackshear/frigate/issues/11961#issuecomment-2477730550)_
