### ISSUE TITLE
Event thumbnails not accessible / created

### ISSUE THREAD

**Issue by SgtBatten** [blakeblackshear/frigate#1821]
**Describe the bug**
I am unable to load thumbnails using the frigate API. 
Thumbnails also do not display in the HA Media Browser for jpg or mp4 files found in media/frigate/clips.
```
http://192.168.1.25:5000/api/frigate/notifications/1632265959.30984-7mzpvz/thumbnail.jpg returns a 404 not found
http://192.168.1.25:5000/api/<other things here> do work
```

I discovered this issue while attempting to setup android notifications. The notifications fire but no image is attached, just the text "A person was detected".

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.1.25
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
cameras:
  entrycam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.25:8554/entry
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 5
    
    zones:
      front_door:
        coordinates: 1013,0,955,413,1055,482,1131,0
      garbage_bins:
        coordinates: 194,1080,635,1080,520,737,171,786

    # Optional: Camera level detect settings
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 25

    # Optional: save clips configuration
    clips:
      # Required: enables clips for the camera (default: False)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - dog
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30

    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: False)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: False)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: False)
      bounding_box: False
      # Optional: crop the snapshot (default: False)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: False
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

    motion:
      mask:
        # left wall
        - 0,0,0,656,0,1080,229,1080,222,844,260,508,323,261,332,0
        # high right wall
        - 1920,0,1920,292,1670,218,1380,152,1118,113,1138,0
        # timestamp
        - 1382,1057,1866,1055,1865,1016,1380,1016
        # Other side of the street
        - 971,0,968,43,331,67,338,0

    # Optional: Camera level object filters config.
    objects:
      track:
        - person
        # - car
        # - dog
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below
      # filters:
      #   person:
      #     min_area: 5000
      #     max_area: 100000
      #     min_score: 0.5
      #     threshold: 0.7
      #     # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      #     # Checks based on the bottom center of the bounding box of the object
      #     mask: 
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera entrycam has rtmp assigned to an input, but rtmp is not enabled.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 31
frigate.app                    INFO    : Camera processor started for entrycam: 36
detector.cpu2                  INFO    : Starting detection process: 33
frigate.app                    INFO    : Capture process started for entrycam: 37
```

**Frigate stats**
```json
{
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 457.54, 
      "pid": 31
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 441.53, 
      "pid": 33
    }
  }, 
  "entrycam": {
    "camera_fps": 5.1, 
    "capture_pid": 37, 
    "detection_fps": 0.0, 
    "pid": 36, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 6191.6, 
        "mount_type": "tmpfs", 
        "total": 6195.3, 
        "used": 3.7
      }, 
      "/media/frigate/clips": {
        "free": 20008.5, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 11685.5
      }, 
      "/media/frigate/recordings": {
        "free": 20008.5, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 11685.5
      }, 
      "/tmp/cache": {
        "free": 6186.7, 
        "mount_type": "tmpfs", 
        "total": 6195.3, 
        "used": 8.6
      }
    }, 
    "uptime": 7583, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe rtsp://192.168.1.25:8554/entry
ffprobe version 3.2.2 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[udp @ 00000000006d3500] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 00000000006e4180] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[rtsp @ 00000000006b9860] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://192.168.1.25:8554/entry':
  Metadata:
    title           : Stream
  Duration: N/A, start: 0.006489, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn, 40 tbc
```

**Screenshots**

**Computer Hardware**
 - OS: Home assistant supervised OS running as a VM on a windows server
 - Install method: Addon
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: None
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Wyze
 - Model: Wyze cam v3
 - Resolution: 1080p
 - FPS: 20, 15 at night. 

**Additional context**

Notification automation
Light turns on, notification is sent, no image is in the notification.
```
  alias: Motion Notifications
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
  action:
  - service: light.turn_on
    target:
      entity_id: light.switch_outside_front_door
  - service: notify.mobile_app_pixel_4a
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected.
      data:
        image: https://homeassistant.mydomain.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
  mode: single
```
![image](https://user-images.githubusercontent.com/24822223/134291424-d662acaf-26b7-4436-8a42-63c4fe7e0473.png)
