### ISSUE TITLE
HA Automation Help

### ISSUE THREAD

**Issue by jonwilliams84** [blakeblackshear/frigate#1833]
I am struggling to get HA automations working :-( 

Can someone tell me the error of my ways please?

```
alias: When Bruce goes near Sofa
trigger:
   platform: mqtt
   topic: frigate/events
condition:
   - "{{ trigger.payload_json['after']['label'] == 'dog' }}"
   - "{{ 'sofa' in trigger.payload_json['after']['zones'] }}"
action:
  - service: notify.mobile_app_sm_g981b
    data_template:
      message: "The {{trigger.payload_json['after']['label']}} is near the sofa."
      data:
        image: "https://hass.domain.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/thumbnail.jpg"
        tag: "{{trigger.payload_json['after']['id']}}"
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
  - service: notify.alexa_media
    data:
      message: >-
        <prosody volume="x-loud"><amazon:effect name='spoken'>Bruce is near the Sofa.</amazon:effect></prosody>
      data:
        type: announce
        method: speak
      target:
        - media_player.kitchen_echo
        - media_player.bedroom_echo_dot
```

I followed the guide, however it's expects "entered_zones" in the json payload...which doesn't exist, so have substituted this for just 'zones'.

If I 'Run Actions' - Alexa does the notification (but I don't get the phone message because obviously trigger.payload is empty when running it from Automations - Run Actions).  

However, when real events happen of this payload and condition it doesn't get triggered at all.

Thanks in advance!
