### ISSUE TITLE
Performance degradation in rc4 compared to rc2

### ISSUE THREAD

**Issue by blasebast** [blakeblackshear/frigate#1835]
![Screenshot 2021-09-24 at 12 59 07](https://user-images.githubusercontent.com/25853397/134664218-b03008ea-2376-47ad-8d16-60a31f38fa2b.png)
**ISSUE DESCRIPTION:**
Hi, thanks for all the great work. 
I would like to report that there is performance degradation after upgrading from rc2 to rc4 (amd64)
Due to this I have reverted to `0.9.0-rc2-amd64`   from `0.9.0-rc4-amd64`.
If course config had to be amended to upgrade, but I kept the same zones and number of cameras is also the same, so changes were related only to new structure required for rc4 `frigate/config.yml`

**CONFIG**
```
mqtt:
  host: {HOSTNAME}
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: {MOSQUITTO_PW}
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  frigate_reolink_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REO_PW}@{NET_PREF}.139:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2560
      height: 1920
      fps: 15

    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          mask:
            - 0,0,0,393,0,1026,197,1020,1125,1003,1606,1001,1642,698,1387,504,1062,197,960,185,987,0
            - 1646,526,2560,555,2560,229,2560,0,925,0,926,81,926,184,1295,193,1296,249
        car:
          mask:
           - 2560,1920,1868,1920,1980,1201,2560,1163
    motion:
      mask:
        - 0,0,0,393,0,1026,197,1020,1125,1003,1606,1001,1642,698,1387,504,1062,197,960,185,987,0
        - 1646,526,2560,555,2560,229,2560,0,925,0,926,81,926,184,1295,193,1296,249

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True

    zones:
      reolink_1_gate_detection_zone:
        coordinates: 1284,191,1276,320,1204,304,1211,181
        filters:
          person:
            min_area: 20
            max_area: 1000
            threshold: 0.65

      reolink_1_detection_zone:
        coordinates: 1679,371,2560,569,2560,1182,1799,1581,1756,1920,1507,1920,1160,1920,0,1920,0,1019,1635,1020,1081,181,1272,193,1469,379
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          car:
            min_area: 2000
            max_area: 100000
            threshold: 0.7

    record:
      enabled: True
      retain_days: 14
      events:
        retain:
          default: 14


  frigate_reolink_2:
    ffmpeg:
      input_args:
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://admin:{FRIGATE_REO_PW}@{NET_PREF}.62:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2560
      height: 1920
      fps: 10

    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          mask:
            - 888,26,1786,71,2529,570,2477,860,2560,958,2560,0,558,0
    motion:
      mask:
        - 888,26,1786,71,2529,570,2477,860,2560,958,2560,0,558,0

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True

    zones:
      reolink_2_detection_zone:
        coordinates: 382,56,0,1920,2560,1920,2496,569,1769,71,1363,49,1260,194,763,198
        filters:
          person:
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          car:
            min_area: 2000
            max_area: 100000
            threshold: 0.7

      reolink_2_terrace_edge:
        coordinates: 963,0,1032,264,777,265,771,0
        filters:
          person:
            threshold: 0.7

    record:
      enabled: True
      retain_days: 7
      events:
        retain:
          default: 14

  frigate_hikvision_1:
    ffmpeg:
      inputs:
        - path: rtsp://rtsp:{FRIGATE_HIK_PW}@{NET_PREF}.64:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15

    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          mask:
            - 449,843,0,1080,0,830,0,25,961,0,1920,0,1920,619,1097,291,976,213,807,224,495,534
    motion:
      mask:
        - 449,843,0,1080,0,830,0,25,961,0,1920,0,1920,619,1097,291,976,213,807,224,495,534

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True

    zones:
      hikvision_1_detection_zone:
        coordinates: 274,609,841,926,909,1080,1920,1080,1920,618,995,229,783,238
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.77
          bicycle:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          car:
            min_area: 2000
            max_area: 100000
            threshold: 0.7

    record:
      enabled: True
      retain_days: 14
      events:
        retain:
          default: 14

  frigate_hikvision_2:
    ffmpeg:
      inputs:
        - path: rtsp://rtsp:{FRIGATE_HIK_PW}@{NET_PREF}.65:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15

    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        car:
          mask:
            - 1037,409,830,372,797,299,874,199,1021,0
        person:
          mask:
            - 578,389,577,290,372,296,0,333,0,646
            - 1021,0,982,163,681,192,0,333,0,0
    motion:
      mask:
        - 578,389,577,290,372,296,0,333,0,646
        - 1021,0,982,163,681,192,0,333,0,0

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True

    zones:
      hikvision_2_detection_zone:
        coordinates: 579,384,559,224,737,189,1297,125,1566,1080,0,1080,0,634
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          car:
            min_area: 2000
            max_area: 100000
            threshold: 0.7

    record:
      enabled: True
      retain_days: 10
      events:
        retain:
          default: 14

  frigate_hikvision_3:
    ffmpeg:
      inputs:
        - path: rtsp://rtsp:{FRIGATE_HIK_PW}@{NET_PREF}.67:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15

    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          mask:
            - 1442,433,1920,619,1920,0,0,0,0,267
            - 0,855,253,653,449,670,572,561,487,391,343,395,341,0,0,0
    motion:
      mask:
        - 1442,433,1920,619,1920,0,0,0,0,267
        - 0,855,253,653,449,670,572,561,487,391,343,395,341,0,0,0

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True

    zones:
      hikvision_3_detection_zone:
        coordinates: 1920,1080,1920,613,1457,424,1358,399,1053,357,1015,262,734,215,519,280,315,286,0,1080
        filters:
          person:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            threshold: 0.7
          car:
            min_area: 2000
            max_area: 100000
            threshold: 0.7

    record:
      enabled: True
      retain_days: 10
      events:
        retain:
          default: 14
```
