### ISSUE TITLE
Proxmox + HassOS = No VA display found for device /dev/dri/renderD128

### ISSUE THREAD

**Issue by steemsjo** [blakeblackshear/frigate#1846]
**Describe the bug**
Trying to use Frigate and have hardware acceleration does not work.

**Version of frigate**
Frigate HassOS addon version 1.14

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
cameras:
  ######################
  frigate_front_door:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.0.0.xxx:554/H.264 # 1536x1536 @ 5-15fps
          roles:
            - clips
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    width: 1536
    height: 1536
    fps: 3
    motion:
      frame_height: 333
      mask:
        - 1118,1536,1536,1536,1536,1465,1118,1464
        - 0,113,274,109,270,0,0,0
        - 1397,1201,1461,1067,1512,913,1483,875,1282,1107,1214,1238,1187,1400
    detect:
        # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
        max_disappeared: 25
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
        - dog
      retain:
        default: 2
        objects:
          person: 14

  ######################
  frigate_terrace:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.0.0.xxx:554/H.264 # 1920x1080 @ 5-15fps
          roles:
            - clips
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    width: 1920
    height: 1080
    fps: 3
    motion:
      frame_height: 333
      mask:
        - 0,1080,666,1080,668,998,0,993
        - 0,123,285,103,282,0,0,0
    detect:
        # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
        max_disappeared: 25
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.7
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
        - dog
      retain:
        default: 2
        objects:
          person: 14

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

**Frigate container logs**
```
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for frigate_front_door: 45
frigate.app                    INFO    : Camera processor started for frigate_terrace: 47
detector.cpu2                  INFO    : Starting detection process: 40
frigate.app                    INFO    : Capture process started for frigate_front_door: 49
detector.cpu3                  INFO    : Starting detection process: 41
detector.cpu4                  INFO    : Starting detection process: 42
detector.cpu1                  INFO    : Starting detection process: 39
frigate.app                    INFO    : Capture process started for frigate_terrace: 54
frigate.video                  INFO    : frigate_terrace: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : frigate_terrace: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : frigate_front_door: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : frigate_front_door: ffmpeg process is not running. exiting capture thread...
ffmpeg.frigate_terrace.detect  ERROR   : [AVHWDeviceContext @ 0x55e63d4f0d00] No VA display found for device /dev/dri/renderD128.
ffmpeg.frigate_terrace.detect  ERROR   : Device creation failed: -22.
ffmpeg.frigate_terrace.detect  ERROR   : [hevc @ 0x55e63d499bc0] No device available for decoder: device type vaapi needed for codec hevc.
ffmpeg.frigate_terrace.detect  ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
ffmpeg.frigate_front_door.detect ERROR   : [AVHWDeviceContext @ 0x563b07233d40] No VA display found for device /dev/dri/renderD128.
ffmpeg.frigate_front_door.detect ERROR   : Device creation failed: -22.
ffmpeg.frigate_front_door.detect ERROR   : [hevc @ 0x563b0722fb80] No device available for decoder: device type vaapi needed for codec hevc.
ffmpeg.frigate_front_door.detect ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : frigate_terrace: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : frigate_terrace: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : frigate_front_door: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : frigate_front_door: ffmpeg process is not running. exiting capture thread...
ffmpeg.frigate_terrace.detect  ERROR   : [AVHWDeviceContext @ 0x5620bd0a3b80] No VA display found for device /dev/dri/renderD128.
ffmpeg.frigate_terrace.detect  ERROR   : Device creation failed: -22.
ffmpeg.frigate_terrace.detect  ERROR   : [hevc @ 0x5620bd097600] No device available for decoder: device type vaapi needed for codec hevc.
ffmpeg.frigate_terrace.detect  ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
ffmpeg.frigate_front_door.detect ERROR   : [AVHWDeviceContext @ 0x562172788940] No VA display found for device /dev/dri/renderD128.
ffmpeg.frigate_front_door.detect ERROR   : Device creation failed: -22.
ffmpeg.frigate_front_door.detect ERROR   : [hevc @ 0x562172788a40] No device available for decoder: device type vaapi needed for codec hevc.
ffmpeg.frigate_front_door.detect ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : frigate_terrace: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : frigate_terrace: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : frigate_front_door: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : frigate_front_door: ffmpeg process is not running. exiting capture thread...
```

**Frigate stats**
```json
{
  "cameras": {
    "frigate_front_door": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": [
          "person",
          "cat",
          "dog"
        ],
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 2,
          "objects": {
            "person": 14
          }
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:password@10.0.0.xxx:554/H.264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frigate_front_door-%Y%m%d%H%M%S.mp4 -r 3 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "clips",
            "detect"
          ]
        }
      ],
      "fps": 3,
      "frame_shape": [
        1536,
        1536
      ],
      "height": 1536,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 333,
        "mask": [
          "1118,1536,1536,1536,1536,1465,1118,1464",
          "0,113,274,109,270,0,0,0",
          "1397,1201,1461,1067,1512,913,1483,875,1282,1107,1214,1238,1187,1400"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "frigate_front_door",
      "objects": {
        "filters": {
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.7,
            "threshold": 0.8
          }
        },
        "mask": null,
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 14,
          "objects": {}
        },
        "timestamp": true
      },
      "width": 1536,
      "zones": {}
    },
    "frigate_terrace": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": [
          "person",
          "cat",
          "dog"
        ],
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 2,
          "objects": {
            "person": 14
          }
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:password@10.0.0.xxx:554/H.264 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frigate_terrace-%Y%m%d%H%M%S.mp4 -r 3 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "clips",
            "detect"
          ]
        }
      ],
      "fps": 3,
      "frame_shape": [
        1080,
        1920
      ],
      "height": 1080,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 333,
        "mask": [
          "0,1080,666,1080,668,998,0,993",
          "0,123,285,103,282,0,0,0"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "frigate_terrace",
      "objects": {
        "filters": {
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.7,
            "threshold": 0.8
          }
        },
        "mask": null,
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 14,
          "objects": {}
        },
        "timestamp": true
      },
      "width": 1920,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu2": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu3": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu4": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "10.0.0.xxx",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "user"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**Computer Hardware**
 - OS: Proxmox 7.0-11 + Home Assistant OS 6.4
 - CPU: Intel i5-4570

**Camera Info:**
 - Manufacturer: EzViz
 - Model: DB1C
 - Model: C3W Pro

**Additional context**
- Commenting out the `hwaccel_args` works but of course without hardware acceleration. 
- Proxmox output:
![Capture](https://user-images.githubusercontent.com/1563817/134773766-c0fd4326-008e-4681-9c16-a8c4f224fdd7.JPG)

- I can specify the RTSP stream with H264 or H265, but both open up with the same codec information given by VLC:
![Capture](https://user-images.githubusercontent.com/1563817/134774004-3f0ba7c0-7b30-4701-a59d-f1b8c014ac4e.JPG)
