### ISSUE TITLE
Cameras from different manufacturers are not possible in one frigate.yml session

### ISSUE THREAD

**Issue by HB1311** [blakeblackshear/frigate#1851]
**Describe the bug**
I have four cameras. Three  SV3C und one LUPUS LE201. It is possible to have the htree SV3C cameras in a frigate.yml. Frigate is running good, all cameras ans there entities are good. It is possible to have one SV3C und the LUPUS LE201 in a frigate.yml. All running well. BUT, is is impossible to have two SC3C cameras and the LUPUS LE201 camera! Only the SV3C cameras running, but not the LUPUS LE 201.
**Version of frigate**
Output from `/api/version`
Frigate  NVR version 1.14
**Config file**
Include your full config file wrapped in triple back ticks.

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: 192.168.178.121
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: SoNoffHAneu
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: H13110296b87HA
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  # Name of your camera
  
  # Name of your camera
  
    # Name of your camera

  auffahrt:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_mmal
      inputs:
        - path: rtsp://admin:1311HB0296NAS@192.168.178.38:554/12 
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
        # Optional: save clips configuration
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: False
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 3
        # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 3
    width: 640
    height: 352
    fps: 5 
  lohe:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_mmal
      inputs:
        - path: rtsp://adminmit:11Hb87iKNAS@192.168.178.29:554/11
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
        - bird
        - mouse
        # Optional: save clips configuration
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: False
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 3
        # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 3
    width: 640
    height: 480
    fps: 5  
  garage:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_mmal
      inputs:
        - path: rtsp://admin:1311HB0296@192.168.178.87:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
        - bird
        - mouse
        # Optional: save clips configuration
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: False
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 3
        # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        # Optional: Per object retention days
        objects:
          person: 3
    width: 640
    height: 480
    fps: 5  
```

**Frigate container logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for auffahrt: 37
frigate.app                    INFO    : Camera processor started for lohe: 38
detector.cpu1                  INFO    : Starting detection process: 34
frigate.app                    INFO    : Camera processor started for garage: 39
frigate.app                    INFO    : Capture process started for auffahrt: 40
frigate.app                    INFO    : Capture process started for lohe: 42
frigate.app                    INFO    : Capture process started for garage: 44
frigate.video                  INFO    : garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage: ffmpeg process is not running. exiting capture thread...
ffmpeg.garage.detect           ERROR   : mmal: mmal_vc_port_enable: failed to enable port vc.ril.video_decode:in:0(H264): ENOMEM
ffmpeg.garage.detect           ERROR   : mmal: mmal_port_enable: failed to enable port vc.ril.video_decode:in:0(H264)(0xf25ba0) (ENOMEM)
ffmpeg.garage.detect           ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0xf25ba0) is not enabled
ffmpeg.garage.detect           ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:out:0(I420)(0xf25eb0) is not enabled
ffmpeg.garage.detect           ERROR   : Error while opening decoder for input stream #0:0 : Unknown error occurred
frigate.video                  INFO    : garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage: ffmpeg process is not running. exiting capture thread...
ffmpeg.garage.detect           ERROR   : mmal: mmal_vc_port_enable: failed to enable port vc.ril.video_decode:in:0(H264): ENOMEM
ffmpeg.garage.detect           ERROR   : mmal: mmal_port_enable: failed to enable port vc.ril.video_decode:in:0(H264)(0x1534da0) (ENOMEM)
ffmpeg.garage.detect           ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:in:0(H264)(0x1534da0) is not enabled
ffmpeg.garage.detect           ERROR   : mmal: mmal_port_disable: port vc.ril.video_decode:out:0(I420)(0x151d770) is not enabled
ffmpeg.garage.detect           ERROR   : Error while opening decoder for input stream #0:0 : Unknown error occurred
frigate.video                  INFO    : garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : garage: ffmpeg process is not running. exiting capture thread...
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
