### ISSUE TITLE
Object masks not working?

### ISSUE THREAD

**Issue by eblohm** [blakeblackshear/frigate#1857]
I'm fairly certain this is an issue on my end, but I'm not positive. I have a Wyze Cam v2 set up with RTSP enabled in my living room and the view of the camera picks up the TV. I don't want it thinking every time something happens or a person appears on the TV to create an event/snapshot, but I can't get the masks to work to prevent it from happening, so I get _tons_ of snapshots and events in that cameras log because of detections from the TV. Here's my config for the camera:

```
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://USERNAME:PASSWORD@192.168.1.222/live
          roles:
            - rtmp
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      filters:
        person:
          mask:
            - 570,0,499,358,113,288,195,0
        cat:
          mask:
            - 570,0,499,358,113,288,195,0
        dog:
          mask:
            - 570,0,499,358,113,288,195,0
      track:
        - person
        - cat
        - dog
    rtmp:
      enabled: true
    record:
      enabled: true
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 3
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:
        default: 3
```

My masks are all position to cover the TV but it's still not working.
