### ISSUE TITLE
Download Clip displayed for events that have no associated clip

### ISSUE THREAD

**Issue by shred86** [blakeblackshear/frigate#1860]
**Describe the bug**
The "DOWNLOAD CLIP" button is still displayed for events that do not have a clip associated with it. When you click the link, a 18 byte file called `clip.mp4.html` is downloaded.

How this case occurs is based on having `required_zones` specified. For example, I only want recordings (clips) for things in the `sidewalk` and `driveway` zones. However, anything in the `street` zone (or really anything not in the `sidewalk` or `driveway` zones) will create an event with no associated recording. They do still produce a snapshot.

Edit: So I have a feeling these events with no clips are occurring because I didn't specify `required_zones` for `snapshots`. I'm testing that now but in any case, this is still a "bug" where I think the desired behavior should be the "DOWNLOAD CLIP" is only displayed if there's actually a clip associated with the event.

**Version of frigate**
0.90 RC5

**Config file**
```yaml
mqtt:
  host: <redacted>
  user: <redacted>
  password: <redacted>
cameras:
  front:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - detect
            - rtmp
        - path: <redacted>
          roles:
            - record
    objects:
      track:
        - person
        - vehicle
        - animal
    record:
      events:
        required_zones:
          - sidewalk
          - driveway
    zones:
      street:
        coordinates: 0,499,1222,186,926,44,512,37,0,117
      sidewalk:
        coordinates: 0,493,1081,217,995,172,501,257,0,378
      driveway:
        coordinates: 315,720,1280,720,1280,386,1194,345,1085,439,752,328,195,479
    motion:
      mask:
        - 1015,228,1280,170,1280,0,889,0
  side:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - detect
            - rtmp
        - path: <redacted>
          roles:
            - record
    objects:
      track:
        - person
        - animal
    motion:
      mask:
        - 267,0,299,65,1133,720,1280,720,1280,0
  back:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - detect
            - rtmp
        - path: <redacted>
          roles:
            - record
    objects:
      track:
        - person
        - animal
    motion:
      mask:
        - 902,31,1097,71,1280,141,1280,0,0,0,0,43
  inside:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - detect
            - rtmp
        - path: <redacted>
          roles:
            - record
    motion:
      mask:
        - 1280,0,1280,40,435,43,440,0

record:
  enabled: True
  retain_days: 7
  events:
    retain:
      default: 14

model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: pci
```

**Frigate container logs**
```
N/A
```

**Frigate stats**
```json
N/A
```

**FFprobe from your camera**

Run the following command and paste output below
```
N/A
```

**Screenshots**
![example](https://user-images.githubusercontent.com/32663154/135009188-3574ad1d-74aa-4b20-a741-c5f0172c3004.jpg)

**Computer Hardware**
 - OS: Debian 11
 - Install method: Docker Compose
 - Virtualization: N/A
 - Coral Version: PCIe
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Loryta (Dahua)
 - Model: 5442
 - Resolution: 720p
 - FPS: 5

**Additional context**
