### ISSUE TITLE
Publish Blank Plate State After Detection

### ISSUE THREAD

**Issue by federicotravaini** [blakeblackshear/frigate#18738]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have the same authorized vehicle open our company gate more than once in a row— for example, when it leaves at night and then returns in the morning— without having to intervene manually. Right now, once Frigate recognizes a license plate, Home Assistant never sees a new state change if that same plate is detected again, so the gate automation doesn’t re-trigger.

**Describe the solution you'd like**
Add a built-in “state reset” or “blank publish” feature to Frigate’s MQTT plate publisher. For instance, after publishing a plate value you could automatically publish an empty payload (or a specific “null” topic) after a short, configurable delay (e.g. 1 s). This way Home Assistant would see the sensor go from blank → “recognized_plate” every time the plate is detected, reliably firing the gate-opening automation.

**Describe alternatives you've considered**

- Forcing a reset of the HA sensor state via a separate Home Assistant automation or script, but Frigate immediately republished the old plate and canceled my override.

**Additional context**

- Frigate version: 0.16 beta 3
- Integration stack: Frigate → MQTT → Home Assistant → Shelly 1L → gate motor
- Labeling logic in Frigate: All allowed plates are assigned labels like PT_<machine_name> (e.g. PT_federico).

HA Automation

```
alias: FRIGATE PLATE > OPEN GATE
description: Automazione che usa nuove entità di Frigate 0.16
triggers:
  - platform: state
    entity_id:
      - sensor.inside_last_recognized_plate
      - sensor.outside_last_recognized_plate
conditions:
  - condition: template
    value_template: "{{ trigger.to_state.state.upper().startswith('PT_') }}"
  - condition: state
    entity_id: schedule.orari_cancello_mensa
    state: "on"
actions:
  - service: switch.turn_on
    target:
      entity_id: switch.shelly1_483fdaa0c760
  - service: notify.ntfy
    data:
      title: "Cancello Aperto ✅"
      message: "0.16:{{ trigger.entity_id }}={{ trigger.to_state.state }}"
  - delay: "00:00:55"
mode: single
```

- What happens now: Frigate publishes e.g. PT_federico once when it first sees the plate, but never clears that value. When the same plate passes again, HA doesn’t detect any state change, so the gate stays closed.
- Desired behavior: Frigate should clear or blank the plate state after publishing, so each new recognition—even of the same plate—triggers a fresh state change in Home Assistant.
