### ISSUE TITLE
Can zones be nested?

### ISSUE THREAD

**Issue by ragenhe** [blakeblackshear/frigate#1879]
Can I have a large zone, ie. entire_front, used for person objects.

Then within entire_front, have driveway, used for car objects?

Person objects _everywhere_, then additional cars in the driveway?

Thanks!

**Comment by blakeblackshear** [comment]
Yes. They can even span multiple cameras.

**Comment by ragenhe** [comment]
Thanks @blakeblackshear - I might have followups.

**Comment by ragenhe** [comment]
Camera level ```objects```.  Is it necessary if it is also defined in other areas?

```
  Front:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://10.121.242.2:554/11
          roles:
            - record
            - rtmp
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
    objects:
      track:
        - person
        - car
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
      max_disappeared: 75
    zones:
      driveway:
        coordinates: 0,1080,1534,1080,1682,756,649,464,0,781
        objects:
          - car
      entire_front:
        coordinates: 0,1080,0,117,372,61,850,54,1472,126,1920,232,1920,1080
        objects:
          - person
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
        max_seconds: 180
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
        required_zones:
          - entire_front
          - driveway
    rtmp:
      enabled: True
    snapshots:
      enabled: False
```
