### ISSUE TITLE
Camera not recording clips?

### ISSUE THREAD

**Issue by eblohm** [blakeblackshear/frigate#1880]
I've had this issue since I set the camera up but I was sure I'd be able to figure it out myself but I can't. It's a Wyze Cam v2 with the official RTSP firmware flashed. I can view the stream and RTMP of the camera and events _are_ created, but it doesn't record anything. The snapshot of the event shows, but there's no option to play anything, and if I try to download the clip, my browser just says "Failed - No File".  Using 0.9.0RC5

Config:
```
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://USERNAME:PASSWORD@192.168.1.222/live
          roles:
            - rtmp
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      filters:
        person:
          mask:
            - 685,0,608,489,0,449,0,54,0,0
        cat:
          mask:
            - 685,0,608,489,0,449,0,54,0,0
        dog:
          mask:
            - 685,0,608,489,0,449,0,54,0,0
    record:
      enabled: true
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - dog
          - cat
        retain:
          default: 3
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 3
```

Debug related to the camera:
```
"living_room": {
  "best_image_timeout": 60,
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 1080,
    "max_disappeared": 25,
    "width": 1920
  },
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "inputs": [
      {
        "global_args": [],
        "hwaccel_args": [],
        "input_args": [],
        "path": "rtsp://USERNAME:PASSWORD@192.168.1.222/live",
        "roles": [
          "rtmp",
          "detect",
          "record"
        ]
      }
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "ffmpeg_cmds": [
    {
      "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://USERNAME:PASSWORD@192.168.1.222/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/living_room-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/living_room -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
      "roles": [
        "rtmp",
        "detect",
        "record"
      ]
    }
  ],
  "live": {
    "height": 720,
    "quality": 8
  },
  "motion": {
    "contour_area": 99,
    "delta_alpha": 0.2,
    "frame_alpha": 0.2,
    "frame_height": 180,
    "mask": "",
    "threshold": 25
  },
  "mqtt": {
    "bounding_box": true,
    "crop": true,
    "enabled": true,
    "height": 270,
    "quality": 70,
    "required_zones": [],
    "timestamp": true
  },
  "name": "living_room",
  "objects": {
    "filters": {
      "cat": {
        "mask": [
          "685,0,608,489,0,449,0,54,0,0"
        ],
        "max_area": 24000000,
        "min_area": 0,
        "min_score": 0.5,
        "threshold": 0.7
      },
      "dog": {
        "mask": [
          "685,0,608,489,0,449,0,54,0,0"
        ],
        "max_area": 24000000,
        "min_area": 0,
        "min_score": 0.5,
        "threshold": 0.7
      },
      "person": {
        "mask": [
          "685,0,608,489,0,449,0,54,0,0"
        ],
        "max_area": 24000000,
        "min_area": 0,
        "min_score": 0.5,
        "threshold": 0.7
      }
    },
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": true,
    "events": {
      "max_seconds": 300,
      "objects": [
        "dog",
        "cat"
      ],
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 3,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": true,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 3,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  },
  "zones": {}
},
```
