### ISSUE TITLE
[Frigate 0.9.0 RC5] Event videos contain no event

### ISSUE THREAD

**Issue by fbcd4f50ea5350f051450323b5abfd0b** [blakeblackshear/frigate#1881]
**Describe the bug**
Sometimes I have the problem that an event has a very good snapshot/preview, but the video does not contain the event. The recognized object is then simply not visible. It looks as if a different point in time was recorded.

**Version of frigate**
0.9.0-aa807d2

**Config file**
```yaml
logger:
  default: info
  # logs:
  #   frigate.events: debug

detectors:
  coral1:
    type: edgetpu
    device: pci:0

mqtt:
  host: IP
  topic_prefix: frigate
  client_id: frigate
  user: USER
  password: PASS
  stats_interval: 600

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rw_timeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - "1"
    - -f 
    - live_flv
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128

detect:
  enabled: True
  width: 2560
  height: 1440
  fps: 5
  max_disappeared: 100

objects:
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - cat
    - dog

record:
  enabled: True
  retain_days: 0
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - motorcycle
      - bicycle
      - cat
      - dog
    retain:
      default: 30

snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  retain:
    default: 30

rtmp:
  enabled: False

timestamp_style:
  position: "tl"
  format: "%d.%m.%Y %H:%M:%S"
  thickness: 1

cameras:
  carport:
    ffmpeg:
      inputs:
        - path: rtmp://IP/bcs/channel0_main.bcs?channel=0&stream=0&user=USER&password=PASS
          roles:
            - detect
            - record
    best_image_timeout: 240

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True
      height: 360

    objects:
      filters:
        car:
          mask:
            - 811,1147,1062,912,1138,844,1496,712,1448,425,1671,158,2560,87,2560,1440,722,1440
    
    zones:
      carport_cars:
        coordinates: 349,1440,1000,413,1549,398,1549,189,2560,189,2560,1440,1571,1440
      carport_road:
        coordinates: 1560,184,1556,391,993,418,351,1440,0,1440,0,189

  entrance:
    ffmpeg:
      inputs:
        - path: rtmp://IP/bcs/channel0_main.bcs?channel=0&stream=0&user=USER&password=PASS
          roles:
            - detect
            - record
    best_image_timeout: 240

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True
      height: 360

    motion:
      mask:
        - 1562,0,2560,0,2560,1440,1909,1440
        - 0,1440,0,0,518,0,647,860,996,936,1060,1440

    zones:
      entrance_steps:
        coordinates: 1124,1180,1029,944,638,849,616,642,1273,549,1300,356,1740,389,1904,1440,940,1440
        objects:
          - person
      entrance_road:
        coordinates: 627,262,662,0,1742,0,1691,364

  frontdoor:
    ffmpeg:
      inputs:
        - path: rtmp://IP/bcs/channel0_main.bcs?channel=0&stream=0&user=USER&password=PASS
          roles:
            - detect
            - record
    best_image_timeout: 240

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: True
      height: 360

    motion:
      mask:
        - 1946,0,2560,0,2560,1440,1760,1440
        - 0,0,844,0,970,1440,0,1440
    
    zones:
      frontdoor_steps:
        coordinates: 1982,82,2560,82,2560,1440,1762,1440
      frontdoor_door:
        coordinates: 853,84,1980,84,1773,1389,991,1373
```

**Frigate container logs**
Nothing relevant found

**Frigate stats**
```json
{"carport":{"camera_fps":5.1,"capture_pid":232,"detection_fps":0.0,"pid":219,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.19,"pid":215}},"entrance":{"camera_fps":5.3,"capture_pid":237,"detection_fps":0.0,"pid":222,"process_fps":5.3,"skipped_fps":0.0},"frontdoor":{"camera_fps":5.4,"capture_pid":241,"detection_fps":0.0,"pid":228,"process_fps":5.4,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":116.5,"mount_type":"tmpfs","total":134.2,"used":17.7},"/media/frigate/clips":{"free":1772014.4,"mount_type":"btrfs","total":2000397.9,"used":227008.7},"/media/frigate/recordings":{"free":1772014.4,"mount_type":"btrfs","total":2000397.9,"used":227008.7},"/tmp/cache":{"free":989.0,"mount_type":"tmpfs","total":1000.0,"used":11.0}},"uptime":3678,"version":"0.9.0-aa807d2"}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, flv, from 'rtmp://IP/bcs/channel0_main.bcs?channel=0&stream=0&user=USER&password=PASS':
  Metadata:
    displayWidth    : 2560
    displayHeight   : 1440
  Duration: 00:00:00.00, start: 326315.858000, bitrate: N/A
    Stream #0:0: Data: none
    Stream #0:1: Video: h264, yuv420p(progressive), 2560x1440, 6 fps, 6.25 tbr, 1k tbn
    Stream #0:2: Audio: aac, 16000 Hz, mono, fltp
Unsupported codec with id 0 for input stream 0
```

**Screenshots**
I could prepare a video where you can see no object if that helps ;)

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Docker Compose
 - Coral Version: m.2 PCIe
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-520
 - Resolution: 2560x1440
 - FPS: 6

**Comment by ragenhe** [comment]
I've seen this on my setup when I have an object set up to detect, but no trigger/rule to record it.

Could that be the case with your setup?

**Comment by blakeblackshear** [comment]
Can you post a list of the files in the recordings directory from the time period of the event? Also, can you take a look at your log file from the time of the event?

**Comment by fbcd4f50ea5350f051450323b5abfd0b** [comment]
Of course!

**Screenshot of the event**
<img width="1094" alt="Screenshot 2021-09-30 at 14 34 23" src="https://user-images.githubusercontent.com/26644130/135455840-95a3f091-140c-4fac-809e-50a5b562d310.png">

**Recordings directory**
``` bash
[...]/frigate/recordings/2021-09/29/18/carport# ls -1 2*
20.09.mp4
20.19.mp4
20.28.mp4
20.35.mp4
20.45.mp4
20.53.mp4
25.15.mp4
25.23.mp4
25.33.mp4
26.17.mp4
26.27.mp4
26.35.mp4
26.45.mp4
```

``` bash
# date
Thu Sep 30 14:41:40 CEST 2021
# docker exec frigate date
Thu Sep 30 14:41:49 CEST 2021
```

There are no logs at that time. Should I increase the log level?

**Comment by fbcd4f50ea5350f051450323b5abfd0b** [comment]
> I've seen this on my setup when I have an object set up to detect, but no trigger/rule to record it.
> 
> Could that be the case with your setup?

Thanks for your idea. Unfortunately I can't find any error in my configuration. Often the video is also correct.

**Comment by blakeblackshear** [comment]
I was expecting to see some messages in the logs about ffmpeg restarting and/or invalid data being found in the segments. I may need to add more logging here to figure out what is happening.

**Comment by Homas** [comment]
I've just noticed the same issue on my 2 cameras but I was able to found the triggered persons.
The event timestamp matches the camera's timestamp but on the selection toolbar (sorry I don't know how it is named in english) I had to select 2 minutes before the event timestamp.
E.g. event was recorded at 17:53:33 (which matches the camera's timestamp) but I have to select 17:51:33 to see the event (or a detected person).

**Comment by blakeblackshear** [comment]
@Homas can you post your config please? Also, can you check the files in the recordings folder directly and see if the timestamps in the video are also about 2 minutes off from the filenames?

**Comment by Homas** [comment]
In the other issue you actually gave me an idea how to validate that.
```
root@beeb7444779d:/media/frigate/recordings/2021-09/30/17/backyardright520# for x in *; do echo -n "$x " ;ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $x; done
00.09.mp4 9.601000
00.19.mp4 9.617000
00.29.mp4 9.568000
00.39.mp4 9.572000
00.49.mp4 9.586000
00.59.mp4 9.606000
01.09.mp4 9.501000
01.19.mp4 9.602000
01.29.mp4 9.563000
01.39.mp4 9.586000
---cut---
09.18.mp4 11.630000
09.30.mp4 7.648000
09.38.mp4 9.659000
09.48.mp4 9.605000
09.58.mp4 9.626000
10.08.mp4 11.570000
--- cut ---
```
you see that every segment is less than 10 seconds. some recordings were more that 10 seconds.
```
root@beeb7444779d:/media/frigate/recordings/2021-09/30/17/backyardright520# for x in *; do echo -n "$x " ;ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $x; done | awk '{sum+=$2} END {print sum}'
**3468.55**
```
and in total the whole hour (3600 seconds) recordings didn't get 130 seconds. Because my example was to teh end of the hour, it was about 120 seconds. 
Last 10 minutes I've lost about 10 seconds.
```
root@beeb7444779d:/media/frigate/recordings/2021-09/30/17/backyardright520# for x in 5*; do echo -n "$x " ;ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $x; done | awk '{sum+=$2} END {print sum}'
578.276
```
here is the camera's config (reolink 520)
```
  backyardright520: 
    ffmpeg:
      inputs:
#        - path: rtsp://frigate:frigate@192.168.10.101:554/h264Preview_01_main
         - path: rtmp://192.168.10.101/bcs/channel0_main.bcs?channel=0&stream=0&user=frigateuser&password=frigatepwd
           roles:
#             - rtmp
             - record
# medium quality
         - path: rtmp://192.168.10.101/bcs/channel0_ext.bcs?channel=0&stream=0&user=frigateuser&password=frigatepwd
# low quality
#         - path: rtmp://192.168.10.101/bcs/channel0_sub.bcs?channel=0&stream=0&user=frigateuser&password=frigatepwd
           roles:
             - detect
             - rtmp
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv

    record:
      enabled: True
      retain_days: 2
      events:
        retain:
          default: 30
    snapshots:
      enabled: True
    motion:
      mask:
        - 1280,275,1280,0,1183,0,828,0
        - 754,25,819,25,818,47,443,44,443,21
    objects:
      track:
        - person
        - dog
        - cat
        - bird
```
