### ISSUE TITLE
GENAI - Enable Extra Arguments for Ollama Provider

### ISSUE THREAD

**Issue by illuzn** [blakeblackshear/frigate#18869]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to keep my ollama model loaded forever.
I want to be able to manually specify certain other options such as `num_gpu` because ollama doesn't always calculate the amount of available VRAM correctly especially with AMD iGPUs with essentially unlimited GTT memory.

**Describe the solution you'd like**
This requires the parameters to be passed here (when frigate requests that the model is loaded):
https://github.com/blakeblackshear/frigate/blob/623bc726330dad75b300277982c3b0b3052f2eba/frigate/genai/ollama.py#L27

in config.yaml:
```yaml
genai:
  enabled: true
  provider: ollama
  model: llava:7b
  extra_parameters: "{JSON parameters go here}"
```

for example:
```yaml
extra_parameters:
  keep_alive: -1
  options:
    num_gpu: 50
```

I'm aware that this yaml will need to be converted to valid JSON together with the requested model before it is sent to the ApiClient e.g.
```json
{"model": "llava:7b", "keep_alive": -1, "options": {"num_gpu": 50}}
```

**Describe alternatives you've considered**
A seperate manual curl request could be made to the ollama before starting frigate but this seems redundant.

**Additional context**
Note that these extra_parameters would also be valid in any generate request (which loads the requested model anyway). It could also be added here:
https://github.com/blakeblackshear/frigate/blob/623bc726330dad75b300277982c3b0b3052f2eba/frigate/genai/ollama.py#L47-L51
This would potentially be useful if the ollama provider is also used for other purposes to load and keep loaded the correct model.

**Comment by streaky** [comment]
Small note but the options should be part of the YAML structure and frigate should handle any necessary encoding, for example to borrow from yours:

```yaml
genai:
  enabled: true
  provider: ollama
  model: llava:7b
  extra_parameters:
    parameters: go
    here: please
    some:
      config: object
```

This would be logically better, more convenient to use within the config structure, and validatable.
