### ISSUE TITLE
Coral / detection not working in HAOSS hib_error_status

### ISSUE THREAD

**Issue by rtenklooster** [blakeblackshear/frigate#1889]
**Describe the bug**
Frigate isn't working when I use the M.2 dual edge TPU. Same config with CPU detector is working fine.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral1:
    type: edgetpu
    device: pci:0

cameras:  
    Schuifpui:
      ffmpeg:
        # hwaccel_args:
        #   - -c:v
        inputs:
          - path: rtsp://x:x@10.0.1.189:554//h264Preview_01_sub
            roles:
              - detect
              - rtmp
          - path: rtsp://x:x@10.0.1.189:554//h264Preview_01_main
            roles:
              - record
              - clips
        # global_args: -hide_banner -loglevel info
        # output_args:
        #   record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy #removed -an parameter to enable audio
        #   clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy #removed -an parameter to enable audio
      width: 640
      height: 480
      fps: 4
      objects:
        track:
          - person
          - car
      clips:
        enabled: True
        pre_capture: 5
        post_capture: 5
      rtmp:
        enabled: True
mqtt:
  host: x
  port: 1883
  topic_prefix: frigate2
  client_id: frigate2
  user: x
  password: x
  stats_interval: 5
```

**Frigate container logs**
```
W :131] Could not set performance expectation : 45 (Inappropriate ioctl for device)
frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
frigate.edgetpu                INFO    : TPU found
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
ffmpeg.Schuifpui.clips_record  ERROR   : [NULL @ 0x55ed85d0edc0] missing picture in access unit with size 24
watchdog.Schuifpui             INFO    : Terminating the existing ffmpeg process...
watchdog.Schuifpui             INFO    : Waiting for ffmpeg to exit gracefully...
frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
root                           INFO    : Waiting for detection process to exit gracefully...
frigate.video                  INFO    : Schuifpui: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Schuifpui: ffmpeg process is not running. exiting capture thread...
ffmpeg.Schuifpui.detect        ERROR   : [flv @ 0x56406d2f67c0] Failed to update header with correct duration.
ffmpeg.Schuifpui.detect        ERROR   : [flv @ 0x56406d2f67c0] Failed to update header with correct filesize.
root                           INFO    : Detection process didnt exit. Force killing...
detector.coral1                INFO    : Starting detection process: 32809
W :131] Could not set performance expectation : 45 (Inappropriate ioctl for device)
frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
frigate.edgetpu                INFO    : TPU found
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
watchdog.Schuifpui             INFO    : Terminating the existing ffmpeg process...
watchdog.Schuifpui             INFO    : Waiting for ffmpeg to exit gracefully...
frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
root                           INFO    : Waiting for detection process to exit gracefully...
watchdog.Schuifpui             INFO    : Terminating the existing ffmpeg process...
watchdog.Schuifpui             INFO    : Waiting for ffmpeg to exit gracefully...
root                           INFO    : Detection process didnt exit. Force killing...
detector.coral1                INFO    : Starting detection process: 32843
W :131] Could not set performance expectation : 45 (Inappropriate ioctl for device)
frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
frigate.edgetpu                INFO    : TPU found
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
root                           INFO    : Waiting for detection process to exit gracefully...
frigate.video                  INFO    : Schuifpui: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Schuifpui: ffmpeg process is not running. exiting capture thread...
ffmpeg.Schuifpui.detect        ERROR   : [flv @ 0x55f23adb51c0] Failed to update header with correct duration.
ffmpeg.Schuifpui.detect        ERROR   : [flv @ 0x55f23adb51c0] Failed to update header with correct filesize.
watchdog.Schuifpui             INFO    : Terminating the existing ffmpeg process...
watchdog.Schuifpui             INFO    : Waiting for ffmpeg to exit gracefully...
root                           INFO    : Detection process didnt exit. Force killing...
detector.coral1                INFO    : Starting detection process: 32876
W :131] Could not set performance expectation : 45 (Inappropriate ioctl for device)
frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
frigate.edgetpu                INFO    : TPU found
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
watchdog.Schuifpui             INFO    : Terminating the existing ffmpeg process...
watchdog.Schuifpui             INFO    : Waiting for ffmpeg to exit gracefully...
frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
root                           INFO    : Waiting for detection process to exit gracefully...
ffmpeg.Schuifpui.clips_record  ERROR   : [h264 @ 0x558f0c2afdc0] missing picture in access unit with size 5768
ffmpeg.Schuifpui.clips_record  ERROR   : [h264 @ 0x558f0c2afdc0] No start code is found.
ffmpeg.Schuifpui.clips_record  ERROR   : [h264 @ 0x558f0c2afdc0] Error splitting the input into NAL units.
ffmpeg.Schuifpui.clips_record  ERROR   : [rtsp @ 0x558f0c2ab980] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
ffmpeg.Schuifpui.clips_record  ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
ffmpeg.Schuifpui.clips_record  ERROR   : [segment @ 0x558f0c2dde00] dimensions not set
ffmpeg.Schuifpui.clips_record  ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
ffmpeg.Schuifpui.clips_record  ERROR   : 
watchdog.Schuifpui             INFO    : Terminating the existing ffmpeg process...
watchdog.Schuifpui             INFO    : Waiting for ffmpeg to exit gracefully...
frigate.video                  INFO    : Schuifpui: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Schuifpui: ffmpeg process is not running. exiting capture thread...
ffmpeg.Schuifpui.detect        ERROR   : [NULL @ 0x5637f14b2b80] missing picture in access unit with size 22
ffmpeg.Schuifpui.detect        ERROR   : [h264 @ 0x5637f15c66c0] no frame!
ffmpeg.Schuifpui.detect        ERROR   : Error while decoding stream #0:0: Invalid data found when processing input
ffmpeg.Schuifpui.detect        ERROR   : [flv @ 0x5637f14b87c0] Failed to update header with correct duration.
ffmpeg.Schuifpui.detect        ERROR   : [flv @ 0x5637f14b87c0] Failed to update header with correct filesize.
root                           INFO    : Detection process didnt exit. Force killing...
detector.coral1                INFO    : Starting detection process: 32899
W :131] Could not set performance expectation : 45 (Inappropriate ioctl for device)
frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
frigate.edgetpu                INFO    : TPU found
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
E :254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
```

**Frigate stats**
```json
{
  "Schuifpui": {
    "camera_fps": 4.0, 
    "capture_pid": 44, 
    "detection_fps": 0.1, 
    "pid": 43, 
    "process_fps": 0.1, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.1, 
  "detectors": {
    "coral1": {
      "detection_start": 1632999940.73981, 
      "inference_speed": 10.0, 
      "pid": 35456
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 3647.9, 
        "mount_type": "tmpfs", 
        "total": 3650.3, 
        "used": 2.4
      }, 
      "/media/frigate/clips": {
        "free": 24216.5, 
        "mount_type": "ext4", 
        "total": 30759.7, 
        "used": 5264.3
      }, 
      "/media/frigate/recordings": {
        "free": 24216.5, 
        "mount_type": "ext4", 
        "total": 30759.7, 
        "used": 5264.3
      }, 
      "/tmp/cache": {
        "free": 3621.2, 
        "mount_type": "tmpfs", 
        "total": 3650.3, 
        "used": 29.1
      }
    }, 
    "uptime": 59208, 
    "version": "0.8.4-5043040"
  }
}
```

**Computer Hardware**
 - OS:HAOS | core-2021.9.7 | supervisor-2021.09.6 | Home Assistant OS 6.4
 - OS core-2021.9.
 - Coral Version: PCIe m.2
 - Network Setup:Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model RLC-520A
 - Resolution: 640x480
 - FPS:4
