### ISSUE TITLE
Could not create clip from recordings for...

### ISSUE THREAD

**Issue by wonkydog** [blakeblackshear/frigate#1898]
Hi all,

Probably me at fault however attempting to use GET /api/events/<id>/clip.mp4

Returns a Could not create clip from recordings for <Camera Name>.

Checking the logs when I hit the url gives me:

[concat @ 0x5563afc800] Impossible to open 'pipe:/media/frigate/recordings/2021-10/02/13/Front Right/58.42.mp4'
pipe:: Invalid data found when processing input
[2021-10-02 14:22:16] frigate.http                   ERROR   : ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-rkmpp --enable-libdrm --enable-v4l2_m2m --enable-neon --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558becab10] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!

Now this was working perfectly in RC4? Wheres best to start looking? Device? Config change or is this a hangover from RC4?

Thanks for any help!

WD

**Comment by blakeblackshear** [comment]
Can you provide the info requested in the issue template?

**Comment by wonkydog** [comment]
**Describe the bug**
Probably me at fault however attempting to use GET FRIGATE_URL/api/events/clip.mp4 example: http://URL:5000/api/events/1633179523.983856-a3a1rr/clip.mp4

Returns a Could not create clip from recordings for (camera name).
Checking the logs when I hit the url gives me:
[concat @ 0x5563afc800] Impossible to open 'pipe:/media/frigate/recordings/2021-10/02/13/Front Right/58.42.mp4'
pipe:: Invalid data found when processing input
[2021-10-02 14:22:16] frigate.http ERROR : ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-rkmpp --enable-libdrm --enable-v4l2_m2m --enable-neon --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
libavutil 56. 51.100 / 56. 51.100
libavcodec 58. 91.100 / 58. 91.100
libavformat 58. 45.100 / 58. 45.100
libavdevice 58. 10.100 / 58. 10.100
libavfilter 7. 85.100 / 7. 85.100
libavresample 4. 0. 0 / 4. 0. 0
libswscale 5. 7.100 / 5. 7.100
libswresample 3. 7.100 / 3. 7.100
libpostproc 55. 7.100 / 55. 7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558becab10] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!


**Version of frigate**
Output from `/api/version`
0.9.0-aa807d2

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: URL
  user: user
  password: mqtt
 

cameras:
  Front Right:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://URL/Streaming/channels/102
          roles:
            - detect
            - record

    detect:
      width: 640
      height: 480
      fps: 5
      max_disappeared: 25
      enabled: True
    motion:
      mask:
        - 0,14,231,14,232,0,0,0
    zones:
      Far Left:
        coordinates: 312,260,89,407,21,217,88,201,158,210
      Far Right:
        coordinates: 606,480,619,420,408,305,187,480
      Door:
        coordinates: 357,330,300,285,80,428,104,480,170,480
    objects:
      filters:
        person:
          min_area: 600
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
        dog:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
        cat:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
        car:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
          mask: 
            - 640,0,640,0,640,94,538,141,0,98,0,0

  Front Left:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://URL/Streaming/channels/302
          roles:
            - detect
            - record

    detect:
      width: 640
      height: 480
      fps: 5
      max_disappeared: 25
      enabled: True
    motion:
      mask:
        - 0,14,231,14,232,0,0,0
        - 414,162,451,162,453,80,413,82
        - 572,59,521,51,510,0,576,0
    zones:
      Far Right:
        coordinates: 553,421,598,264,389,196,298,297
      Far Left:
        coordinates: 383,480,245,386,197,480
      Door:
        coordinates: 420,480,537,480,545,440,322,329,280,384
    objects:
      filters:
        person:
          min_area: 600
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
        car:
          mask: 
            - 640,243,640,32,569,0,415,75,376,140
            - 579,0,578,72,151,154,0,107,0,0
        dog:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
        cat:
          min_area: 100
          min_score: 0.4
          threshold: 0.55


  Garden Decking:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://URL/Streaming/channels/202
          roles:
            - detect
            - record

    detect:
      width: 640
      height: 480
      fps: 5
      max_disappeared: 25
      enabled: True
    zones:
      Back Garden:
        coordinates: 468,480,513,345,531,141,312,145,251,147,171,155,60,160,68,360,96,480
    motion:
      mask:
        - 0,14,231,14,232,0,0,0
        - 640,480,462,480,542,217,640,132
        - 80,213,87,480,0,480,0,193,68,169
    objects:
      filters:
        person:
          min_area: 2000
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
          mask: 
            - 0,480,86,480,75,188,0,156
            - 485,480,640,480,640,128,546,136

  Front Side:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://URL/Streaming/channels/402
          roles:
            - detect
            - record

    detect:
      width: 640
      height: 480
      fps: 5
      max_disappeared: 25
      enabled: True
    zones:
      Side Zone:
        coordinates: 524,480,271,304,150,112,91,116,136,320,187,480
    motion:
      mask:
        - 0,14,231,14,232,0,0,0
        - 131,326,243,326,293,257,286,99,247,85,149,25,86,140
    objects:
      filters:
        person:
          min_area: 1100
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
        car:
          mask: 640,0,640,93,555,49,550,0
        dog:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
        cat:
          min_area: 100
          min_score: 0.4
          threshold: 0.55

  Back Side:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://URL/Streaming/channels/802
          roles:
            - detect
            - record

    detect:
      width: 480
      height: 640
      fps: 5
      max_disappeared: 25
      enabled: True
    zones:
      Side Zone:
        coordinates: 147,177,234,107,337,62,436,265,480,640,286,640,243,422
    motion:
      mask:
        - 0,0,206,0,196,13,3,17
        - 410,249,395,155,361,96,310,56,220,39,119,120,128,164,171,257
        - 480,640,480,588,293,595,286,640
    objects:
      filters:
        person:
          min_area: 2000
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
        car:
          mask: 373,0,344,21,0,99,0,0

  Garage Right:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://URL/Streaming/channels/1002
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
      max_disappeared: 25
      enabled: True
    zones:
      Drive:
        coordinates: 67,480,640,480,640,327,334,227,31,346
    motion:
      mask:
        - 0,14,231,14,232,0,0,0
        - 198,90,210,0,0,0,0,159
    objects:
      filters:
        person:
          min_area: 2000
          max_area: 100000
          min_score: 0.4
          threshold: 0.65
          mask: 360,60,384,95,284,113,221,82,284,69
        dog:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
        cat:
          min_area: 100
          min_score: 0.4
          threshold: 0.55
        car:
          mask: 0,435,280,429,436,305,427,135,156,96,0,111


detectors:
  coral:
    type: edgetpu
    device: usb

motion:
  threshold: 10
  contour_area: 50

objects:
  track:
    - person
    - car
    - cat
    - dog
    - bicycle
    - motorcycle
    - bus


  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 640
  # Optional: Height of the output resolution (default: shown below)
  height: 480
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
 
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: True
  
 
record:
  # Optional: Enable recording (default: shown below)
  enabled: True
  # Optional: Number of days to retain (default: shown below)
  retain_days: 0
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the cache
    #       will begin to expire and the resulting clip will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 600
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 2
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 2
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Retention settings for events
    retain:
      # Required: Default retention days (default: shown below)
      default: 1

snapshots:
  retain:
    # Required: Default retention days (default: shown below)
    default: 1
```

**Frigate container logs**
```
[2021-10-02 15:18:22] frigate.http                   ERROR   : ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-rkmpp --enable-libdrm --enable-v4l2_m2m --enable-neon --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558e7eeb10] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558e7eeb10] moov atom not found
[concat @ 0x558e7ed800] Impossible to open 'pipe:/media/frigate/recordings/2021-10/02/13/Front Right/58.42.mp4'
pipe:: Invalid data found when processing input
[2021-10-02 15:21:06] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:42238]
```

**Frigate stats**
```json
{"Back Side":{"camera_fps":5.0,"capture_pid":249,"detection_fps":0.0,"pid":230,"process_fps":5.0,"skipped_fps":0.0},"Front Left":{"camera_fps":5.1,"capture_pid":237,"detection_fps":3.4,"pid":223,"process_fps":5.1,"skipped_fps":0.0},"Front Right":{"camera_fps":5.1,"capture_pid":233,"detection_fps":0.0,"pid":221,"process_fps":5.1,"skipped_fps":0.0},"Front Side":{"camera_fps":5.0,"capture_pid":244,"detection_fps":0.0,"pid":227,"process_fps":5.0,"skipped_fps":0.0},"Garage Right":{"camera_fps":5.1,"capture_pid":255,"detection_fps":0.0,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"Garden Decking":{"camera_fps":5.1,"capture_pid":240,"detection_fps":0.0,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":3.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":21.8,"pid":218}},"service":{"storage":{"/dev/shm":{"free":4090.8,"mount_type":"tmpfs","total":4095.7,"used":4.9},"/media/frigate/clips":{"free":13967.8,"mount_type":"ext4","total":30659.8,"used":15417.1},"/media/frigate/recordings":{"free":13967.8,"mount_type":"ext4","total":30659.8,"used":15417.1},"/tmp/cache":{"free":4092.8,"mount_type":"tmpfs","total":4095.7,"used":2.8}},"uptime":416,"version":"0.9.0-aa807d2"}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
streams seem to be working fine and I seem to be struggling to run this command! Please let me know if its vital.
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Computer Hardware**
 - OS: [e.g. Pi4 8GB ]
 - Install method: [e.g. Addon]
 - Coral Version: [e.g. USB]
 - Network Setup: [e.g. Wired]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
Above should explain all, but can help you out with any other details you need. Thanks!

WD
