### ISSUE TITLE
MQTT events not published

### ISSUE THREAD

**Issue by v0l** [blakeblackshear/frigate#1899]
**Describe the bug**

Detection events are not published to MQTT
Specifically:
 - `frigate/<camera_name>/<object_name>`
 - `frigate/events`
 - 
**Version of frigate**
`0.8.0-2ec9215`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
{
  "cameras": {
    "front": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "retain": {
          "default": 14,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 10
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:1234567a@10.100.1.37/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec copy /tmp/cache/front-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/front",
          "roles": [
            "clips",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:1234567a@10.100.1.37/cam/realmonitor?channel=1&subtype=2 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "fps": null,
      "frame_shape": [
        1080,
        1920
      ],
      "height": 1080,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": [
          "288,156,339,91,807,57,889,102,1535,121,1920,830,1920,0,0,0,0,685"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 500,
        "timestamp": false
      },
      "name": "front",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 1920,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral1": {
      "device": "pci",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "mosquitto",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": null
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**Frigate container logs**
```
* Starting nginx nginx
...done.
frigate.app INFO : Creating directory: /tmp/cache
Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.coral1 INFO : Starting detection process: 45
frigate.edgetpu INFO : Attempting to load TPU as pci
frigate.app INFO : Camera processor started for front: 48
frigate.app INFO : Capture process started for front: 49
frigate.edgetpu INFO : TPU found
```

**Frigate stats**
```json
{"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.22,"pid":45}},"front":{"camera_fps":5.1,"capture_pid":49,"detection_fps":0.0,"pid":48,"process_fps":5.1,"skipped_fps":0.0},"service":{"uptime":625239,"version":"0.8.0-2ec9215"}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
Input #0, rtsp, from 'rtsp://admin:1234567a@10.100.1.37/live':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.040000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 3072x2048 [SAR 1:1 DAR 3:2], 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: aac (LC), 64000 Hz, mono, fltp
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1172179/135731161-81944b7f-8c88-435d-a4c1-2ee61542b263.png)

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Kubernetes
 - Virtualization: Kubernetes on Ubuntu on Proxmox
 - Coral Version: PCIe
 - Network Setup: 10G

**Camera Info:**
 - Manufacturer: Dahua
 - Model: IPC-HDW4631C-A
 - Resolution: 3072x2048
 - FPS: 25
