### ISSUE TITLE
Stream log errors

### ISSUE THREAD

**Issue by PskNorz** [blakeblackshear/frigate#1902]
**Describe the bug**

When I first set up Frigate I had Reolink's main stream assigned to clips and its substream asssigned for detections. Although the clips were always laggy and jumpting seconds. When I removed the main stream and had clips made using the substream too, they were a lot better, however I was noticing on Frigate that when there is a lot of motion the camera view fills up with quite a lot of motion boxes (but also blue boxes) and then that leads to Frigate crashing and spitting out a lot of errors.

On top of that shouldn't a Pi4 be able to handle just one camera? Even with clips being made with sub stream? Although preferably would want the main stream for the clips

```
Logger: libav.NULL
Source: components/stream/worker.py:223
First occurred: 11:46:11 AM (2 occurrences)
Last logged: 11:46:11 AM

non-existing SPS 1 referenced in buffering period
SEI type 40 size 1856 truncated at 1672
```
```
This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:172
Integration: Frigate (documentation, issues)
First occurred: 10:41:43 AM (2 occurrences)
Last logged: 10:41:54 AM

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Try again]
```
```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:396
Integration: Stream (documentation, issues)
First occurred: 10:57:47 (1 occurrences)
Last logged: 10:51:47

Error demuxing stream: [Errno 1414092869] Immediate exit request: 'rtmp://ccab4aaf-frigate/live/doggie_cam'
```

**Version of frigate**
1.14

**Config file**

```yaml
mqtt:
  host: HA
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: HA
  password: HA

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

cameras:
  doggie_cam:
    ffmpeg:
      inputs:
        - path: rtmp://*********ip****/bcs/channel0_sub.bcs?channel=0&stream=0&user=******&password=******
          roles:
            - detect
            - clips
            - rtmp
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
    width: 640
    height: 480
    fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.7
          min_area: 5000
          max_area: 100000
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 1
    clips:
      enabled: True
      retain:
        default: 1
      pre_capture: 3
    motion:
      mask:
      - 422,35,421,0,207,0,209,37
      - 452,480,640,480,640,366,640,245,577,253,555,298,538,332,506,399,479,436

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

**Frigate container logs**
```
lost in power failure
```

**Frigate stats**
```json
{
  "detection_fps": 0.5, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 126.94, 
      "pid": 37
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 127.1, 
      "pid": 38
    }
  }, 
  "doggie_cam": {
    "camera_fps": 5.0, 
    "capture_pid": 43, 
    "detection_fps": 0.5, 
    "pid": 41, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1987.5, 
        "mount_type": "tmpfs", 
        "total": 1988.6, 
        "used": 1.1
      }, 
      "/media/frigate/clips": {
        "free": 100695.4, 
        "mount_type": "ext4", 
        "total": 117397.1, 
        "used": 11902.2
      }, 
      "/media/frigate/recordings": {
        "free": 100695.4, 
        "mount_type": "ext4", 
        "total": 117397.1, 
        "used": 11902.2
      }, 
      "/tmp/cache": {
        "free": 1986.5, 
        "mount_type": "tmpfs", 
        "total": 1988.6, 
        "used": 2.1
      }
    }, 
    "uptime": 28353, 
    "version": "0.8.4-5043040"
  }
}
```

**FFprobe from your camera**
```
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20210424) 20210424
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-liba                                                                                                                                                                                                              ss --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --                                                                                                                                                                                                              enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-s                                                                                                                                                                                                              hared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static                                                                                                                                                                                                               --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libsoxr --enable-libw                                                                                                                                                                                                              ebp --enable-libaom --disable-debug
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100

  Metadata:
  title : Session streamed by "preview"
  comment : h264Preview_01_sub
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 15 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

**Screenshots**

![error4](https://user-images.githubusercontent.com/80605468/135761130-679d6f58-f1b5-4729-a9da-2b1849e2ef74.png)
![error6](https://user-images.githubusercontent.com/80605468/135761140-6598052f-6b10-4eeb-9356-e5ed983c903e.png)
![u1nknown](https://user-images.githubusercontent.com/80605468/135761145-dfc27777-4982-4def-8c3b-1c13606db147.png)
![i1mage](https://user-images.githubusercontent.com/80605468/135761146-c08cea0e-7369-4987-ae05-dbec593a5907.png)
![im2age0](https://user-images.githubusercontent.com/80605468/135761153-0208a744-ab6f-4266-a212-1712724ed59b.png)
![Inkedunkndown_LI](https://user-images.githubusercontent.com/80605468/135761249-1286997d-25b1-4b82-b7dc-e0a6cd44b58c.jpg)

**Computer Hardware**
 - OS: HAOS 6.4
 - Install method: Addon
 - RPI 4 - 64


**Camera Info:**
 - Manufacturer: [Reolink]
 - Model: [E1 Zoom wifi]
