### ISSUE TITLE
[Support]: Help getting CPU usage down

### ISSUE THREAD

**Issue by amit-nz** [blakeblackshear/frigate#1904]
### Describe the problem you are having

I am running frigate in a docker that is running in a VM that is running on proxmox (I know). I have the onboard intel GPU from the i5-8250U CPU passed through to the VM via Intel GVT-g, and that is then passed through (/dev/dri/renderD128) in the docker compose.

It is visible from within the VM:

`$ lspci | grep UHD
00:10.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)`

**I have a google coral TPU (usb), however I am not using it because it stops working periodically.** I believe I am hitting this - https://github.com/blakeblackshear/frigate/issues/148 For now I am OK using just CPU detectors.

My goal is to offload as much decoding/encoding to the iGPU as possible to get the CPU usage down as low as possible.

With 8 cameras (5 of which are doing object detection), I am seeing around 40-50% cpu usage but I want to see if I can get this down lower by using hw acceleration to do the decoding/encoding. 

Could someone please take a look at my config below and see if it looks good, and if anything can be changed to offload more workloads to the hardware?

### Version

0.8.4-5043040

### Frigate config file

```yaml
mqtt:
  host: hass.mydomain.com
  port: 1883
  topic_prefix: frigate
  user: frigate_mqtt
  password: frigate_mqtt_pw
  stats_interval: 60

database:
  path: /config/frigate.db

ffmpeg:
  hwaccel_args: 
    - '-hwaccel' 
    - vaapi 
    - '-hwaccel_device' 
    - /dev/dri/renderD128 
    - '-hwaccel_output_format' 
    - yuv420p 
  output_args:
      record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      
cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@172.16.2.240:554/s0 # 1920x1080, 30 fps stream for saving clips
          roles:
            - clips
            - record
        - path: rtsp://username:password@172.16.2.240:554/s1 # 640x360, 10 fps stream for motion detect
          roles:
            - detect
    width: 640
    height: 360
    fps: 5
    motion:
      mask:    
        - 0,0,412,0,640,0,640,137,495,132,352,117,346,22,148,37,140,160,0,107
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    record:
      enabled: true
      retain_days: 7
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - dog
        - cat
        - motorcycle
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        #objects:
        #  person: 14
        #  dog: 14
        #  cat: 14
        #  motorycle: 14
        #  car: 14
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
          motorycle: 14
          car: 14
    objects:
      track:
        - person
        - dog
        - cat
        - motorcycle
        - car

  camera_2:
    ffmpeg:   
      inputs:
        - path: rtsp://username:password@172.16.2.239:554/s0 # 1920x1080, 30 fps stream for saving clips
          roles:
          - clips
          - record
        - path: rtsp://username:password@172.16.2.239:554/s1 # 640x360, 10 fps stream for motion detect
          roles:
          - detect
    width: 640
    height: 360
    fps: 5
    motion:
      mask:    
        - 0,286,139,196,132,86,127,0,0,0
        - 375,161,640,156,640,0,380,0
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    record:
      enabled: true
      retain_days: 7
    clips:
      # Required: enables clips for the camera
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - dog
        - cat
        - car
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          car: 14
          cat: 14
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
          car: 14
    objects:
      track:
        - person
        - cat
        - dog
        - car

  camera_3:
    ffmpeg:    
      inputs:
        - path: rtsp://username:password@172.16.2.238:554/s0
          roles:
            - detect
    width: 1920
    height: 1080
    fps: 30
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: false
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
        # Optional: Per object retention days
        objects:
          person: 1
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: false
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
        # Optional: Per object retention days
        objects:
          person: 1
    detect:
      enabled: false
    objects:
      track:
        - person

  camera_4:
    ffmpeg:
      inputs:
        - path: rtsp://username:passw0rd@172.16.2.238:554/h264Preview_01_main
          roles:
            - detect
    width: 2560
    height: 1440
    fps: 20
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: false
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: false
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
        # Optional: Per object retention days
    detect:
      enabled: false

  camera_5:
    ffmpeg:
      inputs:
        - path: rtsp://username:passw0rd@172.16.2.239:554/h264Preview_01_main
          roles:
            - detect
    width: 2560
    height: 1440
    fps: 20
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: false
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: false
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
        # Optional: Per object retention days
    detect:
      enabled: false

  camera_6:
    ffmpeg:
      inputs:
        - path: rtsp://username:passw0rd@172.16.1.241:554/s0 # 1920x1080, 30 fps stream for saving clips
          roles:
          - clips
          - record
        - path: rtsp://username:passw0rd@172.16.1.241:554/s1 # 640x360, 10 fps stream for motion detect
          roles:
          - detect          
    width: 640
    height: 360
    fps: 5
    motion:
      mask:
        - 175,0,187,0,0,0,0,360,79,360,145,360
        - 500,0,640,0,640,360,537,360
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    record:
      enabled: true
      retain_days: 7
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - dog
        - cat
        - cow
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
          cow: 14
    objects:
      track:
        - person
        - cat
        - dog
        - cow

  camera_7:
    ffmpeg:
      inputs:
        - path: rtsp://username:passw0rd@172.16.1.240:554/s0 # 1920x1080, 30 fps stream for saving clips
          roles:
          - clips
          - record
        - path: rtsp://username:passw0rd@172.16.1.240:554/s1 # 640x360, 10 fps stream for motion detect
          roles:
          - detect           
    width: 640
    height: 360
    fps: 5
    motion:
      mask:    
        - 557,139,640,169,640,0,0,0,0,57,0,154
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    record:
      enabled: true
      retain_days: 7
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - dog
        - cat
        - car
        - cow
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          car: 14
          cat: 14
          cow: 14
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
          car: 14
          cow: 14
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - cow
  
  camera_8:
    ffmpeg:
      inputs:
        - path: rtsp://username:passw0rd@172.16.1.242:554/s0 # 1920x1080, 30 fps stream for saving clips
          roles:
          - clips
        - path: rtsp://username:passw0rd@172.16.1.242:554/s2 # 640x360, 10 fps stream for motion detect
          roles:
          - detect           
    width: 640
    height: 360
    fps: 5
    motion:
      mask:    
        - 0,124,344,119,359,69,384,0,0,0
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: false
    record:
      enabled: false
      retain_days: 7
    clips:
      # Required: enables clips for the camera (default: shown below)
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: 5)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: 5)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - person
        - cat
        - dog
        - car
        - cow
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
          cow: 14
          car: 14
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 14
        # Optional: Per object retention days
        objects:
          person: 14
          dog: 14
          cat: 14
          cow: 14
          car: 14
    objects:
      track:
        - person
        - cat
        - dog
        - cow
        - car
          
#CPU detectors
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://user:passw0rd@172.16.2.240:554/s0':
  Metadata:
    title           : s0
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac, 48000 Hz, mono, fltp
    Stream #0:1: Video: h264, yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 24 fps, 30 tbr, 90k tbn, 48 tbc
```

### Frigate stats

```json
{
  "Camera_1": {
    "camera_fps": 5.0, 
    "capture_pid": 56, 
    "detection_fps": 0.0, 
    "pid": 42, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "Camera_2": {
    "camera_fps": 5.0, 
    "capture_pid": 57, 
    "detection_fps": 0.0, 
    "pid": 43, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "Camera_3": {
    "camera_fps": 30.1, 
    "capture_pid": 61, 
    "detection_fps": 0.0, 
    "pid": 44, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "Camera_4": {
    "camera_fps": 19.0, 
    "capture_pid": 70, 
    "detection_fps": 0.0, 
    "pid": 46, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "Camera_5": {
    "camera_fps": 4.8, 
    "capture_pid": 82, 
    "detection_fps": 0.0, 
    "pid": 55, 
    "process_fps": 4.8, 
    "skipped_fps": 0.0
  }, 
  "Camera_6": {
    "camera_fps": 5.0, 
    "capture_pid": 75, 
    "detection_fps": 0.0, 
    "pid": 54, 
    "process_fps": 5.0, 
    "skipped_fps": 0.0
  }, 
  "Camera_7": {
    "camera_fps": 5.1, 
    "capture_pid": 72, 
    "detection_fps": 0.0, 
    "pid": 50, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "Camera_8": {
    "camera_fps": 20.4, 
    "capture_pid": 65, 
    "detection_fps": 0.0, 
    "pid": 45, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 97.27, 
      "pid": 33
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 74.8, 
      "pid": 35
    }, 
    "cpu3": {
      "detection_start": 0.0, 
      "inference_speed": 92.26, 
      "pid": 37
    }, 
    "cpu4": {
      "detection_start": 0.0, 
      "inference_speed": 76.77, 
      "pid": 38
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 251.1, 
        "mount_type": "tmpfs", 
        "total": 268.4, 
        "used": 17.4
      }, 
      "/media/frigate/clips": {
        "free": 6071412.4, 
        "mount_type": "cifs", 
        "total": 23030281.3, 
        "used": 16958868.9
      }, 
      "/media/frigate/recordings": {
        "free": 6071412.4, 
        "mount_type": "cifs", 
        "total": 23030281.3, 
        "used": 16958868.9
      }, 
      "/tmp/cache": {
        "free": 936.2, 
        "mount_type": "tmpfs", 
        "total": 1000.0, 
        "used": 63.8
      }
    }, 
    "uptime": 1582, 
    "version": "0.8.4-5043040"
  }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Mix of UBNT and Reolink Bullet/Domes; All x264

### Any other information that may be helpful

Upon recommendations on reddit, I added masks to 5 of the 8 cameras to mask off the entire frame (so effectively, no detection to take place at all) however I found that CPU usage actually took a ~10 percent jump upwards. Removed the masks - CPU returned back to what it was before. Not sure what to make of this.
