### ISSUE TITLE
[Support]: offline camera

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#1932]
### Describe the problem you are having

One of my cameras was offline (power was disconnected) and Frigate would still show an image if I click on cameras then click on that camera.
Shouldn't it show a black/blank image or an image saying camera is not available ? or even better trigger and alert ?

### Version

0.8.4-5043040

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: xxx.xxx.xxx.xx
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  driveway:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 230,73,640,219,640,0,0,0,0,21
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.6.xxx/2
          roles:
            - detect
        - path: rtsp://admin:xxxx@192.168.6.xxx/1
          roles:
            - clips            
    width: 640
    height: 352
    fps: 5  
    motion:
      mask:
        - 230,73,640,219,640,0,0,0,0,21      

    clips:
      enabled: true
      retain:
        default: 4
    snapshots:
      enabled: False
      bounding_box: True
      retain:
        default: 0
################################################        
  front_porch_camera:
    objects:
      track:
        - person


    ffmpeg:
      inputs:
        - path: http://admin:xxxx@192.168.6.xxx/video.cgi 
          roles:
            - detect
            - clips
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - "1"
      output_args:
           clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -pix_fmt yuv420p -an 
    width: 640
    height: 480
    fps: 5  
    clips:
      enabled: true
      retain:
        default: 7
```

### Relevant log output

```shell
ffmpeg.front_porch_camera.detect ERROR   : http://admin:xxxx@192.168.6.19/video.cgi: No route to host
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front_porch_camera: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

D-Link DCS-930L Wireless N Network Camera
