### ISSUE TITLE
[Support]: validation errors for FrigateConfig

### ISSUE THREAD

**Issue by harihoudini** [blakeblackshear/frigate#1933]
### Describe the problem you are having

update broke Frigate without any change to s working config file. Will not start giving error in the log output

### Version

latest

### Frigate config file

```yaml
mqtt:
  host: 192.168.200.149
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # user: mqtt-user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  # password: mqtt-user
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.50:554/s1
          roles:
            - detect
        - path: rtsp://192.168.200.50:554/s0
          roles:
            - record
            - clips
            - rtmp
      output_args:     
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy      
    width: 640
    height: 360
    fps: 5
    motion:
      mask: 320,106,640,209,640,0,191,0,0,0,0,65
      threshold: 10
      contour_area: 50
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    record:
      enabled: true
      retain_days: 15
    snapshots:
      enabled: true
    mqtt:
      enabled: true
      crop: false
    objects:
      track:    
       - person
       - dog
      filters:
       dog:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.6
       person:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.7
  Deck:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.51:554/s1
          roles:
            - detect
        - path: rtsp://192.168.200.51:554/s0
          roles:
            - record
            - clips
            - rtmp
      output_args:     
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 640
    height: 360
    fps: 5
    motion:
      mask: 368,51,640,205,640,0,0,0,0,62
      threshold: 10
      contour_area: 50
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    record:
      enabled: true
      retain_days: 15
    snapshots:
      enabled: true
    mqtt:
      enabled: true
      crop: false
    objects:
      track:    
       - person
       - dog
      filters:
       dog:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.6
       person:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.7
  Side:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.52:554/s1
          roles:
            - detect
        - path: rtsp://192.168.200.52:554/s0
          roles:
            - record
            - clips
            - rtmp
      output_args:     
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy      
    width: 640
    height: 360
    fps: 5
    motion:
      mask: 399,40,640,0,378,0,257,0,0,0,0,117
      threshold: 10
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    record:
      enabled: true
      retain_days: 15
    snapshots:
      enabled: true
    mqtt:
      enabled: true
      crop: false
    objects:
      track:    
       - person
       - dog
       - car
       - bus
      filters:
       dog:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.6
       person:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.7
  Frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.53:554/s1
          roles:
            - detect
        - path: rtsp://192.168.200.53:554/s0
          roles:
            - clips
            - rtmp
            - record
      output_args:     
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy      
    width: 640
    height: 360
    fps: 5
    motion:
      threshold: 10
      contour_area: 50
    zones:
      yard:
        coordinates: 0,360,640,360,640,70,316,76,0,71
      road:
        coordinates: 0,60,334,68,640,67,640,0,0,0
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    record:
      enabled: true
      retain_days: 15
    snapshots:
      enabled: true
    mqtt:
      enabled: true
      crop: false
    objects:
      track:    
       - person
       - dog
       - bicycle
      filters:
       dog:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.6
       person:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.7
       bus:
        mask:
         - 640,65,640,0,0,0,0,53
       car:
        mask:
         - 640,85,640,0,0,0,0,73
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.200.54:554/s1
          roles:
            - detect
        - path: rtsp://192.168.200.54:554/s0
          roles:
            - record
            - clips
            - rtmp
      output_args:     
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 640
    height: 360
    fps: 5
    motion:
      mask: 
        - 640,159,640,0,0,0,0,149
        - 640,0,640,0,640,95,640,278,288,149,294,0
      threshold: 10
      contour_area: 50
    zones:
      drive:
        coordinates: 640,267,470,209,275,162,108,157,0,156,0,360,387,360,640,360
      road:
        coordinates: 0,145,375,153,389,73,0,72
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
    record:
      enabled: true
      retain_days: 15
    snapshots:
      enabled: true
    mqtt:
      enabled: true
      crop: false
    objects:
      track:
       - person
       - dog
       - car
       - bus
      filters:
       dog:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.6
       person:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.7
       car:
        mask:
         - 0,0,404,0,384,155,0,150
detectors:
  cpu1:
   type: cpu
  cpu2:
   type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-06 11:49:17] frigate.app INFO : Starting Frigate (0.9.1-800f33e)
Error parsing config: 25 validation errors for FrigateConfig

cameras -> backyard -> ffmpeg -> inputs -> 1 -> roles -> 1
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> backyard -> clips
extra fields not permitted (type=value_error.extra)
cameras -> backyard -> fps
extra fields not permitted (type=value_error.extra)
cameras -> backyard -> height
extra fields not permitted (type=value_error.extra)
cameras -> backyard -> width
extra fields not permitted (type=value_error.extra)
cameras -> Deck -> ffmpeg -> inputs -> 1 -> roles -> 1
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Deck -> clips
extra fields not permitted (type=value_error.extra)
cameras -> Deck -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Deck -> height
extra fields not permitted (type=value_error.extra)
cameras -> Deck -> width
extra fields not permitted (type=value_error.extra)
cameras -> Side -> ffmpeg -> inputs -> 1 -> roles -> 1
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Side -> clips
extra fields not permitted (type=value_error.extra)
cameras -> Side -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Side -> height
extra fields not permitted (type=value_error.extra)
cameras -> Side -> width
extra fields not permitted (type=value_error.extra)
cameras -> Frontyard -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Frontyard -> clips
extra fields not permitted (type=value_error.extra)
cameras -> Frontyard -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Frontyard -> height
extra fields not permitted (type=value_error.extra)
cameras -> Frontyard -> width
extra fields not permitted (type=value_error.extra)
cameras -> Driveway -> ffmpeg -> inputs -> 1 -> roles -> 1
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Driveway -> clips
extra fields not permitted (type=value_error.extra)
cameras -> Driveway -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Driveway -> height
extra fields not permitted (type=value_error.extra)
cameras -> Driveway -> width
extra fields not permitted (type=value_error.extra)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Unifi G3
