### ISSUE TITLE
[Support]: Frigate install now it wont start after install ?

### ISSUE THREAD

**Issue by andiewill** [blakeblackshear/frigate#1934]
### Describe the problem you are having

Hi All i updated my Unraid Frigate install now it wont start ? i read about you have to remove "enabled" line under "events" but i do not have that feature in my config, anyone no what my issue may be ?

### Version

blakeblackshear/frigate:stable-amd64

### Frigate config file

```yaml
##frigate sample config.yml:

mqtt:
  host: 192.168.1.XX
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
 
detectors:
  coral:
    type: edgetpu
    device: usb
#  coral_pci:
#    type: edgetpu
#    device: pci
    


 
cameras:


  front_yard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://Bristol:Filton@192.168.1.157/live
          roles:
            - clips
            - detect
            # - rtmp
            # - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
#    width: 1920
#    height: 1080
    fps: 5
    motion:
      mask:
        - 753,695,846,552,889,661,1124,651,1127,596,1535,570,1920,822,1892,278,0,273,0,701
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        # - car
        - cat
        - dog
        - bird
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      # crop: True
      # height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        # - car
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-06 18:16:50] frigate.app INFO : Starting Frigate (0.9.1-800f33e)
Error parsing config: 3 validation errors for FrigateConfig

cameras -> front_yard_cam -> ffmpeg -> inputs -> 0 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> front_yard_cam -> clips
extra fields not permitted (type=value_error.extra)
cameras -> front_yard_cam -> fps
extra fields not permitted (type=value_error.extra)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
?
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Wyze cam v3
