### ISSUE TITLE
[Support]: Set up differene source for 24/7 recording vs events

### ISSUE THREAD

**Issue by jtronicus** [blakeblackshear/frigate#1935]
### Describe the problem you are having

I am in the process of completely redoing my config file to accommodate the new changes in 0.9.1.

On older versions of Frigate I was able to use multiple streams on the same camera, with 24/7 recording on the low-quality stream, and clips being saved from the high-quality stream.  Now that clips have been merged with recordings, I am not sure how to do this. Is this possible with the latest version, or do I need to set up 2 cameras?

This is how it was set up in my old config:
```
cameras:
  deck:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.xxx.xxx:554/Streaming/Channels/1
          roles:
            - clips
            - detect
        - path: rtsp://user:pass@192.168.xxx.xxx:554/Streaming/Channels/2
          roles:
            - record
    width: 1920
    height: 1080
    fps: 6
```

### Version

0.9.1-800f33e

### Frigate config file

```yaml
mqtt:
  host: 192.168.xxx.xxx
  port: xxx
  topic_prefix: xxx
  client_id: xxx
  stats_interval: 60
  
detectors:
  coral_pci:
    type: edgetpu
    device: pci

detect:
  enabled: False
snapshots:
  enabled: False
record:
  enabled: False
rtmp:
  enabled: False

cameras:
  deck:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.xxx.xxx:554/Streaming/Channels/1
          roles:
            - record
        - path: rtsp://xxx:xxx@192.168.xxx.xxx:554/Streaming/Channels/2
          roles:
            - detect
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: 
        - -avoid_negative_ts 
        - make_zero 
        - -fflags 
        - +genpts+discardcorrupt 
        - -rtsp_transport 
        - tcp 
        - -stimeout 
        - '5000000 '
        - -use_wallclock_as_timestamps 
        - '1'
      #Comment next 2 lines to disable hardware decode
      #  - -c:v
      #  - h264_cuvid
      # Optional: global output args
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    best_image_timeout: 60
    motion:
      mask:
        - 277,48,456,22,609,35,640,44,640,0,0,0,0,157
    zones:  
      on_deck:
        coordinates: 640,360,640,81,380,75,0,320,0,360
        objects:
          - person
    # Optional: Camera level detect settings
    detect:
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 640
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 360
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      fps: 6
      max_disappeared: 25
    # Optional: save clips configuration
    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: True
      # Optional: Number of days to retain (default: global setting)
      retain_days: 7
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 60
          # Optional: Per object retention days
          objects:
            person: 60
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      #height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 90
    live:
      height: 720
      # Optional: Set the encode quality of the live stream (default: shown below)
      #1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 10
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          #max_area: 100000
          max_area: 24000000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7  
####################################################
  deck247:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.xxx.xxx:554/Streaming/Channels/2
          roles:
            - record
            - detect
      global_args: -hide_banner -loglevel warning
      hwaccel_args: []
      input_args: 
        - -avoid_negative_ts 
        - make_zero 
        - -fflags 
        - +genpts+discardcorrupt 
        - -rtsp_transport 
        - tcp 
        - -stimeout 
        - '5000000 '
        - -use_wallclock_as_timestamps 
        - '1'
      #Comment next 2 lines to disable hardware decode
      #  - -c:v
      #  - h264_cuvid
      # Optional: global output args
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: save clips configuration
    # Optional: 24/7 recording configuration
    best_image_timeout: 60
    # Optional: Camera level detect settings
    record:
      # Optional: Enable recording (default: global setting)
      enabled: True
      # Optional: Number of days to retain (default: global setting)
      retain_days: 90
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
deck	
camera_fps	6
capture_pid	235
detection_fps	0
pid	229
process_fps	6
skipped_fps	0
deck247	
camera_fps	5
capture_pid	248
detection_fps	0
pid	232
process_fps	0
skipped_fps	0
detection_fps	0
detectors	
coral_pci	
detection_start	0
inference_speed	18.5
pid	222
service	
storage	
/dev/shm	
free	1071.3
mount_type	"tmpfs"
total	1073.7
used	2.4
/media/frigate/clips	
free	1677551.5
mount_type	"ext4"
total	1967925.7
used	190337.6
/media/frigate/recordings	
free	1677551.5
mount_type	"ext4"
total	1967925.7
used	190337.6
/tmp/cache	
free	975.1
mount_type	"tmpfs"
total	1000
used	24.9
uptime	1132
version	"0.9.1-800f33e"
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

hikvision
