### ISSUE TITLE
[Support]: No clue on implementing Custom Models

### ISSUE THREAD

**Issue by karsie1994** [blakeblackshear/frigate#1937]
### Describe the problem you are having

Hi,

So I'm trying to import/use my custom tensorflow lite model, but I can't figure out how. Can anyone care to explain where to upload the model when running HA of a Pi and what edits to make to the configuration to be able to use it? The documentation only says it's possible not what steps to take.

Thanks :)

### Version

0.8.4-5043040

### Frigate config file

```yaml
mqtt:
  host: 172.30.32.1
  port: 1883
  topic_prefix: frigate_n
  client_id: frigate_n
  user: mqtt
  password: -
  stats_interval: 60
detectors:
  coral:
    type: cpu  
  coral:
    type: cpu      
cameras:
  voordeur:
    motion:
      mask: 1920,767,1920,0,1826,0,225,0
    ffmpeg:
      inputs:
        - path: rtsp://-/ch0_0.h264
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1088
    fps: 1
    snapshots:
        enabled: True
        bounding_box: False
        crop: False
        retain:
            default: 10
objects:
  filters:
    person:
      mask: 1920,0,1920,754,283,0
    karsten
      mask: 1920,0,1920,754,283,0    
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.6
model:
  height: 320
  width: 320
```

### Relevant log output

```shell
=
```

### FFprobe output from your camera

```shell
=
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Yi Cam
