### ISSUE TITLE
[Support]: Home Assistant 2010.10.x Update, Frigate Broken

### ISSUE THREAD

**Issue by Normanras** [blakeblackshear/frigate#1960]
### Describe the problem you are having

After updating my Home Assistant to 2010.10 (both .0 and .1), Frigate has stopped working. Someone else [commented in HA Communities](https://community.home-assistant.io/t/2021-10-update-frigate/344842/4) with the same issue. I've attached what shows up on my integrations page.

![frigate_HA_Integration_Error](https://user-images.githubusercontent.com/44226464/136563962-051cd185-0e35-48d3-9014-83b9c4b80dfb.png)

I've already tried a few different fixes, such as:
- Rebuilding the Integration from HA's Supervisor Module
- Removing and Re-adding it from the Integration screen
- Uninstalling and Reinstalling
- Uninstalling, Confirming its removal from Integrations and Installing again

Note, during all those tests, I restarted my HA server after every change. 

It seems like the HA updated broke something in where Frigate should be pointing to gather API information - such as my IP - but I'm not sure if HA is broken within itself, or if it pushed Frigate off course. I'm going to look through the code as best I can soon. 

### Version

2.0

### Frigate config file

```yaml
mqtt:
  host: IP_ADDR
  port: 1883
  client_id: "frigate"
  user: USER
  password: PASS

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  quality: 8
  mode: objects

cameras:
  north:
    ffmpeg:
      inputs:
        - path:  rtsp://USER:PASS@IP_ADDR:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5

    zones:
      north1:    
        coordinates: 997,989,968,1920,2560,1920,2560,848,1736,611,1320,579
      north2:
        coordinates: 2531,472,2560,675,0,541,197,416
      north3:
        coordinates: 2560,476,2560,0,751,0,797,444

    record:
      enabled: False
    
    rtmp:
      enabled: True

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 10
    
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
  
    objects:
      track:
        - person
        - dog
        - cat
    
  south:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASS@IP_ADDR:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    zones:
      south1:
        coordinates: 2560,1336,2560,645,2389,549,2102,1138,2247,1434,2560,1855
      south2:
        coordinates: 0,1920,0,1000,507,764,2018,649,2425,1920
      south3:
        coordinates: 1738,26,2121,383,2109,603,1044,621,42,766,0,0
      south4:
        coordinates: 2560,652,2560,0,1866,0,1766,82

    clips:
      enabled: False
    
    rtmp:
      enabled: True

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 10
    
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
  
    objects:
      track:
        - person
        - dog
        - cat
```

### Relevant log output

```shell
`2021-10-08 09:10:26 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.5', 5000)]`
`2021-10-08 09:11:46 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:157
Integration: Frigate (documentation, issues)
First occurred: 9:01:26 AM (4 occurrences)
Last logged: 9:06:13 AM

Timeout error fetching information from http://ccab4aaf-frigate:5000/api/stats:
```

### FFprobe output from your camera

```shell
Unavailable due to error
```

### Frigate stats

```json
Unavailable due to error
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 520
