### ISSUE TITLE
[Support]: Frigate not loading after Docker container upgrade (UNRAID)

### ISSUE THREAD

**Issue by The-IcEDFiRE** [blakeblackshear/frigate#1961]
### Describe the problem you are having

After upgrading Frigate (running as a Docker Container in UNRAID) it saying the config file is incorrect and shuts down.

### Version

0.9.1-800f33e

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p  

# Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global input args
  
  #input_args for RTSP streams (Reolink)
  #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -flags low_delay -fflags nobuffer

  #input_args for RTMP streams
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - "1"
    
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # Optional: output args for clips streams (default: shown below)
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv

detectors:
  cpu1:
    type: cpu
  #cpu2:
  #  type: cpu
  #cpu3:
  #  type: cpu
  #cpu4:
  #  type: cpu

mqtt:
  host: mosquitto
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass
  stats_interval: 60

snapshots:
  retain:
    # Required: Default retention days (default: shown below)
    default: 2
    # Optional: Per object retention days
    objects:
      person: 2

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 0
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

clips:
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
  #tmpfs_cache_size: 256m

# Optional: 24/7 recording configuration
record:
  # Optional: Enable recording (default: global setting)
  enabled: True
  # Optional: Number of days to retain (default: global setting)
  retain_days: 14 

cameras:
  CommonArea:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.50.230:1935/bcs/channel0_sub.bcs?channel=0&stream=1&user=user&password=pass
          roles:
            - detect
            - rtmp
            - record
            
        - path: rtmp://192.168.50.230:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            #- record
            - clips
            #- rtmp
    width: 640
    height: 480
    fps: 7
    detect:
      enabled: True
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
    snapshots:
      enabled: True
  Kitchen:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.50.231:1935/bcs/channel0_sub.bcs?channel=0&stream=1&user=user&password=pass
          roles:
            - detect
            - rtmp
            - record
        - path: rtmp://192.168.50.231:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            #- record
            - clips
            #- rtmp
    width: 640
    height: 480
    fps: 7
    detect:
      enabled: False
      max_disappeared: 25
  Living:
    ffmpeg:
       inputs:
        - path: rtmp://192.168.50.232:1935/bcs/channel0_sub.bcs?channel=0&stream=1&user=user&password=pass
          roles:
            - detect
            - rtmp
            - record
        - path: rtmp://192.168.50.232:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            #- record
            - clips
            #- rtmp
    width: 640
    height: 480
    fps: 7
    detect:
      enabled: False
      max_disappeared: 25
    record:
      enabled: true
  KidsRoom:
    ffmpeg:
       inputs:
        - path: rtmp://192.168.50.233:1935/bcs/channel0_sub.bcs?channel=0&stream=1&user=user&password=pass
          roles:
            - detect
            - rtmp
            - record
        - path: rtmp://192.168.50.233:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            #- record
            - clips
            #- rtmp
    width: 640
    height: 480
    fps: 7
    detect:
      enabled: False
      max_disappeared: 25
  MainBedroom:
    ffmpeg:
       inputs:
        - path: rtmp://192.168.50.234:1935/bcs/channel0_sub.bcs?channel=0&stream=1&user=user&password=pass
          roles:
            - detect
            - rtmp
            - record
        - path: rtmp://192.168.50.234:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            #- record
            - clips
            #- rtmp
    width: 640
    height: 480
    fps: 7
    detect:
      enabled: False
      max_disappeared: 25
  Study:
    ffmpeg:
       inputs:
        - path: rtmp://192.168.50.235:1935/bcs/channel0_sub.bcs?channel=0&stream=1&user=user&password=pass
          roles:
            - detect
            - rtmp
            - record
        - path: rtmp://192.168.50.235:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            #- record
            - clips
            #- rtmp
    width: 640
    height: 480
    fps: 7
    detect:
      enabled: False
      max_disappeared: 25
  RearTerrace:
    ffmpeg:
      output_args:
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy
      hwaccel_args: []
      inputs:
        - path: rtsp://user:ITComp06@192.168.50.20:8554/RearTerrace/subStream
          roles:
            - detect
            - rtmp
            - record
        - path: rtsp://user:ITComp06@192.168.50.20:8554/RearTerrace/mainStream
          roles:
            #- record
            - clips
            #- rtmp
    objects:
      track:
        - person
    width: 704
    height: 480
    fps: 10
    detect:
      enabled: True
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
    snapshots:
      enabled: True
```

### Relevant log output

```shell
[2021-10-08 10:55:56] frigate.app INFO : Starting Frigate (0.9.1-800f33e)
Error parsing config: 33 validation errors for FrigateConfig

ffmpeg -> output_args -> clips
extra fields not permitted (type=value_error.extra)
cameras -> CommonArea -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> CommonArea -> clips
extra fields not permitted (type=value_error.extra)
cameras -> CommonArea -> fps
extra fields not permitted (type=value_error.extra)
cameras -> CommonArea -> height
extra fields not permitted (type=value_error.extra)
cameras -> CommonArea -> width
extra fields not permitted (type=value_error.extra)
cameras -> Kitchen -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Kitchen -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Kitchen -> height
extra fields not permitted (type=value_error.extra)
cameras -> Kitchen -> width
extra fields not permitted (type=value_error.extra)
cameras -> Living -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Living -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Living -> height
extra fields not permitted (type=value_error.extra)
cameras -> Living -> width
extra fields not permitted (type=value_error.extra)
cameras -> KidsRoom -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> KidsRoom -> fps
extra fields not permitted (type=value_error.extra)
cameras -> KidsRoom -> height
extra fields not permitted (type=value_error.extra)
cameras -> KidsRoom -> width
extra fields not permitted (type=value_error.extra)
cameras -> MainBedroom -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> MainBedroom -> fps
extra fields not permitted (type=value_error.extra)
cameras -> MainBedroom -> height
extra fields not permitted (type=value_error.extra)
cameras -> MainBedroom -> width
extra fields not permitted (type=value_error.extra)
cameras -> Study -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> Study -> fps
extra fields not permitted (type=value_error.extra)
cameras -> Study -> height
extra fields not permitted (type=value_error.extra)
cameras -> Study -> width
extra fields not permitted (type=value_error.extra)
cameras -> RearTerrace -> ffmpeg -> output_args -> clips
extra fields not permitted (type=value_error.extra)
cameras -> RearTerrace -> ffmpeg -> inputs -> 1 -> roles -> 0
value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> RearTerrace -> clips
extra fields not permitted (type=value_error.extra)
cameras -> RearTerrace -> fps
extra fields not permitted (type=value_error.extra)
cameras -> RearTerrace -> height
extra fields not permitted (type=value_error.extra)
cameras -> RearTerrace -> width
extra fields not permitted (type=value_error.extra)
clips
extra fields not permitted (type=value_error.extra)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
The cameras are working ok. Don't think that's the issue here.
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink E1 Zoom
