### ISSUE TITLE
[Support]:  amcrest setup

### ISSUE THREAD

**Issue by tiger-bug** [blakeblackshear/frigate#1963]
### Describe the problem you are having

Hello,

I am still new to Home assistant and Frigate (and security cameras in general).  I am attempting to set up my amcrest camera buy I am only getting a green screen in Frigate.  As you can see from the relevant log output, It appears it has to do  with my rtsp path.  However, according to [Amcrest](https://support.amcrest.com/hc/en-us/articles/360052688931-Accessing-Amcrest-Products-Using-RTSP), you access the rtsp stream via

**IP Cameras**: rtsp://[username]:password@IPaddress:554/cam/realmonitor?channel=1&subtype=0

I've also tried **rtsp://[username]:[password]@[IPaddress]:[port]/h264Preview_[channel]_[stream]** for the path but both give an error. Thanks!

### Version

2.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.121
  user: mqttuser
  password: <my_mqtt_password>

cameras:
  amcrest1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<my_camera_password>@192.168.50.110:554/cam/realmonitor?channel=1&subtype=0

          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
```

### Relevant log output

```shell
[2021-10-08 12:52:09] watchdog.amcrest1              ERROR   : FFMPEG process crashed unexpectedly for amcrest1.
[2021-10-08 12:52:09] watchdog.amcrest1              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-10-08 12:52:09] watchdog.amcrest1              ERROR   : You may have invalid args defined for this camera.
[2021-10-08 12:52:09] ffmpeg.amcrest1.detect         ERROR   : [tcp @ 0x559ca2ed60c0] Port missing in uri
[2021-10-08 12:52:09] ffmpeg.amcrest1.detect         ERROR   : rtsp://admin:<my camera password>@192.168.50.110:554/cam/realmonitor?channel=1&subtype=0: Invalid argument
[2021-10-08 13:01:23] frigate.video                  INFO    : amcrest1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
```

### FFprobe output from your camera

```shell
N/A (not sure where to run this.  Like I said, still new)
```

### Operating system

HassOS

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Amcrest UltraHD 5MP Outdoor POE Camera 2592 x 1944p Bullet IP Security Camera, Outdoor IP67 Waterproof, 103° Viewing Angle, 2.8mm Lens, 98.4ft Night Vision, 5-Megapixel, IP5M-B1186EW-28MM (White)

**Comment by brandonleon** [comment]
Validate your resolution is correct, connect to your camera in a browser and go to Setup in the top right and then Under Camera -> Video get the resolution and use that to update the values you have listed under 

```
detect:
      width: 1920
      height: 1080
```

Additionally you may want to use the sub-stream for detection and the main stream for recording. here is my config.

```
cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.2.3.4:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
        - path: rtsp://user:pass@1.2.3.4:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 704
      height: 480

```
