### ISSUE TITLE
[Support]: Suddenly not working

### ISSUE THREAD

**Issue by provaprova1** [blakeblackshear/frigate#1965]
### Describe the problem you are having

Hi
all of a sudden frigate stopped working without any changes to HA, configuration file or update
Everything else on HA is working properly and so the stream of the video
Web interface doesn't open up and keep loading endlessly

### Version

doesn't open up, keep loading endlessly

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:

  host: core-mosquitto
  # Optional: port (default: shown below)
  port: 1883
  # Optional: user
  user: pai
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
detect:
  max_disappeared: 300

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.201:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.201:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    motion:
      mask: 267,0,262,83,452,94,468,0
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.202:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.202:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    motion:
      mask: 0,135,0,0,262,0,229,40,82,126,0,191
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.203:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.203:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.204:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.204:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
  camera5:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.205:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.205:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    motion:
      mask: 498,0,405,21,800,67,800,0,423,0,485,0,261,65,283,146,217,157,88,78,0,83,0,0
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
  camera6:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.206:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.206:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
  camera7:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.207:554/12
          roles:
            - clips
        - path: rtsp://user:pass@192.168.1.207:554/12
          roles:
            - detect
    width: 800
    height: 600
    fps: 5
    snapshots:
      enabled: true
      bounding_box: true
    clips:
      enabled: true
```

### Relevant log output

```shell
[2021-10-09 11:19:13] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e)
Error parsing config: 35 validation errors for FrigateConfig
cameras -> camera1 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera1 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera1 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera1 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera1 -> width
  extra fields not permitted (type=value_error.extra)
cameras -> camera2 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera2 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera2 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera2 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera2 -> width
  extra fields not permitted (type=value_error.extra)
cameras -> camera3 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera3 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera3 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera3 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera3 -> width
  extra fields not permitted (type=value_error.extra)
cameras -> camera4 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera4 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera4 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera4 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera4 -> width
  extra fields not permitted (type=value_error.extra)
cameras -> camera5 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera5 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera5 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera5 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera5 -> width
  extra fields not permitted (type=value_error.extra)
cameras -> camera6 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera6 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera6 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera6 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera6 -> width
  extra fields not permitted (type=value_error.extra)
cameras -> camera7 -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> camera7 -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> camera7 -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> camera7 -> height
  extra fields not permitted (type=value_error.extra)
cameras -> camera7 -> width
  extra fields not permitted (type=value_error.extra)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

SV3C
