### ISSUE TITLE
[Support]: frigate/events MQTT message not being  sent

### ISSUE THREAD

**Issue by davidcoulson** [blakeblackshear/frigate#1966]
### Describe the problem you are having

Since upgrading to 0.9.1 (via HA Addons) it appears I no longer receive a frigate/events message when an event is generated. I have confirmed via both Node-Red and MQTT Explorer when Frigate logs an event (specifically garage zone, car object), nothing is in MQTT. I do have a frigate/available message, so I believe that indicates Frigate is connected to the MQTT broker (just using MQTT Addon for HassOS - nothing special here).

This was working with older Frigate build, so not sure if defect or I messed up migrating the config to support 0.9.x.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto

cameras:
  sunroom:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXX@10.2.4.39:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXX@10.2.4.39:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 1920,1080,0,1080,93,783,163,791,163,906,500,957,568,845,767,814,766,896,920,951,1325,855,1331,707,1363,753,1920,743
    detect:
      enabled: True
      max_disappeared: 25
      width: 704
      height: 480
      fps: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX@10.2.4.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXX@10.2.4.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 616,305,628,198,649,116,720,91,720,0,0,0,0,576,185,576,136,338
    zones:
      Front Path:
        coordinates: 720,576,720,376,614,365,608,332,288,364,320,503,255,576
    detect:
      enabled: True
      max_disappeared: 25
      fps: 5
      width: 720
      height: 576
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX@10.2.3.126:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXX@10.2.3.126:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      Deck:
        coordinates: 217,163,284,143,527,230,556,267,544,325,640,366,640,480,102,480,38,254,28,168,66,139,128,122
      Lawn:
        coordinates: 343,58,462,77,591,124,640,166,640,365,550,319,559,263,525,227,308,154,264,149,217,157,117,120,175,66
    detect:
      enabled: True
      max_disappeared: 25
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX@10.2.3.117:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXX@10.2.3.117:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 640,0,0,0,0,215,68,210,155,243,228,247,640,342
    zones:
      Driveway:
        coordinates: 0,480,0,213,53,209,156,248,229,245,640,346,640,480
    detect:
      enabled: True
      max_disappeared: 25
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

record:
  enabled: true
  retain_days: 0
  events:
    retain:
      default: 10

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - truck
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: True
  timestamp: false
  bounding_box: true
  retain:
    default: 3
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest
