### ISSUE TITLE
[Support]: Can't use environment variable for mqtt user (can for password)

### ISSUE THREAD

**Issue by lindsaymarkward** [blakeblackshear/frigate#1976]
### Describe the problem you are having

I have a working Frigate setup (recently upgraded to current 0.9), and now I want to use environment variables for my MQTT username and password.
I can get the password to work, but when I use an environment variable for the user field, Frigate is "unable to connect to MQTT server".

The debug output in the web UI shows that the password is parsed, but the user is not - it's still in the variable name format.

    "mqtt": {
      "client_id": "frigate",
      "host": "mosquitto",
      "password": "REDACTED",
      "port": 1883,
      "stats_interval": 60,
      "tls_ca_certs": null,
      "tls_client_cert": null,
      "tls_client_key": null,
      "tls_insecure": null,
      "topic_prefix": "frigate",
      "user": "{FRIGATE_MQTT_USER}"
    },

Is this a problem in my setup, as I cannot see any difference with how I've set these two environment variables other than their names... or is it that Frigate doesn't parse every value for environment variables?
Thanks!

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hauser
  # user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

cameras:
  frontdoor:
...

and here is my docker-compose section:

frigate:
    image: blakeblackshear/frigate:stable-armv7
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro  
      - /data/frigate/config:/config
      - /media/frigate:/media/frigate
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "${FRIGATE_RTSP_PASSWORD}"
      FRIGATE_MQTT_USER: "${MQTT_USER}"
      FRIGATE_MQTT_PASSWORD: "${MQTT_PASSWORD}"

(I can confirm that the MQTT user environment variable works for other containers, and that the MQTT_PASSWORD variable works for Frigate.)
```

### Relevant log output

```shell
frigate          | 2021-10-10T12:43:16.392475765Z [2021-10-10 22:43:16] frigate.mqtt                   ERROR   : Unable to connect to MQTT server: MQTT Not authorized
frigate          | 2021-10-10T12:43:16.395234271Z [2021-10-10 22:43:16] frigate.mqtt                   INFO    : MQTT connected
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":462.34,"pid":214}},"driveway":{"camera_fps":5.1,"capture_pid":227,"detection_fps":0.0,"pid":221,"process_fps":5.1,"skipped_fps":0.0},"frontdoor":{"camera_fps":5.1,"capture_pid":226,"detection_fps":0.0,"pid":218,"process_fps":5.1,"skipped_fps":0.0},"patio":{"camera_fps":5.1,"capture_pid":229,"detection_fps":0.0,"pid":223,"process_fps":5.1,"skipped_fps":0.0},"pool":{"camera_fps":5.1,"capture_pid":233,"detection_fps":0.0,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":63.7,"mount_type":"tmpfs","total":67.1,"used":3.4},"/media/frigate/clips":{"free":577085.6,"mount_type":"ext4","total":984390.2,"used":367276.5},"/media/frigate/recordings":{"free":577085.6,"mount_type":"ext4","total":984390.2,"used":367276.5},"/tmp/cache":{"free":577085.6,"mount_type":"overlay","total":984390.2,"used":367276.5}},"uptime":482,"version":"0.9.1-800f33e"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

If it is that Frigate doesn't parse the `user` value for environment variables, can you please consider this as a feature request? And also a suggestion for updating the documentation?
I'm happy to help contribute if I know what's needed. Thanks again.
