### ISSUE TITLE
[Support]: Hig CPU usage for MJPEG camera and new way of doing clips

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#1980]
### Describe the problem you are having

I see Frigate CPU usage at 100% since the upgrade and causing my Intel i3 system to heat. I have a MJPEG camera and was encoding to H.264 to be able to view the saved event clips from the media browser and notification but due to the new way of always recording this means that Frigate is always transcoding. Is there a way to fix this ?
p.s. I commented out the transcoding line in the configuration

### Version

 0.9.1-800f33e

### Frigate config file

```yaml
# frigate.yml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: xxx.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxxxxx
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  driveway:
    objects:
      track:
        - person
#        - truck
#        - bicycle
#        - motorcycle
      filters:
        person:
          mask:
            - 95,38,317,64,640,130,640,0,0,0,0,42
          min_score: 0.49
          threshold: 0.54
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.6.140/2
          roles:
            - detect
        - path: rtsp://admin:xxxx@192.168.6.140/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 5  
    motion:
      mask:
        - 95,38,317,64,640,130,640,0,0,0,0,42         
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 5
#    clips:
#      enabled: true
#      retain:
#        default: 5
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 2
################################################        
  front_porch_camera:
    objects:
      track:
        - person
#        - car
#        - truck
#        - bicycle
#        - motorcycle

     # Optional: save clips configuration    

    ffmpeg:
      inputs:
        - path: http://admin:xxxx@192.168.6.19/video.cgi 
          roles:
            - detect
            - record

          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
      output_args:
         record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -pix_fmt yuv420p -an 
    detect:
      width: 640
      height: 480
      fps: 5  
#    clips:
#      enabled: true
#      retain:
#        default: 7
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 7
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dlink DCS-932l

### Any other information that may be helpful

Look at the front porch camera config
