### ISSUE TITLE
[Support]: database disk image is malformed

### ISSUE THREAD

**Issue by jarekgrzabel** [blakeblackshear/frigate#1985]
### Describe the problem you are having

Hi,

After upgrading to version 2.0, I've changed the config file as required, restarted Frigate but it drops a migration error. I tried to uninstall it and install back in, unfortunately, that didn't work.

Home Assistant Core version: core-2021.10.3

Any help is appreciated.

### Version

2.0

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  topic_prefix: frigate
  client_id: frigate
cameras:
  office:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.32:554/Streaming/channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 1
    motion:
      mask:
        - 153,0,366,0,640,0,640,360,389,360,366,74,227,83,259,360,0,360,0,182,0,77,0,0,0,0
  korytarz:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass!@192.168.1.32:554/Streaming/channels/202
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 1
    motion:
      mask:
        - 0,360,0,0,280,0,405,0,640,0,640,360,380,360,404,194,247,212,234,360,118,360

ffmpeg:
  global_args: -hide_banner -loglevel info
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
[2021-10-11 09:13:22] peewee_migrate                 INFO    : Starting migrations
Migrate "004_add_bbox_region_area"
[2021-10-11 09:13:22] peewee_migrate                 INFO    : Migrate "004_add_bbox_region_area"
add_column ('event', 'region', <JSONField: Event.region>)
[2021-10-11 09:13:22] peewee_migrate                 INFO    : add_column ('event', 'region', <JSONField: Event.region>)
database disk image is malformed
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
