### ISSUE TITLE
[Support]: Blank Mask setting causes no detection

### ISSUE THREAD

**Issue by madmic1314** [blakeblackshear/frigate#1996]
### Describe the problem you are having

Noticed in config that a blank mask setting will cause object detection not to run.

If you have:
motion:
  mask:
best_image_timeout: 60

This will cause object detection not to run. Whereas:
motion:
  mask:
    - 0,360,137,360,79,217,191,181,212,120,137,99,52,140,39,24,55,0,0,0
    - 395,0,539,117,640,164,640,0
best_image_timeout: 60

Works as expected. Equally commenting out or removing the mask: line works as expected as well. A very small bug, but confused me whilst playing with masks. Be better if the config parser failed or ignored the mask to send the entire image.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
#          mask:
#            - 0,360,137,360,79,217,191,181,212,120,148,92,64,139,53,95,111,75,114,54,94,45,45,45,65,0,0,0
#            - 395,0,539,117,640,164,640,0
```

### Relevant log output

```shell
None, Frigate starts normally.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision
