### ISSUE TITLE
The documentation is a bit unclear about zones.

### ISSUE THREAD

**Issue by frankhommers** [blakeblackshear/frigate#200]
Is it correct that in your example config yaml:
```
zones:
  #################
  # Name of the zone
  ################
  front_steps:
    front_door:
```

"front_steps" = the name of a zone?
"front_door" = the name of a camera?
