### ISSUE TITLE
[Support]: Restore events after updating on docker-compose

### ISSUE THREAD

**Issue by maxi1134** [blakeblackshear/frigate#2000]
### Describe the problem you are having

 When updating from a version to a newer one, it appears that the events are no longer loaded in the Frigate interface.
 
 Is there a way to import them? 
So that I can keep historical data between updates.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
FRIGATE
FRIGATE
Cameras
Birdseye
Events
Debug
Documentation
GitHub
DEBUG 0.9.1-800F33E
detector	detection start	inference speed	pid
coral	1634074240.46192	15.84	233
camera	camera fps	capture pid	detection fps	pid	process fps	skipped fps
facecam	5.1	267	35.2	255	5.2	0
front_door	5.1	258	7.9	240	5.2	0
geovision	5.1	264	1.3	247	5	0
patiocam	5	269	0.2	257	5	0
Debug stats update automatically every 60 seconds.

CONFIG
COPY TO CLIPBOARD
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "facecam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 2304,
        "max_disappeared": 25,
        "width": 1296
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:PASSWORD@192.168.50.9:8554/12",
            "roles": [
              "detect",
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": "-vf transpose=1 -f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtsp://admin:PASSWORD@192.168.50.9:8554/12 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/facecam-%Y%m%d%H%M%S.mp4 -r 5 -s 1296x2304 -vf transpose=1 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 143,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 384,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "facecam",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "1296,2304,1296,1584,1296,1425,646,1413,0,1455,0,2304"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 600,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {
              "person": 15
            }
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "front_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1920,
        "max_disappeared": 25,
        "width": 2560
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.0.210/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=PASSWORD",
            "roles": [
              "detect",
              "record",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtmp://192.168.0.210/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=PASSWORD -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/front_door -r 5 -s 2560x1920 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 237,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 320,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_door",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": [
              "0,1920,813,1920,1304,966,1049,433,0,1441"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": [
              "777,461,991,344,1384,319,1708,0,0,0,0,1084"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [
              "1822,718,1878,0,1324,0,0,0,0,1207,0,1920,402,1920,597,1566,713,1455,745,1388,794,1331,815,1327,820,1279,1102,922,1239,924,1381,670"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 600,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [
            "entrance"
          ],
          "retain": {
            "default": 10,
            "objects": {
              "person": 15
            }
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "entrance"
        ],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "entrance": {
          "coordinates": "2560,1920,2560,0,1661,0,1410,359,950,442,0,1253,0,1920",
          "filters": {},
          "objects": []
        }
      }
    },
    "geovision": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1920,
        "max_disappeared": 25,
        "width": 1080
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://192.168.50.3:8554/CH001.sdp",
            "roles": [
              "detect",
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": "-vf transpose=1 -f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtsp://192.168.50.3:8554/CH001.sdp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/geovision-%Y%m%d%H%M%S.mp4 -r 5 -s 1080x1920 -vf transpose=1 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 99,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 320,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "geovision",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "359,1920,0,1920,0,0,44,0,190,0,310,0,111,633,239,1001,442,1165,434,1255"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 600,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {
              "person": 15
            }
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "patiocam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "width": 1920
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:PASSWORD@192.168.50.8/live",
            "roles": [
              "detect",
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtsp://admin:PASSWORD@192.168.50.8/live -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/patiocam-%Y%m%d%H%M%S.mp4 -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 99,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "patiocam",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "1296,2304,1296,1584,1296,1425,646,1413,0,1455,0,2304"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 600,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {
              "person": 15
            }
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/config/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": 25,
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.0.15",
    "password": "password",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt_user"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{
    "detection_fps": 62.9,
    "detectors": {
        "coral": {
            "detection_start": 1634074362.09378,
            "inference_speed": 14.85,
            "pid": 233
        }
    },
    "facecam": {
        "camera_fps": 5.1,
        "capture_pid": 267,
        "detection_fps": 28.7,
        "pid": 255,
        "process_fps": 4.1,
        "skipped_fps": 0
    },
    "front_door": {
        "camera_fps": 5.1,
        "capture_pid": 258,
        "detection_fps": 21.5,
        "pid": 240,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "geovision": {
        "camera_fps": 5.1,
        "capture_pid": 264,
        "detection_fps": 7,
        "pid": 247,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "patiocam": {
        "camera_fps": 5.1,
        "capture_pid": 269,
        "detection_fps": 5.7,
        "pid": 257,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "service": {
        "storage": {
            "/dev/shm": {
                "free": 2111.2,
                "mount_type": "tmpfs",
                "total": 2147.5,
                "used": 36.3
            },
            "/media/frigate/clips": {
                "free": 2606843.1,
                "mount_type": "cifs",
                "total": 5996476.9,
                "used": 3389633.8
            },
            "/media/frigate/recordings": {
                "free": 2606843.1,
                "mount_type": "cifs",
                "total": 5996476.9,
                "used": 3389633.8
            },
            "/tmp/cache": {
                "free": 9980.6,
                "mount_type": "tmpfs",
                "total": 10000,
                "used": 19.4
            }
        },
        "uptime": 5609,
        "version": "0.9.1-800f33e"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

PTZ: ‎RLC-423, FACECAM: Some chinese minicam, PatioCam: Wyzecam V2 with Official RTSP firmware, Geovision: gv-VD2400

### Any other information that may be helpful
I do a docker pull between updates. and RM the docker before running docker compose up
