### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by VMBindraban** [blakeblackshear/frigate#2002]
### Describe the problem you are having

I am trying to start frigate with the docker-compose file below but it keeps returning an error.
The config file itself is empty.

I gave it 777 permissions but with no success.

### Version

0.9.1

### Frigate config file

```yaml
None
```

### Relevant log output

```shell
[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Error parsing config: 1 validation error for FrigateConfig

__root__

  FrigateConfig expected dict not NoneType (type=type_error)

[cmd] python3 exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink 822A

### Any other information that may be helpful

Docker-compose file:

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume3/docker/frigate/config.yml:/config/config.yml:ro
      - /volume3/docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
