### ISSUE TITLE
[Support]: Some "clips" do not play

### ISSUE THREAD

**Issue by sanderlv** [blakeblackshear/frigate#2007]
### Describe the problem you are having

Clips do not play since update to latest version of frigate

### Version

0.9.1-800f33e

### Frigate config file

```yaml
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects

database:
  path: /media/frigate/db/frigate.db

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

record:
  enabled: true
  retain_days: 10
  events:
    retain:
      default: 14


# MQTT Config ##########################################################################################################
mqtt:
  host: 192.168.1.142
  port: 1883
  topic_prefix: frigate112
  client_id: frigate112
  user: mqtt
  password: mqtt
  stats_interval: 60

# Cameras Config ######################################################################################################
cameras:
# FRONT Camera ########################################################################################################
  front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.3.20:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      enabled: True
      max_disappeared: 2
      width: 2560
      height: 1440
      fps: 6
    snapshots:
      enabled: true
      crop: false
      bounding_box: True
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
        - '1090,81,1216,0,1382,34,1532,99,1518,259,1426,363,1123,247'
        - '1766,498,1753,669,1778,722,1829,773,1863,825,1906,884,1924,955,1953,1065,2237,1169,2255,1128,2295,1046,2338,946,2378,841,2410,743,2215,647,2190,582,2138,512,2010,402,1859,351'

# Back Camera ########################################################################################################
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.3.10:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      enabled: True
      max_disappeared: 2
      width: 2048
      height: 1536
      fps: 4
    snapshots:
      enabled: true
      crop: false
      bounding_box: True
    objects:
      track:
        - person
        - car
        - dog
        - bicycle
        - cat
      filters:
        car:
          min_score: 0.5
          threshold: 0.7
          mask:
            - '276,374,440,126,467,0,808,0,781,103,697,367'
            - '1723,199,2048,354,2048,585,1128,396,1086,128,1115,27'

# PARKING Camera ########################################################################################################
  parkeing:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.3.14:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      enabled: True
      max_disappeared: 2
      width: 3840
      height: 2160
      fps: 6
    snapshots:
      enabled: true
      crop: false
      bounding_box: True
    objects:
      track:
        - person
        - car
        - dog
        - bicycle
    motion:
      mask:
        - '2868,0,2839,240,2812,276,2775,329,2740,783,3840,1037,3840,0'
        - '2261,174,2190,154,2140,142,2096,133,2053,124,2002,122,1968,101,1914,71,1868,58,1817,56,1768,58,1716,69,1689,99,1642,100,1596,117,1566,137,1471,135,1419,162,1378,217,1364,278,1402,344,1474,393,1582,391,1652,347,1710,350,1786,361,1879,347,1991,328,2022,307,2046,289,2046,205,2074,189,2157,201,2154,330,2249,282'
        - '0,1896,153,2081,298,2049,403,1941,436,1839,439,1685,326,1492,142,1419,0,1531'
        - '1130,217,1265,271,519,597,1122,744,1104,990,1016,1049,464,838,426,620,415,564,412,494'
        - '398,490,483,455,605,416,730,372,754,339,751,233,744,167,695,122,645,105,569,99,497,110,441,119,365,189'
    zones:  
        parkeerplaats_voortuin_zone:
            coordinates: 297,2160,3840,2160,3840,1074,2754,786,2768,451,2128,325,1298,258,428,614,515,1002,620,1335,372,1573

# FRONT2 Camera ########################################################################################################
  front2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.3.29:554/Streaming/Channels/101/
          roles:
            - detect
            - record

    detect:
      enabled: True
      max_disappeared: 25
      width: 3840
      height: 2160
      fps: 6
    
    snapshots:
      enabled: true
      crop: false
      bounding_box: True
    objects:
      track:
        - person
        - car
        - dog
        - bicycle
        - cat
        - truck
    motion:
      mask:
        - '3840,751,3840,386,3560,283,3482,341,3275,293,3150,302,3102,481,2948,460,2937,541,2978,714,3306,1422,3714,1413,3840,1647'
        - '1961,892,1907,871,1876,878,1844,867,1787,874,1689,914,1569,896,1486,881,1417,829,1413,736,1374,606,1345,415,1456,293,2344,337,2319,507,2199,499,2194,610,2244,655,2249,786,2213,881,2160,900,2111,921,2024,928'
        - '553,1714,670,1791,726,1866,747,1950,1879,2160,548,2160,466,1880'
        - '265,1437,428,1486,496,1568,426,1728,351,1672,190,1571,222,1502'
        - '1508,0,1586,77,1587,194,1561,229,1493,268,1416,312,1342,304,1225,276,1182,201,1196,86,1274,0'
        - '560,1410,658,1426,739,1490,832,1590,872,1716,879,1823,839,1901,726,1889,661,1816,588,1744,510,1691,506,1539'
        - '499,1508,584,1357,683,1222,682,1155,665,1066,627,987,566,889,491,821,389,803,270,829,176,872,64,966,0,1055,21,1190,63,1323,151,1413,194,1449'

# TERRAS Camera ########################################################################################################
  terras:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.3.15:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    detect:
      enabled: True
      max_disappeared: 25
      width: 3840
      height: 2160
      fps: 4
    snapshots:
      timestamp: False
      bounding_box: True
      enabled: true
      crop: false
    objects:
      track:
        - bird
        - dog
        - cat
    motion:
      mask:    
        - '3840,0,3840,1295,3138,1412,3034,769,2958,382,2622,0'
        - '0,652,178,384,444,137,598,303,416,496,104,819,25,777'
        - '0,161,64,242,180,248,248,264,354,178,455,92,532,0,0,0'
      threshold: 25

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
No log
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
detection_fps	8.3
detectors	
coral	
detection_start	0
inference_speed	8.38
pid	219
parkeerplaats	
camera_fps	6
capture_pid	253
detection_fps	2.2
pid	235
process_fps	6
skipped_fps	0
schuurachter	
camera_fps	4
capture_pid	246
detection_fps	0
pid	234
process_fps	4
skipped_fps	0
service	
storage	
/dev/shm	
free	1020.4
mount_type	"tmpfs"
total	1073.7
used	53.3
/media/frigate/clips	
free	23346974.3
mount_type	"cifs"
total	30712218.6
used	7365244.3
/media/frigate/recordings	
free	4332.8
mount_type	"ext4"
total	50462.3
used	43707.6
/tmp/cache	
free	2946.2
mount_type	"tmpfs"
total	3000
used	53.8
uptime	578
version	"0.9.1-800f33e"
terras	
camera_fps	4.1
capture_pid	259
detection_fps	0
pid	241
process_fps	4.1
skipped_fps	0
voordeur	
camera_fps	6
capture_pid	245
detection_fps	0
pid	226
process_fps	6
skipped_fps	0
voortuin	
camera_fps	6
capture_pid	254
detection_fps	6.1
pid	240
process_fps	6.1
skipped_fps	0
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA

### Any other information that may be helpful

It used to work. I can't pinpoint why and what "clips" do and do not play. It seems random.
