### ISSUE TITLE
[Support]: Cannot play clips, Error: "The media could not be loaded, either because the server or network failed or because the format is not supported."

### ISSUE THREAD

**Issue by pitchblack53** [blakeblackshear/frigate#2008]
### Describe the problem you are having

After the latest update (1.4->2.0) I cannot play any clips anymore. I get the following error: "The media could not be loaded, either because the server or network failed or because the format is not supported."

First I thought that its a websocket issue, but I have a live view when looking at Birdseye viewer.

I tried thru my home assistant url or direct IP or navigating direct (via IP and port 5000), I always get the same two errors in the browser.
1a error (when using IP): GET http://172.24.0.40:5000/vod/event/1634147154.970065-jq6ken/index.m3u8 502 (Bad Gateway)
1b error (when using hass url): GET https://redacted.url.com/api/hassio_ingress/p35XeltYYoCEaoOwHgESZp4_r2A0JCxelxSW3oeWaA4/vod/event/1634152055.599177-x1uc5b/index.m3u8 502 (Bad Gateway)
2 error: VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

When checking the Frigate NVR log, I see this:
[2021-10-13 11:46:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57444]
[2021-10-13 11:47:55] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57444]
Just INFO messages, no ERRORs.

Also, when I click on donwload clip, it downloads a file called "clip.html".

When I navigate to my media folder (local storage) and try playing a clip, it does not play, just sits there and does nothing.

I also want to add, that everything else, like detection, snapshots etc all still works as expected, I just cannot view or download any clips.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "continuous",
    "quality": 1,
    "width": 1280
  },
  "cameras": {
    "front_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1920,
        "max_disappeared": 25,
        "width": 2560
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:REDACTED@172.24.0.235:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:LorEdu_1984@172.24.0.235:554/cam/realmonitor?channel=1&subtype=0 -c copy -f flv rtmp://127.0.0.1/live/front_door -r 5 -s 2560x1920 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 237,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 320,
        "mask": [
          "934,827,971,978,1160,962,1374,923,1479,959,1588,963,1589,666,1440,653,1421,782,1241,750,1176,523,975,521,908,651,818,751,811,821",
          "1936,741,2058,781,2087,847,2080,926,1739,945,1715,847,1742,743",
          "2118,945,2191,967,2242,943,2249,886,2308,818,2324,772,2263,719,2162,702,2108,745",
          "1634,1320,1908,1277,1921,1228,1752,1228,1605,1227",
          "863,1163,967,1210,1136,1206,1162,1300,804,1301,799,1194",
          "1217,911,1265,925,1295,975,1279,1098,1223,1095"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_door",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": [
              "1085,1035,1531,1019,1498,925,1088,925",
              "2104,946,1984,966,1946,1079,2300,1094,2293,955",
              "1171,980,1326,973,1423,1010,1419,1060,1164,1074"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "car",
          "dog",
          "bicycle",
          "motorcycle"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 7,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 7,
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "front_porch": {
          "coordinates": "763,1920,2347,1920,2484,1787,2217,1700,2331,1250,2078,1189,1546,1334,767,1420",
          "filters": {
            "person": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": []
        },
        "front_yard": {
          "coordinates": "1350,1110,1836,1265,1319,1368,756,1426,782,1142",
          "filters": {
            "person": {
              "mask": null,
              "max_area": 24000000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": []
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "width": 1280
  },
  "detectors": {
    "coral1": {
      "device": "pci:0",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "172.24.0.40",
    "password": "XXXXX",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "homeassistant"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-13 11:44:45] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e)
[2021-10-13 11:44:45] frigate.app                    INFO    : Creating directory: /tmp/cache
[2021-10-13 11:44:45] frigate.app                    WARNING : Camera front_door has record enabled, but record is not assigned to an input.
Starting migrations
[2021-10-13 11:44:45] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-10-13 11:44:45] peewee_migrate                 INFO    : There is nothing to migrate
[2021-10-13 11:44:45] frigate.mqtt                   INFO    : MQTT connected
[2021-10-13 11:44:45] frigate.app                    INFO    : Output process started: 218
[2021-10-13 11:44:45] ws4py                          INFO    : Using epoll
[2021-10-13 11:44:45] frigate.app                    INFO    : Camera processor started for front_door: 224
[2021-10-13 11:44:45] frigate.app                    INFO    : Capture process started for front_door: 226
[2021-10-13 11:44:45] ws4py                          INFO    : Using epoll
W driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 36 (Inappropriate ioctl for device)
[2021-10-13 11:44:45] detector.coral1                INFO    : Starting detection process: 217
[2021-10-13 11:44:45] frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
[2021-10-13 11:44:46] frigate.edgetpu                INFO    : TPU found
[2021-10-13 11:46:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57444]
[2021-10-13 11:47:55] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57444]
[2021-10-13 13:10:24] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46430]
[2021-10-13 13:10:47] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46430]
[2021-10-13 13:10:54] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46620]
[2021-10-13 13:11:26] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46620]
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:REDACTED@172.24.0.235:554/                                   
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x55f942078300] max delay reached. need to consume packet
[rtsp @ 0x55f942078300] RTP: missed 23 packets
[h264 @ 0x55f94207c3c0] corrupted macroblock 74 91 (total_coeff=-1)
[h264 @ 0x55f94207c3c0] error while decoding MB 74 91
[h264 @ 0x55f94207c3c0] concealing 4615 DC, 4615 AC, 4615 MV errors in P frame
[rtsp @ 0x55f942078300] max delay reached. need to consume packet
[rtsp @ 0x55f942078300] RTP: missed 4 packets
[h264 @ 0x55f94207c3c0] corrupted macroblock 83 83 (total_coeff=-1)
[h264 @ 0x55f94207c3c0] error while decoding MB 83 83
[h264 @ 0x55f94207c3c0] concealing 5886 DC, 5886 AC, 5886 MV errors in P frame
Input #0, rtsp, from 'rtsp://admin:REDACTED@172.24.0.235:554/':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.095000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":19.02,"pid":217}},"front_door":{"camera_fps":5.1,"capture_pid":226,"detection_fps":0.0,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":8383.1,"mount_type":"tmpfs","total":8391.0,"used":7.9},"/media/frigate/clips":{"free":72980.5,"mount_type":"ext4","total":100707.6,"used":23608.2},"/media/frigate/recordings":{"free":72980.5,"mount_type":"ext4","total":100707.6,"used":23608.2},"/tmp/cache":{"free":8391.0,"mount_type":"tmpfs","total":8391.0,"used":0.0}},"uptime":5426,"version":"0.9.1-800f33e"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

amcrest
