### ISSUE TITLE
[Support]: Clips missing actual events

### ISSUE THREAD

**Issue by MrAnonymous722** [blakeblackshear/frigate#2011]
### Describe the problem you are having

I will have motion events which have metadata that I would expect, for example, my mail man coming by generates an event that has expected time stamps (about 40 seconds worth of time), but the clip saved is only 12 seconds long and does not include any motion. Its also weird because I have 10 seconds of pre and post capture, so I'd expect the clip to be at least 20 seconds long. I do get a thumbnail with the person that set off the event. Furthermore, sometimes the clips will include the whole clip, but will later be cut much shorter. I have a clip that was over a minute that I watched shortly after it happened that is now only 4 seconds.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.127
  user: mqttuser
  password: ohnoiforgottoomitmypassword
detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
#  cpu3:
#    type: cpu
#  cpu4:
#    type: cpu
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: True
  mode: objects
motion:
  frame_height: 180
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
cameras:
  driveway-cam:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.0.213/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=ohnoiforgottoomitmypassword
          roles:
            - record
#            - rtmp
        - path: http://192.168.0.213/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=ohnoiforgottoomitmypassword
          roles:
            - detect
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 10
        post_capture: 10
        required_zones: [yard, driveway, porch]
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      required_zones: [yard, driveway, porch]
      enabled: True
      timestamp: True
      crop: True
    objects:
#      filters:
#        car:
#          mask:
#           - 1920,0,1920,206,1550,144,1027,129,609,181,383,229,0,379,0,88,61,0
      track:
       - person
       - car
#       - bicycle
       - dog
#       - cell phone
#       - bus
       - cat
    motion:
      mask: 190,7,297,13,452,10,452,27,190,26
    zones:
      yard:
        coordinates: 491,168,249,81,56,100,158,209
        objects:
         - person
         - dog
         - cat
      driveway:
        coordinates: 0,251,253,193,450,179,640,286,640,480,0,480
      porch:
        coordinates: 0,113,62,111,169,206,0,245
  garage-cam:
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        post_capture: 10
    ffmpeg:
      inputs:
       - path: rtsp://192.168.0.4:8554/garage-cam
         roles:
          - detect
          - record
    motion:
      mask:
        - 1387,1052,1868,1052,1863,1013,1389,1011
    snapshots:
      enabled: True
      timestamp: True
    objects:
      track:
       - person
       - backpack
  backyard-cam:
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        post_capture: 10
    motion:
      mask: 
       - 1872,1015,1876,1059,1383,1059,1381,1013
       - 478,114,737,109,1264,148,1479,0,1212,0,798,0,591,0,182,0,0,0,0,209
    ffmpeg:
      inputs:
       - path: rtsp://byard:ohnoiforgottoomitmypassword@192.168.0.141/live
         roles:
          - detect
          - record
    objects:
      filters:
        bird:
          mask:
           - 1920,781,1619,527,1683,250,1920,396
    snapshots:
      enabled: True
      timestamp: True
    objects:
      track:
       - person
       - bird
       - cat
       - dog
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
Nothing useable from this command
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink RLC 520

### Any other information that may be helpful

Running the camera via the example RLC configuration in the docs. Also as far as I know, this only happens with my RLC camera, though I don't have many other events on the other two so its hard to say that with any confidence.
