### ISSUE TITLE
[Support]: Events in new Recordings Go to UTC time

### ISSUE THREAD

**Issue by leadZERO** [blakeblackshear/frigate#2019]
### Describe the problem you are having

Love the new recordings/events display! My events get the correct thumbnail and times are displayed in local time in web interface. However, if you click on an event it will go to the UTC timestamp position in the recordings. If the event happened at 14:35 local time for me, when I click on the event it will go to 14:35 UTC (exactly X hours before the event occurred since I'm X hours behind UTC.

I'm guessing this is related to the fact my base system didn't have a local timezone set and was just in UTC. I actually prefer working in UTC usually (although in this instance I don't mind using local). However, I think it's probably a bug that the timeline doesn't jump to the correct timestamp.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: XXXXXXX
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

#ffmpeg:
#  hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128" ]

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain_days: 2
  events:
    max_seconds: 300
    objects: ["person","animal"]
    retain:
      default: 3

detect:
  width: 3840
  height: 2160
  fps: 5

snapshots:
  enabled: True
  timestamp: true

objects:
  track: ["person","animal"]

cameras:

  ############################
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX@192.168.1.149:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
            - record
    zones:
      front_deck:
        coordinates: 2560,589,2560,1920,0,1920,0,1071,647,894,1314,866,1645,840
      yard:
        coordinates: 1047,987,1032,792,863,744,314,630,286,744,0,695,41,1045,671,878
    detect:
      width: 2560
      height: 1920

  ############################
  front:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXXX@192.168.1.146:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    zones:
      yard:
        coordinates: 3840,544,3840,1570,2432,1559,887,968,1768,770,1060,569,945,449,1723,329,2474,326
      front_deck:
        coordinates: 2708,1573,2443,1603,772,934,1445,795,1442,692,1166,605,1090,443,904,340,0,482,0,2160,3840,2160,3840,1592
    record:
      events:
        required_zones:
          - front_yard

  ############################
  driveway_side:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    zones:
      yard:
        coordinates: 0,2160,3840,2160,3840,731,3316,653,2103,508,1832,452,1088,407,0,482
      driveway:
        coordinates: 1774,812,2691,728,2577,561,2025,471,1562,533
        objects: ["person", "animal", "vehicle"]
    objects:
      track: ["person", "animal", "vehicle"]
    record:
      events:
        required_zones:
          - yard
          - driveway

  ############################
  weather_station:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX@192.168.1.142:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
            - detect
    detect:
      width: 1920
      height: 1080
    objects:
      track: []
    record:
      retain_days: 1
      events:
        objects: []

  ############################
  back:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX@192.168.1.155:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    zones:
      lake_deck:
        coordinates: 3840,2160,3840,190,3628,176,2638,0,1933,0,1617,0,1433,159,1389,251,1283,349,1269,510,1336,508,279,1255,226,2160
      yard:
        coordinates: 310,1269,884,803,1269,558,1280,332,1428,276,1411,201,1143,248,775,533,340,666,0,959,0,2160,418,2160

  ############################
  lake:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX@192.168.1.144:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    zones:
      lake_deck:
        coordinates: 1620,1489,1849,1255,2315,1503,2276,2047,2064,2160,220,2160,0,2160,0,708,1104,521,1280,627,1255,878,1500,909
      yard:
        coordinates: 2256,1913,1693,1712,1514,1054,1274,996,1258,772,1570,759,2002,929,3804,1679,3840,2160,2122,2160

  ############################
  side_door:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXX@192.168.1.150:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
            - record
    zones:
      side_deck:
        coordinates: 2560,0,2097,0,2017,232,2168,431,2238,792,2105,801,2008,956,1753,976,1469,1019,43,1128,0,1920,2560,1920
      yard:
        coordinates: 2010,976,2101,794,1774,746,1292,777,892,825,535,913,130,1123,1021,1075
    detect:
      width: 2560
      height: 1920
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA

### Any other information that may be helpful

version: "3.8"
services:
  frigate:
    shm_size: 750m
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/dri/card0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml:ro
      - ./config/labelmap.txt:/labelmap.txt:ro
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - "FRIGATE_RTSP_PASSWORD=${FRIGATE_PASSWORD}"
      - "LIBVA_DRIVER_NAME=radeonsi"
      - "FRIGATE_MQTT_PASSWORD=${FRIGATE_MQTT_PASSWORD}"
