### ISSUE TITLE
Constantly creating clips despite no motion

### ISSUE THREAD

**Issue by jonnyrider** [blakeblackshear/frigate#202]
Using 0.6.0-rc1 and clips are being saved every 10 seconds, despite no motion being detected at the time:

![image](https://user-images.githubusercontent.com/48350560/93199163-ee3cfd80-f745-11ea-92d0-c5aca9318f8e.png)

My config is below (only shown camera with clips enabled:

```
web_port: 5000

mqtt:
  host: 192.168.1.3
  topic_prefix: frigate
  user: home
  password: xxxx



ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    - -r
    - '5'
    - -f
    - rawvideo
    - -pix_fmt
    - rgb24

objects:
  track:
    - person
    - cat
  filters:
    person:
      threshold: 0.8
      min_area: 50000
    cat:
      threshold: 0.7
      min_area: 5000
      max_area: 30000    

cameras:
  front:
    ffmpeg:
      input: rtsp://xxxxxx@192.168.1.41:554/videoMain
    mask: front.bmp     
    save_clips:
      enabled: True
      pre_capture: 5 
```

Happy to help debug further. I have tried restarting the container, completely removing the container and downloading again, and different config options including removing all cameras except the one I want to save clips for.

Thanks!
