### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by denperss** [blakeblackshear/frigate#2020]
### Describe the problem you are having

It was working fine before update now it wont boot :( 
Please help :( 

**This is the log file:** 

### Version

 2.0

### Frigate config file

```yaml
mqtt:
  host: xxxxx
  user: mqtt
  password: xxxxx

cameras:
  fi_indkorelsen:
    ffmpeg:
      #hwaccel_args:
        #- -c:v
        #- h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
      inputs:
        - path: rtsp://xxxxxxx/h264Preview_01_sub
          roles:
            - clips
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
        - cup
        - fire hydrant
        - bicycle
        - cell phone
        - mouse
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    clips: 
      enabled: True
    motion:
      mask:
        - 545,241,480,225,464,200,432,163,401,174,373,173,326,165,284,217,246,229,366,325

  fi_havelagen:
    ffmpeg:
      #hwaccel_args:
        #- -c:v
        #- h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
      inputs:
        - path: rtsp://xxxxxx/h264Preview_01_sub
          roles:
            - clips
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
        - cup
        - fire hydrant
        - bicycle
        - cell phone
        - mouse
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    clips: 
      enabled: True


  fi_doren:
    ffmpeg:
      #hwaccel_args:
        #- -c:v
        #- h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -r
        - "1" # <---- adjust depending on your desired frame rate from the mjpeg image
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://xxxxxxx/live1.sdp
          roles:
            - clips
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - cup
        - cell phone
        - mouse
        - dog
        - bird
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    clips: 
      enabled: True





detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-14 19:09:29] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e)
Error parsing config: 6 validation errors for FrigateConfig
cameras -> fi_indkorelsen -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> fi_indkorelsen -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> fi_havelagen -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> fi_havelagen -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> fi_doren -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> fi_doren -> clips
  extra fields not permitted (type=value_error.extra)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-14 19:09:29] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e)
Error parsing config: 6 validation errors for FrigateConfig
cameras -> fi_indkorelsen -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> fi_indkorelsen -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> fi_havelagen -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> fi_havelagen -> clips
  extra fields not permitted (type=value_error.extra)
cameras -> fi_doren -> ffmpeg -> inputs -> 0 -> roles -> 0
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
cameras -> fi_doren -> clips
  extra fields not permitted (type=value_error.extra)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink
