### ISSUE TITLE
[Support]: Overlapping events of same label in same zone

### ISSUE THREAD

**Issue by davidcoulson** [blakeblackshear/frigate#2021]
### Describe the problem you are having

I am seeing multiple events being generated for the same zone/label combination, that overlap - Not sure if this is normal behavior or why it thinks there are multiple events.

For example, there are three events of 'dog' in 'driveway' that go from:

19:02:38-19:02:59
19:02:51-19:03:80
19:02:58-19:03:22

It's all the same dog, so the motion should have been identified within the same area.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto

cameras:
  sunroom:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX@10.2.4.39:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXX@10.2.4.39:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 1920,1080,0,1080,93,783,163,791,163,906,500,957,568,845,767,814,766,896,920,951,1325,855,1331,707,1363,753,1920,743
    detect:
      enabled: True
      max_disappeared: 25
      width: 704
      height: 480
      fps: 5
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX@10.2.4.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXX@10.2.4.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 616,305,628,198,649,116,720,91,720,0,0,0,0,576,185,576,136,338
    zones:
      Front Path:
        coordinates: 720,576,720,376,614,365,608,332,288,364,320,503,255,576
    detect:
      enabled: True
      max_disappeared: 25
      fps: 5
      width: 720
      height: 576
  backyard:
    ffmpeg:
      output_args:
        detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 854:480 -c copy -f flv'
      inputs:
        - path: rtsp://XXXXX@10.2.3.126:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXX@10.2.3.126:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      Deck:
        coordinates: 349,146,408,145,706,223,753,260,735,318,854,357,854,480,102,480,38,254,25,157,166,118,275,158
      Lawn:
        coordinates: 343,58,577,65,796,118,854,156,854,367,729,313,752,260,698,224,409,145,343,144,281,162,174,125,97,130,117,120,205,67
    detect:
      enabled: True
      max_disappeared: 25
      height: 480
      width: 854
      fps: 5
  garage:
    ffmpeg:
      output_args:
        detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 854:480 -c copy -f flv'
      inputs:
        - path: rtsp://XXXXX@10.2.3.117:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXX@10.2.3.117:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 854,0,0,0,0,215,68,210,198,240,312,246,854,358
    zones:
      Driveway:
        coordinates: 0,480,0,213,75,206,209,241,318,245,854,349,854,480
    detect:
      enabled: True
      max_disappeared: 25
      height: 480
      width: 854
      fps: 5

record:
  enabled: true
  retain_days: 0
  events:
    retain:
      default: 10

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - truck
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 3
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
