### ISSUE TITLE
[Support]: Clip do not match detected event. 

### ISSUE THREAD

**Issue by JoachimAndersson** [blakeblackshear/frigate#2025]
### Describe the problem you are having

Clips do not match what was detected. 

The tumbnail has the correct detection, but the video when playing it does not have match.

As show in the tumbnail the Birds are there but no birds when playing the video.
![image](https://user-images.githubusercontent.com/8239367/137481465-876f73a5-1cb0-4f35-89c1-026920f4e84f.png)

### Version

DEBUG 0.9.1-800F33E

### Frigate config file

```yaml
logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.edgetpu: info

database:
  path: /media/database/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.0.68
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xx
  password: xx
      
ffmpeg:
  global_args: -hide_banner -loglevel error
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    #clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

objects:
  track:
    - person
    - vehicle
    - animal
    
  filters:
    person:
      min_area: 250
      max_area: 100000
      min_score: 0.5
      threshold: 0.68       

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 10
    post_capture: 5
    objects:
      - person
      - animal
      - vehicle
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    retain:
      default: 10
      # Optional: Per object retention days
      objects:
        person: 15

model  
  labelmap:
    1: vehicle
    2: vehicle
    3: vehicle
    4: vehicle
    5: vehicle
    6: vehicle
    7: vehicle
    8: vehicle
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

snapshots:
  timestamp: True
  enabled: True
  crop: True
  height: 500
  retain:
    default: 10
    objects:
      person: 150

cameras:
   main_door:
    mqtt:       
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.0.169:554/h265Preview_01_main
          roles: 
            - record
          input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - nobuffer
              - -flags
              - low_delay
              - -strict
              - experimental
              - -fflags
              - +genpts+discardcorrupt
              - -use_wallclock_as_timestamps
              - '1'

        - path: rtmp://192.168.0.169/bcs/channel0_ext.bcs?channel=0&stream=0&user=xxx&password=xxx
          roles:
            - detect
              #- clips
            - rtmp
          hwaccel_args:
            - -c:v
              #- h264_mmal
            - h264_v4l2m2m
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    best_image_timeout: 60
    rtmp:
      enabled: True
    detect:
      width: 896
      height: 512
      fps: 5
      enabled: True
      max_disappeared: 20
    zones:
      road:
        coordinates: 403,69,106,69,53,70,41,130,404,126
      entrance:
        coordinates: 97,512,629,512,424,135,263,137
      yard:
        coordinates: 97,512,629,512,424,135,263,137
        filters:
          person:
            threshold: 0.5
      door:
        coordinates: 436,186,479,265,247,281,268,210
        filters:
          person:
            threshold: 0.5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      retain:
        default: 10
        objects:
          person: 150
          vehicle: 150
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink
