### ISSUE TITLE
[Support]: Saving snapshots with additional time/date info

### ISSUE THREAD

**Issue by riskendemism** [blakeblackshear/frigate#2029]
### Describe the problem you are having

Hello,

is there a way to add time/date the saved snapshots in the clips folder? 
I ways thinking something like this "< camera >-< %Y%m%d-%H%M%S >-< id >.jpg"

Thank you for your help.
Cheers
Chris

### Version

0.9.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.237
  port: 1883
  topic_prefix: frigate_compretest
  stats_interval: 60

logger:
  default: info
  logs:
    frigate.event: debug
    frigate.app: debug
    detector.cpu: debug

birdseye:
  enabled: False

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180

snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  crop: False
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

cameras:
  WerkstattTest:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.0.91:1554/axis-media/media.amp?videocodec=h264&streamprofile=frigatedetect
          roles:
            - detect
            - rtmp
    detect:
      width: 1980
      height: 1080
    
    best_image_timeout: 60
```

### Relevant log output

```shell
a
```

### FFprobe output from your camera

```shell
a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Axis 1645
