### ISSUE TITLE
[Support]: rtmp can no longer be disabled globally

### ISSUE THREAD

**Issue by DeviantUK** [blakeblackshear/frigate#2055]
### Describe the problem you are having

rtmp can no longer be disabled globally in 0.9.2 (as documented [here](https://docs.frigate.video/configuration/index)) and now results in a validation error.

Quick fix is to explicitly disable rtmp on all cameras in the cameras section.

### Version

0.9.2-25bb515

### Frigate config file

```yaml
mqtt:
  host: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -c:v h264_v4l2m2m  # Raspberry Pi 3/4 (64-bit OS)

detect:
  width: 640
  height: 360
  fps: 3

# Optional: RTMP configuration
# NOTE: Can be overridden at the camera level
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False

cameras:
  Kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.39/ch0_1.h264
          roles:
            - detect
        - path: rtsp://192.168.1.39/ch0_0.h264
          roles:
            - record
    objects:
      track:
        - person
```

### Relevant log output

```shell
[2021-10-20 13:29:01] frigate.app                    INFO    : Starting Frigate (0.9.2-25bb515),
*************************************************************,
***    Your config file is not valid!                     ***,
***    Please check the docs at                           ***,
***    https://docs.frigate.video/configuration/index     ***,
***    Config Validation Errors                           ***,
1 validation error for FrigateConfig,
  Camera Kitchen has rtmp enabled, but rtmp is not assigned to an input. (type=value_error),
cameras,
***    End Config Validation Errors                       ***,
[cmd] python3 exited 1,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
