### ISSUE TITLE
[Support]: /api/events/<id>/clip.mp4 API not responding

### ISSUE THREAD

**Issue by pushpak1990** [blakeblackshear/frigate#2060]
### Describe the problem you are having

I am not able to download clips using `/api/events/<id>/clip.mp4` endpoint. 

There is no response. 

### Version

0.9.2-25bb515

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: homeassistant.local
  topic_prefix: security
  client_id: frigate
  user: frigate
  password: password


detectors:

  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3
  cpu5:
    type: cpu
    num_threads: 3
  cpu6:
    type: cpu
    num_threads: 3


database:
  path: /config/frigate.db


logger:
  default: info
  logs:
    frigate.event: debug


rtmp:
  enabled: True

snapshots:
  enabled: False
  timestamp: False
  bounding_box: False
  crop: False
  height: 720
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

record:
  enabled: False
  retain_days: 0
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 10
ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero

cameras:
  main_door:
    ffmpeg:
      inputs:
        - path: rtmp://ip/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@ip:554//h265Preview_01_main
          roles:
            - record
            # - detect
    motion:
      mask:
        - 640,216,597,213,545,209,461,195,360,173,325,162,262,148,311,157,0,178,0,0,640,0
    zones:
      front_yard:
        coordinates: 0,360,640,360,640,190,640,144,561,165,517,205,455,196,386,173,311,157,246,155,179,163,112,172,34,185,0,194,0,224,0,283
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bird
        - cow
        - sheep
        - bus
        - motorcycle
        - bicycle
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
          - front_yard
    record:
      enabled: True
      events:
        objects:
          - person
          - car
          - dog
          - cat
          - bird
          - cow
          - sheep
          - bus
          - motorcycle
          - bicycle
        required_zones:
          - front_yard
    detect:
      width: 640
      height: 360
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 720
      quality: 100
      required_zones:
        - front_yard


  south_pass:
    ffmpeg:
      inputs:
        - path: rtmp://ip/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - detect
            # - rtmp
        - path: rtmp://ip/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - record
            - rtmp
            # - detect
    motion:
      mask:
        - 238,136,572,0,640,0,640,360,640,360,461,223,371,183,315,178,244,178
    # zones:
    #   front_yard:
    #     coordinates: 0,360,640,360,640,190,640,144,561,165,517,205,455,196,386,173,311,157,246,155,179,163,112,172,34,185,0,194,0,224,0,283
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    snapshots:
      enabled: True
      bounding_box: True
      # required_zones:
      #     - front_yard
    record:
      enabled: True
      events:
        objects:
          - person
          - dog
          - cat
          - bird
        # required_zones:
        #   - front_yard
    detect:
      width: 640
      height: 480
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 720
      quality: 100
      # required_zones:
      #   - front_yard




  back_yard_south:
    ffmpeg:
      inputs:
        - path: rtmp://ip/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@ip:554//h265Preview_01_main
          roles:
            - record
            # - detect
    motion:
      mask:
        - 267,98,479,88,261,0,160,0,0,0,0,172
    # zones:
    #   front_yard:
    #     coordinates: 0,360,640,360,640,190,640,144,561,165,517,205,455,196,386,173,311,157,246,155,179,163,112,172,34,185,0,194,0,224,0,283
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    snapshots:
      enabled: True
      bounding_box: True
      # required_zones:
      #     - front_yard
    record:
      enabled: True
      events:
        objects:
          - person
          - dog
          - cat
          - bird
        # required_zones:
        #   - front_yard
    detect:
      width: 640
      height: 360
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 720
      quality: 100
      # required_zones:
      #   - front_yard



  north_pass:
    ffmpeg:
      inputs:
        - path: rtmp://ip/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - detect
            # - rtmp
        - path: rtmp://ip/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - record
            - rtmp
            # - detect
    motion:
      mask:
        - 301,162,0,275,0,54,204,98,276,119,389,130,382,166
    # zones:
    #   front_yard:
    #     coordinates: 0,360,640,360,640,190,640,144,561,165,517,205,455,196,386,173,311,157,246,155,179,163,112,172,34,185,0,194,0,224,0,283
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    snapshots:
      enabled: True
      bounding_box: True
      # required_zones:
      #     - front_yard
    record:
      enabled: True
      events:
        objects:
          - person
          - dog
          - cat
          - bird
        # required_zones:
        #   - front_yard
    detect:
      width: 640
      height: 480
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 720
      quality: 100
      # required_zones:
      #   - front_yard




  garage_corner:
    ffmpeg:
      inputs:
        - path: rtmp://ip/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=pass
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@ip:554//h265Preview_01_main
          roles:
            - record
            # - detect
    motion:
      mask:
        - 542,128,0,0,0,144,0,272,396,177,446,183,536,165
    zones:
      front_yard:
        coordinates: 640,360,640,166,547,168,423,191,0,326,0,360
      walkway:
        coordinates: 0,267,407,174,441,187,329,223,0,332
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bird
        - cow
        - sheep
        - bus
        - motorcycle
        - bicycle
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
          - front_yard
          - walkway
    record:
      enabled: True
      events:
        objects:
          - person
          - car
          - dog
          - cat
          - bird
          - cow
          - sheep
          - bus
          - motorcycle
          - bicycle
        required_zones:
          - front_yard
          - walkway
    detect:
      width: 640
      height: 360
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 720
      quality: 100
      # required_zones:
      #   - front_yard
```

### Relevant log output

```shell
There are no logs that I can find that would be helpful
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://user:pass@ip:554//h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: -0.013900, bitrate: N/A
    Stream #0:0: Video: hevc, yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp


ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://user:pass@ip:554//h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 2560x1920, 30 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"back_yard_south":{"camera_fps":5.0,"capture_pid":363,"detection_fps":0.0,"pid":354,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":69.02,"pid":335},"cpu2":{"detection_start":0.0,"inference_speed":69.63,"pid":336},"cpu3":{"detection_start":0.0,"inference_speed":66.92,"pid":338},"cpu4":{"detection_start":0.0,"inference_speed":68.16,"pid":341},"cpu5":{"detection_start":0.0,"inference_speed":68.97,"pid":343},"cpu6":{"detection_start":0.0,"inference_speed":68.86,"pid":344}},"garage_corner":{"camera_fps":5.0,"capture_pid":377,"detection_fps":0.0,"pid":356,"process_fps":5.0,"skipped_fps":0.0},"main_door":{"camera_fps":5.0,"capture_pid":357,"detection_fps":0.0,"pid":350,"process_fps":5.0,"skipped_fps":0.0},"north_pass":{"camera_fps":5.1,"capture_pid":366,"detection_fps":0.0,"pid":355,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":5364.3,"mount_type":"tmpfs","total":5368.7,"used":4.4},"/media/frigate/clips":{"free":3448414.0,"mount_type":"zfs","total":4398046.4,"used":949632.4},"/media/frigate/recordings":{"free":3448414.0,"mount_type":"zfs","total":4398046.4,"used":949632.4},"/tmp/cache":{"free":5119580.7,"mount_type":"zfs","total":5119724.9,"used":144.2}},"uptime":4599,"version":"0.9.2-25bb515"},"south_pass":{"camera_fps":5.1,"capture_pid":360,"detection_fps":0.0,"pid":352,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC 810A(h265) and Reolink RLC 510(h264)
