### ISSUE TITLE
[Support]: Frigate container exits shortly after launching with simple configuration

### ISSUE THREAD

**Issue by peterhajas** [blakeblackshear/frigate#2066]
### Describe the problem you are having

Trying to get Frigate working on my Manjaro box running `podman`. My docker-compose file is pretty tame:

```
version: '3'
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64nvidia
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/phajas/services/frigate/storage:/media/frigate
      - /home/phajas/services/frigate/config.yml:/config/config.yml:ro
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

and resembles the one in the [documentation](https://docs.frigate.video/guides/getting_started).

Unfortunately, frigate containers exit shortly after running them with:

```
frigate    | [Errno -2] Name or service not known
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 1
```

### Version

0.9.2-25bb515

### Frigate config file

```yaml
mqtt:
  host: http://192.168.1.250

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.30.200:8554/unicast
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360

logger:
  default: debug
```

### Relevant log output

```shell
$ sudo podman container stop frigate && sudo podman container rm frigate && sudo docker-compose up
frigate
57089bbc253bcbfe25b851bdf1f497cb37ea033b5c3f1b45298bce932ad2c284
Creating frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2021-10-20 19:32:32] frigate.app                    INFO    : Starting Frigate (0.9.2-25bb515)
frigate    | [2021-10-20 19:32:32] frigate.app                    INFO    : Creating directory: /tmp/cache
frigate    | Starting migrations
frigate    | [2021-10-20 19:32:32] peewee_migrate                 INFO    : Starting migrations
frigate    | [2021-10-20 19:32:32] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate    | [2021-10-20 19:32:32] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate    | There is nothing to migrate
frigate    | [2021-10-20 19:32:32] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [Errno -2] Name or service not known
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 1
```

### FFprobe output from your camera

```shell
ffprobe version n4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://192.168.30.200:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 0.116000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x360, 25 fps, 25 tbr, 90k tbn, 50 tbc
```

### Frigate stats

```json
Can't start Frigate :-/
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Xiaomi Dafang with custom firmware

### Any other information that may be helpful

I'm curious if there are more logs I can enable to understand the issue better. I thought setting `logger` to `debug` would show me more, but I'm not exactly sure _what_ is failing. The most relevant line seems to be:

```
frigate    | [Errno -2] Name or service not known
```

I'd love to know what name or service isn't known, or what part of Frigate is falling over. Please let me know if there are any more logs I can collect.
