### ISSUE TITLE
[Support]: Frigate video not always being recorded

### ISSUE THREAD

**Issue by HSB-collab** [blakeblackshear/frigate#2076]
### Describe the problem you are having

I have a problem in that sometimes my events are not being recorded, even though I get a snapshot for the event.

When an event occurs, I get a snapshot and the Frigate events menu thinks there is a video recording but when I try and play it I get a messasge saying "The media could not be loaded, either because the server or network failed or because the format is not supported.". There is also no recording in the Frigate media folder.

I am running Supervised HA in a Virtualbox VM on an Ubuntu 20.04 host. 
I have Frigate version 0.9.1-800F33E running in a separate docker container. 
I have 10 cameras in my setup but to make it simpler I show below the config.yml file for just 1 camera. 

Any idea why this is happening?
Also, how do I get access to the Frigate log file from the docker container?

Sorry about the questions, as I am guessing I am doing something dumb but what?????

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.251
  user: mqtt_user
  password: *****
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  global_args: -hide_banner -loglevel debug    
cameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://****:*****@10.0.0.120/img/video.sav
          roles:
            - detect
            - rtmp
            - record
    detect:    
      width: 1280
      height: 720
      fps: 5  
    objects:
      track:
        - person
        - car
      filters:
        person:
           min_score: 0.6
          threshold: 0.66
    record:
      enabled: true
      retain_days: 0
      events:
        max_seconds: 60
        retain:
          default: 10
    snapshots:
      enabled: true

 detectors:
  coral:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
Sorry don't know how to get this.
```

### FFprobe output from your camera

```shell
ffprobe http://10.0.0.***ff
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
http://10.0.0.120: Invalid data found when processing input
```

### Frigate stats

```json
{"Camera1":{"camera_fps":5.0,"capture_pid":253,"detection_fps":0.0,"pid":222,"process_fps":5.0,"skipped_fps":0.0},"Camera10":{"camera_fps":5.0,"capture_pid":306,"detection_fps":0.0,"pid":251,"process_fps":5.0,"skipped_fps":0.0},"Camera2":{"camera_fps":5.0,"capture_pid":256,"detection_fps":13.4,"pid":223,"process_fps":5.0,"skipped_fps":0.0},"Camera3":{"camera_fps":5.0,"capture_pid":259,"detection_fps":0.0,"pid":226,"process_fps":0.0,"skipped_fps":0.0},"Camera4":{"camera_fps":5.1,"capture_pid":262,"detection_fps":0.0,"pid":228,"process_fps":0.0,"skipped_fps":0.0},"Camera5_Wyze_pan":{"camera_fps":5.1,"capture_pid":266,"detection_fps":0.0,"pid":241,"process_fps":0.0,"skipped_fps":0.0},"Camera6_Wyze_1":{"camera_fps":5.1,"capture_pid":273,"detection_fps":0.0,"pid":243,"process_fps":0.0,"skipped_fps":0.0},"Camera7_Wyze_2":{"camera_fps":5.0,"capture_pid":276,"detection_fps":0.0,"pid":245,"process_fps":0.0,"skipped_fps":0.0},"Camera8_Wyze_pan2":{"camera_fps":5.0,"capture_pid":281,"detection_fps":0.0,"pid":247,"process_fps":0.0,"skipped_fps":0.0},"Camera9":{"camera_fps":5.0,"capture_pid":304,"detection_fps":2.9,"pid":249,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":16.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.34,"pid":216}},"service":{"storage":{"/dev/shm":{"free":1047.2,"mount_type":"tmpfs","total":1073.7,"used":26.6},"/media/frigate/clips":{"free":67292.2,"mount_type":"ext4","total":117299.1,"used":44004.3},"/media/frigate/recordings":{"free":67292.2,"mount_type":"ext4","total":117299.1,"used":44004.3},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"uptime":140211,"version":"0.9.1-800f33e"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Sercomm iCamera2 and Wyze Camera v2
