### ISSUE TITLE
Ability to record sub stream along with main stream

### ISSUE THREAD

**Issue by darkalfx** [blakeblackshear/frigate#2082]
**Describe what you are trying to accomplish and why in non technical terms**

I have cameras with very high resolutions, I want to be able to do continuous recording of the lower resolution input stream but whenever a detection occurs, I want the associated clips to be taken from the high resolution input stream, not from the lower resolution input stream.

**Describe the solution you'd like**

A new camera role called something like "Clips" would allow users to choose which input stream to use for generating clips instead of assuming that this should come from the continous recording role.

**Describe alternatives you've considered**

I could duplicate the camera in Frigate to achieve this, however this would also mean running detection twice for the same stream which is highly undesirable.

I could also do continuous recording of the high resolution input stream but that would take very large amounts of disk space, not ideal.

**Comment by finnaGIT** [comment]
Below is a proposed config to implement continuous recording of sub-stream and recording only `active_objects` in the main stream. Of course while I see this as easy to configure from the user's side, I have no idea if this would work behind the scenes. Just for consideration:

```
go2rtc:
  streams:
    camera_one_main: rtsp://192.168.0.2:1234 # camera one main stream
    camera_one_sub: rtsp://192.168.0.2:5678 # camera one sub stream

cameras:
  camera_one:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/camera_one_main
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/camera_one_sub
          roles:
            - detect
            - record
            - audio
    record:
      enabled: true
      retain:
        mode: all
        days: -1 # '-1' to record continuously, or until storage is consumed & delete oldest 2 hours with 1 hr remaining, or state a number of days as is currently implemented
        stream: camera_one_sub
      alerts:
        mode: active_objects
        days: -1
        stream: camera_one_main
```

**Comment by partytimeexcellent** [comment]
My issue is the ability to stream high-res from my house with only 11Mb/s upload speed, which can buffer clips for 20-30 seconds before playback. Basically as it sits now, I can't use my 4k cameras to their full potential.

My idea for this implementation would be the ability to have a high-res recording accessible on the LAN, and a secondary low-res recording for remote viewing. Possibly some logic to detect if I'm on the LAN or remote when presenting the stream.

A secondary option would be on-the-fly transcoding from high-res to low-res when remote viewing, possibly with logic to detect when streaming is too slow. Seems like this is how some other NVR software handles it.

**Comment by mdv0** [comment]
Has anyone figured out a way to always record the sub stream and use the main stream only for events? Or do the devs have any plans to implement this?

**Comment by NickM-27** [comment]
Yes, that's why it's pinned

**Comment by stefa168** [comment]
I've been trying Frigate for some time now, alongside my main Blue Iris instance. This is the main feature I'm missing in Frigate.

In my opinion, it would be preferable to have to tag the two input streams as "main" and "sub" and then just having Frigate use them as such

**Comment by dominikgrygiel** [comment]
> Has anyone figured out a way to always record the sub stream and use the main stream only for events? Or do the devs have any plans to implement this?

I was able to achieve it by duplicating the camera:

```yaml
cameras:
  camera_one_continuous:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://secondary_stream_url
          roles:
            - record
    detect:
      enabled: false
    record:
      enabled: true
      retain:
        days: 7
        mode: all
  camera_one:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://main_stream_url
          roles:
            - record
        - path: 
            rtsp://secondary_stream_url
          roles:
            - detect
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: motion
```

**Comment by kabaga** [comment]
> > Has anyone figured out a way to always record the sub stream and use the main stream only for events? Or do the devs have any plans to implement this?
> 
> I was able to achieve it by duplicating the camera:
> 
> cameras:
>   camera_one_continuous:
>     enabled: true
>     ffmpeg:
>       inputs:
>         - path: 
>             rtsp://secondary_stream_url
>           roles:
>             - record
>     detect:
>       enabled: false
>     record:
>       enabled: true
>       retain:
>         days: 7
>         mode: all
>   camera_one:
>     enabled: true
>     ffmpeg:
>       inputs:
>         - path: 
>             rtsp://main_stream_url
>           roles:
>             - record
>         - path: 
>             rtsp://secondary_stream_url
>           roles:
>             - detect
>     detect:
>       enabled: true
>     record:
>       enabled: true
>       retain:
>         days: 30
>         mode: motion

I tried to replicate this on version 0.16 and it appears that the main stream is still continuing to record even though it is set to motion. When I go to the Live / History, and scrub the timeline, i am able to play the video on the main stream. The only difference I could tell between the continues sub stream and continues (supposed to be just motion) main stream, the main stream has a lot of motion yellow horizontal lines in its timeline.
Here is my settings:
```
cameras:
  livingroom_sub_continues:
    enabled: true
    ui:
      dashboard: false
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/livingroom_sub
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    record:
      enabled: true
      retain:
        days: 2
        mode: all
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.4
          threshold: 0.7
          min_area: 700
    motion:
      mask: 0.493,0.019,0.594,0.017,0.594,0.05,0.494,0.05  
  livingroom:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/livingroom
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://localhost:8554/livingroom_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 2
        mode: motion
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.4
          threshold: 0.7
          min_area: 700
```
