### ISSUE TITLE
[Support]: Need some help replacing shinobi with frigate

### ISSUE THREAD

**Issue by ovizii** [blakeblackshear/frigate#2122]
### Describe the problem you are having

Hi there,

I have one Reolink E1 zoom which streams to shinobi. Shinobi does nothing. HA is listening on shinobi stream and starts recording via shinobi API once a certain noise level is reached. 

I don't need constant recording or any event triggered recording as I just use this to record when my dog barks so the neighbor can't claim my dog was barking "the whole day" :-) 

**Could I replace shinobi with frigate?**

HA is listening on a stream from shinobi and triggers at a certain noise level. How would the frigate stream URL look like if I were to replace this shinobi link?

```
# Bark detector
# https://www.home-assistant.io/integrations/ffmpeg_noise/
binary_sensor:
  - platform: ffmpeg_noise
    name: Bark Detector
    input: http://10.10.10.10:8088/API_KEY/hls/secret/doggyCam/s.m3u8
    # The threshold of detecting noise, in dB. 0 is very loud and -100 is low.
    # do not start with HA aka always active
    # reset after 30 seconds of less than peak noise
    # trigger with 3 seconds of noise
    initial_state: false
    peak: -45
    reset: 60
    duration: 3

```

Once noise is detected, HA triggers a recording inside shinobi. Any example on how to trigger this via frigate API?

```
#trying to create a service to call shinobi API and trigger recordings
notify:
  - name: trigger_recording
    platform: rest
    resource: "http://10.10.10.10:8088/API_KEY/motion/secret/doggyCam?data={%22plug%22:%22doggycam%22,%22name%22:%22bedroom%22,%22reason%22:%22noise%22,%22confidence%22:100}"
```

### Version

latest

### Frigate config file

```yaml
doesn't really matter until my question is answered :-)
```

### Relevant log output

```shell
nothign yet
```

### FFprobe output from your camera

```shell
sorry not yet
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Reolink E1 zoom

### Any other information that may be helpful

I just wanted to add that I got frigate up and running via docker-compose and it works fine. I am just not sure if it can do what I need to do (see description with my 2 questions further up)
