### ISSUE TITLE
[Support]: Overlapping events instead of combined?

### ISSUE THREAD

**Issue by leadZERO** [blakeblackshear/frigate#2124]
### Describe the problem you are having

Given that I have `max_seconds: 300`, I would have thought these overlapping events would be the same (there's only 1 person in the picture). Is there anything I can adjust to try and get these to combine into a single event (or maybe 2 since it does exceed the 300 seconds)?

![image](https://user-images.githubusercontent.com/1274368/138923175-1170f91f-b38c-4e32-817b-bcee997f9468.png)

### Version

0.9.3-5E692AC

### Frigate config file

```yaml
mqtt:
  host: ds.outhaving.fun
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

ffmpeg:
  hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128" ]

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: info
  logs:
    frigate.event: debug

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"
  thickness: 3
  effect: "shadow"

record:
  enabled: True
  retain_days: 2
  events:
    max_seconds: 300
    retain:
      default: 3
    required_zones:
      - yard
      - front_deck
      - driveway
      - lake_deck
      - side_deck

detect:
  width: 3840
  height: 2160
  fps: 5

snapshots:
  enabled: True
  timestamp: true
  bounding_box: true
  required_zones:
    - yard
    - front_deck
    - driveway
    - lake_deck
    - side_deck
  retain:
    default: 10

objects:
  track: ["person", "animal"]

cameras:

  ############################
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_ARTSP_PASSWORD}@192.168.1.149:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles: ["detect", "rtmp", "record"]
    zones:
      front_deck:
        coordinates: 2560,589,2560,1920,0,1920,0,1071,647,894,1314,866,1645,840
      yard:
        coordinates: 1047,987,1032,792,863,744,314,630,286,744,0,695,41,1045,671,878
    motion:
      mask: 
        - 995,0,972,411,1279,760,1558,799,2560,468,2560,0
    detect:
      width: 2560
      height: 1920

  ############################
  front:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    motion:
      mask:
        - 3840,0,538,0,719,293,1397,240,2284,181,2836,156,3840,212
    zones:
      yard:
        coordinates: 3840,544,3840,1570,2432,1559,887,968,1768,770,1174,588,945,625,959,474,1740,382,2474,382
      front_deck:
        coordinates: 2708,1573,2443,1603,772,934,1445,795,1442,692,1082,572,1007,488,904,340,0,482,0,2160,3840,2160,3840,1592

  ############################
  driveway_side:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.148:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    zones:
      yard:
        coordinates: 0,2160,3840,2160,3840,731,3301,676,2105,536,1830,507,1091,461,0,563
      driveway:
        coordinates: 1744,873,2702,812,2565,587,2029,525,1711,523
        objects: ["person", "animal", "vehicle"]

  ############################
  crawlspace_yard:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.156:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    zones:
      yard:
        coordinates: 3062,730,0,466,0,2160,3840,2160,3840,955

  ############################
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.157:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    zones:
      yard:
        coordinates: 0,2160,3840,2160,3840,1776,3183,1249,2702,921,1970,710,0,701

  ############################
  weather_station:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.142:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    detect:
      width: 1920
      height: 1080
    objects:
      track: []
    record:
      retain_days: 1
      events:
        objects: []

  ############################
  back:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.155:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    zones:
      lake_deck:
        coordinates: 3840,2160,3840,190,3628,176,2638,0,1933,0,1617,0,1433,159,1389,251,1283,349,1269,510,1336,508,279,1255,226,2160
      yard:
        coordinates: 310,1269,884,803,1269,558,1280,332,1428,276,1411,201,1143,248,775,533,340,666,0,959,0,2160,418,2160
    motion:
      mask:
        - 2028,722,1714,719,1798,0,1946,0

  ############################
  lake:
    ffmpeg:
      inputs:
        - path: rtsp://cameras:{FRIGATE_RTSP_PASSWORD}@192.168.1.144:554/cam/realmonitor?channel=1&subtype=0
          roles: ["detect", "rtmp", "record"]
    zones:
      lake_deck:
        coordinates: 1620,1489,1849,1255,2315,1503,2276,2047,2064,2160,220,2160,0,2160,0,708,1104,521,1280,627,1255,878,1500,909
      yard:
        coordinates: 2256,1913,1693,1712,1514,1054,1274,996,1258,772,1570,759,2002,929,3804,1679,3840,2160,2122,2160

  ############################
  side_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_ARTSP_PASSWORD}@192.168.1.150:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles: ["detect", "rtmp", "record"]
    zones:
      side_deck:
        coordinates: 2560,0,2097,0,2017,232,2168,431,2270,851,2106,864,2041,967,1753,976,1469,1019,43,1128,0,1920,2560,1920
      yard:
        coordinates: 2010,976,2101,794,1774,746,1292,777,892,825,535,913,130,1123,1021,1075
    motion:
      mask:
        - 1112,1032,1123,1311,922,1309,898,1047,887,491,1019,292,1119,483
    detect:
      width: 2560
      height: 1920
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://XXXX:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.700000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 3840x2160, 10 fps, 10 tbr, 90k tbn, 20 tbc
```

### Frigate stats

```json
{"back":{"camera_fps":5.0,"capture_pid":312,"detection_fps":0.0,"pid":265,"process_fps":5.0,"skipped_fps":0.0},"backyard":{"camera_fps":5.0,"capture_pid":301,"detection_fps":0.0,"pid":257,"process_fps":5.0,"skipped_fps":0.0},"crawlspace_yard":{"camera_fps":5.0,"capture_pid":299,"detection_fps":0.0,"pid":251,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.39,"pid":11101}},"driveway_side":{"camera_fps":5.1,"capture_pid":293,"detection_fps":0.0,"pid":238,"process_fps":5.1,"skipped_fps":0.0},"front":{"camera_fps":5.0,"capture_pid":288,"detection_fps":0.0,"pid":236,"process_fps":5.0,"skipped_fps":0.0},"front_door":{"camera_fps":5.1,"capture_pid":285,"detection_fps":0.0,"pid":229,"process_fps":5.1,"skipped_fps":0.0},"lake":{"camera_fps":5.0,"capture_pid":318,"detection_fps":0.0,"pid":272,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":595.2,"mount_type":"tmpfs","total":786.4,"used":191.2},"/media/frigate/clips":{"free":1077266.2,"mount_type":"ext4","total":1967924.6,"used":790621.9},"/media/frigate/recordings":{"free":1077266.2,"mount_type":"ext4","total":1967924.6,"used":790621.9},"/tmp/cache":{"free":4955.9,"mount_type":"tmpfs","total":5000.0,"used":44.1}},"uptime":11120,"version":"0.9.3-5e692ac"},"side_door":{"camera_fps":5.1,"capture_pid":322,"detection_fps":0.0,"pid":278,"process_fps":5.1,"skipped_fps":0.0},"weather_station":{"camera_fps":5.0,"capture_pid":307,"detection_fps":0.0,"pid":264,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua
