### ISSUE TITLE
[Support]: HA sensors gone unavailable

### ISSUE THREAD

**Issue by jonandel** [blakeblackshear/frigate#2134]
### Describe the problem you are having

Restart of Home Assistant following 0.94 update over last day or so, and now all the camera sensors and binary sensors are unavailable.

Last time this happened (about 0.93), I added the username and password for MQtt in the Frigate.yml - where before there was only the server IP.  Nothing else has changed on HA install - except Frigate...

Now, adding or removing the credentials makes no difference, and the Frigate sensors in Home Assistant are all unavailable - cameras through to detect binary sensors.  Feels like an MQTT problem... ?

No log entries about Mqtt appear either way....

Am I being dumb ?

### Version

0.94

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.210
# Try removing these this time, or reinstating
#  user: hassio
#  password: hassiopassword
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

N/A

### Any other information that may be helpful

N/A
