### ISSUE TITLE
[Support]: filtering objects in zones; shared zones

### ISSUE THREAD

**Issue by ArturZurawski** [blakeblackshear/frigate#2135]
### Describe the problem you are having

I'm struggling with setting up two things:

- Adding multiple cameras which shares zones with current `front_garage` with common objects. Let's say additional cameras will have common zones `front`, `garage_driveway` and `sidewalk`. I want to define objects that should be recorded when entering zone no matter on which camera (**within defined zone**) they will be recognized. So for instance `person` should trigger recording on zones `front`, `garage_driveway` but not on `sidewalk` no matter on which camera. Is it possible? 

- Current setup (config attached) seems to ignore object restrictions. I'm having `person`s on `street` triggering events even I specified `objects: []` for `street`. Cars seems not be detected at all and I have only `person` in `Tracked objects` while entering `front_garage` camera on webUI. What I'm doing wrong?

### Version

0.9.4

### Frigate config file

```yaml
config: |
  mqtt:
    host: mosquitto.mosquitto.svc.cluster.local
    topic_prefix: frigate
  detectors:
    cpu1:
      type: cpu
      num_threads: 2
  ffmpeg:
    hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
  cameras:

    front_garage:
      zones:
        front:
          coordinates: 203,0,209,0,0,0,0,176,432,240
          objects:
            - car
            - bus
            - person
        garage_driveway:
          coordinates: 545,360,0,360,0,179,433,240
          objects:
            - car
            - bus
            - person
        sidewalk:
          coordinates: 448,200,233,21,225,29,549,360,640,360,600,360
          objects:
            - car
            - bus
        street:
          coordinates: 640,325,558,241,420,125,263,0,235,0,640,360
          objects: []
        front_parking1:
          coordinates: 456,199,449,218,293,71,303,70
          objects:
            - car
            - bus
            - person
        front_parking2:
          coordinates: 485,227,583,330,586,360,462,233
          objects:
            - car
            - bus
            - person
      ffmpeg:
        inputs:
          - path: rtsp://ADMIN:1234@192.168.51.100:554/snl/live/1/1
            roles:
              - record
              - rtmp
          - path: rtsp://ADMIN:1234@192.168.51.100:554/snl/live/1/2
            roles:
              - detect

  record:
    enabled: true
    retain_days: 30
    events:
      retain:
        default: 45

  detect:
    enabled: true
    width: 640
    height: 360
    fps: 5

  objects:
    filters:
      person:
        min_score: 0.4
        threshold: 0.5
      car:
        min_score: 0.3
        threshold: 0.4

  snapshots:
    enabled: true
    timestamp: true
    bounding_box: true
    retain:
      default: 30
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

-

**Comment by blakeblackshear** [comment]
Defining zones alone won't prevent snapshots or recordings. You have to add them to required_zones for one or both.

**Comment by ArturZurawski** [comment]
thank you, that worked.

**Comment by MrSiO** [comment]
@ArturZurawski  Hi.
Could you please send your final fixed config?
Can't quite get mine to work. 
Thx !

**Comment by ArturZurawski** [comment]
eventually I ended up with something like this:

```
config: |
  cameras:

    front_garage:
      zones:
        front:
          coordinates: 203,0,209,0,0,0,0,176,432,240
          objects:
            - car
            - bus
            - person
        garage_driveway:
          coordinates: 545,360,0,360,0,179,433,240
          objects:
            - car
            - bus
            - person
        sidewalk:
          coordinates: 448,200,233,21,225,29,549,360,640,360,600,360
          objects:
            - car
            - bus
        street:
          coordinates: 640,325,558,241,420,125,263,0,235,0,640,360
          objects:
            - cat
        front_parking1:
          coordinates: 456,199,449,218,293,71,303,70
          objects:
            - car
            - bus
            - person
        front_parking2:
          coordinates: 485,227,583,330,586,360,462,233
          objects:
            - car
            - bus
            - person
      ffmpeg:
        inputs:
          - path: rtsp://ADMIN:1234@192.168.51.100:554/snl/live/1/1
            roles:
              - record
              - rtmp
          - path: rtsp://ADMIN:1234@192.168.51.100:554/snl/live/1/2
            roles:
              - detect

  record:
    enabled: true
    retain_days: 15
    events:
      required_zones:
        - front
        - garage_driveway
        - sidewalk
        - front_parking1
        - front_parking2
        - street
      retain:
        default: 30

  snapshots:
    enabled: true
    required_zones:
      - front
      - garage_driveway
      - sidewalk
      - front_parking1
      - front_parking2
      - street
    timestamp: true
    bounding_box: true
    retain:
      default: 30

  detect:
    enabled: true
    width: 640
    height: 360
    fps: 5

  objects:
    track:
      - car
      - person
    filters:
      person:
        min_score: 0.5
        threshold: 0.6
      car:
        min_score: 0.5
        threshold: 0.6

  motion:
    delta_alpha: 0.2
    frame_alpha: 0.3
    contour_area: 0

  mqtt:
    host: mosquitto.mosquitto.svc.cluster.local
    topic_prefix: frigate

  detectors:
    cpu1:
      type: cpu
      num_threads: 2

  ffmpeg:
    hwaccel_args:
      - -hwaccel
      - vaapi
      - -hwaccel_device
      - /dev/dri/renderD128
      - -hwaccel_output_format
      - yuv420p
```
