### ISSUE TITLE
Getting a "bad file" error on camera startup

### ISSUE THREAD

**Issue by blysik** [blakeblackshear/frigate#214]
New user attempting to setup Frigate for the first time, with one LTS/Hikvision camera.  I'm successfully using this camera with both Synology Surveillance Station, as well as the various HA integrations.

**Version of frigate**
Latest stable

**Config file**

```
web_port: 5000
mqtt:
  host: xxx.xxx.xxx.xxx
  topic_prefix: frigate
 
save_clips:
  max_seconds: 300

objects:
  track:
    - person
    - car
    - truck
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.85

cameras:
  backyard:
    ffmpeg:
      
      input: rtsp://USER:PASS@xxx.xxx.xxx.xxx:554/Streaming/Channels/1
  
    take_frame: 1
 
    best_image_timeout: 60

    save_clips:
      enabled: True
  
      pre_capture: 30

      objects:
        - person

    snapshots:
      show_timestamp: True
      draw_zones: False
  
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
```

**Logs**
```
Attaching to frigate
frigate    | On connect called
frigate    | ffprobe -v panic -show_error -show_streams -of json "rtsp://USER:PASS@xxx.xxx.xxx.xxx:554/Streaming/Channels/1"
frigate    | Starting detection process: 22
frigate    | Attempting to load TPU as usb
frigate    | TPU found
frigate    | {'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10', 'profile': 'Main', 'codec_type': 'video', 'codec_time_base': '1/20', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 2688, 'height': 1520, 'coded_width': 2688, 'coded_height': 1520, 'has_b_frames': 0, 'sample_aspect_ratio': '0:1', 'display_aspect_ratio': '0:1', 'pix_fmt': 'yuvj420p', 'level': 50, 'color_range': 'pc', 'color_space': 'bt709', 'color_transfer': 'bt709', 'color_primaries': 'bt709', 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'false', 'nal_length_size': '0', 'r_frame_rate': '10/1', 'avg_frame_rate': '10/1', 'time_base': '1/90000', 'start_pts': 54000, 'start_time': '0.600000', 'bits_per_raw_sample': '8', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}]}
frigate    | Creating ffmpeg process...
frigate    | ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://USER:PASS@xxx.xxx.xxx.xxx:554/Streaming/Channels/1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -map 0 /cache/backyard-%Y%m%d%H%M%S.mp4 -f rawvideo -pix_fmt rgb24 pipe:
frigate    | Camera_process started for backyard: 35
frigate    | Starting process for backyard: 35
frigate    |  * Serving Flask app "detect_objects" (lazy loading)
frigate    |  * Environment: production
frigate    |    WARNING: This is a development server. Do not use it in a production deployment.
frigate    |    Use a production WSGI server instead.
frigate    |  * Debug mode: off
frigate    | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c40e700be0] moov atom not found
frigate    | /cache/backyard-20200924135016.mp4: Invalid data found when processing input
frigate    | bad file: backyard-20200924135016.mp4```
```

**Frigate debug stats**
```
% curl xxx.xxx.xxx.xxx:5000/debug/stats
{"backyard":{"camera_fps":20.0,"detection_fps":85.3,"ffmpeg_pid":94,"frame_info":{"detect":1600981535.159932,"process":0.0,"read":1600981535.750341},"pid":35,"process_fps":20.4,"read_start":0.0,"skipped_fps":0.4},"coral":{"detection_start":1600981535.754274,"fps":85.3,"inference_speed":7.72,"pid":22},"plasma_store_rc":null}
```

**FFprobe from your camera**

Run the following command and paste output below
```
[root@supernuc _data]# ffprobe rtsp://USER:PASS@xxx.xxx.xxx.xxx:554/Streaming/Channels/1
ffprobe version 3.4.8 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --disable-encoder=libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, rtsp, from 'rtsp://USER:PASS@xxx.xxx.xxx.xxx:554/Streaming/Channels/1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.650000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520, 20 fps, 10 tbr, 90k tbn, 40 tbc
```

**Computer Hardware**
 - OS: Centos 7
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: LTS aka Hikvision clone
 - Model: CMIP7442W-28M
 - Resolution: 2688x1520
 - FPS: 10
