### ISSUE TITLE
[Support]: How to get 24x7 low-res recording and 4k clips?

### ISSUE THREAD

**Issue by mzman88** [blakeblackshear/frigate#2144]
### Describe the problem you are having

I'm currently running v0.8.4 and have 640x480 recording 24x7 on 4 4k cameras. When a detector triggers it writes out the 4k clip. This works beautifully and allows me to store 30 days' worth of 24x7 and detection clips. I do not want to have clips and recording feed to be combined.

In reading the documentation for v0.9.1 I do not see a way that is possible after the rewrite. Is there a way to accomplish what I need in v.0.9.1+?

Thanks!

### Version

0.8.4-5043040

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.154
  port: 8883 
  user: mqtt
  password: {FRIGATE_MQTT_PASSWORD}
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.201:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
      output_args:
        # Optional: output args for record streams (default: shown below)
        record: -f segment -segment_time 900 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        # Optional: output args for clip streams (default: shown below)
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 640 #3840
    height: 480 #2160
    fps: 5
    
    motion:
      mask:
        - 629,436,626,467,498,464,500,432
        #4k- 3805,2121,3799,2037,3474,2037,3506,2121

    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: False
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []

    # Optional: Camera level object filters config.
    objects:
      track:
        - person
       # - car
       # - truck

    record:
    #Optional: Enable recording
      enabled: True
    #Optional: Number of days to retain
      retain_days: 30
    
    clips:
    # Required: enables clips for the camera (default: shown below)
    # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
    # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
    # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
    # Optional: Objects to save clips for. (default: all tracked objects)
     # objects:
     #   - person
     #   - car
     #   - truck
    # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
    # Optional: Camera override for retention settings (default: global values)
      retain:
    # Required: Default retention days (default: shown below)
        default: 30
    # Optional: Per object retention days
        objects:
          person: 30

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 30
        # Optional: Per object retention days
        objects:
          person: 30

  
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.203:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.203:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
      output_args:
        # Optional: output args for record streams (default: shown below)
        record: -f segment -segment_time 900 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        # Optional: output args for clip streams (default: shown below)
        clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    width: 640 #3840
    height: 480 #2160
    fps: 5
    
    motion:
      mask:
        - 640,480,464,480,543,240,518,0,640,0
        #4k- 2801,2160,3840,2160,3840,0,3393,0,3281,1098


    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: False
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []

    # Optional: Camera level object filters config.
    objects:
      track:
        - person
       # - car
       # - truck

    record:
    #Optional: Enable recording
      enabled: True
    #Optional: Number of days to retain
      retain_days: 30
    
    clips:
    # Required: enables clips for the camera (default: shown below)
    # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
    # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
    # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
    # Optional: Objects to save clips for. (default: all tracked objects)
     # objects:
     #   - person
     #   - car
     #   - truck
    # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
    # Optional: Camera override for retention settings (default: global values)
      retain:
    # Required: Default retention days (default: shown below)
        default: 30
    # Optional: Per object retention days
        objects:
          person: 30

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 30
        # Optional: Per object retention days
        objects:
          person: 30


  front_door:
      ffmpeg:
        inputs:
          - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.202:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - detect
              - record
          - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.202:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - clips
        output_args:
          # Optional: output args for record streams (default: shown below)
          record: -f segment -segment_time 900 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
          # Optional: output args for clip streams (default: shown below)
          clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      width: 640
      height: 480
      fps: 5
      
      motion:
        mask:
           - 0,229,0,0,640,0,640,0,640,227
           #- 0,439,126,361,60,66,0,56
  
      # Optional: RTMP re-stream configuration
      rtmp:
        # Required: Enable the live stream (default: True)
        enabled: False
  
      # Optional: Configuration for the jpg snapshots published via MQTT
      mqtt:
        # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
        # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
        # All other messages will still be published.
        enabled: False
        # Optional: print a timestamp on the snapshots (default: shown below)
        timestamp: True
        # Optional: draw bounding box on the snapshots (default: shown below)
        bounding_box: True
        # Optional: crop the snapshot (default: shown below)
        crop: True
        # Optional: height to resize the snapshot to (default: shown below)
        height: 270
        # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
        #required_zones: []
  
      # Optional: Camera level object filters config.
      objects:
        track:
          - person
          #- car
          #- truck
  
      record:
      #Optional: Enable recording
        enabled: True
      #Optional: Number of days to retain
        retain_days: 30
      
      clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
        enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
        pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
       # objects:
       #   - person
       #   - car
       #   - truck
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
      # Optional: Camera override for retention settings (default: global values)
        retain:
      # Required: Default retention days (default: shown below)
          default: 30
      # Optional: Per object retention days
          objects:
            person: 30
  
      # Optional: Configuration for the jpg snapshots written to the clips directory for each event
      snapshots:
        # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
        # This value can be set via MQTT and will be updated in startup based on retained value
        enabled: True
        # Optional: print a timestamp on the snapshots (default: shown below)
        timestamp: False
        # Optional: draw bounding box on the snapshots (default: shown below)
        bounding_box: True
        # Optional: crop the snapshot (default: shown below)
        crop: False
        # Optional: height to resize the snapshot to (default: original size)
        height: 175
        # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
        #required_zones: []
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 30
          # Optional: Per object retention days
          objects:
            person: 30

  garage:
      ffmpeg:
        inputs:
          - path: rtsp://192.168.1.200/ch0_1.h264
            roles:
              - detect
              #- record
          - path: rtsp://192.168.1.200/ch0_0.h264
            roles:
              - clips
        output_args:
          # Optional: output args for record streams (default: shown below)
          #record: -f segment -segment_time 900 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
          # Optional: output args for clip streams (default: shown below)
          clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      width: 640
      height: 360
      fps: 5
      
      motion:
        mask:
          - 87,0,177,0,180,34,72,38
         
      # Optional: RTMP re-stream configuration
      rtmp:
        # Required: Enable the live stream (default: True)
        enabled: False
  
      # Optional: Configuration for the jpg snapshots published via MQTT
      mqtt:
        # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
        # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
        # All other messages will still be published.
        enabled: False
        # Optional: print a timestamp on the snapshots (default: shown below)
        timestamp: True
        # Optional: draw bounding box on the snapshots (default: shown below)
        bounding_box: True
        # Optional: crop the snapshot (default: shown below)
        crop: True
        # Optional: height to resize the snapshot to (default: shown below)
        height: 270
        # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
        #required_zones: []
  
      # Optional: Camera level object filters config.
      objects:
        track:
          - person
  
      record:
      #Optional: Enable recording
        enabled: True
      #Optional: Number of days to retain
        retain_days: 30
      
      clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
        enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
        pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
       # objects:
       #   - person
       #   - car
       #   - truck
      # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
      # Optional: Camera override for retention settings (default: global values)
        retain:
      # Required: Default retention days (default: shown below)
          default: 30
      # Optional: Per object retention days
          objects:
            person: 30
  
      # Optional: Configuration for the jpg snapshots written to the clips directory for each event
      snapshots:
        # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
        # This value can be set via MQTT and will be updated in startup based on retained value
        enabled: True
        # Optional: print a timestamp on the snapshots (default: shown below)
        timestamp: False
        # Optional: draw bounding box on the snapshots (default: shown below)
        bounding_box: True
        # Optional: crop the snapshot (default: shown below)
        crop: False
        # Optional: height to resize the snapshot to (default: original size)
        height: 175
        # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
        #required_zones: []
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 30
          # Optional: Per object retention days
          objects:
            person: 30

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

### Relevant log output

```shell
No log output needed
```

### FFprobe output from your camera

```shell
Not a camera issue
```

### Frigate stats

```json
{
  "backyard": {
    "camera_fps": 5.1, 
    "capture_pid": 56, 
    "detection_fps": 0.0, 
    "pid": 52, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 281.46, 
      "pid": 42
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 274.98, 
      "pid": 44
    }, 
    "cpu3": {
      "detection_start": 0.0, 
      "inference_speed": 277.67, 
      "pid": 46
    }, 
    "cpu4": {
      "detection_start": 0.0, 
      "inference_speed": 251.89, 
      "pid": 48
    }
  }, 
  "driveway": {
    "camera_fps": 5.0, 
    "capture_pid": 55, 
    "detection_fps": 0.0, 
    "pid": 51, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "front_door": {
    "camera_fps": 5.1, 
    "capture_pid": 60, 
    "detection_fps": 0.0, 
    "pid": 53, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "garage": {
    "camera_fps": 5.2, 
    "capture_pid": 67, 
    "detection_fps": 0.0, 
    "pid": 54, 
    "process_fps": 0.0, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 63.4, 
        "mount_type": "tmpfs", 
        "total": 67.1, 
        "used": 3.7
      }, 
      "/media/frigate/clips": {
        "free": 330118.0, 
        "mount_type": "cifs", 
        "total": 1099508.5, 
        "used": 769390.5
      }, 
      "/media/frigate/recordings": {
        "free": 330118.0, 
        "mount_type": "cifs", 
        "total": 1099508.5, 
        "used": 769390.5
      }, 
      "/tmp/cache": {
        "free": 95623.3, 
        "mount_type": "ext4", 
        "total": 215066.8, 
        "used": 109548.6
      }
    }, 
    "uptime": 917694, 
    "version": "0.8.4-5043040"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest
