### ISSUE TITLE
Zones for Higher Detection

### ISSUE THREAD

**Issue by tkffaul** [blakeblackshear/frigate#2147]
### Describe the problem you are having

I have a camera that looks down a long driveway, I want to have different conditions for front and rear of the drive. I have some of this working but not completely... I created a zone just for the front of the drive and I've loosened up this zone to look for people with more relaxed rules. This is my Config: See Below

This config works, kinda... I have to use the required_zones to get the zones to work... but I dont think I'm getting recording or snapshots in the standard zone. If I take it out I loose the zone. Do I have to create a second zone? I just figured that the standard settings would apply everywhere the zone wasn't. Is there a way to make this work? Please forgive the thresholds here... I was forcing this thing down and down for testing to try to get it to trigger. So I can see in the debug that I can trigger in either zone right now but as stated above I'm only getting alerts and recording from the defined zone.

### Version

0.94

### Frigate config file

```yaml
Driveway:
    ffmpeg:
      inputs:
        - path: <Camera Path>
          roles:
            - record
        - path: <Camera Path>
          roles:
            - detect
        - path: <Camera Path>
          roles:
            - rtmp
    detect:
      width: 896
      height: 672
      fps: 5
    record:
      events:
        required_zones:
          - Driveway_Far
    snapshots:
      required_zones:
        - Driveway_Far
    zones:
      Driveway_Far:
        coordinates: 615,0,614,156,483,157,483,257,0,300,0,0
        filters:
          person:
            min_area: 500
            max_area: 50000
            min_score: 0.1
            threshold: 0.5
          car:
            min_area: 1500 
            max_area: 100000
            min_score: 0.3
            threshold: 0.5
          truck:
            min_area: 1500
            max_area: 100000
            min_score: 0.5
            threshold: 0.7
          dog:
            min_area: 300
            max_area: 10000
            min_score: 0.3
            threshold: 0.7
          cat:
            min_area: 300
            max_area: 10000
            min_score: 0.3
            threshold: 0.7
          motorcycle:
            min_area: 2000
            max_area: 100000
            min_score: 0.3
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            min_score: 0.3
            threshold: 0.7
    objects:
      filters:
        person:
          min_area: 1200
          max_area: 50000
          min_score: 0.1
          threshold: 0.7
          mask:
            - "563,176,599,153,640,150,651,248,617,251,537,259,471,248,464,170" #<-- 896x672 Trashcans
            - "0,0,488,0,488,87,204,120,163,184,21,408,0,408" #<-- 896x672 Side Yard and Street
        car:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - "493,0,491,90,0,140,0,0"
        motorcycle:
          min_area: 2000
          max_area: 100000
          min_score: 0.3
          threshold: 0.7
          mask:
            - "493,0,491,90,0,140,0,0"
        bicycle:
          min_area: 2000
          max_area: 100000
          min_score: 0.3
          threshold: 0.7
          mask:
            - "493,0,491,90,0,140,0,0"
        truck:
          min_area: 3000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - "493,0,491,90,0,140,0,0"
        dog:
          min_area: 300
          max_area: 10000
          min_score: 0.3
          threshold: 0.7
          mask:
            - "553,177,602,153,651,159,648,253,611,258,561,257,471,251,477,174" #<-- 896x672 Trashcans
        cat:
          min_area: 300
          max_area: 10000
          min_score: 0.3
          threshold: 0.7
          mask:
            - "553,177,602,153,651,159,648,253,611,258,561,257,471,251,477,174" #<-- 896x672 Trashcans
    motion:
      threshold: 5
      contour_area: 25
      frame_alpha: 0.15
      mask: 
        - "493,0,0,0,0,403,21,403,208,123,421,104,493,100" # <-- 896x672 Street
        - "488,91,617,139,623,189,555,199,486,180,477,162,444,141,442,89" # <-- 896x672 Bushes
```

### Relevant log output

```shell
See above
```

### FFprobe output from your camera

```shell
See above
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

**Comment by tkffaul** [comment]
Sorry I tried to reformat the config but its not working.

**Comment by tkffaul** [comment]
After a lot of searching, I think i have the answer. It would appear that zones can only be more restrictive not less. @blakeblackshear would have to tell me if I'm wrong here. But I'm pretty certain that I cant loosen in my zones. So my dropping of settings just made the main detect further into my zone and I think the "required_zones" made the default step back so the zone could work? I would still like to know if its required to use the "required_zones" config options and is there anyway in the future to make a reduced zone? BTW this is the best software around! I've tested a bunch of packages and this is really flexible!

**Comment by blakeblackshear** [comment]
Can you explain what you are trying to accomplish? Something like, I want events for cars in zone1, dogs in zone2, and people everywhere.

**Comment by tkffaul** [comment]
I have a camera that covers a lot of distance... so let say i want to see a person and lets just say its dark. If i look near to the camera the threshold can be much higher as the lights from the house and the IR are very strong up close (first 60ft or so), but i want to create a zone further out (say out close to 150ft) that I can loosen the requirements on. The way my property sits there are very few objects further out to get false positives on, but near the house there are all kind of things. So i want to detect the same object just with different settings.

**Comment by blakeblackshear** [comment]
I see something like this should work:

```yaml
Driveway:
    ffmpeg:
      inputs:
        - path: <Camera Path>
          roles:
            - record
        - path: <Camera Path>
          roles:
            - detect
        - path: <Camera Path>
          roles:
            - rtmp
    detect:
      width: 896
      height: 672
      fps: 5
    record:
      events:
        required_zones:
          - Driveway_Far
          - Driveway_Near
    snapshots:
      required_zones:
        - Driveway_Far
        - Driveway_Near
    zones:
      Driveway_Far:
        coordinates: 615,0,614,156,483,157,483,257,0,300,0,0
        filters:
          person:
            min_area: 500
            max_area: 50000
            min_score: 0.1
            threshold: 0.5
          car:
            min_area: 1500 
            max_area: 100000
            min_score: 0.3
            threshold: 0.5
          truck:
            min_area: 1500
            max_area: 100000
            min_score: 0.5
            threshold: 0.7
          dog:
            min_area: 300
            max_area: 10000
            min_score: 0.3
            threshold: 0.7
          cat:
            min_area: 300
            max_area: 10000
            min_score: 0.3
            threshold: 0.7
          motorcycle:
            min_area: 2000
            max_area: 100000
            min_score: 0.3
            threshold: 0.7
          bicycle:
            min_area: 2000
            max_area: 100000
            min_score: 0.3
            threshold: 0.7
      Driveway_Near:
        coordinates: ...
```

**Comment by tkffaul** [comment]
I actually tried this, but it seems to only take the first set of entries. I can detect objects in the first zone, but the far zone wont detect. I tried this in broad daylight were I can clearly see the object (in this case my son) and motion tracking locks on to the object but no notifications about an object in that zone. Unless the object scores high enough to hit the near zone numbers, then i get a notification. So if i set a threshold of .7 in the near zone and then .4 in the far... the far wont detect until I get 70% on the object regardless of zone. I've since removed the zones as I just cant get them to work. I feel like I'm not setting something correctly, but by your config i did set them right.
```yaml
  Front:
    ffmpeg:
      inputs:
        - path:<>
          roles:
            - record
        - path: <>
          roles:
            - detect
        - path: <>
          roles:
            - rtmp
    detect:
      width: 896
      height: 672
      fps: 7
    record:
      events:
        required_zones:
          - FrontYard
          - FrontDrive
    snapshots:
      required_zones:
        - FrontYard
        - FrontDrive
    zones:
      FrontYard: # <-- All of the Yard
        coordinates: 0,118,42,122,53,234,99,260,276,203,383,190,673,311,896,464,896,672,0,672 #0,0,896,0,896,672,0,672
        #Optional: filters to reduce false positives for specific object types
        filters:
          person:
            min_area: 2000
            max_area: 70000
            min_score: 0.1
            threshold: 0.65
          car:
            min_area: 1000
            max_area: 100000
            min_score: 0.3
            threshold: 0.65
          truck:
            min_area: 2000
            max_area: 100000
            min_score: 0.5
            threshold: 0.65
          dog:
            min_area: 300
            max_area: 3000
            min_score: 0.1
            threshold: 0.7
          cat:
            min_area: 300
            max_area: 3000
            min_score: 0.1
            threshold: 0.7
      FrontDrive: # <-- Drive and Street
        coordinates: 0,0,896,0,896,464,673,311,383,190,276,203,99,260,53,234,42,122,0,118
        # Optional: filters to reduce false positives for specific object types
        filters:
          person:
            # Optional: minimum width*height of the bounding box for the detected object (default: 0)
            min_area: 300
            # Optional: maximum width*height of the bounding box for the detected object (default: 240>
            max_area: 100000
            # Optional: minimum score for the object to initiate tracking (default: shown below)
            min_score: 0.1
            # Optional: minimum decimal percentage for tracked object's computed score to be considere>
            threshold: 0.4
          car:
            min_area: 1000
            max_area: 60000
            min_score: 0.3
            threshold: 0.5
          truck:
            min_area: 2000
            max_area: 100000
            min_score: 0.5
            threshold: 0.6
          dog:
            min_area: 300
            max_area: 3000
            min_score: 0.1
            threshold: 0.5
          cat:
            min_area: 300
            max_area: 3000
            min_score: 0.1
            threshold: 0.5
          bus:
            min_area: 7000
            max_area: 100000
            min_score: 0.5
            threshold: 0.7
          motorcycle:
            min_area: 600
            max_area: 100000
            min_score: 0.3
            threshold: 0.5
          bicycle:
            min_area: 600
            max_area: 100000
            min_score: 0.3
            threshold: 0.5
    objects:
      filters:
        person:
          # min_area: 2000
          # max_area: 100000
          # min_score: 0.1
          # threshold: 0.7
          mask:
            #- "854,253,1085,247,1088,179,854,182" # <--1600x1200
            - "462,143,603,152,608,95,463,92" # <--896x672 Mailbox
            - "142,195,171,182,156,130,125,136" # <--896x672 Tree
            - "0,0,896,0,896,219,706,164,469,140,325,133,205,129,103,157,0,195" # <--896x672 Street
        dog:
          # min_area: 300
          # max_area: 3000
          # min_score: 0.1
          # threshold: 0.7
          mask:
            - "462,143,603,152,608,95,463,92" # <--896x672 Mailbox
            - "142,195,171,182,156,130,125,136" # <--896x672 Tree          
        cat:
          # min_area: 300
          # max_area: 3000
          # min_score: 0.1
          # threshold: 0.7
          mask:
            - "462,143,603,152,608,95,463,92" # <--896x672 Mailbox
            - "142,195,171,182,156,130,125,136" # <--896x672 Tree 
        car:
          # min_area: 5000
          # max_area: 60000
          # min_score: 0.3
          # threshold: 0.7
          mask:
            - "0,0,896,0,896,230,689,172,446,146,375,140,323,137,192,133,103,157,0,195" # <--896x672 Street
        truck:
          # min_area: 5000
          # max_area: 60000
          # min_score: 0.3
          # threshold: 0.7
          mask:
            - "0,0,896,0,896,230,689,172,446,146,375,140,323,137,192,133,103,157,0,195" # <--896x672 Street
        bus:
          mask:
            - "0,0,896,0,896,230,689,172,446,146,375,140,323,137,192,133,103,157,0,195" # <--896x672 Street
        motorcycle:
          # min_area: 5000
          # max_area: 60000
          # min_score: 0.3
          # threshold: 0.7
          mask:
            - "0,0,896,0,896,230,689,172,446,146,375,140,323,137,192,133,103,157,0,195" # <--896x672 Street
        bicycle:
          # min_area: 5000
          # max_area: 60000
          # min_score: 0.3
          # threshold: 0.7
          mask:
            - "0,0,896,0,896,230,689,172,446,146,375,140,323,137,192,133,103,157,0,195" # <--896x672 Street
    motion:
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255. (Default 25)
      threshold: 5
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller moving objects.
      contour_area: 15
      # Low values will cause things like moving shadows to be detected as motion for longer. (Default 0.2)
      frame_alpha: 0.13
      mask: 
        #- "1600,0,1600,356,1006,269,697,239,512,296,333,343,0,442,0,0" # <-- 1600x1200 Road
        #- "1131,1200,1160,1001,1099,764,964,672,814,628,577,611,463,545,327,560,166,595,114,663,217,856,313,925,422,1200" #<--1600x1200 Bush
        #- "896,0,896,230,694,178,474,141,377,138,275,163,0,238,0,0" # <-- 896x672 Road
        - 0,0,896,0,896,230,689,172,446,146,375,140,323,137,192,133,103,157,0,195 # <-- 896x672 Road
        - 636,672,668,555,639,464,596,409,517,386,438,377,356,400,326,330,266,299,98,333,42,373,222,672 # <-- 896x672 Bush
```

Please excuse all the comments as I was trying to move back and forth and test different items in the config.
