### ISSUE TITLE
[Support]: 400 errors when using Frigate Proxy and Home Assistant OS notifications

### ISSUE THREAD

**Issue by craigmdennis** [blakeblackshear/frigate#2150]
### Describe the problem you are having

_I've exhausted my Googling and forum posts so hoping to either identify a bug or get some help resolving this issue in the hope that it helps someone else._

- I'm running Frigate in Unraid Docker.
- I'm running HassOS.
- I have Frigate NVR Proxy Addon installed in Supervisor and configured to point to Frigate in Unraid (using the local IP and port 5000).
- I am able to view Frigate in the HA sidebar without issue.

I'm using the recommended [Blueprint](https://gist.github.com/hunterjm/23c1588a9f2b8b9c2a62ffc364e17f8c) for HA notifications and the notification part works; I get alerts for different events.

But, no image shows up and the actionable links return a 400 error when pressed.

API request from HA: http://192.168.0.YYY:8123/api/frigate/notifications/{event_id}/camera_1/clip.mp4 (400)

Direct API request to frigate instance: http://192.168.0.XXX:5000/api/events/{event_id}/clip.mp4 (Success)

It doesn’t matter if I used the Nabu Casa remote URL, a reverse proxy, or the internal IP address - I always get a 400 response.

The only errors that show up anywhere are posted below in the relevant log output section. This seems related but the timestamps don't appear to line up with events (at least at first glance).

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.XXX
  user: XXX
  password: XXX
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  quality: 8
  mode: continuous

cameras:
  camera_1:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -rw_timeout
        - "5000000"
        - -f
        - live_flv
      inputs:
        - path: rtmp://192.168.0.XXX/bcs/channel0_sub.bcs?channel=0&stream=0&user=frigate&password=XXX
          roles:
            - detect
        - path: rtmp://192.168.0.XXX/bcs/channel0_main.bcs?channel=0&stream=0&user=frigate&password=XXX
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 360
    objects:
      track:
        - person
        - dog
        - car
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
    motion:
      mask:
        - 334,224,343,293,222,311,216,237
        - 0,192,186,0,0,0
```

### Relevant log output

```shell
2021/10/29 12:30:49 [error] 356#356: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: ccab4aaf-frigate-proxy, request: "GET // HTTP/1.1", upstream: "http://192.168.0.XXX:5000//", host: "192.168.0.XXX:8123", referrer: "http://192.168.0.XXX:8123/ccab4aaf_frigate-proxy"
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"camera_1":{"camera_fps":5.1,"capture_pid":252,"detection_fps":0.0,"pid":249,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":24.81,"pid":241}},"service":{"storage":{"/dev/shm":{"free":5367.8,"mount_type":"tmpfs","total":5368.7,"used":0.9},"/media/frigate/clips":{"free":19558025.6,"mount_type":"fuse.shfs","total":33994846.6,"used":14436821.0},"/media/frigate/recordings":{"free":19558025.6,"mount_type":"fuse.shfs","total":33994846.6,"used":14436821.0},"/tmp/cache":{"free":7233.5,"mount_type":"rootfs","total":8109.9,"used":876.4}},"uptime":6975,"version":"0.9.4-26ae608"}}
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-410W
