### ISSUE TITLE
[Support]: Frigate NVR Proxy Does Not Load Up in HA Mobile Application

### ISSUE THREAD

**Issue by humptydumptyhaoz** [blakeblackshear/frigate#2154]
### Describe the problem you are having

Nothing loaded in Home Assistant mobile application using Frigate NVR Proxy (Frigate hosted in unraid), but work perfectly in web browser.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.***.***
  user: *****
  password: ******

cameras:
  Entrance:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.***.***:8554/profile0
          roles:
            - detect
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
  Kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.***.***:8554/profile0
          roles:
            - detect
    detect:
      width: 2304
      height: 1296
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
Frigate NVR Proxy:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Frigate NVR Proxy
 Proxy addon for Frigate
-----------------------------------------------------------
 Add-on version: 1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.10.6
 Home Assistant Supervisor: 2021.10.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:39:37] INFO: Starting NGinx...
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

SRIHOME/SRICAM 029

### Any other information that may be helpful

-
