### ISSUE TITLE
[Support]: Daylight saving bug? After jumping back in time makes new events unavailable

### ISSUE THREAD

**Issue by twau** [blakeblackshear/frigate#2158]
### Describe the problem you are having

Last night after jumping from CEST to CET, all further clips where stuck in /tmp/cache in the frigate container. I could no longer view events from the frigate webui. Anyone else whom using CEST/CET noticed this or was it limited to my setup?

Unfortuanlly I needed my recording up and running again so I deleted my broken frigate.db and now it works.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: x
  user: x
  password: x

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

objects:
  track:
    - person
    - bird
    - cat
    - dog
    - car
    - bicycle

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"

cameras:
  Uteplats:
    ffmpeg:
      inputs:
        - path: rtsp://x:{FRIGATE_RTSP_PASSWORD}@192.168.10.3:554/Streaming/Channels/101
          roles:
            - record
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1440
      fps: 6
    record:
      enabled: True
      retain_days: 3
      events:
        retain:
          default: 3
          objects:
            person: 5
    motion:
      mask:
        - 81,858,406,1440,0,1440,0,802,0,398,281,220,414,254,583,170,651,461
        - 2560,1440,2560,0,2349,0,1740,785,1937,875,2137,637,2344,304,2205,688,1706,1440
        - 309,0,0,201,0,0
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5

  Uppfart:
    ffmpeg:
      inputs:
        - path: rtsp://x:{FRIGATE_RTSP_PASSWORD}@192.168.10.5:554/Streaming/Channels/101
          roles:
            - record
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 6
    record:
      enabled: True
      retain_days: 3
      events:
        retain:
          default: 3
          objects:
            person: 5
    motion:
      mask:
        - 731,263,607,0,1280,0,1280,401,1123,546,998,572,851,581
        - 211,658,338,659,338,685,208,683
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5

  Basement:
    ffmpeg:
      inputs:
        - path: rtsp://x:{FRIGATE_RTSP_PASSWORD}@192.168.10.4:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 6
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 1
          objects:
            person: 3
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3
    motion:
      mask:
        - 1591,1056,1742,1058,1745,1016,1589,1018
    zones:
      kattlada:
        coordinates: 1087,801,1296,779,1263,616,1078,627

  Tvattstuga:
    ffmpeg:
      inputs:
        - path: rtsp://x:{FRIGATE_RTSP_PASSWORD}@192.168.10.2:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
            - detect
    detect:
      width: 1280
      height: 720
      fps: 4
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 1
          objects:
            person: 3
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3
    motion:
      mask:
        - 942,616,956,461,839,466,829,626
        - 399,667,535,668,532,701,398,701
```

### Relevant log output

```shell
root@frigate:~# timedatectl 
               Local time: Sun 2021-10-31 20:19:38 CET  
           Universal time: Sun 2021-10-31 19:19:38 UTC  
                 RTC time: Sun 2021-10-31 19:19:38      
                Time zone: Europe/Stockholm (CET, +0100)
System clock synchronized: yes                          
              NTP service: active                       
          RTC in local TZ: no                           
root@frigate:~# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
root@frigate:~# docker -v
Docker version 20.10.10, build b485636
root@frigate:~# docker-compose -v
docker-compose version 1.29.2, build 5becea4c
root@frigate:~# uname -a
Linux frigate 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### FFprobe output from your camera

```shell
root@28348aa3c10c:/opt/frigate# ffprobe rtsp://x:x@192.168.10.3:554/Streaming/Channels/101
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://x:x@192.168.10.3:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 1.033333, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 2560x1440, 6 fps, 20 tbr, 90k tbn, 12 tbc
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hilook IPC-D120H, Hilook IPC-T240H, Hikvision DS-2CV2041G2-IDW Hilook, IPC-D120H, Hilook IPC-T240H
