### ISSUE TITLE
[Support]: Container runs out of space

### ISSUE THREAD

**Issue by ryanm101** [blakeblackshear/frigate#2161]
### Describe the problem you are having

Even though I have the whole of /media/frigate mapped to local disk the container  there was no space left of my root volume until i deleted the frigate container.

`5.0G    /srv/frigate/data`  is what is used in persistent storage

`/dev/mapper/nuc2--vg-root     45G   15G   28G  36% /`  is my root after i deleted the frigate container prior to that it was 100%. 

It took 3 days to fill, so i'll monitor it more this week and see if i can determine where the storage is being used. 

### Version

0.9.4

### Frigate config file

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:0.9.4-amd64
    shm_size: "1gb"
    devices:
      - /dev/apex_0
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/conf/config.yml:/config/config.yml:ro
      - /srv/frigate/data:/media/frigate
    tmpfs: /tmp/cache,size=1G
    ports:
      - "5000:5000"
      - "1935:1935"
```

### Relevant log output

```shell
None yet
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

hikvision
