### ISSUE TITLE
[Support]: No recording of clips

### ISSUE THREAD

**Issue by euro2** [blakeblackshear/frigate#2163]
### Describe the problem you are having

2 out of 3 camera's, wyze v3 with rtsp firmware and exact similair setups, wont record clips.
All streams are shown on frigate, its just that it wont record. Live views also work.

pressing recordings under the cam: 
"No Recordings Found. Make sure you have enabled the record role in your configuration for the woonkamer_cam camera."

going to events and then press one play:
The media could not be loaded, either because the server or network failed or because the format is not supported."

i *think* its because of updating to a new version i did without thinking

### Version

0.9.4-26ae608

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.9
  user: xxxx
  password: xxxx
  topic_prefix: frigate
  client_id: frigate

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
  cpu5:
    type: cpu
  cpu6:
    type: cpu
  cpu7:
    type: cpu
  cpu8:
    type: cpu

live:
  height: 1080
  quality: 8

timestamp_style:
  position: "tl"
  format: "%d-%m-%Y %H:%M:%S"
  color:
    red: 255
    green: 0
    blue: 0
  thickness: 2

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: motion

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: True

record:
  # Optional: Enable recording (default: shown below)
  enabled: True
  # Optional: Number of days to retain recordings regardless of events (default: shown below)
  # NOTE: This should be set to 0 and retention should be defined in events section below
  #       if you only want to retain recordings of events.
  retain_days: 0
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 240
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 2
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 8
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 5



# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5

cameras:
  voortuin_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.181/live
          roles:
            - detect
            - record
            - clips
    detect:    
      width: 1920
      height: 1080
      fps: 5
      enabled: True
    motion:
      mask: 
          - 880,223,848,410,937,422,972,280,1021,251,1158,281,1119,424,1423,650,1471,575,1725,763,1920,493,1920,0,628,0,0,0,0,307,0,504,0,1080,169,1080,84,603,114,71,167,77

  woonkamer_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.180/live
          roles:
            - detect
            - record
            - clips
    detect:    
      width: 1920
      height: 1080
      fps: 5
      enabled: True

  achtertuin_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.182/live
          roles:
            - detect
            - record
            - clips
    detect:    
      width: 1920
      height: 1080
      fps: 5
      enabled: True
    motion:
      mask:
        - 0,377,665,164,715,238,1140,179,1434,128,1685,61,1659,0,0,0
```

### Relevant log output

```shell
dont know how
```

### FFprobe output from your camera

```shell
dont know how
```

### Frigate stats

```json
dont know how
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

3x Wyze v3

**Comment by euro2** [comment]
supervisor log gives me this. Not sure its related

21-11-01 18:49:55 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.2:5000/_snowpack/pkg/common/_commonjsHelpers-798ad6a7.raTN1lWyU9Kv.js: Cannot write to closing transport
21-11-01 18:49:55 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.2:5000/_snowpack/env.QF6Q-uhFewNU.js: Cannot write to closing transport
21-11-01 18:49:55 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.2:5000/dist/components/Tooltip.h3pnKvx5FrVZ.js: Cannot write to closing transport
21-11-01 18:50:00 ERROR (MainThread) [supervisor.api.ingress] Stream error with http://172.30.33.2:5000/dist/routes/Camera.siLAtYdtmwdH.js: Cannot write to closing transport

**Comment by madmic1314** [comment]
What's your CPU utilisation like? Pulling 3 cameras at 1920x1080 is too much for most systems unfortunately. Turn off all but camera1, test. Turn off camera1, turn on camera2, test. Off 2, on 3, test. If each camera records on their own then it's down to the system. Unlikely it's the cameras if they're all configured the same. My guess is it's CPU power. You'll really need a coral to make this work properly.

Also you're not running any form of HW acceleration for the ffmpeg stream - have a read of this and enable if you can. This will help somewhat. But until you have a coral I don't think you'll have much joy.

**Comment by euro2** [comment]
something is fishy. I had it working with 3 cams earlier. Now when i add a second one, it wont record with the same errors.

My cpu is practically idling, even with load....

**Comment by madmic1314** [comment]
I had the same, quad-core i7 with hyper threading on: one camera was ok for motion, add in recording and it went crazy - two killed it.

I'm not proxmox guy, but in esx you can pass the vga card through, if it's supported. I never had it working properly, but moved to a native Ubuntu docker installation recently. https://docs.frigate.video/configuration/hardware_acceleration describes the hw acceleration options. Have you read through this: https://github.com/blakeblackshear/frigate/discussions/1111 - might help?

I think for your setup you're looking at trading off either recording or motion. I'd go back to one camera with just recording, add in a second, then the 3rd and see. Then add in motion on cam 1 and see.

You're not masking camera 2 in your config, so any motion will be sent for detection - have a look at [camera name] -> debug option (right hand side of the video feed). Turn on motion boxes and see what's happening.

You might also consider sending a smaller feed to the motion detection system - my hikvisions have a substream at 640*360 that's much easier to process.

Here's a snippet of my config (I have 3 cameras, all the same model). You can see the record stream is the full 1920x1080 feed, with the motion (detect) stream at 640x360. I've also reduced the resolution of the birdseye view as well.

//
detectors:
 coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.xx.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p
birdseye:
  enabled: True
  width: 640
  height: 360
  quality: 8
  mode: continuous
detect:
  width: 640
  height: 360
  fps: 5
snapshots:
  enabled: true
  crop: false
  timestamp: false
  retain:
    default: 10
    objects:
      person: 15
rtmp:
  enabled: false
cameras:
  front:
    ffmpeg:
      inputs:
        - path: 'rtsp://xxx:xxx@192.168.xx.xx:554/Streaming/Channels/102'
          roles:
            - detect
        - path: 'rtsp://xxx:xxx@192.168.xx.xx:554'
          roles:
            - record
    record:
      enabled: True
      retain_days: 30
      events:
        retain:
          default: 10
    motion:
      mask:
        - 0,360,137,360,79,217,191,181,212,120,137,99,52,140,39,24,55,0,0,0
        - 395,0,539,117,640,164,640,0
    best_image_timeout: 60
    rtmp:
      enabled: false
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
        cat:
          min_area: 0
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
logger:
  default: info
\\

**Comment by euro2** [comment]
Now even 1 cam fails.... dafuck. yet to make any sense of this.

**Comment by madmic1314** [comment]
I'd strip your config back to the very basic, get one camera up, working on a smaller stream for detection. Then add in recording on a primary stream. When I was starting with Frigate I went through all this, with the added layer of esx in the way.

Maybe grab another machine (if you've got one, guessing likely you have with access to this kind of server power) and run ubuntu + docker and see how you get on. The move the good config to Proxmox?

**Comment by euro2** [comment]
id might go for a separate LXC container on proxmox indeed. Just to keep stuff separated. I removed.

even just motion detection now fails, without an ai detect. Yes imma ditch all code and restart. Also i reinstall frigate.

**Comment by euro2** [comment]
now this fails:
https://www.toptal.com/developers/hastebin/caqomajadi.yaml

**Comment by madmic1314** [comment]
The pasted config has record enabled. Remove lines 26-35 and the rtmp and record roles from the camera.

If you install VLC video player and open a network location - use your camera stream and see what happens. Does this work, or are you getting a funny feed?

**Comment by euro2** [comment]
the stream is fine, all are. I installed an extra accesspoint for them as well.
The basic config works. Once i start adding recording it doesnst start. The dirs are not made in /media/frigate/etc...

**Comment by euro2** [comment]
After some tinkering with docker and portainer, both new-ish to me, i have Frigate running on a clean proxmox debian LXC container. I got video feed from 1 singe Wyze v3 rtsp stream.

I must be missing some VERY basic setting somewhere because i get exactly the same error now as i had in Home Assistant. 
No mp4 files are being made.

this is what i have
![01](https://user-images.githubusercontent.com/6632948/139828011-ef6f0abf-ccc5-4573-ab65-4383d9f056c8.PNG)
:

-clips is being populated with images
-config.yml is in the config dir. Working because i get video
-db files are in db dir. working cause the dir got auto populated
-recordings stay empty?

Portainerscreenshot:

![02](https://user-images.githubusercontent.com/6632948/139829055-c2f226a5-2499-4d91-bdb7-0cc2ed02171f.PNG)

My config.yml
`
database:
  path: /media/frigate/db/frigate.db

mqtt:
  host: 192.168.1.9
  user: xx
  password: xx
  topic_prefix: frigate
  client_id: frigate

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

cameras:
  woonkamer_cam:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.1.180/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True
    record:
      enabled: True

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 240
    pre_capture: 2
    post_capture: 8
    retain:
      default: 5
`

**Comment by euro2** [comment]
I GOT IT! Recording works again

Its either:

i changed prefix&id from frigate to frigate2, just to make something different
  topic_prefix: frigate2
  client_id: frigate2

OR

i removed the (already stopped) Frigate on HA and i removed the HACS HA integration

ill investigate later.

**Comment by madmic1314** [comment]
Glad you got it working - if you want to you can look into your MQTT database with an app like MQTT Explorer and see what's there and delete old topics. Just be careful you don't delete something you need!

**Comment by RobertusIT** [comment]
> I GOT IT! Recording works again (on LXC+docker)
> 
> Its either:
> 
> i changed prefix&id from frigate to frigate2, just to make something different topic_prefix: frigate2 client_id: frigate2
> 
> OR
> 
> i removed the (already stopped) Frigate on HA and i removed the HACS HA integration
> 
> ill investigate later.
> 
> EDIT: Its the renaming of the topic_prefix and the client_id which fixed the issue. I have recording on all 3 stream again. recordings dir is getting populated with mp4 again. Why this is happening i dunno.

same issue here, no way with your suggest.

prefix and id change nothing

**Comment by euro2** [comment]
it happened again. Recording stopped working

**Comment by blakeblackshear** [comment]
Are you certain this isn't the daylight savings bug?

**Comment by fgonza2** [comment]
I have a similar issue.   Only one camera in particular:

```
No Recordings Found
Make sure you have enabled the record role in your configuration for the Backyard camera.
```

Globals & Camera config:

```
record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 2
    max_seconds: 30
    pre_capture: 3
    post_capture: 3

Backyard: 
    ffmpeg:
     inputs:
      - path: rtsp://xx.xx.xx.xx/h264_stream
        roles:
          - detect
          - record
    detect:
      width: 1920
      height: 1080
```

Record works on the other camera but not this one, identical config

**Comment by daranto** [comment]
I have a similar problem. I have only one cam and its not recording. I think the problem starts after I toggled the recording via Home Assistant switch off. I want only record when I am not home. But this don´t work. I get only the snapshots. The recording folder is empty.

Here is my config: 

```
cameras:
  Eingang: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user_removed:password_removed@192.168.1.40:554/live/ch1
          roles:
            - detect            
        - path: rtsp://user_removed:password_removed@192.168.1.40:554/live/ch0
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 20
        objects:
          - person
        retain:
          default: 2
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False

detectors: 
  coral:
    type: edgetpu
    device: pci:0
```
