### ISSUE TITLE
Doc Update: HA Notifications - Include live stream of Camera

### ISSUE THREAD

**Issue by Gurutasker** [blakeblackshear/frigate#2169]
The below could be included in the documentation as an example for live streaming of cameras in notifications on the following page; https://docs.frigate.video/guides/ha_notifications/

This automation can be used to include an live stream of the camera within the notification for iOS devices, using the _entity_id_ field. More information on dynamic content can be found here; https://companion.home-assistant.io/docs/notifications/dynamic-content#camera-stream

It also shows how the trigger payload can be configured to only notify on new events, rather than receiving multiple notifications for a single event.

```
alias: Security_Frigate_Notifications
description: ''
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: '{{ value_json.type }}'
condition: []
action:
  - service: notify.mobile_app_iphone
    data:
      message: '''A {{trigger.payload_json["after"]["label"]}} was detected.'''
      data:
        image: >-
          https://your.public.hass.address.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        entity_id: camera.{{trigger.payload_json["after"]["camera"]}}
mode: single
```
