### ISSUE TITLE
Zone filters not working for overlapping areas

### ISSUE THREAD

**Issue by lupac** [blakeblackshear/frigate#218]
**Describe the bug**
If two zones (on the same camera) overlap, the zone filters are not respected and detected object is triggered in both zones.

**Version of frigate**
0.6.0-rc3

**Expected resuls**
If an object is detected in the overlapping area of configured zones, zone filters should be respected and report only for object matching specific zone filters.

**Config file**

```
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 1000000
      min_score: 0.5
      threshold: 0.5

  ipcam13:
    ffmpeg:
      input: rtsp://blabla
    #mask: ipcam13_stairs_mask.bmp
    zones:
      outside_yard:
        coordinates:
          - 0,0
          - 0,1078
          - 907,1078
          - 909,622
          - 1621,621
          - 1621,565
          - 1786,565
          - 1784,490
          - 1918,493
          - 1918,3
        filters:
          person:
            min_area: 5000
            max_area: 700000
            threshold: 0.75
      outside_stairs:
        coordinates:
          - 938,1078
          - 1918,1078
          - 1918,3
          - 1108,0
          - 1106,110
          - 940,112
        filters:
          person:
            min_area: 180000
            max_area: 700000
            threshold: 0.75
    fps: 4
    snapshots:
      show_timestamp: True
      draw_zones: True
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 700000
          min_score: 0.5
          threshold: 0.75
```

In the above config, the outside_stairs zone is showing ON when a person is in the overlapping area even though they are smaller than the min_area filter.
