### ISSUE TITLE
DOC Update: Provide an example of a camera configuration that ONLY takes snapshots and records when motion is detected

### ISSUE THREAD

**Issue by Tokn59** [blakeblackshear/frigate#2180]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to configure a camera (or all of them) so that when motion is detected, a snapshot is taken and a "clip" is recorded

**Describe the solution you'd like**
As described above

**Describe alternatives you've considered**

**Additional context**
Current configuration with snapshots, events and recording options is confusing and I haven't succeeded yet in obtaining the above. I have read the documentation and did a lot of tests with different configurations.

**Comment by blakeblackshear** [comment]
Frigate doesn't do anything with motion alone, so the concept of "do something when motion is detected" doesn't exist. Do you mean "do something when an object is detected"?

**Comment by Tokn59** [comment]
Sorry, YES .. that's exactly what I mean !

**Comment by Multipage** [comment]
@Tokn59 
Here is my complete config file (maybe you see other stuff in there that could be usefull (Btw i added the 'hwaccel_output_format' today, no problems with that):
```
mqtt:
  host: 192.168.0.20
  client_id: frigate
  user: XXX
  password: XXX
cameras:
  Voorkant:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -codec:a aac
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://XXX:XXX!h@192.168.0.92:554/Streaming/Channels/103
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 20
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle
    motion:
      mask:
        - 0,169,248,0,436,85,172,319,0,345
        - 402,45,399,0,266,0,277,51
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
  Achterkant:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -codec:a aac      
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p        
      inputs:
        - path: rtsp://XXX:XXX!h@192.168.0.91:554/Streaming/Channels/103
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 20
    objects:
      track:
        - person
        - car
        - bicycle
    motion:
      mask:
        - 74,366,803,37,806,0,399,0,0,0,0,217
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70        


record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 30

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
```

On 'Achterkant':
Events get recorded and snapshot taken if it detects a person, car or bicycle

On 'Voorkant':
Events get recorded and snapshot taken if it detects a person,cat,dog or bicycle
