### ISSUE TITLE
New install  Frigates with EdgeTPU M2

### ISSUE THREAD

**Issue by mikey6283** [blakeblackshear/frigate#2183]
### Describe the problem you are having

  Just installed M2 PCIe Edge TPU  in HA Frigate NVR addon. 
I followed the new installation steps for Reolink camera, however i  received the following error regarding the config.yml . I am unable to see what is wrong with the config.yml. 
`detectors:
  # cpu1:
  #  type: cpu
  # num_threads:3
  # cpu2:
  #  type: cpu
  # num_threads:3
  coral1:
    type: edgetpu
    device: pci:0

mqtt:
  host: 192.168.0.96
  user: mikey
  password: mqtt6283

database:
  path: /media/frigate/frigate.db

cameras:
  front_driveway:
    ffmpeg:
      hawaccel_args:
        inputs_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - nobuffer+genpts+discardcorrupt
          - -flags
          - low_delay
          - strict
          - experimental
          - -analyzeduration
          - 1000M
          - -probesize
          - 1000M
          - "5000000"
        inputs:
          - path: http://192.168.0.48/flv?port=1935&app=bcs&stream=channel10_main.bcs&user=admin&password=Front1
            roles:
              - record
              - rtmp
          - path: http://192.168.0.48/flv?port=1935&app=bcs&stream=channel10_ext.bcs&user=admin&password=Front1
            roles:
              -detect
        output_args:
          record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamp 1 -strftime 1 -c copy
      detect:
        width: 640
        height: 480
        fps: 7
      record:
        enabled: True
        retain_days: 0
        events:
          retain:
            default:10
 Any advice would be appreciated.

![Screenshot 2021-11-04 at 19 31 11](https://user-images.githubusercontent.com/88946206/140410394-51e3ce7b-42f0-48d0-8c03-630f2cc5e229.png)

### Version

not available

### Frigate config file

```yaml
detectors:
  # cpu1:
  #  type: cpu
  # num_threads:3
  # cpu2:
  #  type: cpu
  # num_threads:3
  coral1:
    type: edgetpu
    device: pci:0

mqtt:
  host: 192.168.0.96
  user: mikey
  password: mqtt6283

database:
  path: /media/frigate/frigate.db

cameras:
  front_driveway:
    ffmpeg:
      hawaccel_args:
        inputs_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - nobuffer+genpts+discardcorrupt
          - -flags
          - low_delay
          - strict
          - experimental
          - -analyzeduration
          - 1000M
          - -probesize
          - 1000M
          - "5000000"
        inputs:
          - path: http://192.168.0.48/flv?port=1935&app=bcs&stream=channel10_main.bcs&user=admin&password=Front1
            roles:
              - record
              - rtmp
          - path: http://192.168.0.48/flv?port=1935&app=bcs&stream=channel10_ext.bcs&user=admin&password=Front1
            roles:
              -detect
        output_args:
          record: -f segemnt -segment_time 60 -segment_format mp4 -reset_timestamp 1 -strftime 1 -c copy
      detect:
        width: 640
        height: 480
        fps: 7
      record:
        enabled: True
        retain_days: 0
        events:
          retain:
            default:10
```

### Relevant log output

```shell
not available
```

### FFprobe output from your camera

```shell
not available
```

### Frigate stats

```json
q
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink
