### ISSUE TITLE
[Support]: Unable to use mjpeg stream from FOSCAM FI 9803

### ISSUE THREAD

**Issue by zraken** [blakeblackshear/frigate#2184]
### Describe the problem you are having

I have an instance of frigate running fine with an rtsp camera. Now I am trying to add another camera that provides an mjpeg stream. I added the config options from the documentation but looks like ffmpeg is not able to process the stream for some reason. VLC streams the video works fine with the same URL.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: x
  user: x
  password: x
cameras:
  fami:
    ffmpeg:
      inputs:
        - path: http://192.168.2.111:88/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=x&pwd=x
          roles:
            - detect
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
    detect:
      width: 640
      height: 480
      fps: 3
  back:
    ffmpeg:
      inputs:
        - path: rtsp://x@192.168.2.111/live0
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
detectors:
  cpu1:
    type: cpu
    num_threads: 3
```

### Relevant log output

```shell
[2021-11-04 19:00:52] watchdog.fami                  ERROR   : FFMPEG process crashed unexpectedly for fami.
[2021-11-04 19:00:52] watchdog.fami                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-11-04 19:00:52] watchdog.fami                  ERROR   : You may have invalid args defined for this camera.
[2021-11-04 19:00:52] ffmpeg.fami.detect             ERROR   : [mpjpeg @ 0x564101f84a40] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
[2021-11-04 19:00:52] ffmpeg.fami.detect             ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
[2021-11-04 19:00:52] ffmpeg.fami.detect             ERROR   : Output file #0 does not contain any stream
[2021-11-04 19:00:52] frigate.video                  INFO    : fami: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-11-04 19:00:52] frigate.video                  INFO    : fami: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.2-0york0~18.04 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mpjpeg @ 0x557ab2773840] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpjpeg, from 'http://192.168.2.248:88/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=admin&pwd=paval357':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), 25 tbr, 25 tbn, 25 tbc
```

### Frigate stats

```json
{"back":{"camera_fps":5.0,"capture_pid":252,"detection_fps":2.4,"pid":249,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":2.4,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":40.87,"pid":242}},"fami":{"camera_fps":0.0,"capture_pid":251,"detection_fps":0.0,"pid":248,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":130.4,"mount_type":"tmpfs","total":134.2,"used":3.8},"/media/frigate/clips":{"free":377039.1,"mount_type":"ext4","total":453059.5,"used":52934.9},"/media/frigate/recordings":{"free":377039.1,"mount_type":"ext4","total":453059.5,"used":52934.9},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"uptime":436,"version":"0.9.4-26ae608"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

FOSCAM FI 9803
