### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by hathalud** [blakeblackshear/frigate#2190]
### Describe the problem you are having

My instance of Frigate doesn't detect cars. The system detects people alright on the other camera I have (a bit belatedly, but I assume that is because I don't have a Coral) and it has binary sensors show up in Home Assistant and a separate camera feed for person detection. But my Garage camera, despite being setup the same way but with different settings for detecting cars, not people, it doesn't seem to work. 

The goal for me is to be able to use the detection of a car as part of the automation to close or open the garage door instead of it waiting on a timer that is longer than needed most of the time. Then we can pull in or out and the door closes as needed and we get the visual confirmation that the garage door will be closed as expected.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu

mqtt:
  # Required: host name
  host: 192.168.0.12
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: [REDACTED]
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: [REDACTED]
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60


cameras:
  # Name of your camera
  cam_frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://[REDACTED]@192.168.0.27/live
          roles:
            - detect
            - clips
            - rtmp
#    width: 1920
#    height: 1080
#    fps: 5
    motion:
      mask:
        - 1920,0,1920,1080,1798,961,1776,263,1517,0
    zones:
      front_stoop:
        coordinates: 842,1058,1512,1041,1435,271,874,274
    objects:
      filters:
        person:
          mask:
            - 772,1046,1820,1036,1647,191,800,185
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
#    clips:
#      enabled: true
#      retain:
#        default: 14

  cam_garage:
    ffmpeg:
      inputs:
        - path: rtsp://[REDACTED]@192.168.0.30:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - clips
            - rtmp
        - path: rtsp://[REDACTED]@192.168.0.30:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

#    width: 1920
#    height: 1080
    objects:
      filters:
        car:
          mask:
            - 647,1080,1920,1080,1292,164,692,203



record:
  # Optional: Enable recording
  enabled: true
  # Optional: Number of days to retain
  retain_days: 15


#clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
#  max_seconds: 600
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
#  tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
#  retain:
    # Required: Default retention days (default: shown below)
#    default: 9
    # Optional: Per object retention days
#    objects:
#      person: 15
#      car: 3


ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - "1"
```

### Relevant log output

```shell
N/a. No relevant logs about the garage camera
```

### FFprobe output from your camera

```shell
I would supply this information but Debian keeps intercepting the @ and assuming that it's a local system command, not a url with a username and password.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP2M-841B
