### ISSUE TITLE
Delete unused recordings every hour

### ISSUE THREAD

**Issue by philipp089** [blakeblackshear/frigate#2192]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to delete unused recordings every hour, basically it was working that way until the last update but now frigate records clips of 10 seconds all the time and will not delete unused recordings until i rebuild or restart frigate. 
I use the settings described here for non 24/7:
https://docs.frigate.video/configuration/record
I use frigate on a Raspberry Pi and the clips and recordings are saved to the SD-Card (which is limited in space obviously). So i run an RSync-Job daily from my NAS which moves the recordings at midnight to my NAS and deletes them from the media-folder in HA. This method worked quite good for the last weeks but since the last update, frigate just keeps all the 10-second-recordings and will not delete the recordings which are not used in Events. So it just spams my SD-Card.

**Describe the solution you'd like**
I would like to have a value in the frigate.yaml to set the time to an hour or so when frigate looks for unused recordings and deletes these.

**Describe alternatives you've considered**
Pushing them over with an RSync Job hourly, but that does not make sense because i have a bunch of irrelevant clips on my NAS then.

**Additional context**
Screenshot of my SD-usage
<img width="278" alt="sd_card" src="https://user-images.githubusercontent.com/66092908/140606779-7051c542-e11b-46d0-8f79-4a08401ac82f.png">
.

**Comment by blakeblackshear** [comment]
If your config is correct, unused recording segments are deleted every minute.

**Comment by philipp089** [comment]
```
#
# MQTT SETTINGS
#
mqtt:
  host: homeassistant
  port: 1883
  user: "frigate"
  password: "PW"
#
# CAMERA EINGANG
#
cameras:
  Eingang:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PW@IP/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:PW@IP
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 8
      max_disappeared: 32
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        retain:
          default: 0
    snapshots:
      enabled: true
      timestamp: False
      bounding_box: true
      crop: false
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
#
# CAMERA SCHLAFZIMMER
#
  Schlafzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PW@IP/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:PW@IP
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 8
      max_disappeared: 32
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        retain:
          default: 0
    snapshots:
      enabled: true
      timestamp: False
      bounding_box: true
      crop: false
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
#
# CAMERA WOHNZIMMER
#
  Wohnzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PW@IP/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:PW@IP
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 8
      max_disappeared: 32
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        retain:
          default: 0
    snapshots:
      enabled: true
      timestamp: False
      bounding_box: true
      crop: false
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
#
# OBJECTS TO TRACK
#
objects:
  track:
    - person
    - cat
#
# HARDWARE ACCELERATION
#
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
#
# CORAL TPU INTEGRATION
#
detectors:
  coral:
    type: edgetpu
    device: usb
```
