### ISSUE TITLE
[Support]: Recordings Spamming my drive 

### ISSUE THREAD

**Issue by maginator** [blakeblackshear/frigate#2195]
### Describe the problem you are having

Hi, 
I wonder why Frigate saves all recordings every hour although no events happen there. 
And every 10s there is a new file.
Is there a way to configure Frigate so that only the recordings for the events are saved and all others are deleted immediately?

### Version

0.9.4-26AE608

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: xxxxxxxxx
  port: 1883
  topic_prefix: frigate
cameras:
  raspicam_3:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: http://raspicam3.fritz.box/html/cam_pic_new.php?
          roles:
            - record
            - detect
            - clips
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v libx264 -an -f flv
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      filters:
        person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.4
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.6  
  
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.event: debug

record:
  enabled: true
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      objects:
        person: 15

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

motion:
  threshold: 20
  mask:
    - 981,0,977,74,536,76,534,0
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
Input #0, mpjpeg, from 'http://raspicam3.fritz.box/html/cam_pic_new.php?':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 512x288, 25 tbr, 25 tbn, 25 tbc
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

mjpeg Rasperry Pi Cam
