### ISSUE TITLE
[Support]: Frigate is not detecting objects to track i.e person car etc -- No events

### ISSUE THREAD

**Issue by phabeeo** [blakeblackshear/frigate#2202]
### Describe the problem you are having

First thank you for developing such an awesome tool. 
I am having issues with my frigate. I am unable to get real events but when I look into the recording I can clearly see that the object is there but Frigate for some reason is not sending any events.

I ran a test my self where I walked to my driveway and my BlueIris nvr detected me and send an event but Frigate did not send any event, just like if it did not see me as person. This is being very frequent and I am missing important events.

I need some assistant please

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.8
  user: userxxx
  password: xxx
  stats_interval: 60
ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  LivingRoomView:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:pass@192.168.100.240:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:pass@192.168.100.240:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
       width: 1280
       height: 720
       fps: 5
    objects:
      track:
        - person
        - cell phone
    record:
      enabled: False
      retain_days: 1
      events:
        max_seconds: 100
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
    snapshots:
      enabled: False
  OutsideDahuaView:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:pass@192.168.100.33:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:pass@192.168.100.33:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
       width: 1280
       height: 720
       fps: 5
    objects:
      track:
        - person
        - cell phone
        - car
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 100
        pre_capture: 5
        post_capture: 5
        retain:
          default: 0
        objects:
          - person
          - car
    snapshots:
      enabled: True
  GarageAmcrestView:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:pass@192.168.100.210:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:pass@192.168.100.210:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
       width: 1280
       height: 720
       fps: 5
    objects:
      track:
        - person
        - cell phone
        - car
    record:
      enabled: False
      retain_days: 3
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
    snapshots:
      enabled: False
```

### Relevant log output

```shell
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Device TypeDH-SD29204T-GN System Version2.640.0000000.2.R.T4.484.9A.NR, Build Date: 2018-09-28 WEB Version3.2.1.638252 ONVIF Version16.12(V2.4.3.574996) PTZ Version2.200.0000000.9.RHNVFJCB S/N4C0050DPAJE1AF3 Safe Baseline VersionV1.3 Copyright 2018, all rights reserved.

### Any other information that may be helpful

So the test i ran was to walk to my drive way and see if it will trigger an event. It didn't in Frigate but it did in BI
Screenshot below is from the recordings from the Dahua camera where the events stated 0

![frigatenoevent](https://user-images.githubusercontent.com/92824667/140786377-ca060a80-41ae-4927-9f57-f5fc984520cd.JPG)

This screenshot clearly showing that someone was in the direveway and I can see it from the frigate recordings but for some reason Frigate did not send any event
![frigatenoevent1](https://user-images.githubusercontent.com/92824667/140786638-2dc2f4a6-a0e8-404b-b752-7cb24a553533.JPG)

As proof, i also add the BI events
![bievent](https://user-images.githubusercontent.com/92824667/140786995-544c6def-5aac-44cc-bdcd-f98fa014f69b.JPG)
