### ISSUE TITLE
[Support]: Inconsistent Detection

### ISSUE THREAD

**Issue by TheRealAakash** [blakeblackshear/frigate#2203]
### Describe the problem you are having

I am trying to automate some lights using Frigate on unraid, but I am having an issue where if I am still for a while(about 60 seconds) frigate stops detecting me. I am using the camera: "Amcrest 4MP ProHD Indoor WiFi Camera"

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.3
  port: 1813
  user: user
  password: password
cameras:
  user_room:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 30
detectors:
  coral:
    type: edgetpu
    device: pci:0
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://user:password@192.168.1.27:554/live':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.001000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 2560x1440, 100 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wireless

### Camera make and model

amcrest, B095XCGKTF
