### ISSUE TITLE
[Support]: Trying to figure out how to detect and record objects in a zone

### ISSUE THREAD

**Issue by mlittle408** [blakeblackshear/frigate#2205]
### Describe the problem you are having

Have a look at my partial config below. In the "driveway" zone I want to detect people, dogs, and cars. In the "garage" zone I only want to detect people and dogs because that's where my cars are parked. The driveway zone will detect cars pulling in and out of my driveway so I don't need motion setting off a "car" trigger in the garage zone since that's where my cars are parked. The problem I am having is that no cars are being detected in the driveway zone. I tested it today and people are being detected but not cars. 

Here is my config:

  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.1.122:554/live
          roles:
            - detect
    motion:
      mask:
        - 392,197,496,227,874,235,959,0,0,0,0,335
        - 1518,244,1920,418,1920,0,1535,0
    zones:
      driveway:
        coordinates: 629,328,791,335,830,226,558,226,404,335
        objects:
          track:
            - car
            - person
            - dog
            - bicycle
      garage:
        coordinates: 1733,1080,1461,578,1165,348,279,339,0,486,0,1080
        objects:
          track:
            - dog
            - person
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 3

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.6
  user: homeassistant
  password: XXXX

cameras:

  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.1.230:554/live
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,755,317,484,750,193,909,147,1065,147,1060,0,0,0
        - 1920,1080,1233,1080,1332,0,1920,0
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 3

  back_porch:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.1.84:554/live
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 3

  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.1.122:554/live
          roles:
            - detect
    motion:
      mask:
        - 392,197,496,227,874,235,959,0,0,0,0,335
        - 1518,244,1920,418,1920,0,1535,0
    zones:
      driveway:
        coordinates: 629,328,791,335,830,226,558,226,404,335
        objects:
          track:
            - car
            - person
            - dog
            - bicycle
      garage:
        coordinates: 1733,1080,1461,578,1165,348,279,339,0,486,0,1080
        objects:
          track:
            - dog
            - person
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 3

#snapshots:
#  enabled: True
#  timestamp: True
#  bounding_box: True
#  retain:
#    default: 7

#objects:
#  track:
#    - person
#    - car
#    - dog
#    - bicycle

#record:
#  enabled: True
#  retain_days: 0
#  events:
#    retain:
#      default: 3

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p            

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

live:
  height: 720
  quality: 8
```

### Relevant log output

```shell
Not necessary
```

### FFprobe output from your camera

```shell
Not necessary
```

### Frigate stats

```json
Not necessary
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Wyze Cam 3

**Comment by blakeblackshear** [comment]
By default, only person objects are detected. You will need to add other object types to the objects config section. 
![image](https://user-images.githubusercontent.com/569905/140937767-79754d60-ded6-4c1a-bda0-592d7a02ecce.png)


Also, defining zones does not restrict which events are created. You will need to use the `required_zones` setting to restrict recordings.

**Comment by mlittle408** [comment]
Ok then maybe I need to ask a more direct question. How do a select a region in the camera where I DONT want cars to be detected?

**Comment by blakeblackshear** [comment]
You would set required_zones for snapshots and events similar to this guide: https://docs.frigate.video/guides/stationary_objects

Something like this:

```yaml
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.1.122:554/live
          roles:
            - detect
    motion:
      mask:
        - 392,197,496,227,874,235,959,0,0,0,0,335
        - 1518,244,1920,418,1920,0,1535,0
    zones:
      driveway:
        coordinates: 629,328,791,335,830,226,558,226,404,335
        objects:
          track:
            - car
            - person
            - dog
            - bicycle
      garage:
        coordinates: 1733,1080,1461,578,1165,348,279,339,0,486,0,1080
        objects:
          track:
            - dog
            - person
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      required_zones:
        - driveway
        - garage
      retain_days: 0
      events:
        retain:
          default: 3

```

You may also want to define an "all" zone that covers the remaining areas outside the zones that you want to include events from.
