### ISSUE TITLE
[Support]: Simple automation doesnt catch mqtt event

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#2218]
### Describe the problem you are having

automation doesnt catch mqtt event

```
- id: 'Frigate_frontdoor'
  alias: 'Frigate: frontdoor notification'

  trigger:
  - platform: mqtt
    topic: frigate/events
  condition: []

  action:
  - service: notify.telegram_bot
    data_template:
      message: "A {{trigger.payload_json['after']['label']}} was detected."
      data:
        photo:
        - url: http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json['after']['id']}}/thumbnail.jpg
          caption: "{{trigger.payload_json['after']['label']}} detected"

  - service: telegram_bot.send_message
    data:
      parse_mode: html
      keyboard: {}
      title: Frigate Event
      message: "{{trigger.event.data['args']}}"
```

### Version

Debug 0.9.4-26ae608

### Frigate config file

```yaml
#relevant part:
mqtt:
  # Required: host name
  host: core-mosquitto
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: passwd
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 30
```

### Relevant log output

```shell
#no
```

### FFprobe output from your camera

```shell
#no
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

#Not needed
