### ISSUE TITLE
[Support]: Telegram send video

### ISSUE THREAD

**Issue by geyles** [blakeblackshear/frigate#2234]
### Describe the problem you are having

Previously on frigate 8.4 sending video clips using
 http://ccab4aaf-frigate:5000/clips/{{trigger.payload_json["after"]["camera"]}}-{{trigger.payload_json["after"]["id"]}}.mp4
 This link worked a treat.

On frigate 9.4 using old link or this new one
          https://my_ha_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/clip.mp4

I just can't get it to work. The new link works in a browser and the HA log error message is
Can't send file with kwargs: {'message': 'Video of alert', 'url':

Can't load data into ByteIO: No connection adapters were found for "'https://******.com/api/frigate/notifications/********/garden/clip.mp4'"

### Version

0.9.4-26AE608

### Frigate config file

```yaml
N
```

### Relevant log output

```shell
N
```

### FFprobe output from your camera

```shell
N
```

### Frigate stats

```json
{"detection_fps":2.7,"detectors":{"coral":{"detection_start":1636664401.742706,"inference_speed":19.36,"pid":215}},"frontdoor":{"camera_fps":10.0,"capture_pid":228,"detection_fps":1.5,"pid":219,"process_fps":10.0,"skipped_fps":0.0},"garden":{"camera_fps":15.0,"capture_pid":230,"detection_fps":0.0,"pid":224,"process_fps":15.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":63.5,"mount_type":"tmpfs","total":67.1,"used":3.6},"/media/frigate/clips":{"free":237047.7,"mount_type":"ext4","total":251881.1,"used":4571.0},"/media/frigate/recordings":{"free":237047.7,"mount_type":"ext4","total":251881.1,"used":4571.0},"/tmp/cache":{"free":998.9,"mount_type":"tmpfs","total":1000.0,"used":1.1}},"uptime":88536,"version":"0.9.4-26ae608"},"work":{"camera_fps":11.7,"capture_pid":234,"detection_fps":1.2,"pid":227,"process_fps":11.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Imou

### Any other information that may be helpful

Home assistant is on a intel nuc windows virtual box, frigate raspberry pi 4 docker compose with usb coral.

Previous versions of frigate allowed me to send video via telegram

**Comment by blakeblackshear** [comment]
Have you updated to the latest version of the integration? https://github.com/blakeblackshear/frigate-hass-integration/releases

**Comment by geyles** [comment]
Yes definitely

**Comment by KuRue** [comment]
This config seems to work for me on 9.4

```
alias: Frigate Events Frontdoor
description: ''
trigger:
  - platform: mqtt
    topic: /events
condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''after''][''area''] > 20000 }}'
  - condition: template
    value_template: '{{ trigger.payload_json[''after''][''camera''] == "frontdoor" }}'
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 45
      milliseconds: 0
  - service: notify.telegram_video
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected.
      data:
        video:
          - url: https://HA_ADDRESS/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
            timeout: 1000
            caption: Event ID {{trigger.payload_json["after"]["id"]}}
mode: single
```
