### ISSUE TITLE
How to set the correct path to Coral TPU

### ISSUE THREAD

**Issue by cegit55** [blakeblackshear/frigate#2255]
### Describe the problem you are having

Good evening,

If I run Home Assistant and Frigate on my main machine, and I have an M.2 Coral installed on a second machine, how do I tell Frigate where the Coral is located?

Many thanks.

### Version

0.8.4-5043040

### Frigate config file

```yaml
detectors:
  coral_pci:
    type: edgetpu
    device: pci
    device_path:
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Various
