### ISSUE TITLE
[Support]: Static Images on Four Dahua Cameras (Intel i7 QS with Coral USB)

### ISSUE THREAD

**Issue by cjoha** [blakeblackshear/frigate#2259]
### Describe the problem you are having

My four Dahua (4K) cameras are setup in Frigate, using their direct rtsp feeds (tested locally using VLC and not going via my dhaua NVR). For the moment I am only looking for detection, and not a recording function (I have that on my Dahua NVR box). But what I see on Frigate is a static image, the timestamp in the image itself is not incrementing, either live or on refresh of the page.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: [removed]
  user: [removed]
  password: [removed]

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

cameras:
  bins-alley: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:[removed]@[removed]:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          hwaccel_args: -hwaccel qsv
          roles:
            - detect
      hwaccel_args:
        - -c:v
        - h264_qsv
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
      fps: 14

  garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:[removed]@[removed]:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          hwaccel_args: -hwaccel qsv
          roles:
            - detect
      hwaccel_args:
        - -c:v
        - h264_qsv
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
      fps: 14


  bbq_alley: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:[removed]@[removed]:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          hwaccel_args: -hwaccel qsv
          roles:
            - detect
      hwaccel_args:
        - -c:v
        - h264_qsv
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
      fps: 14

  driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:[removed]@[removed]:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          hwaccel_args: -hwaccel qsv
          roles:
            - detect
      hwaccel_args:
        - -c:v
        - h264_qsv
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
      fps: 14
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
ffprobe rtsp://[removed]:[removed]@[removed]:554
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://[removed]:[removed]@[removed]:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 14 fps, 100 tbr, 90k tbn, 28 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{"bbq_alley":{"camera_fps":0.84,"capture_pid":250,"detection_fps":0.0,"pid":231,"process_fps":0.8,"skipped_fps":0.0},"bins-alley":{"camera_fps":1.26,"capture_pid":243,"detection_fps":0.0,"pid":222,"process_fps":1.23,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":217}},"driveway":{"camera_fps":8.82,"capture_pid":254,"detection_fps":0.0,"pid":236,"process_fps":8.75,"skipped_fps":0.0},"garden":{"camera_fps":2.31,"capture_pid":246,"detection_fps":0.0,"pid":227,"process_fps":2.28,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":12.5,"mount_type":"tmpfs","total":67.1,"used":54.6},"/media/frigate/clips":{"free":44168.5,"mount_type":"zfs","total":53687.1,"used":9518.6},"/media/frigate/recordings":{"free":44168.5,"mount_type":"zfs","total":53687.1,"used":9518.6},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"uptime":137,"version":"0.9.4-26ae608"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua HDW5831R

**Comment by blakeblackshear** [comment]
You have added two different hwaccel_args for each camera. Only the most granular one will be applied. I would suggest starting with a single camera and adding the others once you get that working. Have you read the [camera setup guide](https://docs.frigate.video/guides/camera_setup)? You may have special requirements, but the resolution and fps are much higher than the recommended values.

**Comment by cjoha** [comment]
Thanks for the feedback Blake. I've done the following:

1. Changed Dahua encoding (Stream2) to 1280 x 720 at 5fps, and adjusted the Frigate config to pull from Stream2.
2. Removed the `ffmpeg` object from below the `detectors:` object
3. Removed the secondary `hwaccel_args` (duplicate entry) in the camera entities.
4. Removed the other cameras for the moment, focussing on one.

With this in place, I've got the liveView working as expected. But as soon as I add any more than one camera the others come up with a green screen. So the new config.yaml is as below:

```
mqtt:
  host: [removed]
  user: [removed]
  password: [removed]

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  bins-alley: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://[removed]:[removed]@[removed]:554/cam/realmonitor?channel=1&subtype=2 # <----- Update for your camera
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
```
