### ISSUE TITLE
[Support]:  Timestamp style doesnt seem to do much

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#2260]
### Describe the problem you are having

when i change settings in timestamp_style, global or per camera, nothing changes. 

### Version

 0.10.0-B912851

### Frigate config file

```yaml
timestamp_style:
      # Optional: Position of the timestamp (default: shown below)
      #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
      position: "tl"
      # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
      #           Additional Examples:
      #             german: "%d.%m.%Y %H:%M:%S"
      format: "%d/%m/%Y %H:%M:%S TEST"
      # Optional: Color of font
      color:
        # All Required when color is specified (default: shown below)
        red: 255
        green: 255
        blue: 255
      # Optional: Line thickness of font (default: shown below)
      thickness: 2
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
{
back: {
camera_fps: 5,
capture_pid: 240,
detection_fps: 25.1,
pid: 235,
process_fps: 4.9,
skipped_fps: 0
},
detection_fps: 25.1,
detectors: {
coral: {
detection_start: 1637070488.924796,
inference_speed: 8.31,
pid: 226
}
},
front: {
camera_fps: 5.1,
capture_pid: 237,
detection_fps: 0,
pid: 232,
process_fps: 5.1,
skipped_fps: 0
},
service: {
storage: {
/dev/shm: {
free: 3201.8,
mount_type: "tmpfs",
total: 3221.2,
used: 19.4
},
/media/frigate/clips: {
free: 119586.8,
mount_type: "ext4",
total: 3936911.9,
used: 3617269
},
/media/frigate/recordings: {
free: 119586.8,
mount_type: "ext4",
total: 3936911.9,
used: 3617269
},
/tmp/cache: {
free: 7268.7,
mount_type: "ext4",
total: 117608.4,
used: 104321.4
}
},
uptime: 259,
version: "0.10.0-b912851"
}
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

REOLINK 410 / 520
