### ISSUE TITLE
[Support]: Stationary object detection does not seem to work

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#2261]
### Describe the problem you are having

there are currently two cars parked in my driveway. Frigate is not detecting them, only If they move.

### Version

0.10.0-B912851

### Frigate config file

```yaml
cameras:
  front:
    detect:
      width: 2560
      height: 1920
      fps: 5

    zones:
      voordeur:
        coordinates: 2560,1920,2560,1836,2085,901,1365,984,1471,1920
      autosam:
        coordinates: 984,119,821,22,590,0,389,99,307,243,167,579,260,1445,1143,1451
    motion:
      mask:
        - 2560,1920,2560,1613,2560,0,1738,0,1972,408
      
    mqtt:
      bounding_box: True
    
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -rw_timeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac

      
      inputs:
        - path: 
          roles:
            - record
            - detect
            - rtmp


  
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True

####
objects:

  track:
    - car
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink 410 and 520
