### ISSUE TITLE
[Support]: Starting Frigate Addon

### ISSUE THREAD

**Issue by pajstar** [blakeblackshear/frigate#2274]
### Describe the problem you are having

I currently unable to start the Frigate NVR addon. When I press start nothing happens. When I install another addon version of Frigate such as Frigate NVR (Full Access) I get the error message  "Port '5000' is already in use by something else on the host."

### Version

2.3

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: HIDE
  password: HIDE
  stats_interval: 60
cameras:
  front_door:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: HIDE
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
```

### Relevant log output

```shell
WARNING (MainThread) [supervisor.addons.addon] ccab4aaf_frigate is already running!
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Wyze

### Any other information that may be helpful

I had Frigate running and for some reason it is not working.
