### ISSUE TITLE
[Support]: Detection FPS seems to be ignored

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#2276]
### Describe the problem you are having

hi there. i set the detection fps to 5 for all my camera's, but according to /api/stats I am running 30fps on one.

### Version

0.10.0-B912851

### Frigate config file

```yaml
#camera in question is public and not owned by me:

  test3:
    detect:
      max_disappeared: 100
      # Optional: Frequency for running detection on stationary objects (default: 10x the frame rate)
      stationary_interval: 50
      width: 800
      height: 600
      fps: 5

    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid

      
      inputs:
        - path: "rtsp://85.0.230.94/axis-media/media.amp"
          roles:
            - record
            - detect
            - rtmp
      hwaccel_args: -c:v h264_cuvid            
     

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{
back: {
camera_fps: 5.1,
capture_pid: 255,
detection_fps: 8.2,
pid: 241,
process_fps: 4.1,
skipped_fps: 0
},
detection_fps: 87.3,
detectors: {
coral: {
detection_start: 1637238403.426511,
inference_speed: 8.99,
pid: 224
}
},
front: {
camera_fps: 5.1,
capture_pid: 251,
detection_fps: 20.9,
pid: 239,
process_fps: 5.1,
skipped_fps: 0
},
service: {
storage: {
/dev/shm: {
free: 3193,
mount_type: "tmpfs",
total: 3221.2,
used: 28.2
},
/media/frigate/clips: {
free: 110607.4,
mount_type: "ext4",
total: 117612,
used: 986.2
},
/media/frigate/recordings: {
free: 110607.4,
mount_type: "ext4",
total: 117612,
used: 986.2
},
/tmp/cache: {
free: 110607.4,
mount_type: "ext4",
total: 117612,
used: 986.2
}
},
uptime: 320,
version: "0.10.0-b912851"
},
test: {
camera_fps: 5.1,
capture_pid: 242,
detection_fps: 14,
pid: 233,
process_fps: 5.1,
skipped_fps: 0
},
test2: {
camera_fps: 5.1,
capture_pid: 243,
detection_fps: 0,
pid: 235,
process_fps: 5.1,
skipped_fps: 0
},
test3: {
camera_fps: 5.1,
capture_pid: 245,
detection_fps: 30.8,
pid: 236,
process_fps: 4.6,
skipped_fps: 0
},
test4: {
camera_fps: 5.1,
capture_pid: 249,
detection_fps: 13.4,
pid: 237,
process_fps: 5.1,
skipped_fps: 0
}
}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

unknown

### Any other information that may be helpful

ubuntu 20.04 server LTS
