### ISSUE TITLE
[Support]: esphome esp32_camera_web_server

### ISSUE THREAD

**Issue by lahayeg** [blakeblackshear/frigate#2277]
### Describe the problem you are having

Not able to activate esphome cam. Looking for someone configuration that's working.

https://github.com/esphome/esphome/releases/tag/2021.11.0
https://esphome.io/components/esp32_camera_web_server.html

### Version

2.3

### Frigate config file

```yaml
ffmpeg:
      inputs:
        - path: http://192.168.4.16:8080
          hwaccel_args: -c:v h264_v4l2m2m
          input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
          roles:
            - detect
    detect:
      width: 640
      height: 480
```

### Relevant log output

```shell
[2021-11-18 16:36:52] watchdog.chicken               ERROR   : FFMPEG process crashed unexpectedly for chicken.
[2021-11-18 16:36:52] watchdog.chicken               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-11-18 16:36:52] watchdog.chicken               ERROR   : You may have invalid args defined for this camera.
[2021-11-18 16:36:52] ffmpeg.chicken.detect          ERROR   : [h264 @ 0x5571fbaa10] A non-intra slice in an IDR NAL unit.
[2021-11-18 16:36:52] ffmpeg.chicken.detect          ERROR   : [h264 @ 0x5571fbaa10] decode_slice_header error
[2021-11-18 16:36:52] ffmpeg.chicken.detect          ERROR   : [h264 @ 0x5571fbaa10] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mpjpeg, from 'http://192.168.4.16:8080':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 25 tbr, 25 tbn, 25 tbc
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

M5Stack esp32cam + esphome

**Comment by corgan2222** [comment]
I think the ESP32 Cam can't send a h264 stream. Instead, it delivers mostly  a mjpg stream. 
Look here for the correct config: https://docs.frigate.video/configuration/camera_specific

**Comment by lahayeg** [comment]
@corgan2222 just removed line (and update input_args with MJPEG Cameras of your link)
`hwaccel_args: -c:v h264_v4l2m2m`

in camera configuration and now get

[2021-11-18 21:43:32] watchdog.chicken               ERROR   : FFMPEG process crashed unexpectedly for chicken.
[2021-11-18 21:43:32] watchdog.chicken               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-11-18 21:43:32] watchdog.chicken               ERROR   : You may have invalid args defined for this camera.
[2021-11-18 21:43:32] ffmpeg.chicken.detect          ERROR   : [flv @ 0x55b4432e60] Video codec mjpeg not compatible with flv
[2021-11-18 21:43:32] ffmpeg.chicken.detect          ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
[2021-11-18 21:43:32] ffmpeg.chicken.detect          ERROR   :

**Comment by corgan2222** [comment]
```
input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
```

and

```
output_args:
  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
  rtmp: -c:v libx264 -an -f flv
```

if this not works, try to detect what your esp32-cam return.
https://ffmpeg.org/ffprobe.html

**Comment by lahayeg** [comment]
@corgan2222 , seems to work (at least no more green screen in UI). One think I'm not understand is why I need to set this output_args as I'm only using detect role.
For thus who would like full esphome cam config:
`  chicken:
    ffmpeg:
      inputs:
        - path: http://192.168.4.16:8080
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 640
      height: 480
      fps: 25`

**Comment by lahayeg** [comment]
Able to create clips. E2E test OK. Closing

**Comment by blakeblackshear** [comment]
If you don't want to use RTMP, you can disable in the config to reduce CPU usage.

**Comment by Tokn59** [comment]
> @corgan2222 , seems to work (at least no more green screen in UI). One think I'm not understand is why I need to set this output_args as I'm only using detect role. For thus who would like full esphome cam config: ` chicken: ffmpeg: inputs: - path: http://192.168.4.16:8080 roles: - detect input_args: - -avoid_negative_ts - make_zero - -fflags - nobuffer - -flags - low_delay - -strict - experimental - -fflags - +genpts+discardcorrupt - -use_wallclock_as_timestamps - "1" output_args: detect: -f rawvideo -pix_fmt yuv420p record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an rtmp: -c:v libx264 -an -f flv detect: width: 640 height: 480 fps: 25`

Could you please share tyhe exacv yaml code ? Formatting is not so clear to me. Thank You !!!

**Comment by Tokn59** [comment]
Hi, I have tried about every possible configuration as described here. However I still cannot get past the "green screen". The camera is working just fine via http://192.168.1.218 - It DOES NOT give anything when using **http://192.168.1.218**:8080****

What firmware do you use for the ESP32_CAM ?
Do you manually start Stream using the camera's interface or not ?

Thanks for ALL YOUR HELP !!!!

**Comment by lahayeg** [comment]
@Tokn59 I use esp32_cam through esphome like this
```yaml
esphome:
  name: $devicename
  platform: ESP32
  board: m5stack-core-esp32
  arduino_version: 1.0.5
esp32_camera:
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15

  # Image settings
  name: Chicken house

esp32_camera_web_server:
  - port: 8080
    mode: stream
```

**Comment by Tokn59** [comment]
GREAT ! Thanks for sharing !!! Just flashed the device but still have the "green screen". Would you mind sharing your exacv frigate.yml entries for this configuration ?

BIG BIG THANKS !!!

**Comment by lahayeg** [comment]
@Tokn59 my esphome config is specific to my board. You should refer to https://esphome.io/components/esp32_camera.html first and check that cam is working fine in standalone.

Once done, here is my frigate.yml
```yaml
mqtt:
  ... place 

detectors:
  #  coral:
  #    type: edgetpu
  #    device: usb
    cpu1:
      type: cpu
    cpu2:
      type: cpu
birdseye:
    enabled: False
rtmp:
    enabled: False
live:
  height: 240
  quality: 8
cameras:
  chicken:
    ffmpeg:
      inputs:
        - path: http://192.168.4.16:8080
          roles:
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 640
      height: 480
      fps: 25
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      retain:
        default: 2

```
