### ISSUE TITLE
Ability to save image at interval or at given time.. 

### ISSUE THREAD

**Issue by Minglarn** [blakeblackshear/frigate#2279]
**Describe what you are trying to accomplish and why in non technical terms**
Possibility to make cameras save snapshot images at given time/time periods.

**Describe the solution you'd like**
A simple yaml parameter would be nice. 
like for timelaps mode: 
```
snapshots:
...
  timelaps:
    time_interval:
      interval: 5m
      retain:
        default: 30days
        timestamp: true
```
or at given time...
```
snapshots:
...
  timelaps:
    time_set:
      time: 12:00
      retain:
        default: 30days
        timestamp: true
```
**Describe alternatives you've considered**
I've been consider doing this via HA, but as I dont have RTMP enabled this wont work...
Would be great to make this as a parameter in frigate instead.
