### ISSUE TITLE
Coral USB detected, but coral FPS remains 0

### ISSUE THREAD

**Issue by jasonmadigan** [blakeblackshear/frigate#228]
**Describe the bug**
Trying `dev` for the first time in a while, with a Coral USB. Seeing two oddities, may be related:

* coral FPS in `/debug/stats` is zero, detection doesn't seem to be working. The Coral seems to be working (e.g.  no error about edgeTPU missing or falling back to CPU in logs).
* When monitoring the debug stream, it usually freezes after a few moments

**Version of frigate**
Latest `:dev` container

**Config file**
Include your full config file wrapped in back ticks.
```
web_port: 5000
tensorflow_device: usb

mqtt:
  host: 192.168.1.230
  topic_prefix: frigate
  user: xxx
  password: xxx

save_clips:
  max_seconds: 300

objects:
  track:
    - person
    - car
    - truck

cameras:
  gate:
    ffmpeg:
      input: rtsp://XXX:XXX@192.168.1.151:554/Streaming/Channels/2/
```

**Logs**
```
Waiting for detection process to exit gracefully...
Starting detection process: 496
On connect called
On connect called
On connect called
On connect called
On connect called
On connect called
On connect called
On connect called
On connect called
On connect called
Detection appears to be stuck. Restarting detection process
Waiting for detection process to exit gracefully...
Starting detection process: 505
```

**Frigate debug stats**
```
{
  "coral":{
    "detection_start":1602349906.435945,
    "fps":0.0,
    "inference_speed":21.59,
    "pid":276
  },
  "gate":{
    "camera_fps":15.0,
    "detection_fps":0.0,
    "ffmpeg_pid":90,
    "frame_info":{
      "detect":1602349876.601842,
      "process":1602349876.531927,
      "read":1602349911.53208
    },
    "pid":92,
    "process_fps":0.1,
    "read_start":0.0,
    "skipped_fps":15.0
  },
  "plasma_store_rc":null
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: unraidOS
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: -
 - Resolution: 8MP 4k
 - FPS: 15

**Additional context**
