### ISSUE TITLE
[Support]: Frigate does not "create" entities for objects detected anymore

### ISSUE THREAD

**Issue by Tokn59** [blakeblackshear/frigate#2284]
### Describe the problem you are having

It seems to me that in previous releases (I am running 2.3 now) entities were created for every object. I do not see these entities anymore. Are we supposed to now handle this via MQTT ? 

### Version

2.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.163
  port: 1883
  topic_prefix: homeassistant
  client_id: frigate
  user: els
  password: xxxxxxxxxxxx
  stats_interval: 60
#--------------------------------------------------------------------------------------------------------  
cameras:
  Lounge:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxx@192.168.1.122:554
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720   
    objects:
      track:
        - person
        - cat
        - bird
        - motorcycle  
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 1
        max_seconds: 300
        pre_capture: 5
        post_capture: 5 
#--------------------------------------------------------------------------------------------------------  
  Berging:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxx@192.168.1.200:554/Streaming/channels/1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 20
    objects:
      track:
        - person
        - cat
        - bird
        - motorcycle
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 1
        max_seconds: 300
        pre_capture: 5
        post_capture: 5 
#--------------------------------------------------------------------------------------------------------  
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
#--------------------------------------------------------------------------------------------------------  
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Camera override for retention settings (default: global values)
#  retain:
    # Required: Default retention days (default: shown below)
#    default: 3
    # Optional: Per object retention days
#    objects:
#      person: 3
#      dog: 3
#      cat: 3
#      car: 3
#      bicycle: 3
#-----------------------------------------------------------------------------------------------------------------------    
#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
```

### Relevant log output

```shell
Not applicable
```

### FFprobe output from your camera

```shell
Not applicable
```

### Frigate stats

```json
Not applicable
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Digoo, Hikvision ...
