### ISSUE TITLE
[Support]: Frigate add-on in home assistant not running

### ISSUE THREAD

**Issue by cwleth** [blakeblackshear/frigate#2294]
### Describe the problem you are having

Hi,

I have previously run frigate very well and all has worked fine with my 4 cameras via Home Assistant. I have had a pause using Home Assistant for about 6 months, and now after I have updated both core, supervisor and all add-ons - frigate has suddenly stopped working. I am running a HA OS install on an Intel NUC with a coral USB stick and I have Frigate NVR add-on v. 2.3 & Frigate NVR Custom Component v2.1.0 installed via HACS.

I have tried to uninstall and re-install both add-on and integration, and done countless restarts without luck. When I click the open web-UI, 1 in 10 times it shows the frigate top bar/menu and the loading symbol in the center of the window - but nothing happens (if I then go somewhere else, and then back, it's just black screen), 1 in 10 times it also just show a black screen with "502: Bad Gateway" in the top-left corner. the rest 8 in 10 times it's just a black empty screen.

It seems as when I restart the add-on, the CPU & RAM usage goes up for a couple of seconds during the start, and then just go to zero.

The log shows:

![image](https://user-images.githubusercontent.com/78813007/142740442-0288f2ae-bae7-491d-ad1b-a7650e9a830a.png)

### Version

Frigate NVR add-on v. 2.3 & Frigate NVR Custom Component v2.1.0 installed via HACS 

### Frigate config file

```yaml
mqtt:
  host:
  user:
  password:

cameras:
  Gardhave:
    ffmpeg:
      inputs:
        - path:
          roles:
            - detect
            - rtmp
            - clips
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 3
    clips:
      enabled: True
      retain:
        default: 3
    motion:
      mask:
        - 519,124,938,137,1247,173,1920,333,1920,0,158,0,169,197,276,160
        - 655,1001,822,1003,819,951,651,953
  Indkorsel:
    ffmpeg:
      inputs:
        - path:
          roles:
            - detect
            - clips
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 3
    clips:
      enabled: True
      retain:
        default: 3
    motion:
      mask:
        - 0,473,534,332,1016,232,1529,180,1539,0,0,0
        - 602,1035,865,1038,867,983,600,982
  Have:
    ffmpeg:
      inputs:
        - path:
          roles:
            - detect
            - clips
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 3
    clips:
      enabled: True
      retain:
        default: 3
    motion:
      mask:
        - 552,971,823,974,820,918,554,918
  Doorbird:
    ffmpeg:
      inputs:
        - path:
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 3
    clips:
      enabled: True
      retain:
        default: 3
    motion:
      mask:
        - 0,0,1280,0,1280,313,947,353,949,462,550,514,0,514


ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for clips streams (default: shown below)
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
```

### Relevant log output

```shell
Timeout error fetching information from http://ccab4aaf-frigate:5000/api/stats:
9:45:30 PM – (ERROR) Frigate (custom integration) - message first occurred at 9:19:57 PM and shows up 7 times
Can't read Supervisor data: Container addon_ccab4aaf_frigate is not running
9:44:59 PM – (WARNING) Home Assistant Supervisor - message first occurred at 9:19:46 PM and shows up 5 times
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.7', 5000)]
9:44:00 PM – (ERROR) Frigate (custom integration) - message first occurred at 9:20:02 PM and shows up 15 times
Failed to to call /addons/ccab4aaf_frigate/stats - Container addon_ccab4aaf_frigate is not running
9:43:26 PM – (ERROR) Home Assistant Supervisor - message first occurred at 9:20:48 PM and shows up 4 times
```

### FFprobe output from your camera

```shell
Not relevant - cameras and feed are not the issue.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Hikvision

### Any other information that may be helpful

Really appreciate your work and hope I can be back up running soon :-)
