### ISSUE TITLE
[Support]: Don't die when trying to delete a recording from a missing dir

### ISSUE THREAD

**Issue by tve** [blakeblackshear/frigate#2295]
### Describe the problem you are having

When deleting a recording the call to `unlink` has `missing_ok=True`, but that doesn't seem to handle missing intermediate directories. I had a filesystem full situation and deleted a pile of old recording days to make space. Now frigate freaks out each time it tries to prune a recording file, so I have to go back and create a ton of empty dirs. Would be nice to wrap a try-except block around this.

### Version

0.10.0

### Frigate config file

```yaml
mqtt:
  host: core.voneicken.com
  user: frigate
  password: f607ef782c520ccd75ce772f27e38716

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"
record:
  enabled: True
  retain_days: 1
  events:
    retain:
      default: 30
snapshots:
  enabled: True
  timestamp: True
  height: null
  retain:
    default: 120
rtmp:
  enabled: False

cameras:
  gate:
    ffmpeg:
      inputs:
        - path: rtsp://phycam.voneicken.com/live/1/h264.sdp
          roles: [ detect, record]
      input_args: [
        -avoid_negative_ts, make_zero, -use_wallclock_as_timestamps, "1", -stimeout, "5000000",
        -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt,
        ]
    detect:
      width: 768
      height: 432
      fps: 4
    timestamp_style:
      position: "bl"
    motion:
      mask:
        - 768,0,581,0,544,152,540,432,768,432
    zones:
      inside:
        coordinates: 501,432,530,259,0,177,0,432
      outside:
        coordinates: 197,67,607,93,590,264,180,204
    record:
      retain_days: 4
    objects:
      track: [ 'person', 'car', 'dog', 'cat', 'sheep', 'bycicle', 'motorcycle', 'truck', 'bus' ]

  # rpi-cam2 -- rPi3a+imx462-based camera 1920x1080
  birdbath:
    ffmpeg:
      inputs:
        - path: rtsp://rpi-cam2.voneicken.com:8554/cam5fps
          roles: [ detect, record ]
      input_args: [
        -avoid_negative_ts, make_zero, -use_wallclock_as_timestamps, "1", -stimeout, "5000000",
        -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt,
        ]
    detect:
      width: 1920
      height: 1080
      fps: 5
    timestamp_style:
      position: "bl"
    motion:
      #threshold: 20  # default is 25, pixel value delta to detect motion
      #delta_alpha: 0.15  # default is 0.2
      #frame_alpha: 0.15  # default is 0.2
      contour_area: 50  # default is 100, misses hummingbirds
      mask:
        - 1468,0,1920,0,1920,198,1468,172
    record:
      retain_days: 3
    objects:
      track: [ 'bird', 'cat', 'dog', 'sheep' ]

  cam5:
    ffmpeg:
      inputs:
        - path: http://esp32-cam5.voneicken.com:81
          roles: [ detect, record ]
      input_args: [ -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt, -use_wallclock_as_timestamps, "1" ]
      output_args:
        record:
          -f segment -segment_time 60 -segment_format mp4 -segment_atclocktime 1 -g 10
          -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 2 -an
      #  rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 2 -an -f flv
    detect:
      width: 1280
      height: 720
    objects:
      track: [ 'person', 'bird', 'cat', 'dog', 'sheep' ]

  cam8:
    ffmpeg:
      inputs:
        - path: http://esp32-cam8.voneicken.com:81
          roles: [ detect, record ]
      input_args: [ -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt, -use_wallclock_as_timestamps, "1" ]
      output_args:
        record:
          -f segment -segment_time 60 -segment_format mp4 -segment_atclocktime 1 -g 10
          -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 2 -an
      #  rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 2 -an -f flv
    detect:
      width: 1280
      height: 720
    objects:
      track: [ 'person', 'bird', 'cat', 'dog', 'sheep' ]

  rodentcam:
    ffmpeg:
      inputs:
        - path: http://esp32-cam6.voneicken.com:81
          roles: [ detect, record ]
      input_args: [ -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt, -use_wallclock_as_timestamps, "1" ]
      output_args:
        record:
          -f segment -segment_time 60 -segment_format mp4 -segment_atclocktime 1 -g 10
          -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 2 -an
      #  rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 2 -an -f flv
    detect:
      width: 1024
      height: 768
    objects:
      track: [ 'person', 'bird', 'cat', 'dog', 'sheep' ]
      filters:
        bird:
          threshold: 0.8

  studio:
    ffmpeg:
      inputs:
        - path: http://esp32-cam2.voneicken.com:81
          roles: [ detect, record ]
      input_args: [ -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt, -use_wallclock_as_timestamps, "1" ]
      output_args:
        record:
          -f segment -segment_time 60 -segment_format mp4 -segment_atclocktime 1 -g 10
          -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 2 -an
      #  clips: -f segment -segment_time 10 -segment_format mp4 -g 10 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 2 -an
      #  rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 2 -an -f flv
    detect:
      width: 1024
      height: 768
    objects:
      track: [ 'person', 'bird', 'cat', 'dog', 'sheep' ]

  overview:
    ffmpeg:
      inputs:
        - path: http://esp32-cam3.voneicken.com:81
          roles: [ detect, record ]
      input_args: [ -fflags, nobuffer, -flags, low_delay, -strict, experimental, -fflags, +genpts+discardcorrupt, -use_wallclock_as_timestamps, "1" ]
      output_args:
        record:
          -f segment -segment_time 60 -segment_format mp4 -segment_atclocktime 1 -g 10
          -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 30 -vf format=nv12,hwupload -r 1 -an
      #  clips: -f segment -segment_time 10 -segment_format mp4 -g 10 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -qp 28 -vf format=nv12,hwupload -r 1 -an
      #  rtmp: -c:v h264_vaapi -vf format=nv12,hwupload -r 1 -an -f flv
    detect:
      width: 1600
      height: 1200
    motion:
      threshold: 30
      delta_alpha: 0.15
      mask:
        - 0,1200,1600,1200,1266,776,1093,830,917,782,772,717,669,797,519,843,320,690,0,685
        #- 0,1024,1280,1024,1280,888,980,643,914,708,701,631,586,664,419,736,272,582,0,682
    objects:
      track: [ 'person', 'bird', 'cat', 'dog', 'sheep' ]
      filters:
        person:
          min_area: 2000
        bird:
          min_area: 2000
        cat:
          min_area: 2000
        dog:
          min_area: 2000
        sheep:
          min_area: 2000

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  #cpu1:
    #type: cpu
```

### Relevant log output

```shell
Exception in thread recording_cleanup:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/record.py", line 424, in run
    self.expire_files()
  File "/opt/frigate/frigate/record.py", line 408, in expire_files
    if p.stat().st_mtime < delete_before.get(p.parent.name, default_expire):
  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/media/frigate/recordings/2021-11/19/14/birdbath/45.38.mp4'
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
