### ISSUE TITLE
[Support]: Recording files only 10 seconds long

### ISSUE THREAD

**Issue by sirjeannot** [blakeblackshear/frigate#2300]
### Describe the problem you are having

Hello,
I'm wondering if it is possible to extend the default duration for recording on files. It creates hunreds of files only 12 seconds long. The idea is to have recordings up to an x minutes/hours long for continuous recording, independently from detection.
My setup currently has 0 issues, so it's just a question to make manual events lookup less a hassle to open hundreds of files.
Thanks!
![image](https://user-images.githubusercontent.com/9054080/142765140-a28db2c4-892f-453a-b614-d533b7bc8fe8.png)
 edit: I searched for existing info, but didn't find anything. Wrong keywords maybe.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
cameras:
  camera_parking:
    ffmpeg:
      inputs:
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_PARKING_IP}:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_PARKING_IP}:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    detect:
      width: 720
      height: 480
      fps: 5
    record:
      enabled: True
      retain_days: 7
      events:
#        required_zones:
#          - parking
        retain:
          default: 21
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 7
        objects:
          person: 15
    objects:
      track:
        - person
        - cat
        - dog
    motion:
      mask:
        - 499,101,330,145,276,89,0,139,0,0,517,0,720,0,720,254
    zones:
      parking:
        coordinates: 720,480,550,480,432,297,60,320,56,204,381,146,492,137,720,250
        objects:
          - person
```

### Relevant log output

```shell
no issue so nothing to report
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"camera_parking":{"camera_fps":5.0,"capture_pid":228,"detection_fps":0.0,"pid":223,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.1,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":125.72,"pid":217}},"service":{"storage":{"/dev/shm":{"free":64.0,"mount_type":"tmpfs","total":67.1,"used":3.1},"/media/frigate/clips":{"free":188185.3,"mount_type":"ext4","total":235214.4,"used":47012.3},"/media/frigate/recordings":{"free":188185.3,"mount_type":"ext4","total":235214.4,"used":47012.3},"/tmp/cache":{"free":993.1,"mount_type":"tmpfs","total":1000.0,"used":6.9}},"uptime":1083,"version":"0.9.1-800f33e"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW1531S

### Any other information that may be helpful

still no Coral due to current shortages 😪
