### ISSUE TITLE
Example camera configuration yaml request

### ISSUE THREAD

**Issue by clockworkant** [blakeblackshear/frigate#2314]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see what a configuration file looks like that has the setup described in the example camera configuration. https://docs.frigate.video/guides/camera_setup#example-camera-configuration. Specifically, how to configure different streams for different purposes.

**Describe the solution you'd like**
On this document page could you provide an example configuration file.

**Describe alternatives you've considered**
I've read most the documentation and searched the github issues but couldn't see an obvious example. I also looked online however most guides only detail the most basic of setups.

**Additional context**
The setup with the resolutions and fps in the example camera configuration sounds great. I can't tell if I'm supposed to make multiple camera entries (Recording Cam, Detect Cam, RTMP cam), or if I make one camera entry and specify the configuration of the camera in the role entity.

**Comment by blakeblackshear** [comment]
```yaml
cameras:
  back:
    ffmpeg:
      inputs: 
        - path: rtsp://viewer:{FRIGATE_CAMERA_PASSWORD}@10.0.10.11:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://viewer:{FRIGATE_CAMERA_PASSWORD}@10.0.10.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
        - path: rtsp://viewer:{FRIGATE_CAMERA_PASSWORD}@10.0.10.11:554/live
          roles:
            - record
```
