### ISSUE TITLE
[Support]: Duplicate mqtt snapshots with the same timestamp

### ISSUE THREAD

**Issue by Yonny24** [blakeblackshear/frigate#2331]
### Describe the problem you are having

I have set up to receive mqtt snapshot data and view the images. All is working now but I get 2 of every image coming through with the same timestamp on.

Is this a bug or something wrong with my config?

Thanks in advance

### Version

0.9.4-26ae608

### Frigate config file

```yaml
mqtt:      
          # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
     # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 50
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
```

### Relevant log output

```shell
no logs just the duplicate images
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Ezviz

### Any other information that may be helpful

My function to send the image is as follows: (can't see anything in here that would duplicate the image from the payload 

`frigate/frontyard/person/snapshot` output buffer

`msg.payload = {
  content: msg.payload, //the image buffer
  caption: `There's someone in the frontyard. `,
  type : 'photo',
  chatId: ""
 
}

msg.payload.options = { parse_mode : "Markdown" };
return msg;`
