### ISSUE TITLE
[Support]: Coral USB still having slow inference speed

### ISSUE THREAD

**Issue by k2xl** [blakeblackshear/frigate#2349]
### Describe the problem you are having

Finally got my hands on a coral USB.
![image](https://user-images.githubusercontent.com/965260/144087328-7bfd9f3a-1662-4579-b11e-81fc008cc046.png)

Enabled 2 Reolink 810As. Getting inference speeds ~600.

Running on VirtualBox on my 10 year old old [IBM Ideapad y560p](https://www.newegg.com/gray-lenovo-ideapad-y560p/p/N82E16834246094).

I know VirtualBox isn't recommended (and neither is Reolink) with Frigate, but still thought I should be getting faster inference times.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.86.46:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - record
    record: # <----- Enable recording
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    motion:
      mask:
        - 467,10,468,36,154,34,160,9
  driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXX@192.168.86.46:554/h264Preview_03_sub
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
    record: # <----- Enable recording
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    motion:
      mask:
      - 640,0,640,44,0,37,0,0
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 810B4-A https://www.amazon.com/gp/product/B07K734ZTW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
