### ISSUE TITLE
[Support]: [Documentation error?]: Skipping output frames to improve performance does not work

### ISSUE THREAD

**Issue by Draxter** [blakeblackshear/frigate#2360]
### Describe the problem you are having

I'm using a NVidia GPU for decoding and wanted to boost performance by skipping output frames as explained in the docs.
Setting ffmpeg to skip frames in the output, using the fps filter as shown at the bottom of this [documentation](https://docs.frigate.video/configuration/nvdec/) page does not seem to work.

Adding this block to config.yaml causes frigate to crash
```
output_args:
  - -filter:v
  - fps=fps=5
```

After looking at [this](https://docs.frigate.video/configuration/index) docs page, I have alo tried adding this syntax instead:
```
output_args:
  rtmp: -filter:v fps=fps=5
```

However, this results in a green rectangle in frigate UI

### Version

0.10.0-beta4-amd64nvidia

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.100

cameras:
  front_camera:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        - -filter:v
        - fps=fps=5
      inputs:
        - path: http://192.168.10.33/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Password
          roles:
            - rtmp
            - record

record:
  enabled: False
  retain_days: 1
  events:
    retain:
      default: 10

detect:
  enabled: False
```

### Relevant log output

```shell
None, frigate crashes.
```

### FFprobe output from your camera

```shell
Note: Had to use the rtsp stream, as the http one would not work with ffprobe

# ffprobe rtsp://admin:Password@192.168.10.33:554/h264Preview_01_main
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:Password10@192.168.10.33:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 2560x1920, 17.17 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":216}},"front_camera":{"camera_fps":5.1,"capture_pid":223,"detection_fps":0.0,"pid":222,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":65.5,"mount_type":"tmpfs","total":67.1,"used":1.6},"/media/frigate/clips":{"free":403195.1,"mount_type":"xfs","total":414618.0,"used":11423.0},"/media/frigate/recordings":{"free":403195.1,"mount_type":"xfs","total":414618.0,"used":11423.0},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"uptime":197,"version":"0.10.0-c1155af"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink E1 Zoom
