### ISSUE TITLE
[Support]: Full Device Access Warning?

### ISSUE THREAD

**Issue by ksignorini** [blakeblackshear/frigate#2362]
### Describe the problem you are having

I get this warning in my logs:

```
21-12-01 21:52:20 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access) Beta (0.10.0)
21-12-01 21:52:20 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)
```

### Version

0.9.4-26ae608

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.4
  user: mqttuser
  password: PASSPASSPASS

#live:
#  height: 1080
#  quality: 8

cameras:
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://user:PASSPASSPASS@10.0.0.9:8554/Video-113
          roles: 
            - detect
            - clips
    detect:
      enabled: true
#      width: 1280
#      height: 720
#      fps: 5
    objects:
       track:
         - person
         - cat
         - dog
    record:
      enabled: true
      events:
        retain:
           default: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://user:PASSPASSPASS@10.0.0.9:8554/Video-72
          roles: 
            - detect
            - clips
    detect:
      enabled: true
    objects:
       track:
         - person
    record:
      enabled: true
      events:
        retain: 
          default: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
  Back_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:PASSPASSPASS@10.0.0.9:8554/Video-75
          roles: 
            - detect
            - clips
    detect:
      enabled: true
    objects:
       track:
         - person
         - cat
         - dog
    record:
      enabled: true
      events:
        retain:
          default: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
  Side_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:PASSPASSPASS@10.0.0.9:8554/Video-80
          roles: 
            - detect
            - clips
    detect:
      enabled: true
    objects:
       track:
         - person
         - cat
         - dog
    record:
      enabled: true
      events:
        retain:
          default: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5

  Grey_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSPASSPASS@10.0.0.51:554/11
          roles: 
            - detect
            - clips
    detect:
      enabled: true
    objects:
       track:
         - person
    record:
      enabled: false
      events:
        retain:
          default: 1
    snapshots:
      enabled: false
      timestamp: true
      bounding_box: true
      retain:
        default: 1

detectors: 
  cpu1:
    type: cpu
  cpu2:
    type: cpu
    
birdseye:
  enabled: false
```

### Relevant log output

```shell
21-12-01 21:52:20 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access) Beta (0.10.0)
21-12-01 21:52:20 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

various - not related to problem
