### ISSUE TITLE
[Support]: Delay in RTMP stream

### ISSUE THREAD

**Issue by JurajNyiri** [blakeblackshear/frigate#2367]
### Describe the problem you are having

I configured my cameras, everything works fine, except approximately 3 to 4 seconds delay in RTMP stream.
When I watch stream via frigate UI, either live or debug tab, it is near instant.

Adding this stream into home assistant further adds additional delay. I was previously using webrtc with rtsp streams from my cameras. Unfortunately, my cameras only support 1 to 2 active streams which caused issues once frigate was running nonstop.

I have tried using [frigate-hass-card](https://github.com/dermotduffy/frigate-hass-card), which when using `provider: frigate-jsmpeg` provided near-instant latency, however does not load more than 4 streams at the same tab on my android phones. Also, the playback is not smooth (by definition). WebRTC does not work because RTMP is not supported and I cannot create another stream to camera.

Home Assistant stream has a big delay so I have also tried enabling [ll_hls](https://www.home-assistant.io/integrations/stream/#ll-hls) but that didn't seem to make any difference.

So I am looking for one of or combination of following solutions:
1.) RTSP restream instead of RTMP by frigate so that we can use webrtc card for instant playback in home assistant
2.) Elimination of delay in RTMP stream (in VLC) and then also RTSP stream

Is there anything I missed or I can change on my configuration?

Thank you very much

### Version

0.10.0-C1155AF

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264

mqtt:
  host: 192.168.100.25
  user: mqtt
  password: ***
cameras:
  bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.70/stream1
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.71/stream1
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    zones:
      zone_0:
        coordinates: 840,211,831,0,328,0,324,0,341,299,370,483,568,419,559,286
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  hallway:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.72/stream1
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  entry:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.73/stream1
          roles:
            - detect
            - clips
            - rtmp
    zones:
      entry_room_light_zone:
        coordinates: 0,1080,1920,1080,1920,997,1357,657,1435,0,0,0
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      filters:
        person:
          mask:
            - 1051,0,1143,274,1086,540,799,669,748,0
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  dining_room:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.75/stream1
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  office:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.76/stream1
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.30/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    zones:
      garage_property:
        coordinates: 1920,1080,1920,434,1157,154,585,308,349,402,255,439,130,484,0,523,0,1080
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  terrace:
    zones:
      terrace_outside:
        coordinates: 1920,1080,0,1080,0,0,1643,0,1639,276,1603,521,1709,682,1795,640,1920,900
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.31/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  entry_outside:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@192.168.100.33/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    zones:
      doorbell_area:
        coordinates: 1130,52,1130,266,1296,299,1268,22,1112,0,974,0,980,34
      entry_outside_property:
        coordinates: 0,138,0,1080,1920,1080,1920,452,1231,220,1220,295,1120,255,1118,51,1053,41,984,51,994,176,731,230,729,65
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{
  "bedroom": {
    "camera_fps": 5.1,
    "capture_pid": 236,
    "detection_fps": 2.0,
    "pid": 223,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "detection_fps": 16.9,
  "detectors": {
    "cpu": {
      "detection_start": 0.0,
      "inference_speed": 15.66,
      "pid": 218
    }
  },
  "dining_room": {
    "camera_fps": 5.1,
    "capture_pid": 245,
    "detection_fps": 0.0,
    "pid": 230,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "entry": {
    "camera_fps": 5.0,
    "capture_pid": 242,
    "detection_fps": 0.2,
    "pid": 228,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "entry_outside": {
    "camera_fps": 5.0,
    "capture_pid": 260,
    "detection_fps": 0.0,
    "pid": 234,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "garage": {
    "camera_fps": 5.1,
    "capture_pid": 253,
    "detection_fps": 0.0,
    "pid": 232,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "hallway": {
    "camera_fps": 5.0,
    "capture_pid": 240,
    "detection_fps": 0.0,
    "pid": 227,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "living_room": {
    "camera_fps": 5.0,
    "capture_pid": 237,
    "detection_fps": 3.2,
    "pid": 225,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "office": {
    "camera_fps": 5.1,
    "capture_pid": 248,
    "detection_fps": 10.1,
    "pid": 231,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 2106.1,
        "mount_type": "tmpfs",
        "total": 2147.5,
        "used": 41.3
      },
      "/media/frigate/clips": {
        "free": 85513.9,
        "mount_type": "fuse.grpcfuse",
        "total": 494384.8,
        "used": 408870.9
      },
      "/media/frigate/recordings": {
        "free": 85513.9,
        "mount_type": "fuse.grpcfuse",
        "total": 494384.8,
        "used": 408870.9
      },
      "/tmp/cache": {
        "free": 1000.0,
        "mount_type": "tmpfs",
        "total": 1000.0,
        "used": 0.0
      }
    },
    "uptime": 7818,
    "version": "0.10.0-c1155af"
  },
  "terrace": {
    "camera_fps": 5.0,
    "capture_pid": 257,
    "detection_fps": 1.4,
    "pid": 233,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua and Tapo

### Any other information that may be helpful

Running via docker (arm) on Mac Mini M1. CPU Usage seems OK with a lot of room to spare so far.
