### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by heapxor** [blakeblackshear/frigate#2372]
### Describe the problem you are having

the cam changed its IP, i edited config/fraigate.yml updated ip; rebooted Home-assistant, the log shows that frigate trying to connect to olds camera IP.

any idea? is that issue?

Thanks

### Version

latest

### Frigate config file

```yaml
cameras:
  entrance_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@10.0.1.109:554
          roles:
            - detect
            - rtmp
```

### Relevant log output

```shell
[2021-12-03 15:42:25] ffmpeg.entrance_cam.detect     ERROR   : rtsp://admin:xxxx@10.0.1.39:554: Connection refused
```

### FFprobe output from your camera

```shell
[2021-12-03 15:42:25] ffmpeg.entrance_cam.detect     ERROR   : rtsp://admin:xxxx@10.0.1.39:554: Connection refused
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

hikvision
