### ISSUE TITLE
[Support]: Unable to setup docker with old nvidia cards

### ISSUE THREAD

**Issue by rssindian** [blakeblackshear/frigate#2377]
### Describe the problem you are having

I have the below NVidia card
NVIDIA-SMI 418.226.00   Driver Version: 418.226.00   CUDA Version: 10.1

When I run docker compose it throws the below error
ERROR: for frigate  Cannot start service frigate: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.1, please update your driver to a newer version, or use an earlier cuda container: unknown

### Version

0.9.4

### Frigate config file

```yaml
detectors:
  coral:
    type: cpu
logger:
  default: info
mqtt:
  host: 
  port: 
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 
  stats_interval: 60
cameras:
  FrontCamera:
    ffmpeg:
      hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128
      inputs:
        - path: 'rtsp://user:pass@ip:port/live/ch0'
          roles:
            - record
            - detect
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -flags low_delay -strict experimental -c:v h264_cuvid
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

    motion:
      mask:
        - '0,432,332,432,226,124,505,35,557,73,654,432,768,432,768,0,0,0'

    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - '0,432,335,432,198,131,519,37,585,116,639,432,768,432,768,0,0,0'
        car:
          min_area: 5000
          max_area: 100000
          min_score: 0.70
          threshold: 0.80
          mask:
            - '0,432,335,432,198,131,519,37,585,116,639,432,768,432,768,0,0,0'

    zones:
      walkway:
        coordinates: '319,405,660,376,553,64,489,21,196,121'
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    rtmp:
      enabled: false
    
    detect:
      enabled: True
      max_disappeared: 50
      width: 768
      height: 432

    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        required_zones:
            - walkway
        objects:
            - person
            - car
        retain:
            default: 10
            objects:
              person: 30
              car: 30
```

### Relevant log output

```shell
Starting 2cce54437cbb_frigate ... error

ERROR: for 2cce54437cbb_frigate  Cannot start service frigate: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.1, please update your driver to a newer version, or use an earlier cuda container: unknown

ERROR: for frigate  Cannot start service frigate: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.1, please update your driver to a newer version, or use an earlier cuda container: unknown
ERROR: Encountered errors while bringing up the project.
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mpjpeg, from 'http://ip:port/api/Camera':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x360 [SAR 1:1 DAR 16:9], 25 tbr, 25 tbn, 25 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Wansview
