### ISSUE TITLE
[Support]: Stuck Host when install Frigate For old x86_64 CPU without AVX 

### ISSUE THREAD

**Issue by djtomybcn** [blakeblackshear/frigate#2378]
### Describe the problem you are having

Hello!

I had had Frigate working in this computer since some months, but I saw a message that the versión I have working it's not compatible with the new versions of HA.

I'm trying to reinstall again Frigate NVR (For old x86_64 CPU without AVX) unistalling the old version and installa again throught the supervisor:
![image](https://user-images.githubusercontent.com/75133593/144701983-2a7986e7-6b2b-40dd-a5ca-3191aee0e0ff.png)

The process starts and create a docker with a random name (i can see this in portainer) and the process starts "normally".
After 10 minutes of installation process, the docker starts to consume a lot of cpu and memory, until it consumes all resources that it hangs the host operating system and I have to switchoff the host.

Versions: 
supervisor-2021.10.8
HA: core-2021.11.5

Host computer: 
Intel(R) Atom(TM) CPU D525 @ 1.80GHz with 4GB RAM 

### Version

2.3

### Frigate config file

```yaml
mqtt:
  host: ip_of_my_host
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: my_mqtt_password
  stats_interval: 60
cameras:
  Parking:
    ffmpeg:
      inputs:
        - path: rtsp://ip_of_my_cam/ch0_0.h264
          roles:
            - detect
            - clips
            - rtmp
    width: 1920
    height: 1080
    fps: 20
    motion:
      mask:
        - 1229,1080,1326,764,1402,433,1221,343,1108,943
        - 720,390,298,413,311,0,736,0
    
detectors:
  cpu1:
    type: cpu
```

### Relevant log output

```shell
I don't have log output
```

### FFprobe output from your camera

```shell
I don't have log output
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Yi Cam
