### ISSUE TITLE
[Support]: 84 Warnings every time I open the webui

### ISSUE THREAD

**Issue by MRobi1** [blakeblackshear/frigate#2380]
### Describe the problem you are having

Any time I open the webui from the sidebar, I'm getting 84 warning messages in my HA logs. It is the same 7 lines repeated 12 times. This happens every single time. Everything is working fine, it's just flooding the logs with these messages.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": false,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "back_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel fatal",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rw_timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.xx.xxx/bcs/channel3_sub.bcs?channel=3&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.xx.xxx/bcs/channel3_sub.bcs?channel=3&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back_door-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/back_door -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 102,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "back_door",
      "objects": {
        "filters": {
          "dog": {
            "mask": null,
            "max_area": 1000000,
            "min_area": 500,
            "min_score": 0.1,
            "threshold": 0.45
          },
          "person": {
            "mask": null,
            "max_area": 1000000,
            "min_area": 2000,
            "min_score": 0.3,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "dog"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": true,
        "enabled": true,
        "height": 175,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "hot_tub": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel fatal",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rw_timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.xx.xxx/bcs/channel4_sub.bcs?channel=4&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.xx.xxx/bcs/channel4_sub.bcs?channel=4&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/hot_tub-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/hot_tub -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 102,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "272,211,163,157,80,110,88,156,57,169,32,136,15,0,58,7,65,53,82,51,108,45,131,34,204,45,260,55,325,67,377,77,434,90,471,97,480,108,446,133,416,156,372,182,342,203,318,207",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "hot_tub",
      "objects": {
        "filters": {
          "dog": {
            "mask": "272,211,163,157,80,110,88,156,57,169,32,136,15,0,58,7,65,53,82,51,108,45,131,34,204,45,260,55,325,67,377,77,434,90,471,97,480,108,446,133,416,156,372,182,342,203,318,207",
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.1,
            "threshold": 0.45
          },
          "person": {
            "mask": "272,211,163,157,80,110,88,156,57,169,32,136,15,0,58,7,65,53,82,51,108,45,131,34,204,45,260,55,325,67,377,77,434,90,471,97,480,108,446,133,416,156,372,182,342,203,318,207",
            "max_area": 1000000,
            "min_area": 2000,
            "min_score": 0.3,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "dog"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": true,
        "enabled": true,
        "height": 175,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "pool": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel fatal",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rw_timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.xx.xxx/bcs/channel5_sub.bcs?channel=5&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.xx.xxx/bcs/channel5_sub.bcs?channel=5&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/pool-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/pool -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 102,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "490,347,452,341,426,328,405,315,385,284,362,202,341,147,327,110,317,78,348,74,391,67,439,65,458,63,513,86,528,2,561,1,571,87,557,98,592,117,628,136,637,142,638,298,618,315,543,341",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "pool",
      "objects": {
        "filters": {
          "dog": {
            "mask": "490,347,452,341,426,328,405,315,385,284,362,202,341,147,327,110,317,78,348,74,391,67,439,65,458,63,513,86,528,2,561,1,571,87,557,98,592,117,628,136,637,142,638,298,618,315,543,341",
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.1,
            "threshold": 0.45
          },
          "person": {
            "mask": "490,347,452,341,426,328,405,315,385,284,362,202,341,147,327,110,317,78,348,74,391,67,439,65,458,63,513,86,528,2,561,1,571,87,557,98,592,117,628,136,637,142,638,298,618,315,543,341",
            "max_area": 1000000,
            "min_area": 2000,
            "min_score": 0.3,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "dog"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": true,
        "enabled": true,
        "height": 175,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "shed": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel fatal",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rw_timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.xx.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.xx.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/shed-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/shed -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 102,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "shed",
      "objects": {
        "filters": {
          "dog": {
            "mask": null,
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.1,
            "threshold": 0.45
          },
          "person": {
            "mask": null,
            "max_area": 1000000,
            "min_area": 2000,
            "min_score": 0.3,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "dog"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": true,
        "enabled": true,
        "height": 175,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "side_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel fatal",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rw_timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.xx.xxx/bcs/channel2_sub.bcs?channel=2&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.xx.xxx/bcs/channel2_sub.bcs?channel=2&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side_door-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/side_door -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 102,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "102,349,110,264,126,223,126,195,137,197,146,249,159,297,156,347,215,348,317,347,365,346,477,348,518,348,570,346,637,344,639,254,636,150,569,161,501,164,429,175,379,182,374,225,372,262,368,280,412,276,450,313,461,329,542,300,581,281,625,265,628,292,624,315,623,331,623,336",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "side_door",
      "objects": {
        "filters": {
          "dog": {
            "mask": "102,349,110,264,126,223,126,195,137,197,146,249,159,297,156,347,215,348,317,347,365,346,477,348,518,348,570,346,637,344,639,254,636,150,569,161,501,164,429,175,379,182,374,225,372,262,368,280,412,276,450,313,461,329,542,300,581,281,625,265,628,292,624,315,623,331,623,336",
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.1,
            "threshold": 0.45
          },
          "person": {
            "mask": "102,349,110,264,126,223,126,195,137,197,146,249,159,297,156,347,215,348,317,347,365,346,477,348,518,348,570,346,637,344,639,254,636,150,569,161,501,164,429,175,379,182,374,225,372,262,368,280,412,276,450,313,461,329,542,300,581,281,625,265,628,292,624,315,623,331,623,336",
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.3,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "dog"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": true,
        "enabled": true,
        "height": 175,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "side_yard": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel fatal",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rw_timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.xx.xxx/bcs/channel1_sub.bcs?channel=1&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -i rtmp://192.168.xx.xxx/bcs/channel1_sub.bcs?channel=1&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/side_yard-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/side_yard -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 102,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "side_yard",
      "objects": {
        "filters": {
          "dog": {
            "mask": null,
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.1,
            "threshold": 0.45
          },
          "person": {
            "mask": "377,139,386,0",
            "max_area": 1000000,
            "min_area": 1,
            "min_score": 0.3,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "dog"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": true,
        "enabled": true,
        "height": 175,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {
            "person": 15
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 352,
    "max_disappeared": 25,
    "width": 640
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": "-hide_banner -loglevel fatal",
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "nobuffer",
      "-flags",
      "low_delay",
      "-strict",
      "experimental",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rw_timeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {
      "frigate.mqtt": "error"
    }
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "core-mosquitto.local.hass.io",
    "password": "password",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt"
  },
  "objects": {
    "filters": {
      "dog": {
        "mask": null,
        "max_area": 1000000,
        "min_area": 1,
        "min_score": 0.1,
        "threshold": 0.45
      },
      "person": {
        "mask": null,
        "max_area": 1000000,
        "min_area": 2000,
        "min_score": 0.3,
        "threshold": 0.7
      }
    },
    "mask": "",
    "track": [
      "person",
      "dog"
    ]
  },
  "record": {
    "enabled": true,
    "events": {
      "max_seconds": 300,
      "objects": [
        "person",
        "dog"
      ],
      "post_capture": 10,
      "pre_capture": 10,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": true,
    "enabled": true,
    "height": 175,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {
        "person": 15
      }
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'detectors' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'mqtt' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'ffmpeg' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'cameras' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'logger' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'clips' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
21-12-04 20:44:57 WARNING (MainThread) [supervisor.addons.options] Option 'objects' does not exist in the schema for Frigate NVR (ccab4aaf_frigate)
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
??
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink B800

### Any other information that may be helpful

This may not be a new issue, just noticing it now.
