### ISSUE TITLE
Bring back the bounding boxes to MQTT snapshots in RC 0.7.0-x please :)

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#240]
Hi @blakeblackshear !

Would it be possible have the possibility to bring back bounding boxes again to the MQTT snapshots as a configurable item on per camera basis under
```
cameras:
    cam1_front_yard:
      snapshots:
        draw_bounding_boxes: True/False
```

It would help out a lot with debugging and false positives. I really miss the bounding boxes :)
