### ISSUE TITLE
[Support]: HomeAssistant automation not working for image/photo

### ISSUE THREAD

**Issue by binarylimited** [blakeblackshear/frigate#2416]
### Describe the problem you are having

Slowly going insane!
Cant seem to get this working?
mqtt connects fine to homeassistant, no errors in frigate

The message  "1B person was detected" is sent in the signal group....but no picture?
I can see the person event with picture in frigateNVR

```
  alias: 1B - Notify of events
  trigger:
    platform: mqtt
    topic: frigate/events
  action:
  - service: notify.signal
    data_template:
      message: 1B {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: 'http://192.168.1.5/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'

```
### Version

Frigate NVR Current version: 2.3

### Frigate config file

```yaml
###### FRONT DOOR #####

  Front-Door:
    ffmpeg:
      inputs:
        - path: rtsp://blah:blah@192.168.1.25:554/1
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 10

    rtmp:
      enabled: True
    record:
      enabled: False
      retain_days: 7
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - cat
        - dog
#        - car

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hik
