### ISSUE TITLE
[Support]: Failed to view recordings in the Frigate webpage

### ISSUE THREAD

**Issue by t0ny-peng** [blakeblackshear/frigate#2420]
### Describe the problem you are having

Part of the recordings cannot be open in the frontend(Chrome). The page shows error:

![image](https://user-images.githubusercontent.com/4816327/145442827-2b5f17cf-bd2d-46c5-b13e-733a27a6eacf.png)

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

However I've checked that the video files in the `media` folder are all play-able, i.e., can be opened by VLC. And the clips works fine.

P.S, I'm using the official Docker image, and `/media/frigate` is mounted from a NFS folder provided by Synology NAS in the same network. 

### Version

0.9.0

### Frigate config file

```yaml
mqtt:
  host: REDACTED
  user: bot
  password: "REDACTED"

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

record:
  enabled: True
  retain_days: 7
  events:
    retain:
      default: 14

cameras:
  lvrm:
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED/ch0_0.h264
          roles:
            - detect
            - rtmp
            - clips
    motion:
      mask:
        - 1280,0,1280,720,900,720,900,0
        - 0,288,900,288,900,0,0,0
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
```

### Relevant log output

```shell
Not seeing any errors. Only a bunch of `SELECT` and `Insert`
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x563fb3537b80] CSeq 4 expected, 0 received.
Input #0, rtsp, from 'rtsp://REDACTED/ch0_0.h264':
  Metadata:
    title           : Session streamed by "rtspv4"
    comment         : ch0_0.h264
  Duration: N/A, start: 0.100000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 1280x720, 20 fps, 20 tbr, 90k tbn, 180k tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Yi Cam 720
