### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by Richfa** [blakeblackshear/frigate#2427]
### Describe the problem you are having

no camera stream

### Version

2.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.5.219
  user: mqttuser
  password: xynryH-6wyqce_nosnog
  
cameras:
  pi_cam_1:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:admin:FUOPQS@192.168.4.37:554/H.264
          roles:
            - detect
    width: 1000
    hight: 680
    fps: 5
    objects:
      track:
        - person

detectors:
  cpu1:
    type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

### FFprobe output from your camera

```shell
192.168.4.37
```

### Frigate stats

```json
bad gateway
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

ezviz

### Any other information that may be helpful

please help*
