### ISSUE TITLE
[Support]: Single Camera Notification to telegram

### ISSUE THREAD

**Issue by binarylimited** [blakeblackshear/frigate#2431]
### Describe the problem you are having

Have successfully got telegram notifications for frigate events/alerts .

However i cant seem to figure out how to only select 1 camera for telegram alerts. 
Anyone have any idea how to isolate this automation to 1 camera only?

current config :
```
- id: Notify of events
  trigger:
    platform: mqtt
    topic: frigate/events
  condition: '{{ trigger.payload_json["type"] == "end" }}'
  action:
  - service: notify.telegram
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected.
      data:
        photo:
        - url: http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
          caption: A {{trigger.payload_json["after"]["label"]}} was detected on {{
            trigger.payload_json["after"]["camera"] }} camera
  - delay:
      hours: 0
      minutes: 0
      seconds: 45
      milliseconds: 0
  - service: notify.telegram
    data_template:
      message: Video of BillyFrontDoor
      data:
        video:
        - url: https://blahblah.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
          timeout: 1000
          caption: A {{trigger.payload_json["after"]["label"]}} was detected on {{
            trigger.payload_json["after"]["camera"] }} camera
  mode: single
```

### Version

na

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

na
