### ISSUE TITLE
[Support]: [Errno 2] No such file or directory: '/config/config.yml'

### ISSUE THREAD

**Issue by LordNex** [blakeblackshear/frigate#2432]
### Describe the problem you are having

For the life of me, I can't seem to get past this. I'm doing a docker-compose install on a fresh updated raspiean os. I've walked through the config and keep getting this message. Everything will be going to the local sd card for the time being while i set up my nas. Below is the sanitized version of both my docker-compose file as well as the frigate config file

Any help you could give would be much appreciated. I have a Home Assistant box set up on a different box and DeepStack running on a Jetson Nano and both are working correctly. Conversely, I have the HA Integration for Frigate running but am wanting to off-load it to it own RPi4 8gig

### Version

latest armv7

### Frigate config file

```yaml
`mqtt:
  # Required: host name
  host: hostip
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: 
  user: user
  # Optional: pas
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  stats_interval: 60
detectors:
  cpu1:
    type: cpu
    num_threads: 5
  cpu2:
    type: cpu
    num_threads: 5
  cpu3:
    type: cpu
    num_threads: 5
  cpu4:
    type: cpu
    num_threads: 5
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
cameras:
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://streamip/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
  sidedoorbell:
    ffmpeg:
      inputs:
        - path: rtsp://streamip/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2560
      height: 1920
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://streamip/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
  deckcam:
    ffmpeg:
      inputs:
        - path: rtsp://streamip/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db



# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
```

### Relevant log output

```shell
`version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./home/pi/docker-compose/frigate/config.yml:/config/config.yml:ro
#     - ./media/:/media/frigate
      - /mnt/footage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
#    environment:
#      FRIGATE_RTSP_PASSWORD: password
`
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

amcrest, wyze, reolink
