### ISSUE TITLE
[Support]: No Screenshots beeing saved to disk

### ISSUE THREAD

**Issue by maginator** [blakeblackshear/frigate#2445]
### Describe the problem you are having

i dosent get any screenshots of events saved to disk since update from stable 0.9.4 to v0.10 beta4.
But the Storage management for recordings and clips is much better in the newer version Thanks for that.

### Version

0.10.0-C1155AF

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: broker.fritz.box
  port: 1883
  topic_prefix: frigate
cameras:
  raspicam_3:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: http://raspicam3.fritz.box/html/cam_pic_new.php?
          roles:
            - record
            - detect
            - clips
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -r 10
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -preset veryfast -r 10
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v libx264 -an -f flv
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 10
    objects:
      track:
      - person
      filters:
        person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.4
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True



detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.event: debug
    frigate.app: debug

record:
  enabled: true
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      objects:
        person: 15

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

motion:
  threshold: 20
  mask:
    - 981,0,977,74,536,76,534,0
```

### Relevant log output

```shell
No relavant infos found in log
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":10.0,"pid":216},"cpu2":{"detection_start":0.0,"inference_speed":10.0,"pid":218}},"raspicam_3":{"camera_fps":10.1,"capture_pid":226,"detection_fps":0.0,"pid":224,"process_fps":10.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":64.4,"mount_type":"tmpfs","total":67.1,"used":2.7},"/media/frigate/clips":{"free":10872.1,"mount_type":"nfs4","total":21003.6,"used":9041.0},"/media/frigate/recordings":{"free":10872.1,"mount_type":"nfs4","total":21003.6,"used":9041.0},"/tmp/cache":{"free":21938.7,"mount_type":"overlay","total":32626.2,"used":9004.1}},"uptime":31,"version":"0.10.0-c1155af"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

mjpeg Rasperry Pi Cam

### Any other information that may be helpful

Here my Volumes in Portain for Docker: 
![image](https://user-images.githubusercontent.com/19614585/145856393-86bcd85a-ebc7-48fd-b235-9491c79dc2b4.png)
