### ISSUE TITLE
[Support]: Problem during refining in video.py after switching to Raspi OS ffmpeg 

### ISSUE THREAD

**Issue by tomte76** [blakeblackshear/frigate#2450]
### Describe the problem you are having

To get hwaccel back to work on Raspi OS 64 Bit on a Pi 4 I build the containers with "from: debian:stable" and added the Rapsi repository to adjust the packages that differ from Debian and then install ffmpeg with a working hwaccel. See also Issue  #2030. This worked so far as I now can use hwaccel on 2 active cameras with the Raspi OS ffmpeg. I can see birdeyes and the stream of each camera. 

But as soon as there is movement in one of the streams, the following error message comes from Frigate and I have to restart the program so that the corresponding camera works again:

```
frigate | [2021-12-11 20:49:49] ws4py INFO: Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38452]
frigate | [2021-12-11 20:49:53] ws4py INFO: Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38234]
frigate | [2021-12-11 20:49:56] ws4py INFO: Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38234]
frigate | Process camera_processor: Hallway:
frigate | Traceback (most recent call last):
frigate | File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate | self.run ()
frigate | File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate | self._target (* self._args, ** self._kwargs)
frigate | File "/opt/frigate/frigate/video.py", line 362, in track_camera
frigate | process_frames (
frigate | File "/opt/frigate/frigate/video.py", line 554, in process_frames
frigate | obj = group [index [0]]
frigate | IndexError: invalid index to scalar variable.
frigate | [2021-12-11 20:51:44] ws4py INFO: Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38452]
```

### Version

0.9.4-998921a

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: mosquitto

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous
    
snapshots:
  enabled: False
  timestamp: True
  bounding_box: True
  retain:
    default: 10
    objects:
      person: 15  

cameras:
  Flur:
    ffmpeg:
      global_args: -hide_banner -loglevel error
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay 
        - -strict 
        - experimental
        - -analyzeduration
        - 2000M
        - -probesize
        - 2000M
        - -min_port
        - 10000
        - -max_port
        - 10010
        - -rtsp_transport  
        - tcp  
        - -stimeout 
        - 5000000 
        - -use_wallclock_as_timestamps 
        - 1  
      inputs:
        - path: rtsp://192.168.178.84:8554/proxyStream-1
          roles:
            - detect
            - rtmp
            - record
    detect:
      height: 1080
      width: 1920
      fps: 5
    snapshots:
        enabled: True      
  Garten:
    ffmpeg:
      global_args: -hide_banner -loglevel error
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 2000M
        - -probesize
        - 2000M
        - -min_port
        - 10000
        - -max_port
        - 10010
        - -rtsp_transport
        - tcp
        - -stimeout
        - 5000000
        - -use_wallclock_as_timestamps
        - 1
      inputs:
        - path: rtsp://192.168.178.84:8554/proxyStream-2
          roles:
            - detect
    detect:          
      height: 1080
      width: 1920
      fps: 5
```

### Relevant log output

```shell
frigate | [2021-12-11 20:49:49] ws4py INFO: Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38452]
frigate | [2021-12-11 20:49:53] ws4py INFO: Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38234]
frigate | [2021-12-11 20:49:56] ws4py INFO: Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38234]
frigate | Process camera_processor: Hallway:
frigate | Traceback (most recent call last):
frigate | File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate | self.run ()
frigate | File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate | self._target (* self._args, ** self._kwargs)
frigate | File "/opt/frigate/frigate/video.py", line 362, in track_camera
frigate | process_frames (
frigate | File "/opt/frigate/frigate/video.py", line 554, in process_frames
frigate | obj = group [index [0]]
frigate | IndexError: invalid index to scalar variable.
frigate | [2021-12-11 20:51:44] ws4py INFO: Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38452]
```

### FFprobe output from your camera

```shell
needs to go via live555 proxy as camera's tcp RSTP setup is broken and ffmpeg will not accept tcp as transport
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Jovision 

### Any other information that may be helpful

By changing the container to Debian Stable and the dist-upgrade to Raspi OS, a lot of framework conditions have of course changed. Python is now 3.9, the OpenCV bindings are in a newer version and many other packages have also changed. Basically I built nginx_frigate, aarch64_wheels and aarch64_frigate from scratch. I moved the installation of ffmpeg to Dockefile.base and left out aarch64_ffmpeg completely.
