### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by W4rthog** [blakeblackshear/frigate#2464]
### Describe the problem you are having

Detection and recording on one of the cameras seems to stop regularly. 
Restart of Frigate resolves the issue.
At the same time detection on other cameras seems to continue fine.
Interestingly the issue is with a Dahua camera where Reolinks are mostly happy. 

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: {{IP}}
  

detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  fps: 5
    
cameras:
  back_right:
    ffmpeg:
      inputs:
        - path: rtsp://{{path}}
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2688
      height: 1520

  front_left:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: {{path}}
          roles:
            - record
            - rtmp
        - path: {{path}}
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 7
    record:
      events:
        required_zones:
          - front_driveway_enter_left
          - front_left_notcar
    zones:
      front_driveway_enter_left:
        coordinates: 464,141,303,110,168,160,373,512,238,512,83,254,0,265,0,221,0,0,472,0
        objects:
          - person
          - cat
          - car
      front_driveway_left:
        coordinates: 896,512,896,0,30,0,64,512
        objects:
          - person
          - cat
          - car
      front_left_notcar:
        coordinates: 422,512,822,512,896,400,857,237,720,146,896,74,896,0,0,0,0,512
        objects:
          - person
          - cat

  front_right:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: {{path}}
          roles:
            - record
            - rtmp
        - path: {{path}}
          roles:
            - detect
    detect:
      width: 896
      height: 512
      fps: 7
    
    record:
      events:
        required_zones:
          - front_driveway_enter_right
          - front_driveway_right_notcar
    zones:
      front_driveway_enter_right:
        coordinates: 460,196,397,310,704,304,624,190
        objects:
          - person
          - cat
          - car
      front_driveway_right_notcar:
        coordinates: 689,202,896,411,896,512,0,512,268,265,404,181
        objects:
          - person
          - cat
      front_right_zone:
        coordinates: 896,512,0,512,0,259,0,104,49,55,178,26,570,24,674,46,793,107,896,259
        objects:
          - person
          - cat
          - car

    

          
objects:
  track:
    - person
    - car
    - cat
    
    

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
      # Optional: crop the snapshot (default: shown below)
  crop: False

      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
      # Optional: Camera override for retention settings (default: global values)
  retain:
        # Required: Default retention days (default: shown below)
    default: 10
        # Optional: Per object retention days
    objects:
      person: 15
          
record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 7
```

### Relevant log output

```shell
[2021-12-16 09:44:11] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2021-12-16 09:44:11] root                           INFO    : Waiting for detection process to exit gracefully...
[2021-12-16 09:44:41] root                           INFO    : Detection process didnt exit. Force killing...
[2021-12-16 09:44:41] detector.coral                 INFO    : Starting detection process: 16801
[2021-12-16 09:44:41] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-16 09:44:44] frigate.edgetpu                INFO    : TPU found
[2021-12-16 09:46:51] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2021-12-16 09:46:51] root                           INFO    : Waiting for detection process to exit gracefully...
[2021-12-16 09:47:21] root                           INFO    : Detection process didnt exit. Force killing...
[2021-12-16 09:47:21] detector.coral                 INFO    : Starting detection process: 16881
[2021-12-16 09:47:21] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-16 09:47:24] frigate.edgetpu                INFO    : TPU found
[2021-12-16 09:48:01] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2021-12-16 09:48:01] root                           INFO    : Waiting for detection process to exit gracefully...
[2021-12-16 09:48:31] root                           INFO    : Detection process didnt exit. Force killing...
[2021-12-16 09:48:31] detector.coral                 INFO    : Starting detection process: 16921
[2021-12-16 09:48:31] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-16 09:48:34] frigate.edgetpu                INFO    : TPU found
[2021-12-16 09:49:11] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2021-12-16 09:49:11] root                           INFO    : Waiting for detection process to exit gracefully...
[2021-12-16 09:49:41] root                           INFO    : Detection process didnt exit. Force killing...
```

### FFprobe output from your camera

```shell
ffprobe version 4.1.8-0+deb10u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --                                                                                                                                                             libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=a                                                                                                                                                             md64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resam                                                                                                                                                             ple --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-l                                                                                                                                                             ibass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --en                                                                                                                                                             able-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --e                                                                                                                                                             nable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp                                                                                                                                                             3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libop                                                                                                                                                             us --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine -                                                                                                                                                             -enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-li                                                                                                                                                             btheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libv                                                                                                                                                             px --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enab                                                                                                                                                             le-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-o                                                                                                                                                             penal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-                                                                                                                                                             libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-share                                                                                                                                                             d
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, rtsp, from 'rtsp://{{username}}:{{password}}@{{IP}}:554/cam/realmoni                                                                                                                                                             tor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt470bg/bt470bg/bt709, progres                                                                                                                                                             sive), 2688x1520, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-T5442TM-AS-3.6mm
