### ISSUE TITLE
[Support]:   object of type 'NoneType' has no len() (type=type_error)

### ISSUE THREAD

**Issue by hathalud** [blakeblackshear/frigate#2465]
### Describe the problem you are having

After updating Frigate and HA to the latest images, with no changes to my config in Frigate, Frigate has started bootlooping with the error "object of type 'NoneType' has no len() (type=type_error)" I've tried to find where the error is in the config file, but since there is no specific line referenced or layperson-readable error, I have been unable to figure this one out. It just says that it's in the configuration for the front door camera.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
#  cpu2:
#    type:cpu

mqtt:
  # Required: host name
  host: 192.168.0.12
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: ***redacted***
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: ***redacted***
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60


cameras:
  # Name of your camera
  cam_frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://***redacted***@192.168.0.27/live
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
#    fps: 5
    motion:
      mask:
        - 1280,0,790,0,1023,720,1280,720
    zones:
    objects:
      filters:
        person:
          mask:
            - 300,660,1020,630,884,105,293,246
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 14
#    clips:
#      enabled: true
#      retain: 
#        default: 14

  cam_garage:
    ffmpeg:
      inputs:
        - path: rtsp://***redacted***@192.168.0.30:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://***redacted***@192.168.0.30:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
#    fps: 5
    objects:
      track:
        - car
      filters:
        car:
          mask:
            - 647,1080,1920,1080,1292,164,692,203
record:
  # Optional: Enable recording
  enabled: true
  # Optional: Number of days to retain
  retain_days: 15


#clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
#  max_seconds: 600
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
#  tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
#  retain:
    # Required: Default retention days (default: shown below)
#    default: 9
    # Optional: Per object retention days
#    objects:
#      person: 15
#      car: 3


ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - "1"
            - 647,1080,1920,1080,1292,164,692,203
```

### Relevant log output

```shell
[services.d] starting services
[services.d] done.
[2021-12-16 12:04:39] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> cam_frontdoor
  object of type 'NoneType' has no len() (type=type_error)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP2M-841B and Wyze Camv2
