### ISSUE TITLE
[Support]: Startup of Frigate Addon in homeassistant 2021.12.3 Complains about config file but i'm not sure whats wrong.

### ISSUE THREAD

**Issue by tomfrogger** [blakeblackshear/frigate#2475]
### Describe the problem you are having

Startup of Frigate on 2021.12.3 Complains about config file but i'm not sure whats wrong.

### Version

2.3

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: core-mosquitto.local.hass.io
  user: tomfrogger
  password: 
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  front_door:
    ffmpeg:
      inputs:
      - path: rtsp://admin:pw@192.168.0.86:554//h264Preview_01_main
        roles:
        - record
        - rtmp
      - path: rtsp://admin:pw@192.168.0.86:554//h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 352
    motion:
      mask:
      - '640,0,640,352,397,352,427,0'
    zones:
      zone_front_door:
        coordinates: 206,352,640,352,640,0,166,0
  kitchen:
    ffmpeg:
      inputs:
      - path: rtsp://admin:pw@192.168.0.85:554//h264Preview_01_main
        roles:
        - record
        - rtmp
      - path: rtsp://admin:pw@192.168.0.85:554//h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 352
    motion:
      mask:
      - 0,262,51,239,0,0
    zones:
      zone_back_room:
        coordinates: '640,352,529,352,590,153,616,0,640,0'
      zone_kitchen:
        coordinates: '607,0,0,0,0,352,516,352,581,197'
  back_room:
    ffmpeg:
      inputs:
      - path: rtsp://admin:pw@192.168.0.84:554//h264Preview_01_main
        roles:
        - record
        - rtmp
      - path: rtsp://admin:pw@192.168.0.84:554//h264Preview_01_sub
        roles:
        - detect
    detect:
      width: 640
      height: 352
    motion:
      mask:
      - 536,77,640,93,640,0,538
    zones:
      zone_back_room:
        coordinates: 567,0,640,0,640,352,438,352,0,352,0,0,72,0,82,72,99,153,107,185,114,228,195,198,175,0
      zone_kitchen:
        coordinates: 82,64,85,114,110,203,142,295,206,249,170,104,137,0,76,0,80
  garden:
    ffmpeg:
      inputs:
      - path: rtmp://192.168.0.80/bcs/channel0_main.bcs?channel=0&stream=0&user=motioneye&password=pw
        roles:
        - record
        - rtmp
        input_args:
        - "-avoid_negative_ts"
        - make_zero
        - "-fflags"
        - nobuffer
        - "-flags"
        - low_delay
        - "-strict"
        - experimental
        - "-fflags"
        - "+genpts+discardcorrupt"
        - "-rw_timeout"
        - '5000000'
        - "-use_wallclock_as_timestamps"
        - '1'
      - path: rtmp://192.168.0.80/bcs/channel0_ext.bcs?channel=0&stream=2&user=motioneye&password=pw
        roles:
        - detect
        input_args:
        - "-avoid_negative_ts"
        - make_zero
        - "-fflags"
        - nobuffer
        - "-flags"
        - low_delay
        - "-strict"
        - experimental
        - "-fflags"
        - "+genpts+discardcorrupt"
        - "-rw_timeout"
        - '5000000'
        - "-use_wallclock_as_timestamps"
        - '1'
    detect:
      width: 896
      height: 512
    motion:
      mask:
        - 228,436,184,287,107,233,106,131,146,62,240,52,323,62,484,59,585,93,586,189,561,295
    zones:
      zone_garden:
        coordinates: 0,512,0,325,565,66,760,79,896,159,896,512
      zone_road:
        coordinates: 0,258,212,317,318,274,327,101,335,0,0,0
    objects:
      track:
      - person
      - cat
      - dog
      - horse
  garden_back:
    ffmpeg:
      inputs:
      - path: rtmp://192.168.0.87/bcs/channel0_main.bcs?channel=0&stream=0&user=motioneye&password=motioneye
        roles:
        - record
        - rtmp
        input_args:
        - "-avoid_negative_ts"
        - make_zero
        - "-fflags"
        - nobuffer
        - "-flags"
        - low_delay
        - "-strict"
        - experimental
        - "-fflags"
        - "+genpts+discardcorrupt"
        - "-rw_timeout"
        - '5000000'
        - "-use_wallclock_as_timestamps"
        - '1'
      - path: rtmp://192.168.0.87/bcs/channel0_ext.bcs?channel=0&stream=2&user=motioneye&password=motioneye
        roles:
        - detect
        input_args:
        - "-avoid_negative_ts"
        - make_zero
        - "-fflags"
        - nobuffer
        - "-flags"
        - low_delay
        - "-strict"
        - experimental
        - "-fflags"
        - "+genpts+discardcorrupt"
        - "-rw_timeout"
        - '5000000'
        - "-use_wallclock_as_timestamps"
        - '1'
    detect:
      width: 896
      height: 512
    motion:
      mask:
      - 424,0,896,269,896,0,403,0,0,0,0,229
    zones:
      zone_babington:
        coordinates: 0,512,292,512,407,251,0,259
      zone_garden:
        coordinates: 749,512,669,129,318,142,290,512
      zone_road:
        coordinates: 896,512,619,512,644,107,896,88
    objects:
      track:
      - person
      - cat
      - dog
      - horse
objects:
  track:
  - person
  - cat
  filters:
    person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
record:
  enabled: True
  retain_days: 0
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Per object retention days
      objects:
        person: 15
        cat: 20
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-18 09:41:23] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
list index out of range
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
None.
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink
