### ISSUE TITLE
[Support]: Cannot start Frigate

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#2476]
### Describe the problem you are having

Hi Blake,

I've been using Frigate happily since a long time now (you helped me a lot to set it up). I decided to add one more camera into Frigate. Its a camera that i have had for many years but had not yet integrated into Frigate. So i added the rtsp settings and all into the frigate.yml file. restarted frigate, all went well except that this camera and another camera that worked previously started showing green screen. so i started playing around with the resolution and frame rates. and then when i tried to restart frigate, it just didnt start. 

when i click on start, it tries for a split second and then nothing happens, i.e. the start button stays as it is. super strange.  Pls have a look at the screen recording i made:

https://user-images.githubusercontent.com/30929896/146642249-7f29c1cf-f29c-4b95-9878-485983cfe6eb.mov

So then i tried some troubleshooting. i deleted the HACS component, deleted integration, deleted add-on and then re-installed the HACS and addon and restarted HA several times and still frigate just does not start. then i deleted everything again and then installed the beta 0.10.0 and now when i click start it gives error: Port '5000' is already in use by something else on the host. I have seen your comments in the issue #2274 that you cannot run 2 instances of frigate, but i am only running the beta. there are no other instances. no other installations. 

i also tried restoring a complete HA backup from a 1 week old backup and frigate still does not start. Same problem. 

And then i tried running the beta version with port 5001 and this works, i can start the addon, but i cannot install the integration still. gives an error saying cannot connect.

Here's what i see this in the logs:

21-12-18 12:55:15 ERROR (SyncWorker_3) [supervisor.docker] Can't start addon_ccab4aaf_frigate: 500 Server Error for http+docker://localhost/v1.41/containers/1c39c51b924e4ff1d084101b89b9a0d66d18bc0187d5bf1f2ead7df34a89f214/start: Internal Server Error ("driver failed programming external connectivity on endpoint addon_ccab4aaf_frigate (274deb1f75898f0356327e2b50c7e9cf23da39125acfb8cecb633862eaedfc02): Bind for 0.0.0.0:5000 failed: port is already allocated")

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:172
Integration: Frigate (documentation, issues)
First occurred: 12:30:03 (9 occurrences)
Last logged: 12:37:16

Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Try again]

I also installed portainer to see hats going on:

![image](https://user-images.githubusercontent.com/30929896/146645140-3ad99068-fa73-42db-87fe-2eb1a65b4308.png)

There it is. There is a frigate container running since 5 hours, which is before i started trying to add a new camera this morning. I think this is the problem. This is probably why frigate does not start. 

I cannot delete this old running container in portainer. it fails saying that removal is already in progress:

![image](https://user-images.githubusercontent.com/30929896/146645207-28adbd13-8fe7-4ff4-a555-745692f43291.png)

I also cannot delete the images as it says there is a running container with the images.

![image](https://user-images.githubusercontent.com/30929896/146645234-d812df9b-d3d9-4fed-8f4a-960b1fa0c6aa.png)

![image](https://user-images.githubusercontent.com/30929896/146645248-8cac7a90-2cd6-456a-b850-474e2ffc3ec5.png)

Any ideas what else i can try? 

I'm really getting desperate. Your Frigate is the ONLY thing that i really love about my whole setup and if icant fix this, i will need to setup HA all from scratch, which means i need to setup everything including pairing all my zwave devices in my home. it will take me weeks to do all this :(

Please help? 
Thanks so much!

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:119
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 11:30:52 (3 occurrences)
Last logged: 11:45:10

Failed to to call /addons/ccab4aaf_frigate-fa-beta/start - Port '5000' is already in use by something else on the host.

![image](https://user-images.githubusercontent.com/30929896/146638297-7779147d-d06a-4b68-a51a-73b5d343e3f2.png)

### Version

0.10.0

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb'
    num_threads: 3
mqtt:
  host: 192.168.178.125
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: Sike45cem!!99
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:KDROSK@192.168.178.31:554/h.264'
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: >-
        -0,0,1920,0,1920,1080,1490,1080,1659,694,690,270,121,417,345,1080,0,1080
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask: >-
            -2,1,1920,0,1920,1080,1490,1080,1678,653,547,227,533,73,354,86,370,292,116,340,285,1012,680,1014,678,1080,0,1080
    zones:
      car:
        coordinates: 343,1058,1477,1080,1654,683,776,252,123,394
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: [car]
        retain:
          default: 10
          objects:
            person: 15
  Package:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:HAEPIT@192.168.178.36:554/h.264'
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,1080,1920,1080,1350,547,1408,891,1081,899,1105,544,1307,523,1920,1080,1920,0,0,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
    zones:
      box:
        coordinates: 1128,888,1408,891,1356,564,1073,535
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: [box]
        retain:
          default: 10
          objects:
            person: 15
database:
  path: /media/frigate/clips/frigate.db
logger:
  default: info
  logs:
    frigate.mqtt: error
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

EZVIZ CTQ3W
