### ISSUE TITLE
[Support]: How to purge frigate using docker-compose

### ISSUE THREAD

**Issue by junior466** [blakeblackshear/frigate#2482]
### Describe the problem you are having

I am new to docker and frigate and I was wondering how I can start fresh with frigate? No matter what I do I always see 
`peewee_migrate                 INFO    : Starting migrations` due to a mistake I made. 

Thank you.

### Version

Latest

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.141.19
  user: REDACTED
  password: REDACTED

# detectors
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

# Optional: birdseye configuration
birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: motion

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 240
    pre_capture: 2
    post_capture: 8


# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True

# Required
cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://USER:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          roles:
            - detect
            - rtmp
            - record
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 240
        pre_capture: 2
        post_capture: 8
        objects:
          - person
          - car
        required_zones:
          - street_driveway
          - main_driveway

    snapshots:
      required_zones:
        - street_driveway
        - main_driveway

    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True 
  
    # Optional: Motion configuration
    motion:
      mask:
        - 1005,606,1177,832,476,1080,397,768
        - 1920,0,1920,739,890,478,683,0
        - 0,246,228,248,261,726,0,782

    # Optional: zones for this camera
    zones:
      # Required: name of the zone
      street_driveway:
        coordinates: 1846,759,1825,821,1407,674,1475,637
        objects:
          - person
          - car
      main_driveway:
        coordinates: 1463,1080,1059,875,1341,705,1831,873,1744,1080
        objects:
          - person
          # - car
```

### Relevant log output

```shell
peewee_migrate                 INFO    : Starting migrations`
```

### FFprobe output from your camera

```shell
?
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest
