### ISSUE TITLE
[Support]: out of space fast

### ISSUE THREAD

**Issue by WesNz** [blakeblackshear/frigate#2492]
### Describe the problem you are having

Keep running out of space very quickly just not sure why.
Im not looking for 24/7 recording solution but only want x amount of events to refer back to. These events are pushed to telegram and HA MobileApp.

Have a different system that records 24/7.

Tests iv done :  
- Deleted all clips and images. 70GB left on device.
- Adjusted days/events for snapshots and rtmp
- Restarted frigate 
- 12hours later and the device is full again

### Version

0.9.4-26AE608

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.1.55
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: meh
  password: meh

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'
    
    
###### SIDE PATH #####
cameras:
  Side_Path:
    ffmpeg:
      inputs:
        - path: rtsp://meh:meh@192.168.1.22/Streaming/Channels/102 
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 10
      enabled: True

    rtmp:
      enabled: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:
        default: 5
        objects:
          person: 10
    objects:
      track:
#        - person
#        - car
#        - truck
#        - bicycle
#        - motorcycle
#        - dog
        - cat
#      mask: 436,0,201,0,70,0,0,0,0,73,0,44,29,125,458,108,455,37
        # Optional: save clips configuration#

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []

###### CAR PORT ####


  CarPort:
    ffmpeg:
      inputs:
        - path: rtsp://meh:meh@192.168.1.26/cam/realmonitor?channel=1&subtype=1 
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 480
      fps: 10

    rtmp:
      enabled: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:
        default: 5
        objects:
          person: 10
    objects:
      track:
        - person
        - cat
        - dog
#        - car

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []
      
##### GARAGE ######

  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://meh:meh@192.168.1.23/SAPI/Streaming/channels/201
          roles:
            - detect
            - rtmp
    detect:
      width: 480
      height: 640
      fps: 6

    rtmp:
      enabled: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: False
      retain:
        default: 5
        objects:
          person: 10
    objects:
      track:
        - person
        - cat
        - dog
#        - car

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []

###### FRONT DOOR #####

  Front-Door:
    ffmpeg:
      inputs:
        - path: rtsp://meh:meh@192.168.1.25:554/1
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 10

    rtmp:
      enabled: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 360
      required_zones: []
      retain:
        default: 5
        objects:
          person: 10
    objects:
      track:
        - person
        - cat
        - dog
        - car

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []
    
#### BILLYS HOUSE ######

  Billys-House:
    ffmpeg:
      inputs:
        - path: rtsp://meh:meh@192.168.1.90/Streaming/Channels/102 
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 6

    rtmp:
      enabled: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 5
        objects:
          person: 10
    objects:
      track:
        - person
        - cat
        - dog
#        - car
      filters:
        person:
          mask:
            - 124,129,214,0,107,0,0,0,0,136

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []
      
#### BILLY Front Door ######

  Billy-FrontDoor:
    ffmpeg:
      inputs:
        - path: rtsp://meh:meh@192.168.1.91:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    detect:
      width: 704
      height: 576
      fps: 6

    rtmp:
      enabled: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 576
      required_zones: []
      retain:
        default: 5
        objects:
          person: 10
    objects:
      track:
        - person
        - cat
        - dog
#        - car
#      filters:
#        person:
#          mask:
#            - 124,129,214,0,107,0,0,0,0,136
      
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 360
      required_zones: []
```

### Relevant log output

```
2021-12-21 20:50:16] frigate.app                    INFO    : Capture process started for Billys-House: 250
[2021-12-21 20:50:16] frigate.app                    INFO    : Capture process started for Billy-FrontDoor: 252
[2021-12-21 20:50:16] ws4py                          INFO    : Using epoll
[2021-12-21 20:50:18] frigate.edgetpu                INFO    : TPU found
Exception in thread recording_cleanup:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/record.py", line 310, in run
    self.expire_files()
  File "/opt/frigate/frigate/record.py", line 280, in expire_files
    oldest_timestamp = p.stat().st_mtime - 1
  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/media/frigate/recordings/2021-12/12/12/Front-Door/21.10.mp4'
[2021-12-21 20:51:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:54172]
[2021-12-21 20:51:26] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:54172]
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision and some generic's
