### ISSUE TITLE
[Support]: can't initialize time/permission error?

### ISSUE THREAD

**Issue by Jenni32222** [blakeblackshear/frigate#2499]
### Describe the problem you are having

Trying to setup Frigate for a while now, I'm not very handy with this stuff.

### Version

Unknown due to not being able to setup

### Frigate config file

```yaml
version: "3.2"
services:
  frigate:
    container_name: frigate
    privileged: false # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/frigate/config.yml:/config/config.yml:ro
      - /home/ubuntu/frigate/storage:/media/frigate
      # type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #  target: /tmp/cache
      #  tmpfs:
      #    size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
pi@raspberrypi:~ $ docker-compose up
Creating frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | Fatal Python error: pyinit_main: can't initialize time
frigate    | Python runtime state: core initialized
frigate    | PermissionError: [Errno 1] Operation not permitted
frigate    | 
frigate    | Current thread 0xb6f63460 (most recent call first):
frigate    | <no Python frame>
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 1
pi@raspberrypi:~ $
```

### FFprobe output from your camera

```shell
Irrelevant
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink
