### ISSUE TITLE
Bounding boxes a bit off

### ISSUE THREAD

**Issue by zewelor** [blakeblackshear/frigate#25]
Hi

thanks for this great project, its so great. I've started testing today, and it worked right away. I've got question about bounding boxes, they are a bit off, not sure if I got some error in config or its supposed to be like this, it looks consistent, similar offset on multiple frames, its below upper recognition area. It looks like x are ok, only y axis is too low.

![best_person](https://user-images.githubusercontent.com/389828/56863536-a0d8b880-69b7-11e9-8902-d46ee29702d2.jpg)

```yaml
    regions:
      - size: 450
        x_offset: 50
        y_offset: 100
        min_person_area: 4000
```
