### ISSUE TITLE
[Support]: Retention cleaning not kicking in

### ISSUE THREAD

**Issue by lennartkoopmann** [blakeblackshear/frigate#2502]
### Describe the problem you are having

Everything works absolutely flawlessly, except that Frigate does not seem to retention clean neither clips nor recordings and I have to manually delete events every time the disk runs full. I added the entire config file with only passwords redacted.

My storage is a SMB mounted NAS.

### Version

0.9.4

### Frigate config file

```yaml
mqtt:
  host: host.docker.internal
  port: 1883
detectors:
  coral1:
    type: edgetpu
    device: pci

rtmp:
  enabled: false

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10

objects:
  track:
    - person
    - cat
    - dog

record:
  enabled: true
  retain_days: 2
  events:
    max_seconds: 300
    pre_capture: 10
    post_capture: 10
    retain:
      default: 7

detect:
  fps: 15

cameras:

  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@172.16.0.80:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@172.16.0.81:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  office:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@172.16.0.83:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@172.16.0.84:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@172.16.0.82:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@172.16.0.85:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

n/a

**Comment by Sloth-on-meth** [comment]
seem to be having the same issue

**Comment by sycophantic** [comment]
I have the same issue with the below config, nothing is deleted.

```record:
  enabled: true
  retain_days: 0
  events:
    retain:
      default: 14```

**Comment by blakeblackshear** [comment]
Can you add the following to your config to see if there is any useful output?

```yaml
logger:
  default: info
  logs:
    frigate.record: debug
```

**Comment by tyzbit** [comment]
I'm facing this issue as well, here are my logs after restarting:

<details><summary>Click to expand...</summary>
<pre>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-01-04 10:07:09] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
Starting migrations
[2022-01-04 10:07:09] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-01-04 10:07:10] peewee_migrate                 INFO    : There is nothing to migrate
[2022-01-04 10:07:10] frigate.mqtt                   INFO    : MQTT connected
[2022-01-04 10:07:10] detector.coral                 INFO    : Starting detection process: 224
[2022-01-04 10:07:10] frigate.app                    INFO    : Output process started: 226
[2022-01-04 10:07:10] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-01-04 10:07:10] ws4py                          INFO    : Using epoll
[2022-01-04 10:07:10] frigate.app                    INFO    : Camera processor started for frontdoor: 229
[2022-01-04 10:07:12] frigate.edgetpu                INFO    : TPU found
[2022-01-04 10:07:10] frigate.app                    INFO    : Camera processor started for backdoor: 233
[2022-01-04 10:07:10] frigate.app                    INFO    : Camera processor started for driveway: 234
[2022-01-04 10:07:10] frigate.app                    INFO    : Camera processor started for porch: 237
[2022-01-04 10:07:10] frigate.app                    INFO    : Camera processor started for court: 240
[2022-01-04 10:07:10] frigate.app                    INFO    : Capture process started for frontdoor: 248
[2022-01-04 10:07:10] frigate.app                    INFO    : Capture process started for backdoor: 252
[2022-01-04 10:07:10] frigate.app                    INFO    : Capture process started for driveway: 254
[2022-01-04 10:07:10] frigate.app                    INFO    : Capture process started for porch: 259
[2022-01-04 10:07:10] frigate.app                    INFO    : Capture process started for court: 264
[2022-01-04 10:07:10] ws4py                          INFO    : Using epoll
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Start expire recordings (new).
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Start deleted cameras.
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Expiring 0 recordings
[2022-01-04 10:08:10] frigate.record                 DEBUG   : End deleted cameras.
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Start all cameras.
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Start camera: frontdoor.
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:08:10] frigate.record                 DEBUG   : End camera: frontdoor.
[2022-01-04 10:08:10] frigate.record                 DEBUG   : Start camera: backdoor.
[2022-01-04 10:08:11] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:08:11] frigate.record                 DEBUG   : End camera: backdoor.
[2022-01-04 10:08:11] frigate.record                 DEBUG   : Start camera: driveway.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:08:12] frigate.record                 DEBUG   : End camera: driveway.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Start camera: porch.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:08:12] frigate.record                 DEBUG   : End camera: porch.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Start camera: court.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Expiring 0 recordings
[2022-01-04 10:08:12] frigate.record                 DEBUG   : End camera: court.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : End all cameras.
[2022-01-04 10:08:12] frigate.record                 DEBUG   : End expire recordings (new).
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Start expire files (legacy).
[2022-01-04 10:08:12] frigate.record                 DEBUG   : Oldest recording in the db: 1638730595.3573527
[2022-01-04 10:08:15] frigate.record                 DEBUG   : End expire files (legacy).
[2022-01-04 10:09:17] frigate.record                 DEBUG   : Start expire recordings (new).
[2022-01-04 10:09:17] frigate.record                 DEBUG   : Start deleted cameras.
[2022-01-04 10:09:17] frigate.record                 DEBUG   : Expiring 0 recordings
[2022-01-04 10:09:17] frigate.record                 DEBUG   : End deleted cameras.
[2022-01-04 10:09:17] frigate.record                 DEBUG   : Start all cameras.
[2022-01-04 10:09:17] frigate.record                 DEBUG   : Start camera: frontdoor.
[2022-01-04 10:09:18] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:09:18] frigate.record                 DEBUG   : End camera: frontdoor.
[2022-01-04 10:09:18] frigate.record                 DEBUG   : Start camera: backdoor.
[2022-01-04 10:09:18] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:09:18] frigate.record                 DEBUG   : End camera: backdoor.
[2022-01-04 10:09:18] frigate.record                 DEBUG   : Start camera: driveway.
[2022-01-04 10:09:19] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:09:19] frigate.record                 DEBUG   : End camera: driveway.
[2022-01-04 10:09:19] frigate.record                 DEBUG   : Start camera: porch.
[2022-01-04 10:09:20] frigate.record                 DEBUG   : Expiring 7 recordings
[2022-01-04 10:09:20] frigate.record                 DEBUG   : End camera: porch.
[2022-01-04 10:09:20] frigate.record                 DEBUG   : Start camera: court.
[2022-01-04 10:09:20] frigate.record                 DEBUG   : Expiring 0 recordings
[2022-01-04 10:09:20] frigate.record                 DEBUG   : End camera: court.
[2022-01-04 10:09:20] frigate.record                 DEBUG   : End all cameras.
[2022-01-04 10:09:20] frigate.record                 DEBUG   : End expire recordings (new).
</pre>
</details>

My config:
<details><summary>Click to expand...</summary>
<pre>
database:
  path: /db/frigate.db
logger:
  default: info
  logs:
    frigate.record: debug
mqtt:
  host: mosquitto
# ffmpeg:
#   hwaccel_args:
#     - -hwaccel
#     - vaapi
#     - -hwaccel_device
#     - /dev/dri/renderD128
#     - -hwaccel_output_format
#     - yuv420p
cameras:
  frontdoor:
    snapshots:
      timestamp: true
    motion:
      mask:
        - 0,390,190,281,413,219,612,181,842,131,1149,113,1138,0,0,0
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor:554'
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
  backdoor:
    snapshots:
      timestamp: true
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_BACKDOOR_CREDENTIALS}@backdoor:554/live'
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
  driveway:
    snapshots:
      timestamp: true
    motion:
      mask:
        - 1820,127,1775,335,1605,1080,1920,1080,1920,252,1920,0,1252,0,1443,45
        - 595,687,218,948,172,865,103,718,373,553,538,627
    objects:
      filters:
        person:
          mask: 
          - 1820,127,1775,335,1605,1080,1920,1080,1920,252,1920,0,1252,0,1443,45
          - 595,687,218,948,172,865,103,718,373,553,538,627
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_DRIVEWAY_CREDENTIALS}@driveway:554/live'
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
  porch:
    snapshots:
      timestamp: true
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_PORCH_CREDENTIALS}@porch:554/live'
          roles:
            - detect
            - rtmp
    detect:
      width: 2688
      height: 1520
      fps: 5
  court:
    record:
      enabled: false
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_COURT_CREDENTIALS}@court:554/live'
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
record:
  enabled: true
  retain_days: 0
  events:
    retain:
      default: 30
objects:
  track:
    - person
birdseye:
  enabled: true
  mode: objects
detectors:
  coral:
    type: edgetpu
    device: usb
</pre>
</details>

**Comment by junior466** [comment]
Ironically, I just received a quota exceeded message from my NAS and noticed that my retention also didn't kick in but turns out I had 

        record:
          enabled: True
          retain_days: 0
          events:
            max_seconds: 240
            pre_capture: 5
            post_capture: 5

configured globally and under camera settings I had

        record:
          events:
            required_zones:
              - street_driveway
              - main_driveway

And retention wasn't working properly. As soon as I changed the camera settings to 

      record:
        enabled: True
        retain_days: 0
        events:
          max_seconds: 240
          pre_capture: 5
          post_capture: 5
          retain:
            default: 7

events were automatically and quickly deleted and I have exactly 7 days worth of recordings now. 

Probably doesn't help OP but retention is working for me.

**Comment by blakeblackshear** [comment]
You can clearly see it expiring 7 recordings every minute for each camera. There should be 7 deleted files for each of those log messages.

**Comment by tyzbit** [comment]
Perhaps I'm having a slightly different issue then; mine is that I set `retain_days: 0` and it's actually retaining all recordings rather than just recordings for events.

**Comment by blakeblackshear** [comment]
> Is it because the recording section defined under camera didn't have a `retain` section and `retain_days` defined? Sorry If I am not making any sense

Perhaps there is an edge case bug in the way the record settings get merged down between global and camera level. Can you look to see what the differences are in the compiled JSON config in the debug area of the web UI?

**Comment by junior466** [comment]
@blakeblackshear Sorry for the delay in replying. Here's my JSON:

        {
          "birdseye": {
            "enabled": true,
            "height": 1080,
            "mode": "motion",
            "quality": 8,
            "width": 1920
          },
          "cameras": {
            "backyard_cam": {
              "best_image_timeout": 60,
              "detect": {
                "enabled": true,
                "fps": 5,
                "height": 1080,
                "max_disappeared": 25,
                "width": 1920
              },
              "ffmpeg": {
                "global_args": [
                  "-hide_banner",
                  "-loglevel",
                  "warning"
                ],
                "hwaccel_args": [],
                "input_args": [
                  "-avoid_negative_ts",
                  "make_zero",
                  "-fflags",
                  "+genpts+discardcorrupt",
                  "-rtsp_transport",
                  "tcp",
                  "-stimeout",
                  "5000000",
                  "-use_wallclock_as_timestamps",
                  "1"
                ],
                "inputs": [
                  {
                    "global_args": [],
                    "hwaccel_args": [],
                    "input_args": [],
                    "path": "rtsp://ha:REDACTED$@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0",
                    "roles": [
                      "record",
                      "rtmp",
                      "detect"
                    ]
                  }
                ],
                "output_args": {
                  "detect": [
                    "-f",
                    "rawvideo",
                    "-pix_fmt",
                    "yuv420p"
                  ],
                  "record": [
                    "-f",
                    "segment",
                    "-segment_time",
                    "10",
                    "-segment_format",
                    "mp4",
                    "-reset_timestamps",
                    "1",
                    "-strftime",
                    "1",
                    "-c",
                    "copy",
                    "-an"
                  ],
                  "rtmp": [
                    "-c",
                    "copy",
                    "-f",
                    "flv"
                  ]
                }
              },
              "ffmpeg_cmds": [
                {
                  "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://ha:REDACTED$@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/backyard_cam-%Y%m%d%H%M%S.mp4 -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
                  "roles": [
                    "record",
                    "rtmp",
                    "detect"
                  ]
                }
              ],
              "live": {
                "height": 720,
                "quality": 8
              },
              "motion": {
                "contour_area": 99,
                "delta_alpha": 0.2,
                "frame_alpha": 0.2,
                "frame_height": 180,
                "mask": [
                  "1152,399,1920,414,1920,337,1920,0,809,0,0,0,0,546"
                ],
                "threshold": 25
              },
              "mqtt": {
                "bounding_box": true,
                "crop": true,
                "enabled": true,
                "height": 270,
                "quality": 70,
                "required_zones": [],
                "timestamp": true
              },
              "name": "backyard_cam",
              "objects": {
                "filters": {
                  "bear": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  },
                  "cat": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  },
                  "dog": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  },
                  "mouse": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  },
                  "person": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  }
                },
                "mask": "",
                "track": [
                  "person",
                  "cat",
                  "dog",
                  "bear",
                  "mouse"
                ]
              },
              "record": {
                "enabled": true,
                "events": {
                  "max_seconds": 240,
                  "objects": [
                    "person",
                    "car"
                  ],
                  "post_capture": 5,
                  "pre_capture": 5,
                  "required_zones": [],
                  "retain": {
                    "default": 7,
                    "objects": {}
                  }
                },
                "retain_days": 0
              },
              "rtmp": {
                "enabled": false
              },
              "snapshots": {
                "bounding_box": true,
                "clean_copy": true,
                "crop": false,
                "enabled": false,
                "height": null,
                "quality": 70,
                "required_zones": [],
                "retain": {
                  "default": 10,
                  "objects": {}
                },
                "timestamp": false
              },
              "timestamp_style": {
                "color": {
                  "blue": 255,
                  "green": 255,
                  "red": 255
                },
                "effect": null,
                "format": "%m/%d/%Y %H:%M:%S",
                "position": "tl",
                "thickness": 2
              },
              "zones": {}
            },
            "driveway_cam": {
              "best_image_timeout": 60,
              "detect": {
                "enabled": true,
                "fps": 5,
                "height": 1080,
                "max_disappeared": 25,
                "width": 1920
              },
              "ffmpeg": {
                "global_args": [
                  "-hide_banner",
                  "-loglevel",
                  "warning"
                ],
                "hwaccel_args": [],
                "input_args": [
                  "-avoid_negative_ts",
                  "make_zero",
                  "-fflags",
                  "+genpts+discardcorrupt",
                  "-rtsp_transport",
                  "tcp",
                  "-stimeout",
                  "5000000",
                  "-use_wallclock_as_timestamps",
                  "1"
                ],
                "inputs": [
                  {
                    "global_args": [],
                    "hwaccel_args": [],
                    "input_args": [],
                    "path": "rtsp://ha:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0",
                    "roles": [
                      "record",
                      "rtmp",
                      "detect"
                    ]
                  }
                ],
                "output_args": {
                  "detect": [
                    "-f",
                    "rawvideo",
                    "-pix_fmt",
                    "yuv420p"
                  ],
                  "record": [
                    "-f",
                    "segment",
                    "-segment_time",
                    "10",
                    "-segment_format",
                    "mp4",
                    "-reset_timestamps",
                    "1",
                    "-strftime",
                    "1",
                    "-c",
                    "copy",
                    "-an"
                  ],
                  "rtmp": [
                    "-c",
                    "copy",
                    "-f",
                    "flv"
                  ]
                }
              },
              "ffmpeg_cmds": [
                {
                  "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://ha:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway_cam-%Y%m%d%H%M%S.mp4 -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
                  "roles": [
                    "record",
                    "rtmp",
                    "detect"
                  ]
                }
              ],
              "live": {
                "height": 720,
                "quality": 8
              },
              "motion": {
                "contour_area": 99,
                "delta_alpha": 0.2,
                "frame_alpha": 0.2,
                "frame_height": 180,
                "mask": [
                  "1005,606,1177,832,476,1080,397,768",
                  "1920,0,1920,739,933,490,683,0",
                  "0,246,228,248,261,726,0,782"
                ],
                "threshold": 25
              },
              "mqtt": {
                "bounding_box": true,
                "crop": true,
                "enabled": true,
                "height": 270,
                "quality": 70,
                "required_zones": [],
                "timestamp": true
              },
              "name": "driveway_cam",
              "objects": {
                "filters": {
                  "car": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  },
                  "person": {
                    "mask": null,
                    "max_area": 24000000,
                    "min_area": 0,
                    "min_score": 0.5,
                    "threshold": 0.7
                  }
                },
                "mask": "",
                "track": [
                  "person",
                  "car"
                ]
              },
              "record": {
                "enabled": true,
                "events": {
                  "max_seconds": 240,
                  "objects": [
                    "person",
                    "car"
                  ],
                  "post_capture": 5,
                  "pre_capture": 5,
                  "required_zones": [
                    "street_driveway",
                    "main_driveway"
                  ],
                  "retain": {
                    "default": 7,
                    "objects": {}
                  }
                },
                "retain_days": 0
              },
              "rtmp": {
                "enabled": false
              },
              "snapshots": {
                "bounding_box": true,
                "clean_copy": true,
                "crop": false,
                "enabled": false,
                "height": null,
                "quality": 70,
                "required_zones": [
                  "street_driveway",
                  "main_driveway"
                ],
                "retain": {
                  "default": 10,
                  "objects": {}
                },
                "timestamp": false
              },
              "timestamp_style": {
                "color": {
                  "blue": 255,
                  "green": 255,
                  "red": 255
                },
                "effect": null,
                "format": "%m/%d/%Y %H:%M:%S",
                "position": "tl",
                "thickness": 2
              },
              "zones": {
                "main_driveway": {
                  "coordinates": "1463,1080,1173,931,1065,586,1831,873,1744,1080",
                  "filters": {},
                  "objects": [
                    "person"
                  ]
                },
                "street_driveway": {
                  "coordinates": "1846,759,1812,842,1370,681,1475,637",
                  "filters": {},
                  "objects": [
                    "person",
                    "car"
                  ]
                }
              }
            }
          },
          "database": {
            "path": "/db/frigate.db"
          },
          "detect": {
            "enabled": true,
            "fps": 5,
            "height": 720,
            "max_disappeared": null,
            "width": 1280
          },
          "detectors": {
            "coral": {
              "device": "usb",
              "num_threads": 3,
              "type": "edgetpu"
            }
          },
          "environment_vars": {},
          "ffmpeg": {
            "global_args": [
              "-hide_banner",
              "-loglevel",
              "warning"
            ],
            "hwaccel_args": [],
            "input_args": [
              "-avoid_negative_ts",
              "make_zero",
              "-fflags",
              "+genpts+discardcorrupt",
              "-rtsp_transport",
              "tcp",
              "-stimeout",
              "5000000",
              "-use_wallclock_as_timestamps",
              "1"
            ],
            "output_args": {
              "detect": [
                "-f",
                "rawvideo",
                "-pix_fmt",
                "yuv420p"
              ],
              "record": [
                "-f",
                "segment",
                "-segment_time",
                "10",
                "-segment_format",
                "mp4",
                "-reset_timestamps",
                "1",
                "-strftime",
                "1",
                "-c",
                "copy",
                "-an"
              ],
              "rtmp": [
                "-c",
                "copy",
                "-f",
                "flv"
              ]
            }
          },
          "live": {
            "height": 720,
            "quality": 8
          },
          "logger": {
            "default": "info",
            "logs": {}
          },
          "model": {
            "height": 320,
            "labelmap": {},
            "labelmap_path": null,
            "path": null,
            "width": 320
          },
          "motion": null,
          "mqtt": {
            "client_id": "frigate",
            "host": "192.168.141.21",
            "password": "3dzomf1160",
            "port": 1883,
            "stats_interval": 60,
            "tls_ca_certs": null,
            "tls_client_cert": null,
            "tls_client_key": null,
            "tls_insecure": null,
            "topic_prefix": "frigate",
            "user": "lee"
          },
          "objects": {
            "filters": null,
            "mask": "",
            "track": [
              "person"
            ]
          },
          "record": {
            "enabled": true,
            "events": {
              "max_seconds": 240,
              "objects": null,
              "post_capture": 5,
              "pre_capture": 5,
              "required_zones": [],
              "retain": {
                "default": 7,
                "objects": {}
              }
            },
            "retain_days": 0
          },
          "rtmp": {
            "enabled": true
          },
          "snapshots": {
            "bounding_box": true,
            "clean_copy": true,
            "crop": false,
            "enabled": false,
            "height": null,
            "quality": 70,
            "required_zones": [],
            "retain": {
              "default": 10,
              "objects": {}
            },
            "timestamp": false
          },
          "timestamp_style": {
            "color": {
              "blue": 255,
              "green": 255,
              "red": 255
            },
            "effect": null,
            "format": "%m/%d/%Y %H:%M:%S",
            "position": "tl",
            "thickness": 2
          }
        }

**Comment by blakeblackshear** [comment]
I don't see any issues there... There are two levels of expiration here:

1. Cleanup after the first 5 minutes of continuous recording.
2. Cleanup after X days for events

Are either of these working?

**Comment by user897943** [comment]
Please let us have retain days "-1" meaning it will fill up the whole space and then start overwriting the oldest. This is how car dashcams work. Some of us need to record everything 24/7 and don't really need events. For some people AI does not work and we just need a reliable way to record and browse which Frigate offers but it seems like it's impossible to get it to just record 24/7 for all cameras and instead of crashing when the drive is full, it should overwrite the oldest recordings. This should be the default in my opinion, then users can personalize the settings to specify proper retention days if they wish. But on its default state the app must always prioritize storing as much footage as possible. It is the make-or-break in a law enforcement scenario. Three people got arrested this month due to footage that was not captured on events, luckily I have it set to record 24/7.

**Comment by lennartkoopmann** [comment]
```
mqtt:
  host: host.docker.internal
  port: 1883
detectors:
  coral1:
    type: edgetpu
    device: pci

rtmp:
  enabled: false

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 10

objects:
  track:
    - person
    - cat
    - dog

record:
  enabled: true
  retain_days: 2
  events:
    max_seconds: 300
    pre_capture: 10
    post_capture: 10
    retain:
      default: 7

detect:
  fps: 15

cameras:

  front_yard:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  living_room:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  office:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  bedroom:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720

  driveway:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080

  backyard:
    ffmpeg:
      inputs:
        - path: ...
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
```

Here is my config and it does not perform any retention cleaning.
