### ISSUE TITLE
[Support]:   How to protect sensitive yml

### ISSUE THREAD

**Issue by dredvard** [blakeblackshear/frigate#2503]
### Describe the problem you are having

Its not secure having passwords  in the ym .   However I seem to be unable to  use !secret within the config file (standard within hassio yamls)  What is the best approach.

### Version

?

### Frigate config file

```yaml
mqtt:
  host: !secret mqtt_host
  port: 1883
  user: !secret mqtt_user
  password: !secret mqtt_password
  topic_prefix: frigate
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@<ip>
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
could not determine a constructor for the tag '!secret'
  in "<unicode string>", line 2, column 9:
      host: !secret mqtt_host
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

lorex

**Comment by blakeblackshear** [comment]
Frigate's yaml file has nothing to do with homeassistant's config files, so it has no knowledge of the secrets file. Do you store your secrets.yaml file in the same directory as the frigate.yml file?

**Comment by dredvard** [comment]
Yes.  Did a HassOS install (just abandoned supervised as it was too maintenance intensive).  Followed step 5 as per your guide.    
"5. Create the file frigate.yml in your config directory with your detailed Frigate configuration"
Once I replace everything was working perfectly.

I think its just good security practice - especially when we are backing up to github.

Think this is how home assistant does it:
https://github.com/home-assistant/core/blob/7af67d34cfe96a1d4ed02f3cbd26f5e197f3703b/homeassistant/util/yaml/loader.py

ESPHome Add-on uses secrets as well (and as they say just largely copied from home assistant).  
https://github.com/esphome/esphome/blob/55db1908758ff3b5585b01b8563c2549d9784eb9/esphome/yaml_util.py

**Comment by tyzbit** [comment]
Expose environment variables to your Frigate bin/container and reference them in the yaml
```
    cameras:
      frontdoor:
        snapshots:
          timestamp: true
        motion:
          mask:
            - 0,390,190,281,413,219,612,181,842,131,1149,113,1138,0,0,0
        ffmpeg:
          inputs:
            - path: 'rtsp://{FRIGATE_FRONTDOOR_CREDENTIALS}@frontdoor:554'
              roles:
                - detect
                - rtmp
```
