### ISSUE TITLE
Suggestion on mounting /cache on tmpfs

### ISSUE THREAD

**Issue by mattheys** [blakeblackshear/frigate#252]
I would recommend adding a bit in the Readme to mount the cache folder on to tmpfs or another ram based filesystem if possible to reduce wear on SSD's and SD cards.

With 3 cameras keeping 10s cache each I only need about 50MB of cache, but to be safe I've gone with 100MB by adding this to my /etc/fstab and mapping it in my docker-compose.yml file. I know that fstab isn't guaranteed to stay in ram compared to ramfs but ramfs can't be limited in size which could cause other issues.

`none /mnt/frigate-cache tmpfs nodev,nosuid,noexec,nodiratime,size=100M   0 0`

**Comment by danobot** [comment]
Yes I was going to suggest the same. Here is my Docker Compose (feel free to paste into docs)

```
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: '1g' # should work for 5-7 cameras
    image: blakeblackshear/frigate:stable
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <dir>:/config
      - <dir>:/clips
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 100000000  # 1GB
    ports:
      - "5000"
```

**Comment by mattheys** [comment]
Wow, didn't know you could do that direct in compose without having to create a mount point, what version of compase is that as you haven't got the header there.

**Comment by danobot** [comment]
This is in version 3.7 😆

**Comment by mattheys** [comment]
Thanks, was still using 3.5

**Comment by username-ibis** [comment]
It also works in version 3.6. Great solution!

**Comment by mario-tux** [comment]
I'm using this:
```
  frigate:
    container_name: frigate
[...]
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/frigate/data:/config
      - /mnt/cctv/frigate-clips:/clips
    tmpfs: 
      - /cache
[...]
```
It is the same?
