### ISSUE TITLE
[Support]: When the media is set to a locally mounted NFS share it doesn't start

### ISSUE THREAD

**Issue by woolmonkey** [blakeblackshear/frigate#2526]
### Describe the problem you are having

So when I have -v /mnt/share:/media/frigate it hangs on the peewee migrate in the logs.  If I remove that line so it starts up just fine.  If I create a folder on the /root directory to test frigate starts fine.  I have tried multiple NFS mounts and multiple versions of the docker frigate from 0.9 to 0.10 latest beta. It is always the same.  Even with a very simple config.

Also I can send these mounts to other containers or VM's no problem just seems to be the frigate one hanging on them
### Version

0.10.0-14c74e4

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  user: 
  password: 

cameras:
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.2/cam/realmonitor?channel=1&subty>
          roles:
            - rtmp
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-26 06:35:35] frigate.app                    INFO    : Starting Frigate (0.10.0-14c74e4)
Starting migrations
[2021-12-26 06:35:35] peewee_migrate                 INFO    : Starting migrations
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua
