### ISSUE TITLE
[Support]: Frigate Notification Snapshot

### ISSUE THREAD

**Issue by Danny2100** [blakeblackshear/frigate#2527]
### Describe the problem you are having

How do I use the snapshot from the "best image" in the events tab? The notifications are detection frame snapshots. I am only using one stream per camera as it's a blue iris stream I am pulling 1280x720 streams. The best image snapshots are of a much higher quality, have a bounding box and are not zoomed in. 

I tried modifying the blueprint with ```bbox=1``` and it didn't work.

```- action: URI
  title: View Snapshot
  uri: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?bbox=1'
```

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.61
  user: user
  password: pw
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
cameras:
  dining_room_1:
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental 
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://192.168.1.246:81/diningroom1?w=1280&h=720
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      dining_room_walkway:
        coordinates: 92,720,521,594,924,427,760,377,44,586
      dining_room_sitting_area:
        coordinates: 1280,720,1280,574,1025,398,222,720
      dining_room:
        coordinates: 82,566,0,286,370,197,631,391
  dining_room_2:
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental 
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://192.168.1.246:81/diningroom2?w=1280&h=720
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
  outdoor_3:
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental 
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://192.168.1.246:81/outdoor3?w=1280&h=720
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      drive_way:
        coordinates: 234,720,1280,720,1280,477,1280,425,958,305,202,276
  outdoor_4:
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental 
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://192.168.1.246:81/outdoor4?w=1280&h=720
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
  outdoor_2:
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental 
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://192.168.1.246:81/outdoor2?w=1280&h=720
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      front_door:
        coordinates: 913,430,1063,626,1136,577,986,416
      side:
        coordinates: 458,271,880,271,994,720,0,720,0,317
  outdoor_1:
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -flags
        - low_delay
        - -strict
        - experimental 
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - "5000000"
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://192.168.1.246:81/outdoor1?w=1280&h=720
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
objects:
  track:
    - person
    - car
snapshots:
  enabled: True
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Blue Iris

**Comment by Danny2100** [comment]
This is the best image snapshot.
![Screenshot_20211225-062520_Home Assistant](https://user-images.githubusercontent.com/47092714/147410816-07b10e27-85e9-49a8-9fe3-44f373d3af7c.jpg)

**Comment by blakeblackshear** [comment]
> it didn't work

I am not sure what you mean. That url changes what you see when you press the View Snapshot button in the notification. It doesn't change the image sent in the notification. Can you describe what you are trying to accomplish?

**Comment by Danny2100** [comment]
I'm trying to have the image I see before clicking on anything be that image above in the screenshot. Not the detection frame snapshot. Meaning the notification preview image I want it to be the image above.

**Comment by blakeblackshear** [comment]
Post your automation yaml

**Comment by Danny2100** [comment]
```
alias: Frigate Notification
description: ''
use_blueprint:
  path: hunterjm/frigate_notification.yaml
  input:
    camera: outdoor_4
    notify_device: 2d33724ba35dc14184cd04b0893101e2
    cooldown: 32
    base_url: https://link.ui.nabu.casa
```

**Comment by blakeblackshear** [comment]
That's the blueprint yaml. I need the full automation yaml generated from the blueprint to show you where to modify it.

**Comment by Danny2100** [comment]
```
blueprint:
  name: Frigate Notification
  description: "## Frigate Mobile App Notification\n\nThis blueprint will send a notification\
    \ to your device when a Frigate event for the selected camera is fired. The notification\
    \ will initially include the thumbnail of the detection, but will update to include\
    \ actionable notifications allowing you to view the saved clip/snapshot when available,\
    \ or silence the notification for a configurable amount of time.\n\nWith this\
    \ blueprint, you may send the notification to multiple devices by leaving \"Device\"\
    \ blank and instead use a [notification group][1].\n\n### Required entities:\n\
    \  - Frigate Camera Name\n  - Mobile App Device **or** the name of a Notification\
    \ Group\n\n### Optional features:\n  - You can limit notifications to objects\
    \ entering **any** pre-defined [zones][2] in Frigate.\n  - You can specify which\
    \ [zones][2] to be notified about. This must be a list (e.g.):\n    ```yaml\n\
    \    - backyard\n    ```\n  - You can specify what type of [objects][3] to be\
    \ notified about. This must be a list (e.g.):\n    ```yaml\n    - person\n   \
    \ - car\n    ```\n  - You can disable notifications if a presence entity or group\
    \ is \"home\".\n  - You can configure a cooldown for the camera to reduce the\
    \ number of notifications when back-to-back events occur.\n  - You can silence\
    \ future notifications for a defined amount of time through actionable notifications.\
    \ This is helpful in situations where you know you will be triggering detections\
    \ for an extended period of time, like when the kids are playing outside.\n\n\
    [1]: https://companion.home-assistant.io/docs/notifications/notifications-basic#sending-notifications-to-multiple-devices\n\
    [2]: https://blakeblackshear.github.io/frigate/configuration/cameras#zones\n[3]:\
    \ https://blakeblackshear.github.io/frigate/configuration/objects\n"
  domain: automation
  source_url: https://gist.github.com/hunterjm/23c1588a9f2b8b9c2a62ffc364e17f8c
  input:
    camera:
      name: Frigate Camera
      description: The name of the camera as defined in your frigate configuration.
    notify_device:
      name: Device
      description: The device must run the official Home Assistant app to receive
        notifications.
      default: false
      selector:
        device:
          integration: mobile_app
    notify_group:
      name: Notification Group
      description: The name of the notification group to call.
      default: ''
    base_url:
      name: (Optional) Base URL
      description: 'The external url for your Home Assistant instance. This will default
        to a relative URL and will open the clips in the app instead of the browser,
        which may cause issues on some devices.

        '
      default: ''
    zone_filter:
      name: (Optional) Zone Filter
      description: Only notify if object has entered a defined zone.
      default: false
      selector:
        boolean: {}
    zones:
      name: (Optional) Trigger Zones
      description: A list (-) of zones you wish to recieve notifications for.
      default: []
      selector:
        object: {}
    labels:
      name: (Optional) Trigger Objects
      description: A list (-) of objects you wish to recieve notifications for.
      default: []
      selector:
        object: {}
    presence_filter:
      name: (Optional) Presence Filter
      description: Only notify if selected presence entity is not "home".
      default: ''
      selector:
        entity: {}
    cooldown:
      name: (Optional) Cooldown
      description: Delay before sending another notification for this camera after
        the last event.
      default: 30
      selector:
        number:
          max: 300.0
          min: 0.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    silence_timer:
      name: (Optional) Silence Notifications
      description: 'How long to silence notifications for this camera when requested
        as part of the actionable notification.

        '
      default: 30
      selector:
        number:
          max: 300.0
          min: 0.0
          unit_of_measurement: minutes
          mode: slider
          step: 1.0
mode: single
max_exceeded: silent
trigger:
  platform: mqtt
  topic: frigate/events
  payload: !input 'camera'
  value_template: '{{ value_json[''after''][''camera''] }}'
variables:
  id: '{{ trigger.payload_json[''after''][''id''] }}'
  camera: '{{ trigger.payload_json[''after''][''camera''] }}'
  camera_name: '{{ camera | replace(''_'', '' '') | title }}'
  object: '{{ trigger.payload_json[''after''][''label''] }}'
  label: '{{ object | title }}'
  entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
  type: '{{ trigger.payload_json[''type''] }}'
  base_url: !input 'base_url'
  group_target: !input 'notify_group'
  zone_only: !input 'zone_filter'
  input_zones: !input 'zones'
  zones: '{{ input_zones | list }}'
  input_labels: !input 'labels'
  labels: '{{ input_labels | list }}'
  presence_entity: !input 'presence_filter'
condition:
- '{{ type != ''end'' }}'
- '{{ not zone_only or entered_zones|length > 0 }}'
- '{{ not zones|length or zones|select(''in'', entered_zones)|list|length > 0 }}'
- '{{ not labels|length or object in labels }}'
- '{{ not presence_entity or not is_state(presence_entity, ''home'') }}'
action:
- choose:
  - conditions: '{{ not group_target }}'
    sequence:
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      message: A {{ label }} was detected on the {{ camera_name }} camera.
      data:
        tag: '{{ id }}'
        group: frigate-notification-{{ camera }}
        image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
        attachment:
          url: /api/frigate/notifications/{{id}}/thumbnail.jpg
  default:
  - service: notify.{{ group_target }}
    data:
      message: A {{ label }} was detected on the {{ camera_name }} camera.
      data:
        tag: '{{ id }}'
        group: frigate-notification-{{ camera }}
        image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
        attachment:
          url: /api/frigate/notifications/{{id}}/thumbnail.jpg
- repeat:
    sequence:
    - wait_for_trigger:
      - platform: mqtt
        topic: frigate/events
        payload: '{{ id }}'
        value_template: '{{ value_json[''after''][''id''] }}'
      timeout:
        minutes: 2
      continue_on_timeout: false
    - condition: template
      value_template: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
    - choose:
      - conditions: '{{ not group_target }}'
        sequence:
        - device_id: !input 'notify_device'
          domain: mobile_app
          type: notify
          message: A {{ label }} was detected on the {{ camera_name }} camera.
          data:
            tag: '{{ id }}'
            group: frigate-notification-{{ camera }}
            url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            clickAction: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
            sound: none
            attachment:
              url: /api/frigate/notifications/{{id}}/thumbnail.jpg
            actions:
            - action: URI
              title: View Clip
              uri: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            - action: URI
              title: View Snapshot
              uri: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?bbox=1'
            - action: silence-{{ camera }}
              title: Silence Notifications
              destructive: true
      default:
      - service: notify.{{ group_target }}
        data:
          message: A {{ label }} was detected on the {{ camera_name }} camera.
          data:
            tag: '{{ id }}'
            group: frigate-notification-{{ camera }}
            url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            clickAction: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
            sound: none
            attachment:
              url: /api/frigate/notifications/{{id}}/thumbnail.jpg
            actions:
            - action: URI
              title: View Clip
              uri: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
            - action: URI
              title: View Snapshot
              uri: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?bbox=1'
            - action: silence-{{ camera }}
              title: Silence Notifications
              destructive: true
    until: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
- wait_for_trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: silence-{{ camera }}
  timeout:
    seconds: !input 'cooldown'
  continue_on_timeout: false
- delay:
    minutes: !input 'silence_timer'
```

**Comment by blakeblackshear** [comment]
I was talking about the yaml for the automation created from the blueprint. You can see it if you go into automations in the config section, select your automation, select "Show Trace" > "Automation config". You will need to copy that out into your own custom automation and change all of the `thumbnail.jpg` references to `snapshot.jpg` references. You can also remove the `?format=android` parameter.

**Comment by Danny2100** [comment]
```
mode: single
max_exceeded: silent
trigger:
  platform: mqtt
  topic: frigate/events
  payload: outdoor_4
  value_template: '{{ value_json[''after''][''camera''] }}'
variables:
  id: '{{ trigger.payload_json[''after''][''id''] }}'
  camera: '{{ trigger.payload_json[''after''][''camera''] }}'
  camera_name: '{{ camera | replace(''_'', '' '') | title }}'
  object: '{{ trigger.payload_json[''after''][''label''] }}'
  label: '{{ object | title }}'
  entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
  type: '{{ trigger.payload_json[''type''] }}'
  base_url: https://9bt2eujzbvqlq0g4fuvm46kpz60r6h0o.ui.nabu.casa
  group_target: ''
  zone_only: false
  input_zones: []
  zones: '{{ input_zones | list }}'
  input_labels: []
  labels: '{{ input_labels | list }}'
  presence_entity: ''
condition:
  - '{{ type != ''end'' }}'
  - '{{ not zone_only or entered_zones|length > 0 }}'
  - '{{ not zones|length or zones|select(''in'', entered_zones)|list|length > 0 }}'
  - '{{ not labels|length or object in labels }}'
  - '{{ not presence_entity or not is_state(presence_entity, ''home'') }}'
action:
  - choose:
      - conditions: '{{ not group_target }}'
        sequence:
          - device_id: 2d33724ba35dc14184cd04b0893101e2
            domain: mobile_app
            type: notify
            message: A {{ label }} was detected on the {{ camera_name }} camera.
            data:
              tag: '{{ id }}'
              group: frigate-notification-{{ camera }}
              image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
              attachment:
                url: /api/frigate/notifications/{{id}}/thumbnail.jpg
    default:
      - service: notify.{{ group_target }}
        data:
          message: A {{ label }} was detected on the {{ camera_name }} camera.
          data:
            tag: '{{ id }}'
            group: frigate-notification-{{ camera }}
            image: /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
            attachment:
              url: /api/frigate/notifications/{{id}}/thumbnail.jpg
  - repeat:
      sequence:
        - wait_for_trigger:
            - platform: mqtt
              topic: frigate/events
              payload: '{{ id }}'
              value_template: '{{ value_json[''after''][''id''] }}'
          timeout:
            minutes: 2
          continue_on_timeout: false
        - condition: template
          value_template: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
        - choose:
            - conditions: '{{ not group_target }}'
              sequence:
                - device_id: 2d33724ba35dc14184cd04b0893101e2
                  domain: mobile_app
                  type: notify
                  message: A {{ label }} was detected on the {{ camera_name }} camera.
                  data:
                    tag: '{{ id }}'
                    group: frigate-notification-{{ camera }}
                    url: >-
                      {{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
                    clickAction: >-
                      {{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
                    image: >-
                      /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
                    sound: none
                    attachment:
                      url: /api/frigate/notifications/{{id}}/thumbnail.jpg
                    actions:
                      - action: URI
                        title: View Clip
                        uri: >-
                          {{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
                      - action: URI
                        title: View Snapshot
                        uri: >-
                        {{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?bbox=1
                      - action: silence-{{ camera }}
                        title: Silence Notifications
                        destructive: true
          default:
            - service: notify.{{ group_target }}
              data:
                message: A {{ label }} was detected on the {{ camera_name }} camera.
                data:
                  tag: '{{ id }}'
                  group: frigate-notification-{{ camera }}
                  url: >-
                    {{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
                  clickAction: >-
                    {{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
                  image: >-
                    /api/frigate/notifications/{{id}}/thumbnail.jpg?format=android
                  sound: none
                  attachment:
                    url: /api/frigate/notifications/{{id}}/thumbnail.jpg
                  actions:
                    - action: URI
                      title: View Clip
                      uri: >-
                        {{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
                    - action: URI
                      title: View Snapshot
                      uri: >-
                        {{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg?bbox=1
                    - action: silence-{{ camera }}
                      title: Silence Notifications
                      destructive: true
      until: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: silence-{{ camera }}
    timeout:
      seconds: 32
    continue_on_timeout: false
  - delay:
      minutes: 30
id: '1640340866850'
alias: Frigate Notification
description: ''
```
