### ISSUE TITLE
[Support]: Bus Errors and Issues Recording

### ISSUE THREAD

**Issue by LordNex** [blakeblackshear/frigate#2533]
### Describe the problem you are having

I tried to look up anything on this first but for all my digging I couldn't find anything. I am getting errors below when running frigate. I'm running it on ESXi 7 with Ubuntu Server 21 LTS. When I had basically the same settings running in the Home Assistant Add On it went perfect and had no errors. Now I'm getting errors, I see the initial stream image but it never updates after that. Clicking on the camera does not bring up a live feed. But in debug, I'm seeing over 5fps going through and saying it's being checked, but if I stand in front of the camera it doesn't register an event. Here is the how too I used to make the build.

I'm currently using it along with DeepStack on a Jetson Nano, and Home Assistant with Double-Take Add On on a separate ESXi 7 server than Frigate. The cameras are a mix of Wyze Pan Cam with RSTP Firmware, Amcrest Doorbell Cams, and Reolink RCL-520A's. I haven't finished the install yet but it will probably be close to 10 cameras when I'm done, mostly PoE Reolinks. I'm trying to phase out the crappy Wyze cams since they decided they aren't going to cater to our market.

Basically, I want it to record continuously holding about 3 days of recordings on my NAS and Holding the Events longer. I believe I have the config file setup correctly but like I said. I can see the initial picture, but after that the image never updates. Any kind of help you could provide is very much appreciated. And thank you for continuing to develop this kick-ass software!

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.1
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: 
  user: user
  # Optional: pas
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  stats_interval: 60
detectors:
  cpu1:
    type: cpu
    num_threads: 10
  cpu2:
    type: cpu
    num_threads: 10
  cpu3:
    type: cpu
    num_threads: 10
  cpu4:
    type: cpu
    num_threads: 10
  cpu5:
    type: cpu
    num_threads: 10
  cpu6:
    type: cpu
    num_threads: 10
ffmpeg:
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -stimeout 5000000 -use_wallclock_as_timestamps 1
cameras:
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camereaip/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1600
      height: 1200
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
  hallcam:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camereaip:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2560
      height: 1920
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true

  sidedoorbell:
    ffmpeg: 
 #     input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://user:pass@camereaip:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1600
      height: 1200
    motion:
      mask:
        - 2560,0,2560,1920,1674,1920,1674,0
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camereaip/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1600
      height: 1200
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true
  deckcam:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camereaip/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1600
      height: 1200
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True
      bounding_box: true



# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 2560
  # Optional: Height of the output resolution (default: shown below)
  height: 1920
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 10
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25


# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: ~0.17% of the motion frame area)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller
  # moving objects.
  contour_area: 75
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 1/6th of the original frame height, but no less than 180)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 360
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks


# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  enabled: true
  # Optional: Number of days to retain recordings regardless of events (default: shown below)
  # NOTE: This should be set to 0 and retention should be defined in events section below
  #       if you only want to retain recordings of events.
  retain_days: 7
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 600
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 30
      # Optional: Per object retention days
      objects:
        person: 180


# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
#    - -hwaccel_output_format
#    - yuv420p
  # Optional: global input args (default: shown below)
#  input_args:
#    - -avoid_negative_ts
#    - make_zero
#    - -fflags
#   - nobuffer
#    - -flags
#    - low_delay
#    - -strict
#    - experimental
 #   - -fflags
 #   - +genpts+discardcorrupt
 #   - -stimeout
 #   - "5000000"
 #   - -use_wallclock_as_timestamps
 #   - "1" 
 #   - -rtsp_transport 
 #   - tcp
# -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
```

### Relevant log output

```shell
Starting frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2021-12-29 00:40:09] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
frigate    | Starting migrations
frigate    | [2021-12-29 00:40:09] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2021-12-29 00:40:09] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2021-12-29 00:40:09] frigate.mqtt                   INFO    : MQTT connected
frigate    | [2021-12-29 00:40:09] detector.cpu2                  INFO    : Starting detection process: 223
frigate    | [2021-12-29 00:40:09] detector.cpu3                  INFO    : Starting detection process: 225
frigate    | [2021-12-29 00:40:09] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2021-12-29 00:40:09] detector.cpu1                  INFO    : Starting detection process: 222
frigate    | [2021-12-29 00:40:09] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2021-12-29 00:40:09] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2021-12-29 00:40:09] detector.cpu4                  INFO    : Starting detection process: 228
frigate    | [2021-12-29 00:40:09] detector.cpu5                  INFO    : Starting detection process: 230
frigate    | [2021-12-29 00:40:09] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2021-12-29 00:40:10] detector.cpu6                  INFO    : Starting detection process: 232
frigate    | [2021-12-29 00:40:10] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2021-12-29 00:40:10] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Output process started: 233
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Camera processor started for livingroom: 236
frigate    | [2021-12-29 00:40:10] ws4py                          INFO    : Using epoll
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Camera processor started for hallcam: 239
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Camera processor started for sidedoorbell: 246
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Camera processor started for frontdoor: 248
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Camera processor started for deckcam: 259
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Capture process started for livingroom: 261
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Capture process started for hallcam: 267
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Capture process started for sidedoorbell: 276
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Capture process started for frontdoor: 280
frigate    | [2021-12-29 00:40:10] frigate.app                    INFO    : Capture process started for deckcam: 286
frigate    | [2021-12-29 00:40:10] ws4py                          INFO    : Using epoll
frigate    | Fatal Python error: Bus error
frigate    |
frigate    | Thread 0x00007f8642dba700 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 302 in wait
frigate    |   File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
frigate    |   File "/usr/lib/python3.8/threading.py", line 870 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Current thread 0x00007f86495bb700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 150 in capture_frames
frigate    |   File "/opt/frigate/frigate/video.py", line 290 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f8649dbc700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 214 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f864a5bd700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/log.py", line 65 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f86511d4740 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
frigate    |   File "/usr/lib/python3.8/threading.py", line 1011 in join
frigate    |   File "/opt/frigate/frigate/video.py", line 321 in capture_camera
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
frigate    |   File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
frigate    |   File "/opt/frigate/frigate/app.py", line 330 in start
frigate    |   File "/opt/frigate/frigate/__main__.py", line 17 in <module>
frigate    |   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
frigate    |   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
frigate    | Fatal Python error: Bus error
frigate    |
frigate    | Thread 0x00007f8642dba700 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 302 in wait
frigate    |   File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
frigate    |   File "/usr/lib/python3.8/threading.py", line 870 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Current thread 0x00007f86495bb700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 150 in capture_frames
frigate    |   File "/opt/frigate/frigate/video.py", line 290 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f8649dbc700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 214 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f864a5bd700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/log.py", line 65 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inFatal Python error: Bus error
frigate    |
frigate    | Thread 0x00007f8642dba700 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 302 in wait
frigate    |   File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
frigate    |   File "/usr/lib/python3.8/threading.py", line 870 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Current thread 0x00007f86495bb700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 150 in capture_frames
frigate    |   File "/opt/frigate/frigate/video.py", line 290 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f8649dbc700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 214 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f864a5bd700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/log.py", line 65 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f86511d4740 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
frigate    |   File "/usr/lib/python3.8/threading.py", line 1011 in join
frigate    |   File "/opt/frigate/frigate/video.py", line 321 in capture_camera
frigate    |   File "/usr/lib/python3.8/muner
frigate    |   File "/usr/liltiprocessing/process.py", line 108 in run
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
frigate    |   File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
frigate    |   File "/opt/frigate/frigate/app.py", line 330 in start
frigate    |   File "/opt/frigate/frigate/__main__.py", line 17 in <module>
frigate    |   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
frigate    |   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
frigate    | b/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f86511d4740 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
frigate    |   File "/usr/lib/python3.8/threading.py", line 1011 in join
frigate    |   File "/opt/frigate/frigate/video.py", line 321 in capture_camera
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
frigate    |   File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
frigate    |   File "/opt/frigate/frigate/app.py", line 330 in start
frigate    |   File "/opt/frigate/frigate/__main__.py", line 17 in <module>
frigate    |   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
frigate    |   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
frigate    | Fatal Python error: Bus error
frigate    |
frigate    | Thread 0x00007f8642dba700 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 302 in wait
frigate    |   File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
frigate    |   File "/usr/lib/python3.8/threading.py", line 870 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Current thread 0x00007f86495bb700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 150 in capture_frames
frigate    |   File "/opt/frigate/frigate/video.py", line 290 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f8649dbc700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 214 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f864a5bd700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/log.py", line 65 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f86511d4740 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
frigate    |   File "/usr/lib/python3.8/threading.py", line 1011 in join
frigate    |   File "/opt/frigate/frigate/video.py", line 321 in capture_camera
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
frigate    |   File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
frigate    |   File "/opt/frigate/frigate/app.py", line 330 in start
frigate    |   File "/opt/frigate/frigate/__main__.py", line 17 in <module>
frigate    |   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
frigate    |   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
frigate    | Fatal Python error: Bus error
frigate    |
frigate    | Thread 0x00007f8642dba700 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 302 in wait
frigate    |   File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
frigate    |   File "/usr/lib/python3.8/threading.py", line 870 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Current thread 0x00007f86495bb700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 150 in capture_frames
frigate    |   File "/opt/frigate/frigate/video.py", line 290 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f8649dbc700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/video.py", line 214 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f864a5bd700 (most recent call first):
frigate    |   File "/opt/frigate/frigate/log.py", line 65 in run
frigate    |   File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
frigate    |   File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
frigate    |
frigate    | Thread 0x00007f86511d4740 (most recent call first):
frigate    |   File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
frigate    |   File "/usr/lib/python3.8/threading.py", line 1011 in join
frigate    |   File "/opt/frigate/frigate/video.py", line 321 in capture_camera
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
frigate    |   File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
frigate    |   File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
frigate    |   File "/opt/frigate/frigate/app.py", line 330 in start
frigate    |   File "/opt/frigate/frigate/__main__.py", line 17 in <module>
frigate    |   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
frigate    |   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
frigate    | [2021-12-29 00:40:27] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38760]
frigate    | [2021-12-29 00:42:20] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38760]
```

### FFprobe output from your camera

```shell
user@server:~/docker-compose/frigate$ sudo ffprobe rtsp://user:pass@ip:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
[7] 127050
[8] 127051

[5]+  Stopped                 sudo ffprobe rtsp://user:pass@ip:554/cam/realmonitor?channel=1
[6]   Done                    subtype=0
```

### Frigate stats

```json
{"deckcam":{"camera_fps":4.73,"capture_pid":288,"detection_fps":0.84,"pid":259,"process_fps":3.6,"skipped_fps":0.0},"detection_fps":2.99,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":211.02,"pid":221},"cpu2":{"detection_start":0.0,"inference_speed":212.23,"pid":223},"cpu3":{"detection_start":0.0,"inference_speed":238.02,"pid":225},"cpu4":{"detection_start":0.0,"inference_speed":243.75,"pid":227},"cpu5":{"detection_start":0.0,"inference_speed":230.4,"pid":229},"cpu6":{"detection_start":0.0,"inference_speed":212.26,"pid":231}},"frontdoor":{"camera_fps":4.3,"capture_pid":284,"detection_fps":1.3,"pid":241,"process_fps":2.5,"skipped_fps":0.0},"hallcam":{"camera_fps":3.96,"capture_pid":271,"detection_fps":0.34,"pid":239,"process_fps":3.3,"skipped_fps":0.0},"livingroom":{"camera_fps":4.49,"capture_pid":265,"detection_fps":0.51,"pid":237,"process_fps":3.6,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":40.8,"mount_type":"tmpfs","total":67.1,"used":26.3},"/media/frigate/clips":{"free":3088248.2,"mount_type":"nfs4","total":3932880.9,"used":844615.9},"/media/frigate/recordings":{"free":3088248.2,"mount_type":"nfs4","total":3932880.9,"used":844615.9},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"uptime":222,"version":"0.9.4-26ae608"},"sidedoorbell":{"camera_fps":4.76,"capture_pid":276,"detection_fps":0.0,"pid":240,"process_fps":4.74,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest AD-410, Wyze Pan Cam, Reolink RCL-520A

### Any other information that may be helpful

I've tried to keep to the resolutions that the cameras should be able to produce. I've also tried playing with hardware acceleration and that didn't work well. My ESXi server has a GPU in it but passing that through to Linux and then to Docker is a pain. Really all I need Frigate to do is to quickly determine if it's a person and log an event through MQTT. After that Double Take and DeepStack take over and that's it. Thus the reason I haven't really gone out of the way and bought a Coral TPU (Currently about $180 on eBay from overseas). The Jetson and DeepStack can do the heavy lifting so if I can just get it to read and record the streams. And then just trigger on anything that has confidence that it's a person of like 70% which I think is the default. Anyway. let me know if there is anything else you need. I'm competent with Wireshark and such but im no expert when it ccomes to encoding and decoding camera streams

**Comment by blakeblackshear** [comment]
Looks like you just need to increase your shm size: https://docs.frigate.video/faqs/#fatal-python-error-bus-error

**Comment by LordNex** [comment]
@blakeblackshear Thank you for your quick reply. LOL i sware i looked through that page. Just didnt see it at the top there sorry.

I went through and double checked and changed all the resolutions to match the stream. I also had a bad mapping to my nas so things wernt being saved properly. 

I did what you said and from a base resolution of 1600x1200. according to your formula, I need about 24.9 mb per stream. So I modified my docker compose file as below. Now it seems like its running better, I'm getting some streams and see the recordings. But these crappy Wyze cams dont want to keep up. Even though I have them set at 1280x1024 they still say invalid l and w args.

I had to limit the amount of processing power it could take from my ESXi server thought. With a 12 core Haswell i7 with only OpenMediaVault running, Frigate was using 19.7ghz. I have a GPU in that box but I've had nothing but trouble trying to get it to integrate. Being that this is a full size server tower, do you suggest a certain TPU for an x79 chipset?

```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "1gb"
#    runtime: nvidia
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./config/frigate.yml:/config/config.yml:ro
      - /mnt/footage:/media/frigate
#      - ./192.168.1.250/nvr/media/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
    environment:
#      - FRIGATE_RTSP_PASSWORD: password
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
  ```
