### ISSUE TITLE
not a bug. Im a (docker) noob

### ISSUE THREAD

**Issue by R5fan** [blakeblackshear/frigate#255]
Sorry I dont know where else to post this. Im a noob, struggling to get this set up as Im new to docker. I installed docker on my Pi 4. Now what? Against my better judgement I tried 
`sudo docker run blakeblackshear/frigate:0.7.0-amd64`

but that errors out with: exec user process caused "exec format error"

If someone feels like doing a video walking us through the installation (on a pi or linux or  even windows), I would greatly appreciate it, and it might help draw some attention to this project, which seems awesome, but rather obscure still.

**Comment by yayitazale** [comment]
Use the standard docker run command that you can find on the docs as follows:

```
docker run --rm \
--name frigate \
--privileged \
-v /dev/bus/usb:/dev/bus/usb \
-v <path_to_config_dir>:/config:ro \
-v /etc/localtime:/etc/localtime:ro \
-p 5000:5000 \
-e FRIGATE_RTSP_PASSWORD='password' \
blakeblackshear/frigate:0.7.0-amd64
```
Remove the `-v /dev/bus/usb:/dev/bus/usb \` line if you are not using the coral accelerator.

You need to create the config.yml and specify the path on <path_to_config_dir> of the docker run command. As a base use the [config file example ](https://github.com/blakeblackshear/frigate/blob/master/config/config.example.yml) of the docs.

**Comment by mattheys** [comment]
Your problem is the fact you are trying to run the AMD64 version on a Raspberry Pi which isn't x86-64 but Arm based. You need to find out if you have a 32 or 64 bit os and pick either `blakeblackshear/frigate:0.7.1-armv7` for 32 bit or `blakeblackshear/frigate:0.7.1-aarch64` for 64bit. Your original command would have partly worked if you had the right version, but with no volumes, ports or devices mapped it wouldn't work very well.

**Comment by R5fan** [comment]
Ok. I had tried copy pasting the command from the doc (and expected AMD64 to be wrong, but couldnt find what to replace it with), but the '\' escapes at the end of each line didnt work for some reason -or maybe the # comment caused the problem-, but copy pasting yours it 'worked'. At least it was a valid command. Big improvement :)

> You need to create the config.yml and specify the path on <path_to_config_dir> of the docker run command. 

To clarify, I need create the config file somewhere on my actual machine, and replace 

> <path_to_config_dir>

with (for instance)

> /home/pi/frigate/

(no <>) and that is where I put config.yml?

> As a base use the config file example of the docs.

First problem there:

`detectors:
  coral:
    type: edgetpu
    device: usb`

Not clear to me how I change that to cpu. Do I replace 'coral' with 'cpu' and no type/device lines?

next issue:

> 
>   clips_dir: /clips
>   cache_dir: /cache

Where am I going to find those, or do I not care?

Thanks a bunch!

**Comment by mattheys** [comment]
I will address your questions at the bottom, but first I would like to say the following.

I would recommend looking at Docker Compose as a way of starting these, it makes it very easy to make changes to your container configuration without leaving a whole bunch of dangling containers, also I would install Portainer as well so you can easily see what is running and clean it up nice and easily.

I prefer to run it as a docker container itself but I haven't documented that and there isn't an official Arm(64) build for it either so google how to install it with Pip.

Create a folder to keep your docker-compose.yml file in e.g. /opt/docker
Put something like this in it, sorry it might not be perfect but you can tweak till it works, I use /opt for docker configuration data and /mnt for data, this way I can just backup my /opt folder and redploy all my containers quickly with their original settings.

```
version: '3.7'

networks:
  internal:
    name: internal
    driver: bridge

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    networks:
      - internal
    restart: always

  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.7.1-aarch64
    privileged: true
    shm_size: '100m'
    networks:
      - internal
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /opt/frigate/config:/config
      - /dev/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
      - /mnt/frigate:/clips
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 75000000 ## 75MB, good for 3 1080p cameras with 10s of cache each, this depends on your setup.
    ports:
      - 5000:5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3m

```
Then from the folder containing your docker-compose file run `docker-compose up -d --remove-orphans`



Now, your assumption about the config file is correct.

I think it will fail over to cpu anyway so you can just leave it as it is.

The /clips and /cache in the config file is about overriding them if you need to, I wouldn't worry about that and just mount the clips folder outside of the container.
