### ISSUE TITLE
[Support]: Parked car detected repeatedly when no motion is present.

### ISSUE THREAD

**Issue by swiney89** [blakeblackshear/frigate#2556]
### Describe the problem you are having

I have a camera facing my driveway where one car is regularly parked in the driveway and another is parked out on the street.

I can't get frigate to stop creating events every few seconds for one of these cars.  I thought I could create an object mask for those two locations (pictured) but they still trigger constantly (pictured).

I'm just trying to get it to stop alerting for two cars that spend almost all day every day in those spots.

### Version

0.9.4-26ae608

### Frigate config file

```yaml
# example config file at https://docs.frigate.video/configuration/index

mqtt:
  host: 192.168.1.50
  user: XXXXXX
  password: XXXXXX

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
  cpu5:
    type: cpu

birdseye:
  enabled: True
  width: 3040
  height: 1440
  quality: 1
  mode: continuous

timestamp_style:
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"
  thickness: 1

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 10
    objects:
      person: 15

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 600
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 30
      objects:
        person: 60

cameras:
  Driveway-South:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXX@192.168.1.51:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXX@192.168.1.51:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        car:
          mask: 
            - 484,253,522,252,565,248,589,229,584,208,579,168,553,115,510,67,485,57,437,57,416,87,424,202,439,237
            - 546,42,627,51,632,99,535,80
    zones:
      driveway:
        coordinates: 704,480,704,397,495,69,335,71,277,148,163,283,40,480
      street:
        coordinates: 0,115,0,167,116,126,276,90,385,75,516,79,704,99,704,30,315,22,139,61

  Backyard-North:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXX@192.168.1.52:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXX@192.168.1.52:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
  Backyard-East:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXX@192.168.1.53:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXX@192.168.1.53:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
  Frontyard-Southwest:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXX@192.168.1.54:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXX@192.168.1.54:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
  Frontyard-Northwest:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXX@192.168.1.55:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXX@192.168.1.55:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
```

### Relevant log output

```shell
Not applicable I don't think.
```

### FFprobe output from your camera

```shell
I'm guessing I did something wrong here.  not sure what it is or if it matters in my case.

swiney89@ubuntu-vm:~$ ffprobe rtsp://XXXXXX@192.168.1.51:554/cam/realmonitor?channel=1&subtype=1
[1] 103673
swiney89@ubuntu-vm:~$ ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x55a697595f00] method DESCRIBE failed: 404 Not Found
rtsp://XXXXXX@192.168.1.51:554/cam/realmonitor?channel=1: Server returned 404 Not Found
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP8M-2599EW (x5)

### Any other information that may be helpful

![Screenshot 2021-12-31 202012](https://user-images.githubusercontent.com/24804203/147842736-8af999ca-7641-4b15-998e-567d3b07c2ee.png)
![Screenshot 2021-12-31 201919](https://user-images.githubusercontent.com/24804203/147842739-b58c6468-646c-44b7-865c-4e9f593c00ac.png)
![Screenshot 2021-12-31 201901](https://user-images.githubusercontent.com/24804203/147842741-3bc4fb4b-04b1-4d26-bc12-3d609a6896a3.png)
