### ISSUE TITLE
[Support]: Recordings corrupt since yesterday (0.10 beta 6)

### ISSUE THREAD

**Issue by Bod1985** [blakeblackshear/frigate#2561]
### Describe the problem you are having

Suddenly since yesterday, my front door camera recordings have stopped working. I’m not aware of anything changing and my back door camera recordings work fine…

These are my logs:

### Version

0.10 Beta 6

### Frigate config file

```yaml
frontdoor:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -vf transpose=1
        detect: -f rawvideo -pix_fmt yuv420p -vf transpose=1
        rtmp: -f flv -vf transpose=1
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.2.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
          roles:
            - record
        - path: http://192.168.2.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
          roles:
            - detect
    rtmp:
      enabled: False
    detect:
      width: 480
      height: 640
      fps: 15
    motion:
      mask:
        - 0,0,0,640,114,640,157,0
        - 480,0,480,640,367,640,222,0
    objects:
      track:
        - person
      mask:
        - 480,254,480,0,247,0
        - 103,640,0,640,0,0,158,0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1000
      quality: 100
```

### Relevant log output

```shell
[2022-01-01 22:26:22] frigate.record                 WARNING : Discarding a corrupt recording segment: frontdoor-20220101222517.mp4,
[2022-01-01 22:26:22] watchdog.frontdoor             INFO    : Waiting for ffmpeg to exit gracefully...,
[2022-01-01 22:26:22] watchdog.frontdoor             INFO    : Terminating the existing ffmpeg process...
```

### FFprobe output from your camera

```shell
[17] 19989
[18] 19990
[19] 19991
[20] 19992
[14]   Done                    app=bcs
[15]   Done                    stream=channel0_main.bcs
[16]   Done                    user=admin
```

### Frigate stats

```json
{"backdoor":{"camera_fps":15.0,"capture_pid":251,"detection_fps":0.0,"pid":247,"process_fps":15.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":15.45,"pid":241}},"frontdoor":{"camera_fps":15.1,"capture_pid":257,"detection_fps":0.0,"pid":249,"process_fps":15.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":1046.9,"mount_type":"tmpfs","total":1048.6,"used":1.6},"/media/frigate/clips":{"free":3726364.2,"mount_type":"cifs","total":3836000.4,"used":109636.1},"/media/frigate/recordings":{"free":3726364.2,"mount_type":"cifs","total":3836000.4,"used":109636.1},"/tmp/cache":{"free":64210.9,"mount_type":"overlay","total":91864.3,"used":22963.5}},"temperatures":{"apex_0":77.3},"uptime":1486,"version":"0.10.0-db1255a"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink RLC-520
