### ISSUE TITLE
[Support]: Viewing snapshots or clips from HA not working since upgrading frigate

### ISSUE THREAD

**Issue by Lybbe77** [blakeblackshear/frigate#2564]
### Describe the problem you are having

Hi,

I've upgraded Frigate from 0.8.x to the latest beta 0.10.0 Beta 6. Since the upgrade i cannot view snapshots or clips from within HA. 

I get the following error:

![Skärmavbild 2022-01-02 kl  10 51 28](https://user-images.githubusercontent.com/68653149/147872270-c50a0d28-dba5-4b8b-9f6f-59bd3173a4b8.png)

Log from HA:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/frigate/media_source.py:795
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: December 31, 2021, 7:39:36 AM (7 occurrences)
Last logged: 10:51:22 AM

[140167863119344] Error handling message: Unknown error
[140167370432032] Error handling message: Unknown error
[140167216708096] Error handling message: Unknown error
[140167637792992] Error handling message: Unknown error
[140167454544944] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 105, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id", ""))
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 82, in async_browse_media
    return await _get_media_item(hass, media_content_id).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 82, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/frigate/media_source.py", line 652, in async_browse_media
    return self._browse_events(
  File "/config/custom_components/frigate/media_source.py", line 724, in _browse_events
    event_items = self._build_event_response(identifier, events)
  File "/config/custom_components/frigate/media_source.py", line 795, in _build_event_response
    title=f"{dt.datetime.fromtimestamp(event['start_time'], DEFAULT_TIME_ZONE).strftime(DATE_STR_FORMAT)} [{int(event['end_time']-event['start_time'])}s, {event['label'].capitalize()} {int(event['top_score']*100)}%]",
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
`

### Version

0.10.0 Beta 6, HA 2021.11.5

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb


#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_v4l2m2m
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

mqtt:
  host: 192.168.x.x
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - '1'

record:
  enabled: False
  retain_days: 0
  events:
    retain:
      default: 10
    


cameras:
  Uppfart:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://user:password@192.168.x.x:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - clips
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
        - 45,144,363,48,347,0,0,0
        - 640,0,640,161,569,170,558,0
        - 376,57,640,74,640,0,366,0
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5

  Framsida:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://user:password@192.168.x.x:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - clips
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
        - 0,210,0,0,395,0
        - 599,75,608,0,332,0,347,56
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5
  Baksida:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtmp://user:password@192.168.x.x/bcs/channel0_main.bcs?token=xxxxx&channel=0&stream=0&user=user&password=password
          roles:
            - detect
            - rtmp
            - clips
            - record
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    detect:
      width: 2560
      height: 1440
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
    motion:
      mask:
        - 2560,0,2560,379,1806,300,1590,0
        - 596,363,591,503,465,512,454,372
        - 875,463,1019,449,1026,328,875,335
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5
  Garage:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://user:password@192.168.x.x:554/stream2
          roles:
            - detect
            - rtmp
            - clips
            - record
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - '1'
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
        cat:
          min_score: 0.5
          threshold: 0.7
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5
```

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/frigate/media_source.py:795
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: December 31, 2021, 7:39:36 AM (7 occurrences)
Last logged: 10:51:22 AM

[140167863119344] Error handling message: Unknown error
[140167370432032] Error handling message: Unknown error
[140167216708096] Error handling message: Unknown error
[140167637792992] Error handling message: Unknown error
[140167454544944] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 105, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id", ""))
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 82, in async_browse_media
    return await _get_media_item(hass, media_content_id).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 82, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/frigate/media_source.py", line 652, in async_browse_media
    return self._browse_events(
  File "/config/custom_components/frigate/media_source.py", line 724, in _browse_events
    event_items = self._build_event_response(identifier, events)
  File "/config/custom_components/frigate/media_source.py", line 795, in _build_event_response
    title=f"{dt.datetime.fromtimestamp(event['start_time'], DEFAULT_TIME_ZONE).strftime(DATE_STR_FORMAT)} [{int(event['end_time']-event['start_time'])}s, {event['label'].capitalize()} {int(event['top_score']*100)}%]",
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
{"Baksida":{"camera_fps":5.3,"capture_pid":249,"detection_fps":0.0,"pid":236,"process_fps":5.3,"skipped_fps":0.0},"Framsida":{"camera_fps":5.0,"capture_pid":242,"detection_fps":0.0,"pid":235,"process_fps":5.0,"skipped_fps":0.0},"Garage":{"camera_fps":5.1,"capture_pid":252,"detection_fps":0.0,"pid":239,"process_fps":5.1,"skipped_fps":0.0},"Uppfart":{"camera_fps":5.1,"capture_pid":241,"detection_fps":0.2,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.98,"pid":398892}},"service":{"storage":{"/dev/shm":{"free":51.6,"mount_type":"tmpfs","total":67.1,"used":15.5},"/media/frigate/clips":{"free":954900.9,"mount_type":"fuse.glusterfs","total":999714.7,"used":44813.8},"/media/frigate/recordings":{"free":954900.9,"mount_type":"fuse.glusterfs","total":999714.7,"used":44813.8},"/tmp/cache":{"free":977.4,"mount_type":"tmpfs","total":1000.0,"used":22.6}},"temperatures":{},"uptime":735517,"version":"0.10.0-db1255a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 410W/410-5MP
