### ISSUE TITLE
[Support]: Object being detected in zone when it shouldn't be?

### ISSUE THREAD

**Issue by NickM-27** [blakeblackshear/frigate#2570]
### Describe the problem you are having

I have my doorbell cam with 3 zones, driveway, front yard, and street. Street only detects "bus" (hoping to catch delivery trucks) and the driveway and front yard both detect person, car, dog, cat. For some reason I have seen a couple of times where a car driving in the street will be detected in the driveway and created an event. (More often than not it doesn't, but it has happened more times than is negligible. I know that the zones are considered based on the bottom middle of the bounding box, but based on the screenshot bounding box and the recorded clip, it makes no sense that the box was anywhere close to the zone.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
front_doorbell_cam:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:pass@ipaddress:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
            - rtmp
        - path: rtsp://admin:pass@ipaddress:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
      width: 720
      height: 576
    record:
      enabled: true
      retain_days: 2
      events:
        pre_capture: 3
        post_capture: 5
        max_seconds: 180
        retain:
          default: 15
        required_zones:
          - driveway
          - front_yard
          - street
    objects:
      track:
        - bus
        - car
        - cat
        - dog
        - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 15
        objects:
          person: 7
      required_zones:
        - driveway
        - front_yard
        - street
    motion:
      mask:
        - 720,0,720,214,591,252,397,251,277,0
    zones:
      driveway:
        coordinates: 224,399,0,367,0,363,0,550
        objects:
          - car
          - cat
          - dog
          - person
      front_yard:
        coordinates: 0,576,720,576,720,425,613,382,447,406,227,401,0,552
        objects:
          - cat
          - dog
          - person
      street:
        coordinates: 0,277,720,258,720,304,607,313,607,348,269,367,0,334
        objects:
          - bus
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":65.8,"pid":218}},"doggo_cam":{"camera_fps":5.0,"capture_pid":226,"detection_fps":0.0,"pid":224,"process_fps":0.0,"skipped_fps":0.0},"front_doorbell_cam":{"camera_fps":5.0,"capture_pid":228,"detection_fps":0.0,"pid":225,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":5364.3,"mount_type":"tmpfs","total":5368.7,"used":4.4},"/media/frigate/clips":{"free":7451948.3,"mount_type":"fuse.shfs","total":9998848.3,"used":2546900.0},"/media/frigate/recordings":{"free":7451948.3,"mount_type":"fuse.shfs","total":9998848.3,"used":2546900.0},"/tmp/cache":{"free":6233.3,"mount_type":"rootfs","total":7223.5,"used":990.2}},"uptime":86678,"version":"0.9.4-26ae608"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Amcrest AD410

### Any other information that may be helpful

**The zones are shown here. Orange is driveway, blue is front_yard, and yellow is street.**

![debug_zones](https://user-images.githubusercontent.com/14866235/147895600-1e180fd4-7f45-4032-9812-29d31cf56dce.png)

**This is the snapshot that shows the car is a considerable amount of pixels above.**

![detection](https://user-images.githubusercontent.com/14866235/147895598-1c5e3c4c-93a4-4f1a-8e85-b78cba2a6d91.png)

**Showing that this occurred in the driveway zone**

![zone](https://user-images.githubusercontent.com/14866235/147895596-05bd8a10-f318-4eed-aaa0-c2eb202dd49b.png)
