### ISSUE TITLE
Q: CPU load does not trottle back after motion?

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#258]
**Describe the bug**
CPU load does not throttle back after motion(?)

The load on my CPU after restart of the docker container stays around 2.xx and after detection on one or multiple cameras the load never drops below 3.xx. It does not throttle down(?)

Am I alone with this issue?

**Version of frigate**
0.7.1-amd64

**Config file**

```
web_port: 5000

tensorflow_device: usb

mqtt:
  host: 192.168.1.10
  user: username
  password: password
  topic_prefix: frigate

save_clips:
  max_seconds: 300

objects:
  track:
    - person
  filters:
    person:
      min_area: 25000
      max_area: 100000
      threshold: 0.8
      min_score: 0.5

cameras:
  cam9_uppfart:
    ffmpeg:
      input: rtsp://usr:passwd@192.168.1.38:554/Streaming/Channels/1
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    take_frame: 1
    fps: 8
    best_image_timeout: 60
    save_clips:
      enabled: False
      pre_capture: 30
    snapshots:
      show_timestamp: True
      draw_zones: True
      draw_bounding_boxes: True

```

**Computer Hardware**
 - OS: Debian 
 - Virtualization: No, bare metal
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: DS-2CD2T42WD-I5
 - Resolution: 2688x1520
 - FPS: 8
