### ISSUE TITLE
[Feature]: Exclude cameras from birdseye

### ISSUE THREAD

**Issue by orson1282** [blakeblackshear/frigate#2582]
I would like to be able to exclude cameras from the birdseye view.

Maybe this can be accomplished with an exclude key to specifically exclude cameras or an include key to only include specific cameras.
```
birdseye:
  enabled: True
  mode: objects
  include:
    - frontdoor
    - backyard
  exclude:
    - livingroom
    - kitchen
```
