### ISSUE TITLE
[Support]: Some MQTT Topics are not sent by frigate

### ISSUE THREAD

**Issue by stephanfletzberger** [blakeblackshear/frigate#2583]
### Describe the problem you are having

Some mqtt topics (e.g. frigate/events) are not available in MQTT.

<img width="588" alt="Bildschirmfoto 2022-01-03 um 21 31 09" src="https://user-images.githubusercontent.com/17008970/147977266-7b408b22-cfe5-4a23-82d1-4aae838d0b75.png">

All topics for the configured cameras are there as well as the "available" topic, but no topic for 

### Version

0.10.0-DB1255A

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.150
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: --password--

  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  nord-garage:
    ffmpeg:
      inputs:
        - path: --path--
          roles:
            - recording
            - detect
    motion:
      mask:
        - 594,1920,1080,1920,1080,854,751,798
    objects:
      filters:
        car:
          mask:
            - 1080,859,606,791,653,304,0,300,0,1920,1080,1920
  nord-eingang:
    ffmpeg:
      inputs:
        - path: --path--
          roles:
            - recording
            - detect
  ost:
    ffmpeg:
      inputs:
        - path: --path--
          roles:
            - recording
            - detect
    motion:
      mask:
        - 720,0,720,389,439,334,435,0
  sud:
    ffmpeg:
      inputs:
        - path: --path--
          roles:
            - recording
            - detect        
  west:
    ffmpeg:
      inputs:
        - path: --path--
          roles:
            - recording
            - detect  
    motion:
      mask:
        - 583,0,563,128,203,99,206,0
    zones:
      garten:
        coordinates: 0,1920,660,1920,815,755,0,667
      dach:
        coordinates: 848,201,850,515,0,432,0,336,0,233,176,143
 
           
# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 1280
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 6
# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 720
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1280
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 6
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 30
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d.%m.%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 1
# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  coral_pci:
    type: edgetpu
    device: pci
record:
  enabled: True
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 14
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 20
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: ~0.17% of the motion frame area)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller
  # moving objects.
  contour_area: 75
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 1/6th of the original frame height, but no less than 180)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 220
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False
```

### Relevant log output

```shell
[2022-01-03 20:28:54] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)
Starting migrations
[2022-01-03 20:28:54] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-01-03 20:28:54] peewee_migrate                 INFO    : There is nothing to migrate
[2022-01-03 20:28:54] frigate.mqtt                   INFO    : MQTT connected
[2022-01-03 20:28:54] detector.coral_pci             INFO    : Starting detection process: 217
[2022-01-03 20:28:54] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-01-03 20:28:54] ws4py                          INFO    : Using epoll
[2022-01-03 20:28:54] frigate.app                    INFO    : Output process started: 219
[2022-01-03 20:28:54] frigate.edgetpu                INFO    : TPU found
[2022-01-03 20:28:54] frigate.app                    INFO    : Camera processor started for nord-garage: 239
[2022-01-03 20:28:55] frigate.app                    INFO    : Camera processor started for nord-eingang: 241
[2022-01-03 20:28:55] frigate.app                    INFO    : Camera processor started for ost: 242
[2022-01-03 20:28:55] frigate.app                    INFO    : Camera processor started for sud: 244
[2022-01-03 20:28:55] frigate.app                    INFO    : Camera processor started for west: 245
[2022-01-03 20:28:55] frigate.app                    INFO    : Capture process started for nord-garage: 247
[2022-01-03 20:28:55] frigate.app                    INFO    : Capture process started for nord-eingang: 251
[2022-01-03 20:28:55] frigate.app                    INFO    : Capture process started for ost: 254
[2022-01-03 20:28:55] frigate.app                    INFO    : Capture process started for sud: 260
[2022-01-03 20:28:55] frigate.app                    INFO    : Capture process started for west: 262
[2022-01-03 20:28:55] ws4py                          INFO    : Using epoll
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Hikvision
