### ISSUE TITLE
[Support]: Errno 21 Is a directory

### ISSUE THREAD

**Issue by Elomaple** [blakeblackshear/frigate#2585]
### Describe the problem you are having

Complete and total newbie here, but I've made it this far. 

Whenever I run docker-compose up I get:

"Errno 21   Is a Directory:  '/config/config.yml'

My docker-compose.yml is located at Users/me/Frigate and my config.yml is located at Users/me/Frigate/config. The paths are written as such in the docker-compose.yml file (don't have access to those files at the moment but can post them later).

I've read the threads here with the Errno 21 issue and didn't get anywhere. It's a file, not a Directory! I don't know what I'm doing wrong. 

Any suggestions?

### Version

Amd64

### Frigate config file

```yaml
Can post later.
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Reolink

### Any other information that may be helpful

Ubuntu

**Comment by NickM-27** [comment]
@Elomaple the `config.yml` isn't stored in a config directory but in the base. So move it back one step `../` and it should be good. I had the same thought when I first set it up.

**Comment by Elomaple** [comment]
@NickM-27 I'm so new to this...could you explain what you mean by move it back one step?

**Comment by NickM-27** [comment]
@Elomaple So right now you have it in `Users/me/frigate/config/config.yml` I am suggesting that you instead move it to `Users/me/frigate/config.yml`

**Comment by Elomaple** [comment]
Ah yeah, already tried that, same error. I'm wondering if I need to move the file to the home directory maybe? 

So what you suggested worked for you right? Is your config file on your host machine or in the home directory of Linux?

Forgive me if that doesn't make sense...5 days ago I had never used Linux or docker!

**Comment by NickM-27** [comment]
I am running Unraid, so HomeAssistant and Frigate are both in separate docker containers. My config file is under `mnt/user/appdata/frigate/config.yml`. All it really depends on it your docker script and what that is set to, in Unraid it gives me a UI to set these variables, 

![image](https://user-images.githubusercontent.com/14866235/148157805-028c44ce-b322-46a8-b5c9-9e5783ccb458.png)

**Comment by Elomaple** [comment]
I see. The error seems to say that /config/config.yml is the directory, NOT my file path to the left of the ':'

But /config/config.yml and /media/frigate etc are created automatically in the container, right? 

I'm not supposed to have created those folders/files on my local machine, right?

**Comment by NickM-27** [comment]
@Elomaple okay so I think I see what it is. The `config path` needs to just be a directory path. But it seems like you may have put the `config.yml` as part of that variable (not how my `config path` is just directories and doesn't define the file. 

It depends on your setup, I am not as familiar with docker compose but yes I believe that it should create the files for you. By any chance can you paste your docker script here?

**Comment by blakeblackshear** [comment]
You need to create the path and file on your host before starting the container. If you don't, docker will create the path assuming you want a directory. That will cause this error. Clean up the directory created by docker then create a file called config.yml instead according to the docs. Then you can start the container.

**Comment by Elomaple** [comment]
> @Elomaple okay so I think I see what it is. The `config path` needs to just be a directory path. But it seems like you may have put the `config.yml` as part of that variable (not how my `config path` is just directories and doesn't define the file.
> 
> It depends on your setup, I am not as familiar with docker compose but yes I believe that it should create the files for you. By any chance can you paste your docker script here?

@NickM-27 tried that with same result, unfortunately.

**Comment by Elomaple** [comment]
> You need to create the path and file on your host before starting the container. If you don't, docker will create the path assuming you want a directory. That will cause this error. Clean up the directory created by docker then create a file called config.yml instead according to the docs. Then you can start the container.

Hi @blakeblackshear, thanks for the input! Okay, I had suspected something like that occurred based on the reading I've done, so I did stop and remove the container, and removed all volumes, but got the same error when rebuilding the container fresh. 

What command do I need to run to ensure that the bad directory is removed?

**Comment by NickM-27** [comment]
@Elomaple So what config are you running exactly? Are you running a desktop OS with docker-compose downloaded / running, or are you running an OS that comes with docker included?

**Comment by Elomaple** [comment]
@NickM-27 just discovered that I'm probably going to have problems with my setup anyway, because I'm running Linux on WSL 2 on Windows. Running Docker in Linux. But that's not the recommended method so I'll have to back up and install Linux bare metal and try this again!

**Comment by scyto** [comment]
I just did a fresh pull and hit this exact same issue without changing anything my install broke.... didn't move files, didn't change yaml, just did the pull....

```

pi@pi-frigate01:~/frigate $ sudo cat docker-compose.yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/frigate/config.yml:/config/config.yml:ro
      - ~/frigate/store:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "80:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "frigatepassword"

```
