### ISSUE TITLE
[Support]: Lack of events. Overlapping zones to blame?

### ISSUE THREAD

**Issue by flowchartsman** [blakeblackshear/frigate#2593]
### Describe the problem you are having

For some reason, my front yard/driveway camera is not sending events it should be. I was originally having problems with person detection outside of the zones (which resulted in an alert with no snapshot or recording), so in an attempt to fix this I redid my zones and removed what I thought was an incorrect object mask, and now something seems off. I am wondering if it's perhaps because my zone for yard (person) overlaps my zone for driveway (vehicle)? in the [Restricting Zones To Specific Objects](https://docs.frigate.video/configuration/zones#restricting-zones-to-specific-objects) section of the docs, it mentions the zones `entire_yard` and `front_yard_street`, leading me to believe zones could overlap, but it seems that might not be the case? Visually, my zones look something like this, where the blue/purple is `driveway` and the red is `yard`, which mostly overlays it.
![image](https://user-images.githubusercontent.com/926884/148324095-2aac7ffb-cf18-4284-a9a9-5a0809df8a2a.png)

Someone delivered a package to me earlier, so I should have gotten detections on either or both of my `driveway` zone (for vehicle) or my `yard` zone (for person), but instead nothing, so I tore down and re-created the container and then I walked around outside watching the debug view just now, and I noticed that I did not trigger if I was entirely within the bounds of my `driveway` zone.

## Setup/Infrastructure
Sadly, I'm using Reolink cameras, bought before I knew of their issues, so it's using the HTTP streams as detailed in the issues here and suggested config. The "benefit" (at least as I saw it) was that I could use the "balanced" or "ext" stream for detection, as I'd read here that it's a nice balance between "fluent" and "clear".  My "front" camera is an **RLC-820A**, hence the slightly different resolution in the config, and also the reason I'm using the ext stream for recording, since the "main" stream is unusable. The rest are **RLC-520**s.

Frigate is running with a coral USB in plain docker with compose on proxmox in an LXC container with the `debian-10-turnkey-core_16.1-1_amd64` template. The passthroughs for both the coral and the graphics card seem fine. My inference speed hovers around 8, which I gather is fine with the FPS settings I've got? I'm honestly not sure what I _should_ be getting. CPU usage hovers around 12%, according to proxmox.

The VM also has two virtual NICs, one in the "service" vlan, which is where it sits with Home Assistant, and one in the "camera" vlan, which it only shares with the cameras themselves. All on the same switch.

## Config
(see below)
I realize there's a lot going on here, but if anything jumps out, even if it's not related to my issue, please feel free to comment as I want to make sure I'm using best practices.

## Compose
```yaml
version: "3.6"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: '256mb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config.yml:/config/config.yml:ro
      - /root/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "<service VLAN IP>:5000:5000"
      - "<service VLAN IP>:1935:1935" # RTMP feeds
    environment:
      FRIGATE_MQTT_PASSWORD: "<redacted"
      FRIGATE_CAM_USER: "<redacted>"
      FRIGATE_CAM_PASSWORD: "<redacted>"
```

Any help is most appreciated!

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: <hass server>
  user: <mqtt user>
  topic_prefix: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
detectors:
  coral:
    type: edgetpu
    device: usb
model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
objects:
  track:
    - person
    - vehicle
record:
  enabled: True
  # Do not retain non-events
  retain_days: 0
  events:
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    #   - vehicle
    retain:
      # retain recordings for five days
      default: 5
      # Optional: Per object retention days
      #objects:
      #  person: 5
snapshots:
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  bounding_box: False
  crop: False
  retain:
    # Required: Default retention days (default: shown below)
    default: 4
    # Optional: Per object retention days
    # objects:
    #   person: 4
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects
cameras:
  front:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
            - detect
            - rtmp
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer+genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
    detect:
        width: 896
        height: 512
        fps: 5
    zones:
      driveway:
        coordinates: 0,512,0,298,116,207,273,57,381,45,282,161,190,290,103,450,80,512
        objects:
          - vehicle
      yard:
        coordinates: 0,512,0,166,57,114,252,55,421,24,647,21,896,50,896,512
        objects:
          - person
    motion:
      mask:
        - 714,16,477,19,236,56,0,128,0,0,896,0,896,49
    mqtt:
      required_zones:
        - driveway
        - yard
    record:
        events:
          required_zones:
            - yard
            - driveway
    snapshots:
      required_zones:
        - yard
        - driveway
  back:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    zones:
      yard:
        coordinates: 0,672,0,70,434,30,896,88,896,672
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
  bedside:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    motion:
      mask:
        - 518,0,398,34,250,104,356,142,478,123,530,297,599,287,564,114,690,84,639,0
    zones:
      yard:
        coordinates: 896,672,896,191,631,127,0,200,0,672
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
  garage:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    motion:
      mask:
        - 0,0,406,0,405,71,365,106,334,140,305,200,276,229,268,307,328,426,405,578,347,672,0,672
        - 829,0,896,0,896,49
    zones:
      yard:
        coordinates: 725,306,670,379,632,473,582,672,361,604,329,495,316,437,247,389,225,334,217,273,361,68,609,58,726,72,727,21,896,48,896,240
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-01-05 22:48:50] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2022-01-05 22:48:50] frigate.app                    INFO    : Creating directory: /media/frigate/recordings
[2022-01-05 22:48:50] frigate.app                    INFO    : Creating directory: /media/frigate/clips
Starting migrations
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Starting migrations
Migrate "001_create_events_table"
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Migrate "001_create_events_table"
sql ('CREATE TABLE IF NOT EXISTS "event" ("id" VARCHAR(30) NOT NULL PRIMARY KEY, "label" VARCHAR(20) NOT NULL, "camera" VARCHAR(20) NOT NULL, "start_time" DATETIME NOT NULL, "end_time" DATETIME NOT NULL, "top_score" REAL NOT NULL, "false_positive" INTEGER NOT NULL, "zones" JSON NOT NULL, "thumbnail" TEXT NOT NULL)',)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : sql ('CREATE TABLE IF NOT EXISTS "event" ("id" VARCHAR(30) NOT NULL PRIMARY KEY, "label" VARCHAR(20) NOT NULL, "camera" VARCHAR(20) NOT NULL, "start_time" DATETIME NOT NULL, "end_time" DATETIME NOT NULL, "top_score" REAL NOT NULL, "false_positive" INTEGER NOT NULL, "zones" JSON NOT NULL, "thumbnail" TEXT NOT NULL)',)
sql ('CREATE INDEX IF NOT EXISTS "event_label" ON "event" ("label")',)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : sql ('CREATE INDEX IF NOT EXISTS "event_label" ON "event" ("label")',)
sql ('CREATE INDEX IF NOT EXISTS "event_camera" ON "event" ("camera")',)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : sql ('CREATE INDEX IF NOT EXISTS "event_camera" ON "event" ("camera")',)
Done 001_create_events_table
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Done 001_create_events_table
Migrate "002_add_clip_snapshot"
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Migrate "002_add_clip_snapshot"
add_column ('event', 'has_clip', <BooleanField: Event.has_clip>)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : add_column ('event', 'has_clip', <BooleanField: Event.has_clip>)
add_column ('event', 'has_snapshot', <BooleanField: Event.has_snapshot>)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : add_column ('event', 'has_snapshot', <BooleanField: Event.has_snapshot>)
Done 002_add_clip_snapshot
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Done 002_add_clip_snapshot
Migrate "003_create_recordings_table"
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Migrate "003_create_recordings_table"
Done 003_create_recordings_table
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Done 003_create_recordings_table
Migrate "004_add_bbox_region_area"
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Migrate "004_add_bbox_region_area"
add_column ('event', 'region', <JSONField: Event.region>)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : add_column ('event', 'region', <JSONField: Event.region>)
add_column ('event', 'box', <JSONField: Event.box>)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : add_column ('event', 'box', <JSONField: Event.box>)
add_column ('event', 'area', <IntegerField: Event.area>)
[2022-01-05 22:48:50] peewee_migrate                 INFO    : add_column ('event', 'area', <IntegerField: Event.area>)
Done 004_add_bbox_region_area
[2022-01-05 22:48:50] peewee_migrate                 INFO    : Done 004_add_bbox_region_area
[2022-01-05 22:48:50] frigate.mqtt                   INFO    : MQTT connected
[2022-01-05 22:48:50] frigate.app                    INFO    : Output process started: 214
[2022-01-05 22:48:50] frigate.app                    INFO    : Camera processor started for front: 216
[2022-01-05 22:48:50] frigate.app                    INFO    : Camera processor started for back: 217
[2022-01-05 22:48:50] frigate.app                    INFO    : Camera processor started for bedside: 219
[2022-01-05 22:48:50] frigate.app                    INFO    : Camera processor started for garage: 221
[2022-01-05 22:48:50] frigate.app                    INFO    : Capture process started for front: 223
[2022-01-05 22:48:50] ws4py                          INFO    : Using epoll
[2022-01-05 22:48:50] frigate.app                    INFO    : Capture process started for back: 233
[2022-01-05 22:48:50] frigate.app                    INFO    : Capture process started for bedside: 234
[2022-01-05 22:48:50] frigate.app                    INFO    : Capture process started for garage: 238
[2022-01-05 22:48:50] ws4py                          INFO    : Using epoll
[2022-01-05 22:48:50] detector.coral                 INFO    : Starting detection process: 213
[2022-01-05 22:48:50] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-01-05 22:48:53] frigate.edgetpu                INFO    : TPU found
```

### FFprobe output from your camera

```shell
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, flv, from 'http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<camera user>&password=<camera password>':
  Metadata:
    displayWidth    : 896
    displayHeight   : 512
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x512, 9 fps, 12.50 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{
    "back": {
        "camera_fps": 5.1,
        "capture_pid": 233,
        "detection_fps": 0.0,
        "pid": 217,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "bedside": {
        "camera_fps": 5.0,
        "capture_pid": 234,
        "detection_fps": 0.0,
        "pid": 219,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 7.96,
            "pid": 213
        }
    },
    "front": {
        "camera_fps": 5.0,
        "capture_pid": 223,
        "detection_fps": 0.0,
        "pid": 216,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "garage": {
        "camera_fps": 5.0,
        "capture_pid": 238,
        "detection_fps": 0.0,
        "pid": 221,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "service": {
        "storage": {
            "/dev/shm": {
                "free": 263.5,
                "mount_type": "tmpfs",
                "total": 268.4,
                "used": 4.9
            },
            "/media/frigate/clips": {
                "free": 12308.4,
                "mount_type": "ext4",
                "total": 15744.3,
                "used": 2613.8
            },
            "/media/frigate/recordings": {
                "free": 12308.4,
                "mount_type": "ext4",
                "total": 15744.3,
                "used": 2613.8
            },
            "/tmp/cache": {
                "free": 993.2,
                "mount_type": "tmpfs",
                "total": 1000.0,
                "used": 6.8
            }
        },
        "uptime": 4074,
        "version": "0.9.4-26ae608"
    }
}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-820A (1x: front) RLC-520 (3x: back, garage, bedside)

### Any other information that may be helpful

FFProbe output is from the `front` camera only, since it's where I've been seeing the problems.

Front motion mask is the upper slice of the view which covers the street, to eliminate processing spent looking at people taking walks in the neighborhood and the occasional car.

The logs are from a fresh re-initialization with compose after clearing out all files in the `media` directory. This is after the package incident, but they encompass the test where I walked around outside and got detects in the yard only.

**Comment by flowchartsman** [comment]
Side note: should I be using:

```
    - -hwaccel_output_format
    - yuv420p
```
In my global arguments or on a per-camera basis?

**Comment by flowchartsman** [comment]
I also just noticed the indentation level for `input_args` for the front cam seems off (not included then?), so perhaps that's a problem, too.

**Comment by flowchartsman** [comment]
detection FPS is also 0, which is odd, is that normal?

**Comment by flowchartsman** [comment]
accidental close, sorry for the spam

**Comment by blakeblackshear** [comment]
> detection FPS is also 0, which is odd, is that normal?

This is normal until motion is detected.

**Comment by blakeblackshear** [comment]
> I noticed that I did not trigger if I was entirely within the bounds of my `driveway` zone

Trigger can mean many different things. Did you see motion boxes when you were in the driveway? What about object boxes? Or are you saying that the events weren't saved? 

I would suggest using the debug view again to determine what is happening.

First, read this section of the docs to better understand how things work: https://docs.frigate.video/configuration/masks#further-clarification

I would turn on motion boxes in the debug view and ensure that motion is being detected when someone is in the front yard. If you don't see motion boxes, check your mask again. If you do, switch off motion boxes and turn on bounding boxes to see what is being detected. You can enable zones and you will see the lines thicken when the zone is active. 

Zones do not impact motion detection or object detection. Objects are detected and tracked regardless of your defined zones. The required zones don't change anything about what you see in the debug view. They only impact whether or not an event is saved when it's over.

**Comment by flowchartsman** [comment]
> Trigger can mean many different things. Did you see motion boxes when you were in the driveway? What about object boxes? Or are you saying that the events weren't saved?

> First, read this section of the docs to better understand how things work: https://docs.frigate.video/configuration/masks#further-clarification

Sorry, you're right, that was unclear. I actually did familiarize myself with that ahead of time, and what I noticed was that neither motion nor object bounding boxes weren't even getting drawn in the driveway, but this may have been a coincidence now that I reconsider, or perhaps it was a combination of the camera being in night mode (black and white) and the the difference in contrast between me on the dark driveway and the (white, snowy) lawn. But in any case, there was a point where I could see myself in the yard being detected as a person with a proper bounding box, yet no event was being fired

I restarted the container after changing a motion mask on an unrelated camera, and notifications started flowing again.  I'm still not clear what's going on here, but at this point I'm pretty comfortable with debugging the logs, so it's probably best to close this issue for now since the primary issue is probably a red herring. I would like to post my config one more time (after I cleaned it up a bit and added the `hwaccel` stuff), just for any final feedback before closing it out.

```yaml
# For debugging
#logger:
#  default: debug
#  logs:
#    peewee: error # too noisy
mqtt:
  host: <mqtt host>
  user: <mqtt user>
  topic_prefix: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -rw_timeout
    - "5000000"
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
detectors:
  coral:
    type: edgetpu
    device: usb
model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
objects:
  track:
    - person
    - vehicle
record:
  enabled: True
  # Do not retain non-events
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    retain:
      # retain recordings for five days
      default: 5
snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  crop: False
  retain:
    default: 5
birdseye:
  enabled: True
  width: 1280
  height: 720.
  quality: 8
  mode: objects
cameras:
  front:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
            - detect
            - rtmp
    detect:
        width: 896
        height: 512
        fps: 5
    zones:
      driveway:
        coordinates: 0,298,116,207,184,138,273,57,381,45,282,161,190,290,117,412
        objects:
          - vehicle
      yard:
        coordinates: 0,512,0,166,57,114,252,55,421,24,647,21,896,50,896,512
        objects:
          - person
    motion:
      mask:
        - 714,16,477,19,236,56,0,128,0,0,896,0,896,49
    mqtt:
      required_zones:
        - driveway
        - yard
    record:
        events:
          required_zones:
            - yard
            - driveway
    snapshots:
      required_zones:
        - yard
        - driveway
  back:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    zones:
      yard:
        coordinates: 0,672,0,70,434,30,896,88,896,672
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
  bedside:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    motion:
      mask:
        - 518,0,398,34,250,104,356,142,478,123,530,297,598,288,564,114,661,87,824,146,833,101,639,0
    zones:
      yard:
        coordinates: 896,672,896,191,631,127,0,200,0,672
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
  garage:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    motion:
      mask:
        - 0,0,406,0,405,71,365,106,334,140,305,200,276,229,268,307,328,426,405,578,347,672,0,672
        - 829,0,896,0,896,49
    zones:
      yard:
        coordinates: 725,306,670,379,632,473,582,672,361,604,329,495,316,437,247,389,225,334,217,273,361,68,609,58,726,72,727,21,896,48,896,240
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
```
