### ISSUE TITLE
[Support]: Cannot allocate memory when accessing clip.mp4 from API

### ISSUE THREAD

**Issue by Bod1985** [blakeblackshear/frigate#2596]
### Describe the problem you are having

The clip url is inaccessible majority of the time, when I check my logs it throws the error on attempted access

### Version

0.10 beta 6

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
logger:
  default: info
  logs:
    frigate.video: debug
    frigate.event: debug 
mqtt:
  host: 192.168.1.3
  user: user
  password: password
snapshots:
  retain:
    default: 15
  crop: false
  bounding_box: True
record:
  enabled: True
  retain:
    days: 0
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 28
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 28
        cat: 2
database:
  path: /config/frigate.db
# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
objects:
  filters:
    cat:
      min_score: 0.2
      threshold: 0.3
    person:
      min_score: 0.4
      threshold: 0.65
cameras:
  backdoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    rtmp:
      enabled: False
    motion:
      mask:
        - 704,0,704,185,343,0
        - 704,480,518,480,704,295
        - 0,480,0,480,237,480,96,0,0,0
        - 365,0,0,0,0,47
    detect:
      width: 704
      height: 480
      fps: 20
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 62000
          mask: 
            - 153,56,260,0,0,0,0,149,0,480,114,480,173,269
            - 704,0,704,156,336,0
            - 524,480,704,480,704,314
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 100
  frontdoor:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -vf transpose=1
        detect: -f rawvideo -pix_fmt yuv420p -vf transpose=1
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.2.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
          roles:
            - record
            - rtmp
        - path: http://192.168.2.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
          roles:
            - detect
    rtmp:
      enabled: False
    detect:
      width: 480
      height: 640
      fps: 15
    motion:
      mask:
        - 0,0,0,640,114,640,157,0
        - 480,0,480,640,367,640,222,0
    objects:
      track:
        - person
      mask:
        - 480,254,480,0,247,0
        - 103,640,0,640,0,0,158,0
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1000
      quality: 100
```

### Relevant log output

```shell
[2022-01-06 10:58:16] frigate.http                   ERROR   : Exception on /events/1641465142.547152-1886me/clip.mp4 [GET]

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/opt/frigate/frigate/http.py", line 250, in event_clip

    return recording_clip(event.camera, event.start_time, event.end_time)

  File "/opt/frigate/frigate/http.py", line 608, in recording_clip

    p = sp.run(

  File "/usr/lib/python3.8/subprocess.py", line 493, in run

    with Popen(*popenargs, **kwargs) as process:

  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child

    self.pid = _posixsubprocess.fork_exec(

OSError: [Errno 12] Cannot allocate memory
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.128000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2592x1944, 20 fps, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{"backdoor":{"camera_fps":20.0,"capture_pid":253,"detection_fps":0.0,"pid":248,"process_fps":20.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.64,"pid":242}},"frontdoor":{"camera_fps":15.1,"capture_pid":258,"detection_fps":0.0,"pid":251,"process_fps":15.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":260.2,"mount_type":"tmpfs","total":262.1,"used":2.0},"/media/frigate/clips":{"free":3693082.1,"mount_type":"cifs","total":3836000.4,"used":142918.3},"/media/frigate/recordings":{"free":3693082.1,"mount_type":"cifs","total":3836000.4,"used":142918.3},"/tmp/cache":{"free":63865.3,"mount_type":"overlay","total":91864.3,"used":23309.0}},"temperatures":{"apex_0":78.05},"uptime":5920,"version":"0.10.0-db1255a"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Armcrest 5MP
