### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by davidcoulson** [blakeblackshear/frigate#2602]
### Describe the problem you are having

I was previously using Frigate as part of HassOS Add-On. I moved it to a container (Running on docker on ubuntu 21.10 inside a LXC) on a different host and moved to the Frigate proxy add-on with HA.

Cameras and detection are working, however when I try to play a clip for an event I get a "The media could not be loaded, either because the server or network failed or because the format is not supported." message in the UI. Developer tools shows that I am getting a 502 back from the server, although nothing appears in the logs. The same behavior occurs if I access Frigate directly via port 5000, or access it using the HA Frigate Proxy Add-on

My clips folder doesn't seem to have any mp4 files in it, so does that mean the clip was never generated?

david@frigate:/mnt/media/clips$ ls -l
total 1290
-rw-r--r-- 1 root root 603144 Jan  6 11:59 garage-1641488358.144566-6ry609-clean.png
-rw-r--r-- 1 root root  48970 Jan  6 11:59 garage-1641488358.144566-6ry609.jpg
-rw-r--r-- 1 root root 593992 Jan  6 12:00 garage-1641488399.742273-sod85i-clean.png
-rw-r--r-- 1 root root  49129 Jan  6 12:00 garage-1641488399.742273-sod85i.jpg

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 10.2.3.6
  user: frigate
  password: XXXXX

logger:
  default: info
#  logs:
#    frigate.mqtt: debug

cameras:
  sunroom:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXX@10.2.4.39:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:XXXX@10.2.4.39:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 1920,1080,0,1080,93,783,163,791,163,906,500,957,568,845,767,814,766,896,920,951,1325,855,1331,707,1363,753,1920,743
    detect:
      enabled: True
      max_disappeared: 25
      width: 704
      height: 480
      fps: 5
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXX@10.2.4.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:XXXX@10.2.4.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 616,305,628,198,649,116,720,91,720,0,0,0,0,576,185,576,136,338
    zones:
      Front Path:
        coordinates: 720,576,720,376,614,365,608,332,288,364,320,503,255,576
    detect:
      enabled: True
      max_disappeared: 25
      fps: 5
      width: 720
      height: 576
  backyard:
    ffmpeg:
      output_args:
        detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 854:480 -c copy -f flv'
      inputs:
        - path: rtsp://hass:HassHass@10.2.3.126:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://hass:HassHass@10.2.3.126:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      Deck:
        coordinates: 349,146,408,145,706,223,753,260,735,318,854,357,854,480,102,480,38,254,25,157,166,118,275,158
      Lawn:
        coordinates: 343,58,577,65,796,118,854,156,854,367,729,313,752,260,698,224,409,145,343,144,281,162,174,125,97,130,117,120,205,67
    detect:
      enabled: True
      max_disappeared: 25
      height: 480
      width: 854
      fps: 5
  garage:
    ffmpeg:
      output_args:
        detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 854:480 -c copy -f flv'
      inputs:
        - path: rtsp://hass:HassHass@10.2.4.33:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://hass:HassHass@10.2.4.33:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 854,0,0,0,0,215,68,210,198,240,312,246,854,358
    zones:
      Driveway Pad:
        coordinates: 0,480,0,331,318,245,854,349,854,480
      Driveway:
        coordinates: 307,242,0,337,0,280,74,245,36,216,86,210,215,240
    detect:
      enabled: True
      max_disappeared: 25
      height: 480
      width: 854
      fps: 5

record:
  enabled: true
  retain_days: 0
  events:
    retain:
      default: 10

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - truck
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75


detectors:
  coral:
    type: edgetpu
    device: pci

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 3

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

amcrest

### Any other information that may be helpful

docker-compose file is below:

version: "3.9"
services:
  frigate:
    container_name: frigate9
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: '256mb'
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate/config.yml:/config/config.yml:ro
      - /mnt/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "camerapass"
      LIBVA_DRIVER_NAME: "radeonsi"
