### ISSUE TITLE
[Support]: Masking out false alarm event recordings caused by light emitting from window & door

### ISSUE THREAD

**Issue by healeydave** [blakeblackshear/frigate#2604]
### Describe the problem you are having

False alarm event recordings due to windows lighting up from hallway, tried to mask out the area but my config doesn't seem to work.

### Version

2.3

### Frigate config file

```yaml
'''cameras:
  Driveway_Bottom:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://user:pass@192.168.1.15:554/Streaming/channels/202
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
          mask:
            - 640,0,640,229,564,206,448,133,0,126,0,0
        dog:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 640,0,640,229,564,206,448,133,0,126,0,0
        car:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 640,0,640,229,564,206,448,133,0,126,0,0
    motion:
      mask:
        - 640,0,640,229,564,206,448,133,0,126,0,0
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3
'''
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

I have posted my Camera config above but I am wondering if I have mis-interpreted how to configure the various sections properly. Reading through the Doc's, it's a little bit confusing whether certain sections should be grouped or segregated in their own right. 

As you can see from the config, there is a mask entered in several times to try and make this area of the footage ignored (as this is where the window and door are that cause the event recording. 

Below is a screenshot of the mask and an event recording showing the lit up window and door which is still happening despite this mask.

<img width="639" alt="Screenshot 2022-01-05 at 10 47 39" src="https://user-images.githubusercontent.com/5435141/148582601-754d1e3f-2a04-49be-8c13-a218e39401e8.png">

<img width="536" alt="Screenshot 2022-01-05 at 10 46 46" src="https://user-images.githubusercontent.com/5435141/148582628-84206cd3-82cf-4266-99ec-957c76987eae.png">
