### ISSUE TITLE
[Support]: Event clip could not be viewed on Frigate Web UI

### ISSUE THREAD

**Issue by gururise** [blakeblackshear/frigate#2605]
### Describe the problem you are having

Some (but not all) recordings are not able to be viewed on the frigate web UI.

![image](https://user-images.githubusercontent.com/4380009/148589938-9e14471f-31cd-4120-8742-ed86d81bb339.png)

**If I try to download the clip, web browser reports the following error:**
- Could not create clip from recordings for rear_1.

**The nginx error.log from the docker container reports:**
`2022/01/07 10:32:26 [error] 204#204: *200 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 171.51.0.1, server: , request: "GET /vod/event/1641551972.196192-3xem3c/index.m3u8 HTTP/1.1", host: "REDACTED_HOST", referrer: "https://REDACTED_HOST/events?camera=rear_1&label=person"`

### Version

0.10.0-db1255a  (Beta 6)

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.3
  user: pub_client
  password: timewarp
detectors:
  coral:
    type: edgetpu
    device: usb
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion
timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "shadow"
record:
  enabled: True
#  retain:
#    days: 7
#    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
cameras:
  front_1:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.2:554/ch1/sub/av_stream
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.2:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - front_sidewalk
          - front_drive
          - storefront
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
          - front_sidewalk
          - front_drive
          - storefront
    motion:
      mask:
        - 0,0,304,0,288,61,0,245
    zones:
      front_sidewalk:
        coordinates: 0,323,0,240,144,140,239,84,298,59,294,80,219,125,80,238
        objects:
          - person
          - bicycle
      front_drive:
        coordinates: 387,0,309,0,296,78,261,100,221,128,165,159,0,318,0,480,205,480
      storefront:
        coordinates: 367,0,704,0,704,480,195,480
        objects:
          - person
          - bicycle
  front_2:                
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.8:554/ch1/sub/av_stream                                
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.8:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704                                            
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - front_sidewalk
          - front_drive
          - storefront
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - front_sidewalk
        - front_drive
        - storefront
    motion:
      mask:
        - 704,0,452,0,440,51,550,117,704,234
    zones:
      front_sidewalk:
        coordinates: 580,182,450,78,449,53,547,112,617,155,704,233,704,308
        objects:
          - person
          - bicycle
      front_drive:
        coordinates: 382,94,376,45,416,51,539,140,620,212,704,307,704,480,523,480,444,240
      storefront:
        coordinates: 0,480,0,0,395,0,395,115,530,480
        objects:
          - person
          - bicycle
  front_3:                
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.6:554/ch1/sub/av_stream                                
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.6:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704                                            
      height: 480
    record:
      enabled: True
      events:
        required_zones: 
          - front_drive
          - front_sidewalk
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - front_drive
        - front_sidewalk
    motion:
      mask:
        - 0,0,617,0,658,43,621,106,526,152,414,209,254,292,153,346,0,427
    zones:
      front_drive:
        coordinates: 704,480,704,155,628,122,263,411,333,480,417,480
      front_sidewalk:
        coordinates: 405,295,619,123,612,103,159,341,0,422,0,480,310,480,241,415
        objects:
          - person
          - bicycle
  rear_side: # Reolink 520
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtmp://192.168.254.9:1935/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=xxxx
          roles:
            - detect
            - rtmp
        - path: rtmp://192.168.254.9:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=xxxx
          roles:
            - record
    detect:
      width: 640
      height: 480 
    record:
      enabled: True
      events:
        required_zones:
          - back_drive
          - entrance_2
          - side_parking
          - storefront
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - back_drive
        - entrance_2
        - side_parking
        - storefront
    motion:
      mask:
        - 322,115,640,363,640,0,118,0,180,23,242,34,359,107
    zones:
      storefront:
        coordinates: 154,319,250,480,0,480,0,130,75,124
        objects:
          - person
          - bicycle
      back_drive:
        coordinates: 26,46,161,37,239,104,26,122
      entrance_2:
        coordinates: 243,30,376,105,227,117,148,35
      side_parking:
        coordinates: 254,480,640,480,640,359,322,112,83,148
  rear_1:                
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.3:554/ch1/sub/av_stream                                
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.3:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704                                            
      height: 480   
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
    zones:
      back_drive:
        coordinates: 373,46,447,52,704,246,704,480,514,480
      back_storefront:
        coordinates: 0,480,514,480,445,225,415,132,395,0,357,0,0,0
        objects:
          - person
          - bicycle
      rear_entry:
        coordinates: 704,31,704,155,576,138,445,62,457,0
        objects:
          - person
          - bicycle
  rear_2:                
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.4:554/ch1/sub/av_stream                                
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.4:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704                                            
      height: 480
    record:
      enabled: True
      events:
        required_zones: 
          - back_drive
          - back_storefront
          - entrance_2
          - front_parking
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - back_drive
        - back_storefront
        - entrance_2
        - front_parking
    motion:
      mask:
        - 116,121,0,170,0,0,283,0,293,71,243,80
    zones:
      back_drive:
        coordinates: 252,480,0,480,0,253,172,126,249,213,300,284
      entrance_2:
        coordinates: 285,345,314,229,300,67,248,71,143,142
      front_parking:
        coordinates: 0,176,62,138,194,98,0,283
      back_storefront:
        coordinates: 257,480,704,480,704,65,501,0,280,0,316,225
        objects:
          - person
          - bicycle
  parking_1:                
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.5:554/ch1/sub/av_stream                                
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.5:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704       
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - front_left
          - front_parking
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - front_left
        - front_parking
        - entrance_2
        - back_drive
        - back_storefront
    motion:
      mask:
        - 0,0,704,0,704,41,674,58,532,38,487,84,403,75,239,85,172,92,60,82,37,109,0,127
    zones:
      front_left:
        coordinates: 488,480,635,266,681,219,704,221,704,480
        objects:
          - person
      front_parking:
        coordinates: 472,107,704,246,704,480,0,480,0,156,40,152,136,126,180,99,336,89,413,89
      entrance_2:
        coordinates: 483,112,552,119,495,88,406,74
      back_drive:
        coordinates: 704,240,704,198,522,100,479,108
      back_storefront:
        coordinates: 704,50,704,205,499,90,521,28
        objects:
          - person
          - bicycle
  parking_2:                
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.7:554/ch1/sub/av_stream                                
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.7:554/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 704       
      height: 480
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
    motion:
      mask:
        - 704,74,704,0,0,0,320,57
    zones:
      back_drive:
        coordinates: 368,480,555,302,293,232,0,341,0,480
      back_parking:
        coordinates: 682,84,680,157,472,315,241,213,230,74
      back_storefront:
        coordinates: 0,40,232,21,248,247,0,334
        objects:
          - person
          - bicycle
      rear_entry:
        coordinates: 505,340,704,398,658,480,352,480
        objects:
          - person
          - bicycle
  parking_3: # Reolink 520
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
        - -c:v
        - h264_cuvid
      inputs:
#        - path: http://192.168.254.10/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=xxxx
        - path: rtmp://192.168.254.10:1935/bcs/channel0_sub.bcs?channel=0&stream=0&user=user&password=xxxx
          roles:
            - detect
            - rtmp
#        - path: http://192.168.254.10/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=xxxx
        - path: rtmp://192.168.254.10:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=xxxx
          roles:
            - record
    detect:
      width: 640
      height: 480 
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
    motion:
      mask:
        - 213,21,294,0,0,0,0,50
    zones:
      rear_entry:
        coordinates: 246,66,279,21,640,0,640,190
        objects:
          - person
          - bicycle
      back_parking:
        coordinates: 0,480,640,480,640,185,256,69,181,21,0,53
  parking_4:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://user:xxxx@192.168.254.11:8554/live1.264
          roles:
            - detect
            - rtmp
        - path: rtsp://user:xxxx@192.168.254.11:8554/live0.264
          roles:
            - record
    detect:
      width: 720
      height: 480
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
    motion:
      mask:
        - 0,150,75,145,58,33,0,39
    zones:
      back_parking:
        coordinates: 720,480,720,102,490,97,282,87,0,162,0,480
      back_right:
        coordinates: 157,62,272,68,273,139,160,151
        objects:
          - person
          - bicycle
      rear_entry:
        coordinates: 0,480,0,150,46,148,105,240,261,480
        objects:
          - person
          - bicycle
```

### Relevant log output

```shell
[2022-01-07 10:31:28] ws4py                          INFO    : Using epoll
[2022-01-07 10:32:13] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35078]
[2022-01-07 10:32:26] frigate.http                   ERROR   : No recordings found for the requested time range
[2022-01-07 10:33:38] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35078]
[2022-01-07 10:40:06] frigate.http                   ERROR   : ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
pipe:: Invalid data found when processing input
```

### FFprobe output from your camera

```shell
[rtsp @ 0x555d119fdf00] max delay reached. need to consume packet
[rtsp @ 0x555d119fdf00] RTP: missed 85 packets
[h264 @ 0x555d11a01c80] concealing 5280 DC, 5280 AC, 5280 MV errors in I frame
Input #0, rtsp, from 'rtsp://username:xxxx@192.168.254.3':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.400333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
```

### Frigate stats

```json
{
  "detection_fps": 76.3,
  "detectors": {
    "coral": {
      "detection_start": 1641580613.965506,
      "inference_speed": 8.01,
      "pid": 225
    }
  },
  "front_1": {
    "camera_fps": 5,
    "capture_pid": 250,
    "detection_fps": 5.4,
    "pid": 231,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "front_2": {
    "camera_fps": 5.1,
    "capture_pid": 252,
    "detection_fps": 11.3,
    "pid": 234,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "front_3": {
    "camera_fps": 5,
    "capture_pid": 256,
    "detection_fps": 0,
    "pid": 235,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "parking_1": {
    "camera_fps": 5.1,
    "capture_pid": 274,
    "detection_fps": 19.2,
    "pid": 243,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "parking_2": {
    "camera_fps": 5,
    "capture_pid": 305,
    "detection_fps": 0,
    "pid": 245,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "parking_3": {
    "camera_fps": 5,
    "capture_pid": 307,
    "detection_fps": 0,
    "pid": 247,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "parking_4": {
    "camera_fps": 5,
    "capture_pid": 312,
    "detection_fps": 29.5,
    "pid": 248,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "rear_1": {
    "camera_fps": 5,
    "capture_pid": 266,
    "detection_fps": 0.1,
    "pid": 240,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "rear_2": {
    "camera_fps": 5,
    "capture_pid": 272,
    "detection_fps": 5,
    "pid": 242,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "rear_side": {
    "camera_fps": 5.1,
    "capture_pid": 260,
    "detection_fps": 5.8,
    "pid": 237,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1064.7,
        "mount_type": "tmpfs",
        "total": 1073.7,
        "used": 9
      },
      "/media/frigate/clips": {
        "free": 3629520.6,
        "mount_type": "ext4",
        "total": 3936911.1,
        "used": 107334.4
      },
      "/media/frigate/recordings": {
        "free": 3629520.6,
        "mount_type": "ext4",
        "total": 3936911.1,
        "used": 107334.4
      },
      "/tmp/cache": {
        "free": 1112,
        "mount_type": "tmpfs",
        "total": 1200,
        "used": 88
      }
    },
    "temperatures": {},
    "uptime": 325,
    "version": "0.10.0-db1255a"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

This only happens on some recordings, and it seems to be happening quite a bit more often in the latest beta's, as I never really had this problem before.
