### ISSUE TITLE
View birdseye in HA card

### ISSUE THREAD

**Issue by golfvert** [blakeblackshear/frigate#2606]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to get the birdseye view in HA lovelace.

I like to be able to see the birdseye view in an HA card. I like to have a quick view of all my cams. Usually birdseye is very efficient when individual camera can be a bit slow...

**Comment by ozrouter** [comment]
You could use the frigate addon.
Use an iframe integration
Use the webpage integration

**Comment by blakeblackshear** [comment]
The lovelace card already supports Birdseye.

**Comment by blakeblackshear** [comment]
Here is an example lovelace config
```yaml
type: custom:frigate-card
camera_entity: camera.back
frigate_camera_name: birdseye
view_default: live
live_provider: frigate-jsmpeg
dimensions: {}
controls:
  nextprev: none
menu_mode: below
menu_buttons:
  live: false
  snapshots: false
  clips: false
  frigate: false
  frigate_ui: false
  fullscreen: true
elements: []
live_preload: false
```

**Comment by remygiraud** [comment]
Thanks!
I have tried I don't see much difference with just this in the card:
`type: custom:frigate-card
camera_entity: camera.back`

I don't understand what this means:
`frigate_camera_name: birdseye`

Is this documented somewhere?

**Comment by ozrouter** [comment]
doesn't appear to be.. but confirmed example working here..

**Comment by blakeblackshear** [comment]
Documented here: https://github.com/dermotduffy/frigate-hass-card#frigate-server-options

**Comment by remygiraud** [comment]
Using HA 2012.12.8, Frigate integration 2.2, Frigate card 2.1, the MVP for the card should be (according the the doc https://github.com/dermotduffy/frigate-hass-card):
```
type: custom:frigate-card
frigate:
  camera_name: birdseye
live:
  provider: frigate-jsmpeg
```

It gives me a black card.
Adding: 
`camera_entity: camera.cam` (cam being an existing camera) doesn't improve the situation.

```
type: custom:frigate-card
camera_entity: camera.cam
frigate:
  camera_name: birdseye
live:
  provider: frigate
```

Works fine... but is not the birdseye :(

Not sure what I have done wrong here...

**Comment by mattkasa** [comment]
@golfvert What I did that worked for me:

- Add a card
- Select a Manual card type
- Copy/paste the example @blakeblackshear gave above (https://github.com/blakeblackshear/frigate/issues/2606#issuecomment-1007987800):
```
type: custom:frigate-card
camera_entity: camera.back
frigate_camera_name: birdseye
view_default: live
live_provider: frigate-jsmpeg
dimensions: {}
controls:
  nextprev: none
menu_mode: below
menu_buttons:
  live: false
  snapshots: false
  clips: false
  frigate: false
  frigate_ui: false
  fullscreen: true
elements: []
live_preload: false
  ```
- Staying in YAML mode, fix the `camera_entity:` to specify a valid camera entity (I don't have a `camera.back`, mine are named differently from his)
- Click `Save`
- Click `Edit` to reopen the card
- There should be an alert saying `An automatic card configuration upgrade is available`, click `Upgrade`
- You should now have a Birdseye card
