### ISSUE TITLE
Coral USB Resets on Proxmox

### ISSUE THREAD

**Issue by flowchartsman** [blakeblackshear/frigate#2607]
### Describe the problem you are having

Went outside tonight to test an automation on person detected in front yard zone.  Nothing. Opened debug view with all options turned no. No bounding boxes drawn of any kind. No detection and no events.

Logs only show this, from earlier:

```
[2022-01-07 21:08:16] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2022-01-07 21:08:16] root                           INFO    : Waiting for detection process to exit gracefully...
[2022-01-07 21:08:46] root                           INFO    : Detection process didnt exit. Force killing...
[2022-01-07 21:08:46] detector.coral                 INFO    : Starting detection process: 73182
[2022-01-07 21:08:46] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-01-07 21:08:49] frigate.edgetpu                INFO    : TPU found
```
And nothing until my websocket connection at 2022-01-08 00:03:17

Proxmox logs indicate the USB device has been "reset"

```
[Thu Jan  6 15:51:33 2022] usb 1-6: reset full-speed USB device number 6 using xhci_hcd
[Fri Jan  7 21:08:35 2022] usb 2-6: reset SuperSpeed USB device number 3 using xhci_hcd
[Fri Jan  7 21:08:35 2022] usb 2-6: LPM exit latency is zeroed, disabling LPM.
```

Frigate now appears to be in a state where running, but simply not detecting anything.

Some digging has offered only sparse suggestions of using a shorter, better quality cable, however this cable is only 2-3 inches long, and supposedly rated for 10Gbps data:

https://www.amazon.com/gp/product/B08NPSX7FF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

The machine is a [Beelink Mini PC SEi10, 16GB RAM](https://www.amazon.com/gp/product/B091CDJBH4/) Running the latest proxmox with frigate in LXC, and it functions perfectly well for most of the day.

I'm confused as to where to go from here. Is this an issue with LPM perhaps?

### Version

0.9.4-26AE608

### Frigate config file

```yaml
#logger:
#  default: debug
#  logs:
#    peewee: error
mqtt:
  host: <hass host>
  user: <mqtt user>
  topic_prefix: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
ffmpeg:
  global_args:
    -hide_banner
    -loglevel error
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -rw_timeout
    - "5000000"
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
detectors:
  coral:
    type: edgetpu
    device: usb
model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
objects:
  track:
    - person
    - vehicle
record:
  enabled: True
  # Do not retain non-events
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    retain:
      default: 5
snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  crop: False
  retain:
    default: 4
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects
cameras:
  front:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
            - detect
            - rtmp
    detect:
        width: 896
        height: 512
        fps: 5
    zones:
      driveway:
        coordinates: 0,298,116,207,184,138,273,57,381,45,282,161,190,290,117,412
        objects:
          - vehicle
      yard:
        coordinates: 0,512,0,166,57,114,252,55,421,24,647,21,896,50,896,512
        objects:
          - person
    motion:
      mask:
        - 714,16,477,19,236,56,0,128,0,0,896,0,896,49
    mqtt:
      required_zones:
        - driveway
        - yard
    record:
        events:
          required_zones:
            - yard
            - driveway
    snapshots:
      required_zones:
        - yard
        - driveway
  back:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    zones:
      yard:
        coordinates: 0,672,0,70,434,30,896,88,896,672
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
  bedside:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    motion:
      mask:
        - 518,0,398,34,250,104,356,142,478,123,530,297,598,288,564,114,661,87,824,146,833,101,639,0
    zones:
      yard:
        coordinates: 896,672,896,191,631,127,0,200,0,672
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
  garage:
    ffmpeg:
      inputs:
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://<camera ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            - rtmp
    detect:
        width: 896
        height: 672
        fps: 5
    motion:
      mask:
        - 0,0,406,0,405,71,365,106,334,140,305,200,276,229,268,307,328,426,405,578,347,672,0,672
        - 829,0,896,0,896,49
    zones:
      yard:
        coordinates: 725,306,670,379,632,473,582,672,361,604,329,495,316,437,247,389,225,334,217,273,361,68,609,58,726,72,727,21,896,48,896,240
        objects:
          - person
    mqtt:
      required_zones:
        - yard
    record:
        events:
          required_zones:
            - yard
    snapshots:
      required_zones:
        - yard
```

### Relevant log output

```shell
:see above:
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolinks
