### ISSUE TITLE
[Support]: Recordings juddering

### ISSUE THREAD

**Issue by Bod1985** [blakeblackshear/frigate#2614]
### Describe the problem you are having

My recordings are juddering/stuttering, most visible whenever there is motion.

An example of a recorded clip (in .mov format as cut the clip down using iPad Photos app); [GDrive link](https://drive.google.com/file/d/11xqNwDk_77j4XcQ5VvHTGGEvf5i3J4fF/view?usp=drivesdk)

An example of a non-stuttering screen recording from my iPad whilst watching via RTSP/WebRTC in Hassio; [GDrive link](https://drive.google.com/file/d/1F510tzouGzYxjH6CamuSTlKcVQh6SxwP/view?usp=drivesdk)

The issue occurs whether I view recording generated by the event api call or whether I grab the clip directly from recordings. It stutters in every application I’ve tried playing it in.

### Version

0.10 beta 6

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
logger:
  default: info
  logs:
    frigate.video: debug
    frigate.event: debug
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel info
  output_args:
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
mqtt:
  host: 192.168.1.3
  user: username
  password: password
snapshots:
  retain:
    default: 15
  crop: false
  bounding_box: True
record:
  enabled: True
  retain:
    days: 1
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 28
      # Optional: Per object retention days
      objects:
        person: 28
        cat: 2
database:
  path: /config/frigate.db
objects:
  filters:
    cat:
      min_score: 0.2
      threshold: 0.3
    person:
      min_score: 0.4
      threshold: 0.65
cameras:
  backdoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    rtmp:
      enabled: False
    motion:
      mask:
        - 704,0,704,185,343,0
        - 704,480,518,480,704,295
        - 0,480,0,480,237,480,96,0,0,0
        - 365,0,0,0,0,47
    detect:
      width: 704
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 62000
          mask: 
            - 153,56,260,0,0,0,0,149,0,480,114,480,173,269
            - 704,0,704,156,336,0
            - 524,480,704,480,704,314
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 1080
      quality: 100
```

### Relevant log output

```shell
No logs showing issues with debug enabled
```

### FFprobe output from your camera

```shell
ffprobe "rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0"
ffprobe version 4.1.8-0+deb10u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, rtsp, from 'rtsp://admin:password@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.128000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2592x1944, 100 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{"backdoor":{"camera_fps":5.1,"capture_pid":253,"detection_fps":0.0,"pid":249,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.95,"pid":241}},"service":{"storage":{"/dev/shm":{"free":260.5,"mount_type":"tmpfs","total":262.1,"used":1.7},"/media/frigate/clips":{"free":3589398.2,"mount_type":"cifs","total":3836000.4,"used":246602.2},"/media/frigate/recordings":{"free":3589398.2,"mount_type":"cifs","total":3836000.4,"used":246602.2},"/tmp/cache":{"free":3962.3,"mount_type":"tmpfs","total":4000.0,"used":37.7}},"temperatures":{"apex_0":74.55},"uptime":787,"version":"0.10.0-db1255a"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW from the official recommendations

### Any other information that may be helpful

CPU usage doesn’t go above 10% during motion events.
