### ISSUE TITLE
No detection in lxc container in proxmox

### ISSUE THREAD

**Issue by OptimusGREEN** [blakeblackshear/frigate#264]
**Describe the bug**
Detection doesn't appear to be working as detection fps and skipped are always 0

**Version of frigate**
latest "stable-amd64" image

**Config file**
Include your full config file wrapped in back ticks.
```
web_port: 5110

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: *******
  topic_prefix: frigate
  user: *****
  password:  *****

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

objects:
  track:
    - person
  filters:
    person:
      min_area: 6000
      max_area: 100000
      threshold: 0.80

cameras:
  garden:
    ffmpeg:
      input: rtsp://ip:port
    take_frame: 1
    mask: garden-mask.bmp
    snapshots:
      show_timestamp: True
    objects:
      track:
        - person
  driveway:
    ffmpeg:
      input: rtsp://ip:port
    take_frame: 1
    mask: driveway-mask.bmp
    snapshots:
      show_timestamp: True
    objects:
      track:
        - person
```

**Logs**
```
On connect called
ffprobe -v panic -show_error -show_streams -of json "rtsp://admin:@192.168.7.111:554"
Starting detection process: 12
Attempting to load TPU as usb
{'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'unknown', 'profile': '77', 'codec_type': 'video', 'codec_time_base': '6/143', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1920, 'height': 1080, 'coded_width': 1920, 'coded_height': 1088, 'closed_captions': 0, 'has_b_frames': 0, 'pix_fmt': 'yuv420p', 'level': 41, 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'false', 'nal_length_size': '0', 'r_frame_rate': '50/1', 'avg_frame_rate': '143/12', 'time_base': '1/90000', 'start_pts': 41022, 'start_time': '0.455800', 'bits_per_raw_sample': '8', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}]}
Creating ffmpeg process...
ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://ip:port -f rawvideo -pix_fmt yuv420p pipe:
ffprobe -v panic -show_error -show_streams -of json "rtsp://ip”:port
TPU found
{'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'unknown', 'profile': '77', 'codec_type': 'video', 'codec_time_base': '6/143', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1920, 'height': 1080, 'coded_width': 1920, 'coded_height': 1088, 'closed_captions': 0, 'has_b_frames': 0, 'pix_fmt': 'yuv420p', 'level': 41, 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'false', 'nal_length_size': '0', 'r_frame_rate': '25/2', 'avg_frame_rate': '143/12', 'time_base': '1/90000', 'start_pts': 42822, 'start_time': '0.475800', 'bits_per_raw_sample': '8', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}]}
Creating ffmpeg process...
ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://ip:port -f rawvideo -pix_fmt yuv420p pipe:
Camera_process started for garden: 38
Camera_process started for driveway: 39
Starting process for driveway: 39
Starting process for garden: 38
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
```

**Frigate debug stats**
```
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":15}},"driveway":{"camera_fps":12.5,"detection_fps":0.0,"ffmpeg_pid":34,"frame_info":{"detect":1603379890.985884,"process":0.0,"read":1603379890.985884},"pid":37,"process_fps":12.5,"read_start":0.0,"skipped_fps":0.0},"garden":{"camera_fps":12.4,"detection_fps":0.0,"ffmpeg_pid":23,"frame_info":{"detect":1603379890.993181,"process":0.0,"read":1603379890.993181},"pid":36,"process_fps":12.5,"read_start":0.0,"skipped_fps":0.0}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
Ffprobe output
garden
root@65119f26b583:/opt/frigate# ffprobe rtsp://ip:port
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://ip:port':
  Metadata:
    title           : h264.mp4
    comment         : TAS-Tech Live Cast
  Duration: N/A, start: 0.495800, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 11.92 fps, 12.50 tbr, 90k tbn, 23.75 tbc

Driveway
root@65119f26b583:/opt/frigate# ffprobe rtsp://ip:port
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://ip:port':
  Metadata:
    title           : h264.mp4
    comment         : TAS-Tech Live Cast
  Duration: N/A, start: 0.555800, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 11.92 fps, 12.50 tbr, 90k tbn, 23.75 tbc
root@65119f26b583:/opt/frigate# 
```

**Screenshots**

**Computer Hardware**
 - OS: linux
 - Virtualization: Proxmox
 - Coral Version: usb
 - Network Setup: wired

**Camera Info:**
 - Manufacturer: no name
 - Resolution: 1080p

**Additional context**

docker compose
```
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: '2g'
    image: blakeblackshear/frigate:stable-amd64
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /home/john/docker/frigate:/config:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=Europe/London
    ports:
      - "5110:5110"
    environment:
      FRIGATE_RTSP_PASSWORD: “*******”
```

lxc config
```
arch: amd64
cores: 2
features: nesting=1
hostname: FrigateLXC
memory: 4096
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=2E:76:AE:5A:58:48,ip=dhcp,ip6=auto,type=veth
ostype: debian
rootfs: local-lvm:vm-115-disk-0,size=12G
swap: 512
lxc.cgroup.devices.allow: c 189:385 rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.mount.entry: /dev/bus/usb/004/002 dev/bus/usb/004/002 none bind,optional,create=file
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:
```

I'm kind of hoping someone who uses proxmox can see an obvious error on my part.

I've tried all sorts of things to get this working on proxmox and have failed. It used to work when i was running ubuntu.
