### ISSUE TITLE
[Support]: detect    ERROR   : [segment @ / pixelated recordings

### ISSUE THREAD

**Issue by Rowleys** [blakeblackshear/frigate#2669]
### Describe the problem you are having

Hi, in my error log I'm getting loads of these error's 

Also, the recording from the camera keeps freezing and going pixelated 

Hope we can fix 

[2022-01-19 09:16:18] ffmpeg.Livingroomcam.detect    ERROR   : [segment @ 0x563677ef4e00] Non-monotonous DTS in output stream 0:1; previous: 204393, current: 198898; changing to 204394. This may result in incorrect timestamps in the output file.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.172
  user: mqtt
  password: ***
  
  
cameras: 
  Livingroomcam: 
    ffmpeg: 
      inputs: 
        - 
          path: "rtsp://192.168.1.93:8554/unicast"
          roles: 
            - detect
 
  driveway: 
    ffmpeg: 
      inputs: 
        - 
          path: "rtsp://***:****0@192.168.1.230/videoMain"
          roles: 
            - detect
            
objects:
  track:
     - person
  mask: 0,0,1000,0,1000,200,0,200
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7
      mask: 0,0,1000,0,1000,200,0,200
            

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: motion
            
ffmpeg:
  output_args:   # detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

            
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
  mask: 0,900,1080,900,1080,1920,0,1920
  
  
detectors:
  coral1:
    type: edgetpu
    device: pci:0
       
record:
  enabled: True
 #   retain_days: 2
  events:
    retain:
      default: 5
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Dahua

![image](https://user-images.githubusercontent.com/77892731/150102742-5686b113-e2ec-4e25-97c4-4e27eafed79a.png)
