### ISSUE TITLE
Polygons and Best.jpg images are not working

### ISSUE THREAD

**Issue by pilievwm** [blakeblackshear/frigate#267]
**Describe the bug**
When I add a polygon to the zone of the camera entity, they are not followed and I have detections even outside these polygons.

**Config file**
```
zones:
  front_steps:
    coordinates: 1149,183,4,763,4,1078,1919,1078,1914,448,1588,363,1419,327,1156,276,1147,207
```

Another question is that the best.jpg file is not created. I've enabled the settings snapshots like this
```
snapshots:
  show_timestamp: True
  draw_zones: False
  draw_bounding_boxes: True
```

And also the main configuration for the paths
```
save_clips:
  clips_dir: /home/coral/video
  cache_dir: /home/coral/cache
```

What else do I miss?
