### ISSUE TITLE
[Support]: error - Could not set performance expectation

### ISSUE THREAD

**Issue by Rowleys** [blakeblackshear/frigate#2670]
### Describe the problem you are having

[2022-01-19 10:18:54] frigate.app                    INFO    : Capture process started for driveway: 229
W driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 42 (Inappropriate ioctl for device)

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.172
  user: mqtt
  password: *****
  
  
cameras: 
  Livingroomcam: 
    ffmpeg: 
      inputs: 
        - 
          path: "rtsp://192.168.1.93:8554/unicast"
          roles: 
            - detect
 
  driveway: 
    ffmpeg: 
      inputs: 
        - 
          path: "rtsp://***:*****@192.168.1.230/videoMain"
          roles: 
            - detect
            
objects:
  track:
     - person
  mask: 0,0,1000,0,1000,200,0,200
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7
      mask: 0,0,1000,0,1000,200,0,200
            

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: motion
            
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c copy -f flv

            
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
  mask: 0,900,1080,900,1080,1920,0,1920
  
live:
  height: 720
  quality: 8
  
timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid
  
detectors:
  coral1:
    type: edgetpu
    device: pci:0
       
record:
  enabled: True
 #   retain_days: 2
  events:
    retain:
      default: 5
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-01-19 10:18:53] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2022-01-19 10:18:54] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-01-19 10:18:54] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-01-19 10:18:54] peewee_migrate                 INFO    : There is nothing to migrate
[2022-01-19 10:18:54] frigate.mqtt                   INFO    : MQTT connected
[2022-01-19 10:18:54] frigate.app                    INFO    : Output process started: 218
[2022-01-19 10:18:54] detector.coral1                INFO    : Starting detection process: 217
[2022-01-19 10:18:54] frigate.app                    INFO    : Camera processor started for Livingroomcam: 221
[2022-01-19 10:18:54] frigate.app                    INFO    : Camera processor started for driveway: 224
[2022-01-19 10:18:54] ws4py                          INFO    : Using epoll
[2022-01-19 10:18:54] frigate.app                    INFO    : Capture process started for Livingroomcam: 226
[2022-01-19 10:18:54] frigate.app                    INFO    : Capture process started for driveway: 229
W driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 42 (Inappropriate ioctl for device)
[2022-01-19 10:18:54] frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
[2022-01-19 10:18:54] frigate.edgetpu                INFO    : TPU found
[2022-01-19 10:18:54] ws4py                          INFO    : Using epoll
[2022-01-19 10:19:32] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38982]
[2022-01-19 10:19:33] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:48154]
```

### FFprobe output from your camera

```shell
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "motion",
    "quality": 15,
    "width": 1280
  },
  "cameras": {
    "Livingroomcam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "width": 1280
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://192.168.1.93:8554/unicast",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.93:8554/unicast -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Livingroomcam-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/Livingroomcam -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "0,900,1080,900,1080,1920,0,1920",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "Livingroomcam",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "0,0,1000,0,1000,200,0,200",
              "0,0,1000,0,1000,200,0,200"
            ],
            "max_area": 100000,
            "min_area": 5000,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "0,0,1000,0,1000,200,0,200",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 5,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": "solid",
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "driveway": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "width": 1280
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://****y:****@192.168.1.230/videoMain",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://***:***@192.168.1.230/videoMain -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/driveway-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/driveway -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "0,900,1080,900,1080,1920,0,1920",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "driveway",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "0,0,1000,0,1000,200,0,200",
              "0,0,1000,0,1000,200,0,200"
            ],
            "max_area": 100000,
            "min_area": 5000,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "0,0,1000,0,1000,200,0,200",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 5,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": "solid",
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": 25,
    "width": 1280
  },
  "detectors": {
    "coral1": {
      "device": "pci:0",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": "-hide_banner -loglevel warning",
    "hwaccel_args": [],
    "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
    "output_args": {
      "detect": "-f rawvideo -pix_fmt yuv420p",
      "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac",
      "rtmp": "-c copy -f flv"
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": {
    "contour_area": 100,
    "delta_alpha": 0.2,
    "frame_alpha": 0.2,
    "frame_height": 180,
    "mask": "0,900,1080,900,1080,1920,0,1920",
    "threshold": 25
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.172",
    "password": "****",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt"
  },
  "objects": {
    "filters": {
      "person": {
        "mask": "0,0,1000,0,1000,200,0,200",
        "max_area": 100000,
        "min_area": 5000,
        "min_score": 0.5,
        "threshold": 0.7
      }
    },
    "mask": "0,0,1000,0,1000,200,0,200",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": true,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 5,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": "solid",
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Dahua - living / Foscam - Driveway
