### ISSUE TITLE
[Support]: Invalid cross-device link error when starting Frigate container

### ISSUE THREAD

**Issue by ianismynameo** [blakeblackshear/frigate#2675]
### Describe the problem you are having

Hi, I was trying to convert my config  and image to version 0.9.4, but when I start the container I get this error:

`[2022-01-19 15:31:41] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[Errno 18] Invalid cross-device link: '/media/frigate/clips/frigate.db' -> '/media/frigate/frigate.db'
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
`

I'm not sure where it's even getting that link from as it's not a volume that I specified. I'm probably missing something obvious here! Thanks

### Version

0.9.4

### Frigate config file

```yaml
mqtt:
  host: [removed]
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate_mqtt
  password: [removed]
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  retain:
    default: 10

cameras:
  house_front:
    ffmpeg:
      inputs:
        - path: rtsp://[removed]@10.18.0.18:81/front&w=2592&h=1944
          roles:
            - record
        - path: rtsp://[removed]@10.1.8.101:554/H265/Streaming/Channels/102/proto=Onvif
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#    clips:
#      enabled: true
#      pre_capture: 10
#      post_capture: 10
#      retain:
#        default: 10
    rtmp:
      enabled: false

    zones:
      street:
        coordinates: 256,135,0,152,8,60,216,63,376,77,442,79,452,31,515,43,640,90,640,157
      driveway:
        coordinates: 64,470,547,475,275,142,72,141
        objects:
          - person
          - cat
          - car
          - dog
      hole:
        coordinates: 0,181,83,165,64,146,0,147
        objects:

  dining_room_cam:
    ffmpeg:
    #  hwaccel_args:
    #   - -hwaccel
    #   - vaapi
    #   - -hwaccel_device
    #   - /dev/dri/renderD128
    #    - -hwaccel_output_format
    #    - yuv420p
       input_args:
          - -avoid_negative_ts
          - make_zero
      #  - -fflags
      #  - +genpts+discardcorrupt
      #  - "1"
      #  - experimental
      #  - "5000000"
       inputs:
         - path: rtsp://[removed]@10.1.5.86//h264Preview_01_main
           roles:
             - record
         - path: rtsp://[removed]@10.1.5.86//h264Preview_01_sub
           roles:
             - detect
    detect:
      width: 640
      height: 480
    rtmp:
      enabled: false

    objects:
      track:
        - dog
        - cat
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: true
      retain:
        default: 10
```

### Relevant log output

```shell
[2022-01-19 15:31:41] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)

[Errno 18] Invalid cross-device link: '/media/frigate/clips/frigate.db' -> '/media/frigate/frigate.db'

[cmd] python3 exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2022-01-19 15:31:50] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)

[Errno 18] Invalid cross-device link: '/media/frigate/clips/frigate.db' -> '/media/frigate/frigate.db'

[cmd] python3 exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2022-01-19 15:32:02] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)

[Errno 18] Invalid cross-device link: '/media/frigate/clips/frigate.db' -> '/media/frigate/frigate.db'
```

### FFprobe output from your camera

```shell
N/A Not able to get Frigate to start
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest, Reolink
