### ISSUE TITLE
[Support]: Config Validation Errors: 'ffmpeg' -- even though I have "ffmpeg:" in HA-config

### ISSUE THREAD

**Issue by plimmplamm** [blakeblackshear/frigate#2680]
### Describe the problem you are having

Hi. First of all. Thanks so much for your help!

I am trying to start frigate on HA OS on rpi4.
When I start the addon the log file says:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-01-21 13:16:22] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

### Version

0.9.4-26ae608

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.XXX
  user: XXX
  password: XXX

ffmpeg:
  hwaccel_args: -c:v h264_v4l2m2m  # Raspberry Pi 3/4 (64-bit OS)

cameras:
  front_camera_frigate:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.0.XXX/bcs/channel0_main.bcs?channel=0&stream=0&user=XXX&password=XXX
          roles:
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 10
    objects:
      track:
        - person
        - car
        - dog
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    clips:
      enabled: true
      pre_capture: 10
      post_capture: 10
      retain:
        default: 10
    record:
      enabled: true
      retain_days: 10
  detectors:
    cpu1:
      type: cpu
    cpu2:
      type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-01-21 13:16:22] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
can't
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Reolink 410
