### ISSUE TITLE
[Support]: Issues with frigate.

### ISSUE THREAD

**Issue by MichalDoom** [blakeblackshear/frigate#2683]
### Describe the problem you are having

Hello,
can you help me with my problems please?
I have 3 Vivotek cameras,the same model with the same settings.

1 of 3 cameras still showing error messages in log.

i have trouble to play some recording events.Some are working some show error.

i would like have "door bell detection" when somebody enter to zone on Door which is on picture,but it is working only from inside to outside.When somebody go out,detection is not working.
Also false positivedetection is presented on this cameras.

I am using after lot of try Frigate Beta 0.10.0
Here are my settings and logs.
Thanks for check.

![image](https://user-images.githubusercontent.com/95631905/150528737-1449eb61-f5b7-4734-9870-b81166d58cf2.png)

![image](https://user-images.githubusercontent.com/95631905/150528752-5226cfee-db3c-4857-9c37-3857af80fbc0.png)

Error message which getting cam Branka and recording cant be play.

cam_auto: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-01-21 11:35:47] frigate.video INFO : cam_auto: ffmpeg process is not running. exiting capture thread...
[2022-01-21 11:35:47] watchdog.cam_vchod ERROR : FFMPEG process crashed unexpectedly for cam_vchod.

Thank You for all help.

### Version

0.10.0

### Frigate config file

```yaml
mqtt:
host: 192.168.3.5
user: mqtt
password: password
topic_prefix: frigate

#ffmpeg:
#input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -use_wallclock_as_timestamps 1 -f live_flv

hwaccel_args:
- -hwaccel
- qsv
- -qsv_device
- /dev/dri/renderD128
record:
enabled: True
retain:
days: 0
mode: motion
events:
retain:
default: 5
mode: active_objects

cameras:
cam_vchod:
ffmpeg:
inputs:
- path: rtsp://192.168.3.252:554/live2.sdp
roles:
- detect
- rtmp
- record
detect:
width: 1280
height: 800
fps: 5
zones:
vchod-branka:
coordinates: 312,87,305,270,601,261,609,94
record:
enabled: true
retain:
days: 0
mode: motion
events:
required_zones:
- vchod-branka
retain:
default: 5
mode: active_objects
objects:
track:
- person
- car
- dog
snapshots:
enabled: true
timestamp: false
bounding_box: false
retain:
default: 10
motion:
mask:
- 1280,0,1280,145,957,106,528,87,0,105,0,0
- 0,800,1280,800,1280,178,546,233,352,240,0,205
threshold: 25
cam_branka:
ffmpeg:
inputs:
- path: rtsp://192.168.3.251:554/live2.sdp
roles:
- detect
- rtmp
- record
detect:
width: 1280
height: 800
fps: 5
record:
enabled: true
retain:
days: 0
mode: motion
events:
retain:
default: 5
mode: active_objects
objects:
track:
- person
- car
- dog
filters:
person:
threshold: 0.5
mask:
- 0,0,1280,0,1280,159,92,57,122,261,562,251,1280,329,1280,800,0,800
car:
threshold: 0.5
mask:
- 0,0,1280,0,1280,159,92,57,122,261,562,251,1280,329,1280,800,0,800
dog:
threshold: 0.3
mask:
- 0,0,1280,0,1280,159,92,57,122,261,562,251,1280,329,1280,800,0,800
snapshots:
enabled: True
timestamp: False
bounding_box: False
retain:
default: 10
motion:
threshold: 20
mask:
- 0,0,1280,0,1280,159,92,57,122,261,562,251,1280,329,1280,800,0,800
cam_auto:
ffmpeg:
inputs:
- path: rtsp://192.168.3.250:554/live2.sdp
roles:
- detect
- rtmp
- record
detect:
width: 1280
height: 800
fps: 5
record:
enabled: true
retain:
days: 0
mode: motion
events:
retain:
default: 5
mode: active_objects
objects:
track:
- person
- car
- dog
filters:
person:
threshold: 0.5
mask:
- 0,361,0,800,480,800,1280,800,1280,172,1202,270,735,293,516,297,322,336
- 0,0,1060,0,1186,0,1280,0,1280,96,1040,151,412,162,0,230,0,109
car:
threshold: 0.7
mask:
- 0,361,0,800,480,800,1280,800,1280,172,1202,270,735,293,516,297,322,336
- 0,0,1060,0,1186,0,1280,0,1280,96,1040,151,412,162,0,230,0,109
dog:
threshold: 0.5
mask:
- 0,361,0,800,480,800,1280,800,1280,172,1202,270,735,293,516,297,322,336
- 0,0,1060,0,1186,0,1280,0,1280,96,1040,151,412,162,0,230,0,109
snapshots:
enabled: True
timestamp: False
bounding_box: False
retain:
default: 5
motion:
threshold: 35
mask:
- 0,361,0,800,480,800,1280,800,1280,172,1202,270,735,293,516,297,322,336
- 0,0,1060,0,1186,0,1280,0,1280,96,1040,151,412,162,0,230,0,109
```

### Relevant log output

```shell
a
```

### FFprobe output from your camera

```shell
a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Vivotek IP8332
