### ISSUE TITLE
[Support]: Frigate NVR Connection refused with external Mqtt

### ISSUE THREAD

**Issue by fwehrle** [blakeblackshear/frigate#2685]
### Describe the problem you are having

Hi,

I just installed the Frigate NVR plugin in my HomeAssistant VM. It work great with the HA's Mqtt plugin, but when I try to connecte frigate on another Mqtt server on my LAN, it won't start and tell "Connection refused". 
Is there a network restriction in HA because frigate is installed as a HA plugin? 
Thank you for helping
Franck

### Version

2.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.14
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  stats_interval: 60
cameras:
  terrasse:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.x:554/Streaming/channels/102/
          roles: 
            - detect
            - rtmp
            - clip
    detect:
        width: 1920
        height: 1080
        fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
  garage:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.x:554/Streaming/channels/102/
          roles: 
            - detect
            - rtmp
            - clip
    detect:
        width: 1920
        height: 1080
        fps: 5
    objects:
      track:
        - person
        - dog
        #- car
        - cat
        - bicycle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
  entree:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.x:554/Streaming/channels/101/
          roles: 
            - detect
            - rtmp
            - clip
    detect:
        width: 2048
        height: 1536
        fps: 5
    objects:
      track:
        - person
        - dog
        - car
        - cat
        - bicycle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
    motion:
        mask:
            - 2048,0,2048,315,1939,301,1909,445,1629,414,1324,428,951,398,431,453,131,586,0,872,0,0
    zones:
        devant_la_maison:
          coordinates: 2048,1536,2048,324,1940,323,1898,382,1617,373,1325,352,1290,416,1199,569,1077,663,934,744,440,791,192,822,0,872,0,1536
        pas_de_la_porte:
          coordinates: 1100,772,1923,690,2048,650,2048,1055,1785,1536,510,1536,0,1536,0,1012
  arriere:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.x:554/Streaming/channels/102/
          roles: 
            - detect
            - rtmp
    detect:
        width: 640
        height: 360
        fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
detectors: 
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2
  cpu3:
    type: cpu
    num_threads: 2
  cpu4:
    type: cpu
    num_threads: 2
```

### Relevant log output

```shell
[Errno 111] Connection refused
[cmd] python3 exited 1
```

### FFprobe output from your camera

```shell
Not necessary
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Not necessary
