### ISSUE TITLE
[Support]: Windows environment + GeForce Nvidia card - How integrated with Frigate?

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#2687]
### Describe the problem you are having

I have Windows 10 machine with an Nvidia GeForce card
I've already installed windows docker and I didn't find the best practice to run my environment with Frigate?

How the Docker-compose.yml should be?

What do I need to install extra?

### Version

latest version 

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.107
  user: "mqttuser"
  password: "123123"
  
rtmp:
  enabled: False
  
  
cameras:
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin1212@192.168.1.123:8554/Streaming/Channels/101
          roles:
            - detect
        - path: rtsp://admin:admin1212@192.168.1.123:8554/Streaming/Channels/102
          roles:
            - record
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70

detect:
  width: 1920
  height: 1080
  fps: 6
  
objects:
  track:
    - person
    - dog
    - cat
  filters:
    person:
      threshold: 0.70



snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  crop: False
  height: 175
  retain:
    default: 14

record:
  enabled: true
  retain_days: 5
  events:
    max_seconds: 900
    pre_capture: 5
    post_capture: 10
    objects:
      - person
    retain:
      # Required: Default retention days (default: shown below)
      default: 3
```

### Relevant log output

```shell
Docker-compose.yml


version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64nvidia
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./www/config.yml:/config/config.yml:ro
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8555:8555" # RTMP feeds
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

none relevant
