### ISSUE TITLE
[Support]: Coral USB regularly crashing

### ISSUE THREAD

**Issue by Kurisutian** [blakeblackshear/frigate#2691]
### Describe the problem you are having

I'm currently experiencing regular crashes from frigate caused when my Coral device is triggered to detect something. 

I've checked the device with another setup and it is working fine there. I'm running it on an intel nuc so there should also be no issue with USB power like I found sometimes with RPi devices. 
Also sometimes it works for 2 or 3 objects being detected but then the same error occurs again taking down frigate entirely. 
The system was running fine for quite some months but all over sudden it stopped with this behavior and no matter what I cannot get it to work reliably.

### Version

0.9.4-26ae608

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb


mqtt:
  host: <HA local URL>
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <password>
  stats_interval: 60


ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

objects:
  track:
    - person
    - car
    - cat
    - dog
    - motorcycle
    - bus
    - truck
    - bicycle
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

record:
  retain_days: 0
  events:
    max_seconds: 300
    retain:
      default: 5
      objects:
        person: 10


timestamp_style:
  position: "tr"
  format: "%d/%m/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: 'solid'

cameras:
#---------------------------------------------------------------------------------------------------------------------------------
# Kamera Eingang
#---------------------------------------------------------------------------------------------------------------------------------

  garten:
    ffmpeg:
      inputs:
        - path: 'rtsp://<user>:<password>@10.2.0.101:554/11'
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      #fps: 25

    motion:
      mask:
        # Datum und Zeit
        # - 1920,0,1920,34,1616,33,1614,0
        # Abdeckung Freisitz
        - 1696,525,1686,480,1705,435,1727,413,1788,428,1839,464,1870,518,1885,588,1842,629,1768,607,1713,565
        # Großer Baum im Beet
        - 1075,98,1107,58,1171,62,1215,75,1243,119,1252,156,1223,181,1249,215,1252,266,1204,263,1155,212,1112,149
        # Punker Baum
    
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        retain:
          default: 5
          objects:
            person: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False
      height: 1080
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

#---------------------------------------------------------------------------------------------------------------------------------
# Kamera Eingang
#---------------------------------------------------------------------------------------------------------------------------------

  eingang:
    ffmpeg:
      inputs:
        - path: 'rtsp://<user>:<password>@10.2.0.102:554/11'
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      #fps: 25

    motion:
      mask:
        # Datum und Zeit
        #- 1920,0,1920,34,1616,33,1614,0
        # Eingangsbereich
        - 859,0,466,320,0,733,0,879,336,1080,1298,1080,1390,96

    objects:
      track:
        - person
        - cat
        - dog

    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        retain:
          default: 5
          objects:
            person: 10

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False
      height: 1080
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 5
        # Optional: Per object retention days
        objects:
          person: 10

#---------------------------------------------------------------------------------------------------------------------------------


#---------------------------------------------------------------------------------------------------------------------------------
# Kamera Wohnzimmer
#---------------------------------------------------------------------------------------------------------------------------------

  wohnzimmer:
    ffmpeg:
      inputs:
        - path: 'rtsp://<user>:<password>@10.2.0.103:554//h264Preview_01_main'
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560
      height: 1920
      #fps: 20

    #motion:
      #mask:
        # Datum und Zeit
        #- 2560,0,2560,89,1775,84,1769,0

    objects:
      track:
        - person

    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        retain:
          default: 7
          objects:
            person: 14

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False
      height: 1080
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 7
        # Optional: Per object retention days
        objects:
          person: 21

#---------------------------------------------------------------------------------------------------------------------------------


#---------------------------------------------------------------------------------------------------------------------------------
# Kamera Garage
#---------------------------------------------------------------------------------------------------------------------------------

  garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://<user>:<password>@10.2.0.104:554//h264Preview_01_main'
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560
      height: 1920
      #fps: 30

    #motion:
      #mask:
        # Datum und Zeit
        #- 879,27,878,67,1258,68,1256,25

    objects:
      track:
        - person

    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        # Optional: Restrict clips to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        retain:
          default: 7
          objects:
            person: 14

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False
      height: 1080
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 7
        # Optional: Per object retention days
        objects:
          person: 21

#---------------------------------------------------------------------------------------------------------------------------------

```

### Relevant log output

```shell
F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Unknown: USB transfer error 1 [LibUsbDataInCallback]
Fatal Python error: Aborted
Thread 0x00007f51677d8700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap
Thread 0x00007f51782f0740 (most recent call first):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
  File "/opt/frigate/frigate/edgetpu.py", line 104 in detect_raw
  File "/opt/frigate/frigate/edgetpu.py", line 180 in run_detector
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/edgetpu.py", line 241 in start_or_restart
  File "/opt/frigate/frigate/edgetpu.py", line 210 in __init__
  File "/opt/frigate/frigate/app.py", line 187 in start_detectors
  File "/opt/frigate/frigate/app.py", line 326 in start
  File "/opt/frigate/frigate/__main__.py", line 17 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
[2022-01-22 10:08:42] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-01-22 10:08:42] frigate.app                    INFO    : Stopping...
[2022-01-22 10:08:42] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-01-22 10:08:42] frigate.record                 INFO    : Exiting recording cleanup...
[2022-01-22 10:08:42] frigate.stats                  INFO    : Exiting watchdog...
[2022-01-22 10:08:42] frigate.events                 INFO    : Exiting event cleanup...
[2022-01-22 10:08:42] frigate.watchdog               INFO    : Exiting watchdog...
[2022-01-22 10:08:42] frigate.record                 INFO    : Exiting recording maintenance...
[2022-01-22 10:08:42] frigate.object_processing      INFO    : Exiting object processor...
[2022-01-22 10:08:48] frigate.events                 INFO    : Exiting event processor...
[2022-01-22 10:08:48] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-01-22 10:08:48] root                           INFO    : Waiting for detection process to exit gracefully...
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Instar IN-9020HD & Reolink RLC-510A
