### ISSUE TITLE
[Support]: Recording/Clips not accessible from external (download URL contains INGRESS)

### ISSUE THREAD

**Issue by plimmplamm** [blakeblackshear/frigate#2697]
### Describe the problem you are having

When I try to forward the URL for videos in notifications (eg telegram), I can not access the files.

**When I looking into the URL of the clips for the events the URL resolves into something like:**
https://XXXXXXX.duckdns.org:8123/api/hassio_ingress/XXXXXXXXXX/api/events/1642896479.154243-82oe1a/clip.mp4?download=true

**While the URL in the automation looks like this:**
https://XXXXXXX.duckdns.org/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4

**Background**
I replaced the content in the custom components folder with a downloaded ZIP version of FRIGATE from the GitHub repo (https://github.com/blakeblackshear/frigate-hass-integration) since I could not find it in the shop.

Do I need to replace the folder content? Or can I change the URL?

Thanks for your help!

### Version

 0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.XXX.XXX
  user: XXX
  password: XXX
cameras:
  reocam-front:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.XXX.XXX:554//h264Preview_01_main
          roles:
            - detect
            - clips
            - record
      # output_args:
        # record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 2304
      height: 1296
      fps: 6
    objects:
      track:
        - person
    record:
      enabled: true
      retain_days: 5
      events:
        max_seconds: 30
        retain:
          default: 5
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 410
