### ISSUE TITLE
[Support]: CPU stuck at 1xx % after webostv access to mjpeg api endpoint

### ISSUE THREAD

**Issue by TheQue42** [blakeblackshear/frigate#2716]
### Describe the problem you are having

I've just started playing with integrating the frigate notifications to homeassistant, together with my LG TV, running Webos.

It's taken me a few days to realize why my warning for high cpu loads have started going off randomly, and it turns out its when the automation for sending the mjpeg stream to the webostv has run.

So I am using the ha-service below, in an automation/script.
```
service: webostv.command
data:
  command: system.launcher/open
  payload:
    target: >-
      http://frigate:1234/api/<camera>?h=1080&?mask=1&?motion=1&fps=15
  entity_id: media_player.movieplayerlg
```
If I've got `docker stats` running on the docker host(i7 nuc) at the same time, I can see frigate going from its normal 40% load to 100-140%.

And it stays there. Permanently. Even if I turn of the TV.

The annoying this is that if I just browse the same URL via firefox, and disconnect, the CPU load goes back down. Only the webos connection causes the cpuload to get stuck at >1xx%.

### Version

0.9.4

### Frigate config file

```yaml
mqtt:
  host: node
  user: user
  password: password
  client_id: frigate
  topic_prefix: frigate

cameras:
  fr_entre:
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp-URL
          roles:
            - detect
        - path: rtsp-URL
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask: 640,0,0,0,0,380,137,232,114,99,374,64,383,193,473,199,479,245,483,354,458,480,640,480
  fr_baksidan:
    ffmpeg:
      inputs:
        - path: rtsp-URL
          roles:
            - detect
            - rtmp
        - path: rtsp-URL
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    motion:
      mask:
        - 170,101,137,185,0,327,0,190,0,0,589,0,1024,0,1024,150,965,147,941,187,813,157,775,190,764,113
        - 643,576,1024,576,1024,447
  fr_hallen:
    mqtt:
      timestamp: False
      bounding_box: true
      crop: True
      height: 480
      quality: 75
    ffmpeg:
      inputs:
        #- path: rtsp-URL
        - path: httpURL
          roles:
            - detect
        #- path: rtsp-URL
        - path: httpURL
          roles:
            - rtmp
            - record
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -rw_timeout
        - '5000000'
        - -f
        - live_flv
    motion:
      mask:
        - 0,0,0,264,262,136,260,0
    detect:
      width: 640
      height: 480
      fps: 7
  fr_vardagsrum:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 576
    ffmpeg:
      inputs:
        - path: rtsp-URL
          roles:
            - detect
            - rtmp            
        - path: rtsp-URL
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 5
    motion:
      mask:
        - 1024,283,989,409,926,396,860,171,871,0,1024,0

detectors:
  coral_pci:
    type: edgetpu
    device: pci

objects:
  track:
    - person
  filters:
    person:
      min_area: 2000
      max_area: 100000
      min_score: 0.65
      threshold: 0.76

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

logger:
  default: debug
  logs:
    frigate.mqtt: warning
    peewee.sqliteq: warning
    peewee: warning
    ffmpeg.fr_hallen: debug

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 180
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 2
      objects:
        person: 2

snapshots:
  enabled: False
  retain:
    default: 1
    objects:
      person: 2
  timestamp: False
  bounding_box: true
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  #height: 720
  # Optional: Set the encode quality of the live stream (default: 8)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 16

birdseye:
  enabled: True
  mode: motion
```

### Relevant log output

```shell
None :-(
I even added debugs but all I see is:

[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start expire recordings (new).
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start deleted cameras.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Expiring 0 recordings
[2022-01-27 19:56:53] frigate.record                 DEBUG   : End deleted cameras.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start all cameras.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start camera: fr_entre.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Expiring 11 recordings
[2022-01-27 19:56:53] frigate.record                 DEBUG   : End camera: fr_entre.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start camera: fr_baksidan.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Expiring 11 recordings
[2022-01-27 19:56:53] frigate.record                 DEBUG   : End camera: fr_baksidan.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start camera: fr_hallen.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Expiring 0 recordings
[2022-01-27 19:56:53] frigate.record                 DEBUG   : End camera: fr_hallen.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Start camera: fr_vardagsrum.
[2022-01-27 19:56:53] frigate.record                 DEBUG   : Expiring 0 recordings
```

### FFprobe output from your camera

```shell
root@2f647fdde247:/opt/frigate# ffprobe "rtsp://VLooker42:AtgxZMMIvTR71LJ9CMwc@imou.disc-world.se/cam/realmonitor?channel=1&subtype=0&unicast=true"
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://VLooker42:AtgxZMMIvTR71LJ9CMwc@imou.disc-world.se/cam/realmonitor?channel=1&subtype=0&unicast=true':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, progressive), 1920x1080, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral_pci":{"detection_start":0.0,"inference_speed":20.58,"pid":225}},"fr_baksidan":{"camera_fps":5.0,"capture_pid":254,"detection_fps":0.0,"pid":236,"process_fps":5.0,"skipped_fps":0.0},"fr_entre":{"camera_fps":5.1,"capture_pid":250,"detection_fps":0.0,"pid":234,"process_fps":5.1,"skipped_fps":0.0},"fr_hallen":{"camera_fps":7.0,"capture_pid":259,"detection_fps":0.0,"pid":237,"process_fps":0.0,"skipped_fps":0.0},"fr_vardagsrum":{"camera_fps":5.1,"capture_pid":265,"detection_fps":0.0,"pid":238,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":63.5,"mount_type":"tmpfs","total":67.1,"used":3.6},"/media/frigate/clips":{"free":101428.7,"mount_type":"btrfs","total":124787.9,"used":22705.5},"/media/frigate/recordings":{"free":101428.7,"mount_type":"btrfs","total":124787.9,"used":22705.5},"/tmp/cache":{"free":2146.2,"mount_type":"tmpfs","total":2147.5,"used":1.3}},"uptime":2796,"version":"0.9.4-26ae608"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

imou bullet new

### Any other information that may be helpful

I have just upgrade the host to opensuse 15.3 from 15.2, but I did try these automations on the old environment.
