### ISSUE TITLE
[Support]: No motion detected and ffmpeg stream crashing

### ISSUE THREAD

**Issue by stefanelul2000** [blakeblackshear/frigate#2719]
### Describe the problem you are having

Motion Detection does not work on cats and dogs. Also, the system does not recognize them at all, but I think this is also due to them not being detected by motion detection.

There is also the issue that the one of my streams from my front yard is crashing every 10 seconds

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 10.1.88.9
  user: mqtt-user
  password: password
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 15
    objects:
      person: 30
      car: 30
record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - cat
      - dog
    retain:
      default: 15
      objects:
        person: 30
        car: 30
cameras:
  Intrare:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.1.30.3:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://user:password@10.1.30.3:554/Streaming/Channels/101/
          roles:
            - rtmp
            - record
    motion:
      mask:
        - 176,78,450,54,452,0,0,0,0,119
        - 390,170,412,162,419,132,411,112,393,92,371,81,338,102,330,126,331,149,351,161,368,180
    zones:
      poarta_auto:
        coordinates: 52,360,243,260,199,236,190,181,0,238,34,303
      poarta_pieton:
        coordinates: 254,206,305,196,297,150,258,155
      alee_intrare:
        coordinates: 291,191,462,238,445,257,401,313,331,289,379,247,259,206
      trepte_intrare:
        coordinates: 405,322,540,360,590,145,548,132,524,231,471,223
    detect:
      width: 640
      height: 360
      fps: 6
  Curte_Fata:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.1.30.4:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://user:password@10.1.30.4:554/Streaming/Channels/101/
          roles:
            - rtmp
            - record
    motion:
      mask:
        - 216,21,216,36,21,35,22,21
        - 640,124,640,0,391,0,371,0,390,77,348,58,290,35,382,101,440,135,437,201,496,190,561,283,640,285
        - 257,123,222,125,242,219,263,225
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 6
  Curte_Spate:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.1.30.5:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://user:password@10.1.30.5:554/Streaming/Channels/101/
          roles:
            - rtmp
            - record 
    motion:
      mask:
        - 107,178,164,261,190,360,0,360,0,140
        - 640,0,640,360,585,360,579,0
        - 210,21,209,36,23,34,23,21
        - 309,0,272,59,255,93,231,126,237,179,217,176,194,106,162,85,145,0
        - 434,71,421,197,408,196,401,175,389,148,397,88,412,66
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 6
  Curte_Bono:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.1.30.6:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://user:password@10.1.30.6:554/Streaming/Channels/101/
          roles:
            - rtmp
            - record
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 6
```

### Relevant log output

```shell
[2022-01-28 15:55:01] ffmpeg.Intrare.record_rtmp     ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2022-01-28 15:55:01] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x55c20afec700] Failed to update header with correct duration.
[2022-01-28 15:55:01] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x55c20afec700] Failed to update header with correct filesize.
[2022-01-28 15:55:01] ffmpeg.Intrare.record_rtmp     ERROR   : Error writing trailer of rtmp://127.0.0.1/live/Intrare: Connection reset by peer
[2022-01-28 15:55:01] watchdog.Intrare               INFO    : Terminating the existing ffmpeg process...
[2022-01-28 15:55:01] watchdog.Intrare               INFO    : Waiting for ffmpeg to exit gracefully...
[2022-01-28 15:55:11] ffmpeg.Intrare.record_rtmp     ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2022-01-28 15:55:11] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x562cb12bc8c0] Failed to update header with correct duration.
[2022-01-28 15:55:11] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x562cb12bc8c0] Failed to update header with correct filesize.
[2022-01-28 15:55:11] ffmpeg.Intrare.record_rtmp     ERROR   : Error writing trailer of rtmp://127.0.0.1/live/Intrare: Connection reset by peer
[2022-01-28 15:55:11] watchdog.Intrare               INFO    : Terminating the existing ffmpeg process...
[2022-01-28 15:55:11] watchdog.Intrare               INFO    : Waiting for ffmpeg to exit gracefully...
[2022-01-28 15:55:21] ffmpeg.Intrare.record_rtmp     ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2022-01-28 15:55:21] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x55929f8c7700] Failed to update header with correct duration.
[2022-01-28 15:55:21] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x55929f8c7700] Failed to update header with correct filesize.
[2022-01-28 15:55:21] ffmpeg.Intrare.record_rtmp     ERROR   : Error writing trailer of rtmp://127.0.0.1/live/Intrare: Connection reset by peer
[2022-01-28 15:55:21] watchdog.Intrare               INFO    : Terminating the existing ffmpeg process...
[2022-01-28 15:55:21] watchdog.Intrare               INFO    : Waiting for ffmpeg to exit gracefully...
[2022-01-28 15:55:31] ffmpeg.Intrare.record_rtmp     ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2022-01-28 15:55:31] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x55bad6b0fbc0] Failed to update header with correct duration.
[2022-01-28 15:55:31] ffmpeg.Intrare.record_rtmp     ERROR   : [flv @ 0x55bad6b0fbc0] Failed to update header with correct filesize.
[2022-01-28 15:55:31] ffmpeg.Intrare.record_rtmp     ERROR   : Error writing trailer of rtmp://127.0.0.1/live/Intrare: Connection reset by peer
[2022-01-28 15:55:31] watchdog.Intrare               INFO    : Terminating the existing ffmpeg process...
[2022-01-28 15:55:31] watchdog.Intrare               INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
[rtsp @ 0x55aa3c096a00] UDP timeout, retrying with TCP
[rtsp @ 0x55aa3c096a00] method PAUSE failed: 551 Option not supported
Input #0, rtsp, from 'rtsp://user:password@10.1.30.3:554/Streaming/Channels/102/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 640x480 [SAR 126:95 DAR 168:95], 25 tbr, 90k tbn, 25 tbc
```

### Frigate stats

```json
{"Curte_Bono":{"camera_fps":6.1,"capture_pid":248,"detection_fps":0.0,"pid":239,"process_fps":6.1,"skipped_fps":0.0},"Curte_Fata":{"camera_fps":6.1,"capture_pid":241,"detection_fps":0.0,"pid":237,"process_fps":6.1,"skipped_fps":0.0},"Curte_Spate":{"camera_fps":6.0,"capture_pid":244,"detection_fps":5.7,"pid":238,"process_fps":6.0,"skipped_fps":0.0},"Intrare":{"camera_fps":6.1,"capture_pid":240,"detection_fps":0.0,"pid":235,"process_fps":6.1,"skipped_fps":0.0},"detection_fps":5.7,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":112.58,"pid":229}},"service":{"storage":{"/dev/shm":{"free":2057.0,"mount_type":"tmpfs","total":2060.3,"used":3.2},"/media/frigate/clips":{"free":23898.2,"mount_type":"ext4","total":33570.3,"used":8288.7},"/media/frigate/recordings":{"free":23898.2,"mount_type":"ext4","total":33570.3,"used":8288.7},"/tmp/cache":{"free":2054.5,"mount_type":"tmpfs","total":2060.3,"used":5.8}},"uptime":81020,"version":"0.9.4-26ae608"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

HikVision DS-2CD2T4AG-A5

**Comment by blakeblackshear** [comment]
Is this ffprobe output from the failing camera?

**Comment by stefanelul2000** [comment]
Yes.

**Comment by stefanelul2000** [comment]
And the camera name is "Intrare" with IP 10.1.30.3

**Comment by blakeblackshear** [comment]
Can you run ffprobe again with channel 101 on that camera? That's the stream that's failing.

**Comment by stefanelul2000** [comment]
Only thing I am getting is this 

`
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
`

**Comment by stefanelul2000** [comment]
```
[rtsp @ 0x5610ace77a00] UDP timeout, retrying with TCP
[rtsp @ 0x5610ace77a00] method PAUSE failed: 551 Option not supported
[rtsp @ 0x5610ace77a00] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://user:password@10.1.30.3:554/Streaming/Channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
```

**Comment by stefanelul2000** [comment]
I am getting the same output regardless of what camera I am probing on the same channel.

**Comment by blakeblackshear** [comment]
What is the resolution of the 101 channel? I suspect that it may be too high to have RTMP enabled.

**Comment by stefanelul2000** [comment]
All of the 4 cameras I have are on resulution 2688x1520, H264. Also I have seen that the streams are from RTSP but Frigate converts them into RTMP? Could that be create any issues ?
________________________________

**Comment by blakeblackshear** [comment]
I would suggest disabling rtmp. High bitrates are causing the errors you see in the logs.

```yaml
rtmp:
  enabled: false
```

For motion detection, try these settings:
```yaml
motion:
  frame_height: 50
  contour_area: 30
```

These will be the defaults in the next version. If these don't detect motion, try these:
```yaml
motion:
  frame_height: 50
  contour_area: 15
```

**Comment by stefanelul2000** [comment]
But if I am disabling RTMP will direct streaming the cameras still work ?
________________________________

**Comment by blakeblackshear** [comment]
There are several ways streaming works in frigate. What specifically do you mean by "direct streaming"?

**Comment by stefanelul2000** [comment]
I am meaning I am using the RTMP stream inside HA for live viewing my cameras. Is there any other way to do that ?
________________________________

**Comment by blakeblackshear** [comment]
You can either use the jsmpeg provider with the custom lovelace card or switch the rtmp role to the substream. Another option would be to use the builtin camera integration in home assistant to connect directly to your cameras. Unfortunately, the RTMP relay built into frigate currently has issues with high resolution and bitrates.

**Comment by stefanelul2000** [comment]
Would there be any disadvantages in using jsmpeg rather than RTMP or RTSP
________________________________

**Comment by blakeblackshear** [comment]
jsmpeg will always be from the detect stream, so it will have a lower resolution. It has the advantage of being much lower latency, so it will be more real time.

**Comment by stefanelul2000** [comment]
So I have set the following on my cameras:
```
motion:
  frame_height: 50
  contour_area: 30
```

I will monitor the situation on the following days to see if my dog is detected or if it messes up the already working person detection.

In terms of the RTMP stream is there any plan in supporting higher resolution ? I mean I would prefere to use one integration in HA rather than having the generic for live stream and than frigate for detection.

**Comment by blakeblackshear** [comment]
Some of the alternatives I am looking into may handle higher resolutions. We will see.

**Comment by stefanelul2000** [comment]
```  Curte_Fata:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass!@10.1.30.4:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://admin:pass@10.1.30.4:554/Streaming/Channels/101/
          roles:
            - record
    motion:
      mask:
        - 216,21,216,36,21,35,22,21
        - 640,124,640,0,391,0,371,0,390,77,348,58,290,35,382,101,440,135,437,201,496,190,561,283,640,285
        - 257,123,222,125,242,219,263,225
      frame_height: 50
      contour_area: 50        
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 640
      height: 360
      fps: 6
```
```
objects:
  track:
    - person
    - car
    - cat
    - dog
  filters:
    person:
      min_area: 3000
      max_area: 9000
      min_score: 0.5
      threshold: 0.7
```
Detection issues are still present. See the screenshot.
https://images.ciubi.net/bEQi3/NuGOwuyU14.png

What else can I tinker with ?
