### ISSUE TITLE
[Support]: Events not sending mqtt event message with type = start

### ISSUE THREAD

**Issue by frazzyfin** [blakeblackshear/frigate#2720]
### Describe the problem you are having

When an event occurs in frigate, it doesn't seem to publish the event to mqtt with type = start. I only get type = end. This is causing the home assistant notification blueprint not to trigger.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: mosquitto

detectors:
  coral_pci:
    type: edgetpu
    device: pci

# ffmpeg:
#   hwaccel_args:
#     - -hwaccel
#     - vaapi
#     - -hwaccel_device
#     - /dev/dri/renderD128
#     - -hwaccel_output_format
#     - yuv420p

cameras:
  kitchen_cam:
    ffmpeg:
      inputs:
        - path: rtsps://10.0.10.1:7441/21ypIkkOwjHU7w2h?enableSrtp
          roles:
            - detect
        - path: rtsps://10.0.10.1:7441/PLiIivcDBSpBoy1h?enableSrtp
          roles:
            - rtmp
            - record
    detect:
      width: 1024
      height: 576
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,26,163,23,163,0,0,0
    objects:
      track:
        - person
        - dog
      mask:
        - 424,294,569,289,565,177,426,180
  front_door_cam:
    ffmpeg:
      inputs:
        - path: rtsps://10.0.10.1:7441/1CcEkwZvG8xqyG1i?enableSrtp
          roles:
            - detect
        - path: rtsps://10.0.10.1:7441/vhpktdOV3Zpsal3Y?enableSrtp
          roles:
            - rtmp
            - record
    detect:
      width: 960
      height: 720
    record:
      enabled: True
      retain_days: 0
      events:
        required_zones:
          - driveway
        retain:
          default: 10
    snapshots:
      enabled: True
      required_zones:
        - driveway
    motion:
      mask:
        - 0,25,163,26,160,0,159,0,0,0
    zones:
      driveway:
        coordinates: 0,720,547,720,586,473,351,419,0,454
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat

database:
  path: /db/frigate.db
```

### Relevant log output

```shell
{"before": {"id": "1643418304.371133-zi9kef", "camera": "front_door_cam", "frame_time": 1643418307.335852, "snapshot_time": 1643418304.966053, "label": "car", "top_score": 0.7890625, "false_positive": false, "start_time": 1643418304.371133, "end_time": null, "score": 0.76953125, "box": [128, 358, 490, 581], "area": 80726, "region": [92, 258, 524, 690], "current_zones": ["driveway"], "entered_zones": ["driveway"], "has_clip": false, "has_snapshot": false}, "after": {"id": "1643418304.371133-zi9kef", "camera": "front_door_cam", "frame_time": 1643418307.335852, "snapshot_time": 1643418304.966053, "label": "car", "top_score": 0.7890625, "false_positive": false, "start_time": 1643418304.371133, "end_time": 1643418312.569881, "score": 0.76953125, "box": [128, 358, 490, 581], "area": 80726, "region": [92, 258, 524, 690], "current_zones": ["driveway"], "entered_zones": ["driveway"], "has_clip": true, "has_snapshot": true}, "type": "end"}
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x5602e2ce7b80] decoding for stream 1 failed
Input #0, rtsp, from 'rtsps://10.0.10.1:7441/1CcEkwZvG8xqyG1i?enableSrtp':
  Metadata:
    title           : 68D79A8F7741_1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac, 48000 Hz, mono, fltp
    Stream #0:1: Video: h264, yuvj420p(pc, bt709, progressive), 960x720 [SAR 1:1 DAR 4:3], 30 fps, 30 tbr, 90k tbn, 60 tbc
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral_pci":{"detection_start":0.0,"inference_speed":7.15,"pid":217}},"front_door_cam":{"camera_fps":5.1,"capture_pid":236,"detection_fps":0.0,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"kitchen_cam":{"camera_fps":5.1,"capture_pid":226,"detection_fps":0.0,"pid":222,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":64.2,"mount_type":"tmpfs","total":67.1,"used":2.9},"/media/frigate/clips":{"free":6358043.9,"mount_type":"cifs","total":12248059.9,"used":5890016.0},"/media/frigate/recordings":{"free":6358043.9,"mount_type":"cifs","total":12248059.9,"used":5890016.0},"/tmp/cache":{"free":18950.2,"mount_type":"overlay","total":72652.9,"used":50304.2}},"uptime":19555,"version":"0.9.4-26ae608"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Ubiquiti Unifi Doorbell
