### ISSUE TITLE
[Support]: QuickSync not working properly?

### ISSUE THREAD

**Issue by JanickGers85** [blakeblackshear/frigate#2722]
### Describe the problem you are having

I've switched back to a power-efficient system with a Pentium Silver J5040 CPU: it do have QuickSync but enabling it seems that don't change a lot on processor load

 - QS on -> ~22%
 - QS off -> ~25%

Here a screenshot of the intel_gpu_top output with Frigate running, load on GPU is quite stable at those values
![image](https://user-images.githubusercontent.com/21289907/151680940-efe81393-c564-4319-8d31-6f52bd5865c3.png)

Do I have to tweak settings or something?
I tried with the >10th gen config but intel_gpu_top show 0%.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.217
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ***
  password: ***
ffmpeg:
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - panic
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1  
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 640
birdseye:
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
timestamp_style:
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
cameras:
  garden:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.1.237:8554/unicast'
          roles:
            - detect
            - rtmp
            - record
    snapshots:
      required_zones:
        - giardino
        - vialetto
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 90
    detect:
      height: 720
      width: 1280
      fps: 15
    best_image_timeout: 5
    motion:
      mask: 0,0,1280,0,1280,650,1244,552,1223,557,1205,603,1167,528,1137,457,1090,371,1022,263,982,265,943,268,925,253,915,315,803,316,791,243,740,240,715,243,674,243,627,242,564,243,487,249,395,253,302,259,183,271,89,284,0,295
    mqtt:
      enabled: true
      crop: true
      height: 500
    record:
      events:
        required_zones:
          - giardino
          - vialetto
      enabled: true
      retain_days: 90
    zones:
      giardino:
        coordinates: 0,720,887,720,857,576,829,423,789,283,736,258,684,266,595,269,474,268,303,273,202,287,138,289,57,299,0,373
        objects:
          - person
          - cat
      vialetto:
        coordinates: 849,556,872,720,1280,720,1280,720,1231,573,1209,608,1115,435,1022,286,979,289,922,279,919,319,800,319
        objects:
          - person
          - cat
  garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://***:***@192.168.1.76:554/live/ch00_1'
          roles:
            - detect
            - rtmp
            - record
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 90
    detect:
      height: 720
      width: 1280
      fps: 15
    best_image_timeout: 5
    mqtt:
      enabled: true
      crop: true
      height: 500
    objects:
      track:
        - person
    record:
      enabled: true
      retain_days: 90
objects:
  track:
    - person
    - car
    - cat
  filters:
    person:
      min_area: 3000
      max_area: 1000000
      min_score: 0.65
      threshold: 0.75
    cat:
      min_area: 1000
      max_area: 1000000
      min_score: 0.45
      threshold: 0.65
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
ffprobe rtsp://192.168.1.237:8554/unicast (Wyzecam V2 with Dafang Hack)

ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://192.168.1.237:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 1.148144, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 25 fps, 15.17 tbr, 90k tbn, 50 tbc




ffprobe rtsp://***:***@192.168.1.76:554/live/ch00_1 (Chinese camera with RTSP stream)

ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://***:***@192.168.1.76:554/live/ch00_1':
  Metadata:
    title           : streamed by the macro-video rtsp server
  Duration: N/A, start: 0.530000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 20 fps, 20 tbr, 90k tbn, 40 tbc
```

### Frigate stats

```json
{
   "detection_fps":0.0,
   "detectors":{
      "coral":{
         "detection_start":0.0,
         "inference_speed":12.42,
         "pid":217
      }
   },
   "garage":{
      "camera_fps":15.0,
      "capture_pid":230,
      "detection_fps":0.0,
      "pid":225,
      "process_fps":15.0,
      "skipped_fps":0.0
   },
   "garden":{
      "camera_fps":15.0,
      "capture_pid":227,
      "detection_fps":0.0,
      "pid":223,
      "process_fps":15.0,
      "skipped_fps":0.0
   },
   "service":{
      "storage":{
         "/dev/shm":{
            "free":63.3,
            "mount_type":"tmpfs",
            "total":67.1,
            "used":3.8
         },
         "/media/frigate/clips":{
            "free":410279.8,
            "mount_type":"ext4",
            "total":3936934.0,
            "used":3326598.1
         },
         "/media/frigate/recordings":{
            "free":410279.8,
            "mount_type":"ext4",
            "total":3936934.0,
            "used":3326598.1
         },
         "/tmp/cache":{
            "free":495.8,
            "mount_type":"tmpfs",
            "total":500.0,
            "used":4.2
         }
      },
      "uptime":935,
      "version":"0.9.4-26ae608"
   }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Wyzecam V2 with Dafang Hack, other chinese camera with RTSP stream
