### ISSUE TITLE
[Support]: After restarting 0.10-beta6 with new config, frigate is not starting

### ISSUE THREAD

**Issue by vpetrovych** [blakeblackshear/frigate#2724]
### Describe the problem you are having

I've added new camera to the config and restarted the frigate. Now it doesn't start and from logs, it seems like somethings is timing out.

### Version

0.10-beta6

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.0.XX
  user: mqtt
  password: XXXXX

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - info

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://XXXXX@192.168.0.XX:554/media/video2'
          roles:
            - detect
            - record
            - rtmp

    snapshots:
      enabled: true
      timestamp: true
      crop: false
      retain:
        default: 30

    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 7
          mode: motion

    detect:
      enabled: true
      width: 720
      height: 1280

  corridor:
    ffmpeg:
      inputs:
        - path: 'rtsp://XXXXX@192.168.0.XXX:554/media/video2'
          roles:
            - detect
            - record
            - rtmp
    snapshots:
      enabled: true
      timestamp: true
      crop: false
#      crop_to_region: true
#      height: 175
      retain:
        default: 30

    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 7
          mode: motion

    detect:
      enabled: true
#      max_disappeared: 30
      width: 720
      height: 1280
```

### Relevant log output

```shell
frigate    | [2022-01-30 11:02:04] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)
frigate    | Starting migrations
frigate    | [2022-01-30 11:02:05] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2022-01-30 11:02:05] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | timed out
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-01-30 11:03:09] frigate.app                    INFO    : Starting Frigate (0.10.0-db1255a)
frigate    | Starting migrations
frigate    | [2022-01-30 11:03:10] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2022-01-30 11:03:10] peewee_migrate                 INFO    : There is nothing to migrate
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x55c0eb98ef00] max delay reached. need to consume packet
[rtsp @ 0x55c0eb98ef00] RTP: missed 56 packets
[h264 @ 0x55c0eb992c40] error while decoding MB 40 27, bytestream -44
[h264 @ 0x55c0eb992c40] concealing 1529 DC, 1529 AC, 1529 MV errors in I frame
[rtsp @ 0x55c0eb98ef00] max delay reached. need to consume packet
[rtsp @ 0x55c0eb98ef00] RTP: missed 29 packets
[h264 @ 0x55c0eb992c40] error while decoding MB 29 27, bytestream -14
[h264 @ 0x55c0eb992c40] concealing 1540 DC, 1540 AC, 1540 MV errors in I frame
Input #0, rtsp, from 'rtsp://XXXX@192.168.0.XX:554/media/video2':
  Metadata:
    title           : VCP IPC Realtime stream
  Duration: N/A, start: 1.400000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 5 fps, 5 tbr, 90k tbn, 10 tbc
    Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Uniview

### Any other information that may be helpful

I can access cameras without any issues and trying the same exact URL in VLC produces a video.
Reverting to the original working config, doesn't solve the issue.
