### ISSUE TITLE
[Support]: 0.10.0-DB1255A Beta 6

### ISSUE THREAD

**Issue by burnsie-la** [blakeblackshear/frigate#2727]
### Describe the problem you are having

My video clips seem to be fluctuating in speed (FPS).  You can see the footage visibily slow down and then speed up like someone is alternating between slow motion and fast forward.  This is happening when I view the clips on any device.  The same issue can be seen when viewing the camera streams live in the Frigate web interface.

I am using an Intel NUC as my docker host, and using the RTSP stream from my Unifi NVR. If I view the RTSP streams directly the footage is normal speed.  The footage for the clips is being recordede onto an external USB3 HDD.

### Version

0.10.0-DB1255A

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "BackCam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 24,
        "height": 720,
        "max_disappeared": 120,
        "stationary_interval": 240,
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsps://192.168.1.10:7441/Hr4cT1hrlAGjA0Im?enableSrtp",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsps://192.168.1.10:7441/HFXAWZoqku8twyRG?enableSrtp",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsps://192.168.1.10:7441/Hr4cT1hrlAGjA0Im?enableSrtp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/BackCam-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsps://192.168.1.10:7441/HFXAWZoqku8twyRG?enableSrtp -c copy -f flv rtmp://127.0.0.1/live/BackCam -r 24 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": [
          "0,572,27,699,83,671,299,283,396,37,804,38,1035,68,1280,135,1280,0,398,0,0,0",
          "1280,297,1280,720,965,508,1021,216"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "BackCam",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 100000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": 2
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "active_objects",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "FoxCam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 25,
        "height": 576,
        "max_disappeared": 125,
        "stationary_interval": 250,
        "width": 1024
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsps://192.168.1.10:7441/Ip3tsf6yYI30h3M9",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsps://192.168.1.10:7441/mh4DBm3qvTQAaNZO",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsps://192.168.1.10:7441/Ip3tsf6yYI30h3M9 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/FoxCam-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsps://192.168.1.10:7441/mh4DBm3qvTQAaNZO -c copy -f flv rtmp://127.0.0.1/live/FoxCam -r 25 -s 1024x576 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": [
          "854,0,0,0,0,49,773,21"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "FoxCam",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 100000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": 2
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "active_objects",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "FrontCam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 24,
        "height": 720,
        "max_disappeared": 120,
        "stationary_interval": 240,
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsps://192.168.1.10:7441/OB6klvMg96N5bEDi?enableSrtp",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsps://192.168.1.10:7441/lka5qaUN6Tyt8hWR?enableSrtp",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsps://192.168.1.10:7441/OB6klvMg96N5bEDi?enableSrtp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/FrontCam-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsps://192.168.1.10:7441/lka5qaUN6Tyt8hWR?enableSrtp -c copy -f flv rtmp://127.0.0.1/live/FrontCam -r 24 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": [
          "1086,0,1280,0,1280,720,1209,720,1130,331"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [
          "Front_Patio",
          "Front_Steps"
        ],
        "timestamp": true
      },
      "name": "FrontCam",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 100000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "Front_Patio",
            "Front_Steps"
          ],
          "retain": {
            "default": 10,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": 2
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "Front_Patio",
          "Front_Steps"
        ],
        "retain": {
          "default": 10,
          "mode": "active_objects",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "Front_Patio": {
          "coordinates": "1087,475,1094,720,626,681,642,559,736,533,788,479",
          "filters": {},
          "objects": []
        },
        "Front_Steps": {
          "coordinates": "499,421,392,676,134,662,238,454",
          "filters": {},
          "objects": []
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary_interval": null,
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.3",
    "password": "uZ7r0vO4tevQ",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "hass"
  },
  "objects": {
    "filters": {
      "person": {
        "mask": null,
        "max_area": 100000,
        "min_area": 0,
        "min_score": 0.5,
        "threshold": 0.7
      }
    },
    "mask": "",
    "track": [
      "person",
      "dog",
      "cat"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "active_objects",
        "objects": {}
      }
    },
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "active_objects",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 43478040, current: 43478040; changing to 43478041. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 43478041, current: 43478041; changing to 43478042. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 44286956, current: 44286956; changing to 44286957. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 44528608, current: 44528608; changing to 44528609. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 44528609, current: 44528609; changing to 44528610. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 44528610, current: 44528610; changing to 44528611. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 45744907, current: 45744907; changing to 45744908. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 45882046, current: 45882046; changing to 45882047. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [segment @ 0x56281fe308c0] Non-monotonous DTS in output stream 0:0; previous: 46004957, current: 46004957; changing to 46004958. This may result in incorrect timestamps in the output file.


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   : [tls @ 0x56281fd53480] error:00000000:lib(0):func(0):reason(0)


[2022-01-30 12:41:09] ffmpeg.FrontCam.record         ERROR   :     Last message repeated 6 times


[2022-01-30 12:41:09] watchdog.FrontCam              INFO    : Terminating the existing ffmpeg process...
```

### FFprobe output from your camera

```shell
C:\Users\admuser\Downloads>ffprobe.exe rtsps://192.168.1.10:7441/OB6klvMg96N5bEDi?enableSrtp
ffprobe version 5.0-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rtsp, from 'rtsps://192.168.1.10:7441/OB6klvMg96N5bEDi?enableSrtp':
  Metadata:
    title           : 74ACB9001609_0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
  Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1512 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn

C:\Users\admuser\Downloads>ffprobe.exe rtsps://192.168.1.10:7441/lka5qaUN6Tyt8hWR?enableSrtp
ffprobe version 5.0-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rtsp, from 'rtsps://192.168.1.10:7441/lka5qaUN6Tyt8hWR?enableSrtp':
  Metadata:
    title           : 74ACB9001609_1
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
  Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn
```

### Frigate stats

```json
{"BackCam":{"camera_fps":23.9,"capture_pid":242,"detection_fps":0.0,"pid":235,"process_fps":23.9,"skipped_fps":0.0},"FoxCam":{"camera_fps":25.0,"capture_pid":244,"detection_fps":0.0,"pid":237,"process_fps":25.0,"skipped_fps":0.0},"FrontCam":{"camera_fps":23.6,"capture_pid":239,"detection_fps":2.2,"pid":232,"process_fps":23.6,"skipped_fps":0.0},"detection_fps":2.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.85,"pid":225}},"service":{"storage":{"/dev/shm":{"free":62.0,"mount_type":"tmpfs","total":67.1,"used":5.1},"/media/frigate/clips":{"free":677118.0,"mount_type":"ext4","total":979805.8,"used":252893.0},"/media/frigate/recordings":{"free":677118.0,"mount_type":"ext4","total":979805.8,"used":252893.0},"/tmp/cache":{"free":985.7,"mount_type":"tmpfs","total":1000.0,"used":14.3}},"temperatures":{},"uptime":149902,"version":"0.10.0-db1255a"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G4 Bullet
