### ISSUE TITLE
[FR] support for multiple (poly)masks

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#273]
Please consider implementing support for multiple masks, just like there´s support for multiple zones.

Proposed syntax:
```
cameras:
  front_lawn:
    ffmpeg:
      masks:
        top_tree_and_bushes_area:
          coordinates: poly,455,646,636,1,243
        clock_and_date_area:
          coordinates: poly,23,53,64,774
```
