### ISSUE TITLE
value is not a valid dict (type=type_error.dict)

### ISSUE THREAD

**Issue by wgstarks** [blakeblackshear/frigate#2731]
### Describe the problem you are having

My output args copied from documentation generate an error.
`*** Config Validation Errors ***
*************************************************************
1 validation error for FrigateConfig

cameras -> doorbell -> ffmpeg -> output_args
value is not a valid dict (type=type_error.dict)`

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.23
  user: mqtt
  password: redacted
  
detectors:
  coral:
    type: edgetpu
    device: usb
  
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.0.30.20:554/Streaming/channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://user:password@10.0.30.20:554/Streaming/channels/101
          roles:
            - record
      input_args:
        - -c:v
        - h264_cuvid
      output_args:
        - -filter:v
        - fps=fps=5       
    detect:
      width: 352
      height: 240
    motion:
      mask:
        - 775,553,1240,564,1280,0,0,0,0,513
    record:
      enabled: True
    snapshots:
      enabled: True
```

### Relevant log output

```shell
*** Config Validation Errors ***
*************************************************************
1 validation error for FrigateConfig

cameras -> doorbell -> ffmpeg -> output_args
value is not a valid dict (type=type_error.dict)
```

### FFprobe output from your camera

```shell
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

hikvision DB-1

### Any other information that may be helpful

These arguments were copied straight from the documentation.
[https://docs.frigate.video/configuration/nvdec](url)

Not sure what to replace it with?
