### ISSUE TITLE
[Support]: Frigate detecting objects in zones that it shouldn't

### ISSUE THREAD

**Issue by danielvschoor** [blakeblackshear/frigate#2735]
### Describe the problem you are having

I'm not sure if this is intended behavior, but the detection on stationary vehicles is using a lot of CPU (cannot find a Coral at the moment).

The yellow zone is "entire_yard" and the orange zone is "front_of_gate". As far as I can tell, I have only included the car object in front_of_gate zone, but it's still being picked up in "entire_yard". Any help/tips would be appreciated.

![image](https://user-images.githubusercontent.com/43602193/152107759-89b68c64-152c-4222-aff2-b945f03c6028.png)

### Version

0.9.4-26AE608

### Frigate config file

```yaml
cameras:
  front_camera_frigate:
    ffmpeg:
     input_args:
       - -fflags
       - nobuffer+genpts+discardcorrupt
       - -flags
       - low_delay
       - -strict
       - experimental
       - -analyzeduration
       - 1000M
       - -probesize
       - 1000M
    
     inputs:
        - path: rtsp://XXXXX:XXXXX@XXXXXXX.100:554//h265Preview_01_main 
          roles:
            - record
          hwaccel_args:
            - -c:v
            - hevc_cuvid        
        - path: http://XXXXXXX.100/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXX&password=XXXXX
          roles:
            - detect
          hwaccel_args:
            - -c:v
            - h264_cuvid          

    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: True
      events:
        required_zones: 
          - front_of_gate
          - entire_yard
    rtmp:
      enabled: False
    
    best_image_timeout: 30

    zones:
      front_of_gate:
        coordinates: 580,110,599,202,436,168,458,75
        objects:
          - person
          - car
      entire_yard:
        coordinates: 640,142,640,360,28,360,63,49
        objects:
          - person
    mqtt:
      required_zones: 
          - front_of_gate
          - entire_yard

motion:
  mask:
    - 640,0,640,141,551,103,456,69,469,0
    - 474,41,493,0,304,0
    - 0,360,69,360,104,0,0,0
    - 0,30,310,30,314,0,0,0

record:
  enabled: True
  retain_days: 7

  events:
    max_seconds: 300
    pre_capture: 10
    post_capture: 15
    objects:
      - person
      - car
    required_zones: [] 
    retain:
      default: 15
      objects:
        person: 30

snapshots:
  enabled: True 
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: 
    - front_of_gate
    - entire_yard
  retain:
    default: 15
    objects:
      person: 30

objects:
  track:
    - person
    - car
  mask: 640,48,640,134,550,93,463,59,469,0
  filters:
    person:
      mask: 640,48,640,134,550,93,463,59,469,0
    car:
      mask: 640,48,462,69,552,92,461,69,469,0
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{
   "detection_fps":8.7,
   "detectors":{
      "cpu1":{
         "detection_start":0.0,
         "inference_speed":62.51,
         "pid":225
      }
   },
   "front_camera_frigate":{
      "camera_fps":5.0,
      "capture_pid":233,
      "detection_fps":8.7,
      "pid":231,
      "process_fps":5.1,
      "skipped_fps":0.0
   },
   "service":{
      "storage":{
         "/dev/shm":{
            "free":66.2,
            "mount_type":"tmpfs",
            "total":67.1,
            "used":0.9
         },
         "/media/frigate/clips":{
            "free":2993318.8,
            "mount_type":"fuse.mergerfs",
            "total":4365303.5,
            "used":1175288.4
         },
         "/media/frigate/recordings":{
            "free":2993318.8,
            "mount_type":"fuse.mergerfs",
            "total":4365303.5,
            "used":1175288.4
         },
         "/tmp/cache":{
            "free":997.6,
            "mount_type":"tmpfs",
            "total":1000.0,
            "used":2.4
         }
      },
      "uptime":673,
      "version":"0.9.4-26ae608"
   }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 812a

### Any other information that may be helpful

Please let me know if more information is needed
