### ISSUE TITLE
[Support]: Audio not working on cameras

### ISSUE THREAD

**Issue by tjcampanella** [blakeblackshear/frigate#2741]
### Describe the problem you are having

I have recently tried to enable audio for my cameras using the args from the docs and the audio still doesn't show up for me. 

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto.local.hass.io
  user: ****
  password: ****
  
ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -f flv -c:a aac

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - truck

detectors:
  coral1:
    type: edgetpu
    device: pci:0
    
birdseye:
  enabled: False
  width: 704
  height: 480
  quality: 8
  mode: continuous
  
record:
  enabled: True
  retain_days: 60
  
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 60

cameras:
  back_left_corner:
    ffmpeg:
      inputs:
      - path: rtsp://admin:admin@192.168.1.21/VideoInput/1/h264/2
        roles:
        - detect
        - rtmp
        
    detect:
      width: 704
      height: 480
      fps: 5
    
... more cameras with the same config
```

### Relevant log output

```shell
No errors in the logs relating to the args.
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:admin@192.168.1.21/VideoInput/1/h264/2
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://admin:admin@192.168.1.21/VideoInput/1/h264/2':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.200000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 704x480, 100 tbr, 90k tbn, 180k tbc
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Lorex E892DD-E

**Comment by blakeblackshear** [comment]
Where are expecting audio? Recordings? Rtmp?

**Comment by tjcampanella** [comment]
@blakeblackshear In recordings and rtmp.

**Comment by blakeblackshear** [comment]
The ffprobe output doesn't list an audio stream at all. Can you confirm that the audio works with VLC and that stream url?

**Comment by G2G2G2G** [comment]
My recordings have no audio but the rtmp stream does lol

copying his config:
```
ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -f flv -c:a aac
```
fixed this, I guess recordings have the audio off by default. My cameras seem to stream aac already so I'm gonna copy that instead of encode as well.

Why is it -f flv isn't that flash player?
