### ISSUE TITLE
[Support]: Frigate causes read only errors and unresponsive Home Assistant server after several hours of running, power cycle required to recover.

### ISSUE THREAD

**Issue by healeydave** [blakeblackshear/frigate#2749]
### Describe the problem you are having

Home Assistant runs fine for days without Frigate running but if I start Frigate, at first, everything looks fine,
all cameras are running fine but after several hours, the whole system becomes unresponsive and the console screen is constantly scrolling with errors like "systemd-journald[114]: failed to write entry (9 items, 332 bytes), ignoring: read only file system". The only way to get control back is to pull the power.

At first I thought my SSD had failed, so I installed a brand new SSD and restored HA. 
Everything came back up ok but I stopped Frigate initially to keep overhead down, that's when I discovered that its running Frigate that causes this problem. 

Another issue I have noticed is that despite having Frigate set to not start on boot, it ignores this switch and starts anyway.
To keep my system running smoothly, when my Pi is powered up, I have to wait for Frigate to start by monitoring the log screen and the click the stop link once that  appears on the add-on screen.

### Version

2.3

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
#    num_threads: 3


ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m


mqtt:
  host: 192.168.1.16
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: USER
  password: PASS
  stats_interval: 60

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous


record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 4


cameras:
  Driveway_Gate:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://USER:PASS@192.168.1.15:554/Streaming/channels/402
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 308,197,313,139,413,142,419,196,447,198,449,143,640,138,640,0,0,0,0,204
    motion:
      mask:
        - 308,197,313,139,413,142,419,196,447,198,449,143,640,138,640,0,0,0,0,204
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3



  Driveway_Bottom:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://USER:PASS@192.168.1.15:554/Streaming/channels/202
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
          mask:
            - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
        dog:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
        car:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
    motion:
      mask:
        - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3



  Driveway_Top:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://USER:PASS@192.168.1.15:554/Streaming/channels/102
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3
```

### Relevant log output

```shell
None retrievable at the time of fault
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision

### Any other information that may be helpful

![IMG_4219](https://user-images.githubusercontent.com/5435141/152652632-95a8d731-3866-49c6-a452-8229ea6649ee.JPG)
