### ISSUE TITLE
[Support]: How to trigger Blue Iris to record on 0.10.0-B1E84CA?

### ISSUE THREAD

**Issue by Danny2100** [blakeblackshear/frigate#2757]
### Describe the problem you are having

On the new beta the binary motion sensors will stay detected when static objects are detected. If it's not possible to alter that where it clears when static objects are detected and nothing is moving then I think the best route to trigger blue iris to record is Mqtt triggers. I pulled apart the notification blueprint and put the way I think this type of automation would work I'm not sure if it will which is why I'm creating this discussion topic. 

First I got an error that I put at the bottom of the code block over the value templates on the choose action. Blue iris has a separate mqtt payload to tag events as a person/car. That's why I am trying to use label = car/person. I also figured the type should be new in order to get blue iris to trigger on the first alert. I assume end is end of the event and that's when blue iris can stop recording. I left in the conditions for the Automation itself from the blueprint however I assume they aren't necessary especially ```type != end``` as that defeats the purpose of the Automation lol. I also assume the variables aren't needed anymore but I left them anyway.

Here's the code block.

```
alias: Frigate Test 2
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: outdoor_4
    value_template: '{{ value_json[''after''][''camera''] }}'
condition:
  - condition: template
    value_template: '{{ type != ''end'' }}'
  - condition: template
    value_template: '{{ not zone_only or entered_zones|length > 0 }}'
  - condition: template
    value_template: >-
      {{ not zones|length or zones|select('in', entered_zones)|list|length > 0
      }}
  - condition: template
    value_template: '{{ not labels|length or object in labels }}'
  - condition: template
    value_template: '{{ not presence_entity or not is_state(presence_entity, ''home'') }}'
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ type = ''new'' }}'
          - condition: template
            value_template: '{{ label = ''person'' }}'
        sequence:
          - service: mqtt.publish
            data:
              topic: BlueIris/admin
              payload: camera=Outdoor4&trigger&flagalert=7
          - wait_for_trigger:
            - platform: mqtt
             topic: frigate/events
             payload: outdoor_4
             value_template: '{{ value_json[''after''][''camera''] }}'
           continue_on_timeout: false
         - condition: template
           value_template: '{{ type = ''''end'''' }}'
            continue_on_timeout: false
          - service: mqtt.publish
            data:
              payload: camera=Outdoor4&trigger=0
              topic: BlueIris/admin
      - conditions:
          - condition: template
            value_template: '{{ type = ''new'' }}'
          - condition: template
            value_template: '{{ label = ''car'' }}'
        sequence:
          - service: mqtt.publish
            data:
              topic: BlueIris/admin
              payload: camera=Outdoor4&trigger&flagalert=11
          - wait_for_trigger:
            - platform: mqtt
             topic: frigate/events
             payload: outdoor_4
             value_template: '{{ value_json[''after''][''camera''] }}'
           continue_on_timeout: false
         - condition: template
           value_template: '{{ type = ''''end'''' }}'
          - service: mqtt.publish
            data:
              payload: camera=Outdoor4&trigger=0
              topic: BlueIris/admin
mode: single
max_exceeded: silent
variables:
  id: '{{ trigger.payload_json[''after''][''id''] }}'
  camera: '{{ trigger.payload_json[''after''][''camera''] }}'
  camera_name: '{{ camera | replace(''_'', '' '') | title }}'
  object: '{{ trigger.payload_json[''after''][''label''] }}'
  label: '{{ object | title }}'
  entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
  type: '{{ trigger.payload_json[''type''] }}'
  base_url: nabu
  group_target: camera_notifications
  zone_only: false
  input_zones: []
  zones: '{{ input_zones | list }}'
  input_labels: []
  labels: '{{ input_labels | list }}'
  presence_entity: ''
  
  
Message malformed: invalid template (TemplateSyntaxError: expected token 'end of print statement', got '=') for dictionary value @ data['action'][0]['choose'][0]['conditions'][0]['value_template']
```

### Version

0.10.0-B1E84CA

### Frigate config file

```yaml
N/a
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Blue Iris
