### ISSUE TITLE
[Support]: Create seperate zone-based object dectections

### ISSUE THREAD

**Issue by kristophercrawford** [blakeblackshear/frigate#2760]
### Describe the problem you are having

I would like to be able to detect people and dogs on the front_porch camera walkway_zone and detect people, cars, dogs, cats on the driveway camera driveway_zone. 

The issue that I am facing is that the front_porch camera is picking up objects that I have not defined in that zone. When debugging the front_porch camera, I see people, cars, dogs, cats. If I remove the main objects entry on line 11-16 of my config, both cameras only show person as a tracked object when debugging the cameras. 

### Version

0.9.4-26ae608

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.33
  user: mqtt
  password: ...

detectors:
  coral:
    type: edgetpu
    device: usb
    
objects:
  track:
    - person
    - car
    - cat
    - dog

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain: 
    default: 3
  required_zones:
    - driveway_zone
    - walkway_zone

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 300
    pre_capture: 2
    post_capture: 2
    retain: 
      default: 3
    required_zones:
      - driveway_zone
      - walkway_zone

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

rtmp:
  enabled: False

cameras:
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:...@192.168.20.100:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:...@192.168.20.100:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      walkway_zone:
        coordinates: 255,576,296,260,479,256,720,378,720,576 #zone for walkway
        objects:
          - person
          - dog
    detect:
      width: 720
      height: 576
      fps: 15
    motion:
      mask:    
        - 0,0,0,126,720,126,720,0 #mask out timestamp

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:...@192.168.20.102:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:...@192.168.20.102:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      driveway_zone:
        coordinates: 672,175,275,67,0,295,0,480,217,480 #zone for driveway
        objects:
          - person
          - car
          - cat
          - dog
    detect:
      width: 704
      height: 480
      fps: 15
    motion:
      mask:   
        - 0,0,0,80,704,80,704,0 #mask out timestamp
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
