### ISSUE TITLE
[Support]: Capturing all animals

### ISSUE THREAD

**Issue by junior466** [blakeblackshear/frigate#2766]
### Describe the problem you are having

I have enabled a few animals in my configuration but It usually only captures my dog (sometimes) and only during the day so I was wondering since I am open to seeing any type of animal in my yard I wanted to know the easiest way to implement capturing all animals,

Is there a way? I believe the `model` section of the documentation is what I need but I don't fully understand it.

### Version

0.9.4-26ae608

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

#detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: motion

record:
  enabled: True
  retain_days: 0
  events:
    max_seconds: 240
    pre_capture: 5
    post_capture: 5
    retain:
      default: 7 

### Driveway ###
cameras:
  driveway_cam:
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - car
        - dog
    ffmpeg:
      inputs:
        - path: rtsp://ha:REDACTED@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
#            - rtmp
            - record

    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True

#    record:
#      events:
#        required_zones:
#          - street_driveway
#          - main_driveway

    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7 
        objects:
          - person
          - car
          - dog
        required_zones:
          - street_driveway
          - main_driveway

    snapshots:
      required_zones:
        - street_driveway
        - main_driveway

    zones:
      street_driveway:
        coordinates: 1856,763,1821,871,1277,691,1334,641
        objects:
          - person
          - car
      main_driveway:
        coordinates: 1328,1080,1136,983,1024,648,1804,908,1744,1080
        objects:
          - person
          - dog
          # - car

    motion:
      mask:
        - 1005,606,1186,896,1055,941,691,1080,406,1080,397,768
        - 1920,0,1920,786,871,503,683,0
        - 0,0,265,0,308,809,0,877

### Backyard ###

  backyard_cam:
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - cat
        - dog
        - bear
        - mouse
    ffmpeg:
      inputs:
        - path: rtsp://ha:REDACTED@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
 #           - rtmp
            - record
  
    record:
      enabled: True
      retain_days: 0
      events:
        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
        objects:
          - person
          - cat
          - dog
          - bear
          - mouse

    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True
  
    motion:
      mask:
        - 1152,399,1920,414,1920,337,1920,0,809,0,0,0,0,546
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest 4K

**Comment by junior466** [comment]
To show some effort, I believe I may need to add something like: 

        model:
          # Optional: path to the model (default: automatic based on detector)
          path: /edgetpu_model.tflite
          # Optional: path to the labelmap (default: shown below)
          labelmap_path: /labelmap.txt
          # Required: Object detection model input width (default: shown below)
          width: 320
          # Required: Object detection model input height (default: shown below)
          height: 320
          # Optional: Label name modifications. These are merged into the standard labelmap.
          labelmap:
            15: bird
            16: cat
            17: dog
            18: horse
            19: sheep
            20: cow
            21: elephant
            22: bear
            23: zebra
            24: giraffe
            73: mouse

to this part of my backyard configuration?

        ### Backyard ###

          backyard_cam:
            rtmp:
              enabled: False
            objects:
              track:
                - person
                - cat
                - dog
                - bear
                - mouse
          
            record:
              enabled: True
              retain_days: 0
              events:
                max_seconds: 240
                pre_capture: 5
                post_capture: 5
                retain:
                  default: 7
                objects:
                  - person
                  - cat
                  - dog
                  - bear
                  - mouse

Also I need to make sure and change the objects listed under `backyard_cam` and `record`?

**Comment by NickM-27** [comment]
It isn't clear (to me) what you're hoping to accomplish. Are you looking to have all animals in the model just be classified as `animal` since you don't care which one? Or are you just wanting to enable all animal types?

**Comment by junior466** [comment]
> It isn't clear (to me) what you're hoping to accomplish. Are you looking to have all animals in the model just be classified as `animal` since you don't care which one? Or are you just wanting to enable all animal types that the model supports?

My goal is to capture anything that resembles an animal or person in my backyard as  I know for a fact that there are animals visiting us at night. I think I started looking at the `model` option and actually got confused.

**Comment by NickM-27** [comment]
Okay, well the way to do that would be:

```yaml
model:
      # Optional: path to the model (default: automatic based on detector)
      path: /edgetpu_model.tflite
      # Optional: path to the labelmap (default: shown below)
      labelmap_path: /labelmap.txt
      # Required: Object detection model input width (default: shown below)
      width: 320
      # Required: Object detection model input height (default: shown below)
      height: 320
      # Optional: Label name modifications. These are merged into the standard labelmap.
      labelmap:
        15: animal
        16: animal
        17: animal
        18: animal
        19: animal
        20: animal
        21: animal
        22: animal
        23: animal
        24: animal
        # 73: mouse this is a computer mouse, not the animal
```

```yaml
backyard_cam:
        rtmp:
          enabled: False
        objects:
          track:
            - person
            - animal
      
        record:
          enabled: True
          retain_days: 0
          events:
            max_seconds: 240
            pre_capture: 5
            post_capture: 5
            retain:
              default: 7
            objects:
              - person
              - animal
```
