### ISSUE TITLE
[Support]: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures

### ISSUE THREAD

**Issue by aceonce** [blakeblackshear/frigate#2769]
### Describe the problem you are having

I've searched thru google along w/ many of the issues posted here, pretty much tried everything in the past few days and still can't get Frigate to pass initially stage of ffmpeg

Codec info
![image](https://user-images.githubusercontent.com/77632305/152883597-01c3b636-1556-4efe-b7c1-e07b55082f29.png)

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 10.0.19.5
  user: *****
  password: ******!
  client_id: frigate
  
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@10.0.29.3/user=*****&password=*****&channel=1&stream=1.sdp?
          roles:
            - detect

      hwaccel_args:
            - -hwaccels
            - vaapi
            - -hwaccel_device
            - /dev/dri/renderD128
            - -hwaccel_output_format
            - yuv420p
      
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
        - -c:v
        - hevc_cuvid
      
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
detect:
  width: 352
  height: 240
  fps: 5
  enabled: True
  max_disappeared: 25    

logger:
  logs:
    frigate.event: debug
    frigate.mqtt: error
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-02-07 16:27:32] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2022-02-07 16:27:32] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-02-07 16:27:32] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-02-07 16:27:32] peewee_migrate                 INFO    : There is nothing to migrate
[2022-02-07 16:27:32] ws4py                          INFO    : Using epoll
[2022-02-07 16:27:32] detector.cpu                   INFO    : Starting detection process: 219
[2022-02-07 16:27:32] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-02-07 16:27:32] frigate.app                    INFO    : Output process started: 220
[2022-02-07 16:27:32] frigate.app                    INFO    : Camera processor started for frontdoor: 228
[2022-02-07 16:27:32] frigate.app                    INFO    : Capture process started for frontdoor: 231
[2022-02-07 16:27:32] ws4py                          INFO    : Using epoll
[2022-02-07 16:27:32] frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-02-07 16:27:32] frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
Not sure how to get this info
```

### Frigate stats

```json
Not sure how to get this info
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Heimvision 245

**Comment by aceonce** [comment]
> ### Describe the problem you are having
> I've searched thru google along w/ many of the issues posted here, pretty much tried everything in the past few days and still can't get Frigate to pass initially stage of ffmpeg
> 
> ### Version
> 0.9.4-26AE608
> 
> ### Frigate config file
> ```yaml
> mqtt:
>   host: 10.0.19.5
>   user: *****
>   password: ******!
>   client_id: frigate
>   
> cameras:
>   frontdoor:
>     ffmpeg:
>       inputs:
>         - path: rtsp://*****:*****@10.0.29.3/user=*****&password=*****&channel=1&stream=1.sdp?
>           roles:
>             - detect
> 
>       hwaccel_args:
>             - -hwaccels
>             - vaapi
>             - -hwaccel_device
>             - /dev/dri/renderD128
>             - -hwaccel_output_format
>             - yuv420p
>       
>       input_args:
>         - -avoid_negative_ts
>         - make_zero
>         - -fflags
>         - +genpts+discardcorrupt
>         - -rtsp_transport
>         - tcp
>         - -stimeout
>         - '5000000'
>         - -use_wallclock_as_timestamps
>         - '1'
>         - -c:v
>         - hevc_cuvid
>       
>       output_args:
>         detect: -f rawvideo -pix_fmt yuv420p
> detect:
>   width: 352
>   height: 240
>   fps: 5
>   enabled: True
>   max_disappeared: 25    
> 
> logger:
>   logs:
>     frigate.event: debug
>     frigate.mqtt: error
> ```
> 
> ### Relevant log output
> ```shell
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [2022-02-07 16:27:32] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
> [2022-02-07 16:27:32] frigate.app                    INFO    : Creating directory: /tmp/cache
> Starting migrations
> [2022-02-07 16:27:32] peewee_migrate                 INFO    : Starting migrations
> There is nothing to migrate
> [2022-02-07 16:27:32] peewee_migrate                 INFO    : There is nothing to migrate
> [2022-02-07 16:27:32] ws4py                          INFO    : Using epoll
> [2022-02-07 16:27:32] detector.cpu                   INFO    : Starting detection process: 219
> [2022-02-07 16:27:32] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
> [2022-02-07 16:27:32] frigate.app                    INFO    : Output process started: 220
> [2022-02-07 16:27:32] frigate.app                    INFO    : Camera processor started for frontdoor: 228
> [2022-02-07 16:27:32] frigate.app                    INFO    : Capture process started for frontdoor: 231
> [2022-02-07 16:27:32] ws4py                          INFO    : Using epoll
> [2022-02-07 16:27:32] frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
> [2022-02-07 16:27:32] frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
> ```
> 
> ### FFprobe output from your camera
> ```shell
> Not sure how to get this info
> ```
> 
> ### Frigate stats
> ```json
> Not sure how to get this info
> ```
> 
> ### Operating system
> HassOS
> 
> ### Install method
> HassOS Addon
> 
> ### Coral version
> CPU (no coral)
> 
> ### Network connection
> Wired
> 
> ### Camera make and model
> Heimvision 245
> 
> ### Any other information that may be helpful
> _No response_

Codec info
![image](https://user-images.githubusercontent.com/77632305/152883421-f3f0f838-c2cf-4c44-aaa2-5eb161560a09.png)

**Comment by NickM-27** [comment]
Similar to [this issue](https://github.com/blakeblackshear/frigate/issues/2745) rtmp was causing the issue due to the stream type. Have you tried disabling RTMP?

**Comment by aceonce** [comment]
RTMP is disabled, just trying to get camera working then detect, nothing else is enabled

**Comment by NickM-27** [comment]
> RTMP is disabled, just trying to get camera working then detect, nothing else is enabled

I just want to be sure, your config file does not show you disabling RTMP

**Comment by aceonce** [comment]
Its way down at the bottom of config file where I didn't copy over due to bunch of commented lines

rtmp:
  enabled: false

**Comment by NickM-27** [comment]
Gotcha, so what happens if you let it run longer than the logs you posted? Does it keep the same 2 ffmpeg errors or does it have other logs as well?

**Comment by aceonce** [comment]
Keeps giving the same error in the logs no matter how long I leave it up.

**Comment by blakeblackshear** [comment]
Try removing your hwaccel args.

**Comment by aceonce** [comment]
Same thing, additional errors w/ invalid hevc_cuvid

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-02-07 18:11:14] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2022-02-07 18:11:14] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-02-07 18:11:14] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-02-07 18:11:14] peewee_migrate                 INFO    : There is nothing to migrate
[2022-02-07 18:11:14] frigate.app                    INFO    : Output process started: 220
[2022-02-07 18:11:14] detector.cpu                   INFO    : Starting detection process: 219
[2022-02-07 18:11:14] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-02-07 18:11:14] ws4py                          INFO    : Using epoll
[2022-02-07 18:11:14] frigate.app                    INFO    : Camera processor started for frontdoor: 225
[2022-02-07 18:11:14] frigate.app                    INFO    : Capture process started for frontdoor: 227
[2022-02-07 18:11:14] ws4py                          INFO    : Using epoll
[2022-02-07 18:11:14] frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-02-07 18:11:14] frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
[2022-02-07 18:11:34] watchdog.frontdoor             ERROR   : FFMPEG process crashed unexpectedly for frontdoor.
[2022-02-07 18:11:34] watchdog.frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-02-07 18:11:34] watchdog.frontdoor             ERROR   : You may have invalid args defined for this camera.
[2022-02-07 18:11:34] ffmpeg.frontdoor.detect        ERROR   : Unknown decoder 'hevc_cuvid'
[2022-02-07 18:11:34] frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-02-07 18:11:34] frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
[2022-02-07 18:11:44] watchdog.frontdoor             ERROR   : FFMPEG process crashed unexpectedly for frontdoor.
[2022-02-07 18:11:44] watchdog.frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-02-07 18:11:44] watchdog.frontdoor             ERROR   : You may have invalid args defined for this camera.
[2022-02-07 18:11:44] ffmpeg.frontdoor.detect        ERROR   : Unknown decoder 'hevc_cuvid'
[2022-02-07 18:11:44] frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-02-07 18:11:44] frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...
[2022-02-07 18:11:54] watchdog.frontdoor             ERROR   : FFMPEG process crashed unexpectedly for frontdoor.
[2022-02-07 18:11:54] watchdog.frontdoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-02-07 18:11:54] watchdog.frontdoor             ERROR   : You may have invalid args defined for this camera.
[2022-02-07 18:11:54] ffmpeg.frontdoor.detect        ERROR   : Unknown decoder 'hevc_cuvid'
[2022-02-07 18:11:54] frigate.video                  INFO    : frontdoor: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-02-07 18:11:54] frigate.video                  INFO    : frontdoor: ffmpeg process is not running. exiting capture thread...

**Comment by aceonce** [comment]
config file

cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:cath0423@10.0.29.3/user=admin&password=cath0423&channel=1&stream=1.sdp?
          roles:
            - detect

#      hwaccel_args:
#            - -hwaccels
#            - vaapi
#            - -hwaccel_device
#            - /dev/dri/renderD128
#            - -hwaccel_output_format
#            - yuv420p
      
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
        - -c:v
        - hevc_cuvid
      
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
detect:
  width: 352
  height: 240
  fps: 5
  enabled: True
  max_disappeared: 25    

logger:
  logs:
    frigate.event: debug
    frigate.mqtt: error

rtmp:
  enabled: false

**Comment by blakeblackshear** [comment]
The error message says `Unknown decoder 'hevc_cuvid'`. Remove the extra input args you added:

```yaml
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:cath0423@10.0.29.3/user=admin&password=cath0423&channel=1&stream=1.sdp?
          roles:
            - detect

#      hwaccel_args:
#            - -hwaccels
#            - vaapi
#            - -hwaccel_device
#            - /dev/dri/renderD128
#            - -hwaccel_output_format
#            - yuv420p
      
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport
        - tcp
        - -stimeout
        - '5000000'
        - -use_wallclock_as_timestamps
        - '1'
      
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
detect:
  width: 352
  height: 240
  fps: 5
  enabled: True
  max_disappeared: 25    

logger:
  logs:
    frigate.event: debug
    frigate.mqtt: error

rtmp:
  enabled: false
```
