### ISSUE TITLE
Camera Name on Beta9 fails with space

### ISSUE THREAD

**Issue by dmkjr** [blakeblackshear/frigate#2776]
### Describe the problem you are having

When upgrading from beta 6 to beta 9, Frigate would not start.  Upon looking at the logs, it did not like a camera name "Back Porch".  I added a "-" instead of the space and it worked.

However, this seems to be a regression from beta 6 UNLESS there was a fundamental issue to keep spaces out of the camera names.

Thanks!

### Version

0.10.0 Beta 9

### Frigate config file

```yaml
mqtt:
  host: *****
cameras:
  Back-Porch:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://dmkjr:******@10.0.10.83/live
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 1280
      height: 720

  dog:
    ffmpeg:
      inputs:
        - path: rtsp://dmkjr:********@10.0.10.142/live
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 1280
      height: 720

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://Dmkjr:********@10.0.10.109/live
          roles:
            - detect
            - rtmp
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - boat
      filters:
        car:
          mask:
            - 344,342,233,343,161,380,84,419,0,508,0,581,0,684,35,720,189,720,309,720,331,654,355,569,388,448,395,363
            - 663,685,690,696,735,720,799,720,882,720,963,720,993,671,1001,599,972,514,900,415,837,344,781,317,717,314,698,312,601,335
            - 899,157,1011,168,1057,197,1107,231,1112,283,860,282,837,215
    detect:
      width: 1280
      height: 720


snapshots:
  enabled: True
  timestamp: True
  retain:
    default: 10

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 10
      mode: motion
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

WyzeCam V3
