### ISSUE TITLE
Support SRT Stream

### ISSUE THREAD

**Issue by G2G2G2G** [blakeblackshear/frigate#2818]
Someone said this, but closed it:
https://github.com/blakeblackshear/frigate/issues/2736

Info:
https://www.haivision.com/blog/all/rtmp-vs-srt/
https://restream.io/blog/streaming-protocols/
how to:
https://stackoverflow.com/questions/62977448/minimal-srt-stream-example-with-ffmpeg

I do not know of any existing cons of SRT, so supporting it would make sense.

If allowed in the config to set  srt://x.x.x.x instead of rtmp:// that's pretty much all we'd need from the looks of it.

**Comment by yury-sannikov** [comment]
In theory, you could try:
```yaml
camera_name:
  gstreamer:
    inputs:
      - path: srtsrc uri="srt://127.0.0.1:7001" latency=0 name=rtp_stream
        roles:
          - detect
  detect:
    width: 1920
    height: 1080
```
Though you have to build [this](https://github.com/blakeblackshear/frigate/pull/2548) branch manually for your platform.

more info: https://gstreamer.freedesktop.org/documentation/srt/srtsrc.html?gi-language=c#srtsrc-page
