### ISSUE TITLE
[Support]: Stationary objects feature in 0.10.0

### ISSUE THREAD

**Issue by junior466** [blakeblackshear/frigate#2842]
### Describe the problem you are having

Thanks for the awesome release!

I have a very interesting setup in my driveway where two cars are usually always parked when we are home but want to avoid being notified of them when stationary so I created two zones as described in the documentation. It works fairly well for the most part but due to how my camera is positioned, I usually always miss events due to all the masking as the camera also faces the street. I originally had the street mask and I believe that is the reason for the missed events since Frigate can't track the objects as they approach the zone. 

Here's an image of my driveway with the street unmasked for reference:

[Image](https://imgur.com/8KW2G5g) 

I used to deal with the stationary objects with two zones: Yellow only detected person and orange detected person and car.

Now that we have a way to tune stationary objects, I was wondering if I should merge the two zones into one and use the new `detect:` option to properly deal with the cars that are usually there. 

Should this work? if so, any recommendations?

### Version

0.10.0

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 14

model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: motion  

### Driveway ###

cameras:
  driveway_cam:
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - car
        - dog
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
#            - rtmp
            - record

    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True

    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - car
          - animal
        required_zones:
          - street_driveway
          - main_driveway

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - street_driveway
        - main_driveway
      retain:
        default: 14

    motion:
      mask:
         - 1920,0,1920,610,863,432,846,687,1053,941,677,1080,0,1080,0,0

    zones:
      street_driveway:
        coordinates: 1856,763,1821,871,871,575,902,538
        objects:
          - person
          - car
      main_driveway:
        coordinates: 1328,1080,1136,983,852,575,1920,929,1920,1080
        objects:
          - person
          - dog

    objects:
      filters:
        car:
          mask:
            - 1920,0,1920,610,863,432,846,687,1053,941,677,1080,0,1080,0,0
        dog:
          mask:
            - 1920,0,1920,610,863,432,846,687,248,803,0,865,0,0
        person:
          mask:
            - 1920,0,1920,610,863,432,846,687,248,803,0,865,0,0
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

AMCREST 4K
