### ISSUE TITLE
[Support]: Upgrade from 0.9.4-26AE608 -> 0.10.0 stalls

### ISSUE THREAD

**Issue by jschwalbe** [blakeblackshear/frigate#2845]
### Describe the problem you are having

I pulled the new docker image and tried restarting (after making the necessary changes to the config file). It does not start. Logs below.

### Version

0.10.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.25.81
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: secretpassword
  stats_interval: 60
 
cameras:
  doorbell:                  #### DOORBELL ####
    ffmpeg:
      inputs:
        - path: rtsp://x
          roles:
            - detect
        - path: rtsp://x
          roles:
            - record
            - rtmp
      #output_args:
      #  record: -c:a aac
    detect:
      width: 720
      height: 576
      fps: 5
    motion:
      mask:
        - 720,0,720,28,485,25,482,0
      contour_area: 10
    rtmp:
      enabled: true
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - cat
        - dog
        - car    

  patiodoor:                 #### PATIO DOOR ####
    ffmpeg:
      inputs:
        - path: rtsp://x
          roles:
            - detect
        - path: rtsp://x
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 10
        objects:
          person: 15
    objects:  
      track: 
        - person
        - cat
        - dog
        - car  
        - deer

  garage:                  #### GARAGE ####
    ffmpeg:
      inputs:
        - path: rtsp://x
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:   
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - car

  basement:                  #### BASEMENT ####
    ffmpeg:
      inputs:
        - path: rtsp://x
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:   
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
        - car

  bunk_room:                  #### BUNK CAM ####
    ffmpeg:
      inputs:
        - path: rtsp://x
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: true
    snapshots:  
      enabled: true      
      timestamp: false
      bounding_box: true
      crop: False   
      retain:     
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person   

  familyroom:                             #### FAMILY ROOM ####
    ffmpeg:
      inputs:
        - path: "rtsp://x"
          roles:
            - detect
        - path: "rtsp://x"
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
      #interval: 10
      #threshold: 50
    motion:
      mask:
        - 640,21,640,45,450,45,436,21
    zones:
#      kitchen:
#        coordinates: 374,336,462,337,474,265,543,255,547,138,372,152
      fan_area:
        coordinates: 59,480,297,454,260,114,82,85
    rtmp:
      enabled: false
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:   
        default: 0
        objects:
          person: 15
    objects:
      track:
        - person

  extra_cam:                  #### EXTRA CAM ####
    ffmpeg:     
      inputs:       
        - path: rtsp://x
          roles:   
            - detect
            - record
            - rtmp
    detect:  
      width: 1920
      height: 1080
      fps: 5
    rtmp:       
      enabled: true 
    snapshots:    
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person


record:
  enabled: true
  #retain:              #had to comment for rollback to version 0.9
  #  days: 7            #had to comment for rollback to version 0.9
  #  mode: motion       #had to comment for rollback to version 0.9
  events:
    max_seconds: 300
    pre_capture: 15
    post_capture: 15
    objects:
      - person
    retain:
      default: 10
 #     mode: active_objects  #had to comment for rollback to version 0.9

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
```

### Relevant log output

```shell
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-02-20 17:02:48] frigate.app                    INFO    : Starting Frigate (0.10.0-bfecee9)
Starting migrations
[2022-02-20 17:02:48] peewee_migrate                 INFO    : Starting migrations
Migrate "005_make_end_time_nullable"
[2022-02-20 17:02:50] peewee_migrate                 INFO    : Migrate "005_make_end_time_nullable"
drop_not_null ('event', 'end_time')
[2022-02-20 17:02:50] peewee_migrate                 INFO    : drop_not_null ('event', 'end_time')

(nothing more happens)
```

### FFprobe output from your camera

```shell
(not necessary?)
```

### Frigate stats

```json
502 Bad Gateway
nginx/1.18.0
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

various amcrest, etc

### Any other information that may be helpful

Works perfectly on 0.94, running macOS on an M1 processor.

Thank you!
