### ISSUE TITLE
[Support]: Birdeye with 3 cameras shows 4'th square with some stuff in

### ISSUE THREAD

**Issue by paltskallen** [blakeblackshear/frigate#2850]
### Describe the problem you are having

I have a setup with 3 cameras, and in birdeye view all 3 shows ok but the 4'th square contains some garbage in top left corner, see screenshot

![birdeye](https://user-images.githubusercontent.com/44400122/154925277-6031f664-3d7d-4b21-92b7-8ea3666a3208.JPG)

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: -hide_banner -loglevel info

logger:
  default: error


objects:
  track:
    - person
    - vehicle
    - animal

  filters:
    person:
      min_area: 4000
      max_area: 100000
      threshold: 0.65

mqtt:
  host: 192.168.x.y

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

model:
  labelmap:
    0: person
    1: vehicle
    2: vehicle
    3: vehicle
    4: vehicle
    5: vehicle
    6: vehicle
    7: vehicle
    8: vehicle
    14: animal
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects

cameras:
  uppfart:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@webcam1.lan/11
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 8
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30


  entre:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyyy@192.168.x.y:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 8
    motion:
      mask:
        - 482,0,794,21,372,279,0,411,0,0
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30


  garage:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:yyy@webcam6.lan:554/11
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 6
    motion:
      mask:
        - 0,1080,790,1080,545,724,0,735
    objects:
      mask:
        - 0,1080,790,1080,545,724,0,735
      track:
        - person
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.17,"pid":210}},"entre":{"camera_fps":8.1,"capture_pid":224,"detection_fps":0.0,"pid":214,"process_fps":8.1,"skipped_fps":0.0},"garage":{"camera_fps":6.0,"capture_pid":227,"detection_fps":0.0,"pid":218,"process_fps":6.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":526.1,"mount_type":"tmpfs","total":536.9,"used":10.8},"/media/frigate/clips":{"free":580093.4,"mount_type":"ext4","total":1090709.9,"used":464622.9},"/media/frigate/recordings":{"free":580093.4,"mount_type":"ext4","total":1090709.9,"used":464622.9},"/tmp/cache":{"free":1069.6,"mount_type":"tmpfs","total":1073.7,"used":4.1}},"temperatures":{},"uptime":164940,"version":"0.10.0-bfecee9"},"uppfart":{"camera_fps":8.1,"capture_pid":220,"detection_fps":0.0,"pid":213,"process_fps":8.1,"skipped_fps":0.0}}
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink and others
