### ISSUE TITLE
[Support]: Stationary person sensor for room occupancy issue

### ISSUE THREAD

**Issue by Quentin-Cloos** [blakeblackshear/frigate#2853]
### Describe the problem you are having

Hello, I'm glad to see that the new version add the ability to track stationary objects, I have a large room divided in 3 zones and I want to have a binary sensor that stay on when someone stay in a zone, I'm not sure that I understand correctly the new version (I have randomly tweaked the values but no change) because I can see that a person is detected in that zone in the debug mode but my binary sensor in Home Assistant goes on when I enter in the zone but then goes off after a few seconds. 

Is there a way to tweak my code ?

A huge thank you in advance for your help and thank you for your work! 🙂 

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
The code of the room:

  main_room_pir:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.12/live/ch00_1
          roles:
            - detect
    objects:
      track:
        - person
    motion:
      mask:
        #Mask the timestamp
        - 593,0,575,33,345,29,323,0
      contour_area: 30
    zones:
      salon:
        coordinates: 371,0,374,171,272,198,123,120,179,0
        objects:
          - person
      salle_a_manger:
        coordinates: 0,360,196,304,235,209,139,113,143,0,0,0
        objects:
          - person
      cuisine:
        coordinates: 640,360,0,360,0,360,375,173,371,0,640,0
        objects:
          - person
    detect:
      width: 640
      height: 360
      fps: 1
      enabled: True
      stationary:
        interval: 0
        max_frames:
          objects:
            person: 1000
    snapshots:
      enabled: false
      retain: 
        default: 1
      required_zones:
        - salon
        - salle_a_manger
        - cuisine
    record:
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
        required_zones:
          - salon
          - salle_a_manger
          - cuisine
    rtmp:
      enabled: False
```

### Relevant log output

```shell
Log is ok (Only info and warning for the CPU)
```

### FFprobe output from your camera

```shell
None
```

### Frigate stats

```json
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Chinese camera

### Any other information that may be helpful

![frigate-screenshot](https://user-images.githubusercontent.com/36499953/155164377-31180008-ee13-412d-8cfe-a067f3305141.jpg)
_

**Comment by NickM-27** [comment]
You likely do not want to define `max_frames` as that disables stationary detection.

Per the [docs](https://docs.frigate.video/configuration/index):
![Screen Shot 2022-02-21 at 2 06 59 PM](https://user-images.githubusercontent.com/14866235/155026347-6c11c00d-42ab-4a2f-aaf5-6abd65bdebfe.png)

**Comment by Quentin-Cloos** [comment]
> You likely do not want to define `max_frames` as that disables stationary detection.
> 
> Per the [docs](https://docs.frigate.video/configuration/index): ![Screen Shot 2022-02-21 at 2 06 59 PM](https://user-images.githubusercontent.com/14866235/155026347-6c11c00d-42ab-4a2f-aaf5-6abd65bdebfe.png)
> 
> What is it you are trying to achieve that didn't work with the setup that was the same as 0.9.4?

Even without the max_frame my zone motion binary sensor is off when I can see a person detected in that zone in the debug camera, I want it to be always on when a person is detected in it, even stationary. I thought that it was the point of this update but maybe I'm wrong?

**Comment by NickM-27** [comment]
@Quentin-Cloos Just to be clear, in the frigate debug screen you see a person as still being detected but stationary (bounding box is yellow and not moving / resizing at all), but the binary_sensor is false? I have my car in my driveway zone which is stationary and the `binary_sensor.zone_car_motino` shows as `Detected` along with the `sensor.zone_car` showing as `1 object`. 

Some screenshots of your debug screen + HASS entities will help in understanding what is going on.

**Comment by Raphael909** [comment]
Looks like setting interval 0 disables the stationary tracking altogether
from docs 
`# When set to 0, object detection will never be run on stationary objects.`
Probably you may want to do something like 
stationary:
        interval: 10

**Comment by NickM-27** [comment]
@Raphael909 What that means is that once an object is considered stationary, there will be no `detection` run to confirm it is still there. `detection` will only be run when motion occurs. `0` is the default value for this and should remain that way for testing.

**Comment by Quentin-Cloos** [comment]
> @Quentin-Cloos Just to be clear, in the frigate debug screen you see a person as still being detected but stationary (bounding box is yellow and not moving / resizing at all), but the binary_sensor is false? I have my car in my driveway zone which is stationary and the `binary_sensor.zone_car_motino` shows as `Detected` along with the `sensor.zone_car` showing as `1 object`. This has lasted for hours without change, so there must be something else at play.
> 
> Some screenshots of your debug screen + HASS entities will help in understanding what is going on.

Yes It's exactly that, even the sensor show me 0 object when this is happening (and I can still see 1 or 2 persons in that zone, and the timestamp is not frozen), but when it work it's like what you have. I can post a screenshot tomorrow but it will only show a person detected (with the percentage) in a zone and a motion sensor that is off. I spent all my day trying to figure this out 🤔

**Comment by NickM-27** [comment]
@Quentin-Cloos I think the part that would be most helpful would be a screenshot of the debug screen and the person bounding box showing the zones. With no knowledge of that it is difficult to say, but if I had to guess I would say this is an issue with the zones. An object being in a zone is determined by if the bottom center of the bounding box is within the zone outline, so it is important to set your zones up with that in mind (not suggesting you haven't already done that, just covering a common cause for this behavior). 

Barring that, the above info would still be helpful to see what is happening with the detected objects and why it might be dropping out of the zone.

**Comment by Quentin-Cloos** [comment]
> @Quentin-Cloos I think the part that would be most helpful would be a screenshot of the debug screen and the person bounding box showing the zones. With no knowledge of that it is difficult to say, but if I had to guess I would say this is an issue with the zones. An object being in a zone is determined by if the bottom center of the bounding box is within the zone outline, so it is important to set your zones up with that in mind (not suggesting you haven't already done that, just covering a common cause for this behavior).
> 
> Barring that, the above info would still be helpful to see what is happening with the detected objects and why it might be dropping out of the zone.
> 
> Edit: Another point of clarification is that in the debug screen a zone will show up as thicker if it currently has an object apart of it, if this line goes back to thinner then that would mean the HASS entity would go back to 0 / off

I'm at work now and I will post a screenshot later, but the line is indeed thicker when this is happening (and the bottom center of the person is always in the zone), it's why I wonder if that can be a bug. But thanks for your help, I hope we will found out what's happening here.

**Comment by blakeblackshear** [comment]
Looking at the code, I don't see how this could happen unless the object is not in the zone or is missing. Does the outline of the person turn blue when this happens? Are you sure the bottom center of the person box is in the zone? It doesn't matter if 99.999% of the person box overlaps with the zone if the bottom center is outside of the zone.

**Comment by Quentin-Cloos** [comment]
![frigate-screenshot](https://user-images.githubusercontent.com/36499953/155158644-422e89ef-a2ee-4d04-b85f-1b42123c01a6.jpg)

I have realized that the sensor goes on only when I enter the zone (it stay on if I don't stop moving), if I stay stationary for too long it stop detecting me, then the sensor don't turn on even when it detect me, I have to leave the zone then entering it again for the sensor to turn on again. Ask me if you need more info.

**Comment by NickM-27** [comment]
> ![frigate-screenshot](https://user-images.githubusercontent.com/36499953/155158644-422e89ef-a2ee-4d04-b85f-1b42123c01a6.jpg)
> 
> 
> 
> I have realized that the sensor goes on only when I enter the zone (it stay on if I don't stop moving), if I stay stationary for too long it stop detecting me, then the sensor don't turn on even when it detect me again, I have to leave the zone then entering it again for the sensor to turn on again. Ask me if you need more info.
> 
> 
> 
> EDIT: 15min without being detected and without leaving the zone, but when I move I can see myself detected in Frigate with de thicker line around my zone like in my screenshot on the top. And to clarify both screenshot were taken when the sensor is off.

I see, that's helpful. Can you update the OP with your current config? It shouldn't be losing you if you stay still with default config settings.

**Comment by NickM-27** [comment]
> > Looking at the code, I don't see how this could happen unless the object is not in the zone or is missing. Does the outline of the person turn blue when this happens? Are you sure the bottom center of the person box is in the zone? It doesn't matter if 99.999% of the person box overlaps with the zone if the bottom center is outside of the zone.
> 
> 
> 
> I just moved more then the outline turned blue and my sensor was turned on, what is the difference between those two outline colors? It seems to be the key of my issue.

Yellow (in case of person) means a person is detected and being tracked. Blue means frigate has lost the person and the blue box is the last place person was detected

**Comment by Quentin-Cloos** [comment]
> > > Looking at the code, I don't see how this could happen unless the object is not in the zone or is missing. Does the outline of the person turn blue when this happens? Are you sure the bottom center of the person box is in the zone? It doesn't matter if 99.999% of the person box overlaps with the zone if the bottom center is outside of the zone.
> > 
> > 
> > I just moved more then the outline turned blue and my sensor was turned on, what is the difference between those two outline colors? It seems to be the key of my issue.
> 
> Yellow (in case of person) means a person is detected and being tracked. Blue means frigate has lost the person and the blue box is the last place person was detected

In my case it detect me only when the outline is blue 🤔

**Comment by NickM-27** [comment]
The screenshot you posted showed the box as yellow and the zone as active. What part are you saying only detects when the box is blue?

**Comment by Quentin-Cloos** [comment]
> The screenshot you posted showed the box as yellow and the zone as active. What part are you saying only detects when the box is blue?

Yes Frigate detect me, but when I'm in yellow my sensor in HA is off, when I move more then it turn blue and my sensor turn on.

**Comment by Quentin-Cloos** [comment]
> The stopping detecting while you're stationary is likely a config issue. If you have stationary: interval: anything other than 0 it will keep trying to detect after you are stationary (so 0 is a good value to test with until this is figured out) and if max_frames is set then there is a time limit for how long you're stationary before frigate will just drop the detection entirely

I already have changed that yesterday, this issue still remain. This is all I have in detect.

```
    detect:
      width: 640
      height: 360
      fps: 1
      enabled: True
      stationary:
        interval: 0
```

**Comment by blakeblackshear** [comment]
Do you have any object filters defined? I can only see the portion of the config you posted. This may be a case where the detection scores are just too low and it's losing track of the object.

**Comment by Quentin-Cloos** [comment]
> Do you have any object filters defined? I can only see the portion of the config you posted. This may be a case where the detection scores are just too low and it's losing track of the object.

I don't have any filters for this camera. Sorry I should post my full code, here it is:


```
mqtt:
  host: 192.168.0.9
  user: mqtt
  password: ******
  client_id: frigate
  
cameras:
  sonnette_pir:
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@192.168.0.83:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:******@192.168.0.83:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
#      hwaccel_args:
#        - -c:v
#        - h264_v4l2m2m
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0,360,106,360,299,360,314,224,536,221,533,232,640,257,640,0,0,0
#        person:
#          mask:
#            - 0,61,640,70,640,0,0,0
    detect:
      width: 640
      height: 360
      fps: 2
      enabled: True
    snapshots:
      enabled: true
      retain: 
        default: 2
      required_zones:
        - avant_maison
        - entering_cars
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
        required_zones:
          - avant_maison
          - entering_cars
    rtmp:
      enabled: False
    motion:
      mask:
        - 0,0,640,0,640,215,583,142,468,81,396,23,272,21,227,65,187,142,80,170,0,205
    zones:
      entering_cars:
        coordinates: 640,360,573,303,553,243,538,225,311,226,307,360
        objects:
          - car
      avant_maison:
        coordinates: 640,0,640,360,0,360,0,0
        objects:
          - person

  cuisine_pir:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.12/live/ch00_1
          roles:
            - detect
#            - record
#      hwaccel_args:
#        - -c:v
#        - h264_v4l2m2m
    objects:
      track:
        - person
    motion:
      mask:
        - 593,0,575,33,345,29,323,0
      contour_area: 30
    zones:
      salon:
        coordinates: 371,0,374,171,272,198,123,120,179,0
        objects:
          - person
      salle_a_manger:
        coordinates: 0,360,196,304,235,209,139,113,143,0,0,0
        objects:
          - person
      cuisine:
        coordinates: 640,360,0,360,0,360,375,173,371,0,640,0
        objects:
          - person
    detect:
      width: 640
      height: 360
      fps: 1
      enabled: True
      stationary:
        interval: 0
    snapshots:
      enabled: false
      retain: 
        default: 1
      required_zones:
        - salon
        - salle_a_manger
        - cuisine
    record:
      enabled: false
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
        required_zones:
          - salon
          - salle_a_manger
          - cuisine
    rtmp:
      enabled: False
        
  entree_pir:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.57/
          roles:
            - detect
#      hwaccel_args:
#        - -c:v
#        - h264_v4l2m2m
    objects:
      track:
        - person
    detect:
      width: 320 #1280
      height: 180 #720
      fps: 1
    snapshots:
      enabled: false
      retain: 
        default: 1
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 3
          mode: active_objects
    rtmp:
      enabled: False

detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2
  cpu3:
    type: cpu
    num_threads: 2
```

**Comment by NickM-27** [comment]
It's possible that the camera has trouble keeping track of you with your legs occluded. Even when it finds you, it shows the score as 54% so it seems likely that the issue is it doesn't see a person in the cases where it goes to off. The things I can think of trying would be:

1. Reduce `min_score` and `threshold` for person which would probably lead to many false positives
2. Change the position / angle of the camera so that it has more view of people sitting on the couch
3. Maybe some camera settings being changed to make people easier to see against the couch?
4. Maybe try reducing motion sensitivity so that slight body movements won't be counted as motion so stationary tracking will be set more quickly.

Also just wanted to note that it is only doing stationary tracking when the size isn't changing / box isn't moving. If you see the box moving / size changing even slightly then stationary tracking hasn't activated. 

I don't know which, if any, of the above ideas will work or work best. Perhaps blake has some more specific advice.

**Comment by Quentin-Cloos** [comment]
> It's possible that the camera has trouble keeping track of you with your legs occluded. Even when it finds you, it shows the score as 54% so it seems likely that the issue is it doesn't see a person in the cases where it goes to off. The things I can think of trying would be:
> 
> 1. Reduce `min_score` and `threshold` for person which would probably lead to many false positives
> 2. Change the position / angle of the camera so that it has more view of people sitting on the couch
> 3. Maybe some camera settings being changed to make people easier to see against the couch?
> 4. Maybe try reducing motion sensitivity so that slight body movements won't be counted as motion so stationary tracking will be set more quickly.
> 
> Also just wanted to note that it is only doing stationary tracking when the size isn't changing / box isn't moving. If you see the box moving / size changing even slightly then stationary tracking hasn't activated.
> 
> I don't know which, if any, of the above ideas will work or work best. Perhaps Blake has some more specific advice.

I was thinking that it was the solution but no change, now I wonder if it's not the HASS component that have an issue. I have changed the filters with:

```
    zones:
      salon:
        coordinates: 371,0,374,171,272,198,123,120,179,0
        objects:
          - person
        filters:
          person:
            min_score: 0.4
            threshold: 0.5
```
![frigate-fuuuu](https://user-images.githubusercontent.com/36499953/155368404-5dd1f274-c7bf-46c3-91c1-70d71f29f41a.jpg)

It should at least show 2 persons but it show 0... I'm clueless.
