### ISSUE TITLE
[Support]: Person detection when wearing something matching background

### ISSUE THREAD

**Issue by junior466** [blakeblackshear/frigate#2855]
### Describe the problem you are having

With the new update, I started making some adjustments and noticed that if a person is wearing something that matches the background, motion detection takes some time before it kicks in (a person is detected). I noticed this issue mainly on my driveway (dark color) and a person is wearing something dark. 

I understand that this is not necessary a Frigate issue but was wondering if there's anything I can adjust to make it more sensitive. 

### Version

0.10.0

### Frigate config file

```yaml
# mqtt
mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 14

model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: motion  

### Driveway ###

cameras:
  driveway_cam:
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - car
        - dog
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
#            - rtmp
            - record

    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True

    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - car
          - animal
        required_zones:
          - street_driveway
          - main_driveway

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - street_driveway
        - main_driveway
      retain:
        default: 14

    motion:
      mask:
         - 1920,0,1920,610,863,432,846,687,1053,941,677,1080,0,1080,0,0

    zones:
      street_driveway:
        coordinates: 1856,763,1821,871,871,575,902,538
        objects:
          - person
          - car
      main_driveway:
        coordinates: 1328,1080,1136,983,852,575,1920,929,1920,1080
        objects:
          - person
          - dog

    objects:
      filters:
        car:
          mask:
            - 1920,0,1920,610,863,432,846,687,1053,941,677,1080,0,1080,0,0
        dog:
          mask:
            - 1920,0,1920,610,863,432,846,687,248,803,0,865,0,0
        person:
          mask:
            - 1920,0,1920,610,863,432,846,687,248,803,0,865,0,0
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest 4K
