### ISSUE TITLE
[Support]: Object masks ignored

### ISSUE THREAD

**Issue by Baumi1245** [blakeblackshear/frigate#2857]
### Describe the problem you are having

Since update from 0.9.4 it looks like object mask are ignored

### Version

0.10.0-bfecee9

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "Eingang": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "qsv",
          "-qsv_device",
          "/dev/dri/renderD128"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pwd@192.168.125.87:554/11",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel qsv -qsv_device /dev/dri/renderD128 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pwd@192.168.125.87:554/11 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Eingang-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/Eingang -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": [
          "0,182,437,154,621,151,761,207,899,220,1280,285,1280,0,0,0",
          "1170,720,1280,486,1280,720"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "Eingang",
      "objects": {
        "filters": {
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 16000,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [
              "942,196,938,307,875,305,876,193",
              "45,201,44,302,121,300,117,201"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "car"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 25,
          "green": 25,
          "red": 255
        },
        "effect": null,
        "format": "%d.%m.%Y %H:%M:%S",
        "position": "br",
        "thickness": 3
      },
      "zones": {
        "Carport": {
          "coordinates": "665,192,656,297,553,311,424,276,428,188",
          "filters": {
            "person": {
              "mask": null,
              "max_area": 15000,
              "min_area": 0,
              "min_score": 0.4,
              "threshold": 0.6
            }
          },
          "objects": [
            "person"
          ]
        },
        "Carport_Einfahrt": {
          "coordinates": "665,175,666,306,566,311,504,342,325,335,161,328,164,207",
          "filters": {
            "car": {
              "mask": null,
              "max_area": 30000,
              "min_area": 16500,
              "min_score": 0.05,
              "threshold": 0.06
            }
          },
          "objects": [
            "car",
            "person"
          ]
        },
        "Einfahrt": {
          "coordinates": "42,249,114,250,125,296,220,306,513,326,1161,396,1280,428,1280,479,1163,720,1124,720,1002,679,688,660,367,614,244,640,154,472,110,369,42,349",
          "filters": {},
          "objects": [
            "car",
            "person"
          ]
        },
        "Einfahrt_vorne": {
          "coordinates": "226,198,244,320,112,369,45,344,45,212",
          "filters": {
            "car": {
              "mask": null,
              "max_area": 40000,
              "min_area": 20000,
              "min_score": 0.2,
              "threshold": 0.2
            }
          },
          "objects": [
            "car"
          ]
        },
        "Gehsteig": {
          "coordinates": "1003,677,664,649,366,606,264,618,171,469,114,369,40,348,51,516,95,720,1127,720",
          "filters": {},
          "objects": [
            "person"
          ]
        },
        "Gehsteig_hinten": {
          "coordinates": "1003,677,664,649,366,606,256,624,241,599,74,611,28,423,0,354,0,598,0,720,1127,720",
          "filters": {},
          "objects": [
            "person"
          ]
        },
        "Gehsteig_vorne": {
          "coordinates": "57,510,38,341,117,362,264,638,86,671",
          "filters": {
            "person": {
              "mask": null,
              "max_area": 60000,
              "min_area": 0,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "person"
          ]
        }
      }
    },
    "ddmall": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": false,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "qsv",
          "-qsv_device",
          "/dev/dri/renderD128"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pwd@192.168.125.99:8554/live0",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel qsv -qsv_device /dev/dri/renderD128 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pwd@192.168.125.99:8554/live0 -c copy -f flv rtmp://127.0.0.1/live/ddmall -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "ddmall",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 25,
          "green": 25,
          "red": 255
        },
        "effect": null,
        "format": "%d.%m.%Y %H:%M:%S",
        "position": "br",
        "thickness": 3
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "cpu": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [
      "-hwaccel",
      "qsv",
      "-qsv_device",
      "/dev/dri/renderD128"
    ],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.125.100",
    "password": "xxx",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "instar"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 25,
      "green": 25,
      "red": 255
    },
    "effect": null,
    "format": "%d.%m.%Y %H:%M:%S",
    "position": "br",
    "thickness": 3
  }
}
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Instar IN-9020

### Any other information that may be helpful

Person mask
![screenshot 139](https://user-images.githubusercontent.com/4786346/155077996-00a9c251-2fc5-45e8-bb34-ceb61f257221.jpg)

Triggered by the light on the left side
![Eingang-1645464897 984806-ons7hd](https://user-images.githubusercontent.com/4786346/155078035-1413e7d0-daec-4dfb-8d97-6e07e36e8c2d.jpg)

both pictures together
![screenshot](https://user-images.githubusercontent.com/4786346/155078047-3baf748e-855c-4c12-96cb-0d8f9c31f239.jpg)
