### ISSUE TITLE
[Support]: Help with RTMP streams

### ISSUE THREAD

**Issue by junior466** [blakeblackshear/frigate#2862]
### Describe the problem you are having

I am trying to get RTMP working but I am having no luck. I input the correct address in VLC but nothing plays. I am using both streams from the camera if it matters. Frigate unfortunately is not showing any errors associated. 

### Version

0.10.0

### Frigate config file

```yaml
#########################################################
## Global
#########################################################
mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 14

model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

birdseye:
  enabled: False
#  width: 1920
#  height: 1080
#  quality: 8
#  mode: motion  
  
##########################################################
## Driveway
##########################################################
cameras:
  driveway_cam:
    rtmp:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://ha:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://ha:REDACTED$@192.168.141.14:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

    detect:
      width: 704
      height: 480
      fps: 5
      enabled: True

    objects:
      track:
        - person
        - car
        - animal
      filters:
        person:
          mask:
            - 312,232,306,299,0,341,0,0,704,0,704,338
        car:
          mask:
            - 312,232,306,299,0,341,0,0,704,0,704,338
        animal:
          mask:
            - 312,232,306,299,0,341,0,0,704,0,704,338

    motion:
      mask:
         - 312,232,306,299,0,341,0,0,704,0,704,338
         - 345,480,389,411,323,318,156,358,160,480

    zones:
      driveway:
        coordinates: 338,310,386,423,478,480,704,480,704,343,541,309,410,270
        objects:
          - person
          - animal
          - car

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - driveway
#        - street
      retain:
        default: 14

    record:
      enabled: True
      retain:
        days: 14
        mode: motion
      events:
        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 14
          mode: active_objects
        objects:
          - person
          - car
          - animal
        required_zones:
          - driveway
#          - street
```

### Relevant log output

```shell
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Starting Frigate (0.10.0-bfecee9)
frigate    | Starting migrations
frigate    | [2022-02-22 15:34:35] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2022-02-22 15:34:35] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Output process started: 216
frigate    | [2022-02-22 15:34:35] frigate.mqtt                   INFO    : Turning off recordings for living_room_cam via mqtt
frigate    | [2022-02-22 15:34:35] frigate.mqtt                   INFO    : Turning off detection for living_room_cam via mqtt
frigate    | [2022-02-22 15:34:35] detector.coral                 INFO    : Starting detection process: 215
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Camera processor started for driveway_cam: 220
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Camera processor started for backyard_cam: 221
frigate    | [2022-02-22 15:34:35] ws4py                          INFO    : Using epoll
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Camera processor started for living_room_cam: 224
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Capture process started for driveway_cam: 227
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Capture process started for backyard_cam: 228
frigate    | [2022-02-22 15:34:35] frigate.app                    INFO    : Capture process started for living_room_cam: 233
frigate    | [2022-02-22 15:34:35] ws4py                          INFO    : Using epoll
frigate    | [2022-02-22 15:34:35] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | [2022-02-22 15:34:38] frigate.edgetpu                INFO    : TPU found
frigate    | [2022-02-22 15:34:47] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38756]
frigate    | [2022-02-22 15:34:53] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38756]
frigate    | [2022-02-22 15:35:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38798]
frigate    | [2022-02-22 15:35:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:37852]
frigate    | [2022-02-22 15:36:02] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:37852]
frigate    | [2022-02-22 15:36:15] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38798]
frigate    | [2022-02-22 15:37:53] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38938]
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"backyard_cam":{"camera_fps":5.1,"capture_pid":228,"detection_fps":0.0,"pid":221,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":2.5,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.73,"pid":215}},"driveway_cam":{"camera_fps":5.0,"capture_pid":227,"detection_fps":2.5,"pid":220,"process_fps":5.1,"skipped_fps":0.0},"living_room_cam":{"camera_fps":5.0,"capture_pid":233,"detection_fps":0.0,"pid":224,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":1065.9,"mount_type":"tmpfs","total":1073.7,"used":7.9},"/media/frigate/clips":{"free":87471.3,"mount_type":"nfs","total":214748.4,"used":127277.1},"/media/frigate/recordings":{"free":87471.3,"mount_type":"nfs","total":214748.4,"used":127277.1},"/tmp/cache":{"free":985.3,"mount_type":"tmpfs","total":1000.0,"used":14.7}},"temperatures":{},"uptime":18,"version":"0.10.0-bfecee9"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest 4K

**Comment by NickM-27** [comment]
In the config you posted RTMP is disabled

```yaml
cameras:
  driveway_cam:
    rtmp:
      enabled: False

    ffmpeg:
      inputs:
```
