### ISSUE TITLE
[Support]: Stationary/Interval:0 not taken into effect?

### ISSUE THREAD

**Issue by MrSiO** [blakeblackshear/frigate#2870]
### Describe the problem you are having

Hi,
With the deployment of 0.10.0-BFECEE9 and the introduction of stationary object traking, I tried disabling this tracking by adding the following settings:     

```
stationary:
        interval: 0
```

Unfortunately this seems to have no effect as I keep receiving regular updates (MQTT) when a stationary detection is present.
When a car is detected is goes to stationary true, I then keep getting MQTT updates every 60 seconds about that stationnary car even-if my interval was set to zero.

### Version

 0.10.0-BFECEE9

### Frigate config file

```yaml
cameras:                                                                          
  CAM-03:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@198.10.20.8:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    best_image_timeout: 20 
    rtmp:
      enabled: False    
    detect:
      width: 1280
      height: 720
      fps: 5      
      enabled: True                                                               
      max_disappeared: 25
      stationary:          #Optional: Configuration for stationary object tracking
        interval: 0
        threshold: 50
    snapshots:                                                                    
      enabled: True                                                               
      timestamp: True                                                             
      bounding_box: True                                                          
      retain:                                                                     
        default: 3 
    objects:                                                                      
      track:                                                                      
        - person                                                                  
        - dog
        - car
        - bicycle
        - truck  
      filters:
        person:      
          min_score: 0.5
          mask:
            - 0,241,754,61,1280,31,1280,0,0,0
            - 741,654,888,599,985,555,1026,502,1005,434,1008,382,1233,199,1280,65,1280,197,1280,351,1280,720,1037,720,823,720,824,720,674,720,674,720,573,720
            - 938,364,1003,206,921,126,836,267 
        dog:
          min_score: 0.7
          mask:
            - 0,241,754,61,1280,31,1280,0,0,0
        car:
          min_score: 0.5
          mask:
            - 0,241,754,61,1280,31,1280,0,0,0

        bicycle:
          min_score: 0.5
          mask:
            - 0,241,754,61,1280,31,1280,0,0,0

    zones:
      zone_rue:
        coordinates: 0,241,754,61,1280,31,1280,0,0,0
      zone_driveway:
        coordinates: 982,553,586,720,118,720,118,208,591,103
```

### Relevant log output

```shell
The following is the MQTT payload received every 60 seconds when a stationary object is detected:
TOPIC: frigate/events

{
   "before":{
      "id":"1645724740.985654-03hg3k",
      "camera":"CAM-03",
      "frame_time":1645729413.647324,
      "snapshot_time":1645727308.7834,
      "label":"car",
      "top_score":0.8203125,
      "false_positive":false,
      "start_time":1645724740.985654,
      "end_time":null,
      "score":0.57421875,
      "box":[
         75,
         153,
         492,
         672
      ],
      "area":216423,
      "region":[
         0,
         0,
         940,
         940
      ],
      "stationary":true,
      "motionless_count":2468,
      "position_changes":4,
      "current_zones":[
         "zone_driveway"
      ],
      "entered_zones":[
         "zone_driveway"
      ],
      "has_clip":false,
      "has_snapshot":true
   },
   "after":{
      "id":"1645724740.985654-03hg3k",
      "camera":"CAM-03",
      "frame_time":1645729473.970466,
      "snapshot_time":1645727308.7834,
      "label":"car",
      "top_score":0.8203125,
      "false_positive":false,
      "start_time":1645724740.985654,
      "end_time":null,
      "score":0.734375,
      "box":[
         56,
         143,
         515,
         715
      ],
      "area":262548,
      "region":[
         0,
         16,
         704,
         720
      ],
      "stationary":true,
      "motionless_count":2771,
      "position_changes":4,
      "current_zones":[
         "zone_driveway"
      ],
      "entered_zones":[
         "zone_driveway"
      ],
      "has_clip":false,
      "has_snapshot":true
   },
   "type":"update"
}
```

### FFprobe output from your camera

```shell
(see comments below)
```

### Frigate stats

```json
(See comments below)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest

### Any other information that may be helpful

FFprobe and Frigate stats will be provided shortly
