### ISSUE TITLE
Is it possible to get camera audio to play when viewing cameras live in frigate?

### ISSUE THREAD

**Issue by blackburn42330** [blakeblackshear/frigate#2874]
I want to be able to listen to camera audio when viewing a camera live in frigate

This may already be possible?  I deleted the an output arg for recording and my recordings have audio, but can’t figure out how to get it for the live stream.

**Comment by blakeblackshear** [comment]
Audio is not supported in the web UI.

**Comment by blackburn42330** [comment]
Is this something that may be added in the future or not?

**Comment by blakeblackshear** [comment]
It may be added in the future.

**Comment by sevmonster** [comment]
just FYI for anyone visiting this issue, with the latest betas, this is now readily possible thanks to [MSE and RTSP restreaming](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/live).

**Comment by builder555** [comment]
> just FYI for anyone visiting this issue, with the latest betas, this is now readily possible thanks to [MSE and RTSP restreaming](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/live).

I think I've set everything up to re-stream audio, but when I click on the camera to get Live view, it's still video-only, even in the network monitor it shows that it's getting the stream from /jsmpeg endpoint

my config:

```yaml
# removed motion detection for brevity

ui:
  use_experimental: true

mqtt:
  enabled: False

go2rtc:
  streams:
    rtsp_cam:
      - rtsp://10.0.0.50:554/Streaming/channels/101
      - "ffmpeg:rtsp_cam#audio=opus"
  webrtc:
    candidates:
      - 10.0.0.75:8555 # this is IP where frigate is running
      - stun:8555

cameras:
  walkout:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam
          roles:
            - record
    live:
      stream_name: rtsp_cam
```

When I open go2rtc dashboard, it shows webrtc, mse, mp4, mjpeg checked and when i click the stream, it opens the url directly `/live/webrtc/stream.html?src=rtsp_cam` and plays with sound.
