### ISSUE TITLE
[Support]: Question about MQTT messages and best practices 

### ISSUE THREAD

**Issue by Justihar** [blakeblackshear/frigate#2885]
### Describe the problem you are having

I'm pretty new to Frigate so I am trying to understand the behavior of zones, object filtering and how that information comes through in MQTT. 

I am running Frigate in a docker container and although I did end up adding the custom component to HA core, I plan on building my automations in AppDaemon using MQTT directly.

I am doing the typical "notification of car entering driveway" type scenario. I don't particularly care to record or take action on vehicles that are passing by on the street but obviously need to start the process of object detection in that area or at least the entrance of the driveway.

What is the recommended way to allow the zone data to be passed through MQTT but ignore recording?  It seems like if I use the record/snapshot options with required_zones, I still see MQTT data but the "entered_zones" and "required_zones" data is not passed through.

If I am understanding correctly, I should be able to check for an MQTT event where current_zone=["driveway"] and entered_zones=["driveway_entry", "driveway"] but again, don't want to record a vehicle in the driveway or street.

Is there any documentation that explains some of the expected behaviors of MQTT or perhaps some examples of data to look at for various scenarios?

Any suggestions would be helpful, thank you!

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
front_south:
  ffmpeg:
    inputs:
      - path: REDACTED
        roles:
          - detect
          - rtmp
      - path: REDACTED
        roles:
          - record
  detect:
    width: 640
    height: 480
  
  best_image_timeout: 5

  motion:
    mask:
      - 467,206,521,328,640,384,640,0,401,0 # FRONT YARD TREE
      - 133,0,138,92,36,118,0,0 # SOUTH NEIGHBOR TREE

  zones:
    entire_frame:
      coordinates: 640,0,640,480,0,480,0,0
      objects:
        - person
        - dog
    driveway_entry:
      coordinates: 473,382,510,313,276,153,192,167
      objects:
        - car
    front_yard:
      coordinates: 539,319,640,401,640,480,0,480,0,225,204,125
      objects:
        - person
        - dog

  record:
    events:
      required_zones:
        - entire_frame
        - driveway_entry
        - front_yard

  snapshots:
    required_zones:
        - entire_frame
        - driveway_entry
        - front_yard
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
