### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by sygys** [blakeblackshear/frigate#2887]
### Describe the problem you are having

I have a quick question. Everytime i restart the add-on the "person detection switch" of 2 of my 5 cameras go to off in home assistant. I cant seem to find what the problem is because all the cameras are setup the same way in the config, and the person detection of the other 3 arent turned off on a restart.

Its not that big of a deal because i can turn them back on myself after a restart of the add-on. but that still keeps me wondering what causes it.

camera_zijtuin and camera_oprit are the ones which person detect turns off after a restart of the addon.

### Version

3.0

### Frigate config file

```yaml
mqtt:

  host: 192.168.178.51
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  stats_interval: 60



cameras:
  camera_oprit:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.178.71/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
          roles:
            - rtmp
            - detect
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
    detect:
      max_disappeared: 150
      width: 1920
      height: 1080
      fps: 5
    zones:
      eigen_oprit:
        coordinates: 1920,1080,1920,0,536,0,353,311,61,834,0,750,0,1080
        objects:
          - person
    motion:
      mask:
        - 1861,48,1857,99,1448,98,1445,45



  camera_mancave:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.178.89/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
          roles:
            - rtmp
            - detect
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
    detect:
      max_disappeared: 150
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 78
        max_frames:
          objects:
            person: 1000
    motion:
      mask:
        - 1851,108,1851,57,1442,61,1441,100


  camera_over_wit:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.178.65/cam/realmonitor?channel=1&subtype=0&authbasic=xxx
          roles:
            - rtmp
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128


  camera_zijtuin:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.178.38:88/videoMain
          roles:
            - rtmp
            - detect
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
    detect:
      max_disappeared: 150
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 962,282,808,327,1054,393,1280,542,1280,260,1280,0,976,0

  camera_woonkamer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.178.68/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.75
          threshold: 0.75
          min_area: 50000
        dog:
          min_score: 0.75
          threshold: 0.75
          max_area: 40000
      mask:    
        - 1686,285,1665,438,1447,360,1463,220
        - 0,784,0,554,0,319,75,393,133,723,166,847,61,885
        - 1853,38,1862,87,1691,81,1536,74,1537,39
    detect:
      max_disappeared: 400
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 50
        max_frames:
          objects:
            person: 1000
            dog: 1000
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    motion:
      mask:    
        - 1686,285,1665,438,1447,360,1463,220
        - 0,784,0,554,0,319,75,393,133,723,166,847,61,885
        - 1853,38,1862,87,1691,81,1536,74,1537,39
    zones:
      eettafel:
        coordinates: 93,460,204,404,189,279,129,168,0,179,0,299
        objects:
          - person
      tablet_zone:
        coordinates: 270,0,740,0,752,263,667,298,679,478,311,477
        objects:
          - person

  camera_keuken:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.178.93/cam/realmonitor?channel=1&subtype=00&authbasic=xxx
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.80
          threshold: 0.80
          min_area: 50000
        dog:
          min_score: 0.75
          threshold: 0.75
          max_area: 40000
    motion:
      mask:
        - 1531,83,1852,74,1850,35,1535,37
    detect:
      max_disappeared: 400
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 50
        max_frames:
          objects:
            person: 1000
            dog: 1000
    zones:
      tablet_zone:
        coordinates: 1170,0,1178,470,857,638,777,572,767,0
        objects:
          - person
      eettafel:
        coordinates: 1920,1080,1920,698,1632,559,1295,547,1037,673,867,859,889,1080
        objects:
          - person
      keuken:
        coordinates: 378,774,271,662,98,730,0,440,0,0,756,0,781,576
        objects:
          - person
      achterdeur:
        coordinates: 221,1080,455,1080,306,899,163,959
        objects:
          - person

detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
#  cpu3:
#    type: cpu
#  cpu4:
#    type: cpu


  coral:
    type: edgetpu
    device: 'usb:0'
```

### Relevant log output

```shell
dont think this is relevant
```

### FFprobe output from your camera

```shell
dont think this is relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua imou D22P (i think) and the Foscam G4P
