### ISSUE TITLE
[Support]: Fatal Python error: Bus error

### ISSUE THREAD

**Issue by MatheusGelinskiPires** [blakeblackshear/frigate#2888]
### Describe the problem you are having

Hello folks,
I am facing the folliwing issue:

[2022-03-01 21:35:23] peewee                         DEBUG   : ('INSERT INTO "recordings" ("id", "camera", "path", "start_time", "end_time", "duration") VALUES (?, ?, ?, ?, ?, ?)', ['1646181312.0-l8zkdp', 'cam01', '/media/frigate/recordings/2022-03/01/21/cam01/35.12.mp4', 1646181312.0, 1646181320.998, 8.998])
Fatal Python error: Bus error

Thread 0x00007fb38a0e6700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fb3898e5700 (most recent call first):
  File "/opt/frigate/frigate/video.py", line 150 in capture_frames
  File "/opt/frigate/frigate/video.py", line 290 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb3802c3700 (most recent call first):
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 261 in wait
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 349 in wait
  File "/opt/frigate/frigate/video.py", line 215 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb38a8e7700 (most recent call first):
  File "/opt/frigate/frigate/log.py", line 65 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb390ddb740 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
  File "/usr/lib/python3.8/threading.py", line 1011 in join
  File "/opt/frigate/frigate/video.py", line 321 in capture_camera
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
  File "/opt/frigate/frigate/app.py", line 330 in start
  File "/opt/frigate/frigate/__main__.py", line 17 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.110
  port: 1883
  user: frigate
  password: {mypwd}
  topic_prefix: frigate
  stats_interval: 60

database:
  path: /db/frigate.db

logger:
  default: debug

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

rtmp:
  enabled: True

cameras:
  cam01:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:{mypwd}@{myipcam01}:554/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15
    motion:
      mask:
        - 0,68,496,64,497,0,0,0
  cam02:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:{mypwd}@{myipcam02}:554/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15
    objects:
      track:
        - person
        - car
        - motorcycle
    motion:
      mask:
        - 0,68,496,64,497,0,0,0
  cam03:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:{mypwd}@{myipcam03}:554/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15
    motion:
      mask:
        - 0,68,496,64,497,0,0,0
  cam04:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:{mypwd}@{myipcam04}:554/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15
    motion:
      mask:
        - 0,68,496,64,497,0,0,0


record:
  enabled: True
  retain_days: 7
  events:
    retain:
      default: 10
      objects:
        person: 15

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
```

### Relevant log output

```shell
[2022-03-01 21:35:23] peewee                         DEBUG   : ('INSERT INTO "recordings" ("id", "camera", "path", "start_time", "end_time", "duration") VALUES (?, ?, ?, ?, ?, ?)', ['1646181312.0-l8zkdp', 'cam01', '/media/frigate/recordings/2022-03/01/21/cam01/35.12.mp4', 1646181312.0, 1646181320.998, 8.998])
Fatal Python error: Bus error

Thread 0x00007fb38a0e6700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 227 in _feed
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fb3898e5700 (most recent call first):
  File "/opt/frigate/frigate/video.py", line 150 in capture_frames
  File "/opt/frigate/frigate/video.py", line 290 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb3802c3700 (most recent call first):
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 261 in wait
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 349 in wait
  File "/opt/frigate/frigate/video.py", line 215 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb38a8e7700 (most recent call first):
  File "/opt/frigate/frigate/log.py", line 65 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb390ddb740 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1027 in _wait_for_tstate_lock
  File "/usr/lib/python3.8/threading.py", line 1011 in join
  File "/opt/frigate/frigate/video.py", line 321 in capture_camera
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/app.py", line 255 in start_camera_capture_processes
  File "/opt/frigate/frigate/app.py", line 330 in start
  File "/opt/frigate/frigate/__main__.py", line 17 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
```

### Frigate stats

```json
{"cam01":{"camera_fps":15.0,"capture_pid":238,"detection_fps":0.0,"pid":228,"process_fps":15.0,"skipped_fps":0.0},"cam02":{"camera_fps":14.5,"capture_pid":240,"detection_fps":0.0,"pid":232,"process_fps":14.5,"skipped_fps":0.0},"cam03":{"camera_fps":15.2,"capture_pid":247,"detection_fps":0.0,"pid":234,"process_fps":15.2,"skipped_fps":0.0},"cam04":{"camera_fps":0.0,"capture_pid":252,"detection_fps":0.0,"pid":236,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":24.56,"pid":216},"cpu2":{"detection_start":0.0,"inference_speed":29.36,"pid":218},"cpu3":{"detection_start":0.0,"inference_speed":10.0,"pid":219},"cpu4":{"detection_start":0.0,"inference_speed":10.0,"pid":220}},"service":{"storage":{"/dev/shm":{"free":56.1,"mount_type":"tmpfs","total":67.1,"used":11.0},"/media/frigate/clips":{"free":525390.5,"mount_type":"ext4","total":1476623.7,"used":876201.4},"/media/frigate/recordings":{"free":525390.5,"mount_type":"ext4","total":1476623.7,"used":876201.4},"/tmp/cache":{"free":4146.6,"mount_type":"tmpfs","total":4146.6,"used":0.0}},"uptime":453,"version":"0.9.4-26ae608"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Digoo DG-W10
