### ISSUE TITLE
Allow to configure ffmpeg args for jsmpeg stream

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#2911]
## **Describe what you are trying to accomplish and why in non technical terms**
I want to be able to customize the JSMPEG FFMPEG args, so that I can:

- Enable audio, by using `-c:a mp2` for example
- Try to tweak the parameters to fix https://github.com/dermotduffy/frigate-hass-card/issues/388 as mentioned in https://github.com/phoboslab/jsmpeg/issues/268#issuecomment-474653681

## **Describe the solution you'd like**
To be able to tweak the FFMPEG args used to encode the JSMPEG stream, the same way I can tweak the args for RTMP, for example.

## **Describe alternatives you've considered**
Tweak args in source code and rebuild from scratch, but this is an extremely difficult process considering the simple task of enabling audio (for example).

## **Additional context**

https://github.com/blakeblackshear/frigate/blob/ebdfbfe96c1c8b9fe249f3c147c9bdb98b7809f9/frigate/output.py#L32

**Comment by blakeblackshear** [comment]
It's not that simple. The live view is currently encoding raw frames at the end of the processing pipeline for frigate. Audio data isn't maintained in that processing pipeline, so even if you added those parameters there isn't an audio stream to encode.

**Comment by felipecrs** [comment]
Got it. In that case, we may think about handling audio in jsmpeg in the future.

But I believe the option to configure the args would still be useful for other cases, like the one I mentioned about trying to fix `Uncaught RuntimeError: memory access out of bounds`.

**Comment by felipecrs** [comment]
Well, talking specifically about that error, the only "missing" ffmpeg args are the framerate and the bitrate, as [mentioned in the jsmpeg readme](https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg).

```console
-b:v 1500k -r 30
```

Without trying I can't tell, but I wonder if they could really help.

**Comment by blakeblackshear** [comment]
I doubt it. Setting `-r` will just fix the output frame rate and duplicate frames. `Setting b:v` is the equivalent of `-q` for defining the bitrate. You could try setting a higher quality number in your `live` settings.

**Comment by felipecrs** [comment]
Thank you. I just realized that I had sub-optimal configurations for all my cameras:

```yaml
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
```

Since all of them have a `detector.height` of less than 720. I'll check whether this helps or not. Thank you.
