### ISSUE TITLE
[Support]: Stationary being ignored

### ISSUE THREAD

**Issue by Hoosier-IT** [blakeblackshear/frigate#2921]
### Describe the problem you are having

Despite having added stationary to the config. It appears to be ignored and I now have dozens of clips of my stationary car. It's only moved once a week or so.

Cats walking by/near,  birds, 10 ft away, lens flairs from passing car headlights, IR light on rain, IR lights coming on. All seem to trigger, and then the stationary object is detected as having movement?

I have videos if needed.

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.254
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: pass
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  EXAMPLE_VAR: value

birdseye:
  enabled: True
  width: 640
  height: 480
  quality: 8
  mode: objects

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv

detect:
  enabled: True
  width: 640
  height: 480
  fps: 10
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      objects:
        car: 1000

objects:
  track:
    - person
    - car
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
    required_zones: []
    retain:
      default: 7
      mode: active_objects
      objects:
        person: 30

snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  crop: True
  #height: 175
  required_zones: []
  retain:
    default: 7
    objects:
      person: 30

rtmp:
  enabled: True

live:
  height: 640
  quality: 8

cameras:
  North:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.40:554/cam/realmonitor?channel=1&subtype=1&unicast=True&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.40:554/cam/realmonitor?channel=1&subtype=0&unicast=True&proto=Onvif
          roles:
            - record
    motion:
      threshold: 25
      contour_area: 100
      delta_alpha: 0.2
      frame_alpha: 0.2
      frame_height: 180
      mask: 
        - 0,0,640,0,640,115,493,60,304,40,194,49,106,58,0,145
    best_image_timeout: 60

    zones:
      easement:
        coordinates: 0,268,0,161,110,59,188,47
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      driveway:
        coordinates: 0,268,0,480,287,480,307,40,194,47
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      yard:
        coordinates: 534,73,640,122,640,276,609,245,595,232,568,223,460,214,295,214,307,42
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      walkway:
        coordinates: 463,215,570,220,600,242,613,259,640,282,640,480,294,480,298,210
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.156:554/cam/realmonitor?channel=1&subtype=1&unicast=True&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.156:554/cam/realmonitor?channel=1&subtype=0&unicast=True&proto=Onvif
          roles:
            - record
    motion:
      threshold: 25
      contour_area: 100
      delta_alpha: 0.2
      frame_alpha: 0.2
      frame_height: 180
      mask: 
        - 499,181,640,0,0,0,0,0,0,0,0,299,68,299,143,301,166,303,248,307,500,299
    best_image_timeout: 60
    zones:
      porch:
        coordinates: 190,367,257,371,340,371,369,375,387,385,401,398,494,384,640,480,0,480,0,367,90,348
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      doorbell_yard:
        coordinates: 493,313,240,310,92,347,216,365,318,370,363,371,388,382,490,373
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
      doorbell_driveway:
        coordinates: 168,304,0,325,0,369,249,307
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 480
      quality: 70
      required_zones: []
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
