### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by bartomnisound** [blakeblackshear/frigate#2924]
### Describe the problem you are having

I try to run frigate in docker on a synology NAS but I can't the container to boot up.
I've check the RSTP stream URL with VLC and there the streams opens.
Below a screenshot of the error I'm getting in the docker log.

### Version

0.1.1

### Frigate config file

```yaml
port: 5500  

mqtt:
  host: 192.168.18.33
  port: 1883
  user: user
  password: pass

detectors:
  cpu1:
    type: cpu
    num_threads: 3

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug


cameras:
  oprit: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.18.60:88/videoMain
          roles:
            - detect
     
      detect:
        width: 1920
        height: 1080
```

### Relevant log output

```shell
Traceback (most recent call last):
stdout
19:40:11
  File "detect_objects.py", line 90, in <module>
stdout
19:40:11
    main()
stdout
19:40:11
  File "detect_objects.py", line 44, in main
stdout
19:40:11
    cameras[name] = Camera(name, config, prepped_frame_queue, client, MQTT_TOPIC_PREFIX)
stdout
19:40:11
  File "/opt/frigate/frigate/video.py", line 117, in __init__
stdout
19:40:11
    self.rtsp_url = get_rtsp_url(self.config['rtsp'])
stdout
19:40:11
KeyError: 'rtsp'
```

### FFprobe output from your camera

```shell
?
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Foscam D2EP

**Comment by NickM-27** [comment]
Your `detect` is indented too much. It is in line with inputs but it should be in line with ffmpeg.

```yaml
port: 5500  

mqtt:
  host: 192.168.18.33
  port: 1883
  user: user
  password: pass

detectors:
  cpu1:
    type: cpu
    num_threads: 3

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug


cameras:
  oprit: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.18.60:88/videoMain
          roles:
            - detect
     
    detect:
      width: 1920
      height: 1080
```
