### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by Yashaayan** [blakeblackshear/frigate#2925]
### Describe the problem you are having

I'm trying to start Frigate NVR within Home Assistant and I'm coming across this error: 

Currently running the most up to date Home Assistant on a Oracle VM VirtualBox. 
Setup a DIY security camera using the Logitech Brio with motionEye. Using the livefeed URL generated from motionEye within Home Assistant. 

### Version

3

### Frigate config file

```yaml
mqtt: 
  host: 10.2.11.153
  user: mqtt-user
  password: pass

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: 192.168.1.114:8081
          roles:
            - detect
            - clips
    width: 640
    height: 360
    fps: 5
    objects: 
      track: 
        - person

detectors:
  cpu1:
    type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-03-08 12:59:28] frigate.app                    INFO    : Starting Frigate (0.10.0-bfecee9)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
3 validation errors for FrigateConfig
cameras -> front_door -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> front_door -> height
  extra fields not permitted (type=value_error.extra)
cameras -> front_door -> width
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 903, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for FrigateConfig
cameras -> front_door -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> front_door -> height
  extra fields not permitted (type=value_error.extra)
cameras -> front_door -> width
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
not sure what that is
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

logitech brio

**Comment by NickM-27** [comment]
You have these parts defined without their header groups...


```yaml
width: 640
    height: 360
    fps: 5
    objects: 
      track: 
        - person
```

it needs to be 

```yaml
mqtt: 
  host: 10.2.11.153
  user: mqtt-user
  password: pass

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: 192.168.1.114:8081
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
      objects: 
        track: 
          - person

detectors:
  cpu1:
    type: cpu
```
