### ISSUE TITLE
[Issue]: Camera object mask seems to have no effect

### ISSUE THREAD

**Issue by mspinolo** [blakeblackshear/frigate#2928]
### Describe the problem you are having

Defining an object mask within a camera doesn't seem to have any effect.

Even after defining them object is tracked in the region.
Double checked with motion mask and this works fine.

### Version

0.10.0

### Frigate config file

```yaml
cameras:


  corte:
    ffmpeg:
      input_args :
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
      inputs:

        - path: SECRET
          roles:
            - record
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1440
      fps: 5
    motion:
      mask:
        - 1537,473,1396,465,1406,880,1537,882 # this works fine
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 1500
          min_score: 0.5
          threshold: 0.7
          mask:
            - 1411,1018,1573,1016,1556,453,1382,446 # NO EFFECT
        cat:
          min_score: 0.5
          threshold: 0.7
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua, can't remember the name

**Comment by mathmaniac43** [comment]
@NickM-27 I believe that I am having the same kind of problem as @mspinolo, and I have tried both `object masks` and `required_zones`. Is there an easy way to capture an event/video with the debugging information embedded into it, like the debug view in the web UI? If so I should be able to get an example video (raw and with debug info) from my camera, along with my config, this evening.

**Comment by NickM-27** [comment]
Screen recording is the only option I can think of, that would be the most helpful option.

**Comment by blakeblackshear** [comment]
If frigate has recordings for that time period, you can add a "test" camera to your config that will replay and reanalyze that video so you can watch it in debug view. This is what I do for [development](https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing).

**Comment by NickM-27** [comment]
> If frigate has recordings for that time period, you can add a "test" camera to your config that will replay and reanalyze that video so you can watch it in debug view. This is what I do for [development](https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing).

Oh wow, that is awesome!

**Comment by mspinolo** [comment]
Hi,

sorry to be late in replying but I was far from home.
So this is a snapshot where I get the plan in the red box recognized as a person:
![snapshot-1646995347 975456-fx01cr](https://user-images.githubusercontent.com/43354538/157871250-2d2bd324-0876-4515-a0d0-78826da6a53a.jpg)

I created both a motion and objects mask (see my first post) to cover it:

![grab 2022-03-11 alle 14 01 13](https://user-images.githubusercontent.com/43354538/157871356-5949493e-befb-4d19-b9a7-bd566e33cd17.png)

but still I get it detected as a person

![grab 2022-03-11 alle 14 02 08](https://user-images.githubusercontent.com/43354538/157871475-d9beb113-277c-4a9c-8fb1-80988f6bf6eb.png)

likely it is me missing something but I spent quite a lot of time on it (admittedly not being a pro-user) and can't find a solution

Hope this helps.
I didn't try `required_zones`: I see your point but given I would like to remove an area in the center of the image...I guess it will be quite cumbersome to use required zone instead of masking?

**Comment by NickM-27** [comment]
@mspinolo This doesn't show the object mask but assuming it is the same as the motion mask then that won't work... again the object mask just needs to overlap the bottom center of the bounding box and it looks like that may be the only part that isn't covered. 

Also, motion masks only block that part of the scene from running motion detection but won't stop it from being detected so unless that plant moves then the motion mask won't do anything.

**Comment by blakeblackshear** [comment]
Also, that plant might be big enough that you could use a `max_area` filter to mark anything that large as a false positive. Not sure how large person objects can be when close to the camera.

**Comment by mspinolo** [comment]
I see, I will try to enlarge the mask box then.
Motion box and object one I set are exactly the same, hence above image is valid.

I was wondering if for next release wouldn’t make sense to have a logic such that “if the object box is covered by X% by object filter mask do not detect it”
Not sure if will be like that for everyone but in my case will be much more robust

**Comment by NickM-27** [comment]
@mspinolo 

> I see, I will try to enlarge the mask box then.

You don't need to enlarge it, just put a small box on the bottom area where the bounding box is.

> I was wondering if for next release wouldn’t make sense to have a logic such that “if the object box is covered by X% by object filter mask do not detect it”

That logic doesn't work... covered by x% would greatly affect how it behaves based on the height, angle, field of view, etc. of the camera. Using the bottom center of the bounding box makes it predictable no matter the camera / positioning. It may not be as intuitive but it is very well explained all over the docs and works well once masks / zones are designed for this. 

Take my doorbell camera for example. If the % covered logic was used and I wanted to block off people walking on the sidewalk then I would need to create a big wall along the sidewalk. Then if I walked out the front door there would still be a large % of my body covered by that mask despite the fact that I only want to block people walking on the sidewalk.

With the bottom center logic it is very predictable and precise to only block what I want to block and nothing else.

![image](https://user-images.githubusercontent.com/14866235/157890339-8b0e10e7-46d6-458e-8012-1e3d3a2881d4.png)

**Comment by NickM-27** [comment]
@blakeblackshear I wonder if having a specific note about the bottom center rule in the mask editor inside frigate would be helpful?

**Comment by mathmaniac43** [comment]
OK, finally got around to testing with a recording. Here is what I am seeing, and my config is below.

The behavior that I am seeing is, when cars drive up and down the road in front of my house, sometimes their headlights illuminate the car in my driveway and make Frigate think it's moving. So, I have attempted to set up a zone comprising the center of my driveway (excluding where the cars tend to park on the right side) as well as mask motion outside of that zone. That way, I should only get events triggered when a vehicle actually moves through the center of the driveway.

Just uploading a screenshot for now, let me know if having this clip would be helpful.

![Screenshot 2022-03-11 at 10-34-04 Frigate](https://user-images.githubusercontent.com/918497/157898461-68fa2010-013a-43ee-a7f1-0106b063792e.png)

```yaml
cameras:
  driveway_test:
    ffmpeg:
      inputs:
        - path: /test/clip_driveway_1646994554.658506-1646994612.678617.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    motion:
      mask:
        - 0,270,800,270,1280,800,1280,0,0,0 # Ignore the road and parking area
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - cat
        - dog
    zones:
      driveway.no_road:
        coordinates: 0,270,800,270,1280,800,1280,960,0,960 # Capture everything under the road and left of the parking area
    record:
      events:
        required_zones:
          - driveway.no_road
    snapshots:
      required_zones:
        - driveway.no_road
    mqtt:
```
