### ISSUE TITLE
[Support]: BlockingIOError [Errno 11] Resource Temporarily unavailable: '/media/frigate/records'

### ISSUE THREAD

**Issue by tylerwmarrs** [blakeblackshear/frigate#2943]
### Describe the problem you are having

Every now and then frigate will stop writing recordings to disk. The volume it is writing to is a NAS mounted on the host system. When I restart the frigate docker container, it starts to work again. See the stack trace below.

### Version

0.11.0-3de1948

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: 192.168.4.11
  user: mqtt
  password: redacted

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - dog
    - cat

record:
  enabled: True
  events:
    retain:
      default: 180

live:
  quality: 3

snapshots:
  enabled: True

cameras:
  front_left:
    ffmpeg:
      inputs:
        - path: rtsp://admin:redacted@192.168.5.10:554
          roles:
            - detect
            - rtmp
    detect:
      width: 3840
      height: 2160
    motion:
      mask:
        - 2595,470,2824,462,2723,332,2603,359
        - 3688,87,3688,141,2992,139,2989,84
    objects:
      filters:
        person:
          mask:
            - 2566,307,2762,298,2768,476,2572,485
            - 2536,399,2544,508,2443,508,2438,416
            - 1794,130,1799,196,1709,204,1704,141
            - 1889,130,1840,133,1883,174,1853,179
    zones:
      driveway:
        coordinates: 0,1223,0,2160,2015,2160,2069,964,1911,836,1655,735,1387,729,1524,542,640,676,613,738,607,685
      road:
        coordinates: 720,655,857,631,1054,592,1185,577,1453,536,1530,539,1676,503,1855,488,1977,476,2143,464,2295,449,2453,435,2637,426,2724,432,2881,414,3084,417,3245,420,3382,423,3521,420,3655,429,3777,449,3840,444,3840,295,3513,259,3325,235,3027,232,2834,232,2417,238,2286,256,2072,268,1866,286,1715,313,1569,319,1369,357,1179,381,959,435,723,485,545,533,452,569,271,607,182,622,0,637,0,816
      yard_left:
        coordinates: 500,813,0,1217,0,911
      yard_right:
        coordinates: 2012,2160,2060,1170,2048,961,1980,872,1908,833,1828,798,1750,762,1667,738,1581,729,1494,729,1357,729,1402,688,1694,643,1878,622,2066,607,2304,586,2658,566,2813,557,3140,542,3319,536,3602,530,3840,542,3840,2160
      sidewalk:
        coordinates: 0,917,188,869,256,860,321,839,387,833,452,831,512,801,634,789,759,768,878,756,1095,720,1268,700,1411,682,2090,601,2349,575,2509,572,2703,557,2804,557,2998,539,3203,536,3340,533,3840,536,3840,491,3527,479,3015,488,2572,506,2349,524,2006,554,1462,613,604,747,363,795,259,819,137,839,0,866
    record:
      enabled: True
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/frigate/frigate/http.py", line 351, in stats
    stats = stats_snapshot(current_app.stats_tracking)
  File "/opt/frigate/frigate/stats.py", line 91, in stats_snapshot
    storage_stats = shutil.disk_usage(path)
  File "/usr/lib/python3.9/shutil.py", line 1262, in disk_usage
    st = os.statvfs(path)
BlockingIOError: [Errno 11] Resource temporarily unavailable: '/media/frigate/recordings'
```

### FFprobe output from your camera

```shell
root@59ee6b3b1411:/opt/frigate# ffprobe rtsp://admin:redacted@192.168.5.10:554
ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:redacted@192.168.5.10:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.047000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 20 fps, 100 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":80.75,"pid":240}},"front_left":{"camera_fps":5.0,"capture_pid":248,"detection_fps":0.0,"pid":246,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":51526.6,"mount_type":"tmpfs","total":51539.6,"used":13.0},"/media/frigate/clips":{"free":8734464.7,"mount_type":"cifs","total":8795656.6,"used":61191.9},"/media/frigate/recordings":{"free":8734464.7,"mount_type":"cifs","total":8795656.6,"used":61191.9},"/tmp/cache":{"free":970.3,"mount_type":"tmpfs","total":1000.0,"used":29.7}},"temperatures":{},"uptime":1607,"version":"0.11.0-3de1948"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2669EW-AI
