### ISSUE TITLE
[Support]: "Unable to read frames from ffmpeg process" After updating to 3.1

### ISSUE THREAD

**Issue by CZonin** [blakeblackshear/frigate#2947]
### Describe the problem you are having

My Amcrest AD410 that was previously working in Frigate has stopped working since updating to 3.1. I'm now just seeing a green image in the Frigate UI. I've added logs from what I'm seeing on my end.

### Version

3.1

### Frigate config file

```yaml
# frigate.yml
mqtt:
  host: xxx.xxx.xx.xx
  port: xxxx
  user: removed
  password: removed

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  events:
    max_seconds: 120
    pre_capture: 2
    post_capture: 2
    retain:
      default: 2
      mode: motion

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 2

birdseye:
  enabled: false

detectors: 
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

cameras:
  front_doorbell:
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        person:
          min_score: 0.8
          min_area: 20000
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:xxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 2352,623,2385,1009,2303,1619,2560,1812,2560,0,1880,0,2171,102
        - 1804,0,299,0,347,411,1110,277,1702,287
    zones:
      my_driveway:
        coordinates: 2162,1371,2028,1337,2011,1322,2011,1252,2038,1187,2083,1159,2176,1114,2372,1091,2335,1378
        objects:
          - person
          - motorcycle
      neighbor_driveway_1:
        coordinates: 1734,1187,1677,1133,1621,1072,1494,1075,1517,1125,1568,1196
        objects:
          - person
          - motorcycle
      neighbor_driveway_2:
        coordinates: 2052,1136,1949,1063,1891,1057,1767,1052,1694,1117,1897,1179
        objects:
          - person
          - motorcycle
    mqtt:
      quality: 100
      bounding_box: false
      height: 1080
  den:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:xxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 0,0,1920,0,1920,190,1515,99,1162,62,659,59,309,87,0,146
        - 0,656,0,1080,149,1080,70,895
    zones:
      office_entry:
        coordinates: 0,640,114,996,576,996,493,98,0,192
        objects:
          - person
    mqtt:
      quality: 100
      bounding_box: false
      height: 1080
  backyard:
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.8
        cat:
          min_score: 0.8
        dog:
          min_score: 0.8
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:xxx/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 1920,0,1829,90,1784,124,1717,211,1435,140,1057,120,844,129,653,162,400,203,0,493,0,323,0,0
    mqtt:
      quality: 100
      bounding_box: false
      height: 1080
```

### Relevant log output

```shell
[2022-03-11 09:02:41] frigate.video                  ERROR   : front_doorbell: Unable to read frames from ffmpeg process.
[2022-03-11 09:02:41] frigate.video                  ERROR   : front_doorbell: ffmpeg process is not running. exiting capture thread...
[2022-03-11 09:02:48] watchdog.front_doorbell        ERROR   : Ffmpeg process crashed unexpectedly for front_doorbell.
[2022-03-11 09:02:48] watchdog.front_doorbell        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest AD410
