### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by alexrusso51** [blakeblackshear/frigate#2950]
### Describe the problem you are having

Clips start recording 30s too late. This is only happening on the Reolink Duo PoE device (both cameras). I have 3 other Reolink cameras (different models) working just fine.

The Snapshot for the event shows two timestamps (Reolink and Frigate). The Reolink one is at the correct time for the event but the Frigate one is 30s later. When the recording starts it uses the Frigate time which is already 30s after the event, thus missing the event in the recorded clip.
<img width="1115" alt="Screen Shot 2022-03-11 at 4 17 53 PM" src="https://user-images.githubusercontent.com/74624558/157967987-540979ae-dc28-424e-92e7-4ae934544f8e.png">
 

### Version

0.10.0-DB1255A

### Frigate config file

```yaml
mqtt:
  host: XXX.XXX.XXX.XXX
  user: XXX
  password: XXX

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  Cam1:
    ffmpeg:
#      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
#        - -rw_timeout
#        - "5000000"
      inputs:
        - path: rtsp://usr:pw@ip:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://usr:pw@ip:554/h264Preview_01_main
          roles:
            - record
#            - detect
    detect: 
#      width: 2560
#      height: 1440
#      width: 2560
#      height: 1440
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - dog
        - car
#        - bicycle
    zones:
      zone1:
        coordinates: 473,0,640,0,424,66,390,43
        objects: 
          - person
          - dog
          - car
      zone2:
        coordinates: 74,360,640,360,640,0,424,66
        objects:
          - person
          - dog
      zone3:
        coordinates: 424,66,390,43,181,124,0,265,0,360,74,360
        objects:
          - person
          - dog  
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      required_zones:
        - zone1
        - zone2
        - zone3
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        required_zones:
          - zone1
          - zone2
          - zone3
        retain:
          default: 5
          mode: active_objects

  Cam2:
    ffmpeg:
#      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
#        - -rw_timeout
#        - "5000000"
      inputs:
        - path: rtsp://usr:pw@ip:554/h264Preview_02_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://usr:pw@ip:554/h264Preview_02_main
          roles:
            - record
#            - detect
    detect: 
#      width: 2560
#      height: 1920
#      width: 1280
#      height: 720
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - dog
#        - car
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects

  Cam3:
    ffmpeg:
#      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
#        - -rw_timeout
#        - "5000000"
      inputs:
        - path: rtsp://usr:pw@ip:554/h264Preview_01_sub
          roles:
#            - detect
            - rtmp
        - path: rtsp://usr:pw@ip:554/h264Preview_01_main
          roles:
            - record
            - detect
    detect: 
#      width: 2560
#      height: 1920
      width: 1280
      height: 960
#      width: 640
#      height: 480
      fps: 7
    objects:
      track:
        - person
        - dog
#        - bicycle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
                    
  Cam4:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
#        - -rw_timeout
#        - "5000000"
      inputs:
        - path: rtsp://usr:pw@ip:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://usr:pw@ip:554/h264Preview_01_main
          roles:
#            - detect
            - record
    detect: 
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - dog
#        - bicycle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        retain:
          default: 5
          mode: active_objects
          
  Cam5:
    ffmpeg:
      inputs:
        - path: rtsp://usr:pw@ip:554/live0
          roles:
            - detect
    detect:                      
      width: 1920 
      height: 1080
      fps: 5 
    objects:
      track:
        #- dog
        - bicycle
        #- person
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 10

detectors:
  coral:
    type: edgetpu
    device: pci:0
```

### Relevant log output

```shell
No relevant events in logger
```

### FFprobe output from your camera

```shell
Sub_stream:
 title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: -20.880844, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 640x360, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp

Main_Stream:
 Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.036438, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 2560x1440, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp

Also get this from main stream (somethiomes just the two lines, sometimes the two lines repeated many times over):
[rtsp @ 0x5618d84b1b80] max delay reached. need to consume packet
[rtsp @ 0x5618d84b1b80] RTP: missed 1 packets
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink Duo

### Any other information that may be helpful

Able to view hi-res stream with a viewer like VLC with no problem. However, when viewing recordings made from hi-res stream (frigate recordings as well as recordings from AgentDVR) there is green streaking in the bottom of the video which clears up when an object moves through it. There are also horizontal scan lines running down the video
<img width="1105" alt="Screen Shot 2022-03-11 at 5 55 04 PM" src="https://user-images.githubusercontent.com/74624558/157985453-56cb1c58-d4ee-4528-890f-4d9839720c30.png">
<img width="1100" alt="Screen Shot 2022-03-11 at 5 54 50 PM" src="https://user-images.githubusercontent.com/74624558/157985518-1eb8ce69-34c7-45ee-acaa-4c98e7459e45.png">
