### ISSUE TITLE
[Support]: Stop Frigate considering toboggan as a person

### ISSUE THREAD

**Issue by koldogut** [blakeblackshear/frigate#2958]
### Describe the problem you are having

Due to camera position and image characteristics adding a zone to be excluded in the sledge/toboggan area is not a choice and I wonder if there is any way to tell Frigate or tensorflow model this is not a person. I've read and understood the way to avoid static objects to be considered as positives but i'd like to make it easier if possible (retraining the model or similar).
![tobogan](https://user-images.githubusercontent.com/43078880/158056344-77bd45c5-8fa2-4458-9068-a437abeac23a.jpg)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.***
  user: *****
  password: *****

detectors:
    coral:
      type: edgetpu
      device: pci

detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True

motion:
  threshold: 15

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

objects:
  track:
    - person
  filters:
      person:
        min_score: 0.65
        threshold: 0.75
      cat:
        min_score: 0.5
        threshold: 0.7
      bird:
        min_score: 0.5
        threshold: 0.7

snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      #height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

cameras:
  jardin_este:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/v8oaLpQGH0581S4Z
          roles:
            - detect
            - rtmp
    
  jardin_norte:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/VdXYPw03vwSqfTcT
          roles:
            - detect
            - rtmp
  pta_principal:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/GLoF3a4tIC7Gvk4A
          roles:
            - detect
            - rtmp
    motion:
      mask:
        #- 1740,0,1702,214,1481,171,1467,205,1321,170,1327,121,1241,99,1255,0
        - 1740,0,1672,278,1469,233,1210,178,1220,0
       
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      
  entrada:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/VVajnSwa8HGee37U
          roles:
            - detect
            - rtmp
    motion:
      mask:
        #- 0,0,0,621,50,711,138,664,191,749,331,641,302,569,427,498,987,195,1174,103,1320,40,1416,0
        - 0,0,0,711,122,844,451,609,1007,238,1181,145,1326,61,1452,0
    zones:
      patio:
          coordinates: 1920,1080,1920,0,1457,0,0,927,0,1080,177,1080
    record:
      events:
        required_zones:
          - patio
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  sotano:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/hs1R8fuM09AZ33VL
          roles:
            - detect
            - rtmp
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      
  terraza:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/4ODS7cV8RgRfpHXE
          roles:
            - detect
            - rtmp
    motion:
      mask:
        #- 1272,375,1254,334,1156,333,1137,351,1014,346,799,332,269,353,267,328,510,96,814,0,1920,0,1920,559
        - 1258,404,1123,386,1008,366,799,362,273,382,267,328,510,96,814,0,1920,0,1920,604
    zones:
      piscina:
        coordinates: 1139,743,1143,855,1338,1011,1712,891,1724,773,1514,669
      jardin:
        coordinates: 0,1080,1920,1080,1920,685,1376,490,1180,441,988,403,841,393,276,426
    record:
      events:
        required_zones:
          - jardin
          
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
      
  garaje:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/ISH8Tg1G7eLLVN1G
          roles:
            - detect
            - rtmp
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  corner:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/4RimIAgveXY3PEhd?enableSrtp
          roles:
            - detect
            - rtmp
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
```

### Relevant log output

```shell
No relevant logs apply
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://192.168.1.1:7447/ISH8Tg1G7eLLVN1G':
  Metadata:
    title           : B4FBE49E647D_0
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac, 48000 Hz, mono, fltp
    Stream #0:1: Video: h264, yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 15 fps, 25 tbr, 90k tbn, 30 tbc
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Ubiquiti G3-Plex
