### ISSUE TITLE
[Support]: Object still being detected after disappearing

### ISSUE THREAD

**Issue by joe248** [blakeblackshear/frigate#2965]
### Describe the problem you are having

My car usually sits in the driveway and is correctly detected as a stationary object by Frigate.  However, I noticed this morning that after backing out of the driveway and leaving, the car is still being detected as present.

Here is the car after backing out of the driveway and just before driving away:

<img width="737" alt="Screen Shot 2022-03-14 at 9 43 47 AM" src="https://user-images.githubusercontent.com/24720046/158212956-7c44501c-10a8-4c11-8829-1d89d9b56124.png">

Here is what Frigate debug showed right after and continues to show hours later:

<img width="723" alt="Screen Shot 2022-03-14 at 9 42 51 AM" src="https://user-images.githubusercontent.com/24720046/158213149-34115eb6-b551-4940-97a0-33db6e2b734d.png">

I have the street masked off, if that's relevant:

<img width="722" alt="Screen Shot 2022-03-14 at 9 53 20 AM" src="https://user-images.githubusercontent.com/24720046/158213260-f885cbc7-b518-4651-8aff-446eecb325b8.png">

The car is correctly not being counted as an object in my driveway zone, but is still being counted by the Front camera as being present.

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.135

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car

detect:
  stationary:
    max_frames:
      objects:
        person: 300

record:
  enabled: True
  retain:
    days: 0
  events:
    max_seconds: 300
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: True

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

cameras:
  Front:
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_RTSP_PASSWORD}/cam/realmonitor?channel=1&subtype=1'
          roles:
            - detect
    detect:
      width: 704
      height: 480
    motion:
      contour_area: 125
      mask:
        # timestamp
        - 687,20,686,42,514,40,515,19
        # neighbors and road
        - 35,132,76,141,219,93,514,103,703,150,704,68,704,0,527,0,195,0,82,0
    zones:
      driveway:
        coordinates: 570,480,96,480,45,302,494,114,644,146
    record:
      events:
        required_zones:
          - driveway
    snapshots:
      required_zones:
        - driveway
```

### Relevant log output

```shell
Nothing relevant in the standard log output.  If I should turn on debug logging, let me know.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
