### ISSUE TITLE
[Support]: scaling with hardware support

### ISSUE THREAD

**Issue by luzik** [blakeblackshear/frigate#2996]
### Describe the problem you are having

I want to move from software video scaling in detector part into `-vf 'scale_vaapi=w=1280:h=720,hwdownload,format=nv12' -f rawvideo -pix_fmt yuv420p -an -y`. While I can add this to output_args->detect I don't know how to remove -video_size 1280x720.

I tried 
```
    detect:
      width:
      height:
```

but it did not run

```
frigate                   | cameras -> wejscie -> detect -> height
frigate                   |   none is not an allowed value (type=type_error.none.not_allowed)
frigate                   | cameras -> wejscie -> detect -> width
frigate                   |   none is not an allowed value (type=type_error.none.not_allowed)
```

### Version

0.10.1

### Frigate config file

```yaml
x
```

### Relevant log output

```shell
x
```

### FFprobe output from your camera

```shell
x
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua VTO

**Comment by blakeblackshear** [comment]
There isn't a way to remove them in the current version. What happens if you set them to the same values you have for scale_vaapi? Does ffmpeg crash?

**Comment by luzik** [comment]
I believe that scale_vaapi is chained before -video_size 1280x720, because CPU usage dropped with both inline. My config look like


```
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        detect: -vf scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -f rawvideo

      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_flags
        - allow_profile_mismatch
        - -hwaccel_output_format
        - vaapi
```

`allow_profile_mismatch ` because my Dahua incorrectly reports h264 profile as a baseline - that moved cpu usage from 50 to 30.  `scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p` from 30% to 10%
