### ISSUE TITLE
[Support/Question]: Tracked Objects not stored to events?  

### ISSUE THREAD

**Issue by MrSiO** [blakeblackshear/frigate#3004]
### Describe the problem you are having

Hi,
I might be missing something, but here is my issue/question:

I get tracked objects (_eg: person)_ that I see on the preview (Picture: https://ibb.co/PZLSk0r  )
but when I click on it, falling in the events, there are no events logged with that preview image....

**Q**: Why is there preview of a person tracked, but no events logged with that same image/tracked person?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.xx.xx.xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxx
  password: xxxxx
  stats_interval: 60    #Etait 60 Secondes pour stationary objects




#######################################
# GLOBAL DETECT CONFIGURATION
######################################  
detect:
 width: 1280
 height: 720
 fps: 5
 enabled: True
 max_disappeared: 25
 stationary:          #Optional: Configuration for stationary object tracking
   interval: 30
   threshold: 25


#######################################
# GLOBAL SNAPSHOT CONFIGURATION
######################################  
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 3





#######################################
# CAMERAS CONFIGURATION
######################################  
cameras:                                                                          
  CAM-08:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@10.10.50.33:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    best_image_timeout: 20 
    rtmp:
      enabled: False    
    objects:                                                                      
      track:                                                                      
        - person                                                                  
        - car

    snapshots:
      required_zones:       #Voiture doit venir de la Zone Rue et passer a Zone Driverway pour faire un snapshot
        - zone_incoming

    zones:
      zone_incoming:
        coordinates: 1092,440,544,671,556,720,1061,517,1280,117,1280,0,594,56,0,194,0,214,605,75                    #121,250,789,144,1133,497,1280,0,594,56,73,176,0,720,130,720
        objects:
          - car
          - person        
        filters:
          car:
            min_score: 0.45    #WAS 0.5
            threshold: 0.55   #WAS 0.60
          person:      
            min_score: 0.6      #WAS 0.5
            threshold: 0.75
                    

      zone_driveway:
        coordinates: 982,553,586,720,118,720,124,275,636,169
        objects:  
          - car
          - person
        filters:
          car:
            min_score: 0.45    #WAS 0.5
            threshold: 0.55    #WAS 0.60
          person:      
            min_score: 0.6      #WAS 0.5
            threshold: 0.75







  CAM-COUR:
    ffmpeg:
      inputs:
        - path: rtsp://10.11.30.56:8554/mjpeg/1
          roles:
            - detect
    best_image_timeout: 20
    rtmp:
      enabled: False
    detect:
      width: 800
      height: 600
      fps: 5
      enabled: True
      max_disappeared: 25
      stationary:
        interval: 0
        threshold: 50        
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 3
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.5
        dog:
          min_score: 0.5

                                                                                  
detectors:                                                                        
  coral:                                                                          
    type: edgetpu                                                                 
    device: usb
```

### Relevant log output

```shell
(soon to come)
```

### FFprobe output from your camera

```shell
(not related)
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest
