### ISSUE TITLE
[Support]: [Errno -2] Name or service not known (mqtt not resolving)

### ISSUE THREAD

**Issue by crutonjohn** [blakeblackshear/frigate#3005]
### Describe the problem you are having

i updated from 0.9.4-amd64 to 0.10.1-amd64 and started experiencing an issue where frigate can't connect to my MQTT broker giving the `Name or service not known` error.

### Version

0.10.1-amd64

### Frigate config file

```yaml
      logger:
        default: debug
      mqtt:
        host: emqx.soho.svc.cluster.local
        # host: 192.168.130.109
        topic_prefix: frigate
        user: "${SECRET_MQTT_USERNAME}"
        password: "${SECRET_MQTT_PASSWORD}"
      database:
        path: /data/frigate.db
      detectors:
        coral:
         type: edgetpu
         device: pci
      ffmpeg:
        hwaccel_args:
          - -hwaccel
          - vaapi
          - -hwaccel_device
          - /dev/dri/renderD128
          - -hwaccel_output_format
          - yuv420p
      objects:
        track:
          - person
          - dog
        filters:
          person:
            min_area: 2500
            max_area: 100000
            threshold: 0.7
          dog:
            min_area: 1000
            max_area: 10000
            threshold: 0.7
      cameras:
        # --
        kitchen-e1-pro:
          ffmpeg:
            inputs:
              - path: rtsp://admin:${REOLINK_ADMIN_PASSWORD}@192.168.134.64:554/h264Preview_01_sub
                roles:
                  - detect
              - path: rtsp://admin:${REOLINK_ADMIN_PASSWORD}@192.168.134.64:554/h264Preview_01_main
                roles:
                  - record
                  - rtmp
            input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - nobuffer
              - -flags
              - low_delay
              - -strict
              - experimental
              - -fflags
              - +genpts+discardcorrupt
              - -use_wallclock_as_timestamps
              - "1"
              - -analyzeduration
              - 1000M
              - -probesize
              - 1000M
          detect:
            height: 352
            width: 640
          record:
            enabled: True
            retain_days: 2
            events:
              retain:
                objects:
                  person: 50
                  dog: 20
              objects:
                - person
                - dog
          snapshots:
            enabled: True
            timestamp: False
            retain:
              default: 14
        # --
        sitting-room-e1-pro:
          ffmpeg:
            inputs:
              - path: rtsp://admin:${REOLINK_ADMIN_PASSWORD}@192.168.134.65:554/h264Preview_01_sub
                roles:
                  - detect
              - path: rtsp://admin:${REOLINK_ADMIN_PASSWORD}@192.168.134.65:554/h264Preview_01_main
                roles:
                  - record
                  - rtmp
            input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - nobuffer
              - -flags
              - low_delay
              - -strict
              - experimental
              - -fflags
              - +genpts+discardcorrupt
              - -use_wallclock_as_timestamps
              - "1"
              - -analyzeduration
              - 1000M
              - -probesize
              - 1000M
          detect:
            height: 352
            width: 640
          record:
            enabled: True
            retain_days: 2
            events:
              retain:
                objects:
                  person: 50
                  dog: 20
              objects:
                - person
                - dog
          snapshots:
            enabled: True
            timestamp: False
            retain:
              default: 14
        # --
        living-room-e1-pro:
          ffmpeg:
            inputs:
              - path: rtsp://admin:${REOLINK_ADMIN_PASSWORD}@192.168.134.66:554/h264Preview_01_sub
                roles:
                  - detect
              - path: rtsp://admin:${REOLINK_ADMIN_PASSWORD}@192.168.134.66:554/h264Preview_01_main
                roles:
                  - record
                  - rtmp
            input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - nobuffer
              - -flags
              - low_delay
              - -strict
              - experimental
              - -fflags
              - +genpts+discardcorrupt
              - -use_wallclock_as_timestamps
              - "1"
              - -analyzeduration
              - 1000M
              - -probesize
              - 1000M
          detect:
            height: 352
            width: 640
          record:
            enabled: True
            retain_days: 2
            events:
              retain:
                objects:
                  person: 50
                  dog: 20
              objects:
                - person
                - dog
          snapshots:
            enabled: True
            timestamp: False
            retain:
              default: 14
        # --
        front-doorbell-ad410:
          ffmpeg:
            inputs:
              - path: rtsp://admin:${AMCREST_ADMIN_PASSWORD}@192.168.134.61:554
                roles:
                  - detect
                  - record
                  - rtmp
          detect:
            height: 1920
            width: 2560
          record:
            enabled: True
            retain_days: 2
            events:
              retain:
                objects:
                  person: 50
                  dog: 20
                  car: 30
              objects:
                - car
                - person
                - dog
          snapshots:
            enabled: True
            timestamp: True
            retain:
              default: 30
        # --
        kitchen-doorbell-ad410:
          ffmpeg:
            inputs:
              - path: rtsp://admin:${AMCREST_ADMIN_PASSWORD}@192.168.134.62:554
                roles:
                  - detect
                  - record
                  - rtmp
          detect:
            height: 1920
            width: 2560
          record:
            enabled: True
            retain_days: 2
            events:
              retain:
                objects:
                  person: 50
                  dog: 20
                  car: 30
              objects:
                - car
                - person
                - dog
          snapshots:
            enabled: True
            timestamp: True
            retain:
              default: 30
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-03-23 00:20:21] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-03-23 00:20:21] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-03-23 00:20:21] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-03-23 00:20:21] peewee_migrate                 INFO    : There is nothing to migrate
[Errno -2] Name or service not known
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://admin:<password>@192.168.134.62:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: -0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

amcrest ad410, reolink E1 Pro

### Any other information that may be helpful

hello Blake and the frigate team. I've been using frigate for some time with no issues running in my k3s cluster. it's a great piece of software and provides me with a sense of security knowing that something is watching out for me even while i'm punching the snooze button.

unfortunately i'm running into a situation that i can't quite explain regarding frigate connecting to my MQTT broker, which is the first time i've ever had an issue that i seemingly can't explain.

before i get into it, here is a link to the relevant parts of my config: https://github.com/crutonjohn/gitops/blob/main/clusters/apps/env/production/soho/frigate/prod/patch.frigate.yaml#L17-L25

knowing that this was probably name resolution related, i've tried several different ways to connect frigate to the broker including using the external loadbalancer IP but regardless of what permutation of connection settings i've used it just doesn't want to connect. 

i then tried rebooting the node that frigate was running on just to make sure that there was nothing wrong with the underlying host. this didn't help either.

as an additional troubleshooting step, i spun up a pod using frigate @ both 0.10.1 and 0.9.4 and they both are able to _resolve_ the internal dns name for my MQTT broker. 

so then i thought it was maybe an issue with my mqtt broker, but this was dispelled by my zigbee2mqtt still functioning with the broker, albeit using the external loadbalancer IP address; whereas frigate isn't able to connect to either the internal DNS name or the external loadbalancer IP address.

for now i've reverted to 9.4, but it's still in a broken state. this is a really strange one to me, and i'm not exactly sure how to proceed considering the circumstances. i know this is kind of a strange case but any help would be greatly appreciated.
