### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by bakercj** [blakeblackshear/frigate#3006]
### Describe the problem you are having

Ffmpeg process crashed unexpectedly at boot.

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.86.200
  user: mqtt
  password: password
  
detectors:
  coral:
    type: edgetpu
    device: pci

cameras:

## Back Side Camera
  back_side:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://frigate:password@192.168.86.245:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:password@192.168.86.245:554//h264Preview_01_main
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 7
    record:
      enabled: True
      expire_interval: 60
      events:
        retain:
          default: 10
          mode: active_objects
        objects:
          - person
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - backpack
        - handbag
        - knife
        - tv
        - laptop
        - cell phone

## Backyard Camera
  backyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://frigate:password@192.168.86.246:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:password@192.168.86.246:554//h264Preview_01_main
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 7
    record:
      enabled: True
      expire_interval: 60
      events:
        retain:
          default: 10
          mode: active_objects
        objects:
          - person
    objects:
      track:
        - person
        - dog
        - car
        - motorcycle
        - bus
        - backpack
        - handbag
        - knife
        - tv
        - laptop
        - cell phone
```

### Relevant log output

```shell
[2022-03-23 09:49:20] frigate.video                  ERROR   : back_side: Unable to read frames from ffmpeg process.
[2022-03-23 09:49:20] frigate.video                  ERROR   : back_side: ffmpeg process is not running. exiting capture thread...
[2022-03-23 09:49:40] watchdog.backyard              ERROR   : Ffmpeg process crashed unexpectedly for backyard.
[2022-03-23 09:49:40] watchdog.backyard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-23 09:49:40] ffmpeg.backyard.detect         ERROR   : [tcp @ 0x55d224e51600] Connection to tcp://192.168.86.246:554?timeout=0 failed: Connection refused
[2022-03-23 09:49:40] ffmpeg.backyard.detect         ERROR   : rtsp://frigate:Zg9Cw3Xmi6MXRyvu@192.168.86.246:554//h264Preview_01_sub: Connection refused
[2022-03-23 09:49:40] watchdog.back_side             ERROR   : Ffmpeg process crashed unexpectedly for back_side.
[2022-03-23 09:49:40] watchdog.back_side             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-23 09:49:40] ffmpeg.back_side.detect        ERROR   : Option rw_timeout not found.
[2022-03-23 09:49:40] ffmpeg.back_side.record_rtmp   ERROR   : Option rw_timeout not found.
[2022-03-23 09:49:40] watchdog.back_side             INFO    : Terminating the existing ffmpeg process...
[2022-03-23 09:49:40] watchdog.back_side             INFO    : Waiting for ffmpeg to exit gracefully..
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x55c016243c80] Connection to tcp://192.168.86.246:554?timeout=0 failed: Connection refused
rtsp://frigate:Zg9Cw3Xmi6MXRyvu@192.168.86.246:554//h264Preview_01_sub: Connection refused
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink 820a

### Any other information that may be helpful

System was functioning with single camera. Attempted to add second camera and lost feed from all cameras. Have tried uninstalling and reinstalling the addon, rebooting the OS, the host, and the cameras. Able to access via RSTP stream in VLC. All endpoints are on same network.
