### ISSUE TITLE
[Support]: green screen

### ISSUE THREAD

**Issue by lpt2007** [blakeblackshear/frigate#3007]
### Describe the problem you are having

green screen

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.199
  user: mqttuser
  password: xxxx

detectors:
  cpu:
    type: cpu

database:
  path: /db/frigate.db

cameras:
  test:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.2.13/onvif1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 960
```

### Relevant log output

```shell
[2022-03-23 22:28:38] ffmpeg.test.detect             ERROR   : [rtsp @ 0x55963bdc7940] Nonmatching transport in server reply
[2022-03-23 22:28:38] ffmpeg.test.detect             ERROR   : rtsp://admin:xxxx@192.168.2.13/onvif1: Invalid data found when processing input
[2022-03-23 22:28:38] frigate.video                  ERROR   : test: Unable to read frames from ffmpeg process.
[2022-03-23 22:28:38] frigate.video                  ERROR   : test: ffmpeg process is not running. exiting capture thread...
[2022-03-23 22:28:48] watchdog.test                  ERROR   : Ffmpeg process crashed unexpectedly for test.
[2022-03-23 22:28:48] watchdog.test                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:20160404@192.168.2.13/onvif1':
  Metadata:
    title           : H.264 Video, RtspServer_0.0.0.2
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1280x960, 15 fps, 25.25 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":217}},"service":{"storage":{"/dev/shm":{"free":66.8,"mount_type":"tmpfs","total":67.1,"used":0.3},"/media/frigate/clips":{"free":6227624.7,"mount_type":"cifs","total":7937399.2,"used":1709774.4},"/media/frigate/recordings":{"free":5014.4,"mount_type":"overlay","total":8350.3,"used":2889.7},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":780,"version":"0.10.1-83481af"},"test":{"camera_fps":0.0,"capture_pid":224,"detection_fps":0.0,"pid":223,"process_fps":0.0,"skipped_fps":0.0}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

camera with rtsp

**Comment by NickM-27** [comment]
Green screen means that ffmpeg is not receiving any frames from the camera. 

There was a similar issue: #2398 where using UDP solved the problem https://docs.frigate.video/configuration/camera_specific/#udp-only-cameras

**Comment by lpt2007** [comment]
I tried stream on vlc and it is working.


![23 03 2022_23 47 52_REC](https://user-images.githubusercontent.com/38924279/159808931-5bc2165c-5dd9-4897-a0bd-d3b5acd4c306.png)

**Comment by NickM-27** [comment]
@lpt2007 yeah, VLC is a good troubleshooting tool at times but just because it works there doesn't mean it will work by default with ffmpeg. Did you try setting it to use UDP like I showed in the docs, the other users had cameras with the exact same url so that should fix it.

**Comment by lpt2007** [comment]
Its working now thx :)

my working config:
```
mqtt:
  host: 192.168.0.199
  user: mqttuser
  password: xxxx

detectors:
  cpu:
    type: cpu

database:
  path: /db/frigate.db

cameras:
  test:
    ffmpeg:
      input_args:
        -avoid_negative_ts make_zero
        -fflags +genpts+discardcorrupt
        -rtsp_transport udp
        -stimeout 5000000
        -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:xxxx@192.168.2.13/onvif1
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 960
```
