### ISSUE TITLE
[Support]: Recording is broken / no mp4 files in /media/frigate/recordings/

### ISSUE THREAD

**Issue by heapxor** [blakeblackshear/frigate#3008]
### Describe the problem you are having

even the Recording is on only snapshots are generated, no recordings are created.
![image](https://user-images.githubusercontent.com/64676/159810979-cc099d37-f784-466e-8758-9c75eb175501.png)

![image](https://user-images.githubusercontent.com/64676/159811009-cc85c723-e0ba-40e2-b37b-f2cfa66f19da.png)

### Version

0.10.1-83481af

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "entrance_cam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://xx:xxx@10.0.1.xx:554",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:k0k0t1n4@10.0.1.109:554 -c copy -f flv rtmp://127.0.0.1/live/entrance_cam -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "entrance_cam",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 180,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 180,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu2": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu3": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "10.0.1.xxx",
    "password": "mqtt",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 180,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 180,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[2022-03-24 00:02:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57344]
[2022-03-24 00:02:22] frigate.mqtt                   INFO    : Turning off recordings for entrance_cam via mqtt
[2022-03-24 00:02:28] frigate.mqtt                   INFO    : Turning on recordings for entrance_cam via mqtt
[2022-03-24 00:04:13] frigate.mqtt                   INFO    : Turning off snapshots for entrance_cam via mqtt
[2022-03-24 00:04:14] frigate.mqtt                   INFO    : Turning off recordings for entrance_cam via mqtt
[2022-03-24 00:04:16] frigate.mqtt                   INFO    : Turning off detection for entrance_cam via mqtt
[2022-03-24 00:04:17] frigate.mqtt                   INFO    : Turning on detection for entrance_cam via mqtt
[2022-03-24 00:04:18] frigate.mqtt                   INFO    : Turning off detection for entrance_cam via mqtt
[2022-03-24 00:04:19] frigate.mqtt                   INFO    : Turning on snapshots for entrance_cam via mqtt
[2022-03-24 00:04:19] frigate.mqtt                   INFO    : Turning on recordings for entrance_cam via mqtt
[2022-03-24 00:04:20] frigate.mqtt                   INFO    : Turning on detection for entrance_cam via mqtt
[2022-03-24 00:04:27] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57344]
[2022-03-24 00:05:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57596]
[2022-03-24 00:05:20] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47458]
[2022-03-24 00:05:22] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47458]
[2022-03-24 00:06:20] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47646]
[2022-03-24 00:06:21] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47646]
[2022-03-24 00:07:36] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47718]
[2022-03-24 00:07:37] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47718]
[2022-03-24 00:07:54] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57596]
[2022-03-24 00:09:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:58000]
[2022-03-24 00:09:10] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:58000]
```

### FFprobe output from your camera

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
Have any events been created? 

I recall giving a recommended config setup a couple days ago:

```yaml
record:
  retain:
    days: 0 # how long to keep all recordings 
  events:
    retain:
      default: 365 # how long to keep recordings that have events

snapshots:
  retain:
    default: 365 # how long to keep snapshots
```

If you want to have 24/7 recordings saved then you will need to change the 0 to how many days of complete recordings that you would like to have kept.

**Comment by heapxor** [comment]
i dont want to have 24/7 recordings saved, i want to save only recordings with movement.... that was asked.

at the moment no recordings are saved at all. Even there are events = Clips.
Events / Clips are there but no recordings for these events.

**Comment by NickM-27** [comment]
@heapxor Thanks that is helpful, can you show a screenshot of the events page?

**Comment by heapxor** [comment]
it is working properly i think
only clips are missing 

![image](https://user-images.githubusercontent.com/64676/159813049-362d713e-a55f-42ac-bffb-439f50339eb5.png)

**Comment by heapxor** [comment]
so it apparently stopped to work on 3rd of March no idea why.

**Comment by NickM-27** [comment]
@heapxor Can you do a couple things I think should hopefully sort things out or at least give a better idea:
1. Confirm in your config.yaml that recording is enabled 
```yaml
entrance_cam:
  record:
    enabled: true <- this is set to true
```
2. Do a restart of the frigate addon. The frigate addon memory usage should start low and slowly increase as it reads recording data to memory. 

Note that at any point that recordings are enabled / working it will not add clips to existing events and a new one will need to be created to ensure it is working as expected 👍

**Comment by heapxor** [comment]
@NickM-27 
i dont get it ....

1) are u talking about frigate.yml? 
that was never there ... as far as i know, its ON via UI
![image](https://user-images.githubusercontent.com/64676/159814347-1d4d5acd-eb52-4e04-9b71-7f2a2b2d0ee4.png)
and its set to ON as i also posted mqtt log ...

2) i did restart .

Yes thats logical that it wont add clips to old Events.... so i am still testing and trying to create new events...

**Comment by heapxor** [comment]
I did all above and the recordings dir is empty its basically not RECORDING At all.

**Comment by NickM-27** [comment]
@heapxor I have seen weird behavior before if it is off in the config and then set it to on in the UI / MQTT will not get it to start. I would say try setting it to true in the config.

**Comment by NickM-27** [comment]
> I did all above and the recordings dir is empty its basically not RECORDING At all.

All recordings will be saved in memory and only added to the `recordings` directory if it matches the event.

**Comment by heapxor** [comment]
i never touch the config and also i cant have it inside config as i am setting it ON/OFF based on some schedule....

**Comment by NickM-27** [comment]
> i never touch the config and also i cant have it inside config as i am setting it ON/OFF based on some schedule....

That's fine, I do the same having a schedule. If you set it to true on the config it can still be disabled via MQTT. I think there may be a bug if it is disabled in the config. Please try enabling in the config and then restarting, I believe that will fix this and may show a bug.

**Comment by heapxor** [comment]
> > I did all above and the recordings dir is empty its basically not RECORDING At all.
> 
> All recordings will be saved in memory and only added to the `recordings` directory if it matches the event retention settings and is part of an event (with your config).

sorry i dont get it ... u are complicating things. The frigate was working year,  didnt touch any config anything. IT stopped to work .

**Comment by heapxor** [comment]
i added this and restarted frigate 
![image](https://user-images.githubusercontent.com/64676/159815069-8992a620-7745-4fa5-ade4-2807f5545749.png)


created events ... which are inside Events but recordings are not there... 
![image](https://user-images.githubusercontent.com/64676/159815205-5bb49c26-58bb-4db6-a777-b15782ca9058.png)

**Comment by heapxor** [comment]
i am more then surprised there is no other debug/logging mechanism ... to find issue ...

**Comment by heapxor** [comment]
![image](https://user-images.githubusercontent.com/64676/159815380-961c9fff-92eb-440a-a876-2c56b32b8caa.png)

**Comment by NickM-27** [comment]
@heapxor Okay I am confused. That screenshot with the retain `180`, is that supposed to be in your config.yaml?

The config you posted at the top doesn't show that at all:
```json
"record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
```

**Comment by heapxor** [comment]
[core-ssh config]$ cat /config/frigate.yml
mqtt:
  host: 10.0.1.1xx
  user: mqtt
  password: mqtt


cameras:
  entrance_cam:
    record:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@10.0.1.xx:554
          roles:
            - detect
            - rtmp


detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu


# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  retain:
    days: 0
  events:
    retain:
      default: 180

snapshots:
  retain:
    default: 180


.....

in that case its other bug; as far as i can remember when i changed time ago ip add of cam it was also not propagated to frigate->debug UI ... but then something happened and it got (or maybe i set old ip to cam i cant remember)

**Comment by NickM-27** [comment]
Can you please paste here your `frigate.yml` config?

**Comment by heapxor** [comment]
> Can you please paste here your `frigate.yml` config?

yes was pasted above

**Comment by heapxor** [comment]
[core-ssh config]$ ls -al /config/frigate.yml
-rw-r--r--    1 root     root           525 Mar 24 00:50 /config/frigate.yml

**Comment by heapxor** [comment]
okay seems that i pasted old Debug  / and after restart correct values got propagated... i am going to update "Debug" section

**Comment by heapxor** [comment]
@NickM-27 now i updated Debug section at the begging of the thread, and also formatted frigate.yaml conf post.

**Comment by NickM-27** [comment]
@heapxor Thanks, everything in there looks correct like it *should* be working. You can add

```yaml
logger:
  default: debug
```

to the frigate.yml and it will create more logs giving context as to what is happening. I would recommend updating that, restarting, then creating a new event and it will hopefully give some clues as to what is going on.

**Comment by blakeblackshear** [comment]
You do not have recordings enabled in your config file. Try updating your config with
```yaml
mqtt:
  host: 10.0.1.1xx
  user: mqtt
  password: mqtt


cameras:
  entrance_cam:
    record:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@10.0.1.xx:554
          roles:
            - detect
            - rtmp


detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu


# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: True    # <--------------------------- This must be set!
  retain:
    days: 0
  events:
    retain:
      default: 180

snapshots:
  retain:
    default: 180
```

If you do not enable the record feature in the config file, turning it on via mqtt or the UI has not effect.

Enabling recordings is clearly outlined in the documentation [here](https://docs.frigate.video/guides/getting_started#step-7-enable-recording-optional).

Also, I don't recommend adding a default logging config of debug. It generates so many messages, it makes it harder to find actual error messages.
