### ISSUE TITLE
[Q] MQTT image usage

### ISSUE THREAD

**Issue by coyote1** [blakeblackshear/frigate#301]
Hi, 
first, thanks for this cool project. 
My Question is, how can i use snapshot received by MQTT?

I got a code like this in MQTT, what can i do with this code?

`����JFIF��C				��C��,,"��	���}!1AQa"q2���#B��R��$3br�	%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz���������������������������������������������������������������������������	���w!1AQaq"2�B����	#3R�br�$4�%�&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz��������������������������������������������������������������������������?�[;��s��ko�_ť�΁��^W�4�ǝ�a�b3lo?{4�$��ue6���z$_k��4���Ct���9�dC'��$8⸫'Ú��"�<E�H�Ri�|�<R�k�[�~��o���s��1�i�w߳]�C�K�7�������T��wR.G�,�I�����g�ԣ���I��T�4����u���Z�ˠx����1џQ�����`^�Iq���C�U��g����G��_�oF��z���$y����Dp�>m�%�5]5�:Uݾ�ែ�׺���um3�ȑ���-��v��5�u��/-<9�|�>�>���[�X�.`'�b�ߖ�@��I�r��~�I�^*��砇�u���������u,(`Ҵ���"�~����#|ϝ�b������o����R���-��ik$g��!��EP�b1g��[�^!�����i�~���&w�kSIm�<K;��L�%�aYT6psU4Ⱦ;�b�x�ZԼ=�ͨ�"�\�h��9�v�kt�F(��.ܞ	&�.Oz��K�H�K��k�(��-�|o6�o�h_�t�ai#[�C��@0[܍�^ҰR��ڥ��/�MgU��7�g���m�.����K���0��q�6<�����Px������Io��`�N��u�օ�Co�+���wo1��>Z��'`�Դ��֚e���K�<~m���� ���%Ci�A��ٰ�*�sY����׾�Ҵڅ��r��4��?��O��<U�;I/���H��K�N����M#ƀ���S�:�M���i�_�z���׾�}���8us9���n��Oj��/?g�yŗ���崉����wu{u9?<�\-�G��*Z����d����p�Mg�����#�h����7I$�bX�j��6���Y4(ҕ=m��f��7�uֆmw�����V_ع$)��$�E�A���*�����C���ைsQ�ؗ?�Ԗ�5����ҳM]E��1?ᔼSޗ�Ӑ��VO�f/��|E}|�gӬ����T�p=+Ӿ�D�g��S���c����cm��QM*\j�0Gil�[k��H�+ֿi�.~˟�����7������?�*1ySK�6o�51���1g�o���� К�B���@����29PX�����s��7����ׄ�^]]<��+_K���n�t���W�ipϩ�FP��f�ir��'���%��l�[�pX�^\Mh4=���&!���B�����V[�����茰�u�poS�o�$��-��;COxjy�^���Y�\�m8�u��m_����\���߉|;��K���Q�\r6���S_7|�V���V�ދu���y�T�����*A�|o�Ꮐ�[�x��/��J�7��#�Ʒ�Ye��6�qJev��щ�I(���;h�������j�tI�e��('���$���}au�S⾹w�\݉|O�xKåt�V� I&a�CٕXs�W��c��%������2/����{y!�C P�h��k�_xk�x������G��`�v�Ϊ�B�+���sҴ4�O�.�h,�~?���Go�T���q��+�刦��nImx�?��֦�j��I%��Vi:֝p���#a�R�q�+��7�o�9x�M7��)��C!�kI���H�uVD�z�b��z�_�7vz&�,�U����1�ˑ��b���b2k�?�����N����I��E��i��7ZN�G���H���"����Ս'-�<Mz�]�$����ڣ�e���~�:t�O������i�W;��D星�R��d���j8ŗ���?B�������=���`�m4�F3�d�θ�|J��u�M.����R��b���D�|{q֔0�k�P�������.�H������g�_�QhuPß�?��?����]���K}�y�Q��?쑭�&M��v���x��V��k�7�����Z��������yw��2���B�n��������1����ö����!$�]���$�z泖Ƥ�������,�*�J5%'�������\����g�.	��D��Z��d�E�J�c�ڳ����V������烒����'u-å�h��f�A`O~sX�{���v����9�/UA��A-��+�7�	��i�>�k��٪�jwI�����]�|%�U%c���v`�Jr�n˿[�}�&;hݲ2��t�v�x�N��	md^D`�^[U����w���4WhE��<�?�Hb�H���L�>����U�z�;~���qc�$���YV�-��30'8�aޯCkFV%�S��$YU��P01�N�SӄdFC���FB��`as�cVn���$8B��N�Kv�B�j�͐���2���I&��4PCf�-+�G�~�'=>���;�y�G9��Um�^MsV�K��;{kC~f��9�M6ѿ�/����$(�)l��`

**Comment by boverby** [comment]
If I can offer one answer,  let hass do the heavy lifting.

first , add a camera  (hik193 is camera name)
```
- name: hik193 Last Person
    platform: mqtt
    topic: frigate/hik193/person/snapshot
```

then use that camera in an automation, This example has two actions

1.  the first action directly answers your question. The mqtt data is dropped into a local file. I had already added /var/www/snaps to the configuration.yaml file as an allowed destination.
```
  allowlist_external_dirs:
   - /var/www/snaps
```
2. The second action uses that local file in a notification.

```
- alias: hik193 Alert me if a person is detected
  trigger:
    platform: state
    entity_id: binary_sensor.hik193_person
    from: 'off'
    to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.hik193_last_person
        filename: '/var/www/snaps/hik193_last_person.jpg'
    - service: notify.scbot
      data:
        message: "HIK193 saw a PERSON."
        data:
          photo:
            caption: 'hik193 saw a person  {{now().strftime("%Y.%m.%d-%H:%M:%S")}}'
            file: '/var/www/snaps/hik193_last_person.jpg'

```
