### ISSUE TITLE
[Support]: How to make sure that the hardware acceleration is turned on successfully?

### ISSUE THREAD

**Issue by github410117** [blakeblackshear/frigate#3013]
### Describe the problem you are having

I would like to ask how to make sure that the hardware acceleration is turned on successfully? I didn't find any information about hardware acceleration in the logs

100%-120% CPU usage when using main stream
30%-50% CPU usage when using sub stream

Whether I use the main stream or the sub stream, the CPU usage does not change after adding hardware acceleration parameters

### Version

0.10.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.135
  port: 1883
  user: mqtt
  password: mqtt
  client_id: frigate

detectors:
  coral_pci:
    type: edgetpu
    device: pci

objects:
  filters:
    person:
      min_score: 0.7

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

cameras:
  camera_1:
    record:
      enabled: true
      events:
        required_zones:
          - door
    snapshots:
      required_zones:
        - door
    zones:
      door:
        coordinates: 1246,715,1545,733,1827,691,2115,726,2168,588,2378,0,2560,0,2560,1440,1183,1440
        objects:
          - person
      ruhu:
        coordinates: 1753,0,1665,562,2038,544,2183,0
        objects:
          - person
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.1.164/h264/ch1/sub/av_stream
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False
```

### Relevant log output

```shell
[2022-03-24 15:08:29] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-03-24 15:08:29] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-03-24 15:08:29] peewee_migrate                 INFO    : There is nothing to migrate
[2022-03-24 15:08:29] frigate.app                    INFO    : Output process started: 219
[2022-03-24 15:08:29] ws4py                          INFO    : Using epoll
[2022-03-24 15:08:29] frigate.app                    INFO    : Camera processor started for camera_1: 229
[2022-03-24 15:08:29] frigate.app                    INFO    : Capture process started for camera_1: 230
[2022-03-24 15:08:29] ws4py                          INFO    : Using epoll
[2022-03-24 15:08:29] detector.coral_pci             INFO    : Starting detection process: 218
[2022-03-24 15:08:29] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-03-24 15:08:29] frigate.edgetpu                INFO    : TPU found
```

### FFprobe output from your camera

```shell
root@48daf90e9e47:/opt/frigate# ffprobe rtsp://admin:xxxx@192.168.1.164/h264/ch1/sub/av_stream
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:xxxx@192.168.1.164/h264/ch1/sub/av_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, progressive), 640x480 [SAR 1:1 DAR 4:3], 25.08 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
There's a couple ways to check / watch, but in general if hardware acceleration args are added and the cameras are working then the hardware acceleration is being used. 

To get more info on its effectiveness you can compare GPU usage % from before and after enabling. Keep in mind that hardware will be used to decode the video stream but software is still used for resizing, motion detection, etc.

There's a relevant discussion with some more potential advice as well: https://github.com/blakeblackshear/frigate/discussions/2976

**Comment by github410117** [comment]
@NickM-27 thanks for your reply，I used the "intel_gpu_top" to check the GPU usage and it keeps showing 0%, no matter if I turn on hardware acceleration or not, what's going on? I don't know the reason at all, if you know the reason, please help me out, thank you。

**Comment by NickM-27** [comment]
> @NickM-27 thanks for your reply，I used the "intel_gpu_top" to check the GPU usage and it keeps showing 0%, no matter if I turn on hardware acceleration or not, what's going on? I don't know the reason at all, if you know the reason, please help me out, thank you。

Are you passing in the GPU device to the docker container?

**Comment by github410117** [comment]
> Are you passing in the GPU device to the docker container?

I think I successfully passed the GPU to docker @NickM-27 

this is docker-compose.yml
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    user: "root"
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config.yml:/config/config.yml:ro
      - /root/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
this is `docker stats` and `intel_gpu_top` status image
<img width="920" alt="image" src="https://user-images.githubusercontent.com/15375736/160313587-791a5f1a-638a-4301-b988-d438dcef97b7.png">

this is view inside the container
<img width="633" alt="image" src="https://user-images.githubusercontent.com/15375736/160313929-66f97d16-aac3-4f97-bb27-8012f0e80dc2.png">

All configurations seem to be fine, but I really can't find where the problem is.
