### ISSUE TITLE
[Support]: Is it possible to improve the thumbnails in the "Events" view?

### ISSUE THREAD

**Issue by marcopaganini** [blakeblackshear/frigate#3024]
### Describe the problem you are having

When clicking on the "Events" view, the thumbnail present is very small and low quality. It would be useful to have a higher quality thumbnail as the preview for the video. I've looked everywhere in the documentation but found no clear way to increase and image size and quality.

Note: When clicking on the video, everything works as expected.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: mqtthost

birdseye:
  enabled: True
  width: 640
  mode: continuous

objects:
  track:
    - person
    - cat
    - dog
live:
  height: 480
  quality: 8

cameras:
  c01:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@amcrest04.local:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:REDACTED@amcrest04.local:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
    rtmp:
      enabled: True
  c02:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@amcrest03.local:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:REDACTED@amcrest03.local:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
    rtmp:
      enabled: True
  c03:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@amcrest01.local:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:REDACTED@amcrest01.local:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
    rtmp:
      enabled: True
  c04:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@amcrest02.local:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:REDACTED@amcrest02.local:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
    rtmp:
      enabled: True
  c05:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@amcrest05.local:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:REDACTED@amcrest05.local:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
      enabled: True
    rtmp:
      enabled: True
```

### Relevant log output

```shell
No relevant log output.
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:REDACTED@amcrest05.local:554/cam/realmonitor?channel=1&subtype=1':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 1.600000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 640x480 [SAR 2571:1928 DAR 857:482], 5 fps, 5 tbr, 90k tbn, 10 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP8M-2496EB, IP2M-852W, IPM-743E, and others.
