### ISSUE TITLE
[Support]: Object in Zone bypassing zone filters

### ISSUE THREAD

**Issue by Morphy99** [blakeblackshear/frigate#3025]
### Describe the problem you are having

I'm trying to eliminate false positives for clouds reflecting on a car window on a drive. I've have set a filter for zone and the object detected however Frigate is still recording an event and not associating it with the Zone.

These are the events:
![image](https://user-images.githubusercontent.com/5853979/160363128-1c95ae61-2c79-401c-9d5a-544dbab0b4a2.png)

This is the type of snapshot I get:

![image](https://user-images.githubusercontent.com/5853979/160363013-644314a6-dc3e-4c45-866b-0d3febc40a43.png)

This is the "Front_Drive" Zone as defined:
![image](https://user-images.githubusercontent.com/5853979/160370259-197417df-c4c6-4027-9666-1ef43c52ef88.png)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: xxxx

detectors:
  coral_pci:
    type: edgetpu
    device: pci

objects:
  track:
    - person
    - car
    - cat
    - dog

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 20
      mode: active_objects
    pre_capture: 10
    post_capture: 10

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 20

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  hwaccel_args:
    - -hwaccel_output_format
    - yuv420p

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtmp://xxxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxxx&password=xxxx
          roles:
            - detect
            - record
            - rtmp
      input_args:
        - -avoid_negative_ts
        - make_zero
    detect:
      width: 2048
      height: 1536
      fps: 5
    mqtt:
      required_zones: 
        - drive
        - path
    motion:
      mask:
        - 0,80,780,79,795,0,0,0
        - 100,1375,0,1342,0,924,368,375,596,384
        - 1207,615,1325,821,1589,727,1473,576,1482,434,1277,417
    objects:
      filters:
        car:
          mask:
            - 22,0,2048,0,2048,448,1324,398,589,394,0,427,0,0
            - 1261,458,1606,1384,781,1430,135,1349,541,471
            - 670,573,195,1536,0,1536,0,554
            - 1629,1536,2048,1536,2048,569,1220,564
        dog:
          max_area: 10000
        person:
          min_area: 5000
          max_area: 100000
          mask: 
            - 859,0,851,189,400,226,0,282,0,0
            - 100,1375,0,1342,0,924,368,375,596,384
    zones:
      Front_Drive:
        coordinates: 139,1295,859,1349,1629,1307,1278,633,494,637
        filters:
          person:
            min_area: 50000
            max_area: 250000
            threshold: 0.8
      Front_Path:
        coordinates: 1830,1536,2048,1536,2048,1102,1701,515,1430,650
        filters:
          person:
            min_area: 80000
            max_area: 150000
            threshold: 0.8
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink RLC-520
