### ISSUE TITLE
[Support]: One of two cameras stopped recording a few days ago

### ISSUE THREAD

**Issue by lxqikrana** [blakeblackshear/frigate#3033]
### Describe the problem you are having

I have two cameras - a Reolink RLC410W and an Amcrest AD110 doorbell. Until a few days ago both cameras were recording clips whenever motion was detected. I'm not entirely sure when, but a few days ago frigate stopped recording clips for the doorbell. It still collects them for the Reolink. I can see live view of both cameras, but just the Amcrest doesn't record clips. The recording option appears enabled on the UI.

Navigating to recordings for the Amcrest, I just get this:

    No Recordings Found

    Make sure you have enabled the record role in your configuration for the main_door camera.

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.199
  user: username
  password: <password>

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8

objects:
  track:
    - person
    - cat
    - dog
    - car
    - bicycle
    - motorcycle

cameras:
  main_door:
    ffmpeg:
        hwaccel_args:
          - -c:v
          - h264_v4l2m2m
        inputs:
          - path: rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - detect
              - rtmp
          - path: rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - record
    motion:
      mask:
        - 640,0,640,29,304,24,210,102,203,204,138,210,110,184,124,0
    detect:
      width: 640
      height: 360
    zones:
      near_door:
        coordinates: 240,305,640,166,640,360,97,360,109,338,150,325
        objects:
          - person
          - cat
          - dog
      driveway:
        coordinates: 149,321,136,234,198,234,230,306
        objects:
          - person
          - cat
          - dog
      street:
        coordinates: 137,201,199,206,202,232,136,229
        objects:
          - person
          - cat
          - dog
    record:
      enabled: True
      retain_days: 0
      events:
        required_zones:
          - near_door
          - driveway
        retain:
          default: 5
          objects:
            person: 10
            cat: 1
            dog: 1


        
  garage_cam:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -f live_flv
      inputs:
        - path: rtmp://192.168.0.188/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=<password>
          roles:
            - detect
            - rtmp
        - path: rtmp://192.168.0.188/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=<password>
          roles:
            - record
    motion:
      mask:
        - 59,133,167,98,290,98,406,92,534,88,640,94,640,0,0,0,0,150
    zones:
      entryway:
        coordinates: 394,171,427,181,30,360,0,360,0,212
        objects:
          - person
          - cat
          - dog
      car_driveway:
        coordinates: 619,360,640,180,392,168,0,330,0,360
        objects:
          - person
          - cat
          - dog
          - car
          - bicycle
          - motorcycle
      footpath:
        coordinates: 122,140,640,160,640,180,114,159
        objects:
          - person
          - cat
          - dog
      opp_footpath:
        coordinates: 640,100,246,104,238,117,640,117
        objects:
          - person
          - cat
          - dog
      road:
        coordinates: 69,138,0,157,0,138,170,98,149,115,640,118,640,161
        objects:
          - car
          - bicycle
          - motorcycle
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain_days: 0
      events:
        required_zones:
          - entryway
          - footpath
          - road
          - car_driveway
        retain:
          default: 5
          objects:
            person: 10
            cat: 1
            dog: 1
            car: 3
            bicycle: 3
            motorcycle: 3
```

### Relevant log output

```shell
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "garage_cam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 360,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-c:v",
          "h264_v4l2m2m"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -f live_flv",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.0.188/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=<password>",
            "roles": [
              "detect",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.0.188/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=<password>",
            "roles": [
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -f live_flv -i rtmp://192.168.0.188/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=<password> -c copy -f flv rtmp://127.0.0.1/live/garage_cam -r 5 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000 -f live_flv -i rtmp://192.168.0.188/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=<password> -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage_cam-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "59,133,167,98,290,98,406,92,534,88,640,94,640,0,0,0,0,150"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "garage_cam",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "dog",
          "car",
          "bicycle",
          "motorcycle"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "entryway",
            "footpath",
            "road",
            "car_driveway"
          ],
          "retain": {
            "default": 5,
            "mode": "motion",
            "objects": {
              "bicycle": 3,
              "car": 3,
              "cat": 1,
              "dog": 1,
              "motorcycle": 3,
              "person": 10
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "car_driveway": {
          "coordinates": "619,360,640,180,392,168,0,330,0,360",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog",
            "car",
            "bicycle",
            "motorcycle"
          ]
        },
        "entryway": {
          "coordinates": "394,171,427,181,30,360,0,360,0,212",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        },
        "footpath": {
          "coordinates": "122,140,640,160,640,180,114,159",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        },
        "opp_footpath": {
          "coordinates": "640,100,246,104,238,117,640,117",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        },
        "road": {
          "coordinates": "69,138,0,157,0,138,170,98,149,115,640,118,640,161",
          "filters": {},
          "objects": [
            "car",
            "bicycle",
            "motorcycle"
          ]
        }
      }
    },
    "main_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 360,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-c:v",
          "h264_v4l2m2m"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=1",
            "roles": [
              "detect",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=1 -c copy -f flv rtmp://127.0.0.1/live/main_door -r 5 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/main_door-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "640,0,640,29,304,24,210,102,203,204,138,210,110,184,124,0"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "main_door",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "dog",
          "car",
          "bicycle",
          "motorcycle"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "near_door",
            "driveway"
          ],
          "retain": {
            "default": 5,
            "mode": "motion",
            "objects": {
              "cat": 1,
              "dog": 1,
              "person": 10
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "driveway": {
          "coordinates": "149,321,136,234,198,234,230,306",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        },
        "near_door": {
          "coordinates": "240,305,640,166,640,360,97,360,109,338,150,325",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        },
        "street": {
          "coordinates": "137,201,199,206,202,232,136,229",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.0.199",
    "password": "<password>",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "lxq_ikrana"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person",
      "cat",
      "dog",
      "car",
      "bicycle",
      "motorcycle"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### FFprobe output from your camera

```shell
Not sure what this is
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Amcrest AD110

### Any other information that may be helpful

I checked these two issues:
https://github.com/blakeblackshear/frigate/issues/2129
https://github.com/blakeblackshear/frigate/issues/3008

#2129 doesn't appear to be my issue, because the recording function is enabled in the debug JSON and on the UI.
#3008 looks like my issue, but I'm not sure what the resolution for that was... it appeared to just start working after a while?

![image](https://user-images.githubusercontent.com/12616210/160935967-3ef9e487-24aa-4c9d-a03b-3905a486378b.png)
This seems to show detection fps for the amcrest at 0. Maybe that's the problem?

**Comment by NickM-27** [comment]
Please supply logs, without these we can not help much. Based on the fact that camera fps is also 0, seems like ffmpeg has lost connection but no way to tell without the logs.

**Comment by lxqikrana** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-03-30 16:48:12] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-03-30 16:48:12] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-03-30 16:48:12] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-03-30 16:48:12] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-03-30 16:48:12] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-03-30 16:48:12] peewee_migrate                 INFO    : There is nothing to migrate
[2022-03-30 16:48:12] frigate.app                    INFO    : Output process started: 219
[2022-03-30 16:48:12] frigate.app                    INFO    : Camera processor started for main_door: 224
[2022-03-30 16:48:12] detector.coral                 INFO    : Starting detection process: 218
[2022-03-30 16:48:12] frigate.app                    INFO    : Camera processor started for garage_cam: 225
[2022-03-30 16:48:12] ws4py                          INFO    : Using epoll
[2022-03-30 16:48:12] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-03-30 16:48:12] frigate.app                    INFO    : Capture process started for main_door: 228
[2022-03-30 16:48:16] frigate.edgetpu                INFO    : TPU found
[2022-03-30 16:48:12] frigate.app                    INFO    : Capture process started for garage_cam: 232
[2022-03-30 16:48:13] ws4py                          INFO    : Using epoll
[2022-03-30 16:48:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:37850]
[2022-03-30 16:48:30] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38882]
[2022-03-30 16:48:32] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38882]
[2022-03-30 16:48:32] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:37850]
[2022-03-30 16:48:33] watchdog.main_door             INFO    : No frames received from main_door in 20 seconds. Exiting ffmpeg...
[2022-03-30 16:48:33] watchdog.main_door             INFO    : Waiting for ffmpeg to exit gracefully...
[2022-03-30 16:48:34] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38498]
[2022-03-30 16:48:35] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38926]
[2022-03-30 16:48:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38498]
[2022-03-30 16:48:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38926]
[2022-03-30 16:48:43] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38570]
[2022-03-30 16:48:44] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38976]
[2022-03-30 16:48:51] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38976]
[2022-03-30 16:48:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38570]
[2022-03-30 16:49:03] watchdog.main_door             INFO    : FFmpeg didnt exit. Force killing...
[2022-03-30 16:49:03] frigate.video                  ERROR   : main_door: Unable to read frames from ffmpeg process.
[2022-03-30 16:49:03] frigate.video                  ERROR   : main_door: Unable to read frames from ffmpeg process.
[2022-03-30 16:49:03] frigate.video                  ERROR   : main_door: Unable to read frames from ffmpeg process.
[2022-03-30 16:49:03] frigate.video                  ERROR   : main_door: Unable to read frames from ffmpeg process.
[2022-03-30 16:49:03] frigate.video                  ERROR   : main_door: ffmpeg process is not running. exiting capture thread...
[2022-03-30 16:49:13] watchdog.main_door             ERROR   : Ffmpeg process crashed unexpectedly for main_door.
[2022-03-30 16:49:13] watchdog.main_door             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-30 16:49:13] ffmpeg.main_door.detect        ERROR   : [flv @ 0x5589750640] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-03-30 16:49:13] ffmpeg.main_door.detect        ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
[2022-03-30 16:49:27] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38826]
[2022-03-30 16:49:29] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39258]
[2022-03-30 16:49:32] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39258]
[2022-03-30 16:49:33] watchdog.main_door             INFO    : No frames received from main_door in 20 seconds. Exiting ffmpeg...
[2022-03-30 16:49:33] watchdog.main_door             INFO    : Waiting for ffmpeg to exit gracefully...
[2022-03-30 16:49:34] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39294]
[2022-03-30 16:49:48] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38974]
[2022-03-30 16:49:50] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39416]
[2022-03-30 16:49:51] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39416]
[2022-03-30 16:49:59] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39456]
[2022-03-30 16:49:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39456]
[2022-03-30 16:50:00] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:38974]
[2022-03-30 16:50:03] watchdog.main_door             INFO    : FFmpeg didnt exit. Force killing...
[2022-03-30 16:50:03] frigate.video                  ERROR   : main_door: Unable to read frames from ffmpeg process.
[2022-03-30 16:50:03] frigate.video                  ERROR   : main_door: ffmpeg process is not running. exiting capture thread...
[2022-03-30 16:50:13] watchdog.main_door             ERROR   : Ffmpeg process crashed unexpectedly for main_door.
[2022-03-30 16:50:13] watchdog.main_door             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-30 16:50:13] ffmpeg.main_door.detect        ERROR   : [rtsp @ 0x558fb20750] DTS discontinuity in stream 1: packet 11 with DTS 26378831292761, packet 12 with DTS 26378831297906
[2022-03-30 16:50:13] ffmpeg.main_door.detect        ERROR   : [flv @ 0x558fb45ae0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-03-30 16:50:13] ffmpeg.main_door.detect        ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
[2022-03-30 16:50:33] watchdog.main_door             INFO    : No frames received from main_door in 20 seconds. Exiting ffmpeg...
[2022-03-30 16:50:33] watchdog.main_door             INFO    : Waiting for ffmpeg to exit gracefully...
[2022-03-30 16:50:34] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39294]
[2022-03-30 16:50:39] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39670]
```

**Comment by NickM-27** [comment]
Yep, looks like ffmpeg errors for this camera. I see `flv` errors which is usually an issue with rtmp. If you disable rtmp for that camera and restart that should fix the issue.

**Comment by lxqikrana** [comment]
Removing the rtmp role from the Amcrest camera (or both) just causes Frigate to crash. I can't get it to start without the rtmp roles. Anything else I can try?

**Comment by NickM-27** [comment]
What crash is occurring, and how did you go about disabling rtmp roles?

**Comment by lxqikrana** [comment]
I just removed the ```- rtmp``` lines from the roles section in frigate.yml like so:
```  main_door:
    ffmpeg:
        hwaccel_args:
          - -c:v
          - h264_v4l2m2m
        inputs:
          - path: rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - detect
          - path: rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - record```

Frigate simply refuses to start if I make this change. I click start on the add-on page, wait a few seconds and refresh the page. It's back to 'Start' rather than the 'Stop' and 'Restart' options that are visible when the add-on is running. There's nothing in the logs.

**Comment by NickM-27** [comment]
Okay, removing the role will not do anything. You will need to remove the role and also disable rtmp as a global or for the camera that is having issues.

**Comment by lxqikrana** [comment]
Err, how do I do that? I don't have rtmp associated with main_door anywhere else in frigate.yml. Do I have to do this somewhere else?

**Comment by NickM-27** [comment]
it is enabled by default so the section needs to be added. I took the camera main_door config from your post up top and removed rtmp role and added rtmp config with enabled as false:

```yaml
cameras:
  main_door:
    ffmpeg:
        hwaccel_args:
          - -c:v
          - h264_v4l2m2m
        inputs:
          - path: rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - detect
          - path: rtsp://admin:<password>@192.168.0.36:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - record
    motion:
      mask:
        - 640,0,640,29,304,24,210,102,203,204,138,210,110,184,124,0
    detect:
      width: 640
      height: 360
    zones:
      near_door:
        coordinates: 240,305,640,166,640,360,97,360,109,338,150,325
        objects:
          - person
          - cat
          - dog
      driveway:
        coordinates: 149,321,136,234,198,234,230,306
        objects:
          - person
          - cat
          - dog
      street:
        coordinates: 137,201,199,206,202,232,136,229
        objects:
          - person
          - cat
          - dog
    record:
      enabled: True
      retain_days: 0
      events:
        required_zones:
          - near_door
          - driveway
        retain:
          default: 5
          objects:
            person: 10
            cat: 1
            dog: 1
    rtmp:
      enabled: false
```
