### ISSUE TITLE
[Support]: Frigate seems to lose connection to ad410 doorbell and never recover

### ISSUE THREAD

**Issue by mogorman** [blakeblackshear/frigate#3036]
### Describe the problem you are having

I have 2 ad410 door bell cameras.  Over the period of a few days they seem to stop reporting events into frigate.  When I go into the interface of frigate the live view is just blank.  when I hit the same rtsp information i have for frigate in vlc it loads the video for these cameras without problem.

I am assuming given these cameras are hooked up over wifi that occasionally they disappear for a moment and frigate is just not reconnecting to them properly.

Hitting the restart button in frigate always resolves the problem for me.

### Version

0.10.1-83481af

### Frigate config file

```yaml
birdseye:
  enabled: False

mqtt:
  host: host.docker.internal
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"
  client_id: frigate

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral1:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci:0
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3
  coral2:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: pci:1
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3


objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  #  back:
  #    ffmpeg:
  #      inputs:
  #        - path: rtsp://doorcam:8554/unicast
  #          roles:
  #            - detect
  #            - rtmp
  #    detect:
  #      width: 1600
  #      height: 900
  #  outdoor1:
  #    ffmpeg:
  #      inputs:
  #        - path: "rtsp://admin:{FRIGATE_CAMERA_PASSWORD}@outdoor1.lan:554/"
  #          roles:
  #            - detect
  #            - rtmp
  #    detect:
  #      width: 1920
  #      height: 1080
  frontdoor:
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_FRONTDOOR_CREDS}@10.0.100.41:554/"
          roles:
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1920
  sidedoor:
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_SIDEDOOR_CREDS}@10.0.100.42:554/"
          roles:
            - detect
            - rtmp
    detect:
      width: 2560
      height: 1920



snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 365

record:
  # Optional: Enable recording (default: shown below)
  enabled: True
  # Optional: Number of days to retain recordings regardless of events (default: shown below)
  # NOTE: This should be set to 0 and retention should be defined in events section below
  #       if you only want to retain recordings of events.
  retain_days: 10
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - mouse
    retain:
      # Required: Default retention days (default: shown below)
      default: 365
```

### Relevant log output

```shell
nothing relevant in logs i can see can post long dump if needed
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/rvhidl2j4722wgryamn5qshm7azvnw0j-ffmpeg-4.4.1 --arch=x86_64 --target_os=linux --enable-gpl --enable-version3 --enable-shared --enable-pic --enable-libsrt --enable-runtime-cpudetect --enable-hardcoded-tables --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --disable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --disable-doc --enable-libass --enable-bzlib --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libmp3lame --enable-iconv --enable-libtheora --enable-libssh --enable-vaapi --enable-libdrm --enable-vdpau --enable-libvorbis --enable-libvpx --enable-lzma --disable-opengl --disable-libmfx --disable-libaom --enable-libpulse --enable-sdl2 --enable-libsoxr --enable-libx264 --enable-libxvid --enable-zlib --enable-libopus --enable-libspeex --enable-libx265 --enable-libdav1d --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://CREDS@sidedoor':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp


ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/rvhidl2j4722wgryamn5qshm7azvnw0j-ffmpeg-4.4.1 --arch=x86_64 --target_os=linux --enable-gpl --enable-version3 --enable-shared --enable-pic --enable-libsrt --enable-runtime-cpudetect --enable-hardcoded-tables --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --disable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --disable-doc --enable-libass --enable-bzlib --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libmp3lame --enable-iconv --enable-libtheora --enable-libssh --enable-vaapi --enable-libdrm --enable-vdpau --enable-libvorbis --enable-libvpx --enable-lzma --disable-opengl --disable-libmfx --disable-libaom --enable-libpulse --enable-sdl2 --enable-libsoxr --enable-libx264 --enable-libxvid --enable-zlib --enable-libopus --enable-libspeex --enable-libx265 --enable-libdav1d --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://CREDS@frontdoor':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 2560x1920, 15 fps, 100 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{"detection_fps":31.9,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":8.72,"pid":216},"coral2":{"detection_start":1648736656.463947,"inference_speed":8.34,"pid":218}},"frontdoor":{"camera_fps":5.0,"capture_pid":257,"detection_fps":21.1,"pid":230,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":44.0,"mount_type":"tmpfs","total":67.1,"used":23.2},"/media/frigate/clips":{"free":13225459.5,"mount_type":"ext4","total":17927489.7,"used":3802003.9},"/media/frigate/recordings":{"free":13225459.5,"mount_type":"ext4","total":17927489.7,"used":3802003.9},"/tmp/cache":{"free":997.4,"mount_type":"tmpfs","total":1000.0,"used":2.6}},"temperatures":{"apex_0":81.05,"apex_1":80.05},"uptime":976,"version":"0.10.1-83481af"},"sidedoor":{"camera_fps":5.1,"capture_pid":258,"detection_fps":10.8,"pid":244,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wireless

### Camera make and model

amcrest ad410
