### ISSUE TITLE
[Support]: High Motion Sensitivity 

### ISSUE THREAD

**Issue by TelepathicWalrus** [blakeblackshear/frigate#3042]
### Describe the problem you are having

Hi, I've been having an issue where in version 0.10.1 motion detection is too sensitive, this usually happens where there is grass in the wind. I have tried changing the threshold and contour_area however this misses a lot of actual motion, which isn't ideal. I have also turned off imporved_contrast and this did help somewhat but the problem is still there any help would be fantastic, Thanks!

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
    host: 192.168.1.3
    port: 1883
    user: mqtt-user
    password: *

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  # cpu2:
    # type: cpu
    # num_threads: 3
  # cpu3:
    # type: cpu
    # num_threads: 3

# ffmpeg:
  # hwaccel_args:
    # - -c:v
    # - hevc_cuvid
motion:
  #threshold: 35
  improve_contrast: False

snapshots:
  enabled: True

model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - animal
  filters:
    person:
      min_score: 0.65
      threshold: 0.8
      min_area: 40000
    animal:
      min_area: 3000
      max_area: 210000

record:
  enabled: True
  retain:
    days: 20
    mode: all

detect:
  stationary:
    interval: 50

rtmp:
  enabled: False

cameras:
  Garden_Side:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.5:554
          roles:
            - record
            - rtmp
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 5
    motion:
      mask:
        - 3717,146,3135,143,3128,90,3711,95
        - 3840,0,3840,970,3640,873,3652,773,3132,511,2642,349,2651,259,2501,231,2514,106,2542,0
  Garden_Shed:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.4:554
          roles:
            - record
            - rtmp
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 5
    motion:
      mask:
        - 3717,146,3135,143,3128,90,3711,95
        - 0,0,2021,0,2567,0,2564,122,2155,115,2155,262,1634,399,1307,508,976,627,745,736,689,624,90,908,0,427
        - 3840,0,3840,318,3339,238,3096,192,2958,174,2907,162,2854,143,2636,116,2439,112,2433,0
  Garden_Washing_Line:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.6:554
          roles:
            - record
            - rtmp
            - detect
    detect:
      width: 3840
      height: 2160
      fps: 5
    motion:
      mask:
        - 3717,146,3135,143,3128,90,3711,95
        - 0,0,0,518,715,327,1265,157,1625,70,1631,0
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x55f03b645f00] max delay reached. need to consume packet
[rtsp @ 0x55f03b645f00] RTP: missed 57 packets
[h264 @ 0x55f03b649dc0] error while decoding MB 170 60, bytestream -11
[h264 @ 0x55f03b649dc0] concealing 18119 DC, 18119 AC, 18119 MV errors in P frame
[rtsp @ 0x55f03b645f00] max delay reached. need to consume packet
[rtsp @ 0x55f03b645f00] RTP: missed 6 packets
[h264 @ 0x55f03b649dc0] error while decoding MB 107 108, bytestream -9
[h264 @ 0x55f03b649dc0] concealing 6662 DC, 6662 AC, 6662 MV errors in P frame
[rtsp @ 0x55f03b645f00] max delay reached. need to consume packet
[rtsp @ 0x55f03b645f00] RTP: missed 2 packets
Input #0, rtsp, from 'rtsp://admin:@192.168.1.6:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.240000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 100 tbr, 90k tbn, 180k tbc
```

### Frigate stats

```json
{"Garden_Shed":{"camera_fps":5.0,"capture_pid":255,"detection_fps":4.3,"pid":248,"process_fps":4.6,"skipped_fps":0.0},"Garden_Side":{"camera_fps":5.1,"capture_pid":252,"detection_fps":2.0,"pid":246,"process_fps":5.1,"skipped_fps":0.0},"Garden_Washing_Line":{"camera_fps":5.1,"capture_pid":258,"detection_fps":7.7,"pid":250,"process_fps":4.2,"skipped_fps":0.0},"detection_fps":14.0,"detectors":{"cpu1":{"detection_start":1648829490.313024,"inference_speed":57.01,"pid":240}},"service":{"storage":{"/dev/shm":{"free":2096.3,"mount_type":"tmpfs","total":2147.5,"used":51.2},"/media/frigate/clips":{"free":9957669.9,"mount_type":"zfs","total":15484829.4,"used":5527159.6},"/media/frigate/recordings":{"free":9957669.9,"mount_type":"zfs","total":15484829.4,"used":5527159.6},"/tmp/cache":{"free":812.2,"mount_type":"tmpfs","total":1000.0,"used":187.8}},"temperatures":{},"uptime":651,"version":"0.10.1-83481af"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP8M-2496EW-V2
