### ISSUE TITLE
[Support]: zone based object detection not working

### ISSUE THREAD

**Issue by lcasale** [blakeblackshear/frigate#3049]
### Describe the problem you are having

I'm trying to break my driveway camera into zones to avoid vehicle detection on the main street. However, only the person object is being applied to the camera and zones unless I add vehicle tracking to the camera level but then it's not restricted to the zone I want to track vehicles. I've mimicked the configuration [here](https://docs.frigate.video/configuration/zones) but it doesn't seem to be working.

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: ****
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ****
  password: ****
  stats_interval: 60
model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    22: animal
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtsp://****:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - detect
        - path: 'rtsp://****:554/cam/realmonitor?channel=1&subtype=0'
          roles:
            - record
            - rtmp
    record:
      enabled: True
      events:
        required_zones:
          - driveway_end
          - driveway_full
    snapshots:
      required_zones:
        - driveway_end
        - driveway_full
    zones:
      driveway_end:
        coordinates: 601,480,0,480,0,110,84,95,154,84,259,73,375,116
        objects:
          - vehicle
      driveway_full:
        coordinates: 0,480,704,480,704,0,0,0
        objects:
          - person
          - animal
    detect:
      width: 704
      height: 480
      fps: 5
    mqtt:
      bounding_box: true
      quality: 100  
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  quality: 100
  retain:
    default: 7
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 7
      mode: active_objects
detectors:
 coral:
   type: edgetpu
   device: pci
logger:
  default: debug
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW
