### ISSUE TITLE
[Support]: Frigate started using 100% CPU and kicking system killing errors

### ISSUE THREAD

**Issue by brenninger** [blakeblackshear/frigate#3050]
### Describe the problem you are having

Within the last couple of days, I started to getting endless errors in my frigate logs and my CPU usage has jumped to 100% and I'm not sure what has caused the problems. 

This is basically causing my HA to shut down because it uses up all my CPU usage. I can't think of any updates that I have done that would have caused this issue. I am up to date with my HA version and up to date with my Frigate version. I have restarted my Amcrest cameras in hopes to restart the RTSP stream but can't figure out the issue. It appears that the issue is happening with all my cameras and not just one. 

Does anyone have any solutions about what is causing my problems?

### Version

0.10.1-83481af

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "backyard": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 480,
        "max_disappeared": 20,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 704
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@#########:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=1",
            "roles": [
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an",
          "rtmp": "-c:v libx264 -an -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.16:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an /tmp/cache/backyard-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.16:554/cam/realmonitor?channel=1&subtype=1 -c:v libx264 -an -f flv rtmp://127.0.0.1/live/backyard -r 5 -s 704x480 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "693,18,692,49,608,45,598,17"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "backyard",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.6,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 3,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 3,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "rear_deck": {
          "coordinates": "51,77,0,125,1,324,12,480,704,478,701,320,434,235,228,179,143,42",
          "filters": {},
          "objects": []
        },
        "rear_yard": {
          "coordinates": "304,52,458,63,633,100,701,145,704,314,587,280,282,182,173,52",
          "filters": {},
          "objects": []
        }
      }
    },
    "driveway": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 20,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=1",
            "roles": [
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=2",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an",
          "rtmp": "-c:v libx264 -an -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.15:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an /tmp/cache/driveway-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.15:554/cam/realmonitor?channel=1&subtype=1 -c:v libx264 -an -f flv rtmp://127.0.0.1/live/driveway",
          "roles": [
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.15:554/cam/realmonitor?channel=1&subtype=2 -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "952,59,1221,61,1230,28,955,29"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "driveway",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.55,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "bicycle",
          "cat",
          "car",
          "motorcycle"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 5,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 3,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "blacktop": {
          "coordinates": "511,720,1140,720,1252,479,1084,354,867,257,733,181,427,87,269,130",
          "filters": {},
          "objects": []
        },
        "east_yard": {
          "coordinates": "0,720,340,720,366,622,241,162,0,226",
          "filters": {},
          "objects": []
        },
        "front_yard": {
          "coordinates": "505,82,792,185,846,100,971,102,851,62,642,57",
          "filters": {},
          "objects": []
        }
      }
    },
    "front_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 480,
        "max_disappeared": 20,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=1",
            "roles": [
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an",
          "rtmp": "-c:v libx264 -an -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.10:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an /tmp/cache/front_door-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.10:554/cam/realmonitor?channel=1&subtype=1 -c:v libx264 -an -f flv rtmp://127.0.0.1/live/front_door -r 5 -s 640x480 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "624,15,630,44,550,39,552,10"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_door",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "bicycle",
          "cat",
          "car",
          "motorcycle"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 3,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 3,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "west": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 480,
        "max_disappeared": 20,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=0",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@###########:554/cam/realmonitor?channel=1&subtype=1",
            "roles": [
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an",
          "rtmp": "-c:v libx264 -an -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.12:554/cam/realmonitor?channel=1&subtype=0 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an /tmp/cache/west-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i rtsp://admin:bryce2010@192.168.50.12:554/cam/realmonitor?channel=1&subtype=1 -c:v libx264 -an -f flv rtmp://127.0.0.1/live/west -r 5 -s 640x480 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "612,21,608,47,486,50,490,21"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "west",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": [
              "39,221,55,292,250,480,640,480,605,147,192,74"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [
              "219,320,277,398,157,378,136,392"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [
              "278,400,232,480,157,378,206,310"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "bicycle",
          "car",
          "motorcycle"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 3,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 3,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "front_yard": {
          "coordinates": "31,254,220,80,105,94,5,199",
          "filters": {},
          "objects": []
        },
        "west_yard": {
          "coordinates": "41,263,167,476,633,474,639,96,250,46",
          "filters": {},
          "objects": []
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": 20,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": 50
    },
    "width": 1280
  },
  "detectors": {
    "coral_pci": {
      "device": "pci",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1",
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an",
      "rtmp": "-c:v libx264 -an -f flv"
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.200.137",
    "password": "MQTT",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "MQTT"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[2022-04-02 21:29:38] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-04-02 21:29:38] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-04-02 21:29:38] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-04-02 21:29:38] peewee_migrate                 INFO    : There is nothing to migrate
[2022-04-02 21:29:38] detector.coral_pci             INFO    : Starting detection process: 226
[2022-04-02 21:29:38] frigate.app                    INFO    : Output process started: 227
[2022-04-02 21:29:38] ws4py                          INFO    : Using epoll
[2022-04-02 21:29:38] frigate.app                    INFO    : Camera processor started for driveway: 233
[2022-04-02 21:29:38] frigate.app                    INFO    : Camera processor started for west: 234
[2022-04-02 21:29:38] frigate.app                    INFO    : Camera processor started for front_door: 236
[2022-04-02 21:29:38] frigate.app                    INFO    : Camera processor started for backyard: 238
[2022-04-02 21:29:38] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-04-02 21:29:38] frigate.edgetpu                INFO    : TPU found
[2022-04-02 21:29:38] frigate.app                    INFO    : Capture process started for driveway: 239
[2022-04-02 21:29:38] frigate.app                    INFO    : Capture process started for west: 253
[2022-04-02 21:29:38] frigate.app                    INFO    : Capture process started for front_door: 258
[2022-04-02 21:29:38] frigate.app                    INFO    : Capture process started for backyard: 262
[2022-04-02 21:29:38] ws4py                          INFO    : Using epoll
[2022-04-02 21:29:51] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:50958]
[2022-04-02 21:31:56] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:56] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : west: ffmpeg process is not running. exiting capture thread...
[2022-04-02 21:31:57] frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
[2022-04-02 21:31:57] frigate.video                  ERROR   : front_door: Unable to read frames from ffmpeg process.
[2022-04-02 21:31:57] frigate.video                  ERROR   : front_door: ffmpeg process is not running. exiting capture thread...
[2022-04-02 21:31:58] watchdog.front_door            ERROR   : Ffmpeg process crashed unexpectedly for front_door.
[2022-04-02 21:31:58] watchdog.front_door            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-04-02 21:31:58] ffmpeg.front_door.detect       ERROR   : rtsp://user:pass@########:554/cam/realmonitor?channel=1&subtype=1: Connection timed out
[2022-04-02 21:31:58] ffmpeg.front_door.detect       ERROR   : [flv @ 0x557ed9e45400] Failed to update header with correct duration.
[2022-04-02 21:31:58] ffmpeg.front_door.detect       ERROR   : [flv @ 0x557ed9e45400] Failed to update header with correct filesize.
[2022-04-02 21:31:58] watchdog.backyard              ERROR   : Ffmpeg process crashed unexpectedly for backyard.
[2022-04-02 21:31:58] watchdog.backyard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-04-02 21:31:58] ffmpeg.backyard.detect         ERROR   : rtsp://user:pass@##########:554/cam/realmonitor?channel=1&subtype=1: Connection timed out
[2022-04-02 21:31:58] ffmpeg.backyard.detect         ERROR   : [flv @ 0x565283c41a00] Failed to update header with correct duration.
[2022-04-02 21:31:58] ffmpeg.backyard.detect         ERROR   : [flv @ 0x565283c41a00] Failed to update header with correct filesize.
[2022-04-02 21:31:58] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
[2022-04-02 21:31:58] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-04-02 21:31:58] ffmpeg.driveway.detect         ERROR   : rtsp://user:pass@##########:554/cam/realmonitor?channel=1&subtype=2: Connection timed out
[2022-04-02 21:31:58] watchdog.west                  ERROR   : Ffmpeg process crashed unexpectedly for west.
[2022-04-02 21:31:58] watchdog.west                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-04-02 21:31:58] ffmpeg.west.detect             ERROR   : rtsp://user:pass@############:554/cam/realmonitor?channel=1&subtype=1: Connection timed out
[2022-04-02 21:31:58] ffmpeg.west.detect             ERROR   : [flv @ 0x562c536ae640] Failed to update header with correct duration.
[2022-04-02 21:31:58] ffmpeg.west.detect             ERROR   : [flv @ 0x562c536ae640] Failed to update header with correct filesize.
[2022-04-02 21:31:58] ffmpeg.driveway.rtmp           ERROR   : rtsp://user:pass@############:554/cam/realmonitor?channel=1&subtype=1: Connection timed out
[2022-04-02 21:31:58] ffmpeg.driveway.rtmp           ERROR   : [flv @ 0x558112e16400] Failed to update header with correct duration.
[2022-04-02 21:31:58] ffmpeg.driveway.rtmp           ERROR   : [flv @ 0x558112e16400] Failed to update header with correct filesize.
[2022-04-02 21:31:58] watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
[2022-04-02 21:31:58] watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
[2022-04-02 21:32:17] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:50958]
```

### FFprobe output from your camera

```shell
Unknown?
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Amcrest
