### ISSUE TITLE
[Support]: Playback cannot continue. No available working or supported playlists. 

### ISSUE THREAD

**Issue by bakercj** [blakeblackshear/frigate#3054]
### Describe the problem you are having

Unable to playback recordings within Frigate UI for Reolink cameras. Eufy RSTP streams are playing back within UI as expected.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
## Backyard Camera
  backyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rtsp_transport
        - tcp
      inputs:
        - path: rtsp://username:password@192.168.8.5:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://username:password@192.168.8.5:554//h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 7
        mode: motion
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 5
          mode: motion
          objects:
            person: 7
    objects:
      track:
        - person
        - dog
```

### Relevant log output

```shell
## Backyard Camera
  backyard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rtsp_transport
        - tcp
      inputs:
        - path: rtsp://remote:LJM9ExsGsk@192.168.8.5:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://remote:LJM9ExsGsk@192.168.8.5:554//h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 7
        mode: motion
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 5
          mode: motion
          objects:
            person: 7
    objects:
      track:
        - person
        - dog
```

### FFprobe output from your camera

```shell
Unsure *where* ffprobe should be run
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink 820a

### Any other information that may be helpful

Downloading clip and playing back in VLC works.
