### ISSUE TITLE
[Support]: Frigate crashes when using custom model

### ISSUE THREAD

**Issue by Xerionius** [blakeblackshear/frigate#3058]
### Describe the problem you are having

I have trained a custom model using TensorFlow Lite Model Maker, following this guide: [Object Detection with TensorFlow Lite Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection).
I used model spec EfficientDet-Lite0, but I'm getting the same result with EfficientDet-Lite2 (after updating the config file with the correct model dimensions).

A couple days ago it worked fine, but when I started docker today, Frigate started crashing every time it gets restarted. It happens after a couple seconds, just after delivering a single frame to the Web UI. Using the default model, Frigate works fine.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 172.20.0.2
  port: 1883
cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.178.166:8080/h264_ulaw.sdp 
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    detect:
      width: 1920
      height: 1080
ffmpeg:
  input_args:
    - -c:v
    - h264_cuvid
logger:
  default: debug
  logs:
    frigate.mqtt: debug
    frigate.app: debug
objects:
  track:
    - knife
```

### Relevant log output

```shell
frigate  | [2022-04-06 20:12:04] detector.cpu                   INFO    : Starting detection process: 377
frigate  | [2022-04-06 20:12:04] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | Process detector:cpu:
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate  |     self.run()
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate  |     self._target(*self._args, **self._kwargs)
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 160, in run_detector
frigate  |     detections = object_detector.detect_raw(input_frame)
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 89, in detect_raw
frigate  |     count = int(
frigate  | TypeError: only size-1 arrays can be converted to Python scalars
frigate  | [2022-04-06 20:12:14] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate  | [2022-04-06 20:12:14] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:52468]
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [2022-04-06 20:12:14] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-04-06 20:12:14] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rtsp, from 'rtsp://192.168.178.166:8080/h264_ulaw.sdp':
  Metadata:
    title           : IP Webcam
  Duration: N/A, start: 0.239222, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuv420p(tv, unknown/bt470bg/unknown, progressive), 1920x1080, 90k tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Android App "IP Webcam"

### Any other information that may be helpful

Mounting the custom model through docker-compose.yml:
      - /home/***user***/frigate/tflite/model.tflite:/cpu_model.tflite

**Comment by NickM-27** [comment]
Can you include the config that also defines the model?

**Comment by blakeblackshear** [comment]
Did you rebuild the container from source? Don't do that. Or at least just run the frigate build without rebuilding wheels.

**Comment by Xerionius** [comment]
> Can you include the config that also defines the model?

`import numpy as np
import os

from tflite_model_maker.config import QuantizationConfig
from tflite_model_maker.config import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector

import tensorflow as tf
assert tf.__version__.startswith('2')

tf.get_logger().setLevel('ERROR')
from absl import logging
logging.set_verbosity(logging.ERROR)
spec = model_spec.get('efficientdet_lite0')
train_data, validation_data, test_data = object_detector.DataLoader.from_csv('knife_ml.csv')
model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)
model.evaluate(test_data)
model.export(export_dir='.')
model.evaluate_tflite('model.tflite', test_data)
`



> Did you rebuild the container from source? Don't do that. Or at least just run the frigate build without rebuilding wheels.

No, I haven't rebuilt anything.

**Comment by NickM-27** [comment]
You should have something like this in your config, per the docs

```yaml
# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320

```
