### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by pcb1962** [blakeblackshear/frigate#3061]
### Describe the problem you are having

Snapshot on mqtt message ignores settings for timestamp / bounding box / crop. Timestamp on snapshot has US date format.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: xxx
  user: xxx
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  roadcam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/12
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/11
          roles:
            - record
    detect:
      width: 640
      height: 352
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          min_area: 2500
    zones:
      rc_drive_zone:
        coordinates: 0,352,640,352,640,232,0,167
      rc_road_zone:
        coordinates: 0,159,640,221,640,0,0,0

  drivecam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/12
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/11
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          min_area: 7000
        car:
          mask:
            - 390,100,390,190,290,190,290,100
    zones:
      dc_inner_zone:
        coordinates: 56,480,640,480,640,0,310,0
      dc_outer_zone:
        coordinates: 305,0,53,480,0,480,0,0

  drivecam2:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/stream1
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/stream0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          min_area: 10000
        car:
          mask:
            - 165,45,35,75,50,142,153,110
    motion:
      mask:
        - 0,0,640,0,640,90,280,22,0,90
    zones:
      dc2_outer_zone:
        coordinates: 640,90,283,24,0,79,640,282
      dc2_inner_zone:
        coordinates: 0,480,640,480,640,283,0,80

  gardencam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/12
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/11
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle

  pathcam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/12
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/11
          roles:
            - record
    detect:
      width: 640
      height: 352
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat
        - dog
        - bicycle

  hallcam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/media/video3
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/media/video1
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 10000
          mask:
            - 0,360,0,130,105,158,147,360
        cat:
          max_area: 25000
          mask:
            - 0,360,0,130,105,158,147,360

  utrmcam:
    ffmpeg:
      inputs:
        - path: rtsp://xxx/media/video3
          roles:
            - detect
            - rtmp
        - path: rtsp://xxx/media/video3
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    rtmp:
      enabled: true
    objects:
      track:
        - person
        - cat

record:
  enabled: true
  retain:
    days: 10
  events:
    retain:
      default: 10

snapshots:
  enabled: true
  bounding_box: false
  crop: false
  timestamp: false
  retain:
    default: 10

#ffmpeg:
# hwaccel_args:
#   - -c:v
#   - h264_v4l2m2m

# Available log levels are: debug, info, warning, error, critical
logger:
  default: debug
  logs:
    frigate.events: info
    frigate.mqtt: info
    frigate.output: info
    frigate.record: info
    peewee: info
    ws4py: warning

# recordings are on NAS, database on local SSD
database:
  path: /db/frigate.db
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"detection_fps":18.7,"detectors":{"coral":{"detection_start":1649336547.655291,"inference_speed":17.28,"pid":216}},"drivecam":{"camera_fps":5.1,"capture_pid":236,"detection_fps":0.0,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"drivecam2":{"camera_fps":5.1,"capture_pid":238,"detection_fps":8.1,"pid":227,"process_fps":5.1,"skipped_fps":0.0},"gardencam":{"camera_fps":5.1,"capture_pid":241,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"hallcam":{"camera_fps":5.0,"capture_pid":251,"detection_fps":0.0,"pid":232,"process_fps":5.0,"skipped_fps":0.0},"pathcam":{"camera_fps":5.1,"capture_pid":247,"detection_fps":4.2,"pid":229,"process_fps":5.1,"skipped_fps":0.0},"roadcam":{"camera_fps":5.1,"capture_pid":235,"detection_fps":6.4,"pid":221,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":1067.5,"mount_type":"tmpfs","total":1073.7,"used":6.2},"/media/frigate/clips":{"free":823280.1,"mount_type":"nfs4","total":1967846.2,"used":1044529.4},"/media/frigate/recordings":{"free":823280.1,"mount_type":"nfs4","total":1967846.2,"used":1044529.4},"/tmp/cache":{"free":983.7,"mount_type":"tmpfs","total":1000.0,"used":16.3}},"temperatures":{},"uptime":693,"version":"0.10.1-83481af"},"utrmcam":{"camera_fps":5.0,"capture_pid":255,"detection_fps":0.0,"pid":234,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

I am capturing mqtt topic 'frigate/+/+/snapshot' in nodeRed and publishing the payload to Telegram as type photo. 
Photo is always cropped and has bounding box (I want those) but also has datestamp at top of frame in US date format with no apparent way to change that.

**Comment by NickM-27** [comment]
The snapshot you have defined is just for snapshot events, there are completely different config options for customizing the mqtt thumbnail

```yaml
# Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
```
