### ISSUE TITLE
Allow date format change on snapshots

### ISSUE THREAD

**Issue by pcb1962** [blakeblackshear/frigate#3062]
**Describe what you are trying to accomplish and why in non technical terms**
Timestamp on snapshot images is in US date format with no option to change

**Describe the solution you'd like**
Either use the system locale, or allow option of US, dd/mm/yyyy or ISO

**Describe alternatives you've considered**
If you don't crop the snapshot then you have the camera timestamp on the image, but I prefer snapshots to be cropped

**Comment by NickM-27** [comment]
[Per the docs](https://docs.frigate.video/configuration/index) you can customize the timestamp in the config. 

```yaml
# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: None
```
