### ISSUE TITLE
[Support]: Home-Assistant integration: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.

### ISSUE THREAD

**Issue by maxi1134** [blakeblackshear/frigate#3063]
### Describe the problem you are having

My home-assistant is spewing errors regarding the sensor.frigate_event being over 255 characters long.

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "facecam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 2304,
        "max_disappeared": 50,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1296
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:password@192.168.50.9:8554/12",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-vf transpose=1 -f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtsp://user:password@192.168.50.9:8554/12 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/facecam-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/facecam -r 5 -s 1296x2304 -vf transpose=1 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "facecam",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 480000,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 60000,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {
              "person": 150
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {
            "person": 150
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "front_door": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1296,
        "max_disappeared": 50,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 2304
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.0.210/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtmp://192.168.0.210/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/front_door -r 5 -s 2304x1296 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_door",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": [
              "0,1920,813,1920,1304,966,1049,433,0,1441"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": [
              "777,461,991,344,1384,319,1708,0,0,0,0,1084"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [
              "1822,718,1878,0,1324,0,0,0,0,1227,0,1920,402,1920,543,1675,498,1630,305,1460,82,1365,71,1259,156,1033,488,1159,729,1116,1187,782,1362,663"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 6000,
          "objects": [
            "person"
          ],
          "post_capture": 60,
          "pre_capture": 60,
          "required_zones": [
            "entrance"
          ],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {
              "person": 150
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 150,
          "mode": "all"
        },
        "retain_days": 150
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "entrance"
        ],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {
            "person": 150
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "entrance": {
          "coordinates": "2560,1920,2560,0,1661,0,1410,359,950,442,0,1253,0,1920",
          "filters": {},
          "objects": []
        },
        "faceshot_zone": {
          "coordinates": "1610,1920,1686,1440,1744,1122,856,1214,452,1920",
          "filters": {},
          "objects": []
        }
      }
    },
    "geovision": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1920,
        "max_disappeared": 50,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1080
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://192.168.50.1:8554/CH001.sdp",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-vf transpose=1 -f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtsp://192.168.50.1:8554/CH001.sdp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/geovision-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/geovision -r 5 -s 1080x1920 -vf transpose=1 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "geovision",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "359,1920,0,1920,0,0,44,0,190,0,310,0,111,633,239,1001,442,1165,434,1255"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 600,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {
              "person": 150
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {
            "person": 150
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "patiocam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 2160,
        "max_disappeared": 50,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 3840
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1",
          "-c:v",
          "h264_cuvid"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.50.10:1935/livemain",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v h264_cuvid -i rtmp://192.168.50.10:1935/livemain -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/patiocam-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/patiocam -r 5 -s 3840x2160 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "patiocam",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "3840,1403,3840,997,2266,870,2217,1193,2419,2160,3548,2160,3819,2160,3840,2160"
            ],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 600,
          "objects": [
            "person"
          ],
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {
              "person": 150
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {
            "person": 150
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/config/database/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": 50,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.0.15",
    "password": " password",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mosquitto"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
2022-04-07 11:52:30 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://192.168.0.14:5000/api/stats: 
2022-04-07 11:52:31 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'frigate/events': '{"before": {"id": "1649346684.397292-2jm8mp", "camera": "patiocam", "frame_time": 1649346694.255934, "snapshot_time": 1649346691.61069, "label": "person", "top_score": 0.84375, "false_positive": false, "start_time": 1649346684.397292, "end_time": null, "score": 0.84375, "box": [1427, 594, 2115, 1872], "area": 879264, "region": [573, 0, 2809, 2236], "stationary": false, "motionless_count": 1, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true}, "after": {"id": "1649346684.397292-2jm8mp", "camera": "patiocam", "frame_time": 1649346700.729431, "snapshot_time": 1649346691.61069, "label": "person", "top_score": 0.84375, "false_positive": false, "start_time": 1649346684.397292, "end_time": 1649346713.951904, "score": 0.57421875, "box": [465, 292, 899, 1378], "area": 471324, "region": [0, 15, 1872, 1887], "stationary": false, "motionless_count": 1, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true}, "type": "end"}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 47, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 283, in message_received
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 679, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1361, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1047, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.frigate_event. State max length is 255 characters.
```

### FFprobe output from your camera

```shell
I don't think this is relevant
```

### Frigate stats

```json
{"detection_fps":16.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":15.48,"pid":89468}},"facecam":{"camera_fps":5.0,"capture_pid":261,"detection_fps":9.7,"pid":247,"process_fps":5.0,"skipped_fps":0.0},"front_door":{"camera_fps":5.0,"capture_pid":251,"detection_fps":0.0,"pid":244,"process_fps":5.0,"skipped_fps":0.0},"geovision":{"camera_fps":5.1,"capture_pid":256,"detection_fps":0.0,"pid":245,"process_fps":5.1,"skipped_fps":0.0},"patiocam":{"camera_fps":5.1,"capture_pid":249,"detection_fps":6.4,"pid":242,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":4169.2,"mount_type":"tmpfs","total":4244.6,"used":75.4},"/media/frigate/clips":{"free":3258132.3,"mount_type":"cifs","total":5996476.9,"used":2738344.6},"/media/frigate/recordings":{"free":3258132.3,"mount_type":"cifs","total":5996476.9,"used":2738344.6},"/tmp/cache":{"free":9890.2,"mount_type":"tmpfs","total":10000.0,"used":109.8}},"temperatures":{},"uptime":91608,"version":"0.10.0-bfecee9"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Geovisions, Reolinks, No-names
