### ISSUE TITLE
[FR] Detection Short Clip Option for Notification Service

### ISSUE THREAD

**Issue by rjgrandy** [blakeblackshear/frigate#307]
Would be nice to have an option to output just the first 10 seconds (or definable duration) (plus some prerecord) of video from a detection of an object to send to a notification service.

I think currently we have prerecord option, it looks like you are going to implement a postrecord option, but this is a bit different.

My use case is: currently I have the best image sent to telegram after detection of an object, then I tell Blue Iris to record the event in HD until detection is complete. Then I use ffmpeg to cut the first 10s and optimize for sending over telegram. This works relatively well as I get a short video of the start of each detection over telegram which is much more useful than a static image. However it seems like this could be easily and better implemented in Frigate vs doing it through a Node Red flow and shell commands.

**Comment by blakeblackshear** [comment]
Thanks for describing your use case. I will be looking at post processing for clips in a future release as some other users have requested similar functionality. In addition, the next version will have the ability to do full HD recording from a separate stream, so you won't need to use Blue Iris for that.

**Comment by rogerquake** [comment]
This would be a great feature to have. It looks like HomeAssistant supports MP4s in notifications: https://companion.home-assistant.io/docs/notifications/notification-attachments/

It would be great to include a small clip (maybe 2 seconds before the object is detected) as part of the Events HTTP endpoint that currently provides the object screenshot in the latest beta. On my Nest for example, a very short looped clip is presented in the iOS notification.

**Comment by blakeblackshear** [comment]
This is still something I am considering

**Comment by rjgrandy** [comment]
Still would love this feature. I do this manually right now and it works ok, but I would think if it would get integrated into Frigate, the clip could be generated much faster, like in real time which would be much nicer and useful, instead of having to wait until the end of a detection event.

**Comment by HSB-collab** [comment]
I am looking for something similar and have failed to get it working. I wrote it up in the Home Assistant community (https://community.home-assistant.io/t/frigate-video-via-telegram/286852) but I am not getting any response, so I apologise for putting the same query in 2 different places. 
I am not sure if the latest version of Frigate (1.13) has implemented this feature or not, but I know it produces short videos of an incident and saves them in the /media/frigate/clips folder. I would like to be able to send the latest clip via Telegram when an event occurs.  I have tried the following configuration file but I am getting the errors listed below:
Automation configuration file:
```
alias: Frigate alerts
description: Person/car detection in cameras from Frigate
trigger:
  - platform: mqtt
    topic: frigate/events
condition: []
action:
   - service: notify.camera_alert_telegram
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected on
        {{trigger.payload_json["after"]["camera"]}} 
      data:
        video:
          - url: >-
              'http://ccab4aaf-frigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4'  
            caption: >-
              'Video of {{trigger.payload_json["after"]["label"]}} detected on
              {{ trigger.payload_json["after"]["camera"] }}'
mode: single
```
This gives the following errors:
```
Can't load data into ByteIO: No connection adapters were found for "'http://ccab4aaf-frigate:5000/api/events/1614904741.504328-knf1ic/Camera1/clip.mp4'"
Can't send file with kwargs: {'message': "'Video from person detected on Camera1'", 'url': "'http://ccab4aaf-frigate:5000/api/events/1614904741.504328-knf1ic/Camera1/clip.mp4'", 'caption': "'Video caption for person detected on Camera1'"}
```
Help would be greatly appreciated.
For completeness, I am running HassOS on a Raspberry Pi 4 with 4Gbyte of memory. My Home Assistant Core is version core-2021.3.0.
