### ISSUE TITLE
[Support]: Some events lasts from several minutes up to hours. max_seconds doesn't help

### ISSUE THREAD

**Issue by Homas** [blakeblackshear/frigate#3070]
### Describe the problem you are having

Some events lasts from several minutes up to several hours. I've explicitly set max_seconds but it didn't help. Retain mode "active_objects" and stationary set to "0" (IMO means disabled).
E.g. an event started @ 19:50:19 and still in progress @ 21:13:43. There was a car in a masked remote area but likely lights touched a parked car. There is no bounding box on a snapshot. There were no error logs reported starting 19:50 (see in the logs section).
Previously I've observed similar behavior during day light. I've several such events a day.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
"frontgaragerlc423": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": "-avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -rw_timeout 5000000 -analyzeduration 1000M -probesize 1000M",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.000.000/bcs/channel0_main.bcs?channel=0&stream=0&user=******&password=******",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtmp://192.168.000.000/bcs/channel0_ext.bcs?channel=0&stream=0&user=***&password=***",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -rw_timeout 5000000 -analyzeduration 1000M -probesize 1000M -i rtmp://192.168.000.000/bcs/channel0_main.bcs?channel=0&stream=0&user=***&password=*** -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontgaragerlc423-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -rw_timeout 5000000 -analyzeduration 1000M -probesize 1000M -i rtmp://192.168.000.000/bcs/channel0_ext.bcs?channel=0&stream=0&user=***&password=*** -c copy -f flv rtmp://127.0.0.1/live/frontgaragerlc423 -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "907,10,907,51,379,46,380,9"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "frontgaragerlc423",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "bird": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 10000,
            "min_score": 0.5,
            "threshold": 0.75
          }
        },
        "mask": "",
        "track": [
          "car",
          "motorcycle",
          "bicycle",
          "person",
          "dog",
          "cat",
          "bird"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "road",
            "wholeview"
          ],
          "retain": {
            "default": 90,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 3,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": 600,
        "quality": 70,
        "required_zones": [
          "road",
          "wholeview"
        ],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "parked_front": {
          "coordinates": "1,715,1,489,52,485,225,537,243,720",
          "filters": {},
          "objects": []
        },
        "parked_otherside": {
          "coordinates": "3,79,350,70,353,213,3,196",
          "filters": {},
          "objects": []
        },
        "road": {
          "coordinates": "1130,507,766,155,503,181,306,260,380,9,200,523,256,719",
          "filters": {},
          "objects": []
        },
        "wholeview": {
          "coordinates": "0,720,1280,720,1280,0,0,0",
          "filters": {},
          "objects": [
            "person",
            "bicycle",
            "dog",
            "cat",
            "bird"
          ]
        }
      }
    },
```

### Relevant log output

```shell
frigate    | [2022-04-08 19:44:22] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:40656]
frigate    | [2022-04-08 19:44:31] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:40656]
frigate    | [2022-04-08 20:52:45] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44546]
frigate    | [2022-04-08 20:52:52] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44546]
frigate    | [2022-04-08 21:00:52] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41410]
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
"frontgaragerlc423":{"camera_fps":5.1,"capture_pid":265,"detection_fps":0.2,"pid":231,"process_fps":5.1,"skipped_fps":0.0}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

reolink

### Any other information that may be helpful

I didn't observe such issue on previous major release 0.9.x

**Comment by NickM-27** [comment]
So there's a few things that are confused /  incorrect here [per the docs](https://docs.frigate.video/configuration/index):

1. `0` is the DEFAULT value for `stationary -> interval` and is the default behavior to have it enabled. This means that once an object is seen as stationary it will not be continually checked. Any value greater will just be the nth frame that a detection will be done to see if the object is still there. 
2. `max_seconds` has to do with the amount of recording that is kept for the event, not how long the actual event lasts.

If you truly do want to completely disable stationary object tracking, then you will want to use the `stationary -> max_frames` option.

**Comment by Homas** [comment]
Yes. the doc is very confusing.
1. Right now it says that with "0" it will never run on stationary objects. I've a few parked cars, some of them out of detection zones, some areas are hidden. 
Other problem is that an object (car, person) can disappear completely from a cam but an event will not be completed to some undefined time in the future. I'll try to find such event and upload it.
3. Ok. It is better described in the doc in comparing with other place where I found this setting (don't remember where).
4. yes. It is clear

'stationary -> max_frames' is not an intuitive setting to disable the feature.

Thank you for you help.

**Comment by NickM-27** [comment]
> Yes. the doc is very confusing.
> 
> 1. Right now it says that with "0" it will never run on stationary objects. I've a few parked cars, some of them out of detection zones, some areas are hidden.
>    Other problem is that an object (car, person) can disappear completely from a cam but an event will not be completed to some undefined time in the future. I'll try to find such event and upload it.
> 2. Ok. It is better described in the doc in comparing with other place where I found this setting (don't remember where).
> 3. yes. It is clear
> 
> 'stationary -> max_frames' is not an intuitive setting to disable the feature.
> 
> Thank you for you help.

1. Right, meaning once an object is stationary detection will not be run on it. While an event will be somewhat helpful, most helpful would be a screenshot of the camera debug screen while this is occurring. That way we can tell what the software is actually seeing.

The `max_frames` is the max amount of frames an object can be stationary for before it is considered a false positive and forcibly removed until motion occurs and it is detected again. Overall, it isn't clear if you are talking about true positive events that are lasting longer than you'd like for stationary objects, or if objects are leaving the frame but remaining to be detected.

**Comment by Homas** [comment]
Here is an example of such event "in progress". In this case there were 2 cars with a similar color:
- the parked car is not in the detection zone;
- moving truck is in the detection zone.
and it is just one of the examples. It is hard to catch in progress such events (I'm not looking on cameras 24/7). But will provide more.
<img width="1313" alt="Screenshot 2022-04-09 at 13 18 54" src="https://user-images.githubusercontent.com/13776103/162590395-a8394257-12bc-4cf9-880b-f8d012d70562.png">
<img width="905" alt="Screenshot 2022-04-09 at 13 19 19" src="https://user-images.githubusercontent.com/13776103/162590403-ff2d3cad-bbc7-443f-94f1-84c116edc574.png">
<img width="516" alt="Screenshot 2022-04-09 at 13 19 25" src="https://user-images.githubusercontent.com/13776103/162590412-e1112928-4e83-439f-8534-e77634011926.png">

**Comment by NickM-27** [comment]
> the parked car is not in the detection zone

That is false. The car across the street is in the blue zone. Remember, zones are based on the bottom center of the bounding box, not how much the bounding box overlaps with the zone.

**Comment by Homas** [comment]
> ones are based on the bottom center of the bounding box
Sorry I didn't get it. I mean that the blue zone is the zone I want to detect cars.
The moving car on the road triggered the detection of the parked road. It did happen before but because where were no support of stationary objects detections -they didn't last long.
Here is the config for this cam.
```
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 90
          mode: active_objects
        required_zones:
          - road
          - wholeview
    mqtt:
      required_zones:
        - road
        - wholeview
    snapshots:
      enabled: True
    motion:
      mask:
      - 906,0,903,53,368,48,364,0 #time
      - 1280,202,1232,202,1162,140,1069,121,945,0,1280,0 #tree
      #- 0,720,880,720,845,668,665,564,566,540,302,574,382,644,0,542 #bushes next to the den's window
    zones:
      parked_front:
        coordinates: 958,26,1088,162,814,160,410,176,425,19
        objects:
          - person
          - dog
          - cat
          - bird
      road:
        coordinates: 213,59,414,24,421,174,0,231,0,124
        objects:
          - car
          - motorcycle
          - bicycle
      wholeview:
        coordinates: 0,720,1280,720,1280,0,0,0
        objects:
          - person
          - bicycle
          - dog
          - cat
          - bird
    objects:
      track:
        - car
        - motorcycle
        - bicycle 
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          min_area: 10000
          threshold: 0.75
```

I also observe other issue. A snapshot on a video belongs to previous event.
See bellow:
- An event with a red pickup contains a video with the blue subaru
- An event with a blue subaru contains a video with the usps car

<img width="1344" alt="Screenshot 2022-04-09 at 13 36 21" src="https://user-images.githubusercontent.com/13776103/162590859-82e6f02a-8141-438a-8b6b-878569aaa411.png">

<img width="896" alt="Screenshot 2022-04-09 at 13 36 35" src="https://user-images.githubusercontent.com/13776103/162590868-e377e707-eaeb-4bac-829b-199f55c8069f.png">

<img width="788" alt="Screenshot 2022-04-09 at 13 36 47" src="https://user-images.githubusercontent.com/13776103/162590887-a36e9fa9-189e-4032-bbf8-81d7338a84fa.png">
