### ISSUE TITLE
[Support]: Latest Home Assistant core stops recognicing TPU

### ISSUE THREAD

**Issue by thundergreen** [blakeblackshear/frigate#3072]
### Describe the problem you are having

Hello I upgraded to Home Assistant OS 8.0.rc1 and now i get this error message:

Is that addon related or Home assistant core?

### Version

0.10.0-e5714f5

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.41
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password: hass
  stats_interval: 306

detectors:
  coral:
    type: edgetpu
    device: pci

logger:
  default: info
  logs:
    frigate.event: debug

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 10
  mode: continuous

ffmpeg:
  global_args: 
    - -hide_banner 
    - -loglevel 
    - warning
  # input_args:
  #   - -avoid_negative_ts
  #   - make_zero
  #   - -fflags
  #   - +genpts+discardcorrupt
  #   - -rtsp_transport
  #   - tcp
  #   - -stimeout
  #   - '5000000'
  #   - -use_wallclock_as_timestamps
  #   - '1'
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    # Optional: output args for clips streams (default: shown below)

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  max_disappeared: 5

objects:
  track:
    - person
#    - car
    - cat
    - dog
    - truck

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: []
    retain:
      default: 1
      objects:
        person: 1

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  height: 175
  required_zones: []
  retain:
    default: 1
    objects:
      person: 1



rtmp:
  enabled: False
live:
  height: 720

  quality: 10


timestamp_style:
  position: "tl"
  format: "%d.%m.%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

  effect: shadow

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@40.40.40.224:88/videoMain
          roles:
            - detect
#            - rtmp
            - record
            - clips
    rtmp:
      enabled: False
    best_image_timeout: 60
    motion:
      mask:
        - 778,335,1280,347,1280,65,936,75,0,66,0,720,431,720,777,720

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

## ------------------------------------------------------------------------------------------------------------------------- ##
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.1.241
          roles:
            - detect
#            - rtmp
            - record
            - clips
    rtmp:
      enabled: False
    best_image_timeout: 60
    motion:
      mask:
        - 1280,720,1280,236,1192,242,921,313,822,336,788,358,704,487,767,720
        - 502,381,0,332,0,720,159,720,245,720,414,720
        - 127,218,387,217,351,377,141,375
        - 1280,215,1280,338,864,328,862,218
        - 1280,151,1280,405,0,397,0,149,319,145,601,145
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

#   entrance:
#     ffmpeg:
#       input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
#       output_args:
#         record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
#         rtmp: -c:v libx264 -an -f flv
#       inputs:
#         - path: http://40.40.40.246:8080
#           roles:
#             - detect
# #            - record
#             - rtmp
#     detect:
#       width: 640
#       height: 480
#     objects:
#       track:
#         - person
#         # - car
#     mqtt:
#       enabled: True
#       timestamp: True
#       bounding_box: True
#       crop: True
#       height: 270
#       quality: 70
#       required_zones: []

#   server:
#     ffmpeg:
#       input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
#       output_args:
#         record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
#         rtmp: -c:v libx264 -an -f flv
#       inputs:
#         - path: http://40.40.40.245:8080
#           roles:
#             - detect
# #            - record
#             - rtmp
#     detect:
#       width: 640
#       height: 480
#     objects:
#       track:
#         - person
# #        - car
#     mqtt:
#       enabled: True
#       timestamp: True
#       bounding_box: True
#       crop: True
#       height: 270
#       quality: 70
#       required_zones: []

  garden_upstairs:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@40.40.40.92:554/stream1
          roles:
            - detect
#            - rtmp
            - record
            - clips
    rtmp:
      enabled: False
    best_image_timeout: 60

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []


## ------------------------------------------------------------------------------------------------------------------------- ##

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://40.40.40.220:554/media/stream1
          roles:
            - detect
#            - rtmp
            - record
            - clips
    rtmp:
      enabled: False
    best_image_timeout: 60

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

## ------------------------------------------------------------------------------------------------------------------------- ##

  garden:
    ffmpeg:
      inputs:
        - path: rtsp://40.40.40.14:554/media/stream1
          roles:
            - detect
#            - rtmp
            - record
            - clips
    rtmp:
      enabled: False
    best_image_timeout: 60

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []
```
```


### Relevant log output

```shell
[2022-04-09 14:55:17] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 44, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```
```


### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Foscam, Xiaomi, Tapo
