### ISSUE TITLE
[Support]: RuntimeError with CPU detector

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#3085]
### Describe the problem you are having

I'm trying to run Frigate on a RPI4/2GB using a CPU detector and a single MJPEG camera, but I get an exception (non fatal) and then a watchdog error causes it to exit.

The Frigate UI works for a bit and I can see a single frame of the MJPEG camera (but clicking it gives nothing). Note that I had to add `-c:v mjpeg` to the ffmpeg options to get anything to show at all (as per #2184).

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: xxx
  # Optional: port (default: shown below)
  port: 1883
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2

# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320
  # Optional: Label name modifications. These are merged into the standard labelmap.
  labelmap:
    2: vehicle


# Required
cameras:
  # Required: name of the camera
  livingroom:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        - path: http://xxx/?action=stream
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - rtmp
          # Optional: stream specific global args (default: inherit)
          # global_args:
          # Optional: stream specific hwaccel args (default: inherit)
          # hwaccel_args:
          # Optional: stream specific input args (default: inherit)
          input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      # Optional: camera specific global args (default: inherit)
      # global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      # hwaccel_args:
      # Optional: camera specific input args (default: inherit)
      # input_args:
      # Optional: camera specific output args (default: inherit)
      # output_args:

    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60


...
```

### Relevant log output

```shell
frigate  | [2022-04-11 19:03:49] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-04-11 19:03:49] frigate.app                    INFO    : Output process started: 218
frigate  | [2022-04-11 19:03:49] detector.cpu                   INFO    : Starting detection process: 217
frigate  | [2022-04-11 19:03:49] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | Process detector:cpu:
frigate  | [2022-04-11 19:03:49] frigate.app                    INFO    : Camera processor started for livingroom: 221
frigate  | [2022-04-11 19:03:49] ws4py                          INFO    : Using epoll
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate  |     self.run()
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate  |     self._target(*self._args, **self._kwargs)
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate  |     object_detector = LocalObjectDetector(
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
frigate  |     self.interpreter.allocate_tensors()
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
frigate  |     return self._interpreter.AllocateTensors()
frigate  | RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.
frigate  |
frigate  | [2022-04-11 19:03:49] frigate.app                    INFO    : Capture process started for livingroom: 224
frigate  | [2022-04-11 19:03:49] frigate.mqtt                   DEBUG   : MQTT connected
frigate  | [2022-04-11 19:03:49] ws4py                          INFO    : Using epoll
frigate  | [2022-04-11 19:03:49] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)
frigate  | [2022-04-11 19:03:49] peewee                         DEBUG   : ('UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)', [30, None])
frigate  | [2022-04-11 19:03:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/livingroom/recordings/state.
frigate  | [2022-04-11 19:03:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/livingroom/snapshots/state.
frigate  | [2022-04-11 19:03:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/livingroom/detect/state.
frigate  | [2022-04-11 19:03:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate  | [2022-04-11 19:03:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate  | [2022-04-11 19:04:09] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Generic MJPEG
