### ISSUE TITLE
[Support]:  

### ISSUE THREAD

**Issue by balvant813** [blakeblackshear/frigate#3104]
### Describe the problem you are having

I am using Frigate in Homeassistant, but I get following error when adding stationary object detection
--- Error in Log ---
 cameras -> drivewaysouth66 -> detect -> stationary
  extra fields not permitted (type=value_error.extra)
-

### Version

Frigate NVR Current version: 2.3  

### Frigate config file

```yaml
# https://www.youtube.com/watch?v=T0g3EnpYP-E&t=683s
mqtt:
  # Required: host name
  host: xxxxxxxxx.100
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate107
  # Optional: user
  user: xxxxxxxxxxxxxx
  # Optional: password
  password: xxxxxxxxxxxxx

  ## Optional: interval in seconds for publishing stats (default: shown below)
  # stats_interval: 60
cameras:
  drivewaysouth66:
    ffmpeg:
      inputs:
      #  video path
        - path: rtsp://xxxxxxxxxxxx/user=xxxx_password=xxxxx_channel=1_stream=1.sdp
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxxxxxxxxx/user=xxxxxxxx_password=xxxxxxxxxxx_channel=1_stream=0.sdp?real_stream
          roles:
            - record
    detect:
      width: 704 #  FROM VLC -> Tools -> codec info -> codec or (ctrl-j)
      height: 480
      fps: 5
      stationary:
        interval: 10
    snapshots:
      enabled: True
      timestamp: True
      height: 720
      retain:
        default: 5
    # Optional: Per object retention days
    objects:
      track:
        - person
        - bicycle
        - car
    motion:
      mask:
        - 0,0,368,0,704,0,704,119,704,263,539,125,373,66,0,167
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 20
detectors:
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-04-14 11:00:26] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> drivewaysouth66 -> detect -> stationary
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
I am not sure how or which OS I run this ...
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision
