### ISSUE TITLE
Cannot start add-on Frigate NVR (Full Access)

### ISSUE THREAD

**Issue by kajmaj** [blakeblackshear/frigate#3106]
### Describe the problem you are having

I have installed the add-on Frigate NVR (Full Access) long time ago (RPi 4, HASSOS). 
Everything (3 cameras) was working well till last core update to core-2022.4.3. 
Now I am not able to start Frigate either manually or automatically after reboot, with no related error messages in the HA logger and no log in add-on as well. Nothing happens If I "press" start button in the add-on UI.
I did not modify frigate.yml since I've added last camera ie. 2 months al least. 
I tried to reboot HA, restart RPi, unistall and reinstall add-on, revert back to core_2022.3.8 from backup with no result.

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.107
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: ub32A74.
  stats_interval: 60

record:
  retain:
    days: 3
birdseye: 
  enabled: false

cameras:
  garaz:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.11:554/11
          roles:
            - detect
            - rtmp
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 15
    record: 
      enabled: False

  vchod:
    ffmpeg:
      inputs:
         - path: rtsp://user:password@192.168.1.13:554/live/ch0    #ch0 
           roles:
            - detect
            - rtmp
            - record
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 5
    live:
      height: 720
      quality: 15
    record:
      retain:
        days: 3  
      enabled: true

  dvere:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.16:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - detect
            - rtmp
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 5
    live:
      height: 600
      quality: 15
    record: 
      enabled: False

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version N-103134-gaccfd015e3-g65fdc0e589+2 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration:  --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-librtmp --enable-mbedtls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads
  libavutil      57.  3.100 / 57.  3.100
  libavcodec     59.  4.100 / 59.  4.100
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  1.103 /  8.  1.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Dahou Imou Turret
