### ISSUE TITLE
[Support]: Many errors, but Frigate working.

### ISSUE THREAD

**Issue by Marcos-kp** [blakeblackshear/frigate#3107]
### Describe the problem you are having

I am experiencing a couple Error from the Supervisor and Core Logs.
Since the frigate service appears to be working really well, but my HA is having some issues, I'm not sure if Frigate might be causing some of my issues.

My HA supervisor logs retrieve me a weird output: WARNING (SyncWorker_6) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)
The weird thing here is that I only have the official Add-on installed (and without Full Acess). I already tried to install and uninstall all other Frigate Add-ons, but the logs remain.

### Version

3.1 -  0.10.1

### Frigate config file

```yaml
mqtt:
  host: xxx
  user: xxx
  password: xxx

cameras:
  Social:
    ffmpeg:
      inputs:
        - path: rtsp://xxx@xxx/cam/realmonitor?channel=5&subtype=0
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.65
    motion:
      threshold: 25
      contour_area: 30
      mask:
        - 502,69,836,79,835,425,1089,464,1049,134,1162,128,1280,256,1280,0,0,0,0,720,262,720,143,461
    zones:
      zone_calcada_social:
        coordinates: 1280,720,1280,89,907,96,878,260,847,542,829,720
        objects:
          - bicycle
          - motorcycle
      zone_portao_social:
        coordinates: 843,42,514,21,0,23,0,593,0,720,974,720,959,444,846,425
        objects:
          - person
  Portao:
    ffmpeg:
      inputs:
        - path: rtsp://Hassio:xxx@xxx/cam/realmonitor?channel=2&subtype=0
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - car
      filters:
        car:
          threshold: 0.56
        motorcycle:
          threshold: 0.65  
    motion:
      threshold: 50
      contour_area: 40
      mask:
        - 700,0,995,720,1280,720,1280,0,0,0,0,394,63,251,192,86,427,33
    zones:
      zone_calcada:
        coordinates: 0,506,0,720,302,720,356,454,819,433,884,0,310,0,236,70
        objects:
          - bicycle
          - motorcycle
          - car
      zone_portao:
        coordinates: 341,720,1055,720,747,0,645,418,391,428
        objects:
          - person

detect:
  width: 1280
  height: 720
  fps: 5

snapshots:
  enabled: True
  bounding_box: True
  required_zones:
    - zone_portao
    - zone_calcada
    - zone_calcada_social
    - zone_portao_social
  retain:
    default: 3

record:
  enabled: True
  retain:
    days: 0
  events:
    required_zones:
      - zone_portao
      - zone_calcada
      - zone_calcada_social
      - zone_portao_social
    pre_capture: 2
    post_capture: 2
    max_seconds: 120
    retain:
      default: 3

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

birdseye:
  enabled: False
```

### Relevant log output

```shell
Core Logs:

Timeout error fetching information from http://ccab4aaf-frigate:5000/api/stats:

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Try again]

Supervisor Logs:
WARNING (SyncWorker_6) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)
```

### FFprobe output from your camera

```shell
--
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Intelbras
