### ISSUE TITLE
[Config Support]: Puzzled on how to connect frigate container on Coral Dev board to a separate host running HA

### ISSUE THREAD

**Issue by the-bort-the** [blakeblackshear/frigate#3111]
### Describe the problem you are having

Currently trying to set up frigate on a separate Coral Dev Board and connect to an existing Home Assistant running on another separate host, a raspberry pi 4. I currently have frigate installed on the rpi as an add-in, but would like to leverage the TPU. I have Docker installed and a frigate container running/restarting, with what I believe is a valid config. It restarts every minute, as it can't connect to the rpi host running Home Assistant. How might I accomplish that connectivity?

rpi running home assistant, HACS, working mqtt server - 192.168.0.a
coral dev board trying to run frigate container - 192.168.0.b

### Version

2.3 is running in the add-in

### Frigate config file

```yaml
mqtt:
  host: 172.30.33.0 # host running mqtt in separate rpi host
  user: mqtt_user
  password: secret_pwd
  port: 1883
  topic_prefix: frigate
  client_id: frigate
detectors:
  coral:
    type: edgetpu
    device: ""
cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://secret_user:secret_pwd@192.168.0.X:554/11
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-04-17 00:49:42] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-04-17 00:49:42] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-04-17 00:49:42] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 101] Network is unreachable
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Frigate stats

```json
No stats as of yet.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Dev Board

### Any other information that may be helpful

Wishing to decommission frigate add-in within current Home Assistant installation in favor of running a standalone Coral Dev Board where I'd prefer to have a container run frigate.
