### ISSUE TITLE
[Support]: Homeassistant integration - custom domain https url instead of localip:5000

### ISSUE THREAD

**Issue by noenthu** [blakeblackshear/frigate#3119]
### Describe the problem you are having

Homeassistant running on docker with SSL termination handled using Traefik with letsencrypt certificates.
Frigate running on same subnet using docker compose with SSL termination handled by Traefik running on the above host. 

In Homeassistant, when trying to add Frigate, instead of passing localip:5000, is it possible to use the FQDN? Currently homeassistant is unable to add the frigate instance unless I provide the localip.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: mqtt.local.<domain>.tech
  port: 8883
  user: "user"
  password: "userspass"
  tls_ca_certs: /etc/ssl/certs/ca-certificates.crt

logger:
  default: debug

cameras:
  reo1:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        #- path: rtsp://admin:password@192.168.107.91:554/h264Preview_01_sub
        - path: http://192.168.107.91/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password
          roles:
            - detect
        #- path: rtsp://admin:password@192.168.107.91:554/h264Preview_01_main
        - path: http://192.168.107.91/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 7
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        objects:
          - person
        retain:
          default: 1
          mode: motion
          objects:
            person: 2
    objects:
      track:
        - person
detectors:
  cpu1:
    type: cpu
    num_threads: 3
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink Zoom E1
