### ISSUE TITLE
[Config Support]:  Connection reset by peer | No space left on device

### ISSUE THREAD

**Issue by miczlo** [blakeblackshear/frigate#3127]
### Describe the problem you are having

Every now and then I get a black recording in the browser with just sound.
If I go to view the files I have the .mp4 files but the length is 0:00 and they are more like snapshots..

When that happens I get the following:
```
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : av_interleaved_write_frame(): Connection reset by peer
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x555e70f7d600] Failed to update header with correct duration.
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x555e70f7d600] Failed to update header with correct filesize.
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : Error writing trailer of rtmp://127.0.0.1/live/back_gate: Connection reset by peer
frigate    | [2022-04-20 10:54:12] watchdog.back_gate             INFO    : Terminating the existing ffmpeg process...
```

I also get 

```
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : av_interleaved_write_frame(): No space left on device
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : [segment @ 0x55b038b4c080] Failure occurred when ending segment '/tmp/cache/back_gate-20220420143541.mp4'
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : Error writing trailer of /tmp/cache/back_gate-%Y%m%d%H%M%S.mp4: No space left on device
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x55b038b4dd00] Failed to update header with correct duration.
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x55b038b4dd00] Failed to update header with correct filesize.
frigate    | [2022-04-20 14:35:48] watchdog.back_gate             INFO    : Terminating the existing ffmpeg process...
frigate    | [2022-04-20 14:35:48] watchdog.back_gate             INFO    : Waiting for ffmpeg to exit gracefully...
```

But not sure if these are related 

I don't know what's running out of space:

```
Filesystem      1K-blocks       Used  Available Use% Mounted on
udev              8120060          0    8120060   0% /dev
tmpfs             1628888       8508    1620380   1% /run
/dev/sda2       458866824    6273300  429210896   2% /
tmpfs             8144432          0    8144432   0% /dev/shm
tmpfs                5120          4       5116   1% /run/lock
/dev/sda1          523244       3484     519760   1% /boot/efi
/dev/sdc1      5813176856 2113004448 3407129976  39% /media/usb-drive
tmpfs             1628884         64    1628820   1% /run/user/115
tmpfs             1628884         52    1628832   1% /run/user/1000
```
I have frigate mapped to /media/usb-drive

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.10.0-amd64
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /home/michal/frigate/config/config.yml:/config/config.yml:ro
      - /media/usb-drive/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
```

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
#Only relevant camera below
mqtt:
  host: myMQTTHost
  

detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  fps: 5
    
cameras:

  back_gate:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: http://CAMERA_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=TOP_SECRET
          roles:
            - record
            - rtmp
        - path: http://CAMERA_IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=TOP_SECRET
          roles:
            - detect
    zones:
      tree:
        coordinates: 0,720,672,720,1015,450,922,355,588,304,440,245,465,98,269,56,232,248,0,474
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_area: 5000
            max_area: 60000 #10260
          cat:
            min_area: 10000 #12496
            max_area: 30000 #21160
          dog:
            min_area: 10000 #14382
            max_area: 100000 #47685

      gate:
        coordinates: 308,720,1280,720,1280,103,1167,103,1163,256,1019,361
        objects:
          - person
          - cat
          - bird
          - dog
        filters:
          person:
            min_area: 8000 #74930, 
            max_area: 350000 #257925
          cat:
            min_area: 10000
            max_area: 500000
          bird:
            min_area: 5000
      path_gate:
        coordinates: 1126,280,995,360,726,344,597,319,522,280,572,227
        objects:
          - person
          - cat
          - car
        filters:
          person:
            min_area: 1200
            max_area: 5500
          cat:
            min_area: 5000
          car:
            max_area: 300000
    motion:
      mask:
        - 427,0,450,93,698,149,1143,144,1280,0
    detect:
     # width: 896
     # height: 512
      fps: 7

    

          
objects:
  track:
    - person
    - car
    - cat
    
    

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
      # Optional: crop the snapshot (default: shown below)
  crop: False

      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
      # Optional: Camera override for retention settings (default: global values)
  retain:
        # Required: Default retention days (default: shown below)
    default: 60
        # Optional: Per object retention days
    objects:
      person: 90
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p         
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    max_seconds: 500
    pre_capture: 15
    post_capture: 15
    retain:
      default: 45
      mode: active_objects
```

### Relevant log output

```shell
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : av_interleaved_write_frame(): Connection reset by peer
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x555e70f7d600] Failed to update header with correct duration.
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x555e70f7d600] Failed to update header with correct filesize.
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : Error writing trailer of rtmp://127.0.0.1/live/back_gate: Connection reset by peer
frigate    | [2022-04-20 10:54:12] watchdog.back_gate             INFO    : Terminating the existing ffmpeg process...

frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : av_interleaved_write_frame(): No space left on device
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : [segment @ 0x55b038b4c080] Failure occurred when ending segment '/tmp/cache/back_gate-20220420143541.mp4'
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : Error writing trailer of /tmp/cache/back_gate-%Y%m%d%H%M%S.mp4: No space left on device
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x55b038b4dd00] Failed to update header with correct duration.
frigate    | [2022-04-20 14:35:48] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x55b038b4dd00] Failed to update header with correct filesize.
frigate    | [2022-04-20 14:35:48] watchdog.back_gate             INFO    : Terminating the existing ffmpeg process...
frigate    | [2022-04-20 14:35:48] watchdog.back_gate             INFO    : Waiting for ffmpeg to exit gracefully...
```

### Frigate stats

```json
{"back_color":{"camera_fps":0.0,"capture_pid":240,"detection_fps":0.0,"pid":228,"process_fps":0.0,"skipped_fps":0.0},"back_gate":{"camera_fps":7.1,"capture_pid":267,"detection_fps":8.1,"pid":237,"process_fps":7.1,"skipped_fps":0.0},"back_right":{"camera_fps":5.1,"capture_pid":239,"detection_fps":4.6,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"back_tapo":{"camera_fps":5.1,"capture_pid":242,"detection_fps":9.0,"pid":229,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":21.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.31,"pid":217}},"front_left":{"camera_fps":7.0,"capture_pid":245,"detection_fps":0.0,"pid":231,"process_fps":7.0,"skipped_fps":0.0},"front_left_HighRes":{"camera_fps":5.0,"capture_pid":250,"detection_fps":0.0,"pid":232,"process_fps":5.0,"skipped_fps":0.0},"front_porch":{"camera_fps":7.1,"capture_pid":258,"detection_fps":0.0,"pid":236,"process_fps":7.1,"skipped_fps":0.0},"front_right":{"camera_fps":7.0,"capture_pid":256,"detection_fps":0.0,"pid":234,"process_fps":7.0,"skipped_fps":0.0},"front_right_HighRes":{"camera_fps":5.1,"capture_pid":252,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":518.3,"mount_type":"tmpfs","total":536.9,"used":18.5},"/media/frigate/clips":{"free":3496750.8,"mount_type":"ext4","total":5952693.1,"used":2155866.9},"/media/frigate/recordings":{"free":3496750.8,"mount_type":"ext4","total":5952693.1,"used":2155866.9},"/tmp/cache":{"free":951.3,"mount_type":"tmpfs","total":1000.0,"used":48.7}},"temperatures":{},"uptime":15226,"version":"0.10.0-bfecee9"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

This camera sits behind a powerline adapter and only this one experiences both the issues mentioned
Other cameras experience the space problem
