### ISSUE TITLE
[Config Support]: Connection reset by peer

### ISSUE THREAD

**Issue by miczlo** [blakeblackshear/frigate#3128]
### Describe the problem you are having

Every now and then I get a black recording in the browser with just sound.
If I go to view the files I have the .mp4 files but the length is 0:00 and they are more like snapshots.
I have 2 cameras with this config but this one produces these errors constantly and sometimes they result in broken recordings.

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
#Only relevant camera below
mqtt:
  host: myMQTTHost
  

detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  fps: 5
    
cameras:

  back_gate:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: http://CAMERA_IP/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=TOP_SECRET
          roles:
            - record
            - rtmp
        - path: http://CAMERA_IP/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=TOP_SECRET
          roles:
            - detect
    zones:
      tree:
        coordinates: 0,720,672,720,1015,450,922,355,588,304,440,245,465,98,269,56,232,248,0,474
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_area: 5000
            max_area: 60000 #10260
          cat:
            min_area: 10000 #12496
            max_area: 30000 #21160
          dog:
            min_area: 10000 #14382
            max_area: 100000 #47685

      gate:
        coordinates: 308,720,1280,720,1280,103,1167,103,1163,256,1019,361
        objects:
          - person
          - cat
          - bird
          - dog
        filters:
          person:
            min_area: 8000 #74930, 
            max_area: 350000 #257925
          cat:
            min_area: 10000
            max_area: 500000
          bird:
            min_area: 5000
      path_gate:
        coordinates: 1126,280,995,360,726,344,597,319,522,280,572,227
        objects:
          - person
          - cat
          - car
        filters:
          person:
            min_area: 1200
            max_area: 5500
          cat:
            min_area: 5000
          car:
            max_area: 300000
    motion:
      mask:
        - 427,0,450,93,698,149,1143,144,1280,0
    detect:
     # width: 896
     # height: 512
      fps: 7

    

          
objects:
  track:
    - person
    - car
    - cat
    
    

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
      # Optional: crop the snapshot (default: shown below)
  crop: False

      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
      # Optional: Camera override for retention settings (default: global values)
  retain:
        # Required: Default retention days (default: shown below)
    default: 60
        # Optional: Per object retention days
    objects:
      person: 90
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p         
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    max_seconds: 500
    pre_capture: 15
    post_capture: 15
    retain:
      default: 45
      mode: active_objects
```

### Relevant log output

```shell
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : av_interleaved_write_frame(): Connection reset by peer
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x555e70f7d600] Failed to update header with correct duration.
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : [flv @ 0x555e70f7d600] Failed to update header with correct filesize.
frigate    | [2022-04-20 10:54:12] ffmpeg.back_gate.record_rtmp   ERROR   : Error writing trailer of rtmp://127.0.0.1/live/back_gate: Connection reset by peer
frigate    | [2022-04-20 10:54:12] watchdog.back_gate             INFO    : Terminating the existing ffmpeg process...
```

### Frigate stats

```json
{"back_color":{"camera_fps":0.0,"capture_pid":240,"detection_fps":0.0,"pid":228,"process_fps":0.0,"skipped_fps":0.0},"back_gate":{"camera_fps":7.1,"capture_pid":267,"detection_fps":8.1,"pid":237,"process_fps":7.1,"skipped_fps":0.0},"back_right":{"camera_fps":5.1,"capture_pid":239,"detection_fps":4.6,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"back_tapo":{"camera_fps":5.1,"capture_pid":242,"detection_fps":9.0,"pid":229,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":21.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.31,"pid":217}},"front_left":{"camera_fps":7.0,"capture_pid":245,"detection_fps":0.0,"pid":231,"process_fps":7.0,"skipped_fps":0.0},"front_left_HighRes":{"camera_fps":5.0,"capture_pid":250,"detection_fps":0.0,"pid":232,"process_fps":5.0,"skipped_fps":0.0},"front_porch":{"camera_fps":7.1,"capture_pid":258,"detection_fps":0.0,"pid":236,"process_fps":7.1,"skipped_fps":0.0},"front_right":{"camera_fps":7.0,"capture_pid":256,"detection_fps":0.0,"pid":234,"process_fps":7.0,"skipped_fps":0.0},"front_right_HighRes":{"camera_fps":5.1,"capture_pid":252,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":518.3,"mount_type":"tmpfs","total":536.9,"used":18.5},"/media/frigate/clips":{"free":3496750.8,"mount_type":"ext4","total":5952693.1,"used":2155866.9},"/media/frigate/recordings":{"free":3496750.8,"mount_type":"ext4","total":5952693.1,"used":2155866.9},"/tmp/cache":{"free":951.3,"mount_type":"tmpfs","total":1000.0,"used":48.7}},"temperatures":{},"uptime":15226,"version":"0.10.0-bfecee9"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Not sure if it's config or the fact it's behind a powerline adapter maybe

**Comment by NickM-27** [comment]
Did you mean to duplicate your other issue? This should all be covered under the first one

**Comment by miczlo** [comment]
> Did you mean to duplicate your other issue? This should all be covered under the first one

Yes. I initially had it together but I think these are 2 different issues.

The other one with space I had on all cameras and might well have to do with the tmpfs which was underprovisioned.
This one only occurs on this one camera.

**Comment by skaa** [comment]
I have the same issue. Camera and frigate restart doesn't help. Viewing this stream from camera with VLC is ok.
Using latest Docker image from 2022-03-11 07:06:55.

**Comment by miczlo** [comment]
I have just added another camera and am getting connection reset by peer as well.
It's a different camera with different config on a different connection
```
back_left:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@myIP:554/Streaming/Channels/102/?transportmode=unicast.sdp
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@myIP:554/Streaming/Channels/101/?transportmode=unicast.sdp
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - cat
```
