### ISSUE TITLE
[Config Support]: Cant connect to Frigate Docker from HA VM

### ISSUE THREAD

**Issue by bipple294** [blakeblackshear/frigate#3139]
### Describe the problem you are having

I get the following error message when attempting to launch the frigate sidebar from within HA:

[error] 352#352: *11 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.30.32.2, server: ccab4aaf-frigate-proxy, request: "GET // HTTP/1.1", upstream: "http://10.14.41.249:5000//", host: "10.14.41.15:8123", referrer: "http://10.14.41.15:8123/hassio"

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.14.41.15
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: bipple
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  coral1:
   type: edgetpu
   device: pci:0
  coral2:
   type: edgetpu
   device: pci:1

ffmpeg:
  input_args: 
    - -c:v 
    - h264_cuvid

detect:  
  width: 640
  height: 480
  fps: 5

objects:
  track:
    - person
    - car
    - airplane
    - cat
    - dog
    - snowboard

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.24.7.101:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - rtmp
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.24.7.101:554/Streaming/Channels/102/?transportmode=unicast
          roles:
            - detect
```

### Relevant log output

```shell
[error] 352#352: *11 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.30.32.2, server: ccab4aaf-frigate-proxy, request: "GET // HTTP/1.1", upstream: "http://10.14.41.249:5000//", host: "10.14.41.15:8123", referrer: "http://10.14.41.15:8123/hassio"
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

M.2
