### ISSUE TITLE
[Support]: ffmpeg command leaks passwords

### ISSUE THREAD

**Issue by cliffjao** [blakeblackshear/frigate#3145]
### Describe the problem you are having

Using `ps`, you can see the command with the password embedded. I don't know that there's an easy way around this, but flagging it here just in case.

root      798363  3.0  0.4 1136472 37744 ?       Ssl  Apr24  34:05 ffmpeg -hide_banner -loglevel warning -hwaccel qsv -qsv_device /dev/dri/renderD128 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:**REDACTED_PASSWORD**@192.168.101.183/cam/realmonitor?channel=1&subtype=1 -r 5 -s 704x480 -f rawvideo -pix_fmt yuv420p pipe:

### Version

0.10.1

### Frigate config file

```yaml
backyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED_PASSWORD@192.168.101.183/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:REDACTED_PASSWORD@192.168.101.183/
          roles:
            - record
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
