### ISSUE TITLE
[Support]: Run Frigate without MQTT broker

### ISSUE THREAD

**Issue by shoutbc** [blakeblackshear/frigate#3153]
### Describe the problem you are having

Is it possible to disable MQTT? I am using Frigate for another use (just using the API). Frigate docker wont start without an MQTT broker, so this means I am running an MQTT broker docker for no reason.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
"mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.102",
    "password": null,
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": null
  },
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"detection_fps":4.9,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":40.57,"pid":241}},"driveway":{"camera_fps":5.0,"capture_pid":249,"detection_fps":4.9,"pid":247,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":5367.8,"mount_type":"tmpfs","total":5368.7,"used":0.9},"/media/frigate/clips":{"free":387763.8,"mount_type":"fuse.shfs","total":500107.8,"used":110395.4},"/media/frigate/recordings":{"free":387763.8,"mount_type":"fuse.shfs","total":500107.8,"used":110395.4},"/tmp/cache":{"free":15859.0,"mount_type":"rootfs","total":16630.8,"used":771.7}},"temperatures":{},"uptime":84223,"version":"0.10.1-83481af"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision
