### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by sharkssl** [blakeblackshear/frigate#3169]
### Describe the problem you are having

Hello, I used to run frigate then uninstalled it.
I re-installed it, configuration not changed, same version 3.1, and now it's not even starting.

### Version

Home Assistant 2022.4.7; Frigate NVR Current version: 3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.25
  user: mqttuser
  password: ...

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
   
cameras:
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:...@192.168.1.10:554/cam/realmonitor?channel=2&subtype=0
          roles:
            - detect
            - clips
            - record
            - rtmp
   detect:
     width: 928
      height: 576
      fps: 5  
      objects:
        track:
          - person
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://admin:...@192.168.1.10:554/cam/realmonitor?channel=4&subtype=0
          roles:
            - detect
            - clips
            - record
            - rtmp
    detect:
      width: 928
      height: 576
      fps: 5  
      objects:
        track:
          - person

snapshots:
   enabled: True
   timestamp: True
   retain:
     default: 3
```

### Relevant log output

```shell
no log!
```

### FFprobe output from your camera

```shell
[core-ssh ~]$ ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20210424) 20210424
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libsoxr --enable-libwebp --enable-libaom --disable-debug
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0  libswscale      5.  9.100 /  5.  9.100  libswresample   3.  9.100 /  3.  9.100  libpostproc    55.  9.100 / 55.  9.100[rtsp @ 0x7f88729670] method DESCRIBE failed: 404 Not Foundrtsp://admin:...@192.168.1.10:554/cam/realmonitor?channel=2: Server returned 404 Not Found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

analog cameras connected to a Dahua NVR

### Any other information that may be helpful

used to work!
