### ISSUE TITLE
Docker volumes vs just mapping to config question[Config Support]: 

### ISSUE THREAD

**Issue by sirweazel** [blakeblackshear/frigate#3172]
### Describe the problem you are having

This is my first deep dive into docker, so it's been a learning curve. I'm bouncing back between portainer and the command line so i can visually see a little bit better the docker relationships between the images, networks, volumes, etc.  I think i'm 75% to understanding.  The part i have a question about is with the volume mappings.  It seems in all the examples I've seen, you directly map to the config or storage on the host system?  I assume because this is the best setup?  Can someone explain if docker managed volumes comes into play at all?  When i setup portainer, i created an actual docker volume to persist data.  So for the frigate setup, do i  want to setup a docker volume or just directly map to the host file system?  Or maybe i want to create a volume for the db?  I wasn't sure where to turn for help or someone to explain the differences, pro's, cons.  I read an article detailing some of the pros and cons in general, but i wasn't sure how it would relate to frigate specific instance, or if i even had a grasp of what i read.  I currently have frigate running as a proof of concept that i could get it up and going in a test environment.  So now I'm looking at actually getting it more production ready, and that includes making sure data is persisted and easily accessible.  I'm thinking it makes sense to store the clips directly on the host filesystem, but is that the same for the db?  Does the db need to persist, and if so would that be a docker volume or direct link to db file on host.  My current frigate config.yml is directly on the host right now.  Thanks in advance, for the help.

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: homeassistant
  user: notmyuser
  password: notmypass

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

cameras:
  GDCam02: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://notmyuser:notmypass@cam.lan:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
```

### Relevant log output

```shell
Not applicable, but will provide if needed
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I'm just looking for why or when to configure one way versus another.  My setup is basic right now in a disposable VM so i get a better understanding and learn. In this test scenerio i was able to get frigate started with one camera added and even integrated into HA with minimal setup.  Now i'm looking at moving to bare metal with a better understanding of config options.

Docker Compose / Portainer Stack file:
`  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/notmyuser/frigate/config.yml:/config/config.yml
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "notmypass"
`
