### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by BobFish** [blakeblackshear/frigate#3176]
### Describe the problem you are having

Hey! I've been running frigate mostly fine for a few months now except I've often had to restart frigate as my cameras have stopped recording (motion detection continues to work however). I recently read https://docs.frigate.video/configuration/camera_specific/ this page of the docs and implemented the suggested input args for my reolink cameras.

Unfortunately I'm getting this error listed below. I've removed my urls / passwords but they've been working completely fine before I added the ffmpeg arguments so shouldn't be necessary.

Hope someone can help :) Thanks.

### Version

0.10.1

### Frigate config file

```yaml
mqtt:
  host: ****
  user: ****
  password: ****


cameras:
  courtyardCam:
    ffmpeg:
      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: ****
          roles:
            - detect
        - path: ****
          roles:
            - record
            - rtmp
    objects:
      track:
        - person
        - dog
        - bird
        - cat
    snapshots:
      enabled: True
      retain:
        default: 30
    record:
      enabled: true
      retain_days: 7
      events:
        retain:
          default: 14
    detect:
      width: 640
      height: 480
      fps: 5
  frontdoorcam:
    ffmpeg:
      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: ****
          roles:
            - detect
        - path: ****
          roles:
            - record
            - rtmp
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.67
    snapshots:
      enabled: True
      retain:
        default: 30
    record:
      enabled: true
      retain_days: 7
      events:
        retain:
          default: 14
    detect:
      width: 640
      height: 480
      fps: 5
detectors:
  coral1:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
2 validation errors for FrigateConfig
ffmpeg -> input_args
str type expected (type=type_error.str)
ffmpeg -> input_args
value is not a valid list (type=type_error.list)
Traceback (most recent call last):
File "/opt/frigate/frigate/app.py", line 312, in start
self.init_config()
File "/opt/frigate/frigate/app.py", line 77, in init_config
user_config = FrigateConfig.parse_file(config_file)
File "/opt/frigate/frigate/config.py", line 904, in parse_file
return cls.parse_obj(config)
File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
ffmpeg -> input_args
str type expected (type=type_error.str)
ffmpeg -> input_args
value is not a valid list (type=type_error.list)
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2
