### ISSUE TITLE
[Support]: HWaccel on Raspi4 with Reolink 520a

### ISSUE THREAD

**Issue by emuell36** [blakeblackshear/frigate#3181]
### Describe the problem you are having

Hey,

after I updated from 32bit to 64bit I hoped to be able tu turn on the HWaccel according to #2030.
But as soon as I turn on the HWaccel I get a green screen and ffmpeg seems to mess things up.

### Version

0.11.0-3de1948

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.63

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

cameras:
  camera_1:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
#      hwaccel_args:
#        - -hwaccel
#        - vaapi
#        - -hwaccel_device
#        - /dev/dri/renderD128
#        - -hwaccel_output_format
#        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://admin:xxx@192.168.1.112:554//h264Preview_01_main
#        - path: rtmp://192.168.1.112/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxx
#        - path: http://192.168.1.112/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxx
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False# <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 7
```

### Relevant log output

```shell
frigate  | [2022-05-03 11:40:09] frigate.app                    INFO    : Starting Frigate (0.11.0-3de1948)
frigate  | Starting migrations
frigate  | [2022-05-03 11:40:09] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-05-03 11:40:09] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-05-03 11:40:09] frigate.app                    INFO    : Output process started: 218
frigate  | [2022-05-03 11:40:09] detector.cpu                   INFO    : Starting detection process: 217
frigate  | [2022-05-03 11:40:09] ws4py                          INFO    : Using epoll
frigate  | [2022-05-03 11:40:09] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-05-03 11:40:09] frigate.app                    INFO    : Camera processor started for camera_1: 223
frigate  | [2022-05-03 11:40:09] frigate.app                    INFO    : Capture process started for camera_1: 224
frigate  | [2022-05-03 11:40:09] ws4py                          INFO    : Using epoll
frigate  | [2022-05-03 11:40:29] watchdog.camera_1              INFO    : No frames received from camera_1 in 20 seconds. Exiting ffmpeg...
frigate  | [2022-05-03 11:40:29] watchdog.camera_1              INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | [2022-05-03 11:40:38] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:47528]
frigate  | [2022-05-03 11:40:59] watchdog.camera_1              INFO    : FFmpeg didnt exit. Force killing...
frigate  | [2022-05-03 11:41:01] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-05-03 11:41:01] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-05-03 11:41:01] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-05-03 11:41:01] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-05-03 11:41:01] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-05-03 11:41:11] watchdog.camera_1              ERROR   : Ffmpeg process crashed unexpectedly for camera_1.
frigate  | [2022-05-03 11:41:11] watchdog.camera_1              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### FFprobe output from your camera

ffprobe version 4.3.4-0+deb11u1+rpt1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt1 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:xxx@192.168.1.112:554//h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.037400, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 30 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

### Operating system

Debian - Raspberry Pi OS Lite 64Bit

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 520a
