### ISSUE TITLE
[Support]: QNAP - docker-compose

### ISSUE THREAD

**Issue by gklank** [blakeblackshear/frigate#3182]
### Describe the problem you are having

Background task error for application_custom frigate3: ERROR: for frigate-2 Cannot create container for service frigate: Unknown runtime specified nvidia

### Version

0.10.1-amd64nvidia

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.250
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: xxxxxxxx
  stats_interval: 60

logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

detectors:
  cpu1:
    type: cpu

cameras:
  Garage-2:
    ffmpeg:
      #input_args:
        #- -c:v
        #- h264_cuvid
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.1.213:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:xxxxxxxx@192.168.1.213:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: false
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - traffic light
      filters:
        person:
          threshold: 0.5
          mask:
            - 292,143,287,66,163,71,168,147
        cat:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 10
        post_capture: 10
    zones:
      zone_garage_name1:
        coordinates: 0,480,640,480,524,168,130,203,0,243
    motion:
      mask:
        - 280,432,316,446,330,432,301,414
```

### Relevant log output

```shell
Background task error for application_custom frigate3: ERROR: for frigate-2 Cannot create container for service frigate: Unknown runtime specified nvidia
```

### FFprobe output from your camera

```shell
ffprobe not running as docker-compose error occur
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wireless

### Camera make and model

reolink, RLC-511WA

### Any other information that may be helpful

docker-compose.yml:

services:
  frigate:
    container_name: frigate-4
    #privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.10.1-amd64nvidia
    #command: nvidia-smi
    runtime: nvidia
    devices:
      # - /dev/dri            # uncomment this to use intel transcoder if available
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - LD_LIBRARY_PATH=/usr/local/cuda-11.1/targets/x86_64-linux/lib:/usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/applib:/usr/local/nvidia/syslib
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/GK/Frigate/config/config.yml:/config/config.yml:ro
      - /share/GK/Frigate/media:/media/frigate
      - /share/CACHEDEV1_DATA/.qpkg/NVIDIA_GPU_DRV/usr:/usr/local/nvidia
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
