### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by joaoferreira-git** [blakeblackshear/frigate#3183]
### Describe the problem you are having

Had the container running for a couple of months now and all of a sudden it stopped working, the last recording i have is from day 30 of April.
When i start the docket container it crashes and i belive this is the relevant error code [Errno 113] No route to host
Tried changing the network interface, reinstalling it and nothing works.

### Version

frigate:0.10.1-amd64

### Frigate config file

```yaml
mqtt:
 host: 192.168.1.75
 user: homeassistant
 password: xxxx
  
cameras:
 Quintal:
  rtmp:
      enabled: False
  ffmpeg:
   inputs:
    - path: rtsp://admin:xxxx@192.168.1.92:554/h.265
      roles:
      - record
      - detect
  detect:
    enabled: True
    width: 640
    height: 480
    fps: 5  
  motion:
    mask:
      - 0,328,0,480,287,480,284,431,274,411,261,386,252,366,220,329,181,273,28,208
  record: # <----- Enable recording
    enabled: True
    retain:
      days: 10

 Garagem:
  rtmp:
      enabled: False
  ffmpeg:
   inputs:
    - path: rtsp://admin:xxxx@192.168.1.40:554//h265Preview_01_main
      roles:
      - record
      - detect   
    - path: rtsp://admin:xxxx@192.168.1.40:554//h264Preview_01_sub
      roles:
       - rtmp
  detect:
    enabled: True
    width: 640
    height: 480
    fps: 5
  motion:
    mask:
      - 203,472,421,471,417,456,209,456
  record: # <----- Enable recording
    enabled: True
    retain:
      days: 10 

 Jardim:
  rtmp:
      enabled: False
  ffmpeg:
   inputs:
    - path: rtsp://admin:xxxx@192.168.1.41:554//h265Preview_01_main
      roles:
       - record
    - path: rtsp://admin:xxxx@192.168.1.41:554//h264Preview_01_sub
      roles:
      - detect    
  detect:
    enabled: True
    width: 640
    height: 480
    fps: 5    
  motion:
    mask:
      - 210,471,413,470,419,457,210,456  
  record: # <----- Enable recording
    enabled: True
    retain:
      days: 10 

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

ffmpeg:
  output_args:
    # Optional: output args for detect streams (default: shown below)
    #detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -analyzeduration 1000M -probesize 1000M -c copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    #rtmp: -c copy -f flv
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-05-03 15:44:37] frigate.app INFO : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-05-03 15:44:37] peewee_migrate INFO : Starting migrations
There is nothing to migrate
[2022-05-03 15:44:37] peewee_migrate INFO : There is nothing to migrate
[Errno 113] No route to host
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[Errno 113] No route to host
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
Can't run it.
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

EZVIZ C3N and 2 Reolink RLC-520A

### Any other information that may be helpful

No changes made to UNRAID before it stopped working, everything else working.
