### ISSUE TITLE
[Config Support]: No RTMP Streams, Recordings, or Events Available

### ISSUE THREAD

**Issue by robdoug89** [blakeblackshear/frigate#3188]
### Describe the problem you are having

Hello! I've got Frigate set up with two cameras and from the web UI, everything appears to be functioning normally (ie. I'm able to see the live view of both of my cameras just fine)

However, no events are captured, no recordings/clips/snapshots are persisted, and all of my RTMP streams fail to load in both VLC and Home Assistant.

For the RTMP streams I'm using the format: rtmp://192.168.1.X/live/CAMERA_NAME_1

For the recording, I'm doing software transcoding from HEVC to h264 (Intel QuickSync on Alder Lake CPUs is currently crashing/soft-locking, so just doing this in software for now)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci

model:
  width: 320
  height: 320

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects

detect:
  width: 640
  height: 480
  fps: 5
  enabled: True

rtmp:
  enabled: True

live:
  height: 720
  quality: 4

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -vf scale=1080:720 -c:a copy -an
  input_args:
    - -hide_banner
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt+igndts
    - -rtsp_transport
    - tcp
    - -stimeout
    - 5000000
    - -analyzeduration
    - 2147483647
    - -probesize
    - 2147483647

objects:
  track:
    - person
    - dog

record:
    enabled: True
    retain:
      days: 7
      mode: active_objects
    events:
      pre_capture: 15
      post_capture: 15
      retain:
        default: 10
        mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  retain:
    default: 10

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.X1:554//h265Preview_01_main
          roles:
            - record
        - path: rtsp://user:pass@192.168.1.X1:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
    live:
      height: 480
      quality: 1
    detect:
      width: 704
      height: 480
      fps: 30
    rtmp:
      enabled: True
    record:
      enabled: True
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://user:passg@192.168.1.X1:554//h265Preview_01_main
          roles:
            - record
        - path: rtsp://user:passg@192.168.1.X2:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
    live:
      height: 360
      quality: 1
    detect:
      width: 640
      height: 360
      fps: 30
    rtmp:
      enabled: True
    record:
      enabled: True

logger:
  default: debug
  logs:
    ffmpeg: debug
```

### Relevant log output

```shell
I get the following error message (but for only one of my cameras):

frigate    | [2022-05-04 06:49:42] watchdog.drive_way             ERROR   : Ffmpeg process crashed unexpectedly for drive_way.
frigate    | [2022-05-04 06:49:42] watchdog.drive_way             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | [2022-05-04 06:49:42] ffmpeg.drive_way.detect        ERROR   : [rtsp @ 0x558ab57a1a80] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate    | [2022-05-04 06:49:42] ffmpeg.drive_way.detect        ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
frigate    | [2022-05-04 06:49:42] ffmpeg.drive_way.detect        ERROR   : Output file #1 does not contain any stream
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.95,"pid":241}},"drive_way":{"camera_fps":30.7,"capture_pid":264,"detection_fps":0.0,"pid":249,"process_fps":30.7,"skipped_fps":0.0},"front_door":{"camera_fps":30.2,"capture_pid":253,"detection_fps":0.0,"pid":245,"process_fps":30.2,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":132.3,"mount_type":"tmpfs","total":134.2,"used":1.9},"/media/frigate/clips":{"free":7536963.4,"mount_type":"ext4","total":7937045.5,"used":0.1},"/media/frigate/recordings":{"free":7536963.4,"mount_type":"ext4","total":7937045.5,"used":0.1},"/tmp/cache":{"free":999.7,"mount_type":"tmpfs","total":1000.0,"used":0.3}},"temperatures":{"apex_0":56.8},"uptime":686,"version":"0.10.1-83481af"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

Both cameras are model REOLINK RLC-811A, with a main stream outputting at 4K via h265 and a substream at h264

FFProbe for the substream:
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: 0.000375, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x360, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

and for the main stream:
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000813, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 11.99 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

I'm attempting to persist the recordings to a software RAID array and am using an M.2 version of the Coral for detection
