### ISSUE TITLE
[Config Support]: frigate container does not launch if localhost is not defined in /etc/hosts

### ISSUE THREAD

**Issue by erenoglu** [blakeblackshear/frigate#3190]
### Describe the problem you are having

I installed a new Arch linux server system. It is using systemd-resolved and all is working properly except Frigate docker container.
when I ping localhost (from host), I get 127.0.0.1.  But frigate throws me this error when launcing and stops:

[emerg] 181#181: host not found in upstream "localhost:5001" in /usr/local/nginx/conf/nginx.conf:33

Here's my docker-compose.yml

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/config:/config:ro
      - /data/frigate:/media/frigate
      - /srv/frigate/logs:/usr/local/nginx/logs
      - /srv/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 512000000
    network_mode: host
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "abcd"
```

### Version

0.10.1-83481AF

### Frigate config file

```yaml
No problem with my configuration file
```

### Relevant log output

```shell
When starting docker container with docker-compose up command, I see below:
[emerg] 181#181: host not found in upstream "localhost:5001" in /usr/local/nginx/conf/nginx.conf:33
```

### Frigate stats

```json
Not relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I solved the issue by adding the below to /etc/hosts in the host docker server. 
Filing this bug to understand why frigate was expecting this information, while systemd-resolved is running and is providing response to localhost requests.

127.0.0.1	localhost
