### ISSUE TITLE
[Support]: Automation keeps sending same notification nonstop

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#3195]
### Describe the problem you are having

Hello,

One of Frigate automations seems to be stuck in a loop. It keeps sending me a notification to my phone with the same picture. I tried to trace the automation and checked error logs but cannot figure it out myself. Could someone please help me out? Funny thing is i have another automation for another camera with exact same notification and that is working fine. Thanks so much. 

alias: When a person enters a zone named Box
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''after''][''label''] == ''person'' }}'
  - condition: template
    value_template: '{{ ''box'' in trigger.payload_json[''after''][''entered_zones''] }}'
action:
  - service: notify.all_devices
    data_template:
      message: A {{trigger.payload_json['after']['label']}} has left a package!
      data:
        image: >-
          https://asemev.duckdns.org/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/thumbnail.jpg?format=android
        tag: '{{trigger.payload_json[''after''][''id'']}}'
mode: single

### Version

0.10.1-83481AF

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb'
    num_threads: 2
mqtt:
  host: 192.168.178.125
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: 
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.178.31:554/h.264'
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: >-
        -0,0,1920,0,1920,1080,1490,1080,1659,694,690,270,121,417,345,1080,0,1080
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask: >-
            -2,1,1920,0,1920,1080,1490,1080,1678,653,547,227,533,73,354,86,370,292,116,340,285,1012,680,1014,678,1080,0,1080
    zones:
      car:
        coordinates: 343,1058,1477,1080,1654,683,776,252,123,394
    record:
      enabled: true
      retain_days: 5 
#      events:
#        max_seconds: 300
#        pre_capture: 5
#        post_capture: 5
#        objects:
#          - person
#        required_zones: [car]
#        retain:
#          default: 10
#          objects:
#            person: 15

  Package:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.178.36:554/h.264'
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,1080,1920,1080,1350,547,1408,891,1081,899,1105,544,1307,523,1920,1080,1920,0,0,0


    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
        - cat
    zones:
      box:
        coordinates: 1128,888,1408,891,1356,564,1073,535
    record:
      enabled: true
      retain_days: 5
#      events:
#        max_seconds: 300
#        pre_capture: 5
#        post_capture: 5
#        objects:
#          - person
#        required_zones: [box]
#        retain:
#          default: 10
#          objects:
#            person: 15

database:
  path: /media/frigate/clips/frigate.db
logger:
  default: info
  logs:
    frigate.mqtt: error
```

### Relevant log output

```shell
Dont know where to get this
```

### FFprobe output from your camera

```shell
Dont know how to do this
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

EZVIZ CTQ3W
