### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by Marcos-kp** [blakeblackshear/frigate#3197]
### Describe the problem you are having

Hi! I am having some trouble with motion detection at night.

Things work great during daytime, but sometimes at night, frigate does not identifies motion on my stream.

### Version

3.1 -  0.10.1

### Frigate config file

```yaml
mqtt:
  host: x
  user: x
  password: x

cameras:
  Social:
    ffmpeg:
      inputs:
        - path: rtsp://x@x/cam/realmonitor?channel=5&subtype=1
          roles:
            - detect
        - path: rtsp://x@x/cam/realmonitor?channel=5&subtype=0
          roles:
            - record
            - rtmp
    detect:
      width: 352
      height: 240
      fps: 6
      stationary:
        interval: 0
        threshold: 40
    objects:
      track:
        - person
        - bicycle
        - motorcycle
      filters:
        person:
          threshold: 0.60
    motion:
      threshold: 20
      contour_area: 30
      mask:
        - 79,240,58,157,93,110,67,0,0,0,0,240
        - 132,0,281,0,352,0,352,47,352,71,291,38,307,147,188,49
    zones:
      zone_calcada_social:
        coordinates: 352,240,352,74,297,0,242,0,251,76,221,240,305,240
        objects:
          - bicycle
          - motorcycle
      zone_portao_social:
        coordinates: 262,70,279,149,280,240,0,240,0,0,134,0
        objects:
          - person
  Portao:
    ffmpeg:
      inputs:
        - path: rtsp://x@x/cam/realmonitor?channel=2&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 40
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - car
      filters:
        car:
          threshold: 0.56
        motorcycle:
          threshold: 0.65  
    motion:
      threshold: 35
      contour_area: 30
      mask:
        - 674,0,639,398,665,446,714,122,746,0,945,409,795,720,1280,720,1280,0,0,0,0,394,63,251,242,0,428,0
    zones:
      zone_calcada:
        coordinates: 0,506,0,720,302,720,356,454,819,433,884,0,252,0
        objects:
          - bicycle
          - motorcycle
          - car
      zone_portao:
        coordinates: 341,720,1051,720,921,138,846,0,684,0,601,241,454,298,391,428
        objects:
          - person

snapshots:
  enabled: True
  bounding_box: True
  required_zones:
    - zone_portao
    - zone_calcada
    - zone_calcada_social
    - zone_portao_social
  retain:
    default: 3

record:
  enabled: True
  retain:
    days: 0
  events:
    required_zones:
      - zone_portao
      - zone_calcada
      - zone_calcada_social
      - zone_portao_social
    pre_capture: 2
    post_capture: 2
    max_seconds: 120
    retain:
      default: 3

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

birdseye:
  enabled: False
```

### Relevant log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

Here is a screen capture of frigate running the debug. Motion boxes are turned on and they work, but with this video for example, no motion was triggered (nor event). Any help on how I can proceed? I tried using the main stream with width = 1280 and  height = 720 for better resolution, but apparently my object (person)[ is too big for it (?)](https://photos.app.goo.gl/pe5ijvev2cNCrDQ29)

Is my camera quality to poor? Is my CPU too weak to run it at night time?

[Video Link](https://photos.google.com/share/AF1QipN7z79Rzo4kgApdgl1ESVsint0M1s1BC2NT0UrquwhCSQdIjIi8WqCxUPEvWGDtSA?key=Q1FMS0VuVGVDYmYySWowMTZtZndBNjktcHNKYzln
)
