### ISSUE TITLE
[Camera Support]: Help with ffmpeg input args

### ISSUE THREAD

**Issue by MRobi1** [blakeblackshear/frigate#3198]
### Describe the problem you are having

Trying to get nvidia hardware decoding working on 1 camera. 
I currently have nvidia hardware decoding working on 6 other cameras with no issue. This camera is a different brand than the rest. I can make the camera work without specifying the h264_cuvid argument, but as soon as I add that argument in, I get a green screen and ffmpeg errors.

Config posted below is working for the camera WITHOUT nvidia hardware decoding.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
side_doorbell:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: 'rtsp://192.168.XX.XX:31549/c3ffe7e44cdf2c5c'
          roles:
            - detect
            - record
    detect:
      height: 1080
      width: 1920
      fps: 5
    best_image_timeout: 60
    rtmp:
      enabled: false
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask:
            - 984,665,1040,659,1146,622,1326,620,1455,625,1561,608,1683,622,1698,847,1621,885,1495,924,1335,967,1164,993,982,990
            - 445,1003,391,674,355,676,404,1008
            - 635,839,618,635,588,640,612,851
            - 1008,854,1010,652,982,652,986,860
          min_area: 1000
          max_area: 1000000
          min_score: 0.3
          threshold: 0.75
        dog:
          mask:
            - 984,665,1040,659,1146,622,1326,620,1455,625,1561,608,1683,622,1698,847,1621,885,1495,924,1335,967,1164,993,982,990          
            - 445,1003,391,674,355,676,404,1008
            - 635,839,618,635,588,640,612,851
            - 1008,854,1010,652,982,652,986,860
          min_area: 1
          max_area: 1000000
          min_score: 0.1
          threshold: 0.45
```

### Relevant log output

```shell
[2022-05-08 23:23:54] watchdog.side_doorbell         ERROR   : Ffmpeg process crashed unexpectedly for side_doorbell.,
[2022-05-08 23:23:44] frigate.video                  ERROR   : side_doorbell: ffmpeg process is not running. exiting capture thread...,
[2022-05-08 23:23:44] frigate.video                  ERROR   : side_doorbell: Unable to read frames from ffmpeg process.,
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55a74eb71bc0] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://192.168.XX.XX:31549/c3ffe7e44cdf2c5c':
  Metadata:
    title           : No Name
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 15 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
```

### Frigate stats

```json
{"back_door":{"camera_fps":5.0,"capture_pid":250,"detection_fps":0.0,"pid":235,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":91.13,"pid":225}},"hot_tub":{"camera_fps":5.1,"capture_pid":254,"detection_fps":0.0,"pid":236,"process_fps":5.1,"skipped_fps":0.0},"pool":{"camera_fps":5.1,"capture_pid":261,"detection_fps":0.0,"pid":238,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":62.2,"mount_type":"tmpfs","total":67.1,"used":4.9},"/media/frigate/clips":{"free":90831.5,"mount_type":"ext4","total":134145.4,"used":36425.2},"/media/frigate/recordings":{"free":90831.5,"mount_type":"ext4","total":134145.4,"used":36425.2},"/tmp/cache":{"free":989.5,"mount_type":"tmpfs","total":1000.0,"used":10.5}},"temperatures":{},"uptime":183,"version":"0.10.1-83481af"},"shed":{"camera_fps":5.0,"capture_pid":240,"detection_fps":0.0,"pid":231,"process_fps":5.0,"skipped_fps":0.0},"side_door":{"camera_fps":5.1,"capture_pid":244,"detection_fps":0.0,"pid":234,"process_fps":5.1,"skipped_fps":0.0},"side_doorbell":{"camera_fps":0.0,"capture_pid":264,"detection_fps":0.0,"pid":239,"process_fps":0.0,"skipped_fps":0.0},"side_yard":{"camera_fps":5.1,"capture_pid":241,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Ring Video Doorbell Wired through Scrypted ring plugin

### Any other information that may be helpful

Just looking for which input args to add to allow NVIDIA hardware decoding for this camera.
Thanks!
