### ISSUE TITLE
[Camera Support]: iOS Compatible ffmpeg Settings for RTSP Cameras

### ISSUE THREAD

**Issue by bdola** [blakeblackshear/frigate#3200]
### Describe the problem you are having

I am looking for correct ffmpeg settings to format my clip files to be compatible to view on an iPhone running iOS 15.4.1.  I use Home Assistant for everything and I just spun up Frigate as an add-on on a dedicated HA OS x86-64 server which is separate from my main HA OS RPi4 server.

Everything seems to function correctly for live streaming, detection (car, people, dog) through the Frigate GUI and HA GUI from a desktop using Microsoft Edge.  Clips are also saving and are viewable through both the Frigate GUI and HA GUI.

The issue I have is trying to view a clip of a detection event through iOS.  All clips show up as "The media playback was aborted due to a corruption problem or because the media used features your browser did not support" error.  This happens when trying to play clips through the Frigate GUI, Home Assistant GUI or Safari on the phone.  The only way I can successfully play the clip is if I download the clip to my phone then play it.

Are there any ffmpeg settings I can use to force encode the clips to a format that is iOS compatible?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: x.x.x.x
  user: ********
  password: ********

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    max_seconds: 300
    pre_capture: 15
    post_capture: 15
    retain:
      default: 7

cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.200.12:554/stream2
          roles: 
            - detect
        - path: rtsp://user:pass@192.168.200.12:554/stream1
          roles:
            - record
            - rtmp
    detect:
      height: 960
      stationary:
        interval: 0
        threshold: 60
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - dog
        - cat
    motion:
      mask:
        - 713,64,548,74,478,74,353,104,358,127,79,229,138,261,105,337,173,367,264,521,661,720,0,720,0,0,853,0,855,37
        - 1131,425,1224,258,1280,96,1280,720,879,720
    zones:
      zone_frontyard:
        coordinates: 856,26,1280,58,1181,325,860,720,551,720,141,437,62,346,126,286,64,215,324,128,373,87,518,58,643,60,676,39

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.200.11:554/stream2
          roles: 
            - detect
        - path: rtsp://user:pass@192.168.200.11:554/stream1
          roles:
            - record
            - rtmp
    detect:
      height: 960
      stationary:
        interval: 0
        threshold: 60
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - dog
        - cat
    motion:
      mask:
        - 1168,164,943,98,759,59,734,32,510,35,437,75,0,169,0,0,1280,0,1280,211
    zones:
      zone_driveway:
        coordinates: 1019,108,1280,199,1280,720,0,720,0,166,43,142,250,100,470,65,534,26,711,26,764,55

  amelia:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.200.42/0/av1
          roles:
            - detect
        - path: rtsp://user:pass@192.168.200.42/0/av0
          roles:
            - record
            - rtmp
    detect:
      stationary:
        interval: 0
        threshold: 30
    snapshots:
      enabled: True
    objects:
      track:
        - person
    motion:
      mask:
        - 77,164,0,177,0,80,56,76
        - 0,0,339,0,341,63,0,67
        - 0,192,176,178,350,627,0,697
    zones:
      zone_amelia:
        coordinates: 403,720,1280,720,1280,0,334,0,337,59,136,63

detectors: 
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
```

### Relevant log output

```shell
Nothing out of the ordinary.  All streams and recordings work in Frigate Web GUI...

[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-05-09 16:24:21] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-05-09 16:24:21] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-05-09 16:24:21] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-05-09 16:24:21] peewee_migrate                 INFO    : There is nothing to migrate
[2022-05-09 16:24:21] detector.cpu1                  INFO    : Starting detection process: 217
[2022-05-09 16:24:21] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-05-09 16:24:21] detector.cpu2                  INFO    : Starting detection process: 219
[2022-05-09 16:24:21] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-05-09 16:24:21] detector.cpu3                  INFO    : Starting detection process: 221
[2022-05-09 16:24:21] frigate.app                    INFO    : Output process started: 223
[2022-05-09 16:24:21] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-05-09 16:24:21] ws4py                          INFO    : Using epoll
[2022-05-09 16:24:21] frigate.app                    INFO    : Camera processor started for front_yard: 227
[2022-05-09 16:24:21] frigate.app                    INFO    : Camera processor started for driveway: 229
[2022-05-09 16:24:21] frigate.app                    INFO    : Camera processor started for amelia: 230
[2022-05-09 16:24:21] frigate.app                    INFO    : Capture process started for front_yard: 232
[2022-05-09 16:24:21] frigate.app                    INFO    : Capture process started for driveway: 236
[2022-05-09 16:24:21] frigate.app                    INFO    : Capture process started for amelia: 239
[2022-05-09 16:24:21] ws4py                          INFO    : Using epoll
[2022-05-09 16:24:47] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:42874]
[2022-05-09 16:24:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:58888]
[2022-05-09 16:24:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:58888]
```

### FFprobe output from your camera

```shell
ffprobe version 5.0.1-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 904 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 904 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 159
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
    Last message repeated 17 times
[h264 @ 000001f125e62880] SEI type 5 size 888 truncated at 160
    Last message repeated 1 times
[h264 @ 000001f125e62880] SEI type 5 size 896 truncated at 160
Input #0, rtsp, from 'rtsp://user:pass@192.168.200.11/stream1':
  Metadata:
    title           : IP camera Live streaming
    comment         : stream1
  Duration: N/A, start: 0.066667, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 2048x1536 [SAR 1:1 DAR 4:3], 30 fps, 30 tbr, 90k tbn
```

### Frigate stats

```json
{"amelia":{"camera_fps":5.0,"capture_pid":239,"detection_fps":0.0,"pid":230,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":176.05,"pid":217},"cpu2":{"detection_start":0.0,"inference_speed":174.75,"pid":219},"cpu3":{"detection_start":0.0,"inference_speed":178.75,"pid":221}},"driveway":{"camera_fps":5.1,"capture_pid":236,"detection_fps":0.0,"pid":229,"process_fps":5.1,"skipped_fps":0.0},"front_yard":{"camera_fps":5.0,"capture_pid":232,"detection_fps":0.0,"pid":227,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":2534.6,"mount_type":"tmpfs","total":2541.3,"used":6.7},"/media/frigate/clips":{"free":208091.4,"mount_type":"ext4","total":239268.0,"used":21565.5},"/media/frigate/recordings":{"free":208091.4,"mount_type":"ext4","total":239268.0,"used":21565.5},"/tmp/cache":{"free":2531.5,"mount_type":"tmpfs","total":2541.3,"used":9.7}},"temperatures":{},"uptime":1059,"version":"0.10.1-83481af"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Pelco IWP333-1ERS

### Any other information that may be helpful

"Front Yard" and "Driveway" cameras are ONVIF compatible with Stream 1 as 2048 x 1536 @ 30 fps (live) and Stream 2 as 1280 x 960 @ 5 fps (detection).

The "Amelia" camera is a $20 Amazon special EYEPLUS 1080P ONVIF Camera with 1080P @ 15 fps that the recorded clips play correctly on iOS using Frigate GUI in Safari and in HA GUIs without any issues.
