### ISSUE TITLE
[Support]:Problem running container after latest HomeAssistant update.

### ISSUE THREAD

**Issue by P3nkiln** [blakeblackshear/frigate#3212]
### Describe the problem you are having

I was having a problem viewing recordings after the latest home assistant update. It kept complaining that they were in the wrong format even though it worked for months before that. I believe it was a problem with FFmpeg.  I stopped the container and restarted  to see if that would help then i got this new error. I have tried uninstalling and even the beta container and can no longer get frigate to work.

### Version

3.1

### Frigate config file

```yaml
mqtt: 
  host: 192.168.1.143
  port: 1883
  user: mqtt
  password: *****

cameras:
  reargarden:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:*****@192.168.1.73:554/h264_stream'
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: true
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bird
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: true
      retain: 
        days: 2
        mode: motion
  frontdoor:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:******@192.168.1.59:554/h264_stream'
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: true
    detect:
      width: 576
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bird
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain: 
        days: 2
        mode: motion

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
s6-svscan (child): fatal: unable to exec s6-supervise: Exec format error
```

### FFprobe output from your camera

```shell
*
```

### Frigate stats

```json
*
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

EZVIZ
