### ISSUE TITLE
[Camera Support]: Simple JPEG Camera with HTTP Url

### ISSUE THREAD

**Issue by SirLouen** [blakeblackshear/frigate#3216]
### Describe the problem you are having

Green CAM:

![image](https://user-images.githubusercontent.com/224787/168441280-6974db28-4312-4a31-ba54-939ef6e5ffc1.png)

**CAM User is:** PpStRoNg
**Password is**: #%&wL1@*tU123zv
Note that the password uses a lot of special chars.
I cannot change this combination because it's hardcoded in the JPEG cam
To access from a browser I have to use a URL Encoded alternative, same for ffprobe

IMPORTANT: I've tried BOTH versions, URL encoded and the password as-is, but they don't work.

```yaml
cameras:
  back:
    ffmpeg:
      inputs:
        - path: http://PpStRoNg:%23%25%26wL1%40*tU123zv@192.168.101.73:8090/devices/snapshot
          roles:
            - detect
      input_args:
        - -r
        - 5 # << enter FPS here
        - -stream_loop
        - -1
        - -f
        - image2
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - 1
    detect:
      width: 640
      height: 360
      fps: 3
```

I'm using the [official config for JPEG cameras](https://docs.frigate.video/configuration/camera_specific/#jpeg-stream-cameras)

I've also tried encoding URL like this (URL ENCODED) without success

`http://PpStRoNg:%23%25%26wL1%40*tU123zv@192.168.101.73:8090/devices/snapshot`

But I have to say that if I put this on browser it works perfectly.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "back": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 3,
        "height": 360,
        "max_disappeared": 15,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 30
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-r",
          "5",
          "-stream_loop",
          "-1",
          "-f",
          "image2",
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-fflags",
          "+genpts+discardcorrupt",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "http://PpStRoNg:#%&wL1@*tU123zv@192.168.101.73:8090/devices/snapshot",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -r 5 -stream_loop -1 -f image2 -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i http://PpStRoNg:#%&wL1@*tU123zv@192.168.101.73:8090/devices/snapshot -c copy -f flv rtmp://127.0.0.1/live/back -r 3 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "back",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "cpu": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.100",
    "password": "1234",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "admin"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[2022-05-14 16:41:06] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.

[2022-05-14 16:41:06] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...

[2022-05-14 16:41:16] watchdog.back                  ERROR   : Ffmpeg process crashed unexpectedly for back.

[2022-05-14 16:41:16] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.

[2022-05-14 16:41:16] ffmpeg.back.detect             ERROR   : [tcp @ 0x55e727ce5dc0] Port missing in uri

[2022-05-14 16:41:16] ffmpeg.back.detect             ERROR   : [image2 @ 0x55e727ce0c00] Could find no file with path 'http://PpStRoNg:#%&wL1@*tU123zv@192.168.101.73:8090/devices/snapshot' and index in the range 0-4

[2022-05-14 16:41:16] ffmpeg.back.detect             ERROR   : http://PpStRoNg:#%&wL1@*tU123zv@192.168.101.73:8090/devices/snapshot: No such file or directory

[2022-05-14 16:41:16] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
```

### Version with PASSWORD URL Encoded

```shell
[2022-05-14 16:59:46] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.

[2022-05-14 16:59:46] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...

[2022-05-14 16:59:56] watchdog.back                  ERROR   : Ffmpeg process crashed unexpectedly for back.

[2022-05-14 16:59:56] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.

[2022-05-14 16:59:56] ffmpeg.back.detect             ERROR   : [tcp @ 0x55a06180ed00] Port missing in uri

[2022-05-14 16:59:56] ffmpeg.back.detect             ERROR   : [image2 @ 0x55a061809c00] Could find no file with path 'http://PpStRoNg:%23%25%26wL1%40*tU123zv@192.168.101.73:8090/devices/snapshot' and index in the range 0-4

[2022-05-14 16:59:56] ffmpeg.back.detect             ERROR   : http://PpStRoNg:%23%25%26wL1%40*tU123zv@192.168.101.73:8090/devices/snapshot: No such file or directory
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, jpeg_pipe, from 'http://PpStRoNg:%23%25%26wL1%40*tU123zv@192.168.101.73:8090/devices/snapshot':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x360 [SAR 1:1 DAR 16:9], 25 tbr, 25 tbn, 25 tbc
```

### Frigate stats

```json
{"back":{"camera_fps":0.0,"capture_pid":241,"detection_fps":0.0,"pid":239,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":233}},"service":{"storage":{"/dev/shm":{"free":66.8,"mount_type":"tmpfs","total":67.1,"used":0.3},"/media/frigate/clips":{"free":159113.0,"mount_type":"9p","total":1990045.2,"used":1830932.2},"/media/frigate/recordings":{"free":159113.0,"mount_type":"9p","total":1990045.2,"used":1830932.2},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":691,"version":"0.10.1-83481af"}}
```

### Operating system

Windows

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

ZS-GX1S

### Any other information that may be helpful

```shell
[2022-05-14 17:02:41] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.

[2022-05-14 17:02:41] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...

[2022-05-14 17:02:51] watchdog.back                  ERROR   : Ffmpeg process crashed unexpectedly for back.

[2022-05-14 17:02:51] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.

[2022-05-14 17:02:51] ffmpeg.back.detect             ERROR   : [tcp @ 0x556b03b2bd00] Port missing in uri

[2022-05-14 17:02:51] ffmpeg.back.detect             ERROR   : [image2 @ 0x556b03b26c00] Could find no file with path 'http://PpStRoNg:%23%25%26wL1%40%2AtU123zv@192.168.101.73:8090/devices/snapshot' and index in the range 0-4

[2022-05-14 17:02:51] ffmpeg.back.detect             ERROR   : http://PpStRoNg:%23%25%26wL1%40%2AtU123zv@192.168.101.73:8090/devices/snapshot: No such file or directory
```

Also note that it doesn't matter if I encode the * with %2A. Port missing in URI is still there in the log.

**Comment by PiscuDog** [comment]
Reading your debug info I think the problem is that frigate URL initializor is reading wrongly the URL and cannot parse the characters of that password adequately, so cannot read the full URL including the port and therefore, it fails. 

They are probably using a wrong implementation in python for encoding the URL, this is why FFMPEG crashes. Move to another system because some JPEG cameras like that are not compatible with Frigate.

**Comment by NickM-27** [comment]
We have seen this before with passwords that have special characters, I would try with a simple password and see if that fixes the issue.

**Comment by SirLouen** [comment]
> We have seen this before with passwords that have special characters, I would try with a simple password and see if that fixes the issue.

The problem is that the user & password is hardcoded in the firmware :(

```yaml
cameras:
  front:
    ffmpeg:
      inputs:
        - path: http://192.168.101.107:8080/video/mjpeg
          roles:
            - detect
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 640
      height: 360
      fps: 3
  back:
    ffmpeg:
      inputs:
        - path: http://PpStRoNg:%23%25%26wL1%40%2AtU123zv@192.168.101.73:8090/devices/snapshot
          roles:
            - detect
      input_args:
        - -r
        - 5 # << enter FPS here
        - -stream_loop
        - -1
        - -f
        - image2
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 640
      height: 360
      fps: 3
```

Expanding the YAML config file, I've introduced an Android MJPEG cam to check. It works fine. But clearly the error as I can read in the logs I have sent, is `Port missing in uri`

Python is not parsing adequately the URL because I can clearly see the stream with ffprobe when I pass the URL straight away to both ffprobe and ffmpeg in Linux.

**Comment by NickM-27** [comment]
> The problem is that the user & password is hardcoded in the firmware :(

Gotcha, that makes sense. The thing that seems odd is in the logs it shows the url the same as it was input so would think it is parsing it correctly.

Have you tried surrounding the stream in "" or using the password as an environment variable to see if there's any difference?

**Comment by SirLouen** [comment]
> Have you tried surrounding the stream in "" or using the password as an environment variable to see if there's any difference?

Nope, neither of the two options worked for me.
I recreated the container with the new environment variable:

```shell
docker run -d --name frigate --restart=unless-stopped --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --shm-size=64m -v "D:\VMS\frigate\media\frigate:/media/frigate" -v "D:\VMS\frigate\config\config.yml:/config/config.yml:ro" -v "D:\VMS\frigate\etc\localtime:/etc/localtime:ro" -e 'FRIGATE_RTSP_PASSWORD="#%&wL1@*tU123zv"' -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:stable-amd64
```

Plus updated the config file:

```yaml
back:
    ffmpeg:
      inputs:
        - path: http://PpStRoNg:{FRIGATE_RTSP_PASSWORD}@192.168.101.73:8090/devices/snapshot
          roles:
            - detect
      input_args: -r 5 -stream_loop -1 -f image2 -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      width: 640
      height: 360
      fps: 3
```

Without any changes in the logs. 

```shelll
14 19:04:21] ffmpeg.back.detect             ERROR   : [image2 @ 0x555c730b0bc0] Could find no file with path 'http://PpStRoNg:#%&wL1@*tU123zv@192.168.101.73:8090/devices/snapshot' and index in the range 0-4

[2022-05-14 19:04:21] ffmpeg.back.detect             ERROR   : http://PpStRoNg:#%&wL1@*tU123zv@192.168.101.73:8090/devices/snapshot: No such file or directory
```
