### ISSUE TITLE
[Support]: Fails to Start with 0.11.0-beta2 container on arm

### ISSUE THREAD

**Issue by stephengolub** [blakeblackshear/frigate#3222]
### Describe the problem you are having

Just upgraded to the `0.11.0-beta2` docker image running on a raspberry pi 4b+. Now I'm getting an import error for `numpy`. The base of the error is:

`ImportError: libcblas.so.3: cannot open shared object file: No such file or directory`

### Version

0.11.0-beta2

### Frigate config file

```yaml
---
detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

mqtt:
  host: 192.168.6.190
  port: 34883
  topic_prefix: frigate
  client_id: frigate

# Optional: Global ffmpeg args
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  # hwaccel_args:
  #   - -c:v
  #   - h264_mmal
  # Optional: global input args (default: shown below)
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'

objects:
  track:
    - person
    - cat
    - dog

record:
  enabled: true
  retain_days: 5
  events:
    # enabled: true
    max_seconds: 300
    retain:
      default: 5
      mode: active_objects

cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.6.151:554/\
                Streaming/Channels/102"
          roles:
            - detect
            - rtmp
            - record
    detect:
      height: 360
      width: 640
      fps: 4
    best_image_timeout: 60
    motion:
      mask:
        - 640,0,640,181,463,82,461,0
    zones:
      back_patio:
        coordinates: 408,360,303,288,56,108,0,116,0,249,60,360
      back_yard:
        coordinates: "252,260,400,360,640,360,640,204,533,274,431,0,287,0,44,\
                      39,57,106"
    mqtt:
      crop: false
      timestamp: false
      height: 480
    record:
      events:
        objects:
          - person
  frontyard:
    record:
      events:
        objects:
          - person
    motion:
      mask:
        - 0,0,0,48,0,83,28,59,83,59,200,60,406,114,640,224,640,0
    zones:
      frontyard_grass:
        coordinates: "162,58,280,77,399,108,486,146,587,186,640,219,640,\
                      426,502,358,461,344,374,370,268,440,171,398,68,380,
                      30,282,0,244,0,134,0,81,29,57"
      sidewalk:
        coordinates: "311,397,393,357,492,346,492,363,552,372,640,424,640,\
                      480,207,480"
      frontyard_flowerbed:
        coordinates: 28,270,0,244,0,480,202,480,268,442,216,406,69,382,48,344
    ffmpeg:
      inputs:
        - path: "rtmp://192.168.6.153/bcs/channel0_sub.bcs?channel=0&stream=0\
                 &user=admin&password={FRIGATE_RTSP_PASSWORD}"
          roles:
            - detect
            - rtmp
            - record
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    detect:
      height: 480
      width: 640
      fps: 4
    best_image_timeout: 60
    mqtt:
      crop: false
      timestamp: false
      height: 480
  driveway:
    record:
      events:
        objects:
          - person
          - car
    motion:
      mask:
        - 137,156,212,110,292,84,476,0,131,0,0,0,0,234
    zones:
      driveway_area:
        coordinates: 21,212,288,87,353,98,640,184,466,480,395,480,270,398
      driveway_sidewalk:
        coordinates: 58,406,0,480,171,480,263,393,167,317
      driveway_grass:
        coordinates: 31,216,64,232,164,321,54,416,22,480,0,480,0,229
      driveway_sideyard:
        coordinates: 611,174,640,89,431,31,347,48,290,83
    ffmpeg:
      inputs:
        - path: "rtmp://192.168.6.154/bcs/channel0_sub.bcs?channel=0&stream=0\
                &user=admin"
          roles:
            - detect
            - rtmp
            - record
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -rw_timeout
            - '5000000'
            - -use_wallclock_as_timestamps
            - '1'
    detect:
      height: 480
      width: 640
      fps: 4
    best_image_timeout: 60
    objects:
      track:
        - person
        - cat
        - car
        - dog
    mqtt:
      crop: false
      timestamp: false
      height: 480
  bedroom:
    ffmpeg:
      inputs:
        - path: http://192.168.6.19:2971/camera/stream
          roles:
            - detect
            - rtmp
            - record
          input_args: '-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1'
      output_args:
        record: '-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an'
        rtmp: '-c:v libx264 -an -f flv'
    detect:
      height: 480
      width: 640
      fps: 4
    best_image_timeout: 60
    mqtt:
      crop: false
      height: 480
    objects:
      track:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 3
          mode: active_objects
  utility_room:
    ffmpeg:
      inputs:
        - path: http://192.168.6.145:2971/camera/stream
          roles:
            - detect
            - rtmp
          input_args: '-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1'
      output_args:
        record: '-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an'
        rtmp: '-c:v libx264 -an -f flv'
    detect:
      height: 480
      width: 640
      fps: 4
    best_image_timeout: 60
    mqtt:
      crop: false
      height: 480
    objects:
      track:
        - person
        - cat
        - dog
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 3
          mode: active_objects
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/frigate/frigate/__main__.py", line 9, in <module>
    from frigate.app import FrigateApp
  File "/opt/frigate/frigate/app.py", line 22, in <module>
    from frigate.config import DetectorTypeEnum, FrigateConfig
  File "/opt/frigate/frigate/config.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 104, in <module>
    import numpy
  File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.22.3"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: libcblas.so.3: cannot open shared object file: No such file or directory
[cmd] python3 exited 1
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
can't start
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

....
