### ISSUE TITLE
[Support]: Beta 11-2

### ISSUE THREAD

**Issue by teslamine** [blakeblackshear/frigate#3228]
### Describe the problem you are having

After updating, frigate will no longer start without errors. First there were lots of hardware acceleration errors so then I commented everything out. Its now not able to detect the coral. 

### Version

beta11-2

### Frigate config file

```yaml
#ui:
#  use_experimental: true
objects:
  filters:
    person:
      threshold: 0.65
    car:
      threshold: 0.70
ffmpeg:
  global_args: -hide_banner -loglevel info
  #hwaccel_args:
  #  - -hwaccel
  #  - vaapi
  #  - -hwaccel_device
  #  - /dev/dri/renderD128
  #  - -hwaccel_output_format
  #  - yuv420p
mqtt:
  # Required: host name
  host: ip
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: p
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  #width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  #height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for running detection on stationary objects (default: shown below)
    # When set to 0, object detection will never be run on stationary objects. If set to 10, it will be run on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to  
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      # Optional: Object specific values
      objects:
        person: 1000
cameras:
  front:
    ffmpeg:
      inputs:
        #- path: rtmp://ip
        - path: rtsps://ip
          roles:
            - record
        #    - detect
        - path: rtsps://ip
          roles:
            - detect
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
        #- /dev/dri/renderD128
      # output_args:
      #   record:
      #     - -f
      #     - segment
      #     - -segment_time
      #     - 10
      #     - -segment_format
      #     - mp4
      #     - -reset_timestamps
      #     - 1
      #     - -strftime
      #     - 1
      #     - -c:v
      #     - copy
      # input_args:
      #   - '-avoid_negative_ts'
      #   - make_zero
      #   - '-fflags'
      #   - nobuffer
      #   - '-flags'
      #   - low_delay
      #   - '-strict'
      #   - experimental
      #   - '-fflags'
      #   - +genpts+discardcorrupt
      #   - '-use_wallclock_as_timestamps'
      #   - '1' 
      #hwaccel_args:
      #  - '-f'
      #  - yuv420p
    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
    objects:
      track:
        - person
        - dog
        - car
        - bird
        - bicycle
    #   filters:
    #     car:
    #       mask:
    #         - 416,286,409,439,968,563,1030,251,643,220
    #         - 504,143,514,189,379,209,370,157
    #         - 218,254,200,206,303,182,330,223
    #         - 533,224,693,237,687,161,549,131
    #         #- 214,96,316,88,349,118,257,163,205,148
    zones:
      cul-de-sac:
        coordinates: 0,353,98,307,194,275,357,227,477,208,591,196,666,226,495,309,343,372,0,475
        objects: 
          - car
          - person
          - dog
          - bicycle
      driveway:
        coordinates: 158,442,195,720,1144,720,1154,643,440,535,365,416
        objects:
          - car
      front_door:
        coordinates: 1058,337,1059,89,863,130,871,317
      mitchells:
        coordinates: 98,292,76,171,292,119,317,226
      parks:
        coordinates: 541,131,565,177,374,210,356,158
        objects:
          - car
      street:
        coordinates: 663,212,903,189,886,105,745,104,615,158
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
    record:
      enabled: True
      expire_interval: 60
      retain: 
        days: 0
        mode: all
      events:
        required_zones:
          - driveway
        # Optional: Enable event recording retention settings (default: shown below)
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the cache
        #       will begin to expire and the resulting clip will be the last x seconds of the event unless retain_days under record is > 0.
        max_seconds: 300
        # Optional: Number of seconds before the event to include in the event (default: shown below)
        pre_capture: 10
        # Optional: Number of seconds after the event to include in the event (default: shown below)
        post_capture: 10
        # Optional: Objects to save event for. (default: all tracked objects)
        # Optional: Restrict event to objects that entered any of the listed zones (default: no required zones)
        # Optional: Retention settings for event
        retain:
          # Required: Default retention days (default: shown below)
          default: 1
          # Optional: Per object retention days
    objects:
      track:
        - person
        - dog
        - car
        - bicycle

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
[2022-05-18 11:09:45] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi
