### ISSUE TITLE
[Config Support]: MQTT issue - 502: Bad Gateway

### ISSUE THREAD

**Issue by Nicolasdomotique** [blakeblackshear/frigate#3241]
### Describe the problem you are having

Hi,

I am facing issue on installing Frigate.

I have a netatmo camera.

I installed the Addon via supervisor and configured frigate.yml file. I also installed MQTT mosquitto.

However when I try to run Frigate, I have the message : 502: Bad Gateway.

Can you please tell me what is the root of this issue? frigate.yml file or MQTT set up? or anything else...

I think it might be an MQTT issue as I can not see in MQTT explorer : Frigate...

Can you please help? thanks

### Version

no

### Frigate config file

```yaml
mqtt:
  host: IP adress
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: user
  stats_interval: 60
  
cameras:
  pi_cam:
    ffmpeg:
      inputs:
        - path: http://192.168.1.106/ID-CAM/live/files/medium/index.m3u8
          roles:
            - detect:
            - rtmp:
            - clips:
            - record:
      input_args:
        -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    width: 1920
    height: 1080
    fps: 5
    
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
502: Bad Gateway
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by blakeblackshear** [comment]
This usually means the addon is not running. Take a look at the logs.

**Comment by Nicolasdomotique** [comment]
Thanks for your return 👍 
Below the log :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-05-20 16:04:18] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
3 validation errors for FrigateConfig
cameras -> pi_cam -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> pi_cam -> height
  extra fields not permitted (type=value_error.extra)
cameras -> pi_cam -> width
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 511, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 3 validation errors for FrigateConfig
cameras -> pi_cam -> fps
  extra fields not permitted (type=value_error.extra)
cameras -> pi_cam -> height
  extra fields not permitted (type=value_error.extra)
cameras -> pi_cam -> width
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Can you please assist on what is wrong for my configuration? thanks

**Comment by NickM-27** [comment]
You have

```yaml
width: 1920 
height: 1080 
fps: 5
```

Without the detect header set. Please look at https://docs.frigate.video/guides/getting_started#step-3-add-a-minimal-camera-configuration for how to do this properly
