### ISSUE TITLE
[Support]: 0.11.0 Beta2 frigate keeps crashing

### ISSUE THREAD

**Issue by kbmetz** [blakeblackshear/frigate#3249]
### Describe the problem you are having

Been trying to get the 0.11.0 Beta2 version running and all it does is keep crashing. I've tried trimming down my config file to one camera and removing all the options. It's extremely difficult to troubleshoot because the container keeps crashing every 15 seconds so I'm not able to run much in it. It seems to find ffmpeg without issue. I've removed all cameras except for one from the config file for testing purposes

Running with 'docker-compose -f frigate.compose up

version: '3.6'
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    image: blakeblackshear/frigate:0.11.0-beta2
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/config:/config
      - /srv/frigate/db:/db
      - /srv/frigate/clips:/media/frigate/clips
      - /srv/frigate/recordings:/media/frigate/recordings
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: 'password'
    shm_size: '12G'

### Version

0.11.0-D2C3CDC

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.82
  topic_prefix: frigate
  user: xxx
  password: xxx
detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True

record:
  enabled: True
  retain_days: 1
  events:
    max_seconds: 300
    pre_capture: 30
    post_capture: 30
    retain:
      default: 45
      objects:
        person: 90
        car: 90

snapshots:
  enabled: True
  timestamp: True
  bounding_box: False
  crop: False
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15
cameras:
  Amcrest-Driveway:
    ffmpeg:
      inputs:  
        - path: rtsp://frigate:frigate@192.168.50.105:554
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car   
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
    zones:
      zone_driveway:
        coordinates: 1280,362,1256,696,525,686,284,248
```

### Relevant log output

```shell
Status: Downloaded newer image for blakeblackshear/frigate:0.11.0-beta2
Creating frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-05-24 10:15:41] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
frigate    | [2022-05-24 10:15:41] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
frigate    | Starting migrations
frigate    | [2022-05-24 10:15:41] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2022-05-24 10:15:41] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2022-05-24 10:15:41] frigate.app                    INFO    : Output process started: 240
frigate    | [2022-05-24 10:15:41] detector.coral                 INFO    : Starting detection process: 239
frigate    | [2022-05-24 10:15:41] ws4py                          INFO    : Using epoll
frigate    | [2022-05-24 10:15:41] frigate.app                    INFO    : Camera processor started for Amcrest-Driveway: 245
frigate    | [2022-05-24 10:15:41] frigate.app                    INFO    : Capture process started for Amcrest-Driveway: 246
frigate    | [2022-05-24 10:15:41] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | Process detector:coral:
frigate    | [2022-05-24 10:15:41] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
frigate    |     delegate = Delegate(library, options)
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
frigate    |     raise ValueError(capture.message)
frigate    | ValueError
frigate    | 
frigate    | During handling of the above exception, another exception occurred:
frigate    | 
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
frigate    |     object_detector = LocalObjectDetector(
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
frigate    |     edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
frigate    |     raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate    | ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate    | 
frigate    | [2022-05-24 10:15:42] ws4py                          INFO    : Using epoll
frigate    | [2022-05-24 10:16:02] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [2022-05-24 10:16:02] frigate.video                  ERROR   : Amcrest-Driveway: Unable to read frames from ffmpeg process.
frigate    | [2022-05-24 10:16:02] frigate.video                  ERROR   : Amcrest-Driveway: ffmpeg process is not running. exiting capture thread...
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
docker exec -it frigate ffprobe rtsp://frigate:frigate@192.168.50.105:554
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable
e-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg 
nable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://frigate:ADMINadmin@192.168.50.105:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.105000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 20 fps, 100 tbr, 90k tbn, 40 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest ip8m-t2599ew

### Any other information that may be helpful

Running on OpenSUSE Leap 15.3
Docker version 20.10.14-ce, build 87a90dc786bd
