### ISSUE TITLE
[Support]: after update add-on don't start

### ISSUE THREAD

**Issue by joshrezende** [blakeblackshear/frigate#3250]
### Describe the problem you are having

after i updated the frigate plugin via HACS it wont start anymore

### Version

v1.1.2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.166
  user: mqtt-user
  password: teste-mqtt

cameras:
  portao: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://<username>:<password>@<ip address>:554/Streaming/Channels/101 # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

detectors:
  # cpu1:
  #   type: cpu
  # cpu2:
  #   type: cpu
  coral1:
    type: edgetpu
    device: pci:0
  # coral2:
  #   type: edgetpu
  #   device: pci:1
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-05-24 15:45:57] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-05-24 15:45:57] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-05-24 15:45:57] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-05-24 15:45:57] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 113] No route to host
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

na
