### ISSUE TITLE
[Camera Support]: Config an HLS ipcam

### ISSUE THREAD

**Issue by dimat789** [blakeblackshear/frigate#3251]
### Describe the problem you are having

How can use .m3u8 stream from my camera for video analize?

### Version

latest

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.21
  user: mqtt
  password: mqtt
detectors:
  cpu1:
    type: cpu
    num_threads: 8 
detect:
  enabled: True
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 4
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# Optional: ffmpeg configuration
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 100
    
cameras:
  STOROZKA_01:
    ffmpeg:
      inputs:
        - path: http://xxx/cam1/stream1.m3u8
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False
    detect:
      width: 1280
      height: 720
    objects:
      track: 
        - person
        - car
        - bicycle
        - motorcycle
        - bus


```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
ffprobe version 4.1.8-0+deb10u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x55b51d30d100] Opening 'http://XXX/cam1/stream1284.ts' for reading
[hls,applehttp @ 0x55b51d30d100] Opening 'http://XXX/cam1/stream1285.ts' for reading
Input #0, hls,applehttp, from 'http://XXX/cam1/stream1.m3u8':
  Duration: N/A, start: 2834.466667, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 15 fps, 15 tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Polyvision over nginx proxy
