### ISSUE TITLE
[Config Support]: Unifi G3 Instant RTSP

### ISSUE THREAD

**Issue by stu1811** [blakeblackshear/frigate#3261]
### Describe the problem you are having

I'm using Unifi Protect to generate an RTSP stream. I'm having trouble getting the stream to import into Frigate. The log shows an error with the audio stream but I'm telling ffmpeg to ignore that stream.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
heat_cam:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 600 -segment_format yuvj420p  -reset_timestamps 1 -strftime 1 -map 0 -map -0:a
      input_args: -fflags nobuffer -rtsp_transport tcp 
      inputs:
        - path: rtsps://192.168.42.1:7441/ABC123?enableSrtp
          roles:
            - detect
            - rtmp
        - path: rtsps://192.168.42.1:7441/ABC123?enableSrtp
          roles:
            - record
    objects: 
      track:
        - person
        - dog
        # Optional: save clips configuration
    record:
      enabled: true
      retain:
        days: 7
      events:
        pre_capture: 5
        post_capture: 5
        required_zones: []
        retain:
          # Required: Default retention days (default: shown below)
          default: 30
          # Optional: Per object retention days
          #objects:
          #  person: 15
    snapshots:
      enabled: true
    detect:
      width: 640
      height: 360
      fps: 5
```


### Relevant log output

```shell
[2022-05-27 08:04:50] frigate.video                  ERROR   : heat_cam: Unable to read frames from ffmpeg process.
[2022-05-27 08:04:50] frigate.video                  ERROR   : heat_cam: ffmpeg process is not running. exiting capture thread...
[2022-05-27 08:05:08] watchdog.heat_cam              ERROR   : Ffmpeg process crashed unexpectedly for heat_cam.
[2022-05-27 08:05:08] watchdog.heat_cam              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-05-27 08:05:08] ffmpeg.heat_cam.detect         ERROR   : [flv @ 0x55a33ef446c0] FLV does not support sample rate 48000, choose from (44100, 22050, 11025)
[2022-05-27 08:05:08] ffmpeg.heat_cam.detect         ERROR   : [flv @ 0x55a33ef446c0] Audio codec opus not compatible with flv
[2022-05-27 08:05:08] ffmpeg.heat_cam.detect         ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
[2022-05-27 08:05:08] ffmpeg.heat_cam.detect         ERROR   : 
[2022-05-27 08:05:10] frigate.video                  ERROR   : heat_cam: Unable to read frames from ffmpeg process.
[2022-05-27 08:05:10] frigate.video                  ERROR   : heat_cam: Unable to read frames from ffmpeg process.
[2022-05-27 08:05:10] frigate.video                  ERROR   : heat_cam: Unable to read frames from ffmpeg process.
[2022-05-27 08:05:10] frigate.video                  ERROR   : heat_cam: Unable to read frames from ffmpeg process.
```


### Frigate stats

_No response_

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

M.2

### Any other information that may be helpful

ffrobe:
```
ffprobe -show_streams -select_streams v:2 rtsps://192.168.42.1:7441/ABC123?enableSrtpffprobe version 4.4-6ubuntu5 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsps://192.168.42.1:7441/ABC123?enableSrtp':
  Metadata:
    title           : 7845582FD265_0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
  Stream #0:2: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn, 60 tbc
```

ffmpeg from command line
```
ffmpeg  -fflags nobuffer -rtsp_transport tcp   -i rtsps://192.168.42.1:7441/ABC213?enableSrtp -f segment -segment_time 600 -segment_format yuvj420p  -reset_timestamps 1 -st
rftime 1 -map 0 -map -0:a  foo.mp4                                                                                                                                                                                                       
ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers                                                                                                                                                                
  built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)                                                                                                                                                                                             
  configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsps://192.168.42.1:7441/Ft5BcntrOmlj3H00?enableSrtp':
  Metadata:
    title           : 7845582FD265_0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 16000 Hz, mono, fltp
  Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
  Stream #0:2: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn, 60 tbc
Stream mapping:
  Stream #0:2 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x55daa6ccb440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55daa6ccb440] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 0x55daa6ccb440] 264 - core 160 r3011 cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, segment, to 'foo.mp4':
  Metadata:
    title           : 7845582FD265_0
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 1920x1080, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  144 fps= 27 q=-1.0 Lsize=N/A time=00:00:04.70 bitrate=N/A dup=86 drop=0 speed=0.869x    
video:256kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
``

**Comment by NickM-27** [comment]
There's a few things that are confusing here. 

1. Both your inputs are the same url
2. You are telling ffmpeg to ignore audio for record but the logs are complaining about the rtmp stream which has it's own set of output args and needs to be adjusted

**Comment by stu1811** [comment]
> There's a few things that are confusing here.
> 
> 1. Both your inputs are the same url
> 2. You are telling ffmpeg to ignore audio for record but the logs are complaining about the rtmp stream which has it's own set of output args and needs to be adjusted

1. I sanitized the URLs. They are actually different. 
2. Good to know. I'll see if I can find some documentation.

**Comment by stu1811** [comment]
@NickM-27 got it. Thanks for the pointer. Added the rtmp line.
```
ffmpeg:
      output_args:
        record: -f segment -segment_time 600 -segment_format yuvj420p  -reset_timestamps 1 -strftime 1 -map 0 -map -0:a
        rtmp: -c copy -f flv -map 0 -map -0:a
```
