### ISSUE TITLE
[Support]: v0.11.0 beta2 - Events missing frames when snapshot is taken

### ISSUE THREAD

**Issue by D34DC3N73R** [blakeblackshear/frigate#3264]
### Describe the problem you are having

When events are captured on my POE cams, I'm getting a lot of dropped frames exactly when the snapshots are taken.
Snapshot: https://drive.google.com/file/d/165mOAir1qrfhSCSX3HDzBv4V-iKlBuUW/view?usp=sharing
Clip: https://drive.google.com/file/d/1UaVUMzv9D-7ZvfpFoE7d23zHxo1iUdQ3/view?usp=sharing

### Version

0.11.0-D2C3CDC

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.178
  user: user
  password: pass
database:
  path: /config/db/frigate.db
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  global_args: -hide_banner -loglevel info
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  hwaccel_args: -c:v h264_cuvid
record:
  enabled: true
  retain:
    days: 14
  events:
    max_seconds: 600
    pre_capture: 10
    post_capture: 10
    retain:
      default: 365
objects:
  track:
    - person
    - cat
    - dog
    - bird
    - frisbee
cameras:
  back1:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.15:554/Streaming/Channels/103
          roles:
            - detect
        - path: rtsp://<user>:<pass>@192.168.0.15:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
  back2:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.16:554/Streaming/Channels/103
          roles:
            - detect
        - path: rtsp://<user>:<pass>@192.168.0.16:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
  front1:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.13:554/Streaming/Channels/103
          roles:
            - detect
        - path: rtsp://<user>:<pass>@192.168.0.13:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
    objects:
      filters:
        person:
          min_area: 5000
  front2:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.14:554/Streaming/Channels/103
          roles:
            - detect
        - path: rtsp://<user>:<pass>@192.168.0.14:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
    objects:
      filters:
        person:
          min_area: 5000
  side1:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.17:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://<user>:<pass>@192.168.0.17:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
    objects:
      filters:
        person:
          min_area: 5000
  side2:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.18:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://<user>:<pass>@192.168.0.18:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
    objects:
      filters:
        person:
          min_area: 5000
  doorbell:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 1000
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: rtsp://<user>:<pass>@192.168.0.26:554/Streaming/Channels/101
          roles:
            - record
            - rtmp
            - detect
          input_args:
            - -avoid_negative_ts
            - make_zero
#      output_args:
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#    rtmp:
#      enabled: False
    detect:
      width: 960
      height: 1280
      fps: 15
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 365
    objects:
      filters:
        person:
          min_area: 11500
        cat:
          min_score: 0.4
          threshold: 0.5
          max_area: 30000
```

### Relevant log output

```shell
Follow up next comment
```

### FFprobe output from your camera

```shell
# front1
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://<user>:<pass>@192.168.0.13:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.300000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn, 40 tbc

# front 2
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://<user>:<pass>@192.168.0.14:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.300000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn, 40 tbc

# back1
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://<user>:<pass>@192.168.0.15:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.300000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn, 40 tbc

# back2
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://<user>:<pass>@192.168.0.16:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.300000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn, 40 tbc

# side1 - substream - detect errors
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://<user>:<pass>@192.168.0.17:554/Streaming/Channels/102':
  Metadata:
    title           : h264.mp4
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 10 fps, 10 tbr, 90k tbn, 20 tbc
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s

# side2
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://<user>:<pass>@192.168.0.18:554/Streaming/Channels/102':
  Metadata:
    title           : h264.mp4
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 10 fps, 10 tbr, 90k tbn, 20 tbc
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{"back1":{"camera_fps":10.1,"capture_pid":252,"detection_fps":0.0,"pid":238,"process_fps":10.1,"skipped_fps":0.0},"back2":{"camera_fps":10.1,"capture_pid":256,"detection_fps":0.0,"pid":240,"process_fps":10.1,"skipped_fps":0.0},"detection_fps":15.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.74,"pid":232}},"doorbell":{"camera_fps":15.0,"capture_pid":281,"detection_fps":0.0,"pid":250,"process_fps":15.0,"skipped_fps":0.0},"front1":{"camera_fps":10.0,"capture_pid":258,"detection_fps":10.0,"pid":243,"process_fps":10.0,"skipped_fps":0.0},"front2":{"camera_fps":10.0,"capture_pid":263,"detection_fps":0.0,"pid":246,"process_fps":10.0,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":53.8,"mount_type":"tmpfs","total":67.1,"used":13.3},"/media/frigate/clips":{"free":10347544.9,"mount_type":"fuse.mergerfs","total":11905574.1,"used":957878.1},"/media/frigate/recordings":{"free":10347544.9,"mount_type":"fuse.mergerfs","total":11905574.1,"used":957878.1},"/tmp/cache":{"free":16686.0,"mount_type":"tmpfs","total":16791.6,"used":105.6}},"temperatures":{},"uptime":9329,"version":"0.11.0-d2c3cdc"},"side1":{"camera_fps":10.1,"capture_pid":269,"detection_fps":0.0,"pid":247,"process_fps":10.1,"skipped_fps":0.0},"side2":{"camera_fps":10.1,"capture_pid":275,"detection_fps":5.7,"pid":249,"process_fps":10.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Front1: Hikvision DS-2CD2385G1-I  - Front2: Hikvision DS-2CD2085G1-I  - Back1: Hikvision DS-2CD2085G1-I  - Back2: Hikvision DS-2CD2085G1-I  - Side1:  Herospeed/Fuhan FH8856_K05_B1T1A1M0C0P1_W   - Side2:  Herospeed/Fuhan FH8856_K05_B1T1A1M0C0P1_W

### Any other information that may be helpful

In testing I've noticed I can drastically cut down on missed frames with an extremely low I-Frame value. The clip above was taken with an I-Frame interval of 50. I've since dropped all cameras to 5 and the chunks missing are much shorter, but still there. I consider this a bandaid and not a remedy. The comment is too long for github. Following up with missing info.
