### ISSUE TITLE
[Support]: Frigate detect but not event, no recording

### ISSUE THREAD

**Issue by pinkfloydFR** [blakeblackshear/frigate#3275]
### Describe the problem you are having

Hi,

**EDIT : don't know why and how, but seem to be ok now ( perhaps the update modification in the config file )

You can close, Sorry.**

Thanks for any help ( prove me i don't know how to read a doc ^^ )

I am french, sorry if my english is not perfect

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.10
  user: mqtt
  password: xxxxxx

database:
  path: /db/frigate.db

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous

ffmpeg:
  global_args: -hide_banner -loglevel warning

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True

record:
  enabled: True
  retain:
    days: 3

cameras:
# ---------------
  jardin:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx:554/H.264
          roles:
            - detect
            - rtmp
            - record
    record:
      enabled: True
    detect:
      width: 1920
      height: 1080
      fps: 10
    motion:
      mask:
        - 191,514,194,0,115,0,0,0,0,1080,445,1080
        - 418,87,1310,46,1920,271,1920,0,410,0
# --------------
  salon:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxx:554/stream1
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: True


# -------------
  entree:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxx:554/stream1
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: True
    motion:
      mask:
        - 0,222,778,194,1472,240,1691,454,1920,619,1920,0,0,0
```

### Relevant log output

```shell
no error in the frigate docker logs
```

### FFprobe output from your camera

```shell
can successfuly done the command, possible problem is the '!' in my password i can't protect successfully in the commandline
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

TP Link Tapo C200
