### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by markfrancisonly** [blakeblackshear/frigate#3276]
### Describe the problem you are having

Frigate docker container fails to operate using macvlan networking

### Version

0.11.0-D2C3CDC

### Frigate config file

```yaml
# docker-compose.yml

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-beta2
    device_cgroup_rules:
      - 'c *:* rmw'
    shm_size: '1024mb'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate.yml:/config/config.yml:ro
      - ./database:/config/database
      - /media/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

    networks:
      vlan100:
        ipv4_address: 10.1.1.100

networks:
  vlan100:
    name: vlan100
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

Macvlan networks are needed to assign a docker container a unique mac address and ip address that can then be firewalled.

Frigate web interface fails to load when it's container is connected to a macvlan network. Issue can be reproduced by creating a frigate container with a macvlan network using the host machine's main network adapter as a parent interface. 

Once setup, the following url is not accessible:
http://10.1.1.100:5000/api/config

and the result is:
502 Bad Gateway
nginx/1.18.0

The frigate user interface never loads.

**Comment by markfrancisonly** [comment]
Some portions of my docker-compose.yml have no effect, just forgot to remove these lines:   
```
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```
