### ISSUE TITLE
[Support]: Mqtt availability flaps on and off

### ISSUE THREAD

**Issue by flacjacket** [blakeblackshear/frigate#3280]
### Describe the problem you are having

For the frigate instance that I am running, it looks like the MQTT client keeps re-connecting over and over, and each time it does so, sends an `"offline"` message, followed shortly by the `"online"` message as it comes back up to the `frigate/available` topic. The `"offline"` message is not retained, so it does not appear to be the LWT tripping. This happens continuously every couple seconds. Because of this, the Home Assistant entities have their sensors flicker available and unavailable, because the availability topic is set to look at the `frigate/available` topic.

On each reconnect, frigate would receive a lot of messages on various `frigate/#` topics, including for some cameras that are no longer used but which must have had messages retained. I removed all of the retained `frigate/#` topics and continue to have this problem. I am also running a separate testing frigate instance on this same machine, and have manually set the topic prefix to `frigatetesting`, and can see the appropriate messages coming through there.

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: <redacted>
  user: <redacted>
  password: <redacted>

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: True
  fps: 5
  stationary:
    interval: 0

record:
  enabled: True
  retain:
    days: 3
    mode: all

snapshots:
  enabled: True
  bounding_box: True

rtmp:
  enabled: False

logger:
  default: info
  #logs:
  #  frigate.mqtt: debug

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - detect
            - record
  front:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - record
        - path: <redacted>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
  driveway:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - record
        - path: <redacted>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
  porch:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - record
        - path: <redacted>
          roles:
            - detect
  back:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - record
        - path: <redacted>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
  side:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - record
        - path: <redacted>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6
  garage:
    ffmpeg:
      inputs:
        - path: <redacted>
          roles:
            - record
        - path: <redacted>
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 6

database:
  path: /db/frigate.db
```

### Relevant log output

```shell
frigate              | [2022-05-31 18:50:50] frigate.mqtt                   DEBUG   : MQTT connected
frigate              | [2022-05-31 18:50:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:50] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:52] frigate.mqtt                   DEBUG   : MQTT connected
frigate              | [2022-05-31 18:50:52] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:52] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:54] frigate.mqtt                   DEBUG   : MQTT connected
frigate              | [2022-05-31 18:50:54] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:54] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:56] frigate.mqtt                   DEBUG   : MQTT connected
frigate              | [2022-05-31 18:50:56] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:56] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:58] frigate.mqtt                   DEBUG   : MQTT connected
frigate              | [2022-05-31 18:50:58] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
frigate              | [2022-05-31 18:50:58] frigate.mqtt                   DEBUG   : Received mqtt message on frigate/available.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
