### ISSUE TITLE
The new rtmp feature fails - ffmpeg sent a broken frame. something is wrong (0.8.0beta1)

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#330]
**Describe the bug**
When "roles: -rtmp" is enabled the camera does not start up proper, if commented out it works.

Sidenote (already reported here [Issue 328)](https://github.com/blakeblackshear/frigate/issues/328) Any camera with HEVC and H.265 codec does not work at all, clearly stated by the flv debug log output `Video codec hevc not compatible with flv`

**Version of frigate**
0.8.0beta1

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
logger:
  default: debug
  logs:
    frigate.mqtt: error
    frigate.video: debug

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.3.44
  user: username
  password: password
  topic_prefix: frigate

save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 15

ffmpeg:
  global_args: -loglevel debug
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -vsync
    - drop

objects:
  track:
    - person
  filters:
    person:
      min_area: 25000
#      min_area: 5000
      max_area: 100000
      threshold: 0.8
      min_score: 0.5

cameras:
  cam3_framsidan:
    ffmpeg:
      inputs:
        - path: rtsp://camop:bleh!@192.168.3.8:554/Streaming/Channels/1
          roles:
            - detect
            - rtmp
    fps: 8
    height: 1520
    width: 2688
    mask: 'poly,0,1518,0,0,2687,0,2687,644,2305,542,2290,463,2115,406,1889,401,1922,119,1794,17,1393,43,1381,468,1174,523,889,485,804,337,835,216,502,221,512,539,414,615,433,1518'
    zones:
      buskarna_cam3:
        coordinates: 0,1518,0,0,2687,0,2687,644,2305,542,2290,463,2115,406,1889,401,1922,119,1794,17,1393,43,1381,468,1174,523,889,485,804,337,835,216,502,221,512,539,414,615,433,1518
    objects:
      track:
        - person
      filters:
        person:
          min_area: 20000
          max_area: 300000
          threshold: 0.8
          min_score: 0.5


```

**Logs**
Please see here for details [hastebin link](https://hastebin.com/ahukoyugin.yaml)

**Frigate debug stats**
```
N/A
```

**FFprobe from your camera**

Run the following command and paste output below
```
root@docker04:/usr/share/dockers/frigate/config# ffprobe 'rtsp://camop:supersecret@192.168.3.8:554/Streaming/Channels/1'
ffprobe version 3.2.15-0+deb9u1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version=0+deb9u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[rtsp @ 0x55832fa54740] max delay reached. need to consume packet
[rtsp @ 0x55832fa54740] RTP: missed 170 packets
[h264 @ 0x55832fa57a40] cabac decode of qscale diff failed at 23 11
[h264 @ 0x55832fa57a40] error while decoding MB 23 11, bytestream 467308
[h264 @ 0x55832fa57a40] concealing 14138 DC, 14138 AC, 14138 MV errors in P frame
[rtsp @ 0x55832fa54740] max delay reached. need to consume packet
[rtsp @ 0x55832fa54740] RTP: missed 80 packets
[rtsp @ 0x55832fa54740] max delay reached. need to consume packet
[rtsp @ 0x55832fa54740] RTP: missed 898 packets
[h264 @ 0x55832fa57a40] concealing 13961 DC, 13961 AC, 13961 MV errors in P frame
[rtsp @ 0x55832fa54740] max delay reached. need to consume packet
[rtsp @ 0x55832fa54740] RTP: missed 84 packets
[h264 @ 0x55832fa57a40] Increasing reorder buffer to 1
[h264 @ 0x55832fa57a40] concealing 7126 DC, 7126 AC, 7126 MV errors in P frame
[rtsp @ 0x55832fa54740] max delay reached. need to consume packet
[rtsp @ 0x55832fa54740] RTP: missed 267 packets
[h264 @ 0x55832fa57a40] concealing 11756 DC, 11756 AC, 11756 MV errors in P frame
[rtsp @ 0x55832fa54740] max delay reached. need to consume packet
[rtsp @ 0x55832fa54740] RTP: missed 285 packets
[h264 @ 0x55832fa57a40] error while decoding MB 86 33, bytestream -5
[h264 @ 0x55832fa57a40] concealing 10379 DC, 10379 AC, 10379 MV errors in P frame
Input #0, rtsp, from 'rtsp://camop:kr1x0rkr4x0r!@192.168.21.32:554/Streaming/Channels/1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.600000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 1:1 DAR 168:95], 20 fps, 20 tbr, 90k tbn, 40 tbc
root@docker04:/usr/share/dockers/frigate/config#

```

**Screenshots**
N/A

**Computer Hardware**
 - OS: [Debian - AMD64 docker]
 - Coral Version: [USB]
 - Network Setup: [Wired]

**Camera Info:**
 - Manufacturer: [Hikvision]
 - Model: [DS-2CD2T42WD-I5]
 - Resolution: [4MP]
 - FPS: [8]

**Additional context**
With 0.7.3 at startup, for like 5-10 minutes there are restarts and "broken frames" just like this - but it settles down after 5-10 minutes and all works like expected without any issues.
Could the broken frames be ignored rather than just throwing an error?

The camera (cam3_framsidan) works great in 0.7.3. But simply will not load at all in 0.8.0.

**Comment by blakeblackshear** [comment]
Switching the camera to h264 isn't an option? I will have to do some digging on h265. At the very least, I will update the camera entities in homeassistant to work with mjpeg even if rtmp isn't available.

**Comment by tubalainen** [comment]
Hi Blake.

Nah, the camera above is not the H.265 one - its a h264.

**Comment by blakeblackshear** [comment]
Try this to see if injecting an empty audio stream helps:
```yaml
logger:
  default: debug
  logs:
    frigate.mqtt: error
    frigate.video: debug

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.3.44
  user: username
  password: password
  topic_prefix: frigate

save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 15

ffmpeg:
  global_args: -loglevel debug
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -vsync
    - drop

objects:
  track:
    - person
  filters:
    person:
      min_area: 25000
#      min_area: 5000
      max_area: 100000
      threshold: 0.8
      min_score: 0.5

cameras:
  cam3_framsidan:
    ffmpeg:
      inputs:
        - path: rtsp://camop:bleh!@192.168.3.8:554/Streaming/Channels/1
          roles:
            - detect
            - rtmp
      output_args:
        rtmp: -f lavfi -i anullsrc=channel_layout=mono:sample_rate=16000 -c:v copy -c:a aac -shortest -f flv
    fps: 8
    height: 1520
    width: 2688
    mask: 'poly,0,1518,0,0,2687,0,2687,644,2305,542,2290,463,2115,406,1889,401,1922,119,1794,17,1393,43,1381,468,1174,523,889,485,804,337,835,216,502,221,512,539,414,615,433,1518'
    zones:
      buskarna_cam3:
        coordinates: 0,1518,0,0,2687,0,2687,644,2305,542,2290,463,2115,406,1889,401,1922,119,1794,17,1393,43,1381,468,1174,523,889,485,804,337,835,216,502,221,512,539,414,615,433,1518
    objects:
      track:
        - person
      filters:
        person:
          min_area: 20000
          max_area: 300000
          threshold: 0.8
          min_score: 0.5
```
