### ISSUE TITLE
[Config Support]: Frigate issues with EzViz DB1C 

### ISSUE THREAD

**Issue by asantaga** [blakeblackshear/frigate#3308]
### Describe the problem you are having

EzViz DB1C works for liveview ,clips but not for recording

When i go to the recordings page ,i get playback cannot continue, no available working playlists.

I think this is due to the H265 format of the camera but I cant work out how to resolve it. The files are being recorded correctly on the disk though...

### Version

0.11.0-D2C3CDC

### Frigate config file

```yaml
## Removed two other cameras which work fine.

mqtt:
  host: 192.168.0.204
#ui:
  use_experimental: True

detectors:
  cpu1:
    type: cpu

birdseye:
  enabled: true

cameras:
  ezviz_doorbell:
    ffmpeg:

      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.0.55/Streaming/Channels/101
          roles:
            - clips
            - record
            - detect
    rtmp:
      enabled: false
    detect:
      width: 1536
      height: 1536
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    motion:
      mask:
        - 1536,1102,1536,0,0,0,0,1118
    record:
      enabled: True
      retain:
        days: 10
      events:
        retain:
          default: 10
```

### Relevant log output

```shell
[2022-06-06 11:55:01] frigate.video                  ERROR   : ezviz_doorbell: Unable to read frames from ffmpeg process.
[2022-06-06 11:55:01] frigate.video                  ERROR   : ezviz_doorbell: ffmpeg process is not running. exiting capture thread...
[2022-06-06 11:55:10] watchdog.ezviz_doorbell        ERROR   : Ffmpeg process crashed unexpectedly for ezviz_doorbell.
[2022-06-06 11:55:10] watchdog.ezviz_doorbell        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":91.84,"pid":215}},"ezviz_doorbell":{"camera_fps":5.1,"capture_pid":230,"detection_fps":0.0,"pid":224,"process_fps":5.1,"skipped_fps":0.0},"frontroom":{"camera_fps":5.1,"capture_pid":228,"detection_fps":0.0,"pid":223,"process_fps":5.1,"skipped_fps":0.0},"pantilt":{"camera_fps":5.1,"capture_pid":226,"detection_fps":0.0,"pid":221,"process_fps":5.1,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":55.9,"mount_type":"tmpfs","total":67.1,"used":11.2},"/media/frigate/clips":{"free":1201915.9,"mount_type":"ext4","total":1967925.7,"used":665973.1},"/media/frigate/recordings":{"free":1201915.9,"mount_type":"ext4","total":1967925.7,"used":665973.1},"/tmp/cache":{"free":307047.6,"mount_type":"overlay","total":502467.1,"used":169824.1}},"temperatures":{},"uptime":181,"version":"0.11.0-d2c3cdc"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Same behaviour on stable release, tried this on latest to be sure it wasnt fixed/work-d around.
Many thanks
