### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by sygys** [blakeblackshear/frigate#3316]
### Describe the problem you are having

I have one camera with no detect rules in the config and still it will keep detecting persons.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
camera_over_wit:
    ffmpeg:
      inputs:
        - path: rtsp://admin:ef9fwew7@192.168.178.65/cam/realmonitor?channel=1&subtype=0&authbasic=YvTY4OTcdbvedd
          roles:
            - rtmp
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
```

### Relevant log output

```shell
nothing to see in the log files no errors relating to this.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
