### ISSUE TITLE
Camera specific MQTT settings not allowed (0.8.0beta1)

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#332]
**Describe the bug**
The camera specific MQTT settings are not allowed.

**Version of frigate**
0.8.0beta1

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
cameras:
  cam9_uppfart:
    ffmpeg:
      inputs:
        - path: rtsp://camop:bleh123@192.168.1.2:554/Streaming/Channels/1
          roles:
            - clips
            - detect
            - rtmp
      output_args:
        rtmp: -c:v h264_vaapi -c:a copy -vf format=nv12|vaapi,hwupload -f flv
    rtmp:
      enabled: True
    width: 3840
    height: 2160
    fps: 8
    best_image_timeout: 60
    snapshots:
      show_timestamp: False
      draw_zones: True
      draw_bounding_boxes: True
      crop_to_region: False
    save_clips:
      enabled: True
      pre_capture: 30
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    mask: 'poly,0,682,0,0,3838,0,3838,665,3519,492,3519,424,2526,71,2570,326,2919,244,3180,326,3245,444,3285,556,3204,719,3000,929,2648,949,1973,831,1501,685,833,373'
    zones:
      vagen:
        coordinates: 0,682,0,0,3838,0,3838,665,3519,492,3519,424,2526,71,2570,326,2919,244,3180,326,3245,444,3285,556,3204,719,3000,929,2648,949,1973,831,1501,685,833,373
    mqtt:
      crop_to_region: True
      snapshot_height: 175
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 20000
          max_area: 1000000
          threshold: 0.8
        car:
          min_area: 200000
          max_area: 2000000
          threshold: 0.8
```

**Logs**
```
2020-12-07T15:31:48.676691288Z  * Starting nginx nginx
2020-12-07T15:31:48.682427276Z    ...done.
2020-12-07T15:31:49.252735644Z frigate.app                    ERROR   : Error parsing config: extra keys not allowed @ data['cameras']['cam9_uppfart']['mqtt']

```
