### ISSUE TITLE
[Support]: Getting Your config file is not valid! error

### ISSUE THREAD

**Issue by drumstick77** [blakeblackshear/frigate#3321]
### Describe the problem you are having

Hi all,

I'm new to HA and frigate, so apologies for the newbie questions.

Ive got MQTT running already for sometime and when I'm trying to run frigate, I'm getting an error that my config is not valid

I've posted my frigate.yml below
as well as the error from log

Not too sure where I've gone wrong here.
I've got a XVR that's RSTP capable running on port 554.

Cheers

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: X.X.X.XX
  port: 1883
  user: mqttuser
  password: mymqttpassword
  stats_interval: 60

  cameras:
    back:
      ffmpeg:
        inputs:
          - path: rtsp://username:password@X.X.X.X:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
      detect:
        width: 1280
        height: 720

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 16:59:42] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
2 validation errors for FrigateConfig
mqtt -> cameras
  extra fields not permitted (type=value_error.extra)
cameras
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
mqtt -> cameras
  extra fields not permitted (type=value_error.extra)
cameras
  field required (type=value_error.missing)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua
