### ISSUE TITLE
[Config Support]: Disk i/o error

### ISSUE THREAD

**Issue by goshi0** [blakeblackshear/frigate#3324]
### Describe the problem you are having

Frigate refuses to start under the disk io error, if you dont pass the docker volume of media/frigate, it works correctly

### Version

stable

### Frigate config file

```yaml
frigate:
    container_name: frigate
   # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-beta2
    shm_size: "64mb" # update for your cameras based on calculation above
    #devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/dockers/frigate/config/config.yml:/config/config.yml:ro
      - /srv/5fba792b-8c5a-4e2e-9572-66ea9ec631f2/Camaras:/media/frigate
      #- /srv/5fba792b-8c5a-4e2e-9572-66ea9ec631f2/Camaras:/prueba
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5001:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:52:55] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:52:55] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:52:55] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Proxmox running a VM with a OMV here the docker has direct access to the OMV's HDD
