### ISSUE TITLE
[Support]:Issue with new ffmpeg builds in dev branch

### ISSUE THREAD

**Issue by tungmeister** [blakeblackshear/frigate#3325]
### Describe the problem you are having

ffmpeg fails to run on dev branch builds since the introduction of new ffmpg build. 

### Version

0.11.0-97E18B3

### Frigate config file

```yaml
ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
        - -c:v
        - h264_qsv
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: -vf hwdownload,format=nv12 -f rawvideo -pix_fmt yuvj420p
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy


Also tried with the args shown in the commit:

hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
```

### Relevant log output

```shell
[2022-06-10 10:56:55] ffmpeg.Drive.detect ERROR : Failed to inject frame into filter network: Function not implemented

[2022-06-10 10:56:55] ffmpeg.Drive.detect ERROR : Error while processing the decoded data for stream #0:0

[2022-06-10 10:56:55] watchdog.Garden ERROR : Ffmpeg process crashed unexpectedly for Garden.

[2022-06-10 10:56:55] watchdog.Garden ERROR : The following ffmpeg logs include the last 100 lines prior to exit.

[2022-06-10 10:56:55] ffmpeg.Garden.detect ERROR : Option hwaccel (use HW accelerated decoding) cannot be applied to output url yuv420p -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
...
```

### FFprobe output from your camera

```shell
configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:****@10.0.0.110:554/Streaming/Channels/103/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 10 fps, 24 tbr, 90k tbn, 20 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, mono, fltp
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

hikvision

**Comment by blakeblackshear** [comment]
What specific intel processor are you running?

**Comment by tungmeister** [comment]
i5-10400

**Comment by noelhibbard** [comment]
@tungmeister I see you have a problem with your input args -stimeout needs to be -timeout for ffmpeg5.

Bad: ```input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1```

Good: ```input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1```

**Comment by blakeblackshear** [comment]
Can you give this image a try? `blakeblackshear/frigate:0.11.0-1d45b0b`

Update your hwaccel args to:

```yaml
      hwaccel_args: -c:v h264_qsv
```

**Comment by tungmeister** [comment]
@blakeblackshear Just tested it however I'm getting the below:
```
[2022-06-11 20:00:45] watchdog.Garden ERROR : Ffmpeg process crashed unexpectedly for Garden.

[2022-06-11 20:00:45] watchdog.Garden ERROR : The following ffmpeg logs include the last 100 lines prior to exit.

[2022-06-11 20:00:45] ffmpeg.Garden.detect ERROR : [rtsp @ 0x557b209acc00] Unable to open RTSP for listening

[2022-06-11 20:00:45] ffmpeg.Garden.detect ERROR : rtsp://admin:l0caladm1n@10.0.0.241:554/Streaming/Channels/103/: Cannot assign requested address

[2022-06-11 20:00:45] frigate.video ERROR : Drive: Unable to read frames from ffmpeg process.

[2022-06-11 20:00:45] frigate.video ERROR : Drive: ffmpeg process is not running. exiting capture thread...

[2022-06-11 20:00:45] ffmpeg.Garden.record ERROR : [rtsp @ 0x5604237e5c80] Unable to open RTSP for listening

[2022-06-11 20:00:45] ffmpeg.Garden.record ERROR : rtsp://admin:l0caladm1n@10.0.0.241:554/Streaming/Channels/101/: Cannot assign requested address
```

**Comment by leloch** [comment]
I had a lot of issues as well with HW access on Intel using branch (pre-built docker container).

Got `i5-8500T` with 'GEN 9.5' QSV - my cameras are Hikvision 4K units, I want to keep all video in h264 end-to-end (to minimize recompressions/overhead) since support for HEVC in the browsers is a mess.

The following seems to work well in the latest 0.11 beta Fritage version (besides `inputs: path`, the options are global and I do not override it on the camera level):
```
ffmpeg:
   output_args:
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
     detect: -vf fps=fps=5,vpp_qsv=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -an -f rawvideo
   input_args: -rtsp_transport tcp -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental
   hwaccel_args: -hwaccel qsv -c:v h264_qsv
```
This config keeps input and recording as h264 (as per camera output - no re-encoding needed) and creates a downsampled stream for detection purpose. The `intel_gpu_top` tools confirms around ~ 10% Video engine utilization per 4K camera stream.
