### ISSUE TITLE
[Support]: Attaching multiple NICs to frigate container. 

### ISSUE THREAD

**Issue by narayanvs** [blakeblackshear/frigate#3326]
### Describe the problem you are having

Its not a big problem & more of a docker question.  just trying to find a better way to handle this situation.

I have two NIC cards on my Unraid system . NIC 1 connects to my home network and vlans through the router. NIC 2 is isolated and just connects to CCTV network. 

I have connected frigate CT using the NIC1 for accessing it over home network and home assistant. also attched frigate CT to the NIC2 using a post argument. so it can access the camera stream. Everything works except this the container always fail to start on system reboot or docker service restart.. to fix this,  I always need go to container -> edit, edit a field so the "apply" button becomes available, and then click it. After this, the container works perfectly fine again. I have been reading this over the forums but couldn't find a way to  fix this cleanly..

Post argument used: _`; docker network connect --ip 192.168.2.103 br1 frigate`_

I am doing it this way so the heavy lifting of BW usage of multiple cameras will not chock my home LAN, also it is a security practice to protect the cameras from external access. I know it can be done using VLAN and ACLs but I setup it this way and it works :)

The question is - is there a better way to connect a second network to frigate container ? or am I doing it in wrong way and it is causing frigate to not start on system reboot ?

I have tried adding a delay of the container start after a system reboot (like 10-15 mins) but that did not help. 

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.2
  port: 1883
  user: mqtt-admin
  password: <Removed>

detectors:
  coral_pci:
    type: edgetpu
    device: pci

cameras:

  front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<Removed>@192.168.2.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:<Removed>@192.168.2.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
        - path: rtsp://admin:<Removed>@192.168.2.11:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 10
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - car
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    motion:
      mask:
        - 0,371,1280,329,1280,0,0,0
    objects:
      filters:
        person:
          mask:
            - 0,371,1280,329,1280,0,0,0
  parking:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<Removed>@192.168.2.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:<Removed>@192.168.2.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
        - path: rtsp://admin:<Removed>@192.168.2.12:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 10
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - car
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    zones:
      zone_0:
        coordinates: 1280,720,943,219,413,189,67,720

  patio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<Removed>@192.168.2.13:554//h264Preview_01_main
          roles:
            - record
        - path: rtsp://admin:<Removed>@192.168.2.13:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
    record:
      enabled: true
      retain:
        days: 10
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10


  garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<Removed>@192.168.2.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:<Removed>@192.168.2.14:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
        - path: rtsp://admin:<Removed>@192.168.2.14:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 10
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - car
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dahua
