### ISSUE TITLE
[Support]: 11 Beta - ffmpeg memory usage is higher than 0.10.1

### ISSUE THREAD

**Issue by Bonn93** [blakeblackshear/frigate#3328]
### Describe the problem you are having

Running the v0.11.0-beta2 docker image is consuming more GPU memory than before which puts pressure on other GPU applications sharing the GPU memory/buffers.

0.10.1 used 590MB for a 4K camera, and 98-102mb for some 2K reolink cameras. On the 11 beta2, the 4K camera is now using 800MB, and the 2K Cameras using 120MB. 

### Version

0.11.0 Beta 2

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
database:
  path: /db/frigate.db
mqtt:
  host: 10.5.80.20
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  mode: motion
live:
  height: 1080
  quality: 1
cameras:
  driveway:
    motion:
     mask:
      - 640,480,471,303,503,96,640,105
      - 0,167,640,144,640,0,0,0
      - 191,222,223,216,218,145,179,138
    zones:
     frontdoor:
       coordinates: 0,480,640,480,483,222,254,200,56,171
       objects:
         - person
    objects:
      track:
        - car
        - person
        - motorcycle
      filters:
        person:
          min_score: 0.6
          threshold: 0.7
          mask: 190,219,224,213,218,151,181,151
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      input_args:
        #- -avoid_negative_ts
        #- make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        #- -fflags
        #- +genpts+discardcorrupt
        #- -use_wallclock_as_timestamps
        #- "1"
        #- -rtsp_transport
        #- tcp
        #- -analyzeduration
        #- 1000M
        #- -probesize
        #- 1000M
      inputs:
        - path: rtsp://stream:stream@10.5.70.24:554//h264Preview_01_main
          roles:
            - record
        - path: rtsp://stream:stream@10.5.70.24:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 120 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_cuvid -c copy
        rtmp: -c:v h264_nvenc -an -f flv
    detect:
      width: 640
      height: 480
      fps: 4
      enabled: true
      max_disappeared: 25
    record:
      enabled: true
      retain_days: 3
      events:
        retain:
          default: 10
  backyard:
    motion:
     mask:
      - 0,0,0,187,248,145,274,188,310,244,352,124,640,172,640,0
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - cell phone
        - sports ball
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      input_args:
        #- -avoid_negative_ts
        #- make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        #- -fflags
        #- +genpts+discardcorrupt
        #- -use_wallclock_as_timestamps
        #- "1"
        #- -rtsp_transport
        #- tcp
      inputs:
        - path: rtsp://stream:stream@10.5.70.22:554//h264Preview_01_main
          roles:
            - record
        - path: rtsp://stream:stream@10.5.70.22:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_cuvid -c copy
        rtmp: -c:v h264_nvenc -an -f flv
    detect:
      width: 640
      height: 480
      fps: 4
      enabled: true
      max_disappeared: 25
    record:
      enabled: true
      retain_days: 3
      events:
        retain:
          default: 10
  streetcam:
    motion:
     mask:
      - 0,217,640,167,640,0,0,0
      - 181,194,229,251,272,190,220,139
      - 101,360,547,262,510,246,0,306
      - 50,360,155,360,43,208,0,161
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
        - cell phone
        - bird
    ffmpeg:
      inputs:
        - path: rtsp://stream:stream@10.5.70.23:554/h265Preview_01_main
          roles:
            - record
          hwaccel_args:
            - -c:v
            - hevc_cuvid
          input_args:
            #- -avoid_negative_ts
            #- make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            #- -fflags
            #- +genpts+discardcorrupt
            #- -use_wallclock_as_timestamps
            #- "1"
            #- -rtsp_transport
            #- tcp
        - path: rtsp://stream:stream@10.5.70.23:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
          hwaccel_args:
            - -c:v
            - h264_cuvid
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - "1"
            - -rtsp_transport
            - tcp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -crf 18 -c:a copy -vf format=yuv420p -b:v 6M -r 25
        rtmp: -c:v h264_nvenc -an -f flv
    detect:
      width: 640
      height: 360
      fps: 7
      enabled: True
      max_disappeared: 25
    record:
      enabled: True
      retain_days: 3
      events:
        retain:
          default: 10
```

### Relevant log output

```shell
### Beta 2, 11.
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P620         Off  | 00000000:1B:00.0 Off |                  N/A |
| 39%   53C    P0    N/A /  N/A |   1123MiB /  2048MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    991246      C   ffmpeg                            104MiB |
|    0   N/A  N/A    991249      C   ffmpeg                            794MiB |
|    0   N/A  N/A    991250      C   ffmpeg                            110MiB |
|    0   N/A  N/A    991254      C   ffmpeg                            110MiB |
+-----------------------------------------------------------------------------+
```

### FFprobe output from your camera

```shell
ffprobe rtsp://stream:stream@10.5.70.23:554/h265Preview_01_main
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://stream:stream@10.5.70.23:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: -0.018833, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"backyard":{"camera_fps":4.1,"capture_pid":231,"detection_fps":0.0,"pid":226,"process_fps":4.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.69,"pid":216}},"driveway":{"camera_fps":4.1,"capture_pid":229,"detection_fps":0.0,"pid":223,"process_fps":4.1,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":534.1,"mount_type":"tmpfs","total":536.9,"used":2.7},"/media/frigate/clips":{"free":1470344.2,"mount_type":"nfs4","total":2146434.5,"used":676090.3},"/media/frigate/recordings":{"free":1470344.2,"mount_type":"nfs4","total":2146434.5,"used":676090.3},"/tmp/cache":{"free":51783.9,"mount_type":"overlay","total":124968.9,"used":67450.8}},"temperatures":{},"uptime":407,"version":"0.11.0-d2c3cdc"},"streetcam":{"camera_fps":7.1,"capture_pid":232,"detection_fps":0.0,"pid":228,"process_fps":7.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 520A, 810A
