### ISSUE TITLE
[Support]: Recording won't play if first segment ends up with `503 Service Temporarily Unavailable`

### ISSUE THREAD

**Issue by peledzius** [blakeblackshear/frigate#3335]
### Describe the problem you are having

Related to #1862.

I can't play recording in UI or Home Assistant if first segment gives `503 Service Temporarily Unavailable` error. Every segment after is fine.

First segment plays fine in VLC(`../recordings/2022-06/12/19/svetaine/00.00.mp4`)

If I play `index.m3u8` file with "corrupt" segment in VLC, first segment is skipped and video starts from second segment.

```
$ curl http://192.168.222.100:5000//vod/2022-06/12/19/svetaine/seg-1-v1-a1.ts
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

<details>
<summary>index.m3u8</summary>

```
$ curl http://192.168.222.100:5000//vod/2022-06/12/19/svetaine/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
seg-1-v1-a1.ts
#EXTINF:10.000,
seg-2-v1-a1.ts
#EXTINF:10.000,
seg-3-v1-a1.ts
#EXTINF:10.000,
seg-4-v1-a1.ts
#EXTINF:10.000,
seg-5-v1-a1.ts
#EXTINF:10.000,
seg-6-v1-a1.ts
#EXTINF:10.000,
seg-7-v1-a1.ts
#EXTINF:10.000,
seg-8-v1-a1.ts
#EXTINF:10.000,
seg-9-v1-a1.ts
#EXTINF:10.000,
seg-10-v1-a1.ts
#EXTINF:10.000,
seg-11-v1-a1.ts
#EXTINF:10.000,
seg-12-v1-a1.ts
#EXTINF:10.000,
seg-13-v1-a1.ts
#EXTINF:10.000,
seg-14-v1-a1.ts
#EXTINF:10.000,
seg-15-v1-a1.ts
#EXTINF:10.000,
seg-16-v1-a1.ts
#EXTINF:10.000,
seg-17-v1-a1.ts
#EXTINF:10.000,
seg-18-v1-a1.ts
#EXTINF:10.000,
seg-19-v1-a1.ts
#EXTINF:10.000,
seg-20-v1-a1.ts
#EXTINF:10.000,
seg-21-v1-a1.ts
#EXTINF:10.000,
seg-22-v1-a1.ts
#EXTINF:10.000,
seg-23-v1-a1.ts
#EXTINF:10.000,
seg-24-v1-a1.ts
#EXTINF:10.000,
seg-25-v1-a1.ts
#EXTINF:10.000,
seg-26-v1-a1.ts
#EXTINF:10.000,
seg-27-v1-a1.ts
#EXTINF:10.000,
seg-28-v1-a1.ts
#EXTINF:10.000,
seg-29-v1-a1.ts
#EXTINF:10.000,
seg-30-v1-a1.ts
#EXTINF:10.000,
seg-31-v1-a1.ts
#EXTINF:10.000,
seg-32-v1-a1.ts
#EXTINF:10.000,
seg-33-v1-a1.ts
#EXTINF:10.000,
seg-34-v1-a1.ts
#EXTINF:10.000,
seg-35-v1-a1.ts
#EXTINF:10.000,
seg-36-v1-a1.ts
#EXTINF:10.000,
seg-37-v1-a1.ts
#EXTINF:10.000,
seg-38-v1-a1.ts
#EXTINF:10.000,
seg-39-v1-a1.ts
#EXTINF:10.000,
seg-40-v1-a1.ts
#EXTINF:10.000,
seg-41-v1-a1.ts
#EXTINF:10.000,
seg-42-v1-a1.ts
#EXTINF:10.000,
seg-43-v1-a1.ts
#EXTINF:10.000,
seg-44-v1-a1.ts
#EXTINF:10.000,
seg-45-v1-a1.ts
#EXTINF:10.000,
seg-46-v1-a1.ts
#EXTINF:10.000,
seg-47-v1-a1.ts
#EXTINF:10.000,
seg-48-v1-a1.ts
#EXTINF:10.000,
seg-49-v1-a1.ts
#EXTINF:10.000,
seg-50-v1-a1.ts
#EXTINF:10.000,
seg-51-v1-a1.ts
#EXTINF:10.000,
seg-52-v1-a1.ts
#EXTINF:10.000,
seg-53-v1-a1.ts
#EXTINF:10.000,
seg-54-v1-a1.ts
#EXTINF:10.000,
seg-55-v1-a1.ts
#EXTINF:10.000,
seg-56-v1-a1.ts
#EXTINF:10.000,
seg-57-v1-a1.ts
#EXTINF:10.000,
seg-58-v1-a1.ts
#EXTINF:10.000,
seg-59-v1-a1.ts
#EXTINF:10.000,
seg-60-v1-a1.ts
#EXTINF:10.000,
seg-61-v1-a1.ts
#EXTINF:10.000,
seg-62-v1-a1.ts
#EXTINF:10.000,
seg-63-v1-a1.ts
#EXTINF:10.000,
seg-64-v1-a1.ts
#EXTINF:10.000,
seg-65-v1-a1.ts
#EXTINF:10.000,
seg-66-v1-a1.ts
#EXTINF:10.000,
seg-67-v1-a1.ts
#EXTINF:10.000,
seg-68-v1-a1.ts
#EXTINF:10.000,
seg-69-v1-a1.ts
#EXTINF:10.000,
seg-70-v1-a1.ts
#EXTINF:10.000,
seg-71-v1-a1.ts
#EXTINF:10.000,
seg-72-v1-a1.ts
#EXTINF:10.000,
seg-73-v1-a1.ts
#EXTINF:10.000,
seg-74-v1-a1.ts
#EXTINF:10.000,
seg-75-v1-a1.ts
#EXTINF:10.000,
seg-76-v1-a1.ts
#EXTINF:10.000,
seg-77-v1-a1.ts
#EXTINF:10.000,
seg-78-v1-a1.ts
#EXTINF:10.000,
seg-79-v1-a1.ts
#EXTINF:10.000,
seg-80-v1-a1.ts
#EXTINF:10.000,
seg-81-v1-a1.ts
#EXTINF:10.000,
seg-82-v1-a1.ts
#EXTINF:10.000,
seg-83-v1-a1.ts
#EXTINF:10.000,
seg-84-v1-a1.ts
#EXTINF:10.000,
seg-85-v1-a1.ts
#EXTINF:10.000,
seg-86-v1-a1.ts
#EXTINF:10.000,
seg-87-v1-a1.ts
#EXTINF:10.000,
seg-88-v1-a1.ts
#EXTINF:10.000,
seg-89-v1-a1.ts
#EXTINF:10.000,
seg-90-v1-a1.ts
#EXTINF:10.000,
seg-91-v1-a1.ts
#EXTINF:10.000,
seg-92-v1-a1.ts
#EXTINF:10.000,
seg-93-v1-a1.ts
#EXTINF:10.000,
seg-94-v1-a1.ts
#EXTINF:10.000,
seg-95-v1-a1.ts
#EXTINF:10.000,
seg-96-v1-a1.ts
#EXTINF:10.000,
seg-97-v1-a1.ts
#EXTINF:10.000,
seg-98-v1-a1.ts
#EXTINF:10.000,
seg-99-v1-a1.ts
#EXTINF:10.000,
seg-100-v1-a1.ts
#EXTINF:10.000,
seg-101-v1-a1.ts
#EXTINF:2.824,
seg-102-v1-a1.ts
#EXT-X-ENDLIST
```

</details>

### Version

0.11.0-1d45b0b

### Frigate config file

```yaml
ffmpeg:
# hwaccel_args: -c:v h264_v4l2m2m
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

cameras:
  svetaine:
    ffmpeg:
      inputs:
        - path: 'rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.222.103:554/live/ch1'
          roles:
            - record
            - rtmp

detect:
  enabled: False
  width: 768
  height: 432
  fps: 5

record:
  enabled: True
  retain:
    days: 7

mqtt:
  host: 192.168.222.100
  user: frigate
  password: '{FRIGATE_MQTT_PASSWORD}'

birdseye:
  enabled: False
```

### Relevant log output

```shell
Nothing relevant
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://xxx:xxx@192.168.222.103:554/live/ch1':
  Metadata:
    title           : hysxrtpsion
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 768x432, 15 fps, 15 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Ubuntu Server

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Wansview Q5

### Any other information that may be helpful

RPi400
