### ISSUE TITLE
[Config Support]: Can u rescale the camera preview in the console?

### ISSUE THREAD

**Issue by asantaga** [blakeblackshear/frigate#3339]
### Describe the problem you are having

Hi there, 

I've looked for this in the docs and cant find it. Most of my cameras are either 1080p or 2k, and what Im noticing is in that when I preview the camera in the frigate ui (especially recordings) , the image is too big. Ideally it should be scaled to fit the browser window. 

is there a config for this affecting only the frigate UI?

Here is an example of what i get

![image](https://user-images.githubusercontent.com/2940224/173327069-8ce485a7-769d-4fa5-9625-0204f5d5825e.png)

thank you!

### Version

0.11.0 Beta 3 , but also other versions

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.204
ui:
  use_experimental: True

detectors:
  cpu1:
    type: cpu

birdseye:
  enabled: true

cameras:
  pantilt: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:yyyy@192.168.0.28/live0
          roles:
            - rtmp
            - detect
            - clips
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p


    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    motion:
      mask:
        - 1920,712,1920,0,0,0,0,750,505,632,698,625,773,716,1409,724,1400,635

    record:
      enabled: True
      retain:
        days: 10
      events:
        retain:
          default: 10




  frontroom: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:yyyyy@192.168.0.31:554/live0
          roles:
            - rtmp
            - detect
            - clips
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    motion:
      mask:
        - 584,531,1549,503,1552,592,1865,594,1920,576,1920,480,1920,0,569,0,563,95,570,168,576,250
    record:
      enabled: True
      retain:
        days: 10
      events:
        retain:
          default: 10


  doorbell: 
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:yyyyy@192.168.0.55/Streaming/Channels/101
          roles:
            - clips
            - record
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
#    rtmp:
#     enabled: false
    detect:
      width: 1536
      height: 1536
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 10
    motion:
      mask:
        - 1536,1102,1536,0,0,0,0,1118
    record:
      enabled: True
      retain:
        days: 10
      events:
        retain:
          default: 10
```

### Relevant log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by asantaga** [comment]
Just noticed, if I shrink the Y axis then after a bit of reduction it does render correctly, as soon as the Y goes beyond a point then it scales incorrectly.

thanks

**Comment by NickM-27** [comment]
This is from the docs, should do what you're asking:

```yaml
# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

```
