### ISSUE TITLE
[Support]: Events not getting recorded 

### ISSUE THREAD

**Issue by justdummyuser** [blakeblackshear/frigate#3340]
### Describe the problem you are having

Hi,

I've been using Frigate NVR from last 3 months without any issues, working flawlessly. Then, two days ago, all of a sudden recording of events has stopped working. I saw there is an update available for HA, Mosquito & Frigate and ran the same but no luck.

There are total 5 cameras setup with Frigate and all 5 cam's are reporting the feed (I can see it under Frigate sidebar menu), Even when i see Debug, i can see "person" is getting detected with bounding box. The only thing is, these events are not getting recorded. I've setup automation scripts to switch on/off smart bulbs based on when Frigate detects person in mentioned zone. This too has stopped working.

I suspected if it maybe due to MQTT misconfig but i can see all events triggered by Frigate. Tried to reinstall Frigate, Mosquito, HACS Frigate integration but all in vain. 

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: <IP address of HA>
  user: xxxx
  password: xxxx

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.85  

ffmpeg:
  global_args: '-hide_banner -loglevel fatal' 
  hwaccel_args: 
    - '-hwaccel' 
    - vaapi 
    - '-hwaccel_device' 
    - /dev/dri/renderD128 
    - '-hwaccel_output_format' 
    - yuv420p 

cameras:
  Front_View:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.22.17/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://username:password@192.168.22.17/Streaming/Channels/101
          roles:
            - record             
    rtmp:
      enabled: False
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - Front_Zone
    zones:
      Front_Zone:
        coordinates: 0,480,640,480,640,140,445,56,227,105,0,165
        objects:
          - person

  Back_View:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.22.18/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://username:password@192.168.22.18/Streaming/Channels/101
          roles:
            - record             
    rtmp:
      enabled: False
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - Back_Zone
    zones:
      Back_Zone:
        coordinates: 53,480,191,480,353,480,640,480,640,95,359,0,229,0,95,92
        objects:
          - person

  Cooler_View:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.22.19/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        
        - path: rtsp://username:password@192.168.22.19/Streaming/Channels/101
          roles:
            - record
                    
    rtmp:
      enabled: False
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - Cooler_Zone
    zones:
      Cooler_Zone:
        coordinates: 211,217,201,301,181,480,397,480,640,480,640,79,564,58,464,29,381,21,335,67,289,105,217,159
        objects:
          - person
    
    motion:
      mask: 0,47,0,480,168,480,210,156,335,51
    
    objects:
      filters:
        person:
          mask: 0,47,0,480,168,480,210,156,335,51
  
  Parlour_View:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.22.20/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://username:password@192.168.22.20/Streaming/Channels/101
          roles:
            - record             
    rtmp:
      enabled: False
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - Parlour_Zone
    zones:
      Parlour_Zone:
        coordinates: 443,480,99,480,407,75,441,75,474,81
        objects:
          - person

    motion:
      mask: 0,86,0,480,80,480,409,65,322,0

    objects:
      filters:
        person:
          mask: 0,86,0,480,80,480,409,65,322,0

  Parlour_Gate:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.22.21/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://username:password@192.168.22.21/Streaming/Channels/101
          roles:
            - record             
    rtmp:
      enabled: False
    detect:
      width: 640
      height: 480
    record:
      enabled: True
      events:
        required_zones:
          - PGate_Zone
    zones:
      PGate_Zone:
        coordinates: 408,480,163,0,26,0,0,480
        objects:
          - person
    
    motion:
      mask: 435,480,640,480,640,175,388,0,171,0
    
    objects:
      filters:
        person:
          mask: 435,480,640,480,640,175,388,0,171,0
```

### Relevant log output

```shell
No relevant logs. Sharing whatever found under logs -

[2022-06-13 14:40:43] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33202]
[2022-06-13 14:41:00] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:39952]
[2022-06-13 14:42:03] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:39952]
[2022-06-13 14:44:16] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39358]
[2022-06-13 14:44:19] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39358]
[2022-06-13 16:45:51] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41492]
[2022-06-13 16:45:57] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41492]
[2022-06-13 16:56:06] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45722]
[2022-06-13 16:59:03] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45722]
[2022-06-13 17:09:06] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:37120]
```

### FFprobe output from your camera

```shell
not sure how to run this command. From HA CLI, throwing error "ffprobe: command not found"
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
