### ISSUE TITLE
PLUS_API_KEY not set but is in config 

### ISSUE THREAD

**Issue by angrycatmeowmeow** [blakeblackshear/frigate#3346]
### Describe the problem you are having

Getting error in logs when trying to upload an image to Frigate+

`[2022-06-14 16:35:01] frigate.http                   ERROR   : PLUS_API_KEY environment variable is not set`

### Version

0.11.0 beta4

### Frigate config file

```yaml
# frigate.yml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  # Required: host name
  host: 192.168.86.25
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: homeassistant
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: 7
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  # Name of your camera
  Garage_East:
    ffmpeg:
      inputs:
        - path: rtsp://admin:*@192.168.86.239:554/h264Preview_01_sub
          roles:
            - detect
            - record
        - path: rtsp://admin:@192.168.86.239:554/h264Preview_01_main
          roles:
            - rtmp
    record:
      enabled: True
      events:
        retain:
          default: 2
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask:
            - >-
              274,319,421,458,574,300,445,191
  Garage_West:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Z@192.168.86.48:554/h264Preview_01_sub
          roles:
            - detect
            - record
        - path: rtsp://admin:@192.168.86.48:554/h264Preview_01_main
          roles:
            - rtmp
    record:
      enabled: True
      events:
        retain:
          default: 2
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
  # Name of your camera
  Lounge:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Z@192.168.86.235:554/h264Preview_01_sub
          roles:
            - detect
            - record
        - path: rtsp://admin:@192.168.86.235:554/h264Preview_01_main
          roles:
            - rtmp
    record:
      enabled: True
      events:
        retain:
          default: 2
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
  # Name of your camera
  Front_Porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.86.40:554/h264Preview_01_sub
          roles@192.168.86.40:554/h264Preview_01_sub
          roles:
            - detect
            - record
        - path: rtsp://admin:@192.168.86.40:554/h264Preview_01_main
          roles:
            - rtmp
    record:
      enabled: True
      events:
        retain:
          default: 2
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
              
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 2

environment_vars:
  PLUS_API_KEY: my-api-key
```

### Relevant log output

```shell
[2022-06-14 16:34:57] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:50366]
[2022-06-14 16:35:01] frigate.http                   ERROR   : PLUS_API_KEY environment variable is not set
[2022-06-14 16:35:09] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:50366]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
