### ISSUE TITLE
[Config Support]: Come someone help me with recording events in a zone?

### ISSUE THREAD

**Issue by mlittle408** [blakeblackshear/frigate#3347]
### Describe the problem you are having

I cannot figure out why events aren't being recorded in my zones. The camera in the area has three zones. The first zone is driveway and I want to capture any person, car, dog or bicycle that enters that zone. Basically anything that enters that zone. The second zone is Garage and I only want to capture persons or dogs in that zone (but keeps capturing cars). Finally is the Grass zone and I only need to capture persons or dogs in that zone. I have attached the section of my config that deals with that zone. The camera that deals with these zones is "back_yard" I've attached my config. At the moment no . 

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.6
  user: homeassistant
  password: xxxxxxxxxxx

cameras:

  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxx@192.168.1.230:554/live
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,755,317,484,750,193,909,147,1065,147,1060,0,0,0
        - 1920,1080,1233,1080,1332,0,1920,0
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 7

  back_porch:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxx@192.168.1.84:554/live
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 7
      events:
        retain:
          default: 7

  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxx@192.168.1.122:554/live
          roles:
            - detect
    motion:
      mask:
        - 392,197,496,227,874,235,959,0,0,0,0,335
        - 1518,244,1920,418,1920,0,1535,0
    zones:
      driveway:
        coordinates: 629,332,823,340,830,226,558,226,390,331
        objects:
          - car
          - person
          - dog
          - bicycle
      garage:
        coordinates: 1733,1080,1461,578,1165,348,279,339,0,486,0,1080
        objects:
          - dog
          - person
      grass:
        coordinates: 1920,1080,1920,449,1535,281,1499,424,1337,433
        objects:
          - dog
          - person
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 7
      events:
        required_zones:
          - driveway
          - garage
          - grass
        retain:
          default: 7

#snapshots:
#  enabled: True
#  timestamp: True
#  bounding_box: True
#  retain:
#    default: 7

objects:
 track:
   - person
   - car
   - dog
   - bicycle

record:
  enabled: True
  retain_days: 7
  events:
    retain:
      default: 7

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

live:
  height: 720
  quality: 8
```

### Relevant log output

```shell
Nothing relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
You need to set `required_zones` for snapshots as well on that camera, right now snapshots will still be created no matter what

**Comment by mlittle408** [comment]
So I do this in the config for that camera?

snapshots:
    required_zones:
      - driveway
      - garage
      - grass

**Comment by NickM-27** [comment]
I would do:

```yaml

snapshots:
  enabled: true
  required_zones:
    - driveway
    - garage
    - grass
```

**Comment by NickM-27** [comment]
Actually hold on, I may have misunderstood the problem. Is the issue that objects are being recorded when they shouldn't, or that no events are being recorded when you expect them to be?

**Comment by mlittle408** [comment]
Well... To make sure I was communicating the problem correctly, I went out and test all the zones and everything seems to be working correctly. Basically, I don't want vehicles recorded in the driveway zone. Can you answer a partially related question? What's the difference between recordings and snapshots? 

In the end, I don't want vehicles recorded in the driveway zone. 

Thanks for all your help!

**Comment by NickM-27** [comment]
Your driveway zone seems to include car which would explain why it is having an event created

```yaml
driveway:
  coordinates: 629,332,823,340,830,226,558,226,390,331
  objects:
    - car
    - person
    - dog
    - bicycle
```
