### ISSUE TITLE
[Config Support]: Missing intervals in recordings

### ISSUE THREAD

**Issue by joshbenner** [blakeblackshear/frigate#3353]
### Describe the problem you are having

Recordings often skip various stretches of time, losing video data. I frequently see gaps between 5s and 1m, and have observed gaps as large as 15 minutes.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
# yaml-language-server: $schema=http://frigate:5000/api/config/schema
mqtt:
  host: 192.168.13.13
  user: frigate
  password: redacted
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: true
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects
objects:
  track:
    - person
    - vehicle
    - animal
  filters:
    person:
      min_score: 0.3
      #threshold: 0.4
    animal:
      min_score: 0.3
      threshold: 0.4
ffmpeg:
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -rtsp_transport tcp -stimeout 5000000
  hwaccel_args:
    - -c:v
    - h264_cuvid
snapshots:
  enabled: true
  bounding_box: true
birdseye:
  mode: continuous
rtmp:
  enabled: false
cameras:
  cam-driveway1:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.11:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp
    objects:
      filters:
        vehicle:
          mask:
            - 882,424,1087,491,1280,568,1280,164,926,82
    motion:
      mask:
        - 28,0,1280,0,1280,123,875,53,588,64,383,91,46,181
    detect:
      width: 1280
      height: 720
      fps: 5
  cam-porch1:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp
    motion:
      mask:
        - 314,47,592,45,594,21,535,0,114,0,0,0,0,132
    detect:
      width: 704
      height: 480
      fps: 5
  cam-sideyard:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp
    detect:
      width: 704
      height: 480
      fps: 5
  cam-doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.70:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.70:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      filters:
        animal:
          mask:
            - 62,330,70,345,98,344,122,363,135,346,155,337,176,317,153,290,95,289,67,308
    detect:
      width: 720
      height: 576
      fps: 5
  cam-backyard:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.14:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
  cam-garage:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.15:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.165.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- rtmp
    objects:
      track:
        - person
        - animal
    detect:
      width: 704
      height: 480
      fps: 5
```

### Relevant log output

```shell
[2022-06-15 14:21:03] frigate.app INFO : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-06-15 14:21:03] peewee_migrate INFO : Starting migrations
There is nothing to migrate
[2022-06-15 14:21:03] peewee_migrate INFO : There is nothing to migrate
[2022-06-15 14:21:03] detector.coral INFO : Starting detection process: 226
[2022-06-15 14:21:03] frigate.app INFO : Output process started: 228
[2022-06-15 14:21:03] ws4py INFO : Using epoll
[2022-06-15 14:21:03] frigate.app INFO : Camera processor started for cam-driveway1: 234
[2022-06-15 14:21:03] frigate.app INFO : Camera processor started for cam-porch1: 237
[2022-06-15 14:21:03] frigate.app INFO : Camera processor started for cam-sideyard: 238
[2022-06-15 14:21:03] frigate.app INFO : Camera processor started for cam-doorbell: 240
[2022-06-15 14:21:03] frigate.app INFO : Camera processor started for cam-backyard: 241
[2022-06-15 14:21:03] frigate.app INFO : Camera processor started for cam-garage: 243
[2022-06-15 14:21:03] frigate.app INFO : Capture process started for cam-driveway1: 245
[2022-06-15 14:21:03] frigate.app INFO : Capture process started for cam-porch1: 248
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-sideyard: 253
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-doorbell: 258
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-backyard: 265
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-garage: 269
[2022-06-15 14:21:04] ws4py INFO : Using epoll
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-sideyard: 253
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-doorbell: 258
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-backyard: 265
[2022-06-15 14:21:04] frigate.app INFO : Capture process started for cam-garage: 269
[2022-06-15 14:21:04] ws4py INFO : Using epoll
[2022-06-15 14:21:03] frigate.edgetpu INFO : Attempting to load TPU as usb
[2022-06-15 14:21:06] frigate.edgetpu INFO : TPU found
```

### Frigate stats

```json
{"cam-backyard":{"camera_fps":5.1,"capture_pid":258,"detection_fps":0.0,"pid":239,"process_fps":5.1,"skipped_fps":0.0},"cam-doorbell":{"camera_fps":5.0,"capture_pid":255,"detection_fps":0.0,"pid":238,"process_fps":5.0,"skipped_fps":0.0},"cam-driveway1":{"camera_fps":5.1,"capture_pid":242,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"cam-garage":{"camera_fps":5.0,"capture_pid":263,"detection_fps":0.0,"pid":241,"process_fps":5.0,"skipped_fps":0.0},"cam-porch1":{"camera_fps":5.1,"capture_pid":246,"detection_fps":0.0,"pid":235,"process_fps":5.1,"skipped_fps":0.0},"cam-sideyard":{"camera_fps":5.0,"capture_pid":249,"detection_fps":0.0,"pid":237,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.83,"pid":225}},"service":{"storage":{"/dev/shm":{"free":5361.1,"mount_type":"tmpfs","total":5368.7,"used":7.6},"/media/frigate/clips":{"free":5720627.2,"mount_type":"fuse.shfs","total":15995333.9,"used":10274706.7},"/media/frigate/recordings":{"free":5720627.2,"mount_type":"fuse.shfs","total":15995333.9,"used":10274706.7},"/tmp/cache":{"free":2947.4,"mount_type":"tmpfs","total":3000.0,"used":52.6}},"temperatures":{},"uptime":62506,"version":"0.10.1-83481af"}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

All my cameras are Amcrest of various models. All but the doorbell are ethernet. I've observed the gaps with all of them.

I've seen similar issues described multiple times in the issue queue. It's not perfectly clear it's all the same thing, but these things seem to rhyme:
* #2733 
* #3189

Things I've done so far:
* Disabled RTMP. Saw that suggested several times. While some recurring errors disappeared from logs (logs now show nothing after startup messages), the skips continue.
* Confirmed cache writing to tmpfs, with plenty of space.
* Confirmed I/O to disk well within hardware capability.
