### ISSUE TITLE
[Support]: ws4py Terminating Websocket

### ISSUE THREAD

**Issue by federicotravaini** [blakeblackshear/frigate#3357]
### Describe the problem you are having

Frigate runs fine, but in the logs I find these "Terminating Websocket" and "Managing Websocket" lines that I have no idea what they mean and how I should fix them

### Version

0.9.2-25BB515

### Frigate config file

```yaml
mqtt:
  host: 192.168.91.92
  user: !user
  password: !password

# detect:
#   stationary:
#     max_frames:
#       default: 300

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 0

cameras:
  giardino:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.91.100/bcs/channel0_ext.bcs?channel=0&stream=2&user=admin&password=password
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,512,387,512,385,464,0,464

  garage:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.91.100/bcs/channel3_ext.bcs?channel=3&stream=2&user=admin&password=password
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
        - car
    motion:
      mask:
        - 0,512,387,512,385,464,0,464

  retro:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.91.100/bcs/channel1_ext.bcs?channel=1&stream=2&user=admin&password=password
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,512,387,512,385,464,0,464

  balcone:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.91.100/bcs/channel2_ext.bcs?channel=2&stream=2&user=admin&password=password
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect: 
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,512,387,512,385,464,0,464

  ingresso:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.91.100/bcs/channel5_ext.bcs?channel=5&stream=2&user=admin&password=password
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      width: 896
      height: 512
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,512,387,512,385,464,0,464
        - 669,105,829,512,896,512,896,0,467,0,471,71
  
  sala:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.91.31:554//h264Preview_01_sub
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      width: 640
      height: 352
      fps: 5
    objects:
      track:
        - person

  letto:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.91.30:554//h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:password@192.168.91.30:554//h264Preview_01_main
          roles:
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - '1'
    detect:
      width: 640
      height: 352
      fps: 5
    objects:
      track:
        - person

detectors:
  coral:
    type: edgetpu
```

### Relevant log output

```shell
[2022-06-17 12:03:44] ws4py                          INFO    : Using epoll

[2022-06-17 12:03:47] frigate.edgetpu                INFO    : TPU found

[2022-06-17 12:03:54] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47846]

[2022-06-17 12:04:00] frigate.mqtt                   INFO    : Turning off detection for letto via mqtt

[2022-06-17 12:04:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:41058]

[2022-06-17 12:04:10] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:41058]

[2022-06-17 12:04:37] frigate.mqtt                   INFO    : Turning off detection for giardino via mqtt

[2022-06-17 12:04:40] frigate.mqtt                   INFO    : Turning off detection for balcone via mqtt

[2022-06-17 12:05:54] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47846]

[2022-06-17 12:07:22] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48026]

[2022-06-17 12:07:25] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48026]

[2022-06-17 12:10:51] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48186]

[2022-06-17 12:11:54] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48186]

[2022-06-17 12:38:07] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49194]

[2022-06-17 12:39:55] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49194]
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, flv, from 'rtmp://192.168.91.100/bcs/channel0_ext.bcs?channel=0&stream=2&user=admin&password=666666':
  Metadata:
    displayWidth    : 896
    displayHeight   : 512
  Duration: 00:00:00.00, start: 470664.587000, bitrate: N/A
    Stream #0:0: Data: none
    Stream #0:1: Video: h264, yuv420p(progressive), 896x512, 19 fps, 20 tbr, 1k tbn
    Stream #0:2: Audio: aac, 16000 Hz, mono, fltp
Unsupported codec with id 0 for input stream 0
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink 420 and reolink E1 Pro
