### ISSUE TITLE
[Support]: Alder lake vaapi hwaccell working on 0.11.0-beta2 but broken on 0.11.0-beta3 and beta4

### ISSUE THREAD

**Issue by charlesmunger** [blakeblackshear/frigate#3368]
### Describe the problem you are having

See this [comment](https://github.com/blakeblackshear/frigate/issues/3170#issuecomment-1160688643) on #3170, filing as its own bug because I think the use case is different (pure decode acceleration with vaapi rather than qsv transcoding hevc) and the original bug filer says their issue is fixed.

beta2 works with vaapi (working images, intel_gpu_top confirms hwaccel), the other betas (1, 3, 4) fail with a green screen and error logs.

Same config, everything else identical but running a different beta version. 

So something in beta2 made it work, that then regressed in beta 3. Specifying the qsv configuration also does not work; the stream works correctly, but `intel_gpu_top` confirms that ffmpeg is falling back to software decode. 

Running on ubuntu 22.04 with linux kernel 5.18 mainline.

### Version

0.11.0-1D45B0B

### Frigate config file

```yaml
ffmpeg:
      inputs:
        - path: rtmp://***/bcs/channel0_main.bcs?channel=0&stream=0&user=frigate&password=***
          roles:
            - record
        - path: rtmp://***/bcs/channel0_sub.bcs?channel=0&stream=0&user=frigate&password=***
          roles:
            - detect
      input_args:
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -rw_timeout
        - '5000000'
        - -f
        - live_flv
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -vaapi_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
```

### Relevant log output

```shell
[2022-06-20 17:09:00] watchdog.tree_driveway         ERROR   : Ffmpeg process crashed unexpectedly for tree_driveway.
[2022-06-20 17:09:00] watchdog.tree_driveway         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-06-20 17:09:00] ffmpeg.tree_driveway.detect    ERROR   : [h264 @ 0x5638405bea80] hardware accelerator failed to decode picture
[2022-06-20 17:09:00] ffmpeg.tree_driveway.detect    ERROR   : Error while decoding stream #0:1: Input/output error
[2022-06-20 17:09:00] ffmpeg.tree_driveway.detect    ERROR   : [h264 @ 0x5638405bea80] Failed to end picture decode issue: 23 (internal decoding error).
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, flv, from 'rtmp://***/bcs/channel0_sub.bcs?channel=0&stream=0&user=frigate&password=***':
  Metadata:
    |RtmpSampleAccess: true
    displayWidth    : 640
    displayHeight   : 480
  Duration: 00:00:00.00, start: 152681.670000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x480, 6 fps, 12 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-410
