### ISSUE TITLE
[Support]: Frigate Proxy Shows Blank Screen

### ISSUE THREAD

**Issue by hhinma** [blakeblackshear/frigate#3371]
### Describe the problem you are having

Installed Frigate server in docker running on Debian 11.  Server comes up quite happily with no obvious problems,  the GUI is accessible and displays camera feeds as expected, however, frigate proxy addon in HA shows a blank screen.

I simplified the configuration to a single camera.  I attempted to install the frigate proxy addin in multiple different HA instances on several different platforms, all resulting in the same blank screen from this server  I have to think this is a misconfiguration problem but so far nothing obvious has occurred to me.

Any thoughts on debugging?

Log file images etc attached.    The ffpmeg errors reported from the camera are an issue with this particular video feed and do not appear to adversely affect normal GUI operating when connecting directly to the GUI.

<img width="987" alt="frigate-gui" src="https://user-images.githubusercontent.com/8053813/174892535-b934b4c4-d1d5-44c7-b6c0-56d2decd0b52.png">
<img width="1035" alt="frigate-proxy-screen" src="https://user-images.githubusercontent.com/8053813/174892543-1ea36333-7cb9-4487-8e2c-470bc2b9e6ee.png">
<img width="727" alt="frigate-server-config" src="https://user-images.githubusercontent.com/8053813/174892544-4d835cd2-2956-4909-8adb-15fbae3bf481.png">
<img width="698" alt="homeassistant-version-info" src="https://user-images.githubusercontent.com/8053813/174892545-1d3e06d3-0cef-4696-8559-f82e39a4ddc4.png">
<img width="1280" alt="server-container-log" src="https://user-images.githubusercontent.com/8053813/174892546-fc1406d9-228c-4097-ae38-bc8a406e0bd3.png">
<img width="1326" alt="supervisor-log" src="https://user-images.githubusercontent.com/8053813/174892547-724a28fa-7d20-42aa-83c3-c89036fd03ac.png">
<img width="656" alt="supervisor-version-info" src="https://user-images.githubusercontent.com/8053813/174892549-9d53ec58-addf-4a15-a702-14ac7549d027.png">

### Version

0.11.0-D2C3CDC

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.250

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -an
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  rear:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.50.1:7441/Ra1lItAqeLRx70b1?enableSrtp
          roles:
            - detect
            - rtmp
    detect:
      width: 1024
      height: 576
      fps: 5

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 7

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3

logger:
  default: info

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
```

### Relevant log output

```shell
[services.d] starting services
[services.d] done.
[2022-06-21 16:34:27] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-21 16:34:27] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-06-21 16:34:27] peewee_migrate                 INFO    : There is nothing to migrate
[2022-06-21 16:34:27] detector.coral                 INFO    : Starting detection process: 224
[2022-06-21 16:34:27] frigate.app                    INFO    : Output process started: 226
[2022-06-21 16:34:27] ws4py                          INFO    : Using epoll
[2022-06-21 16:34:27] frigate.app                    INFO    : Camera processor started for rear: 231
[2022-06-21 16:34:27] frigate.app                    INFO    : Capture process started for rear: 235
[2022-06-21 16:34:27] ws4py                          INFO    : Using epoll
[2022-06-21 16:34:27] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-06-21 16:34:30] frigate.edgetpu                INFO    : TPU found
[2022-06-21 16:34:46] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:36722]
[2022-06-21 16:37:37] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:36722]
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsps://192.168.50.1:7441/Ra1lItAqeLRx70b1?enableSrtp':
  Metadata:
    title           : 74ACB99E26C7_1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 16000 Hz, mono, fltp
    Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
    Stream #0:2: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1024x576, 30 fps, 29.97 tbr, 90k tbn, 60 tbc
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":14.96,"pid":224}},"rear":{"camera_fps":5.0,"capture_pid":235,"detection_fps":0.0,"pid":231,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":65.6,"mount_type":"tmpfs","total":67.1,"used":1.5},"/media/frigate/clips":{"free":933299.7,"mount_type":"ext4","total":983358.5,"used":31.8},"/media/frigate/recordings":{"free":933299.7,"mount_type":"ext4","total":983358.5,"used":31.8},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":380,"version":"0.11.0-d2c3cdc"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Ubiquiti G3 Instant, via UDMP.   Multiple different cameras produce the same results. 

### Any other information that may be helpful

Proxy is configured with port 5010.
