### ISSUE TITLE
[Config Support]: Audio out of sync

### ISSUE THREAD

**Issue by eatoff8** [blakeblackshear/frigate#3373]
### Describe the problem you are having

I have added a new camera (Reolink E1 Outdoor). The issue I am seeing, is that the audio is out of sync when reviewing events. Live view its fine.

When viewing the clips, the clip sounds correct but its like the video is delayed. I have attached a couple examples, one with a car and one with a runner going past. The car is delayed and stuttering video, but the other clip is actually a runner that is missed completely by the video, but the audio is recorded fine.

https://nextcloud.eatoff.me/s/sMAHzPbSw457SLy

All my other cameras (a couple RTSP Eufy cams, and a couple Unifi indoor cams) work fine.

Any ideas of what to do? I've set the Reolink RTSP quality quite high, but nothing on the system is stressed (11th Gen i7, 8C16T)

### Version

0.11.0 Beta 4

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

birdseye:
  enabled: True
  mode: objects

database:
  path: /config/Database/frigate.db
  
snapshots:
  enabled: True
  retain:
    default: 0

rtmp:
  enabled: False

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.109:554//h264Preview_01_main
          roles:
            - record
        - path: rtsp://admin:password@192.168.1.109:554//h264Preview_01_sub
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        car:
          mask: 915,86,918,234,616,226,624,80
        person:
          mask: 962,0,942,207,518,187,0,200,0,0
    zones:
      driveway_close:
        coordinates: 1280,720,1076,408,98,407,0,526,0,720
    motion:
      mask:
        - 0,524,111,386,89,165,0,209
        - 1280,695,1280,234,1152,163,1077,429
        - 663,0,662,128,0,123,0,0
    record:
      enabled: True
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects
      expire_interval: 1440
```

### Relevant log output

```shell
Nothing relevant in the logs
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2
