### ISSUE TITLE
[Support]: max disapear in zones

### ISSUE THREAD

**Issue by sygys** [blakeblackshear/frigate#3375]
### Describe the problem you are having

When configuring zones the detection in these zones cant be set to have a ' max_disappeared:' frames. This means the person motion sensor of a specific zone goes on of several times a second when someone isnt moving much. I would like to be able to set a 'max_disappeared:'  per zone.

### Version

3.1

### Frigate config file

```yaml
not relavent
```

### Relevant log output

```shell
not relavent
```

### FFprobe output from your camera

```shell
not relavent
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relavent

**Comment by NickM-27** [comment]
Are you seeing this happen when someone is at the edge of a zone or it's a small zone, and the zone is continually activated then not activated?

**Comment by sygys** [comment]
I have been looking for this. but it seems to also happen when an orange bounding box becomes blue and then back orange. (orange means a person is moving and detected and blue that the person isnt moving.) when trouble shooting i see that bounding boxes switch between orange and blue allot. the main camera zone (the whole picture) seems to maintain the 'max_disappeared:' and will keep the motion on until 400 frames of no motion are detected but the manual setup zones keep going on off triggering automations in home assistant 5 times a second

**Comment by NickM-27** [comment]
> (orange means a person is moving and detected and blue that the person isnt moving.)

That's not true, blue means the object is not detected in that current frame. max_dissappeared is the number of frames from when the object is not seen (blue bounding box) until it is considered gone and the event is finalized

**Comment by sygys** [comment]
Still as soon as it becomes blue the motion of a specific manual zone is set to off

**Comment by NickM-27** [comment]
> Still as soon as it becomes blue the motion of a specific manual zone is set to off

Right, I just wanted to clear that part up so it's clear how this is working.

Another thing to clear up is that while in the current version of the integration they're called "motion sensors" they are actually occupancy sensors and have nothing to do with motion (this is addressed in an upcoming integration update).

I think in general the idea that as soon as an object is not detected the zone shows that it is not there any more makes sense, but I do see how that can be difficult for automations. 

Is there any reason you can't adjust your automations to filter for this by setting the `for:` variable in HA so it only triggers when the object is missing for 5 seconds (as an example)?

**Comment by sygys** [comment]
I read something in the changelog indeed. Haven't updated to the latest version because I have to change all my automation too when I do this. The problem is that a system like mine that has around 3500 entities with almost 500 automations and 7 camera's running object detection you want to save as many resources as possible. As soon as the accupancy is on and off an automation will trigger. When this happens a few times a second with multiple automations then you shouldn't want this to happen. It's not a big impact on the machine but its not necessary. When I set a camera detection max disappear to 400 frames then this should also mean all zones get the same settings. It's kinda strange that this setting isn't used for the zones and you can't set them differently.

For your info. A for is like a delay in home assistant. So the automation will trigger and then waits for a state to be a specific value for the time specified. So it's not like the automation won't trigger when a for 10 seconds is set. It will trigger everytime the state changes but only executes the actions when the for timer is on zero. So all your automations with a for are still triggered.

**Comment by sygys** [comment]
But it's not only the automations also every state change is saved to the database. This means when you have 7 camera's with an average of 3 zones per camera doing random on offs several times a second this could go to 100000s of database entries for nothing

**Comment by NickM-27** [comment]
That's seems like a matter of semantics on "trigger", but I see what you're saying and the way you describe it does line up with what I've seen as well.

> But nevermind. If you thinks it's ok as is then I need to accept it I guess

To be clear, I'm not saying nothing should change, I'm just trying to establish alternatives and better understand the problem to see what viable solutions are.

**Comment by NickM-27** [comment]
There's another aspect of this behavior which also needs to be addressed and that is the amount of on/off you're getting. 

Can you please add your config to the top file, show a screenshot of the sensor history in HA, and a screenshot of how your zone is setup in frigate? I'm looking back at my HA detections and don't see this rapid on/off behavior, so wondering if there's other things that could be optimized to alleviate this.

**Comment by dermotduffy** [comment]
> The problem is that a system like mine that has around 3500 entities with almost 500 automations and 7 camera's running object detection you want to save as many resources as possible. 

With 500 automations, if we imagine _all_ of them are triggered and give a generous 20 bytes per date object to hold the delay time, that's 10KB. The compute time required to respond to these 500 timers is likely not worth considering. In short:  Is there an observed performance issue that is causing a problem, or only a theoretical one?

As for database entries, do you need to store these at all? I [exclude](https://www.home-assistant.io/integrations/recorder/#exclude) high-change-rate variables for this very reason (e.g. no point in storing `sensor.uptime` in a database!). And for users with a smaller footprint, this presumably isn't a worry either.

> There's another aspect of this behavior which also needs to be addressed and that is the amount of on/off you're getting.

+1. I also don't see this behavior and wonder if there's something that could be masked or otherwise reduce this trigger rate. Also is it the `occupancy` or `motion` entity you are seeing this with?

**Comment by sygys** [comment]
I guess you are right. its not a big impact. my HA is running on a 10th gen nuc i7. without frigate on it runs around 1% cpu load. and with frigate active and detection on 7 cameras the CPU is around 25 / 40% depending on how many motion is detected.

So all this is done without a sweat. 

I looked at the history and do think its not a problem the few times it happens. that a person is in that zone.

But i still would like to have something cleared. I dont understand when a camera is set to max_disappeared: 400 the zones for that camera keep flicking on and off on their occupancy sensor. shouldnt they just stay on when the "blue box" is still in that zone. The way it works now is that when the box becomes orange the occupancy sensor will turn on and when it becomes blue it goes to off. But turning blue doesnt mean the person is out of the zone right? The thing is when i look at the occupancy sensor of the whole camerafeed so not a zone but the total picture, the occupancy sensor stays on until the blue box disappears. So maybe im doing it wrong.

Here is the config for the camera:

```
##### KEUKEN #####
  camera_keuken:
    ffmpeg:
      inputs:
        - path: rtsp://login+pass@192.168.178.93/cam/realmonitor?channel=1&subtype=00&authbasic=auth=
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.80
          threshold: 0.80
          min_area: 50000
        dog:
          min_score: 0.75
          threshold: 0.75
          max_area: 40000
    motion:
      mask:
        - 1531,83,1852,74,1850,35,1535,37
    detect:
      max_disappeared: 400
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 50
        max_frames:
          objects:
            person: 1000
            dog: 1000
    zones:
      tablet_zone:
        coordinates: 1170,0,1178,470,857,638,777,572,767,0
        objects:
          - person
      eettafel:
        coordinates: 1920,1080,1920,698,1632,559,1295,547,1037,673,867,859,889,1080
        objects:
          - person
      keuken:
        coordinates: 378,774,271,662,98,730,0,440,0,0,756,0,781,576
        objects:
          - person
      achterdeur:
        coordinates: 0,1080,277,1080,250,1032,0,1001
        objects:
          - person
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: active_objects
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: []
        retain:
          default: 4
          mode: active_objects
          objects:
            person: 4
```

**Comment by blakeblackshear** [comment]
Blue does not mean the object has left the zone. It just shows the last location an object was, but indicates that it was not found in the current frame. Do you have object masks or other filters that would cause frigate to assume the object was a false positive? It seems odd that you would have so many frames where the object wasn't detected.

**Comment by sygys** [comment]
It's pretty common that it keeps flicking between colors https://youtu.be/rOqdQAZCI6Y

**Comment by NickM-27** [comment]
Looks like it's doing this due to the high scores you're requiring for `dog`

```yaml

        dog:
          min_score: 0.75
          threshold: 0.75

```

I'd recommend lowering them and trying again, should work a lot better
