### ISSUE TITLE
[Camera Support]: What should I set the detect width & height to?

### ISSUE THREAD

**Issue by WizBangCrash** [blakeblackshear/frigate#3376]
### Describe the problem you are having

Firstly, thanks for such a great application. After spending two weeks evaluating both Shinobi and ZoneMinder and getting more and more frustrated with them. I came across frigate and haven't looked back :-)

I've a question about the values to use the in the `detect` element of the camera configuration. Should these be set to the actual values of the camera video feed i.e. 3840x2160 in my case? Or should they be set to the width and height that you want the detect engine to use e.g. 1280x720

It's not clear in the documentation and I may be overthinking it, but when I read the page on [detect resolution](https://docs.frigate.video/guides/camera_setup#choosing-a-detect-resolution) I wondered if I am supposed to set lower numbers here to help fit the 320x320 model.

Any light someone can shed here would be really useful.

### Version

0.11.0 Beta 4

### Frigate config file

```yaml
cameras:
  street:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@reolink-front.lan:554/h265Preview_01_main
          roles:
            - record
            - detect
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@reolink-front.lan:554/h264Preview_01_sub
          roles:
            - rtmp
    detect:
      enabled: true
      width: 3840
      height: 2160
      fps: 5
    record:
      enabled: true
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.2-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://<user>:<password>@reolink-front.lan:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000188, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 24.92 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-810A and RLC-811A

### Any other information that may be helpful

Also, for reference to anyone else out there, I have three Reolink cameras (2 x RLC-810A + RLC-811A) and I have had no issues using the default settings for ffmpeg input_args. I have the latest firmware on all of them (v3.1.0), I think [this](https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others) section does not apply to the newer models.
