### ISSUE TITLE
Which hardware acceleration config?[Config Support]: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3385]
### Describe the problem you are having

Now that I have my 10 cameras set up and working, I'm down to the fine performance tuning.

I'm confused as to which hardware acceleration setting to use

I am running Frigate as an HA add-on on a Dell Optiplex 3040, and HA reports it as a X86-64.

Which hwaccel settings should I be using?

BTW, this is such an awesome asset!

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.105
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ashscott
  password: brillig269
  stats_interval: 60

database:
  path: /media/frigate/clips/frigate.db

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

detectors:
  # cpu1:
  #   type: cpu
  coral:
    type: edgetpu
    device: usb
# resolution was 640x352 changed to 1920x1080
cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.109:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.109:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - horse
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        car:
          threshold: 0.5
          min_score: 0.85
    motion:
      mask:
        - 0,332,1920,453,1920,0,0,0
      threshold: 15
    zones:
      driving:
        coordinates: 0,488,0,382,650,435,1782,525,1783,568
        objects:
          - person
          - car
      horses:
        coordinates: 0,1075,1915,1080,1920,685,1220,738,372,695,2,680
        objects:
          - horse
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  turning_circle: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.119:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.119:554/11 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        car:
          threshold: 0.5
          min_score: 0.85
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 10,0,1920,0,1908,37,988,33,995,92,935,97,860,90,868,40,655,13
    # zones:
      # circle:
      #   coordinates: 0,23,0,137,0,352,640,352,640,107,640,24,470,17,336,3,332,33,288,28,290,4
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  car_park: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.0.1.118:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://10.0.1.118:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
        car:
          threshold: 0.5
          min_score: 0.85
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 0,110,147,98,312,73,723,92,1080,93,1918,45,1913,3,358,0,0,0
    zones:
      carpark:
        coordinates: 1025,367,1070,267,1510,228,1612,277,1838,427,1377,745,1212,657,1105,592,1068,528,1068,472
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        # required_zones:
        #   - arriving
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  south_terrace: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.125:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.125:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,0,1920,488,1018,378,0,365,0,0
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south_east: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.42:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.42:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,0,1920,275,0,518,0,0
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south_west: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.22:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.22:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.6
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 430,498,592,475,542,317,470,295
        - 952,478,832,467,845,317,907,340
        - 0,233,593,157,1440,220,1760,385,1543,1080,1920,1080,1920,0,0,0
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.54:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.54:554/11 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,210,1920,0,833,0,833,35
      # threshold: 15
    # zones:
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east_terrace: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.108:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.108:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 0,478,0,0,441,0,1920,0,1920,387,793,472
      # threshold: 15
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  # courtyard: # <------ Name the camera
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://admin:******@10.0.1.51:554/12 # <----- Update for your camera
  #         roles:
  #           - detect
  #       - path: rtsp://admin:******@10.0.1.51:554/11 # <----- Update for your camera
  #         roles:
  #           - record
  #   rtmp:
  #     enabled: False # <-- RTMP should be disabled if your stream is not H264
  #   detect:
  #     width: 1920 # <---- update for your camera's resolution
  #     height: 1080 # <---- update for your camera's resolution
  #     fps: 5
  #   # objects:
  #   #   track:
  #   #     - person
  #   #     - car
  #   #   filters:
  #   #     person:
  #   #       threshold: 0.8
  #   #       min_score: 0.75
  #   #     car:
  #   #       # threshold: 0.5
  #   #       min_score: 0.3
  #   # motion:
  #   #   mask:
  #   #     - 0,129,640,141,640,0,0,0
  #   #     - 0,352,562,352,640,350,640,200,319,205,0,205
  #   #   threshold: 15
  #   # zones:
  #   #   # approaching:
  #   #   #   coordinates: 0,170,237,165,239,143,0,136
  #   #   driving:
  #   #     coordinates: 0,184,0,136,623,141,638,144,637,186
  #   #   # leaving:
  #   #   #   coordinates: 432,166,576,170,575,148,435,141
  #   record:
  #     enabled: True
  #     retain:
  #       days: 2
  #       mode: all
  #     events:
  #       retain:
  #         default: 5
  #         mode: motion
  #       pre_capture: 3
  #       post_capture: 15
  #   snapshots:
  #     enabled: true
  #     timestamp: false
  #     bounding_box: false
  #     crop: true
  #     height: 500
  #     retain:
  #       default: 5
  #   mqtt:
  #     timestamp: False
  #     bounding_box: False
  #     crop: True
  #     height: 500
  #     quality: 100

  greenhouse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@10.0.1.140:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:******@10.0.1.140:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    # objects:
    #   track:
    #     - person
    #     - car
    #   filters:
    #     person:
    #       threshold: 0.8
    #       min_score: 0.75
    #     car:
    #       # threshold: 0.5
    #       min_score: 0.3
    # motion:
    #   mask:
    #     - 0,129,640,141,640,0,0,0
    #     - 0,352,562,352,640,350,640,200,319,205,0,205
    #   threshold: 15
    # zones:
    #   # approaching:
    #   #   coordinates: 0,170,237,165,239,143,0,136
    #   driving:
    #     coordinates: 0,184,0,136,623,141,638,144,637,186
    #   # leaving:
    #   #   coordinates: 432,166,576,170,575,148,435,141
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by blakeblackshear** [comment]
I would start by trying the QuickSync configuration. Ffprobe output or some info on your camera streams would be helpful to know.

**Comment by ripvega** [comment]
Thanks for the reply.

There are two Quicksync options:

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

Which do you suggest?
How will I know if I have the correct one?

I'll need some help with Ffprobe output. What is that?
What camera streams info do you need?

**Comment by NickM-27** [comment]
> Which do you suggest?

Per [the docs](https://docs.frigate.video/configuration/hardware_acceleration) I believe your CPU is older than 10th gen so this should be preferred 

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

> How will I know if I have the correct one?

You should be able to use `intel_gpu_top` to see if it's being utilized

> I'll need some help with Ffprobe output. What is that?
> What camera streams info do you need?

Ffprobe is a tool built into ffmpeg to get information about a media source and will print a big summary. You should be able to run it like `ffprobe rtsp://admin:******@10.0.1.42:554/12`
