### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by MickPBduece** [blakeblackshear/frigate#3387]
### Describe the problem you are having

When an object is detected Frigate throws Exception in thread event_processor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely

### Version

3.1 Full Access installed as Add on to HA  

### Frigate config file

```yaml
#   Config notes - The Addon ethernet card is plugged into a blue usb on the PI.  Not sure if it needs to be but after this last reload... Just do it
#   The Coral and the SSD are plugged into the powered usb hub
#   The network is consigured eth0 - 192.168.1.9/24 and 192.168.1.1 (Gateway) and 192.168.1.1 for DNS  IPV6 is disabled
#                         enp1sou1 - 192.168.10.9/24 and 192.168.10.9 (Gateway) and no DNS IPV6 is disabled
#   Frigate add on is the version that allows me to turn off protection mode (Spefically 3.1 as o 6/4/2022)
#   HArdware accel is the PI3/4 settings for 64 bit
#
#   Changing the ffmpeg setting seems to reqiure a hardware restart?? !! // 
#   shm-size (width * height * 1.5 * 9 + 270480)/1048576 = <shm size in mb>
detectors:
  # Required: name of the detector
  coral:
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3

mqtt:
    host: 192.168.1.9
    user: Jeff
    password: HunkyHusband

#global_args: -hide_banner -loglevel error
#--- Commented out after restored HA subsequent to power failure.  This restore is thougth to have not been needed and the actual issue
# was that after many many on/off power cycles in a short period of time the network setting in HA were corrupted and the camera netword
# replaced the home network as the primary network for HA and Unifi controller
#
#

#Front door camera will WILL WILL work with audio enabled (AAC) and HWaccel for RPI4. 
#Adding HWaccel for all cameras except front door keep the second and all subsequent cameras with hwaccel config from running
#I had opened an issue for this in the past - it is now closed
#
# ffmpeg:
#   hwaccel_args:
#     - -c:v
#     - h264_v4l2m2m
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 704
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 480
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - car
    - motorcycle

# Video stream storage settings
record:
  enabled: True
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 6   

cameras:
  frontdoor:
    ffmpeg:
      inputs:
#  Substream path          
        - path: rtsp://HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=1 #&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
# #  Substream2 path          
        #  - path: rtsp://HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=2
        #      - clips
# Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.121:554/cam/realmonitor?channel=1&subtype=0 #&unicast=true&proto=Onvif
          roles:
            - record
    motion:
      mask:
      - 704,480,704,362,654,337,538,480
      - 0,0,285,0,109,22,0,387
    # snapshots:
    #   enabled: true
    #   timestamp: false
    #   bounding_box: true
    #   retain:
    #     default: 5 
        
  frontmiddle:
    ffmpeg:  
      # hwaccel_args:
      #   - -c:v
      #   - h264_v4l2m2m
      inputs:
#  Substream path          
        - path: rtsp://HA:HA123456@192.168.10.118:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
#  Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.118:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
 
    motion:
      mask:
        - 85,424,170,458,171,480,0,480,0,162,73,287,72,380
        - 354,25,704,148,704,0,0,0,0,60,0,136
        - 704,284,608,190,552,0,704,0
    # snapshots:
    #   enabled: true
    #   timestamp: false
    #   bounding_box: true
    #   retain:
    #     default: 5
        
  fronteast:
    ffmpeg:
      # hwaccel_args:
      #   - -c:v
      #   - h264_v4l2m2
      inputs:
#  Substream path          
        - path: rtsp://HA:HA123456@192.168.10.116:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
#  Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.116:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    
    motion:
      mask:
        - 85,424,170,458,171,480,0,480,0,162,73,287,72,380
        - 354,25,704,148,704,0,0,0,0,60,0,136
        - 704,284,608,190,552,0,704,0
    # snapshots:
    #   enabled: true
    #   timestamp: false
    #   bounding_box: true
    #   retain:
    #     default: 5

  patiodoor:
    ffmpeg:
      # hwaccel_args:
      #   - -c:v
      #   - h264_v4l2m2
      inputs:
#  Substream path          
        - path: rtsp://HA:HA123456@192.168.10.117:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
           - detect
           - rtmp
#  Mainstream path          
        - path: rtsp://HA:HA123456@192.168.10.117:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    
    motion:
      mask: 0,423,0,480,227,480,221,426
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5

  garage:
    ffmpeg:
      # hwaccel_args:
      #   - -c:v
      #   - h264_v4l2m2
      inputs:
#  Substream path          
         - path: rtsp://HA:HA123456@192.168.10.122:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
           roles:
            - detect
            - rtmp
#  Mainstream path          
         - path: rtsp://HA:HA123456@192.168.10.122:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
           roles:
            - record
    
    motion:
      mask: 0,423,0,480,227,480,221,426
    # snapshots:
    #   enabled: true
    #   timestamp: false
    #   bounding_box: true
    #   retain:
    #     default: 5

  patiowest:
    ffmpeg:
      # hwaccel_args:
      #   - -c:v
      #   - h264_v4l2m2
      inputs:
#  Substream path          
         - path: rtsp://HA:HA123456@192.168.10.123:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
           roles:
            - detect
            - record
#  Mainstream path          
#         - path: rtsp://HA:HA123456@192.168.10.123:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    
    motion:
      mask: 0,423,0,480,227,480,221,426
    # snapshots:
    #   enabled: true
    #   timestamp: false
    #   bounding_box: true
    #   retain:
    #     default: 5

  basement:
    ffmpeg:
      # hwaccel_args:
      #   - -c:v
      #   - h264_v4l2m2
      inputs:
#  Substream path          
         - path: rtsp://HA:HA123456@192.168.10.124:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
           roles:
            - detect
            - record
#  Mainstream path          
#         - path: rtsp://HA:HA123456@192.168.10.124:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    
    motion:
      mask: 0,423,0,480,227,480,221,426
    # snapshots:
    #   enabled: true
    #   timestamp: false
    #   bounding_box: true
    #   retain:
    #     default: 5
```

### Relevant log output

```shell
[2022-06-26 12:16:55] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:59304]
Exception in thread event_processor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/events.py", line 67, in run
    Event.replace(
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1969, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2730, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2466, in _execute
    return self.handle_result(database, cursor)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2739, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3218, in last_insert_id
    return cursor.lastrowid
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 88, in lastrowid
    self._wait()
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3136, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely
```

### FFprobe output from your camera

```shell
H264 
704x480
5 FPS

MPEG Audio
```

### Frigate stats

```json
{"basement":{"camera_fps":5.0,"capture_pid":268,"detection_fps":3.8,"pid":234,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":15.7,"detectors":{"coral":{"detection_start":1656264490.792331,"inference_speed":25.55,"pid":217}},"frontdoor":{"camera_fps":5.0,"capture_pid":237,"detection_fps":0.0,"pid":221,"process_fps":5.0,"skipped_fps":0.0},"fronteast":{"camera_fps":5.1,"capture_pid":241,"detection_fps":0.0,"pid":227,"process_fps":5.1,"skipped_fps":0.0},"frontmiddle":{"camera_fps":5.1,"capture_pid":238,"detection_fps":5.8,"pid":225,"process_fps":5.0,"skipped_fps":0.0},"garage":{"camera_fps":5.0,"capture_pid":250,"detection_fps":0.0,"pid":229,"process_fps":5.0,"skipped_fps":0.0},"patiodoor":{"camera_fps":5.1,"capture_pid":247,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"patiowest":{"camera_fps":5.1,"capture_pid":262,"detection_fps":6.1,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":1559.2,"mount_type":"tmpfs","total":1566.9,"used":7.7},"/media/frigate/clips":{"free":84395.8,"mount_type":"ext4","total":119244.7,"used":30038.6},"/media/frigate/recordings":{"free":84395.8,"mount_type":"ext4","total":119244.7,"used":30038.6},"/tmp/cache":{"free":1532.9,"mount_type":"tmpfs","total":1566.9,"used":34.0}},"temperatures":{},"uptime":976,"version":"0.10.1-83481af"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Front Door Dahua IPC-HDW5231R-ZE
