### ISSUE TITLE
[Support/Bug]: Zones and Masks being ignored

### ISSUE THREAD

**Issue by droans** [blakeblackshear/frigate#3392]
### Describe the problem you are having

I created some zones and masks for my cameras so Frigate will ignore them. While they appear to be working on the front end (no events are created), they don't actually seem to be doing anything. The "Events" option for each event type still shows events from discarded areas even though they do not appear in the event log. The Home Assistant integration still captures these events and records them as motion. 

Some examples:

Camera:

![image](https://user-images.githubusercontent.com/49721649/176183091-83db144e-f58a-4246-8257-9f2c6ffc86bf.png)

With zones and object masks:

![image](https://user-images.githubusercontent.com/49721649/176183189-a2680942-e335-4ea2-a8cc-e7ff0987ed99.png)

Person events:

![image](https://user-images.githubusercontent.com/49721649/176183268-75121192-bb9c-45c3-b9d1-63781610d0f8.png)

Person Motion Camera from Home Assistant:

![camera](https://user-images.githubusercontent.com/49721649/176182732-c41a1f29-cc58-4c0b-b5c2-6cfb35f5bb9a.jpg)
 

### Version

0.10.1-83481AF

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "front_yard": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 480,
        "max_disappeared": 25,
        "stationary": {
          "interval": 30,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 10
        },
        "width": 704
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": "-c:v h264_cuvid -fflags +genpts+discardcorrupt",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://XXXX:XXXX@10.10.20.51:554/cam/realmonitor?channel=1&subtype=0&authbasic=64",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://XXXX:XXXX@10.10.20.51:554/cam/realmonitor?channel=1&subtype=0&authbasic=64",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -c:v h264_cuvid -fflags +genpts+discardcorrupt -i rtsp://XXXX:XXXX@10.10.20.51:554/cam/realmonitor?channel=1&subtype=0&authbasic=64 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_yard-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -c:v h264_cuvid -fflags +genpts+discardcorrupt -i rtsp://XXXXXX:XXXXXX@10.10.20.51:554/cam/realmonitor?channel=1&subtype=0&authbasic=64 -c copy -f flv rtmp://127.0.0.1/live/front_yard -r 5 -s 704x480 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "362,478,408,443,468,472,517,442,537,419,576,386,600,341,665,218,691,113,687,22,583,18,465,31,381,49,268,85,0,193,1,0,704,0,704,58,704,480"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_yard",
      "objects": {
        "filters": {
          "bicycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "bus": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "motorcycle": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "bicycle",
          "car",
          "motorcycle",
          "bus",
          "dog"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "driveway",
            "sidewalk_to_door",
            "frontyard",
            "sideyard"
          ],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 10,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "driveway",
          "sidewalk_to_door",
          "frontyard",
          "sideyard"
        ],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {
            "car": 15,
            "dog": 15,
            "person": 15
          }
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "driveway": {
          "coordinates": "74,163,111,203,134,232,220,331,301,395,387,457,416,437,471,480,566,398,602,344,642,263,670,197,524,140,408,106,283,82",
          "filters": {},
          "objects": []
        },
        "frontyard": {
          "coordinates": "288,81,454,44,551,31,636,48,704,69,677,141,602,112,555,149",
          "filters": {},
          "objects": []
        },
        "sidewalk_to_door": {
          "coordinates": "555,151,616,107,673,126,618,176",
          "filters": {},
          "objects": []
        },
        "sideyard": {
          "coordinates": "0,480,362,480,400,449,342,430,247,360,147,253,89,176,0,218",
          "filters": {},
          "objects": []
        }
      }
    },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 30,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": 10
    },
    "width": 1280
  },
  "detectors": {
    "cpu": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.86.36",
    "password": null,
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": null
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": true,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 10,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": true,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {
        "car": 15,
        "dog": 15,
        "person": 15
      }
    },
    "timestamp": true
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"back_yard":{"camera_fps":5.1,"capture_pid":262,"detection_fps":0.0,"pid":254,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_s
peed":28.26,"pid":233}},"east_side_yard":{"camera_fps":5.0,"capture_pid":275,"detection_fps":0.0,"pid":256,"process_fps":5.0,"skipped_fps":0.0},"front_yard":{"camera_fps":5.1,"capture_pid":2
59,"detection_fps":0.0,"pid":253,"process_fps":5.1,"skipped_fps":0.0},"living_room":{"camera_fps":5.1,"capture_pid":257,"detection_fps":0.0,"pid":252,"process_fps":5.1,"skipped_fps":0.0},"se
rvice":{"storage":{"/dev/shm":{"free":532.1,"mount_type":"tmpfs","total":536.9,"used":4.8},"/media/frigate/clips":{"free":8364700.3,"mount_type":"xfs","total":13998380.5,"used":5633680.2},"/
media/frigate/recordings":{"free":8364700.3,"mount_type":"xfs","total":13998380.5,"used":5633680.2},"/tmp/cache":{"free":5977.3,"mount_type":"tmpfs","total":6000.0,"used":22.7}},"temperature
s":{},"uptime":311036,"version":"0.10.1-83481af"},"west_side_yard":{"camera_fps":5.1,"capture_pid":267,"detection_fps":0.0,"pid":255,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest
