### ISSUE TITLE
[Config Support]:   retain_days: 7 - but keeps "all" (I believe)

### ISSUE THREAD

**Issue by sanderlv** [blakeblackshear/frigate#3405]
### Describe the problem you are having

I have configured:
```
record:
  enabled: true
  retain_days: 7
  events:
    retain:
      default: 14
```

But despite this my NAS is over 20TB in 40 days... I believe all is kept...

### Version

Before 10.1 now 0.11.0-1d45b0b

### Frigate config file

```yaml
record:
  enabled: true
  retain_days: 7
  events:
    retain:
      default: 14
```
```


### Relevant log output

```shell
none
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --privileged \
  --shm-size=1g \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=2000000000 \
  -v /shared/frigate/config:/config:ro \
  -v /dev/bus/usb:/dev/bus/usb \
  -v /etc/localtime:/etc/localtime:ro \
  -v /shared/frigate/clips:/media/frigate/clips:rw \
  -v /shared/frigate/recordings:/media/frigate/recordings:rw \
  -v /shared/frigate/db:/media/frigate/db:rw \
  --device-cgroup-rule="c 189:* rmw" \
  --device=/dev/dri/renderD128 \
  -d \
  -p 5000:5000 \
  -e FRIGATE_RTSP_PASSWORD='password' \
  blakeblackshear/frigate:0.11.0-1d45b0b

**Comment by NickM-27** [comment]
For one, `retain_days` is the old format and I would recommend moving over to the new `retain -> days` format. Also please include all the logs currently seen from frigate as there could be helpful information.

Can you check the `/media/recordings` folder and see what is in there?

**Comment by NickM-27** [comment]
Example of new format:

```yaml
record:
  enabled: true
  retain:
    days: 7
  events:
    retain:
      default: 14
```
