### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by jacktux** [blakeblackshear/frigate#3411]
### Describe the problem you are having

All worked ok before upgrade to 0.11 (beta). I can see Live view and it's recording OK. But getting errors in log and cant see anything in FrigateCard

---Frigate Card---
The configured camera_entity is unavailable. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "camera_entity": "camera.workshop_inside_frigate",
  "live_provider": "auto",
  "frigate": {
    "client_id": "frigate",
    "camera_name": "workshop_inside_frigate"
  },
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  }
}

### Version

0.11.0-1D45B0B

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "workshop_outside_frigate": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 7,
        "height": 360,
        "max_disappeared": 35,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 70
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "nobuffer+genpts+discardcorrupt",
          "-flags",
          "low_delay",
          "-strict",
          "experimental",
          "-analyzeduration",
          "1000M",
          "-probesize",
          "1000M",
          "-rw_timeout",
          "5000000"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "http://192.168.2.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx",
            "roles": [
              "record",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "http://192.168.2.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.2.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxx&password=xxx -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/workshop_outside_frigate-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/workshop_outside_frigate",
          "roles": [
            "record",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer+genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://192.168.2.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxx&password=xxx -r 7 -s 640x360 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "0,360,136,360,140,251,0,243",
          "640,360,640,0,475,0,555,74,577,130,467,133,457,168,389,164,402,360"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "workshop_outside_frigate",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.73,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 28,
            "mode": "active_objects",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 14,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 90,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 7,
    "height": 360,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 640
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {
    "PLUS_API_KEY": "xxx"
  },
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "nobuffer+genpts+discardcorrupt",
      "-flags",
      "low_delay",
      "-strict",
      "experimental",
      "-analyzeduration",
      "1000M",
      "-probesize",
      "1000M",
      "-rw_timeout",
      "5000000"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": "-f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy",
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.xx.xx",
    "password": "xxx",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "frigate"
  },
  "objects": {
    "filters": {
      "person": {
        "mask": null,
        "max_area": 24000000,
        "max_ratio": 24000000,
        "min_area": 0,
        "min_ratio": 0,
        "min_score": 0.73,
        "threshold": 0.7
      }
    },
    "mask": "",
    "track": [
      "person"
    ]
  },
  "plus": {
    "enabled": true
  },
  "record": {
    "enabled": true,
    "events": {
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 28,
        "mode": "active_objects",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 14,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": true,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 90,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": true
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  },
  "ui": {
    "use_experimental": false
  }
}
```

### Relevant log output

```shell
[2022-07-02 16:06:11] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [mp4 @ 0x55b4a326b700] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 64112 >= 1008
[2022-07-02 16:06:11] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : av_interleaved_write_frame(): Invalid argument
[2022-07-02 16:06:11] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [mp4 @ 0x55b4a326b700] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 64112 >= 2032
[2022-07-02 16:06:11] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : Error writing trailer of /tmp/cache/workshop_outside_frigate-%Y%m%d%H%M%S.mp4: Invalid argument
[2022-07-02 16:06:11] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [flv @ 0x55b4a34cde80] Failed to update header with correct duration.
[2022-07-02 16:06:11] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [flv @ 0x55b4a34cde80] Failed to update header with correct filesize.
[2022-07-02 16:06:11] watchdog.workshop_outside_frigate INFO    : Terminating the existing ffmpeg process...
[2022-07-02 16:06:11] watchdog.workshop_outside_frigate INFO    : Waiting for ffmpeg to exit gracefully...
[2022-07-02 16:06:21] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [mp4 @ 0x5591cac52a00] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 64112 >= 1008
[2022-07-02 16:06:21] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : av_interleaved_write_frame(): Invalid argument
[2022-07-02 16:06:21] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [flv @ 0x5591cada4340] Failed to update header with correct duration.
[2022-07-02 16:06:21] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [flv @ 0x5591cada4340] Failed to update header with correct filesize.
[2022-07-02 16:06:21] watchdog.workshop_outside_frigate INFO    : Terminating the existing ffmpeg process...
[2022-07-02 16:06:21] watchdog.workshop_outside_frigate INFO    : Waiting for ffmpeg to exit gracefully...
[2022-07-02 16:06:31] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [mp4 @ 0x55da89b84c80] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 63344 >= 240
[2022-07-02 16:06:31] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : av_interleaved_write_frame(): Invalid argument
[2022-07-02 16:06:31] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [mp4 @ 0x55da89b84c80] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 63344 >= 1264
[2022-07-02 16:06:31] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : Error writing trailer of /tmp/cache/workshop_outside_frigate-%Y%m%d%H%M%S.mp4: Invalid argument
[2022-07-02 16:06:31] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [flv @ 0x55da89de8580] Failed to update header with correct duration.
[2022-07-02 16:06:31] ffmpeg.workshop_outside_frigate.record_rtmp ERROR   : [flv @ 0x55da89de8580] Failed to update header with correct filesize.
[2022-07-02 16:06:31] watchdog.workshop_outside_frigate INFO    : Terminating the existing ffmpeg process...
[2022-07-02 16:06:31] watchdog.workshop_outside_frigate INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
[1] 412
[2] 413
[3] 414
[4] 415
root@ccab4aaf-frigate-beta:/opt/frigate# ffprobe version 4.3.2-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[http @ 0x55ca72c4bc80] HTTP error 500 Internal Server Error
http://192.168.2.11/flv?port=1935: Server returned 5XX Server Error reply
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-820A
