### ISSUE TITLE
[Camera Support]: Asecam LAN camera with 4k resolution 

### ISSUE THREAD

**Issue by zuzuman** [blakeblackshear/frigate#3414]
### Describe the problem you are having

Clips/records are laggy. 
Previews are half-green

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
mqtt:
  host: x.x.x.x
  client_id: xxx
  user: xxx
  password: xxx
  topic_prefix: frigate
cameras:
  Doorbell:
    ffmpeg:
      inputs:
        - path: 'rtsp://xxx:xxx@x.x.x.x:xxxx/Streaming/Channels/101'
          roles: 
            - rtmp
            - detect
            - record     
          hwaccel_args: 
             - '-hwaccel'
             - 'vaapi'
             - '-hwaccel_device'
             - '/dev/dri/renderD128'
             - '-hwaccel_output_format'
             - 'yuv420p'    
    detect:
      width: 1920
      height: 1080
      fps: 5 
  Backyard:
    ffmpeg:
      inputs:
        - path: 'rtsp://xxx:xxx@x.x.x.x/x:xxxx'
          roles: 
            - rtmp
            - detect
            - record     
          hwaccel_args: 
             - '-hwaccel'
             - 'vaapi'
             - '-hwaccel_device'
             - '/dev/dri/renderD128'
             - '-hwaccel_output_format'
             - 'yuv420p'    
    detect:
      width: 3840
      height: 2160
      fps: 5 
snapshots:
  enabled: true  
  retain: 
    default: 30  
record:
  enabled: true
  retain_days: 30 
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: 
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p  
  input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
   # record: -f segment -segment_time 120 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv    

rtmp:
  enabled: True

objects:
  track:
    - person
    - car   
    - dog
    - cat
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
 [segment @ 0x55887f24bf00] Non-monotonous DTS in output stream 0:1; previous: 117046, current: 117031; changing to 
```

### FFprobe output from your camera

```shell
Camera 1 (4k that is lagging)

  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, progressive), 3840x2160, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s


Camera 2 (old doorbell, that working OK)
  Metadata:
    title           : pps_rtsp
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 12 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Asecam

### Any other information that may be helpful

Running on Synology DS220+
