### ISSUE TITLE
[Support]: Unknown camera validaton error in `config.yml`

### ISSUE THREAD

**Issue by SeaDude** [blakeblackshear/frigate#3423]
### Describe the problem you are having

I can't tell why `frigate` is seeing a slicing error in my `config.yml` file. I linted the config and its valid YAML.

### Version

NA

### Frigate config file

```yaml
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
logger:
  default: info
record:
  enabled: False
snapshots:
  enabled: False
rtmp:
  enabled: True
cameras:
  test_cam:
    ffmpeg:
      - input_args:
        - -c:v
        - h264
      - path: rtsp://192.168.0.23:554/s1
        roles: 
          - rtmp
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      height: 720
      quality: 70
```

### Relevant log output

```shell
user@system:~/Documents/frigate$ docker logs frigate
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-07-04 11:50:09] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> test_cam
  list indices must be integers or slices, not str (type=type_error)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> test_cam
  list indices must be integers or slices, not str (type=type_error)

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://192.168.0.23:554/s1':
  Metadata:
    title           : s1
  Duration: N/A, start: 0.146000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp
    Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 90k tbn, 30 tbc
```

### Frigate stats

```json
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

UniFi UVC G3 FLEX

### Any other information that may be helpful

Thank you

**Comment by blakeblackshear** [comment]
It's not formatted correctly. I don't know where you got those input args from, but you may end up needing to just use the defaults. I would recommend working through this guide: https://docs.frigate.video/guides/getting_started

Try this:

```yaml
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
logger:
  default: info
record:
  enabled: False
snapshots:
  enabled: False
rtmp:
  enabled: True
cameras:
  test_cam:
    ffmpeg:
      - path: rtsp://192.168.0.23:554/s1
        input_args:
          - -c:v
          - h264
        roles: 
          - rtmp
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      height: 720
      quality: 70
```

**Comment by SeaDude** [comment]
The `input_args` came from the NVIDIA installation docs: https://docs.frigate.video/configuration/nvdec. Looks like I mistakenly

![image](https://user-images.githubusercontent.com/8636973/177237447-400e0b62-1a89-4ddb-a863-40af905d213a.png)

I have the same error using the `config.yml` you posted

![Peek 2022-07-04 19-46](https://user-images.githubusercontent.com/8636973/177240014-8113c919-ac7b-4ad5-a191-94232061954a.gif)

**Comment by SeaDude** [comment]
After further debugging, it appears the `frigate` config parser does not like the `- path` under `ffmpeg`. Even tried quoting the string per [this SO question](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml).

Running docker compose on this minimal config throws the error:

```
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
logger:
  default: info
record:
  enabled: False
snapshots:
  enabled: False
rtmp:
  enabled: True
cameras:
  testcam:
    ffmpeg:
      - path: rtsp://192.168.0.23:554/s1
```

```
user8@system8:~/Documents/frigate$ docker logs frigate
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-07-04 20:18:15] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> testcam
  list indices must be integers or slices, not str (type=type_error)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> testcam
  list indices must be integers or slices, not str (type=type_error)

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by SeaDude** [comment]
I tried to find a relevant `"path"` keyword in the `app.py` and `config.py` source (but my Python is not good!). Sorry man, here is where I'm stuck. Unsure why the validation doesn't like my `- path`.

**Comment by NickM-27** [comment]
It needs `inputs` and path goes inside that

**Comment by SeaDude** [comment]
Eureka! Frigate UI is now up and runnnnniiinnngggg!!! Wahooooo!
Thank you @blakeblackshear and @NickM-27 !
I'll work at making my system's build reproducable, then commence on some (what I'd consider) useful documentation PR's. 
Cheers!

**Comment by SeaDude** [comment]
Just to be thorough, here is the config that works for me. Notice the `inputs:` above `- path` in the yaml hierarchy that @NickM-27 suggested.

```
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
logger:
  default: info
record:
  enabled: False
snapshots:
  enabled: False
rtmp:
  enabled: True
cameras:
  testcam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.23:554/s1
          input_args:
            - -c:v
            - h264
          roles: 
            - rtmp
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      height: 720
      quality: 70
```
