### ISSUE TITLE
Change RTMP Port

### ISSUE THREAD

**Issue by AshtonKem** [blakeblackshear/frigate#3424]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to change the RTMP port that frigate binds to, so that I may run frigate on K8s

**Describe the solution you'd like**
A single config option to change the RTMP port, with the default set to 1935.

**Describe alternatives you've considered**

**Additional context**
By default K8S does not allow TCP load balancing for ports below 30000. This is easy to get around for HTTP access, just use an Ingress Controller, but quite annoying for non-HTTP TCP protocols like RTMP and RTSC. It would be nice if we could configure these to be a higher port, such as 31935, for compatibility with K8S.

**Comment by blakeblackshear** [comment]
The exposed port can be adjusted in the kubernetes service, no need to adjust the container in the port. Same is true for docker port mappings.

**Comment by AshtonKem** [comment]
About 30min after posting this, I found out that I had the wrong config in K8S anyways, so this is doubly unnecessary. Turns out that while NodePort restricts values below 30000, LoadBalancers do not.

For the sanity of anyone stumbling on this in the future, here's what I settled on:

```
Apiversion: v1
kind: Service
metadata:
  name: frigate-lb
  namespace: frigate
spec:
  ports:
  - port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app.kubernetes.io/name: frigate
  type: LoadBalancer
```
