### ISSUE TITLE
Add `ffmpeg.preset`s

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#3429]
## **Describe what you are trying to accomplish and why in non technical terms**
I enable audio for my cameras. This implies that I need to copy all the default args from the documentation, make my modification and add it to my configuration. Every time Frigate updates, I need to double-check the documentation, analyze the new default args and decide whether I need to "rebase" my custom args or not.

I believe others who use other kinds of cameras would fall in the same situation, like the ones mentioned in the documentation: https://docs.frigate.video/configuration/camera_specific

## **Describe the solution you'd like**

A new field named `ffmpeg.preset`. As the name implies, a `preset` would cause the use of preconfigured ffmpeg args instead of the default ones.

### MJPEG as per the docs

Before:

```yaml
cameras:
  my_mjpeg_camera:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v  libx264 -an -f flv
```

After:

```yaml
cameras:
  garden:
    ffmpeg:
      preset: rtsp-mjpeg-generic
```

### Default args but with audio enabled

Before:

```yaml
cameras:
  my_audio_camera:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        rtmp: -c:v copy -c:a aac -f flv
```

After:

```yaml
cameras:
  garden:
    ffmpeg:
      preset: rtsp-h264-generic-audio
```

Some presets could be:

```
rtsp-h264-generic
rtsp-h264-generic-audio
rtsp-mjpeg-generic
rtsp-mjpeg-generic-audio
jpeg-generic # we can leverage `detect.fps` to fill `-r`
http-h264-reolink
http-h264-reolink-audio
rtmp-h264-generic
rtmp-h264-generic-audio
```

And so on.

We could also introduce `ffmpeg.hwaccel_preset`, like:

```
rpi3-4-x64
rpi3-4-x86
intel-before-10th-gen
intel-10th-gen-or-newer
```

And so on.

This have the benefit that users don't need to keep refreshing their args on every new release to keep things optimal (or when newer, and more optmized args are discovered and updated in the documentation), and allows smother upgrades for the likes of https://github.com/blakeblackshear/frigate/pull/2829/commits/b36b63599bde375b5ca7e7619a1d2441a62833c1 which updates `stimeout` to `timeout`.

Community will certainly do a good job of maintaining (and growing) the presets.

## **Describe alternatives you've considered**
The alternative is actually the problem.

## **Additional context**
- Refs #3428
