### ISSUE TITLE
Camera api stream not working on v11

### ISSUE THREAD

**Issue by ChrisSutton123** [blakeblackshear/frigate#3431]
### Describe the problem you are having

Camera api stream not working on v11 (any rc). Okay on v10

http://192.168.3.200:5000/api/RLC-520

### Version

0.11.0-EF54CD6

### Frigate config file

```yaml
detectors:
  cpu:
    type: cpu
    num_threads: 2
    
mqtt:
  host: 192.168.3.200
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqttuser
  password: xxxxx

birdseye:
  mode: objects
  
rtmp:
  enabled: false

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

record:
  enabled: true
  retain:
    days: 4
#    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
          
snapshots:
  enabled: false
      
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.7    

cameras:
  RLC-520:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"  
        
      inputs:
      # 2560x1920
        - path: http://192.168.3.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxx      
#        - path: rtmp://192.168.3.201/bcs/channel0_main.bcs?token=254&channel=0&stream=0&user=admin&password=xxxxx
#        - path: rtsp://admin:xxxx@192.168.3.201:554/h264Preview_01_main        
          roles:
            - record
      # 896x672      
        - path: http://192.168.3.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxxx
#        - path: rtmp://192.168.3.201/bcs/channel0_sub.bcs?token=254&channel=0&stream=0&user=admin&password=xxxxx
#        - path: rtsp://admin:xxxxx@192.168.3.201:554/h264Preview_01_sub
          roles:
            - detect

    detect:
      width: 896
      height: 672
      fps: 5
            
    motion:
      mask: 
        - 641,0,646,48,252,46,256,0

  Amcrest:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        
      inputs:
      # 2592x1944
        - path: rtsp://admin:xxxxx@192.168.3.124:554/cam/realmonitor?channel=1&subtype=00        
          roles:
            - record
      # 640x480      
        - path: rtsp://admin:xxxxx@192.168.3.124:554/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect

    detect:
      width: 640
      height: 480
      fps: 5
```

### Relevant log output

```shell
VLC Error:-

Your input can't be opened:
VLC is unable to open the MRL 'http://192.168.3.200:5000/api/RLC-520'. Check the log for details.

access error: HTTP connection failure
main error: connection failed: Connection refused by peer
http error: cannot connect to 192.168.3.200:5000
```

### FFprobe output from your camera

```shell
Not sure how to do this in HassOS
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-520 and Amcrest IP5M-T1179EW

### Any other information that may be helpful

Works perfectly on v10 after upgrade to v11 doesn't work
