### ISSUE TITLE
[Config Support]: No audio with foscam and Tapo camera  

### ISSUE THREAD

**Issue by balthus** [blakeblackshear/frigate#3433]
### Describe the problem you are having

Hello,

The recordings never contains sound.
I read the faq and used the advised settings but then there are ffmpeg errors. 
Using the same url/stream via vlc does produce some sound (although few second of lags)
I tried with latest build and nightly docker build
I tried with 1 foscam and 2 different tapo cameras and the result is the same.

Maybe there are other ticks/options to make it work?

### Version

0.11.0-ef54cd6

### Frigate config file

```yaml
LivingRoom:
    ffmpeg:
      inputs:
      - path: rtsp://xxxxx
        roles:
          - detect
          - rtmp
          - record     
      output_args:
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        rtmp: -c:v libx264 -an -f flv      
    objects:
      track:
        - person
```

### Relevant log output

```shell
frigate    | [2022-07-06 18:50:41] frigate.video                  ERROR   : LivingRoom: Unable to read frames from ffmpeg process.
frigate    | [2022-07-06 18:50:41] frigate.video                  ERROR   : LivingRoom: ffmpeg process is not running. exiting capture thread...
frigate    | [2022-07-06 18:50:59] watchdog.LivingRoom            ERROR   : Ffmpeg process crashed unexpectedly for LivingRoom.
frigate    | [2022-07-06 18:50:59] watchdog.LivingRoom            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : [aac @ 0x5604d1925540] Too many bits 8832.000000 > 6144 per frame requested, clamping to max
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : [mp4 @ 0x5604d1c79300] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1024 >= 260
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : av_interleaved_write_frame(): Invalid argument
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : [swscaler @ 0x5604d20b3400] deprecated pixel format used, make sure you did set range correctly
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : Finishing stream 1:0 without any data written to it.
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : Finishing stream 2:0 without any data written to it.
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : [flv @ 0x5604d1924680] Failed to update header with correct duration.
frigate    | [2022-07-06 18:50:59] ffmpeg.LivingRoom.detect       ERROR   : [flv @ 0x5604d1924680] Failed to update header with correct filesize.
frigate    | [2022-07-06 18:51:00] frigate.video                  ERROR   : LivingRoom: Unable to read frames from ffmpeg process.
frigate    | [2022-07-06 18:51:00] frigate.video                  ERROR   : LivingRoom: ffmpeg process is not running. exiting capture thread...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

![image](https://user-images.githubusercontent.com/16748341/177604170-700efc23-3948-4485-ad37-7ed7585aad1d.png)
