### ISSUE TITLE
[Support]: Custom model error "TypeError: only size-1 arrays can be converted to Python scalars "

### ISSUE THREAD

**Issue by mexxBf** [blakeblackshear/frigate#3437]
### Describe the problem you are having

Hi,

I trained my own model using this tutorial:
https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb

Its working well in Jupyter and now I try to make it work in frigate as well. 
Sadly I get the following exception while doing so:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 160, in run_detector
    detections = object_detector.detect_raw(input_frame)
  File "/opt/frigate/frigate/edgetpu.py", line 89, in detect_raw
    count = int(
TypeError: only size-1 arrays can be converted to Python scalars

I "imported" the model and the labelmap via docker binding.

my model only has two possible labels.

this is the conent of my labelmap.txt

RomyMitMaus
RomyOhneMaus

this is the row where it fails:

count = int(
            self.interpreter.tensor(self.tensor_output_details[3]["index"])()[0]
        )

but I don't understand what this row does :-/
Thank you :)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.*
  user: *
  password: **
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/*
          roles:
            - detect
        - path: rtsps://192.168.1.1:7441/*
          roles:
            - rtmp
    detect:
      width: 1920
      height: 1080
      stationary:
        interval: 0
        threshold: 50
  links:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.1.1:7441/*
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      stationary:
        interval: 0
        threshold: 50
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - RomyMitMaus
    - RomyOhneMaus
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no r
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      RomyMitMaus: 30
      RomyOhneMaus: 30
# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 384
  # Required: Object detection model input height (default: shown below)
  height: 384
  # Optional: Label name modifications. These are merged into the standard labelmap
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 160, in run_detector
    detections = object_detector.detect_raw(input_frame)
  File "/opt/frigate/frigate/edgetpu.py", line 89, in detect_raw
    count = int(
TypeError: only size-1 arrays can be converted to Python scalars
```

### FFprobe output from your camera

```shell
camera working well
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Unifi
