### ISSUE TITLE
[Config Support]: NVIDIA GPU no processes running

### ISSUE THREAD

**Issue by paultanger** [blakeblackshear/frigate#3442]
### Describe the problem you are having

I'm trying to get NVIDIA GPU running hardware acceleration, but I don't see any ffmpeg processes running when looking at `nvidia-smi`, maybe it is a frigate config setting?  I have 3 rtsp cameras (streaming h264), and one mpeg camera (streaming through http from a raspberry pi).  When I add any `hwaccel_args` to the mpeg stream, it doesn't work and just results in a green screen.  So I have two questions: should I be seeing any processes in `nvidia-smi` and what can I do to my config to get hardware accel working for the mpeg stream decoding and reduce my CPU usage?

Thanks!

### Version

0.11.0-EF54CD6

### Frigate config file

```yaml
mqtt:
  host: <hidden>
  port: 1883
  client_id: frigate
detectors:
  coral1:
    type: edgetpu
    device: pci
birdseye:
  enabled: True
  mode: continuous
  quality: 5
rtmp: # this is for home assistant etc 
  enabled: True
live: # for the web ui
  quality: 5
  height: 720
detect:
  enabled: True
record:
  enabled: True
  expire_interval: 15 # mins to clear
  retain:
    days: 7 
    mode: all # can be all, motion or active_objects
  events:
    retain:
      default: 7 # days
      mode: all # can be motion
motion:
  threshold: 15 # default 25 range 15-50
  contour_area: 30 # default 30
  improve_contrast: True 
model:
  labelmap:
    2: vehicle # car
    3: vehicle # motorcycle
    5: vehicle # bus
    7: vehicle # car / truck
    16: animal # cat
    17: animal # dog
    18: animal # horse
    19: animal # sheep
    20: animal # cow
    21: animal # elephant 
    22: animal # bear
    23: animal # zebra
    24: animal # giraffe 
objects:
  track:  
    - person
    - bicycle
    - animal
  filters:
    animal:
      min_score: .4
      threshold: .50
    person:
      min_score: .5
      threshold: .60
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
cameras:
  front:
    ui:
      order: 0
    ffmpeg:
      hwaccel_args: 
        - -c:v 
        - h264_cuvid
      inputs:
        - path: rtsp://<hidden>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://<hidden>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      enabled: True 
      width: 704
      height: 480
      fps: 5
    record:
      enabled: True
      retain:
        mode: all
  side:
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: 
        - -c:v 
        - h264_cuvid
      inputs:
        - path: rtsp://<hidden>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://<hidden>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: True 
      width: 704
      height: 480
      fps: 5
    record:
      enabled: True
      retain:
        mode: all 
  back:
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: 
        - -c:v 
        - h264_cuvid
      inputs: 
        - path: rtsp://<hidden>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://<hidden>:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    objects:
      filters:
        person:
          min_score: .55
          threshold: .65
    detect:
      enabled: True 
      width: 704
      height: 480
      fps: 5
    record:
      enabled: True
      retain:
        mode: all 
  pi-cam:
    ui:
      order: 3
    timestamp_style:
      position: "tr"
      color:
        red: 255
        green: 255
        blue: 255
    ffmpeg:
      # hwaccel_args:
        # - -c:v 
        # - mjpeg_cuvid
        # - hwaccel cuda
      inputs:
        - path: http://<hidden>/
          roles:
            - detect
            - rtmp
            - record
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    detect:
      enabled: True 
      width: 704 
      height: 480 
      fps: 5 
    objects:
      filters:
        animal:
          min_score: .3
          threshold: .40
        person:
          min_score: .3
          threshold: .40
    record:
      enabled: True 
      retain:
        mode: all
```

### Relevant log output

```shell
From inside the container:

# nvidia-smi
Fri Jul  8 12:47:51 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 00000000:01:00.0 Off |                  N/A |
| 40%   54C    P0    N/A /  N/A |    135MiB /  2000MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

### Frigate stats

```json
{"back":{"camera_fps":5.1,"capture_pid":244,"detection_fps":7.6,"pid":226,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":11.7,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.02,"pid":215}},"front":{"camera_fps":5.0,"capture_pid":229,"detection_fps":0.0,"pid":223,"process_fps":5.0,"skipped_fps":0.0},"pi-cam":{"camera_fps":0.0,"capture_pid":247,"detection_fps":0.0,"pid":228,"process_fps":0.0,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":64.0,"mount_type":"tmpfs","total":67.1,"used":3.1},"/media/frigate/clips":{"free":474237.2,"mount_type":"zfs","total":1610612.7,"used":1136375.5},"/media/frigate/recordings":{"free":474237.2,"mount_type":"zfs","total":1610612.7,"used":1136375.5},"/tmp/cache":{"free":8558.6,"mount_type":"tmpfs","total":8589.9,"used":31.4}},"temperatures":{"apex_0":43.55},"uptime":3703,"version":"0.11.0-ef54cd6"},"side":{"camera_fps":5.0,"capture_pid":232,"detection_fps":4.1,"pid":224,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

PCIe

### Any other information that may be helpful

From inside the container, checking that nvidia codecs:
```
# ffmpeg -decoders | grep cuvid
ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
 V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)
```

The output from the mpeg camera stream:

```
ffmpeg -i http://10.0.0.102:54354
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 704x480 [SAR 1:1 DAR 22:15], 25 tbr, 25 tbn, 25 tbc
```
