### ISSUE TITLE
[Config Support]: Birdseye hardware acceleration

### ISSUE THREAD

**Issue by NPutting** [blakeblackshear/frigate#3447]
### Describe the problem you are having

The ffmpeg process for the birdseye stream isn't using hardware acceleration like the rest of my steams. Is there something I'm missing to enable this or is this by design or not considered yet? I tried reading the documentation and searching github with no luck. I know for cameras we can override ffmpeg settings, is this possible already for birdseye and just not documented?

Here is htop with the birdseye ffmpeg command at the top, it's the only 4k one as I was testing higher outputs. also pictured are my 4 cameras using hardware acceleration.
![image](https://user-images.githubusercontent.com/7637195/178129136-3aac1e4d-d96c-4281-af90-5e07c923e6a0.png)

### Version

 0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: x

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
    
    
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 3840
  # Optional: Height of the output resolution (default: shown below)
  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  
record:
  enabled: true
  retain:
    days: 100
    mode: all

objects:
  track:
    - person
    - dog

detect:
  fps: 5

cameras:
  Doorbell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      threshold: 50
      mask: 
      - 1920,0,1920,1080,1420,1080,1455,861,1472,675,1339,687,959,722,661,743,534,752,401,754,458,1080,0,1080,0,758,0,0,1442,0

  Patio: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x/live
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
      - 0,0,1920,0,1920,1080,1744,1080,1737,1015,1849,1017,1474,229,1275,209,1203,55,697,56,594,192,366,208,0,721
      - 130,972,106,1048,137,1080,233,1080,251,1015,228,959,167,942
      
  Kitchen: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x/live
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 1660,1055,1865,1055,1865,1015,1660,1015

  Living: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://x/unicast
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 1660,1055,1865,1055,1865,1015,1660,1015

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

snapshots:
  enabled: True
  bounding_box: true
  retain:
    default: 100
```

### Relevant log output

```shell
Htop pictured in main text
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe
