### ISSUE TITLE
[Config Support]: Keep getting `extra keys not allowed` using configuration from the README

### ISSUE THREAD

**Issue by mike-code** [blakeblackshear/frigate#3448]
# Update

ugh. I now realised that the `blakeblackshear/frigate:stable-aarch64`(released ~4 months ago) image is using `VERSION='0.8.4-5043040` so I guess my question boils down to: was that indented?

### Describe the problem you are having

I'm trying to apply the minimal configuration the docs but I keep getting `extra keys not allowed` such as

- `extra keys not allowed @ data['record']['expire_interval']`
- `extra keys not allowed @ data['record']['retain']`
- `extra keys not allowed @ data['live']` (same happens if I move `live` key to the `['cameras']['front_door']`
 
also I'm getting keys not provided error even though they are not specified in the README

- ` required key not provided @ data['cameras']['front_door']['width']`

I'm using `blakeblackshear/frigate:stable-aarch64` image @ aarch64 rpi. I've noticed that this image was released ~4 months ago so I assumed it's a release of version `0.10.0`. Nonetheless the [docs/configuration/index.md](https://github.com/blakeblackshear/frigate/blob/v0.10.0/docs/docs/configuration/index.md) file tagged in that release does not comply with the errors I'm getting. What am I doing wrong?

### Version

I can't get to the web UI

### Frigate config file

```yaml
mqtt:
  host: mqtt

cameras:
  front_door: # <------ Name the camera
    detect:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://cam03.lan:554/s0
          roles:
            - rtmp
            - record
            - detect
    record:
      enabled: True
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264

record:
  enabled: True
  expire_interval: 10
  retain:
    days: 14
    mode: all

live:
  height: 1080
  quality: 8
```

### docker-compose file

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yaml:/config/config.yml:ro
      - /camera_fs/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: ""
```

### Relevant log output

```shell
Attaching to frigate, frigate-mqtt-1
frigate         |  * Starting nginx nginx
frigate         |    ...done.
frigate         | Error parsing config: extra keys not allowed @ data['record']['expire_interval']
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
