### ISSUE TITLE
[Config Support]: Error when deploying stack

### ISSUE THREAD

**Issue by MDLefevere** [blakeblackshear/frigate#3460]
### Describe the problem you are having

When i deploy the stack in Portainer i get the following error:
![image](https://user-images.githubusercontent.com/47443715/178438314-3ff7aef1-1987-4b41-bcd7-4f211410464a.png)

**Stack Config:**
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
      #You should not need to map through other devices for hardware acceleration when the Coral TPU is used.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml:ro
      - /home/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "welkom"

**On the host i edited the LXC config to the following:**
arch: amd64
cores: 2
features: nesting=1
hostname: Frigate
memory: 1024
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=3A:BE:EF:69:53:F2,ip=dhcp,type=veth
ostype: debian
rootfs: local-lvm:vm-103-disk-0,size=10G
swap: 512
unprivileged: 1
usb0: host=1a6e:089a,usb3=1
usb1: host=18d1:9302,usb3=1
lxc.cgroup.devices.allow: c 226:0 rwm
lxc.cgroup.devices.allow: c 226:128 rwm
lxc.cgroup.devices.allow: c 29:0 rwm
lxc.cgroup.devices.allow: c 189:* rwm
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:

### Version

-

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Voortuin:
    ffmpeg:
      inputs:
        - path: rtsp:/camera # <-- 101 Mainstream
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5 #Should be sufficient

mqtt:
  host: 192.168.**
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: username
  password: 'password'
  stats_interval: 60
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I've used this GitHub for config example: https://github.com/vandenberghev/Frigate-With-USB-Coral-TPU-In-Docker-In-VM-In-Proxmox
