### ISSUE TITLE
[Support]: Misclassification of objects

### ISSUE THREAD

**Issue by ashwinikalantri** [blakeblackshear/frigate#3475]
### Describe the problem you are having

Objects are all getting classified as persons. Here is a cat getting classified as person. 

![snapshot-1657893752 908388-goosim](https://user-images.githubusercontent.com/4697107/179340093-b659efb6-564b-4420-b393-d26eae75e62a.jpg)
<img width="442" alt="Screenshot 2022-07-16 at 10 25 27 AM" src="https://user-images.githubusercontent.com/4697107/179340107-42908776-1f11-4c62-9658-399e77326d8b.png">

While the night mode was active, there were random detections of persons, when there was nothing in the view. I have deleted those events, but will post them if they get detected again tonight.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 172.16.1.158
  port: 1883
  user: mqtt
  password: *****

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
    # Optional: Mode of the view. Available options are: objects, motion, and continuous
    #   objects - cameras are included if they have had a tracked object within the last 30 seconds
    #   motion - cameras are included if motion was detected in the last 30 seconds
    #   continuous - all cameras are included always
  mode: motion

record:
  enabled: True

cameras:
  outside:
    ffmpeg:
      inputs:
        - path: rtsp://user:*****@<ip>:554/Streaming/channels/101
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - car
    record:
      enabled: True
      events:
        retain:
          mode: all
    snapshots:
      enabled: True
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.240000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2120F-I

### Any other information that may be helpful

I do not have a coral device but the CPU peaks at around 60%.
