### ISSUE TITLE
Camera feed green + several other errors. Please help? 

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#348]
First of all, big thank you for making this! I have been dreaming of such a solution for 2 years now and finally you did it! 👍 I would be eternally grateful if you can help me out. Thank you Blake!

**Describe the bug**
I have experienced several issues:

1. When i use my Samsung Hanwha Techwin camera, the video feed is green. So when i check the URL http://192.168.178.84:5000/Garage, i just see green screen. Ps see attached screenshot below.  With my ezviz camera it works very well. So it must be some camera codec issue with the HANWHA camera perhaps?

2. In general, the ffmepg HW acceleration or any of the global parameters always cause errors. so i removed them all. Also the frigate logs showed error with your default config version because perhaps the ffmpeg arguments have double entries (one in the upper part in the ffmpeg's own config section and then again in the camera section). Removing all these made the frigate work. I just cannot get the ffmpeg HW acceleration working. Tried it with the Raspi3/4 64bit version.

3. I made frigate detection work with another camera (EZVIZ CTQ3W) but i constantly get over 100% CPU even though i'm using the Coral accelerator. Is this normal?

4. The logs always show the following error everytime it starts. "Fontconfig error: Cannot load default config file". Is this normal?

5. I also continuously get "On connect called" but i dont see the docker container running multiple times.

**Version of frigate**
1.3

**Config file**
Include your full config file wrapped in triple back ticks.
```web_port: 5000
detectors:
  coral:
    type: edgetpu
    device: usb
save_clips:
  clips_dir: /media/frigate
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: **XXXXXXX**
  password: **XXXXXXXX**
ffmpeg: {}
cameras:
  Garage:
    ffmpeg:
      input: 'rtsp://192.168.178.234/profile1/media.smp'
    height: 1080
    width: 1920
    fps: 5
    best_image_timeout: 60
    mqtt:
      crop_to_region: true
      snapshot_height: 300
    save_clips:
      enabled: false
      pre_capture: 30
      objects:
        - person
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
```

**Logs**
Fontconfig error: Cannot load default config file
Starting detection process: 16
Attempting to load TPU as usb
Camera capture process started for Garage: 17
Camera process started for Garage: 19
Creating ffmpeg process...
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.178.234/profile1/media.smp -r 5 -f rawvideo -pix_fmt yuv420p pipe:
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: development
 * Debug mode: off
On connect called
TPU found
No frames received from Garage in 5 seconds. Exiting ffmpeg...
Waiting for ffmpeg to exit gracefully...
Garage: ffmpeg sent a broken frame. something is wrong.
Garage: ffmpeg sent a broken frame. something is wrong.
Garage: ffmpeg process is not running. exiting capture thread...
Creating ffmpeg process...
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.178.234/profile1/media.smp -r 5 -f rawvideo -pix_fmt yuv420p pipe:```

**FFprobe from your camera**
This camera has 3 profiles. Did ffprobe for all 3 profiles below.

ubuntu@ubuntu:~$ ffprobe rtsp://192.168.178.234/profile1/media.smp
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://192.168.178.234/profile1/media.smp':
  Metadata:
    title           : Media Presentation
    comment         : samsung
  Duration: N/A, start: 0.052144, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x360 [SAR 1:1 DAR 16:9], 5 tbr, 90k tbn, 90k tbc
    Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1

ubuntu@ubuntu:~$ ffprobe rtsp://192.168.178.234/profile2/media.smp
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://192.168.178.234/profile2/media.smp':
  Metadata:
    title           : Media Presentation
    comment         : samsung
  Duration: N/A, start: 0.013000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1280x720, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1

ubuntu@ubuntu:~$ ffprobe rtsp://192.168.178.234/profile3/media.smp
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://192.168.178.234/profile3/media.smp':
  Metadata:
    title           : Media Presentation
    comment         : samsung
  Duration: N/A, start: 0.025000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 2592x1520, 20 fps, 20 tbr, 90k tbn, 90k tbc
    Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1

**Screenshots**

![image](https://user-images.githubusercontent.com/30929896/101681379-5a3bb300-3a62-11eb-8ffc-2e78c9e7a2d5.png)

![image](https://user-images.githubusercontent.com/30929896/101683132-d59e6400-3a64-11eb-99ad-6ed99dbea0ec.png)

![image](https://user-images.githubusercontent.com/30929896/101683172-e353e980-3a64-11eb-8f38-a54159cebb58.png)

![image](https://user-images.githubusercontent.com/30929896/101684653-0ed7d380-3a67-11eb-98ac-d9d4a47ba2c5.png)

**Computer Hardware**
 - RaspberryPi 4 2GB
 - OS: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1023-raspi aarch64)
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Samsung Hanwha Techwin 
 - Model: QNO-7010R
 - Resolution: tried several video profiles (1080p, 720p, 640x360 etc)
 - FPS: tried several (1 to 20). currently at 5 with the profile1 MJPEG video feed.

Thank you very much in advance! :)
EMRE

**Comment by scottgrobinson** [comment]
Do you know how to build your own docker image? If so - It sounds like it *might* be similar to this: https://github.com/blakeblackshear/frigate/issues/312... Maybe...

I was having the same problem on certain types of RTSP feeds until I increased the timeout. If you're not too sure on building docker images, it my be worth trying the latest beta (0.8.0) which I believe has support for this already in the configuration.

If building your own image - Change frigate/video.py line 196 to increase the 5 seconds to something like 15/20.

**Comment by asemev** [comment]
Thank you Scott. HA did itself the docker installation....

**Comment by blakeblackshear** [comment]
The width and height from the ffprobe output say 640x360.

Try this:
```yaml
web_port: 5000
detectors:
  coral:
    type: edgetpu
    device: usb
save_clips:
  clips_dir: /media/frigate
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: **XXXXXXX**
  password: **XXXXXXXX**
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - fatal
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
cameras:
  Garage:
    ffmpeg:
      input: 'rtsp://192.168.178.234/profile1/media.smp'
    height: 360
    width: 640
    fps: 5
    best_image_timeout: 60
    mqtt:
      crop_to_region: true
      snapshot_height: 300
    save_clips:
      enabled: false
      pre_capture: 30
      objects:
        - person
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
```

**Comment by asemev** [comment]
Hi Blake,

Thank you so much for your help. I didnt try your config proposal yet because i installed the 0.8 Beta as Scott adviced (as it provides much better CPU performance I am super interested to make this work). 

So here is the new config i tried:

detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: emre1972
ffmpeg:
  global_args: '-hide_banner -loglevel fatal'
  hwaccel_args: []
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    record: >-
      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    clips: >-
      -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    rtmp: '-c copy -f flv'
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:KDROSK@192.168.178.209:554/h.264'
          roles:
            - detect
            - rtmp
          global_args: null
          hwaccel_args: null
          input_args: null
      global_args: null
      hwaccel_args: null
      input_args: null
      output_args: null
    width: 1920
    height: 1080
    fps: 5
    mask: 'poly,935,2,1910,9,1912,528,932,50'
    best_image_timeout: 60
    zones:
      Front:
        coordinates: '935,2,1910,9,1912,528,932,50'
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.8
    save_clips:
      enabled: false
      pre_capture: 30
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: false
      retain_days: 30
    rtmp:
      enabled: false
    snapshots:
      show_timestamp: true
      draw_zones: true
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
logger:
  default: info
  logs:
    frigate.mqtt: error
model:
  height: 320
  width: 320
save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 15
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.85


But the Log is showing an error:

 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    ERROR   : Error parsing config: expected str for dictionary value @ data['cameras']['Garage']['ffmpeg']['inputs'][0]['global_args']

Any idea what could be causing this?
Many thanks again!!! :)

Best,
Emre

![image](https://user-images.githubusercontent.com/30929896/101988229-97898600-3c98-11eb-88b3-594b20d0f343.png)

**Comment by blakeblackshear** [comment]
You can't use `null` for your args values.

Try this config:
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: emre1972
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:KDROSK@192.168.178.209:554/h.264'
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    mask: 'poly,935,2,1910,9,1912,528,932,50'
    best_image_timeout: 60
    zones:
      Front:
        coordinates: '935,2,1910,9,1912,528,932,50'
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.8
    save_clips:
      enabled: false
      pre_capture: 30
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: false
      retain_days: 30
    rtmp:
      enabled: false
    snapshots:
      show_timestamp: true
      draw_zones: true
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
logger:
  default: info
  logs:
    frigate.mqtt: error
save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 15
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.85
```

**Comment by asemev** [comment]
Its working now!!! Thank you!

So i cannot use any ffmpeg accelerator then right? I wonder why?

**Comment by blakeblackshear** [comment]
You have to disable protection mode for the addon: https://github.com/blakeblackshear/frigate/issues/340#issue-759790120

Once that is done, try updating your config with:
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args:  -c:v h264_v4l2m2m
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: emre1972
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:KDROSK@192.168.178.209:554/h.264'
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5
    mask: 'poly,935,2,1910,9,1912,528,932,50'
    best_image_timeout: 60
    zones:
      Front:
        coordinates: '935,2,1910,9,1912,528,932,50'
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.8
    save_clips:
      enabled: false
      pre_capture: 30
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: false
      retain_days: 30
    rtmp:
      enabled: false
    snapshots:
      show_timestamp: true
      draw_zones: true
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
logger:
  default: info
  logs:
    frigate.mqtt: error
save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 15
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.85
```

**Comment by asemev** [comment]
I disabled the protected mode. But i think the config you mentioned above is the same as before, right? I mean i dont see the ffmpeg HW acceleration in it...?

**Comment by asemev** [comment]
Oh it is working! My bad. This is so awesome.

**Comment by asemev** [comment]
CPU Performance went down to 30%max on each core. It used to be 90% on each core. This is amazing. Thank you for everything Blake! You're a genius :)

**Comment by asemev** [comment]
Hi Blake, i also added my Garden cam now to the config and the CPU has gone up a lot. Is it normal?

![image](https://user-images.githubusercontent.com/30929896/101991734-e17d6680-3cae-11eb-86e7-9382b2558a13.png)

Thanks.

**Comment by blakeblackshear** [comment]
The CPU load depends on the resolution, frame rates, and the amount of motion from your cameras. Using masks to block off areas with unwanted motion will reduce CPU usage.

**Comment by asemev** [comment]
Thank you. I will tweak the settings.

**Comment by asemev** [comment]
Much better already :)

![image](https://user-images.githubusercontent.com/30929896/101992415-5ce11700-3cb3-11eb-9359-05f06689f1ee.png)

**Comment by asemev** [comment]
Made the mask area bigger and lowered the 2nd camera resolution to 720p. And now its really good.

![image](https://user-images.githubusercontent.com/30929896/101992551-7a62b080-3cb4-11eb-96f5-a410348a7a27.png)

**Comment by asemev** [comment]
Hi Blake, just FYI. I noticed a certain behavior. When frigate starts the cpu load is quite low in the first 1 hour but then later it goes up a lot. I tried this several times. So after applying a bigger mask and lowering the camera res to 720p and lowering the frame rates I reported above that cpu was down to around 30% (with 2 cameras). But pls have a look at the current cpu load now (i havent changed any settings):

![image](https://user-images.githubusercontent.com/30929896/102010817-be02fc00-3d40-11eb-8449-634ecd6adc83.png)

**Comment by blakeblackshear** [comment]
The data at /debug/stats will tell you more about what is happening.

**Comment by asemev** [comment]
Hi Blake, thank you. I cannot get the stats working. Could you please help? :)

i get this error when i go to http://192.168.178.84:5000/debug/stats:

![image](https://user-images.githubusercontent.com/30929896/102190455-58d21680-3eb8-11eb-88ed-0a571a8259c1.png)

This is what i entered in my "configuration.yaml" (I have other sensors so i skipped entering "sensor:" at the top, and config 
 test doesnt report any errors):

  - platform: rest
    name: Frigate Debug
    resource: http://192.168.178.84:5000/debug/stats
    scan_interval: 5
    json_attributes:
      - Garage
      - detection_fps
      - detectors
    value_template: 'OK'  
  - platform: template
    sensors:
      garage_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["Garage"]["camera_fps"] }}'
        unit_of_measurement: 'FPS'
      garage_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["Garage"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      garage_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["Garage"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_coral_inference:
        value_template: '{{ states.sensor.frigate_debug.attributes["detectors"]["coral"]["inference_speed"] }}' 
        unit_of_measurement: 'ms'

**Comment by blakeblackshear** [comment]
Make sure your are using the beta documentation. The new stats ending is `/stats`. Also, no need to setup these rest sensors. The new integration does that for you. https://github.com/blakeblackshear/frigate-hass-integration

**Comment by asemev** [comment]
Thank you Blake. Indeed i was not looking at the beta documentation. my bad.

btw searched HACS but i cannot find your integration. Searched frigate and blakeblackshear...

oh and i started sponsoring you as you have been so kind in helping me out! :)

**Comment by blakeblackshear** [comment]
I appreciate that. You have to add it as a custom repository. It isn't available in the official repo yet: https://hacs.xyz/docs/faq/custom_repositories

**Comment by asemev** [comment]
Thanks again i installed it now 👍 

so just to be sure: I dont need any of the configuration.yaml entries that are mentioned in the original setup instructions right? 
I mean these:

![image](https://user-images.githubusercontent.com/30929896/102223830-7ec1e000-3ee5-11eb-8473-b4c334bd2c58.png)

**Comment by blakeblackshear** [comment]
Correct. Once you add the integration, it will setup all of that for you.

**Comment by asemev** [comment]
awesome, thank you. cleaned up the configuration.yaml now.

**Comment by asemev** [comment]
sorry to disturb you again. Now after i removed all those old entries from the configuration.yaml (as HACS is doing it now), i cannot find the Frigate camera entities (Garage and Garden). Frigate is working so i guess they are hidden? I wanted to add the motion snapshot to my HA main homescreen as a picture entity card..

btw, the stats are working :) Dont know how to interpret those numbers though...

{"Garage":{"camera_fps":5.0,"capture_pid":38,"detection_fps":20.5,"pid":36,"process_fps":4.1,"skipped_fps":0.0},"Garden":{"camera_fps":5.0,"capture_pid":40,"detection_fps":0.0,"pid":37,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":20.5,"detectors":{"coral":{"detection_start":0.0,"inference_speed":20.02,"pid":33}}}

**Comment by blakeblackshear** [comment]
Just to confirm, you did setup the integration after installing with HACS right? Do you see Frigate listed when you go to Configuration > Integrations?

**Comment by asemev** [comment]
No I dont see Frigate in Configuration > Integrations. I guess i did the setup wrong? I installed HACS integration. It seems to be installed well. And i restarted the HA and also the Frigate addon in Supervisor. 

![image](https://user-images.githubusercontent.com/30929896/102228571-24c41900-3eeb-11eb-95da-98867a4dc823.png)

![image](https://user-images.githubusercontent.com/30929896/102228611-2e4d8100-3eeb-11eb-91ed-45150e8f3042.png)

![image](https://user-images.githubusercontent.com/30929896/102228390-efb7c680-3eea-11eb-8b0e-508c33ee03f5.png)

**Comment by asemev** [comment]
![image](https://user-images.githubusercontent.com/30929896/102228693-47563200-3eeb-11eb-8b4b-4513e5535d51.png)

**Comment by asemev** [comment]
![image](https://user-images.githubusercontent.com/30929896/102228846-72408600-3eeb-11eb-9e5d-89ebe9297378.png)

**Comment by blakeblackshear** [comment]
Click the add integration button and search for frigate from the integrations page. HACS just makes it show up in that list, but doesn't enable it.

**Comment by asemev** [comment]
i think i did that already:

![image](https://user-images.githubusercontent.com/30929896/102229179-c5b2d400-3eeb-11eb-8cbd-3f21880f8170.png)

**Comment by asemev** [comment]
![image](https://user-images.githubusercontent.com/30929896/102229303-ea0eb080-3eeb-11eb-88cd-7325c84f2317.png)

**Comment by blakeblackshear** [comment]
That is the HACS page. I'm referring to Configuration > Integrations

**Comment by asemev** [comment]
Oooooooh i see now! Such a rookie i am :) Thanks again!

**Comment by asemev** [comment]
![image](https://user-images.githubusercontent.com/30929896/102229433-19bdb880-3eec-11eb-97ab-e2165122d7a5.png)

**Comment by asemev** [comment]
![image](https://user-images.githubusercontent.com/30929896/102229813-76b96e80-3eec-11eb-966a-f134ae0eda89.png)

**Comment by asemev** [comment]
ok fixed (entered the IP address of my HA)

![image](https://user-images.githubusercontent.com/30929896/102230176-d57ee800-3eec-11eb-8ed4-3b5a5ce45efb.png)

**Comment by asemev** [comment]
HI Blake, 

Since moving to the HACS custom component, and removing all the config.yaml entries, my setup has been very stable now, the CPU load is not going over 30%, so overall super happy! :) Thanks a million for helping me out. This is seriously my dream come true.

The only thing i'm now struggling with is the automations to send me notifications with the snapshots outside my LAN network. I tried many thing but cant get the pictures coming with the notification. also most of the time the notification dosnt come at all. 

- I'm using duckdns: https://asemev.duckdns.org. This is working well since forever.
- I have Nginx configured so i dont need to add a port number at the end of the https://asemev.duckdns.org URL
- Maybe related: My router does not support "NAT Lookup" so i cannot access the https://asemev.duckdns.org URL in my LAN. It only works from the outside like on my phone using mobile network.
- I used your automation example from the Beta instructions:

alias: Notify Person Detection
description: ''
trigger:
  - platform: mqtt
    topic: frigate/events
condition: []
action:
  - service: notify.notify
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: >-
          https://asemev.duckdns.org/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}.jpg?format=android
        tag: '{{trigger.payload_json["after"]["id"]}}'
mode: single

NOTE: I inserted my duckdns URL in here. And maybe thats the problem?

I see the following errors in the HA logs:

Logger: homeassistant.components.automation.garden_person_detection
Source: helpers/service.py:190
Integration: Automation (documentation, issues)
First occurred: December 15, 2020, 11:00:49 PM (6 occurrences)
Last logged: December 15, 2020, 11:05:36 PM

Notify Person Detection: Error executing script. Unexpected error for call_service at pos 1: Error rendering data template: UndefinedError: 'trigger' is undefined
While executing automation automation.garden_person_detection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
    render_result = compiled.render(kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'trigger' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 188, in async_prepare_call_from_config
    service_data.update(template.render_complex(config[conf], variables))
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 93, in render_complex
    return {
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 94, in <dictcomp>
    render_complex(key, variables): render_complex(item, variables)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 98, in render_complex
    return value.async_render(variables)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'trigger' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 429, in _async_call_service_step
    domain, service_name, service_data = service.async_prepare_call_from_config(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 190, in async_prepare_call_from_config
    raise HomeAssistantError(f"Error rendering data template: {ex}") from ex
homeassistant.exceptions.HomeAssistantError: Error rendering data template: UndefinedError: 'trigger' is undefined


Any help would be awesome. Thanks again.

**Comment by asemev** [comment]
Hi Blake, i know you will update your documentation so appreciate that very much. I will wait patiently :)

I'm just wondering if i can access the snapshot image files manually. This way i can manually push the best.jpg via an automation temporarily.

I can see the image at this URL: http://192.168.178.84:5000/Garage/person/best.jpg
But i cannot find the best.jpg file in my filesystem :) Is it perhaps inside the db?

![image](https://user-images.githubusercontent.com/30929896/102535239-3a327200-40a8-11eb-8638-561e18016618.png)

**Comment by blakeblackshear** [comment]
Those are never written to disk. They are retrieved directly from memory.

**Comment by asemev** [comment]
> Do you know how to build your own docker image? If so - It sounds like it _might_ be similar to this: #312... Maybe...
> 
> I was having the same problem on certain types of RTSP feeds until I increased the timeout. If you're not too sure on building docker images, it my be worth trying the latest beta (0.8.0) which I believe has support for this already in the configuration.
> 
> If building your own image - Change frigate/video.py line 196 to increase the 5 seconds to something like 15/20.

Hi Scott, didn't properly thank you for your support earlier. Your suggestion totally fixed the green video issue. So thanks a lot again.

**Comment by asemev** [comment]
Hi Blake, any chance you can help me out with the latest thing remaining which is the picture attachment in the noifications? I really need this to work. Thanks a lot.

**Comment by blakeblackshear** [comment]
What version of homeassistant are you using? The key error message I see is `jinja2.exceptions.UndefinedError: 'trigger' is undefined`.

This looks correct to me:

```yaml
alias: Notify Person Detection
description: ''
trigger:
  - platform: mqtt
    topic: frigate/events
action:
  - service: notify.notify
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: 'https://asemev.duckdns.org/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}.jpg?format=android'
        tag: '{{trigger.payload_json["after"]["id"]}}'
mode: single
```
