### ISSUE TITLE
[Config Support]: A significant performance drop after upgrade from 0.11 beta 5 to beta 6 on Haswell CPU

### ISSUE THREAD

**Issue by Aculeasis** [blakeblackshear/frigate#3499]
### Describe the problem you are having

My i7-4770k has a significant performance drop
```
top
beta 5 without vaapi
 767663 root      20   0  865272 145728  21200 S  30.0   0.9   0:34.45 ffmpeg
 767656 root      20   0  854764  60728  20176 S   5.0   0.4   0:06.12 ffmpeg   
beta 5 with vaapi 
 768415 root      20   0  905132 113612  39972 S  17.6   0.7   0:13.53 ffmpeg
 768410 root      20   0  864508  61952  21320 S   7.3   0.4   0:05.67 ffmpeg
beta 6 without vaapi
 765945 root      20   0 1554208 168448  24076 S  39.3   1.0   0:25.43 ffmpeg
 765939 root      20   0 1542240  81840  22848 S   7.3   0.5   0:05.27 ffmpeg 
beta 6 with vaapi
 766645 root      20   0 1595808 140920  42896 S  28.9   0.9   0:09.28 ffmpeg
 766641 root      20   0 1552040  82968  23888 S  14.0   0.5   0:03.93 ffmpeg 
```
And this does not look like a problem of hardware acceleration (`LIBVA_DRIVER_NAME_JELLYFIN=i965` has also no effect)
```
intel_gpu_top -l
Beta 5
 Freq MHz      IRQ RC6 Power     IMC MiB/s           RCS/0           BCS/0           VCS/0          VECS/0 
 req  act       /s   %     W     rd     wr       %  se  wa       %  se  wa       %  se  wa       %  se  wa 
 200  200       17  51  0.50      0    479   13.99   0   0    0.00   0   0   14.48   0   0    0.00   0   0 
 200  200       16  50  0.51      0    490   13.99   0   0    0.00   0   0   14.48   0   0    0.00   0   0 
 200  200       17  51  0.50      0    469   14.48   0   0    0.00   0   0   14.98   0   0    0.00   0   0 
 200  200       16  50  0.50      0    477   15.97   0   0    0.00   0   0   14.48   0   0    0.00   0   0 
 200  200       17  50  0.51 262097    484   14.98   0   0    0.00   0   0   12.99   0   0    0.00   0   0 
 200  200       16  50  0.50      0    481   14.49   0   0    0.00   0   0   12.00   0   0    0.00   0   0 
 200  200       17  50  0.53      0    568   13.00   0   0    0.00   0   0   13.48   0   0    0.00   0   0 
 200  200       16  50  0.51      0    482   12.49   0   0    0.00   0   0   13.00   0   0    0.00   0   0
Beta 6
 Freq MHz      IRQ RC6 Power     IMC MiB/s           RCS/0           BCS/0           VCS/0          VECS/0 
 req  act       /s   %     W     rd     wr       %  se  wa       %  se  wa       %  se  wa       %  se  wa 
 200  200       17  52  0.49      0    507   14.49   0   0    0.00   0   0   10.98   0   0    0.00   0   0 
 200  200       16  52  0.47  11259    501   12.51   0   0    0.00   0   0   11.98   0   0    0.00   0   0 
 200  200       16  52  0.49 250823    512   10.99   0   0    0.00   0   0   12.97   0   0    0.00   0   0 
 200  200       17  52  0.48      0    505   11.99   0   0    0.00   0   0   13.99   0   0    0.00   0   0 
 200  200       16  52  0.48      0    510   10.49   0   0    0.00   0   0   13.99   0   0    0.00   0   0 
 200  200       17  52  0.50      0    533   13.99   0   0    0.00   0   0   14.98   0   0    0.00   0   0 
 200  200       16  52  0.51      0    562   14.49   0   0    0.00   0   0   15.49   0   0    0.00   0   0 
 200  200       17  52  0.50 262085    529   15.47   0   0    0.00   0   0   14.97   0   0    0.00   0   0 
```

### Version

0.11.0-ed1897d

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": false,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "First": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": false,
        "mode": "objects"
      },
      "detect": {
        "enabled": false,
        "fps": 8,
        "height": 720,
        "max_disappeared": 40,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": 3000,
            "objects": {}
          },
          "threshold": 80
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": "-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p",
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://**********.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://*********.3:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif",
            "roles": [
              "detect",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*************.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/First-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*************.3:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif -c copy -f flv rtmp://127.0.0.1/live/First -r 8 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "442,0,0,0,0,720,523,720",
          "874,720,1067,720,1074,83,861,86"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "First",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.3,
            "threshold": 0.45
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 365,
            "mode": "motion",
            "objects": {
              "person": 365
            }
          }
        },
        "expire_interval": 120,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m.%d.%y %H:%M:%S",
        "position": "bl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    },
    "Second": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": false,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 8,
        "height": 720,
        "max_disappeared": 40,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": 3000,
            "objects": {}
          },
          "threshold": 80
        },
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": "-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p",
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://*********.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif",
            "roles": [
              "detect",
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://********.2:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif",
            "roles": [
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://***********.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy /tmp/cache/Second-%Y%m%d%H%M%S.mp4 -r 8 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://**********.2:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif -c copy -f flv rtmp://127.0.0.1/live/Second",
          "roles": [
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "192,0,0,0,0,201",
          "0,720,220,720,252,662,0,448",
          "1096,720,1105,490,1042,191,1014,119,972,52,980,126,700,109,717,74,696,0,1280,0,1280,720",
          "1101,662,1103,688,949,695,953,665"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "Second",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.65
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 10,
          "pre_capture": 10,
          "required_zones": [],
          "retain": {
            "default": 365,
            "mode": "motion",
            "objects": {
              "person": 365
            }
          }
        },
        "expire_interval": 120,
        "retain": {
          "days": 30,
          "mode": "motion"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 30,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m.%d.%y %H:%M:%S",
        "position": "bl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 8,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": 3000,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu2": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": "-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p",
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-timeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy",
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {
      "frigate.record": "debug",
      "ws4py": "warning"
    }
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "*.*.*.*",
    "password": null,
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": null
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "plus": {
    "enabled": false
  },
  "record": {
    "enabled": true,
    "events": {
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 365,
        "mode": "motion",
        "objects": {
          "person": 365
        }
      }
    },
    "expire_interval": 120,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m.%d.%y %H:%M:%S",
    "position": "bl",
    "thickness": 2
  },
  "ui": {
    "use_experimental": false
  }
}
```

### Relevant log output

```shell
There is no interesting there
```

### Frigate stats

```json
{"Hall":{"camera_fps":8.1,"capture_pid":233,"detection_fps":0.0,"pid":230,"process_fps":8.1,"skipped_fps":0.0},"Portal":{"camera_fps":8.1,"capture_pid":239,"detection_fps":0.0,"pid":232,"process_fps":8.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":52.74,"pid":222},"cpu2":{"detection_start":0.0,"inference_speed":51.84,"pid":224}},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":264.9,"mount_type":"tmpfs","total":268.4,"used":3.5},"/media/frigate/clips":{"free":639440.3,"mount_type":"ext4","total":983429.0,"used":293961.8},"/media/frigate/recordings":{"free":639440.3,"mount_type":"ext4","total":983429.0,"used":293961.8},"/tmp/cache":{"free":992.7,"mount_type":"tmpfs","total":1000.0,"used":7.3}},"temperatures":{},"uptime":436,"version":"0.11.0-ed1897d"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

OS: Ubuntu 20.04.4 LTS

The streams for the detects:
 - First: H.264B, 1280x720, 8 fps, VBR, 10 i-frame interval
 - Second: H.264B, 2560x1440, 16 fps, VBR, 32 i-frame interval

Docker cli configurations
```bash
#!/bin/bash

docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/dri/renderD128 \
  --shm-size=256m \
  -v /mnt/hdd1/frigate/storage:/media/frigate \
  -v /mnt/hdd1/frigate/config.yml:/config/config.yml:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -e LIBVA_DRIVER_NAME_JELLYFIN=i965 \
  -p 5000:5000 \
  -p 1935:1935 \
  blakeblackshear/frigate:0.11.0-beta6


```

**Comment by NickM-27** [comment]
What happens if you try:

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
```

with and without `LIBVA_DRIVER_NAME_JELLYFIN=i965`? Please paste the different CPU numbers for these 👍
