### ISSUE TITLE
[Support]: Tracked Objects out of zone

### ISSUE THREAD

**Issue by gettingerr** [blakeblackshear/frigate#3505]
### Describe the problem you are having

Tracked objects are showing even though they are out of a required zone. They do not show as events which is correct, but on the camera page, the most recent snapshot in the tracked objects space below the feed shows snapshots of images where the tracked object is in the street and not in my required driveway zones. This seems to be leading to issues with the Home Assistant notification as well where I am notified for these tracked objects but if I try to open the event, it doesn't exist since it was not in a required zone. Is this proper functionality?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
################################################################
mqtt:
  host: my ip address
  user: my username
  password: my password
################################################################
detectors: 
  cpu1:
    type: cpu
    num_threads: 1
################################################################
detect:
  enabled: True
  width: 1920
  height: 1080
  fps: 5
  max_disappeared: 25
################################################################
objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
  filters:
    car:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
    person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
################################################################
motion:
  threshold: 20
  contour_area: 25
  frame_height: 45
################################################################
record:
  enabled: True
  retain:
    days: 5
    mode: all
  events:
    max_seconds: 240
    pre_capture: 10
    post_capture: 10
    objects:
      - person
      - car
    retain:
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      mode: motion
################################################################
rtmp:
  enabled: True
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 480
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
################################################################
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  height: 200
  retain:
    default: 30
################################################################
timestamp_style:
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"
################################################################

#####
  Driveway_Camera:
    ffmpeg:
      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - nobuffer+genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - "5000000"
      inputs:
        - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=nodepass
          roles:
            - record
            - rtmp
        - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=user&password=password
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 640
      height: 480
      fps: 4
    record:
      events:
        required_zones: 
          - Driveway_Near
          - Driveway_Mid
    snapshots:
      required_zones: 
        - Driveway_Near
        - Driveway_Mid
    zones:
      Driveway_Near:
        coordinates: 0,480,0,239,52,218,115,179,525,266,452,480
        objects:
          - car
          - person
      Driveway_Mid:
        coordinates: 278,103,118,177,527,270,556,137
        objects:
          - car
          - person
      Driveway_Far:
        coordinates: 349,65,270,105,551,138,565,85
    objects:
      track:
        - person
        - car
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
#####
```

### Relevant log output

```shell
No supporting logs
```

### FFprobe output from your camera

```shell
Not part of the issue
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLN 410
