### ISSUE TITLE
[Support]: Camera live stream stops working on mobile

### ISSUE THREAD

**Issue by CZonin** [blakeblackshear/frigate#3507]
### Describe the problem you are having

For awhile I've noticed that specifically on my Android tablet and phones using the mobile app that the live stream will run into an issue and stop. I have to close out the app and restart it to get the stream back. I've never experienced it on web. I primarily view the stream using the Frigate card (https://github.com/dermotduffy/frigate-hass-card), but not sure if the issue is with Frigate or the card, so going to start here.
![Screenshot_20220722-112927_Home Assistant](https://user-images.githubusercontent.com/67965669/180474353-99328450-ca71-47fe-b314-9b5542455aa5.jpg)

### Version

3.1

### Frigate config file

```yaml
# frigate.yml
mqtt:
  host: xxx.xxx.xx.xx
  port: 1883
  user: hamqtt
  password: removed

record:
  enabled: true
  retain:
    days: 1
    mode: motion
  events:
    max_seconds: 120
    pre_capture: 1
    post_capture: 1
    retain:
      default: 1
      mode: motion

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 1

birdseye:
  enabled: false

detectors: 
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

cameras:
  front_doorbell:
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        person:
          min_score: 0.8
          min_area: 20000
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 960
      fps: 5
    live:
      height: 960
      quality: 8
    motion:
      mask:
        - 2352,623,2385,1009,2303,1619,2560,1812,2560,0,1880,0,2171,102
        - 1804,0,299,0,347,411,1110,277,1702,287
    zones:
      my_driveway:
        coordinates: 2162,1371,2028,1337,2011,1322,2011,1252,2038,1187,2083,1159,2176,1114,2372,1091,2335,1378
        objects:
          - person
          - motorcycle
      neighbor_driveway_1:
        coordinates: 1734,1187,1677,1133,1621,1072,1494,1075,1517,1125,1568,1196
        objects:
          - person
          - motorcycle
      neighbor_driveway_2:
        coordinates: 2052,1136,1949,1063,1891,1057,1767,1052,1694,1117,1897,1179
        objects:
          - person
          - motorcycle
    mqtt:
      quality: 85
      bounding_box: false
      height: 960
  den:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 0,0,1920,0,1920,190,1515,112,1159,86,649,82,306,99,0,169
        - 0,834,0,1080,88,1080,29,953
    zones:
      office_entry:
        coordinates: 0,640,114,996,576,996,493,98,0,192
        objects:
          - person
    mqtt:
      quality: 85
      bounding_box: false
      height: 720
  backyard:
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.8
        cat:
          min_score: 0.8
        dog:
          min_score: 0.8
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 1920,0,1829,90,1784,124,1717,211,1435,140,1057,120,844,129,653,162,400,203,0,493,0,323,0,0
    mqtt:
      quality: 85
      bounding_box: false
      height: 720
  nursery:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://admin:removed@xxx.xxx.xx.xx:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles: 
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 1280
      height: 720
      fps: 5
    live:
      height: 720
      quality: 8
    motion:
      mask:
        - 0,376,0,1080,352,1080,140,722
        - 1920,459,1920,1080,1532,1080,1705,827
    mqtt:
      quality: 85
      bounding_box: false
      height: 720
```

### Relevant log output

```shell
[2022-07-22 07:13:59] ffmpeg.front_doorbell.detect   ERROR   : [flv @ 0x56176bc787c0] Failed to update header with correct duration.
[2022-07-22 07:13:59] ffmpeg.front_doorbell.detect   ERROR   : [flv @ 0x56176bc787c0] Failed to update header with correct filesize.
[2022-07-22 11:30:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51110]
[2022-07-22 11:30:25] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51110]
[2022-07-22 11:30:29] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:52088]
[2022-07-22 11:30:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:52088]
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest AD410, Amcrest ASH21-W
