### ISSUE TITLE
Reducing CPU load: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3510]
### Describe the problem you are having

My Frigate CPU usage hovers around 50% and I need to get this down.

Frigate continues to work well and I've now eliminated practically all false positives!

I've changed all of my cameras to Dahua IPC-HFW5442E-ZE, which are excellent.

Please can you take a look at my config and give me some hints as to how I can optimise it to reduce the CPU load?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.105
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

database:
  path: /media/frigate/clips/frigate.db

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

detectors:
  # cpu1:
  #   type: cpu
  coral:
    type: edgetpu
    device: usb
# resolution was 640x352 changed to 1920x1080
cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            # - detect
        # - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=2 # <----- Update for your camera
        #   roles:
        #     - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 20
    objects:
      track:
        - car
      filters:
        # person:
        #   threshold: 0.5
        #   min_score: 0.8
        car:
          threshold: 0.4
          min_score: 0.65
          # mask:
          #   - 1920,0,1920,363,27,1080,2,1
          #   - 1920,592,1920,1080,27,1080,0,417
        # horse:
        #   threshold: 0.5
        #   min_score: 0.8
    motion:
      mask:
        - 704,0,704,88,0,68,0,0
        - 0,576,704,576,704,209,0,174
      # threshold: 15
    zones:
      left:
        coordinates: 0,77,0,138,241,142,239,92
      middle:
        coordinates: 258,152,449,165,454,125,254,100
      right:
        coordinates: 704,145,704,206,459,169,456,119
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  turning_circle: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 355,267,423,256,428,215,356,216
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 0,0,0,171,355,196,355,257,438,259,437,220,640,201,640,0
    zones:
      # circle:
      #   coordinates: 0,207,348,201,352,267,427,258,434,207,640,204,640,200,640,480,83,480,77,289
        tc_east:
          coordinates: 0,480,362,480,363,192,0,187
        tc_west:
          coordinates: 640,480,369,480,367,195,640,197
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - circle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  car_park: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.6
          min_score: 0.76
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 280,160,348,209,403,125,408,99,301,90,279,103         
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,39,187,21,326,29,280,89,288,172,447,346,493,139
    zones:
      carpark:
        coordinates: 640,480,0,480,0,211,57,175,234,45,283,55,284,164
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - carpark
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  south_terrace: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
          mask:
            - 640,101,640,197,130,217,0,255,0,107
            - 640,480,640,340,509,275,350,480,411,480
        dog:
          threshold: 0.5
          min_score: 0.55
    motion:
      mask:
        - 640,0,640,236,315,227,0,207,0,0
    zones:
      rear_lawn:
        coordinates: 640,266,640,480,335,480,195,264,191,235
      terrace:
        coordinates: 345,480,0,480,0,273,126,231,191,228
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - terrace
          - rear_lawn
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south_east: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.208:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.208:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.6
        dog:
          threshold: 0.5
          min_score: 0.5
    motion:
      mask:
        - 390,0,640,0,640,137,399,155,93,183,184,352,0,352,0,0  
    zones:
      rear_lawn:
        coordinates: 188,352,640,352,640,151,486,156,124,191        
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - rear_lawn
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south_west: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.22:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.22:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.8
          mask:
            - 269,156,309,163,304,102,278,101
            - 188,158,149,149,151,114,177,108
            - 368,79,367,105,349,107,346,80
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 0,74,610,68,508,352,640,352,640,0,0,0
    zones:
      west:
        coordinates: 128,174,204,170,203,79,258,87,258,160,334,164,327,78,572,113,554,205,497,352,391,352,0,352,0,101,126,92
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - west
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.56:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.56:554/11 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,210,1920,0,793,0,743,0,752,38,802,50,1083,130
      # threshold: 15
    # zones:
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east_terrace: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
        dog:
          threshold: 0.5
          min_score: 0.6
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
    motion:
      mask:
        - 640,0,0,0,0,158,0,157,640,152
      # threshold: 15
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  courtyard: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    # objects:
    #   track:
    #     - person
    #     - car
    #   filters:
    #     person:
    #       threshold: 0.8
    #       min_score: 0.75
    #     car:
    #       # threshold: 0.5
    #       min_score: 0.3
    # motion:
    #   mask:
    #     - 0,129,640,141,640,0,0,0
    #     - 0,352,562,352,640,350,640,200,319,205,0,205
    #   threshold: 15
    # zones:
    #   # approaching:
    #   #   coordinates: 0,170,237,165,239,143,0,136
    #   driving:
    #     coordinates: 0,184,0,136,623,141,638,144,637,186
    #   # leaving:
    #   #   coordinates: 432,166,576,170,575,148,435,141
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  greenhouse: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - cat
        - dog
      filters:
        cat:
          threshold: 0.6
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100
  
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-07-23 09:52:19] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-07-23 09:52:19] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-07-23 09:52:19] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-07-23 09:52:19] peewee_migrate                 INFO    : There is nothing to migrate
[2022-07-23 09:52:19] frigate.app                    INFO    : Output process started: 214
[2022-07-23 09:52:19] ws4py                          INFO    : Using epoll
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for driveway: 219
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for turning_circle: 222
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for car_park: 225
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for south_terrace: 227
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for garage_south_east: 229
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for garage_south_west: 231
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for east: 233
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for east_terrace: 235
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for courtyard: 236
[2022-07-23 09:52:19] frigate.app                    INFO    : Camera processor started for greenhouse: 239
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for driveway: 240
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for turning_circle: 243
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for car_park: 246
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for south_terrace: 249
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for garage_south_east: 256
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for garage_south_west: 265
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for east: 272
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for east_terrace: 287
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for courtyard: 296
[2022-07-23 09:52:19] frigate.app                    INFO    : Capture process started for greenhouse: 299
[2022-07-23 09:52:19] ws4py                          INFO    : Using epoll
[2022-07-23 09:52:19] detector.coral                 INFO    : Starting detection process: 213
[2022-07-23 09:52:19] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-07-23 09:52:22] frigate.edgetpu                INFO    : TPU found
[2022-07-23 09:58:42] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46222]
[2022-07-23 10:00:30] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46222]
```

### Frigate stats

```json
{"driveway": {"camera_fps": 20.0, "process_fps": 20.0, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 219, "capture_pid": 240}, "turning_circle": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 222, "capture_pid": 243}, "car_park": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 225, "capture_pid": 246}, "south_terrace": {"camera_fps": 5.0, "process_fps": 5.0, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 227, "capture_pid": 249}, "garage_south_east": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 229, "capture_pid": 256}, "garage_south_west": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 231, "capture_pid": 265}, "east": {"camera_fps": 5.0, "process_fps": 5.0, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 233, "capture_pid": 272}, "east_terrace": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.7, "pid": 235, "capture_pid": 287}, "courtyard": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 236, "capture_pid": 296}, "greenhouse": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 0.0, "pid": 239, "capture_pid": 299}, "detectors": {"coral": {"inference_speed": 31.82, "detection_start": 0.0, "pid": 213}}, "detection_fps": 0.7, "service": {"uptime": 911, "version": "0.10.1-83481af", "storage": {"/media/frigate/recordings": {"total": 983749.4, "used": 540264.8, "free": 403468.4, "mount_type": "ext4"}, "/media/frigate/clips": {"total": 983749.4, "used": 540264.8, "free": 403468.4, "mount_type": "ext4"}, "/tmp/cache": {"total": 8342.5, "used": 24.6, "free": 8317.8, "mount_type": "tmpfs"}, "/dev/shm": {"total": 8342.5, "used": 13.0, "free": 8329.5, "mount_type": "tmpfs"}}, "temperatures": {}}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Running on a Dell 3040 with 16Gb ram.
CPU usage peaks to 100% with Frigate 45-55% typical
Memory usage 17% typical
Disk usage 57%

**Comment by NickM-27** [comment]
For starters you're running one of your cameras detection at 20 fps which is very high, any particular reason for that?

Are the sub streams the same size as the width and height you put into the config under detect?

Other than those things, your usage seems what I'd expect for that many cameras running a 6th gen celeron

**Comment by ripvega** [comment]
Thanks for the reply, Nick.

The substreams are set as per the camera substreams. Should I be using a different one?

The options I have are:
704*576
640*480
352*288

I running the first camera at 20fps as I'm trying to detect vehicles moving left to right and right to left across the frame to detect direction using three zones.
<img width="642" alt="Screenshot 2022-07-23 at 12 46 59" src="https://user-images.githubusercontent.com/42817627/180603584-686f711d-5413-44d2-b82d-d7fd7cde5788.png">

With slower frame rates, vehicles get missed. I'm open to alternatives though!

**Comment by NickM-27** [comment]
That makes sense, I really don't think there's much that can be done to lower CPU usage, might be time for a CPU upgrade

**Comment by shred86** [comment]
Doubt it will help but I noticed some of your `detect:` resolutions are incorrect. For example, for your `garage_south_east:` camera, you have:

````
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 5
````

There’s a few others set to 640x480 which I don’t know if that’s intentional. Might be worth just checking all the camera `detect:` resolutions.
