### ISSUE TITLE
What does this error mean?: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3518]
### Describe the problem you are having

I am repeatedly seeing an error that I don't understand.

Please can you explain it and where to look for a solution?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.105
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

database:
  path: /media/frigate/clips/frigate.db

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

detectors:
  # cpu1:
  #   type: cpu
  coral:
    type: edgetpu
    device: usb
# resolution was 640x352 changed to 1920x1080
cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            # - detect
        # - path: rtsp://admin:password@10.0.1.35:554/cam/realmonitor?channel=1&subtype=2 # <----- Update for your camera
        #   roles:
        #     - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 20
    objects:
      track:
        - car
      filters:
        # person:
        #   threshold: 0.5
        #   min_score: 0.8
        car:
          threshold: 0.4
          min_score: 0.65
          # mask:
          #   - 1920,0,1920,363,27,1080,2,1
          #   - 1920,592,1920,1080,27,1080,0,417
        # horse:
        #   threshold: 0.5
        #   min_score: 0.8
    motion:
      mask:
        - 704,0,704,88,0,68,0,0
        - 0,576,704,576,704,209,0,174
      # threshold: 15
    zones:
      left:
        coordinates: 0,77,0,138,241,142,239,92
      middle:
        coordinates: 258,152,449,165,454,125,254,100
      right:
        coordinates: 704,145,704,206,459,169,456,119
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  turning_circle: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.40:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 355,267,423,256,428,215,356,216
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 0,0,0,171,355,196,355,257,438,259,437,220,640,201,640,0
    zones:
      # circle:
      #   coordinates: 0,207,348,201,352,267,427,258,434,207,640,204,640,200,640,480,83,480,77,289
      tc_east:
        coordinates: 0,480,362,480,363,192,0,187
      tc_west:
        coordinates: 640,480,369,480,367,195,640,197
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        # required_zones:
        #   - tc_east
        #   - tc_west
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  car_park: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.42:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.6
          min_score: 0.76
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 280,160,348,209,403,125,408,99,301,90,279,103         
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,39,187,21,326,29,280,89,288,172,447,346,493,139
    zones:
      carpark:
        coordinates: 640,480,0,480,0,211,57,175,190,79,290,96,284,164
      # top_of_drive:
      #   coordinates: 254,39,304,49,293,87,209,76
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - carpark
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  south_terrace: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.52:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
          mask:
            - 640,101,640,197,130,217,0,255,0,107
            - 640,480,640,340,509,275,350,480,411,480
        dog:
          threshold: 0.5
          min_score: 0.55
    motion:
      mask:
        - 640,0,640,236,315,227,0,207,0,0
    zones:
      rear_lawn:
        coordinates: 640,266,640,480,335,480,195,264,191,235
      terrace:
        coordinates: 345,480,0,480,0,273,126,231,191,228
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - terrace
          - rear_lawn
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south_east: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.208:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.208:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.6
        dog:
          threshold: 0.5
          min_score: 0.5
    motion:
      mask:
        - 390,0,640,0,640,137,399,155,93,183,184,352,0,352,0,0  
    zones:
      rear_lawn:
        coordinates: 188,352,640,352,640,151,486,156,124,191        
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - rear_lawn
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  garage_south_west: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.22:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.22:554/11 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.8
          mask:
            - 269,156,309,163,304,102,278,101
            - 188,158,149,149,151,114,177,108
            - 368,79,367,105,349,107,346,80
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 0,74,610,68,508,352,640,352,640,0,0,0
    zones:
      west:
        coordinates: 128,174,204,170,203,79,258,87,258,160,334,164,327,78,572,113,554,205,497,352,391,352,0,352,0,101,126,92
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - west
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.56:554/12 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.56:554/11 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,210,1920,0,793,0,743,0,752,38,802,50,1083,130
      # threshold: 15
    # zones:
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east_terrace: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
        dog:
          threshold: 0.5
          min_score: 0.6
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
    motion:
      mask:
        - 640,0,0,0,0,158,0,157,640,152
      # threshold: 15
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  courtyard: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    # objects:
    #   track:
    #     - person
    #     - car
    #   filters:
    #     person:
    #       threshold: 0.8
    #       min_score: 0.75
    #     car:
    #       # threshold: 0.5
    #       min_score: 0.3
    # motion:
    #   mask:
    #     - 0,129,640,141,640,0,0,0
    #     - 0,352,562,352,640,350,640,200,319,205,0,205
    #   threshold: 15
    # zones:
    #   # approaching:
    #   #   coordinates: 0,170,237,165,239,143,0,136
    #   driving:
    #     coordinates: 0,184,0,136,623,141,638,144,637,186
    #   # leaving:
    #   #   coordinates: 432,166,576,170,575,148,435,141
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  greenhouse: # <------ Name the camera
    ffmpeg:
      # hwaccel_args:
      #   - -hwaccel
      #   - qsv
      #   - -qsv_device
      #   - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:password@10.0.1.55:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - cat
        - dog
      filters:
        cat:
          threshold: 0.6
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100
```

### Relevant log output

```shell
[2022-07-24 14:13:52] ffmpeg.east_terrace.record     ERROR   : [segment @ 0x5570798e1ec0] Non-monotonous DTS in output stream 0:0; previous: 865067723, current: 865067723; changing to 865067724. This may result in incorrect timestamps in the output file.
[2022-07-24 14:13:52] ffmpeg.east_terrace.record     ERROR   : [segment @ 0x5570798e1ec0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
