### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by jonofmac** [blakeblackshear/frigate#3538]
### Describe the problem you are having

Is there a suggested method to debug unexpected zone violations.

I have an issue where a zone is "entered" even though the tracked object is nowhere near it. Is there a way to turn on event debug mode or something that saves additional tracking information, or perhaps even just a snapshot of the frame that it states violated the boundary (if it's not the snapshot that is shown in an event, I don't know how it chooses which snapshot to use)

The orange line is my 'driveway' zone, and the snapshot provided to me clearly shows it nowhere near the zone boundaries.
The car drove down the street at a constant speed.
![snapshot-1658860527 501959-t05fls](https://user-images.githubusercontent.com/11986470/181087540-0cd4f3d7-b028-4b07-ba30-ab1e83c80eff.jpg)
![driveway](https://user-images.githubusercontent.com/11986470/181087549-e53bff53-bd3d-4f1e-b881-c5f701b2bc24.jpg)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
driveway_camera:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: rtsp://<user>:<pass>@192.168.2.204:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
            - clips
            - record
    rtmp:
      enabled: False
    detect:
        width: 1920
        height: 1080
        fps: 5
    motion:
      mask:
        - 821,0,823,130,1273,234,1385,146,1390,0
        - 531,0,68,0,84,203,377,126,556,69
    zones:
      driveway:
        coordinates: 1171,420,1292,250,1452,224,1653,0,1920,0,1920,1080,0,1080,0,404,319,305,666,278
        objects:
          - person
          - car
          - cat
          - dog
      street:
        coordinates: 93,272,67,97,811,21,821,122
        objects:
          - car
          - person
    record:
      events:
        required_zones:
          - driveway
    snapshots:
      required_zones:
        - driveway
```

### Relevant log output

```shell
No log information since there were no errors.
```

### FFprobe output from your camera

```shell
Not needed
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2783G2-IZS

**Comment by NickM-27** [comment]
You can follow https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing to download the events mp4, add it to the config (MAKE SURE TO SET THE SAME ZONES, MASKS, FPS, RESOLUTION, ETC. as the actual camera) and then you will be able to use the debug camera view to watching a close approximation of what happened during the actual event.

**Comment by jonofmac** [comment]
That link is very helpful. I'd suggest it get moved (or perhaps copied, since it does pertain to setting up a dev env for contributing code) to some other topic other than "contributing". Perhaps a "debug" section might make sense to add.

For anyone who stumbles across this thread,
I simply modified the camera path in ffmpeg to point to the .mp4 file instead so I could change as little, and my server is basically a test environment right now anyway (still running my production NVR while I try to bring frigate up to my liking).

I changed this code:
```
driveway_camera:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: rtsp://hass:m4c1n705h@192.168.2.204:554/Streaming/Channels/101/

```

to this

```
  driveway_camera:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      inputs:
        - path: /media/frigate/driveway-test.mp4
          input_args: -re -stream_loop -1 -fflags +genpts

```

This keeps all of my masks and settings for the camera (since I am not deleting or touching anything but the camera path itself) and enabled me to watch the playback of the file in debug view (go to camera in the web ui, click debug, then show regions and masks).

Doing this showed me that it was actually a funny coincident of timing and a false car was detected in my region. I can fix this by applying a min_area filter.

This is also extremely useful because you can use the same clip and keep replaying it to tweak your settings without having to go outside and keep manually recreating it. Extremely useful for setting up masks and automations!

I do not know why it selected a screenshot of the actual car on the street for the event, when it was an object on the driveway that triggered the alert

You can see the false car objectr below circled in blue
![false car](https://user-images.githubusercontent.com/11986470/181092092-928b1f1e-9265-40e7-b225-089136c1c44a.jpg)
.
