### ISSUE TITLE
[Support]: Event viewer filters when "all" is selected on Camera, Zone, or Label

### ISSUE THREAD

**Issue by andreklug** [blakeblackshear/frigate#3563]
### Describe the problem you are having

Hi, I just started using Frigate and got it working with one camera so far. I thought that the camera wasn't recording always, but when I select a filter more clips are becoming visible. For example:

all filters are set to "all": Only 5 events visible

![image](https://user-images.githubusercontent.com/13343357/181956131-33249437-6954-4215-b6d3-811f7b3a3da0.png)

Filter is set to bird: different events visible

![image](https://user-images.githubusercontent.com/13343357/181956961-bf039f9d-41a5-4591-a6dd-8887eb8b4ec8.png)

Filter is set to Zone treppen: 7 Events visible, not sure if those are all that have been recorded yet.

![image](https://user-images.githubusercontent.com/13343357/181958555-69914943-e797-4f2b-9e6c-1af180b0053d.png)

This doesn't make sense to me. Can I do something to fix this?

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: mosquitto.home
  port: 8883
  topic_prefix: 'frigate'
  client_id: 'frigate'
  user: 'frigate-nvr'
  password: 'redacted'
  tls_ca_certs: /ssl/XXXXXXX
  tls_insecure: false

detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3  
  
database:
  path: /database/frigate.db

logger:
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

cameras:
  eingang:
    ffmpeg:
      #hwaccel_args:
        #- -hwaccel
        #- vaapi
        #- -hwaccel_device
        # - /dev/dri/renderD128  #renderD128
        # - -c:v
        #- h264_yuv420p
      inputs:
        - path: rtsp://USER:PASS@IP:554/Streaming/channels/101/
          roles:
            - record
        - path: rtsp://USER:PASS@IP:554/Streaming/channels/102/
          roles:
            - rtmp
            - detect
          
    detect:
      max_disappeared: 20
      width: 640
      height: 480
      fps: 15
    objects:
      track:
        - person
        - bicycle
        - bird
        - cat
        - dog
        - handbag
        - tie
        - backpack
        - suitcase
        - skis
      #filters:
      #  person:
      #    min_score: 0.6
      #    threshold: 0.75
    snapshots:
      enabled: true
    record:
        enabled: true
    rtmp:
        enabled: true
    live:
      height: 720
      quality: 8
    zones:
      treppen:
        coordinates: 247,480,238,402,482,445,472,480
      fläche:
        coordinates: 472,446,479,400,546,303,563,223,392,125,282,174,146,251,181,318,232,398
      weg:
        coordinates: 257,60,242,0,296,0,325,35,401,109,295,162
```

### Relevant log output

```shell
I don't know where to find the logs yet
```

### FFprobe output from your camera

```shell
HIGH RES:
root@frigate:/media/frigate/media/recordings/2022-07/30/20/eingang# ffprobe rtsp://redacted:554/Streaming/channels/101/
ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://redacted:554/Streaming/channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: adpcm_g726le, 8000 Hz, mono, s16, 16 kb/s


LOW RES:
root@frigate:/media/frigate/media/recordings/2022-07/30/20/eingang# ffprobe rtsp://redacted:554/Streaming/channels/102/
ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55740b595a00] RTP: dropping old packet received too late
    Last message repeated 18 times
Input #0, rtsp, from 'rtsp://redacted:554/Streaming/channels/102/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.433333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x360, 15 fps, 20 tbr, 90k tbn, 30 tbc
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

HikVision DS-2CD2142FWD
