### ISSUE TITLE
[Config Support]: Hwaccel on CPU?

### ISSUE THREAD

**Issue by andreklug** [blakeblackshear/frigate#3564]
### Describe the problem you are having

Hi, I am wondering if any kind of hardware acceleration is possible with Debian (QEMU in Proxmox). I have set the CPU to host or max, the latter gives me the following output:

`processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 8
model name      : AMD Ryzen 7 2700 Eight-Core Processor
stepping        : 2
microcode       : 0x800820d
cpu MHz         : 3193.998
cache size      : 512 KB
physical id     : 0
siblings        : 6
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx
16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi
2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr virt_ssbd arat npt nrip_save arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 6387.99
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:
`

Is Hardware acceleration only possible with a GPU?

### Version

0.11.0-37325c7

### Frigate config file

```yaml
I can run frigate only with all hwaccel arguments disabled, otherwise I am getting the errors below

cameras: #        - path: rtsp://andre:andre123@192.168.53.180/Streaming/Channels/101
  eingang:
    ffmpeg:
      #hwaccel_args:
        #- -hwaccel
        #- vaapi
        #- -hwaccel_device
        #- /dev/dri/renderD128  #renderD128
        #- -c:v
        #- h264_v4l2m2m
```

### Relevant log output

```shell
frigate  | [2022-07-30 23:21:00] frigate.video                  ERROR   : eingang: Unable to read frames from ffmpeg process.
frigate  | [2022-07-30 23:21:00] frigate.video                  ERROR   : eingang: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-07-30 23:21:17] watchdog.eingang               ERROR   : Ffmpeg process crashed unexpectedly for eingang.
frigate  | [2022-07-30 23:21:17] watchdog.eingang               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB
