### ISSUE TITLE
[Config Support]: Can't stop events triggering for people on the sidewalk

### ISSUE THREAD

**Issue by totalitarian** [blakeblackshear/frigate#3576]
### Describe the problem you are having

HI all,

Frigate keeps capturing people on the sidewalk despite me setting up zones to prevent this. Any idea what is wrong?

### Version

0.11 rc1

### Frigate config file

```yaml
database:
  path: /frigate.db


mqtt:
  host: xxx
  user: xxx
  password: xxx


detectors:
  coral:
    type: edgetpu
    device: usb


birdseye:
  enabled: false
  width: 1280
  height: 720
  quality: 8
  mode: continuous

record:
  enabled: true
  retain:
    days: 15
    mode: all
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 21
      mode: motion


snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  retain:
    # Required: Default retention days (default: shown below)
    default: 21

cameras:
  garden:
    rtmp:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.66:8554/garden-main
          roles:
            - record
        - path: rtsp://192.168.1.66:8554/garden-sub
          roles:
            - detect
    detect:
      fps: 5
    motion:
      mask:
        - 439,241,387,0,0,0,0,280
    objects:
      track:
        - person

  side:
    rtmp:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.66:8554/side-main
          roles:
            - record
        - path: rtsp://192.168.1.66:8554/side-sub
          roles:
            - detect
    motion:
      mask:
        - 441,0,451,164,398,149,281,85,0,241,0,0
    detect:
      fps: 5
    objects:
      track:
        - person

  doorbell:
    rtmp:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.66:8554/doorbell-main
          roles:
            - record
            - detect
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
            
    detect:
      fps: 5
      width: 2560
      height: 1440
      
    record:
      events:
        required_zones:
          - driveway
    snapshots:
      required_zones:
        - driveway
    zones:
      driveway:
        coordinates: 573,677,576,888,2560,916,2560,1440,0,1440,0,663
        objects:
          - person
```

### Relevant log output

```shell
.
```

### Frigate stats

```json
{"detection_fps":5.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.23,"pid":212}},"doorbell":{"camera_fps":5.1,"capture_pid":224,"detection_fps":4.9,"pid":218,"process_fps":5.1,"skipped_fps":0.0},"garden":{"camera_fps":5.1,"capture_pid":219,"detection_fps":0.0,"pid":215,"process_fps":5.1,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":258.7,"mount_type":"tmpfs","total":268.4,"used":9.8},"/media/frigate/clips":{"free":1766349.3,"mount_type":"cifs","total":1999387.5,"used":233038.2},"/media/frigate/recordings":{"free":1766349.3,"mount_type":"cifs","total":1999387.5,"used":233038.2},"/tmp/cache":{"free":986.8,"mount_type":"tmpfs","total":1000.0,"used":13.2}},"temperatures":{},"uptime":68078,"version":"0.11.0-37325c7"},"side":{"camera_fps":5.7,"capture_pid":220,"detection_fps":0.1,"pid":216,"process_fps":5.7,"skipped_fps":0.0}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

The red zone (driveway) is the only area of my doorbell cam that I want to detect people.
Here is an example where an event was raised even those the person is outside the driveway zone
