### ISSUE TITLE
[Support]: Use secret file

### ISSUE THREAD

**Issue by PanMat** [blakeblackshear/frigate#3578]
### Describe the problem you are having

I tried putting values like user name and password in secrets.yaml but "!secrets username" did not work in frigate.yml.

Is there a way to remove sensitive information from frigate.yml and refactor into secrets.yaml file?

### Version

3.1

### Frigate config file

```yaml
#Configuration for Frigate
mqtt:
  host: <redacted>
  user: <redacted>
  password: '<redacted>'
  #topic_prefix: frigate
#Camera
cameras:
  wans01:
    ffmpeg:
      inputs:
        - path: rtsp://camera:<redacted>@<redacted>/live/ch0
          roles:
            - detect
            - clips
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: true
      retain: 
        days: 10

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
  cpu5:
    type: cpu
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Wansview v w4
