### ISSUE TITLE
[Support]: Home assistant notification spam

### ISSUE THREAD

**Issue by bluesk1d** [blakeblackshear/frigate#3596]
### Describe the problem you are having

I am using the example found here regarding updating existing notifications: https://docs.frigate.video/guides/ha_notifications/

```
alias: Frigate person detection
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
  - condition: or
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: group.family
            state: home
          - condition: state
            entity_id: input_boolean.overnight
            state: "off"
action:
  - service: notify.mobile_app
    data_template:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected by
        {{trigger.payload_json["after"]["camera"]}} camera
      data:
        image: >-
          https://hclcrlv6ss5oz9gwb926qra5h6co1we0.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
```

I get notifications over and over while the event is active rather than any kind of update. Home Assistant actually rate limited me and advised there would be no more notifications until midnight after the 500 sent by this automation.

Is there a new/better way to do this or am I just doing something silly?

Mobile device: Pixel 4
Mobile HA app version: 2022.6.0-full

Frigate version 0.11.0-3C46A33 (also happens on non-beta releases)

Home Assistant 2022.8.1
Supervisor 2022.07.0
Operating System 8.4

### Version

0.11.0-3C46A33

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.6
  user: redacted
  password: redacted
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  porch_east:
    rtmp:
      enabled: False
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    motion:
      mask:
        - 1532,971,1241,976,1251,894,702,551,813,266,949,129,1010,124,733,0,1920,0,1920,1080,1714,1080,1920,654,1920,96,1653,752 #bush/street/overlap
        - 332,0,335,38,0,40,0,0 #timestamp
    zones:
      Porch:
        coordinates: 1619,782,1839,876,1702,1080,0,1080,0,517,194,446,441,377,539,434,542,548,602,589,653,568,1517,1027
      Driveway:
        coordinates: 1078,148,805,308,712,256,681,232,668,201,644,84,850,38
    record:
      enabled: True
      retain:
        days: 0
  doorbell:
    rtmp:
      enabled: False
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/
          roles:
            - detect
            - record
    detect:
      width: 1600
      height: 1200
    motion:
      mask:
        - 1572,144,1161,323,980,331,997,923,1252,842,1258,702,1600,792 #sidewalk/street
        - 0,31,313,30,312,0,0,0 #timestamp
    zones:
      Porch:
        coordinates: 988,930,1229,830,1562,934,1546,1050,1495,1200,593,1200,596,1055
      Frontyard:
        coordinates: 1567,912,1600,778,1416,736,1264,828
      Driveway:
        coordinates: 1256,698,1257,830,1420,739
    record:
      enabled: True
      retain:
        days: 0
  backyard:
    rtmp:
      enabled: False
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.30.116:554/H264/ch1/main/av_stream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    motion:
      mask:
        - 124,340,290,235,568,97,738,39,742,0,0,0,0,434 # Timestamp
        - 518,323,604,395,683,435,767,494,821,563,833,613,799,649,742,645,673,581,572,548,466,467,410,401,377,304,414,219,470,192,511,306,536,259,555,201,604,206,608,289 # Lower bushes
        - 927,147,921,61,1014,36,1038,86,1055,121,1101,108,1110,144,1183,167,1273,172,1292,261,1107,204,1098,158,974,124 # Upper bushes
    zones:
      Deck:
        coordinates: 1779,491,1799,376,1498,250,1201,478,1707,721
      Patio:
        coordinates: 1378,335,1466,289,1384,283,940,160,494,343,841,546,819,571,919,648,866,688,961,761,927,779,1039,862,922,946,970,976,936,1018,1016,1080,1500,1080,1303,974,1415,762,1189,650,1266,586,1193,543,1198,483    
objects:
  track:
    - person
    - cat
    - dog
record:
  enabled: True
  retain:
    days: 14
  events:
    retain:
      default: 180
      mode: active_objects
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
// 20220805190029
// https://frigate.1tp.co/api/stats

{
  "backyard": {
    "camera_fps": 6.0,
    "capture_pid": 242,
    "detection_fps": 0.0,
    "pid": 233,
    "process_fps": 6.0,
    "skipped_fps": 0.0
  },
  "detection_fps": 0.0,
  "detectors": {
    "coral": {
      "detection_start": 0.0,
      "inference_speed": 7.94,
      "pid": 5908
    }
  },
  "doorbell": {
    "camera_fps": 5.1,
    "capture_pid": 238,
    "detection_fps": 0.0,
    "pid": 231,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "porch_east": {
    "camera_fps": 5.0,
    "capture_pid": 235,
    "detection_fps": 0.0,
    "pid": 229,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "service": {
    "latest_version": "0.10.1",
    "storage": {
      "/dev/shm": {
        "free": 114.1,
        "mount_type": "tmpfs",
        "total": 134.2,
        "used": 20.1
      },
      "/media/frigate/clips": {
        "free": 3543188.2,
        "mount_type": "ext4",
        "total": 23435036.8,
        "used": 19891294.9
      },
      "/media/frigate/recordings": {
        "free": 3543188.2,
        "mount_type": "ext4",
        "total": 23435036.8,
        "used": 19891294.9
      },
      "/tmp/cache": {
        "free": 988.3,
        "mount_type": "tmpfs",
        "total": 1000.0,
        "used": 11.7
      }
    },
    "temperatures": {
      
    },
    "uptime": 364418,
    "version": "0.11.0-3c46a33"
  }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
