### ISSUE TITLE
[Config Support]: Google Coral & Frigate on HASSIO RPI4

### ISSUE THREAD

**Issue by martijnrenkema** [blakeblackshear/frigate#3606]
### Describe the problem you are having

Has the google coral usb a LED light(on/blinking/whatever) when it is plugged in?
I received mine today and it looks like it is DOA. 

It not shows up in the hardware page on HAssio. and frigate doesnt recognized a coral usb. (Also tried different usb port on Rpi4) 

I also plugged it in my macbook but it doesnt do anything.

Anyone a solution to test it out?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: xxxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: xxxx
  
detectors:
  coral:
    type: edgetpu
    device: usb
    
cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://camera1:554/Streaming/Channels/302/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

### Relevant log output

```shell
no
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
