### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by husnainali09** [blakeblackshear/frigate#3618]
### Describe the problem you are having

Whoops forgot to add title

Detection and recording dramas. New user.

front_road camera  picks very inconsistently in the driveway area and only picks motion more consistently in the road area (pre and post masking). Does not record anything even with record active.
Living_room camera picks motion and does snapshots and all correctly but does not record any clips.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.245
  user: mqtt-user
  password: XXXX
  
cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
    record:
      enabled: true
      retain: 
        days: 0
        mode: all
      events:
        max_seconds: 120
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - bus
          - bicycle
          - motorcycle
          - cat
          - dog
        retain:
          default: 2
          mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256
        
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.92/ch0_0.h264
          roles:
            - record
        - path: rtsp://192.168.1.92/ch0_1.h264 
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle
    record:
      enabled: true
      retain: 
        days: 0
        mode: all
      events:
        max_seconds: 120
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - bus
          - bicycle
          - motorcycle
          - cat
          - dog
        retain:
          default: 2
          mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2

  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.90/ch0_1.h264 
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.93/ch0_1.h264
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
        
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.95/ch0_1.h264
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
        
  Dining:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.91/ch0_1.h264
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
        
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu  
  cpu5:
    type: cpu
  cpu6:
    type: cpu
    
rtmp:
  enabled: false
```

### Relevant log output

```shell
mqtt:
  host: 192.168.1.245
  user: mqtt-user
  password: kom128
  
cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
    record:
      enabled: true
      retain: 
        days: 0
        mode: all
      events:
        max_seconds: 120
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - bus
          - bicycle
          - motorcycle
          - cat
          - dog
        retain:
          default: 2
          mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256
        
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.92/ch0_0.h264
          roles:
            - record
        - path: rtsp://192.168.1.92/ch0_1.h264 
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle
    record:
      enabled: true
      retain: 
        days: 0
        mode: all
      events:
        max_seconds: 120
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - bus
          - bicycle
          - motorcycle
          - cat
          - dog
        retain:
          default: 2
          mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2

  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.90/ch0_1.h264 
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.93/ch0_1.h264
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
        
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.95/ch0_1.h264
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
        
  Dining:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.91/ch0_1.h264
          roles:
            - detect
            - clips
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
        
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu  
  cpu5:
    type: cpu
  cpu6:
    type: cpu
    
rtmp:
  enabled: false
```

### Frigate stats

```json
{"Dining":{"camera_fps":5.0,"capture_pid":262,"detection_fps":0.0,"pid":246,"process_fps":5.0,"skipped_fps":0.0},"Garage":{"camera_fps":5.1,"capture_pid":258,"detection_fps":0.0,"pid":245,"process_fps":5.1,"skipped_fps":0.0},"backyard":{"camera_fps":5.1,"capture_pid":256,"detection_fps":0.0,"pid":243,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":109.24,"pid":222},"cpu2":{"detection_start":0.0,"inference_speed":113.39,"pid":224},"cpu3":{"detection_start":0.0,"inference_speed":115.94,"pid":225},"cpu4":{"detection_start":0.0,"inference_speed":111.8,"pid":226},"cpu5":{"detection_start":0.0,"inference_speed":114.82,"pid":230},"cpu6":{"detection_start":0.0,"inference_speed":120.94,"pid":232}},"driveway":{"camera_fps":5.0,"capture_pid":249,"detection_fps":0.0,"pid":240,"process_fps":5.0,"skipped_fps":0.0},"front_road":{"camera_fps":5.0,"capture_pid":247,"detection_fps":0.0,"pid":238,"process_fps":5.0,"skipped_fps":0.0},"living_room":{"camera_fps":5.3,"capture_pid":252,"detection_fps":0.0,"pid":242,"process_fps":5.2,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":62.0,"mount_type":"tmpfs","total":67.1,"used":5.1},"/media/frigate/clips":{"free":16904.6,"mount_type":"btrfs","total":21646.6,"used":4742.1},"/media/frigate/recordings":{"free":16904.6,"mount_type":"btrfs","total":21646.6,"used":4742.1},"/tmp/cache":{"free":16904.6,"mount_type":"btrfs","total":21646.6,"used":4742.1}},"temperatures":{},"uptime":343,"version":"0.10.1-83481af"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Front_road camera is hikvision 4k and 2nd stream is 640x480. Ive played around with different and constant bitrate with no effect.
All remaining cameras are Xiaomi dome or outdoor with yihack5 rtsp. ESXI on synology on docker.

**Comment by NickM-27** [comment]
Please include your logs, that could give helpful information

> front_road camera picks very inconsistently in the driveway area and only picks motion more consistently in the road area (pre and post masking). Does not record anything even with record active.

Doesn't record anything at all (if you click on recordings in the main cameras page)? Or just doesn't create clips for the event?

I think it would be helpful to see a snapshot of your front_road camera with masks enabled. 

> Living_room camera picks motion and does snapshots and all correctly but does not record any clips.

You haven't enabled recordings for that camera so that makes sense

Also it should be noted that your objects lists are incorrect. You have 

```yaml
objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
    record:
      enabled: true
      retain: 
        days: 0
        mode: all
      events:
        max_seconds: 120
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - car
          - bus
          - bicycle
          - motorcycle
          - cat
          - dog
        retain:
          default: 2
          mode: motion
```

but the `record -> events -> objects` needs to be a sublist of the `camera -> objects -> track` list. You have bus in the latter list but never defined it in the list of objects that the camera tracks so that will do nothing. 

You also defined a `clips` role which does not exist anymore. It needs to be `record` instead

**Comment by husnainali09** [comment]
`cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
        record:
          enabled: true
          retain: 
            days: 0
            mode: all
          events:
            max_seconds: 120
            pre_capture: 5
            post_capture: 5
            objects:
              - person
              - car
              - bus
              - bicycle
              - motorcycle
              - cat
              - dog
            retain:
              default: 2
              mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256`

**Comment by husnainali09** [comment]
> cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
        record:
          enabled: true
          retain: 
            days: 0
            mode: all
          events:
            max_seconds: 120
            pre_capture: 5
            post_capture: 5
            objects:
              - person
              - car
              - bus
              - bicycle
              - motorcycle
              - cat
              - dog
            retain:
              default: 2
              mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256

>

**Comment by husnainali09** [comment]
`cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
        record:
          enabled: true
          retain: 
            days: 0
            mode: all
          events:
            max_seconds: 120
            pre_capture: 5
            post_capture: 5
            objects:
              - person
              - car
              - bus
              - bicycle
              - motorcycle
              - cat
              - dog
            retain:
              default: 2
              mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256`

**Comment by husnainali09** [comment]
'''
cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
        record:
          enabled: true
          retain: 
            days: 0
            mode: all
          events:
            max_seconds: 120
            pre_capture: 5
            post_capture: 5
            objects:
              - person
              - car
              - bus
              - bicycle
              - motorcycle
              - cat
              - dog
            retain:
              default: 2
              mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256
'''

**Comment by husnainali09** [comment]
,,,

cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
        record:
          enabled: true
          retain: 
            days: 0
            mode: all
          events:
            max_seconds: 120
            pre_capture: 5
            post_capture: 5
            objects:
              - person
              - car
              - bus
              - bicycle
              - motorcycle
              - cat
              - dog
            retain:
              default: 2
              mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256

,,,

**Comment by husnainali09** [comment]
[config2.txt](https://github.com/blakeblackshear/frigate/files/9290490/config2.txt)
Does this look correct now ?

**Comment by husnainali09** [comment]
Ok that probably wasnt correct as got heap of errors in logs

**Comment by husnainali09** [comment]
How do i post my yaml code here with formatting (Noob question)

**Comment by NickM-27** [comment]
You use backticks (not single quotes) ```

**Comment by husnainali09** [comment]
```cameras:
  # Name of your camera
  front_road:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:KOM.128.kom@192.168.1.97:554/Streaming/Channels/102
          roles:
            - detect  
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle   
    record:
      enabled: true
      retain: 
        days: 0
        mode: all
      events:
        max_seconds: 120
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: motion
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain: 
        default: 2
    motion:
      mask:
        - 0,167,0,253,29,252,46,247,60,238,73,223,66,201,61,184,42,180,110,168,185,171,243,177,309,183,392,197,449,205,538,224,640,245,640,0,0,0
        - 640,245,640,480,600,480,582,480,560,459,552,444,542,415,529,376,517,337,500,286,489,222
        - 0,312,21,335,55,358,89,364,113,349,129,328,149,305,166,284,168,263,154,253,128,245,65,243,0,256```

**Comment by NickM-27** [comment]
The 3 backticks at the end need to be on their own line but yes that's good

**Comment by NickM-27** [comment]
config for that looks better, still interested in what those masks look like

**Comment by husnainali09** [comment]
Ok recording seems to be working on living room cam but no events on front cam, been dancing out in 5C cold trying to get it to trigger

https://ibb.co/1d3fLDn
https://ibb.co/BqM5bBR

Both cams and fronts mask

**Comment by husnainali09** [comment]
It is a high mounted hikvision 4k turrent cam.

**Comment by NickM-27** [comment]
Oh okay I see, you will want to do this:

```yaml
camera:
  front_road:
    motion:
      improve_contrast: true
```
