### ISSUE TITLE
[Config Support]: Google Coral USB accelerator not detected on Home Assistant OS 8.4

### ISSUE THREAD

**Issue by kukaturbo** [blakeblackshear/frigate#3624]
### Describe the problem you are having

I recently got a google coral usb accelerator and I am not able to connected it to frigate. When I plug it to my RPI4 and start the frigate add-on the system starts to get unstable (several bad gateways errors and unable to check logs).  I have to unplugged it and reboot home assistant.

I haven't detected anything in the host logs, but it seams that it's missing drivers to install google coral usb accelerator. I have read that Home Assistant OS 8.4 already has the driver pre installed and it should be only plug and play.

Please advice on how to troubleshoot the issue.

Many thanks for your help.
Vítor

### Version

Home Assistant OS 8.4 with version 2022.8.3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.144
  user: mqtt_user
  password: *******

cameras:
  hall_cam:
    ffmpeg:
      inputs:
        - path: rtsp://**********@192.168.1.65:554/play2.sdp
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 1
  bed_cam:
    ffmpeg:
      inputs:
        - path: rtsp://***********@192.168.1.70:554/play2.sdp
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 1
  office_cam:
    ffmpeg:
      inputs:
        - path: rtsp://***********@192.168.1.147:554
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 1

rtmp:
  enabled: False 

detectors:
  coral:
    type: edgetpu
    device: usb


#detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
```

### Relevant log output

```shell
not applicable yet
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
