### ISSUE TITLE
[Support]: Can I view bounding boxes on recorded video

### ISSUE THREAD

**Issue by scottjjr** [blakeblackshear/frigate#3637]
### Describe the problem you are having

Hi, am having an issue where cars are regulalry recognised going in one direction (up the drive past the house), but generally missed in the other direction (down the drive past the house), and find cars & people are hit & miss when it's dark. 

Assume I might need to do some tuning from the defaults. I've lowered the threshold and upped the detect framerate to see if that gives better results (cars go a little faster down than up).

Is there a way where I can run the debug window (where it shows the bounding boxes) over previously recorded video to assist with tuning?

### Version

0.11-rc1

### Frigate config file

```yaml
logger:
  default: debug

mqtt:
  host: mqtt.home

ui:
  use_experimental: true

record:
  enabled: true
  retain:
    days: 21
    mode: all
  events:
    retain:
      default: 60
      mode: motion

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - cat

  filters:
    person:
      min_score: 0.4
      threshold: 0.6
    car:
      min_score: 0.4
      threshold: 0.6


cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://<camera>:554/Streaming/Channels/102
          roles:
           - detect
           - rtmp

        - path: rtsp://<camera>:554/Streaming/Channels/101
          roles:
           - record

    detect:
      width: 1280
      height: 720
      fps: 10
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hilook IPC-T281H-MU

**Comment by NickM-27** [comment]
For the night issue you'll likely want to set `motion -> improve_contrast` to true

https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing will let you get a camera setup to debug previous recordings. Be sure to set it up exactly as the original camera

**Comment by scottjjr** [comment]
Brilliant thanks for that.

**Comment by NickM-27** [comment]
https://docs.frigate.video/development/contributing#2-modify-your-local-config-file-for-testing

**Comment by bortek** [comment]
sorry po post on a closed issue but can anyone elaborate a bit on how to was this achieved. That is how to overlay and see bounding boxes on a already recorded video like in a debug view. Alternatively how to make the recordings contain the bounding boxes (for the future recording)

**Comment by mchugh19** [comment]
@bortek I had the same question and just got it going. 

1. Using version 0.14, the review tab shows the clips where a person was (mis)detected. Once you select a clip, you have the option to export the clip. This will save the file in /media/frigate somewhere.
2. In my case recordings are done off the main video stream and are thus too large to use by themselves for detection. So I have to convert the large video down to the detect stream size. 
`ffmpeg -i /media/frigate/exports/front2_l6qaj9.mp4 -vf scale="704:576" /media/frigate/exports/resized.mp4`
3. Now that you have a clip of the detect sized video, you can add it to your frigate config so it runs on a loop. 
```
cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/exports/resized.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
```
If desired, you can add mask lines to this to match your real camera setup
4. After restarting frigate, you should now see an additional "test" camera, which should be playing a loop of what previously triggered object detection. You can then bring up the settings screen, go to the debug tab, display the test camera, and watch for object detection triggers.
