### ISSUE TITLE
[Support]: Javascript Error when clicking on "Show Event Details"

### ISSUE THREAD

**Issue by VTEX999** [blakeblackshear/frigate#3647]
### Describe the problem you are having

 Javascript Error when clicking on "Show Event Details":  Uncaught (in promise) TypeError: can't access property "toLocaleString", N is null

### Version

0.10.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.XXX

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 5
      mode: motion

birdseye:
  enabled: true
  mode: continuous

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - cat
    - dog

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.1.XXX/1/1
          roles:
           - rtmp
           - detect
           - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.1.XXX/1/1
          roles:
           - rtmp
           - detect
           - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"detection_fps":5.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.15,"pid":213}},"driveway":{"camera_fps":5.1,"capture_pid":223,"detection_fps":5.9,"pid":220,"process_fps":5.1,"skipped_fps":0.0},"front":{"camera_fps":5.0,"capture_pid":222,"detection_fps":0.0,"pid":219,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":63.3,"mount_type":"tmpfs","total":67.1,"used":3.8},"/media/frigate/clips":{"free":95208.3,"mount_type":"overlay","total":105089.3,"used":4495.4},"/media/frigate/recordings":{"free":95208.3,"mount_type":"overlay","total":105089.3,"used":4495.4},"/tmp/cache":{"free":95208.3,"mount_type":"overlay","total":105089.3,"used":4495.4}},"temperatures":{},"uptime":7804,"version":"0.10.1-83481af"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

VEEZOOM IPR5150BSBN
