### ISSUE TITLE
[Support]: MQTT - end_time is always "null"

### ISSUE THREAD

**Issue by gklank** [blakeblackshear/frigate#3659]
### Describe the problem you are having

Hi,

I am trying to use the mqtt topic "frigate/events'" for triggering further messages, etc. etc.

But all my events entries are not showing any end_time in the mqtt server, as described:

Message published for each changed event. The first message is published when the tracked object is no longer marked as a false_positive. When frigate finds a better snapshot of the tracked object or when a zone change occurs, it will publish a message with the same id. When the event ends, a final message is published with end_time set.

### Version

blakeblackshear/frigate:0.11.0-rc1 - docker

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.250
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mosquitto
  password: 1234466
  stats_interval: 60

logger:
  default: info
  logs:
    frigate.event: debug

detectors:
  coral:
    type: edgetpu
    device: usb
  #cpu1:
    #type: cpu

cameras:
  Garage-2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456789@192.168.1.213:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:123456789@192.168.1.213:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: false
    detect:
      width: 1280
      height: 720
      fps: 10
      max_disappeared: 50
    objects:
      track:
        - person
        - cat
      #filters:
        #person:
          #min_area: 16000
          #max_area: 80000
          #min_score: 0.5
          #threshold: 0.7
        #cat:
          #min_area: 2500
          #max_area: 15000
          #min_score: 0.5
          #threshold: 0.5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
      required_zones:
        - zone_garage_hauptbereich
    record:
      enabled: true
      retain:
        days: 3
        #mode: motion wenn spaeter mal auch die Katzen erkannt werden, dann ist hier motion meine Wahl
        mode: all
      events:
        retain:
          default: 7
          #mode: active_objects wenn spaeter mal auch die Katzen erkannt werden, dann ist active_objects meine Wahl
          mode: motion
        pre_capture: 10
        post_capture: 15
        required_zones:
          - zone_garage_hauptbereich
    zones:
      zone_garage_hauptbereich:
        coordinates: 0,632,1280,635,1280,362,1047,186,523,220,137,240,0,300
    motion:
      mask:
        - 0,0,0,254,442,223,401,0

  Tuer-2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:123456789@192.168.1.214:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:123456789@192.168.1.214:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: false
    detect:
      width: 1280
      height: 720
      fps: 10
      max_disappeared: 50
    objects:
      track:
        - person
        - cat
      #filters:
        #person:
          #min_area: 16000
          #max_area: 80000
          #min_score: 0.5
          #threshold: 0.7
          #mask:
            #- 137,81,354,720,0,720,0,81
        #cat:
          #min_area: 2500
          #max_area: 15000
          #min_score: 0.5
          #threshold: 0.5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 3
      required_zones:
        - zone_tuer_hauptbereich
    record:
      enabled: true
      retain:
        days: 3
        #mode: motion wenn spaeter mal auch die Katzen erkannt werden, dann ist hier motion meine Wahl
        mode: all
      events:
        retain:
          default: 7
          #mode: active_objects wenn spaeter mal auch die Katzen erkannt werden, dann ist active_objects meine Wahl
          mode: motion
        pre_capture: 10
        post_capture: 15
        required_zones:
          - zone_tuer_hauptbereich
    zones:
      zone_tuer_hauptbereich:
        coordinates: 342,720,1280,720,1280,67,137,68
    motion:
      mask:
        #- 0,270,445,180,407,0,0,0
        - 1280,258,1280,0,1214,0

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  #enabled: True
  enabled: false
  # Optional: Width of the output resolution (default: shown below)
  #width: 1280
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  #height: 720
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
```

### Relevant log output

```shell
{"before":{"id":"1660652197.845441-lfta84","camera":"Tuer-2","frame_time":1660652197.845441,"snapshot_time":0,"label":"person","top_score":0,"false_positive":true,"start_time":1660652197.845441,"end_time":null,"score":0.55859375,"box":[504,79,594,208],"area":11610,"ratio":0.6976744186046512,"region":[0,0,1132,1132],"stationary":false,"motionless_count":0,"position_changes":0,"current_zones":[],"entered_zones":[],"has_clip":false,"has_snapshot":false},"after":{"id":"1660652197.845441-lfta84","camera":"Tuer-2","frame_time":1660652217.319186,"snapshot_time":1660652217.319186,"label":"person","top_score":0.71484375,"false_positive":false,"start_time":1660652197.845441,"end_time":null,"score":0.71484375,"box":[525,81,597,210],"area":9288,"ratio":0.5581395348837209,"region":[0,0,1148,1148],"stationary":true,"motionless_count":156,"position_changes":1,"current_zones":["zone_tuer_hauptbereich"],"entered_zones":["zone_tuer_hauptbereich"],"has_clip":true,"has_snapshot":true},"type":"new"}
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink, RLC-511WA
