### ISSUE TITLE
What does this message mean?: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3663]
### Describe the problem you are having

On a particular camera I am seeing the following when trying to play back a clip.
<img width="844" alt="Screenshot 2022-08-17 at 08 46 47" src="https://user-images.githubusercontent.com/42817627/185063967-427f256c-38f8-44ff-91bd-fd331880da71.png">

Other cameras are from the same time OK.

Please can you point me in the right direction?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
greenhouse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.55:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.55:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        cat:
          threshold: 0.6
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
        person:
          threshold: 0.6
          min_score: 0.6
          mask:
            - 94,314,64,323,67,273,88,269
    motion:
      mask:
        - 0,195,704,198,704,0,0,0,0,0
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
I get command not found.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW5442E-ZE
