### ISSUE TITLE
[Support]: Issues and queries

### ISSUE THREAD

**Issue by aidbish** [blakeblackshear/frigate#3669]
### Describe the problem you are having

1. When selecting download clip from an event it always shows an empty clip.htm with the error 
![image](https://user-images.githubusercontent.com/38182386/185369603-f1fb2f7a-f72b-4b65-8247-7057cef63d9e.png)

Downloading snapshots works fine. i can view recordings via the recordings tab of each camera just fine

2. When viewing a clip directly from the recording folder it has a weird like message "media server " or "session streamed by preview" that is visible for the first few seconds of the recording. i have checked the cameras in case it was an overlay from them, but there is nothing

![image](https://user-images.githubusercontent.com/38182386/185370180-5c3ed547-ed56-41fa-a474-8e24d3d76c50.png)

3. How do i integrate timestamps into the recording so that if i need to export it will show the details. 

thanks

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.18
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
detectors:
  coral:
    type: edgetpu
    device: usb
    
cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.3:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    rtmp:
      enabled: true        
    detect:
      width: 704
      height: 568
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
        
  buddah_garden:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    rtmp:
      enabled: true        
    detect:
      width: 704
      height: 568
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
        
  side_garden:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.5:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.5:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    rtmp:
      enabled: true        
    detect:
      width: 704
      height: 568
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
       
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.6:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.6:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    rtmp:
      enabled: true        
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
        
  back_gate:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.7:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.7:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
    rtmp:
      enabled: true        
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
      

  garage:
    ffmpeg:
      hwaccel_args: []
 #     input_args:
  #      - -avoid_negative_ts
  #      - make_zero
  #      - -fflags
  #      - nobuffer+genpts+discardcorrupt
   #     - -flags
    #    - low_delay
    #    - -strict
    #    - experimental
     #   - -analyzeduration
     #   - 1000M
     #   - -probesize
     #   - 1000M
     #   - -rw_timeout
     #   - "5000000"
      inputs:
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.9:554/h264Preview_01_main
          roles:
            - record
            - rtmp
        - path: rtsp://XXXXXXX:XXXXXXX@10.0.60.9:554/h264Preview_01_sub
          roles:
            - detect
    rtmp:
      enabled: false        
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
```

### Relevant log output

```shell
[2022-08-18 13:00:48] watchdog.front_door            INFO    : Terminating the existing ffmpeg process...
[2022-08-18 13:00:48] watchdog.front_door            INFO    : Waiting for ffmpeg to exit gracefully...
[2022-08-18 19:26:33] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:53722]
[2022-08-18 19:26:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44600]
[2022-08-18 19:28:15] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:53722]
[2022-08-18 19:33:55] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44600]
[2022-08-18 19:33:55] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:53724]
[2022-08-18 19:33:55] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44602]
[2022-08-18 19:34:03] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44602]
[2022-08-18 19:35:15] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:53724]
[2022-08-18 19:35:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44604]
[2022-08-18 19:38:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44604]
[2022-08-18 20:18:12] frigate.video                  ERROR   : front_door: Unable to read frames from ffmpeg process.
[2022-08-18 20:18:12] frigate.video                  ERROR   : front_door: ffmpeg process is not running. exiting capture thread...
[cont-finish.d] executing container finish scripts...
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
10.0.60.4: No such file or directory
```

### Frigate stats

```json
{"back_gate":{"camera_fps":5.1,"capture_pid":247,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"buddah_garden":{"camera_fps":5.1,"capture_pid":237,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.24,"pid":217}},"front_door":{"camera_fps":5.1,"capture_pid":244,"detection_fps":0.0,"pid":231,"process_fps":5.1,"skipped_fps":0.0},"garage":{"camera_fps":5.1,"capture_pid":249,"detection_fps":0.2,"pid":235,"process_fps":5.0,"skipped_fps":0.0},"patio":{"camera_fps":5.0,"capture_pid":236,"detection_fps":0.0,"pid":224,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":260.8,"mount_type":"tmpfs","total":268.4,"used":7.6},"/media/frigate/clips":{"free":550416.7,"mount_type":"xfs","total":999715.5,"used":449298.8},"/media/frigate/recordings":{"free":550416.7,"mount_type":"xfs","total":999715.5,"used":449298.8},"/tmp/cache":{"free":979.3,"mount_type":"tmpfs","total":1000.0,"used":20.7}},"temperatures":{},"uptime":146,"version":"0.10.1-83481af"},"side_garden":{"camera_fps":5.0,"capture_pid":242,"detection_fps":0.0,"pid":230,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
> 1. When selecting download clip from an event it always shows an empty clip.htm with the error

You don't have `required_zones` set for `snapshots` but you do for `record -> events`. Odds are the object is not actually getting in the zone so the recordings are not being attached to the event.

> 2. When viewing a clip directly from the recording folder it has a weird like message "media server " or "session streamed by preview" that is visible for the first few seconds of the recording. i have checked the cameras in case it was an overlay from them, but there is nothing

VLC shows this popup when starting watching a file / stream

> 3. How do i integrate timestamps into the recording so that if i need to export it will show the details.

https://docs.frigate.video/configuration/index

```yaml
# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: None
```
