### ISSUE TITLE
[Config Support]: hwaccel_args for Intel NUC

### ISSUE THREAD

**Issue by Jonnehs** [blakeblackshear/frigate#3681]
### Describe the problem you are having

Hello,

I'm unsure how to find out what hwaccel_args I might use for the built in integrated GFX etc. Is it just the Intel gen10 plus stuff from the docs below, or are there other things to take advantage of onboard GFX?

Intel-based CPUs (>=10th Generation) via Quicksync[#](https://docs.frigate.video/configuration/hardware_acceleration#intel-based-cpus-10th-generation-via-quicksync-1)
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.25.1.15
  user: <user>
  password: <pass>

cameras:
  Front:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@10.25.101.102:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<pass>@10.25.101.102:554//h264Preview_01_main
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
  Garage:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@10.25.101.103:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<pass>@10.25.101.103:554//h264Preview_01_main
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
  Driveway:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:<pass>@10.25.101.101:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<pass>@10.25.101.101:554//h264Preview_01_main
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
