### ISSUE TITLE
[Config Support]: Capturing a stream from motion (motioneye)

### ISSUE THREAD

**Issue by Hoerli1337** [blakeblackshear/frigate#3682]
### Describe the problem you are having

I have already installed motioneye.
Now I have installed frigate as docker.
Unfortunately, I can't get it to include the HTTP stream.
I also can't manage to include the USB camera directly in frigate.

### Version

Frigate (0.10.1-83481af)

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.110
  user: blaaaaaaaaah
  password: blaaaaaaaaaaaah
  topic_prefix: frigate
  
cameras:
  back:
    ffmpeg:
      inputs:
        - path: http://192.168.178.200:8091
          roles:
            - detect
            - http
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
frigate  | [2022-08-20 18:28:35] ffmpeg.back.detect             ERROR   : Option stimeout not found.
frigate  | [2022-08-20 18:28:36] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
frigate  | [2022-08-20 18:28:36] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I have a Microsoft LifeCam Cinema as webcam.
I running it on a Pine ROCK64 with 4GB RAM.

**Comment by NickM-27** [comment]
Check out the docs, the default input args won't work for http camera

You didn't include ffprobe output for the stream so I'm unsure what type of screen is, but here's one to try by default:

https://docs.frigate.video/configuration/camera_specific#blue-iris-rtsp-cameras

**Comment by Hoerli1337** [comment]
The documentation for this is unfortunately not informative enough.
I have read it, but the examples are so far only valid for rtsp-cameras.
For HTTP streams I've only seen some examples on the internet - mostly in YouTube videos.
Supposedly this should work, but I can't get it to work.
I tried it with various flags, but that seems to have absolutely no effect.

To test the general function, I installed an RTSP server app on my smartphone.
So far it has worked.
Unfortunately, no app allows to turn off the screen to abuse an old smartphone as a surveillance camera.

If an http stream is absolutely not supported, Frigate is currently probably not a solution for me.

**Comment by NickM-27** [comment]
Frigate usss ffmpeg to capture streams, ffmpeg of course supports http streams so http streams are supported. I also use http stream from a camera in my setup and it works as expected. 

Like I said, you have provided no information on what type of http stream is being supplied (jsmpeg, mjpeg, h264, etc) so it's difficult to suggest anything.

**Comment by NickM-27** [comment]
Also, did you try the input args that I linked? What were the logs for that?

**Comment by Hoerli1337** [comment]
It is a MJPEG-Stream.

I try the args, but did not work.
```
frigate  | [2022-08-21 18:42:16] ffmpeg.hinten.detect           ERROR   : Error splitting the argument list: Option not found
frigate  | [2022-08-21 18:42:16] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
frigate  | [2022-08-21 18:42:16] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
```

**Comment by NickM-27** [comment]
> It is a MJPEG-Stream.
> 
> I try the args, but did not work.
> ```
> frigate  | [2022-08-21 18:42:16] ffmpeg.hinten.detect           ERROR   : Error splitting the argument list: Option not found
> frigate  | [2022-08-21 18:42:16] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
> frigate  | [2022-08-21 18:42:16] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
> ```

Okay, then you'll need to use the specific args for mjpeg streams 

https://docs.frigate.video/configuration/camera_specific#mjpeg-cameras

If it doesn't work then please include your logs and updated config

**Comment by frakman1** [comment]
For what it's worth, I am running motion eye on a Raspberry Pi and was able to get the http stream to work 

```yaml
cameras:
  picam:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://xxxxx
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
```

Hope that helps someone!
