### ISSUE TITLE
[Support]: Camera recordings playback incorrect starting time

### ISSUE THREAD

**Issue by notgood** [blakeblackshear/frigate#3699]
### Describe the problem you are having

Steps to reproduce:
1) Go to Frigate web UI, open recordings for your camera, i.e. URL /recording/mycamera
2) Frigate displays last recorded frame of the first hour of the current day. For example my today recorded videos start at 05:24, yet going to recordings displays 05:57:59 still frame.
3) Hitting play starts the playback of the NEXT hour videos, in my case starting from 06:xx:xx

The way it is probably supposed to work: going to recordings should display first frame of the first video recorded today, hitting play should start playing from the first second.

### Version

0.11.0-rc1

### Frigate config file

```yaml
doesn't matter
```

### Relevant log output

```shell
doesn't matter
```

### FFprobe output from your camera

```shell
doesn't matter
```

### Frigate stats

```json
doesn't matter
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
Can you include your docker-compose file? I'm not seeing this behavior when trying.

**Comment by notgood** [comment]
docker-compose.yml

```
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    hostname: myhostname
    network_mode: host
    restart: unless-stopped
    volumes:
      - /docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.11.0-rc1
    hostname: myhostname
    network_mode: host
    restart: unless-stopped
    privileged: true
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/frigate.yml:/config/config.yml:ro
      - /docker/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

```

frigate.yml
```
mqtt:
  host: localhost
cameras:
  mycamera:
    ffmpeg:
      inputs:
        - path: rtsp://mycamera:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://mycamera:554/Streaming/Channels/101/
          roles:
            - record
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: True
      events:
        retain:
          default: 30
          mode: active_objects
    motion:
      mask:
        - 25,29,213,30,211,17,31,18
        - 0,0,62,0,65,33,52,59,32,104,61,117,90,158,78,191,0,191
        - 513,56,487,75,498,95,502,114,465,115,425,138,467,163,540,133,558,85,560,28,517,24
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        car:
          mask:
            - 0,77,101,61,137,72,140,97,105,136,0,144
snapshots:
  enabled: False
birdseye:
  enabled: False
rtmp:
  enabled: False
detectors:
  coral:
    type: edgetpu
    device: usb

```
