### ISSUE TITLE
[Support]: Many clips that are captured won't play

### ISSUE THREAD

**Issue by clearwave1** [blakeblackshear/frigate#3701]
### Describe the problem you are having

I have just started using Frigate over the last few days and I really like it. I only have one camera at the moment and I am recording 24/7 and keeping those recordings for 10 days. This is working fine. My detection is working fine but some of the clips it captures will not play. What happens is that the player will just show a spinning busy circle and not play anything. When I go into the full recording, I can play from before the time of the clip to well after it with the contents displaying fine.

The logs below are clean. They were taken after a restart and then a few attempts to play clips that won't play.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.149
  user: mqtt
  password: camsim1123

cameras:
  front_db:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 
        rtmp: -c copy -f flv -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:YWEGYP@192.168.1.223:554/1
          roles:
          - record
          - rtmp
#          - detect
        - path: rtsp://admin:YWEGYP@192.168.1.223:554/2
          roles:
          - detect
    detect:
      enabled: true
      width: 352
      height: 240
      fps: 5
    rtmp:
      enabled:  true
    record:
      enabled: true
      retain:
        days: 10


snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 30
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-08-23 11:33:06] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-08-23 11:33:06] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-08-23 11:33:06] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-08-23 11:33:07] peewee_migrate                 INFO    : There is nothing to migrate
[2022-08-23 11:33:07] frigate.app                    INFO    : Output process started: 218
[2022-08-23 11:33:07] detector.cpu                   INFO    : Starting detection process: 217
[2022-08-23 11:33:07] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-08-23 11:33:07] frigate.app                    INFO    : Camera processor started for front_db: 221
[2022-08-23 11:33:07] frigate.app                    INFO    : Capture process started for front_db: 223
[2022-08-23 11:33:07] ws4py                          INFO    : Using epoll
[2022-08-23 11:33:07] ws4py                          INFO    : Using epoll
```

### FFprobe output from your camera

```shell
C:\>ffprobe -rtsp_transport tcp -i rtsp://admin:YWEGYP@192.168.1.223:554/1 -select_streams v:0 -show_frames -show_entries frame=coded_picture_number,pkt_pts_time -of csv=p=0
ffprobe version 4.4.1-full_build-www.gyan.dev Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0000017d6207f5c0] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://admin:YWEGYP@192.168.1.223:554/1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 960x1280, 10 fps, 10 tbr, 90k tbn, 20 tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
0.600000,0
0.100000,1
0.200000,2
0.300000,3
0.400000,4
0.500000,5
0.600000,6
0.700000,7
0.800000,8
0.900000,9
1.000000,10
1.100000,11
1.200000,12
1.300000,13
1.400000,14
1.500000,15
1.600000,16
1.700000,17
1.800000,18
1.900000,19
2.000000,20
2.100000,21
2.200000,22
2.300000,23
2.400000,24
2.500000,25
2.600000,26
2.700000,27
2.800000,28
2.900000,29
3.000000,30
3.100000,31
3.200000,32
3.300000,33
3.400000,34
3.500000,35
3.600000,36
3.700000,37
3.800000,38
3.900000,39
4.000000,40
4.100000,41
4.200000,42
4.300000,43
4.400000,44
4.500000,45
4.600000,46
4.700000,47
4.800000,48
4.900000,49
5.000000,50
5.100000,51
5.200000,52
5.300000,53
5.400000,54
5.500000,55
5.600000,56
5.700000,57
5.800000,58
5.900000,59
6.000000,60
6.100000,61
6.200000,62
6.300000,63
6.400000,64
6.500000,65
6.600000,66
6.700000,67
6.800000,68
6.900000,69
7.000000,70
7.100000,71
7.200000,72
7.300000,73
7.400000,74
7.500000,75
7.600000,76
7.700000,77
7.800000,78
7.900000,79
8.000000,80
8.100000,81
8.200000,82
8.300000,83
8.400000,84
8.500000,85
8.600000,86
8.700000,87
8.800000,88
8.900000,89
9.000000,90
9.100000,91
9.200000,92
9.300000,93
9.400000,94
9.500000,95
9.600000,96
9.700000,97
9.800000,98
9.900000,99
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

EZVIZ DB1 Pro
