### ISSUE TITLE
[Support]: Recordings of Events are unplayable in Browser

### ISSUE THREAD

**Issue by maginator** [blakeblackshear/frigate#3706]
### Describe the problem you are having

Hi, 
my problem is that smoe recorded events are not playable in the Browser. I use Opera as browser but Opera is just based on Chromium. These Clips i can  download normaly and then play them so the Media Files exists. But i got the Message : "The media could not be loaded, either because the server or network failed or because the format is not supported." With other Recorded Events its working and i can play them in a Browser. and at a third i have some events with only snapshots and no recordings beeing saved. 
Does anyone know why this happend?

### Version

0.11.0-37325C7

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: broker.fritz.box
  port: 1883
  topic_prefix: frigate

cameras:
  vorne:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: http://raspicam3.fritz.box/html/cam_pic_new.php?
          roles:
            - record
            - detect
      output_args:
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -r 10
        #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -preset veryfast -r 10
        detect: -f rawvideo -pix_fmt yuv420p
        rtmp: -c:v libx264 -an -f flv
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
      - person
      filters:
        person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6

detectors:
  cpu1:
    type: cpu
    num_threads: 2

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

logger:
  default: info
  logs:
    frigate.mqtt: error
    frigate.app: debug
    frigate.zeroconf: info

record:
  enabled: true
  expire_interval: 60
  retain:
    days: 0
    mode: active_objects
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    #max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 20
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 15



snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  height: 720
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

motion:
  threshold: 20
  mask:
    - 981,0,977,74,536,76,534,0
```

### Relevant log output

```shell
[2022-08-24 12:11:57] frigate.http ERROR : No recordings found for the requested time range
```

### FFprobe output from your camera

```shell
Input #0, mpjpeg, from 'http://raspicam3.fritz.box/html/cam_pic_new.php?':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 512x288, 25 tbr, 25 tbn
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":103.27,"pid":217}},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":65.1,"mount_type":"tmpfs","total":67.1,"used":2.0},"/media/frigate/clips":{"free":8079.3,"mount_type":"overlay","total":41082.7,"used":30890.4},"/media/frigate/recordings":{"free":8079.3,"mount_type":"overlay","total":41082.7,"used":30890.4},"/tmp/cache":{"free":996.5,"mount_type":"tmpfs","total":1000.0,"used":3.5}},"temperatures":{},"uptime":54032,"version":"0.11.0-37325c7"},"vorne":{"camera_fps":5.0,"capture_pid":224,"detection_fps":0.0,"pid":222,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

mjpeg Rasperry Pi Cam
