### ISSUE TITLE
[Config Support]: Timestamp configuration not taking effect

### ISSUE THREAD

**Issue by lordratner** [blakeblackshear/frigate#3729]
### Describe the problem you are having

I've added the Timestamp_style as both a global argument and a camera specific arg, but in both cases the timestamp does not show up at all

When I go into Debug and turn on the timestamp toggle, the format from the config (%Y/%m/%d) is not showing, and instead the default shows. Default color instead of my config color as well. 

I looked at the config from Debug, and it's not showing my timestamp_style entries, just the defaults

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.xx.xx
  port: 1883
  user: xxx
  password: xxx

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - cat
    required_zones:
    - feeder
    retain:
      default: 5
      mode: all
timestamp_style:
  position: "tl"
  format: "%Y/%m/%d %H:%M:%S"
  color:
    red: 0
    green: 255
    blue: 255
  thickness: 2
  effect: None
cameras:
  living:
    ffmpeg:
      inputs:
        - path: rtsp://xx:xx@192.168.xxx.xxx:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp

    timestamp_style:
      position: "tl"
      format: "%Y/%m/%d %H:%M:%S"
      color:
        red: 255
        green: 0
        blue: 255
      thickness: 2
      effect: "shadow"

    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    zones:
      feeder:
        coordinates: 641,346,654,480,586,576,427,615,394,392
        objects:
          - cat
    snapshots:
      required_zones:
        - feeder
    record:
      enabled: True
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
objects:
  track:
#    - car
    - cat
  filters:
    cat:
      min_score: 0.5
      threshold: 0.7
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  required_zones:
    - feeder
  retain:
    default: 7
database:
  path: /config/frigate.db
detect:
  fps: 5
  enabled: True
  stationary:
    interval: 50
    threshold: 50
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

### Relevant log output

```shell
nothing I could find
```

### Frigate stats

```json
{"detection_fps":4.2,"detectors":{"cpu1":{"detection_start":1661739543.414247,"inference_speed":185.69,"pid":214},"cpu2":{"detection_start":0.0,"inference_speed":200.64,"pid":215}},"living":{"camera_fps":5.0,"capture_pid":220,"detection_fps":4.2,"pid":219,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":130.8,"mount_type":"tmpfs","total":134.2,"used":3.4},"/media/frigate/clips":{"free":1639963.0,"mount_type":"cifs","total":1639964.9,"used":1.8},"/media/frigate/recordings":{"free":1639963.0,"mount_type":"cifs","total":1639964.9,"used":1.8},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":3536,"version":"0.10.1-83481af"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Have you restarted to apply the new config?

The config you pasted above is invalid, `effect: None` is not a valid option and throws a config error. Once I removed that, starting frigate up and the timestamp style works as expected

<img width="402" alt="Screen Shot 2022-08-29 at 7 05 43 AM" src="https://user-images.githubusercontent.com/14866235/187208140-e599ebc1-1e2c-4c77-b38f-71a58e6dd38b.png">

**Comment by lordratner** [comment]
> Have you restarted to apply the new config?
> 
> The config you pasted above is invalid, `effect: None` is not a valid option and throws a config error. Once I removed that, starting frigate up and the timestamp style works as expected
> 
> 

Any chance you could share your config?

When you say "restart frigate" do you mean the container, or just through the upper left menu option in the webGUI?

**Comment by NickM-27** [comment]
> Any chance you could share your config?

This is my test config I threw together to test this:

```yaml
mqtt:
  host: mqtt

timestamp_style:
  position: "tl"
  format: "%Y/%m/%d %H:%M:%S"
  color:
    red: 0
    green: 255
    blue: 255
  thickness: 2

cameras:

  garage_cam:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@ipaddress/garage_cam
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        retain:
          default: 2
          mode: all
```

> When you say "restart frigate" do you mean the container, or just through the upper left menu option in the webGUI?

I think the web UI should work but I would definitely restart the container in this case to be sure.
