### ISSUE TITLE
Home Assistant automation examples does not validate (0.8.0)

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#373]
**Describe the bug**
None of the fantastic examples [here](https://github.com/blakeblackshear/frigate/blob/release-0.8.0/docs/notification-examples.md) works or can be validated in home assistant.
All three examples does not validate, the example in readme.md works, there is something wrong with the condition templates.

I cannot with my limited templating skills figure out whats wrong :/

**Version of frigate**
0.8.0 Beta 1

![image](https://user-images.githubusercontent.com/26795429/101988778-2f3ca380-3c9c-11eb-8a09-ba4cf0acdffd.png)
![image](https://user-images.githubusercontent.com/26795429/101988834-9195a400-3c9c-11eb-85c4-2d2367af0b21.png)

**Comment by blakeblackshear** [comment]
I havent had a chance to fix it yet. It is a single/double quote issue. They should be like this:
# Notification examples

```yaml
automation:

  - alias: When a person enters a zone named yard
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - "{{ 'yard' in trigger.payload_json['after']['entered_zones'] }}"
    action:
      - service: notify.mobile_app_pixel_3
        data_template:
          message: "A {{trigger.payload_json['after']['label']}} has entered the yard."
          data:
            image: "https://url.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}.jpg"
            tag: "{{trigger.payload_json['after']['id']}}"

  - alias: When a person leaves a zone named yard
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - "{{ 'yard' in trigger.payload_json['before']['current_zones'] }}"
      - "{{ not 'yard' in trigger.payload_json['after']['current_zones'] }}"
    action:
      - service: notify.mobile_app_pixel_3
        data_template:
          message: "A {{trigger.payload_json['after']['label']}} has left the yard."
          data:
            image: "https://url.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}.jpg"
            tag: "{{trigger.payload_json['after']['id']}}"

  - alias: Notify for dogs in the front with a high top score
    trigger:
      platform: mqtt
      topic: frigate/events
    conditions: 
      - "{{ trigger.payload_json['after']['label'] == 'dog' }}"
      - "{{ trigger.payload_json['after']['camera'] == 'front' }}"
      - "{{ trigger.payload_json['after']['top_score'] > 0.98 }}"
    action:
      - service: notify.mobile_app_pixel_3
        data_template:
          message: 'High confidence dog detection.'
          data:
            image: "https://url.com/api/frigate/notifications/{{trigger.payload_json['after']['id']}}.jpg"
            tag: "{{trigger.payload_json['after']['id']}}"
```
