### ISSUE TITLE
[Support]: FFmpeg on 0.11.0-RC2 crashes: Timestamps are unset in a packet

### ISSUE THREAD

**Issue by elgorro** [blakeblackshear/frigate#3735]
### Describe the problem you are having

Something crashes the logs say - I've no idea how to reproduce... 

### Version

0.11.0-RC2

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.27
  user: admin
  password: pa$$
  stats_interval: 60
birdseye:
  enabled: False
cameras:
  hof:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pa$$@192.168.178.20:554/Streaming/Channels/101
          roles:
            - detect
            - record
detect:
  width: 1920
  height: 1080
  fps: 10
  max_disappeared: 50
  stationary:
    interval: 0
    threshold: 64
objects:
  track:
    - person
    - car
  mask: 0,0,577,0,1063,0,360,241,0,619
  filters:
    person:
      min_area: 400
      max_area: 100000
      mask: 928,227,993,211,965,97,892,112
    car:
      min_area: 2500
      max_area: 500000
      mask: 1920,0,1920,154,1608,122,1370,0
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 1
      mode: motion
      objects:
        person: 3
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 3
rtmp:
  enabled: False
motion:
  threshold: 20
logger:
  default: info
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
frigate  | [2022-08-30 11:05:58] frigate.video                  ERROR   : hof: Unable to read frames from ffmpeg process.
frigate  | [2022-08-30 11:05:58] frigate.video                  ERROR   : hof: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-08-30 11:06:01] watchdog.hof                   ERROR   : Ffmpeg process crashed unexpectedly for hof.
frigate  | [2022-08-30 11:06:01] watchdog.hof                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-08-30 11:06:01] ffmpeg.hof.detect              ERROR   : [segment @ 0x55b2db65a0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | [2022-08-30 11:06:01] ffmpeg.hof.detect              ERROR   : [segment @ 0x55b2db65a0] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frigate  | [2022-08-30 11:06:01] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55b2db20c0] Undefined type (31)


frigate  | [2022-08-30 11:47:37] frigate.video                  ERROR   : hof: Unable to read frames from ffmpeg process.
frigate  | [2022-08-30 11:47:37] frigate.video                  ERROR   : hof: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-08-30 11:47:41] watchdog.hof                   ERROR   : Ffmpeg process crashed unexpectedly for hof.
frigate  | [2022-08-30 11:47:41] watchdog.hof                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-08-30 11:47:41] ffmpeg.hof.detect              ERROR   : [segment @ 0x557b0345a0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
frigate  | [2022-08-30 11:47:41] ffmpeg.hof.detect              ERROR   : [segment @ 0x557b0345a0] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frigate  | [2022-08-30 11:47:41] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x557b0300c0] RTP H.264 NAL unit type 27 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
frigate  | [2022-08-30 11:47:41] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x557b0300c0] RTP H.264 NAL unit type 25 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
frigate  | [2022-08-30 11:47:41] ffmpeg.hof.detect              ERROR   : [NULL @ 0x557b035d80] missing picture in access unit with size 2864
frigate  | [2022-08-30 11:47:41] ffmpeg.hof.detect              ERROR   : [segment @ 0x557b0345a0] Non-monotonous DTS in output stream 0:0; previous: 25537271, current: 25537271; changing to 25537272. This may result in incorrect timestamps in the output file.
```

### FFprobe output from your camera

```shell
ffprobe version n5.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.1 (GCC) 20220730
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin:pa$$@192.168.178.20:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.100000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 10 fps, 10 tbr, 90k tbn
```

### Frigate stats

```json
{"detection_fps":16.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":21.53,"pid":215}},"hof":{"camera_fps":10.0,"capture_pid":226,"detection_fps":16.2,"pid":222,"process_fps":9.7,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":59.1,"mount_type":"tmpfs","total":67.1,"used":8.0},"/media/frigate/clips":{"free":143678.1,"mount_type":"ext4","total":246439.0,"used":90168.0},"/media/frigate/recordings":{"free":143678.1,"mount_type":"ext4","total":246439.0,"used":90168.0},"/tmp/cache":{"free":984.3,"mount_type":"tmpfs","total":1000.0,"used":15.7}},"temperatures":{},"uptime":10987,"version":"0.11.0-c461c9e"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

HiLook IPC-D120

### Any other information that may be helpful

Two diffrent stack-traces :/
