### ISSUE TITLE
[Support]: Zone occupancy timeout

### ISSUE THREAD

**Issue by nabahr** [blakeblackshear/frigate#3738]
### Describe the problem you are having

It appears that the occupancy sensor for an object within a specific zone times out immediately (~1s) even though the object is still present, whereas the occupancy sensor for the object in the camera device stays active for the entire expected duration. This is with the default stationary object configuration.

From home assistant logbook after a short test standing still within the zone for about 2 minutes:
```
(Zone) Person Occupancy cleared (no detected)
2:57:37 PM - 17 minutes ago
(Zone) Person Occupancy detected
2:57:36 PM - 17 minutes ago
(Zone) Person Occupancy cleared (no detected)
2:57:28 PM - 17 minutes ago
(Zone) Person Occupancy detected
2:57:27 PM - 17 minutes ago
```

```
(Camera) Person Occupancy cleared (no detected)
2:59:23 PM - 16 minutes ago
(Camera) Person Occupancy detected
2:57:17 PM - 19 minutes ago
```

```
(Camera) Motion cleared (no detected)
2:59:49 PM - 18 minutes ago
(Camera) Motion detected
2:57:16 PM - 20 minutes ago
```

### Version

0.11.0-C461C9E

### Frigate config file

```yaml
detect:
  width: 1920
  height: 1080
  fps: 10
objects:
  track:
    - person
record:
  enabled: True
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: True
  crop: False
  bounding_box: True
  timestamp: False
  height: 1080
  retain:
    default: 31
cameras:
  main_floor:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://XXXXXXX:YYYYYYY@1.2.3.4/xxxx
          roles:
            - detect
            - record
    zones:
      dining_table:
        coordinates: 1224,803,692,801,764,468,1115,464
      kitchen:
        coordinates: 1404,170,1429,0,817,0,815,147
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"backyard_sw":{"camera_fps":9.2,"capture_pid":249,"detection_fps":3.6,"pid":225,"process_fps":8.4,"skipped_fps":0.0},"detection_fps":3.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.25,"pid":216}},"driveway":{"camera_fps":10.0,"capture_pid":260,"detection_fps":0.0,"pid":229,"process_fps":10.0,"skipped_fps":0.0},"family_room":{"camera_fps":10.1,"capture_pid":252,"detection_fps":0.0,"pid":227,"process_fps":10.1,"skipped_fps":0.0},"front_door":{"camera_fps":10.0,"capture_pid":245,"detection_fps":0.0,"pid":221,"process_fps":10.0,"skipped_fps":0.0},"garage":{"camera_fps":10.1,"capture_pid":264,"detection_fps":0.0,"pid":242,"process_fps":10.1,"skipped_fps":0.0},"main_floor":{"camera_fps":10.1,"capture_pid":248,"detection_fps":0.0,"pid":222,"process_fps":10.1,"skipped_fps":0.0},"malcolms_bedroom":{"camera_fps":10.1,"capture_pid":244,"detection_fps":0.0,"pid":220,"process_fps":10.1,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":504.7,"mount_type":"tmpfs","total":536.9,"used":32.2},"/media/frigate/clips":{"free":1153933.3,"mount_type":"ext4","total":1967925.7,"used":713955.7},"/media/frigate/recordings":{"free":1153933.3,"mount_type":"ext4","total":1967925.7,"used":713955.7},"/tmp/cache":{"free":5091.5,"mount_type":"tmpfs","total":5120.0,"used":28.5}},"temperatures":{"apex_0":48.8},"uptime":95255,"version":"0.11.0-c461c9e"}}
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wireless

### Camera make and model

Wyze V3
