### ISSUE TITLE
[Config Support]: I keep getting a validation error saying that there are missing fields for detect

### ISSUE THREAD

**Issue by Ming-A** [blakeblackshear/frigate#3745]
### Describe the problem you are having

I keep getting the error 
`Error parsing config: 1 validation error for FrigateConfig
cameras -> back -> detect
  field required (type=value_error.missing)`

### Version

0.10.1

### Frigate config file

```yaml
mqtt:
  host: 10.69.40.4
  user: USERNAME
  password: PASSWORD
database:
  path: /media/frigate/database/frigate.db
birdseye:
  enabled: True
  mode: continuous
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog
record:
  enabled: True
  retain:
    days: 28
  events:
    max_seconds: 300
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      days: 10
snapshots:
  enabled: True
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
cameras:
    carport-front:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - rtmp
        record:
          events:
            required_zones:
              - insidecarport
              - outsidecarport
        snapshots:
          required_zones:
            - insidecarport
            - outsidecarport
        zones:
          insidecarport:
            coordinates: 1280,720,1280,446,1224,319,1156,225,1025,139,690,125,0,140,0,720
            objects:
              - person
              - motorcycle
              - cat
              - dog
          outsidecarport:
            coordinates: 1280,0,1280,136,0,129,0,0
            objects:
              - car
              - person
              - motorcycle
              - cat
              - dog

    garden:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - rtmp
        record:
          events:
            required_zones:
              - gardenzone
        snapshots:
          required_zones:
            - gardenzone
        zones:
          gardenzone:
            coordinates: 0,720,1280,720,1280,0,0,0
            objects:
              - person
              - motorcycle
              - cat
              - dog

          
    left:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - rtmp
    right:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - rtmp
        motion:
          mask:
            - 514,191,519,161,781,80,759,0,552,0,188,0,205,80,301,136,331,269
    back:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - rtmp
        motion:
          mask:
            - 1280,402,1280,0,924,0,673,0,973,155,944,161,786,127,660,100,649,174,725,196,708,225,743,234,870,265
    foyer:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/stream1
              roles:
                - detect
                - rtmp
        motion:
          mask:
            - 812,27,1202,117,1212,84,820,0
    kitchen:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/stream1
              roles:
                - detect
                - rtmp

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
cameras -> right -> detect
  field required (type=value_error.missing)
cameras -> back -> detect
  field required (type=value_error.missing)
cameras -> foyer -> detect
  field required (type=value_error.missing)
cameras -> kitchen -> detect
  field required (type=value_error.missing)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Error parsing config: 7 validation errors for FrigateConfig
cameras -> carport-front -> detect
  field required (type=value_error.missing)
cameras -> garden -> detect
  field required (type=value_error.missing)
cameras -> left -> detect
  field required (type=value_error.missing)
cameras -> right -> detect
  field required (type=value_error.missing)
cameras -> back -> detect
  field required (type=value_error.missing)
cameras -> foyer -> detect
  field required (type=value_error.missing)
cameras -> kitchen -> detect
  field required (type=value_error.missing)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Error parsing config: 7 validation errors for FrigateConfig
cameras -> carport-front -> detect
  field required (type=value_error.missing)
cameras -> garden -> detect
  field required (type=value_error.missing)
cameras -> left -> detect
  field required (type=value_error.missing)
cameras -> right -> detect
  field required (type=value_error.missing)
cameras -> back -> detect
  field required (type=value_error.missing)
cameras -> foyer -> detect
  field required (type=value_error.missing)
cameras -> kitchen -> detect
  field required (type=value_error.missing)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Error parsing config: 7 validation errors for FrigateConfig
cameras -> carport-front -> detect
  field required (type=value_error.missing)
cameras -> garden -> detect
  field required (type=value_error.missing)
cameras -> left -> detect
  field required (type=value_error.missing)
cameras -> right -> detect
  field required (type=value_error.missing)
cameras -> back -> detect
  field required (type=value_error.missing)
cameras -> foyer -> detect
  field required (type=value_error.missing)
cameras -> kitchen -> detect
  field required (type=value_error.missing)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
your config under `cameras` is indented too much. also there are other spacing errors. Please be aware that YAML is indent dependent based on indents of 2 spaces. It must be consistent and correct.

```yaml
cameras:
    carport-front:
        ffmpeg:
          inputs:
            - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
              roles:
                - detect
                - rtmp
        record:
          events:
            required_zones:
              - insidecarport
              - outsidecarport
        snapshots:
          required_zones:
            - insidecarport
            - outsidecarport
        zones:
          insidecarport:
            coordinates: 1280,720,1280,446,1224,319,1156,225,1025,139,690,125,0,140,0,720
            objects:
              - person
              - motorcycle
              - cat
              - dog
          outsidecarport:
            coordinates: 1280,0,1280,136,0,129,0,0
            objects:
              - car
              - person
              - motorcycle
              - cat
              - dog
```

should be 

```yaml
cameras:
  carport-front:
    ffmpeg:
      inputs:
        - path: rtsp://USERNAME:PASS@IP:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
          roles:
            - detect
            - rtmp
    record:
      events:
        required_zones:
          - insidecarport
          - outsidecarport
    snapshots:
      required_zones:
        - insidecarport
        - outsidecarport
    zones:
      insidecarport:
        coordinates: 1280,720,1280,446,1224,319,1156,225,1025,139,690,125,0,140,0,720
        objects:
          - person
          - motorcycle
          - cat
          - dog
      outsidecarport:
        coordinates: 1280,0,1280,136,0,129,0,0
        objects:
          - car
          - person
          - motorcycle
          - cat
          - dog
```

same for other cameras as well
