### ISSUE TITLE
[Support]: API images not working - returning a black box only

### ISSUE THREAD

**Issue by Trashmee** [blakeblackshear/frigate#3748]
### Describe the problem you are having

Hi,

Frigate is working as expected & pretty stable during the last couple of month, excellent piece of software.

When trying to access the latest person jpeg via API today I found that none of the following return a valid jpeg.

```
https://frigate.abc.de/api/eingang/person/best.jpg
https://frigate.abc.de/api/eingang/person/snapshot.jpg
https://frigate.abc.de/api/eingang/person/thumbnail.jpg
```

Its the same for multiple cameras from different vendors. All cameras show up perfect in the WebUI.
This is the URL that works fine & has thumbnails as well as recordings. Just mentoining to ensure the above URLs are valid.
```
https://frigate.abc.de/events?camera=eingang&label=person
```

This one might be outdated I understood from other issues - it returns a 'not found'. The first three URLs return an 'all black' jpeg in comparision.
```
https://frigate.abc.de/api/eingang/person/latest.jpg
```

Any advice on how to investigate is appreciated

ItsMee

### Version

0.11.0-rc2

### Frigate config file

```yaml
mqtt:
  host: 
  [..]

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/database/frigate.db

birdseye:
  enabled: True
  width: 1900
  height: 1080
  quality: 8
  mode: continuous

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

motion:
  threshold: 25
  contour_area: 33
  frame_alpha: 0.2
  frame_height: 50

objects:
  track:
    - person
    - cat
  filters:
    cat:
      threshold: 0.5
    person:
      min_area: 1000

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
    required_zones: []
    retain:
      default: 11
      mode: active_objects
      objects:
        person: 16

rtmp:
  enabled: True

live:
  height: 720
  quality: 8


cameras:

  eingang:  #  IPC-HDW2831T-ZS-S2
    ffmpeg:
      inputs:
        - path: rtsp://frigate:pass@camera/cam/realmonitor?channel=1&subtype=00&authbasic=uu
          roles:
            - record
        - path: rtsp://frigate:pass@camera/cam/realmonitor?channel=1&subtype=01&authbasic=uu
          roles:
            - detect
            - rtmp
      output_args:
        rtmp: -aspect 760:432 -c copy -f flv
        detect: -vf scale=760:432 -f rawvideo -pix_fmt yuv420p
    detect:
      width: 704
      height: 576
#      width: 3840
#      height: 2160
      fps: 5
    motion:
      mask:
        - 412,576,199,393,196,310,336,257,452,263,446,430,704,576,704,0,0,0,0,576
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
# ffprobe  'rtsp://frigate:pass@camera/cam/realmonitor?channel=1&subtype=01&authbasic=uu..'
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://frigate:Set4Frigate@192.168.176.56/cam/realmonitor?channel=1&subtype=01&authbasic=ZnJpZ2F0ZTpTZXQ0RnJpZ2F0ZQ==':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.200000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 704x576, 15 fps, 100 tbr, 90k tbn
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":48.45,"pid":211}},"eingang":{"camera_fps":4.7,"capture_pid":231,"detection_fps":0.0,"pid":223,"process_fps":4.7,"skipped_fps":0.0},"garten":{"camera_fps":4.9,"capture_pid":226,"detection_fps":0.0,"pid":219,"process_fps":4.9,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":4287.2,"mount_type":"tmpfs","total":4295.0,"used":7.7},"/media/frigate/clips":{"free":255979.7,"mount_type":"nfs","total":3936819.7,"used":3480783.8},"/media/frigate/recordings":{"free":255987.5,"mount_type":"nfs","total":3936819.7,"used":3480776.1},"/tmp/cache":{"free":3950.9,"mount_type":"tmpfs","total":4000.0,"used":49.1}},"temperatures":{},"uptime":12470,"version":"0.11.0-c461c9e"},"terasse":{"camera_fps":5.0,"capture_pid":227,"detection_fps":0.0,"pid":221,"process_fps":5.0,"skipped_fps":0.0},"vorgarten":{"camera_fps":5.0,"capture_pid":235,"detection_fps":0.0,"pid":225,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HDW2831T-ZS-S2
