### ISSUE TITLE
[Config Support]: FFMPEG not working (crashing) after upgrading packages - no camera feeds - Frigate 0.11 RC2

### ISSUE THREAD

**Issue by healeydave** [blakeblackshear/frigate#3752]
### Describe the problem you are having

I was running Frigate 0.11.0 (Full Access) beta fine for several months.

Today, I updated to Frigate 0.11.0 (Full Access) RC2 and now Frigate won't start, terminating after FFMPEG Issues.

I read the release notes and changed references to stimeout to timeout but its still crashing.

### Version

Frigate 0.11.0 (Full Access) RC2

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
#    num_threads: 3


ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m


mqtt:
  host: 192.168.1.16
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: ********
  stats_interval: 60

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous


record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 4


cameras:
  Driveway_Gate:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:pw@192.168.1.15:554/Streaming/channels/402
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 308,197,313,139,413,142,419,196,447,198,449,143,640,138,640,0,0,0,0,204
    motion:
      mask:
        - 308,197,313,139,413,142,419,196,447,198,449,143,640,138,640,0,0,0,0,204
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3



  Driveway_Bottom:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:pw@192.168.1.15:554/Streaming/channels/202
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
          mask:
            - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
        dog:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
        car:
          min_score: 0.5
          threshold: 0.7
          mask:
            - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
    motion:
      mask:
        - 640,0,640,238,535,167,530,255,497,227,473,134,329,107,232,100,0,126,0,0
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3



  Driveway_Top:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:pw@192.168.1.15:554/Streaming/channels/102
          roles:
            - rtmp
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.65
        dog:
          min_score: 0.5
          threshold: 0.7
        car:
          min_score: 0.5
          threshold: 0.7
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 3
```

### Relevant log output

```shell
ERROR   : [h264_v4l2m2m @ 0x559db406f0] Could not find a valid device
ERROR   : [h264_v4l2m2m @ 0x559db406f0] can't configure decoder
ERROR   : Error while opening decoder for input stream #0:0 : Operation not permitted
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
