### ISSUE TITLE
Recordings not listen in Frontend

### ISSUE THREAD

**Issue by renarena** [blakeblackshear/frigate#3759]
### Describe the problem you are having

On my media folder are recordings i cannot see in frigate events list. Is this supposed to be so? 
Something moves (mirroring in window), but is probably not recognized as object.

### Version

0.10.1-83481af

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
You are going to need to elaborate more on what is happening and what you are expecting to happen. 

You have also not included your config file or any info so it is impossible to help you without more information.

**Comment by renarena** [comment]
Looking through my video folder with a filemanager there are 29 video in recordings/2022-08/31/05/cam2 (it was dark outside and light and someone in the room caused reflections in the window, where the camera sits inside)) which dont appear on the event page if i show all events of this day.
The last one is a car leaving, which is detected on other days, where there are only 2 videos in this hour (same situation in the room).
Its not really important  but i was wondering....
```
...
cameras:
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.xxx:8080/video/h264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False 
   detect:
      width: 960
      height: 720
    motion:
      mask:
        - 243,232,469,179,666,114,666,0,0,0,0,393
    zones: 
      # some zones are defined

objects:
  filters:
    person:
      threshold: 0.75

  track:
    - person
    - cat

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 5

record:
  enabled: True
  events:
    retain:
      default: 5
```
