### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by Jonnehs** [blakeblackshear/frigate#3760]
### Describe the problem you are having

Record config is invalid, I assume my indenting but im not great with yaml so please school

### Version

x

### Frigate config file

```yaml
mqtt:
  host: 10.25.1.15
  user: MQTTUser
  password: <pass>

cameras:
  Front:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: http://10.25.101.102/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<pass>
          roles:
            - detect
        - path: http://10.25.101.102/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<pass>
          roles:
            - rtmp
            - record
    record:
      enabled: True
      retain:
        days: 21
        mode: motion
      events:
        retain:
        default: 21
        mode: active_objects
        objects:
          dog: 10
          cat: 10
          person: 60
          car: 60
    detect:
      width: 640
      height: 480
  Garage:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: http://10.25.101.103/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<pass>
          roles:
            - detect
        - path: http://10.25.101.103/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<pass>
          roles:
            - rtmp
            - record
    record:
      enabled: True
      retain:
        days: 21
        mode: motion
      events:
        retain:
        default: 21
        mode: active_objects
        objects:
          dog: 10
          cat: 10
          person: 60
          car: 60
    detect:
      width: 640
      height: 480
  Driveway:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: http://10.25.101.101/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=<pass>
          roles:
            - detect
        - path: http://10.25.101.101/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=<pass>
          roles:
            - rtmp
            - record
    record:
      enabled: True
      retain:
        days: 21
        mode: motion
      events:
        retain:
        default: 21
        mode: active_objects
        objects:
          dog: 10
          cat: 10
          person: 60
          car: 60
    detect:
      width: 640
      height: 480
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
12 validation errors for FrigateConfig


cameras -> Front -> record -> events -> objects


  value is not a valid list (type=type_error.list)


cameras -> Front -> record -> events -> retain


  none is not an allowed value (type=type_error.none.not_allowed)


cameras -> Front -> record -> events -> default


  extra fields not permitted (type=value_error.extra)


cameras -> Front -> record -> events -> mode


  extra fields not permitted (type=value_error.extra)


cameras -> Garage -> record -> events -> objects


  value is not a valid list (type=type_error.list)


cameras -> Garage -> record -> events -> retain


  none is not an allowed value (type=type_error.none.not_allowed)


cameras -> Garage -> record -> events -> default


  extra fields not permitted (type=value_error.extra)


cameras -> Garage -> record -> events -> mode


  extra fields not permitted (type=value_error.extra)


cameras -> Driveway -> record -> events -> objects


  value is not a valid list (type=type_error.list)


cameras -> Driveway -> record -> events -> retain


  none is not an allowed value (type=type_error.none.not_allowed)


cameras -> Driveway -> record -> events -> default


  extra fields not permitted (type=value_error.extra)


cameras -> Driveway -> record -> events -> mode


  extra fields not permitted (type=value_error.extra)


Traceback (most recent call last):


  File "/opt/frigate/frigate/app.py", line 312, in start


    self.init_config()


  File "/opt/frigate/frigate/app.py", line 77, in init_config


    user_config = FrigateConfig.parse_file(config_file)


  File "/opt/frigate/frigate/config.py", line 904, in parse_file


    return cls.parse_obj(config)


  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj


  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__


pydantic.error_wrappers.ValidationError: 12 validation errors for FrigateConfig


cameras -> Front -> record -> events -> objects


  value is not a valid list (type=type_error.list)


cameras -> Front -> record -> events -> retain


  none is not an allowed value (type=type_error.none.not_allowed)


cameras -> Front -> record -> events -> default


  extra fields not permitted (type=value_error.extra)


cameras -> Front -> record -> events -> mode


  extra fields not permitted (type=value_error.extra)


cameras -> Garage -> record -> events -> objects


  value is not a valid list (type=type_error.list)


cameras -> Garage -> record -> events -> retain


  none is not an allowed value (type=type_error.none.not_allowed)


cameras -> Garage -> record -> events -> default


  extra fields not permitted (type=value_error.extra)


cameras -> Garage -> record -> events -> mode


  extra fields not permitted (type=value_error.extra)


cameras -> Driveway -> record -> events -> objects


  value is not a valid list (type=type_error.list)


cameras -> Driveway -> record -> events -> retain


  none is not an allowed value (type=type_error.none.not_allowed)


cameras -> Driveway -> record -> events -> default


  extra fields not permitted (type=value_error.extra)


cameras -> Driveway -> record -> events -> mode


  extra fields not permitted (type=value_error.extra)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
