### ISSUE TITLE
[Support]: Docker-Copose Error 28 no room on device

### ISSUE THREAD

**Issue by gr8er1mark** [blakeblackshear/frigate#3761]
### Describe the problem you are having

I am trying to migrate away from my current configuration running frigate in Home Assistant and instead running and instance on docker. I am new to docker and chose to use docker-compose when configuring frigate.

When ever I run command sudo docker-compuse up Frigate existing stating error code 1 with the log containing the following entry OSError: [Errno 28] No space left on device.

I have looked online I found the different guidance about prune etc but none of these command seem to remove the issue. There is plenty of space on the device/disks I am trying to use. I thought it may have been a permission issue but can't see anything obvious when I look at the setup currently.

### Version

Can't launch to get this

### Frigate config file

```yaml
mqtt:
  host: 192.168.50.94:1883
  user: XXXXXX
  password: XXXXXXXXX
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Front_Door:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: http://192.168.50.201/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXXXX&password=XXXXXXXX
          roles:
            - record
            - rtmp
        - path: http://192.168.50.201/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXXXXX&password=XXXXXXX
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 7
    motion:
      mask:
        - 178,0,0,63,0,0
        - 725,672,896,672,896,253,742,618
    objects:
      track:
        - person
        - car
        - bicycle
        - dog
        - cat
        - bird
    record:
      enabled: true
      events:
        pre_capture: 20
        post_capture: 30
#      retain:
#         default: 2
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      
  Back_Garden:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: http://192.168.50.203/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXXXXXX&password=XXXXXX
          roles:
            - record
            - rtmp
        - path: http://192.168.50.203/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXXXXXX&password=XXXXXXXXX
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 178,0,0,63,0,0
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bicycle
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        pre_capture: 20
        post_capture: 30
#      retain:
#         default: 2
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      
  Driveway:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: http://192.168.50.202/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=XXXXXXXXpassword=633403
          roles:
            - record
            - rtmp
        - path: http://192.168.50.202/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=XXXXXXXXpassword=XXXXXXX
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 7
    motion:
      mask:
        - 178,0,0,63,0,0
        - 725,672,896,672,896,253,742,618
    objects:
      track:
        - person
        - car
        - bicycle
        - dog
        - cat
        - bird
    record:
      enabled: true
      events:
        pre_capture: 20
        post_capture: 30
#      retain:
#         default: 2
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
```

### Relevant log output

```shell
Recreating frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
frigate    |     return _run_code(code, main_globals, None,
frigate    |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
frigate    |     exec(code, run_globals)
frigate    |   File "/opt/frigate/frigate/__main__.py", line 15, in <module>
frigate    |     frigate_app = FrigateApp()
frigate    |   File "/opt/frigate/frigate/app.py", line 39, in __init__
frigate    |     self.stop_event = mp.Event()
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 93, in Event
frigate    |     return Event(ctx=self.get_context())
frigate    |   File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 324, in __init__
frigate    |     self._cond = ctx.Condition(ctx.Lock())
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 78, in Condition
frigate    |     return Condition(lock, ctx=self.get_context())
frigate    |   File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 214, in __init__
frigate    |     self._sleeping_count = ctx.Semaphore(0)
frigate    |   File "/usr/lib/python3.8/multiprocessing/context.py", line 83, in Semaphore
frigate    |     return Semaphore(value, ctx=self.get_context())
frigate    |   File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 126, in __init__
frigate    |     SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
frigate    |   File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
frigate    |     sl = self._semlock = _multiprocessing.SemLock(
frigate    | OSError: [Errno 28] No space left on device
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 520A

### Any other information that may be helpful

HP elitedesk 800 G2 mini running ubuntu 

***DOCKER-COMPOSE Config****
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "666" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for othe
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/mark/NVME SSD/frigate/config/config.yml:/config/config.yml:ro
      - /media/mark/NVME SSD/frigate/media:/media/frigate
      - /media/mark/NVME SSD/frigate/recordings:/media/frigate/recordings:rw
      - /media/mark/NVME SSD/frigate/clips/:/media/frigate/clips:rw
      - /media/mark/NVME SSD/frigate/frigate.db:/db/frigate.db:rw
      - type: tmpfs
        target: /shared/frigate/tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

**Comment by NickM-27** [comment]
On first look, it isn't talking about storage but about memory.

I believe it is your tmp cache assignment

```yaml
- type: tmpfs
target: /shared/frigate/tmp/cache
tmpfs:
size: 1000000000
```

is incorrect and it should be `/tmp/cache` otherwise it won't use RAM which defeats the purpose of it.

**Comment by gr8er1mark** [comment]
@NickM-27 
Thanks for looking at this.

I tried changing that as part of my attempts to resolve the issue but it was happening with the /tmp/cache as well.

I just changed it back and tried to run and still get the same error.

**Comment by NickM-27** [comment]
> @NickM-27 Thanks for looking at this.
> 
> I tried changing that as part of my attempts to resolve the issue but it was happening with the /tmp/cache as well.
> 
> I just changed it back and tried to run and still get the same error.

Definitely leave it as that. How much RAM does your device have?

**Comment by gr8er1mark** [comment]
@NickM-27 

I have 8gb RAM

Running Ubuntu with virtualbox for home assistant with 2gb RAM allocated to that and nothing else other than trying to run frigate in docker.

**Comment by NickM-27** [comment]
It also looks like you have conflicting volume mounts, you should remove `- /media/mark/NVME SSD/frigate/media:/media/frigate` from the compose file since you are mapping its subdirectories already

**Comment by gr8er1mark** [comment]
@NickM-27 thanks I removed the extra mapping. Still getting the same error message.

**Comment by NickM-27** [comment]
So you're running docker natively in your OS right? How much free space is available?

**Comment by gr8er1mark** [comment]
The OS partition has over 80gb free space left.

The M.2 SSD drive where I am mapping clips and recordings is 2tb, it has nothing else on it at the moment. At some point Frigate was able to create the folders on the m.2 drive.

**Comment by NickM-27** [comment]
Okay I think it's due to your db mapping, you never actually mapped the Frigate config to use the db location you specified

You need to add

```yaml
database:
  # The path to store the SQLite DB (default: shown below)
  path: /db/frigate.db
```

to your Frigate config
