### ISSUE TITLE
Camera "friendly name"

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3765]
### Describe the problem you are having

How do I get the Frigate camera view to show a friendly name rather than the config camera name?
<img width="604" alt="Frigate friendly name" src="https://user-images.githubusercontent.com/42817627/188303251-f5b81a3a-5fb0-4c40-bc06-31f6e91127b2.png">

### Version

0.10.1-83481AF

### Frigate config file

```yaml
car_park: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://pw@10.0.1.57:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://pw@10.0.1.57:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
