### ISSUE TITLE
[Support]: Excessive recordings with no object detections

### ISSUE THREAD

**Issue by coverthembrow** [blakeblackshear/frigate#3766]
### Describe the problem you are having

On one of my 3 cameras, I'm getting random, long recordings, with no related object detection. All my cameras are set up to only detect people, and set to retain events only.

```
objects:
  track:
    - person

record:
  enabled: True
  events:
    retain:
      default: 10
```

The camera which is misbehaving is the back garden, which does have plants moving in the wind; I'm wondering if this could be the issue?

At 08:25 it detected me in the back garden, and created a recording and snapshot. This recording continued until 08:59 (as seen in Home Assistant), even though the last person detected was around 08:35.

I then have separate recordings, each of an hour until 12:00, then as last one of ~21 minutes until 12:21, when a second person was detected.

The false positives [page](https://docs.frigate.video/guides/false_positives/) talks about a number of values to change, but I don't see where to apply these in the config, or how to work out what values I should use instead. Is there a way to see the different scores for a given event?

As seen in the below from Home Assistant, it's showing motion solidly from 08:31 to 14:42.
![image](https://user-images.githubusercontent.com/102583631/188468956-6158eea7-856b-44aa-a54a-ada8a69f4a45.png)

### Version

0.11.0-37325C7

### Frigate config file

```yaml
birdseye:
  enabled: False

mqtt:
  host: REDACTED
  user: REDACTED
  password: REDACTED

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

cameras:
  drive_camera:
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED
          roles:
            - record

        - path: rtsp://REDACTED
          roles:
            - detect
            - rtmp

    motion:
      mask:
        - 0,368,152,368,151,0,0,0
        - 288,0,284,57,147,55,142,0
        - 640,368,468,368,509,0,640,0

    zones:
      front_door :
        coordinates: 302,0,293,0,244,166,294,293,458,288,491,0
        objects:
          - person

    detect:
      width: 640
      height: 368
      fps: 5
      enabled: True

  garden_camera:
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED
          roles:
            - record

        - path: rtsp://REDACTED
          roles:
            - detect
            - rtmp

    motion:
      mask:
        - 640,0,299,0,285,91,640,285
        - 183,352,0,352,0,45,60,44

    detect:
      width: 640
      height: 352
      fps: 5
      enabled: True

  front_camera:
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED
          roles:
            - record

        - path: rtsp://REDACTED
          roles:
            - rtmp
            - detect

    detect:
      width: 640
      height: 480
      fps: 5
      enabled: True

    motion:
      mask:
        - 436,33,447,175,573,335,565,480,640,480,640,0,0,0,0,105,86,39


objects:
  track:
    - person

record:
  enabled: True
  events:
    retain:
      default: 10

snapshots:
  enabled: True
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version 5.0.1-Jellyfin Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --toolchain=hardened --enable-cross-compile --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu-
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rtsp, from 'rtsp://REDACTED':
  Metadata:
    title           : RTSP/RTP stream from anjvision ipcamera
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 640x352, 5 fps, 5 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

various
