### ISSUE TITLE
[Support]: Unable to re-install

### ISSUE THREAD

**Issue by smcnab1** [blakeblackshear/frigate#3767]
### Describe the problem you are having

Migrated HA OS instance. Frigate somehow stopped working suddenly.

Now when trying to access telling me add-on not running.

When go to start states Port '5000' already in use.

Have tried to remove all evidence of frigate in config including HACS & Add-On and reinstall. Still doing the same as above.

Tried with port forward on router and without.

Unable to now have frigate on my HA system which is a bit of a pain.

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: X.X.X.X
  port: 1883
  user: mqtt-user
  password: XX

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous

detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  improve_contrast: True

record:
  enabled: true
  retain: 
    days: 0
    mode: all
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  crop: false
  retain:
    default: 10
    objects:
      person: 15
  
live:
  height: 1920
  quality: 8
  
timestamp_style:
  position: tl
  format: "%d/%m/%y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid

cameras:
  Hall:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX
          roles:
            - record
            - rtmp
        - path: rtsp://XXXX
          roles:
            - detect

  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX
          roles:
            - record
            - rtmp
        - path: rtsp://XXXX
          roles:
            - detect

  Bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX
          roles:
            - record
            - rtmp
        - path: rtsp://XXXX
          roles:
            - detect

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
      quality: 70
```

### Relevant log output

```shell
2022-09-05 15:36:33.981 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/ccab4aaf_frigate/start - Port '5000' is already in use by something else on the host.
2022-09-05 15:40:25.008 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/ccab4aaf_frigate/start - Port '5000' is already in use by something else on the host.
```

### FFprobe output from your camera

```shell
Nil
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo C210 (x3)
