### ISSUE TITLE
[Support]: Person detection issue

### ISSUE THREAD

**Issue by maframan** [blakeblackshear/frigate#3770]
### Describe the problem you are having

I've configured a zone for person detection but  detection events of person outside the zone are generated, why? I've wrong configuration?
Below event and zone in ingresso_principale camera:
![image](https://user-images.githubusercontent.com/24868793/188512223-d38f216d-e32d-450a-96c4-4ea415803572.png)

Zone:
![image](https://user-images.githubusercontent.com/24868793/188512301-64d37132-02df-4fc6-86bc-8db899bd4ddd.png)

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  user: xxxxxxxxxxx
  password: xxxxxxxxxx
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  retain:
    default: 10
    objects:
      person: 15

cameras:
  ingresso_principale:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxx@192.168.102.51:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False  # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - zone_1
    zones:
      zone_1:
        coordinates: 1390,1080,1540,473,825,377,800,373,54,669,0,1080
        objects:
          - person
  strada_privata:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.102.44:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - zone_4
    zones:
      zone_4:
        coordinates: 1280,720,1234,166,0,409,0,720
        objects:
          - person
  giardino_posteriore_sx:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.102.23:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:   
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - zone_2
    zones:
      zone_2:
        coordinates: 0,720,1280,720,1280,246,1106,239,0,333,1099,251,864,197,609,187,0,287
        objects:
          - person
  garage_esterno:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxx@192.168.102.45:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    snapshots:
      required_zones:
        - rampa
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    zones:
      rampa:
        coordinates: 0,1080,1920,1080,1920,150,1444,310,1369,333,1242,443,1316,621,986,617,634,596,0,47
        objects:
          - person
  giardino_posteriore_dx:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.102.2:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
    snapshots:
      required_zones:
        - zone_3
    zones:
      zone_3:
        coordinates: 763,491,1920,557,1920,1080,0,1080,0,1080,86,666
        objects:
          - person

birdseye:
  enabled: False
  width: 1280
  height: 720
  quality: 8
  mode: objects
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version 5.1-2+b1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.1.0-7)
  configuration: --prefix=/usr --extra-version=2+b1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libplacebo --enable-libx264 --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0xaaaafb891dc0] Missing PPS in sprop-parameter-sets, ignoring
[rtsp @ 0xaaaafb891dc0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@yyy.yyy.yyy.yyy:554/h.264':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"detection_fps":3.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":17.25,"pid":1246}},"garage_esterno":{"camera_fps":5.1,"capture_pid":253,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"giardino_posteriore_dx":{"camera_fps":5.1,"capture_pid":257,"detection_fps":0.0,"pid":234,"process_fps":5.1,"skipped_fps":0.0},"giardino_posteriore_sx":{"camera_fps":5.0,"capture_pid":245,"detection_fps":0.0,"pid":231,"process_fps":5.0,"skipped_fps":0.0},"ingresso_principale":{"camera_fps":5.1,"capture_pid":235,"detection_fps":3.1,"pid":225,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":1047.2,"mount_type":"tmpfs","total":1073.7,"used":26.5},"/media/frigate/clips":{"free":210065.8,"mount_type":"ext4","total":245822.8,"used":23258.3},"/media/frigate/recordings":{"free":210065.8,"mount_type":"ext4","total":245822.8,"used":23258.3},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":38832,"version":"0.10.1-83481af"},"strada_privata":{"camera_fps":5.1,"capture_pid":237,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Ezviz
