### ISSUE TITLE
[Support]: Object detection despite the use of zones

### ISSUE THREAD

**Issue by dennisoderwald** [blakeblackshear/frigate#3786]
### Describe the problem you are having

Objects are also detected outside the zone, I had thought that this should work with the creation of zones and inside the camera of the definition of the `required_zones`, but unfortunately not. Previously I had used Motion Masks but @NickM-27  had already told me that this is not the appropriate use.

<img width="1458" alt="Bildschirmfoto 2022-09-07 um 09 31 10" src="https://user-images.githubusercontent.com/1653185/188816874-c46fb10e-6dd2-4697-8895-674276eb001a.png">

<img width="1027" alt="Bildschirmfoto 2022-09-07 um 09 30 50" src="https://user-images.githubusercontent.com/1653185/188817107-03383f15-cd52-417f-8049-7e655d492443.png">

I've also tested dragging the zone smaller, but the object is so far outside that I can't understand it.

Thanks for your support in advance!

### Version

0.10.1-83481AF

### Frigate config file

```yaml
0.10.1-83481AF{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "garden_left": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "url",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i url -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "garden_left",
      "objects": {
        "filters": {
          "bird": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "bird",
          "cat",
          "dog",
          "car"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "zone_left",
          "zone_right"
        ],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "zone_left": {
          "coordinates": "1612,0,1582,285,1535,585,1920,729,1920,1080,0,1080,0,0",
          "filters": {},
          "objects": []
        }
      }
    },
    "garden_right": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "url",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i url -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "garden_right",
      "objects": {
        "filters": {
          "bird": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "bird",
          "cat",
          "dog",
          "car"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "zone_left",
          "zone_right"
        ],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "zone_right": {
          "coordinates": "0,483,1920,493,1920,1080,0,1080",
          "filters": {},
          "objects": []
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 1080,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1920
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 8,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "127.0.0.1",
    "password": "",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mosquitto"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person",
      "bird",
      "cat",
      "dog",
      "car"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": false
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": true,
    "height": null,
    "quality": 70,
    "required_zones": [
      "zone_left",
      "zone_right"
    ],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

UniFi Protect Stream (G3 Flex)

**Comment by NickM-27** [comment]
You set `required_zones` on `snapshot` but you did not set it for `record`. As such, an event will be created since the recordings are always saved for detected objects.

**Comment by dennisoderwald** [comment]
@NickM-27 That means if I don't want a triggered motion, I also have to put it in `record` even though I have record set to enabled: False?

**Comment by NickM-27** [comment]
> ```yaml
> enabled": true
> ```

No that's my bad, I didn't catch that `record` was disabled. In that case, odds are you have a false positive somewhere that is being seen as a person. Potentially one of those plants in the zone, I would watch the debug view and see.

Frigate's tracking is currently not sophisticated, if it saw one person in the last frame and sees one person in the current frame then it assumes that it is the same person. This means that if the person walking is being tracked and disappears and then the next frame frigate detects the plant as a person it assumes it is the same person now in the zone and the event is saved.

To fix this:
1. Watch the debug view and see what frigate sees, likely a false positive somewhere
2. Once false positive is identified, use an object mask to mask out the bottom center of the false objects bounding box.

**Comment by dennisoderwald** [comment]
I understand, but it has already happened with real people who simply moved far outside the zone. Is there no option to tell Frigate to ignore them completely and just analyze the zone itself?

**Comment by dennisoderwald** [comment]
This really happened a lot today. Here is another example where it is correct that it is a person but well outside the defined zone.

![snapshot](https://user-images.githubusercontent.com/1653185/188990431-ac4ab0a3-5be3-4ea9-8700-7eefe41525bd.jpeg)

**Comment by NickM-27** [comment]
> I understand, but it has already happened with real people who simply moved far outside the zone.

Like I said it's due to a false positive being in the zone (as in an object that isn't a person being detected as a person). Without a person entering the zone this won't happen, so one way or another frigate is seeing a person in the zone. 

> Is there no option to tell Frigate to ignore them completely and just analyze the zone itself?

Frigate will only create an event if it found the person inside of the zone.

**Comment by NickM-27** [comment]
> This really happened a lot today. Here is another example where it is correct that it is a person but well outside the defined zone.
> 
> 
> 
> ![snapshot](https://user-images.githubusercontent.com/1653185/188990431-ac4ab0a3-5be3-4ea9-8700-7eefe41525bd.jpeg)


Please read the docs as I've already explained how this likely occurred and how to address it https://docs.frigate.video/guides/false_positives

**Comment by dennisoderwald** [comment]
But the person is not in the zone at all? See the screenshot in the initial post. Or is it that it incorrectly assigns false positive to an object in the zone and then identifies the same person outside the zone and then triggers an event? If so, how can this be prevented? Or is this only possible by already limiting the source of the camera?

**Comment by NickM-27** [comment]
> But the person is not in the zone at all? See the screenshot in the initial post. Or is it that it incorrectly assigns false positive to an object in the zone and then identifies the same person outside the zone and then triggers an event?

Not meaning this to be rude, but please re-read my explanation above.
It's the opposite order of what you said.
What likely happened is: 

1. frigate saw a real person walking outside the zone
2. Frigate saw this real person and assigned a high score
3. The real person disappeared from the camera frame
4. The following frame frigate sees a "person" that was not a person (aka false positive) and it happens to be in the zone (plants can often be seen as person).
5. Frigate assumes this is the same person and the high score is kept meaning the object is detected in the zone. 

> If so, how can this be prevented? Or is this only possible by already limiting the source of the camera?

As I explained above, simply view the debug view of the camera in frigate with bounding boxes enabled so you can see what frigate sees. Once motion occurs (if false positive objects are not already visible) they should be shown at least for a few seconds. You can then use the techniques linked above to mask out or otherwise remove the false positive from occurring.

**Comment by dennisoderwald** [comment]
Sorry if I didn't quite follow the logic. I have read the whole thing several times but simply misunderstood the form. I will read through again tomorrow at my leisure. However, the debug view is only live. I can't see any more information on a snapshot except the detected object or an information of an origin object - right? I hope that was not too confusing formulated now.

**Comment by NickM-27** [comment]
> However, the debug view is only live. I can't see any more information on a snapshot except the detected object or an information of an origin object - right?

Without any recordings, yes. 

However, if you were to enable record along with required_zones for record. 

```yaml
record:
  enabled: true
  events:
    pre_capture: 30 # this is to ensure there is enough pre-motion data
    retain:
      default: 3
      mode: all # to ensure that all segments are kept for accurate replay
    required_zones: your_zone
```

You could then download the mp4 that was created and use it as an emulated camera (meaning the config would need to be exactly the same) so you could watch back the event and see what the camera saw during that time. 
https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing
