### ISSUE TITLE
[EdgeTPU Support]:  HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback] Fatal Python error: Aborted

### ISSUE THREAD

**Issue by maxi1134** [blakeblackshear/frigate#3808]
### Describe the problem you are having

The Edge TPU seems to get undetected then redetected

### Version

0.11.0-C461C9E

### Frigate config file

```yaml
objects:
  track:
    - person
detect:
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 50
detectors:
  coral:
    type: edgetpu
    device: usb
database:
  path: /config/database/frigate.db
mqtt:
  # Required: host name
  host: 192.168.0.15
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mosquitto
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: '!@#43qgq3g'
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  patiocam:
    rtmp:
      enabled: false
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -c:v
        - h264_cuvid
      inputs:
         #- path: rtmp://192.168.50.10:1935/livemain
         - path: rtsp://127.0.0.1:8554/patio_camera
           roles:
            - record
         #- path: rtmp://192.168.50.10:1935/livesub
         - path: rtsp://127.0.0.1:8554/patio_camera_sub
           roles:
            - detect          
      output_args:
        rtmp: -c copy -f flv
    detect:
       width: 704
       height: 576
       fps: 5
    # zones:
      # entrance:
        # coordinates: 2560,1920,2560,0,1661,0,1410,359,950,442,0,1253,0,1920
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # required_zones: 
      # Optional: height to resize the snapshot to (default: original size)
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 60
    record:
        # Optional: Enable recording (default: shown below)
        enabled: true
        # Optional: Number of days to retain (default: shown below)
        #retain_days: 60
        # Optional: Event recording settings
        events:
          # Optional: Enable event recording retention settings (default: shown below)
          # Optional: Maximum length of time to retain video during long events. (default: shown below)
          # NOTE: If an object is being tracked for longer than this amount of time, the cache
          #       will begin to expire and the resulting clip will be the last x seconds of the event unless retain_days under record is > 0.
          #max_seconds: 60000
          # Optional: Number of seconds before the event to include in the event (default: shown below)
          pre_capture: 10
          # Optional: Number of seconds after the event to include in the event (default: shown below)
          post_capture: 10
          # Optional: Objects to save event for. (default: all tracked objects)
          objects:
            - person
          # Optional: Restrict event to objects that entered any of the listed zones (default: no required zones)
          # required_zones: ["entrance"]
          # Optional: Retention settings for event
          retain:
            # Required: Default retention days (default: shown below)
            default: 10
            # Optional: Per object retention days
            objects:
              person: 60
    # objects:
      # filters:
         # person:
           # mask:
            # # - 1820,678,1878,0,1324,0,0,0,0,1208,0,1920,402,1920,597,1566,48,1276,164,1161,412,1192,448,1176,628,1205,1104,806,1388,644
             # #  NORMAL MASK- 1822,718,1878,0,1324,0,0,0,0,1207,0,1920,402,1920,597,1566,713,1455,745,1388,794,1331,815,1327,820,1279,1102,922,1239,924,1381,670
            # - 3840,1403,3840,997,2266,870,2217,1193,2419,2160,3548,2160,3819,2160,3840,2160
  front_door:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
       - -c:v 
       - h264_cuvid
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_camera_sub
          roles:
            - detect
        #- path: rtmp://192.168.0.210/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=
        - path: rtsp://127.0.0.1:8554/front_door_camera
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    record:
        # Optional: Enable recording (default: shown below)
        enabled: true
        # Optional: Number of days to retain (default: shown below)
        #retain_days: 60
        # Optional: Event recording settings
        events:
          # Optional: Enable event recording retention settings (default: shown below)
          # Optional: Maximum length of time to retain video during long events. (default: shown below)
          # NOTE: If an object is being tracked for longer than this amount of time, the cache
          #       will begin to expire and the resulting clip will be the last x seconds of the event unless retain_days under record is > 0.
         # max_seconds: 60000
          # Optional: Number of seconds before the event to include in the event (default: shown below)
          pre_capture: 10
          # Optional: Number of seconds after the event to include in the event (default: shown below)
          post_capture: 10
          # Optional: Objects to save event for. (default: all tracked objects)
          objects:
            - person
          # Optional: Restrict event to objects that entered any of the listed zones (default: no required zones)
          # required_zones: ["entrance"]
          # Optional: Retention settings for event
          retain:
            # Required: Default retention days (default: shown below)
            default: 10
            # Optional: Per object retention days
            objects:
              person: 60
    objects:
      filters:
         bicycle:
           mask:
             - 348,183,185,480,0,480,0,380,289,74
         car:
           mask:
             - 389,0,0,0,0,99,0,480,239,90,376,100
         person:
           mask:
             - 114,480,208,333,101,384,0,352,30,317,56,322,116,315,352,121,466,140,487,0,0,0,0,480,60,480
  geovision:
    rtmp:
      enabled: false
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
        - -c:v
        - h264_cuvid
        #- hevc_cuvid
      inputs:
         - path: rtsp://127.0.0.1:8554/back_door_camera
           roles:
            - record
         - path: rtsp://127.0.0.1:8554/back_door_camera_sub
           roles:
            - detect
    detect:
      width: 252
      height: 448
      fps: 5
            

    # detect:
      # width: 1080
      # height: 1920
      # fps: 5
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: false
      required_zones: []
      # Optional: height to resize the snapshot to (default: original size)
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 60
    record:
        # Optional: Enable recording (default: shown below)
        enabled: true
        # Optional: Number of days to retain (default: shown below)
        #retain_days: 0
        # Optional: Event recording settings
        events:
          # Optional: Enable event recording retention settings (default: shown below)
          # Optional: Maximum length of time to retain video during long events. (default: shown below)
          # NOTE: If an object is being tracked for longer than this amount of time, the cache
          #       will begin to expire and the resulting clip will be the last x seconds of the event unless retain_days under record is > 0.
          #max_seconds: 60000
          # Optional: Number of seconds before the event to include in the event (default: shown below)
          pre_capture: 10
          # Optional: Number of seconds after the event to include in the event (default: shown below)
          post_capture: 10
          # Optional: Objects to save event for. (default: all tracked objects)
          objects:
            - person
          # Optional: Restrict event to objects that entered any of the listed zones (default: no required zones)
          required_zones: []
          # Optional: Retention settings for event
          retain:
            # Required: Default retention days (default: shown below)
            default: 10
            # Optional: Per object retention days
            objects:
              person: 60
    #objects:
    objects:
      filters:
        person:
          mask: 
            - 0,402,0,0,23,0,75,190
  # facecam:
    # rtmp:
      # enabled: false
    # ffmpeg:
      # input_args:
        # - -avoid_negative_ts
        # - make_zero
        # - -fflags
        # - nobuffer
        # - -flags
        # - low_delay
        # - -strict
        # - experimental
        # - -fflags
        # - +genpts+discardcorrupt
        # - -use_wallclock_as_timestamps
        # - "1"
        # - -c:v
        # - h264_cuvid
        # #- hevc_cuvid
      # inputs: 
         # - path: rtsp://127.0.0.1:8554/faceshot_camera
           # roles: 
            # - record
         # - path:  rtsp://127.0.0.1:8554/faceshot_camera_sub
           # roles:
            # - detect
    # detect:
      # width: 208
      # height: 368
      # fps: 5
    # snapshots:
      # # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # # This value can be set via MQTT and will be updated in startup based on retained value
      # enabled: True
      # # Optional: print a timestamp on the snapshots (default: shown below)
      # timestamp: False
      # # Optional: draw bounding box on the snapshots (default: shown below)
      # bounding_box: True
      # # Optional: crop the snapshot (default: shown below)
      # crop: False
      # required_zones: []
      # # Optional: height to resize the snapshot to (default: original size)
      # # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      # # Optional: Camera override for retention settings (default: global values)
      # retain:
        # # Required: Default retention days (default: shown below)
        # default: 10
        # # Optional: Per object retention days
        # objects:
          # person: 60
    # record:
        # # Optional: Enable recording (default: shown below)
        # enabled: true
        # # Optional: Number of days to retain (default: shown below)
        # #retain_days: 60
        # # Optional: Event recording settings
        # events:
          # # Optional: Enable event recording retention settings (default: shown below)
          # # Optional: Maximum length of time to retain video during long events. (default: shown below)
          # # NOTE: If an object is being tracked for longer than this amount of time, the cache
          # #       will begin to expire and the resulting clip will be the last x seconds of the event unless retain_days under record is > 0.
          # max_seconds: 60000
          # # Optional: Number of seconds before the event to include in the event (default: shown below)
          # pre_capture: 10
          # # Optional: Number of seconds after the event to include in the event (default: shown below)
          # post_capture: 10
          # # Optional: Objects to save event for. (default: all tracked objects)
          # objects:
            # - person
          # # Optional: Restrict event to objects that entered any of the listed zones (default: no required zones)
          # required_zones: []
          # # Optional: Retention settings for event
          # retain:
            # # Required: Default retention days (default: shown below)
            # default: 10
            # # Optional: Per object retention days
            # objects:
              # person: 60
    # #objects:
    # objects:
      # filters:
        # person:
          # min_area: 380000 #previouslyt 480000
         # # mask:
            # # bonne coordene  - 1296,2304,1296,1584,1296,1425,646,1413,0,1455,0,2304
            # # - 1296,2304,1296,1659,1296,1807,1296,1397,699,1426,615,1381,550,1433,0,1415,0,2304
    # zones:
      # facecam_zone:
        # coordinates: 1296,2304,1296,0,0,0,0,2304
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: '4048M'
    image: blakeblackshear/frigate:0.11.0-rc2
    runtime: nvidia
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/maxi1134/docker/frigate/config.yml:/config/config.yml:ro
      - /home/maxi1134/docker/frigate/database:/config/database
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 10000000000
   # ports:
   #   - '5000:5000'
   #   - '1935:1935' # RTMP feeds
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
```

### Relevant log output

```shell
F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
Fatal Python error: Aborted

Thread 0x00007f4246ffd700 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap

Thread 0x00007f42c297a700 (most recent call first):
  File "/usr/lib/python3.9/selectors.py", line 416 in select
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 936 in wait
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 429 in _poll
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 262 in poll
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 113 in get
  File "/opt/frigate/frigate/edgetpu.py", line 147 in run_detector
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/edgetpu.py", line 220 in start_or_restart
  File "/opt/frigate/frigate/watchdog.py", line 34 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
[2022-09-09 19:51:23] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-09-09 19:51:23] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34668]
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
