### ISSUE TITLE
[Support]: person detection stays on

### ISSUE THREAD

**Issue by sygys** [blakeblackshear/frigate#3823]
### Describe the problem you are having

Im not sure why this is happening but for some reason on 1 of my camera's i have a binary sensor for when someone is in a specific zone. For some reason it now happened once that a person is detected in the zone but the sensor isnt going back to off after a person left the zone. Can the integration miss a mqtt message? OR could this have something to do with the mqtt trouble in core 2022.9.1

### Version

0.10.1-83481AF

### Frigate config file

```yaml
##### KEUKEN #####
  camera_keuken:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.178.93/cam/realmonitor?channel=1&subtype=00&authbasic=wdfc43frec43f3rf3=
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.80
          threshold: 0.80
          min_area: 50000
        dog:
          min_score: 0.75
          threshold: 0.75
          max_area: 40000
    motion:
      mask:
        - 1531,83,1852,74,1850,35,1535,37
    detect:
      max_disappeared: 400
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 50
        max_frames:
          objects:
            person: 1000
            dog: 1000
    zones:
      tablet_zone:
        coordinates: 1170,0,1178,470,857,638,777,572,767,0
        objects:
          - person
      eettafel:
        coordinates: 1920,1080,1920,698,1632,559,1295,547,1037,673,867,859,889,1080
        objects:
          - person
      keuken:
        coordinates: 378,774,271,662,98,730,0,440,0,0,756,0,781,576
        objects:
          - person
      achterdeur:
        coordinates: 0,1080,277,1080,250,1032,0,1001
        objects:
          - person
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 0
        mode: active_objects
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        required_zones: []
        retain:
          default: 4
          mode: active_objects
          objects:
            person: 4
```

### Relevant log output

```shell
no errors were found
```

### FFprobe output from your camera

```shell
dont know what this is
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Imou ranger iq

### Any other information that may be helpful

I know im using an old version of frigate and i would like to keep it this way. i has always worked.
