### ISSUE TITLE
[Support]: FFMPEG not working after upgrade from 11.0.0-rc1 to 11.0.0-rc2

### ISSUE THREAD

**Issue by andrempo** [blakeblackshear/frigate#3829]
### Describe the problem you are having

After updating to rc2 version the stream stoped working with  the log "Cannot assign requested address". Downgrading to rc1 all works fine. Same problem with and without hwaccel_args.

### Version

0.11.0-rc2

### Frigate config file

```yaml
cameras:
  portao:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass!@192.168.0.12:554/stream2
          roles:
            - detect
            - record
    motion:
      mask:
        - 65,56,240,28,252,0,0,0,0,360,120,360,168,310
        - 640,360,640,0,543,0,459,337,480,360
    zones:
      rua:
        coordinates: 495,209,550,51,345,28,347,193
    record:
      retain: 
        days: 2
      events:
        retain:
          default: 15
```

### Relevant log output

```shell
2022-09-12 13:32:33] ffmpeg.portao.detect           ERROR   : [rtsp @ 0xc6e060] Unable to open RTSP for listening
[2022-09-12 13:32:33] ffmpeg.portao.detect           ERROR   : rtsp://user:password!@192.168.0.12:554/stream2: Cannot assign requested address
```

### FFprobe output from your camera

```shell
configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[udp @ 0x2498330] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0x24a86c0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0x24b93f0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0x24c9740] attempted to set receive buffer to size 393216 but it only ended up set as 360448
Input #0, rtsp, from 'rtsp://user:pass!@192.168.0.12:554/stream2':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 640x360, 15 fps, 28.58 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

TPLINK Tapo
