### ISSUE TITLE
[Support]: HASS Video "jumps"

### ISSUE THREAD

**Issue by jean-paullizotte** [blakeblackshear/frigate#3831]
### Describe the problem you are having

Camera view in hass "jumps".

It looks like video changes alignment.
In any case it gives the illusion(?) that the video frames jumps up and down.
Sample video attached of a screen grab.
FFPLAY of the rtmp stream(s) from frigate does not reflect this.
The birdseye view and the live view, in frigate is all good.

Cameras are all 3 different brands and all my views are doing this (6).
Was not present on the "latest" tag/version of docker.

https://user-images.githubusercontent.com/36302005/189930158-a1ac5a75-4067-409f-be8e-2412047ad48e.mp4

### Version

0.11.0-C461C9E

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.4
  topic_prefix: frigate
  stats_interval: 30

cameras:
  doorbell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:PAHDEZ@192.168.1.78 # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
    zones:
      balcony:
        coordinates: 1114,659,1238,615,1041,544,806,572,505,570,295,550,206,593,118,640,292,685,497,714,795,708,1011,688
      landing:
        coordinates: 899,449,1122,501,1078,561,1218,621,1280,599,1280,494,1121,441
    motion:
      mask:
        - 253,307,255,416,299,542,403,552,717,562,1037,542,1200,513,1280,453,1280,245,880,192,298,197
        - 683,641,791,637,793,613,681,619
    rtmp:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      events:
        required_zones: 
          - balcony
          - landing
        retain:
          mode: motion
          default: 7
    snapshots:
      enabled: true
      required_zones: 
          - balcony
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          threshold: 0.7
      mask:
        - 738,565,919,554,1114,555,1237,532,930,450,1200,438,1280,472,1280,392,1040,395,803,382,243,385,254,430,298,552,535,570


#======================doorbell



  garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.119:554/11 # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
    zones:
      driveway:
        coordinates: 1280,720,461,720,413,491,606,441,506,185,367,219,331,71,614,14,832,184,1139,477,1280,637
    motion:
      mask:
        - 932,264,1280,639,1280,213,1280,0,802,0,0,0,0,720,431,720,344,107,628,26
    rtmp:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects  
      events:
        required_zones:
          - driveway
        retain:
          mode: motion
          default: 7
    snapshots:
      enabled: true
      required_zones:
          - driveway
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
        - bicycle
      filters:
        car:
          mask:
           - 610,0,1280,631,1280,0,877,0
        bicycle:
          mask:
           - 610,0,1280,631,1280,0,877,0
        person:
          mask:
           - 610,0,1280,631,1280,0,877,0

#======================garage



  backyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:mypassword@192.168.1.186:554/11 # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
    zones:
      cabanon_1:
        coordinates: 0,720,179,720,156,547,131,273,0,232
      cabanon_2:
        coordinates: 992,379,1118,447,1185,461,1280,438,1280,373,1026,353
      yard:
        coordinates: 1012,720,172,720,243,462,479,472,664,450,988,417,1102,441,1248,587,1133,641,981,699
    motion:
      mask:
       - 479,472,1000,418,1001,351,1028,359,1188,427,1216,335,1280,181,1280,110,1280,0,789,0,301,0,0,0,0,217,21,252,42,469,477,463
       - 1185,610,1280,530,1280,720,1009,720,992,695,1145,624,1208,348,1163,339,1215,281,1280,286,1280,391,1210,453
    rtmp:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects 
      events:
        required_zones:
          - yard
          - cabanon_1
          - cabanon_2
        retain:
          mode: active_objects
          default: 7
    snapshots:
      enabled: true
      required_zones:
          - yard
          - cabanon_1
          - cabanon_2
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - bicycle
      filters:
        person:
          threshold: 0.8
          min_area: 6000


#======================backyard



  kitchen: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:mypassword@192.168.1.197:554/live # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
    zones:
        door1:
          coordinates: 1069,720,931,720,1066,523,1078,477,1154,489,1227,586,1153,602
        door2:
          coordinates: 313,462,412,466,408,282,320,288
    motion:
      mask:
        - 466,0,512,235,364,248,179,236,210,0
        - 232,690,499,601,465,545,327,505,196,546
    rtmp:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects 
      events:
        required_zones:
          - door1
          - door2
        retain:
          mode: active_objects
          default: 7
    snapshots:
      enabled: true
      required_zones:
          - door1
          - door2
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
          threshold: 0.8
      mask:
        - 227,720,380,720,507,720,519,626,501,532,372,516,294,475,288,376,181,371,178,457,194,591

#========================end kitchen


  deck: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:mypassword@192.168.1.49:10554/udp/av0_0 # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -timeout 5000000 -use_wallclock_as_timestamps 1 -analyzeduration 5000000 -probesize 5000000
    zones:
        deck_area:
          coordinates: 434,720,419,361,880,286,1014,266,1244,212,1280,231,1280,720
        yard:
          coordinates: 234,547,134,510,125,433,458,420,555,476

    motion:
      mask:
        - 1280,0,1022,0,1027,303,814,327,562,311,142,155,0,720,0,0
    rtmp:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects 
      events:
        required_zones:
          - deck_area
        retain:
          mode: active_objects
          default: 7
    snapshots:
      enabled: true
      required_zones:
          - deck_area
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
    

  downstairs: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:mypassword@192.168.1.105:554/live # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
      
    zones:
      backdoor:
        coordinates: 712,232,627,232,594,0,677,0
      stairs:
        coordinates: 229,331,314,243,285,56,198,91
    motion:
      mask:
        - 1280,0,1280,419,982,158,960,0
        - 259,284,172,442,181,720,529,720,626,720,637,648,690,594,747,498,767,399,769,310,624,246,519,193,354,217
    rtmp:
      enabled: true
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects 
      events:
        required_zones:
          - backdoor
          - stairs
        retain:
          mode: active_objects
          default: 7
    snapshots:
      enabled: true
      required_zones:
          - backdoor
          - stairs
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
      filters:
        person:
          threshold: 0.8
      mask:
        - 259,284,172,442,181,720,529,720,626,720,637,648,690,594,747,498,767,399,769,310,624,246,519,193,354,217
        - 1280,0,1280,281,1280,720,997,720,846,181,750,177,680,0

objects:
# Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  filters:
    person:
      threshold: 0.8

     
    
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous


ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -an
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: -hwaccel auto
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args


detectors:
  coral:
    type: edgetpu
    device: usb
  cpu0:
    type: cpu
    num_threads: 2
  cpu1:
    type: cpu
    num_threads: 2
  cpu2:
    type: cpu
    num_threads: 2
  cpu3:
    type: cpu
    num_threads: 2
  cpu4:
    type: cpu
    num_threads: 2
  cpu5:
    type: cpu
    num_threads: 2
  cpu6:
    type: cpu
    num_threads: 2
  cpu7:
    type: cpu
    num_threads: 2
    
    
live:
  quality: 4
  height: 1080

database:
# The path to store the SQLite DB (default: shown below)
  path: /frigate/db/frigate.db

timestamp_style:
  position: "br"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%Y-%m-%d %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  effect: solid
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe version N-105890-g5cd8eb2aef-20220310 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220310
  libavutil      57. 22.100 / 57. 22.100
  libavcodec     59. 22.100 / 59. 22.100
  libavformat    59. 17.103 / 59. 17.103
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 27.100 /  8. 27.100
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
Input #0, rtsp, from 'rtsp://192.168.1.119:554/11':
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 5 fps, 5 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{
  "backyard": {
    "camera_fps": 5,
    "capture_pid": 263,
    "detection_fps": 0,
    "pid": 252,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "deck": {
    "camera_fps": 5.6,
    "capture_pid": 272,
    "detection_fps": 4.1,
    "pid": 255,
    "process_fps": 5.2,
    "skipped_fps": 0
  },
  "detection_fps": 4.1,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 11.48,
      "pid": 224
    },
    "cpu0": {
      "detection_start": 0,
      "inference_speed": 119.14,
      "pid": 226
    },
    "cpu1": {
      "detection_start": 1663078035.683989,
      "inference_speed": 115.54,
      "pid": 228
    },
    "cpu2": {
      "detection_start": 0,
      "inference_speed": 119.43,
      "pid": 232
    },
    "cpu3": {
      "detection_start": 0,
      "inference_speed": 120.17,
      "pid": 235
    },
    "cpu4": {
      "detection_start": 0,
      "inference_speed": 122.17,
      "pid": 237
    },
    "cpu5": {
      "detection_start": 0,
      "inference_speed": 117.83,
      "pid": 239
    },
    "cpu6": {
      "detection_start": 0,
      "inference_speed": 118.19,
      "pid": 241
    },
    "cpu7": {
      "detection_start": 0,
      "inference_speed": 116.25,
      "pid": 243
    }
  },
  "doorbell": {
    "camera_fps": 5,
    "capture_pid": 259,
    "detection_fps": 0,
    "pid": 249,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "downstairs": {
    "camera_fps": 5.1,
    "capture_pid": 278,
    "detection_fps": 0,
    "pid": 257,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "garage": {
    "camera_fps": 5,
    "capture_pid": 262,
    "detection_fps": 0,
    "pid": 251,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "kitchen": {
    "camera_fps": 5.1,
    "capture_pid": 268,
    "detection_fps": 0,
    "pid": 254,
    "process_fps": 5.1,
    "skipped_fps": 0
  },
  "service": {
    "latest_version": "0.10.1",
    "storage": {
      "/dev/shm": {
        "free": 120.1,
        "mount_type": "tmpfs",
        "total": 134.2,
        "used": 14.1
      },
      "/media/frigate/clips": {
        "free": 4463210.3,
        "mount_type": "nfs4",
        "total": 15736650.1,
        "used": 11273439.8
      },
      "/media/frigate/recordings": {
        "free": 4463210.3,
        "mount_type": "nfs4",
        "total": 15736650.1,
        "used": 11273439.8
      },
      "/tmp/cache": {
        "free": 4163,
        "mount_type": "tmpfs",
        "total": 4168.9,
        "used": 5.9
      }
    },
    "temperatures": {},
    "uptime": 3662,
    "version": "0.11.0-c461c9e"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Wyzecam v2, Vstarcam ??, ANRAN B04

### Any other information that may be helpful

Hardware: Khadas VIM4 box, 64 bit UBUNTU os
(excellent performance) 
Without a TPU: inference speed ~120/cpu * core (8)
With TPU: 12.6
