### ISSUE TITLE
Support / Provide include files to simplify advance configuration

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3837]
Right now there are a lot of FFMPEG settings to support server acceleration and to FIX specific camera issues however many of these will be common to large groups of users.

Home assistant and a lot of other YAML configured projects use the idea of importing include files for simplifying the main config and also for storing secrets etc.

What I would propose is to:

1. support user made include files or document it if already possible.
2. Bundle / include a library of common include files (with each frigate release) for Server HW / Camera HW specific settings..

IE instead of depending on documentation for Intel support

Change this:
```
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```
to 

```
ffmpeg:
  hwaccel_args:  !include global_hwaccel_args_intel_7thGen_or_less.yaml
```

Instead of a large FFMPEG block in a camera section.

```
 reolink:
    ffmpeg:
      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
```

to

```
 reolink:
    ffmpeg: !include camera_ffmpeg_reolink_generic.yaml
```

If the include files where maintained with the releases it would help make upgrades easier going forward, and would make the config file a bit less lengthy.

Documentation would also possibly need less updating if it just generally referred to looking at the include library for matching configurations.

Using include files in the camera section in general would be very helpful. Many users will have the same over all settings for several cameras so being able to use includes would clean up these sections.

**Comment by NickM-27** [comment]
Thanks, let me know if you disagree but I'm considering this a duplicate of https://github.com/blakeblackshear/frigate/issues/3429

As it's a similar approach to the same problem and more likely to be how we approach it.

**Comment by bagobones** [comment]
Ya same idea but my version is more generic and also leaves it open for the user to nest / leverage includes like Home assistant does. I am sort of asking for two things.. presets AND the ability to use includes as a user.

For example if I had includes the same way as in HA I would probably move ALL of my individual cameras out as includes to keep the primary config nice and short.

**Comment by bagobones** [comment]
If Frigate config ultimately is going to move to the UI at some point then I probably don't care as much as to how big and monolithic the config file becomes but at the moment I have a mish mash of brands of cameras with each having unique quarks to set so the config file grows rather quickly.

If using it as a HASS addon has a limitation of exposing only 1 config file then I guess that is just a limitation for users using it as a HASS addon? I don't see how this would break that.

**Comment by NickM-27** [comment]
> If Frigate config ultimately is going to move to the UI at some point then I probably don't care as much as to how big and monolithic the config file becomes but at the moment I have a mish mash of brands of cameras with each having unique quarks to set so the config file grows rather quickly.

Setup via UI is the ultimate goal. In my personal opinion time spent in making the config file cleaner is better spent adding UI configuration. See  #3587 

> If using it as a HASS addon has a limitation of exposing only 1 config file then I guess that is just a limitation for users using it as a HASS addon?

More config files could be exposed but it gets complicated quickly because we either have to give the container access to the entire `/config` directory (security implications) or like now we only have access to `/config/frigate.yml`

> I don't see how this would break that.

The problem isn't that something would break, the problem is the amount of users that would try it despite the docs saying it doesn't work and the time that we would have to spend supporting it by explaining that fact.

**Comment by bagobones** [comment]
> More config files could be exposed but it gets complicated quickly because we either have to give the container access to the entire `/config` directory (security implications) or like now we only have access to `/config/frigate.yml`

Maybe I am not understanding this but since this is all based on docker is this not easily fixed by moving the config file or the includes into their own path / folder on the host and mappings that folder for that use?/config/includes but only includes is mapped with folder access? 

Also going back to presets instead of !include you go !preset and use a named preset and !preset just maps to a folder in the image.

End of the day these are just ideas.

Looking at my current config I would love to take this:

```
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.103.8:554
          roles:
            - record
            - rtmp
        - path: rtsp://admin:password@192.168.103.8:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      threshold: 30
      mask:
        - 0,30,640,31,640,0,0,0
        - 0,442,162,403,254,409,294,451,412,451,531,428,598,406,594,248,0,249
        - 640,296,640,133,568,131,566,300
    zones:
      front_steps:
        coordinates: 227,480,222,402,158,396,0,439,0,480
        objects:
          - person
      front_deck:
        coordinates: 640,480,640,418,602,410,447,444,289,458,295,480
        objects:
          - person
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        required_zones:
          - front_steps
          - front_deck
  garage_front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:passwor@192.168.103.3:554/
          roles:
            - record
            - rtmp
        - path: rtsp://admin:passwor@192.168.103.3:554/h264Preview_01_sub
          roles:
            - detect
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - car
    motion:
      threshold: 35
      mask:
        - 640,360,400,360,398,334,640,328
        - 149,83,21,0,640,0,640,300
    zones:
      front_steps:
        coordinates: 124,70,127,135,163,135,213,162,215,179,154,193,0,124,0,0,30,0
        objects:
          - person
      parking_spot:
        coordinates: 0,360,0,262,262,159,640,291,640,360
        objects:
          - person
          - car
      mailbox:
        coordinates: 66,158,72,221,0,244,0,133
        objects:
          - person
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        required_zones:
          - front_steps
          - parking_spot
```

And turn it into

```
cameras:
  doorbell: !include camera_doorbell.yaml
  garage_front: !include camera_garage_front.yaml
```

Having each camera as a file would greatly simplify version control and make cloning, swapping back and forth between versions of a config, much easier than tracking a DIFF in the main config file.
