### ISSUE TITLE
Lovelace Thumbnails not working

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#3843]
### Describe the problem you are having

After the latest update the thubnails in the lovelace are not working. i deleted and re-installed HACS and the integration. but no fix. Any ideas?

<img width="787" alt="image" src="https://user-images.githubusercontent.com/30929896/190399268-6c458829-df7b-40bf-a199-608fbe1d04f8.png">

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/30929896/190399328-02a9b3e6-b839-417d-a2fa-7394cfec038d.png">

### Version

0.10.1-83481AF

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb'
    num_threads: 2
mqtt:
  host: 192.168.178.125
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user:
  password: 
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m

cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask: >-
        -0,0,1920,0,1920,1080,1490,1080,1659,694,690,270,121,417,345,1080,0,1080
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask: >-
            -2,1,1920,0,1920,1080,1490,1080,1678,653,547,227,533,73,354,86,370,292,116,340,285,1012,680,1014,678,1080,0,1080
    zones:
      car:
        coordinates: 343,1058,1477,1080,1654,683,776,252,123,394
    record:
      enabled: true
      retain: 
        days: 30
        mode: motion 
      events:
        retain:
          default: 30
          mode: active_objects

  Package:
    ffmpeg:
      inputs:
        - path: 
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,1080,1920,1080,1350,547,1408,891,1081,899,1105,544,1307,523,1920,1080,1920,0,0,0


    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
        - cat
    zones:
      box:
        coordinates: 1128,888,1408,891,1356,564,1073,535
    record:
      enabled: true
      retain: 
        days: 30
        mode: motion 
      events:
        retain:
          default: 30
          mode: active_objects

database:
  path: /media/frigate/clips/frigate.db
logger:
  default: info
  logs:
    frigate.mqtt: error
```

### Relevant log output

```shell
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:84
Integration: HTTP (documentation, issues)
First occurred: 14:01:11 (356 occurrences)
Last logged: 14:06:58

Login attempt or request with invalid authentication from Emres-MacBook-Air.fritz.box (192.168.178.140). Requested URL: '/api/frigate/frigate/thumbnail/1663156822.045811-ps6n8w'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36)
Login attempt or request with invalid authentication from Emres-MacBook-Air.fritz.box (192.168.178.140). Requested URL: '/api/frigate/frigate/thumbnail/1663156715.295886-wvmbxe'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36)
Login attempt or request with invalid authentication from Emres-MacBook-Air.fritz.box (192.168.178.140). Requested URL: '/api/frigate/frigate/thumbnail/1663096926.478666-5bl708'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36)
Login attempt or request with invalid authentication from Emres-MacBook-Air.fritz.box (192.168.178.140). Requested URL: '/api/frigate/frigate/thumbnail/1663079797.578253-z5tvhh'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36)
Login attempt or request with invalid authentication from Emres-MacBook-Air.fritz.box (192.168.178.140). Requested URL: '/api/frigate/frigate/thumbnail/1662977537.395232-tlarxz'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
