### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by powellelectric** [blakeblackshear/frigate#3854]
### Describe the problem you are having

Is Coral installed/configured properly?

Running Docker on Ubuntu Server 20.04 on Mini PC Windows 11 Pro GK41 Mini Desktop with Google Coral USB Accelerator. 
Four cameras:

- Dahua IPC-T5442TM-AS-LED-2.8mm-S2
- Dahua IPC-T5442TM-AS 2.8mm IR
- Amcrest IP8M-2496EW-V2
- Reolink RLC-811A

Utility top shows 25-30% CPU
Utility sensors shows a four cores at 50.0°C

### Version

0.10.1-83481AF

### Frigate config file

```yaml
larry@frigate:/opt/frigate$ cat tmp
mqtt:
  host: 192.168.10.21
  user: homeassistant
  password: xyz

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /opt/frigate/frigate.db

logger:
  default: info
  logs:
    frigate.event: debug

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000

cameras:
  adu:
    ffmpeg:
      inputs:
        - path: rtsp://user:pwd@192.168.10.201:554
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution

  porch:
    ffmpeg:
      inputs:
        - path: rtsp://user:pwd@192.168.10.202:554
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution

  front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pwd@192.168.10.203:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pwd@192.168.10.203:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

  driveway: # <------ Name the camera
    ffmpeg:
      input_args: 
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.10.204/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pwd
          roles:
            - record
            - rtmp
        - path: http://192.168.10.204/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pwd
          roles:
            - detect
    detect:
      width: 896 
      height: 672
      fps: 7
```

### Relevant log output

```shell
Unrelated error:

[2022-09-16 08:04:56] ffmpeg.driveway.record_rtmp    ERROR   : http://192.168.10.204/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pwd: could not find codec parameters
[2022-09-16 08:04:56] watchdog.driveway              INFO    : Terminating the existing ffmpeg process...
[2022-09-16 08:04:56] watchdog.driveway              INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
ffprobe rtsp://user:pwd@192.168.10.204
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://user:pwd@192.168.10.204':
  Metadata:
    title           : Session streamed by "preview"
    comment         : 
  Duration: N/A, start: 0.000438, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25.08 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-811A

**Comment by NickM-27** [comment]
If you have 

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
```

and frigate doesn't immediately stop, then the coral is working as expected.

**Comment by NickM-27** [comment]
Is there a reason you think it's not working correctly? If it has to do with CPU usage, that's probably because you don't have hwaccel setup

**Comment by powellelectric** [comment]
Nick, can you recommend settings for hwaccel?

**Comment by NickM-27** [comment]
> Nick, can you recommend settings for hwaccel?

What CPU do you have?

**Comment by powellelectric** [comment]
Intel Celeron J4125 processor,2.00 GHz -2.70 GHz processor

**Comment by NickM-27** [comment]
> Intel Celeron J4125 processor,2.00 GHz -2.70 GHz processor

You'll need to set

`LIBVA_DRIVER_NAME: i965` as an environment variable in your docker compose file and then use 

```yaml
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```
