### ISSUE TITLE
[Support]: Frigate keeps sending person detections long after he has left

### ISSUE THREAD

**Issue by jentstemmerman** [blakeblackshear/frigate#3857]
### Describe the problem you are having

Occasionally frigate will (correctly) identify a person on my driveway and send a MQTT event but then get in a mode in which the same event keeps being sent, with exactly the same id and snapshot time, every few minutes. There is no other person in sight 
frame_time and motionless_time is different. 

### Version

Debug 0.10.1-83481af

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "achterdeur": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://jents:Lampekap15@192.169.2.20:554/s0",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": "-f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://jents:Lampekap15@192.169.2.20:554/s0 -c copy -f flv rtmp://127.0.0.1/live/achterdeur -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "892,465,784,562,0,1026,0,671,0,369,0,322,0,0,112,0,1152,0,1043,476",
          "1920,204,1346,91,1354,169,1611,257,1610,418,1920,544"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "achterdeur",
      "objects": {
        "filters": {
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "horse": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "horse",
          "car",
          "dog"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "cat"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "achterdeur_buitenzeurende_kat_zone",
            "achterdeur_buiten_zone"
          ],
          "retain": {
            "default": 1,
            "mode": "motion",
            "objects": {
              "person": 5
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {
            "cat": 4,
            "person": 15
          }
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "achterdeur_buiten_zone": {
          "coordinates": "1313,674,1327,0,548,100,294,347,97,400,124,530,0,710,0,1080,391,1080,1711,1080,1208,732",
          "filters": {
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.8
            }
          },
          "objects": [
            "person",
            "cat",
            "dog"
          ]
        },
        "achterdeur_buitenzeurende_kat_zone": {
          "coordinates": "1324,648,1079,588,1114,798,1710,1080,1920,1080,1920,1028",
          "filters": {
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 200,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "cat",
            "person",
            "dog"
          ]
        }
      }
    },
    "achtertuin": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://jents:Lampekap15@192.169.2.22:554/s0",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": "-f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://jents:Lampekap15@192.169.2.22:554/s0 -c copy -f flv rtmp://127.0.0.1/live/achtertuin -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "improve_contrast": false,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "achtertuin",
      "objects": {
        "filters": {
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "horse": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "horse",
          "car",
          "dog"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "car",
            "dog",
            "horse"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "achtertuin_zone"
          ],
          "retain": {
            "default": 1,
            "mode": "motion",
            "objects": {
              "dog": 30,
              "horse": 30,
              "person": 15
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "achtertuin_zone": {
          "coordinates": "255,922,0,872,0,648,375,442,582,472,648,473,656,405,720,398,779,406,892,422,898,487,1004,489,1055,507,1080,506,1108,499,1224,493,1284,438,1386,447,1473,470,1539,541,1595,560,1656,569,1708,564,1761,520,1920,564,1920,1080,936,1080",
          "filters": {
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "dog": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "horse": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.8
            }
          },
          "objects": [
            "cat",
            "person",
            "dog",
            "horse"
          ]
        }
      }
    },
    "bureau": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://jents:Lampekap15@192.169.1.47:554/s0",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": "-f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://jents:Lampekap15@192.169.1.47:554/s0 -c copy -f flv rtmp://127.0.0.1/live/bureau -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "1920,0,789,213,604,266,101,399,32,420,0,436,0,0"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "bureau",
      "objects": {
        "filters": {
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "horse": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "horse",
          "car",
          "dog"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "oprit_zone": {
          "coordinates": "395,540,1920,1080,1920,504,1920,1080,1920,1080,1920,430,827,224,227,367",
          "filters": {
            "car": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "cat",
            "person",
            "car"
          ]
        },
        "voordeur_zone": {
          "coordinates": "425,525,1028,1059,873,1080,780,1080,684,1080,0,1080,0,518,309,423",
          "filters": {
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "cat",
            "person"
          ]
        }
      }
    },
    "voortuin": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://jents:Lampekap15@192.169.2.21:554/s0",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": "-f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy",
          "rtmp": "-c copy -f flv"
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://jents:Lampekap15@192.169.2.21:554/s0 -c copy -f flv rtmp://127.0.0.1/live/voortuin -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "1920,0,1024,0,0,0,0,1019,231,782,564,557,805,536,1605,427,1920,377"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "voortuin",
      "objects": {
        "filters": {
          "car": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "horse": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "cat",
          "horse",
          "car",
          "dog"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "car"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "voortuin_zone",
            "oprit_zone"
          ],
          "retain": {
            "default": 1,
            "mode": "motion",
            "objects": {
              "person": 15
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {
        "oprit_zone": {
          "coordinates": "1414,623,1580,657,1732,678,1896,603,1920,580,1845,570,1732,559",
          "filters": {
            "car": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "cat",
            "person",
            "car"
          ]
        },
        "voordeur_zone": {
          "coordinates": "1648,1027,1920,816,1920,1080,1823,1080",
          "filters": {
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "cat",
            "person"
          ]
        },
        "voortuin_zone": {
          "coordinates": "480,908,290,1080,1808,1080,1634,1032,1920,803,1920,699,1734,668,1569,646,1414,623,975,713,701,766,444,859",
          "filters": {
            "cat": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            },
            "person": {
              "mask": null,
              "max_area": 100000,
              "min_area": 500,
              "min_score": 0.5,
              "threshold": 0.7
            }
          },
          "objects": [
            "cat",
            "person"
          ]
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 1080,
    "max_disappeared": 25,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1920
  },
  "detectors": {
    "coral_pci_1": {
      "device": "pci",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": "-hide_banner -loglevel warning",
    "hwaccel_args": [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1",
    "output_args": {
      "detect": "-f rawvideo -pix_fmt yuv420p",
      "record": "-f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy",
      "rtmp": "-c copy -f flv"
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.169.1.48",
    "password": "Lampekap5",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "jents"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person",
      "cat",
      "horse",
      "car",
      "dog"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
detection of a person on my driveway ( he left already )

object
before: object
id: "1663346474.819631-1cfsuw"
camera: "bureau"
frame_time: 1663348905.438456
snapshot_time: 1663346475.222704
label: "person"
top_score: 0.841796875
false_positive: false
start_time: 1663346474.819631
end_time: null
score: 0.71484375
box: array[4]
area: 8820
region: array[4]
stationary: true
motionless_count: 12112
position_changes: 1
current_zones: array[0]
entered_zones: array[1]
has_clip: false
has_snapshot: true
after: object
id: "1663346474.819631-1cfsuw"
camera: "bureau"
frame_time: 1663348965.837079
snapshot_time: 1663346475.222704
label: "person"
top_score: 0.841796875
false_positive: false
start_time: 1663346474.819631
end_time: null
score: 0.71484375
box: array[4]
area: 8820
region: array[4]
stationary: true
motionless_count: 12414
position_changes: 1
current_zones: array[0]
entered_zones: array[1]
has_clip: false
has_snapshot: true
type: "update"

detection of a person on my driveway again ( he is still not there )
object
before: object
id: "1663346474.819631-1cfsuw"
camera: "bureau"
frame_time: 1663349026.23978
snapshot_time: 1663346475.222704
label: "person"
top_score: 0.841796875
false_positive: false
start_time: 1663346474.819631
end_time: null
score: 0.71484375
box: array[4]
area: 8820
region: array[4]
stationary: true
motionless_count: 12716
position_changes: 1
current_zones: array[0]
entered_zones: array[1]
has_clip: false
has_snapshot: true
after: object
id: "1663346474.819631-1cfsuw"
camera: "bureau"
frame_time: 1663349086.635461
snapshot_time: 1663346475.222704
label: "person"
top_score: 0.841796875
false_positive: false
start_time: 1663346474.819631
end_time: null
score: 0.71484375
box: array[4]
area: 8820
region: array[4]
stationary: true
motionless_count: 13018
position_changes: 1
current_zones: array[0]
entered_zones: array[1]
has_clip: false
has_snapshot: true
type: "update"
```

### FFprobe output from your camera

```shell
do I need to run this in the container ? 
root@ad4b95b18128:/unifi# ffprobe 192.169.1.47
bash: ffprobe: command not found
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Unifi G3 Flex
