### ISSUE TITLE
[Config Support]: Only person detected

### ISSUE THREAD

**Issue by erte1** [blakeblackshear/frigate#3861]
### Describe the problem you are having

Hi All, hoping for some basic guidance. The following config is only capturing person events. cat, car, dog detection is not recording and when I view the debug screen, only person is showing as detected. Any helpful tips?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.x
  user: xxx
  password: xxx

# ffmpeg:
 # hwaccel_args:
 #   - -c:v
 #   - h264_v4l2m2m

cameras:
  FrontDoor: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
      inputs:
        - path: rtsp://xxxx:xxxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            - rtmp
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 526 # <---- update for your camera's resolution
      fps: 5

  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
      inputs:
        - path: rtsp://xxxx:xxxxx@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            - rtmp
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5

record:
  enabled: true
  retain:
   days: 2
   mode: motion
  events:
    retain:
      default: 5
      mode: active_objects
      objects:
        cat: 1
        car: 5
        dog: 2
        person: 5

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
```

### Relevant log output

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You haven't set what objects to track. You need to define what objects you want tracked. 

```yaml
objects:
  track:
    - person
    - dog
```
