### ISSUE TITLE
[Camera Support]: One camera periodically stops streaming

### ISSUE THREAD

**Issue by mike-lloyd03** [blakeblackshear/frigate#3863]
### Describe the problem you are having

I have three RLC-410-5MP cams configured according to [this](https://docs.frigate.video/configuration/camera_specific/#reolink-410520-possibly-others). One of them will randomly stop recording and restreaming RTMP a few hours after restarting the Frigate container. Logs show that Frigate stops receiving frames and ends up killing ffmpeg due to `Packet mismatch`. Restarting the container again fixes the problem for a few hours. I would think that if the ffmpeg process crashes for a camera, it would restart on it's own but that doesn't appear to be the case.

### Version

0.10.1-83481af

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.0.100
  port: 1883
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

cameras:
  Driveway:
    ffmpeg:
      inputs:
        - path: http://192.168.0.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
        - path: http://192.168.0.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - car
    motion:
      mask:
        - 0,0,640,0,640,114,574,107,491,73,309,70,0,141
    zones:
      parking_area:
        coordinates: 345,480,0,480,0,174,270,113,335,143,268,177,547,302
        objects:
          - person
      driveway:
        coordinates: 289,170,490,238,614,98,546,82
        objects:
          - person
          - car
    record:
      events:
        required_zones:
          - parking_area
          - driveway

  FrontDoor:
    ffmpeg:
      inputs:
        - path: http://192.168.0.129/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
        - path: http://192.168.0.129/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
    motion:
      mask:
        - 640,0,640,179,534,171,372,123,232,82,184,0
      
  Backyard:
    ffmpeg:
      inputs:
        - path: http://192.168.0.102/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
        - path: http://192.168.0.102/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USER}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 0,480,640,480,640,55,551,53,422,89,204,90,0,156
        person:
          mask:
            - 640,0,0,0,0,165,222,83,640,108


ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -rw_timeout
    - "5000000"
  output_args:
    record:
      - -f
      - segment
      - -segment_time
      - 10
      - -segment_format
      - mp4
      - -reset_timestamps
      - 1
      - -strftime
      - 1
      - -c:v
      - copy
      - -c:a
      - aac

record:
  enabled: true
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 3 # seconds
    post_capture: 5 # seconds
    retain:
      default: 10 # days
```

### Relevant log output

```shell
frigate-app-1  | [2022-09-15 20:32:57] watchdog.FrontDoor             INFO    : No frames received from FrontDoor in 20 seconds. Exiting ffmpeg...
frigate-app-1  | [2022-09-15 20:32:57] watchdog.FrontDoor             INFO    : Waiting for ffmpeg to exit gracefully...
frigate-app-1  | [2022-09-15 20:33:27] watchdog.FrontDoor             INFO    : FFmpeg didnt exit. Force killing...
frigate-app-1  | [2022-09-15 20:33:27] frigate.video                  ERROR   : FrontDoor: Unable to read frames from ffmpeg process.
frigate-app-1  | [2022-09-15 20:33:27] frigate.video                  ERROR   : FrontDoor: ffmpeg process is not running. exiting capture thread...
frigate-app-1  | [2022-09-15 20:33:37] watchdog.FrontDoor             ERROR   : Ffmpeg process crashed unexpectedly for FrontDoor.
frigate-app-1  | [2022-09-15 20:33:37] watchdog.FrontDoor             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 407109550 11 -1287954227
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -263583646 131663 -1287822564
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -662417705 131663 -1287690901
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 767791621 131663 -1287559238
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1479861563 131663 -1287427575
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -899556662 131663 -1287295912
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1095741555 588367 -1286707545
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -207948141 131663 -1286575882
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 1291483164 369999 -1286205883
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1847956162 131663 -1286074220
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1880083866 131663 -1285942557
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1567341496 131663 -1285810894
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 991009837 131663 -1285679231
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1923138883 275023 -1285404208
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -2042347885 131663 -1285272545
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -1833884821 131663 -1285140882
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -360121069 131663 -1285009219
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 379778574 317007 -1284692212
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 1747622716 131663 -1284560549
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 1616158812 131663 -1284428886
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 458099688 131663 -1284297223
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch -251971672 131663 -1284165560
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 303287015 131663 -1284033897
frigate-app-1  | [2022-09-15 20:33:37] ffmpeg.FrontDoor.detect        ERROR   : [flv @ 0x560cb7858940] Packet mismatch 1192637846 21583 -1284012314
```

### FFprobe output from your camera

```shell
Low res stream:

ffprobe version n5.1.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flv, from 'http://192.168.0.129/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<USER>&password=<PASS>':
  Metadata:
    displayWidth    : 896
    displayHeight   : 672
  Duration: 00:00:00.00, start: -0.007000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x672, 19 fps, 30 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

High res stream:

ffprobe version n5.1.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flv, from 'http://192.168.0.129/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<USER>&password=<PASS>':
  Metadata:
    displayWidth    : 2560
    displayHeight   : 1920
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 17 fps, 30 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{
  "Backyard": {
    "camera_fps": 7.1,
    "capture_pid": 245,
    "detection_fps": 0.0,
    "pid": 235,
    "process_fps": 7.1,
    "skipped_fps": 0.0
  },
  "Driveway": {
    "camera_fps": 7.0,
    "capture_pid": 238,
    "detection_fps": 0.0,
    "pid": 231,
    "process_fps": 7.0,
    "skipped_fps": 0.0
  },
  "FrontDoor": {
    "camera_fps": 7.1,
    "capture_pid": 243,
    "detection_fps": 7.7,
    "pid": 234,
    "process_fps": 7.1,
    "skipped_fps": 0.0
  },
  "detection_fps": 7.7,
  "detectors": {
    "coral": { "detection_start": 0.0, "inference_speed": 11.69, "pid": 225 }
  },
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 265.6,
        "mount_type": "tmpfs",
        "total": 268.4,
        "used": 2.8
      },
      "/media/frigate/clips": {
        "free": 1384801.6,
        "mount_type": "nfs4",
        "total": 1915211.9,
        "used": 530410.2
      },
      "/media/frigate/recordings": {
        "free": 1384801.6,
        "mount_type": "nfs4",
        "total": 1915211.9,
        "used": 530410.2
      },
      "/tmp/cache": {
        "free": 998.2,
        "mount_type": "tmpfs",
        "total": 1000.0,
        "used": 1.8
      }
    },
    "temperatures": {},
    "uptime": 2695,
    "version": "0.10.1-83481af"
  }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-410-5MP

**Comment by NickM-27** [comment]
Frigate does restart the ffmpeg process when it stops, however we have seen this issue with Reolinks before. I believe newer Reolinks have improved this somewhat but unfortunately the 410 is not being supported at all anymore.

See [#2886](https://github.com/blakeblackshear/frigate/issues/2886#issuecomment-1056865797) for more info on this issue, but for now I am going to mark this as a duplicate and will close unless you disagree.

> I have seen this issue with Reolinks several times when people were using the RTMP streams. This is the first time I have seen it with the http streams. Basically the camera stops sending data, but doesn't disconnect. This causes ffmpeg to think more data is coming. The rw_timeout parameter in the input args is supposed to fix it, but it's not for some reason.

I might also recommend trying 0.11 RC3 (be sure to read the breaking changes), as that has a newer and different ffmpeg build that may handle this better.

**Comment by mike-lloyd03** [comment]
Okay thanks for the quick feedback. I searched but didn't find the thread you mentioned. I'll give 0.11 a try and report back.

**Comment by bagobones** [comment]
I am running two older 410W units I am using the rtmp streams with the following parameters. under beta 11.

Camera details:
Model: RLC-410W
Build No.: build 20121102
Hardware No.: IPC_51316M
Config Version: v3.0.0.0
Firmware Version: v3.0.0.136_20121102
Details: IPC_51316MS07E1W31100000001

Global acceleration for my Intel CPU

```
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

```
Per camera input_args , output_args and rtmp for beta 11
```
  backyard:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: rtmp://192.168.103.2/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=[password]
          roles:
            - record
            - rtmp
        - path: rtmp://192.168.103.2/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=[password]
          roles:
            - detect
```
