### ISSUE TITLE
[Support]: RTMP fps customisation

### ISSUE THREAD

**Issue by weitheng** [blakeblackshear/frigate#3865]
### Describe the problem you are having

Is there any way to configure custom fps for rtmp stream? If so, where do I set it?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.0.XX                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: XXX
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: XXXX
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 1

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 4
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv

cameras:
  Gate:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            - detect
        - path: rtsp://
          roles:
            - record
            - rtmp
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: true
    record:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
        max_seconds: 240
        # Optional: Number of seconds before the event to include in the clips (default: shown below)
        pre_capture: 3
        # Optional: Number of seconds after the event to include in the clips (default: shown below)
        post_capture: 4
        # Optional: Objects to save clips for. (default: all tracked objects)
        objects:
          - person
          - car
          - motorcycle
          - bicycle
          - bus
          - dog
          - cat
        # Optional: Camera override for retention settings (default: global values)
        retain:
          # Required: Default retention days (default: shown below)
          default: 1
          mode: active_objects
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
#      # Optional: height to resize the snapshot to (default: original size)
#      height: 175
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
        # Optional: Per object retention days
        objects:
          person: 1
          car: 1
          motorcycle: 1
          bus: 1
          bicycle: 1
    objects:
      track:
        - person
        - car
        - motorcycle
        - bus
        - bicycle
        - dog
        - cat
      mask: 179,55,171,0,302,0,704,0,704,457,428,225,272,157,218,89,207,57
      filters:
        person:
          threshold: 0.65
        car:
          threshold: 0.65
    motion:
      mask:
        - 179,55,171,0,302,0,704,0,704,457,428,225,272,157,218,89,207,57
    detect:
      width: 704
      height: 576
      fps: 5
      stationary:
        # Optional: Frequency for running detection on stationary objects (default: shown below)
        # When set to 0, object detection will never be run on stationary objects. If set to 10,
        # it will be run on every 10th frame.
        interval: 0
        # Optional: Number of frames without a position change for an object to be considered
        # stationary (default: 10x the frame rate or 10s)
        threshold: 50
        # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
        # This can help with false positives for objects that should only be stationary for a limited amount of time.
        # It can also be used to disable stationary object tracking. For example, you may want to set a value for person,
        # but leave car at the default.
        max_frames:
          # Optional: Default for all object types (default: not set, track forever)
          default: 3000
          # Optional: Object specific values
          objects:
            person: 1000
detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
#  cpu3:
#    type: cpu
#  cpu4:
#    type: cpu
  coral:
    type: edgetpu
    device: usb

# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320
```


### Relevant log output

```shell
N/A
```


### FFprobe output from your camera

```shell
N/A
```


### Frigate stats

```json
N/A
```


### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dhaka

### Any other information that may be helpful

_No response_
