### ISSUE TITLE
[HW Accel Support]: Nothing urgent whatsoever... 

### ISSUE THREAD

**Issue by heebo1974** [blakeblackshear/frigate#3912]
### Describe the problem you are having

Basically I don't have any problem I guess.

I just want to know what is the best hwaccel option:

1. hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
2. hwaccel_args: -c:v h264_qsv
3. hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128

All these works with rig Dell-OptiPlex-3040M-DM-i3-6100T-8-120SSD which is basically i3 intel gen 6 Skylake with HD Graphics 530. 

Why it is working with qsv too? I have HAOS installed so I don't have access eg. intel-gpu-top so I could compare with that.
Any ideas how to get intel-gpu-top installed ? Maybe future in the frigate docker ?
I am not really sure that hwaccell is really working. I think that if I disable it in config I still get quite same results, because it is quite hard to just stare some htop if it is really different with those configs. Logs doesn't show much about hwaccell.

Any ideas ? 

### Version

0.11.0-3846A13

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.5
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: Henri
  password: xxxxxxxxxxxx

#environment_vars:
#  LIBVA_DRIVER_NAME: i965

birdseye:
   enabled: False

cameras:
  etupiha:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

#      hwaccel_args: -c:v h264_qsv
#      hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128

#      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1

      inputs:
        # High Resolution Stream
        - path: rtsp://xxxx:xxxx@192.168.0.200:554/stream1
          roles:
            - detect
            - rtmp
            - record
        # Low Resolution Stream
#        - path: rtsp://xxxx:xxxx@192.168.0.200:554/stream2
#          roles:
#            - detect

    detect:
      width: 2304 # 1920 2304
      height: 1296 # 1080 1296
      fps: 5
      stationary:
        interval: 0
        threshold: 50
      enabled: True

    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
        - bird
        - umbrella

      filters:
        person:
          threshold: 0.6
          min_area: 5000
          max_area: 170000
        car:
          threshold: 0.6
          min_area: 13000
          max_area: 100000
          mask: 0,0,2304,0,2304,1296,1146,1296,0,1296,955,359,953,545,1510,557,1520,413,956,376,0,1296 # 2304x1296
        cat:
          max_area: 50000

        umbrella:
          mask:
            - 2304,0,2304,396,962,366,956,455,0,454,0,0 # 2304x1296
            - 1039,735,1134,743,1126,677,1041,684 # 2304x1296

    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 15
        objects:
          person: 20

    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 15
          mode: active_objects

    motion:
      threshold: 29
      contour_area: 33
      mask:
        - 0,0,0,620,565,454,565,347,978,359,1613,394,2304,1296,2304,0 # 2304x1296

    zones:
      etupiha_oma:
        coordinates: 626,565,640,420,921,425,926,721,2304,740,2304,1296,0,1296,0,963 # 2304x1296
        filters:
          person:
            threshold: 0.72
```

### docker-compose file or Docker CLI command

```yaml
No idea what this is.
```

### Relevant log output

```shell
[2022-09-23 20:26:37] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-09-23 20:26:37] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-09-23 20:26:37] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-23 20:26:37] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-23 20:26:37] frigate.app                    INFO    : Output process started: 217
[2022-09-23 20:26:37] ws4py                          INFO    : Using epoll
[2022-09-23 20:26:37] detector.cpu                   INFO    : Starting detection process: 216
[2022-09-23 20:26:37] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-09-23 20:26:37] frigate.app                    INFO    : Camera processor started for etupiha: 222
[2022-09-23 20:26:37] frigate.app                    INFO    : Capture process started for etupiha: 224
[2022-09-23 20:26:38] ws4py                          INFO    : Using epoll
```

### FFprobe output from your camera

```shell
➜  config docker exec -it addon_ccab4aaf_frigate ffprobe rtsp://secret:verysecret@192.168.0.200:554/stream1
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55a3bacd0140] method DESCRIBE failed: 406 Not Acceptable
rtsp://secret:verysecret@192.168.0.200:554/stream1: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

TP-Link C310
