### ISSUE TITLE
[Support]: Installing problem with portainer

### ISSUE THREAD

**Issue by Kalougear** [blakeblackshear/frigate#3914]
### Describe the problem you are having

Hello guys,im trying to install frigate via docker,im doing it with portainer and my docker compose is this.

```yaml
frigate:
  container_name: frigate
  image: blakeblackshear/frigate:stable-amd64
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime
    - /home/sktech-server/frigate/config.yml:/config/config.yml
  ports:
    - 5000:5000
    - 1935:1935
  environment:
    FRIGATE_RTSP_PASSWORD: "password"
```

and i got this error but i cant find any info,im sure its a silly mistake im doing but i cant figure it out im a begginer at dockering

### Version

latest

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.107
  user: stefanos
  password: "@mousmoula@94"

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://fakeuser:fakepass@192.168.1.100:554/stream1
          roles:
            - rtmp
```

### Relevant log output

> Deployment error
> failed to deploy a stack: (root) Additional property frigate is not allowed

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo

**Comment by NickM-27** [comment]
Is that your entire config? This looks like a portainer error and I am not sure how that is supposed to work exactly.

**Comment by Kalougear** [comment]
Lighting reply NIckM-27! yes thats the entire config im just building it,you are correct it has to do with the portainer,i have followed this video to install it and i did exactly what he says,in fact the config is a copy with my paths. [](https://www.youtube.com/watch?v=qfchptEzqdo)

**Comment by NickM-27** [comment]
I notice it seems to be indented in the video but yours is not, perhaps that is an issue?

**Comment by idontcare99999** [comment]
Need the first two lines to look more like this and then indent the rest of the lines:

version: "3"
services:

**Comment by bagobones** [comment]
Try reformatting it more like this

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/sktech-server/frigate/config.yml:/config/config.yml
    environment:
      - FRIGATE_RTSP_PASSWORD=password
     ports:
      - "5000:5000"    
      - "1935:1935" # RTMP feeds
```
