### ISSUE TITLE
[EdgeTPU Support]: How to connect to docker image on QNAP Container Station

### ISSUE THREAD

**Issue by gadgetbazza** [blakeblackshear/frigate#3920]
### Describe the problem you are having

As a linux newbie (old school MS guy) I'm unable to determine how to connect the USB Coral through to my Frigate container.

To clarify I am using a QNAP NAS with Container Station which as far as I can tell is QNAP's kludgy wrapper UI around Docker.  Thus far I have discovered that there are a number of folders / files created for each container that I have on my QNAP and have located the one for the Frigate container.  In there I can see 3 json config files, which appear to contain similar data across the three.

I've googled around how to pass through the USB into Docker, but really not sure what I should add and how to make it persistent after a restart.

I have verified that the Coral is showing on the NAS bash using the command lsusb as below:

```
[~] # lsusb
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1005:b155 Apacer Technology, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

I've attached the 3 config files I found below in the hope that someone can confirm what I need to change to make the Coral visible.  I've tried connecting into the terminal of the frigate container and running the lsusb command, but the command isn't available.
[config.v2.json.txt](https://github.com/blakeblackshear/frigate/files/9637163/config.v2.json.txt)
[hostconfig.json.txt](https://github.com/blakeblackshear/frigate/files/9637164/hostconfig.json.txt)
[qnap.json.txt](https://github.com/blakeblackshear/frigate/files/9637165/qnap.json.txt)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.162
  user: user
  password: pass

detectors:
  cpu1:
    type: cpu
    num_threads: 3
# cpu2:
#   type: cpu
#   num_threads: 3

record:
  enabled: True
  retain:
    days: 21
  events:
    retain:
      default: 42

cameras:
  Gate-Door-Station: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.55:554/h264_stream # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://192.168.4.55:554/h264_stream # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      filters:
        person:
          mask:
            - 640,286,450,311,213,323,0,298,0,243,0,0,640,0
        dog:
          mask:
            - 640,286,450,311,213,323,0,298,0,243,0,0,640,0
        car:
          mask:
            - 640,286,450,311,213,323,0,298,0,243,0,0,640,0
      track:
        - person
        - dog
        - car
    motion:
      mask:
        - 640,286,450,311,213,323,0,298,0,243,0,0,640,0

  PondCam1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.36:554/user=user_password=f1shy_channel=1_stream=0.sdp?real_stream # <----- Update for your camera
          roles:
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 7

#  PondCam2: # <------ Name the camera
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.4.37:554/user=user_password=f1shy_channel=1_stream=0.sdp?real_stream # <----- Update for your camera
#          roles:
#            - detect
#            - rtmp
#        - path: rtsp://192.168.4.37:554/user=user_password=f1shy_channel=1_stream=0.sdp?real_stream # <----- Update for your camera
#          roles:
#            - record
#    rtmp:
#      enabled: True # <-- RTMP should be disabled if your stream is not H264
#    detect:
#      width: 720 # <---- update for your camera's resolution
#      height: 480 # <---- update for your camera's resolution
#    record:
#      enabled: True
#    snapshots:
#      enabled: True
#    objects:
#      track:
#        - person
#        - dog
#
  Dining-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.21/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.21/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,480,138,480,109,402,109,304,91,208,0,231

  Utility-Walkway-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.22/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.22/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

#   Lounge-Internal: # <------ Name the camera
#    ffmpeg:
#      inputs:
#        - path: rtsp://user:pass@192.168.4.23/rtsph264480p # <----- Update for your camera
#          roles:
#            - detect
#            - rtmp
#        - path: rtsp://user:pass@192.168.4.23/rtsph2641080p # <----- Update for your camera
#          roles:
#            - record
#    rtmp:
#      enabled: True # <-- RTMP should be disabled if your stream is not H264
#    detect:
#      width: 720 # <---- update for your camera's resolution
#      height: 480 # <---- update for your camera's resolution
#    record:
#      enabled: True
#    snapshots:
#      enabled: True
#    objects:
#      track:
#        - person
#        - dog

  Front-Door-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.24/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.24/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Lower-Patio-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.25/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.25/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Landing-Kids: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.26/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.26/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Landing-Master: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.27/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.27/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Front-Door-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.29/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.29/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
        - car

  Gates-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.30/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.30/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 720,0,720,125,672,139,571,114,292,100,254,132,0,107,0,0

  Lounge-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.31/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.31/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Dining-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.32/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.32/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,0,259,0,263,67,0,122
        - 460,163,396,169,326,167,323,99,415,97,433,70,461,71
        - 266,109,204,106,234,128,243,162,268,167
  Garage-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.33/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.33/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
        - car
    motion:
      mask:
        - 48,436,122,436,122,200,48,200
        - 720,131,640,96,398,41,399,0,720,0

  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.34/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.34/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 349,68,545,49,545,0,0,0,0,198
    objects:
      track:
        - person
        - dog
        - car

  Utility-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.35/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.35/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  BinCam-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.38:554/h264Preview_01_sub # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.38:554/h264Preview_01_main # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,181,138,123,201,141,206,169,270,159,286,87,334,97,341,153,334,190,392,270,640,369,640,0,0,0
    objects:
      track:
        - person
        - dog
```

### docker-compose file or Docker CLI command

```yaml
As per attached json text files in main subject
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I do actually have two Coral's to install, as I have quite a few cameras currently and want to add some more, so assumed I'd need more than one.  I assume I will need some way of making sure that both are passed through and identified, but for the minute am just trying with a single Coral plugged in.

**Comment by NickM-27** [comment]
Please share your docker compose

**Comment by NickM-27** [comment]
I would imagine those json files are edited by the UI, can you share what the UI looks like for configuring the frigate container?

**Comment by gadgetbazza** [comment]
Sure, there is a section for linking devices, but it's not too clear and I've read other posts via Google of people modifying the Docker command content manually from the files I've listed, but I'm out of my depth!

Screenshots attached:
<img width="1159" alt="Screenshot 2022-09-23 at 22 41 37" src="https://user-images.githubusercontent.com/99490699/192060752-468a6fcc-fe54-44ee-8aba-d9fb206a1bf3.png">

<img width="1157" alt="Screenshot 2022-09-23 at 22 41 53" src="https://user-images.githubusercontent.com/99490699/192060779-594647c9-75e2-4fe3-ae63-559c2d02240c.png">

<img width="858" alt="Screenshot 2022-09-23 at 22 42 07" src="https://user-images.githubusercontent.com/99490699/192060797-b1e2cb36-0589-4461-89a7-2455f8756615.png">

<img width="853" alt="Screenshot 2022-09-23 at 22 42 16" src="https://user-images.githubusercontent.com/99490699/192060806-d09bcdc2-07d2-458c-ab00-7e9ef21629bb.png">

<img width="857" alt="Screenshot 2022-09-23 at 22 42 23" src="https://user-images.githubusercontent.com/99490699/192060814-7954fd10-7b71-4629-bdd7-9685c47c119f.png">

<img width="858" alt="Screenshot 2022-09-23 at 22 42 31" src="https://user-images.githubusercontent.com/99490699/192060823-c16e6e67-56f3-4962-adeb-dd1f516a4dfc.png">

<img width="861" alt="Screenshot 2022-09-23 at 22 42 38" src="https://user-images.githubusercontent.com/99490699/192060909-81c18a8b-63c2-4be6-a5ab-071e3bf0ab42.png">

I appreciate the assist and quick response.

**Comment by NickM-27** [comment]
So the menu you want is going to be under Device. Not sure if those menus expand or not but you might just want to try adding `ACM USB modems` `TTY` and maybe `Input` and see if that gets them to work

**Comment by gadgetbazza** [comment]
That's the full list in the drop down shown on the Device tab.  I had selected the ACM USB modems previous but no joy.  I'm just adding the other two and restarting.

How will I be able to verify that the device is visible to the container image when the lsusb command doesn't work in the frigate console?  Is there another way?

**Comment by NickM-27** [comment]
Just install lsusb: `apt-get update && apt-get install usbutils`

**Comment by NickM-27** [comment]
Or you can just enable the coral in the config and see if it works, since when it doesn't work frigate instantly quits

**Comment by gadgetbazza** [comment]
Ok, installed the usbutils (so easy when you know how) and this is what I see inside the container for lsusb

# lsusb
Bus 002 Device 002: ID 1a6e:089a  
Bus 002 Device 001: ID 1d6b:0003  
Bus 001 Device 002: ID 1005:b155          USB DISK MODULE
Bus 001 Device 001: ID 1d6b:0002  
# 
The first item in the list marries with the Bus/Dev/ID from the host for the Coral, so hopefully that's passed through now.

I've adjusted my frigate config as follows for the detectors piece and then restarted the container.

`
#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3
# cpu2:
#   type: cpu
#   num_threads: 3
detectors:
  coral:
    type: edgetpu
    device: usb`

But Frigate is indeed crashing shortly after starting with the following error:

```
[2022-09-23 22:59:14] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:
```

**Comment by NickM-27** [comment]
So I do see the coral is being passed in `Bus 002 Device 002: ID 1a6e:089a`

Can you please try running frigate a few more times and then paste another `lsusb` run from the host?

**Comment by gadgetbazza** [comment]
Interesting, so I just started the Frigate container again as you suggested and this showed up:

`[2022-09-23 23:04:42] frigate.edgetpu                INFO    : TPU found`

Looking at the LSUSB outputs, this is what is present:

QNAP Host:

```
[~] # lsusb
Bus 002 Device 003: ID 18d1:9302 Google Inc. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1005:b155 Apacer Technology, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Frigate Container Station Console:

```
# lsusb
Bus 002 Device 003: ID 18d1:9302  
Bus 002 Device 001: ID 1d6b:0003  
Bus 001 Device 002: ID 1005:b155          USB DISK MODULE
Bus 001 Device 001: ID 1d6b:0002  
```

It appears that it has enumerated the Coral differently now and it's identified as a Google Device - not sure why that's just happened.

Will this be persistent during restarts of the Frigate container and / or the NAS do you know?

Frigate is still running after 5+ minutes now and the inference speed has dropped significantly :)

**Comment by NickM-27** [comment]
The coral USB has an internal driver. So when it first is connected it appears as `Global Unicorp...`. Once Frigate tries to use the coral, the coral will load its internal driver which will then have it appear as `Google Inc.` which means it is working properly. 

Frigate restarts shouldn't matter, but upon restarting the NAS or unplugging and replugging the coral Frigate will likely fail on the first try.

**Comment by gadgetbazza** [comment]
Ok understood.

Is there a way to make the container restart upon failure like this, so that in the event of a restart I don't have to remember to boot Frigate a second time?

I will also try de-selecting some of the options on the Devices tab in the container station to see which one actually allowed the Coral to work for reference.

**Comment by NickM-27** [comment]
Click on advanced settings it will likely have an option in there to configure auto restart

**Comment by gadgetbazza** [comment]
I've only got an Auto Start option in the settings unfortunately.

I've reduced the Device tab in Advanced settings down to the TTY option only and the Coral is still detected after restarting, so it seems that's what was needed along with the second start of Frigate.

<img width="859" alt="Screenshot 2022-09-23 at 23 22 05" src="https://user-images.githubusercontent.com/99490699/192064549-af1eeffe-e800-41bb-892c-9cffaea12fd7.png">


I could still do with a solution to the second start of Frigate being needed, but I suppose a UPS for the NAS is one option! :)

**Comment by NickM-27** [comment]
Native docker has a restart behavior, but looks like QNAP does not support it. Nothing we can do about that: https://forum.qnap.com/viewtopic.php?t=143609

**Comment by NickM-27** [comment]
I'll go ahead and close this as this is solved, feel free to create a new issue if something else comes up.

**Comment by gadgetbazza** [comment]
Yeah that figures, the QNAP is a great device, but I'm wishing it was just a pure Linux box now!

I assume that when I plug the second Coral in (tomorrow now), that I just update the frigate config with

```
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
```

and I'm good to go (barring maybe a second restart)?

Many thanks for your help Nick, you've been awesome... Coffee inbound.

**Comment by NickM-27** [comment]
```yaml
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
```

yes, that is how it would be configured to use two usb corals
