### ISSUE TITLE
[Config Support]: MQTTmessages to Azure IOT Hub

### ISSUE THREAD

**Issue by francoisdutoit** [blakeblackshear/frigate#3923]
### Describe the problem you are having

Hi,

I'm trying to get my MQTT messages sent to azure IOT Hub using info from https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support.

Frigate runs if I use port 443 and comment out the [tls_ca_certs path] - but no messages  are received in my IOT hub - presumably because a cert is required. Currently my logs are giving me errors with the cert path - not sure why :/

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: {MY_IOT_HUB_NAME}.azure-devices.net
  port: 8883
  topic_prefix: frigate
  client_id: frigate
  user: {MY_IOT_HUB_NAME}.azure-devices.net/{MY_DEVICE_NAME}/?api-version=2022-09-24
  password: {SHARED ACCES KEY}
  tls_ca_certs: /home/francois/docker-compose/frigate/BaltimoreCyberTrustRoot.crt
  tls_insecure: false
  stats_interval: 60
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://{USERNAME}:{PASSWORD}@192.168.88.208/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-09-24 16:20:05] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-09-24 16:20:05] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-09-24 16:20:05] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [Errno 2] No such file or directory
frigate  | [cmd] python3 exited 1
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)
