### ISSUE TITLE
[Config Support]: Motion detected in the camera is recognized as door bell in Homekit

### ISSUE THREAD

**Issue by t0ny-peng** [blakeblackshear/frigate#3933]
### Describe the problem you are having

Great work! 

I just upgraded from 0.11.0-rc1 today and everything works fine(with a little bit of modification). One thing I noticed that isn't the same as before is that whenever an object(person) is detected in the field of view, the Home app on iOS always send out the following notification. The camera is added via the Home Asssitant HomeKit integration. Is this behavior configurable?

<img width="370" alt="image" src="https://user-images.githubusercontent.com/4816327/192129051-68feb7b4-7a8f-4ae0-96af-d850e2beac4c.png">

### Version

0.11.0

### Frigate config file

```yaml
mqtt:
  host: REDACTED
  user: bot
  password: "REDACTED"

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  fps: 5
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person
    - cat

ffmpeg:
 hwaccel_args: -c:v h264_qsv

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True

rtmp:
  enabled: True

cameras:
  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://REDACTED/ch0_0.h264
          roles:
            - record
            - detect
            - rtmp
```

### Relevant log output

```shell
Nothing wrong in the log.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
