### ISSUE TITLE
[Config Support]: just recording h265?

### ISSUE THREAD

**Issue by Sim0nW0lf** [blakeblackshear/frigate#3940]
### Describe the problem you are having

Hey, thank you so much for your work on this project! It has been a gamechanger for me.
Right now I am struggeling with the most simple task: recording without doing anything else.
My cameras main feed is h265 and I am trying not to transcode it in any way, just to record 24/7.
I am sure tho that frigate is transcoding my streams because I have these ffmpeg commands in my processes and also I can watch the live streams in my browser which should not be possible at all in chrome.

I am also not seeing any recordings for now, so I am not sure if it's recording at all but maybe someone could help me understand this better.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: mqtt-record
  user: USER
  password: PASSWORD

ffmpeg:
  #https://docs.frigate.video/configuration/hardware_acceleration
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

record:
  enabled: True
  retain:
    days: 7
    mode: all

detect:
  enabled: False

rtmp:
  enabled: False

cameras:
  Versand-vorne:
    ffmpeg:
      inputs:
        #https://docs.frigate.video/configuration/camera_specific/
        - path: rtsp://USER:PASSWORD@LOCALIP:554/h265Preview_01_main
          roles:
            - record

  Versand-hinten:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@LOCALIP:554/h265Preview_01_main
          roles:
            - record

  Versand-Eingang:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@LOCALIP:554/h265Preview_01_main
          roles:
            - record

  Flur-Treppe:
    ffmpeg:
      inputs:
        - path: rtsp://USER:PASSWORD@LOCALIP:554/h265Preview_01_main
          roles:
            - record

birdseye:
  enabled: False
```

### Relevant log output

```shell
ffmpeg -hide_banner -loglevel warning -hwaccel qsv -qsv_device /dev/dri/renderD128 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://USER:PASSWORD@LOCALIP:554/h265Preview_01_main -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Versand-vorne-%Y%m%d%H%M%S.mp4 -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
