### ISSUE TITLE
[HW Accel Support]: Worse HWaccel since v11 (even with i965)

### ISSUE THREAD

**Issue by boehser-enkel** [blakeblackshear/frigate#3948]
### Describe the problem you are having

![grafik](https://user-images.githubusercontent.com/59539881/192273501-533cfe13-dca2-40c2-aff1-d303109c638d.png)

10:00-11:00: v10.1
11:00-14:00: v11
from 14:00: with LIBVA_DRIVER_NAME: "i965"

Is there any way to get back the old performance?

greetz

### Version

11

### Frigate config file

```yaml
mqtt:
  host: 172.18.0.200
  user: mqtt_user
  password: 
  
 
detectors:
  coral:
    type: edgetpu
    device: usb
    
    
cameras:
  vorne:


    ffmpeg:
      inputs:
        - path: rtsp://192.168.88.66/live0
          roles:
            - detect
            - record
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128

    detect:
      width: 1920
      height: 1080
      
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 7
          mode: active_objects
          


    snapshots:
      enabled: True      
      
    motion:
      mask:
        - 0,0,1920,0,1920,551,1079,360,1043,611,996,824,869,944,704,940,724,405,312,405,331,669,416,671,504,1080,0,1080

        

objects:

  track:
    - person
  mask:
    - 0,0,1920,0,1920,551,1079,360,1043,611,853,602,852,883,721,873,724,405,312,405,331,669,416,671,504,1080,0,1080
    - 1770,391,1495,268,1454,632,1714,711
    
  filters:
    person:
      min_area: 2500
      max_area: 5000000
      min_score: 0.5
      threshold: 0.75

  
birdseye:
  quality: 8
  mode: objects
  
rtmp:

  enabled: true



live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 1080
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
```

### docker-compose file or Docker CLI command

```yaml
#Frigate
  frigate:
    container_name: Frigate
    hostname: Frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # (width * height * 1.5 * 9 + 270480)/1048576 = <shm size in mb>
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/frigate.yml:/config/config.yml:ro
      - ./frigate:/media/frigate
    ports:
      - "5000:5000"
      - "1935:1935"
    environment:
      FRIGATE_RTSP_PASSWORD: "schulleder6"
#      LIBVA_DRIVER_NAME: "radeonsi"
      LIBVA_DRIVER_NAME: "i965"
      PLUS_API_KEY: "01cb8d25-de22-4ed8-9150-40c1f51ca4be:de32a259c9daa4dde460df78ddd0371d84c54aa5"
    depends_on:
      - mosquitto
    networks:
      default:
        ipv4_address: 172.18.0.203
```

### Relevant log output

```shell
nothing to see here
```

### FFprobe output from your camera

```shell
Needed?
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Eufy
