### ISSUE TITLE
[Config Support]:  "high" cpu usage with detect, record, and snapshots disabled

### ISSUE THREAD

**Issue by lygris** [blakeblackshear/frigate#3951]
### Describe the problem you are having

I'm trying to track down why my frigate instances cpu usage is as high as it is. I added an extra camera today for a total of 9 and cpu usage was up to about 40% of a dual e5-2650 v2 system. I got curious and started trying to performance tune my frigate config because I haven't really changed it much since the original setup besides adding a camera here and there. After masking off some areas of cameras with trees swaying in the wind and such i was down to 30-35%. So I tried disabling detect, record, and snapshots for every camera and cpu is still sitting at 20-25%. Is RTMP eating up that much cpu usage or do I have something stupidly configured? config below

### Version

0.11.0-3846A13

### Frigate config file

```yaml
# yaml-language-server: $schema=http://10.0.6.43:5000/api/config/schema
mqtt: 
  host: mqtt.nesseth.org
  user: frigate
  password: mRnfhAE$KwEN3cJ@n&$u
detectors:
  coral:
    type: edgetpu
    device: pci
birdseye:
  enabled: True
  mode: objects
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
cameras:
  Living-Room:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
      inputs:
        - path: rtsp://x.x.x.247/live0
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - dog      
    motion:
      mask:
        - 1249,12,1246,44,921,38,920,11
  Garage:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
      inputs:
        - path: rtsp://x.x.x.246/live0
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 1242,0,1243,34,921,38,917,0
  Front-Door:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
      inputs:
        - path: rtsp://admin:Pass!@x.x.x.132:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 1920,0,1920,795,1399,782,1249,642,801,509,577,411,552,685,0,818,0,0
  Laundry-Room:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
      inputs:
        - path: rtsp://x.x.x.245/live0
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1249,12,1246,44,921,38,920,11
  Entryway:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
      inputs:
        - path: rtsp://x.x.x.222/live0
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 1249,12,1246,44,921,38,920,11
  Kitchen:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
      inputs:
        - path: rtsp://x.x.x.173/live0
          roles:
            - detect
            - rtmp
            - record
    detect:
      enabled: True
      max_disappeared: 25
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 914,38,1246,43,1247,0,918,0
  # Bedroom:
  #   ffmpeg:
  #     input_args:
  #       - -c:v
  #       - h264_cuvid
  #       - -c:a
  #       - aac
  #     inputs:
  #       - path: rtsp://x.x.x.167/live0
  #         roles:
  #           - detect
  #           - rtmp
  #           - record
  #   detect:
  #     enabled: True
  #     max_disappeared: 45
  #   objects:
  #     track:
  #       - person
  #       - dog
  #   record:
  #     enabled: True
  #   motion:
  #     mask:
  #       - 1244,14,1244,35,920,33,920,10
  Backyard:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
        - -rtsp_transport
        - tcp
      inputs:
        - path: rtsp://user:Pass!@10.0.0.252/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,0,0,52,1276,67,1280,0
  Backyard-2:
    ffmpeg:
      input_args:
        - -c:v
        - h264_cuvid
        - -c:a
        - pcm_mulaw
        - -rtsp_transport
        - tcp
      inputs:
        - path: rtsp://lygris:Pass@x.x.x.249:80/videoMain
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,117,0,0,0,0,288,0,293,34
  Driveway:
    ffmpeg:
      input_args: 
        - -c:v
        - h264_cuvid
        - -c:a
        - aac
        - -rtsp_transport
        - tcp
      inputs:
        - path: rtsp://user:pass@x.x.x.253/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - car
        - motorcycle
        - dog
    motion:
      mask:
        - 857,0,622,0,0,0,0,520,410,257,755,176,1920,253,1920,0
snapshots:
  enabled: true
record:
  enabled: true
  days: 0
  events:
    post_capture: 20
    retain:
      mode: active_objects
      default: 10
      objects:
        person: 10
        dog: 3
        car: 3
        motorcycle: 3
```

### Relevant log output

```shell
No errors beyond a couple random ones for snapshot not in cache
```

### Frigate stats

```json
Not sure where to find this
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe

**Comment by NickM-27** [comment]
a few things here:
1. your hardware accleration args (`- h264_cuvid`) should be added as `ffmpeg -> hwaccel_args` not `input_args`
2. Difficult to say what is normal, I would recommend getting a shell in frigate then running `apt-get update && apt-get install htop -y && htop` and paste a screenshot here. That will give info on what processes are using what CPU.

**Comment by lygris** [comment]
I'll change over the hwaccell_args, here's the screenshot of htop currently
![htop](https://user-images.githubusercontent.com/22260038/192359386-ce87b19e-7109-47cd-9131-242a77143e57.png)

**Comment by lygris** [comment]
1 & 2: I went through on the cameras page and hit disable on detect/record/snapshots for every camera, i'm assuming that disabled motion and object detection?
3: it's dual e5-2650 v2's

**Comment by NickM-27** [comment]
> 1 & 2: I went through on the cameras page and hit disable on detect/record/snapshots for every camera, i'm assuming that disabled motion and object detection?

No, motion detection stays on. It must be specifically disabled (there is no UI button to do this).

**Comment by lygris** [comment]
How do i disable motion detection for testing?

and based on what we've talked through i'm guessing my cpu is just struggling to handle the motion detection aspect?

**Comment by NickM-27** [comment]
> How do i disable motion detection for testing?

https://docs.frigate.video/integrations/mqtt#frigatecamera_namemotion

> and based on what we've talked through i'm guessing my cpu is just struggling to handle the motion detection aspect?

That but also ffmpeg is using a decent amount, are all your cameras 1080p? Keep in mind you set 1080p resolution but aren't setting the resolution for each camera which means any cameras that aren't that size will have their stream resized to match that.

**Comment by lygris** [comment]
2 are not so I changed them over to 1080, but it didnt really change anything. The rest of the cameras have always been 1080p but if i check the info in vlc it shows video resolution: 1920 x 1080 and buffer dimensions: 1920 x 1088. Should i be setting detect dimensions for 1920 x 1080 or 1920 x 1088?

**Comment by NickM-27** [comment]
You set it like this:

```yaml
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
```

any not like that should be specifically set. And you should use the video dimensions not buffer dimensions
