### ISSUE TITLE
[Support]: connection refused - but from where is the error coming?

### ISSUE THREAD

**Issue by Symbiot78** [blakeblackshear/frigate#3952]
### Describe the problem you are having

As title.. 
I am seeing connection refused errors in my log.

But what is causing it? 
my connection url is:

`inputs:
        - path: rtsp://redacted@10.20.10.32/Streaming/Channels/202   ####rtsp://10.0.10.10:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - rtmp`

error is
[2022-09-26 22:47:03] ffmpeg.carport.detect          ERROR   : [tcp @ 0x55ad8bec9180] Connection to tcp://10.20.10.32:554?timeout=5000000 failed: Connection refused

The error doesn't 'start' as soon as frigate starts.. it's only after a while it starts cropping up.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.131
  user: mqttuser
  password: redacted



cameras:
  carport: # <------ Name the camera
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://redacted@10.20.10.32/Streaming/Channels/202   ####rtsp://10.0.10.10:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://redacted@10.20.10.32/Streaming/Channels/201   ####rtsp://10.0.10.10:554/rtsp # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640  # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 6
    motion:
      mask:
         - 0,75,1707,76,1095,434,766,559,570,630,457,658,0,806
    zones:
      carport_area:
        coordinates: 2558,465,2555,578,2535,675,2522,755,2502,843,2098,1470,1993,1520,1125,1520,1024,1470,766,1298,623,1142,464,929,327,745,650,593,775,547,918,499,1072,490,1232,356,1395,271,1566,208,1844,254,1937,211,2430,362
    record:
      enabled: True
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 0
        required_zones:
          - carport_area
    snapshots:
      enabled: True
      required_zones:
        - carport_area
##########
  garden: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://redacted@10.20.10.31/Streaming/Channels/102   ####rtsp://10.0.10.10:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://redacted@10.20.10.31/Streaming/Channels/101
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 2688  # <---- update for your camera's resolution
      height: 1520 # <---- update for your camera's resolution
      fps: 24
    snapshots:
      enabled: True
    motion:
      mask:
        - 33,45,253,49,377,49,376,27,318,23,31,31
```

### Relevant log output

```shell
see above
```

### FFprobe output from your camera

```shell
not sure if it's relevant?
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision DS-2CD2347G2-LU
