### ISSUE TITLE
[Support]: Web Interface / API of Add-On not reachable after update to 0.11

### ISSUE THREAD

**Issue by derhappy** [blakeblackshear/frigate#3954]
### Describe the problem you are having

I updated / reinstalled the Frigate Home Assistant add-on, integration and card two days ago. Overall, wow, thank you so much!
It's mostly working without too many manual changes. The CPU utilization went up from around 150% to 200%, but I don't mind since the power consumption somehow stayed about the same. I can access the front end embedded in Home Assistant and MQTT events seem work fine as well. 
However, I can not reach the web interface / HTTP API anymore since the update. 
I used to fetch images using links like http://192.168.1.234:5000/api/events/$1/thumbnail.jpg to upload them to another server. 
I also can not reach the Web Interface using a browser.

Checking docker, the port seems to be correct. Logs don't show anything about the web interface at all.

Any idea why I can't reach the web interface anymore or how I can make it work again?

### Version

0.11.0-3846a13

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": false,
    "height": 600,
    "mode": "continuous",
    "quality": 20,
    "width": 800
  },
  "cameras": {
    "eingang": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": false,
        "mode": "continuous"
      },
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1080,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 1920
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@192.168.1.200/axis-media/media.amp?steamingprofile=full2&camera=2",
            "roles": [
              "record"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@192.168.1.200/axis-media/media.amp?streamprofile=detect&camera=2",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.1.200/axis-media/media.amp?steamingprofile=full2&camera=2 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/eingang-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.1.200/axis-media/media.amp?streamprofile=detect&camera=2 -r 5 -s 1920x1080 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "0,0,975,0,430,519,0,648",
          "588,867,546,935,548,998,616,1014,699,986,736,896,714,870,657,838",
          "1920,1080,1629,1080,1634,0,1920,0",
          "454,1080,0,904,0,1080",
          "1207,1080,1221,911,959,863,848,1080",
          "990,416,1109,284,1313,256,1324,594,1147,601",
          "161,1080,28,990,47,725,106,725,116,846,155,904,189,729,270,761,213,979,344,1058,437,1080"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 500,
        "quality": 100,
        "required_zones": [],
        "timestamp": false
      },
      "name": "eingang",
      "objects": {
        "filters": {
          "bear": {
            "mask": [
              "1920,1080,1920,0,1487,0,1511,446,1515,1080",
              "826,0,0,0,0,652"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": [
              "1920,1080,1920,0,1462,0,1485,321,1018,402,495,1080",
              "1268,74,1458,0,1471,246,1279,251",
              "826,0,0,0,0,652"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": [
              "1920,1080,1920,0,1487,0,1511,446,1515,1080",
              "950,657,776,635,948,407,1051,392",
              "826,0,0,0,0,652"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [
              "1920,1080,1920,0,1487,0,1511,446,1515,1080",
              "826,0,0,0,0,652"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [
              "1053,169,1168,115,1182,0,0,0,0,1080,135,1080",
              "826,0,0,0,0,652"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": [
          "826,0,0,0,0,652"
        ],
        "track": [
          "person",
          "car",
          "cat",
          "dog",
          "bear"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "treppe",
            "einfahrt",
            "rasen"
          ],
          "retain": {
            "default": 8,
            "mode": "motion",
            "objects": {
              "person": 15
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": false,
        "crop": true,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "eingang_ext",
          "einfahrt",
          "rasen",
          "eingang_all"
        ],
        "retain": {
          "default": 8,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "einfahrt": {
          "coordinates": "1462,129,1152,166,979,396,1461,310",
          "filters": {},
          "objects": []
        },
        "eingang_all": {
          "coordinates": "1514,1080,1456,0,1063,0,0,984,0,1080",
          "filters": {},
          "objects": [
            "car",
            "cat",
            "bird",
            "bear",
            "mouse"
          ]
        },
        "eingang_ext": {
          "coordinates": "1556,1080,1535,46,1155,98,385,1080",
          "filters": {},
          "objects": []
        },
        "treppe": {
          "coordinates": "1502,534,788,650,642,840,1461,925",
          "filters": {},
          "objects": []
        }
      }
    },
    "garage": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": false,
        "mode": "continuous"
      },
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1296,
        "max_disappeared": 25,
        "stationary": {
          "interval": 10,
          "max_frames": {
            "default": null,
            "objects": {
              "person": 300
            }
          },
          "threshold": 50
        },
        "width": 2304
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@192.168.1.201:554/Streaming/Channels/101/",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.1.201:554/Streaming/Channels/101/ -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garage-%Y%m%d%H%M%S.mp4 -r 5 -s 2304x1296 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "636,162,1833,278,2053,381,2131,0,0,0,0,535,350,291,451,272"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 500,
        "quality": 100,
        "required_zones": [],
        "timestamp": false
      },
      "name": "garage",
      "objects": {
        "filters": {
          "bear": {
            "mask": [
              "2304,1296,2304,0,2071,0,2099,1296",
              "2137,0,0,0,0,172,2135,200",
              "0,448,0,1296,412,1296",
              "938,0,0,0,0,564"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": [
              "2304,1296,2304,0,2071,0,2099,1296",
              "0,1296,0,411,564,1296,316,1296",
              "1568,259,1898,601,1680,1296,742,1296,167,705,219,610,745,161"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": [
              "2304,1296,2304,0,2071,0,2099,1296",
              "2137,0,0,0,0,172,2135,200",
              "0,448,0,1296,412,1296",
              "938,0,0,0,0,564"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [
              "2304,1296,2304,0,2071,0,2099,1296",
              "2137,0,0,0,0,172,2135,200",
              "0,448,0,1296,412,1296",
              "938,0,0,0,0,564"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [
              "560,289,916,151,1500,0,0,0,0,581,74,581",
              "2115,0,2105,110,1447,0"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "car",
          "cat",
          "dog",
          "bear"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "treppe",
            "einfahrt",
            "rasen"
          ],
          "retain": {
            "default": 8,
            "mode": "motion",
            "objects": {
              "person": 15
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": false,
        "crop": true,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [
          "eingang_ext",
          "einfahrt",
          "rasen",
          "eingang_all"
        ],
        "retain": {
          "default": 8,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "einfahrt": {
          "coordinates": "540,1296,1878,1296,2062,527,1515,471,613,291,89,657",
          "filters": {},
          "objects": []
        },
        "rasen": {
          "coordinates": "2092,415,1866,273,819,182,563,314,1517,473,2059,529",
          "filters": {},
          "objects": []
        }
      }
    },
    "klingel": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": false,
        "mode": "continuous"
      },
      "detect": {
        "enabled": false,
        "fps": 5,
        "height": 600,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 800
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1",
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://user:pass@192.168.1.201/axis-media/media.amp?camera=3",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": "-f rawvideo -pix_fmt yuv420p",
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.1.201/axis-media/media.amp?camera=3 -r 5 -s 800x600 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": "",
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": false,
        "crop": true,
        "enabled": true,
        "height": 500,
        "quality": 100,
        "required_zones": [],
        "timestamp": false
      },
      "name": "klingel",
      "objects": {
        "filters": {},
        "mask": "",
        "track": []
      },
      "record": {
        "enabled": false,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "treppe",
            "einfahrt",
            "rasen"
          ],
          "retain": {
            "default": 8,
            "mode": "motion",
            "objects": {
              "person": 15
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 2,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": false,
        "crop": true,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [
          "eingang_ext",
          "einfahrt",
          "rasen",
          "eingang_all"
        ],
        "retain": {
          "default": 8,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": "-hide_banner -loglevel warning",
    "hwaccel_args": [
      "-hwaccel",
      "vaapi",
      "-hwaccel_device",
      "/dev/dri/renderD128",
      "-hwaccel_output_format",
      "yuv420p"
    ],
    "input_args": "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1",
    "output_args": {
      "detect": "-f rawvideo -pix_fmt yuv420p",
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.234",
    "password": "mqtt_pass",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt_user"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "plus": {
    "enabled": false
  },
  "record": {
    "enabled": true,
    "events": {
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [
        "treppe",
        "einfahrt",
        "rasen"
      ],
      "retain": {
        "default": 8,
        "mode": "motion",
        "objects": {
          "person": 15
        }
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 2,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": false,
    "crop": true,
    "enabled": true,
    "height": null,
    "quality": 70,
    "required_zones": [
      "eingang_ext",
      "einfahrt",
      "rasen",
      "eingang_all"
    ],
    "retain": {
      "default": 8,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  },
  "ui": {
    "use_experimental": false
  }
}
```

### Relevant log output

```shell
non really
[2022-09-26 22:21:48] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-09-26 22:21:49] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-09-26 22:21:49] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-26 22:21:49] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-26 22:21:49] frigate.app                    INFO    : Output process started: 218
[2022-09-26 22:21:49] frigate.app                    INFO    : Camera processor started for garage: 222
[2022-09-26 22:21:49] frigate.app                    INFO    : Camera processor started for eingang: 224
[2022-09-26 22:21:49] ws4py                          INFO    : Using epoll
[2022-09-26 22:21:49] detector.coral                 INFO    : Starting detection process: 216
[2022-09-26 22:21:49] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-26 22:21:49] frigate.app                    INFO    : Camera processor started for klingel: 225
[2022-09-26 22:21:49] frigate.app                    INFO    : Capture process started for garage: 228
[2022-09-26 22:21:49] frigate.app                    INFO    : Capture process started for eingang: 231
[2022-09-26 22:21:49] frigate.app                    INFO    : Capture process started for klingel: 233
[2022-09-26 22:21:50] ws4py                          INFO    : Using epoll
[2022-09-26 22:21:52] frigate.edgetpu                INFO    : TPU found
[2022-09-26 22:23:00] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59468]
[2022-09-26 22:23:12] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59468]
[2022-09-27 08:29:52] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:40188]
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not reachable!
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relevant
