### ISSUE TITLE
[Support]: Restarting the addon throws an error after update to v0.11.0 if watchdog is enabled

### ISSUE THREAD

**Issue by pauln** [blakeblackshear/frigate#3968]
### Describe the problem you are having

Restarting the addon with the "watchdog" setting enabled throws the following error:
> Can't create container from addon_ccab4aaf_frigate: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate: Conflict ("Conflict. The container name "/addon_ccab4aaf_frigate" is already in use by container "131cbd0d164a02eb4fad96446f086e9a00e7725aeccc59867eef273c54a604e8". You have to remove (or rename) that container to be able to reuse that name.")

I first noticed this when prompted to restart the addon after adding a Frigate+ key to the addon config, but it's also happened on subsequent attempts to restart the addon.  The Frigate addon usually does seem to restart successfully despite the error, but when this first happened, that didn't seem to be the case; it appeared to be stopped, and clicking "start" got it running again without issue, but during subsequent testing I've noticed that the Home Assistant UI sometimes seems to get out of sync with the actual status and incorrectly show it as stopped, so I'm not sure whether it was really stopped that first time.

The log below is from the HA Supervisor.  There's nothing in the Frigate logs relating to this as it's at the HA Addon / Docker level.

### Version

0.11.0-3846A13

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: [redacted]
  password: [redacted]

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]/unicast
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    
  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]/unicast
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
    motion:
      mask:
        - [redacted]
    zones:
      driveway:
        coordinates: [redacted]
      lawn:
        coordinates: [redacted]
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 25
      mode: active_objects
      
detectors:
  coral1:
    type: edgetpu
    device: pci:0
    
logger:
  default: info
```

### Relevant log output

```shell
22-09-28 23:11:26 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate application
22-09-28 23:11:27 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate application
22-09-28 23:11:27 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Frigate NVR is failed, restarting...
22-09-28 23:11:27 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate application
22-09-28 23:11:27 ERROR (SyncWorker_4) [supervisor.docker.manager] Can't create container from addon_ccab4aaf_frigate: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate: Conflict ("Conflict. The container name "/addon_ccab4aaf_frigate" is already in use by container "43981bd9b762f92899bcb04a49fb9f1043f55a404622dc8ea9a8aa8c8b87d2e9". You have to remove (or rename) that container to be able to reuse that name.")
22-09-28 23:11:28 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on blakeblackshear/frigate with version None
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

PCIe

### Network connection

Wireless

### Camera make and model

N/A
