### ISSUE TITLE
v0.11 Camera thumbnail in "Cameras" view does not updated afrer returning from viewing camera stream page.

### ISSUE THREAD

**Issue by artlov** [blakeblackshear/frigate#3977]
### Describe the problem you are having

When go from the general Cameras view (where there are thumbnails of camera images) to a detailed view of a specific camera and then go back to the general view, the thumbnail of the camera does not update and remains old. In the previous version, the image was updated. This can be seen especially well if the previous view was from nighttime, then when moving back and forth during the daytime, the thumbnail view still remains with the nighttime image.

### Version

0.11.0-3846A13

### Frigate config file

```yaml
mqtt:
  host: <host>
  user: <user>
  password: <pass>

ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p

cameras:
  hik1:
    ffmpeg:
      inputs:
        - path: 'rtsp://ds214:{FRIGATE_RTSP_PASSWORD}@192.168.1.37:554/Streaming/Channels/102'
          roles:
            - detect
            - rtmp
```

### Relevant log output

```shell
[2022-09-29 15:00:02] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44098]
[2022-09-29 15:00:07] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44098]
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://ds214:REDACTED@192.168.1.37:554/Streaming/Channels/102':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 6 fps, 6 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
