### ISSUE TITLE
[Config Support]: Cannot get config to load

### ISSUE THREAD

**Issue by hancooo** [blakeblackshear/frigate#3980]
### Describe the problem you are having

Not sure what is going on here. Just cannot seem to get config to load.
Fresh Ubuntu 20.04 VM on ESXi 7.0.3
No Coral


** replaced passwords and IPs


```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yml:/config/config.yml:ro
      - /mnt/footage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
#    environment:
#      FRIGATE_RTSP_PASSWORD: password
```


### Version

v2.11.2

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
mqtt:
  host: *.*.*.*
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *****
  password: *****
  stats_interval: 60
cameras:
  front_drive:
    ffmpeg:
      hwaccel_args: -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero
      inputs:
        - path: rtmp://*.*.*.*/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=****
          roles:
            - detect
            - clips
            - snapshots
            - rtmp
    objects:
      track:
        - person
        - car
    clips:
      enabled: True
      pre_capture: 10
      post_capture: 10
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      retain:
        default: 10
        objects:
          person: 15
    width: 2560
    height: 1920
    fps: 10
```


### Relevant log output

```shell
chris@syn-ho-cctv:~/docker-compose/frigate$ sudo docker-compose up
[+] Running 1/0
 ⠿ Container frigate  Created                                                                                                                                                                                                                                                                                           0.0s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-09-29 18:44:40] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Your config file is not valid!                     ***
frigate  | ***    Please check the docs at                           ***
frigate  | ***    https://docs.frigate.video/configuration/index     ***
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Config Validation Errors                           ***
frigate  | *************************************************************
frigate  | 4 validation errors for FrigateConfig
frigate  | cameras -> front_drive -> clips
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | cameras -> front_drive -> fps
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | cameras -> front_drive -> height
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | cameras -> front_drive -> width
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | Traceback (most recent call last):
frigate  |   File "/opt/frigate/frigate/app.py", line 332, in start
frigate  |     self.init_config()
frigate  |   File "/opt/frigate/frigate/app.py", line 82, in init_config
frigate  |     user_config = FrigateConfig.parse_file(config_file)
frigate  |   File "/opt/frigate/frigate/config.py", line 942, in parse_file
frigate  |     return cls.parse_obj(config)
frigate  |   File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
frigate  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
frigate  | pydantic.error_wrappers.ValidationError: 4 validation errors for FrigateConfig
frigate  | cameras -> front_drive -> clips
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | cameras -> front_drive -> fps
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | cameras -> front_drive -> height
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  | cameras -> front_drive -> width
frigate  |   extra fields not permitted (type=value_error.extra)
frigate  |
frigate  | *************************************************************
frigate  | ***    End Config Validation Errors                       ***
frigate  | *************************************************************
frigate  | [cmd] python3 exited 1
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 1
```


### Frigate stats

_No response_

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

_No response_
