### ISSUE TITLE
[Camera Support]: ffmpeg repeatedly fails and restarts

### ISSUE THREAD

**Issue by tbclark3** [blakeblackshear/frigate#3999]
### Describe the problem you are having

On 2 of my cameras (same model), ffmpeg repeatedly fails and restarts.  Sometimes it resolves after around 15 minutes of retries, but not always.  Rarely it's one camera but not both.  Both cameras work fine with vlc, no errors. I am currently running both with the default configuration, but I have tried numerous ffmpeg flags with no change in behavior. I am posting the configuration and logs for only one of the cameras.

### Version

0.11.0-3846A13

### Frigate config file

```yaml
"camera-basement": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "motion"
      },
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 352,
        "max_disappeared": 25,
        "stationary": {
          "interval": 300,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 100
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": "-hide_banner -loglevel warning",
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://viewer:password@camera-basement:554/play2.sdp",
            "roles": [
              "detect"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://viewer:password@camera-basement:554/play1.sdp",
            "roles": [
              "record",
              "rtmp"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy",
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:password@camera-basement:554/play2.sdp -r 5 -s 640x352 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:password@camera-basement:554/play1.sdp -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy /tmp/cache/camera-basement-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/camera-basement",
          "roles": [
            "record",
            "rtmp"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "640,0,640,80,0,61,0,0"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "camera-basement",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 30,
            "mode": "active_objects",
            "objects": {
              "animal": 7
            }
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 7,
          "mode": "motion"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 30,
          "mode": "motion",
          "objects": {
            "animal": 15,
            "car": 60,
            "person": 60
          }
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    },
```

### Relevant log output

```shell
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [segment @ 0x559d130b3740] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [mp4 @ 0x559d12f4e300] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [flv @ 0x559d12f493c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [flv @ 0x559d12f493c0] Packet is missing PTS
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : av_interleaved_write_frame(): Invalid argument
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [mp4 @ 0x559d12f4e300] pts has no value
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [flv @ 0x559d12f493c0] Failed to update header with correct duration.
[2022-10-02 11:36:49] ffmpeg.camera-basement.record_rtmp ERROR   : [flv @ 0x559d12f493c0] Failed to update header with correct filesize.
[2022-10-02 11:36:49] watchdog.camera-basement       INFO    : Terminating the existing ffmpeg process...
[2022-10-02 11:36:49] watchdog.camera-basement       INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
ffprobe version 5.0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-librtmp --enable-librubberband --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rtsp, from 'rtsp://viewer:viewer00@camera-basement:554/play2.sdp':
  Metadata:
    title           : TV-IP662PI
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, progressive), 640x352, 15 fps, 5 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Frigate stats

```json
{"camera-alley":{"camera_fps":5.1,"capture_pid":257,"detection_fps":0.0,"pid":235,"process_fps":5.1,"skipped_fps":0.0},"camera-backdoor":{"camera_fps":5.1,"capture_pid":252,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"camera-basement":{"camera_fps":5.0,"capture_pid":307,"detection_fps":0.0,"pid":244,"process_fps":5.0,"skipped_fps":0.0},"camera-frontdoor":{"camera_fps":5.0,"capture_pid":271,"detection_fps":0.0,"pid":238,"process_fps":5.0,"skipped_fps":0.0},"camera-lowergarage":{"camera_fps":5.0,"capture_pid":284,"detection_fps":0.0,"pid":242,"process_fps":5.0,"skipped_fps":0.0},"camera-sidewalk":{"camera_fps":5.0,"capture_pid":265,"detection_fps":0.0,"pid":237,"process_fps":5.0,"skipped_fps":0.0},"camera-street":{"camera_fps":5.1,"capture_pid":248,"detection_fps":0.0,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"camera-uppergarage":{"camera_fps":6.0,"capture_pid":278,"detection_fps":0.0,"pid":240,"process_fps":6.0,"skipped_fps":0.0},"detection_fps":0.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":12.99,"pid":223}},"doorbell-back":{"camera_fps":5.0,"capture_pid":319,"detection_fps":0.1,"pid":247,"process_fps":5.0,"skipped_fps":0.0},"doorbell-front":{"camera_fps":5.0,"capture_pid":313,"detection_fps":0.0,"pid":245,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.0","storage":{"/dev/shm":{"free":57.9,"mount_type":"tmpfs","total":67.1,"used":9.2},"/media/frigate/clips":{"free":6536473.6,"mount_type":"nfs","total":7578620.8,"used":1040008.1},"/media/frigate/recordings":{"free":6536473.6,"mount_type":"nfs","total":7578620.8,"used":1040008.1},"/tmp/cache":{"free":937.1,"mount_type":"tmpfs","total":1000.0,"used":62.9}},"temperatures":{},"uptime":805,"version":"0.11.0-3846a13"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Trendnet TV-IP662PI
