### ISSUE TITLE
[FR] Timestamp format of snapshot

### ISSUE THREAD

**Issue by fanningert** [blakeblackshear/frigate#400]
**Describe the bug**
Currently the date time format of the snapshot is displaying the values not in DD.MM.YYYY.

**Version of frigate**
0.8 beta1 (HASS Addon)

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
  host: ip
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: etagirf
ffmpeg: {}
cameras:
  camgarage01:
    ffmpeg:
      inputs:
        - path: 'rtsp://user:pass@ip/videoSub'
          roles:
            - detect
        - path: 'rtsp://user:pass@ip/videoMain'
          roles:
            - rtmp
            - clips
            - record
    width: 1280
    height: 720
    fps: 5
    save_clips:
      enabled: true
    rtmp:
      enabled: true
    snapshots:
      show_timestamp: true
logger:
  logs:
    detector.coral: debug
    watchdog.camgarage01: debug
```

**Screenshots**
![image](https://user-images.githubusercontent.com/365219/102688649-60ffbe00-41f8-11eb-851d-939670b627c0.png)
