### ISSUE TITLE
[Support]: Frigate Home Assistant automation for two cameras covering one zone

### ISSUE THREAD

**Issue by Rogue136198** [blakeblackshear/frigate#4007]
### Describe the problem you are having

I've been trying to figure out the logic to configure a home assistant automation for my driveway. I have two cameras to cover the full width of my driveway with a small overlap in-between. I have a single zone setup that currently covers the two cameras but will later be tuned to more accurately cover the driveway.

With my current understanding I know how to get this working where I have one camera triggering only if an object has entered the driveway zone. If I simply double this I would always get double notifications for any person walking by at the foot of the driveway. How can I get this setup basically using the zone as the primary filter instead of the camera?

### Version

0.11.0

### Frigate config file

```yaml
mqtt:
  host: 10.15.1.6
  topic_prefix: frigate
  client_id: frigate

environment_vars:
  PLUS_API_KEY: 

detectors:
  cpu1:
    type: cpu
    num_threads: 8
  cpu2:
    type: cpu
    num_threads: 8
  cpu3:
    type: cpu
    num_threads: 8
  cpu4:
    type: cpu
    num_threads: 8
    
birdseye:
  enabled: True
  width: 1080
  height: 1920
  quality: 1
  mode: objects

ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - cat
    - dog
  filters:
    person:
      min_area: 1500
      
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 10
    mode: all
  events:
    pre_capture: 0
    post_capture: 0
    retain:
      default: 60
      mode: motion

snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  crop: False
  retain:
    default: 60
    objects:
      person: 60
      car: 60

rtmp:
  enabled: True

detect:
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 300

cameras:
  front_door:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid      
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:password@10.0.0.1:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:password@10.0.0.1:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      test:
        coordinates: 0,576,720,576,720,0,0,0
    detect:
      width: 720
      height: 576
      fps: 7
    ui:
      order: 0
      dashboard: True
    
  backyard:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:password@10.0.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
        - path: rtsp://admin:password@10.0.0.2:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect            
    motion:
      mask:
        - 704,199,704,0,0,0,0,201,45,168,117,125,148,110,184,91,227,89,297,86,337,86,382,88,443,92,526,96,573,118,619,143
    detect:
      width: 704
      height: 480
      fps: 7
    ui:
      order: 1
      dashboard: True

  left_driveway:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:password@10.0.0.3:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
        - path: rtsp://admin:password@10.0.0.3:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect  
    zones:
      driveway:
        coordinates: 704,0,0,0,0,480,704,480
    detect:
      width: 704
      height: 480
      fps: 7
    ui:
      order: 2
      dashboard: True
  
  right_driveway:
    ffmpeg:
      hwaccel_args: -c:v h264_cuvid
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
        - path: rtsp://admin:password@10.0.0.4:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect  
    zones:
      driveway:
        coordinates: 704,0,0,0,0,480,704,480
    detect:
      width: 704
      height: 480
      fps: 7
    ui:
      order: 3
      dashboard: True
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW

### Any other information that may be helpful

This is my current notification blueprint:

blueprint:
  name: Frigate Video Notification
  description: ""
  domain: automation
  input:
    camera:
      name: Frigate Camera
      description: The name of the camera as defined in your frigate configuration.
    notify_group:
      name: Notification Group
      description: The name of the notification group to call.
      default: 'all_devices'
    camera_page:
      name: Camera URL
      description: The URL of your camera page. (Omit the leading '/') e.g. lovelace/camera
      default: 'lovelace/cameras'
    base_url:
      name: (Optional) Base URL
      description: 'The external url for your Home Assistant instance. This will default
        to a relative URL and will open the clips in the app instead of the browser,
        which does not work well on iOS.'
      default: ''
    zone_filter:
      name: (Optional) Zone Filter
      description: Only notify if object has entered a defined zone.
      default: false
      selector:
        boolean:
    zones:
      name: (Optional) Trigger Zones
      description: A list (-) of zones you wish to recieve notifications for.
      default: []
      selector:
        object: {}
    labels:
      name: (Optional) Trigger Objects
      description: A list (-) of objects you wish to recieve notifications for.
      default: []
      selector:
        object: {}
mode: parallel
trigger_variables:
  camera: !input 'camera'
trigger:
- platform: mqtt
  topic: frigate/events
  payload: '{{ camera }}/new'
  value_template: '{{ value_json[''after''][''camera''] }}/{{ value_json[''type'']}}'
  id: frigate-event-new
- platform: mqtt
  topic: frigate/events
  payload: '{{ camera }}/end'
  value_template: '{{ value_json[''after''][''camera''] }}/{{ value_json[''type'']}}'
  id: frigate-event-end
variables:
  camera: !input 'camera'
  camera_name: '{{ camera | replace(''_'', '' '') | title }}'
  camera_page: !input 'camera_page'
  base_url: !input 'base_url'
  group_target: !input 'notify_group'
  zone_only: !input 'zone_filter'
  input_zones: !input 'zones'
  zones: '{{ input_zones | list }}'
  input_labels: !input 'labels'
  labels: '{{ input_labels | list }}'
action:
  - choose:
    - alias: Frigate Event New
      conditions:
      - condition: trigger
        id: frigate-event-new
      sequence:
      - variables:
          id: '{{ trigger.payload_json[''after''][''id''] }}'
          object: '{{ trigger.payload_json[''after''][''label''] }}'
          label: '{{ object | title }}'
          initial_entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
      - alias: Notifications enabled for object label
        condition: template
        value_template: '{{ not labels|length or object in labels }}'
      - alias: Notify on new object
        choose:
        - conditions:
          - '{{ not zone_only or initial_entered_zones|length > 0 }}'
          - '{{ not zones|length or zones|select(''in'', initial_entered_zones)|list|length > 0 }}'
          sequence:
          - service: notify.{{ group_target }}
            data:
              title:  '{{ label }} seen • {{ camera_name }}'
              message: '{{ camera_name }}'
              data:
                tag: '{{ id }}'
                group: '{{ camera_name }}'
                clickAction: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                channel: Cameras
                ttl: 0
                priority: 'high'
                url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                attachment:
                  url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                push:
                  interruption-level: 'critical'
                actions:
                  - action: URI
                    title: View Cameras
                    uri: '{{base_url}}{{camera_page}}'
    - alias: Frigate Event End
      conditions:
      - condition: trigger
        id: frigate-event-end
      sequence:
      - variables:
          id: '{{ trigger.payload_json[''after''][''id''] }}'
          object: '{{ trigger.payload_json[''after''][''label''] }}'
          label: '{{ object | title }}'
          initial_entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
      - alias: Notifications enabled for object label
        condition: template
        value_template: '{{ not labels|length or object in labels }}'
      - alias: Notify on new object
        choose:
        - conditions:
          - '{{ not zone_only or initial_entered_zones|length > 0 }}'
          - '{{ not zones|length or zones|select(''in'', initial_entered_zones)|list|length > 0 }}'
          sequence:
          - service: notify.{{ group_target }}
            data:
              title:  '{{ label }} seen • {{ camera_name }}'
              message: '{{ camera_name }}'
              data:
                tag: '{{ id }}'
                group: '{{ camera_name }}'
                video: /api/frigate/notifications/{{id}}/{{camera}}/clip.mp4      
                clickAction: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                channel: Cameras
                ttl: 0
                priority: 'high'
                url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                attachment:
                  url: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                push:
                  interruption-level: 'critical'
                actions:
                  - action: URI
                    title: View Clip
                    uri: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
                  - action: URI
                    title: View Cameras
                    uri: '{{base_url}}{{camera_page}}'

**Comment by NickM-27** [comment]
I'm not sure that the blueprint supports this, you could definitely use my notifications guide https://github.com/blakeblackshear/frigate/discussions/2898 and trigger on zone instead of camera

**Comment by Rogue136198** [comment]
> I'm not sure that the blueprint supports this, you could definitely use my notifications guide #2898 and trigger on zone instead of camera

I'll take a look and see if I can figure out how you implemented this. I've been debating switching to a customized version of your notification automation so maybe this will be my test.

**Comment by NickM-27** [comment]
If you key off the zone instead of the camera should make it easy to remove some of the conditions too which makes it simpler

**Comment by Rogue136198** [comment]
Been messing with this, I need a bit of help figuring out how to make the MQTT value_template to check if "value_json.after.entered_zones" contains driveway.

**Comment by NickM-27** [comment]
Should look like this:

```yaml
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: ["driveway"] # <---- this would be your current zone to trigger off of
    value_template: '{{ value_json["after"]["current_zones"] }}'
    variables:
      after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
      before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
      camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
      id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
      label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
```

**Comment by Rogue136198** [comment]
Okay, so apart from the variables that is almost what I had. Difference is I didn't have driveway encapsulated in double quotes and square brackets. When I try it the way you have shown I get this error
![image](https://user-images.githubusercontent.com/14829730/193878040-908a9cd3-6e66-4272-9302-a643f5b54fa1.png)

**Comment by NickM-27** [comment]
Oh that stinks, didn't realize it had to be a string. Maybe put single quotes around what I had `payload: '["driveway"]'`

**Comment by Rogue136198** [comment]
Nope, that does not work either. So far this is the only way I've gotten it working but its not ideal as it will likely break if I ever add another zone to the camera(s):

```
platform: mqtt
topic: frigate/events
id: frigate-event
payload: driveway
value_template: "{{ value_json[\"after\"][\"current_zones\"][0] }}"
variables:
  after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
  before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
  camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
  id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
  label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
```

Ideally what I am looking for is a way to parse the array found at trigger.payload_json.after.entered_zones to determine if ANY value is equal to driveway
