### ISSUE TITLE
Frigate frozen after >24h of normal operation [ffmpeg defunct]

### ISSUE THREAD

**Issue by Trashmee** [blakeblackshear/frigate#401]
**Describe the bug**
 - All ffmpeg processes in defunct state
 - http://<ip>:5000/<cameras> still shows a picture
 - The picture has a timestamp from the camera which is static and from now()-2h. Same timestamp 2 hours later
 - Picture content doesn't change
 - Frigate was running fine for > 2 weeks, a maybe similar freeze was fixed by restarting the container earlier
 - Direct live camera feeds in HomeAssistant still working (so cameras should be ok?)
```
root@3cea9367fde6:/opt/frigate# ps -aef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  3 Dec18 ?        00:50:00 python3 -u -m frigate
root        18     1  0 Dec18 ?        00:00:00 nginx: master process /usr/sbin/nginx
nobody      19    18  0 Dec18 ?        00:07:54 nginx: worker process
root        30     1  0 Dec18 ?        00:00:04 python3 -u -m frigate
root        33     1  0 Dec18 ?        00:05:17 /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(29)
root        34     1  8 Dec18 ?        02:06:08 python3 -u -m frigate
root        36     1  2 Dec18 ?        00:42:35 python3 -u -m frigate
root        38     1  0 Dec18 ?        00:14:55 python3 -u -m frigate
root        39     1 26 Dec18 ?        06:47:39 python3 -u -m frigate
root        41     1  2 Dec18 ?        00:33:17 [python3] <defunct>
root        44     1  2 Dec18 ?        00:32:50 [python3] <defunct>
root        50     1 17 Dec18 ?        04:32:14 [python3] <defunct>
root        52     1  2 Dec18 ?        00:44:16 [ffmpeg] <defunct>
root        54     1  3 Dec18 ?        00:56:30 [ffmpeg] <defunct>
root     17504     1  1 11:27 ?        00:03:00 [ffmpeg] <defunct>
root     24197     0  0 14:20 pts/0    00:00:00 bash
root     24206 24197  0 14:20 pts/0    00:00:00 ps -aef
```

**Version of frigate**
FROM blakeblackshear/frigate:0.8.0-beta1-amd64

**Config file**
```
mqtt:
  host: mqtt.<home>.de
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <pass>

logger:
  logs:
    frigate.mqtt: error

objects:
  track:
    - person
    - cat
  filters:
    cat:
      threshold: 0.5
    person:
      min_score: 0.5
      threshold: 0.7

cameras:
  garten:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:<pass>@garten:88/videoSub
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
  eingang:
    save_clips:
      enabled: True
      pre_capture: 10
    ffmpeg:
      inputs:
        - path: rtsp://frigate:<pass>@eingang:554/videoMain
          roles:
            - detect
            - rtmp
            - record
            - clips
    width: 1280
    height: 720
    fps: 5
    mask: poly,2,103,118,109,115,0,328,12,329,138,407,141,420,26,543,26,536,128,573,135,590,38,665,47,655,142,837,170,866,5,0,5

  vorgarten:
    save_clips:
      enabled: True
    record:
      enabled: False
      retain_days: 5
    objects:
      track:
        - person
        - cat
        - car
    ffmpeg:
      inputs:
        - path: rtsp://frigate:<pass>@vorgarten:554/h264Preview_01_main
          roles:
            - detect
            - rtmp
            - record
            - clips
    width: 2560
    height: 1920
    fps: 10
    mask: poly,5,988,5,7,2553,2,2553,699,1979,502,1438,597,1389,563,907,660


ffmpeg:
   hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

**Logs**
docker logs frigate
 ```
rson'])
peewee                         DEBUG   : ('DELETE FROM "event" WHERE ((("event"."camera" = ?) AND ("event"."start_time" < ?)) AND ("event"."label" = ?))', ['eingang', 1607519534.318821, 'person'])
peewee                         DEBUG   : ('SELECT DISTINCT "t1"."label" FROM "event" AS "t1" WHERE ("t1"."camera" = ?)', ['vorgarten'])
peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."label", "t1"."camera", "t1"."start_time", "t1"."end_time", "t1"."top_score", "t1"."false_positive", "t1"."zones", "t1"."thumbnail" FROM "event" AS "t1" WHERE ((("t1"."camera" = ?) AND ("t1"."start_time" < ?)) AND ("t1"."label" = ?))', ['vorgarten', 1607519534.32156, 'cat'])
peewee                         DEBUG   : ('DELETE FROM "event" WHERE ((("event"."camera" = ?) AND ("event"."start_time" < ?)) AND ("event"."label" = ?))', ['vorgarten', 1607519534.32156, 'cat'])
peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."label", "t1"."camera", "t1"."start_time", "t1"."end_time", "t1"."top_score", "t1"."false_positive", "t1"."zones", "t1"."thumbnail" FROM "event" AS "t1" WHERE ((("t1"."camera" = ?) AND ("t1"."start_time" < ?)) AND ("t1"."label" = ?))', ['vorgarten', 1607519534.323447, 'person'])
peewee                         DEBUG   : ('DELETE FROM "event" WHERE ((("event"."camera" = ?) AND ("event"."start_time" < ?)) AND ("event"."label" = ?))', ['vorgarten', 1607519534.323447, 'person'])
```

**Frigate debug stats**
 ```
{"detection_fps":12.5,"detectors":{"coral":{"detection_start":0.0,"inference_speed":12.15,"pid":34}},"eingang":{"camera_fps":5.0,"capture_pid":44,"detection_fps":0.0,"pid":38,"process_fps":5.0,"skipped_fps":0.0},"garten":{"camera_fps":5.0,"capture_pid":41,"detection_fps":0.0,"pid":36,"process_fps":5.0,"skipped_fps":0.0},"vorgarten":{"camera_fps":10.2,"capture_pid":50,"detection_fps":12.5,"pid":39,"process_fps":9.8,"skipped_fps":0.0}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe rtsp://frigate:<pass>@garten:88/videoSub
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x55e5aff844c0] Missing reference picture, default is 65542
[h264 @ 0x55e5aff844c0] Missing reference picture, default is 65544
[h264 @ 0x55e5aff844c0] Missing reference picture, default is 65546
[h264 @ 0x55e5aff844c0] Missing reference picture, default is 65548
[h264 @ 0x55e5aff844c0] Missing reference picture, default is 65550
[h264 @ 0x55e5aff844c0] Missing reference picture, default is 65552
Input #0, rtsp, from 'rtsp://frigate:<pass>@garten:88/videoSub':
  Metadata:
    title           : IP Camera Video
    comment         : videoSub
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 5.17 tbr, 90k tbn, 3520886.88 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```
```
# ffprobe rtsp://frigate:<pass>@vorgarten:554/h264Preview_01_main
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://frigate:<pass>@vorgarten:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 2560x1920, 10 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

**Screenshots**
N/A

**Computer Hardware**
Intel J4105, 8GB
Debian GNU/Linux 10 (buster)
FROM blakeblackshear/frigate:0.8.0-beta1-amd64
Coral Version: USB ( Bus 002 Device 002: ID 18d1:9302 Google Inc.) 
Network: 1GbE

**Camera Info:**
- Foscam 9902, FI9803P, Reolink RLC-522-5MP

The container is still stale in case you'd like additional information, pls. let me know.
