### ISSUE TITLE
[Config Support]: tls_ca_certs - No such file or directory

### ISSUE THREAD

**Issue by francoisdutoit** [blakeblackshear/frigate#4010]
### Describe the problem you are having

When adding the MQTT  tls_ca_certs location - I get the following error : [Errno 2] No such file or directory

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: mymqttserver.net
  port: 8883
  client_id: elitedeskpc
  user: theusername
  password: thepassword
  topic_prefix: devices/elitedeskpc/messages/events/
  tls_ca_certs: /home/francois/docker-compose/frigate/config/digicert.cer
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: debug
detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
cameras:
  12EdwardOffice:
    ffmpeg:
      inputs:
        - path: rtsp://theusername:thepassword@192.168.88.208/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
        - path: rtsp://theusername:thepassword@192.168.88.208/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 2
        mode: all
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
  12EdwardField:
    ffmpeg:
      inputs:
        - path: rtsp://theusername:thepassword@192.168.88.207/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
        - path: rtsp://theusername:thepassword@192.168.88.207/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 2
        mode: all
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 2
```

### Relevant log output

```shell
frigate exited with code 1
frigate  | exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-10-04 14:32:12] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-10-04 14:32:12] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-10-04 14:32:12] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [Errno 2] No such file or directory
frigate  | [cmd] python3 exited 1
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [s6-finish] sending all processes the TERM signal.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
