### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by brembygit** [blakeblackshear/frigate#4014]
### Describe the problem you are having

Every 5 seconds I see this error

ERROR   : could not convert string to float: ''
ERROR   : Error occurred when attempting to maintain recording cache

### Version

0.11.0-3846A13

### Frigate config file

```yaml
etectors:
  coral:
     type: edgetpu
     device: usb

objects:
 track:
   - person
#   - car
   - bicycle
   - motorcycle
   - bird
   - cat
   - dog

cameras:
 camera1:
  ffmpeg:
    inputs:
    - path: rtsp://user:XYZ/videoSub
      roles:
       - detect
    - path: rtsp://user:XYZ/videoMain
      roles:
       - record

  detect:
   width: 1280
   height: 720
   fps: 5

  record:
   enabled: True
   retain:
     days: 7
     mode: motion
 
   events:
     pre_capture: 15
     post_capture: 15
     retain:
       default: 5
       mode: active_objects
       objects:
        person: 5
     objects:
      - person
  snapshots:
   enabled: True
   timestamp: True
   bounding_box: True
   retain:
    default: 5
    objects:
     person: 5

  rtmp:
   enabled: False

 camera2:
  ffmpeg:
    inputs:
    - path: rtsp://user:XYZ/videoMain
      roles:
       - detect
       - record

  detect:
   width: 2304
   height: 1536
   fps: 5

  record:
   enabled: True
   retain:
     days: 7
     mode: motion

   events:
     pre_capture: 15
     post_capture: 15
     retain:
       default: 5
       mode: active_objects
       objects:
        person: 5
     objects:
      - person

  snapshots:
   enabled: True
   timestamp: True
   bounding_box: True
   retain:
    default: 5
    objects:
     person: 5

  rtmp:
   enabled: False
```

### Relevant log output

```shell
frigate_camera_tpu | [2022-10-04 23:34:16] frigate.record                 ERROR   : could not convert string to float: ''
frigate_camera_tpu | [2022-10-04 23:34:21] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate_camera_tpu | [2022-10-04 23:34:21] frigate.record                 ERROR   : could not convert string to float: ''
frigate_camera_tpu | [2022-10-04 23:34:26] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate_camera_tpu | [2022-10-04 23:34:26] frigate.record                 ERROR   : could not convert string to float: ''
frigate_camera_tpu | [2022-10-04 23:34:31] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate_camera_tpu | [2022-10-04 23:34:31] frigate.record                 ERROR   : could not convert string to float: ''
frigate_camera_tpu | [2022-10-04 23:34:36] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
```

### FFprobe output from your camera

```shell
/
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Foscam G4EP
