### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by diveschumi** [blakeblackshear/frigate#4022]
### Describe the problem you are having

I have set min_area = 1500 and max_area = 30000 at person, but sometimes I get a detection of a person between only 300 and 700. Why?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
cameras:
  objects:
    filters:
      person:
        threshold: 0.6
        min_area: 1500
        max_area: 30000
```

### Relevant log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
