### ISSUE TITLE
[Support]: 24h recording with events but no event recordings

### ISSUE THREAD

**Issue by nelsongraca** [blakeblackshear/frigate#4027]
### Describe the problem you are having

Hi, I'm currently using Frigate in order to have 24h recording and events in HA (turn on a light if a person is detected for example), but I don't find a way to have 24h recording and detection on but without keeping those event recordings, snapshots can be easily disabled but not events.

It's a little hard to explain what I want so here are some examples (event retention is 1 week, continuous recording 48h):
When at home I want continuous 24h recording and events, but no specific recordings or snapshots of those events.
When away I want continuous 24h recording and events including those specific recording events and snapshots.

### Version

0.11.0-3846A13

### Frigate config file

```yaml
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 30
      mode: motion
      objects:
        cat: 1
        dog: 1
```

### Relevant log output

```shell
irrelevant
```

### FFprobe output from your camera

```shell
irrelevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

**Comment by NickM-27** [comment]
```yaml
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 30
      mode: motion
      objects:
        cat: 1
        dog: 1
```

This means you're asking to keep 30 days of events

Simply change it to

```yaml
record:
  enabled: true
  expire_interval: 60
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 0
```
