### ISSUE TITLE
[Support]: High CPU w/ Coral & GPU Hardware Acceleration

### ISSUE THREAD

**Issue by lzmith8080** [blakeblackshear/frigate#4033]
### Describe the problem you are having

Hi all. Apologies in advance for yet another "high CPU" ticket, but I couldn't find anything in existing issues around my use case so I wanted to validate what I'm experiencing.

I currently have Frigate running in a docker container on my home server. The home server has an i5-9600k, GTX 1070, and a Coral Dual-Edge TPU running through a PCIE adapter. Typically, my CPU load is <10% without frigate running. My camera setup consists of nine 4k Reolink cameras ([streaming 2k@20hz](https://i.imgur.com/lVJG9FB.png)) with detect and record enabled on all nine cameras. In the config linked, I only have one cam listed, but all nine are effectively identical just with differing zones. 

With frigate running, my overall CPU utilization hovers between 40-60%. I know my hardware acceleration is working successfully [as this is the result of running `nvidia-smi` on my unraid host](https://i.imgur.com/mHJ96dq.png). If I run `top` on my server, [this is the result](https://i.imgur.com/G4bJvVs.png), indicating the CPU is still doing quite a bit of work for ffmpeg.

Things I've tried:
- Disabling 4k birdseye view - No impact
- Using the [recommended reolinkcamera specs](https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others) - Errors, maybe due to these being different models?
- Dropping the quality of live to `25` instead of `10` - Seemingly no impact
- Dropping Camera FPS from 20->10 - Maybe dropped CPU usage by 5% on average?
- Dropping camera bitrate from 6144->2048 - Another maybe 5% improvement in CPU usage (If I both lower FPS and lower bit rate, still using ~35-55% CPU)

Does this CPU utilization sound high? Is there some configuration I am missing or should try to get that usage lower?

Thanks in advance!

### Version

0.11.0-3846a13

### Frigate config file

```yaml
mqtt:
  host: <redacted>
  user: <redacted>
  password: <redacted>

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

birdseye:
  enabled: True
  width: 3840
  height: 2160
  quality: 10
  mode: continuous

live:
  height: 1440
  quality: 10

record:
  enabled: True
  events:
    retain:
      mode: active_objects
      default: 30

ffmpeg:
  hwaccel_args: 
  - -c:v 
  - h264_cuvid

detect:
  width: 2560
  height: 1440
  fps: 5

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>@<redacted>:554/h264Preview_01_main
          roles:
            - detect
            - record
    <Redacted Record/Zones settings>
```

### Relevant log output

```shell
N/A no logs
```

### FFprobe output from your camera

```shell
...>ffprobe rtsp://<redacted>@<redacted>:554/h265Preview_01_main
Input #0, rtsp, from 'rtsp://<redacted>@<redacted>:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000250, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 25.08 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink 822a's and 820a's
