### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by Steidy12** [blakeblackshear/frigate#4037]
### Describe the problem you are having

Frigate addon will not start up. I am not shure what I am missing. Please help, I have tried multiple times and ways. Thank you!

### Version

0.11.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.68.57
  port: 1883
  user: mqtt-user
  password: Password
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
birdseye:
  enabled: True
  width: 640
  height: 480
  quality: 10
  mode: motion
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.68.77:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - rtmp
            - record
            - snapshot
    record:
      enabled: True
      events: 
        retain:
          default: 10
    snapshots:
      enabled: True
    detect:
      width: 640
      hight: 480
      fps: 10
      stationary:
        interval: 0
        threshold: 50
    motion:
      mask:
    zones:
    objects:
      track:
      filters:
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-10-07 09:39:30] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> driveway
  object of type 'NoneType' has no len() (type=type_error)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 521, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> driveway
  object of type 'NoneType' has no len() (type=type_error)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
A few things here:
1. There is no snapshot role so you should remove that
2. You have to enter values for everything. You have lots of definitions at the bottom with no values and they should all be removed. 



```yaml
motion:
      mask:
    zones:
    objects:
      track:
      filters:
```

**Comment by Steidy12** [comment]
Thank you NickM-27 for the reply.

I just removed those from the config file, but that changes nothing for the config erros on start up.

**Comment by NickM-27** [comment]
Paste new config and logs

**Comment by Steidy12** [comment]
mqtt:
  host: 192.168.68.57
  port: 1883
  user: mqtt-user
  password: Password
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
birdseye:
  enabled: True
  width: 640
  height: 480
  quality: 10
  mode: motion
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Paytenls20@192.168.68.70:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - rtmp
            - record
    record:
      enabled: True
      events: 
        retain:
          default: 10
    snapshots:
      enabled: True
    detect:
      width: 640
      hight: 480
      fps: 10
      stationary:
        interval: 0
        threshold: 50

.............................................................................................................................................................................................................

1 validation error for FrigateConfig
cameras -> driveway -> detect -> hight
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 521, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> driveway -> detect -> hight
  extra fields not permitted (type=value_error.extra)

**Comment by Steidy12** [comment]
mqtt:
host: 192.168.68.57
port: 1883
user: mqtt-user
password: Password
detectors:
cpu1:
type: cpu
cpu2:
type: cpu
birdseye:
enabled: True
width: 640
height: 480
quality: 10
mode: motion
cameras:
driveway:
ffmpeg:
inputs:
- path: rtsp://admin:Password@192.168.68.77:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
roles:
- detect
- rtmp
- record
record:
enabled: True
events:
retain:
default: 10
snapshots:
enabled: True
detect:
width: 640
hight: 480
fps: 10
stationary:
interval: 0
threshold: 50

.............................................................................................................................................................................................................

1 validation error for FrigateConfig
cameras -> driveway -> detect -> hight
extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
File "/opt/frigate/frigate/app.py", line 332, in start
self.init_config()
File "/opt/frigate/frigate/app.py", line 82, in init_config
user_config = FrigateConfig.parse_file(config_file)
File "/opt/frigate/frigate/config.py", line 942, in parse_file
return cls.parse_obj(config)
File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 521, in parse_obj
return cls(**obj)
File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 341, in init
raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> driveway -> detect -> hight
extra fields not permitted (type=value_error.extra)

**Comment by Steidy12** [comment]
mqtt:
  host: 192.168.68.57
  port: 1883
  user: mqtt-user
  password: Password
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
birdseye:
  enabled: True
  width: 640
  height: 480
  quality: 10
  mode: motion
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Password@192.168.68.77:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - rtmp
            - record
    record:
      enabled: True
      events: 
        retain:
          default: 10
    snapshots:
      enabled: True
    detect:
      width: 640
      hight: 480
      fps: 10
      stationary:
        interval: 0
        threshold: 50

**Comment by Steidy12** [comment]
1 validation error for FrigateConfig
cameras -> driveway -> detect -> hight
extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
File "/opt/frigate/frigate/app.py", line 332, in start
self.init_config()
File "/opt/frigate/frigate/app.py", line 82, in init_config
user_config = FrigateConfig.parse_file(config_file)
File "/opt/frigate/frigate/config.py", line 942, in parse_file
return cls.parse_obj(config)
File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 521, in parse_obj
return cls(**obj)
File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 341, in init
raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> driveway -> detect -> hight
extra fields not permitted (type=value_error.extra)

**Comment by NickM-27** [comment]
You spelled height incorrectly under detect

```yaml
      width: 640
      hight: 480
      fps: 10
      stationary:
        interval: 0
        threshold: 50
```
