### ISSUE TITLE
[Config Support]: Unable to Run Frigate When Building Container Image from Source

### ISSUE THREAD

**Issue by MJ33** [blakeblackshear/frigate#4042]
### Describe the problem you are having

I built a Docker Container Image using the **dev** branch source code, but when I start Frigate I get a _Connection refused_ error

### Version

release-0.11.0

### Frigate config file

```yaml
mqtt:
host: myhostname.net
port: 8883
client_id: elitedeskpc
user: user
password: 1234
topic_prefix: devices/elitedeskpc/messages/events
tls_ca_certs: /config/digicert.cer
tls_client_cert: /config/certificate.cer
tls_client_key: /config/key.cer
logger:
# Optional: default log level (default: shown below)
default: info
# Optional: module by module log level configuration
logs:
frigate.mqtt: debug
detectors:
coral:
type: edgetpu
device: usb
objects:
track:
- person
cameras:
12EdwardOffice:
ffmpeg:
inputs:
- path: rtsp://password@192.168.88.208/cam/realmonitor?channel=1&subtype=0
roles:
- rtmp
- record
- path: rtsp://password@192.168.88.208/cam/realmonitor?channel=1&subtype=2
roles:
- detect
detect:
width: 1280
height: 720
record:
enabled: True
retain:
days: 2
mode: all
snapshots:
enabled: True
timestamp: False
bounding_box: True
retain:
default: 2
12EdwardField:
ffmpeg:
inputs:
- path: rtsp://password@192.168.88.207/cam/realmonitor?channel=1&subtype=0
roles:
- rtmp
- record
- path: rtsp://password@192.168.88.207/cam/realmonitor?channel=1&subtype=2
roles:
- detect
detect:
width: 1280
height: 720
record:
enabled: True
retain:
days: 2
mode: all
snapshots:
enabled: True
timestamp: False
bounding_box: True
retain:
default: 2
```

### Relevant log output

```shell
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [services.d] done.
frigate  | [2022-10-08 11:16:33] frigate.app                    INFO    : Starting Frigate (0.11.0-7c60753)
frigate  | Starting migrations
frigate  | [2022-10-08 11:16:33] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-10-08 11:16:33] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [2022-10-08 11:16:34] frigate.app                    INFO    : Output process started: 219
frigate  | [2022-10-08 11:16:34] ws4py                          INFO    : Using epoll
frigate  | [2022-10-08 11:16:34] frigate.app                    INFO    : Camera processor started for 12EdwardOffice: 224
frigate  | [2022-10-08 11:16:34] frigate.app                    INFO    : Camera processor started for 12EdwardField: 227
frigate  | [2022-10-08 11:16:34] frigate.app                    INFO    : Capture process started for 12EdwardOffice: 229
frigate  | [2022-10-08 11:16:34] frigate.app                    INFO    : Capture process started for 12EdwardField: 230
frigate  | [2022-10-08 11:16:34] frigate.mqtt                   DEBUG   : MQTT connected
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [2022-10-08 11:16:34] ws4py                          INFO    : Using epoll
frigate  | [2022-10-08 11:16:35] frigate.mqtt                   DEBUG   : MQTT connected
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [2022-10-08 11:16:34] detector.coral                 INFO    : Starting detection process: 218
frigate  | [2022-10-08 11:16:34] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-10-08 11:16:36] frigate.edgetpu                INFO    : TPU found
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [2022-10-08 11:16:40] frigate.mqtt                   DEBUG   : MQTT connected
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [2022-10-08 11:16:45] frigate.mqtt                   DEBUG   : MQTT connected
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | [2022-10-08 11:16:54] ffmpeg.12EdwardOffice.record_rtmp ERROR   : [tcp @ 0x555d30726000] Connection to tcp://127.0.0.1:1935?tcp_nodelay=0 failed: Connection refused
frigate  | [2022-10-08 11:16:54] ffmpeg.12EdwardOffice.record_rtmp ERROR   : [rtmp @ 0x555d3070b3c0] Cannot open connection tcp://127.0.0.1:1935?tcp_nodelay=0
frigate  | [2022-10-08 11:16:54] ffmpeg.12EdwardOffice.record_rtmp ERROR   : rtmp://127.0.0.1/live/12EdwardOffice: Connection refused
frigate  | [2022-10-08 11:16:54] watchdog.12EdwardOffice        INFO    : Terminating the existing ffmpeg process...
frigate  | [2022-10-08 11:16:54] watchdog.12EdwardOffice        INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | [2022-10-08 11:16:54] ffmpeg.12EdwardField.record_rtmp ERROR   : [tcp @ 0x563c9f39c900] Connection to tcp://127.0.0.1:1935?tcp_nodelay=0 failed: Connection refused
frigate  | [2022-10-08 11:16:54] ffmpeg.12EdwardField.record_rtmp ERROR   : [rtmp @ 0x563c9f39c840] Cannot open connection tcp://127.0.0.1:1935?tcp_nodelay=0
frigate  | [2022-10-08 11:16:54] ffmpeg.12EdwardField.record_rtmp ERROR   : rtmp://127.0.0.1/live/12EdwardField: Connection refused
frigate  | [2022-10-08 11:16:54] watchdog.12EdwardField         INFO    : Terminating the existing ffmpeg process...
frigate  | [2022-10-08 11:16:54] watchdog.12EdwardField         INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
frigate  | execlineb: usage: execlineb [ -p | -P | -S nmin | -s nmin ] [ -q | -w | -W ] [ -c commandline ] script args
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

When running Frigate from Docker Container Image hosted by blakeblackshear, it runs fine.
