### ISSUE TITLE
[Support]: Frigate repeating events?

### ISSUE THREAD

**Issue by mikerenna** [blakeblackshear/frigate#4048]
### Describe the problem you are having

I'm troubleshooting repeating notifications. Every 30-60 seconds it seems I'm getting sent the same images representing the last detected object which could be hours ago. The notification in HA is following the MQTT topic for events and I can confirm that frigate is publishing what appear to be duplicate object detection events. Anyone have any ideas on why that might be happening?

### Version

0.11.0-3846A13

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.14
  user: michael
  password: XXXXXXXXXXXX

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: True
  timestamp: True

birdseye:
  enabled: True
  mode: continuous

cameras:
  driveway: #amcrest 4k 
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxx@192.168.0.31:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      # filters:
        # person:
          # mask:
            # - 140,110,305,112,431,134,704,195,704,0,0,0,0,117
        # car:
          # mask:
            # - 208,193,0,296,0,215,0,117,41,90,380,124
            # - 704,198,704,480,349,480,497,151
        # motorcycle:
          # mask:
            # - 208,193,0,296,0,215,0,117,41,90,380,124
            # - 704,198,704,480,349,480,497,151
        # bicycle:
          # mask:
            # - 208,193,0,296,0,215,0,117,41,90,380,124
            # - 704,198,704,480,349,480,497,151              
    zones:
      driveway_main:
        coordinates: 332,137,227,176,105,238,0,298,0,480,338,480,386,389,449,244,481,166
        objects:
          - car
          - bicycle
          - motorcycle
      front_yard_entire:
        coordinates: 0,480,704,480,704,265,704,213,528,159,357,126,106,100,0,111
        objects:
          - person
      street:
        coordinates: 140,110,305,112,431,134,704,195,704,0,0,0,0,117
        # objects:
          # filters:
            # car:
              # mask:
    # snapshots:
      # required_zones:
        # - driveway_main
        # - front_yard_entire        
    motion:
      mask:
        - 290,0,704,0,704,480,341,480,479,156,341,132,0,304,0,102,0,0
    birdseye:
      mode: objects    
  
  front_yard: #amcrest  
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxxx@192.168.0.34:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
      filters:
        person:
          threshold: 0.5
          # mask:
            # - 368,89,640,92,640,0,0,0,0,137
        # car:
          # mask:
            # - 0,480,640,480,640,342,533,202,436,85,322,94,0,133
            # - 368,89,640,92,640,0,0,0,0,137
        # motorcycle:
          # mask:
            # - 0,480,640,480,640,342,533,202,436,85,322,94,0,133
            # - 368,89,640,92,640,0,0,0,0,137
        # bicycle:
          # mask:
            # - 0,480,640,480,640,342,533,202,436,85,322,94,0,133
            # - 368,89,640,92,640,0,0,0,0,137
            
    # snapshots:
      # required_zones:
        # - driveway_main
        # - front_yard_entire 
    zones:
      driveway_main:
        coordinates: 529,104,640,203,640,319,535,196,435,103
        objects:
          - car
          - bicycle
          - motorcycle
      street:
        coordinates: 364,100,640,103,640,0,0,0,0,146
        # objects:
          # filters:
            # car:
              # mask:
      front_yard_entire:
        coordinates: 0,480,640,480,640,298,640,104,397,105,97,141,77,249,0,396
        objects:
          - person
    motion:
      mask:
        - 0,314,60,263,128,132,392,104,640,100,640,0,383,0,171,0,0,0
    birdseye:
      mode: objects   
  front_porch: # reolink
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxx@192.168.0.30:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    birdseye:
      mode: objects   

  doorbell: # amcrest ad410
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxxx@192.168.0.43:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    birdseye:
      mode: objects   
    motion:
      mask:
        - 418,280,413,232,247,227,251,274
  back_porch: #amcrest 4k 
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.0.35:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

  garage_side_door: #amcrest  
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.0.33:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    birdseye:
      mode: objects   
    motion:
      mask:
        - 178,239,333,211,305,139,257,0,97,0
        - 640,89,640,0,536,0
  play_set: #amcrest  
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxx@192.168.0.36:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      # hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    birdseye:
      mode: objects
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"back_porch":{"camera_fps":5.1,"capture_pid":249,"detection_fps":4.8,"pid":231,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":4.8,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.94,"pid":216}},"doorbell":{"camera_fps":5.1,"capture_pid":246,"detection_fps":0.0,"pid":230,"process_fps":5.1,"skipped_fps":0.0},"driveway":{"camera_fps":5.0,"capture_pid":236,"detection_fps":0.0,"pid":224,"process_fps":5.0,"skipped_fps":0.0},"front_porch":{"camera_fps":5.1,"capture_pid":242,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"front_yard":{"camera_fps":5.1,"capture_pid":239,"detection_fps":0.0,"pid":227,"process_fps":5.0,"skipped_fps":0.0},"garage_side_door":{"camera_fps":5.0,"capture_pid":252,"detection_fps":0.0,"pid":233,"process_fps":5.0,"skipped_fps":0.0},"play_set":{"camera_fps":5.0,"capture_pid":260,"detection_fps":0.0,"pid":234,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.0","storage":{"/dev/shm":{"free":60.8,"mount_type":"tmpfs","total":67.1,"used":6.4},"/media/frigate/clips":{"free":227039.1,"mount_type":"ext4","total":249365.4,"used":9584.6},"/media/frigate/recordings":{"free":227039.1,"mount_type":"ext4","total":249365.4,"used":9584.6},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":24278,"version":"0.11.0-3846a13"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest

**Comment by NickM-27** [comment]
This is the expected behavior, if an object is stationary then it will have an event published to the events topic every 30 seconds. As the user you should use filters to ensure you only get notifications when you want them.

**Comment by mikerenna** [comment]
No the object are long gone when I'm getting the repeated events. These are new MQTT messages and the image I'm getting is the same old one over and over. For two different cameras.

**Comment by NickM-27** [comment]
Odds are you have a false positive then, an object is leaving and frigate is seeing something else as that person. 

I'd recommend watching the debug view of the camera in frigate while this is happening with bounding boxes enabled. 

In any case, would need a paste of the MQTT payload to understand more of what is going on.

**Comment by mikerenna** [comment]
Thanks Nick. It's strange. Notifications are including the same picture, which is the last object identified such as the mailman who came by only one time. The mqtt messages are almost identical (to my eyes) with the exception of the snapshot time. Possible something new is triggering it but sending historical snapshot.    The event list in frigate UI is not changing. the snapshot i keep getting sent is still the top of list.  in debug mode i didn't see any bounding boxes but i do see yellow detection boxes with names like car and percent. I can't tell if they correspond to the most recent notification but they dont' show in the event list in the UI. here are a couple of recent mqtt messages. I'm not sure what to look for here so any insight is appreciated. 

{"before": {"id": "1665321026.215654-mveutt", "camera": "driveway", "frame_time": 1665322492.531154, "snapshot_time": 1665321026.349371, "label": "person", "top_score": 0.84375, "false_positive": false, "start_time": 1665321026.215654, "end_time": null, "score": 0.609375, "box": [430, 89, 438, 109], "area": 160, "ratio": 0.4, "region": [334, 0, 682, 348], "stationary": true, "motionless_count": 7284, "position_changes": 1, "current_zones": ["street"], "entered_zones": ["front_yard_entire", "street"], "has_clip": false, "has_snapshot": true}, "after": {"id": "1665321026.215654-mveutt", "camera": "driveway", "frame_time": 1665322552.672478, "snapshot_time": 1665321026.349371, "label": "person", "top_score": 0.84375, "false_positive": false, "start_time": 1665321026.215654, "end_time": null, "score": 0.609375, "box": [430, 89, 438, 109], "area": 160, "ratio": 0.4, "region": [334, 0, 682, 348], "stationary": true, "motionless_count": 7585, "position_changes": 1, "current_zones": ["street"], "entered_zones": ["front_yard_entire", "street"], "has_clip": false, "has_snapshot": true}, "type": "update"}

{"before": {"id": "1665321026.215654-mveutt", "camera": "driveway", "frame_time": 1665322552.672478, "snapshot_time": 1665321026.349371, "label": "person", "top_score": 0.84375, "false_positive": false, "start_time": 1665321026.215654, "end_time": null, "score": 0.609375, "box": [430, 89, 438, 109], "area": 160, "ratio": 0.4, "region": [334, 0, 682, 348], "stationary": true, "motionless_count": 7585, "position_changes": 1, "current_zones": ["street"], "entered_zones": ["front_yard_entire", "street"], "has_clip": false, "has_snapshot": true}, "after": {"id": "1665321026.215654-mveutt", "camera": "driveway", "frame_time": 1665322613.128181, "snapshot_time": 1665321026.349371, "label": "person", "top_score": 0.84375, "false_positive": false, "start_time": 1665321026.215654, "end_time": null, "score": 0.609375, "box": [430, 89, 438, 109], "area": 160, "ratio": 0.4, "region": [334, 0, 682, 348], "stationary": true, "motionless_count": 7887, "position_changes": 1, "current_zones": ["street"], "entered_zones": ["front_yard_entire", "street"], "has_clip": false, "has_snapshot": true}, "type": "update"}

**Comment by NickM-27** [comment]
> in debug mode i didn't see any bounding boxes but i do see yellow detection boxes with names like car and percent.

That is what a bounding box is, showing the detected objects.

Both of your MQTT payloads have `stationary: true` which means it is in fact what I described above. An object is stationary and that means a message will be sent once a minute, note that the image will not necessarily update.

**Comment by NickM-27** [comment]
It also has `label: person` so there is either an actual person on that camera or a false positive. Judging by the fact that the `area: 160` it is most likely a false positive

**Comment by mikerenna** [comment]
Thank you. I can work on eliminating that. if you have a section of the image that you want to exclude entirely, what is the best way to do that? a filter mask? That doesn't seem to have the effect i was expecting. required zones also don't seem to have an impact. are these event mqtt messages going to be triggered always or should they be mitigated by false positive configuration considerations?

**Comment by mikerenna** [comment]
can/should i add a condition to the notification that simply ignores stationary true messages?

**Comment by NickM-27** [comment]
You can, my first suggestion though would be finding the false positive and using https://docs.frigate.video/guides/false_positives to filter it out.

**Comment by mikerenna** [comment]
ok i'll try that first. any thoughts on ways to just eliminate an entire area? from the detection process? i've been over the documentation and may be missing something if that exits. thanks again for the responses/insights.

**Comment by NickM-27** [comment]
Object masks can be used but that's usually a last resort. In this case a min_area filter should take care of this one at least.

**Comment by mikerenna** [comment]
is the number i see next to the yellow box the pixel count? After the %?  For example there is a mailbox that shows person 61% 160. That 160 is a number i can use for min value? for example set a min value for 200 and it should ignore it?  I also see a car 61% 490. So i can set min of 500 for car?

**Comment by NickM-27** [comment]
That number is the area of the bounding box yes. 

And while you could set it to a number just above what is there, I'd recommend looking at previous true positive events snapshots and seeing what the number is. 

For example a car is likely to be at least 2000 probably

**Comment by mikerenna** [comment]
thank you again. I'll give that all a try.

**Comment by databoy2k** [comment]
I just wanted to throw in my 2 cents. I'm getting a positive in the active area (an area that I don't want to mask out) because of a pile of snow that is apparently bothering Frigate. I'm in the enviable position of not caring if someone is stationary, so I don't want my Home Assistant notifications going off every minute.

Solved by adding a template condition to the automation: {{ trigger.payload.json["before"]["stationary"] == 'false' }}

**Comment by avico78** [comment]
@mikerenna - have u managed to solved it?
My problem is similiar , if a car parking near my house - i'm getting same message over and over(every min),
I tried @databoy2k  but it behave even worse ,
while there's statinory object - it send 2-3 message ,
when the stationary object disappear - it start sending the same message over and over .
I can't mask or mark the region as camera angle is quite problematic ,

this is the automaiton i got to:

```
- alias: Notify of events
  trigger:
    platform: mqtt
    topic: frigate/events
  condition:
    condition: template
    value_template: >
       {{ trigger.payload_json["before"]["stationary"] == false }}
  action:
    - service: notify.avico_ha
      data:
        title: Send an image
        message: Message
        data:
          photo:
            - url: 'https://xxxxxxxxxxx.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
              caption: '{{trigger.payload_json["after"]["label"]}} was detected by {{trigger.payload_json["after"]["camera"]}} score ({{trigger.payload_json["after"]["top_score"]}})'              

```
