### ISSUE TITLE
[Support]: Birdseye displays active camera when below ratio

### ISSUE THREAD

**Issue by nerodark** [blakeblackshear/frigate#4061]
### Describe the problem you are having

I have cameras set to track persons only. Birdseye's mode is objects only. My person min ratio is 0.5 and threshold is 0.7 (the defaults). I expected that Birdseye behaves to only display active cameras when person's score is above 0.7. It displays them even between 0.5 and 0.7. For score below 0.5, that's correct, birdseye doesn't display them.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: ...
  user: ...
  password: ...

detectors:
  coral:
    type: edgetpu
    device: usb

ui:
  use_experimental: True

birdseye:
  enabled: True
  width: 960
  height: 576
  quality: 1
  mode: objects

#ffmpeg:
  #global_args: -loglevel info
  #hwaccel_args: -c:v h264_v4l2m2m

detect:
  width: 960
  height: 576

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000

motion:
  improve_contrast: True

record:
  enabled: True
  events:
    objects:
      - person

snapshots:
  enabled: True

rtmp:
  enabled: False

live:
  height: 576
  quality: 1

cameras:
  camera_zero:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - rtmp
    detect:
      enabled: False
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - detect
            - rtmp
    objects:
      filters:
        person:
          mask:
            - 0,409,192,259,319,324,598,161,677,136,766,122,960,130,960,0,0,0
            - 960,576,960,293,855,221,675,346,679,576
  camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - detect
            - rtmp
    objects:
      filters:
        person:
          mask:
            - 0,374,268,296,638,266,960,407,960,0,0,0
            - 689,535,797,535,804,508,690,508
            - 566,576,578,308,91,421,120,576
  camera_3:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - detect
            - rtmp
    objects:
      filters:
        person:
          mask:
            - 960,0,960,576,762,576,255,366,173,315,154,173,0,189,0,0
            - 0,576,381,576,379,525,0,519
  camera_4:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
            - detect
            - rtmp
    objects:
      filters:
        person:
          mask:
            - 0,0,862,0,916,130,877,253,682,350,493,298,462,365,342,344,333,263,218,222,121,416,0,343
            - 790,503,790,527,690,527,690,503
```

### Relevant log output

```shell
Not relevant.
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision
