### ISSUE TITLE
[Support]: Chrome now supports H.265 - Direct link playback works but playback in Event viewer still has issues. 

### ISSUE THREAD

**Issue by cartersdad2008** [blakeblackshear/frigate#4067]
### Describe the problem you are having

Chrome now supports H.265 video playback, officially supported for Chrome 104, and with a little investigation also found out that it’s enabled by default for Chrome 105 for all platforms. All my cameras record in this format. I've tested this in both desktop chrome and on Android and it's working. Direct links to the mp4, like the ones send in HA notifications, work great now. Video playback from the event viewer in Frigate still has issues though. I checked the console output in chrome when I try to play videos from the event viewer in frigate, the error that it reports in attached in the "Relevant log output" section. 

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
mqtt:
  host: 192.168.88.220
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: *******
  password: ***********
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
  
detectors:
  coral:
    type: edgetpu
    device: usb
    

detect:        
  width: 704
  height: 480
  fps: 5
  
record:
  enabled: True
  events:
    max_seconds: 30
    pre_capture: 3
    post_capture: 3
    objects:
      - car
      - person
    retain:
      default: 10

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 10
    
rtmp:
  enabled: False
  
objects:
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.78
    car:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.75
    dog:
      min_area: 5000
      max_area: 100000
      min_score: 0.6
      threshold: 0.78   

cameras:
  porch:
    zones:
      driveway:
        coordinates: 297,80,435,129,561,102,616,133,573,193,218,98
      porchdeck:
        coordinates: 612,480,704,344,572,272,382,380,326,364,181,419,208,480
      frontyard:
        coordinates: 638,208,228,101,72,141,173,414
    objects:
      track:
        - person
        - car
        - dog
      filters:
        car:
          mask:
            - 485,194,704,243,704,117,559,97
    ffmpeg:
      inputs:
        - path: rtsp://*************@192.168.88.200:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
  garage:
    zones:
      driveway:
        coordinates: 0,321,149,191,275,123,333,121,340,152,586,196,507,228,652,480,0,480
    objects:
      track:
        - person
        - car
        - dog
      filters:
        car:
          mask: 704,480,704,246,157,238,0,374,0,480
    ffmpeg:
      inputs:
        - path: rtsp://***************@192.168.88.194:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
  breezewayEntry:
    zones:
      cement:
        coordinates: 601,480,600,270,175,211,0,323,0,414,68,480
      frontyard:
        coordinates: 592,140,521,131,498,66,338,67,310,74,320,135,203,208,593,261
    objects:
      track:
        - person
        - car
        - dog
    ffmpeg:
      inputs:
        - path: rtsp://*****************@192.168.88.196:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
  backyard:
    objects:
      track:
        - person
        - dog
      filters:
        person:
          mask: 212,413,155,21,62,113,83,439
    ffmpeg:
      inputs:
        - path: rtsp://*****************@192.168.88.197:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - record
  backdoorbell:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://****************@192.168.88.81:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - record
  frontdoorbell:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://*************@192.168.88.147:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            - record
```

### Relevant log output

```shell
video.es-cba2b316.htcmvalaG3LD.js:31 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Playback cannot continue. No available working or supported playlists. je {code: 3, message: 'Playback cannot continue. No available working or supported playlists.'}code: 3message: "Playback cannot continue. No available working or supported playlists."[[Prototype]]: ObjectMEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: 0message: ""
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest UltraHD 5MP IP5M-B1186EW-28MM
