### ISSUE TITLE
[Support]: wrong detecting objects as a perso

### ISSUE THREAD

**Issue by TheCherry** [blakeblackshear/frigate#4080]
### Describe the problem you are having

The algro keeps wrong detecting objects as a person.
I know that I can fix that by `min_area` argument - but then persons far away don't will be tracked.
Best option is to train the model right? Or do I have here any another option?

![grafik](https://user-images.githubusercontent.com/1090782/195681934-3619e345-e5bd-499b-a10f-30ffcb85f974.png)
![grafik](https://user-images.githubusercontent.com/1090782/195682001-0c6a50dc-ca3d-4fb6-bf21-6f5fbf754903.png)

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.100

detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
  cpu3:
    type: cpu
    num_threads: 1
  cpu4:
    type: cpu
    num_threads: 1
  cpu5:
    type: cpu
    num_threads: 1
  cpu6:
    type: cpu
    num_threads: 1
  cpu7:
    type: cpu
    num_threads: 1
  cpu8:
    type: cpu
    num_threads: 1
  cpu9:
    type: cpu
    num_threads: 1
  cpu10:
    type: cpu
    num_threads: 1


objects:
  track:
    - person
  filters:
    person:
      min_score: 0.4
    car:
      min_score: 0.6

detect:
  stationary:
    interval: 10
    threshold: 30

cameras:
  KameraEinfahrtSchuppen:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://XXX.XXX.XXX.XXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=XXXXXXXXXX
          roles:
            - record
            - detect
        - path: http://XXX.XXX.XXX.XXX/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=XXXXXXXXX
          roles:            
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 10
    zones:
      grundstueck:
        coordinates: 2560,1171,2560,1920,722,1920,630,513,825,354,870,184,1301,178,1463,259,1647,482,2098,924
        objects:
          - person
    motion:
      threshold: 10
      mask:
        - 782,1513,1116,1503,1105,1009,1087,806,730,794
        - 2560,0,1711,0,0,0,0,221,1393,227,1593,363,2560,1213
        - 587,1920,0,1920,0,0,916,0,771,298,646,530
    record:
      events:
        required_zones:
          - grundstueck
    snapshots:
        required_zones:
          - grundstueck

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink
