### ISSUE TITLE
[Support]: The media could not be loaded

### ISSUE THREAD

**Issue by sbelongie** [blakeblackshear/frigate#4086]
### Describe the problem you are having

Having an issue with just one camera. It looks like a few days ago one of my cameras stopped being able to playback video in the browswer.  I am able to download the file and play it though. 

The error I am getting is:  The media could not be loaded, either because the server or network failed or because the format is not supported.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xxx
  user: xxxx
  password: password
  stats_interval: 60
#logger:
  # Optional: default log level (default: shown below)
#  default: debug
  # Optional: module by module log level configuration
 # logs:
 #   frigate.http: debug


record:
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 20
    
cameras:
  backyard_north:
    ffmpeg:
      inputs:
        - path: rtsp://user:Password@192.168.1.x:554/live
          roles:
            - record
            - rtmp
        - path: rtsp://user:Password@192.168.1.x:554/cam/realmonitor?channel=1&subtype=1
          roles:
           - detect     
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 15
          mode: motion
    snapshots:
      enabled: True
      retain:
        default: 3      
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.74
  Backyard_south:
    ffmpeg:
      inputs:
        - path: rtsp://user:Password@192.168.1.x:554/live
          roles:
            - record
            - rtmp
        - path: rtsp://user:Password@192.168.1.x:554/cam/realmonitor?channel=1&subtype=1
          roles:
           - detect     
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    record:
      enabled: true
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 15
          mode: motion       
    snapshots:
      enabled: True
      retain:
        default: 3      
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.74
  Front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp:user:Password@192.168.1.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - rtmp
        - path: rtsp:user:Password@192.168.1.x:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
           - detect     
    detect:
      width: 1280
      height: 720
      fps: 5
      stationary:
        interval: 0
        threshold: 50
    record:
      enabled: true
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 15
          mode: motion       
    snapshots:
      enabled: True
      retain:
        default: 3      
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bicycle
        - motorcycle
        - bird
      filters:
        car:
          mask:
            - 1280,377,1280,511,968,470,970,382
        person:
          threshold: 0.60

ffmpeg:
  output_args:
     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  hwaccel_args:
    -c:v h264_qsv
birdseye:
  enabled: false
```

### Relevant log output

```shell
none at this time
```

### FFprobe output from your camera

```shell
none at this time
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

amcrest AD410
