### ISSUE TITLE
[Camera Support]: Camera with yuvj420p(pc, bt709, progressive) issues

### ISSUE THREAD

**Issue by truxntrax** [blakeblackshear/frigate#4099]
### Describe the problem you are having

I have several camera's but one I have issues with and the thing I see different is this output from ffprobe: yuvj420p(pc, bt709, progressive).  The symptoms of this camera is that I cannot playback the recordings of the events, when I check if the recordings are captured for the bad cams within the folder structure, they are not.  I only see folders for the good cams within my folder structure.  It captures the still snapshot fine - so I assume the detection is working fine.  I'm 100% sure these "bad" cam did use to work on an earlier version, I think v9...  I have upgraded and not checked any recordings for some time - hence not caught when they stopped working.

When I try to play the recording on the bad cam I get this error message:
"The media could not be loaded, either because the server or network failed or because the format is not supported."

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.1
  port: 1883
  user: redacted
  password: mredacted
#clips:
#  max_seconds: 300
#  tmpfs_cache_size: 2G
#  retain:
#    default: 15
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  fri_back_facing_house:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:redacted@192.168.1.69:554/user=admin_password=_channel=1_stream=0
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain:
        days: 10
        mode: all
      events:
        retain:
          default: 10
          mode: all
    snapshots:
      enabled: True      
    motion:
      mask: 
        - 0,240,73,218,141,201,143,172,269,128,293,0,0,0
        - 1920,482,1920,0,1559,0,1583,119
        - 463,179,536,192,521,78,463,82
#removed cameras that are working ok
detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
    - dog
```

### Relevant log output

```shell
Not sure how to capture this issue in a log?
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://viewer:m0ret0life@192.168.1.69:554/user=admin_password=_channel=1_stream=0':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.200000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 5 fps, 5 tbr, 90k tbn, 180k tbc
```

### Frigate stats

```json
{"detection_fps":16.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.07,"pid":210}},"fri_back_facing_garden":{"camera_fps":5.3,"capture_pid":236,"detection_fps":4.0,"pid":221,"process_fps":3.3,"skipped_fps":0.0},"fri_back_facing_house":{"camera_fps":5.1,"capture_pid":230,"detection_fps":0.0,"pid":216,"process_fps":5.1,"skipped_fps":0.0},"fri_front_door":{"camera_fps":5.0,"capture_pid":253,"detection_fps":7.5,"pid":228,"process_fps":5.0,"skipped_fps":0.0},"fri_front_drive":{"camera_fps":5.1,"capture_pid":243,"detection_fps":5.4,"pid":226,"process_fps":5.0,"skipped_fps":0.0},"fri_play_room":{"camera_fps":5.0,"capture_pid":240,"detection_fps":0.0,"pid":222,"process_fps":5.0,"skipped_fps":0.0},"fri_side_door":{"camera_fps":5.0,"capture_pid":232,"detection_fps":0.0,"pid":218,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":118.2,"mount_type":"tmpfs","total":134.2,"used":16.0},"/media/frigate/clips":{"free":1469672.6,"mount_type":"ext4","total":1967831.6,"used":398124.1},"/media/frigate/recordings":{"free":1469672.6,"mount_type":"ext4","total":1967831.6,"used":398124.1},"/tmp/cache":{"free":842.5,"mount_type":"tmpfs","total":1000.0,"used":157.5}},"temperatures":{},"uptime":1389,"version":"0.11.1-2eada21"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Generic / unbranded H264 1080p cam 

### Any other information that may be helpful

The only difference i can see between my working cams and those that are not working is the output off ffprobe.

Bad Camera:
Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 5 fps, 5 tbr, 90k tbn, 180k tbc
Good camera:
Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 5 fps, 5 tbr, 90k tbn, 10 tbc

Any help would be very much appreciated.

Best
