### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by gadgetbazza** [blakeblackshear/frigate#4100]
### Describe the problem you are having

Camera feeds stop working, debug view shows a frozen image which is out of date, live view shows just a blank white frame.

There appear to be lots of terminating sockets in the logs.

This problem seems to be intermittent and usually goes away with a couple of restarts but re-occurs quite frequently.

### Version

0.11.0-3846A13

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.162
  user: emonpi
  password: emonpimqtt2016

#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3
#  cpu2:
#   type: cpu
#   num_threads: 3
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

record:
  enabled: True
  retain:
    days: 21
  events:
    retain:
      default: 42

cameras:
  Gate-Door-Station: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.55:554/h264_stream # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://192.168.4.55:554/h264_stream # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      filters:
        person:
          mask:
            - 640,286,450,311,213,323,0,298,0,243,0,0,640,0
        dog:
          mask:
            - 640,286,450,311,213,323,0,298,0,243,0,0,640,0
        car:
          mask:
            - 640,286,450,311,213,323,0,298,0,243,0,0,640,0
      track:
        - person
        - dog
        - car
    motion:
      mask:
        - 640,286,450,311,213,323,0,298,0,243,0,0,640,0

  PondCam1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.4.36:554/user=user_password=f1shy_channel=1_stream=0.sdp?real_stream # <----- Update for your camera
          roles:
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 2
      events:
        retain:
          default: 7

#  PondCam2: # <------ Name the camera
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.4.37:554/user=user_password=f1shy_channel=1_stream=0.sdp?real_stream # <----- Update for your camera
#          roles:
#            - detect
#            - rtmp
#        - path: rtsp://192.168.4.37:554/user=user_password=f1shy_channel=1_stream=0.sdp?real_stream # <----- Update for your camera
#          roles:
#            - record
#    rtmp:
#      enabled: True # <-- RTMP should be disabled if your stream is not H264
#    detect:
#      width: 720 # <---- update for your camera's resolution
#      height: 480 # <---- update for your camera's resolution
#    record:
#      enabled: True
#    snapshots:
#      enabled: True
#    objects:
#      track:
#        - person
#        - dog
#
  Dining-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.21/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.21/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,480,138,480,109,402,109,304,91,208,0,231

  Utility-Walkway-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.22/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.22/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

#   Lounge-Internal: # <------ Name the camera
#    ffmpeg:
#      inputs:
#        - path: rtsp://user:pass@192.168.4.23/rtsph264480p # <----- Update for your camera
#          roles:
#            - detect
#            - rtmp
#        - path: rtsp://user:pass@192.168.4.23/rtsph2641080p # <----- Update for your camera
#          roles:
#            - record
#    rtmp:
#      enabled: True # <-- RTMP should be disabled if your stream is not H264
#    detect:
#      width: 720 # <---- update for your camera's resolution
#      height: 480 # <---- update for your camera's resolution
#    record:
#      enabled: True
#    snapshots:
#      enabled: True
#    objects:
#      track:
#        - person
#        - dog

  Front-Door-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.24/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.24/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Lower-Patio-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.25/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.25/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Landing-Kids: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.26/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.26/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Landing-Master: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.27/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.27/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Cinema-Internal: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.28/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.28/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Front-Door-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.29/rtsph264480p # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.29/rtsph2641080p # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
        - car

  Gates-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.30/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.30/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 720,0,720,125,672,139,571,114,292,100,254,132,0,107,0,0

  Lounge-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.31/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.31/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  Dining-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.32/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.32/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        - 0,0,259,0,263,67,0,122
        - 460,163,396,169,326,167,323,99,415,97,433,70,461,71
        - 266,109,204,106,234,128,243,162,268,167
  Garage-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.33/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.33/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
        - car
    motion:
      mask:
        - 48,436,122,436,122,200,48,200
        - 720,131,640,96,398,41,399,0,720,0

  Driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.34/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.34/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 349,68,545,49,545,0,0,0,0,198
    objects:
      track:
        - person
        - dog
        - car

  Utility-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.35/stream2 # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.35/stream0 # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 720 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog

  BinCam-External: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.4.38:554/h264Preview_01_sub # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://user:pass@192.168.4.38:554/h264Preview_01_main # <----- Update for your camera
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,181,138,123,201,141,206,169,270,159,286,87,334,97,341,153,334,190,392,270,640,369,640,0,0,0
    objects:
      track:
        - person
        - dog
```

### Relevant log output

```shell
[2022-10-16 17:04:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50318]
[2022-10-16 17:05:24] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50102]
[2022-10-16 17:05:29] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50598]
[2022-10-16 17:05:56] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50318]
[2022-10-16 17:06:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50982]
[2022-10-16 17:06:29] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50598]
[2022-10-16 17:06:34] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51058]
[2022-10-16 17:07:21] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50982]
[2022-10-16 17:07:26] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51476]
[2022-10-16 17:07:34] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51058]
[2022-10-16 17:07:40] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51548]
[2022-10-16 17:08:26] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51476]
[2022-10-16 17:08:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51548]
[2022-10-16 17:08:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:52160]
[2022-10-16 17:09:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:52160]
[2022-10-16 17:10:06] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:53826]
[2022-10-16 17:11:06] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:53826]
[2022-10-16 17:11:11] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:54900]
[2022-10-16 17:12:11] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:54900]
[2022-10-16 17:12:36] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:56052]
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://user:pass@192.168.4.34/stream2
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://user:pass@192.168.4.34/stream2':
  Metadata:
    title           : RTSP/RTP stream from HDIPCam
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, smpte170m, progressive), 720x480 [SAR 1:1 DAR 3:2], 25 fps, 25 tbr, 90k tbn
```

### Frigate stats

```json
{"BinCam-External":{"camera_fps":5.0,"capture_pid":334,"detection_fps":0.3,"pid":249,"process_fps":5.0,"skipped_fps":0.0},"Cinema-Internal":{"camera_fps":5.1,"capture_pid":277,"detection_fps":0.0,"pid":241,"process_fps":5.1,"skipped_fps":0.0},"Dining-External":{"camera_fps":5.0,"capture_pid":303,"detection_fps":0.0,"pid":245,"process_fps":5.0,"skipped_fps":0.0},"Dining-Internal":{"camera_fps":5.1,"capture_pid":257,"detection_fps":0.0,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"Driveway":{"camera_fps":5.0,"capture_pid":326,"detection_fps":0.0,"pid":247,"process_fps":5.0,"skipped_fps":0.0},"Front-Door-External":{"camera_fps":5.0,"capture_pid":283,"detection_fps":0.0,"pid":242,"process_fps":5.0,"skipped_fps":0.0},"Front-Door-Internal":{"camera_fps":5.0,"capture_pid":262,"detection_fps":0.0,"pid":236,"process_fps":5.0,"skipped_fps":0.0},"Garage-External":{"camera_fps":5.0,"capture_pid":313,"detection_fps":0.0,"pid":246,"process_fps":5.0,"skipped_fps":0.0},"Gate-Door-Station":{"camera_fps":5.0,"capture_pid":250,"detection_fps":0.0,"pid":230,"process_fps":5.0,"skipped_fps":0.0},"Gates-External":{"camera_fps":5.0,"capture_pid":287,"detection_fps":0.0,"pid":243,"process_fps":5.0,"skipped_fps":0.0},"Landing-Kids":{"camera_fps":5.1,"capture_pid":270,"detection_fps":3.1,"pid":239,"process_fps":5.1,"skipped_fps":0.0},"Landing-Master":{"camera_fps":5.1,"capture_pid":275,"detection_fps":2.3,"pid":240,"process_fps":5.1,"skipped_fps":0.0},"Lounge-External":{"camera_fps":5.0,"capture_pid":290,"detection_fps":0.0,"pid":244,"process_fps":5.0,"skipped_fps":0.0},"Lower-Patio-External":{"camera_fps":5.0,"capture_pid":266,"detection_fps":0.0,"pid":238,"process_fps":5.0,"skipped_fps":0.0},"PondCam1":{"camera_fps":5.0,"capture_pid":253,"detection_fps":13.3,"pid":231,"process_fps":5.1,"skipped_fps":0.0},"Utility-External":{"camera_fps":5.1,"capture_pid":332,"detection_fps":0.0,"pid":248,"process_fps":5.1,"skipped_fps":0.0},"Utility-Walkway-Internal":{"camera_fps":5.1,"capture_pid":259,"detection_fps":0.0,"pid":233,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":19.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.59,"pid":10216},"coral2":{"detection_start":0.0,"inference_speed":7.61,"pid":226}},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":39.0,"mount_type":"tmpfs","total":67.1,"used":28.1},"/media/frigate/clips":{"free":4326247.4,"mount_type":"ext4","total":19023900.2,"used":14697099.2},"/media/frigate/recordings":{"free":4326247.4,"mount_type":"ext4","total":19023900.2,"used":14697099.2},"/tmp/cache":{"free":4326247.4,"mount_type":"overlay","total":19023900.2,"used":14697099.2}},"temperatures":{},"uptime":546383,"version":"0.11.0-3846a13"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Mainly Lilin, some others

### Any other information that may be helpful

Problem existed in 0.10 also, but less frequently.  Now happening practically every day.
