### ISSUE TITLE
[Config Support]: config validation

### ISSUE THREAD

**Issue by lyonsad** [blakeblackshear/frigate#4101]
### Describe the problem you are having

Valid YAML, config validation error but no helpful messages.

### Version

.11

### Frigate config file

```yaml
mqtt:
  host: homeassistant.lyons.net
  user: mqtt # <----- Can be removed if allow_anonymous is set to true
  password: XXXX # <----- Can be removed if allow_anonymous is set to true

detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

birdseye:
  enabled: false
rtmp:
  enabled: false

#Global Object Settings
objects:
  track:
    - person
    - cat
    - car
    - dog
    - horse
  # filters:
  #   person:
  #     min_area: 5000
  #     max_area: 100000
snapshots:
  enabled: true
  timestamp: true
  clean_copy: true
record:
  enabled: true
  events:
    retain:
      default: 7
      mode: active_objects
detect:
  stationary:
    interval: 1
    threshold: 50

cameras:
    front_door: # <------ Name the camera
        ffmpeg:
            inputs:
            - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.3/axis-media/media.amp?streamprofile=forai # <----- Update for your camera
            roles:
            - detect
        detect:
            width: 1440 # <---- update for your camera's resolution
            height: 1080 # <---- update for your camera's resolution
        motion:
            mask: "332,254,0,406,0,0,1061,0,1106,0,1058,93,605,171"

    driveway: # <------ Name the camera
        ffmpeg:
            inputs:
             - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.16:554/axis-media/media.amp?streamprofile=forai # <----- Update for your camera
            roles:
            - detect
    detect:
        width: 2560 # <---- update for your camera's resolution
        height: 1440  # <---- update for your camera's resolution
    motion:
        mask:
            - 500,0,580,279,0,420,0,0
            - 2560,0,2560,256,2123,264,1652,197,1507,199,1498,0
    backyard:
        objects:
            track:
                - person
                - cat
                - dog
                - horse
        ffmpeg:
            inputs:
            - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.6:554/axis-media/media.amp?streamprofile=forai # <----- Update for your camera
            roles:
            - detect
        detect:
            width: 1920 # <---- update for your camera's resolution
            height: 1080 # <---- update for your camera's resolution
    south_side: # <------ Name the camera
        objects:
            track:
            - person
            - cat
            - dog
            - horse
        ffmpeg:
            inputs:
            - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.18:554/axis-media/media.amp?streamprofile=forai # <-->
            roles:
            - detect
        detect:
            width: 1080 # <---- update for your camera's resolution
            height: 1920 # <---- update for your camera's resolution
```

### Relevant log output

```shell
[2022-10-16 18:05:35] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Your config file is not valid!                     ***
frigate  | ***    Please check the docs at                           ***
frigate  | ***    https://docs.frigate.video/configuration/index     ***
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Config Validation Errors                           ***
frigate  | *************************************************************
frigate  | 'ffmpeg'
frigate  | Traceback (most recent call last):
frigate  |   File "/opt/frigate/frigate/app.py", line 332, in start
frigate  |     self.init_config()
frigate  |   File "/opt/frigate/frigate/app.py", line 82, in init_config
frigate  |     user_config = FrigateConfig.parse_file(config_file)
frigate  |   File "/opt/frigate/frigate/config.py", line 942, in parse_file
frigate  |     return cls.parse_obj(config)
frigate  |   File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
frigate  |   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
frigate  |   File "pydantic/main.py", line 1056, in pydantic.main.validate_model
frigate  |   File "pydantic/fields.py", line 859, in pydantic.fields.ModelField.validate
frigate  |   File "pydantic/fields.py", line 994, in pydantic.fields.ModelField._validate_mapping_like
frigate  |   File "pydantic/fields.py", line 1067, in pydantic.fields.ModelField._validate_singleton
frigate  |   File "pydantic/fields.py", line 857, in pydantic.fields.ModelField.validate
frigate  |   File "pydantic/fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
frigate  |   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
frigate  |   File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
frigate  |   File "pydantic/main.py", line 704, in pydantic.main.BaseModel.validate
frigate  |   File "/opt/frigate/frigate/config.py", line 584, in __init__
frigate  |     if len(config["ffmpeg"]["inputs"]) == 1:
frigate  | KeyError: 'ffmpeg'
frigate  | 
frigate  | *************************************************************
frigate  | ***    End Config Validation Errors                       ***
frigate  | *************************************************************
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

was working fine, added some masks and another camera and cannot figure out what i did wrong.

**Comment by NickM-27** [comment]
This is not correct, yaml is space dependent language:

```yaml
cameras:
    front_door: # <------ Name the camera
        ffmpeg:
            inputs:
            - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.3/axis-media/media.amp?streamprofile=forai # <----- Update for your camera
            roles:
            - detect
        detect:
            width: 1440 # <---- update for your camera's resolution
            height: 1080 # <---- update for your camera's resolution
        motion:
            mask: "332,254,0,406,0,0,1061,0,1106,0,1058,93,605,171"
```

it might be valid yaml but it is certainly not a valid config, which would be

```yaml
cameras:
  front_door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.3/axis-media/media.amp?streamprofile=forai # <----- Update for your camera
          roles:
            - detect
    detect:
      width: 1440 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask: "332,254,0,406,0,0,1061,0,1106,0,1058,93,605,171"
```
