### ISSUE TITLE
[Config Support]: the same file works on Frigate add-on and not on Frigate LXC

### ISSUE THREAD

**Issue by Pinez83** [blakeblackshear/frigate#4106]
Hi everyone, I have a particular problem.
I have used Frigate as a Home assistant add-on until now. I use a mini-pc with proxmox, and therefore I wanted to use Frigate on lxc. I managed to do everything without problems, but I can't use the config.yml file that I have used up to now, because in the Portainer log it still gives me an error. I would like to point out that I am using EXACTLY the same file that still works in the add-on version currently.
With this configuration I get this error

 * Starting nginx nginx
   ...done.
Error parsing config: expected a dictionary for dictionary value @ data['cameras']['Ingresso']['detect']

### Version

latest

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.56
  user: xxxx
  password: xxxx
  topic_prefix: frigate
  client_id: frigate
cameras:
  Ingresso: 
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.65:554/live2.sdp
          roles:
            - detect
    rtmp:
      enabled: false 
    detect:
      width:480
      height:272
      fps:7
    objects:
      track:
        - person
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
  Sala: 
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.64/Streaming/Channels/2
          roles:
            - detect
    rtmp:
      enabled: false 
    detect:
      width:352
      height:240
      fps:15
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
* Starting nginx nginx
   ...done.
Error parsing config: expected a dictionary for dictionary value @ data['cameras']['Ingresso']['detect']
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)
