### ISSUE TITLE
[Support]: after updating from 0.10.x to 0.11.1 camera's no longer working

### ISSUE THREAD

**Issue by droosma** [blakeblackshear/frigate#4107]
### Describe the problem you are having

Running on a Raspberry pi 4 with a fresh install of DietPi x64 with Docker installed.
After upgrading to the new version the camera's no longer work. (Green panel in the interface)

### Version

0.11.1

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
database:
  path: /media/frigate/frigate.db
detect:
  width: 640
  height: 480
  fps: 5
  enabled: True
objects:
  track:
    - person
    - dog
rtmp:
  enabled: false
snapshots:
  enabled: true
  timestamp: false
  crop: true
  retain:
    objects:
      person: 14
record:
  enabled: true
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      mode: motion
      objects:
        person: 14
    objects:
      - person
ffmpeg:
  global_args: -hide_banner -loglevel info
  input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  hwaccel_args: -c:v h264_v4l2m2m
cameras:
  Front-door:
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.47.29.113:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif"
          roles:
            - detect
        - path: "rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@10.47.29.113:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"
          roles:
            - record
    motion:
      mask:
        - 311,111,0,134,0,0,640,0,640,480,640,222
        - 0,233,117,121,0,132
    zones:
      driveway:
        coordinates: 376,480,444,155,169,116,0,324,0,480        
        objects:
          - motorcycle
          - car
          - person
```

### Relevant log output

```shell
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-10-17 16:00:34] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-10-17 16:00:34] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-10-17 16:00:34] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-10-17 16:00:34] frigate.app                    INFO    : Output process started: 217
frigate  | [2022-10-17 16:00:34] detector.coral                 INFO    : Starting detection process: 216
frigate  | [2022-10-17 16:00:34] ws4py                          INFO    : Using epoll
frigate  | [2022-10-17 16:00:34] frigate.app                    INFO    : Camera processor started for Front-door: 224
frigate  | [2022-10-17 16:00:35] frigate.video                  ERROR   : Front-door: Unable to read frames from ffmpeg process.
frigate  | [2022-10-17 16:00:34] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-10-17 16:00:34] frigate.app                    INFO    : Capture process started for Front-door: 228
frigate  | [2022-10-17 16:00:35] frigate.video                  ERROR   : Front-door: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-10-17 16:00:37] frigate.edgetpu                INFO    : TPU found
frigate  | [2022-10-17 16:00:34] ws4py                          INFO    : Using epoll
frigate  | [2022-10-17 16:00:54] watchdog.Front-door            ERROR   : Ffmpeg process crashed unexpectedly for Front-door.
frigate  | [2022-10-17 16:00:54] watchdog.Front-door            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   : Input #0, rtsp, from 'rtsp://name:pass@10.47.29.113:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif':
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :   Metadata:
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :     title           : Media Server
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :   Duration: N/A, start: 1666018834.848375, bitrate: N/A
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x480, 90k tbr, 90k tbn
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :   Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :   Stream #0:2: Data: none
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   : [h264_v4l2m2m @ 0x55ad594c70] Could not find a valid device
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   : [h264_v4l2m2m @ 0x55ad594c70] can't configure decoder
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   : Stream mapping:
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   :   Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> rawvideo (native))
frigate  | [2022-10-17 16:00:54] ffmpeg.Front-door.detect       ERROR   : Error while opening decoder for input stream #0:0 : Invalid argument
frigate  | [2022-10-17 16:00:55] frigate.video                  ERROR   : Front-door: Unable to read frames from ffmpeg process.
frigate  | [2022-10-17 16:00:55] frigate.video                  ERROR   : Front-door: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5596a5a030] method OPTIONS failed: 401 Unauthorized
rtsp://name:pass@10.47.29.113:554/cam/realmonitor?channel=1: Server returned 401 Unauthorized (authorization failed)
```

### Frigate stats

```json
{"Front-door":{"camera_fps":0.0,"capture_pid":222,"detection_fps":0.0,"pid":220,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":216}},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":66.8,"mount_type":"tmpfs","total":67.1,"used":0.3},"/media/frigate/clips":{"free":2891874.0,"mount_type":"nfs","total":3829392.9,"used":937518.8},"/media/frigate/recordings":{"free":2891874.0,"mount_type":"nfs","total":3829392.9,"used":937518.8},"/tmp/cache":{"free":27657.6,"mount_type":"overlay","total":31257.7,"used":2309.5}},"temperatures":{},"uptime":76,"version":"0.11.1-2eada21"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HDW2431T-AS-S2

### Any other information that may be helpful

Using VLC and the exact url logged in the output the camera works perfectly fine.
