### ISSUE TITLE
Support for enabling/disabling a camera in config

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#4109]
Occasionally I need to temporarily disable a camera and it would be convenient to so in the yaml file without have to remove all of its configuration. I propose adding an optional top level `enabled` field for every camera like this:

```yaml
cameras:
  my_camera: 
    enabled: False # <------ True by default
    ...
```
