### ISSUE TITLE
Docs for running out of storage

### ISSUE THREAD

**Issue by SeaDude** [blakeblackshear/frigate#4119]
**Describe what you are trying to accomplish and why in non technical terms**
I have retention set for 7 days on each camera in my config file. But my harddrive keeps running out of memory. Deleting contents of the `recordings` directory doesn't work. 

**Describe the solution you'd like**
Some kind of doc entry on how to handle this. I can craft the doc, just need to know what procedures are to clean up `recordings` to free up storage. Some kind of `chron` job?

**Describe alternatives you've considered**
Manually deleting contents of the `recordings` directory doesn't work.

**Additional context**
This system is air-gapped so its a bit of a pain to get logs.

**Comment by SeaDude** [comment]
Ok. So I could update to the latest Frigate to address the problem?

**Comment by NickM-27** [comment]
That will be in 0.12 which is unreleased

**Comment by SeaDude** [comment]
> That will be in 0.12 which is unreleased

Hi @NickM-27 ,

Version .12 is not released yet. Is there something I can look at to determine why the capacity of my hdd keeps filling up? Frigate is the only program I have installed on this server. Every 7-9 days I have to delete `recordings` and `clips` otherwise I have to boot into safe mode and delete these directories because the GUI won't load. 

I'm suspicious of the `tmp/cache` setting in `docker-compose.yml`: 

```
volumes:
    - /etc/localtime:/etc.localtime:ro
    - /home/user9/Documents/frigate/frigate.yml:/config/config.yml
    - /home/user9/Documents/frigate:/media/frigate
    - type: tmpfs
       target: /tmp/cache
       tmpfs:
         1000000000
```
