### ISSUE TITLE
The camera.yourcamname.object isn't working

### ISSUE THREAD

**Issue by danbutter** [blakeblackshear/frigate#413]
**Describe the bug**
Camera entity made by home assistant integration camera.cameraname.object isn't working.

**Version of frigate**
Issue started with 0.8.0 beta 1 and still happening in 0.8.0 beta 2
Running addons for frigate and Mqtt.
Also running home assistant integration.

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  cpu:
    type: cpu
    num_threads: 3
mqtt:
  host: 192.168.1.230
  topic_prefix: frigate
  client_id: frigate
ffmpeg: {}
cameras:
  frigate_frontyard:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://xxx:xxx@192.168.1.181:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
            - clips
    height: 720
    width: 1280
    fps: 1
    save_clips:
      enabled: true
      pre_capture: 5
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - car
  frigate_driveway:
    ffmpeg:
      inputs:
        - path: >-
            rtsp://xxx:xxx@192.168.1.179:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
            - clips
    height: 720
    width: 1280
    fps: 1
    save_clips:
      enabled: true
      pre_capture: 5
    objects:
      track:
        - person
        - car
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
objects:
  track:
    - person
    - car

```

**Logs**
```
Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/stats -
4:35:32 PM – Frigate (ERROR) - message first occurred at 4:35:17 PM and shows up 2 times
Error fetching information from http://ccab4aaf-frigate-beta:5000/stats - 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate-beta:5000/stats')
4:35:02 PM – Frigate (ERROR) - message first occurred at 4:34:52 PM and shows up 2 times
Error fetching frigate data:
4:34:52 PM – Frigate (ERROR)


```

**Frigate debug stats**
```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**FFprobe from your camera**

Run the following command and paste output below
No idea where to run this.  Using formally known as hassio.  I tried on the host PC and got this:
```
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[rtsp @ 0x55dcfd5cd080] method DESCRIBE failed: 404 Not Found
rtsp://xxx:xxx@192.168.1.181:554/cam/realmonitor?channel=1: Server returned 404 Not Found

```

**Screenshots**

**Computer Hardware**
 - OS: Ubuntu 18
 - Virtualization: na
 - Coral Version: na
 - Network Setup:  Wired

**Camera Info:**
 - Manufacturer:  Dahua
 - Model:  IPC-HDW5231R-ZE and SD1A203T-GN
 - Resolution: e.g. 720p
 - FPS:  5

**Additional context**
I have cams named frigate_frontyard (the SD1A203T-GN) and frigate_driveway (IPC-HDW5231R-ZE).
So the entities I have generated by the frigate integration are camera.frigate_frontyard_person and camera.frigate_frontyard_car and camera.frigate_driveway_person and camera.frigate_driveway_car.
They all worked the day I installed all of this except frontyard_car, but I don't think any cars were there that day.
Never got any other updates to these even though the clip recording works and I can view them via media browser.
