### ISSUE TITLE
[Support]: Where the clips are saved?

### ISSUE THREAD

**Issue by Pinez83** [blakeblackshear/frigate#4140]
### Describe the problem you are having

hello everyone, I use frigate on lxc, and save the snapshots on the CIFS folder of the NAS. However, I discovered that inside the "Clips" folder there are no "videos", only Snapshot images. Where are the clips saved? I would not like to weigh too much on the hard disk of my mini PC. Thank you

### Version

latest

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xx
  user: xxx
  password: xxx
  topic_prefix: frigate
  client_id: frigate

cameras:
  Ingresso:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.xxx/live2.sdp
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.xxx/live1.sdp
          roles:
            - record
    rtmp:
      enabled: false
    detect:
      width: 480
      height: 272
      fps: 7
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
  Sala:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxxx@192.168.1.xxx/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.xxx/HighResolutionVideo
          roles:
            - record

        - path: rtsp://xxx:xxx@192.168.1.xxx/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.xxx/HighResolutionVideo
          roles:
            - record
    rtmp:
      enabled: false
    detect:
      width: 352
      height: 240
      fps: 15
    objects:
      track:
        - person
        - dog
        - cat

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
birdseye:
  enabled: True
  mode: continuous
detectors:
  cpu1:
    type: cpu
    num_threads: 2
timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
record:
  enabled: True
  events:
    retain:
      default: 10
```

### Relevant log output

```shell
no
```

### FFprobe output from your camera

```shell
no
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision
