### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by dcreager** [blakeblackshear/frigate#4144]
### Describe the problem you are having

Is there a way to configure which addresses the Frigate web UI and RTMP feeds listen on?

As a workaround, I was able to edit the `/usr/local/nginx/conf/nginx.conf` file inside the container, updating each `listen` line from

```
listen 5000;
```

to

```
listen [address]:5000;
```

My worry is that these updates will be overwritten the next time I download a newer snapshot of the Frigate container image.

Is there a preferred way to achieve this result?  (I am using host networking when running the Docker container, and do not want to set up a bridge network for this.)

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 127.0.0.1
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

birdseye:
  enabled: True
  mode: continuous

#logger:
#  default: debug

rtmp:
  enabled: False

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: "rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@{REDACTED}/cam/realmonitor?channel=1&subtype=0"
          roles:
            - detect
            - record
            - rtmp
      hwaccel_args: -c:v h264_qsv
  garage:
    ffmpeg:
      inputs:
        - path: "rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@{REDACTED}/cam/realmonitor?channel=1&subtype=0"
          roles:
            - detect
            - record
            - rtmp
      hwaccel_args: -c:v h264_qsv
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

Note that I'm using podman instead of docker CLI to run the container, but that wasn't an option for "Install method"
