### ISSUE TITLE
[Support]: Crashing on Migration from 0.10.1 to 0.11 or 0.11.1

### ISSUE THREAD

**Issue by joeShuff** [blakeblackshear/frigate#4148]
### Describe the problem you are having

I tried to migrate from 0.10.1 up to 0.11.1 (and after this error I also tried 0.11 but same issue) and the container isn't starting and keeps stopping/restarting itself (probably docker autorestarting) and failing on the same database migration.

Fortunately I made a backup of everything and have just reverted to 0.10.1 for the time being.

### Version

0.10.1-83481af

### Frigate config file

```yaml
logger:
  default: debug
  logs:
    peewee: info
mqtt:
  host: <ip>
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: <user>
  password: <pass>
  stats_interval: 60
cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: http://<ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<pass>
          roles:
            - rtmp
            - record
        - path: http://<ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<user>&password=<pass>
          roles:
            - detect
      output_args:    
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    detect:
      width: 896
      height: 672
      fps: 5
      max_disappeared: 25
    record:
      enabled: true
      retain:
        days: 90
        mode: motion
      events:
        pre_capture: 3
        post_capture: 3
        objects:
          - person
          - cat
        retain:
          default: 365
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 365
    objects:
      track:
        - person
        - cat   
    motion:
      mask:
        - 896,0,896,57,500,53,504,0
  front_bedroom:
    ffmpeg:
      inputs:
        - path: http://<ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<pass>
          roles:
            - rtmp
            - record
        - path: http://<ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<user>&password=<pass>
          roles:
            - detect
      output_args:    
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    detect:
      width: 896
      height: 672
      fps: 5
      max_disappeared: 25
    record:
      enabled: true
      retain:
        days: 90
        mode: motion
      events:
        pre_capture: 3
        post_capture: 3
        objects:
          - person
          - cat
        retain:
          default: 365
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 365
    objects:
      track:
        - person
        - cat   
    motion:
      mask:
        - 896,0,896,57,500,53,504,0
  back_bedroom:
    ffmpeg:
      inputs:
        - path: http://<ip>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<user>&password=<pass>
          roles:
            - rtmp
            - record
        - path: http://<ip>/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=<user>&password=<pass>
          roles:
            - detect
      output_args:    
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    detect:
      width: 896
      height: 672
      fps: 5
      max_disappeared: 25
    record:
      enabled: true
      retain:
        days: 90
        mode: motion
      events:
        pre_capture: 3
        post_capture: 3
        objects:
          - person
          - cat
        retain:
          default: 365
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 365
    objects:
      filters:
        person:
          mask:
            - 618,399,687,399,729,402,801,420,825,448,896,492,896,562,896,672,840,672,741,672,683,600,650,540,615,497,543,438
      track:
        - person
        - cat   
    motion:
      mask:
        - 896,0,896,57,500,53,504,0
  feeder:
    ffmpeg:
      inputs:
        - path: http://<ip>:8081
          roles:
            - record  
            - detect
      output_args:    
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -r
        - "3" # <---- adjust depending on your desired frame rate from the mjpeg image
        - -use_wallclock_as_timestamps
        - "1"
    detect:
      enabled: false
      width: 640
      height: 480
      fps: 5
      max_disappeared: 25
    record:
      enabled: true
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 3
        post_capture: 3
        objects:
          - person
          - cat
        retain:
          default: 7
          mode: active_objects
    rtmp:
      enabled: false
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 365 
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@<ip>:554
          roles:
            - rtmp
            - record
        - path: rtsp://<user>:<pass>@<ip>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 720
      height: 576
      fps: 5      
      max_disappeared: 25
    record:
      enabled: true
      retain:
        days: 365
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        retain:
          default: 365
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 365
    motion:
      threshold: 15
      contour_area: 15
      mask:
        - 119,235,201,203,276,156,354,177,410,174,422,244,466,228,484,162,579,169,678,171,720,165,720,127,720,0,0,0,0,253
        - 550,576,720,576,720,500,720,442,657,429,571,437,490,477,468,529,494,561
        - 438,576,384,542,344,520,263,508,208,523,171,542,120,576
        - 0,576,122,576,122,537,111,474,73,428,0,422
    zones: 
      driveway:
        coordinates: 720,503,720,576,720,576,0,576,77,417,164,358,208,340,342,364,469,372,603,491
    objects:
      filters:
        person:
          mask:
            - 556,454,524,426,462,373,328,368,239,356,167,343,96,331,0,315,0,0,720,0,720,454,684,437
      track:
        - person
        - cat
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<pass>@<ip>:554
          roles:
            - rtmp
            - record
        - path: rtsp://<user>:<pass>@<ip>:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 704
      height: 480
      fps: 5      
      max_disappeared: 25
    record:
      enabled: true
      retain:
        days: 365
        mode: motion
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        retain:
          default: 365
          mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 365
    motion:
      mask: 
        - 704,0,704,42,704,150,661,119,599,83,565,59,513,42,512,0
        - 48,0,138,0,142,86,70,113
    objects:
      filters:
        person:
          mask:
            - 505,0,704,0,704,55,704,90,704,156,623,100,593,70,548,47
      track:
        - person
        - cat
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: true
  mode: continuous
  height: 1080
  width: 1920
```

### Relevant log output

```shell
Starting migrations
[2022-10-23 19:38:40] peewee_migrate                 INFO    : Starting migrations
[2022-10-23 19:38:40] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
Migrate "011_update_indexes"
[2022-10-23 19:38:40] peewee_migrate                 INFO    : Migrate "011_update_indexes"
sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
[2022-10-23 19:38:40] peewee_migrate                 INFO    : sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
sql ('DROP INDEX recordings_start_time_end_time',)
[2022-10-23 19:38:40] peewee_migrate                 INFO    : sql ('DROP INDEX recordings_start_time_end_time',)
no such index: recordings_start_time_end_time
Traceback (most recent call last):
Migration failed: 011_update_indexes
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3177, in execute_sql
sqlite3.OperationalError: no such index: recordings_start_time_end_time
    cursor.execute(sql, params or ())
During handling of the above exception, another exception occurred:
  File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 179, in run_one
  File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 151, in run
    migrator.run()
```

### FFprobe output from your camera

```shell
<N/A>
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Mix of Reolink, Amcrest
