### ISSUE TITLE
Frigate crashes with EDGE TPU. Runs fine with CPU detector

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#4149]
### Describe the problem you are having

I have three identical Dell 3040 machines running Home Assistant with the frigate addon.

Since updating two of them to version 0.11 they fail to detect the Coral TPU and frigate crashes frequently.

The install that's still running 0.10.1 continues to perform well.

Swapping around the TPUs still gives the same result so the TPUs are fine. No other USB devices are connected to any machine.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.105
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ashscott
  password: brillig269
  stats_interval: 60

# ffmpeg:
#   hwaccel_args:
#     - -hwaccel
#     - vaapi
#     - -hwaccel_device
#     - /dev/dri/renderD128
#     - -hwaccel_output_format
#     - yuv420p

database:
  path: /media/frigate/clips/frigate.db

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

detectors:
  coral:
    type: edgetpu
    device: usb
  # coral:
  #   type: edgetpu
  #   device: usb
  # coral2:
  #   type: edgetpu
  #   device: usb:1
# resolution was 640x352 changed to 1920x1080
cameras:
  driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.35:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.35:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record


#### Testing with file ####
      # inputs:
      #   - path: /media/frigate/driveway.mp4
      #     input_args: -re -stream_loop -1 -fflags +genpts
      #     roles:
      #       - detect
      #       - rtmp


    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 20
      # stationary:
      #   interval: 0
      #   threshold: 50
    objects:
      track:
        - car
      filters:
        # person:
        #   threshold: 0.5
        #   min_score: 0.8
        car:
          threshold: 0.6
          min_score: 0.6
          min_area: 800
    motion:
      mask:
        - 704,0,704,88,0,68,0,0
        - 0,576,704,576,704,209,0,174
      threshold: 30  

      # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      contour_area: 28

      # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
      # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
      # Too low and a fast moving person wont be detected as motion.
      # Default is 0.2
      delta_alpha: 0.4

      # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
      # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
      # Low values will cause things like moving shadows to be detected as motion for longer.
      # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
      # Default is 0.2
      frame_alpha: 0.22

      # Optional: Height of the resized motion frame  (default: 50)
      # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
      # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
      # Default is 50
      frame_height: 55

    zones: 
      # left:
      #   coordinates: 0,92,0,136,132,139,120,94
      # # left:
      # #   coordinates: 50,93,50,134,241,142,236,112
      # middle:
      #   coordinates: 258,152,449,165,454,125,254,100
      # right:
      #   coordinates: 704,145,704,206,459,169,456,119zones:
      left:
        coordinates: 0,92,0,136,250,146,252,107
      middle:
        coordinates: 258,152,449,165,454,125,254,100
      right:
        coordinates: 672,143,671,205,459,169,456,119
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - right
          - middle
          - left
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  turning_circle: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.40:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.40:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record


#### Testing with file ####
      # inputs:
      #   - path: /media/frigate/turning_circle.mp4
      #     input_args: -re -stream_loop -1 -fflags +genpts
      #     roles:
      #       - detect
      #       - rtmp

      
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 355,267,423,256,428,215,356,216
          min_area: 1200
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 0,0,0,171,355,196,355,257,438,259,437,220,640,201,640,0
    zones:
      tc_east:
        coordinates: 0,480,187,480,186,269,185,189,0,187
      tc_middle:
        coordinates: 190,480,399,480,399,198,182,190
      tc_west:
        coordinates: 640,480,404,480,405,194,640,197

      # tc_east:
      #   coordinates: 0,480,273,480,278,192,0,187
      # tc_west:
      #   coordinates: 640,480,404,480,405,194,640,197
      # tc_middle:
      #   coordinates: 279,480,399,480,399,198,278,195
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - tc_east
          - tc_west
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100


  car_park:
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.42:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.42:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

### Testing with file ####
      # inputs:
      #   - path: /media/frigate/carpark.mp4
      #     input_args: -re -stream_loop -1 -fflags +genpts
      #     roles:
      #       - detect
      #       - rtmp


    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 20
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.6
          min_score: 0.76
        car:
          threshold: 0.6
          min_score: 0.75
          mask:
            - 280,160,348,209,403,125,408,99,301,90,279,103         
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,39,187,21,326,29,280,89,288,172,447,346,493,139
    zones:
      carpark_middle:
        coordinates: 302,139,279,100,180,94,131,138
      carpark_south:
        coordinates: 640,480,0,480,0,211,110,143,297,144
      top_of_drive:
        coordinates: 254,39,304,49,303,88,191,88
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - carpark_north
          - carpark_south
          - top_of_drive
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  south_terrace: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.52:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.52:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
          mask:
            - 640,101,640,197,130,217,0,255,0,107
            - 640,480,640,340,509,275,350,480,411,480
        dog:
          threshold: 0.5
          min_score: 0.55
    motion:
      mask:
        - 640,0,640,236,315,227,0,207,0,0
    zones:
      rear_lawn:
        coordinates: 640,266,640,480,335,480,195,264,191,235
      terrace:
        coordinates: 345,480,0,480,0,273,126,231,191,228
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - terrace
          - rear_lawn
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  # garage_south_east: # <------ Name the camera
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://admin:brillig269@10.0.1.57:554/cam/realmonitor?channel=1&subtype=1
  #         roles:
  #           - detect
  #       - path: rtsp://admin:brillig269@10.0.1.57:554/cam/realmonitor?channel=1&subtype=0
  #         roles:
  #           - record
  #   rtmp:
  #     enabled: False # <-- RTMP should be disabled if your stream is not H264
  #   detect:
  #     width: 640 # <---- update for your camera's resolution
  #     height: 480 # <---- update for your camera's resolution
  #     fps: 5
  #   objects:
  #     track:
  #       - person
  #       - dog
  #     filters:
  #       person:
  #         threshold: 0.5
  #         min_score: 0.6
  #       dog:
  #         threshold: 0.5
  #         min_score: 0.5
  #   motion:
  #     mask:
  #       - 390,0,640,0,640,137,399,155,93,183,184,352,0,352,0,0  
  #   zones:
  #     rear_lawn:
  #       coordinates: 188,352,640,352,640,151,486,156,124,191        
  #   record:
  #     enabled: True
  #     retain:
  #       days: 2
  #       mode: all
  #     events:
  #       retain:
  #         default: 5
  #         mode: motion
  #       pre_capture: 3
  #       post_capture: 15
  #       required_zones:
  #         - rear_lawn
  #   snapshots:
  #     enabled: true
  #     timestamp: false
  #     bounding_box: false
  #     crop: true
  #     height: 500
  #     retain:
  #       default: 5
  #   mqtt:
  #     timestamp: False
  #     bounding_box: False
  #     crop: True
  #     height: 500
  #     quality: 100

  garage_south: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.22:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.5
          min_score: 0.8
        dog:
          threshold: 0.5
          min_score: 0.6
        cat:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 0,74,610,68,640,183,640,0,0,0
    zones:
      south:
        coordinates: 203,79,258,87,327,78,640,107,640,352,0,352,0,119,126,92

    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
        required_zones:
          - south
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.56:554/12
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.56:554/11
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.5
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
    motion:
      mask:
        - 1920,210,1920,0,793,0,743,0,752,38,802,50,1083,130
      # threshold: 15
    # zones:
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  east_terrace: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.47:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.5
          min_score: 0.7
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
        dog:
          threshold: 0.5
          min_score: 0.6
          mask:
            - 165,344,370,353,640,414,640,480,162,480,0,480,0,453
            - 0,201,0,0,640,0,640,153,348,145,116,201
        cat:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,158,0,157,640,152
      # threshold: 15
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  courtyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.54:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        # - car
        - cat
        - dog
      filters:
        person:
          threshold: 0.8
          min_score: 0.75
        # car:
        #   # threshold: 0.5
        #   min_score: 0.7
        #   mask:
        #     - 250,119,260,196,181,207,179,127
        cat:
          min_score: 0.5
        dog:
          min_score: 0.5
    motion:
      mask:
        - 442,118,561,283,348,263,333,102
        - 704,0,704,42,327,52,326,150,242,187,238,54,0,82,0,0
    zones:
      courtyd:
        coordinates: 468,70,634,256,704,273,704,576,310,576,315,69
      terrace:
        coordinates: 309,47,306,576,0,576,0,480,0,273,0,197,89,99
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100

  greenhouse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:brillig269@10.0.1.55:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:brillig269@10.0.1.55:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - cat
        - dog
        - person
      filters:
        cat:
          threshold: 0.6
          min_score: 0.75
        dog:
          threshold: 0.5
          min_score: 0.7
        person:
          threshold: 0.6
          min_score: 0.75
          mask:
            - 94,314,64,323,67,273,88,269
    motion:
      mask:
        - 0,195,704,198,704,0,0,0,0,0
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant log output

```shell
[2022-10-24 08:43:33] frigate.edgetpu                INFO    : Attempting to load TPU as usb
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-10-24 08:43:58] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
[2022-10-24 08:44:03] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-10-24 08:44:03] frigate.app                    INFO    : Stopping...
[2022-10-24 08:44:03] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-10-24 08:44:03] frigate.events                 INFO    : Exiting event cleanup...
[2022-10-24 08:44:03] frigate.record                 INFO    : Exiting recording cleanup...
[2022-10-24 08:44:03] frigate.stats                  INFO    : Exiting watchdog...
[2022-10-24 08:44:03] frigate.watchdog               INFO    : Exiting watchdog...
[2022-10-24 08:44:04] frigate.record                 INFO    : Exiting recording maintenance...
[2022-10-24 08:44:04] frigate.object_processing      INFO    : Exiting object processor...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
