### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by ankurtalukdar5** [blakeblackshear/frigate#4150]
### Describe the problem you are having

i have retrained the model following the coral tutorial , now i want to add the new model.tflite in the config.yml file. i have added the path to the model in the config.yml file. but it shows an error ValueError: Could not open '/home/pc/frigate/salad.tflite'

here is the log:
pc@gotisheel:~/frigate$ sudo docker-compose -f frigate.yml up
Creating network "frigate_default" with the default driver
Creating frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate    | Starting migrations
frigate    | [2022-10-24 14:11:59] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2022-10-24 14:11:59] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2022-10-24 14:11:59] detector.cpu1                  INFO    : Starting detection process: 232
frigate    | Process detector:cpu1:
frigate    | [2022-10-24 14:11:59] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate    |     object_detector = LocalObjectDetector(
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 59, in __init__
frigate    |     self.interpreter = tflite.Interpreter(
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
frigate    |     _interpreter_wrapper.CreateWrapperFromFile(
frigate    | ValueError: Could not open '/home/pc/frigate/salad.tflite'.
frigate    | [2022-10-24 14:11:59] detector.cpu2                  INFO    : Starting detection process: 233
frigate    | Process detector:cpu2:
frigate    | [2022-10-24 14:11:59] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2022-10-24 14:11:59] ws4py                          INFO    : Using epoll
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate    |     object_detector = LocalObjectDetector(
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 59, in __init__
frigate    |     self.interpreter = tflite.Interpreter(
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
frigate    |     _interpreter_wrapper.CreateWrapperFromFile(
frigate    | ValueError: Could not open '/home/pc/frigate/salad.tflite'.
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Output process started: 235
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Camera processor started for back: 240
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Capture process started for back: 242
frigate    | [2022-10-24 14:11:59] ws4py                          INFO    : Using epoll
frigate    | [2022-10-24 14:12:19] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | [2022-10-24 14:12:19] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
pc@gotisheel:~/frigate$ 

### Version

NA

### Frigate config file

```yaml
mqtt:
  host: broker.hivemq.com 
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
model:
  path: /home/pc/frigate/salad.tflite
  #labelmap_path: /home/pc/frigate/salad.txt
  width: 320
  height: 320
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.29.138:554/live/0/main
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: false
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,461,3,0,1919,0,1919,843,1699,492,1344,458,1346,336,973,317,869,375,866,432
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
        chair: 1000
objects:
  track:
    - person
    - chair
    - bottle
    - laptop
    - helmet
  mask: 0,0,1000,0,1000,200,0,200
record:
  enabled: False
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 15
        chair: 15
```

### Relevant log output

```shell
pc@gotisheel:~/frigate$ sudo docker-compose -f frigate.yml up
Creating network "frigate_default" with the default driver
Creating frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate    | Starting migrations
frigate    | [2022-10-24 14:11:59] peewee_migrate                 INFO    : Starting migrations
frigate    | There is nothing to migrate
frigate    | [2022-10-24 14:11:59] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2022-10-24 14:11:59] detector.cpu1                  INFO    : Starting detection process: 232
frigate    | Process detector:cpu1:
frigate    | [2022-10-24 14:11:59] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate    |     object_detector = LocalObjectDetector(
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 59, in __init__
frigate    |     self.interpreter = tflite.Interpreter(
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
frigate    |     _interpreter_wrapper.CreateWrapperFromFile(
frigate    | ValueError: Could not open '/home/pc/frigate/salad.tflite'.
frigate    | [2022-10-24 14:11:59] detector.cpu2                  INFO    : Starting detection process: 233
frigate    | Process detector:cpu2:
frigate    | [2022-10-24 14:11:59] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate    | [2022-10-24 14:11:59] ws4py                          INFO    : Using epoll
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate    |     object_detector = LocalObjectDetector(
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 59, in __init__
frigate    |     self.interpreter = tflite.Interpreter(
frigate    |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
frigate    |     _interpreter_wrapper.CreateWrapperFromFile(
frigate    | ValueError: Could not open '/home/pc/frigate/salad.tflite'.
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Output process started: 235
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Camera processor started for back: 240
frigate    | [2022-10-24 14:11:59] frigate.app                    INFO    : Capture process started for back: 242
frigate    | [2022-10-24 14:11:59] ws4py                          INFO    : Using epoll
frigate    | [2022-10-24 14:12:19] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | [2022-10-24 14:12:19] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
pc@gotisheel:~/frigate$
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
