### ISSUE TITLE
Substreams that stretch the source aspect ratio should output clips of the source aspect ratio

### ISSUE THREAD

**Issue by paularmstrong** [blakeblackshear/frigate#416]
**Describe the bug**
I have a couple of cameras that are running 1920x1080 (or larger, 16:9 aspect ratio). Their substreams output 640x480 of the same view, but that's a 4:3 aspect ratio. So when a snapshot is created due to `detect` rule on the substream, the snapshot still ends up stretched because the snapshot is of the substream 640x480.

Example output image:
![best](https://user-images.githubusercontent.com/33297/102725131-3f223c00-42c9-11eb-8df6-b17fa1a0ed46.jpg)

What I would _prefer_ to see is the image converted to the aspect ratio of the main source stream:
![best2](https://user-images.githubusercontent.com/33297/102725162-7395f800-42c9-11eb-87f2-8c66168a692f.jpg)

Because the current configuration wants you to set the `width` and `height` properties on the main part of the camera but not per ffmpeg input, there isn't any way to ensure that this happens reliably.

**Version of frigate**
What version are you using?
0.8.0-beta2

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: core-mosquitto.local.hass.io
  user: mqtt
  password: unhook-kick-flabby
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - qsv
    - '-qsv_device'
    - /dev/dri/renderD128
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://<REDACTED>/videoMain
          roles:
            - record
            - clips
        - path: rtsp://<REDACTED>/videoSub
          roles:
            - rtmp
            - detect
    fps: 5
    height: 480
    width: 640
# other cameras redacted
objects:
  track:
    - person
    - dog
    - cat
    - deer
    - bicycle
```

**Logs**
n/a

**Frigate debug stats**
```
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.17,"pid":51}},"front":{"camera_fps":5.0,"capture_pid":62,"detection_fps":0.0,"pid":56,"process_fps":5.0,"skipped_fps":0.0},"kitchen":{"camera_fps":5.0,"capture_pid":65,"detection_fps":0.0,"pid":58,"process_fps":5.0,"skipped_fps":0.0},"living":{"camera_fps":5.0,"capture_pid":70,"detection_fps":0.0,"pid":60,"process_fps":5.0,"skipped_fps":0.0},"turret":{"camera_fps":5.1,"capture_pid":61,"detection_fps":0.0,"pid":54,"process_fps":5.1,"skipped_fps":0.0}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
$ ffprobe rtsp://<REDACTED>/videoMain
Input #0, rtsp, from 'rtsp://<REDACTED>/videoMain':
  Metadata:
    title           : IP Camera Video
    comment         : videoMain
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuvj420p(pc, progressive), 2304x1536, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s

# -------

$ ffprobe rtsp://<REDACTED>/videoSub
Input #0, rtsp, from 'rtsp://<REDACTED>/videoSub':
  Metadata:
    title           : IP Camera Video
    comment         : videoSub
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuvj420p(pc, progressive), 640x480, 20.17 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

**Screenshots**
See bug

**Computer Hardware**
 - OS: Home Assistant
 - Virtualization: HA Addon (docker)
 - Coral Version: USB
 - Network Setup: WiFi camera

**Camera Info:**
 - Manufacturer: Foscam, Amcrest
 - Model: Foscam VZ4, Amcrest IP3M-943W
 - Resolution: 640x480 for substream, 2k 3MP for main stream
 - FPS: 5

**Additional context**

**Comment by paularmstrong** [comment]
Something of note, viewing the substream in VLC, the aspect ratio looks like it gets constrained to the 16:9 correctly.

**Comment by scottlamb** [comment]
+1. For reference, these streams are called [anamorphic](https://en.wikipedia.org/wiki/Anamorphic_widescreen). All of my cameras are 16:9 and have anamorphic 704x480 sub streams. My Dahua ones declare themselves as such properly in the H.264 VUI parameters. (I don't remember off the top of my head if there's a way to get ffprobe to tell you that.) My older Hikvision ones don't, and so look wrong when I view them in VLC and the like (directly, so not due to any problem with frigate). So some autodetection + knob for manual override might be best.

**Comment by blakeblackshear** [comment]
I have Dahua cameras, so I should be able to figure this out. Worst case scenario, I'm sure you can tweak the ffmpeg parameters and correct it upstream of frigate.

**Comment by paularmstrong** [comment]
Thanks, Blake. Taking a look at ffmpeg args, but I'm completely new at it and stumbling, trying to add the following:

```yaml
cameras:
  turret:
    ffmpeg:
      inputs:
        - path: 'rtsp://REDACTED/videoMain'
          roles:
            - record
            - clips
        - path: 'rtsp://REDACTED/videoSub'
          roles:
            - rtmp
            - detect
          input_args:
            - '-vf'
            - 'scale=854:480'
    fps: 5
    save_clips:
      enabled: false
    objects:
      track: []
    height: 480
    width: 854
```

Based on a bunch of searching around, it seems like `-vf scale=854:480` should scale the input as desired, but it's causing ffmpeg to crash. Would love suggestions if anyone is familiar:

```
frigate.video                  INFO    : turret: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
```

**Comment by blakeblackshear** [comment]
Try setting the log level to info for that ffmpeg process in the global_args so you can see why the ffmpeg process is exiting.

**Comment by paularmstrong** [comment]
Looks like an issue on where the `input_args` are applied. I don't think there's control over that, correct?

```
ffmpeg.turret.detect           ERROR   : Option vf (set video filters) cannot be applied to input url rtsp://REDACTED/videoSub -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
```

**Comment by blakeblackshear** [comment]
Setting output args like that replaces the default args, it doesn't add to them. You need to add the new args to the defaults.

**Comment by blakeblackshear** [comment]
Try this to see if it fixes rtmp first. Also, do you intentionally have an empty list for objects > track? That tells frigate not to track anything.

```yaml
cameras:
  turret:
    ffmpeg:
      inputs:
        - path: 'rtsp://REDACTED/videoMain'
          roles:
            - record
            - clips
        - path: 'rtsp://REDACTED/videoSub'
          roles:
            - rtmp
            - detect
      output_args:
        rtmp: -aspect 854:480 -c copy -f flv
    fps: 5
    save_clips:
      enabled: false
    objects:
      track: []
    height: 480
    width: 640
```

**Comment by paularmstrong** [comment]
> Also, do you intentionally have an empty list for objects > track? That tells frigate not to track anything.

For the moment, yes :). This is a new camera and it hasn't been mounted anywhere, but it's sitting next to my desk

(minor note: I realized the main feed is 16:10, not 16:9, so I'm aiming for 720x480)

With the following config, note that I assume `width` also must be changed otherwise ffmpeg will crash:

```yaml
cameras:
  turret:
    ffmpeg:
      inputs:
        - path: 'rtsp://REDACTED/videoMain'
          roles:
            - record
            - clips
        - path: 'REDACTED/videoSub'
          roles:
            - rtmp
            - detect
      output_args:
        rtmp: '-aspect 720:480 -c copy -f flv'
        detect: '-aspect 720:480 -c copy -f flv'
    fps: 5
    save_clips:
      enabled: false
    objects:
      track: []
    height: 480
    width: 720
```

This is the output video from frigate:
<img width="570" alt="Screen Shot 2020-12-21 at 6 28 48 AM" src="https://user-images.githubusercontent.com/33297/102787655-45122e80-4356-11eb-9372-4f87dcb612c1.png">

**Comment by blakeblackshear** [comment]
Your detect output_args are all wrong, so that's what I would expect. Let's try and get rtmp working first. Try this config exactly as is and check the aspect ratio of the rtmp feed.
```yaml
cameras:
  turret:
    ffmpeg:
      inputs:
        - path: 'rtsp://REDACTED/videoMain'
          roles:
            - record
            - clips
        - path: 'rtsp://REDACTED/videoSub'
          roles:
            - rtmp
            - detect
      output_args:
        rtmp: -aspect 720:480 -c copy -f flv
    fps: 5
    save_clips:
      enabled: false
    objects:
      track: []
    height: 480
    width: 640
```

**Comment by paularmstrong** [comment]
With the above and `width: 640`, I get ffmpeg crashing. Setting `width: 720` there is less noise, more this:
<img width="581" alt="Screen Shot 2020-12-21 at 6 38 42 AM" src="https://user-images.githubusercontent.com/33297/102788262-34ae8380-4357-11eb-9402-a80ada44772e.png">

**Comment by blakeblackshear** [comment]
Is that screenshot from frigate's mjpeg endpoint or rtmp? Are you sure you removed the output_args you added in the config for `detect`? Your ffprobe output above indicates that the resolution for the substream is 640x480.

**Comment by paularmstrong** [comment]
> Is that screenshot from frigate's mjpeg endpoint or rtmp? 
mjpeg – using the http path to the camera

> Are you sure you removed the output_args you added in the config for detect?
Yes

> Your ffprobe output above indicates that the resolution for the substream is 640x480.
Apparently I didn't wait long enough and the camera eventually comes up with using 640. The problem from the original issue still exists, though. The width and height of the visible image and stream are 640x480, but not the desired 720x480

**Comment by blakeblackshear** [comment]
> Let's try and get rtmp working first

I would expect the original issue to still be there for the mjpeg stream. Can you check the rtmp stream to see if the aspect ratio is correct now?

**Comment by paularmstrong** [comment]
I can't get the RTMP stream to load in VLC.

Opening up the camera in Home Assistant (is this the RTMP as well?) is still 640x480

**Comment by blakeblackshear** [comment]
For RTMP, I would expect the resolution to show 640x480. We are trying to get the RTMP endpoint to behave the same way it does when you connect directly to the camera with VLC. I am sure it shows 640x480 there too, but there is some extra metadata that tells it to stretch the image. If you have to resize the image, you will have to use CPU to re-encode the video again and we are trying to avoid that.

Let's see if this config fixes the detect stream (mjpeg in frigate).
```yaml
cameras:
  turret:
    ffmpeg:
      inputs:
        - path: 'rtsp://REDACTED/videoMain'
          roles:
            - record
            - clips
        - path: 'rtsp://REDACTED/videoSub'
          roles:
            - rtmp
            - detect
      output_args:
        detect: -vf scale=720:480 -f rawvideo -pix_fmt yuv420p
        rtmp: -aspect 720:480 -c copy -f flv
    fps: 5
    save_clips:
      enabled: false
    objects:
      track: []
    height: 480
    width: 720
```

**Comment by paularmstrong** [comment]
Whoa! That's done it. I feel like ffmpeg is full of magic incantations here.

**Comment by blakeblackshear** [comment]
Lots of magic. I learn something new about ffmpeg every time I look at the docs. There may be some way to make sure the metadata for the aspect ratio is maintained through RTMP, but I don't know what it is. If it were me, I would rather have an odd aspect ratio than use my CPU to re-encode. I will circle back if I ever figure this out since I have Dahua cameras too.

**Comment by paularmstrong** [comment]
Oh wait, so this worked for one but not the other. Sorry I'm jumping the gun here on some of these. 

It seems the Foscam doesn't scale, but the Amcrest does. The differences between the two:
| details | Foscam | Amcrest |
| --- | --- | --- |
| main stream resolution | 2304x1536 | 2304x1296 |
| substream from camera in VLC | 🚫 appears 640x480 | ✅ comes in as 640x480, but is automatically given the correct aspect ratio, so it appears correctly |
| in HA `camera.entity` without scaling in Frigate | 🚫 appears 640x480 (expected?) | 🚫 appears 640x480 (expected?) |
| in HA, with scaling in Frigate | 🚫 appears 640x480 | ✅ appears 854x480 |
| in Frigate RTMP | 🚫 appears 640x480 | ✅ appears 854x480 |
| in Frigate MJPEG | ✅ appears 720x480 | ✅ appears 854x480 |

Configs:

Foscam:
```yaml
  turret:
    ffmpeg:
      inputs:
        - path: 'rtsp://<REDACTED>/videoMain'
          roles:
            - record
            - clips
        - path: 'rtsp://<REDACTED>/videoSub'
          roles:
            - rtmp
            - detect
      output_args:
        detect: '-vf scale=720:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 720:480 -c copy -f flv'
    fps: 5
    save_clips:
      enabled: false
    objects:
      track: []
    height: 480
    width: 720
```

Amcrest:
```yaml
  front:
    ffmpeg:
      inputs:
        - path: rtsp://<REDACTED>/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - clips
        - path: rtsp://<REDACTED>/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
            - detect
      output_args:
        detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
        rtmp: '-aspect 854:480 -c copy -f flv'
    fps: 5
    height: 480
    width: 854
// zones, masks, etc
```

**Comment by blakeblackshear** [comment]
There must be some piece of metadata in the header of the video stream that is different. Ffmpeg might be able to add that for the foscam, but I dont know how.

**Comment by paularmstrong** [comment]
Cool, I'm going to keep digging and use this thread for notes, in case someone else stumbles upon similar. Thanks for the help so far, @blakeblackshear 

So the Amcrest, with `ffprobe` returns something interesting:
```
Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 4:3 DAR 16:9], 5 fps, 5 tbr, 90k tbn, 10 tbc
```

Whereas the foscame does not include the SAR/DAR:
```
Stream #0:0: Video: h264 (Constrained Baseline), yuvj420p(pc, progressive), 640x480, 90k tbr, 90k tbn, 180k tbc
```

I've seen a few notes about SAR/DAR in my recent scaling/aspect searches, so I'm going to pull that back up and tinker.

**Comment by paularmstrong** [comment]
In the debug logs for frigate, it looks like ffmpeg is setting the SAR/DAR correctly when using `-aspect 16:10`

```
ffmpeg.turret.detect           ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.turret.detect           ERROR   : Input #0, rtsp, from 'rtsp://<REDACTED>/videoSub':
ffmpeg.turret.detect           ERROR   :   Metadata:
ffmpeg.turret.detect           ERROR   :     title           : IP Camera Video
ffmpeg.turret.detect           ERROR   :     comment         : videoSub
ffmpeg.turret.detect           ERROR   :   Duration: N/A, start: 1608569902.329875, bitrate: N/A
ffmpeg.turret.detect           ERROR   :     Stream #0:0: Video: h264, yuvj420p(pc, progressive), 640x480, 5 tbr, 90k tbn, 180k tbc
ffmpeg.turret.detect           ERROR   :     Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
ffmpeg.turret.detect           ERROR   : Overriding aspect ratio with stream copy may produce invalid files
ffmpeg.turret.detect           ERROR   : Output #0, flv, to 'rtmp://127.0.0.1/live/turret':
ffmpeg.turret.detect           ERROR   :   Metadata:
ffmpeg.turret.detect           ERROR   :     title           : IP Camera Video
ffmpeg.turret.detect           ERROR   :     comment         : videoSub
ffmpeg.turret.detect           ERROR   :     encoder         : Lavf58.45.100
ffmpeg.turret.detect           ERROR   :     Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuvj420p(pc, progressive), 640x480 [SAR 6:5 DAR 8:5], q=2-31, 5 tbr, 1k tbn, 90k tbc
ffmpeg.turret.detect           ERROR   :     Stream #0:1: Audio: pcm_mulaw ([8][0][0][0] / 0x0008), 8000 Hz, mono, s16, 64 kb/s
ffmpeg.turret.detect           ERROR   : Stream mapping:
ffmpeg.turret.detect           ERROR   :   Stream #0:0 -> #0:0 (copy)
ffmpeg.turret.detect           ERROR   :   Stream #0:1 -> #0:1 (copy)
ffmpeg.turret.detect           ERROR   :   Stream #0:0 -> #1:0 (h264 (native) -> rawvideo (native))
```

In particular, this line:
```
ffmpeg.turret.detect           ERROR   :     Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuvj420p(pc, progressive), 640x480 [SAR 6:5 DAR 8:5], q=2-31, 5 tbr, 1k tbn, 90k tbc
```

**Comment by scottlamb** [comment]
Ahh, that ffprobe SAR/DAR comes from the H.264 VUI information I mentioned. I didn't see it in my own ffprobe output because I was wrong when I said all my Dahua cameras do the right thing. Turns out one model does, one model doesn't. Edited my comment above to reflect that.

If you're curious, you can also use [h264bitstream](https://github.com/aizvorski/h264bitstream) to inspect the VUI:

```
$ ffmpeg -i 20200220175230-driveway-sub.mp4 -bsf:v h264_mp4toannexb -c copy -f mpegts 20200220175230-driveway-sub.h264
$ h264_analyze 20200220175230-driveway-sub.h264
...
10.2: sps->vui_parameters_present_flag: 1
10.1: sps->vui.aspect_ratio_info_present_flag: 1
11.8: sps->vui.aspect_ratio_idc: 255
12.8: sps->vui.sar_width: 40
14.8: sps->vui.sar_height: 33
...
```

That 40/33 turns the 704x480 image into a 853x480 one.

In a `.mp4` file, this codec-layer information is supposed to be either respected or overridden by the container-layer `pasp` (PixelAspectRatioBox).

When you're producing a JPEG file, as in frigate's `/latest.jpg`...I'm not really sure if there's an equivalent of that. Is there some EXIF tag for aspect ratio? Or HTML can tell the browser to scale the image, or maybe it's just more straightforward if frigate scales the image itself.

**Comment by paularmstrong** [comment]
It appears to work with the following, though I'm not sure if this means it's fully re-encoding the video, not just copying it. I don't really see any change in CPU usage:

```
rtmp: '-vf scale=720:480,setdar=16:10 -c:a copy -f flv'
```

All looks good in VLC, the frigate live stream and `/latest.jpg` now, but Home Assistant's lovelace UI doesn't seem to be able to open and play the video anymore.

**Comment by blakeblackshear** [comment]
For the mjpeg stream, I think it's better to scale the image to the right resolution with ffmpeg upstream as shown above since you already have to decode it for detection. The skewed image would likely reduce the accuracy of detections slightly. Ffmpeg will probably be more efficient at that resize than frigate anyway.

**Comment by scottlamb** [comment]
Fair enough. When I said "if frigate scales the image itself", I suppose I was thinking of the ffmpeg subprocess as basically part of frigate from the user's perspective.

On the other hand, IMHO it's a bit of a shame to be doing the scaling all the time and doing motion detection on 21% more pixels. Isn't frigate already scaling stuff when preparing the inputs to the object detection model? That seems like the most efficient place to account to handle the aspect ratio correction for object detection, short of retraining a model specifically for anamorphic images.

For MJPEG: I'd guess it has some equivalent of the aspect ratio override. I've never looked at MJPEG though; H.264 is so much more efficient in terms of bandwidth and coming ready from the camera.

**Comment by blakeblackshear** [comment]
I would have to add a bunch of special handling to only correct the aspect ratio when needed for some cameras but not others. The motion detection already downsizes the image, so it's not adding much.

**Comment by lkaino** [comment]
I struggled with the resizing myself.

I'm planning to buy a Dahua B180 panoramic camera, which squeezes the video. I'm testing if it would be possible to resize the video in Frigate using ffmpeg.

I'll leave my config here, maybe it will help someone. This is how I managed to do it when using VAAPI:

```
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.183:8554/unicast
          roles:
            - detect
      output_args:
        detect: '-vf scale_vaapi=w=iw*2:h=ih,hwdownload -f rawvideo -pix_fmt yuv420p'
      hwaccel_args: preset-vaapi
    detect:
      enabled: True
      width: 2560 # 1280
      height: 720
```

**Comment by NickM-27** [comment]
> I'm planning to buy a Dahua B180 panoramic camera

I might suggest using the hikvision panoramic instead which does not have the stretching issue and performs better in low light https://www.youtube.com/watch?v=twnZayxPjzY

**Comment by lkaino** [comment]
> > I'm planning to buy a Dahua B180 panoramic camera
> 
> I might suggest using the hikvision panoramic instead which does not have the stretching issue and performs better in low light https://www.youtube.com/watch?v=twnZayxPjzY

This is getting a bit offtopic, but..

I have watched that video, I don't fully agree with Hook Ups opinions. I don't think the Hikvision looks that much better in low light compared to Dahua. The unstretched image is tempting though.

Do you know what is the corresponding Hikvision model to the NCD 800?

**Comment by NickM-27** [comment]
Obviously don't have the dahua to compare but I have been quite happy with the hikvision in low light https://www.bhphotovideo.com/c/product/1705511-REG/hikvision_colorvu_ds_2cd2387g2p_lsu_sl_8mp_network.html/

**Comment by lkaino** [comment]
> Obviously don't have the dahua to compare but I have been quite happy with the hikvision in low light https://www.bhphotovideo.com/c/product/1705511-REG/hikvision_colorvu_ds_2cd2387g2p_lsu_sl_8mp_network.html/

Thanks! One more thing: how does the detection model perform on the wide aspect ratio? I would imagine it's harder to do the detections as I assume the image is resized before feeding it to the model.

**Comment by NickM-27** [comment]
> > Obviously don't have the dahua to compare but I have been quite happy with the hikvision in low light https://www.bhphotovideo.com/c/product/1705511-REG/hikvision_colorvu_ds_2cd2387g2p_lsu_sl_8mp_network.html/
> 
> Thanks! One more thing: how does the detection model perform on the wide aspect ratio? I would imagine it's harder to do the detections as I assume the image is resized before feeding it to the model.

it works exactly the same as any other camera. Frigate does not send the entire image to detection, it sends motion regions.

**Comment by mihalski** [comment]
Sorry to resurrect an old thread but I have tried to do this for my Dahua cameras and it doesn't seem to have any affect. Do I have the output_args in the correct place? Here's a partial section of my config to illustrate where I have placed it:

```
cameras:
  Driveway:
    ffmpeg:
      inputs:
      - path: 
          rtsp://REDACTED/cam/realmonitor?channel=1&subtype=0
        roles:
        - record
      - path: 
          rtsp://REDACTED/cam/realmonitor?channel=1&subtype=1
        roles:
        - rtmp
      - path: 
          rtsp://REDACTED/cam/realmonitor?channel=1&subtype=2
        roles:
        - detect
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      output_args:
        detect: -vf scale=704:576 -f rawvideo -pix_fmt yuv420p
        rtmp: -aspect 704:576 -c copy -f flv
    detect:
      width: 704
      height: 576
      fps: 5
```

**Comment by NickM-27** [comment]
This would be easier to do with go2rtc not rtmp.

**Comment by mihalski** [comment]
> This would be easier to do with go2rtc not rtmp.

I use the Frigate interface to view the streams. Will it work in that?

**Comment by NickM-27** [comment]
Yes, it that's one of the main features of its integration

**Comment by mihalski** [comment]
So what does that entail?

**Comment by NickM-27** [comment]
I'd start with https://docs.frigate.video/guides/configuring_go2rtc

**Comment by iscofield** [comment]
I'm trying to do this with go2rtc and I've found several old threads that mention fixing this, but it seems none of them work anymore.

Here's a basic go2rtc config:
```
go2rtc:
  streams:
    annabelle_room:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.4.11:554/cam/realmonitor?channel=1&subtype=0&unicast=1&proto=Onvif
      - "ffmpeg:annabelle_room#audio=opus" # <- copy of the stream which transcodes audio to opuss
    annabelle_room_sub:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.4.11:554/cam/realmonitor?channel=1&subtype=1&unicast=1&proto=Onvif
      - "ffmpeg:annabelle_room_sub#audio=opus"
```

Cameras config:
```
cameras:
  anabelle_room:
    enabled: true
    # audio: # to enable audio events
    #   enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        # detect: -vf scale=704:480 -f rawvideo -pix_fmt yuv420p
        # rtmp: -vf scale=1024:576:force_original_aspect_ratio=increase -an -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/annabelle_room
        # - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.4.11:554/cam/realmonitor?channel=1&subtype=0&unicast=1&proto=Onvif
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/annabelle_room_sub
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    detect:
      width: 704
      height: 480
```

Everything works via go2rtc and the video is fine, up until I add the substream, then the aspect ratio is incorrect.  
The resolution of my main stream is: 2560x1440 and the resolution of the substream is 704x480.  If I view the mainstream via RTSP in VLC, it looks fine aspect ratio wise.

I tried following the guidance in this other [github issue](https://github.com/blakeblackshear/frigate/discussions/4223) but this doesn't seem to work for me.

Does anyone have an updated config for the Dahua cameras with varying aspect ratios between the main stream and substream, via go2rtc?
