### ISSUE TITLE
[Config Support]: Excluding events by colors ?

### ISSUE THREAD

**Issue by sgurgul** [blakeblackshear/frigate#4163]
### Describe the problem you are having

Flies :)

They regularly trigger events on some cameras - obviously they like the white LED the camera is using for the scene.

All these events have one in common - flies appears in from of the camera and are extremely bright/white.
The shape of the fly depends, of course, but is frequently classified as "cat" by build in models.

The difference is that the cat would never be that "white" - mainly because it will never appear so close to the camera lens.

So the question is, is there any way to limit/exclude events by the brightness or RGB color of the object ?

### Version

0.11.0-3846A13

### Frigate config file

```yaml
# FRONT
  frigate_front:
    ffmpeg:
      inputs:
        - path: rtsp://aaa:bbb@192.168.1.128
          roles:
            - record
        - path: rtsp://aaa:bbb@192.168.1.128:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False
    detect:
      width: 704
      height: 576
    zones:
      front_entry:
        coordinates: 257,150,355,170,358,87,286,79
    objects:
      track:
        - person
        - bicycle
        - car
        - dog
        - cat
      filters:
        person:
          min_area: 500    
          max_area: 12000  
          min_score: 0.5   
          threshold: 0.6   
    motion:
      mask:
        - 206,66,289,83,353,85,356,59,653,143,677,158,650,309,704,471,704,126,704,0,235,0,0,0,0,198
```

### Relevant log output

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
