### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by joelduerksen** [blakeblackshear/frigate#4177]
### Describe the problem you are having

only one camera can use this specific GPU ffmpeg configuration, if a second camera is setup with the same ffmpeg settings, ONE of the cameras goes black as frigate starts up, and stays black.  It is probably something obvious to others in the config, 

for now I have the second (idenitical model and settings) camera using libx264 (CPU)

### Version

DEBUG 0.11.0-TENSOR-20CF27A

### Frigate config file

```yaml
chimbaug:
    ui:
      order: 15
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -an
        rtmp: -c:v h264_nvenc -an -f flv
      inputs:
        - path: http://admin:redacted@10.0.1.12/video/mjpg.cgi
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
```
```


### Relevant log output

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

ubuntu 20.04
