### ISSUE TITLE
[Config Support]: after docker update v20.10.21 build baeda1f frigate stopt working and making system unavailable from network  

### ISSUE THREAD

**Issue by pbvdven** [blakeblackshear/frigate#4189]
### Describe the problem you are having

i ran apt update today and everything became unavailable docker kept rebooting. problem frigate. took me a while to discover but i start reinstalling and when i installed frigate everything instantly crashed again. this time i force removed the container from the host itself because all networking was unavailable. i don't know why it's happening because when i run the frigate container on the host it keeps kicking me out the system every 1min or so and nothing is working then i log in quickly force remove and all is fine? I'm figuring out how to downgrade docker to see if it works again because before the update no problems.

### Version

0.11.1

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    pid: host
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/hassio/homeassistant/frigate/config.yml:/config/config.yml:ro
      - /usr/share/hassio/share/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5001:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD:
```

### Relevant log output

```shell
no log
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
