### ISSUE TITLE
crop_to_region causing detection to stop

### ISSUE THREAD

**Issue by rtsam** [blakeblackshear/frigate#419]
Upgraded to v0.8.0-beta2....

Using "crop_to_region: False/True" seems to cause frigate to stop detecting entirely. As soon as I remove the line detection starts working again. 

Here is the config that is failing....

```
  driveway_right:
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        - path: <rtsp removed>
          roles:
            - detect
    width: 1280
    height: 720
    fps: 5
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False
    mask: driveway_right_1080.bmp
    snapshots:
      show_timestamp: False
      crop_to_region: False
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.7

```
