### ISSUE TITLE
[Support]: Increasing Memory Usage

### ISSUE THREAD

**Issue by kingcode94** [blakeblackshear/frigate#4191]
### Describe the problem you are having

Hi,

My RAM usage just seems to climb when the docker is running. 

I have attached my config version below. If I restart the docker the memory will reduce  to around 700mb but then slowly climb again over a few days to use all of the available memory.  

My system is:
i7 9700t - CPU is approx 20% cpu with 6 cameras as per the config below.
16gb ram
Unraid Version: 6.10.3 

Anyone got any ideas? 

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 172.17.0.3
  user: XXXX
  password: XXXX
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  DriveRight:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.1:554/Streaming/Channels/102/
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - dog
        - cat

  FrontPorch:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.2:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - dog
        - cat

  DriveLeft:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.3:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - dog
        - cat

  BackGarden:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.4:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - dog
        - cat

  HouseLeft:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.5:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
         min_score: 0.7

  HouseRight:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.6:554/Streaming/Channels/101/
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 360
    snapshots:
      enabled: True
    record:
      enabled: True
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - dog
        - cat
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision
