### ISSUE TITLE
Person detection not working

### ISSUE THREAD

**Issue by pvillanyi** [blakeblackshear/frigate#4192]
### Describe the problem you are having

Since the last HA update the person detection recognizes all stray cats.

### Version

3.1

### Frigate config file

```yaml
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.0:554/live/ch00_1
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.75
          threshold: 0.76
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 5
        objects:
          person: 15
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 5
```

### Relevant log output

```shell
found nothing
```

### FFprobe output from your camera

```shell
no camera problem
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

etc
