### ISSUE TITLE
[Support]: Frigate loses connection to 1 camera overtime - direct connect from web works

### ISSUE THREAD

**Issue by FS1961** [blakeblackshear/frigate#4193]
### Describe the problem you are having

I have a D-Link camera that works from time to time with Frigate but gives a static or green screen after a few hours. The WiFi is good because I can talk to the camera. All my other cameras stay connected. The camera name is "Garage."

### Version

v3.0.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.XX
  user: XXXXXXXX
  password: XXXXXXXX
  
cameras:
  Dining: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.59:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
  Garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.36:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
  Front-door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.28:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
  Garten-house: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t@192.168.178.46:554/play1.sdp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
  Drive-way: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:spyb0t22!@192.168.178.55:554/h264  # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
  Patio: # <------ Name the camera
    ffmpeg:
```

### Relevant log output

```shell
Error from stream worker: Error demuxing stream: [Errno 1414092869] Immediate exit requested: 'rtmp://ccab4aaf-frigate-fa-beta/live/Garage'
8:59:01 AM – (ERROR) Stream - message first occurred at October 26, 2022 at 3:09:23 PM and shows up 110 times
Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [Name does not resolve]
October 26, 2022 at 11:08:24 AM – (ERROR) Frigate (custom integration) - message first occurred at October 26, 2022 at 11:08:06 AM and shows up 2 times
Config entry 'ccab4aaf-frigate-fa-beta:5000' for frigate integration not ready yet; Retrying in background
October 26, 2022 at 11:08:06 AM – (WARNING) config_entries.py
```

### FFprobe output from your camera

```shell
ffprobe started on 2022-10-27 at 09:14:02
Report written to "ffprobe-20221027-091402.log"
Log level: 48
Command line:
/Users/frankspatt/Downloads/ffprobe rtsp://frigate:spyb0t@192.168.178.36 -report
ffprobe version N-108816-g874a6f2090-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 51.100 / 59. 51.100
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[tcp @ 0x7fa5e3a04080] No default whitelist set
[tcp @ 0x7fa5e3a04080] Original list of addresses:
[tcp @ 0x7fa5e3a04080] Address 192.168.178.36 port 554
[tcp @ 0x7fa5e3a04080] Interleaved list of addresses:
[tcp @ 0x7fa5e3a04080] Address 192.168.178.36 port 554
[tcp @ 0x7fa5e3a04080] Starting connection attempt to 192.168.178.36 port 554
[tcp @ 0x7fa5e3a04080] Successfully connected to 192.168.178.36 port 554
```

### Frigate stats

```json
Not sure what this is or how to get it.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

DCS-2630L

### Any other information that may be helpful

The other cameras are DCS-936L,
