### ISSUE TITLE
[Support]: Can't start Frigate

### ISSUE THREAD

**Issue by ztardik** [blakeblackshear/frigate#4194]
### Describe the problem you are having

I have no Idea why, it just wont start.

Home assistant on HP T640 Thin Client, AMD R1505G,  4GB RAM
Everything installed fresh, only one camera to start with. Known good setup copied from working system.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
    host: localhost
    port: 1883
    topic_prefix: frigate
    client_id: frigate
    user: admin
    password: *****
    stats_interval: 60

detectors:
    cpu1:
        type: cpu
    
cameras:
  Ulaz:
    ffmpeg:
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://frigate:*****@10.11.12.119:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://frigate:*****@10.11.12.119:554//h264Preview_01_main
          roles:
            - record
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60
    detect:
      width: 640
      height: 480
      fps: 10
      enabled: True
      max_disappeared: 25
    record:
        enabled: True
        events:
            retain:
                default: 10
                mode: active_objects

    rtmp:
        enabled: false
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-10-28 11:49:36] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2022-10-28 11:49:36] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-10-28 11:49:36] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-10-28 11:49:36] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 99] Cannot assign requested address
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
I have no Idea how to provide this.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolinkl RLC-520
