### ISSUE TITLE
[Support]: Frigate "snapshots gallery" no longer showing images although clickable.

### ISSUE THREAD

**Issue by donster22** [blakeblackshear/frigate#4198]
### Describe the problem you are having

Frigate snapshots have disappeared from the frigate dashboard "snapshots gallery" card after updating.
Snapshots in the "most recent snapshots" card still working.

The placeholders are there for the thumbnails and they are clickable through to the actual file but the thumbnail image no longer shows in the "snapshots gallery" **- as per the screenshot below.**

Screenshot here:
https://imgur.com/a/MN9cnEb
[edit: also no idea what those funky ovals are in the "most recent snapshots" image]

All was working fine and has been for a long time. The only thing that changed in the last 24 hours is an update as below but I read the breaking changes and don't remember seeing Frigate mentioned.

Home Assistant 2022.9.6
Supervisor 2022.10.0
Operating System 9.0
Frontend 20220907.2 - latest

I can't work out why the snapshots are not visible in the "snapshots gallery" mode but are visible in "most recent snapshots" mode.

Any ideas?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.12
  user: homeassistant
  password: abc

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://...
          roles:
          - record
          - rtmp
        - path: rtsp://...
          roles:
          - detect
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp:
      enabled: true

    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask:
            - 492,1920,1462,878,1219,847,140,1851

    detect:
      enabled: true
      width: 2560
      height: 1920

    motion:
      mask:
        - 1402,232,2451,269,2449,138,2445,0,0,0,599,279

    record:
      enabled: true

    snapshots:
      enabled: true

    zones:
      drive_14:
        coordinates: 1556,235,2151,286,1443,981,443,1920,0,1920,0,413,0,81,543,70,610,316
      drive_16:
        coordinates: 484,1920,2291,1920,2490,932,2507,335,2125,288
      night:
        coordinates: 2505,313,2560,1920,1232,1920,217,1920,0,1920,0,731,0,0,168,0,512,0,588,292,1812,264

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink
