### ISSUE TITLE
[Config Support]: Constant alerts from one camera - clips not coming in for that camera

### ISSUE THREAD

**Issue by cmgerdes** [blakeblackshear/frigate#4205]
### Describe the problem you are having

I'm getting a notification on ios about every minute or so from one of my six cameras.  I use a single automation to drive the notifications for all cameras, and there's just triggers for each camera on the automation.  For some reason this one camera ("driveway") is just sending constant notifications.  The clips for the notifications for this camera return a 500 unless it's a legitimate notification (that is, if you actually trigger a legit notification then the clip shows up). 

This issue originally seemed to be one of masking - specifically I was struggling to get a mask to work in preventing frigate from picking up a truck canopy that was next to my house as a car.  Its confidence was fairly low so it was dropping in and out of threshold and I thought that was generating notifications.

however, with the help of blackbear I got the masking to work so the bounding box is no longer showing up for the truck canopy...however the notifications are still coming in about every minute.  I did try restarting HA in case there was some sort of backlog of notifications.

Note on the log output: I believe this is the 500 message and is the result of the clip not existing, but I went ahead and provided it.

Important note: I tried commenting out the trigger for the driveway camera (automation provided in last section) and I continued to receive the notifications!  one concern I have is the possibility that with the flood of notifications I had for the last several days trying to fix this, it could be there's a backlog of notifications somewhere slowly playing out.  I already tried restarting HA so I'm not sure where else the issue could exist.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.24
  user: <secret>
  password: <secret>
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>@192.168.2.4:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.4:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    objects:
      filters:
        car:
          mask: 
            - 352,38,352,240,268,240,272,31
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>@192.168.2.9:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.9:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
  top_deck:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>@192.168.2.6:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.6:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
  dog_run_one:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>@192.168.2.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.10:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
  dog_run_two:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>192.168.2.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.12:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>@192.168.2.7:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.7:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,240,128,240,136,26,0,23
  bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://<secret>:<secret>554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<secret>:<secret>@192.168.2.8:554
          roles:
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    detect:
      width: 352
      height: 240
      fps: 2
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    objects:
      track:
        - person
detectors:
  coral:
    type: edgetpu
    device: usb
objects:
  track:
    - person
    - car
    - truck
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - info
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
```

### Relevant log output

```shell
[concat @ 0x5590e29970] No files to concat
/dev/stdin: Invalid data found when processing input
[2022-10-28 14:44:02] frigate.http                   ERROR   : ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[concat @ 0x558b1ca970] No files to concat
/dev/stdin: Invalid data found when processing input
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Below is the automation in question.  Note that it is the "driveway" camera that is getting triggered repeatedly:

```
automation:
  - alias: Camera detected object
    description: ''
    # The trigger is mqtt and will fire whenever an object is detected by YOUR_CAMERA_NAME
    trigger:
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: front_door
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: driveway
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: garage
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: top_deck
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: dog_run_one
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: dog_run_two
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
      - platform: mqtt
        topic: frigate/events
        id: frigate-event
        payload: bedroom
        value_template: '{{ value_json["after"]["camera"] }}'
        variables:
          after_zones: "{{ trigger.payload_json[\"after\"][\"entered_zones\"] }}"
          before_zones: "{{ trigger.payload_json[\"before\"][\"entered_zones\"] }}"
          camera: "{{ trigger.payload_json[\"after\"][\"camera\"] }}"
          id: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
          label: "{{ trigger.payload_json[\"after\"][\"label\"] }}"
    # Conditions must be used to filter out objects / detections that are not of interest
    condition:
      # This condition is used to ensure that I am only notified of objects that are new or only just entered a zone. This is to avoid getting loads of updated notifications for the same dog in my backyard (as an example).
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ trigger.payload_json['type'] == 'new' }}"
          - condition: template
            value_template: "{{ before_zones | length == 0 }}"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: frigate-event
            sequence:
              # Send the initial notification with snapshot and info. 
              - service: script.send_dynamic_notification_to_all_devices
                data:
                  id: "{{ id }}"
                  title: >-
                    {{ label }} was
                    detected on {{ camera |
                    replace("_", " ") | title }}
                  message: >-
                    {{ label }} detected in
                    the {{ after_zones[0] |
                    replace("_", " ") | title }}
                  notifTag: "{{ id }}"
                  notifIcon: mdi:doorbell-video
                  group: >-
                      frigate-notification-{{
                      trigger.payload_json["after"]["camera"] }}
                  importance: default
                  image: "https://<secret>.duckdns.org:8123/api/frigate/notifications/{{id}}/snapshot.jpg"
                  video: "https://<secret>.duckdns.org:8123/api/frigate/notifications/{{id}}/clip.mp4"
                  clickAction: >-
                    https://<secret>.duckdns.org:8123/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
              - repeat:
                  until:
                    - condition: template
                      value_template: '{{ wait.trigger.payload_json["type"] == "end" }}'
                  sequence:
                    - wait_for_trigger:
                        - platform: mqtt
                          topic: frigate/events
                          payload: "{{ trigger.payload_json[\"after\"][\"id\"] }}"
                          value_template: "{{ value_json[\"after\"][\"id\"] }}"
                      continue_on_timeout: false
                      timeout: '00:00:30'
                    - condition: template
                      value_template: '{{ wait.trigger.payload_json[''type''] == ''end'' }}'
                    - service: script.send_dynamic_notification_to_all_devices
        default: []
    mode: parallel
    max: 10
    
script:
  send_dynamic_notification_to_all_devices:
    sequence:
      - delay: "00:00:45"
      - service: notify.mobile_app_chrisiphone
        data:
          message: "{{ message }}"
          title: "{{ title }}"
          data:
            url: "{{ video }}"
            tag: "{{ notifTag }}"
            group: "{{ group }}"
            image: "{{ image }}" 
            video: "{{ video }}"
            clickAction: "{{ video }}"
            attachment:
              url: >-
                {% if (importance == "default" and video != null) -%} {{ video }} {%-
                else -%} {{ image }} {%- endif %}
            push:
              interruption-level: >-
                {% if importance == "max" -%} time-sensitive {%- else -%} passive {%-
                endif %}
```
