### ISSUE TITLE
[Config Support]: Parking cars cause very long events

### ISSUE THREAD

**Issue by Chris18284** [blakeblackshear/frigate#4221]
### Describe the problem you are having

When a car arrives and parks on the side of the road then the event will be recorded until the car leaves. Stationary detection has to detect that the car stopped and not moving, not it?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: <host>
  user: <user>
  password: <password>

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

rtmp:
  enabled: false

birdseye:
  enabled: false

detect:
  width: 2560
  height: 1944
  fps: 5

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 31

record:
  enabled: true
  retain:
    days: 3
  events:
    retain:
      default: 31
    pre_capture: 15
    post_capture: 15

cameras:
  front_garage:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<host>:<port>/Streaming/Channels/301
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - car
        - cat
      mask: 0,0,2560,0,2560,525,2226,441,1224,377,1221,317,476,336,0,396
      filters:
        car:
          mask:
            - 0,0,2560,0,2560,1944,2441,1944,1959,1263,1932,949,1950,769,2192,680,2224,437,1469,396,1449,615,114,742,82,498,0,522
    motion:
      mask:
        - 0,0,2560,0,2560,525,2226,441,1224,377,1221,317,476,336,0,396
    zones:
      our_zone:
        coordinates: 2560,1944,0,1944,0,0,1482,0,1454,591,2161,788,2268,0,2560,0
  rear_garage:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<host>:<port>/Streaming/Channels/401
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - car
        - cat
      mask: 0,365,0,0,2560,0,2560,1049,2560,1944,2032,1944,2176,1631,2276,1343,2062,1252,2121,1103,2027,1065,1953,621,1878,296,1553,216,1546,152,837,512
      filters:
        car:
          mask:
            - 0,1944,0,0,2560,0,2560,1049,2560,1944,2032,1944,2276,1343,2062,1252,2121,1103,2027,1065,1953,621,1882,334,1461,244,831,587,935,1110,2205,1691,2221,1944
    motion:
      mask:
        - 0,365,0,0,2560,0,2560,1049,2560,1944,2032,1944,2176,1631,2276,1343,2062,1252,2121,1103,2027,1065,1953,621,1878,296,1553,216,1546,152,837,512
    zones:
      our_zone:
        coordinates: 2560,0,2560,1944,0,1944,0,0
  entrance_gate:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<host>:<port>/Streaming/Channels/201
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - car
        - cat
      mask: 2560,528,1173,241,802,225,0,496,0,0,2560,0
      filters:
        car:
          mask:
            - 2560,1944,2560,854,1909,661,1883,843,1078,1441,344,1944
    motion:
      mask:
        - 2560,528,1173,241,802,225,0,496,0,0,2560,0
    zones:
      our_zone:
        coordinates: 1184,498,0,846,0,1944,2560,1944,2501,883,1859,678
  terrace:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<host>:<port>/Streaming/Channels/101
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
    motion:
      mask:
        - 0,0,0,361,57,374,59,411,65,442,68,469,89,542,95,590,106,623,120,656,132,685,149,732,165,758,187,777,212,793,235,812,281,839,308,845,342,859,361,862,420,869,449,864,466,840,483,805,487,781,507,758,528,729,547,694,571,685,583,710,604,710,621,716,632,737,629,770,639,789,650,818,664,837,682,845,699,873,709,907,731,953,751,976,778,989,804,1016,799,1041,826,1072,856,1091,888,1110,948,1118,976,1124,1007,1122,1049,1113,1076,1092,1108,1060,1140,1032,1156,1014,1189,978,1197,959,1209,935,1219,911,1233,883,1243,845,1249,821,1265,777,1287,734,1293,709,1293,686,1311,621,1324,594,1333,564,1357,510,1360,483,1363,423,1366,366,1371,331,1360,288,1352,265,1346,236,1343,203,1351,181,1351,155,1351,128,1346,94,1343,57,1336,27,1325,0
    zones:
      our_zone:
        coordinates: 2560,0,2560,1944,0,1944,0,0
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<host>:<port>/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: false
    snapshots:
      enabled: false
  ante-room:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@<host>:<port>/Streaming/Channels/201
          roles:
            - record
    detect:
      enabled: false
    snapshots:
      enabled: false
```

### Relevant log output

```shell
-
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

USB

**Comment by NickM-27** [comment]
This is working as expected, an event will last from when the object is detected until it is no longer detected. You can use the different retention modes to control what recordings are kept for the event: https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

**Comment by Chris18284** [comment]
I edited the config:
```
record:
  enabled: true
  retain:
    days: 4
  events:
    retain:
      default: 31
      mode: active_objects
    pre_capture: 15
    post_capture: 15
```
I still experience 1+ hour events with parking cars. Almost every of them has a moving car which moves next to the parking car and then record the parking car for a very long time. What can cause this? Is there any way to debug that?
