### ISSUE TITLE
[Support]: recordings are stuttering - probably missing frames

### ISSUE THREAD

**Issue by AnduriI** [blakeblackshear/frigate#4242]
### Describe the problem you are having

My camera works fine and I can see a good live stream of it in frigate. But when a event is saved to disc it is kind of stuttering. I can see vertical lines from different heights to the bottom until the next masterframe (I suppose) soon to be repeated with different lines. This makes the recordings nearly useless.
I have frigate running as an addon in home assistant. Due to limited space on the sd card (and to minimize write cycles) I mounted a network share to /usr/share/hassio/media/frigate, which in turn gets mounted to the docker container.
I also tested the write speed, but that is even greater on the share (~50MB/s) than on the sd (~10MB/s). I have no further idea what might cause that, hope someone can help.

Regards,
Anduril

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.38.46
  port: 1883
  client_id: frigate
  user: user
  password: pw

detectors:
  coral:
    type: edgetpu
    device: usb
    
record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 20    
    
cameras:
  Eingang:
    rtmp:
      enabled: true
    ffmpeg:
#      hwaccel_args: -c:v h264_v4l2m2m
      input_args: -stimeout 10
      inputs:
        - path: rtsp://user:pw@192.168.38.39:554/Streaming/Channels/101
          roles:
            - detect
            - clips
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5

    motion:
      mask: 0,0,1920,0,1920,123,1502,89,1474,242,1367,258,1379,173,1398,134,1400,103,1250,77,539,90,490,197,220,182,187,124,0,157
      threshold: 40
      contour_area: 100

    zones:
      Treppe:
        coordinates: 1649,1080,1801,748,1591,616,1167,1080
      Garage:
        coordinates: 779,1080,293,1080,236,959,680,727,994,925
      Einfahrt_aussen:
        coordinates: 1034,178,1294,181,1362,255,872,402,731,229
      Einfahrt_innen:
        coordinates: 0,354,726,225,786,475,38,802

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
  # Optional: crop the snapshot (default: shown below)
      crop: False
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
  # Optional: Camera override for retention settings (default: global values)
      retain:
        default: 3
        objects:
          person: 5

    objects:
      track:
        - person
        - car
#        - cat
        - bicycle
  # Optional: filters to reduce false positives for specific object types
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
#        cat:
#          mask:
#            - 1920,1080,1920,403,909,344,0,585,0,1080

detect:
  max_disappeared: 50
```

### Relevant log output

```shell
what log could be helpful here? Just tell me and I will post it here asap.
```

### FFprobe output from your camera

```shell
libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[udp @ 0x105c270] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0x106c5c0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[rtsp @ 0x1058540] max delay reached. need to consume packet
[rtsp @ 0x1058540] RTP: missed 28 packets
[h264 @ 0x105b8c0] error while decoding MB 60 39, bytestream -19
[h264 @ 0x105b8c0] concealing 3469 DC, 3469 AC, 3469 MV errors in I frame
Input #0, rtsp, from 'rtsp://user:pw@192.168.38.39:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.310000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 25 tbr, 90k tbn, 40 tbc
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision N2404I-DE3
