### ISSUE TITLE
[Support]: Won't start after upgrade ([Errno 74] Bad message: '/media/frigate')

### ISSUE THREAD

**Issue by Gurreman** [blakeblackshear/frigate#4248]
### Describe the problem you are having

The folder mentioned in the subject does no longer exist after upgrade of frigate to the latest GA version. 
I'm not able to manually create the frigate folder within the media folder (the folder is in use by another process). I can, however, create other folders and files in the media folder.

### Version

0.11.1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.189:5000/api/config/schema
mqtt:
  host: 192.168.1.189
  user: ----
  password: ---

database:
  path: /config/frigate.db
objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
record:
  enabled: true
  expire_interval: 60
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones:
      - "framsida"
      - "infart"
      - "parkering"
cameras:
  Matrummet:
    ffmpeg:
      inputs:
        - path: ----
          roles:
          - record
          - rtmp
        - path: ----
          roles:
            - detect
    detect:
      width: 640
      height: 352
      fps: 5
  Sovrummet:
        ffmpeg:
          inputs:
            - path: ---
              roles:
              - record
              - rtmp
            - path: ----
              roles:
                - detect
        detect:
          width: 640
          height: 352
          fps: 5
  Uppfarten:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.1.219/flv?
          roles:
            - record
            - rtmp
        - path: http://192.168.1.219/flv?
          roles:
            - detect
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 1
      required_zones:
        - "framsida"
        - "infart"
        - "parkering"
    detect:
      width: 896
      height: 512
      fps: 10
    motion:
      mask:
        - 574,0,896,0,723,143,633,125
    objects:
      filters:
        car:
          mask:
            - 725,72,668,46,598,64,637,121,717,141
    zones:
      infart:
        coordinates: 652,165,740,173,715,144,676,140,640,133
      parkering:
        coordinates: 788,153,668,157,673,285,864,313
        objects:
          - person
      framsida:
        coordinates: 0,0,0,512,685,512,638,120
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-11-04 08:16:28] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[Errno 74] Bad message: '/media/frigate'
[2022-11-04 08:16:28] frigate.app                    INFO    : Creating directory: /media/frigate/recordings
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink
