### ISSUE TITLE
[Support]: [Errno 113] No route to host - MQTT?!?!

### ISSUE THREAD

**Issue by afarley** [blakeblackshear/frigate#4249]
### Describe the problem you are having

I recently migrated a working configuration from Manjaro to Arch. [Both using docker 20.10.21-1] The MQTT broker is on a Home Assistant system and is verified as reachable from the Arch installation using MQTT Explorer (netcat also indicates that the 1883 port of open on the Home Assistant system). However, when I start up Frigate on the new Arch system (either stable or stable-amd64nvidia) I get the "[Errno 113] No route to host" error. I installed an MQTT broker on the Arch system to see if there was a firewall issue and still got the same error. 

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.9
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: REDACTED
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: 'REDACTED'
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
#  tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
#  tls_client_cert: /path/to/client.crt
#  tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
#  tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:  
  bedroom: # <------ Camera 4
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@192.168.1.36:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    objects:
      track:
        - person
    detect:
      width: 3840
      height: 2160
      fps: 4   
            
logger:
  # Optional: default log level (default: shown below)
  default: debug
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: debug
    frigate.app: debug
    frigate.zeroconf: debug
    detector.<detector_name>: debug
#    watchdog.camera_1: debug
#    ffmpeg.camera_1.rtmp: error
#    ffmpeg.camera_1.detect: error
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-11-04 11:30:15] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2022-11-04 11:30:15] peewee_migrate                 INFO    : Starting migrations
[2022-11-04 11:30:15] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[2022-11-04 11:30:15] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
[2022-11-04 11:30:15] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 113] No route to host
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
^C[s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
ffprobe version n5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x558845723e00] max delay reached. need to consume packet
[rtsp @ 0x558845723e00] RTP: missed 26 packets
[h264 @ 0x558845728c00] left block unavailable for requested intra mode
[h264 @ 0x558845728c00] error while decoding MB 0 75, bytestream 198805
[h264 @ 0x558845728c00] concealing 14449 DC, 14449 AC, 14449 MV errors in I frame
Input #0, rtsp, from 'rtsp://admin:REDACTED@192.168.1.36:554/rtsp':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.050000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 20 fps, 20 tbr, 90k tbn
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

tried with and without Coral USB
