### ISSUE TITLE
[Config Support]: How to configure required zones by object type?

### ISSUE THREAD

**Issue by RexWheeler** [blakeblackshear/frigate#4254]
### Describe the problem you are having

One of my cameras oversees the street in front of my house and I would like to eliminate events for parked cars. I only want to have a car related event if a car spends some time moving on the street. I believe the recommended way to do this is to set up a required zone so that a detected car must pass through a required zone in order for an event to be declared.

The challenge I have is that on the same camera I also want to raise an event anytime a person is detected anywhere.

Is there a syntax I can use that says cars have one set of required zones and people have a different set of required zones? 

I currently have the following under my camera config:
```
    record:
      events:
        required_zones:
          - street
          - all
```
I think I am looking for something like:
```
    record:
      events:
      - object: car
         required_zones:
         - street 
      - object: person
         required_zones:
         - all
```

Config and image showing the zone definitions below

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
snapshots:
  enabled: True
  timestamp: False
  bounding_box: true
  retain:
    default: 90
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
detect:
  stationary:
    max_frames:
      objects:
        person: 1200
cameras:
  culdesac:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
        rtmp: -c:v copy -f flv -ar 44100 -c:a aac
      inputs:
        - path: rtsp://192.168.1.1:7447/LF1dAnYcoiLuxxx
          roles:
            - detect
            - rtmp
        - path: rtsp://192.168.1.1:7447/gnudUvfMbAxxxxx
          roles:
            - record
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
        - car
    record:
      events:
        required_zones:
          - street
          - all
    zones:
      street:
        coordinates: 1280,203,1112,199,936,194,724,109,640,109,522,118,391,157,265,205,201,263,367,263,483,333,1280,352
        objects:
          - car
      all:
        coordinates: 1280,720,1280,0,0,0,0,720
        objects:
          - person
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Image showing my "street" zone (where I want to ensure a car passes through before declaring an event). The "all" zone covers the full frame and I would like events if a person is found anywhere in the image.

![Screenshot 2022-11-04 174955](https://user-images.githubusercontent.com/6587943/200093718-2d82a015-d059-47ea-8bdf-20df56e170f6.jpg)

**Comment by NickM-27** [comment]
Just set the objects on the zone:

```yaml
    zones:
      driveway:
        coordinates: 370,702,292,760,185,822,332,850,281,912,202,889,122,960,0,960,0,707,161,660
        objects:
          - car
          - cat
          - dog
          - person
      front_yard:
        coordinates: 1280,733,1111,673,945,699,728,717,377,699,195,822,337,853,280,913,190,890,124,960,1280,960
        objects:
          - cat
          - dog
          - person
    record:
      events:
        required_zones:
          - driveway
          - front_yard
```
