### ISSUE TITLE
[Config Support]: Getting a config error

### ISSUE THREAD

**Issue by languy99** [blakeblackshear/frigate#4255]
### Describe the problem you are having

Hello, 

I was hoping I could get some help to see why I keep getting an error in frigate. 

This is what I used to create a new stack in Portainer. 

```
#######################FRIGATE
Verison: "3.9"
Services:
  frigate:
  container_name: frigate
  image: blakeblackshear/frigate:stable-amd64
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime
   - /home/frigate/config.yml:/config/config.yml:ro
  ports:
  - 5000:5000
  - 1935:1935
  environment:
   FRIGATE_RTSP_PASSWORD: "topsecretfrigatepassword"
```

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: [homeassistant ip]
  port: 1883
  user: [user]
  password: [password]
  stats_interval: 60

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://[user]:[password]@[camera ip]:554/cam/realmonitor?channel=4&subtype=0
          roles:
            - detect
    detect:
      width: 1280
      height: 720

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
[Errno 21] Is a directory: '/config/config.yml'
[2022-11-05 02:09:19] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 896, in parse_file
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by RexWheeler** [comment]
Try mapping your config to a directory instead of a file. Mine looks like:

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/tiger/frigate/config:/config:ro
      - /mnt/frigate/video:/media/frigate
      - /home/tiger/frigate/db:/db

**Comment by NickM-27** [comment]
What is the name of your config file? Also recommend changing the image to `stable` to update to the latest frigate version.

**Comment by languy99** [comment]
> What is the name of your config file? Also recommend changing the image to `stable` to update to the latest frigate version.

It's config.yml

**Comment by NickM-27** [comment]
Docker will create a directory for any file that is mapped that does not exist, this usually means the host mapping in the docker compose is incorrect. Portainer could be messing with things as well.

**Comment by languy99** [comment]
I figured it out. 

The issue was in this line. 

`/home/frigate/config.yml:/config/config.yml:ro`

The directions that I followed did not put frigate in the home folder, it put it in the root folder. 

it should be 

`/root/frigate/config.yml:/config/config.yml:ro`

**Comment by NickM-27** [comment]
Makes sense, glad it's solved. Will close this and feel free to create a new issue if something comes up.

**Comment by sanderlv** [comment]
May I ask...

this is where I want Frigate to be:
```
root@frigate-02:/frigate/compose# pwd
/frigate/compose
root@frigate-02:/frigate/compose# ls
compose.yml
root@frigate-02:/frigate/compose#
```

My compose (for now) change it a few:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config/config.yml:/config/config.yml
      - /root/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

Giving me:
```
 s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | 2023-04-14 13:45:20.970934107  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-04-14 13:45:20.979225369  [INFO] Starting Frigate...
frigate  | 2023-04-14 13:45:20.985963358  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 23, in <module>
frigate  |     with open(config_file) as f:
frigate  | IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
frigate  | 2023-04-14 13:45:21.143568560  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | 2023-04-14 13:45:21.531956073  *************************************************************
frigate  | 2023-04-14 13:45:21.531975555  *************************************************************
frigate  | 2023-04-14 13:45:21.531984750  ***    Your config file is not valid!                     ***
frigate  | 2023-04-14 13:45:21.531993337  ***    Please check the docs at                           ***
frigate  | 2023-04-14 13:45:21.532001887  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2023-04-14 13:45:21.532012270  *************************************************************
frigate  | 2023-04-14 13:45:21.532022552  *************************************************************
frigate  | 2023-04-14 13:45:21.532032745  ***    Config Validation Errors                           ***
frigate  | 2023-04-14 13:45:21.532042982  *************************************************************
frigate  | 2023-04-14 13:45:21.532055264  [Errno 21] Is a directory: '/config/config.yml'
frigate  | 2023-04-14 13:45:21.532570505  [2023-04-14 13:45:21] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
frigate  | 2023-04-14 13:45:21.532582455  Traceback (most recent call last):
frigate  | 2023-04-14 13:45:21.532583453    File "/opt/frigate/frigate/app.py", line 351, in start
frigate  | 2023-04-14 13:45:21.532584800      self.init_config()
frigate  | 2023-04-14 13:45:21.532586275    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate  | 2023-04-14 13:45:21.532587320      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2023-04-14 13:45:21.532588202    File "/opt/frigate/frigate/config.py", line 1064, in parse_file
frigate  | 2023-04-14 13:45:21.532593763      with open(config_file) as f:
frigate  | 2023-04-14 13:45:21.532594547  IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
frigate  | 2023-04-14 13:45:21.532604000
frigate  | 2023-04-14 13:45:21.532613665  *************************************************************
frigate  | 2023-04-14 13:45:21.532622948  ***    End Config Validation Errors                       ***
frigate  | 2023-04-14 13:45:21.532633295  *************************************************************
frigate  | 2023-04-14 13:45:22.147238849  [INFO] Preparing go2rtc config...
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 23, in <module>
frigate  |     with open(config_file) as f:
frigate  | IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
frigate  | 2023-04-14 13:45:22.249093736  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | 2023-04-14 13:45:22.641316873  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-04-14 13:45:22.648692747  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
```

Whats wrong? Running Docker on Ubuntu server.
