### ISSUE TITLE
[HW Accel Support]: 

### ISSUE THREAD

**Issue by alanmgomes** [blakeblackshear/frigate#4269]
### Describe the problem you are having

I have some cameras that the manufacturer didn't implement Onvif correctly, they don't have the method that describes the streams. (error bellow)
They work normally via rtsp, but I can't use hwaccel, because Frigate uses ffprobe for it.
Is there any way to get around this ffprobe check via configuration for using hwaccel?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: automation.local
  port: 1884
  user: frigate
  password: <pass>

logger:
  default: info

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

objects:
  track:
    - person
    - car
    - dog
    - umbrella

snapshots:
  enabled: True

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 2
    mode: motion
  events: 
    retain:
      default: 3
      mode: active_objects

cameras:
  Portao: # <------ Name the camera
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:<pass>@portao.camera:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://admin:<pass>@portao.camera:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    zones:
      portao_calcada:
        coordinates: 125,475,639,480,640,431,463,215,143,219
        objects:
          - person
          - car
          - dog
          - umbrella
      portao_pessoas:
        coordinates: 125,475,639,480,640,431,463,215,143,219
        objects:
          - person
          - umbrella
      portao_interfone:
        coordinates: 0,480,640,480,607,420,295,466,0,441
        objects:
          - person
          - umbrella

  Frente: # <------ Name the camera
    ffmpeg:
      inputs:
         # High Resolution Stream
        - path: rtsp://admin:<pass>@frente.camera:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://admin:<pass>0@frente.camera:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,0,0,214,67,218,116,0

  Lavanderia: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:<pass>@lavanderia.camera:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://admin:<pass>@lavanderia.camera:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

  Garagem: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://admin:<pass>@garagem.camera:554/live/mpeg4 # <----- Update for your camera
          roles:
            - record
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  Rampa: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://admin:<pass>@rampa.camera:554/
          roles:
            - record
            - rtmp
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.8
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  Churrasqueira: # <------ Name the camera
    ffmpeg:
      hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://admin:<pass>@churrasqueira.camera:554/
          roles:
            - record
            - rtmp
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.8
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    restart: unless-stopped
    container_name: frigate
    privileged: true
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "160mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/frigate/config/config.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "<pass>"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    depends_on:
      - emqx
```

### Relevant log output

```shell
[2022-11-06 21:09:37] watchdog.Lavanderia            INFO    : No frames received from Lavanderia in 20 seconds. Exiting ffmpeg...
[2022-11-06 21:09:37] watchdog.Lavanderia            INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-06 21:09:37] frigate.video                  ERROR   : Lavanderia: Unable to read frames from ffmpeg process.
[2022-11-06 21:09:37] frigate.video                  ERROR   : Lavanderia: ffmpeg process is not running. exiting capture thread...
[2022-11-06 21:09:47] watchdog.Lavanderia            ERROR   : Ffmpeg process crashed unexpectedly for Lavanderia.
[2022-11-06 21:09:47] watchdog.Lavanderia            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-06 21:09:47] ffmpeg.Lavanderia.detect       ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
[2022-11-06 21:09:47] ffmpeg.Lavanderia.detect       ERROR   :     Last message repeated 104 times
[2022-11-06 21:09:47] ffmpeg.Lavanderia.detect       ERROR   : Finishing stream 1:0 without any data written to it.
[2022-11-06 21:09:47] ffmpeg.Lavanderia.detect       ERROR   : [swscaler @ 0x55af84e5d0] deprecated pixel format used, make sure you did set range correctly
[2022-11-06 21:09:47] ffmpeg.Lavanderia.detect       ERROR   : [flv @ 0x55af874ea0] Failed to update header with correct duration.
[2022-11-06 21:09:47] ffmpeg.Lavanderia.detect       ERROR   : [flv @ 0x55af874ea0] Failed to update header with correct filesize.
[2022-11-06 21:09:54] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:38194]
```

### FFprobe output from your camera

```shell
alan@automation:~ $ ffprobe version 4.3.4-0+deb11u1+rpt3 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt3 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x5567ab9870] method DESCRIBE failed: 404 Not Found
rtsp://admin:<pass>@lavanderia.camera:554/cam/realmonitor?channel=1: Server returned 404 Not Found
^C
[1]+  Exit 1                  ffprobe rtsp://admin:<pass>@lavanderia.camera:554/cam/realmonitor?channel=1
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Intelbras IMC X (Its a Dahua IMOU Cue 2c with some modifications from a Brazilian reseller)
