### ISSUE TITLE
ffmpeg errors when enabling hardware acceleration (rpi4)

### ISSUE THREAD

**Issue by paulmorabito** [blakeblackshear/frigate#428]
Hi,

I'm running Home Assistant as follows:

## System Health

version | 2020.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v8
arch | aarch64
timezone | XXX

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4964
Installed Version | 1.9.0
Stage | running
Available Repositories | 702
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.9
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 109.3 GB
disk_used | 7.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), deCONZ (6.6.1), SSH & Web Terminal (7.8.0), Mosquitto broker (5.1), Unraid API (1.1), Glances (0.9.1), TasmoAdmin (0.13.1), motionEye (0.10.2), Frigate NVR (1.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 2
resources | 5

</details>

Using Frigate with hardware acceleration enabled for RPI, I get the following errors:

```
ffmpeg sent a broken frame. something is wrong.: 
ffmpeg process is not running. exiting capture thread... frigate homeassistant
```

dmesg 

```
[ 5503.610131] bcm2835-codec bcm2835-codec: dma_alloc_coherent of size 3112960 failed
[ 5503.626189] cma: cma_alloc: alloc failed, req-size: 760 pages, ret: -12
[ 5503.638917] bcm2835-codec bcm2835-codec: dma_alloc_coherent of size 3112960 failed
[ 5503.655025] cma: cma_alloc: alloc failed, req-size: 760 pages, ret: -12
[ 5503.666365] bcm2835-codec bcm2835-codec: dma_alloc_coherent of size 3112960 faile
```

These continue endlessly. However, without any hwaccel_args, it seems to load and start fine.

My config for Frigate is:

```
web_port: 5000
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
save_clips:
  clips_dir: /media/frigate
  max_seconds: 300
mqtt:
  host: 192.168.1.193
  port: 1883
  topic_prefix: frigate
  user: mqtt
  password: mqtt
ffmpeg:
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - panic
  input_args:
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-rtsp_transport'
    - tcp
    - '-stimeout'
    - '5000000'
    - '-use_wallclock_as_timestamps'
    - '1'
  output_args:
    - '-f'
    - rawvideo
    - '-pix_fmt'
    - yuv420p
cameras:
  Study:
    ffmpeg:
      input: 'rtsp://192.168.1.64/stream2'
    fps: 5

```

I tried adding both versions of the hardware acceleration flags as per the main page and got the the same error above. Any help would be very appreciated!

Thanks,

**Comment by blakeblackshear** [comment]
Turn off protection mode for the addon and try again.

**Comment by paulmorabito** [comment]
That worked. Thanks!

**Comment by paulmorabito** [comment]
That removed the errors but getting something a little different now:

```
ffmpeg -hide_banner -loglevel panic -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.64/stream2 -r 5 -f rawvideo -pix_fmt yuv420p pipe:
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: development
 * Debug mode: off
No frames received from Study in 5 seconds. Exiting ffmpeg...
Waiting for ffmpeg to exit gracefully...
FFmpeg didnt exit. Force killing...
Study: ffmpeg sent a broken frame. something is wrong.
Study: ffmpeg process is not running. exiting capture thread...
Creating ffmpeg process...
ffmpeg -hide_banner -loglevel panic -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.64/stream2 -r 5 -f rawvideo -pix_fmt yuv420p pipe:
No frames received from Study in 5 seconds. Exiting ffmpeg...
Waiting for ffmpeg to exit gracefully...
FFmpeg didnt exit. Force killing...
Study: ffmpeg sent a broken frame. something is wrong.
Study: ffmpeg process is not running. exiting capture thread...
Creating ffmpeg process...
ffmpeg -hide_banner -loglevel panic -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.64/stream2 -r 5 -f rawvideo -pix_fmt yuv420p pipe:
No frames received from Study in 5 seconds. Exiting ffmpeg...
Waiting for ffmpeg to exit gracefully...
```

The RTSP feed is definitely working and again without hardware acceleration, doesn't give the error.

**Comment by blakeblackshear** [comment]
Did you increase the GPU memory? Also, the beta version increases that timeout and may solve your issue.

**Comment by paulmorabito** [comment]
I set gpu_mem=128 in config.txt and still getting same error. Should it be higher?

I am trying to get the beta version started but it keeps giving config errors. I copied the config from the non-beta version directly. Has the format changed?

**Comment by blakeblackshear** [comment]
You will need to update your config in several areas. See the updated Readme https://github.com/blakeblackshear/frigate/tree/release-0.8.0

**Comment by paulmorabito** [comment]
Getting the same problem if I use latest beta with 64-bit acceleration flag (h264_v4l2m2m):

```
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
```

dmesg:

```
[55874.766128] cma: cma_alloc: alloc failed, req-size: 760 pages, ret: -12
[55874.779470] bcm2835-codec bcm2835-codec: dma_alloc_coherent of size 3112960 failed
[55874.802394] cma: cma_alloc: alloc failed, req-size: 760 pages, ret: -12
[55874.814947] bcm2835-codec bcm2835-codec: dma_alloc_coherent of size 3112960 failed
```

If I change h264_v4l2m2m to h264_mmal then I get no dmesg errors but the same ffmpeg errors. What's strange about this is that I'm definitely running 64bit:

```
﻿# uname -ma
Linux homeassistant 5.4.79-v8 #1 SMP PREEMPT Fri Dec 18 21:50:34 UTC 2020 aarch64 HassOS
#
```

As I mentioned before, protected mode is disabled and I set "gpu_mem=128" in config.txt. 

config for frigate is:

```
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
  host: 192.168.1.193
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: mqtt
ffmpeg:
  global_args: '-hide_banner -loglevel fatal'
  hwaccel_args: '-c:v - h264_v4l2m2m'
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    record: >-
      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    clips: >-
      -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    rtmp: '-c copy -f flv'
cameras:
  back:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.1.64/stream2'
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
    best_image_timeout: 60
save_clips:
  max_seconds: 300
  tmpfs_cache_size: 256m
  retain:
    default: 10
    objects:
      person: 15
```

**Comment by blakeblackshear** [comment]
See what the logs say if you update the log level in global_args for ffmpeg to info.

**Comment by paulmorabito** [comment]
Here you go: with both hardware acceleration options:

```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Creating tmpfs of size 256m
frigate.app                    INFO    : Camera processor started for back: 39
frigate.app                    INFO    : Capture process started for back: 41
detector.coral                 INFO    : Starting detection process: 37
frigate.edgetpu                INFO    : Attempting to load TPU as usb:0
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.
frigate.mqtt                   INFO    : MQTT connected
ffmpeg.back.detect             ERROR   : Input #0, rtsp, from 'rtsp://192.168.1.64/stream2':
ffmpeg.back.detect             ERROR   :   Metadata:
ffmpeg.back.detect             ERROR   :     title           : Session streamed by "Amba RTSP Server"
ffmpeg.back.detect             ERROR   :     comment         : stream2
ffmpeg.back.detect             ERROR   :   Duration: N/A, start: 1608681124.307056, bitrate: N/A
ffmpeg.back.detect             ERROR   :     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 640x360 [SAR 1:1 DAR 16:9], 29.58 tbr, 90k tbn, 90k tbc
ffmpeg.back.detect             ERROR   : [NULL @ 0x5598928320] Unable to find a suitable output format for 'h264_mmal'
ffmpeg.back.detect             ERROR   : h264_mmal: Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
```

```
ffmpeg.back.detect             ERROR   : Input #0, rtsp, from 'rtsp://192.168.1.64/stream2':
ffmpeg.back.detect             ERROR   :   Metadata:
ffmpeg.back.detect             ERROR   :     title           : Session streamed by "Amba RTSP Server"
ffmpeg.back.detect             ERROR   :     comment         : stream2
ffmpeg.back.detect             ERROR   :   Duration: N/A, start: 1608681222.830978, bitrate: N/A
ffmpeg.back.detect             ERROR   :     Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 640x360 [SAR 1:1 DAR 16:9], 29.50 tbr, 90k tbn, 90k tbc
ffmpeg.back.detect             ERROR   : [NULL @ 0x55b2ad0320] Unable to find a suitable output format for 'h264_v4l2m2m'
ffmpeg.back.detect             ERROR   : h264_v4l2m2m: Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
```

**Comment by blakeblackshear** [comment]
Can you post your config again with the h264_v4l2m2m version?

**Comment by paulmorabito** [comment]
Here it is, I basically took the sample from the github page and amended only the necessary values:

```
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
  host: 192.168.1.193
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: mqtt
ffmpeg:
  global_args: '-hide_banner -loglevel info'
  hwaccel_args: '-c:v - h264_v4l2m2m'
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    record: >-
      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    clips: >-
      -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    rtmp: '-c copy -f flv'
cameras:
  back:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.1.64/stream2'
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
```
