### ISSUE TITLE
`min_person_area` doesn't seem to be filtering objects

### ISSUE THREAD

**Issue by aav7fl** [blakeblackshear/frigate#43]
Right now I have a camera set up that streams in 1080p. Because of that, I knew I would need to raise the `min_person_area` to account for the extra pixels. Below is one of the debug frames that I capture when an MQTT message is sent for a person being detected.

![image](https://user-images.githubusercontent.com/3487107/59798647-a1534880-92b0-11e9-8cca-241ec6657434.png)

I'm using a `min_person_area` of `3000`, so it doesn't seem like a person in the image across the street below has enough pixels to meet that criteria. 

Is there a chance the MQTT person message is being sent without taking into account the `min_person_area`, or am I off by an order of magnitude with my values?

Below is my config.

```yaml
web_port: 5000

mqtt:
  host: mqtt
  port: 8883
  topic_prefix: frigate
  user: <user>
  password: <password>

cameras:
  front_window:
    rtsp:
      user: <username>
      host: <ip_address>
      port: <port>
      password: <password>
      path: <path>
    regions:
      - size: 700
        x_offset: 1220
        y_offset: 200
        min_person_area: 3000
        threshold: 0.9
      - size: 1080
        x_offset: 0
        y_offset: 0
        min_person_area: 3000
        threshold: 0.9
```
