### ISSUE TITLE
[Support]: Mask and Zone Creator not rendering correctly

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#4304]
### Describe the problem you are having

When using the mask and zone creator I am trying to draw a simple rectangle. I start at the bottom left, then bottom right, upper right, upper left. This is what I am left with

![image](https://user-images.githubusercontent.com/7737834/200390049-934841f3-143c-4367-b371-37a67adf5b7b.png)

Is this just a display error? Are my zones getting created correctly regardless?

### Version

11

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local

ffmpeg:
  #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/card0 -hwaccel_output_format yuv420p
  #hwaccel_args:
    #-hwaccel h264_rkmpp
    #-hwaccel_device /dev/dri/card0
    #-hwaccel_output_format yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1

detect:
  width: 704
  height: 480
  fps: 5

snapshots:
  enabled: True

cameras:
  driveway:
    motion:
      mask:
        - 0,0,704,0,704,166,0,184
    ffmpeg:
      inputs:
        - path: rtsp://admin:foo@192.168.1.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Frigate stats

```json
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

amcrest
