### ISSUE TITLE
[HW Accel Support]: Raspberry Pi 4 (RPI OS 64bit) hardware acceleration not working

### ISSUE THREAD

**Issue by Vogete** [blakeblackshear/frigate#4307]
### Describe the problem you are having

Raspberry Pi 4 (8GB) on Raspberry Pi OS 64 bit does not work with hardware acceleration enabled. (Coral USB TPU successfully detected)

Everything works until I enable hardware acceleration in the config file such as:
```yaml
ffmpeg:
  hwaccel_args: -c:v h264_v4l2m2m
```

I tried Ubuntu 64 bit, Raspberry Pi OS 32 bit, and now Raspberry Pi OS 64 bit. `ffprobe` works perfeclty outside the container, but inside the container I need to pass the `-rtsp_transport tcp` argument to it. (otherwise it just hangs and never works)
Of course, I tried passing `input_args: -rtsp_transport tcp` in the frigate config (under `ffmpeg`) too, which was the only way I could frigate get the RTSP feed in 32bit RPI OS (no hardware acceleration).
In 64 bit RPI OS I can make the RTSP feed appear with the config attached, IF I don't use ` hwaccel_args: -c:v h264_v4l2m2m`. As soon as I turn it on, it stops working, and I get a green screen.

I set `gpu_mem=256`, and added a `shm_size: "128mb"` as well.

I tried both version 0.10.1, and 0.11.1, both behaved the same way.

For the RTSP feed, I'm using my phone with an RTSP server on it _(I know it's weird, but it's a test setup to pre-configure as much as possible before deployment, and it works with no HW acceleration!)_, with a 720x1280 resolution, 30fps, and H264 encoding.

I even tried installing ffmpeg directly on the RPI (ffprobe worked fine on it), and pass it through the container, but it resulted in the same behavior.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  port: 1883

logger:
  default: debug

cameras:
  back:
    ffmpeg:
      inputs:
        # - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
        #   roles:
        #     - detect
        #     # - rtmp
        - path: rtsp:192.168.1.96:1935
          roles:
            - detect

    detect:
      # ez csak tesztelesre van.
      width: 720
      height: 1280

ffmpeg:
  hwaccel_args: -c:v h264_v4l2m2m

detectors:
  coral:
    type: edgetpu
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
version: '3'
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    restart: unless-stopped
    environment:
      - TZ=Europe/Copenhagen
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /etc/mosquitto:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /var/log/mosquitto:/mosquitto/log
    networks:
      - mqtt_network


  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/frigate/frigate.yml:/config/config.yml:ro
      - /opt/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      - mqtt_network

networks:
  mqtt_network:
```

### Relevant log output

```shell
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | [2022-11-07 21:18:12] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate    | Starting migrations
frigate    | [2022-11-07 21:18:12] peewee_migrate                 INFO    : Starting migrations
frigate    | [2022-11-07 21:18:12] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate    | [2022-11-07 21:18:12] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate    | There is nothing to migrate
frigate    | [2022-11-07 21:18:12] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | [2022-11-07 21:18:12] frigate.mqtt                   DEBUG   : MQTT connected
frigate    | [2022-11-07 21:18:12] frigate.app                    INFO    : Output process started: 216
frigate    | [2022-11-07 21:18:12] ws4py                          INFO    : Using epoll
frigate    | [2022-11-07 21:18:12] frigate.app                    INFO    : Camera processor started for back: 222
frigate    | [2022-11-07 21:18:12] frigate.app                    INFO    : Capture process started for back: 224
frigate    | [2022-11-07 21:18:12] urllib3.connectionpool         DEBUG   : Starting new HTTPS connection (1): api.github.com:443
frigate    | [2022-11-07 21:18:12] urllib3.connectionpool         DEBUG   : https://api.github.com:443 "GET /repos/blakeblackshear/frigate/releases/latest HTTP/1.1" 200 1216
frigate    | [2022-11-07 21:18:12] ws4py                          INFO    : Using epoll
frigate    | [2022-11-07 21:18:12] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)
frigate    | [2022-11-07 21:18:12] peewee                         DEBUG   : ('UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)', [30, None])
frigate    | [2022-11-07 21:18:12] detector.coral                 INFO    : Starting detection process: 215
frigate    | [2022-11-07 21:18:12] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | [2022-11-07 21:18:15] frigate.edgetpu                INFO    : TPU found
frigate    | [2022-11-07 21:18:32] watchdog.back                  INFO    : No frames received from back in 20 seconds. Exiting ffmpeg...
frigate    | [2022-11-07 21:18:32] watchdog.back                  INFO    : Waiting for ffmpeg to exit gracefully...
frigate    | [2022-11-07 21:19:02] watchdog.back                  INFO    : FFmpeg didnt exit. Force killing...
frigate    | [2022-11-07 21:19:02] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
frigate    | [2022-11-07 21:19:02] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
root@70ad735d998b:/opt/frigate# ffprobe rtsp://192.168.1.96:1935 -rtsp_transport tcp

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://192.168.1.96:1935':
  Metadata:
    title           : Unnamed
    comment         : N/A
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 720x1280, 30 fps, 29.92 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 32000 Hz, stereo, fltp


root@70ad735d998b:/opt/frigate# ffprobe rtsp://192.168.1.96:1935

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55ce3c1030] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, rtsp, from 'rtsp://192.168.1.96:1935':
  Metadata:
    title           : Unnamed
    comment         : N/A
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac, 32000 Hz, stereo, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

A smartphone, running RTSP server (h264, 720p, 30fps)
