### ISSUE TITLE
[Config Support]: Frigate is not showing cars

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#4308]
### Describe the problem you are having

Trying to get frigate to create events for cars. I am getting them for persons but not cars. As you can see, here is the driveway_area zone, but when I pull our vehicles in or out of it, no events are getting raised.

![image](https://user-images.githubusercontent.com/7737834/200432725-8fbf509e-43f1-4465-89a9-d395f0dda00e.png)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: homeassistant.local
  user: user
  password: password

ffmpeg:
  #hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/card0 -hwaccel_output_format yuv420p
  #hwaccel_args:
    #-hwaccel h264_rkmpp
    #-hwaccel_device /dev/dri/card0
    #-hwaccel_output_format yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1

detect:
  width: 704
  height: 480
  fps: 5

snapshots:
  enabled: True

cameras:
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp

  driveway:
    motion:
      mask:
        - 0,0,704,0,704,166,0,184
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    zones:
      front_street:
        coordinates: 0,250,704,239,704,170,0,181
        objects:
          - person
          - car
      driveway_area:
        coordinates: 704,480,0,480,0,226,704,233
        objects:
          - person
          - car
    snapshots:
      required_zones:
        - front_street
        - driveway_area

  south_side:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.22:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp

  back_north:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.23:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
```

### Relevant log output

```shell
No relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
