### ISSUE TITLE
Do not maintain a connection to the camera if not required

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4325]
**Describe what you are trying to accomplish and why in non technical terms**

I have a battery-powered camera in which I want to add to Frigate, but I don't want Frigate to record or detect objects on it all the time. I will enable Frigate's recording dynamically through external events, like by an external motion sensor in Home Assistant.

When there's no one connected in the camera, the camera enters in sleep mode to save battery.

**Describe the solution you'd like**
Ideally Frigate should NOT maintain a connection with the camera for a configuration like below:

```yaml
video_porteiro:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/camera.video_porteiro
          roles:
            - detect
            - record
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
        rtmp: -c:v copy -c:a aac -f flv
    record:
      enabled: false
    rtmp:
      enabled: true
    detect:
      enabled: false
      width: 640
      height: 360
    live:
      height: 360
```

I have `rtmp.enabled: true`, but I have no client streaming from it (and `preload` is not activated in Home Assistant configuration). Frigate should understand that a connection with the camera is not required in this situation.

**Describe alternatives you've considered**
I can't think of any.

**Additional context**
I'm using go2rtc to capture my Tuya battery-powered video doorbell through this:

- https://github.com/felipecrs/hass-expose-camera-stream-source#importing-home-assistant-cameras-to-go2rtc-andor-frigate

And I'm reusing the go2rtc stream in Frigate. In the go2rtc info panel I can see that it's Frigate  who is connected to the stream.
