### ISSUE TITLE
[Support]: 0.11.1 docker verison runs perfectly, 012.0-1bc9efd fails with restream error

### ISSUE THREAD

**Issue by ashleyw-gh** [blakeblackshear/frigate#4329]
### Describe the problem you are having

Cameras, run fine on 0.11.1 tagged version.
anything after then  like 012.0-1bc9efd  fails with the following error;
```
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
Camera front has restream enabled, but restream is not assigned to an input.
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 344, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 79, in init_config
    self.config = user_config.runtime_config
  File "/opt/frigate/frigate/config.py", line 928, in runtime_config
    raise ValueError(
ValueError: Camera front has restream enabled, but restream is not assigned to n input.

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

### Version

012.0-1bc9efd

### Frigate config file

```yaml
database:
  path: /db/frigate.db
mqtt:
  host: <mqttip>
  port: <mqttip port>
  topic_prefix: frigate
  user: <frigateuser>
  password: <password>
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://<logon:password@camera1IP:port>/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<logon:password@camera1IP:port>/h264Preview_01_main
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 2
    motion:
      mask:
        - 196,0,196,26,0,27,0,0
    objects:
      filters:
        person:
          min_area: 700
          mask:
            - 230,230,352,229,353,288,235,294
      track:
        - person
        - animal
  back:
    ffmpeg:
      inputs:
        - path: rtsp://<logon:password@camera2IP:port>/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<logon:password@camera2IP:port>/h264Preview_01_main
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 2
    motion:
      mask:
        - 490,195,489,308,558,308,606,127,565,93,499,103
        - 640,0,640,73,320,87,226,107,130,142,91,275,78,328,0,330,0,0
    objects:
      filters:
        person:
          min_area: 700
          mask:
            - 488,283,592,285,594,312,492,312
      track:
        - person
        - animal
motion:
  improve_contrast: True
record:
  enabled: True
  events:
    retain:
      default: 2
      mode: all
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 2
birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
Camera front has restream enabled, but restream is not assigned to an input.
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 344, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 79, in init_config
    self.config = user_config.runtime_config
  File "/opt/frigate/frigate/config.py", line 928, in runtime_config
    raise ValueError(
ValueError: Camera front has restream enabled, but restream is not assigned to n input.

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

### FFprobe output from your camera

```shell
will provide if relevant.
```

### Frigate stats

```json
{"back":{"camera_fps":5.1,"capture_pid":236,"detection_fps":1.9,"pid":234,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":4.5,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":7.79,"pid":217},"coral2":{"detection_start":0.0,"inference_speed":7.78,"pid":219}},"front":{"camera_fps":5.1,"capture_pid":235,"detection_fps":2.6,"pid":232,"process_fps":5.1,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":3219.5,"mount_type":"tmpfs","total":3221.2,"used":1.8},"/media/frigate/clips":{"free":3647013.4,"mount_type":"nfs4","total":3861563.6,"used":214550.2},"/media/frigate/recordings":{"free":3647013.4,"mount_type":"nfs4","total":3861563.6,"used":214550.2},"/tmp/cache":{"free":994.2,"mount_type":"tmpfs","total":1000.0,"used":5.8}},"temperatures":{},"uptime":876,"version":"0.11.1-2eada21"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink rlc810a

### Any other information that may be helpful

any tag after 0.11.1 generates the error as documented and results in the container failing to start and repeatedly dying and restarting. The API output is from 0.11.1
I'm detecting on the lowres stream but recording using the higher resolution stream if that makes a difference.
I'm running a pair of Coral USB devices - just because a 2nd one unexpectedly arrived form a backorder.
I'm running on Ubuntu as the host OS on VMware ESXi8 with usb passthrough on the Coral devices (by passing through the usb controller card).
