### ISSUE TITLE
[Support]: Latest stable not recording in Kubernetes

### ISSUE THREAD

**Issue by danielvschoor** [blakeblackshear/frigate#4330]
### Describe the problem you are having

I've ported my docker-compose Frigate instance to Kubernetes, but I'm experiencing a weird issue where there are no recordings if I use the latest docker image (frigate:stable), but it does record when I use the older image (frigate:stable-amd64). There are no errors in the logs, and I've set the "record" flag everywhere I can think of in the config.

The latest stable did record when I was still using docker-compose, and I used Kompose to create a Kubernetes deployment.yaml from my docker-compose file. 

There are no differences between the working image and the non-working image, I just change the tag in Rancher.

My volumes and volumeMounts in my deployment.yaml look like this:
```    
       volumeMounts:
        - mountPath: /media/frigate
          name: cameras
        - mountPath: /db
          name: db
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /dev/dri
          name: drivers
        - mountPath: /config
          name: frigate-config
        - mountPath: /tmp/cache
          name: tmp
      volumes:
      - hostPath:
          path: /mnt/cameras/frigate
          type: ""
        name: cameras
      - hostPath:
          path: /home/daniel/frigate/db
          type: ""
        name: db
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: dshm
      - hostPath:
          path: /dev/dri
          type: ""
        name: drivers
      - configMap:
          defaultMode: 420
          name: frigate-config
          optional: false
        name: frigate-config
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: tmp
```

I don't mind using the stable-amd64 image, but I did like the latest changes, and it would be a bummer not to have access to it.

Any idea what could be causing the recording issue?

### Version

0.10.1-83481AF(working) and 0.11.1-2EADA21(not recording)

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.4
  port: 31096
  user: homeassistant
  password: <redacted>

detectors:
  cpu1:
    type: cpu
    num_threads: 1

ffmpeg:
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p 

database:
  path: /db/frigate.db

cameras:
  front_camera_frigate:
    ffmpeg:
     input_args:
      -avoid_negative_ts make_zero 
      -fflags +genpts+discardcorrupt+nobuffer
      -use_wallclock_as_timestamps 1
      -flags low_delay
      -strict experimental 
      -analyzeduration 1000M
      -probesize 1000M
     hwaccel_args:
       - -hwaccel
       - vaapi
       - -hwaccel_device
       - /dev/dri/renderD128
       - -hwaccel_output_format
       - yuv420p
     inputs:
        - path: rtsp://user:<redacted>@192.168.1.100:554//h265Preview_01_main 
          roles:
            - record
          hwaccel_args:
            -hwaccel vaapi
            -hwaccel_device /dev/dri/renderD128
            -hwaccel_output_format vaapi      
       
        - path: http://192.168.1.100/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=<redacted>
          roles:
            - detect
          hwaccel_args:
            -hwaccel vaapi
            -hwaccel_device /dev/dri/renderD128
            -hwaccel_output_format yuv420p

    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: True
      events:
        required_zones: 
          - front_of_gate
          - entire_yard
    rtmp:
      enabled: False
    
    best_image_timeout: 30

    zones:
      front_of_gate:
        coordinates: 580,110,599,202,436,168,458,75
        objects:
          - person
      entire_yard:
        coordinates: 640,142,640,360,28,360,63,49
        objects:
          - person
    mqtt:
      required_zones: 
          - front_of_gate
          - entire_yard

motion:
  mask:
    - 640,0,640,141,551,103,456,69,469,0
    - 474,41,493,0,304,0
    - 0,360,69,360,104,0,0,0
    - 0,30,310,30,314,0,0,0
      
record:
  enabled: True
  retain:
    days: 15
    mode: all
  events:
    pre_capture: 10
    post_capture: 15
    objects:
      - person
    required_zones: [] 
    retain:
      default: 15
      mode: active_objects
      objects:
        person: 30

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: 
    - front_of_gate
    - entire_yard

  retain:
    default: 15
    objects:
      person: 30


objects:
  track:
    - person
    - car
 
  mask: 640,48,640,134,550,93,463,59,469,0
  filters:
    person:
      mask: 640,48,640,134,550,93,463,59,469,0
    car:
      mask: 640,48,462,69,552,92,461,69,469,0


logger:
  default: debug
```

### Relevant log output

```shell
Nothing relevant, even with logging set to debug
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":88.68,"pid":215}},"front_camera_frigate":{"camera_fps":5.0,"capture_pid":223,"detection_fps":0.0,"pid":221,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":1072.8,"mount_type":"tmpfs","total":1073.7,"used":1.0},"/media/frigate/clips":{"free":266884.6,"mount_type":"ext4","total":491107.6,"used":199200.8},"/media/frigate/recordings":{"free":266884.6,"mount_type":"ext4","total":491107.6,"used":199200.8},"/tmp/cache":{"free":1073.7,"mount_type":"tmpfs","total":1073.7,"used":0.0}},"temperatures":{},"uptime":165,"version":"0.11.1-2eada21"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 812a

### Any other information that may be helpful

Install method is not Docker-CLI, it's Kubernetes
