### ISSUE TITLE
[Config Support]: Stationary object disappear

### ISSUE THREAD

**Issue by aqwserf** [blakeblackshear/frigate#4354]
### Describe the problem you are having

Hi!
I'm trying to use the stationary feature to track if there's a place available in the driveway. 
After reading the doc a lot, I think I'm close to it but for some reason, after a pretty good persistent detection, the detection disappear, and when something passes by, most of the time it doesn't detect anything anymore.
I then tried to apply a mask and a zone or changing `min_score` or `threshold` but without success so far.
I believe it's just a matter of tweaking but I can't figure it out.

Thanks!

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: addon_core_mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

live:
  height: 360

cameras:
  camera_6:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx@xxxx:554/ch0_0.h264
          roles:
            - record
            - rtmp
            - detect
    
    objects:
      track:
        - car

    detect:
      width: 1920
      height: 1088
      fps: 5
      max_disappeared: 60
      stationary:
        interval: 0
        threshold: 20
        #max_frames:
          # Optional: Default for all object types (default: not set, track forever)
          #default: 3000
          # Optional: Object specific values
          #objects:
            #car: 1000

    motion:
      mqtt_off_delay: 10
      mask:
        - 0,571,1580,674,1920,1088,1920,0,0,0,0,1088

    zones:  
      driveway:
        coordinates: 1920,1088,1920,692,0,571,0,884
        objects:
          - car
        filters:          
          car:
            min_score: 0.4
            threshold: 0.4

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      required_zones:
        - driveway

    birdseye:
      enabled: False
```

### Relevant log output

```shell
I dont believe it is, but heh...

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-11-10 12:01:16] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2022-11-10 12:01:16] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-11-10 12:01:16] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-11-10 12:01:16] peewee_migrate                 INFO    : There is nothing to migrate
[2022-11-10 12:01:16] detector.coral                 INFO    : Starting detection process: 216
[2022-11-10 12:01:16] frigate.app                    INFO    : Output process started: 218
[2022-11-10 12:01:16] ws4py                          INFO    : Using epoll
[2022-11-10 12:01:16] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-11-10 12:01:16] frigate.app                    INFO    : Camera processor started for camera_6: 225
[2022-11-10 12:01:19] frigate.edgetpu                INFO    : TPU found
[2022-11-10 12:01:16] frigate.app                    INFO    : Capture process started for camera_6: 227
[2022-11-10 12:01:20] ws4py                          INFO    : Using epoll
[2022-11-10 12:02:27] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57246]
[2022-11-10 12:02:29] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57246]
[2022-11-10 12:18:03] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:42476]
[2022-11-10 12:18:10] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:42476]
```

### Frigate stats

```json
{
  "camera_6": {
    "camera_fps": 5,
    "capture_pid": 227,
    "detection_fps": 0,
    "pid": 225,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "detection_fps": 0,
  "detectors": {
    "coral": {
      "detection_start": 0,
      "inference_speed": 15.56,
      "pid": 216
    }
  },
  "service": {
    "latest_version": "0.11.1",
    "storage": {
      "/dev/shm": {
        "free": 1987.3,
        "mount_type": "tmpfs",
        "total": 1991,
        "used": 3.7
      },
      "/media/frigate/clips": {
        "free": 130261.7,
        "mount_type": "ext4",
        "total": 174545.2,
        "used": 35342.6
      },
      "/media/frigate/recordings": {
        "free": 130261.7,
        "mount_type": "ext4",
        "total": 174545.2,
        "used": 35342.6
      },
      "/tmp/cache": {
        "free": 1991,
        "mount_type": "tmpfs",
        "total": 1991,
        "used": 0
      }
    },
    "temperatures": {},
    "uptime": 1014,
    "version": "0.11.1-2eada21"
  }
}
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Stationary detection ok:

![Screenshot from 2022-11-10 12-12-13](https://user-images.githubusercontent.com/29235861/201078057-714104fd-fe2d-4100-8731-c699264c9098.png)

And then not:
![Screenshot from 2022-11-10 12-12-44](https://user-images.githubusercontent.com/29235861/201078164-67640edc-f646-4c2e-a6e3-a189d483b7f7.png)

![Screenshot from 2022-11-10 12-12-53](https://user-images.githubusercontent.com/29235861/201078196-dade2120-2180-4b9e-b57d-35d5020a8f74.png)

For reference, here's the full picture:
![Screenshot from 2022-11-10 12-22-40](https://user-images.githubusercontent.com/29235861/201078486-549abbfc-27cb-47ae-a6ca-7abd59a735af.png)

the black mesh is the mosquito net (I try to tune in the worst possible scenario)
and yes the color is reddish, I have to open the camera to see what's going on :)

**Comment by NickM-27** [comment]
The blue box means that it is no longer seeing the object at all. The red is motion so it essentially is losing where the car is. 

Can you explain why you need it to be considered stationary?

**Comment by aqwserf** [comment]
Thanks @NickM-27 for your prompt response.
Yes, I've read about the color meaning (very helpful!).
As explained, I'm trying to detect if there's a parking space available (in this case, almost, in front of my car, but I can tweak with zone later on) so I can get a notification when it is.

**Comment by aqwserf** [comment]
> Right, I guess my point is it should still work without the car being stationary as long as it's detected all the time.

Hum, I'm not sure to understand. You mean I should try something like this?

```detect:
  stationary:
    interval: 10
    threshold: 50
```
Cause I've tried that and results are not very accurate either :/

> Stationary has a very specific meaning in Frigate and I'm not sure why it's required here.

Oh, so I would have misunderstood the concept of stationary on Frigate? If so, could you be more specific?

> Do you have an automation or something else that will be using this for the parking space detection?

Not yet. I would like the car presence detection to be reliable first before starting to create automation.

**Comment by NickM-27** [comment]
> Hum, I'm not sure to understand. You mean I should try something like this?
> 
> ```
>   stationary:
>     interval: 10
>     threshold: 50
> ```

I would recommend deleting that from the config and just letting it work off the defaults

> > Stationary has a very specific meaning in Frigate and I'm not sure why it's required here.
> 
> Oh, so I would have misunderstood the concept of stationary on Frigate? If so, could you be more specific?

I would recommend reading the docs about this: https://docs.frigate.video/configuration/stationary_objects/#why-does-it-matter-if-an-object-is-stationary

But basically, the object doesn't need to be stationary to still have its presence accurately tracked which seems like that's all you're needing.

**Comment by aqwserf** [comment]
> > Hum, I'm not sure to understand. You mean I should try something like this?
> > ```
> >   stationary:
> >     interval: 10
> >     threshold: 50
> > ```
> 
> I would recommend deleting that from the config and just letting it work off the defaults
> 
> > > Stationary has a very specific meaning in Frigate and I'm not sure why it's required here.
> > 
> > 
> > Oh, so I would have misunderstood the concept of stationary on Frigate? If so, could you be more specific?
> 
> I would recommend reading the docs about this: https://docs.frigate.video/configuration/stationary_objects/#why-does-it-matter-if-an-object-is-stationary
> 
> But basically, the object doesn't need to be stationary to still have its presence accurately tracked which seems like that's all you're needing.

Ok, got it, thanks.

So back to default and now, my car gets detected then not (well, same as before ^^):
![Screenshot from 2022-11-10 15-15-55](https://user-images.githubusercontent.com/29235861/201115848-005a9ef1-c85c-43de-b114-5253b427fdff.png)
then
![Screenshot from 2022-11-10 15-15-42](https://user-images.githubusercontent.com/29235861/201115930-c59dc94f-924b-4d0c-a877-1ad192def01f.png)
and then nothing.
But (depending on motion I believe?) my car gets detected again, then not. In a any case, I noticed that when a car goes by in the street, I do have a detection again (and then not).

Any advice which parameter I should tweak?

**Comment by NickM-27** [comment]
Can you please re-post your current config?

**Comment by aqwserf** [comment]
Sure thing:

```yaml
mqtt:
  host: addon_core_mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: xxxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

live:
  height: 360

cameras:
  camera_6:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx@xxxx:554/ch0_0.h264
          roles:
            - record
            - rtmp
            - detect
    
    objects:
      track:
        - car
      filters:
        car:
          min_score: 0.4 # modified this one for tests
          threshold: 0.4 # modified this one for tests

    detect:
      width: 1920
      height: 1088
      # fps: 5
      # max_disappeared: 25
      # stationary:
      #   interval: 0
      #   threshold: 50
        #max_frames:
          # Optional: Default for all object types (default: not set, track forever)
          #default: 3000
          # Optional: Object specific values
          #objects:
            #car: 1000

    motion:
      mqtt_off_delay: 10
      #mask:
      #  - 0,571,1580,674,1920,1088,1920,0,0,0,0,1088

    # zones:  
    #   driveway:
    #     coordinates: 1920,1088,1920,692,0,571,0,884
    #     objects:
    #       - car


    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      # required_zones:
      #   - driveway

    birdseye:
      enabled: False
```
