### ISSUE TITLE
[Bug?] Home Assistant loses clips with new Frigate container

### ISSUE THREAD

**Issue by drinfernoo** [blakeblackshear/frigate#436]
I'm not really sure if this *is* a bug, but certainly seems worth noting...

I made a fresh Frigate container, by stopping, removing, and composing it again:
```bash
docker stop frigate
docker rm frigate
docker-compose up -d
```
But for whatever reason, all of my previously recorded clips no longer show up inside Home Assistant's media browser.

New clips still get created just fine, but I appear to no longer have (or have access to) the old ones.

My `docker-compose.yaml`:
```yaml
version: '3'
services:
  frigate:
    container_name: frigate
    restart: always
    privileged: true
    image: blakeblackshear/frigate:0.8.0-beta2-aarch64
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /storage/docker/frigate/config:/config
      - /storage/docker/frigate/clips:/clips
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 100000000
    ports:
      - 5000:5000
      - 1935:1935
```

And my `config.yml`:
```yaml
mqtt:
  host: 192.168.1.253
cameras:
  front_porch:
    snapshots:
      height: 512
      draw_zones: True
    save_clips:
      enabled: True
      objects:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://front:front@192.168.1.202/live
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 5
  back_porch:
    snapshots:
      height: 512
      draw_zones: True
    save_clips:
      enabled: True
      objects:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://back:back@192.168.1.203/live
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 5
objects:
  track:
    - person
    - car
    - truck
    - cat
    - dog
    - bicycle
  filters:
    person:
      threshold: 0.75
logger:
  default: debug
  logs:
    frigate.mqtt: debug
    frigate.app: debug
```

My current directory structure looks like:
```bash
Errol:~ # ls -R docker
docker:
frigate

docker/frigate:
clips                docker-compose.yaml
config

docker/frigate/clips:
frigate.db

docker/frigate/config:
config.yml       config.yml.save
```

Do I need to be mounting the `.db` file specifically, or maybe specifying it in `config.yml`? I was under the impression that it wouldn't make a difference, as long as it was in the default location, and not on a network.
