### ISSUE TITLE
Crash in events.py

### ISSUE THREAD

**Issue by TheSleepySlee** [blakeblackshear/frigate#437]
**Describe the bug**
Just seeing a crash in the logs

**Version of frigate**
0.8 beta3

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
    ffmpeg.z5.detect: error
    ffmpeg.garage.detect: error
    ffmpeg.japonais.detect: error
    ffmpeg.garageptz.detect: error
    ffmpeg.z5.clips: error
    ffmpeg.garage.clips: error
    ffmpeg.japonais.clips: error
    ffmpeg.garageptz.clips: error

# Optional: detectors configuration
# USB Coral devices will be auto detected with CPU fallback
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3

# Optional: model configuration
model:
  # Required: height of the trained model
  height: 320
  # Required: width of the trained model
  width: 320

# Required: mqtt configuration
mqtt:
  # Required: host name
  host: 192.168.0.114
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
#  client_id: frigate
  # Optional: user
#  user: mqtt_user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}. 
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
#  password: password

# Optional: Global configuration for saving clips
save_clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300

  # OLD: Optional: Location to save event clips. (default: shown below)
#  clips_dir: /clips

  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # Notice: If you have mounted a tmpfs volume through docker, this value should not be set in your config
#  tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

# Optional: Global ffmpeg args
# Args may be provided as a string or an array
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
#  global_args: -hide_banner -loglevel fatal
#  global_args: -hide_banner -loglevel info
  global_args: -hide_banner -loglevel error

  # NOTE: See hardware acceleration docs for your specific device

# VAAPI
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
# QSV
#  hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128

  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args: 
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
#    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for clips streams (default: shown below)
#    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
#    rtmp: -c copy -f flv

# Optional: Global object filters for all cameras.
# NOTE: can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

# Optional: Global motion detection config. These may also be defined at the camera level.
# ADVANCED: Most users will not need to set these values in their config
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller
  # moving objects.
  contour_area: 100
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 1/6th of the original frame height)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 180

# Optional: Global detecttion settings. These may also be defined at the camera level.
# ADVANCED: Most users will not need to set these values in their config
detect:
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
  max_disappeared: 10

cameras:
  garageptz:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.121:8554/garageptz_light
          roles:
            - detect
#            - rtmp 
        - path: rtsp://192.168.0.121:8554/garageptz_full
          roles:
            - clips
    best_image_timeout: 45
    # Required: width of the frame for the input with the detect role
    width: 1280
    # Required: height of the frame for the input with the detect role
    height: 720
    mask:
#      - poly,0,0,1280,0,1280,90,0,112
#      - poly,19,127,33,718,2,718,1,2,769,6,763,88,274,121
      - poly,0,127,0,718,0,0,769,0,763,88,274,121
      - poly,0,0,20,0,20,719,0,719
    zones:
      ptzportail:
        coordinates: 63,142,271,133,285,266,81,276
    save_clips:
      enabled: True
      pre_capture: 10
      post_capture: 5
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15  
    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30
    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False
    snapshots:
      show_timestamp: True
      draw_zones: False
      draw_bounding_boxes: False
      crop_to_region: True
      # Optional: height to resize the snapshot to (default: shown below)
      # NOTE: 175px is optimized for thumbnails in the homeassistant media browser
      height: 250

  japonais:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.121:8554/japonais_light
          roles:
            - detect
 #           - rtmp
        - path: rtsp://192.168.0.121:8554/japonais_full
          roles:
            - clips
    # Required: width of the frame for the input with the detect role
    width: 1280
    # Required: height of the frame for the input with the detect role
    height: 720
    mask:
      - poly,1279,0,989,0,1279,107
#      - poly,0,0,595,0,590,138,0,165
#      - poly,193,408,941,418,1064,706,183,702

    best_image_timeout: 60

    zones:
#      pasjap:
#        coordinates: 193,408,941,418,1064,706,183,702
      portail:
        coordinates: 1220,101,1208,164,1033,131,1139,31
    save_clips:
      enabled: True
      pre_capture: 10
      post_capture: 10
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15  
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30
    # Optional: RTMP re-stream configuration
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False
    snapshots:
      show_timestamp: True
      draw_zones: False
      draw_bounding_boxes: False
      crop_to_region: True
      # Optional: height to resize the snapshot to (default: shown below)
      # NOTE: 175px is optimized for thumbnails in the homeassistant media browser
      height: 250
 
  z5:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.121:8554/z5_light
          roles:
            - detect
#            - rtmp
        - path: rtsp://192.168.0.121:8554/z5_full
          roles:
            - clips
    # Required: width of the frame for the input with the detect role
    width: 1280
    # Required: height of the frame for the input with the detect role
    height: 720
    mask:
      - poly,1,1,1279,3,1279,77,263,61,140,111,1,144
    best_image_timeout: 60
    zones:
      portailzoom:
        coordinates: 280,81,280,488,1150,527,1150,131
    save_clips:
      enabled: True
      pre_capture: 10
      post_capture: 10
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15  
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False

    snapshots:
      show_timestamp: True
      draw_zones: False
      draw_bounding_boxes: False
      crop_to_region: True
      # Optional: height to resize the snapshot to (default: shown below)
      # NOTE: 175px is optimized for thumbnails in the homeassistant media browser
      height: 250
  
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.121:8554/garage_light
          roles:
            - detect
#            - rtmp
        - path: rtsp://192.168.0.121:8554/garage_full
          roles:
            - clips
    # Required: width of the frame for the input with the detect role
    width: 704
    # Required: height of the frame for the input with the detect role
    height: 576
    zones:
      garageint:
        coordinates: 0,0,702,0,702,575,0,575
    save_clips:
      enabled: True
      pre_capture: 10
      post_capture: 10
#      objects:
#        - person
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15  
    # Optional: 24/7 recording configuration
    record:
      # Optional: Enable recording (default: global setting)
      enabled: False
      # Optional: Number of days to retain (default: global setting)
      retain_days: 30
    
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: False
    snapshots:
      show_timestamp: True
      draw_zones: False
      draw_bounding_boxes: False
      crop_to_region: True
      # Optional: height to resize the snapshot to (default: shown below)
      # NOTE: 175px is optimized for thumbnails in the homeassistant media browser
      height: 250

    objects:
      track:
        - person
```

**Logs**
```
2020-12-26T21:19:14.845976414Z frigate.edgetpu                INFO    : TPU found
2020-12-26T21:19:22.259085715Z Exception in thread event_processor:
2020-12-26T21:19:22.259116131Z Traceback (most recent call last):
2020-12-26T21:19:22.259195687Z   File "/opt/frigate/frigate/events.py", line 159, in run
2020-12-26T21:19:22.259313106Z     event_type, camera, event_data = self.event_queue.get(timeout=10)
2020-12-26T21:19:22.259320393Z   File "/usr/lib/python3.8/multiprocessing/queues.py", line 108, in get
2020-12-26T21:19:22.259739275Z     raise Empty
2020-12-26T21:19:22.259750367Z _queue.Empty
2020-12-26T21:19:22.259753780Z 
2020-12-26T21:19:22.259756213Z During handling of the above exception, another exception occurred:
2020-12-26T21:19:22.259758754Z 
2020-12-26T21:19:22.259761084Z Traceback (most recent call last):
2020-12-26T21:19:22.259763498Z   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2020-12-26T21:19:22.260671511Z     self.run()
2020-12-26T21:19:22.260685783Z   File "/opt/frigate/frigate/events.py", line 162, in run
2020-12-26T21:19:22.260796319Z     self.refresh_cache()
2020-12-26T21:19:22.260805244Z   File "/opt/frigate/frigate/events.py", line 56, in refresh_cache
2020-12-26T21:19:22.260885400Z     start_time = datetime.datetime.strptime(f.split('-')[-1].split('.')[0], '%Y%m%d%H%M%S')
2020-12-26T21:19:22.260953013Z   File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
2020-12-26T21:19:22.261540638Z     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
2020-12-26T21:19:22.261567818Z   File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
2020-12-26T21:19:22.261662195Z     raise ValueError("time data %r does not match format %r" %
2020-12-26T21:19:22.261705579Z ValueError: time data 'gnupg' does not match format '%Y%m%d%H%M%S'
```

**Frigate debug stats**
```
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":35}},"garage":{"camera_fps":6.1,"capture_pid":52,"detection_fps":0.0,"pid":42,"process_fps":6.1,"skipped_fps":0.0},"garageptz":{"camera_fps":5.1,"capture_pid":44,"detection_fps":0.0,"pid":38,"process_fps":5.1,"skipped_fps":0.0},"japonais":{"camera_fps":5.0,"capture_pid":45,"detection_fps":0.0,"pid":39,"process_fps":5.0,"skipped_fps":0.0},"z5":{"camera_fps":5.0,"capture_pid":48,"detection_fps":0.0,"pid":40,"process_fps":5.0,"skipped_fps":0.0}}
```

**Computer Hardware**
 - OS: debian
 - Virtualization: Proxmox
 - Coral Version: USB
 - Network Setup: Wired
