### ISSUE TITLE
[Custom detector model issue]: 

### ISSUE THREAD

**Issue by gokarbido** [blakeblackshear/frigate#4370]
### Describe the problem you are having

I have retrained ssdlite_mobiledet model  for 30,000 steps using 200 images custom datasets and deploy it on frigate cpu platform.  The retrained model could not be able to detect the desired target object, the event section is black blank. I have tried to lower the score and thresold level, but still there is no detection result.
![frig1](https://user-images.githubusercontent.com/45560315/201288808-62e1b264-0b27-4e68-a2e1-eb4c3cefafd4.png)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: broker.hivemq.com 
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
model:
  path: /custom_object.tflite
  labelmap_path: /labelmap.txt
  width: 320
  height: 320
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.**.***:554/live/0/main        
          roles:
            - detect
            - rtmp             
    rtmp:
      enabled: False
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots:
      enabled: True
    #motion:
      #mask:
        #- 0,461,3,0,1919,0,1919,843,1699,492,1344,458,1346,336,973,317,869,375,866,432
detect:
  width: 1280
  height: 720
  fps: 30
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 5
    max_frames:
      default: 3000
      objects:
        0: 1000
objects:
  track:
    - 0
  #filters:
    #0:
      #min_score: 0.5 # min score for object to initiate tracking (default: 0.5
      #threshold: 0.4
  mask: 0,0,1000,0,1000,200,0,200
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        0: 15
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
```

### Relevant log output

```shell
- Network frigate_default  Created                                                                                                                    0.7s
 - Container frigate        Created                                                                                                                    0.0s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-11-11 07:19:50] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-11-11 07:19:50] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-11-11 07:19:50] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-11-11 07:19:50] detector.cpu1                  INFO    : Starting detection process: 240
frigate  | [2022-11-11 07:19:50] detector.cpu2                  INFO    : Starting detection process: 242
frigate  | [2022-11-11 07:19:50] frigate.app                    INFO    : Output process started: 243
frigate  | [2022-11-11 07:19:50] ws4py                          INFO    : Using epoll
frigate  | [2022-11-11 07:19:50] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-11-11 07:19:50] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-11-11 07:19:50] frigate.app                    INFO    : Camera processor started for back: 248
frigate  | [2022-11-11 07:19:50] frigate.app                    INFO    : Capture process started for back: 250
frigate  | [2022-11-11 07:19:50] ws4py                          INFO    : Using epoll
frigate  | [2022-11-11 07:19:51] frigate.mqtt                   INFO    : Turning on snapshots for back via mqtt
frigate  | [2022-11-11 07:19:52] frigate.mqtt                   INFO    : Turning off detection for back via mqtt
frigate  | [2022-11-11 07:19:53] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:56966]
frigate  | [2022-11-11 07:20:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:56966]
frigate  | [2022-11-11 07:20:40] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:36004]
frigate  | [2022-11-11 07:20:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57008]
frigate  | [2022-11-11 07:20:48] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57008]
frigate  | [2022-11-11 07:20:50] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57022]
frigate  | [2022-11-11 07:20:50] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2022-11/01/06/back/56.21.mp4
frigate  | [2022-11-11 07:22:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57022]
frigate  | [2022-11-11 07:27:42] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57116]
```

### FFprobe output from your camera

```shell
camera is working
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

hikvision
