### ISSUE TITLE
[Config Support]: not recognize objects or people

### ISSUE THREAD

**Issue by migue789** [blakeblackshear/frigate#4374]
### Describe the problem you are having

greetings sorry to bother but I have no experience in frigate I can see the camera by rstp the video looks good

but it does not recognize objects or people, things, or animals, no box appears indicating what objects it is, can you help me? grams

### Version

1

### Frigate config file

```yaml
mqtt:
  host: ipmqttmosquitto
cameras:
  comedor:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -timeout 5000000 -use_wallclock_as_timestamps 1 -analyzeduration 10000000 -probesize 10000000
      inputs:
        - path: rtsp://user:pass@ipcamera:554/onvif1
          roles:
            - detect
            
    detect:
      width: 1280
      height: 720
      fps: 5          
detectors:
  cpu1:
    type: cpu
```

### Relevant log output

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Recommend reading the docs: https://docs.frigate.video/guides/getting_started

There are a handful of things to know:
1. Frigate only tracks `person` by default, any other objects you want tracked will need to be added as 
```yaml
objects:
  track:
    - person
    - car
    - etc
```
2. How do you know it isn't tracking people? It is important to know that no events will be created unless snapshots or recordings are enabled and they are both disabled by default.
