### ISSUE TITLE
[Config Support]: min_ratio object filter

### ISSUE THREAD

**Issue by jonrasp** [blakeblackshear/frigate#4376]
### Describe the problem you are having

I'm tuning my filters to reduce false positives, want to enable min&max ratio for my person detector. However this gives me a config file error. I've followed the example in the documentation, am I missing something? I expect this to be valid:

```

objects:
  track:
    - person
    - cat
    - dog
    - bird
    - bicycle
    - umbrella
#    - car
    - motorcycle

  filters:
    person:
      min_ratio: 0.5
      max_ratio: 2
```

however I see this error:

```
2 validation errors for FrigateConfig
objects -> filters -> person -> max_ratio
  extra fields not permitted (type=value_error.extra)
objects -> filters -> person -> min_ratio
  extra fields not permitted (type=value_error.extra)

```

### Version

0.10.0

### Frigate config file

```yaml
# works with 0.10.1
mqtt:
  host: 192.168.0.60
  topic_prefix: frigate
  user: user
  password: mqttfingerprint

detectors:
#  cpu1:
#    type: cpu
  coral:
    type: edgetpu
    device: usb

ffmpeg:
#  input_args: -stimeout
#use this for v0.11?
#  hwaccel_args: -c:v h264_v412m2m
#or this
#  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
#  input_args -stimeout 10
# use the next three lines for v0.10
  hwaccel_args:
    - -c:v
    - h264_mmal


objects:
  track:
    - person
    - cat
    - dog
    - bird
    - bicycle
    - umbrella
#    - car
    - motorcycle
#111122
  filters:
    person:
      min_ratio: 0.5
      max_ratio: 2

cameras:
  front_cam:
    ffmpeg:
      inputs:
        - path: rtsp://fcamalt:password@ipaddress:554/
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 30
    record:
      enabled: true

      retain:
        days: 0

      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 4
          objects:
            person: 14
#            car: 1

    snapshots:
      enabled: true
      retain:
        default: 4
        objects:
          person: 14
#          car: 1

    motion:
#221024 default->25
      threshold: 25
      mask:
        - 1920,0,1435,0,0,0,0,182,69,158,164,125,501,87,842,47,1422,23,1445,89,1672,87,1920,158
        - 1920,1080,1223,1080,1229,929,1235,756,1285,611,1382,423,1542,296,1725,251,1920,315
        - 0,1080,0,37,191,41,185,205,203,372,234,599,1009,1080

    zones:
      Jgarden:
        coordinates: 1383,1080,1425,443,1282,374,289,686,526,1080
        objects:
          - person
          - cat
          - bird
          - dog
#      Sgarden:
#        coordinates: 204,279,762,185,1172,254,1169,347,253,612
#        objects:
#          - person
#          - cat
#          - bird
#          - dog
      path:
        coordinates: 1251,362,1213,225,707,201,175,331,254,640
        objects:
          - person
          - bicycle
          - umbrella
          - backpack
        filters:
          person:
            min_area: 20000
      pbottom:
# reenable if breaking path into path/pathtpop
        coordinates: 924,435,260,664,193,325,396,268,735,199
#        coordinates: 1247,337,260,664,203,390,798,262,1015,282
        objects:
          - person
          - bicycle
          - umbrella
          - backpack
        filters:
          person:
            min_area: 25000
      ptop:
        coordinates: 1208,220,1191,325,902,433,768,182
        objects:
          - person
#reenabled 091122
        filters:
          person:
            min_area: 25000
#            max_area: 100000
#            threshold: 0.3

      street:
        coordinates: 845,43,496,83,498,201,985,197,1117,207,1135,118,1357,132,1470,191,1920,341,1920,143,1605,75
        objects:
          - person
          - car
          - motorcycle
          - bicycle
          - umbrella
#added 111122 - ratio of width/height
#        filters:
#          person:
#            min_ratio: 0.5
```

### Relevant log output

```shell
2 validation errors for FrigateConfig
objects -> filters -> person -> max_ratio
  extra fields not permitted (type=value_error.extra)
objects -> filters -> person -> min_ratio
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 511, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
objects -> filters -> person -> max_ratio
  extra fields not permitted (type=value_error.extra)
objects -> filters -> person -> min_ratio
  extra fields not permitted (type=value_error.extra)
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
