### ISSUE TITLE
[EdgeTPU Support]: Issue with event clip playback "Playback cannot continue. No available working or supported playlists."

### ISSUE THREAD

**Issue by crazyfrog-github** [blakeblackshear/frigate#4380]
### Describe the problem you are having

When using Frigate Proxy to access Frigate Docker in LXC and playback a clip I get the following message and spinning circle and video is not played back (h265 or h264). This happens on any browser or device. If I don't use Frigate Proxy and another method the video clip plays back fine.

![image](https://user-images.githubusercontent.com/33864965/201481347-b8144166-0e95-4657-a03d-b1844f6a602e.png)

![image](https://user-images.githubusercontent.com/33864965/201481370-4ccdcf43-7422-4b9f-bcd6-dc91b74197d6.png)

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.106
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate_mqtt
  password: <insert>
  stats_interval: 60
  
detectors:
  coral:
    type: edgetpu
    device: usb
#   cpu1:
#     type: cpu
    
cameras:
  Cam1:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://admin:<insert>@192.168.0.4:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://admin:<insert>@192.168.0.4:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640    
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
        - apple
        - keyboard
      filters:
        apple:
          threshold: 0.3
        person:
          threshold: 0.7
        keyboard:
          threshold: 0.4
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 3

    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15
        
rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/frigate/config.yml:/config/config.yml
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "<insert>"
```

### Relevant log output

```shell
Do know which log this would be found in?
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
