### ISSUE TITLE
[Config Support]: config esp32cam frigatee high

### ISSUE THREAD

**Issue by migue789** [blakeblackshear/frigate#4381]
### Describe the problem you are having

I am testing an esp32cam in frigate I can already see the camera but it has a high processor consumption, is there any way that the processor does not have so high? Thank you

### Version

1

### Frigate config file

```yaml
mqtt:
  host: ipmqtt

cameras:
  eesp32cam:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://ipcamera:port
          roles:
            - detect
            - rtmp               
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      retain:
        default: 2
detectors:
  cpu1:
    type: cpu
```

### Relevant log output

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

### Any other information that may be helpful

.
