### ISSUE TITLE
[Support]: Viewing frigate event clips threw Android HomeAssistant has strange CPU spikes

### ISSUE THREAD

**Issue by spacebares** [blakeblackshear/frigate#4388]
### Describe the problem you are having

Viewing a clip threw _ANDROID HomeAssistant -> Frigate Proxy -> Frigate Events Page_ causes a spike in cpu from process "python3". Once "python3" finishes its work, the clip loads and you may seek to any point in the clip without further cpu usage. Longer/Larger clips like from the Recordings page will trigger this process again.

Viewing the same event threw _ANDROID Chrome -> FrigateIP:5000 -> Frigate Events Page_ loads the clip faster and has no cpu spikes while the clip loads.

Desktop HomeAssistant threw chrome has no cpu spikes.

Please note, these cpu spikes are on the machine that has both HomeAssistant and Frigate in docker.

The clip can be of any type or any resolution. Larger clips from 4K cameras take longer to load. But even simple H264 clips from small 640x360 camera substreams use 25% cpu to load for a fraction of a second. 

Its like "python3" is preparing the clip for HomeAssistant Android viewing ???? Its very strange i don't understand it at all, because if you view frigate threw android chrome, there is no issue. Something with the app is all screwed.

In home assistant you dont even need to view frigate. Just looking at the clips threw Home Assistant media browser is enough to trigger python3 cpu spike.

### Version

0.11.1-86268B9 & 0.12.0-9B5C6BE

### Frigate config file

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.1.158
  port: 1883

rtmp:
  enabled: False

objects:
  track:
    - person

snapshots:
  enabled: True
  crop: True
  retain:
    default: 365

birdseye:
  enabled: True
  mode: continuous
  width: 1280
  height: 720

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac 

cameras:
  front:   
    ffmpeg:
      inputs:
        - path: rtsp://192.168.10.11:8554/front/subStream
          roles:
            - detect
            - rtmp
        - path: rtsp://192.168.10.20:8554/front/subStream
#        - path: rtsp://192.168.10.20:8554/front/mainStream #to generate 4K H265 clips 
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 8
    mqtt:
      quality: 90
```

### Relevant log output

```shell
nothing related in logs
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.2-0ubuntu1~20.04.sav1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version='0ubuntu1~20.04.sav1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-lcms2 --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-sndio --enable-pocketsphinx --enable-librsvg --enable-libdav1d --enable-libjxl --enable-librist --enable-libvmaf --enable-libzimg --enable-crystalhd --enable-libmfx --enable-libsvtav1 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 21 with DTS 134499, packet 22 with DTS 147907
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 23 with DTS 147908, packet 24 with DTS 165596
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 26 with DTS 165599, packet 27 with DTS 184380
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 28 with DTS 184382, packet 29 with DTS 194017
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 31 with DTS 194020, packet 32 with DTS 205652
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 33 with DTS 205653, packet 34 with DTS 224514
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 36 with DTS 224517, packet 37 with DTS 235912
[rtsp @ 0x5630867b1300] DTS discontinuity in stream 0: packet 38 with DTS 235914, packet 39 with DTS 253629
Input #0, rtsp, from 'rtsp://192.168.1.20:8554/front/subStream':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.020625, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x360, 47 tbr, 90k tbn
  Stream #0:1: Audio: pcm_s16be, 16000 Hz, mono, s16, 256 kb/s
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.0,"pid":212}},"front":{"camera_fps":8.1,"capture_pid":222,"detection_fps":0.0,"pid":220,"process_fps":8.1,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":837.9,"mount_type":"tmpfs","total":838.9,"used":1.0},"/media/frigate/clips":{"free":60434.5,"mount_type":"ext4","total":117547.6,"used":51094.7},"/media/frigate/recordings":{"free":60434.5,"mount_type":"ext4","total":117547.6,"used":51094.7},"/tmp/cache":{"free":999.3,"mount_type":"tmpfs","total":1000.0,"used":0.7}},"temperatures":{},"uptime":814,"version":"0.11.1-86268b9"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

RLC822A

### Any other information that may be helpful

I checked cpu usage using `top -i` Then press D and type in 0.5.
