### ISSUE TITLE
[Support]: Stuck in restart loop

### ISSUE THREAD

**Issue by raintonr** [blakeblackshear/frigate#4414]
### Describe the problem you are having

Stuck in restart loop see log.

### Version

0.11.1-2eada21

### Frigate config file

```yaml
logger:
  default: info

mqtt:
  host: redacted

detect:
  width: 704
  height: 576
  fps: 3
  max_disappeared: 30

detectors:
  cpu1:
    type: cpu
    num_threads: 2

objects:
  track:
    - car
    - person

ffmpeg:
  hwaccel_args:
    -hwaccel vaapi
    -hwaccel_device /dev/dri/renderD128
    -hwaccel_output_format yuv420p

snapshots:
  enabled: True

record:
  enabled: True

live:
  height: 576

birdseye:
  enabled: False
  width: 704
  height: 576
  mode: continuous

cameras:
  porch_intercom:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://redacted@redacted:554/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://redacted@redacted:554/Streaming/Channels/1
          roles:
            - record
    detect:
      enabled: true
      width: 704
      height: 576
    mqtt:
      enabled: false
    objects:
      mask: 35,499,131,488,136,350,76,345,42,372
      filters:
        car:
          mask:
            - 220,351,337,451,92,510,64,354
    motion:
      mask:
        - 638,462,473,462,473,443,638,443
```

### Relevant log output

```shell
# docker-compose up
[+] Running 1/1
 ⠿ Container frigate  Created                                                                                                                                      1.4s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-11-16 19:29:40] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-11-16 19:29:40] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-11-16 19:29:40] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-11-16 19:29:40] detector.cpu1                  INFO    : Starting detection process: 215
frigate  | [2022-11-16 19:29:40] frigate.app                    INFO    : Output process started: 217
frigate  | [2022-11-16 19:29:40] ws4py                          INFO    : Using epoll
frigate  | [2022-11-16 19:29:40] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-11-16 19:29:40] frigate.app                    INFO    : Camera processor started for porch_intercom: 221
frigate  | [2022-11-16 19:29:40] frigate.app                    INFO    : Capture process started for porch_intercom: 222
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [2022-11-16 19:29:41] ws4py                          INFO    : Using epoll
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 0
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-11-16 19:29:49] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-11-16 19:29:49] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-11-16 19:29:49] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-11-16 19:29:49] detector.cpu1                  INFO    : Starting detection process: 217
frigate  | [2022-11-16 19:29:49] frigate.app                    INFO    : Output process started: 219
frigate  | [2022-11-16 19:29:49] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-11-16 19:29:49] frigate.app                    INFO    : Camera processor started for porch_intercom: 223
frigate  | [2022-11-16 19:29:49] ws4py                          INFO    : Using epoll
frigate  | [2022-11-16 19:29:49] frigate.app                    INFO    : Capture process started for porch_intercom: 225
frigate  | [2022-11-16 19:29:49] ws4py                          INFO    : Using epoll
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 0
```

### FFprobe output from your camera

```shell
ffprobe version 5.0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-librtmp --enable-librubberband --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[rtsp @ 0x55bc1ac34e40] Missing PPS in sprop-parameter-sets, ignoring
Input #0, rtsp, from 'rtsp://redacted@redacted:554/Streaming/Channels/2':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 704x576, 25 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-KD8003-IME1

### Any other information that may be helpful

Was working fine for ages but noticed MQTT not being updated and upon restart noticed this loop occuring.
