### ISSUE TITLE
[Config Support]: Configuration question

### ISSUE THREAD

**Issue by aqwserf** [blakeblackshear/frigate#4417]
### Describe the problem you are having

Hey!

After some tweaking related to me issue #4354, I found that it's possible to add the same parameters in many places.
Especially, what is the difference between placing like this:

```yaml
cameras:
  camera_1:
  ....
    objects:
      track:
        - car
        - person
      filters:
        car:
          min_score: 0.5
          threshold: 0.5
          mask:
            - 0,0,1920,0,1920,703,306,540,146,719,0,707
```

instead of this:

```yaml
cameras:
  camera_1:
  ....
    zones:
      parking_space:
  ....
        objects:
          - car
        filters:
          car:
            min_score: 0.5
            threshold: 0.5
            mask:
              - 0,0,1920,0,1920,703,306,540,146,719,0,707
```
According to the doc, it's a zone level object filters but I'm not sure I understand. 
Does it mean that in the first case the whole image is scanned even with the mask and in the second only the part of the zone is scanned?
Same for the threshold.

Thanks!

### Version

0.11.1-2eada21

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
They're slightly different so I'll address both separately:

### objects

The objects you define in 

```yaml
objects:
  track:
    - this
    - list
```

are what are tracked by the camera.

Zones are meant to limit the events to objects that are of interest. You can list tracked objects for a zone to limit which objects are considered apart of that zone. For example you may want to track `person`, `dog`, `cat` in your yard and then track `car` in your driveway. Or you may not want to know about people in the street but do want to know about vehicles in the street.

**PLEASE NOTE:** Any objects that are not in `objects -> track` will not be tracked. If you put `car` in the zone level tracking and it is not in the `object -> track` list then cars will not be tracked anywhere. In 0.12 this will result in a config error.

### filters

You can set a global filter which will apply to all objects that are detected, but you can also apply it to just a zone. A practical example of this that I used to use is I wanted to be notified of `car` in my driveway. I also wanted to know if the UPS / Fedex truck drove by, but of course if I added a `min_area` filter globally then the normal car in my driveway would be ignored. So I simply have car tracked everywhere but then create a street zone with a `min_area` of 40000 so the car is only considered apart of the street zone if it is that big.
