### ISSUE TITLE
[Config Support]: HA person sensors never reset

### ISSUE THREAD

**Issue by ericnotthered** [blakeblackshear/frigate#4419]
### Describe the problem you are having

I have two Reolink cameras that are generally working well.   Detection and recording works as expected in Frigate.  I use the Frigate Lovelace card and it behaves properly

My issue is that the "Person" Sensor for each of the cameras never resets.  It stays "active", with the most recent snapshot.  

![image](https://user-images.githubusercontent.com/22112690/202326413-ab85ba8a-4e68-48a1-9dd0-4723068654b4.png)

![image](https://user-images.githubusercontent.com/22112690/202327200-c8c5a2e7-98f4-4a4b-87f1-8a50224de596.png)

Motion sensors go to the "Detected" state and return to "Clear" after a short period.

### Version

Home Assistant:  2022.11.2, Frigate:  0.11.1, Frigate HACS:  3.0.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.115
  user: mqtt
  password: XXXXXX

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: True

#Global Object Settings
objects:
  track:
    - person
  
cameras:
  kitchen: 
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@192.168.1.149:554/h264Preview_01_main
          roles:
            - record
            - detect
        - path: rtsp://admin:XXXXXX@192.168.1.149:554/h264Preview_01_sub
          roles:
            - rtmp
    detect:
      width: 2560
      height: 1920
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects 

      
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXX@192.168.1.158:554/h264Preview_01_main
          roles:
            - record
            - detect
        - path: rtsp://admin:XXXXXX@192.168.1.158:554/h264Preview_01_sub
          roles:
            - rtmp
    detect:
      width: 2560
      height: 1920
    snapshots:
      enabled: True           
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
```

### Relevant log output

```shell
I'm not sure if this is related, but this warning comes up in the HA log one and two minutes respectively after events on my two cameras.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 4:59:30 PM (1 occurrences)
Last logged: 4:59:30 PM

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")
```

### Frigate stats

```json
Not sure how to obtain this.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
