### ISSUE TITLE
[Config Support]: Documentation may be incorrect about NVIDIA HW accel

### ISSUE THREAD

**Issue by ksheyman** [blakeblackshear/frigate#4427]
### Describe the problem you are having

Hello, I tried using the NVIDIA HW acceleration instructions and they did not work. It says they were taken from the Jellyfin guide.

```
services:
  frigate:
    ...
    image: blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
```
The above does not enable hardware acceleration using the NVIDIA gpu. I do not know why, it just throws errors and says ffmpeg is not running. I searched around and found https://docs.docker.com/compose/gpu-support/ which says to do this:

```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
I don't know enough to tell you why, but once I put the 'count: 1' it worked like a charm.  Maybe it is something in my particular hardware configuration causing it, I'm not sure... I just thought it might be worth adding the solution to the documentation, as I wasted a lot of time as a novice trying to get it to work using the example in the instructions before I found the correct way. Thanks

### Version

0.11.1-2eada21

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by davefx** [comment]
I'm experiencing exactly the same problem. 
Pulling the thread I think that the problem could be caused by ffmpeg in the last version, not including support for any CUVID decoder (`ffmpeg -decoders| grep cuvid` returns an empty list)

**Comment by NickM-27** [comment]
Nvidia is working fine here with the latest versions. @davefx what does your compose or docker CLI look like?

**Comment by davefx** [comment]
This is my docker-compose.yml:

```
version: '3.3'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yml:/config/config.yml:ro
      - ./media/:/media/frigate
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              capabilities: [gpu]
#    environment:
#      FRIGATE_RTSP_PASSWORD: password

    environment:
      #- FRIGATE_RTSP_PASSWORD='XXXX
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - NVIDIA_VISIBLE_DEVICES=all

```
