### ISSUE TITLE
[Support]: HomeAssistant motion sensor keeps triggering

### ISSUE THREAD

**Issue by federicotravaini** [blakeblackshear/frigate#4430]
### Describe the problem you are having

Every sensor motion keeps triggering every few seconds, resulting in a totale mess

![photo_2022-11-18_11-17-03](https://user-images.githubusercontent.com/2836634/202678617-13d46d03-e71b-4dbd-ad32-abaf7c173f0c.jpg)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.91.92
  user: xxx
  password: xxx

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: http://192.168.91.100/flv?port=1935&app=bcs&stream=channel3_ext.bcs&user=xxx&password=xxx
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car
    motion:
      mask:
        - 0,512,387,512,385,464,0,464
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
 
  ingresso:
    ffmpeg:
      inputs:
        - path: http://192.168.91.100/flv?port=1935&app=bcs&stream=channel5_ext.bcs&user=xxx&password=xxx
          roles:
            - detect
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    motion:
      mask:
        - 0,512,387,512,385,464,0,464
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    rtmp:
      # Required: Enable the live stream (default: True)
      enabled: True
detectors:
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    # device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    # num_threads: 3
  #cpu1:
  #  type: cpu
  #cpu2:
  #  type: cpu
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink 410
