### ISSUE TITLE
[Support]: How do i see DoubleTake labels in frigate ?

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#4453]
### Describe the problem you are having

I have it configured as per the Doubletake website, but not seeing anything (i asked for help there as well, but hoping someone might know here how it should work, on the frigate side).

```yaml
frigate:


  url: http://192.1.1.41:5000 # frigate host
  update_sub_labels: false # frigate 0.11+ option to include names in frigate events
  
# ignore detected areas so small that face recognition would be difficult
# quadrupling the min_area of the detector is a good start
# does not apply to MQTT events
# min_area: 0
  
  # object labels that are allowed for facial recognition
  labels:
    - person
  
  events:
  
    camera:
      attempts:
        latest: 16 # number of "latest" frigate snapshots to try to find face in
        snapshot: 16 # number of event frigate snapshots to try to find face in
        mqtt: false # whether or not to use mqtt snapshots
      image:
        height: 640 # set this to the detect height of your frigate camera
```

### Version

na

### Frigate config file

```yaml
frigate:


  url: http://192.168.50.41:5000 # frigate host
  update_sub_labels: false # frigate 0.11+ option to include names in frigate events
  
# ignore detected areas so small that face recognition would be difficult
# quadrupling the min_area of the detector is a good start
# does not apply to MQTT events
# min_area: 0
  
  # object labels that are allowed for facial recognition
  labels:
    - person
  
  events:
  
    camera:
      attempts:
        latest: 16 # number of "latest" frigate snapshots to try to find face in
        snapshot: 16 # number of event frigate snapshots to try to find face in
        mqtt: false # whether or not to use mqtt snapshots
      image:
        height: 640 # set this to the detect height of your frigate camera
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

na
