### ISSUE TITLE
[Support]: ffmpeg retry delay

### ISSUE THREAD

**Issue by brickman7713** [blakeblackshear/frigate#4454]
### Describe the problem you are having

I am running Frigate in Docker with 5 cameras that stream consistently, but I would also like to record video from my Ring doorbell when it sees motion. I have set up RTSP streaming from the doorbell using the [Ring-MQTT with Video Streaming](https://github.com/tsightler/ring-mqtt-ha-addon) addon in HomeAssistant, and I have it streaming to a server running an RTSP proxy. I would stream the video directly from the doorbell to Frigate, but the doorbell battery would die within a couple of hours, so to save battery I have HomeAssistant start the RTSP proxy when Ring.com tells HA that it sees motion. Everything is working, but there is a 10-15 second delay from the time the RTSP proxy starts to the time the Frigate picks up the stream. So my question... is there any way to decrease the retry time that Frigate will try connecting to a camera? I assume this will lead to more server resources being used by Frigate, but my server is only using about 50% ram and CPU currently so I don't think it will affect me. I included the startup logs from Docker, and 4 cycles of Frigate trying to connect to the doorbell (which wasn't streaming at the time). Also included my config general and Doorbell camera config.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
#General Config
logger:
  default: error

mqtt:
  host: redacted 
  user: redacted 
  password: "redacted"

objects:
  track:
    - person
    - cat

ffmpeg:
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: "solid"

#Camera configs
cameras:

#Doorbell
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://100.122.121.18:8555/proxied
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 10
    record:
      enabled: True
      expire_interval: 60
      retain:
        days: 2
        mode: all
    ui:
      order: 50
```

### Relevant log output

```shell
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-11-20 19:41:54] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-11-20 19:41:54] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-11-20 19:41:54] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-11-20 19:41:55] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:41:55] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:42:15] watchdog.Doorbell              ERROR   : Ffmpeg process crashed unexpectedly for Doorbell.
frigate  | [2022-11-20 19:42:15] watchdog.Doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:42:15] ffmpeg.Doorbell.detect         ERROR   : [tcp @ 0x55e336d650c0] Connection to tcp://100.122.121.18:8555?timeout=5000000 failed: Connection refused
frigate  | [2022-11-20 19:42:15] ffmpeg.Doorbell.detect         ERROR   : rtsp://100.122.121.18:8555/proxied: Connection refused
frigate  | [2022-11-20 19:42:15] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:42:15] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:42:25] watchdog.Doorbell              ERROR   : Ffmpeg process crashed unexpectedly for Doorbell.
frigate  | [2022-11-20 19:42:25] watchdog.Doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:42:25] ffmpeg.Doorbell.detect         ERROR   : [tcp @ 0x5559ace650c0] Connection to tcp://100.122.121.18:8555?timeout=5000000 failed: Connection refused
frigate  | [2022-11-20 19:42:25] ffmpeg.Doorbell.detect         ERROR   : rtsp://100.122.121.18:8555/proxied: Connection refused
frigate  | [2022-11-20 19:42:25] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:42:25] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:42:35] watchdog.Doorbell              ERROR   : Ffmpeg process crashed unexpectedly for Doorbell.
frigate  | [2022-11-20 19:42:35] watchdog.Doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:42:35] ffmpeg.Doorbell.detect         ERROR   : [tcp @ 0x5632e04250c0] Connection to tcp://100.122.121.18:8555?timeout=5000000 failed: Connection refused
frigate  | [2022-11-20 19:42:35] ffmpeg.Doorbell.detect         ERROR   : rtsp://100.122.121.18:8555/proxied: Connection refused
frigate  | [2022-11-20 19:42:35] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:42:35] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:42:45] watchdog.Doorbell              ERROR   : Ffmpeg process crashed unexpectedly for Doorbell.
frigate  | [2022-11-20 19:42:45] watchdog.Doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:42:45] ffmpeg.Doorbell.detect         ERROR   : [tcp @ 0x5628236290c0] Connection to tcp://100.122.121.18:8555?timeout=5000000 failed: Connection refused
frigate  | [2022-11-20 19:42:45] ffmpeg.Doorbell.detect         ERROR   : rtsp://100.122.121.18:8555/proxied: Connection refused
frigate  | [2022-11-20 19:42:45] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:42:45] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:42:55] watchdog.Doorbell              ERROR   : Ffmpeg process crashed unexpectedly for Doorbell.
frigate  | [2022-11-20 19:42:55] watchdog.Doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:42:55] ffmpeg.Doorbell.detect         ERROR   : [tcp @ 0x557bb46520c0] Connection to tcp://100.122.121.18:8555?timeout=5000000 failed: Connection refused
frigate  | [2022-11-20 19:42:55] ffmpeg.Doorbell.detect         ERROR   : rtsp://100.122.121.18:8555/proxied: Connection refused
frigate  | [2022-11-20 19:42:55] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:42:55] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-11-20 19:43:05] watchdog.Doorbell              ERROR   : Ffmpeg process crashed unexpectedly for Doorbell.
frigate  | [2022-11-20 19:43:05] watchdog.Doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-11-20 19:43:05] ffmpeg.Doorbell.detect         ERROR   : [tcp @ 0x55dcaa8c40c0] Connection to tcp://100.122.121.18:8555?timeout=5000000 failed: Connection refused
frigate  | [2022-11-20 19:43:05] ffmpeg.Doorbell.detect         ERROR   : rtsp://100.122.121.18:8555/proxied: Connection refused
frigate  | [2022-11-20 19:43:05] frigate.video                  ERROR   : Doorbell: Unable to read frames from ffmpeg process.
frigate  | [2022-11-20 19:43:05] frigate.video                  ERROR   : Doorbell: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
Don't think this is needed, but I can include it if told otherwise.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Ring Doorbell Gen 2
