### ISSUE TITLE
[EdgeTPU Support]: USB Coral not recognized and not changing vendor id

### ISSUE THREAD

**Issue by dollarusername2** [blakeblackshear/frigate#4463]
### Describe the problem you are having

Hi guys,

I am currently experiencing trouble with setup up a edge TPU. As I started from scratch and just received the HW accelerator, I am not quite sure where to start. I hope you can point me in the right direction!

I first though I ran into https://github.com/blakeblackshear/frigate/issues/3890 , however this seems to apply only to Home Assistant installations (I run HA on a complete different machine).
Then I guess I ran into the https://github.com/google-coral/edgetpu/issues/536 issue. However I tried multiple times (a dozen?) to restart, use a different port, reboot, etc. And the lsusb output always shows the Generic Vendor output, never the Google Inc. one. As the setup currently is with python 3.10, I cannot get the Google Example to work. However according to the frigate docs, I would not need any drivers. Anyways, I installed libedgetpu1-std/coral-edgetpu-stable,now 16.0 amd64 anyways...

Any ideas? Thanks!

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.100
  user: mqtt
  password: pw

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  vorgarten:
    ffmpeg:
      #  hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: https://192.168.2.230/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=mira&password=pw
          roles:
            - record
            - rtmp
        - path: https://192.168.2.230/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=mira&password=pw
          roles:
            - detect
              #    detect:
              #      width: 896
              #      height: 672
              #      fps: 7
              #    clips:
              #      enabled: true
              #      retain:
              #        default: 1
    motion:
      mask:
        - 914,542,844,424,904,418,940,409,957,408,991,397,1049,483
        - 1140,383,1185,445,1280,521,1241,609,1220,637,1216,720,1046,720,883,720,811,477,871,439

  garten:
    ffmpeg:
      #  hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: https://192.168.2.231/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=mira&password=pw
          roles:
            - record
            - rtmp
        - path: https://192.168.2.231/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=mira&password=pw
          roles:
            - detect
              #    detect:
              #      width: 896
              #      height: 672
              #      fps: 7
              #    clips:
              #      enabled: true
              #      retain:
              #        default: 1

objects:
  track:
    - person
    - dog
    - cat
    - cell phone
      #- car
      #- bicycle
    - bird
  # filters:
    #person:
      #mask:
      #- 914,542,844,424,904,418,940,409,957,408,991,397,1049,483
      #- 1140,383,1185,445,1280,521,1241,609,1220,637,1216,720,1046,720,883,720,811,477,871,439

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 90
      mode: motion

snapshots:
  enabled: True
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/mira/frigate/config.yml:/config/config.yml:ro
      - /media/hdd/frigate-media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "pw"
```

### Relevant log output

```shell
$ docker compose up 
[+] Running 2/0
 ⠿ Network frigate_default  Created                                                                                                                                                           0.0s
 ⠿ Container frigate        Created                                                                                                                                                           0.0s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-11-21 14:28:41] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-11-21 14:28:41] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-11-21 14:28:41] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-11-21 14:28:41] detector.coral                 INFO    : Starting detection process: 215
frigate  | [2022-11-21 14:28:41] frigate.app                    INFO    : Output process started: 217
frigate  | [2022-11-21 14:28:41] ws4py                          INFO    : Using epoll
frigate  | [2022-11-21 14:28:41] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-11-21 14:29:06] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
frigate  | [2022-11-21 14:28:41] frigate.app                    INFO    : Camera processor started for vorgarten: 225
frigate  | [2022-11-21 14:28:41] frigate.app                    INFO    : Camera processor started for garten: 226
frigate  | Process detector:coral:
frigate  | [2022-11-21 14:28:41] frigate.app                    INFO    : Capture process started for vorgarten: 228
frigate  | [2022-11-21 14:28:41] frigate.app                    INFO    : Capture process started for garten: 230
frigate  | [2022-11-21 14:28:41] ws4py                          INFO    : Using epoll
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
frigate  |     delegate = Delegate(library, options)
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
frigate  |     raise ValueError(capture.message)
frigate  | ValueError
frigate  | 
frigate  | During handling of the above exception, another exception occurred:
frigate  | 
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate  |     self.run()
frigate  |   File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate  |     self._target(*self._args, **self._kwargs)
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
frigate  |     object_detector = LocalObjectDetector(
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
frigate  |     edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
frigate  |     raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate  | ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate  | 




$ lsusb
Bus 002 Device 004: ID 1a6e:089a Global Unichip Corp. 
Bus 002 Device 002: ID 05e3:0616 Genesys Logic, Inc. hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Ubuntu 22.04.1 LTS
Coral EdgeTPU USB connected via USB Hub with ext. (2A) power supply.
Pretty clean install (just setup the complete box, only installed docker, frigate).
