### ISSUE TITLE
[BUG]: TypeError: can't access property "day", w is undefined

### ISSUE THREAD

**Issue by fabsenet** [blakeblackshear/frigate#4479]
### Describe the problem you are having

btw. you have no issue template for actual bugs?

I have kind of a fresh and empty frigate installation, added cameras, enabled record via the web gui, disabled it a minute or so later and clicked on recordings. I wanted to see what is there.

The recording page fails to finish loading and I see an error in the browser console:

```js
 h = E(() =>{
    if (!s) return []; // <<<<<<<<<<<<<<< maybe bug, because s is an empty array [] and ![] is false
    const w = s.find(y=>!e || y.day === e),
    [
      D,
      C,
      M
    ] = w.day.split('-'); // <<<<<<<<<<<< error location. w is undefined
    return w.hours.map(y=>({
      name: y.hour,
      description: `${ t } recording @ ${ y.hour }:00.`,
      sources: [
        {
          src: `${ o }/vod/${ D }-${ C }/${ M }/${ y.hour }/${ t }/master.m3u8`,
          type: 'application/vnd.apple.mpegurl'
        }
      ]
    })).reverse()
  }, [
    o,
    e,
    s,
    t
```

it is the reformatted source code obviously, but it is part of Recording.*.js

I guess I somehow managed to get an empty recordings list?

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: mqtthost

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Simon:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@cam:554/Streaming/Channels/101
          roles:
            # - record
            - rtmp
        - path: rtsp://user:pass@cam:554/Streaming/Channels/102
          roles:
            - detect
    rtmp:
      enabled: True
    detect:
      width: 3840
      height: 2160
```

### Relevant log output

```shell
Uncaught (in promise) TypeError: can't access property "day", w is undefined
```

### FFprobe output from your camera

```shell
ffprobe version 5.0-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, rtsp, from 'rtsp://user:pass@cam:554/Streaming/Channels/102':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.080000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 4:3 DAR 16:9], 12 fps, 12.50 tbr, 90k tbn
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

ANNKE C800

### Any other information that may be helpful

tested in chrome and firefox. they have the same result
