### ISSUE TITLE
[Config Support]: Problem detecting people further "away"

### ISSUE THREAD

**Issue by Pinez83** [blakeblackshear/frigate#4492]
### Describe the problem you are having

hello everyone, I use a frigate with 4 cameras. Everything works fine in 3 of them, while in the fourth one (the one with the best definition, called "Giardino") I have a little problem with detecting people. In practice, the view is very wide, and people are only detected in the red part, while they are rarely seen in the yellow part, being further away and therefore smaller.
I've read all the documentation, but I'm a newbie and I don't quite understand how I can fix this. Thank you

![rilevazione](https://user-images.githubusercontent.com/96543064/203605513-c73cc3e3-0692-41e4-9614-8a7d65941fde.jpg)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.56
  user: xxx
  password: xxx
  topic_prefix: frigate
  client_id: frigate

cameras:
  Ingresso:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.65:554/live2.sdp
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.65/live1.sdp
          roles:
            - record
      hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: false
    detect:
      width: 480
      height: 272
      fps: 7
    motion:
      mask:
        - 265,87,311,92,319,55,269,51
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      bounding_box: true
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.209:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.209/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46TDI4NUYxNjQ=
          roles:
            - record
      hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: false
    detect:
      width: 640
      height: 480
      fps: 15
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      bounding_box: true
  Giardino:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.77:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.77:554/h264Preview_01_main
          roles:
            - record
    rtmp:
      enabled: false
    detect:
       width: 1536
       height: 576
       fps: 30
    motion:
      mask:
        - 0,0,388,0,0,504
        - 1536,0,1536,322,1384,440,1067,0
    objects:
      track:
        - person
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      bounding_box: true
  Sala:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.1.64/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.1.64/HighResolutionVideo
          roles:
            - record
      hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: false
    detect:
      width: 352
      height: 240
      fps: 15
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      bounding_box: true
birdseye:
  enabled: True
  mode: continuous
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  events:
    retain:
      default: 10
database:
  path: /media/frigate/db/frigate.db
```

### Relevant log output

```shell
nothing
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
