### ISSUE TITLE
[Support]: Clips and recordings cannot be played from Frigate or HA

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4494]
### Describe the problem you are having

Hi, since several weeks (or months, not sure), and I don't know what exactly triggered this change (may be updating Frigate from 0.10 to 0.11, but I can't confirm) this started happening.

I cannot open any clip or recording from Frigate in the Frigate UI or even in Home Assistant. However, if I download the file and open it in VLC it works fine. I see no issues with the codecs either.

I recorded a video showing more details about it, but I'm really clueless on what to do. Any help is really appreciated.

https://user-images.githubusercontent.com/29582865/203677223-43d44d94-a54b-4fde-82d0-ddd24a28c2c3.mp4

### Version

0.11.1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate:5000/api/config/schema

detectors:
  coral1:
    type: edgetpu
    device: pci:0

mqtt:
  host: core-mosquitto
  user: mqtt
  password: hidden

detect:
  enabled: true

objects:
  track:
    - person
    - car
    - dog
    - cat
    - motorcycle
    - bicycle
    - cow
    - horse

record:
  enabled: true
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 60
      mode: active_objects

snapshots:
  enabled: true

birdseye:
  enabled: true
  width: 1920
  height: 1080
  mode: continuous

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

environment_vars:
  LIBVA_DRIVER_NAME: i965

cameras:
  portao:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.10:8554/camera.portao?video=copy&audio=aac
          roles:
            - detect
            - record
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a copy
        rtmp: -c:v copy -c:a copy -f flv
    detect:
      width: 640
      height: 360
    live:
      height: 360
    zones:
      video_porteiro_area:
        coordinates: 421,186,465,213,385,225,376,202
        objects:
          - person
      estrada:
        coordinates: 271,306,271,246,463,215,529,252
        objects:
          - car
          - person
          - motorcycle
```

### Relevant log output

```shell
[2022-11-23 20:24:15] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2022-09/23/07/portao/43.47.mp4
[2022-11-23 21:24:26] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2022-09/23/07/portao/43.48.mp4
[2022-11-23 22:24:34] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2022-09/23/07/portao/43.54.mp4
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0000020f2854b5c0] method SETUP failed: 461 Unsupported transport
[h264 @ 0000020f28558700] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0000020f28558700] decode_slice_header error
[h264 @ 0000020f28558700] no frame!
Input #0, rtsp, from 'rtsp://192.168.1.10:8554/camera.portao?video=copy&audio=aac':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 8000 Hz, mono, fltp
  Stream #0:1: Video: h264 (Constrained Baseline), yuv420p(progressive), 640x360, 10 fps, 10 tbr, 90k tbn
```

### Frigate stats

```json
{
"chafariz": {
"camera_fps": 5.1,
"capture_pid": 248,
"detection_fps": 0.0,
"pid": 231,
"process_fps": 5.1,
"skipped_fps": 0.0
},
"detection_fps": 2.7,
"detectors": {
"coral1": {
"detection_start": 0.0,
"inference_speed": 11.47,
"pid": 216
}
},
"morro": {
"camera_fps": 5.0,
"capture_pid": 239,
"detection_fps": 0.0,
"pid": 225,
"process_fps": 5.0,
"skipped_fps": 0.0
},
"portao": {
"camera_fps": 5.0,
"capture_pid": 237,
"detection_fps": 0.1,
"pid": 224,
"process_fps": 5.0,
"skipped_fps": 0.0
},
"portao_do_terreiro": {
"camera_fps": 5.1,
"capture_pid": 243,
"detection_fps": 0.0,
"pid": 230,
"process_fps": 5.1,
"skipped_fps": 0.0
},
"rua": {
"camera_fps": 5.1,
"capture_pid": 236,
"detection_fps": 0.0,
"pid": 222,
"process_fps": 5.1,
"skipped_fps": 0.0
},
"service": {
"latest_version": "0.11.1",
"storage": {
"/dev/shm": {
"free": 4072.3,
"mount_type": "tmpfs",
"total": 4080.5,
"used": 8.2
},
"/media/frigate/clips": {
"free": 270099.8,
"mount_type": "ext4",
"total": 983358.5,
"used": 663231.8
},
"/media/frigate/recordings": {
"free": 270099.8,
"mount_type": "ext4",
"total": 983358.5,
"used": 663231.8
},
"/tmp/cache": {
"free": 4079.6,
"mount_type": "tmpfs",
"total": 4080.5,
"used": 0.9
}
},
"temperatures": {
"apex_0": 68.3
},
"uptime": 9192,
"version": "0.11.1-2eada21"
},
"terreiro": {
"camera_fps": 5.1,
"capture_pid": 241,
"detection_fps": 2.6,
"pid": 229,
"process_fps": 5.0,
"skipped_fps": 0.0
},
"terreiro_escada": {
"camera_fps": 5.0,
"capture_pid": 250,
"detection_fps": 0.0,
"pid": 233,
"process_fps": 5.0,
"skipped_fps": 0.0
},
"video_porteiro_do_terreiro": {
"camera_fps": 5.0,
"capture_pid": 256,
"detection_fps": 0.0,
"pid": 234,
"process_fps": 5.0,
"skipped_fps": 0.0
}
}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Howell QJ05 (restreamed by go2rtc)

### Any other information that may be helpful

N/A
