### ISSUE TITLE
[EdgeTPU Support]: 

### ISSUE THREAD

**Issue by ianwood** [blakeblackshear/frigate#4516]
### Describe the problem you are having

EdgeTPU was not found after upgrade. Tried multiple reboots. Moved TPU to different USB port. Still not found. Finally, turned off protection mode and it was found and worked normally. 

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -c:a aac -f flv

rtmp:
  enabled: False

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@xxx:554/H264/ch1/sub/av_stream
          roles:
            - detect
        - path: rtsp://xxx:xxx@xxx:554/H264/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      improve_contrast: True
      mask:
      - 505,78,316,58,105,73,0,119,0,0,640,0,640,106
      - 585,480,609,429,640,360,640,318,597,390,640,91,558,89,558,233,547,294,420,293,320,308,228,335,147,385,148,480
      - 201,423,204,436,24,440,24,426
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
    record:
      enabled: True
      retain:
        days: 4
        mode: motion
      events:
        retain:
          default: 4
          mode: active_objects
        required_zones:
          - property
          - street
    zones:
      property:
        coordinates: 640,229,640,480,0,480,0,123,29,256,137,174,327,172,486,182,567,194
        objects:
        - person
      street:
        coordinates: 315,0,0,0,26,220,136,148,140,169,320,172,494,182,640,176,640,0
        objects:
        - person
```

### docker-compose file or Docker CLI command

```yaml
Running as HASSIO addon.
```

### Relevant log output

```shell
No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
