### ISSUE TITLE
[Config Support]: Working with parked cars

### ISSUE THREAD

**Issue by adambmedent** [blakeblackshear/frigate#4518]
### Describe the problem you are having

Trying to get my front camera working the way I want with cars.  

The blue zone is for a parked car, the orange zone in the front of the driveway is ideally for cars pulling in, but there are a lot of situations that we end up with a car parked in that spot as well.  Which then typically results in a recording that is as long as the car sits there.  Is there a better way to do my zones so that it picks up cars pulling in the driveway but doesn't record them if they are in the front driveway zone?

![FrontCam](https://user-images.githubusercontent.com/3780255/204092650-04ab3d80-ed0c-4ecf-ab32-b2c76d5a7536.png)

Appreciate the input, Frigate has been awesome so far!

### Version

0.10.1-83481AF

### Frigate config file

```yaml
cameras:
  FrontCamera:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxx@10.x.x.xx:554:/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      width: 2592
      height: 1944
      fps: 5
#      stationary:
#        max_frames:
#          objects:
#            car: 100
    zones:
      DrivewayEntrance:
        coordinates: 1034,307,1215,417,1708,335,1363,175,741,231
        objects:
          - person
          - car
          - car
          - dog
          - cat
      ParkingArea:
        coordinates: 2122,1058,2473,828,2085,429,1698,358,1329,464
        objects:
          - person
      Everywhere:
        coordinates: 1754,1944,2200,1505,2224,1428,2351,1231,2412,1130,2499,1066,2592,905,2592,758,1934,310,1403,185,783,204,0,388,0,1944
        objects:
          - person
          - cat
          - dog
      FrontDoor:
        coordinates: 2163,1080,2369,1217,2139,1547,1987,1695,1721,1944,1613,1944,1318,1944,692,1473,1395,865
        objects:
          - person
    motion:
      mask:
        - 1087,0,2592,0,2592,687,2390,544,2151,412,1937,305,1660,220,1571,199,1489,202,1334,197,780,212,639,236,552,254,0,427,0,0
    record:
      events:
        required_zones:
          - DrivewayEntrance
          - ParkingArea
          - FrontDoor
          - Everywhere
    snapshots:
        required_zones:
          - DrivewayEntrance
          - Driveway
          - FrontDoor
          - Everywhere
```

### Relevant log output

```shell
I don't think there is any relevant log output
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
