### ISSUE TITLE
[Support]: x-ingress-path works on first page but subsequent url history pushes are wrong

### ISSUE THREAD

**Issue by drewp** [blakeblackshear/frigate#4526]
### Describe the problem you are having

https://bigasterisk.com/frigate/ works (for my user) because I have pomerium set "x-ingress-path: /frigate" on all requests. I also have to strip /frigate, so your server receives request paths like /assets/index.26543.js (if I don't do this, requesting /frigate/assets/index.js returns some html page).

The working home page I see contains `<script>window.baseUrl="/frigate/";</script>`.

Now when I click on Birdseye, the url goes to `https://bigasterisk.com/birdseye` which is wrong. That should be /frigate/birdseye.

### Version

dev branch from a few mins ago

### Frigate config file

```yaml
My k8s/pomerium ingress config:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    ingress.pomerium.io/allow_public_unauthenticated_access: "false"
    ingress.pomerium.io/pass_identity_headers: "true"
    ingress.pomerium.io/preserve_host_header: "true"
    ingress.pomerium.io/allow_websockets: "true"
    ingress.pomerium.io/policy: ...
    ingress.pomerium.io/prefix_rewrite: "/"
    ingress.pomerium.io/set_request_headers: |
      x-ingress-path: /frigate
spec:
  ingressClassName: pomerium
  rules:
    - host: "bigasterisk.com"
      http:
        paths:
          - pathType: Prefix
            path: /frigate/
            backend: { service: { name: frigate, port: { number: 80 } } }

----
Partial frigate config:

    mqtt:
      host: mosquitto-ext.default.svc.cluster.local
      port: 1883
      topic_prefix: frigate
      client_id: frigate
      stats_interval: 60

    detectors:
      cpu1:
        type: cpu
    logger:
      default: debug
      logs:
        peewee: warning
        peewee_migrate: warning

    cameras: ...
```

### Relevant log output

```shell
Selected chrome inspector network urls that are fetched (note double-slash on the last one):

https://bigasterisk.com/frigate/
https://bigasterisk.com/frigate/assets/index.269d582e.js
https://bigasterisk.com/frigate/api/config
https://bigasterisk.com/frigate//api/garage_hall/latest.jpg?h=216
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

various
