### ISSUE TITLE
Improving snapshot pic + lag

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#4527]
### Describe the problem you are having

Snapshot is really useful in my case (send via telegram) but the picture quality is bad ,
I understand it's happened as I'm using the sub channel for detection but wonder how i can improve it.
second , once event is being it started ~10 seconds after the motion detected ,
Hardware - qnap 451 + 16GB of ram 
Using Frigate for single camera .

```
Automation:

- alias: Frigate All Events
  trigger:
    platform: mqtt
    topic: frigate/events 
  condition:
    condition: template
    value_template: >
       {{ trigger.payload_json["before"]["stationary"] == false }}
  action
    - service: notify.x_security
      data:
        title: Send an image
        message: Message
        data:
          photo:
            - url: 'https://xxxxx.xxxxx.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
              caption: '{{trigger.payload_json["after"]["label"]}} was detected by {{trigger.payload_json["after"]["camera"]}} score ({{trigger.payload_json["after"]["top_score"]}})'              
    - service: notify.avico_security
      data_template:
        message: >
          {{trigger.payload_json["after"]["label"]}} was detected by {{trigger.payload_json["after"]["camera"]}} score {{trigger.payload_json["after"]["top_score"]}}

```

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.113
  port: 1883

 
cameras:
  intercom:
    mqtt:
      required_zones:
        - zone_parking_line      

    ffmpeg:
      global_args: -hide_banner -loglevel warning
      inputs:
         - path:  rtsp://xxx:yyy@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0
           roles:
            - record

         - path:  rtsp://xxx:yyy@192.168.1.110:554/cam/realmonitor?channel=1&subtype=1
           roles:
            - detect 
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264              
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - zone_parking_line
      retain:
        default: 3
        objects:
          person: 10
    record:
      enabled: True
      retain:
        days: 5
      events:
        pre_capture: 10
        post_capture: 10      
        retain:
          default: 10
        required_zones:
          - zone_parking_line

    motion:
      mask:
        - 347,200,530,245,555,406,892,421,1030,402,1019,165,984,109,1212,45,1190,0,343,0

    zones:
      zone_parking_line:     
        coordinates: 1185,720,291,720,326,535,607,547,773,652,1037,676,1029,242,1239,240
        objects:
          - person
          - dog
          - cat
          - truck
          - bicycle

        filters:
          person:
            threshold: 0.7
            min_area: 5000
            max_area: 100000      
          car:
            threshold: 0.7
            min_area: 5000
            max_area: 100000              
    detect:
      height: 720
      width: 1280
      fps: 10
```

### Relevant log output

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

The QNAP TS-451 (TS-451)
Cpu: Intel Celeron J1800 dual-core @ 2.4 GHz CPU and 16 GB   RAM
