### ISSUE TITLE
[Config Support]: New to Frigate - can't get it started

### ISSUE THREAD

**Issue by okridgway** [blakeblackshear/frigate#4529]
### Describe the problem you are having

I have a standalone Raspberry Pi 4 (4 GB RAM) that I have set up to be my Frigate server. I've installed Frigate with Docker Compose and created a simple configuration file (`config.yml`) that I put in `~/frigate/config/`. I keep getting an error saying that the file `config/config.yml` doesn't exist, so I've also put this file in `/frigate/config/`. I have noticed that when trying to start frigate, it generates a directory called `config.yml`, so I've also put my config file within this directory. I've also tried navigating to `/opt/frigate/frigate/` but nothing exists within the `/opt` directory. 

The documentation says that the config file should be in `/config/config.yml` within the container directory, but I'm unsure of where the container directory is, if not `/frigate/` or `~/frigate/`.

### Version

N/A

### Frigate config file

```yaml
mqtt:
  host: 192.168.190.2
  user: <home assistant mosquito username> 
  password: <home assistant mosquito password> 

cameras:
  backyard_camera:
    ffmpeg:
      inputs:
        - path: rtsp://<camera username>:<camera password>@192.168.190.178:554/cam/realmonitor?channel=1&subtype=0
          roles:
	    - rtmp
```

### Relevant log output

```shell
Starting frigate ... done
Attaching to frigate
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | *************************************************************
frigate    | *************************************************************
frigate    | ***    Your config file is not valid!                     ***
frigate    | ***    Please check the docs at                           ***
frigate    | ***    https://docs.frigate.video/configuration/index     ***
frigate    | *************************************************************
frigate    | *************************************************************
frigate    | ***    Config Validation Errors                           ***
frigate    | *************************************************************
frigate    | [Errno 2] No such file or directory: '/config/config.yml'
frigate    | [2022-11-27 10:36:16] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate    | Traceback (most recent call last):
frigate    |   File "/opt/frigate/frigate/app.py", line 312, in start
frigate    |     self.init_config()
frigate    |   File "/opt/frigate/frigate/app.py", line 77, in init_config
frigate    |     user_config = FrigateConfig.parse_file(config_file)
frigate    |   File "/opt/frigate/frigate/config.py", line 896, in parse_file
frigate    |     with open(config_file) as f:
frigate    | FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
frigate    | 
frigate    | *************************************************************
frigate    | ***    End Config Validation Errors                       ***
frigate    | *************************************************************
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Ultimately, I am hoping to connect this stand-alone pi running frigate to a second Pi running home assistant.

**Comment by blakeblackshear** [comment]
Post your docker compose file

**Comment by okridgway** [comment]
```
version: "3.3"
services: 
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    shm_size: "64mb"
    devices: 
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config.yml:/frigate/config.yml
      - /frigate/media:/frigate/media
      - type: tmpfs
        target: /tmp/cache
    ports: 
     - "5000:5000"
     - "1935:1935"
    environment: 
     FRIGATE_RTSP_PASSWORD: "password"
```
