### ISSUE TITLE
[Support]: Confused about Snapshots

### ISSUE THREAD

**Issue by gregeeh** [blakeblackshear/frigate#4533]
### Describe the problem you are having

Hi all,

I have Frigate, HA and Mosquitto setup in separate Containers on my NAS.  All is working fine but I cannot get video snapshots attached to SMTP Emails for every notification.

From what I can tell the Frigate Snapshot is created when the detection recording stops.  Hence when I get many detections (person) ,as say a person moves around an area, the recording continues until no movement is detected. 

In the meantime MQTT is detecting all this motion, sends an email and trys to attach a snapshot.  But it fails to find a snapshot as the recording has not ended.

So I suppose what I'm saying is I need just one email sent per recording and not per motion detection.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
    host: 192.168.10.2
    user: mqtt-user
    password: mqtt-password
cameras:
    Villa333:
        rtmp:
            enabled: false
        ffmpeg:
            input_args:
               - -avoid_negative_ts
               - make_zero
               - -fflags
               - +genpts+discardcorrupt
               - -flags
               - low_delay
               - -strict
               - experimental
               - -analyzeduration
               - 1000M
               - -probesize
               - 1000M
            inputs:
                - path: rtsp://admin:open4me@192.168.10.70:554/h264Preview_01_sub
                  roles:
                    - detect
                - path: rtsp://admin:open4me@192.168.10.70:554/h264Preview_01_main
                  roles:
                    - record
                    - rtmp
        detect:
            width: 640
            height: 360
        record:
            enabled: True
            events:
                pre_capture: 15
                post_capture: 5
                retain:
                    default: 1
                    mode: active_objects
snapshots:
    enabled: True
    retain:
        default: 1
birdseye:
    enabled: True
    mode: continuous
    quality: 6
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
Not known.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Reolink E! Pro

### Any other information that may be helpful

**Below is Home Assistant configuration.yaml**

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Allow Access to Frigate Files
homeassistant:
    allowlist_external_dirs:
        - "/media-frigate"

```
notify:
  - name: ClickHost
    platform: smtp
    port: 465
    sender: someemail@something.com
    recipient: someemail@something.com
    username: someemail@something.com
    password: password
    sender_name: Home Assistant
    server: mxserver.com.au
    encryption: tls

automation: !include myautomations.yaml

# Labeled automation block
automation frigate:
- id: '9669508379780'
  alias: Frigate Mail Automation
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
    payload: Villa333
    value_template: '{{ value_json[''after''][''camera''] }}'
  variables:
    frigateid: '{{ trigger.payload_json[''after''][''id''] }}'
    camera: '{{ trigger.payload_json[''after''][''camera''] }}'
    camera_name: '{{ camera | replace(''_'', '' '') | title }}'
    object: '{{ trigger.payload_json[''after''][''label''] }}'
    label: '{{ object | title }}'
    entered_zones: '{{ trigger.payload_json[''after''][''entered_zones''] }}'
    type: '{{ trigger.payload_json[''type''] }}'
  condition: []
  action:
  - service: notify.clickhost
    data:
        title: "Camera {{trigger.payload_json['after']['camera']}}: Motion!"
        message: "{{trigger.payload_json['after']['camera']}}-{{trigger.payload_json['after']['id']}}.jpg"
        data:
            images:
                - "/media-frigate/clips/{{trigger.payload_json['after']['camera']}}-{{trigger.payload_json['after']['id']}}.jpg"
        target: someemail@something.com
  mode: single
```

**Comment by NickM-27** [comment]
It's important to note that there is a difference between snapshots (still images) and recordings.

Snapshots are available while the event is ongoing, the event does not need to be over for the snapshot to be available.

> In the meantime MQTT is detecting all this motion, sends an email and trys to attach a snapshot. But it fails to find a snapshot as the recording has not ended.

as said above this is not the case, having the actual logs would be helpful in understanding what the error is

**Comment by gregeeh** [comment]
Thanks for your reply.

After a bit of digging around I found the issue.  I changed this:
```
 trigger:
  - platform: mqtt
    topic: frigate/events
    payload: Villa333
    value_template: '{{ value_json[''after''][''camera''] }}'
```

To this:
 ```
 trigger:
  - platform: mqtt
    topic: frigate/events
    payload: "on"
    value_template: '{{ "on" if value_json["after"]["camera"] == "Villa333" and value_json["type"] == "end" else "off"}}'
    id: end_event
```
