### ISSUE TITLE
QUADRO card + I7 - Help configuring 

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#4537]
### Describe the problem you are having

after i give up running friagte on my qnap 451,
Moving it to HP z3 mini running dokers on Windows 10 :
https://support.hp.com/us-en/document/c05338666
And have doubt for configuring the frigate.yaml for ffmpeg and detectors or actually any paramer
that can help "nvring" up to 5 Dahua 4Mp cameras?
Second , i see many define the mqtt also per cameras - why we need to save snapshot also on mqtt while it saved directly on FS?

CPU:
Intel Core i7-6700 processor with Intel HD Graphics 530

QUADRO M620 card:
https://www.notebookcheck.net/NVIDIA-Quadro-M620-GPU-Benchmarks-and-Specs.213796.0.html

Memory: 
32GB of RAM

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.113
  port: 1883

cameras:

  salon_ceiling:

    ffmpeg:
      global_args: -hide_banner -loglevel warning
      inputs:
         - path:  rtsp://admin:xxxxx@192.168.1.138/cam/realmonitor?channel=1&subtype=0
           roles:
            - record
            - detect 
            - rtmp  
    objects:
      track:
        - person
        - dog

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      required_zones:
        - zone_parking_line      
      height: 500

    detect:
      height: 1080
      width: 1920
      fps: 5      

    zones:
      zone_salon:
        coordinates: 50,234,1570,286,1868,1034,44,1050
  
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - zone_salon
      # height: 175
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        objects:
          person: 15

    record:
      enabled: True
      retain:
        days: 5
      events:
        pre_capture: 10
        post_capture: 10      
        retain:
          default: 7
        required_zones:
          - zone_salon


  salon_desk:

    ffmpeg:
      global_args: -hide_banner -loglevel warning
      inputs:
         - path:  rtsp://admin:xxxx@192.168.1.92/cam/realmonitor?channel=1&subtype=0
           roles:
            - record
            - detect 
            - rtmp  
    objects:
      track:
        - person
        - dog

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      required_zones:
        - zone_parking_line      
      height: 500

    detect:
      height: 1080
      width: 1920
      fps: 5      

    zones:
      zone_salon_desk:
        coordinates: 50,234,1570,286,1868,1034,44,1050
  
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - zone_salon_desk
      # height: 175
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        objects:
          person: 15

    record:
      enabled: True
      retain:
        days: 5
      events:
        pre_capture: 10
        post_capture: 10      
        retain:
          default: 7
        required_zones:
          - zone_salon_desk


  intercom:
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      inputs:
         - path:  rtsp://aaar:xxxxx@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0
           roles:
            - record
            - detect 
            - rtmp
    detect:
      height: 720
      width: 1280
      fps: 5  
      stationary:
        threshold: 50
        max_frames:
          # Optional: Object specific values
          objects:
            person: 200
            car: 2000
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
        - bicycle
        - truck
        - cat
        - dog

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      required_zones:
        - zone_parking_line      
      height: 500

    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264              
   
    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - zone_parking_line
      # height: 175
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        objects:
          person: 15

    record:
      enabled: True
      retain:
        days: 5
      events:
        pre_capture: 10
        post_capture: 10      
        retain:
          default: 7
        required_zones:
          - zone_parking_line

    motion:
      mask:
        - 347,200,530,245,555,406,892,421,1030,402,1019,165,984,109,1212,45,1190,0,343,0

    zones:
      zone_parking_line:     
        coordinates: 1185,720,291,720,326,535,607,547,773,652,1037,676,1029,242,1239,240
        objects:
          - person
          - dog
          - cat
          - truck
          - bicycle

        filters:
          person:
            threshold: 0.7
            min_area: 5000
            max_area: 100000      
          car:
            threshold: 0.7
            min_area: 5000
            max_area: 100000
```

### Relevant log output

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

NA
