### ISSUE TITLE
[Support]: Frigate armed my home alarm in HomeAssistant 

### ISSUE THREAD

**Issue by gustjoha** [blakeblackshear/frigate#4540]
### Describe the problem you are having

Hi,

This is very odd and I´m not quite sure what happened, but my alarm was armed in Frigate via mqtt. 

```
Partition Area 1 changed to Arming triggered by service alarm_control_panel.alarm_arm_home
17:41:27 - 17 minutes ago - frigate
```

Did anyone experience this? The alarm is also set up via mqtt - can it be something passed over? Super weird and I have no automations for Frigate in place...

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.147
  user: frigate
  password: frigate
  
detectors:
  coral:
    type: edgetpu
    device: usb
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true     
record:
  enabled: True
  expire_interval: 60
  retain:
    days: 1
    mode: all


ffmpeg:
  hwaccel_args: -c:v h264_cuvid
cameras:
  Backyard:
    ffmpeg:
      #hwaccel_args:
      #input_args:
      inputs:
        - path: rtsp://xxxxx@192.168.1.39:554//h264Preview_01_main
          roles:
            - record
            - rtmp
        - path: rtsp://xxxxx@192.168.1.39:554//h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 10
    objects:
     # Optional: list of objects to track from labelmap.txt (default: shown below)
     track:
     - person
     - dog
     - cat  
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true     

  Terrace:
    ffmpeg:
      #hwaccel_args:
      #input_args:
      inputs:
        - path: rtsp://xxxxx@192.168.1.74/cam/realmonitor?channel=1&subtype=00&authbasic=xxxx=
          roles:
            - record
            - rtmp
        - path: rtsp://xxxx@192.168.1.74/cam/realmonitor?channel=1&subtype=01&authbasic=xxxx=
          roles:
            - detect    
    detect:
      width: 640
      height: 480
      fps: 15
    objects:
     # Optional: list of objects to track from labelmap.txt (default: shown below)
     track:
     - person
     - dog
     - cat  
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true      

      
  Front:
    ffmpeg:
      #hwaccel_args:
      #input_args:
      inputs:
        - path: rtsp://xxx@192.168.1.64/Streaming/Channels/101
          roles:
            - record
            - rtmp
        - path: rtsp://xxxx@192.168.1.64/Streaming/Channels/102
          roles:
            - detect    
    detect:
      width: 640
      height: 480
      fps: 25
    objects:
     # Optional: list of objects to track from labelmap.txt (default: shown below)
     track:
     - person
     - dog
     - cat 
     - car   
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
```

### Relevant log output

```shell
x
```

### FFprobe output from your camera

```shell
x
```

### Frigate stats

```json
x
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

x
