### ISSUE TITLE
Conditional frigate monitoring/process by enabling full mask

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#4546]
### Describe the problem you are having

My use case is simple:

I'd like to enable frigate processing/monitoring by "known" condition - it can be if kids/wife at home or any other 
 scenario.

I wish it I could use some of the HA sensors to trigger this functionality but i don't know if it possible ,
So I'm trying to using full masked screen to get this to  working:

On camera itself , i create full masking overlay (using Dahua camera)

On HA i set 2 shell_command for enable/disable the masking:
```
set_mask_salon_on: /usr/bin/curl --digest -u aaaa:xxx -g 'http://192.168.1.138/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].Covers[].EncodeBlend=true'
 set_mask_salon_off: /usr/bin/curl --digest -u aaaa:xxx -g 'http://192.168.1.138/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].Covers[].EncodeBlend=false'
````
now can set any automation for triggering above commands
````
             
 - alias: 'Set mask OFF salon2'
   initial_state: 'on'
   trigger:
     platform: state
     entity_id:  group.kids
     to: 'not_home'
     for:
       minutes: 4
   action:
      - service: shell_command.set_mask_salon2_off

 - alias: 'Set mask ON salon2'
   initial_state: 'on'
   trigger:
     - platform: state
       entity_id: group.kids
       to: 'home'
       for:
         minutes: 4
   action:
      - service: shell_command.set_mask_salon2_on
              


```
Now Frigate see black screen so nothing to process right?
I would expect it will not record anything but it does records black screen ,

I added:
```
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 10
        post_capture: 10      
        retain:
          default: 7
          mode: active_objects
        required_zones:
          - zone_parking_line
```
Need more time to test it maybe can get some tips what else can be done .
I know it's a bit monkey patch solution but it suppose to work,
what do u think?any tips for Frigate so it can "sleep" while seeing a full black screen?






### Version

0.11.1-2eada21

### Frigate config file

```yaml
record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 10
        post_capture: 10      
        retain:
          default: 7
          mode: active_objects
        required_zones:
          - zone_parking_line
```


### Relevant log output

```shell
NA
```


### Frigate stats

```json
NA
```


### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

NA
