### ISSUE TITLE
[Config Support]: Frigate not saving to samba share

### ISSUE THREAD

**Issue by Everett115** [blakeblackshear/frigate#4556]
### Describe the problem you are having

I can't get frigate to save to my windows share. I thought I had it working before but then the system crashed and won't boot. It had ended up saving everything on the NAS and local SSD. I deleted the old share and created a samba share mounted in /media/SecurityCamera. Now there are no recordings or clips being saved there. I am definitely able to access the share in the terminal and create files in it that I can then view on my windows machine. It looks like recordings might be being saved in the database file because I can't find the actual video files anywhere but the homeassistant notification clips can be opened. The database file size seems to keep growing as well (went from 83Gb to 86Gb while writing this)

### Docker compose file:

```frigate:
  container_name: frigate
  privileged: true # this may not be necessary for all setups
  restart: unless-stopped
  image: blakeblackshear/frigate:stable
  shm_size: "600mb" # update for your cameras based on calculation above
  devices:
    - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    - /dev/dri/card0 # for intel hwaccel, needs to be updated for your hardware
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/frigate/config/config.yaml:/config/config.yml:ro
    - /media/SecurityCamera:/media/frigate
    - /opt/frigate/db:/db
    - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      target: /tmp/cache
      tmpfs:
        size: 1000000000
  ports:
    - "5000:5000"
    - "1935:1935" # RTMP feeds
  environment:
    FRIGATE_RTSP_PASSWORD: "#REDACTED#"
```

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.67
  user: hass
  password: #REDACTED#

database:
  path: /db/frigate.db

logger:
  default: info

detectors:
  coral:
    type: edgetpu
    device: usb

#Global Hardware Acceleration Arguments
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/card0
    - -hwaccel_output_format
    - yuv420p 
    
#Global Object Settings
objects:
  track:
    - person
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.8  

#Birdseye Settings
birdseye:
  enabled: True
  mode: continuous

#Camera Settings
cameras:
  Back_Door:
    ffmpeg:
      inputs:
        # Main Stream - High Res
        - path: rtsp://admin:#REDACTED#@192.168.1.10:554/cam/realmonitor?channel=1&subtype=00&authbasic=64
          roles:
            - record
            - rtmp
        # Sub Stream - Low Res      
        - path: rtsp://admin:#REDACTED#@192.168.1.10:554/cam/realmonitor?channel=1&subtype=01&authbasic=64
          roles:
            - detect     
    detect:
      width: 704
      height: 480
      fps: 5
    record: 
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10  
    snapshots: 
      enabled: True
    motion:
      mask:
        - 586,185,561,480,704,480,704,0,136,0,0,114,0,0,546,0
  Back_Yard:
    ffmpeg:
      inputs:
        # Main Stream - High Res
        - path: rtsp://admin:#REDACTED#@192.168.1.11:554/cam/realmonitor?channel=1&subtype=00&authbasic=64
          roles:
            - record
            - rtmp
        # Sub Stream - Low Res      
        - path: rtsp://admin:#REDACTED#@192.168.1.11:554/cam/realmonitor?channel=1&subtype=01&authbasic=64
          roles:
            - detect   
    detect:
      width: 704
      height: 480
      fps: 5
    record: 
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10  
    snapshots: 
      enabled: True
    motion:
      mask:
        - 206,0,520,0,510,39,456,74,456,107,433,124,384,117,335,158,259,120,210,89
        - 704,480,651,480,676,398,704,382
        - 134,442,43,327,0,248,0,480,183,480
        - 704,109,704,0,517,0,513,30
  Side_Gate:
    ffmpeg:
      inputs:
        # Main Stream - High Res
        - path: rtsp://admin:#REDACTED#@192.168.1.12:554/cam/realmonitor?channel=1&subtype=00&authbasic=64
          roles:
            - record
            - rtmp
        # Sub Stream - Low Res      
        - path: rtsp://admin:#REDACTED#@192.168.1.12:554/cam/realmonitor?channel=1&subtype=01&authbasic=64
          roles:
            - detect     
    detect:
      width: 704
      height: 480
      fps: 5
    record: 
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10  
    snapshots: 
      enabled: True
    motion:
      mask:
        - 704,0,0,0,0,218,158,258,360,93,488,98,478,183,465,480,704,480
        - 193,441,345,480,452,480,536,292,100,247  
  Driveway:
    ffmpeg:
      inputs:
        # Main Stream - High Res
        - path: rtsp://admin:#REDACTED#@192.168.1.13:554/cam/realmonitor?channel=1&subtype=00&authbasic=64
          roles:
            - record
            - rtmp
        # Sub Stream - Low Res      
        - path: rtsp://admin:#REDACTED#@192.168.1.13:554/cam/realmonitor?channel=1&subtype=01&authbasic=64
          roles:
            - detect     
    detect:
      width: 704
      height: 480
      fps: 5
      stationary:
        interval: 0
        threshold: 30
    record: 
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
        required_zones:
          - Entire_Yard
          - Parking_Area
    mqtt:
      required_zones:
        - Entire_Yard
        - Parking_Area
    snapshots:    
      enabled: True
      required_zones:
        - Entire_Yard
        - Parking_Area        
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bicycle
    zones:
      Parking_Area:
        coordinates: 149,480,430,141,161,117,271,67,491,70,632,106,582,480
        objects:
          - person
          - cat
          - dog
      Entire_Yard:
        coordinates: 110,480,0,271,0,184,60,139,206,68,501,77,678,118,704,480   
        objects:
          - car
          - motorcycle
          - bicycle
    motion:
      mask:
        - 704,0,0,0,0,185,40,154,76,148,157,96,217,70,407,63,704,121
        - 0,480,98,480,0,300
```

### Relevant log output

```shell
[2022-11-29 21:59:48] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2022-11/24/17/Driveway/18.41.mp4

[2022-11-29 22:30:41] watchdog.Driveway              INFO    : Terminating the existing ffmpeg process...
[2022-11-29 22:30:41] watchdog.Driveway              INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : [segment @ 0x563bfe8d9040] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : [flv @ 0x563bfe8da2c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : av_interleaved_write_frame(): No space left on device
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : [segment @ 0x563bfe8d9040] Failure occurred when ending segment '/tmp/cache/Side_Gate-20221129223032.mp4'
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : Error writing trailer of /tmp/cache/Side_Gate-%Y%m%d%H%M%S.mp4: No space left on device
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : [flv @ 0x563bfe8da2c0] Failed to update header with correct duration.
[2022-11-29 22:30:41] ffmpeg.Side_Gate.record_rtmp   ERROR   : [flv @ 0x563bfe8da2c0] Failed to update header with correct filesize.

BlockingIOError: [Errno 11] Resource temporarily unavailable: '/media/frigate/recordings' 
[2022-11-24 20:09:44] frigate.http ERROR : Exception on /stats [GET] Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
