### ISSUE TITLE
Corrupted image from frigate stream in frigate:0.8.0-beta3-amd64

### ISSUE THREAD

**Issue by ghettodev** [blakeblackshear/frigate#456]
**Describe the bug**
In beta 3, I can view the rtmp stream from frigate in vlc and it displays correctly, the direct stream from http://192.168.1.234:5000/{camera} is always corrupted as per the screenshot.

**Version of frigate**
0.8.0-beta3-amd64

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
logger:
  default: debug
  logs:
    frigate.mqtt: info
    frigate.edgetpu: info
    frigate.app: info
    frigate.zeroconf: info

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.1.39
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx

ffmpeg:
  global_args: -hide_banner -loglevel info

cameras:
  wyze2:
    ffmpeg:
      inputs: 
        - path: rtsp://xxx:xxx@192.168.1.250:8554/unicast
        #- path: rtsp://xxx:xxx@192.168.1.253:554/ch01/0
        #- path: rtsp://xxx:xxx@192.168.1.121:81/camiushd&w=1280&h=720
          roles:
            - detect
            - rtmp
            - clips
            - record
    height: 1920
    width: 1080
    fps: 15
```

**Logs**
```
frigate          |  * Starting nginx nginx
frigate          |    ...done.
frigate          | peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "event" ("id" VARCHAR(30) NOT NULL PRIMARY KEY, "label" VARCHAR(20) NOT NULL, "camera" VARCHAR(20) NOT NULL, "start_time" DATETIME NOT NULL, "end_time" DATETIME NOT NULL, "top_score" REAL NOT NULL, "false_positive" INTEGER NOT NULL, "zones" JSON NOT NULL, "thumbnail" TEXT NOT NULL)', [])
frigate          | peewee                         DEBUG   : ('CREATE INDEX IF NOT EXISTS "event_label" ON "event" ("label")', [])
frigate          | peewee                         DEBUG   : ('CREATE INDEX IF NOT EXISTS "event_camera" ON "event" ("camera")', [])
frigate          | frigate.mqtt                   INFO    : MQTT connected
frigate          | detector.coral                 INFO    : Starting detection process: 49
frigate          | frigate.app                    INFO    : Camera processor started for wyze2: 52
frigate          | frigate.app                    INFO    : Capture process started for wyze2: 54
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] non-existing PPS 0 referenced
frigate          | ffmpeg.wyze2.detect            ERROR   :     Last message repeated 1 times
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] decode_slice_header error
frigate          | ffmpeg.wyze2.detect            ERROR   : [h264 @ 0x556999e8ba80] no frame!
frigate          | ffmpeg.wyze2.detect            ERROR   : Input #0, rtsp, from 'rtsp://xxx:xxx@192.168.1.250:8554/unicast':
frigate          | ffmpeg.wyze2.detect            ERROR   :   Metadata:
frigate          | ffmpeg.wyze2.detect            ERROR   :     title           : LIVE555 Streaming Media v2020.05.15
frigate          | ffmpeg.wyze2.detect            ERROR   :     comment         : LIVE555 Streaming Media v2020.05.15
frigate          | ffmpeg.wyze2.detect            ERROR   :   Duration: N/A, start: 1609381051.737833, bitrate: N/A
frigate          | ffmpeg.wyze2.detect            ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 25 fps, 15.17 tbr, 90k tbn, 50 tbc
frigate          | ffmpeg.wyze2.detect            ERROR   : Output #0, flv, to 'rtmp://127.0.0.1/live/wyze2':
frigate          | ffmpeg.wyze2.detect            ERROR   :   Metadata:
frigate          | ffmpeg.wyze2.detect            ERROR   :     title           : LIVE555 Streaming Media v2020.05.15
frigate          | ffmpeg.wyze2.detect            ERROR   :     comment         : LIVE555 Streaming Media v2020.05.15
frigate          | ffmpeg.wyze2.detect            ERROR   :     encoder         : Lavf58.45.100
frigate          | ffmpeg.wyze2.detect            ERROR   :     Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 15.17 tbr, 1k tbn, 90k tbc
frigate          | ffmpeg.wyze2.detect            ERROR   : Stream mapping:
frigate          | ffmpeg.wyze2.detect            ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate          | ffmpeg.wyze2.detect            ERROR   :   Stream #0:0 -> #1:0 (h264 (native) -> rawvideo (native))
frigate          | ffmpeg.wyze2.detect            ERROR   : Press [q] to stop, [?] for help
frigate          | ffmpeg.wyze2.detect            ERROR   : Output #1, rawvideo, to 'pipe:':
frigate          | ffmpeg.wyze2.detect            ERROR   :   Metadata:
frigate          | ffmpeg.wyze2.detect            ERROR   :     title           : LIVE555 Streaming Media v2020.05.15
frigate          | ffmpeg.wyze2.detect            ERROR   :     comment         : LIVE555 Streaming Media v2020.05.15
frigate          | ffmpeg.wyze2.detect            ERROR   :     encoder         : Lavf58.45.100
frigate          | ffmpeg.wyze2.detect            ERROR   :     Stream #1:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, q=2-31, 373248 kb/s, 15 fps, 15 tbn, 15 tbc
frigate          | ffmpeg.wyze2.detect            ERROR   :     Metadata:
frigate          | ffmpeg.wyze2.detect            ERROR   :       encoder         : Lavc58.91.100 rawvideo
frigate          | frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate          | frigate.edgetpu                INFO    : TPU found
frigate          | ffmpeg.wyze2.detect            ERROR   : frame=   15 fps=0.0 q=-1.0 q=-0.0 size=     104kB time=00:00:01.91 bitrate= 442.3kbits/s speed=3.73x    
frigate          | ffmpeg.wyze2.detect            ERROR   : frame=   23 fps= 22 q=-1.0 q=-0.0 size=     119kB time=00:00:02.44 bitrate= 398.1kbits/s speed=2.36x    
frigate          | ffmpeg.wyze2.detect            ERROR   : frame=   31 fps= 20 q=-1.0 q=-0.0 size=     205kB time=00:00:02.97 bitrate= 565.4kbits/s speed= 1.9x    
frigate          | ffmpeg.wyze2.detect            ERROR   : frame=   39 fps= 19 q=-1.0 q=-0.0 size=     220kB time=00:00:03.49 bitrate= 514.7kbits/s speed=1.67x    
frigate          | ffmpeg.wyze2.detect            ERROR   : frame=   47 fps= 18 q=-1.0 q=-0.0 size=     232kB time=00:00:04.02 bitrate= 471.2kbits/s speed=1.53x    
frigate          | ffmpeg.wyze2.detect            ERROR   : frame=   55 fps= 17 q=-1.0 q=-0.0 size=     328kB time=00:00:04.56 bitrate= 589.1kbits/s speed=1.44x    
```

**Frigate debug stats**
```json
{"detection_fps":1.8,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.22,"pid":49}},"wyze2":{"camera_fps":15.1,"capture_pid":53,"detection_fps":1.8,"pid":52,"process_fps":15.1,"skipped_fps":0.0}}
```

**FFprobe from your camera**

Run the following command and paste output below
```bash
docker exec -it frigate bash     
root@3b86a43b04f1:/opt/frigate# ffprobe rtsp://xxx:xxx@192.168.1.250:8554/unicast
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x560478e76b00] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x560478e76b00] decode_slice_header error
[h264 @ 0x560478e76b00] no frame!
[h264 @ 0x560478e76b00] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x560478e76b00] decode_slice_header error
[h264 @ 0x560478e76b00] no frame!
Input #0, rtsp, from 'rtsp://xxx:xxx@192.168.1.250:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 0.594011, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 25 fps, 15.17 tbr, 90k tbn, 50 tbc
```

**Screenshots**
![Screenshot from 2020-12-30 18-02-34](https://user-images.githubusercontent.com/1900655/103390934-cc387280-4acb-11eb-94c8-02a0eae5c751.png)

**Computer Hardware**
 - OS: Ubuntu
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Wyzecam V2
 - Model: Dafang
 - Resolution: 1920
 - FPS: 15

**Additional context**
This problem persists across numerous makes and models of camera that all work with the .7 branch.

**Comment by ghettodev** [comment]
Docker compose:

```yaml
   frigate:
     container_name: frigate
     restart: unless-stopped
     privileged: true
     shm_size: '512m'
     #image: blakeblackshear/frigate:stable-amd64
     image: blakeblackshear/frigate:0.8.0-beta3-amd64
     volumes:
       - /dev/bus/usb:/dev/bus/usb
       - /etc/localtime:/etc/localtime:ro
       - /media/docker/frigate2/config:/config
       - /media/docker/frigate2/clips:/media/frigate/clips
       - /media/docker/frigate2/recordings:/media/frigate/recordings
       - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
         target: /tmp/cache
         tmpfs:
           size: 200000000
     ports:
       - "5000:5000"
       - "1935:1935" # RTMP feeds
     environment:
       FRIGATE_RTSP_PASSWORD: "password"
       LIBVA_DRIVER_NAME: "iHD"
     healthcheck:
       test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
       interval: 30s
       timeout: 10s
       retries: 5
       start_period: 3m
```
