### ISSUE TITLE
[Support]: Wrong time stamp on event

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#4563]
### Describe the problem you are having

The time stamp on the even is wrong and different from the time stamp on the camera feed (which is the correct time)

### Version

0.11.1-2eada21

### Frigate config file

```yaml
# frigate.yml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: caha.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: Fr1g@te21
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
rtmp:
  enabled: false

motion:
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 80
  threshold: 25
  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  
cameras:
  driveway:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 95,38,317,64,640,130,640,0,0,0,0,42
#          min_score: 0.49
#          threshold: 0.54
#          min_area: 1000
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@ip140/2
          roles:
            - detect
        - path: rtsp://admin:pass@ip140/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 5  
    motion:
      mask:
        - 95,38,317,64,640,130,640,0,0,0,0,42         
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#    clips:
#      enabled: true
#      retain:
#        default: 5
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True      
      retain:
        default: 7
################################################ 
  front_porch_camera:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@ip141/2
          roles:
            - detect
        - path: rtsp://admin:pass@ip141/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 5  
    motion:
      mask:
        - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True      
      retain:
        default: 7
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Chortau

### Any other information that may be helpful

![image](https://user-images.githubusercontent.com/75389943/204877188-9ba0c83c-74c5-4465-be0f-4be204a3641d.png)
