### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by pvillanyi** [blakeblackshear/frigate#4564]
### Describe the problem you are having

Frigatte integration stopped working today in the morning.
I saw, the add-on had an update. I've installed it, but it's not working.
The add-on works. Frigatte sees the cameras, detects the person, but doesn't deliver it to HA Integration.

### Version

0.11.1

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
mqtt:
  host: 192.168.0.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: ******
  stats_interval: 60

cameras:
  door:
    ffmpeg:
#      hwaccel_args:
#        - -c:v
#        - h264_v4l2m2m
      inputs:
        - path: rtsp://192.168.0.xxx:554/live/ch00_0
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 4
    motion:
      mask:
        - 1666,0,1920,0,1920,1080,1570,1080,1568,783
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.7
          threshold: 0.75
          max_ratio: 0.8
          min_area: 9000
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 5
        objects:
          person: 15
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 5


  
  terase:
    ffmpeg:
#      hwaccel_args:
#        - -c:v
#        - h264_v4l2m2m
      inputs:
        - path: rtsp://192.168.0.xxx:554/live/ch00_0
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.7
          threshold: 0.75
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 5
        objects:
          person: 15
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 5

  garden:
    ffmpeg:
#      hwaccel_args:
#        - -c:v
#        - h264_v4l2m2m
      inputs:
        - path: rtsp://192.168.0.xxx:554/live/ch00_1
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 4
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.75
          threshold: 0.76
          max_ratio: 0.8
        object_0:
          mask: 166,275,210,275
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      height: 175
      required_zones: []
      retain:
        default: 5
        objects:
          person: 15
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 5
```

### Relevant log output

```shell
Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:51
Integration: Frigate (documentation, issues)
First occurred: 19:09:53 (12 occurrences)
Last logged: 19:16:50

Error fetching information from http://192.168.0.200:5000/api/stats: Cannot connect to host 192.168.0.200:5000 ssl:default [Connect call failed ('192.168.0.200', 5000)]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

It worked stable for months without changes
