### ISSUE TITLE
[Support]: outdated stable-amd64 tag works better than stable tag.

### ISSUE THREAD

**Issue by short-circuit** [blakeblackshear/frigate#4571]
### Describe the problem you are having

I have a Dafang camera. This works with Frigate perfectly when run with the outdated docker image `stable-amd64` (has not been updated in months).
Switching to the `stable` tag makes everything stop working. FFmpeg not starting anymore, green screen, no way of fixing apart from switching back to older tag `stable-amd64`.

Can someone help me out here and let me know why this happens?

### Version

-

### Frigate config file

```yaml
mqtt:
  host: [REDACTED]
  port: [REDACTED]
  topic_prefix: frigate
  client_id: frigate
  user: [REDACTED]
  password: [REDACTED]

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv

record:
  enabled: true
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    required_zones: []
    retain:
      default: 10

cameras:
  livingroomcam:
    ffmpeg:
      inputs:
        - path: rtsp://[REDACTED]
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      retain:
        default: 10

objects:
  track:
    - person

detectors:
  coral:
    type: edgetpu
    device: usb

```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Dafang
