### ISSUE TITLE
[Config Support]: Unraid: Frigate docker + HA VM with Proxy addon (notification images problem)

### ISSUE THREAD

**Issue by Zelete** [blakeblackshear/frigate#4580]
### Describe the problem you are having

I have researched this issue but I couldn't find any relevant solutions to this. I am coming from a simpler VirtualBox setup (where notification images were working) and have migrated to Unraid, which is running Frigate in a docker container since this allows for GPU passthrough.

Home Assistant is running as a VM in Unraid, and is running the Frigate Proxy addon which is connected to that docker.

So basically the issue is that notifications itself are working, but my images do not load.
![image](https://user-images.githubusercontent.com/6378878/205442437-5232026b-438d-4254-ba3e-6ba5d8262efe.png)

The address to the image is the following:
https://00kcdxxxxxxxxxxxmj3jwmynq.ui.nabu.casa/api/frigate/notifications/1670072470.046729-qejodk/thumbnail.jpg
(I use Nabu Casa)

I figured this must be because the snapshots and recordings reside on the docker container, and are inaccessible by the HA VM. Does the Frigate Proxy addon not handle this? Is there any solution?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.21.3
  port: 1883
  user: homeassistant
  password: xxxxx

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: False
  
record:
  enabled: True
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects
      
objects:
  track:
    - person
    - cat
    - bicycle
    - car

snapshots:
  enabled: True
  clean_copy: False
  timestamp: True
  bounding_box: True
  crop: False
  retain:
    default: 10
    objects:
      person: 15

cameras:

#################### Living ####################

  living:
    
    record:
        events:
            required_zones:
                - computer
                - woonkamer
                
    snapshots:
        required_zones:
            - computer
            - woonkamer

    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://admin:xxxxx@192.168.19.101:554/Streaming/Channels/101?transportmode=multicast&profile=Profile_1
          roles:
            - detect
            - record
        
    rtmp:
        enabled: False
    
    detect:
        width: 2560
        height: 1440
        fps: 15

    zones:
        computer:
            coordinates: 2055,1386,2262,1004,1901,808,1596,1008,1597,1110
            objects:
                - person
                - cat
        woonkamer:
            coordinates: 403,1440,183,840,729,503,1085,439,1283,529,1221,1440
            objects:
                - person

    objects:
        filters:
            person:
                mask:
                    - 1327,272,1460,312,1483,57,1345,38

#################### Buiten ####################

  buiten:

    record:
        events:
            required_zones:
                - terras
                - tuin
                
    snapshots:
        required_zones:
            - terras
            - tuin

    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://admin:xxxxx@192.168.19.102:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
          roles:
            - detect
            - record
            - rtmp

    rtmp:
        enabled: False
    
    detect:
        width: 2560
        height: 1440
        fps: 15

    motion:
        mask:
            - 554,145,548,0,320,26,335,162
            - 2560,381,2560,0,1701,0,1705,115

    zones:
        terras:
            coordinates: 1014,1440,0,1440,0,845,505,624,1241,1032,2187,1440
            objects:
                - person
                - cat

        tuin:
            coordinates: 910,324,437,401,0,514,58,695,548,501,2281,1204,2417,805
            objects:
                - person
                - cat
                - bicycle
                
        speeltuin:
            coordinates: 2418,792,2496,494,1693,262,948,322
            objects:
                - person
                - cat

#################### Deurbel ####################

  deurbel:

    record:
        events:
            required_zones:
                - oprit
                - tuin

    snapshots:
        required_zones:
            - oprit
            - tuin

    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_cuvid
      inputs:
        - path: rtsp://admin:xxxxx@192.168.17.147:8554/Streaming/Channels/101
          roles:
            - detect
            - record

    rtmp:
        enabled: False
    
    detect:
        width: 1280
        height: 720
        fps: 10

    objects:
        filters:
            person:
                mask:
                    - 311,562,390,563,390,422,307,422

    motion:
        mask:
            - 339,460,656,450,1003,416,1280,378,1280,0,0,0,0,453

    zones:
        tuin:
            coordinates: 1280,720,326,720,206,610,264,556,644,548,845,527,1280,427
            objects:
                - person
                - cat
                - bicycle
                - car
        oprit:
            coordinates: 0,720,0,531,238,551,179,619,304,720
            objects:
                - person
                - cat
                - bicycle
                - car
        straat:
            coordinates: 561,462,1029,421,1280,382,1280,407,1142,433,594,503,249,505,0,491,0,456
            objects:
                - car
```

### Relevant log output

```shell
/
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB
