### ISSUE TITLE
[Support]: Receive occupancy events in HA without storing recorded clips

### ISSUE THREAD

**Issue by Jleagle** [blakeblackshear/frigate#4589]
### Describe the problem you are having

I have been detecting dog objects fine and it records clips for 2 days, i use the event in Home Assistant and the occupancy value.

I want to receive these events for people object too, but i don't want to store recorded clips. It seems when i set that to 0 days it does not send the events to HA either?

Thanks.

### Version

blakeblackshear/frigate:stable-amd64

### Frigate config file

```yaml
# https://docs.frigate.video/configuration/index

mqtt:
  host: 192.168.0.7

birdseye:
  enabled: false
  mode: motion

ffmpeg:
  # https://docs.frigate.video/configuration/hardware_acceleration
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

objects:
  track:
    - dog
    - person

record:
  enabled: true
  events:
    retain:
      mode: active_objects
      objects:
        dog: 2
        person: 0

cameras:
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_KITCHEN_USERNAME}:{FRIGATE_KITCHEN_PASSWORD}@192.168.0.12:10554/tcp/av0_1
          roles:
            - detect
            - rtmp
        - path: rtsp://{FRIGATE_KITCHEN_USERNAME}:{FRIGATE_KITCHEN_PASSWORD}@192.168.0.12:10554/tcp/av0_0
          roles:
            - record
    detect:
      width: 1024
      height: 576
      fps: 10
  dining:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_DINING_USERNAME}:{FRIGATE_DINING_PASSWORD}@192.168.0.14/stream2
          roles:
            - detect
            - rtmp
        - path: rtsp://{FRIGATE_DINING_USERNAME}:{FRIGATE_DINING_PASSWORD}@192.168.0.14/stream1
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10

detectors:
  coral:
    type: edgetpu
    device: pci
    num_threads: 3
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

n/a
