### ISSUE TITLE
[Support]: Firgate Keeps Crashing Unraid

### ISSUE THREAD

**Issue by austindetzel** [blakeblackshear/frigate#4591]
### Describe the problem you are having

Frigate keeps crashing after an update, these are the only logs I get. This is on Unraid.

### Version

Latest (Fresh new Install)

### Frigate config file

```yaml
mqtt:
  host: 192.168.40.10
  port: 1883


record:
    enabled: True
    retain:
        days: 14
        mode: all
    events:
        retain:
            default: 28
            mode: motion 

detect:
  enabled: True
            
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - dog
    - bird
    
                    
cameras:
    Front_Door:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.22/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - rtmp
                    - detect
                - path: rtsp://admin:redacted@192.168.40.22/cam/realmonitor?channel=1&subtype=0 # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
            
    Front_Yard:
        ffmpeg:
            inputs:
                - path: rtsp://admin:redacted@192.168.40.23/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - rtmp
                    - detect
                - path: rtsp://admin:redacted@192.168.40.23/cam/realmonitor?channel=1&subtype=0 # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
            
    Shed_Camera:
        ffmpeg:
            input_args:
             - -c:v
             - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.21/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - rtmp
                    - detect
                - path: rtsp://admin:redacted@192.168.40.21/cam/realmonitor?channel=1&subtype=0 # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 704 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
            
            
    Driveway_Doorbell:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.24/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - detect
                    - rtmp
                - path: rtsp://admin:redacted@192.168.40.24/cam/realmonitor?channel=1&subtype=0 # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
            
    Living_Room:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.20/live
                  roles:
                    - detect
                    - rtmp
                    - record
        #detect:
        #    width: 1920 # <---- update for your camera's resolution
        #    height: 1080 # <---- update for your camera's resolution
            
    Barn:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.25:554/h264Preview_01_sub
                  roles:
                    - detect
                - path: rtsp://admin:redacted@192.168.40.25:554/h264Preview_01_main # <----- Add high res stream
                  roles:
                    - rtmp
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
            
    Septic_Shed:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.26:554/h264Preview_01_sub
                  roles:
                    - rtmp
                    - detect
                - path: rtsp://admin:redacted@192.168.40.26:554/h264Preview_01_main # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
            
    Septic_Driveway:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.28:554/h264Preview_01_sub
                  roles:
                    - rtmp
                    - detect
                - path: rtsp://admin:redacted@192.168.40.28:554/h264Preview_01_main # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 352 # <---- update for your camera's resolution
            
    Septic_Inside:
        ffmpeg:
            input_args:
            - -c:v
            - h264_cuvid
            inputs:
                - path: rtsp://admin:redacted@192.168.40.27:554/h264Preview_01_sub
                  roles:
                    - rtmp
                    - detect
                - path: rtsp://admin:redacted@192.168.40.27:554/h264Preview_01_main # <----- Add high res stream
                  roles:
                    - record
        #detect:
        #    width: 640 # <---- update for your camera's resolution
        #    height: 480 # <---- update for your camera's resolution
```

### Relevant log output

```shell
[2022-12-03 20:37:19] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2022-12-03 20:37:20] peewee_migrate                 INFO    : Starting migrations
Migrate "011_update_indexes"
[2022-12-03 20:37:21] peewee_migrate                 INFO    : Migrate "011_update_indexes"
sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
[2022-12-03 20:37:21] peewee_migrate                 INFO    : sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
sql ('DROP INDEX recordings_start_time_end_time',)
[2022-12-03 20:37:21] peewee_migrate                 INFO    : sql ('DROP INDEX recordings_start_time_end_time',)
sql ('CREATE INDEX "recordings_end_time_start_time" ON "recordings" ("end_time" DESC, "start_time" DESC)',)
[2022-12-03 20:41:14] peewee_migrate                 INFO    : sql ('CREATE INDEX "recordings_end_time_start_time" ON "recordings" ("end_time" DESC, "start_time" DESC)',)
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
Unavailable
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest,Reolink

### Any other information that may be helpful

Frigate updated, and now It is erroring out.
