### ISSUE TITLE
[Config Support]: Motion Detection disable

### ISSUE THREAD

**Issue by 1990marco1990** [blakeblackshear/frigate#4619]
### Describe the problem you are having

Hello,

I would disable the Motion detection of my Cameras because It used many CPU. Have change the switch in Hommeassistant but the switch goes on back alone. Can anyone help? Can I disable it with the frigate.yml?

Also I would used it to light on if a person ist detect. I have do a Nodered Flow but its very slow. I must wait 5 sec till the lights go on.  Can I make the detection faster?

Also the Clips did not work on the Android Smartphone App. It load but nothing do on the Computer it looks well.

I have a Reolink Duo 2. There the Detection only works if I go in front of the Camera. If I go 5 meter away nothing would detect. 

Thanks for your help.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt   
  password: 
  port: 1883

database:
  path: /media/frigate/frigate.db
  
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: True
  mode: continuous
    
cameras:
  Kamera_HWR:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.31.230:554/stream0?username=admin&password=
          roles:
            - detect
            - clips
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
  Kamera_Tuerklingel:
    motion:
      mask: 
       - 203,274,640,283,640,155,0,149,0,216,0,302
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.31.242/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.31.242/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    snapshots:
      enabled: True
      required_zones:
        - Home
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10    
        required_zones:
          - Home
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
    zones:
      Home:
        coordinates: 640,480,640,292,454,265,302,284,180,278,0,303,0,480
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
  Kamera_Schuppen:
    motion:
      mask:
        - 0,0,263,0,447,0,482,78,394,123,0,576
        - 1340,245,972,47,960,0,1536,0,1536,576
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 1536
      height: 576
      fps: 7

    snapshots:
      enabled: True
      required_zones:
        - Schuppen_Grundstueck
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10    
        required_zones:
          - Schuppen_Grundstueck
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
    zones:
      Schuppen_Grundstueck:
        coordinates: 0,576,388,102,474,80,466,27,864,0,1005,61,1315,227,1536,576
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
```

### Relevant log output

```shell
[2022-12-06 19:46:12] ffmpeg.Kamera_Schuppen.record_rtmp ERROR   : http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=: Connection timed out
[2022-12-06 19:46:12] ffmpeg.Kamera_Schuppen.record_rtmp ERROR   : [flv @ 0x55a4e6aec0] Failed to update header with correct duration.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
