### ISSUE TITLE
[Camera Support]: Snapshots / Event Images save at lower resolution than camera stream. (4k resolution downscaled to 1280x720 image)

### ISSUE THREAD

**Issue by Michael-Loia** [blakeblackshear/frigate#4627]
### Describe the problem you are having

I have a 4K camera, however the images saved for the Snapshots / Event Images are saved at a resolution of 1280x720. The files are saved to the "\frigate\clips\" folder. In there I see png and jpg files, they both have the resolution of 1280x720. How can I get the 4K images that the camera is capable of?

It does not appear to downgrade the recorded video:
![image](https://user-images.githubusercontent.com/62631007/206091896-dce70970-47e5-4076-a901-40bfa40a24bb.png)

However the image resolution is far smaller:

Png:
![image](https://user-images.githubusercontent.com/62631007/206091552-ee3be40b-245c-4388-88b3-b35a80b7e728.png)

Jpg:
![image](https://user-images.githubusercontent.com/62631007/206091480-8f47c458-0103-4be4-aa36-80757fe88eab.png)

Summary: 
How to get Snapshots / Event Images to be saved as the highest capable resolution by camera as opposed to being downscaled to 1280x720.

Any and all feedback would be greatly appreciated.

Best,
Michael

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
    host: XXX
    port: XXX
    topic_prefix: XXX
    client_id: XXX
    user: XXX
    password: XXX
  

  detectors:
    coral:
      type: edgetpu
      device: usb

  birdseye:
    enabled: True
    mode: continuous
  
  ffmpeg:
    hwaccel_args: -c:v h264_cuvid
    output_args:
      record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  detect:
    fps: 15
    enabled: True
    max_disappeared: 75
    stationary:
      interval: 5
      threshold: 150
      max_frames:
        default: 3000
        objects:
          person: 1000

  objects:
    track:
      - person
    filters:
      person:
        min_score: 0.5
        threshold: 0.7
        
  motion:
    contour_area: 25
  
  record:
    enabled: true
    retain:
      days: 0
      mode: all
  
    events:
      pre_capture: 60
      post_capture: 60
      objects:
        - person
      required_zones: []
      retain:
        default: 7
        mode: all
        objects:
          person: 7
  
  snapshots:
    enabled: True
    clean_copy: True
    timestamp: True
    bounding_box: True
    crop: False
    required_zones: []
    retain:
      default: 7
      objects:
        person: 7
  
  rtmp:
    enabled: True
  live:
    height: 720
    quality: 5
  timestamp_style:
    position: "tl"
    format: "%m/%d/%Y %-I:%M:%S %p"
    color:
      red: 255
      green: 255
      blue: 255
    thickness: 2
    effect: shadow
  
  cameras:
    side_door:
      ffmpeg:
        inputs:
          - path: rtsp://XXX:XXX@XXX:XXX/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
              - record

      mqtt:
        enabled: True
        timestamp: True
        bounding_box: True
        crop: False
        quality: 100
        required_zones: []
```

### Relevant log output

```shell
Not applicable
```

### FFprobe output from your camera

```shell
Not applicable
```

### Frigate stats

```json
Not applicable
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest 4K Outdoor Security IP Turret PoE Camera IP67

**Comment by NickM-27** [comment]
The snapshots come from the detect stream, this is working as expected. There's a pinned request to add a snapshots role though there are a number of difficulties. 

Recommend reading https://github.com/blakeblackshear/frigate/issues/2199 for more info.

**Comment by Michael-Loia** [comment]
Thank You Both for your time and prompt response. That worked perfectly; The images are now saved at the resolution set for _detect_.

**For those following along:** 
By setting a resolution in _detect_, the Snapshots / Event images will save at the same resolution.

Before (Automatically Detected Resolution):
```
  camera_name:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@ip_address:port/your_path
          roles:
            - detect
            - record
```      
This configuration would have Frigate autodetect the camera's resolution and use that to record. However, for _detect_, Frigate resizes to the default resolution of 720p (As Mentioned By Blake), Causing the images to be saved at that default resolution of 1280x720. (This is likely done for better performance)
![image](https://user-images.githubusercontent.com/62631007/206327663-8bb9c39a-402c-4ab1-a4ed-3a13a9881a9a.png)

==========

After (Manually Set Resolution):
```
  camera_name:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@ip_address:port/your_path
          roles:
            - detect
            - record
    detect:
      width: 3840
      height: 2160
      fps: 15
``` 
![image](https://user-images.githubusercontent.com/62631007/206327392-c3180c7f-4a43-4a21-b7d4-b3e1ddb3a764.png)
This configuration would have Frigate autodetect the camera's resolution and use that to record. However, for _detect_, We manually set the resolution (width, height, and fps). Now the images are saved at our set resolution, in this case, 3840x2160. Remember to use your camera's resolution and fps; Ours may vary.
