### ISSUE TITLE
[Support]: In Progress Configuration Help

### ISSUE THREAD

**Issue by BoostN** [blakeblackshear/frigate#4632]
### Describe the problem you are having

I'm having an issues with consistent driveway car alerting. It seems I don't get the events at all, or if I do I get a "In Progress" one stuck for hours. Currently I come home from lunch and parked, and the event is still in progress. Any tips here? 

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: *************
  user: m*********
  password: *********
  
  
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
      global_args: -hide_banner -loglevel debug
      input_args: >-
        -an
  
cameras:
  Outside_Driveway: # <------ Name the camera  
    ffmpeg:        
      inputs:
        - path: rtsps://***************************** # <----- Update for your camera
          roles:
            - detect
            - rtmp       
    motion:
      mask:
        - 1002,45,290,23,323,0,604,0,790,0,923,0
        - 0,244,258,122,340,84,422,66,482,48,549,0,143,0,0,60,0,204
      
    zones:
      driveway_end:
        coordinates: 372,373,239,309,402,234,449,207,580,148,755,186,1011,231,980,338
        
      driveway_entry:
        coordinates: 472,91,636,146,912,203,933,44,798,21
        
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 3
      
    snapshots:
      required_zones:
        - driveway_entry
      
    objects:
      track:
        - person
        - car
        - motorcycle
      filters:
        car:
          # Optional: minimum width*height of the bounding box for the detected object. Vorher: 5000. Default 0
          min_area: 22000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          #max_area: 0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.2
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.5
          mask: 125,212,169,284,362,345,668,225,564,127,407,69,262,97
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"Back_Porch":{"camera_fps":3.0,"capture_pid":240,"detection_fps":0.0,"pid":226,"process_fps":3.0,"skipped_fps":0.0},"Front_Doorbell":{"camera_fps":3.0,"capture_pid":232,"detection_fps":0.0,"pid":225,"process_fps":3.0,"skipped_fps":0.0},"Int_Garage":{"camera_fps":3.0,"capture_pid":229,"detection_fps":0.0,"pid":223,"process_fps":3.0,"skipped_fps":0.0},"Living_Room":{"camera_fps":3.0,"capture_pid":230,"detection_fps":3.0,"pid":224,"process_fps":3.0,"skipped_fps":0.0},"Outside_Driveway":{"camera_fps":3.1,"capture_pid":227,"detection_fps":0.0,"pid":222,"process_fps":3.1,"skipped_fps":0.0},"detection_fps":3.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.55,"pid":211}},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":60.0,"mount_type":"tmpfs","total":67.1,"used":7.1},"/media/frigate/clips":{"free":94868.7,"mount_type":"ext4","total":105089.3,"used":4835.0},"/media/frigate/recordings":{"free":94868.7,"mount_type":"ext4","total":105089.3,"used":4835.0},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":7348,"version":"0.11.1-2eada21"}}
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

UniFi Protect G4

### Any other information that may be helpful
Live Debug Picture
https://drive.google.com/file/d/1zdwYo_lHJBLghL3B3HXVMqiTDP_l8AwT/view?usp=sharing

_No response_
