### ISSUE TITLE
[Support]: Unable to rename count entities

### ISSUE THREAD

**Issue by chrisdrackett** [blakeblackshear/frigate#4645]
### Describe the problem you are having

To match the name format I use in the rest of my HASS install I wanted to rename the entities in frigate from `sensor.backyard_cat_count` to `sensor.count_cat_backyard`. I went ahead and changed them all last night. This morning while the occupancy entities kept the new names (`binary_sensor.occupancy_dog_backyard`) the count ones somehow have reverted to their old names. I tried to change them again this morning but found they somehow went back again.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.190:5000/api/config/schema

mqtt:
  host: <host>
  user: <user>
  password: <pass>
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac
  input_args: -fflags nobuffer -rtsp_transport tcp
  hwaccel_args: -c:v h264_qsv
detectors:
  coral:
    type: edgetpu
    device: usb
snapshots:
  enabled: true
  retain:
    default: 360
cameras:
  dining:
    objects:
      track:
        - dog
        - person
        - cat
    ffmpeg:
      inputs:
        - path: <url>
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
  # and so on for 10 more cameras..
```

### Relevant log output

```shell
unknown
```

### FFprobe output from your camera

```shell
not relevant I believe
```

### Frigate stats

```json
{"backYard":{"camera_fps":2.7,"capture_pid":294,"detection_fps":0.0,"pid":252,"process_fps":2.7,"skipped_fps":0.0},"carport":{"camera_fps":2.8,"capture_pid":278,"detection_fps":0.0,"pid":247,"process_fps":2.8,"skipped_fps":0.0},"chickenCoop":{"camera_fps":5.1,"capture_pid":300,"detection_fps":1.3,"pid":254,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":1.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":14.35,"pid":232}},"dining":{"camera_fps":5.1,"capture_pid":259,"detection_fps":0.0,"pid":240,"process_fps":5.1,"skipped_fps":0.0},"frontDoor":{"camera_fps":4.9,"capture_pid":284,"detection_fps":0.0,"pid":249,"process_fps":4.9,"skipped_fps":0.0},"frontYard":{"camera_fps":2.8,"capture_pid":306,"detection_fps":0.0,"pid":256,"process_fps":2.8,"skipped_fps":0.0},"garage":{"camera_fps":5.0,"capture_pid":272,"detection_fps":0.0,"pid":245,"process_fps":5.0,"skipped_fps":0.0},"laundry":{"camera_fps":5.2,"capture_pid":324,"detection_fps":0.0,"pid":257,"process_fps":5.2,"skipped_fps":0.0},"living":{"camera_fps":1.67,"capture_pid":263,"detection_fps":0.0,"pid":242,"process_fps":2.4,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":16646.7,"mount_type":"tmpfs","total":16685.9,"used":39.3},"/media/frigate/clips":{"free":55300.1,"mount_type":"ext4","total":491499.9,"used":415269.6},"/media/frigate/recordings":{"free":55300.1,"mount_type":"ext4","total":491499.9,"used":415269.6},"/tmp/cache":{"free":16685.9,"mount_type":"tmpfs","total":16685.9,"used":0.0}},"temperatures":{},"uptime":40849,"version":"0.11.1-2eada21"},"stable":{"camera_fps":2.7,"capture_pid":267,"detection_fps":0.0,"pid":244,"process_fps":2.7,"skipped_fps":0.0},"stableDoor":{"camera_fps":5.1,"capture_pid":288,"detection_fps":0.0,"pid":250,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi Protect
