### ISSUE TITLE
[Camera Support]: 2nd identical camera doesn't work

### ISSUE THREAD

**Issue by blacknell** [blakeblackshear/frigate#4652]
### Describe the problem you are having

I've just added a second identical camera to my frigate set up and it's not working. The streams work fine on VLC - see end of issue below

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
ui:
  use_experimental: true

database:
  path: /media/frigate/frigate.db

logger:
  default: info
  logs:
    frigate.event: debug

cameras:
  front_door:
    zones:
      street:
        coordinates: 572,0,557,120,410,93,414,0
        objects:
          - car
          - person
      driveway:
        coordinates: 919,128,849,373,757,540,573,540,275,360,296,339,254,84,403,56,422,101,541,120,599,73
        objects:
          - person
          - car
        filters:
          car:
            min_area: 50000
      porch:
        coordinates: 305,540,547,540,259,359,287,339,245,0,0,0,0,540
        objects:
          - person
    motion:
      mask:
        - 935,45,935,21,855,21,854,45
    ffmpeg:
      inputs:
        - path: rtsp://stream:REDACTED@192.168.100.61/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://stream:REDACTED@192.168.100.61/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect



  back_garden:
    ffmpeg:
      inputs:
        - path: rtsp://stream:REDACTED@192.168.100.74/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://stream:REDACTED@192.168.100.74/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      patio:
        coordinates: 0,0,960,0,960,540,0,540
        objects:
          - person

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
detect:
  width: 960
  height: 540
  fps: 15

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

rtmp:
  enabled: false

birdseye:
  enabled: false

live:
  height: 576
  quality: 1

mqtt:
  host: 192.168.100.23
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: REDACTED

detectors:
#  cpu1:
#    type: cpu
#    num_threads: 4
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - car

record:
  enabled: true
  events:
    pre_capture: 2
    post_capture: 2
    retain:
      default: 14

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 14
    objects:
      person: 28
```

### Relevant log output

```shell
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-12-09 11:59:36] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2022-12-09 11:59:36] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-12-09 11:59:36] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-12-09 11:59:36] frigate.app                    INFO    : Output process started: 217
frigate  | [2022-12-09 11:59:36] ws4py                          INFO    : Using epoll
frigate  | [2022-12-09 11:59:36] frigate.app                    INFO    : Camera processor started for front_door: 223
frigate  | [2022-12-09 11:59:36] frigate.app                    INFO    : Camera processor started for back_garden: 226
frigate  | [2022-12-09 11:59:36] frigate.app                    INFO    : Capture process started for front_door: 228
frigate  | [2022-12-09 11:59:36] frigate.app                    INFO    : Capture process started for back_garden: 230
frigate  | [2022-12-09 11:59:37] ws4py                          INFO    : Using epoll
frigate  | [2022-12-09 11:59:36] detector.coral                 INFO    : Starting detection process: 216
frigate  | [2022-12-09 11:59:36] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-12-09 11:59:39] frigate.edgetpu                INFO    : TPU found
frigate  | [2022-12-09 11:59:47] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56380]
frigate  | [2022-12-09 11:59:57] watchdog.back_garden           INFO    : No frames received from back_garden in 20 seconds. Exiting ffmpeg...
frigate  | [2022-12-09 11:59:57] watchdog.back_garden           INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | [2022-12-09 12:00:27] watchdog.back_garden           INFO    : FFmpeg didnt exit. Force killing...
frigate  | [2022-12-09 12:00:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:00:27] frigate.video                  ERROR   : back_garden: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-12-09 12:00:37] watchdog.back_garden           ERROR   : Ffmpeg process crashed unexpectedly for back_garden.
frigate  | [2022-12-09 12:00:37] watchdog.back_garden           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-12-09 12:00:57] watchdog.back_garden           INFO    : No frames received from back_garden in 20 seconds. Exiting ffmpeg...
frigate  | [2022-12-09 12:00:57] watchdog.back_garden           INFO    : Waiting for ffmpeg to exit gracefully...
frigate  | [2022-12-09 12:01:05] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56380]
frigate  | [2022-12-09 12:01:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57696]
frigate  | [2022-12-09 12:01:10] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:33208]
frigate  | [2022-12-09 12:01:13] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:33208]
frigate  | [2022-12-09 12:01:15] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:33224]
frigate  | [2022-12-09 12:01:16] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:33224]
frigate  | [2022-12-09 12:01:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:37134]
frigate  | [2022-12-09 12:01:22] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:37134]
frigate  | [2022-12-09 12:01:23] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:37146]
frigate  | [2022-12-09 12:01:27] watchdog.back_garden           INFO    : FFmpeg didnt exit. Force killing...
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: Unable to read frames from ffmpeg process.
frigate  | [2022-12-09 12:01:27] frigate.video                  ERROR   : back_garden: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
NON WORKING CAMERA
ffprobe rtsp://stream:REDACTED@192.168.100.74/cam/realmonitor?channel=1&subtype=0
[1] 72619
pi@frigatepi:~ $ ffprobe version 4.3.5-0+deb11u1+rpt2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt2 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55aa92d870] method DESCRIBE failed: 404 Not Found
rtsp://stream:REDACTED@192.168.100.74/cam/realmonitor?channel=1: Server returned 404 Not Found


WORKING CAMERA
ffprobe rtsp://stream:REDACTED@192.168.100.61/cam/realmonitor?channel=1&subtype=0

ffprobe version 4.3.5-0+deb11u1+rpt2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt2 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x557d795870] method DESCRIBE failed: 404 Not Found
rtsp://stream:REDACTED@192.168.100.61/cam/realmonitor?channel=1: Server returned 404 Not Found
```

### Frigate stats

```json
{"back_garden":{"camera_fps":0.0,"capture_pid":230,"detection_fps":0.0,"pid":226,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":16.25,"pid":216}},"front_door":{"camera_fps":15.0,"capture_pid":228,"detection_fps":0.0,"pid":223,"process_fps":15.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":132.7,"mount_type":"tmpfs","total":134.2,"used":1.5},"/media/frigate/clips":{"free":98993.3,"mount_type":"ext4","total":472320.0,"used":354104.3},"/media/frigate/recordings":{"free":98993.3,"mount_type":"ext4","total":472320.0,"used":354104.3},"/tmp/cache":{"free":929.6,"mount_type":"tmpfs","total":1000.0,"used":70.4}},"temperatures":{},"uptime":571,"version":"0.11.1-2eada21"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HDBW2831E-S-S2

### Any other information that may be helpful

The only difference between the two cameras are the firmware versions
- Working V2.800.0000000.19.R, Build Date: 2020-06-28
- Not working V2.820.0000000.45.R, Build Date: 2022-03-31

I checked both streams (main and detector) on VLC and they work perfectly - both cameras

I checked frigate with both cameras pointing to same URL and that worked fine (of course)

I checked frigate with only the non working camera and that made no difference
