### ISSUE TITLE
[Config Support]: Adjust aspect ratio in substream

### ISSUE THREAD

**Issue by avvalex** [blakeblackshear/frigate#4659]
### Describe the problem you are having

Hi, i'm trying to setup my first cam in Frigate. I'm using 4mp stream for RTMP and 640x480 sub stream for detection.
I've tried somr ffmpeg arguments that should correct sub stream wrong aspect ratio (from 4:3 to 16:9) but no one of them seems to change anything. If i'll be able to correct aspect ratio i would use sub stream also for RTMP (leaving 4MP only for recording).

I've tried:

output_args:
detect: -aspect 854:480 -c copy -f flv

output_args:
detect: -vf scale=854:480 -f rawvideo -pix_fmt yuv420p

The image remains always the same on Frigate (4:3 instead of 16:9).
Is there a way to stretch the image to 16:9?

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  port: xxxxx
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxxxxx
  password: xxxxxxxxxxxx
  stats_interval: 120

detectors:
  cpu:
    type: cpu
    num_threads: 2
    
cameras:
  xxxxxxxxx:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxx:xxxxxxxxxxxxxx@xxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://xxxxxxx:xxxxxxxxxxxxxx@xxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    rtmp:
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)
