### ISSUE TITLE
[Config Support]: Docker best memory usage options 

### ISSUE THREAD

**Issue by avvalex** [blakeblackshear/frigate#4668]
### Describe the problem you are having

Now that my first cam seems to work correctly, it's time to add others.
I have two doubts:

1) shm-size has to be calculated only for detection streams (i.e. sub stream with low resolution, in my case?), or also for recording or RTMP streams? I will have only 2 VGA streams detecting for humans (since i will find a Coral USB at a reasonable price....)

2) What tmpfs size is reasonable for eight 4MP cams, full resolution H24 recordings at 5FPS, 4096 mbps? I have 16GB of RAM, mostly unused... I prefer to use more RAM and let my HDD relax (even if it's a 4GB WD Purple, so it should be reliable enough....)

Many thanks!!!!

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  port: xxxxx
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxxxxx
  password: xxxxxxxxxxxx
  stats_interval: 120

detectors:
  cpu:
    type: cpu
    num_threads: 2
    
cameras:
  xxxxxxxxx:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxx:xxxxxxxxxxxxxx@xxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://xxxxxxx:xxxxxxxxxxxxxx@xxxxxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    rtmp:
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)
