### ISSUE TITLE
[Support]: Cannot start service frigate: OCI runtime create failed:

### ISSUE THREAD

**Issue by atlcell** [blakeblackshear/frigate#4670]
### Describe the problem you are having

I am trying to get Frigate up and running so I can add my Blue Iris Cameras for some quick CV alerts - if only I could get the docker container to run. 

I've tested frigate on two separate machines, one using `docker compose up` and one using `docker-compose up` and I'm running into the same issue with volumes.

![image](https://user-images.githubusercontent.com/1452704/206893944-ffc5107f-eec3-49d8-b834-b42aa82917ae.png)

I've tried using a dot reference, an absolute path, and I am having problems with mounting localtime. If I comment out the first line, frigate will run but will exit out as that folder is ciritcal for operation - but I've changed the path over 100 times, tried it on two different docker installs, and it won't run

what am I doing wrong?
![image](https://user-images.githubusercontent.com/1452704/206893983-98c0cafd-20c8-49c4-a1c9-03c6b4f19708.png)

### Version

null

### Frigate config file

```yaml
mqtt:
  host: mqtt.local

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 0,461,3,0,1919,0,1919,843,1699,492,1344,458,1346,336,973,317,869,375,866,432
```

### Relevant log output

```shell
null
```

### FFprobe output from your camera

```shell
null
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

null
