### ISSUE TITLE
[Config Support]: Display in home page only HD stream 

### ISSUE THREAD

**Issue by avvalex** [blakeblackshear/frigate#4671]
### Describe the problem you are having

Sorry if i make many questions, but i want to understand :-P
I've currently set un only 2 cams, the first fith recording and RTMP on main stream and detection on sub stream, and the second only with recording and RTMP on main stream.
If i open Frigate's home page now i see first cam in low res sub stream and second cam in high res main stream.
Is there a way to dispay main stream for every cam?

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  port: xxxx
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxx
  password: xxxxxxxxx
  stats_interval: 120

detectors:
  cpu:
    type: cpu
    num_threads: 2
    
cameras:
# cam 1
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxxx@xxxxxxx:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://xxxxx:xxxxxx@1xxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    rtmp:
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
# cam 2
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://yyyyyy:yyyyyyyyy@yyyyyyyyyyyyy554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        # - path: rtsp://yyyyyyy:yyyyyyyyyyyyy@yyyyyyyyyyy:554/cam/realmonitor?channel=1&subtype=1
          # roles:
            # - detect
    # detect:
      # width: 854
      # height: 480
      # fps: 5
    # objects:
      # track:
        # - person
      # filters:
        # person:
          # threshold: 0.6
    rtmp:
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    # snapshots:
      # enabled: true
      # timestamp: false
      # bounding_box: true
      # retain:
        # default: 3
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)
