### ISSUE TITLE
[Config Support]: Speed Detection/lights on delay

### ISSUE THREAD

**Issue by 1990marco1990** [blakeblackshear/frigate#4672]
### Describe the problem you are having

Hello,

I would use my Camera to detect a Person and lights on. It work but with a delay of 3-5 seconds. I have make a automation in Nodered. Can anyone help me please?

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt   
  password: 
  port: 1883

database:
  path: /media/frigate/frigate.db
  
detectors:
  coral:
    type: edgetpu
    device: usb
birdseye:
  enabled: True
  mode: continuous
    
cameras:
  Kamera_HWR:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.31.230:554/stream0?username=admin&password=E10ADC3949BA59ABBE56E057F20F883E
          roles:
            - detect
            - clips
            - record
    detect:
      width: 720
      height: 480
      fps: 10
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
  Kamera_Tuerklingel:
    motion:
      mask: 
       - 203,274,640,285,640,0,0,0,0,216,0,302
      improve_contrast: true
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.31.242/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.31.242/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 12
    snapshots:
      enabled: True
      required_zones:
        - Home
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10    
        required_zones:
          - Home
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
    zones:
      Home:
        coordinates: 640,480,640,292,454,265,302,284,180,278,0,303,0,480
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
  Kamera_Schuppen:
    motion:
      mask:
        - 0,0,263,0,485,0,496,72,394,123,0,576
        - 1340,245,972,47,960,0,1536,0,1536,576
      improve_contrast: true
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 1536
      height: 576
      fps: 10

    snapshots:
      enabled: True
      required_zones:
        - Schuppen_Grundstueck
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10    
        required_zones:
          - Schuppen_Grundstueck
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: true
      timestamp: false
    record:
      enabled: true
    zones:
      Schuppen_Grundstueck:
        coordinates: 0,576,388,102,485,82,479,38,864,0,1005,61,1405,279,1536,576
        objects:
          - person
          - car
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
```

### Relevant log output

```shell
[2022-12-11 13:36:20] ffmpeg.Kamera_Schuppen.detect  ERROR   : http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=: Connection refused
[2022-12-11 13:36:20] ffmpeg.Kamera_Schuppen.record_rtmp ERROR   : [tcp @ 0x55ad785630] Connection to tcp://192.168.31.161:80 failed: Connection refused
[2022-12-11 13:36:20] ffmpeg.Kamera_Schuppen.record_rtmp ERROR   : http://192.168.31.161/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=: Connection refused
[2022-12-11 13:36:20] watchdog.Kamera_Schuppen       INFO    : Terminating the existing ffmpeg process...
[2022-12-11 13:36:20] watchdog.Kamera_Schuppen       INFO    : Waiting for ffmpeg to exit gracefully...
[2022-12-11 13:36:40] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41378]
[2022-12-11 13:37:07] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41378]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
What device are you running on? Doesn't look like you have hardware acceleration enabled which would be highly recommended

**Comment by 1990marco1990** [comment]
`[2022-12-11 14:56:26] frigate.object_processing      INFO    : Exiting object processor...
[2022-12-11 14:56:27] watchdog.Kamera_HWR            ERROR   : Ffmpeg process crashed unexpectedly for Kamera_HWR.
[2022-12-11 14:56:27] watchdog.Kamera_HWR            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-12-11 14:56:27] ffmpeg.Kamera_HWR.detect       ERROR   : [h264_v4l2m2m @ 0x5589ceb7d0] output VIDIOC_REQBUFS failed: Invalid argument
[2022-12-11 14:56:27] ffmpeg.Kamera_HWR.detect       ERROR   : [h264_v4l2m2m @ 0x5589ceb7d0] no v4l2 output context's buffers
[2022-12-11 14:56:27] ffmpeg.Kamera_HWR.detect       ERROR   : [h264_v4l2m2m @ 0x5589ceb7d0] can't configure decoder
[2022-12-11 14:56:27] ffmpeg.Kamera_HWR.detect       ERROR   : Error while opening decoder for input stream #0:0 : Inappropriate ioctl for device
[2022-12-11 14:56:27] frigate.events                 INFO    : Exiting event processor...
[2022-12-11 14:56:27] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-12-11 14:56:27] root                           INFO    : Waiting for detection process to exit gracefully...`

This is in the Logs if i do this. Then nothing work.

**Comment by NickM-27** [comment]
Very weird, what version of HA OS are you running?

**Comment by 1990marco1990** [comment]
Home Assistant 2022.11.5 Supervisor 2022.11.2 Operating System 9.2 Frontend 20221108.0 - latest

**Comment by NickM-27** [comment]
Odds are this is an issue with the kernel, see https://github.com/blakeblackshear/frigate/issues/3780

**Comment by 1990marco1990** [comment]
Ok but what is the solution? I only installed Homeassistant and no Raspbian. Where can I downgrade the Kernel?

**Comment by NickM-27** [comment]
I wouldn't recommend that, most likely need to just wait for ffmpeg to issue a fix. hwaccel should speed up the decoding of the stream which will reduce delay.

also, is 720x480 the native resolution of your stream?

**Comment by 1990marco1990** [comment]
No I have set the native resolution in the config vor every Camere each like this:

`    detect:
      width: 1536
      height: 576`

**Comment by NickM-27** [comment]
One of them is set with 

```yaml
    detect:
      width: 720
      height: 480
```

So just making sure 👍

**Comment by NickM-27** [comment]
For hwaccel, yes, it needs to be fixed my ffmpeg

**Comment by daernsinstantfortress** [comment]
If you're happy to do this, drop the HAOS version back to 8.5 and this will restore hardware decoding:

`ha os update --version 8.5`

As it happens, I've just done this myself as I suspect the real fix might take quite a while to propagate into ffmpeg. No problems at all - one command, and it took around 10 mins to install and reboot, with no obvious negative side effects. Note: this does not affect the version of HA you are running, just the underlying host OS.

**Comment by 1990marco1990** [comment]
`[2022-12-14 21:49:46] ffmpeg.Kamera_Tuerklingel.detect ERROR   : [h264_v4l2m2m @ 0x55ab9b0a50] no v4l2 output context's buffers
[2022-12-14 21:49:46] ffmpeg.Kamera_Tuerklingel.detect ERROR   : [h264_v4l2m2m @ 0x55ab9b0a50] can't configure decoder
[2022-12-14 21:49:46] ffmpeg.Kamera_Tuerklingel.detect ERROR   : Error while opening decoder for input stream #0:0 : Inappropriate ioctl for device
[2022-12-14 21:49:46] watchdog.Kamera_Schuppen       ERROR   : Ffmpeg process crashed unexpectedly for Kamera_Schuppen.
[2022-12-14 21:49:46] watchdog.Kamera_Schuppen       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.`


That is my log. I do ha os update befor.

**Comment by 1990marco1990** [comment]
I have transfer my Installation to a Intel NUC 10 i5 with the same frigate.yml. The delay is always there.

**Comment by NickM-27** [comment]
What hardware acceleration method are you using?

**Comment by 1990marco1990** [comment]
I have used:

`ffmpeg:
  hwaccel_args: -c:v h264_qsv`

but the nothing work all are green

**Comment by NickM-27** [comment]
Include logs otherwise won't be able to help.

**Comment by 1990marco1990** [comment]
`[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Failed to create a VAAPI device.
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Error initializing an MFX session
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Error decoding header
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Error while decoding stream #0:0: Generic error in an external library
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Error querying IO surface: unsupported (-3)
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Error while decoding stream #0:0: Function not implemented
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Error querying IO surface: unsupported (-3)
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Error while decoding stream #0:0: Function not implemented
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Error querying IO surface: unsupported (-3)
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Error while decoding stream #0:0: Function not implemented
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] Error querying IO surface: unsupported (-3)
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Error while decoding stream #0:0: Function not implemented
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] video_get_buffer: image parameters invalid
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : [h264_qsv @ 0x55e485aebe00] get_buffer() failed
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Error while decoding stream #0:0: Invalid argument
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Finishing stream 0:0 without any data written to it.
[2022-12-23 22:45:54] ffmpeg.Kamera_Schuppen.detect  ERROR   : Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)`

**Comment by NickM-27** [comment]
Maybe try VAAPI, what generation i5 is it?

**Comment by 1990marco1990** [comment]
Yes VAAPI but who install it? im not very good on Linux.

**Comment by NickM-27** [comment]
Just set different args in the config https://docs.frigate.video/configuration/hardware_acceleration#intel-based-cpus-10th-generation-via-quicksync

**Comment by 1990marco1990** [comment]
I didnot understand it. Can you explain it a little bit?

**Comment by NickM-27** [comment]
The args are shown there in the docs I linked, replace the `-c:v h264_qsv` with the args in the linked sections with `-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p`

**Comment by 1990marco1990** [comment]
`ffmpeg:
  hwaccel_args: LIBVA_DRIVER_NAME=i965`
or
`ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p`

That also did not work.

**Comment by NickM-27** [comment]
If it didn't work include logs, i965 is a separate unrelated thing

**Comment by 1990marco1990** [comment]
`[2022-12-23 23:18:02] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
mapping values are not allowed here
  in "<unicode string>", line 17, column 21:
    ffmpeg: hwaccel_args: LIBVA_DRIVER_NAME=i965`

**Comment by 1990marco1990** [comment]
`[2022-12-23 23:19:47] ffmpeg.Kamera_Tuerklingel.detect ERROR   : [NULL @ 0x55914fa18d80] Unable to find a suitable output format for 'LIBVA_DRIVER_NAME=i965'
[2022-12-23 23:19:47] ffmpeg.Kamera_Tuerklingel.detect ERROR   : LIBVA_DRIVER_NAME=i965: Invalid argument
[2022-12-23 23:19:47] watchdog.Kamera_Schuppen       INFO    : Waiting for ffmpeg to exit gracefully...
[2022-12-23 23:19:47] ffmpeg.Kamera_Tuerklingel.record_rtmp ERROR   : [NULL @ 0x55b5a5904ac0] Unable to find a suitable output format for 'LIBVA_DRIVER_NAME=i965'
[2022-12-23 23:19:47] ffmpeg.Kamera_Tuerklingel.record_rtmp ERROR   : LIBVA_DRIVER_NAME=i965: Invalid argument
[2022-12-23 23:19:47] watchdog.Kamera_Tuerklingel    INFO    : Terminating the existing ffmpeg process...
[2022-12-23 23:19:47] watchdog.Kamera_Tuerklingel    INFO    : Waiting for ffmpeg to exit gracefully...`

**Comment by NickM-27** [comment]
ffmpeg: hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

Is what should be used

**Comment by 1990marco1990** [comment]
`[2022-12-23 23:23:39] ffmpeg.Kamera_Tuerklingel.detect ERROR   : [AVHWDeviceContext @ 0x55717a71fe00] No VA display found for device /dev/dri/renderD128.
[2022-12-23 23:23:39] ffmpeg.Kamera_Tuerklingel.detect ERROR   : Device creation failed: -22.
[2022-12-23 23:23:39] ffmpeg.Kamera_Tuerklingel.detect ERROR   : [h264 @ 0x55717a642900] No device available for decoder: device type vaapi needed for codec h264.
[2022-12-23 23:23:39] ffmpeg.Kamera_Tuerklingel.detect ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-12-23 23:23:39] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:39470]
[2022-12-23 23:23:41] frigate.video                  ERROR   : Kamera_HWR: Unable to read frames from ffmpeg process.
[2022-12-23 23:23:41] frigate.video                  ERROR   : Kamera_HWR: ffmpeg process is not running. exiting capture thread...
[2022-12-23 23:23:41] frigate.video                  ERROR   : Kamera_Schuppen: Unable to read frames from ffmpeg process.
[2022-12-23 23:23:41] frigate.video                  ERROR   : Kamera_Schuppen: ffmpeg process is not running. exiting capture thread...
[2022-12-23 23:23:42] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:39470]
[2022-12-23 23:23:43] frigate.video                  ERROR   : Kamera_Tuerklingel: Unable to read frames from ffmpeg process.
[2022-12-23 23:23:43] frigate.video                  ERROR   : Kamera_Tuerklingel: ffmpeg process is not running. exiting capture thread...`

**Comment by NickM-27** [comment]
Are you using docker compose? What does your docker look like?

**Comment by 1990marco1990** [comment]
I use Proxmox with Homeassistant.

**Comment by NickM-27** [comment]
Your proxmox isn't passing the GPU into the container or VM (whichever you're using)

**Comment by 1990marco1990** [comment]
Who can I do this?

**Comment by 1990marco1990** [comment]
`[2022-12-25 10:22:10] frigate.app                    INFO    : Capture process started for Kamera_Schuppen: 229
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-12-25 10:22:11] ws4py                          INFO    : Using epoll
[2022-12-25 10:22:31] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-12-25 10:22:31] frigate.app                    INFO    : Stopping...
[2022-12-25 10:22:31] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-12-25 10:22:31] frigate.record                 INFO    : Exiting recording maintenance...
[2022-12-25 10:22:31] frigate.record                 INFO    : Exiting recording cleanup...
[2022-12-25 10:22:31] frigate.events                 INFO    : Exiting event cleanup...
[2022-12-25 10:22:31] frigate.stats                  INFO    : Exiting watchdog...
[2022-12-25 10:22:31] frigate.watchdog               INFO    : Exiting watchdog...
[2022-12-25 10:22:31] frigate.events                 INFO    : Exiting event processor...
[2022-12-25 10:22:32] frigate.object_processing      INFO    : Exiting object processor...
[2022-12-25 10:22:32] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-12-25 10:22:32] root                           INFO    : Waiting for detection process to exit gracefully...`


It lloks well a little time but then it crasched.

**Comment by NickM-27** [comment]
The coral is going offline, what other USB devices do you have and is the coal plugged into usb3?

**Comment by 1990marco1990** [comment]
`[2022-12-27 07:35:53] watchdog.Kamera_Schuppen       ERROR   : Ffmpeg process crashed unexpectedly for Kamera_Schuppen.
[2022-12-27 07:35:53] watchdog.Kamera_Schuppen       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-12-27 07:35:53] watchdog.Kamera_HWR            ERROR   : Ffmpeg process crashed unexpectedly for Kamera_HWR.
[2022-12-27 07:35:53] watchdog.Kamera_HWR            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-12-27 07:35:53] ffmpeg.Kamera_HWR.detect       ERROR   : [segment @ 0x55ca458df700] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-12-27 07:35:53] ffmpeg.Kamera_HWR.detect       ERROR   : [flv @ 0x55ca458f3240] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-12-27 07:35:53] ffmpeg.Kamera_HWR.detect       ERROR   : [segment @ 0x55ca458df700] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.`

Have it plugged in a USB 3.0 Port then it works a time (15 hours) but still not working sometime.

**Comment by NickM-27** [comment]
Those are just camera errors, if your camera is WiFi then it makes a lot of sense. Those error have nothing to do with a coral though.

**Comment by 1990marco1990** [comment]
I have this error for all 3 Cameras but all over POE LAN and works well in Reolink App. There in the APP I have no problems every time I connect.

Sometimes it works a time without a LOG but then the bad LOGS come back. 

The recognize off a person is still to late if I would it use as a motion detector. Sometimes I have 2 Events for one Person detection. 

MQTT binary_sensor works well but still with 3-5 sec delay. The System ismore quickly frigate also but MQTT not much.

**Comment by NickM-27** [comment]
maybe try qsv instead of vaapi and see if it is better

**Comment by 1990marco1990** [comment]
How can I change it?

**Comment by NickM-27** [comment]
Use the args `-c:v h264_qsv` instead of `-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p`

**Comment by 1990marco1990** [comment]
How can I prevent 2 events being recognized in quick succession for one person?

**Comment by NickM-27** [comment]
are you saying there are 2 events happening at the same time. Or one event, frigate loses the person, then quickly picks up them again?

If it is the latter then you can slightly increase `detect -> max_disappeared` but you don't want that value to be too big

**Comment by 1990marco1990** [comment]
No not at the same time but as soon as I am out of the area for 1 second the video stops and as soon as I re-enter the area a new video starts.

`      events:
        pre_capture: 5
        post_capture: 20`

I have set it but the capture is only the seconds if a person is detect I think.

**Comment by NickM-27** [comment]
yes, in that case you want to set `detect -> max_disappeared` to a higher value

**Comment by 1990marco1990** [comment]
`      events: pre_capture: 5 post_capture: 20`

But why is the Clip not 5 sec before and 20 sec later the detection? Or am I misunderstanding something?

**Comment by NickM-27** [comment]
That only pushes the events start / end time, the segments saved with the clip will still adhere to the retention mode https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean so if the segment doesn't meet that it won't be saved

**Comment by 1990marco1990** [comment]
Ok but how can I make a Video with 5 sec before and 20 sec after from an Event?

The Frigate LOGS are good with qsv. 

By the way can i figure record the complete video for 2 Days? I have found the configuration but i did not understand, I would recor 24 hours for 2 days and also recognise events or can I only use one of them?

**Comment by NickM-27** [comment]
> Ok but how can I make a Video with 5 sec before and 20 sec after from an Event?

Change the retention mode to `all`

> By the way can i figure record the complete video for 2 Days? I have found the configuration but i did not understand, I would recor 24 hours for 2 days and also recognise events or can I only use one of them?

the configuration you have here

```yaml
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10    
```

records 24/7 for 5 days and keeps recordings for events for 10 days
