### ISSUE TITLE
[Support]: High CPU usage simply adding second cam

### ISSUE THREAD

**Issue by avvalex** [blakeblackshear/frigate#4675]
### Describe the problem you are having

Here again.... A strange problem is driving me crazy. I own a mini PC with Pentium J5040 al 16GB of ram, and i thought it would have been enough for 16 cams recording, but i have my CPU with very high usage just with second cam...

FIRST CONFIG:
I have CAM 1 configured like attached file, and CPU stays, let's say, al 10% (i have also Home Assistant and some other things).
If i add CAM 2 (same cam as cam 1), configured as attached, my CPU makes a jump of +25%.... Only for recording??? I thought that with detect enable set to "false" the only work would have been record direct stream and pass-thru RTMP stream, not so much....
And here the strange part (after many tries)....

SECOND CONFIG:
Cam 1 configured same way.
If i enable in CAM 2 the second stream (it was not enabled since i didnt't need it, ot at least this was what i thought...) and i:
1-put "detect" role on second low res stream and...
2-leave detect enabled "false" (like in first configuration)....
CPU load is only 2-3% more!!!! What? 

So my question is: why it seems that ffmpeg goes crazy (i see it with command "top -i") in first config, while adding second cam, and even third, with second config my CPU goes from 10 to 13%? What am i missing again? :-P
Is always necessary an active low res sub stream with a detect role disabled?
Thanks!!!

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host:  
  port:  
  topic_prefix: frigate
  client_id: frigate
  user:  
  password:  
  stats_interval: 120

detectors:
  cpu:
    type: cpu
    num_threads: 1
    
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
    
cameras:
# cam 1
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:xxxxxxxx@xxxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 854
      height: 480
      fps: 5
    motion:
      mask:
        - 0,0,0,102,520,99,520,143,854,247,854,0
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    rtmp:
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
# cam 2
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@xxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        # - path: rtsp://admin:xxxxxxxxx@xxxxxxxxxxxx:554/cam/realmonitor?channel=1&subtype=1
          # roles:
            # - detect
    detect:
      enabled: false
      # width: 854
      # height: 480
      # fps: 5
    # objects:
      # track:
        # - person
      # filters:
        # person:
          # threshold: 0.6
    rtmp:
      enabled: true
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 10
        mode: all
    # snapshots:
      # enabled: true
      # timestamp: false
      # bounding_box: true
      # retain:
        # default: 3
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

HassOS

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Imou IPC-G22
