### ISSUE TITLE
[Support]: Frigate Memory Consumption

### ISSUE THREAD

**Issue by daemian** [blakeblackshear/frigate#4687]
### Describe the problem you are having

I am running a Frigate Docker (blakeblackshear/frigate:stable-amd64) on my Unraid Server (6.11.5).  Every time i start the container, I find it stopped a few hours later. It seems unraid is killing the process because of memory usage. Any idea what would be causing this? Perhaps one of my config settings? I do have a PCie coral device installed TIA!

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: x.x.x.2
  user: <user>
  password: <pass>

detectors:
  coral:
    type: edgetpu
    device: pci
  # cpu1:
  #   type: cpu
  #   num_threads: 3
  # cpu2:
  #   type: cpu
  #   num_threads: 3
  # cpu3:
  #   type: cpu
  #   num_threads: 3
  # cpu4:
  #   type: cpu
  #   num_threads: 3

#database:
#  path: /config/frigate.db

model:
  labelmap:
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    16: animal
    17: animal

logger:
  default: info

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - qsv
#    - -qsv_device
#    - /dev/dri/renderD128

detect:
  width: 3840
  height: 2160

objects:
  track:
    - person
    - vehicle
    - animal

motion:
  threshold: 25
  contour_area: 30
  improve_contrast: False

record:
  enabled: True
  retain:
    days: 0
    mode: all
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - vehicle
    retain:
      default: 7
      mode: motion
      objects:
        person: 15
        vehicle: 15

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 7
    objects:
      person: 15
      vehicle: 15


cameras:
  front:
    ffmpeg:
     inputs:
       - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@x.x.x.66:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
         roles:
           - detect
           - rtmp
           - record
    rtmp:
      enabled: False
    zones:
      Driveway:
        coordinates: 0,946,200,805,480,624,1205,384,1739,393,151,1040
      Sidewalk:
        coordinates: 31,1322,0,1169,275,993,664,1073,986,1226,275,1781
      Road:
        coordinates: 2398,412,1179,402,449,459,402,388,1367,202,2421,176,2880,231,3179,278,3840,440,3840,696
  back:
    ffmpeg:
     inputs:
       - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@x.x.x.67:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
         roles:
           - detect
           - rtmp
           - record
    rtmp:
      enabled: False
  shop:
    ffmpeg:
     inputs:
       - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@x.x.x.68:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
         roles:
           - detect
           - rtmp
           - record
    rtmp:
      enabled: False
```

### Relevant log output

```shell
12 14:25:07 ur01 kernel: Out of memory: Killed process 34500 (python3) total-vm:62014940kB, anon-rss:55671756kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:110092kB oom_score_adj:0
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:<pass>@x.x.x.68:554/Streaming/Channels/101?transportmode=unicast':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.066000, bitrate: N/A
    Stream #0:0: Video: hevc, yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 90k tbn, 15 tbc
```

### Frigate stats

```json
{"back":{"camera_fps":5.1,"capture_pid":286,"detection_fps":2.7,"pid":281,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":13.8,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.52,"pid":273}},"front":{"camera_fps":5.1,"capture_pid":285,"detection_fps":5.2,"pid":279,"process_fps":5.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":5315.1,"mount_type":"tmpfs","total":5368.7,"used":53.6},"/media/frigate/clips":{"free":7108532.7,"mount_type":"fuse.shfs","total":14177911.0,"used":7067545.7},"/media/frigate/recordings":{"free":7070746.8,"mount_type":"fuse.shfs","total":13997865.3,"used":6927118.5},"/tmp/cache":{"free":32410.2,"mount_type":"rootfs","total":33661.8,"used":1251.6}},"temperatures":{"apex_0":44.55},"uptime":1058,"version":"0.10.1-83481af"},"shop":{"camera_fps":5.1,"capture_pid":291,"detection_fps":5.9,"pid":283,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Annke I91BF
