### ISSUE TITLE
[Support]: Error 404 when attempting to view snapshots and clips from push notification

### ISSUE THREAD

**Issue by C0nvictions** [blakeblackshear/frigate#4689]
### Describe the problem you are having

To preface, my experience with unraid, home assistant, and VMs is just the last couple weeks that I've been working to set up a home server for a security camera system. I'm running a VM with Home Assistant OS inside of Unraid. I have frigate installed as a docker within Unraid to capture video. In the Home Assistant VM, I'm using frigate proxy.

Notifications have been set up using the frigate blueprint. I currently get notifications, but trying to tap "view snapshot" or "view clip" results in a 404 error. I can still get to the snapshots and clips from within frigate proxy, however. From what I've seen online, this issue is often a result of the frigate integration not being installed in HACS, but I do have it installed.

I appreciate any help anyone can provide!

### Version

Frigate Proxy v. 1.3

### Frigate config file

```yaml
mqtt:
  host: xxxxxxxxxxxx
  user: xxxxxxxx
  password: xxxxxxxxxxx
  
objects:
  track:
    - person

rtmp:
  enabled: true

record:
  enabled: True
  events:
    retain:
        default: 7

snapshots:
      enabled: True
      bounding_box: true
      retain:
        default: 7

birdseye:
  enabled: True
  mode: continuous
  
cameras:
  backdoor: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # <----- Update for your camera
          roles:
            - record
         
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
    
    motion:
      mask:
      - 2160,0,2213,1440,2560,1440,2560,0
      - 2560,0,1547,368,2086,168,2105,1413
            
  bedroom: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx # <----- Update for your camera
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # <----- Update for your camera
          roles:
            - record
        
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
```

### Relevant log output

```shell
Not sure what this would be.
```

### FFprobe output from your camera

```shell
Not sure what this would be or if it'd be relevant.
```

### Frigate stats

```json
Not sure what this is.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C320WS
