### ISSUE TITLE
There are no boxes on screenshots or web output

### ISSUE THREAD

**Issue by alex-savin** [blakeblackshear/frigate#469]
**Describe the bug**
There are no boxes on any screenshot or web output

**Version of frigate**
v0.8.0b3

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
---
logger:
  default: info
  logs:
    frigate.mqtt: error

database:
  path: /media/frigate/clips/frigate.db

detectors:
  coral:
    type: edgetpu
    device: pci

model:
  height: 320
  width: 320

mqtt:
  host: 10.XX.XX.XX
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: REDACTED

save_clips:
  max_seconds: 60
  tmpfs_cache_size: 256m
  retain:
    default: 10
    objects:
      person: 15

ffmpeg:
  global_args: -hide_banner -loglevel fatal
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv

#objects:
#  track:
#    - person
#    - car
#    - truck
#  filters:
#    person:
#      min_area: 5000
#      max_area: 100000
#      threshold: 0.8

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180

detect:
  max_disappeared: 10

cameras:
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://10.XX.XX.XX:7447/XXXXXXXXXXXXXXX
          roles:
            - detect
            - rtmp
    height: 1080
    width: 1920
    fps: 30
    best_image_timeout: 60
    zones:
      zone_driveway:
        coordinates:
          - 141,1077
          - 0,1077
          - 0,395
          - 343,193
          - 1011,256
        filters:
          car:
            min_area: 5000
            max_area: 500000
            threshold: 0.7
      zone_property:
        coordinates:
          - 1915,1073
          - 0,1073
          - 7,168
          - 1913,346
        filters:
          person:
            min_area: 2000
            max_area: 150000
            threshold: 0.7
          cat:
            min_area: 1000
            max_area: 150000
            threshold: 0.7
    objects:
      track:
        - person
        - car
    save_clips:
      enabled: True
      pre_capture: 15
      objects:
        - person
    snapshots:
      show_timestamp: False
      draw_zones: True
      draw_bounding_boxes: True
```

**Logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating tmpfs of size 256m
frigate.app                    WARNING : Camera frontyard has save_clips enabled, but clips is not assigned to an input.
detector.coral                 INFO    : Starting detection process: 78
frigate.edgetpu                INFO    : Attempting to load TPU as pci
frigate.app                    INFO    : Camera processor started for frontyard: 81
frigate.app                    INFO    : Camera processor started for doorbell: 82
frigate.app                    INFO    : Camera processor started for entrance: 83
frigate.app                    INFO    : Capture process started for frontyard: 84
frigate.app                    INFO    : Capture process started for doorbell: 86
frigate.app                    INFO    : Capture process started for entrance: 90
frigate.edgetpu                INFO    : TPU found
frigate.video                  INFO    : doorbell: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : doorbell: ffmpeg process is not running. exiting capture thread...
```

**Frigate debug stats**
```
{"detection_fps":77.4,"detectors":{"coral":{"detection_start":1609707287.757457,"inference_speed":10.35,"pid":78}},"doorbell":{"camera_fps":30.0,"capture_pid":86,"detection_fps":31.2,"pid":82,"process_fps":29.8,"skipped_fps":0.0},"entrance":{"camera_fps":30.0,"capture_pid":90,"detection_fps":0.0,"pid":83,"process_fps":30.0,"skipped_fps":0.0},"frontyard":{"camera_fps":30.1,"capture_pid":84,"detection_fps":46.2,"pid":81,"process_fps":9.1,"skipped_fps":0.0}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --enable-libaribb24 --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x558ba6b8cbc0] UDP timeout, retrying with TCP
[rtsp @ 0x558ba6b8cbc0] Could not find codec parameters for stream 1 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://10.XX.XX.XX:7447/XXXXXXXXXXX':
  Metadata:
    title           : FCXXDAXX80XX_0
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 11025 Hz, mono, fltp
    Stream #0:1: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
```

**Screenshots**

**Computer Hardware**
 - OS: Debian 10
 - Virtualization: Proxmox
 - Coral Version: PCIe
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Ubiquiti
 - Model: G3 Pro
 - Resolution: 1080
 - FPS: 30

**Additional context**
