### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by mlause** [blakeblackshear/frigate#4690]
### Describe the problem you are having

I have a camera that faces the street and also includes my driveway and front lawn (grass). I want frigate to detect objects (car and person) across the entire frame but only notify me if I an object goes into the driveway or grass. The initial configuration I had notified me of everything. I change it to a new config, and a car outside of the zones showed up while I was watching my camera. It did not trigger an event nor did it record the car. 

I'm using frigate mobile notifications blueprint which allows me to specify a zone for a push notification.

How do I need to change my code to allow for what I am asking above?

I'll post the relevant config details below.

### Version

0.10.1-83481af

### Frigate config file

```yaml
Same global setting across both configs:
record:
  enabled: True
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 14
      mode: active_objects

Old camera config:
cameras:
  street:
    ffmpeg:
      inputs:
        - path: rtsp://xx/h264Preview_01_main
          roles:
            - record
            - rtmp
        - path: rtsp://xx/h264Preview_01_sub
          roles:
            - detect
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
    zones:
      driveway:
        coordinates: 47,218,0,244,0,312,61,417,224,229
      grass:
        coordinates: 608,480,93,480,71,420,238,230,640,264

New camera config:
cameras:
  street:
    ffmpeg:
      inputs:
        - path: rtsp://xx/h264Preview_01_main
          roles:
            - record
            - rtmp
        - path: rtsp://xx/h264Preview_01_sub
          roles:
            - detect
    rtmp:
      enabled: True
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
        - car
    record:
      events:
        required_zones:
          - driveway
          - grass
    snapshots:
      required_zones:
        - driveway
        - grass
    zones:
      driveway:
        coordinates: 47,218,0,244,0,312,61,417,224,229
        objects:
          - car
      grass:
        coordinates: 608,480,93,480,71,420,238,230,640,264
        objects:
          - person
```

### Relevant log output

```shell
no log issues
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

I'm running the frigate-nvidia docker in Unraid. HA is running as a docker with the HACS addon to get the firgate integration. I'm going to get it updated to .11 here shortly.
