### ISSUE TITLE
[Support]: tmpfs keeps filling up

### ISSUE THREAD

**Issue by Dougiebabe** [blakeblackshear/frigate#4699]
### Describe the problem you are having

It seems that Frigate will stop working after a random amount of time, the logs will complain of:

ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device'. 

But the actual drive that it is saving to has space. I have consoled onto the docker container and found this when running df -h
```
root:/opt/frigate# df -h
Filesystem                         Size  Used Avail Use% Mounted on
overlay                             36G   14G   21G  40% /
tmpfs                               64M     0   64M   0% /dev
shm                                128M  6.0M  123M   5% /dev/shm
/dev/mapper/ubuntu--vg-ubuntu--lv   36G   14G   21G  40% /db
//192.168.1.248/cctv               1.9T  1.7T  175G  91% /media/frigate
tmpfs                              954M  954M     0 100% /tmp/cache
```
So it looks like the tmpfs is filling up. Resetting the docker container is normally enough to bring it back online and the tmpfs will sit around 5% used UNTIL there is an issue.

If I understand correctly, the tmpfs is a RAM drive and used to reduce wear, the files get saved there and then removed if not needed?

I haven't been able to pin down if there is something specific that causes the tmpfs to stop emptying itself but it seems to happen at random times, sometime a day, sometimes a week.

This seems to have started when I did two things, I migrated to a new device and upgraded to the newest version of Frigate.

My setup is:

Host: 
Intel(R) Pentium(R) Gold 7505 @ 2.00GHz
32GB RAM
Proxmox

VM:
Ubuntu VM
2 x vCPU
4GB RAM
USB Passthrough for coral (Entire PCI Device)
GPU Passthrough

I did have an issue with the Coral when only passing through the device but since passing through the whole USB PCI Device it seems to be stable.
GPU Passthrough seems to be functioning correctly and intel_gpu_top shows activity on the Video encoder 

This is what I am greeted to when going to the website once it has happened
![image](https://user-images.githubusercontent.com/26346986/207289278-a177e399-8ea0-4995-923d-69d8f05a4b00.png)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
database:
    path: /db/frigate.db
mqtt:
    host: REDACTED
    user: REDACTED
    password: REDACTED
detectors:
    coral:
        type: edgetpu
        device: usb
ffmpeg:
    output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    hwaccel_args:
        -c:v h264_qsv
        #- -hwaccel
        #- vaapi
        #- -hwaccel_device
        #- /dev/dri/renderD128
        #- -hwaccel_output_format
        #- yuv420p
detect:
    stationary:
        interval: 50
objects:
    track:
        - person
        - cat
        - dog
    filters:
        person:
            min_area: 5000
            max_area: 8000000
            threshold: 0.80
record:
    events:
        pre_capture: 7
        post_capture: 10
cameras:
    Back_left: # <------ Name the camera
        ffmpeg:
            inputs:
                - path: rtsp://REDACTED/Streaming/Channels/103/ # <----- Update for your camera
                  roles:
                    - detect
                    - rtmp
                - path: rtsp://REDACTED/Streaming/Channels/101/
                  roles:
                    - record
                   # - detect
                    #- rtmp
        rtmp:
            enabled: False # <-- RTMP should be disabled if your stream is not H264
        detect:
            width: 1280 # <---- update for your camera's resolution
            height: 720 # <---- update for your camera's resolution
            #width: 2688
            #height: 1520
        record:
            enabled: True
           # retain:
           #     days: 1
           #     mode: all
            events:
                retain:
                    mode: active_objects
                    default: 10
        snapshots:
            enabled: True
            retain:
                default: 10
        mqtt:
            height: 1000
            quality: 100
    #720p zones
        zones:
            patio:
                coordinates: 0,720,1280,720,1280,260,1037,111,1002,187,801,184,727,160,710,218,521,242,516,164,417,204,105,253,83,164,0,218
            garden:
                coordinates: 375,0,385,142,332,151,328,214,520,228,709,209,814,180,939,185,954,113,608,0
            path_shed:
                coordinates: 388,149,376,0,307,0,182,0,158,117,122,250,264,229,328,216,324,162
    #4mp zones
       #zones:
       #    garden:
       #        coordinates: 809,300,679,313,682,459,932,429,932,290,1074,276,1092,379,1080,501,1225,483,1511,466,1536,271,1619,271,1694,303,1678,378,2049,394,2105,208,1892,186,1310,0,826,0
       #    path_shed:
       #        coordinates: 801,295,807,0,478,0,386,130,300,233,185,211,215,534,694,446,689,315
       #    patio:
       #        coordinates: 0,1520,0,404,216,549,925,409,930,275,1092,283,1087,493,1496,451,1543,260,1691,301,1679,376,2064,389,2104,195,2688,561,2688,1520
       #motion:
       #    mask:
       #        - 2160,201,1887,178,1337,0,2688,0,2688,543
       #        - 206,208,295,245,446,75,807,60,797,0,0,0,0,376
    Crib:
        ffmpeg:
            output_args:
                record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
            inputs:
                - path: rtsp://REDACTED/stream1
                  roles:
                    - record
                  #  - detect
                - path: rtsp://REDACTED/stream2
                  roles:
                  #  - record
                    - detect
        rtmp:
            enabled: False # <-- RTMP should be disabled if your stream is not H264
        detect:
          width: 640
          height: 360
        record:
            enabled: True
            events:
                retain:
                    mode: active_objects
                    default: 10
        snapshots:
            enabled: True
            retain:
                default: 10
        mqtt:
            height: 1000
            quality: 100
```

### Relevant log output

```shell
[2022-12-13 09:55:43] ffmpeg.Crib.record             ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device
[2022-12-13 10:28:14] watchdog.Crib                  INFO    : Waiting for ffmpeg to exit gracefully...
[2022-12-13 10:28:02] ffmpeg.Back_left.record        ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device
[2022-12-13 10:28:02] watchdog.Back_left             INFO    : Terminating the existing ffmpeg process...
[2022-12-13 10:28:02] ffmpeg.Back_left.record        ERROR   : 
[2022-12-13 10:28:02] ffmpeg.Back_left.record        ERROR   : Error initializing output stream 0:1 -- 
[2022-12-13 10:28:02] watchdog.Back_left             INFO    : Waiting for ffmpeg to exit gracefully...
[2022-12-13 10:28:04] ffmpeg.Crib.record             ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device
[2022-12-13 10:28:04] ffmpeg.Crib.record             ERROR   : Error initializing output stream 0:0 -- 
[2022-12-13 10:28:04] ffmpeg.Crib.record             ERROR   : 
[2022-12-13 10:28:04] watchdog.Crib                  INFO    : Terminating the existing ffmpeg process...
[2022-12-13 10:28:04] watchdog.Crib                  INFO    : Waiting for ffmpeg to exit gracefully...
[2022-12-13 10:28:12] ffmpeg.Back_left.record        ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device
[2022-12-13 10:28:12] ffmpeg.Back_left.record        ERROR   : Error initializing output stream 0:1 -- 
[2022-12-13 10:28:12] ffmpeg.Back_left.record        ERROR   : 
[2022-12-13 10:28:12] watchdog.Back_left             INFO    : Terminating the existing ffmpeg process...
[2022-12-13 10:28:12] watchdog.Back_left             INFO    : Waiting for ffmpeg to exit gracefully...
[2022-12-13 10:28:14] ffmpeg.Crib.record             ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): No space left on device
[2022-12-13 10:28:14] ffmpeg.Crib.record             ERROR   : Error initializing output stream 0:0 -- 
[2022-12-13 10:28:14] ffmpeg.Crib.record             ERROR   : 
[2022-12-13 10:28:14] watchdog.Crib                  INFO    : Terminating the existing ffmpeg process...
```

### FFprobe output from your camera

```shell
Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720, 6 fps, 25 tbr, 90k tbn
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520, 15 fps, 25 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp

 Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2304x1296, 15 fps, 14.92 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

 Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x360, 20 fps, 20.08 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Frigate stats

```json
{"Back_left":{"camera_fps":5.1,"capture_pid":218,"detection_fps":0.0,"pid":215,"process_fps":5.1,"skipped_fps":0.0},"Crib":{"camera_fps":5.1,"capture_pid":223,"detection_fps":0.0,"pid":216,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.63,"pid":212}},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":131.4,"mount_type":"tmpfs","total":134.2,"used":2.8},"/media/frigate/clips":{"free":187127.5,"mount_type":"cifs","total":2000397.9,"used":1813270.4},"/media/frigate/recordings":{"free":187127.5,"mount_type":"cifs","total":2000397.9,"used":1813270.4},"/tmp/cache":{"free":963.9,"mount_type":"tmpfs","total":1000.0,"used":36.1}},"temperatures":{},"uptime":54,"version":"0.11.1-2eada21"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2347G2-LU  -  Tapo C210

**Comment by NickM-27** [comment]
64MB for tmpfs is not enough. Any time you download a clip (HA does this when viewing too) it uses tmpfs to create the clip. Odds are the clip is too big and filling it

**Comment by Dougiebabe** [comment]
I thought I set it to 1gb, the df -h shows 954MB used?

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml:ro
      - /opt/frigate/nasstorage:/media/frigate
      - /opt/frigate/storage:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```

Here is my docker compose file where I thought it was set 1gb as well
