### ISSUE TITLE
[Support]: Frigate seems to be missing a "person detected" motion sensor in home assistant

### ISSUE THREAD

**Issue by patrick-jane-crypto** [blakeblackshear/frigate#4710]
### Describe the problem you are having

First of all, I love frigate. I'm running it in parallel with my Hikvision NVR and it's generally working great. My problem is that none of the entities which frigate currently provides seem to do what by Hikvision NVR home assistant integration already does.

What I'm looking for is essentially a motion sensor but for `object` only (so for people or cars etc). Instead, as of today, these are the sensors which Frigate creates:

- `switch.detect` which turns on/off detection
- `switch.motion` which turns on/off motion
- `binary_sensor.motion` which is a GENERAL motion sensor, which means ANY motion at all detected will trigger this
- `sensor.<object>_count` it's like the occupancy sensor except gives you a count of how many objects are in the area
- `binary_sensor.occupancy` this is the closest to what I'd want, except that this sensor will stay "on" for as long as the object is in the view / detected. It never seems to turn off again, which I guess makes sense given the name as the object still "occupies" the area.

The hikvision integration is pretty bad compared to Frigate, but it does provide the one sensor I feel I'm missing here, which iss, like I said, an `object` motion sensor that turns ON when it recognizes a person and then turns OFF if the person is stationary or moved away from the frame.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.111
  user: mqtt
  password: <snip>
cameras:
  hik_entrance_low: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/101/ # <----- Update for your camera
          roles:
            - record
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/102/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,360,569,360,505,312,111,61,0,65,0,0,196,0
        - 550,317,546,339,448,337,447,319
        - 24,0,37,145,64,255,113,360,0,360,0,71,0,0
    # zones:
    #   zone_0:
    #     coordinates: 640,308,640,192,548,142,410,81,242,38,178,66
    #   zone_1:
    #     coordinates: 440,300,432,323,428,360,113,360,44,169,32,102,98,62
    #   zone_2:
    #     coordinates: 640,360,640,313,315,123,138,56,108,63
  hik_driveway: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/201/ # <----- Update for your camera
          roles:
            - record
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/202/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,56,0,120,0,216,153,56,474,61,566,119,592,221,604,354,640,360,640,87,640,2,193,1,2,2
        - 531,315,526,341,458,338,458,315
    # zones:
    #   zone_0:
    #     coordinates: 218,360,577,360,593,316,587,256,585,183,552,131,493,87,382,65,214,65,187,70,81,155,0,233,0,360
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
  hik_entrance_high: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/301/ # <----- Update for your camera
          roles:
            - record
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/302/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    motion:
      mask:
        - 513,0,640,0,640,66,569,84,539,99,463,145,0,337,0,0
        - 640,360,325,360,356,293,393,273,465,227,565,147,640,52
    # zones:
    #   zone_0:
    #     coordinates: 442,152,555,90,595,110,529,173,335,317,314,358,2,358
  hik_backyard_low: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/401/ # <----- Update for your camera
          roles:
            - record
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/402/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    motion:
      mask:
        - 205,10,198,34,10,35,15,14
        - 410,339,524,339,520,309,414,312
        - 0,81,0,243,0,360,112,360,55,261,66,135
        - 459,3,640,1,640,73
  hik_backyard_high: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/501/ # <----- Update for your camera
          roles:
            - record
        - path: rtsp://<creds>@192.168.0.132:554/Streaming/Channels/502/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,110,464,21,204,86,65,74,0,57,0,0
        - 544,307,550,339,431,336,429,316
    # zones:
    #   zone_0:
    #     coordinates: 0,360,0,69,201,89,430,271,412,360,248,360
    #   zone_1:
    #     coordinates: 217,87,470,24,640,129,640,184,605,328,560,313,481,307
  hik_doorbell: # <------ Name the camera
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      inputs:
        - path: rtsp://<creds>@192.168.0.151:554/Streaming/Channels/101/ # <----- Update for your camera
          roles:
            - record
        - path: rtsp://<creds>@192.168.0.151:554/Streaming/Channels/102/ # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    motion:
      mask:
        - 620,511,619,529,490,531,490,510
        - 488,464,274,475,265,195,305,0,637,0,704,0,704,392
        - 0,576,284,576,276,192,301,185,309,0,0,0
    # zones:
    #   zone_0:
    #     coordinates: 704,576,704,427,628,425,459,457,268,465,286,475,283,576
  # eufy_living_room: # <------ Name the camera
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://<creds>@192.168.0.174/live0 # <----- Update for your camera
  #         roles:
  #           - detect
  #           - rtmp
  #   rtmp:
  #     enabled: True # <-- RTMP should be disabled if your stream is not H264
  #   detect:
  #     width: 1920 # <---- update for your camera's resolution
  #     height: 1080 # <---- update for your camera's resolution
  #   snapshots:
  #     enabled: True
  #   objects:
  #     # Optional: list of objects to track from labelmap.txt (default: shown below)
  #     track:
  #       - dog
  #       - cat
  # eufy_kitchen: # <------ Name the camera
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://<creds>@192.168.0.216/live0 # <----- Update for your camera
  #         roles:
  #           - detect
  #           - rtmp
  #   rtmp:
  #     enabled: True # <-- RTMP should be disabled if your stream is not H264
  #   detect:
  #     width: 1920 # <---- update for your camera's resolution
  #     height: 1080 # <---- update for your camera's resolution
  #   snapshots:
  #     enabled: True
  #   objects:
  #     # Optional: list of objects to track from labelmap.txt (default: shown below)
  #     track:
  #       - dog
  #       - cat
  # eufy_master_bedroom: # <------ Name the camera
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://<creds>@192.168.0.245/live0 # <----- Update for your camera
  #         roles:
  #           - detect
  #           - rtmp
  #   rtmp:
  #     enabled: True # <-- RTMP should be disabled if your stream is not H264
  #   detect:
  #     width: 1920 # <---- update for your camera's resolution
  #     height: 1080 # <---- update for your camera's resolution
  #   snapshots:
  #     enabled: True
  #   objects:
  #     # Optional: list of objects to track from labelmap.txt (default: shown below)
  #     track:
  #       - dog
  #       - cat
  #     filters:
  #       dog:
  #         # Optional: minimum score for the object to initiate tracking (default: shown below)
  #         min_score: 0.3
  #         threshold: 0.6
  #       cat:
  #         # Optional: minimum score for the object to initiate tracking (default: shown below)
  #         min_score: 0.3
  #         threshold: 0.6
  #   motion:
  #     # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  #     # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  #     # The value should be between 1 and 255.
  #     threshold: 15
  #     delta_alpha: 0.5
  #     improve_contrast: True

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (defau
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 15
birdseye:
  enabled: True
  mode: continuous
  quality: 5

detect:
  stationary:
    interval: 0
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

NA
