### ISSUE TITLE
Large amount of Clips files [Support]: 

### ISSUE THREAD

**Issue by rysm83** [blakeblackshear/frigate#4713]
### Describe the problem you are having

I'm running Frigate as Home assistant Addon.  I noticed that in the media folder I have the Frigate directory that holds all the files (Clips, Recording, and Snapshots).  I also Noticed that under the local media folder this too has a folder called clips and another for recordings.  The recordings folder seems to match what I have in me configuration file (retain for 5 days) however in the clips folder I have a large amount of files that do not seem to be auto deleted after the retain day.  Some files go back 2 months.  I wasn't sure if this was an issue as it seems my over all disk space has been slowing adding up.  anyway to have these files auto deleted? 

cameras:
  living_room_camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
      enabled: True
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
    snapshots:
      enabled : True
      retain:
        default: 5
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 483,406,640,433,640,105,465,132
          
    motion:
      mask:
        - 313,0,444,0,442,51,190,46,195,0
        - 338,82,327,105,218,167,65,155,61,78
    
    zones:
      livingroom_zone:
        coordinates: 0,358,128,351,205,334,251,310,279,265,480,250,484,412,534,430,596,448,640,480,268,480,0,480
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - record
        
    zones:
      driveway_zone:
        coordinates: 487,59,519,434,34,431,143,147
        objects:
          - person
          - car
          - cat
          - dog
          - bear

    detect:
      width: 640
      height: 480
      fps: 7
      enabled: True
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bear
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
        required_zones:
          - driveway_zone
    snapshots:
      enabled: True
      retain:
        default: 5
    motion:
      mask:
        - 313,0,444,0,442,51,190,46,195,0
        - 182,0,168,23,93,53,0,100,0,0
    objects:
      filters:
        car:
          mask:
            - 0,0,0,212,46,144,193,51,274,0
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - record
    zones:
      frontyard_zone:
        coordinates: 194,379,148,384,108,396,59,410,0,440,0,494,43,536,116,546,190,576,575,576,720,576,690,354
        objects:
          - person
          - cat
          - dog
          - bear
    detect:
      width: 720
      height: 576
      fps: 5
      enabled: True
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bear
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
    snapshots:
      enabled: True
      retain:
        default: 5
    motion:
      mask:
        - 0,0,720,0,720,0,720,345,0,358    
  
    

    
detectors:
  coral:
    type: edgetpu
    device: usb

### Version

 0.11.1-2EADA21

### Frigate config file

```yaml
cameras:
  living_room_camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
      enabled: True
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
    snapshots:
      enabled : True
      retain:
        default: 5
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 483,406,640,433,640,105,465,132
          
    motion:
      mask:
        - 313,0,444,0,442,51,190,46,195,0
        - 338,82,327,105,218,167,65,155,61,78
    
    zones:
      livingroom_zone:
        coordinates: 0,358,128,351,205,334,251,310,279,265,480,250,484,412,534,430,596,448,640,480,268,480,0,480
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - record
        
    zones:
      driveway_zone:
        coordinates: 487,59,519,434,34,431,143,147
        objects:
          - person
          - car
          - cat
          - dog
          - bear

    detect:
      width: 640
      height: 480
      fps: 7
      enabled: True
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bear
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
        required_zones:
          - driveway_zone
    snapshots:
      enabled: True
      retain:
        default: 5
    motion:
      mask:
        - 313,0,444,0,442,51,190,46,195,0
        - 182,0,168,23,93,53,0,100,0,0
    objects:
      filters:
        car:
          mask:
            - 0,0,0,212,46,144,193,51,274,0
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - record
    zones:
      frontyard_zone:
        coordinates: 194,379,148,384,108,396,59,410,0,440,0,494,43,536,116,546,190,576,575,576,720,576,690,354
        objects:
          - person
          - cat
          - dog
          - bear
    detect:
      width: 720
      height: 576
      fps: 5
      enabled: True
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bear
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
    snapshots:
      enabled: True
      retain:
        default: 5
    motion:
      mask:
        - 0,0,720,0,720,0,720,345,0,358    
  
    

    
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "driveway": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 7,
        "height": 480,
        "max_disappeared": 35,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 70
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/driveway-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/driveway -r 7 -s 640x480 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "313,0,444,0,442,51,190,46,195,0",
          "182,0,168,23,93,53,0,100,0,0"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "driveway",
      "objects": {
        "filters": {
          "car": {
            "mask": [
              "0,0,0,212,46,144,193,51,274,0"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [
            "driveway_zone"
          ],
          "retain": {
            "default": 5,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 5,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "driveway_zone": {
          "coordinates": "487,59,519,434,34,431,143,147",
          "filters": {},
          "objects": [
            "person",
            "car",
            "cat",
            "dog",
            "bear"
          ]
        }
      }
    },
    "front_door": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 576,
        "max_disappeared": 25,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 50
        },
        "width": 720
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub",
            "roles": [
              "detect",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub",
            "roles": [
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub-c copy -f flv rtmp://127.0.0.1/live/front_door -r 5 -s 720x576 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/front_door-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "0,0,720,0,720,0,720,345,0,358"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "front_door",
      "objects": {
        "filters": {
          "bear": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "car": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "car",
          "cat",
          "dog",
          "bear"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 5,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 5,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "frontyard_zone": {
          "coordinates": "194,379,148,384,108,396,59,410,0,440,0,494,43,536,116,546,190,576,575,576,720,576,690,354",
          "filters": {},
          "objects": [
            "person",
            "cat",
            "dog",
            "bear"
          ]
        }
      }
    },
    "living_room_camera": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 7,
        "height": 480,
        "max_disappeared": 35,
        "stationary": {
          "interval": 0,
          "max_frames": {
            "default": null,
            "objects": {}
          },
          "threshold": 70
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-timeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub",
            "roles": [
              "detect",
              "rtmp"
            ]
          },
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub",
            "roles": [
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub -c copy -f flv rtmp://127.0.0.1/live/living_room_camera -r 7 -s 640x480 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:xxxxxx@xxx.xxx.xxx.xxx:554/h264Preview_01_sub -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/living_room_camera-%Y%m%d%H%M%S.mp4",
          "roles": [
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": [
          "313,0,444,0,442,51,190,46,195,0",
          "338,82,327,105,218,167,65,155,61,78"
        ],
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "living_room_camera",
      "objects": {
        "filters": {
          "person": {
            "mask": [
              "483,406,640,433,640,105,465,132"
            ],
            "max_area": 24000000,
            "max_ratio": 24000000,
            "min_area": 0,
            "min_ratio": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 5,
            "mode": "motion",
            "objects": {}
          }
        },
        "expire_interval": 60,
        "retain": {
          "days": 0,
          "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 5,
          "mode": "motion",
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {
        "livingroom_zone": {
          "coordinates": "0,358,128,351,205,334,251,310,279,265,480,250,484,412,534,430,596,448,640,480,268,480,0,480",
          "filters": {},
          "objects": []
        }
      }
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-timeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "xxx.xxx.xxx.xxx",
    "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "homeassistant"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "plus": {
    "enabled": false
  },
  "record": {
    "enabled": false,
    "events": {
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "mode": "motion",
        "objects": {}
      }
    },
    "expire_interval": 60,
    "retain": {
      "days": 0,
      "mode": "all"
    },
    "retain_days": null
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "mode": "motion",
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  },
  "ui": {
    "use_experimental": false
  }
}
```

### FFprobe output from your camera

```shell
Unable to run Not really sure how to do so.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink
