### ISSUE TITLE
[Support]: camera not loading until ffprobe is clicked on system page (0.12 dev)

### ISSUE THREAD

**Issue by WhistleMaster** [blakeblackshear/frigate#4721]
### Describe the problem you are having

Thanks for the great work on Frigate !

I've tried version 0.12 dev-420bcd7 and I'm experiencing a strange thing: I have 6 cameras in the config, working great with 0.11. I've made the change to use `restream` option for each of them for 0.12 dev, and for two of them, not sure why, I have the placeholder message displayed with the following error in the log:

Then, those two cameras will not be displayed until I click on the `ffprobe` button for those two cameras on the new `/system` page. After clicking on the `ffprobe` button, the cameras are displayed.

### Version

0.12.0-420bcd7

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: {FRIGATE_MQTT_IP}
  topic_prefix: frigate
  user: {FRIGATE_MQTT_USER}
  password: '{FRIGATE_MQTT_PASSWORD}'

detect:
  max_disappeared: 25

snapshots:
  retain:
    default: 5

record:
  retain:
    days: 0
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 5
      mode: active_objects

ffmpeg:
  hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD128
  
objects:
  track:
    - person
    - car
    - cat
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

cameras:

  view1:
    ffmpeg:
      inputs:
        - path: rtsp://{USER_VIEW1}:{FRIGATE_RTSP_PASSWORD}@{IP_VIEW1}/axis-media/media.amp?streamprofile=High_B8A44F5A3DB7_0
          roles:
            - restream
        - path: rtsp://localhost:8554/view1
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: False
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    motion:
      mask:
        - 1099,352,1238,424,1298,109,1141,84
        - 1688,738,1580,660,1734,258,1876,327
        - 1049,257,1070,80,1036,75,1018,246
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask:
            - 1099,352,1238,424,1298,109,1141,84
            - 1688,738,1580,660,1734,258,1876,327
            - 1049,257,1070,80,1036,75,1018,246

  view2:
    ffmpeg:
      inputs: 
        - path: rtsp://{USER_VIEW2}:{FRIGATE_RTSP_PASSWORD}@{IP_VIEW2}/axis-media/media.amp?camera=2&streamprofile=ACC_High_B8A44F326815_0
          roles:
            - restream
        - path: rtsp://localhost:8554/view2
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1600
      height: 1200
      fps: 5
    rtmp:
      enabled: False
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1200
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1200
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_area: 0
          max_area: 24000000
          min_score: 0.5
          threshold: 0.7
          mask: 706,0,0,0,0,1944,965,1944,1063,1663,1071,611

  view3:
    ffmpeg:
      inputs: 
        - path: rtsp://{USER_VIEW3}:{FRIGATE_RTSP_PASSWORD}@{IP_VIEW3}/axis-media/media.amp?camera=5
          roles:
            - restream
        - path: rtsp://localhost:8554/view3
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: False
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080

  view4:
    ffmpeg:
      inputs: 
        - path: rtsp://{USER_VIEW4}:{FRIGATE_RTSP_PASSWORD}@{IP_VIEW4}/axis-media/media.amp?camera=6
          roles:
            - restream
        - path: rtsp://localhost:8554/view4
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: False
    record:
      enabled: True
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    motion:
      mask: 682,0,710,114,505,90,0,385,0,0
    objects:
      filters:
        person:
          mask:
            - 682,0,710,114,505,90,0,385,0,0
            - 836,261,810,382,764,381,740,335,801,191,827,192
        car:
          mask: 682,0,710,114,505,90,0,385,0,0
        dog:
          mask: 
            - 682,0,710,114,505,90,0,385,0,0
            - 836,261,810,382,764,381,740,335,801,191,827,192
        cat:
          mask: 682,0,710,114,505,90,0,385,0,0

  view5:
    ffmpeg:
      inputs:
        - path: rtsp://{USER_VIEW5}:{FRIGATE_RTSP_PASSWORD}@{IP_VIEW5}/axis-media/media.amp?camera=7
          roles:
            - restream
        - path: rtsp://localhost:8554/view5
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: False
    record:
      enabled: True
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    motion:
      mask: 415,220,324,0,1918,0,1920,212
    objects:
      filters:
        person:
          mask: 415,220,324,0,1918,0,1920,212
        car:
          mask: 415,220,324,0,1918,0,1920,212
        dog:
          mask: 415,220,324,0,1918,0,1920,212
        cat:
          mask: 415,220,324,0,1918,0,1920,212
      
  view6:
    ffmpeg:
      inputs:
        - path: rtsp://{USER_VIEW6}:{FRIGATE_RTSP_PASSWORD}@{IP_VIEW6}/axis-media/media.amp?camera=8
          roles:
            - restream
        - path: rtsp://localhost:8554/view6
          roles:
            - detect
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: False
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1080
    motion:
      mask: 1920,0,1920,388,1705,272
    objects:
      filters:
        person:
          mask: 1920,0,1920,388,1705,272
        car:
          mask: 1920,0,1920,388,1705,272
        dog:
          mask: 1920,0,1920,388,1705,272
        cat:
          mask: 1920,0,1920,388,1705,272
```

### Relevant log output

```shell
2022-12-13 19:07:38.266687545  [2022-12-13 19:07:38] frigate.video                  ERROR   : view1: Unable to read frames from ffmpeg process.
2022-12-13 19:07:38.266711412  [2022-12-13 19:07:38] frigate.video                  ERROR   : view1: ffmpeg process is not running. exiting capture thread...
2022-12-13 19:07:38.363755803  [2022-12-13 19:07:38] frigate.video                  ERROR   : view2: Unable to read frames from ffmpeg process.
2022-12-13 19:07:38.363839858  [2022-12-13 19:07:38] frigate.video                  ERROR   : view2: ffmpeg process is not running. exiting capture thread...
2022-12-13 19:07:40.967537814  [2022-12-13 19:07:40] watchdog.view2           ERROR   : Ffmpeg process crashed unexpectedly for view2.
2022-12-13 19:07:40.967626572  [2022-12-13 19:07:40] watchdog.view2           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2022-12-13 19:07:40.967678009  [2022-12-13 19:07:40] watchdog.view1           ERROR   : Ffmpeg process crashed unexpectedly for view1.
2022-12-13 19:07:40.972056763  [2022-12-13 19:07:40] ffmpeg.view2.detect      ERROR   : [rtsp @ 0x56174aaec840] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2022-12-13 19:07:40.972165835  [2022-12-13 19:07:40] watchdog.view1           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2022-12-13 19:07:40.972234959  [2022-12-13 19:07:40] ffmpeg.view2.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2022-12-13 19:07:40.972287893  [2022-12-13 19:07:40] ffmpeg.view2.detect      ERROR   : Output file #0 does not contain any stream
2022-12-13 19:07:40.972336768  [2022-12-13 19:07:40] ffmpeg.view1.detect      ERROR   : [rtsp @ 0x56208bda4840] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2022-12-13 19:07:40.972388509  [2022-12-13 19:07:40] ffmpeg.view1.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
2022-12-13 19:07:40.972459406  [2022-12-13 19:07:40] ffmpeg.view1.detect      ERROR   : Output file #0 does not contain any stream
```

### FFprobe output from your camera

```shell
View1:

"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1080,\n          \"width\": 1920\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1080,\n          \"width\": 1920\n        }\n      ]\n    }\n  }\n]"

View2:
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1200,\n          \"width\": 1600\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1200,\n          \"width\": 1600\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  }\n]"
```

### Frigate stats

```json
{
    "cpu_usages": {
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.0"
        },
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "112": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "141": {
            "cpu": "0.0",
            "mem": "1.0"
        },
        "147": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "148": {
            "cpu": "0.0",
            "mem": "1.8"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "150": {
            "cpu": "1.3",
            "mem": "1.6"
        },
        "1507": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "1508": {
            "cpu": "46.7",
            "mem": "0.4"
        },
        "157": {
            "cpu": "0.3",
            "mem": "1.6"
        },
        "158": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "159": {
            "cpu": "0.3",
            "mem": "1.6"
        },
        "160": {
            "cpu": "0.7",
            "mem": "1.7"
        },
        "161": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "162": {
            "cpu": "0.0",
            "mem": "1.7"
        },
        "163": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "164": {
            "cpu": "0.7",
            "mem": "1.7"
        },
        "165": {
            "cpu": "0.0",
            "mem": "1.7"
        },
        "166": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "167": {
            "cpu": "2.3",
            "mem": "1.6"
        },
        "169": {
            "cpu": "2.0",
            "mem": "1.6"
        },
        "17": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "173": {
            "cpu": "2.0",
            "mem": "1.6"
        },
        "176": {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "177": {
            "cpu": "2.0",
            "mem": "1.6"
        },
        "182": {
            "cpu": "2.3",
            "mem": "1.6"
        },
        "183": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "186": {
            "cpu": "12.0",
            "mem": "1.5"
        },
        "187": {
            "cpu": "1.7",
            "mem": "1.6"
        },
        "189": {
            "cpu": "0.0",
            "mem": "0.3"
        },
        "190": {
            "cpu": "13.7",
            "mem": "1.5"
        },
        "195": {
            "cpu": "13.7",
            "mem": "1.5"
        },
        "199": {
            "cpu": "12.7",
            "mem": "1.7"
        },
        "210": {
            "cpu": "1.3",
            "mem": "0.4"
        },
        "213": {
            "cpu": "1.0",
            "mem": "0.4"
        },
        "215": {
            "cpu": "1.7",
            "mem": "0.4"
        },
        "217": {
            "cpu": "1.7",
            "mem": "0.4"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "33": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "587": {
            "cpu": "13.7",
            "mem": "1.4"
        },
        "590": {
            "cpu": "2.3",
            "mem": "0.4"
        },
        "686": {
            "cpu": "15.0",
            "mem": "1.4"
        },
        "688": {
            "cpu": "0.3",
            "mem": "0.3"
        },
        "73": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "74": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "75": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "76": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "77": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "78": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "79": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.2"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "83": {
            "cpu": "3.0",
            "mem": "0.3"
        },
        "84": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "85": {
            "cpu": "1.3",
            "mem": "3.2"
        },
        "MiB": {
            "cpu": "3265.1",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 7.92,
            "pid": 148
        }
    },
    "gpu_usages": {
        "intel-vaapi": {
            "gpu": "3.79 %",
            "mem": "- %"
        }
    },
    "view2": {
        "camera_fps": 5.1,
        "capture_pid": 169,
        "detection_fps": 0.0,
        "ffmpeg_pid": 587,
        "pid": 159,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "view3": {
        "camera_fps": 5.1,
        "capture_pid": 173,
        "detection_fps": 0.0,
        "ffmpeg_pid": 186,
        "pid": 160,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "view4": {
        "camera_fps": 5.0,
        "capture_pid": 177,
        "detection_fps": 0.0,
        "ffmpeg_pid": 190,
        "pid": 162,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "view5": {
        "camera_fps": 5.0,
        "capture_pid": 182,
        "detection_fps": 0.0,
        "ffmpeg_pid": 195,
        "pid": 164,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "view6": {
        "camera_fps": 5.1,
        "capture_pid": 187,
        "detection_fps": 0.0,
        "ffmpeg_pid": 199,
        "pid": 165,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "view1": {
        "camera_fps": 5.0,
        "capture_pid": 167,
        "detection_fps": 0.0,
        "ffmpeg_pid": 686,
        "pid": 157,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "service": {
        "latest_version": "0.11.1",
        "storage": {
            "/dev/shm": {
                "free": 247.1,
                "mount_type": "tmpfs",
                "total": 268.4,
                "used": 21.3
            },
            "/media/frigate/clips": {
                "free": 256485.1,
                "mount_type": "ext4",
                "total": 306160.1,
                "used": 34048.1
            },
            "/media/frigate/recordings": {
                "free": 256485.1,
                "mount_type": "ext4",
                "total": 306160.1,
                "used": 34048.1
            },
            "/tmp/cache": {
                "free": 817.7,
                "mount_type": "tmpfs",
                "total": 1000.0,
                "used": 182.3
            }
        },
        "temperatures": {},
        "uptime": 668,
        "version": "0.12.0-420bcd7"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Axis M3116, Axis I8016
