### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by mlittle408** [blakeblackshear/frigate#4735]
### Describe the problem you are having

All of my sensors in Home Assistant are showing "Unavailable". 

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.X.XXX
  user: kiosk
  password: XXXXX

cameras:

  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX:XXXXX@192.168.1.XXXX:554/live
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,755,317,484,750,193,909,147,1065,147,1060,0,0,0
        - 1920,1080,1233,1080,1332,0,1920,0
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 7

  back_porch:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXXX@192.168.1.XXX:554/live
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 7
      events:
        retain:
          default: 7

  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.1.XXX:554/live
          roles:
            - detect
    motion:
      mask:
        - 392,197,496,227,874,235,959,0,0,0,0,335
        - 1518,244,1920,418,1920,0,1535,0
    zones:
      driveway:
        coordinates: 629,332,823,340,830,226,558,226,390,331
        objects:
          - car
          - person
          - dog
          - bicycle
      garage:
        coordinates: 1733,1080,1461,578,1165,348,279,339,0,486,0,1080
        objects:
          - dog
          - person
      grass:
        coordinates: 1920,1080,1920,449,1535,281,1499,424,1337,433
        objects:
          - dog
          - person
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: True
      retain_days: 7
      events:
        required_zones:
          - driveway
          - garage
          - grass
        retain:
          default: 7

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 10

objects:
 track:
   - person
   - car
   - dog
   - bicycle

record:
  enabled: True
  retain:
    days: 10
    mode: active_objects
  events:
    retain:
      default: 10
      mode: active_objects

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

live:
  height: 720
  quality: 8
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
