### ISSUE TITLE
[Camera Support]: Reolink doorbell Onvif ?

### ISSUE THREAD

**Issue by unf0rg0tt3n** [blakeblackshear/frigate#4749]
### Describe the problem you are having

The new reolink doorbell can be added to frigate. unfortunately I can't figure out how to add a onvif stream

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
deurbel:
ffmpeg:
inputs:
 - path: rtsp://<user>:<password>@192.168.1.168:554//h265Preview_01_main
roles:
 - record
 - path: rtsp://<user>:<password>@192.168.1.168:554//h265Preview_01_main
roles:
 - detect
 - rtmp
detect:
width: 640 
height: 480
fps: 15
objects:
track:
 - person
 - dog
record: 
enabled: True
retain:
days: 5
events:
retain:
default: 10
snapshots:
enabled: True
timestamp: false
bounding_box: true
retain:
default: 2
motion:
mask:
 - 87,94,51,139,24,277,182,297,321,306,319,255,379,257,390,311,506,285,640,251,640,76,565,111,437,42,303,0,200,0
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Smart 2K+ Wired PoE Video Doorbell

### Any other information that may be helpful

is it possible to get the doorbell press and two-way audio working via onvif?
