### ISSUE TITLE
[Support]: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by markus-seidl** [blakeblackshear/frigate#4775]
### Describe the problem you are having

Fresh install of frigate shows "Connection refused" without any indication what connection has been refused.
Improvement: Provide a stack trace to the logging or some more information so this can more easily debugged.

### Version

frigate doesn't start - stable; docker image id: 9f9afbe969f2

### Frigate config file

```yaml
# https://docs.frigate.video/configuration/index

mqtt:
  # Required: host name
  host: XXX
  user: "frigate-dvr"
  password: ""
  tls_ca_certs: "/config/tls.crt"

detectors:
  cpu:
    type: cpu
    num_threads: 2

logger:
  default: debug

birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  hwaccel_args: "-c:v h264_qsv"

record:
  enabled: True
  retain:
    days: 2

snapshots:
  enabled: True

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://stream-only:{FRIGATE_CAMERA_FRONT_PASSWORD}@XXX:554/Streaming/Channels/103/?transportmode=unicast
          roles:
            - detect
            - rtmp
```

### Relevant log output

```shell
frigate                | [s6-finish] waiting for services.
frigate                | [s6-finish] sending all processes the TERM signal.
frigate                | [s6-finish] sending all processes the KILL signal and exiting.
frigate                | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate                | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate                | [fix-attrs.d] applying ownership & permissions fixes...
frigate                | [fix-attrs.d] done.
frigate                | [cont-init.d] executing container initialization scripts...
frigate                | [cont-init.d] done.
frigate                | [services.d] starting services
frigate                | [services.d] done.
frigate                | [2022-12-22 11:01:00] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate                | Starting migrations
frigate                | [2022-12-22 11:01:00] peewee_migrate                 INFO    : Starting migrations
frigate                | [2022-12-22 11:01:00] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate                | [2022-12-22 11:01:00] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate                | There is nothing to migrate
frigate                | [2022-12-22 11:01:00] peewee_migrate                 INFO    : There is nothing to migrate
frigate                | [Errno 111] Connection refused
frigate                | [cmd] python3 exited 1
frigate                | [cont-finish.d] executing container finish scripts...
frigate                | [cont-finish.d] done.
frigate                | [s6-finish] waiting for services.
frigate                | [s6-finish] sending all processes the TERM signal.
frigate                | [s6-finish] sending all processes the KILL signal and exiting.
frigate                | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate                | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate                | [fix-attrs.d] applying ownership & permissions fixes...
frigate                | [fix-attrs.d] done.
frigate                | [cont-init.d] executing container initialization scripts...
frigate                | [cont-init.d] done.
frigate                | [services.d] starting services
frigate                | [services.d] done.
frigate                | [2022-12-22 11:02:05] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate                | Starting migrations
frigate                | [2022-12-22 11:02:05] peewee_migrate                 INFO    : Starting migrations
frigate                | [2022-12-22 11:02:05] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate                | [2022-12-22 11:02:05] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate                | There is nothing to migrate
frigate                | [2022-12-22 11:02:05] peewee_migrate                 INFO    : There is nothing to migrate
frigate                | [Errno 111] Connection refused
frigate                | [cmd] python3 exited 1
frigate                | [cont-finish.d] executing container finish scripts...
frigate                | [cont-finish.d] done.
frigate                | [s6-finish] waiting for services.
frigate                | [s6-finish] sending all processes the TERM signal.
frigate                | [s6-finish] sending all processes the KILL signal and exiting.
^CGracefully stopping... (press Ctrl+C again to force)
```

### FFprobe output from your camera

```shell
ffprobe doesn't return for some reason. I don't think this is relevant to the problem.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision
