### ISSUE TITLE
[Support]: Events triggering outside required zones

### ISSUE THREAD

**Issue by amdhunter** [blakeblackshear/frigate#4785]
### Describe the problem you are having

I have been fighting with one camera for a while now, it mostly works great but I keep getting random events when I have a lot of motion, be it wind, rain (under IR), lighting changes, and especially when my main house lights dim at night when an automation runs.  The lighting change creates large amounts of motion, and the resulting chance for a false positive goes up and I get a couple events per week during this time.  Attached are a couple photos from my camera during these events.  

This was one triggered during a rainstorm at night.  This is typical of what I see most of, be it rain or wind.
![car1](https://user-images.githubusercontent.com/44300387/209188847-859d57a0-69cb-4573-b9a3-45a17eb4a7d5.jpg)

This one was me driving my golf cart through the zone, and it rightly picked up the motion, but ended up triggering on a house across the street.
![image](https://user-images.githubusercontent.com/44300387/209188999-734407ab-5247-4f50-9ef0-164aee86b951.png)

In this one, the actual motion event of a vehicle driving down my driveway triggered via a car on the road (outside the motion zone, and inside the motion mask).
![image](https://user-images.githubusercontent.com/44300387/209189160-273b3865-c065-4bf9-854c-25811c1aee5d.png)

This one, again outside the required zone, and inside the motion mask, triggered when a person was being tracked, but a car presumably drove through the "person" bounding box, and triggered a car event.
![image](https://user-images.githubusercontent.com/44300387/209189514-4b6f9274-2ac1-4949-bc86-c185f6e65498.png)

These two are a similar event.  A vehicle drove into the required zone, and its bounding box captured a car on the road.  
![image](https://user-images.githubusercontent.com/44300387/209189740-9c8c3346-97e8-4fe4-9267-3177f88b087c.png)
![image](https://user-images.githubusercontent.com/44300387/209189752-aa6053a1-9de6-45f3-9b18-9fac2ce0322f.png)

This is one that happened when the camera switched on its IR:
![image](https://user-images.githubusercontent.com/44300387/209191682-f7be89c1-04de-453b-bd8e-6ed7addf8294.png)

I feel like this is a simple thing, maybe to do with masking, but I have been playing with everything I can find in the docs and been unable to reduce the false positives.  I also have a decent amount of false negatives, which is why the default min_score and thresholds are changed.  That being said, I have been getting these types of false positives since long before I changed those values.

One more thing, I do not have a sub-stream that is usable from this camera for detection.  The camera is an Amcrest 5MP bullet, and has a very very low (unusable) resolution sub-stream.  Since I am running in a VM, the CPU detectors actually work well enough for me, without getting into trying to pass a USB Coral to the VM.   Inference speeds are in the low 40's at all times.  

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: redacted
  user: redacted
  password: redacted

cameras:
  Front-Yard:
    ffmpeg:
      inputs:
        - path: rtsp://redacted:redacted@redacted/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - rtmp
            - detect
            - record
    detect:
      width: 2592
      height: 1944
      fps: 3
    snapshots:
      required_zones:
        - motion_area
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 180
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        required_zones:
          - motion_area
        retain:
          default: 30
    objects:
      track:
      - person
      - car
      - bus
      filters:
        car:
          min_score: 0.5
          threshold: 0.57
    motion:
        mask:
            - 814,614,1487,503,1931,545,2592,710,2592,0,0,0,0,825
    zones:
      motion_area:
        coordinates: 1487,503,1931,545,2592,710,2592,1944,0,1944,0,859,0,599
        objects:
          - person
          - car
          - bus

detectors:
    cpu1:
        type: cpu
    cpu2:
        type: cpu
    cpu3:
        type: cpu
    cpu4:
        type: cpu
    cpu5:
        type: cpu
    cpu6:
        type: cpu
    cpu7:
        type: cpu
    cpu8:
        type: cpu
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://redacted@redacted:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.200000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2592x1944, 10 fps, 10 tbr, 90k tbn
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest IP5M-B1186EW-28MM

**Comment by NickM-27** [comment]
Can you include a screenshot with the zone drawn? That would be helpful.

Also, to be clear an objects presence in a zone is based on the bottom center of its bounding box, are your zones designed with that in mind?

Also, the snapshot that is created with an event WILL NOT necessarily be the moment that the object entered the zone, so your problem may not be the zone itself but just that a false positive is being seen in the zone at one frame or another. 

As far as the actual issue, I'd suggest setting a min_area for `car` as there's no way a car could be identified with an area of 65 pixels (as in that one image). 

It should also be noted that motion masks are absolutely not meant to stop objects from being detected, so if you are trying to use motion masks to do that then you may be causing more harm than help https://docs.frigate.video/configuration/masks

**Comment by amdhunter** [comment]
I was just working on adding the zone and mask screenshots!  :)

Zone:
![image](https://user-images.githubusercontent.com/44300387/209192395-60b97142-47ee-477d-b13f-b2cd6efadb20.png)
Mask:
![image](https://user-images.githubusercontent.com/44300387/209192610-e39bb9be-b273-4fbf-aa26-954f8ac2b32f.png)

Since the zone is the top of the image, I believe the bottom center should be fine -- Maybe it's because the bounding boxes expand to include the road, etc, and that's what's causing part of this?  Honestly it would probably be fine if I could move the camera but I am trying to avoid that if possible.

As far as the snapshots, I do understand that, however, this happens a decent amount when there is motion (with no person or car), meaning, it's a separate event.  If the limitation is that the snapshot might show a car on the road while also capturing video of a car in my driveway driving the trigger, that's ok with me.  It's the true false positives that are problematic.  This camera is the only one I have with a phone notification so I am trained to "depend" on the alert to know someone is at my house.  (I recognize it's not perfect, but you get my idea hopefully)

That being said, the detections outside a zone that has been triggered by a true positive are outside my understanding.  I see what you are saying, but how can it trigger outside the required zone at all?  That is the part that I am not understanding, I believe.

I can try setting a min_area for car -- what method would you recommend for doing this, while not reducing true positives?  I am walking what seems to be a fine line because even now, I have false negatives at night with dark vehicles.  Even with my exterior lighting on, and the camera in day mode, it's as if the image quality is not good enough to capture them.  

As for the motion masks, I was and am trying to do that.  I was trying to mask the road (I never want events for the road itself), and the trees.  This was, in my mind, for two reasons.  One, the obvious of trying to filter out false positives, and also to reduce CPU usage.  Placebo effect told me that the former happened, to an extent, and the latter definitely worked.  Since I am stuck with CPU detectors for the time being, I really would like to keep the motion mask in place if possible.  Are you suggesting to refine the mask and only mask the trees themselves, and leave the driveway un-masked?

Thanks for your help! :)

**Comment by NickM-27** [comment]
>  I am walking what seems to be a fine line because even now, I have false negatives at night with dark vehicles. Even with my exterior lighting on, and the camera in day mode, it's as if the image quality is not good enough to capture them.

Okay first of all, I'd recommend setting `motion -> improve_contrast` to true which will increase your detections at night (it's motion not object detection that is causing the lack of detections in this case)

> Are you suggesting to refine the mask and only mask the trees themselves, and leave the driveway un-masked?

your motion mask actually seems fine, but I do think I would suggest doing that, just so objects don't get stuck inside the motion mask (which might be what is happening at least partially)

also, in case you didn't know, if you want to debug a particular event then you can add that mp4 file as a camera, set ALL the config to EXACTLY the same as the original camera, and watch it back with debug live view keeping in mind it will be a close approximation and not an exact replay of what happened https://docs.frigate.video/development/contributing#2-create-a-local-config-file-for-testing

**Comment by NickM-27** [comment]
these tips should get you moving in the right direction, I will probably have more specific suggestions once we get some more concrete examples of what is going on

P.S. still suggest setting a min_area for car of like 10000

**Comment by amdhunter** [comment]
> Okay first of all, I'd recommend setting `motion -> improve_contrast` to true which will increase your detections at night (it's motion not object detection that is causing the lack of detections in this case)
> 
> if you have home assistant or some other automation platform you could even automate it to do this at night only (what I do)

I had read some information on the improve_contrast setting, so I will create an automation to handle it.  Do you just do it at sunrise/sunset?  My exterior lighting is on at night so the camera's IR is off even late into the night.  I guess where I am going with this question is, does the automation need to coincide with the camera's switching from day to night mode?

> your motion mask actually seems fine, but I do think I would suggest doing that, just so objects don't get stuck inside the motion mask (which might be what is happening at least partially)

I will make that change and track the issue and see what happens.  I'll just block out ONLY the tall pine trees to sides of the driveway.

> also, in case you didn't know, if you want to debug a particular event then you can add that mp4 file as a camera, set ALL the config to EXACTLY the same as the original camera, and watch it back with debug live view keeping in mind it will be a close approximation and not an exact replay of what happened https://docs.frigate.video/development/contributing#2-create-a-local-config-file-for-testing

I didn't know this existed.  Honestly, since playing with required_zones, I have been getting probably 25% or less of the false positives I used to get, and I was running out of data to post here.  I think I made the change to include required_zones in my config early in Dec and I only keep video out to 30 days.  So that's a good thing at least.  :)

I will create a local camera the next time I can save a good version of the problem I am seeing.  Just need a windy day or rainy night, I guess.

**Comment by amdhunter** [comment]
> these tips should get you moving in the right direction, I will probably have more specific suggestions once we get some more concrete examples of what is going on
> 
> P.S. still suggest setting a min_area for car of like 10000

These tips do help, and if nothing else I have a better understanding of the masks and zone relationships.

How are you coming to that number, just curious?  Is there a way I can take an image and measure to get to a "correct" number?  (Or did you do that already...LOL)

**Comment by NickM-27** [comment]
> I had read some information on the improve_contrast setting, so I will create an automation to handle it. Do you just do it at sunrise/sunset? My exterior lighting is on at night so the camera's IR is off even late into the night. I guess where I am going with this question is, does the automation need to coincide with the camera's switching from day to night mode?

I do it at sunset/sunrise, the only downside to having it on when it isn't in IR mode is it might be a little over sensitive but I'd start with being oversensitive until you get things working how you want then can tweak.

> I will make that change and track the issue and see what happens. I'll just block out ONLY the tall pine trees to sides of the driveway.

👍 

> These tips do help, and if nothing else I have a better understanding of the masks and zone relationships.
>
> How are you coming to that number, just curious? Is there a way I can take an image and measure to get to a "correct" number? (Or did you do that already...LOL)

If you look at the screenshots you posted, the bounding boxes have a % (confidence) and then the number to the right of that is the area of the box. So I saw the screenshot where the truck was detected and had an area of 4000. Then looking at other objects it seems like a car in the zone would be at least 10000 pixels in area so that's what I chose

**Comment by amdhunter** [comment]
> I do it at sunset/sunrise, the only downside to having it on when it isn't in IR mode is it might be a little over sensitive but I'd start with being oversensitive until you get things working how you want then can tweak.

I will start with that.   The false negatives I am getting happen very often while the camera is in day mode anyway, after dark, and my exterior lighting on.  

> If you look at the screenshots you posted, the bounding boxes have a % (confidence) and then the number to the right of that is the area of the box. So I saw the screenshot where the truck was detected and had an area of 4000. Then looking at other objects it seems like a car in the zone would be at least 10000 pixels in area so that's what I chose

I will try the min_area thing, but I do see most of the false positives being fairly large.  Large enough that I would be concerned about starting to cut down on true positives.  Here's a couple examples:

False:
![image](https://user-images.githubusercontent.com/44300387/209198691-5f538d99-584c-4130-89b8-e01df6f339bc.png)
This one is smaller, though:
![image](https://user-images.githubusercontent.com/44300387/209198789-82a0f4dd-5fb2-4684-b41b-43b7f4e45dd1.png)
![image](https://user-images.githubusercontent.com/44300387/209198863-196545c7-f9fb-4938-be4d-1d7263063391.png)
![image](https://user-images.githubusercontent.com/44300387/209199084-f0e71a5a-b6ab-4bc7-a7ac-0ef320f20a16.png)
This was was before I added the required_zone, so it's probably not relevant any more:
![image](https://user-images.githubusercontent.com/44300387/209199928-65dab480-b7bb-4918-b8cc-b35bdafb7ec3.png)



The ones in the ~30k range seem to be about the size I'd start tracking as a car comes into view.  Although, once the car gets closer to the camera, that number gets much much larger so I don't know if setting the min_area to, say, 30k would cause a problem or not.  I guess it would just not track the car until closer to the camera?

For reference, here are some true positives to show the pixel areas:
![image](https://user-images.githubusercontent.com/44300387/209199361-5cfa3fb7-70c8-4c1d-a766-3f9fa99b7b63.png)
![image](https://user-images.githubusercontent.com/44300387/209199439-b570d853-c20c-49a1-8f77-5ca31da240d6.png)
![image](https://user-images.githubusercontent.com/44300387/209199549-0595caa2-2214-4cae-9766-1bbd1d5cd983.png)
![image](https://user-images.githubusercontent.com/44300387/209199581-433327c3-df90-4a11-b2b5-8be7556c786d.png)
![image](https://user-images.githubusercontent.com/44300387/209200006-b1a836c3-3d8c-4fc0-b2e1-8aff5a48c1c7.png)

**Comment by amdhunter** [comment]
> yeah, 30000 might be pushing it but it really depends on your needs. If you'd rather have absolute confidence that a notification is true then might want to trend higher in min_area, if you'd be okay with some false positives knowing that frigate will have tracked true cars earlier on then trend lower.
> 
> Even just a min_area of 10000 will help eliminate earlier detections which would help frigate, I'd suggest reading https://docs.frigate.video/guides/false_positives if you haven't already

I think I am going to start at 15000 and move from there if need be.  I would rather get false positives than the opposite.

I had read the min_area part of that doc but didn't think it would really help me here.  I'll give it a shot and monitor.  Thanks again for all the help!

**Comment by NickM-27** [comment]
I should have been clear, I specifically meant the scoring part

**Comment by amdhunter** [comment]
I'm tracking.  I have tweaked the scores a bit with this already, and it did help, and didn't really make an impact with more false positives:

```      filters:
        car:
          min_score: 0.5
          threshold: 0.57

**Comment by amdhunter** [comment]
Just updating this, I am still seeing false positives during times of high wind, which introduces more motion, which in turn introduces more changes for false positives.  One such event was this one, that I got today.  As well as some recent ones that are almost identical.  We really need a way to completely mask an area no matter motion or object.   I am kinda at my wit's end on this config, and for the moment am just dealing with the false positives. 

![image](https://user-images.githubusercontent.com/44300387/213492595-da3bdca6-ad40-4c9e-bbff-e272c2f14534.png)

For more info, here's some other recent false positives:
![image](https://user-images.githubusercontent.com/44300387/213493032-23ed62bd-309b-47de-8e97-b7d4c44dba73.png)
![image](https://user-images.githubusercontent.com/44300387/213493157-afa6ce38-9c30-45bd-a051-79ac7c0d336a.png)
![image](https://user-images.githubusercontent.com/44300387/213493248-2d418b06-704a-4f1b-8434-f1441b3c103e.png)
![image](https://user-images.githubusercontent.com/44300387/213493341-7d7e6223-bd4e-485c-91d4-a5781cf2bf6e.png)

I am going to raise my threshold to .6, and change the min_area to 21000 in hopes to get rid of these.

**Comment by NickM-27** [comment]
yeah, these are quite low scores even for the COCO model. I think raising the threshold makes sense

**Comment by amdhunter** [comment]
Agreed, I was just trying to capture more cars in times of dark, etc.  I've changed min_score to 0.6 and threshold to 0.55.  Does this seem like a good relationship between the two scores?

**Comment by NickM-27** [comment]
it doesn't make sense for threshold to be below min_score

**Comment by amdhunter** [comment]
So what should I set the threshold to be, if I want min_score around .6?  I guess I haven't been able to wrap my brain around the two functions as they work together.  In the meantime, I'll read over the doc on that again.  Thanks!

**Comment by NickM-27** [comment]
basically min_score is when frigate first starts tracking the object. if the score is below that then it ignores it. Once the object has a score above min_score frigate starts tracking it, calculating the median score. Once that median score is above threshold then it is considered a true positive and the event is added to the list.

I'd suggest min_score of 0.6 and threshold of 0.7

**Comment by amdhunter** [comment]
Thank you.  I had it completely backwards.  I'll try that setup now.

**Comment by blakeblackshear** [comment]
> We really need a way to completely mask an area no matter motion or object

This is what an object mask can be used for. It tells Frigate that everything in the object mask (bottom center of bounding box) is guaranteed to be a false positive. You can apply an object mask to the trees, or areas of the yard where you never expect a car to be. The docs talk about masking areas like the top of a roof or sky for things you would never expect to be up there.

**Comment by amdhunter** [comment]
> > We really need a way to completely mask an area no matter motion or object
> 
> This is what an object mask can be used for. It tells Frigate that everything in the object mask (bottom center of bounding box) is guaranteed to be a false positive. You can apply an object mask to the trees, or areas of the yard where you never expect a car to be. The docs talk about masking areas like the top of a roof or sky for things you would never expect to be up there.

Thanks for your reply, Blake.  Can you show me how I would utilize that in my config?  I have a required_zone defined already, but I am getting the false positives outside that zone.  I do understand that can happen, depending on the size of motion and the related bounding box.  Here's my config for that camera as it is now, with a screenshot of the current required_zone.  Basically, anything above the zone in the screenshot is fair game to completely mask out.

`cameras:
  Front-Yard:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - rtmp
            - detect
            - record
    detect:
      width: 2592
      height: 1944
      fps: 3
    snapshots:
      required_zones:
        - motion_area
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 180
    record:
      enabled: true
      retain:
        days: 1
        mode: motion
      events:
        required_zones:
          - motion_area
        retain:
          default: 30
    objects:
      track:
      - person
      - car
      - bus
      filters:
        car:
          min_area: 21000
          min_score: 0.57
          threshold: 0.63
    motion:  #< -- This is the old motion mask with no break for the driveway
        mask:
          - 833,516,1020,503,1518,471,1938,516,2592,634,2592,0,0,0,0,767
    #motion:  #<-- New mash with break for driveway
        #mask:
          #- 0,0,0,750,825,583,825,0
          #- 2592,0,2592,700,1644,481,1048,484,1040,0
    zones:
      motion_area:
        coordinates: 1487,503,1931,545,2592,710,2592,1944,0,1944,0,859,0,599
        objects:
          - person
          - car
          - bus`

![image](https://user-images.githubusercontent.com/44300387/213594418-19b7f3ba-82f1-4193-9fee-991f0dc4a7b0.png)

**Comment by amdhunter** [comment]
I think I understand how this would be done, I have created a zone called "excluded_area", and left the required_zones defined with "motion_area".  Now my config looks like this and I have the "excluded_area" zone above, as the screenshot show.  Is this correct?

```
    zones:
      excluded_area:
        coordinates: 833,516,1020,503,1518,471,1938,516,2592,634,2592,0,0,0,0,577
      motion_area:
        coordinates: 1487,503,1931,545,2592,710,2592,1944,0,1944,0,859,0,599
        objects:
          - person
          - car
          - bus
          
```

![image](https://user-images.githubusercontent.com/44300387/213595534-0557e4b1-bd2c-47e7-bba8-3cb6fbb1a145.png)

**Comment by blakeblackshear** [comment]
I'm not talking about zones at all. I'm talking about object filter masks. https://docs.frigate.video/configuration/masks

**Comment by amdhunter** [comment]
Sorry guys, trying here...

Would this be correct?  It's not clear in the docs where to place the mask but I found some other Git posts showing a mask under the object node like this:

```
    objects:
      track:
      - person
      - car
      - bus
      filters:
        car:
          min_area: 21000
          min_score: 0.57
          threshold: 0.63
        mask:
          - 833,516,1020,503,1518,471,1938,516,2592,634,2592,0,0,0,0,577
   
```
