### ISSUE TITLE
[Support]: Extremely high memory usage

### ISSUE THREAD

**Issue by timcooijmans** [blakeblackshear/frigate#4788]
### Describe the problem you are having

I'm running Frigate with 11 camera's on Ubuntu. I'm using vaapi as I'm using a 8th-gen Intel. FFmpeg is using around 800MB-1000MB of memory per process. Causing my NVR-server to stall. 

I have the feeling that this wasn't an issue on 0.10

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: mqtt

detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
  oprit-links:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.11:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
        - 704,0,704,198,637,129,544,76,320,24,315,0
  oprit-rechts:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.12:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
        - 0,0,0,186,140,116,358,95,497,107,704,266,704,0
  oprit-langs:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.13:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
  oprit-achter:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.14:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.14:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
        - 0,0,602,0,601,184,319,222,0,337
        - 704,182,609,375,512,364,563,138
  huis-achter-links:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.15:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.15:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
  achterdeur:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.16:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.16:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.16:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
        - 354,302,553,393,626,107,386,150
  huis-achter-rechts:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.17:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.17:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
        - 662,576,536,576,633,232,704,260,704,576
    objects:
      filters:
        person:
          threshold: 0.8
  huis-zijkant:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.18:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.18:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
            - record
    detect:
      width: 704
      height: 576 
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
  schuur-zijkant:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.19:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.19:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.19:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record 
    detect:
      width: 704
      height: 576
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
        - 704,442,387,316,423,154,560,152,704,246
  schuur-deur:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.30.0.20:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - record
    detect:
      width: 704
      height: 576
    motion:
      mask:
        - 401,56,704,58,704,21,403,24
rtmp:
  enabled: false
snapshots:
  enabled: true
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 21
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"achterdeur":{"camera_fps":5.0,"capture_pid":246,"detection_fps":5.0,"pid":234,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":9.3,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.98,"pid":220}},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":128.8,"mount_type":"tmpfs","total":134.2,"used":5.4},"/media/frigate/clips":{"free":4365981.0,"mount_type":"ext4","total":4960383.9,"used":344337.2},"/media/frigate/recordings":{"free":4365981.0,"mount_type":"ext4","total":4960383.9,"used":344337.2},"/tmp/cache":{"free":219453.2,"mount_type":"overlay","total":249792.1,"used":17575.6}},"temperatures":{},"uptime":877,"version":"0.11.1-2eada21"},"voordeur":{"camera_fps":5.0,"capture_pid":245,"detection_fps":4.3,"pid":232,"process_fps":5.0,"skipped_fps":0.0},"voorzijde":{"camera_fps":5.0,"capture_pid":251,"detection_fps":0.0,"pid":235,"process_fps":5.0,"skipped_fps":0.0},"zijkant-voor":{"camera_fps":5.0,"capture_pid":260,"detection_fps":0.0,"pid":244,"process_fps":5.0,"skipped_fps":0.0},"zijkant-water":{"camera_fps":5.0,"capture_pid":255,"detection_fps":0.0,"pid":243,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Device:
Intel(R) Core(TM) i7-8700T 
8GB RAM

**Comment by NickM-27** [comment]
We've seen some issues with memory usage and VAAPI. I'd recommend trying QSV and see if it works as it does work for some 8th gen CPUs.

**Comment by timcooijmans** [comment]
Alright, I switched to QSV, no complaints in the logs so let's see how this goes.

**Comment by Cheerpipe** [comment]
Hi @timcooijmans 

How did you enabled QSV for a 8th gen i7? Frigate docs only has VAAPI params for <10th Generation intel cpus.

Thanks in advance

**Comment by NickM-27** [comment]
@Cheerpipe our docs are generalized. Some CPUs older than 10th gen support qsv, it just depends. Simply change the args to see if it works.

**Comment by Cheerpipe** [comment]
Thanks for encourage me to try qsv.

This config works well with my i5 9400. I am also rescaling my camera feeds with VAAPI/QSV which reduces a lot my cpu usage.

```
ffmpeg:
  #hwaccel_args: -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi            # Working VAAPI 
  hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv                                             # Working QSV
  output_args:
   #detect: -vf fps=6,deinterlace_vaapi=rate=field:auto=1,scale_vaapi=w=1280:h=720,hwdownload,format=yuv420p -f rawvideo                          # Working scale with VAAPI
   detect:  -vf vpp_qsv=framerate=4,scale_qsv=w=1280:h=720:format=nv12,hwdownload,format=nv12,format=yuv420p -f rawvideo                          # Working scaleQSV

```
