### ISSUE TITLE
[EdgeTPU Support]: USB Coral works when plugged into built in USB but not when plugged into USB-C expansion card

### ISSUE THREAD

**Issue by brianboko** [blakeblackshear/frigate#4795]
### Describe the problem you are having

I am running Frigate in a CTX container in Proxmox on Debian 11 turnkey. This is a privileged container. The hardware is an old Dell Ivybridge based rack mount workstation so it only has USB 2.0 ports. In order to get good bus speeds out of the Coral, I bought this USB-C Pcie card:

https://www.newegg.com/p/17Z-0128-00004?Item=9SIB5G5GC59591

I also bought some high-ish quality USB C cables from Anker so I could plug the coral in with a direct C to C connection. Anyway, I set everything up and passed through the entire USB bus from the card to the container. I was able to pull and execute the first Coral test case in this container from the getting started article they (coral) published. With that working, I setup Frigate with docker-compose and got my camera brought in. However, when I walked in front of the camera, the detection would get stuck and freeze the camera live feed on frigate with it. It would then restart the detection thread and repeat the freezing over and over again as long as I was triggering motion for the detection to run on. While this was happening, an error that looks like it was being reported by the USB card driver was being displayed in the native terminal on the Proxmox host machine. I've attached a picture I took of the screen of the Proxmox host. I have no idea what these errors mean generally speaking, regardless of their relation to my issue with frigate.

![20221224_210357](https://user-images.githubusercontent.com/25753293/209499690-183f6fca-5acb-47e1-802b-f04cd5dbc5e8.jpg)

After experiencing this, I decided to test the built in USB ports by passing that bus through to the container and plugging the coral into them. After doing this, frigate worked as expected - just with a much slower bus speed obviously. I know virtualization isn't really officially supported by Frigate, but I've found many cases of it being successfully done online so far. I am wondering what about this particular USB card setup is not playing nice with Frigate and if there is anything I can do about it. I know I could've just gotten a pcie coral and probably avoided this problem, but I wanted the flexibility and portability of the USB devices. I look forward to hearing any input you might have and appreciate the help!

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: broker.hivemq.com #Please replace with a valid mqtt broker
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  basement-test:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:LOLCANTREADMYPASSWORD@192.168.2.127:554/cam/realmonitor?channel=1&subtype=1 #replace with your RTS>
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: True
    record:
      enabled: True
      retain:
        days: 10
```

### docker-compose file or Docker CLI command

```yaml
ersion: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config/config.yml:/config/config.yml:ro
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
```

### Relevant log output

```shell
root@myhostnamecantreaditbro /home/frigate# docker compose -f frigate.yml up
WARN[0000] The "F3K6it" variable is not set. Defaulting to a blank string. 
[+] Running 1/0
 ⠿ Container frigate  Created                                                                                      0.0s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-12-26 04:38:03] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-12-26 04:38:03] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-12-26 04:38:03] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-12-26 04:38:03] frigate.app                    INFO    : Output process started: 213
frigate  | [2022-12-26 04:38:03] frigate.app                    INFO    : Camera processor started for basement-test: 216
frigate  | [2022-12-26 04:38:03] ws4py                          INFO    : Using epoll
frigate  | [2022-12-26 04:38:03] frigate.app                    INFO    : Capture process started for basement-test: 218
frigate  | [2022-12-26 04:38:03] ws4py                          INFO    : Using epoll
frigate  | [2022-12-26 04:38:03] detector.coral                 INFO    : Starting detection process: 212
frigate  | [2022-12-26 04:38:03] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-12-26 04:38:32] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
frigate  | Process detector:coral:
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
frigate  |     delegate = Delegate(library, options)
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
frigate  |     raise ValueError(capture.message)
frigate  | ValueError
frigate  | 
frigate  | During handling of the above exception, another exception occurred:
frigate  | 
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate  |     self.run()
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate  |     self._target(*self._args, **self._kwargs)
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate  |     object_detector = LocalObjectDetector(
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 44, in __init__
frigate  |     edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
frigate  |     raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate  | ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate  | 
frigate  | [2022-12-26 04:38:33] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [2022-12-26 04:38:33] frigate.video                  ERROR   : basement-test: Unable to read frames from ffmpeg process.
frigate  | [2022-12-26 04:38:33] frigate.video                  ERROR   : basement-test: ffmpeg process is not running. exiting capture thread...
frigate  | [s6-finish] sending all processes the TERM signal.
frigate  | [s6-finish] sending all processes the KILL signal and exiting.
frigate exited with code 0
frigate  | exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-12-26 04:38:38] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-12-26 04:38:38] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-12-26 04:38:38] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-12-26 04:38:39] frigate.app                    INFO    : Output process started: 214
frigate  | [2022-12-26 04:38:39] frigate.app                    INFO    : Camera processor started for basement-test: 217
frigate  | [2022-12-26 04:38:39] frigate.app                    INFO    : Capture process started for basement-test: 219
frigate  | [2022-12-26 04:38:39] ws4py                          INFO    : Using epoll
frigate  | [2022-12-26 04:38:39] ws4py                          INFO    : Using epoll
frigate  | [2022-12-26 04:38:39] detector.coral                 INFO    : Starting detection process: 213
frigate  | [2022-12-26 04:38:39] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-12-26 04:38:41] frigate.edgetpu                INFO    : TPU found
frigate  | [2022-12-26 04:39:59] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
frigate  | [2022-12-26 04:39:59] root                           INFO    : Waiting for detection process to exit gracefully...
frigate  | [2022-12-26 04:40:29] root                           INFO    : Detection process didnt exit. Force killing...
frigate  | [2022-12-26 04:40:29] detector.coral                 INFO    : Starting detection process: 313
frigate  | [2022-12-26 04:40:29] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2022-12-26 04:40:31] frigate.edgetpu                INFO    : TPU found
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

The following are the lines I added to the config file of my Proxmox container to pass through the USB bus:

unprivileged: 0
lxc.mount.entry: /dev/bus/usb/006/ dev/bus/usb/006/ none bind,optional,create=dir 0,0
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.mount.auto: cgroup:rw

Also, in my frigate log you can see that the detection thread crashes and says that it can't find the TPU before restarting and saying that the TPU was found successfully. This happens every time I change which physical USB port the TPU is plugged into. All frigate launches after the initial one don't do this. Not sure if this is expected behavior or not so I figured it was worth mentioning. Thanks!
