### ISSUE TITLE
[HW Accel Support]: 0.12.0-368c07c on Fedora 37

### ISSUE THREAD

**Issue by cananda** [blakeblackshear/frigate#4798]
### Describe the problem you are having

I'm new to frigate and experimenting with person detection and eventually use face recognition with double-take.  While I wait for coral devices to be available, I'm thrilled about 0.12 and openvino support.  

 I'm not 100% sure if iGPU acceleration is working on my 11th Gen Intel(R) Core(TM) i7-1165G7 laptop. With 0.11.1, I get anywhere from 45 to 64ms inference speeds using CPU (30-40% usage) with 1 Reolink 810a camera.  With 0.12.0-368c07c, I get ~11-12ms with ov_detector enabled (CPU usage 1-8%), but vainfo on the UI errors out

I'm running frigate as docker container on my Fedora 37 host. `vainfo` on  host reports - 

```
Trying display: wayland
libva info: VA-API version 1.16.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.16 (libva 2.16.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.5.4 ()
...
...
```
`ls /dev/dri` reports
```
by-path  card1  renderD128
```
`vainfo` from the Frigate UI reports 
```
Vainfo Output

{ "return_code": 3, "stderr": "error: XDG_RUNTIME_DIR is invalid or not set in the environment.\nerror: can't connect to X server!\nlibva info: VA-API version 1.16.0\nlibva info: User environment variable requested driver '\"iHD\"'\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/\"iHD\"_drv_video.so\nlibva info: va_openDriver() returns -1\nvaInitialize failed with error code -1 (unknown libva error),exit", "stdout": "" }
```
 
It's unable to find the iHD driver . Any improvements to my configuration is most welcome

### Version

0.12.0-368c07c

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.xx
  user: xxxx
  password: xxxx
detectors:
   ov_detector:
    type: openvino
    device: GPU
  model:
    path: /openvino-model/ssdlite_mobilenet_v2.xml
    width: 300
    height: 300
    input_tensor: nhwc
    input_pixel_format: bgr
    labelmap_path: /openvino-model/coco_91cl_bkgr.txt
record:
  enabled: True
  retain:
    days: 5
    mode: motion
  events:
    pre_capture: 2
    post_capture: 3
    retain:
      default: 7
      mode: active_objects
cameras:
  livingroom-001:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.0.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=xxxx&password=xxxx
          roles:
            - record
            - restream
        - path: http://192.168.0.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 10
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:dev-368c07c
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/xxxx/src/frigate/config/config.yml:/config/config.yml:ro
      - /home/xxxx/src/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
    environment:
      - FRIGATE_RTSP_PASSWORD="xxxx"
      - LIBVA_DRIVER_NAME="iHD"
```

### Relevant log output

```shell
...
...
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate    | s6-linux-init-hpr: fatal: unable to talk to shutdownd: Operation not permitted
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | cont-init: info: running /etc/cont-init.d/prepare-logs.sh
frigate    | cont-init: info: /etc/cont-init.d/prepare-logs.sh exited 0
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | services-up: info: copying legacy longrun frigate (no readiness notification)
frigate    | services-up: info: copying legacy longrun go2rtc (no readiness notification)
frigate    | services-up: info: copying legacy longrun nginx (no readiness notification)
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2022-12-27 13:33:54.400202200  08:03:54.400 INF go2rtc version 0.1-rc.5 linux/amd64
frigate    | 2022-12-27 13:33:54.400338498  08:03:54.400 INF [api] listen addr=:1984
frigate    | 2022-12-27 13:33:54.400369079  08:03:54.400 INF [rtsp] listen addr=:8554
frigate    | 2022-12-27 13:33:54.400478248  08:03:54.400 INF [webrtc] listen addr=:8555
frigate    | 2022-12-27 13:33:54.400513956  08:03:54.400 INF [srtp] listen addr=:8443
frigate    | 2022-12-27 13:33:54.923737860  [2022-12-27 13:33:54] frigate.app                    INFO    : Starting Frigate (0.12.0-368c07c)
frigate    | 2022-12-27 13:33:54.938938705  Starting migrations
frigate    | 2022-12-27 13:33:54.938941812  [2022-12-27 13:33:54] peewee_migrate                 INFO    : Starting migrations
frigate    | 2022-12-27 13:33:54.941475727  There is nothing to migrate
frigate    | 2022-12-27 13:33:54.941489417  [2022-12-27 13:33:54] peewee_migrate                 INFO    : There is nothing to migrate
frigate    | 2022-12-27 13:33:54.942607920  [2022-12-27 13:33:54] ws4py                          INFO    : Using epoll
frigate    | 2022-12-27 13:33:54.950989021  [2022-12-27 13:33:54] detector.ov_detector           INFO    : Starting detection process: 409
frigate    | 2022-12-27 13:33:54.954670218  [2022-12-27 13:33:54] frigate.app                    INFO    : Output process started: 411
frigate    | 2022-12-27 13:33:54.954790605  [2022-12-27 13:33:54] ws4py                          INFO    : Using epoll
frigate    | 2022-12-27 13:33:54.954842457  [2022-12-27 13:33:54] frigate.app                    INFO    : Camera processor started for xxx-001: 415
frigate    | 2022-12-27 13:33:54.957804930  [2022-12-27 13:33:54] frigate.app                    INFO    : Capture process started for xxx-001: 417
frigate    | 2022-12-27 13:33:58.554116614  [2022-12-27 13:33:58] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
frigate    | 2022-12-27 13:33:58.554173790  [2022-12-27 13:33:58] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
frigate    | 2022-12-27 13:33:58.554195590  [2022-12-27 13:33:58] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
....
...
```

### FFprobe output from your camera

```shell
$ ffprobe "http://192.168.0.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx"
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-librubberband --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libshaderc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flv, from 'http://192.168.0.xx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=xxxx&password=xxxx':
  Metadata:
    displayWidth    : 896
    displayHeight   : 512
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 896x512, 21 fps, 24.92 tbr, 1k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```
```


### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Reolink 810A with latest firmware - v3.1.0.956_22041503

### Any other information that may be helpful

Here is Reolink configuration -
![image](https://user-images.githubusercontent.com/6565597/209632055-42cac0f9-c65b-492e-9c56-a343d3fe46d7.png)

![image](https://user-images.githubusercontent.com/6565597/209632144-2d51ffd3-d532-43ad-af2d-dccb02f0d192.png)
