### ISSUE TITLE
Clips resulting in multiple videos because person is briefly not detected then detected again

### ISSUE THREAD

**Issue by Eeeeeediot** [blakeblackshear/frigate#481]
**Describe the bug**
A person delivered something to my door and because he bent down out of sight  for a split second frigate stopped detecting him. This has resulted in me having two saved clips which are essentially the one episode of object detection. mp4 are attached.

Is it possible to build in a brief delay so that is object detection stops for a brief time then there is an offset that if it starts again then it counted as one episode?

EDIT: I have video files but they show my reg plates for cars and I don't know how to block them out so removed them form post. I can share them with you privately if you like.

**Version of frigate**
HassOS Addon and custom_components

**Config file**
Include your full config file wrapped in triple back ticks.
```
detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3
mqtt:
  host: 192.168.0.200
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxx
  password: xxxxx
ffmpeg:
  global_args: '-hide_banner -loglevel fatal'
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    record: >-
      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    clips: >-
      -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an
    rtmp: '-c copy -f flv'
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: 'rtsp://xxxxx@xxxxxxx:554//h264Preview_01_sub'
          roles:
            - detect
            - clips
            - record
            - rtmp
    width: 640
    height: 480
    fps: 4
    mask: 'poly,0,0,0,168,232,94,290,110,341,125,380,129,372,0'
    best_image_timeout: 60
    save_clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain_days: 2
    rtmp:
      enabled: true
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
  garden:
    ffmpeg:
      inputs:
        - path: 'rtsp://xxxxxxxx@xxxxxxxx:554//h264Preview_01_sub'
          roles:
            - detect
            - clips
            - record
            - rtmp
    width: 640
    height: 480
    fps: 4
    mask: 'poly,639,333,622,289,543,162,540,143,496,80,469,75,317,0,639,0'
    best_image_timeout: 60
    save_clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: true
      retain_days: 2
    rtmp:
      enabled: true
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
logger:
  default: info
  logs:
    frigate.mqtt: error
database:
  path: /media/frigate/clips/frigate.db
model:
  height: 320
  width: 320
save_clips:
  max_seconds: 300
  tmpfs_cache_size: 512m
  retain:
    default: 10
    objects:
      person: 15
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7
motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
detect:
  max_disappeared: 10

```
