### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by macnug** [blakeblackshear/frigate#4815]
### Describe the problem you are having

HW:
iNTEL -NUC10I5  with 8GB or ram
Proxmox with 2 VM
Frigate run on HA addon
Coral tpu on usb
3 Dahua PoE cams 
-1  IPC-HDBW2531E-S-S2
-2  IPC-HFW2230S-S-S2

I didn't have issue for at least one year, now i figure out several errors from the log that prevent the correct functioning of the detection function.

Moreover as you can see from my config i tried with different Hwacc but i always had green screen on camera's live view. Any suggestion on my config code would be much appreciated.

Thankyou

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: XXXX
  stats_interval: 60


detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db    

model:
    # Optional: path to the model (default: automatic based on detector)
#  path: /edgetpu_model.tflite
    # Optional: path to the labelmap (default: shown below)
#  labelmap_path: /labelmap.txt
    # Required: Object detection model input width (default: shown below)
  width: 320
    # Required: Object detection model input height (default: shown below)
  height: 320


logger:
  default: info
  logs:
    frigate.event: debug

#environment_vars:
#  EXAMPLE_VAR: value

birdseye:
  enabled: true
  width: 1920
  height: 1080
  quality: 8
  mode: continuous
  
#ffmpeg:

    # Optional: global ffmpeg args (default: shown below)
#  global_args: -hide_banner -loglevel warning
    # Optional: global hwaccel args (default: shown below)
    # NOTE: See hardware acceleration docs for your specific device
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
    # Optional: global input args (default: shown below)
#  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
    # Optional: global output args
#  output_args:
      # Optional: output args for detect streams (default: shown below)
#    detect: -f rawvideo -pix_fmt yuv420p
      # Optional: output args for record streams (default: shown below)
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an


################################################################################  

cameras:
  Entrata:
    ffmpeg:
#      global_args: -hide_banner -loglevel warning
#      hwaccel_args: -hwaccel vaapi -hwaccel_device -hwaccel_output_format yuv420p
#      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1          
      inputs:
        - path: rtsp://admin:XXXX@192.168.1.101/live
          roles:
            - record
#            - detect
        - path: rtsp://admin:XXXX@192.168.1.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    best_image_timeout: 60
    
    rtmp:
      enabled: false
      
    motion:
      mask:
        - 1280,269,1280,0,871,0,880,94
      improve_contrast: true  
    
    detect:
      enabled: True
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      enabled: true
      retain:
          days: 0
      
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - bird
          - dog
        retain:
          default: 10

    live:
      height: 1080
      quality: 1    

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 15

    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 1080
      required_zones: []

    objects:
      track:
        - person
        - bird
        - cat
        - dog
      filters:
        person:
          threshold: 0.70
          mask:
            - 1280,269,1280,0,871,0,880,94
        bird:
          threshold: 0.70
          mask:
            - 1280,269,1280,0,871,0,880,94
        cat:
          threshold: 0.70
          mask:
            - 1280,269,1280,0,871,0,880,94
        dog:
          threshold: 0.70
          mask:
            - 1280,269,1280,0,871,0,880,94           
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below

########################################################################################################################
  Loggiato:
    ffmpeg:
#      global_args: -hide_banner -loglevel warning
#      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1  
      inputs:
        - path: rtsp://admin:XXXX@192.168.1.100/live
          roles:
            - record
#            - detect
        - path: rtsp://admin:XXX@192.168.1.100:554/cam/realmonitor?channel=1&subtype=1
          roles: 
            - detect
    best_image_timeout: 60
    
    rtmp:
      enabled: false
      
    motion:
      mask:
        - 0,514,0,720,348,720,350,634,328,182
        - 937,67,1280,77,1280,25,943,26

      improve_contrast: true
    
    detect:
      enabled: True
      width: 1920
      height: 1080
      max_disappeared: 25
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      enabled: true
      retain:
          days: 0
      
      events:
        #max_seconds: 300
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - bird
          - dog
        retain:
          default: 10

    live:
      height: 1080
      quality: 1  

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 15

    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 1080
      required_zones: []

    objects:
      track:
        - person
        - bird
        - cat
        - dog
      filters:
        person:
          threshold: 0.70

        bird:
          threshold: 0.70

        cat:
          threshold: 0.70

        dog:
          threshold: 0.70
        
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below

########################################################################################################################
  Piscina:
    ffmpeg:
#      global_args: -hide_banner -loglevel warning
#      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1  
      inputs:
        - path: rtsp://admin:XXX@192.168.1.108/live
          roles:
            - record
#            - detect
        - path: rtsp://admin:XXXX@192.168.1.108:554/cam/realmonitor?channel=1&subtype=1
          roles: 
            - detect
    best_image_timeout: 60
    
    rtmp:
      enabled: false
    
      
    zones:
      dentro_piscina: 
        coordinates: 741,640,1280,492,1280,138,607,371,246,481,171,668
        objects:
          - person
        
    motion:
      mask:
        - 1280,0,948,0,953,71,1280,80
        - 658,0,0,0,0,439


      improve_contrast: true
    
    detect:
      enabled: True
      max_disappeared: 25
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      enabled: true
      retain:
          days: 0
      
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        retain:
          default: 10

    live:
      height: 1080
      quality: 1  

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 15

    mqtt:
      enabled: True
      timestamp: true
      bounding_box: True
      crop: true
      height: 1080
      required_zones: []

    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.70

        bird:
          threshold: 0.70

        cat:
          threshold: 0.70

        dog:
          threshold: 0.70
        
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below


########################################################################################################################
```

### Relevant log output

```shell
have this error that compares several time in a loop.

"[2022-12-29 22:59:01] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2022-12-29 22:59:01] root                            INFO    : Waiting for detection process to exit gracefully...
[2022-12-29 22:59:31] root                            INFO    : Detection process didnt exit. Force killing...
[2022-12-29 22:59:31] detector.coral                  INFO    : Starting detection process: 456
[2022-12-29 22:59:31] frigate.edgetpu                 INFO    : Attempting to load TPU as usb
[2022-12-29 22:59:34] frigate.edgetpu                 INFO    : TPU found

The second is:

[2022-12-29 22:59:34] ffmpeg.Piscina.detect         ERROR : [swscaler @ 0x564b87b79c80] [swscaler @ 0x564b87bc0d00] deprecated pixel format used, make sure you did set range correctly
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
