### ISSUE TITLE
[Support]: Frigate is triggering events without zones

### ISSUE THREAD

**Issue by setterlee** [blakeblackshear/frigate#4818]
### Describe the problem you are having

I have required zones for record and snapshots in my cameras configs but I just received an event without zone in home assistant but show zone in the frigate UI

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 127.0.0.1
  user: homeassistant
  password: m$030mbn
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxxx@192.168.4.11:554/stream1
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    objects:
      track:
        - person
        - cat
      mask: 0,415,660,320,1371,300,1929,343,2374,394,2401,292,2560,368,2560,0,0,0
    detect:
      width: 2560
      height: 1440
    motion:
      mask: 0,415,660,320,1371,300,1929,343,2374,394,2401,292,2560,368,2560,0,0,0
    zones:
      frontis_izquierdo:
        coordinates: 216,374,1102,292,1612,322,1902,338,2179,368,2370,391,2399,296,2560,366,2560,1440,0,1440,0,421
    record:
      events:
        required_zones:
          - frontis_izquierdo
    snapshots:
      required_zones:
        - frontis_izquierdo
  camera_2:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxxx@192.168.4.12:554/stream1
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    objects:
      track:
        - person
        - cat
      mask: 0,167,176,108,312,77,359,38,506,26,914,24,1459,55,1884,136,2120,207,2261,268,2413,332,2560,388,2560,0,0,0
    motion:
      mask: 0,167,176,108,312,77,359,38,506,26,914,24,1459,55,1884,136,2120,207,2261,268,2413,332,2560,388,2560,0,0,0
    detect:
      width: 2560
      height: 1440
    zones:
      terraza_principal:
        coordinates: 0,1440,2560,1440,2560,740,2452,669,0,1046
        filters:
          person:
            min_area: 125000
          cat:
            min_area: 20000
            max_area: 60000
      jardin:
        coordinates: 2465,671,0,1057,0,163,246,77,266,271,874,231,1277,246,1580,255,1794,284,1789,368
        filters:
          person:
            min_area: 19000
          cat:
            min_area: 5000
      estacionamiento:
        coordinates: 1790,363,1812,282,2106,323,2122,218,2560,390,2560,733
        filters:
          person:
            min_area: 15000
          cat:
            min_area: 5000
      terraza_posterior:
        coordinates: 365,31,713,22,1105,26,1466,59,1891,132,1986,165,2113,203,2091,324,1570,262,1237,255,257,284,249,68
        filters:
          person:
            min_area: 5000
    record:
      events:
        required_zones:
          - terraza_principal
          - jardin
          - estacionamiento
          - terraza_posterior
    snapshots:
      required_zones:
        - terraza_principal
        - jardin
        - estacionamiento
        - terraza_posterior
  camera_3:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxxx@192.168.4.13:554/stream1
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    objects:
      track:
        - person
        - cat
      mask: 0,776,454,543,946,335,1504,173,1585,165,1582,296,1932,313,1936,180,1838,0,0,0
    motion:
      mask:
        - 0,776,454,543,946,335,1504,173,1585,165,1582,296,1932,313,1936,180,1838,0,0,0
        - 1961,126,1990,121,1981,97,1944,92
    detect:
      width: 2560
      height: 1440
    zones:
      estacionamiento_frontal:
        coordinates: 2560,680,2560,0,1826,0,1923,184,1927,307,1585,277,1578,157,1517,165,1374,200,947,328,449,520
        filters:
          person:
            min_area: 20000
      estacionamiento_trasero:
        coordinates: 0,1440,2560,1440,2560,676,1543,566,583,519,445,531,0,757
        filters:
          person:
            min_area: 60000
    record:
      events:
        required_zones:
          - estacionamiento_frontal
          - estacionamiento_trasero
    snapshots:
      required_zones:
        - estacionamiento_frontal
        - estacionamiento_trasero
  camera_4:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxxx@192.168.4.14:554/stream1
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    objects:
      track:
        - person
        - cat
      mask: 0,432,291,192,563,0,0,0
    motion:
      mask:
        - 0,432,291,192,563,0,0,0
        - 890,254,1170,254,1172,0,864,0
        - 237,1440,873,1440,797,1210,303,1152
    detect:
      width: 2560
      height: 1440
    zones:
      solar:
        coordinates: 1985,1440,0,1440,0,406,348,150,570,0,836,0,867,341,1653,348
        filters:
          person:
            min_area: 150000
          cat:
            max_area: 50000
      terraza_principal:
        coordinates: 1668,139,947,137,938,0,814,0,848,418,1655,392
        filters:
          person:
            min_area: 50000
      jardin:
        coordinates: 975,165,971,0,1688,0,1680,161
        filters:
          person:
            min_area: 10000
    record:
      events:
        required_zones:
          - solar
          - terraza_principal
          - jardin
    snapshots:
      required_zones:
        - solar
        - terraza_principal
        - jardin
  camera_5:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxxx@192.168.4.15:554/stream1
          roles:
            - detect
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    objects:
      track:
        - person
        - cat
      mask:
        - 2560,0,2178,0,2560,491
        - 1766,69,1708,58,1703,38,1397,22,681,58,270,150,216,0,1732,0,1806,0,1797,181,1756,178
    motion:
      mask:
        - 2560,0,2178,0,2560,491
        - 1766,69,1708,58,1703,38,1397,22,681,58,270,150,216,0,1732,0,1806,0,1797,181,1756,178
    detect:
      width: 2560
      height: 1440
    zones:
      frontis_derecho:
        coordinates: 1902,181,1692,22,1074,22,598,65,261,136,458,611,676,929,455,1440,2254,1440
        filters:
          person:
            min_area: 150000
          cat:
            max_area: 50000
    record:
      events:
        required_zones:
          - frontis_derecho
    snapshots:
      required_zones:
        - frontis_derecho
 
rtmp:
  enabled: False
record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
snapshots:
  enabled: True
  retain:
    default: 30
birdseye:
  enabled: True
  mode: motion
  width: 1280
  height: 720
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
```

### Relevant log output

```shell
this:
  entity_id: automation.movimiento_detectado_camera_1
  state: 'on'
  attributes:
    last_triggered: '2022-12-30T12:05:36.961685+00:00'
    mode: single
    current: 1
    id: '1666485822918'
    friendly_name: Persona detectada en camaras
  last_changed: '2022-12-29T20:01:26.437667+00:00'
  last_updated: '2022-12-30T12:05:36.961792+00:00'
  context:
    id: 01GNHERRJ0FWAMKQCY6R1NH1YG
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: mqtt
  topic: frigate/events
  payload: >-
    {"before": {"id": "1672401938.063385-l1ghte", "camera": "camera_5",
    "frame_time": 1672401938.063385, "snapshot_time": 0.0, "label": "person",
    "sub_label": null, "top_score": 0.0, "false_positive": true, "start_time":
    1672401938.063385, "end_time": null, "score": 0.640625, "box": [239, 170,
    480, 574], "area": 97364, "ratio": 0.5965346534653465, "region": [144, 130,
    632, 618], "stationary": false, "motionless_count": 0, "position_changes":
    0, "current_zones": [], "entered_zones": [], "has_clip": false,
    "has_snapshot": false}, "after": {"id": "1672401938.063385-l1ghte",
    "camera": "camera_5", "frame_time": 1672401938.460854, "snapshot_time":
    1672401938.460854, "label": "person", "sub_label": null, "top_score":
    0.82421875, "false_positive": false, "start_time": 1672401938.063385,
    "end_time": null, "score": 0.82421875, "box": [286, 167, 689, 717], "area":
    221650, "ratio": 0.7327272727272728, "region": [96, 74, 796, 774],
    "stationary": false, "motionless_count": 1, "position_changes": 1,
    "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot":
    false}, "type": "new"}
  qos: 0
  description: mqtt topic frigate/events
  payload_json:
    before:
      id: 1672401938.063385-l1ghte
      camera: camera_5
      frame_time: 1672401938.063385
      snapshot_time: 0
      label: person
      sub_label: null
      top_score: 0
      false_positive: true
      start_time: 1672401938.063385
      end_time: null
      score: 0.640625
      box:
        - 239
        - 170
        - 480
        - 574
      area: 97364
      ratio: 0.5965346534653465
      region:
        - 144
        - 130
        - 632
        - 618
      stationary: false
      motionless_count: 0
      position_changes: 0
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
    after:
      id: 1672401938.063385-l1ghte
      camera: camera_5
      frame_time: 1672401938.460854
      snapshot_time: 1672401938.460854
      label: person
      sub_label: null
      top_score: 0.82421875
      false_positive: false
      start_time: 1672401938.063385
      end_time: null
      score: 0.82421875
      box:
        - 286
        - 167
        - 689
        - 717
      area: 221650
      ratio: 0.7327272727272728
      region:
        - 96
        - 74
        - 796
        - 774
      stationary: false
      motionless_count: 1
      position_changes: 1
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
    type: new
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://xxxx:xxxxx@192.168.4.15:554/stream1':
  Metadata:
    title           : HTMS
    comment         : stream1
  Duration: N/A, start: 0.040625, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2560x1440, 15 fps, 15 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{
    "camera_1": {
        "camera_fps": 5.1,
        "capture_pid": 231,
        "detection_fps": 0.0,
        "pid": 223,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "camera_2": {
        "camera_fps": 5.1,
        "capture_pid": 235,
        "detection_fps": 0.0,
        "pid": 224,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "camera_3": {
        "camera_fps": 5.1,
        "capture_pid": 240,
        "detection_fps": 0.0,
        "pid": 226,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "camera_4": {
        "camera_fps": 5.1,
        "capture_pid": 244,
        "detection_fps": 0.0,
        "pid": 228,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "camera_5": {
        "camera_fps": 5.0,
        "capture_pid": 251,
        "detection_fps": 0.0,
        "pid": 230,
        "process_fps": 5.0,
        "skipped_fps": 0.0
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 10.07,
            "pid": 215
        }
    },
    "service": {
        "latest_version": "0.11.1",
        "storage": {
            "/dev/shm": {
                "free": 867.0,
                "mount_type": "tmpfs",
                "total": 897.6,
                "used": 30.6
            },
            "/media/frigate/clips": {
                "free": 339060.4,
                "mount_type": "ext4",
                "total": 489997.2,
                "used": 125971.1
            },
            "/media/frigate/recordings": {
                "free": 339060.4,
                "mount_type": "ext4",
                "total": 489997.2,
                "used": 125971.1
            },
            "/tmp/cache": {
                "free": 997.1,
                "mount_type": "tmpfs",
                "total": 1000.0,
                "used": 2.9
            }
        },
        "temperatures": {},
        "uptime": 62076,
        "version": "0.11.1-2eada21"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Asecam

### Any other information that may be helpful

the event on frigate showing the zone

![image](https://user-images.githubusercontent.com/6598795/210069664-9dcc99a3-42fb-47b3-8cc8-46f0d8c80a23.png)
