### ISSUE TITLE
[Support]: Home Assistant object detected binary sensors repeatedly showing unavailable

### ISSUE THREAD

**Issue by Morphy99** [blakeblackshear/frigate#4835]
### Describe the problem you are having

I've noticed that several of the binary sensors for objects keep becoming unavailable in the HA logbook:

![image](https://user-images.githubusercontent.com/5853979/210129013-62bb1537-0eec-4d89-8a17-9dc023a7f957.png)

I'm not even sure why this sensor is enabled as I only have these objects on this camera:
```
    record:
      events:
        retain:
          default: 10
        objects:
          - person
          - cat
          - dog
```
However, I have noticed the same for other allowed objects as well. So, two issues really:
1. Object detected sensors being enabled in HA despite being filtered out at a camera level.
2. Detect sensors repeatedly showing unavailable.

This may be a HA or MQTT issue as now I'm doing some digging I can see tasmota devices showing unavailable intermittently as well, but not nearly as often as Frigate entities. 

I've been looking at the MQTT and struggling to see where these object detected messages are? I've checked frigate/events and frigate/back_patio but can't see any messages despite entries in the HA logbook showing up.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: i965
mqtt:
  host: xxx.xxx.xxx.xxx
  user: x
  password:x

detectors:
  coral_pci:
    type: edgetpu
    device: pci
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
#  logs:
 #   frigate.mqtt: debug
  #  frigate.event: debug
#birdseye:
#  enabled: True
#  width: 1280
#  height: 720
#  quality: 8
#  mode: continuous

objects:
  track:
    - person
    - car
    - cat
    - dog
  filters:
    person:
      threshold: 0.7
      max_ratio: 0.6

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 20
      mode: all
    pre_capture: 2
    post_capture: 10

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 20

detect:
  stationary:
    interval: 10

ffmpeg:
  hwaccel_args: -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

cameras:
  back_patio:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
      output_args: 
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: http://xxx.xxx.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=x&password=x
          roles:
            - record
            - rtmp
        - path: http://xxx.xxx.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=x&password=x
          roles:
            - detect
    detect:
      width: 896 #2560
      height: 672 #1920
      fps: 7 #5
    mqtt:
      required_zones:
        - back_patio_left
        - back_patio_right
        - back_patio_steps
        - back_patio_shed
    live:
      height: 1080
      quality: 15
    record:
      events:
        retain:
          default: 10
        objects:
          - person
          - cat
          - dog
        required_zones:
          - back_patio_left
          - back_patio_right
          - back_patio_steps
          - back_patio_shed
    snapshots:
      required_zones:
        - back_patio_left
        - back_patio_right
        - back_patio_steps
        - back_patio_shed
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          threshold: 0.8
    zones:
      back_patio_left:
        coordinates: 729,0,322,0,321,323,690,314
        filters:
          person:
            min_area: 10000
            max_area: 50000
            threshold: 0.8
      back_patio_right:
        coordinates: 391,672,896,672,896,410,785,323,562,323,388,328,391,544
        filters:
          person:
            min_area: 30000
            threshold: 0.8
      back_patio_steps:
        coordinates: 155,303,122,147,0,152,0,48,315,54,310,246,310,330,383,334,388,470,184,468,184,413
        filters:
          person: 
            min_area: 75000
            threshold: 0.8
      back_patio_shed:
        coordinates: 122,149,169,476,391,474,390,672,0,672,0,174
        filters:
          person:
            min_area: 100000
            threshold: 0.8
    motion:
      mask:
        - 396,0,397,46,0,42,0,0
        - 326,41,256,144,133,108,128,40
```

### Relevant log output

```shell
No relevant logs in Frigate or MQTT
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink RLC-510WA
