### ISSUE TITLE
[Config Support]: Avoiding recordings of parked car

### ISSUE THREAD

**Issue by totalitarian** [blakeblackshear/frigate#4841]
### Describe the problem you are having

This is my driveway, car and a zone called driveway_entrance

![image](https://user-images.githubusercontent.com/2385696/210165809-9bfd2d5e-e0c3-4a1f-902b-5727607fd0ce.png)

Even though I have set a small zone at the entrance to my driveway and added this zone to my required_zones, I still get recordings of my car sat in my driveway when stationary.

Any ideas how to only get recordings when the car enters the driveway?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
objects:
      track:
        - person
        - car
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 40000
        car:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 50000
    record:
      events:
        required_zones:
          - driveway_entrance
    snapshots:
      bounding_box: True
      required_zones:
        - driveway_entrance
    zones:
      driveway:
        coordinates: 2560,892,2560,1440,0,1440,0,668,525,635,534,889
      driveway_entrance:
        coordinates: 453,794,277,856,2154,862,1948,800
        objects:
          - car
          - person
      street:
        coordinates: 2560,409,2560,749,633,728,633,394
```

### Relevant log output

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
Change your recording retention mode https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

**Comment by totalitarian** [comment]
> Change your recording retention mode https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

Sorry I should have included my current settings for that. What should I change it to?

```
record:
  enabled: True
  retain:
    days: 8
    mode: motion
  events:
    pre_capture: 2
    post_capture: 2
    retain:
      default: 16
      mode: active_objects
```
