### ISSUE TITLE
[Support]: MSE camera view failing under Firefox.

### ISSUE THREAD

**Issue by ashleyw-gh** [blakeblackshear/frigate#4861]
### Describe the problem you are having

Just a heads up: I updated to 0.12.0-beta1, and noticed that the camera view (using mse) is not working under Firefox. On firefox I have to switch to jsmpeg, but then the resolution seems to drop to the standard detect resolution.
mse works under Chrome fine. 
I suspect the problem is Firefox specific as there seem to be long standing issues with mse support under Firefox.
(I had to add the restream role under the roles on the high resolution main stream).
thanks - great work with the 0,12 beta though!
It's great to see the high res real-time feed though on the camera view under Chrome!

### Version

0.12.0-beta1

### Frigate config file

```yaml
database:
  path: /db/frigate.db
mqtt:
  host: <mqtthost>
  port: 1883
  topic_prefix: frigate
  user: <mqttuser>
  password: <mqttpassword>
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1
model:
  labelmap:
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://<user:pwd>@<camerafront>:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user:pwd>@<camerafront>:554/h264Preview_01_main
          roles:
            - record
            - rtmp
            - restream
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 2
    motion:
      mask:
        - 196,0,196,26,0,27,0,0
    objects:
      filters:
        person:
          min_area: 700
          mask:
            - 230,230,352,229,353,288,235,294
      track:
        - person
        - animal
  back:
    ffmpeg:
      inputs:
        - path: rtsp://<user:pwd>@<cameraback>:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://<user:pwd>@<cameraback>:554/h264Preview_01_main
          roles:
            - record
            - rtmp
            - restream
    detect:
      width: 640
      height: 360
    record:
      enabled: True
      retain:
        days: 2
    motion:
      mask:
        - 490,195,489,308,558,308,606,127,565,93,499,103
        - 640,0,640,73,320,87,226,107,130,142,91,275,78,328,0,330,0,0
    objects:
      filters:
        person:
          min_area: 700
          mask:
            - 488,283,592,285,594,312,492,312
      track:
        - person
        - animal
motion:
  improve_contrast: True
record:
  enabled: True
  events:
    retain:
      default: 2
      mode: all
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 2
birdseye:
  enabled: True
  mode: continuous
```

### Relevant log output

```shell
not relevant.
```

### FFprobe output from your camera

```shell
not relevant.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink RLC-811A
