### ISSUE TITLE
Green/blurry thumbnail images in clips

### ISSUE THREAD

**Issue by jlaitinen81** [blakeblackshear/frigate#487]
**Describe the bug**
The thumbnail images of stored clips in Media Browser are often green/blurry, even if the actual video looks perfect.

**Version of frigate**
Version 1.2 (0.8.0 Beta 3)

**Config file**
Include your full config file wrapped in triple back ticks.
```
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.1.2
  user:
  password:
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p
cameras:
  YiCamera1:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.1.230/ch0_0.h264'
          roles:
            - detect
            - rtmp
            - clips
    save_clips:
      enabled: true
    height: 1080
    width: 1920
    fps: 5
  YiCameraDome:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.1.193/ch0_0.h264'
          roles:
            - detect
            - rtmp
            - clips
    save_clips:
      enabled: true
    height: 1080
    width: 1920
    fps: 5
save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 30
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      min_score: 0.5
      threshold: 0.8
```

**Logs**
```
nothing relevant
```

**Frigate debug stats**
```
Don't know what this means
```

**FFprobe from your camera**

Run the following command and paste output below
```
I do not have terminal access to Home Assistant
```

**Screenshots**

![image](https://user-images.githubusercontent.com/67101282/103939787-faa1f780-5134-11eb-91bb-ccd95866ac69.png)

**Computer Hardware**
 - Host Operating System: Home Assistant OS 5.9
 - Update Channel: stable
 - Supervisor Version: 2020.12.7
 - Docker Version: 19.03.13
 - Healthy: true
 - Supported: true
 - Board: intel-nuc
 - Coral Version: USB
 - Network Setup: Wired 1000Mbps

**Camera Info:**
 - Manufacturer: Yi 1080p Camera Dome
 - Model: h201c
 - Resolution: 1080p
 - FPS: 5

**Comment by segator** [comment]
I have same issue

**Comment by Parlane** [comment]
If your cameras support it try using rtmp instead.

I am using frigate 8.0-beta3 with the following camera config and rfeolink cameras:

```
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.1.240/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password={FRIGATE_RTSP_PASSWORD}
          roles:
            - detect
            - rtmp
            - clips
            - record
          global_args:
            - -hide_banner
            - -loglevel
            - panic
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - '1'
```

**Comment by jlaitinen81** [comment]
Thanks, but unfortunately I think the Yi cams only provide an rtsp stream.

**Comment by blakeblackshear** [comment]
Can you try connecting to the stream with vlc or something else and making sure the resolution is truly 1920x1080? This is almost always because the resolution is not right. The clips and camera streams are totally different, so it is definitely possible for the clips and streams to work fine while the images are messed up.

**Comment by jlaitinen81** [comment]
That was it! The dome actually streams 1920x1088. Thank you!

One more thing... looking at my config, how can I change the detection to be done on a low quality stream and for the storing use the high quality stream currently used for both detection and recording of clips?

**Comment by blakeblackshear** [comment]
Something like below. You will need to update the width and height to match the substream.

```yaml
...
cameras:
  YiCamera1:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.1.230/ch0_1.h264'
          roles:
            - detect
        - path: 'rtsp://192.168.1.230/ch0_0.h264'
          roles:
            - rtmp
            - clips
    save_clips:
      enabled: true
    height: 480
    width: 640
    fps: 5
 ...
```
