### ISSUE TITLE
[Camera Support]: 0.12-beta1 ReoLink Cameras No Longer Recording

### ISSUE THREAD

**Issue by jonadis** [blakeblackshear/frigate#4874]
### Describe the problem you are having

After upgrading to 0.12-beta1, previously working ReoLink RLC-410 cameras are no longer recording, but are still detecting, live streaming, etc okay.

### Version

0.12.0-53D39A1

### Frigate config file

```yaml
garage_se:
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: rtsp://localhost:8554/garage_se
          roles:
            - record
        - path: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED
          roles:
            - restream
        - path: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=REDACTED
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 7
```

### Relevant log output

```shell
2023-01-03 13:35:24	
2023-01-03 13:35:24.599812586  [2023-01-03 13:35:24] watchdog.garage_se             INFO    : Waiting for ffmpeg to exit gracefully...


2023-01-03 13:35:24	
2023-01-03 13:35:24.599331111  [2023-01-03 13:35:24] watchdog.garage_se             INFO    : Terminating the existing ffmpeg process...
2023-01-03 13:35:24	
2023-01-03 13:35:24.598377835  [2023-01-03 13:35:24] watchdog.garage_se             ERROR   : No new recording segments were created for garage_se in the last 120s. restarting the ffmpeg record process...
```

### FFprobe output from your camera

```shell
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1920, "width": 2560 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } }, { "return_code": 0, "stderr": {}, "stdout": {} }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "25/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 672, "width": 896 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]
```

### Frigate stats

```json
{"chicken":{"camera_fps":15.0,"capture_pid":372,"detection_fps":0.0,"ffmpeg_pid":399,"pid":350,"process_fps":15.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.5"},"1":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"0.0","mem":"0.1"},"113":{"cpu":"0.0","mem":"0.1"},"114":{"cpu":"0.0","mem":"0.1"},"115":{"cpu":"0.0","mem":"0.1"},"116":{"cpu":"0.0","mem":"0.1"},"125":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"2454":{"cpu":"0.0","mem":"0.0"},"2455":{"cpu":"0.0","mem":"0.0"},"2456":{"cpu":"6.7","mem":"0.4"},"2463":{"cpu":"0.0","mem":"0.0"},"2469":{"cpu":"0.0","mem":"0.0"},"2470":{"cpu":"0.0","mem":"0.2"},"2487":{"cpu":"0.0","mem":"0.0"},"2489":{"cpu":"40.0","mem":"0.4"},"25":{"cpu":"0.0","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"332":{"cpu":"0.0","mem":"1.0"},"338":{"cpu":"1.7","mem":"0.1"},"339":{"cpu":"1.0","mem":"1.4"},"340":{"cpu":"7.0","mem":"1.2"},"350":{"cpu":"1.7","mem":"1.2"},"361":{"cpu":"0.0","mem":"0.2"},"362":{"cpu":"9.6","mem":"1.2"},"363":{"cpu":"2.3","mem":"1.2"},"364":{"cpu":"0.0","mem":"0.2"},"365":{"cpu":"2.0","mem":"1.2"},"366":{"cpu":"0.0","mem":"0.2"},"367":{"cpu":"2.0","mem":"1.2"},"368":{"cpu":"2.3","mem":"1.2"},"369":{"cpu":"2.0","mem":"1.2"},"370":{"cpu":"0.0","mem":"0.2"},"371":{"cpu":"0.0","mem":"1.1"},"372":{"cpu":"3.7","mem":"1.1"},"373":{"cpu":"5.3","mem":"1.1"},"374":{"cpu":"0.0","mem":"0.2"},"375":{"cpu":"3.0","mem":"1.1"},"382":{"cpu":"2.7","mem":"1.1"},"383":{"cpu":"11.6","mem":"0.7"},"384":{"cpu":"6.3","mem":"0.7"},"385":{"cpu":"4.3","mem":"1.1"},"388":{"cpu":"4.3","mem":"1.1"},"389":{"cpu":"0.0","mem":"0.2"},"391":{"cpu":"2.3","mem":"1.1"},"394":{"cpu":"0.0","mem":"1.1"},"399":{"cpu":"6.0","mem":"1.1"},"402":{"cpu":"7.6","mem":"0.3"},"403":{"cpu":"6.6","mem":"0.8"},"407":{"cpu":"6.6","mem":"0.4"},"409":{"cpu":"8.3","mem":"0.8"},"411":{"cpu":"0.0","mem":"0.2"},"412":{"cpu":"12.0","mem":"0.3"},"422":{"cpu":"6.0","mem":"0.3"},"425":{"cpu":"11.3","mem":"0.4"},"426":{"cpu":"0.0","mem":"0.2"},"428":{"cpu":"0.0","mem":"0.3"},"431":{"cpu":"6.6","mem":"0.8"},"434":{"cpu":"10.3","mem":"0.3"},"435":{"cpu":"0.0","mem":"0.2"},"438":{"cpu":"0.0","mem":"0.3"},"444":{"cpu":"2.7","mem":"0.3"},"456":{"cpu":"7.3","mem":"0.3"},"698":{"cpu":"10.0","mem":"0.4"},"72":{"cpu":"0.0","mem":"0.0"},"74":{"cpu":"0.0","mem":"0.0"},"75":{"cpu":"0.0","mem":"0.0"},"76":{"cpu":"0.0","mem":"0.0"},"77":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"10.3","mem":"2.2"},"82":{"cpu":"8.0","mem":"0.3"},"83":{"cpu":"0.0","mem":"0.0"},"84":{"cpu":"0.0","mem":"0.0"},"871":{"cpu":"8.3","mem":"0.8"},"93":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"5556.5","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"3"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":10.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.54,"pid":339}},"front_door":{"camera_fps":30.2,"capture_pid":373,"detection_fps":10.1,"ffmpeg_pid":383,"pid":362,"process_fps":29.9,"skipped_fps":0.0},"front_porch":{"camera_fps":15.1,"capture_pid":375,"detection_fps":0.0,"ffmpeg_pid":384,"pid":363,"process_fps":15.1,"skipped_fps":0.0},"garage":{"camera_fps":15.2,"capture_pid":382,"detection_fps":0.0,"ffmpeg_pid":403,"pid":365,"process_fps":15.2,"skipped_fps":0.0},"garage_se":{"camera_fps":15.0,"capture_pid":385,"detection_fps":0.0,"ffmpeg_pid":409,"pid":367,"process_fps":15.0,"skipped_fps":0.0},"garage_sw":{"camera_fps":15.1,"capture_pid":388,"detection_fps":0.0,"ffmpeg_pid":871,"pid":368,"process_fps":15.2,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"7.94 %","mem":"- %"}},"mud_room":{"camera_fps":15.1,"capture_pid":391,"detection_fps":0.0,"ffmpeg_pid":431,"pid":369,"process_fps":15.1,"skipped_fps":0.0},"pole_barn_porch":{"camera_fps":0.0,"capture_pid":394,"detection_fps":0.0,"ffmpeg_pid":2461,"pid":371,"process_fps":0.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":528.5,"mount_type":"tmpfs","total":536.9,"used":8.3},"/media/frigate/clips":{"free":991065.0,"mount_type":"btrfs","total":1050223.3,"used":58218.2},"/media/frigate/recordings":{"free":991065.0,"mount_type":"btrfs","total":1050223.3,"used":58218.2},"/tmp/cache":{"free":976.3,"mount_type":"tmpfs","total":1000.0,"used":23.7}},"temperatures":{"apex_0":39.05},"uptime":548,"version":"0.12.0-53d39a1"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

reolink rlc-410

### Any other information that may be helpful

pointing VLC to rtsp://_frigate_host_IP_:8554/garage_se
works fine, I see the camera stream in VLC as expected

**Comment by NickM-27** [comment]
This is a good point, you can't mix presets like that. the `preset-http-reolink` is only for the HTTP reolink stream like you have for detect. However, `input_args` are also used for the record which is RTSP so of course it won't work. Instead you need to set it up like this

```yaml
garage_se:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage_se
          roles:
            - record
        - path: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=REDACTED
          roles:
            - restream
        - path: http://10.0.71.199/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=REDACTED
          input_args: preset-http-reolink
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 7
```
