### ISSUE TITLE
[Config Support]: KeyError: 'FRIGATE_MQTT_PASSWORD'

### ISSUE THREAD

**Issue by jritsema** [blakeblackshear/frigate#4878]
### Describe the problem you are having

I don't see it in the docs but according to [this issue](https://github.com/blakeblackshear/frigate/issues/1662), it looks like Frigate supports environment variables in the config file.  I have successfully gotten frigate up and running, however, when I add the following configuration, I'm getting an error.  What am I doing wrong?

```yaml
version: "3.5"
services:

  rtsp:
    container_name: rtsp
    image: mpromonet/v4l2rtspserver:v0.3.7
    ports:
      - "8554:8554"
    devices:
      - "/dev/video0:/dev/video0"
    command: ["-U", "${RTSP_USER}:${RTSP_PASSWORD}", "-G","640x480x25", "-S"]

  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.11.1
    privileged: true
    restart: unless-stopped
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml:ro
      - ./frigate/storage:/media/frigate
    ports:
      - "5000:5000"
      - "1935:1935"
    environment:
      FRIGATE_RTSP_USER: "${RTSP_USER}"
      FRIGATE_RTSP_PASSWORD: "${RTSP_PASSWORD}"
      FRIGATE_MQTT_USER: "${MQTT_USER}"
      FRIGATE_MQTT_PASSWORD: "${MQTT_PASSWORD}"
    depends_on:
      - rtsp
```

```
docker-compose --env-file frigate.env up
```

```
frigate    | *************************************************************
frigate    | ***    Config Validation Errors                           ***
frigate    | *************************************************************
frigate    | 'FRIGATE_MQTT_PASSWORD'
frigate    | Traceback (most recent call last):
frigate    |   File "/opt/frigate/frigate/app.py", line 332, in start
frigate    |     self.init_config()
frigate    |   File "/opt/frigate/frigate/app.py", line 83, in init_config
frigate    |     self.config = user_config.runtime_config
frigate    |   File "/opt/frigate/frigate/config.py", line 800, in runtime_config
frigate    |     config.mqtt.password = config.mqtt.password.format(**FRIGATE_ENV_VARS)
frigate    | KeyError: 'FRIGATE_MQTT_PASSWORD'
frigate    | 
frigate    | *************************************************************
frigate    | ***    End Config Validation Errors                       ***
frigate    | *************************************************************
```

### Version

 blakeblackshear/frigate:0.11.1

### Frigate config file

```yaml
mqtt:
  host: server
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frontyard
  client_id: frontyard

cameras:
  basement:
    ffmpeg:
      input_args: -stimeout 10
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontyard:8554/unicast
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
```

### Relevant log output

```shell
frigate    | *************************************************************
frigate    | ***    Config Validation Errors                           ***
frigate    | *************************************************************
frigate    | 'FRIGATE_MQTT_PASSWORD'
frigate    | Traceback (most recent call last):
frigate    |   File "/opt/frigate/frigate/app.py", line 332, in start
frigate    |     self.init_config()
frigate    |   File "/opt/frigate/frigate/app.py", line 83, in init_config
frigate    |     self.config = user_config.runtime_config
frigate    |   File "/opt/frigate/frigate/config.py", line 800, in runtime_config
frigate    |     config.mqtt.password = config.mqtt.password.format(**FRIGATE_ENV_VARS)
frigate    | KeyError: 'FRIGATE_MQTT_PASSWORD'
frigate    | 
frigate    | *************************************************************
frigate    | ***    End Config Validation Errors                       ***
frigate    | *************************************************************
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Where are you providing the value to these? Are they in an env file somewhere? Can you start by trying to hardcode

```yaml
    environment:
      FRIGATE_MQTT_USER: "actual user"
      FRIGATE_MQTT_PASSWORD: "actual password"
``` 

and see if that works?

**Comment by jritsema** [comment]
The actual values are coming from an external env file
```sh
docker-compose --env-file frigate.env up
```

**Comment by NickM-27** [comment]
Okay, I'd start with hardcoding the env variable as I put above and see if that works (if not, get it to work), then work with the env file

**Comment by jritsema** [comment]
Ah, ok, I think I figured it out.  It looks like ONLY these two special values are supported.

```
FRIGATE_RTSP_PASSWORD
FRIGATE_MQTT_PASSWORD
```

I had assumed (I *think* I saw it someplace) that anything starting with `FRIGATE_` would be supported so I added the users as well so that I could manage credentials in a separate file.

```yaml
mqtt:
  host: server
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frontyard
  client_id: frontyard

cameras:
  basement:
    ffmpeg:
      input_args: -stimeout 10
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@frontyard:8554/unicast
          roles:
            - detect
            - rtmp
    detect:
      width: 640
      height: 480
```

It might be good to make this a bit more explicit in the docs so that others don't run into this.

Thanks for the support.  This is an excellent project!

**Comment by jritsema** [comment]
Hmm. Hard coding the user values is now working for me.  When I change it back to the config above I get this error.

```
frigate    | [2023-01-03 15:57:48] frigate.mqtt                   ERROR   : Unable to connect to MQTT server: MQTT Not authorized
```

I'm assuming that the user is not being evaluated.  Is there a way to confirm that frigate is getting the correct values?

**Comment by NickM-27** [comment]
Hardcode the values in the actual frigate config and then get a shell in the frigate container and print the env variables.

**Comment by jritsema** [comment]
I actually kept the config the same (values coming from docker-compose envvars) and exec'ed into the container and dumped the envvars.  I see them correctly set, however, frigate doesn't appear to be picking them up correctly.

```
env|grep FRIGATE_
FRIGATE_MQTT_USER=<redacted>
FRIGATE_RTSP_USER=<redacted>
FRIGATE_RTSP_PASSWORD=<redacted>
FRIGATE_MQTT_PASSWORD=<redacted>
```

```yaml
mqtt:
  host: server
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frontyard
  client_id: frontyard
```
```
DEBUG   : MQTT connected
ERROR   : Unable to connect to MQTT server: MQTT Not authorized
```

Again, when I set the user explicitly, it works.

```yaml
mqtt:
  host: server
  port: 1883
  user: my-user
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frontyard
  client_id: frontyard
```
```
DEBUG   : Received mqtt message
```
