### ISSUE TITLE
Support for dynamic MQTT user configuration

### ISSUE THREAD

**Issue by jritsema** [blakeblackshear/frigate#4883]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to manage MQTT credentials outside of Frigate configuration so that I can manage them in an external secrets store.  For example:

```yaml
mqtt:
  host: server
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
```

**Describe the solution you'd like**
Have Frigate evaluate ALL config values starting with `{FRIGATE_` sourcing them from envvars.
