### ISSUE TITLE
[Support]: go2rtc crashing with runtime error

### ISSUE THREAD

**Issue by Flamewires** [blakeblackshear/frigate#4891]
### Describe the problem you are having

Edit: Already tracked as part of https://github.com/AlexxIT/go2rtc/issues/111

Periodic crashes from gortc on docker.io/blakeblackshear/frigate:0.12.0-beta1

They seem to happen after a little while of watching the birdseye or any camers webrtc or mse stream. Frigate restarts but it is a bit annoying, since all the cams are down for that time. Any other debugging steps are welcome.

Version

Frigate stats

Operating system

Other Linux
Install method

Docker CLI
Coral version

CPU (no coral)
Network connection

Wired
Camera make and model

Gstreamer, sent via:
Any other information that may be helpful

No response

### Version

0.12.0-53d39a1

### Frigate config file

```yaml
mqtt:
  host: *XXX*
  user: *XXX*
  topic_prefix: frigate
  client_id: frigate
  password: *XXX*

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  #logs:
  #  frigate.event: debug
  #  frigate.record: debug

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  #max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    #threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    #max_frames:
    #  # Optional: Default for all object types (default: not set, track forever)
    #  default: 3000
    #  # Optional: Object specific values
    #  objects:
    #    person: 1000

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - vehicle
    - animal
    - backpack
    - umbrella
    - handbag 
    - sports ball
    - skateboard
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  #mask: 0,0,1000,0,1000,200,0,200
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 2000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  #mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: True

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 7
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    #max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    #pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    #post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    #objects:
    #  - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    #required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: all
      # Optional: Per object retention days
      #objects:
      #  person: 365

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 1280
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 7
    # Optional: Per object retention days
    objects:
      person: 30

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -probesize 64  -rtsp_transport tcp -allowed_media_types video+audio
  hwaccel_args: []
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
    rtmp: preset-rtmp-generic

# Optional: Restream configuration
# NOTE: Can be overridden at the camera level
restream:
  # Optional: Enable the restream (default: True)
  enabled: True
  # Optional: Force audio compatibility with browsers (default: shown below)
  force_audio: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  birdseye: True
  # Optional: jsmpeg stream configuration for WebUI
  jsmpeg:
    # Optional: Set the height of the jsmpeg stream. (default: 720)
    # This must be less than or equal to the height of the detect stream. Lower resolutions
    # reduce bandwidth required for viewing the jsmpeg stream. Width is computed to match known aspect ratio.
    height: 720
    # Optional: Set the encode quality of the jsmpeg stream (default: shown below)
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
    quality: 5

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "bl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
model:
  labelmap:
    1: vehicle
    2: vehicle
    3: vehicle
    4: vehicle
    5: vehicle
    6: vehicle
    7: vehicle
    8: vehicle
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal


cameras:
  *XXX*:
    motion:
      mask:
        - 0,0,1920,0,1920,880,1588,614,1285,704,1233,527,1229,462,670,507,692,727,709,929,853,882,1011,728,895,660,704,675,408,842,670,494,631,452,0,699
    ffmpeg:
      inputs:
        - path: rtsp://*XXX*:8555/video
          roles:
            - restream
        - path: rtsp://localhost:8554/*XXX*
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
  *XXX*:
    motion:
      mask:    
        - 0,593,2560,616,2560,0,0,0
    ffmpeg:
      inputs:
        - path: rtsp://*XXX*:8555/video
          roles:
            - restream
        - path: rtsp://localhost:8554/*XXX*
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1440
  *XXX*:
    ffmpeg:
      inputs:
        - path: rtsp://*XXX*:8555/video
          roles:
            - restream
        - path: rtsp://localhost:8554/*XXX*
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 768
      enabled: False
```

### Relevant log output

```shell
2023-01-04 00:56:27.239101864  05:56:27.238 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:105 > error=EOF
2023-01-04 00:57:18.292952182  panic: runtime error: invalid memory address or nil pointer dereference
2023-01-04 00:57:18.292965366  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f4fb4]
2023-01-04 00:57:18.292977623  
2023-01-04 00:57:18.294218883  goroutine 45 [running]:
2023-01-04 00:57:18.294229827  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0x4000318100)
2023-01-04 00:57:18.294235459  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x1a4
2023-01-04 00:57:18.294243268  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0x40003262c0, {0x801ab0?, 0x4000200270})
2023-01-04 00:57:18.294289828  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:70 +0x454
2023-01-04 00:57:18.294390213  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0x604de0?, 0x7fc108?})
2023-01-04 00:57:18.294425157  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:166 +0x270
2023-01-04 00:57:18.294432325  github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
2023-01-04 00:57:18.294436614  	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
2023-01-04 00:57:18.294441382  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x4000200270)
2023-01-04 00:57:18.294447014  	github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:558 +0xac0
2023-01-04 00:57:18.294555719  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0x4000200270)
2023-01-04 00:57:18.294560999  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:201 +0x1a4
2023-01-04 00:57:18.294635912  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-01-04 00:57:18.294641288  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:63 +0x3c



2023-01-04 00:45:09.859546489  05:45:09.858 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:105 > error="read tcp 127.0.0.1:8554->127.0.0.1:57278: i/o timeout"
2023-01-04 00:45:19.224514672  panic: runtime error: invalid memory address or nil pointer dereference
2023-01-04 00:45:19.224526928  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f4fb4]
2023-01-04 00:45:19.224530512  
2023-01-04 00:45:19.225145911  goroutine 55 [running]:
2023-01-04 00:45:19.225199032  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0x4000141a00)
2023-01-04 00:45:19.225204504  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x1a4
2023-01-04 00:45:19.225784735  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0x40001e0ac0, {0x801ab0?, 0x4000212680})
2023-01-04 00:45:19.225801151  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:70 +0x454
2023-01-04 00:45:19.225877088  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0x604de0?, 0x7fc108?})
2023-01-04 00:45:19.225883520  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:166 +0x270
2023-01-04 00:45:19.225916544  github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
2023-01-04 00:45:19.225920544  	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
2023-01-04 00:45:19.225924640  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x4000212680)
2023-01-04 00:45:19.225927904  	github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:558 +0xac0
2023-01-04 00:45:19.226032066  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0x4000212680)
2023-01-04 00:45:19.226036514  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:201 +0x1a4
2023-01-04 00:45:19.226109186  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-01-04 00:45:19.226113730  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:63 +0x3c



2023-01-04 00:32:11.378829755  panic: runtime error: invalid memory address or nil pointer dereference
2023-01-04 00:32:11.380211443  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f4fb4]
2023-01-04 00:32:11.380220211  
2023-01-04 00:32:11.380224691  goroutine 67 [running]:
2023-01-04 00:32:11.380268500  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0x4000212080)
2023-01-04 00:32:11.380274900  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x1a4
2023-01-04 00:32:11.380279796  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0x4000204140, {0x801ab0?, 0x400017cb60})
2023-01-04 00:32:11.380285845  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:70 +0x454
2023-01-04 00:32:11.380384502  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0x604de0?, 0x7fc108?})
2023-01-04 00:32:11.380417975  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:166 +0x270
2023-01-04 00:32:11.380421943  github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
2023-01-04 00:32:11.380534233  	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
2023-01-04 00:32:11.380538937  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x400017cb60)
2023-01-04 00:32:11.380543001  	github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:558 +0xac0
2023-01-04 00:32:11.380546521  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0x400017cb60)
2023-01-04 00:32:11.380626939  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:201 +0x1a4
2023-01-04 00:32:11.380631675  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
s6-rc: info: service legacy-services: stopping
2023-01-04 00:32:11.380635771  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:63 +0x3c
```

### FFprobe output from your camera

```shell
*XXX*@*XXX*:/ssd/frigate$ docker exec -it frigate ffprobe rtsp://*XXX*:8555/video
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://*XXX*:8555/video':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.215833, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, smpte170m/unknown/unknown, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 5 fps, 4.58 tbr, 90k tbn
```

### Frigate stats

```json
{"*XXX*":{"camera_fps":5.0,"capture_pid":371,"detection_fps":2.0,"ffmpeg_pid":383,"pid":365,"process_fps":1.4,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.1"},"130":{"cpu":"0.0","mem":"0.1"},"131":{"cpu":"0.0","mem":"0.1"},"132":{"cpu":"0.0","mem":"0.1"},"133":{"cpu":"0.0","mem":"0.1"},"134":{"cpu":"0.0","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"352":{"cpu":"0.0","mem":"1.2"},"358":{"cpu":"0.7","mem":"0.1"},"359":{"cpu":"115.2","mem":"1.5"},"360":{"cpu":"113.9","mem":"1.5"},"362":{"cpu":"4.0","mem":"1.8"},"365":{"cpu":"11.6","mem":"1.5"},"368":{"cpu":"12.6","mem":"1.8"},"369":{"cpu":"0.0","mem":"0.2"},"370":{"cpu":"0.0","mem":"1.4"},"371":{"cpu":"12.3","mem":"1.4"},"372":{"cpu":"20.9","mem":"1.5"},"373":{"cpu":"0.0","mem":"0.2"},"376":{"cpu":"0.0","mem":"1.4"},"38":{"cpu":"0.0","mem":"0.0"},"380":{"cpu":"0.0","mem":"0.2"},"381":{"cpu":"36.1","mem":"1.3"},"383":{"cpu":"75.2","mem":"0.9"},"385":{"cpu":"7.0","mem":"1.1"},"387":{"cpu":"0.0","mem":"0.7"},"39":{"cpu":"0.0","mem":"0.0"},"393":{"cpu":"3.6","mem":"0.3"},"395":{"cpu":"2.0","mem":"0.3"},"47":{"cpu":"0.0","mem":"0.0"},"753":{"cpu":"0.0","mem":"0.3"},"86":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.0"},"90":{"cpu":"0.0","mem":"0.0"},"91":{"cpu":"0.0","mem":"0.0"},"92":{"cpu":"0.0","mem":"0.0"},"93":{"cpu":"0.0","mem":"0.0"},"940":{"cpu":"0.3","mem":"0.0"},"943":{"cpu":"1.3","mem":"0.0"},"946":{"cpu":"1.3","mem":"0.0"},"95":{"cpu":"0.0","mem":"0.0"},"954":{"cpu":"0.3","mem":"0.1"},"96":{"cpu":"69.2","mem":"3.3"},"97":{"cpu":"0.0","mem":"0.2"},"99":{"cpu":"9.3","mem":"0.3"},"MiB":{"cpu":"4222.7","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":4.1,"detectors":{"cpu1":{"detection_start":1672813444.979561,"inference_speed":479.45,"pid":359},"cpu2":{"detection_start":1672813445.187559,"inference_speed":450.56,"pid":360}},"*XXX*":{"camera_fps":0.0,"capture_pid":376,"detection_fps":0.0,"ffmpeg_pid":387,"pid":370,"process_fps":0.1,"skipped_fps":0.0},"*XXX*":{"camera_fps":5.0,"capture_pid":372,"detection_fps":2.1,"ffmpeg_pid":381,"pid":368,"process_fps":1.1,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":1033.2,"mount_type":"tmpfs","total":1073.7,"used":40.5},"/media/frigate/clips":{"free":396057.9,"mount_type":"ext4","total":983430.8,"used":537345.9},"/media/frigate/recordings":{"free":396057.9,"mount_type":"ext4","total":983430.8,"used":537345.9},"/tmp/cache":{"free":3586.8,"mount_type":"tmpfs","total":3589.5,"used":2.7}},"temperatures":{},"uptime":88,"version":"0.12.0-53d39a1"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Gstreamer from USB webcams, various boards, khadas VIM and PI4s, sent with: 

```
gst-rtsp-launch -p 8555 '( souphttpsrc location=http://127.0.0.1:8080?action=stream ! image/jpeg, width=1920, height=1080, framerate=25/1 ! queue max-size-bytes=1000000000 ! jpegdec !  clockoverlay halignment=left time-format="%Y-%m-%dT%H:%M:%S%z" font-desc="Sans, 8" ! queue max-size-bytes=1000000000 ! x264enc pass=cbr speed-preset=3 byte-stream=true bitrate=2048 tune=zerolatency key-int-max=15 ! video/x-h264,profile=high ! queue max-size-bytes=1000000000 ! rtph264pay name=pay0 pt=96 )'
```

or direct from v4l
```
gst-rtsp-launch -p 8555 '( v4l2src device=/dev/video0 do-timestamp=true io-mode=auto ! image/jpeg, width=2560, height=1440, framerate=5/1 ! queue max-size-bytes=1000000000 ! jpegdec ! clockoverlay halignment=left time-format="%Y-%m-%dT%H:%M:%S%z" 
font-desc="Sans, 8" ! queue max-size-bytes=1000000000 ! x264enc pass=cbr speed-preset=3 byte-stream=true bitrate=2048 tune=zerolatency key-int-max=15 ! video/x-h264,profile="high" ! queue max-size-bytes=1000000000 ! rtph264pay name=pay0 pt=96 )'
```
depending on if mjpeg streamer is sitting in front on that device. (It is for octoprint)

### Any other information that may be helpful

Running on a jetson Xavier NX.
