### ISSUE TITLE
[Support]: Not able to watch webrtc stream exteranlly

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#4916]
### Describe the problem you are having

Frigate 12.0 Beta1  run docker in  network_mode: host      
Router open port 8555:8555 to frigate docker
not behind NAT 

Problem:
webrtc is working when connect on same network 
from outside - it doesnt work 

I tried with/without below with no success:
````
webrtc:
  listen: ":8555"  # address of your local server (TCP)
  candidates:
    - stun:8555  # if you have dynamic public IP-address
```


### Version

frigate:0.12.0-beta1

### Frigate config file

```yaml
webrtc:
  listen: ":8555"  # address of your local server (TCP)
  candidates:
    - stun:8555  # if you have dynamic public IP-address

```


### Relevant log output

```
[1mgithub.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:25[0m[36m >[0m [36merror=[0m[31m"address 2a00:a040:191:c096:3438:9fc3:f7ed:949c:8555: too many colons in address"[0m
2023-01-05 15:04:44.635705013  [90m13:04:44.634[0m [31mWRN[0m [1mgithub.com/AlexxIT/go2rtc/cmd/webrtc/candidates.go:25[0m[36m >[0m [36merror=[0m[31m"address 2a00:a040:191:c096:3438:9fc3:f7ed:949c:8555: too many colons in address"[0m
```



### FFprobe output from your camera

```shell
NA
```


### Frigate stats

```json
NA
```


### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Running Traefik as RP - I don't see issue as frigate is accessible ,
but case it may might be relevant -  adding Traefik dynamic file
```
http:
  routers:
    service-router-frigate:
      entryPoints:
        - websecure
      middlewares:
        - frigate-auth
      service: service-frigate
      rule: Host(`frigate.mydomian.com`)
      tls:
        certResolver: myresolver

  services:

    service-frigate:
      loadBalancer:
        servers:
          - url: "http://192.168.1.3:5000"



```

**Comment by NickM-27** [comment]
Can you provide your docker compose file? Need to make sure that the file is being mapped correctly. Not sure about that too many colons error but that is also probably releated.

**Comment by avico78** [comment]
compose
```
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.12.0-beta1
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/frigate.yml:/config/config.yml:ro
      - ./frigate/NAS:/media/frigate
      - ./frigate/database:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host          
    environment:
      - FRIGATE_RTSP_PASSWORD="xxxx"
      - TZ=Asia/Jerusalem
      # - LIBVA_DRIVER_NAME=i965 
      - database=frigate.db     
      - PLUS_API_KEY=6xxxx32c-xb-xxxa-93a3-0exb71:0c8c265xxxxxxxxxxxxxd40f01460b
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
            max-file: "3"
```
go2rtc log

<img width="703" alt="image" src="https://user-images.githubusercontent.com/9049952/210799291-b3ed5486-4848-4548-8240-861ace355d0b.png">

**Comment by NickM-27** [comment]
I don't see the frigate-go2rtc file being overwritten at all, you need to follow the docs which show how to set your manual go2rtc config https://deploy-preview-4055--frigate-docs.netlify.app/configuration/live#webrtc-extra-configuration

**Comment by AlexxIT** [comment]
This is known issue https://github.com/AlexxIT/go2rtc/issues/148

**Comment by avico78** [comment]
> I don't see the frigate-go2rtc file being overwritten at all, you need to follow the docs which show how to set your manual go2rtc config https://deploy-preview-4055--frigate-docs.netlify.app/configuration/live#webrtc-extra-configuration

Thanks @NickM-27 - actually i did that (from some reason paste it without it),
still webrtc - doesn't work outside .

compose volume:
```

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/frigate.yml:/config/config.yml:ro
      - ./frigate/NAS:/media/frigate
      - ./frigate/database:/db
      - ./frigate/go2rtc.yaml:/config/frigate-go2rtc.yaml:ro


```
see:
```
root@aviot:/opt/frigate# cat /config/frigate-go2rtc.yaml
webrtc:
  listen: ":8555"  # address of your local server (TCP)
  candidates:
    - stun:8555  # if you have dynamic public IP-address
````
anything else i can do?
if there's a need to debug webrtc kindly share how
thanks!
