### ISSUE TITLE
[Support]: "In Progress" events go on forever because phantom objects detected after real objects have left

### ISSUE THREAD

**Issue by SpartacusIam** [blakeblackshear/frigate#4918]
### Describe the problem you are having

I've been having an issue for quite some time where I have "in progress" events go on for hours upon hours after a real object detection takes place.  For example a car pulls in my driveway, then leaves, but Frigate is still detecting the object is there even when it's gone.  Please see the attached
![1](https://user-images.githubusercontent.com/16405200/210795547-17acddb2-c07e-4feb-853e-68ac3e8ffd34.png)
![4](https://user-images.githubusercontent.com/16405200/210795852-6d07fa01-d0fe-4a25-b1ae-9a98f6190e60.png)
![5](https://user-images.githubusercontent.com/16405200/210795872-fddc15e8-8b5d-44fc-85b4-5af4fac6dfa4.png)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 10.4.110.70
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USERNAME}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

detectors:
  coral_pci:
    type: edgetpu
    device: pci

birdseye:

  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

cameras:
  
  01-garage-driveway:
    ffmpeg:
      inputs:
        - path: rtsp://10.4.130.72:554/ch01/1
          roles:
            - detect
            - rtmp
        - path: rtsp://10.4.130.72:554/ch01/0
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

    zones:
      driveway_entry:
        coordinates: 1118,46,1239,58,1228,158,959,120,999,36
      driverway_main:
        coordinates: 1133,720,1280,331,1280,149,945,128,433,417,701,720
    
    motion:
      mask:
        - 0,0,1280,0,1280,64,1004,47,633,79,0,462

    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        - car
      filters:
        person:
          min_score: 0.55
          threshold: 0.65

    record:
      enabled: True
      retain:
        days: 28
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects
  
  02-front-doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.4.130.79:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.4.130.79:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
            - rtmp
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

    motion:
      mask:
        - 0,0,640,0,640,0,640,238,0,337

    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        #- car

    record:
      enabled: True
      retain:
        days: 28
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects

  03-front-yard:
    ffmpeg:
      inputs:
        - path: rtsp://10.4.130.71:554/ch01/1
          roles:
            - detect
            - rtmp
        - path: rtsp://10.4.130.71:554/ch01/0
          roles:
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

    motion:
      mask:
        - 338,68,571,57,869,69,1280,150,1280,0,0,0,0,142

    rtmp:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        - car
      filters:
        car:
          mask:
            - 0,720,1280,720,1280,142,1054,246,796,194,854,68,1280,148,1280,0,0,0
        person:
          mask:
            - 0,720,1280,720,1280,142,1054,246,796,194,854,68,1280,148,1280,0,0,0
            
    record:
      enabled: True
      retain:
        days: 28
        mode: all
      events:
        retain:
          default: 28
          mode: active_objects
    
ffmpeg:

  global_args: -hide_banner -loglevel error

  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - "1"
  
  output_args: 

    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

logger:
  default: info
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

GoSwift 4K

**Comment by NickM-27** [comment]
What do your motion masks look like? Based on the config it seems like they may be too big which is causing objects to get stuck

**Comment by SpartacusIam** [comment]
> What do your motion masks look like? Based on the config it seems like they may be too big which is causing objects to get stuck

This is what they look like.  I created these to not catch motion of cars driving by.
![6](https://user-images.githubusercontent.com/16405200/210797485-7a45157a-e778-432f-a3c3-bc0f77fb1196.png)
![7](https://user-images.githubusercontent.com/16405200/210797505-4b540edd-dd5c-49af-aa2f-ae32ba992f19.png)

**Comment by NickM-27** [comment]
> I created these to not catch motion of cars driving by.

Please read the docs: https://docs.frigate.video/configuration/masks Motion masks are not meant to be used to block real objects from being detected in unwanted areas, that is what zones are for. Frigate is designed to track all objects but only alert you when it enters an area of interest. 

Motion masks are designed to block specific areas like timestamps, trees, bushes, etc. These motion masks are most likely the reason that this is happening.

**Comment by SpartacusIam** [comment]
> > I created these to not catch motion of cars driving by.
> 
> Please read the docs: https://docs.frigate.video/configuration/masks Motion masks are not meant to be used to block real objects from being detected in unwanted areas, that is what zones are for. Frigate is designed to track all objects but only alert you when it enters an area of interest.
> 
> Motion masks are designed to block specific areas like timestamps, trees, bushes, etc. These motion masks are most likely the reason that this is happening.

Ok i removed all masks except over the timestamp and created zones.  However I'm still having the same problem.  This detected "person" has been here non stop for about 6 hours and because of that I'm receiving notifications non stop.  How should I handle this?  I have the following set.  Do I need to up the minimum score?

```
      filters:
        person:
          min_score: 0.55
          threshold: 0.65
```
