### ISSUE TITLE
[Camera Support]: Reolink 510A

### ISSUE THREAD

**Issue by BLKKKBVSIK** [blakeblackshear/frigate#4930]
### Describe the problem you are having

Hi.

I'm using the Reolink 510A, and I currently receive no frame from FFmpeg, so it's displayed as a green camera right now.
My configuration seems correct when I compare it to the documentation.

I verified that my RTMP link is functional on VLC and others apps.
I verified that my RTMP is enabled in the config.
I tried with and without input_args.
I also try to use the[-stimeout trick described in this issue](https://github.com/blakeblackshear/frigate/issues/4008), but it seems that -stimeout is not not recognized (ffmpeg.camera_un.detect        ERROR   : Unrecognized option 'stimeout'.)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.37
  user: HA
  password: HA

cameras:
  camera_un: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: <my valid RTMP link here>
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    record:
      enabled: True
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.25
        cat:
          min_score: 0.25
        dog:
          min_score: 0.25
```

### Relevant log output

```shell
[2023-01-06 08:41:40] ffmpeg.camera_un.detect        ERROR   : Error splitting the argument list: Option not found
[2023-01-06 08:41:40] frigate.video                  ERROR   : camera_un: Unable to read frames from ffmpeg process.
[2023-01-06 08:41:40] frigate.video                  ERROR   : camera_un: ffmpeg process is not running. exiting capture thread...
[2023-01-06 08:41:50] watchdog.camera_un             ERROR   : Ffmpeg process crashed unexpectedly for camera_un.
[2023-01-06 08:41:50] watchdog.camera_un             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2023-01-06 08:41:50] ffmpeg.camera_un.detect        ERROR   : Unrecognized option 'stimeout'.
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
rtmp://XXXXX:XXXX@XX.XX.XX.XX/bcs/channel0_main.bcs?token=sdasdasd: Input/output error
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink 510A

### Any other information that may be helpful

Unraid version: 6.11.1
