### ISSUE TITLE
Docs incorrectly define `clips` instead of `save_clips`

### ISSUE THREAD

**Issue by DeadEnded** [blakeblackshear/frigate#494]
**Describe the bug**
Clips key in YAML not correct

**Version of frigate**
beta 4

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
#    objects:
#      person: 15
```

**Logs**
```
ERROR   : Error parsing config: extra keys not allowed @ data['clips']
```

**Additional context**
Changing `clips` to `save_clips` fixes the issue.
I expect this is just an update that hasn't made it to the docs... but being a novice I can't find in the python files anywhere that defines `save_clips`.  I am also getting errors for camera `snapshots` and `mqtt`... the only reason I figure out the clips is because I also had this warning:
```
WARNING : Camera front has clips assigned to an input, but save_clips is not enabled.
```
That is when I realized that it was `save_clips` and not just `clips`.
So, this is probably just a docs update... but again I am trying to find the correct mqtt and snapshot keys because I have those erroring as well.
```
ERROR   : Error parsing config: extra keys not allowed @ data['cameras']['front']['snapshots']['enabled']
ERROR   : Error parsing config: extra keys not allowed @ data['cameras']['front']['mqtt']
```

Can someone show me where these are defined so I can figure this out?
First time setting up Frigate - trying to work through the config file :-)

Thanks - Cheers!
DeadEnd
