### ISSUE TITLE
Frigate will not start

### ISSUE THREAD

**Issue by leeandy1** [blakeblackshear/frigate#4950]
### Describe the problem you are having

After updating to Frigate (Full Access) Beta (0.12.0) the addon will not start in home assistant. the error in the log states:

s6-overlay-suexec: fatal: can only run as pid 1

the Beta 0.11 worked fine.

### Version

0.12.0-beta2 

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.05
  user: mqtt
  password: ****

detectors:
  coral:
    type: edgetpu
    device: usb


cameras:
  patio: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@192.168.1.11:554/streaming/channels/202 # <----- Update for your camera
          roles:
            - detect
            - rtmp
#      hwaccel_args: -c:v h264_v4l2m2m

    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,0,0,189,24,184,101,147,222,96,345,85,476,61,550,109,697,108,828,108,994,119,1140,138,1300,193,1485,250,1673,316,1920,392,1920,0
    objects:
      track:
        - person
        - cat
      filters:
        person: 
          mask:
            - 0,0,0,189,24,184,101,147,222,96,345,85,476,61,550,109,697,108,828,108,994,119,1140,138,1300,193,1485,250,1673,316,1920,392,1920,0
        cat:
          mask:
            - 0,0,0,189,24,184,101,147,222,96,345,85,476,61,550,109,697,108,828,108,994,119,1140,138,1300,193,1485,250,1673,316,1920,392,1920,0    
#
#
#
  front: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@192.168.1.69:554/Streaming/channels/2# <----- Update for your camera
          roles:
            - detect
            - rtmp
#      hwaccel_args: -c:v h264_v4l2m2m

    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
      mask:
        - 0,352,112,342,230,341,351,356,546,384,789,510,1236,792,1374,927,1531,1080,1920,1080,1920,0,0,0
    objects:
      track:
        - person
        - cat
      filters:
        person: 
          mask:
            - 0,352,112,342,230,341,351,356,546,384,789,510,1236,792,1374,927,1531,1080,1920,1080,1920,0,0,0
        cat:
          mask:
            - 0,352,112,342,230,341,351,356,546,384,789,510,1236,792,1374,927,1531,1080,1920,1080,1920,0,0,0
#
#
#

      
  drive: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:****@192.168.1.11:554/streaming/channels/102 # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution  
    motion:
      mask:
        - 0,1080,165,1080,320,950,408,823,494,666,584,480,655,314,782,115,839,80,1080,68,1159,45,1471,165,1733,170,1855,208,1920,232,1920,0,0,0
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person: 
          mask:
            - 0,1080,165,1080,320,950,408,823,494,666,584,480,655,314,782,115,839,80,1080,68,1159,45,1471,165,1733,170,1855,208,1920,232,1920,0,0,0
        car:
          mask:
            - 0,1080,165,1080,320,950,408,823,494,666,584,480,655,314,782,115,839,80,1080,68,1159,45,1471,165,1733,170,1855,208,1920,232,1920,0,0,0     
        cat:
          mask:
            - 0,1080,165,1080,320,950,408,823,494,666,584,480,655,314,782,115,839,80,1080,68,1159,45,1471,165,1733,170,1855,208,1920,232,1920,0,0,0  

snapshots:
  enabled: True
  retain:
     default: 7
```

### Relevant log output

```shell
s6-overlay-suexec: fatal: can only run as pid 1
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision
