### ISSUE TITLE
Restream record time out error

### ISSUE THREAD

**Issue by bm55** [blakeblackshear/frigate#4969]
I still get  following error using below camera config:

```
2023-01-08 19:11:12.574104316  [2023-01-08 19:11:12] ffmpeg.garage.record             ERROR   : rtsp://192.168.0.10:8554/garage: Connection timed out
2023-01-08 19:11:12.574105789  [2023-01-08 19:11:12] watchdog.garage                  INFO    : Terminating the existing ffmpeg process...
2023-01-08 19:11:12.574107151  [2023-01-08 19:11:12] watchdog.garage                  INFO    : Waiting for ffmpeg to exit gracefully...
```

  rw_timeout is for http streams only, if you try to use it with an rtsp stream then it will have problems. You need to set the input_args at the camera level

```yaml
cameras:
  garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio
      inputs:
        - path: http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
        - path: http://192.168.0.139/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          roles:
            - restream
            #- record
        - path: rtsp://192.168.0.10:8554/garage
          input_args: preset-rtsp-generic
          roles:
            - record
```

_Originally posted by @NickM-27 in https://github.com/blakeblackshear/frigate/discussions/4859#discussioncomment-4606383_

**Comment by NickM-27** [comment]
No need to create duplicate issues for the same problem

**Comment by NickM-27** [comment]
Nevermind looks like it's different.

The log is complaining about the camera back so seeing the config for that would be necessary

**Comment by bm55** [comment]
> Nevermind looks like it's different.
> 
> The log is complaining about the camera back so seeing the config for that would be necessary

```
  back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio
      inputs:
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          roles:
            - restream
            #- record
        - path: rtsp://192.168.0.10:8554/back
          input_args: preset-rtsp-generic
          roles:
            - record       
    detect:
      width: 896
      height: 672
```

**Comment by bm55** [comment]
It looks like the "preset-rtsp-reolink" instead of "preset-rtsp-generic" solves the issue

```
  back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio
      inputs:
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          roles:
            - restream
            #- record
        - path: rtsp://192.168.0.10:8554/back
          input_args: preset-rtsp-reolink
          roles:
            - record       
    detect:
      width: 896
      height: 672
```

**Comment by NickM-27** [comment]
There's no such thing as preset-rtsp-reolink so it's just defaulting to global input args. In that case leaving it blank (not having the input_args for the record oath) would have the same event.

**Comment by bm55** [comment]
Yep spoke too soon, see the error now and recording is not working.

**Comment by NickM-27** [comment]
Yes, seems like it's not able to connect for some reason and times out. Does it work if you access the record stream directly with http preset?

**Comment by bm55** [comment]
> back:
>     ffmpeg:
>       output_args:
>         record: preset-record-generic-audio
>       inputs:
>         - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
>           input_args: preset-http-reolink
>           roles:
>             - detect
>         - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
>           roles:
>             - restream
>             #- record
>         - path: rtsp://192.168.0.10:8554/back
>           input_args: preset-rtsp-reolink
>           roles:
>             - record       
>     detect:
>       width: 896
>       height: 672

Yes, that does work.

**Comment by bm55** [comment]
This works without error
```

  back:
    ffmpeg:
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic-audio
      inputs:
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          roles:
            - restream
            - record
    detect:
      width: 896
      height: 672
```

**Comment by NickM-27** [comment]
Try this

```yaml
back:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio
      inputs:
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          input_args: preset-http-reolink
          roles:
            - detect
        - path: http://192.168.0.138/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_CAM_PASSWORD}
          roles:
            - restream
            #- record
        - path: rtsp://192.168.0.10:8554/back?video=copy&audio=aac
          input_args: preset-rtsp-reolink
          roles:
            - record       
    detect:
      width: 896
      height: 672
```
