### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by MrPlatnum** [blakeblackshear/frigate#4975]
### Describe the problem you are having

What is the minimum resolution for a stream with the "detect" role.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.114
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: eF4uaNKuw4
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  balkon:
    ffmpeg:
      input_args:
        - -fflags
        - +genpts+discardcorrupt
        - -rtsp_transport 
        - udp
        - -loglevel
        - info
      #output_args: -s 896x512
      inputs:
      - path: rtsp://admin:password@192.11.11.1:554/h265Preview_01_main
        hwaccel_args: -hwaccel drm -hwaccel_device /dev/dri/card0 -c:v hevc_rkmpp
        roles:
        - record
      - path: rtsp://admin:password@192.11.11.1:554/h264Preview_01_sub
        hwaccel_args: -hwaccel drm -hwaccel_device /dev/dri/card0 -c:v h264_rkmpp
        roles:
        - rtmp
        - detect
    rtmp:
      enabled: True
    detect:
      width: 896
      height: 512
      fps: 30
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
         default: 3
    snapshots:
      enabled: True
    motion:
      mask:
      - 407,72,727,101,896,162,896,0,559,0,0,0,0,144
```

### Relevant log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

![image](https://user-images.githubusercontent.com/27893271/211338259-0a4b2c5b-54b6-4355-91d5-db3ed45ad773.png)
I get very high CPU usage in my frigate container. Not from stream decoding but from upscaling for the detector as it seems.
I dont quite understand why my input stream gets upscaled like that. Is there an option or input/output arg to omit this?

**Comment by NickM-27** [comment]
The stream is always resizes to whatever is in

```yaml
    detect:
      width: 896
      height: 512
```

also you have your fps at 30 which is not recommended as there is no need. 5 is the default and usually enough for most people. The fps set in frigate config does not need to match the fps of the camera stream.
