### ISSUE TITLE
[Support]: Two events shown as one recording

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#4977]
### Describe the problem you are having

Scenario:
1- My car drove into my driveway zone and was detected (car) and was stopped there for about 30 minutes.
2- Later I walked out on foot passed by the car

Outcome:
One video recording showing the car driving in  and myself leaving on foot (1) then a couple of seconds later showing myself walking by the car (2)  (4 hours later and it still shows as in progress)
There is also another clip for me detected as person

Expected:
Two different clips:
 Car driving in (car detected)
 Myself walking on foot ( person detected)

### Version

0.11.1-2eada21

### Frigate config file

```yaml
# frigate.yml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: xyz.duckdns.org
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: fdsfdsfds
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
rtmp:
  enabled: false

#motion:
#  contour_area: 100
#  delta_alpha: 0.2
#  frame_alpha: 0.2
#  frame_height: 80
#  threshold: 25
  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
  
cameras:
  driveway:
    zones:
      sidewalk:
        coordinates: 70,49,225,34,315,28,499,30,640,46,640,0,0,0,0,63
        objects:
          - car
      drive_way:
        coordinates: 296,32,488,33,640,57,640,352,0,352,0,65,130,44
        objects:
          - person
          - car
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 70,49,225,34,315,28,499,30,640,46,640,0,0,0,0,63
#            - 95,38,317,64,640,130,640,0,0,0,0,42
#          min_score: 0.49
          threshold: 0.58
          min_area: 3200
          max_area: 30320
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.6.140/2
          roles:
            - detect
        - path: rtsp://admin:xxxx@192.168.6.140/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 7  
#      stationary:
#        interval: 14
#    motion:
#      mask:
#        - 70,49,225,34,315,28,499,30,640,46,640,0,0,0,0,63
#        - 95,38,317,64,640,130,640,0,0,0,0,42         
    record:
      enabled: true
      retain:
        days: 0
      events:
        required_zones:
          - drive_way
          - sidewalk
        retain:
          default: 5
          mode: active_objects
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - drive_way
        - sidewalk
      timestamp: True      
      retain:
        default: 7


################################################ 
  front_porch_camera:
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.6.141/2
          roles:
            - detect
        - path: rtsp://admin:xxxx@192.168.6.141/1
          roles:
            - record
    detect:    
      width: 640
      height: 352
      fps: 5  
    motion:
      mask:
        - 148,348,171,122,173,12,377,8,518,57,640,80,640,0,0,0,0,352         
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True      
      retain:
        default: 7
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Chortau

**Comment by B0ndo2** [comment]
Ok but then the problem is that it becomes not so useful as it is a time compressed clip. Anyone who walks by the car will be added to the clip and there is no way for me to tell when that person was present by looking at the clip.
To make it clear. The event started at 8:02 and I walked by again at 8:35 and if someone else walks by at 12p, s/he will be added to the same clip and playing it back will make it look like it was once continuous stream of events.
Why would a person be added to the clip for a car detection ?

**Comment by NickM-27** [comment]
> Why would a person be added to the clip for a car detection ?

Because the event is for the car and the car is still there and your recording retention policy is 

```yaml
record:
      events:
        retain:
          default: 5
          mode: active_objects
```

which means it only keeps recording segments where an object is active (in this case you)
