### ISSUE TITLE
[Support]: birdseye quality seems very low

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#4983]
### Describe the problem you are having

For some reason, birdseye quality, even though set at 1 (continuous) seems very low. I don't know if that's just in frigate, but i assume it will stay that way if i cast it or use it in a card.

I don't care about the 5fps, that's fine, but the quality feels like i'm looking at less then 320x or so.

### Version

frigate-12-beta

### Frigate config file

```yaml
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

dahua

### Any other information that may be helpful

about 8 cameras in total.

**Comment by NickM-27** [comment]
birdseye is stitched together and made up of the frames from the detect feeds, so if your camera detect feeds are lower resolution than the cameras showing in birdseye are going to be lower resolution too.

**Comment by atv2016** [comment]
Hmm
Most of my camera setups are using:
```
 detect:
      width: 1920
      height: 1080
      fps: 6
```

Should be ample resolution?
