### ISSUE TITLE
[Config Support]:  Per camera object masks in 0.12 beta 2

### ISSUE THREAD

**Issue by jmtatsch** [blakeblackshear/frigate#5005]
### Describe the problem you are having

Hi,

I have some bird stickers on my windows which cause frequent false positives and which I would like to mask out per camera. My configuration for that camera is added below.

After saving and restarting, when I Iook at the debug view for that camera the defined mask is not shown.

Is my config wrong or my expectation to see the mask in the debug view of the camera?

### Version

0.12.0-0DBF909

### Frigate config file

```yaml
cameras:
  vorne_1: 
    ffmpeg:
      inputs:
        - path: rtsp://192.168.179.59:8554/unicast
          roles:
            - detect
            - record
            - restream
    detect:
      width: 1920 
      height: 1080 
      enabled: True
    objects:
      filters:
        bird:
          mask:
            - 1156,408,1214,423,1177,341,1138,354
```

### Relevant log output

```shell
nothing regarding masks
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
