### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by tmjpugh** [blakeblackshear/frigate#5025]
### Describe the problem you are having

Some of my cameras are showing "no frames have been received, check error logs" and Jsmpeg stream stop functioning for the camera that is showing the error.

my South01 and South02 camera are same make/model/firmware. only 1 of the 2 camera are affected. After reboot the error may switch between the 2 camera.  Problem exits in both beta 1 and beta 2 version.  No error showing in go2rtc log

### Version

0.12.0-53d39a1 and  0.12.0-0dbf909

### Frigate config file

```yaml
###############################
#           MQTT               #
################################
mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60


################################
#         DETECTORS:      #
################################
detectors:
  coral_pci:
    type: edgetpu
    device: pci


################################
#           GLOBAL             #
################################
birdseye:
  enabled: True
  width: 2592
  height: 1944
  # Optional: Encoding quality of the mpeg1 feed  1-31. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  mode: continuous

restream: 
  birdseye: true
#live:
#  #height: 500
#  quality: 1

################################
#          CAMERAS             #
################################
cameras:
#Each role can only be assigned to one input per camera. The options for roles are as follows:
###detect	Main feed for object detection
###clips	Clips of events from objects detected in the detect feed. docs
###record	Saves 60 second segments of the video feed. docs
###restream	Broadcast as an restream feed for other services to consume. doc


  #######################################
  #             SOUTH-01                #
  #######################################
  Frigate_South01:
    ffmpeg:
      inputs:
       # SD Stream
       - path: rtsp://admin:admin@192.168.20.111:554/cam/realmonitor?channel=1&subtype=1
         roles:
           - detect
       # HD STREAM
       - path: rtsp://admin:admin@192.168.20.111:554/cam/realmonitor?channel=1&subtype=0
         roles:
           - restream
       # RE Stream  
       - path: rtsp://localhost:8554/Frigate_South01
         roles:
           - record

    detect:
       width: 704
       height: 480
       fps: 20
       enabled: True
       # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
       #max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: True
      retain_days: 10
      events:
        retain:
          default: 30

    objects:
      track:
        - animal
        - car
        - motorcycle
        - person
    #  filters:
    #    car:
    #      min_score: 0.8
    #      threshold: 0.9

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      #height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        #objects:
          #person: 15

    motion:
      # Optional: (default: 100) Minimum size in pixels of resized motion image that counts as motion
      # Increasing prevent small area motion being detected. Decreasing make detection sensitive to smaller moving o>
      contour_area: 50

  
  #######################################
  #             SOUTH-02                #
  #######################################
  Frigate_South02:
    ffmpeg:
      inputs:
       # SD Stream
       - path: rtsp://admin:admin@192.168.20.149:554/cam/realmonitor?channel=1&subtype=1
         roles:
           - detect
       # HD STREAM
       - path: rtsp://admin:admin@192.168.20.149:554/cam/realmonitor?channel=1&subtype=0
         roles:
           - restream
       # RE Stream  
       - path: rtsp://localhost:8554/Frigate_South02
         roles:
           - record

    detect:
       width: 704
       height: 480
       #width: 2592
       #height: 1944
       fps: 20
       enabled: True
       # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
       #max_disappeared: 25

#    best_image_timeout: 60

    record:
      enabled: True
      retain_days: 10
      events:
        retain:
          default: 30

    objects:
      track:
        - animal
        - car
        - motorcycle
        - person
    #  filters:
    #    car:
    #      min_score: 0.8
    #      threshold: 0.9

    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      #height: 175
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        #objects:
          #person: 15

    motion:
      # Optional: (default: 100) Minimum size in pixels of resized motion image that counts as motion
      # Increasing prevent small area motion being detected. Decreasing make detection sensitive to smaller moving o>
      contour_area: 50
```

### Relevant log output

```shell
GO2RTC LOG

2023-01-11 10:29:53.640397713  [90m16:29:53.640[0m [32mINF[0m go2rtc version 0.1-rc.6 linux/amd64
2023-01-11 10:29:53.641004933  [90m16:29:53.640[0m [32mINF[0m [api] listen [36maddr=[0m:1984
2023-01-11 10:29:53.641160141  [90m16:29:53.641[0m [32mINF[0m [rtsp] listen [36maddr=[0m:8554
2023-01-11 10:29:53.641742216  [90m16:29:53.641[0m [32mINF[0m [webrtc] listen [36maddr=[0m:8555
2023-01-11 10:29:53.641934671  [90m16:29:53.641[0m [32mINF[0m [srtp] listen [36maddr=[0m:8443
2023-01-11 10:30:06.353047063  [90m16:30:06.328[0m [31mWRN[0m [1mgithub.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:202[0m[36m >[0m [36merror=[0m[31mEOF[0m
2023-01-11 10:34:09.113175280  [90m16:34:09.112[0m [31mWRN[0m [1mgithub.com/AlexxIT/go2rtc/cmd/streams/producer.go:105[0m[36m >[0m [36merror=[0m[31mEOF[0m


NGINX LOG (jsmpeg no workin)

2023-01-11 10:58:13.454943709  10.88.10.239 - - [11/Jan/2023:10:58:13 -0600] "GET /live/jsmpeg/Frigate_Gate03 HTTP/1.1" 101 4 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0" "-"
'''


### FFprobe output from your camera

```shell
SOUTH01
fprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100

SOUTH02
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

### Frigate stats

```json
{"Frigate_Attic":{"camera_fps":10.6,"capture_pid":574,"detection_fps":6.0,"ffmpeg_pid":580,"pid":558,"process_fps":5.4,"skipped_fps":0.0},"Frigate_Doorbell":{"camera_fps":14.2,"capture_pid":578,"detection_fps":1.69,"ffmpeg_pid":584,"pid":559,"process_fps":10.5,"skipped_fps":0.0},"Frigate_FrontDr":{"camera_fps":20.1,"capture_pid":583,"detection_fps":5.9,"ffmpeg_pid":590,"pid":560,"process_fps":18.7,"skipped_fps":0.0},"Frigate_Gate01":{"camera_fps":10.5,"capture_pid":589,"detection_fps":6.37,"ffmpeg_pid":598,"pid":561,"process_fps":5.1,"skipped_fps":0.0},"Frigate_Gate03":{"camera_fps":10.1,"capture_pid":595,"detection_fps":7.6,"ffmpeg_pid":606,"pid":562,"process_fps":10.2,"skipped_fps":0.0},"Frigate_Goat":{"camera_fps":2.5,"capture_pid":603,"detection_fps":9.2,"ffmpeg_pid":614,"pid":563,"process_fps":0.5,"skipped_fps":0.0},"Frigate_Goat2":{"camera_fps":4.8,"capture_pid":610,"detection_fps":5.8,"ffmpeg_pid":623,"pid":565,"process_fps":4.7,"skipped_fps":0.0},"Frigate_MasterPatio":{"camera_fps":20.0,"capture_pid":616,"detection_fps":0.0,"ffmpeg_pid":633,"pid":567,"process_fps":19.9,"skipped_fps":0.0},"Frigate_Pool":{"camera_fps":20.1,"capture_pid":621,"detection_fps":0.0,"ffmpeg_pid":630,"pid":568,"process_fps":19.8,"skipped_fps":0.0},"Frigate_Pool2":{"camera_fps":20.0,"capture_pid":627,"detection_fps":1.7,"ffmpeg_pid":640,"pid":570,"process_fps":19.4,"skipped_fps":0.0},"Frigate_South01":{"camera_fps":20.3,"capture_pid":634,"detection_fps":0.7,"ffmpeg_pid":652,"pid":571,"process_fps":20.0,"skipped_fps":0.0},"Frigate_South02":{"camera_fps":9.2,"capture_pid":635,"detection_fps":3.6,"ffmpeg_pid":651,"pid":572,"process_fps":3.5,"skipped_fps":0.0},"Frigate_xtra1":{"camera_fps":20.1,"capture_pid":647,"detection_fps":0.0,"ffmpeg_pid":658,"pid":573,"process_fps":20.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.1"},"1":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"126":{"cpu":"0.0","mem":"0.0"},"127":{"cpu":"0.3","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"155":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"183":{"cpu":"0.0","mem":"0.0"},"218":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"255":{"cpu":"0.0","mem":"0.0"},"2802":{"cpu":"0.0","mem":"0.0"},"292":{"cpu":"0.0","mem":"0.0"},"3261":{"cpu":"6.0","mem":"0.0"},"327":{"cpu":"0.3","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"3644":{"cpu":"87.5","mem":"0.1"},"3646":{"cpu":"0.3","mem":"0.0"},"3650":{"cpu":"0.3","mem":"0.0"},"3655":{"cpu":"0.0","mem":"0.0"},"544":{"cpu":"0.0","mem":"0.1"},"550":{"cpu":"2.0","mem":"0.0"},"551":{"cpu":"3.0","mem":"0.2"},"552":{"cpu":"74.1","mem":"0.2"},"557":{"cpu":"0.0","mem":"0.0"},"558":{"cpu":"0.0","mem":"0.2"},"559":{"cpu":"0.0","mem":"0.2"},"560":{"cpu":"2.3","mem":"0.2"},"561":{"cpu":"0.0","mem":"0.2"},"562":{"cpu":"12.6","mem":"0.2"},"563":{"cpu":"0.0","mem":"0.1"},"564":{"cpu":"0.0","mem":"0.0"},"565":{"cpu":"12.3","mem":"0.2"},"566":{"cpu":"0.0","mem":"0.0"},"567":{"cpu":"2.0","mem":"0.2"},"568":{"cpu":"2.0","mem":"0.2"},"569":{"cpu":"0.0","mem":"0.0"},"570":{"cpu":"2.0","mem":"0.2"},"571":{"cpu":"2.7","mem":"0.2"},"572":{"cpu":"0.0","mem":"0.2"},"573":{"cpu":"2.7","mem":"0.2"},"574":{"cpu":"0.0","mem":"0.0"},"575":{"cpu":"0.0","mem":"0.0"},"578":{"cpu":"0.0","mem":"0.0"},"579":{"cpu":"0.0","mem":"0.1"},"583":{"cpu":"3.3","mem":"0.1"},"588":{"cpu":"0.0","mem":"0.0"},"589":{"cpu":"0.0","mem":"0.0"},"590":{"cpu":"3.0","mem":"0.1"},"595":{"cpu":"1.7","mem":"0.1"},"596":{"cpu":"0.0","mem":"0.0"},"597":{"cpu":"5.3","mem":"0.0"},"603":{"cpu":"0.0","mem":"0.0"},"604":{"cpu":"1.3","mem":"0.0"},"605":{"cpu":"0.0","mem":"0.0"},"606":{"cpu":"2.3","mem":"0.1"},"610":{"cpu":"0.7","mem":"0.1"},"613":{"cpu":"0.0","mem":"0.0"},"616":{"cpu":"3.0","mem":"0.1"},"618":{"cpu":"1.3","mem":"0.0"},"621":{"cpu":"3.0","mem":"0.1"},"623":{"cpu":"8.0","mem":"0.2"},"624":{"cpu":"15.9","mem":"0.1"},"627":{"cpu":"3.3","mem":"0.1"},"629":{"cpu":"0.0","mem":"0.0"},"630":{"cpu":"2.7","mem":"0.1"},"633":{"cpu":"2.3","mem":"0.1"},"634":{"cpu":"3.3","mem":"0.1"},"635":{"cpu":"0.0","mem":"0.0"},"640":{"cpu":"3.7","mem":"0.1"},"644":{"cpu":"0.0","mem":"0.0"},"647":{"cpu":"3.7","mem":"0.1"},"648":{"cpu":"2.3","mem":"0.0"},"650":{"cpu":"2.3","mem":"0.0"},"652":{"cpu":"2.7","mem":"0.1"},"654":{"cpu":"40.9","mem":"0.3"},"658":{"cpu":"4.7","mem":"0.1"},"664":{"cpu":"1.3","mem":"0.0"},"680":{"cpu":"1.3","mem":"0.0"},"681":{"cpu":"1.3","mem":"0.0"},"683":{"cpu":"1.0","mem":"0.0"},"705":{"cpu":"1.3","mem":"0.0"},"712":{"cpu":"6.0","mem":"0.0"},"713":{"cpu":"2.7","mem":"0.0"},"715":{"cpu":"1.7","mem":"0.0"},"717":{"cpu":"2.3","mem":"0.0"},"718":{"cpu":"2.0","mem":"0.0"},"719":{"cpu":"4.3","mem":"0.0"},"72":{"cpu":"0.0","mem":"0.0"},"722":{"cpu":"2.7","mem":"0.0"},"724":{"cpu":"8.0","mem":"0.0"},"74":{"cpu":"0.0","mem":"0.0"},"75":{"cpu":"0.0","mem":"0.0"},"76":{"cpu":"0.0","mem":"0.0"},"77":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"12.6","mem":"0.3"},"81":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"15.3","mem":"0.0"},"84":{"cpu":"0.0","mem":"0.0"},"85":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"56360.5","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"5"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":48.55,"detectors":{"coral_pci":{"detection_start":0.0,"inference_speed":9.54,"pid":551}},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":40.0,"mount_type":"tmpfs","total":67.1,"used":27.1},"/media/frigate/clips":{"free":1806803.8,"mount_type":"xfs","total":5998469.2,"used":4191665.4},"/media/frigate/recordings":{"free":1806803.8,"mount_type":"xfs","total":5998469.2,"used":4191665.4},"/tmp/cache":{"free":945.0,"mount_type":"tmpfs","total":1000.0,"used":55.0}},"temperatures":{"apex_0":46.55},"uptime":709,"version":"0.12.0-0dbf909"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest/various

### Any other information that may be helpful

Docker does not run in host mode
I connect go2rtc/frigate on docker network 

13 total cameras in system
2 model amcrest, wansview, and another cheap brand.  issue is not isoloted to any specific model and affect all
