### ISSUE TITLE
[Support]: frigate.object_processing warning

### ISSUE THREAD

**Issue by tpjanssen** [blakeblackshear/frigate#5040]
### Describe the problem you are having

I just had some warnings in the log file related to snapshot and . This warnings occured on the very same moment Frigate detect a person in a required zone. I've looked back on the 24/7 recording, and no person was there in that zone (or any other zone). The generated snapshot is a fully black tile (in the event viewer). The generated clip is very long (43 minutes) and not useable when I try to open it with VLC or any other media player. The 24/7 recordings are fine. The warning about the missing jpg in the cache is something I've noticed a couple of times before, but this is something that seems to happen to more users?

I've been running Frigate for quite some time now, I moved to the 0.12 beta on the first day. I did not have any serious problems or issues so far. I realise that based on my information there is not much you can do about it (I guess), but maybe somebody is experiencing the same thing. Any thoughts?

### Version

0.12.0 beta 2

### Frigate config file

```yaml
mqtt:
  host: addon_core_mosquitto
  user: mqtt
  password: REDACTED
  port: 1883

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  driveway:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      inputs:
        - path: rtsp://admin:REDACTED@192.168.5.141:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - restream
        - path: rtsp://admin:REDACTED@192.168.5.141:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
    motion:
      mask:
        - 1036,106,1119,150,1659,305,1920,417,1920,0,1021,0
      mqtt_off_delay: 60
      improve_contrast: True
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - zone_driveway
          - zone_porch
        pre_capture: 15
        post_capture: 15
        retain:
          default: 21
          mode: all
    snapshots:
      enabled: True
      bounding_box: True
      quality: 100
      required_zones:
        - zone_driveway
        - zone_porch
      retain:
        default: 21
    best_image_timeout: 0
    zones:
      zone_street:
        coordinates: 
          #1068,0,1920,0,1920,422,1063,113
          1068,0,1920,0,1920,422,1494,224,1063,113
        objects:
          - car
          - bus
        filters:
          person:
            min_score: 0.55
            threshold: 0.70
            #min_area: 10000
            max_area: 400000
      zone_driveway:
        coordinates:
          0,1080,1920,1080,1920,640,1694,516,1472,389,1293,274,1017,369,485,524,157,339,0,355
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.55
            threshold: 0.70
            min_area: 10000
            max_area: 400000
          cat:
            min_score: 0.55
            threshold: 0.70
            max_area: 35000
          dog:
            min_score: 0.55
            threshold: 0.70
            max_area: 35000
      zone_porch:
        coordinates:
          1041,243,1146,213,1043,167
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.55
            threshold: 0.70
            max_area: 400000
      zone_driveway_parking_1:
        coordinates:
          1335,966,1920,1043,1793,466,1654,403,1533,367,1147,641
        objects:
          - car
          - bus
        filters:
          person:
            min_score: 0.55
            threshold: 0.70
            #min_area: 10000
            max_area: 400000
      zone_driveway_parking_2:
        coordinates:
          1036,294,1239,307,1431,340,1558,397,1346,476,1146,475,1043,389
        objects:
          - car
          - bus
        filters:
          person:
            min_score: 0.55
            threshold: 0.70
            #min_area: 10000
            max_area: 400000
    objects:
      track:
        - person
        - car
        - bus
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.70
          #min_area: 10000
          max_area: 400000
        cat:
          mask:
            - 849,420,1365,1080,0,1080,0,0,589,0
        dog:
          mask:
            - 849,420,1365,1080,0,1080,0,0,589,0

detectors:
  coral:
    type: edgetpu
    device: usb

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"
  
logger:
  default: info
  logs:
    frigate.event: debug

restream:
  enabled: True
  force_audio: False
  birdseye: False
  jsmpeg:
    height: 720
    quality: 16

birdseye:
  quality: 16
  mode: motion
  
ui:
  use_experimental: False
```

### Relevant log output

```shell
2023-01-12 13:28:01.840608950  [2023-01-12 13:28:01] frigate.object_processing      WARNING : Unable to create jpg because frame 1673526480.672723 is not in the cache
2023-01-12 13:28:02.017415951  [2023-01-12 13:28:02] frigate.object_processing      WARNING : Unable to create jpg because frame 1673526480.672723 is not in the cache
2023-01-12 13:28:09.525372514  [2023-01-12 13:28:09] frigate.object_processing      WARNING : Unable to create jpg because frame 1673526480.672723 is not in the cache
2023-01-12 13:28:09.525376756  [2023-01-12 13:28:09] frigate.object_processing      WARNING : Unable to save snapshot for 1673523718.366884-gl02of.
2023-01-12 13:28:09.525378719  [2023-01-12 13:28:09] frigate.object_processing      WARNING : Unable to create clean png because frame 1673526480.672723 is not in the cache
2023-01-12 13:28:09.525380460  [2023-01-12 13:28:09] frigate.object_processing      WARNING : Unable to save clean snapshot for 1673523718.366884-gl02of.
2023-01-12 13:28:09.537355908  [2023-01-12 13:28:09] frigate.object_processing      WARNING : Unable to create jpg because frame 1673526480.672723 is not in the cache
```

### FFprobe output from your camera

```shell
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"25/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 2160,\n          \"width\": 3840\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"10/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1080,\n          \"width\": 1920\n        }\n      ]\n    }\n  }\n]"
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua
