### ISSUE TITLE
[Config Support]: 0.12.0 Beta 3 - Green bar at side of camera on hwaccel preset-intel-qsv-h264

### ISSUE THREAD

**Issue by conorlap** [blakeblackshear/frigate#5041]
### Describe the problem you are having

![Screenshot 2023-01-12 at 13 51 18](https://user-images.githubusercontent.com/57415184/212086949-51bdbd15-6b2b-4319-b5f8-8628bcaf1762.png)

Getting a green bar on the side of my detect image on 0.12.0 Beta 3 on **hwaccel preset-intel-qsv-h264**.

hwaccel preset-intel-qsv-h264 didn't exhibit this issue on 0.12.0 Beta 2.

I've tested **hwaccel_args: preset-vaapi** and it works fine. 

### Version

0.12.0-cf2466c

### Frigate config file

```yaml
cameras:
  frontdoor:
    ffmpeg:
      inputs:
          #FRONT DOOR CAMERA SUB STREAM FOR DETECTION
        - path: rtsp://localhost:8554/frontdoor-substream
          roles:
            - detect
          #FRONT DOOR CAMERA MAIN STREAM FOR HQ RECORDINGS
        - path: rtsp://admin:supersecretpassword@192.168.0.25:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - restream
        - path: rtsp://localhost:8554/frontdoor
          roles:
            - record
    detect: 
      width: 720
      height: 576
      fps: 5



detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt



  
restream:
  enabled: True
  force_audio: False


ffmpeg:
  hwaccel_args: preset-intel-qsv-h264 
  output_args:
    record: preset-record-generic-audio



database:
  path: /frigate.db
```

### Relevant log output

```shell
VAINFO on preset-intel-qsv-h264:

"{\n  \"return_code\": 0,\n  \"stderr\": \"\",\n  \"stdout\": \"vainfo: VA-API version: 1.17 (libva 2.10.0)\\nvainfo: Driver version: Intel i965 driver for Intel(R) Coffee Lake - 2.4.1\\nvainfo: Supported profile and entrypoints\\n      VAProfileMPEG2Simple            :\\tVAEntrypointVLD\\n      VAProfileMPEG2Simple            :\\tVAEntrypointEncSlice\\n      VAProfileMPEG2Main              :\\tVAEntrypointVLD\\n      VAProfileMPEG2Main              :\\tVAEntrypointEncSlice\\n      VAProfileH264ConstrainedBaseline:\\tVAEntrypointVLD\\n      VAProfileH264ConstrainedBaseline:\\tVAEntrypointEncSlice\\n      VAProfileH264ConstrainedBaseline:\\tVAEntrypointEncSliceLP\\n      VAProfileH264Main               :\\tVAEntrypointVLD\\n      VAProfileH264Main               :\\tVAEntrypointEncSlice\\n      VAProfileH264Main               :\\tVAEntrypointEncSliceLP\\n      VAProfileH264High               :\\tVAEntrypointVLD\\n      VAProfileH264High               :\\tVAEntrypointEncSlice\\n      VAProfileH264High               :\\tVAEntrypointEncSliceLP\\n      VAProfileH264MultiviewHigh      :\\tVAEntrypointVLD\\n      VAProfileH264StereoHigh         :\\tVAEntrypointVLD\\n      VAProfileVC1Simple              :\\tVAEntrypointVLD\\n      VAProfileVC1Main                :\\tVAEntrypointVLD\\n      VAProfileVC1Advanced            :\\tVAEntrypointVLD\\n      VAProfileNone                   :\\tVAEntrypointVideoProc\\n      VAProfileJPEGBaseline           :\\tVAEntrypointVLD\\n      VAProfileJPEGBaseline           :\\tVAEntrypointEncPicture\\n      VAProfileVP8Version0_3          :\\tVAEntrypointVLD\\n      VAProfileHEVCMain               :\\tVAEntrypointVLD\\n      VAProfileHEVCMain10             :\\tVAEntrypointVLD\\n      VAProfileVP9Profile0            :\\tVAEntrypointVLD\\n      VAProfileVP9Profile2            :\\tVAEntrypointVLD\"\n}"

VAINFO on preset-vaapi:

"{\n  \"return_code\": 0,\n  \"stderr\": \"\",\n  \"stdout\": \"vainfo: VA-API version: 1.17 (libva 2.10.0)\\nvainfo: Driver version: Intel i965 driver for Intel(R) Coffee Lake - 2.4.1\\nvainfo: Supported profile and entrypoints\\n      VAProfileMPEG2Simple            :\\tVAEntrypointVLD\\n      VAProfileMPEG2Simple            :\\tVAEntrypointEncSlice\\n      VAProfileMPEG2Main              :\\tVAEntrypointVLD\\n      VAProfileMPEG2Main              :\\tVAEntrypointEncSlice\\n      VAProfileH264ConstrainedBaseline:\\tVAEntrypointVLD\\n      VAProfileH264ConstrainedBaseline:\\tVAEntrypointEncSlice\\n      VAProfileH264ConstrainedBaseline:\\tVAEntrypointEncSliceLP\\n      VAProfileH264Main               :\\tVAEntrypointVLD\\n      VAProfileH264Main               :\\tVAEntrypointEncSlice\\n      VAProfileH264Main               :\\tVAEntrypointEncSliceLP\\n      VAProfileH264High               :\\tVAEntrypointVLD\\n      VAProfileH264High               :\\tVAEntrypointEncSlice\\n      VAProfileH264High               :\\tVAEntrypointEncSliceLP\\n      VAProfileH264MultiviewHigh      :\\tVAEntrypointVLD\\n      VAProfileH264StereoHigh         :\\tVAEntrypointVLD\\n      VAProfileVC1Simple              :\\tVAEntrypointVLD\\n      VAProfileVC1Main                :\\tVAEntrypointVLD\\n      VAProfileVC1Advanced            :\\tVAEntrypointVLD\\n      VAProfileNone                   :\\tVAEntrypointVideoProc\\n      VAProfileJPEGBaseline           :\\tVAEntrypointVLD\\n      VAProfileJPEGBaseline           :\\tVAEntrypointEncPicture\\n      VAProfileVP8Version0_3          :\\tVAEntrypointVLD\\n      VAProfileHEVCMain               :\\tVAEntrypointVLD\\n      VAProfileHEVCMain10             :\\tVAEntrypointVLD\\n      VAProfileVP9Profile0            :\\tVAEntrypointVLD\\n      VAProfileVP9Profile2            :\\tVAEntrypointVLD\"\n}"
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"19.5"},"1":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"0.0","mem":"0.1"},"113":{"cpu":"0.0","mem":"0.1"},"114":{"cpu":"0.0","mem":"0.1"},"115":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"262":{"cpu":"0.0","mem":"1.0"},"268":{"cpu":"0.3","mem":"0.1"},"269":{"cpu":"0.0","mem":"3.5"},"271":{"cpu":"0.7","mem":"1.1"},"275":{"cpu":"1.0","mem":"1.1"},"276":{"cpu":"0.7","mem":"1.1"},"277":{"cpu":"0.0","mem":"0.1"},"278":{"cpu":"0.0","mem":"1.0"},"279":{"cpu":"0.0","mem":"1.0"},"280":{"cpu":"1.3","mem":"1.1"},"281":{"cpu":"0.0","mem":"0.1"},"283":{"cpu":"1.7","mem":"1.1"},"285":{"cpu":"0.0","mem":"1.1"},"287":{"cpu":"1.7","mem":"0.4"},"288":{"cpu":"0.0","mem":"0.0"},"294":{"cpu":"4.3","mem":"0.2"},"295":{"cpu":"0.0","mem":"1.1"},"296":{"cpu":"0.0","mem":"0.0"},"298":{"cpu":"2.0","mem":"0.4"},"305":{"cpu":"4.3","mem":"0.2"},"33":{"cpu":"0.0","mem":"0.0"},"72":{"cpu":"0.0","mem":"0.0"},"74":{"cpu":"0.0","mem":"0.0"},"75":{"cpu":"0.0","mem":"0.0"},"76":{"cpu":"0.0","mem":"0.0"},"77":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"2.7","mem":"1.5"},"81":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"0.0","mem":"0.0"},"847":{"cpu":"0.0","mem":"0.0"},"853":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"3.7","mem":"0.3"},"88":{"cpu":"0.0","mem":"0.1"},"90":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"649.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"4.41,"}},"detection_fps":0.0,"detectors":{"ov":{"detection_start":0.0,"inference_speed":83.98,"pid":269}},"frontdoor":{"camera_fps":5.0,"capture_pid":280,"detection_fps":0.0,"ffmpeg_pid":287,"pid":275,"process_fps":5.0,"skipped_fps":0.0},"frontdoor-gif-notifications":{"camera_fps":5.0,"capture_pid":283,"detection_fps":0.0,"ffmpeg_pid":298,"pid":276,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"intel-qsv":{"gpu":"0.31 %","mem":"- %"}},"kitchen_tapo":{"camera_fps":0.0,"capture_pid":285,"detection_fps":0.0,"ffmpeg_pid":800,"pid":278,"process_fps":0.0,"skipped_fps":0.0},"office":{"camera_fps":0.0,"capture_pid":295,"detection_fps":0.0,"ffmpeg_pid":806,"pid":279,"process_fps":0.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":64.6,"mount_type":"tmpfs","total":67.1,"used":2.5},"/media/frigate/clips":{"free":4930303.7,"mount_type":"fuse.mergerfs","total":37700917.9,"used":32770547.2},"/media/frigate/recordings":{"free":4930303.7,"mount_type":"fuse.mergerfs","total":37700917.9,"used":32770547.2},"/tmp/cache":{"free":981.7,"mount_type":"tmpfs","total":1000.0,"used":18.3}},"temperatures":{},"uptime":110,"version":"0.12.0-cf2466c"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

FFPROBE OUTPUT:

"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"5/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 576,\n          \"width\": 720\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1920,\n          \"width\": 2560\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"bit_rate\": \"64000\",\n          \"codec_long_name\": \"PCM A-law / G.711 A-law\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1920,\n          \"width\": 2560\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"bit_rate\": \"64000\",\n          \"codec_long_name\": \"PCM A-law / G.711 A-law\"\n        }\n      ]\n    }\n  }\n]"

**Custom go2rtc config:**

```
log:
  format: text
  
webrtc:
  listen: ":8555"  
  candidates:
    - stun:8555

rtsp:
  listen: ":8554"
  
api:
  listen: ":1984"  


streams:
  frontdoor-substream:
    - rtsp://admin:supersecretpassword@192.168.0.25:554/cam/realmonitor?channel=1&subtype=1

```

**Comment by NickM-27** [comment]
I know it's wrong but just curious, what happens if you set your detect to

```yaml
detect: 
  width: 1280
  height: 720
```

**Comment by conorlap** [comment]
![Screenshot 2023-01-12 at 14 18 12](https://user-images.githubusercontent.com/57415184/212090329-b1205756-0b8e-409e-9ae1-dbd1b6a50775.png)

Same thing happens

**Comment by tpjanssen** [comment]
I'm having the same issue, but at my instance it's showing a green bar on the bottom.

**Comment by NickM-27** [comment]
What resolution is your stream?

**Comment by tpjanssen** [comment]
Detection at 1280x720, recording on 1920x1080

**Comment by NickM-27** [comment]
Okay, can either of y'all try the following config

```yaml
ffmpeg:
  hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv
  output_args:
    detect: -vf pp_qsv=framerate=5,scale_qsv=w={YOUR_CAMERA_WIDTH}:h={YOUR_CAMERA_HEIGHT}:format=nv12,hwdownload,format=nv12,format=yuv420p -f rawvideo
```

being sure to replace `{YOUR_CAMERA_HEIGHT}` with a number including removing the curly braces. Confirm whether or not this still happens (I hope it does with this config)

**Comment by conorlap** [comment]
![Screenshot 2023-01-12 at 17 08 44](https://user-images.githubusercontent.com/57415184/212133337-b64a8af9-3169-4eda-b41c-9a0c1a178e5e.png)

Still happening here yep!

**Comment by NickM-27** [comment]
Okay great now please try

```yaml
ffmpeg:
  hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128 -hwaccel_output_format qsv -c:v h264_qsv
  output_args:
    detect: -vf vpp_qsv=framerate=5:w={YOUR_CAMERA_WIDTH}:h={YOUR_CAMERA_HEIGHT}:format=nv12,hwdownload,format=nv12,format=yuv420p -f rawvideo
```

and confirm if this still happens. If there is an error please let it run for 1 minute then paste the logs.
