### ISSUE TITLE
[Config Support]: How does the new Restream feature fit in with the hass integration?

### ISSUE THREAD

**Issue by SpartacusIam** [blakeblackshear/frigate#5047]
### Describe the problem you are having

In the beta release docs, the hass integration still refers to RTMP which is now deprecated.  How do we configure our cameras (specifically those using a main and substream) to work with hass in the new beta release?

### Version

Release 0.12.0 Beta 3

### Frigate config file

```yaml
mqtt:

  host: 10.4.110.70
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: '{FRIGATE_MQTT_PASSWORD}'
  stats_interval: 60

detectors:
  coral_pci:
    type: edgetpu
    device: pci

birdseye:

  enabled: False
  width: 1280
  height: 720
  quality: 8
  mode: motion

cameras:
  
  01-garage-driveway:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/01-garage-driveway
          roles:
            - record
        - path: rtsp://10.4.130.72:554/ch01/0
          roles:
            - restream
        - path: rtsp://10.4.130.72:554/ch01/1
          roles:
            - detect
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

    zones:
      driveway_entry:
        coordinates: 966,129,1052,64,1128,67,1226,76,1228,147,1176,152,1087,148
      driverway_main:
        coordinates: 1133,720,1280,335,1280,157,1107,159,926,137,433,417,701,720
      church_st:
        coordinates: 254,177,599,0,728,0,587,74,283,259
        objects:
          - person
      greenmeadow_rd:
        coordinates: 728,0,578,95,839,60,997,48,1137,54,1280,63,1280,0
        objects:
          - person
      yard:  
        coordinates: 423,409,1015,79,654,92,0,522,0,720,658,720
    
    motion:
      mask:
        - 0,481,283,272,252,192,242,141,237,101,215,42,294,40,301,0,0,0

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      required_zones:
        - driveway_entry
        - driveway_main
        - greenmeadow_rd
        - church_st
        - yard  
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        - car
      filters:
        person:
          min_score: 0.55
          threshold: 0.65
          mask:
            - 311,245,328,241,325,224,310,228

    record:
      enabled: True
      events:
        required_zones:
          - driveway_entry
          - driveway_main
          - greenmeadow_rd
          - church_st
          - yard  
        retain:
          default: 28
          mode: active_objects
  
  02-front-doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/02-front-doorbell
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.4.130.79:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - restream
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.4.130.79:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

    zones:
      greenmeadow_rd:
        coordinates: 640,0,0,0,0,330,640,234
        objects:
          - person
      front_yard:
        coordinates: 153,311,216,293,561,256,640,253,640,344,430,480,81,397
        
    motion:
      mask:
        - 339,0,640,0,640,0,640,32,338,34
        - 0,86,21,33,0,21

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      required_zones:
        - greenmeadow_rd
        - front_yard
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        #- car

    record:
      enabled: True
      events:
        required_zones:
          - greenmeadow_rd
          - front_yard
        retain:
          default: 28
          mode: active_objects

  03-front-yard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/03-front-yard
          roles:
            - record
        - path: rtsp://10.4.130.71:554/ch01/0
          roles:
            - restream
        - path: rtsp://10.4.130.71:554/ch01/1
          roles:
            - detect
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    

    zones:
      driveway_entry:
        coordinates: 1052,245,1175,160,899,108,812,188
      driveway_main:
        coordinates: 563,247,349,262,192,246,105,318,272,441,647,460,945,368,1049,253,796,194
      greenmeadow_rd:
        coordinates: 1280,0,345,0,343,66,381,60,472,56,603,51,755,60,1280,149
        objects:
          - person
      front_yard:
        coordinates: 184,183,371,252,569,240,794,186,878,106,783,91,332,86
        
    motion:
      mask:
        - 295,0,293,33,0,34,0,0

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      required_zones:
        - driveway_entry
        - driveway_main
        - greenmeadow_rd
        - front_yard
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        - car
      filters:
        person:
          min_score: 0.55
          threshold: 0.65
          mask:
            - 246,620,299,615,298,551,250,556
            - 310,74,349,66,344,30,313,32 
    
    record:
      enabled: True
      events:
        required_zones:
          - driveway_entry
          - driveway_main
          - greenmeadow_rd
          - front_yard
        retain:
          default: 28
          mode: active_objects
      
  04-back-deck:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/04-back-deck
          roles:
            - record
        - path: rtsp://10.4.130.73:554/ch01/0
          roles:
            - restream
        - path: rtsp://10.4.130.73:554/ch01/1
          roles:
            - detect
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:
        - 159,31,267,31,269,0,154,0
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        #- car

    record:
      enabled: True
      events:
        retain:
          default: 28
          mode: active_objects
      
  05-garage-inside:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/05-garage-inside
          roles:
            - record
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.4.130.75:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - restream
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.4.130.75:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

    motion:
      mask:
        - 96,24,171,24,172,0,97,0

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 30

        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        #- car

    record:
      enabled: True
      events:
        retain:
          default: 28
          mode: active_objects
  
  06-back-yard:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/06-back-yard
          roles:
            - record
        - path: rtsp://10.4.130.74:554/ch01/0
          roles:
            - restream
        - path: rtsp://10.4.130.74:554/ch01/1
          roles:
            - detect
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

    motion:
      mask:
        - 166,36,268,34,271,0,168,0

    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      retain:
        default: 30
        objects:
          person: 45
    objects:
      track:
        - person
        - cat
        - dog
        #- car

    record:
      enabled: True
      events:
        retain:
          default: 28
          mode: active_objects
    
ffmpeg:

  global_args: -hide_banner -loglevel error

  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - "1"
  
  output_args: 

    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

logger:
  default: info
  logs:
    watchdog.back-yard: warning
    watchdog.garage-driveway: warning
```

### Relevant log output

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

**Comment by NickM-27** [comment]
Thanks, will update the docs. If you have restream enabled then the hass integration will automatically use that as the source for the camera.

**Comment by SpartacusIam** [comment]
> 

With the new restream feature, how would I restream the substream while recording the main stream?

**Comment by NickM-27** [comment]
Set the restream role on the substream, use the restream as the source for detect, have the recording role connect directly to the camera

**Comment by SpartacusIam** [comment]
> Set the restream role on the substream, use the restream as the source for detect, have the recording role connect directly to the camera

I'm not sure I understand how to use the restream as the source for detect.  How would the config look like for this camera?

```
  01-garage-driveway:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/01-garage-driveway
          roles:
            - 
        - path: rtsp://10.4.130.72:554/ch01/0 [main stream]
          roles:
            - 
        - path: rtsp://10.4.130.72:554/ch01/1 [sub stream]
          roles:
            - 
```

**Comment by NickM-27** [comment]
```yaml
  01-garage-driveway:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/01-garage-driveway
          roles:
            - detect
        - path: rtsp://10.4.130.72:554/ch01/0 [main stream]
          roles:
            - record
        - path: rtsp://10.4.130.72:554/ch01/1 [sub stream]
          roles:
            - restream
```

**Comment by SpartacusIam** [comment]
> ```yaml
>   01-garage-driveway:
>     ffmpeg:
>       inputs:
>         - path: rtsp://localhost:8554/01-garage-driveway
>           roles:
>             - detect
>         - path: rtsp://10.4.130.72:554/ch01/0 [main stream]
>           roles:
>             - record
>         - path: rtsp://10.4.130.72:554/ch01/1 [sub stream]
>           roles:
>             - restream
> ```

Thanks!

**Comment by tmjpugh** [comment]
The [beta docs](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream) "with substream" sections say use the substream for detect detect role and the main (high res stream) for restream role.
the Record role uses restream api link

```

cameras:
  test_cam:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/test_cam # <--- the name here must match the name of the camera
          roles:
            - record
        - path: rtsp://192.168.1.5:554/stream # <--- camera high res stream
          roles:
            - restream
        - path: rtsp://192.168.1.5:554/substream # <--- camera sub stream
          roles:
            - detect
```
