### ISSUE TITLE
[UI] vainfo not available on Xeon machines

### ISSUE THREAD

**Issue by zacs** [blakeblackshear/frigate#5049]
### Describe the problem you are having

Running the latest beta (Nvidia tensor support is A+, you guys kick ass!), and found a small issue. I've got a Xeon proc and it doesn't have Quicksync (which is fine), but in the UI on the "System" page, the "VAINFO" button returns a bunch of error text. Might make sense to either hide the button or detect exit code and say "Info not available" or something. 

This is the text that shows up in the modal box: 

```
"{\n  \"return_code\": 3,\n  \"stderr\": \"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\\nerror: can't connect to X server!\\nlibva info: VA-API version 1.17.0\\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so\\nlibva info: va_openDriver() returns -1\\nvaInitialize failed with error code -1 (unknown libva error),exit\",\n  \"stdout\": \"\"\n}"
```

![image](https://user-images.githubusercontent.com/27705/212161658-b1f19f78-ae2b-4d66-9074-03dad70c78cd.png)

### Version

0.12.0-CF2466C

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
"{\n  \"return_code\": 3,\n  \"stderr\": \"error: XDG_RUNTIME_DIR is invalid or not set in the environment.\\nerror: can't connect to X server!\\nlibva info: VA-API version 1.17.0\\nlibva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so\\nlibva info: va_openDriver() returns -1\\nvaInitialize failed with error code -1 (unknown libva error),exit\",\n  \"stdout\": \"\"\n}"
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Unifi
