### ISSUE TITLE
[Support]: Object Mask not working

### ISSUE THREAD

**Issue by jsbowling42** [blakeblackshear/frigate#5057]
### Describe the problem you are having

I created an object mask for cars to help with ID swapping and after the beta 3 im now seeing the binding box reappear for the area i masked off. maybe i miss understand how the mask works.
recognized car (no event in the events log though):
![car](https://user-images.githubusercontent.com/35424582/212209512-261a047b-a7dc-4f6a-afb1-ad331117d2a2.JPG)

mask:
![carMask](https://user-images.githubusercontent.com/35424582/212209589-f4d17f49-9af8-4581-988c-0d6f7b89a3cf.JPG)

### Version

0.12 Beta 3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.65
  user: xxx
  password: xxx
 

# Optional: Restream configuration
# NOTE: Can be overridden at the camera level
restream:
  # Optional: Enable the restream (default: True)
  enabled: True
  # Optional: Force audio compatibility with browsers (default: shown below)
  force_audio: True
  # Optional: Video encoding to be used. By default the codec will be copied but
  # it can be switched to another or an MJPEG stream can be encoded and restreamed
  # as h264 (default: shown below)
  video_encoding: "copy"
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  birdseye: False

ffmpeg:
  hwaccel_args: -c:v h264_cuvid


cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            # - clips
            - record
            - restream
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          threshold: 0.7
        cat:
          threshold: 0.7
        car:
          mask:
            - 421,97,397,125,472,122,516,121,555,124,743,84,773,52,556,62
          min_score: 0.5
          threshold: 0.7
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
      required_zones:
        - driveway_entrance
        - side_yard
        - front_yard
        - driveway
    motion:
      # 1080
      mask: 21,1053,510,1051,510,1006,21,1005

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
          - driveway_entrance
          - side_yard
          - front_yard
          - driveway
        retain:
          default: 14
          mode: active_objects
    zones:
      driveway_entrance:
        # 1920x1080
        coordinates: 1114,202,1336,229,1324,206,1132,182
        objects:
          - person
          - dog
          - cat
          - car
      driveway:
        coordinates: 0,1080,1920,1080,1920,753,1920,689,1880,650,1859,615,1834,583,1801,543,1779,516,1756,497,1738,473,1708,458,1693,441,1673,424,1687,401,1681,383,1645,373,1605,363,1563,352,1529,345,1495,333,1455,324,1424,314,1396,300,1373,283,1321,231,1122,209,1073,243,1031,257,952,259,877,266,810,280,769,297,711,331,656,359,541,429,451,485,360,545,232,640,147,706,0,831
        objects:
          - car
          - person
          - dog
          - cat
      side_yard:
        coordinates:  0,784,52,753,102,719,141,680,174,657,259,596,316,551,367,514,422,483,472,452,524,425,564,400,605,380,637,355,672,336,713,318,737,298,776,281,828,264,884,253,920,247,968,249,997,246,1044,239,1077,233,1105,218,1116,202,1088,196,1051,194,1021,192,983,188,920,179,886,189,802,216,722,239,574,291,446,343,321,390,178,469,95,517,0,499
        objects: 
          - person
          - dog
          - cat
      front_yard:
        coordinates: 1574,267,1630,280,1669,291,1695,300,1724,305,1721,325,1704,365,1683,372,1654,366,1616,357,1584,349,1553,342,1520,333,1483,321,1452,312,1423,302,1396,292,1376,275,1362,261,1349,247,1345,225
        objects: 
          - person
          - dog
          - cat
  front_Door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://
          roles:
            # - clips
            - record
            - restream
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          threshold: 0.7
        cat:
          threshold: 0.7
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
      required_zones:
        - front_yard
    motion:
      mask: 1887,0,1883,40,1348,39,1345,0


    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
          - front_yard
        retain:
          default: 14
          mode: active_objects
    zones:
      front_yard:
        coordinates: 572,1080,1920,1080,1920,780,1270,666,1276,640,1084,613,1001,618,898,625,841,625,794,623,749,630,697,634,586,635,593,682
        objects: 
          - person
          - dog
          - cat
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Amcrest
