### ISSUE TITLE
[Config Support]: Can't get TensorRT to start up

### ISSUE THREAD

**Issue by Dravelz-21** [blakeblackshear/frigate#5058]
### Describe the problem you are having

Hi. I generated the tensor models based on [this](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/detectors#generate-models) guide and it always errors out on startup.

I see that "libyolo_layer.so" is missing but don't know how to generate it or download it.

### Version

0.12.0 Beta 3

### Frigate config file

```yaml
mqtt:
  host: #
  port: 1883
  user: #
  password: #


detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

cameras:
  test:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://###
          roles:
            - detect

    detect:
       width: 1280
       height: 720
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 3
        objects:
          person: 3

objects:
  track:
    - person

record:
  enabled: True
  retain:
    days: 7
    mode: motion

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 10
    objects:
      person: 14
```

### Relevant log output

```shell
frigate    | 2023-01-13 00:32:08.358329444  [2023-01-13 00:32:08] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. /trt-models/libyolo_layer.so: cannot open shared object file: No such file or directory
frigate    | 2023-01-13 00:32:08.359403033  Traceback (most recent call last):
frigate    | 2023-01-13 00:32:08.359442155    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate    | 2023-01-13 00:32:08.359444290      self.run()
frigate    | 2023-01-13 00:32:08.359446239    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate    | 2023-01-13 00:32:08.359447969      self._target(*self._args, **self._kwargs)
frigate    | 2023-01-13 00:32:08.359457807    File "/opt/frigate/frigate/object_detection.py", line 97, in run_detector
frigate    | 2023-01-13 00:32:08.359459800      object_detector = LocalObjectDetector(detector_config=detector_config)
frigate    | 2023-01-13 00:32:08.359461683    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
frigate    | 2023-01-13 00:32:08.359463160      self.detect_api = create_detector(detector_config)
frigate    | 2023-01-13 00:32:08.359464679    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
frigate    | 2023-01-13 00:32:08.359466012      return api(detector_config)
frigate    | 2023-01-13 00:32:08.359470574    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 225, in __init__
frigate    | 2023-01-13 00:32:08.359474438      self.engine = self._load_engine(detector_config.model.path)
frigate    | 2023-01-13 00:32:08.359484216    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 93, in _load_engine
frigate    | 2023-01-13 00:32:08.359485993      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
frigate    | 2023-01-13 00:32:08.359487896  FileNotFoundError: [Errno 2] No such file or directory: '/trt-models/yolov7-tiny-416.trt'
frigate    | 2023-01-13 00:32:08.359532220  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f8a149f5550>
frigate    | 2023-01-13 00:32:08.359533896  Traceback (most recent call last):
frigate    | 2023-01-13 00:32:08.359551406    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 244, in __del__
frigate    | 2023-01-13 00:32:08.359767143      if self.outputs is not None:
frigate    | 2023-01-13 00:32:08.359782585  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
frigate    | 2023-01-13 00:32:28.657434102  [2023-01-13 00:32:28] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | 2023-01-13 00:32:28.669592937  exit OK
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other
