### ISSUE TITLE
[Support]: Frigate turns off detection after restart

### ISSUE THREAD

**Issue by EduardoLaranjo** [blakeblackshear/frigate#5065]
### Describe the problem you are having

For some reason when I restart frigate container, frigate turns off detection only for the second camera.

### Version

version 12-beta3

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: mosquitto
  user: admin
  password: password

detectors:
  ov_detector:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  enabled: True

record:
  enabled: True
  retain:
    days: 15

ffmpeg:
  hwaccel_args: preset-vaapi

objects:
  track:
    - person
    - cat
    - mouse
    - dog
    - car

cameras:  
  pool:
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: http://10.10.30.253/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - restream
        - path: http://10.10.30.253/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 7
  garage:
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: http://10.10.30.254/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - restream
        - path: http://10.10.30.254/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 7 
    record:
      events:
        required_zones:
          - garage_street
          - garage_yard
    zones:
      garage_street:
        coordinates: 896,0,896,222,56,274,0,250,0,0
        objects:
          - person
      garage_yard:
        coordinates: 0,672,896,672,896,235,770,216,548,218,221,250,39,292,0,345
        objects:
          - person
          - car
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink

### Any other information that may be helpful

Could this be relate to readonly docker volumes?
