### ISSUE TITLE
[Support]: I see birdseye just fine, but my cameras itself do not seem be able to be casted

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#5067]
### Describe the problem you are having

Followup from previous issue, with configs.

After having enabled restream configurations, i see birdseye just fine now. 
However, i still have issues actually casting the individual cameras to chromecast, either with the camera entities or the restreamed rtsp url. When i do, it goes beyond the dash cast icon now, and looks to be streaming with a bar at the bottom, but nothing seems to show.

I did think of changing the localhost as per the restream docs to the actual ip of the instance frigate is running on, but that didn't seemed to make a difference.

I casted them from the frigate lovelace card by dermotduffy, and that worked fine.

### Version

0.12.0-0dbf909

### Frigate config file

```yaml
mqtt:

  host: 192.168.50.148
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: Mqttforyouandm3!
  stats_interval: 300

record:
  expire_interval: 10


timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:

  license_plate:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/license_plate
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=5&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream 
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15

  greenhouse_2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/greenhouse_2
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.170:554/user=admin&password=Van1llaPa&channel=3&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15

  front_driveway_1:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_driveway_1
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=6&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15
        
  front_driveway_2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_driveway_2
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=8&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_2_close_in
#        - front_driveway_2_whole_area
      crop: True
      height: 500
      retain:
        default: 3
#    zones:
#      front_driveway_2_close_in:
#        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
#        objects:
#          - car
#          - person
#          - dog
#          - cat
#          - bicycle
 #     front_driveway_2_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
        - 889,476,891,596,785,598,786,476
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_2_close_in
#          - front_driveway_2_whole_area
        pre_capture: 5
        post_capture: 15
        
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_porch
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=7&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
  #    mask:
  #      - 0,480,198,480,200,449,0,451
  #      - 640,0,640,36,640,111,608,135,485,96,504,0
  #      - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
  #      - 370,0,356,100,291,79,292,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
#      required_zones:
#        - front_porch_close_in
      retain:
        default: 5
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    #zones:
    #  front_porch_close_in:
    #    coordinates: 45,480,362,480,640,480,640,213,554,145,525,328,466,343,408,272,348,70,253,64,181,118,67,178
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
#        required_zones:
#         - front_porch_close_in
        pre_capture: 5
        post_capture: 15
        
  back_porch:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/back_porch
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=1&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
 #      person:
 #         mask:
 #           - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  diningroom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/diningroom
          roles:
            - detect
            - record
        - path: rtsp://Admin1:Van1llaPa1@192.168.50.227/live0
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1382,58,1872,55,1868,8,1382,7
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/kitchen
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.70/live0
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1382,58,1872,55,1868,8,1382,7
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=2&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  greenhouse:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/greenhouse
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=Van1llaPa&channel=3&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
        
detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

restream:
  birdseye: True
  jsmpeg:
    height: 640
    quality: 1
```

### Relevant log output

```shell
No log output observed that shows any errors.
```

### FFprobe output from your camera

```shell
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "12/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1080, "width": 1920 } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "12/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1080, "width": 1920 } ] } } ]
```

### Frigate stats

```json
{"back_porch":{"camera_fps":6.0,"capture_pid":317,"detection_fps":0.0,"ffmpeg_pid":331,"pid":287,"process_fps":6.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"0.0","mem":"0.1"},"113":{"cpu":"0.0","mem":"0.1"},"114":{"cpu":"0.0","mem":"0.1"},"115":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"262":{"cpu":"0.0","mem":"1.0"},"268":{"cpu":"0.7","mem":"0.1"},"269":{"cpu":"13.3","mem":"1.7"},"271":{"cpu":"23.6","mem":"1.7"},"278":{"cpu":"2.7","mem":"1.5"},"279":{"cpu":"0.0","mem":"0.2"},"280":{"cpu":"8.3","mem":"1.7"},"281":{"cpu":"0.7","mem":"1.9"},"282":{"cpu":"0.0","mem":"0.2"},"2826":{"cpu":"9.0","mem":"1.0"},"2829":{"cpu":"4.7","mem":"0.3"},"283":{"cpu":"0.7","mem":"1.8"},"2830":{"cpu":"9.3","mem":"1.1"},"2832":{"cpu":"5.3","mem":"0.3"},"284":{"cpu":"0.0","mem":"0.2"},"285":{"cpu":"1.0","mem":"1.4"},"286":{"cpu":"0.0","mem":"0.2"},"287":{"cpu":"0.7","mem":"1.4"},"288":{"cpu":"1.0","mem":"1.6"},"289":{"cpu":"0.0","mem":"0.2"},"290":{"cpu":"0.7","mem":"1.9"},"291":{"cpu":"0.0","mem":"0.2"},"292":{"cpu":"0.3","mem":"1.9"},"293":{"cpu":"10.0","mem":"1.8"},"294":{"cpu":"0.0","mem":"0.2"},"295":{"cpu":"2.7","mem":"1.4"},"296":{"cpu":"0.0","mem":"0.2"},"299":{"cpu":"3.0","mem":"1.4"},"300":{"cpu":"9.3","mem":"0.8"},"301":{"cpu":"3.0","mem":"1.4"},"304":{"cpu":"0.0","mem":"0.2"},"306":{"cpu":"12.3","mem":"1.1"},"307":{"cpu":"2.7","mem":"1.4"},"308":{"cpu":"0.3","mem":"0.3"},"312":{"cpu":"3.0","mem":"1.4"},"314":{"cpu":"12.3","mem":"1.2"},"315":{"cpu":"0.3","mem":"0.3"},"316":{"cpu":"0.0","mem":"0.2"},"317":{"cpu":"3.3","mem":"1.4"},"321":{"cpu":"4.0","mem":"1.4"},"325":{"cpu":"3.7","mem":"1.4"},"327":{"cpu":"0.3","mem":"0.3"},"33":{"cpu":"0.0","mem":"0.0"},"330":{"cpu":"3.3","mem":"1.4"},"331":{"cpu":"11.6","mem":"1.3"},"332":{"cpu":"13.3","mem":"0.9"},"337":{"cpu":"3.3","mem":"1.4"},"339":{"cpu":"12.6","mem":"1.2"},"341":{"cpu":"12.0","mem":"1.2"},"352":{"cpu":"0.7","mem":"0.3"},"355":{"cpu":"11.3","mem":"1.5"},"357":{"cpu":"0.3","mem":"0.3"},"362":{"cpu":"13.3","mem":"1.2"},"367":{"cpu":"0.7","mem":"0.3"},"375":{"cpu":"0.3","mem":"0.3"},"378":{"cpu":"0.3","mem":"0.3"},"4809":{"cpu":"0.0","mem":"0.0"},"4814":{"cpu":"0.0","mem":"0.0"},"72":{"cpu":"0.0","mem":"0.0"},"73":{"cpu":"0.0","mem":"0.0"},"74":{"cpu":"0.0","mem":"0.0"},"75":{"cpu":"0.0","mem":"0.0"},"76":{"cpu":"0.0","mem":"0.0"},"77":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"4.7","mem":"0.2"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.2"},"83":{"cpu":"10.6","mem":"4.6"},"85":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"5293.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"4.07,"}},"detection_fps":30.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":11.23,"pid":269}},"diningroom":{"camera_fps":6.1,"capture_pid":321,"detection_fps":1.6,"ffmpeg_pid":2830,"pid":288,"process_fps":6.1,"skipped_fps":0.0},"front_driveway_1":{"camera_fps":5.0,"capture_pid":301,"detection_fps":0.0,"ffmpeg_pid":314,"pid":281,"process_fps":5.0,"skipped_fps":0.0},"front_driveway_2":{"camera_fps":5.1,"capture_pid":307,"detection_fps":0.1,"ffmpeg_pid":355,"pid":283,"process_fps":5.1,"skipped_fps":0.0},"front_porch":{"camera_fps":5.1,"capture_pid":312,"detection_fps":0.2,"ffmpeg_pid":341,"pid":285,"process_fps":5.1,"skipped_fps":0.0},"garage":{"camera_fps":6.1,"capture_pid":330,"detection_fps":0.0,"ffmpeg_pid":339,"pid":292,"process_fps":6.1,"skipped_fps":0.0},"greenhouse":{"camera_fps":5.0,"capture_pid":337,"detection_fps":8.0,"ffmpeg_pid":362,"pid":293,"process_fps":5.1,"skipped_fps":0.0},"greenhouse_2":{"camera_fps":5.1,"capture_pid":299,"detection_fps":11.4,"ffmpeg_pid":306,"pid":280,"process_fps":5.1,"skipped_fps":0.0},"kitchen":{"camera_fps":6.2,"capture_pid":325,"detection_fps":0.0,"ffmpeg_pid":2826,"pid":290,"process_fps":6.2,"skipped_fps":0.0},"license_plate":{"camera_fps":5.0,"capture_pid":295,"detection_fps":9.6,"ffmpeg_pid":300,"pid":278,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":226.1,"mount_type":"tmpfs","total":268.4,"used":42.4},"/media/frigate/clips":{"free":160713.8,"mount_type":"ext4","total":248215.2,"used":76278.3},"/media/frigate/recordings":{"free":160713.8,"mount_type":"ext4","total":248215.2,"used":76278.3},"/tmp/cache":{"free":930.1,"mount_type":"tmpfs","total":1000.0,"used":69.9}},"temperatures":{},"uptime":2108,"version":"0.12.0-0dbf909"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Inference is usually about 10 or so.
