### ISSUE TITLE
[HW Accel Support]: Beta 0.12.0-0dbf909 ffmpeg is missing hevc_v4l2m2m codec on RPi 4

### ISSUE THREAD

**Issue by heresiarch** [blakeblackshear/frigate#5085]
### Describe the problem you are having

The docker image provided is missing the HEVC Codec on RPi4, but the RPi ffmpeg on the host has support for it
From the docker image:
``` bash
`ffmpeg -hide_banner -encoders | grep v4l2
 V..... h263_v4l2m2m         V4L2 mem2mem H.263 encoder wrapper (codec h263)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 encoder wrapper (codec mpeg4)
 V..... vp8_v4l2m2m          V4L2 mem2mem VP8 encoder wrapper (codec vp8)
```
From the RPi CLI
``` bash
ffmpeg -hide_banner -encoders | grep v4l2
 V..... h263_v4l2m2m         V4L2 mem2mem H.263 encoder wrapper (codec h263)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... hevc_v4l2m2m         V4L2 mem2mem HEVC encoder wrapper (codec hevc)
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 encoder wrapper (codec mpeg4)
 V..... vp8_v4l2m2m          V4L2 mem2mem VP8 encoder wrapper (codec vp8)
```

### Version

Beta 0.12.0-0dbf909

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.178.8
  # Optional: port (default: shown below)
  port: 8883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  tls_ca_certs: /config/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  tls_client_cert: /config/client.crt
  tls_client_key: /config/client.key
  tls_insecure: true

detectors:
  coral:
    type: edgetpu
    device: usb

restream:
#   # Optional: Enable the restream (default: True)
  enabled: False

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False

#restream:
#  enabled: False


birdseye:
  enabled: True
  mode: continuous

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects

logger:
 # Optional: default log level (default: shown below)
  default: debug
  logs:
    frigate.app: debug
    frigate.mqtt: debug
    frigate.edgetpu: debug
    frigate.zeroconf: debug

cameras:
  camera_1: 
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
      hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://camadmin:xxx@192.168.178.31/stream1
          roles:
            - rtmp
            - record
        - path: rtsp://camadmin:xxx@192.168.178.31/stream2
          roles:
            - detect    
    detect:
      width: 640
      height: 360
  camera_2: 
    ffmpeg:
      #hwaccel_args: preset-rpi-64-h264
      hwaccel_args: -c:v h264_v4l2m2m
      inputs:
        - path: rtsp://camadmin:xxx@192.168.178.30/stream1
          roles:
            - rtmp
            - record
        - path: rtsp://camadmin:xxx@192.168.178.30/stream2
          roles:
            - detect   
    detect:
      width: 640
      height: 360
  steinel:
    ffmpeg:
      hwaccel_args: -c:v hevc_v4l2m2m
      inputs:
        - path: rtsp://192.168.178.76:554/user=admin&password=xxx&channel=1&stream=0.sdp?real_stream--rtp-caching=500
          roles:
            - rtmp
            - record
        - path: rtsp://192.168.178.76:554/user=admin&password=xxx&channel=1&stream=1.sdp?real_stream--rtp-caching=500
          roles:
            - detect
  #    #output_args:
  #      #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an -tag:v hvc1
  #      #record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_qsv -b:v 4M -r 5
  #    #  record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_qsv -b:v 4M -r 6
  #  detect:
  #    width: 640 # <---- update for your camera's resolution
  #    height: 360 # <---- update for your camera's resolution
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate-beta
    privileged: true 
    restart: unless-stopped
    image: blakeblackshear/frigate:0.12.0-beta2
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/src/frigate/config.yml:/config/config.yml:ro
      - /home/pi/src/frigate/ca.crt:/config/ca.crt:ro
      - /home/pi/src/frigate/client.crt:/config/client.crt:ro
      - /home/pi/src/frigate/client.key:/config/client.key:ro
      #- /home/rene/Downloads/frigate:/usr/lib/btbn-ffmpeg:ro
      - /home/pi/src/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1984:1984"
      - "8555:8555"
      - "5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
2023-01-14 11:24:57.336844587  [2023-01-14 11:24:57] frigate.events                 DEBUG   : Event received: update camera_1 1673691872.642107-7mcqa7
2023-01-14 11:25:00.088433290  [2023-01-14 11:25:00] watchdog.steinel               ERROR   : Ffmpeg process crashed unexpectedly for steinel.
2023-01-14 11:25:00.089193411  [2023-01-14 11:25:00] watchdog.steinel               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-01-14 11:25:00.089607740  [2023-01-14 11:25:00] ffmpeg.steinel.detect          ERROR   : Unknown decoder 'hevc_v4l2m2m'
2023-01-14 11:25:00.115485235  [2023-01-14 11:25:00] ffmpeg.steinel.record_rtmp     ERROR   : Unknown decoder 'hevc_v4l2m2m'
2023-01-14 11:25:00.116257782  [2023-01-14 11:25:00] watchdog.steinel               INFO    : Terminating the existing ffmpeg process...
2023-01-14 11:25:00.118653922  [2023-01-14 11:25:00] watchdog.steinel               INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
ffprobe "rtsp://192.168.178.76:554/user=admin&password=xxx&channel=1&stream=1.sdp?real_stream--rtp-caching=500" 
ffprobe version 4.3.5-0+deb11u1+rpt2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt2 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://192.168.178.76:554/user=admin&password=Molch2022&channel=1&stream=1.sdp?real_stream--rtp-caching=500':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 640x360, 12 fps, 12 tbr, 90k tbn, 12 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hevc
