### ISSUE TITLE
[Config Support]: restream and birdseye confusion

### ISSUE THREAD

**Issue by jherby2k** [blakeblackshear/frigate#5118]
### Describe the problem you are having

I have 0.12-beta 3 configured for restream, and need a bit of clarification:

1) If I set
```yaml
restream:
  birdseye: true
  jsmpeg:
    height: 360 (my detect resolution)
```
is there any need to set the birdseye resolution? what does it do, exactly? Its not the jsmpeg resolution, and its not the restream or detect resolution, so what is it for?
```yaml
# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
```

### Version

0.12 beta 3

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
