### ISSUE TITLE
[Support]: Painless upgrade from HA 3.0.0/.011 to 4.1/.012?

### ISSUE THREAD

**Issue by angrycatmeowmeow** [blakeblackshear/frigate#5119]
### Describe the problem you are having

I currently have the HACS integration 3.0.0 and add-on Frigate Beta .011. If I understand correctly they both need to be updated to use .012. What is the most painless method to do this? Download both updates then reboot once, or update the integration then the add-on? I currently have one Reolink wifi doorbell and 5 Reolink E1 zoom cameras using HTTP streams with the args below. I'm not sure how these args will transfer to the new preset method. I followed the link on the [FFMPEG docs](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/ffmpeg_presets/) to see the difference in the presets and my current args, but it took me to a [broken page](https://github.com/blakeblackshear/frigate/blob/master/frigate/ffmpeg_presets.py).

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
rtmp:
  enabled: false
cameras:
  # Name of your camera
  Doorbell:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: http://192.168.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password
          roles:
            - detect
        - path: http://192.168.xxx.xxx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password
          roles:
            - record
    record:
      enabled: True
      events:
        retain:
          default: 2
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - bird
```

### Relevant log output

```shell
none, it's currently working well
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Doorbell/E1 Zoom
