### ISSUE TITLE
[Config Support]: go2rtc example doesn't work for me

### ISSUE THREAD

**Issue by jherby2k** [blakeblackshear/frigate#5137]
### Describe the problem you are having

If I follow the beta 4 instructions here, go2rtc crashes with an exit code 1. This was "fixed" in beta 3 by setting 

```yaml
restream:
  force_audio: false
```

so I took a look at the beta 3 code and made the changes you can see below. Just curious a) why using ffmpeg: doesn't work, and b) if maybe this should be in the docs.

My camera streams appear to be h264 video and a-law. Don't really care about the audio so this config works for me.

side note: what does input_args: preset-rtsp-restream actually do? I see no difference if i exclude it.

### Version

0.12 beta 4

### Frigate config file

```yaml
# not working:

go2rtc:
  streams:
    driveway:       ffmpeg:rtsp://192.168.2.206:80/ch0_0.264#video=copy#audio=aac#audio=opus
    driveway_sub:   ffmpeg:rtsp://192.168.2.206:80/ch0_1.264#video=copy#audio=aac#audio=opus

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect

# working:

go2rtc:
  streams:
    driveway:       rtsp://192.168.2.206:80/ch0_0.264
    driveway_sub:   rtsp://192.168.2.206:80/ch0_1.264

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

# working:

go2rtc:
  streams:
    driveway:       rtsp://192.168.2.206:80/ch0_0.264
    driveway_sub:   rtsp://192.168.2.206:80/ch0_1.264

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant log output

```shell
2023-01-17 15:52:33.880280311  15:52:33.880 INF go2rtc version 0.1-rc.9 linux/arm64
2023-01-17 15:52:33.881737818  15:52:33.881 INF [api] listen addr=:1984
2023-01-17 15:52:33.882309832  15:52:33.882 INF [rtsp] listen addr=:8554
2023-01-17 15:52:33.883972912  15:52:33.883 INF [webrtc] listen addr=:8555
2023-01-17 15:52:33.884571815  15:52:33.884 INF [srtp] listen addr=:8443
2023-01-17 15:52:42.540168944  15:52:42.539 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:rtsp://192.168.2.206:80/ch0_0.264#video=copy#audio=aac#audio=opus
2023-01-17 15:52:42.652206719  15:52:42.651 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:rtsp://192.168.2.206:80/ch0_1.264#video=copy#audio=aac#audio=opus
2023-01-17 15:52:43.000135656  15:52:42.998 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:rtsp://192.168.2.206:80/ch0_0.264#video=copy#audio=aac#audio=opus
2023-01-17 15:52:43.000149063  15:52:42.999 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=driveway
2023-01-17 15:52:43.080599825  15:52:43.079 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:rtsp://192.168.2.206:80/ch0_1.264#video=copy#audio=aac#audio=opus
2023-01-17 15:52:43.080620806  15:52:43.079 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=driveway_sub
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
1. our docs are being updated to fix this as a recommendation, you should do this instead

```yaml
go2rtc:
  streams:
    driveway:
      - rtsp://192.168.2.206:80/ch0_0.264
      - ffmpeg:driveway#audio=opus
    driveway_sub:   
      - rtsp://192.168.2.206:80/ch0_1.264
      - ffmpeg:driveway_sub#audio=opus
```

> side note: what does input_args: preset-rtsp-restream actually do? I see no difference if i exclude it.

go2rtc returns a much more stable stream compared to the camera. Without these input args your recordings will likely have stuttering and hitching due to the default input args

**Comment by jherby2k** [comment]
rtsp://192.168.1.2:8554/back_door for example

**Comment by NickM-27** [comment]
right, but that stream has multile audio tracks and go2rtc will pick one. If you want it to use opus then you need to use `rtsp://192.168.1.2:8554/back_door?video=copy&audio=opus`

**Comment by NickM-27** [comment]
okay, can you go to `http://ha_ip:5000/live/webrtc` and click the info button for that camera and paste the output here

**Comment by NickM-27** [comment]
thanks, and can you show the same thing when using `rtsp://192.168.1.2:8554/driveway?video=copy&audio=opus` ?

**Comment by jherby2k** [comment]
```json
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.2.206:80/ch0_0.264",
      "remote_addr": "192.168.2.206:80",
      "user_agent": "go2rtc/0.1-rc.9",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 8 PCMA/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1",
        "8 PCMA/8000, sinks=0"
      ],
      "recv": 14997560
    },
    {
      "url": "ffmpeg:driveway#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://192.168.1.2:8554/driveway?video=copy\u0026audio=opus",
      "remote_addr": "192.168.1.94:31123",
      "user_agent": "LibVLC/3.0.17.4 (LIVE555 Streaming Media v2016.11.28)",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 0 OPUS/0"
      ],
      "tracks": [
        "96 H264/90000, sinks=1"
      ],
      "recv": 624,
      "send": 16411828
    }
  ]
}
```

**Comment by NickM-27** [comment]
so it is working as it should just sending no opus audio, might be an issue with ffmpeg trying to transcode to opus, maybe file a bug with go2rtc

**Comment by jherby2k** [comment]
OK i can do that, as long as you're seeing the correct behavior. Does the same thing with AAC.

**Comment by NickM-27** [comment]
I think that would explain why using `ffmpeg:` only also has problems, because the process exits with code 1 for some reason

**Comment by jherby2k** [comment]
QQ: any way to set the log level for go2rtc? I tried adding:

```yaml
go2rtc:
  log:
    exec: trace
```

but its not working. go2rtc can't investigate without some better logs

**Comment by NickM-27** [comment]
Set it like this:

```
go2rtc:
  log:
    format: text
    exec: trace
```
