### ISSUE TITLE
[Config Support]: Reolink Camera - not restreaming via go2rtc

### ISSUE THREAD

**Issue by mjalindahl** [blakeblackshear/frigate#5144]
### Describe the problem you are having

I have 2 Reolink cameras that no longer restream via the new go2rtc in beta4.  All of my other cameras do, successfully.

In order to get the Reolink camera working originally, I was doing the custom input_args, but now I'm just using `input_args: preset-http-reolink` and frigate is able to see the stream successfully, I just can't seem to connect to the stream via BlueIris.  All other cams are successfully connecting to the `rtsp://ip.ad.dr.ess:8554/(camera)_cam?video=copy` URL.

Is this somehow a limitation in go2rtc with the Reolink stream?  Is there something I need to change in the `output_args` or is that not even relevant?  One Reolink camera uses the rtmp stream, and one uses the http/flv stream.  Neither are working.

Thanks!

### Version

0.12.0-19afb03

### Frigate config file

```yaml
ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: preset-rtsp-generic

go2rtc:
  streams:
    gates_cam: ffmpeg:rtsp://admin:admin@192.168.21.96:554/11
    alpr_cam: ffmpeg:http://192.168.20.247/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
    chickens_cam: ffmpeg:rtmp://192.168.21.26:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=password

cameras:
  frigate_gates: #<-- generic rtsp, works
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gates_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
  frigate_alpr: #<-- reolink, doesn't work
    ffmpeg:
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/alpr_cam?video=copy
          # input_args: preset-rtsp-restream
          roles:
            - record
            - detect
  frigate_chickens: #<-- reolink, doesn't work
    ffmpeg:
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic
      inputs:
        - path: rtsp://127.0.0.1:8554/chickens_cam?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```

### Relevant log output

```shell
nothing shows up in the logs regarding this
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
[as is shown in the docs](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/ffmpeg_presets#input-args-presets) you should not be using `preset-http-reolink` with the rtsp stream. In that case you should be using `preset-rtsp-restream`

**Comment by NickM-27** [comment]
and there will definitely be logs that show up, in both the frigate and the go2rtc logs.

I am using this with reolink cams without issue.

**Comment by mjalindahl** [comment]
I changed the `input_args` to `preset-rtsp-restream`, with no change.

I'd like to mention again, though, it seems as though Frigate is able to consume the go2rtc restreams just fine.  BlueIris, however, is not.  BlueIris connects to all other cameras' `rtsp://ip.ad.dr.ess:8554/(camera)_cam?video=copy` URLs just fine, just not these Reolink cameras.  And this worked prior to the beta4 upgrade.

I tried finding the go2rtc logs, but was unable to.  Is there a specific location with Unraid/Docker?

Thanks!

**Comment by NickM-27** [comment]
> I changed the input_args to preset-rtsp-restream, with no change.

in any case that is what it needs to be

> I tried finding the go2rtc logs, but was unable to. Is there a specific location with Unraid/Docker?

the location is the same for all installs, just go to the frigate webui, click logs, and then select go2rtc in the top right

**Comment by mjalindahl** [comment]
Oh duh, I forgot about the logs section of 12.

This is my entire go2rtc log:

`2023-01-17 14:42:40.519761590  22:42:40.519 INF go2rtc version 0.1-rc.9 linux/amd64
2023-01-17 14:42:40.520222492  22:42:40.520 INF [api] listen addr=:1984
2023-01-17 14:42:40.520367484  22:42:40.520 INF [rtsp] listen addr=:8554
2023-01-17 14:42:40.520866921  22:42:40.520 INF [webrtc] listen addr=:8555
2023-01-17 14:42:40.521020844  22:42:40.520 INF [srtp] listen addr=:8443`



The frigate log shows no errors either:

`2023-01-17 14:42:44.757205462  [2023-01-17 14:42:44] frigate.app                    INFO    : Starting Frigate (0.12.0-19afb03)
2023-01-17 14:42:44.892222966  [2023-01-17 14:42:44] peewee_migrate                 INFO    : Starting migrations
2023-01-17 14:42:44.913832013  [2023-01-17 14:42:44] peewee_migrate                 INFO    : There is nothing to migrate
2023-01-17 14:42:44.920445379  [2023-01-17 14:42:44] ws4py                          INFO    : Using epoll
2023-01-17 14:42:44.950353958  [2023-01-17 14:42:44] detector.coral                 INFO    : Starting detection process: 1217
2023-01-17 14:42:44.952457026  [2023-01-17 14:42:44] frigate.app                    INFO    : Output process started: 1219
2023-01-17 14:42:44.955930075  [2023-01-17 14:42:44] ws4py                          INFO    : Using epoll
2023-01-17 14:42:44.959851221  [2023-01-17 14:42:44] frigate.app                    INFO    : Camera processor started for frigate_gates: 1223
2023-01-17 14:42:44.965915465  [2023-01-17 14:42:44] frigate.app                    INFO    : Camera processor started for frigate_poolhouse: 1225
2023-01-17 14:42:44.972497838  [2023-01-17 14:42:44] frigate.app                    INFO    : Camera processor started for frigate_driveway: 1226
2023-01-17 14:42:44.979813101  [2023-01-17 14:42:44] frigate.app                    INFO    : Camera processor started for frigate_frontpatio: 1227
2023-01-17 14:42:44.988369311  [2023-01-17 14:42:44] frigate.app                    INFO    : Camera processor started for frigate_alpr: 1228
2023-01-17 14:42:44.995906020  [2023-01-17 14:42:44] frigate.app                    INFO    : Camera processor started for frigate_backdoor: 1230
2023-01-17 14:42:44.997698288  [2023-01-17 14:42:44] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-01-17 14:42:47.634825128  [2023-01-17 14:42:45] frigate.app                    INFO    : Camera processor started for frigate_sidedoor: 1234
2023-01-17 14:42:47.635012363  [2023-01-17 14:42:45] frigate.app                    INFO    : Camera processor started for frigate_bedroomdoor: 1236
2023-01-17 14:42:47.635162698  [2023-01-17 14:42:45] frigate.app                    INFO    : Camera processor started for frigate_horses: 1238
2023-01-17 14:42:47.635308675  [2023-01-17 14:42:45] frigate.app                    INFO    : Camera processor started for frigate_chickens: 1239
2023-01-17 14:42:47.635490500  [2023-01-17 14:42:45] frigate.app                    INFO    : Camera processor started for frigate_frontsidewalk: 1241
2023-01-17 14:42:47.635634688  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_gates: 1242
2023-01-17 14:42:47.635777188  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_poolhouse: 1246
2023-01-17 14:42:47.635911651  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_driveway: 1250
2023-01-17 14:42:47.636046128  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_frontpatio: 1255
2023-01-17 14:42:47.636179166  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_alpr: 1261
2023-01-17 14:42:47.636317848  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_backdoor: 1269
2023-01-17 14:42:47.636451015  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_sidedoor: 1276
2023-01-17 14:42:47.636582065  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_bedroomdoor: 1284
2023-01-17 14:42:47.636668091  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_horses: 1293
2023-01-17 14:42:47.636754456  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_chickens: 1299
2023-01-17 14:42:47.636849334  [2023-01-17 14:42:45] frigate.app                    INFO    : Capture process started for frigate_frontsidewalk: 1308
2023-01-17 14:42:47.636951426  [2023-01-17 14:42:45] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46938]
2023-01-17 14:42:47.648136813  [2023-01-17 14:42:47] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found`

To Frigate itself, everything seems to be working correctly.

**Comment by NickM-27** [comment]
Please show your unraid docker CLI run command

**Comment by NickM-27** [comment]
Also maybe try including audio as well `rtsp://ip.ad.dr.ess:8554/(camera)_cam?video=copy&audio=copy`

**Comment by mjalindahl** [comment]
Tried the `&audio=copy` to no avail.

Here's the docker run:

```/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Frigate' --net='bridge' --cpuset-cpus='8,9,10,11,12,13,14,15,24,25,26,27,28,29,30,31' --privileged=true -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="Frigate" -e 'FRIGATE_RTSP_PASSWORD'='enterpassword' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:5000]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png' -p '5000:5000/tcp' -p '1935:1935/tcp' -p '8554:8554/tcp' -v '/mnt/user/appdata/frigate':'/config':'rw' -v '/mnt/user/Media/frigate':'/media/frigate':'rw' -v '/tmp/frigate':'/tmp/cache':'rw' -v '/etc/localtime':'/etc/localtime':'rw' --device='/dev/bus/usb' --device='/dev/dri/renderD128' --shm-size=5G --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:0.12.0-beta4'

b2551a8578f017f1558599c69b894be50afb0d5624d2c730589b41346a13db06```

**Comment by NickM-27** [comment]
okay, what do blue iris logs show when trying to consume the stream?

**Comment by mrplow** [comment]
Just in case this helps, even though I'm using http instead of rtsp with my reolinks
I had no audio in go2rtc until I added #audio-opus to the end of it's url, even though ffprobe says it's outputting aac

http://192.168.1.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[redacted]&password=[redacted]#video=copy#audio=copy#audio=opus

Also, I wasn't exactly sure where to put input_args: preset-http-reolink for go2rtc, so I put it in it's main block - which works fine for me since I'm using that preset for all my cameras

<details><summary>full config.yml</summary><p>

```
mqtt:
  host: 192.168.1.10
  user: mrplow
  password: [redacted]

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: preset-record-generic-audio-copy

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True

go2rtc:
  input_args: preset-http-reolink
  streams:
    frontdoor: ffmpeg:http://192.168.1.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[redacted]&password=[redacted]#video=copy#audio=copy#audio=opus
    duoleft: ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[redacted]&password=[redacted]#video=copy#audio=copy#audio=opus
    duoright: ffmpeg:http://192.168.1.151/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=[redacted]&password=[redacted]#video=copy#audio=copy#audio=opus

cameras:

  frontdoor:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    timestamp_style:
      position: "tl"
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      filters:
       car:
         mask:
          - 756,196,1086,476,1280,446,1280,236,959,0,731,0
    motion:
      mask:
        - 934,0,960,0,964,66,914,60
        - 1280,342,1280,566,1202,504

  duoleft:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    timestamp_style:
      position: "br"
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/duoleft
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1280
      height: 720
      fps: 15

  duoright:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    timestamp_style:
      position: "bl"
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/duoright
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
       width: 1280
       height: 720
       fps: 15
    objects:
      filters:
        car:
          mask:
            - 1280,720,1280,450,1000,450,1000,720

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /trt-models/yolov4-416.trt
  labelmap_path: /trt-models/coco_91cl.txt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        dog: 7
        cat: 7
        car: 7

objects:
  track:
    - bear
    - bird
    - car
    - cat
    - dog
    - person

birdseye:
  enabled: True
  mode: continuous

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"
  effect: shadow
```
</p></details>
