### ISSUE TITLE
[Support]: fatal - supervisor died

### ISSUE THREAD

**Issue by user897943** [blakeblackshear/frigate#5148]
### Describe the problem you are having

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/prepare-logs.sh
cont-init: info: /etc/cont-init.d/prepare-logs.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun frigate (no readiness notification)
services-up: info: copying legacy longrun go2rtc (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 25, in <module>
    if not go2rtc_config.get("log", {}).get("format"):
AttributeError: 'NoneType' object has no attribute 'get'
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Version

12b4

### Frigate config file

```yaml
####################################
########## FRIGATE CONFIG ##########

#mqtt:
#  host: xx
#  port: 1883
#  topic_prefix: frigate
#  client_id: frigate
#  stats_interval: 60

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ui:
  live_mode: webrtc
  timezone: Europe/London
  use_experimental: true

logger:
  default: info
  logs:
    frigate.event: debug

database:
  path: /db/frigate.db

birdseye:
  enabled: True
  restream: False
  width: 1024
  height: 760
    # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  mode: continuous

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: preset-rtsp-generic
#-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
#-f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
#-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

go2rtc:

detect:
  width: 2048
  height: 1520
  fps: 5
  enabled: false
  max_disappeared: 25

record:
  enabled: True
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 30

snapshots:
  enabled: False
  timestamp: true
  bounding_box: False
  crop: False
  retain:
    default: 7

rtmp:
  enabled: False

#live:
#  height: 972
#  quality: 8

timestamp_style:
    # "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
    # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
    #           Additional Examples:
    #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
    # None (No effect),
    # "solid" (solid background in inverse color of font)
    # "shadow" (shadow for font)
  effect: shadow

###################################
########## CAMERA CONFIG ##########

cameras:
  frigate_street_front:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx/cam2_ch1
          roles:
            - record
    detect:
      enabled: False

  frigate_street_nw:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx/cam3_ch1
          roles:
            - record
    detect:
      enabled: False

  frigate_street_se:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx/cam1_ch1
          roles:
            - record
    detect:
      enabled: False

  frigate_backyard:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxx/cam4_ch1
          roles:
            - record
    detect:
      enabled: False
```
```


### Relevant log output

```shell
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/prepare-logs.sh
cont-init: info: /etc/cont-init.d/prepare-logs.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun frigate (no readiness notification)
services-up: info: copying legacy longrun go2rtc (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 25, in <module>
    if not go2rtc_config.get("log", {}).get("format"):
AttributeError: 'NoneType' object has no attribute 'get'
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
```


### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
Can't access UI
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Anpviz 5MP ZOOM

### Any other information that may be helpful

See above, thanks.
