### ISSUE TITLE
Environment Variable refactor using scalars

### ISSUE THREAD

**Issue by onedr0p** [blakeblackshear/frigate#5157]
**Describe what you are trying to accomplish and why in non technical terms**

Hi 👋🏼 it would be nice if the configuration file could read env vars like home assistant, it has a [pretty neat way](https://www.home-assistant.io/docs/configuration/yaml/#environment-variables) for this to work. I know there's a current way it's handled but it's pretty confusing and the below example would be much easier to follow as it would be no different than home assistant.

**Describe the solution you'd like**

frigate compose:

```yaml
frigate:
  image: frigate
  container_name: frigate
  restart: unless-stopped
  env:
    MQTT_USER: frigate
    MQTT_PASSWORD: abc123
  volumes:
    - ./frigate.yaml:/config/config.yaml:ro
```

frigate config:

```yaml
mqtt:
  host: emqx.default.svc.cluster.local
  topic_prefix: frigate
  user: !env_var MQTT_USER
  password: !env_var MQTT_PASSWORD
```

**Additional context**

This feature is pretty handy when using an orchestration platform like Kubernetes where you can use secrets as environment variables. This method allows you to map any environment variable to any configuration file option.

**Comment by NickM-27** [comment]
to be honest I don't really see what the difference is between how it is now, except that right now the variable needs to start with `FRIGATE_` and you just use `{}` instead of `!env_var`

another problem is users like to just have an env var for a password so it can be `rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_BACKYARD_PW}@0.0.0.0...` which would not work with this proposed format

**Comment by NickM-27** [comment]
right now you can just do

```yaml
frigate:
  image: frigate
  container_name: frigate
  restart: unless-stopped
  env:
    FRIGATE_MQTT_USER: frigate
    FRIGATE_MQTT_PASSWORD: abc123
  volumes:
    - ./frigate.yaml:/config/config.yaml:ro

mqtt:
  host: emqx.default.svc.cluster.local
  topic_prefix: frigate
  user: {FRIGATE_MQTT_USER}
  password: {FRIGATE_MQTT_PASSWORD}
```

**Comment by onedr0p** [comment]
I guess my suggestion would be to have the config syntax be closer to the home assistant syntax, and since these are both python projects you might be able to use the same library as them for parsing YAML.

> another problem is it is very common to use an env var for the password so it can be rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_BACKYARD_PW}@0.0.0.0... which would not work with this proposed format

Maybe this is useful? But you can also put the whole thing in an env var, however maybe there's an edge case for waiting to have it the way it is.

```yaml
frigate:
  image: frigate
  container_name: frigate
  restart: unless-stopped
  env:
    FRIGATE_BACKYARD_FEED: "rtsp://admin:blahblah@0.0.0.0..."
  volumes:
    - ./frigate.yaml:/config/config.yaml:ro
```

and then use `camera: !env_var FRIGATE_BACKYARD_FEED` in the config.
