### ISSUE TITLE
[Config Support]: Old configuration vs New configuration - need example for my camera

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5159]
### Describe the problem you are having

I did not understand how to create a new configuration 
I have attached my camera example and would be happy if someone can help me
I'm pretty sure it's going to help a lot of people also

### Version

11

### Frigate config file

```yaml
Garden:
   ffmpeg:
#      hwaccel_args: -------------> we need that ?
#        - -hwaccel
#        - qsv
#        - -qsv_device
#        - /dev/dri/renderD128
#        - -hwaccel_output_format
#        - yuv420p
      input_args:
         - -avoid_negative_ts
         - make_zero
      inputs:
          - path: rtsp://admin:admin@192.168.1.139:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
          - path: rtsp://admin:admin@192.168.1.139:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - record
   detect:
     width: 1280
     height: 720
     fps: 5
   rtmp:
     enabled: false
          
   objects:
     track:
       - person
       - dog
       - cat
     filters:
       person:
         threshold: 0.70
       
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: false
     crop: False
     height: 175
     retain:
       default: 14

   record:
     enabled: true
     retain:
       days: 1
     events:
       pre_capture: 5
       post_capture: 10
       objects:
         - person
         - cat
         - dog
       retain:
         default: 1
   motion:
     mask:
       - 422,0,0,0,0,325
   zones:
     zone_parking:
       coordinates: 796,339,690,189,414,253,220,406
       objects:
         - person
         - dog
         - cat
     zone_storage:
       coordinates: 738,0,1191,0,1258,112,700,201
       objects:
         - person
         - dog
         - cat
```

### Relevant log output

```shell
not have
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
