### ISSUE TITLE
[Support] [Beta]: Beta5 Problem with freezing cameras on camera page and birdseye

### ISSUE THREAD

**Issue by aervig** [blakeblackshear/frigate#5169]
### Describe the problem you are having

I have got a problem with my TP-Link Tapo (C200 and C100) cameras after I upgraded from Beta 3 to Beta 5.

The image on the cameras page only updates when I restart Frigate, and the same with the video stream at birdseye. Birdseye only show a still image from this cameras, and that image are updated when Frigate is restarted.

Livestream webrtc and mse are working, but jsmpeg shows the same frozen image as camera overview and birdseye

I didn't have this issue in Beta 3, and I have also downgraded to v 0.11.1 and everything worked normal again then.

### Version

0.12.0 Beta 5

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 10.0.1.150
  port: 1883
  client_id: frigate
  user: userid
  password: mqttpassword
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: -hide_banner -loglevel warning
  input_args: preset-rtsp-generic
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic-audio
    rtmp: preset-rtmp-generic

logger:
  default: info
  logs:
    frigate.event: debug

birdseye:
  enabled: True
  width: 1920
  height: 1080
  restream: True
  quality: 8
  mode: continuous

detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True

objects:
  track:
    - person
    - dog
    - cat
    - motorcycle
    - bus
    - umbarella
  mask: 357,57,608,61,611,0,352,0

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 7
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
      - dog
      - motorcycle
      - bus
      - umbarella
    retain:
      default: 10
      objects:
        person: 15
snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

go2rtc:
  streams:
    frontdoor:
      - rtsp://userid:password@10.0.3.60:554/stream1
      - ffmpeg:frontdoor#audio=opus
    gate: 
      - rtsp://userid:password@10.0.3.61:554/stream1
      - ffmpeg:gate#audio=opus    
    terasse:
      - rtsp://userid:password@10.0.3.62:554/stream1
      - ffmpeg:terasse#audio=opus
    brasil_gate:
      - rtsp://userid:password@10.0.32.60/cam/realmonitor?channel=1&subtype=00
      - ffmpeg:brasil_gate#audio=opus
    brasil_front:
      - rtsp://userid:password@10.0.32.61:554/stream1
      - ffmpeg:brasil_front#audio=opus
    stue_tv:
      - rtsp://userid:password@10.0.3.63:554/stream1
      - ffmpeg:stue_tv#audio=opus
    stue_kjokken:
      - rtsp://userid:password@10.0.3.64:554/stream1
      - ffmpeg:stue_kjokken#audio=opus
    kontor:
      - rtsp://userid:password@10.0.3.65:554/stream1
      - ffmpeg:kontor#audio=opus
    gang:
      - rtsp://userid:password@10.0.3.66:554/stream1
      - ffmpeg:gang#audio=opus

cameras:

# Kamera Hoveddør Hjemme
  frontdoor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/frontdoor?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera Gate Hjemme

  gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/gate?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera Gang Hjemme
  gang:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/gang?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7


# Kamera Terasse Hjemme
  terasse:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/terasse?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera Kontor Hjemme
  kontor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/kontor?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera Stue/Kjøkken Hjemme
  stue_kjokken:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/stue_kjokken?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera Stue/TV Hjemme
  stue_tv:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/stue_tv?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera front Brasil
  brasil_front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/brasil_front?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7

# Kamera Gate Brasil
  brasil_gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/brasil_gate?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
      events:
        retain:
          default: 7
```

### Relevant log output

```shell
I don't get any error messages in the logfiles
```

### FFprobe output from your camera

```shell
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1080,\n          \"width\": 1920\n        }\n      ]\n    }\n  }\n]"
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

TP-Link Tapo

### Any other information that may be helpful

docker-compose.yaml
```

version: "3.9"
services:

  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta5

    shm_size: "1024mb" 
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/frigate/frigate_config.yml:/config/config.yml
      - /mnt/disk2/storage:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host

    environment:
      FRIGATE_RTSP_PASSWORD: "mypassword"
```

**Comment by NickM-27** [comment]
Please include a full copy of the logs from frigate

**Comment by NickM-27** [comment]
What device are you running on? Is there a reason you don't have hwaccel enabled?

**Comment by aervig** [comment]
> What device are you running on? Is there a reason you don't have hwaccel enabled?

I'm running this on esxi 7, and have not got hwaccel to work there.

I just got the cameras to work now, by changing the camera configuration input_args to preset-rtsp-generic instead of preset-rtsp-restream

```
# Kamera Gate Hjemme

  gate:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/gate?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    record:
      enabled: True
      events:
        retain:
          default: 7   
```
