### ISSUE TITLE
[Support]: Won't boot after Docker update

### ISSUE THREAD

**Issue by KillahB33** [blakeblackshear/frigate#5176]
### Describe the problem you are having

Can't get frigate to boot after updating docker.

### Version

stable

### Frigate config file

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: '1000mb'
    runtime: nvidia
    environment:
      - FRIGATE_RTSP_PASSWORD="password"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/config/frigate/config.yml:/config/config.yml:ro
      - /opt/config/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
```

### Relevant log output

```shell
[+] Running 0/1
 ⠿ Container frigate  Starting                                                                                                                                                                                                       1.0s
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
```

### FFprobe output from your camera

```shell
not camera related
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

na

**Comment by KillahB33** [comment]
Went and updated docker and the error changed slightly

`bryan@ubundock:/opt/compose$ docker compose up -d frigate
[+] Running 0/1
 ⠇ Container frigate  Starting                                                                                                                                                                                                       0.7s
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown`

**Comment by NateMeyer** [comment]
I don't think you need the `runtime: nvidia` in the newer docker versions.  Check the nvidia-container-runtime installation [here](https://docs.docker.com/config/containers/resource_constraints/#gpu)

also I think your deploy section is missing a few lines
```yml
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [gpu]
```
