### ISSUE TITLE
[Camera Support]: Dahua 5MP H264 

### ISSUE THREAD

**Issue by evasilisin1984** [blakeblackshear/frigate#5178]
### Describe the problem you are having

No errors in logs, but camera image frozen.   It has never worked.  It shows the image it saw when you started frigate.   But no live or debug.  However debug shows FPS and that number appears to be live.  

### Version

Latest

### Frigate config file

```yaml
nightvision:
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:Password@192.168.50.157:554/h264/ch1/sub/av_stream 
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:Password@192.168.50.157:554/h264/ch1/main/av_stream
          roles:
            - record
    detect:
      width: 1280
      height: 720 
      fps: 20
    #   stationary:
    #     interval: 10
    objects:
      track:
      - person
      - bottle
      - car
      - wine glass
      - cat
      - dog
      - motorcycle
      - bicycle
      - pizza 
      - cellphone phone
    snapshots:
      enabled: true
      timestamp: true
      retain:
        default: 4
    record:
      enabled: True
      retain:
        days: 1
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 10
        post_capture: 15
```

### Relevant log output

```shell
No issues in log, shows camera started just like the others
```

### FFprobe output from your camera

```shell
FFPROBE command not found lol
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua
