### ISSUE TITLE
[Config Support]: Camera freezing after couple of hours

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5179]
### Describe the problem you are having

On version 0.11 everything working well
The camera freezes after a couple of hours of usage and can continue after 2-3-4 hours as regular
Someone can help with this issue please?
The type of camera if its matters (Arenti - onvif/RTSP)

### Version

0.12

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.230
  user: "mqttuser"
  password: "pass"

detectors:
  coral:
    type: edgetpu
    device: usb   
go2rtc:
  streams:
    LivingRoom:
      - rtsp://admin:admin@192.168.1.103:8554/Streaming/Channels/101
      - ffmpeg:LivingRoom#audio=opus
    LivingRoom_sub:
      - rtsp://admin:admin@192.168.1.103:8554/Streaming/Channels/102
  LivingRoom:
    ffmpeg:
      inputs:
          - path: rtsp://127.0.0.1:8554/LivingRoom_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect        
          - path: rtsp://127.0.0.1:8554/LivingRoom?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: false
           
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.70
        dog:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 500
      retain:
        default: 14 
    record:
     enabled: true
     retain:
       days: 1
     events:

       pre_capture: 5
       post_capture: 10
       objects:
         - person
       retain:
         default: 2
    motion:
      mask:
        - 1221,174,1512,327,1591,99,1316,0,1290,0,1260,0
```

### Relevant log output

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
