### ISSUE TITLE
RTSP unauth but was working [Support]: 

### ISSUE THREAD

**Issue by sezbez** [blakeblackshear/frigate#5202]
### Describe the problem you are having

for some reason I am now getting unauth error. I haven't changed anything as far as i know. 

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xxx
  port: 1883
  user: mqtt
  password: xxxxx
  topic_prefix: frigate
  
database:
 path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

#Global Object Settings
objects:
  track:
    - person
    - dog
  filters:
    person:
      min_area: 20000
      max_area: 200000
      min_score: 0.6
      threshold: 0.6
    dog:
      min_area: 1000
      max_area: 10000
      min_score: 0.1
      threshold: 0.3
cameras:
  Backyard2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@192.168.1.106:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:xxxxxx@192.168.1.106:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 6
    snapshots:
      enabled: True
      required_zones:
        - backyard_lawn
        - backyard
    record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
       retain:
         default: 14
         mode: active_objects
    zones:
      backyard_lawn:
        coordinates: 238,28,300,41,407,83,459,102,507,196,556,190,609,267,478,295,183,300,81,272,130,131,180,26
        objects:
          - dog
          - person
      backyard:
        coordinates: 383,75,439,94,537,142,640,195,640,295,573,339,307,360,0,360,0,0,152,21,283,50
        objects:
          - person
    motion:
      mask: 0,0,640,0,640,194,361,74
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.1.xxx:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:xxxxx@192.168.1.xx:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 6
    snapshots:
      enabled: True
      required_zones:
        - backyard_lawn
        - backyard
    record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
       retain:
         default: 14
         mode: active_objects
    zones:
      backyard_lawn:
        coordinates: 233,170,293,220,391,258,481,283,568,293,522,360,0,360,21,217,169,162,195,139
        objects:
          - dog
          - person
      backyard:
        coordinates: 294,162,438,223,473,41,640,86,522,360,0,360,0,114,50,106,93,111,164,105,310,67
        objects:
          - person
    motion:
      mask: 0,0,595,0,417,58,0,120
  Side:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@192.168.1.100:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:xxxxx@192.168.1.100:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 6
    snapshots:
      enabled: True
      required_zones:
        - side_path
        - side_road
    record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
       retain:
         default: 14
         mode: active_objects
    zones:
      side_path:
        coordinates: 0,192,680,199,680,106,0,102
        objects:
          - dog
          - person
      side_road:
        coordinates: 0,94,680,101,680,0,0,0
        objects:
          - person
  Porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@192.168.1.107:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:xxxxxxx@192.168.1.107:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    snapshots:
      enabled: True
      required_zones:
        - entrance
    record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
       retain:
         default: 14
         mode: active_objects
    zones:
      entrance:
        coordinates: 640,480,604,0,508,0,484,127,329,105,267,146,357,177,450,194,401,264,415,322,348,480
        objects:
          - person
    motion:
      mask: 275,432,384,284,294,202,182,313
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.1.65:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:xxxxxxx@192.168.1.65:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 6
    snapshots:
      enabled: True
      required_zones:
        - front
        - driveway
        - halloween
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
    zones:
      front:
        coordinates: 227,183,640,167,640,0,0,0,0,124,89,124,220,102
        objects:
          - person
          - dog
      driveway:
        coordinates: 640,360,640,190,217,216,217,360
        objects:
          - person
          - dog
  Front_PTZ:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxx@192.168.1.200:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:xxxxxx@192.168.1.200:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 6
    snapshots:
      enabled: True
      required_zones:
        - path
        - road
    record:
     enabled: True
     retain:
       days: 7
       mode: motion
     events:
       retain:
         default: 14
         mode: active_objects
    zones:
      path:
        coordinates: 955,720,1055,213,890,217,823,320,652,504,238,720
        objects:
          - person
          - dog
      road:
        coordinates: 0,720,0,57,572,51,874,142,153,687,30,720
        objects:
          - person
          - cars
    motion:
      mask: 704,452,806,81,858,50,749,49,655,426
```

### Relevant log output

```shell
INFO    : Waiting for ffmpeg to exit gracefully...
[2023-01-23 20:10:02] ffmpeg.Porch.record            ERROR   : [rtsp @ 0x55d03571bd40] method DESCRIBE failed: 401 Unauthorized
[2023-01-23 20:10:02] ffmpeg.Porch.record            ERROR   : rtsp://admin:xxxxx@192.168.1.107:554/Streaming/Channels/101: Server returned 401 Unauthorized (authorization failed)
[2023-01-23 20:10:02] watchdog.Porch                 INFO    : Terminating the existing ffmpeg process...
[2023-01-23 20:10:02] watchdog.Porch                 INFO    : Waiting for ffmpeg to exit gracefully...
```

### FFprobe output from your camera

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision DS-2CD2555FWD-IS
