### ISSUE TITLE
[Config Support]: Cant see playback (events) -The media could not be loaded -Error

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5207]
### Describe the problem you are having

I can't see any playback
When going to events I see the snapshot and want to play some, I get a black screen and "The media could not be loaded"

### Version

0.12 beta5

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.230
  user: "mqttuser"
  password: "pass"

detectors:
  coral:
    type: edgetpu
    device: usb   
    
cameras:
 GardenOne:
   ffmpeg:
      input_args:
         - -avoid_negative_ts
         - make_zero
         - -fflags
         - nobuffer+genpts+discardcorrupt
         - -flags
         - low_delay
         - -strict
         - experimental
         - -analyzeduration
         - 1000M
         - -probesize
         - 1000M
         - -rw_timeout
         - "5000000"
      inputs:
          - path: http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=admin
            roles:
              - record
              - rtmp
          - path: http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=admin
            roles:
              - detect
   detect:
     width: 1920
     height: 1080
     fps: 5
   rtmp:
     enabled: false
          
   objects:
     track:
       - person
       - dog
       - cat
     filters:
       person:
         threshold: 0.70
       
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: false
     crop: False
     height: 500
     retain:
       default: 14

   record:
     enabled: true
     retain:
       days: 1
     events:
       pre_capture: 5
       post_capture: 10
       objects:
         - person
         - cat
         - dog
       retain:
         default: 1

 LivingRoom:
   ffmpeg:
      inputs:
          - path: rtsp://admin:admin@192.168.1.103:8554/Streaming/Channels/101
            roles:
              - detect
          - path: rtsp://admin:admin@192.168.1.103:8554/Streaming/Channels/102
            roles:
              - record
   detect:
     width: 1920
     height: 1080
     fps: 5
   rtmp:
     enabled: false
          
   objects:
     track:
       - person
       - dog
     filters:
       person:
         threshold: 0.70
       dog:
         threshold: 0.70
       
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: false
     crop: False
     height: 500
     retain:
       default: 14

   record:
     enabled: true
     retain:
       days: 1
     events:
       pre_capture: 5
       post_capture: 10
       objects:
         - person
       retain:
         default: 2
   motion:
     mask:
       - 1221,174,1512,327,1591,99,1316,0,1290,0,1260,0

 Entrance:
   ffmpeg:
      input_args:
         - -avoid_negative_ts
         - make_zero
      inputs:
          - path: rtsp://admin:admin@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
          - path: rtsp://admin:admin@192.168.1.127:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - record
   detect:
     width: 1280
     height: 720
     fps: 5
   rtmp:
     enabled: false
          
   objects:
     track:
       - person
       - dog
       - cat
     filters:
       person:
         threshold: 0.70
       
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: false
     crop: False
     height: 175
     retain:
       default: 14

   record:
     enabled: true
     retain:
       days: 2
     events:
       pre_capture: 30
       post_capture: 50
       objects:
         - person
         - cat
         - dog
       retain:
         default: 1
   motion:
     mask:
       - 1280,0,1280,327,961,0
```

### Relevant log output

```shell
Entrance:

[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "25/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 720, "width": 1280 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "30/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 480, "width": 704 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]

GardenOne:

FFPROBE OUTPUT
[ { "return_code": 0, "stderr": {}, "stdout": {} }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "14/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 512, "width": 896 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]

LivingRoom:
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1080, "width": 1920 }, { "avg_frame_rate": "0/0", "bit_rate": "64000", "codec_long_name": "PCM mu-law / G.711 mu-law" } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 360, "width": 640 }, { "avg_frame_rate": "0/0", "bit_rate": "64000", "codec_long_name": "PCM mu-law / G.711 mu-law" } ] } } ]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
