### ISSUE TITLE
[Support]: Some event times are wrong and out of order

### ISSUE THREAD

**Issue by chris-thorn** [blakeblackshear/frigate#5214]
### Describe the problem you are having

I was reviewing events for one of my cameras and I noticed that one of the events seemed to be shown in the wrong order. I then looked through the list a bit more and found several instances of events that show one time in Frigate, but a different time on the camera timestamp (which I've checked is correct to within about 30 seconds for all cameras).

As an example, here is my partner leaving the house at 06:30 this morning. It then shows me getting into the car at 06:31, and it then shows my partner returning at 07:01.

![image](https://user-images.githubusercontent.com/3541291/214083648-dd251e1e-debc-4224-a9b1-774a7e78a897.png)

The two events of my partner leaving and returning are correct, but I didn't get into the car until 07:24.

![image](https://user-images.githubusercontent.com/3541291/214083675-154e295b-5d66-4410-8292-76c2cdfed75e.png)

As I said, there are a few instances of this, but I can't see a clear relationship (e.g. +/-30 min) between the time shown in Frigate and the time recorded by the camera.

**Additionally**, the dates shown in the Frigate event list are all in US format (m/d/Y) - is there any way to change this to Y-m-d? I have mounted /etc/localtime as read-only in the Docker container.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.20
  port: 1883
  user: <username>
  password: <password>

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

detect:
  fps: 10
  stationary:
    interval: 0
    threshold: 50

objects:
  track:
    - person
    - cat
    - car
    - bicycle
    - motorcycle
    - dog

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.48/user=<username>_password=<password>_channel=1_stream=0.sdp?real_stream
          roles:
            - record
        - path: rtsp://192.168.0.48/user=<username>_password=<password>_channel=1_stream=1.sdp?real_stream
          roles:
            - rtmp
            - detect
    zones:
      road:
        coordinates: 307,417,1060,444,895,253,751,158,750,123,260,142,219,209,326,302
        objects:
          - car
          - bicycle
          - motorcycle
      entire_driveway:
        coordinates: 1280,159,954,147,816,161,589,160,577,95,229,153,232,218,318,287,284,379,0,418,0,720,1280,720
        objects:
          - person
          - cat
          - dog
  garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.49/user=<username>_password=<password>_channel=1_stream=0.sdp?real_stream
          roles:
            - record
        - path: rtsp://192.168.0.49/user=<username>_password=<password>_channel=1_stream=1.sdp?real_stream
          roles:
            - rtmp
            - detect
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.44/user=<username>_password=<password>_channel=1_stream=0.sdp?real_stream
          roles:
            - record
        - path: rtsp://192.168.0.44/user=<username>_password=<password>_channel=1_stream=1.sdp?real_stream
          roles:
            - rtmp
            - detect
  catcam:
    ffmpeg:
      inputs:
        - path: rtsp://<username>:<password>@192.168.0.45/stream1
          roles:
            - record
        - path: rtsp://<username>:<password>@192.168.0.45/stream2
          roles:
            - rtmp
            - detect
```

### Relevant log output

```shell
I can't see any logs for the relevant time period
```

### FFprobe output from your camera

```shell
chris@nvr-1 ~ $ ffprobe rtsp://192.168.0.48/user=<username>_password=<password>_channel=1_stream=1.sdp?real_stream
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://192.168.0.48/user=<username>_password=<password>_channel=1_stream=1.sdp?real_stream':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.500000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 704x576, 2 fps, 2 tbr, 90k tbn, 180k tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Besder

### Any other information that may be helpful

**docker-compose.yml**

```yaml
version: "3.9"

###############################################################################

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/dri/renderD128
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml:ro
      - ./db:/db
      - /mnt/cameras/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 536870912
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "frigate"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "6"
```
