### ISSUE TITLE
go2rtc `exec` issue with env vars substitutions

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#5218]
### Describe the problem you are having

I have a stream like:

```yaml
go2rtc:
  streams:
    test_cam:
      - exec:ffmpeg -hide_banner -v error -allowed_media_types video -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i rtsp://admin:1234@192.168.1.12:554/Streaming/Channels/101 -vf hqdn3d -c:v copy -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}
```

Notice the `{output}` on it.

Frigate container initialization fails with:

```
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 62, in <module>
    go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
KeyError: 'output'
```
