### ISSUE TITLE
[Config Support]: Force MSE to use h264 stream

### ISSUE THREAD

**Issue by LckySndays** [blakeblackshear/frigate#5222]
### Describe the problem you are having

I am not sure whether it is intentional or bug
If i use this stream path the MSE player will not loading up in browser that don't support h265 as expected
```yaml
path: rtsp://127.0.0.1:8554/TestCam1?video=h265 (Camera FFProbe h265 2560x1440)
path: rtsp://127.0.0.1:8554/TestCam1 (Camera FFProbe h265 2560x1440)
```
But If I change the stream path to this one
```yaml
path: rtsp://127.0.0.1:8554/TestCam1?video=h264 (Camera FFProbe h264 1280x720)
```
The System Camera FFProbe output listed as h264 1280x720 which should be playing alright with the browser that support h264. But mine was failed to load the video/audio like it would play it with h265 (I'm not sure how to check it)

Is there any way to check or set the MSE player to use the h264?
Btw with the configuration below the WebRTC will play it with h264 no matter if I set ```?video=h264``` or ```?video=h265```

### Version

v0.12.0-beta5

### Frigate config file

```yaml
mqtt:
  enabled: False
  
birdseye:
  enabled: False
  
detect:
  enabled: False

go2rtc:
  streams:
    TestCam1:
      - rtsp://user:pass@192.168.1.199/Streaming/Channels/101 (h265 2560x1440)
      - ffmpeg:TestCam1#video=h264#width=1280#audio=opus (h264 1280x720)
  webrtc:
    candidates:
      - 192.168.1.109:8555
      - stun:8555
  log:
    level: trace
      
cameras:
  TestCam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/TestCam1?video=h264 (Camera FFProbe h264 1280x720)
          roles:
            - restream
          hwaccel_args: preset-nvidia-h264
          input_args: preset-rtsp-restream
```

### Relevant log output

```shell
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"25/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 720,\n          \"width\": 1280\n        }\n      ]\n    }\n  }\n]"
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
MSE supports h265 so it will be used. WebRTC only supports h264 so that's all that will be used.

If you want a specific stream for the frontend you should create another entry in go2rtc that points to it

```

go2rtc:
  streams:
    TestCam1:
      - rtsp://user:pass@192.168.1.199/Streaming/Channels/101 (h265 2560x1440)
      - ffmpeg:TestCam1#video=h264#width=1280#audio=opus (h264 1280x720)
    TestCam1Live: TestCam1?video=h264&audio=aac
  webrtc:
    candidates:
      - 192.168.1.109:8555
      - stun:8555
  log:
    level: trace
```

And then set `live -> stream_name` as TestCam1Live for that camera in the frigate cameras config.

**Comment by LckySndays** [comment]
Same result, it seems not working

```yaml
mqtt:
  enabled: False
  
birdseye:
  enabled: False
  
detect:
  enabled: False

go2rtc:
  streams:
    TestCam1:
      - rtsp://user:pass@192.168.1.199/Streaming/Channels/101
      - ffmpeg:TestCam1#video=h264#width=1280#audio=opus
    TestCam1Live: TestCam1?video=h264&audio=aac
  webrtc:
    candidates:
      - 192.168.1.109:8555
      - stun:8555
  log:
    level: trace
      
cameras:
  TestCam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/TestCam1?video=h264
          roles:
            - restream
          hwaccel_args: preset-nvidia-h264
          input_args: preset-rtsp-restream
    live:
      stream_name: TestCam1Live
```

I found this go2rtc trace error log that might be related
```
2023-01-25 09:28:41.529357715  01:28:41.529 TRC [streams] consumer=0 candidate=1 media="audio, recvonly, 0 MPEG4-GENERIC/0"
2023-01-25 09:28:41.529359370  01:28:41.529 DBG [streams] probe producer url=TestCam1?video=h264&audio=aac
2023-01-25 09:28:41.529367415  01:28:41.529 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="unsupported scheme: TestCam1?video=h264&audio=aac" url=TestCam1?video=h264&audio=aac
```

The ffmpeg libopus I think causing this error
```
2023-01-25 09:28:38.529908572  [libopus @ 0x55e7927d07c0] Queue input is backward in time
2023-01-25 09:28:38.530161531  [rtsp @ 0x55e7927c9fc0] Non-monotonous DTS in output stream 0:1; previous: 56664, current: 56472; changing to 56665. This may result in incorrect timestamps in the output file.
```

With ```#width=1280``` it produce this go2rtc error log
```
2023-01-25 09:35:50.302773539  [swscaler @ 0x555ccf6bb3c0] [swscaler @ 0x555ccf6cadc0] deprecated pixel format used, make sure you did set range correctly
```
