### ISSUE TITLE
 0.12.0 Beta 5 - webrtc - No sound + issue with doorbell

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#5223]
### Describe the problem you are having

Frigate running on Docker .
Frigate using go2rtc rtsp stream (also go2rtc run on docker).

Upgrade to  0.12.0 Beta 5 ,

No sound on webrtc live view with MSE audio is working.
Following RN I tried below with no success:

adding live 
```
  front:

    live:
      stream_name: front
    birdseye:
      mode: objects  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy    
      global_args: -hide_banner -loglevel warning
      hwaccel_args: preset-vaapi
      inputs:
         - path: rtsp://192.168.1.113:8554/front_go2rtc
           roles:
            - record
            - detect 
....
```
Also tried transcoding:

```
go2rtc:
   streams:
     front: # <- for RTSP streams
       - rtsp://192.168.1.113:8554/front_go2rtc # <- stream which supports video & aac audio
       - ffmpeg:front#audio=opus # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)

  front:

    birdseye:
      mode: objects  
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy    
      global_args: -hide_banner -loglevel warning
      hwaccel_args: preset-vaapi
      inputs:
         - path: rtsp://192.168.1.113:8554/front_go2rtc
           roles:
            - record
            - detect 
....
```

second issue ,on doorbell liveview - no video or audio for both mse and webrtc - same config as above.
+  ffprobe output below

### Version

 0.12.0 Beta 5 

### Frigate config file

```yaml
mention in post
```

### Relevant log output

```shell
no error
```

### FFprobe output from your camera

```shell
front camera(no sound on webrtc) ffprobe output

[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "25/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "display_aspect_ratio": "3:2", "height": 1080, "width": 1920 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]
```

ffprobe for doorbell(no sound/video for mse/webrtc):

```
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 720, "width": 1280 } ] } } ]
```
```


### Frigate stats

_No response_

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua 

### Any other information that may be helpful

_No response_
