### ISSUE TITLE
[Config Support]: problem with time

### ISSUE THREAD

**Issue by Pinez83** [blakeblackshear/frigate#5228]
Good morning everyone,
I'm using Frigate installed in a dedicated LXC container su Proxmox with Portainer. 
The "clips" and "recordings" folders are mounted on an external Nas, and work correctly. I also use a Coral USB, and fortunately it works perfectly too.
My current configuration has 3 cameras, everything works but I have e small problem that I would like to solve.
The timestamp (visible on "debug") and nomenclature time is wrong, being one hour behind. I think it's a timezone problem, since mine is UTC+1;

Sorry for my english.
Thanks to whoever wants to help me.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xx
  user: xxx
  password: xxx
  topic_prefix: frigate
  client_id: frigate

cameras:
  Ingresso:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - detect
        - path: xxx
          roles:
            - record
      hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: false
    detect:
      width: 480
      height: 272
      fps: 7
    motion:
      mask:
        - 265,87,311,92,319,55,269,51
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      bounding_box: true
  Garage:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - detect
        - path: xxx
          roles:
            - record
      hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: false
    detect:
      width: 640
      height: 480
      fps: 15
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
        - car
    snapshots:
      enabled: true
      bounding_box: true
    Sala:
    ffmpeg:
      inputs:
        - path: xxx
          roles:
            - detect
        - path: xxx
          roles:
            - record
      hwaccel_args: -c:v h264_qsv
    rtmp:
      enabled: false
    detect:
      width: 352
      height: 240
      fps: 15
    objects:
      track:
        - person
        - dog
        - cat
    snapshots:
      enabled: true
      bounding_box: true
birdseye:
  enabled: True
  mode: continuous
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  events:
    retain:
      default: 10
database:
  path: /media/frigate/db/frigate.db
```

### Relevant log output

```shell
no error
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
