### ISSUE TITLE
Mask config changes

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#523]
The motion mask has been moved under the `motion` config entry in recent changes. Also, there are now object level masks available as filters.

```yaml
cameras:
  front_door:
    ...
    motion:
      mask: poly,0,900,1080,900,1080,1920,0,1920
    ...
    objects:
      filters:
        person:
          min_area: 5000
          threshold: 0.6
          mask: poly,574,1058,772,1072,768,632,439,636,34,600
```

Also note that I updated to a docker based build process for the frontend @paularmstrong
