### ISSUE TITLE
[Config Support]: Connection failed: No route to host

### ISSUE THREAD

**Issue by yngveskog** [blakeblackshear/frigate#5237]
### Describe the problem you are having

I have one out of four cameras that has turned green, but which recently worked fine

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.104
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: password
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb
rtmp:
  enabled: False

# timestamp_style:
#   position: "tl"
#   format: "%m/%d/%Y %H:%M:%S"
#   color:
#     red: 255
#     green: 255
#     blue: 255
#   thickness: 2
#   effect: shadow

cameras:
  innkjoring:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.144:88/videoSub
          roles:
            - detect
          
        - path: rtsp://username:password@192.168.1.144:88/videoMain
          roles:
            - record
  

    detect:                 
      width: 640
      height: 480
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - car
    #   mask:
    #     - 2,465,328,468,330,432,5,431
    #     - 640,0,640,72,484,21,333,21,133,64,62,123,0,196,0,0
    # mqtt:
    #   timestamp: False
    #   bounding_box: False
    #   crop: True
    #   height: 500
    #   quality: 100
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 5
    # zones:
    #   drivewayclose_in:
    #     coordinates: 0,480,286,480,312,323,221,223,233,161,107,133,36,212,0,279      
    motion:
      mask:
        - 353,223,375,175,365,139,351,103,337,51,307,28,263,50,229,87,187,125,191,174,219,220,281,242
    #    
    #   threshold: 20
    #   contour_area: 100
    record:
      enabled: True
      retain: 
        days: 3
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
        pre_capture: 5
        post_capture: 10

  veggen:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.145/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            
        - path: rtsp://username:password@192.168.1.145/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  

    detect:                 
      width: 640
      height: 480
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - car
    #   mask:
    #     - 2,465,328,468,330,432,5,431
    #     - 640,0,640,72,484,21,333,21,133,64,62,123,0,196,0,0
    # mqtt:
    #   timestamp: False
    #   bounding_box: False
    #   crop: True
    #   height: 500
    #   quality: 100
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 5
    # zones:
    #   drivewayclose_in:
    #     coordinates: 0,480,286,480,312,323,221,223,233,161,107,133,36,212,0,279      
    motion:
      mask:
        - 144,378,204,280,242,194,395,186,390,132,374,87,363,51,319,0,188,0,0,0,0,107,0,272,0,414
        - 545,235,525,232,497,250,492,275,513,304,535,301    
    #   threshold: 20
    #   contour_area: 100
    record:
      enabled: True
      retain: 
        days: 3
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
        pre_capture: 5
        post_capture: 10   

  kjokkenet:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.143:88/videoSub
          roles:
            - detect
          
        - path: rtsp://username:password@192.168.1.143:88/videoMain
          roles:
            - record
  

    detect:                 
      width: 640
      height: 480
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
    #   mask:
    #     - 2,465,328,468,330,432,5,431
    #     - 640,0,640,72,484,21,333,21,133,64,62,123,0,196,0,0
    # mqtt:
    #   timestamp: False
    #   bounding_box: False
    #   crop: True
    #   height: 500
    #   quality: 100
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 5
    # zones:
    #   drivewayclose_in:
    #     coordinates: 0,480,286,480,312,323,221,223,233,161,107,133,36,212,0,279      
    motion:
      mask:
        - 234,40,234,0,123,0,0,0,0,75
    #    
    #   threshold: 20
    #   contour_area: 100
    record:
      enabled: True
      retain: 
        days: 3
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
        pre_capture: 5
        post_capture: 10    

  soveromsvindu:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.1.37:554/stream2
          roles:
            - detect
          
        - path: rtsp://username:password@192.168.1.37:554/stream1
          roles:
            - record
  

    detect:                 
      width: 640
      height: 480
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - car
    #   mask:
    #     - 2,465,328,468,330,432,5,431
    #     - 640,0,640,72,484,21,333,21,133,64,62,123,0,196,0,0
    # mqtt:
    #   timestamp: False
    #   bounding_box: False
    #   crop: True
    #   height: 500
    #   quality: 100
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 5
    # zones:
    #   drivewayclose_in:
    #     coordinates: 0,480,286,480,312,323,221,223,233,161,107,133,36,212,0,279      
    motion:
      mask:
          - 640,156,640,109,640,0,484,0,238,0,0,0,0,182
    #    
    #   threshold: 20
    #   contour_area: 100
    record:
      enabled: True
      retain: 
        days: 3
        mode: active_objects
      events:
        retain:
          default: 10
          mode: active_objects
        pre_capture: 5
        post_capture: 10 

birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: objects
```

### Relevant log output

```shell
[2023-01-24 21:32:21] watchdog.veggen                ERROR   : Ffmpeg process crashed unexpectedly for veggen.
[2023-01-24 21:32:21] watchdog.veggen                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2023-01-24 21:32:21] ffmpeg.veggen.detect           ERROR   : [tcp @ 0x55cffd9b5e00] Connection to tcp://192.168.1.145:554?timeout=5000000 failed: No route to host
[2023-01-24 21:32:21] ffmpeg.veggen.detect           ERROR   : rtsp://username:password@192.168.1.145/cam/realmonitor?channel=1&subtype=1: No route to host
[2023-01-24 21:32:21] ffmpeg.veggen.record           ERROR   : [tcp @ 0x5618a93e7fc0] Connection to tcp://192.168.1.145:554?timeout=5000000 failed: Connection timed out
[2023-01-24 21:32:21] ffmpeg.veggen.record           ERROR   : rtsp://username:password@192.168.1.145/cam/realmonitor?channel=1&subtype=0: Connection timed out
[2023-01-24 21:32:21] watchdog.veggen                INFO    : Terminating the existing ffmpeg process...
[2023-01-24 21:32:21] watchdog.veggen                INFO    : Waiting for ffmpeg to exit gracefully...
[2023-01-24 21:32:24] frigate.video                  ERROR   : veggen: Unable to read frames from ffmpeg process.
[2023-01-24 21:32:24] frigate.video                  ERROR   : veggen: ffmpeg process is not running. exiting capture thread...
[2023-01-24 21:32:31] watchdog.veggen                ERROR   : Ffmpeg process crashed unexpectedly for veggen.
[2023-01-24 21:32:31] watchdog.veggen                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
