### ISSUE TITLE
Reduce object detection rate during storms

### ISSUE THREAD

**Issue by silentnyte** [blakeblackshear/frigate#5244]
**Describe what you are trying to accomplish and why in non technical terms**
It would be great if during high motion events (like snow or rain storms) the object detection rate would reduce. I have noticed that during snow and rain storms my NVR machine goes into overdrive. I do not see any value in processing these images because they will mostly end up mis-identifications anyways.

**Describe the solution you'd like**
Set a threshold of percent of image that detects motion for x amount of time then reduce object detection rate to y. Might also be good to be able to increase the object percent confidence threshold.

**Comment by NickM-27** [comment]
This can already be done somewhat using the motion values inputs in MQTT to do things like reducing the motion sensitivity. 

Or, if like you said you don't see any value in processing the images then can just disable object detection until the rain has stopped?

**Comment by silentnyte** [comment]
Are you suggesting using a external program to monitor the MQTT motion value then disable or reduce object detection? A solution within Frigate would be more robust and not rely on an external to return to normal operation. Within Frigate a more robust detection of snow or rain storm could be developed.

**Comment by NickM-27** [comment]
> Are you suggesting using a external program to monitor the MQTT motion value then disable or reduce object detection? A solution within Frigate would be more robust and not rely on an external program to return to normal operation. Within Frigate a more robust detection of snow or rain storm could also be developed.

Home Assistant and other applications use MQTT to automate things, that way you can be very specific with how you want the situation to be tuned and handled. VS a more generic solution that would be implemented in frigate, which is why I suggested that.

**Comment by silentnyte** [comment]
I do not see in the setting where you can determine the % motion detected via MQTT. The only option I see would be to detected the time motion has been active. This would not be a good indicator of a snow or rain storm.

Is there another indicator of % area of motion detected?

**Comment by NickM-27** [comment]
> Is there another indicator of % area of motion detected?

You could do it based on the current detection FPS. If the current detection fps is high for a long enough period of time then can have an action to lower motion sensitivity.

% motion detected will have its own problems, for example a garbage truck driving past the camera slowly as it picks up trash. It would need to be done very carefully to avoid false positive rain / snow detections which will probably vary for each persons camera.

For my setup, it makes a lot more sense to use other signals besides the camera to detect when it is raining / snowing like my weather station,

**Comment by silentnyte** [comment]
That is why I suggested a % area detected along with time. This would reduce the false positives.

How do you get the current detection FPS via MQTT?

**Comment by NickM-27** [comment]
If you use home assistant it is a diagnostic sensor, likely disabled by default. Otherwise, it is in the /stats endpoint of MQTT

![Screen Shot 2023-01-25 at 07 43 01 AM](https://user-images.githubusercontent.com/14866235/214593358-977b49c5-f0ee-40c9-acd5-e22a81766907.png)

**Comment by silentnyte** [comment]
How do you enable the additional diagnostics? Are there instructions for understanding frigate/stats, frigate/<camera_name>/motion_threshold and frigate/<camera_name>/motion_contour_area?

**Comment by NickM-27** [comment]
> How do you enable the additional diagnostics? 

Just click on the `+x entities not shown` part and then click on the one you want and press enable

> Are there instructions for understanding frigate/stats, frigate/<camera_name>/motion_threshold and frigate/<camera_name>/motion_contour_area?

yes, they are explained in the reference config https://docs.frigate.video/configuration/index

**Comment by NickM-27** [comment]
```yaml
# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: False
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30
```
