### ISSUE TITLE
[Support]: (Beta) intel-vaapi GPU stats

### ISSUE THREAD

**Issue by bluesk1d** [blakeblackshear/frigate#5271]
### Describe the problem you are having

Frigate (beta) is unable to gather GPU stats and displays this message on the "System" page:
There was an error getting usage stats. Either your GPU does not support this or Frigate does not have proper access.

The log also indicates:
ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)

It sounds like a permission thing but I don't see anything referenced in the new docs regarding additional permissions or Docker volumes/devices needing to be mounted. Do I need to add something further to get the correct perms or is it just not supported on the i5-8400T?

### Version

0.12.0-12D51D3

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.6
  user: 
  password: 
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  doorbell:
    rtmp:
      enabled: False
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.1:7447/1BpSabwR3t5IDq0a
          roles:
            - detect
            - record
    detect:
      width: 1200
      height: 900
      stationary:
        interval: 150
        threshold: 30
    motion:
      mask:
        - 1200,591,931,526,923,463,745,496,723,0,1200,0 # sidewalk/street
        - 0,21,212,21,208,0,0,0 # Timestamp
    zones:
      Porch:
        coordinates: 446,810,458,789,926,627,1171,706,1121,900,404,900,410,813
      Frontyard:
        coordinates: 1171,694,1200,585,1067,556,954,623
      Driveway:
        coordinates: 971,616,1057,553,854,507,748,525,747,658,854,613
    record:
      enabled: True
      retain:
        days: 0
objects:
  track:
    - person
    - cat
    - dog
record:
  enabled: True
  retain:
    days: 14
  events:
    retain:
      default: 7
      mode: motion
      objects:
        person: 180
        dog: 30
        cat: 30
```

### Relevant log output

```shell
ERROR   : Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
// 20230127112736
// https://frigate.1tp.co/api/stats

{
  "backyard": {
    "camera_fps": 6.0,
    "capture_pid": 371,
    "detection_enabled": 1,
    "detection_fps": 0.0,
    "ffmpeg_pid": 387,
    "pid": 361,
    "process_fps": 6.0,
    "skipped_fps": 0.0
  },
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "16": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "40": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "41": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "76": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "77": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "79": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "86": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "104": {
      "cpu": "1.7",
      "mem": "1.3"
    },
    "109": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "116": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "117": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "118": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "119": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "120": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "128": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "342": {
      "cpu": "0.0",
      "mem": "0.5"
    },
    "348": {
      "cpu": "0.3",
      "mem": "0.1"
    },
    "349": {
      "cpu": "0.0",
      "mem": "0.7"
    },
    "351": {
      "cpu": "0.7",
      "mem": "0.6"
    },
    "358": {
      "cpu": "0.7",
      "mem": "0.6"
    },
    "359": {
      "cpu": "0.7",
      "mem": "0.6"
    },
    "360": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "361": {
      "cpu": "0.3",
      "mem": "0.6"
    },
    "362": {
      "cpu": "0.3",
      "mem": "0.6"
    },
    "363": {
      "cpu": "1.7",
      "mem": "0.6"
    },
    "366": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "367": {
      "cpu": "1.3",
      "mem": "0.6"
    },
    "368": {
      "cpu": "21.9",
      "mem": "0.6"
    },
    "370": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "371": {
      "cpu": "1.3",
      "mem": "0.6"
    },
    "374": {
      "cpu": "2.0",
      "mem": "0.6"
    },
    "375": {
      "cpu": "23.9",
      "mem": "0.6"
    },
    "378": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "383": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "384": {
      "cpu": "28.6",
      "mem": "0.9"
    },
    "387": {
      "cpu": "19.9",
      "mem": "1.0"
    },
    "902": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "905": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "2.9"
    },
    "MiB": {
      "cpu": "7033.7",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 0.0,
  "detectors": {
    "coral": {
      "detection_start": 0.0,
      "inference_speed": 8.82,
      "pid": 349
    }
  },
  "doorbell": {
    "camera_fps": 5.0,
    "capture_pid": 367,
    "detection_enabled": 1,
    "detection_fps": 0.0,
    "ffmpeg_pid": 375,
    "pid": 359,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "garage_exterior": {
    "camera_fps": 6.1,
    "capture_pid": 374,
    "detection_enabled": 1,
    "detection_fps": 0.0,
    "ffmpeg_pid": 384,
    "pid": 362,
    "process_fps": 6.1,
    "skipped_fps": 0.0
  },
  "gpu_usages": {
    "error-gpu": {
      "gpu": -1,
      "mem": -1
    }
  },
  "porch_east": {
    "camera_fps": 5.1,
    "capture_pid": 363,
    "detection_enabled": 1,
    "detection_fps": 0.0,
    "ffmpeg_pid": 368,
    "pid": 358,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "service": {
    "latest_version": "0.11.1",
    "storage": {
      "/dev/shm": {
        "free": 58.0,
        "mount_type": "tmpfs",
        "total": 67.1,
        "used": 9.1
      },
      "/media/frigate/clips": {
        "free": 6502011.5,
        "mount_type": "ext4",
        "total": 23435036.8,
        "used": 16932471.6
      },
      "/media/frigate/recordings": {
        "free": 6502011.5,
        "mount_type": "ext4",
        "total": 23435036.8,
        "used": 16932471.6
      },
      "/tmp/cache": {
        "free": 979.2,
        "mount_type": "tmpfs",
        "total": 1000.0,
        "used": 20.8
      }
    },
    "temperatures": {
      
    },
    "uptime": 284,
    "version": "0.12.0-12d51d3"
  }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

Hardware info:
QNAP model: TVS-672XT
CPU: i5-8400T
