### ISSUE TITLE
[Config Support]: Unable to view clips on iPhone

### ISSUE THREAD

**Issue by tsaG1337** [blakeblackshear/frigate#5282]
### Describe the problem you are having

I upgraded frigate to 12..0 beta 5 and it seems I changed my config to restream to a format I my iphone is not able to read. 

Watching the live card is fine, however when I look at the events I only get a crossed out play button. Same for the Notifications. I forwarded the Videolink of a notification to my PC where it plays perfectly, thats why I assume its due to the encoding.
The URL I opened would be the following
`https://mydomain.de/api/frigate/notifications/1674810587.613818-hwlnkc/camera_xyz/clip.mp4`

### Version

0.12.0-beta5

### Frigate config file

```yaml
go2rtc:
  streams:
    Gartencam_high: # <- for RTSP streams
      - rtsp://user:pass@192.168.1.22:554/11
      - ffmpeg:Gartencam_high#audio=opus
    Gartencam_low: # <- for RTSP streams
      - rtsp://user:pass@192.168.1.22:554/12
      - ffmpeg:Gartencam_low#audio=opus

  webrtc:
    candidates:
      - 192.168.1.3:8555
      - stun:8555

mqtt:
  host: 192.168.1.2

cameras:
  Gartencam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Gartencam_high?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Gartencam_low?video=copy&audio=aac
          roles:
            - detect
    detect:
      enabled: True
      fps: 10
      width: 800
      height: 600
    motion:
      mask:
        - 619,21,800,21,800,0,619,0
    live:
      stream_name: Gartencam_low

detectors:
  coral1:
    type: edgetpu
    device: pci
    
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous
  
objects:
  track:
    - person
    - cat
    - bird

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - cat
      - bird
    required_zones: []
    retain:
      default: 21
      mode: motion
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

M.2
