### ISSUE TITLE
[Support]: beta5 doesn't like my config

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#5296]
### Describe the problem you are having

Getting this upon startup. Looked at the breaking changes but couldn't find anything, the logs seem to say acceptable roles are record,rtmp and detect, which is what it seems to get.

`rigate  | 2023-01-30 09:23:07.507665154  11 validation errors for FrigateConfig
frigate  | 2023-01-30 09:23:07.507668371  cameras -> license_plate -> ffmpeg -> inputs -> 1 -> roles -> 0
frigate  | 2023-01-30 09:23:07.507672266    value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
frigate  | 2023-01-30 09:23:07.507673544  cameras -> greenhouse_2 -> ffmpeg -> inputs -> 1 -> roles -> 0
frigate  | 2023-01-30 09:23:07.507675378    value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
frigate  | 2023-01-30 09:23:07.507676511  cameras -> front_driveway_1 -> ffmpeg -> inputs -> 1 -> roles -> 0
`

### Version

frigate-0.12.0-beta5

### Frigate config file

```yaml
mqtt:

  host: 192.168.50.148
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: blabla
  stats_interval: 300

record:
  expire_interval: 10


timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:

  license_plate:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/license_plate
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=5&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream 
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15

  greenhouse_2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/greenhouse_2
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.170:554/user=admin&password=blabla&channel=3&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15

  front_driveway_1:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_driveway_1
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=6&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15
        
  front_driveway_2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_driveway_2
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=8&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_2_close_in
#        - front_driveway_2_whole_area
      crop: True
      height: 500
      retain:
        default: 3
#    zones:
#      front_driveway_2_close_in:
#        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
#        objects:
#          - car
#          - person
#          - dog
#          - cat
#          - bicycle
 #     front_driveway_2_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
        - 889,476,891,596,785,598,786,476
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_2_close_in
#          - front_driveway_2_whole_area
        pre_capture: 5
        post_capture: 15
        
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_porch
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=7&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
  #    mask:
  #      - 0,480,198,480,200,449,0,451
  #      - 640,0,640,36,640,111,608,135,485,96,504,0
  #      - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
  #      - 370,0,356,100,291,79,292,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
#      required_zones:
#        - front_porch_close_in
      retain:
        default: 5
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    #zones:
    #  front_porch_close_in:
    #    coordinates: 45,480,362,480,640,480,640,213,554,145,525,328,466,343,408,272,348,70,253,64,181,118,67,178
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
#        required_zones:
#         - front_porch_close_in
        pre_capture: 5
        post_capture: 15
        
  back_porch:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/back_porch
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=1&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
 #      person:
 #         mask:
 #           - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  diningroom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/diningroom
          roles:
            - detect
            - record
        - path: rtsp://Admin1:Van1llaPa1@192.168.50.227/live0
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1382,58,1872,55,1868,8,1382,7
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/kitchen
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.70/live0
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1382,58,1872,55,1868,8,1382,7
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=2&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  greenhouse:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/greenhouse
          roles:
            - detect
            - record
        - path: rtsp://192.168.50.15:554/user=admin&password=blabla&channel=3&stream=0.sdp?real_stream--rtp-caching=100
          roles:
            - restream
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
        
detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

restream:
  birdseye: True
  jsmpeg:
    height: 640
    quality: 1
```

### Relevant log output

```shell
`rigate  | 2023-01-30 09:23:07.507665154  11 validation errors for FrigateConfig
frigate  | 2023-01-30 09:23:07.507668371  cameras -> license_plate -> ffmpeg -> inputs -> 1 -> roles -> 0
frigate  | 2023-01-30 09:23:07.507672266    value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
frigate  | 2023-01-30 09:23:07.507673544  cameras -> greenhouse_2 -> ffmpeg -> inputs -> 1 -> roles -> 0
frigate  | 2023-01-30 09:23:07.507675378    value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
frigate  | 2023-01-30 09:23:07.507676511  cameras -> front_driveway_1 -> ffmpeg -> inputs -> 1 -> roles -> 0
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
Not running currently.
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

dahua

### Any other information that may be helpful

No
