### ISSUE TITLE
Ability to dynamically enable / disable saving detections as events

### ISSUE THREAD

**Issue by mikeage** [blakeblackshear/frigate#5314]
**Describe what you are trying to accomplish and why in non technical terms**
I use Frigate as my home NVR, and Home Assistant for home automation. I want to activate my lights when there's motion, without purchasing a bunch of discrete motion sensors (I have some, but I want more coverage). If I use motion sensing in Frigate to trigger the lights, I wind up with an infinite loop whereby after X minutes of no motion, the lights turn off, which causes a significant change in the image, and then they turn back on again almost immediately, ad infinitum. The same problem happens when my cameras automatically switch from day mode to night mode and back.

To solve this, I switched from camera motion detection to object detection. Only if there are people found do the lights activate. This works great, however, it also records clips. I want to record clips if people are found when I'm "Not Home" (this is managed by Home Assistant), but not when I'm home. If I disable the recording, I get no recordings, ever, and if I enable it, I get recordings at all times, whenever people are around.

I also want the global background recording to always take place. Only the clips should be disabled.

**Describe the solution you'd like**
I can use MQTT to enable/disable global recording. I can use MQTT to enable/disable object tracking. But within the object detection, I have to specify "record" in the YAML, and can't control it dynamically. I want to be able to do this.

**Describe alternatives you've considered**
Right now, I use object detection for my motion sensors, and I have a bunch of clip recordings that I don't care about. 

**Additional context**
This is my yaml (excerpts, of course):

```yaml
record:
  enabled: True # I can change this now already
...
cameras:
  foo_camera:
    ffmpeg:
      inputs:
        - path: REDACTED
          roles:
            - detect # I can change this now already, but I need it to stay enabled
            - record  # This is what I want to be able to toggle, without having to disable 'detect'
```
