### ISSUE TITLE
Config for HASS is incorrect

### ISSUE THREAD

**Issue by vpetrovych** [blakeblackshear/frigate#532]
**Describe the bug**
It seems that settings defined for release 8.0 don't seem to match reality.
1) It still seems to accept `save_clips` instead of `clips`
2) `mqtt` is not defined at camera level, showing the following error:
```
frigate.app                    ERROR   : Error parsing config: extra keys not allowed @ data['cameras']['corridor']['mqtt']
```

**Version of frigate**
What version are you using? 
Frigate NVR Beta addons

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
  host: core-mosquitto.local.hass.io
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - info
cameras:
  corridor:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.0.141:554'
          roles:
            - clips
            - record
            - rtmp
        - path: 'rtsp://192.168.0.141:554/media/video2'
          roles:
            - detect
    width: 720
    height: 1280
    fps: 5
    save_clips:
      enabled: true
    mqtt:
      crop_to_region: true
      snapshot_height: 500
```

**Logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    ERROR   : Error parsing config: extra keys not allowed @ data['cameras']['corridor']['mqtt']
```

**Computer Hardware**
 - OS: HASS IO
 - Virtualization: [e.g. Proxmox, Virtualbox] none
 - Coral Version: [e.g. USB, PCIe, None] none
 - Network Setup: [e.g. Wired, WiFi] WIFI

**Camera Info:**
 - Manufacturer: [e.g. Dahua] Uniview
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**
