### ISSUE TITLE
Latest is showing distorted image

### ISSUE THREAD

**Issue by vpetrovych** [blakeblackshear/frigate#533]
**Describe the bug**
It seems that the latest image is somehow incorrectly generated.
The RTMP stream seems to be fine.

**Version of frigate**
What version are you using?
8.0-beta3

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
#detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
mqtt:
  host: 192.168.0.10
  user: mqtt
  password: mqtt
ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - info
cameras:
  corridor:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.0.141:554'
          roles:
            - clips
            - record
            - rtmp
        - path: 'rtsp://192.168.0.141:554/media/video2'
          roles:
            - detect
    width: 720
    height: 1280
    fps: 5
    save_clips:
      enabled: true
#    snapshots:
#      enabled: true
#      crop: true
#      crop_to_region: true
#      height: 500
```

**Logs**
```
ffmpeg.corridor.detect         ERROR   : frame=  899 fps=5.0 q=-0.0 size=  303412kB time=00:02:59.80 bitrate=13824.0kbits/s dup=0 drop=1790 speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  902 fps=5.0 q=-0.0 size=  304425kB time=00:03:00.40 bitrate=13824.0kbits/s dup=0 drop=1795 speed=1.01x
[h264 @ 0x56386b4a5d00] SEI type 5 size 2280 truncated at 1928
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3604 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:00.37 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  905 fps=5.0 q=-0.0 size=  305438kB time=00:03:01.00 bitrate=13824.0kbits/s dup=0 drop=1801 speed=1.01x
ffmpeg.corridor.detect         ERROR   : [NULL @ 0x55d4f240ea00] SEI type 5 size 2280 truncated at 1944
ffmpeg.corridor.detect         ERROR   : [h264 @ 0x55d4f2583300] SEI type 5 size 2280 truncated at 1928
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3615 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:00.89 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  907 fps=5.0 q=-0.0 size=  306112kB time=00:03:01.40 bitrate=13824.0kbits/s dup=0 drop=1806 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3625 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:01.40 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  910 fps=5.0 q=-0.0 size=  307125kB time=00:03:02.00 bitrate=13824.0kbits/s dup=0 drop=1811 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3636 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:01.96 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  913 fps=5.0 q=-0.0 size=  308138kB time=00:03:02.60 bitrate=13824.0kbits/s dup=0 drop=1817 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3647 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:02.48 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  915 fps=5.0 q=-0.0 size=  308812kB time=00:03:03.00 bitrate=13824.0kbits/s dup=0 drop=1822 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3657 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:03.00 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  918 fps=5.0 q=-0.0 size=  309825kB time=00:03:03.60 bitrate=13824.0kbits/s dup=0 drop=1827 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3668 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:03.56 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  921 fps=5.0 q=-0.0 size=  310838kB time=00:03:04.20 bitrate=13824.0kbits/s dup=0 drop=1833 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3679 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:04.08 bitrate=N/A speed=1.01x
ffmpeg.corridor.detect         ERROR   : frame=  923 fps=5.0 q=-0.0 size=  311512kB time=00:03:04.60 bitrate=13824.0kbits/s dup=0 drop=1838 speed=1.01x
ffmpeg.corridor.clips_record_rtmp ERROR   : frame= 3689 fps= 20 q=-1.0 q=-1.0 size=N/A time=00:03:04.60 bitrate=N/A speed=1.01x
```

**Frigate debug stats**
```
{"corridor":{"camera_fps":1.3,"capture_pid":37,"detection_fps":0.0,"pid":36,"process_fps":1.3,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":33}}}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.28)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.3.1_8 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://192.168.0.141:554/':
  Metadata:
    title           : VCP IPC Realtime stream
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1080x1920, 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1
```

**Screenshots**
![latest (1)](https://user-images.githubusercontent.com/576364/104854523-cf2ac400-590f-11eb-89ee-fb310ceaf957.jpg)
<img width="783" alt="Screenshot 2021-01-17 at 22 04 12" src="https://user-images.githubusercontent.com/576364/104854551-f1244680-590f-11eb-8def-3323c0da72cb.png">

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows] Ubunto 20.04
 - Virtualization: [e.g. Proxmox, Virtualbox] None
 - Coral Version: [e.g. USB, PCIe, None] None
 - Network Setup: [e.g. Wired, WiFi] Wired

**Camera Info:**
 - Manufacturer: [e.g. Dahua] Uniview
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p] 1080x1920
 - FPS: [e.g. 5] 20
