### ISSUE TITLE
[Config Support]: Amcrest cameras -  Failed to get WebRTC port from supervisor

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5336]
### Describe the problem you are having

Hey
I have in total 12 cameras.
Only Amcrest cameras was failed, all the rest working great

### Version

0.12 beta6

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.230
  user: "mqttuser"
  password: "pass"


birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb   
    
go2rtc:
  streams:
    Entrance:
      - rtsp://admin:abc@192.168.1.127:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:Entrance#audio=opus
    Entrance_sub: 
      - rtsp://admin:abc@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0
    Garden:
      - path: rtsp://admin:abc@192.168.1.139:554/cam/realmonitor?channel=1&subtype=1
      - ffmpeg:Garden#audio=opus
    Garden_sub: 
      - path: rtsp://admin:abc@192.168.1.139:554/cam/realmonitor?channel=1&subtype=0
cameras:
#################################################Garden########################################
  Garden:
    ffmpeg:
       inputs:
           - path:  rtsp://127.0.0.1:8554/Garden_sub?video=copy
             input_args: preset-rtsp-restream
             roles:
               - detect
           - path: rtsp://127.0.0.1:8554/Garden?video=copy&audio=aac
             input_args: preset-rtsp-restream
             roles:
               - record
    detect:
      width: 1280
      height: 720
      fps: 5
           
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 175
      retain:
        default: 14
 
    record:
      enabled: true
      retain:
        days: 1
      events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        retain:
          default: 1
    motion:
      mask:
        - 422,0,0,0,0,325
    zones:
      zone_parking:
        coordinates: 796,339,690,189,414,253,220,406
        objects:
          - person
          - dog
          - cat
      zone_storage:
        coordinates: 738,0,1191,0,1258,112,700,201
        objects:
          - person
          - dog
          - cat
#################################################Garden########################################
#################################################Entrance######################################
  Entrance:
    ffmpeg:
      inputs:
          - path:  rtsp://127.0.0.1:8554/Entrance_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
          - path: rtsp://127.0.0.1:8554/Entrance?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
    detect:
      width: 1280
      height: 720
      fps: 10
    rtmp:
      enabled: false
           
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 175
      retain:
        default: 14
 
    record:
      enabled: true
      retain:
        days: 2
      events:
        pre_capture: 30
        post_capture: 50
        objects:
          - person
          - cat
          - dog
        retain:
          default: 1
    motion:
      mask:
        - 1280,0,1280,327,961,0
    zones:
      zone_entrance:
        coordinates: 74,720,563,611,768,565,993,497,1046,636,806,720,95,720,880,533,734,199,583,308,455,410,303,540,91,699,119,454,195,249,326,51,739,189
        objects:
          - person
          - dog
          - cat
#################################################Entrance######################################
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service frigate: starting
[INFO] Preparing go2rtc config...
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[INFO] Starting Frigate...
[INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
[INFO] Got IP address from supervisor: 192.168.1.230
[WARN] Failed to get WebRTC port from supervisor
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 65, in <module>
    go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
AttributeError: 'dict' object has no attribute 'format'
Service go2rtc exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
Service Frigate exited with code 256 (by signal 15)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
