### ISSUE TITLE
[Camera Support]: What the best config for Amcrest (IP5M-T1179E) camera?

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5341]
### Describe the problem you are having

I'm not sure what the best config, I feel can do better
What do you think guys ?

### Version

0.12 beta6

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.230
  user: "mqttuser"
  password: "pass"


birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb   
    
go2rtc:
  streams:
    Entrance:
      - rtsp://admin:abc@192.168.1.127:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Entrance#audio=opus
    Entrance_sub: 
      - rtsp://admin:abc@192.168.1.127:554/cam/realmonitor?channel=1&subtype=1
    Garden:
      - path: rtsp://admin:abc@192.168.1.139:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Garden#audio=opus
    Garden_sub: 
      - path: rtsp://admin:abc@192.168.1.139:554/cam/realmonitor?channel=1&subtype=1
cameras:
#################################################Garden########################################
  Garden:
    ffmpeg:
       inputs:
           - path:  rtsp://127.0.0.1:8554/Garden_sub?video=copy
             input_args: preset-rtsp-restream
             roles:
               - detect
           - path: rtsp://127.0.0.1:8554/Garden?video=copy&audio=aac
             input_args: preset-rtsp-restream
             roles:
               - record
    detect:
      width: 1280
      height: 720
      fps: 5
           
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 175
      retain:
        default: 14
 
    record:
      enabled: true
      retain:
        days: 1
      events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        retain:
          default: 1
    motion:
      mask:
        - 422,0,0,0,0,325
    zones:
      zone_parking:
        coordinates: 796,339,690,189,414,253,220,406
        objects:
          - person
          - dog
          - cat
      zone_storage:
        coordinates: 738,0,1191,0,1258,112,700,201
        objects:
          - person
          - dog
          - cat
#################################################Garden########################################
#################################################Entrance######################################
  Entrance:
    ffmpeg:
      inputs:
          - path:  rtsp://127.0.0.1:8554/Entrance_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
          - path: rtsp://127.0.0.1:8554/Entrance?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
    detect:
      width: 1280
      height: 720
      fps: 10
    rtmp:
      enabled: false
           
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 175
      retain:
        default: 14
 
    record:
      enabled: true
      retain:
        days: 2
      events:
        pre_capture: 30
        post_capture: 50
        objects:
          - person
          - cat
          - dog
        retain:
          default: 1
    motion:
      mask:
        - 1280,0,1280,327,961,0
    zones:
      zone_entrance:
        coordinates: 74,720,563,611,768,565,993,497,1046,636,806,720,95,720,880,533,734,199,583,308,455,410,303,540,91,699,119,454,195,249,326,51,739,189
        objects:
          - person
          - dog
          - cat
#################################################Entrance######################################
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "20/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 720, "width": 1280 } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "20/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 480, "width": 704 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest
