### ISSUE TITLE
[HW Accel Support]:  Ryzen 5 5625U MiniPc Proxmox Not Working

### ISSUE THREAD

**Issue by liamstears** [blakeblackshear/frigate#5344]
### Describe the problem you are having

I am trying to get hardware acceleration working but unfortunately failing, probably due to my stupidity but hope to get some help/verification

Frigate is in a docker container on an Alpine Linux VM in Proxmox, I have attached relevant log from Frigate and from the VAINFO

### Version

0.12.0-EA8EC23

### Frigate config file

```yaml
mqtt:
  host: "HOST_IP"
  user: "USERNAME"
  password: "PASSWORD"
cameras:
  doorbell:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: "PATH_TO_CAMERA"
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: motion
  driveway:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: "PATH_TO_CAMERA"
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 14
          mode: motion
```

### docker-compose file or Docker CLI command

```yaml
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --shm-size=256m \
  -v /root/frigate/media:/media/frigate \
  -v /root/frigate/config.yml:/config/config.yml:ro \
  -e FRIGATE_RTSP_PASSWORD='PASSWORD' \
  -e LIBVA_DRIVER_NAME=radeonsi \
  -p 5000:5000 \
  -p 1935:1935 \
  ghcr.io/blakeblackshear/frigate:0.12.0-beta6
```

### Relevant log output

```shell
2023-02-02 02:20:34.921182267  [2023-02-02 02:20:34] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x55563645a740] No VA display found for device /dev/dri/renderD128.
2023-02-02 02:20:34.921239543  [2023-02-02 02:20:34] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -22.
2023-02-02 02:20:34.921287530  [2023-02-02 02:20:34] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x555636465900] No device available for decoder: device type vaapi needed for codec h264.
```

### FFprobe output from your camera

```shell
Trying display: wayland
error: XDG_RUNTIME_DIR not set in the environment.
Trying display: x11
error: can't connect to X server!
Trying display: drm
error: failed to initialize display
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

NA
