### ISSUE TITLE
Feature Request: Reimplementation of rtmp/rtsp role and more preset ffmpeg config

### ISSUE THREAD

**Issue by Maxcodesthings** [blakeblackshear/frigate#5358]
First just want to say this beta version 0.12.0 is looking great. I love having a simpler deployment with `go2rtc` built-in

**Describe what you are trying to accomplish and why in non technical terms**
I want some cameras to have 3 streams, but their hardware only supports 2:

1. HIghest quality for recording
2. Medium quality for near-seamless playback on mobile devices (HD/1080)
3. Low quality for better detection performance

My cameras already give me High and Low quality, as a sub-stream, but nothing for a medium setting. And with version 0.12.0 there is no longer an `rtmp` role to flag a video input as which one you want to stream.

If i stream the highest quality to Home Assistant, mobile devices have a very hard time keeping up especially with a slow connection.

**Describe the solution you'd like**

1. Reimplementation of the removed `rtmp` role so i can flag a particular input for streaming video seperate from recording or detecting
2. An ffmpeg preset that will re-encode a stream at a lower quality. Ffmpeg is notoriously difficult to use and the presets would be extremely useful

Example config:
```
cameras:
  family:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/family_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/family
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/family_medium
          input_args: preset-rtsp-restream-1080-h264
          roles:
            - restream
 ```
           

**Describe alternatives you've considered**
I have tried using [Advanced Restrean Configurations](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream#advanced-restream-configurations ) but ffmpeg is too hard to use to know what to put. I feel detecting what raw stream is being input and what flags to set on ffmpeg for the desired output is a better handled using an ffmpeg preset

**Additional context**

Thanks Again!

**Comment by NickM-27** [comment]
You can already accomplish all of this with go2rtc without using direct ffmpeg commands

**Comment by NickM-27** [comment]
https://github.com/AlexxIT/go2rtc

From your example you could just do

```yaml
go2rtc:
  streams:
    family:
      ...
    family_medium:
      - "ffmpeg:family#video#h264#audio=copy#width=1080#hardware=YOUR_HWACCEL_TYPE"
```

And it'll work like you're wanting. There's really no reason for frigate to reinvent the wheel here which is why the restream role was removed in the first place for beta 4

**Comment by Maxcodesthings** [comment]
Thanks for the reply @NickM-27, so the go2rtc configuration in Frigate is a direct passthrough? It looks like it might be, ill have to see what presets Alex has added

The reimplementation of restream role was so I could flag what stream to use in Home Assistant. Which camera would surface  in Home Assistant given my example config? Would I be expected to just make another camera just for this stream?

**Comment by NickM-27** [comment]
> Thanks for the reply @NickM-27, so the go2rtc configuration in Frigate is a direct passthrough? It looks like it might be, ill have to see what presets Alex has added

Yes, that's the advantage. 

> The reimplementation of restream role was so I could flag what stream to use in Home Assistant. Which camera would surface in Home Assistant given my example config? Would I be expected to just make another camera just for this stream?

Depends how you configure it. By default it uses the go2rtc stream that matches the name of the camera in cameras section. You could easily setup HA integration to use the `{{ camera }}_medium` stream though. 

Also if you're using the frigate card / WebRTC card (which is recommended) you'd just want to specify the exact stream `family_medium` which is really easy.

**Comment by Maxcodesthings** [comment]
I believe this is a complete example of what you suggest?
```
go2rtc:
  streams:
    family_record:
      - rtsp://admin:crispycheese609@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - "ffmpeg:family#audio=opus"
    family_sub:
      - rtsp://admin:crispycheese609@192.168.1.58:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
    family:
      - "ffmpeg:family#video=h264#audio=copy#width=1080#hardware=YOUR_HWACCEL_TYPE"

cameras:
  family:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/family
          input_args: preset-rtsp-restream
        - path: rtsp://127.0.0.1:8554/family_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/family_record
          input_args: preset-rtsp-restream
          roles:
            - record
```

I dont think that default behavior is in the docs, but I could be wrong. Do you take documentation PRs?

**Comment by Maxcodesthings** [comment]
```
2023-02-02 16:02:17.063574739  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2023-02-02 16:02:17.063575863  cameras -> family -> ffmpeg -> inputs -> 0 -> roles
2023-02-02 16:02:17.063576846    none is not an allowed value (type=type_error.none.not_allowed)
```
What role would i set for this input if i already have detect and record covered?

**Comment by Maxcodesthings** [comment]
Now im back to where i was with native go2rtc: guessing and trying every combination of ffmpeg parameters. This is why i mentioned some presets from Frigate side are useful. 
```
2023-02-02 16:31:23.260113818  16:31:23.259 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:family#video=h264#audio=copy#width=1080#hardware
```
```
2023-02-02 16:31:10.830885835  16:31:10.830 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:family#video=h264
```
```
2023-02-02 16:34:01.683116050  16:34:01.683 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:family#video=h264#audio=copy#width=1080#hardware=h264_cuvid
```


I guess ill take this to go2rtc issues instead.

**Comment by NickM-27** [comment]
Reastream is not a role so that's your problem there. Also the #hardware should be `cuda` if you're using nvidia.

**Comment by NickM-27** [comment]
Also you're doing the referencing wrong. You're using ffmpeg:family but that's the name of the camera you're creating. It should be `ffmpeg:family_record#...`

There's no need to be guessing you just need to slow down and read the documentation for go2rtc, it's all there.

**Comment by blakeblackshear** [comment]
Just to clarify, you can add whatever streams you want to go2rtc. There is no requirement to reference that stream anywhere else in frigate. It will still function as a rtsp relay for the stream as it runs independently.

**Comment by Maxcodesthings** [comment]
> It should be `ffmpeg:family_record#...`

Yup, to much renaming i missed that, thanks

> There's no need to be guessing you just need to slow down and read the documentation for go2rtc

There is a good deal missing in the hardware section, but I definitely jumped to conclusions from my previous experience with ffmpeg. That thing scares me.

> Reastream is not a role so that's your problem there
I don't see where I put that as a role. I tried not specifying a role for my inputs like this:
```
cameras:
  family:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/family
          input_args: preset-rtsp-restream
        - path: rtsp://127.0.0.1:8554/family_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
       - path: rtsp://127.0.0.1:8554/family_record 
          input_args: preset-rtsp-restream
          roles:
            - record
```
Like you mentioned earlier so my default streamed input and the one played back by home assistant is the resized one but I have to specify a `role` for inputs
```
2023-02-02 16:02:17.063574739  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2023-02-02 16:02:17.063575863  cameras -> family -> ffmpeg -> inputs -> 0 -> roles
2023-02-02 16:02:17.063576846    none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by NickM-27** [comment]
> I don't see where I put that as a role. I tried not specifying a role for my inputs like this:
> 
> ```
> 
> cameras:
> 
>   family:
> 
>     ffmpeg:
> 
>       inputs:
> 
>         - path: rtsp://127.0.0.1:8554/family
> 
>           input_args: preset-rtsp-restream
> 
>         - path: rtsp://127.0.0.1:8554/family_sub
> 
>           input_args: preset-rtsp-restream
> 
>           roles:
> 
>             - detect
> 
>        - path: rtsp://127.0.0.1:8554/family_record 
> 
>           input_args: preset-rtsp-restream
> 
>           roles:
> 
>             - record
> 
> ```
> 
> Like you mentioned earlier so my default streamed input and the one played back by home assistant is the resized one but I have to specify a `role` for inputs
> 
> ```
> 
> 2023-02-02 16:02:17.063574739  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
> 
> 2023-02-02 16:02:17.063575863  cameras -> family -> ffmpeg -> inputs -> 0 -> roles
> 
> 2023-02-02 16:02:17.063576846    none is not an allowed value (type=type_error.none.not_allowed)
> 
> ```

You defined 3 streams but aren't giving any roles to the first stream which is incorrect, there's no reason to define it there

**Comment by Maxcodesthings** [comment]
Thinking what @blakeblackshear said i think i see now what you mean.

The frigate HA integration imports camera for what is under `cameras` configuration. It then matches that name with a name under `streams` to use for HA. It then accesses the stream at http://<frigate-host>:8554/<camera>. I thot i had to put the `streams.family` under `cameras.family.ffmpeg.inputs` in order for it to get pickup by HA

Unfortunately, Home Assistant seems to now wants to stream in 'mjpeg'. Do you know why this would be? The stream on 8554 seems to be webrtc when using VLC

**Comment by NickM-27** [comment]
> Unfortunately, Home Assistant seems to now wants to stream in 'mjpeg'. Do you know why this would be? The stream on 8554 seems to be webrtc when using VLC

VLC doesn't play WebRTC, it's definitely just rtsp. 

And as far as the HA integration goes, it would just be jpeg snapshots if the stream isn't working. We'd need to see a new full copy of your config to diagnose that (also make sure to reload the frigate integration when changing the frigate config.

**Comment by Maxcodesthings** [comment]
> VLC doesn't play WebRTC, it's definitely just rtsp.

I should say the Frigate portal. It runs fine on WebRTC and MSE in the portal
I have reloaded the integration as well

```
mqtt:
  host: 192.168.1.50

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -c:v h264_cuvid


go2rtc:
  webrtc:
    listen: ":8555"
    candidates:
      - 192.168.1.50:8555
      - stun:8555
  streams:
    family_record:
      - rtsp://admin:pass@192.168.1.58:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - "ffmpeg:family_record#audio=opus"
    family_sub:
      - rtsp://admin:pass@192.168.1.58:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
    family:
      - "ffmpeg:family_record#video=h264#audio=copy#width=640#height=480#hardware=cuda"
      

cameras:
  family:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/family_record
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/family_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

```
