### ISSUE TITLE
[Support]: Motion detection via MQTT stuck "on"

### ISSUE THREAD

**Issue by rogersmj** [blakeblackshear/frigate#5359]
### Describe the problem you are having

I've had Frigate setup for two days, and while it appeared to work fine at first (including the Home Assistant integration), my motion detection for both cameras is now stuck "on" (as reported via MQTT). 

Event detection/recording seems to work in Frigate itself (mostly...it's not detecting cars at night even though my driveway is well-lit, but that's probably a different issue), but as you can see it reports motion in Home Assistant all day today (the Cleared/Unavailable blips were me restarting everything in the past hour as part of troubleshooting...once it comes back up, it sends the "ON" MQTT message again):

![image](https://user-images.githubusercontent.com/20134/216503410-7485c376-e7e7-4618-b1b2-4ec3da829640.png)

Just now, there had been no one on my front porch for hours. I stepped out there, and Frigate correctly detected a person and recorded a clip...but the motion sensor in Home Assistant has never stopped saying "Detected", even now 5+ minutes after I came back inside.

It's doing the same thing on both cameras, despite the fact that there is nothing moving anywhere in frame.

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.5.102
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: '{FRIGATE_MQTT_PASSWORD}'
database:
  path: /db/frigate.db
objects:
  track:
    - person
    - car
detect:
  width: 704
  height: 480
record:
  enabled: true
cameras:
  front_porch:
    zones:
      on_porch:
        coordinates: 501,21,592,54,546,260,601,292,520,480,217,480,152,354,211,183
        objects:
          - person
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.200/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.200/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.201/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.3.201/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
```

### Relevant log output

```shell
No errors/warnings in the log other than CPU detectors are not recommended (I know...waiting on my Coral)
```

### FFprobe output from your camera

```shell
bash: !@192.168.3.200/cam/realmonitor?channel=1: event not found

^ I just took the rstp URL from the config file (and put my real password in it), was that the right way to do this?
```

### Frigate stats

```json
{"front_porch": {"camera_fps": 5.1, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 2.5, "pid": 220, "capture_pid": 224}, "driveway": {"camera_fps": 5.0, "process_fps": 5.1, "skipped_fps": 0.0, "detection_fps": 2.0, "pid": 221, "capture_pid": 228}, "detectors": {"cpu": {"inference_speed": 51.88, "detection_start": 1675394416.321403, "pid": 216}}, "detection_fps": 4.5, "service": {"uptime": 1270, "version": "0.11.1-2eada21", "latest_version": "0.11.1", "storage": {"/media/frigate/recordings": {"total": 646811.0, "used": 4549.8, "free": 642261.2, "mount_type": "nfs"}, "/media/frigate/clips": {"total": 646811.0, "used": 4549.8, "free": 642261.2, "mount_type": "nfs"}, "/tmp/cache": {"total": 1000.0, "used": 65.3, "free": 934.7, "mount_type": "tmpfs"}, "/dev/shm": {"total": 67.1, "used": 2.6, "free": 64.5, "mount_type": "tmpfs"}}, "temperatures": {}}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest UltraHD 4K (IP8M-T2599EW)
