### ISSUE TITLE
[Config Support]: Reolink new docs for beta 7

### ISSUE THREAD

**Issue by angrycatmeowmeow** [blakeblackshear/frigate#5370]
### Describe the problem you are having

Curious if the `go2rtc `config controls the live view, and the `cameras:` config controls how Frigate connects to the cameras? I ask because the new recommended configs in the docs for Reolink cameras shows HTTP streams under go2rtc and RTSP streams in camera config, I plan on using HTTP for both. I'm not sure if I even need a go2rtc config in that scenario, but when I upgraded to beta4 it wouldn't start unless I added a go2rtc config. What is the benefit of adding main and sub streams to go2rtc?

### Version

0.12.0-66881EB

### Frigate config file

```yaml
go2rtc:
  ffmpeg:
    rtsp: "-fflags nobuffer -flags low_delay -stimeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i {input}"
  streams:
    Doorbell:
      - rtsp://user:password@reolink_ip:554/h264Preview_01_main
      - ffmpeg:Doorbell#audio=opus
    Crouton_Cam:
      - rtsp://user:password@reolink_ip:554/h264Preview_01_main
      - ffmpeg:Crouton_Cam#audio=opus
    Garage_East:
      - rtsp://user:password@reolink_ip:554/h264Preview_01_main
      - ffmpeg:Garage_East#audio=opus
    Garage_West:
      - rtsp://user:password@reolink_ip:554/h264Preview_01_main
      - ffmpeg:Garage_West#audio=opus
    Lounge:
      - rtsp://user:passwordZ@reolink_ip:554/h264Preview_01_main
      - ffmpeg:Lounge#audio=opus
    Front_Porch:
      - rtsp://user:password@reolink_ip:554/h264Preview_01_main
      - ffmpeg:Front_Porch#audio=opus

cameras:
  # Name of your camera
  Doorbell:
    ffmpeg:
      input_args: preset-http-reolink
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password
          roles:
            - detect
        - path: http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password
          roles:
            - record
    record:
      enabled: True
      events:
        retain:
          default: 2
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - bird
```

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Not using any hwaccel as I haven't found anything that works on an odroid n2+
addon 0.12.0-beta7 and integration v4.0.0-beta4
