### ISSUE TITLE
[Camera Support]: Repeated Crashes with Reolink Cameras (beta7 ... and previous betas)

### ISSUE THREAD

**Issue by horspiste** [blakeblackshear/frigate#5400]
### Describe the problem you are having

ffmpeg seerms to be crashing very often for my 3 reolink cameras.
The cameras are:
ENT: RLC-423
Gar and Gen: RLC-820A

For ENT: I am using the http method.
For Gar and Gen, I am using http for detect and rtsp for record, this seems to be a little more stable than only http.

The cameras are running the latest firmware generally available.

Thank you for looking into that.

### Version

0.12.0-66881EB

### Frigate config file

```yaml
# frigate-0.9.yml
logger:
  default: warning
detectors:
  coral_m2:
    type: edgetpu
    device: pci
database:
# note that this database path is remapped in docker-compose. 
  path: /db/frigate.db
mqtt:
  # Required: host name
  host: ubuntuvm2.local
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mqtt
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: 'password'
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
go2rtc:
  streams:
    ENT:
      - http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
#      - ffmpeg:ENT#audio=opus
    ENT_sub:
      - http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy
#      - ffmpeg:ENT_sub
    Gar:
      - rtsp://admin:password@192.168.2.150/h265Preview_01_main
#      - http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
      - ffmpeg:Gar#audio=opus
    Gar_sub:
      - http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy
#      - ffmpeg:Gar_sub
    Gen:
      - rtsp://admin:password@192.168.2.151/h265Preview_01_main
      - ffmpeg:Gen#audio=opus

    Gen_sub:
      - http://192.168.2.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy
#      - ffmpeg:Gen_sub

#ffmpeg:
#  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
objects:
  track:
    - person
    - car
    - truck
#    - bicycle
#    - motorcycle
#    - dog
#    - cat
#  filters:
#    person:
#      min_score: 0.4
#      threshold: 0.6
#     min_area: 1000
cameras:
  # Name of your camera
  ENT:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/ENT_sub?video=copy'
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: 'rtsp://127.0.0.1:8554/ENT?video=copy&audio=aac'
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 640
      height: 480
      fps: 5
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      crop: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      retain:
        default: 7
    objects:
      filters:
        person:
          mask:
            - 126,40,92,34,91,117,130,127
  Gar:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/Gar_sub?video=copy'
          input_args: preset-rtsp-restream
          roles:
           - detect
        - path: 'rtsp://127.0.0.1:8554/Gar?video=copy'
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 640
      height: 360
      fps: 5
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      crop: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      retain:
        default: 7
  Gen:
    ffmpeg:
      inputs:
        - path: 'rtsp://127.0.0.1:8554/Gen_sub?video=copy'
          input_args: preset-rtsp-restream
          roles:
           - detect
        - path: 'rtsp://127.0.0.1:8554/Gen?video=copy&audio=aac'
          input_args: preset-rtsp-restream
          roles:
            - record
    objects:
      track:
        - person
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        retain:
          default: 10
          mode: active_objects
    detect:
      width: 640
      height: 360
      fps: 5
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      crop: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      retain:
        default: 7
```

### Relevant log output

```shell
Frigate:
2023-02-06 07:30:12.827059008  [2023-02-06 07:30:12] frigate.app                    INFO    : Starting Frigate (0.12.0-66881eb)
2023-02-06 08:53:53.076785742  [2023-02-06 08:53:53] frigate.video                  ERROR   : Gar: Unable to read frames from ffmpeg process.
2023-02-06 08:53:53.076859222  [2023-02-06 08:53:53] frigate.video                  ERROR   : Gar: ffmpeg process is not running. exiting capture thread...
2023-02-06 08:54:03.006538550  [2023-02-06 08:54:03] frigate.video                  ERROR   : Gen: Unable to read frames from ffmpeg process.
2023-02-06 08:54:03.006856490  [2023-02-06 08:54:03] frigate.video                  ERROR   : Gen: Unable to read frames from ffmpeg process.
2023-02-06 08:54:03.007157081  [2023-02-06 08:54:03] frigate.video                  ERROR   : Gen: Unable to read frames from ffmpeg process.
2023-02-06 08:54:03.007267041  [2023-02-06 08:54:03] frigate.video                  ERROR   : Gen: ffmpeg process is not running. exiting capture thread...
2023-02-06 08:54:03.078250266  [2023-02-06 08:54:03] watchdog.Gar                   ERROR   : Ffmpeg process crashed unexpectedly for Gar.
2023-02-06 08:54:03.078320746  [2023-02-06 08:54:03] watchdog.Gar                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-06 08:54:03.171493666  [2023-02-06 08:54:03] frigate.video                  ERROR   : ENT: Unable to read frames from ffmpeg process.
2023-02-06 08:54:03.171495806  [2023-02-06 08:54:03] frigate.video                  ERROR   : ENT: Unable to read frames from ffmpeg process.
2023-02-06 08:54:03.171741957  [2023-02-06 08:54:03] frigate.video                  ERROR   : ENT: ffmpeg process is not running. exiting capture thread...
2023-02-06 08:54:13.007784821  [2023-02-06 08:54:13] watchdog.Gen                   ERROR   : Ffmpeg process crashed unexpectedly for Gen.
2023-02-06 08:54:13.007866021  [2023-02-06 08:54:13] watchdog.Gen                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-06 08:54:13.171578425  [2023-02-06 08:54:13] watchdog.ENT                   ERROR   : Ffmpeg process crashed unexpectedly for ENT.
2023-02-06 08:54:13.171655935  [2023-02-06 08:54:13] watchdog.ENT                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-06 08:55:33.177337116  [2023-02-06 08:55:33] watchdog.ENT                   ERROR   : No new recording segments were created for ENT in the last 120s. restarting the ffmpeg record process...

Go2rtc:
2023-02-06 07:30:12.335572235  07:30:12.335 INF go2rtc version 1.1.1 linux/amd64
2023-02-06 07:30:12.335789336  07:30:12.335 INF [api] listen addr=:1984
2023-02-06 07:30:12.336046606  07:30:12.336 INF [rtsp] listen addr=:8554
2023-02-06 07:30:12.336284246  07:30:12.336 INF [srtp] listen addr=:8443
2023-02-06 07:30:12.336450767  07:30:12.336 INF [webrtc] listen addr=:8555
2023-02-06 08:53:32.879959717  08:53:32.879 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="context deadline exceeded (Client.Timeout or context cancellation while reading body)" url=http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=o8hu7t4AyhkH#video=copy
2023-02-06 08:53:32.885077235  08:53:32.885 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="context deadline exceeded (Client.Timeout or context cancellation while reading body)" url=http://192.168.2.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=o8hu7t4AyhkH#video=copy
2023-02-06 08:53:33.006581524  08:53:33.006 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="context deadline exceeded (Client.Timeout or context cancellation while reading body)" url=http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=o8hu7t4AyhkH#video=copy
2023-02-06 08:53:33.010856771  08:53:33.010 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="context deadline exceeded (Client.Timeout or context cancellation while reading body)" url=http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=o8hu7t4AyhkH#video=copy#audio=copy#audio=opus
```

### FFprobe output from your camera

```shell
ENT
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 672,\n          \"width\": 896\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1920,\n          \"width\": 2560\n        }\n      ]\n    }\n  }\n]"

Gar
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 512,\n          \"width\": 896\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"height\": 2160,\n          \"width\": 3840\n        }\n      ]\n    }\n  }\n]"

Gen
"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 512,\n          \"width\": 896\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"height\": 2160,\n          \"width\": 3840\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  }\n]"
```

### Frigate stats

```json
{"ENT":{"camera_fps":5.1,"capture_pid":291,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":4960,"pid":285,"process_fps":5.1,"skipped_fps":0.0},"Gar":{"camera_fps":5.0,"capture_pid":292,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":4932,"pid":289,"process_fps":5.0,"skipped_fps":0.0},"Gen":{"camera_fps":5.0,"capture_pid":293,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":4958,"pid":290,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"1.0","mem":"4.2"},"112":{"cpu":"0.0","mem":"0.3"},"128":{"cpu":"0.0","mem":"0.2"},"129":{"cpu":"0.0","mem":"0.2"},"130":{"cpu":"0.0","mem":"0.2"},"131":{"cpu":"0.0","mem":"0.2"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"273":{"cpu":"0.0","mem":"2.0"},"279":{"cpu":"0.0","mem":"0.3"},"28":{"cpu":"0.0","mem":"0.0"},"280":{"cpu":"0.0","mem":"2.6"},"281":{"cpu":"0.3","mem":"2.3"},"285":{"cpu":"0.0","mem":"2.4"},"286":{"cpu":"0.0","mem":"1.0"},"289":{"cpu":"0.0","mem":"2.3"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.3","mem":"2.3"},"291":{"cpu":"0.0","mem":"2.1"},"292":{"cpu":"0.0","mem":"2.1"},"293":{"cpu":"0.3","mem":"2.1"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"0.7","mem":"0.5"},"308":{"cpu":"0.7","mem":"0.6"},"309":{"cpu":"0.0","mem":"0.4"},"31":{"cpu":"0.0","mem":"0.0"},"323":{"cpu":"0.0","mem":"0.4"},"325":{"cpu":"0.0","mem":"0.4"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"4932":{"cpu":"2.7","mem":"0.7"},"4958":{"cpu":"3.0","mem":"0.7"},"4960":{"cpu":"4.3","mem":"0.7"},"5060":{"cpu":"0.7","mem":"0.6"},"6062":{"cpu":"0.0","mem":"0.1"},"6070":{"cpu":"0.0","mem":"0.1"},"6073":{"cpu":"0.0","mem":"0.1"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"8.0","mem":"0.5"},"MiB":{"cpu":"2242.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral_m2":{"detection_start":0.0,"inference_speed":5.96,"pid":280}},"service":{"last_updated":1675692812,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":64.3,"mount_type":"tmpfs","total":67.1,"used":2.8},"/media/frigate/clips":{"free":1762389.8,"mount_type":"cifs","total":1967846.1,"used":205456.2},"/media/frigate/recordings":{"free":1762389.8,"mount_type":"cifs","total":1967846.1,"used":205456.2},"/tmp/cache":{"free":979.5,"mount_type":"tmpfs","total":1000.0,"used":20.5}},"temperatures":{"apex_0":55.3},"uptime":6200,"version":"0.12.0-66881eb"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

RLC-423, RLC-820A

### Any other information that may be helpful

Running Frigate in a docker-compose container on ubuntu.

**Comment by NickM-27** [comment]
This is somewhat expected due to Reolinks incorrect implementation of HTTP_FLV codec. go2rtc shows the error: `github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="context deadline exceeded (Client.Timeout or context cancellation while reading body)" url=http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=o8hu7t4AyhkH#video=copy`

you could try using ffmpeg instead and see if that works better for your particular cameras

```yaml
go2rtc:
  streams:
    ENT:
      - ffmpeg:http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus
    ENT_sub:
      - ffmpeg:http://192.168.2.149/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy
    Gar:
      - ffmpeg:rtsp://admin:password@192.168.2.150/h265Preview_01_main
      - ffmpeg:Gar#audio=opus
    Gar_sub:
      - ffmpeg:http://192.168.2.150/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy
    Gen:
      - ffmpeg:rtsp://admin:password@192.168.2.151/h265Preview_01_main
      - ffmpeg:Gen#audio=opus
    Gen_sub:
      - ffmpeg:http://192.168.2.151/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password#video=copy
```
