### ISSUE TITLE
[Support]: Recordings ending too soon

### ISSUE THREAD

**Issue by angrycatmeowmeow** [blakeblackshear/frigate#5405]
### Describe the problem you are having

Recordings are frequently ending while the object is still in the frame and moving. On a recent clip Frigate shows 1m43s but only provides 15s of footage.

### Version

0.12.0-66881EB

### Frigate config file

```yaml
go2rtc:
  streams:
    doorbell:
      - http://192.168.50.79/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password
      - ffmpeg:Doorbell#audio=opus
    doorbell_sub:
      - http://192.168.50.79/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password
   
cameras:
  # Name of your camera
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: True
      events:
        retain:
          default: 2
    motion:
      mask:
        - 640,0,640,37,0,36,0,0
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
        - package
        - bird
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink E1 Zoom
