### ISSUE TITLE
Events recording logic

### ISSUE THREAD

**Issue by Choo-lux** [blakeblackshear/frigate#5410]
### Describe the problem you are having

I'm getting odd event timings.  

Event: 12:02:25 AM (2 hours 49 minutes 40 seconds).
Object detection snapshot is at 02:50am.
_**The recording starts at 01:00am and is 11min long but finishes at 02:50am**_

This is on HassOs and Ubuntu docker. Any way

### Version

beta 12 and prior

### Frigate config file

```yaml
go2rtc:
 streams:
    front:
     - rtsp://192.168.0.4:554/stream1
     - ffmpeg:front#audio=opus
    front_sub:
     - rtsp://192.168.0.4:554/stream2

cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      width: 1024
      height: 576
      fps: 1

snapshots:
    enabled: True
record:
  enabled: True
  events:
    pre_capture: 15
    post_capture: 30
    retain:
      default: 10
      objects:
        person: 20
```

### Relevant log output

```shell
no errors
```

### FFprobe output from your camera

```shell
multiple different cams same result
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

a few types
