### ISSUE TITLE
[Config Support]: correct tag for beta versions?

### ISSUE THREAD

**Issue by andreklug** [blakeblackshear/frigate#5416]
### Describe the problem you are having

I would like to try 0.12.0-beta7, currently have 0.11.0 running through docker compose. 

What's the correct entry for the image:blakeblackshear/frigate:??? line? I tried several variations but always get a "manifest unknown" error.
I see that tags for beta images of older versions were provided, but not for 0.12.0-beta. Does this mean they do not exist?

### Version

NA

### Frigate config file

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.12.0-beta7
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
...
```

### Relevant log output

```shell
andre@frigate:/opt/frigate$ docker compose up -d
[+] Running 0/1
 ⠿ frigate Error                                                           1.5s
Error response from daemon: manifest for blakeblackshear/frigate:0.12.0-beta not found: manifest unknown: manifest unknown
andre@frigate:/opt/frigate$
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
