### ISSUE TITLE
[Config Support]: Live stream on webui is set to low res

### ISSUE THREAD

**Issue by StephanGR** [blakeblackshear/frigate#5422]
### Describe the problem you are having

Hello, 

I've enabled both stream of my HIKVision camera one for HD and another one for SD

But when I go to WebUI of Frigate the channel 102 (AKA SD stream) is displayed instead of 101

Have you any advice of this particular problem ?

Thanks

### Version

0.11.1-2eada21

### Frigate config file

```yaml
cameras:
  xxx:
    ffmpeg:
      inputs:
        # HIGH RESOLUTION Stream
        - path: rtsp://xxx:xxx@wireguard/Streaming/Channels/101
          roles:
            - record
        # LOW RESOLUTION Stream
        - path: rtsp://xxx:xxx@wireguard/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 10
```

### Relevant log output

```shell
No logs
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
