### ISSUE TITLE
[Support]: MQTT Unable to publish to events

### ISSUE THREAD

**Issue by Valinwolf** [blakeblackshear/frigate#5434]
### Describe the problem you are having

I keep getting "Unable to publish to events: client is not connected" in the log. I was seeing these exact messages at random on 0.11.0, just less frequent. I have Mosquitto v2.0.14 set up on a VPS with a passwd file using mosquitto_passwd. There are 2 users in the passwd file. I have tried using a local install of MQTT as well, but I had the exact same issue. I know that my issue is not a firewall/port forward issue as I have another client using the server without issues. 

[Gist with logs](https://gist.github.com/Valinwolf/f2f95c174cdbfbe3988de288fc7bc836) - IPs and host names have been sensored, as well as usernames and passwords. I replaced them with descriptions of what it was.

### Version

0.12.0-66881eb

### Frigate config file

```yaml
mqtt:
  host: EXTERNAL_MQTT_HOSTNAME
  port: EXTERNAL_MQTT_PORT
  topic_prefix: frigate
  user: MQTT_USER
  password: MQTT_PASSWORD
  stats_interval: 60
birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  mode: objects
go2rtc:
  streams:
    front:
      - rtsp://CAMERA_USER:CAMERA_PASS@CAMERA_IP:554/streaming/channels/101 # censored
  webrtc:
    candidates:
      - FRIGATE_HOST_LAN_IP:8555 # censored
      - stun:8555
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects
snapshots:
  enabled: True
  height: 1440
  retain:
    default: 60
cameras:
  front:
    zones:
      front_yard:
        coordinates: 2090,454,2560,717,2560,1440,0,1440,0,720
        objects:
          - person
    record:
      events:
        required_zones:
          - front_yard
    snapshots:
      required_zones:
        - front_yard
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 2560
      height: 1440
    mqtt:
      enabled: True
      height: 1440
      quality: 100
    ui:
      order: 0
      dashboard: True
```

### Relevant log output

```shell
See gist link provided in the main section.
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.5-0+deb11u1+rpt3 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt3 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x557eda5870] max delay reached. need to consume packet
[rtsp @ 0x557eda5870] RTP: missed 143 packets
[h264 @ 0x557eda87d0] out of range intra chroma pred mode
[h264 @ 0x557eda87d0] error while decoding MB 25 36
[h264 @ 0x557eda87d0] concealing 8664 DC, 8664 AC, 8664 MV errors in I frame
Input #0, rtsp, from 'rtsp://CAMERA_USER:CAMERA_PASSWORD@CAMERA_IP:554/streaming/channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 2560x1440, 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.2"},"129":{"cpu":"0.0","mem":"0.2"},"130":{"cpu":"0.0","mem":"0.2"},"131":{"cpu":"0.0","mem":"0.2"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"272":{"cpu":"0.0","mem":"2.1"},"278":{"cpu":"0.0","mem":"0.3"},"279":{"cpu":"0.0","mem":"2.7"},"28":{"cpu":"0.0","mem":"0.0"},"280":{"cpu":"1.7","mem":"2.7"},"284":{"cpu":"1.7","mem":"3.1"},"285":{"cpu":"0.0","mem":"1.9"},"286":{"cpu":"12.3","mem":"3.2"},"288":{"cpu":"0.0","mem":"1.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"537":{"cpu":"45.5","mem":"2.0"},"548":{"cpu":"0.0","mem":"0.1"},"78":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"4.0","mem":"0.5"},"92":{"cpu":"0.7","mem":"3.8"},"99":{"cpu":"0.0","mem":"0.3"},"MiB":{"cpu":"3038.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"load","mem":"average:"}},"detection_fps":0.3,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":127.65,"pid":279}},"front":{"camera_fps":0.0,"capture_pid":286,"detection_enabled":1,"detection_fps":0.3,"ffmpeg_pid":537,"pid":284,"process_fps":16.8,"skipped_fps":0.0},"service":{"last_updated":1675901340,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":257.8,"mount_type":"tmpfs","total":268.4,"used":10.7},"/media/frigate/clips":{"free":1855511.9,"mount_type":"ext4","total":1967846.1,"used":12297.5},"/media/frigate/recordings":{"free":1855511.9,"mount_type":"ext4","total":1967846.1,"used":12297.5},"/tmp/cache":{"free":999.5,"mount_type":"tmpfs","total":1000.0,"used":0.5}},"temperatures":{},"uptime":702,"version":"0.12.0-66881eb"}}
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

LTS CMIP1042W-28MA, fw v5.7.0 build 220113

### Any other information that may be helpful

Frigate Host Info:
```
Hardware: Raspberry PI 4 Model B
OS: Raspbian 11/Bullseye
Docker Command: docker run -d   --name frigate   --restart=unless-stopped   --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --shm-size=256m   -v /etc/localtime:/etc/localtime:ro -v /mnt/frigate/config:/config -v /mnt/frigate/storage:/media/frigate -v /etc/localtime:/etc/localtime:ro   -e FRIGATE_RTSP_PASSWORD='CHOSEN_PASSWORD' --network host ghcr.io/blakeblackshear/frigate:0.12.0-beta7
```

VPS Mosquitto Host Info:
```
OS: Fedora 34
MQTT Broker: Mosquitto 2.0.14
Hardware: 4GB ram, 2 vCPUs
Host: Digital Ocean
```

I have not been able to acquire a coral device yet as they have been out of stock, but I needed my security system up and running. Detection seems to be working well on CPU right now, so until someone gets a reasonably priced coral in, I will get it added into the system. I'm not paying $200+ for a $60 product. Not that this was relevant to the issue.... I just thought I would preempt any comments about my lack of coral device...
