### ISSUE TITLE
[HW Accel Support]: GPU is passed through and shows in dashboard - CPU usage still high

### ISSUE THREAD

**Issue by Sgt-Ogre** [blakeblackshear/frigate#5435]
### Describe the problem you are having

I am having issues with getting GPU acceleration working. I have the device passed through in my docker-compose, i can access all the streams, and i have the config preset set properly. The GPU even shows in the dashboard. However when i pull up the streams in VLC i can clearly see that each one is taking ~20% CPU usage when i start the stream which tells me it is transcoding the stream with the CPU most likely. I know its not the motion detection as i can see those spikes as well when cars drive in front of the cameras.

I check radeon top and the GPU usage at the top never goes above about 5-8% so i dont think that it is utilizing it for the stream. 

### Version

0.12.0-66881eb

### Frigate config file

```yaml
mqtt:
  host: 10.0.50.10
  user: admin
  password: pass
    
record:
  enabled: True
  retain:
    days: 2
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format 
    - yuv420p
    
  
go2rtc:
  streams:    
    driveway_cam_detect: 
      - rtsp://admin:password@10.0.30.201:554/Streaming/Channels/2
      
    doorbell_cam_detect: 
      - rtsp://admin:password@10.0.230.103:554/cam/realmonitor?channel=1&subtype=1
      
    sideyard_cam_detect: 
      - rtsp://admin:password@10.0.30.202:554/Streaming/Channels/2
      
    backyard_cam_detect: 
      - rtsp://admin:password@10.0.30.200:554/h264Preview_01_sub
      
    driveway_cam_4k: 
      - rtsp://admin:password@10.0.30.201:554/Streaming/Channels/1
      
    doorbell_cam_4k: 
      - rtsp://admin:password@10.0.230.103:554/cam/realmonitor?channel=1&subtype=0
      
    sideyard_cam_4k: 
      - rtsp://admin:password@10.0.30.202:554/Streaming/Channels/1
      
    backyard_cam_4k: 
      - rtsp://admin:password@10.0.30.200:554/
      
    driveway_cam_1080: 
      - ffmpeg:rtsp://127.0.0.1:8554/driveway_cam_4k#video=h264#width=1920
      
    doorbell_cam_1080: 
      - rtsp://127.0.0.1:8554/doorbell_cam_4k
      
    sideyard_cam_1080: 
      - ffmpeg:rtsp://127.0.0.1:8554/sideyard_cam_4k#video=h264#width=1920
      
    backyard_cam_1080: 
      - ffmpeg:rtsp://127.0.0.1:8554/backyard_cam_4k#video=h264#width=1920
  
    
cameras:
  driveway_cam_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_cam_detect
          roles: 
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_cam_4k
          roles: 
            - record
    objects:
      track:
        - person
        
    motion:
      mask:
        - 474,82,856,98,856,0,0,0,0,64,0,128
            
            
    rtmp:
      enabled: false
      
    detect:
      width: 856
      height: 480
      
    snapshots:
      enabled: True
            
  sideyard_cam_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.30.202:554/Streaming/Channels/2
          roles: 
            - detect
        - path: rtsp://admin:password@10.0.30.202:554/Streaming/Channels/1
          roles: 
            - record
            
    objects:
      track:
        - person
        
    motion:
      mask:
        - 856,0,856,173,484,106,433,0
        - 856,480,856,241,424,480
            
    rtmp:
      enabled: false
      
    detect:
      width: 856
      height: 480
      
    snapshots:
      enabled: True
            
  doorbell_cam_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.230.103:554/cam/realmonitor?channel=1&subtype=1
          roles: 
            - detect
        - path: rtsp://admin:password@10.0.230.103:554/cam/realmonitor?channel=1&subtype=0
          roles: 
            - record
    objects:
      track:
        - person    
        
    rtmp:
      enabled: false
      
    detect:
      width: 768
      height: 576
      
    snapshots:
      enabled: True
      
  backyard_cam_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@10.0.30.200:554/h264Preview_01_sub
          roles: 
            - detect
        - path: rtsp://admin:password@10.0.30.200:554/
          roles: 
            - record
            
    objects:
      track:
        - person
            
    motion:
      mask:
        - 205,65,358,49,640,79,640,0,0,0,0,110,76,78,116,75,129,120,157,165,198,150
        - 640,360,640,221,486,160,346,184,0,312,0,360
        
    rtmp:
      enabled: false
      
    detect:
      width: 640
      height: 360
      
    snapshots:
      enabled: True
      
    
detectors:
  cpu1:
    type: cpu
    num_threads: 6
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    network_mode: "host"
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta7
    shm_size: "512mb" 
    devices:
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/frigate/config.yml:/config/config.yml
      - /home/ubuntu/frigate/clips:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Restream
      - "1984:1984" # go2rtc API
      - "8555:8555" # WebRTC
    environment:
      LIBVA_DRIVER_NAME: "radeonsi"
```

### Relevant log output

```shell
2023-02-08 17:19:28.930158899  [2023-02-08 17:19:28] frigate.app                    INFO    : Starting Frigate (0.12.0-66881eb)
2023-02-08 17:19:28.958780559  [2023-02-08 17:19:28] peewee_migrate                 INFO    : Starting migrations
2023-02-08 17:19:28.962319243  [2023-02-08 17:19:28] peewee_migrate                 INFO    : There is nothing to migrate
2023-02-08 17:19:28.975065923  [2023-02-08 17:19:28] frigate.app                    INFO    : Output process started: 424
2023-02-08 17:19:28.975916162  [2023-02-08 17:19:28] detector.cpu1                  INFO    : Starting detection process: 423
2023-02-08 17:19:28.978416735  [2023-02-08 17:19:28] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-02-08 17:19:28.980650867  [2023-02-08 17:19:28] frigate.app                    INFO    : Camera processor started for driveway_cam_frigate: 428
2023-02-08 17:19:28.985401285  [2023-02-08 17:19:28] frigate.app                    INFO    : Camera processor started for sideyard_cam_frigate: 429
2023-02-08 17:19:28.990141717  [2023-02-08 17:19:28] frigate.app                    INFO    : Camera processor started for doorbell_cam_frigate: 430
2023-02-08 17:19:28.994742677  [2023-02-08 17:19:28] frigate.app                    INFO    : Camera processor started for backyard_cam_frigate: 431
2023-02-08 17:19:28.998791616  [2023-02-08 17:19:28] frigate.app                    INFO    : Capture process started for driveway_cam_frigate: 433
2023-02-08 17:19:29.002746830  [2023-02-08 17:19:29] frigate.app                    INFO    : Capture process started for sideyard_cam_frigate: 436
2023-02-08 17:19:29.007562270  [2023-02-08 17:19:29] frigate.app                    INFO    : Capture process started for doorbell_cam_frigate: 441
2023-02-08 17:19:29.012809046  [2023-02-08 17:19:29] frigate.app                    INFO    : Capture process started for backyard_cam_frigate: 445
```

### FFprobe output from your camera

```shell
driveway:

"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"display_aspect_ratio\": \"4:3\",\n          \"height\": 480,\n          \"width\": 640\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"display_aspect_ratio\": \"16:9\",\n          \"height\": 2160,\n          \"width\": 3840\n        }\n      ]\n    }\n  }\n]"

sideyard:

"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"display_aspect_ratio\": \"4:3\",\n          \"height\": 480,\n          \"width\": 640\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"bit_rate\": \"64000\",\n          \"codec_long_name\": \"PCM mu-law / G.711 mu-law\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"display_aspect_ratio\": \"16:9\",\n          \"height\": 2160,\n          \"width\": 3840\n        }\n      ]\n    }\n  }\n]"

doorbell:

"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 576,\n          \"width\": 720\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"bit_rate\": \"64000\",\n          \"codec_long_name\": \"PCM A-law / G.711 A-law\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"15/1\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1920,\n          \"width\": 2560\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"bit_rate\": \"64000\",\n          \"codec_long_name\": \"PCM A-law / G.711 A-law\"\n        }\n      ]\n    }\n  }\n]"

backyard:

"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 360,\n          \"width\": 640\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.265 / HEVC (High Efficiency Video Coding)\",\n          \"height\": 2160,\n          \"width\": 3840\n        },\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"AAC (Advanced Audio Coding)\"\n        }\n      ]\n    }\n  }\n]"
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

total 4 cameras - RLC-820A, AD410, 2x C800

### Any other information that may be helpful

Running under Ubuntu 22.04 on a Lenovo Mini PC with a Ryzen 3400GE
