### ISSUE TITLE
[HW Accel Config Support]: 

### ISSUE THREAD

**Issue by Choo-lux** [blakeblackshear/frigate#5443]
### Describe the problem you are having

Prior to adding **#hardware** to the new go2rtc stream my old _**gen 8 intel Atom**_ showed 8% gpu usage and 70% CPU (7cams with coral).

Now it shows 15-20% gpu usage. CPU still 70%.

1. Is HW Accel useless on a old onboard gpu?
2. On system page often a cams detect CPU% hits 20%. I'm assuming this is normal on a slow PC even with a Coral. 

![Untitled-1](https://user-images.githubusercontent.com/5474756/217974010-b16b7a37-624a-4a47-9bec-e2c36b99c7a4.jpg)

### Version

beta 12

### Frigate config file

```yaml
environment_vars:
    LIBVA_DRIVER_NAME: i965
  ffmpeg:
    hwaccel_args: preset-vaapi
    output_args:
            record: preset-record-generic-audio-copy
  go2rtc:
   streams:
      front_entrance:
       - rtsp://192.168.1.175:7447/61316ffce4b0a72521fde882_0#hardware
       - ffmpeg:front_entrance#audio=opus
      front_entrance_sub:
       - rtsp://192.168.1.175:7447/61316ffce4b0a72521fde882_1
  cameras:
    front_entrance:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/front_entrance_sub?video=h264
            input_args: preset-rtsp-restream
            roles:
              - detect
          - path: rtsp://127.0.0.1:8554/front_entrance?video=h264&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
      detect:
        width: 1024
        height: 576
        fps: 5
```

### Relevant log output

```shell
na
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2
