### ISSUE TITLE
[Config Support]: Frigate MQTT password must be cleartext in frigate-config, cannot be stored in env file

### ISSUE THREAD

**Issue by hornet-dev** [blakeblackshear/frigate#5452]
### Describe the problem you are having

I can put my camera passwords in a Docker env file and pass them to Frigate for use in the config file, but when I try to do the same with the MQTT password, Frigate cannot resolve the password.

Long story short: 

mqtt:
  host: mqtt.host.com
  user: mqtt
  password: MyRealPassword

works in my Frigate config, but:

mqtt:
  host: mqtt.host.com
  user: mqtt
  password: {FRIGATE_MQTT_PASSWORD}

errors out as seen below

### Version

0.12.0-66881eb

### Frigate config file

```yaml
mqtt:
    host: mqtt.myhost.com
    user: mqtt
    password: MyMQTTPassword # want to use {FRIGATE_MQTT_PASSWORD} here, too
  
  cameras:
    garage:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
              - detect
      detect:
        width: 1280
        height: 720
  
    driveway:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/driveway?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        width: 1280
        height: 720
  
    backyard:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/backyard?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/backyard_sub?video=copy
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        width: 1280
        height: 720
      objects:
        filters:
          person:
            threshold: 0.78
  
    doorbell:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/doorbell?video=copy&audio=aac
            input_args: preset-rtsp-restream
            roles:
              - record
              - detect
      detect:
        width: 1280
        height: 720
  
  go2rtc:
    streams:
      garage:
        - rtsp://admin:{FRIGATE_GARAGE_RTSP_PASSWORD}@garage.cams.myhost.com:554/h264Preview_01_sub
        - "ffmpeg:garage#audio=opus"
      doorbell:
        - rtsp://admin:{FRIGATE_DOORBELL_RTSP_PASSWORD}@doorbell.cams.myhost.com:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
        - "ffmpeg:doorbell#audio=opus"
      backyard:
        - rtsp://admin:{FRIGATE_BACKYARD_RTSP_PASSWORD}@backyard.cams.myhost.com:554/Streaming/Channels/101
        - "ffmpeg:backyard#audio=opus"
      backyard_sub:
        - rtsp://admin:{FRIGATE_BACKYARD_RTSP_PASSWORD}@backyard.cams.myhost.com:554/Streaming/Channels/102
      driveway:
        - rtsp://admin:{FRIGATE_DRIVEWAY_RTSP_PASSWORD}@driveway.cams.myhost.com:554/cam/realmonitor?channel=1&subtype=0
        - "ffmpeg:driveway#audio=opus"
      driveway_sub:
        - rtsp://admin:{FRIGATE_DRIVEWAY_RTSP_PASSWORD}@driveway.cams.myhost.com:554/cam/realmonitor?channel=1&subtype=1
    log:
      level: debug
      exec: debug
      rtsp: debug
      streams: debug
      webrtc: debug
  
    webrtc:
      candidates:
        - nvr.myhost.com:8555
  
  detectors:
    coral:
      type: edgetpu
      device: usb
  
  snapshots:
    enabled: True
    timestamp: True
    bounding_box: True
  
  ffmpeg:
    hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
    output_args:
      record: preset-record-generic-audio-aac
  
  record:
    enabled: True
    retain:
      days: 21
      # mode: motion
    events:
      retain:
        default: 21
        # mode: active_objects
        mode: motion
  
  objects:
    track:
      - person
      - cat
      - dog
      - bicycle
      - motorcycle
      - bus
    filters:
      person:
        # Optional: minimum decimal percentage for tracked object's computed score to be considered
        # a true positive (default: shown below)
        threshold: 0.75
```

### Relevant log output

```shell
2023-02-11 17:44:53.963929400  [2023-02-11 17:44:53] frigate.app                    INFO    : Starting Frigate (0.12.0-66881eb)
2023-02-11 17:44:53.974828237  *************************************************************
2023-02-11 17:44:53.974830864  *************************************************************
2023-02-11 17:44:53.974834077  ***    Your config file is not valid!                     ***
2023-02-11 17:44:53.974836196  ***    Please check the docs at                           ***
2023-02-11 17:44:53.974837722  ***    https://docs.frigate.video/configuration/index     ***
2023-02-11 17:44:53.974847998  *************************************************************
2023-02-11 17:44:53.974849451  *************************************************************
2023-02-11 17:44:53.974851177  ***    Config Validation Errors                           ***
2023-02-11 17:44:53.974852565  *************************************************************
2023-02-11 17:44:53.974941731  1 validation error for FrigateConfig
2023-02-11 17:44:53.974943919  mqtt -> password
2023-02-11 17:44:53.974945396    str type expected (type=type_error.str)
2023-02-11 17:44:53.975512323  Traceback (most recent call last):
2023-02-11 17:44:53.975514590    File "/opt/frigate/frigate/app.py", line 357, in start
2023-02-11 17:44:53.975515970      self.init_config()
2023-02-11 17:44:53.975517402    File "/opt/frigate/frigate/app.py", line 81, in init_config
2023-02-11 17:44:53.975518713      user_config = FrigateConfig.parse_file(config_file)
2023-02-11 17:44:53.975520087    File "/opt/frigate/frigate/config.py", line 1038, in parse_file
2023-02-11 17:44:53.975521364      return cls.parse_obj(config)
2023-02-11 17:44:53.975522760    File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
2023-02-11 17:44:53.975524044    File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
2023-02-11 17:44:53.975525367  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2023-02-11 17:44:53.975527311  mqtt -> password
2023-02-11 17:44:53.975528544    str type expected (type=type_error.str)
2023-02-11 17:44:53.975544465  
2023-02-11 17:44:53.975545924  *************************************************************
2023-02-11 17:44:53.975547140  ***    End Config Validation Errors                       ***
2023-02-11 17:44:53.975555123  *************************************************************
Service Frigate exited with code 1 (by signal 0)
```

### Frigate stats

```json
{"backyard":{"camera_fps":5.1,"capture_pid":305,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":313,"pid":293,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"22.8"},"1":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"0.0","mem":"0.1"},"122":{"cpu":"0.0","mem":"0.0"},"123":{"cpu":"0.0","mem":"0.0"},"124":{"cpu":"0.0","mem":"0.0"},"125":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"276":{"cpu":"0.0","mem":"1.1"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"0.1"},"283":{"cpu":"0.0","mem":"1.2"},"285":{"cpu":"1.0","mem":"1.1"},"289":{"cpu":"0.3","mem":"1.1"},"29":{"cpu":"0.0","mem":"0.0"},"292":{"cpu":"0.3","mem":"1.1"},"293":{"cpu":"0.3","mem":"1.1"},"294":{"cpu":"0.0","mem":"0.1"},"295":{"cpu":"0.3","mem":"1.1"},"296":{"cpu":"1.0","mem":"1.1"},"297":{"cpu":"0.0","mem":"0.1"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"4.3","mem":"0.3"},"301":{"cpu":"1.0","mem":"1.1"},"304":{"cpu":"0.0","mem":"0.1"},"305":{"cpu":"1.0","mem":"1.1"},"308":{"cpu":"2.7","mem":"0.3"},"309":{"cpu":"0.7","mem":"1.1"},"31":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"0.0","mem":"0.1"},"313":{"cpu":"2.7","mem":"0.3"},"318":{"cpu":"0.0","mem":"0.1"},"321":{"cpu":"2.0","mem":"0.2"},"322":{"cpu":"4.3","mem":"0.3"},"323":{"cpu":"2.3","mem":"0.2"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"553":{"cpu":"0.3","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"4.3","mem":"0.1"},"94":{"cpu":"1.3","mem":"2.5"},"MiB":{"cpu":"13655.5","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":1.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.25,"pid":283}},"doorbell":{"camera_fps":5.0,"capture_pid":309,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":322,"pid":295,"process_fps":5.0,"skipped_fps":0.0},"driveway":{"camera_fps":5.0,"capture_pid":301,"detection_enabled":1,"detection_fps":1.7,"ffmpeg_pid":308,"pid":292,"process_fps":5.0,"skipped_fps":0.0},"garage":{"camera_fps":5.1,"capture_pid":296,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":300,"pid":289,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"1.32 %","mem":"- %"}},"service":{"last_updated":1676138052,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":126.7,"mount_type":"tmpfs","total":134.2,"used":7.5},"/media/frigate/clips":{"free":396413.1,"mount_type":"nfs","total":2470396.8,"used":1948343.3},"/media/frigate/recordings":{"free":396413.1,"mount_type":"nfs","total":2470396.8,"used":1948343.3},"/tmp/cache":{"free":25108.6,"mount_type":"overlay","total":33501.8,"used":6658.4}},"temperatures":{},"uptime":55,"version":"0.12.0-66881eb"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

Installed in privileged LXC on Proxmox host (Intel i5-7500t)

**Comment by NickM-27** [comment]
```
mqtt -> password
    str type expected (type=type_error.str)
```

you have to put it in quotes

```yaml
mqtt:
  host: mqtt.host.com
  user: mqtt
  password: "{FRIGATE_MQTT_PASSWORD}"
```
