### ISSUE TITLE
Optimize threading+latency of ffmpeg configuration

### ISSUE THREAD

**Issue by charlesmunger** [blakeblackshear/frigate#5459]
I've been playing around with the new presets (specifically `preset-http-reolink`, and diffed it versus the configuration I was using on version 0.11.

Resulting detect command lines (preset one first):
```
ffmpeg -hide_banner -loglevel warning -user_agent FFmpeg Frigate/0.12.0-27a31e7 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i http://10.0.0.71/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password=<redacted> -r 7 -s 640x480 -f rawvideo -pix_fmt yuv420p pipe:
ffmpeg -hide_banner -loglevel warning -flags low_delay -threads 1 -fflags nobuffer+genpts -strict experimental -rw_timeout 5000000 -f live_flv -i http://10.0.0.71/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password=<redacted> -r 7 -s 640x480 -avioflags direct -threads 1 -fps_mode vfr -muxdelay 0 -flags low_delay -flush_packets 1 -f rawvideo -pix_fmt yuv420p pipe:
```

I configured the same camera twice (motion etc elided):
```yaml
  chimney:
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: http://10.0.0.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record
        - path: http://10.0.0.71/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect

  chimney2:
    ffmpeg:
      inputs:
        - path: http://10.0.0.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_CAM_PASSWORD}
          roles:
            - record 
          input_args:
            - -flags
            - low_delay+genpts
            - -analyzeduration
            - "1"
            - -probesize
            - "32"
            - -threads
            - "1"
            - -strict
            - experimental
            - -rw_timeout
            - '5000000'
            - -f
            - live_flv
        - path: http://10.0.0.71/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=frigate&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
          input_args:
            - -flags
            - low_delay
            - -threads
            - "1"
            - -fflags
            - nobuffer+genpts
            - -strict
            - experimental
            - -rw_timeout
            - '5000000'
            - -f
            - live_flv
      output_args:
        detect: -avioflags direct -threads 1 -fps_mode vfr -muxdelay 0 -flags low_delay -flush_packets 1 -f rawvideo -pix_fmt yuv420p
```

In both the birds-eye-view and when detecting events, `chimney2` is quicker. It also appears to use slightly less CPU. Here's the timestamp difference for the detected event:
```
chimney-1676170460.172301-xkz9st.jpg
chimney2-1676170460.02309-bhv0co.jpg
```
So approx. 149ms improvement which looks very close to one frame at 7 fps. That implies that 5 fps substreams might see a larger improvement.

## Threads configuration
ffmpeg will create thread pools for parallel processing that are not actually beneficial for Frigate's use case. I think it's very unlikely that frigate users will have both fewer cameras than cores *and* sufficient CPU load from decoding detect streams that any one stream more than saturates a single core. Inspecting `/proc/` shows that `chimney`'s ffmpeg detect process has 13 threads, and `chimney2`'s has 1. 

## vsync/fps_mode
By default, ffmpeg will choose between CFR (dupe/drop) and VFR (drop or passthrough). The `-r` command to set framerate will either duplicate or drop frames to keep the rate constant; but there is no value in ever duplicating a frame on the detect stream. vfr mode will drop extra frames or pass through but not duplicate. Would be worth looking into `-fpsmax` rather than `-r` for reducing framerate of detect streams - since many cameras offer low-fps substreams anyway.

## Buffering/delay options
I just went through the docs and picked literally everything that promised to reduce delay. For detect streams, timestamps don't matter, stuttering doesn't matter, all that matters (to me!) is minimizing delay as much as possible for previews and events. Since we're writing to a pipe, I'm not concerned about any small buffer issues.

These in particular might be worthwhile to add to the birdseye stream.

## genpts/live_flv
See discussion on #1467
