### ISSUE TITLE
Allow Environment variables on all MQTT settings

### ISSUE THREAD

**Issue by distante** [blakeblackshear/frigate#5460]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use environment variables on the config.yml mqtt settings so that I can define them on my portainer setup and make it easier to move from one MQTT instance to another with the same setup. 

**Describe the solution you'd like**
allow 
```
mqtt:
  host: '{FRIGATE_MOSQUITO_HOST}'
  user: '{FRIGATE_MOSQUITO_USER'
  password: '{FRIGATE_MOSQUITO_PASSWORD}'
```

**Describe alternatives you've considered**
Nothing besides create an own script that build all the variables I have, which sounds like reimplement what is already possible for the password field.
