### ISSUE TITLE
[HW Accel Support]: 

### ISSUE THREAD

**Issue by mikerasmussen1** [blakeblackshear/frigate#5467]
### Describe the problem you are having

Trying to decode and encode camera streams with NVIDIA GPU to offload CPU.  

First of all, I have seen a few different things on this.  Is HW accelerate encoding supported?

Went through a lot of pain to get the NVIDIA drivers up and running and working in Docker,  I verified it works for decoding, but when I tried adding the necessary arguments for encoding with GPU I cannot get it to work,

### Version

011.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.86.52
  port: 1883
  user: frigate
  password: XXXXXXX
detectors:
  coral:
    type: edgetpu
    device: usb
    ffmpeg:
cameras:
    NewFront:
        ffmpeg:
            hwaccel_args: -hwaccel cuda -hwaccel_output_format cuda  #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            output_args: 
                record:  -f segment -segment_time 10 -segment_format mp4 -strftime 1 -c:a copy -c:v h264_nvenc 
            inputs:
                - path: rtsp://admin:deadbeef11@192.168.86.94:554/cam/realmonitor?channel=1&subtype=1
        record:
            enabled: True
            retain:
                days: 60
                mode: all
            events:
                retain:
                    default: 180
                    mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "br"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False
#environment_vars:
#  LIBVA_DRIVER_NAME_JELLYFIN: i965
#    LIBVA_DRIVER_NAME: i965
#    LIBVA_DRIVER_NAME: radeonsi
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1
              capabilities: [gpu]
    #command: ffmpeg -encoders | grep cuvid
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modifi>
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instruc>
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/hassio/homeassistant/frigate.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
```

### Relevant log output

```shell
frigate  | 2023-02-12 12:43:05.761216901  192.168.86.52 - - [12/Feb/2023:12:43:05 -0700] "GET /api/stats HTTP/1.1" 200 1870 "-" "HomeAssistant/2023.2.3 aiohttp/3.8.1 Python/3.10" "-"
frigate  | 2023-02-12 12:43:07.634354217  [2023-02-12 12:43:07] watchdog.NewFront              ERROR   : Ffmpeg process crashed unexpectedly for NewFront.
frigate  | 2023-02-12 12:43:07.634374000  [2023-02-12 12:43:07] watchdog.NewFront              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-02-12 12:43:07.637240601  [2023-02-12 12:43:07] ffmpeg.NewFront.detect         ERROR   : [mp4 @ 0x557b45cdab00] Could not find tag for codec pcm_alaw in stream #1, codec not currently supported in container
frigate  | 2023-02-12 12:43:07.638305724  [2023-02-12 12:43:07] ffmpeg.NewFront.detect         ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
frigate  | 2023-02-12 12:43:07.640278440  [2023-02-12 12:43:07] ffmpeg.NewFront.detect         ERROR   : Error initializing output stream 0:0 -- 
frigate  | 2023-02-12 12:43:09.097340572  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.098778707  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.098789676  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.099589329  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.100304318  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.100821165  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.102015593  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.106330151  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.112088415  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.114206011  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.115515339  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.116611380  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
frigate  | 2023-02-12 12:43:09.118827343  [2023-02-12 12:43:09] frigate.video                  ERROR   : NewFront: Unable to read frames from ffmpeg process.
```

### FFprobe output from your camera

```shell
ffprobe version N-109851-ge506ea3ce1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared
  libavutil      58.  0.100 / 58.  0.100
  libavcodec     60.  1.100 / 60.  1.100
  libavformat    60.  2.100 / 60.  2.100
  libavdevice    60.  0.100 / 60.  0.100
  libavfilter     9.  1.100 /  9.  1.100
  libswscale      7.  0.100 /  7.  0.100
  libswresample   4.  9.100 /  4.  9.100
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Wyze
