### ISSUE TITLE
[Support]: Frigate card error after a few seconds of live footage, can't browse clips

### ISSUE THREAD

**Issue by leotrost** [blakeblackshear/frigate#5472]
### Describe the problem you are having

After a few seconds of live viewing the stream on any of the cameras, this error appears.

![image](https://user-images.githubusercontent.com/115377500/218361233-eceb21f9-8db8-4837-98d6-9a2bc20b04c0.png)

Additionally, if I go to Media and try to browse for a recording, I get this error

![image](https://user-images.githubusercontent.com/115377500/218361446-41b4d7c3-3cb9-4de4-a443-53057ae46b5c.png)

HACS integration version 3.0.0
I am able to browse clips in the Frigate webui, as well as view the live streams of all the cameras.

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: 10.254.3.13
  port: 1883
  user: leotrost
  password: myname
  stats_interval: 60
ffmpeg:
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
  #  - -analyzeduration
  #  - 1000M
  #  - -probesize
  #  - 1000M
    - -vsync
    - drop
    - -use_wallclock_as_timestamps
    - '1'
#    - -rtsp_transport udp
#  output_args:
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  output_args:
    detect: -dn -an -f rawvideo -pix_fmt yuv420p
    record: -dn -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:v copy -codec:a aac -b:a 24k -ac 1 
    rtmp: -c copy -f flv
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.21/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - cat
    detect:
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
    zones:
      canopy:
        coordinates: 1811,1080,1920,867,1292,681,1100,396,493,310,483,785,838,1080
      fire_pit:
        coordinates: 1341,693,1852,842,1876,749,1487,664
      porch:
        coordinates: 582,1080,0,1080,0,570,332,535
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          dog: 60
          cat: 60
  backporch:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.22/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - cat
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          dog: 60
          cat: 60
  livingroom:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.23/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    zones:
      cat_tree:
        coordinates: 1540,295,1560,87,1453,47,1329,169,1321,428,1440,473,1506,424
      cat_wall:
        coordinates: 908,0,620,0,654,549,907,432
      downstars_hall:
        coordinates: 367,103,535,97,642,653,451,692
      living_room:
        coordinates: 425,621,1567,337,1920,568,1920,1080,526,1080
      stairs:
        coordinates: 0,1080,436,1080,186,0,0,0
    motion:
      mask:
        - 1920,180,1920,508,1561,285,1592,29
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          cat: 60
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.20/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          mask:
            - 218,693,219,458,498,486,498,865,289,854
            - 1125,502,1458,486,1382,332,1246,205,1120,199
            - 1828,486,1861,421,1804,355,1726,352,1656,446,1692,485
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    zones:
      front_yard:
        coordinates: 475,1080,315,871,510,836,508,728,1171,712,1327,1080
      front_steps:
        coordinates: 1385,1080,1571,1080,1366,674,1210,683
      our_cars:
        coordinates: 595,89,1207,102,1312,276,1126,309,1111,433,582,448
      parking_lot:
        coordinates: 1278,0,0,0,0,109,1596,178,1519,64
      street:
        coordinates: 1920,0,1920,285,1920,370,1470,0
      3226-3228_cars:
        coordinates: 1266,122,1462,475,1920,442,1590,184
      3222_cars:
        coordinates: 0,442,0,76,514,43,436,489
      3222_yard:
        coordinates: 1864,531,1920,690,1594,939,1404,613
      sidewalk:
        coordinates: 440,661,204,630,161,477,1889,465,1600,186,1788,221,1920,349,1920,539,1716,580
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          dog: 60
          cat: 60
          car: 60
  upstairs_hallway:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.24/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    zones:
      hallway:
        coordinates: 709,44,421,738,385,1080,812,1080,836,973,1027,980,1041,1080,1584,1080,1519,746,1426,309,1142,0
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          cat: 60
  bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.25/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    zones:
      bed:
        coordinates: 1321,450,1230,213,1245,54,758,68,782,175,671,450
      bed_right:
        coordinates: 1389,0,1586,93,1476,477,1412,630,1301,638,1344,473,1245,202
      bed_left:
        coordinates: 739,227,735,0,611,0,390,0,535,572,683,601,652,442
      bed_main:
        coordinates: 508,615,256,1080,1920,1080,1920,586
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          cat: 60
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.26/live
          roles:
            - detect
            - record
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p -vf transpose=1
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -vf transpose=1
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
    objects:
      track:
        - person
        - cat
      filters:
        cat:
          mask:
            - 0,646,264,689,133,1920,0,1920
            - 1080,1182,1080,317,961,306,951,366,850,352
            - 72,444,173,276,307,287,230,447
        person:
          mask:
            - 44,205,646,131,575,358,0,406
            - 1080,1182,1080,317,961,306,951,366,850,352
            - 72,444,173,276,307,287,230,447
    detect:
      enabled: True
      width: 1080
      height: 1920
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          cat: 60
  dining_room:
    ffmpeg:
      inputs:
        - path: rtsp://leotrost:myname@10.254.3.27/live
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - cat
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: motion
    zones:
      dining_room_table:
        coordinates: 1514,0,1379,476,1431,667,1589,268,1920,1080,248,1080,439,472,422,409,476,220,433,0
    motion:
      mask:
        - 0,1080,0,0,427,0,459,175,156,1080
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 60
          cat: 60
```

### Relevant log output

```shell
No log error output
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://leotrost:@10.254.3.20/live':
  Metadata:
    title           : Session streamed by the WYZE Media Server
    comment         : live
  Duration: N/A, start: 0.000313, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 19.83 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: pcm_alaw, 16000 Hz, 1 channels, s16, 128 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Wyze Cam v3

### Any other information that may be helpful

I have attempted to run this with the latest 11.1 with the same issue, and with 4.0Beta 3 on the Hass integration with the same issue. Hass is connecting to frigate over localhost, both containers using host networking
