### ISSUE TITLE
[Support]: Birdseye restream corrupt?

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#5479]
### Describe the problem you are having

https://user-images.githubusercontent.com/29582865/218519159-7c949648-9f80-4659-b22b-5890e0a1e755.mp4

### Version

0.12 beta 8

### Frigate config file

```yaml
birdseye:
  enabled: true
  restream: true
  width: 1280
  height: 720
  mode: continuous
```

### Relevant log output

```shell
I don't see any.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

This is not new, I observed this since the first 0.12 beta that added restream capabilities to birdseye.

**Comment by NickM-27** [comment]
What hardware acceleration are you running?

**Comment by felipecrs** [comment]
```
ffmpeg:
  hwaccel_args: preset-vaapi

environment_vars:
  LIBVA_DRIVER_NAME: i965
```
