### ISSUE TITLE
Frigate: Failed to start add on

### ISSUE THREAD

**Issue by pkatuin** [blakeblackshear/frigate#5480]
### Describe the problem you are having

I tryed installing Frigate today, but after several attempts it keeps failing to start the add on. 

upon start up i get this message:
**Failed to start add on** 
Image blakeblackshear/frigate:0.11.1 does not exist for addon_ccab4aaf_frigate

when i look in the logs of home assistant this is the only thing i see about Frigate.
Failed to to call /addons/ccab4aaf_frigate/start - Image blakeblackshear/frigate:0.11.1 does not exist for addon_ccab4aaf_frigate

Current version: 0.11.1 
installed the hacs integration V3.0.0 later tryed V4.0.0 Beta but that also doesnt seem to make any difference.

### Version

x

### Frigate config file

```yaml
mqtt:  
  host: 192.168.2.14
  user: **user**
  password: **password**
  

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://login:password@192.168.2.108:554/cam/realmonitor?channel=4&subtype=0
          roles: 
            - detect
    width: 1920
    height: 1080
    fps: 5
    
detectors: 
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
x
```

### FFprobe output from your camera

```shell
x
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua
