### ISSUE TITLE
[HW Accel Support]: 

### ISSUE THREAD

**Issue by mikerasmussen1** [blakeblackshear/frigate#5483]
### Describe the problem you are having

trying to offload from CPU to do decoding in GPU.  Installed GTX-750Ti.  Installed nvidia drivers and container toolkit according to instructions here:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

nvidia driver version is 525.85.12

The system actually seems to running much SLOWER after moving to NVIDIA (like big delays going from page to page in homeassistant that did not happen before moving to nvidia HW Accel).  CPU is at 100% all the time. ffmpeg is listed as top CPU processes.

running nvidia-smi from INSIDE the docker image looks like this:

# nvidia-smi
Mon Feb 13 14:10:45 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 33%   29C    P0     1W /  38W |    428MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

Running from OUTSIDE the docker looks like this:

### Version

11

### Frigate config file

```yaml
mqtt:
  host: 192.168.86.47
  port: 1883
  user: frigate
  password: XXXXXXXX
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
    HotTubPad:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            inputs:
              - path: rtsp://192.168.86.47:8554/hot-tub-pad # <----- Update for your camera
                roles:
                - detect
                - record
        detect:
          #enabled: False
          width: 1920 # <---- update for your camera's resolution
          height: 1080 # <---- update for your camera's resolution
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
    RVPad:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            inputs:
              - path: rtsp://192.168.86.47:8554/rv-pad
                roles:
                #- detect
                - record
        detect:
          #enabled: False
          width: 1920 # <---- update for your camera's resolution
          height: 1080 # <---- update for your camera's resolution
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
    BackDeck:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            inputs:
              - path: rtsp://192.168.86.47:8554/back-porch
                roles:
                #- detect
                - record
        detect:
          #enabled: False
          width: 1920 # <---- update for your camera's resolution
          height: 1080 # <---- update for your camera's resolution
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
    BackYard:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            inputs:
              - path: rtsp://192.168.86.47:8554/back-yard-cam
                roles:
                #- detect
                - record
        detect:
          #enabled: False
          width: 1920 # <---- update for your camera's resolution
          height: 1080 # <---- update for your camera's resolution
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
    NewFront:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            inputs:
              - path: rtsp://admin:deadbeef11@192.168.86.94:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - detect
              - path: rtsp://admin:deadbeef11@192.168.86.94:554/cam/realmonitor?channel=1&subtype=0 # <----- Add high res stream
                roles:
                  - record
        detect:
          #enabled: False
          width: 704
          height: 408 
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
    MainFront:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            inputs:
              - path: rtsp://XXXXXXXX@192.168.86.90:554/cam/realmonitor?channel=1&subtype=1
                roles:
                  - detect
              - path: rtsp://XXXXXXXX@192.168.86.90:554
                roles:
                  - record
        detect:
          #enabled: False
          width: 704 # <---- update for your camera's resolution
          height: 408 # <---- update for your camera's resolution
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
    FrontDoor:
        ffmpeg:
            hwaccel_args: -c:v h264_cuvid #-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
            input_args:
              - -avoid_negative_ts
              - make_zero
              - -fflags
              - nobuffer
              - -flags
              - low_delay
              - -strict
              - experimental
              - -fflags
              - +genpts+discardcorrupt
              - -r
              - "15" # <---- adjust depending on your desired frame rate from the mjpeg image
              - -use_wallclock_as_timestamps
              - "1"
            inputs:
              - path: https://stream-ue1-charlie.dropcam.com:443/nexus_aac/b84d5d9f55a94a92b66afc38b1368b8f/chunklist_w516121983.m3u8?public=lx8suTOAgf
                roles:
                - detect
                - record
        detect:
          #enabled: False
          width: 1152
          height: 864
          fps: 5
        record: # <----- Enable recording
          enabled: True
          retain:
            days: 30
            mode: all
          events:
            retain:
                default: 90
                mode: active_objects
        objects:
            track:
                - person
                - car
                - truck
                - cat
                - dog
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
    #          #device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1
              capabilities: [gpu]
    #command: ffmpeg -encoders | grep cuvid
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modifi>
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instruc>
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/hassio/homeassistant/frigate.yml:/config/config.yml:ro
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      #- "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "frigatepass"
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      LIBVA_DRIVER_NAME: i965
```

### Relevant log output

```shell
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2023-02-13 13:34:44] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
frigate  | Starting migrations
frigate  | [2023-02-13 13:34:44] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2023-02-13 13:34:44] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2023-02-13 13:34:44] frigate.app                    INFO    : Output process started: 213
frigate  | [2023-02-13 13:34:44] detector.coral                 INFO    : Starting detection process: 212
frigate  | [2023-02-13 13:34:44] frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate  | [2023-02-13 13:34:44] frigate.mqtt                   INFO    : Turning on snapshots for NewFront via mqtt
frigate  | [2023-02-13 13:34:44] ws4py                          INFO    : Using epoll
frigate  | [2023-02-13 13:34:44] frigate.mqtt                   INFO    : Turning on snapshots for FrontDoor via mqtt
frigate  | [2023-02-13 13:34:44] frigate.app                    INFO    : Camera processor started for HotTubPad: 216
frigate  | [2023-02-13 13:34:44] frigate.mqtt                   INFO    : Turning on snapshots for BackYard via mqtt
frigate  | [2023-02-13 13:34:45] frigate.mqtt                   INFO    : Turning on snapshots for MainFront via mqtt
frigate  | [2023-02-13 13:34:45] frigate.mqtt                   INFO    : Turning on snapshots for BackDeck via mqtt
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Camera processor started for RVPad: 223
frigate  | [2023-02-13 13:34:45] frigate.mqtt                   INFO    : Turning on snapshots for RVPad via mqtt
frigate  | [2023-02-13 13:34:45] frigate.mqtt                   INFO    : Turning on snapshots for HotTubPad via mqtt
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Camera processor started for BackDeck: 224
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Camera processor started for BackYard: 225
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Camera processor started for NewFront: 227
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Camera processor started for MainFront: 228
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Camera processor started for FrontDoor: 231
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for HotTubPad: 232
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for RVPad: 236
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for BackDeck: 237
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for BackYard: 244
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for NewFront: 250
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for MainFront: 257
frigate  | [2023-02-13 13:34:45] frigate.app                    INFO    : Capture process started for FrontDoor: 265
frigate  | [2023-02-13 13:34:46] ws4py                          INFO    : Using epoll
frigate  | [2023-02-13 13:34:47] frigate.edgetpu                INFO    : TPU found
```

### FFprobe output from your camera

```shell
Ran this in the frigate docker:

ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
rtsp://192.168.86.47:8554/: Server returned 400 Bad Request

---don't understand this as it is coming up in Frigate????
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

wyze through docker-wyze-bridge
