### ISSUE TITLE
[Config Support]: go2rtc ffmpeg device source issue

### ISSUE THREAD

**Issue by Valinwolf** [blakeblackshear/frigate#5484]
### Describe the problem you are having

The problem seems to be very close to #5137, if not identical. I am running Frigate 0.12.0-b7 on a RPi4B, with ffmpeg version 4.3.5 installed from the Debian repos. I tried the configs in that issue with no dice. Any ideas?

### Version

0.12.0-66881eb

### Frigate config file

```yaml
mqtt:
  host: 127.0.0.1
  port: 1884
  topic_prefix: frigate
  user: frigate
  password: Bo7sfaWcNGXsdKYc
  stats_interval: 60
birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  mode: continuous
  restream: true
go2rtc:
  logs:
    format: text
    exec: trace
  streams:
    entry:
      - ffmpeg:device?video=0&resolution=1920x1080#video=h264
  webrtc:
    candidates:
      - HOST_IP:8555
      - stun:8555
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects
snapshots:
  enabled: True
  height: 1440
  retain:
    default: 60
cameras:
  entry:
    record:
      enabled: false
    snapshots:
      enabled: false
    detect:
      enabled: false
    mqtt:
      enabled: false
    ui:
      order: 1
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entry
          input_args: preset-rtsp-restream
```

### Relevant log output

```shell
2023-02-13 18:26:58.102854008  18:26:58.102 INF go2rtc version 1.1.1 linux/arm64
2023-02-13 18:26:58.103988767  18:26:58.103 INF [api] listen addr=:1984
2023-02-13 18:26:58.105454502  18:26:58.105 INF [rtsp] listen addr=:8554
2023-02-13 18:26:58.106898737  18:26:58.106 INF [srtp] listen addr=:8443
2023-02-13 18:26:58.107912665  18:26:58.107 INF [webrtc] listen addr=:8555
2023-02-13 18:27:03.386546096  18:27:03.386 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:device?video=0&resolution=1280x720#video=h264
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
I don't think they're related. In this case go2rtc is failing. You should enable trace logs for the exec module to get more info. Also you should show your docker CLI command.

**Comment by Valinwolf** [comment]
> I don't think they're related. In this case go2rtc is failing. You should enable trace logs for the exec module to get more info.

I thought that's what this segment was supposed to do?
```
go2rtc:
  logs:
    format: text
    exec: trace
```

> Also you should show your docker CLI command.

```
docker run -d   --name frigate   --restart=unless-stopped   --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --shm-size=256m   -v /etc/localtime:/etc/localtime:ro -v /mnt/frigate/config:/config -v /mnt/frigate/storage:/media/frigate -v /etc/localtime:/etc/localtime:ro --device /dev/video0 -e FRIGATE_RTSP_PASSWORD='CENSORED' --network host ghcr.io/blakeblackshear/frigate:0.12.0-beta7
```
