### ISSUE TITLE
[Support]: ffmpeg crashes and does not recover

### ISSUE THREAD

**Issue by day1118** [blakeblackshear/frigate#5485]
### Describe the problem you are having

Frigate shows `No frames have been received, check error logs for all cameras`. Restarting Frigate resolves the issue.

The logs say `ffmpeg process is not running`, but I cannot determine why it is crashing, or why it does not recover without me manually restarting the Frigate container.

### Version

0.12.0-beta8

### Frigate config file
<details><summary>expand</summary>

```yaml
mqtt:
  host: mosquitto
cameras:
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.169:8554/driveway
          roles:
            - detect
            - record
            
    rtmp:
      enabled: False 
    detect:
      width: 1920 
      height: 1080 
    motion:
      mask:
        - 1920,1080,1920,323,1920,0,1017,0,471,0,640,174,673,551,837,1080
        - 0,147,65,145,74,181,252,201,174,694,0,1032
    zones:
      driveway:
        coordinates: 837,1080,684,585,653,340,444,359,328,420,0,820,0,1080
      road:
        coordinates: 1089,245,1092,0,0,0,0,355,667,299,652,249
    objects:
      track:
        - person
        - car
        - bicycle
        - dog
        - bird
        - cat
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.169:8554/backyard
          roles:
            - detect
            - record
            
    rtmp:
      enabled: False 
    detect:
      width: 1920 
      height: 1080 
    motion:
      mask:
        - 0,0,627,0,847,116,788,361,903,439,925,557,712,761,494,856,354,986,0,982
        - 1291,0,1351,135,1465,98,1605,134,1677,241,1830,288,1844,359,1767,377,1447,341,1203,420,1075,423,1076,356,578,150,610,0,953,0
        - 1089,459,1137,492,1122,528,1096,577,1028,560,999,497,1036,453
    zones:
      lawn:
        coordinates: 0,1080,1592,1080,993,712,918,726,859,687,403,714,0,924
      path:
        coordinates: 1590,1080,1845,1080,1139,753,1156,613,980,636,978,668,867,683,926,724,998,723
      garage:
        coordinates: 1838,1080,1920,1080,1920,403,1440,342,1159,433,1142,758
      jenny:
        coordinates: 1765,385,1920,334,1920,0,0,0,0,459,1205,427,1446,345
    objects:
      track:
        - person
        - bird
        - cat

  backFence:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.169:8554/back-fence
          roles:
            - detect
            - record
            
    rtmp:
      enabled: False 
    detect:
      width: 1920 
      height: 1080 
    motion:
      mask:
        
        - 683,802,776,778,764,550,817,530,876,592,937,554,884,442,751,314,589,370,442,435,540,513
        - 550,135,592,0,805,0,1175,0,1239,42,1281,152,1220,230,1210,332,1191,459,1104,484,1006,397,916,373,810,429,653,343
        - 1175,246,1269,214,1377,128,1505,159,1591,203,1716,209,1774,287,1725,449,1726,635,1561,653,1412,626,1283,476,1210,368
        - 1920,0,1920,321,1780,324,1625,230,1397,160,1379,0
        - 1728,623,1851,570,1816,881,1573,953,1569,788,1711,734
    objects:
      track:
        - cat
        - person

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects


record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects
```
</details>

### Relevant log output

```shell
frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
frigate.video                  ERROR   : frontyard: Unable to read frames from ffmpeg process.
frigate.video                  ERROR   : frontyard: ffmpeg process is not running. exiting capture thread...
2023-02-14 11:18:08.624489443  172.29.0.3 - - [14/Feb/2023:11:18:08 +1100] "GET /api/stats HTTP/1.1" 200 2502 "-" "HomeAssistant/2023.2.3 aiohttp/3.8.1 Python/3.10" "-"
watchdog.backFence             ERROR   : Ffmpeg process crashed unexpectedly for backFence.
watchdog.backFence             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ffmpeg.backFence.detect        ERROR   : [rtsp @ 0x5561ae0a7f00] method DESCRIBE failed: 404 Not Found
ffmpeg.backFence.detect        ERROR   : rtsp://192.168.0.169:8554/back-fence: Server returned 404 Not Found
frigate.video                  ERROR   : backFence: Unable to read frames from ffmpeg process.
frigate.video                  ERROR   : backFence: ffmpeg process is not running. exiting capture thread...
2023-02-14 11:18:16.620812313  172.29.0.3 - - [14/Feb/2023:11:18:16 +1100] "GET /api/stats HTTP/1.1" 200 2439 "-" "HomeAssistant/2023.2.3 aiohttp/3.8.1 Python/3.10" "-"
watchdog.backyard              ERROR   : Ffmpeg process crashed unexpectedly for backyard.
watchdog.backyard              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 9272861, current: 9272861; changing to 9272862. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 9292544, current: 9292544; changing to 9292545. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 9337357, current: 9337357; changing to 9337358. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 26203473, current: 26203473; changing to 26203474. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 29188749, current: 29188749; changing to 29188750. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 29196551, current: 29196551; changing to 29196552. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 29218525, current: 29218525; changing to 29218526. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 29250456, current: 29250456; changing to 29250457. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Non-monotonous DTS in output stream 0:0; previous: 29250457, current: 29250457; changing to 29250458. This may result in incorrect timestamps in the output file.
ffmpeg.backyard.detect         ERROR   : [segment @ 0x55f33bdd3600] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
watchdog.frontyard             ERROR   : Ffmpeg process crashed unexpectedly for frontyard.
watchdog.frontyard             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ffmpeg.frontyard.detect        ERROR   : [segment @ 0x55a9049df8c0] Non-monotonous DTS in output stream 0:0; previous: 10307915, current: 10307915; changing to 10307916. This may result in incorrect timestamps in the output file.
ffmpeg.frontyard.detect        ERROR   : [segment @ 0x55a9049df8c0] Non-monotonous DTS in output stream 0:0; previous: 10307916, current: 10307916; changing to 10307917. This may result in incorrect timestamps in the output file.
ffmpeg.frontyard.detect        ERROR   : [segment @ 0x55a9049df8c0] Non-monotonous DTS in output stream 0:0; previous: 10343071, current: 10343071; changing to 10343072. This may result in incorrect timestamps in the output file.
ffmpeg.frontyard.detect        ERROR   : [segment @ 0x55a9049df8c0] Non-monotonous DTS in output stream 0:0; previous: 12251080, current: 12251080; changing to 12251081. This may result in incorrect timestamps in the output file.
ffmpeg.frontyard.detect        ERROR   : [segment @ 0x55a9049df8c0] Non-monotonous DTS in output stream 0:0; previous: 13453185, current: 13453185; changing to 13453186. This may result in incorrect timestamps in the output file.
```

### FFprobe output from your camera
<details><summary>expand</summary>

```shell
/opt/frigate# ffprobe rtsp://192.168.0.169:8554/driveway
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55bd69acf140] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://192.168.0.169:8554/driveway':
  Metadata:
    title           : Stream
  Duration: N/A, start: 0.224744, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
```
</details>

### Frigate stats
<details><summary>expand</summary>

```json
{
    "backFence": {
        "camera_fps": 0,
        "capture_pid": 294,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 3648,
        "pid": 289,
        "process_fps": 0,
        "skipped_fps": 0
    },
    "backyard": {
        "camera_fps": 5.1,
        "capture_pid": 292,
        "detection_enabled": 1,
        "detection_fps": 0,
        "ffmpeg_pid": 299,
        "pid": 288,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "cpu_usages": {
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "17": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "93": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "104": {
            "cpu": "2.0",
            "mem": "1.7"
        },
        "112": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "129": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "130": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "131": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "132": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "274": {
            "cpu": "0.0",
            "mem": "0.5"
        },
        "280": {
            "cpu": "0.3",
            "mem": "0.1"
        },
        "281": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "282": {
            "cpu": "7.7",
            "mem": "0.7"
        },
        "286": {
            "cpu": "8.7",
            "mem": "0.3"
        },
        "287": {
            "cpu": "0.7",
            "mem": "0.7"
        },
        "288": {
            "cpu": "1.0",
            "mem": "0.8"
        },
        "289": {
            "cpu": "0.0",
            "mem": "0.6"
        },
        "290": {
            "cpu": "3.7",
            "mem": "0.6"
        },
        "291": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "292": {
            "cpu": "3.3",
            "mem": "0.6"
        },
        "294": {
            "cpu": "0.3",
            "mem": "0.6"
        },
        "299": {
            "cpu": "17.0",
            "mem": "0.5"
        },
        "305": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "308": {
            "cpu": "5.7",
            "mem": "0.3"
        },
        "820": {
            "cpu": "19.0",
            "mem": "0.6"
        },
        "3657": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.1"
        },
        "MiB": {
            "cpu": "2742.3",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 0.8,
    "detectors": {
        "cpu": {
            "detection_start": 0,
            "inference_speed": 143.41,
            "pid": 281
        }
    },
    "frontyard": {
        "camera_fps": 5,
        "capture_pid": 290,
        "detection_enabled": 1,
        "detection_fps": 0.8,
        "ffmpeg_pid": 820,
        "pid": 287,
        "process_fps": 5.1,
        "skipped_fps": 0
    },
    "service": {
        "last_updated": 1676337109,
        "latest_version": "0.11.1",
        "storage": {
            "/dev/shm": {
                "free": 59.3,
                "mount_type": "tmpfs",
                "total": 67.1,
                "used": 7.8
            },
            "/media/frigate/clips": {
                "free": 354692.5,
                "mount_type": "overlay",
                "total": 982820.9,
                "used": 578128.4
            },
            "/media/frigate/recordings": {
                "free": 354692.5,
                "mount_type": "overlay",
                "total": 982820.9,
                "used": 578128.4
            },
            "/tmp/cache": {
                "free": 998.4,
                "mount_type": "tmpfs",
                "total": 1000,
                "used": 1.6
            }
        },
        "temperatures": {},
        "uptime": 3068,
        "version": "0.12.0-27a31e7"
    }
}
```

</details>

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Wyze v3

### Any other information that may be helpful

- Camera backFence is currently offline/unplugged
- Stream is RTSP coming from [docker-wyze-bridge](https://github.com/mrlt8/docker-wyze-bridge)
- Docker image is `ghcr.io/blakeblackshear/frigate:0.12.0-beta8`. I saw the same thing on `beta7`, but I don't think I saw it on `0.11.1`
- Full logs are [here](https://gist.github.com/day1118/271e7adf7aa123b1f55056ce859b95d2)

In addition, it is clear that Frigate knows something is wrong, but I cannot see any mqtt event that could be used to detect/notify when this occurs. The camera state still says `recording` - Is there a way to detetct this from the mqtt events?
