### ISSUE TITLE
[Support]: H.265 Can't Stream to Web UI

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5509]
### Describe the problem you are having

I have a smattering of Hikvision cameras, some H.264, some H.265. With all the H.264 cameras, I've got them setup going through go2rtc, WebRTC is set up and working, and restreaming them for Frigate. BUT, the H.265 cameras are having various issues. I have them set up to still use H.264 for the substream to reduce decoding requirements for motion and stuff, but the main stream is H.265 (with H.265+ turned OFF).

In the WebUI in Chrome, MSE and JSMPEG work just fine.  WebRTC view the timer starts going, but nothing ever displays. I can't find any browser errors or problems with the web socket connections.

In Safari, MSE view will load the first frame at full resolution, but then says "error" down in the area where playback controls normally would be. Web inspector is showing continual binary messages are still coming through. The WebRTC view behaves the same as Chrome.

In Safari on iOS, MSE is not supported, and WebRTC behaves the same as the others.

There are zero errors in any of the Frigate, Go2RTC, or Nginx logs.

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

ui:
  live_mode: webrtc
  use_experimental: false

go2rtc:
  streams:
    pantry: rtsp://admin:secret@192.168.x.x/Streaming/Channels/101
    pantry_sub: rtsp://admin:secret@192.168.x.x/Streaming/Channels/102
  webrtc:
    candidates:
      - frigate.x.network:8555
      - 192.168.x.x:8555

detect:
  fps: 6
  max_disappeared: 18
  stationary:
    interval: 12

objects:
  track:
    - person
    - dog
    - cat

cameras:
  pantry:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pantry?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pantry_sub?video=copy&audio=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
    record:
      enabled: true
    rtmp:
      enabled: false
    detect:
      width: 640
      height: 360
    motion:
      mask:
        - 28,26,234,26,234,35,28,35 # timestamp
    zones:
      mud_zone:
        coordinates: 492,0,395,0,337,146,397,193
      pantry_zone:
        coordinates: 455,251,296,360,194,360,82,134,277,59
    snapshots:
      enabled: true
    objects:
      filters:
        person:
          min_area: 3350
          mask:
            - 291,360,486,176,533,214,415,360
```

### Relevant log output

```shell
Nothing relevant.
```

### FFprobe output from your camera

```shell
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)", "display_aspect_ratio": "16:9", "height": 2160, "width": 3840 }, { "avg_frame_rate": "0/0", "bit_rate": "64000", "codec_long_name": "PCM mu-law / G.711 mu-law" } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "6/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "display_aspect_ratio": "16:9", "height": 360, "width": 640 } ] } } ]
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.9"},"1":{"cpu":"0.0","mem":"0.0"},"458":{"cpu":"0.7","mem":"0.7"},"585":{"cpu":"1.7","mem":"0.4"}},"pantry":{"camera_fps":6.0,"capture_pid":562,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":585,"pid":458,"process_fps":6.0,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2183G0-IU 2.8mm

### Any other information that may be helpful

Events are detected, and the recorded clips record and play back just fine.
