### ISSUE TITLE
[Support]: how to set 24h format for event display

### ISSUE THREAD

**Issue by andreklug** [blakeblackshear/frigate#5517]
### Describe the problem you are having

Although correct, all the timestamps for events are displayed in AM / PM. I would like to see the time in 24h format. 

Is there a way to change this?

<img width="362" alt="image" src="https://user-images.githubusercontent.com/13343357/219491573-be05a7c2-8b1a-424c-bf62-eac54f51fd13.png">

### Version

0.12.0-66881EB

### Frigate config file

```yaml
mqtt:
  host: mosquitto.home
  port: 8883
  topic_prefix: 'frigate'
  client_id: 'frigate'
  user: 'frigate-nvr'
  password: 'xxx'
  tls_ca_certs: /ssl/xxx
  tls_insecure: false


detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3
#  cpu1:
#    type: cpu
#    num_threads: 3
#    model:
#      path: "/custom_model.tflite"
      
database:
  path: /database/frigate.db

logger:
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

rtmp:
  enabled: False

go2rtc:
#  ffmpeg:
#    rtsp: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i {input}"
  streams:
    eingang: 
      - rtsp://andre:xxx:554/Streaming/channels/101/
      - "ffmpeg:eingang#audio=pcm_mulaw"
    eingang_sub:
      - rtsp://andre:xxx:554/Streaming/channels/102/
      #- "ffmpeg:eingang_sub#audio=opus"

cameras: #        - path: rtsp://andre:xxx/Streaming/Channels/101
  eingang:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      # hwaccel_args:
        #- -c:v
        #- h264_v4l2m2mhwaccel_args:
        #- -hwaccel
        #- vaapi
        #- -hwaccel_device
        #  - /dev/dri/card0  #renderD128
        #- -c:v
        #- h264_v4l2m2m
      inputs:
        #- path: rtsp://andre:xxx:554/Streaming/channels/101/
        - path: rtsp://127.0.0.1:8554/eingang
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        #- path: rtsp://andre:xxx:554/Streaming/channels/102/
        - path: rtsp://127.0.0.1:8554/eingang_sub
          input_args: preset-rtsp-restream
          roles:
            - rtmp
        #    - detect
          
    detect:
      max_disappeared: 20
      width: 640
      height: 480
      fps: 15
    objects:
      track:
        - person
        - bicycle
        - bird
        - cat
        - dog
        - handbag
        - tie
        - backpack
        - suitcase
        - skis
        - baseball bat
        - bottle
        - knife
      #filters:
      #  person:
      #    min_score: 0.6
      #    threshold: 0.75
    snapshots:
      enabled: true
      retain:
        default: 100
        objects:
          person: 365 # Per object retention days
    record:
        enabled: true
    rtmp:
        enabled: true
    live:
      height: 720
      quality: 8
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
