### ISSUE TITLE
[HW Accel Support]: Hardware acceleration problems with Radeon HD 3470 and HiWatch cameras

### ISSUE THREAD

**Issue by rogovst** [blakeblackshear/frigate#5520]
### Describe the problem you are having

Hi. 
I have several HiWatch(Hikvision) cameras DS-I200D
Have some problems with the hardware acceleration with Radeon HD 3470.
<details>
  <summary>When I enable it, I do see the load in radeontop, </summary>

![Screenshot_2023-02-16_13-57-30](https://user-images.githubusercontent.com/29466094/219499656-17a66c21-c93d-45af-9e42-fd13a03e33a6.png)
</details>

<details>
  <summary>but in the UI cameras show green or black screen.</summary>

  ![Screenshot_2023-02-16_13-57-55](https://user-images.githubusercontent.com/29466094/219499694-a798c56d-dbcd-4043-b57f-08c25b845537.png)

  ![Screenshot_2023-02-16_14-18-14](https://user-images.githubusercontent.com/29466094/219499799-e36923de-1340-4537-9d89-34182a637207.png)
</details>

Videocard:
`01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV620 PRO [Radeon HD 3470]`

Vainfo:
```
root@499f3589a3c9:/opt/frigate# vainfo 
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Mesa Gallium driver 22.3.3 for AMD RV620 (DRM 2.50.0 / 5.15.0-60-generic, LLVM 15.0.6)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc```


### Version

0.12.0-beta8

### Frigate config file

```yaml
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

mqtt:
  host: mqtt_server

birdseye:
  enabled: True

detect:
  width: 640
  height: 480
  max_disappeared: 50
  stationary:
    threshold: 150

motion:
  contour_area: 20

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
    - bicycle

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: motion
  events:
    pre_capture: 30
    post_capture: 15
    required_zones: []
    retain:
      default: 10
      mode: active_objects
      objects:
        person: 15

ffmpeg:
  global_args:
    -loglevel warning
  input_args: "-avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1"
  hwaccel_args: 
    -hwaccel vaapi 
    -hwaccel_device /dev/dri/renderD128
    -hwaccel_output_format yuv420p

cameras:
  cam_1:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxxx@192.168.0.69:554/streaming/channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxx:xxxx@192.168.0.69:554/streaming/channels/101/
          roles:
            - record
  cam_2:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.0.68:554/streaming/channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxx:xxxx@192.168.0.68:554/streaming/channels/101/
          roles:
            - record
  cam_3:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.0.70:554/streaming/channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxx:xxxx@192.168.0.70:554/streaming/channels/101/
          roles:
            - record
  cam_4:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@192.168.0.170:554/streaming/channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxx:xxxx@192.168.0.170:554/streaming/channels/101/
          roles:
            - record
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    depends_on:
      - mosquitto    
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta8
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/volume/local/frigate/config:/config
      - /srv/volume/local/frigate/storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    links:
      - "mosquitto:mqtt_server"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      LIBVA_DRIVER_NAME: "radeonsi"
```

### Relevant log output

```shell
No errors in logs
```

### FFprobe output from your camera

```shell
Substream:
$ ffprobe  -hide_banner  -rtsp_transport tcp rtsp://xxxx:xxxx@192.168.0.70:554/streaming/channels/102/
Input #0, rtsp, from 'rtsp://xxxx:xxxx@192.168.0.70:554/streaming/channels/102/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 640x480, 25 tbr, 90k tbn, 180k tbc

Main stream:
$ ffprobe  -hide_banner  -rtsp_transport tcp rtsp://xxxx:xxxx@192.168.0.70:554/streaming/channels/101/
Input #0, rtsp, from 'rtsp://xxxx:xxxx@192.168.0.70:554/streaming/channels/101/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.040000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 25 tbr, 90k tbn, 180k tbc
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

HiWatch DS-I200(D)
