### ISSUE TITLE
[Support]: Some HTTP API endpoints are not found

### ISSUE THREAD

**Issue by BenDavidson90** [blakeblackshear/frigate#5530]
### Describe the problem you are having

If I go to `http://frigate_ip/api/portal`, the API returns me the mjpeg stream like stated in [docs](https://docs.frigate.video/integrations/api/#get-apicamera_name).

According to the [docs](https://docs.frigate.video/integrations/api/#get-apicamera_namelabelthumbnailjpg), `http://frigate_ip/api/portal/any/thumbnail.jpg` should return the thumbnail from the latest event for the given camera and label combo.
However, it throws me a 404 with message: "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.".
Via the web interface, I can see the latest event thumbnail just before playing the video.

Same error with `http://frigate_ip/api/portal/any/snapshot.jpg`.

Is there anything I am missing?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: ##.##.##.##
  port: 1883
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  portal:
    ffmpeg:
      inputs:
        - path: rtsp://###:###@##.##.##.##:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://###:###@##.##.##.##:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
        width: 640
        height: 480
        fps: 30
rtmp:
    enabled: false
# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 800
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 600
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 8
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 2
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 2
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - cat
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      #objects:
      #  person: 2
      #  cat: 3
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian 11

### Install method

OS / install

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW1831E

**Comment by NickM-27** [comment]
You are running frigate 0.10 which is an outdated version. 0.11 is the current latest version which supports this feature.

**Comment by BenDavidson90** [comment]
> You are running frigate 0.10 which is an outdated version. 0.11 is the current latest version which supports this feature.

Thank for you reply.
How can it be possible ? I installed Frigate yesterday by following the official [docs](https://docs.frigate.video/frigate/installation/)...

**Comment by NickM-27** [comment]
You put your version above as `0.10.1-83481AF` so I am assuming that is correct. Is it correct that you have installed the frigate addon from the HA OS addon store?

**Comment by BenDavidson90** [comment]
> You put your version above as `0.10.1-83481AF` so I am assuming that is correct. Is it correct that you have installed the frigate addon from the HA OS addon store?

No I don't own any Home Assistant instance, I use Frigate in standalone mode.
Installed via Docker, I copied the configuration file from the [docs here](https://docs.frigate.video/frigate/installation/#docker).

**Comment by NickM-27** [comment]
Okay, make sure to select os / install type when filling out the issue form. Right now it shows ha os. 

Can you please paste your docker compose file as you have it

**Comment by BenDavidson90** [comment]
> Okay, make sure to select os / install type when filling out the issue form. Right now it shows ha os.
> 
> Can you please paste your docker compose file as you have it

Sorry, my mistake. I didn't see it on the form...
Here it is:
```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/benjamin/frigate/config/config.yml:/config/config.yml:ro
      - /home/benjamin/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

```
