### ISSUE TITLE
[Config Support]: Bushes are detected as persons until restart

### ISSUE THREAD

**Issue by HanseHouse** [blakeblackshear/frigate#5544]
### Describe the problem you are having

I have this situation:

- frigate detects persons on my lawn (which is correct) and generates an event
- when the persons leave the lawn, the event does not end and will be "IN PROGRESS" forever, frigate is sending MQTT events
- when I view the camera in debug mode with bounding boxes on, multiple "person" bounding boxes are shown, not moving or changing and constantly there (see screenshot)
- when I restart frigate, these bounding boxes are gone (see screenshot)
![frigate_false_positive_essbereich_Download_after_restart](https://user-images.githubusercontent.com/636594/219960151-7dd1dde6-0c09-4748-add7-b53b42244c7a.png)
![frigate_false_positive_essbereich_Download](https://user-images.githubusercontent.com/636594/219960153-d821d210-3268-4a9c-96d6-350d5e56478a.png)

I can't explain why the bounding boxes are gone after restart. I also can't set a min_area or ration because the bounding boxes have similar dimensions of persons.

Any help is appreciated :-)

### Version

0.12.0-B6B10E7

### Frigate config file

```yaml
mqtt:
  host: mosquitto

cameras:
  vorne:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.34.98/h264?**credentials-hidden**
          roles:
            - detect
    motion:
      mask:
        - 0,0,1592,0,1645,380,1518,441,1577,953,1605,1177,1466,1194,1426,977,1110,1029,251,1557,470,1944,0,1944,0,1424
        - 2542,1876,2537,1811,1625,1806,1623,1876
    detect:
      width: 2592
      height: 1944
    birdseye:
      mode: continuous

    zones:
      z_vorne_strasse: 
        coordinates: 830,1944,713,1164,0,1435,0,1944
      z_vorne_podest:
        coordinates: 2014,1944,1880,1428,774,1525,781,1944
      z_vorne_auffahrt:
        coordinates: 842,1944,764,1490,599,1518,542,1696,0,1781,0,1944
    record:
      events:
        required_zones:
          - z_vorne_strasse
          - z_vorne_podest
          - z_vorne_auffahrt
    snapshots:
      required_zones:
        - z_vorne_strasse
        - z_vorne_podest
        - z_vorne_auffahrt

  souterrain:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.34.83/h264?**credentials-hidden**
          roles:
            - detect
    motion:
      mask:
        - 2592,202,2592,797,2265,1105,2397,534
        - 2537,1874,2533,1810,1691,1817,1689,1875
        - 0,1944,1547,1944,1619,1600,1082,1474,1693,644,1793,360,1915,162,2046,221,2154,0,0,0
    zones:
      z_souterrain_treppe:
        coordinates: 2113,654,2436,0,1757,0,1548,346
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.2
            threshold: 0.3
      z_souterrain_terasse:
        coordinates: 1821,1560,1702,1604,620,940,1221,237,1505,226,2275,615,2208,777
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.2
            threshold: 0.3
    record:
      events:
        required_zones:
          - z_souterrain_terasse
          - z_souterrain_treppe
    snapshots:
      required_zones:
        - z_souterrain_terasse
        - z_souterrain_treppe

    detect:
      width: 2592
      height: 1944

  essbereich:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.34.97/h264?**credentials-hidden**
          roles:
            - detect
    motion:
      mask:
        - 231,1311,0,909,0,425,187,253,297,705,443,1068,495,1733
        - 2537,1874,2535,1817,1691,1817,1693,1877
        - 2592,1944,2592,612,2592,0,1878,0,1363,0,1363,214,1803,226,2230,345,1803,516,2297,815,1635,1944

    detect:
      width: 2592
      height: 1944

    zones:
      z_essbereich_rasen:
        coordinates: 1703,217,1914,236,2181,334,2259,421,1941,468,1382,210
      z_essbereich_terasse:
        coordinates: 1349,636,2098,1896,2471,836,1529,274,1370,286
      z_essbereich_ecke:
        coordinates: 957,1884,2136,1887,1387,653,402,844,437,1197,655,1188

    record:
      events:
        required_zones:
          - z_essbereich_rasen
          - z_essbereich_terasse
          - z_essbereich_ecke
    snapshots:
      required_zones:
          - z_essbereich_rasen
          - z_essbereich_terasse
          - z_essbereich_ecke

  terrasse:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.34.93/h264?**credentials-hidden**
          roles:
            - detect

    motion:
      mask:
        - 2592,959,2592,232,2321,35,2133,953,2155,1831
        - 2541,1876,2541,1808,1683,1811,1679,1869
        - 947,570,1143,594,1257,446,1337,304,1186,213,1135,0,0,0,0,577,785,694
    detect:
      width: 2592
      height: 1944

    zones:
      z_terasse_rasen:
        coordinates: 0,604,0,1208,644,699
        filters:
          person:
            min_area: 100000
            max_area: 600000
      z_terasse_terasse:
        coordinates: 1155,337,1799,429,1491,1944,0,1944,0,1944,0,1240
        filters:
          person:
            min_area: 100000
            max_area: 600000
      z_terasse_fensterbereich:
        coordinates: 2158,1944,2113,432,1732,403,1494,1944
        filters:
          person:
            min_area: 100000
            max_area: 600000
      z_terasse_trampolin:
        coordinates: 1075,342,1097,0,1540,0,1505,351
        filters:
          person:
            min_area: 100000
            max_area: 600000
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - z_terasse_rasen
          - z_terasse_terasse
          - z_terasse_fensterbereich
          - z_terasse_trampolin
    snapshots:
      required_zones:
        - z_terasse_rasen
        - z_terasse_terasse
        - z_terasse_fensterbereich
        - z_terasse_trampolin

  carport:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.34.52/h264?**credentials-hidden**
          roles:
            - detect
    zones:
      z_carport_vorne:
        coordinates: 2592,973,2592,465,1432,417,1423,178,1161,133,1218,955
        objects:
          - person
          - cat
          - dog

      z_carport_hinten:
        coordinates: 690,1944,2592,1944,2592,1001,1155,927,898,1242,1074,1332
        objects:
          - person
          - cat
          - dog

    motion:
      mask:
        - 2257,0,2241,513,1467,497,1455,0
        - 1899,1877,2535,1872,2543,1813,1903,1815
        - 0,1944,0,783,711,785,1037,1283,554,1944
    record:
      events:
        required_zones:
          - z_carport_vorne
          - z_carport_hinten
    snapshots:
      required_zones:
        - z_carport_vorne
        - z_carport_hinten
    detect:
      width: 2592
      height: 1944

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - cat
    - dog

      #motion:
      #  threshold: 1

      #detect:
      #  width: 2592
      #  height: 1944
    
      #birdseye:
      #  mode: motion

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
```

### Relevant log output

```shell
frigate      | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate      | s6-rc: info: service fix-attrs: starting
frigate      | s6-rc: info: service s6rc-fdholder successfully started
frigate      | s6-rc: info: service fix-attrs successfully started
frigate      | s6-rc: info: service legacy-cont-init: starting
frigate      | s6-rc: info: service legacy-cont-init successfully started
frigate      | s6-rc: info: service log-prepare: starting
frigate      | s6-rc: info: service log-prepare successfully started
frigate      | s6-rc: info: service nginx-log: starting
frigate      | s6-rc: info: service go2rtc-log: starting
frigate      | s6-rc: info: service frigate-log: starting
frigate      | s6-rc: info: service nginx-log successfully started
frigate      | s6-rc: info: service go2rtc-log successfully started
frigate      | s6-rc: info: service go2rtc: starting
frigate      | s6-rc: info: service frigate-log successfully started
frigate      | s6-rc: info: service go2rtc successfully started
frigate      | s6-rc: info: service frigate: starting
frigate      | s6-rc: info: service frigate successfully started
frigate      | s6-rc: info: service nginx: starting
frigate      | [INFO] Preparing go2rtc config...
frigate      | s6-rc: info: service nginx successfully started
frigate      | s6-rc: info: service legacy-services: starting
frigate      | [INFO] Starting Frigate...
frigate      | [INFO] Starting NGINX...
frigate      | s6-rc: info: service legacy-services successfully started
frigate      | [INFO] Starting go2rtc...
frigate      | 2023-02-19 15:50:58.988210199  15:50:58.988 INF go2rtc version 1.1.1 linux/amd64
frigate      | 2023-02-19 15:50:58.988374796  15:50:58.988 INF [api] listen addr=:1984
frigate      | 2023-02-19 15:50:58.988511237  15:50:58.988 INF [rtsp] listen addr=:8554
frigate      | 2023-02-19 15:50:58.988638626  15:50:58.988 INF [srtp] listen addr=:8443
frigate      | 2023-02-19 15:50:58.988740049  15:50:58.988 INF [webrtc] listen addr=:8555
frigate      | 2023-02-19 15:51:00.737855583  [2023-02-19 15:51:00] frigate.app                    INFO    : Starting Frigate (0.12.0-b6b10e7)
frigate      | 2023-02-19 15:51:00.782847915  [2023-02-19 15:51:00] peewee_migrate                 INFO    : Starting migrations
frigate      | 2023-02-19 15:51:00.786801797  [2023-02-19 15:51:00] peewee_migrate                 INFO    : There is nothing to migrate
frigate      | 2023-02-19 15:51:00.804560202  [2023-02-19 15:51:00] detector.coral                 INFO    : Starting detection process: 419
frigate      | 2023-02-19 15:51:00.808135147  [2023-02-19 15:51:00] frigate.app                    INFO    : Output process started: 421
frigate      | 2023-02-19 15:51:00.808695695  [2023-02-19 15:51:00] frigate.comms.dispatcher       INFO    : Turning on snapshots for vorne
frigate      | 2023-02-19 15:51:00.815103772  [2023-02-19 15:51:00] frigate.app                    INFO    : Camera processor started for vorne: 425
frigate      | 2023-02-19 15:51:00.820860512  [2023-02-19 15:51:00] frigate.app                    INFO    : Camera processor started for souterrain: 426
frigate      | 2023-02-19 15:51:00.827804838  [2023-02-19 15:51:00] frigate.app                    INFO    : Camera processor started for essbereich: 428
frigate      | 2023-02-19 15:51:00.838771868  [2023-02-19 15:51:00] frigate.app                    INFO    : Camera processor started for terrasse: 429
frigate      | 2023-02-19 15:51:00.838903795  [2023-02-19 15:51:00] frigate.app                    INFO    : Camera processor started for carport: 431
frigate      | 2023-02-19 15:51:00.844643293  [2023-02-19 15:51:00] frigate.app                    INFO    : Capture process started for vorne: 434
frigate      | 2023-02-19 15:51:00.850905576  [2023-02-19 15:51:00] frigate.app                    INFO    : Capture process started for souterrain: 440
frigate      | 2023-02-19 15:51:00.856754031  [2023-02-19 15:51:00] frigate.app                    INFO    : Capture process started for essbereich: 443
frigate      | 2023-02-19 15:51:00.865305878  [2023-02-19 15:51:00] frigate.comms.dispatcher       INFO    : Turning on snapshots for souterrain
frigate      | 2023-02-19 15:51:00.865312372  [2023-02-19 15:51:00] frigate.app                    INFO    : Capture process started for terrasse: 448
frigate      | 2023-02-19 15:51:00.871198903  [2023-02-19 15:51:00] frigate.app                    INFO    : Capture process started for carport: 454
frigate      | 2023-02-19 15:51:00.876975194  [2023-02-19 15:51:00] frigate.comms.dispatcher       INFO    : Turning on snapshots for essbereich
frigate      | 2023-02-19 15:51:00.877491800  [2023-02-19 15:51:00] frigate.comms.dispatcher       INFO    : Turning on snapshots for terrasse
frigate      | 2023-02-19 15:51:00.877494487  [2023-02-19 15:51:00] frigate.comms.dispatcher       INFO    : Turning on snapshots for carport
frigate      | 2023-02-19 15:51:01.235740812  172.21.0.3 - - [19/Feb/2023:15:51:01 +0000] "GET /cameras/essbereich HTTP/1.1" 200 6641 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "192.168.32.13"
frigate      | 2023-02-19 15:51:01.268885404  172.21.0.3 - - [19/Feb/2023:15:51:01 +0000] "GET /api/config HTTP/1.1" 200 19690 "https://cctv.lan.ps32.de/cameras/essbereich" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "192.
168.32.13"
frigate      | 2023-02-19 15:51:01.313170152  172.21.0.3 - - [19/Feb/2023:15:51:01 +0000] "GET //api/essbereich/dog/thumbnail.jpg HTTP/1.1" 200 1111 "https://cctv.lan.ps32.de/cameras/essbereich" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.
0 Safari/537.36" "192.168.32.13"
frigate      | 2023-02-19 15:51:01.314125818  172.21.0.3 - - [19/Feb/2023:15:51:01 +0000] "GET //api/essbereich/person/thumbnail.jpg HTTP/1.1" 200 9022 "https://cctv.lan.ps32.de/cameras/essbereich" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0
.0.0 Safari/537.36" "192.168.32.13"
frigate      | 2023-02-19 15:51:01.314615450  172.21.0.3 - - [19/Feb/2023:15:51:01 +0000] "GET //api/essbereich/cat/thumbnail.jpg HTTP/1.1" 200 1111 "https://cctv.lan.ps32.de/cameras/essbereich" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.
0 Safari/537.36" "192.168.32.13"
frigate      | 2023-02-19 15:51:04.149221301  [2023-02-19 15:51:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
frigate      | 2023-02-19 15:51:04.160163761  [2023-02-19 15:51:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Frigate stats

```json
{"carport":{"camera_fps":5.0,"capture_pid":454,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":462,"pid":431,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"3.1"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"161":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"198":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"244":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"3738":{"cpu":"0.3","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"412":{"cpu":"0.0","mem":"0.5"},"418":{"cpu":"0.7","mem":"0.0"},"419":{"cpu":"0.0","mem":"0.7"},"421":{"cpu":"4.7","mem":"0.7"},"424":{"cpu":"0.0","mem":"0.1"},"425":{"cpu":"1.7","mem":"0.7"},"426":{"cpu":"0.7","mem":"0.6"},"427":{"cpu":"0.0","mem":"0.1"},"428":{"cpu":"1.0","mem":"0.7"},"429":{"cpu":"1.0","mem":"0.6"},"430":{"cpu":"0.0","mem":"0.2"},"431":{"cpu":"0.7","mem":"0.6"},"434":{"cpu":"10.3","mem":"0.7"},"438":{"cpu":"0.0","mem":"0.1"},"439":{"cpu":"36.5","mem":"0.7"},"440":{"cpu":"10.0","mem":"0.7"},"443":{"cpu":"11.6","mem":"0.7"},"444":{"cpu":"63.5","mem":"0.7"},"448":{"cpu":"8.3","mem":"0.7"},"449":{"cpu":"0.0","mem":"0.1"},"453":{"cpu":"67.1","mem":"0.7"},"454":{"cpu":"8.0","mem":"0.7"},"455":{"cpu":"37.5","mem":"0.7"},"460":{"cpu":"0.0","mem":"0.1"},"462":{"cpu":"61.5","mem":"0.7"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"93":{"cpu":"3.0","mem":"1.6"},"MiB":{"cpu":"28758.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":26.57,"pid":419}},"essbereich":{"camera_fps":5.0,"capture_pid":443,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":453,"pid":428,"process_fps":5.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"24.03 %","mem":"- %"}},"service":{"last_updated":1676822782,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":495.8,"mount_type":"tmpfs","total":536.9,"used":41.0},"/media/frigate/clips":{"free":827059.7,"mount_type":"btrfs","total":1000203.1,"used":171635.9},"/media/frigate/recordings":{"free":827059.7,"mount_type":"btrfs","total":1000203.1,"used":171635.9},"/tmp/cache":{"free":1972.1,"mount_type":"tmpfs","total":2000.0,"used":27.9}},"temperatures":{},"uptime":922,"version":"0.12.0-b6b10e7"},"souterrain":{"camera_fps":5.0,"capture_pid":440,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":444,"pid":426,"process_fps":5.0,"skipped_fps":0.0},"terrasse":{"camera_fps":5.0,"capture_pid":448,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":455,"pid":429,"process_fps":5.0,"skipped_fps":0.0},"vorne":{"camera_fps":5.1,"capture_pid":434,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":439,"pid":425,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
This usually happens when motion masks are too large, causing the object to get stuck. I do see that those are are near trees so you could try:
1. making the motion masks smaller
2. Setting stationary object verification
```yaml
detect:
  stationary:
    interval: 10
```
3. Set max_frames value, though this is a last resort
