### ISSUE TITLE
Saving multiple clips for the same time when multiple objects detected

### ISSUE THREAD

**Issue by vpetrovych** [blakeblackshear/frigate#555]
**Describe the bug**
If there are 2 or more people in the camera, Frigate is generating multiple clips for the same time.

**Version of frigate**
What version are you using?
8-rc1

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
mqtt:
  host: 192.168.0.10
  user: mqtt
  password: mqtt
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - info
cameras:
  corridor:
    ffmpeg:
      inputs:
#        - path: 'rtsp://192.168.0.141:554'
#          roles:
#            - clips
#            - record
#            - rtmp
        - path: 'rtsp://192.168.0.141:554/media/video2'
          roles:
            - detect
            - clips
            - record
            - rtmp
    width: 720
    height: 1280
#    fps: 5
    clips:
      enabled: true
    snapshots:
      enabled: true
      crop: true
#      crop_to_region: true
      height: 175
#model:
#  height: 640
#  width: 360
motion:
  contour_area: 50
```

**Logs**
```
Include relevant log output here
```

**Frigate debug stats**
```
{
    "corridor": {
        "camera_fps": 5,
        "capture_pid": 40,
        "detection_fps": 0,
        "pid": 39,
        "process_fps": 5,
        "skipped_fps": 0
    },
    "detection_fps": 0,
    "detectors": {
        "cpu1": {
            "detection_start": 0,
            "inference_speed": 65.14,
            "pid": 34
        },
        "cpu2": {
            "detection_start": 0,
            "inference_speed": 65.03,
            "pid": 36
        }
    },
    "service": {
        "uptime": 140160,
        "version": "0.8.0-b10b64b"
    }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
<img width="1404" alt="Screenshot 2021-01-20 at 09 17 51" src="https://user-images.githubusercontent.com/576364/105140440-60608d00-5b00-11eb-9060-038982bc314a.png">

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows] Ubuntu
 - Virtualization: [e.g. Proxmox, Virtualbox] None
 - Coral Version: [e.g. USB, PCIe, None] None
 - Network Setup: [e.g. Wired, WiFi] Wired
