### ISSUE TITLE
[Support]: Frigate always disables snapshots for one of my cameras

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#5552]
### Describe the problem you are having

1. It's enabled in the config file
2. When Frigate starts, the snapshots comes disabled:

    ```
    frigate.comms.dispatcher       INFO    : Turning off snapshots for video_porteiro
    ```

3. If I enabled from UI it only stays enabled before next reboot
4. Same if I change from the Home Assistant switch

https://user-images.githubusercontent.com/29582865/220140216-4238c74e-f0f2-48a4-8c0b-1e17197e0cf7.mp4

### Version

Latest dev branch, but it was happening before

### Frigate config file

```yaml
snapshots:
  enabled: true
cameras:
  video_porteiro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/video_porteiro?video=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/video_porteiro_hd
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 1280
      height: 720
    live:
      height: 720
    zones:
      video_porteiro_area:
        coordinates: 956,720,835,617,724,617,512,720
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua VTO2202F-P-S2

**Comment by NickM-27** [comment]
Frigate 0.12 has no memory and will not set based on MQTT retained values. So if this is happening on reboot it is due to an automation or something running on frigate startup. I'd suggest enabling mqtt debug logs, restart frigate, and see where the topic is being set

**Comment by felipecrs** [comment]
Documentation does not mention how to enable mqtt logs, is it like following:

```
logger:
  default: info
  logs:
    mqtt: debug
```
