### ISSUE TITLE
[Support]: Log error for async_forward_entry_setups will fail in 2023.3

### ISSUE THREAD

**Issue by Moondevil-ha** [blakeblackshear/frigate#5554]
### Describe the problem you are having

I have a log error stating that the component will fail in version 2023.3. Error is in the log section below:

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
# frigate.yml
mqtt:
  host: 192.168.1.xxx
  user: mqtt-user
  password: xxxxxxxx
  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
    
cameras:
  Back_Garden:
    rtmp:
      enabled: true
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
        #- -c:v 
        #- h264_cuvid
      input_args:
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      
      inputs:
      #  - path: rtsp://admin:xxxxxxxx@192.168.1.75:554
      #  - path: rtmp://192.168.1.xx/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=Cthulhu1
        - path: http://192.168.1.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx 
          roles: 
            - detect
            - record
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75

    snapshots:
      enabled: True
      timestamp: True
    record:
      # Optional: Enable recording (default: shown below)
      enabled: True
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 5
          mode: all
          # Optional: Per object retention days
          objects:
            person: 15
    motion:
      mask:
        - 0,410,710,390,876,1158,379,1920,0,1920
        - 2560,234,1891,214,2560,633
  Sideway:
    rtmp:
      enabled: true
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
      #  - path: rtsp://admin:xxxxxxxx@192.168.1.xx:554
      #  - path: rtmp://192.168.1.xx/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
        - path: http://192.168.1.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx 
          roles: 
            - detect
            - record
            - rtmp
    detect:
      width: 2560
      height: 1440
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
          mask:
            - 2389,1440,1588,818,1233,519,2560,0,2560,1440

    snapshots:
      enabled: True
      timestamp: True
    record:
      # Optional: Enable recording (default: shown below)
      enabled: True
      # Optional: Number of days to retain recordings regardless of events (default: shown below)
      # NOTE: This should be set to 0 and retention should be defined in events section below
      #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
      # Optional: Event recording settings
      events:
        # Optional: Maximum length of time to retain video during long events. (default: shown below)
        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
        #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
        # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
        # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
        # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
          # Required: Default retention days (default: shown below)
          default: 5
          mode: all
          # Optional: Per object retention days
          objects:
            person: 15
    motion:
      mask:
        - 2389,1440,1588,818,1233,519,2560,0,2560,1440
    
  Front_Yard:
    rtmp:
      enabled: true
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        #- live_flv
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
      #  - path: rtsp://admin:xxxxxxxx@192.168.1.xx:554
      #  - path: rtmp://192.168.1.xx/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=xxxxxxxx
        - path: http://192.168.1.xx/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxxxxxx 
          roles: 
            - detect
            - record
            - rtmp
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_score: 0.75
  
    snapshots:
      enabled: True
      timestamp: True
    record:
            # Optional: Enable recording (default: shown below)
      enabled: True
            # Optional: Number of days to retain recordings regardless of events (default: shown below)
            # NOTE: This should be set to 0 and retention should be defined in events section below
            #       if you only want to retain recordings of events.
      retain: 
        days: 5
        mode: all
            # Optional: Event recording settings
      events:
              # Optional: Maximum length of time to retain video during long events. (default: shown below)
              # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
              #       will be the last x seconds of the event unless retain_days under record is > 0.
        #max_seconds: 300
              # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 5
              # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
              # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - cat
          - dog
              # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: []
        # Optional: Retention settings for recordings of events
        retain:
                # Required: Default retention days (default: shown below)
          default: 5
          mode: all
                # Optional: Per object retention days
          objects:
            person: 15

detectors:
  coral_pci:
    type: edgetpu
    device: pci
  coral_usb:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 15:11:54 (1 occurrences)
Last logged: 15:11:54

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for frigate using this method at custom_components/frigate/__init__.py, line 289: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink 511W / 410W
