### ISSUE TITLE
[Config Support]: Do i need required_zones statement?

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#5555]
### Describe the problem you are having

I have below config (see frigate config file) where i setup 1 zone, for detecting people in the yard at night. From older parts of the config that i used as a template, which i have now commented out, i see that once the zones were defined, they also used the required_zones for detect/record and snapshots.

Do i need this ? I guess i get the normal events pertaining to the defined objects at the camera level already, and if i want to have the zone snapshots or record events as well i need to use the required_zones command ?

I guess for my purpose just creating the zone is good enough. I see the zones after a reload in HA and i can automate on it, so that's great.

Just wondering..

### Version

beta-8

### Frigate config file

```yaml
front_driveway_1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway_1
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
          min_score: 0.7
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      front_driveway_1_person_at_night:
        coordinates: 739,1080,1920,1080,1920,384,1085,434
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15
```

### Relevant log output

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

na
