### ISSUE TITLE
[Support]: Consistent Issue with FFmpeg process

### ISSUE THREAD

**Issue by gettingerr** [blakeblackshear/frigate#5557]
### Describe the problem you are having

I am running Frigate 12.0 Beta 8 via docker in the latest Unraid. I have 1 Amcrest doorbell camera, 2 Wyze cameras with RTSP firmware, and 4 Reolink POE Cameras running through a Reolink NVR.

On Frigate 11.0, I have all cameras up and running. When trying to migrate to 12.0, I am running into the following errors in logs on all of my Reolink Cameras:

ERROR   : Name_Camera: ffmpeg process is not running. exiting
ERROR   : Ffmpeg process crashed unexpectedly for Name_Camera

And these errors repeat over and over for the 4 Reolink cameras. Occasionally, one or two will bite after a while of letting the container run, but even then, trying to play back events from these cameras is painfully slow if it ever loads. My other three cameras (Wyze and Amcrest) appear to function normally within the RTSP FFmpeg set up shown in the latest docs.

For Reolink, I have attempted to set them up both via RTMP and RTSP as well as using Main and Sub streams with a variety of resolutions, but nothing seems to stick. I can view both RTMP and RTSP in VLC and in a GoRTC Container with no issues whatsoever.

I am at a loss for what to try next. Any assistance is appreciated, will provide more specific logs and config as desired, just let me know what we need to diagnose. (in the config below, the commented out part at the end is my old 11.0 config)

### Version

12.0beta8 (non tensorrt)

### Frigate config file

```yaml
################################################################Usernames and passwords removed, this messed up some of the user= and password= lines but rest assured they are correct in actual config and dont say passwordword lol

mqtt:
  host: 192.168.2.10
  user: mqtt
  password: mqttpassword
################################################################
detectors: 
  cpu1:
    type: cpu
    num_threads: 1

#logger:
#  default: warning


################################################################
birdseye:
  enabled: False
  width: 1280
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 15
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous
################################################################
detect:
  enabled: True
  width: 1920
  height: 1080
  fps: 2
  max_disappeared: 20
################################################################
objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
    - bear
  filters:
    car:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
    person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
################################################################
motion:
  threshold: 20
  contour_area: 25
  frame_height: 45
################################################################
record:
  enabled: True
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 10
    post_capture: 10
    objects:
      - person
      - car
      - bear
      - cat
      - dog
    retain:
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      mode: all
################################################################
# rtmp:
#   enabled: True
################################################################
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: True
  height: 400
  retain:
    default: 30
################################################################
timestamp_style:
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"
################################################################
go2rtc:
  streams:
    Test_Camera: # <- for RTSP streams
      - rtsp://user:passwordword@192.168.2.41:554/h264Preview_01_sub #Driveway # <- stream which supports video & aac audio
      - ffmpeg:Driveway_Camera#audio=opus # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Back_Door_Camera: # <- for RTSP streams
      - rtsp://user:userpassword@192.168.2.51/live #Back Door # <- stream which supports video & aac audio
      - ffmpeg:Back_Door_Camera#audio=opus # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Front_Door_Camera:
      - rtsp://user:userpassword@192.168.2.50/live #Front Door # <- stream which supports video & aac audio
      - ffmpeg:Front_Door_Camera#audio=opus # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    Doorbell_Camera:
      - rtsp://user:ampassword12@192.168.2.52:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:Doorbell_Camera#audio=opus
    # Driveway_Camera: # <- for http streams
    #   - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus" # <- http streams must use ffmpeg to set all types
    Backyard_Camera:
      - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus"
    Side_Camera:
      - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel2_main.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus"
    Porch_Camera:
      - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel3_main.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus"
    # Driveway_Camera_sub: # <- for http streams
    #   - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus" # <- http streams must use ffmpeg to set all types
    Backyard_Camera_sub:
      - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel1_sub.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus"
    Side_Camera_sub:
      - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel2_sub.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus"
    Porch_Camera_sub:
      - "ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel3_sub.bcs&user=user&passwordword=userpassword#video=copy#audio=copy#audio=opus"
################################################################
cameras:



  Back_Door_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Camera?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
    snapshots: 
      enabled: True
    objects:
      track:
        - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
#####
  Front_Door_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door_Camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: 
            - detect
            - record
    record:
      enabled: True
    snapshots: 
      enabled: True
    objects:
      track:
        - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100  
#####
  # Driveway_Camera:
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/Driveway_Camera_sub?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
#        - path: rtsp://127.0.0.1:8554/Driveway_Camera_sub?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
#          input_args: preset-rtsp-restream
#          roles:
#            - detect
  Driveway_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_Camera?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
    snapshots: 
      enabled: True
    objects:
      track:
        - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100  
  
    # record:
    #   enabled: True
    #   events:
    #     required_zones: 
    #       - Driveway_Near
    #       - Driveway_Mid
    # snapshots:
    #   required_zones: 
    #     - Driveway_Near
    #     - Driveway_Mid
    # zones:
    #   Driveway_Near:
    #     coordinates: 0,480,0,239,52,218,115,179,525,266,452,480
    #     objects:
    #       - car
    #       - person
    #       - bear
    #   Driveway_Mid:
    #     coordinates: 278,103,118,177,527,270,556,137
    #     objects:
    #       - car
    #       - person
    #       - bear
    #   Driveway_Far:
    #     coordinates: 349,65,270,105,551,138,565,85
    # objects:
    #   track:
    #     - person
    #     - car
    #     - bear
    # mqtt:
    #   enabled: True
    #   timestamp: False
    #   bounding_box: False
    #   crop: True
    #   quality: 100
#####
  Side_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Side_Camera_sub?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
    objects:
      track:
        - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
#####
  Backyard_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard_Camera_sub?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
#####
  Porch_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Porch_Camera_sub?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
    record:
      events:
        required_zones: 
          - Driveway_Porch
          - Porch_Zone
    snapshots:
      required_zones: 
        - Driveway_Porch
        - Porch_Zone
    zones:
      Driveway_Porch:
        coordinates: 171,75,198,74,193,183,195,220,151,245,167,186,129,164,30,108
        objects:
          - car
          - person
      Porch_Zone:
        coordinates: 494,25,314,0,304,258,277,270,279,0,204,0,190,222,157,239,137,274,107,301,53,333,0,346,0,480,640,480,640,232,640,173,640,67
        objects:
          - car
          - person
          - bear
    objects:
      track:
        - person
        - car
        - bear
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
#####
  Doorbell_Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell_Camera?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: True
    snapshots: 
      enabled: True
    objects:
      track:
        - person
        - bear
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
    zones:
      Doorbell_Porch:
        coordinates: 0,1080,1897,1080,1920,41,1519,35,1341,270,1339,620,777,623,766,0,658,25,605,620,232,617,243,0,0,0
        objects:
          - person
          - bear
    detect:
      width: 640
      height: 480



# #   Driveway_Camera:
# #     ffmpeg:
# #       input_args:
# #       - -avoid_negative_ts
# #       - make_zero
# #       - -fflags
# #       - nobuffer+genpts+discardcorrupt
# #       - -flags
# #       - low_delay
# #       - -strict
# #       - experimental
# #       - -analyzeduration
# #       - 1000M
# #       - -probesize
# #       - 1000M
# #       - -rw_timeout
# #       - "5000000"
# #       inputs:
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - record
# #             # - rtmp
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - detect
# #       output_args:
# #         record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
# #     detect:
# #       width: 640
# #       height: 480
# #       fps: 4
# #     record:
# #       events:
# #         required_zones: 
# #           - Driveway_Near
# #           - Driveway_Mid
# #     snapshots:
# #       required_zones: 
# #         - Driveway_Near
# #         - Driveway_Mid
# #     zones:
# #       Driveway_Near:
# #         coordinates: 0,480,0,239,52,218,115,179,525,266,452,480
# #         objects:
# #           - car
# #           - person
# #           - bear
# #       Driveway_Mid:
# #         coordinates: 278,103,118,177,527,270,556,137
# #         objects:
# #           - car
# #           - person
# #           - bear
# #       Driveway_Far:
# #         coordinates: 349,65,270,105,551,138,565,85
# #     objects:
# #       track:
# #         - person
# #         - car
# #         - bear
# #     mqtt:
# #       enabled: True
# #       timestamp: False
# #       bounding_box: False
# #       crop: True
# #       quality: 100
# # #####
# #   Backyard_Camera:
# #     ffmpeg:
# #       input_args:
# #       - -avoid_negative_ts
# #       - make_zero
# #       - -fflags
# #       - nobuffer+genpts+discardcorrupt
# #       - -flags
# #       - low_delay
# #       - -strict
# #       - experimental
# #       - -analyzeduration
# #       - 1000M
# #       - -probesize
# #       - 1000M
# #       - -rw_timeout
# #       - "5000000"
# #       inputs:
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel1_main.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - record
# #             # - rtmp
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel1_sub.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - detect
# #       output_args:
# #         record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
# #     detect:
# #       width: 640
# #       height: 480
# #       fps: 4
# #     mqtt:
# #       enabled: True
# #       timestamp: False
# #       bounding_box: False
# #       crop: True
# #       quality: 100
# # #####
# #   Side_Camera:
# #     ffmpeg:
# #       input_args:
# #       - -avoid_negative_ts
# #       - make_zero
# #       - -fflags
# #       - nobuffer+genpts+discardcorrupt
# #       - -flags
# #       - low_delay
# #       - -strict
# #       - experimental
# #       - -analyzeduration
# #       - 1000M
# #       - -probesize
# #       - 1000M
# #       - -rw_timeout
# #       - "5000000"
# #       inputs:
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel2_main.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - record
# #             # - rtmp
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel2_sub.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - detect
# #       output_args:
# #         record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
# #     detect:
# #       width: 640
# #       height: 480
# #       fps: 4
# #     mqtt:
# #       enabled: True
# #       timestamp: False
# #       bounding_box: False
# #       crop: True
# #       quality: 100
# # #####
# #   Porch_Camera:
# #     ffmpeg:
# #       input_args:
# #       - -avoid_negative_ts
# #       - make_zero
# #       - -fflags
# #       - nobuffer+genpts+discardcorrupt
# #       - -flags
# #       - low_delay
# #       - -strict
# #       - experimental
# #       - -analyzeduration
# #       - 1000M
# #       - -probesize
# #       - 1000M
# #       - -rw_timeout
# #       - "5000000"
# #       inputs:
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel3_main.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - record
# #             # - rtmp
# #         - path: http://192.168.2.41/flv?port=1935&app=bcs&stream=channel3_sub.bcs&user=user&passwordword=userpassword
# #           roles:
# #             - detect
# #       output_args:
# #         record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
# #     detect:
# #       width: 640
# #       height: 480
# #       fps: 4
# #     record:
# #       events:
# #         required_zones: 
# #           - Driveway_Porch
# #           - Porch_Zone
# #     snapshots:
# #       required_zones: 
# #         - Driveway_Porch
# #         - Porch_Zone
# #     zones:
# #       Driveway_Porch:
# #         coordinates: 171,75,198,74,193,183,195,220,151,245,167,186,129,164,30,108
# #         objects:
# #           - car
# #           - person
# #       Porch_Zone:
# #         coordinates: 494,25,314,0,304,258,277,270,279,0,204,0,190,222,157,239,137,274,107,301,53,333,0,346,0,480,640,480,640,232,640,173,640,67
# #         objects:
# #           - car
# #           - person
# #           - bear
# #     objects:
# #       track:
# #         - person
# #         - car
# #         - bear
# #     mqtt:
# #       enabled: True
# #       timestamp: False
# #       bounding_box: False
# #       crop: True
# #       quality: 100
# # #####
# #   Doorbell_Camera:
# #     ffmpeg:
# #       inputs:
# #         - path: rtsp://user:ampassword12@192.168.2.52:554/cam/realmonitor?channel=1&subtype=0
# #           roles:
# #             - record
# #             # - rtmp
# #             - detect
# #     record:
# #       enabled: True
# #     snapshots: 
# #       enabled: True
# #     objects:
# #       track:
# #         - person
# #         - bear
# #     mqtt:
# #       enabled: True
# #       timestamp: False
# #       bounding_box: False
# #       crop: True
# #       quality: 100
# #     zones:
# #       Doorbell_Porch:
# #         coordinates: 0,1080,1897,1080,1920,41,1519,35,1341,270,1339,620,777,623,766,0,658,25,605,620,232,617,243,0,0,0
# #         objects:
# #           - person
# #           - bear
```

### Relevant log output

```shell
2023-02-20 22:05:15.492254676  ipaddress - - [20/Feb/2023:22:05:15 -0500] "GET /api/stats HTTP/1.1" 200 4117 "-" "HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10" "-"
2023-02-20 22:05:17.127870319  [2023-02-20 22:05:17] frigate.video                  ERROR   : Porch_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:17.127874818  [2023-02-20 22:05:17] frigate.video                  ERROR   : Porch_Camera: ffmpeg process is not running. exiting capture thread...
2023-02-20 22:05:17.495900818  [2023-02-20 22:05:17] frigate.video                  ERROR   : Side_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:17.496026595  [2023-02-20 22:05:17] frigate.video                  ERROR   : Side_Camera: ffmpeg process is not running. exiting capture thread...
2023-02-20 22:05:22.009164062  [2023-02-20 22:05:22] watchdog.Porch_Camera          ERROR   : Ffmpeg process crashed unexpectedly for Porch_Camera.
2023-02-20 22:05:22.009168431  [2023-02-20 22:05:22] watchdog.Porch_Camera          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-20 22:05:22.009170404  [2023-02-20 22:05:22] ffmpeg.Porch_Camera.detect     ERROR   : rtsp://127.0.0.1:8554/Porch_Camera_sub?video=copy&audio=aac: Invalid data found when processing input
2023-02-20 22:05:22.381044392  [2023-02-20 22:05:22] watchdog.Driveway_Camera       ERROR   : Ffmpeg process crashed unexpectedly for Driveway_Camera.
2023-02-20 22:05:22.381053719  [2023-02-20 22:05:22] watchdog.Driveway_Camera       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-20 22:05:22.381055563  [2023-02-20 22:05:22] ffmpeg.Driveway_Camera.detect  ERROR   : [rtsp @ 0x55fb3eaa7d80] method DESCRIBE failed: 404 Not Found
2023-02-20 22:05:22.381057326  [2023-02-20 22:05:22] ffmpeg.Driveway_Camera.detect  ERROR   : rtsp://127.0.0.1:8554/Driveway_Camera?video=copy&audio=aac: Server returned 404 Not Found
2023-02-20 22:05:22.390793128  [2023-02-20 22:05:22] watchdog.Side_Camera           ERROR   : Ffmpeg process crashed unexpectedly for Side_Camera.
2023-02-20 22:05:22.390797196  [2023-02-20 22:05:22] watchdog.Side_Camera           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-20 22:05:22.390799230  [2023-02-20 22:05:22] ffmpeg.Side_Camera.detect      ERROR   : rtsp://127.0.0.1:8554/Side_Camera_sub?video=copy&audio=aac: Invalid data found when processing input
2023-02-20 22:05:22.394044851  [2023-02-20 22:05:22] frigate.video                  ERROR   : Driveway_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:22.394386504  [2023-02-20 22:05:22] frigate.video                  ERROR   : Driveway_Camera: ffmpeg process is not running. exiting capture thread...
2023-02-20 22:05:23.486324960  ipaddress - - [20/Feb/2023:22:05:23 -0500] "GET /api/stats HTTP/1.1" 200 4018 "-" "HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10" "-"
2023-02-20 22:05:26.273404445  22:05:26.273 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error="write tcp 127.0.0.1:8554->127.0.0.1:58904: write: broken pipe"
2023-02-20 22:05:26.273485728  22:05:26.273 WRN [streams] can't get track url=ffmpeg:http://192.168.2.41/flv?port=1935&app=bcs&stream=channel3_sub.bcs&user=user&password=password#video=copy#audio=copy#audio=opus
2023-02-20 22:05:27.021112888  22:05:27.020 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error="write tcp 127.0.0.1:8554->127.0.0.1:35470: write: broken pipe"
2023-02-20 22:05:27.138945824  [2023-02-20 22:05:27] frigate.video                  ERROR   : Porch_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:27.139093411  [2023-02-20 22:05:27] frigate.video                  ERROR   : Porch_Camera: ffmpeg process is not running. exiting capture thread...
2023-02-20 22:05:27.527801908  [2023-02-20 22:05:27] frigate.video                  ERROR   : Side_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:27.527942042  [2023-02-20 22:05:27] frigate.video                  ERROR   : Side_Camera: ffmpeg process is not running. exiting capture thread...
2023-02-20 22:05:29.766875576  ipaddress - - [20/Feb/2023:22:05:29 -0500] "GET /api/config HTTP/1.1" 200 22472 "http://ipaddress:5000/storage" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
2023-02-20 22:05:31.662945098  ipaddress - - [20/Feb/2023:22:05:31 -0500] "GET /api/stats HTTP/1.1" 200 4053 "-" "HomeAssistant/2023.2.5 aiohttp/3.8.1 Python/3.10" "-"
2023-02-20 22:05:32.021124279  [2023-02-20 22:05:32] watchdog.Porch_Camera          ERROR   : Ffmpeg process crashed unexpectedly for Porch_Camera.
2023-02-20 22:05:32.021128397  [2023-02-20 22:05:32] watchdog.Porch_Camera          ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-20 22:05:32.021130491  [2023-02-20 22:05:32] ffmpeg.Porch_Camera.detect     ERROR   : rtsp://127.0.0.1:8554/Porch_Camera_sub?video=copy&audio=aac: Invalid data found when processing input
2023-02-20 22:05:32.392484179  [2023-02-20 22:05:32] watchdog.Driveway_Camera       ERROR   : Ffmpeg process crashed unexpectedly for Driveway_Camera.
2023-02-20 22:05:32.396480624  [2023-02-20 22:05:32] watchdog.Driveway_Camera       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-20 22:05:32.396483750  [2023-02-20 22:05:32] ffmpeg.Driveway_Camera.detect  ERROR   : [rtsp @ 0x5611a543bd80] method DESCRIBE failed: 404 Not Found
2023-02-20 22:05:32.396485664  [2023-02-20 22:05:32] ffmpeg.Driveway_Camera.detect  ERROR   : rtsp://127.0.0.1:8554/Driveway_Camera?video=copy&audio=aac: Server returned 404 Not Found
2023-02-20 22:05:32.401144306  [2023-02-20 22:05:32] watchdog.Side_Camera           ERROR   : Ffmpeg process crashed unexpectedly for Side_Camera.
2023-02-20 22:05:32.401224647  [2023-02-20 22:05:32] watchdog.Side_Camera           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-02-20 22:05:32.401294358  [2023-02-20 22:05:32] ffmpeg.Side_Camera.detect      ERROR   : rtsp://127.0.0.1:8554/Side_Camera_sub?video=copy&audio=aac: Invalid data found when processing input
2023-02-20 22:05:32.410963795  [2023-02-20 22:05:32] frigate.video                  ERROR   : Driveway_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:32.411584815  [2023-02-20 22:05:32] frigate.video                  ERROR   : Driveway_Camera: Unable to read frames from ffmpeg process.
2023-02-20 22:05:32.411587510  [2023-02-20 22:05:32] frigate.video                  ERROR   : Driveway_Camera: ffmpeg process is not running. exi
```

### FFprobe output from your camera

```shell
Side Camera, Driveway Camera, Porch Camera:
FFPROBE OUTPUT
[ { "return_code": 0, "stderr": {}, "stdout": {} } ]

Backyard Camera (Reolink but happened to actually work this startup):
FFPROBE OUTPUT
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 480, "width": 640 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]

Amcrest:
FFPROBE OUTPUT
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1920, "width": 2560 }, { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" } ] } } ]

Wyze:
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "20/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 1080, "width": 1920 } ] } } ]
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Wyze Cam V3, Amcrest Doorbell, Reolink NVR RLN8-410

**Comment by NickM-27** [comment]
The frigate logs aren't helpful, go2rtc logs in this case will show the necessary info 

It is known that go2rtc restream as a source for frigate does not work well with some buggy cameras. I'd suggest using frigate directly with the camera stream and leave the go2rtc in place just for live view / restream to HA

**Comment by NickM-27** [comment]
You could also try the latest dev image and using go2rtc with manual input args like we have them for reolink in frigate. 

```
ffmpeg:
      http-reolink: "-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000 -i {input}"

streams:
  reolink_cam: 
          - "ffmpeg:http://192.168.50.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#input=http-reolink#video=copy#audio=copy#audio=opus"

```
