### ISSUE TITLE
[EdgeTPU Support]: HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback].

### ISSUE THREAD

**Issue by fisch55** [blakeblackshear/frigate#5559]
### Describe the problem you are having

I use the Choral USB. It used to work without problems on my NUC7i5BNH with Homeassistant OS.
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

But now, after a while, Frigtae always crashes with the error message: HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback].

The Coral is connected to an external USB3.0 hub with 3A power supply. There are 4 ports in total, but only one of them is active. The Coral is connected to this as mentioned.

I have tried everything, different cables, new HUB...nothing helps. The same with the Stabile version, by the way.

### Version

SYSTEM 0.12.0-27A31E7

### Frigate config file

```yaml
logger:
  default: error

environment_vars:
  LIBVA_DRIVER_NAME: i965
mqtt:
  host: xxxxx
  user: xxxxx
  password:xxxx



  
detectors:
  #cpu:
   # type: cpu
    #num_threads: 3
  coral:
    type: edgetpu
    device: usb
  
    

birdseye:
  enabled: true
  mode: continuous

detect:
  enabled: true
  width: 1280
  height: 720
  #fps: 7 #coral
  fps: 5
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 15

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects
      
snapshots:
  enabled: true
  

#rtmp:
 # enabled: true 


cameras:
#  back:
#    ffmpeg:
#      inputs:
#        - path: rtsp://xxxxx/Streaming/Channels/1
#          roles:
#            - detect
#            
#            
#       - path: rtsp://xxxxxx/Streaming/Channels/1
#          roles:
#            - record
#            - rtmp
#            
#    objects:
#      track:
#        - person
#        - cat
#        
#      filters:
#        person:
#          threshold: 0.7
#        cat:
#          threshold: 0.5
#        #dog:
#         # threshold: 0.5
    
#    motion:
#      mask:
#        - 1280,0,1280,720,1089,720,986,720,954,686,924,664,863,634,800,606,709,546,674,513,663,484,707,456,751,424,787,404,830,367,860,340,883,326,883,164,313,0       
#        - 279,0,0,0,0,254,406,83,369,0,306,0,291,0,396,0

#    zones:
#      zone_back_1:
#                coordinates: 0,720,0,163,40,267,0,186,26,151,111,234,147,221,181,196,209,181,241,171,279,147,319,143,336,129,370,119,403,104,429,106,480,123,507,140,540,159,587,174,911,280,237,720,30,720,76,699,133,720,216,720,191,720
      
    

  
  
  front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxxxxxx/Streaming/Channels/1
          roles:
            - detect
            - record
            - restream

        #- path: rtsp://xxxxxxx/Streaming/Channels/1
         # roles:
          #  - record
            

    objects:
      track:
        - person
        - cat
        
      filters:
        person:
          threshold: 0.7
          mask: 
            - 0,276,0,339,64,336,94,331,117,331,149,329,174,327,197,327,239,326,264,327,284,320,296,301,304,284,316,270,340,229,351,209,413,87,451,0,0,0
            - 1280,720,1280,0,1253,0,770,0,947,231,791,0,710,0,637,0,681,110,864,114
            - 801,0,1280,0,1280,720,733,720,763,223,787,39,789,154,740,0,809,233,749,720
            - 0,0,981,0,917,119,826,114,420,111
        cat:
          
          threshold: 0.5
        #dog:
          
         # threshold: 0.5
    
    zones:
      zone_0:
        coordinates: 199,720,181,444,397,111,766,117,660,720
    
    motion:
      mask:
        - 0,276,0,339,64,336,94,331,117,331,149,329,174,327,197,327,239,326,264,327,284,320,296,301,304,284,316,270,340,229,351,209,413,87,451,0,0,0
        - 1280,720,1280,0,1253,0,770,0,947,231,791,0,710,0,637,0,681,110,864,114
        - 801,0,1280,0,1280,720,733,720,763,223,787,39,789,154,740,0,809,233,749,720
        - 0,0,981,0,917,119,826,114,420,111
        
        
        
  #netatmo_haustuer:
   # ffmpeg:
    #  inputs:
     #   - path: http://192.168.178.114/xxxxxx
      #    roles: 
       #     - detect
      #input_args :
       # - -avoid_negative_ts
    #    - make_zero
    #    - -fflags
     #   - nobuffer
      #  - -flags
       # - low_delay
    #    - -strict
     #   - experimental
      #  - -fflags
       # - +genpts+discardcorrupt
    #    - -use_wallclock_as_timestamps
     #   - '1'
      
    #objects:
     # track:
     #   - person
      #  - cat
        
      #filters:
      #  person:
       #   threshold: 0.7    
        
     
    
      
  
  

```
### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant log output

```shell
2023-02-21 09:09:36.317652624  F driver/usb/usb_driver.cc:1148] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]
2023-02-21 09:09:36.317671994  Fatal Python error: Aborted
2023-02-21 09:09:36.317683955  
2023-02-21 09:09:36.317692470  Thread 0x00007f31b70e6740 (most recent call first):
2023-02-21 09:09:36.317839784    File "/usr/lib/python3.9/selectors.py", line 416 in select
2023-02-21 09:09:36.318183335    File "/usr/lib/python3.9/multiprocessing/connection.py", line 936 in wait
2023-02-21 09:09:36.318523247    File "/usr/lib/python3.9/multiprocessing/connection.py", line 429 in _poll
2023-02-21 09:09:36.318861811    File "/usr/lib/python3.9/multiprocessing/connection.py", line 262 in poll
2023-02-21 09:09:36.319150310    File "/usr/lib/python3.9/multiprocessing/queues.py", line 113 in get
2023-02-21 09:09:36.319499977    File "/opt/frigate/frigate/object_detection.py", line 108 in run_detector
2023-02-21 09:09:36.319822536    File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
2023-02-21 09:09:36.320165685    File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
2023-02-21 09:09:36.320571162    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
2023-02-21 09:09:36.320930483    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
2023-02-21 09:09:36.321270775    File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
2023-02-21 09:09:36.321828577    File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
2023-02-21 09:09:36.322008922    File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
2023-02-21 09:09:36.322769873    File "/opt/frigate/frigate/object_detection.py", line 179 in start_or_restart
2023-02-21 09:09:36.322780935    File "/opt/frigate/frigate/object_detection.py", line 147 in __init__
2023-02-21 09:09:36.323497898    File "/opt/frigate/frigate/app.py", line 219 in start_detectors
2023-02-21 09:09:36.323508660    File "/opt/frigate/frigate/app.py", line 385 in start
2023-02-21 09:09:36.324161603    File "/opt/frigate/frigate/__main__.py", line 16 in <module>
2023-02-21 09:09:36.325564933    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
2023-02-21 09:09:36.325578635    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
2023-02-21 09:09:41.032993882  XXX - - [21/Feb/2023:10:09:41 +0100] "GET / HTTP/1.1" 200 6641 "-" "HomeAssistantSupervisor/2023.01.1 aiohttp/3.8.3 Python/3.10" "-"
2023-02-21 09:09:41.308227700  XXX - - [21/Feb/2023:10:09:41 +0100] "GET /ws HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15" "fXXXXX"
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2023-02-21 09:09:50.408974580  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 7 leaked shared_memory objects to clean up at shutdown
2023-02-21 09:09:50.408979217    warnings.warn('resource_tracker: There appear to be %d '
Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-02-21 09:09:50.413087501  exit OK
s6-rc: info: service frigate-log successfully stopped
Service go2rtc exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped```


### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

_No response_
