### ISSUE TITLE
[Config Support]: Low def cameras driving high CPU usage

### ISSUE THREAD

**Issue by onetoomany** [blakeblackshear/frigate#5560]
### Describe the problem you are having

I've 4 H264 cameras and 5 MPEG-4 cameras. My power consumption is quite high, so I tested with / without each camera family. What I found was that the H264 cameras had little impact on power consumption, whereas the MPEG-4 cameras used around 5x the power each of the H264 cameras.

The MPEG-4 cameras are set up with 640x480@30fps. I've based my config off [the docs](https://docs.frigate.video/configuration/camera_specific). I note "Note that mjpeg cameras require encoding the video into h264 for recording, and rtmp roles. This will use significantly more CPU than if the cameras supported h264 feeds directly." - however, even the "detect" is driving the high CPU usage.

How can I change my config to reduce CPU usage. Note, I'm using a Coral USB, and this is working fine.

Example camera config below:
```
#=========================================================
# Drive
#=========================================================
  drive:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      inputs:
        - path: http://username:password@ipaddress:8081/nphMotionJpeg?Resolution=640x480&Quality=Standard
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    zones:
      main:
        coordinates: 0,720,1280,720,1280,96,0,96
        objects:
          - person
          - dog
          - cat
          - bicycle
          - car
          - truck
          - motorcycle
#    motion:
#      mask:
#        - 808,0,807,89,0,88,0,0 # timestamp
    detect:
      width: 640
      height: 480
      fps: 10
```

### Version

0.10.1-83481AF

### Frigate config file

```yaml
#=========================================================
# Drive
#=========================================================
  drive:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      inputs:
        - path: http://username:password@ipaddress:8081/nphMotionJpeg?Resolution=640x480&Quality=Standard
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    zones:
      main:
        coordinates: 0,720,1280,720,1280,96,0,96
        objects:
          - person
          - dog
          - cat
          - bicycle
          - car
          - truck
          - motorcycle
#    motion:
#      mask:
#        - 808,0,807,89,0,88,0,0 # timestamp
    detect:
      width: 640
      height: 480
      fps: 10
```

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
First off it looks like you're running an old version of frigate so I'd suggest updating. 

How do you know detect itself is running high cpu?

**Comment by onetoomany** [comment]
Thanks - I've updated to v0.12.0Beta8 so am getting proper stats here.

What I was using before was power consumption on my server using smartplugs - varying between using HD, LD, LD+HD, none camera combinations.  This was based with nothing triggering the cameras. In essence, using LD cameras increased my power consumption by 50W - given this is 24/7, that's £150 per year of additional energy costs, so I'm keen to tweak settings accordingly! The new version makes no difference to the power consumption.

What I'm now seeing under the System tab is better data:

**Detectors:** coral
P-ID | Inference Speed | CPU % | Memory %
557 | 7.58 ms | 0.0% | 0.2%

**GPU:** intel-qsv
GPU % | Memory %
1.19 % | - %


**High Def:**
Process | P-ID | FPS | CPU % | Memory %
ffmpeg | 587 | 10.1 | 1.3% | 0.1%
Capture | 582 | 10.1 | 0.7% | 0.1%
Detect | 565 | 0 (0 skipped) | 0.7% | 0.2%

**Low Def:**
Process | P-ID | FPS | CPU % | Memory %
ffmpeg | 629 | 10 | **51.8%** | 0.2%
Capture | 623 | 10.1 | 1.0% | 0.1%
Detect | 575 | 0 (0 skipped) | 0.7% | 0.1%

Note, the high CPU usage for ffmpeg.

**Comment by NickM-27** [comment]
If you are on 0.12 then you should be following the 0.12 docs for mjpeg cameras https://deploy-preview-4055--frigate-docs.netlify.app/configuration/camera_specific#mjpeg-cameras

**Comment by onetoomany** [comment]
That's definitely created an improvement!
The ffmpeg CPU is registering 2% for the LD cameras, down from 50%
Process | P-ID | FPS | CPU % | Memory %
ffmpeg | 634 | 10.1 | 2.3% | 0.1%

with the GPU going from 1.19% to 12.49%

The real acid test is the overall power consumption of my system, as we've moved the processing from Frigate and the CPU to Go2rtc and GPU, but a level of processing still needs to be done.
- Old setup: 150W
- New setup: 125W
- HD cameras only: 100W
- No frigate: 90W

So in summary, we've halved the power consumption of the LD cameras. If there is anything else I can do, then great, otherwise I can declare victory on that!

Note, I'm running frigate in a CT on Proxmox.

```
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -c:v h264_qsv

go2rtc:
  streams:
    rear_of_shed: ffmpeg:http://username:password@IP/nphMotionJpeg?Resolution=640x480&Quality=Standard#video=h264#hardware # <- use hardware acceleration to create an h264 stream usable for other components.

cameras:
  rear_of_shed: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/rear_of_shed
          roles:
            - detect
            - rtmp
            - record
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
    zones:
      active_area:
        coordinates: 0,480,640,480,640,85,0,85
        objects:
          - person
          - dog
          - cat
          - bicycle
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640  # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10
```
