### ISSUE TITLE
[Camera Support]: Logs are confusing about corrupted recording segments

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5581]
### Describe the problem you are having

I have a variety of cameras. One particular type I'm still troubleshooting why recording doesn't work (this issue is _not_ to fix recording on those cameras). The problem is that when recording is enabled on one of these troublesome cameras, the logs indicate that a _different_ camera is having corrupt recording segments discarded. But it's not! The referenced timestamps for the otherwise-working camera do exist on disk, and I can seek to them in the recordings UI and they play just fine. But it's making it a _lot_ harder to figure out what's wrong with recording on the other camera.

In concrete terms of my config, whenever Bunk, Sewing, or Toy cameras have recording enabled (and don't work), Volleyball always claims to have corrupt recording segments. Interesting that it's always the volleyball camera complaining - perhaps because it's the last camera in the config (or alphabetically; my config is alphabetized).

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
# yaml-language-server: $schema=https://frigate.cutrer.us/api/config/schema.json

mqtt:
  ...

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-aac

ui:
  live_mode: webrtc
  use_experimental: false

birdseye:
  mode: objects
  width: 1920
  height: 1080
  restream: true

go2rtc:
  streams:
    back_yard_south:
      - rtsp://redacted/Streaming/Channels/101
      - "ffmpeg:back_yard_south#audio=aac"
    back_yard_south_sub: rtsp://redacted/Streaming/Channels/102
    basketball: rtsp://redacted/Streaming/Channels/101
    basketball_sub: rtsp://redacted/Streaming/Channels/102
    bunk: 
      - rtsp://redacted/Streaming/Channels/101
      - "ffmpeg:bunk#audio=aac"
    bunk_sub: rtsp://redacted/Streaming/Channels/102
    many_other_snipped_cameras...
    volleyball: rtsp://redacted/Streaming/Channels/101
    volleyball_sub: rtsp://redacted/Streaming/Channels/102
  webrtc:
    candidates:
      - redacted:8555
      - redacted:8555

detect:
  width: 640
  height: 360
  fps: 6
  max_disappeared: 18
  stationary:
    interval: 12

objects:
  track:
    - person
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 2
    post_capture: 2

snapshots:
  enabled: true
  retain:
    default: 14

cameras:
  back_yard_south:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard_south
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_yard_south_sub
          roles:
            - detect
    motion:
      mask:
        - 28,26,234,26,234,35,28,35 # timestamp
        - 350,30,0,37,0,0,640,0,640,200 # background
        - 374,45,434,166,476,144,516,181,502,304,355,236,308,120,349,86,312,69,334,0 # bushes
        - 0,360,489,360,428,316,378,333,363,318,242,318,223,212,183,171,169,230,194,325,0,296 # patio bushes
        - 183,0,184,0,185,24,147,63,62,72,0,104,0,0 # solar panels
    zones:
      back_yard_zone:
        coordinates: 389,169,406,129,385,95,403,84,616,249,555,360
      pool_zone:
        coordinates: 214,107,182,213,27,215,121,111
      pool_deck_zone:
        coordinates: 288,73,416,292,200,305,0,293,0,191,56,121,116,107,29,207,182,208,218,98,66,123,67,94
    objects:
      track:
        - person
        - cat
        - dog
        - horse
      filters:
        person:
          max_area: 6500
          mask:
            - 308,84,292,85,298,55

  basketball:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/basketball
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/basketball_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic
    motion:
      mask:
        - 28,26,234,26,234,35,28,35 # timestamp
        - 640,0,640,92,449,0 # backyard
    zones:
      basketball_zone:
        coordinates: 0,360,537,360,604,278,640,209,640,183,601,123,439,44,0,155
      crumps_zone:
        coordinates: 0,37,78,0,440,0,442,23,0,67
    objects:
      track:
        - car
        - person
        - cat
        - dog
        - horse
        - bicycle
        - motorcycle
      filters:
        car:
          min_area: 700
        person:
          min_area: 700

  bunk:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bunk?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bunk_sub
          roles:
            - detect
    motion:
      mask:
        - 28,22,234,22,234,31,28,31 # timestamp
        - 353,0,307,17,268,26,224,15,199,0 # fan
    zones:
      bunk_zone:
        coordinates: 640,360,640,0,379,0,300,42,273,265,50,277,26,360
      gaming_zone:
        coordinates: 227,93,238,267,178,269,177,93

  volleyball:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/volleyball
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/volleyball_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic
    motion:
      mask:
        - 28,26,234,26,234,35,28,35 # timestamp
        - 0,360,640,360,640,312,523,232,404,200,187,147,157,0,0,0 # pine tree and bushes
        - 490,33,640,98,640,0,149,0,152,16,212,13,414,21 # background
        - 640,0,640,193,548,326,535,0 # tree
    zones:
      back_yard_zone:
        coordinates: 247,167,462,215,567,253,640,336,640,159,529,84,425,63,311,58,150,69,0,143
      orchard_zone:
        coordinates: 143,65,356,59,528,85,457,34,188,24
    objects:
      track:
        - person
        - cat
        - dog
        - horse
      filters:
        person:
          max_ratio: 1.0
```

### Relevant log output

```shell
2023-02-24 16:50:56.738394881  [2023-02-24 16:50:56] frigate.comms.dispatcher       INFO    : Turning on recordings for bunk
2023-02-24 16:51:03.511045620  [2023-02-24 16:51:03] frigate.record                 WARNING : Failed to probe corrupt segment volleyball-20230224165100.mp4: 0 - b'[extract_extradata @ 0x55ef3db990c0] No start code is found.\n/tmp/cache/bunk-20230224165052.mp4: Invalid data found when processing input\n'
2023-02-24 16:51:03.511221570  [2023-02-24 16:51:03] frigate.record                 WARNING : Discarding a corrupt recording segment: volleyball-20230224165100.mp4
2023-02-24 16:51:13.493080604  [2023-02-24 16:51:13] frigate.record                 WARNING : Failed to probe corrupt segment volleyball-20230224165110.mp4: 0 - b'[extract_extradata @ 0x5631481e0400] No start code is found.\n/tmp/cache/bunk-20230224165102.mp4: Invalid data found when processing input\n'
2023-02-24 16:51:13.493178621  [2023-02-24 16:51:13] frigate.record                 WARNING : Discarding a corrupt recording segment: volleyball-20230224165110.mp4
2023-02-24 16:51:23.457860537  [2023-02-24 16:51:23] frigate.record                 WARNING : Failed to probe corrupt segment volleyball-20230224165120.mp4: 0 - b'[extract_extradata @ 0x55957495f100] No start code is found.\n/tmp/cache/bunk-20230224165112.mp4: Invalid data found when processing input\n'
2023-02-24 16:51:23.457865089  [2023-02-24 16:51:23] frigate.record                 WARNING : Discarding a corrupt recording segment: volleyball-20230224165120.mp4
<repeated over and over again>
2023-02-24 17:04:17.557836415  [2023-02-24 17:04:17] frigate.record                 WARNING : Failed to probe corrupt segment volleyball-20230224170410.mp4: 0 - b'[extract_extradata @ 0x55e7423ed4c0] No start code is found.\n/tmp/cache/bunk-20230224170402.mp4: Invalid data found when processing input\n'
2023-02-24 17:04:17.557991448  [2023-02-24 17:04:17] frigate.record                 WARNING : Discarding a corrupt recording segment: volleyball-20230224170410.mp4
2023-02-24 17:04:27.407762405  [2023-02-24 17:04:27] frigate.comms.dispatcher       INFO    : Turning off recordings for bunk
<no more error messages>
```

### FFprobe output from your camera

```shell
bunk:

[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" }, { "avg_frame_rate": "15/1", "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)", "display_aspect_ratio": "168:95", "height": 1520, "width": 2688 } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "display_aspect_ratio": "168:95", "height": 360, "width": 640 } ] } } ]

volleyball:

[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)", "display_aspect_ratio": "16:9", "height": 2160, "width": 3840 } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "display_aspect_ratio": "16:9", "height": 360, "width": 640 } ] } } ]
```

### Frigate stats

```json
{"back_yard_south":{"camera_fps":6.0,"capture_pid":483,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":488,"pid":427,"process_fps":6.0,"skipped_fps":0.0},"basketball":{"camera_fps":6.1,"capture_pid":486,"detection_enabled":1,"detection_fps":0.7,"ffmpeg_pid":495,"pid":429,"process_fps":6.1,"skipped_fps":0.0},"bunk":{"camera_fps":6.0,"capture_pid":489,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":504,"pid":431,"process_fps":6.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.3"},"1":{"cpu":"0.0","mem":"0.0"},"1001":{"cpu":"1.3","mem":"0.0"},"105":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.1"},"132":{"cpu":"0.0","mem":"0.1"},"142":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"160":{"cpu":"0.0","mem":"0.0"},"191":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"302370":{"cpu":"1.3","mem":"0.1"},"31":{"cpu":"0.0","mem":"0.0"},"361457":{"cpu":"0.3","mem":"0.0"},"361467":{"cpu":"0.3","mem":"0.0"},"364590":{"cpu":"0.3","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"412":{"cpu":"0.0","mem":"0.1"},"418":{"cpu":"2.3","mem":"0.0"},"419":{"cpu":"1.7","mem":"0.2"},"420":{"cpu":"6.3","mem":"0.2"},"427":{"cpu":"0.7","mem":"0.2"},"428":{"cpu":"0.0","mem":"0.0"},"429":{"cpu":"0.3","mem":"0.2"},"430":{"cpu":"0.0","mem":"0.0"},"431":{"cpu":"0.7","mem":"0.2"},"432":{"cpu":"0.3","mem":"0.2"},"433":{"cpu":"0.0","mem":"0.0"},"434":{"cpu":"6.6","mem":"0.2"},"435":{"cpu":"0.7","mem":"0.2"},"436":{"cpu":"0.0","mem":"0.0"},"437":{"cpu":"0.7","mem":"0.2"},"438":{"cpu":"0.7","mem":"0.2"},"439":{"cpu":"0.0","mem":"0.0"},"440":{"cpu":"0.3","mem":"0.2"},"441":{"cpu":"0.3","mem":"0.2"},"442":{"cpu":"0.0","mem":"0.0"},"443":{"cpu":"0.0","mem":"0.0"},"444":{"cpu":"0.7","mem":"0.2"},"445":{"cpu":"0.0","mem":"0.0"},"446":{"cpu":"0.3","mem":"0.2"},"447":{"cpu":"0.7","mem":"0.2"},"448":{"cpu":"0.0","mem":"0.0"},"449":{"cpu":"0.3","mem":"0.2"},"450":{"cpu":"1.0","mem":"0.2"},"451":{"cpu":"0.0","mem":"0.0"},"452":{"cpu":"0.3","mem":"0.2"},"453":{"cpu":"0.7","mem":"0.2"},"454":{"cpu":"0.0","mem":"0.0"},"455":{"cpu":"0.3","mem":"0.2"},"456":{"cpu":"0.0","mem":"0.0"},"457":{"cpu":"1.0","mem":"0.2"},"458":{"cpu":"0.3","mem":"0.2"},"459":{"cpu":"0.0","mem":"0.0"},"460":{"cpu":"0.3","mem":"0.2"},"461":{"cpu":"0.0","mem":"0.0"},"462":{"cpu":"0.7","mem":"0.2"},"463":{"cpu":"0.0","mem":"0.0"},"464":{"cpu":"0.7","mem":"0.2"},"465":{"cpu":"0.7","mem":"0.2"},"466":{"cpu":"0.0","mem":"0.0"},"467":{"cpu":"0.7","mem":"0.2"},"468":{"cpu":"0.0","mem":"0.0"},"469":{"cpu":"0.3","mem":"0.2"},"470":{"cpu":"0.0","mem":"0.0"},"471":{"cpu":"0.3","mem":"0.2"},"472":{"cpu":"0.7","mem":"0.2"},"473":{"cpu":"0.0","mem":"0.0"},"474":{"cpu":"0.3","mem":"0.2"},"475":{"cpu":"0.0","mem":"0.0"},"476":{"cpu":"0.3","mem":"0.2"},"477":{"cpu":"0.0","mem":"0.0"},"478":{"cpu":"0.3","mem":"0.2"},"479":{"cpu":"0.7","mem":"0.2"},"480":{"cpu":"0.0","mem":"0.0"},"481":{"cpu":"0.7","mem":"0.2"},"482":{"cpu":"0.0","mem":"0.0"},"483":{"cpu":"0.7","mem":"0.2"},"486":{"cpu":"0.3","mem":"0.2"},"487":{"cpu":"0.0","mem":"0.0"},"488":{"cpu":"1.3","mem":"0.1"},"489":{"cpu":"0.3","mem":"0.2"},"494":{"cpu":"0.0","mem":"0.0"},"495":{"cpu":"1.3","mem":"0.1"},"496":{"cpu":"0.3","mem":"0.2"},"499":{"cpu":"2.7","mem":"0.0"},"502":{"cpu":"0.3","mem":"0.2"},"504":{"cpu":"1.3","mem":"0.1"},"506":{"cpu":"0.0","mem":"0.0"},"507":{"cpu":"1.7","mem":"0.0"},"509":{"cpu":"1.0","mem":"0.2"},"510":{"cpu":"1.7","mem":"0.1"},"514":{"cpu":"0.0","mem":"0.0"},"517":{"cpu":"3.0","mem":"0.0"},"518":{"cpu":"0.3","mem":"0.2"},"519":{"cpu":"1.7","mem":"0.0"},"521":{"cpu":"1.0","mem":"0.1"},"523":{"cpu":"2.3","mem":"0.1"},"524":{"cpu":"0.3","mem":"0.2"},"526":{"cpu":"0.0","mem":"0.0"},"530":{"cpu":"2.3","mem":"0.0"},"531":{"cpu":"0.7","mem":"0.2"},"536":{"cpu":"1.3","mem":"0.1"},"538":{"cpu":"0.7","mem":"0.2"},"540":{"cpu":"3.7","mem":"0.0"},"541":{"cpu":"2.7","mem":"0.0"},"543":{"cpu":"0.0","mem":"0.0"},"544":{"cpu":"1.0","mem":"0.2"},"545":{"cpu":"1.3","mem":"0.1"},"549":{"cpu":"0.7","mem":"0.2"},"550":{"cpu":"3.3","mem":"0.0"},"552":{"cpu":"0.0","mem":"0.0"},"554":{"cpu":"1.3","mem":"0.1"},"555":{"cpu":"0.7","mem":"0.2"},"558":{"cpu":"1.7","mem":"0.1"},"559":{"cpu":"1.3","mem":"0.0"},"560":{"cpu":"0.7","mem":"0.2"},"565":{"cpu":"1.7","mem":"0.1"},"566":{"cpu":"0.0","mem":"0.1"},"567":{"cpu":"0.7","mem":"0.2"},"572":{"cpu":"1.7","mem":"0.1"},"574":{"cpu":"1.3","mem":"0.0"},"578":{"cpu":"1.3","mem":"0.1"},"579":{"cpu":"0.7","mem":"0.2"},"582":{"cpu":"1.3","mem":"0.1"},"584":{"cpu":"0.7","mem":"0.2"},"587":{"cpu":"2.7","mem":"0.0"},"588":{"cpu":"3.0","mem":"0.0"},"589":{"cpu":"3.0","mem":"0.0"},"595":{"cpu":"0.3","mem":"0.2"},"597":{"cpu":"2.0","mem":"0.0"},"603":{"cpu":"3.0","mem":"0.0"},"604":{"cpu":"0.7","mem":"0.2"},"605":{"cpu":"0.0","mem":"0.0"},"608":{"cpu":"1.0","mem":"0.2"},"609":{"cpu":"1.3","mem":"0.1"},"610":{"cpu":"1.3","mem":"0.1"},"611":{"cpu":"1.3","mem":"0.1"},"612":{"cpu":"1.3","mem":"0.0"},"615":{"cpu":"0.3","mem":"0.2"},"617":{"cpu":"2.3","mem":"0.0"},"619":{"cpu":"3.0","mem":"0.0"},"621":{"cpu":"0.7","mem":"0.2"},"624":{"cpu":"1.3","mem":"0.0"},"626":{"cpu":"0.0","mem":"0.0"},"631":{"cpu":"1.0","mem":"0.1"},"632":{"cpu":"1.7","mem":"0.0"},"633":{"cpu":"0.7","mem":"0.2"},"635":{"cpu":"1.0","mem":"0.1"},"636":{"cpu":"1.3","mem":"0.1"},"640":{"cpu":"3.0","mem":"0.0"},"641":{"cpu":"1.0","mem":"0.1"},"642":{"cpu":"0.3","mem":"0.2"},"644":{"cpu":"3.0","mem":"0.0"},"645":{"cpu":"1.3","mem":"0.1"},"646":{"cpu":"0.3","mem":"0.2"},"648":{"cpu":"1.7","mem":"0.0"},"652":{"cpu":"0.7","mem":"0.2"},"654":{"cpu":"1.7","mem":"0.0"},"658":{"cpu":"3.0","mem":"0.0"},"659":{"cpu":"2.7","mem":"0.0"},"663":{"cpu":"1.7","mem":"0.1"},"664":{"cpu":"0.7","mem":"0.2"},"666":{"cpu":"1.3","mem":"0.0"},"672":{"cpu":"0.3","mem":"0.2"},"675":{"cpu":"3.3","mem":"0.0"},"678":{"cpu":"1.7","mem":"0.0"},"679":{"cpu":"1.7","mem":"0.1"},"680":{"cpu":"0.7","mem":"0.2"},"684":{"cpu":"3.0","mem":"0.0"},"685":{"cpu":"1.7","mem":"0.1"},"690":{"cpu":"2.7","mem":"0.0"},"691":{"cpu":"0.3","mem":"0.2"},"695":{"cpu":"1.3","mem":"0.1"},"701":{"cpu":"1.7","mem":"0.0"},"702":{"cpu":"1.3","mem":"0.1"},"705":{"cpu":"0.7","mem":"0.2"},"709":{"cpu":"1.3","mem":"0.1"},"710":{"cpu":"0.7","mem":"0.2"},"711":{"cpu":"2.7","mem":"0.0"},"724":{"cpu":"0.3","mem":"0.2"},"725":{"cpu":"1.3","mem":"0.0"},"728":{"cpu":"1.7","mem":"0.0"},"732":{"cpu":"1.3","mem":"0.0"},"733":{"cpu":"1.3","mem":"0.0"},"734":{"cpu":"1.7","mem":"0.1"},"736":{"cpu":"1.3","mem":"0.0"},"737":{"cpu":"3.0","mem":"0.0"},"744":{"cpu":"3.0","mem":"0.0"},"747":{"cpu":"1.7","mem":"0.0"},"748":{"cpu":"1.3","mem":"0.1"},"768":{"cpu":"1.3","mem":"0.1"},"772":{"cpu":"1.3","mem":"0.0"},"773":{"cpu":"3.0","mem":"0.0"},"774":{"cpu":"1.7","mem":"0.0"},"778":{"cpu":"3.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"780":{"cpu":"1.7","mem":"0.1"},"782":{"cpu":"1.7","mem":"0.1"},"788":{"cpu":"1.3","mem":"0.0"},"791":{"cpu":"1.7","mem":"0.0"},"792":{"cpu":"1.7","mem":"0.0"},"794":{"cpu":"2.7","mem":"0.0"},"795":{"cpu":"1.7","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"801":{"cpu":"2.0","mem":"0.0"},"802":{"cpu":"1.7","mem":"0.0"},"803":{"cpu":"1.7","mem":"0.0"},"804":{"cpu":"1.3","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"90.7","mem":"0.0"},"93":{"cpu":"21.3","mem":"0.5"},"943":{"cpu":"1.7","mem":"0.0"},"MiB":{"cpu":"57075.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"4.61,"}},"deck":{"camera_fps":6.0,"capture_pid":496,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":510,"pid":432,"process_fps":6.0,"skipped_fps":0.0},"detection_fps":2.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.51,"pid":419}},"dining":{"camera_fps":6.0,"capture_pid":502,"detection_enabled":1,"detection_fps":1.3,"ffmpeg_pid":521,"pid":434,"process_fps":6.0,"skipped_fps":0.0},"doorbell":{"camera_fps":6.0,"capture_pid":509,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":523,"pid":435,"process_fps":6.0,"skipped_fps":0.0},"driveway":{"camera_fps":6.0,"capture_pid":518,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":536,"pid":437,"process_fps":6.0,"skipped_fps":0.0},"entry":{"camera_fps":6.1,"capture_pid":524,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":545,"pid":438,"process_fps":6.1,"skipped_fps":0.0},"family":{"camera_fps":6.0,"capture_pid":531,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":554,"pid":440,"process_fps":6.0,"skipped_fps":0.0},"fire_pit":{"camera_fps":6.0,"capture_pid":538,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":558,"pid":441,"process_fps":6.0,"skipped_fps":0.0},"gaming":{"camera_fps":6.1,"capture_pid":544,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":572,"pid":444,"process_fps":6.1,"skipped_fps":0.0},"garage":{"camera_fps":6.1,"capture_pid":549,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":565,"pid":446,"process_fps":6.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"7.94 %","mem":"- %"}},"great":{"camera_fps":6.1,"capture_pid":555,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":578,"pid":447,"process_fps":6.1,"skipped_fps":0.0},"hot_tub":{"camera_fps":6.0,"capture_pid":560,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":582,"pid":449,"process_fps":6.0,"skipped_fps":0.0},"john_deere":{"camera_fps":6.1,"capture_pid":567,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":611,"pid":450,"process_fps":6.1,"skipped_fps":0.0},"laundry":{"camera_fps":6.1,"capture_pid":579,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":609,"pid":452,"process_fps":6.1,"skipped_fps":0.0},"loft":{"camera_fps":6.0,"capture_pid":584,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":610,"pid":453,"process_fps":6.0,"skipped_fps":0.0},"loft_door":{"camera_fps":6.0,"capture_pid":595,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":635,"pid":455,"process_fps":6.0,"skipped_fps":0.0},"man_door":{"camera_fps":6.0,"capture_pid":604,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":636,"pid":457,"process_fps":6.0,"skipped_fps":0.0},"mud":{"camera_fps":6.0,"capture_pid":608,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":631,"pid":458,"process_fps":6.0,"skipped_fps":0.0},"pantry":{"camera_fps":6.0,"capture_pid":615,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":645,"pid":460,"process_fps":6.0,"skipped_fps":0.0},"patio":{"camera_fps":6.0,"capture_pid":621,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":685,"pid":462,"process_fps":6.0,"skipped_fps":0.0},"playset":{"camera_fps":6.0,"capture_pid":633,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":663,"pid":464,"process_fps":6.0,"skipped_fps":0.0},"porch":{"camera_fps":6.1,"capture_pid":642,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":679,"pid":465,"process_fps":6.1,"skipped_fps":0.0},"service":{"last_updated":1677259581,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":169.0,"mount_type":"tmpfs","total":201.3,"used":32.4},"/media/frigate/clips":{"free":201937.7,"mount_type":"ext4","total":241770.0,"used":27476.6},"/media/frigate/recordings":{"free":24567385.4,"mount_type":"ext4","total":27892949.5,"used":1925273.5},"/tmp/cache":{"free":708.9,"mount_type":"tmpfs","total":1000.0,"used":291.1}},"temperatures":{},"uptime":51361,"version":"0.12.0-27a31e7"},"sewing":{"camera_fps":6.1,"capture_pid":646,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":302370,"pid":467,"process_fps":6.1,"skipped_fps":0.0},"solar_panels":{"camera_fps":6.0,"capture_pid":652,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":695,"pid":469,"process_fps":6.0,"skipped_fps":0.0},"south_side":{"camera_fps":6.1,"capture_pid":664,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":702,"pid":471,"process_fps":6.1,"skipped_fps":0.0},"street":{"camera_fps":6.0,"capture_pid":672,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":709,"pid":472,"process_fps":6.0,"skipped_fps":0.0},"theater_back":{"camera_fps":6.0,"capture_pid":680,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":734,"pid":474,"process_fps":6.0,"skipped_fps":0.0},"theater_front":{"camera_fps":6.1,"capture_pid":691,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":748,"pid":476,"process_fps":6.1,"skipped_fps":0.0},"toy":{"camera_fps":6.0,"capture_pid":705,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":780,"pid":478,"process_fps":6.0,"skipped_fps":0.0},"trampoline":{"camera_fps":6.1,"capture_pid":710,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":782,"pid":479,"process_fps":6.1,"skipped_fps":0.0},"volleyball":{"camera_fps":6.0,"capture_pid":724,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":768,"pid":481,"process_fps":6.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Bunk is Hikvision DS-2CD2443G0-IW 2.8mm; Volleyball is Hikvision DS-2CD2185FWD-ISB 2.8mm

### Any other information that may be helpful

All cameras (except Sewing) are hardwired.
