### ISSUE TITLE
[Camera Support]: Hikvision DS-2CD2443G0-IW Can't Record

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5585]
### Describe the problem you are having

I get an error about corrupted segments when trying to record with this specific model of camera. I have 3 of this model, and none of them will record. I have similar Hikvision cameras that have their video streams configured the same way (HEVC, 4k, same bitrate, H.265+ disabled, etc)., and I'm able to record them just fine.

WebRTC and MSE both work for live viewing of the camera, including audio.

Any suggestions or tips on how to tweak the camera's settings to make it recordable would be appreciated.

I also temporarily enabled debug logging for the record process, and no additional (relevant) log lines were added.

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
# yaml-language-server: $schema=https://frigate.cutrer.us/api/config/schema.json

mqtt:
  <redacted>

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-aac

ui:
  live_mode: webrtc
  use_experimental: false

birdseye:
  mode: objects
  width: 1920
  height: 1080
  restream: true

go2rtc:
  streams:
    bunk: 
      - rtsp://redacted/Streaming/Channels/101
      - "ffmpeg:bunk#audio=aac"
    bunk_sub: rtsp://admin:8j)F3m%23JeyJNNeYA@192.168.84.51/Streaming/Channels/102
    family:
      - rtsp://redacted/Streaming/Channels/101
      - "ffmpeg:family#audio=aac"
    family_sub: rtsp://redacted/Streaming/Channels/102
    <lots more cameras>

detect:
  width: 640
  height: 360
  fps: 6
  max_disappeared: 18
  stationary:
    interval: 12

objects:
  track:
    - person
    - dog
    - cat

record:
  enabled: true
  retain:
    days: 14
    mode: all
  events:
    pre_capture: 2
    post_capture: 2

snapshots:
  enabled: true
  retain:
    default: 14

cameras:
  bunk:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bunk?video=copy&audio=aac # I've tried variations of these params - not having any, copying the audio stream, converting it
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bunk_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic # I attempted recording without any audio stream to see if it would help
    motion:
      mask:
        - 28,22,234,22,234,31,28,31 # timestamp
        - 353,0,307,17,268,26,224,15,199,0 # fan
    zones:
      bunk_zone:
        coordinates: 640,360,640,0,379,0,300,42,273,265,50,277,26,360
      gaming_zone:
        coordinates: 227,93,238,267,178,269,177,93

  family: # this camera records just fine, including audio
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/family
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/family_sub
          roles:
            - detect
    motion:
      mask:
        - 28,26,234,26,234,35,28,35 # timestamp
    zones:
      family_zone:
        coordinates: 94,360,500,360,588,143,301,28,0,142,0,162
      gaming_zone:
        coordinates: 100,48,205,72,0,173,0,86
    objects:
      filters:
        person:
          min_area: 1000
```

### Relevant log output

```shell
2023-02-24 21:15:09.805085538  [2023-02-24 21:15:09] frigate.record                 WARNING : Failed to probe corrupt segment volleyball-20230224211503.mp4: 0 - b'[extract_extradata @ 0x55c784ff8240] No start code is found.\n/tmp/cache/bunk-20230224211455.mp4: Invalid data found when processing input\n'
2023-02-24 21:15:09.805185678  [2023-02-24 21:15:09] frigate.record                 WARNING : Discarding a corrupt recording segment: volleyball-20230224211503.mp4
```

### FFprobe output from your camera

```shell
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "AAC (Advanced Audio Coding)" }, { "avg_frame_rate": "25/1", "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)", "display_aspect_ratio": "168:95", "height": 1520, "width": 2688 } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "15/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "display_aspect_ratio": "168:95", "height": 360, "width": 640 } ] } } ]
```

### Frigate stats

```json
{"back_yard_south":{"camera_fps":6.1,"capture_pid":481,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":486,"pid":428,"process_fps":6.1,"skipped_fps":0.0},"basketball":{"camera_fps":6.1,"capture_pid":485,"detection_enabled":1,"detection_fps":0.5,"ffmpeg_pid":493,"pid":430,"process_fps":6.1,"skipped_fps":0.0},"bunk":{"camera_fps":6.1,"capture_pid":488,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":499,"pid":432,"process_fps":6.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.6"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"128":{"cpu":"0.0","mem":"0.0"},"129":{"cpu":"0.0","mem":"0.0"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"145":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"165":{"cpu":"0.0","mem":"0.0"},"192":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"40":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"412":{"cpu":"0.0","mem":"0.1"},"419":{"cpu":"2.0","mem":"0.0"},"420":{"cpu":"1.3","mem":"0.2"},"421":{"cpu":"23.8","mem":"0.2"},"428":{"cpu":"0.7","mem":"0.2"},"429":{"cpu":"0.0","mem":"0.0"},"430":{"cpu":"0.3","mem":"0.2"},"431":{"cpu":"0.0","mem":"0.0"},"432":{"cpu":"0.7","mem":"0.2"},"433":{"cpu":"0.3","mem":"0.2"},"434":{"cpu":"0.0","mem":"0.0"},"435":{"cpu":"0.3","mem":"0.2"},"436":{"cpu":"0.0","mem":"0.0"},"437":{"cpu":"0.7","mem":"0.2"},"438":{"cpu":"1.3","mem":"0.2"},"439":{"cpu":"0.0","mem":"0.0"},"440":{"cpu":"0.3","mem":"0.2"},"441":{"cpu":"0.3","mem":"0.2"},"442":{"cpu":"0.0","mem":"0.0"},"443":{"cpu":"0.3","mem":"0.2"},"444":{"cpu":"0.3","mem":"0.2"},"445":{"cpu":"0.0","mem":"0.0"},"446":{"cpu":"0.0","mem":"0.0"},"447":{"cpu":"0.3","mem":"0.2"},"448":{"cpu":"0.7","mem":"0.2"},"449":{"cpu":"0.3","mem":"0.2"},"450":{"cpu":"0.7","mem":"0.2"},"451":{"cpu":"4.3","mem":"0.2"},"452":{"cpu":"0.7","mem":"0.2"},"453":{"cpu":"0.7","mem":"0.2"},"454":{"cpu":"0.0","mem":"0.0"},"455":{"cpu":"0.7","mem":"0.2"},"456":{"cpu":"0.0","mem":"0.0"},"457":{"cpu":"0.3","mem":"0.2"},"458":{"cpu":"0.0","mem":"0.0"},"459":{"cpu":"0.7","mem":"0.2"},"460":{"cpu":"0.3","mem":"0.2"},"461":{"cpu":"0.0","mem":"0.0"},"462":{"cpu":"0.3","mem":"0.2"},"463":{"cpu":"0.0","mem":"0.0"},"464":{"cpu":"0.3","mem":"0.2"},"465":{"cpu":"0.0","mem":"0.0"},"466":{"cpu":"0.0","mem":"0.2"},"467":{"cpu":"0.3","mem":"0.2"},"468":{"cpu":"0.0","mem":"0.0"},"469":{"cpu":"0.3","mem":"0.2"},"470":{"cpu":"0.3","mem":"0.2"},"471":{"cpu":"0.0","mem":"0.0"},"472":{"cpu":"0.3","mem":"0.2"},"473":{"cpu":"0.0","mem":"0.0"},"474":{"cpu":"0.3","mem":"0.2"},"475":{"cpu":"0.0","mem":"0.0"},"476":{"cpu":"0.3","mem":"0.2"},"477":{"cpu":"0.3","mem":"0.2"},"478":{"cpu":"0.0","mem":"0.0"},"479":{"cpu":"0.3","mem":"0.2"},"480":{"cpu":"0.0","mem":"0.0"},"481":{"cpu":"0.7","mem":"0.2"},"482":{"cpu":"0.0","mem":"0.0"},"485":{"cpu":"0.7","mem":"0.2"},"486":{"cpu":"1.3","mem":"0.1"},"487":{"cpu":"0.0","mem":"0.0"},"488":{"cpu":"0.7","mem":"0.2"},"493":{"cpu":"1.3","mem":"0.1"},"494":{"cpu":"2.6","mem":"0.0"},"495":{"cpu":"0.7","mem":"0.2"},"498":{"cpu":"0.0","mem":"0.0"},"499":{"cpu":"1.7","mem":"0.1"},"504":{"cpu":"0.7","mem":"0.2"},"505":{"cpu":"0.0","mem":"0.0"},"506":{"cpu":"1.3","mem":"0.0"},"507":{"cpu":"1.3","mem":"0.1"},"510":{"cpu":"1.0","mem":"0.2"},"513":{"cpu":"1.7","mem":"0.0"},"515":{"cpu":"0.0","mem":"0.0"},"516":{"cpu":"1.3","mem":"0.1"},"519":{"cpu":"0.7","mem":"0.2"},"521":{"cpu":"2.6","mem":"0.0"},"522":{"cpu":"2.3","mem":"0.1"},"525":{"cpu":"1.7","mem":"0.0"},"527":{"cpu":"0.0","mem":"0.0"},"528":{"cpu":"0.3","mem":"0.2"},"532":{"cpu":"3.0","mem":"0.0"},"535":{"cpu":"1.3","mem":"0.1"},"536":{"cpu":"3.6","mem":"0.0"},"537":{"cpu":"0.3","mem":"0.2"},"538":{"cpu":"0.0","mem":"0.0"},"539":{"cpu":"1.3","mem":"0.1"},"547":{"cpu":"0.0","mem":"0.0"},"5497":{"cpu":"0.0","mem":"0.0"},"550":{"cpu":"3.0","mem":"0.0"},"551":{"cpu":"3.0","mem":"0.0"},"5519":{"cpu":"0.3","mem":"0.0"},"552":{"cpu":"1.3","mem":"0.1"},"553":{"cpu":"0.3","mem":"0.2"},"554":{"cpu":"0.0","mem":"0.0"},"555":{"cpu":"2.0","mem":"0.0"},"557":{"cpu":"0.7","mem":"0.2"},"560":{"cpu":"1.7","mem":"0.0"},"561":{"cpu":"0.0","mem":"0.0"},"564":{"cpu":"1.3","mem":"0.1"},"566":{"cpu":"3.3","mem":"0.0"},"567":{"cpu":"0.7","mem":"0.2"},"568":{"cpu":"1.7","mem":"0.1"},"569":{"cpu":"0.0","mem":"0.0"},"570":{"cpu":"2.0","mem":"0.0"},"573":{"cpu":"0.7","mem":"0.2"},"576":{"cpu":"1.3","mem":"0.1"},"578":{"cpu":"0.7","mem":"0.2"},"581":{"cpu":"0.0","mem":"0.0"},"583":{"cpu":"2.0","mem":"0.0"},"584":{"cpu":"2.6","mem":"0.0"},"585":{"cpu":"2.0","mem":"0.0"},"586":{"cpu":"0.7","mem":"0.2"},"590":{"cpu":"3.0","mem":"0.0"},"591":{"cpu":"0.7","mem":"0.2"},"592":{"cpu":"1.3","mem":"0.1"},"594":{"cpu":"0.0","mem":"0.0"},"596":{"cpu":"1.0","mem":"0.2"},"600":{"cpu":"1.3","mem":"0.1"},"601":{"cpu":"0.7","mem":"0.2"},"605":{"cpu":"9.2","mem":"0.1"},"606":{"cpu":"1.3","mem":"0.1"},"608":{"cpu":"0.7","mem":"0.2"},"609":{"cpu":"1.3","mem":"0.1"},"610":{"cpu":"1.7","mem":"0.1"},"614":{"cpu":"0.3","mem":"0.2"},"618":{"cpu":"1.7","mem":"0.0"},"619":{"cpu":"2.6","mem":"0.0"},"623":{"cpu":"1.7","mem":"0.0"},"625":{"cpu":"1.7","mem":"0.1"},"626":{"cpu":"0.7","mem":"0.2"},"627":{"cpu":"2.6","mem":"0.0"},"628":{"cpu":"2.6","mem":"0.0"},"632":{"cpu":"1.3","mem":"0.0"},"638":{"cpu":"0.7","mem":"0.2"},"651":{"cpu":"0.3","mem":"0.2"},"662":{"cpu":"3.0","mem":"0.0"},"663":{"cpu":"1.0","mem":"0.1"},"666":{"cpu":"1.3","mem":"0.1"},"667":{"cpu":"1.7","mem":"0.1"},"670":{"cpu":"1.3","mem":"0.0"},"671":{"cpu":"1.7","mem":"0.1"},"672":{"cpu":"3.3","mem":"0.0"},"674":{"cpu":"1.7","mem":"0.1"},"675":{"cpu":"3.0","mem":"0.0"},"676":{"cpu":"0.7","mem":"0.2"},"680":{"cpu":"0.0","mem":"0.2"},"685":{"cpu":"3.0","mem":"0.0"},"686":{"cpu":"1.3","mem":"0.0"},"687":{"cpu":"2.6","mem":"0.0"},"688":{"cpu":"0.3","mem":"0.2"},"692":{"cpu":"1.7","mem":"0.0"},"695":{"cpu":"2.6","mem":"0.0"},"699":{"cpu":"0.3","mem":"0.2"},"706":{"cpu":"2.6","mem":"0.0"},"708":{"cpu":"2.0","mem":"0.0"},"711":{"cpu":"0.3","mem":"0.2"},"716":{"cpu":"1.7","mem":"0.0"},"717":{"cpu":"0.0","mem":"0.1"},"718":{"cpu":"0.3","mem":"0.2"},"719":{"cpu":"1.7","mem":"0.1"},"722":{"cpu":"1.3","mem":"0.1"},"725":{"cpu":"1.7","mem":"0.0"},"726":{"cpu":"1.7","mem":"0.0"},"727":{"cpu":"0.7","mem":"0.2"},"732":{"cpu":"1.3","mem":"0.1"},"735":{"cpu":"1.7","mem":"0.0"},"736":{"cpu":"0.7","mem":"0.2"},"737":{"cpu":"1.7","mem":"0.0"},"740":{"cpu":"1.7","mem":"0.1"},"742":{"cpu":"0.7","mem":"0.2"},"743":{"cpu":"1.3","mem":"0.1"},"745":{"cpu":"1.0","mem":"0.0"},"753":{"cpu":"1.3","mem":"0.1"},"754":{"cpu":"0.7","mem":"0.2"},"760":{"cpu":"1.3","mem":"0.0"},"761":{"cpu":"3.0","mem":"0.0"},"762":{"cpu":"1.0","mem":"0.1"},"763":{"cpu":"3.0","mem":"0.0"},"769":{"cpu":"1.3","mem":"0.0"},"775":{"cpu":"3.3","mem":"0.0"},"781":{"cpu":"1.3","mem":"0.1"},"785":{"cpu":"3.3","mem":"0.0"},"786":{"cpu":"1.7","mem":"0.0"},"787":{"cpu":"1.7","mem":"0.0"},"789":{"cpu":"1.7","mem":"0.1"},"79":{"cpu":"0.0","mem":"0.0"},"792":{"cpu":"2.0","mem":"0.0"},"793":{"cpu":"1.7","mem":"0.0"},"797":{"cpu":"1.7","mem":"0.0"},"798":{"cpu":"1.7","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"803":{"cpu":"1.7","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"81.8","mem":"0.0"},"93":{"cpu":"18.8","mem":"0.5"},"944":{"cpu":"1.7","mem":"0.0"},"MiB":{"cpu":"57545.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"7.22,"}},"deck":{"camera_fps":6.0,"capture_pid":495,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":507,"pid":433,"process_fps":6.0,"skipped_fps":0.0},"detection_fps":6.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.72,"pid":420}},"dining":{"camera_fps":6.0,"capture_pid":504,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":516,"pid":435,"process_fps":6.0,"skipped_fps":0.0},"doorbell":{"camera_fps":6.1,"capture_pid":510,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":522,"pid":437,"process_fps":6.1,"skipped_fps":0.0},"driveway":{"camera_fps":6.1,"capture_pid":519,"detection_enabled":1,"detection_fps":0.6,"ffmpeg_pid":535,"pid":438,"process_fps":6.1,"skipped_fps":0.0},"entry":{"camera_fps":6.1,"capture_pid":528,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":539,"pid":440,"process_fps":6.1,"skipped_fps":0.0},"family":{"camera_fps":6.0,"capture_pid":537,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":552,"pid":441,"process_fps":6.0,"skipped_fps":0.0},"fire_pit":{"camera_fps":6.1,"capture_pid":553,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":564,"pid":443,"process_fps":6.1,"skipped_fps":0.0},"gaming":{"camera_fps":6.0,"capture_pid":557,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":568,"pid":444,"process_fps":6.0,"skipped_fps":0.0},"garage":{"camera_fps":6.1,"capture_pid":567,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":576,"pid":447,"process_fps":6.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"8.19 %","mem":"- %"}},"great":{"camera_fps":6.0,"capture_pid":573,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":592,"pid":448,"process_fps":6.0,"skipped_fps":0.0},"hot_tub":{"camera_fps":6.0,"capture_pid":578,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":600,"pid":449,"process_fps":6.0,"skipped_fps":0.0},"john_deere":{"camera_fps":6.0,"capture_pid":586,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":609,"pid":450,"process_fps":6.0,"skipped_fps":0.0},"laundry":{"camera_fps":6.1,"capture_pid":591,"detection_enabled":1,"detection_fps":1.9,"ffmpeg_pid":606,"pid":451,"process_fps":6.1,"skipped_fps":0.0},"loft":{"camera_fps":6.1,"capture_pid":596,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":610,"pid":452,"process_fps":6.1,"skipped_fps":0.0},"loft_door":{"camera_fps":6.0,"capture_pid":601,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":625,"pid":453,"process_fps":6.0,"skipped_fps":0.0},"man_door":{"camera_fps":6.0,"capture_pid":608,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":666,"pid":455,"process_fps":6.0,"skipped_fps":0.0},"mud":{"camera_fps":6.0,"capture_pid":614,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":663,"pid":457,"process_fps":6.0,"skipped_fps":0.0},"pantry":{"camera_fps":6.1,"capture_pid":626,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":671,"pid":459,"process_fps":6.1,"skipped_fps":0.0},"patio":{"camera_fps":6.1,"capture_pid":638,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":667,"pid":460,"process_fps":6.1,"skipped_fps":0.0},"playset":{"camera_fps":6.0,"capture_pid":651,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":674,"pid":462,"process_fps":6.0,"skipped_fps":0.0},"porch":{"camera_fps":6.0,"capture_pid":676,"detection_enabled":1,"detection_fps":1.6,"ffmpeg_pid":722,"pid":464,"process_fps":6.1,"skipped_fps":0.0},"service":{"last_updated":1677273606,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":170.8,"mount_type":"tmpfs","total":201.3,"used":30.5},"/media/frigate/clips":{"free":201810.7,"mount_type":"ext4","total":241770.0,"used":27603.5},"/media/frigate/recordings":{"free":24160967.5,"mount_type":"ext4","total":27892949.5,"used":2331691.4},"/tmp/cache":{"free":744.1,"mount_type":"tmpfs","total":1000.0,"used":255.9}},"temperatures":{},"uptime":504,"version":"0.12.0-27a31e7"},"sewing":{"camera_fps":8.4,"capture_pid":680,"detection_enabled":1,"detection_fps":2.0,"ffmpeg_pid":717,"pid":466,"process_fps":2.5,"skipped_fps":0.0},"solar_panels":{"camera_fps":6.0,"capture_pid":688,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":719,"pid":467,"process_fps":6.0,"skipped_fps":0.0},"south_side":{"camera_fps":6.1,"capture_pid":699,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":743,"pid":469,"process_fps":6.1,"skipped_fps":0.0},"street":{"camera_fps":6.1,"capture_pid":711,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":732,"pid":470,"process_fps":6.1,"skipped_fps":0.0},"theater_back":{"camera_fps":6.0,"capture_pid":718,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":740,"pid":472,"process_fps":6.0,"skipped_fps":0.0},"theater_front":{"camera_fps":6.1,"capture_pid":727,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":753,"pid":474,"process_fps":6.1,"skipped_fps":0.0},"toy":{"camera_fps":6.1,"capture_pid":736,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":762,"pid":476,"process_fps":6.1,"skipped_fps":0.0},"trampoline":{"camera_fps":6.1,"capture_pid":742,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":781,"pid":477,"process_fps":6.1,"skipped_fps":0.0},"volleyball":{"camera_fps":6.0,"capture_pid":754,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":789,"pid":479,"process_fps":6.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

bunk: Hikvision DS-2CD2443G0-IW 2.8mm; family: DS-2CD2183G0-IU 2.8mm

### Any other information that may be helpful

Note that the log line mentions volleyball; it _is_ the bunk camera that's having issues (see #5581). I also grabbed a temp file from the cache and ran `ffprobe` directly on it (I'm not sure if I should be passing additional parameters); here's the full output:

```
# ffprobe bunk-20230224210511.mp4 
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[extract_extradata @ 0x55e7ec062fc0] No start code is found.
bunk-20230224210511.mp4: Invalid data found when processing input
```

**Comment by NickM-27** [comment]
Maybe try running the entire camera with the ffmpeg module in go2rtc

```
go2rtc:
  streams:
    bunk: 
      - "ffmpeg:rtsp://redacted/Streaming/Channels/101#video=copy#audio=copy#audio=aac"
```

**Comment by ccutrer** [comment]
No dice. The go2rtc logs start containing this:

```
2023-02-24 21:38:23.114012970  21:38:23.113 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-02-24 21:38:23.115146247  21:38:23.115 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:rtsp://redacted/Streaming/Channels/101#video=copy#audio=copy#audio=aac
```

and the frigate logs contain:

```
2023-02-24 21:38:41.226304522  [2023-02-24 21:38:41] ffmpeg.bunk.record             ERROR   : [rtsp @ 0x55565b428000] method DESCRIBE failed: 404 Not Found
2023-02-24 21:38:41.226589905  [2023-02-24 21:38:41] ffmpeg.bunk.record             ERROR   : rtsp://127.0.0.1:8554/bunk: Server returned 404 Not Found
2023-02-24 21:38:41.232161593  [2023-02-24 21:38:41] watchdog.bunk                  INFO    : Terminating the existing ffmpeg process...
2023-02-24 21:38:41.232273602  [2023-02-24 21:38:41] watchdog.bunk                  INFO    : Waiting for ffmpeg to exit gracefully...
```

I also tried changing my `input_args` to just `preset-rtsp-restream` to see if it was low-latency causing the problems. No change in output.

**Comment by NickM-27** [comment]
Set your go2rtc logs exec to trace level so we can see why it's failing

**Comment by jtronicus** [comment]
I had a similar issue, but with a different model of Hikvision camera.

DS-2CD2042WD-I - works fine with or without go2rtc
DC-2CD2532F-IS - works without go2rtc, but did not work with go2rtc

I ended up having to update the firmware on the 2CD2532F.  Once I updated to firmware 5.4.5, everything worked as expected

``` streams:
    DS-2CD2042WD-I_sub:
      - rtsp://user:pass@192.x.x.1:554/Streaming/Channels/2
    DS-2CD2042WD-I:
      - rtsp://user:pass@192.x.x.1:554/Streaming/Channels/1
    DC-2CD2532F-IS_sub:
      - rtsp://user:pass@192.x.x.2:554/Streaming/Channels/2
    DC-2CD2532F-IS:
      - ffmpeg:user:pass@192.x.x.2:554/Streaming/Channels/1#video=copy#audio=aac
  ```

**Comment by ccutrer** [comment]
> Set your go2rtc logs exec to trace level so we can see why it's failing

```
2023-02-27 17:11:04.229217129  Input #0, rtsp, from 'rtsp://redacted/Streaming/Channels/101':
2023-02-27 17:11:04.229219797    Metadata:
2023-02-27 17:11:04.229249181      title           : Media Presentation
2023-02-27 17:11:04.229252141    Duration: N/A, start: 0.000000, bitrate: N/A
2023-02-27 17:11:04.229414841    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 2688x1520 [SAR 1:1 DAR 168:95], 25 fps, 25 tbr, 90k tbn
2023-02-27 17:11:04.229471207    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
2023-02-27 17:11:04.230083122  Stream mapping:
2023-02-27 17:11:04.230218565    Stream #0:0 -> #0:0 (copy)
2023-02-27 17:11:04.230239293    Stream #0:1 -> #0:1 (copy)
2023-02-27 17:11:04.230263180    Stream #0:1 -> #0:2 (pcm_mulaw (native) -> aac (native))
2023-02-27 17:11:04.230266703  Press [q] to stop, [?] for help
2023-02-27 17:11:04.262744355  size=N/A time=00:00:01.96 bitrate=N/A speed=0.95x    
size=N/A time=00:00:01.83 bitrate=N/A speed=0.89x    
[aac @ 0x557eecbab8c0] Too many bits 8832.000000 > 6144 per frame requested, clamping to max
2023-02-27 17:11:04.265300957  Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
2023-02-27 17:11:04.265304339  Error initializing output stream 0:2 -- 
2023-02-27 17:11:04.265529174  17:11:04.265 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-02-27 17:11:04.265730097  [aac @ 0x557eecbab8c0] Qavg: nan
2023-02-27 17:11:04.266517314  Conversion failed!
2023-02-27 17:11:04.267051334  17:11:04.266 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:rtsp://admin:8jF3mJeyJNNeYA@192.168.84.51/Streaming/Channels/101#video=copy#audio=copy#audio=aac
2023-02-27 17:11:04.267092209  17:11:04.267 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=bunk
```

> I ended up having to update the firmware on the 2CD2532F. Once I updated to firmware 5.4.5, everything worked as expected

No dice, I'm already on the latest firmware. I also tried recording direct from the camera, not via the restroom, and it failed in the same way as before.

**Comment by NickM-27** [comment]
Looks like the audio is not able to be converted to aac audio, I would suggest this setup for the cameras which are having this issue

```yaml
go2rtc:
  streams:
    bunk: 
      - rtsp://redacted/Streaming/Channels/101
    bunk_sub: rtsp://redacted/Streaming/Channels/102

...

cameras:
  bunk:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bunk?video=copy&audio=copy 
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bunk_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
```
