### ISSUE TITLE
[Support]: Frigate not showing events in HA GUI

### ISSUE THREAD

**Issue by hhinma** [blakeblackshear/frigate#5612]
### Describe the problem you are having

Frigate HA addon GUI is not showing events.   Detection/motion events appear to be detected since snapshots are posted to MQTT, and my detection automation that drives telegram notify functions as expected - just no events reported in the GUI.

<img width="486" alt="car-detect" src="https://user-images.githubusercontent.com/8053813/221874345-2c7229f3-caa2-4499-ba8c-4f195e9bfa95.png">

### Version

0.10.1-83481AF,    HACS integration 3.0.1

### Frigate config file

```yaml
mqtt:
  host: 10.2.1.201
  user: XXX
  password: XXX

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
    - -an
    
#ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p 

birdseye:
  enabled: True
  mode: objects

cameras:

  front:
    ffmpeg:
      inputs:
        - path: rtsps://10.2.1.1:7441/1h0dBMJPytuU4YFP?enableSrtp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
        - bus
      filters:
        car:
          mask: 
            - 792,0,0,0,0,379,651,108,786,134,793,60
            - 939,0,661,0,653,114,929,195
            - 1024,0,595,0,606,144,1024,263
        motorcycle: 
          mask: 
            - 792,0,0,0,0,379,651,108,786,134,793,60
        person:
          mask:
            - 792,0,0,0,0,379,651,108,786,134,793,60
          min_area: 5000
          min_score: 0.6
    snapshots: 
      enabled: True 
      timestamp: True 
      bounding_box: True 
      retain: 
        default: 30
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects

  barn:
    ffmpeg:
      inputs:
        - path: rtsps://10.2.1.1:7441/q3DheemE97w1DoAx?enableSrtp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
        - horse
        - sheep
        - cow
        - bear
        - kite
      filters:
        person:
          mask:
            - 1432,63,1449,157,1209,177,1206,86
          min_area: 5000
          min_score: 0.6
    snapshots: 
      enabled: True 
      timestamp: True 
      bounding_box: True 
      retain: 
        default: 30
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
          
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsps://10.2.1.1:7441/3hVDRyz8emUThJ2S?enableSrtp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - car
        - motorcycle
        - bus        
      filters:
        car:
          mask:
            - 1024,0,1024,86,654,67,374,49,369,0
        motorcycle:
          mask:
            - 1024,0,1024,86,654,67,374,49,369,0 
        bus:
          mask:
            - 1024,0,1024,86,654,67,374,49,369,0
        person:
          min_area: 5000
          min_score: 0.6  
    snapshots: 
      enabled: True 
      timestamp: True 
      bounding_box: True 
      retain: 
        default: 30
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects

  House1stFloor:
    ffmpeg:
      inputs:
        - path: rtsps://10.2.1.1:7441/n0ZTBjRq8IdEc0HI?enableSrtp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          min_score: 0.6  
    snapshots: 
      enabled: True 
      timestamp: True 
      bounding_box: True 
      retain: 
        default: 30
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects

  BarnAuditorium:
    ffmpeg:
      inputs:
        - path: rtsps://10.2.1.1:7441/pU6XIr0PqscuPXz4?enableSrtp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1024
      height: 576
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          min_score: 0.6  
    snapshots: 
      enabled: True 
      timestamp: True 
      bounding_box: True 
      retain: 
        default: 30
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects          
          
            
detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

unifi g3

### Any other information that may be helpful

I have been unable to determine precisely when this behavior began since I tightened up the masks a couple of months ago, and detections are relatively infrequent.   I noticed this yesterday when I got a telegram notification of a car from my automation but the frigate GUI did not show any events.
