### ISSUE TITLE
[Support]: TrackMix Wifi Recordings not working

### ISSUE THREAD

**Issue by angrycatmeowmeow** [blakeblackshear/frigate#5613]
### Describe the problem you are having

Reolink Trackmix Wifi snapshots and streams work but I get the following error in the video player when trying to view events:

The media could not be loaded, either because the server or network failed or because the format is not supported.

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
go2rtc:
  streams:
        driveway_sub:
      - rtsp://user:pass@192.168.50.110:554/Preview_01_sub
 


cameras:
    driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record    
    record:
      enabled: True
      events:
        required_zones:
          - not_street
        retain:
          mode: motion
          default: 2
    detect:
      width: 896
      height: 512
      fps: 15
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - bird
    zones:
      not_street:
        coordinates: 481,138,896,204,896,512,0,512,0,151
        objects:
          - person
          - dog
          - cat
          - bird
          - car

          
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 2
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Trackmix Wifi

**Comment by NickM-27** [comment]
if you open chrome://media-internals/ and try to play back it will show the issue / logs

**Comment by angrycatmeowmeow** [comment]
```render_id: 1267
player_id: 29
created: 2023-02-28 17:46:18.115 UTC
origin_url: http://homeassistant.local:8123/
kFrameUrl: http://homeassistant.local:8123/events?cameras=driveway&labels=person
kFrameTitle: Frigate
url: blob:http://homeassistant.local:8123/aabbee4c-40b4-4473-be9e-897a0f3f4f52
kTextTracks: 
info: Selected D3D11VideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [896,512], visible rect: [0,0,896,512], natural size: [896,512], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}
kRendererName: RendererImpl
pipeline_state: kStopped
kVideoTracks: [object Object]
kAudioTracks: [object Object]
event: kWebMediaPlayerDestroyed
kIsAudioDecryptingDemuxerStream: false
kAudioDecoderName: FFmpegAudioDecoder
kIsPlatformAudioDecoder: false
debug: Video rendering in low delay mode.
kIsVideoDecryptingDemuxerStream: false
kVideoDecoderName: D3D11VideoDecoder
kIsPlatformVideoDecoder: true
error: [object Object]
warning: audio decoder fallback after initial decode error.
duration: 44.692
`

**Comment by NickM-27** [comment]
Looks like the camera is sending crap audio, you'll probably need to use ffmpeg module with it

```yaml
go2rtc:
  streams:
    driveway_sub:
      - ffmpeg:rtsp://user:pass@192.168.50.110:554/Preview_01_sub#video=copy#audio=aac
```
