### ISSUE TITLE
[Camera Support]: Wyze Audio not syncd with video

### ISSUE THREAD

**Issue by ratbich** [blakeblackshear/frigate#5614]
### Describe the problem you are having

When watching playback of clips/recordings, the audio is not in sync. The audio seems to play ~15 seconds or more later on.
I am using Wyzebridge, Wyze camera v3. Docker container on Ubuntu Host.

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: IP
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://IP:8554/CAMERA NAME
          roles:
            - detect
            - record
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
    rtmp:
      enabled: false
    detect:
      width: 1920
      height: 1080
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 14
        mode: all
motion:
  threshold: 50
  contour_area: 35
  mask: 
    - 881,0,785,347,584,458,0,495,0,0
    - 1920,1003,1920,1080,1376,1080,1378,999
    - 1920,0,1920,363,1811,522,1165,428,1157,0
    - 798,130,1209,133,1204,0,812,0
    - 1019,624,1480,719,1492,277,1043,264
    - 1419,622,1870,663,1920,277,1458,197
    - 719,216,915,226,983,69,736,29
```

### Relevant log output

```shell
no errors on this
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55da543bb140] method SETUP failed: 461 Unsupported Transport
[h264 @ 0x55da543bfcc0] Missing reference picture, default is 0
[h264 @ 0x55da543bfcc0] decode_slice_header error
Input #0, rtsp, from 'rtsp://IP:8554/CAM':
  Metadata:
    title           : Stream
  Duration: N/A, start: 0.115188, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 16000 Hz, mono, s16, 128 kb/s
```

### Frigate stats

```json
detection_fps	0
detectors	
cpu	
detection_start	0
inference_speed	107.83
pid	216
patio	
camera_fps	5.1
capture_pid	221
detection_fps	0
pid	220
process_fps	5.1
skipped_fps	0
service	
latest_version	"0.11.1"
storage	
/dev/shm	
free	63.4
mount_type	"tmpfs"
total	67.1
used	3.7
/media/frigate/clips	
free	287759.2
mount_type	"ext4"
total	491107.6
used	178326.2
/media/frigate/recordings	
free	287759.2
mount_type	"ext4"
total	491107.6
used	178326.2
/tmp/cache	
free	998.9
mount_type	"tmpfs"
total	1000
used	1.1
temperatures	{}
uptime	191052
version	"0.11.1-2eada21"
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Wyze V3
