### ISSUE TITLE
I can’t visualize clips in web ui nor in HA media brower

### ISSUE THREAD

**Issue by simulot** [blakeblackshear/frigate#562]
**Describe the bug**
I can't view recorded clips neither using build in web server nor with HO media browser. 

**Version of frigate**
frigate:0.8.0-rc2-amd64

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: 192.168.10.20
  topic_prefix: frigate
  user: broker 
  password: 28a4be0cfe 
  client_id: frigate

objects:
  track:
    - person
    - cat
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

cameras:
  wansview:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.10.104:554/live/ch0?token=redacted
          roles:
            - detect
            - rtmp
            - clips 
            - record            
    width: 1920
    height: 1080
    fps: 5
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true
   

  facade:
    ffmpeg:
      inputs: 
        - path: rtsp://redacted:redacted@192.168.10.52:554/Streaming/Channels/102?profile=Profile_1
          roles:
            - detect 
            - rtmp
        - path: rtsp://redacted:redacted@192.168.10.52:554/Streaming/Channels/101?profile=Profile_1
          roles:
            - clips 
            - record
    width: 640
    height: 480
    fps: 5
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true

  entree:
    ffmpeg:
      inputs:
        - path:  rtsp://redacted:redacted@192.168.10.53:554/Streaming/Channels/102?profile=Profile_1
          roles:
            - detect 
            - rtmp
        - path:  rtsp://redacted:redacted@192.168.10.53:554/Streaming/Channels/101?profile=Profile_1
          roles:
            - clips 
            - record
    width: 640
    height: 480
    fps: 5
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true

  jardin:
    ffmpeg:
      inputs: 
        - path: rtsp://redacted:redacted@192.168.10.51:554/Streaming/Channels/102?profile=Profile_1
          roles:
            - detect 
            - rtmp
        - path: rtsp://redacted:redacted@192.168.10.51:554/Streaming/Channels/101?profile=Profile_1
          roles:
            - clips 
            - record
    width: 640
    height: 480
    fps: 5
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true

  salon:
    ffmpeg:
      inputs: 
        - path: rtsp://redacted:redacted@192.168.10.50:554/Streaming/Channels/102?profile=Profile_1
          roles:
            - detect 
            - rtmp
        - path: rtsp://redacted:redacted@192.168.10.50:554/Streaming/Channels/101?profile=Profile_1
          roles:
            - clips 
            - record
    width: 640
    height: 480
      
    fps: 5
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true
```

**Logs**
```
frigate.events                 DEBUG   : Event received: end facade 1611152227.663525-m3wngx,
frigate.events                 DEBUG   : Event received: end facade 1611152227.101333-54apk7,
frigate.events                 DEBUG   : Event received: start facade 1611152231.10983-vp5h3i,
frigate.events                 DEBUG   : Event received: end facade 1611152227.422053-5lf3bz,
frigate.events                 DEBUG   : Event received: end facade 1611152231.10983-vp5h3i,
frigate.app                    INFO    : Stopping...,
frigate.object_processing      INFO    : Exiting object processor...,
frigate.watchdog               INFO    : Exiting watchdog...,
frigate.events                 INFO    : Exiting event cleanup...,
frigate.stats                  INFO    : Exiting watchdog...,
frigate.record                 INFO    : Exiting recording maintenance...,
frigate.events                 INFO    : Exiting event processor...,
root                           INFO    : Waiting for detection process to exit gracefully...,
frigate.video                  INFO    : entree: exiting subprocess,
 * Starting nginx nginx,
   ...done.,
frigate.app                    WARNING : Camera wansview has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera facade has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera entree has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera jardin has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera salon has record assigned to an input, but record is not enabled.,
Starting migrations,
peewee_migrate                 INFO    : Starting migrations,
There is nothing to migrate,
peewee_migrate                 INFO    : There is nothing to migrate,
frigate.mqtt                   INFO    : MQTT connected,
detector.coral                 INFO    : Starting detection process: 33,
frigate.app                    INFO    : Camera processor started for wansview: 36,
frigate.edgetpu                INFO    : Attempting to load TPU as usb,
frigate.app                    INFO    : Camera processor started for facade: 38,
frigate.edgetpu                INFO    : TPU found,
frigate.app                    INFO    : Camera processor started for entree: 39,
frigate.app                    INFO    : Camera processor started for jardin: 40,
frigate.app                    INFO    : Camera processor started for salon: 42,
frigate.app                    INFO    : Capture process started for wansview: 43,
frigate.app                    INFO    : Capture process started for facade: 45,
frigate.app                    INFO    : Capture process started for entree: 47,
frigate.app                    INFO    : Capture process started for jardin: 49,
frigate.app                    INFO    : Capture process started for salon: 55,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561c03d4e140] moov atom not found,
/tmp/cache/facade-20210120151732.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: facade-20210120151732.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55872b33e140] moov atom not found,
/tmp/cache/jardin-20210120151732.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: jardin-20210120151732.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x563d3a274140] moov atom not found,
/tmp/cache/wansview-20210120151734.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: wansview-20210120151734.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x563d65403140] moov atom not found,
/tmp/cache/entree-20210120151734.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: entree-20210120151734.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d1396aa140] moov atom not found,
/tmp/cache/salon-20210120151722.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: salon-20210120151722.mp4,
frigate.app                    INFO    : Stopping...,
frigate.object_processing      INFO    : Exiting object processor...,
frigate.events                 INFO    : Exiting event processor...,
frigate.events                 INFO    : Exiting event cleanup...,
frigate.watchdog               INFO    : Exiting watchdog...,
frigate.record                 INFO    : Exiting recording maintenance...,
 * Starting nginx nginx,
   ...done.,
frigate.app                    WARNING : Camera wansview has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera facade has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera entree has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera jardin has record assigned to an input, but record is not enabled.,
frigate.app                    WARNING : Camera salon has record assigned to an input, but record is not enabled.,
Starting migrations,
peewee_migrate                 INFO    : Starting migrations,
There is nothing to migrate,
peewee_migrate                 INFO    : There is nothing to migrate,
frigate.mqtt                   INFO    : MQTT connected,
frigate.app                    INFO    : Camera processor started for wansview: 36,
frigate.app                    INFO    : Camera processor started for facade: 37,
frigate.app                    INFO    : Camera processor started for entree: 39,
frigate.app                    INFO    : Camera processor started for jardin: 40,
frigate.app                    INFO    : Camera processor started for salon: 42,
frigate.app                    INFO    : Capture process started for wansview: 44,
frigate.app                    INFO    : Capture process started for facade: 45,
frigate.app                    INFO    : Capture process started for entree: 46,
frigate.app                    INFO    : Capture process started for jardin: 53,
frigate.app                    INFO    : Capture process started for salon: 54,
detector.coral                 INFO    : Starting detection process: 33,
frigate.edgetpu                INFO    : Attempting to load TPU as usb,
frigate.edgetpu                INFO    : TPU found,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55be08e52140] moov atom not found,
/tmp/cache/facade-20210120152100.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: facade-20210120152100.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f08ab32140] moov atom not found,
/tmp/cache/jardin-20210120152100.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: jardin-20210120152100.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a8f720b140] moov atom not found,
/tmp/cache/entree-20210120152103.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: entree-20210120152103.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55958a013140] moov atom not found,
/tmp/cache/salon-20210120152100.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: salon-20210120152100.mp4,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d718cbd140] moov atom not found,
/tmp/cache/wansview-20210120152101.mp4: Invalid data found when processing input,
frigate.events                 INFO    : bad file: wansview-20210120152101.mp4,
```

**Frigate debug stats**
``` json
{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.84,"pid":33}},"entree":{"camera_fps":5.0,"capture_pid":46,"detection_fps":0.0,"pid":39,"process_fps":5.0,"skipped_fps":0.0},"facade":{"camera_fps":5.0,"capture_pid":45,"detection_fps":0.0,"pid":37,"process_fps":5.0,"skipped_fps":0.0},"jardin":{"camera_fps":5.0,"capture_pid":53,"detection_fps":0.0,"pid":40,"process_fps":5.0,"skipped_fps":0.0},"salon":{"camera_fps":5.1,"capture_pid":54,"detection_fps":0.0,"pid":42,"process_fps":5.1,"skipped_fps":0.0},"service":{"uptime":71,"version":"0.8.0-fcc9cd5"},"wansview":{"camera_fps":5.0,"capture_pid":44,"detection_fps":0.0,"pid":36,"process_fps":5.0,"skipped_fps":0.0}}

```

**FFprobe from your camera**

Cam1
```


    Input #0, rtsp, from ‘rtsp://redacted:redacted@192.168.10.52:554/Streaming/Channels/102?profile=Profile_1’:
    Metadata:
    title : Media Presentation
    Duration: N/A, start: 0.556667, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 4:3 DAR 16:9], 12 fps, 12.50 tbr, 90k tbn, 24 tbc

Cam2:

    Input #0, rtsp, from ‘rtsp://192.168.10.104:554/live/ch0?token=redacted’:
    Metadata:
    title : hysxrtpsion
    Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp

```

**Screenshots**
![image](https://user-images.githubusercontent.com/5980377/105187885-9408da80-5b33-11eb-8ade-cba8df131a80.png)

**Computer Hardware**
 - OS: Ubuntu
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: [Wired

**Camera Info:**
 - Manufacturer: Wansview 
 - Model: HD Caméra Dôme Q5 
 - Resolution: 1080P  
 - FPS: ?

**Camera Info:**
 - Manufacturer: ANNKE 
 - Model: 4K HD PoE Caméra de Sécurité Ultra HD 8MP IP 
 - Resolution: 640x480 for detection  
 - FPS: ?

**Camera Info:**
 - Manufacturer: ANNKE 
 - Model: ANNKE PoE C500 5MP Full HD Caméra IP
 - Resolution: 640x480 for detection  
 - FPS: ?

**Additional context**
Clips taken from storage are visible with any media player.
