### ISSUE TITLE
[Config Support]: Recordings never moved from cache for one camera

### ISSUE THREAD

**Issue by dsanner** [blakeblackshear/frigate#5632]
### Describe the problem you are having

Amcrest IP4M-1041B camera's not recording. I have a few tapo's, reolink, and wyze with rtsp. Detection and record works fine on all those. I was using go2rtc with everything at first. The other cameras will record clips and record snapshots. The two amcrest cameras, however, will work fine with detect, and snapshot but I can't get them to record anything. 

There doesn't seem to be any errors in logs related to it. I tried using go2rtc, and then tried using just a single camera in frigate config, and both ways it doesn't store a recording for the event... just a snapshot picture. 

I am running the bleeding edge so might be that... or maybe something wrong with my config. 

I tried running 
ffmpeg -hide_banner -loglevel debug -i 'rtsp://admin:pass@10.0.0.44/cam/realmonitor?channel=1&subtype=0&authbasic=64
' -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an test.mp4

and ffmpeg is able to connect and record the mp4 with no issues. 

### Version

0.12.0-318240C

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.181
  port: 1883
  client_id: frigate
  user: frigate
  password: pass
  stats_interval: 60
logger:
  default: debug
  logs: 
    frigate.record: debug

ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 1
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-nvidia-h264
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 1 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic


detectors:
  coral:
    type: edgetpu
    device: usb  
snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  retain:
    default: 100
cameras:
  livingroomtokitchen:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@10.0.0.44/cam/realmonitor?channel=1&subtype=0&authbasic=64
          input_args: preset-rtsp-generic
          roles:
            - record
            - detect
    record:
      enabled: True
      retain:
        days: 14
        mode: all
detect:
  stationary:
    interval: 0
    threshold: 50
record:
  enabled: True
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 31
      mode: active_objects

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  mode: motion
  # Optional: Width of the output resolution (default: shown below)
  width: 1400
  height: 800
  quality: 15
```

### Relevant log output

```shell
2023-03-03 06:34:12.370609503  [2023-03-03 06:34:12] frigate.events                 DEBUG   : Event received: update livingroomtokitchen 1677825121.185688-da4ok6
2023-03-03 06:34:33.949130837  [2023-03-03 06:34:33] frigate.http                   ERROR   : No recordings found for the requested time range
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB
