### ISSUE TITLE
[HW Accel Support]: Old Laptop without coral accelerator improve perfomance and use AMD hwacc

### ISSUE THREAD

**Issue by chopin94** [blakeblackshear/frigate#5645]
### Describe the problem you are having

My HW info
![image](https://user-images.githubusercontent.com/62321622/222970806-39c6f724-74c3-4a6b-92c3-940c3d65bb5a.png)

Whit this config it works but gpu in system tab don't increase only 0%.
![image](https://user-images.githubusercontent.com/62321622/222971793-2393cf59-624b-4b6d-99d7-7ccd99cb48b9.png)

I know that without coral isn't efficent, but only two cam with this configuration at 5fps detection is my desire.
I have a nuc i3 10th where 5 cams work without coral and inference speed is below 100ms. Here is over 300. 
I want to use hw acceleration and then i could to buy a coral.

Thanks for the probably advise

### Version

0.12.0-0DBF909

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

mqtt:
  host: ................
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: .........
  stats_interval: 60


ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
#ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD129 -hwaccel_output_format yuv420p
  
birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects


    
record:
  enabled: True
  retain:
    days: 5
  events:
    retain:
      default: 15

detect:
  width: 768
  height: 432
  fps: 10
  stationary:
    interval: 0
    threshold: 50
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person
    - car
    - dog
    - cat

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 3
    objects:
      person: 15

restream:
  enabled: false



cameras:
  cancello_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:......@........:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:.....@192.168.1.135:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp

      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac


    objects:
      track:
        - person
        - car
        - dog
        - cat

    snapshots:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
    motion:
      #threshold: 25
      mask:
        - 89,90,403,49,594,62,768,53,768,0,0,0
        
    zones:
      cancello_zona:
        coordinates: 768,432,768,70,104,236,0,253,0,432
      spiazzale_zona:
        coordinates: 75,190,768,63,768,0,72,0
    rtmp:
       enabled: False



  fronte_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:.....@.......:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:.....@........:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp


      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac


    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
    motion:
      threshold: 25
      mask:
        - 0,323,0,374,0,432,31,432,36,260,104,61,313,61,768,278,768,0,266,0,200,0,99,0,0,0


    zones:
      garage_zona:
        coordinates: 0,297,145,292,175,249,171,189,146,167,40,150,0,191
      rotonda_zona:
        coordinates: 333,35,349,0,205,0,100,0,106,49
      elba_zona:
        coordinates: 264,140,492,432,768,432,768,156,501,125
      giampaolo_zona:
        coordinates: 426,112,337,49,109,55,109,110

    rtmp:
       enabled: False
```

### docker-compose file or Docker CLI command

```yaml
# Frigate
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.12.0-beta2-tensorrt
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
      - FRIGATE_RTSP_PASSWORD:...............
    devices:
      - /dev/bus/usb:/dev/bus/usb
      #- /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD128
      #- /dev/dri/renderD129
      # :/dev/dri/renderD129
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/frigate:/media
      - /home/docker/frigate/config.yml:/config/config.yml:ro
      - type: tmpfs 
      # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - '5000:5000'
      - '1935:1935' # RTMP feeds
```

### Relevant log output

```shell
Nothing
```

### FFprobe output from your camera

```shell
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 0, "width": 0 } ] } }, { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "0/0", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 0, "width": 0 } ] } } ]
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

Ezviz
