### ISSUE TITLE
[Feature Request] Ability to grab single image from input

### ISSUE THREAD

**Issue by jtronicus** [blakeblackshear/frigate#5647]
**Describe what you are trying to accomplish and why in non technical terms**
My cameras are all set up to do 24/7 recording on the main stream and detection on the sub stream.  This works well for object detection, but the latest.jpg and snapshot.jpg images are all based on the detect role and are not large enough for reliable face recognition (using Double Take).  I am looking for an efficient method of pulling still images from the main stream.

**Describe the solution you'd like**
It would be nice to have another input role (called "still_image" or something) that would allow me to call `GET /api/<camera_name>/still_image.jpg` and get a single JPEG image from the appropriate stream (in the below example it would return an image from the deck_main stream)
```
cameras:
  deck:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/deck_main
          roles:
            - record
            - still_image
    image:
      width: 1920
      height: 1080
      quality: 70
```

This would allow me to configure Double Take to use the higher resolution image for facial recognition, while still using the low resolution stream for object detection

**Describe alternatives you've considered**
- I was originally going to just configure Double Take to pull high-res snapshot images from the cameras themselves, but not all my cameras support this feature.
- Switching detection to the main stream allows Double Take to pull high resolution images, but results in much higher CPU usage for motion analysis
