### ISSUE TITLE
[Detector Support]: Input size optimisation 

### ISSUE THREAD

**Issue by jmtatsch** [blakeblackshear/frigate#5664]
### Describe the problem you are having

Detection performance in frigate "feels" not state of the art.
It produces really a lot of false positives in cluttered scenes so I am trying to get to the bottom of this.

I think frigate uses EfficientDet-Lite0 by default, correct?

Model architecture | Size(MB)* | Latency(ms)** | Average Precision***
-- | -- | -- | --
EfficientDet-Lite0 | 4.4 | 37 | 25.69%
EfficientDet-Lite1 | 5.8 | 49 | 30.55%
EfficientDet-Lite2 | 7.2 | 69 | 33.97%
EfficientDet-Lite3 | 11.4 | 116 | 37.70%
EfficientDet-Lite4 | 19.9 | 260 | 41.96%

Only EfficientDet-Lite0 and EfficientDet-Lite1 fit on a single tpu.
According to the default model config input size is 320x320

```
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320
```
According to

 ![](https://user-images.githubusercontent.com/25674295/79549715-4ce84780-80d2-11ea-8bd9-66f74a8b01f3.png) 

input size should be 512x512 for lite0 or 640x640 for lite1.

According to https://github.com/google/automl/issues/257#issuecomment-618242188 the input ideally should be as close as possible to the original dataset used for training i.e. the coco dataset which is ~ 640x640.

Is there a particular reason why the default input size is chosen as 320x320?

### Version

Beta 9

### Frigate config file

```yaml
does not apply
```

### docker-compose file or Docker CLI command

```yaml
does not apply
```

### Relevant log output

```shell
does not apply
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
