### ISSUE TITLE
[Support]: Object filters (area / ratio) not applied for all frames for the same object tracking

### ISSUE THREAD

**Issue by Mincka** [blakeblackshear/frigate#5674]
### Describe the problem you are having

From what I understand, the area and ratio object filters are checked when the object is detected AND above the threshold.
This means that if during the tracking the min/max area and ratio are exceeded, it does not matter.

I have cases where, for a single frame during object tracking, the area or the ratio filters are outside the limits in my configuration.

![image](https://user-images.githubusercontent.com/6184289/223658776-777827dd-9d67-4ed4-9a2f-01ad131ee9ef.png)
![image](https://user-images.githubusercontent.com/6184289/223655150-38958deb-60e9-414e-b529-056395b16fd8.png)

Despite the min_ratio / max_ratio, when the subject entered the field of view, for a single frame, the object detection was in the yellow zone. In this frame, the ratio is 0,16 so below the min_ratio.
When the detection threshold was above 0.7 a few frames after, the ratio was fine but the object was already tracked in the yellow zone.

Relevant config part:
```
filters:
  person:
    threshold: 0.7
    min_area: 1000
    max_area: 45000
    min_ratio: 0.3
    max_ratio: 1.4
```

Any idea how to prevent this? Maybe increase the min_score but the score could be honest with this very weird ratio for a person.

I have requested a minimum number of frames in a zone [here](https://github.com/blakeblackshear/frigate/discussions/5637) to consider it entered in a zone. This could also help for such cases.

### Version

0.11.1

### Frigate config file

```yaml
Frigate_Maison_Avant:
    ffmpeg:   
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp:/XXX 
          roles:
            - detect
            - record
    zones:
      orange:
        coordinates: 660,181,946,50,947,0,757,0,608,27,364,89,0,337,21,430
      yellow:
        coordinates: 777,207,1049,104,1280,208,1280,720,0,720,0,558,327,400
    detect: 
      fps: 10 
      max_disappeared: 50
    snapshots:
      enabled: True 
      bounding_box: True
      retain:
        default: 7       
    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 3 
    objects:
      track:
        - person
        - car     
      filters:
        person:
          threshold: 0.7
          min_area: 1000
          max_area: 45000
          min_ratio: 0.3
          max_ratio: 1.4
        car:
          mask:
            - 0,0,389,0,391,120,0,331
        person:
          mask:
            - 1219,605,1156,720,1096,720,792,371,816,309
    motion:
      improve_contrast: True
      mask:
        - 396,0,400,27,0,166,0,0
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

**Comment by NickM-27** [comment]
> This means that if during the tracking the min/max area and ratio are exceeded, it does not matter.

I don't think that's correct. The filters are applied throughout the object tracking not just before it becomes a true positive. 

An object also can't be part of a zone until it is considered a true positive. 

Your fps is 10 which means there are 5 frames in the debug view each second that are not shown and that may be causing confusion.

**Comment by Mincka** [comment]
Thank you for your answer.

What do you mean by  `Your fps is 10 which means there are 5 frames in the debug view that are not shown`?

I copied my configuration for this camera and I used the looping ffmpeg argument on the clip where the detection occurred to troubleshoot this event.

The person was again detected in the zone, every time, because the bottom center of the object box is in the yellow zone. 

You can see it in the screenshots as the zone is bold. At that moment, the only way to have a person detected in this zone, without being physically in it, is because of this narrow rectangle with the ratio below the minimum.

**Comment by NickM-27** [comment]
> Thank you for your answer.
> 
> What do you mean by  `Your fps is 10 which means there are 5 frames in the debug view that are not shown`?

The debug view is capped at 5 fps so since your detect is running at 10 fps there's 5 frames each second not rendered. 

> I copied my configuration for this camera and I used the looping ffmpeg argument on the clip where the detection occurred to troubleshoot this event.

Keep in mind these are not direct playbacks of what frigate saw originally, it is just an estimation. 

> The person was again detected in the zone, every time, because the bottom center of the object box is in the yellow zone.
> 
> You can see it in the screenshots as the zone is bold. At that moment, the only way to have a person detected in this zone, without being physically in it, is because of this narrow rectangle with the ratio below the minimum.

Right, an object won't be considered in a zone unless it is a true positive so its score has been above the threshold. 

I'd suggest using MQTT explorer to get a lotg of the events topic so we can see the objects exact metadata, that will provide the best way to fully understand what is going on.

**Comment by Mincka** [comment]
There's a sequence from start to end.

```
{
  "before": {
    "id": "1678289352.096728-s8s529",
    "camera": "Frigate_Maison_Avant_Debug",
    "frame_time": 1678289352.096728,
    "snapshot_time": 0,
    "label": "person",
    "sub_label": null,
    "top_score": 0,
    "false_positive": true,
    "start_time": 1678289352.096728,
    "end_time": null,
    "score": 0.51171875,
    "box": [
      1,
      198,
      54,
      571
    ],
    "area": 19769,
    "ratio": 0.14209115281501342,
    "region": [
      0,
      84,
      500,
      584
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 0,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": false,
    "has_snapshot": false
  },
  "after": {
    "id": "1678289352.096728-s8s529",
    "camera": "Frigate_Maison_Avant_Debug",
    "frame_time": 1678289358.610147,
    "snapshot_time": 1678289358.610147,
    "label": "person",
    "sub_label": null,
    "top_score": 0.70703125,
    "false_positive": false,
    "start_time": 1678289352.096728,
    "end_time": null,
    "score": 0.70703125,
    "box": [
      563,
      45,
      596,
      147
    ],
    "area": 3366,
    "ratio": 0.3235294117647059,
    "region": [
      394,
      0,
      714,
      320
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 1,
    "current_zones": [
      "orange"
    ],
    "entered_zones": [
      "yellow",
      "orange"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "type": "new"
}
```

```
{
  "before": {
    "id": "1678289352.096728-s8s529",
    "camera": "Frigate_Maison_Avant_Debug",
    "frame_time": 1678289358.610147,
    "snapshot_time": 1678289358.610147,
    "label": "person",
    "sub_label": null,
    "top_score": 0.70703125,
    "false_positive": false,
    "start_time": 1678289352.096728,
    "end_time": null,
    "score": 0.70703125,
    "box": [
      563,
      45,
      596,
      147
    ],
    "area": 3366,
    "ratio": 0.3235294117647059,
    "region": [
      394,
      0,
      714,
      320
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 1,
    "current_zones": [
      "orange"
    ],
    "entered_zones": [
      "yellow",
      "orange"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "after": {
    "id": "1678289352.096728-s8s529",
    "camera": "Frigate_Maison_Avant_Debug",
    "frame_time": 1678289360.082107,
    "snapshot_time": 1678289358.800159,
    "label": "person",
    "sub_label": null,
    "top_score": 0.724609375,
    "false_positive": false,
    "start_time": 1678289352.096728,
    "end_time": null,
    "score": 0.57421875,
    "box": [
      658,
      22,
      689,
      102
    ],
    "area": 2480,
    "ratio": 0.3875,
    "region": [
      480,
      0,
      800,
      320
    ],
    "stationary": false,
    "motionless_count": 1,
    "position_changes": 1,
    "current_zones": [
      "orange"
    ],
    "entered_zones": [
      "yellow",
      "orange"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "type": "update"
}
```

```
{
  "before": {
    "id": "1678289352.096728-s8s529",
    "camera": "Frigate_Maison_Avant_Debug",
    "frame_time": 1678289360.082107,
    "snapshot_time": 1678289358.800159,
    "label": "person",
    "sub_label": null,
    "top_score": 0.724609375,
    "false_positive": false,
    "start_time": 1678289352.096728,
    "end_time": null,
    "score": 0.57421875,
    "box": [
      658,
      22,
      689,
      102
    ],
    "area": 2480,
    "ratio": 0.3875,
    "region": [
      480,
      0,
      800,
      320
    ],
    "stationary": false,
    "motionless_count": 1,
    "position_changes": 1,
    "current_zones": [
      "orange"
    ],
    "entered_zones": [
      "yellow",
      "orange"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "after": {
    "id": "1678289352.096728-s8s529",
    "camera": "Frigate_Maison_Avant_Debug",
    "frame_time": 1678289360.082107,
    "snapshot_time": 1678289358.800159,
    "label": "person",
    "sub_label": null,
    "top_score": 0.724609375,
    "false_positive": false,
    "start_time": 1678289352.096728,
    "end_time": 1678289365.198646,
    "score": 0.57421875,
    "box": [
      658,
      22,
      689,
      102
    ],
    "area": 2480,
    "ratio": 0.3875,
    "region": [
      480,
      0,
      800,
      320
    ],
    "stationary": false,
    "motionless_count": 1,
    "position_changes": 1,
    "current_zones": [
      "orange"
    ],
    "entered_zones": [
      "yellow",
      "orange"
    ],
    "has_clip": true,
    "has_snapshot": true
  },
  "type": "end"
}
```

**Comment by Mincka** [comment]
It helps me to understand what's happening. Maybe my original description of the issue is incorrect or not precise enough.

For the `new` event, we can see that the threshold and the ratio are below the expected values, so it's flagged `false_positive`.
My problem is that both zones are added at that time and they will be kept are `entered_zone` for the whole event.

So when the `false_positive` flagged is removed, the event keeps with yellow zone as an entered one, and my alarm automation is triggered because the event is not a false_positive, it's a person that "has entered the yellow zone".

```
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate-event
    payload: 1/1/1/1
    value_template: >-
      {{ iif(value_json["type"] != "end", 1) }}/{{
      iif(value_json["before"]["label"] == "person", 1) }}/{{
      iif(["yellow", "green"]|select("in",
      value_json["before"]["entered_zones"])|list|length == 0, 1) }}/{{
      iif(["yellow", "green"]|select("in",
      value_json["after"]["entered_zones"])|list|length > 0, 1) }}
```

**Comment by Mincka** [comment]
Actually, there's something I don't get with my automation. If I don't check that the event is not categorized as a false positive, the automation will be wrongfully triggered anyway.

Do I miss something? You don't check for this neither in your [automation sample here](https://github.com/blakeblackshear/frigate/discussions/2898#discussion-3915893).

**Comment by blakeblackshear** [comment]
Frigate doesn't start sending events for an object until it is no longer a false_positive. You see in the first message that false_positive is `true` in the before and `false` in the after.

False_positive is not calculated based on a single frame, its the history of frames for the tracked object. Note that the `top_score` goes from 0 to >0.7 once its a true_positive. 

The ratio filter (and all other filters) is applied upstream of all of this and tells frigate to just drop any detections that don't meet the filter criteria as they are guaranteed to be a false_positive. They aren't even in the calculation.

**Comment by Mincka** [comment]
What do you think about the fact that `entered_zones` contains a value from a previous detection considered as false positive?

In the `before` of the first message, the object is not seen in any zone, in the `after` of this message, `yellow` is populated in `entered_zones` but not present in `current_zones`, so I understand that, in-between, for at least 1 frame, the object was seen in the `yellow` zone. When this happened, its ratio was invalid (> 0.3) because that's the only possibility to reach this zone.

I need to use `entered_zones` but it's wrongfully populated by a detection considered as false positive in one of the previous frames, when the tracking started for this object.

**Comment by Mincka** [comment]
Not sure about this, but it looks like the object is not added to the zone when discarded by zone filters, but not if the filters are set on camera>objects>filters>person ("object" filters?)
https://github.com/blakeblackshear/frigate/blob/master/frigate/object_processing.py#L142

If that's correct, I could put my filters in a zone definition and the object would not be added to the `entered_zones`.

**Comment by blakeblackshear** [comment]
> What do you think about the fact that `entered_zones` contains a value from a previous detection considered as false positive?

Remember that the false_positive value isn't specific to a frame. It is for the lifetime of a tracked object. It could take 5-10 seconds to confirm that a tracked object is a true_positive if the scores are low at first. However, once it decides the object is a true_positive, the entire timeline is considered a true_positive including the initial frames with low scores. 

Note that there was ~6 seconds between the frame times on the before and after messages, so the object could have stepped into the yellow zone during that time. There isn't an mqtt message sent for every frame.

> If that's correct, I could put my filters in a zone definition and the object would not be added to the

I'm not sure that would have worked as there was likely another frame where the object passed the filters.

**Comment by Mincka** [comment]
Good idea for the delay but I realized this delay is because of the ffmpeg loop. It's the time between the end of one event, whe the person is leaving the scene and comes back in.
When the person enters the frame the first time, it does not seems flagged as entered_zones for yellow. I need to check why it becomes included after.
Is it possible to have precise/exhaustive debug logs for all frames / each detection?

**Comment by blakeblackshear** [comment]
I have no idea what you mean by ffmpeg loop. 

> Is it possible to have precise/exhaustive debug logs for all frames / each detection?

Not without modifying the source code.

**Comment by Mincka** [comment]
> I have no idea what you mean by ffmpeg loop.

I'm using this to debug the clip:
```
  Frigate_Jardin_Avant_Debug:
    ffmpeg:
      inputs:
        - path: /media/frigate/clip_Frigate_Maison_Avant_1678235891.66674-1678235914.773344.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
```

Frigate believes it's a continuous event because of the looping clip. This may produce incoherent messages if there are taken between two loops.

**Comment by blakeblackshear** [comment]
I see. You would need to append 30s or so of a black frame to avoid that effect.

Even still, this is just an approximation of what happened originally.

Are you certain you had the filters applied to this debug camera? I don't see how it could have resulted in a detection. The filters are used to drop bounding boxes immediately after detection runs to make sure they are used during object tracking. Because they are applied so early in the process, I don't see how this could have happened.

**Comment by Mincka** [comment]
I don't manage to reproduce the issue with the black padding.
May I share the clip recorded by Frigate privately (3 MB)? The behavior with the detection in the yellow zone with the ratio outside of limits happens for every loop of the clip. I understand it may not reflect what happened initially, but I still don't get why the object is added to the yellow zone. We can clearly see on the clip that the only moment where it's detected in the zone is when the ratio filter should prevent it to be considered as valid.

I'm using Coral USB. You just have to paste this config:

```
  Frigate_Jardin_Avant_Debug:
    ffmpeg:
      inputs:
        - path: /media/frigate/clip_Frigate_Maison_Avant_1678235891.66674-1678235914.773344.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    zones:
      orange:
        coordinates: 660,181,946,50,947,0,757,0,608,27,364,89,0,337,21,430
      yellow:
        coordinates: 777,207,1049,104,1280,208,1280,720,0,720,0,558,327,400
    detect: 
      fps: 10 
      max_disappeared: 50
    snapshots:
      enabled: True 
      bounding_box: True
      retain:
        default: 7       
    record:
      enabled: True
      retain:
        days: 0
        mode: all
      events:
        retain:
          default: 3 
    objects:
      track:
        - person
        - car     
      filters:
        person:
          threshold: 0.7
          min_area: 1000
          max_area: 45000
          min_ratio: 0.3
          max_ratio: 1.4
        car:
          mask:
            - 0,0,389,0,391,120,0,331
        person:
          mask:
            - 1219,605,1156,720,1096,720,792,371,816,309
    motion:
      improve_contrast: True
      mask:
        - 396,0,400,27,0,166,0,0
```
