### ISSUE TITLE
[Support]: Cannot place points in the Mask & Zone Creator

### ISSUE THREAD

**Issue by krcm0209** [blakeblackshear/frigate#5679]
### Describe the problem you are having

I'm trying to setup motion masks, but every time I try to click on the camera frame still image in the tool, nothing happens. When I try doing the same thing with Chrome Developer Console open, I can see a 1:1 correlation with every time I try to click to create a point, and the following error:

![image](https://user-images.githubusercontent.com/17315774/223844345-12c2622c-4ac1-44fa-ab87-e0f1fb059589.png)

### Version

0.12.0-beta9

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.177
  user: frigate
  password: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  north_corner:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.0.0.50:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
        - path: rtsp://username:password@10.0.0.50:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
    rtmp:
      enabled: False
    detect:
      width: 704
      height: 480
      fps: 5
  south_corner:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.0.0.51:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
        - path: rtsp://username:password@10.0.0.51:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
    rtmp:
      enabled: False
    detect:
      width: 704
      height: 480
      fps: 5
  east_corner:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.0.0.52:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
        - path: rtsp://username:password@10.0.0.52:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
    rtmp:
      enabled: False
    detect:
      width: 704
      height: 480
      fps: 5
  west_corner:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.0.0.53:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
        - path: rtsp://username:password@10.0.0.53:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
    rtmp:
      enabled: False
    detect:
      width: 704
      height: 480
      fps: 5
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@10.0.0.54:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
        - path: rtsp://username:password@10.0.0.54:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
    rtmp:
      enabled: False
    detect:
      width: 720
      height: 576
      fps: 5
```

### Relevant log output

```shell
CameraMap-797676da.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')
    at Object.clickfalse (CameraMap-797676da.js:14:459)
    at HTMLDivElement.Gn (index-aed28f04.js:1:4930)
(anonymous) @ CameraMap-797676da.js:14
Gn @ index-aed28f04.js:1
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Amcrest mixed

### Any other information that may be helpful

Chrome browser version: `Version 110.0.5481.178 (Official Build) (64-bit)`
