### ISSUE TITLE
How to record Audio in clips and recordings?

### ISSUE THREAD

**Issue by cben0ist** [blakeblackshear/frigate#568]
**Describe the bug**
I want to record audin in my clips and rexordings

**Version of frigate**
RC2

**Config file**
ffmpeg section of my config
```
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p
  global_args: '-hide_banner -loglevel fatal'
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: '-f rawvideo -pix_fmt yuv420p'
    record: >-
      -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an -c:a aac 
    clips: >-
      -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
      -strftime 1 -c copy -an -c:a aac 
    rtmp: '-c copy -f flv'
```

**FFprobe from your camera**

Camera 1: (Reolink rlc-410-5mp):
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Metadata:
  width                 640.00
  height                480.00
  displayWidth          640.00
  displayHeight         480.00
  duration              0.00
  videocodecid          7.00
  audiocodecid          10.00
  audiosamplerate       16000.00
  framerate             6.00
Input #0, flv, from 'rtmp://10.1.60.14/bcs/channel0_sub.bcs?channel=0&stream=0&user=128fosc&password=C4m3r4%21128':
  Metadata:
    displayWidth    : 640
    displayHeight   : 480
  Duration: 00:00:00.00, start: 318700.136000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 16000 Hz, mono, fltp
    Stream #0:1: Video: h264 (Baseline), yuv420p(progressive), 640x480, 6 fps, 12 tbr, 1k tbn
```
Camera 2 (foscam c2):
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with Apple clang version 11.0.3 (clang-1103.0.32.62)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65548
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65550
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65552
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65554
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65556
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65558
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65560
[h264 @ 0x7fdd07014a00] Missing reference picture, default is 65562
Input #0, rtsp, from 'rtsp://128fosc:C4m3r4%21128@10.1.50.31:88/videoSub':
  Metadata:
    title           : IP Camera Video
    comment         : videoSub
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 10.42 tbr, 90k tbn, 3520886.88 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
```
**Computer Hardware**
 - OS: Debisn
 - Virtualization: Proxmox 6.3-3
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink rlc-410-5mp and Foscam C2
 - Resolution: 640:380 and 640:360
 - FPS: 5

**Additional context**
I have tried adding  -c:a aac to the ffmpeg output clips and recordings without success.
