### ISSUE TITLE
Anything I can do to improve detection?

### ISSUE THREAD

**Issue by szupi-ipuzs** [blakeblackshear/frigate#5681]
### Describe the problem you are having

![obraz](https://user-images.githubusercontent.com/25821342/223852820-9916c103-1dcb-42da-80d6-f294eb46fcdc.png)
I have setup TensorRT as detector and it works fine with cars and people, but seem to have problems with my dogs (see the screenshot). Is there anything I can tinker with in config (or camera settings) to make frigate more successful with detecing my dogs as dogs? :)
I also tested with Coral before and I kinda have a feeling it had the same problems, but during those tests the stream quality was pretty bad, so can't say for sure.

### Version

0.12.0-e8d8cc4

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.111
detectors:
    tensorrt:
      type: tensorrt
      device: 0
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
motion:
  contour_area: 15
cameras:
  gatewatcher:
    motion:
      improve_contrast: True
    rtmp:
      enabled: false
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bird
        - bicycle
        - motorcycle
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gatewatcher?video=all&audio=all
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/gatewatcher_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: []
    detect:
      width: 2048
      height: 1536
      fps: 6
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
        objects:
          - person
          - car
          - dog
    snapshots:
      enabled: true
    live:
      height: 1536
  salon:
    motion:
      improve_contrast: True
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - dog
        - cat
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/salon?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/salon_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: []
    detect:
      width: 2560
      height: 1440
      fps: 6
    snapshots:
      enabled: true
    live:
      height: 1440
  # birdfeeder:
  #   motion:
  #     improve_contrast: True
  #   rtmp:
  #     enabled: False
  #   objects:
  #     track:
  #       - person
  #       - dog
  #       - cat
  #       - bird
  #   ffmpeg:
  #     hwaccel_args: preset-nvidia-h264
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/birdfeeder?video=copy&audio=aac
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
  #   detect:
  #     width: 640
  #     height: 360
  #     fps: 5
  #   record:
  #     enabled: true
  #     events:
  #       pre_capture: 2
  #       post_capture: 2
  #       retain:
  #         default: 7
  #       objects:
  #         - person
  #         - dog
  #         - cat
  #         - bird
  #   snapshots:
  #     enabled: true
birdseye:
  enabled: False
go2rtc:
  streams:
    gatewatcher:
      - http://192.168.2.216/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
      - "ffmpeg:gatewatcher#audio=opus"
    gatewatcher_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.216:554/h264Preview_01_sub
      - "ffmpeg:gatewatcher_sub#audio=opus"
    salon:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.230:554/h264Preview_01_main
      - "ffmpeg:salon#audio=opus"
    salon_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.230:554/h264Preview_01_sub
      - "ffmpeg:salon_sub#audio=opus"
    # birdfeeder:
    #   - echo:/config/get_ha_stream.sh camera.smart_bird_feeder_camera
    #   - "ffmpeg:birdfeeder#audio=aac"
  webrtc:
    candidates:
      - 192.168.2.5:8555
      - stun:8555
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

Starting docker with the following command:

docker run -d --name frigate \
        --privileged \
        --restart=unless-stopped \
        --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
        --device /dev/bus/usb:/dev/bus/usb \
        --device /dev/dri/renderD128 \
        --shm-size=200m \
        -v /home/user/frigate/storage:/media/frigate \
        -v /home/user/frigate/config:/config \
        -v /home/user/frigate/trt-models:/trt-models \
        -v /etc/localtime:/etc/localtime:ro \
        -p 5000:5000 -p 1984:1984 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp \
        -e FRIGATE_RTSP_USER=redacted \
        -e FRIGATE_RTSP_PASSWORD=redacted \
        -e YOLO_MODELS=yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416 \
        --gpus=all \
