### ISSUE TITLE
[Camera Support]: disruptive recording playback

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#5685]
### Describe the problem you are having

Version 0.11.0 running on a QNAP NAS as a docker, mixture of 6 Wyze Cam V2 and V3 on official Wyze rtsp firmware, recording to a Western Digital 6T purple drive.  Integrated with Home Assistant.  Reproducible after restarting Frigate.  Not sure if this is the same issue as issue #4531.

When viewing playbacks, Frigate would spin several seconds to load.  It will play about 40 seconds of recordings and start spinning for 20 seconds.  The recording will resume, skipping the 20 seconds.  E.g., if recording starts at 02:40:00, it will play till 02:40:40, then spin 20 seconds.  Playback resumes and plays the recording with a timestamp of 02:41:00.  I.e., it skips 20 seconds of recordings for every minute (the spinning time can vary, I observed 9-12 seconds in my different tries after restarting Frigate).  Also, it is practically impossible to seek the recordings to a certain timestamp, because the spinning wheel just keeps spinning, seems, forever.  Checked the network tab from browser developer tools, did not see any connection attempts.  I do not see the same issue when I play the same recording from inside of Home Assistant.  It appears more severe on Wyze Cam V2 than on V3.

### Version

0.11.0

### Frigate config file

```yaml
mqtt:
  host: 192.xxx.xxx.xxx

birdseye:
  enabled: True
  mode: continuous

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    # Optional: output args for detect streams (default: shown below)
    # detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.xxx.xxx.xx/live
          roles:
            - detect
            - record
            - rtmp
    rtmp:
      enabled: False
    detect:
      enabled: False
    record:
      enabled: True
      retain:
        days: 30
        mode: all
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://username:password@192.xxx.xxx.xxx/live':
  Metadata:
    title           : Session streamed by "wyze"
    comment         : live
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 13.17 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Wyze Cam V2, V3 on rtsp firmware
