### ISSUE TITLE
[FR] Include Ngrok in container

### ISSUE THREAD

**Issue by luisiam** [blakeblackshear/frigate#5688]
### Describe the problem you are having

I tried to setup Ngrok tunneling but go2rtc is throwing ngrok not found error. I tried with standalone go2rtc docker and it works fine.

### Version

0.12.0-E8D8CC4

### Frigate config file

```yaml
go2rtc:
  ngrok:
    command: ngrok tcp 8555 --authtoken xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Relevant log output

```shell
10:53:00.669 ERR [ngrok] start error="exec: \"ngrok\": executable file not found in $PATH"
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A
