### ISSUE TITLE
[Config Support]: Not have AAC record (sound) on specific camera

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5698]
### Describe the problem you are having

Hey
What I'm doing wrong ? when I try watch at mse I cant hearing nothing 

### Version

0.12 beta9

### Frigate config file

```yaml
go2rtc:
  streams:
    Hall:
      - rtsp://admin:123@192.168.1.106:8554/Streaming/Channels/101
      - ffmpeg:Hall#audio=opus
    Hall_sub: 
      - rtsp://admin:123@192.168.1.106:8554/Streaming/Channels/102

cameras:
  Hall:
    ffmpeg:
       hwaccel_args: preset-vaapi
       inputs:
           - path:  rtsp://127.0.0.1:8554/Hall_sub?video=copy
             input_args: preset-rtsp-generic
             roles:
               - detect
           - path: rtsp://127.0.0.1:8554/Hall?video=copy&audio=aac
             input_args: preset-rtsp-generic
             roles:
               - record
```

### Relevant log output

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: Unknown

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: Unknown
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
