### ISSUE TITLE
[Support]: Masks are not loaded quickly enough during restart - Events are triggered

### ISSUE THREAD

**Issue by bortek** [blakeblackshear/frigate#5700]
### Describe the problem you are having

My Frigate is integrated to HASS and using https://github.com/blakeblackshear/frigate-hass-integration and I have setup notifications with the help of this simple Automation. It sends a notification to my Telegram whenever an event is triggered attaching an image.

```
alias: Frigate Notification
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: "{{ value_json.type }}"
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: notify.telegram_notify
    data:
      message: MSG
      title: Tittle
      data:
        photo:
          - url: >-
              http://192.168.2.194:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
            caption: >-
              A {{trigger.payload_json["after"]["label"]}} was detected by
              {{trigger.payload_json["after"]["camera"]}} camera.
mode: single
```

Due to my Reolink cameras often hang I need to restart Frigate container every 30 minutes.  The problem is that during the startup of the container what I experience is that the masks are NOT loaded quickly enough before the object is detected. Or rather masks are not loaded before the events "engine" starts and kicks in.

Therefore if there is an object detected during the Frigate startup the result will be the following: 
- Frigate starts (masks are not loaded yet)
- Object enters camera area
- Object is detected
- Event is triggered which triggers notification
- Masks are loaded

This is my theory but I pretty sure it is the case because the evens are triggered exactly at every 30 minutes time intervals like 2:30, 3:00, 5:30 etc.

Any idea what can be done about this?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.194
  user: frigate
  password: 

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  jo-frontside-1:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000
      inputs:
        # Ethernet
        #- path: rtmp://192.168.2.27/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=XXX
        - path: rtmp://192.168.2.176/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=XXX
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
      fps: 25
    motion:
      mask:
        - 1083,349,1214,388,1647,428,2010,441,2295,465,2560,616,2560,0,1000,0

  jo-driveway-1:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rw_timeout 5000000
      inputs:
        # Ethernet
        # - path: rtmp://192.168.2.70/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=XXX
        - path: rtmp://192.168.2.150/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=XXX
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 25
    motion:
      mask:
        - 1557,351,1261,359,1112,377,973,455,857,531,706,575,424,653,0,859,0,380,0,0,1577,0

rtmp: # Restream RTMP to e.g. HASS, not now.
  enabled: true

record:
  enabled: true
  retain:
    days: 20
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 20
  expire_interval: 60

objects:
  track:
    - person
    - car
    - bicycle
    - bus
      #- refrigerator # värmepump
    - dog
    - bear
    - bird
    - cat
    - skis
    - snowboard

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: False
  retain:
    default: 30

timestamp_style:
  position: "tl"
  format: "%Y-%m-%d %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

birdseye:
  enabled: True
  width: 1920
  height: 1130
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

database:
  path: /media/frigate/frigate.db

logger:
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
    frigate.record: debug
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A
