### ISSUE TITLE
[HW Accel Support]: Question about hwaccel predets

### ISSUE THREAD

**Issue by phabibjr** [blakeblackshear/frigate#5702]
### Describe the problem you are having

Running Version 0.12.0-beta-9 in a Proxmox VM Ubuntu 22.04 with a Tesla P4 passed through.

Everything works great. Hardware h.264 decoding is working on all cameras and I have 4 TensorRT detectors running. However, when I click on the "VAINFO" button under "System" I get the following error message:

{"return_code":3,"stderr":"error:XDG_RUNTIME_DIRisinvalidornotsetintheenvironment.nerror:can'tconnecttoXserver!nlibvainfo:VA-APIversion1.17.0nlibvainfo:Tryingtoopen/usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.sonlibvainfo:va_openDriver()returns-1nvaInitializefailedwitherrorcode-1(unknownlibvaerror),exit","stdout":""}

### Version

0.12.0-E8D8CC4

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.34
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

detectors:
  cuda0:
    type: tensorrt
  cuda1:
    type: tensorrt
  cuda2:
    type: tensorrt
  cuda3:
    type: tensorrt

database:
  path: /db/frigate.db

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 2
  mode: objects

motion:
  frame_height: 200
  improve_contrast: False

ffmpeg:
  output_args: 
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-nvidia-h264

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 30

snapshots:
  enabled: True
  bounding_box: True
  clean_copy: False
  retain:
    default: 30
    objects:
      person: 365

objects:
  track:
    - person
    - dog
    - cat

rtmp:
  enabled: False

cameras:
  Pool:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.0.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://user:password@192.168.0.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      width: 846
      height: 480
    motion:
      mask:
        - 21,24,245,24,245,0,21,0
```

### docker-compose file or Docker CLI command

```yaml
# compose
version: '3.9'
services:
  frigate:
    container_name: frigate-beta
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta9-tensorrt
    runtime: nvidia
    shm_size: 512mb

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml
      - /media/share/NVR/Frigate/recordings:/media/frigate/recordings
      - /media/paul/snapshots/Frigate/clips:/media/frigate/clips
      - ./db:/db
      - ./trt-models:/trt-models
      - type: tmpfs
        target: /tmp/cache

    ports:
      - "5000:5000"
      - "8554:8554"   # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
#      - FRIGATE_RTSP_PASSWORD: password

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Amcrest, Dahua
