### ISSUE TITLE
[Support]: Recordings missing from Database

### ISSUE THREAD

**Issue by w1ll1am23** [blakeblackshear/frigate#5708]
### Describe the problem you are having

First reported here https://www.reddit.com/r/homeassistant/comments/11po6lf/frigate_recordings_stuck_on_loading/

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.X.X
  port: 1883
  user: frigate
  password: password

  detectors:
    coral:
      type: edgetpu
      device: usb

  ffmpeg:
    global_args: -hide_banner -loglevel warning
    hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
    input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
    output_args:
      detect: -f rawvideo -pix_fmt yuv420p
      record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
      rtmp: -c copy -f flv

  snapshots:
    enabled: True

  cameras:
    room:
      record:
        enabled: True
        retain:
          days: 1
          mode: motion
      detect:
        width: 2688
        height: 1520
      ffmpeg:
        input_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - nobuffer+genpts+discardcorrupt
          - -flags
          - low_delay
          - -strict
          - experimental
          - -analyzeduration
          - 1000M
          - -probesize
          - 1000M
        inputs:
          - path: rtsp://frigate:frigate@192.168.X.X:554/cam/realmonitor?channel=1&subtype=0
            roles:
              - detect
              - record
          - path: rtsp://frigate:frigate@192.168.X.X:554/cam/realmonitor?channel=1&subtype=1
            roles:
              - rtmp
```

### Relevant log output

```shell
Uncaught (in promise) TypeError: can't access property "day", w is undefined
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://frigate:frigate@192.168.X.X:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2688x1520, 20 fps, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Frigate stats

```json
{
  "backpatio": {
    "camera_fps": 5.0,
    "capture_pid": 255,
    "detection_fps": 0.0,
    "pid": 245,
    "process_fps": 5.0,
    "skipped_fps": 0.0
  },
  "backyard": {
    "camera_fps": 5.1,
    "capture_pid": 252,
    "detection_fps": 0.1,
    "pid": 233,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "room": {
    "camera_fps": 5.1,
    "capture_pid": 246,
    "detection_fps": 0.0,
    "pid": 229,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "detection_fps": 0.1,
  "detectors": {
    "coral": {
      "detection_start": 0.0,
      "inference_speed": 9.35,
      "pid": 222
    }
  },
  "frontdoor": {
    "camera_fps": 5.1,
    "capture_pid": 248,
    "detection_fps": 0.0,
    "pid": 232,
    "process_fps": 5.1,
    "skipped_fps": 0.0
  },
  "service": {
    "latest_version": "0.11.1",
    "storage": {
      "/dev/shm": {
        "free": 125.1,
        "mount_type": "tmpfs",
        "total": 134.2,
        "used": 9.1
      },
      "/media/frigate/clips": {
        "free": 1147326.3,
        "mount_type": "ext4",
        "total": 1967864.1,
        "used": 720501.2
      },
      "/media/frigate/recordings": {
        "free": 1147326.3,
        "mount_type": "ext4",
        "total": 1967864.1,
        "used": 720501.2
      },
      "/tmp/cache": {
        "free": 959.6,
        "mount_type": "tmpfs",
        "total": 1000.0,
        "used": 40.4
      }
    },
    "temperatures": {},
    "uptime": 1292,
    "version": "0.11.1-2eada21"
  }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful

Deleted everything on my local system under the Frigate media directory including the DB, deleted the docker container and still having the same issue.
