### ISSUE TITLE
[Support]: Frigate stuck in 'in progress' state

### ISSUE THREAD

**Issue by cemilbrowne** [blakeblackshear/frigate#5716]
### Describe the problem you are having

Frigate was stuck in 'in progress' on a match for 8 minutes.  Kept sending same snapshot over mqtt to double take.

<img width="1445" alt="Screenshot 2023-03-14 at 4 15 58 pm" src="https://user-images.githubusercontent.com/834596/224902121-2a46cf2c-bb1b-438b-b5c3-f78cae6c48ec.png">

### Version

System 0.12.0-e8d8cc4

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: xxxxx
  port: 1883
  user: xxxx
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: xxxx

cameras:
  doorbell: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://xxxxxx # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1600 # <---- update for your camera's resolution
      height: 1200 # <---- update for your camera's resolution
    snapshots: # <----- Enable snapshots
      enabled: True
    motion:
      mask:    
        - 1600,0,1600,585,0,447,0,0
  # ayla_cam: # <------ Name the camera
  #   ffmpeg:
  #     hwaccel_args: preset-vaapi
  #     inputs:
  #       - path: rtsp://192.168.8.1:7447/6N1gWVw9SXHqv4Zf # <----- The stream you want to use for detection
  #         roles:
  #           - detect
  #   detect:
  #     enabled: True # <---- disable detection until you have a working camera feed
  #     width: 1920 # <---- update for your camera's resolution
  #     height: 1080 # <---- update for your camera's resolution
  #   snapshots: # <----- Enable snapshots
  #     enabled: True

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  height: 500
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 1
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Audio:

Codec: AAC (Advanced Audio Coding)

Audio:

Codec: Opus (Opus Interactive Audio Codec)

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1600x1200
FPS: 30/1
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Unifi Doorbell

### Any other information that may be helpful

Running latest beta with Intel CPU acceleration.
