### ISSUE TITLE
Database Files won't delete[Config Support]: 

### ISSUE THREAD

**Issue by alexispattein** [blakeblackshear/frigate#5728]
### Describe the problem you are having

hi,

I needed to re compose my docker-compose file and since then it is impossible for frigate to restart.
It cannot because it is impossible for it to overwrite the previous DB files and more accurately frigate.db-wal and frigate.db-shm
I tried to remove it with admin access but it seems to be impossible to remove it.
The short term solution is to create a new db folder and change path in the config file but everytime I ll reboot my docker host it will happen. Any idea how to remove those ?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.X.X
  port: 1883
  user: MQTT
  password: {FRIGATE_MQTT_PASSWORD}
  topic_prefix: frigate
database:
  path: /db/frigate.db
cameras:
  room1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.X.X:X/X
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    networks:
      dockernet:
        ipv4_address: 192.168.X.X
      proxy:
        ipv4_address: 192.168.X.X
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "~/docker/frigate/config.yml:/config/config.yml:ro"
      - "~/docker/frigate/media:/media/frigate"
      - "~/docker/frigate/database:/db"
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)
