### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by lucabress** [blakeblackshear/frigate#5732]
### Describe the problem you are having

The application starts, but when I enter the page it does not load, I see the upper bar with the word frigate and the waiting circle that rotates, if I exit the page the application is stopped

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: (mymqtt host)
  username: (mypassword)
  password: (mypassword)

  cameras:
    Garage:
      ffmpeg:
        inputs:
          - path: rtsp://camerauser:camerapassword@192.168.1.110:554/streaming/channels/102
            roles:
              - detect
    width: 1280
    height: 720
    fps: 5
  detectors:
    cpu1:
      type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

### FFprobe output from your camera

```shell
rtsp://camerauser:camerapassword@192.168.1.110:554/streaming/channels/102
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision DS-2CD2342WD-I
