### ISSUE TITLE
[Config Support]: Eufy camera's and how to minimise logging, aac and corrupt segments

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#5758]
### Describe the problem you are having

I would like to know how to :

1. Limit go2rtc logging. If have some eufy cameras only come on temparily, i have put in frigate logging on the camera to set to critical like so:

```
logger:
  default: info
  logs:
    ffmpeg.kitchen_backdoor.detect: critical
    watchdog.kitchen_backdoor: critical
    detector.kitchen_backdoor: critical
``` 

but go2rtc is still spamming the logs quite frequently that it can't reach the camera. Any way to limit those logs as well ?

2. If i specific the preset preset-record-generic-audio-aac
```
cameras:
  backyard:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264 
      output_args:
        record: preset-record-generic-audio-aac
```

Do i still need to specific this in the go2rtc configuration as well like this?
```
    kitchen_back_door:
      - rtsp://192.168.50.48/live2
      #- "ffmpeg:kitchen_backdoor#audio=aac"
```
3. How does preset-record-generic-audio-copy different from the aac preset? I used the generic one with eufy and that seems to work fine too.
4. I am getting these occasionally:
```
WARNING : Discarding a corrupt recording segment: /tmp/cache/kitchen_backdoor-20230317082956.mp
```
Is there any way to resolve this ? I saw someone seemingly able to resolve this by setting events retain to all ?
5. I also get ```Unable to create jpg because frame is not in cache``` occasionally as a log message (suspect from the eufy's as well, but i suppose it could be something else.

Apology for the many questions, but they all related to the same topic, e.g. Eufy camera's.

### Version

0.12.0-e8d8cc4

### Frigate config file

```yaml
mqtt:

  host: 192.168.50.148
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: **
  stats_interval: 300

record:
  expire_interval: 10


timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

logger:
  default: info
  logs:
    ffmpeg.kitchen_back_door.detect: critical
    watchdog.kitchen_back_door: critical
    detector.kitchen_back_door: critical

    ffmpeg.backyard.detect: critical
    watchdog.backyard: critical
    detector.backyard: critical
#
#    ffmpeg.backyard_camera.detect: critical
#    watchdog.backyard_camera: critical
#    detector.backyard_camera: critical
#
    frigate.video: critical

go2rtc:
  streams:
    license_plate:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=5&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:license_plate#audio=opus"
    greenhouse_2:
      - rtsp://192.168.50.170:554/user=admin&password=**&channel=3&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:greenhouse_2#audio=opus"
    front_driveway_1:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=6&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:front_driveway_1#audio=opus"
    front_driveway_2:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=8&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:front_driveway_2#audio=opus"
    front_porch:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=7&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:front_porch#audio=opus"
    back_porch:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=1&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:back_porch#audio=opus"
    diningroom:
      - rtsp://Admin1:**@192.168.50.227/live0
    # - ffmpeg:diningroom
    #  - "ffmpeg:diningroom#audio=opus"
    kitchen:
      - rtsp://192.168.50.70/live0
    # - ffmpeg:kitchen
    #  - "ffmpeg:kitchen#audio=opus"
    garage:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=2&stream=0.sdp?real_stream--rtp-caching=100
    #  - "ffmpeg:garage#audio=opus"
    greenhouse:
      - rtsp://192.168.50.15:554/user=admin&password=**&channel=3&stream=0.sdp?real_stream--rtp-caching=100
    #  -  "ffmpeg:greenhouse#audio=opus"
    kitchen_back_door:
      - rtsp://192.168.50.48/live2
      #- "ffmpeg:kitchen_back_door#audio=aac"
    backyard:
      - rtsp://192.168.50.48/live1
      #- "ffmpeg:backyard#audio=aac"


cameras:
  backyard:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264 
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          min_area: 500
          min_score: 0.6
          threshold: 0.7
  #    mask:
  #      - 0,480,198,480,200,449,0,451
  #      - 640,0,640,36,640,111,608,135,485,96,504,0
  #      - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
  #      - 370,0,356,100,291,79,292,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
#      required_zones:
#        - front_porch_close_in
      retain:
        default: 5
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    #zones:
    #  front_porch_close_in:
    #    coordinates: 45,480,362,480,640,480,640,213,554,145,525,328,466,343,408,272,348,70,253,64,181,118,67,178
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
#        required_zones:
#         - front_porch_close_in
        pre_capture: 5
        post_capture: 15

  kitchen_back_door:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264 
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_back_door
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_area: 500
          min_score: 0.6
          threshold: 0.7
  #    mask:
  #      - 0,480,198,480,200,449,0,451
  #      - 640,0,640,36,640,111,608,135,485,96,504,0
  #      - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
  #      - 370,0,356,100,291,79,292,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
#      required_zones:
#        - front_porch_close_in
      retain:
        default: 5
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    #zones:
    #  front_porch_close_in:
    #    coordinates: 45,480,362,480,640,480,640,213,554,145,525,328,466,343,408,272,348,70,253,64,181,118,67,178
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
#        required_zones:
#         - front_porch_close_in
        pre_capture: 5
        post_capture: 15

  license_plate:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/license_plate
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15

  greenhouse_2:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/greenhouse_2
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - mouse
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
 #   zones:
 #     front_driveway_1_close_in:
 #       coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
 #       objects:
 #         - car
 #         - person
 #         - dog
 #         - cat
 #         - bicycle
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15

  front_driveway_1:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway_1
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
          min_score: 0.6
          threshold: 0.7
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_1_close_in
#        - front_driveway_1_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      front_driveway_1_person_at_night:
        coordinates: 739,1080,1920,1080,1920,384,1085,434
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
      front_driveway_1_driveway_only:
        coordinates: 814,1080,1920,1080,1920,536,1799,411,1091,444
        objects:
          - car
 #     front_driveway_1_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_1_close_in
#          - front_driveway_1_whole_area
        pre_capture: 5
        post_capture: 15
        
  front_driveway_2:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_driveway_2
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
          min_score: 0.6
          threshold: 0.7
          mask:
            - 694,805,1047,787,1096,1048,706,1056
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      required_zones:
#        - front_driveway_2_close_in
#        - front_driveway_2_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      front_driveway_2_person_at_night:
        coordinates: 1920,1080,1920,316,1273,395,115,509,0,600,0,1080
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
      front_driveway_2_driveway_only:
        coordinates: 0,1080,715,1080,712,453,128,504,0,596
        objects:
          - car
 #     front_driveway_2_whole_area:
 #       coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
 #       objects:
 #         - person
 #         - cat
 #         - dog
 #         - bicycle
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
#        required_zones:
#          - front_driveway_2_close_in
#          - front_driveway_2_whole_area
        pre_capture: 5
        post_capture: 15
        
  front_porch:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        person:
          min_area: 500
          min_score: 0.6
          threshold: 0.7
  #    mask:
  #      - 0,480,198,480,200,449,0,451
  #      - 640,0,640,36,640,111,608,135,485,96,504,0
  #      - 439,200,441,324,512,320,532,261,554,188,540,129,451,134
  #      - 370,0,356,100,291,79,292,0
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: True
      height: 500
#      required_zones:
#        - front_porch_close_in
      retain:
        default: 5
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    #zones:
    #  front_porch_close_in:
    #    coordinates: 45,480,362,480,640,480,640,213,554,145,525,328,466,343,408,272,348,70,253,64,181,118,67,178
    record:
      enabled: True
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
#        required_zones:
#         - front_porch_close_in
        pre_capture: 5
        post_capture: 15
        
  back_porch:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_porch
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
        person:
          min_area: 500
          min_score: 0.7
          threshold: 0.8
 #      person:
 #         mask:
 #           - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  diningroom:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/diningroom
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1382,58,1872,55,1868,8,1382,7
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  kitchen:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1382,58,1872,55,1868,8,1382,7
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  garage:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 6
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - mouse
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
#       person:
#          mask:
#            - 79,385,107,480,287,480,259,313,107,268
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 4
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: motion
        pre_capture: 5
        post_capture: 15
        
  greenhouse:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/greenhouse
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    motion:
      mask:
        - 1211,102,1682,101,1679,62,1211,64
        
detectors:
  coral:
    type: edgetpu
    device: usb

rtmp:
  enabled: false

birdseye:
  restream: True
  enabled: True
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

live:
  height: 640
  quality: 1
```

### Relevant log output

```shell
2023-03-17 11:46:01.865831065  11:46:01.865 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="wrong response on DESCRIBE" url=rtsp://192.168.50.48/live2
2023-03-17 11:46:02.019107688  11:46:02.018 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="wrong response on DESCRIBE" url=rtsp://192.168.50.48/live1
2023-03-17 11:46:02.019164435  11:46:02.019 WRN [rtsp] error="source 0 error: wrong response on DESCRIBE" stream=backyard
2023-03-17 11:46:02.074458287  11:46:02.074 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="wrong response on DESCRIBE" url=rtsp://192.168.50.48/live2
2023-03-17 11:46:02.075110015  11:46:02.074 WRN [rtsp] error="source 0 error: wrong response on DESCRIBE" stream=kitchen_back_door
```

### Frigate stats

```json
{"back_porch":{"camera_fps":6.1,"capture_pid":358,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":419,"pid":309,"process_fps":6.1,"skipped_fps":0.0},"backyard":{"camera_fps":0.0,"capture_pid":317,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":972,"pid":298,"process_fps":0.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.7"},"1":{"cpu":"0.0","mem":"0.0"},"1002":{"cpu":"0.0","mem":"0.0"},"1008":{"cpu":"0.3","mem":"0.0"},"1012":{"cpu":"1.0","mem":"0.3"},"109":{"cpu":"8.3","mem":"2.5"},"111":{"cpu":"0.0","mem":"0.0"},"117":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"1.0"},"289":{"cpu":"1.0","mem":"0.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.3","mem":"1.7"},"292":{"cpu":"30.6","mem":"1.8"},"298":{"cpu":"0.0","mem":"1.4"},"299":{"cpu":"0.0","mem":"0.2"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"1.4"},"301":{"cpu":"0.7","mem":"1.5"},"302":{"cpu":"0.0","mem":"0.2"},"303":{"cpu":"1.0","mem":"1.5"},"304":{"cpu":"0.0","mem":"0.2"},"305":{"cpu":"0.3","mem":"1.6"},"306":{"cpu":"0.7","mem":"1.5"},"307":{"cpu":"0.0","mem":"0.2"},"308":{"cpu":"1.0","mem":"1.5"},"309":{"cpu":"0.7","mem":"1.5"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"0.0","mem":"0.2"},"311":{"cpu":"0.3","mem":"1.5"},"312":{"cpu":"0.7","mem":"1.5"},"313":{"cpu":"0.0","mem":"0.2"},"314":{"cpu":"1.0","mem":"1.5"},"315":{"cpu":"0.0","mem":"0.2"},"316":{"cpu":"0.3","mem":"1.5"},"317":{"cpu":"0.0","mem":"1.4"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"0.0","mem":"1.4"},"323":{"cpu":"3.0","mem":"1.5"},"328":{"cpu":"4.0","mem":"1.4"},"332":{"cpu":"0.0","mem":"0.2"},"333":{"cpu":"7.3","mem":"0.9"},"334":{"cpu":"4.0","mem":"1.4"},"339":{"cpu":"5.3","mem":"0.8"},"340":{"cpu":"4.0","mem":"1.4"},"342":{"cpu":"0.0","mem":"0.2"},"343":{"cpu":"3.3","mem":"1.4"},"358":{"cpu":"4.3","mem":"1.4"},"359":{"cpu":"7.6","mem":"0.9"},"364":{"cpu":"0.0","mem":"0.2"},"366":{"cpu":"7.6","mem":"0.9"},"372":{"cpu":"7.0","mem":"0.8"},"374":{"cpu":"0.0","mem":"0.2"},"377":{"cpu":"3.3","mem":"1.5"},"399":{"cpu":"5.0","mem":"1.4"},"41":{"cpu":"0.0","mem":"0.0"},"415":{"cpu":"4.7","mem":"1.4"},"416":{"cpu":"7.0","mem":"0.8"},"417":{"cpu":"0.0","mem":"0.2"},"419":{"cpu":"8.0","mem":"0.9"},"42":{"cpu":"0.0","mem":"0.0"},"426":{"cpu":"3.0","mem":"1.4"},"431":{"cpu":"7.6","mem":"0.8"},"434":{"cpu":"13.6","mem":"0.9"},"439":{"cpu":"8.3","mem":"0.8"},"445":{"cpu":"7.0","mem":"0.9"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"11.3","mem":"0.2"},"971":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"5587.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.5,"pid":290}},"diningroom":{"camera_fps":6.1,"capture_pid":377,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":416,"pid":311,"process_fps":6.1,"skipped_fps":0.0},"front_driveway_1":{"camera_fps":5.2,"capture_pid":334,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":366,"pid":305,"process_fps":5.2,"skipped_fps":0.0},"front_driveway_2":{"camera_fps":5.0,"capture_pid":340,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":359,"pid":306,"process_fps":5.0,"skipped_fps":0.0},"front_porch":{"camera_fps":5.1,"capture_pid":343,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":372,"pid":308,"process_fps":5.1,"skipped_fps":0.0},"garage":{"camera_fps":6.1,"capture_pid":415,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":431,"pid":314,"process_fps":6.1,"skipped_fps":0.0},"gpu_usages":{"intel-qsv":{"gpu":"11.02 %","mem":"- %"}},"greenhouse":{"camera_fps":5.1,"capture_pid":426,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":445,"pid":316,"process_fps":5.1,"skipped_fps":0.0},"greenhouse_2":{"camera_fps":5.1,"capture_pid":328,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":333,"pid":303,"process_fps":5.1,"skipped_fps":0.0},"kitchen":{"camera_fps":6.0,"capture_pid":399,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":439,"pid":312,"process_fps":6.0,"skipped_fps":0.0},"kitchen_back_door":{"camera_fps":0.0,"capture_pid":320,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":974,"pid":300,"process_fps":0.0,"skipped_fps":0.0},"license_plate":{"camera_fps":5.0,"capture_pid":323,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":339,"pid":301,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1679053607,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":799.7,"mount_type":"tmpfs","total":838.9,"used":39.1},"/media/frigate/clips":{"free":160056.9,"mount_type":"ext4","total":248215.2,"used":76935.2},"/media/frigate/recordings":{"free":160056.9,"mount_type":"ext4","total":248215.2,"used":76935.2},"/tmp/cache":{"free":975.7,"mount_type":"tmpfs","total":1000.0,"used":24.3}},"temperatures":{},"uptime":76,"version":"0.12.0-e8d8cc4"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

n/a
