### ISSUE TITLE
0.8.0-rc3 snapshots not working

### ISSUE THREAD

**Issue by bezpodstawny** [blakeblackshear/frigate#576]
**Describe the bug**
Snapshots cannot be created, despite the configuration settings, they are not created in the CLIP folder. The last working version is RC1.
I also can't get MQTT to switch snapschoots to ON. In Mqttexplorer I can see that it is OFF all the time.

**Version of frigate**
0.8.0-rc3

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 192.168.32.61
  topic_prefix: frigate
  user: frigate # Optional
  password: @@@@@@ # Optional
detectors:
  coral:
    type: edgetpu
    device: usb
clips:
  max_seconds: 30
  retain:
    default: 5
    objects:
      person: 5
      car: 5
snapshots:
  retain:
    default: 10
  objects:
    person: 10
    car: 10
ffmpeg:
  global_args: -hide_banner -loglevel fatal
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args: 
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:a aac -c:v copy -an
    rtmp: -c copy -f flv
objects:
  track:
    - person
    - car
  # filters:
    # car:
      # min_score: 0.60
      # threshold: 0.60
      # min_area:  1000
    # person:
      # min_score: 0.60
      # threshold: 0.60
      # min_area:  1000
cameras:
  asfalt:
    ffmpeg:
      inputs: 
        - path: rtsp://admin:mypassword@192.168.32.23/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp
          roles:
          - detect
          - clips
        #  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
    fps: 5
    height: 1440
    width: 2560
    best_image_timeout: 15
    clips:
        enabled: True
        pre_capture: 2
        objects:
          - person 
          - car
        retain:
          default: 7
          objects:
            person: 7
            car: 7
    record:
      enabled: False
      retain_days: 1
    rtmp:
      enabled: False
    snapshots:
        enabled: True
        timestamp: True
        bounding_box: True
        crop: False
        height: 1440
        retain:
          default: 10
          objects:
            person: 15
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      height: 1440
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 1000
         # max_area: 100000
          min_score: 0.5
          threshold: 0.65
        car:
          min_area: 1000
         # max_area: 100000
          min_score: 0.5
          threshold: 0.65
```

**Frigate debug config**
```
...snapshots":{"bounding_box":true,"crop":false,"enabled":false,"height":1440,"retain":{"default":10,"obje......
```

**Screenshots**
[https://ibb.co/M5bd63M]https://ibb.co/M5bd63M

**Comment by tubalainen** [comment]
Good that you edited and removed your passwords 😸 

Can be a simple indentation issue in your camera: section of the config file.

Try this:

```
cameras:
  asfalt:
    ffmpeg:
      inputs: 
        - path: rtsp://admin:mypassword@192.168.32.23/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp
          roles:
            - detect
            - clips

```
If that is not the issue, start with the bare minimum settings in your config.yml and test from there.

**Comment by InToSSH** [comment]
Yes, I think you have indentation error in your config:
```yaml
snapshots:
  retain:
    default: 10
  objects:
    person: 10
    car: 10
```

Should be:
```yaml
snapshots:
  retain:
    default: 10
    objects:
      person: 10
      car: 10
```
