### ISSUE TITLE
[Config Support]: Restream all cameras - am i missing something obvious?

### ISSUE THREAD

**Issue by madasus** [blakeblackshear/frigate#5768]
### Describe the problem you are having

Trying to go here rtsp://<frigate_host>:8554/<camera_name> to access the rtsp streams for my cameras but it won't work.  The only camera I can find there is the birdseye feed.

Is there something I need to add globally in the config to tell Frigate to restream all cameras? or do I have to re-add all the cameras again under the go2rtc: section of the config?

Thank you

### Version

Beta9

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: xxx
  user: mqtt
  password: xxx

ffmpeg:
#  hwaccel_args: -c:v h264_qsv
#  hwaccel_args: preset-intel-qsv-h264
  hwaccel_args: preset-vaapi

logger:
  # Optional: default log level (default: shown below)
  default: warning
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error

detectors:
  coral:
    type: edgetpu
    device: usb

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: solid


birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  restream: true

objects:
  track:
    - person
    - dog
    - cat
    - car
    - bear

record:
  enabled: True
  events:
    retain:
      default: 10
    pre_capture: 5
    post_capture: 15


cameras:

  attic1: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      inputs:
        - path: rtsp://xxx:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - detect
            - record

    record:
      enabled: True
      retain:
        days: 14
        mode: motion
    
    objects:
      track:
        - person
        - cat
        - bird

    motion:
      threshold: 15
```

### Relevant log output

```shell
2023-03-18 10:21:02.758476393  [2023-03-18 10:21:02] frigate.record                 ERROR   : list index out of range
2023-03-18 10:21:03.704931513  10:21:03.704 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-03-18 10:21:03.705784689  10:21:03.705 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB
