### ISSUE TITLE
[Config Support]: No audio on recordings since X beta version

### ISSUE THREAD

**Issue by evolucja** [blakeblackshear/frigate#5776]
### Describe the problem you are having

Audio works fine when watching live via webrtc. However there is no audio on recordings anymore. It worked completely fine till one of the previous beta versions which I had till ~12th of March but can't tell now the exact version I had.

### Version

0.12.0-E454DAF

### Frigate config file

Tried it also with:
"preset-record-generic-audio-aac" and "preset-record-generic-audio-copy"

```yaml
ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    
go2rtc:
  rtsp:
    username: "xxxx"
    password: "xxxxx"  
  streams:
    bedroom: rtsp://xxxxx:xxxxxxx!@10.0.0.150:554/stream1
  webrtc:
    candidates:
      - 10.0.0.108:8555
      - stun:8555

cameras:
  bedroom: 
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom
          roles:
            - detect
            - rtmp
            - record
        
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
ffprobe

Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 15/1
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

PCIe
