### ISSUE TITLE
[Support]: Recordings in webview or hassio frigate card are not available only for iphone devices

### ISSUE THREAD

**Issue by FizykPSX** [blakeblackshear/frigate#5778]
### Describe the problem you are having

Hi Everyone,

The strangest problem is that everything works like a charm, that is before you want to open a recording in a webview, hassio frigate card or hassio media browser on iPhone. On android deevices - no issue, on a PC - no issue, on a mac - no issue.
Only iphone is the problem and I tried everything. Changing browser did not help too.
Problem is that I don't own this device and logs from the browser are unobtainable.
But maybe there is a magic trick or a preset to make viewing recordings possible?

### Version

0.12.0-318240C

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: 192.168.8.20
  user: mqtt
  password: mqtt
objects:
  track:
    - person
    - dog
    - car
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 1
  hwaccel_args: preset-nvidia-h264
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 4 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: preset-rtmp-generic

go2rtc:
  streams:
    dzwonek:
      - rtsp://admin:pass@192.168.8.130:554/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0
   
    dzwonek_detect:
      - rtsp://admin:pass@192.168.8.130:554/cam/realmonitor?channel=1&subtype=1&authbasic=64#backchannel=0
      
    kamera110:
      - rtsp://admin:pass@192.168.8.110/cam/realmonitor?channel=1&subtype=0
    
    kamera110_detect:
      - rtsp://admin:pass@192.168.8.110/cam/realmonitor?channel=1&subtype=1
    
    kamera111:
      - rtsp://admin:pass@192.168.8.111/cam/realmonitor?channel=1&subtype=0
    
    kamera111_detect:
      - rtsp://admin:pass@192.168.8.111/cam/realmonitor?channel=1&subtype=1
    
    kamera112:
      - rtsp://admin:pass@192.168.8.112/cam/realmonitor?channel=1&subtype=0
    
    kamera112_detect:
      - rtsp://admin:pass@192.168.8.112/cam/realmonitor?channel=1&subtype=1
    
    kamera113:
      - rtsp://admin:pass@192.168.8.113/cam/realmonitor?channel=1&subtype=0
    
    kamera113_detect:
      - rtsp://admin:pass@192.168.8.113/cam/realmonitor?channel=1&subtype=1

cameras:
  kamera113:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamera113
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kamera113_detect
          roles:
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 15
    motion:
      mask:
        - 242,21,243,50,24,50,25,24
        - 1280,151,879,117,314,142,0,228,0,0,1132,0,1280,0
  kamera112:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamera112
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kamera112_detect
          roles:
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 15
    motion:
      mask:
        - 242,21,243,50,24,50,25,24
        - 1242,0,1248,116,952,89,756,100,562,110,262,208,0,333,0,0
  kamera111:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamera111
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kamera111_detect
          roles:
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 15
    motion:
      mask:
        - 242,21,243,50,24,50,25,24
        - 1012,720,1280,720,1280,0,373,0,379,0
  kamera110:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kamera110
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/kamera110_detect
          roles:
            - detect
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 15
    motion:
      mask:
        - 242,21,243,50,24,50,25,24
        - 1280,0,0,0,127,39,1017,452,1280,557,1280,499

  dzwonek:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dzwonek
          roles:
            - rtmp
            - record
        - path: rtsp://127.0.0.1:8554/dzwonek_detect
          roles:
            - detect
    detect:
      enabled: True
      width: 720
      height: 576
      fps: 10
record:
  enabled: True
  events:
    retain:
      default: 90
snapshots:
  enabled: True

live:
  height: 720
  quality: 8
birdseye:
  enabled: True
  mode: objects
```

### Relevant log output

```shell
nothing relevant in the log, recordings work well
```

### FFprobe output from your camera

```shell
all cameras are working great
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

BCS (dahua protocols) x4, Amcrest Ad410
