### ISSUE TITLE
Clip generation fails after some time  - 0.8 beta

### ISSUE THREAD

**Issue by walthowd** [blakeblackshear/frigate#578]
**Describe the bug**
Clips stop being generated after a random period of time. Log file continuously prints `No cache clips for driveway. Waiting...`

**Version of frigate**
0.8.0-RC3

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
cameras: 
  backporch: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.109/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - detect
        - path: "rtmp://192.168.1.109/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  backyard: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.42/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - detect
        - path: "rtmp://192.168.1.42/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  backyard-nw: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.247/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - detect
        - path: "rtmp://192.168.1.247/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
  driveway: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.24/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - detect
        - path: "rtmp://192.168.1.24/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      track: 
        - person
        - car
        - truck
    motion:
      mask:
#        - 3,469,638,465,637,204,314,87,0,87
        - 0,0,640,0,637,204,312,101,0,87
  garage: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.128/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - detect
        - path: "rtmp://192.168.1.128/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      track: 
        - person
        - car
        - truck
  sideyard: 
    ffmpeg: 
      inputs:
        - path: "rtmp://192.168.1.21/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - detect
        - path: "rtmp://192.168.1.21/bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=camera-password"
          roles:
            - clips
            - record
    fps: 4 
    height: 480
    width: 640
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      track: 
        - person
        - car
        - truck
  doorbell: 
    ffmpeg: 
      inputs:
        - path: "rtsp://admin:HFMMFC@192.168.1.48:554/h264/ch01/sub/av_stream"
          roles:
            - detect
        - path: "rtsp://admin:HFMMFC@192.168.1.48:554/h264/ch01/main/av_stream"
          roles:
            - clips
#            - rtmp
            - record
    fps: 10
    height: 512
    width: 384
    clips:
      enabled: true
    record:
      enabled: true 
      retain_days: 30
    objects: 
      track: 
        - person
        - car
        - truck
    motion:
      mask:
        - 0,295,0,0,384,0,384,332,157,313
   - 2,284,0,500,381,501,380,312,163,303

database:
  path: /config/frigate.db

detectors: 
  coral: 
    device: usb
    type: edgetpu

ffmpeg: 
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
  hwaccel_args: 
    - "-hwaccel"
    - vaapi
    - "-hwaccel_device"
    - /dev/dri/renderD128
    - "-hwaccel_output_format"
    - yuv420p

mqtt: 
  host: "192.168.1.1"
  password: mqtt-password
  topic_prefix: frigate
  user: homeassistant

objects: 
  track: 
    - person

clips: 
  max_seconds: 300
  retain:
    default: 30

logger:
  default: debug 
#  default: info 
  logs:
    frigate.mqtt: error
```

**Logs**
```
watchdog.driveway              INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate.events                 DEBUG   : Event received: start sideyard 1611252836.953116-xfgfu5
frigate.events                 DEBUG   : Event received: end sideyard 1611252836.953116-xfgfu5
frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate.events                 DEBUG   : Event received: start sideyard 1611252879.485718-vrfn7f
frigate.events                 DEBUG   : Event received: start sideyard 1611252879.485718-8m10x8
frigate.events                 DEBUG   : Event received: end sideyard 1611252879.485718-vrfn7f
frigate.events                 DEBUG   : Event received: end sideyard 1611252879.485718-8m10x8
frigate.events                 DEBUG   : Event received: start driveway 1611252884.238361-nf8237
frigate.events                 DEBUG   : Event received: start driveway 1611252884.23954-42m1ml
frigate.events                 DEBUG   : Event received: start driveway 1611252884.23954-sjp0xl
frigate.events                 DEBUG   : Event received: start driveway 1611252884.261754-jfd1zg
frigate.events                 DEBUG   : Event received: start driveway 1611252884.261754-6ekptj
frigate.events                 DEBUG   : Event received: start driveway 1611252884.498063-txufeh
frigate.events                 DEBUG   : Event received: end driveway 1611252884.261754-jfd1zg
frigate.events                 DEBUG   : Event received: end driveway 1611252884.498063-txufeh
frigate.events                 DEBUG   : Event received: end driveway 1611252884.261754-6ekptj
frigate.events                 DEBUG   : Event received: start driveway 1611252887.021895-oo1fbc
frigate.events                 DEBUG   : Event received: start driveway 1611252887.021895-rip4bv
frigate.events                 DEBUG   : Event received: start driveway 1611252887.021895-nmg7i8
frigate.events                 DEBUG   : Event received: end driveway 1611252884.23954-42m1ml
frigate.events                 DEBUG   : Event received: end driveway 1611252887.021895-rip4bv
frigate.events                 DEBUG   : Event received: end driveway 1611252887.021895-nmg7i8
frigate.events                 DEBUG   : Event received: end driveway 1611252887.021895-oo1fbc
frigate.events                 DEBUG   : Event received: start driveway 1611252890.251964-udchdm
frigate.events                 DEBUG   : Event received: start driveway 1611252890.251964-1c688s
frigate.events                 DEBUG   : Event received: end driveway 1611252890.251964-1c688s
frigate.events                 DEBUG   : Event received: end driveway 1611252890.251964-udchdm
frigate.events                 DEBUG   : Event received: start driveway 1611252892.988122-ufh7on
frigate.events                 DEBUG   : Event received: start driveway 1611252892.988122-c3b2gv
frigate.events                 DEBUG   : Event received: end driveway 1611252892.988122-ufh7on
frigate.events                 DEBUG   : Event received: end driveway 1611252892.988122-c3b2gv
frigate.events                 DEBUG   : Event received: start driveway 1611252895.744236-wxrq4b
frigate.events                 DEBUG   : Event received: end driveway 1611252895.744236-wxrq4b
frigate.events                 DEBUG   : Event received: end driveway 1611252884.238361-nf8237
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
frigate.events                 DEBUG   : No cache clips for driveway. Waiting...
```

**Frigate debug stats**
![Screenshot from 2021-01-21 13-06-53](https://user-images.githubusercontent.com/864569/105399702-99286100-5be9-11eb-88dc-9525b80f90f4.png)

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, flv, from 'rtmp://192.168.1.24/bcs/channel0_sub.bcs?channel=0&stream=0&user=view&password=viewDub11':
  Metadata:
    displayWidth    : 640
    displayHeight   : 480
  Duration: 00:00:00.00, start: 3432.049000, bitrate: N/A
    Stream #0:0: Data: none
    Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
    Stream #0:2: Video: h264, yuv420p(progressive), 640x480, 4 tbr, 1k tbn
Unsupported codec with id 0 for input stream 0
```

**Computer Hardware**
 - OS: Ubuntu 18.03
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC-410MP
 - Resolution: 480p
 - FPS: 4

When the bug happens, it seems to bug clip creation for all defined cameras. I recreated the issue today on RC3 and I scanned the files from the garage camera. They all validated except for one:

```
whowd@howdnuc:/opt/frigate/garage/extract$ ls -1 | xargs -I {} ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 {}
9.555000
9.677000
9.726000
9.707000
9.711000
9.688000
9.702000
9.705000
9.779000
9.554000
9.493000
9.548000
9.556000
9.720000
9.685000
9.757000
9.727000
9.727000
9.522000
9.196000
9.513000
9.551000
9.468000
9.495000
9.487000
9.499000
9.580000
9.761000
9.707000
9.756000
9.744000
9.678000
9.668000
9.694000
9.668000
9.708000
9.659000
9.610000
9.544000
9.684000
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558ba93704c0] moov atom not found
garage-20210121123827.mp4: Invalid data found when processing input
whowd@howdnuc:/opt/frigate/garage/extract$ ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 garage-20210121123827.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55e03cd114c0] moov atom not found
garage-20210121123827.mp4: Invalid data found when processing input
```

Seems that the while loop here is getting stuck:
https://github.com/blakeblackshear/frigate/blob/7b4e510b95601a15514c9684f592d18126dcdab0/frigate/events.py#L104

I'll try to add some more debugging to see what exactly is happening.
