### ISSUE TITLE
[Support]: go2rtc dashboard not loading

### ISSUE THREAD

**Issue by Haloooch** [blakeblackshear/frigate#5781]
### Describe the problem you are having

When clicking on the go2rtc dashboard link from System tab I get a 404 not found error.
Page being loaded is: https://192.168.1.176:8123/live/webrtc/

go2rtc logs are not reporting any issue, equally no error in Frigate logs.

### Version

0.12.0-e454daf

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.176:5000/api/config/schema

mqtt:
  host: 192.168.1.176
  port: 1883
  user: xxx
  password: xxx
  topic_prefix: frigate
  client_id: frigate

#detectors:
#  coral:
#    type: edgetpu
#    device: usb

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

go2rtc:
  streams:
    deck_detect: 
      - rtspx://192.168.1.1:7441/U372bol8XpE63yi2
    deck_record: 
      - rtsp://192.168.1.1:7447/2nhGCeE2TOMQmdSl

birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 4
  mode: objects

snapshots:
  enabled: True
  bounding_box: true
  retain:
    default: 1

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 1

objects:
  track:
    - person
    - cat
    - dog
    - bird
    - car
  filters:
    person:
      min_score: 0.75
    cat:
      min_score: 0.75
    bird:
      min_score: 0.75

cameras:

##############################################################################################
# Deck Camera
##############################################################################################
  deck:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_detect
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/deck_record
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-ubiquiti
        rtmp: preset-rtmp-ubiquiti 
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask: 
        - 925,0,831,71,681,106,432,275,0,375,0,0
    rtmp:
      enabled: false   
    mqtt:
      timestamp: False
      bounding_box: False
      crop: False
      height: 500
    objects:
      track:
        - person
        - cat
        - dog
        - bird
```

### Relevant log output

```shell
2023-03-21 00:04:48.611867735  [INFO] Preparing go2rtc config...
2023-03-21 00:04:48.647600076  [INFO] Got IP address from supervisor: 192.168.1.176
2023-03-21 00:04:48.677512269  [INFO] Got WebRTC port from supervisor: 8556
2023-03-21 00:04:48.922767366  [INFO] Starting go2rtc...
2023-03-21 00:04:48.988369399  11:04:48.988 INF go2rtc version 1.2.0 linux/amd64
2023-03-21 00:04:48.988684351  11:04:48.988 INF [api] listen addr=:1984
2023-03-21 00:04:48.988998501  11:04:48.988 INF [rtsp] listen addr=:8554
2023-03-21 00:04:48.989626422  11:04:48.989 INF [srtp] listen addr=:8443
2023-03-21 00:04:48.989912487  11:04:48.989 INF [webrtc] listen addr=:8555
2023-03-21 00:04:58.612852339  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"24/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":720,"width":1280},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"48/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","display_aspect_ratio":"16:9","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Unifi

### Any other information that may be helpful

Might be related, when going to the camera feed page I'm only given the option to view jsmpeg. 
Shouldn't be relevant, I'm not using any hardware acceleration or a Coral on this box, it's just my test instance of HA.

Funny feeling, I might have a port conflict issue. I was running a standalone instance of go2rtc which worked fine, however I can no longer start the addon, even when I have fully stopped Frigate

```
12:40:05.548 INF go2rtc version 1.2.0 linux/amd64
12:40:05.550 FTL [api] listen error="listen tcp :1984: bind: address already in use"
```
