### ISSUE TITLE
[Config Support]: WebRTC working in HA but not available to other devices on LAN

### ISSUE THREAD

**Issue by lawrence-jeff** [blakeblackshear/frigate#5782]
### Describe the problem you are having

I have the latest beta and have successfully gotten the MSE and WebRTC stuff working in the Frigate UI. I can't seem to access the restream using anything else, its probably a misunderstanding of the IP or port to use with all the docker stuff

I see mentions of ports 8555, 5000, 1984, and I think I have tried every combination with Chrome and VLC (same network - not trying anything external) 

HA Supervised install with the Frigate beta install

Things I have tried

http://192.168.0.136:5000/live/webrtc
http://192.168.0.136:8555/live/webrtc
rtsp://192.168.0.136:8554/driveway
Countless other iterations

Nothing seems to work, inside HA I get the MSE and WebRTC dropdown and both options work fine

### Version

0.12.0-E454DAF

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
mqtt:
  host: core-mosquitto.local.hass.io
  user: frigatenew
  password: frigatenew
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: '-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt'
go2rtc:
  streams:
    driveway:
      - rtmp://192.168.0.130/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=password
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: >-
            rtmp://192.168.0.130/bcs/channel0_sub.bcs?channel=0&stream=0&user=admin&password=password
          roles:
            - detect 
        - path: >-
             rtmp://192.168.0.130/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=password
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    detect:
      width: 640
      height: 480
      fps: 7
      max_disappeared: 70
      stationary:
        interval: 100
    record:
      enabled: true
      events:
        retain:
          default: 10
          mode: active_objects
        required_zones:
        - carentry
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain: 
        default: 10
    zones:
      carentry:
        coordinates: '181,179,411,187,460,228,370,275'
      garageexit:
        coordinates: '0,225,147,200,354,291,405,258,524,302,462,480,74,480'
    motion:
      mask: '2,170,634,216,632,0,5,3,3,74'  

objects:
  track:
    - person
    - car
```

### Relevant log output

```shell
2023-03-21 02:16:00.624681034  [INFO] Preparing go2rtc config...
2023-03-21 02:16:00.677681476  [INFO] Got IP address from supervisor: 192.168.0.136
2023-03-21 02:16:00.724867944  [INFO] Got WebRTC port from supervisor: 8555
2023-03-21 02:16:01.051602932  [INFO] Starting go2rtc...
2023-03-21 02:16:01.152842908  21:16:01.152 INF go2rtc version 1.2.0 linux/amd64
2023-03-21 02:16:01.153569857  21:16:01.153 INF [api] listen addr=:1984
2023-03-21 02:16:01.153647146  21:16:01.153 INF [rtsp] listen addr=:8554
2023-03-21 02:16:01.154061232  21:16:01.154 INF [srtp] listen addr=:8443
2023-03-21 02:16:01.154465689  21:16:01.154 INF [webrtc] listen addr=:8555
2023-03-21 02:16:10.639043651  [INFO] Starting go2rtc healthcheck service...
```

### Frigate stats

```json
That URL on my ip doesn't work either
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

Probably a silly user error, just can't figure it out and I have read the beta docs a few times and just not finding a URL that will work anywhere
