### ISSUE TITLE
Blue Iris RTSP streams broken with HW acceleration

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#579]
**Describe the bug**
RTSP streams are broken with HW acceleration enabled (<10th gen). I have an Intel(R) Core(TM) i5-8600K. RTSP streams work fine without HW acceleration.

**Version of frigate**
0.8.0 RC3

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
logger:
  default: debug

detectors:
  cpu1:
    type: cpu

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
    - 
mqtt:
  host: xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate

objects:
  track:
    - person
    - cat
    - dog

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://url
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    clips:
      enabled: True

```

**Logs**
```
frigate           |  * Starting nginx nginx
frigate           |    ...done.
frigate           | Starting migrations
frigate           | peewee_migrate                 INFO    : Starting migrations
frigate           | peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate           | peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate           | There is nothing to migrate
frigate           | peewee_migrate                 INFO    : There is nothing to migrate
frigate           | frigate.mqtt                   INFO    : MQTT connected
frigate           | frigate.mqtt                   DEBUG   : on_clips_toggle: frigate/entrance/clips/state ON
frigate           | frigate.mqtt                   DEBUG   : on_snapshots_toggle: frigate/entrance/snapshots/state ON
frigate           | frigate.mqtt                   DEBUG   : on_detect_toggle: frigate/entrance/detect/state ON
frigate           | frigate.app                    INFO    : Camera processor started for entrance: 38
frigate           | detector.cpu1                  INFO    : Starting detection process: 36
frigate           | frigate.app                    INFO    : Capture process started for entrance: 39
frigate           | frigate.video                  INFO    : entrance: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate           | frigate.video                  INFO    : entrance: ffmpeg process is not running. exiting capture thread...
frigate           | frigate.video                  INFO    : entrance: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate           | frigate.video                  INFO    : entrance: ffmpeg process is not running. exiting capture thread...
```

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x561fb5325f00] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://url':
  Metadata:
    title           : Blue Iris
  Duration: N/A, start: 1.176667, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 30 fps, 5 tbr, 90k tbn, 60 tbc
```

**Screenshots**

**Computer Hardware**
 - OS: Ubuntu 20.04
 - Virtualization: no
 - Coral Version: None
 - Network Setup: WiFi

**Camera Info:**
 - Manufacturer: Amcrest
 - Model: ProHD
 - Resolution: 1280x720
 - FPS: 30

**Additional context**
dockercompose:

```
frigate:
    image: blakeblackshear/frigate:0.8.0-rc3-amd64
    container_name: frigate
    privileged: true    
    env_file: env/frigate.env
    volumes:
      - /home/me/frigate/config:/config
      - /media/me/clips:/clips
      - /media/me/recordings:/recordings
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 100000000 # 1GB
```

ENV file is:
LIBVA_DRIVER_NAME=iHD

**Comment by tubalainen** [comment]
Can you please post the debug information as well?
Meanwhile;
- Give it a try and lower the frame rate on the camera to at least half of 30 frames/sec.
- Also add the `fps: 15` to your camera config like this:
- Remove the extra `-` under hardware acceleration (not causing this issue, but for a cleaner and more correct config.yml)

```
cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://url
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    fps: 15
    clips:
      enabled: True
```

**Comment by blakeblackshear** [comment]
Ffmpeg is exiting. Update your config to this to see what the error messages are:
```yaml
logger:
  default: debug

detectors:
  cpu1:
    type: cpu

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
mqtt:
  host: xx
  port: 1883
  topic_prefix: frigate
  client_id: frigate

objects:
  track:
    - person
    - cat
    - dog

cameras:
  entrance:
    ffmpeg:
      inputs:
        - path: rtsp://url
          global_args: -hide_banner -loglevel error
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    clips:
      enabled: True

```
