### ISSUE TITLE
[Support]: Unable to find a suitable output format for 'acc'

### ISSUE THREAD

**Issue by didi3r** [blakeblackshear/frigate#5796]
### Describe the problem you are having

The audio of my cameras used to work just fine until a couple of days ago when it suddenly stopped working. I checked the logs and I found it throws the following error:

```
2023-03-21 08:35:16.706829101  [NULL @ 0x55be89857a00] Unable to find a suitable output format for 'acc'
2023-03-21 08:35:16.706890610  acc: Invalid argument
```

### Version

0.12.0Beta10

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -timeout 5000000
  output_args:
    record: preset-record-generic-audio-aac
    

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 90

snapshots:
  enabled: True
  retain:
      default: 90
  

objects:
  track:
    - person
    # - car
    - dog
    - bicycle
    - motorcycle
    - cat
    
birdseye:
  enabled: True
  mode: continuous
    
go2rtc:
  log:
    level: debug
    
  streams:
    entrance_camera_1:
      - rtsp://*****@192.168.31.15:554/stream1
      - "ffmpeg:entrance_camera_1#audio=acc"
    entrance_camera_1_sub: 
      - rtsp://*****@192.168.31.15:554/stream2
      - "ffmpeg:entrance_camera_1_sub#audio=acc"
    
    entrance_camera_2:
      - rtsp://*****@192.168.31.36:554/stream1
      - "ffmpeg:entrance_camera_2#audio=acc"
    entrance_camera_2_sub: 
      - rtsp://*****@192.168.31.36:554/stream2
      - "ffmpeg:entrance_camera_2_sub#audio=acc"

    patio_camera: 
      - rtsp://*****@192.168.31.18:554/stream1
      - "ffmpeg:patio_camera#audio=acc"
    patio_camera_sub: 
      - rtsp://*****@192.168.31.18:554/stream2
      - "ffmpeg:patio_camera_sub#audio=acc"
    
    back_camera: 
      - rtsp://*****@192.168.31.43:554/stream1
      - "ffmpeg:back_camera#audio=acc"
    back_camera_sub: 
      - rtsp://*****@192.168.31.43:554/stream2
      - "ffmpeg:back_camera_sub#audio=acc"
    
    rooftop_camera: 
      - rtsp://*****@192.168.31.41:554/stream1
      - "ffmpeg:rooftop_camera#audio=acc"
    rooftop_camera_sub: 
      - rtsp://*****@192.168.31.41:554/stream2
      - "ffmpeg:rooftop_camera_sub#audio=acc"

    mias_camera: 
      - rtsp://*****@192.168.31.22:554/stream1
      - "ffmpeg:mias_camera#audio=acc"
    mias_camera_sub: 
      - rtsp://*****@192.168.31.22:554/stream2
      - "ffmpeg:mias_camera_sub#audio=acc"
    

cameras:
  entrance_camera_1:
    ui:
      order: 2
      
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_camera_1?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrance_camera_1_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect

    record:
      events:
        required_zones:
          - street_zone_1
          - sidewalk_zone_1a
          - sidewalk_zone_1b

    snapshots:
      required_zones:
        - street_zone_1
        - sidewalk_zone_1a
        - sidewalk_zone_1b

    motion:
      mask:
        # Timestamp Mask
        - 468,0,471,72,0,80,0,0
        # Others
        - 435,0,375,81,173,205,221,408,611,720,0,720,0,0

    zones:
      street_zone_1:
        coordinates: 1280,194,1280,425,194,158,418,73
        objects: 
          # - car
          - motorcycle
          - bicycle
      sidewalk_zone_1a:
        coordinates: 405,126,1280,273,1280,720,640,720,221,400,158,100
        objects: 
          - person
          - dog
          - cat
      sidewalk_zone_1b:
        coordinates: 1280,0,1280,260,779,164,228,120,220,65,374,58,428,0
        objects: 
          - person
          - dog
          - cat
  
  
  
  entrance_camera_2:
    ui:
      order: 1
      
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_camera_2?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrance_camera_2_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect

    record:
      events:
        required_zones:
          - street_zone_2
          - sidewalk_zone_2a
          - sidewalk_zone_2b

    snapshots:
      required_zones:
        - street_zone_2
        - sidewalk_zone_2a
        - sidewalk_zone_2b

    motion:
      mask:
        # Timestamp Mask
        - 468,0,471,72,0,80,0,0
        # Others
        - 1280,720,1280,0,977,0,953,318,1048,334,643,720

    zones:
      street_zone_2:
        coordinates: 0,221,696,72,956,63,957,113,0,434
        objects: 
          # - car
          - motorcycle
          - bicycle
      sidewalk_zone_2a:
        coordinates: 632,135,980,46,953,310,1040,328,638,720,0,720,0,302
        objects: 
          - person
          - dog
          - cat
      sidewalk_zone_2b:
        coordinates: 517,23,547,0,812,0,982,0,974,56,473,153,0,271,0,100
        objects: 
          - person
          - dog
          - cat
 
 
 
  patio_camera:
    ui:
      order: 3
      
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patio_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
      required_zones:
        - patio_outdoor_zone


    record:
      events:
        required_zones:
          - patio_indoor_zone
          - patio_outdoor_zone

    snapshots:
      required_zones:
        - patio_indoor_zone
        - patio_outdoor_zone

    motion:
      mask:
        # Timestamp Mask
        - 468,0,471,72,0,80,0,0

    zones:
      patio_indoor_zone:
        coordinates: 0,720,273,720,287,312,271,65,0,76
        objects: 
          - person
      patio_outdoor_zone:
        coordinates: 281,317,272,720,1280,720,1280,720,1280,0,812,0,437,0,414,51,277,91
        objects: 
          - person

  
  
  back_camera:
    ui:
      order: 4
      
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect

    record:
      events:
        required_zones:
          - field_left_zone
          - field_right_zone
          - field_boder_zone

    snapshots:
      required_zones:
        - field_left_zone
        - field_right_zone
        - field_boder_zone

    motion:
      mask:
        # Timestamp Mask
        - 468,0,471,72,0,80,0,0

    zones:
      field_left_zone:
        coordinates: 0,348,143,359,147,79,0,78
        objects: 
          - person
      field_right_zone:
        coordinates: 1280,0,1280,493,1093,488,1089,0
        objects: 
          - person
      field_boder_zone:
        coordinates: 1280,720,918,720,597,673,257,579,0,466,0,329,1280,498
        objects: 
          - person
  

  
  rooftop_camera:
    ui:
      order: 5
      
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rooftop_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rooftop_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream    
          roles:
            - detect

    record:
      events:
        required_zones:
          - rooftop_zone_1

    snapshots:
      required_zones:
        - rooftop_zone_1

    motion:
      mask:
        # Timestamp Mask
        - 468,0,471,72,0,80,0,0

    zones:
      rooftop_zone_1:
        coordinates: 1037,496,1034,313,1280,317,1280,720,0,720,0,501,153,505,147,319,825,316,829,482
        objects: 
          - person


  mias_camera:
    ui:
      order: 9

    birdseye:
      enabled: False
      
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/mias_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/mias_camera_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect

    motion:
      mask:
        # Timestamp Mask
        - 468,0,471,72,0,80,0,0
```

### Relevant log output

```shell
2023-03-21 13:08:14.440161407  13:08:14.439 DBG [exec] run url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i rtsp://localhost:8554/mias_camera?audio -vn acc -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/e912c7204a29b9761ea00e8490e313f3"
2023-03-21 13:08:14.466667889  13:08:14.465 DBG [rtsp] new consumer stream=mias_camera
2023-03-21 13:08:14.493038391  [NULL @ 0x563433095780] Unable to find a suitable output format for 'acc'
2023-03-21 13:08:14.493051754  acc: Invalid argument
2023-03-21 13:08:14.493742493  13:08:14.493 DBG [rtsp] handle=EOF
2023-03-21 13:08:14.497564838  13:08:14.497 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:mias_camera#audio=acc
2023-03-21 13:08:14.498142016  13:08:14.497 DBG [streams] can't stop none producer
2023-03-21 13:08:14.498153868  13:08:14.497 DBG [rtsp] disconnect stream=mias_camera
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo c100, c200 and c310
