### ISSUE TITLE
[Config Support]: Frigate docker container marked as unsupported

### ISSUE THREAD

**Issue by NormKOALA** [blakeblackshear/frigate#5802]
### Describe the problem you are having

To be able to use Nvidia GPU hardware acceleration I have migrate from Add-on installation method to Docker-Compose + Frigate Proxy Add-on. All works well, but HA Supervisor said about detecting unsupported installation.

#### docker-compose.yaml
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/username/docker-compose/frigate/volumes/config/config.yml:/config/config.yml:ro
      - /home/username/docker-compose/frigate/volumes/media:/media/frigate
    ports:
      - "5000:5000"
      - "1935:1935"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: ip
  user: user
  password: password

ffmpeg:
  hwaccel_args: -c:v h264_cuvid

cameras:
  Hall_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/stream2
          roles:
          - detect
        - path: rtsp://user:password@ip:554/stream1
          roles:
          - record
    detect:
      enabled: true
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2 # days
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 2 # days
    motion:
      mask:
      - 788,0,808,398,1015,391,1020,0,1920,0,1920,1080,0,1080,0,0

  Livingroom_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/stream1
          roles:
          - detect
    detect:
      enabled: false
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
      - person

  Facade_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@ip:554/h264Preview_01_sub
          roles:
          - detect
        - path: rtsp://user:password@ip:554/h264Preview_01_main
          roles:
          - record
    detect:
      enabled: true
      max_disappeared: 25
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
      - person
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2 # days
    record:
      enabled: true
      retain_days: 0
      events:
        retain:
          default: 2 # days
    motion:
      mask:
      - 819,272,1377,268,2111,314,2560,750,2560,0,0,0,0,386,251,347


detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  logs:
    frigate.edgetpu: debug
```

### Relevant log output

```shell
23-03-22 13:50:26 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported images: {'blakeblackshear/frigate'} (more-info: https://www.home-assistant.io/more-info/unsupported/software)
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
