### ISSUE TITLE
[Config Support]: Hardware Acceleration Not Working

### ISSUE THREAD

**Issue by weswitt** [blakeblackshear/frigate#5817]
### Describe the problem you are having

trying to get hardware acceleration working, but ffmpeg is not happy. in the frigate system tab i can see that hardware acceleration is enabled & working. i also have the nvidia gpu working with tensorrt detector. so that's all good. but i want hwaccel to work too.

i get these errors in the logs for the camera's ffmpeg.

[h264_cuvid @ 0x5644496ed900] Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x5644496ed900] Failed loading nvcuvid

here is my docker run command:

docker run --rm --name frigate --privileged --shm-size=512m --runtime=nvidia --gpus all -v /dev/bus/usb:/dev/bus/usb -v /etc/localtime:/etc/localtime:ro -v /opt/frigate/config/config.yml:/config/config.yml:ro -v /opt/frigate/trt-models:/trt-models:ro -v /opt/frigate/media:/media/frigate:rw -e USE_FP16=False -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp -e FRIGATE_RTSP_PASSWORD='password' ghcr.io/blakeblackshear/frigate:0.12.0-beta10-tensorrt

### Version

0.12

### Frigate config file

```yaml
relevant parts of my config:

ffmpeg:
  hwaccel_args: -c:v h264_cuvid

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
[h264_cuvid @ 0x5644496ed900] Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x5644496ed900] Failed loading nvcuvid.
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB
