### ISSUE TITLE
Significant increase in CPU usage in recent build(s)

### ISSUE THREAD

**Issue by daernsinstantfortress** [blakeblackshear/frigate#5821]
### Describe the problem you are having

Seeing a significant amount of CPU usage from `frigate.detector.coral` process, which is running at 50% CPU much of the time, despite having a Coral handling offloading of object detection. It's noticeable that there is a significant increase in CPU usage on  when there is activity on a camera. My understanding was that with a correctly configured Coral, this process should have a relatively light footprint on the RPi CPU.

e.g. 
```
   6585 root      20   0  908.2m  76.1m  54.1   2.1  65:49.74 S frigate.process:driveway
  36049 root      20   0 2252.9m 183.6m  45.2   5.1  43:21.67 R frigate.detector.coral
```

(Note: this is separate from the ffmpeg CPU utilisation which has also increased since 0.11, but I believe this is mostly due to a reduction in efficiency to workaround the hardware decoding issues introduced in the RPi firmware last summer)

Coral is connected and working, and Frigate is functionally ok, but since 0.11 to latest 0.12 beta 10, CPU utilisation has increased from 40% to 80% for the same camera configuration from a combination of the above. It's a little hard to roll back add-ons in Home Assistant, but I would be happy to do this in order to validate exactly when this changed and quantify the increase in CPU utilisation.

### Version

0.12.0-beta10

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.94
  port: 1883
  user: mqttuser
  password: mqttuser
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
detectors:
  coral:
    type: edgetpu
    device: usb
record:
  enabled: True
  events:
    retain:
      default: 10
objects:
    track:
      - person
    filters:
      person:
        min_area: 3000
        max_area: 100000
        max_ratio: 0.7 

motion:
  threshold: 15

cameras:
  driveway:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.254.12:554/Streaming/Channels/103
            roles:
              - detect
              - record
      rtmp:
        enabled: false
      detect: 
        width: 1280
        height: 720
        enabled: true
      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        crop: false
        required_zones:
          - lower_drive 
      motion:
        mask:
          - 407,49,404,0,22,0,22,52
      record:
        events:
          objects:
            - person
            - car
          required_zones:
            - lower_drive    
      mqtt:
        required_zones:
          - lower_drive 
      zones:
        lower_drive:
          coordinates: 1280,720,1280,314,969,267,685,250,326,258,226,340,0,344,0,720
        road:
          coordinates: 1280,0,1280,314,969,267,685,250,326,258,226,340,0,344,0,0
      objects:
        track:
          - person
          - car
        # filters:
        #   car:
        #     min_score: 0.75
        #   person:
        #     min_area: 3000
        #     max_area: 100000
        #     min_score: 0.5
        #     threshold: 0.7      
  back_door:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.254.14:554/Streaming/Channels/103
            roles:
              - detect
              - record
#        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 1280
        height: 720
        enabled: true
      snapshots:
        enabled: true
        required_zones:
          - upper_drive 
      mqtt:
        required_zones:
          - upper_drive         
      motion:
        mask:
          - 407,72,407,32,22,34,27,76
      record:
        events:
          objects:
            - person
            - car
            - dog
          required_zones:
            - upper_drive 
      zones:
        upper_drive:
          coordinates: 1280,720,1280,622,1063,293,965,188,910,425,739,114,559,109,560,0,336,0,136,83,70,106,0,160,0,720
          objects:
            - person
            - car
            - dog
      objects:
          track:
            - person
            - car
            - dog
          filters:
            person:
              mask:
                - 770,120,770,0,992,0,916,394
  patio:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.254.11:554/Streaming/Channels/103
            roles:
              - detect
              - record
#        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 1280
        height: 720
        enabled: true
      snapshots:
        enabled: true
      motion:
        mask:
          - 407,49,404,0,22,0,22,52
      objects:
          track:
            - person
            - dog
      zones:
        lower_garden:
          coordinates: 0,720,1280,720,1280,0,0,0

  garage_door:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.254.15:554/Streaming/Channels/102
            roles:
              -detect
              - record
#        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 640
        height: 480
        enabled: true
      snapshots:
        enabled: true
      motion:
        mask:
          - 218,24,220,48,24,49,26,21        
      zones:
        passage:
          coordinates: 0,0,0,480,640,480,640,0          
  back_garden:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.254.6:554/Streaming/Channels/102
            roles:
              - detect
              - record
#        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 640
        height: 480
        enabled: true
      snapshots:
        enabled: true
      motion:
        mask:
          - 22,44,220,40,219,21,23,21
      objects:
          track:
            - person
            - dog
      zones:
        middle_garden:
          coordinates: 0,480,640,480,640,0,0,0
  garage:
      ffmpeg:
        inputs:
          - path: rtsp://user:pass@192.168.254.16:554/Streaming/Channels/102
            roles:
              - detect
              - record
#        hwaccel_args: preset-rpi-64-h264
      rtmp:
        enabled: false
      detect: 
        width: 640
        height: 480
        enabled: true
      snapshots:
        enabled: true
      zones:
        garage_inside:
          coordinates: 0,0,0,480,640,480,640,0
      # motion:
      #   mask:
      #     - 0,25,204,27,209,0,0,0
```

### docker-compose file or Docker CLI command

```yaml
HAOS Add-on install
```

### Relevant log output

```shell
PID USER      PR  NI    VIRT    RES  %CPU  %MEM     TIME+ S COMMAND
  36049 root      20   0 2252.9m 183.6m  50.0   5.1  44:42.25 S frigate.detector.coral
   6585 root      20   0  908.2m  76.1m  42.5   2.1  67:12.98 S frigate.process:driveway
  49955 root      20   0  248.9m  51.4m  26.2   1.4 184:29.51 S ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_v4l2m2m -user_agent FFmpeg Friga+
  49953 root      20   0  249.1m  51.5m  23.1   1.4 188:02.60 R ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_v4l2m2m -user_agent FFmpeg Friga+
  49957 root      20   0  249.0m  51.6m  21.2   1.4 151:57.49 S ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_v4l2m2m -user_agent FFmpeg Friga+
   6120 root      20   0 2386.4m 176.3m  20.6   4.9 158:47.30 S python3 -u -m frigate
   6590 root      20   0  906.6m  73.2m  16.2   2.0  35:05.58 S frigate.process:patio
   6594 root      20   0  893.7m  61.4m  15.0   1.7  20:13.39 S frigate.process:back_garden
 129902 root      20   0  192.5m  16.0m  10.6   0.4   0:00.17 R ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 /tmp/+
  49951 root      20   0  221.8m  45.5m   9.4   1.3  46:46.84 R ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_v4l2m2m -user_agent FFmpeg Friga+
   6598 root      20   0  904.1m  57.0m   7.5   1.6  73:08.66 S frigate.capture:back_door
   6596 root      20   0  904.1m  57.0m   6.9   1.6  73:58.53 S frigate.capture:driveway
  49978 root      20   0  222.0m  45.8m   6.9   1.3  47:28.24 S ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_v4l2m2m -user_agent FFmpeg Friga+
   6599 root      20   0  904.1m  56.9m   6.2   1.6  73:12.16 S frigate.capture:patio
   6578 root      20   0 1109.5m  60.4m   5.6   1.7  65:13.97 S frigate.output
  49959 root      20   0  221.9m  45.3m   5.6   1.3  48:00.11 S ffmpeg -hide_banner -loglevel warning -threads 2 -c:v h264_v4l2m2m -user_agent FFmpeg Friga+
   4185 root      20   0 1111.9m 372.0m   5.0  10.3  65:17.68 S python3 -m homeassistant --config /config
 128028 root      20   0    5.0m   2.9m   4.4   0.1   0:40.87 R top
 120532 root      20   0   52.8m  36.4m   3.8   1.0   3:24.34 S python3 -m backup
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
