### ISSUE TITLE
Feature request: "Motion detected" global sensor

### ISSUE THREAD

**Issue by cben0ist** [blakeblackshear/frigate#583]
Can we expose a global sensor in Home assistant? ie a binary sensor that would be on whenever we see a motion box in the camera back-end and off otherwise .
Doesn't have to be that an object has been detected but just that motion has been detected.
Or is there a way to do that already ?
Thank you.

**Comment by HITChris** [comment]
Via the custom integration, I'd think sensor.detection_fps should give you what you need? E.g. sensor.detection_fps > 0.0

**Comment by cben0ist** [comment]
Good point! I'll give this a try.
Thanks

**Comment by cben0ist** [comment]
That definitely provided the expected result, thank you!
```
- platform: template
  sensors:
    backyard_cam_motion:
      friendly_name: "Backyard Cam Motion"
      value_template: "{{ states('sensor.backyard_detection_fps')|float > 0 }}"
```
