### ISSUE TITLE
[Support]: camera access url

### ISSUE THREAD

**Issue by bobdivx** [blakeblackshear/frigate#5830]
### Describe the problem you are having

I first installed frigate in a container, I could access my camera via: http://10.1.0.97:5000/api/entree
Now I have installed Frigate via Home assistant, but cannot find how to access the same page obtained because I have a 404 error

I use this to broadcast my video stream on my android TV via PIPUP;
### Version

Home Assistant 2023.3.6 Supervisor 2023.03.2 Operating System 9.5 Interface utilisateur : 20230309.1 - latest

### Frigate config file

```yaml
mqtt:
  host: 10.1.0.141
  user: mqtt-user
  password:
cameras:
  entree:
    ffmpeg:
      inputs:
        - path: rtsp://10.1.0.22:7447/biRI2mBx7po?enablertp
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  #height: 175
  required_zones: []
  retain:
    default: 1
    objects:
      person: 30

motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 180
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  #mask: 0,0,720,0,720,169,653,103,579,75,461,52,350,42,250,42,136,63,0,208



detect:
  width: 720
  height: 576
  fps: 5
  enabled: True
  max_disappeared: 25

objects:
  track:
    - person
    - car
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
  #mask: 269,68,429,49,621,46,852,61,1117,113,1280,207,1280,0,0,0,0,246
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
#      mask: 0,0,1000,0,1000,200,0,200
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Unifi
