### ISSUE TITLE
Snapshot API returns 404 Error

### ISSUE THREAD

**Issue by kidhasmoxy** [blakeblackshear/frigate#584]
**Describe the bug**
Attempting to access a snapshot for an event via API returns a 404 error. 

**Version of frigate**
0.8.0-7B4E510 (rc3)

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral:
    device: 'usb:0'
    type: edgetpu
mqtt:
  host: core-mosquitto
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p
cameras:
  front:
    width: 1536
    height: 2048
    objects:
      track:
        - person
        - car
        - dog
    motion:
      mask:
        - '1536,0,1536,1024,1109,1038,270,1027,223,1012,2,868,1,0'
    ffmpeg:
      inputs:
        - path: 'rtsp'
          roles:
            - rtmp
            - clips
            - record
            - detect
    fps: 5
    snapshots:
      enabled: true
      bounding_box: true
      timestamp: false
    clips:
      enabled: true
      objects:
        - person
        - dog
    zones:
      front_yard:
        coordinates: >-
          422,1114,815,1129,1220,1122,1331,1117,1452,1105,1536,1110,1535,2045,0,2048,0,1079
```

**Logs**
```
Include relevant log output here
```

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Computer Hardware**
Hassos on NUC hardwired network

**Additional context**
Generating URL in automation via `http://ccab4aaf-frigate-beta:5000/api/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg`

Also unable to access via copying an event and accessing directly via port 5000 mapped from host. Snapshot exists in UI and am able to access it via /clips/<camera>-<id>.jpg

Clips endpoint does not have the querystring params available that I use with the notification in some of my automations

snippet of event json 
```
{"camera":"front","end_time":1611344494.125814,"false_positive":false,"has_clip":true,"has_snapshot":true,"id":"1611344476.142118-33p66x","label":"person","start_time":1611344476.142118
```
