### ISSUE TITLE
[Support]: "Detect" low-res stream in web UI

### ISSUE THREAD

**Issue by hlzr** [blakeblackshear/frigate#5845]
### Describe the problem you are having

Hi, I've just set up frigate with an Amcrest camera with support for 2 streams.  I have one set up for "detect" and the other set up for "rtmp" and "record".   Recordings show up using the higher resolution camera, but when browsing the web ui and looking at the current camera view, I get the "detect" camera stream (which is pretty limited on my camera, only 704x480; the camera doesn't allow me to go any higher).

Is there a way that I can see the "record" camera stream in the web UI instead?

### Version

0.11.1-2eada21

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.36
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  garage_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.200:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.200:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution

birdseye:
  enabled: True
  mode: continuous

record:
  enabled: True
  events:
    retain:
      default: 10

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Amcrest IP5M-T1179EW-28MM
