### ISSUE TITLE
[Config Support]: Reduce motion detection false positives.

### ISSUE THREAD

**Issue by frakman1** [blakeblackshear/frigate#5849]
### Describe the problem you are having

I have a camera pointing at a hallway with many people crossing it. 
I am only interested in capturing the motion of people who linger more than a few seconds in front of the camera.
Currently, all crossings are being captured and recorded. Those are ones I consider to be false positives.

I looked at the config file documentation around `motion` and the variables seem to be around pixel size and area to determine thresholds (`threshold`,`contour_area`). I didn't see an option for length of time a motion is detected before considering it a true positive match.

Is there a way to use the time that motion is detected as a trigger?

### Version

0.12.0-66881EB

### Frigate config file

```yaml
mqtt:
  host: xxxxx

ui:
  use_experimental: true

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  track:
    - person
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      #min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200


# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 2
    # Optional: Per object retention days
    objects:
      person: 3

record:
  enabled: True
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    retain:
      default: 3

      
cameras:
 
  picam_office:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        #(motion eye link)
        - path: https://xxxxx 
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1024
      height: 768
      fps: 5
```

### Relevant log output

```shell
NA
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)
