### ISSUE TITLE
[Restream]: Missing audio stream in restream

### ISSUE THREAD

**Issue by kyvaith** [blakeblackshear/frigate#5850]
### Describe the problem you are having

I'm trying to use a restream and video works well, but the audio stream is missing. 

- without additional ffmpeg parms there is no audio in mse and webrtc stream
- with "ffmpeg:front#audio=copy" there is no audio in mse and webrtc stream
- with "ffmpeg:front#audio=opus" there is no audio in mse and webrtc stream
- with "ffmpeg:front#audio=aac"  _there is_ audio in mse (but high latency) but not in webrtc stream

What missing is the possibility to copy the audio stream from the original source.
Thanks.

### Version

Frigate (Full Access) Beta (0.12.0)

### Frigate config file

```yaml
go2rtc:
  api:
    origin: "*"
  streams:
    front:
      - rtsp://admin:password!@192.168.88.233/media/video1/
      - "ffmpeg:front#audio=copy"
cameras:
  front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://admin:password!@192.168.88.233/media/video2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect: 
      width: 720
      height: 576
      fps: 10
      enabled: true
    record:
      enabled: true
      retain:
        days: 5
      events:
        retain:
          default: 15
    objects:
      track:
        - person
        - car
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: false
      required_zones: []
      retain:
        default: 3
        objects:
          person: 15
mqtt:
  host: 192.168.88.3
  user: homeassistant
  password: oonah3chahc0ieba8asay7hai4sha6Ushing4iethahg8boGheed7iemahhee2ya
ui:
  use_experimental: true
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2023-03-27 18:32:17.243256053  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-03-27 18:32:17.267669859  [INFO] Starting Frigate...
2023-03-27 18:32:17.289609462  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-03-27 18:32:17.466918466  [INFO] Got IP address from supervisor: 192.168.88.3
2023-03-27 18:32:17.656293127  [INFO] Got WebRTC port from supervisor: 8555
2023-03-27 18:32:18.586674782  [INFO] Starting go2rtc...
2023-03-27 18:32:18.832353494  20:32:18.832 INF go2rtc version 1.2.0 linux/amd64
2023-03-27 18:32:18.834341992  20:32:18.834 INF [api] listen addr=:1984
2023-03-27 18:32:18.835477924  20:32:18.835 INF [rtsp] listen addr=:8554
2023-03-27 18:32:18.838667840  20:32:18.838 INF [srtp] listen addr=:8443
2023-03-27 18:32:18.840069085  20:32:18.839 INF [webrtc] listen addr=:8555
2023-03-27 18:32:21.764715350  [2023-03-27 20:32:21] frigate.app                    INFO    : Starting Frigate (0.12.0-7d589bd)
2023-03-27 18:32:21.827942885  [2023-03-27 20:32:21] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-03-27 18:32:21.835159777  [2023-03-27 20:32:21] peewee_migrate                 INFO    : Starting migrations
2023-03-27 18:32:21.852365764  [2023-03-27 20:32:21] peewee_migrate                 INFO    : There is nothing to migrate
2023-03-27 18:32:21.927369935  [2023-03-27 20:32:21] frigate.app                    INFO    : Output process started: 298
2023-03-27 18:32:21.934182973  [2023-03-27 20:32:21] detector.cpu                   INFO    : Starting detection process: 297
2023-03-27 18:32:21.943138629  [2023-03-27 20:32:21] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-03-27 18:32:21.992517607  [2023-03-27 20:32:21] frigate.app                    INFO    : Camera processor started for front: 302
2023-03-27 18:32:21.998084285  [2023-03-27 20:32:21] frigate.app                    INFO    : Capture process started for front: 304
2023-03-27 18:32:27.275555595  [INFO] Starting go2rtc healthcheck service...
2023-03-27 18:32:35.983977099  192.168.88.3 - - [27/Mar/2023:20:32:35 +0200] "GET /get_vehicleinfo/VF3M4DGZUMS226734?from_cache=1 HTTP/1.1" 200 6641 "-" "HomeAssistant/2023.3.6 httpx/0.23.3 Python/3.10" "-"
2023-03-27 18:32:35.998454354  192.168.88.3 - - [27/Mar/2023:20:32:35 +0200] "GET /charge_control?vin=VF3M4DGZUMS226734&?always_check=true HTTP/1.1" 200 6641 "-" "HomeAssistant/2023.3.6 httpx/0.23.3 Python/3.10" "-"
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You need to provide the ffprobe of the original camera stream otherwise there is no way to help

**Comment by kyvaith** [comment]
Sure:

```shell
FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 30/1

Audio:

Codec: PCM mu-law / G.711 mu-law
```

**Comment by NickM-27** [comment]
Okay, audio should work out of the box for webrtc. In this case, you should start a webrtc live view in frigate and then also open the go2rtc dashboard (available at frigate_ip:5000/live/webrtc OR frigate_ip:1984) and use the stream info button and paste that entire json blob here while the webrtc stream is ongoing

**Comment by kyvaith** [comment]
Here you go:

```shell
{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.88.233:554/media/video1/",
      "remote_addr": "192.168.88.233:554",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, sendonly, 105 H264/90000",
        "audio, sendonly, 0 PCMU/8000",
        "audio, recvonly, 0 PCMA/8000",
        "application, sendonly, 107 VND.ONVIF.METADATA/90000"
      ],
      "tracks": [
        "105 H264/90000, sinks=2",
        "0 PCMU/8000, sinks=1"
      ],
      "recv": 81378987
    },
    {
      "url": "ffmpeg:front#audio=copy"
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://127.0.0.1:8554/front",
      "remote_addr": "127.0.0.1:40702",
      "user_agent": "FFmpeg Frigate/0.12.0-7d589bd",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 0 MPEG4-GENERIC/0"
      ],
      "tracks": [
        "96 H264/90000, sinks=2"
      ],
      "send": 79854834
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.88.244:65051 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
      "send": 5503016
    }
  ]
}
```

**Comment by NickM-27** [comment]
There may be some kind of issues with your cameras 2 way talk / audio backchannel. I'd suggest updating your config to:

```yaml
go2rtc:
  api:
    origin: "*"
  streams:
    front:
      - rtsp://admin:password!@192.168.88.233/media/video1/#backchannel=0
      - "ffmpeg:front#audio=aac"
```

**Comment by kyvaith** [comment]
Please take a look at the description. I am able to transcode to aac but I want to keep the PCM. Adding only _#backchannel=0_ don't hep unfortunately

**Comment by NickM-27** [comment]
> Please take a look at the description. I am able to transcode to aac but I want to keep the PCM. Adding only _#backchannel=0_ don't help unfortunately

yes, I read the description. using ffmpeg to copy the audio does absolutely nothing, no point to have that. The frigate config asks for aac audio by default so your recordings won't have any audio unless you set the config to ask for that specifically.

Can you include the json blob from go2rtc with backchannel set to 0?

**Comment by kyvaith** [comment]
Maybe related? https://github.com/AlexxIT/go2rtc/issues/108

**Comment by NickM-27** [comment]
What happens if you run the entire camera in ffmpeg:

```yaml
go2rtc:
  api:
    origin: "*"
  streams:
    front:
      - "ffmpeg:rtsp://admin:password!@192.168.88.233/media/video1/"
```

> But converting to aac is not an option for me.

okay, then you also need to update the camera config 

```yaml
cameras:
  front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
       ...
```

> Maybe related? https://github.com/AlexxIT/go2rtc/issues/108

that was fixed long before the current version of go2rtc that is used in frigate

**Comment by NickM-27** [comment]
> > What happens if you run the entire camera in ffmpeg:
> 
> It works well.

in that case I would suggest leaving the setup running that way. You can make an issue on go2rtc but there is a newer go2rtc version which may have fixed this. Frigate has pinned the go2rtc dep to version 1.2.1 for the 0.12 release

> > okay, then you also need to update the camera config
> 
> It gots interesting in logs after adding ?video&audio
> 
> ```shell
> s6-rc: info: service s6rc-fdholder: starting
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service s6rc-fdholder successfully started
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service log-prepare: starting
> s6-rc: info: service log-prepare successfully started
> s6-rc: info: service nginx-log: starting
> s6-rc: info: service go2rtc-log: starting
> s6-rc: info: service frigate-log: starting
> s6-rc: info: service nginx-log successfully started
> s6-rc: info: service go2rtc-log successfully started
> s6-rc: info: service go2rtc: starting
> s6-rc: info: service frigate-log successfully started
> s6-rc: info: service go2rtc successfully started
> s6-rc: info: service go2rtc-healthcheck: starting
> s6-rc: info: service frigate: starting
> s6-rc: info: service go2rtc-healthcheck successfully started
> s6-rc: info: service frigate successfully started
> 2023-03-27 19:22:40.058549523  [INFO] Preparing go2rtc config...
> s6-rc: info: service nginx: starting
> s6-rc: info: service nginx successfully started
> s6-rc: info: service legacy-services: starting
> 2023-03-27 19:22:40.101249033  [INFO] Starting Frigate...
> 2023-03-27 19:22:40.102957435  [INFO] Starting NGINX...
> s6-rc: info: service legacy-services successfully started
> 2023-03-27 19:22:40.300722041  [INFO] Got IP address from supervisor: 192.168.88.3
> 2023-03-27 19:22:40.507441415  [INFO] Got WebRTC port from supervisor: 8555
> 2023-03-27 19:22:41.547672597  [INFO] Starting go2rtc...
> 2023-03-27 19:22:41.844963290  21:22:41.844 INF go2rtc version 1.2.0 linux/amd64
> 2023-03-27 19:22:41.845984717  21:22:41.845 INF [api] listen addr=:1984
> 2023-03-27 19:22:41.849356955  21:22:41.849 INF [rtsp] listen addr=:8554
> 2023-03-27 19:22:41.850137982  21:22:41.849 INF [srtp] listen addr=:8443
> 2023-03-27 19:22:41.850920430  21:22:41.850 INF [webrtc] listen addr=:8555
> 2023-03-27 19:22:44.840873131  [2023-03-27 21:22:44] frigate.app                    INFO    : Starting Frigate (0.12.0-7d589bd)
> 2023-03-27 19:22:44.909357460  [2023-03-27 21:22:44] frigate.app                    INFO    : Creating directory: /tmp/cache
> 2023-03-27 19:22:44.914911028  [2023-03-27 21:22:44] peewee_migrate                 INFO    : Starting migrations
> 2023-03-27 19:22:44.929981119  [2023-03-27 21:22:44] peewee_migrate                 INFO    : There is nothing to migrate
> 2023-03-27 19:22:44.987756837  [2023-03-27 21:22:44] frigate.app                    INFO    : Output process started: 301
> 2023-03-27 19:22:45.078297552  [2023-03-27 21:22:45] frigate.app                    INFO    : Camera processor started for front: 305
> 2023-03-27 19:22:45.083536122  [2023-03-27 21:22:45] frigate.app                    INFO    : Capture process started for front: 307
> 2023-03-27 19:22:45.095240355  [2023-03-27 21:22:44] detector.cpu                   INFO    : Starting detection process: 300
> 2023-03-27 19:22:45.095260336  [2023-03-27 21:22:45] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
> 2023-03-27 19:22:50.082168428  [INFO] Starting go2rtc healthcheck service...
> 2023-03-27 19:22:50.863179618  [2023-03-27 21:22:50] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/front-20230327212246.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55600edd26c0] moov atom not found\n/tmp/cache/front-20230327212246.mp4: Invalid data found when processing input\n'
> 2023-03-27 19:22:50.863192525  [2023-03-27 21:22:50] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/front-20230327212246.mp4
> 2023-03-27 19:23:05.256789507  [2023-03-27 21:23:05] ffmpeg.front.record            ERROR   : [mp4 @ 0x55976a8a1c00] Could not find tag for codec pcm_mulaw in stream #1, codec not currently supported in container
> 2023-03-27 19:23:05.257672098  [2023-03-27 21:23:05] ffmpeg.front.record            ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> 2023-03-27 19:23:05.258995813  [2023-03-27 21:23:05] ffmpeg.front.record            ERROR   : Error initializing output stream 0:1 -- 
> 2023-03-27 19:23:05.259006245  [2023-03-27 21:23:05] ffmpeg.front.record            ERROR   : 
> 2023-03-27 19:23:05.259010487  [2023-03-27 21:23:05] watchdog.front                 INFO    : Terminating the existing ffmpeg process...
> 2023-03-27 19:23:05.259192679  [2023-03-27 21:23:05] watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
> 2023-03-27 19:23:10.857652660  [2023-03-27 21:23:10] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/front-20230327212306.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b0733d96c0] moov atom not found\n/tmp/cache/front-20230327212306.mp4: Invalid data found when processing input\n'
> 2023-03-27 19:23:10.858022558  [2023-03-27 21:23:10] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/front-20230327212306.mp4
> 2023-03-27 19:23:15.278912639  [2023-03-27 21:23:15] ffmpeg.front.record            ERROR   : [mp4 @ 0x55d6fc7e4e80] Could not find tag for codec pcm_mulaw in stream #1, codec not currently supported in container
> 2023-03-27 19:23:15.279268322  [2023-03-27 21:23:15] ffmpeg.front.record            ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> 2023-03-27 19:23:15.279402723  [2023-03-27 21:23:15] ffmpeg.front.record            ERROR   : Error initializing output stream 0:1 -- 
> 2023-03-27 19:23:15.279768315  [2023-03-27 21:23:15] ffmpeg.front.record            ERROR   : 
> 2023-03-27 19:23:15.279843636  [2023-03-27 21:23:15] watchdog.front                 INFO    : Terminating the existing ffmpeg process...
> 2023-03-27 19:23:15.280015559  [2023-03-27 21:23:15] watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
> 2023-03-27 19:23:20.849163086  [2023-03-27 21:23:20] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/front-20230327212316.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x561f864e16c0] moov atom not found\n/tmp/cache/front-20230327212316.mp4: Invalid data found when processing input\n'
> 2023-03-27 19:23:20.849174818  [2023-03-27 21:23:20] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/front-20230327212316.mp4
> 2023-03-27 19:23:25.299379117  [2023-03-27 21:23:25] ffmpeg.front.record            ERROR   : [mp4 @ 0x55e9019577c0] Could not find tag for codec pcm_mulaw in stream #1, codec not currently supported in container
> 2023-03-27 19:23:25.300088017  [2023-03-27 21:23:25] ffmpeg.front.record            ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> 2023-03-27 19:23:25.300095111  [2023-03-27 21:23:25] ffmpeg.front.record            ERROR   : Error initializing output stream 0:1 -- 
> 2023-03-27 19:23:25.300097544  [2023-03-27 21:23:25] ffmpeg.front.record            ERROR   : 
> 2023-03-27 19:23:25.300100156  [2023-03-27 21:23:25] watchdog.front                 INFO    : Terminating the existing ffmpeg process...
> 2023-03-27 19:23:25.307955286  [2023-03-27 21:23:25] watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
> 2023-03-27 19:23:30.862135633  [2023-03-27 21:23:30] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/front-20230327212326.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5636c9ccd6c0] moov atom not found\n/tmp/cache/front-20230327212326.mp4: Invalid data found when processing input\n'
> 2023-03-27 19:23:30.862563118  [2023-03-27 21:23:30] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/front-20230327212326.mp4
> ```

So that makes sense, because your cameras pcmu is not compatible for mp4 recordings with ffmpeg. You will need to add aac transcoding (either in go2rtc or in the frigate output args) to have audio in the recordings.

**Comment by kyvaith** [comment]
Well, I'm unable to keep the setup where I have a one connection to the camera 1080p stream for recording and another connection to the same stream for the live preview because it works really bad with this camera. I had hopes in the restreaming features of Frigate with without audio it is the problem. Can't we just force go2rtc to keep the audio stream as it is? Another find: http://ffmpeg.org/pipermail/ffmpeg-user/2018-January/038641.html

**Comment by NickM-27** [comment]
You seem to be misunderstanding how this works. Using go2rtc it would only ever have one connection to your camera. Live preview in frigate and recording would only ever use one connection to the camera even if you have aac audio transcoding enabled, which is the whole point of the feature

**Comment by kyvaith** [comment]
Just to clarify - I was expecting, that restream feature will restream RTSP stream. Form what you're saying I understand now it captures the original RTSP stream, unpacks te RT container, re-packs it into the MP4 container (without streams transcoding) and stream it again as a RTSP with MP4 container instead RT. This way it would be obvious for me, there is no way to restream PCM audio. But is that correct? Also can't we just keep the RT container in restream? Is this something that would be for you to consider or guys behind the go2rtc project?

**Comment by NickM-27** [comment]
> Just to clarify - I was expecting, that restream feature will restream RTSP stream. Form what you're saying I understand now it captures the original RTSP stream, unpacks te RT container, re-packs it into the MP4 container (without streams transcoding) and stream it again as a RTSP with MP4 container instead RT. This way it would be obvious for me, there is no way to restream PCM audio. But is that correct? Also can't we just keep the RT container in restream? Is this something that would be for you to consider or guys behind the go2rtc project? 

No that is incorrect. The mp4 container is for frigate recordings not go2rtc, that part has nothing to do with go2rtc. 

Go2rtc supports your cameras audio fine, if you want frigates recordings to have audio then you will need to either have go2rtc transcode to aac (creating an additional producer but NOT increasing the connections to the camera) or you can simply update the frigate output args to use preset-record-generic-audio-aac which will transcode it just for recordings

**Comment by kyvaith** [comment]
Omg, that was the missing part xD I simply needed to change preset to aac. Now I have working recording with audio in aac (where latency is not so important) and a live view with PCM audio! Thank you!

```yaml
go2rtc:
  api:
    origin: "*"
  streams:
    front:
      - rtsp://admin:pass!@192.168.88.233/media/video1/
cameras:
  front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video&audio
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
```
