### ISSUE TITLE
[Config Support]: Config file not found error 

### ISSUE THREAD

**Issue by tmbiggs** [blakeblackshear/frigate#5853]
### Describe the problem you are having

Same error over and over. I can't seem to sort it out. 
When I look for the directory that contains frigate, I don't see it. Perhaps I am looking in the wrong place. I see Mosquitto and Node-Red etc in the volumes folder but no frigate so perhaps a crappy install?

### Version

(0.11.1-2eada21)

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.191
  port: 1883

cameras:
  FrontDoor:
    ffmpeg:
      inputs: 
        - path: rtsp://192.168.1.88
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 800
*************************************************
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /IOTstack/config/frigate/config/config.yml:/config/config.yml:ro
      - /HA2NAS:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
*************************************************************

*************************************************************

[2023-03-28 00:04:33] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)

***    Your config file is not valid!                     ***

***    Please check the docs at                           ***

***    https://docs.frigate.video/configuration/index     ***

*************************************************************

*************************************************************

***    Config Validation Errors                           ***

*************************************************************

[Errno 21] Is a directory: '/config/config.yml'

Traceback (most recent call last):

  File "/opt/frigate/frigate/app.py", line 332, in start

    self.init_config()

  File "/opt/frigate/frigate/app.py", line 82, in init_config

    user_config = FrigateConfig.parse_file(config_file)

  File "/opt/frigate/frigate/config.py", line 934, in parse_file

    with open(config_file) as f:

IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'

*************************************************************

***    End Config Validation Errors                       ***

*************************************************************

[cmd] python3 exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Container continually restarts. 
The "HA2NAS" in the home directory is linked to Synology. 
File structure:
home/IOTstack (location of docker-compose.yml)
home/IOTstack/config/frigate/config/config.yml 
(Coral to be added later.)
