### ISSUE TITLE
[Support]: Recordings and clips no longer playing since upgrade to 0.12.0-rc1.

### ISSUE THREAD

**Issue by limitless-code** [blakeblackshear/frigate#5862]
### Describe the problem you are having

Recordings and clips no longer playing since upgrade to 0.12.0-rc1. videos not playing back. Uploading an mp4 sample file does play from the "media" folder, jpg and png files display as well as an mp3 file plays that was uploaded, but recordings do not. Was fine yesterday after upgrade to rc1 but over night all recordings and clips fail to play.

### Version

0.12.0-rc1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate-fa-beta:5000/api/config/schema
mqtt:  
  host: <>
  user: <>
  password: <>

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Main-Drive:
    rtmp:
      enabled: false
    ffmpeg:
      global_args: -y -hide_banner -loglevel warning
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format 
        - yuv420p
#      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      input_args: preset-rtsp-generic
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
#        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -b:v 4M -r 25
        record: preset-record-generic
        rtmp: -c:vv copy -c:a aac -f flv
      inputs:
        - path: rtsp://viewer:<>:<>@<>:554
          roles:
            - detect
            - clips
    detect:  
      # Optional: width of the frame for the input with the detect role (default: shown below)
      width: 1280
      # Optional: height of the frame for the input with the detect role (default: shown below)
      height: 720
      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
      fps: 25
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      #max_disappeared: 25        
    zones:
      main_drive:
        coordinates: 1025,450,883,354,583,382,327,364,87,537,0,720,1280,720
#     zone_main_drive_full_height:
#      coordinates: 0,720,1280,720,1280,131,0,140
    record:
      enabled: True
        # Optional: Number of days to retain recordings regardless of events (default: shown below)#        
        # NOTE: This should be set to 0 and retention should be defined in events section below
        #       if you only want to retain recordings of events.
      retain:
        days: 7
        mode: active_objects
      # Optional: Event recording settings
      events:
          # Optional: Maximum length of time to retain video during long events. (default: shown below)#          # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
          #       will be the last x seconds of the event unless retain_days under record is > 0.
#        max_seconds: 300
          # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 15
          # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 20
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - car
        retain:
          default: 7
          mode: active_objects
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
        required_zones: [main_drive]
          # Optional: Retention settings for recordings of events
#    retain:
          # Required: Default retention days (default: shown below)
#      default: 7
      # Optional: Per object retention days
 #     objects:
 #       person: 10
 #   motion:
 #     mask: 
  #      - 380,689,918,682,918,639,383,636
#        - 0,283,399,241,393,0,0,0
#        - 639,225,1014,182,1280,160,1280,0,686,0
#        - 681,234,683,0,359,0,379,218
#        - 312,366,500,359,551,259,686,139,553,146,400,156,316,158
#        - 1280,139,835,261,1280,720
 #       - 567,269,527,211,409,206,360,244,281,343,558,343
    motion:
      mask:
          - 380,689,918,682,918,639,383,636
          - 567,269,527,211,409,206,360,244,281,343,558,343
 #         - 121,492,189,416,155,290,55,308
 #         - 247,261,284,364,197,318
    objects:
              # Optional: list of objects to track from labelmap.txt (default: shown below)
      track:
        - person
        - car
              # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
              # Checks based on the bottom center of the bounding box of the object.
              # NOTE: This mask is COMBINED with the object type specific mask below
              # Optional: filters to reduce false positives for specific object types
      filters:
        person:
                  # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
                  # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 200000
                # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6     
                  # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
                  # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
                  # Checks based on the bottom center of the bounding box of the object
        #  mask: 0,0,1000,0,1000,200,0,200
        car:
        # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 10000
        # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 500000
            # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.6
        # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
        # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
        # Checks based on the bottom center of the bounding box of the object
        #  mask:  0,0,1000,0,1000,200,0,200
        #mask:  367,111,365,249,307,326,37,316,40,134        
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 2
timestamp_style:
          # Optional: Position of the timestamp (default: shown below)
          #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
          # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
          #           Additional Examples:
          #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
#    color:
    #        # All Required when color is specified (default: shown below)
#      red: 255
#      green: 255
#      blue: 255
    #      # Optional: Line thickness of font (default: shown below)
#      thickness: 2
          # Optional: Effect of lettering (default: shown below)
          #           None (No effect), none is not valid
          #           "solid" (solid background in inverse color of font)
          #           "shadow" (shadow for font)
#    effect: "solid"       
#  Front-Door:
#    rtmp:
#      enabled: false
#    #detect:
#    #  enabled: True
#    ffmpeg:
#      global_args: -y -hide_banner -loglevel info
#      hwaccel_args:
#        - -hwaccel
#        - vaapi
#        - -hwaccel_device
#        - /dev/dri/renderD128
#        - -hwaccel_output_format
#        - yuv420p
##        - -c:v
##        - h264_v4l2m2m
#      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport udp -stimeout 5000000 -use_wallclock_as_timestamps 1
#      output_args:
#        detect: -f rawvideo -pix_fmt yuv420p
#        record: -map 0:v -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -b:v 4M -r 25
#        rtmp: -c copy -f flv
#      inputs:
#        - path: rtsp://<>:<>@<>:554/onvif1
#          roles:
#            - detect
#            - clips
#    detect:  
#        # Optional: width of the frame for the input with the detect role (default: shown below)
#      width: 1280
#      # Optional: height of the frame for the input with the detect role (default: shown below)
#      height: 720
#      # Optional: desired fps for your camera for the input with the detect role (default: shown below)
#      # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
##      fps: 15
#      # Optional: enables detection for the camera (default: True)
#      # This value can be set via MQTT and will be updated in startup based on retained value
#      enabled: True
#      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
#      #max_disappeared: 25
##  zones:
##    zone_entire_main_drive:
##      coordinates: 845,275,582,341,330,320,87,537,0,720,1280,720
##    zone_main_drive_full_height:
##      coordinates: 0,720,1280,720,1280,131,0,140
##  motion:
##    mask:
##     - 385,690,915,680,915,638,385,640
#    objects: 
#      - person
#      #- car
#    record:
#      enabled: True
#      # Optional: Number of days to retain recordings regardless of events (default: shown below)
#      # NOTE: This should be set to 0 and retention should be defined in events section below
#      #       if you only want to retain recordings of events.
#      retain_days: 0
#      # Optional: Event recording settings
#      events:
#        # Optional: Maximum length of time to retain video during long events. (default: shown below)
#        # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
#        #       will be the last x seconds of the event unless retain_days under record is > 0.
#        max_seconds: 300
#        # Optional: Number of seconds before the event to include (default: shown below)
#        pre_capture: 5
#        # Optional: Number of seconds after the event to include (default: shown below)
#        post_capture: 5
#        # Optional: Objects to save recordings for. (default: all tracked objects)
#        objects:
#          - person
#        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
##        required_zones: [zone_entire_main_drive]
#        # Optional: Retention settings for recordings of events
#        retain:
#        # Required: Default retention days (default: shown below)
#          default: 10
#        # Optional: Per object retention days
#          objects:
#            person: 10
#    objects:
#            # Optional: list of objects to track from labelmap.txt (default: shown below)
#      track:
#        - person
#       # - car
#            # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
#            # Checks based on the bottom center of the bounding box of the object.
#            # NOTE: This mask is COMBINED with the object type specific mask below
#      #mask: 0,0,1000,0,1000,200,0,200
#            # Optional: filters to reduce false positives for specific object types
#      filters:
#        person:
#                # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#          min_area: 5000
#                # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#          max_area: 200000
#              # Optional: minimum score for the object to initiate tracking (default: shown below)
#          min_score: 0.5
#                # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
#          threshold: 0.7
#                # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
#                # Checks based on the bottom center of the bounding box of the object
#       #   mask: 0,0,1000,0,1000,200,0,200
#          mask: 
#            - 0,45,495,46,492,0,0,0
#        car:
#            # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#        #  min_area: 5000
#          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#        #  max_area: 100000
##         min_score: 0.5
#          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
#         threshold: 0.7
#           # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
#            # Checks based on the bottom center of the bounding box of the object
#        #  mask:  0,0,1000,0,1000,200,0,200
#        motion:
#          mask:
#            - 0,45,495,46,492,0,0,0
#    snapshots:
#      enabled: True
    # timestamp: True
#      bounding_box: True
#      retain:
#        default: 2
      # clips:
      #   enabled: True
      #  retain:
      #    default: 2


#environment_vars: 
#  LIBVA_DRIVER_NAME: i965
#go2rtc:
#  streams:
#    Drive:
#      - "rtsp://viewer:<>@<>:554#input=rtsp/udp"
#      - "ffmpeg:Drive#video=h264"
#  webrtc:
#    candidates:
#      - 192.168.99.11:8555
#      - stun:8555
#    log:
#      level: info  # default level
#      api: info
#      exec: info
#      ngrok: info
#      rtsp: debug
#      streams: debug
#      webrtc: debug
```

### Relevant log output

```shell
2023-03-28 21:22:57.620356677  [INFO] Starting Frigate...
2023-03-28 21:23:00.084612033  [2023-03-28 22:23:00] frigate.app                    INFO    : Starting Frigate (0.12.0-7d589bd)
2023-03-28 21:23:00.123247397  [2023-03-28 22:23:00] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-03-28 21:23:00.125489055  [2023-03-28 22:23:00] peewee_migrate                 INFO    : Starting migrations
2023-03-28 21:23:00.136800033  [2023-03-28 22:23:00] peewee_migrate                 INFO    : There is nothing to migrate
2023-03-28 21:23:00.153389098  [2023-03-28 22:23:00] detector.coral                 INFO    : Starting detection process: 299
2023-03-28 21:23:00.155932564  [2023-03-28 22:23:00] frigate.app                    INFO    : Output process started: 301
2023-03-28 21:23:00.162559759  [2023-03-28 22:23:00] frigate.app                    INFO    : Camera processor started for Main-Drive: 305
2023-03-28 21:23:00.162565752  [2023-03-28 22:23:00] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-03-28 21:23:04.421666490  [2023-03-28 22:23:00] frigate.app                    INFO    : Capture process started for Main-Drive: 306
2023-03-28 21:23:04.440081488  [2023-03-28 22:23:04] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
fprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.265 / HEVC (High Efficiency Video Coding)
Resolution: 1280x720
FPS: 15/1

Audio:

Codec: PCM A-law / G.711 A-law
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

digoo lantern

### Any other information that may be helpful

![mime-type](https://user-images.githubusercontent.com/49276185/228369638-81827ce0-0e74-430b-8bb7-e03ae459f2b0.png)
![frigate-recordings](https://user-images.githubusercontent.com/49276185/228369642-f0db43bc-c6be-4b8a-869f-151bdfa3f4a6.png)
