### ISSUE TITLE
[Support]: "Stream not found" MSE & WebRTC

### ISSUE THREAD

**Issue by e3ndr** [blakeblackshear/frigate#5875]
### Describe the problem you are having

I am unable to watch a feed with MSE nor WebRTC. JSMPEG works fine.

### Version

0.12.0-7D589BD

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.13
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  password: PiperCub12

database:
  path: /media/frigate/frigate.db

detectors:
  cpu1:
    type: cpu
    num_threads: 2

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 12 # Lower is higher quality, higher is worse.
  mode: objects

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: []
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -c:a aac -f flv

detect:
  width: 1920
  height: 1080
  fps: 30
  enabled: True
  max_disappeared: 150
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

motion:
  threshold: 25
  contour_area: 30 # Lower is higher sensitivity.
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mqtt_off_delay: 30

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5 # Seconds
    post_capture: 5 # Seconds
    # objects:
    #   - person
    required_zones: []
    retain:
      default: 10 # days
      mode: motion
      objects:
        person: 15 # days

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: true
  crop: False
  # height: 175 # Defaults to original size
  required_zones: []
  retain:
    default: 10 # days
    objects:
      person: 15 # days

live:
  height: 720
  quality: 12 # Lower is higher quality, higher is worse.

timestamp_style:
  position: "tl" # "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  format: "%m/%d/%Y %H:%M:%S" # Python datetime formatter
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: "shadow"

cameras:
  backgate:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.13:8654/####################
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720

go2rtc:
  streams:
    backgate:
      - "ffmpeg:backgate#video=h264#audio=opus"
  webrtc:
    candidates:
      - 10.0.0.18:8555
      - stun:8555
```

### Relevant log output

```shell
23-03-29 15:28:37.030790526  [2023-03-29 15:28:37] frigate.video                  ERROR   : backgate: Unable to read frames from ffmpeg process.
2023-03-29 15:28:37.031055207  [2023-03-29 15:28:37] frigate.video                  ERROR   : backgate: ffmpeg process is not running. exiting capture thread...
2023-03-29 15:28:41.914764788  [2023-03-29 15:28:41] watchdog.backgate              ERROR   : Ffmpeg process crashed unexpectedly for backgate.
2023-03-29 15:28:41.914994822  [2023-03-29 15:28:41] watchdog.backgate              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-03-29 15:28:41.915263317  [2023-03-29 15:28:41] ffmpeg.backgate.detect         ERROR   : rtsp://10.0.0.13:8654/9884e3287a72_live: Invalid data found when processing input
```

### FFprobe output from your camera

```shell
[rtsp @ 0000028bb7255f00] method SETUP failed: 461 Unsupported transport
Input #0, rtsp, from 'rtsp://10.0.0.13:8654/####################':
  Metadata:
    title           : go2rtc/1.2.0
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 15 fps, 15 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp
  Stream #0:2: Audio: opus, 48000 Hz, stereo, fltp
```

### Frigate stats

```json
{"backgate":{"camera_fps":30.0,"capture_pid":433,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":638,"pid":431,"process_fps":30.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"4.0","mem":"0.8"},"116":{"cpu":"0.0","mem":"0.1"},"133":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"159":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"187":{"cpu":"0.0","mem":"0.0"},"223":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"419":{"cpu":"0.0","mem":"0.5"},"42":{"cpu":"0.0","mem":"0.0"},"425":{"cpu":"0.7","mem":"0.1"},"426":{"cpu":"0.0","mem":"0.6"},"428":{"cpu":"2.3","mem":"0.5"},"431":{"cpu":"5.6","mem":"0.6"},"432":{"cpu":"0.0","mem":"0.3"},"433":{"cpu":"15.0","mem":"0.6"},"437":{"cpu":"0.0","mem":"0.1"},"638":{"cpu":"28.9","mem":"0.5"},"770":{"cpu":"0.0","mem":"0.0"},"780":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.1"},"MiB":{"cpu":"5284.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"2.89,"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":111.36,"pid":426}},"service":{"last_updated":1680104054,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":63.6,"mount_type":"tmpfs","total":67.1,"used":3.5},"/media/frigate/clips":{"free":925644.8,"mount_type":"zfs","total":927139.9,"used":1495.1},"/media/frigate/recordings":{"free":925644.8,"mount_type":"zfs","total":927139.9,"used":1495.1},"/tmp/cache":{"free":925644.8,"mount_type":"overlay","total":938441.0,"used":12796.3}},"temperatures":{},"uptime":533,"version":"0.12.0-7d589bd"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Ring 1st Gen Doorbell

### Any other information that may be helpful

While I am using a Ring camera as a continous camera feed (which is unsupported by virtually everyone, I know), this issue appears to be unique to MSE and WebRTC as JSMPEG works fine.

Also, I'm unsure if the log output I've provided is related to this issue at all. Ring's video transport is pretty unstable even at the best of times so that could be the cause of those errors.

**Comment by e3ndr** [comment]
Here's some screenshots of the errors in the network inspector: 
![chrome_pJiFAEaCf1](https://user-images.githubusercontent.com/33337309/228602101-9df2332e-58eb-4bb1-b766-80d54d119fe2.png)
![chrome_hrDP7Uih3U](https://user-images.githubusercontent.com/33337309/228602113-5109deca-1d54-4d89-ac72-ca21766f67e5.png)

**Comment by NickM-27** [comment]
your go2rtc configuration is incorrect, you are using ffmpeg but you never created the actual stream for frigate to reference.

```
go2rtc:
  streams:
    backgate:
      - "ffmpeg:backgate#video=h264#audio=opus"
```
