### ISSUE TITLE
[Config Support]: help to configure go2rtc

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#5881]
### Describe the problem you are having

I have read the document but still cannot fully get it to work.  I trimmed down my config to include only one camera.  Please check the attached config.yml file.  For audio, I tried both "aac" and "opus", but I cannot get audio from mse, and I cannot get webrtc to work at all (spin wheel forever).  Also, I do not quite follow how I can use my go2rtc setting to replace my current camera setting (as present in the attached config).

Looks using go2rtc is to reduce connections to cameras.  But it will likely increase CPU usage?  How does it use hardware acceleration?  If it simply copies the stream (which I guess is CPU's job), looks hardware acceleration is not that useful here?

I have Frigate integrated with Home Assistant (HA).  If I understand correctly, it uses rtmp to send over the stream to HA.  I get rtmp is deprecated.  If go2rtc incurs heavily on CPU and bring down the host, does it mean that there is no way to integrate with HA?

Thanks for your help.

### Version

0.12.0-7D589BD

### Frigate config file

```yaml
mqtt:
  host: 192.168.xxx.xxx

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: True 
  mode: continuous

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    # Optional: output args for detect streams (default: shown below)
    # detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

go2rtc:
  streams:
    camera1:
      - rtsp://xxx:xxx@192.168.222.333/live
      - ffmpeg:front_door#audio=opus
    webrtc:
      candidates:
        - 192.168.222.333:8555
        - stun:8555

detect:
  enabled: True

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.222.333/live
          roles:
            - detect
            - record
            - rtmp
```

### Relevant log output

```shell
# This is all I get from web UI
2023-03-30 21:01:40.416955196  [INFO] Starting Frigate...
2023-03-30 21:01:43.797243023  [2023-03-30 17:01:43] frigate.app                    INFO    : Starting Frigate (0.12.0-7d589bd)
2023-03-30 21:01:43.851425556  [2023-03-30 17:01:43] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-03-30 21:01:43.875834723  [2023-03-30 17:01:43] peewee_migrate                 INFO    : Starting migrations
2023-03-30 21:01:43.892705614  [2023-03-30 17:01:43] peewee_migrate                 INFO    : There is nothing to migrate
2023-03-30 21:01:43.985981487  [2023-03-30 17:01:43] frigate.app                    INFO    : Output process started: 290
2023-03-30 21:01:44.004325102  [2023-03-30 17:01:44] frigate.app                    INFO    : Camera processor started for camera1: 293
2023-03-30 21:01:44.008985253  [2023-03-30 17:01:43] detector.ov                    INFO    : Starting detection process: 289
2023-03-30 21:01:44.016578209  [2023-03-30 17:01:44] frigate.app                    INFO    : Capture process started for camera1: 294
2023-03-30 21:01:45.056472276  [2023-03-30 17:01:45] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-03-30 21:01:45.056760839  [2023-03-30 17:01:45] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-03-30 21:01:45.056995903  [2023-03-30 17:01:45] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-03-30 21:01:47.374214077  [2023-03-30 17:01:47] frigate.util                   ERROR   : Unable to poll intel GPU stats: Failed to detect engines! (No such file or directory)
2023-03-30 21:01:47.374221290  (Kernel 4.16 or newer is required for i915 PMU support.)
2023-03-30 21:01:47.374224258  
2023-03-30 21:02:54.494228002  [2023-03-30 17:02:54] frigate.util                   ERROR   : Unable to poll intel GPU stats: Failed to detect engines! (No such file or directory)
2023-03-30 21:02:54.494235959  (Kernel 4.16 or newer is required for i915 PMU support.)
2023-03-30 21:02:54.494237651
```

### Frigate stats

```json
{
  "camera1": {
    "camera_fps": 5,
    "capture_pid": 294,
    "detection_enabled": 1,
    "detection_fps": 0,
    "ffmpeg_pid": 299,
    "pid": 293,
    "process_fps": 5,
    "skipped_fps": 0
  },
  "cpu_usages": {
    "1": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "15": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "17": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "24": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "25": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "26": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "27": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "28": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "29": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "30": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "31": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "32": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "39": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "47": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "79": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "81": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "82": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "89": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "104": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "111": {
      "cpu": "1.3",
      "mem": "1.0"
    },
    "117": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "129": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "130": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "131": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "132": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "282": {
      "cpu": "0.0",
      "mem": "0.5"
    },
    "288": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "289": {
      "cpu": "0.0",
      "mem": "2.7"
    },
    "290": {
      "cpu": "0.3",
      "mem": "0.6"
    },
    "293": {
      "cpu": "1.0",
      "mem": "0.6"
    },
    "294": {
      "cpu": "2.0",
      "mem": "0.5"
    },
    "299": {
      "cpu": "17.3",
      "mem": "0.3"
    },
    "300": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "301": {
      "cpu": "0.0",
      "mem": "0.1"
    },
    "1007": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1016": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "1019": {
      "cpu": "0.0",
      "mem": "0.0"
    },
    "%Cpu(s):": {
      "cpu": "id,",
      "mem": "1.4"
    },
    "MiB": {
      "cpu": "8258.5",
      "mem": "avail"
    },
    "PID": {
      "cpu": "%CPU",
      "mem": "%MEM"
    },
    "Tasks:": {
      "cpu": "stopped,",
      "mem": "0"
    },
    "top": {
      "cpu": "users,",
      "mem": "load"
    }
  },
  "detection_fps": 0,
  "detectors": {
    "ov": {
      "detection_start": 0,
      "inference_speed": 33.33,
      "pid": 289
    }
  },
  "gpu_usages": {
    "error-gpu": {
      "gpu": -1,
      "mem": -1
    }
  },
  "service": {
    "last_updated": 1680211385,
    "latest_version": "0.11.1",
    "storage": {
      "/dev/shm": {
        "free": 266.4,
        "mount_type": "tmpfs",
        "total": 268.4,
        "used": 2
      },
      "/media/frigate/clips": {
        "free": 2083647.4,
        "mount_type": "ext4",
        "total": 3838581.8,
        "used": 1754380.7
      },
      "/media/frigate/recordings": {
        "free": 2083647.4,
        "mount_type": "ext4",
        "total": 3838581.8,
        "used": 1754380.7
      },
      "/tmp/cache": {
        "free": 8377510,
        "mount_type": "overlay",
        "total": 9664376.5,
        "used": 1286312.8
      }
    },
    "temperatures": {},
    "uptime": 1281,
    "version": "0.12.0-7d589bd"
  }
}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Other

### Any other information that may be helpful

Wyze cam v2 with rtsp firmware.

**Comment by NickM-27** [comment]
I see a few things here that could be improved.

1. You should be using ffmpeg presets, these are not the same as the args you are running and will reduce CPU usage

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
```

2. your go2rtc config is not correct, you have `frontdoor` but no camera in the go2rtc config named frontdoor

it should be 

```yaml
go2rtc:
  streams:
    camera1:
      - rtsp://xxx:xxx@192.168.222.333/live
      - ffmpeg:camera1#audio=opus # <- needs to match the name of the camera for this config
    webrtc:
      candidates:
        - 192.168.222.333:8555
        - stun:8555
```

> For audio, I tried both "aac" and "opus", but I cannot get audio from mse, and I cannot get webrtc to work at all (spin wheel forever).

please provide an ffprobe (can be retrieved from system page) with your cameras settings. 

> Also, I do not quite follow how I can use my go2rtc setting to replace my current camera setting (as present in the attached config).

Just follow the docs https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream#reduce-connections-to-camera

> Looks using go2rtc is to reduce connections to cameras. But it will likely increase CPU usage? How does it use hardware acceleration? If it simply copies the stream (which I guess is CPU's job), looks hardware acceleration is not that useful here?

go2rtc is used to provide the mse / webrtc live views, reduce connections to the camera, and can be utilized for many other things as well. I have not seen CPU usage that high, but hardware acceleration is only used if you are transocding your stream (like h.265 -> h.264).

> I have Frigate integrated with Home Assistant (HA). If I understand correctly, it uses rtmp to send over the stream to HA. I get rtmp is deprecated. If go2rtc incurs heavily on CPU and bring down the host, does it mean that there is no way to integrate with HA?

There were some reports in the early betas of issues with go2rtc performance but at this point I have not heard of it. For now RTMP can be used but it is deprecated and will be removed in a future version, it also uses some CPU as well.

**Comment by my-umd** [comment]
Thanks @NickM-27.  Good catch for the mismatch.  Apparently that was left unchanged when I made the trim down config.  However, I still have no audio and webrtc remains the same after matching up camera name and using ffmpeg presets as you suggested.  Here is the ffprobe output:
```
[
  {
    "return_code": 0,
    "stderr": "",
    "stdout": {
      "programs": [],
      "streams": [
        {
          "avg_frame_rate": "15/1",
          "codec_long_name": "H.264/AVC/MPEG-4AVC/MPEG-4part10",
          "height": 1080,
          "width": 1920
        },
        {
          "avg_frame_rate": "0/0",
          "bit_rate": "64000",
          "codec_long_name": "PCMA-law/G.711A-law"
        }
      ]
    }
  }
]
```
I'll read again the [doc](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream#reduce-connections-to-camera) again once I get go2rtc straight out.  And thanks for the info. about CPU usage regarding go2rtc.

**Comment by NickM-27** [comment]
MSE / recordings won't have audio since those require aac. Since your stream provides PCMA audio you should be transcoding to aac in go2rtc

```yaml
go2rtc:
  streams:
    camera1:
      - rtsp://xxx:xxx@192.168.222.333/live
      - ffmpeg:camera1#audio=aac
    webrtc:
      candidates:
        - 192.168.222.333:8555
        - stun:8555
```
