### ISSUE TITLE
[Support]: api/config - 502 Bad Gateway 

### ISSUE THREAD

**Issue by bevanm8** [blakeblackshear/frigate#5884]
### Describe the problem you are having

Installed Frigate 0.12.0-rc1 using Docker Compose on my Synology NAS, and now the initial frigate home page will not fully load. I pressed the F12 button to see if there are any issues, it seems to be failing to hit the api (See screenshots and logs). My first thought was that it could be the custom port I set (5212 instead of 5000), unfortunately I can't test port 5000 as that is what the Synology uses as its main port.

The main reason I upgraded was so that I could stop using rtmp, so I did go through and set my config to use the go2rtc restream option. It's quite possible I've stuffed something up in the config.

I'm about to try a basic config to see if that helps.

If there is any more information that I can provide that would help, just let me know.

### Version

0.12.0-rc1

### Frigate config file

```yaml
yaml-language-server: $schema=http://172.16.13.70:5212/api/config/schema.json

mqtt:
  host: 172.16.13.70
  port: 5207
  topic_prefix: frigate
  client_id: frigate
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

logger:
  default: info
  logs:
    frigate.event: debug

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects
#  restream: "rtsp://localhost:8554/birdseye"

live:
  height: 720
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
    
record:
  enabled: True
#  events:
#    max_seconds: 300
#    pre_capture: 5
#    post_capture: 5
#    objects:
#      - person
#      - car
#      - dog
#    retain:
#      default: 30

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 120
    objects:
      person: 120

#rtmp:
 # enabled: True

 go2rtc:
  rstp:
    username: "${FRIGATE_RTSP_USERNAME}"
    password: "${FRIGATE_RTSP_PASSWORD}"
  streams:
    patio_cam: 
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.60:554/Streaming/Channels/101 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:patio_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    patio_cam_sub:
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.60:554/Streaming/Channels/103 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:patio_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    pool_cam: 
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.61:554/Streaming/Channels/101 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:pool_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    pool_cam_sub:
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.61:554/Streaming/Channels/103 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:pool_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    frontright_cam: 
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.62:554/Streaming/Channels/101 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:frontright_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    frontright_cam_sub:
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.62:554/Streaming/Channels/103 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:frontright_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    frontleft_cam: 
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.63:554/Streaming/Channels/101 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:frontleft_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    frontleft_cam_sub:
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.63:554/Streaming/Channels/103 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:frontleft_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    frontdoor_cam: 
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.64:554/Streaming/Channels/101 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:frontdoor_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    frontdoor_cam_sub:
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.64:554/Streaming/Channels/103 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:frontdoor_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    side_cam: 
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.65:554/Streaming/Channels/101 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:side_cam#audio=opus" # <- copy of the stream which transcodes audio to opus
    side_cam_sub:
      - rtsp://{FRIGATE_CAMERA_RTSP_CREDENTIALS}@172.16.13.65:554/Streaming/Channels/103 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - "ffmpeg:side_cam_sub#audio=opus" # <- copy of the stream which transcodes audio to opus

# Required
cameras:
  Patio:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/patio_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patio_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
          - detect
    live:
      stream_name: patio_cam_sub
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
    motion:
      mask:    
        - 54,66,433,65,427,35,51,42
    objects:
      filters:
        person:
          threshold: 0.83
          min_score: 0.5
      track:
        - person 
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  Pool:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/pool_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pool_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
          - detect
    live:
      stream_name: poolo_cam_sub
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
    motion:
      mask:    
        - 45,74,434,74,435,38,55,36
    zones:  
      Pool_Area:
        coordinates: 375,720,1280,720,1280,328,1280,44,797,46,790,119,357,154
    objects:
      filters:
        person:
          threshold: 0.83
          min_score: 0.5
        dog:
          mask:
            - 0,720,388,720,356,365,366,161,580,137,785,133,788,49,1001,103,1280,232,1280,0,0,0
      track:
        - person
        - dog
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  Front_Right:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontright_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontright_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
          - detect
    live:
      stream_name: frontright_cam_sub
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
    motion:
      mask:
        - 437,72,432,35,47,35,55,72
        - 463,720,1280,720,1280,453,423,628,420,720
        - 740,392,923,363,879,143,734,90,669,157,520,180,460,177,422,208,344,160,281,365,318,523,530,391
    zones:  
      Nbr_Driveway:
        coordinates: 0,720,284,720,316,491,399,186,233,207,0,251
      Driveway:
        coordinates: 1210,269,1213,237,1280,245,1216,201,1039,185
    objects:
      filters:
        person:
          threshold: 0.7
          min_score: 0.5  
          mask:
            - 219,206,446,177,592,168,835,164,1016,177,1174,195,1280,207,1280,0,0,0,0,250
        bicycle:
          threshold: 0.7
          min_score: 0.5  
          mask:
            - 240,207,418,190,602,175,835,164,1016,177,1174,195,1280,207,1280,0,0,0,0,250
        car:
          threshold: 0.7
          min_score: 0.5  
          mask:
            - 366,223,290,720,1280,720,1280,376,949,202,1280,221,1280,0,0,0,0,280,173,239
        motorcycle:
          threshold: 0.7
          min_score: 0.5 
          mask:
            - 366,223,290,720,1280,720,1280,376,949,202,1280,221,1280,0,0,0,0,280,173,239
        dog:
          threshold: 0.7
          min_score: 0.5 
          mask:
            - 413,164,786,144,1072,157,1280,191,1280,154,1118,99,684,53,306,84,0,140,0,220
      track:
        - person
        - dog
        - car
        - motorcycle
        - bicycle
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  Front_Left:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontleft_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontleft_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
          - detect
    live:
      stream_name: frontleft_cam_sub
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
    motion:
      mask:    
        - 0,0,1280,0,1280,162,926,41,437,21,428,77,0,70
        - 1157,185,1280,264,1280,720,1228,620,1082,417,997,264,1020,201,1087,219
    zones:  
      Driveway:
        coordinates: 551,194,791,223,731,240,718,279,809,354,766,720,0,720,0,328,145,259,231,241,331,215,368,183
    objects:
      filters:
        car:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 688,212,812,227,991,259,1049,371,1193,599,1280,720,1280,0,0,0,0,191,249,180
        motorcycle:
          threshold: 0.7
          min_score: 0.5
          mask:
           - 688,212,812,227,991,259,1049,371,1193,599,1280,720,1280,0,0,0,0,191,249,180
        dog:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 688,212,812,227,991,259,1049,371,1193,599,1280,720,1280,236,829,143,557,117,244,114,0,145,0,191,316,179
        person:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 688,212,812,227,991,259,1049,371,1193,599,1280,720,1280,0,0,0,0,191,249,180
        bicycle:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 688,212,812,227,991,259,1049,371,1193,599,1280,720,1280,0,0,0,0,191,249,180
      track:
        - person
        - car
        - motorcycle
        - dog
        - bicycle
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  Front_Door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
          - detect
    live:
      stream_name: frontdoor_cam_sub
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    motion:
      mask:    
        - 361,77,640,119,640,0,0,0,0,71
    zones:  
      Driveway:
        coordinates: 255,480,68,321,74,252,23,221,110,185,192,160,261,174,327,170,544,202,540,355,521,480
    objects:
      filters:
        person:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 0,0,640,0,640,47,520,80,518,128,406,111,327,97,134,160,0,220
        bicycle:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 0,0,640,0,640,150,495,127,406,111,312,99,166,147,0,213
        car:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 0,0,640,0,548,76,541,196,395,161,257,140,188,158,90,197,0,244
        motorcycle:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 0,0,640,0,548,76,541,196,395,161,257,140,188,158,90,197,0,244
        dog:
          threshold: 0.7
          min_score: 0.5
          mask:
            - 0,209,0,0,640,0,640,87,352,94,150,149,0,212
      track:
        - person
        - car
        - dog
        - motorcycle
        - bicycle
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
  Side:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/side_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
          - detect
    live:
      stream_name: side_cam_sub
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5
    record:
      enabled: true
    motion:
      mask:    
        - 0,48,205,49,205,0,0,0
        - 517,480,181,480,158,411,352,345
    objects:
      filters:
        person:
          threshold: 0.83
          min_score: 0.5
      track:
        - person
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True
      height: 500
```

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:5212/api/config:1 
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:5212/api/config:1 
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
index-db0d4912.js:16 
GET http://172.16.13.70:5212/api/config 502 (Bad Gateway)
(anonymous) @ index-db0d4912.js:16
xhr @ index-db0d4912.js:16
Lr @ index-db0d4912.js:16
request @ index-db0d4912.js:16
Ct.<computed> @ index-db0d4912.js:16
(anonymous) @ index-db0d4912.js:14
fetcher @ index-db0d4912.js:16
(anonymous) @ index-db0d4912.js:14
f @ index-db0d4912.js:14
(anonymous) @ index-db0d4912.js:14
(anonymous) @ index-db0d4912.js:14
po @ index-db0d4912.js:14
(anonymous) @ index-db0d4912.js:14
index-db0d4912.js:16
```

### FFprobe output from your camera

```shell
libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, rtsp, from 'rtsp://{MYCREDS}@172.16.13.60:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.080000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 12 fps, 12.50 tbr, 90k tbn
```

### Frigate stats

```json
Page throws 502 Gateway error (Output from network below)

Request URL: http://172.16.13.70:5212/api/stats
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 172.16.13.70:5212
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 559
Content-Type: text/html
Date: Fri, 31 Mar 2023 04:33:46 GMT
Server: nginx/1.22.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Host: 172.16.13.70:5212
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Annke I91BF

### Any other information that may be helpful

The page just sits there continuously trying to load, and the Gateway errors continue.

![image](https://user-images.githubusercontent.com/1908517/229024079-92675d89-665e-4754-8f55-6db6ce34be0b.png)

![image](https://user-images.githubusercontent.com/1908517/229024148-09fd8e16-a36c-43c9-b177-62ce7a576e47.png)

The Frigate part of my Docker Compose file:

  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-rc1
    privileged: true
    hostname: "frigate"
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    environment:
      - PUID=1040
      - PGID=65536
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/lab/frigate:cached
      - /volume1/docker/frigate/config/config.yml:/config/config.yml
      - /volume1/docker/frigate/media:/media/frigate
      - /volume1/docker/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5212:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    networks:
      - frigate_network
    env_file:
      - "./secrets.env"
