### ISSUE TITLE
[Config Support]: Audio in Live Streams but not in records with the 0.12-rc2

### ISSUE THREAD

**Issue by setterlee** [blakeblackshear/frigate#5897]
### Describe the problem you are having

I have audio in live but not in records, I Already tested all the ouputs presets.

### Version

0.12.0-BC16AD1

### Frigate config file

```yaml
mqtt:
    host: 127.0.0.1
    user: xxxxx
    password: xxxxxx
  detectors:
    coral:
      type: edgetpu
      device: usb
  cameras:
    camera_1:
      mqtt:
        timestamp: False
        bounding_box: False
        crop: True
        quality: 100
        height: 500
      ffmpeg:
        output_args:
          record: preset-record-generic-audio-copy
        inputs:
          - path: rtsp://127.0.0.1:8554/camera_1
            roles:
              - detect
              - record
      objects:
        track:
          - person
          - car
          - cat
      detect:
        width: 2560
        height: 1440
        stationary:
          interval: 0
          threshold: 50
          max_frames:
            default: 3000
            objects:
              car: 100
      zones:
        calle:
          coordinates: 0,403,634,316,1344,285,1911,320,2379,385,2401,292,2560,368,2560,0,0,0
          objects:
            - person
            - car
        estacionamiento_delantero:
          coordinates: 0,1440,1989,1440,1201,484,806,515,390,565,0,609
          objects:
            - person
            - cat
        frontis_izquierdo:
          coordinates: 1406,460,1712,457,2094,455,2560,745,2457,955,2560,1042,2560,1440,1966,1440,1121,480
          objects:
            - person
            - cat
        frontis_derecho:
          coordinates: 2350,457,2497,536,2451,683,2076,453
          objects:
            - person
            - cat
        muro_perimetral_delantero_derecho:
          coordinates: 2411,288,2560,366,2489,547,2350,460
          objects:
            - person
            - cat
      record:
        events:
          required_zones:
            - calle
            - estacionamiento_delantero
            - frontis_izquierdo
            - frontis_derecho
            - muro_perimetral_delantero_derecho
          retain:
            objects:
              car: 5
      snapshots:
        height: 500
        crop: False
        required_zones:
          - calle
          - estacionamiento_delantero
          - frontis_izquierdo
          - frontis_derecho
          - muro_perimetral_delantero_derecho
  record:
    enabled: True
    retain:
      days: 14
      mode: motion
    events:
      retain:
        default: 14
        mode: active_objects
  snapshots:
    enabled: True
    retain:
      default: 14
  birdseye:
    enabled: True
    mode: motion
    width: 1280
    height: 720
  logger:
    # Optional: default log level (default: shown below)
    default: info
    # Optional: module by module log level configuration
    logs:
      frigate.mqtt: error
  go2rtc:
    streams:
      camera_1:
        - rtsp://xxxxx:xxxx@192.168.xxx.xxx:554/stream1
```

### Relevant log output

```shell
No errors on logs
```

### Frigate stats

```json
{
    "camera_1": {
        "camera_fps": 5.1,
        "capture_pid": 306,
        "detection_enabled": 1,
        "detection_fps": 7.8,
        "ffmpeg_pid": 311,
        "pid": 296,
        "process_fps": 5.1,
        "skipped_fps": 0.0
    },
    "cpu_usages": {
        "%Cpu(s):": {
            "cpu": "id,",
            "mem": "0.2"
        },
        "1": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "1007": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "1014": {
            "cpu": "0.3",
            "mem": "0.0"
        },
        "104": {
            "cpu": "41.5",
            "mem": "3.5"
        },
        "109": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "116": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "134": {
            "cpu": "0.3",
            "mem": "0.1"
        },
        "135": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "136": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "138": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "15": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "16": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "24": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "25": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "26": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "27": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "28": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "282": {
            "cpu": "0.0",
            "mem": "0.7"
        },
        "288": {
            "cpu": "0.7",
            "mem": "0.1"
        },
        "289": {
            "cpu": "4.7",
            "mem": "1.3"
        },
        "29": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "291": {
            "cpu": "4.0",
            "mem": "1.3"
        },
        "296": {
            "cpu": "1.3",
            "mem": "1.5"
        },
        "298": {
            "cpu": "1.0",
            "mem": "1.3"
        },
        "299": {
            "cpu": "0.0",
            "mem": "0.4"
        },
        "30": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "300": {
            "cpu": "7.6",
            "mem": "1.4"
        },
        "301": {
            "cpu": "1.3",
            "mem": "1.3"
        },
        "302": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "303": {
            "cpu": "1.7",
            "mem": "1.3"
        },
        "304": {
            "cpu": "0.7",
            "mem": "1.4"
        },
        "305": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "306": {
            "cpu": "6.6",
            "mem": "1.3"
        },
        "309": {
            "cpu": "7.0",
            "mem": "1.3"
        },
        "31": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "310": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "311": {
            "cpu": "21.9",
            "mem": "0.7"
        },
        "314": {
            "cpu": "6.6",
            "mem": "1.3"
        },
        "315": {
            "cpu": "22.6",
            "mem": "0.7"
        },
        "317": {
            "cpu": "6.3",
            "mem": "1.3"
        },
        "318": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "32": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "322": {
            "cpu": "7.0",
            "mem": "1.3"
        },
        "327": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "328": {
            "cpu": "2.0",
            "mem": "1.2"
        },
        "329": {
            "cpu": "19.3",
            "mem": "0.7"
        },
        "330": {
            "cpu": "18.3",
            "mem": "0.6"
        },
        "332": {
            "cpu": "20.9",
            "mem": "0.7"
        },
        "338": {
            "cpu": "0.0",
            "mem": "0.1"
        },
        "339": {
            "cpu": "17.3",
            "mem": "0.4"
        },
        "41": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "42": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "80": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "81": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "82": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "89": {
            "cpu": "2.0",
            "mem": "0.2"
        },
        "988": {
            "cpu": "0.0",
            "mem": "0.0"
        },
        "MiB": {
            "cpu": "5124.2",
            "mem": "avail"
        },
        "PID": {
            "cpu": "%CPU",
            "mem": "%MEM"
        },
        "Tasks:": {
            "cpu": "stopped,",
            "mem": "0"
        },
        "top": {
            "cpu": "users,",
            "mem": "load"
        }
    },
    "detection_fps": 25.4,
    "detectors": {
        "coral": {
            "detection_start": 1680463413.450758,
            "inference_speed": 15.21,
            "pid": 289
        }
    },
    "service": {
        "last_updated": 1680463416,
        "latest_version": "0.11.1",
        "storage": {
            "/dev/shm": {
                "free": 3422.1,
                "mount_type": "tmpfs",
                "total": 3454.0,
                "used": 31.9
            },
            "/media/frigate/clips": {
                "free": 144246.2,
                "mount_type": "ext4",
                "total": 489997.2,
                "used": 320785.3
            },
            "/media/frigate/recordings": {
                "free": 144246.2,
                "mount_type": "ext4",
                "total": 489997.2,
                "used": 320785.3
            },
            "/tmp/cache": {
                "free": 997.1,
                "mount_type": "tmpfs",
                "total": 1000.0,
                "used": 2.9
            }
        },
        "temperatures": {},
        "uptime": 499,
        "version": "0.12.0-bc16ad1"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB
