### ISSUE TITLE
[Support]: Camera Page snapshots not updating when accessing through Reverse Proxy (NPM)

### ISSUE THREAD

**Issue by russ-sentient** [blakeblackshear/frigate#5902]
### Describe the problem you are having

I just setup frigate to go through reverse proxy through the NGINX Proxy Manager UI.  I have only allowed local access, and am forwarding the host frigate.domain.com to my NPM IP on pfSense so I don't even have a CNAME for it in my Cloudflare DNS setup.  

This all works great, until today I noticed that when I access Frigate through frigate.domain.com, the thumbnail snapshots on the camera page were not updating (they were all still from last night in the dark).  I do not see any errors in the NGINX log for Frigate, curious what I might be missing (maybe some advanced config for NPM?)  Everything works as intended when I access through local IP/hostname.

### Version

0.12.0-BC16AD1

### Frigate config file

```yaml
mqtt:
  host: 10.10.0.14
  user: ****
  password: ****

ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

go2rtc:
  rtsp:
    username: "view"
    password: "*****"
  webrtc:
    candidates:
      - 10.50.0.10:8555
      - stun:8555
  streams:
    doorbell_main:
      - rtsp://***@10.50.0.77:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
      - "ffmpeg:doorbell_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    doorbell_sub:
      - rtsp://***@10.50.0.77:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
      - "ffmpeg:doorbell_sub#audio=opus"
    front_main:
      - rtsp://***@10.50.0.80:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:front_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    front_sub:
      - rtsp://***@10.50.0.80:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:front_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    back_main:
      - rtsp://***@10.50.0.81:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:back_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    back_sub:
      - rtsp://***@10.50.0.81:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:back_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    living_main:
      - rtsp://***@10.50.0.82:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:living_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    living_sub:
      - rtsp://***@10.50.0.82:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:living_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    server_main:
      - rtsp://***@10.50.0.83:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:server_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    server_sub:
      - rtsp://***@10.50.0.83:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:server_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    garage_main:
      - rtsp://***@10.50.0.84:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:garage_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    garage_sub:
      - rtsp://***@10.50.0.84:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:garage_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    dining_main:
      - rtsp://***@10.50.0.85:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:dining_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    dining_sub:
      - rtsp://***@10.50.0.85:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:dining_sub#audio=opus" # <- copy of the stream which transcodes audio to opus
    nursery_main:
      - rtsp://***@10.50.0.86:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:nursery_main#audio=opus" # <- copy of the stream which transcodes audio to opus
    nursery_sub:
      - rtsp://***@10.50.0.86:554/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:nursery_sub#audio=opus" # <- copy of the stream which transcodes audio to opus

    
cameras:
  doorbell:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: doorbell_main
    detect:
      width: 720
      height: 576
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          threshold: 0.7
  front:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: front_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - motorcycle
      filters:
        person:
          threshold: 0.7
          mask:
            - 854,0,854,103,809,93,805,21,822,0
        car:
          mask:
            - 854,480,0,480,0,167,237,116,662,154,667,0,854,0
        motorcycle:
          mask:
            - 854,480,0,480,0,167,237,116,662,154,667,0,854,0
    motion:
      mask:
        - 820,20,820,40,470,40,470,20
    zones:
      porch:
        coordinates: 854,480,235,480,695,195,854,222
      driveway:
        coordinates: 514,91,222,149,649,204,657,106
        objects:
          - person
          - car
          - motorcycle
        
  back:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 480
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: back_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.65
          mask:
            - 200,480,854,480,854,196,729,143,715,269
    motion:
      mask:
        - 820,20,820,40,470,40,470,20
    zones:
      deck:
        coordinates: 418,131,58,239,162,480,640,480,833,296
        objects:
          - dog
          - cat
          - person

  living:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: living_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.7
          #max_area: 900

        dog:
          min_score: 0.6
          threshold: 0.8
          #max_area: 700

        cat:
          min_score: 0.6
          threshold: 0.8
          #max_area: 550
    motion:
      mask:
        - 820,20,820,40,470,40,470,20

  server:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/server_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/server_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: server_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.7
    motion:
      mask:
        - 820,20,820,40,470,40,470,20

  garage:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: garage_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.65
    motion:
      mask:
        - 820,20,820,40,470,40,470,20
          
  dining:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dining_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/dining_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: dining_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.75
    motion:
      mask:
        - 820,20,820,40,470,40,470,20

  nursery:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nursery_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nursery_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      #output_args:
      #  detect: '-vf scale=854:480 -f rawvideo -pix_fmt yuv420p'
    live:
      stream_name: nursery_main
    detect:
      #width: 854
      #height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          threshold: 0.7
    motion:
      mask:
        - 820,20,820,40,470,40,470,20
    
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 7

record:
  enabled: true
  retain:
    mode: motion
    days: 0
  events:
    retain:
      mode: active_objects
      default: 7
      objects:
        cat: 7
        dog: 7
        person: 14

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 4
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
  restream: true
 
detectors: 
  coral:
    type: edgetpu
    device: usb

timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%b %d, %Y - %I:%M %p"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 1.8
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
```

### Relevant log output

```shell
2023-04-03 11:48:14.551945009  10.10.0.70 - - [03/Apr/2023:11:48:14 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 20309 "-" "axios/0.27.2" "-"
2023-04-03 11:48:15.298274704  10.10.0.70 - - [03/Apr/2023:11:48:15 -0500] "GET /api/living/latest.jpg?h=500 HTTP/1.1" 200 46779 "-" "axios/0.27.2" "-"
2023-04-03 11:48:16.054430919  10.10.0.70 - - [03/Apr/2023:11:48:16 -0500] "GET /api/living/latest.jpg?h=500 HTTP/1.1" 200 46865 "-" "axios/0.27.2" "-"
2023-04-03 11:48:16.841628782  10.10.0.70 - - [03/Apr/2023:11:48:16 -0500] "GET /api/living/latest.jpg?h=500 HTTP/1.1" 200 46481 "-" "axios/0.27.2" "-"
2023-04-03 11:48:16.841897439  10.10.0.70 - - [03/Apr/2023:11:48:16 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 20309 "-" "axios/0.27.2" "-"
2023-04-03 11:48:17.099703123  10.10.0.14 - - [03/Apr/2023:11:48:17 -0500] "GET /api/stats HTTP/1.1" 200 5318 "-" "HomeAssistant/2023.3.1 aiohttp/3.8.4 Python/3.10" "-"
2023-04-03 11:48:17.587512772  10.10.0.70 - - [03/Apr/2023:11:48:17 -0500] "GET /api/living/latest.jpg?h=500 HTTP/1.1" 200 46705 "-" "axios/0.27.2" "-"
2023-04-03 11:48:18.353941217  10.10.0.70 - - [03/Apr/2023:11:48:18 -0500] "GET /api/living/latest.jpg?h=500 HTTP/1.1" 200 46525 "-" "axios/0.27.2" "-"
2023-04-03 11:48:19.102054143  10.10.0.70 - - [03/Apr/2023:11:48:19 -0500] "GET /api/living/latest.jpg?h=500 HTTP/1.1" 200 46548 "-" "axios/0.27.2" "-"
2023-04-03 11:48:19.834556749  10.10.0.70 - - [03/Apr/2023:11:48:19 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 88211 "-" "axios/0.27.2" "-"
2023-04-03 11:48:21.239660909  10.10.0.70 - - [03/Apr/2023:11:48:21 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 88211 "-" "axios/0.27.2" "-"
2023-04-03 11:48:24.253728767  10.10.0.70 - - [03/Apr/2023:11:48:24 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 88211 "-" "axios/0.27.2" "-"
2023-04-03 11:48:26.024747116  10.10.0.14 - - [03/Apr/2023:11:48:26 -0500] "GET /api/stats HTTP/1.1" 200 5319 "-" "HomeAssistant/2023.3.1 aiohttp/3.8.4 Python/3.10" "-"
2023-04-03 11:48:27.765704456  10.10.0.70 - - [03/Apr/2023:11:48:27 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 88211 "-" "axios/0.27.2" "-"
2023-04-03 11:48:31.786478489  10.10.0.70 - - [03/Apr/2023:11:48:31 -0500] "GET /api/events/1680540369.268353-k7p07a/snapshot.jpg?h=500&crop=1 HTTP/1.1" 200 88211 "-" "axios/0.27.2" "-"
2023-04-03 11:48:35.245660237  10.10.0.14 - - [03/Apr/2023:11:48:35 -0500] "GET /api/stats HTTP/1.1" 200 5336 "-" "HomeAssistant/2023.3.1 aiohttp/3.8.4 Python/3.10" "-"
2023-04-03 11:48:43.658083046  10.10.0.5 - - [03/Apr/2023:11:48:43 -0500] "GET /api/config HTTP/1.1" 200 29559 "https://frigate.kanser-russ.com/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "10.10.0.204"
2023-04-03 11:48:43.659594609  10.10.0.5 - - [03/Apr/2023:11:48:43 -0500] "GET /api/config/raw HTTP/1.1" 200 2131 "https://frigate.kanser-russ.com/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "10.10.0.204"
2023-04-03 11:48:44.062919412  10.10.0.14 - - [03/Apr/2023:11:48:44 -0500] "GET /api/stats HTTP/1.1" 200 5366 "-" "HomeAssistant/2023.3.1 aiohttp/3.8.4 Python/3.10" "-"
2023-04-03 11:48:44.892175225  10.10.0.5 - - [03/Apr/2023:11:48:44 -0500] "GET /api/logs/go2rtc HTTP/1.1" 200 496 "https://frigate.kanser-russ.com/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "10.10.0.204"
2023-04-03 11:48:44.893837062  10.10.0.5 - - [03/Apr/2023:11:48:44 -0500] "GET /api/logs/frigate HTTP/1.1" 200 603 "https://frigate.kanser-russ.com/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "10.10.0.204"
```

### FFprobe output from your camera

```shell
These work fine.
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

AMCREST
