### ISSUE TITLE
[Support]: Supress "GET /api/stats HTTP/1.1" in Nginx Logs

### ISSUE THREAD

**Issue by saluther** [blakeblackshear/frigate#5911]
### Describe the problem you are having

I'm not sure if this issue belongs in the Frigate or Frigate Integration issues. It seems related to both. Since about the 12.0-beta3 version of Frigate I have noticed that the Frigate Nginx logs show the following log item about every 8 to 9 seconds.

       "GET /api/stats HTTP/1.1" 200 3516 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"

This log entry also appears in the Frigate docker container logs. The log entry seems to correspond to the updating of the capture, detect and ffmpeg CPU usage from the Frigate Integration. Those values change at the same time as the log updates. The Frigate UI only updates these values every 60 seconds along with the other system values. With this entry showing up every 8 to 9 seconds, it sort of "spams' the Nginx log. Is there a way to suppress this entry from showing up in the Nginx logs?

### Version

Frigate: 0.12.0-bc16ad1, Integration: v4.0.0-beta4

### Frigate config file

```yaml
# yaml-language-server: $schema=https://192.168.1.240:5000/api/config/schema.json

logger:
  default: info
  logs:
    frigate.mqtt: info
    frigate.app: info
    frigate.event: debug
 
ui:
  live_mode: mse
  use_experimental: false

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  width: 320
  height: 320
  labelmap:
    1: vehicle # previously "bicycle"
    2: vehicle # previously "car"
    3: vehicle # previously "motorcycle"
    5: vehicle # previously "bus"
    7: vehicle # previously "truck"
    14: animal # previously "bird"
    15: animal # previously "cat"
    16: animal # previously "dog"
    17: animal # previously "horse"
    18: animal # previously "sheep"
    19: animal # previously "cow"

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50

mqtt:
  host: 192.168.1.240
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ######
  password: ######
  stats_interval: 60

timestamp_style:
  position: "bl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

ffmpeg:
  global_args: -hide_banner -loglevel debug
  hwaccel_args: preset-vaapi
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic

record:
  enabled: True
  retain:
    days: 0
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - animal
      - person
      - vehicle
    required_zones: []
    retain:
      default: 7
      mode: motion
      objects:
        person: 7
        vehicle: 7

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: continuous

go2rtc:
  streams:
    driveway_main:
      - rtsp://#######:#######@192.168.1.38:554/cam/realmonitor?channel=1&subtype=0 # <--- 2304x1296
    driveway_sub1:
      - rtsp://#######:#######@192.168.1.38:554/cam/realmonitor?channel=1&subtype=1 # <--- 704x480
    frontyard_main:
      - rtsp://#######:#######@192.168.1.31:554/cam/realmonitor?channel=1&subtype=0 # <--- 2304x1296
    frontyard_sub1:
      - rtsp://#######:#######@192.168.1.31:554/cam/realmonitor?channel=1&subtype=1 # <--- 704x480
    frontyard_sub2:
      - rtsp://#######:#######@192.168.1.31:554/cam/realmonitor?channel=1&subtype=2 # <--- 1920x1080
    backyard_main:
      - rtsp://#######:#######@192.168.1.32:554/cam/realmonitor?channel=1&subtype=0 # <--- 2304x1296
    backyard_sub1:
      - rtsp://#######:#######@192.168.1.32:554/cam/realmonitor?channel=1&subtype=1 # <--- 704x480
    backyard_sub2:
      - rtsp://#######:#######@192.168.1.32:554/cam/realmonitor?channel=1&subtype=2 # <--- 1920x1080
    doorbell_sd:
      - rtsp://#######:#######@192.168.1.24:8554/Video-27_SD # <--- 640x360
      - ffmpeg:doorbell_sd#video=copy#audio=aac#audio=opus
    sideyard_hd:
      - rtsp://#######:#######@192.168.1.24:8554/Video-41 # <--- 1280x720
      - ffmpeg:sideyard_hd#video=copy#audio=pcmu#audio=opus

cameras:

  driveway:
    ffmpeg:
      inputs: 
        - path: rtsp://127.0.0.1:8554/driveway_main?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: driveway_main

    detect:
      width: 2304
      height: 1296
      fps: 10
      enabled: True
      max_disappeared: 50
      stationary:
        interval: 0
        threshold: 100
        max_frames:
          default: 150
          objects:
            person: 600

    best_image_timeout: 60

    zones:
      aries:
        coordinates: 434,274,820,240,1301,227,1756,249,2304,329,2304,648,1375,627,502,621,0,631,0,370

      drive_way:
        coordinates: 0,1296,2304,1296,2304,721,376,695,0,1101
    mqtt:
      required_zones:
        - aries
        - drive_way

    motion:
      mask:
        - 0,317,495,204,857,157,1205,140,1897,186,2304,270,2304,0,0,0
      threshold: 25
      contour_area: 30
      delta_alpha: 0.2
      frame_alpha: 0.5
      frame_height: 50
      improve_contrast: false
    rtmp:
      enabled: False

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - aries
          - drive_way

    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 512
      retain:
        default: 7
        objects:
          person: 7
          vehicle: 7
      required_zones:
        - aries
        - drive_way

    objects:
      track:
        - animal
        - person
        - vehicle
      filters:
        animal:
          min_area: 1000
          max_area: 20000
          min_score: 0.35
          threshold: 0.60
        person:
          min_area: 1250
          max_area: 50000
          min_score: 0.35
          threshold: 0.70
          mask:
            - 289,334,357,319,353,281,278,302
            - 1713,278,1802,289,1800,249,1717,234
            - 360,622,508,622,514,576,360,576
        vehicle:
          min_area: 2500
          max_area: 500000
          min_score: 0.30
          threshold: 0.50
          mask:
            - 380,346,929,298,1443,309,1977,327,2304,391,2304,164,1819,98,1133,60,599,115,0,253,0,413
            - 70,397,238,388,235,338,68,353

  frontyard:
    ffmpeg:
      inputs: 
        - path: rtsp://127.0.0.1:8554/frontyard_main?video=copy
          input_args: preset-rtsp-restream
          roles:
            #- detect
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_sub2?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            #- record
    live:
      stream_name: frontyard_sub2
 
    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True
      max_disappeared: 50
      stationary:
        interval: 0
        threshold: 100
        max_frames:
          default: 150
          objects:
            person: 600

    best_image_timeout: 60

    zones:
      aries:
        coordinates: 1234,78,1521,240,1920,543,1920,437,1719,283,1419,114
      front_yard:
        coordinates: 0,1080,1920,1080,1920,550,1664,381,1354,325,1055,283,757,260,359,267,132,301,0,361
        objects:
          - animal
          - person
      pegasis:
        coordinates: 401,71,185,64,0,207,0,327,102,279,227,258,472,238,891,245,1154,270,1441,319,1717,381,1379,156,1107,99,839,74
    mqtt:
      required_zones:
        - aries
        - front_yard
        - pegasis

    motion:
      mask:
        - 411,0,0,281,0,0
        - 1318,93,1845,95,1847,46,1318,42
        - 779,241,747,390,858,414,947,555,875,751,584,748,436,637,512,437,622,238
        - 521,238,372,465,241,602,83,564,200,390,359,243
        - 1920,806,1920,854,1709,1080,1628,1080,1590,991
        - 1267,838,1920,695,1920,597,1254,552
        - 1570,134,1920,312,1920,0,1250,0
      threshold: 25
      contour_area: 30
      delta_alpha: 0.2
      frame_alpha: 0.4
      frame_height: 50
      improve_contrast: false

    rtmp:
      enabled: False

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - aries
          - front_yard
          - pegasis

    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 512
      retain:
        default: 7
        objects:
          person: 7
          vehicle: 7
      required_zones:
        - aries
        - front_yard
        - pegasis

    objects:
      track:
        - animal
        - person
        - vehicle
      filters:
        animal:
          min_area: 1250
          max_area: 20000
          min_score: 0.35
          threshold: 0.60
          mask:
            - 1267,838,1920,695,1920,597,1254,552
            - 1647,531,1920,540,1920,466,1645,457
            - 907,58,1098,56,1102,0,906,0
        person:
          min_area: 1500
          max_area: 50000
          min_score: 0.35
          threshold: 0.60
          mask:
            - 1647,531,1920,540,1920,466,1645,457
            - 1639,390,1920,568,1920,496,1647,338
            - 1647,531,1920,540,1920,466,1645,457
            - 0,445,85,443,80,356,0,348
            - 1528,770,1663,770,1663,805,1528,805

        vehicle:
          min_area: 3000
          max_area: 125000
          min_score: 0.35
          threshold: 0.55
          mask: 
            - 0,156,348,131,762,122,1180,160,1573,216,1920,457,1920,0,0,0
            - 1668,501,1847,504,1846,450,1662,443
 
  backyard:
    ffmpeg:
      inputs: 
        - path: rtsp://127.0.0.1:8554/backyard_main?video=copy
          input_args: preset-rtsp-restream
          roles:
            #- detect
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub2?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
            #- record
    live:
      stream_name: backyard_sub2

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True
      max_disappeared: 50
      stationary:
        interval: 0
        threshold: 100
        max_frames:
          default: 150
          objects:
            person: 600

    best_image_timeout: 60

    zones:
      back_yard:
        coordinates: 0,1080,1920,1080,1920,294,1673,265,1403,245,1162,237,869,259,561,300,292,346,125,398,0,440
        objects:
          - animal
          - person
      #neighbor:
        #coordinates: 0,285,271,185,621,122,906,82,1167,87,1332,87,1691,155,1920,217,1920,0,0,0
    mqtt:
      required_zones:
        - back_yard
        #- neighbor

    motion:
      mask:
        - 0,436,235,334,487,292,939,243,1232,235,1522,235,1920,283,1920,0,0,0
        - 1478,363,1356,352,1190,357,1031,384,905,417,827,468,743,551,628,668,625,854,1013,854,959,674,1007,551,1098,497,1265,478,1472,458
        - 1856,744,1920,810,1920,615,1852,617
        - 38,1032,273,1025,262,830,35,832
        - 1570,477,1789,632,1820,465,1590,348
      threshold: 25
      contour_area: 30
      frame_alpha: 0.2
      frame_height: 50
      improve_contrast: false

    rtmp:
      enabled: False

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - back_yard
          #- neighbor

    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 512
      retain:
        default: 7
        objects:
          person: 7
      required_zones:
        - back_yard
        #- neighbor

    objects:
      track:
        - animal
        - person
        #- vehicle
      filters:
        animal:
          min_area: 1000
          max_area: 10000
          min_score: 0.35
          threshold: 0.75
          mask:
            - 1311,665,1511,647,1508,529,1311,536
            - 0,436,235,334,487,292,939,243,1232,235,1522,235,1920,283,1920,0,0,0
        person:
          min_area: 3500
          max_area: 37000
          min_score: 0.35
          threshold: 0.80
          mask:
            - 1704,640,1832,640,1832,576,1704,568
            - 1119,962,1225,956,1225,918,1119,923
            - 0,436,235,334,487,292,939,243,1232,235,1522,235,1920,283,1920,0,0,0
        #vehicle:
          #min_area: 12000
          #max_area: 50000
          #min_score: 0.35
          #threshold: 0.55
          #mask:
            #- 0,1080,1920,1080,1920,294,1673,265,1403,245,1162,237,869,259,561,300,292,346,125,398,0,440

  doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs: 
        - path: rtsp://127.0.0.1:8554/doorbell_sd?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: doorbell_sd

    detect:
      width: 640
      height: 360
      fps: 5
      enabled: True
      max_disappeared: 25
      stationary:
        interval: 0
        threshold: 100
        max_frames:
          default: 150
          objects:
            person: 600

    best_image_timeout: 60

    zones:
      front_yard:
        coordinates: 0,360,640,360,640,211,564,206,484,218,354,222,172,219,0,220
      pegasis:
        coordinates: 117,210,196,203,305,210,449,207,554,197,640,196,640,184,529,179,377,174,231,172,118,179

    mqtt:
      required_zones:
        - front_yard
        - pegasis

    motion:
      mask:
        - 0,190,640,188,640,0,0,0
        - 357,286,470,286,466,260,356,259
      threshold: 25
      contour_area: 30
      frame_alpha: 0.2
      frame_height: 50
      improve_contrast: false

    rtmp:
      enabled: False

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - front_yard
          - pegasis

    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 512
      retain:
        default: 7
        objects:
          person: 7
          vehicle: 7
      required_zones:
        - front_yard
        - pegasis

    objects:
      track:
        - animal
        - person
        - vehicle
      filters:
        animal:
          min_area: 115
          max_area: 20000
          min_score: 0.35
          threshold: 0.60
          mask:
            - 357,286,470,286,466,260,356,259
        person:
          min_area: 190
          max_area: 50000
          min_score: 0.35
          threshold: 0.75
          mask:
            - 357,286,470,286,466,260,356,259
        vehicle:
          min_area: 1000
          max_area: 300000
          min_score: 0.30
          threshold: 0.50
          mask:
            - 0,187,640,192,640,0,0,0
            - 559,206,640,205,640,195,558,196
            - 357,286,470,286,466,260,356,259

  sideyard:
    ffmpeg:
      inputs: 
        - path: rtsp://127.0.0.1:8554/sideyard_hd?video=copy&audio=pcm
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    live:
      stream_name: sideyard_hd

    detect:
      width: 1280
      height: 720
      fps: 5
      enabled: True
      max_disappeared: 25
      stationary:
        interval: 0
        threshold: 50
        max_frames:
          default: 150
          objects:
            person: 600

    best_image_timeout: 60

    zones:
      neighbor:
        coordinates: 763,148,765,0,218,0,216,177
      pegasis:
        coordinates: 772,120,1204,367,1230,289,1280,0,771,0
      side_yard:
        coordinates: 0,720,942,720,1089,574,1198,378,825,164,218,184,0,272

    mqtt:
      required_zones:
        - neighbor
        - pegasis
        - side_yard

    motion:
      mask:
        - 787,62,983,132,1184,254,1280,332,1280,0,586,0
        - 272,0,263,243,144,371,0,467,0,0
      threshold: 25
      contour_area: 30
      frame_alpha: 0.3
      frame_height: 50
      improve_contrast: false

    rtmp:
      enabled: False

    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        required_zones:
          - neighbor
          - pegasis
          - side_yard

    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      crop: True
      height: 512
      retain:
        default: 7
        objects:
          person: 7
          vehicle: 7
      required_zones:
        - neighbor
        - pegasis
        - side_yard

    objects:
      track:
        - animal
        - person
        - vehicle
      filters:
        animal:
          min_area: 400
          max_area: 20000
          min_score: 0.35
          threshold: 0.70
          mask:
            - 400,443,404,575,942,519,958,380
        person:
          min_area: 500
          max_area: 50000
          min_score: 0.35
          threshold: 0.72
          mask:
            - 774,375,774,447,969,453,972,377
            - 432,443,427,518,623,513,630,439
        vehicle:
          min_area: 1500
          max_area: 50000
          min_score: 0.30
          threshold: 0.55
          mask:
            - 0,720,942,720,1089,574,1198,378,825,164,218,184,0,272
            - 581,71,674,79,671,44,579,40
            - 1087,247,1182,254,1179,208,1092,200
            - 768,84,768,0,572,0,569,44
```

### Relevant log output

```shell
Nginx Log:
2023-04-04 11:30:15.975113247  192.168.1.240 - - [04/Apr/2023:11:30:15 -0600] "GET /api/stats HTTP/1.1" 200 3518 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"
2023-04-04 11:30:24.004966621  192.168.1.240 - - [04/Apr/2023:11:30:24 -0600] "GET /api/stats HTTP/1.1" 200 3487 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"
2023-04-04 11:30:32.846105927  192.168.1.240 - - [04/Apr/2023:11:30:32 -0600] "GET /api/stats HTTP/1.1" 200 3489 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"
2023-04-04 11:30:40.903465927  192.168.1.240 - - [04/Apr/2023:11:30:40 -0600] "GET /api/stats HTTP/1.1" 200 3486 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"
2023-04-04 11:30:48.866881296  192.168.1.240 - - [04/Apr/2023:11:30:48 -0600] "GET /api/stats HTTP/1.1" 200 3485 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"
2023-04-04 11:30:56.809506412  192.168.1.240 - - [04/Apr/2023:11:30:56 -0600] "GET /api/stats HTTP/1.1" 200 3483 "-" "HomeAssistant/2023.3.6 aiohttp/3.8.4 Python/3.10" "-"
```

### FFprobe output from your camera

```shell
Driveway:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304}]}}]

Frontyard:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]

Backyard:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"10/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]

Doorbell:
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"},{"avg_frame_rate":"30000/1001","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":360,"width":640}]}}]

Sideyard: (No response from Frigate UI)
  Metadata:
    title           : LIVE555 Streaming Media v2016.11.28
    comment         : LIVE555 Streaming Media v2016.11.28
  Duration: N/A, start: 0.000146, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn, 48 tbc
    Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
```

### Frigate stats

```json
{"backyard":{"camera_fps":10.0,"capture_pid":446,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":460,"pid":439,"process_fps":10.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"11.0","mem":"1.5"},"102":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"0.0","mem":"0.1"},"130":{"cpu":"0.0","mem":"0.0"},"131":{"cpu":"0.0","mem":"0.0"},"132":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"14":{"cpu":"0.0","mem":"0.0"},"144":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"160":{"cpu":"0.0","mem":"0.0"},"23":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"34321":{"cpu":"18.9","mem":"0.8"},"35195":{"cpu":"0.0","mem":"0.0"},"35245":{"cpu":"0.3","mem":"0.0"},"35250":{"cpu":"1.0","mem":"0.0"},"39":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"424":{"cpu":"0.0","mem":"0.5"},"430":{"cpu":"1.7","mem":"0.1"},"431":{"cpu":"0.3","mem":"0.7"},"433":{"cpu":"7.6","mem":"0.7"},"436":{"cpu":"4.0","mem":"0.9"},"437":{"cpu":"0.0","mem":"0.1"},"438":{"cpu":"3.3","mem":"0.7"},"439":{"cpu":"3.0","mem":"0.7"},"440":{"cpu":"1.7","mem":"0.7"},"441":{"cpu":"1.3","mem":"0.7"},"442":{"cpu":"0.0","mem":"0.1"},"443":{"cpu":"25.2","mem":"0.8"},"444":{"cpu":"17.9","mem":"0.7"},"446":{"cpu":"17.9","mem":"0.7"},"447":{"cpu":"0.0","mem":"0.1"},"453":{"cpu":"2.0","mem":"0.7"},"459":{"cpu":"5.3","mem":"0.7"},"460":{"cpu":"12.0","mem":"0.6"},"463":{"cpu":"0.0","mem":"0.1"},"465":{"cpu":"2.3","mem":"0.3"},"471":{"cpu":"0.0","mem":"0.1"},"474":{"cpu":"6.6","mem":"0.5"},"475":{"cpu":"1.3","mem":"0.1"},"479":{"cpu":"0.0","mem":"0.1"},"489":{"cpu":"10.0","mem":"0.2"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"16.9","mem":"0.1"},"8995":{"cpu":"12.3","mem":"0.6"},"8997":{"cpu":"2.0","mem":"0.2"},"MiB":{"cpu":"9583.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"0","mem":"users,"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":13.23,"pid":431}},"doorbell":{"camera_fps":5.0,"capture_pid":453,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":465,"pid":440,"process_fps":5.0,"skipped_fps":0.0},"driveway":{"camera_fps":10.0,"capture_pid":443,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":34321,"pid":436,"process_fps":10.0,"skipped_fps":0.0},"frontyard":{"camera_fps":10.1,"capture_pid":444,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":8995,"pid":438,"process_fps":10.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"16.86 %","mem":"- %"}},"service":{"last_updated":1680649589,"latest_version":"0.11.1","storage":{"/dev/shm":{"free":135.1,"mount_type":"tmpfs","total":151.0,"used":15.9},"/media/frigate/clips":{"free":42088.8,"mount_type":"fuseblk","total":1000202.0,"used":958113.3},"/media/frigate/recordings":{"free":42088.8,"mount_type":"fuseblk","total":1000202.0,"used":958113.3},"/tmp/cache":{"free":87.5,"mount_type":"tmpfs","total":100.0,"used":12.5}},"temperatures":{},"uptime":19586,"version":"0.12.0-bc16ad1"},"sideyard":{"camera_fps":5.0,"capture_pid":459,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":474,"pid":441,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

2-Dahua IPC-T5442TM-AS-2.8mm
