### ISSUE TITLE
[HW Accel Support]: RPi3+ higher ffmpeg CPU usage with HW accel than without?

### ISSUE THREAD

**Issue by klingon888** [blakeblackshear/frigate#5914]
### Describe the problem you are having

I'm testing rc2 on a RPi 3B+, latest bullseye-64 image, GPU mem 128 with 1 camera. Everything works well. But I noticed that when using "hwaccel_args: preset-rpi-64-h264", the ffmpeg CPU% goes up to 30-40%. Without hardware accel, it goes down to the teens. Is there something wrong in my setup? Thanks.

With hwaccel_args: preset-rpi-64-h264 :
![image](https://user-images.githubusercontent.com/30375535/230120135-8c5a693c-92b8-402f-8e9a-14a52d95a61a.png)

Without:
![image](https://user-images.githubusercontent.com/30375535/230120309-8438a3f2-b9da-4474-a2bf-89f0e4198977.png)

### Version

rc2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.50
  port: 1883
  topic_prefix: frigate
  user: xxxx
  password: xxxx

birdseye:
  enabled: True
  mode: continuous

database:
  path: /db/frigate.db

detectors:
  cpu1:
    type: cpu

rtmp:
  enabled: False

go2rtc:
  streams:
    front_wyze:
      - rtsp://192.168.10.145:8554/video1_unicast
    front_wyze_sub:
      - rtsp://192.168.10.145:8554/video2_unicast

ffmpeg:
  hwaccel_args: preset-rpi-64-h264  
  input_args: preset-rtsp-generic  


timestamp_style:
  position: "bl"
  thickness: 1

cameras:
  front_wyze:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://127.0.0.1:8554/front_wyze?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://127.0.0.1:8554/front_wyze_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
      max_disappeared: 25
      stationary:
        interval: 10  
        threshold: 50
    objects:
      track:
        - person
      mask:
        - 259,119,302,191,330,180,332,106,301,29,249,24
        - 378,79,408,62,400,0,367,0
        - 211,260,247,219,228,170,168,172
      filters:
        person:
          threshold: 0.7  
          min_area: 3500
          max_area: 37000
    motion:
      threshold: 25
      improve_contrast: True
      mask: 
        - 0,360,640,360,640,338,0,335 
        - 505,97,495,235,456,225,451,162,465,99
    record:
      enabled: True
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14
    mqtt:
      enabled: False
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-rc2
    shm_size: "45mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - frigate_mount:/media/frigate
      - /home/pi/frigate:/db
      - /home/pi/frigate/config/config.yml:/config/config.yml
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000   #1000000000 OR 400000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - TZ=America/New_York

volumes:
  frigate_mount:
    driver_opts:
      type: "cifs"
      device: "//192.168.1.50/media/homecam/frigate"
      o: "username=xxx,password=xxx,file_mode=0775,dir_mode=0775"
```

### Relevant log output

```shell
2023-04-05 10:34:51.930259371  [INFO] Starting Frigate...
2023-04-05 10:35:00.326614577  [2023-04-05 10:35:00] frigate.app                    INFO    : Starting Frigate (0.12.0-bc16ad1)
2023-04-05 10:35:00.485496423  [2023-04-05 10:35:00] peewee_migrate                 INFO    : Starting migrations
2023-04-05 10:35:00.520624681  [2023-04-05 10:35:00] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-05 10:35:00.609118970  [2023-04-05 10:35:00] detector.cpu1                  INFO    : Starting detection process: 289
2023-04-05 10:35:00.624955863  [2023-04-05 10:35:00] frigate.app                    INFO    : Output process started: 291
2023-04-05 10:35:00.632274545  [2023-04-05 10:35:00] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-04-05 10:35:00.650988307  [2023-04-05 10:35:00] frigate.app                    INFO    : Camera processor started for front_wyze: 293
2023-04-05 10:35:00.677470906  [2023-04-05 10:35:00] frigate.app                    INFO    : Capture process started for front_wyze: 296

2023-04-05 10:34:51.919377311  [INFO] Preparing go2rtc config...
2023-04-05 10:34:53.994539997  [INFO] Starting go2rtc...
2023-04-05 10:34:54.345196744  10:34:54.344 INF go2rtc version 1.2.0 linux/arm64
2023-04-05 10:34:54.346958199  10:34:54.346 INF [api] listen addr=:1984
2023-04-05 10:34:54.348826008  10:34:54.348 INF [rtsp] listen addr=:8554
2023-04-05 10:34:54.350866941  10:34:54.350 INF [srtp] listen addr=:8443
2023-04-05 10:34:54.352558812  10:34:54.352 INF [webrtc] listen addr=:8555
2023-04-05 10:35:01.918845737  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
root@7eeb1e3b28d9:/opt/frigate# ffprobe rtsp://192.168.10.145:8554/video1_unicast
ffprobe version 4.3.5-0+deb11u1+rpt3 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt3 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-strippin-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcacalibcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-lible-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enab --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enablme --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enableenable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request ibudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vouable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://192.168.10.145:8554/video1_unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2022.04.26
    comment         : LIVE555 Streaming Media v2022.04.26
  Duration: N/A, start: 0.350389, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn, 40 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Wyzecamv3

**Comment by NickM-27** [comment]
With the detect resolution of 640x360 along with the rpis suboptimal decoder, it is not unexpected that it could take more CPU resources to move the data to and from GPU memory as opposed to running everything on the CPU. I'd expect if you ran it on 1080p it would be a different story.

**Comment by klingon888** [comment]
Nick... Thanks for the prompt response. But my detect stream from the cam is at 640x360. 

ffprobe for detect substream:
```
Input #0, rtsp, from 'rtsp://192.168.10.145:8554/video2_unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2022.04.26
    comment         : LIVE555 Streaming Media v2022.04.26
  Duration: N/A, start: 0.446378, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 640x360, 20 fps, 20.08 tbr, 90k tbn, 40 tbc
```

As for your suggestion to run it at 1080p, is this the config to change? Wouldn't this consume more CPU given its running detect at 1080p?
```
cameras:
  front_wyze:
    ffmpeg:
      inputs:
        # High Resolution Stream 1920x1080
        - path: rtsp://127.0.0.1:8554/front_wyze?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
```
