### ISSUE TITLE
[0.8.0-rc4] Mask editor area not sized properly to camera image

### ISSUE THREAD

**Issue by InToSSH** [blakeblackshear/frigate#592]
**Describe the bug**
It looks like there is some error in recalculation of the image size on the screen and the mask editor coordinates.
It is not possible to strech the area over full image size.
The generated coordinates of the mask (for config file) match the image, but what is shown in the editor doesn't fit the whole image.

Checked the Developer Tools, the `<svg>` tag fits the whole image, but it looks like the calculated constrains of how far the mask can be stretched are not calculated properly to the size of the image on the screen. (more in screenshots)

**Version of frigate**
0.8.0-rc4

**Config**
```yaml
cameras:
  frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://u:p@10.10.3.243/third
          roles:
            - detect
            - clips

    height: 1080
    width: 1920
    fps: 5
    
    rtmp:
      enabled: False
      
    clips:
      enabled: True
      pre_capture: 3
      post_capture: 3
        
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      height: 1080
      
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 400
      
    motion:
      mask: 966,63,969,3,1912,8,1919,236,1756,195,1531,141,1324,95,1166,71
      
    zones:
      driveway:
        coordinates: 6,1072,18,451,147,365,528,307,835,292,1154,288,1495,293,1848,363,1897,456,1902,529,1916,722,1897,919,1895,1055,1297,1066,523,1066
      outside_road:
        coordinates: 4,363,8,239,13,124,160,112,428,86,688,58,893,66,1105,78,1241,119,1327,195,1268,258,1034,297,727,298,447,297,276,317
      

    objects:
      track:
        - person
```

**Screenshots**
![chrome_2021-01-23_19-33-40](https://user-images.githubusercontent.com/6452373/105610854-2dddbb00-5db2-11eb-8d92-17b770e3a202.png)

![chrome_2021-01-23_19-33-49](https://user-images.githubusercontent.com/6452373/105610856-2fa77e80-5db2-11eb-85d5-e1b7f72d6a1b.png)

![2021-01-23_19-34-50](https://user-images.githubusercontent.com/6452373/105610858-31714200-5db2-11eb-8689-4a142370ad06.png)
