### ISSUE TITLE
[Config Support]: Invalid Time on Events

### ISSUE THREAD

**Issue by cdavis289** [blakeblackshear/frigate#5928]
### Describe the problem you are having

After updating to 0.12 RC 2, events are showing "Invalid Time". I'm running Frigate via docker and passing the servers local time and timezone environment variable.

### Version

0.12.0-BC16AD1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.20.2
  port: 1883
  topic_prefix: frigate
  user: user
  password: password

rtmp:
  enabled: False

go2rtc:
  streams:
    aibullet_high: 
      - rtspx://192.168.20.100:7441/XXX
    aibullet_med: 
      - rtspx://192.168.20.100:7441/XXX
    g4_doorbell_high: 
      - rtspx://192.168.20.100:7441/XXX
    g4_doorbell_med: 
      - rtspx://192.168.20.100:7441/XXX
    g4_doorbell_pro_high: 
      - rtspx://192.168.20.100:7441/XXX
    g4_doorbell_pro_med: 
      - rtspx://192.168.20.100:7441/XXX
    ai360_high: 
      - rtspx://192.168.20.100:7441/XXX
    ai360_med: 
      - rtspx://192.168.20.100:7441/XXX
    boono_cam_high: 
      - rtspx://192.168.20.100:7441/XXX
    tv_room_cam_high: 
      - rtspx://192.168.20.100:7441/XXX
    floodlight_stairs_main:
      - rtsp://admin:XXX@192.168.20.55:554/cam/realmonitor?channel=1&subtype=0
    floodlight_stairs_sub1:
      - rtsp://admin:XXX@192.168.20.55:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.20.2:8555
      - stun:8555

ffmpeg:
  hwaccel_args: preset-vaapi
    #- -hwaccel
    #- vaapi 
    #- -hwaccel_device
    #- /dev/dri/renderD128 
    #- -hwaccel_output_format
    #- yuv420p 
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac

detectors:
  coral_pci:
    type: edgetpu
    device: pci
  coral_usb:
    type: edgetpu
    device: usb

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db
# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  #path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  #labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320

cameras:
  aibullet:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.20.2:8554/aibullet_high 
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.20.2:8554/aibullet_med 
          roles:
            - detect
            #- rtmp
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: aibullet_high
      height: 720
      quality: 8
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    record:
      events:
        required_zones:
          - aibullet_all
    snapshots:
      required_zones:
        - aibullet_all
    zones:
      aibullet_all:
        coordinates: 0,720,1280,720,1280,0,0,0
        objects:
          - dog
          - cat
          - person

  ai360:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.20.2:8554/ai360_high
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.20.2:8554/ai360_med
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: ai360_high
      height: 720
      quality: 8
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 1280 # <---- update for your camera's resolution
    zones:
      ai360_all:
        coordinates: 160,1046,672,1280,1106,1073,1280,634,1091,214,657,0,142,210,0,645
        objects:
          - person
    record:
      events:
        required_zones:
          - ai360_all
    snapshots:
      required_zones:
        - ai360_all
  
  floodlight_stairs:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.20.2:8554/floodlight_stairs_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.20.2:8554/floodlight_stairs_sub1
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: floodlight_stairs_main
      height: 1440
      quality: 8
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
    zones:
      Rear_Entry:
        coordinates: 704,480,704,299,281,288,224,297,222,480
        objects:
          - person
          - dog
          - cat
    record:
      events:
        required_zones:
          - Rear_Entry
    snapshots:
      required_zones:
        - Rear_Entry
  
  g4_doorbell_pro:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.20.2:8554/g4_doorbell_pro_high
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.20.2:8554/g4_doorbell_pro_med
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: g4_doorbell_pro_high
      height: 720
      quality: 8
    detect:
      width: 960 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    zones:
      Front_Entry:
        coordinates: 170,720,584,720,572,662,465,629,429,623,318,650
        objects:
          - person
          - umbrella
          - suitcase
      Sidewalk_Left:
        coordinates: 330,595,568,644,575,552,320,515
        objects:
          - person
          - umbrella
    record:
      events:
        required_zones:
          - Front_Entry
          - Sidewalk_Left
    snapshots:
      required_zones:
        - Front_Entry
        - Sidewalk_Left

  g4_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.20.2:8554/g4_doorbell_high
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.20.2:8554/g4_doorbell_med
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: g4_doorbell_high
      height: 720
      quality: 8
    detect:
      width: 960 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    zones:
      Side_Entry:
        coordinates: 347,720,839,720,864,657,534,499,473,465,450,464,350,486
        objects:
          - person
          - umbrella
          - suitcase
      Sidewalk_Right:
        coordinates: 346,483,448,464,531,429,529,407,343,436
        objects:
          - person
          - umbrella
    record:
      events:
        required_zones:
          - Side_Entry
          - Sidewalk_Right
    snapshots:
      required_zones:
        - Side_Entry
        - Sidewalk_Right

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - dog
    - cat
    - person
    - umbrella
    - suitcase
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - dog
      - cat
      - person
      - umbrella
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 7
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        dog: 7
        cat: 7
        person: 15

# Optional
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: mse
  # Optional: Set a timezone to use in the UI (default: use browser local time)
  timezone: False
  # Optional: Use an experimental recordings / camera view UI (default: shown below)
  use_experimental: False
  # Optional: Set the time format used.
  # Options are browser, 12hour, or 24hour (default: shown below)
  time_format: browser
  # Optional: Set the date style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 2/11/23
  #    medium: Feb 11, 2023
  #    full: Saturday, February 11, 2023
  # (default: shown below).
  date_style: short
  # Optional: Set the time style for a specified length.
  # Options are: full, long, medium, short
  # Examples:
  #    short: 8:14 PM
  #    medium: 8:15:22 PM
  #    full: 8:15:22 PM Mountain Standard Time
  # (default: shown below).
  time_style: medium
  # Optional: Ability to manually override the date / time styling to use strftime format
  # https://www.gnu.org/software/libc/manual/html_node/Formatting-Calendar-Time.html
  # possible values are shown above (default: not set)
  strftime_fmt: "%Y/%m/%d %H:%M"

  # Optional: Telemetry configuration
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
None
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

Docker Compose YAML for Frigate. I'm passing -/etc/localtime:/etc/localtime:ro via volumes and TZ=${TZ} via environment variables.

```
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always #unless-stopped
    #network_mode: host 
    image: ghcr.io/blakeblackshear/frigate:0.12.0-rc2
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/serial/by-id/usb-Unknown_Seeeduino_Cortex_M0+_D9DF79F65054414B352E3120FF09113E-if00:/dev/ttyACM0
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDATADIR}/frigate/config:/config
      - ${DOCKERDATADIR}/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "1984:1984"
    environment:
      - TZ=${TZ}
      - LIBVA_DRIVER_NAME=i965
```
 
<img width="444" alt="Frigate Invalid Time" src="https://user-images.githubusercontent.com/90156355/230689550-a98f2105-2d2d-4af8-8e66-0e6f9fd150e1.png">
