### ISSUE TITLE
[Config Support]: Updated config is not used when restarting frigate from UI top-right menu

### ISSUE THREAD

**Issue by amosyuen** [blakeblackshear/frigate#5930]
### Describe the problem you are having

I'm using frigate through HASS add-on, in the frigate UI, if I restart from the top-right hamburger menu it does not load the updated config. I have to go to the HA add-on and restart from there in order for the new config to be used.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
Change from:

detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
  cpu3:
    type: cpu
    num_threads: 1

to

detectors:
  cpu1:
    type: cpu
    num_threads: 1
  cpu2:
    type: cpu
    num_threads: 1
```

### Relevant log output

```shell
nothing relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)
