### ISSUE TITLE
[Support]:  unable to use Webrtc integration and Frigate 0.12V

### ISSUE THREAD

**Issue by chatz86** [blakeblackshear/frigate#5943]
### Describe the problem you are having

In unable to use both Webrtc and Frigate. Frigate will not start unless I disable Webrtc. I can then enable it afterwards. 

Is this normal? I use Webrtc to cast my cctv to a tv one page with 4 or 5 cameras 

### Version

0.12.0

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate:5000/api/config/schema
go2rtc:
  streams:
    test_cam: ...
  webrtc:
    candidates:
      - 192.168.1.189:8555
      - stun:8555
mqtt:
  host: 192.168.1.189
  port: 1883
  topic_prefix: frigate
  client_id: core-mosquitto
  user:
  password: 
  stats_interval: 60
birdseye:
  enabled: False
  width: 1920
  height: 1080
  quality: 8
  mode: objects 
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-vaapi
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-restream
  #-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  #output_args: preset-record-generic-audio-aac
    # Optional: output args for detect streams (default: shown below)
    #detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    #record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    # rtmp: -c copy -f flv
rtmp:
  enabled: False
live:
  height: 720
  quality: 8
detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5
  max_disappeared: 25
objects:
  track: 
    - person
    - dog
    - car
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 30
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: all
      # Optional: Per object retention days
      objects:
        person: 30
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://garage:xx@192.168.1.174:554/stream2
          roles:
            - detect
        - path: rtsp://garage:xx@192.168.1.174:554/stream1
          roles:  
            - record
    objects:
      track:
        - person
        - car
        - truck
    detect:
      width: 1280
      height: 720
      stationary:
        interval: 0
        max_frames:
          default: 3000
          objects:
            person: 1000
    motion:
      mask:
        - 390,453,386,720,0,720,0,259
    record:
      enabled: True
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: False
      bounding_box: True
  Entrance:
    ffmpeg:
      inputs:
        - path: rtsp://entrance:xx@192.168.1.74:554/stream2
          roles:
            - detect
        - path: rtsp://entrance: xx@192.168.1.74:554/stream1
          roles:
            - record
    detect:
      width: 1280
      height: 720
      stationary:
        interval: 0
        max_frames: 
          default: 3000
          objects:
            person: 1000
    motion:
      mask:
        - 593,549,545,345,447,280,393,356,418,633
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
  Workshop_Inside:
    ffmpeg:
      inputs:
        - path: rtsp://workshop_inside:xx@192.168.1.246:554/stream2
          roles:
            - detect
        - path: rtsp://workshop_inside:xx@192.168.1.246:554/stream1
          roles:  
            - record
    objects:
      track:
        - person
        - dog
    detect:
      width: 1280
      height: 720
      stationary:
        interval: 0
        max_frames:
          default: 3000
          objects:
            person: 1000
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
  Workshop_Outside:
    ffmpeg:
      inputs:
        - path: rtsp://workshop_outside:xx@192.168.1.88:554/stream2
          roles:
            - detect
        - path: rtsp://workshop_outside:xx@192.168.1.88:554/stream1
          roles:  
            - record
    objects:
      track:
        - person
        - dog
        - cat
    detect:
      width: 1280
      height: 720
      stationary:
        interval: 0
        max_frames:
          default: 3000
          objects:
            person: 1000
    record:
      enabled: True
    snapshots: 
      enabled: True
      timestamp: False
      bounding_box: True
    mqtt:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: True 
      height: 270
      quality: 100
```

### Relevant log output

```shell
X
```

### FFprobe output from your camera

```shell
X
```

### Frigate stats

```json
I can't figure out what's wrong with it
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

TP link Tapo C210, 200, 325ws, c500
