### ISSUE TITLE
[Config Support]: Implement configuration option to force binding of Nginx ports 5000 and 1935 on 127.0.0.1

### ISSUE THREAD

**Issue by dmak** [blakeblackshear/frigate#5972]
### Describe the problem you are having

I would like to run Frigate docker container in [host network mode](https://docs.docker.com/network/network-tutorial-host/) together with HomeAssistant to simplify configuration. To increase network isolation it would be great to configure Frigate nginx server to bind to 127.0.0.1 (by default it binds on all interfaces), in particular [lines 56 and 260](https://github.com/blakeblackshear/frigate/blob/dev/docker/rootfs/usr/local/nginx/conf/nginx.conf#L56) should read:
```
http {
    server {
        listen 127.0.0.1:5000; # needs further parametrisation/templating
...
rtmp {
    server {
        listen 127.0.0.1:1935; # needs further parametrisation/templating
```
Could be configured via e.g. environment variable and passed to [Docker compose](https://docs.docker.com/compose/environment-variables/set-environment-variables/):
```
services:
  frigate:                                                                                                                                                              
    container_name: frigate                                                                                                                                             
    ...
    environment:
      - BIND_ADDRESS=127.0.0.1
```

### Version

0.12.0-beta2

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)
