### ISSUE TITLE
[Support]: Help reducing false positives during rain

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#5974]
### Describe the problem you are having

It happens quite frequently where I live that we get a lot of rain. During these times I always get false positives especially on my driveway camera that there are cars.

![image](https://user-images.githubusercontent.com/7737834/230939697-9d0af2cd-3176-4233-959a-f350c13c3465.png)

![image](https://user-images.githubusercontent.com/7737834/230940207-d5896af4-2ef0-43fe-856d-1f23480a5c6d.png)

![image](https://user-images.githubusercontent.com/7737834/230940909-c1c9b073-f7bd-4c36-aa5f-0f4c2fca09d9.png)

![image](https://user-images.githubusercontent.com/7737834/230940972-608fa292-1ddc-4110-9d21-0365aa3f2fee.png)

### Version

0.12.0-BC16AD1

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

AMCREST

**Comment by NickM-27** [comment]
rain makes it difficult because the entire frame has motion on it so an object will likely be seen. This in general will need to be fixed by a frigate logic update to ignore those times of entire frame motion.

You could try raising the score but you are pretty close to the ceiling of the default model. You could also try a max_size filter which may help as well.

**Comment by rayzorben** [comment]
So I set a max_area for cars as such
```yaml
objects:
  filters:
    person:
      min_area: 800
    car:
      max_area: 80000
```

I also set a mask for car on the driveway:

```yaml
driveway:
    motion:
      mask:
        - 0,0,704,0,704,166,0,184
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      front_street:
        coordinates: 0,250,704,239,704,170,0,181
        objects:
          - person
          - car
          - dog
      driveway_area:
        coordinates: 704,480,0,480,0,226,704,233
        objects:
          - person
          - car
          - dog
    objects:
      filters:
        car:
          mask:
            - 560,284,672,279,679,223,561,221
```

![image](https://user-images.githubusercontent.com/7737834/231226853-74f6fe20-4f8c-41d5-ac1a-61473703e822.png)

However it is still raising events for a car in this area

![image](https://user-images.githubusercontent.com/7737834/231227069-4fa2aeb9-9b71-4e45-bfb3-787c5626ba4a.png)
