### ISSUE TITLE
[HW Accel Support]: Unable to read frames from ffmpeg process.

### ISSUE THREAD

**Issue by artur90226** [blakeblackshear/frigate#5975]
### Describe the problem you are having

Hi
I wanted to change to 12. But get some problems. Started over, but when I use "hwaccel: preset-nvidia-h264", I get errors.
I have nvidia p400, driver 530.30. 02
On 11 I used "hwaccel_args: - -c:v - h264_cuvid" and it all went very well.

What am I doing wrong? 

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
go2rtc:
  streams:
    haupteingang:
      - rtsp://adminpassword @192.168.xx.xx:554/Streaming/channels/101
      - "ffmpeg:haupteingang#video=h264"
    haupteingang_sub:
      - rtsp://adminpassword @192.168.xx.xx:554/Streaming/channels/103
      - "ffmpeg:haupteingang_sub#video=h264"

cameras:
  Haupteingang:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.xx.xx:8553/haupteingang?video=copy&audio=aac
          roles:
            - record
        - path: rtsp://192.168.xx.xx:8553/haupteingang_sub?video=copy
          roles:
            - detect
      hwaccel_args: -c:v h264_cuvid
    detect:
      enabled: False
      width: 1280
      height: 720
      fps: 7       
detectors:
  coral:
    type: edgetpu
    device: pci
```

### Operating system

UNRAID

### Install method

Docker Unraid CA Plugin 

### Network connection

Wired

### Camera make and model

Hikvision
