### ISSUE TITLE
[Support]: Frigate 0.12.0 randomly crashes

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#5976]
### Describe the problem you are having

Experienced twice during the past two days.  The docker container seem not responding.  If I try to stop it, I get an error message saying that the container cannot be stopped ("tried to kill the container, but did not receive an exit event").  I see 'go2rtc-healthcheck service exited with code 256 (by signal 15)'.  Then it says 'service go2rtc-healthcheck successfully stopped'.  I did not have this issue when running 0.12.0-rc1 (I had rc1 running for about two weeks before started using the official 0.12.0 release yesterday).

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# I have 6 cameras setting up the same way.  Only present settings for one here
mqtt:
  host: 192.168.xxx.xxx

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: True 
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    front_door:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:front_door#audio=aac

  webrtc:
    candidates:
      - 192.168.xxx.xxxx:8555
      - stun:8555

detect:
  enabled: True
  width: 1920
  height: 1080

rtmp:
  enabled: True

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
      output_args:
        record: preset-record-generic-audio-copy
```

### Relevant log output

```shell
The Web UI crashed, I have no way to get any log.
```

### FFprobe output from your camera

```shell
Container crashed.  I cannon access Frigate Web UI, or open a shell to access the container.
```

### Frigate stats

```json
Frigate Web UI crashed.  Cannot reach the end point.
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wireless

### Camera make and model

Wyze Cam V2, V3 on rtsp firmware

### Any other information that may be helpful

The application was run on a QNAP NAS with J3455 CPU.  This is the command to create the container:
`docker run --name=frigate --shm-size=256m --restart=unless-stopped --env=TZ=America/New_York --env=LIBVA_DRIVER_NAME=i965 --env=FRIGATE_RTSP_PASSWORD=xxxxxx --volume=/share/Container/frigate/config:/config:rw --volume=/share/share_vol2/frigate/media:/media/frigate:rw --network=bridge --privileged --workdir=/opt/frigate -p 4xxxx:1935 -p 4xxxx:5000 -p 4xxxx:8554 -p 4xxxx:8555 -p 4xxxx:8555/udp --label='com.qnap.qcs.network.mode=nat' --label='com.qnap.qcs.gpu=False' --memory="4g" --cpus="2" --detach=true -t ghcr.io/blakeblackshear/frigate:0.12.0`
I used the same command to create 0.12.0-rc1 container.  Config files are identical in 0.12.0 and 0.12.0-rc1.

I know it is hard to debug without any logs.  I recall there was one object referencing from one of the cameras stayed at 'in progress' stage for very long time.  Not sure if this exhausted system resources.  But I would assume same thing also happened in 0.12.0-rc1, which never crashed.  Another observation is that, I ran the docker from QNAP's Container Station (similar thing to Portainer).  When Frigate crashed, Container Station lost control of it.  I had to turn off the NAS by pressing the power button.  There seems to be a hanging process.  When I run the `ps` command, the command just hangs there after showing some processes.
