### ISSUE TITLE
[Config Support]: go2rtc credentials not updating from env

### ISSUE THREAD

**Issue by idle-user** [blakeblackshear/frigate#5982]
### Describe the problem you are having

In my docker config I have a few environment variables for different camera RTSP passwords and the streams are working great.

But when setting credentials for `go2rtc` in the config, it's not replacing the variable with the env value. 

I tried changing the variable name around the docker-compose and config file, but its just accepting the literal entry in the frigate's config file.

Maybe I'm doing something wrong?

Thanks in advance.

### Version

0.12.0

### Frigate config file

```yaml
...

go2rtc:
  rtsp:
    username: "admin"
    password: "{FRIGATE_RTSP_PASSWORD}"

...
```

RTSP credentials lets me with with the literal password: `{FRIGATE_RTSP_PASSWORD}`

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
