### ISSUE TITLE
[Support]: WebRTC doesn't work in Frigate for some of my cameras

### ISSUE THREAD

**Issue by belgianrubs** [blakeblackshear/frigate#5986]
### Describe the problem you are having

I've added all my streams to the go2rtc part of the config but I'm not able to view 2 of my cameras (Zijkant-Huis which is a Reolink RLC520 and Zijkant-Huis2 which is a Reolink RLC820A) using WebRTC in Frigate using the drop-down menu in the top right corner of the camera. All of my other cameras are working fine (these are all Reolink RLC 520A).
Although they're showing up in the go2rtc portal: 
![image](https://user-images.githubusercontent.com/80924413/231121571-89018446-a19c-4e97-9a5e-2d1cb105ee73.png)

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: mqtt-host
  user: Frigate
  password: password

go2rtc:
  streams:
    tuinhuis: http://192.168.30.91/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass
    tuinhuis_sub: http://192.168.30.91/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass
    oprit: http://192.168.10.14/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass
    oprit_sub: http://192.168.10.14/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass
    zij: http://192.168.10.11/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass
    zij_sub: http://192.168.10.11/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass
    zij2: http://192.168.10.16/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass
    zij2_sub: http://192.168.10.16/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass
  webrtc:
    candidates:
      - 192.168.20.21:8555
      - stun:8555

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

ui:
  live_mode: webrtc

cameras:
  tuinhuis:
    ui:
      order: 0
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://127.0.0.1:8554/tuinhuis
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuinhuis_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: true
      retain:
        days: 6
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 10
    detect:
      width: 896
      height: 672
      fps: 7
  zijkant-huis:
    ui:
      order: 1
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://127.0.0.1:8554/zij
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/zij_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 10
    detect:
      width: 896
      height: 672
      fps: 7
  zijkant-huis2:
    ui:
      order: 2
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://127.0.0.1:8554/zij2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/zij2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: true
      retain:
        days: 5
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 10  
    detect:
      width: 896 
      height: 512
      fps: 7
  oprit:
    ui:
      order: 3
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: rtsp://127.0.0.1:8554/oprit
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/oprit_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - person
        - car
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: true
      retain:
        days: 6
      events:
        pre_capture: 10
        post_capture: 10
        retain:
          default: 10    
    detect:
      width: 896
      height: 672
      fps: 7
  
database:
  # The path to store the SQLite DB (default: shown below)
  path: /db/frigate.db

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 5
  mode: continuous

detectors:
  coral1:
    type: edgetpu
    device: pci:0
```

### Relevant log output

```shell
2023-04-11 11:55:56.259983769  [INFO] Preparing go2rtc config...
2023-04-11 11:55:56.785073524  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-04-11 11:55:56.843331219  [INFO] Starting go2rtc...
2023-04-11 11:55:56.984793327  11:55:56.984 INF go2rtc version 1.2.0 linux/amd64
2023-04-11 11:55:56.985243014  11:55:56.985 INF [api] listen addr=:1984
2023-04-11 11:55:56.985696247  11:55:56.985 INF [rtsp] listen addr=:8554
2023-04-11 11:55:56.986255087  11:55:56.986 INF [srtp] listen addr=:8443
2023-04-11 11:55:56.986579851  11:55:56.986 INF [webrtc] listen addr=:8555
2023-04-11 11:56:06.267194174  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":672,"width":896},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":512,"width":896},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink RLC 520 and 820A
