### ISSUE TITLE
[Detector Support]: Coral PCIe on Synology

### ISSUE THREAD

**Issue by ManClone** [blakeblackshear/frigate#5987]
### Describe the problem you are having

Hello!
i try to get the CORAL M.2 ACCELERATOR B+M KEY running on a Synology DS920+. Problem is, i'm not able to install the drivers via ssh.
Is it possible to integrate the drivers for PCIe/m.2 in the Dockerimage like the USB drivers?

Or do anybody have some tips to get the Coral M.2 running on a synology without APT? 

### Version

0.12.0-rc2

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-rc2
    shm_size: "160mb"
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/Frigate/config.yml:/config/config.yml
      - /volume1/Data/Frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8552:1935"
      - "8553:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
endless boot
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

M.2
