### ISSUE TITLE
[Config Support]: No audio in Home Assistant camera entity despite go2rtc working

### ISSUE THREAD

**Issue by brywithawhy** [blakeblackshear/frigate#5996]
### Describe the problem you are having

I've been searching for hours but as a beginner, I can't seem to find a solution. I'm sorry if this is staring me in the face but I cannot figure it out.

I have installed Frigate via Docker on my Ubuntu NAS, have set up a standalone Unifi G3 Flex camera, got both mse and webrtc working with audio on the live view with go2rtc, and have detections and recordings working also. I have also installed the Frigate integration via HACS and connected it to my NAS. Everything works fine, except the camera entity in Home Assistant does not have audio. It seems to be the original low quality stream from the original jsmpeg when I started, although I can't confirm this.

I've tried reloading the integration and also deleting and reconfiguring however there is still no audio.

I'm hoping to get this working, because prior to frigate I could tell Alexa to "Show me the garage camera" and it pop up rather quickly via Home Assistant Cloud. Since moving to Frigate, this no longer works and from what I have read, it is because there needs to be an audio stream.

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: 172.16.11.253
  user: xxxxxx
  password: xxxxxx
  enabled: True

cameras:
  garage:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5

    snapshots:
      enabled: true
    
    record:
      enabled: true
      retain:
        days: 3
    motion:
      mask:
        - 0,1080,381,905,296,179,1049,79,1920,54,1920,0,0,0

record:
  enabled: True
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 14
      mode: active_objects

objects:
  track:
    - person
    - car
  filters:
    car:
      mask:
        - 773,405,863,211,1272,220,1263,424

go2rtc:
  streams:
    garage:
      - rtsp://user:pass@172.16.10.78:554/s0
      - "ffmpeg:garage#audio=opus"
      - "ffmpeg:garage#audio=aac"
  webrtc:
    candidates:
      - 172.16.10.252:8555
      - stun:8555
```

### Relevant log output

```shell
Nothing noteworthy in logs
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.7"},"1":{"cpu":"0.0","mem":"0.0"},"102":{"cpu":"0.0","mem":"0.0"},"1065":{"cpu":"0.0","mem":"0.0"},"1088":{"cpu":"0.0","mem":"0.0"},"1091":{"cpu":"0.0","mem":"0.0"},"111":{"cpu":"0.3","mem":"2.7"},"117":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"1.0"},"288":{"cpu":"0.0","mem":"0.1"},"289":{"cpu":"0.0","mem":"1.3"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.3","mem":"1.2"},"293":{"cpu":"0.7","mem":"1.2"},"294":{"cpu":"0.0","mem":"0.2"},"295":{"cpu":"2.7","mem":"1.1"},"299":{"cpu":"0.0","mem":"0.2"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"51.7","mem":"0.7"},"31":{"cpu":"0.0","mem":"0.0"},"316":{"cpu":"2.0","mem":"0.2"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"92":{"cpu":"4.3","mem":"0.3"},"MiB":{"cpu":"6165.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"0","mem":"users,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":52.68,"pid":289}},"garage":{"camera_fps":5.1,"capture_pid":295,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":301,"pid":293,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1681214530,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":63.3,"mount_type":"tmpfs","total":67.1,"used":3.8},"/media/frigate/clips":{"free":3670557.8,"mount_type":"ext4","total":23996157.3,"used":20325582.7},"/media/frigate/recordings":{"free":3670557.8,"mount_type":"ext4","total":23996157.3,"used":20325582.7},"/tmp/cache":{"free":989.8,"mount_type":"tmpfs","total":1000.0,"used":10.2}},"temperatures":{},"uptime":843,"version":"0.12.0-da3e197"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

Using the Go2rtc that was bundled with Frigate, including webrtc
