### ISSUE TITLE
[Config Support]: only option to select jsmpeg on video feeth => go2rtc/webrtc

### ISSUE THREAD

**Issue by Tuurkevg** [blakeblackshear/frigate#6003]
### Describe the problem you are having

I want to select also web rtc and or webrtc.

I use right now go2rtc to restream my feed and use it ass well for my frigate detection
![image](https://user-images.githubusercontent.com/77327545/231299250-b4185a00-59fa-4120-af52-df2bc812ad6b.png)

### Version

0.12.0-da3e197

### Frigate config file

```yaml
---
mqtt:
  # Required: host name
  host: mqtt-broker-home.mqttbroker
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  #user: frigate
  user: frigate
  ## Optional: password
  ## NOTE: MQTT password can be specified with an environment variables that must begin with 'FRIGATE_'.
  ##       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  #password: empty
  password: "{FRIGATE_MQTT_PASSWORD}"
  # Optional: tls_ca_certs for enabling TLS using self-signed certs (default: None)
  #tls_ca_certs: /path/to/ca.crt
  # Optional: tls_client_cert and tls_client key in order to use self-signed client
  # certificates (default: None)
  # NOTE: certificate must not be password-protected
  #       do not set user and password when using a client certificate
  #tls_client_cert: /path/to/client.crt
  #tls_client_key: /path/to/client.key
  # Optional: tls_insecure (true/false) for enabling TLS verification of
  # the server hostname in the server certificate (default: None)
  #tls_insecure: false
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    #num_threads: 3
# Optional: Database configuration
# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector)
  path: /edgetpu_model.tflite
  # Optional: path to the labelmap (default: shown below)
  labelmap_path: /labelmap.txt
  # Required: Object detection model input width (default: shown below)
  width: 320
  # Required: Object detection model input height (default: shown below)
  height: 320
  # Optional: Label name modifications. These are merged into the standard labelmap.
  labelmap:
    2: vehicle
# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.mqtt: info
    #frigate.event: debug
    #frigate.record: debug
# Optional: set environment variables
environment_vars:
  {}
  #EXAMPLE_VAR: value
# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  #mode: objects
  mode: continuous
  restream: False
## Optional: ffmpeg configuration
ffmpeg:
  #  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel debug
  #  # Optional: global hwaccel args (default: shown below)
  #  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    # https://blog.peterblandford.com/2021/10/30/reolink-4k-cameras-with-frigate-home-assistant-and-24-hour-recording/
    # https://docs.frigate.video/configuration/hardware_acceleration#intel-based-cpus-10th-generation-via-quicksync
    # aquarak has 8th generation cpu: https://ark.intel.com/content/www/us/en/ark/products/135936/intel-core-i38109u-processor-4m-cache-up-to-3-60-ghz.html
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  #  # Optional: global input args (default: shown below)
  #  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others
  input_args: preset-rtsp-restream #preset-rtsp-restream-low-latency
  #    - -avoid_negative_ts
  #    - make_zero
  #    - -fflags
  #    - +genpts+discardcorrupt
  #    - -flags
  #    - low_delay
  #    - -strict
  #    - experimental
  #    - -analyzeduration
  #    - 1000M
  #    - -probesize
  #    - 1000M
  #    - -rw_timeout
  #    - "5000000"
  # Optional: global output args
  output_args:
    # https://blog.peterblandford.com/2021/10/30/reolink-4k-cameras-with-frigate-home-assistant-and-24-hour-recording/
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy #-an removed to hear sound
#    # Optional: output args for detect streams (default: shown below)
#    detect: -f rawvideo -pix_fmt yuv420p
#    # Optional: output args for record streams (default: shown below)
#    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
#    # Optional: output args for rtmp streams (default: shown below)
# https://github.com/blakeblackshear/frigate/issues/1602
# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 640
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 360
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking # since v0.10
  stationary:
    # Optional: Frequency for running detection on stationary objects (default: shown below)
    # When set to 0, object detection will never be run on stationary objects. If set to 10,
    # it will be run on every 10th frame.
    interval: 2
    # Optional: Number of frames without a position change for an object to be considered
    #                 stationary (default: 10x the frame rate or 10s)
    threshold: 15
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person,
    # but leave car at the default.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 1000
      # Optional: Object specific values
      #objects:
      # person: 500
## Optional: Object configuration
## NOTE: Can be overridden at the camera level
objects:
  #  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - dog
    - bus
    - truck
  filters:
    person:
      threshold: 0.70
    car:
      threshold: 0.35
#  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
#  # Checks based on the bottom center of the bounding box of the object.
#  # NOTE: This mask is COMBINED with the object type specific mask below
#  mask: 0,0,1000,0,1000,200,0,200<
#  # Optional: filters to reduce false positives for specific object types
#    person:
#      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#      min_area: 5000
#      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#      max_area: 100000
#      # Optional: minimum score for the object to initiate tracking (default: shown below)
#      min_score: 0.5
#      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
#      threshold: 0.7
#      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
#      # Checks based on the bottom center of the bounding box of the object
#      mask: 0,0,1000,0,1000,200,0,200
## Optional: Motion configuration
## NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  enabled: True
  # Optional: Number of days to retain recordings regardless of events (default: shown below)
  # NOTE: This should be set to 0 and retention should be defined in events section below
  #       if you only want to retain recordings of events.
  #retain_days: 1 # deprecated in v0.10
  retain:
    days: 3
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 15
    # Optional: Objects to save recordings for. (default: all tracked objects)
    #objects:
    #  - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 15
      mode: active_objects
      # Optional: Per object retention days
      #objects:
      # person: 15
# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  #  enabled: False
  enabled: True
  #  # Optional: print a timestamp on the snapshots (default: shown below)
  #  timestamp: False
  timestamp: True
  #  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  #  # Optional: crop the snapshot (default: shown below)
  #  crop: False
  #  # Optional: height to resize the snapshot to (default: original size)
  #  height: 175
  #  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #  required_zones: []
  #  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    #    default: 10
    default: 60
#    # Optional: Per object retention days
#    objects:
#      person: 15
# Optional: RTMP configuration
# NOTE: Can be overridden at the camera level
go2rtc:
  streams:
    cam0_Main:
      - ffmpeg:http://cam0.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM0_PASSWORD}
    cam0_Sub:
      - ffmpeg:http://cam0.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM0_PASSWORD}

    cam1_Main:
      - ffmpeg:http://cam1.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM1_PASSWORD}
    cam1_Sub:
      - ffmpeg:http://cam1.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM1_PASSWORD}

    cam2_Main:
      - ffmpeg:http://cam2.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM2_PASSWORD}
    cam2_Sub:
      - ffmpeg:http://cam2.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM2_PASSWORD}

    cam3_Main:
      - ffmpeg:http://cam3.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM3_PASSWORD}
    cam3_Sub:
      - ffmpeg:http://cam3.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM3_PASSWORD}

    cam360_Main:
      - ffmpeg:http://cam360.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM360_PASSWORD}
    cam360_Sub:
      - ffmpeg:http://cam360.iot.vanginderachter.be/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM360_PASSWORD}
  webrtc:
    candidates:
      - frigate.frigate:8555
      # - frigate-streams.home.vanginderachter.be:8555
      - stun:8555

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1
# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tr"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%d/%m/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow
# Required
cameras:
  # https://support.reolink.com/hc/en-us/articles/360006240073-Request-for-RTSP-URL
  # Required: name of the camera
  cam0:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: A list of input streams for the camera. See documentation for more information.
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM0_PASSWORD}@cam0.iot.vanginderachter.be:554/h264Preview_01_sub
        - path: rtsp://127.0.0.1:8554/cam0_Sub
          roles:
            - detect
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM0_PASSWORD}@cam0.iot.vanginderachter.be:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/cam0_Main
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - record
  cam1:
    ffmpeg:
      inputs:
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM1_PASSWORD}@cam1.iot.vanginderachter.be:554/h264Preview_01_sub
        - path: rtsp://127.0.0.1:8554/cam1_Sub
          roles:
            - detect
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM1_PASSWORD}@cam1.iot.vanginderachter.be:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/cam1_Main
          roles:
            - record
  cam2:
    ffmpeg:
      inputs:
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM2_PASSWORD}@cam2.iot.vanginderachter.be:554/h264Preview_01_sub
        - path: rtsp://127.0.0.1:8554/cam2_Sub
          roles:
            - detect
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM2_PASSWORD}@cam2.iot.vanginderachter.be:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/cam2_Main
          roles:
            - record
    objects:
      filters:
        car:
          threshold: 0.75

  cam3:
    ffmpeg:
      inputs:
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM3_PASSWORD}@cam3.iot.vanginderachter.be:554/h264Preview_01_sub
        - path: rtsp://127.0.0.1:8554/cam3_Sub
          roles:
            - detect
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM3_PASSWORD}@cam3.iot.vanginderachter.be:554/h264Preview_01_main
        - path: rtsp://127.0.0.1:8554/cam3_Main
          roles:
            - record
    objects:
      filters:
        car:
          threshold: 0.75
  cam360:
    ffmpeg:
      inputs:
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        #- path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM360_PASSWORD}@cam360.iot.vanginderachter.be:554/h264Preview_01_sub
        - path: rtsp://127.0.0.1:8554/cam360_Sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/cam360_Main
          roles:
            - record
    birdseye:
      enabled: False
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-04-11 22:12:10.163151905  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
2023-04-11 22:12:10.166196408  [INFO] Starting Frigate...
s6-rc: info: service legacy-services: starting
2023-04-11 22:12:10.188984289  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-04-11 22:12:10.484462998  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-04-11 22:12:10.534041282  [INFO] Starting go2rtc...
2023-04-11 22:12:10.610048686  00:12:10.610 INF go2rtc version 1.2.0 linux/amd64
2023-04-11 22:12:10.610335345  00:12:10.610 INF [api] listen addr=:1984
2023-04-11 22:12:10.610695259  00:12:10.610 INF [rtsp] listen addr=:8554
2023-04-11 22:12:10.611112098  00:12:10.611 INF [srtp] listen addr=:8443
2023-04-11 22:12:10.611345154  00:12:10.611 INF [webrtc] listen addr=:8555
2023-04-11 22:12:11.387626953  [2023-04-12 00:12:11] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-11 22:12:11.436949799  [2023-04-12 00:12:11] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-04-11 22:12:11.438968839  [2023-04-12 00:12:11] peewee_migrate                 INFO    : Starting migrations
2023-04-11 22:12:11.442389949  [2023-04-12 00:12:11] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-11 22:12:11.459913749  [2023-04-12 00:12:11] detector.coral                 INFO    : Starting detection process: 290
2023-04-11 22:12:14.136802871  [2023-04-12 00:12:11] frigate.app                    INFO    : Output process started: 292
2023-04-11 22:12:14.136806399  [2023-04-12 00:12:11] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-04-11 22:12:14.136810645  [2023-04-12 00:12:11] frigate.app                    INFO    : Camera processor started for cam0: 294
2023-04-11 22:12:14.136813020  [2023-04-12 00:12:11] frigate.app                    INFO    : Camera processor started for cam1: 296
2023-04-11 22:12:14.136824026  [2023-04-12 00:12:11] frigate.app                    INFO    : Camera processor started for cam2: 299
2023-04-11 22:12:14.136826356  [2023-04-12 00:12:11] frigate.app                    INFO    : Camera processor started for cam3: 303
2023-04-11 22:12:14.136828266  [2023-04-12 00:12:11] frigate.app                    INFO    : Camera processor started for cam360: 304
2023-04-11 22:12:14.136841473  [2023-04-12 00:12:11] frigate.app                    INFO    : Capture process started for cam0: 306
2023-04-11 22:12:14.136843408  [2023-04-12 00:12:11] frigate.app                    INFO    : Capture process started for cam1: 309
2023-04-11 22:12:14.136845158  [2023-04-12 00:12:11] frigate.app                    INFO    : Capture process started for cam2: 313
2023-04-11 22:12:14.136853522  [2023-04-12 00:12:11] frigate.app                    INFO    : Capture process started for cam3: 315
2023-04-11 22:12:14.136855281  [2023-04-12 00:12:11] frigate.app                    INFO    : Capture process started for cam360: 319
2023-04-11 22:12:14.141362865  [2023-04-12 00:12:14] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-04-11 22:12:20.183581461  [INFO] Starting go2rtc healthcheck service...
2023-04-11 22:12:49.665197528  10.42.0.1 - - [12/Apr/2023:00:12:49 +0200] "GET / HTTP/1.1" 200 10081 "-" "kube-probe/1.23" "-"
2023-04-11 22:12:49.665205057  10.42.0.1 - - [12/Apr/2023:00:12:49 +0200] "GET / HTTP/1.1" 200 10081 "-" "kube-probe/1.23" "-"
2023-04-11 22:12:53.153185089  10.42.0.150 - - [12/Apr/2023:00:12:53 +0200] "GET /logs HTTP/1.1" 200 6641 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0" "172.31.32.43"
```

### Frigate stats

```json
/
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I want to use the webrtc or MSE feed in home assistent and frigate. But i cant get it to work to get the other feeds
