### ISSUE TITLE
[Support]: Expose full quality record stream to home assistant

### ISSUE THREAD

**Issue by JRascagneres** [blakeblackshear/frigate#6007]
### Describe the problem you are having

I'm using home assistant with frigate and using the home assistant integration. I'm using a simple picture entity card and was using the 'recording' sensor provided by the integration.
This appears to be using my substream meant for detection when really I'd like it to use the high quality record stream. Is this possible? Perhaps this could be an enhancement to the integration to show both cameras.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: homeassistant.lan
  user: mqtt-user
  password: bladder-doe-fencing

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3

cameras:
  front_reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_reolink
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_reolink_sub
          roles:
            - detect
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
    motion:
      mask:
        - 2476,0,0,0,0,1126,176,1428
    zones:
      front_path:
        coordinates: 1834,1920,761,1092,171,1449,0,1168,0,1920
      front_pavement:
        coordinates: 2560,1205,2560,791,1702,452,1385,658
      front_road:
        coordinates: 2560,821,2560,284,2184,132,1728,469
    live:
      stream_name: front_reolink
    ui:
      order: 0
  back_reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_reolink
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
    zones:
      patio:
        coordinates: 1293,995,1084,812,67,1037,317,1920,1736,1920,1160,1373,740,1519,510,1167
      grass:
        coordinates: 1293,995,1084,812,2108,591,2560,750,2560,1920,1736,1920,1160,1373,740,1519,510,1167
    ui:
      order: 1
  garage_reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_reolink
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1920
      fps: 5
    objects:
      track: 
        - person
        - car
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: True
      retain:
        default: 10
    record:
      enabled: True
      events:
        retain:
          default: 2
    motion:
      mask:
        - 0,233,1501,233,1780,816,2560,818,2560,269,2560,0,0,0
    zones:
      driveway:
        coordinates: 387,1920,1026,468,1603,468,2178,1920
    ui:
      order: 2

birdseye:
  enabled: True
  mode: continuous
  quality: 1

rtmp:
  enabled: false

live:
  quality: 1
  height: 2560

go2rtc:
  streams:
    front_reolink:
      - rtsp://admin:redacted@192.168.4.30:554/h264Preview_01_main
    front_reolink_sub:
      - rtsp://admin:redacted@192.168.4.30:554/h264Preview_01_sub
    back_reolink:
      - rtsp://admin:redacted@192.168.4.31/h264Preview_01_main
    garage_reolink:
      - rtsp://admin:redacted@192.168.4.44/h264Preview_01_main

record:
  retain:
    mode: active_objects
  events:
    post_capture: 15
    retain:
      mode: active_objects
      objects:
        person: 5

snapshots:
  retain:
    objects:
      person: 15

detect:
  # Number of frames before someone has disappeared --> 5 fps therefore 25s
  max_disappeared: 125
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"back_reolink":{"camera_fps":5.0,"capture_pid":736,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":746,"pid":731,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"114":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"141":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"158":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"182":{"cpu":"0.0","mem":"0.0"},"209":{"cpu":"0.3","mem":"0.0"},"2217":{"cpu":"0.0","mem":"0.0"},"2230":{"cpu":"0.0","mem":"0.0"},"2238":{"cpu":"0.3","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"247":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"274":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"312":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"353":{"cpu":"0.0","mem":"0.0"},"389":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"425":{"cpu":"0.0","mem":"0.0"},"461":{"cpu":"0.0","mem":"0.0"},"715":{"cpu":"0.0","mem":"0.2"},"721":{"cpu":"0.3","mem":"0.0"},"722":{"cpu":"0.0","mem":"0.3"},"724":{"cpu":"0.0","mem":"0.3"},"726":{"cpu":"2.3","mem":"0.3"},"729":{"cpu":"0.7","mem":"0.3"},"730":{"cpu":"0.0","mem":"0.1"},"731":{"cpu":"1.0","mem":"0.3"},"732":{"cpu":"1.0","mem":"0.3"},"733":{"cpu":"5.7","mem":"0.3"},"736":{"cpu":"6.7","mem":"0.3"},"740":{"cpu":"7.0","mem":"0.3"},"746":{"cpu":"27.3","mem":"0.3"},"747":{"cpu":"1.3","mem":"0.1"},"748":{"cpu":"28.3","mem":"0.3"},"751":{"cpu":"0.0","mem":"0.1"},"752":{"cpu":"0.0","mem":"0.1"},"753":{"cpu":"0.0","mem":"0.1"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"9.7","mem":"0.1"},"909":{"cpu":"7.0","mem":"0.2"},"97":{"cpu":"0.0","mem":"0.0"},"99":{"cpu":"58.3","mem":"1.2"},"MiB":{"cpu":"15240.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":90.6,"pid":722},"cpu2":{"detection_start":0.0,"inference_speed":88.1,"pid":724}},"front_reolink":{"camera_fps":5.0,"capture_pid":733,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":909,"pid":729,"process_fps":5.0,"skipped_fps":0.0},"garage_reolink":{"camera_fps":5.0,"capture_pid":740,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":748,"pid":732,"process_fps":5.0,"skipped_fps":0.0},"service":{"last_updated":1681269955,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":244.3,"mount_type":"tmpfs","total":268.4,"used":24.2},"/media/frigate/clips":{"free":106808.2,"mount_type":"ext4","total":490577.0,"used":358773.6},"/media/frigate/recordings":{"free":106808.2,"mount_type":"ext4","total":490577.0,"used":358773.6},"/tmp/cache":{"free":985.3,"mount_type":"tmpfs","total":1000.0,"used":14.7}},"temperatures":{},"uptime":558,"version":"0.12.0-da3e197"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-510
