### ISSUE TITLE
[Support]: Can't view WebRTC stream even if port is forwarded

### ISSUE THREAD

**Issue by victorlee115** [blakeblackshear/frigate#6011]
### Describe the problem you are having

<img width="176" alt="image" src="https://user-images.githubusercontent.com/126674491/231384005-063c3a01-e498-4b48-a4fd-0dec24ea33b0.png">

I currently host my frigate instance via Cloudflare Tunnels. I have also port forwarded port 8555 to 10.20.10.2 on my router.

I have tested this with a Port Forward checker.
<img width="213" alt="image" src="https://user-images.githubusercontent.com/126674491/231384854-39db87b4-5074-47ce-a195-8612637ed480.png">

Now I'm not sure what could be the issue here. 

My current Frigate/go2rtc is hosted on 10.20.10.2, and I have a Nginx Proxy Manager (10.20.10.5) that proxies traffic for 10.20.10.2 for SSL. So when I go to my domain (frigate.domain.com), it has a "DNS record" of 10.20.10.5.

Everything works locally but not remotely.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
go2rtc:
  rtsp:
    username: "admin"
    password: "REDACTED"
  webrtc:
    candidates:
      - 10.20.10.2:8555
      - stun:8555
      - frigate.domain.com:8555
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

HikVision
