### ISSUE TITLE
[Config Support]: Only Snapshots, No Clips

### ISSUE THREAD

**Issue by databoy2k** [blakeblackshear/frigate#6019]
### Describe the problem you are having

For whatever reason, I can't seem to get recordings on events, just snapshots. I even get the snapshot in my MQTT events, but no video file is created. There's virtually no logs, either (see below)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 10.10.1.9
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  fext_cam_door:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:admin@10.10.3.44:554/Streaming/Channels/102
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
  fext_cam_north:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://10.10.3.47/ch0_0.h264
          roles:
            - detect
            - record
    motion:
      mask:
        - 1280,255,1280,0,511,0

ffmpeg:
  #hwaccel_args: -hwaccel preset-nvidia-h264 -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  global_args: -hide_banner -loglevel warning
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
```

### Relevant log output

```shell
2023-04-12 11:48:20.397151593  [2023-04-12 11:48:20] frigate.comms.dispatcher       INFO    : Turning off detection for fext_cam_door
2023-04-12 11:48:20.444130198  [2023-04-12 11:48:20] frigate.comms.dispatcher       INFO    : Turning off detection for fext_cam_north
2023-04-12 11:50:54.466935289  [2023-04-12 11:50:54] frigate.comms.dispatcher       INFO    : Turning on detection for fext_cam_door
2023-04-12 11:50:55.344531030  [2023-04-12 11:50:55] frigate.comms.dispatcher       INFO    : Turning on recordings for fext_cam_door
2023-04-12 11:50:56.072548758  [2023-04-12 11:50:56] frigate.comms.dispatcher       INFO    : Turning on snapshots for fext_cam_door
2023-04-12 11:51:56.930881089  [2023-04-12 11:51:56] frigate.http                   ERROR   : No recordings found for the requested time range
2023-04-12 11:51:56.947093173  [2023-04-12 11:51:56] frigate.http                   ERROR   : Event does not have recordings: 1681321884.687357-ub8zhb
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"1.0","mem":"1.1"},"124":{"cpu":"0.0","mem":"0.1"},"140":{"cpu":"0.0","mem":"0.0"},"141":{"cpu":"0.0","mem":"0.0"},"142":{"cpu":"0.0","mem":"0.0"},"143":{"cpu":"0.0","mem":"0.0"},"21":{"cpu":"0.0","mem":"0.0"},"2174":{"cpu":"0.3","mem":"0.9"},"2299":{"cpu":"0.0","mem":"0.0"},"23":{"cpu":"0.0","mem":"0.0"},"2331":{"cpu":"0.0","mem":"0.0"},"2336":{"cpu":"0.0","mem":"0.0"},"2338":{"cpu":"0.0","mem":"0.0"},"294":{"cpu":"0.0","mem":"0.5"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.1"},"301":{"cpu":"0.0","mem":"0.7"},"303":{"cpu":"0.0","mem":"0.6"},"307":{"cpu":"0.3","mem":"0.6"},"308":{"cpu":"0.0","mem":"0.1"},"309":{"cpu":"0.0","mem":"0.6"},"31":{"cpu":"0.0","mem":"0.0"},"311":{"cpu":"1.0","mem":"0.5"},"312":{"cpu":"0.0","mem":"0.6"},"318":{"cpu":"1.7","mem":"1.4"},"319":{"cpu":"0.0","mem":"0.1"},"32":{"cpu":"0.0","mem":"0.0"},"323":{"cpu":"0.0","mem":"0.3"},"33":{"cpu":"0.0","mem":"0.0"},"34":{"cpu":"0.0","mem":"0.0"},"35":{"cpu":"0.0","mem":"0.0"},"36":{"cpu":"0.0","mem":"0.0"},"37":{"cpu":"0.0","mem":"0.0"},"38":{"cpu":"0.0","mem":"0.0"},"47":{"cpu":"0.0","mem":"0.0"},"48":{"cpu":"0.0","mem":"0.0"},"86":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"95":{"cpu":"0.0","mem":"0.1"},"MiB":{"cpu":"10987.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"load","mem":"average:"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.12,"pid":301}},"fext_cam_door":{"camera_fps":5.1,"capture_pid":311,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":318,"pid":307,"process_fps":5.1,"skipped_fps":0.0},"fext_cam_north":{"camera_fps":0.2,"capture_pid":312,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":2174,"pid":309,"process_fps":0.2,"skipped_fps":0.0},"gpu_usages":{"NVIDIA GeForce GTX 750 Ti":{"gpu":"1 %","mem":"9.7 %"}},"service":{"last_updated":1681322270,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":62.9,"mount_type":"tmpfs","total":67.1,"used":4.2},"/media/frigate/clips":{"free":356416.2,"mount_type":"ext4","total":489997.2,"used":108615.2},"/media/frigate/recordings":{"free":356416.2,"mount_type":"ext4","total":489997.2,"used":108615.2},"/tmp/cache":{"free":356416.2,"mount_type":"overlay","total":489997.2,"used":108615.2}},"temperatures":{},"uptime":1391,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I think it quit working during the 12 beta; I've never gotten it working since.

**Comment by rayzorben** [comment]
You seem to be missing `record` section. The default is False https://docs.frigate.video/configuration/

```yaml
record:
  enabled: True
  events:
    retain:
      default: 10
```
