### ISSUE TITLE
[Config Support]: Can't get detailed/debug log prints

### ISSUE THREAD

**Issue by mashmeade** [blakeblackshear/frigate#6020]
### Describe the problem you are having

I'm struggling to set up Nvidia-based detection, but in order to try and figure out what's not working, I am struggling to get any detailed logs. I have the system working with cpu detection, and that works fine. When I change the detector to tensor, I can see in nvtop that frigate connects to it and 4x ffmpeg for hw acceleration, and the inference time drops to ~10ms, so I think it's a model issue. I can see a spike in GPU activity in nvtop when I trigger the camera by walking in front of it, but there's nothing in the logs to help.

Having reverted to cpu detection, I'd like to see what a successful detection looks like in the logs, so then I can try and figure out what is not working with the tensor detector.

I'm looking at both "docker-compose logs" and the UI log feature.

It's possibly just a config/syntax thing in config.yml (I hope!). Grateful for guidance, thanks!

### Version

0.12.0-BC16AD1 (RC2 -tensorrt)

### Frigate config file

```yaml
mqtt:
  enabled: False
detectors:
  cpu1:
    type: cpu
    num_threads: 8
    model:
      path: "/cpu_model.tflite"
logger:
  default: debug
  # component specific logger overrides
  logs:
    asyncio: info
    peewee: info # this logs every sql query otherwise
    ws4py: warning
    #urllib3.connectionpool: info
    frigate.app: debug
    frigate.record: info
    frigate.events: info
    frigate.storage: info
    frigate.comms.mqtt: info
    frigate.event: debug
    frigate.object_detection: debug
    detector.tensorrt: debug
    detector.cpu1: debug
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous

cameras:
  Shed: # <------ Name the camera
    enabled: True
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass@192.168.100.140:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.100.140:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <----- Add stream you want to record from
          roles:
            - record
  Door: # <------ Name the camera
    enabled: True
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass@192.168.100.141:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.100.141:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <----- Add stream you want to record from
          roles:
            - record
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
  Deck1: # <------ Name the camera
    enabled: True
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass@192.168.100.142:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.100.142:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <----- Add stream you want to record from
          roles:
            - record
  Deck2: # <------ Name the camera
    enabled: True
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:pass@192.168.100.143:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.100.143:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif # <----- Add stream you want to record from
          roles:
            - record
detect:
    enabled: True # <---- disable detection until you have a working camera feed
    width: 704 # <---- update for your camera's resolution
    height: 480 # <---- update for your camera's resolution
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - truck
    - bicycle
    - bear
    - cat
    - dog
    - horse
    - sheep
    - cow
    - motorcycle
  filters:
    person:
      threshold: 0.5
record:
    enabled: True
    events:
        retain:
            default: 10
```

### Relevant log output

```shell
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2023-04-12 17:36:06.262922536  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-04-12 17:36:06.269177411  [INFO] Starting Frigate...
frigate  | 2023-04-12 17:36:06.269878677  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-04-12 17:36:06.712395580  [INFO] Starting go2rtc...
frigate  | 2023-04-12 17:36:06.810959804  17:36:06.810 INF go2rtc version 1.2.0 linux/amd64
frigate  | 2023-04-12 17:36:06.811369375  17:36:06.811 INF [api] listen addr=:1984
frigate  | 2023-04-12 17:36:06.811781921  17:36:06.811 INF [rtsp] listen addr=:8554
frigate  | 2023-04-12 17:36:06.812078793  17:36:06.812 INF [srtp] listen addr=:8443
frigate  | 2023-04-12 17:36:06.812484806  17:36:06.812 INF [webrtc] listen addr=:8555
frigate  | 2023-04-12 17:36:07.701329349  [2023-04-12 17:36:07] frigate.app                    INFO    : Starting Frigate (0.12.0-bc16ad1)
frigate  | 2023-04-12 17:36:07.731479465  [2023-04-12 17:36:07] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
frigate  | 2023-04-12 17:36:07.742970433  [2023-04-12 17:36:07] peewee_migrate                 INFO    : Starting migrations
frigate  | 2023-04-12 17:36:07.748907635  [2023-04-12 17:36:07] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | 2023-04-12 17:36:07.774514260  [2023-04-12 17:36:07] frigate.app                    INFO    : Output process started: 434
frigate  | 2023-04-12 17:36:07.774913496  [2023-04-12 17:36:07] detector.cpu1                  INFO    : Starting detection process: 433
frigate  | 2023-04-12 17:36:07.778859077  [2023-04-12 17:36:07] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2023-04-12 17:36:07.803196703  [2023-04-12 17:36:07] frigate.app                    INFO    : Camera processor started for Shed: 437
frigate  | 2023-04-12 17:36:07.803645850  [2023-04-12 17:36:07] frigate.app                    INFO    : Camera processor started for Door: 439
frigate  | 2023-04-12 17:36:07.803914922  [2023-04-12 17:36:07] frigate.app                    INFO    : Camera processor started for Deck1: 440
frigate  | 2023-04-12 17:36:07.804205293  [2023-04-12 17:36:07] frigate.app                    INFO    : Camera processor started for Deck2: 441
frigate  | 2023-04-12 17:36:07.804691962  [2023-04-12 17:36:07] frigate.app                    INFO    : Capture process started for Shed: 442
frigate  | 2023-04-12 17:36:07.804700322  [2023-04-12 17:36:07] frigate.app                    INFO    : Capture process started for Door: 443
frigate  | 2023-04-12 17:36:07.809692219  [2023-04-12 17:36:07] frigate.app                    INFO    : Capture process started for Deck1: 444
frigate  | 2023-04-12 17:36:07.815725812  [2023-04-12 17:36:07] frigate.app                    INFO    : Capture process started for Deck2: 447
frigate  | 2023-04-12 17:36:07.823433087  [2023-04-12 17:36:07] urllib3.connectionpool         DEBUG   : Starting new HTTPS connection (1): api.github.com:443
frigate  | 2023-04-12 17:36:08.333187000  [2023-04-12 17:36:08] urllib3.connectionpool         DEBUG   : https://api.github.com:443 "GET /repos/blakeblackshear/frigate/releases/latest HTTP/1.1" 200 12930
frigate  | 2023-04-12 17:36:16.267802734  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-04-12 17:37:02.446957757  [2023-04-12 17:37:02] frigate.comms.ws               DEBUG   : payload for Door/person/snapshot wasn't text. Skipping...
frigate  | 2023-04-12 17:37:14.666736088  [2023-04-12 17:37:14] frigate.comms.ws               DEBUG   : payload for Door/person/snapshot wasn't text. Skipping...
frigate  | 2023-04-12 17:37:18.538815965  [2023-04-12 17:37:18] frigate.stats                  DEBUG   : Starting stats collection
frigate  | 2023-04-12 17:37:21.884576177  [2023-04-12 17:37:21] frigate.stats                  DEBUG   : Finished stats collection
```

### Frigate stats

```json
{"Deck1":{"camera_fps":5.0,"capture_pid":444,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":458,"pid":440,"process_fps":5.0,"skipped_fps":0.0},"Deck2":{"camera_fps":5.0,"capture_pid":447,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":457,"pid":441,"process_fps":5.0,"skipped_fps":0.0},"Door":{"camera_fps":5.0,"capture_pid":443,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":454,"pid":439,"process_fps":5.0,"skipped_fps":0.0},"Shed":{"camera_fps":5.1,"capture_pid":442,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":453,"pid":437,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.0"},"1":{"cpu":"0.0","mem":"0.0"},"100":{"cpu":"5.0","mem":"1.1"},"1090":{"cpu":"0.0","mem":"0.0"},"1105":{"cpu":"0.3","mem":"0.0"},"115":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"138":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.0"},"144":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"157":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"427":{"cpu":"0.0","mem":"0.5"},"432":{"cpu":"1.0","mem":"0.0"},"433":{"cpu":"0.0","mem":"0.6"},"434":{"cpu":"1.7","mem":"0.6"},"437":{"cpu":"1.0","mem":"0.6"},"439":{"cpu":"1.0","mem":"0.6"},"440":{"cpu":"1.0","mem":"0.6"},"441":{"cpu":"1.0","mem":"0.6"},"442":{"cpu":"1.7","mem":"0.5"},"443":{"cpu":"1.7","mem":"0.5"},"444":{"cpu":"1.7","mem":"0.5"},"447":{"cpu":"1.3","mem":"0.5"},"453":{"cpu":"2.3","mem":"0.3"},"454":{"cpu":"2.0","mem":"0.3"},"457":{"cpu":"1.7","mem":"0.3"},"458":{"cpu":"2.0","mem":"0.3"},"460":{"cpu":"0.0","mem":"0.1"},"464":{"cpu":"4.7","mem":"0.1"},"466":{"cpu":"4.7","mem":"0.1"},"470":{"cpu":"5.0","mem":"0.1"},"471":{"cpu":"0.0","mem":"0.1"},"472":{"cpu":"5.6","mem":"0.1"},"473":{"cpu":"0.0","mem":"0.1"},"474":{"cpu":"0.0","mem":"0.1"},"475":{"cpu":"0.0","mem":"0.1"},"79":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"30414.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.61,"}},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":147.9,"pid":433}},"gpu_usages":{"Quadro M4000":{"gpu":"0 %","mem":"4.1 %"}},"service":{"last_updated":1681321920,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":63.2,"mount_type":"tmpfs","total":67.1,"used":4.0},"/media/frigate/clips":{"free":8695.4,"mount_type":"ext4","total":51460.5,"used":40117.9},"/media/frigate/recordings":{"free":8695.4,"mount_type":"ext4","total":51460.5,"used":40117.9},"/tmp/cache":{"free":3950.0,"mount_type":"tmpfs","total":4000.0,"used":50.0}},"temperatures":{},"uptime":953,"version":"0.12.0-bc16ad1"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Just want to say thanks for making this software. I started using it yesterday, and was able to config 4x camera with GPU acceleration in ffmpeg in just a day from scratch. Almost have tensorrt working too. MUCH easier than some other NVRs!

I don't think it's relevant to my log issue, but in case it is, my hardware is a HP DL360 G9 with 2xE2640 2.6 GHz (16 cores total), 96GB RAM, running Proxmox 7.4 with Quadro M4000 (8GB) passed through to an Ubuntu 22.04 VM with 32GB and 8 cores assigned. The host isn't doing anything else and this is the only VM running. RAM and CPU usage is minimal. Cameras are 4x Amcrest IP8M-2669s (4K high res, 704 x 480 or 640 x 480 lo-res). Everything works with CPU detection, except the logs!
