### ISSUE TITLE
[HW Accel Support]:  Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#6024]
### Describe the problem you are having

Hey
I break my head how to solve the issue with no success
I have PC based Intel CPU (i5-8600k) and my main system is Debian buster

The problem - i got when i want hardware acceleration `rigate.util                   ERROR   : Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found`

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.187
  user: "test"
  password: "test"
environment_vars:
  LIBVA_DRIVER_NAME: i965
detectors:
  coral:
    type: edgetpu
    device: usb   

cameras:
 GardenOne:
   ffmpeg:
      hwaccel_args: preset-vaapi
#      hwaccel_args: preset-nvidia-h264
      input_args:
         - -avoid_negative_ts
         - make_zero
         - -fflags
         - nobuffer+genpts+discardcorrupt
         - -flags
         - low_delay
         - -strict
         - experimental
         - -analyzeduration
         - 1000M
         - -probesize
         - 1000M
         - -rw_timeout
         - "5000000"
      inputs:
          - path: http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=123&password=123
            roles:
              - record
              - rtmp
          - path: http://192.168.1.108/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=123&password=123
            roles:
              - detect
      output_args:
        record: preset-record-generic-audio-aac
   detect:
     width: 1920
     height: 1080
     fps: 15
   rtmp:
     enabled: false
          
   objects:
     track:
       - person
       - dog
       - cat
     filters:
       person:
         threshold: 0.70
       
   snapshots:
     enabled: true
     timestamp: false
     bounding_box: false
     crop: False
     height: 900
     retain:
       default: 14

   record:
     enabled: true
     retain:
       days: 4
     events:
       pre_capture: 10
       post_capture: 15
       objects:
         - person
         - cat
         - dog
       retain:
         default: 14
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigateNvidia
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable

    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb 
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
    shm_size: "512mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/a/Downloads/frigateNvidia/config/config.yml:/config/config.yml
      - /home/a/Downloads/frigateNvidia/media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
2023-04-13 00:30:07.688184870  [2023-04-13 00:30:06] frigate.util                   ERROR   : Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

non relevant
