### ISSUE TITLE
[HW Accel Support]: Vmware workstation 17

### ISSUE THREAD

**Issue by monsieurlatte** [blakeblackshear/frigate#6025]
### Describe the problem you are having

I am running vmworkstation pro 17 on a windows 10 install.  It has an i7 12700 cpu.  It also has an nvidia t600 in it.  Both work fine in windows.  I have enabled the 3d accelerated graphics option for the HAOS install but it never detects either graphics card.  I have tried the vapi config as well as the ihd and the cuda one.  Any thoughts on things to try to test?  The config below doesn't have the options in it because it's my currently working one without hw.  

### Version

12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.165
  user: redacted
  password: redacted

detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  AnimalWalkway:
    ffmpeg:
      global_args:
        - -an
      inputs:
        - path: redacted
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true
    detect:
      width: 2688
      height: 1512
    objects:
      filters:
        cat:
          mask:
            - 0,1512,647,1512,780,313,1866,324,2094,334,2163,0,0,0
        dog:
          mask:
            - 0,1512,647,1512,780,313,1866,324,2094,334,2163,0,0,0

  Overhang:
    ffmpeg:
      global_args:
        - -an
      inputs:
        - path: redacted
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true
    detect:
      width: 1920
      height: 1080
    objects:
      filters:
        cat:
          mask:
            - 0,1080,600,1080,661,265,1343,291,1920,776,1920,325,1920,0,0,0     
        dog:
          mask:
            - 0,1080,600,1080,661,265,1343,291,1920,776,1920,325,1920,0,0,0

objects:
  track:
    - person
    - cat
    - dog
```

### docker-compose file or Docker CLI command

```yaml
HAOS install.
```

### Relevant log output

```shell
VAINFO OUTPUT
Return Code: 3

Process Error:

error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/simpledrm_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Audio:

Codec: AAC (Advanced Audio Coding)

Audio:

Codec: Opus (Opus Interactive Audio Codec)

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2688x1512
FPS: 24/1

```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Unifi Protect
