### ISSUE TITLE
[Detector Support]: High CPU consumption by frigate.detector.ov (OpenVINO) after sunrise (IR from on to off).

### ISSUE THREAD

**Issue by avbor** [blakeblackshear/frigate#6034]
### Describe the problem you are having

Hi!
I just recently tried this wonderful program and ran into a problem.
At dawn, when the IR is turned off on one of my cameras, the object detection process goes crazy and starts consuming a lot of CPU (130+%, according to the dashboard).
If I turn off object detection at that point, everything goes back to normal. If I turn it back on, the high load comes back.
Only complete restart of frigate solves the problem completely.
![image](https://user-images.githubusercontent.com/32452033/231669755-5ebcb98d-ae07-4527-ab5d-a66996de669f.png)

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: ip
  port: 1883
  topic_prefix: frigate_srv01
  client_id: srv01
  user: user
  password: pass

database:
  path: /db/frigate.db

ffmpeg:
  hwaccel_args: preset-vaapi

telemetry:
  version_check: True

birdseye:
  enabled: False

detectors:
  ov:
    type: openvino
#    device: AUTO
    device: CPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: True
  events:
    pre_capture: 3
    post_capture: 3
    retain:
      default: 3
      mode: active_objects

snapshots:
  enabled: True
  retain:
    default: 3

objects:
  track:
    - person

ui:
  live_mode: webrtc

environment_vars:
  LIBVA_DRIVER_NAME: i965

cameras:

  reolinkcam_01:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolinkcam_01_main_raw
          input_args: preset-rtsp-generic
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolinkcam_01_sub_raw
          input_args: preset-rtsp-generic
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    live:
      stream_name: reolinkcam_01_main
    ui:
      order: 1

  reolinkcam_02:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolinkcam_02_main_raw
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolinkcam_02_sub_raw
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 20
      contour_area: 20
      improve_contrast: True
      mask:
        - 120,28,0,64,0,0,640,0,640,29
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
        - bird
    live:
      stream_name: reolinkcam_02_main
    ui:
      order: 3

go2rtc:

  webrtc:
    candidates:
      - stun:8555

  streams:
  
    "reolinkcam_01_main_raw":
      - rtsp://user:pass@ip:554/h264Preview_01_main
    "reolinkcam_01_main":
      - rtsp://localhost:8554/reolinkcam_01_main_raw
      - ffmpeg:reolinkcam_01_main_raw#audio=opus
  
    "reolinkcam_01_sub_raw":
      - rtsp://user:pass@ip:554/h264Preview_01_sub
    "reolinkcam_01_sub":
      - rtsp://localhost:8554/reolinkcam_01_sub_raw
      - ffmpeg:reolinkcam_01_sub_raw#audio=opus
  
    "reolinkcam_02_main_raw":
      - rtsp://user:pass@ip:554/h264Preview_01_main
    "reolinkcam_02_main":
      - rtsp://localhost:8554/reolinkcam_02_main_raw
      - ffmpeg:reolinkcam_02_main_raw#audio=opus
  
    "reolinkcam_02_sub_raw":
      - rtsp://user:pass@ip:554/h264Preview_01_sub
    "reolinkcam_02_sub":
      - rtsp://localhost:8554/reolinkcam_02_sub_raw
      - ffmpeg:reolinkcam_02_sub_raw#audio=opus
  
    "dafangcam_01":
      - rtsp://ip:8554/unicast
  
    "dafangcam_02":
      - rtsp://ip:8554/unicast
  
    "dafangcam_03":
      - rtsp://ip:8554/unicast
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
    privileged: true
    shm_size: "256mb"
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./media:/media/frigate
      - ./db:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 512M
    deploy:
      resources:
        limits:
          memory: 3G
    network_mode: host
```

### Relevant log output

```shell
I haven't found anything interesting in the log during this time.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Frigate is running on an Intel NUC ([NUC7PJYH](https://ark.intel.com/content/www/ru/ru/ark/products/126137/intel-nuc-kit-nuc7pjyh.html)), with a Pentium J5005 CPU.

**Comment by blakeblackshear** [comment]
Watch the debug view and see what's happening.

**Comment by avbor** [comment]
Thanks, I think I found the problem:
```
    motion:
      threshold: 20
      contour_area: 20
      improve_contrast: True
```

And it is the combination of these parameters that causes the problem.
Thresholds without contrast enhancement does not cause problems, as well as contrast enhancement without thresholds.
