### ISSUE TITLE
[Support]: Birdseye buffer

### ISSUE THREAD

**Issue by globalenergys** [blakeblackshear/frigate#6038]
### Describe the problem you are having

Often I leave BirdsEye view in a browser tab not in focus, this could be for several hours.

When I bring the tab back in focus the live preview is sped up to catch-up to real-time which could take 30 seconds or so until you are again seeing a live stream.

A refresh of the page does clear the buffer but it would be ideal, for me at least, for BirdsEye to always show the live view when the browser tab is brought back in focus

### Version

 0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: xxx
  user: ***
  password: ***

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous

go2rtc:
  streams:
    driveway: rtsp://***:***@xxx/h264Preview_01_main
    lounge: rtsp://***:***@xxx/stream1


cameras:
  driveway:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://***:***@xxx/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://***:***@xxx/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
        mode: all

  lounge_1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://***:***@xxx/stream2
          roles:
            - detect
        - path: rtsp://***:***@xxx/stream1
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
        mode: all
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a
