### ISSUE TITLE
[Camera Support]: How important is the detection resolution (i.e., substream at 640x480 or main stream at 4MP)?

### ISSUE THREAD

**Issue by mikeage** [blakeblackshear/frigate#6039]
### Describe the problem you are having

I've read https://docs.frigate.video/frigate/camera_setup, but I'm looking for some real world advice. I have a few cameras in my house, and people are normally somewhere in the range of 1/2 of the frame to about 1/5th or so.

My camera is an Amcrest IP4M-1051B. It's NTSC only (unlike my other Amcrests which are NTSC or PAL -- PAL gives me a slightly higher resolution), and offers the following resolutions for the main stream:

* 2560x1440
* 2304x1296
* 1920x1080
* 1280x960
* 1280x720
* 640x480

For the secondary stream, I can only choose 640x480. 

I want to use a higher quality stream for recording... ideally 2560x1440, but I can also go down to 1920x1080. Similarly, I'd like to run this at 15 fps. For the detection, I know it's recommended to use a lower bitrate, lower framerate, lower resolution stream, but is 640x480 too small? The page above is configured for 1280x720 for the substream, which is three times as many pixels as my VGA resolution substream... how critical is that? I'm trying to avoid the extra CPU overhead of transcoding the high res stream.

My assumption is that since it takes a 320x320 area, 640x480 is really not enough, but I don't know how true this conclusion is.

I know the only completely accurate answer is "try it and see". It seems fairly good, but I'm not really sure how many detections I'm missing, and I'd like to know if there are any official recommendations.

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: mosquitto.lan
  user: mqttuser
  password: XXXXXXXX

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  mode: motion  # Default is objects, meaning detection

ffmpeg:
  hwaccel_args: -c:v h264_qsv

objects:
  mask: 0,0,0,48,425,48,425,0
  track:
    - person
    - bird

motion:
  threshold: 50  # default 25
  contour_area: 50  # default 30

record:
  enabled: True
  retain:
    days: 2
    mode: all  # Maybe change to motion, probably not active_objects
  events:
    post_capture: 10  # Default is 5
    retain:
      default: 2  # Default is 10 days

snapshots:
  enabled: True
  bounding_box: True


go2rtc:
  streams:
    Living_Room:
      - rtsp://admin:XXXXXXXX@amc0582cdbea48.lan:554/cam/realmonitor?channel=1&subtype=0
    Living_Room_sub:
      - rtsp://admin:XXXXXXXX@amc0582cdbea48.lan:554/cam/realmonitor?channel=1&subtype=1

cameras:
  Living_Room:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/Living_Room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Living_Room
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
ffprobe 'rtsp://admin:XXXXXXXX@amc0582cdbea48.lan:554/cam/realmonitor?channel=1&subtype=0'
ffprobe version 5.1.3 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r4) 20220924
  configuration: --prefix=/usr --enable-avfilter --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --disable-lzma --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --enable-libzmq --optflags=-O2 --disable-debug --enable-libsvtav1
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://admin: XXXXXXXX@amc0582cdbea48.lan:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2560x1440, 100 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp

For the substream, it returns 

  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x480, 5 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Amcrest IP4M-1051B
