### ISSUE TITLE
[Support]: Nginx not found (0.12 update)

### ISSUE THREAD

**Issue by boehser-enkel** [blakeblackshear/frigate#6043]
### Describe the problem you are having

Updated to 0.12 - frigate does not start anymore

### Version

0.12

### Frigate config file

```yaml
mqtt:
  host: 172.18.0.200
  user: mqtt_user
  password: pw..
  
 
detectors:
  coral:
    type: edgetpu
    device: usb
    
    
cameras:
  vorne:

    ffmpeg:
      inputs:
        - path: rtsp://192.168.88.66/live0
          roles:
            - detect
            - record
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128

    detect:
      width: 1920
      height: 1080
      
    record:
      enabled: True
      retain:
        days: 7
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
          


    snapshots:
      enabled: True      
      
    motion:
      mask:
        - 0,0,1920,0,1920,551,1079,360,1043,611,996,824,869,944,704,940,724,405,312,405,331,669,416,671,504,1080,0,1080

        

objects:

  track:
    - person
  mask:
    - 0,0,1920,0,1920,551,1079,360,1043,611,853,602,852,883,721,873,724,405,312,405,331,669,416,671,504,1080,0,1080
    - 1770,391,1495,268,1454,632,1714,711
    
  filters:
    person:
      min_area: 2500
      max_area: 5000000
      min_score: 0.5
      threshold: 0.75

  
birdseye:
  quality: 8
  mode: objects
  
rtmp:

  enabled: true



live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 1080
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
```

### Relevant log output

```shell
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-04-13 13:13:43.023414293  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-04-13 13:13:43.023836788  [INFO] Starting Frigate...
2023-04-13 13:13:43.025004254  [INFO] Starting NGINX...
2023-04-13 13:13:43.025031983  ./run.user: line 13: exec: nginx: not found
s6-rc: info: service legacy-services successfully started
2023-04-13 13:13:43.026880232  [INFO] Service NGINX exited with code 127 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2023-04-13 13:13:43.030722568  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-04-13 13:13:43.031484163  [INFO] Service Frigate exited with code 256 (by signal 15)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service frigate-log successfully stopped
2023-04-13 13:13:43.033700707  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Eufy
