### ISSUE TITLE
[Support]: Cannot get proxy to start

### ISSUE THREAD

**Issue by bigthrilla** [blakeblackshear/frigate#6047]
### Describe the problem you are having

Installed proxy addon, set configuration (frigate IP:port).  Does not start, couldn't find a way to grab the container logs and continue troubleshooting.  Have uninstalled/reinstalled, updated my config to get frigate back to running on port 5000 (did a side/side while runnning the v12 betas) all to no avail.
Running frigate 12 (DA3E197).  Was not running the proxy before, but thought after going to 12 it was time.

Thanks in advanced!

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.1.34:5000/api/config/schema.json

mqtt:
  enabled: False

record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 21

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 60

objects:
  track:
    - person
    - car
    - bus
    - bicycle
    - cat
    - dog

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args: 
    record: preset-record-generic-audio-aac

go2rtc:

  streams:
    front_yard:
      - rtsp://user:pass@192.168.1.70:554//h264Preview_01_main
    front_yard_sub:
      - rtsp://user:pass@192.168.1.70:554//h264Preview_01_sub
    deck:
      - rtsp://user:pass@192.168.1.71:554//h264Preview_01_main
    deck_sub:
      - rtsp://user:pass@192.168.1.71:554//h264Preview_01_sub
    pink:
      - rtsp://user:pass@192.168.2.201:554//h264Preview_01_main
    pink_sub:
      - rtsp://user:pass@192.168.2.201:554//h264Preview_01_sub
    quonset: 
      - rtsp://user:pass@192.168.2.202:554//h264Preview_01_main
    quonset_sub: 
      - rtsp://user:pass@192.168.2.202:554//h264Preview_01_sub
    deck_doorbell:
      - rtsp://admin:bigthrilla13@192.168.1.72:554/
    deck_doorbell_sub:
      - rtsp://admin:bigthrilla13@192.168.1.72:554/cam/realmonitor?channel=1&subtype=1
    west:
      - rtsp://user:pass@192.168.1.75:554//h264Preview_01_main
    west_sub:
      - rtsp://user:pass@192.168.1.75:554//h264Preview_01_sub
  webrtc:
    candidates:
      - 192.168.1.34:8555
      - stun:8555

cameras:

  ####################
  # FRONT YARD ####### 
  ####################
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_yard_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 640,0,0,0,0,97,71,109,90,195,200,186,201,102,224,70,281,75,329,105,318,140,351,203,407,172,410,228,432,241,454,206,508,277,640,380

  ####################
  # DECK DOORBELL #### 
  ####################
  deck_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck_doorbell_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/deck_doorbell
          roles:
            - record
          # input_args:
          #   - -c:v
          #   - h264_cuvid
    detect:
      width: 720
      height: 576
      fps: 5          
    motion:
      mask:
        - 720,0,0,0,0,309,223,290,283,310,404,294,426,282,482,264,638,272,720,288
        - 393,436,506,428,503,403,394,404
        - 213,364,247,408,230,426,191,378
    objects:
      filters:
        car:
          mask: 
            - 0,576,0,464,216,417,480,426,720,372,720,576
            - 596,287,680,278,683,313,603,324 #white car parked

  ##############
  # DECK ####### 
  ##############
  deck:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/deck
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/deck_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 4
    motion:
      mask:
        - 640,48,640,0,339,0,0,0,0,107,248,54,247,124,313,116,358,114,384,131,436,145,474,123,510,122,562,131,573,117,586,131,612,129,640,118
    # zones:
    #   deck_zone:
    #     coordinates: 526,480,640,206,394,153,0,291,0,480
    #     objects:
    #         - person
    #         - bicycle
    #         - cat
    #         - dog
    objects:
      filters:
        car:
          mask: 
            - 526,480,640,206,388,164,0,313,0,480
            - 321,77,336,119,209,141,207,94 #white car parked
  west:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/west
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/west_sub
          roles:
            - detect
    detect:
      width: 1536
      height: 576
      fps: 4
    motion:
      mask:
        - 0,0,526,0,1536,0,1536,324,1404,248,1360,205,1115,101,850,59,699,49,448,97,321,135,271,148,0,306
    objects:
      filters:
        car:
          mask: 
            - 1536,349,1384,295,1344,373,1445,430 #white car parked
        

  pink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/pink
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/pink_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 78,214,117,265,157,309,127,338,71,294,0,290,0,234
        - 224,364,243,480,0,480,0,397
        - 640,0,517,0,426,164,393,160,362,174,405,199,640,243,640,237
        - 133,0,259,0,284,31,302,69,302,96,287,121,260,143,207,142,169,131,140,82
        - 112,98,83,129,47,138,0,142,0,60,0,0,160,0,147,90
        - 491,0,184,0,176,36,496,46

  quonset:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/quonset
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/quonset_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 640,480,640,193,290,480
        - 328,0,640,0,640,148,614,128,552,85,517,107
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Frigate Proxy
 Proxy addon for Frigate
-----------------------------------------------------------
 Add-on version: 1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.4.3
 Home Assistant Supervisor: 2023.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:15:38] INFO: Starting NGinx...
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"111":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"139":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"150":{"cpu":"0.0","mem":"0.0"},"163":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"186":{"cpu":"0.0","mem":"0.0"},"206":{"cpu":"0.0","mem":"0.0"},"227":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"253":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"275":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"306":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"573":{"cpu":"0.0","mem":"0.3"},"578":{"cpu":"0.0","mem":"0.0"},"579":{"cpu":"13.6","mem":"1.7"},"581":{"cpu":"1.3","mem":"0.3"},"586":{"cpu":"9.0","mem":"0.3"},"587":{"cpu":"0.0","mem":"0.0"},"588":{"cpu":"1.0","mem":"0.3"},"589":{"cpu":"8.3","mem":"0.3"},"590":{"cpu":"0.7","mem":"0.3"},"591":{"cpu":"12.0","mem":"0.3"},"592":{"cpu":"0.3","mem":"0.3"},"593":{"cpu":"1.3","mem":"0.3"},"597":{"cpu":"1.0","mem":"0.3"},"600":{"cpu":"1.3","mem":"0.4"},"601":{"cpu":"1.0","mem":"0.3"},"602":{"cpu":"1.7","mem":"0.4"},"605":{"cpu":"1.3","mem":"0.3"},"606":{"cpu":"4.3","mem":"0.5"},"609":{"cpu":"1.0","mem":"0.3"},"612":{"cpu":"2.0","mem":"0.5"},"619":{"cpu":"0.7","mem":"0.3"},"621":{"cpu":"1.0","mem":"0.5"},"623":{"cpu":"0.0","mem":"0.0"},"626":{"cpu":"3.7","mem":"0.1"},"628":{"cpu":"3.3","mem":"0.1"},"629":{"cpu":"2.3","mem":"0.0"},"630":{"cpu":"3.3","mem":"0.1"},"631":{"cpu":"1.0","mem":"0.4"},"634":{"cpu":"0.7","mem":"0.0"},"637":{"cpu":"0.0","mem":"0.0"},"638":{"cpu":"2.3","mem":"0.0"},"639":{"cpu":"0.0","mem":"0.0"},"640":{"cpu":"0.0","mem":"0.0"},"641":{"cpu":"0.0","mem":"0.0"},"642":{"cpu":"0.0","mem":"0.1"},"7883":{"cpu":"0.0","mem":"0.0"},"7887":{"cpu":"0.0","mem":"0.0"},"7920":{"cpu":"0.7","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"23.3","mem":"0.0"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"19.6","mem":"0.9"},"MiB":{"cpu":"32787.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"0","mem":"users,"}},"deck":{"camera_fps":4.1,"capture_pid":601,"detection_enabled":1,"detection_fps":5.0,"ffmpeg_pid":606,"pid":589,"process_fps":4.0,"skipped_fps":0.0},"deck_doorbell":{"camera_fps":5.0,"capture_pid":597,"detection_enabled":1,"detection_fps":2.4,"ffmpeg_pid":602,"pid":588,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":15.2,"detectors":{"tensorrt":{"detection_start":0.0,"inference_speed":7.63,"pid":579}},"front_yard":{"camera_fps":5.1,"capture_pid":593,"detection_enabled":1,"detection_fps":3.2,"ffmpeg_pid":600,"pid":586,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"NVIDIA GeForce GTX 1050 Ti":{"gpu":"11 %","mem":"38.0 %"}},"pink":{"camera_fps":5.2,"capture_pid":609,"detection_enabled":1,"detection_fps":3.2,"ffmpeg_pid":621,"pid":591,"process_fps":5.2,"skipped_fps":0.0},"quonset":{"camera_fps":5.1,"capture_pid":619,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":631,"pid":592,"process_fps":5.1,"skipped_fps":0.0},"service":{"last_updated":1681396102,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":260.5,"mount_type":"tmpfs","total":268.4,"used":8.0},"/media/frigate/clips":{"free":2040213.0,"mount_type":"fuse.shfs","total":3999810.2,"used":1959597.2},"/media/frigate/recordings":{"free":2040213.0,"mount_type":"fuse.shfs","total":3999810.2,"used":1959597.2},"/tmp/cache":{"free":50.8,"mount_type":"tmpfs","total":100.0,"used":49.2}},"temperatures":{},"uptime":958,"version":"0.12.0-da3e197"},"west":{"camera_fps":4.0,"capture_pid":605,"detection_enabled":1,"detection_fps":1.4,"ffmpeg_pid":612,"pid":590,"process_fps":4.0,"skipped_fps":0.0}}
```

### Operating system

HassOS

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink (various), lorex

### Any other information that may be helpful

No Coral, but using TensorRT
