### ISSUE TITLE
[Config Support]: Snapshot to be taken earlier 

### ISSUE THREAD

**Issue by andrewhack** [blakeblackshear/frigate#6051]
### Describe the problem you are having

I have 3 zones - 2 of them are detecting car - blue and orange:
https://drive.google.com/file/d/1Ecr8wvJdO-KOX1R-2hQtd-v88QBWQ-kf/view?usp=share_link
The snapshot which is generated is always between the zones - when the car is the best position I assume - the event show the both zones:
https://drive.google.com/file/d/1BUs9IgDxUn4J7w4fr20gY9It9FonYLAl/view?usp=share_link
What I want to achieve: the snapshot to be from the exact zone. Already tried max_area: 300000 but no luck
Any suggestions?
 

### Version

0.12

### Frigate config file

```yaml
cameras:
  crosstreet:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/crosstreet
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    rtmp:
      enabled: False
    snapshots:
      quality: 100
      enabled: true
      timestamp: True
      bounding_box: true
      retain:
        default: 15
      required_zones:
        - downstreet
        - upstreet
        - middlestreet

    objects:
      filters:
        bicycle:
          mask:
            - 267,344,527,197,462,41,215,143
            - 875,163,956,81,1111,131,1075,261
        car:
          max_area: 300000
          mask:
            - 267,344,527,197,462,41,215,143
            - 875,163,956,81,1111,131,1075,261
        motorcycle:
          mask:
            - 267,344,527,197,462,41,215,143
            - 875,163,956,81,1111,131,1075,261
        person:
          mask:
            - 267,344,527,197,462,41,215,143
            - 875,163,956,81,1111,131,1075,261
        truck:
          max_area: 500000
          mask:
            - 267,344,527,197,462,41,215,143
            - 875,163,956,81,1111,131,1075,261
    motion:
      mask:
        - 0,720,61,720,293,0,0,0
        - 1280,142,1280,0,963,0
    zones:
      downstreet:
        coordinates: 260,585,646,305,495,232,262,355
        objects:
          - person
          - bicycle
          - motorcycle
          - car
          - truck
      upstreet:
        coordinates: 719,297,849,185,1022,266,1001,452
        objects:
          - person
          - bicycle
          - motorcycle
          - car
          - truck
      middlestreet:
        coordinates: 139,720,1280,720,999,481,689,309
        objects:
          - person
          - bicycle
          - motorcycle
```

### Relevant log output

```shell
not relevant
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB
