### ISSUE TITLE
[Support]:  usb cam hardware acceleration

### ISSUE THREAD

**Issue by parttimer777** [blakeblackshear/frigate#6056]
### Describe the problem you are having

Hi,

I'm using a USB cam to record footage (1 day retention) and that works but work is being done on the CPU.

I understand hw accel is enabled with these 2 options: `        "-hwaccel",
        "cuda",
        "-hwaccel_output_format",
        "cuda",`

However, the presence of "hwaccel_output_format" makes the process throw errors. 

I've simplified the output_args/record to this: 

` record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -pix_fmt yuv420p`

Which results in this error:

```
cam: ffmpeg process is not running. exiting capture thread...
Failed to probe corrupt segment /tmp/cache/cam-20230413142522.
 Invalid data found when processing input\n'
Discarding a corrupt recording segment: /tmp/cache/cam-2023041

Error occurred when attempting to maintain recording cache
list index out of range
```

Wondering if anyone has suggestions for usb cam + nvidia hw accel.

Thanks

p.s.

I have some other cams with specific requirements for record output so i modify the filter -vf. Generally when that happens i have to remove hwaccel_output_format because custom filters dont jive with that.

Is it possible to turn on logging to show the exact ffmpeg commands that are being run? i would like to learn more about the relationship of hwaccel_args, input_args, and output_args (detect & record). Perhaps i can run the ffmpeg commands ad-hoc and troubleshoot that way.

### Version

latest

### Frigate config file

```yaml
ffmpeg:
  global_args: -hide_banner -loglevel info
  hwaccel_args: preset-nvidia-h264

cameras:
  cam:
    ffmpeg:
      inputs:
      - path: /dev/video0
        roles:
          - detect
          - record

        input_args: -avoid_negative_ts make_zero -strict normal -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      hwaccel_args: -hwaccel cuda
      output_args:
        record: "-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -pix_fmt yuv420p -vf \"setpts=0.5*PTS, drawtext=fontfile=/config/DejaVuSansMono.ttf: text='%{localtime}': x=(w-tw)/2: y=h-(2*lh): fontcolor=white: box=1: boxcolor=0x00000000@1: fontsize=20\""

    detect: 
      enabled: False

    record:
      enabled: True
      retain: 
        days: 1
        mode: all

    snapshots:
      enabled: False
```

### Relevant log output

```shell
frigate-frigate-1  | 2023-04-13 14:09:35.143250782  [2023-04-13 14:09:35] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate-frigate-1  | 2023-04-13 14:09:35.143386264  [2023-04-13 14:09:35] frigate.record                 ERROR   : list index out of range
```

### FFprobe output from your camera

```shell
I'm not sure this works on the USB cams. I've seen output from this show up on a rtsp. Tried it on the usb cam and it didnt get passed the spinner.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

logitech brio usb
