### ISSUE TITLE
Zone folder library named with non ASCII characters is empty in Media Browser

### ISSUE THREAD

**Issue by artlov** [blakeblackshear/frigate#606]
**Describe the bug**
Non ASCII named zone ("autovärav" in my case) folder in Media Player Browser is empty. Header shows that it have clips inside (8), but folder is empty when open it. Library's clips list with other zones named with ASCII characters only (Parkimine, Trepp) works correctly.

**Version of frigate**
Latest beta (0.8.0-rc5-amd64)

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
 hik2:
    ffmpeg:
      inputs:
        - path: 'rtsp://user:pass@192.168.2.36:554/Streaming/Channels/102'
          roles:
            - detect
            - rtmp
        - path: 'rtsp://user:pass@192.168.2.36:554/Streaming/Channels/101'
          roles:
            - clips
            - record
    height: 360
    width: 640
    fps: 6
    zones:
      autovärav:
        coordinates: '0,360,280,360,299,120,280,0,0,48,58,150'
    clips:
      enabled: true
    record:
      enabled: true
      retain_days: 2
    snapshots:
      enabled: true
    detect:
      enabled: true
      max_disappeared: 10
```

**Screenshots**
![Kuvatõmmis 2021-01-25 223654](https://user-images.githubusercontent.com/6746304/105763231-37a42180-5f5e-11eb-9fb3-5e2b2747cd30.png)
![Kuvatõmmis 2021-01-25 223730](https://user-images.githubusercontent.com/6746304/105763262-425eb680-5f5e-11eb-9b23-3196bd721d5d.png)

**Computer Hardware**
 - OS: Debian 10
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: DS-2CD2742FWD-IZS
 - Resolution: 1080p
 - FPS: 6

**Additional context**
