### ISSUE TITLE
[Config Support]: ValueError: Config input objects is defined multiple times for the same field, this is not allowed.

### ISSUE THREAD

**Issue by leecosta466** [blakeblackshear/frigate#6060]
### Describe the problem you are having

Just finished upgrading to the new version and this errors appears on startup. I am not sure what I need to change.

### Version

0.12

### Frigate config file

```yaml
##########################################################
## Driveway
##########################################################

cameras:
  driveway_cam:
    rtmp:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record

    detect:
      width: 3840
      height: 2160
      fps: 10
      enabled: True

    zones:
      driveway:
        coordinates: 2141,2160,1881,1405,2067,1347,3840,1796,3840,2160
        objects:
          - person
          - animal
      street:
        coordinates: 2528,1432,2806,1297,3840,1545,3840,1761
        objects:
          - person
          - animal
          - car

    objects:
      track:
        - person
        - animal
        - car
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 40000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          mask:
            - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0
        car:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 200000
          mask:
            - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0
        animal:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1000
          mask:
            - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0

    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25

      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30
      mask:
       - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
#        max_seconds: 240 Deprecated in 0.11
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person
          - car
          - animal
        required_zones:
          - driveway
          - street

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      required_zones:
        - driveway
        - street
      retain:
        default: 7

##########################################################
## Backyard
##########################################################

  backyard_cam:
    rtmp:
      enabled: False

    detect:
      width: 3840
      height: 2160
      fps: 10
      enabled: True

    motion:
      # Increasing this value will make motion detection less sensitive
      threshold: 30
      # default 25

      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35 
      # default: 30

      mask:
        - 3840,600,3538,538,3434,1293,2992,1173,3012,705,2268,712,1363,782,1068,848,1130,1173,852,1231,790,890,225,1130,0,1215,0,0,3840,0
        - 3840,1966,3840,2160,3163,2160,3163,1970
        - 3782,1374,3751,1634,3488,1560,3538,1308
        - 2775,1359,3050,1537,3205,1301,2938,1212

    objects:
      track:
        - person
        - animal
      filters:
        animal:
          min_area: 1000
          max_area: 100000
          mask:
            - 3840,600,3314,511,3290,1185,2992,1095,3012,705,2268,712,1363,782,1068,848,1130,1173,852,1231,790,890,225,1130,0,1215,0,0,3840,0
            - 3840,1966,3840,2160,3163,2160,3163,1970
            - 3782,1374,3751,1634,3488,1560,3538,1308
            - 2880,1347,3046,1463,3205,1301,2938,1212
        person:
          min_area: 10000
          # max_area: 100000
          mask:
            - 3840,600,3314,511,3290,1185,2992,1095,3012,705,2268,712,1363,782,1068,848,1130,1173,852,1231,790,890,225,1130,0,1215,0,0,3840,0
            - 3840,1966,3840,2160,3163,2160,3163,1970
            - 3782,1374,3751,1634,3488,1560,3538,1308
            - 2880,1347,3046,1463,3205,1301,2938,1212
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record

    record:
      enabled: True
      retain:
        days: 7
        mode: active_objects
      events:
#        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person
          - animal

##########################################################
## Living Room
##########################################################

  living_room_cam:
    rtmp:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.16:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record

    motion:
      mask:
        - 1641,207,1661,615,1239,586,1250,267
        - 1862,0,1434,0,1440,99,1860,105

    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 1641,207,1661,615,1239,586,1250,267
            - 1862,0,1434,0,1440,99,1860,105

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True

    objects:
      track:
        - person

    record:
      enabled: True
      retain:
        days: 0
        # mode: active_objects
      events:
#        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person

#########################################################
## Global
#########################################################

mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED
  

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 7

#model:
#  labelmap:
#    15: animal
#    16: animal
#    17: animal
#    18: animal
#    19: animal
#    20: animal
#    21: animal
#    22: animal
#    23: animal
#    24: animal

birdseye:
  enabled: False
  # width: 1920
  # height: 1080
  # quality: 8
  # mode: motion
```

### Relevant log output

```shell
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2023-04-13 16:41:25.977977926  [INFO] Starting NGINX...
frigate    | 2023-04-13 16:41:25.990030354  [INFO] Preparing go2rtc config...
frigate    | 2023-04-13 16:41:25.992692864  [INFO] Starting Frigate...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2023-04-13 16:41:26.125905924  [INFO] Starting go2rtc...
frigate    | 2023-04-13 16:41:26.219164997  16:41:26.219 INF go2rtc version 1.2.0 linux/amd64
frigate    | 2023-04-13 16:41:26.220306064  16:41:26.219 INF [api] listen addr=:1984
frigate    | 2023-04-13 16:41:26.220579474  16:41:26.220 INF [rtsp] listen addr=:8554
frigate    | 2023-04-13 16:41:26.220943304  16:41:26.220 INF [srtp] listen addr=:8443
frigate    | 2023-04-13 16:41:26.222147385  16:41:26.222 INF [webrtc] listen addr=:8555
frigate    | 2023-04-13 16:41:26.662997099  [2023-04-13 16:41:26] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
frigate    | 2023-04-13 16:41:26.680313124  *************************************************************
frigate    | 2023-04-13 16:41:26.680316461  *************************************************************
frigate    | 2023-04-13 16:41:26.680319162  ***    Your config file is not valid!                     ***
frigate    | 2023-04-13 16:41:26.680320888  ***    Please check the docs at                           ***
frigate    | 2023-04-13 16:41:26.680322230  ***    https://docs.frigate.video/configuration/index     ***
frigate    | 2023-04-13 16:41:26.680380470  *************************************************************
frigate    | 2023-04-13 16:41:26.680413546  *************************************************************
frigate    | 2023-04-13 16:41:26.680414722  ***    Config Validation Errors                           ***
frigate    | 2023-04-13 16:41:26.680415729  *************************************************************
frigate    | 2023-04-13 16:41:26.680416795  Config input objects is defined multiple times for the same field, this is not allowed.
frigate    | 2023-04-13 16:41:26.681470375  Traceback (most recent call last):
frigate    | 2023-04-13 16:41:26.681472777    File "/opt/frigate/frigate/app.py", line 351, in start
frigate    | 2023-04-13 16:41:26.681473688      self.init_config()
frigate    | 2023-04-13 16:41:26.681474699    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate    | 2023-04-13 16:41:26.681475647      user_config = FrigateConfig.parse_file(config_file)
frigate    | 2023-04-13 16:41:26.681476653    File "/opt/frigate/frigate/config.py", line 1068, in parse_file
frigate    | 2023-04-13 16:41:26.681477643      config = load_config_with_no_duplicates(raw_config)
frigate    | 2023-04-13 16:41:26.681479503    File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
frigate    | 2023-04-13 16:41:26.681481185      return yaml.load(raw_config, PreserveDuplicatesLoader)
frigate    | 2023-04-13 16:41:26.681482300    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate    | 2023-04-13 16:41:26.681503088      return loader.get_single_data()
frigate    | 2023-04-13 16:41:26.681504315    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
frigate    | 2023-04-13 16:41:26.681505454      return self.construct_document(node)
frigate    | 2023-04-13 16:41:26.681506582    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 55, in construct_document
frigate    | 2023-04-13 16:41:26.681514144      data = self.construct_object(node)
frigate    | 2023-04-13 16:41:26.681515334    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
frigate    | 2023-04-13 16:41:26.681516362      data = constructor(self, node)
frigate    | 2023-04-13 16:41:26.681517361    File "/opt/frigate/frigate/util.py", line 63, in map_constructor
frigate    | 2023-04-13 16:41:26.681518397      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
frigate    | 2023-04-13 16:41:26.681519652    File "/opt/frigate/frigate/util.py", line 63, in <listcomp>
frigate    | 2023-04-13 16:41:26.681520765      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
frigate    | 2023-04-13 16:41:26.681521891    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
frigate    | 2023-04-13 16:41:26.681529444      data = constructor(self, node)
frigate    | 2023-04-13 16:41:26.681530498    File "/opt/frigate/frigate/util.py", line 63, in map_constructor
frigate    | 2023-04-13 16:41:26.681531561      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
frigate    | 2023-04-13 16:41:26.681532884    File "/opt/frigate/frigate/util.py", line 63, in <listcomp>
frigate    | 2023-04-13 16:41:26.681533963      vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
frigate    | 2023-04-13 16:41:26.681535085    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
frigate    | 2023-04-13 16:41:26.681544044      data = constructor(self, node)
frigate    | 2023-04-13 16:41:26.681545072    File "/opt/frigate/frigate/util.py", line 68, in map_constructor
frigate    | 2023-04-13 16:41:26.681545937      raise ValueError(
frigate    | 2023-04-13 16:41:26.681547057  ValueError: Config input objects is defined multiple times for the same field, this is not allowed.
frigate    | 2023-04-13 16:41:26.681548007  
frigate    | 2023-04-13 16:41:26.681549049  *************************************************************
frigate    | 2023-04-13 16:41:26.681550023  ***    End Config Validation Errors                       ***
frigate    | 2023-04-13 16:41:26.681551027  *************************************************************
frigate    | 2023-04-13 16:41:27.791608880  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | 2023-04-13 16:41:27.801719218  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2023-04-13 16:41:27.843787203  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | 2023-04-13 16:41:27.847239550  exit OK
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | 2023-04-13 16:41:27.851700587  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 1
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
