### ISSUE TITLE
[HW Accel Support]: black video stream after after updating to 0.12.0 and changing hw_accel to preset-vaapi

### ISSUE THREAD

**Issue by pejotigrek** [blakeblackshear/frigate#6061]
### Describe the problem you are having

hardware acceleration stopped working after updating to 0.12.0.
in the earlier versions I used below setting (quoted only the part for hw accel):

```yaml
(...)
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
(...)
```

when moved to 0.12.0 this stopped working (stream was black-blank) so I've checked the documentation and changed ffmpeg settings to fit new presets but with no luck. stream still is black.

my CPU/GPU hardware is quadcore AMD GX-415GA SOC with Radeon HD 8330E.

there's nothing special in the log - I didn't saw any errors there. 
if I remove the hwaccel_args line - everything works, stream is correctly displayed.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.4
  port: 1883
  topic_prefix: frigate12
  client_id: frigate12
  user: #redacted#
  password: #redacted#
  stats_interval: 60

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

live:
  height: 480
  quality: 15

timestamp_style:
  position: "tr"
  format: "%Y.%m.%d, %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid

detect:
  enabled: false
  width: 640
  height: 360
  fps: 5
  max_disappeared: 25

objects:
  track:
  - person
  - car
  - dog
  filters:
    person:
      min_area: 5000
      max_area: 80000
      min_score: 0.5
      threshold: 0.6
    dog:
      min_area: 800
      max_area: 40000
      min_score: 0.45
      threshold: 0.5

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 3
    objects:
      person: 7

rtmp:
  enabled: false

record:
  enabled: true
  retain:
    days: 3
    mode: active_objects
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 3
      mode: active_objects
      objects:
        person: 7

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic
  output_args:
    record: preset-record-generic
    rtmp: preset-rtmp-generic

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: continuous

cameras:
  3_out_entrance:
    ffmpeg:
      inputs:
      - path: rtsp://192.168.2.6:8554/streaming
        roles:
        - detect
        - record
        - rtmp
    best_image_timeout: 30
    motion:
      threshold: 15
      contour_area: 50
      delta_alpha: 0.3
      frame_height: 240
      mask:
      - 301,194,532,0,0,0,0,768,1024,768,1024,0,624,0,656,287,772,494,806,395,856,406,728,744,633,729,574,768,376,640,396,597,121,396
    detect:
      width: 1024
      height: 768
    objects:
      track:
      - person
      filters:
        person:
          mask:
          - 144,411,574,0,0,0,0,768,1024,768,1024,0,626,0,662,283,738,437,655,692,588,736,365,645,380,602
          min_area: 26000
          max_area: 70000
    zones:
      delivery_zone:
        coordinates: 621,732,670,739,730,735,792,601,852,431,762,463
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'
services:
  frigate12:
    container_name: frigate12
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
    - /dev/dri/renderD128
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/peejay/docker_volumes/frigate_12:/config:ro
    - /home/peejay/docker_volumes/frigate_12/media:/media/frigate
    - type: tmpfs
      target: /tmp/cache
      tmpfs:
        size: 1000000000
    ports:
    - 8087:5000
    - 1937:1935
    - 8574:8554
    - 8575:8555/tcp
    - 8575:8555/udp
    environment:
      LIBVA_DRIVER_NAME: radeonsi
networks:
  default:
    name: hassio
    external: true
```

### Relevant log output

```shell
2023-04-13 23:38:12.033983093  [INFO] Starting Frigate...
2023-04-13 23:38:18.406659103  [2023-04-13 23:38:18] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-13 23:38:18.566911154  [2023-04-13 23:38:18] peewee_migrate                 INFO    : Starting migrations
2023-04-13 23:38:18.584424174  [2023-04-13 23:38:18] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-13 23:38:18.643949960  [2023-04-13 23:38:18] detector.cpu                   INFO    : Starting detection process: 292
2023-04-13 23:38:18.670940423  [2023-04-13 23:38:18] frigate.app                    INFO    : Output process started: 294
2023-04-13 23:38:18.670962152  [2023-04-13 23:38:18] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-04-13 23:38:18.681593448  [2023-04-13 23:38:18] frigate.app                    INFO    : Camera processor started for 3_out_entrance: 297
2023-04-13 23:38:18.696440343  [2023-04-13 23:38:18] frigate.app                    INFO    : Capture process started for 3_out_entrance: 299
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":768,"width":1024}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":768,"width":1024}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Mixed

### Camera make and model

config & probe is from RPi0 with dedicated camera module; but the problem exists with different cameras too

### Any other information that may be helpful

above configuration and ffprobe is from one camera only - I am running v0.12.0 in additional container just to test the configuration (that's why ports in docker-compose are slightly different). my "production environment" with v0.11 is running 4 cameras with no issues - including the one RPi0-based mentioned earlier.

additional VAINFO output (if needed):

```json
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:MesaGalliumdriver22.3.6forKABINI(,LLVM15.0.6,DRM2.50,5.15.0-69-generic)nvainfo:SupportedprofileandentrypointsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG4Simple:tVAEntrypointVLDnVAProfileMPEG4AdvancedSimple:tVAEntrypointVLDnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileNone:tVAEntrypointVideoProc"}
```
