### ISSUE TITLE
[Config Support]: Camera is not creating recordings

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#6062]
### Describe the problem you are having

I have two cameras, Driveway and Front Porch. Driveway takes snapshots and recordings (clipls). Front Porch only takes Snapshots, it does not create recordings.

I am unable to toggle it from the UI for this camera.

![image](https://user-images.githubusercontent.com/7737834/231890555-0934a781-4b22-431a-b3ac-c88f02c8d2f4.png)

### Version

Frigate (Full Access) Beta (0.12.0)

### Frigate config file

```yaml
snapshots:
  enabled: True
    
record:
  enabled: True
  events:
    retain:
      default: 10
        
cameras:
  front_porch:
    motion:
      mask:
        - 0,0,0,74,70,52,173,32,274,29,416,33,530,57,653,92,704,85,704,0
    zones:
      front_street:
        coordinates: 139,39,163,31,206,36,247,23,327,25,416,34,515,51,592,72,644,89,674,97,658,172,634,163,566,138,443,112,286,76,144,86,142,66
        objects:
          - person
          - car
          - dog
      front_porch_area:
        coordinates: 0,480,0,76,140,41,140,82,258,86,430,111,652,172,704,90,704,480
        objects:
          - person
          - dog
    snapshots:
      required_zones:
        - front_street
        - front_porch_area
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

  driveway:
    motion:
      mask:
        - 0,0,704,0,704,166,0,184
    ffmpeg:
      inputs:
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:@192.168.1.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    zones:
      front_street:
        coordinates: 0,250,704,239,704,170,0,181
        objects:
          - person
          - car
          - dog
      driveway_area:
        coordinates: 704,480,0,480,0,236,704,233        
        objects:
          - person
          - car
          - dog
    objects:
      filters:
        car:
          mask:            
            - 569,335,677,339,676,258,566,261
    snapshots:
      required_zones:
        - front_street
        - driveway_area
```

### Relevant log output

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB
