### ISSUE TITLE
[Config Support]: how to solve this error please?

### ISSUE THREAD

**Issue by luciandf** [blakeblackshear/frigate#6064]
### Describe the problem you are having

I keep getting the error below in the description. I am completely new at this docker (I am using Portainer because I am trying to follow a tutorial I found here: https://github.com/blakeblackshear/frigate/files/9737633/Installing.frigate.from.scratch.pdf) and frigate. I feel like I am close but this error doesn't tell me anything and have no idea where to look. When I start the container I get a webpage but I get a loading circle and then an error unable to connect.

Can anyone help me figure this out please?

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.67
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: SECRET
  password: MORE SECRET
  stats_interval: 60

detectors:
  coral:
    type: edgetpu

database:
  path: /home/lucian/frigate/db/frigate.db

logger:
  default: info
  logs:
    frigate.event: debug

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  hwaccel_args: []
  input_args: preset-rtsp-generic
  output_args:
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    record: preset-record-generic
    rtmp: preset-rtmp-generic

detect:
  width: 1280
  height: 720
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

objects:
  track:
    - person
  mask: 0,0,1000,0,1000,200,0,200
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.7
      mask: 0,0,1000,0,1000,200,0,200

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mask: 0,900,1080,900,1080,1920,0,1920
  improve_contrast: False
  mqtt_off_delay: 30

record:
  expire_interval: 60
  retain:
    days: 14
    mode: motion
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: []
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  clean_copy: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: "solid"

cameras:
  gate:
    ffmpeg:
      inputs:
        - path: rtsp://admin:ANOTHERSECRET@192.168.1.85:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
            - record
            - rtmp
    best_image_timeout: 60

    zones:
      front_steps:
        coordinates: 545,1077,747,939,788,805
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    mqtt:
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

    ui:
      order: 0
      dashboard: True
  veranda:
    ffmpeg:
      inputs:
        - path: rtsp://admin:ANOTHERSECRET@192.168.1.94:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
            - record
            - rtmp
    best_image_timeout: 60

    zones:
      front_steps:
        coordinates: 545,1077,747,939,788,805
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    mqtt:
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
      required_zones: []

    ui:
      order: 0
      dashboard: True

telemetry:
  version_check: True
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2023-04-14 03:13:07] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)

*************************************************************

*************************************************************

***    Your config file is not valid!                     ***

***    Please check the docs at                           ***

***    https://docs.frigate.video/configuration/index     ***

*************************************************************

*************************************************************

***    Config Validation Errors                           ***

*************************************************************

1 validation error for FrigateConfig
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe
