### ISSUE TITLE
[Detector Support]: Frigate doesn't detect Nvidia GPU

### ISSUE THREAD

**Issue by weitheng** [blakeblackshear/frigate#6066]
### Describe the problem you are having

Frigate isn't able to detect NVIDIA GPU following a host restart specifically giving me error `AssertionError: Failed to initialize cuda 999`,I have tried running `nvidia-smi -r` to reset the GPU, but frigate still doesn't detect NVIDIA GPU. It seems like the only way to fix it is to keep performing host restart until it starts detecting it again.

### Version

0.12.0

### Frigate config file

```yaml
# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/edgetpu_model.tflite"
      width: 320
      height: 320

# Optional: model modifications
model:
  # Optional: path to the model (default: automatic based on detector) /edgetpu_model.tflite
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
  labelmap_path: /labelmap.txt

# Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects

# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: preset-nvidia-h264
  # Optional: global input args (default: shown below)
  input_args: preset-rtsp-generic
#-avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: preset-record-generic
#-f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 704
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 576
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 5000
      # Optional: Object specific values
      objects:
        person: 3000

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
      - bus
      - dog
      - cat
      - motorcycle
      - bicycle
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 2
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
#  height: 175
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 2

# Required
cameras:
  Foyer:
    birdseye:
      mode: continuous
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.0.XXX:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://XXXX:XXXX@192.168.0.XXX:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - motorcycle
        - bus
        - bicycle
      filters:
        car:
          threshold: 0.55
    detect:
      fps: 10
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
      max_disappeared: 50
      # Optional: Configuration for stationary object tracking
      stationary:
        threshold: 100
    motion:
      threshold: 15
      contour_area: 20
```

### docker-compose file or Docker CLI command

```yaml
version: '3.9'

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    image: ghcr.io/blakeblackshear/frigate:0.12.0-tensorrt
    shm_size: "180mb" # update for your cameras based on calculation above
    # blakeblackshear/frigate:stable
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    runtime: nvidia
    volumes:
      - "/root/frigate/config/config.yml:/config/config.yml:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/frigate/trt-models:/trt-models"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 5000000000
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - '5000:5000'
      - "8554:8554"  # GO2RC stream
      - "8555:8555"
    environment:
      NVIDIA_DRIVER_CAPABILITIES: 'all'
```

### Relevant log output

```shell
2023-04-14 10:02:21.675956630  [2023-04-14 10:02:21] frigate.app                    INFO    : Output process started: 956
2023-04-14 10:02:21.678648626  [2023-04-14 10:02:21] detector.tensorrt              INFO    : Starting detection process: 955
2023-04-14 10:02:21.707058948  Process detector:tensorrt:
2023-04-14 10:02:21.707673016  [2023-04-14 10:02:21] frigate.app                    INFO    : Camera processor started for Foyer: 961
2023-04-14 10:02:21.708879609  [2023-04-14 10:02:21] frigate.app                    INFO    : Camera processor started for Gate: 962
2023-04-14 10:02:21.709099437  Traceback (most recent call last):
2023-04-14 10:02:21.709432855    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-04-14 10:02:21.709437950      self.run()
2023-04-14 10:02:21.709608815    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-04-14 10:02:21.709613059      self._target(*self._args, **self._kwargs)
2023-04-14 10:02:21.709844770    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-04-14 10:02:21.709848419      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-04-14 10:02:21.709969427    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-04-14 10:02:21.709972224      self.detect_api = create_detector(detector_config)
2023-04-14 10:02:21.710157127    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-04-14 10:02:21.710160620      return api(detector_config)
2023-04-14 10:02:21.710338975    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 203, in __init__
2023-04-14 10:02:21.710341611      assert (
2023-04-14 10:02:21.710584936  AssertionError: Failed to initialize cuda 999
2023-04-14 10:02:21.711034085  Exception ignored in: <function TensorRtDetector.__del__ at 0x7efceeee2700>
2023-04-14 10:02:21.711221985  Traceback (most recent call last):
2023-04-14 10:02:21.711535190    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-04-14 10:02:21.712237683      if self.outputs is not None:
2023-04-14 10:02:21.712627972  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:04:00.0 Off |                  N/A |
| 67%   51C    P0    26W / 105W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
