### ISSUE TITLE
Not found 404 when click Camera, Label or Zones in Events

### ISSUE THREAD

**Issue by artlov** [blakeblackshear/frigate#607]
**Describe the bug**
Being in Frigate NVR Beta -> Events screen clicking on Camera, Label or Zones link leads to the "404: Not Found" screen.

**Version of frigate**
Latest beta (0.8.0-rc5-amd64)

**Config file**
```yaml
{
  "cameras": {
    "aicam": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "retain": {
          "default": 10,
          "objects": {
            "person": 10
          }
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 10
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.2.33:554/user=user&password=pass&channel=1&stream=1.cgi -c copy -f flv rtmp://127.0.0.1/live/aicam -r 6 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.2.33:554/user=user&password=pass&channel=1&stream=0.cgi -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /media/frigate/recordings/aicam-%Y%m%d%H%M%S.mp4 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/aicam-%Y%m%d%H%M%S.mp4",
          "roles": [
            "clips",
            "record"
          ]
        }
      ],
      "fps": 6,
      "frame_shape": [
        480,
        704
      ],
      "height": 480,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 80,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "timestamp": true
      },
      "name": "aicam",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "retain_days": 2
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": true,
        "height": null,
        "retain": {
          "default": 10,
          "objects": {
            "person": 10
          }
        },
        "timestamp": false
      },
      "width": 704,
      "zones": {
        "majatagune": {
          "coordinates": "202,258,151,279,190,480,680,480,489,243,443,209,459,131,194,159",
          "filters": {}
        }
      }
    },
    "hik1": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "retain": {
          "default": 10,
          "objects": {
            "person": 10
          }
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 10
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:passPF@192.168.2.37:554/Streaming/Channels/102 -c copy -f flv rtmp://127.0.0.1/live/hik1 -r 6 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.2.37:554/Streaming/Channels/101 -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /media/frigate/recordings/hik1-%Y%m%d%H%M%S.mp4 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/hik1-%Y%m%d%H%M%S.mp4",
          "roles": [
            "clips",
            "record"
          ]
        }
      ],
      "fps": 6,
      "frame_shape": [
        360,
        640
      ],
      "height": 360,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 60,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "timestamp": true
      },
      "name": "hik1",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "retain_days": 2
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": true,
        "height": null,
        "retain": {
          "default": 10,
          "objects": {
            "person": 10
          }
        },
        "timestamp": false
      },
      "width": 640,
      "zones": {
        "parkimine": {
          "coordinates": "185,360,577,360,394,137,123,258",
          "filters": {}
        },
        "trepp": {
          "coordinates": "208,200,368,139,321,66,206,63",
          "filters": {}
        }
      }
    },
    "hik2": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": true,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "retain": {
          "default": 10,
          "objects": {
            "person": 10
          }
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 10
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.2.36:554/Streaming/Channels/102 -c copy -f flv rtmp://127.0.0.1/live/hik2 -r 6 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel fatal -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://user:pass@192.168.2.36:554/Streaming/Channels/101 -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /media/frigate/recordings/hik2-%Y%m%d%H%M%S.mp4 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/hik2-%Y%m%d%H%M%S.mp4",
          "roles": [
            "clips",
            "record"
          ]
        }
      ],
      "fps": 6,
      "frame_shape": [
        360,
        640
      ],
      "height": 360,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 60,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "timestamp": true
      },
      "name": "hik2",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "retain_days": 2
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": true,
        "height": null,
        "retain": {
          "default": 10,
          "objects": {
            "person": 10
          }
        },
        "timestamp": false
      },
      "width": 640,
      "zones": {
        "autovärav": {
          "coordinates": "0,360,280,360,299,120,280,0,0,48,58,150",
          "filters": {}
        }
      }
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 5,
      "objects": {
        "person": 10
      }
    },
    "tmpfs_cache_size": "256m"
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral": {
      "device": "usb:0",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {
      "frigate.edgetpu": "INFO",
      "frigate.mqtt": "DEBUG"
    }
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "core-mosquitto.local.hass.io",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "frigate"
  },
  "snapshots": {
    "retain": {
      "default": 5,
      "objects": {
        "person": 10
      }
    }
  }
}
```

**Computer Hardware**
 - OS: Debian 10
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired
