### ISSUE TITLE
[Config Support]: RTSP Unauthorized

### ISSUE THREAD

**Issue by customstudioyandexru** [blakeblackshear/frigate#6070]
### Describe the problem you are having

After installing WebRTC Camera in Frigate, one of the four cameras stopped showing.
does not work Camera_1 

### Version

 0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.134
  user: Alex
  password: 123
  

      
cameras:
  camera_1: # <------ Name the camera
    mqtt:
      crop: True
      height: 500
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://root:Alex@192.168.1.62:554/user=admin&password=Alex&channel=1&stream=0.sdp? # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
            - clips
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 14
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - bird
        - cat
        - dog
      filters:
        person:
          min_score: 0.6 # min score for object to initiate tracking (default: 0.5
          threshold: 0.7 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
        car:
          threshold: 0.7
      mask:
        - 880,73,884,32,1280,26,1280,67
        - 112,175,556,134,554,327,123,360
    zones:
      parking:
        coordinates: 470,315,264,334,190,569,413,685,710,680,883,540,1236,525,1241,307,875,150,461,175
        objects:
          - car
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        objects:
          - person
        retain:
            default: 10
            mode: motion

  camera_2: # <------ Name the camera
    mqtt:
      crop: True
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://admin:Alex@192.168.1.56:8554/Streaming/Channels/101 # <----- Update for your camera
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 15


  camera_3: # <------ Name the camera
    mqtt:
      crop: True
      height: 500
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:Alex@192.168.1.112:554/1 # <----- Update for your camera
          roles:
            - detect
            - record
            - clips
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 14
    objects:
      track:
        - person
        - car
        - bird
        - cat
        - dog
      filters:
        person:
          min_score: 0.8 # min score for object to initiate tracking (default: 0.5
          threshold: 0.7 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
        car:
          threshold: 0.6
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        objects:
          - person
        retain:
            default: 10
            mode: motion
    motion:
      mask:
        - 732,385,775,466,644,489,617,390


  camera_4: # <------ Name the camera
    mqtt:
      crop: True
      height: 500
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:Alex@192.168.1.79:554/1 # <----- Update for your camera
          roles:
            - detect
            - record
            - clips
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 14
    objects:
      track:
        - person
        - car
        - bird
        - cat
        - dog
      filters:
        person:
          min_score: 0.8 # min score for object to initiate tracking (default: 0.5
          threshold: 0.7 # min decimal percentage for tracked object's computed score to be considered a true positive (default: 0.7)
        car:
          threshold: 0.6
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        objects:
          - person
        retain:
            default: 10
            mode: motion
```

### Relevant log output

```shell
2023-04-14 13:20:51.347689518  [2023-04-14 16:20:51] ffmpeg.camera_1.detect         ERROR   : rtsp://*:*@192.168.1.62:554/user=admin&password=Alexey%211&channel=1&stream=0.sdp?: Server returned 401 Unauthorized (authorization failed)
2023-04-14 13:20:51.391548070  [2023-04-14 16:20:51] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
2023-04-14 13:20:51.391553343  [2023-04-14 16:20:51] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
2023-04-14 13:21:01.356853397  [2023-04-14 16:21:01] watchdog.camera_1              ERROR   : Ffmpeg process crashed unexpectedly for camera_1.
2023-04-14 13:21:01.356859474  [2023-04-14 16:21:01] watchdog.camera_1              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-14 13:21:01.356861080  [2023-04-14 16:21:01] ffmpeg.camera_1.detect         ERROR   : [rtsp @ 0x5641c19f7100] method DESCRIBE failed: 401 Unauthorized
2023-04-14 13:21:01.356862996  [2023-04-14 16:21:01] ffmpeg.camera_1.detect         ERROR   : rtsp://*:*@192.168.1.62:554/user=admin&password=Alexey%211&channel=1&stream=0.sdp?: Server returned 401 Unauthorized (authorization failed)
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

Frigate shows four camera shot windows. 
3 I can see well. 1 - black square and inscription:
**no frames have been received check error logs**
