### ISSUE TITLE
[Detector Support]: USB Coral not found 

### ISSUE THREAD

**Issue by sanderlv** [blakeblackshear/frigate#6072]
### Describe the problem you are having

2023-04-14 14:22:59.362199506  [2023-04-14 14:22:55] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb

2023-04-14 14:22:59.362663616  [2023-04-14 14:22:59] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

root@frigate-02:/frigate/compose# lsusb
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp.

### Version

cant get so far

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/custom_model.tflite"
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config/config.yml:/config/config.yml
      - /frigate/media:/media/frigate
      - /frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
2023-04-14 14:22:59.362199506  [2023-04-14 14:22:55] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb

2023-04-14 14:22:59.362663616  [2023-04-14 14:22:59] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by sanderlv** [comment]
Is has all the power it needs...

**Comment by NickM-27** [comment]
What device are you running it on? It's very common for it to not be getting enough power when running on a device like the RPi or a laptop. 

And in any case, it needs to show as Google Inc. for frigate to be able to load it.

**Comment by sanderlv** [comment]
Intel NUC12

**Comment by blakeblackshear** [comment]
Try moving `- /dev/bus/usb:/dev/bus/usb` to volumes instead of devices.

**Comment by isaacsanfran** [comment]
@blakeblackshear as a data point, your suggestion above worked for me while troubleshooting the same issue.  

(For anyone else reading, Unraid's template calls it a "Path" rather than Docker's nomenclature of "Volumes")

**Comment by sanderlv** [comment]
> @blakeblackshear as a data point, your suggestion above worked for me while troubleshooting the same issue.
> 
> (For anyone else reading, Unraid's template calls it a "Path" rather than Docker's nomenclature of "Volumes")

What does your config look like? (Comppse)

**Comment by sanderlv** [comment]
> Try moving `- /dev/bus/usb:/dev/bus/usb` to volumes instead of devices.

Can you help me how to find the correct line for compose?

**Comment by NickM-27** [comment]
Instead of a device, make it a volume 

```yaml

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config/config.yml:/config/config.yml
      - /frigate/media:/media/frigate
      - /frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

```
