### ISSUE TITLE
[Support]: Birdseye restream spinup time

### ISSUE THREAD

**Issue by hawkeye217** [blakeblackshear/frigate#6073]
### Describe the problem you are having

I have a Roku TV that I want to stream birdseye to, using the `motion` mode. Roku has a simple app available to display mjpeg streams from IP cameras (called IP Camera Viewer - Basic). I'm setting up an automation in HA that essentially will display the restreamed birdseye view on the TV from an Alexa command. I've set that up without a problem. I'm using an additional line in my go2rtc config to convert the birdseye stream to mjpeg:

```
go2rtc:
  streams:
    birdseyemjpeg: 
      - ffmpeg:birdseye#video=mjpeg
      ...
```

Once go2rtc brings up the stream (sometimes that takes a bit), it all works. I can use the mjpeg link from go2rtc and put that in the Roku app and I can see the birdseye stream on the TV.

The problem comes when the stream in go2rtc is inactive for a while. It takes some time for go2rtc to begin generating the rtsp stream, and then takes more time for the mjpeg stream to spin up. This causes the Roku app to timeout with an error.

I've noticed a faster spinup in go2rtc when birdseye is already streaming something (whether it be from motion or if it's set on continuous). Obviously when it's streaming something more than the birdseye logo, the framerate coming from the birdseye pipe jumps to 10fps (up from 1fps when there's no motion), so I wonder if this is contributing to my issue. 

Maybe this could be fixed with some sort of ffmpeg arg or something in go2rtc to generate a more consistent framerate and thus avoid any delays/buffering in the spinup of the mjpeg stream for the Roku.

I realize my use case is unique, and with go2rtc now in Frigate, I might be able to just use that to craft a better solution rather than making changes to birdseye code.

Let me know if you have any thoughts or ideas!

### Version

0.12.0-7d589bd

### Frigate config file

```yaml
...
go2rtc:
  streams:
    birdseyemjpeg: 
      - ffmpeg:birdseye#video=mjpeg
      ...
...
```

### Relevant log output

```shell
--
```

### FFprobe output from your camera

```shell
--
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
It's definitely a known issue that it is slower to startup when there is only the logo showing, this is the case for h264 as well. I'd suggest looking in go2rtc config to see what the ffmpeg command is and then use that directly for your mjpeg camera so it is not dependent on two ffmpeg processes spinning up. 

We are already planning on a birdseye revamp at some point in the future and this will be improved at that point.

**Comment by hawkeye217** [comment]
This is the command I can run inside the container to watch the fps changes in realtime:

``
ffmpeg -hide_banner -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD129 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -f mp4 foo.mp4
``

The go2rtc config runs the birdseye command from frigate:

``
  birdseye: exec:ffmpeg -hide_banner -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device
    /dev/dri/renderD129 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i
    /tmp/cache/birdseye -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v
    0 -an -vf format=vaapi|nv12,hwupload -rtsp_transport tcp -f rtsp {output}
  birdseyemjpeg:
  - ffmpeg:birdseye#video=mjpeg
 ``

Go2rtc reads from the birdseye pipe, and that's the issue - the pipe is only dripping 1fps when the logo is displayed, then 10fps when motion frames are written to the pipe.

So where would you suggest I run ffmpeg to generate the mjpeg stream? I might be mistaken, but go2rtc requires rtsp output from ffmpeg, which is why I just set up another go2rtc stream for mjpeg.

**Comment by NickM-27** [comment]
I'm suggesting instead of using ffmpeg:birdseye which means the birdseye stream has to start before your mjpeg stream can start, you create a manual ffmpeg command that outputs mjpeg directly reading from the birdseye pipe, skipping the step of the h264 stream needing to start first (and reducing load overall)

**Comment by hawkeye217** [comment]
Right. I don't know how to make ffmpeg output mjpeg within rtsp - though I know it's possible because some Dahua cameras do mjpeg via rtsp as a substream.

Off to google for a bit... 😂

**Comment by NickM-27** [comment]
It should be the same just -c:v mjpeg_vaapi instead. Although vaapi may not support mjpeg output in which case you'd need to use software. You can also enable trace logs for exec on go2rtc and see the ffmpeg command in the logs

**Comment by hawkeye217** [comment]
I'm definitely missing something.

```
go2rtc:
  log:
    level: debug
    exec: trace
  streams:
    birdseyemjpeg: 
      - exec:ffmpeg -hide_banner -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD129 -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v mjpeg_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf format=vaapi|nv12,hwupload -rtsp_transport tcp -f rtsp {output}
```

I get this:

```
Input #0, rawvideo, from '/tmp/cache/birdseye':
  Duration: N/A, bitrate: 110592 kb/s
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 110592 kb/s, 10 tbr, 10 tbn
At least one output file must be specified
```

Removing hwaccel and using this causes go2rtc to not even come up, nothing in the go2rtc log either (even with log level: debug):

``
 streams:
    birdseyemjpeg: 
      - "exec:ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -r 10 -i /tmp/cache/birdseye -c:v mjpeg -r 10 -rtsp_transport tcp -f rtsp {output}"
```
