### ISSUE TITLE
[Support]: Frigate 0.12 does not start in LXC unprivileged enviroment

### ISSUE THREAD

**Issue by ivlis** [blakeblackshear/frigate#6075]
### Describe the problem you are having

Frigate cannot start after updating to 0.12. The  same setup works perfectly for 0.11.1

Docker compose config:

```yaml
  frigate:
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0
    # privileged: true
    shm_size: "512mb" 
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/bus/usb # usb for coral
    user: root
    group_add:
      - "105"
    volumes:
      - /etc/localtime:/localtime:ro
      - /config.yml:/config/config.yml:ro
      - /frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "9999:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "<>"
      LIBVA_DRIVER_NAME: "iHD"
      TZ: America/New_York
```

### Version

0.12.0

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
frigate-frigate-1  | s6-rc: info: service s6rc-fdholder: starting
frigate-frigate-1  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-frigate-1  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-frigate-1  | s6-rc: info: service fix-attrs: starting
frigate-frigate-1  | s6-rc: info: service s6rc-fdholder successfully started
frigate-frigate-1  | s6-rc: info: service fix-attrs successfully started
frigate-frigate-1  | s6-rc: info: service legacy-cont-init: starting
frigate-frigate-1  | s6-rc: info: service legacy-cont-init successfully started
frigate-frigate-1  | s6-rc: info: service log-prepare: starting
frigate-frigate-1  | chown: changing ownership of '/dev/shm/logs/frigate': Invalid argument
frigate-frigate-1  | chown: changing ownership of '/dev/shm/logs/go2rtc': Invalid argument
frigate-frigate-1  | chown: changing ownership of '/dev/shm/logs/nginx': Invalid argument
frigate-frigate-1  | s6-rc: warning: unable to start service log-prepare: command exited 1
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA
