### ISSUE TITLE
[Config Support]: Having trouble configuring go2rtc

### ISSUE THREAD

**Issue by leecosta466** [blakeblackshear/frigate#6081]
### Describe the problem you are having

I am having trouble configuring go2rtc and having a few errors in the logs. I am trying to enable it for the first time and have added the configuration as directed by the documentation (see the first section of the configuration/driveway_cam).

Am I not doing it right?

### Version

0.12

### Frigate config file

```yaml
##########################################################
## Driveway
##########################################################

cameras:
  driveway_cam:
    rtmp:
      enabled: False

    go2rtc:
      streams:
        driveway_cam:
          - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0

    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record

    detect:
      width: 3840
      height: 2160
      fps: 10
      enabled: True

    zones:
      driveway:
        coordinates: 2141,2160,1881,1405,2067,1347,3840,1796,3840,2160
        objects:
          - person
          - animal
      street:
        coordinates: 2528,1432,2806,1297,3840,1545,3840,1761
        objects:
          - person
          - animal
          - car

    objects:
      track:
        - person
        - animal
        - car
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 40000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          mask:
            - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0
        car:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 200000
          mask:
            - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0
        animal:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 1000
          mask:
            - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0

    motion:
      # Increasing this value will make motion detection less sensitive
      # threshold: 30
      # default 25

      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35
      # default: 30
      mask:
       - 0,0,0,2160,2098,2160,1850,1401,2470,1223,3840,1537,3840,0

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
#        max_seconds: 240 Deprecated in 0.11
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person
          - car
          - animal
        required_zones:
          - driveway
          - street

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      required_zones:
        - driveway
        - street
      retain:
        default: 7

##########################################################
## Backyard
##########################################################

  backyard_cam:
    rtmp:
      enabled: False

    detect:
      width: 3840
      height: 2160
      fps: 10
      enabled: True

    motion:
      # Increasing this value will make motion detection less sensitive
      threshold: 30
      # default 25

      # Minimum size in pixels in the resized motion image that counts as motion.
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 15 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      # contour_area: 35 
      # default: 30

      mask:
        - 3840,600,3538,538,3434,1293,2992,1173,3012,705,2268,712,1363,782,1068,848,1130,1173,852,1231,790,890,225,1130,0,1215,0,0,3840,0
        - 3840,1966,3840,2160,3163,2160,3163,1970
        - 3782,1374,3751,1634,3488,1560,3538,1308
        - 2775,1359,3050,1537,3205,1301,2938,1212

    objects:
      track:
        - person
        - animal
      filters:
        animal:
          min_area: 1000
          max_area: 100000
          mask:
            - 3840,600,3314,511,3290,1185,2992,1095,3012,705,2268,712,1363,782,1068,848,1130,1173,852,1231,790,890,225,1130,0,1215,0,0,3840,0
            - 3840,1966,3840,2160,3163,2160,3163,1970
            - 3782,1374,3751,1634,3488,1560,3538,1308
            - 2880,1347,3046,1463,3205,1301,2938,1212
        person:
          min_area: 10000
          # max_area: 100000
          mask:
            - 3840,600,3314,511,3290,1185,2992,1095,3012,705,2268,712,1363,782,1068,848,1130,1173,852,1231,790,890,225,1130,0,1215,0,0,3840,0
            - 3840,1966,3840,2160,3163,2160,3163,1970
            - 3782,1374,3751,1634,3488,1560,3538,1308
            - 2880,1347,3046,1463,3205,1301,2938,1212
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.15:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record

    record:
      enabled: True
      retain:
        days: 7
        mode: active_objects
      events:
#        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person
          - animal

##########################################################
## Living Room
##########################################################

  living_room_cam:
    rtmp:
      enabled: False

    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.141.16:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record

    motion:
      mask:
        - 1641,207,1661,615,1239,586,1250,267
        - 1862,0,1434,0,1440,99,1860,105

    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 1641,207,1661,615,1239,586,1250,267
            - 1862,0,1434,0,1440,99,1860,105

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True

    objects:
      track:
        - person

    record:
      enabled: True
      retain:
        days: 0
        # mode: active_objects
      events:
#        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
          mode: active_objects
        objects:
          - person

#########################################################
## Global
#########################################################

mqtt:
  host: 192.168.141.21
  user: REDACTED
  password: REDACTED
  

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 7

#model:
#  labelmap:
#    15: animal
#    16: animal
#    17: animal
#    18: animal
#    19: animal
#    20: animal
#    21: animal
#    22: animal
#    23: animal
#    24: animal

birdseye:
  enabled: False
  # width: 1920
  # height: 1080
  # quality: 8
  # mode: motion
```

### Relevant log output

```shell
frigate    | 2023-04-14 16:20:28.631362936  *************************************************************
frigate    | 2023-04-14 16:20:28.631364408  ***    Config Validation Errors                           ***
frigate    | 2023-04-14 16:20:28.631379421  *************************************************************
frigate    | 2023-04-14 16:20:28.631380337  'ffmpeg'
frigate    | 2023-04-14 16:20:28.632386794  Traceback (most recent call last):
frigate    | 2023-04-14 16:20:28.632388997    File "/opt/frigate/frigate/app.py", line 351, in start
frigate    | 2023-04-14 16:20:28.632389969      self.init_config()
frigate    | 2023-04-14 16:20:28.632391025    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate    | 2023-04-14 16:20:28.632391993      user_config = FrigateConfig.parse_file(config_file)
frigate    | 2023-04-14 16:20:28.632393033    File "/opt/frigate/frigate/config.py", line 1072, in parse_file
frigate    | 2023-04-14 16:20:28.632393994      return cls.parse_obj(config)
frigate    | 2023-04-14 16:20:28.632395039    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
frigate    | 2023-04-14 16:20:28.632396098    File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
frigate    | 2023-04-14 16:20:28.632397188    File "pydantic/main.py", line 1076, in pydantic.main.validate_model
frigate    | 2023-04-14 16:20:28.632399803    File "pydantic/fields.py", line 886, in pydantic.fields.ModelField.validate
frigate    | 2023-04-14 16:20:28.632400961    File "pydantic/fields.py", line 1021, in pydantic.fields.ModelField._validate_mapping_like
frigate    | 2023-04-14 16:20:28.632421694    File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
frigate    | 2023-04-14 16:20:28.632422820    File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
frigate    | 2023-04-14 16:20:28.632430068    File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
frigate    | 2023-04-14 16:20:28.632431256    File "pydantic/fields.py", line 1151, in pydantic.fields.ModelField._apply_validators
frigate    | 2023-04-14 16:20:28.632432508    File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
frigate    | 2023-04-14 16:20:28.632433564    File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
frigate    | 2023-04-14 16:20:28.632441272    File "/opt/frigate/frigate/config.py", line 632, in __init__
frigate    | 2023-04-14 16:20:28.632442326      if len(config["ffmpeg"]["inputs"]) == 1:
frigate    | 2023-04-14 16:20:28.632443225  KeyError: 'ffmpeg'
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB
